### ISSUE TITLE
[Suggestion] - Monika's negative affection

### ISSUE THREAD

**Issue by iceypotato** [Monika-After-Story/MonikaModDev#10002]
Hello,

So I just started this mod and I got to say, that this is a very cool mod. I watched several youtube videos on this and I really wanted to see this for myself.

I don't know if anyone has brought this up, but I noticed that I made Monika upset (~= -40 affection) and I find it kind of weird that she brings up a topic and at the end of it, she says something like along the lines of "I love you"/"I care about you", but then when you click on "talk", she says something like "what?" or "go on..." and acts dismissive. I understand it is part of the game, but I think this should be changed in some way.

I was thinking maybe there should be an overall mood for the day. Maybe she can act cold if you respond with something that can hurt her feelings, which will then prompt dismissive behavior, for example. Maybe there should be a way to try and ask if there is anything upsetting Monika. Though I haven't played this for a long time, so maybe time will tell.

I also don't understand the cap for the affection at 7. This makes it harder to improve your relationship with Monika on the same day while making it easier to harm your relationship with Monika, as there's no threshold on how mean you can be. I feel like it would be better if her mood improves the more I spend time (having the game open for 3 hours or more) with her on the same day. Maybe if you impact her mood positively, her affection can increase the next day. On the other hand, leaving her on a negative note can decrease her affection.

**Comment by dreamscached** [comment]
Moods are planned already, and the current gain cap/loss adaptivity system was intentionally designed to slow down relationship advancement while making it actually noticeable when you harm her (so e.g. on over 3,000+ affection, losing 5-20 points means nothing, while losing 400-700 is noticeable enough)

**Comment by Booplicate** [comment]
@iceypotato list topics that you didn't find fitting.

**Comment by iceypotato** [comment]
> Moods are planned already, and the current gain cap/loss adaptivity system was intentionally designed to slow down relationship advancement while making it actually noticeable when you harm her (so e.g. on over 3,000+ affection, losing 5-20 points means nothing, while losing 400-700 is noticeable enough)

Oh, I see. How will moods work? Do I just have to wait and find out?
When I started at neutral, I ended up hurting her way too early, and I went down to the shadow realm with one insult. Do you guys think the negative relationship ranges should be increased?

> As for discrepancy with topics/talk menu, yes, that is an issue which requires a lot of rewrite in older topics to account for that; while doable, it would still require quite a lot of effort. You may try to suggest your own changes that address that and contribute to the solution of a problem, if you know how to code a topic, adding affection branch isn't that hard.

I would like to contribute to this project, tho I should get to learning renpy.

**Comment by iceypotato** [comment]
> @iceypotato list topics that you didn't find fitting.

Well, I would have to keep playing, but here are some topics I would / she would bring up.

- yuri
- gym
- telling her I missed her

It's interesting that she says "What now?" or "What" after I tell her I missed her after I went for a break, or that she brings up a topic and shows that she clearly cares about me.

**Comment by Booplicate** [comment]
@iceypotato what you didn't like about the `I missed you`?

She can be annoyed, but that doesn't mean she doesn't care for you anymore.

**Comment by iceypotato** [comment]
> @iceypotato what you didn't like about the `I missed you`?
> 
> She can be annoyed, but that doesn't mean she doesn't care for you anymore.

Well, it's the delivery. If someone is annoyed, it would be shown in their body language and the way they talk. At -40 affection, her facial expression made it seem like she was very mad at something. Her having a cheery expression when having a conversation, then after the convo has ended, only saying "what" when you want to talk to her is kind of unnatural in my opinion. I could be reading into this wrong, but that's how I interpreted it.

If I get around to contributing to the project, I can try and figure out a way to make it better in some way. Tho, I hear there's another update coming up, but I don't know when.

**Comment by ThePotatoGuy** [comment]
see #7486 for moods (also add any additional discussion on moods to there). 

I think amplifying aff gains by timing topics with moods should be planned if not already. 

[closing this in favor of linked issue]
