### ISSUE TITLE
Big idea: coding minigame

### ISSUE THREAD

**Issue by Chamelllemon** [Monika-After-Story/MonikaModDev#10003]
A coding-minigame, and in-game submods, like, Monika would explain the coding fot the player and even make a minigame for them, and then the player could go looking through the files to find other games or mechanics scattered around, like making a coffee for her. Some could be made by Monika and some not, I don't know how to explaing this properly so if I did a bad job at it I'd like to explain it better next time

**Comment by ThePotatoGuy** [comment]
this is pretty ambitious, doesn't seem very feasible tbh. The mod already has a feature to teach coding (although its somewhat outdated now), and I think we should focus on finishing/adding to that instead off trying to make a game ver.

[closing as rejected]
