### ISSUE TITLE
Monika keeps saying "I cant find any songs." But I can play the music on the game but she cant see it. help?

### ISSUE THREAD

**Issue by AssaultivePrime** [Monika-After-Story/MonikaModDev#10014]

**Comment by Wingdinggaster656** [comment]
When describing how to add music, Monika stated:

```
Then either let me know that you added some music or restart the game.
```

You probably restarted the game, so your music are already in the game now --  and since they are already in the game, it is natural that Monika says "can't find any songs".

**Comment by Booplicate** [comment]
When does she say that? How are you playing the music?

**Comment by AssaultivePrime** [comment]
@Booplicate Yeah, I can play the music on the music section of the game, but when I ask monika to check theres any new songs, she says theres no new song 
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/135458096/40d2fdbc-5d17-4aca-93d9-bac092e51d32)

**Comment by AssaultivePrime** [comment]
@Wingdinggaster656 Okay, Imma try that with a new music

**Comment by AssaultivePrime** [comment]
@Wingdinggaster656 thanks, that worked very well
