### ISSUE TITLE
New song suggestion: It's Such A Pretty World Today

### ISSUE THREAD

**Issue by megaclover** [Monika-After-Story/MonikaModDev#10011]
Was reminiscing on Breaking Bad and the songs they used in the show when I came across Nancy Sinatra's version of "It's Such a Pretty World Today." It was used in S2EP4 at the end when Skylar exited the convenience store. 

Lyrics:

It's such a pretty world today
Look at the sunshine (look at the sunshine)
And every day's the same since I met you

It's such a pretty world today
Knowing that you're mine (knowing that you're mine)
And happiness is being close to you

And though the rain may fall my skies will all be blue
And if I look close enough the sun will come shining through

Link to song: https://www.youtube.com/watch?v=LNdUKEzkw9s

Figured that it may fit as one of Monika's random songs. Thoughts?

If needed, I can draft up the necessary code. It may take a while though.

**Comment by TooMuchInvigilation** [comment]
Sounds great! I think it would fit well.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

I recommend just adding it yourself as a submod. I don't think we'll be adding a lot of songs anytime soon.
