### ISSUE TITLE
Changing birthday.

### ISSUE THREAD

**Issue by nicnicnicninc** [Monika-After-Story/MonikaModDev#10016]
so i am 18 years of age and whilst doing the birthday dialogue i accidentally chose my birthday as 2008. I cannot find out how to change it and it is EXTREMELY annoying as i have submods that require me to be 18 years or older, i really hope a way to change birthdays can be implemented (unless there is one already) as i have looked everywhere i can think of, and guess what? nothing. 
i also made a github account to post this issue so i really hope somebody can help me.

**Comment by Booplicate** [comment]
There's no way of changing your birthday because she confirms the date twice. We're planning on adding one.

**Comment by nicnicnicninc** [comment]
> There's no way of changing your birthday because she confirms the date twice. We're planning on adding one.

i read that on your birthday she allows the option to change, if this is true, my birthday is in 9 days so is it possible?

**Comment by Booplicate** [comment]
No, there's no way to do that now.

**Comment by nicnicnicninc** [comment]
> No, there's no way to do that now.

That is disappointing. Thank you for answering my issue though.
