### ISSUE TITLE
Suggestion: Allow disabling of the AI getting easier in games when you lose

### ISSUE THREAD

**Issue by Gr1m5Coding** [Monika-After-Story/MonikaModDev#10012]
I just think it'd be nice because it seems to be weird a lot, like sometimes when I play a game of Pong Monika's paddle moves really slowly even though I just started playing. I just like it more when it's difficult even if I lose whatever game I'm playing more often.

**Comment by ThePotatoGuy** [comment]
hmm maybe a topic where you tell Monika to stop taking it easy on you in games. I like the idea.

[closing until we look into it]
