### ISSUE TITLE
Weird window glitch in MAS

### ISSUE THREAD

**Issue by SpecteralCandle** [Monika-After-Story/MonikaModDev#10021]
Everytime I swipe to another desktop, MAS minimizes.  I'm unable to maximize, minimize or close the tab manually because the window is stuck in fullscreen.  It's not game breaking or anything, but just a bit annoying

I'm on a Mac OS if it helps.

What the hotbar looks like when swiping back to the previous desktop:

![Screen Shot 2023-06-08 at 6 25 52 PM](https://github.com/Monika-After-Story/MonikaModDev/assets/135329716/7e296f2d-6b38-49b5-b947-776d2bcceba3)

**Comment by Booplicate** [comment]
This is a renpy bug, we can't fix it ourselves, but it may get away with py3 migration.
