### ISSUE TITLE
[Suggestion] Change (or remove) the event where Monika thinks you didn't listen to her graduation speech.

### ISSUE THREAD

**Issue by MagicianPatchouli** [Monika-After-Story/MonikaModDev#10035]
So after Monika gives you her graduation speech, she asks you what you think of it. You only seem to have a couple seconds to reply before she complains that you didn't listen, and this timer isn't apparent. I did listen to it, but I didn't really like it and none of the options represented how I felt about it. I ended up thinking to myself for a minute, unaware that I was on a timer, and got penalized. I feel as though the speech _should_ be something that you take time to think about, so the timer is inappropriate. I think making it more forgiving (either by lengthening the timer or adding a failsafe that checks if you're there), or just removing it entirely would make the event more fair.

**Comment by Booplicate** [comment]
Already working on improving the timer.
