### ISSUE TITLE
[Suggestion] Rainy mood outside the windows

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1003]
I think that Rainy mood could be something pretty sweet in MAS

Say for example, rain would have a 35% chance of appearing instead of a daytime

And there could be a 15% chance that rain turns into a thunderstorm.

I can make the art for these two, but I have no idea how to code that in. If you, devs, feel like this can idea could be in the game, give me a task or something, idk how github works, and I will try to come up with the art for the weather : )

**Comment by IlywI** [comment]
i think it is also possible to set weather according to your location so it reflects upon the actual weather you are experiencing currently.
(maybe thru ip address? idk i'm just bullshitting)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Could possibly be done through weather.com (not without some excessive python tho).
The only problem is that it would need a countrycode to function and I have no idea how to retrieve that.
It would probably be possible to fetch a user's ip through some third party service and then have the game determine the user's country by it and retrieve a country code from a table of countries.
There are two big problems with it tho.
Firstly the ip adress does not always correspond to a user's physical location (but that's not so critical, really).
And secondly, MAS has a very thin line on which features are okay and which could be deemed too intrusive or disturbing (and for a good reasons), and this would certainly be too much.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Has all the possible reasons to be too much, really.
- [x] Fetching things from the internet
- [x] Excessive python
- [x] Requires third party services
- [x] Requires user's location info

**Comment by sebastianN01** [comment]
Well, I still am going to make rain weather and make a pull request and go with what I said in the first post:

"Say for example, rain would have a 35% chance of appearing instead of a daytime

And there could be a 15% chance of a thunderstorm."

**Comment by sebastianN01** [comment]
Could be useful to have someone write some dialogue about the weather change aswell, and perhaps, some disturbing dialogue if thunderstorm comes up (chance for a good one time jumpscare)

**Comment by sebastianN01** [comment]
OK, I got the files

**Comment by sebastianN01** [comment]
![arms-crossed-r](https://user-images.githubusercontent.com/36047607/36132632-b21aec9c-1078-11e8-9fad-a33b2f63386d.png)
![arms-pointright-r](https://user-images.githubusercontent.com/36047607/36132633-b23653f6-1078-11e8-80c5-a4b128b328cc.png)
![arms-restleftpointright-r](https://user-images.githubusercontent.com/36047607/36132634-b251dcc0-1078-11e8-863c-e2d44da9ad70.png)
![arms-restleft-r](https://user-images.githubusercontent.com/36047607/36132635-b26b4926-1078-11e8-96c5-2c29b5bb3173.png)
![arms-steepling-r](https://user-images.githubusercontent.com/36047607/36132636-b288c1cc-1078-11e8-97eb-bdc38e96cd08.png)
![body-leaning-r](https://user-images.githubusercontent.com/36047607/36132637-b2a499d8-1078-11e8-97ac-5611fd0bd8f6.png)
![face-eyebrows-knit-r](https://user-images.githubusercontent.com/36047607/36132638-b2bfe2c4-1078-11e8-80b8-b2c636c20c7c.png)
![face-eyebrows-mid-r](https://user-images.githubusercontent.com/36047607/36132639-b2dcb66a-1078-11e8-8208-a5848a9e580e.png)
![face-eyebrows-up-r](https://user-images.githubusercontent.com/36047607/36132640-b2f50f62-1078-11e8-80d8-9b69ae694e83.png)
![face-eyes-closedhappy-r](https://user-images.githubusercontent.com/36047607/36132641-b326c6ba-1078-11e8-8ee5-e4b27db62f36.png)
![face-eyes-closedsad-r](https://user-images.githubusercontent.com/36047607/36132642-b347a1c8-1078-11e8-8b5b-446463e6cdd0.png)
![face-eyes-left-r](https://user-images.githubusercontent.com/36047607/36132643-b3630b66-1078-11e8-9e88-61acf89504ba.png)
![face-eyes-normal-r](https://user-images.githubusercontent.com/36047607/36132644-b3884732-1078-11e8-92ab-109511e78526.png)
![face-leaning-eyebrows-knit-r](https://user-images.githubusercontent.com/36047607/36132645-b3a03ebe-1078-11e8-9692-dcf04a82b748.png)
![face-leaning-eyebrows-mid-r](https://user-images.githubusercontent.com/36047607/36132646-b3ba4cbe-1078-11e8-9e04-3d929ca9bb55.png)
![face-leaning-eyebrows-up-r](https://user-images.githubusercontent.com/36047607/36132647-b3d5e014-1078-11e8-9d25-f701050d1e11.png)
![face-leaning-eyes-closedhappy-r](https://user-images.githubusercontent.com/36047607/36132648-b3f40a94-1078-11e8-9bd2-f72cf4000bdd.png)
![face-leaning-eyes-closedsad-r](https://user-images.githubusercontent.com/36047607/36132649-b40e31da-1078-11e8-81c1-a9af043bd145.png)
![face-leaning-eyes-left-r](https://user-images.githubusercontent.com/36047607/36132650-b427d284-1078-11e8-8792-363c09a145f6.png)
![face-leaning-eyes-normal-r](https://user-images.githubusercontent.com/36047607/36132651-b4475d2a-1078-11e8-828e-4fbf664ab4d1.png)
![face-leaning-mouth-big-r](https://user-images.githubusercontent.com/36047607/36132652-b465cbd4-1078-11e8-81da-3ffacb3d81e1.png)
![face-leaning-mouth-small-r](https://user-images.githubusercontent.com/36047607/36132653-b483f320-1078-11e8-81e9-8d7b7913803c.png)
![face-leaning-mouth-smile-r](https://user-images.githubusercontent.com/36047607/36132654-b4a09296-1078-11e8-8306-d83975725c58.png)
![face-leaning-mouth-smirk-r](https://user-images.githubusercontent.com/36047607/36132655-b4bfede4-1078-11e8-913f-4bcc58d78d9c.png)
![face-leaning-nose-r](https://user-images.githubusercontent.com/36047607/36132656-b4dc11fe-1078-11e8-941c-4d5faf53b4f5.png)
![face-leaning-sweatdrop-r](https://user-images.githubusercontent.com/36047607/36132657-b4fa367a-1078-11e8-9b8c-135cf07f32d6.png)
![face-mouth-big-r](https://user-images.githubusercontent.com/36047607/36132658-b51af7de-1078-11e8-85d3-a4305779b877.png)
![face-mouth-small-r](https://user-images.githubusercontent.com/36047607/36132659-b534b354-1078-11e8-8ad6-6158b6979ef2.png)
![face-mouth-smile-r](https://user-images.githubusercontent.com/36047607/36132661-b5515946-1078-11e8-8ecd-7db15b4e05c9.png)
![face-mouth-smirk-r](https://user-images.githubusercontent.com/36047607/36132662-b56db7d0-1078-11e8-8e61-52780b680702.png)
![face-nose-r](https://user-images.githubusercontent.com/36047607/36132663-b58638f0-1078-11e8-8b6b-c529d3db9c84.png)
![face-sweatdrop-r](https://user-images.githubusercontent.com/36047607/36132664-b59f43ea-1078-11e8-816c-44fac662defe.png)
![monika_day_room_rain](https://user-images.githubusercontent.com/36047607/36132665-b5c03c8a-1078-11e8-9a54-c5e50e516df0.png)
![monika_day_room_rain_strike](https://user-images.githubusercontent.com/36047607/36132666-b5dfbda8-1078-11e8-8d38-4825b9abe75b.png)
![rain_sky](https://user-images.githubusercontent.com/36047607/36132667-b5fd7488-1078-11e8-96ae-e42950d3659e.jpg)
![torso](https://user-images.githubusercontent.com/36047607/36132668-b6173dd2-1078-11e8-8f0d-e1fe45c45249.png)
![window_5_fallback](https://user-images.githubusercontent.com/36047607/36132669-b6302e0a-1078-11e8-8f6c-65c1aaf0a0e5.png)
![window_6_fallback](https://user-images.githubusercontent.com/36047607/36132670-b64a4f6a-1078-11e8-82a9-004a28e6477f.png)

**Comment by sebastianN01** [comment]
[webm-soundfx.zip](https://github.com/Backdash/MonikaModDev/files/1718556/webm-soundfx.zip)

**Comment by ThePotatoGuy** [comment]
Loving the sound + window art.

**Comment by ThePotatoGuy** [comment]
As always, dev team never gives timely feedback.

1. Good work on getting a looping window animation and sound fx. Many people **don't** do that for some reason.
2. Not sure if I like the grey versions of the sprites/background. I think it's just too gray. Kind of makes the mood dark and gloomy instead of calm and peaceful, which is what I'd say in-game rain should be.

**Comment by sebastianN01** [comment]
@ThePotatoGuy Alright, I will give you that, I wanted the room to have a different mood when rain is falling, it could also help to for example: run an event of monika asking about our fears or our mood. Rain could be a chance of adding events that happen not so often, as the rain itself i expected to have a small/medium chance of falling at daytime...

But of course, if the rain could've been added, but not the rooms greyed out version, I would be very happy still :)

**Comment by oniigirii** [comment]
The sound of the rain is very relaxing especially in the Youtube video with _I still love you_ playing in the background. I agree with Potato's comment about being a bit too gray. Would also like to see simple animations on the windows like raindrops hitting on glass for that realistic look, although the sunlight glow on the floor couldn't be animated that easily.

**Comment by sebastianN01** [comment]
I made them, kind off. not as bubbles though, more like strings of lines that falls down the window.

**Comment by sebastianN01** [comment]
@ThePotatoGuy isn't it not inside the folder you downloaded? I mean I can try and make it look sharper though..

**Comment by sebastianN01** [comment]
@PopeAesthetics thank you for kind word. :P and as for the windows, its cool, I do also love some mountain or something else outside windows, go and make your own issue suggesting it! i will try to focus this issue on the rain I made.

**Comment by sebastianN01** [comment]
@ThePotatoGuy isn't it inside the zip file you can download here? Whatever, I will make them better looking right now, much better. oh and also, I've noticed there is a blue_sky.jpg file, so I decided to do a rain_sky.jpg which is in zip file with monika sprites and all that, Plus Here I will reupload rain-strike effect, if there were ever a thunderstorm to hit. (maybe programmed into the game in future)

![monika_day_room_rain_strike](https://user-images.githubusercontent.com/36047607/36424737-ad3558da-1644-11e8-9488-238f520a0eb3.png)
![window_5_fallback](https://user-images.githubusercontent.com/36047607/36424994-96a3db22-1645-11e8-9ee0-1a166c9d2329.png)
![window_6_fallback](https://user-images.githubusercontent.com/36047607/36424996-96c242f6-1645-11e8-9c16-f1a86a5069cb.png)

**Comment by ThePotatoGuy** [comment]
Oh I didn't check the other zip.

**Comment by sebastianN01** [comment]
its ok. these are better than the other one anyway. :)

**Comment by sebastianN01** [comment]
Im glad i could help. this is really quite a niche i found i could put my work into, and im happy for committing to at least that. I hope i find something else to do in future for mas and  your crew. :P

**Comment by ThePotatoGuy** [comment]
We're still having difficulty deciding the best way to transition to rain.

**Comment by IlywI** [comment]
maybe darken the usual morning background and then slowly transition into a darker grey(in like a span of 2 minutes?) with monika saying hmm? it started to rain. [player] do you like rainy days... and so on :V idk

**Comment by sebastianN01** [comment]
I think that the event could be foreseen by monika stating something about the rain and that she might turn it for us if we want it. and have an option to turn it on and off via "ask a question"

**Comment by ThePotatoGuy** [comment]
`IN`

**Comment by sebastianN01** [comment]
Does that mean its in the game? I'm hyped
