### ISSUE TITLE
It's still snowing in the game.

### ISSUE THREAD

**Issue by ArtemYo17** [Monika-After-Story/MonikaModDev#10044]
Before I deleted the game, I logged into it for the last time in December. Recently, I downloaded the game again and she greeted me as usual. In addition, it was still snowing in the game, although it was written on the calendar that it was July.

**Comment by Booplicate** [comment]
Ask Monika to change the weather: `Hey, Monika > Weather > Can you change the weather?`

**Comment by ArtemYo17** [comment]
> Ask Monika to change the weather: `Hey, Monika > Weather > Can you change the weather?`

Oh, yeah, it worked, thank you!
