### ISSUE TITLE
"zz_monikamovie.rpy"

### ISSUE THREAD

**Issue by gwen573** [Monika-After-Story/MonikaModDev#10049]
IDK if it's allowed or not, but I was looking through the MAS source code using un.rpyc, and found 'zz_monikamovie.rpy'. Looking into it, I found some kind of mechanic to play movies? There appears to be a text box for one of the things you need to do, to put probably the hour,minute, and seconds of the movie, pasted below.

------------------------------------------
            if bad_format:
                m 1lksdlc "Erm..."
                m 1lksdlb "Sorry, I can't understand that, [player]."
                m 1eka "Remember to set it in the format of HH:MM:SS."
                m 3eua "That's 'Hours:Minutes:Seconds.'"
                m "Here's an example for you, [player]."
                m "01:05:32"
                m 1eub "That's 1 hour, 5 minutes, and 32 seconds."
                m 3hua "So try again!"
                jump mm_movie_repeattime
--------------------------------------------------
Any answers? I'm pretty sure this was unused, since I've seen nobody talk about it before, but made it into the final releases anyway.

**Comment by dreamscached** [comment]
It's unused leftover from development process of the said feature, possibly actually functional to some extent. But no promises or even speculations on if it's ever going to be finished and released.

**Comment by gwen573** [comment]
Thanks!
