### ISSUE TITLE
Windows React / Notifications don't work

### ISSUE THREAD

**Issue by Sugarlord32** [Monika-After-Story/MonikaModDev#10047]
I use Windows 10, have "Window Detect" on, same with all of the "Alerts" options.

The notification in the tutorial worked fine, but now there's nothing.

**Comment by dreamscached** [comment]
They are random and will eventually show up.

**Comment by Sugarlord32** [comment]
It's been days since i started playing, i'm not sure how "random" that is. There's no notifications for topics either.

**Comment by Booplicate** [comment]
Make sure you enabled notifications for DDLC in windows settings.

**Comment by Sugarlord32** [comment]
It doesn't seem to show up. Maybe it's not detected for some reason?

**Comment by dreamscached** [comment]
You shouldn't ever run MAS as admin, just like any other application that doesn't need elevated access.

**Comment by Booplicate** [comment]
> It doesn't seem to show up. Maybe it's not detected for some reason?

Try triggering a notificatioin, then open the windows notifs settings, only then you can see DDLC being there. Once there, adjust the settings.

**Comment by Sugarlord32** [comment]
> Try triggering a notification, then open the windows notifs settings, only then you can see DDLC being there. Once there, adjust the settings.

Nope. I've tried various ways to trigger a notif (opening certain apps, websites and just waiting for a topic) and nothing seems to make it show up.

**Comment by Sugarlord32** [comment]
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/12205401/mas_log.log)

Here. The errors in the latest ones are from a submod btw, since the hours align to when i installed it. The bug of the notifications not appearing has been happening since before then though, so i don't think they're connected.

**Comment by Booplicate** [comment]
Just wanted to be sure notifs are working on MAS side.

Then it's a DDLC/windows issue. Window reacts can be triggered only once (usually), so try restarting the game, make sure you're not in a dialogue or any interaction, open a website that has a react (like youtube), open "Notifications and actions" settings, DDLC should appear there for a few seconds.

Usually that works, but if not, then it's most likely a windows issue, I can only suggest to wait for next big update, we improved the way windows finds MAS window.

**Comment by Sugarlord32** [comment]
> try restarting the game, make sure you're not in a dialogue or any interaction, open a website that has a react (like youtube), open "Notifications and actions" settings, DDLC should appear there for a few seconds.

Nope, nothing. I guess i'll wait for the update then, thanks for the support.

**Comment by dreamscached** [comment]
Closing as stale.
