### ISSUE TITLE
How to import Tkinter for a submod? 

### ISSUE THREAD

**Issue by destiny6destroyed** [Monika-After-Story/MonikaModDev#10046]
Hi, I want to create a submod, but for that I need Tkinter and, when I tried to import it like this:
____________________
*python:
        import sys
        if sys.version_info[0] == 3:
            from tkinter import *
        root = Tk()*
____________________

The error is: **NameError: name 'Tk' is not defined**

Then I tried:

____________________
*python:
from tkinter import *
        root = Tk()*
____________________
____________________
*python:
        try:
            import Tkinter as tkinter
        except ImportError:
            import tkinter
        root = tkinter.Tk()*
____________________
____________________
*python:
        try:
            import _tkinter as tkinter
        except ImportError:
            import tkinter
        root = tkinter.Tk()*
____________________

But the error of those three is: **ImportError: No module named tkinter**

How I can make it work?

**Comment by multimokia** [comment]
Have you added tkinter to python-packages? Renpy will not pull from global python, any packages you require also require you to include them with your submod, including their depdencies.

**Comment by destiny6destroyed** [comment]
@multimokia yeah, I also tried that, but...

```SyntaxError: invalid syntax (python-packages/tkinter/__init__.py, line 151)```

**Comment by multimokia** [comment]
Ah okay. I'd actually hold off a little bit in the interest of compatibility due to this, but also for another reason.

The updated submod framework coming with a renpy 8 version of MAS (py3) #9742, introduces a `require` function that allows you to add your python packages in a folder local to your submod (thus not creating other conflicts potentially) and loading it in that specific version. It _also_ addresses this issue with the init py.

The issue you might be having in your case is that you may just be using a python 3 version of tkinter, MAS currently only supports py2.

**Comment by destiny6destroyed** [comment]
I see, so I should wait until that framework is finished to use the ``require`` function and be able to make my submod work without causing problems with the main code, right? (sorry, english is not my first language)

In any case, I have being searching and I found a version of tkinter that works for py2 (at least it did in linux), so I will be trying to make it work at least in my pc until the framework is read

Thanks for your help!

**Comment by Booplicate** [comment]
Bear in mind that renpy doesn't support complex (or generally most) custom packages, including tkinter. If there's a way for you to  avoid using tkinter (replace it with pygame, for example), or launch tkinter from a child process, it's probably going to be easier than trying to make renpy work with it.

It's definitely going to be better with py3 and the new framework, but I'm not sure about tkinter.

**Comment by dreamscached** [comment]
Closing as stale.
