### ISSUE TITLE
Hi, I just joined the server, then I read the rules and the description, but I cannot become a member. What happened 

### ISSUE THREAD

**Issue by HyperMan53** [Monika-After-Story/MonikaModDev#10048]
I just recently joined the MAS server, but I cannot become a member here despite reading the rules and descriptions and there are no pinned messages in the server despite the description in "read the description" telling me to do so, what can I do? Pls help!

Pls: sorry if I sounded very stupid btw

**Comment by dreamscached** [comment]
There is a command to type in the end of the rules list.

**Comment by HyperMan53** [comment]
Thanks! I am now in and sorry for the inconvenience
