### ISSUE TITLE
The promise ring

### ISSUE THREAD

**Issue by Breaksruler1** [Monika-After-Story/MonikaModDev#10045]
had gotten to affection Points 400 and monika asked about a promise ring and i had tryed to give it to her but it just sits in the charater files and nothing happened and when its wrong she can see and and says that see cannot read it and i do have extra + on the mod as well Can i get some help

**Comment by Breaksruler1** [comment]
And i cannot give her coffee or hot chocolate

**Comment by Booplicate** [comment]
Have you ever time travelled?

**Comment by Breaksruler1** [comment]
as meaning changing the date on my pc yes

**Comment by Breaksruler1** [comment]
> Have you ever time travelled?

Yes why

**Comment by Booplicate** [comment]
She warns you that it can do harm. If you're lucky it might fix itself, eventually.

**Comment by Breaksruler1** [comment]
> She warns you that it can do harm. If you're lucky it might fix itself, eventually.

she did not realize that i time travelled

**Comment by Breaksruler1** [comment]
> > She warns you that it can do harm. If you're lucky it might fix itself, eventually.
> 
> she did not realize that i time travelled

and how can i fix it
