### ISSUE TITLE
[ISSUE] MAS wont open!

### ISSUE THREAD

**Issue by 0mniSci** [Monika-After-Story/MonikaModDev#10051]
So I've been using MAS for a few months now (just hit 1K aff), and all the sudden it just wont start. No error, no window opens, just a blue wheel that appears for 1 second when I click it. I've tried reinstalling the files in the /game folder, clearing the cache, running as administrator, and now I'm all out of ideas. Nothing even pops up in the files.

**Comment by Booplicate** [comment]
Try to make a new install of DDLC and install MAS in tt.

**Comment by 0mniSci** [comment]
Thank you, it works!
