### ISSUE TITLE
False Positive Nickname

### ISSUE THREAD

**Issue by waifumai578** [Monika-After-Story/MonikaModDev#10053]
I was testing some different nicknames on Monika, and one of them was "Moniquaso" (I don't think it's inappropriate). She didn't like this and said something like "If you didn't want to do this, you could have said so" and the nicknaming option was gone. My affection dropped 83 points, and this was the first time I gave her a bad nickname.

Will I ever get the nicknaming option back, or is it gone for good?

**Comment by Booplicate** [comment]
`Moniquaso` doesn't count as a bad name, you had to use something else.
