### ISSUE TITLE
eveerytime i try to open the MAS mod this happens

### ISSUE THREAD

**Issue by LuvAkino** [Monika-After-Story/MonikaModDev#10067]
yesterday while playing the monika after school mod i accidentally closed the game on monika without saying goodbye. every since, whenever i tried to open the game with the mod installed monika would come on the screen crying than the game would close and this message would appear. im not sure what to do. i have uninstalled and reinstalled both the game and the mod multiple times and still nothing new. i would appreciate it if some one could help me
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/143454903/efd90e57-3887-4c40-8a2d-3a22db7ed056)

**Comment by dreamscached** [comment]
You have missing sprites, reinstall the DDLC/MAS. Your progress won't be lost.

**Comment by dreamscached** [comment]
Closing as stale.
