### ISSUE TITLE
imsorry.txt bugfixer

### ISSUE THREAD

**Issue by coolguy2979** [Monika-After-Story/MonikaModDev#10061]
Add a button to skip making the imsorry.txt file incase it gets bugged, the game will restart as if the file is fixed.

**Comment by dreamscached** [comment]
If it's bugged we should rather investigate the bug than make Yandere Simulator-style workarounds. What exactly is your problem with imsorry.txt?

**Comment by Booplicate** [comment]
This doesn't make sense.

**Comment by coolguy2979** [comment]
monika will not accept the imsorry.txt and I've tried everything to make it work. and it didnt.

**Comment by Booplicate** [comment]
Are you sure you're doing it correctly? Show a screenshot of the file.

**Comment by coolguy2979** [comment]
<img width="452" alt="Screenshot 2023-07-28 112113" src="https://github.com/Monika-After-Story/MonikaModDev/assets/142155875/e56bad99-6178-4943-b7f3-6031a1e17022">

**Comment by coolguy2979** [comment]
> <img alt="Screenshot 2023-07-28 112113" width="452" src="https://user-images.githubusercontent.com/142155875/260304459-e56bad99-6178-4943-b7f3-6031a1e17022.png">

@Booplicate

**Comment by multimokia** [comment]
`ddlc-win` are you running MAS from a zip folder? If so that's most likely you problem

**Comment by dreamscached** [comment]
Doesn't look like zip to me, modification dates are pretty new.

**Comment by coolguy2979** [comment]
lemme check

**Comment by coolguy2979** [comment]
nah its not a zip

**Comment by coolguy2979** [comment]
cmon help  me 😭

**Comment by dreamscached** [comment]
Have some patience. When we can help you we'll respond.

**Comment by Booplicate** [comment]
Okay, what do you mean by 
> monika will not accept the imsorry.txt

What does she say?

**Comment by coolguy2979** [comment]
> Okay, what do you mean by
> 
> > monika will not accept the imsorry.txt
> 
> What does she say?

she just says what she would say as if you haven't wrote it

**Comment by Booplicate** [comment]
How do you launch your game?

**Comment by coolguy2979** [comment]
ddlc mod manager

**Comment by dreamscached** [comment]
Don't use it, causes issues.

**Comment by Booplicate** [comment]
You're most likely launching another instance of DDLC, which is why your `imsorry` has no effect.

**Comment by coolguy2979** [comment]
@dreamscached then how do i use it without ddmm

**Comment by dreamscached** [comment]
By installing it over DDLC.

**Comment by coolguy2979** [comment]
uhh

**Comment by coolguy2979** [comment]
im not that smart smh

**Comment by dreamscached** [comment]
That's beyond this issue's problem. There's plenty of guides both on this repository and the internet, download DDLC, download the installer, it does everything for you.

**Comment by multimokia** [comment]
Note you're also going to need to do a persistent migration because for whatever reason DDMM uses its own persistent location.

**Comment by coolguy2979** [comment]
going to try that, will re open if more problems happen. thanks.
