### ISSUE TITLE
A recurring crash keeps happening 

### ISSUE THREAD

**Issue by FrogCheems** [Monika-After-Story/MonikaModDev#10064]
There seems to be a crash where it says a bit of stuff I do not understand and says 'mm' not defined

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/12443393/traceback.txt)

**Comment by Booplicate** [comment]
It seems you installed some other mod along with MAS. That's not gonna work, make a new clean install.

**Comment by FrogCheems** [comment]
I don't want to lose everything

**Comment by Booplicate** [comment]
You won't.

**Comment by FrogCheems** [comment]
ok, ill do that thank you
