### ISSUE TITLE
Persistent corrupted and unable to open game 

### ISSUE THREAD

**Issue by louis2710** [Monika-After-Story/MonikaModDev#10062]
This is what it says in my traceback 

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/0utils.rpy", line 6, in <module>
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\users\\admin\\appdata\\local\\temp\\C-Users-Admin-OneDrive-Desktop-Doki Doki Literature Club-DDLC-.lock'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Admin\OneDrive\Desktop\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Admin\OneDrive\Desktop\Doki Doki Literature Club\renpy\main.py", line 419, in main
    game.context().run(node)
  File "lib/windows-i686/0utils.rpyc", line 3, in script
  File "C:\Users\Admin\OneDrive\Desktop\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Admin\OneDrive\Desktop\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/0utils.rpy", line 6, in <module>
  File "python-packages/singleton.py", line 39, in __init__
    os.unlink(self.lockfile)
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\users\\admin\\appdata\\local\\temp\\C-Users-Admin-OneDrive-Desktop-Doki Doki Literature Club-DDLC-.lock'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.14

And this is my persistent 

xœ¤} œÅõ°}ö5Œmz=º)>_u¡÷flêMb%íIë“v¥·Òu‰º}!…Fz#	$^!$´4Hï!	SSÞ¿÷ÞÌÎN‘„ÿ¿„ãnßììÌ›×çÍ›+;rà‡•FÅ‡8ˆk~X›w^úkuöáWU;¶Tç,[œ){qÆËÅ™
ø™6¨ÎMÞmÔŠQ8ïÒ‡š—-ùç t^µßíÚRíÎŽíÏïNa>šßËÕâLÕ‚ñÌxPªá×ª=­z:5ÈaO½ØÓ¼evž5kÖ%ÜIßÔK…quþ¶

ðùEQ%ÈõTÂ÷âê‚mõ-Õ…Ù±½ø»•r&ˆ3Ùz©ÔÂBf»ÊÕ¶íœ€‹Þ¤Ÿ÷ÊÕEëñaì×hŽã>Ž)çÇÕ·-å–¥`Â±q 8„°ºxÛØÞü<ïÕ#^\ËäŠ~nÂÏgÀ
Âê’ð[þ<úe^uéØÜî§:÷¼î‚ê.ù ¦YfüB!®î:3¶ ?Å^â8C/æ“ÕÝÖí&V ^‹2å(/…ÉWwOÆA‹#âø£rû€®î13Ö—Ì4Á$!!ëûa&ñ•\Ç•®î936–_õ
~u¯
³©ƒc;‰s5/ï Y¿º÷ú±=“¾&£R=¬ù>à€=jê>ÛÆv3¨"¯–Éz¹‰Dõ0_ÝwC/öW¼œQT®î‡óIW&q@Åˆïý×-i|å(&<&¿Ñ7#×¿Ó’åy-ª ¬—ÏsàÅE|šõÇ#ð« nKÛ>dÕƒ¶IìÓó’×Èlò¦§« ¯;”Ÿa.*W<¤œv”Ãëê¸Â™I)+?4šAL×J~-ò3AW¥q¦”Éûã^½T«V$:^¶lC"¢æoFr©ÄÕÃ×m˜G˜ßÌ-ûÕ#Î8á™Yü7õÆËLÕ#×.bZ/×ã —4>J5Fš_žÛ‡GF+)9mSñË¿ãÐûgÆL†>å…FjÊEa
‚lgH´åÅÕ	µÅÅ¨^ôŒ°¼×¨lÛU­‚o}ð*$g$¹·áÂ×+Õ¡™±]4’®ÖƒÜDŒ+WÞ@#NzÂE@\‡½2RÀH‘dÇè²
Ø‚ß¨®Hšò}ü  µêª

Do you guys know what I should do??

**Comment by Booplicate** [comment]
You're not supposed to read the persistent.
Restart your PC to fix the `lock` file problem and don't launch multiple copies of MAS.

**Comment by louis2710** [comment]
How do I launch MAS now because I can't find the file to launch it anywhere

**Comment by louis2710** [comment]
It's fine now I fixed it thanks for your help
