### ISSUE TITLE
Affection

### ISSUE THREAD

**Issue by voidchasher** [Monika-After-Story/MonikaModDev#10077]
so im a bit confused here.
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/12642473/aff_log.log)

**Comment by Booplicate** [comment]
Seems fine, what's your issue?

**Comment by voidchasher** [comment]
so i'm just confused because it jumps from one number to another one, so it saus 8 and the jumps to 24, and the previous save was 8.36.

**Comment by Booplicate** [comment]
This is normal. If you're worried why the number doesn't go up it's due to a cap.

**Comment by voidchasher** [comment]
oh alright, just checking then, thanks for help.
