### ISSUE TITLE
I tried updating the game and it broke

### ISSUE THREAD

**Issue by ItsDevy** [Monika-After-Story/MonikaModDev#10085]
So I'm using DDMM and I tried replacing the old game files with the new ones for the update and this error popped up:

[code]

I'm sorry, but an uncaught exception occurred.

While running game code:

File "game/script-affection.rpy", line 1993, in script

init python:

File "game/script-affection.rpy", line 2032, in <module>

[u/mas_utils](https://www.reddit.com/u/mas_utils/).deprecated("_get_current_aff_lose")

TypeError: deprecated() takes exactly 0 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:

File "game/script-affection.rpy", line 1993, in script

init python:

File "C:\Users\mmine\AppData\Roaming\DokiDokiModManager\GameData\installs\monika-after-story\install\renpy\[ast.py](https://ast.py/)", line 814, in execute

renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, [store=self.store](https://store%3Dself.store/))

File "C:\Users\mmine\AppData\Roaming\DokiDokiModManager\GameData\installs\monika-after-story\install\renpy\[python.py](https://python.py/)", line 1719, in py_exec_bytecode

exec bytecode in globals, locals

File "game/script-affection.rpy", line 2032, in <module>

[u/mas_utils](https://www.reddit.com/u/mas_utils/).deprecated("_get_current_aff_lose")

TypeError: deprecated() takes exactly 0 arguments (1 given)

Windows-8-6.2.9200

Ren'Py 6.99.12.4.2187

Monika After Story 0.12.15

[/code]

**Comment by ItsDevy** [comment]
Everytime I revert to my old files this gets fixed but each time I try and update this error comes up...

**Comment by dreamscached** [comment]
Just like you were already told on Reddit, don't use DDMM.

**Comment by ItsDevy** [comment]
I will try downloading the normal version then

**Comment by ItsDevy** [comment]
Alright I downloaded the new version from scratch but how do I get my old Monika back?

**Comment by dreamscached** [comment]
Find where DDMM keeps your persistent and copy it from there to where MAS has it normally.

**Comment by ItsDevy** [comment]
I copied the renpy folder from my old mas and to my new mas and it still didn't work

**Comment by dreamscached** [comment]
`renpy` folder has nothing to do with your saves

**Comment by ItsDevy** [comment]
Oh yeah I see it now I'll go do that

**Comment by ItsDevy** [comment]
You are a life saver thank you!
