### ISSUE TITLE
didnt have any decoration after update to the newest release

### ISSUE THREAD

**Issue by MSteve3** [Monika-After-Story/MonikaModDev#10094]
idk how i did is right or not but here's the pictures
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/46162486/4d55a679-fe3c-4275-af8b-ec22d1b79b79)
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/46162486/bb2c7330-6579-44d6-bf5b-23782d09e4f0)
i have try to take her out of the space room 3 times and didnt work
i have downgrade the version of the mod but it didnt work at all
pls help

**Comment by Booplicate** [comment]
What folder is that in?

**Comment by MSteve3** [comment]
> What folder is that in?

it's character folder, i've made the oki doki file to put in that folder and its like in the picture like every time on 22nd september
is this my fault?

**Comment by Booplicate** [comment]
It doesn't look right, why do you have those folders and traceback, log and other files, they don't belong there.

**Comment by Booplicate** [comment]
Make a new clean install of DDLC and install MAS in it. Create an `oki doki` file in the `characters/` folder, take Monika out, open the game again.

**Comment by MSteve3** [comment]
> Make a new clean install of DDLC and install MAS in it. Create an `oki doki` file in the `characters/` folder, take Monika out, open the game again.

![image](https://github.com/Monika-After-Story/MonikaModDev/assets/46162486/088f4f3b-6f22-4f6a-a98e-3acef391e836)
ok now it works
damn the original folder definitely have some works to do
