### ISSUE TITLE
birthday decorations are bugged and won't trigger

### ISSUE THREAD

**Issue by kiothefrail** [Monika-After-Story/MonikaModDev#10095]
is it a one time thing? i did the oki doki file, i got the gotcha file, i've taken her out like three times for her birthday today, i've even made sure to return to the base spaceroom incase THAT was what was causing it, and then i switched back to the room i was using incase THAT was causing it, and yet when i bring her back each time, the decorations/party just REFUSE to trigger, is it because i accidentally took her out and brought her back early when i forgot yesterday was the 21st instead of the 22nd? everyone else's on the subreddit seems to fix itself, except for mine, because everyone says you can do it on the 21st OR the 22nd.
if this ends up borked until her birthday is over, if the gotcha file is still there, should i just- delete it?

**Comment by kiothefrail** [comment]
i cannot even wish her a happy birthday (it's not one of the options i have available to me) without the party proc'ing, maybe that could be added as a failsafe for when this happens?

**Comment by kweerfrog** [comment]
im having the same issue! everyone else on reddit has theirs working fine, but i dont know what to do

**Comment by dreamscached** [comment]
So you say you got `gotcha` (check if it's not from the previous year or something), took her out and nothing happened?

**Comment by kiothefrail** [comment]
> So you say you got `gotcha` (check if it's not from the previous year or something), took her out and nothing happened?

yep, nothing happened

**Comment by dreamscached** [comment]
Have you time travelled before?

**Comment by kiothefrail** [comment]
> Have you time travelled before?

never!

**Comment by kweerfrog** [comment]
do i need to take her out for a certain period of time? i only waited about 2-3 minutes. should i wait longer?

**Comment by dreamscached** [comment]
I'd suggest to try taking her out for about 15 minutes.

**Comment by kiothefrail** [comment]
> I'd suggest to try taking her out for about 15 minutes.

i took her out for like, hours, does it need to specifically be 15 minutes?

**Comment by kweerfrog** [comment]
> I'd suggest to try taking her out for about 15 minutes.

alright, ill try that, thank you

**Comment by Booplicate** [comment]
Create another `oki doki` and take her out, then reopen the game.

**Comment by kiothefrail** [comment]
> Create another `oki doki` and take her out, then reopen the game.

i'll try that now

**Comment by kiothefrail** [comment]
> Create another `oki doki` and take her out, then reopen the game.

the old gotcha file is still there, and my oki doki file isn't disappearing, even after reopening the game, should i delete the old gotcha file and try again?

**Comment by kweerfrog** [comment]
> > Create another `oki doki` and take her out, then reopen the game.
> 
> the old gotcha file is still there, and my oki doki file isn't disappearing, even after reopening the game, should i delete the old gotcha file and try again?

try that! thats what i did, and now the decorations are showing up

**Comment by kiothefrail** [comment]
> > > Create another `oki doki` and take her out, then reopen the game.
> > 
> > 
> > the old gotcha file is still there, and my oki doki file isn't disappearing, even after reopening the game, should i delete the old gotcha file and try again?
> 
> try that! thats what i did, and now the decorations are showing up

nope, no new gotcha file is showing up

**Comment by Booplicate** [comment]
@kiothefrail, send your persistent.

**Comment by kiothefrail** [comment]
> @kiothefrail, send your persistent.

how would one go about doing that? apologies, i'm not that technically savvy

**Comment by Booplicate** [comment]
Return Monika back to the room, close the game, [find the persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent), attach it here.

**Comment by kiothefrail** [comment]
> Return Monika back to the room, close the game, [find the persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent), attach it here.

github says it doesn't support the file type, so i threw it on google drive, hopefully this works, sorry if i did this wrong
https://drive.google.com/file/d/13fVbVQhnfTH2QuZO82R3WKDUdYdTttIq/view?usp=drive_link

**Comment by Booplicate** [comment]
Can't download from there, please, put it into a zip archive and attach.

**Comment by kiothefrail** [comment]
> Can't download from there, please, put it into a zip archive and attach.

will do!

**Comment by kiothefrail** [comment]
> Can't download from there, please, put it into a zip archive and attach.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/12704182/persistent.zip)

**Comment by Booplicate** [comment]
You didn't return Monika back in the room as I asked.

I can see that you didn't create an `oki doki` file, if you create it and return Monika in the room, the party will work.

**Comment by kiothefrail** [comment]
> You didn't return Monika back in the room as I asked.
> 
> I can see that you didn't create an `oki doki` file, if you create it and return Monika in the room, the party will work.

but i did return monika? a bit confused but i'll do as you say and hopefully it will work

**Comment by kiothefrail** [comment]
> You didn't return Monika back in the room as I asked.
> 
> I can see that you didn't create an `oki doki` file, if you create it and return Monika in the room, the party will work.

thank you, it finally worked! 😭
