### ISSUE TITLE
[Bug] -

### ISSUE THREAD

**Issue by LastWatanabe** [Monika-After-Story/MonikaModDev#10103]
I would like them to fix a bug that happened to me, when I click on "affection" automatically I can't click on anything or any option other than "exit" and "music",and when I try to exit the game in a casual way (closing the game and opening it again) the bug continues, and the only way I found to get out of the bug is to close the game in front of Monika,I ask you to fix this bug.

**Comment by dreamscached** [comment]
Official MAS has no 'Affection' button. Are you using a submod?
