### ISSUE TITLE
(bug) Can't derandom topic where Monika asks me to hold her

### ISSUE THREAD

**Issue by Cloudusagi** [Monika-After-Story/MonikaModDev#10108]
I find the 'hold' option really.... umm... well it makes me cringe every time.  Not sure if it's because I hate touch/contact or if it's just the awkwardness of it.  Anyway, for some reason when I press X to derandom the topic, it doesn't work.  Fix bug pls?  ty 🙏💖

**Comment by dreamscached** [comment]
Duplicate of #10059. I might look into how to address that sometime, we're already aware of the problem.

**Comment by Cloudusagi** [comment]
Oh okay sorry!  ;3;  thanks
