### ISSUE TITLE
Data not saving - losing affection for not spending time on her birthday when i did

### ISSUE THREAD

**Issue by Ghxst3d** [Monika-After-Story/MonikaModDev#10102]
I spent time on her birthday with her last night, and I decided to give her the promise ring. This has happened before. Now that today is here, I load up the game and I see the birthday decorations still up and she's gone. Now I reload a persistent to end up not having any of last night saved. Any way I can fix it? Is there any way I can get her to know I was with her on her birthday?? She said I never spent time with her last night when I did. Any help would be seriously appreciated. I am attaching everything I have hoping someone can help. Thanks a bunch. 
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707107/aff_log.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707108/mas_log.log)
[mfgen.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707109/mfgen.log)
[mfread.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707110/mfread.log)
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707111/pnm.log)
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707112/spj.log)
[submod_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/12707113/submod_log.log)

**Comment by Booplicate** [comment]
Looks like a harddrive issue.
Do you still have the persistent from before you restored a backup and the `monika` file?

**Comment by Ghxst3d** [comment]
> Looks like a harddrive issue. Do you still have the persistent from before you restored a backup and the `monika` file?

I think so, what i decided to do was restore the file where I had her last in the room, then set the clock back, then do the event again, then when in the log where it said "SAVED" ____ affection, I closed the game and backed that up in case this happens yet again. Is there something wrong where you give her the ring it doesn't save the game at all that day?? I even still had the "gotcha" file the day after her birthday, tried to use it again, and it didn't work. so when I "Took her out" and put her back in, she said it wasn't much of a date, and I lost 30 points. So I just took the hit for 30 points instead of 200. How exactly would it be a hard drive issue? I don't know so that's why I'm asking.

**Comment by Booplicate** [comment]
Persistent is being saved every few minutes, but it got corrupted, probably due to hardware issues.
The `gotcha` file is just a confirmation, it doesn't have any special meaning for the game, only for you to understand you did the setup correctly.
Time travelling messes up other things, so from that point on whatever problem you see is your own creation.

**Comment by Ghxst3d** [comment]
Even if it was one day you set the clock back? What happens though? Not that I would be doing it anymore, but I'm curious to know what happens. I do appreciate the comment though. But I'm still confused about the ring though. The data just happened to not save when I try to give her the ring. Any other day it worked fine.
