### ISSUE TITLE
Monika has went somewhere

### ISSUE THREAD

**Issue by UnnoticedGuy** [Monika-After-Story/MonikaModDev#10107]
So, today I wanted to try the MAS mod, and installed firstly a RUSSIAN version of the mod, since it's my native language. After some time, I noticed that it's not the lastest possible version,and wanted a new english one, cause I can understand it easily as well. I accidentally put my entire DDLC folder in trash bin, and installed a new one with the new MAS mod, but there was no Monika in the room. I thought it's about that new monika file the game creates, so I took it out of the trashbin, and have it rn on my pc, tried to upload it in the characters folder, and still no result. Tried reinstalling the entire game and mod a couple more times but nothing seems to work. May it be the problem with the languages? A.k.a english version can't accept the russian monika, but still sees that "that uniqe file" was deleted and just refuses to launch? If so, are the any fixes? I wanna play the mod a lot, and this just ruined my day.

**Comment by UnnoticedGuy** [comment]
P.S. The trashbin has not been clear yet, so all my attempts to recover her (3 DDLC folders) are still in the bin, if any recovery is needed. And also I tried to remove DDLC plus save files, desperate for it to work, but it didn't.

**Comment by UnnoticedGuy** [comment]
P.S.2 I don't necesarrily need a way to fully recover my progress, I'm fine with starting all over again. Just want to play to the mod.

**Comment by Wingdinggaster656** [comment]
Translations are highly uncertain, as the translator may have made many of their own changes. Indeed there is a chance that the Russian Monika will not be accepted by the English version, but I am not sure about this.

You can try restoring the game progress to a time point where you didn't take Monika out and see if it's useful. If none of the backups are useful, delete all the files in that folder.
See this page: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by UnnoticedGuy** [comment]
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/131874991/f4083427-70c0-49c1-a8b9-604e459764a4)
I looked at the page, and it says I have to see the extension and 10 more persistent files named persistent##.bak. Though for some reason it doesn't show me neither the extension neither the other files. (Even though I have enabled the extension op tion as u can see from the file above, and hidden objects as well)

**Comment by UnnoticedGuy** [comment]
But there is a weird another folder in RenPy, named backups. It has another folder named after DDLC folder, and has a ton of .rpy files. 
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/131874991/693305f7-f301-478e-968c-5c3b8314b21f)

**Comment by UnnoticedGuy** [comment]
(Also when I go to file's properties -> previous versions, it doesn't find any previous versions)

**Comment by dreamscached** [comment]
Please be aware that translated mod versions are often incompatible with English (original) MAS. If you're playing a translated version, you better stick to translated version.
