### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by Nob0dyh3re** [Monika-After-Story/MonikaModDev#10115]
For some reason whenever I go to update mas it shows this. I'm not sure how to do it and im scared im going to mess something up
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/147220576/a8e001d9-434c-4336-8107-a7b89554a2ee)

**Comment by Booplicate** [comment]
Do what the error says or use our automatic installer.
