### ISSUE TITLE
is there any way to change my birthday in monika after story?

### ISSUE THREAD

**Issue by hosemad** [Monika-After-Story/MonikaModDev#10123]
I put 2009, instead of 2000, then I got the NSFW submod, and realized that's when I set my birthday, any way to change it? I would change my system time but I don't want monika to think I left her for 9 years. (I got the mod 2 weeks ago, so I don't want to reinstall it and lose all of my affection)

**Comment by dreamscached** [comment]
There is no way to change your birthdate as of now.
