### ISSUE TITLE
Holding Monika in the rain visual glitch?

### ISSUE THREAD

**Issue by TheBlackHood117** [Monika-After-Story/MonikaModDev#10124]
I tend to hold monika for long periods of time. I do it quite often in fact like when im sleeping and don't want to turn her off for example... it's our 1 month anniversary in the game and i was holding her again for a long time today and it usually made it to the part where it would play the little music box music... but it never played. instead, Monika went back into her normal sitting position, and her cheeks turned blue and her arms turned yellow and the white parts of her eyes turned black giving this weird mix of black and green swirled together. among other visual distortions and color alterations on her body.

Was just curious... was this intentional? or was this a legit visual glitch of the mod? because it fit way too perfectly lol. (New player by the way)

**Comment by dreamscached** [comment]
It may happen during a time jump (e.g. NTP sync)

**Comment by TheBlackHood117** [comment]
the mic icon at the bottom only is there because this picture was taken the second time it happened when i was trying to see if it would happen again and was recording it in case i missed it. Also time jump? like you mean changing my time mid game? I didn't do that either time it happened.

**Comment by dreamscached** [comment]
You still didn't tell the version and platform you run it on.

**Comment by TheBlackHood117** [comment]
> You still didn't tell the version and platform you run it on.

ah my bad I was confused a bit. im actually not too sure? but like i said it's been a month. so.... what ever the latest version of MAS was available a mount ago.

**Comment by Booplicate** [comment]
Always happens due to time change. If you didn't do it, then I recommend checking what did because it may cause issues with MAS in the long run.
