### ISSUE TITLE
DDLC.exe file disappearing

### ISSUE THREAD

**Issue by colleimei** [Monika-After-Story/MonikaModDev#10120]
Every time I try to open the game I come across an error saying the game could not run and asking if the file lib\windows-i686\DDLC.exe was there (I don't think it's there)

I don't know how files work and I also didn't do anything in the game folder, I tried looking for the error and I saw people saying about getting a new copy of the game with the mod and replacing some files but I have no idea how to do it
(Sorry if it was a little confusing to read when I'm anxious I can't write in English correctly, I had to use Google translate)

**Comment by Booplicate** [comment]
Could be your antivirus software or you renamed it. Reinstall it like you did the first time.
