### ISSUE TITLE
[Bug] - Poses don't work anymore

### ISSUE THREAD

**Issue by sepia019** [Monika-After-Story/MonikaModDev#10126]
So I believe the problem started when I was coding a submod and I had the sprite_map.json file open when I accidentally clicked save on the sprite map file. Now, Monika's “leaning” pose and her “down left point right” pose are replaced by the “steepling” pose. I tried replacing the sprite map file with a fresh copy, but Monika's poses were still glitched.

**Comment by Booplicate** [comment]
Reinstall the mod and don't edit the main install.
