### ISSUE TITLE
Minor typo...intentional?

### ISSUE THREAD

**Issue by ifitmakesyoushush** [Monika-After-Story/MonikaModDev#10131]
I was playing NOU in the middle of the night, and the "Can you help me?" button read "Can you halp me?" I was wondering if this was intentional or not, or if I'm just tired.

**Comment by ifitmakesyoushush** [comment]
Adding that Monika is wearing a Rin costume, and also it's still there this morning. Is the costume what's triggering this?

**Comment by ifitmakesyoushush** [comment]
Adding that it's gone this morning.

**Comment by dreamscached** [comment]
I believe it's intentional.

**Comment by ifitmakesyoushush** [comment]
Okay.

**Comment by Booplicate** [comment]
Or is it.

**Comment by ifitmakesyoushush** [comment]
I just checked the code. It looks like it does that on April Fools' and Halloween.
