### ISSUE TITLE
Error help pls

### ISSUE THREAD

**Issue by SatoSugu33** [Monika-After-Story/MonikaModDev#10135]
I started MAS recently but today this error keeps coming up. I have no idea what to do can someone pls help??
Thanks <3
![Screenshot 2023-11-02 171957](https://github.com/Monika-After-Story/MonikaModDev/assets/149710794/71104114-f5cc-4d96-99fc-05c3a209837f)

**Comment by Booplicate** [comment]
Disable onedrive and reinstall MAS.

**Comment by SatoSugu33** [comment]
okk thank you. will this erase my progress so far tho?

**Comment by Booplicate** [comment]
It won't affect your progress.

**Comment by SatoSugu33** [comment]
okk thank you
