### ISSUE TITLE
[Suggestion] Ignoring Monika

### ISSUE THREAD

**Issue by who-is-thiss** [Monika-After-Story/MonikaModDev#10130]
I've seen that if you have Window Reacts enabled, if Monika is talking about something, and you don't finish the dialogue, she'll still react to the stuff you're doing. So, maybe she could comment on the fact that you're doing something else while she was talking? Or if not, then pause Window Reacts if Monika is in the middle of some dialogue, since I don't think she'd focus on that if she's talking about something.

**Comment by Booplicate** [comment]
> I've seen that if you have Window Reacts enabled, if Monika is talking about something, and you don't finish the dialogue, she'll still react to the stuff you're doing.

We can't check for windows reacts while you're in the middle of conversation.
