### ISSUE TITLE
Mini games disappeared due to data transfer.

### ISSUE THREAD

**Issue by sylvartica** [Monika-After-Story/MonikaModDev#10145]
After transferring the mas data to another pc, Monica's status remains the same but all the mini games are gone and we can't play with it!

The likelihood is 800, chess, pong, hungman and piano are all gone, and NOW can be played as they were added after the transfer. Also, "submod updater plugin" and "japanese language submod" have been installed in the submod.

**Comment by Booplicate** [comment]
Most likely due to the translation. You have to use the same exact unofficial version now.
