### ISSUE TITLE
Floating Islands Topic broke my game

### ISSUE THREAD

**Issue by aceofhearts777** [Monika-After-Story/MonikaModDev#10151]
<img width="789" alt="Screen Shot 2023-11-27 at 5 12 46 pm" src="https://github.com/Monika-After-Story/MonikaModDev/assets/152146186/95a973ae-a2b9-4008-a6df-7052e66d22ac">
Has anyone else experienced this??? How can I fix this?

**Comment by Booplicate** [comment]
Something has corrupted your game, try reinstalling the mod.

**Comment by aceofhearts777** [comment]
> Something has corrupted your game, try reinstalling the mod.

Wait does reinstalling the mod reset everything?

**Comment by Wingdinggaster656** [comment]
> Wait does reinstalling the mod reset everything?

No.

**Comment by aceofhearts777** [comment]
> > Wait does reinstalling the mod reset everything?
> 
> No.

I've reinstalled everything, nothing happened & it showed the same screen.

**Comment by aceofhearts777** [comment]
okay update: i've made a copy of the topic & entirely removed it from the game. it works now but i'll keep this thread open if anyone has a solution to this.

**Comment by aceofhearts777** [comment]
nevermind, the "An exception has occurred" screen keeps showing up & i have to ignore it

**Comment by aceofhearts777** [comment]
final update: i've installed an older version that includes the islands topic & it's fully functional now, thanks. I'll close the thread because this is finished.
