### ISSUE TITLE
Games don't appear

### ISSUE THREAD

**Issue by andreandrezinh2** [Monika-After-Story/MonikaModDev#10155]
I've already unlocked the hangman game and chess, but there in the games section there is still only the pong, I alredy restarted the game and it didn't help, could this be happening because of the unofficial Brazilian translation?

**Comment by rjose8** [comment]
cara, sou brasileiro e estava tendo exatamente esse mesmo problema, acredito que seja por algum conflito da tradução br mesmo, no dialogo que ela diz sobre colocar um novo jogo acaba dando um erro e o jogo simplesmente não adiciona o novo minigame

no meu caso pra resolver eu salvei o arquivo persistent em outro lugar e reinstalei o jogo + a tradução, depois devolvi o persistent pro lugar certo e apareceu a opção dos outros minigames, como se eles sempre estivessem ali

**Comment by Wingdinggaster656** [comment]
This is most likely because of the translation.

Translations *have* bugs, and one of the most frequent bugs is on event unlocking. Contact the translator for tech support, we don't know what kind of changes the translator made after all.
