### ISSUE TITLE
Monika isn't reacting to the spritepacks?

### ISSUE THREAD

**Issue by monikangel** [Monika-After-Story/MonikaModDev#10159]
I'm over 100 affection, I've been giving her spritepacks for a long time now but today when i gave her an outfit she wouldn't react to it at all, and no she didn't say she cant't read the file, she didn't say anything but when i checked the characters file, the gift file was gone so that means she took it, but she didnt say anything about it nor is it in her outfits.

**Comment by zwartkop2** [comment]
Did she put up a Christmas tree yet? If so, you'll find whatever you tried to give under the tree.

**Comment by monikangel** [comment]
> Did she put up a Christmas tree yet? If so, you'll find whatever you tried to give under the tree.

Yeah, she did. Thanks !
