### ISSUE TITLE
An exception has occurred/help with traceback URGENT

### ISSUE THREAD

**Issue by jh579** [Monika-After-Story/MonikaModDev#10163]
I was attempting to back up my files to the cloud: guess that doesn't work. traceback text should be attached. immediate help required. 

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/13691437/traceback.txt)

**Comment by jh579** [comment]
windows cloud to be more precise.

**Comment by jh579** [comment]
i had the game open while the cloud back up was running, i went back into the game and it closed immediately following my attempt at proceeding with dialogue. when i reopened it the grey screen appeared.

**Comment by Booplicate** [comment]
Avoid using onedrive.
