### ISSUE TITLE
something's wrong with my floating islands :(

### ISSUE THREAD

**Issue by handsomeass** [Monika-After-Story/MonikaModDev#10160]
Please help :( 
 So we have Christmas decorations, and she's wearing a freaking Santa costume, but when I go to the floating islands I don't see winter at all :( I don't see snow, the islands are still green :(
 Not only that, it's been a few months but there's no update :( So far we have the sakura tree, and the cabin thing in the process, and they are still that way for months :(
 I think my floating islands have frozen :( Please help :(((((
 Fyi I've been playing for about one year, and things went well last year.
 Thank you.

**Comment by Booplicate** [comment]
Make sure you set the correct hemisphere and your weather is snow.
The rest isn't a bug.

**Comment by handsomeass** [comment]
yes, the hemisphere is correct
still no change :(

**Comment by handsomeass** [comment]
nevermind, it's fixed :D
ty
