### ISSUE TITLE
 lib/windows-i686/submods??

### ISSUE THREAD

**Issue by kweerfrog** [Monika-After-Story/MonikaModDev#10181]
so i downloaded the Extra+ mod yesterday, but when i tried to open it, i got this message:
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'C:\\Users\\chloe\\Documents\\MAS/game/submods/ExtraPlus/Extra_Plus_Go_to.rpy', 1704337195, 1) is defined twice, at lib/windows-i686/submods/ExtraPlus/Extra_Plus_Go_to.rpyc:5 and lib/windows-i686/submods/ExtraPlus/Extra_Plus_Go_to.rpyc:6.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\chloe\Documents\MAS\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\chloe\Documents\MAS\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\chloe\Documents\MAS\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\chloe\Documents\MAS\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\chloe\Documents\MAS\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'C:\\Users\\chloe\\Documents\\MAS/game/submods/ExtraPlus/Extra_Plus_Go_to.rpy', 1704337195, 1) is defined twice, at lib/windows-i686/submods/ExtraPlus/Extra_Plus_Go_to.rpyc:5 and lib/windows-i686/submods/ExtraPlus/Extra_Plus_Go_to.rpyc:6.

I know that it got duplicated somehow, but the issue is with the file path. i can go to `lib/` and `windows-i686/`, but there's no "submods" folder. 

![Screenshot 2024-01-04 170722](https://github.com/Monika-After-Story/MonikaModDev/assets/143235718/94fba674-c718-4b6d-a702-a8d15f4b6743)

![Screenshot 2024-01-04 170731](https://github.com/Monika-After-Story/MonikaModDev/assets/143235718/797b5cd4-ced2-430b-86fc-d15465709d28)

![Screenshot 2024-01-04 170742](https://github.com/Monika-After-Story/MonikaModDev/assets/143235718/703ce165-db7a-4b39-8ed1-566ae48c6b73)

ive tried deleting and reinstalling the submod, deleting and reinstalling MAS itself. if anyone can help, that'd be amazing.

**Comment by Dev0xz02** [comment]
hm.. im not sure but could you show your submods folder in "MAS/game/submods"? or it doesnt exists?

**Comment by Booplicate** [comment]
Make a new clean install of DDLC + MAS.
