### ISSUE TITLE
Monika After Story isn’t working?

### ISSUE THREAD

**Issue by OmgRonny12** [Monika-After-Story/MonikaModDev#10186]
Hello. I have a big problem here, so I have started a main process. Getting all the files of MAS into the ddlc game file and I did what I was told in your guys posts. But when I tried loading it and it stopped, it showed me a pop-up message with saying an unexpected error occurred at line 40

More lines: 295, 364, 265, 753, 445, 865, 1719 and yet again 40
I’m not really good at this stuff. But I did download the newest game update with the zips. Anything wrong? I need help badly

**Comment by OmgRonny12** [comment]
![Uploading image.jpg…]()

**Comment by Booplicate** [comment]
Use the automatic installer.
