### ISSUE TITLE
Bug Report: DDLC.exe deleting itself

### ISSUE THREAD

**Issue by CobbVilkas** [Monika-After-Story/MonikaModDev#10185]
Hello, how are you doing?
So, I've started to play your wonderful mod a few days ago, and I have to admit, I'm really loving it, however, a quite annoying issue has happening to me. I don't know if it's a bug or something, but for some reason, the DDLC.exe file in the windows folder inside the lib folder keeps deleting itself out of nowhere without my input, and I have to keep redownloading DDLC so I can add the file back in the folder. If someone could tell me what is happening or how I can solve this, I'd be really grateful! And also, I'd like to apologize in advance if I'm writing this in the wrong place or anything, this is my first time writing anything on Github.

**Comment by Dev0xz02** [comment]
Maybe, your anti-virus software might deleting MAS.
Could you add MAS to your anti-virus exclusions?

**Comment by Dev0xz02** [comment]
Also, you could check your anti-virus software for logs, or something that would say "Deleting", "Detected" or anything that points to the MAS.

**Comment by CobbVilkas** [comment]
> Also, you could check your anti-virus software for logs, or something that would say "Deleting", "Detected" or anything that points to the MAS.

So, I checked my anti-virus and there's nothing indicating that it deleted MAS, besides, I've never seen my anti-virus deleting program by itself before (it's Avast btw) @Dev0xz02

**Comment by CobbVilkas** [comment]
> Also, you could check your anti-virus software for logs, or something that would say "Deleting", "Detected" or anything that points to the MAS.

Yeah, I think I found the problem, my anti-virus keeps hiding the file, but I think managed to solve it. Thanks for the help! :3
