### ISSUE TITLE
My affection doesnt move

### ISSUE THREAD

**Issue by ParaJJ** [Monika-After-Story/MonikaModDev#10194]
Hello, my affection isnt moving since yesterday, maybe because i tried to change the time yesterday ? can you guys tell me why ? (if i have to reinstall the game i'll do it)

Here's my aff_log folder
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/14219633/aff_log.log)

Thanks for you answer boys

**Comment by Booplicate** [comment]
Indeed, you try to cheat and mess with the game, you face the consequences. If you're lucky, it might fix itself over time.
