### ISSUE TITLE
Student who would like to contribute

### ISSUE THREAD

**Issue by cleaam** [Monika-After-Story/MonikaModDev#10191]
Hey there! So, I just finished playing DDLC and decided to install Monika After Story – it's a really cool mod! But, being French, even though the mod could help improve my English, I'm having a bit of trouble understanding some of the dialogues. So, I thought, why not look for a French patch to make things easier? But no luck! Someone had the idea to make the French patch back on November 22, 2018, but it seems like their project didn't quite work out.

While checking possible game translations, I only found Chinese, Russian, Portuguese, and Spanish, but no French! So, I thought, why not do it myself? I've decided to create this patch, hehe. I wanted to know if it's cool to do so and the steps for translating. I noticed there's no specific folder linking all the game dialogues. I'd appreciate some guidelines and conditions. Thanks!

**Comment by Booplicate** [comment]
You're allowed to make translations, but we don't provide support for them and they stay as unofficial builds. You can use renpy tools to translate the game.
