### ISSUE TITLE
 trouble with changing monika hairstyle and can't give gift

### ISSUE THREAD

**Issue by Temoxi** [Monika-After-Story/MonikaModDev#10207]
IDK why but i unlock this fonction of changing her hairstyle but i lost it and unlock it again and lost it 
now i can't change her hair anymore (i have 400+ affection)

i have an other issue i can't give to monika a cofee and an hot chocolate  and other thing idk why (i have this problem for like 2month)
![Capture d’écran (66)](https://github.com/Monika-After-Story/MonikaModDev/assets/142745293/e78a5c68-ad2a-407c-9010-e02624bd8dcf)
![Capture d’écran (67)](https://github.com/Monika-After-Story/MonikaModDev/assets/142745293/0cc6fa2f-d7a6-407f-bdc5-34336185e924)
![Capture d’écran (68)](https://github.com/Monika-After-Story/MonikaModDev/assets/142745293/6fc17587-ebef-4161-b617-702c09658508)

**Comment by Booplicate** [comment]
Please send your logs.

**Comment by Temoxi** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351534/aff_log.log)
[early.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351535/early.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351536/mas_log.log)
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351537/pnm.log)
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351538/spj.log)
[submod_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/14351539/submod_log.log)

**Comment by Booplicate** [comment]
You time travelled, which breaks the game, as Monika explains herself.
