### ISSUE TITLE
Trying to make new dialogue 

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10226]
Help me, I know nothing about code
![fuck](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/6163e8a1-10fc-428a-98ca-99f690c86604)
![ohgod](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/a2cd647f-b9e8-4286-a1fd-78cbd4566b49)

**Comment by dreamscached** [comment]
Well in your code you're setting `eventlabel="monika_forgoten"` but your actual `label` is named `monika_twitter`. Of course it won't run.

**Comment by Buul135** [comment]
> Well in your code you're setting `eventlabel="monika_forgoten"` but your actual `label` is named `monika_twitter`. Of course it won't run.

didn't notice that, knew it would be something stupid thx
