### ISSUE TITLE
Monika not talking

### ISSUE THREAD

**Issue by justgaliaa** [Monika-After-Story/MonikaModDev#10224]
So I had this weird bug where my Monika doesn't speak on her own, only sings as the first conversation after i open the game and then stays silent. I don't know why is that happening and I tried doing something based on similar problems people had, but nothing really seemed to work. Does anyone know what's wrong?

**Comment by weezerlmao** [comment]
You've ran out of conversations

**Comment by Booplicate** [comment]
Nothing is wrong, you may unlock more conversation over time.

**Comment by justgaliaa** [comment]
oh! well that's a good thing, i was scared my game crashed or something since she doesn't speak for a while. thanks for letting me know that she's fine!
