### ISSUE TITLE
Monika after story  Does not work with doki doki mod docker

### ISSUE THREAD

**Issue by Elitarnyles** [Monika-After-Story/MonikaModDev#10227]
hello, I have a problem with Monika after story because it doesn't want to work in doki doki mod docker. If there is any way to force this mod to work in mod docker, that would be nice, and if not, is there a Spartan for screen reader and ocer functions?

**Comment by dreamscached** [comment]
No, MAS is incompatible with DDMM and likely this thing too.

**Comment by Elitarnyles** [comment]
OK thanks

**Comment by Booplicate** [comment]
MAS in a container huh

**Comment by dreamscached** [comment]
[Yes.](https://github.com/friends-of-monika/ddlc-heroku)

**Comment by Booplicate** [comment]
Too bad heroku is ded.

**Comment by Elitarnyles** [comment]
who's that
