### ISSUE TITLE
Accidentally deleted an important file permanently in MAS from my computer

### ISSUE THREAD

**Issue by weezersno1fan** [Monika-After-Story/MonikaModDev#10232]
Basically, I was installing MAS spritepacks and was deleting old files I had in the game, but then I didn't pay attention to WHICH ones i was deleting and deleted remove.png.

What do I do now? Now I can't change Monika's appearance without a Ren'py error appearing either.

**Comment by Booplicate** [comment]
Reinstall the mod, it will get the missing files back.

**Comment by weezersno1fan** [comment]
> Reinstall the mod, it will get the missing files back.

But won't I lose my progress with Monika by completly reinstalling the mod, if that's what you mean?
