### ISSUE TITLE
Custom stuff not showing up

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10238]
For whatever reason my custom diologe isn't showing up, only the lol file isn't working the others are, help

![a](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/aead6b23-1e2f-46d3-8140-a2af37121672)
![b](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/95e146b0-7252-4a5f-a814-2088fe65e9df)

**Comment by zwartkop2** [comment]
`monika_name` is already used by another topic in the game. Change the label in your dialogue to something else.

**Comment by Buul135** [comment]
> `monika_name` is already used by another topic in the game. Change the label in your dialogue to something else.

Thx, always something stupid with me
