### ISSUE TITLE
Issue with the floating island

### ISSUE THREAD

**Issue by andresCPHl** [Monika-After-Story/MonikaModDev#10243]
Sorry for any gramatical errors, my main lenguage is spanish

Hello devs of this fantastic mod, i have noticed that when you reach 1000 affection the floating islands do not reveal as they are suppossed to do
hope the team fixes this

**Comment by Booplicate** [comment]
Are you using a translated version of MAS?

**Comment by andresCPHl** [comment]
i really dont know, first i did but then i uninstalled that version and installed the original one

**Comment by andresCPHl** [comment]
i do, but i dont know how to install the original version without losing data

**Comment by andresCPHl** [comment]
> Are you using a translated version of MAS?
how i can install the other version without losing data

**Comment by Booplicate** [comment]
We do not support unofficial versions.
