### ISSUE TITLE
Monika File do not work

### ISSUE THREAD

**Issue by Wilson-Smith** [Monika-After-Story/MonikaModDev#10241]
Yesterday,  I took Monika to a USB.

It was all right, but then when I tried to open again the game and she has gone.

The file is in the character folder, but still no monika.

Exist the file and it is in the folder, but the program behaves like it doesn't exist.

I'm open to suggestions, thanks for your attention.

**Comment by Booplicate** [comment]
[Restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).
