### ISSUE TITLE
maybe a good idea

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10247]
I was thinking, monika can't see us and using a webcam would be almost impossable, but could we make it so she can see a png file in the character folder named something like "me.png" and if the player does this it starts a diolog about this
I would do this but I know nothing about coding and I seems like it would be hard, I'll keep looking into it

**Comment by Booplicate** [comment]
It's not that accessing a webcam is impossible, it's detecting and recognising face and somehow commenting on it is what's nearly impossible.
