### ISSUE TITLE
Unable to gain affection pts after gifting. Registering as 0.0 pts when gifting

### ISSUE THREAD

**Issue by defnotlsplash** [Monika-After-Story/MonikaModDev#10248]
So i recently reached my 400 affection milestone and i wanted to gift the promise ring to monika (and i did). Just after i gifted, i checked my aff_log.log file. i went to my latest gifting attempt. it registered as 0 aff gain. (20.0 -> 0.0) and my affection wasn't changed. i was stuck at 429 affection pts after gifting. (i know i reached my limit but it said !BYPASS!)

(P.S: I never made changes to my client/mod nor the settings of my computer. it was loaded on a older persistent when i upgraded my os)

Log File of my current affection pts for my persistent save:
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/15273778/aff_log.log)

**Comment by Booplicate** [comment]
It's normal, you're gaining the affection.
