### ISSUE TITLE
Problem with Monica's name

### ISSUE THREAD

**Issue by Nordavindi** [Monika-After-Story/MonikaModDev#10245]
Hello.  In MAS, a situation arose where when a function appeared, give a nickname to Monica upon reaching 100 affection points, and if you give her a name that she does not like, she may be offended and remove (in my case) 50 affection points, but upon reaching 100 points again this  the function did not reappear.  I called her Sayori, just out of interest, and of course I immediately apologized.  What should you do in such a situation: reinstall the mod completely or continue to increase affection and wait for such a function?  Version 0.12.5, there were no backups before this situation(

**Comment by Booplicate** [comment]
Moni**k**a*

the option should reappear once you apologise and is eligible again. Unless you've done it multiple times.
