### ISSUE TITLE
How do you unlock chess?

### ISSUE THREAD

**Issue by Gerva2** [Monika-After-Story/MonikaModDev#10256]
Hello, I have a question. Does anyone know how to unlock chess? Because, I have already unlocked the hangman, the Nou and the piano. But I haven't been able to unlock the chess, even though Monika mentioned it to me.
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/15462157/ev_dump.log)

**Comment by Wingdinggaster656** [comment]
Are you using a translated version?

**Comment by Gerva2** [comment]
Yes, I am using a translated version. could be that the problem?

**Comment by Wingdinggaster656** [comment]
Probably.

Translated version has bugs that aren't in the original version, especially when it comes to unlocking. Even if you switch to the original version now, there's no guarantee that you'll be able to unlock it properly.

Please try contacting the author of your translation, after all, we can't be sure what all the changes are in your translation.

**Comment by Gerva2** [comment]
Ok, I will try to contact the author of my translation. Thanks for the help.
