### ISSUE TITLE
[Suggestion] - That monika could acess your Webcam

### ISSUE THREAD

**Issue by RenanDDLC** [Monika-After-Story/MonikaModDev#10251]
Your suggestion goes here

It would be nice if Monika could have access to my webcam. that she could even watch me sleeping hehe~

**Comment by Buul135** [comment]
it was said before, I would simply be near impossable to make work for all web cams on all platforms, she also couldn't react to anything going on, it would be nice but too hard

**Comment by RenanDDLC** [comment]
Well. I'm learning how to code. so next year. if you want some help in the project. just leave an message in my discord! i would love to help :D

discord: therenanoriginal

**Comment by RenanDDLC** [comment]
wrong button. sorry!
