### ISSUE TITLE
Japnese Script

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10258]
I was trying to get some Japanese writing for fun and the topic wouldn't show, I'm guesssing thats beacuse the game doesn't have the font but I'm not sure if I'm right or where I'd find something like that if anybody can help

**Comment by Wingdinggaster656** [comment]
If you are talking about how to show Japanese text, take a look at this example:

```
label greeting_hai_domo:
    m 1hub "{=jpn_text}はいどうもー!{/=jpn_text}"
    m "Virtual girlfriend, Monika here!"
    m 1hksdlb "Ahaha, sorry! I've been watching a certain Virtual Youtuber lately."
    m 1eua "I have to say, she's rather charming..."
```

**Comment by Buul135** [comment]
> If you are talking about how to show Japanese text, take a look at this example:
> 
> ```
> label greeting_hai_domo:
>     m 1hub "{=jpn_text}はいどうもー!{/=jpn_text}"
>     m "Virtual girlfriend, Monika here!"
>     m 1hksdlb "Ahaha, sorry! I've been watching a certain Virtual Youtuber lately."
>     m 1eua "I have to say, she's rather charming..."
> ```

thanks
