### ISSUE TITLE
I took Monika somewhere on a USB drive, pasted her back into the characters folder, but she's gone when I open the game!

### ISSUE THREAD

**Issue by ysmafuyufan** [Monika-After-Story/MonikaModDev#10259]
I put her on usb, brought her back but when I opened the game, she wasn't there.

**Comment by Buul135** [comment]
Did you put the file, back in the character folder

**Comment by ysmafuyufan** [comment]
update: SOrry I completely forgot, I dunno what happened but I used a back up and put the persistent files in the renpy app data directory and it worked
