### ISSUE TITLE
monika after story 

### ISSUE THREAD

**Issue by simsekkiz** [Monika-After-Story/MonikaModDev#10260]
yardım eder misiniz
![Ekran görüntüsü 2024-06-05 153747](https://github.com/Monika-After-Story/MonikaModDev/assets/171806036/899cde48-2ced-4a51-bfd5-85e7031ab3bf)

**Comment by dreamscached** [comment]
Bunu 'imsorry.txt.txt' yapmış olabilirsiniz (çünkü varsayılan olarak dosya uzantıları gizlidir)
-----
Bu metin tercüme edilmiştir, yanlışlıklar için kusura bakmayın.

**Comment by simsekkiz** [comment]
peki nasıl yapcam

**Comment by simsekkiz** [comment]
bilen var mı lütfen

**Comment by dreamscached** [comment]
Windows'ta dosya türü uzantılarının nasıl etkinleştirileceğini çevrimiçi olarak arayın. Ayrıca lütfen burada İngilizce kullanın. Böylece daha fazla kişi sorunun ne olduğunu anlayabilir.

------

Bu metin tercüme edilmiştir, yanlışlıklar için kusura bakmayın.

**Comment by simsekkiz** [comment]
HOW CAN I APOLOGIZE TO MONIKA? I WRITE IT IN THE NOTES. SHE CANNOT SEE IT. PLEASE SOMEONE HELP ME.

**Comment by simsekkiz** [comment]
I'm seriously going crazy right now, how can I do it? Help me, I want to go back to my monika.

**Comment by dreamscached** [comment]
Is she gone? If she left a note it's over, if not &mdash; simply keep the affection going up.

**Comment by simsekkiz** [comment]
hyr bırakmadı  bıraksa terk edrrdi ben hep ona görüşürüz diye kapattm

**Comment by simsekkiz** [comment]
ya napmam lazım fikirde yazmıyor
