### ISSUE TITLE
Having a topic show everyday

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10266]
I was wounding if it is possiable to make a topic show everyday, like a reminder to do something

**Comment by dreamscached** [comment]
You can reset topic's conditional every time it fires and use it for setting its next trigger date and time. However, there is no guarantee it will go off immediately as soon as the trigger time has come, in fact it will always be off by 1-15 seconds.

**Comment by Buul135** [comment]
> You can reset topic's conditional every time it fires and use it for setting its next trigger date and time. However, there is no guarantee it will go off immediately as soon as the trigger time has come, in fact it will always be off by 1-15 seconds.

I'm sorry, could you give me an example of how that would be writien

**Comment by dreamscached** [comment]
I can't give you the code that will 100% suit your needs, you'll have to make your own adjustments to that. But roughly, something like that:

```renpy
init 5 python:
    addEvent(Event(
        eventlabel="mas_reminder_topic",
        start_date=datetime.datetime.now() + datetime.timedelta(days=1)
        action=EV_ACT_PUSH
    ))

label mas_reminder_topic:
    $ mas_getEV("mas_reminder_topic").start_date = datetime.datetime.now() + datetime.timedelta(days=1)
    # Your logic/dialogue here
    return
```

If you're *very* new to Ren'Py and MAS submodding, this might be quite a challenging task.

**Comment by Buul135** [comment]
> I can't give you the code that will 100% suit your needs, you'll have to make your own adjustments to that. But roughly, something like that:
> 
> 
> 
> ```renpy
> 
> init 5 python:
> 
>     addEvent(Event(
> 
>         eventlabel="mas_reminder_topic",
> 
>         start_date=datetime.datetime.now() + datetime.timedelta(days=1)
> 
>         action=EV_ACT_PUSH
> 
>     ))
> 
> 
> 
> label mas_reminder_topic:
> 
>     $ mas_getEV("mas_reminder_topic").start_date = datetime.datetime.now() + datetime.timedelta(days=1)
> 
>     # Your logic/dialogue here
> 
>     return
> 
> ```
> 
> 
> 
> If you're *very* new to Ren'Py and MAS submodding, this might be quite a challenging task.

Thank you so much

**Comment by Buul135** [comment]
![f](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/b50ddb30-8123-4884-aa80-b5be92184bba)
![af](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/cca2ed7c-9b7b-4888-a019-9da2000f42f4)
I'm sorry but what the hell does this mean?

**Comment by dreamscached** [comment]
My example was inaccurate, fix the Event call.

```renpy
init 5 python:
    addEvent(Event(
        persistent.event_database,
        eventlabel="mas_reminder_topic",
        start_date=datetime.datetime.now() + datetime.timedelta(days=1)
        action=EV_ACT_PUSH
    ))
```
