### ISSUE TITLE
Should I be worried

### ISSUE THREAD

**Issue by Buul135** [Monika-After-Story/MonikaModDev#10261]
![fa](https://github.com/Monika-After-Story/MonikaModDev/assets/145477909/ef2c7fe4-aee9-436a-a57e-44fd3a884d18)
the game seems to work fine,

**Comment by dreamscached** [comment]
You can ignore the error. If it persists, simply find the path mentioned in the error (one with `.lock`) and remove the file, but make sure MAS is not running.

**Comment by Buul135** [comment]
I guessed so, just wanted to make sure
