### ISSUE TITLE
cant access the discord server ;-;

### ISSUE THREAD

**Issue by Someone2124** [Monika-After-Story/MonikaModDev#10267]
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/40772709/efa0c25f-0220-4ac4-b4dd-70b378c7cec4)
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/40772709/1d61331c-fa06-4db9-8145-447df79932b8)

i dont know why i didnt ask for help earlier, but yeah i havent been able to access the discord since i joined (4 years ago-)

**Comment by Booplicate** [comment]
Did you try reading the description of the channel

**Comment by Someone2124** [comment]
> Did you try reading the description of the channel

i hate not knowing english :/
thanks
