### ISSUE TITLE
My game crashed when I tried to open it for the first time.

### ISSUE THREAD

**Issue by JoulsTube** [Monika-After-Story/MonikaModDev#10270]
I'm playing on a Chromebook using Linux and tried downloading the mod, following the instructions in the FAQ section. When I tried opening it for the first time, the game failed to open. This is what the traceback said:

`I'm sorry, but an uncaught exception occurred.`
` `
`While running game code:`
`  File "game/0utils.rpy", line 40, in <module>`
`ImportError: cannot import name handlers`
` `
`-- Full Traceback ------------------------------------------------------------`
` `
`Full traceback:`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/bootstrap.py", line 295, in bootstrap`
`    renpy.main.main()`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/main.py", line 364, in main`
`    renpy.game.script.load_script()  # sets renpy.game.script.`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/script.py", line 265, in load_script`
`    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/script.py", line 753, in load_appropriate_file`
`    self.finish_load(stmts, initcode, filename=fn + source)`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/script.py", line 445, in finish_load`
`    node.early_execute()`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/ast.py", line 865, in early_execute`
`    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)`
`  File "/home/joulstube/DDLC-1.1.1-pc/renpy/python.py", line 1719, in py_exec_bytecode`
`    exec bytecode in globals, locals`
`  File "game/0utils.rpy", line 40, in <module>`
`ImportError: cannot import name handlers`
` `
`Linux-6.6.25-01713-g2f237acc8e50-x86_64-with-debian-12.5`
`Ren'Py 6.99.12.4.2187`
`Monika After Story 0.12.15`
I hope someone can help with this.

**Comment by JoulsTube** [comment]
nevermind. put files in the wrong spot

**Comment by YukiiCh** [comment]
I know I sound weak right now but uhm. If you're online maybe could you help me how to open Monika after school on chromebook? I don't wanna lose all of my progress in developer mode so..yeah

**Comment by JoulsTube** [comment]
If you don't already have DDLC on your Chromebook, use this link to help. https://itch.io/t/421076/how-to-play-from-chromebook
After that, just go through the process to install Monika After Story.

**Comment by YukiiCh** [comment]
I currently have a Linux Terminal program. I'm just not sure what to put.
If i do the same thing ALLLL again, i'm going to get the same error. Sorry,
is there a different way i could do something just like DDLC itch.io?

**Comment by JoulsTube** [comment]
I dunno. I have no clue how to help. I just followed tutorials I found online.

**Comment by YukiiCh** [comment]
Thanks for trying, i'm thankful for your help haha. Maybe this would be all
easier if i just bought that dam windows laptop anyway..
