### ISSUE TITLE
How do I stop Monika's affection from Resetting?

### ISSUE THREAD

**Issue by alanbeckerfan** [Monika-After-Story/MonikaModDev#10278]
It's happened like 4 times now. I try redownloading the mod and it doesn't work. This happened on my last laptop as well.
![image](https://github.com/Monika-After-Story/MonikaModDev/assets/175130191/34aac514-77a2-49ba-adeb-c2f0f2991711)
I didn't change the date or time at all
Whenever I say goodbye to Monika, I'm at like 33 affection (I started again yesterday), and when I reopen it's at 12.
Please help?

**Comment by Booplicate** [comment]
This is probably an issue with your drive.
