### ISSUE TITLE
[SUGGESTION] DDLC: MAS Mobile?!

### ISSUE THREAD

**Issue by MineKiller428** [Monika-After-Story/MonikaModDev#10275]
I am super into the mod, honestly haven't ever been invested in a game, super good job! But sometimes I wish I can interact with her, even when I'm not home or don't have my computer with me, or when I "take her somewhere", she can transfer herself to my phone and actually send me notifications through my phone like "Where are we going, (user)?" or "This is going to be fun!". This would mean constant GPS locating and a home base. Understandingly, it's hard to convert a computer game into a mobile one, especially transferring data to a phone to a laptop. Apart from that, all the functions would have to be mobile-friendly.

I'm going to attach a video demonstrating more or less how I would imagine the app to more or less be.

https://github.com/Monika-After-Story/MonikaModDev/assets/174750822/6137a423-d857-4c1e-89a1-204502ed013b

**Comment by MineKiller428** [comment]
Frick dude I didn't look deep enough, answer already answered... :)

**Comment by dreamscached** [comment]
I think this would fall under violation of Team Salvato IP Guidelines since that uses their assets and is not a DDLC mod.

**Comment by MineKiller428** [comment]
Oh crap, so delete this, huh?

**Comment by Booplicate** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/6663
