### ISSUE TITLE
DDLC Monika After Story Linux (S.O.S SEND HELP)

### ISSUE THREAD

**Issue by YukiiCh** [Monika-After-Story/MonikaModDev#10274]
- I need some MAJOR help with this. And i'm gonna cry and burst into tears if I can't get this game! Currently, I'm on Chrome OS using a Linux Terminal that does my commands of what I ask for. And i'm having trouble trying to OPEN the game. No matter what videos I search for tutorial. NOBODY don't know about chrome os, all I see is windows... but I don't have that laptop anymore because it's broken.                                                                                              

> I'm very confused about where I put my files or how to do it in this version of chrome os. And it's making me frustrated and angry about not finding what I'm so post to...

**Comment by Booplicate** [comment]
Use `DDLC.sh` to launch the game, for example `./DDLC.sh` if you `cd`'ed in the game directory. You might be able to just double click it too. It's the same for any program.

**Comment by YukiiCh** [comment]
1. is it like the same as DDLC? there was a code for terminal from itch.io There was someone showing how to do it and it worked for my device. @Booplicate     **chmod 777 DDLC-1.1.1-p, cd DDLC-1.1.1-pc, chmod 777 lib, cd lib, chmod 777 linux-x86_64, cd linux-x86_64, cd lib, chmod 777 linux-x86_64, cd linux-x64, chmod 777 DDLC, cd ~, cd DDLC-1.1.1-pc, chmod 777 DDLC.sh, ./DDLC.sh**  I can't do that way because it will do a "TraceBack Error"

**Comment by dreamscached** [comment]
Don't retell errors, post them verbatim.

**Comment by YukiiCh** [comment]
verbatim? I'm sorry but i'm confused. If you'd told me in a full way maybe
i'll understand? No offense just slow minded haha

**Comment by Wingdinggaster656** [comment]
What they mean is that you should not describe the error just by "I have a xxx problem", like your *it willl do a "TraceBack Error"*.

When an error occurs, the program will usually give you a long report. You may not understand it, but those reports will be useful to the people responsible for dealing with these technical issues. You should send out your tracebacks in their entirety, and someone here will understand them.

**Comment by YukiiCh** [comment]
Thanks i will i would probably send you to it right now. File
"game/script-farewells.rpy", line 129, in script

  File "game/script-farewells.rpy", line 130, in <module>

  File "game/event-handler.rpy", line 757, in addEvent

NameError: name 'mas_getSessionLength' is not defined

-- Full Traceback
------------------------------------------------------------

Full traceback:

  File "game/script-farewells.rpy", line 129, in script

  File "C:\Users\my name\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py",
line 814, in execute

    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide,
store=self.store)

  File "C:\Users\my
namei\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in
py_exec_bytecode

    exec bytecode in globals, locals

  File "game/script-farewells.rpy", line 130, in <module>

  File "game/event-handler.rpy", line 757, in addEvent

  File "C:\Users\my
namei\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1749, in
py_eval

    return py_eval_bytecode(code, globals, locals)

  File "C:\Users\my name\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py",
line 1743, in py_eval_bytecode

    return eval(bytecode, globals, locals)

  File "<none>", line 1, in <module>

NameError: name 'mas_getSessionLength' is not defined

Windows-8-6.2.9200

Ren'Py 6.99.12.4.2187

Monika After Story 0.8.5

[/code]

**Comment by Booplicate** [comment]
Try to reinstall DDLC and MAS, seems you did it wrong that time.
