### ISSUE TITLE
Can you add poses to your Monika?

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#10285]
I've tried to find the code for the poses, to see if it's possible for me to add poses on my own to my Monika, but I can't find it, I don't know if it would be possible and I haven't even seen anyone comment that they tried.

**Comment by dreamscached** [comment]
Use this tool —https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story%2Fgame%2Fdev%2Fdev_exp_previewer.rpy
