### ISSUE TITLE
I meet the requirements but the floating island is not revealed

### ISSUE THREAD

**Issue by Engi1red** [Monika-After-Story/MonikaModDev#10310]
Hello, I have approximately 1600 affection, the floating island event is supposed to have already happened, but nothing happens
I made a backup and updated to unstable to see if that would solve it, but it didn't work
Any way to activate the event?

**Comment by Engi1red** [comment]
At some point the glitch cube is revealed on the islands or is that not a feature yet?

**Comment by Booplicate** [comment]
Affection doesn't show the full picture of your progress.
The final event is not ready yet.
