### ISSUE TITLE
Add toggle for an optional ground layer

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#10342]
This thing hasn't been updated in a year and I have for the most part left the MAS community and I'm making one final contribution before flying off into the sunset. Some people might find it offputting (including me) that the room is just floating in space. The main question that could arise from this is "Are we just floating through space and time?"

We should add a toggle that simply overlays grass, trees and seasonal effects.

**Comment by TheSystemGuy1337** [comment]
> Well no, it's called _space_room for a reason. Planetary structures are planned, but the spaceroom will stay in space.


I'll admit, this one was stupid like the rest of my suggestions. I'm sure someone down the road will likely add a groundroom submod to the game, but that's unlikely. I'm retiring.

**Comment by Booplicate** [comment]
chatbots != AI
