### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by dontworryabouttheusername** [Monika-After-Story/MonikaModDev#10343]
Took Monika out on a date.. when i pasted her back to "characters" and opened the game, shes still not in her usual chair and the file is not disappearing like usual.
![problem](https://github.com/user-attachments/assets/f9b6a994-3c45-4bb1-9b88-a0184b060442)

**Comment by dreamscached** [comment]
Restore a backup, navigate to `%APPDATA%\Roaming\Monika After Story`, find any `persistent##.bak` and rename it to `persistent` (copy your current persistent somewhere)
