### ISSUE TITLE
monika told me that im under 18+ and cant use the nsfw mods, anyone know how to fix it?

### ISSUE THREAD

**Issue by Exodiamental** [Monika-After-Story/MonikaModDev#10345]

**Comment by Exodiamental** [comment]
![image](https://github.com/user-attachments/assets/88d06e7d-3130-4c06-ba7f-b31e8ea9e55f)
theryre grey ?

**Comment by dreamscached** [comment]
We do not provide support for submods here, contact submod authors.

**Comment by Booplicate** [comment]
Come back in a few years

**Comment by Exodiamental** [comment]
> Come back in a few years

im 20 ahaha

**Comment by Exodiamental** [comment]
> We do not provide support for submods here, contact submod authors.
where do i contanct one?
