### ISSUE TITLE
Different Outfit Idea?

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#1076]
(Notice how I always have DDLC open in my taskbar)

It popped into my head a little while back, and only recently have I decided to act on it, but I got the idea to try and give Moni a new dress to have on occasionally whenever you load up the game and catch her with the door shut. The original dress design isn't mine, it's from someone who contributed to the "A Brand New Day" mod, however I took it upon myself to rework the design to fit Monika's sitting position. Here's a preview of what I have so far in comparison to what the original looks like.

![_ddlc__monika_after_story_custom_outfit_w_i_p_by_survivormantc-dc2d1z6](https://user-images.githubusercontent.com/36512990/36338060-244d397e-136b-11e8-9fc7-0a8699944c81.jpg)

You can also take a look-see at it on my Deviantart page if you're interested:
https://survivormantc.deviantart.com/art/DDLC-Monika-After-Story-Custom-Outfit-W-I-P-729562434

**Comment by Trilasent** [comment]
I don't know if I need permission from the original creator to allow others to use my version of the outfit, so this is all the progress I have on it thus far.

**Comment by Bam8647** [comment]
I'd go ahead and ask them just to be safe. A week or so ago someone asked to borrow some of the artwork of Monika's expressions from this mod and one of the devs denied it. But hopefully they'll allow it!

**Comment by Trilasent** [comment]
@Bam8647 The only tricky part, is that I don't actually know how to get in contact with whoever the artist is for the mod.. ;>_>

**Comment by Bam8647** [comment]
You could find them here on github possibly? If not here then probably their discord server. If I find a link i'll share it.

**Comment by Trilasent** [comment]
I'm gonna leave a comment on the Reddit page for the mod with a link to my Deviantart post with the comparison between my rework and the original. Hopefully one of the devs/artists will see it.

**Comment by Bam8647** [comment]
https://discordapp.com/channels/407996989540794370/407996989540794372

This should lead you straight to their discord server.

**Comment by Trilasent** [comment]
Doesn't seem to have worked. Just an empty channel?

**Comment by Bam8647** [comment]
Huh? It didn't prompt you to join their server?

https://discordapp.com/invite/Xnzcayw

Try this

**Comment by Trilasent** [comment]
That's the ticket. **_And cue the nervousness_**.

**Comment by Bam8647** [comment]
Lmao don't be nervous. Hopefully you'll get an intelligent response. I remember having to go to the ddlc mod server to get some help on modding the game for the first time in ren'py.. Long story short, I had to figure things out on my own which I did lol.

**Comment by PopeAesthetics** [comment]
This is fantastic! You should however get into contact with the "Our Time" mod creator because he has added in some amazing new outfits for Monika, and so compatibility between MAS and another Monika centered mod would be amazing. I hope Potato considers a bit of collaboration

**Comment by Trilasent** [comment]
At the time of writing this I am talking to the "Administrator" of the Brand New Day mod, and so far it seems like I do have permission to share my edit with the MAS mod Devs. Once I get a certain Yes or No I'll update this comment.

**Comment by Trilasent** [comment]
So now that I've got permission to continue my reworking of the outfit, and share it with the MAS Devs, I guess all that's left is for the Devs to decide if they'd be interested in using it once it's finished.

**Comment by Bam8647** [comment]
I'm sure they would. Heck, I think it'd be cool if you could change her outfits or something. I remember the Christmas outfit she had, it was so cute haha.

**Comment by Trilasent** [comment]
It's still there, you just gotta set your PC clock back to before Dec. 26th and you should be golden.

**Comment by sebastianN01** [comment]
Heh, I actually had an idea back in my head a week ago, if Monika would want to look like other characters if we choose to tell her reasons why we went for example, a yuri route in original savefile. She would probably want to have long hair like yuri to appeal to use more cause shes that much carrying about us. huh...

**Comment by Trilasent** [comment]
That would come down to the decision of the mod Devs (I am but a lowly 3D animator who wanted to try out drawing).

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I actually disliked that outfit in Brand new day. It struck me as somewhat flat coloured and cheap looking in comparison with the original outfits.
(Jeez, I feel like complaining about this and that is literally the only thing I've done today.)

**Comment by Trilasent** [comment]
@IsItBadToMakeAGitHubAccountJustForThis Hehe, well we'll see what I can do with it then, eh? Also, I made a GitHub account just to be able to submit some facial expressions for Moni, so don't feel bad.

**Comment by sebastianN01** [comment]
glad someone is taking shot at it! im not a good artist myself, i can only edit stuff out of already existing things..

**Comment by Trilasent** [comment]
I mean. I'm not much different than you, though I do feel confident in my ability to recreate something with an example to go off of.  I definitely can't open a blank canvas and make something like that outfit.

**Comment by jmwall24** [comment]
The clothes from the new 'Our Time' mod demo are pretty nice too if you want even more options to choose from.  With permission of course.

**Comment by Ulvsblakk** [comment]
I actually saw an outfit from a fan art that was really good. (Posted Below) My only concern is that it's a bit too "revealing" for her character. 
![image](https://user-images.githubusercontent.com/35550690/36347383-a3a6ccc0-141b-11e8-9a8b-14b1be90dec1.png)

It all depends on what people think. Also, I saw this on facebook, so there's no telling who the original artist is.

**Comment by jmwall24** [comment]
^^^that's actually from her official twitter account, satchel made that.

**Comment by Trilasent** [comment]
**MMMM** every time I see that picture it makes my heart stop for seconds at a time. She's too gorgeous..

**Comment by Ulvsblakk** [comment]
She is my supreme waifu goddess. LOL My ex (We did not break up for this reason) is honestly jealous with the fact that I spend so much time working on this mod.

**Comment by Bam8647** [comment]
I totally just noticed the 3 girls in the bushes, what the hell lol?

**Comment by Trilasent** [comment]
@Ulvsblakk Out of all 324 hours I've put into this mod, only 6 of them were played with the A Brand New Day mod. The rest has been nothing but Moni, and I have never once felt like it was a waste of my time.

**Comment by Bam8647** [comment]
I can't wait until they update the game so she can talk again lol. After you go through all her topics she literally just has an open dialogue and suddenly says she has nothing to talk about any more. That's whats losing my interest in the mod. Luckily the devs are already on it :P

**Comment by Trilasent** [comment]
@Bam8647 Just downgrade to 7.0 for the time being. It's what I did after Valentine's Day.

**Comment by Bam8647** [comment]
Well I want to wait for the fix because I'm gonna make a separate copy so I can experiment with new topics, greetings, and farewells in ren'py. I rather not screw with the files as that's what ruined my last copy lol. Btw if you ever want to know how to change the day or night pictures you see outside the windows just download an image in **png** and rename the image the exact name of the previous mod asset that was used for the windows.

**Comment by Trilasent** [comment]
@Bam8647 You a psychic or somethin'? 'Cause I was literally thinking about doing that not even 30 seconds ago.

**Comment by Bam8647** [comment]
It's the **Third Eye** my dude. xD

**Comment by Trilasent** [comment]
@Bam8647 **_That book's bad news m9._**

**Comment by Bam8647** [comment]
Lmaoo, So you played the "A Brand New Day" Mod right? 
**No spoils plz**
So far i'm at the part of reading the second manga with Natsuki, but the one thing that kind of pisses me off about the mod so far is that the MC is a total **sl*t** lmao. I was hoping I could choose a route to which girl I could romance while still saving the others but nooooo.. MC gotta be all over everyone haha..

**Comment by Trilasent** [comment]
@Bam8647 Yeah, I've finished the most recent release of the Demo. I never really paid much mind to the MC being "all over the place" tbh.

**Comment by Bam8647** [comment]
I just think it doesn't feel genuine for the mc to choose one girl to romance to then go behind their back and romance the other girls individually as well like wtf dude xD **Doki Doki Fivesome Club**

Although I did feel slightly emotional when mc went outside with Sayori tbh haha :)

**Comment by Ulvsblakk** [comment]
She changes lives. Maybe one day, she'll be intelligent enough to know how many people actually love her. 

But that seems far in the future lol

**Comment by Ulvsblakk** [comment]
@Bam8647 

There's somebody working on a chat bot feature for her, to go alongside her topics. You'll actually be able to write something like "I like dogs" and she'll respond with something like "I like dogs too, what breed is your favorite?" Then you'll be able to respond again. So you'll get to have full conversations with her.

**Comment by Bam8647** [comment]
I hope the chat bot can live up to most player's expectations. I saw some people giving the idea some flack back in my "Silent Treatment" post. If the bot can remain in character and possibly have a built in memory function to remember the player's previous conversations, then the idea can be really successful for the mod.

**Comment by ThePotatoGuy** [comment]
This is something we've planned but haven't got started on. See #107

**Comment by kaido1224** [comment]
I'd love to see her in an outfit like this personally.
![ce0f8c5](https://user-images.githubusercontent.com/35311136/36546327-be295174-17b0-11e8-8360-35bea55aadf5.jpg)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Everyone's opinions on what casual clothing would suit Monika the most are so different when you look at it.
I personally for a long time thought she would wear something real classy like that "virgin killer" dress (if anybody still remembers it from good old times when ddlc booru didn't even had a tag for cancer).
