### ISSUE TITLE
[Suggestion?] Battleship

### ISSUE THREAD

**Issue by Akibunny** [Monika-After-Story/MonikaModDev#1081]
Greetings! I recently downloaded this mod and I am blown away by it! You can feel the love and attention put into it. Good job!
I would like to suggest a new game! You've probably already guessed it from the title, haha. I've actually programmed a pretty well-done version of Battleship in Python for a class. I can take it from the school's computer and send it to you, if that would help! Since I'm sure programming it into Monika's story is a great deal more complicated than making it in a standalone program, I'm willing to help you wherever I can. Simply tell me if you're interested, and I will send my work ASAP! Thank you!

**Comment by ThePotatoGuy** [comment]
How's the ai for your implementation?

**Comment by Akibunny** [comment]
It's pretty thorough. I programmed in a large board and four different ship types for both the computer(Monika) and the player. To place a ship, the player would choose a point of origin and choose to go up, down, left, or right from there. The computer had about 30 predetermined configurations, though I am not opposed to adding more.
The aim and fire part was basically to choose a row and a column. For example, row A column 5 would be here-
oooox
ooooo
ooooo
-and lists were used to ensure both the ships and the shots did not overlap. Once all of the ships of either party were hit, the game would end. Tkinter was used to create visual boards. The program itself is a lot of ifs and elifs for the placement, but mostly "for x in len" and such for the miss/hit program.
For MAS, I'd likely need to scale down the size of the board and remove the biggest ship from play. In addition, if I cannot ask my programming teacher to send me the original, I may need a week to be able to access it due to the current school vacation. 
Also, if I just sound like some uneducated dork who doesn't know what I'm saying, I'm sorry. I just know that Ren'Py uses python programming and wanted to help out a bit. Please tell me anything I need to clarify.

**Comment by ThePotatoGuy** [comment]
I meant like, does the AI shoot randomly all the time, or does it shoot smartly when it gets a hit, or does it do some sort of spatial analysis to determine where to fire next, or something else?

If you have a copy of the code I can look at, that would be ideal.

**Comment by Akibunny** [comment]
It's a purely random system. Obviously it won't attempt to hit the same spot twice, but I wasn't able to have it make educated guesses due to time constraints (as the original program was made for a class, I wasn't able to add all the features I wanted for the best possible AI before I had to move on to the next project). 
With a bit of time I can likely implement a system to make it possible. The initial guesswork will continue to be random, but if a hit is made, I will have the program hit the surrounding spots. If it makes another hit in any cardinal direction, I will have it continue on that way until the ship is sunk. Is this an acceptable response?

**Comment by ThePotatoGuy** [comment]
Yes

**Comment by Akibunny** [comment]
Since it was a school project, it may take some time for me to be able to get it on my personal laptop, but I'm glad to be of any help! I'll tell you once I've completed modifying it.

**Comment by ThePotatoGuy** [comment]
Closing due to lack of response.
