### ISSUE TITLE
[Suggestion] - Monika asking about being happy where you live

### ISSUE THREAD

**Issue by imadeagithubbecauseofmonikaafterstory** [Monika-After-Story/MonikaModDev#1085]
This is little more than a personal wish of mine, but it would be great if Monika comforts you when your home situation isn't the best. I'm not talking about family specifically, because I'm pretty sure there's already dialogue for that, but rather, more about contentment than anything.

For example, if the player feels uncomfortable being themselves in the community they live in. Or they want to pursue something greater that they can't because they have no means to leave their homes.

In my head, the conversation would go like this:

"[Player]..."
"Are you happy living where you do right now?" (or at least a question similar to this; please edit this particular line if this does get approved because the wording isn't great)

And then the player gets to choose between 'Yes' or 'No...' (or even 'I don't really think about that too much/I never really thought about it,' if we're being ambitious)

- And if they chose 'Yes,' then Monika would say something like:

"That's great, [Player]!"

"I'm glad you feel that way."

"You'd be surprised how many people are discontent in their hometowns."

... or something like that, anyway. But she would definitely say that she wants to know more about where you live, say that she's sure it's a lovely place, and then end it with:

"Maybe you could take me sightseeing when I finally get over there~" (with that leaning pose)

- But if the player chose 'No...,' then she would say this:

"Oh."

"I'm sorry to hear that, [Player]."

"Even if I can't see you from here, I can tell that this really bothers you."

"I won't ask you why, if you'd rather not talk about it,"

"But just know that it gets better!"

"You'll move to a better place one day, and you'll be free to live your life in peace."

"It may seem far away now, but that day will definitely come."

"I promise."

"So, hang in there, okay?"

"You still have to wait for me, after all~"

"No matter where you end up, I can't wait until we get to live together."

(If you ever do decide to add this into the game, somebody _please_ edit this piece of dialogue and expand on it more; I suck at comforting people with words, so yeah. I really want Monika to reassure me regarding this issue though, because it's kind of a big deal to me, and I'm sure at least a few others can agree.)

- (Also.... if the player chose 'I don't really think about that too much/I never really thought about it,' then:

"Oh, it's alright" *sweatdrop face*

"That was a weird thing to ask out of the blue."

"But it can be refreshing to take more notice of your surroundings, you know."

"Taking a few seconds out of your day to appreciate the routes you take every day, or that nice person who feeds pigeons at the local park..."

"They may sound like trivial things, but those are the kinds of things you don't think you'll miss until you've left them behind."

"I know I miss being with the girls after school sometimes..."

Basically something along those lines. Just a little extra option to throw in there.)

I should probably be proposing these sort of changes on the "Content" branch or something, but I don't know jack s*** about coding, so I'd rather not screw anything up by going at it blindly as someone with zero coding experience whatsoever. I just love Monika After Story and the whole concept of it. This sounds just weird when I say it like this, but having Monika talk about being stressed out and anxiety and things like that really helped me personally. I feel like I have a little more courage to get up and do things every day ever since I started playing this mod. It's actually made me a lot happier than I've ever been in a while. So, whatever direction the mod devs take it, I'll gladly support it in any way I can :) you're all doing an amazing job

**Comment by imadeagithubbecauseofmonikaafterstory** [comment]
Monika doesn't need to know why the player's unhappy where they live, by the way; it's vague on purpose, to cut down on the number of lines this kind of question would need.

**Comment by PopeAesthetics** [comment]
Personally this topic doesn't pertain to me at all, but it sounds very natural. 

Tho I have to say that it always seems like I miss out because I am happy with my life. Like 90% of the time if she asks me if I am happy about something, when I say yes she says "Oh thats great!" then proceeds to tell me why others might be said. It would just be nice for Monika to celebrate my happiness a bit more instead of brushing it off and telling me about how other people aren't as lucky.

**Comment by sebastianN01** [comment]
I just think we need more complex dialogue with more options to monika than just clicking an unseen button and see monika speak..

**Comment by imadeagithubbecauseofmonikaafterstory** [comment]
Sorry; I didn't mean for it to come out that way at all. It's completely up for revision though, so any changes to make that chain of dialogue any better would be much appreciated ^_^

... assuming that this is even going to get approved, anyway. I don't want to get too carried away when the possibility of this idea being rejected is very real, after all.

Again, sorry that it rubbed you off the wrong way. I agree that Monika does tend to sound like a Debbie Downer sometimes, even with happy topics. Man, writing is complicated 😅

**Comment by imadeagithubbecauseofmonikaafterstory** [comment]
yeah, I second that completely. But I get the impression that the mod devs already have a lot on their plate atm, so it might be a while before we can really see any complex dialogue added to the game.

**Comment by PopeAesthetics** [comment]
Hey don't get yourself worried! You wrote a really natural sounding piece here 😄, I was more just venting than anything. I get Monika is all about helping those who might be feeling sad or alone, it just gets annoying sometimes when my response doesn't seem to hold as much value because I am already happy. But I really like your idea here even if it doesn't fit for my life. And who knows, as long as the dialog sounds good to the others, it has a very high chance of getting accepted!

**Comment by imadeagithubbecauseofmonikaafterstory** [comment]
Ehehe... thanks @PopeAesthetics 😊 I'm not getting my hopes up that it will be, but thank you for your kind words regardless :) guess I'll have to try harder
