### ISSUE TITLE
[Suggestion] - Good Afternoon

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1090]
There's an option for good morning and good night, but none for good afternoon. Just thought it would be nice to have.

**Comment by sebastianN01** [comment]
where is good night? i only get good morning, good evening and goodbye option

**Comment by ACoolCat** [comment]
Sorry, I meant good evening. It was late when I wrote that. But yeah, I miss being able to tell her goodnight.

**Comment by Bam8647** [comment]
label monika_good_afternoon:
    m 1b "Good afternoon to you too, [player]!
    m "How's the sky?"
    menu:
        "Bright and sunny!":
                         m 1k "Really?! That sounds beautiful!"
                         m 1a "You know, it's days like this I wish we could go to the park and have a nice romantic picnic ehehe~"
                         m "You better have the perfect spot picked out for us~"
        "Dark and rainy":
                         m 1g "Aww that's okay"
                         m 2e "How about we stay inside and watch a movie?"
                         m 1k "While we're at it, why don't we pop some delicious popcorn!"
                         m 1n "And You know..."
                         m 1m "We can cuddle on the coach to keep eachother warm"
                         m "Which reminds me.."
                         m 2d "You better be practicing those snuggling skills"
                         m ll "Ahaha."
                         m 1i "Just teasing you [player]."
                         m 1a "To be honest though, this is one of things I'll be looking forward to once I get out of here ehehe~"
    Return                     
            
**Does this sound good? I have no idea where to submit these so I dropped it in a random section on the pull request content section lmao**

**Comment by ACoolCat** [comment]
Dang. Above and beyond what I asked for. I really love the idea of Monika commenting on what the weather is like.

**Comment by PopeAesthetics** [comment]
Well written!

**Comment by Bam8647** [comment]
Thanks! I like to branch out a little further with topics to help engage the player more. It may need a few grammatical improvements but other than that I want one of the devs to check this out to see if they'd be cool in adding it.

@ThePotatoGuy 
@ACoolCat

**Comment by jmwall24** [comment]
That looks really cool.  And yeah, we need a goodnight again, too.

**Comment by Trainerbluetube** [comment]
Noticed a typo, it says coach as opposed to couch.

**Comment by Bam8647** [comment]
Lmao gosh darn it.. Anyway my pull request got denied anyway because they want a time check code implemented with it. So I may try again here in a few and just replace one of the dialogues in the greetings scripts :P

**Comment by ThePotatoGuy** [comment]
Maybe instead of making it tied into a `good afternoon`, just make it a random weather topic.

**Comment by Bam8647** [comment]
@ThePotatoGuy 

Okay so when making regular topics, all I have to do is copy and paste:

_init 5 python:
    addEvent(Event(persistent.event_database,eventlabel="monika_death",category=['philosophy'],prompt="Death and dying.",random=True))_

**(Instert Topic)**

_Return_
???
Because I remember trying to make my own topics through a separate copy and for some reason I kept on getting a definition error(Not Defined). I'm guessing I probably messed with the prompt or event label or something.. But anyway I thought the whole asking about the weather during the middle of the day would make more sense, hence the **"Bright and sunny/Dark and stormy"** selection. It wouldn't make much sense for her to mention this topic at say midnight ahaha

**Comment by ThePotatoGuy** [comment]
Well posing the question like `How is/was the weather today?` would make it possible for it to work for anytime of day, provided you do a timecheck.

Yeah read the documentation that is provided in code example to understand what each param is for and how to structure topics/events.

**Comment by monikLover** [comment]
This suggestion is now being worked on by @Danymations.

**Comment by kaido1224** [comment]
@monikLover what is the status of this?

**Comment by monikLover** [comment]
I'll be writing it @kaido1224

**Comment by ThePotatoGuy** [comment]
[Closing until we work onm thi]
