### ISSUE TITLE
[Suggestion] - Monika Brain Teasers

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1102]
Monika seems to strike me as the type who'd be into puzzles and such. So maybe she could challenge the player to some riddles? Like, maybe she could say the riddle of the Detective and the Blacksmith Brothers and it prompts a multiple choice of James, Mark and Brad for you can pick the suspect. And other such riddles that could end in a multiple choice/yes or no for the player. 

Maybe if you fail the riddle she comments about how she'll leave it in the Play category till you're ready to try again. Riddles being unlocked via random dialogue before getting put in there.

**Comment by ThePotatoGuy** [comment]
@FireyAmber was working on riddles.

**Comment by FireyAmber** [comment]
About that, I'm just working on one topic that features a riddle with 3 possible answers. The topic would lock off once the player found all 3 answers and change the hints around depending on the answers found.

**Comment by ACoolCat** [comment]
Oh, well, if you want I could possibly give some more riddles. I have three or four in the back of my mind I thought would be good.

**Comment by MrBallad** [comment]
That sounds like a neat idea.

**Comment by ThePotatoGuy** [comment]
We'll look into this at a later time.
