### ISSUE TITLE
[Suggestion]- Scrabble 

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#1119]
First off, I want to thank the developers of this mod. It has in all seriousness helped me get through a few insecurities of mine, and if that sounds funny then oh well. I was just thinking how scrabble would be suited in this game. Since Monika is in the Literature club, she would play really well, perhaps due to her knowledge of literature and words in general. Just a thought though, but keep up the great work, I love ya all.

**Comment by kaido1224** [comment]
Looks like this was already suggested on #55

**Comment by Pbm13** [comment]
Ah, sorry about that, wasn't aware of the suggestion, I'll try to see next time if it's been made if I make another suggestion.

**Comment by kaido1224** [comment]
No worries. I had to search to see if it was suggested. I think it'd fit her perfectly... she may be too good at it like chess. Lol

**Comment by Pbm13** [comment]
yeah, took me lots of saving and tries but I'm finally 1 win, 20 losses hahaha.

**Comment by jmwall24** [comment]
Just what I need more games for her to destroy me at lol  In all seriousness Scrabble would be perfect.

**Comment by Pbm13** [comment]
I know right?! Adding on to the fact she's smart in the literature department, she may know how to make words we can't think of.

**Comment by ThePotatoGuy** [comment]
From a technical standpoint, scrabble would be incredibly difficult to implement from scratch. If there's a python library out there for scrabble (probably is, but too lazy to search rn), then we could look into this. 

There's also a matter of whether or not this makes sense to add. Scrabble is pretty niche.

**Comment by Pbm13** [comment]
understandable, implementing a game of infinite possibilities but its still a nice thought though.

**Comment by TinyInternetTree** [comment]
Oh good, another game for her to 100% beat me at. Jk, this would be really cool. She'd probably be too good at it though. Like Chess (or so I've been told).

**Comment by kaido1224** [comment]
I'd put this on the back burner.

**Comment by ThePotatoGuy** [comment]
[Unlikely to happen, closing if we decided to do this]

**Comment by CrocWorks** [comment]
What about talking to the guy who made this? https://github.com/Innoviox/Pyrotor

It was made two years ago, though. And it says it needs python 3.4.2 as well... I don't know if that means it's Python 3 or not, but if I recall MAS uses Python 2 and (thanks to Monika's lovely tutorials) I don't think they'd be compatible? Perhaps a better coder might have better insight?

This one is also a Python 3 Scrabble game. https://github.com/ShalaQweghen/py_scrabble_gui
