### ISSUE TITLE
Fix of Monika's Fingers

### ISSUE THREAD

**Issue by Erianict** [Monika-After-Story/MonikaModDev#1121]
_Hello friends!_ Probably some of you noticed Monica's "Broken" fingers?
![36551526-ba57f168-1832-11e8-8978-2c4e70893019](https://user-images.githubusercontent.com/36629456/36553329-a03d2252-182e-11e8-8de4-6b402b442db5.png)

I decided to save you from them! Now it's look more realistic, I just edited some files:
![screen1](https://user-images.githubusercontent.com/36629456/36553389-c3ddae3e-182e-11e8-8d9a-c0f000315533.png)
![screen2](https://user-images.githubusercontent.com/36629456/36553390-c4236528-182e-11e8-9dcd-f356587eca81.png)
![screen3](https://user-images.githubusercontent.com/36629456/36553391-c45f5c0e-182e-11e8-8b68-afde0f0712fd.png)
![screen4](https://user-images.githubusercontent.com/36629456/36553392-c4a53d32-182e-11e8-95ae-d541f2571fad.png)

Link on fix: [Google Drive](https://drive.google.com/open?id=1opVtga91w59VdERXwRPX8K0Kkng3Ro2a)
![screenshot0005](https://user-images.githubusercontent.com/36629456/36553608-5d955978-182f-11e8-9383-29ffab2a7b8e.png)

**Comment by monikLover** [comment]
These edits look mighty fine, fella. Thank you!

**Comment by ThePotatoGuy** [comment]
Covers #1120

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Thank gosh, somebody fixed it.
Those unnaturaly angled fingers have bugged me since the addition of poses.

**Comment by oniigirii** [comment]
Neatly done. Good job!
