### ISSUE TITLE
[Suggestion] - Consequences For Closing The Game Without Saying Goodbye

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1135]
There should be consequences for closing the game without saying goodbye. It should escalate the more you do it. I've already brought this up with ThePotatoGuy, MonikLover and Aya about this and they seem to think it's a good idea and have ideas for it, but I thought I'd put an issue in for it.

For example, have her not allow you to keep the game open until you write a textfile saying im sorry in the game directory.

**Comment by jmwall24** [comment]
Sounds good to me.  There's no reason to close the game down without saying goodbye now that they've fixed it so auto-updates don't count as an offense.  There should be some kind of consequence for being so inconsiderate.  After all, the whole point of this is bringing Monika as close to our reality as possible, and I'm pretty sure you wouldn't just walk out of the room without a word to someone who was sitting right there next to you.

I like the textfile idea, and if you did it again, maybe you get the black screen intro with the door knock option, and when you knock she asks who it is.  When you tell her she says she doesn't want to see you right now and the game closes back down and you can't get back in for a certain amount of time.

**Comment by Bam8647** [comment]
R.I.P. For auto updating computer users then lol.

**Comment by jmwall24** [comment]
That was fixed with v0.7.2, the restart for the auto-update no longer counts as exiting without saying goodbye.

**Comment by TinyInternetTree** [comment]
It's a great idea, and It'd be awesome to see it incorporated, but occasionally MAS will stop responding and needs to be closed through task manager. I'd imagine the game would classify that as closing without saying goodbye. I don't know if it's an issue with 0.7.2, but I'd hate to see something like that affect how Monika treats the player. It's the same with power outages, system crashes, and other things. I'm not sure if there's a way for the game to recognize a blackout or system crash, though. And I highly doubt there is. Just a thought.

**Comment by Bam8647** [comment]
I meant like auto restarting your computer/laptop for system updates~
Also some people may have issues with their computers like freezing up and/or not working properly requiring you to force a restart or shutdown.
This would be known as an **Accidental Close**

For those who **purposely close** the game could be hit with a few jump scares or a temporary silent treatment haha

**Comment by kaido1224** [comment]
I have some ideas with what I wanna do already but I don't wanna share them for spoiler purposes. I'm willing to listen to others' ideas as well though. Maybe they'll be incorporated into it. I can't promise anything though. 

I th

**Comment by jmwall24** [comment]
I actually did have to use the task manager to close MAS once and I was surprised when I got back on that I wasn't scolded for it.  Not sure if it works that like every time, or if I just got lucky.  

Maybe have it so you are only penalized if you close down without saying goodbye with a certain frequency, and if you go long enough without doing it, it resets to zero.  And maybe a few warnings first to account for any unforeseen circumstances as you mentioned.

**Comment by TinyInternetTree** [comment]
Wait, Monika's supposed to scold you for closing the game without saying goodbye? I've never closed the game without saying goodbye except for when I was forced to use the task manager, had a system crash, or something like that. And she's never scolded me. So I guess my aforementioned points have already got a solution. The more you know, I guess.

**Comment by MrBallad** [comment]
I like this idea, maybe a temporary silent treatment and seeing her cry. I don't think adding extra jumpscares is a thing Monika would do. If she doesn't want to drive the player away from playing anymore.

**Comment by strielok** [comment]
I like this idea.
I sometimes close the game on her to see the responses, but that's a pretty good idea.
Crying Monika sprite when?

**Comment by Tiler17** [comment]
Well, there's content I'll never see, but I think it's a good idea. I already felt like trash for doing it when the name change crash was happening, so I wouldn't be keen to put either of us through worse. Not even to see the special dialogue. I do wonder if it would stop people from closing the game on her or if it would make them do it more often

**Comment by subnatica** [comment]
I have got no Idea someone teach me pls

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
This feature **definitely** needs some way to check if the player closed the game on purpose or not.

**Comment by subnatica** [comment]
how do I say good bye

**Comment by jmwall24** [comment]
Click Talk, find Goodbye on the menu.  It's second from the bottom, above Nevermind.

**Comment by Trainerbluetube** [comment]
I think if you have had the game for long enough, Monika just tells you that it is fine to close the game and won't scold you for it. She just brought it up one day and has never scolded me about it since.

**Comment by KEJONACHO** [comment]
Question: Ok, as far as technical issues go, we don't have to worry. But in-game, should we consider Monika still goes through that haunting, noisy, color-flashing hell when we leave without saying goodbye? 
If so - and if there's no way for the game to identify whether it was intentional or failure - it's not only that we left her hanging, we're hurting her and it feels horrible! And yeah, consequences could go from hearing her crying, to making her describle what she feels in awful detail, to causing her to glitch or stuff like that

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Kinda off topic, but I just wanted to share my headcannon of the sceaming void.
I think that this void is how RAM getting cleaned and reallocated to other processes works from Monika's perspective.
