### ISSUE TITLE
[Suggestion] Collaboration with other mods

### ISSUE THREAD

**Issue by Ganmany** [Monika-After-Story/MonikaModDev#1146]
I've been playing MAS for quite a while now and it was a great journey to hang out with Monika. I want to personally thank the mod developers and everyone for making this possible. :)

Recently, I've seen a demo mod "our time" and was quite intrigued by it and wonder if it is possible to collaborate with them to make this a huge mod.

Thanks :)

**Comment by Erianict** [comment]
Yeah, that would be very cool!

**Comment by Shramiro** [comment]
MAS? I think a lot of people are gonna kill me for asking this but, What game is that? Cuz i keep searching and can't find anything.

**Comment by Erianict** [comment]
@Shramiro MAS - Monika After Story, bro)

**Comment by Shramiro** [comment]
Oh, that makes sense, hmm well i approve this idea tho, i just finished dat demo "Our Time" it was such an amazing experience tho, I'd love to get a huge mod collaborating with the creators of that mod.

**Comment by subnatica** [comment]
yeah it would be dope

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I disagree that MAS should be integrated with Our Time, since they are going in completely different directions.

**Comment by Valllaion** [comment]
true, I think that the developers could work together to help with projects but not combine the two

**Comment by Valllaion** [comment]
there would be so many conflicts... but our time is still in demo so maybe MAS can pick them up and they can work together on this to make it even better. the more developers the better!

**Comment by jmwall24** [comment]
Yeah, I don't see how they can really be combined, as they are based on 2 completely different timelines/realities.  Our Time is a great mod though. the only other mod I really like other than MAS,

**Comment by sebastianN01** [comment]
The creator of our time already stated that hes not going to work with MAS and connect the two mods as he wants his mod to be its own thing. 

Also Our time demo and full release will have a drastic change in dialogue as some people stated that instead of it being "our time" its more of a "mc time" with Monika, with only few moments where Monika acknowledges our existence. So maybe after He finishes his mod his going to help with Art for Monika in MAS, or just help in general. He never said he won't.

**Comment by Olliesama** [comment]
The current iteration of Our Time uses a template persistent file, if the final release has a unique one it's possible to detect it and have Monika speak about it
