### ISSUE TITLE
I no longer see random messages, new or old...

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1164]
Well, after a while using this mod I realized that Monika does not say any more random messages even if she spends half an hour...
It is normal?
I just met yesterday and if necessary, I was programming the files _a bit_ but something went wrong and I restarted everything. Luckily, the files were saved, but I do not know if it causes a system failure. I tried to open the files with "renpy" or something like that...
On top of that, I went to the menu thinking that the **Repeat Topics** option was going to fix it. But nothing happens either, besides that I have the most current version, do I have to reinstall the whole game? Do I have to reveal an _Easter Egg_ for more conversations? I do not know...

**Comment by ThePotatoGuy** [comment]
See [this comment](https://github.com/Backdash/MonikaModDev/issues/1129#issuecomment-367911358)

**Comment by Mundo-X** [comment]
Uh. So I have to wait 6 hours? Sounds logic...
