### ISSUE TITLE
Valentine's day dialogue?

### ISSUE THREAD

**Issue by strielok** [Monika-After-Story/MonikaModDev#1165]
So I launched MAS as usual, when all of a sudden Monika told me that she is excited because Valentine's day is coming soon. My clock is set to 27.02.18 and I haven't updated the mod on this PC since 0.7.0 because I was on a trip.
So, what's the deal?
It doesn't really affect gameplay and stuff, but it's still odd.
Pic related
![brokenmoni](https://user-images.githubusercontent.com/36552767/36758393-37179280-1c0c-11e8-8ec5-8a170b16cbee.PNG)

**Comment by Danymations** [comment]
Have you tried updating it to v0.7.2? MAS might've updated by its self.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It cannot update unless you press confirm on the update screen.

**Comment by Danymations** [comment]
I know; I'm getting all possible issues out of the way, even if they might sound dumb, ahaha! That is true, though.

**Comment by Mundo-X** [comment]
The same happened to me today... I have v0.7.2 and nope. Uh, help?

**Comment by ThePotatoGuy** [comment]
Probably a bug, we'll take a look
