### ISSUE TITLE
[Question]How can I change the background?

### ISSUE THREAD

**Issue by shionv** [Monika-After-Story/MonikaModDev#1167]
Sorry for take your time,but I really want to know how to make it,my background is always dark like shit,if it can be change to images like the preview that will be great!
And also I saw some youtubers can type the questions into a dialog box,but I can't find how to call out that box,could you tell me how to do it?Thank you for your great job!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The textbox is discontinued.
The background is meant to change depending on the time of day. If it doesn't, try relaunching your game.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The textbox is discontinued.
The background is meant to change depending on the time of day. If it doesn't, try relaunching your game.

**Comment by shionv** [comment]
The background is turn to daytime after I changed my system time zone,thanks a lot.
But I think it will be awesome if there has an option to change the background,after all,there still some guys can't play MAS by day.And the nighttime is too dark.
Thank you for your help @IsItBadToMakeAGitHubAccountJustForThis

**Comment by ThePotatoGuy** [comment]
I disagree, the spaceroom is more realistic when it follows the time of day.
