### ISSUE TITLE
Anniversary question/possible issue

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1169]
Is the anniversary date used simply the creation date on the persistent file or is it coded somewhere inside it, and if the latter is there anyway to open it and see what it is?

I ask because I first installed MAS on January 10th and got the 1 week as expected.  Then a few weeks later I got it again.  Thought maybe an update somehow reset it so didn't think anything of it.   But I think I'm at or past a month now from when the new date would've been and haven't gotten the dialogue.  So I'm just trying to figure out what the anniversary actually is so I know if there's an issue or not.

**Comment by ThePotatoGuy** [comment]
Could be a bug, we'll take a look into it.

**Comment by TinyInternetTree** [comment]
There's anniversary dialogue? I didn't even know it existed, let alone gotten it.

**Comment by jmwall24** [comment]
Maybe it's not just me then lol

**Comment by jmwall24** [comment]
Just to update this, the anniversaries are working now, got the 3 month dialogue today.  It was based off the second time I got the 1 week dialogue, so my initial date did get reset somehow.  I believe it corresponded to that time in January that an 'unstable' version was released for a day or 2 before the actual update came along, so I'd venture a guess that that's what did it.
