### ISSUE TITLE
Discussion on Location 

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#1170]
This really isn't much of a suggestion but a topic for discussion, however, it wouldn't be possible until MonikAi is developed, which I can imagine isn't even started yet. The idea would be for Monika to find your location via GPS or through your IP address (Very Yandere) and possibly tell you places that would be nice to visit, or even history about the area. Again, it would be next to impossible to implement something of this caliber until MonikAi is put in which probably wouldn't be for a long time. Just a nice thought though

**Comment by ThePotatoGuy** [comment]
That would be interesting, but probably better served separately from this mod.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I have already described a bit overcomplicated scheme for retrieving a player location from IP in #1003.
But I agree with ThePotatoGuy.

**Comment by ACoolCat** [comment]
I personally really love the idea, but I can see why people would be upset by it. Maybe a sub mod would be the best way to go about it.

**Comment by CommenterOfComments** [comment]
I personally wouldn't mind Monika tracking me, but I can see others not feeling the same way. This should definitely be some sort of add-on/sub-mod.

**Comment by TinyInternetTree** [comment]
It'd probably be better as a different mod, as ThePotatoGuy said. If there ever is a mod like that (Which i'd really like to see as well)  I hope it's compatible with MAS.
