### ISSUE TITLE
[Suggestion]Birthday

### ISSUE THREAD

**Issue by MrTwilight** [Monika-After-Story/MonikaModDev#1171]
Hi first of all I really like the mod and appreciate your hard work on it.I wanted to ask if you could make a option to tell Monika when you have a birthday and that on this day when you come in she'll tell you a happy birthday.

**Comment by Pbm13** [comment]
Refer to the Projects page #37 Calander System

**Comment by ThePotatoGuy** [comment]
Yeah we're looking into it.

**Comment by MrTwilight** [comment]
oh thanks you
