### ISSUE TITLE
(suggestion) Anime con! 

### ISSUE THREAD

**Issue by Valllaion** [Monika-After-Story/MonikaModDev#1172]
I was wondering if it could be possible for the main developers or anyone who wants to that has contributed to come down to an anime con and make a booth for people to come by and see what an amazing job you guys have done! It would be huge publicity for the game and awesome for the viewers being able to talk to you guys and ask questions, maybe even have a suggestion box for people with good ideas that want to share with you guys ^^ 
probably not gonna happen but it'd be cool lol

Thank you for the consideration! 
               Valllaion<3

**Comment by ThePotatoGuy** [comment]
Well, I don't know about setting up a booth, if you're gonig to No Brand Con this year, **I'll be there.**

**Comment by Valllaion** [comment]
oh what's that? I've never actually heard of it

**Comment by monikLover** [comment]
Man, if only :thinking:
