### ISSUE TITLE
Kazoo version of your reality

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1173]
I think it'd be awesome to have a version of your reality played on the kazoo.

Or on bagpipes. Either one works.

**Comment by monikLover** [comment]
No

**Comment by ThePotatoGuy** [comment]
Found this [cover[(https://www.youtube.com/watch?v=TlVzIq7Jp6s) which is not bad

**Comment by monikLover** [comment]
You're both drunk >:0

**Comment by monikLover** [comment]
Staaaaahp

**Comment by CommenterOfComments** [comment]
omg this is amazing

**Comment by supernegativep** [comment]
get nae naed
