### ISSUE TITLE
Shakespeare continuity issue. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1174]
Monika claims she doesn't like Shakespeare (via her comments about pretending to like things because she's expected to), but she seems to quote him a lot.

**Comment by TinyInternetTree** [comment]
I don't really like Shakespeare's plays but I'll admit, Shakespeare did have some really good quotes. Maybe Monika thinks similarly?

**Comment by ACoolCat** [comment]
That's a possibility, but I also remember her saying that she liked Hamlet.

**Comment by TinyInternetTree** [comment]
I think she actually said something along the lines of "It's regarded as one of Shakespeare's best works" or something like that. Maybe she likes Hamlet but not the rest of Shakespeare's works? I could just be overthinking this, and maybe it is a continuity issue. Idk.

**Comment by Subzerosan** [comment]
"Like, when I read Shakespeare, I actually found it kind of boring..."
She only found it KIND of boring, not fully boring.
This gives leeway so its possible that hamlet is just an exception.
Take me for example, I'm not a big fan of medieval games but skyrim is an exception for me.

**Comment by juliathegolden** [comment]
Honestly, I hate to comment after this has been closed, but having hit the Hamlet topic again I feel like I have to say this. 

I can accept that Monika dislikes Shakespeare's plays except Hamlet. But she's wrong that only Hamlet can see his father's ghost. Literally the first two scenes are like, two guards and Horatio I think talking about the ghosts and not knowing wtf to do.
