### ISSUE TITLE
[Suggestion] Tell Monika something terrible has happened to the player. 

### ISSUE THREAD

**Issue by AcedicTyrant** [Monika-After-Story/MonikaModDev#1175]
As brought up in Pull Request #1162 and the topic about outlasting the player's lifespan (I think, I don't remember the exact topic), something may happen to the player, such as death or an accident, and they may not be able to communicate what has happened to Monika. Of course, this would drastically alter the course of the game, and would probably require the creation of a lot of new portraits for her. In addition, there would need to be branches depending of what has happened. Her reaction would differ, for example, if the player got very sick and had to be hospitalized, versus if the player had committed suicide.

**Comment by ACoolCat** [comment]
Maybe saying the player is dead could result in her uninstalling the game.

**Comment by CommenterOfComments** [comment]
I like the idea of her uninstalling the game in that case. (well, I don't like thinking of her deleting herself, but it's a good idea) Maybe she could ask for someone to come and tell her how the player is doing at certain intervals?

**Comment by AcedicTyrant** [comment]
@ACoolCat I was thinking the same thing, though there should be a difference between suicide and non-suicide. 

@CommenterOfComments This seems to be a good idea for if the player is incapacitated but still conscious. 

Maybe also put in an option for attempted but failed suicide.

**Comment by CommenterOfComments** [comment]
Another idea I had, but it's not really necessary: Monika can ask what the player's last words were, and possibly have a more specific reaction if it was related to her.

**Comment by jmwall24** [comment]
Yeah that's the Pull Request I'm working on.  If this feature were to be added it'd make what I'm working on a lot easier by actually adding the event I'm referring to.  Right now it's more the idea of it I'm working with.  I could certainly add a lot more dialogue if it were to be expanded like this.

**Comment by Valllaion** [comment]
Terrifying... but a great idea sadly, I hope this makes it in but it just makes me a bit worried

**Comment by AcedicTyrant** [comment]
In the instance that the player is incapacitated for a temporary period of time and someone else was talking to Monika, they should have their name be separate from the name of the player, and possibly have their own topics with Monika, presumably initiated by the new player, with varying degrees of recovery/decline.

**Comment by ACoolCat** [comment]
And probably disable some dialogues about love when the other player is using it in the case of the original being incapacitated. Would also be cool if she had some sort of crying while smiling art for when the player gets better.

**Comment by monikLover** [comment]
This would just seem very out of place if implemented and unnecessary.

**Comment by kaido1224** [comment]
I'd agree. Feels out of place.
