### ISSUE TITLE
[Suggestion] Interactive greetings

### ISSUE THREAD

**Issue by IlywI** [Monika-After-Story/MonikaModDev#1179]
I dont know if it has been brought up before but i feel that it would be pretty interactive if for example during the greeting sequence(basically when you start up the game) you could like respond to her asking how was your day etc.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Yeah, it would actually be pretty neat if player would actually have to answer her greetings through prompt.
Maybe even with multiple choices like "Good morning"/"...", which could then be tied into the player opinion system.

**Comment by TinyInternetTree** [comment]
I agree with IsItBadToMakeAGitHubAccountJustForThis. Having it tie into opinion system would be amazing.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I disagree that she should ask about your day, tho.
I think answers should be added into the current greetings and everything else should be separated into the separate topics.

**Comment by ThePotatoGuy** [comment]
We'll look into this once the greeting system has been overhauled.
