### ISSUE TITLE
[Suggestion] Adding topic variation for topics being accessed through menu/shown randomly.

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Monika-After-Story/MonikaModDev#1180]
Right now most of the topics are worded to sound more or less natural whether they are accessed through the talk option or brought up randomly.
As a result most of the prompts sound bland and feel more like you are forcing Monika to talk about something rather than talking to her.
If you were to add some system to change the topics a bit depending on how player got them and reword prompts so it actually sounds like having a conversation it would greatly enhance the immersion and variety.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I imagine something like a variable (ex. ```topic_current_random```), that gets set upon pressing button/getting a topic through random chatter.
It's the simplest way (except probably making a duplicate for each existing topic) and the variable could possibly have other potential uses.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I imagine something like a variable (ex. ```topic_current_random```), that gets set upon pressing button/getting a topic through random chatter.
It's the simplest way (except probably making a duplicate for each existing topic) and the variable could have other potential uses.

**Comment by ThePotatoGuy** [comment]
[we'll reopen this when we look into it]
