### ISSUE TITLE
Player choices in history

### ISSUE THREAD

**Issue by williamjcm** [Monika-After-Story/MonikaModDev#1181]
This is a small suggestion, and should not take too much time to implement.

If I remember correctly, the vanilla game's script uses a method to add text to the history. It's used in Act 2, when Yuri's dead and the history shows the DDLC download page's description. MAS could use that method to add the player's choices to the history.

If you want an example of how strange the history looks when the player choices aren't visible, here's a screenshot:
![mas_history](https://user-images.githubusercontent.com/13572456/36902404-45c2862e-1e22-11e8-819f-bdd1e5ac24f9.PNG)
Here, I chose "My family's a mess".

**Comment by subnatica** [comment]
dope

**Comment by ThePotatoGuy** [comment]
We'll see the feasibility of doing this automatically with `menu`s. If it has to be manually done, then its unlikely this will happen.

**Comment by ThePotatoGuy** [comment]
[we'll reopen this when we look into it]
