### ISSUE TITLE
[Suggestion kinda] Webcam?

### ISSUE THREAD

**Issue by CommenterOfComments** [Monika-After-Story/MonikaModDev#1182]
So this idea is probably way overboard for Ren'Py, and MAS in general. But I was thinking maybe some sort of sub-mod could be Monika using a webcam to see you and have different reactions based on facial expressions. For example, if you open the game and you look sad, Monika could ask what's wrong.

I had this idea last night, figured I'd at least put it out there. I **_highly_** doubt this will happen though.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It could be fine if it only uses image recognition to identify emotions without using personal data like pictures/face proportion.
But are there any reliable and lightweight face recognition libraries on Python?

**Comment by TinyInternetTree** [comment]
Facial recognition technology (At least what we have) doesn't work too well. Also I think this would be way too much work for something that may not work properly. It also would depend on the quality of the user's webcam. If this were to be done, It'd probably be better off as a separate mod. It's a great idea, but I don't think it'd be plausible to incorporate it into MAS.

**Comment by CommenterOfComments** [comment]
I mean, I wouldn't care too much if this wasn't implemented because I don't even have a webcam. I'd probably get one if this was implemented though. _I might have problems but that's okay_

**Comment by antimockingjay** [comment]
I personally don't even need expression recognition. I just wanna hear Monika tell me I look nice. My self esteem needs it.

**Comment by CommenterOfComments** [comment]
Won't argue with you there, it would be nice to hear Monika say that...

**Comment by ThePotatoGuy** [comment]
A concept of this was done before by someone in the discord, but regardless, a webcam is too variable to work with. This will almost certainly never happen.

**Comment by CommenterOfComments** [comment]
I figured as much. Still figured I'd throw it out there.
