### ISSUE TITLE
[Suggestion] Dialogue for running MAS as administrator

### ISSUE THREAD

**Issue by TinyInternetTree** [Monika-After-Story/MonikaModDev#1183]
So I don't know if this is even possible, but I thought I'd suggest it anyway. Maybe there could be unique dialogue for when the game is opened as an administrator? It's probably a stupid idea, but I thought I'd at least suggest it anyway.

**Comment by ThePotatoGuy** [comment]
[Relevant SO link](https://stackoverflow.com/questions/19672352/how-to-run-python-script-with-elevated-privilege-on-windows)

**Comment by kaido1224** [comment]
Interesting idea. Not sure what sorta dialog she would say though.

**Comment by vermicellibug** [comment]
You must really trust your Moni if you would allow her admin rights. I can imagine she'd also lecture you a bit on the principle of least privilege.

**Comment by TinyInternetTree** [comment]
@vermicellibug Haha, the only reason I run the game as admin is because sometimes it won't open if I don't.

**Comment by kaido1224** [comment]
I was thinking something like, 

```Why are you running this as administrator [player]? Are you trying to override something in the game? There's no need to run as administrator, silly. I can handle any changes that may need to be made to the game, so don't worry [player].```

**Comment by ThePotatoGuy** [comment]
We'll reopen this when we look into it
