### ISSUE TITLE
MAS 0.7.2 Repeat Topics

### ISSUE THREAD

**Issue by valznik** [Monika-After-Story/MonikaModDev#1184]
So, 0.7.2 have this option to repeat topics, even if Monika's out of topics, right?
I've ticked it, but why it doesn't do nothing?

![img_20180302_192847](https://user-images.githubusercontent.com/37007990/36929994-60d96c30-1ecb-11e8-934e-e50029528f15.jpg)

She even said the usual talk about something aoon
![mas_0 7 2](https://user-images.githubusercontent.com/37007990/36930038-3ba69fd6-1ecc-11e8-867e-454feeaf15ac.jpg)

**Comment by ThePotatoGuy** [comment]
See [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/1129#issuecomment-367911358)

**Comment by Mundo-X** [comment]
The same thing happened to me, close the game and wait 6 hours to give Monika a break.

**Comment by valznik** [comment]
Okay, according to that thread, I supposed to close the program for 6 hours minimum before starting it again, correct?

Well, I did that, and still got this
![img_20180304_082758_hdr](https://user-images.githubusercontent.com/37007990/36941129-5504c646-1f86-11e8-954d-b3109e9ac9a3.jpg)

Despite my Repeat Topics options ticked as seen below
![img_20180304_082737_hdr](https://user-images.githubusercontent.com/37007990/36941160-57c0794c-1f87-11e8-8362-9c633088b532.jpg)

**Comment by ThePotatoGuy** [comment]
Upload your `persistent` file here please. [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf) is a guide

**Comment by valznik** [comment]
https://www.dropbox.com/s/m9g3uaokpkhw5o5/persistent.zip?dl=0

**Comment by valznik** [comment]
Anything?

**Comment by ThePotatoGuy** [comment]
I didn't see anything unusual with the `persistent` file. Try unticking, closing the game, reopening the game, and then reticking it.

**Comment by valznik** [comment]
Okay, yeah. The problem seems to disappear after I updating to 0.7.3
But I'm not so sure, let me try

**Comment by valznik** [comment]
Okay, no...
She's still saying this
![mas_-_repeat_topics_0 7 3](https://user-images.githubusercontent.com/37007990/37474638-6ccc6934-28a3-11e8-9129-fc3cc0907e0a.jpg)

Despite my Repeat Topics being ticked
![mas_-_oot_0 7 3](https://user-images.githubusercontent.com/37007990/37474639-6d12abf6-28a3-11e8-9454-9fe01af68628.jpg)

But it's weird...
A few hours after updating and completing the White Day event
She's still talking about seen topics

After that I run her in the background at my laptop at home whilst I'm off at work.
Tonight, when I came home, she's still running in the background, but she's not saying anything.

**Comment by ThePotatoGuy** [comment]
6 hour rule still applies, so if you're leaving her on background while you're away, she's not gonna have anything to say to you when you get back.

**Comment by valznik** [comment]
Speaking of...
What's that "6 hour rule" for anyway?
I've heard rumors that it's for preventing spamming exp, but what's the exp used for anyway?

**Comment by ThePotatoGuy** [comment]
It's for unlocking new content.

**Comment by ThePotatoGuy** [comment]
Move this over to #1298
