### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1189]
In the previous publication I put questions or doubts that I had, which were answered. However, I want to help in this project, and not only giving ideas, I want to give dialogs, and if possible, Python commands that are complex. No, I do not know how to use Python, however I have a programming teacher who is teaching me HTML, I will ask him to teach me Python and soon, at least in April, I will start to help.

Meanwhile, as an ordinary person, how can I help in all possible ways?

**Comment by aldoram5** [comment]
Thanks for wanting to contribute :) 

Read the [contributing document](https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md), there you can see how you can contribute, also you may want to join the [discord server] (https://discordapp.com/invite/K2KuJeX) that way you can talk with other community members and ask more easily there.

**Comment by kaido1224** [comment]
Aldoram pretty much covered it. You don't necessarily need to know python to contribute dialog though. Many people contribute that without knowing any python.

**Comment by Mundo-X** [comment]
init 5 python:
    addEvent(Event(persistent.event_database,eventlabel="monika_example",category=['undefined'],prompt="Example Topic.",random=True))

label monika_death:
    m ?? "Here should I put text and then the expression of it on the left?"
    m ?? "Also before placing the characteristics and then placing 'return'"
    return

I would like to save the work by putting many topics to talk about, I do not know if it is done this way and then I send it to the administrators to approve it in future versions...

**Comment by ThePotatoGuy** [comment]
Yes, but make sure to have proper indentation.

**Comment by Mundo-X** [comment]
Okay. I will do my best :/
