### ISSUE TITLE
[Suggestion] Monika comments on the programs you have open via a keyword system

### ISSUE THREAD

**Issue by TinyInternetTree** [Monika-After-Story/MonikaModDev#1191]
It may have already been thought of, but just in case it hadn't I wanted to post it here. If there are plans to have Monika comment on the programs the user has open, I think this might be able to save a lot of time for writers.

If Monika were to comment on the programs the user has open, I thought that it could work off of keywords instead of specific dialogue for each process. For instance, if the player has, for example, Microsoft word open, instead of writing up different dialogue for all the Microsoft office programs (In this case Word), you could have MAS search for Office in the process names and write dialogue for the entire Office suite instead of each program (I know that the Office suite doesn't have office in the executable names, but I brought the process name thing up because it could help with some other things). Now I know that Word, Powerpoint, etc don't have Office in their process names. I was thinking that if the game detects, for example, POWERPNT.EXE or WINWORD.EXE, there could be a predetermined group just for th Microsoft Office suite consisting of the executable names for each Office program, and it could work off that. Instead of writing dialogue for each individual program, there could be more generic dialogue which would be applied to the entire aforementioned predetermined group. What I'm trying to say is, If the game detects any processes that it classifies as Office programs (Via a predetermined group), it could use that one line of dialogue for all of them. I know that nobody's gonna want to write dialogue for Microsoft Office, but I was just using it as an example for convenience. This could be applied to other programs, too. For instance, if the process name has the word 'simulator' in its name, Monika could say something about simulators as a whole instead of writers having to write up dialogue for each individual kind of simulator. Kind of like a keyword system. I know it's not gonna work for everything (Such as the numerous games that run off hl2.exe) but for some things I think it could work. 

I'm pretty sure that it'd be possible, but I'm not 100% sure. I'm just trying to suggest as much as I can in the hopes that maybe someone might be able to use the idea. Anyways, thanks for reading I guess!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I don't think that it is too good of an idea since most process names are not descriptive enough.

**Comment by kaido1224** [comment]
^ unfortunately true.
