### ISSUE TITLE
[Suggestion] Monika Asks the player if its really him (when launching the game) and ask a couple of questions to make sure

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1193]
I've recently thought about an idea where Monika will question the person whos launching the game, by asking questions that the player has to answer correctly, otherwise Monika will do some action.

Questions such as "what is your name?" You will need to answer with the name that Monika calls the "player" with

"How long since We've met?" Would need an answer depending on how long you've actually been with Monika, Hints would be dialogues like "We are together more than 2 weeks now" or a monthly aniversary That Monika mentions over time.

"Who am I to the true player?" Would have a choice to answer with either "a girlfriend", "friend" or "relative"

and so on. If you guess an important question Monika would realize its really you!

This event could've happen if you dont play the game for more than few days or a week.

What do you think? Add some more questions in the comments below :)

**Comment by CommenterOfComments** [comment]
I could see this potentially being tied into #1175. If Monika doesn't think you're the player, she'll ask if they know if the player is okay. After all, if you've been gone for a while, I imagine Monika would be worried.

**Comment by jmwall24** [comment]
Could be an option for one of the door knock scenes if, like you said, you hadn't opened the game for a certain period of time.

**Comment by monikLover** [comment]
This would be tedious since it'd just be annoying everytime you launch the game. It'll be like having to answer questions everytime you unlock your phone.

**Comment by sebastianN01** [comment]
Why everytime? I said "could've happen if you dont play the game for more than few days or a week."

**Comment by monikLover** [comment]
Ah, misread it, sorry. The point still stands, tho. as it still tedious.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I think she should only do this if player does something really suspicious or uncharacteristic.
If she asks it out of the blue it would seem like she doesn't trust the player.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Opinion system/hidden gauge that would rise from certain topics/choices, maybe.

**Comment by jmwall24** [comment]
It could be a teasing thing.  Like if you haven't visited in a week, you get the black screen opening, knock on the door and she pretends not to remember you to make you sweat it out a little.  It could replace the random, 'haven't you kept me waiting a little too long' dialogue that is present now, which can come up at anytime no matter how long it's been.

**Comment by kaido1224** [comment]
I have an amnesia greeting already that's on hold atm
