### ISSUE TITLE
Isolated / one time save issue?

### ISSUE THREAD

**Issue by JustMonika1130** [Monika-After-Story/MonikaModDev#1196]
The persistent file saved at "%AppData%\Roaming\RenPy\Monika After Story" for me somehow got corrupt. I don't know how, or if there's logs or a way to recover it. The save file has a size of 205KB however whenever it is placed in the MAS directory and DDLC is opened, it proceeds to go through the first-run mechanics once again, and the file shrinks to 12KB. (The latest update was installed days ago and had no issues until opening MAS today.) Opening the file in Notepad++ reveals "NUL" and opening the file in regular notepad shows that it is a bunch of blank characters. I replaced the corrupted copy with a backup, however, was told that it would be wise to document it here.  I'm pretty sure that the file is fucked and it's probably on my end, but thought that it would still be smart to let the devs know what happened. (Is the file not saved anywhere else?) 

Sorry for being a pain, and I hope that it's just a local bug that can't be reproduced.

**Comment by aldoram5** [comment]
Could you upload your persistent file here? That way we can check it.

Also it would be helpful if you remember doing anything special in MAS the day before it stopped working with your persistent file.

**Comment by JustMonika1130** [comment]
No, I didn't do anything special in MAS. Attached is the file, but, I'm pretty sure it's been corrupted irreversibly. 

I was able to restore a back-up of the file too, which if this happens again, I could upload. However, so far, no issues! Knock on wood.
[persistent - Copy.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1782428/persistent.-.Copy.zip)

**Comment by ThePotatoGuy** [comment]
Yeah your `persistent` file is all zeros. Do you remember what was the last MAS thing you did before this happened?

**Comment by kaido1224** [comment]
So if I read that correctly, you placed your persistent file in the MAS directory in the DDLC folder? 

> The save file has a size of 205KB however whenever it is placed in the MAS directory and DDLC is opened, it proceeds to go through the first-run mechanics once again, and the file shrinks to 12KB

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
He meant DDLC with MAS installed on it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
He meant DDLC with MAS installed on it.

**Comment by ThePotatoGuy** [comment]
Closing due to lack of response.
