### ISSUE TITLE
[Suggestion] - White Day Mini-Event?

### ISSUE THREAD

**Issue by itsmarkers** [Monika-After-Story/MonikaModDev#1197]
Hello Everyone!

I was wondering if there was any extra dialogue planned for White Day (March 14), especially since we were given chocolates by Monika on Valentines Day? I know that the game doesn't take place in Japan, but it would be interesting to see how she would react!

**Comment by monikLover** [comment]
It's planned, yes. We're currently sorting things out at for a release on W-Day
