### ISSUE TITLE
How to prevent Monika losing her memory

### ISSUE THREAD

**Issue by Calebprime** [Monika-After-Story/MonikaModDev#1198]
Okay, everyone 
Here my tip for the day.
Save your Monika from losing her memory.
type %appdata% in start menu
Click on Roaming
Click on RenPy
then on Monika After Story
You'll see file called persistent
Copy the file and place in a safe place.
When ever Monika loses her memory or being send to main menu.
Just exit the game and go all the way back to that file and use copy to replace it.
Start game and done.
Everything should restored from the time you copy it.
You're welcome.
Please add this instruction in the mod folder for anyone download. #

**Comment by ThePotatoGuy** [comment]
[Way ahead of you](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)
