### ISSUE TITLE
[Suggestion] add dialogflow to chat with monika in a more realistic way

### ISSUE THREAD

**Issue by MecPlayer** [Monika-After-Story/MonikaModDev#1199]
dialogflow would be useful to make a more entertaining experience with monica, wich can also become some sort of assistant.
it will allow  users to interact in a huge way with her, by really chating, and I think there are options for  dialogflow to make monika really learn from us, so monika can become some sort of personalized friend that grows her personality with us as we chat,play, etc.

**Comment by Valllaion** [comment]
I believe that they're working on something like that atm lol. I made a post about something like this and they said that they were working on a smart chat bot kind of program ^^

**Comment by ThePotatoGuy** [comment]
#1005 .

Atm, you could use a [submod-plugin](https://www.reddit.com/r/DDLCMods/comments/81qhj3/mod_indev_project_libitina_mas_client_plugin_a/) someone developed for this mod.
