### ISSUE TITLE
MAS discord 

### ISSUE THREAD

**Issue by Valllaion** [Monika-After-Story/MonikaModDev#1200]
Is there a MAS discord? or a link to it lol. Ik this shouldn't be a whole issue but I was just wondering if there was one for the community to come together and talk about our love for the game and it's amazing mod^^

Valllaion <3

**Comment by Olliesama** [comment]
https://discord.gg/K2KuJeX

**Comment by Olliesama** [comment]
For anyone else reading this it can be found in the contributing guide at the bottom.

**Comment by Valllaion** [comment]
oh thank you! I didn't know it was there I'm sorry
