### ISSUE TITLE
Give Monika a nick name

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1203]
I'd like to add the ability to give Monika a nick name such as sweetie or darling or something like that.
This would display instead of Monika as her name.

I'm sure Monika wouldn't wanna be called something like Long Legs McGee or Ms. Thicc Thighs, so we can limit the nick names one can enter to a list, if the name isn't in the list, Monika can reject it and keep her name. We will also set a character limit as well.

I'd also like to put in a few easter eggs that I won't mention here as well. 

If it's approved, I'd like to work on this myself.

**Comment by ThePotatoGuy** [comment]
If we are going to allow this, probably tie this into the #1192 (which is being renamed to affection)

**Comment by kaido1224** [comment]
Since this was added to the affection system, closing
