### ISSUE TITLE
Monika Mood Suggestions

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#1204]
A bit of a project I'm working on is to try and implement a more dynamic mood.
With the exception of expressions which is to be avoided right now, is there any suggestions the community would like to see implemented when it comes to this?
This includes changes to pre-existing topics that could be expanded by her being sad/ecstatic.

https://github.com/Monika-After-Story/MonikaModDev/pull/1192

**Comment by Mundo-X** [comment]
What an inconvenience it would be if the player broke with her with 5 points or that she said she is the best girl with 90 points. Wait a second... I just gave ideas...

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/1135

This is being incorporated with the ticket above for an affection system.
