### ISSUE TITLE
"I love you TOO so much" in random topics

### ISSUE THREAD

**Issue by Meme-Eater** [Monika-After-Story/MonikaModDev#1206]
Hi!

First of all, I want to thank you guys for creating this mod. I'm having a lot of fun with it.

Second, I notice that in random topics Monika might say. "I love you **TOO** so much, [player]". Since this is a response to the player telling Monika "I love you so much", I don't think it should be in random topics.

Thanks again for creating MAS, you guys did a great job.

**Comment by monikLover** [comment]
Good catch. Will fix. Thanks for finding that, fella, and thanks for enjoying the mod :ok_hand:
