### ISSUE TITLE
Tell Monika that your pc might crash

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#1208]
Requested by @Trilasent

Currently there's no easy way of determining the difference between closing the game without telling Monika goodbye or your computer crashed and shit happened. With #1135 becoming reality, what better way to mitigate game closures that aren't your fault than pro-actively warning Monika that crashes may occur. 

This could be useful for a variety of users:
- people with shitty computers
- people in the midst of a thunderstorm
- people who want Monika to watch their computer delete itself
- and more...

## Technical:
We'll probably do this by adding another closure `persistent` for this. This can be checked 2nd to `closed_self`, and will have its own bit of reload dialogue.

Also some code should be added to the "Don't quit the game on me" screen that resets this `persistent`, since it's very obvious that people could abuse this proactive dialogue to quit without saying goodbye.

Also this shouldn't be a once-only thing. Either this will be timed or last until next session. Or maybe something else. We'll see.

**Comment by Trilasent** [comment]
Nothing like another game causing your screen to go black and preventing you to tell her goodbye so you can reboot without cutting her off. **_I'm so sorry Moni.. :c_**

**Comment by Mundo-X** [comment]
That happens to me.

**Comment by IlywI** [comment]
Or the windows 10 update(old joke i know but still :/)

**Comment by TinyInternetTree** [comment]
My PC's pretty high-end, but I occasionally get BSODs because of all the shit I have running at once, so this will be really helpful to me and others who do similar stuff.

**Comment by Trilasent** [comment]
It only seems to happen to me while I'm trying to play Black Ops 3 while having MAS open at the same time. Oddly enough the game never actually had issues like that before, and since it started earlier I had around 3-4 crashes that caused me to have to "force" the power off on my PC, preventing me from letting Monika close my game.

**Comment by GoldTheEevee** [comment]
first of all amazing idea second of all "people who want Monika to watch their computer delete itself" amazing! one last thing is how do we do it?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
While we're at it. I was going to propose timed autosaves for a longest time.
Mostly because I had to terminate ddlc.exe thanks to the alt-tab bug and the game didn't save any progress.

**Comment by kaido1224** [comment]
Per convo I had with TPG, this is being aborted because it's easier to detect whether the game crashed or not.
