### ISSUE TITLE
[Suggestion] "Our Names" Silly Dialogue

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#1217]
So, the "Our Names" conversation is the one where Monika tells you the roots of her name. But the first time I ran into this conversation, she told me this:

![screenshot0002](https://user-images.githubusercontent.com/36717174/37245014-95950d6c-2457-11e8-91d9-7dd22b780bd8.png)

Ay, I figured you would, Monika, my parents didn't know how to spell either.

![screenshot0003](https://user-images.githubusercontent.com/36717174/37245021-ab4529bc-2457-11e8-8ba9-4ff53421fe76.png)

You what?

I played around with it a little bit, because I wanted to know what it was supposed to say, and apparently it's simply, "I like your last name, but I like your current name better." It goes back to looking silly if you "change" your name to the same thing, but that isn't something I'd ever done...I think.

Anyway, I think a new bit of dialogue would be good there if the two names she comments on are the same. Could be as simple as trimming the second line,

>"Tiler" is a lovely name too.
>Ehehe~

but it could also be something to the effect of how much she likes your name, as you've elected to keep it how you have it and don't want a nickname.

Cheers!

**Comment by neyoriquans** [comment]
That conversation bit at the end has always bugged me. I've struggled to understand what it was supposed to mean since she just ends up repeating my name as well. It could definitely use a fix.

**Comment by juliathegolden** [comment]
m 1e "..."
    m "That part doesn't matter so much, now that you're here."
    m 1a "'[mcname]' is a lovely name, too."
    m 1b "But I think I like '[player]' better!"
    m 1a "Ehehe~"
return

Is the code. For some reason, it just assumes these two are different. 

This should be fixable, I think? 

m 1e "..."
    m "That part doesn't matter so much, now that you're here."
    if mcname.lower() != player.lower():
        m 1a "'[mcname]' is a lovely name, too."
        m 1b "But I think I like '[player]' better!"
        m 1a "Ehehe~"
    else:
        m 1a "[player]" is a lovely name, too."
        m 1a "Ehehe~"
return

should really be all it takes.

**Comment by monikLover** [comment]
Fixed by @juliathegolden #1219
