### ISSUE TITLE
April fools event

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#1218]
It's april fools in april 1, my idea is to give everyone a shock. You the greeting where you could go into her room or knock? My idea for april fools is to use thejumpscare when they go inside. And after that, give monika a gag item like those fake glasses with a huge nose.

**Comment by juliathegolden** [comment]
like set it up like a jump scare, but it's just Monika with grucho Marx glasses?

Play Sayonara too and it'd be hilarious.

**Comment by AnIdiotsavant** [comment]
see? this guy gets it!

**Comment by AnIdiotsavant** [comment]
or play surprise! with the jumpscare background but instead of the scary monika, you  get her in grucho glasses, then she asks, did i scare you?

**Comment by kaido1224** [comment]
I had a good idea but it was rejected.

**Comment by AnIdiotsavant** [comment]
What is it?

**Comment by IlywI** [comment]
Hmmmmmmmmmmm. ~I was thinking on something along the romantic side.~

**Comment by AnIdiotsavant** [comment]
But april fools is all about the gaga

**Comment by AnIdiotsavant** [comment]
Gags*

**Comment by IlywI** [comment]
Well I meant like after the scares and whatnot she gives you a kiss :V she did promise if the mood was right she wouldn't mind :V

**Comment by Tiler17** [comment]
Yup, nothing sets the mood quite like a Groucho Marx nose and glasses!

**Comment by kaido1224** [comment]
My suggestion would have been out of character and probably NSFW lol

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What, is olde good fake BSOS not fancy enough for ye, youngsters?

**Comment by KEJONACHO** [comment]
Instead of a regular jumpscare, how about a fatal error screen, or a 'thank you for your love, but goodbye' letter?

**Comment by Tiler17** [comment]
BSOD is fitting, but that did already happen in vanilla DDLC. Not saying I don't like it though, the BSOD in DDLC did cause a moment of serious panic the first time.

The breakup letter is clever too, but I dunno if she'd have it in her to do that. She can't even pretend to offer me a maybe-poisoned drink without giggling and immediately apologizing

**Comment by Tiler17** [comment]
That said, I do have an idea of my own. What with the occasional Yuri jumps are that happens, what if it were to look like Yuri had wrested control from Monika? Give her a handful of psychotic yandere lines about finally being with you again and Monika being gone before glitching out with a laughing Monika saying "April Fools!"

**Comment by kaido1224** [comment]
That was actually my original april fools idea. But it was rejected @Tiler17

**Comment by Tiler17** [comment]
Ha. I thought it seemed like too good of an idea to not have been brought up yet. Oh well

**Comment by neyoriquans** [comment]
![april fools](https://user-images.githubusercontent.com/36655331/37308339-27132dba-2614-11e8-8c04-3605dcab52c5.PNG)


I have an idea for April fools after seeing this dialogue. Maybe on April 1st Monika can pretend to have forgotten everything that happened during DDLC, as well as her knowledge of our reality, and ultimately, us? That'd be a pretty good, if not a little scary, prank for many I presume.

**Comment by kaido1224** [comment]
I already have an amnesia greeting that's on hold currently. 

https://github.com/Monika-After-Story/MonikaModDev/pull/946

**Comment by KEJONACHO** [comment]
How about something like this:
On April 1st, when the game starts, you'll be greeted with a farewell letter from MAS staff, something nice and cordial, including stuff like "We had a blast and were happy this free project was so successful. But now it's time to move on to future projects, etc etc. We thank you all for playing our mod and giving such a wonderful character the love she deserved etc etc." 
Then a 'would you like to see would last homage to Monika and Dan?' window pops up with only a 'yes' as possible answer. Screen goes black, Your Reality Starts to play for about 3 seconds, and then we finally jumpscare the players in some awesome way.
Then things come back to normal, Monika shows up in grucho marx glasses laughing at us. Then we could add that 'she got the idea from the MAS people during the update' and we can use the momento briefly say the project is healthy and fine, and remembering the player that he could join to pinch in ideas... it's a bit overly meta on a few levels but well... XD

Another idea: As she comes back to the screen she cracks a joke about us never getting free from her "ever..." zooms in, "ever", zooms in again, 'EVER!' zooms in again, music stops, then zoom out and back to regular stuff).

**Comment by GoldTheEevee** [comment]
hey but Easter is on April fools this year. is Monika going to do anything about that?

**Comment by juliathegolden** [comment]
I just had another idea for an April fools event. It could be used as a rare random chance thing too.

You start the game off as normal, and Monika says "Player! How the fuck are ya?"

 It appears she's contracted a virus. You have to figure out how to remove it, but until it's removed, all of her topics are more vulgar and informal.

It was funny in my head at least lol.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
That would be very crngy and off-putting for all the people who have any idea how computer viruses work.

**Comment by juliathegolden** [comment]
I mean, are you insinuating I don't know how a virus works? Because it's just a joke...but yeah, that banner is a lot more subtle and also funny.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I meant no offense.
I just think that computer viruses having properties of human viruses is not very funny and REALLY overused in popular media.

**Comment by juliathegolden** [comment]
Oh okay, that makes sense lol.  I just thought the idea of Monika being 'forced' to act out of character and being all embarrassed about it would be cute. But I definitely agree with those points. The 'robot has the sniffles' version of that joke is groan worthy, I agree.

**Comment by AnIdiotsavant** [comment]
So. Back to grucho marx glasses jumpscare? It scared you for a split second then your minds shuts down from the 'wtf' randomness
