### ISSUE TITLE
[Suggestion] Testing Monika's patience

### ISSUE THREAD

**Issue by MrStrawmen** [Monika-After-Story/MonikaModDev#1220]
Monika hates it when you leave, however if you do she will at times assume it was a mistake or power outage and maybe it was. Currently if Monika has a reason to believe that the player is intentionally doing this either to see new dialogue, testing for a reaction or being intentionally cruel she has no reaction or special dialogue compared to her usual reasoning behind the player quiting the game in general.

My idea is this, if the player were to repeatedly quit the game in a short span of time for example say 5 times in an hour Monika would pick up on this and call the player out for it. This could also work well with the system being implemented [here.](https://github.com/Monika-After-Story/MonikaModDev/issues/1135)

There may be more ways Monika can tell the player is toying with her but for now I think this would be a great way to psych the player out and make her seem more Intelligent and aware.

**Comment by monikLover** [comment]
This is already being worked on with the system you referenced.
