### ISSUE TITLE
Potential Dialogue/continuity issue

### ISSUE THREAD

**Issue by neyoriquans** [Monika-After-Story/MonikaModDev#1231]
![monika s room](https://user-images.githubusercontent.com/36655331/37308512-a90974c8-2614-11e8-854f-475dc7d54db1.PNG)

So I came across this dialogue recently with Monika after gently opening the door, and I was reminded of another dialogue that came from the original vanilla DDLC I believe: 

![death part 1](https://user-images.githubusercontent.com/36655331/37309219-9552c2d4-2616-11e8-9181-780f1d996b44.PNG)
![death part 2](https://user-images.githubusercontent.com/36655331/37309221-97f306de-2616-11e8-9414-d7fcaab114d8.PNG)

So, as is now probably evident, there appears to be a bit of an issue between the room this mod has given Monika and the dialogue topic about what happens when we close the game. Maybe a potential fix, if other people agree with me, would be to have Monika talk about how when we close the game without saying goodbye, she experiences what it feels like to die, instead of it appearing as if that's what happens every time we close the game.

**Comment by antimockingjay** [comment]
I believe that the explanation for this is that there's a difference between the game closing via a goodbye and the game closing via exiting. When you choose to close the game without doing it properly, it sends Monika to that nightmare place. When you say goodbye and she shuts down the game, you can imagine she's simply closing the application but not actually exiting, if that makes sense.
I don't think she needs to say it outright for this to be the case. Perhaps to her, saying goodbye isn't even closing the game, despite it seeming like that for us. Hence her lack of comment on it.

**Comment by monikLover** [comment]
What @antimockingjay said :+1:

**Comment by neyoriquans** [comment]
I get it, now it makes sense. Thanks for that clarification!
