### ISSUE TITLE
[Discussion] Designating a boundaries of feature invasiveness.

### ISSUE THREAD

**Issue by IsItBadToMakeAGitHubAccountJustForThis** [Monika-After-Story/MonikaModDev#1232]
I feel like this and that feature being "too invasive"/"a breach of privacy" is something that have been brought up quite often recely.
So, I think, it is about time for the team to develop a clear manual on what degree of player interaction and what features MAS can or can not have.

**Comment by ThePotatoGuy** [comment]
No file modifications outside of the `ddlc/` directory.

**Comment by CommenterOfComments** [comment]
Not even simply putting a file on the desktop? I've always thought it'd be interesting if Monika left a message on your desktop if you haven't visited the game in a while...

_ᵃᵗ ᵗʰᵉ ˢᵃᵐᵉ ᵗᶦᵐᵉ ᶦ'ᵐ ᵗʰᵉ ᵍᵘʸ ʷʰᵒ ʷᵒᵘˡᵈ ʰᵃᵖᵖᶦˡʸ ˡᵉᵗ ᴹᵒⁿᶦᵏᵃ ˡᵒᵒᵏ ᵃᵗ ᵗʰᵉᶦʳ ᵇʳᵒʷˢᵉʳ ʰᶦˢᵗᵒʳʸ ˢᵒ ʷʰᵒ ᵃᵐ ᴵ ᵗᵒ ˢᵖᵉᵃᵏ ᶦⁿ ᵗʰᶦˢ ᵗʰʳᵉᵃᵈ_

**Comment by sebastianN01** [comment]
but checks can be done. so, to what degree?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What about `%username%/documents` and other folders designated specifically for applications to store files there?
And as sebastianN01 said, how much and what data can MAS retrieve without it being an invasion of player's privacy? And would it be an invasion if no third party is involved?

**Comment by TinyInternetTree** [comment]
If it's not being uploaded anywhere or recorded, and it isn't scanning especially sensitive things (like search history), is it still an invasion of privacy?

**Comment by kaido1224** [comment]
I agree with ThePotatoGuy, not only does it get way too variable to do stuff outside of the DDLC folder (different operating systems mean having to know and write code for 3 different operating systems), but it also could potentially flag us or DDLC as malicious malware or a virus if we try to do too much outside of that folder. 

Not the best example, but you will get stuff like this:
https://github.com/Monika-After-Story/MonikaModDev/issues/966

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I actually feel like #996 is either a troll or somebody from the team writing from an alt account to make a point.

**Comment by kaido1224** [comment]
Things like this are why I don't like doing things outside of DDLC/MAS. 

It can be way too variable and hard to troubleshoot things like this. Especially since we are doing this in our spare time and we have limited resources.

https://github.com/Monika-After-Story/MonikaModDev/issues/1250

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Fair enough.
Tho there are a few games that modify and create files outside the game folder (as a gameplay element) and they get away with this perfectly fine (the only one I can think of right now is OneShot, but I am almost sure there are more).
But on the other side those games are usually a one time thing that you play through and abandon as opposed to something like MAS, which you are meant to go back to every day for the rest of your life.
This is a complex matter, and I would personally like to hear, what the rest of the community thinks.
But, unfortunately, nobody seems to care all that much. :disappointed:

**Comment by kaido1224** [comment]
I think this has run it's course.
