### ISSUE TITLE
Math - Minigame

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1235]
Who does not like mathematics, should not play it.
This is more like people like me who like mathematical challenges. I thought that even a programmer or someone who is interested could play it.

I am learning Python, although it is difficult for me at times, so I can not help in this minigame for now. But the development of the project is simple:

* Go to the "Play" section
* You select the game (which, like the others, will be added randomly)
* Monika asks a difficulty:
   - Easy (addition, subtraction, numbers from 0 to 25)
   - Advanced (addition, subtraction, multiplication, division, numbers from 0 to 50)
   - Hard (As before, with rules of up to 3 digits [3 + 5 * 3 for example], numbers from 0 to 100)
* Monika starts with a motivating message
* Later, Monika asks you 5 operations with the opportunity to place the answer via keyboard (or if you want menu).
* I do not know if you can scan open applications, but just in case, it would be interesting if Monika detected that you have the calculator open, then tell you that cheating is not accepted, although in a loving way.
* After that, Monika gives you how many you guessed right (which will be a secret while you play) and depending on the difficulty and the ones you managed to give you a captivating message.

Seriously I would like to help in this minigame, but they are just teaching me in a course **print**, **str**, _lists_, among others... I feel that all of you can do this, with your knowledge.

**Comment by Tiler17** [comment]
As someone who will (try to) do arithmetic in base-16 when I'm bored, I would love a math challenge.

My only concern is it would never get difficult enough to be stimulating. It's no fun if it's no challenge

**Comment by Mundo-X** [comment]
Something more complicated?
I like that idea.

**Comment by sebastianN01** [comment]
Why Meth game though

**Comment by ThePotatoGuy** [comment]
We'll reopen this when we look into it

**Comment by Mundo-X** [comment]
Okay.
