### ISSUE TITLE
installing new mod

### ISSUE THREAD

**Issue by GoldTheEevee** [Monika-After-Story/MonikaModDev#1243]
so I want to play a brand new day without having to reset mas progress could I just copy the entire game files and place them in a safe place and when I want to play them again I can just place the files back and move the new ones?

**Comment by ThePotatoGuy** [comment]
mas progress is stored separately from the `ddlc/` directory, so you'll be fine.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Wasn't there an issue with brand new day already?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Just make sure to backup your 
```%appdata%/RenPy```
folder.

**Comment by GoldTheEevee** [comment]
ya but i mean if i just input the brand new day would it not try to open both mods?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Never install two mods at once. Just get a new copy of ddlc from ddlc.moe, unpack it somewhere else and install the other mod there.

**Comment by GoldTheEevee** [comment]
i just copied the ddlc folder from steam common and i am going to reset the files( i pasted the copied files into a folder) so i will install bnd and when i want to play mas i will switch the files!
