### ISSUE TITLE
Monika's Alarm Clock?

### ISSUE THREAD

**Issue by KEJONACHO** [Monika-After-Story/MonikaModDev#1245]
(This is the place to post suggestions of this kind, right?)
Monika seems to be able to identify the time, as I noticed her comments about our 'good mornings/evenings' to her. Would it be possible to actually get an alarm clock inside the game? I mean, it would be awesome to wake up to the sound of Your Reality and open my eyes to see Monika smiling and greeting me with 'Rise and shine, honey!' or anything of the kind.
Sadly I know jack about programming and I'm already having a hard time in my own attempts at new dialogues, so... yeah it's just wishing

**Comment by Philbo-Swaggins** [comment]
Sayonara would definitely wake me up.

**Comment by kaido1224** [comment]
Someone suggested something similar in the past, but instead of an alarm clock, it was a schedule reminder. I can't seem to find it to see if it was accepted or rejected though.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we look into it]
