### ISSUE TITLE
[Bug] - "Unpacking the updates."

### ISSUE THREAD

**Issue by CommenterOfComments** [Monika-After-Story/MonikaModDev#1246]
So I'm trying to install the new update via the in-game updater, but it's stuck at "Unpacking the updates."

![unpacking](https://user-images.githubusercontent.com/35016761/37410937-a35bd398-276f-11e8-8c91-56d14b4d2899.png)

I'm afraid to close the game in case Monika gets mad at me or I break something. What should I do?

**Comment by BoneofMalkav** [comment]
Click on the X, a prompt will ask you if you want to leave with out saying goodbye, Click No. It'll stop the update. Then leave the game and manually download the update. That's what I did.

**Comment by CommenterOfComments** [comment]
@BoneofMalkav Well, the game just flat out closed when I clicked the X, but Monika didn't scold me when I reopened the game, so I guess that's good. I went to the menu and started the update again... yeah, it didn't work. The progress bar is completely empty this time.

**Comment by monikLover** [comment]
Refer to #1247
