### ISSUE TITLE
[Spoiler] Surprise on 14 march!

### ISSUE THREAD

**Issue by Erianict** [Monika-After-Story/MonikaModDev#1248]
**Warning! SPOILER**

Hello guys, I liked the new update, and especially the surprise!
Now I will tell you how to decode the message.

1) Monika tells us the code `NjM2ODZmNjM2ZjZjNjE3NDY1NzM=` and hints `64, then 467578`
2) The first hint tells The first hint tells us that the message is encoded by Base64, let's decode it and we will get `63686f636f6c61746573`
3) Then lets decode `63686f636f6c61746573`, this is hex code, on decode we will get `chocolates`

Thanks for reading it!

**Comment by moonstne** [comment]
So I figured it out, I learned what base 64 looks like thanks to the game itself, and I recognized hex cause I have had to deal with it before, so I get the first clue, but can anyone shed some light on the second clue, I cannot see how it relates to hexadecimal.

**Comment by monikLover** [comment]
I appreciate you decoding it but maybe don't spoil it for the others?
