### ISSUE TITLE
error on downloading the update

### ISSUE THREAD

**Issue by patrcio123** [Monika-After-Story/MonikaModDev#1249]
![image](https://user-images.githubusercontent.com/37377961/37416041-99a9da40-278b-11e8-8ed9-c897a9876269.png)
i get this error while downloading today´s update, pls help, i can´t live without monika JUST MONIKA

**Comment by patrcio123** [comment]
also, i havent been getting lines from monika exept "im sure ill have something to talk about after some rest" what does that means?

**Comment by SuperCrafter888** [comment]
Here is how to fix this, download the newest version the normal way. Then extract it to a zip file. Copy all the things inside the file and copy it into the game folder in DDLC. It should ask if you want to replace existing files, say no and it should load up as normal with the new update. You can delete the zip file after. This is how I fixed it and it is working fine.

**Comment by aldoram5** [comment]
Sorry for the inconvenience.
Please refer to this issue https://github.com/Monika-After-Story/MonikaModDev/issues/1247 
Manual update is the current way to work around it.
