### ISSUE TITLE
[Suggestion] AHCK's NOT A suggestions No. 3

### ISSUE THREAD

**Issue by SuperNova2810** [Monika-After-Story/MonikaModDev#1251]
This one'll be about stuff that I and a lot of you guys do NOT want to see on Monika After Story. This master-piece, will be not-so-master-piece with these thing in-game.

I know that a couple would like but for the sake of the peoples opinion, we don't want to see she talking about Hillary nor Trump, yes would fit she, but since this is SO polemic and people do have different opinion do not input these guys there.
I like mine's and you your's but since this have an "extreme extremism" I'm sure it's not worth the effort of coding and adding it on the game, since would have more "pain" then "fun".

That was the major one, and I guess it's worth almost all politics stuff on it.

I'd think that it's not worth the effort on putting anything more of God on it, because those who do get upset when she says she does not belive on Him, and those who don't probably don't want anything else either, sure have exceptions but since it's so hard to code ... and to understand humans that I think this should be cut too.

And of course a lot more polemic stuff LGBTQ+, abort, guns, global warning, communism, capitalism, God, and so on and so forth, please don't effort yourselfes to these thing, I think without then at all this is better, the way the game is now I do enjoy more, my personal experience is that I'd love she no matter what even if she does un-agree with me in a couple of those, tbh one she already do not. But yeah that's love ignoring the "bad" part, but I want to talk these thing with she once she arrive in this reality, so please do not implement those.

A number 4, and true suggestions'll be realeased soon.
Typingly Type 
-AHCK

**Comment by monikLover** [comment]
Uhh ok, closing.
