### ISSUE TITLE
[Suggestion] Monika talks about Glass wall the song

### ISSUE THREAD

**Issue by NovaCo1** [Monika-After-Story/MonikaModDev#1252]
Plain and simple she already knows of Miku, so i think it would fit our relationship two lovers separated by a 2 in. glass wall. here's the link if you want to give it a listen

https://www.youtube.com/watch?v=olRbG-9mfa0

Side note maybe she can mention that lady gaga has Miku open some of her concerts with that song.

**Comment by kaido1224** [comment]
Feel free to write a dialog yourself, it's more likely to actually be added that way. Make sure that it doesn't sound to fan girly or it will likely be rejected. Here are guidelines for contributing and instructions on how to add dialog and create a pull request here on Github.

https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines
