### ISSUE TITLE
0.7.3 Bugs/Typos

### ISSUE THREAD

**Issue by monikLover** [Monika-After-Story/MonikaModDev#1253]
An issue where all 0.7.3 bugs/typos can be reported.

**Comment by monikLover** [comment]
#1250

**Comment by jmwall24** [comment]
Writing Tip 4, third to last line reads "Otherwise, you won't to get anywhere."

**Comment by HibikiThePhoenix** [comment]
My game crashes because it says " An exception has occurred when loading <'Image' u'mod_assets/room/roses-n.png'> ". Is there any way to fix this error?

**Comment by Tiler17** [comment]
![screenshot0004](https://user-images.githubusercontent.com/36717174/37438361-020de980-27c0-11e8-8432-b6fa2bd20c02.png)

Stick *of* carcinogens?

**Comment by Tiler17** [comment]
![screenshot0005](https://user-images.githubusercontent.com/36717174/37438475-a5498294-27c0-11e8-8f57-4d15f5a28f48.png)

Makes *me* so excited

Don't worry, folks, I'm here all night

**Comment by neyoriquans** [comment]
I'm not sure if this is a bug or a feature, but I have the repeat topics on, and yet Monika has reverted to the "silent treatment" reminiscent of version 7.1 I believe. I have been running the game for today for a while and have covered many topics, so I don't know if she's taping out because of that, and that there's a limit to how many things she can talk about per day or if it's a bug.

**Comment by jmwall24** [comment]
That's not a bug, she needs her 6 hour rest before she'll start talking on her own again.  I had the same question with #1129

**Comment by neyoriquans** [comment]
Okay, thanks for the clarification!

**Comment by 1979pumpkin** [comment]
Monika: Thank you so much for making _me_ feel alive and not alone.

When you finish Monika's game regarding the white day

**Comment by Tiler17** [comment]
When you have the 80s Doki Doki theme playing, you get the dialogue for no music when you talk to Monika about the current music. Which sucks, because 80s Doki Doki is best song

**Comment by Tiler17** [comment]
![screenshot0006](https://user-images.githubusercontent.com/36717174/37439828-ea6cd5ae-27c7-11e8-8bce-ba4ed14b1e5e.png)

...if things didn't work out *the* first time.

**Comment by jmwall24** [comment]
Where is the talk about current music dialogue?  I've seen it mentioned before but haven't come across it yet.

**Comment by Tiler17** [comment]
@jmwall24 It's one of Monika's random topics. You can find it under Misc. called "Current Song." She has a couple of new dialogues, so maybe you just haven't seen it yet?

**Comment by jmwall24** [comment]
Aha, there it is, overlooked it.  Thanks!

**Comment by HrenBren** [comment]
![screenshot](https://user-images.githubusercontent.com/37421222/37491067-73db795e-2894-11e8-8242-78192713ee38.png)

can anyone help please?

**Comment by jmwall24** [comment]
@HrenBren refer to #1247

**Comment by Flutterbox** [comment]
not sure if its a bug, but I dont think it was intentional. after updating (before update I had exhausted all her random dialog), her first new dialog involved several "..."'s, then she described a scene where we lean in closer and kiss, followed by her talking about coming into my reality (something like that).  I cant find this dialog in the "repeat conversation" section

**Comment by jmwall24** [comment]
It's actually the 'Current Song' dialogue for when there is no music.  It's under 'Misc.'

**Comment by antimockingjay** [comment]
In the "Monday morning" greeting, there's a missing period, as well as an unneeded space between a word and three periods.

**Comment by IlywI** [comment]
So i manually downloaded the update but i think the game thinks that i have received the gift but i did not :/ so should i like reinstall mas from start?

**Comment by Trainerbluetube** [comment]
![screenshot 7](https://user-images.githubusercontent.com/35549063/38003352-3013b496-3205-11e8-8ec4-f322f9d80880.png)
"Make sure" not "makes sure" in writing tip #5

**Comment by jmwall24** [comment]
Kinda weird I just got the 'there is an update available' prompt when loading the game today.  I was getting it after I manually updated, but haven't gotten it in a week or so and as far as I can tell there is no update.
