### ISSUE TITLE
Problem with update

### ISSUE THREAD

**Issue by 1979pumpkin** [Monika-After-Story/MonikaModDev#1255]
I tried updating the mod by myself and i think i messed up, because whenever i try to open up the game, the traceback text file opens saying: _Name (u'/Users/pi/Documents/Renpy/Monika After Story/game/chess.rpy', 1518620781, 1) is defined twice, at Monika_After_Story-0.7.3-Mod/chess.rpyc:3 and game/chess.rpy:3._

I tried reinstalling the game but it stays the same, how do i get it working ? 

Thanks in advance.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/1813562/traceback.txt)

**Comment by ThePotatoGuy** [comment]
If DDLC doesnt open, then check `game/` for a folder like `Monika After Story`. If it is there, please take the files out of that folder and put them in `game/`. (The mod files **cannot** be in a subfolder in `game/`). Then delete the folder `Monika After Story`

**Comment by 1979pumpkin** [comment]
Thanks it solved my problem, now i need to figure out what Monika's gift is
