### ISSUE TITLE
(Suggestion) Monika talking about charity

### ISSUE THREAD

**Issue by Tsadokiel** [Monika-After-Story/MonikaModDev#1257]
I was wondering if it would be in character if Monika talks about charities in general and the means to contribute to a good cause (donating money, clothes, work as a volunteer, etc.). She would then asks the player if they have ever done such a thing or if they intend to do it, or something like that.

I'll try to write something about in the future, but I wanted to see if it was alright to talk about it first.

**Comment by kaido1224** [comment]
Sounds like a decent topic to me.

Feel free to write a dialog yourself, it's more likely to actually be added that way. Here are guidelines for contributing and instructions on how to add dialog and create a pull request here on Github. Once you create a PR, one of the Jr. Writers or Writers will check your dialog and probably ask you to make some adjustments. Then once that is done, the editors will review it, make any additional changes they see fit and add it.

https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines

**Comment by MarkusRamikin** [comment]
Monika strikes me as someone would appreciate the concept of "effective altruism", i.e. targetting your money where you can do the most good with your limited budget.

**Comment by kaido1224** [comment]
Topic has been made into a PR. Closing
