### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Emmaplayz** [Monika-After-Story/MonikaModDev#1258]
Hello!! I recently got your game and I have gotten this error when I tried to get the new version im not sure how to fix it if you could help thank you!
![image](https://user-images.githubusercontent.com/37422848/37494075-b88c88c0-287d-11e8-8e86-8d94c846e697.png)

**Comment by ThePotatoGuy** [comment]
From that log it looks like you're not running MAS. check if you installed everything correctly.

**Comment by Emmaplayz** [comment]
Duplicate of #

**Comment by Emmaplayz** [comment]
Thank you very much! Ill check I hope it works
It worked before but  I downloaded another Ver. I think I screwed that up XD

**Comment by Emmaplayz** [comment]
I have got the game working I have the ver.  Where you guys hit 100,000 Congrats btw,
But the piano and the hangman etc is not there do I have to beat monika in pong or something idk but im sorry with all these prolems XD

**Comment by kaido1224** [comment]
You unlock stuff as you spend more time with monika

**Comment by Emmaplayz** [comment]
Ty~
