### ISSUE TITLE
birthday celebration

### ISSUE THREAD

**Issue by todemodu** [Monika-After-Story/MonikaModDev#1261]
is there any way we can get Monika to celebrate our birthday with us? I know she can say happy birthday to someone else but can we find a way to input our birthday and get a little message or something? or maybe even a way we can celebrate her birthday when it comes around?

**Comment by kaido1224** [comment]
Once https://github.com/Monika-After-Story/MonikaModDev/issues/37 this may be possible. This suggestion has been made multiple times. Once we get this implemented, we'll look into celebrating the player's birthday.
