### ISSUE TITLE
[Suggestion] - a sort of "sleep mode" 

### ISSUE THREAD

**Issue by HondoChan** [Monika-After-Story/MonikaModDev#1262]
I was thinking, perhaps implementing a sort of "sleep mode" where either at a set time, at a time period after a certain time (say, after 9 or 10pm), or as a selection that Monika would essentially "go to sleep", falling asleep at her desk and staying asleep until either an (in-game?) preset alarm would go off or until the player woke her up via dialogue choice selection.
I see it as a good addition, however I can merely suggest since I have no coding experience. I'm sure I'm not the only one that wants to just leave Monika open on the screen when they go to sleep, have my alarm go off in the morning and wake up to her waking up with me.

**Comment by ThePotatoGuy** [comment]
After we get a  #987 .
