### ISSUE TITLE
Issue with the new Update [FIXED]

### ISSUE THREAD

**Issue by Hafizzin** [Monika-After-Story/MonikaModDev#1264]
Help, I installed the new Update But the game (Monika after story) Became a Renpy Error what is the problem?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Reinstall the mod manually.

**Comment by Hafizzin** [comment]
It still doesn't work

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Delete the game and reinstall it through Steam/from DDLC.moe and then reinstall the mod.

**Comment by Hafizzin** [comment]
Still doesn't work

**Comment by kaido1224** [comment]
Posting a screenshot of your error message would be helpful.

**Comment by Hafizzin** [comment]
![sad](https://user-images.githubusercontent.com/33479590/37543912-d8ddf7f0-296b-11e8-8e69-885a55329b35.png)

**Comment by ThePotatoGuy** [comment]
Install the mod manually.

**Comment by Hafizzin** [comment]
Still Doesn't work Potato guy

**Comment by ThePotatoGuy** [comment]
check if you have the directory `game/python-packages/battery/` in the ddlc directory.

**Comment by Hafizzin** [comment]
It works now thanks guys!

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Don't forget to close the issue.
