### ISSUE TITLE
Update Version button doesn't work

### ISSUE THREAD

**Issue by Denymeister** [Monika-After-Story/MonikaModDev#1267]
This isn't exactly an urgent issue, just wondering if anyone else had this problem:
Simply enough clicking 'Update Version' just exits the menu completely and brings me back to the previous screen.
https://gyazo.com/8df461653455e5bd1cf6f1ee92f58172
It did work in previous versions, I believe the 0.6 series worked fine.

**Comment by ethancedrik** [comment]
Mine downloaded the mod, but failed to replace the existing files with the new ones, so I was left with a bunch of (file).(extension).new ones, and had to do a search in /game for *.new and delete them all and update it manually from the zip file.

I assume there may have been some file access, etc. issues, maybe running as administrator would have fixed that in my case

**Comment by ThePotatoGuy** [comment]
Could not reproduce this. File access issues are beyond our scope.
