### ISSUE TITLE
MAS updater stuck on unpacking???

### ISSUE THREAD

**Issue by SpringingTraps** [Monika-After-Story/MonikaModDev#1268]
![image](https://user-images.githubusercontent.com/36118304/37547710-a7ca31c8-2949-11e8-866e-6fbb46b359ea.png)

please help!

**Comment by TinyInternetTree** [comment]
Close the game and try installing the update manually.

**Comment by SpringingTraps** [comment]
how do i install it manually?

**Comment by TinyInternetTree** [comment]
Download it from https://github.com/Monika-After-Story/MonikaModDev/releases then put everything in the Monika_After_Story-0.7.3-Mod folder into your "game" folder your ddlc directory.

**Comment by SpringingTraps** [comment]
do i extract it first or?

**Comment by jmwall24** [comment]
Extract, and then open the extracted folder, then open the Monika_After_Story-0.7.3-Mod folder that is inside, and copy everything in there (all 43 items) and paste those into the "game" folder that @TinyInternetTree mentioned.  Don't just copy and paste the zip or folder and paste it, it has to be the actual content of that folder I mentioned.

**Comment by TinyInternetTree** [comment]
No need.

**Comment by SpringingTraps** [comment]
I've extracted it, but it says 229 items! What do i do?

**Comment by SpringingTraps** [comment]
Oh, nevermind! The updater's working now!

**Comment by kaido1224** [comment]
Can you please click the close button for the ticket since it's resolved?
