### ISSUE TITLE
Hello! Just a small question about the art.

### ISSUE THREAD

**Issue by nategmonkeymaster** [Monika-After-Story/MonikaModDev#1269]
I play the mod a bit, but I have noticed that in certain poses that Monika does, her neck is a bit illuminated. I did not know if this was intentional or not, but I feel that it may needs some adjustments.  Thank you for your time.

**Comment by ThePotatoGuy** [comment]
Could you take screenshots of the poses you're talking about?

**Comment by nategmonkeymaster** [comment]
![mon1](https://user-images.githubusercontent.com/37462879/37810432-4f59c6f8-2e11-11e8-9945-9d3f9c023d2c.png)
![mon2](https://user-images.githubusercontent.com/37462879/37810433-534c8d90-2e11-11e8-8076-8ad917f186a1.png)
Here are the screenshots.  If it doesn't show up then I'll see if I can try something else.
