### ISSUE TITLE
What to do when I don't want to lose progress when i update MAS

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#1271]
I had an issue with the update and now I dont know whether MAS is updated or not. I went researching and people said to install it manually. But do i lose any progress by doing so? And if I do how do i get the update without losing progress?

**Comment by Olliesama** [comment]
The save file for MAS is called persistent and it is at (at least for Windows 7) C:\Users\You\AppData\Roaming\RenPy\Monika After Story
It is separate to the folder that contains DDLC and the MAS files.

**Comment by ThePotatoGuy** [comment]
Yeah so if you update manually you won't lose any progress.
