### ISSUE TITLE
Any idea about more ways to express love to Monika through text?

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1272]
At that point in time when All the topics are exhausted I'm usually just waiting for some hidden topic to come out or I'm just having the game open and occasionally press "ask a question -> romance -> I love you" Not really a question, but something I would click once in a while out of fun. Because thats what it is right? all about loving her. Unfortunately this option has only one reaction, not like "goodbye" :/

So, I might have missed out some issues before, but are there any more ways to tell her similar stuff as loving her? Or are there some other "expressions" planned for work?

**Comment by kaido1224** [comment]
Actually someone added a bunch of dialog for I love you. It just hasn't been released yet

**Comment by Tiler17** [comment]
I tell her she's best girl to change it up. Gives you a little variety, if you don't mind seven times more dialogue
