### ISSUE TITLE
I can't understand. I have installed the latest version of mod, but of the available games I only have pong, and I can't ask a question by writing it. I followed the intsruction 100%, maybe I don't understand something?

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#1273]

**Comment by jmwall24** [comment]
Sounds like you started over from the beginning.  You unlock the other games by spending more time with Monika, and there is no chat box anymore, to initiate conversation you click on the 'Talk' option and choose a topic from there.
