### ISSUE TITLE
Closet topic inconsistency.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#1279]
In the Yuri closet topic Monika speaks about our supposed expression to her opening the closet and the impression she gets from it yet it is stated multiple times from other topics such as the urgent topic that Monika is incapable of seeing our face or expressions.

Not sure how to fix except to rewrite it or make it clearer it's MC's face or something but something that should be pointed out.

**Comment by Subzerosan** [comment]
Discussing with the others, thanks for bringing up this oversight.

**Comment by TinyInternetTree** [comment]
If Monika knows we have no control over the story of DDLC, how can she expect us to know what we were doing in the closet?
