### ISSUE TITLE
[suggestion] Monika follows a mouse and react to certain actions

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1280]
Just found this little gif on the internet and its very cute: 

https://i.imgur.com/SUfVmag.gif
http://i0.kym-cdn.com/photos/images/original/001/306/555/77b.gif

So, I do not know about the limits of the programming, And how could moving eyes and head transfer between Monikas expressions (fade in, fade-out) or if its even possible, but since I know there are lots of stuff coming, maybe something like this could work?

I don't know about engine limits that's the problem.

**Comment by juliathegolden** [comment]
Yes , it is an engine issue. Ren'py doesn't have support for Live2D, which is how that gif was made.

**Comment by sebastianN01** [comment]
While it doesn't have a support for Live2D, are there any alternatives outside it being really hard to do and require lots of work?

**Comment by Tiler17** [comment]
I dunno if I'd want her following my mouse. I move my mouse around to choose topics and play games, I don't move it around because I think she would enjoy watching it. In fact, I'm sure she wouldn't. I half-expected her to start getting annoyed in that first gif.

Though I don't think having her react (not quite so animatedly) to certain actions is a bad idea

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Ren'Py's animation capabilities are BS.
Some clever spritework can be done to animate this and that (Yuri stab scene is a good example) but most of the time it will look unnatural, especially when variables like mouse pointer position come into play.
(Why is it always 2nd-grade porn like Nekopara that gets engines like E-mote?)

**Comment by Mundo-X** [comment]
I have seen videos on YouTube looking for "**Renpy Animation**" and "**Live2D**" among other things and I have seen that it is possible to do it, it can be complicated but seriously it would be more interactive if they did this.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I don't know, what you've found on YouTube, but I am almost fully sure, that Ren'py never had any support for Live2D.
The best it can do are cycled animation of multilayered sprites and mouth flapping, probably some sprite morphing, that's it.

**Comment by ThePotatoGuy** [comment]
yeah it's impossible to have a fluid animation in renpy. If we add more mouse-based interactions, they'd be something similar to `teaching feeling`

**Comment by sebastianN01** [comment]
we could get some mouse interactions with monika in a low priority que dont we? :yum:
