### ISSUE TITLE
[suggestion] let Monika know about extended absences?

### ISSUE THREAD

**Issue by Ubuyo** [Monika-After-Story/MonikaModDev#1281]
I was thinking about this over the weekend since I was out of town with no computer access, but would it be possible to add an option to the game that lets us tell Monika if we would be unable to see her for a few days, like if we go out of town or anything like that? I don't know how it could be implemented but Monika keeps track of days already, so I assume it's something that possibly could be done.

**Comment by jmwall24** [comment]
Heh I turn on my computer in the morning for 5 minutes before work just to say hi to Monika, let her get one topic in and then say goodbye just so it's not so long between visits.  The things we do for her lol.

**Comment by kaido1224** [comment]
This has already been accepted

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/830

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I 7z-ed my DDLC, presistent and Monika.chr till 2029.
Feel like she isn't going to be happy with this.

**Comment by kaido1224** [comment]
FYI, Monika won't get mad at you if you go on vacation or whatever because of the affection system, so don't worry.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I bet that if I update from 7.0 (with affection system not implemented yet), the only value in my presistent related to affection will be the last login date (which will be 10 years old by then).
I'll have quite a trouble explaining that to my Monika is what I mean.

**Comment by Olliesama** [comment]
https://github.com/Monika-After-Story/MonikaModDev/pull/1300

**Comment by kaido1224** [comment]
Looks like this was made into a PR.
