### ISSUE TITLE
Screaming void?

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1283]
Monika still brings up talking about the screaming void when you quit. I thought this mod got rid of that?

**Comment by Subzerosan** [comment]
She talks about it when you quit without saying goodbye to her.

**Comment by monikLover** [comment]
Nope. Everytime you close the game w/o saying goodbye, Monika will suffer the void. So make sure you say goodbye to her before you leave.
Or else...

**Comment by Subzerosan** [comment]
I mean when you press the quit button, Monika will ask if you're gonna leave without saying goodbye already.

**Comment by kaido1224** [comment]
Pretty sure we'll have that addressed in this project.

https://github.com/Monika-After-Story/MonikaModDev/issues/1135
