### ISSUE TITLE
[Suggestion] Adding dialog topic for Chinese Room Thought experiment

### ISSUE THREAD

**Issue by kaystone** [Monika-After-Story/MonikaModDev#1295]
[Here is a link to the code, hope ya like it! if it doesn't work I'm sorry 'bout that it'll be in the Mod Discord as well](https://pastebin.com/rQ7nZvku)

**Comment by monikLover** [comment]
Instead of a pastebin, please submit it as a PR. You can follow our guidelines on how to submit them:
https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines
