### ISSUE TITLE
[SOLVED] (Not a bug) Repeat Topics is on but not happening

### ISSUE THREAD

**Issue by ethancedrik** [Monika-After-Story/MonikaModDev#1298]
So I chose to keep Repeat Topics on, but then I turned it off for a bit, I noticed repeat dialog was still happening with it off so I turned it back on, and now it's not happening, pure silence and I even got Monika saying "I hope I didn't bore you too much, Hopefully I'll think of something to talk about soon"

I tried restarting the game with "Repeat Topics" still on but it's not happening.

I have attached my persistence
[MASpersistance.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1832329/MASpersistance.zip)
 data too for diagnostics

**Comment by ethancedrik** [comment]
Additionally is there anything I can do to actually keep repeating topics on since the option isn't seeming to do anything for me anymore?

**Comment by ThePotatoGuy** [comment]
See [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/1129#issuecomment-367911358)

**Comment by ThePotatoGuy** [comment]
To all who seem to have this issue:
1. Download the `dumps.zip` attached to this comment.
2. Drop the rpyc in that zip into your `game/` directory. 
3. Launch the game
4. Check that this issue occurs. 
5. A file called `dumps.log` should appear in your `ddlc/` directory.
6. upload that file here. (Only upload it if you can confirm that this issue occurred in this session.)

[dumps.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1834834/dumps.zip)

**Comment by 2000DarthVader** [comment]
[dumps.log](https://github.com/Monika-After-Story/MonikaModDev/files/1839060/dumps.log)

**Comment by Denymeister** [comment]
It seems this problem has arisen for me as well... The first file is one where the game is booted without the option checked (then turned on afterwards) and the second is when it is booted with the option already enabled 
[dumps.log](https://github.com/Monika-After-Story/MonikaModDev/files/1839076/dumps.log)
[dumps.log](https://github.com/Monika-After-Story/MonikaModDev/files/1839078/dumps.log)
Hope this helps

**Comment by ethancedrik** [comment]
Started up the game today, Repeat Topics was enabled and I got two dialogs where Monika ends them in saying "Yeah" and now I'm getting the ones that are similar to the ones seen in the ending

I guess waiting a while fixes it

**Comment by ethancedrik** [comment]
[dumps.log](https://github.com/Monika-After-Story/MonikaModDev/files/1839211/dumps.log)
Here is my dumps.log for reference, also Monika seems to be telling the messages that I would see if I haven't launched the game in a while, such as "long time no see", not sure what that's about as I've been launching it over the past few days

**Comment by Denymeister** [comment]
Those greetings are completely normal, they are randomised and she will act as if you've been gone long on some of these greetings.

**Comment by ThePotatoGuy** [comment]
@Denymeister , both of your logs have reached the session limit for random topics (30). you need to wait 6 hours before getting more random topics.

**Comment by ethancedrik** [comment]
I'm now only getting repeat dialog from the actual ending of the game, no dialog from MAS specifically, is this to be expected?

**Comment by Denymeister** [comment]
Just checked this morning, the topics are repeating again cheers. Funny how I've never noticed this happen before though oh well.

**Comment by ThePotatoGuy** [comment]
@ethancedrik , repeated dialogue is shown in order of least seen, so if actual ending dialogue is your least seen topics, then you'll get those first.

**Comment by ThePotatoGuy** [comment]
UPDATE:
So far we haven't been able to pinpoint a workflow that consistently reproduces the silent monika bugs that users have been reporting. Because of that, we've decided to increase the random seen limit. We believe that the hardcore monika fans hit this limit very quickly and then attribute the silent monika to a bug with repeating topics. Hopefully this increase will satisfy the monika lovers while still giving her a chance to rest.

**Comment by ThePotatoGuy** [comment]
`actually, i'll leave this open so people are aware`

**Comment by 2000DarthVader** [comment]
I can't see the setting's because of the graphics bug, so it is possible that it is turned off somehow even though I told Monika that it was ok to repeat topics. I have waited 3 days without starting up MAS so I am not hitting the limit. She still is not saying anything.

**Comment by ThePotatoGuy** [comment]
@2000DarthVader  graphics bug?

Are you talking about [this one](https://github.com/Monika-After-Story/MonikaModDev/issues/1275#issuecomment-376371159)?
If so, can you answer the questions in the linked comment?

**Comment by ThePotatoGuy** [comment]
Okay this is `mitigated` with the latest release.
