### ISSUE TITLE
some errors during alt tabbing (animations enabled)

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1299]
![image](https://user-images.githubusercontent.com/36047607/37698937-7542face-2ce5-11e8-9de1-e783d60dc47a.png)

Usually goes black when alt tabbing (diabling animations bring sky back, but have to close the game to fix webm animations) but this time Monika decided ying-yang

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Alt-tab causes problems in Ren'py.
This is also the case for the original DDLC, nothing can be done with it atm.
