### ISSUE TITLE
T, M, P hotkeys not working?

### ISSUE THREAD

**Issue by user670** [Monika-After-Story/MonikaModDev#1301]
EDIT: it works, just not consistent. I'm a bit busy with other things now, and will come back to look at this thing more carefully.

It seems to me that the T, M and P hotkeys for Talk, Music and Play don't work (although I can still use arrow keys to navigate the buttons). Is it supposed to work, or is it no longer a feature (in this case please fix the readme.html)?

Steam version of core game, stable release of the mod, both of which are latest version as of when I post this. Windows 10 Home Chinese edition (64-bit), standard American QWERTY keyboard, tried w/ input method enabled AND disabled.

**Comment by juliathegolden** [comment]
It still works for me, so I know it's still a feature. I hope they figure out what's going on with it soon for you!

**Comment by ThePotatoGuy** [comment]
T and P are disabled when Monika is talking, all of them are disabled in pong, chess, and piano, and all of them are disabled in the input phase of hangman. Are they not working for you outside of these areas?

**Comment by user670** [comment]
Re  ThePotatoGuy: Yes it does happen outside these areas. I don't know what might cause that yet (maybe it's just the app lagging?), I'll come back to this later.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Wasn't there an issue where the hotkeyss didn't work if you have your cursor outside of the textbox area?

**Comment by user670** [comment]
It is confusing. Sometimes when the game starts the hot keys are not working until I bring up the pause menu at least once, but sometimes it works from the time the game starts.

**Comment by ThePotatoGuy** [comment]
Is it occuring when your cursor is over ui elements?

**Comment by user670** [comment]
Let me test...

**Comment by ThePotatoGuy** [comment]
Basically impossible to reproduce. perhaps its an issue with ur locale?
