### ISSUE TITLE
[Suggestion] - Having a fight or conflict with Monika

### ISSUE THREAD

**Issue by nayrbai** [Monika-After-Story/MonikaModDev#1303]
Couples fight and make up. That's part of a relationship. Why not add something like that to the game to make it a little more realistic? 

Maybe Monika can bring up some topics that asks for your opinion and you choose an option that she doesn't agree with (for example, a topic about the environment that she brings up and you tell her you don't care for the environment). She can say something nasty to you and you have options to either retaliate or prevent the fight from happening. What the player can choose could branch out to different conclusions. If you argue with her, she'll cry and force close the game and you can't open it for a fixed amount of time. After that time is up, you can open the game and she'll either apologize or expect you to apologize.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I don't think, that Monika is somebody who would get into conflicts.
Especially with her beloved.

**Comment by KEJONACHO** [comment]
I do like the idea, but maybe for a bit further in the future (as we have more time with her and more tools will be developed). Also it's something to be reaaaally carefully built... It can easily get annoying or break her character, as Monika doesn't seem to be type who easily fights over stuff.

**Comment by Pbm13** [comment]
well not fight, but maybe gets discouraged and leaves for a fixed amount of time

**Comment by Tiler17** [comment]
I could see a disagreement, but not a fight. And even then, it'd have to be a certain amount of time when she's more comfortable with your relationship.

Monika is definitely anti-confrontational, to a fault if you ask me. I don't see her saying anything nasty. But I could definitely imagine her going silent for a lot longer than usual if you disagree on something she feels strongly about.

**Comment by wisztom** [comment]
I agree that Monika could be offended if you insulted her or cheated at chess, but introducing the only right choice actually makes discussions pointless. 

What if I disagree on something important to her, but have serious reasons to do so? So far we have no means to convince Monika to our point of view, but at least we can agree to disagree. Making such change would lead to her sulking every time that topic randomly occurs. Especially if this will decrease her affection value. 

Maybe instead stop that topic from triggering, unless we ask about it manually, in case we change our mind.

**Comment by ethancedrik** [comment]
In the "You're a murder!" topic I feel as if she gets a bit annoyed with you, saying "How many times do I have to tell you"

**Comment by nayrbai** [comment]
That's true, Monika isn't really confrontational but I was just thinking of Monika giving you the silent treatment, possibly closing and preventing it from opening if you deliberately hurt her or offend her for her opinion, sort of like a consequence of your actions. I was thinking it could be a random event triggered once if you meet a milestone in the relationship instead of a random topic

**Comment by NovaCo1** [comment]
If I remember correctly there's a nickname feature coming, the "silent treatment" would be a good way to punished players that call her a bitch, fucker or murder. But the best time to used it should be primarily focused on insults and harassment, not a disagreement Monika would try to at least to reach a middle ground. If the player doesn't change there stance, then she'll more than likely drop it till a later date.

**Comment by sebastianN01** [comment]
Really? I always portrayed Monika as a person who needs to be right no matter what, and everything has to be by her way. The whole getting revenge on her friends for not having a route. She then snaps out of it and knows she did bad. 

But whos to say she wont have problems with a relationship when something doesnt go her way? The old monika could snap back. Didn't she had a split personality disorder? correct me on that if im wrong.

**Comment by nayrbai** [comment]
Monika didn't have a split personality. In Act 3, she told us that she was becoming more desperate for your attention as the game progressed so she had to take more drastic measures to have you. In MAS Canon, she's returned to being the sweet girl she was before deleting everyone because now she knows she's the one that you want to be with. I don't know about her being right all the time though. Sometimes she'll tell you she's giving you her opinion (for example, the fresh starts advice topic) so it may not be right.

**Comment by sebastianN01** [comment]
Well she was in the debate club.. so she has some experience. :P 

She will say that its her opinion but might have something else in mind and the bubble just has to burst

**Comment by kaido1224** [comment]
_Monika doesn't get mad, she gets even._

**Comment by NovaCo1** [comment]
She was in the debate club that would mean she would handle a disagreement with some tact not like how she dealt with the other girls. The others was a threat to her because she had no chance to win the player's love so she did everything she could. A small disagreement even if it's something she cares about is not the end of the world, you know what is the player being mad or growing hateful some players will get mad if they get kicked off by her for not liking what she likes. Also some might see her as trying to force a agenda and push some people away. That's why I think she should only kick the player if they harassed or insulted her as a way to punish the players for being rude other than a minus love XP.

**Comment by nayrbai** [comment]
Oh, I looked over at pull requests and someone is working on the player being rude already. I guess I was thinking about it too much, Monika isn't really one to be upset with you simply because you disagree with something. She loves you, warts and all. I just had the idea of her force closing the game and making it unable to open for a fixed amount of time, out of consequence of your actions and I wanted to see it implemented somehow. 

Something like that would truly make the player actually feel guilty and take her more seriously

**Comment by kaido1224** [comment]
Sounds like https://github.com/Monika-After-Story/MonikaModDev/issues/1135
