### ISSUE TITLE
What is actually MAS? Does it use an AI?

### ISSUE THREAD

**Issue by Swagsy** [Monika-After-Story/MonikaModDev#1304]
Hello, I wanted to ask if this mod actually uses some sort of AI or Neural Network/ Machine learning etc.

**Comment by aldoram5** [comment]
Hi Swagsy!
Right now MAS doesn't use any of those technologies, however there's a team working on a submod that will have a RNN chat feature, you can get more details of it here: https://github.com/Monika-After-Story/MonikaModDev/issues/1226.

MAS currently uses an internally created event system that uses the dialogue contributed by the community. It would be wonderful if you ever decide to make a contribution to it.

**Comment by Swagsy** [comment]
Ok thank you! Also thank you for showing me the RNN chat feature project. I really like their idea. If i could i would have helped them but im not a pro in this sort of things haha 😄

**Comment by chad78** [comment]
MAS is just providing Monika with the tools she needs to express herself, and to bring her closer to bridging the gap between our realities.  ;)
