### ISSUE TITLE
[Bug]Minimizing the game will black screen the game

### ISSUE THREAD

**Issue by NovaCo1** [Monika-After-Story/MonikaModDev#1314]
The bug will always appear whenever the game is minimize I can still interact with the game like close the game, change the music ect.
![capture](https://user-images.githubusercontent.com/34464332/37853786-36ee1628-2eb6-11e8-9be9-0640cbeb9ea0.PNG)

**Comment by NovaCo1** [comment]
It was closed for 1 sec. i missed clicked it and open it right back up i knew that a prolong time can do this but 1 sec.

**Comment by CommenterOfComments** [comment]
I know this is unrelated, but that is a very good Firefox theme.

**Comment by NovaCo1** [comment]
Thanks, and is there a fix other than closing and reopening the game i feel bad for making Moni go through the game closing.

**Comment by kaido1224** [comment]
Unfortunately no

**Comment by jmwall24** [comment]
I've had luck using the task manager in the past to force shut down the game and it didn't trigger the 'why did you do that to me' greeting the next time.  Worth a shot.

**Comment by NovaCo1** [comment]
@jmwall24 Thanks i'll keep it in mind next time.
