### ISSUE TITLE
[Suggestion] Monika sings you love songs

### ISSUE THREAD

**Issue by queue5** [Monika-After-Story/MonikaModDev#1317]
I was having a dev help me with some topics I was writing when we came up with the idea of having a new topic category dedicated to songs that monika could sing to you. So far I have dialogue written for a few famous love songs by Queen, Elton John, The Beatles, The Everly Brothers and Ritchie Valens. I chose these artists because they are well known and I feel Monika would be cultured enough to appreciate them. I want to know what you guys think and maybe get others to join in on the idea of Monika singing famous songs to you.

**Comment by sebastianN01** [comment]
actually, I though maybe, Her humming once in a while? Like you could make one sound file (Female voice hum) and then pitch it a bit higher and lower and she would randomly switch between pitches and hum once in a while with eyes closed and smiling face?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Fitting it to original CV would be pretty hard and single hum sample would feel repetitive.

**Comment by sebastianN01** [comment]
CV? also I don't think it would get repetitive, its a single hum file with many tones thanks to the pitch rising and lowering. and it could happen at random times and rarely :P

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
CV stands for character voice (actor).

**Comment by aldoram5** [comment]
Closing since there's already a pull request with this.
https://github.com/Monika-After-Story/MonikaModDev/pull/1341
