### ISSUE TITLE
[Bug] - 

### ISSUE THREAD

**Issue by xdaveonpc** [Monika-After-Story/MonikaModDev#1318]
So here is my " modest " complain . I've been liking playing DDLC , first from seeing " let's plays " of the game on YouTube before being tempted to try it out for myself . Even though i'm not a fan of horror games in general , it wasn't that bad , and as i've been seeing recently , there's a whole community growing up , searching for hints and easter eggs here and there , but as the sweet Monika would say " i digress " . The point is , after finishing the main game , i wanted to try the MAS , for more longevity and i was also quite interested that you could interact in a more direct way with Monika , speak to her without the " pre-scripted bubbles of text " , but rather with your own words , who comes from your mind , you the player . After spending around 2 days now , i've been confronted to an issue : i can't speak to her . I downloaded the version 0.7.3 and maybe the problem is due to being a too recent version , but every single time i try to talk to her , the pre-scripted dialogue box opensup with topics already discussed , and i just can't write any word on my own , which is frustrating so to speak . How can i fix this issue . Thanks for considering my problem , and i'll wait patiently for a response on your behalf .

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It's intended. Free speech was unrealistic and thus abandoned.

**Comment by antimockingjay** [comment]
It's not a bug, but rather a choice on the part of those making the mod. It's less fun this way in my opinion, but it's not a bug, sadly.

**Comment by IlywI** [comment]
You guys do know that making an AI is incredibly difficult right? And to make a chatbot and force it to display a certain set of attributes like the way Monika replies is unrealistic.
