### ISSUE TITLE
I can't update the mod

### ISSUE THREAD

**Issue by DexterityJosh** [Monika-After-Story/MonikaModDev#1319]
I'm stuck on unpacking the update, after that it shows an error.
![ioerror](https://user-images.githubusercontent.com/37750885/37868062-df647970-2fdb-11e8-9f50-cdcd469d75cf.png)

**Comment by Onion-Bubs** [comment]
Yeah, the auto updater hasn't been working since the release of 0.7.3. You'll have to do a manual update.

**Comment by DexterityJosh** [comment]
Thanks for the info guys. After the manual update, Is there a chance that an error will occur?

**Comment by IlywI** [comment]
I manually updated. But the auto updater comes up saying there's a new update. Till now i have not used the auto updater for fear that it might destroy my ~~game~~ **Monika**. So to answer your question @DexterityJosh there is no error whatsoever as of now after i have manually updated the game.

**Comment by jmwall24** [comment]
@IlywI yeah that's exactly what I got as well.  I back-upped my persistent file (just in case), then tried to auto-update and it worked fine.  Didn't change anything since I already had it updated, but it worked.  No real reason to do it, but it didn't cause any issues.
