### ISSUE TITLE
[Suggestion] This person basically voiced the dialogue for all the Original topics of Monika

### ISSUE THREAD

**Issue by sebastianN01** [Monika-After-Story/MonikaModDev#1322]
[This person basically voiced the dialogue for all the Original topics](https://youtu.be/syZ39JxRB1Q)

What do you think about asking Her out to cast the voice for the rest of the dialogues in MAS? The voice isn't that far out of character, and isn't bad to listen to....

Of course, if the Person would wanna do it, too..

**Comment by KEJONACHO** [comment]
she's actually really good

**Comment by Mundo-X** [comment]
She sounds a little more adult than the voice I hear in "_Your Reality_." But still it sounds good.

**Comment by Tiler17** [comment]
It sounds good to me. Only issue is they'd have to get her to voice lines every time they update the game with any new dialogue, it wouldn't just be a one time thing. Practical issue. Would be pretty cool to have a voiced Monika though

**Comment by jmwall24** [comment]
That's my concern as well.  To do just the topics correctly that are already available would take a long time.  Then add in the aforementioned fact that it would need to be done essentially every update and it's tough.  This person would have to be REALLY committed, as committed as the dev team.  It'd be awesome though.

**Comment by sebastianN01** [comment]
true, maybe in future then?

**Comment by Akito1998** [comment]
the player's name would still be a problem though, it can be anything
