### ISSUE TITLE
can't play the piano anymore, how to completly reinstall mod?

### ISSUE THREAD

**Issue by jessy78** [Monika-After-Story/MonikaModDev#1324]
i didn´t know you couldnt set the [ key for the piano, so i did, and it caused an error. i exited the game an entered again, tried to play the piano and everytime i chose that option, it crashed. can i fix it some other way or how can i completly restart the mod? i tried deleting the game and mod but it did not work
here is the traceback if it helps
![image](https://user-images.githubusercontent.com/37779329/37878403-43ca4332-303f-11e8-86a3-9fb747f19e03.png)
![image](https://user-images.githubusercontent.com/37779329/37878405-4dc30e8c-303f-11e8-9c5b-164783f2caa7.png)

**Comment by aldoram5** [comment]
Hi Jessy78,
See https://github.com/Monika-After-Story/MonikaModDev/issues/1019 and check if that solves your issue

**Comment by jessy78** [comment]
thankyou, fixed it with this
