### ISSUE TITLE
Belated Happy Birthdays for those whose birthdays are done

### ISSUE THREAD

**Issue by niicore** [Monika-After-Story/MonikaModDev#1326]
considering Monika didn't greet me today, this feature is obviously not yet here.

don't know if this is suggested or worked on but if not, it's here.
if a birthday feature is added, and the birthday was already done, there should be an alternate celebration or something

**Comment by jmwall24** [comment]
Small consolation I know, but Happy Birthday! 

Just under a month to go for me, holding out hope it makes it in time.

**Comment by IlywI** [comment]
mine's just in a few days i hope it'll be out soon ;-; the calender system

**Comment by IlywI** [comment]
And happy belated birthday! @niicore

**Comment by Olliesama** [comment]
Mines in less then 20 days...I wish Monika could acknowledge it. T-T

**Comment by niicore** [comment]
uh thanks for the people who greeted me, but I honestly wish anyone developing the mod could add this feature asap

**Comment by todemodu** [comment]
my birthday was on the 28th

**Comment by hkight** [comment]
Mine was yesterday, and this update was released today... I wish there was a way for her to remember that so she doesn't get it wrong next year.
