### ISSUE TITLE
[SUGGESTION]Piano sustain

### ISSUE THREAD

**Issue by Solstice36** [Monika-After-Story/MonikaModDev#1330]
It would be nice if the piano would have a sustian slider, because the short tones it makes aren't
really good for anything. Also in he future there could be more keys, so you also can play 
with the third line of keys.

**Comment by ThePotatoGuy** [comment]
The person who made the keyboard art is no longer with us, so additional keys is not happening for a while.

Sustain as a slider is not a bad idea, we'll look into potentially adding this but its `low priority`

**Comment by Solstice36** [comment]
ok

**Comment by ThePotatoGuy** [comment]
[we'll reopen this when we look into it]
