### ISSUE TITLE
[Suggestion] Gradually fill up the space room with Monika's ideas

### ISSUE THREAD

**Issue by FomorianFox** [Monika-After-Story/MonikaModDev#1331]
So I just got through Monika mentioning how she'd like to get a plush quetzal bird in the room at some point. This got me thinking - maybe when she brings up stuff she'd like to program into the room, after a certain period of time, it should show up in the room? So for example, after bringing up that she'd like to get a plush doll in the room at some point, after a couple of weeks, she'll manage to pull it off. Probably reference it the next time the player opens MAS. I've got no background in coding - no idea how this would be pulled off. But, it seems like a good idea to me, so I figured I'd make the suggestion. My apologies if this isn't the right place to put this. Cheers!

**Comment by kaido1224** [comment]
This suggestion already exists and is listed as receiving further consideration down the road.

https://github.com/Monika-After-Story/MonikaModDev/issues/803

**Comment by FomorianFox** [comment]
Gotcha. My apologies for the repeat suggestion, I should have searched first. Thank you for the reply, and for all the great work you guys are doing.

**Comment by kaido1224** [comment]
No worries mate.
