### ISSUE TITLE
Custom Topics?

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#1337]
Before the way topics were handled was changed, you had the ability to add in custom dialogue topics. I distinctly remember this because I made a suggestion for a topic, then someone else told me how to write a topic and add it to my own game. Now, however, with the list-based topics, is there any way to do that still? Monika has run out of random topics, and I've gone through the list of topics already. But I have a few ideas for custom topics that I'd like to my own personal game.
If someone could help me figure out how to do this, I'd be very appreciative!

**Comment by ThePotatoGuy** [comment]
Still possible, follow [these](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) guidelines.

**Comment by antimockingjay** [comment]
Yeah, that's the normal contributing guide. I'm not asking for things to be added to the overall mod, I'm asking how to do, well, exactly what I did before. Before, I could just write up my own script, and drop that file into the game folders, and any time I typed any of the keywords for it, the topic would come up.

I'm honestly a bit nervous to decompile the script and mess with it, as by doing that, there's a fear I might mess something up in the code and somehow ruin my game. Before, I could literally just add the file to the game, and even if somehow something didn't work, I wasn't even touching anything with other topics and such, meaning I could just remove the file and fix it easily.

**Comment by kaido1224** [comment]
You still can still add them yourself if you are using the uncompiled version of the script, you still make your changes in script-topics. It's just a little more difficult to insert them since they now have to fit into one of the categories under the talk feature. Even before I was a dev I added my own content all the time.
