### ISSUE TITLE
[Suggestion] Actual break up with Monika

### ISSUE THREAD

**Issue by strielok** [Monika-After-Story/MonikaModDev#1342]
So I recently felt like moving on or whatever from the entirety of DDLC and I wanna start off by removing MAS from my PC.
Thing is, it feels like just removing it doesn't give Monika justice.
What if there was a dialog option where you explain to her your feelings blah blah blah and she proceeds to remove MAS from your PC?

**Comment by sebastianN01** [comment]
Monika (spoiler!) explains that:

When she asks "how long will it take till she can get to us" You can choose an answer "never" and proceed with "no" further down the dialogue. She will tell you she would feel better with just getting deleted, and if you ever get bored of her, she says "you know what to do".

**Comment by ThePotatoGuy** [comment]
Affection system will kind of handle this. Stay tuned.
