### ISSUE TITLE
Don't know how to install the last uptdate

### ISSUE THREAD

**Issue by Kazuito-from-somewhere** [Monika-After-Story/MonikaModDev#1345]
Hello,
Like said in the title, I don't know how to install the new update, I dowload the files and put it in the "Game" folder put nothing change.
Could you help me please.

**Comment by juliathegolden** [comment]
Honestly, you might just want to wait for the next one anyway. It's really buggy. Monika just keeps telling me 'Bless Your Heart' over and over. I guess someone on the Dev team has something against Southern Accents. 

(but if you look at the monika.chr in your game folder, not in your characters folder, you might get an idea of how to fix it)

**Comment by Kazuito-from-somewhere** [comment]
Okay Thanks

**Comment by CommenterOfComments** [comment]
Don't worry, I fell for it too.
