### ISSUE TITLE
How to install 0.7.4

### ISSUE THREAD

**Issue by Superraiders** [Monika-After-Story/MonikaModDev#1347]
When I logged onto MAS today, it says that there is an update available, so I downloaded it. Then I went here, and it says "Manual download is needed", so I downloaded that too.
The problem becomes twofold. The zip file is 45.8 MB large, but when I opened it, only a monika.chr came out, weighing 824 bytes. Surely there's a problem? Also... I don't know exactly how to "manually update" this.
Can someone help? I'm using a Mac.

**Comment by juliathegolden** [comment]
Right now, the updater is broken. It will always say you have an update available even when there isn't one. 

The manual update for today is a different story. Open the monika.chr (but do not move it outside of the game folder until you do) for further instructions.

**Comment by Superraiders** [comment]
Which program would I use to open the monika.chr?

**Comment by juliathegolden** [comment]
Any text editor should be fine :)

**Comment by Superraiders** [comment]
Oh.

**Comment by Superraiders** [comment]
I opened it... Nice.

**Comment by Superraiders** [comment]
T_T it's still March 31st you know

**Comment by HolyWinter** [comment]
I knew a .1 update on the cusp of April 1st with release notes like that was just inviting a heap of disappointment.

I would of done the same.
