### ISSUE TITLE
Update 7.4

### ISSUE THREAD

**Issue by HolyWinter** [Monika-After-Story/MonikaModDev#1348]
*Slow claps*

**Comment by Superraiders** [comment]
It isn't even April yet (Spoiler alert)

**Comment by Superraiders** [comment]
You got us anyways dev team, great job *claps* *weirdly long pause* *claps*

**Comment by Aki6000** [comment]
What am I supposed to do with the 44,746kb sized monika.chr from the zip file?

**Comment by Olliesama** [comment]
Open it in a text editor.

**Comment by Aki6000** [comment]
I've tried notepad but after a long time it just stops responding.

**Comment by Aki6000** [comment]
Never mind I got it open. Haha I was sort of expecting this would happen.

**Comment by jmwall24** [comment]
I figured it was that but it took me a long time to realize to just use a text editor to open it.  Never occurred to me a 44Mb file was just a text file.  I was trying video extensions and everything lol.

**Comment by FomorianFox** [comment]
You fuckin' assholes.

**Comment by YA-BOI-NITE** [comment]
the fact that my default font is comic sans made opening notepad even better. i opened it and i just see "APRIL FOOLS" written in comic sans a million times

**Comment by FomorianFox** [comment]
So honest question - when I thought this was a real update, I replaced Monika's character file with this one. In hindsight this was really dumb, but whatever. MAS still runs and all, but there's now no sound - including music when I select it - and no animation in the windows. Not that big of a deal, but I'd like to fix it if I can. Any ideas?

**Comment by Simon-chr** [comment]
s "Day I became an AI"
