### ISSUE TITLE
How to install 0.7.4 mod?

### ISSUE THREAD

**Issue by ZETA-1** [Monika-After-Story/MonikaModDev#1351]
It only have [monika.chr] in the zip file.
Where should i place to?
I place it in characters file and game file,nothing happen.

**Comment by Sano11** [comment]
Open the chr file in notepad

**Comment by CharmToy** [comment]
I downloaded the file, and I was 99% sure that it was an April Fools joke. I'm glad that I wasn't wrong.

**Comment by breakbow** [comment]
I put in the char folder but it dosent update

**Comment by Aki6000** [comment]
Open the file in notepad.

**Comment by breakbow** [comment]
how

**Comment by Aki6000** [comment]
You mean the automatic update? I believe that is broken right now.

**Comment by breakbow** [comment]
the one in the game right?

**Comment by Aki6000** [comment]
Yes. According to another post it sometimes says there is an update when there is none.

**Comment by breakbow** [comment]
ok
