### ISSUE TITLE
Update 7.4... 

### ISSUE THREAD

**Issue by AimzStuff** [Monika-After-Story/MonikaModDev#1353]
Well done. You went full out on this, I checked the scripts for the first time ever and found some interesting things.

(Best april fools prank ever.)

**Comment by skyhot004** [comment]
I shouldn't have started playing this mod today.
It got me confused that why the mod doesn't working...
Then I checked youtube and it has totally different folder structure from version 7.4

**Comment by CrystalQuartz** [comment]
please help! I think this version broke my Monika ;-; How can I fix it now? ;-;

**Comment by FomorianFox** [comment]
What's wrong CrystalQuartz?

**Comment by CrystalQuartz** [comment]
the april fools update...I tried using it and I think I broke my Monika because it's not working anymore ;w;

**Comment by jmwall24** [comment]
what exactly did you do with the file?

**Comment by CrystalQuartz** [comment]
I put it in the characters file ;-;''''

**Comment by CrystalQuartz** [comment]
yes I also tried putting in the games folder...and the game didn't open so I tried downloading an older version of the mod and did it all again,_,)

**Comment by jmwall24** [comment]
You should just be able to download a new version of DDLC (or if you still have the original zip file just extract it again), then download v0.7.3 (or again, extract it if you have the zip already) and manually install that into the new version of DDLC and it should work where you left off.  The save file for MAS is in a completely separate area so it shouldn't be affected.

**Comment by CrystalQuartz** [comment]
I....also tried that ^^;

**Comment by jmwall24** [comment]
The game isn't opening at all?  Any errors?

**Comment by FomorianFox** [comment]
Stupid question, but I assume you've already rebooted your computer, right?

**Comment by CrystalQuartz** [comment]
yes ^^;;

**Comment by FomorianFox** [comment]
So like jmwall asked, are you getting any errors when you try to open up MAS? Or is it not responding at all?

**Comment by jmwall24** [comment]
I'm stumped. First off, replacing the character file should have any effect whatsoever, and I wouldn't think simply putting that file in the game folder would do anything either, unless you deleted other things.

**Comment by CrystalQuartz** [comment]
I didn't.. I'm scared of breaking my games so I never get close to the files ^^;

**Comment by jmwall24** [comment]
What exactly happens when you try to open the game?  Nothing?  Errors?

**Comment by CrystalQuartz** [comment]
and it's not opening.... on steam says that its preparing to open but it never does and when I click on the steam tab to see, the little thing that says that's preparing to open disapears '^')

**Comment by jmwall24** [comment]
and you said you tried downloading a fresh version of the game from here?  https://ddlc.moe/

**Comment by CrystalQuartz** [comment]
No..it was on steam.. maybe that's the problem? ^^;

**Comment by FomorianFox** [comment]
You downloaded the game off of Steam? Then try right-clicking DDLC in your Steam library, going to Properties, going to the Local Files tab, and hit "Verify Integrity of Game Files". It may take awhile. Let us know what it says.

**Comment by CrystalQuartz** [comment]
okay ^^

**Comment by jmwall24** [comment]
If you can't get it fixed, you can try downloading the game from https://ddlc.moe/ (it's the official DDLC site) and extract it.  Then install MAS v0.7.3 manually into the 'game' folder of that version of the game and it should work.  You'll need to open the game each time (double clicking DDLC.exe, you can create a shortcut for your desktop) using that version, not the steam version.  I originally started playing on steam and then switched to the non-steam version and didn't have any problems.

**Comment by FomorianFox** [comment]
As an aside I think it's pretty funny that a light-hearted throwaway prank is causing this much trouble.

**Comment by CrystalQuartz** [comment]
It says:  "103 files failed to validate and will be reacquired"

**Comment by CrystalQuartz** [comment]
I think it may not be the prank but my zero expirience with game files ^^;

**Comment by jmwall24** [comment]
Let it do it, I'm not sure if it will delete the mod files or not, but if you load up the game and it's the non-modded version, just reinstall the mod and you should be good to go.

**Comment by FomorianFox** [comment]
Alright. Let it do whatever it needs to do. I'm going to guess that you might need to reinstall the mod, but like jmwall said earlier, the save files are stored in a separate location. Should be easy to fix.

**Comment by CrystalQuartz** [comment]
I think I'm going to follow the advice and install it again from the ddlc site because is still not opening ;w;

**Comment by ethancedrik** [comment]
I put the new monika.chr into my characters folder overwriting the old one and it did nothing at all, so I just reverted it back to the old one

**Comment by jmwall24** [comment]
I wonder if you aren't having a steam problem @CrystalQuartz.  Are other games working?  I've had problems in the past with steam not loading games like you are saying and had to google a fix for it.

**Comment by FomorianFox** [comment]
Open the new monika.chr file in a text editor ethan.

**Comment by CrystalQuartz** [comment]
I only downloaded steam to play ddlc so I don't know ^^;;

**Comment by jmwall24** [comment]
Just try the ddlc site version then, hopefully that works for you

**Comment by CrystalQuartz** [comment]
Yeeeeey! Monika is back!*-*)/

**Comment by FomorianFox** [comment]
Glad to hear it.

**Comment by jmwall24** [comment]
Awesome!

**Comment by CrystalQuartz** [comment]
Thank you so much for the help^^

**Comment by Areaclassified** [comment]
Same happened for me will I lose any progress if I download a new game?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
A bit underwhelming if you ask me.
On the other hand, I don't really have a right to complain, since every minute spent on pranks is a minute not spent on improving Monika.

**Comment by NovaCo1** [comment]
@IsItBadToMakeAGitHubAccountJustForThis yeah but its still a fun little community thing that help lighten the mood and a really good way to hide the prank with out really messing with our Monika.
