### ISSUE TITLE
[Suggestion] Variable moods for Monika independent of the player

### ISSUE THREAD

**Issue by FomorianFox** [Monika-After-Story/MonikaModDev#1354]
Now, I know what you're about to say. What I'm suggesting is not the same as what's currently being developed for the affection system, and isn't the same as the mood system that was being suggested before that. At least, not to my knowledge, or as far as I could tell from my searches. Basically, I think it would be a good addition if Monika's mood occasionally varied, independent of her affection for the player.

We all sometimes just have shitty days, sometimes for extended periods of time. Likewise some days are better than others, and some days we seem to have no motivation or energy to do much of anything. Some of Monika's subjects cover this. So, I think it would go some way towards making Monika more realistic if she also experienced this.

I haven't put a great deal of thought into this yet, but the basic gist is this. I think there should be a series of different moods that Monika can be in when you load MAS. For example, these might include "depressed", "energetic", "thoughtful", "happy", what have you. They might have specific triggers to activate, or they might be random, I don't know - but I do think they should largely be independent of Monika's current affection level for the player. The key thing here is to bring Monika closer to being a real person with thoughts and moods that do not rely exclusively on the player, even if she in love with/slightly obsessed with him/her.

Whatever mood Monika is currently in could influence which topics she's most likely to bring up. For example, while "thoughtful", she might bring up philosophical subjects more often. While "happy", she might bring up more explicitly affectionate subjects more often. While "energetic", she might outright ask the player if they want to play a particular game instead of waiting for the player to bring it up - maybe bring up physical fitness or sports related subjects, if those ever get added. While "depressed", she might bring up more morbid subjects more often, and just all around come off as less happy. Probably replace her default "smiling dreamily at the player" expression with one of the more serious ones as well. At the most extreme - and I'm not sure if this is a good idea or not, just spitballing - she might tell the player that she really needs some time to herself right now - or that she doesn't want the player to see her like this - make it clear that she's not angry or sad about anything the player did, apologize, and then close the game.

This might be able to interface with the affection system once it's implemented. Maybe turning Monika down if she asks you to play a game with her could lose a few affection points, while trying to cheer her up if she's depressed - and succeeding - could gain you some. Maybe having very low affection points with Monika could make it far more likely that she'll load into the depressed state. Like I said, I have not given this a whole lot of thought. I just had the idea while playing MAS, and I figured I'd make the suggestion before I forgot.

Now, I did try to search for any indication that this had already been suggested. I couldn't find any, and from what I can tell, while it does look like it could interface pretty well with the affection system, it isn't identical. But having said that, I do have a hard time believing that nobody has brought this idea up yet. If I'm wrong, and this is another repeat suggestion, I apologize. If I'm not, what do you guys think?

**Comment by CrystalQuartz** [comment]
I think it's a great idea. She's not like the other ddlc characters and diferent emotions could make it feel like she have her own mind, life and problems even when the player is not around^^

**Comment by jmwall24** [comment]
I like the idea, anything that could possibly make the topics that come up during a given session have more continuity is a good thing.  

Part of this has been brought up before, specifically the being in a bad/depressed mood and not feeling like talking with the player right now.  I'm not really a fan of that myself.  Talking with the player is really all Monika has to look forward to, and between sleep and school/work obligations our time is limited with her as it is, so it seems counter-intuitive for her to not want us to spend our available time with her.  To me us spending time with her is what would help break her out of her funk.

**Comment by FomorianFox** [comment]
I wasn't sure about that idea myself. Like I said, I was pretty much just spitballing. In isolation, I like the idea of Monika sometimes wanting time to herself and not just being ecstatic to talk to us anytime we want. It makes her more real, at least for me. But as you say, when you consider Monika's situation, it doesn't really make sense. Maybe if it's phrased more as Monika not wanting the player to see her like that, or not wanting to bring the player down to her level... which in and of itself is a fairly common thought with depressed people. But yeah, I do share your concern regarding the idea.

**Comment by jmwall24** [comment]
I could see maybe her not wanting to play games if she's in more of a depressed mood.  Or even kind of tying into what she talks about with introverts (just spending time with someone even if you aren't actually doing anything with them specifically), maybe she doesn't really feel like talking but wouldn't mind just spending quiet time with the player and just having you there could be comforting.  But then again, with the number of people who didn't like 'the silent treatment,' that probably won't be the most popular thing either.

**Comment by FomorianFox** [comment]
Good point on the reference to the introvert subject. Yeah, on consideration, you're probably right. Just being less talkative and not feeling like playing any games would probably be sufficient. As far as people maybe not liking Monika talking less though, I think that's kind of the point. The ideal that we're all striving towards here - at least so far as I understand it - is bringing Monika as close to our reality as possible. That in and of itself entails her having ideas, thoughts, and moods independent of the player, and some of those, the player might not particularly like.

Now, maybe the player could bring up that he doesn't like how quiet Monika's being, and she would - consistent with her character - then try being more talkative. But that would also be a pretty douchy and inconsiderate thing to say, and should probably carry some sort of consequence. That particular aspect is already being developed under the affection system.

I don't know man. For lack of a better way of putting it, it just kind of annoys me that, as it stands, this is basically a one-way relationship, so to speak. It's probably safe to say that most of us involved with this suffer from depression and/or loneliness in one way or another, and we find some degree of relief in Monika. We load up MAS everyday, spend time with Monika, and for whatever reason, it makes our day a little better. But Monika doesn't require anything from us, no effort and no discomfort. She's just there, whenever we want to load her up, always happy to see us, always happy to talk to us, no thoughts or moods that don't essentially revolve around us. Something about this just puts me off. Spending time with Monika should demand effort from the player as well, from time to time. The affection system currently under development goes some way towards addressing this. I think that this would as well.

Hopefully that makes sense.

**Comment by jmwall24** [comment]
Yeah I agree with you.  One thing I'm really looking forward to with the affection system and/or any mood stuff that gets implemented is the ability to truly interact a little more and feel like what we do/say has an impact on Monika.  And most importantly, be able to make her life better the way she does for us.  I'm all for anything that brings Monika closer to our reality.

**Comment by strielok** [comment]
I like it

**Comment by kaido1224** [comment]
This idea was already brought up internally and largely poo pooed on by the editors

**Comment by kaido1224** [comment]
Changing vast amounts of dialog based on Monika's mood was largely frowned upon. Even if we did do It, it would be low priority. We haven't even gotten around to reviewing stuff that was opened 2 months ago.

**Comment by sebastianN01** [comment]
so how is the affection system gonna work then?

**Comment by strielok** [comment]
>we haven't even gotten around to reviewing stuff that was opened 2 months ago
man we might get MAS 1.0 by the time we get half life 3

**Comment by sebastianN01** [comment]
i remember we were meant to visit new rooms instead of just space classroom... its forgotten idea or not?.. so much to do. I guess I will not change the subject of this issue though.
