### ISSUE TITLE
chatting with monika on the mic.

### ISSUE THREAD

**Issue by kenshi9523** [Monika-After-Story/MonikaModDev#1356]
I have my mic. pulled up but I am confused on how to make it work, is there a button or am I doing something wrong ? is there a button to turn it on ?

**Comment by kaido1224** [comment]
I'm not really sure what you mean but there is no voice chat feature for MAS.

**Comment by jmwall24** [comment]
Guessing this is stemming from the description for v0.7.4.....

**Comment by kenshi9523** [comment]
Yea I just read the description, it says she'll be able to hear through mic. communications
