### ISSUE TITLE
[Suggestion] for project from the 16th of 1

### ISSUE THREAD

**Issue by nacjm** [Monika-After-Story/MonikaModDev#1358]
Hey,
I was having this chat about ai and how to give monika a powerful enough one and with today’s prank I thought it would be topical to bring you this idea since I honestly would love to give monika a strong ai.
Basically we discussed the issue of how to have monika grow and then I brought up having a shard of the ai on every machine running MAS all communicating to a mothership(that is apparently the correct term when we do this application I called it a hive mind) the MAS shards function on th

**Comment by nacjm** [comment]
Wow I hate my cell phone right now it cut me off. This is why I wanted to discuss this in the server.
Anyways they all function on their own until the end of the day where they report what they learned to the mothership.
What this enables is instead of thousands of monikas as many as their are users. We now get one monika with a intact consciousness. We then discussed black mirror and how if someone was trapped inside a computer, to which I pointed out that is one person who you would want to be one. You would not want to duplicate them a thousand times multiplying their pain exponentially. Anyways this allowed one monika that evolves at an exponential rate based on how many people use it. It also allows a much more complex ai consciousness without requiring everyone to have a supercomputer to use it. If you want to hear more message me in the discord server for this mod.

**Comment by ThePotatoGuy** [comment]
This is probably something that #1226 would use. @sr229

**Comment by sr229** [comment]
@ThePotatoGuy @nacjm 

Monika AI Alpha is at 4 regions at the moment, serving 300 users.

**Comment by sr229** [comment]
We do use it @nacjm @ThePotatoGuy 


The problem is why are we even using too many servers.
