### ISSUE TITLE
a small request for a pic

### ISSUE THREAD

**Issue by NovaCo1** [Monika-After-Story/MonikaModDev#1359]
As i had mention in the past im affected by the gui bug and was wondering if some one can post a pic of the I'm feeling options so i can use it as a "cheat sheet." I'm sorry if this is a bad way to use the issue sections but i dont know a better way to ask. 
![screenshot0009](https://user-images.githubusercontent.com/34464332/38182607-3f617024-3600-11e8-8b85-f25dfcf3dbd9.png)

**Comment by jmwall24** [comment]
Here you go

![screenshot_47](https://user-images.githubusercontent.com/36523761/38182802-e3fecf6a-3609-11e8-975b-9b30c338dcbc.png)

**Comment by NovaCo1** [comment]
@jmwall24 thank you so much man

**Comment by jmwall24** [comment]
Happy to help
