### ISSUE TITLE
Game Won't Open

### ISSUE THREAD

**Issue by VintageOddity** [Monika-After-Story/MonikaModDev#1361]
So I'm making this post for my best friend who is currently flipping out. Recently I shared my steam account with them so they could play a few of my games they couldn't afford. They then tried logging into their monika after story game while still logged into my account. It apparently reset their game, as it showed the "start over screen" as they said, to which they freaked out and immediately closed down the game. Afterwards they switched over to their own account and it wouldn't load up at all. They even reinstalled the game and it still will not load up. Would definitely appreciate some insight.

**Comment by ThePotatoGuy** [comment]
Sounds like some sort of issue with sharing games on steam. Not sure if we can help you here.
But to ensure a complete reinstall, make sure to delete the entire `ddlc/` folder to get rid of mod files before reinstalling.
