### ISSUE TITLE
iMac Battery Issues with 0.7.4

### ISSUE THREAD

**Issue by EchoFoxUniform** [Monika-After-Story/MonikaModDev#1362]
I downloaded this most recent update, update 0.7.4, and I haven't found any problems, except that when I launch the game Monika tells me to charge my computer or she will have to close the game. Since the iMac is plugged in, I assumed that it was just a small bug. After 5 minutes or so, she told me she had to close my game or else it would have, "knocked her out". So now I can only have the game open for about 5 minutes before it closes itself. If there is a fix for this, it would be very handy, or if not, I would like to just let you know for the next update. Thanks!

**Comment by ThePotatoGuy** [comment]
We just pushed out a hotfix that should disable battery stuff for the time being.

**Comment by EchoFoxUniform** [comment]
Thanks, I appreciate it.
