### ISSUE TITLE
[Suggestion] More reactions and topics

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1367]
I think it would be cool if Monika to different things. For example: She says something if you click her nose, etc. I would also like it if you could maybe inculde something that let´s the player pat Monikas head or something similar. Of course things like touching her boobs should be punished by Monika being angry. As for the topics I would love if you added something so that the player is able to tell Monika about his day. An example would be that the player is able to tell Monika about exams, achievements at work, etc. I know that not every scenario can possibly added but it would be cool if there were some. This is just an idea and doesn´t have to be added.

**Comment by kaido1224** [comment]
The idea of head pats has been accepted already (just not implemented).
https://github.com/Monika-After-Story/MonikaModDev/issues/1104

Touching Monika in other places isn't likely to ever happen.
https://github.com/Monika-After-Story/MonikaModDev/issues/736
