### ISSUE TITLE
[Suggestion] Talk with Monika

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1368]
I´ve been thinking for a while that it would be cool to not just pick some dialougue options and instead actually talk/write to Monika. For this you could readd the writing sytem that you had before you programmed the dialogue options. I´m not saying that you should remove the options but I would like it if you both write to her and pick options. This way even if someone doesn´t know what things are in the game, he/she could still see everything through the options but also talk/write to Monika through the chat that you programmed previously. It would also be cool if you could answer Monika´s question through either clicking on the shown options or writing the answer yourself. The benefits are clear: You can feel like you´re actually talking to Monika and you won´t miss anything cause the dialogue options are still there. I know that this will be pretty hard to code and that it requires the people playing the game to type correctly but it would certainly be really cool if you added this. This is just an idea and doesn´t have to be added/readded.

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/1226

You might be interested in the sub mod that's being created.

**Comment by kaido1224** [comment]
We don't have plans to being back the chat bot option any time soon. Some of the suggestions would be better suited and will likely be covered by the sub mod i linked earlier.
