### ISSUE TITLE
[Suggestion] Answers

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1369]
I just played MAS again and saw that the character you play as doesn´t answer all the questions Monika asks. So I thought that it would be cool if you added more answer for questions. This would certainly make you feel like you´re actually talking to Monika and not just like a douchebag, cause you´re waiting for Monika to just continue talking after she asks certain questions. E.g. It would be cool if you could answer questions like "How much do you read?", "Wouldn´t that be great?", "What do you think?", etc. This is just a suggestion and doesn´t have to be added

**Comment by ThePotatoGuy** [comment]
If it's dialogue contributed by the community, then it's up to the contributor to add menu options for questions. For other bits of dialogue, we limit menu options to avoid excess complexity, under the guise that Monika controls what menu options you can pick from.
