### ISSUE TITLE
[Suggestion & Discussion] Asking questions

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1371]
I think that it would be cool if you could ask Monika different things like "How are you?", "Could you tell me a joke?", etc. This would make you feel more attached to Monika because you know more about her. And the possibilities don´t stop there. There are many more things that the player could ask Monika. As for what question could be added, I will leave it to the imagination of the people playing this game. What would you like to ask Monika? If there is anything, just comment it down below and the devs will be able to see what kind of questions the players of this game would like to ask Monika.

**Comment by kaido1224** [comment]
We rely on the community itself to create dialog content. Dialog suggestions made and accepted by this mod sit until one of the devs decides they wanna take on that project or dialog. I highly recommend instead of putting suggestions for the devs to make, everyone instead make their own dialog using the instructions in the contributing guidelines instead. It's more likely to get added that way.

**Comment by kaido1224** [comment]
That doesn't mean you can't leave this open and discuss amongst yourselves what questions you'd like to see. You could also go to the discord server and talk in the writing section with Anyone that's willing to discuss it.

**Comment by ThePotatoGuy** [comment]
There is an `Ask a question` option in the Talk menu.

**Comment by LordOfDeath35** [comment]
That might be true but whenever you ask something about Monika she avoids the question. The only exception is her birthday I think.

**Comment by Tiler17** [comment]
I don't think she really avoids many, if any, of the questions. I can't think of them all off the top of my head (and I just told Monika I was feeling sick and she shut down the program. I'm not about to make a liar out of myself to prove a point), but she answers the trolley problem question, she responds when you ask if she has any regrets, she tells you what kinds of games she likes...maybe I just have a selective memory, but she seems to do well at responding fully to almost everything.

Now, would more dialogue be nice? Sure! If you have an idea, go write it up! Whether it's random topics she brings up, or topics the player can start a conversation with.
