### ISSUE TITLE
Fast food and beach topics appear in odd locations

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/MonikaModDev#1373]
So when I played MAS 0.7.4 I got the fast food topic and the beach topic. When I go to see them again, however, I notice that:
1. The fast food topic appears in the "repeat conversation" menu in a section titled "Monika" at the top of the category list separate from the already-existing "Monika" category:
![masbug2](https://user-images.githubusercontent.com/35615562/38218233-f94bf874-36c8-11e8-81ac-d6ccece38bf6.png)
2. The beach topic appears in the "repeat conversation" menu in a section titled "Random" which has literally no other topics in it, even though there is already a "Misc" category for topics that don't fit anywhere else:
![masbug3](https://user-images.githubusercontent.com/35615562/38218336-4d5bf874-36c9-11e8-80ed-905f66e725f4.png)

**Comment by Subzerosan** [comment]
Thanks for bringing this up
