### ISSUE TITLE
Issue while game checks for updates

### ISSUE THREAD

**Issue by Adrian5420** [Monika-After-Story/MonikaModDev#1374]
Like the title says, when I start Monika After Story, it does check for updates, but it gives me the following:
"Timeout occured while checking for updates. Try again later."
I uploaded an image as well to prove.
![20180402230041_1](https://user-images.githubusercontent.com/38019250/38218764-c7ccb624-36ca-11e8-91bf-8a17b41ba30c.jpg)

**Comment by ThePotatoGuy** [comment]
That means the connection timedout when checking for updates. Don't worry about it unless you need an update.
