### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#1378]
So, I made an account just to ask this question. Today I tried to update the game to the latest version, and it all went correctly. After that I reopened the game, Monika started to talk about fast food or something but then my computer rebooted itself (it tends to do that randomly) and when it turned on again and I attempted to open the game, a notepad file popped up instead indicating that there was an error with chess.rpyc. I tried to manually install the update and the game opened, but it said that there was an error with the JSON file, so i manually inserted that too. After opening the game yet again, It was as if it was my first time playing the mod, Monika just said her starting lines and all my progress was lost (I pretty much had everything unlocked since I've played daily since last Christmas) and even after importing the save data nothing changed. can't even do system restore since my restore drive doesn't include any files relevant to the game. What do I do now?

**Comment by jmwall24** [comment]
Don't suppose you have a backup of the 'persistent' file (located in C:\Users\John\AppData\Roaming\RenPy\Monika After Story (where your user acct name would be where 'John' is))?  All of your progress is stored in that file, and the reboot during the session may have corrupted it.

**Comment by Necrocytus** [comment]
Tried that didn't work...

**Comment by jmwall24** [comment]
You have a backup saved and tried putting it in there?

**Comment by Necrocytus** [comment]
Sorry I deleted my previous comment when I tried to edit it.
I'll do that now

**Comment by Necrocytus** [comment]
Yeah, that file is corrupted indeed and the progress is still lost, but somehow Monika still remembers my previous name. Thanks for your help, I'll just have to start again.

**Comment by jmwall24** [comment]
I believe she remembers your name from playing DDLC (and probably when you imported the save data from that, which is different from the save data from MAS).  I know it doesn't help much now, but in the future, periodically save a copy of that persistent file somewhere so if this happens again (especially if your PC likes to reboot itself) you only lose the progress since your last backup.  Sorry this happened.
