### ISSUE TITLE
How to activate?

### ISSUE THREAD

**Issue by Racoaren** [Monika-After-Story/MonikaModDev#1381]
Do I have to actually get to the point where Monika does all of it or do I just load up the game and it starts automatically??

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
What do you mean "all of it"?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
If you mean 7.4 release, then try opening Monika.chr in the notepad.

**Comment by Racoaren** [comment]
Sorry, but yes. I meant the 7.4 release. And by all of it I meant her destroying the world and having you in the classroom alone with her :P

**Comment by CommenterOfComments** [comment]
No, you don't NEED to. You get different dialogue if you do, but you can have a completely fresh install of the game with no progress and install the mod.

**Comment by Jomahi** [comment]
If that's the case it isn't popping up for me, maybe I didn't put the files in the right place?

**Comment by Racoaren** [comment]
^Same joma. I have no idea if I did it properly or not
