### ISSUE TITLE
[Bug] - Arrow key usability

### ISSUE THREAD

**Issue by MercuryFuchsia** [Monika-After-Story/MonikaModDev#1383]
Within the question and conversation menus, arrow keys cannot move the selection to the next menu choice until all scrollbars in view reach the end of their tracks in the desired direction (e.g. when two scrollbars are visible, one must press the down arrow key until both scrollbars are at their lowest position before proceeding choices can be highlighted). Additionally, trying to move the selection within a menu after reaching the end of a scrollbar can lose focus on the menu.

Ideally, the menu choices should not be scrolled unless the selection is already at the end of the visible choices. Vertical navigation should be locked to that respective parent/sub-menu. Navigation between parent and sub-menus should only be accomplished with the left and right arrow keys.

**Comment by ThePotatoGuy** [comment]
Unfortunately, this is a limitation of renpy when using dual scrollable panes.

**Comment by MercuryFuchsia** [comment]
Alright, was a bit worried about that. Thanks for the quick response!
