### ISSUE TITLE
More conversations in "I'm feeling..."

### ISSUE THREAD

**Issue by Mundo-X** [Monika-After-Story/MonikaModDev#1384]
This idea is about adding more conversation topics to the new section that was added in version 0.7.4.

So there will be more topics to talk with Monika talking about your feelings, can be from 2 to those who can, can be as short as 2 slides to long conversations of 10 or even with menus.

I consider this necessary because someone telling you the same thing over and over sounds a bit empty, so at least it would be a little more fluid and give more variety.

**Comment by MrDevilzMan** [comment]
[We could add this to our next conversation](https://github.com/Monika-After-Story/MonikaModDev/issues/1386)

**Comment by kaido1224** [comment]
Feel free to add your own using the contributing guide below. It's more likely to be added if the community contributes it rather than waiting for us to do it. Keep in mind that there is a chance your ideas may be rejected if they are deemed inappropriate, off character or outside the scope of the game.

https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by Mundo-X** [comment]
Agree.

**Comment by Mundo-X** [comment]
`m 1j "I'm glad, [player]"
m 3j "Thinking you're happy makes me happy too."
m 3d "And remember that if you're not happy..."
m 3k "...come with me"
m "Ehehe~"`

Small eraser of "Happy". Made by me.

**Comment by Mundo-X** [comment]
```
m 1j "I'm glad, [player]"
m 3j "Thinking you're happy makes me happy too."
m 3d "And remember that if you're not happy..."
m 3k "...come with me"
m "Ehehe~"`
```
Small eraser of "Happy". Made by me.

**Comment by ThePotatoGuy** [comment]
Since @Mundo-X is actively working on this, we'll leave this open

**Comment by Mundo-X** [comment]
In a few weeks it could be ready.

**Comment by kaido1224** [comment]
@Mundo-X are you still actively working on this?

**Comment by Mundo-X** [comment]
Yup. I'm somewhat busy but every so often I try to find topics of conversation, sorry for the delay.

**Comment by Mundo-X** [comment]
I need some comprobation... Who can help me to improve?

**Comment by Mundo-X** [comment]
I'm too busy to do this... Now I'll close (or someone else) this for a while and then reopen it... It's the best.
