### ISSUE TITLE
[Suggestion] Real Time Sundown/Sun Up?

### ISSUE THREAD

**Issue by juliathegolden** [Monika-After-Story/MonikaModDev#1388]
As it stands right now, Sun down always occurs at 18:00 and (I assume) sunrise is always at 6:00. However, now that the days are getting longer again, it's a little depressing to me for daylight to go away so quickly. I was wondering if it'd be feasible to calculate sun up/sun down. I've already found some python packages that seems like it can do it, but I know we have issues with taking user location, so I'm hoping it's possible to run them off of time zones alone. 

https://pypi.python.org/pypi/astral/1.2
http://rhodesmill.org/pyephem/
https://michelanders.blogspot.ru/2010/12/calulating-sunrise-and-sunset-in-python.html

I'm reading through them myself, but it's just a smidgen over my head so I wanted to post and share at least!

**Comment by ThePotatoGuy** [comment]
Nice job linking external libs that could handle this. Doing your own research really helps us out.

A quick skim of your links says that it's somewhat likely we could put that in. Will need to go over them in more detail later and evalulate the location data issue.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we look into it]
