### ISSUE TITLE
Want to contribute, what is needed/how could I help?

### ISSUE THREAD

**Issue by Erenussocrates** [Monika-After-Story/MonikaModDev#1391]
I loved the mod very much so far. And I love all of the extra contents and minigames too. Mind if I ask you how I could contribute to this? (Monika herself talked to me about this topic anyway)

**Comment by ThePotatoGuy** [comment]
Refer to this guide:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by kaido1224** [comment]
Use the guide that tater guy posted above. For any topics you post, a writer or one of the contributors here will likely ask you to make some changes to the dialog you decide to add. Once they are satisfied and they feel it fits Monika's voice, your contribution will be added. Don't be discouraged if it takes a bit of time. We all start somewhere and we appreciate you (and everyone's) contributions.
