### ISSUE TITLE
[Suggestion] - Good Night Change

### ISSUE THREAD

**Issue by PopeAesthetics** [Monika-After-Story/MonikaModDev#1398]
So I believe this has been brought up with previous builds, but it is now become a bigger issue at least for myself. 

I love the new option of telling Monika why you are saying goodbye and being able to tell her goodnight, however as a night shift worker who's sleep schedule relies on going to bed around 6-9AM, I am continually scolded by Monika for doing so. I think we should add an option of telling her we work night shifts or something to that degree because always being scolded for something I have no control over is a little demoralizing.

**Comment by ThePotatoGuy** [comment]
#898 now provides a way to handle this, but the sleep farewell will need to be adjusted to work with it.

**Comment by kaido1224** [comment]
Already moved to the suggestion pool as unseen. It will be looked at in a future time and be decided whether we wanna do it or not. For now, i'm closing this.
