### ISSUE TITLE
Editing persistent file

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#1404]
So, almost a week ago I posted an issue where I commented on how some files relevant to the game got corrupted when my computer crashed and rebooted, including the persistent file, and I lost all my progress. Ever since I've been creating backups of the persistent file almost daily so that doesn't happen again. Today was my birthday so I noticed that after Monika greeted me, the persistent file got larger, so I figured that special occasions get saved there too.

My question is, can I edit the persistent file in order to recover data from all the past events (Christmas, Valentine's, White Day)? And if the answer is yes, how do I do it? Will the game notice a forced change?

Thanks in advance.

**Comment by ThePotatoGuy** [comment]
To edit the `persistent`, you need to run the development version of MAS and open the dev console. For past events, all you can really do is set that you've seen that event, but you'll need to know its label:
```python
> persistent._seen_ever["<label name>"] = True
```

The game won't notice forced changes.

### NOTE
This is all the instructions I'm willing to give you. If the other devs or the community want to assist you in manually setting data, thats on them to provide. Don't want to set a precedent that we're like on-demand tech support.

**Comment by Necrocytus** [comment]
Thanks! I understand that it's not your job to help out everyone, but your response is way more than enough for me,
