### ISSUE TITLE
Adding Feelings

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#1408]
So I've been reading through [this](https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md), and it makes enough sense, but the instructions seem to refer to adding topics, not feelings. Understandable enough, feelings are new. I had an idea for a new feeling I wanted to add as a first contribution, so I'm putting up a rough draft in a word processor right now while I hopefully get help here.

My plan was to just copy the format that juliathegolden used in their recent feeling-inadequate PR, but I also don't want to just make assumptions and do something stupid, so any help would be appreciated. I think I understand how Monika's poses work and the general formatting for the text, etc, because that seems like it should be the same as adding topics. My biggest concern is with the addEvent(stuffandwords) section. I can guess, but I like to be sure. I also won't complain if I end up getting more help than I need.

Cheers!

**Comment by juliathegolden** [comment]
To be honest, all I did was copy the formatting from another mood in the topic, so doing that is a okay!  I'll tell you what you need to change for yours, though. 

init 5 python:
    addEvent(Event(persistent._mas_mood_database,"mas_mood_inadequate",prompt="inadequate",category=[store.mas_moods.TYPE_BAD],unlocked=True),eventdb=store.mas_moods.mood_db) 

Where mine says "mas_mood_inadequate" is the label name, just like with topics. Your label can be anything, but start try to stick to the mas_mood_SOMETHING format. Prompt will be what appears on the button, so in my case again, "inadequate" was all that was needed. You might need more to make it fit the "I'm feeling ____" statement formula they've got going on. 

Finally, pay attention to the store.mas_moods.TYPE_BAD part. If it's a good emotion, just replace BAD with GOOD. If it's a Neutral Emotion, replace it with NEUTRAL.

**Comment by Tiler17** [comment]
Seems intuitive enough, I'll see what I can rustle up. Thanks a bunch!

**Comment by Tiler17** [comment]
Alright, figured it out with no further questions. Thanks again!
