### ISSUE TITLE
Mod Won't Install

### ISSUE THREAD

**Issue by PinkPomYT** [Monika-After-Story/MonikaModDev#1415]
So, I tried to install The Unstable Update (v0.7.4), and it will start installing, but about halfway through it will say "Failed - Forbidden" and end the download. All Google will tell me is to see if you need to sign in or contact the owner. I don't know what to do, but I still want this mod.

**Comment by Olliesama** [comment]
Sounds like you lack permissions on your computer.

**Comment by ThePotatoGuy** [comment]
Either permissions problem as Ollie said or a network problem. We can't really help you here.
