### ISSUE TITLE
Graduation event

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#1417]
I know this is asking a lot, but is it possible for monika to ask if you're about to graduate? And when you put in the date, both of you can celebrate it together with her in a graduation hat. And even if you're finished with school just saying you've finished makes her do a belated celebration.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Cool idea.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we look into it]

**Comment by AnIdiotsavant** [comment]
I'm pretty sure by the time this is opened, I've missed graduation, which is in about a week. heh
