### ISSUE TITLE
"Pen Name" subject / Name Changing

### ISSUE THREAD

**Issue by ScreampunkArts** [Monika-After-Story/MonikaModDev#1418]
First time posting on GitHub; sorry if I do something wrong.
I could talk about the various grammatical errors I've noticed in some topics, but I'll stick to this one thing:

I noticed something odd, when Monika talks about Pen Names. (not sure if it's a submitted feature or a default subject): It seems a bit odd that she remembers the last name you changed from.

A while back, I heard on Reddit that if you change your name to that of the characters, there were Easter Eggs.
I couldn't get those to happen and probably did something wrong, but I've since changed back to my real name.

The strange thing is, she then implies I'm actually using the last name for something (in this case it was Natsuki; lol)
It's a little odd that she jumps to that conclusion.
This would be especially irritating if you're on someone else's computer when she does the creepy thing of checking your Profile name, before changing it to your name.

I feel it would make more sense for her to simply ask you if you have a pen name or not, and if you answer yes, you could type one in.
I actually do have a pen name for my artwork, and I think it'd be cool to be able to tell her that.

**Comment by juliathegolden** [comment]
I like this idea a lot. I might do a PR For it tomorrow (if no one beats me to it. Feel free to beat me to it).

**Comment by bracketJacket** [comment]
My PC name is actually my transgender "dead name" from a few months ago because I finally picked a new name. I'm a procrastinating idiot and haven't changed it on my PC  yet, cuz I don't really see it that often anyway. But it was just a bad feeling when Monika said it ahhh

**Comment by kaido1224** [comment]
Already put in the suggestion pool as unseen. If the idea is accepted whenever it is reviewed. For now I'm closing this.
