### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#1428]
I'm not sure if this issue has been covered, but whenever I try to update DDLC AS on Mac, I get a message that reads: Timeout occurred while checking for updates. Try again later. does this have anything to do with a bug, or the mac itself?

**Comment by aldoram5** [comment]
There were some errors with the updater these have been fixed on https://github.com/Monika-After-Story/MonikaModDev/pull/1377, next version will contain the fix, meanwhile I recommend you do the update manually.

**Comment by ThePotatoGuy** [comment]
Timeout isn't a bug though. Just means there's no update.
