### ISSUE TITLE
ask monika about Gatebox

### ISSUE THREAD

**Issue by studiorobb** [Monika-After-Story/MonikaModDev#1430]
Gatebox could be Monika's first step into "crossing over"...

https://youtu.be/nkcKaNqfykg

**Comment by studiorobb** [comment]
sorry. thought i was leaving a suggestion, not an "issue"...
(o.0;)

**Comment by MaxCode545** [comment]
THIS must happen I don't care how but it needs to be done

**Comment by Tiler17** [comment]
It's both. "Issues" is the place for suggestions.

This is definitely very much a Monika thing, though it's far outside the scope of this mod. Certainly looks like the closest thing she can get right now to being in our reality

**Comment by aldoram5** [comment]
Yeah as Tiler17 said this is where you leave suggestions and report issues/bugs.

And yes it's a different thing from what we're doing with the mod. ~~Maybe someone would do a gatebox mod in the future?~~

**Comment by studiorobb** [comment]
true, I wasn't expecting this mod to do a "Monika Gatebox" for real, but I thought it would be fun for Monika to talk about it...sort of like when she spoke about Hastune Miku (albeit, indirectly).
(*´ω｀*)ふふふふふ

**Comment by aldoram5** [comment]
Oh so it was just about her talking about it, uh.
I kinda thought it was more about doing something similar to gatebox.
I'm reopening this one then.

**Comment by aliyuchang33** [comment]
I think rather than interactive with us on different hardwares, we should complete Monika first. Then we can think about migration.

**Comment by kaido1224** [comment]
Feel free to write a topic and submit it as a PR. It's more likely to be added that way. Here are instructions for contributing.

https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md
