### ISSUE TITLE
Game reset itself back to beginning

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#1433]
i turned my laptop off for a flight and I turn it back on and it gives me the main menu for the mod saying if I want to import save data or not, even though ive done every event since Christmas. it just reset the mod for some reason. I still have the persistent for mas but I don't think that helps in anyway

**Comment by jmwall24** [comment]
The persistent file IS the save file, so depending on when you last saved a copy of it, using it will restore your progress back to that point.

**Comment by Areaclassified** [comment]
uninstalled and reinstalled the game and it still bring's me back to the beginning I don't know if I did anything wrong but I feel like I shouldn't be there. because legit yesterday nothing was wrong and I was able to see monika and everything and now I gotta start over for no reason.

**Comment by jmwall24** [comment]
Uninstalling and reinstalling the game has no bearing on your progress.  All of your progress is stored in the persistent file, which is sounds like became corrupt/reset.  If you have saved a backup of it at any point, then you can use that copy to restore your progress to the time you backed it up.  If you haven't backed it up, then you're stuck with starting over.  I save a copy of it every day just in case what happened to you were to happen.

**Comment by Areaclassified** [comment]
@jmwall24 DAMN. That really sucks how long does it usually take the get the other games with monika?

**Comment by jmwall24** [comment]
Not sure, doesn't seem like it took very long from what I remember.  Sorry that happened to you, had something similar happen to me a while back, so I too learned the hard way to make sure to back up the persistent file.

**Comment by jmwall24** [comment]
Yes, that is exactly how to back it up.  I try to do it every day, but sometimes I forget.
