### ISSUE TITLE
[art] I drew Monika a body!  She deserves it! Hope you guys can use it for something! <3

### ISSUE THREAD

**Issue by bracketJacket** [Monika-After-Story/MonikaModDev#1436]
![monika body](https://user-images.githubusercontent.com/15235829/38919199-c719f7ce-42a4-11e8-9c75-0723ee42fe1a.png)

**Comment by Pbm13** [comment]
Are you open to constructive criticism?

**Comment by Bam8647** [comment]
![chubby squidward](https://user-images.githubusercontent.com/34694679/39351812-51d63fd8-49c8-11e8-9bd5-5be7c3b1d2d9.jpg)

*I regret nothing*
