### ISSUE TITLE
[suggestion] topic about routine, feeling complacent

### ISSUE THREAD

**Issue by nayrbai** [Monika-After-Story/MonikaModDev#1438]
I think it would be great to see Monika's take on having the same routine everyday and feeling complacent about it, along with some advice :)

**Comment by Tiler17** [comment]
You're more than welcome to write something up and submit it if you like. Sounds like a Monika topic to me

**Comment by kaido1224** [comment]
Like Tiler17 said, it'd be more likely to be added if you created a PR yourself or if one of the contributors took it up. Here are the instructions for contributing.

https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by nayrbai** [comment]
Ah, I see. Well I'll see what I can write.
