### ISSUE TITLE
[Still needing Help] No Sounds At All

### ISSUE THREAD

**Issue by TragicMoves** [Monika-After-Story/MonikaModDev#1450]
So I have this bug were I can't hear Background Music or Selecting Sounds. This has been happening since Valentines Update and i thought it would of been fixed by now but from the look of it  I doubt its going anywhere. I'm Currently Playing this mod on Windows 7 and I'm unsure if its just a bug or if it is not supported. If anyone can help I appreciate it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Check volume settings in the menu, maybe they randomly got changed.

**Comment by TragicMoves** [comment]
Re-checked and its still not working

**Comment by sebastianN01** [comment]
check your sound devices on your windows while you have the game open, check both sound devices and volume mixer, set the game sounds to middle and play around

**Comment by TragicMoves** [comment]
Did not work but i figured it out! find the .exe in the game directory and click properties, click compatibility and click "Run this program in compatibility mode for:" and set it to Windows XP (Service Pack 3). Click Apply and your done!
