### ISSUE TITLE
Different archives in different OS

### ISSUE THREAD

**Issue by aliyuchang33** [Monika-After-Story/MonikaModDev#1455]
I have download the mod and play it for serval months. When I switch to linux OS and run DDLC.sh, the old archive under windows OS disappear. I try to save the game with 'save' bottom under windows but that doesn't work. How can I continue the game under linux from windows archive? Thx.

**Comment by juliathegolden** [comment]
I'm sorry, I'm not sure I understand what you're saying entirely, but I'll try to help. 

It sounds like you're running Linux and Windows on the same computer. Are you trying to launch DDLC from the Windows partition? If you don't want to move your persistent data around, could you try running the DDLC.exe through wine? I did that for ages with few problems. 

If that's not an option, you'll have to back up your persistent data for Monika to remember you. This wouldn't be directly in the game folder, but in a different folder. Usually, it would be something like /users/YOUR-USER-NAME/Application Data/RenPy/Monika After Story/.  Your persistent data for Linux (the .SH) Should be in a hidden folder in your  home folder, so something like /home/YOUR-USER-NAME/.renpy/Monika After Story/

I'm sorry if this is not the information you need.

**Comment by aliyuchang33** [comment]
Thanks. I forgot windows programs always store data in user/document. Thank you for providing the data dir of the mod.
