### ISSUE TITLE
Sleep concern not auto activating?

### ISSUE THREAD

**Issue by moonstne** [Monika-After-Story/MonikaModDev#1462]
So when midnight rolls around, Monika has never expressed concern about the time. To activate it, I have to go into "Repeat conversation" then "advice..." and press the button "Sleep Concern". It was not in italics and when I pressed it i got the first message your supposed to see "Shiki, It's night time already. Shouldn't you be in bed?" (plus more)

I don't have Monika repeat topics, I am currently running unstable v0.41 2018.04.23.9

**Comment by ThePotatoGuy** [comment]
Sleep concern is triggered via a greeting or random, so you most likely won't see it if you have the game running and midnight happens. We're looking into ways to change this.

**Comment by moonstne** [comment]
gotcha
