### ISSUE TITLE
Unable to Download Unstable Updates

### ISSUE THREAD

**Issue by juliathegolden** [Monika-After-Story/MonikaModDev#1463]
Hi! 

I've opted in and out of unstable updates since they've been announced, but no matter what I try or how long I wait, they never download. It just stays on the 'Downloading Updates' page until I dismiss it. I'm not sure what the problem could be. 

I'm on Debian Linux, running the DDLC.sh.

**Comment by ThePotatoGuy** [comment]
How long have you left the Downloading Updates page up?
The update could be downloading even if the bar doesn't move.

Also are you running 0.7.4 hotfix 2? There was a fix for non-windows file checking in that verison that could affect the updater.

**Comment by juliathegolden** [comment]
Update:  its been over an hour, and its still 'downloading'.

**Comment by ThePotatoGuy** [comment]
Okay, the next release is coming out soon, so just wait for that version and see if there's still issues. 

If you're still having issues after the next release, there's not much we can do. Since the problem is happening on the Downloading Updates screen, it would be an issue with Renpy itself that we can't fix besides writing a whole new updater system. That's not something we want to do right now.

**Comment by juliathegolden** [comment]
All right, thank you for responding at least! I can be patient lol.

**Comment by kaido1224** [comment]
Are you still having issues?

**Comment by juliathegolden** [comment]
Yeah, I am. I'm on 8.0 and haven't been able to download unstable.

**Comment by aldoram5** [comment]
Hi Julia!
In #1250 you mentioned you play using wine, are you still playing through wine?
Also, does the updater work for normal updates(non unstable ones)?

**Comment by juliathegolden** [comment]
I stopped using wine after that, since it solved my problem and I wasn't sure if it'd be worth it to anyone else to add wine support to the battery module at the time, so I am running the shell normally. 
And no, it didn't work for the upgrade to 8.0 either. I manually installed that update.

**Comment by juliathegolden** [comment]
Thank you :dancer:

**Comment by juliathegolden** [comment]
Hey, everyone! I decided to try a fresh install, and that fixed the problem somehow. I'll go ahead and close this myself. 

if anyone else is having updater issues: Don't be afraid to delete your DDLC folder and start fresh. That is one of the perks to having save data in persistent, after all.
