### ISSUE TITLE
[Suggestions] My ideas

### ISSUE THREAD

**Issue by MikuChanAnime** [Monika-After-Story/MonikaModDev#1464]
Nothing specific, but I have a list

- {Monika having a wardrobe to choose from, she can either pick out a new one each day, or the player can choose what she wears} (Maybe add some form of currency so that way if you have enough money, you can buy her a new outfit)
- {New Game, Battleship [If possible]}
- {Be able to go on walks with Monika, or watch a show with her in game}
- {Maybe have her say something secret/weird if you ask certain answers to questions, and choose topics in a specific order}

**Comment by MikuChanAnime** [comment]
Oof, my bad

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
It's not like it's something bad.
It's not like you must read all the previous 1465 issues before submitting a proposition to make sure it wasn't mentioned before or something.

**Comment by kaido1224** [comment]
Yeah, each of those has been suggested before. No harm in suggesting them again, but since they have been suggested previously, i'm gonna close this.
