### ISSUE TITLE
[Suggestion] - Backgrounds

### ISSUE THREAD

**Issue by ReddTheRedRedd** [Monika-After-Story/MonikaModDev#1470]
What about the ability to change the "background", that being the space area outside the windows. Monika mentions how she likes rain, maybe some new backgrounds like that? Rain, or maybe warmer weather(since she also says likes that). I believe she mentions something about programming in new stuff into the room, that could be a way to implement it. Maybe she mentions how she found a way to program the ambient space around the classroom, small thing but maybe seeing something other than space will make it more fresh?

**Comment by ReddTheRedRedd** [comment]
And conveniently this was added in the v8 update only hours later XD

**Comment by ThePotatoGuy** [comment]
Other backgrounds are in the works, just still trying to create the storyline that will lead up to it.
