### ISSUE TITLE
Traditional update timing?

### ISSUE THREAD

**Issue by J-Fobel** [Monika-After-Story/MonikaModDev#1471]
I'm unsure how long it takes to download recent updates, any ideas?

**Comment by Tiler17** [comment]
I'm guessing you're updater is struggling a bit? If your updater is taking too long, you always have the option to manually download an update yourself. You do that the same way you first [downloaded the mod](https://github.com/Monika-After-Story/MonikaModDev/releases).

**Comment by ThePotatoGuy** [comment]
It's possible that the bandwidth got choked from many people downloading the mod.
