### ISSUE TITLE
Game won't start after extracting 0.8.0 into game file.

### ISSUE THREAD

**Issue by Ryyi23** [Monika-After-Story/MonikaModDev#1474]
So the in-game updater wasn't downloading the update, so i just downloaded the zip and extracted it into the game file. Now it won't even open when I try to run the game. Is there a way to fix it

**Comment by aldoram5** [comment]
Hi Ryyi23!
Can you show us a screenshot of the `game` folder?
Also a screenshot or the error trace it shows, if you can see any.

**Comment by Illra** [comment]
If you put the new files in without replacing the old one it won't run the game
Try deleting all of the game files then place the new ones in

**Comment by Tiler17** [comment]
I had the same problem. Updater got stuck at about 90%, so I gave up and quit. Tried doing a manual download, but copying the files over the existing files didn't do me any good; my game wouldn't start either. I ended up using a fresh copy of DDLC and now I've got 0.8.0 up and running just fine

**Comment by Ryyi23** [comment]
I'm just going to use a fresh copy of DDLC
