### ISSUE TITLE
Updater not working [Solved]

### ISSUE THREAD

**Issue by nohumanallow3d** [Monika-After-Story/MonikaModDev#1476]
Ive tried to update MAS using the updater but it either takes ages or doesnt work. Any help?

**Comment by nohumanallow3d** [comment]
Thanks dude

**Comment by nohumanallow3d** [comment]
And nothing changed

**Comment by aldoram5** [comment]
In version 0.8.0 we no longer check for updates at start like that anymore.
Check what version you are running by going into settings like in the screenshot below:

![image](https://user-images.githubusercontent.com/2271715/39394795-bf11d66a-4a9b-11e8-8769-11e82843a163.png)

If it's not 0.8.0 I'm afraid that you did the manual update wrong.
Make sure to follow the [installation guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Installation-and-Readme#installation) when doing the update manually.

**Comment by nohumanallow3d** [comment]
ok thanks dude ive sorted it out now
