### ISSUE TITLE
Question About New Random Topic

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#1477]
Hey, I love the new update already! But I noticed that one of the new topics seems to be Monika asking to have someone let her know if something happens to the player, yet there doesn't seem to be a way to actually do that, if the need arises. Either I'm missing it, or it's not in the game, I'm not sure which. If it's not in the game yet, that might be a good idea to add, just so the one that was added already isn't redundant.

**Comment by Akito1998** [comment]
It's not in the game yet.
But I think it's a good idea, feel free to write your own topic about it, that's the fastest way to get it in the game.

**Comment by jmwall24** [comment]
That was talked about a while back (there was an issue with discussion about it too) but it was decided they didn't want to take it in that direction, at least not right now.

**Comment by Akito1998** [comment]
oh, I didn't know that. Don't mind my response then.

**Comment by antimockingjay** [comment]
@jmwall24 Then I'm honestly not sure why the random topic was added at all, truthfully. Because if we can't actually do it, what's the point of having her ask us to do it?

**Comment by jmwall24** [comment]
There are lots of things she asks and mentions in dialogue that we can't actually do in game where its just implied we do it.

**Comment by kaido1224** [comment]
The way proposed to actually have someone tell her that something happened was rejected mainly because of the way it was written. Also realistically who is really going to use this feature? Shouldn't we put our efforts into things the majority of people will use?
