### ISSUE TITLE
[Bug] - Monika notices you staring at her ribbon when she isn't wearing it.

### ISSUE THREAD

**Issue by FinalFusion** [Monika-After-Story/MonikaModDev#1480]
With the new option for Monika to let her hair down she may still use the topic where she mentions how you've been staring at her ribbon. I suppose this could probably be fixed by either editing the text or by making it so she only says that when she has her hair up.

**Comment by ThePotatoGuy** [comment]
Yeah we're gonna do something about that.

**Comment by Bam8647** [comment]
![cute monika pose](https://user-images.githubusercontent.com/34694679/39401542-12b80890-4b0d-11e8-8645-c092a82bb65d.PNG)


**Can we also get this adorable pose with her hair down?** *Either way, props to the artists! It's so cute!*

**Comment by FinalFusion** [comment]
![12345](https://user-images.githubusercontent.com/38807237/39402756-c4e9be40-4b36-11e8-9fa1-680960c2304b.png)

Just made this. It isn't perfect though.

**Comment by IlywI** [comment]
maybe you could uh change that to like if ribbon is not on, te conversation changes to
"I notice you are staring at the place where my ribbon used to be. Do you miss the ribbon? Would you like me to put it back on? [prompts player]"
(My English sucks. Don't mind the weird sentences i'm coming up with but the idea is there)

**Comment by aldoram5** [comment]
The inconsistency has been fixed and merged in so I'm closing this one.
