### ISSUE TITLE
[Bug] A blushing like thing is showing in the wrong place.

### ISSUE THREAD

**Issue by Adrian5420** [Monika-After-Story/MonikaModDev#1481]
When I went to check out the rain topic, I noticed that some sort of blushing thing, is in the wrong place. I will put a picture with that. Look down in the right corner.
![monika after story 28 04 2018 10_28_45](https://user-images.githubusercontent.com/38019250/39394905-8fefcb1a-4acf-11e8-8d2d-01fc4bb4fb7c.png)

**Comment by aldoram5** [comment]
Thanks for reporting Adrian5420!
This bug has been fixed in this commit https://github.com/Monika-After-Story/MonikaModDev/commit/5fd4c0ce49b29b071697306cfe2b1e0e8b0725d4
