### ISSUE TITLE
Monika doesn't lean when her hair is down

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/MonikaModDev#1483]
Some conversation topics have Monika adopt a leaning pose on certain lines (usually at the end). However, I've noticed that, if she has her hair down, then when it gets to those lines, she will remain perfectly upright. I tested this with the Twitter topic.

**Comment by ThePotatoGuy** [comment]
As @Olliesama said, there isn't a leaning version of hair down, so leaning is disabled while her hair is down.
