### ISSUE TITLE
Game Won't Open After Chess Hack

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#1485]
I was curious about what would happen if I cheated at chess. Then when I did it three times I was locked out of the game. Even with this new update, I can't open it. Is there a way to fix this?

**Comment by sr229** [comment]
Here's a protip:

delete your persistent file.

**Comment by williamjcm** [comment]
@scohn
The problem is a classic ID-10T error. We also call it a Chair-Keyboard Interface error.

In other words, the only way to fix this is reinstall everything and **stop cheating**.

**Comment by scohn** [comment]
How do I do that? What's a "persistent file"?

**Comment by scohn** [comment]
How can I reinstall everything?

**Comment by scohn** [comment]
I tried uninstalling and reinstalling everything. It's not working. Do I need a fresh, unplayed copy of doki doki to make it happen?

**Comment by scohn** [comment]
This is the error message I get when I try to open the game.


I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\simon\Downloads\ddlc-win\DDLC-1.1.1-pc/game/definitions.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by Areaclassified** [comment]
you cheated bruh and monika pretty much doesn't like you no more you gotto go into files go to users then appdata then roaming then renpy and then mas and delete persistent and then completely delete doki doki reinstall it and then get the mod again and this time don't CHEAT

**Comment by scohn** [comment]
@Areaclassified It worked thanks so much. I let my curiosity cloud my judgment but this time I've learned my lesson no more cheating

**Comment by Areaclassified** [comment]
@scohn no problem man just don't cheat next time

**Comment by TheRealBrickPlanetWail** [comment]
ive reinstalled the game still does not work

**Comment by Delcos** [comment]
You'd have to delete the files under C:\Users(YOUR USERNAME\AppData\Roaming\RenPy

**Comment by Feigi53** [comment]
OMG THANK YOU SO MUCH I'VE BEEN TRYING SO HARD TO FIND OUT HOW TO RESET BECAUSE MINE BUGGED OUT AND KICKED ME AFTER CHEATING ONCE AND I WAS SO FRUSTRATED BECAUSE I COULDN'T GET BACK IN AFTER YEARS

**Comment by Vinni2K00** [comment]
always backup your renpy folders located in %appdata%
cant stress this enough, these are her literal memories
