### ISSUE TITLE
How to let Monika's hair down

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#1486]
I've searched every bit of dialogue (maybe i did miss some) and i can't seem to find the one that lets Monika let her hair down. Anyone can help me out?

**Comment by jmwall24** [comment]
I believe it's triggered by one of the random greetings.

**Comment by RyanHanter** [comment]
ok thx let me know if you find anything else

**Comment by jmwall24** [comment]
Just got it, yes it is a random greeting.  Just answer that yes, you do like it if you want to have the option in the future.

**Comment by ThePotatoGuy** [comment]
Yes, random greeting. Just wait it'll show up within 10 sessions.

**Comment by RyanHanter** [comment]
ok thx a lot!
