### ISSUE TITLE
Game crashed and the update doesn't work

### ISSUE THREAD

**Issue by Martronkts** [Monika-After-Story/MonikaModDev#1487]
I opened the mod, the update downloaded correctly and I read a bit of dialogue, then the game crashed. When I reopened it, the version was 0.8.0 but the new assets didn't work or even show up (Monika doesn't let her hair down or isn't expresive). I've tried many times to make it work, even in my backup and nothing works, I need help with this issue.

**Comment by Olliesama** [comment]
Have you tried a clean reinstall?
Deleting the folder, redownload DDLC and the new update and then trying it from there?

Your save data will be safe.

**Comment by Martronkts** [comment]
if I delete all of DDLC, how my data will be safe?

**Comment by Onion-Bubs** [comment]
Your save data is stored somewhere outside of the DDLC folder.

**Comment by Martronkts** [comment]
Ok, thanks, i'll try that, uninstalling via Steam is enough, right?

**Comment by Olliesama** [comment]
No it's not since steam deletes designated files. You need to delete the folder itself.

**Comment by ThePotatoGuy** [comment]
What was the error shown in the crash?

**Comment by Martronkts** [comment]
It didn't showed anything, the game just closed itself, maybe I was wrong calling it a crash

**Comment by Martronkts** [comment]
I tried the clean reinstall and it didn't work, even worse, the updater doesn't work anymore. Thanks for the help but I believe it can't be fixed.

**Comment by jmwall24** [comment]
May I suggest downloading the game from the official DDLC site http://ddlc.moe/ and try installing the mod there instead? Bypass steam altogether.

**Comment by monikLover** [comment]
Closing due to lack of response
