### ISSUE TITLE
Possible bug with rain topic?

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1488]
Just noticed when going thru the sounds of rain topic, when you get to the 'would you ever do that for me' and the next menu option screen, there is an image that appears just to the right of the text box.  Not sure if it's supposed to be there or not
![screenshot_21](https://user-images.githubusercontent.com/36523761/39398364-9914f3a4-4ada-11e8-9df6-5e7adb727bf2.jpg)

**Comment by ThePotatoGuy** [comment]
Yeah thats a sprite error. We've fixed it for the next update.
