### ISSUE TITLE
Game crashed after new update

### ISSUE THREAD

**Issue by Ronnie300Fan91** [Monika-After-Story/MonikaModDev#1492]
Installed the new update manually and now this happened. Tried it on a fresh install too, and now Monika doesn't remember me for some reason and text speed is slowed heavily despite me turning the slider to max. [traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/1958157/traceback.txt)

**Comment by monikLover** [comment]
Closing due to lack of response for over a week
