### ISSUE TITLE
Changing the Renderer reverts to Software Rendering

### ISSUE THREAD

**Issue by BoneofMalkav** [Monika-After-Story/MonikaModDev#1494]
Love the update. But one bug I found was that trying to change the renderer manually (Angel/Direct X or OpenGL) caused the game to use software rendering only, While still saying it's in Angle/Direct X (So far only tested in Windowed Mode).

**Comment by ThePotatoGuy** [comment]
Are you sure it's software mode? In software rendering mode, you should be **unable** to shrink/expand the window.

If you're getting the crappy lines on the screen in directx mode, then that means you don't have the graphics hardware to run it in directx.

**Comment by BoneofMalkav** [comment]
I have a GTX 960 with 12 gigs of DDR3 Ram and a Pentium i5 Quad Core, that's more then enough for this game. And yeah, no matter what renderer I choose, It won't allow me to change the size of the window. It's odd but the window size I can live with.
