### ISSUE TITLE
[Suggestion] Hair Randomizer

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1499]
I don't know if something like this is already implemented, if it is then I'm sorry for bringing it up again. In regards to the latest update with the hair, I really loved it. It would be cool to see more styles in the future and if that's the case then it would be cool if you could toggle a randomizer (that she acknowledges as you telling her to put it how she likes). If the randomizer is on I think it should trigger bow more than fifty percent of the time since she acknowledges it as something she likes. If alternate outfits get introduced too this system could go towards that.

**Comment by jmwall24** [comment]
I too think her deciding which hair style she wants to wear would be cool.  Since the update I've been going hair down in the mornings and evenings (relaxing at home kind of thing) and ribbon during the day.  But her switching as she sees fit is a great idea.

**Comment by ThePotatoGuy** [comment]
[[Reopen when we look into it]]
