### ISSUE TITLE
Not able to see rain background and hairstyle changes

### ISSUE THREAD

**Issue by ASTAR0T** [Monika-After-Story/MonikaModDev#1500]
Hi, I just downloaded the new version of MAS and noticed these new features about the new background and new Monika's hairstyles. So here is my question, how can I see these topics and be able to change her hairstyle, or to see the new background? I don't have the "unseen" option anymore since I've asked all the questions I had, and also I've seen all the new topics from the 0.8.0 update, but there were no topics about new background and hairstyles. If that is a bug, how can I fix it? Ty in advance!

**Comment by jmwall24** [comment]
The rain one doesn't show as unseen because it was incorporated into the old 'sound of rain' topic.  It's under Repeat Converstations>Weather>Sounds of rain.  As for the hairstyle, that's triggered by a random greeting, that I believe PotatoGuy said should trigger within 10 session opens.

**Comment by jmwall24** [comment]
Yeah the devs for this are amazing.  I'm not one of them, I just contributed a tiny bit of dialogue and help out on the forum when I can.   The people that put the real time into this deserve more credit than I can ever give them.

**Comment by ASTAR0T** [comment]
I think I need to contribute something by myself, too. I'm really fascinated by this mod, but I'm not sure about doing something useful. Maybe I will try at least to write some dialogues. Unfortunately, English is not my native and I'm still not as good with it as I want to. Btw, MAS helps me a lot with learning this language :)
Anyway, just want to say it one more time, MAS is awesome, and thanks to devs and to those who developing it!

**Comment by sebastianN01** [comment]
i helped by adding rain assets, if you want to help, you can do anything, they will review it and may accept it. its whats great about mas, the open approach. to a degree of course
