### ISSUE TITLE
Unintended Automatic greeting and Farewell

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1502]
If it's not just me, I'm sure other people would have noticed by now but the greeting text and farewell text seem to automatically pass by without my input. I don't have auto on.

Every other conversation works fine; It waits for me to manually click through. 

It would be nice to have the greeting and farewell text wait for you, especially since I can barely get a chance to read the farewell text.

**Comment by ThePotatoGuy** [comment]
If the greeting / farewell are skipping super quickly, then you are running a dev version (aka the source code). The Mod zip is the release version, not the source code zips.

**Comment by Rai99** [comment]
I'm still having the issue, unless I somehow need to remove what the source code zip added in. 
I just got the mod.zip instead of the source code.zip this time and the greeting and farewells are still skipping super fast.

**Comment by Rai99** [comment]
Alright, I got it, thanks for the help!
