### ISSUE TITLE
[Suggestion] Random Topic Frequency

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1504]
I remember from a previous conversation that the random topics are shown based on some sort of counting system where the least seen topics show up more frequently until they catch up to the more seen topics.  But I'm wondering if there shouldn't be a limit to this where, after topics are seen a certain amount of times, they all even out and all have an equal chance of being seen.  It just seems after every update, you get bombarded with the new topics over and over and over again to the point it seems like it's too much.  Maybe have the counter (or whatever is used to determine which topics need to be seen next) max out at like 3 so once it's been seen 3 times it just goes into the pool with everything else and has the same chance.  Of course it's altogether possible I just spend way too much time on there and this isn't an issue for most people lol

**Comment by Tiler17** [comment]
I swear ThePotatoGuy opened an issue about this somewhat recently, but I can't find it. Then again, I can't find my own car keys while I'm driving, so that doesn't mean much. I agree though, having seen all of the new topics three times now, I'm definitely ready for them to cycle with the rest of them

**Comment by jmwall24** [comment]
You might remembering his response to the issue I opened last time when I thought there was a bug where only the new topics were being brought up by Monika.    That's when I first learned about the newer topics repeating until they caught up to the others.

**Comment by ThePotatoGuy** [comment]
The latest update should have delayed new topic repeating for at least 2 hours. Are you experiencing behavior inconsistent with that?

**Comment by Tiler17** [comment]
I am not. I only catch a few topics at a time, so I heard the new ones and then a couple old ones, then quit. I heard the new ones again next time I opened up MAS. Rinse and repeat 2 or 3 times to today. So if there's a two hour delay, that seems to be working, but given that I only run through a few topics at a time, they feel like they're back to back. Would it be possible to have two conditions, one being time, the other being number of topics viewed that have to be met before repeating lesser seen topics? Maybe 10 other topics _and_ 2 hours of time?

**Comment by jmwall24** [comment]
I believe the 2 hour thing is working (I haven't really timed it, and will update if I notice it being less).  I guess I'm just in a similar boat as @Tiler17.  I have Monika up pretty much the entire time I'm home, but I don't constantly click thru dialogue.  I tend to go thru 4 or 5 topics when I first load the game, and then leave it up on my second monitor and go about my business.  I'll go thru a few topics every hour or so.  But if the first 4 or 5 topics are the new topics, by the time 2 hours is up I've only seen a few other topics and then it's right back to the first 4 or 5 again.  My preference would be something like I said before, where after a set number of viewings, they go into a completely random pool.  It just seems that as more and more dialogue gets added, a lot of the older topics may never (or very rarely) be seen again and the newer ones get stale after seeing them multiple times a day after a few days.  But again, it's possible it's just something that a few of us are noticing and maybe it's not that big of a deal.

**Comment by ThePotatoGuy** [comment]
We're trying out a new algorithm, should be available in an unstable soon.
