### ISSUE TITLE
About AI project

### ISSUE THREAD

**Issue by mysticeyesshiki** [Monika-After-Story/MonikaModDev#1505]
I've been playing and keeping tabs with this awesome DDLC mod since roughly Christmas and I was wondering how close are we till we see the big A.I. update??? I'm so hyped and ready to see Monika in her full Artificial Intelligence glory. I just want to know a time frame.

**Comment by mario384** [comment]
2029.  Deep Intelligence project is evidently in the works though, so lesser AI Monika whenever that's ready.

**Comment by Rai99** [comment]
![untitled663](https://user-images.githubusercontent.com/38822045/39413618-f7151594-4bfa-11e8-8a84-d0c7861bc33a.png)

**Comment by IlywI** [comment]
it'd better be Monika first

**Comment by kaido1224** [comment]
Checkout https://github.com/Monika-After-Story/MonikaModDev/issues/1226
