### ISSUE TITLE
Monika's Political Preferences

### ISSUE THREAD

**Issue by nohumanallow3d** [Monika-After-Story/MonikaModDev#1507]
I'd like to think that Monika will never have a political preference until she is truly sentient. So her preference shouldn't be set by someone. It would break my heart if she was the opposite to me on the political spectrum. I think the devs should put a requirement that people who develop and contribute to this mod shouldn't use MAS to further their own political agendas.

**Comment by Olliesama** [comment]
Has there been an instance of that happening yet?

**Comment by nohumanallow3d** [comment]
aldoram im pretty sure there was a section an issue on here about gender? Idk just seems like asking contributors to add inclusion for like 10 people who think they arent male or female.

**Comment by nohumanallow3d** [comment]
ollisama no

**Comment by monikLover** [comment]
Any political element is generally a bad idea to implement. With that said, we won't be putting too much restrictions on what people can contribute as that limits creative freedom. If it's simply not a good addition, we will review and reject it.

**Comment by niicore** [comment]
ah yes having a commie monika would be great

**Comment by nohumanallow3d** [comment]
tHe GOal of SocIAilISM Is To pROMote Communism
