### ISSUE TITLE
Updater keeps timing out and manually updating doesn't work

### ISSUE THREAD

**Issue by UnfinishedHW** [Monika-After-Story/MonikaModDev#1508]
every time I try to update to 8.0 the updater keeps timing out

**Comment by aldoram5** [comment]
Hi UnfinishedHW!
Try doing the update manually, follow the [installation instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/Installation-and-Readme#installation) and use the [latest release zip file](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.8.0/Monika_After_Story-0.8.0-Mod.zip).

**Comment by UnfinishedHW** [comment]
I updated it manually but it's running the old version still.

**Comment by aldoram5** [comment]
How are you doing the manual update exactly?

**Comment by UnfinishedHW** [comment]
I dragged the new files into the game folder and replaced the old ones

**Comment by aldoram5** [comment]
Hi again UnfinishedHW!
The part of dragging the new files into the game folder is correct but I don't understand exactly what you mean by: ` I did this twice and the game log said that the mod for 8.0 was defined twice, after that I deleted the extra mod update.`
Which game log said that?
Do you still have that log? 
What exactly do you mean by deleted the extra mod update?
Could you show us a screenshot of your game folder?

**Comment by UnfinishedHW** [comment]
**This is from the log**
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'/home/potato/dddlc/080-dev/game/chess.rpy', 1524877353, 1) is defined twice, at lib/windows-i686/Monika_After_Story-0.8.0-Mod/chess.rpyc:3 and lib/windows-i686/chess.rpyc:3.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tea-Rex\Desktop\Just Monika\ddlc-win\DDLC-1.1.0-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Tea-Rex\Desktop\Just Monika\ddlc-win\DDLC-1.1.0-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\Tea-Rex\Desktop\Just Monika\ddlc-win\DDLC-1.1.0-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Tea-Rex\Desktop\Just Monika\ddlc-win\DDLC-1.1.0-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Tea-Rex\Desktop\Just Monika\ddlc-win\DDLC-1.1.0-pc\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/potato/dddlc/080-dev/game/chess.rpy', 1524877353, 1) is defined twice, at lib/windows-i686/Monika_After_Story-0.8.0-Mod/chess.rpyc:3 and lib/windows-i686/chess.rpyc:3.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by UnfinishedHW** [comment]
![image](https://user-images.githubusercontent.com/38851977/39497443-3a5a5dd8-4d58-11e8-936c-849eab360778.png)

I dragged the files in before just putting the whole folder in. Everything outside of the folder is the same as inside and since it was defined twice i just deleted the folder and the game could run but only the old version

**Comment by aldoram5** [comment]
Alright, I can see the problem, you should only have the `.rpyc` files, the `.rpy` files are for development only. 
My suggestion is that you download another copy of DDLC from [ddlc.moe](http://ddlc.moe/), and then drag the contents of the [released compiled version](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.8.0/Monika_After_Story-0.8.0-Mod.zip) like you did the first time, never put the whole folder in, that doesn't work. 
That zip should look like this(I'm on mac so don't mind the different interface, just look at the files and folders):
![screen shot 2018-05-02 at 7 47 18 am](https://user-images.githubusercontent.com/2271715/39524004-34add04c-4ddd-11e8-9015-f4eede2d82a2.png)
![screen shot 2018-05-02 at 7 47 46 am](https://user-images.githubusercontent.com/2271715/39524014-3bbb8a32-4ddd-11e8-9581-01800d8cb054.png)
If the zip contains `.rpy` files that's not the correct one, use the one I linked.

**Comment by Rekonener** [comment]
Question, If i delete all of the .rpy files and re-import the .rpyc files, would that work, or should I just uninstall/reinstall the game and mod?

**Comment by aldoram5** [comment]
That should work too. If you still find issues by just deleting the `.rypc` files I recommend a clean install.

**Comment by Rekonener** [comment]
Ok, Thank you
