### ISSUE TITLE
Request For Some Fixes On Monika's Sprites

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#1509]
*Both Monika's default sprite as well as another have an abnormal grey shade on her neck compared to the other sprites that the artists must of forgot. This has been mentioned before in earlier versions but I just wanted to point out some that weren't fixed.*

![mas grey neck bug](https://user-images.githubusercontent.com/34694679/39418645-1b4833f8-4c21-11e8-864a-ea22ba085841.PNG)

![mas grey neck 2](https://user-images.githubusercontent.com/34694679/39418651-24564804-4c21-11e8-8a23-49851f99a71b.PNG)

*Can we perhaps work on blending the blush more in tone with her skin and possibly smooth out any abnormal features to help make her blush look more natural? With respect, it kind of looks like someone just smeared face paint on her haha..*
![mas blush](https://user-images.githubusercontent.com/34694679/39418655-2909f4f4-4c21-11e8-8cc5-21030cf9734e.PNG)

**Comment by aldoram5** [comment]
Hi Bam8647!
Thanks for pointing out that gray shadow, we're going to check that internally and decide if we remove that extra shadow.
As for the blushing we're already checking out some options so it looks better in both at day and night.

**Comment by aldoram5** [comment]
The fixes have been merged and will be added on the next version so I'm closing this one.
