### ISSUE TITLE
Monika remembers the reason why you had to close the game

### ISSUE THREAD

**Issue by Reclaimer1905** [Monika-After-Story/MonikaModDev#1510]
Just had an idea about something like a special greeting when you reopen MAS after saying Monika you were going to work, school or to sleep, whaddaya think?

**Comment by Bam8647** [comment]
I've also thought about this. I think in order for this to work they would have to find a way to connect farewells to greetings. Like if you say goodbye/going to work or class, the greeting should pick up on why you left and ask you about your day at work/class. I also wouldn't mind a cute "Love you" message before leaving, but that's just me haha. 👍

**Comment by aldoram5** [comment]
Hi Reclaimer1905!
An almost identical suggestion has already been posted https://github.com/Monika-After-Story/MonikaModDev/issues/1402
Please refer to that one in case you have a more elaborated suggestion.
Thanks for the suggestion though.
