### ISSUE TITLE
[Suggestion] Topics Excluded From Repeats

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1515]
When on random mode Monika repeats specific topics, however, I think there should be a list of topics that shouldn't be repeated. Questions where Monika collects information about the player (IE "Do you like mint ice cream") shouldn't show up more than once, since she now knows that information about the player. However, if there's a topic that has the possibility of changing over time then it could be asked more than once. Like, if you say you're trying to quit cigarettes that could cause the topic itself to become more rare so that she can ask again to see if you've quit.

**Comment by Tiler17** [comment]
Makes sense to me. I believe that Monika really and truly convinces herself that every week will be the week that I decide to start liking mint ice cream. Something like this would save her the repeated heartbreak

**Comment by jmwall24** [comment]
I like it too.  And if for some reason we do want to answer the questions differently in the future, you can always go and find it from the menu.
