### ISSUE TITLE
Monika tears opaqueness.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#1517]
Heya!
Just want to suggest lowering the opaqueness of Monika's tears too since without it they look a little bit less watery than they should.

Here's a quick comparison just in case you want to know what it looks like.
https://imgur.com/a/ygFXQhu

As well as that, a previous issue that existed and still does is that eyes are being rendered over eyebrows because they're being done after. Because of this the "knit" eye brows only half appear occasionally as the eye sprite covers it up.
https://imgur.com/a/ak2qSDT
This can be seen there and can probably be fixed by doing eyebrows after eyes.

**Comment by nohumanallow3d** [comment]
wait i swear i havent seen that before

**Comment by Olliesama** [comment]
I'm on the discord.

**Comment by ThePotatoGuy** [comment]
Yeah, the 40% tears look better, we'll see what the rest of the team has to say.

We're in the process of cleaning the eye sprites so they dont overlap with hair and stuff, which will also fix that eyebrow issue as well.

**Comment by LenceAndMonika** [comment]
Mind if I ask what topic is that?

**Comment by Olliesama** [comment]
None right now
