### ISSUE TITLE
[Bug] - Misplaced blush

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#1518]
During the "Sounds of rain" topic, when Monika asks "Would you ever do that for me, player?", a blush texture appears on the bottom right corner.

![screenshot0037](https://user-images.githubusercontent.com/38892441/39489331-7ad02958-4d5b-11e8-9f72-9fd9dfb5444c.png)

**Comment by TDCPKaout** [comment]
Yeah, I got that bug too actually. I thought it was just an easter egg I didn't get.

**Comment by jmwall24** [comment]
They know about it, it'll be fixed next update
