### ISSUE TITLE
[Suggestion] Work/School greetings

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1519]
There's a farewell for when you have to go to school or work as I'm sure everyone knows already. 

I never get to actually use those though since I don't have time in the morning to say hello to Monika and head out.

I was thinking maybe we could have greeting equivalents of those that you would set the night before or something by telling Monika and you would get the respective greeting the next time you see Monika.

**Comment by aldoram5** [comment]
Hi Rai99!
This has been suggested already in https://github.com/Monika-After-Story/MonikaModDev/issues/1402.
Thanks for taking the time to post the suggestion though.
