### ISSUE TITLE
Can't play the piano

### ISSUE THREAD

**Issue by Damuchi99** [Monika-After-Story/MonikaModDev#1521]
Hello, the problem is that I pressed the '{' on the Piano Minigame and it crashed, and now i can't play Piano anymore because I choose the Piano and the game crashes
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/1965776/traceback.txt)

**Comment by ThePotatoGuy** [comment]
Upload your `persistent` file here.

**Comment by kaido1224** [comment]
i thought that was a bug we've seen before and fixed?

**Comment by Damuchi99** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1968216/persistent.zip)
 here it is

**Comment by ThePotatoGuy** [comment]
We've identified a fix for the `{` issue. Your traceback error is different, but I assume it was a subsequent error.

The fix won't be out until 0.8.1, so you can fix your game by replacing your `zz_pianokeys.rpyc` with the one from this zip. (Please backup your existing `zz_pianokeys.rpyc` just in case.
[zz_pianokeys.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1973234/zz_pianokeys.zip)
