### ISSUE TITLE
Monika doesn't seem to understand time

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#1524]
Hello! I noticed something that isn't really a bug, so much as an issue with the detection of time. I just woke up, and it's 1:00 in the morning. My sleep schedule is messed up, I know. Anyways, I hopped on to MAS to say hello, and I said "good morning" at which point she said I was being silly because it's night time. Which makes sense!

But then I said "good evening" instead, to which she replied "Jay! It's early in the morning!"

Technically, yes, it could be considered morning, but most people wouldn't call 1:00 AM early morning, so much as carrying over from the previous night. Plus, she literally just said it's night time, not morning.

Just... monika pls. i just woke up i don't have it in me to do mind games.

**Comment by kaido1224** [comment]
No special greetings at 1 am in the morning. It can be either night or early morning depending on your viewpoint. It should probably be adjusted to be one or the other and leave it at that.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
