### ISSUE TITLE
Question about Monika's new expressions

### ISSUE THREAD

**Issue by NoahDaggler** [Monika-After-Story/MonikaModDev#1526]
Hello!
So, I just got the new update and was quite confused when I loaded the game up, nothing seemed to have changed besides a new song.

Then I looked in the folders of the game and saw Monika throwing some sassy peace signs, and this crazy eye look, plus the major blush. I know what triggers her blush, but what can I do to get her to do the peace signs and the new eyes? I'm too lazy to go through every topic to find this out for myself.

**Comment by MikuChanAnime** [comment]
I'm also confused

**Comment by Onion-Bubs** [comment]
And for that to happen, people would need to know how to include the new expressions in dialogue.

**Comment by Tiler17** [comment]
True enough. The cheat sheet needs to be updated for the new poses, etc

**Comment by jmwall24** [comment]
Yeah I'm guessing the new art is just ahead of whatever they have planned to do with it.  Something to look forward to :)

**Comment by IceclimbersGD** [comment]
All those poses look cool and all but I really don´t like when she blushes, I feel like it doesn´t fit.

**Comment by Onion-Bubs** [comment]
@IceclimbersGD I think they're sorting out a new blush effect.

**Comment by ThePotatoGuy** [comment]
Making a cheatsheet for 292+ new expressions isn't exactly easy. We do have part of our team assigned to updating it, but in the meantime, `sprite-chart.rpy` has a decent explanation of how the new sprite code system works.
