### ISSUE TITLE
[Suggestion]Good Afternoon Button

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1528]
I haven't seen anyone else suggest this but I'd also be really surprised if I was the first one to bring it up, but why isn't there a good afternoon option?

There are options for the morning and evening but no afternoon in Question->Misc. Those two options also aren't acknowledged by Monika as appropriate in the afternoon so there has to be one coming up.

Don't tell me I'm the only one to suggest this.

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/1090
