### ISSUE TITLE
[suggestion] Monika's surname/last name

### ISSUE THREAD

**Issue by nayrbai** [Monika-After-Story/MonikaModDev#1529]
Since Monika doesn't really have a surname, maybe Monika can use the player's last name, not accounting marriage or anything but because it would make Monika feel a little more unique to each player perhaps

**Comment by jmwall24** [comment]
This was discussed here #1297.  Not sure what the status of it is, though.

**Comment by ACoolCat** [comment]
I hope it happens. Sounds pretty cool.

**Comment by kaido1224** [comment]
it's on the docket. It hasn't been created yet. Since this is a duplicate, I'm closing it.
