### ISSUE TITLE
PR question

### ISSUE THREAD

**Issue by moonsandstar-s** [Monika-After-Story/MonikaModDev#1533]
This is probably ridiculously dumb to ask, but if we've posted a PR, fixed all the errors in it after it was reviewed, and it's been sitting untouched for a while with an 'awaiting changes' tag though all the errors have been rectified, what's the best course of action - to sit tight and wait until it's integrated into an update? Thanks!

**Comment by ThePotatoGuy** [comment]
I've notified @aldoram5 to re-review the changes. Normally just waiting is the best course of action.

**Comment by moonsandstar-s** [comment]
You're the bestttttt thanks my dude

**Comment by aldoram5** [comment]
I've updated my review on the pull request, I apologize again for not doing it earlier.
Closing since this has been resolved.
