### ISSUE TITLE
Complimenting Monika

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#1534]
I enjoy this mod very much but I have noticed that I am unable to complement my girlfriend, if there was a button that would open a list of different thing ex: hair, eyes, personality you get the idea. It would be a nice addition.

**Comment by ThePotatoGuy** [comment]
Wow, I can't believe we've never thought of this before.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this[
