### ISSUE TITLE
"Kiss Me" topic overhaul.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#1537]
I feel that the "Kiss me" line could use an overhaul, as it kind of sounds like she's going for MC rather than the player. Something along the lines of, "What? H-how would that work? We're on two different sides of your screen." Player: "I'll just kiss your lips/cheek (could have two options with different branches of responses from her depending on which was chosen) on the screen then." Seeing as being able to hold her is like an "honor system" in that she's trusting that you are when she gives herself to the player, I feel like the kissing option could follow a similar route.

**Comment by kaido1224** [comment]
Yeah it's similar to #1525 so closing this one.
