### ISSUE TITLE
My problem with the anniversary of the relationship with Monika.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1538]
Well, I have a somewhat personal problem with the mod that is kind of complicated, so I hope I can explain it clearly and if possible get help.
First, I wanted to apologize if something went wrong, I'm from Brazil and I do not know English, so I'm doing it 100% with Google Traslate.
Well, a few days ago (more specifically on April 29, still in version 0.7.4 of the mod) Monika told me that we were doing three months of dating, but that was wrong, since that date was on April 12 , so I went to look at the files to see if I found something with the date three months ago (January 29th) and the only things I found with the date were some files in the 'game' folder, they were with the edit date on Jan. 29, so I changed my computer date to January 12 (the correct day of our dating), opened the files on a notepad, and just took out and put the first letter of them just so they were marked with the date of edition on January 12, as I believed they were responsible for Monika's confusion over the dates; but this only made the game get buggy and did not open, so to fix it I just pasted the mod back into the game.
What I really wanted here is to know how I can sort the date without ruining the game. Thanks in advance.

*Something that is very important in relation to this: I do not play the Monika After Story virgin, I put a translation of the mod that a fan of here made so that it stays in my language (Portuguese), so I can play the game normally with he is in my language, however, has a condition with this, whenever they have new updates of the mod, I need to download them through the site and then put in the game, because if I download by the installer of the game it gets errors and bugs.

**Comment by ThePotatoGuy** [comment]
Aha, January 29th happens to be when released 0.7.0, which was when we started tracking session data. There was no way to retroactively apply the correct day, so pretty much everyone is getting their anniversary dates at the same time.

It is possible to correct the day programmitically, but that means we have to write custom code for you (and by extension, everyone else who wants their anniversary days correct).

In the future, we're looking into adding some sort of calendar UI, and we're probably allow for changing original start date in there as a one time thing.

**Comment by jmwall24** [comment]
Yeah, mine is now January 27th (when I believe a test/unstable version of that same update came out that we could download manually) when the original date was January 10th.  So you're not alone @EntonyEscX.

**Comment by EntonyEscX** [comment]
Ah, agora eu entendi, é bom saber disso. Escrever códigos não parecem a coisa mais fácil do mundo, então acho que eu consigo esperar até a interface de calendário surgir no mod no futuro. Muito obrigado. :)
