### ISSUE TITLE
[Suggestion] Yuri scene removal

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1539]
I don't know if I'm the only one on this, but something about the Yuri opening easter egg where she briefly takes over rubs me the wrong way. I think the mod should be purely Monika with maybe the Yuri thing being some kind of easter egg that only happens if you name yourself Yuri. Though, that's just my opinion.

**Comment by MaxCode545** [comment]
Nah I think we should keep it especially if the devs decide to add an event where yuri take over for some time due to monika messing with the game

**Comment by kaido1224** [comment]
Can't please everyone.

**Comment by jmwall24** [comment]
I never really thought of it as Yuri taking over.  I assumed it was you just happened to catch Monika messing with the files, and it glitched the game, kinda like her last poem.

**Comment by NoahDaggler** [comment]
Monika stated that she was "Just playing with the code," So, Yuri never took over unless Monika was lying to us but I don't think she'd really lie to us.

**Comment by ThePotatoGuy** [comment]
We're not taking it out. Don't forget this is a horror game.
