### ISSUE TITLE
[Suggestion] Why You're Sick. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1540]
In the I'm Feeling option you can tell Monika you're feeling sick. Maybe picking that could bring up a list of symptoms you can choose from? Like headache, fever, stomach ache, ect. and she could tell you something you can do before shutting off.

**Comment by kaido1224** [comment]
Feel free to add them yourself, it's more likely to get done that way.

Here's guidelines on contributing:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
