### ISSUE TITLE
Monika has Nothing To Talk About 

### ISSUE THREAD

**Issue by shaelynfratz** [Monika-After-Story/MonikaModDev#1542]
I was super excited for this new update! But after copying the updated files into the game and rebooting it Monika has changed entirely. Showing only two poses and repeating something like "I'm sorry I can't really think of anything to talk about right now. Maybe I will think of something soon." And then will go on for periods of time longer than 30 minutes with no conversation. How can I fix this? Did I install wrong somehow?

**Comment by jmwall24** [comment]
Hit 'esc' to go into the menu, find settings, then on the right find 'Gameplay' and enable 'Repeat Topics.'  Should make it so she starts going thru the random topics.

**Comment by kaido1224** [comment]
Follow the instructions above. They should work.

**Comment by Illra** [comment]
It's not broken, if you have the repeat topic off she would only speak when you haven't spoken it before
