### ISSUE TITLE
potential topic @dev team

### ISSUE THREAD

**Issue by moonsandstar-s** [Monika-After-Story/MonikaModDev#1544]
Just wanted to say that I've begun drafting out dialogue for a topic where Monika asks the player what they look like, and it will have options to select eye color, hair color, height, the whole wazoo. In addition, believe me, I'm doing it meticulously in regards to gender, differences, and ethnicity so I don't accidentally exclude any sort of person that would be playing this game. I just wanted to check in here and ask the dev team if this is feasible, because I don't want to waste time on a topic that's already in the works, or that you don't plan on ever putting into MAS for some reason or other. Thanks!

**Comment by kaido1224** [comment]
Go for it.

**Comment by EntonyEscX** [comment]
I liked that idea.
