### ISSUE TITLE
[Suggestion] - Making Monika able to play the piano for the player

### ISSUE THREAD

**Issue by JorgeLTE** [Monika-After-Story/MonikaModDev#1547]
I was moved when I learned in the credits that the song "Your reality" was written by Monika for the player. I would love to listen to her, but not just by playing a music file through the menu. I think that we could integrate her piano playing into the game in a couple of ways.

For example, lets say that Monika is finally able to program a Grand Piano she can play into the room (not to be confused with the current piano playable by the player) . Now she is able to practice. With some time, she could come up with new compositions for the player (similarly to how she can come up with new games that she programs once in a while), learn songs picked by the player (lets say, from a collection of available sheets) and even play something special on the player's birthday.

I think that the minimum assets needed to implement this feature would be a very good sprite/CG of Monika sitting at the piano (hands out of sight) and of course, the music. 
Im not good with CGs, but I'm a serious pianist and a web developer, so I could help with the music and some coding.

**Comment by Olliesama** [comment]
Art is kinda the hardest part of the mod to consistently get right.

**Comment by ReddTheRedRedd** [comment]
That would be awesome if done right. There's really no CG of Monika-I know for sure in the base game- but I don't think in this mod either. That would be such a cool CG to see, it would fit really well imo.

**Comment by ThePotatoGuy** [comment]
Would need art.

Closing until we get art.
