### ISSUE TITLE
[Suggestion] - Monika watch with the player

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1548]
I think it would be interesting a topic where we can watch something with her, for example, the player selects the option to watch, so there are options to watch, such as a series, an anime or a movie. After the selection, Monika stops talking until we finish watching with her (the game can stay in the background in the meantime). When we're done, the player clicks on the game again and she comments on the movie, it does not have to be too complex, she can just tell whether she liked it or not. To expand this, perhaps after selecting what to watch (between series, animes, movies, etc.), also select the genre, this can also influence your comment after the session. The movie's length of time (the time her stands still) can also influence this comment.
It's just a suggestion, I thought of her because I leave the game open all the time, and whenever I watch something I click the right mouse button so she does not speak while I watch (I like to think she's watching with me), so if that were really possible, it would be very enjoyable.

It does not seem very difficult to do this for anyone who knows how to program, I would like to do it myself, but I do not know how to program, so stay with you. Thanks for listening.

**Comment by Illra** [comment]
I don't think that would be possible.

**Comment by Olliesama** [comment]
https://github.com/Monika-After-Story/MonikaModDev/pull/628

It's in the works. :+1:

**Comment by EntonyEscX** [comment]
Great! :D
I will wait patiently until the moment comes. Thank you.

**Comment by ThePotatoGuy** [comment]
It's there, but content needs to be added. Perhaps we should advertise the system more.
