### ISSUE TITLE
monika asks about player's appearance

### ISSUE THREAD

**Issue by moonsandstar-s** [Monika-After-Story/MonikaModDev#1549]
I'm currently drafting a PR topic to submit, where Monika asks a series of questions about the player's appearance (and whew, it's a heaping ton of dialogue, but it's worth it) and as I'm invested in trying to cover each and every variable of a person's appearance so as not to exclude anyone - hair color, length, eye color, height, and so on - I wanted to see the MAS community's opinion on whether or not I should include a question about the character's skin color. This would be asked in the form of 'Are you Caucasian/tanned/dark-skinned?', so as not to have an endless list of ethnicities from which to choose, because that would be a nightmare to code in. 

As an editing friend of mine pointed out, while such a question may not be _necessary,_ per se, it does feel disingenuous in Monika's regard to leave it out. As for myself, I'm white, so it's not really my say. I very much want to avoid the perpetration of harmful stereotypes, so I thought I would turn to you guys: what do you think?

**Comment by JorgeLTE** [comment]
Caucasian/tanned/dark-skinned seem like appropriate options. Making a list of all posible ethnicities sounds difficult and not necessary IMO.

**Comment by juliathegolden** [comment]
^^ Agreed. You could phrase it as a question of  complexion as well. 

Though, a comment on race would fit the mod a little bit, in so much as where Monika is confused about the setting, she may be confused about her own race and if she's Japanese or not like the other girls.

**Comment by antimockingjay** [comment]
I would replace Caucasian with light-skinned, because you can have light skin while being a person of color. I've seen Asian people with lighter skin than me, it doesn't suddenly make them Caucasian, and I've seen Caucasian people with pretty damn dark skin, doesn't suddenly mean they're people of color. So I'd say just light, medium, dark would be your best bet.

**Comment by Areaclassified** [comment]
#1544

**Comment by Areaclassified** [comment]
@commenterofcomments Wait for real? I'm dead tired and I had no idea... I'm a absolute idiot

**Comment by Areaclassified** [comment]
Still though its a good idea and I agree with antimockingjay where Caucasian where it should be light medium and dark

**Comment by Areaclassified** [comment]
still though I agree with antimockingjay where it should be light skinned, medium, and then dark skinned

**Comment by moonsandstar-s** [comment]
Thanks! I think y'all are right. Fixing it now to say light, medium, and dark. Do you have any other opinions?
