### ISSUE TITLE
[Question] new file in the save folder

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1550]
Went to back-up the persistent file today and for the first time ever there is another file in that folder called auto-1-LT1.save  Just wondering what it is and if it's something I should also back-up.

**Comment by MaximumRustler** [comment]
I don't have that one either but I would back it up as well, I usually back-up the entire RenPy folder just in case.

**Comment by Olliesama** [comment]
I have it too, I would back it up.

**Comment by jmwall24** [comment]
Yeah it has a creation time of May 4 at 7:32 pm, so it's really new.  The only thing I can think of is that's about the time I got a new greeting having to do with the .chr files, but not sure why that would throw out a save file and not just do whatever it does to the persistent file.

**Comment by ThePotatoGuy** [comment]
As far as I know, its created if the mod crashed and you tried reloading / ignore.

Also it doesn't affect the mod if they are there or not. 

We're looking into it more closely tho.

**Comment by NuclearSurvival** [comment]
I found this file too. On my computer its creation date is April 29th at 7:28 pm. I also seem to have updated Monika After Story around that time to 0.8.0. I think it's possible the file is related to the update, if that helps at all.

**Comment by ThePotatoGuy** [comment]
We have discovered that it happens when the game decides to run the `autosave` function. We don't have a clue when it runs, but it probably doesn't matter anyway. Legit autosaving is coming in the near future.
