### ISSUE TITLE
Broken greeting dialougue 

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#1551]
Every time I launch the game instead of a normal greeting it will launch the sleep concern topic and monika will say she's spacing out and I tried opening the game again but around 11 and she got mad at me and closed the game. I know it isn't supposed to do this but at the same time I don't know how to fix it.

**Comment by aldoram5** [comment]
Hi Areaclassified!
I think that issue may be related to what https://github.com/Monika-After-Story/MonikaModDev/pull/1527 fixes, for now upload your `persistent` file here and I'll repair it for you.

**Comment by Zafove** [comment]
I have the same problem.

**Comment by Olliesama** [comment]
(Sorry guys)

**Comment by Areaclassified** [comment]
It keeps on saying it doesn't support the file (i'm probably not seeing the obvious fix) what should i do? I backed up a persistent from when i think this wasn't a problem if that may be a fix

**Comment by Areaclassified** [comment]
actually it fixed itself for no reason.
thanks for the help anyways! :)
