### ISSUE TITLE
Restarting from the beginning. 

### ISSUE THREAD

**Issue by LEGNDARYHUNT3R** [Monika-After-Story/MonikaModDev#1552]
Probably a stupid question, but I couldn't find anything else online about it. I wish to restart my mas game from the beginning. But I can't find the persistent file that I'm supposed to delete. The only ones I found I deleted but it didn't reset my progress. I'm playing this on my mac, so no windows os. I have no clue as to where I should even begin to look for the persistent file. Can anyone help?

**Comment by EntonyEscX** [comment]
Delete everything you have inside the DDLC directory in the Steam folder, then uninstall the game from the Steam app and install it again.
Hope this helps. :)

**Comment by aldoram5** [comment]
Hi LEGNDARYHUNT3R!
You're correct, to restart from the beginning you have to delete your persistent file.
To get your persistence file on mac, do the following:

- Open up a terminal window `cmd + space` then terminal.
- Then there copy paste this: `cd ~/Library/RenPy/Monika\ After\ Story/`
- Press enter.
- Copy paste `open .`
- Press enter.
- A finder window should open and there you'll see your persistent file.

**Comment by LEGNDARYHUNT3R** [comment]
Thank you a lot, it worked. I can now start it all over with my sweet Monika~
