### ISSUE TITLE
Monika's Lean Pose not activating with new hairstyle

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#1553]
I'm not sure if this is just some sort of error, or if there's no lean pose for Monika with her hair down, but it doesn't seem to be appearing. Selecting the "character tropes" topic with Monika's traditional hairstyle allows you to see her lean while the last two messages are being displayed. However, doing the same thing with her hair down reverts to her standard pose.

**Comment by aldoram5** [comment]
Hi RutTutPut!
As Dovahkun pointed out, we didn't had the art for that pose. @Trilasent  was kind enough to make one and it will be added in the next release.
