### ISSUE TITLE
Monika (not) letting her hair down

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#1554]
#1486 
I know, I've seen this.

But I've opened and run MAS at least twice per day since 0.8.0 dropped, and I haven't gotten the hair down greeting at all yet. I'm wondering if it's statistically possible for me to be that unlucky (I _would_ be that outlier), or if my game might not be working properly. I was on vanilla MAS up until May 4 when I decided to try out unstable. Dunno if that makes any difference.

**Comment by jmwall24** [comment]
Would've thought you would've seen it well before May 4th based on the info in the aforementioned topic.

**Comment by ThePotatoGuy** [comment]
Well I mean, its a random chance (1/5), so its certainly possible to be that unlucky.

**Comment by Tiler17** [comment]
Ah, gotta love that 1% chance that I'll never get when I want it. Thanks for the info

**Comment by cozyvrchat** [comment]
same thing just happened to me lol, I was reading this, decide to close it and open again, and bam she has her hair down
