### ISSUE TITLE
Dynamic Poem Suggestion

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#1556]
I was suggested to post it as an issue haha
The general idea is that Monika will take data that the player gives her and have a poem that'll dynamically be different depending on the data given.
Say for instance the player told her that they have never had a family, Monika could allude to her savior coming from a broken home but if they said they were happy with siblings the line would instead read that their kindness came from comfort.

**Comment by moonsandstar-s** [comment]
im a lil biased but i think this idea sounds A1

**Comment by Authrix** [comment]
I'm totally not biased, and have gone from "This is cool, but not feasable" to "This is totally possible to do really well" over the last five minutes.

So the poem would follow a sort of template structure, with specific words, phrases or lines being used in correspondence with certain choices the player has made (such as liking mint ice cream) as Olliesama already put forward.

That's fine, but that could make the poem read rather robotically when the lines end. Two options here to try and prevent that:
1) End each line with a vague ending word. Something non-specific that can be read from easily. I'd love to give a decent example but my brain is currently on hiatus. 
2) Custom build each line referring to the start and end of each other possible line before and after it.
2.5) Some combination of the above.

It's worth remembering that not every line of poetry will end with punctuation, so "just slap a full stop (period) on the end" won't actually help much. 

_"The bird flies beneath the sky
and scorns all it sees."_ 

is an example of a two-line poem. Starting the second line with "and" helps to keep it somewhat generic, meaning we could start it with something else if we wanted. At the end of the second line, we're free to move on to another topic or carry on talking about the bird - but overusing that will make it sound very forced. Easy to do, really.

Fortunately for us, Monika's poems in the main game have all (or mostly) been free verse, so we don't have to worry about metre, rhyme, or anything like that.

If I knew the first thing about coding, I'd totally get to helping with this.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
