### ISSUE TITLE
[Suggestion] Preserve song location across 'Your Reality' covers

### ISSUE THREAD

**Issue by juliathegolden** [Monika-After-Story/MonikaModDev#1560]
One interesting bit of polish in DDLC is that when switching 'Okay Everyone' variants, it preserves the place in the song with this little nifty piece of code:

    #If a special track is chosen, play it, otherwise swap over to the character's
    #special version of "Okay, Everyone!"
    if music:
        $ currentpos = get_pos() #The current point in the song
        if track:
            $ audio.t5b = "<from " + str(currentpos) + " loop 4.444>" + track #change music
        else:
            $ audio.t5b = "<from " + str(currentpos) + " loop 4.444>bgm/5_" + poem.author + ".ogg" #Play the special character Okay, Everyone! for the character
        stop music fadeout 2.0
        $ renpy.music.play(audio.t5b, channel="music_poem", fadein=2.0, tight=True)
    window hide

I'm not sure if it's possible (it may not be if the covers have different lengths) but I thought it'd be nice if we could use this when switching between different 'Your Reality' covers in the music menu.

**Comment by ThePotatoGuy** [comment]
Probably not possible, especially since the different versions have different tempos.
