### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by dryolopuppy** [Monika-After-Story/MonikaModDev#1564]
ive downloaded it but i dont know exactly where to put it or if i have to delete anything, pls help

**Comment by Olliesama** [comment]
Take the folder in the downloaded called "Monika After Story" and add it to the base directory for DDLC.

**Comment by dryolopuppy** [comment]
is that it?

**Comment by dryolopuppy** [comment]
where exactly is the base directory?
