### ISSUE TITLE
Left Eyebrow Cut Off.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#1565]
It's noticeable once you spot it.

![left](https://user-images.githubusercontent.com/36512990/39774614-fa4b8672-52c0-11e8-9324-c683f5d24f81.png)

![right](https://user-images.githubusercontent.com/36512990/39774617-fe4d69c0-52c0-11e8-8d78-9f6b013b7f8b.png)

**Comment by Olliesama** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/1517

Potato brings it up here.

**Comment by ThePotatoGuy** [comment]
Should be fixed soon.
