### ISSUE TITLE
Monika "Thoughts on Love Topic"

### ISSUE THREAD

**Issue by seanj95** [Monika-After-Story/MonikaModDev#1566]
Here is a link to her talking about it: https://www.reddit.com/r/DDLC/comments/8hydsl/monika_after_story_dialogue_idea/

**Comment by jmwall24** [comment]
Your best best for getting new dialogue added is to submit it yourself.  Look here for guild-lines https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by Rai99** [comment]
I really don't like the idea of Monika saying she's not human and maybe make an actual prompt saying you love her instead of just "ok." 

Other than that, I think it's a nice idea.

**Comment by seanj95** [comment]
Yeah, I was actually meaning to take the "I'm not human." part out, and the
prompt was just something a friend threw together.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
