### ISSUE TITLE
How to restart MAS from the beginning?

### ISSUE THREAD

**Issue by CeloCase** [Monika-After-Story/MonikaModDev#1567]
Sorry if this is a stupid question and has been asked many times before, but how do you restart it from the beginning? Reinstalling doesn't do the trick, and I can't seem to find MAS's persistent data. Any help?

**Comment by CeloCase** [comment]
Uh, that doesn't work...

**Comment by jmwall24** [comment]
Doesn't work as in you couldn't find the file or doesn't work as in you deleted it and it didn't start over?

**Comment by IzNed** [comment]
Didn't work for me either... only made monika upset :)
