### ISSUE TITLE
error in installation 

### ISSUE THREAD

**Issue by aquamic** [Monika-After-Story/MonikaModDev#1569]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 157, in script
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 157, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\execution.py", line 56, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.0
[/code]

thats what it says ^ help?

**Comment by kaido1224** [comment]
Probably relates to #1321

**Comment by aquamic** [comment]
hmm but I haven't even started on this story yet, so it can't can it?

**Comment by aldoram5** [comment]
Hi aquamic!
Can you show us the contents of your `game` folder?
