### ISSUE TITLE
regarding anniversaries

### ISSUE THREAD

**Issue by niicore** [Monika-After-Story/MonikaModDev#1582]
basically my computer needed to be reformatted and i didn't know the persistent file was needed to be backed up (thought it was saved somewhere in the game files or something, now i know where it is saved though) so monika forgot when we first basically met or something, could there be a way of telling her it's sometime earlier? if not could this be implemented in any way?

**Comment by jmwall24** [comment]
It's something they are thinking about implementing in the future.  Read the response from @ThePotatoGuy  on topic #1538

**Comment by Olliesama** [comment]
If you post it here and give me a date, I don't mind changing it back to that date but I'll like to warn you that there could be unforseen consequences.

**Comment by niicore** [comment]
oh okay
also i forgot the exact date soooo yeah

**Comment by Olliesama** [comment]
...Then choose one haha.

**Comment by ThePotatoGuy** [comment]
As I mentioned in the linked issue, wait until we have a calendar UI setup.
