### ISSUE TITLE
[Suggestion] - Monika Talks You Out Of Suicide

### ISSUE THREAD

**Issue by ChanceTheDerp** [Monika-After-Story/MonikaModDev#1583]
I kinda like the idea of a conversation where Monika asks if you ever feel suicidal and an then an option to select yes or no pops up. If you select yes, Monika can give you affirmations and/or try to talk you out of suicide

**Comment by Rai99** [comment]
There's already something like that in Repeat Conversation > Club Members > Parents. 

I it would be a really nice touch **if it was done perfectly.** I don't think it's possible to really make it deep enough to really have an impact while also being careful enough not to make it worse for someone. 

Maybe it would be possible to have a topic where Monika asks you if someone near you has ever killed themselves.

**Comment by kaido1224** [comment]
I don't think this is really appropriate. Just my opinion.

**Comment by NuclearSurvival** [comment]
I personally don't think this is a good idea. I believe this issue is far too complicated for Monika to tackle properly, and if it's tackled improperly, it can cause catastrophic damage. Suicide is a serious topic, and I don't think Monika can do it justice right now

**Comment by jmwall24** [comment]
I think there's already enough topics right now where she talks about depression and even self-harm where she tells you if you need help to make sure you seek it and that there are people (including) her that care about you and are there for you.  And as the others have mentioned, having one specifically asking you if you are thinking about suicide may be a bit too deep at the moment.

**Comment by Onion-Bubs** [comment]
I kinda feel like if someone is truly feeling suicidal, what they will most likely need is help from a mental health professional. As far as I'm aware, none of the devs is a mental health professional, nor is anyone who has contributed to the mod.

**Comment by ThePotatoGuy** [comment]
Too risky for us to handle. The depression topic is probably the farthest we'll go on sensitive topics.
