### ISSUE TITLE
[Suggestion] Configure Sunset Time

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#1585]
This may be a dumb idea, but I think it might be cool if we can configure, within reason, when the game shifts to bright or dark. It's just a bit before 6:30 for me, and looking out the window, it's still perfectly bright out. In the game, however, it's pitch black. I think it'd be really cool if we could adjust it to be more fitting, based on when it sets where we happen to be.

**Comment by jmwall24** [comment]
I've been hoping for this as well now that the days are getting longer.  Not sure if they have a way to check for sunrise/sunset times tho.

**Comment by MaximumRustler** [comment]
It was talked about in issue #1388. I also hope this will be implemented soon. Currently in my game sunrise is at 7:00 AM and sunset is at 6:00 PM I think, and outside sunrise is at about 5:00 AM and sunset at about 9:00 PM.
