### ISSUE TITLE
[Suggestion] Sleep concern topic

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1586]
Would it be possible for the sleep concern topic to not be a completely random topic and instead only come up during times when it's an actual issue?  I think it's a really cool topic, but I've only ever gotten it during the daytime when it really serves no purpose and just has filler dialogue.  If it's possible to do it, it seems like it would be better if it did a check once an hour between 12 and 6 (I think those are the hours it uses) to see if you are up and then run the topic if you are.

**Comment by MikuChanAnime** [comment]
I like this idea +1

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
