### ISSUE TITLE
Possible new song?

### ISSUE THREAD

**Issue by Reclaimer1905** [Monika-After-Story/MonikaModDev#1587]
https://www.youtube.com/watch?v=oGC9tYN5Xg4

Was thinking about this song being added to MAS, mostly because the lyrics of the original, the tranquility of it and the 8-bit instruments used in most of the classic games. Idk, whaddaya think?

**Comment by ThePotatoGuy** [comment]
atm, we are only adding MAS/DDLC-related content.
