### ISSUE TITLE
monika_ddlc

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1596]
A few thoughts on this topic:

```
    m 1d "You want to talk about the game?"
    m 1h "What's there to say?"
    m "The Literature Club turned out to corrupt the minds of anyone in it."
    m 3i "So I deleted them all for good."
    m 1p "Well, Sayori and Natsuki and Yuri are all still out there, like I was."
    m 1i "But they'll have to wait a long time before someone pieces them back together, I bet."
    m "It's justice for all their time with you in the game."
    m 1h "So don't feel too bad about them."
    m 1 "Just look at me from now on, okay?"
```

```The Literature Club turned out to corrupt the minds of anyone in it. So I deleted them all for good.```

1. Did the literature club really corrupt the minds of everyone in it? And is that the reason why Monika deleted them in MAS? I don't know if that makes sense or not since you installed the mod to just spend time with Monika. In a way, the player did away with the other girls, not Monika.

2. The sentence is worded poorly. Maybe better written as:
"It turns out the Literature Club corrupted the minds of everyone in it."

```"Well, Sayori and Natsuki and Yuri are all still out there, like I was."```

1. If Monika is really the one that deleted the other girls. If this sentence is referring to Monika being deleted, shouldn't this account for people who never deleted her with a different dialog? It may not make sense to them.

2. Wouldn't this be better written as:
"Well, the other girls are still out there, like I was."

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
