### ISSUE TITLE
Minor Sleep Concern issue

### ISSUE THREAD

**Issue by fsranks** [Monika-After-Story/MonikaModDev#1597]
When the Sleep Concern option becomes available, it creates its completely own "Advice" tab separate from anything else.

And should the topic be something that can be randomly selected? As neat as an idea the topic is, it seems a little bit awkward for it to be something that never happens unless the player initiates it.

**Comment by jmwall24** [comment]
The double advice topics has been fixed (for next release) and the second part is somewhat related to topic #1586.
