### ISSUE TITLE
[SUGGESTION] Read/Study mode

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1598]
Just turn on and Monika will be more silent (She might just read something herself too) and if you are studying she will show you some support

**Comment by kaido1224** [comment]
Not a bad idea.

**Comment by ReddTheRedRedd** [comment]
I like this idea as well, I've tried writing and working with the mod open, but seeing that dialogue prompt up is too much to resist clicking it.

**Comment by Rai99** [comment]
I kinda think disabling repeat topics is the same thing but I do like the idea of her having a reading sprite while idle.

**Comment by juliathegolden** [comment]
It could be like the holding event, where if you click the game she stops and asks you if you are ready to take a break. And if you're not, you can click no and she goes back to reading.  

I think it's super cute!

**Comment by Rai99** [comment]
Or just something for Monika to do while I have her in the background.

**Comment by ThePotatoGuy** [comment]
[Closing until we look intho this]
