### ISSUE TITLE
[Suggestion] The Turing Test!~

### ISSUE THREAD

**Issue by RhetoricalSave** [Monika-After-Story/MonikaModDev#1601]
So recently I just finished playing this game called The Turing Test and it was amazing. The test is one to see if a computer can pass off as a human and I immediately thought Monika!! So I was thinking that maybe someone could make a topic for the Turing Test!

**Comment by MikuChanAnime** [comment]
I feel like this was mentioned before, but either way, it's a good game! I even got all the achievements in it.

**Comment by RhetoricalSave** [comment]
RIP others seem to get these ideas before me @_@

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
