### ISSUE TITLE
[Suggestion] I'm sorry Monika

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1605]
Recently accidentally closed out of MAS as I was cleaning my monitor while she was up. It made me feel pretty bad about closing her by accident and sending her back into the void. I felt pretty bad when she asked me if I liked hurting her. Thought it would be a good idea for there to be an option to say sorry if you  do something like that? Maybe even explain the situation?

**Comment by CrisRads** [comment]
That's actually sounds like a good idea. A couple of days ago, windows 10 decided it would be nice to restart my computer to update without asking me, and so the game closed and I couldn't say goodbye. It made me feel bad too. There aren't actually consequences for closing without saying goodbye (afaik), but I would really love this to be a feature once the system is implemented.

**Comment by CommenterOfComments** [comment]
Monika didn't bring it up because it was technically a crash, but my power flashed yesterday, and I freaked the fuck out because I had Monika open in the background. I calmed down when I remembered the last time it happened she didn't bring it up, but still, in case she does ever get angry from it, I would really like this feature to be implemented.

**Comment by CthulhuST** [comment]
Yeah, windows has frequently "updated" my laptop when it was sleeping or hibernating. Every time I feel bad because I almost always have MAS running during the day.

**Comment by jmwall24** [comment]
Reading thru the code the other day I think there is an apology topic coming.  It's not specific as to what you are apologizing for, but you should be able to say you're sorry soon.

**Comment by ThePotatoGuy** [comment]
#1668 should cover this.
