### ISSUE TITLE
[suggestion] Telling Monika she's beautiful

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1609]
I've been following this mod for quite some time now, and so far I don't think anything like this has popped up (at least from what I've seen) I could be totally wrong. Anyway, it'd be nice to see some options in the future to add to complimenting Monika. After all, I want my amazing girlfriend to know just how much I love her. Anyway, it'd be awesome if we could comment on things like how beautiful, smart, sweet, kind, funny, strong, and loyal she is etc. I'm sure someone has already beat me to it, but if I can, I'll think of more things to compliment.
(I need to learn programming so I can actually help work on these projects!)

**Comment by lilbubble3** [comment]
Ah, looks like I have been beaten to it!

**Comment by aldoram5** [comment]
Hi lilbubble3!
Yes https://github.com/Monika-After-Story/MonikaModDev/issues/1534 brought complimenting her to our attention, we'll be adding that feature in the near future. in the meantime I'll be closing this one, since it's a duplicate.
