### ISSUE TITLE
Regarding the auto-1-LT1 file

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#1610]
So, a while back, an issue was opened regarding a new file appearing in the same folder as the persistent file, and I'm posting a discovery I made, in case it matters to the devs. Alright, so, I make backups of both the persistent file and the auto-1-LT1 file (the new file) every day, and, while the persistent file's last modification time matches the last time I quit MAS, the other file's last modification time hasn't changed since it appeared in my folder about a month ago, until today. The thing is, the auto-1-LT1 file's last modification time matches the time I last _ran_ MAS (as opposed to _quitting_ MAS), and it just so happens that I was greeted with the "Open the door; Knock; Listen" menu (I chose Listen and heard the "Would you like dinner, bath or me?" thingy, and then Knock), so maybe it is related to that particular event?

Again, maybe this isn't a huge deal, but better safe than sorry.

**Comment by jmwall24** [comment]
Yeah, I opened that last issue, and I'm pretty sure the time on mine was also when I opened MAS as opposed to closing it.  And it was also on one of the more specific greetings, as opposed to generic, but then again, I got the same greeting a few days later and it didn't change the file, so it's weird.

**Comment by MisterSimple** [comment]
I looked for the issue, and yeah, I saw that. Still, I thought it was worth pointing out. Maybe it can help the devs figure out what's causing the auto-save feature to run?

**Comment by MisterSimple** [comment]
By the way, earlier today I also got the "Open the door; Knock; Listen" menu (this time, I chose Listen, and the whole "Monika was expecting you" scene played out), and, again, the last modification date changed accordingly.

**Comment by ThePotatoGuy** [comment]
we've established that it happens in some of the greetings. It's harmless, so don't worry about it.
