### ISSUE TITLE
[Bug?] Home from work greeting

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1612]
Just loaded MAS for the first time since installing the new update, and immediately got the 'did you have a good day at work' greeting.  My last farewell (before installing the update) was just a plain ol' goodbye, and I haven't used the going to work farewell since Thursday, and have said goodbye or goodnight multiple times since then, so something may be going on there.

**Comment by jmwall24** [comment]
Have said goodbye multiple times since (been playing with the custom music feature and adding songs, works great btw!) and have just gotten generic greetings since.  So maybe it just had something to do with the update shutting the game down and not having the option to say goodbye at all because of that?

**Comment by jmwall24** [comment]
Oh and there's also a typo in the home from work greeting.  Can simply take out the word 'from' or take it out and substitute in 'at work'

![screenshot_9](https://user-images.githubusercontent.com/36523761/40284966-23588856-5c64-11e8-8ed2-991346ca2579.jpg)

**Comment by aldoram5** [comment]
Hi jmwall24!
It's indeed a bug, we've found why that happens and a it will be fixed soon.
Thanks for reporting!

**Comment by jmwall24** [comment]
I'm sure it's the same bug, but I just got the Monday morning greeting on Friday afternoon as well lol
