### ISSUE TITLE
Sunrise and sunset time sliders not precise enough

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/MonikaModDev#1613]
I was trying to adjust the custom sunset timer to set it to exactly 20:00, but I cannot set the slider so that the sunset time is 20:00. It always skips from 19:57 to 20:02 or 20:06, and when I try going the other way, it skips to 19:57 or 19:53.

Could you either:
a) Implement another way to set the sunrise and sunset times more precisely (text input for example)
b) Make the slider only ever change in 5-minute increments or something so the time always ends in a 5 or a 0

**Comment by lilbubble3** [comment]
Yes, I agree. The sliders could be much better. Honestly a text input is the way to go imo.
