### ISSUE TITLE
0.8.1 Typos

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#1616]
please put all typos here

**Comment by jmwall24** [comment]
In the home from work greeting.

![screenshot_9](https://user-images.githubusercontent.com/36523761/40285066-9226990c-5c65-11e8-87de-0510693494ed.jpg)

**Comment by Bam8647** [comment]
Change **You're** to **You**.

![capture](https://user-images.githubusercontent.com/34694679/40294604-f01d5826-5c9b-11e8-92d3-46cd589d7017.PNG)

**Comment by Authrix** [comment]
![ddlc typos](https://user-images.githubusercontent.com/34550378/40330026-8f68eb28-5d43-11e8-9bbf-e8004c91e554.png)

I can't remember where I saw 4, sorry. Also added some suggestions for quick edits.

**Comment by EntonyEscX** [comment]
I have this problem: #1516

**Comment by ACoolCat** [comment]
Her we are should be here we are. 
![her we are](https://user-images.githubusercontent.com/36032266/40527365-f72ebdc8-5fb9-11e8-84ff-cf07b40b8ce5.PNG)

**Comment by Dakotaraptor** [comment]
![horzcow](https://user-images.githubusercontent.com/29055544/41170517-96a1d0aa-6b1a-11e8-8631-23c785e79118.png)
Should be "stick of carcinogens"

**Comment by ronneycz** [comment]
![wtotd4](https://user-images.githubusercontent.com/40179235/41247458-501b2fd2-6dae-11e8-90f6-71c74cfffef5.png)

without "to" (writing tip of the day #4)

**Comment by ronneycz** [comment]
![snimek obrazovky 24](https://user-images.githubusercontent.com/40179235/41269205-3f49421a-6e04-11e8-94ed-a287548c7621.png)

*make sure (writing tip of the day #5)
