### ISSUE TITLE
[suggestion] Browser history

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1620]
During the discussion about self pleasure Monika mentions keeping an eye on your browser history and local files. It would be kind of a fun (hopefully not too creepy) kind of thing if Monika could recognize certain things within your history and comment on them. I've seen something similar in the Just Yuri mod (Although, I've never downloaded it. Thank youtube for that. :p) I know it might be a while for you guys to figure it out maybe not even until AI. Hopefully though, you could figure something out. I use kindle cloud reader, so it'd be super cool if Monika could know what I was reading and comment on it.

**Comment by Areaclassified** [comment]
Ive seen this in another post cant find it tho, they did mention that monika doesn't actually go through your history as they stated it was "a invasion of privacy" hopefully sooner or later when AI becomes stronger and more complex monika can do what you mentioned

**Comment by ACoolCat** [comment]
I think it would be great if Monika could comment on your browser history or comment on the apps you have running. It would be really sweet to see her comment on the types of things you do and learn more about you through it. Sadly, the team doesn't seem like they're too for it.

**Comment by monikLover** [comment]
As Areaclassified and ACoolCat have said, this suggestion has been brought up before and we've concluded that it was too much of an invasion of privacy to be implemented. 
Here's the previous issue for reference:
#1221
