### ISSUE TITLE
Stop closing things without reason

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1626]
Stop closing PRs and issues without even commenting why. This has bothered me for a while. Its common courtesy.

Example
https://github.com/Monika-After-Story/MonikaModDev/pull/1622

**Comment by ThePotatoGuy** [comment]
Looks like that pull request looks more like a joke than a serious contribution.

**Comment by kaido1224** [comment]
Comment looks like a joke cuz i couldnt think of anything to put. The content was legit though.. next time i just won't put a comment. Still doesn't excuse no comment on why it was closed.
