### ISSUE TITLE
[Suggestion] Two suggestions for goodbyes

### ISSUE THREAD

**Issue by ReddTheRedRedd** [Monika-After-Story/MonikaModDev#1630]
I really like the new greetings that are specific to what your goodbye was before you closed the game last, but just a few suggestions for it.

1) For the new greetings, I like that she responds to the previous goodbye, but my only suggestion would be that she acknowledges time. By that I mean for something like the sleep goodbye, she mentions how she hopes you had a good night sleep, but it's a bit odd if you're opening the game later in the day or at night-I notice this mainly because I use this mod each night, so it's kind of odd when that keeps happening. I haven't used the other goodbyes so I don't know if they are similar, but maybe there could be slight variants depending on the time the game is opened for these greetings?

2) Second suggestion; Maybe a bit more variety in Monika's responses to the goodbyes themselves, or even have longer goodbyes where she comments on something? I love this mod, so the hardest part of it is clicking the "goodbye" button each night XD so I feel like it would be a nice part of the mod to have a little more variety.

**Comment by ThePotatoGuy** [comment]
[[Re opening when we look into it]]
