### ISSUE TITLE
Help needed: 'Persistent' doesn`t work

### ISSUE THREAD

**Issue by Akh0r** [Monika-After-Story/MonikaModDev#1636]
While working on MAS translation I've found lots of interesting stuff in the code. 
-Katawa Shoujo reaction
-Time concern reactions 
-Battery reactions
All of this doesn't seem to work on my computer (and MAS version is currently 0.8.1) for unknown reason.
There is a 'Persistent' file in user\AppData\Roaming\RenPy\Monika After Story folder, and other RenPy games folders in RenPy folder. All of them do contain the 'Persistent' file - so what can be wrong?

**Comment by juliathegolden** [comment]
Battery reactions are disabled right now due to glitches.  I don't know why the other two are disabled, but I think they are disabled intentionally as well.

**Comment by jmwall24** [comment]
By time concern I assume you mean sleep concern?  That's still there, it just doesn't have it's own Advice category anymore, they fixed it so it's in the Advice category that has other topics in it.

**Comment by Akh0r** [comment]
I mean, the code shows that Monika reacts to the time Player is up. And there was even cases (I don't remember now what is the label of that dialogue) when Monika forcefully shuts down the game to make you go sleep. 
It is not a random monologue topic from the Talk/Ask or Talk/Repeat Conversation menu, it connects to the Persistent file only.

I am not a coder, so I can't clearly understand what code line doesn't work. Only thing I see is that all the aforementioned instances connected to the Persistent doesn't work for me (and I'm having MAS a'runnin' for 1.5 months already).

May the problem be caused by Cyrillic symbols in the root to the folder (I use Russian Win10)? The last time I've seen such a problem with OS on Russian was, like, 10-15 years ago, but who knows?:)
Is there any way to test DDLC ability to interact with its Persistent file?

**Comment by juliathegolden** [comment]
Simply put, if Monika remembers your name and what topics you've previously discussed, your persistent file is working properly. All progress is saved to it.  I can't say with a hundred percent certainty that it causes you no issues, but those topics aren't active to the general public, so you definitely aren't having an issue in not seeing them.

**Comment by Akh0r** [comment]
I was sitting over translating the final parts of the mod with MAS running on the background as a music player (Like I`ve been doing for a month now). And this very line of dialogue appeared (I mean, the first from a row of 'Time Concerns', where Monika mentions current time, not only showing '...I just kind of zoned out...').
Just... How? 
Well, the problem seems to be fixed... By itself...
Still, no reaction on Katawa Shoujo v1.3 Persistent, though. Maybe it is just random, and I should`ve waited for long enough:)

**Comment by ThePotatoGuy** [comment]
The Katawa shoujo topics use an older way of being added to the topic stream and will **not** appear in any version after 0.7.2 or 0.7.3 probably. 

I think we'll update this later.
