### ISSUE TITLE
[Suggestion] Different music settings for day time and night time

### ISSUE THREAD

**Issue by Icep0wder** [Monika-After-Story/MonikaModDev#1637]
I think this would help set the mood a bit more, since usually in the morning i'd prefer something more cheerful like maybe the 80's version for example or "Okay everyone!", while at night something calmer and more "initimate" like "My feelings" or "My confession", and i don't mean to sound "lazy", but having to make the switch myself everytime ruins it a bit. 

Maybe add 2 checkboxes on the music menu, one for day and one for the night, or make it so that when choosing the song normally it would be set for both, but if you click on it when holding 'd' or 'n' on the keyboard it would set the song to be played at day or night respectively

**Comment by ThePotatoGuy** [comment]
Would be a super low priority enhancement.

**Comment by ThePotatoGuy** [comment]
[[ Closing until we look into it]]
