### ISSUE TITLE
A new piano [Suggestion] [Very Low Priority]

### ISSUE THREAD

**Issue by multimokia** [Monika-After-Story/MonikaModDev#1638]
Figured I'd drop this here. I've been playing a bit of Monika's piano now and then, and I felt the sounds a tad lackluster, so I took it upon myself to get some new ones. These ones not only are sampled from a real piano, but also have a little more of a tail to them, it just makes it a little more satisfying to play if you ask me haha. Note: I've gotten these from the library "Piano in 162" Rendering out each one in my DAW. I've looked over the terms and sharing this does not violate any laws or their terms either.  Here's the new sounds:
[Monika's new piano.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2033376/Monika.s.new.piano.zip)

**Comment by ThePotatoGuy** [comment]
Thanks for taking the time to collect piano sounds.

Will take a listen later (aka a few days) and see if they're appropriate for replacing existing sounds.

**Comment by multimokia** [comment]
Sure thing, thanks for considering!

**Comment by multimokia** [comment]
Just a little update, .zip was originally a .rar . So, if you don't have something to open that, here's a google drive link for them instead 
https://drive.google.com/open?id=1vtWhBt2f7Ai22Beg_CFxF5rKUPR0oiDw

**Comment by ThePotatoGuy** [comment]
I like them.

I noticied in the discord that you're getting feedback about the sounds, so please let me know when you're at the final revision so I can put them in.

**Comment by multimokia** [comment]
Will do, final versions should be done today if it's only a volume boost!

**Comment by multimokia** [comment]
All right, the google drive link has been updated with louder versions of the sounds. All good to go!
