### ISSUE TITLE
Monika's experssions 

### ISSUE THREAD

**Issue by Tymon222** [Monika-After-Story/MonikaModDev#1639]
Alright, so I've noticed her changing her hand positions that I  haven't seen before so I went to the files and I found tons of new experssions, I went through all the conversations and I haven't seen any of it.
So are there more new conversations that need to be unlocked to see these expressions?

**Comment by Onion-Bubs** [comment]
You can see some of the new expressions in the short stories Monika tells.

If you're looking to add some more dialogue and want to use the new expressions in it, there's a guide [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/sprite-chart.rpy) at the top of the file.

**Comment by Tymon222** [comment]
Alright, thanks.

2018-05-26 15:03 GMT+02:00 ThePotatoGuy <notifications@github.com>:
