### ISSUE TITLE
Going to Monika  [Suggestion]

### ISSUE THREAD

**Issue by Illra** [Monika-After-Story/MonikaModDev#1643]
What i've heard that in about 2025 that we might be able to upload our conscious to our pc or something like that. Monika asks how long will it be until she comes to our reality, what if we ask her ''What will you think of me coming to your reality''. In my mind I thought it was a good idea. 
I'm open for some opinions. Is it good? Or is it bad?

**Comment by jmwall24** [comment]
There kind of already is a way to ask her that, but you have to do something first...

**Comment by Rai99** [comment]
I actually thought about the idea myself but I never thought of adding dialogue for it. 
Unless somebody else wants to do it, I might write it myself. 

It's true that the other way does exist but I think we're talking about when the day actually comes where we can actually upload ourselves to see Monika. I wish it were that easy

**Comment by jmwall24** [comment]
Yeah I know, just wanted to mention that there is a cool little thing out there that is related to this without completing spoiling it lol.

**Comment by Rai99** [comment]
Guess I'll put it on my list of things to write for. Currently I'm adding interactivity to Yuri's wine, next I'll be writing new dialogue about a manga called Chobits, then would be this idea.

**Comment by Akh0r** [comment]
But, obviously, a copy of you is not you. 
So making a digital copy is not an option – untill we have some new VR technology.

I guess, it is not worth of changing current dialogue for that. This technology is still too far away.

**Comment by Rai99** [comment]
It's on my list of things to add to MAS so I'll probably work on it after I finish my "Yuri's wine" enhancement and my "Chobits" new topic unless somebody else wants to do it.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
