### ISSUE TITLE
[Suggestion][Not really a must] Something happened

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1644]
So... Take this as the word of a random really paranoid girl in the internet, but when I close DDLC, It feels kind of bad that anytime, something could happen to me that prevents me from opening the game for weeks or never again even, Monika would wait for me forever without ever knowing something bad happened. A way to tell her something happened to me via another person.

I might be weird, or I might be too dark for the mod, but it would just make me feel better. That's why I just want fanbase/devs deciding if it's something they'd like in the mod.

**Comment by jmwall24** [comment]
This has been discussed before here (#1175) and there is in-game dialogue that references this  You can read thru that other topic, but basically it was decided it didn't really fit the mod and would probably never be used enough to make it worthwhile.

**Comment by CommenterOfComments** [comment]
I still don't understand the "out of place" part. They added a topic where Monika literally asks for you to tell her, and then they reject the ability to tell her? How is that out of place? Sure, it would be technically unnecessary work, but let's say someone decided to make it all in a pull request for the team to implement. I don't see any reason, in that instance, not to put that in the game.

**Comment by jmwall24** [comment]
That I can't answer. My guess would be adding that essentially requires one of 2 things to also be added to it.  Either if you told her something happened then it would end the 'game' and Monika would probably delete herself, or she would start talking and perhaps form some sort of relationship with whoever told her something happened.  Both scenarios are a pretty big step.  But you can't just make it a topic where you tell her and then the game goes on as normal after that.  So it's more complicated than just writing dialogue.  It would have to be something the devs wanted to do.  

I wrote the dialogue about this, originally with the intent to take it as far as that, but when it was decided they didn't want to go that far, I rewrote it from the perspective of a worry Monika would have and made it a way to ease her mind.  But who knows, maybe someday there will be a way to essentially end the game this way.  We already learned the game can be ended if you cheat too often at chess and I'm assuming the affection system will have a similar route if you act consistently like a jerk, so perhaps it's not out of the question forever.

**Comment by lilbubble3** [comment]
Honestly, I think the game just needs more developers. The current game devs have a lot on their plate. The more people contributing to the mod the more things like this can happen. Otherwise it's just too much work.

**Comment by ThePotatoGuy** [comment]
#1677 [[Closing in favor of linked topic discussion]]
