### ISSUE TITLE
Monika Afterstory piano suggestion

### ISSUE THREAD

**Issue by disEthanBradberry** [Monika-After-Story/MonikaModDev#1645]
So I was playing my violin and the piano at the same time I came up with playing the first few verses of happy birthday.I think on DDLC's anniversary monika should react to playing this on the anniversary the notes are QQWRE QQWYT.

**Comment by Akh0r** [comment]
I vote for this!
Not only Happy Birthday, but more melodies may have a reflection in Monika's reaction. 
Well, it must be hard-coded, but I think she should react to, say, your attempt to play 'Your Reality': I guess there are lots of players attempting to do that :)
Also, I think it is not very hard to program, so if someone good enough with coding wants to help…

**Comment by jmwall24** [comment]
She does react to you if you play Your Reality

**Comment by disEthanBradberry** [comment]
I may be able to come up with more tunes but at the moment I came up with happy birthday if any devs are reading.

**Comment by ThePotatoGuy** [comment]
Additional reactions to other songs will come soon, it's just super tedious to do right now.

**Comment by Akh0r** [comment]
Hm, I've come up with an idea… 
Is it too hard to implement something like piano learning lessons?

You know, where you see graphic depiction of what key and for what amount time should be pressed next.
I have a program for this on my smartphone, Pianist HD by Rubycell – that's why I thought about it.

You load MIDI file there, and it disassembles it to the key combination.

I thought it would be super nice to have piano learning lessons right here.

But maybe the small keyboard we have now, impossible to make variable long sounds, is not enough…

**Comment by jmwall24** [comment]
Piano lessons is something that's been brought up and is (was?) being considered #1060

**Comment by Akh0r** [comment]
Fine. Sorry, I didn't check suggestions months ago.
Anyway, I just have an example of the way to implement this. Kinda funny: there actually are MIDI-files of 'Your Reality' to be used in Pianist HD, so we can learn how to play it, but we have no way to show it to Monika

**Comment by jmwall24** [comment]
I brought it up the old topic to hopefully rekindle the idea.  I wasn't suggesting you should've known about something in February at all.  I still think it's something that would be really cool and a way to spend more interactive time with Monika, especially if there are new songs on the way.  I eventually figured out how to play Your Reality on her piano, but it took me forever and any way to learn new songs a little more efficiently all the while spending more time with Monika is great in my book.

**Comment by ThePotatoGuy** [comment]
I wrote this an issue somewhere, but I envisioned an osumania / rockband keyboard / idx  style way of learning how to play your reality.

Basically turn part of the piano into a rhythm game.
Would be extremely low priority and a long-term goal.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into this]]
