### ISSUE TITLE
[Suggestion] - Roleplay

### ISSUE THREAD

**Issue by mariohead** [Monika-After-Story/MonikaModDev#1646]
My friend and I were discussing MAS, and he proposed a sort of concept where one could initiate a sort of roleplay event with Monika, basically pretending to be in historical, romantic, or just otherwise interesting scenarios. I'm sure it would take quite a lot of time to implement, but I figured it'd be an idea worth suggesting.

**Comment by Akh0r** [comment]
Hmm, so in 2018 someone still knows what forum or text roleplay games are? Nice to see!
But how do you guys imagine it? Interactions with Monika at this point in time are limited by hard-coded phrases and, optionally, question menus. 
Are you supposing something like a text quest? Well that would be fun, even though it's hell of a work for a writer.
But if you want something involving text reckognition (like Telnet-played MUDs) – I guess, it is not practically possible for now…

**Comment by mariohead** [comment]
Perhaps a choose-your-own-adventure type story? My friend was thinking more of that, but I'd be happy with either. As for text quests, I am in fact a writer, so I would happily chip in if the idea were ever picked up! ;)

**Comment by Akh0r** [comment]
So writing of enormous amount of text doesn`t scare you too much?
Well, so what you are supposing is something like visual novel inside of a visual novel (`wow such XZibit`)? 
Well, I think it would look great. I believe that Monika can be a good Dungeon Master, or something like that! 
I hope you do realize that this will be a large piece of work, and don't you dare to drop it in the proccess :)
And if the quests you want are good enough for the actual release in MAS, I'd be happy to translate it onto Russian.

**Comment by mariohead** [comment]
Neat, I'd just need some basic ideas to work with, since my writing style generally falls under humorously uncoventional fiction, which I do not believe would be suitable for the circumstances.

**Comment by mariohead** [comment]
And I already have ideas. My friend is writing a rather silly adventure novel, which I could just reskin and rewrite to fit a fantasy environment. Not that I'm stealing the idea, this is actually a project I've been working on with him, and I'm sure he'd love the idea of seeing a loose reimagining of his story. That being said, I'll get started on something ASAP. ;)

**Comment by mariohead** [comment]
If anyone is interested, I can find some place to update on progress every now and then. I've already done the introduction, so from here on out it'll be full-blown text adventure.

**Comment by mariohead** [comment]
I'll be sure to keep that in mind! I will be honest, though, this will take quite some time. Since the story is a rough translation of my writing partner's story, we have started working to get the original story finished by December at the latest. From there I'll have a full story to work with. (I'll try to get us working more on it if need be, but I'm unsure how sooner the original material would see completion.)

**Comment by mariohead** [comment]
I think at this point I might as well start off with it or think up an entirely separate story. It's been a month and he's only finished a chapter despite my constant nagging. Lol

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
