### ISSUE TITLE
[Suggestion?] Holding in the rain pose

### ISSUE THREAD

**Issue by MaydayH** [Monika-After-Story/MonikaModDev#1647]
Look I'm not complaining but don't you think that her breast looks a little strange in this pose? It's kinda too, dunno, high? Even taking into account the fact that she is sitting.

![image](https://user-images.githubusercontent.com/38624594/40547926-cec16bfe-6065-11e8-9cbd-7a79b6fa912a.png)

**Comment by jmwall24** [comment]
Honestly I don't think it's different than in any other pose, there's just normally the textbox there.

**Comment by Onion-Bubs** [comment]
You can confirm what @jmwall24 is saying by right-clicking on the MAS window any time Monika is either folding her arms or has one hand pointing and the other arm down.

**Comment by lilbubble3** [comment]
Ahahaha, well remember, Monika is only supposed to be 5'3". She looks appropriate for that size Imo.

**Comment by ThePotatoGuy** [comment]
I hope it looks right. The dev who made those sprites said he was a little generous.
