### ISSUE TITLE
Horror stories

### ISSUE THREAD

**Issue by BigPoofyRibbon** [Monika-After-Story/MonikaModDev#1648]
Hi, if Monika can tell for us stories, what about horror stories at night time? What you think about that?

**Comment by ThePotatoGuy** [comment]
I think we even have the ambience for that, so it's for sure planned.

Biggest problem is that there will be people who will want to exclude those stories, but I think that's a non issue. This is a horror game after all.

**Comment by MaydayH** [comment]
Suddenly creepy music like "Surprise" may begin to play

**Comment by Tsadokiel** [comment]
I like that idea a lot. Maybe we could also add some of the disturbing sprites present in the main game as well for the scariest part? I'm not good at drawing but maybe we could add a creepier expression of her face too?

**Comment by kaido1224** [comment]
Edgar Allan Poe stories are open source from what i can see.

**Comment by ThePotatoGuy** [comment]
[[Closing until we reopen this @aldoram5 ]]
