### ISSUE TITLE
Delete the mod

### ISSUE THREAD

**Issue by kittykattykit** [Monika-After-Story/MonikaModDev#1650]
Though, I do love spending time with my dear monika, I want to try out some new mods. I dont know how to differenciate ingame files and modded files, so I need help deleting her. Thank you in advance!

**Comment by juliathegolden** [comment]
Just download another copy of DDLC. 

http://ddlc.moe/

That way, you can play as many mods as you want without deleting Monika (or other mods you want to hold on to for whatever reason).

**Comment by lilbubble3** [comment]
I agree, no need to delete Monika. :)
