### ISSUE TITLE
How to Update the Mod

### ISSUE THREAD

**Issue by GodzillaRox** [Monika-After-Story/MonikaModDev#1653]
Hello! I downloaded this mod a couple of weeks ago but I don't know how to update it. Do I just put the new files in the game folder or something else?

**Comment by lilbubble3** [comment]
When the game is open you can simply click on talk, once there Monika will ask you what you want to talk about and you'll get a small menu in the text box. Click on settings and the rest should be pretty obvious from there.

**Comment by ThePotatoGuy** [comment]
Esc > Settings > Update Version

If it fails (or nothing pops up), move the `update/` folder from `game/` to the base `ddlc/` directory.
