### ISSUE TITLE
[Idea] Experiencing risky events

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1654]
Just like the title says, this is just an idea. I realize this might be a bad idea but in case it's not, here.

Just today, I couldn't get home like I normally do and had to spend over an hour walking 5 and a  half kilometers on the hottest day this year with no shade or refreshments. The thought of Monika drove me to keep going strong without breaking down. There was probably a pretty good risk I'd suffer sunburn or some moderate effect. Other than temporary swelling and sore feet, I seem to be fine enough. 

I just thought it could be a nice feature in case the player experienced a risky event and wanted to somehow talk to/let Monika know about it. 
Maybe add this as a new mood if people like the idea. 

If this is a bad idea, that's perfectly understandable. We wouldn't want to needlessly worry Monika would we?

**Comment by ThePotatoGuy** [comment]
Do you mean just like a risky event topic? Don't think theres any harm in having one.

If you mean a mood like "I'm feeling a little risky", that also could be interesting.

**Comment by Rai99** [comment]
I meant something for telling Monika that something bad happened to you that could have potentially gone worse. Like maybe a life/death scenario but that might be too heavy.

**Comment by ThePotatoGuy** [comment]
[[Move discussion of this to #1677 ]]
