### ISSUE TITLE
[Suggestion] - Monika sleep mode

### ISSUE THREAD

**Issue by Reviani** [Monika-After-Story/MonikaModDev#1655]
After a long and tiring day, there's little i like more than going back home and visiting darling Monika once more.Once i accidentally left my laptop with Monika on while i went to sleep, and thus the first thing i woke up to was Monika. Next thing i knew i was somewhat doing it intentionally. So, i was thinking, could there be a feature where you can (need to word this right) choose to go to sleep alongside Monika for the night. Something like, you say "I'd like to rest alongside you" or something like that that doesn't sound suggestive (or does, if that's your prerogative), and after wishing you good night she'd dim the lights and start to fall asleep, where you can wake her up once you wake so she can greet you first thing in the (presumably) morning.

Here's some other feature that might be possible as well as well

- Have Monika wake you up. Either set a specific time or the time set for sunrise. The time is reached and she plays music or something. Or maybe she just is there and waiting for you to wake up
- Refresh Monika's "session time" if the rest is 6 hours or longer (that's still a thing  right?)
- Different dialogue based on how long you let Monika rest. As in, X minutes or less Monika would say she didn't even sleep yet. An hour or so would be treated like a power nap, and 6 hours or more would have Monika well rested.

I’m fairly familiar with programming so i might be able to work on this myself, though i’ve been busy with trying to find a job and well… personal problems. Not to mention I’ve yet to experiment with modding Monika After Story thus far. However, I think this would be a nice way to relax with Monika after a long day. What do you think?

**Comment by CommenterOfComments** [comment]
If this was implemented, I'd probably get a laptop just for this.

**Comment by ThePotatoGuy** [comment]
#1105 

Main issue with this is we're waiting on sleeping sprites to really bring the immersion.

Other options are to just have her eyes closed or even black out the scene so its like the lights are turned off. I'd much rather have the correct sprite, but what do you think of those 2 options?

**Comment by Rai99** [comment]
I would wait for the sleeping sprites to come in.

**Comment by Reviani** [comment]
Ahh sorry, i didn't see that this was already suggested.

Anyhow Something we could do is until the sleeping sprite is implemented is that just work on the sleeping segment and have her eyes just closed as a placeholder, then when the sleeping sprite is finished we could use that instead of the regular closed eyes, so the feature is ready to go once the sleeping sprite is done.

**Comment by Akh0r** [comment]
I vote for light dimming!
But it would be better if some near-visible part of an image still was there. Like Monika's silhouette lit by only whatever-the-hell-is-this outside the windows.

Actually, being a program, she doesn't have to sleep, so keeping her eyes closed (and, possibly, sometimes opening them to 'check' on you) would be good, IMHO.

What is most important, I think, is that her lines should stop appearing when she sees that Player is not with her.

OK, let me try to make a scheme.

-If Player tells her Goodbye/Good Night – she closes the game, going to whatever mental safehouse she has for herself.

-If Player ceases to click through her monologue she waits for 15 minutes, then removes current chat line and instead asks:
`You seem to be away from me. Are you busy out there? I think so. Well, call me when you're back!`
After that, if Player doesn't do anything and the time is night (0–6 hrs), she assumes you are asleep with something like this:
`It is quite late already. Well, I really hope you are not stuck on anything immersive like watching films or surfing the Internet! If this is the case – I warn you that I'll eventually find a way to shut your PC down! Or…  Maybe you simply left me while you are sleeping? That'd be cute! So I'll watch over you…'
After a couple of lines, she would enter the sleeping mode.

-If Player straightfully tells her that s/he is going to sleep, but doesn't want to shut the game down, she will skip idle-concerning phrases straight to "I'll watch over you" and dims the lights.

-If Player is absent during daytime, she will stop showing new monologue lines after 15 minutes delay and just lefts the message that she's waiting for a call. But she won't enter the Sleeping Mode, unless being asked to.

Also, it may be fun for Monika to propose Player to answer for his/her E-Mails and other online calls.

Or maybe she could be programmed to shut down the computer (if running on one) after a specified time. 

Or, if asked to, she could switch on the light and play music with slowly increasing volume, being your cute wake alarm :)

I think it is not so hard to implement

**Comment by ThePotatoGuy** [comment]
[[We'll reopen this when we look into]]
