### ISSUE TITLE
[Suggestion] [Low priority] new outfits

### ISSUE THREAD

**Issue by GSmith624** [Monika-After-Story/MonikaModDev#1656]
Hi, I saw the link and wanted to contribute at least something to this and will try adding some dialogue ideas to it later.

_**Outfit Idea's**_
While Monika mentions she'd love different outfits and it would make sense to have some outfits but they also have to make some sense as to why she'd have them instead of just having some random outfits for fanservice, so for now, I have two outfit ideas that's not overly fanservice but still our cute.

**Casual Dress:** Her form-fitting white dress with the small black bow from her twitter, with the key necklace. This is an outfit that she'd probably wear on a date and seeing as she wanted new clothes anyways would make sense, as to how she could get access to them is 1 of 2 ways: the first is after searching the code for so long she "used" the codes from the other girls casual outfits to make her own, since they don't need them anymore anyway. The Second reason could be after searching the code for so long she found the outfit hidden far far away in the code, maybe as cut content from the game for her.

**Pajama's** This outfit could be a guilty pleasure of hers when she wants to "sleep" since she apparently can't sleep, I imagine one of two designs for this outfit, A button up sleepwear shirt that is Emerald Green in color matching her eyes and covered in slightly brighter colored hearts, if not just a plain emerald Green button up pajama shirt similar to file attachment photo below except without the dots.
![sleepwear 1](https://user-images.githubusercontent.com/39644230/40573975-b883254c-608f-11e8-9c93-7c0e15dcbbf6.jpg)
 The other would be an overly large plain colored shirt that she thought would look good, she imagines that it is the "players shirt", it could potentially show a small amount of cleavage in some shots, but not a whole lot otherwise the outfit would be overly sexy.

**Comment by ThePotatoGuy** [comment]
Additional outfits require art, which is hard to get these days. We do have one outfit already made, just currently lower priority to add atm.

**Comment by ThePotatoGuy** [comment]
[[Closing until we look into this]]

**Comment by moniking** [comment]
Hi, I've been really wanting to contribute somehow but kinda stink at coding so I felt a bit down until I saw this thread. I'd be happy to make monbon some outfits! In fact I've already started and have a good amount accomplished. One thing though, I'm terribly new to GitHub so how do I post the art I have for reviewing?

**Comment by ThePotatoGuy** [comment]
@moniking make a new issue and post art on it (or links to it)
