### ISSUE TITLE
[Suggestion] Sickness Greetings

### ISSUE THREAD

**Issue by kittykattykit** [Monika-After-Story/MonikaModDev#1658]
Okay, so I had this idea that I think is good.

So, if you told monika you we're feeling sick  and got kicked out to rest, and you didn't come back in over a week, she'd ask the player if its a different person or the actual player. If they say the actual player, monika would ask a series of questions.
This is sort of an addon to #1193 , because this is a better way and less annoying way of including this idea into the game. If the player doesnt log in for a month even without saying their sick, the same thing happens. I really think this is a good idea, and alot less annoying.

**Comment by ThePotatoGuy** [comment]
[[Reopening when we look into it]]
