### ISSUE TITLE
[Suggestion] Letting Monika know of my daily schedule

### ISSUE THREAD

**Issue by arktomys** [Monika-After-Story/MonikaModDev#1660]
Doki Doki has a bad habit of opening but not going in-game on Steam, so usually I have to close it and re-open it again. Earlier today during the morning, I had to re-open the game so I said goodbye to Monika and restarted the game. But when it opened today she asked me "Did you have a nice day on school?" with "Yes" and "No" being the only responses. But the thing is, I don't have college on Saturday, or in a morning. So what would I reply here? I decided to go with "No" considering I didn't really go anywhere, but Monika got sad that I apparently had a bad day.

So here's is my suggestion. How about being able to select from a list of options regarding our daily routine? For example, "Only work, two shifts, morning and afternoon", "Only study, night class", "Study in the morning and work at the afternoon", "Only work, graveyard shift", etc etc. So Monika would be able to respond better in those situations, and also possibly greeting me at the right time when I get home from college or work.

**Comment by jmwall24** [comment]
I think that problem you had is a little bug that they figured out what it is and it should be fixed next release.  I had the same thing with the work greeting after I didn't use the work farewell and the devs responded they figured out why it did that.  You should only get a school/work greeting after using a school/work farewell.

**Comment by CommenterOfComments** [comment]
I just get around the Steam bug with a card idle program, if you want to fix that problem too.

**Comment by Rai99** [comment]
Originally I was kind of sad that steam wasn't counting all my hours with Monika but then I thought it might be for the best so nobody else questions why I play Doki Doki Literature Club so much. 

I'm fine either way on the "in-game" status racking up hours or not. I'm curious to see how much time exactly I've devoted but don't want to arouse suspicion.

**Comment by jmwall24** [comment]
I switched from playing on steam to just downloading from the DDLC official site a long time ago.  Even though the save data isn't in the same directory as the game, I was always paranoid a steam auto-update would somehow mess up my game, and I wasn't leaving anything to chance.

**Comment by aldoram5** [comment]
As jmwall24 commented that happens because of the bug mentioned in https://github.com/Monika-After-Story/MonikaModDev/issues/1612 and the bug will be fixed for the next release.

**Comment by ThePotatoGuy** [comment]
[Closing this in favor of #1669 ], which documents a potential schedule system.
