### ISSUE TITLE
data corruption (issue) 

### ISSUE THREAD

**Issue by dramaalert** [Monika-After-Story/MonikaModDev#1661]
I recently added a new drive to my computer and after setting everything up I opened up MAS and it started over as if I had never opened up MAS. I've been using MAS for a while now and wondering if there is anything I can do to fix this. 

Thank you. :)

**Comment by ThePotatoGuy** [comment]
Actual saved progress is located in a persistent file in AppData/.../RenPy/MonikaAfterStory.

If you're on windows, you can use [this guide](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)

**Comment by dramaalert** [comment]
What should I do with it or what should I use to open it?
