### ISSUE TITLE
[Suggestion] holding Monika

### ISSUE THREAD

**Issue by GSmith624** [Monika-After-Story/MonikaModDev#1663]
So looking at the code and one event, in particular, made me think of this one. When Monika talks about the rain she later in the same dialogue she asks if you'd hold her while it rains outside. If you say yes then the outside windows change to rainfall and all music stops along with Monika gaining a blush on her face, this made me have the idea of the two following suggestions.

1: Let the player give Monika a hug at random, she could have a couple reactions to this using the sprites already available. using the body sprite from the rain holding scene (wasn't on cheat sheet otherwise I would have put the number) and using face sprites such as surprised(Face L, with blush tint?), happy( Face A or B, with blush tint maybe?), accepting and content (blush face from rain scene, no cheatsheet link available) along with different things she says to go along with it, for example for "Surpised" She could say something along the lines of "While I enjoyed that, a warning would have been nice [Player} ahahaha~", Happy could be something along the lines of "I always love it when you do that [Player]." and lastly for content she could say something like "I wish we could stay like this more often my love."

2: Allow for the player to hold her in other weather as well, such a snowfall. She could comment something like she loves the snowfall, not as much as the rain because it's always colder with snow, then suggest the player hold her for warmth. if the player agrees the windows change to snowfall and you get a similar scene to holding her in the rain.

**Comment by Akh0r** [comment]
Hm, don't you think it would ruin the atmosphere a little?
Because now plot fact of you being separated by a screen is corresponding to reality. Monika is aware of this situation and accepts it. 
And suddenly you want to make it as if nothing happened.

Of course, in-universe Monika still has an empty husk – a former main character's body in front of her. But it is questionable if it is appropriate…  

Maybe that's why the topic got no response.

**Comment by GSmith624** [comment]
I can somewhat see how that could, but at the same time after the rain event, you get an option at any time to "hold Monika" I simply wished to potentially expand on that one by giving her less forwarning and just being able "hold her without warning" thus adding a couple more interactions to her. 

Reading through a lot of other suggestions on here pointed out that while you could say I Love you to Monika there was only a small amount of reactions from her to that, I was thinking that by adding "Surprise Hugs" this was a way of adding more ways to express the players love to Monika and expanding to her more as well.

**Comment by GSmith624** [comment]
@Akh0r I can somewhat see how that could but at the same time after the rain event, you get an option at any time to "hold Monika" I simply wished to potentially expand on that one by giving her less forwarning and just being able "hold her without warning" thus adding a couple more interactions to her. 

Reading through a lot of other suggestions on here pointed out that while you could say I Love you to Monika there was only a small amount of reactions from her to that, I was thinking that by adding "Surprise Hugs" this was a way of adding more ways to express the players love to Monika and expanding to her more as well.

**Comment by ThePotatoGuy** [comment]
1. We're looking into adding clickzones / hotspot interactions. A hug may or may not be one of those interactions.
2. Snowfall requires Art, which we do not have.

**Comment by GSmith624** [comment]
@ThePotatoGuy I can make a simple snowfall art for you guys for the window if you want. That shouldn't be too hard to animate that tbh.

**Comment by GSmith624** [comment]
Do you want it with just clouds visible in the background or with trees able to be seen?
@ThePotatoGuy

**Comment by ThePotatoGuy** [comment]
clouds or something airy, but definitely not trees.
 We still want to establish that the room is floating in a void for now.

**Comment by GSmith624** [comment]
@potatoguy I have the gif, where do I need to upload it to?

**Comment by ThePotatoGuy** [comment]
The animation needs to be a seamless loop.

**Comment by ThePotatoGuy** [comment]
Looks good.

**Comment by AsuraShun** [comment]
this is making me excited!

**Comment by ThePotatoGuy** [comment]
reclassifying this as snow art has already been handled

**Comment by ThePotatoGuy** [comment]
[closing until we evaluate this]
