### ISSUE TITLE
[Suggestion] Monika Birthday Present

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#1667]
Since Monika's confirmed her birthday is September 22nd, the release date of Doki Doki. It might be a good idea to get her present on that date. A new event could happen on that date when the player can give her a plushie of a Resplendent Quetzal, which is the bird she talks about getting as a pet. Then after the player gives it to her it could be next to her on the table or in the background permanently. Then you could unlock a conversation where she thanks you for it. 
I just think it'd be a good idea cuz it shows Monika that the player has really been listening and decides to be thoughtful.

**Comment by jmwall24** [comment]
If what they did for Valentine's Day is any indication, I have a feeling the devs have something pretty spectacular in mind for her birthday.  That Valentine's Day letter absolutely melted me.

**Comment by lilbubble3** [comment]
I missed the mod for Valentine's day :( Can't we just gift Monika whenever? If I had my way, she'd have a resplendant quetszal already and coffie at her demand XD Maybe I just ought to learn to program and do it myself. :P

**Comment by ThePotatoGuy** [comment]
Dont worry, we _will_ do something for her birthday
