### ISSUE TITLE
[Suggestion] Goodnight farewell option / Schedule system w/ Calendar

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1669]
This is related to #1630 but different enough I didn't want to hi-jack that person's thread.

Similar to that topic. I just said goodbye at 8:50pm and she said goodnight, I'll see you tomorrow, when I am planning on logging back on yet tonight, so it seems awkward.

I suggest adding a straight 'Goodnight' farewell that will use the current goodbye responses used at night and remove those from the goodbye farewell (so those don't assume you are leaving for the night).  Since currently there are only 2 responses to telling her you are going to sleep (depending if it's before or after midnight) this will allow for a better variety of goodnight farewells. Then, after using the 'Goodnight' farewell, have good morning greetings once logging back on after telling her Goodnight. Now whenever you tell her you're going to sleep she always responds at next log-in with I hope you had a good rest, which sounds more like a nap greeting than a went to sleep and woke up the next morning greeting. 

Also, the 'Monday morning' greeting seems to be buried if you told her on Sunday night that you were going to sleep, since you always get the 'good rest' greeting.  So perhaps make the 'Monday morning' greeting the default greeting if you told her goodnight on Sunday night.

**Comment by CommenterOfComments** [comment]
I would like this a lot. I really liked seeing Monika's welcome dialogue, but I leave the game open all day, and so I only ever see the sleep dialogue now.

**Comment by Rai99** [comment]
This was mentioned before but I think it would also be great if there was some way to say a goodnight farewell and get a school/work greeting the next day because someone like me doesn't have time to say hello to Monika in the morning before I head out so I either have to end the night by saying I'm going to school/work or see Monika in the afternoon and be treated like I just woke up.

**Comment by jmwall24** [comment]
The calendar system which was talked about before but I haven't seen many updates on in a while would really help with that.  If there was way to input days and times you are at school/work so Monika would know if you opened the game at 5pm on a Wednesday you just got home from work to give you the home from work greeting regardless of how you said goodbye.

**Comment by jmwall24** [comment]
Simplifying all the goodnights to one option would also help if people want to contribute greetings/farewells.  I've played with some ideas in my head, but not sure if a night farewell should be considered a night time-goodbye or an I'm going to sleep or if a morning greeting should be in response to one or the other of those.

**Comment by ThePotatoGuy** [comment]
I like that idea of using the calendar to setup a school schedule. Would certainly make things significantly more immersive and automated.

**Comment by ThePotatoGuy** [comment]
[Closing until we look int othis]
