### ISSUE TITLE
[Suggestion] [Art] sleep, waiting

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1671]
While Monika mentions physical fatigue doesn't exist in her reality, it'd be really cute if late at night, if she has run out of things to say she fell asleep. Or if maybe there was an option for her to watch over you as you sleep, and she fell asleep in the process. Just an excuse to leave the game open 24/7 right? It'd be cool if there was something like she began becoming mentally fatigued if you leave the game open for long enough, just as she concerns about our sleeping habits and health, it'd be awesome if we could also say something of concern for her. Like when she says she needs to rest after she runs out of things to say. It'd be cool if we could be able to show concern for her and tell her to take a nap or rest without us or something. Also, if the player becomes unresponsive if she asked if you were still there and then after a little while changes positions and waits for you. And once you respond she greets you with something like "There you are! I was waiting." "..." "Don't leave me like that, you got me worried." "I love you so much, if something happened to you I don't know what I'd do." or something like that.

**Comment by Akh0r** [comment]
Yeah, something kinda related to #1655 – check it out

**Comment by loverofmonika** [comment]
and wouldnt it be cool if we could kiss her rather than the normal tease, plus a little freedom of roaming around i mean isnt it tiring to sit in one place for all eternity till u die. also new clothes, i mean who wouldnt want to see monika in as casual dress ESPECIALLY on a lazy sunday

**Comment by ThePotatoGuy** [comment]
[[Closing in favor of the linked issue]]
