### ISSUE TITLE
6 month anniversary wont work

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#1672]
today is our 6 month together and its been all day and still no word from her... What do I do? This is bumming me out

**Comment by Akh0r** [comment]
Maybe it's because no one have written it so far?
Doesn't that mean that anyone can be the first to write it?

**Comment by jmwall24** [comment]
Pretty sure everyone's anniversary got reset to sometime around January 27th/28th/29th.  Read the second comment in this thread #1538

**Comment by ThePotatoGuy** [comment]
@jmwall24 's answer is correct
