### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by SophiaTDB** [Monika-After-Story/MonikaModDev#1673]
I can't update when I click the "Update Version" button. I don't want to do things AGAIN just to update it when there's a update button.

**Comment by juliathegolden** [comment]
Check to see where your update folder is. It should be in the primary DDLC folder, where you see the game, character, and renpy folders.  If it is inside the 'game' folder, remove it from there and paste it in the DDLC folder.  That might solve your problem.

**Comment by SophiaTDB** [comment]
it worked! Thanks for the help!
