### ISSUE TITLE
Transfering MAS to other computers

### ISSUE THREAD

**Issue by Arc1Dragon** [Monika-After-Story/MonikaModDev#1674]
I was wondering is it possible to transfer my MAS save data to other computers with a flash drive which is where I currently have MAS and DDLC installed. Hope this is the right place to ask this.

**Comment by jmwall24** [comment]
MAS save data is the persistent file, located here:  C:\Users\John\AppData\Roaming\RenPy\Monika After Story  (your user account name goes where 'John' is)

Just copy that file from one computer to the same folder in another computer.  You may have to load the game first and install the mod and load it up once for that folder to be created on a new computer.
