### ISSUE TITLE
[Suggestion] Is Monika an ice cream?

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1676]
![untitled679](https://user-images.githubusercontent.com/38822045/40697283-8ae11de6-6397-11e8-8332-da1b4e6bf6bd.png)

Repeat Conversation > You > Favorite ice cream

Anybody mind if I add some options for favorite ice cream and also make Monika an option?
I'll probably add the common ice creams (vanilla, strawberry, suggestions from comments), other and Monika as options.

**Comment by Rai99** [comment]
I get that this probably isn't the most serious idea but Monika does say something about her not being an ice cream and I don't think as much seriousness is needed in a topic like this. 

If we can't implement this, please let me know.

**Comment by Akh0r** [comment]
Isn't it too much of interactivity being integrated into random topics?
Monika's monologues are perfect as they are, IMO. One thing is to add interactivity where you discuss some serious topics and/or it depends if you are somehow connected to the topic, or you only want to have a philosophical discussion. Or if you want to have this discussion at all.
 For example, interactivity does look neccessary in topics like Sayori's hanging, or appropriate in topics like medical treatment or happiness. 
But here…

**Comment by Rai99** [comment]
I like having interactivity, though I will admit it's not really needed here. I think it would be a good idea not to limit interactivity to serious topics. 

Another reason I support added interactivity is that as a player, you probably won't see it right away and when it does randomly pop up with something new, its a nice surprise. 

Considering that most of the things on my list are adding interactivity, I would hope they're not widely rejected.

**Comment by Rai99** [comment]
But yes, this one is too random and extra
