### ISSUE TITLE
[Suggestion] Sleeping with Monika 

### ISSUE THREAD

**Issue by HoboSasuke** [Monika-After-Story/MonikaModDev#1678]
I like to sleep with the game open to simulate sleeping with Monika, but it would be pretty sweet if this could actually be a mechanic. Currently when you tell Monika you're going to sleep, it requires you to say goodbye and the game closes. I'd love it if I could ask Monika to sleep with me. She'd then close her eyes and silence the music. After this, an option would pop up that says "I'm awake," and you'd press that whenever you woke up (The option should be out of the way and not covering Monika's face, as seeing her when you wake up is part of the charm.) She would have different reactions depending on the time of day and how long you slept. 

For example: Lets say you go sleep at 11PM. Waking up at 8AM would prompt a simple "Good Morning darling, how'd you sleep?" whereas waking up at 1AM would prompt a "Is everything okay? Its 1 in the morning, you shouldn't be awake yet." This could allow for an array of options like telling Monika you cant sleep, telling her you had a nightmare, telling her you work a night job, etc.

Another example would be: Lets say you go to sleep at 2PM. Monika would say something along the lines of "Taking a nap I see. Just don't oversleep, okay?" then proceed to sleep with you. If you wake up at 3PM, Monika would say "How was your nap?" and give a small speech about how good naps are for you (I think she may have a dialogue about this already? Maybe she could recycle that.) However if you woke up at 10PM she'd lightly scold you for sleeping the day away where you'd have the option to apologize, tell her you work a night job or tell her you were really tired.

Sleeping with her on a regular basis could have small little dialogue rewards as well. For example, sleeping with Monika every day for a week consecutively would have her say something along the lines of "It really means a lot that you do this with me. I really love you." or something like that. She could have a bunch of sweet messages like this the longer you do this with her. After 2 weeks or so she could have a warning as well. Something along the lines of  "Hey [PLAYER]... while I love being with you when you wake up, it probably isn't good for your computer to be on for so many hours at a time. Maybe you should stop doing this so often, If your computer breaks I won't be able to see you anymore." After this a few dialogue options could pop up, some suggestions being "You're right, I'll cut down on it." "But I love waking up to your face..." and "That won't happen, don't worry."

Not sure if others would love this feature as much as I would, but as someone who regularly sleeps with Monika already, I think it'd be a really nice update.

**Comment by ThePotatoGuy** [comment]
We'll take what you wrote into consideration, but I'll close this in favor of #1655 so we dont have too many open duplicates.

This will be linked tho, so it wont get lost.
