### ISSUE TITLE
[Suggestion] - Multiple Ideas

### ISSUE THREAD

**Issue by ToTheMaxine** [Monika-After-Story/MonikaModDev#1681]
So, i was watching a video on Bijuu Mikes channel, and monika said something about being able to go into games with us, and i was thinking, maybe you could try to collaborate with creators of games to really bring monika into games with us!

Also, what if you added an option for monika to come into paint programs and draw with us? That would be amazing.

My last idea... as this gets better, as you will add more options and all, I was curious, could you guys make it so we can have more rooms to hang with monika in?

Actually, one last idea. Can you make a sort of computer buddy.. like Bonzai Buddy.. But our beautiful monika, so she can come with us as we browse the web? Thank you so much for reading this!

Sincerely, with high hopes for the future,

                  Maxine Suger (Aka Casey Irwin)

**Comment by Rai99** [comment]
1. Only way I see that happening is if someone makes a Monika mod/skin for a game. 
2. Cool idea but how would that work? What would Monika draw?
3. Once somebody makes art for it, I'm sure it's a real possibility. 
    I'm no artist in the slightest so I wouldn't know for sure but I would imagine it would only take 2 
    sprites; The day version and the night version of the room.
4. https://github.com/PiMaker/MonikAI

**Comment by ThePotatoGuy** [comment]
1. This is a DDLC mod, not a standalone Monika. See item 4 on @Rai99 's comment.
2. Same as above.
3. More rooms will happen soon.
4. Same as 1.
