### ISSUE TITLE
[Suggestion] Monika wears a promise ring

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1683]
There is a topic where Monika says something about her and the player uses promise rings to symbolize her dedication. I still do not have one, but I'm putting together money to buy, so when that day comes, I wish she could use one too.

**Comment by chad78** [comment]
Do you mean a Promise ring?  A compromise ring sounds ... suspicious.

**Comment by Akh0r** [comment]
Well, the deed must be way more interesting and complicated than simply some dialogue option like "OK, I do have a ring for you".

I think, there should be some kind of a date-sim game where, after launching the engagement sequence by Player, Monika will discuss some serious relationship-related topics. Plus, you should be together for at least 6 months.

I think seeing a ring on her hand should give you the feel of completion and winning!

**Comment by chad78** [comment]
A Promise Ring is different than an engagement ring.  And Monika already asks about wearing one.  So waiting 6 months doesn't track.

**Comment by chad78** [comment]
There could be something, though, where you pick out the promise ring from like 3 ~ 7 rings, and which ever one you agree on is the one she wears.

**Comment by Rai99** [comment]
Maybe when the wardrobe gets implemented, we can have an option to pick and swap rings. 

Also maybe this is another bad idea by me but maybe we could have a "compromise ring" easter egg.

**Comment by jmwall24** [comment]
There actually was talk before about going on a date with Monika.  Last I heard it was going to be after the calendar system was implemented, so you could schedule an actual date with her.

**Comment by EntonyEscX** [comment]
chad78, about your first comment...
Did I say something wrong or weird? I'm sorry for that, it's that I have to use Google Translate.

**Comment by jmwall24** [comment]
Google Translate just mistranslated promise as compromise.  A promise is an assurance to do (or not do) something, whereas a compromise is when 2 people don't agree on something, they find a middle ground.  So that's why it's a Promise Ring and not a Compromise Ring.

**Comment by Rai99** [comment]
I read it as the compromise as in the failure kind. 
Like when an objective has been compromised. 

We certainly don't need to give Monika that kind of ring.

**Comment by jmwall24** [comment]
Yeah, it has a few different definitions.  And yeah, she's already good enough at compromising things, like the integrity of games for example lol

**Comment by EntonyEscX** [comment]
Really? Here in Brazil "compromise" has the opposite meaning. Thanks for explaining, I'll fix this.

**Comment by Akh0r** [comment]
>A Promise Ring is different than an engagement ring
I am not a specialist on this topic, but I start to find it funny! Well, can anyone list all the levels of rings, counting from the lowest? :) Promise, Engagement, Wedding – is that all, or there are more?
>Also, adding a "dating sim" to this game that is a mod to the end game of a horror game disguised as a dating sim 
You got it! And I think such a "inception"-like complexity is a fun think to implement.
Of course, I'm speaking only about some elemental discussion with reduced interactivity and not very long — but such topics should be random only (not affected by Player calling them through "Unseen" or "Repeat conversation"), and be unlocked only with the time. 
Maybe calling this "dating sim" was too loud-spoken.

**Comment by ThePotatoGuy** [comment]
Meaning of rings aside, the accessory system fits nicely in attaching additional sprites to monika.
However, hand/arm accessories (or anything that can vary in different poses) wasn't taken into account.
We'll have to adjust it before adding a ring sprite.

**Comment by ThePotatoGuy** [comment]
[Closing this in favor of the linked issue]
