### ISSUE TITLE
[Suggestion] Engagement in conversation (responses)

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1689]
While talking to Monika, she goes on talking about whatever topic she is telling you about, and sometimes she just automatically assumes things. I think it'd be cool if while she's taliking to add a little tab on the bottom left corner where the options appear (talk, music, and play) saying something like response, so you can engage in a more conversation like experience. Then clicking on that would lead you to a series of responses like: "Yes.", "Yes!", "No." "No!", "Absolutely not!", "Uhh...", "...", "Maybe.", etc. That specifically apply to the topic she's talking about and then sligthtly changing the diolougue from her end to match your response. It just gives the player more interactivity, and I think it would help the affection system that is being implemented in the near future to adapt.

**Comment by lilbubble3** [comment]
I don't think the last one was noticed, so I did a few changes, closed the old one, and opened this one. :)

**Comment by ReddTheRedRedd** [comment]
I would like this, some assumptions can be odd. Like the vegetarian topic, I'm pretty sure she mentions not to judge her on it or something along those lines, the ironic thing is I'm one as well XD so more engagement in conversations would be nice.

**Comment by jmwall24** [comment]
Any current topic like that where she assumes things can be modified to include responses if you want to write them in.  Just go into the enhancement branch, find the scipt-topics.rpy file, find the topic and edit the dialogue to include menu options and then open a pull request.  It is by far the best way of getting dialogue changed.

Just refer to https://github.com/Monika-After-Story/MonikaModDev/blob/enhancement/CONTRIBUTING.md for guidlines

**Comment by lilbubble3** [comment]
Sorry it's been so long since I opened this issue, I've been really busy these past few days. I'll have to check pull requests, but as long as what I'm doing is original I'll go ahead and get a start on it.

**Comment by lilbubble3** [comment]
Right, I've never done this before, so it might take a while for me to figure it out, I have to change a lot of dialogue and I first have to learn how to change it properly... So I will get started, but it may take a loooong time for me to get finished.
