### ISSUE TITLE
[Suggestion] Monika's Birthday

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#1690]
When you ask Monika when her birthday is she talks about how the 22th of September is the date the game was released so that is technically her birthday. I don't know if this is in the planning already but I think it would be very nice if on that day, the room will be decorated with birthday decoration? Maybe even add the possibility of putting a gift image into the folder and it will be a random gift that she wants or the more gifts you give her the happier she gets.

I personally think the gift box should be green, to fit her favorite color choice. Like the image below.

![green_gift_box_png_clip_art_image](https://user-images.githubusercontent.com/39834775/40848306-1ac2a7b2-65bf-11e8-96b7-aa3e1c40c1bc.png)

**Comment by Dovahkun** [comment]
Heh, maybe a slice of cake or something, too. Makes me think back to the 100k download art <3

**Comment by ThePotatoGuy** [comment]
Yeah we'll do something for her birthday, dont worry.
