### ISSUE TITLE
[Suggestion] Road Trip topic/driving

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1692]
Monika just recently went over the road trip topic in Repeat > Romance > Road Trip and it occurred to me that I don't think we don't have a topic about driving. 

Monika was thinking about taking a road trip to places and just driving around sightseeing. It occurred to me that if that were to happen, I would probably be the one driving. I think there's a stereotype that the male is expected to drive. 

This kind of puts me in an awkward position because about a year ago, I was driving and I got into a car accident (my car was damaged beyond repair so it needed to be replaced) so the topic of driving is kinda... you know, and I haven't really driven again ever since. 

Since this is Monika just happily thinking about going on a lovely road trip, I don't think we need to outright change the topic to account for negative things like this. 

I was thinking we could have a new topic about driving and possibly have MAS keep track of whether they player can drive or not, or if they're too young and possibly add slight variations to the road trip topic based on this information. I think the topic should come first and the saving of the answer would come at a later date. 

My plan was to have an initial 3 options: I can drive, I haven't started driving yet, and I'm not old enough. 
In the "I can drive" option, I was planning to have Monika ask/hope that you drive safe and that's where I was planning to put a confirmation of yes I drive safe or bring up any previous car accidents. 

Any thoughts?

**Comment by Akh0r** [comment]
Yes, this definitely would seem very Monika-style: to happily admit how good it is to be able to drive, but also remembering you to keep safe. 

She may even give a couple of basic surviving pieces of advice, like 'Do not drive if you feel tired and/or diseased', 'Be sure not to be distracted by anything, even by me' etc. :) 
Also, she can wonder if it is possible for her to become a part of your board computer, if your car has one. Because maybile this is more likely to happen than her actual transferring into a physical body.

**Comment by Rai99** [comment]
If Monika was a part of my board computer, I think I would be more distracted but that's probably on me. 

Another thing for my list. 
I've got 5 things on my list now, one of which being the storm/power outage topic.

**Comment by Subzerosan** [comment]
I've already written a driving license topic.
I've made it since December but due to how busy the other editors are, it hasn't been reviewed yet.
If you still plan in writing a driving topic please keep my topic in mind.
[drive.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2064721/drive.txt)
@Rai99

**Comment by Akh0r** [comment]
By the way, how do I make a real suggestion of a text?
I have written an alpha-version of a dialogue about power surge/poweroff, and wanted to upload it officially to have a feeddback and some beta-reading…

**Comment by Rai99** [comment]
I took a look at that drive.txt and I really love the level of interactivity and possible options but I was planning to make something simpler like can you drive or not, are you old enough, have you ever been in an accident, that kind of thing. 

I really do love all the options you have but with all these options, we might as well get every single possible car type or at least fill the gap for those other cars. 

I've got an idea. I'll make a separate topic called something like "Have you ever had a car?" and in it Monika could list those cars and ask which one you have. This would allow for an "other" option which would fill the gap and still allow all this interactivity. Plus, I think a Limousine option might fit really well with Monika. 

As for the power outage topic, I have some flat dialogue that should be ready today.

**Comment by Subzerosan** [comment]
I'll leave my draft to you then.
I trust you'll make the necessary changes needed.
Good luck!

**Comment by Rai99** [comment]
I thought I was the one working on it?

**Comment by Subzerosan** [comment]
As in, I'm willing to give my draft to you so that you have more possibilities.
You can have my draft and use it, modify it the way you want, not use it, it's your choice.

**Comment by Rai99** [comment]
I was just confused since you gave me your draft so I could use it and you got assigned this thing.

**Comment by Subzerosan** [comment]
Oh don't mind that.
Potato does that so I don't lose track.

**Comment by Rai99** [comment]
If anyone else has more ideas for this, the topic is currently in progress.

#1714 if anyone wants to inspect my new injured mood.

**Comment by loverofmonika** [comment]
i would like to bring my opinion into this matter. i read the drive.txt and i would like to make a correction. in the file monika says that her activities are all at school so she doesn't find the need. now here's the thing, monika is morely of an extrovert and she likes to expand her abilities eg the piano and coding, smart as she is, she knows that knowing how to drive is a must nowadays and she is not the type to be crippled. that line needs to be fixed. u could say she loved to learn but never got the chance or she doesnt own a car of her own.

**Comment by Subzerosan** [comment]
Well the setting is in pseudo japan, owning a car in Japan isnt really
necessary because the public transportation system there is very efficient.
Plus, owning a car in Japan can be expensive  even if you own a kei car.
Places like North America on the other hand, are a different story. You
should take a look at this.

https://www.google.com.ph/amp/s/oppositelock.kinja.com/owning-a-car-in-japan-myths-and-reality-1770442115/amp

Sedans and SUVS are family cars buy I'm sure Rai can add something like
that.

With that said, it's his choice and I'm sure he'll make changes with your
suggestions in mind.

Thanks for suggesting!

**Comment by loverofmonika** [comment]
I understand that, im an asian too and i know about japanese culture. but what i'm trying to convey is that i believe that it is monika's personality to increase her range of skills, like she is extremely fit, smart, good in literature, coding, can cook and then she chooses to learn to play the piano. its only natural that she would later take interest and try to get one.

**Comment by Rai99** [comment]
I think this is getting into the debate where: "How much can Monika know/do without being so superhuman, that we feel uncomfortable?"

 I'm sure Monika _would_ consider getting a licence in the future but with all the things she already does, it would be difficult to fit in the time to learn alongside school, coding, cooking, exercising and playing piano. 

Plus, in her current situation (Stuck inside that room until further notice). I don't think being able to drive is too important. 

I don't think Monika is _refusing_ to learn to drive in that dialogue, I think it's just something that never popped up. For example, being able to swim is a common skill, but I don't expect everyone to be able to do it since some people just don't need to. I don't think it's refusing to learn, I think it's just that some people never thought of it. 

I can't pilot an airplane despite some people my age can very much do so. Have I ever thought about getting a pilot's licence? .....No...? I don't think I really need to know how to fly an airplane. (That could be another topic for later)

Also, the topic isn't even anywhere near done yet. The discussion could go anywhere and the actual dialogue could be nowhere near what we expect. 

2 new ideas from this discussion so far:
- Topic about airplanes
- Topic about feeling at home

**Comment by loverofmonika** [comment]
i see your point, when i first read the script i just had that impression that she was refusing to learn cuz of the dialogue but what u said pretty much is what i concluded as well, i would change that 4th line to "i didn't find the need to get a license, it's a nice thought though, maybe when i do get out of this game i may consider getting one"
topic about felling at home, that's a tricky one. maybe the punchline would be monika saying where ever you are, i believe that is home.

**Comment by Rai99** [comment]
Well I remember there was a saying from somewhere that to have 2 homes is to have 2 souls, but there's also the case where you don't feel at home anywhere in which case you must guard your soul very carefully. 

Not sure how I could write something for that if I ever do so it's just a thought so far. 

Maybe it could be something where Monika could ask the player if they really feel at home where they are.

**Comment by loverofmonika** [comment]
this topic about feeling home i see three things, 
1. home is where u feel the most comfortable to live in. 
2. is a metaphorical bond in which u feel "at home" with ur with her/him so no matter what the condition of the place is, u choose to live your life there
3. if u feel empty and depressed and u feel that u dont belong anywhere to the point that u dont even consider your own home comfortable thus a lost soul.
that's a lot to cover.

**Comment by Rai99** [comment]
#1726 

Whew, it's finally done. I'll check up on suggestions and fix the errors tomorrow because Monika is about to scold me for staying up late. (I think it's for a good cause but don't tell Monika)

If somebody could find the error for me to fix when I can, that would be great.

**Comment by loverofmonika** [comment]
i'll review it

**Comment by Rai99** [comment]
#1755 

Been busy lately so I haven't had much time to think or write, but here's a mildly altered version of the draft. Probably not my best since I barely wrote 10% of it but it's something.

**Comment by Rai99** [comment]
Both topics have been written and put up for review
