### ISSUE TITLE
[Suggestion] Remove random possibility from Scripted family topic

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1693]
The scripted family topic in Repeat > Monika > Scripted family seems a bit weird to have as a possibility of getting at random. Monika suddenly starts answering as if you asked her a question. 

I think this topic might fit better in ask a question since Monika answers it like one. Maybe slightly alter the topic name to make it seem like a question and remove it from the random pool.

**Comment by juliathegolden** [comment]
It is done :D

**Comment by Rai99** [comment]
Great, I thought it might be already but just in case.
