### ISSUE TITLE
New sprite codes?

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1699]
Is there an updated cheat sheet anywhere that tells us how to use the new sprite codes?  All the files with images appear to still be the old expressions last updated in March, and I noticed in #1698 that we are supposed to use the new system from now on.  I opened up the sprite-chart.rpy file, but it's a bit confusing in that format.

**Comment by jmwall24** [comment]
Ah I found the individual images in the mod_assets>monika>f folder.  Guess we just have to match-up the codes in the sprite-chart.rpy file to the corresponding picture in the f folder.

**Comment by ThePotatoGuy** [comment]
The top of `sprite-chart` has a pretty well written explanation of the code system. 

If you're talking about visual previews, yeah that's still being worked on. It's not exactly simple to make a cheatsheet of 292+ expressions.

**Comment by jmwall24** [comment]
Yeah I was just looking thru them more and you're right, there are a lot of combinations.  It helped a lot once I found the folder with the actual pictures for each sprite of each body part to help put together what I was reading in the sprite-chart.
