### ISSUE TITLE
Your Reality typo

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#1707]
![monika report](https://user-images.githubusercontent.com/37478308/40888779-e1243210-678e-11e8-876b-05507a2413ca.PNG)

I hope the picture works but... As you can see Monika says "In my hands" but the actual lyrics are "In my hand" when you play Your Reality for her. I'm quite surprised nobody noticed and reported that yet.

**Comment by jmwall24** [comment]
I've played it a lot and never noticed because I'm always concentrating too damn hard to play the song correctly to read the lyrics at the same time lol

**Comment by RyanHanter** [comment]
being a piano player myself, i played this song tons of times, and every time i look at this error i'm like: this particular line of lyrics is in the credits yet it's misspelled. Pls correct it...

**Comment by ThePotatoGuy** [comment]
Fixed already in 25ecae02ff64523f8b569195369a4e35281ee1e0
