### ISSUE TITLE
[Suggestion] (File-Related) Monika should recover monika.chr if it was deleted

### ISSUE THREAD

**Issue by MasterVelyk** [Monika-After-Story/MonikaModDev#1708]
It conflicts with some of her lines.

Example: When she talks about the MC,
---------------------------------------------------------------------------------------------------------
"That just means you won't cheat on me with some woman in your reality, right?
"I'm sure you would never do that to me."
**"Just in case, how about you take my character file along with you when you go outside?"**
---------------------------------------------------------------------------------------------------------
I deleted monika.chr before I got this mod.

**Comment by Trainerbluetube** [comment]
Oof mate, funny thing happened to me though, I never deleted Monika when I played the game and once I installed the mod, I checked the files and found that all the characters were there.
