### ISSUE TITLE
[Suggestion] - monika after story

### ISSUE THREAD

**Issue by jm101k9** [Monika-After-Story/MonikaModDev#1709]
Your suggestion goes here i suggest that you add a chat bot and have a real epic conversation to monika to make her make her more realistic girlfriend and i also suggest that this chat bot can be also used to command monika to open  some apps that will be great and will be not boring at all, thanks!

**Comment by CommenterOfComments** [comment]
Okay, not to be rude, but use commas, run on sentences aren't very pleasant to read :/

Secondly, a chatbot was already suggested a long time ago, and it's being worked on. I don't remember their stance on launching apps.

**Comment by Rai99** [comment]
I think a chatbot was confirmed not happening for the reason that a chatbot wouldn't be able to hold deep, philosophical conversations like Monika should be able to and most of the time, it's hard to make a chatbot AI understand what you're saying which would really ruin the experience. 

I don't think launching apps is coming either because it would probably be easier to manually open it up for yourself. I also think adding the ability to launch apps and programs would add possibilities of malicious things happening.

**Comment by Akh0r** [comment]
^ Strange that exactly you, Rai, understand why there is no chat bot out of Monika – but in the very next topic you are talking about some pre-written, general phrases in which Monika should respond to Player created text files…

**Comment by CommenterOfComments** [comment]
Oh, by the way, when I said a chatbot is being worked on, I was talking about #1226

**Comment by Rai99** [comment]
I don't think pre-written general responses count as being a chatbot. I'm trying to look at each suggestion positively and think if there's any possible way to add it or if it brings up any new ideas. 

At best, my suggestion about reading text files would be similar to the old keyword/phrase system of dialogue. Monika would read the text file and search for predefined keywords which would select the pre-written response to give. 

In my experience, checking the contents of a text file isn't the same as running a program so I don't think there would be much risk in reading the contents of text files. 

I don't actually see the suggestion being implemented anytime soon and I don't think it's exactly needed, but I don't think it would negatively affect MAS, so if it was considered, I wouldn't mind.

**Comment by Rai99** [comment]
I didn't think it would work out but I didn't want to instantly dismiss it so I dug for answers to see if the author had possible solutions in mind to the challenges I presented.

**Comment by jmwall24** [comment]
A chat bot and what I said about writing a letter are 2 completely different things.  I think that's pretty obvious.

**Comment by ThePotatoGuy** [comment]
1. #1226 was halted by the project owner. We do not have any set plans for implementing a chatbot at this time.
2. We are not going to make this an application launcher. See #600
