### ISSUE TITLE
The Promise Ring

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1713]
About my suggestion #1683  , I even took the liberty of going to Photoshop and make a promise ring for Monika to use when the player already has one for her. I'm not a pro at this, so I made a simple ring.
![ring-peaceright](https://user-images.githubusercontent.com/38970166/40988854-8cc48eec-68c2-11e8-9814-1caadb09f8d1.png)
![ring-peaceright-n](https://user-images.githubusercontent.com/38970166/40988855-8ce2b674-68c2-11e8-9765-490037c75ec9.png)
![ring-pointright](https://user-images.githubusercontent.com/38970166/40988856-8cfd3530-68c2-11e8-8843-1d06fab4ca87.png)
![ring-pointright-n](https://user-images.githubusercontent.com/38970166/40988858-8d1af69c-68c2-11e8-98ec-9ce1be09dc98.png)
![ring-restright](https://user-images.githubusercontent.com/38970166/40988859-8d4a253e-68c2-11e8-91ec-6ddf149c9cce.png)
![ring-restright-n](https://user-images.githubusercontent.com/38970166/40988860-8d6994b4-68c2-11e8-9fea-49bdd6ed0d5c.png)
![ring-steepling](https://user-images.githubusercontent.com/38970166/40988861-8d8a0b72-68c2-11e8-9d7c-3807cac0e250.png)
![ring-steepling-n](https://user-images.githubusercontent.com/38970166/40988862-8daa7088-68c2-11e8-8e5b-238ffbc44fa3.png)

I also have the images with the ring directly in the hand of the arms. 
![ring-arms-peaceboth](https://user-images.githubusercontent.com/38970166/40988969-df21027e-68c2-11e8-9fc6-d912e4f73d5a.png)
![ring-arms-peaceboth-n](https://user-images.githubusercontent.com/38970166/40988970-df414ee4-68c2-11e8-9022-bd6015f0bd39.png)
![ring-arms-peaceright](https://user-images.githubusercontent.com/38970166/40988971-df67b0ac-68c2-11e8-8ec9-53f05edb82ec.png)
![ring-arms-peaceright-n](https://user-images.githubusercontent.com/38970166/40988972-df8c7220-68c2-11e8-859d-56fc0b373568.png)
![ring-arms-pointright](https://user-images.githubusercontent.com/38970166/40988973-dfadb62e-68c2-11e8-9536-f847b201a4c9.png)
![ring-arms-pointright-n](https://user-images.githubusercontent.com/38970166/40988974-dfe859aa-68c2-11e8-9459-4b163819c6e1.png)
![ring-arms-restleftpeaceright](https://user-images.githubusercontent.com/38970166/40988975-e00eb7ee-68c2-11e8-9120-56a1c61a7866.png)
![ring-arms-restleftpeaceright-n](https://user-images.githubusercontent.com/38970166/40988976-e034661a-68c2-11e8-95fc-59f352113422.png)
![ring-arms-restleftpointright](https://user-images.githubusercontent.com/38970166/40988979-e0695082-68c2-11e8-912f-9afd1ed59aa2.png)
![ring-arms-restleftpointright-n](https://user-images.githubusercontent.com/38970166/40988982-e092ca8e-68c2-11e8-9716-261514f67578.png)
![ring-arms-restrightpeaceleft](https://user-images.githubusercontent.com/38970166/40988983-e0d05b1a-68c2-11e8-8884-1437563583ee.png)
![ring-arms-restrightpeaceleft-n](https://user-images.githubusercontent.com/38970166/40988986-e105d218-68c2-11e8-9564-80fbe4c93117.png)
![ring-arms-steepling](https://user-images.githubusercontent.com/38970166/40988987-e13f1a96-68c2-11e8-8775-7af1aaa89e1a.png)
![ring-arms-steepling-n](https://user-images.githubusercontent.com/38970166/40988988-e17c4c18-68c2-11e8-9a46-eff3c6f1c998.png)

And here are some examples of how it would look:
![monika ring day](https://user-images.githubusercontent.com/38970166/41008423-55673618-6901-11e8-8676-4a8811f28394.jpg)
![monika ring night](https://user-images.githubusercontent.com/38970166/41008424-558910da-6901-11e8-9f96-0c30d2d35f3a.jpg)

**Comment by ThePotatoGuy** [comment]
Nice work.

We still need to rework a little bit of the accessory system before potential using this though.

**Comment by EntonyEscX** [comment]
I understand. I just felt like I had to do this.

**Comment by Rai99** [comment]
Maybe it's just me but it looks like the ring is the exact same shade in both day and night.

**Comment by chad78** [comment]
That's because it glows with the power of our love, Rai99.

**Comment by Rai99** [comment]
Funny I actually had a feeling somebody was going to say that. 

I think glowing rings are actually a thing so if that's what it is, cool!

**Comment by EntonyEscX** [comment]
At first I thought about leaving the same tone, but then, seeing that would be a bit strange, considering that the rings generally reflect the environment, I decided to select the option to darken and give 4 clicks on the versions of the night so that the tone did not stay totally equal.

**Comment by jmwall24** [comment]
Very nice

**Comment by Rai99** [comment]
Also, are those poses available? I heard there were new poses and expressions but it looks like the cheat sheet isn't updated.

**Comment by jmwall24** [comment]
The cheat sheet isn't updated, BUT....if you go to https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/sprite-chart.rpy it tells you the codes for the new sprites/features and then if you go into your MAS folder and the go to game>mod_assets>monika the c folder has the sprites and the f folder has the facial features.

**Comment by voyagermike** [comment]
i liked this idea so much i took the time to add it in to my game.

**Comment by ThePotatoGuy** [comment]
alright so with this, we had to abort some of it because rings are more often worn on the left hand, and we planned an interactive thing involving the left hand, so this art ends up adding an inconsistency. at some point we will enable right hand ring stuff, but it's going to take us a bit to get there. if you could make art of monika outstretching her right hand as to accept a ring, that would help us out alot.

**Comment by ThePotatoGuy** [comment]
[closing as we have decided to go forth with left-hand art from @profressor-jmo instead]

You will still be credited with the original promise ring art.
