### ISSUE TITLE
[Suggestion/Correction] Monika confuses the player with the protagonist in some topics

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1715]
On some topics, Monika refers to the protagonist as "you", for example, when she quotes some event of the game as when Yuri takes our character to the closet, Monika says: "when **you** and Yuri were in the closet", even though the protagonist and the player (you) are clearly different individuals. I think it would be a good improvement if Monika referred to the protagonist as "MC" or just as "protagonist", and only said "you" when referring to the player. (I'm sorry for my bad English.)

**Comment by kubastory9** [comment]
I think she is talking in this way, because MC is our avatar to interact with their world. So when he's our "representation" I think it's not bad to call him "us", but I must say, I hate this guy.
