### ISSUE TITLE
[Bug] Music

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1716]
This one is extremely low priority to the point I almost didn't post it, but figured I would in case it becomes more of a problem later on.  If you right-click while listening to music so that all the boxes disappear, and press the 'M' key to open the music menu and choose 'No Music' to stop the music, the music stops as it should, but if you then right-click again to bring the boxes back up, the song you were listening to re-starts automatically from the beginning, and clicking 'No Music' no longer stops music from playing.  The only way to stop music is to choose a different song and then click 'No Music.'  This applies to MAS songs as well as user-installed music.  So kind of 2 bugs there, the first being the music starting by itself and the second not being able to turn it off once it does.

**Comment by jmwall24** [comment]
Just found another twist to this.  I decided to play the piano, but I had music on.  I chose to stop the music after I chose to play piano but before I actually go to where I play the piano.  Once I chose to 'Quit' playing the piano, the music that I had told to stop started playing again, and like before can't be turned off without starting another song first.

**Comment by lilbubble3** [comment]
Adding to it, when playing the piano the music stops as it should, but when you're finished the music doesn't return, and when you try clicking on a song nothing happens, you have to click 'No Music' before it will let you select the song you want to play again.
