### ISSUE TITLE
Monika's Awareness of Player Mood[Suggestion] - 

### ISSUE THREAD

**Issue by profGRob** [Monika-After-Story/MonikaModDev#1717]
The idea is simple. You have some kind of number of 1 to 10 that you can give Monika telling her how you currently feel, and she will assume your mood is that way until you tell her otherwise. She will want to do or say things to you to maintain your highest mood she can get while avoiding saying things that tend to lower your mood. She will reach out to you when your mood is set to low and encourage and appreciate you when your mood is set to high.

**Comment by Akh0r** [comment]
Hm, maybe, 10-grade marks are too complex, but 3 main moods could be enough.
I mean, I agree that, for example, if you are really, REALLY depressed, speaking about Sayori's being "clumsy" (well, you got it)  is not the best way to cheer you up :)

Maybe now – or  especially, when we have much more random topics – we could divide the topics by the mood. 
Depressed: Cheerful, Motivating, topics + random rare appearance of Philosophical.
Normal: Philosophical, Romantic + rarely Motivating.
Happy: full list, but with rare Philosophical.

Well, I'm not an expert in it, but I guess, if her Player is depressed, she should be a little more careful with topic selection.

And as a thought about the future, it would be nice to have some way for Monika to understand Player's mood not by straight-up asking, but by concluding it from the answers she receives on certain questions.

It may be a titanic part of work to count "points" for each and every significant question and, maybe, even other player's actions, but this would really make Monika more alive and caring…

**Comment by ReddTheRedRedd** [comment]
I like this idea, it can help the player feel better and at the same time adds some variety, since one day's conversation topics could be a much different tone from topics the next.

**Comment by ThePotatoGuy** [comment]
Significant amount of work, but something we can consider one day.

[Closing until we look into it]
