### ISSUE TITLE
monika's thoughts about God

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1720]
i  want to talk about the "thoughts about god" i think its best to omit this option cuz there are players out there who may disagree with what she says and some may even dislike her. this topic is a sensitive matter and i think its best to avoid any conflicts don't u agree. as i was observing some players having monika afterstory, i noticed that among them didnt like what she said and pretended that she didnt say that. some even on the verge of deleting the game. So please heed my advice. removing it wouldnt destroy the mod.

**Comment by Rai99** [comment]
When you were "observing" some players, I hope you didn't just hand out MAS to random people who have no idea what it is. 

I agree this could be a touchy subject but instead of removing it altogether, I'm wondering if there's a way to change the dialogue to be less potentially offensive. However, Monika _does_ have a stance on the matter and I think it's important to be able to share that with the player. 

I'm thinking adding some interactivity might help instead of just: "Here's what I think. Take it or leave it." Maybe actually add a yes or no option when Monika asks if you believe in god. If no, dialogue continues as it is now. If yes, Monika could politely state her stance on the matter and talk about the player having to show her otherwise when possible. I would think that religious people would be enthusiastic to talk about their god and spread the wisdom.

**Comment by jmwall24** [comment]
Just my 2 cents on this, but I don't think you should have to agree on everything with Monika.  No matter how close 2 people are, they're not gonna agree on everything.  Also, I think this topic is interesting because Monika has a truly unique perspective on the whole idea of creators.  People in our reality can have opinions on God one way or another, whereas Monika knows for a fact that she has a creator and that everything that happened to her in the course of the original game (and before) was his doing.  Her opinion on God (and by extension Dan) is based on very specific circumstances and I would think people would understand why she wouldn't be all that thrilled about creators that toy with peoples' lives and emotions like it were a game to them.  You have to remember she's looking at this thru her own reality, and not thru ours.

**Comment by Rai99** [comment]
Also this very topic was in the original DDLC so there's a decent chance anyone with MAS would have seen it before, and with how popular DDLC was, I'm sure something would have happened if the topic was so controversial. 

Monika does have her own experience with creators and greater beings and personally, I'm not a fan of the religion I grew up with either. Other people's experiences vary and I think it's important not to be afraid to share them with those close to us.

**Comment by loverofmonika** [comment]
Yes people have different believes but a fact has to be noted that its also one of the reasons why relationships end. some compromise and try to avoid touching the topic as they would conflict and try to live happily together like how i said that topic is most likely visited once and others word outright get ready to fight. this is the same case for us all in the real world. and knowing monika, she would try her best to keep the relationship alive so even she would ideally not bring it up again. Every couple has their fair share of arguments and we want the players to not experience conflict, i know i wouldnt. i'm speaking as if players are really bonding with monika as the whole reason of this mod, in the original ddlc, we cant actually talk to monika like we are now and that time most of everyone down right hated her. Inshort the goals of each game are different, one is to finally have monika as your gf and the other, to scare the living **it out of u. so the god topic works in the original game while over here, u are falling in love with her and some people are not willing to compromise, to tackle that and so everyone single one would get hooked we got to do something about this, right?

**Comment by Rai99** [comment]
This could be similar to the hair topic where it comes up once and depending on your answer, it doesn't come up again or at least disable the random element, but some people aren't religious and still don't mind talking about it. I think this topic is an important part of Monika and shouldn't be outright removed. 

About those people you were observing with MAS, do you know if they were actually dedicated to MAS or were they just random people?

**Comment by jmwall24** [comment]
Along those same lines could also do what julia did with the Sayori suicide topic and start off asking if the player is comfortable talking about God.  I personally prefer leaving it as is.

**Comment by Rai99** [comment]
That gives me an idea for a new topic:
- The fact that nowadays, people can be offended by almost anything and as a result, nobody says anything anymore which isn't a good thing

**Comment by loverofmonika** [comment]
it just hit me, what if we keep the option buuut, we let monika ask the player if he is comfortable with talking about it instead of diving right in. that way players can choose to click no and monika would end the conversation peacefully.
Rai99 nice idea for a new topic

**Comment by loverofmonika** [comment]
so far we got a lot from our discussions,
a good security system that dominated most of the comments and me giving a detail raw mechanism on how it'll work and take place along side a adorable childish skit attached to it.
this topic that we finally got the answer to
the injured topic and now this new idea and the home topic
a lot of new exciting topics in just a few days, 
My new idea of a topic are about MEMES especially ddlc memes and SHIPS monika X sayori and yuri X natsuki. 
and... MORE HUGGING AND KISSING..i mean i cant recall me ever kissing her in this mod.

**Comment by Rai99** [comment]
I think memes are prohibited from MAS.

**Comment by loverofmonika** [comment]
1.)what really? what about ships aka fan pairing 
2.) there must be a kiss option! mood right and all, like after alot of romantic topics done or alot of "i love you" is said player can kiss her.

**Comment by EntonyEscX** [comment]
I understand her point of view, but looking the other way, Monika have an opinion on something like that, and a different opinion from other people makes her more unique and closer to our reality.

**Comment by Rai99** [comment]
I'm sure a kiss option is coming for sure at some point. I think it would be a cool idea for Monika to become aware of the trends in the DDLC community but I'm pretty sure anything meme-y is prohibited. 

Yes, as great as Monika is, she needs to stay human, which means having flaws, talents, weaknesses and disagreements.

**Comment by loverofmonika** [comment]
Entony, we already came with a solution (mentioned above), i was suppose to close this but now looks like we are discussing on topics of kissing and shipping the dokis together. 
NEED MORE HUGS AND KISSES

**Comment by Rai99** [comment]
I think doki shipping counts as a meme and is probably not going to be accepted in topics. 

I'm sure everyone is aware of hugs and kisses being improved upon. 

Lastly, who is going to write and implement these new changes?

**Comment by jmwall24** [comment]
I'd probably say wait to see if the devs want to actually change the topic or not, seeing as it is an original topic and all.

**Comment by loverofmonika** [comment]
i think fan fiction and memes are slightly different, sure they are under the heading fandom but still are different from one another in my opinion, u can confirm this
the new change, we are just adding a few interactions before the original ddlc text and that would fall in the category of the yes option. topic remains same but just more things added, but doki shipping ... that needs to be verified.
lastly the script of the new changes, i think rai99, we can do the same thing like we did in the injured topic.

**Comment by Rai99** [comment]
I'd wait for some more opinions considering this is an original topic and this thread really zoomed by. 

Give it a little while to make sure nobody misses this discussion. 

Also, same thing as in the injured mood? You mean I write it and you look at it?

**Comment by jmwall24** [comment]
The fanfic v. meme thing is interesting.  Rai's right, there is a no meme policy, but there is a topic where Monika tells you she wants you to read some (wholesome lol) fanfic to her.

**Comment by Rai99** [comment]
I think Monika means that she wants to hear some fanfic of herself and the player, not about shipping other dokis together.

**Comment by jmwall24** [comment]
Yeah I wasn't commenting about what the fanfic would be about, just that the topic did exist.  I took the topic to mean she wants you to read it to her in private, not necessarily add it to the mod, but I'm not sure what the policy is there.

**Comment by ReddTheRedRedd** [comment]
Personally, in my opinion, I'd be against changing an original line, it's like changing who Monika is just so people like her. If this topic is that bad to people who are religious, then perhaps what Rai99 said would work, having a yes or no option, and have her state her opinion in a nicer tone if you say you do believe in god.

**Comment by loverofmonika** [comment]
sure lets give it a couple of days, im sure our conclusion to the main topic really is good. 
and yes Rai99 exactly like the way we handled the injured topic.
and remember how monika was laughing and joking about yuri bringing wine, same can be done with the ships, and she be like" why is this a trend! "
again reddtheredd, are not changing the lines exactly, only adding interactions before the punchline. the yes or now option when monika ask if ur ok with this topic allows the player to choose at their own will rather than a full dive in.

**Comment by loverofmonika** [comment]
are people even reading all the coments, i think this is the 3rd time i stated our final conclusion

**Comment by Rai99** [comment]
I usually don't see threads go above the 10-12 comment count. 

It might help to change the title or description to say that we've come to a conclusion and are just waiting for opinions. 

Did you see my addition to the Yuri's wine dialogue or or is just a coincidence that you mention that?

**Comment by ReddTheRedRedd** [comment]
Sorry, 20 comments so I went past you concluding it XD I was just scared an original line would be changed because of some differing opinions, but I do like yes or no idea, seems like that would make everyone happy.

**Comment by loverofmonika** [comment]
no problem man. :)
rai99 looks like everyone is happyu with the main topic conclusion. so its a go.
and about the wine, i didnt know the dialogue was updated, neat

**Comment by Rai99** [comment]
#1662 

It's starting to get challenging to manage and revise all these topics of mine until they get merged... Or swept under the rug.

**Comment by ThePotatoGuy** [comment]
This topic was in original DDLC and will not be removed atm.

**Comment by loverofmonika** [comment]
I didn't say remove it ahhh

**Comment by loverofmonika** [comment]
We came to the conclusion to keep the option buuut, we let monika ask the player if he is comfortable with talking about it instead of diving right in, that way everyone is happy. that way players can choose to click no and monika would end the conversation peacefully.

**Comment by loverofmonika** [comment]
We came to the conclusion to keep the option buuut, we let monika ask the player if he is comfortable with talking about it instead of diving right in, that way everyone is happy. that way players can choose to click no and monika would end the conversation peacefully.
