### ISSUE TITLE
Monika's individuality and thoughts on other Monikas

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#1729]
Hi, this is my first contribution attempt. I'm still new to Github and coding, so I wanted to drop this dialogue for a new event to see what people thought and get some feedback.

I also wasn't sure how to make it into the .rpy format that I see other posts use, so I just use a text file here instead.

I'm guessing that eventually affection will be implemented, so I added some comment lines about it should that feature go live.

[Individuality_with_sprite_codes.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2087258/Individuality_with_sprite_codes.txt)

**Comment by Rai99** [comment]
I would wait until affection gets implemented and see how it works before making anything that has to do with it, but that's just me. 

I think the dialogue options could be changed to be a bit more fleshed out but it looks like a good concept.

**Comment by CrocWorks** [comment]
Alright, I'll just close this now and revisit it when the affection mechanic is live.

**Comment by CrocWorks** [comment]
Welp, affection is out now, so I guess I'll reopen this. The text file uses the old sprite codes, though. Is there a database that shows all the new sprites and the codes that call them?

**Comment by aldoram5** [comment]
Hi CrocWorks!
You can see the new sprites with their codes by reading and following the instructions [here on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/blob/master/FAQ.md#how-do-i-find-the-spritecode-for-an-expression).
As for contributions we expect them in the form of pull requests, read our [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines). Once you send us one it'll be reviewed by us(there we can check your questions about how to work with affection).

**Comment by CrocWorks** [comment]
Cool! Thanks for the links.

**Comment by CrocWorks** [comment]
I don't think I'm gonna submit this now that I think about it. The text seems more like a "finale" conversation and Monika just gets handed an answer too quickly. We want MAS to last, after all.
