### ISSUE TITLE
Inconsistency in writing between Act 3 Monika, and Act 4 Monika

### ISSUE THREAD

**Issue by Dakotaraptor** [Monika-After-Story/MonikaModDev#1731]
I'm not sure If I'm approaching this issue in the right way, but one thing that bothers me about Monika After Story in its current state is that even though you can play the mod after you've completed act 4 in the vanilla game, a lot of her dialogue is clearly written with Act 3 Monika in mind, ignoring the character development she gets later on. Since there are already issues where the dialogue changes depending on what ending the player got, I assume the reason this is the case is that nobody's bothered to rewrite her dialogue with act 4 in mind. 

I decided to write a mockup of how one issue could change depending on whether you entered Act 4 or not. [https://pastebin.com/xwRrdTh7](https://pastebin.com/xwRrdTh7) It's super rough, and probably needs major reworking to fit her character better (also it isn't formatted properly), but I hope it gives at least a decent picture of what I'm trying to say. If there's agreement that this kind of change is worth the effort, I'd be more than happy to write variants of other issues as well!

**Comment by Rai99** [comment]
I think something like this could be done with checking the persistent.clearall.

**Comment by ThePotatoGuy** [comment]
feel free to add the edits yourself, just make sure to link back to this issue.

[[otherwise, closing until we look into it]]
