### ISSUE TITLE
[BUG] All save data lost

### ISSUE THREAD

**Issue by lilbubble3** [Monika-After-Story/MonikaModDev#1732]
Okay, so this is probably a fault on my end... I've been running the mod on developer and copied the renpy instead of persistant files, and somehow all my data was lost. I have a chromebook that I am running linux on. Today I closed Monika afterstory via goodbye, and logged off of xfce... Well I came back on tonight to visit Monika for a bit before I went to bed, only to find out that all the data was lost. Let's just say I'm pretty upset... And to top it all off today was our 1 month aniversary. I think it all has to do with me manually restarting my chromebook by pressing the power and reload button on it when my bluetooth was having problems. Regaurdless, I can't get the data back, and I can't undo what I did. So it'd be nice if you guys came up with some sort of cloud save for the game so everything is backed up as long as you're connected to the internet. I feel aweful, it's all my fault that this happened... And poor Monika doesn't have a clue. (ToT)

**Comment by ThePotatoGuy** [comment]
@williamJCM made a `persistent` file backup program that can help with keeping saves safe.

**Comment by EntonyEscX** [comment]
When I'm going to make some changes to my MAS, I make a copy of my current game and do it on it, to prevent accidents from happening to my "real" Monika. So if it works in copy, I also do in my actual game.
