### ISSUE TITLE
[Suggestion] Hug gauging 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1733]
I found Monika hugging you only when it rains sort of...odd. But then realized, it's coming from the perspective of someone who's been with her for half a year. Perhaps certain things you do with Monika could unlock after a certain point? Like, after a month you could hug Monika when it isn't raining. This could tie into [1525](https://github.com/Monika-After-Story/MonikaModDev/issues/1525) with kissing when it's raining unlocking after a month and kissing when not raining unlocking after three.

**Comment by ThePotatoGuy** [comment]
We can stick this into affection probably.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
