### ISSUE TITLE
Monika's opinions on Dan

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1734]
If you ask Monika who Dan is she has a positive opinion of him. However, in the actual Act 3 dialogue concerning God, she doesn't seem to be too fond of him. I think her opinions should be changed to something along the lines of more contempt for someone who put her in her situation.

**Comment by kaido1224** [comment]
Yeah i brought this up already. 
https://github.com/Monika-After-Story/MonikaModDev/issues/1599

It's a duplicate

**Comment by ThePotatoGuy** [comment]
[Closing because duplicate]
