### ISSUE TITLE
Is it possible to speed up Monika's text even further? [Suggestion]

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#1735]
I'm a pretty quick reader, so often when Monika does a repeat topic I feel like I have to wait forever for her to finish. Even when it's a new topic, I still find the text for Monika's talking to be much slower than my reading speed, so if the max speed could be increased, that'd be great. (Too be honest, I'm not even sure if the text speed slider in settings does anything... At least I don't notice much of a difference)

**Comment by Akito98** [comment]
The speed slider is indeed disabled, you can't change the text speed.
see #996 and #731.

**Comment by Onion-Bubs** [comment]
What you can do is download and install a dev version of MAS. The text speed slider works as normal on that.
