### ISSUE TITLE
player's birthday and monika's birthday 

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1740]
I played around with the I feel like a year older option and found out that the next time ur birthday comes, monika greets u but that's it. I thought there would be something special for such an occasion. Another thing is monika got nothing for her own bday. Any suggestions. ( my bday is coming soon too so  yeaaa kinda want to upgrade it)

**Comment by ThePotatoGuy** [comment]
the "feel like a year older" is just a placeholder to store your birthday / involve a birthday in an interaction until calendar comes out.

It will most likely be either removed or completely changed with calendar.

And ofc we will do something for monika's birthday.
