### ISSUE TITLE
[Suggestion] Emotions applied to speach

### ISSUE THREAD

**Issue by lsmine0** [Monika-After-Story/MonikaModDev#1742]
I had an idea to add few randomizes and values as her emotions, in that way there can be multiple responses to one question and many groups of random questions to Monika talking also some more variance of every of her line witch would make her seam more emotional.

**Comment by lsmine0** [comment]
also there can be emotes and reaction to users mouse location or active programs in background
witch could add more of her personality to live

**Comment by lsmine0** [comment]
every action user takes will change values also time of her being turned off and how much do you ask or play games with her could be also a value witch makes her more real of a person

**Comment by lsmine0** [comment]
there would be one randomiser for multiplying the effects of emotions in talk

**Comment by lsmine0** [comment]
there also should be multiple default states of her in different moods when she stops talking she stays like a statue until she talks

**Comment by ThePotatoGuy** [comment]
1. Varying lines of dialogue on emotions can be done in small amounts, but if you're implying that _the majority_ of dialogue should have adjustments based on emotion, you're welcome to modify the 7k+ lines of dialogue yourself. It's not feasible to implement such a feature without going to an chatbot/ai-style setup, which is not currently planned atm.

2. We will be adding more interactivity with mouse stuff soon. We are **not** going to support running MAS as a background process. If you want that, use MonikAI.

3. The affection update will track user action in a way and affect certain bits of dialogue as well as control what topics are available.

4. See 1.

5. We could look into pose variety during idle.

**Comment by lsmine0** [comment]
what i meant by active programs is cheeking the names of the program and react to it
like she would be asking what you drawing in gimp
or what are you listening to

**Comment by lsmine0** [comment]
the dialogue is to much to convert but to just group it to different moods

**Comment by lsmine0** [comment]
also there was something about kitchen and cooking

**Comment by lsmine0** [comment]
there can be a random event on startup when she trys to make something or find a recipe for something or anything like that

**Comment by ThePotatoGuy** [comment]
2. Program checking can be done, we'll add stuff like that when it makes sense. Currently there's one for a certain monika-related program.

6. cooking sounds like a neat topic idea.
