### ISSUE TITLE
[Suggestion] Gift choices for Monika

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1743]
I've been thinking about it lately, on Valentine's Day I wanted to give white roses to Monika, but since there was no option for that choice, I had to give red roses like the other players. So I've been thinking, I think it would be cool if on the next Valentine's Day, or even on Monika's birthday, players had the option to choose just one gift from a list, so each player could gift your Monika with the gift he would like to give.

**Comment by ThePotatoGuy** [comment]
[Closnig until we look into this]
