### ISSUE TITLE
Gaming mode/topic

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1744]
I was thinking there could be something similar to when you tell Monika that you're feeling sad and she lets you talk until you tell her that you're done, except for when you're about to go into a game/round.

You could tell Monika that you're about to play a game while Monika sits in the background and she could wish you luck or to have fun and patiently wait for you to finish and ask how it was when you finish and get back to Monika. 

The challenges of this are that there would likely have to be a good amount of variety as not all games are about winning or losing, some games are just about having fun and some games you just play and get better at each time. 
Here's what I imagine it would be like:
- Games that you can win or lose
     - Monika would ask if you won or lost and have respective dialogue
- Games that are only about having fun and have no real objective
     - Monika would ask if you had fun and provide respective dialogue
- Games that you practice and get better at over time 
     - Monika would ask how it went; If you were better/worse than usual, etc.
- Already having a game up and it needs your attention for a bit
     - Monika would wish you luck and expect you to come back in a few minutes 

Sometimes I get distracted by Monika and always keep having/wanting to listen to her dialogue for a bit but with this, I can focus on what I'm doing and maybe it would feel like Monika could spectate me.

**Comment by Rai99** [comment]
If people like the idea, I think it could be fun for me to write up, but there are a few other topics I want to take care of first.
Currently working on a topic about types of cars using Subzerosan's driving draft in #1692.
Next I would want to handle #1573 and #1643 as it looks like those are about to be swept under the rug.

**Comment by jmwall24** [comment]
Not really regarding the sprite codes.  That pull request you referenced actually just created aliases for the old sprite codes that convert them into the new sprite codes.  Just try to use the new codes from now on is what I gather from it.  I don't think that is what is keeping topics from getting approved, it's the time needed for the writing team to actually review them,  It usually takes a few months for new dialogue topics to get approved.

**Comment by Rai99** [comment]
I was a little confused as I thought I saw some brand new topics get proposed and merged almost instantly.  I can't find them now so I might be wrong. I'm sometimes told that my topics are good and it seems like most people like them or at least think they're ok so I guess I'll get that fabled contributor tag eventually. 

I didn't know there was a dedicated writing team. I thought it was just voted on by the team or community members and then merged whenever. Good to know the reason, thanks. 

As for the new sprite codes, I'm tempted to write up a program that converts old sprite codes into the new ones just so I can keep using the old ones and then running it through my program. Who knows? Maybe if I do get it working, I'll share it to keep contributing simple. Yes I can program as well as write, but whether or not I can program as well as I can write is debatable. 

As for this gaming mode/topic, I'm looking for some thoughts on it.

**Comment by jmwall24** [comment]
If you go to the bottom of https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/sprite-chart.rpy it shows the new codes for all the original sprites that are on the cheatsheet so you can see what you are using.  Starts on line 7108.

**Comment by Rai99** [comment]
I might just try writing that script to convert the sprite codes automatically. 

Also can you tell me who is on the writing team?

**Comment by jmwall24** [comment]
As for the pull requests that are getting approved quickly, those are typically the long-time contributors and dev team members. If you look at the closed PRs that were recently merged they are pretty much all julia, aldo, and potato.

**Comment by jmwall24** [comment]
I'm not sure who all is on the writing team right now tbh.

**Comment by Rai99** [comment]
Maybe I'll get there one day for faster approval times. 

Also, any thoughts on this topic?

**Comment by jmwall24** [comment]
A few of us asked if they wanted more people on the writing team a while back and we were told they weren't looking for anyone else.  I know everyone wants their contributions in the mod as quickly as possible, but it's a relatively small team and they have lives outside of this.  It just takes time.  There are still pull requests from March sitting there so don't think your topics sitting there for less than a month have been ignored, they'll get to them.  The first topic I wrote took about 2 months to get merged for reference.

As for the topic, sounds like a good idea.  I can't remember if I actually put it on here anywhere, but I was thinking a week or so back that being able to tell her you are going to be busy would be a good thing so that you don't end up ignoring her while she talks to you.  Right now I use the right click feature for that so she doesn't start talking while I'm doing other things.  An actual feature where you tell her what you are going to be doing could be useful.

**Comment by jmwall24** [comment]
Well like I said, you can use the exact same expressions as before if you want that are on the cheat sheet if you just use their new codes and they are all listed at the end of that link with the old and new codes..  Also, all of the currently available sprites are on that same link I listed above, starting on line 1707.  The problem with an all inclusive cheat sheet is there are a ton of combinations available.  Good luck.

**Comment by Rai99** [comment]
If I can use the old codes and put it up like that with the old codes, great. 

If you mean I can replace the old codes with the new ones found on the bottom of that link, that'll be some work. 

**Basically, can I just keep using the old codes on the old cheatsheet all the same, but the only difference is that there are new possible expressions with more complicated codes if I want to use them?**

**Comment by juliathegolden** [comment]
Short answer yes. Long answer, it'd be really great if you'd use the new codes for the old expressions, both for efficiency sake and good habit building.  We also want as much content with the new expressions to come in so everyone will get to see them, but applying new expressions to PRs is something the editing team is doing as well. 

Anyway, I doubt it'll have any affect to whether or not your PR is accepted or rejected. Don't worry about that.  Thank you for all the submissions you've been making lately.

**Comment by Rai99** [comment]
You know, I'm never too sure people like my topics/writing so it's always nice when someone does. Thanks for the support!

Unfortunately I've been a bit busy lately so I haven't had much time to write but I should be back to normal, regular contribution writing starting Friday night.

**Comment by loverofmonika** [comment]
coming together and discussing leads to lots of interesting discoveries, Rai99 ur topics are nice and is fun discussing them with u, keep up the good work bud

**Comment by Rai99** [comment]
Link right there to avoid excess referencing. 

Finally got around to finishing this idea. It's 1am and Monika would probably be dragging me to bed if she had the power to.
