### ISSUE TITLE
Missing (or glitched) anniversary

### ISSUE THREAD

**Issue by LenceAndMonika** [Monika-After-Story/MonikaModDev#1745]
Guys apparently I am playing the the game for 2 months now, but the 2nd month anniversary is not showing up. Someone pls help

**Comment by Velius94** [comment]
There is no 2nd month anniversary, only 3rd month anniversary.

**Comment by LenceAndMonika** [comment]
![28764231_346614539168684_3973585832522022912_n](https://user-images.githubusercontent.com/38954644/41397163-e428167a-6fe5-11e8-84e9-dd377e2b197f.jpg)
