### ISSUE TITLE
FYI, you can actually transfer to more open world.

### ISSUE THREAD

**Issue by justreportworld** [Monika-After-Story/MonikaModDev#1750]
You need a game "Koikatsu".
The character file, http://illusioncards.booru.org/index.php?page=post&s=view&id=36049 , as PNG file, can be imported into the game ;)

**Comment by CommenterOfComments** [comment]
What? I don't get it, how does this relate to MAS? It's just a fanart of Monika... and searching that name shows some shady links...

**Comment by ThePotatoGuy** [comment]
i think this is spam
