### ISSUE TITLE
[Bug] - Monday morning greeting

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#1753]
So, I ran and quit MAS 3 times in a short timespan (about a minute) and got the Monday morning greeting, unexpectedly, since it is Friday evening at the moment.

**Comment by jmwall24** [comment]
Yeah, that's the same bug as #1612 and it has been fixed in #1727.  Should be good to go next release.

**Comment by ThePotatoGuy** [comment]
[[Has already been fixed]]
