### ISSUE TITLE
0.8.2 Typos

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#1757]
put typos here (for 0.8.2 and pre-releases)

**Comment by Dakotaraptor** [comment]
[https://pasteboard.co/HqlKojF.png](https://pasteboard.co/HqlKojF.png) Should be "pets", not "pet"

**Comment by neyoriquans** [comment]
I got this greeting from Monika today but I think it should say "Best thing to do after a long day *at work*, don't you think?" since it was a greeting talking about work and how my day went. 

![image](https://user-images.githubusercontent.com/36655331/41517382-8622c192-7288-11e8-815a-e9caa9f4871f.png)

**Comment by Rai99** [comment]
Either just long day, or: of, from, at work I think. 

I think long day _of_ or _at_ work sounds more natural than from.

**Comment by Velius94** [comment]
The monday morning greeting has a lot of stylistic problems. I know it's PH, but whatever, I'll mention it anyway.

'label greeting_monika_monday_morning:
    m "Another monday morning, eh [player]?"
    m 1r "It surely sucks to wake up and start off the week ..."
    m 1 "But seeing you makes all that laziness go away"
    m 1k "You are the sunshine that wakes me up every morning!"
    m "I love you so much, [player]~"
return'

Correct form would be:

`label greeting_monika_monday_morning:
    m "Another Monday morning, eh, [player]?"
    m 1r "It surely sucks to wake up and start off the week..."
    m 1 "But seeing you makes all that laziness go away."
    m 1k "You are the sunshine that wakes me up every morning!"
    m "I love you so much, [player]~"
return`
