### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1769]
Ever since downloading the 0.8.2 update I am experiencing very noticeable lag when Monika is talking that I have never seen before.  I have tried every rendering mode and it happens on each one.  Wonder if the new auto-save feature isn't causing this?

**Comment by jmwall24** [comment]
The direct x setting seems to be the best, but that may just be coincidence.  The window animations lag as well as Monika talking when it does it.

**Comment by jmwall24** [comment]
It's possible it was just REALLY unfortunate timing and something else was going on on my pc when it was really bad.  It's just the fact that it started happening immediately after installing the update and had never happened before in 5 months that got me worried it had something to do with the update.  And I have a hard time believing my pc can't keep up with MAS, I play some pretty new graphic-intensive games on the highest settings with no lag.  

Anyhow thanks for looking into it (and the discord chat) and I'll monitor it on my end and provide any info I can.

**Comment by ReddTheRedRedd** [comment]
May not have been, I'm having some lag as well after the update.

**Comment by jmwall24** [comment]
It's coming and going, even on the direct x setting.  For a while it's fine, then get bad spells.  Really strange.

**Comment by MaximumRustler** [comment]
I'm having the same problem, tried using direct x and open gl mode. I don't think it's my pc because I have a ryzen 5 1600 and a 980ti...

**Comment by jmwall24** [comment]
Still doing it today.  Had task manager up to see if there are any spikes when it happens and don't notice any CPU or Memory spikes.  Not even remotely close to using up all my resources so really don't know why it does it.  I've got a i7-7700 3.6 GHz and the overclocked 1050ti (not quite the 980ti but plenty for this).  I've got 2 monitors hooked up to it, and up until yesterday I could play another game on one monitor while talking to Monika on the other monitor and had zero lag on either game running simultaneously.  Now MAS by itself lags so I'm at a loss.

**Comment by MaximumRustler** [comment]
Hmm... I noticed that the cpu usage does go up a bit when it lags but not much, it went to like %13 where normally besides that it's below %10. That wouldn't be enough to make it lag. Otherwise all of my other hardware seems to be performing normally. I also noticed on the longer topics it tends to smooth out, even if it starts out rough.

**Comment by jmwall24** [comment]
My cpu usage sits between 6 and 8% when running MAS and a browser only, with MAS taking up 3 to 5%.  A few times it lagged it was at 8% but other times it stayed at like 6%.  Wasn't consistent enough to form a correlation on my end.

**Comment by MaximumRustler** [comment]
Yeah it wasn't consistent on my end either. It also sometimes lags when I open up the start menu (where history, settings, etc. is). I also tried opening and closing different menus and alt tab out and then back in, doesn't seem to make a difference. I use fullscreen, what do you use?

**Comment by ReddTheRedRedd** [comment]
It's lagging on windowed as well, on my end atleast.

**Comment by jmwall24** [comment]
Windowed here

**Comment by MaximumRustler** [comment]
Huh... interesting, I look forward to the results! lol

**Comment by ReddTheRedRedd** [comment]
Hmm, Monika must have been trying to code in some buttons, but coded in bombs instead.

**Comment by jmwall24** [comment]
Awesome

**Comment by ThePotatoGuy** [comment]
[[We are looking at additional optimizations, but the last set should be enough for the time being. Closing this]]
