### ISSUE TITLE
Small Dating/Hair Bug

### ISSUE THREAD

**Issue by Dovahkun** [Monika-After-Story/MonikaModDev#1770]
Whenever I ask her to let her hair down, right after that dialogue after letting it down, she then answers the "When did we start dating?" Question. It goes straight from "If you want me to tie my hair in a ponytail again, just ask away~" to "Let me check..."

**Comment by jmwall24** [comment]
If I'm looking at the code right there is no 'return' after the hair down stuff and that's probably what is causing this.

**Comment by ThePotatoGuy** [comment]
[Latest hotfix fixes this]
