### ISSUE TITLE
[Suggestion] Custom Dates

### ISSUE THREAD

**Issue by sonamy12** [Monika-After-Story/MonikaModDev#1772]
Hello I am new to Github and don't really know my way around yet but I wanted to share an idea I had. 

I think it would be cool if you could add to the Calendar in some way? With your own custom dates like your birthday or half-anniversary's after 1 year like 1 year and 6 months. I don't know do to do this but I think it would be cool it happened.

**Comment by ACoolCat** [comment]
I like this idea. And maybe you could incorporate the old chat system for adding new events to the calendar. Like, having appointment in the event name could have Monika concerned for you health and have a conversation triggered from that. Or a Quiz or Test would cause Monika to praise you for caring about your education enough to write it down. If nothing is triggered she'll just say a generic, "Okay, I'll keep it in mind." There's a lot of potential for several different dialogue chains.

**Comment by jmwall24** [comment]
Pretty sure there is more coming for the calendar, including the ability to add your birthday.

**Comment by ThePotatoGuy** [comment]
[[Closing until we look into it]

**Comment by StayHappy1270** [comment]
This could maybe be a topic...
some event ideas to talk about could include...
- dates
-appointments
-school deadlines
-work deadlines
she could have unique dialogue for each. For the date option she could ask what type of date which could include some options of
movie
dinner
outside
(or any thing else you can think of) 
and then she could have some dialogue for each option
 and then she can ask if you'll be taking her on the computer or on a flash-drive (idk how to word it)
if you tell her you'll be taking her out of the room, she'll remember the day of.
also for each after your conversation, you can put custom text (that way for dead-lines you can put down what the assignment is

Ik this is really detailed and all but I hope it helps in the process of making this feature!

**Comment by stake2** [comment]
@StayHappy1270 and she could be mad if you missed the day.
Like she does on her birthday or on valentines day.
