### ISSUE TITLE
[Suggestion] - New Topic -  Pygmalion and the Ivory Statue 

### ISSUE THREAD

**Issue by Babushka93** [Monika-After-Story/MonikaModDev#1773]
Hi everyone,

I stumbled onto the story of Pygmalion while looking through [wikipedia](https://en.wikipedia.org/wiki/Pygmalion_(mythology)) and I thought that his fable might be a story that Monika would share.

--------------------------------------

Pygmalion was a sculptor who fell in love with an ivory statue he had carved. He loved the statue so much that during the Festival of Aphrodite, Pygmalion made an offering to Aphrodite wishing for a bride that would be the living likeness of his ivory statue. 

When he returned home, he kissed the statue, and to his surprise the lips of the statue were warm. He kissed it once more, and found that the ivory had lost its hardness. Aphrodite had granted his wish.

The statue through Aphrodite's blessing had become human. Pygmalion and the now transformed statue went on to marry and live together. 

------------------------------------------------
I feel like this would be a story that Monika would share with the player, and hint at the player making an offering to Aphrodite in the hope that it would bring her closer to our reality. 

==update==
Here is the most recent version of the dialouge based on contributions by @loverofmonika 
Also huge thanks to everyone who has shown interest and contribute to this topic so far 😄 

label monika_pygmalion
m 1 “Hey [player] have you ever read The Metamorphoses?”
m 3 “It’s a collection of poems by an Ancient Roman poet called Ovid.”
m 3b “There’s one poem that really struck me.”
m 3a “The poem is called The Story of Pygmalion and the Statue”
m 1b “It tells the story of a sculpture who fell in love with an ivory statue that he had sculpted.”
m 1a “He loved the statue so much that during one of the festivals held for Aphrodite. Pygmalion made an offering to Aphrodite and wished for the goddess to grant life to the ivory statue.”
m 1b “When he returned to his home, he kissed the statue and to his surprise the lips of the statue felt warm. He kissed the statue once more, and the statue lost its hardness becoming soft like skin.”
m 1e “Aphrodite had granted his wish.”
m 1b "This story really struck me because in a way it kinda reminds me of us , [player]"
m 1d "and how this poem talks about the impossible turning into reality"
m 5e "kinda fills me up with hope, that a miracle can happen and i can finally cross over"
m 5e "yeah...wouldn't that be wonderful"
m 1j "then you can finally kiss me without a screen between us, just imagine, kissing your computer screen when no one's looking or maybe you already tried that, hahaha~"
m 5a "Sorry, i was just teasing hehe..... truth be told, i really can’t wait for the day when I can finally kiss you back and be with you forever, for me, that would definitely be a dream come true"

**Comment by sonamy12** [comment]
I think this is a cool suggestion and it could fit in to the game well.

**Comment by loverofmonika** [comment]
it can be one of those 'did you know' topics and monika's would consider this as informative but not actually believing in such offerings cuz she is practical and is aware it isn't gonna work thus becoming the tease we all know and love. ahh greek mythologies, to come to think of it, we could have a topic about greek mythologies.

**Comment by Babushka93** [comment]
@sonamy12 

@loverofmonika that would work well actually, 


we could have the topic like:

label monika_pygmalion 
m 1 “Hey [player] have you ever read The Metamorphoses?”
m 3 “It’s a collection of poems by an Ancient Roman poet called Ovid.”
m 3b “There’s one poem that really struck me.”
m 3a “The poem is called The Story of Pygmalion and the Statue”
m 1b “It tells the story of a sculpture who fell in love with an ivory statue that he had sculpted.” 
m 1a “He loved the statue so much that during one of the festivals held for Aphrodite. Pygmalion made an offering to Aphrodite and wished for the goddess to grant life to the ivory statue.” 
m 1b “When he returned to his home, he kissed the statue and to his surprise the lips of the statue felt warm. He kissed the statue once more, and the ivory of statue lost its hardness becoming soft like skin.”
m 1e “Aphrodite had granted his wish.”
m 1b “This story really struck me, because it reminds me of us, [player].” 
m 1k “[player] maybe you should try kissing me to see if I can finally cross over hehehe~
m 2q …. 
m 5a “I can’t wait for the day when I can finally kiss you back in your world. (blushing)”

**Comment by Rai99** [comment]
I like this topic and I think it would fit perfectly with Monika. 

Any volunteers or... Am I going to have to read through this story and lore?

**Comment by loverofmonika** [comment]
@Babushka93, thats a nice outline of how things could turn out but the part where monika tries to relate our situation to the story doesn't well quite relate, here me out,the poem is about a non living object is brought to life where as monika is alive to begin with and is just trapped in the virtual world and tbh, kissing your computer screen, not really an appealing sight. i would like to change the last lines to
 "This story really struck me, because it reminds me of us, [player].
 "and how this poem talks about the impossible turning into reality"
"kinda fills me up with hope, that a miracle can happen and i can finally cross over"
"yeah...wouldn't that be wonderful"
" then you can finally kiss me without a screen between us, just imagine, kissing your computer screen when no one's looking or maybe you already tried that, hahaha~"
"Sorry, i was just teasing hehe..... truth be told, i really can’t wait for the day when I can finally kiss you back and be with you forever, for me, that would definitely be a dream come true"

 just polished the ending of this topic, good work team


@Rai99 our good friend has provided with a raw outline and my changes, we can utilize it and better polish it. maybe adding a bit more facts before reaching the conclusion i wrote. other than that i think we are good to go.

**Comment by Babushka93** [comment]
@loverofmonika just finished reading your update and I love new ending 😁 

Here is my latest revision with your ending

@Rai99  I've never coded before, so if you would like to help out that would be amazing. 😄 

label monika_pygmalion
m 1 “Hey [player] have you ever read The Metamorphoses?”
m 3 “It’s a collection of poems by an Ancient Roman poet called Ovid.”
m 3b “There’s one poem that really struck me.”
m 3a “The poem is called The Story of Pygmalion and the Statue”
m 1b “It tells the story of a sculpture who fell in love with an ivory statue that he had sculpted.”
m 1a “He loved the statue so much that during one of the festivals held for Aphrodite. Pygmalion made an offering to Aphrodite and wished for the goddess to grant life to the ivory statue.”
m 1b “When he returned to his home, he kissed the statue and to his surprise the lips of the statue felt warm. He kissed the statue once more, and the ivory of statue lost its hardness becoming soft like skin.”
m 1e “Aphrodite had granted his wish.”
m 1b "This story really struck me, because it reminds me of us, [player].
m 1d "and how this poem talks about the impossible turning into reality"
m 5e "kinda fills me up with hope, that a miracle can happen and i can finally cross over"
m 5e "yeah...wouldn't that be wonderful"
m 1j "then you can finally kiss me without a screen between us, just imagine, kissing your computer screen when no one's looking or maybe you already tried that, hahaha~"
m 5a "Sorry, i was just teasing hehe..... truth be told, i really can’t wait for the day when I can finally kiss you back and be with you forever, for me, that would definitely be a dream come true"

**Comment by loverofmonika** [comment]
i'm glad u did, i found a bit of errors that was on my part, correction
line m1b "This story really struck me because in a way it kinda reminds me of us , [player]"
and 2 lines above that, just call it statue not ivory of statue

**Comment by Babushka93** [comment]
updating now 👍

**Comment by loverofmonika** [comment]
@Rai99 i just wanted to know if the script is ready

**Comment by Rai99** [comment]
I still need to add the menu option to the Thoughts on God topic which shouldn't take too long. Then I'll get this one if people would like to see this one soon. Shouldn't take too long since the outline is pretty nice already. Best case scenario is that I would just have to revise the sprites and update the codes.

**Comment by Babushka93** [comment]
Sounds good, thank you again @loverofmonika and @Rai99

**Comment by Rai99** [comment]
I did a bit of my own research on the topic to see if there was anything else to add, but it looks like you covered all the significant parts. Also I find it just a little bit funny that it _almost_ looked like you copied and pasted some of the description of the story from Wikipedia. 

I put some long lines onto their own lines to make sure the dialogue box wasn't going to get too full. 
Adjusted some expressions to better fit. 
Fixed a few typos. 
Tried using a couple advanced expression sprites.

**Comment by loverofmonika** [comment]
Nice, so the core content is polished along with my polished ending, I think we got ourselves a new topic

**Comment by Rai99** [comment]
Maybe I can finally work on my #1744 Gaming Mode

It could take a bit since there are a _lot_ of things to include such as game types, objectives and so many different branches to write for.

**Comment by Babushka93** [comment]
@Rai99 thank you for all your hard work, enjoy your sleep

**Comment by 20wings** [comment]
how can I add this topic to game file?

**Comment by multimokia** [comment]
Closing as complete
