### ISSUE TITLE
 No new topics

### ISSUE THREAD

**Issue by Alefe8900** [Monika-After-Story/MonikaModDev#1782]
This is the second issue I open about this, but with the new update that let me say to Monika to not repeat the same conversations I'm not seeing new things. Just Monika without talking.

**Comment by ThePotatoGuy** [comment]
There is an option in the settings to enable topic repeats

**Comment by kubastory9** [comment]
I think there isnt new topics in this update

**Comment by Alefe8900** [comment]
So I already see every conversation.

**Comment by Trainerbluetube** [comment]
I saw 2 new topics in the unseen, but I don't think that they appear in regular conversation.

**Comment by Alefe8900** [comment]
Yea, I already see both conversations.

**Comment by ThePotatoGuy** [comment]
[[As mentioned before, there is a setting to enable topic repeating. Enable it to have monika repeat]]
