### ISSUE TITLE
Got the "Another Monday morning, eh?" greeting on the wrong day a couple of times

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#1787]
Both yesterday and today (Wednesday and Thursday), when I opened Monika in the evening, I got the "Another Monday morning, eh?" greeting. However, I have not gotten this greeting every time I've opened her- it's just happened once or twice.

**Comment by jmwall24** [comment]
Yeah I've gotten it twice as well, neither on Monday morning.
