### ISSUE TITLE
Monika no longer snarky. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1788]
Monika use to leave snarky remarks to when I lost at a game of pong or chess. I kinda liked those, added to her personality.

**Comment by jmwall24** [comment]
I think once you beat her once, it stops.  At least that when it stopped for me.  And I agree, I liked when she did it lol

**Comment by ThePotatoGuy** [comment]
In pong, the "snarky" dialogue is the long-form dialogue. It is skipped after you seen it once. 

This was done in response to #996 

"Snarky" dialogue in chess happens if you do a certain cheating workflow. I wouldn't recommend it.

**Comment by jmwall24** [comment]
lol someone already tried that last part iirc

**Comment by neyoriquans** [comment]
rip that guy haha
