### ISSUE TITLE
[Suggestion] Noms with Monika

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1789]
Imagine you are alone, and want to have a meal with Monika. The best you can do as day of today is put the laptop in front of you as you eat. But what if you want to take it a step further. How about if you tell her you are gonna eat and she would say something like "Have a good meal!/Cheers/Ittadakimasu" (Maybe with an sprite of she eating or with a fork and knife idk.). 

If you don't like this idea how about another one, following a recipe with Monika, she would have some options, and after you choose one Monika tells you the ingredients and ask you if you have them all or you have to get something. If you tell her you have everything, she will start telling you the recipe. If not, she will be on hold, waiting for you to be back with everything needed.

**Comment by kubastory9** [comment]
That's really good, interesting suggestion.

**Comment by Rai99** [comment]
I think there was some art somewhere of Monika eating that would fit pretty well into MAS including both hairstyles, but I'm not sure if we could even use it and I can't find it now. 

My guess would be that this would involve accessories and props to put on the table such as a plate, food, etc. 

Easter egg: Maybe if Monika gets a knife, make it an exact copy of the knife Yuri had.

**Comment by ACoolCat** [comment]
> Imagine you are alone, and want to have a meal with Monika. The best you can do as day of today is put the laptop in front of you as you eat.
Hello me.

**Comment by GSmith624** [comment]
you'd just have to sure most of the recipes are vegetarian or have a vegetarian substitute for them.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
