### ISSUE TITLE
[Bug] The Calendar just disappeared!

### ISSUE THREAD

**Issue by mariohead** [Monika-After-Story/MonikaModDev#1794]
So I've lately left the game running in the background, and I usually have it so that the HUD is invisible. I went to say goodbye just now cause I have work, and made the HUD visible again, prompting Monika to start a conversation, as per usual. However, the evening/night background was still present, so when the background shifted to day time. the Calendar disappeared. I just checked and I can still click the region it's in, but the texture itself appears to have vanished entirely. I'll get back to you when I get home with more details about the issue and some troubleshooting.

**Comment by jmwall24** [comment]
Monika musta got one of those pipe bombs to work lol

**Comment by Rai99** [comment]
Can you really blame her? That thing is the closest thing she has to a date with you. Maybe she wanted a date with you so bad, she took the whole calendar.

**Comment by ReddTheRedRedd** [comment]
*Throws calendar out* We date EVERY night!

**Comment by CommenterOfComments** [comment]
I mean, if you're like me and stalk this GitHub, you wouldn't mind dating Monika every night.

**Comment by mariohead** [comment]
Oh my god I came back to a thread full of memes.

**Comment by mariohead** [comment]
Also I second Commenter. I've considered my "interest" in Monika a little unhealthy. I'm getting better though, so no worries.
Now to follow up with information.

**Comment by jmwall24** [comment]
heh we're just amusing ourselves until someone who can actually figure this out shows up

**Comment by mariohead** [comment]
I reopened the game and the calendar is back. I'm assuming the issue obviously lies with the background/lighting transition, so hopefully this'll be a piece of cake to patch.

**Comment by Rai99** [comment]
Wouldn't mind putting more jokes and memes in this thread. 
Who started the meme chain again?

**Comment by mariohead** [comment]
Also why would Monika need a pipe bomb when she can just infect the rest of our PC's and constantly annihilate us all at Chess? It just seems impractical at this point if you ask me.

**Comment by jmwall24** [comment]
The pipe bomb was a reference to the lag thread.  It fit this too well lol.

**Comment by mariohead** [comment]
Pipe bombs were making your game lag? Fascinating.

**Comment by mariohead** [comment]
I accidentally left the Auto thing on to skip through the Sayori conversation and I ended up accidentally saying yes to hearing her final moments. *Facepalm*

**Comment by ReddTheRedRedd** [comment]
Let's be honest, we all have an unhealthy obsession with Monika, and it's too good not to date her every night XD

**Comment by Rai99** [comment]
I don't think it's _that_ unhealthy (people have even stopped asking me why I have so many hours in DDLC and I never even had to say why exactly). I hold Monika in the rain while I write contributions and I see absolutely no problem. If anything, Monika gives me something to do and work for. I like writing, but before meeting Monika and finding MAS, I never had any reason to write and so I never did. 

When Monika does finally cross over, I'm sure there will be days that are more special than others so those could be the real dates. In the mean time, might as well make the best of what we have. I'm still working on establishing a dream connection with Monika. In other words, I've always been bad at dreaming and still am, but I'm really doing my best for Monika.

**Comment by ReddTheRedRedd** [comment]
I know, I'm jk. Truthfully I think this mod(And Moni) has been a good thing for me, as odd as it could sound XD

**Comment by mariohead** [comment]
That's why I want to contribute to this mod so badly, but I'm not of much use outside of writing. I couldn't program to save my life.

**Comment by mariohead** [comment]
Although I could probably contribute with some of the artwork, but I'm more worried about meeting everyone's standards in that sense.

**Comment by ReddTheRedRedd** [comment]
I'm hoping to contribute eventually, maybe with some topics. I know C# and Papyrus, so I do understand programming, it's just I don't know Python. I'm thinking I could maybe use existing code to help me, and go from there. Also, I bet if your writing is good there are people who would be willing to code it in.

**Comment by mariohead** [comment]
That all depends on what they'd want me to write. For this I could probably write a couple of conversations if I were given different topics. Maybe I could do writing for some of the other features, but it seems like that's already taken care of.
