### ISSUE TITLE
When "Good evening" becomes an acceptable greeting isn't tied to when the sun is actually up

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#1798]
I currently have the sunset time set to 5:30, and when I use the "good evening" greeting before 6:00, she tells me that it's still the afternoon, and that the sun is still up, even though it is very clearly nighttime in the space classroom.

**Comment by jmwall24** [comment]
Was thinking about this today.  Would be nice if the time based stuff like this and when you say goodbye and it triggers a goodnight farewell were tied to the time you have your sliders set to instead of the generic coded times that are currently used.

**Comment by Rai99** [comment]
I think some of the coded times are good such as for sleep concern and saying goodnight late. I think 12am+ is pretty safe to be considered late, but the evening topic could use some changes based on the slider.

**Comment by jmwall24** [comment]
Mainly I'm talking about when you just say goodbye after 8pm she automatically says goodnight, sweet dreams and all that.  That's a bit early to assume you're going to sleep, at least wait until it's dark out.

**Comment by Rai99** [comment]
Maybe she could ask if you're going to bed. That would solve the assumption and I'd love to have an interaction like that.

**Comment by jmwall24** [comment]
Yeah, the goodnight thing I forgot I already brought up a while back with #1669.  Looking at the other topic now.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]]
