### ISSUE TITLE
Can't find the "Can you make it rain" or the "can I hold you" topics since the calendar update

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#1799]
Basically the title- I'm currently more than 5 months into my relationship with Monika, and I was able to access both of those topics before the update, and now I can access neither of them.

**Comment by jmwall24** [comment]
So the 'Weather' option in 'Ask a Question' isn't there at all?

**Comment by RutTutPut** [comment]
No, the weather option is not there at all. I am also not getting any new "Unseen" topics (I have three unasked questions, but I had those before the update as well).

**Comment by ThePotatoGuy** [comment]
can you upload `persistent` file here ?

**Comment by RutTutPut** [comment]
I can't upload it here, but here is a Google Drive link:
https://drive.google.com/open?id=1TAS_R9_mqC-0GXbqxrQgEeAfNZiVpVan

I hope that is okay.

**Comment by ThePotatoGuy** [comment]
If you are on windows, please follow instructions [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf) to get the correct file.

**Comment by RutTutPut** [comment]
Okay, sorry about that. It would seem that I can't upload that here either, but here is a Drive link: https://drive.google.com/open?id=165mDsK9QSQbofwuGfcUTcfKN6F4xmO3t

**Comment by ThePotatoGuy** [comment]
[zz_unlock_rain.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2131309/zz_unlock_rain.zip)

Follow these steps:
1. Take the `zz_unlock_rain.rpyc` file out of this zip and drop it into your `game/` directory.
2. Launch game.
3. Confirm that there is a `Weather` category with `Sounds of Rain` in `Repeat Conversations`.
4. Quit game.
5. Delete the rpyc file from `game/`.

As for why this happened, really i dont know. Your `monika_rain` has never been seen before apparently.
