### ISSUE TITLE
[Suggestion] Monika's handwriting font on calendar

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1801]
As the title suggests, it seems to me that since it's Monika's calendar she would write the notes on there herself so it'd be in her handwriting, which I just love to look at.  Maybe the actual holidays would be in a generic font because they come that way on calendars anyway, but the personal stuff Monika would have to write on there.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]]

**Comment by ThePotatoGuy** [comment]
reopening as in progress

**Comment by multimokia** [comment]
closing as completed
