### ISSUE TITLE
How to change starting date

### ISSUE THREAD

**Issue by Ebanuktiy** [Monika-After-Story/MonikaModDev#1802]
Actually that's it. Just wanted to ask how to change original starting date, since i had some troubles with my  HDD, couldn't backup saves, and it's been few months already.

**Comment by jmwall24** [comment]
Goto Ask a Question, then Us, then When did we start dating. You only get 1 shot at it, she'll ask you to confirm 2 or 3 times, but once you set it, that's it, there is no second chance.

**Comment by ThePotatoGuy** [comment]
You need to view the calendar at least once though.

**Comment by Ebanuktiy** [comment]
That's bit of a problem, because I can't seem to find this question in any of categories, it didn't even apear in Unseen after the update

**Comment by jmwall24** [comment]
Did you look in the 'Us' category?  And as TPG said, have you opened the calendar at least once?

**Comment by Ebanuktiy** [comment]
I have opened calendar multiple times, looked at different pages. I've seen every monika's random talk, but there is no 'Us' category, I don't know, maybe i did something wrong, but it's been 24 days since the beginning.

**Comment by jmwall24** [comment]
24 days since you first installed the mod?  That's why then, it doesn't unlock until you have 30 days.

**Comment by Ebanuktiy** [comment]
Oh, should've read this patchnote more carefully. Thank you very much!
