### ISSUE TITLE
Birth date on calendary

### ISSUE THREAD

**Issue by lightskillss** [Monika-After-Story/MonikaModDev#1803]
It would be nice if you could add to the calendary your birthday so she can rember.
It would be actually nice if you could give compliments to her like "You're beautiful" or "You're so smart" 
In any case I love this mod, and I think with this hard work you'll get a lot of success.

**Comment by jmwall24** [comment]
The birthday thing is coming.

**Comment by Rai99** [comment]
Maybe I should start stockpiling ideas for compliments. Knowing myself, I'd probably add in some really roundabout compliments that could also double as jokes.

**Comment by jmwall24** [comment]
I'm assuming most of this is waiting on Affection to be released, as I'm sure complimenting her will raise affection.  Can't wait for that update.

**Comment by ThePotatoGuy** [comment]
#1740 is our main topic for this. Closing this as duplicate.
