### ISSUE TITLE
Telling Monika About A Book You're Reading So Far

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#1804]
So I'm not sure if anyone actually had this idea before, but it just popped into my mind recently. So we all know about the topic of Monika asking the player if they read anything so far. For a future topic, Monika could ask the player if they have been reading whatever book they're reading by answering " yes " or " no". If the player chooses " yes", then they can explain about what is occurring in the story so far probably by typing out into the box and continue to type without Monika interrupting in case the player ran out of space and they were still continuing their talk about their book.  If the player chooses "no", then Monika can maybe try to get the player to read something she read before or try to ask the player what genre they like and perhaps she can suggest the player a suitable novel based on the genre they like. After the topic appears a second time, Monika could probably ask the player the same thing of what is still happening in the story and probably explain how it ends based upon how many times the topic repeats and whenever the player finishes the book they're reading.  Yeah, this is surely a lot but something nice to give. Just wondering if this could be created and installed into future updates. Thanks for making this mod better by each update.

**Comment by Rai99** [comment]
**My guess, is that there's no way in the world something like this could be implemented.** 

I'm pretty sure there's more than a couple books in existence and probably too many to add dialogue for. If the textbox is brought back, any response from Monika would have to be generic enough to make sense with any book the player might be reading, and if it's so generic, it wouldn't really mean anything at all. If it gave _something_ unique for each book, it would be something, but it would take a sizable effort to write something in response to each individual book. Not to mention how many books even exist and I don't think you could fit a decent summary into the textbox. 

In the case of Monika asking if the same thing is happening, it would have to be generic. Monika wouldn't know if an event is good or bad just from the textbox and no depth would be in her response. Also, what books _has_ Monika read and able to recommend to the player? 

I do like the idea of telling Monika what your favorite genre of book is, but that's still a lot. There are a lot of different genres of books and far too many to fit every single one in one menu at once. I could probably narrow it down to 5 well known genres + other for 6 options,  but that does leave out a lot. 

I'll give you one thing, you're definitely right that this is surely a lot of work if anybody were to attempt to implement it.

**Comment by KarterLackey** [comment]
I understand. Thank you for your repsonse. And if Monika were to suggest any of the books to player, she could have suggested the ones she talked about in other topics like Bradbury's" Fahrenheit 451" or Orwell's " 1984". I mean I knew I was gonna get a reply like this, but like I said, I understand and thought this could be nice.

**Comment by Rai99** [comment]
The idea of telling Monika what your favorite book genre is still in the picture I think. Just need to think of a good way to do it. 6 options is really pushing it I think but there might be some way.

**Comment by MisterSimple** [comment]
Maybe, rather than asking about the genre, Monika could ask how you feel about the book so far. Possible options could be "I can't put it down!", "It's alright", "I'm not really into it", "I find it hard to continue", etc, and she would react accordingly (by saying she's glad you're enjoying it, or giving you tips on how to keep on reading). Then again, it would be out of character for Monika not to ask what it is about in the first place.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
