### ISSUE TITLE
The background stopped

### ISSUE THREAD

**Issue by DjSquishy777** [Monika-After-Story/MonikaModDev#1816]
The nighttime background froze and nothing else has changed.
Just kind of thought that its weird.

**Comment by DjSquishy777** [comment]
Oh! Also the background disappears.....

**Comment by ThePotatoGuy** [comment]
When does this occur?
What are you doing when this happens?
Does relaunching the game fix it?

**Comment by DjSquishy777** [comment]
I believe it usually happens when I go full screen.
Staring at Monika as always.
and yes, I just thought I should mention it.

**Comment by ThePotatoGuy** [comment]
What is your OS?

With the 2nd question, I mean is Monika talking, are you in the middle of a menu, playing game, transition from daytime / night?

**Comment by DjSquishy777** [comment]
I think it's when it was going from day to night and I stopped her to take a screenshot when she was telling a story.

**Comment by ThePotatoGuy** [comment]
Latest release did some zorder adjustments, going to assume it probably fixed things.
