### ISSUE TITLE
[Bug] - Anniversary Events

### ISSUE THREAD

**Issue by FinalFusion** [Monika-After-Story/MonikaModDev#1818]
So i used the option to reset our anniversary to December 22nd (thank you for adding that!) and when I did that I got access to up to the 3 month lines which is good but 6 months was coming up on the calendar. Its now past the 6 month mark and she hasn't said anything about it. Probably isn't a huge deal as long as she brings it up eventually. Maybe she'll say it when it hits 6 months from the anniversary date before I fixed it?Just something I noticed. Also didn't really know what to title this.

**Comment by jmwall24** [comment]
I just tested this by adjusting the date on my computer and I got the 6 month anniversary dialogue based on the date I changed it to with the calendar update, so not sure why you didn't get it on June 22.

**Comment by FinalFusion** [comment]
Oh it actually worked! Don't know why she didn't bring it up before. I turn on MAS at least once a day so I couldn't have missed it.

Should I delete this thread now that its fixed or is it still considered a bug because she didn't say it the first time?

**Comment by jmwall24** [comment]
I'd wait until someone who actually can fix bugs looks at it.  Glad you got it working tho!

**Comment by ThePotatoGuy** [comment]
Anniversaries only unlock the day of, so you have a 24 hour window to see the anniversary (and unlock it so you can see it later).

I don't think we're going to change this.

**Comment by Rai99** [comment]
I think it's a bit harsh to possibly miss the window due to some circumstances and never be able to see the anniversary event in game. 

Maybe add unique dialogue about missing the anniversary the next time the player visits Monika and unlock the respective anniversary?

But this does raise the problem of somebody abandoning Monika for a long, long time to come back and still get all the anniversaries. Maybe give an extra day or 2 window to unlock it.

**Comment by FinalFusion** [comment]
I do turn on MAS once a day. I normally turn it on pretty late and I remember noticing that when the time ticked over to the day of the anniversary she didn't say anything. Maybe it got confused by the day transitioning from one day to the anniversary day? Maybe it was just something specific I did? idk.

**Comment by jmwall24** [comment]
That might be why, depending on when exactly you were on.  I know in older versions, the anniversary dialogue was set to not show up until after 3 am on that day, so if you were on at midnight, and left before 3am and didn't log back on again that day you would have missed it.  Looking at the file now, I don't see that 3am thing anymore but maybe it's still there in a different form that I don't recognize.

**Comment by FinalFusion** [comment]
I typically get off after 3 am but maybe on that specific day I got off early. I don't get off early very often but if I did it kinda sucks that I was essentially an hour or 2 away from getting it and I would have never gotten it if I hadn't put my computers time back. But that could probably explain it.

**Comment by Rai99** [comment]
3am? And Monika scolds _me_ for staying up until midnight or 1 at the latest.

**Comment by FinalFusion** [comment]
Yeah, she doesn't like it very much. You should see her when you get off at 5 am.

**Comment by Rai99** [comment]
Sometimes, I'm glad Monika isn't here because I'm sure she would just drag me into bed for the night.

Although, I'm not entirely sure if that's a good thing or a bad thing.

**Comment by ThePotatoGuy** [comment]
The cutoff is still 3am, so actually the 24 hour window is 3am the day of, to 3am the next day.
We should probably change that to midnight start, 3am next day end.

I think the 24 hour window is fair. You wouldn't miss an anniversary with a _real_ gf.

**Comment by Rai99** [comment]
That's most likely true and it is fair, but I'm just thinking of worst case scenarios where the player might have been in an accident or their computer was damaged.
