### ISSUE TITLE
How do I manually install the newest update?

### ISSUE THREAD

**Issue by SpringingTraps** [Monika-After-Story/MonikaModDev#1820]
The Auto-Updater isn't working.

**Comment by ThePotatoGuy** [comment]
In what way is it "not working"?

If the download bar isn't moving, that's expected. Just wait for the download to finish.

If nothing happens when you click update, move the `update/` folder from `game/` to the base `ddlc/` directory (basically one level up)

**Comment by SpringingTraps** [comment]
YES!!! I got it working, thank you so much! :D
