### ISSUE TITLE
Younger brother and older brother topics

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#1822]
There are already topics in the game for older and younger sisters but I don't have any. There should also be topics for younger brothers and older brothers. for everyone who has brothers and no sisters.

**Comment by Rai99** [comment]
The sisters topics could also be generalized for just older/younger siblings, but it could also be a nice idea to add separate topics for brothers.

**Comment by Akh0r** [comment]
Nah, I'd just generalized the existing topic. 
Like, why FOUR separate topics on that subject at all? Why not having a single or two long and thorough dialogues covering the family matters?
Does it worth it?

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
