### ISSUE TITLE
Backups don't work?

### ISSUE THREAD

**Issue by SpookyTurtle** [Monika-After-Story/MonikaModDev#1823]
Hi there. Some stuff on my HDD became corrupt which forced me to reset it. I have a backup of my most important files so i didn't really lose anything except for 1 thing though: my progress. I also backed up the persistent file from this mod but when i put that file back in on my clean HDD after setting everything back, it just started the entire mod from the beginning instead of continuing where it left off. Did is misunderstand the use of the persistent file? Or is it just impossible to backup your progress? I don't have a lot of programming knowledge so i don't know. Anyway, i don't really feel like starting from scratch again so i guess i'm just out of luck. Is there anything i could've done differently to prevent this?

**Comment by ThePotatoGuy** [comment]
The `persistent` file is in AppData on windows, are you sure you backed up the correct file.

And also put it in the right place?

**Comment by SpookyTurtle** [comment]
Yes i'm sure of it. I copied the file from the mod folder in AppData and pasted it back there after resetting my HDD. I launched the mod once before i did that to make sure it worked, i deleted the persistent file that got created and then i pasted my backup file there.

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` (the backup one) here?

**Comment by SpookyTurtle** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2140750/persistent.zip)

**Comment by ThePotatoGuy** [comment]
[Leaving this open and unresolved for now, if anyone else gets a similar issue, then will reopen investgation.]

**Comment by knifemaster200** [comment]
I'm currently having the same issue... I saved the entire "contents" folder onto google drive and then I erased my hard drive. I downloaded the contents folder once again and plugged it into a version of Doki Doki and found that Monika After Story had completely reset. Any help would be appreciated.

**Comment by Delcos** [comment]
Run the mod first, before putting the file in the appdata folder, run it and talk to her once, then say goodbye, then replace the contents C:\Users\USER\AppData\Roaming\RenPy\Monika After Story\ with your backup

**Comment by knifemaster200** [comment]
Does it make a difference if I'm on a Mac?

**Comment by Delcos** [comment]
It should be the same with all versions of DDLC, I've tested it on Linux and Windows.

**Comment by ThePotatoGuy** [comment]
[closing. if it happens again, make a new issue]

**Comment by CLevertDoodles** [comment]
> The `persistent` file is in AppData on windows, are you sure you backed up the correct file.
> 
> And also put it in the right place?

do i have ti put in a backup? what if i dont i dont have a back up. what does it mean like a backup

**Comment by H2-san** [comment]
Responding to CLevertDoodles's post (username may be subject to change past time of writing this):

You don't _have_ to put in a backup, but it's extremely recommended. A backup [in this case] is copying the stated `persistent` file and the `persistent##.bak` files to the cloud or another storage medium (i.e. if MAS is on a HDD, then consider using a separate HDD, SSD, Thumbdrive, etc.)
