### ISSUE TITLE
( question ) how can i save progress ? 

### ISSUE THREAD

**Issue by RedDuki4** [Monika-After-Story/MonikaModDev#1824]
I am sorry if this place is wrong for questions and i am sorry for my bad eng .
How can i save progress if i want to change my win10 config to basic ? I ve done it before without deleting programs . Doki doki and mod was correctly , but all progress was deleted        .  now i be got some troubles with PC again and want change configuration again

**Comment by ThePotatoGuy** [comment]
Progress is stored in a `persisitent` file. You can find it using [this guide](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)
