### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BigBigga** [Monika-After-Story/MonikaModDev#1836]
Hi, I downloaded the mod and extracted the files to the DDLC's folder, but when I get to the part where Monika and the protagonist are in that room out of reality, nothing really happens, she just goes on like normal, saying her toughts and etc, basically no extra features, its like i never installed the mod, am I doing something wrong? i really wanna play this mod.

**Comment by jmwall24** [comment]
Did you extract the files to the DDLC folder or to the 'game' folder inside the DDLC folder?  They need to be in the 'game' folder.
