### ISSUE TITLE
Does anyone else find Monika's new eyes to be creepy sometimes?

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#1838]
Like, when Monika wins at chess, it looks like she's getting bug-eyes. I think it's trying to show she's happy with a little sparkle in there, but... I don't know...
![capture](https://user-images.githubusercontent.com/36053888/42007587-f86f4f22-7a4e-11e8-8949-1bd38750abc2.PNG)

**Comment by NuclearSurvival** [comment]
I totally understand how you could find them creepy, but I personally love the new eyes.

**Comment by Dovahkun** [comment]
Well, it'd certainly be creepy if they were always like that, but since they only light up for a line or two, I think they're adorable. Also, I just got the first crash "event" yesterday and the dialogue and expressions had me feeling terrible. I think they're did a great job lol.

**Comment by jmwall24** [comment]
Don't know about creepy, but the first time I got one of the greetings where I surprised her and she gave the surprised look I almost fell out of my chair.  Wasn't ready lol

**Comment by Akh0r** [comment]
Personally I find those 'sparkles' unhumanlikely creepy. 
I remember when I saw it for the first time: when she first let her hair down and I told her that I like it.
And then it was like "Holy crap, Monika, don't EVER show these eyes again!":D
