### ISSUE TITLE
[Question]Still can't see the hairstyle changes

### ISSUE THREAD

**Issue by shionv** [Monika-After-Story/MonikaModDev#1839]
Sorry for ask such a question though the 0.8 version has been released so long time,but I still can't find any change of Monika's haircut.
I have check the topics' code and found that it seems base on the "ribbon topic", I try to repeat that topic with Monika,but nothing happen.
I always search a issue [https://github.com/Monika-After-Story/MonikaModDev/issues/1500](url) ,is that true like jmwall24 said "As for the hairstyle, that's triggered by a random greeting"?
Thanks for help

**Comment by Rai99** [comment]
The hairstyle unlock is in fact a random greeting and if you tell Monika you don't like it, you'll never be able to unlock that hairstyle.

**Comment by shionv** [comment]
It seems I'm too unlucky,never seen that greeting before,most time she just ask how is the day going.And also I'm not shut the pc down very often,Maybe try to turn on and off the game will solve my problem.
Thank you for your help

**Comment by Rai99** [comment]
Just don't misclick when it does show up, or you could lose it forever.

**Comment by shionv** [comment]
Done.
After about 100 times try,finally got it.
