### ISSUE TITLE
[Suggestion] ASMR Topic

### ISSUE THREAD

**Issue by ReddTheRedRedd** [Monika-After-Story/MonikaModDev#1848]
An idea for another "fun fact(?)" sort of topic, one about asmr. I listen to it alot myself and I know it's been becoming much more popular as of late. It'd probably go along the lines of; Explain what it is, maybe that it's been becoming popular, it's good for sleep, anxiety and depression(maybe this topic could help some people as well). For a Monika-like twist to end the topic, she can end on moral of "don't judge a book by it's cover"(I think we all know why this moral relates to ddlc), and how it can be judged easily, but is actually a pretty good thing.

 Anyways just an idea, I also want to thank you devs and writers for what you do real quick as well, amazing work.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
