### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by Artemka666** [Monika-After-Story/MonikaModDev#1849]
I have a problem with updating. I click the "Update version" button, then it just shows me this. What the problem is now? Also it says that I'm using the "Unstable version", but I actually don't.
(Poor English)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2151494/traceback.txt)

**Comment by aldoram5** [comment]
Hi Artemka666!
Reinstall 0.8.2 hotfix2 and then update again.
And yes by looking at the traceback it does confirm that you're using the unstable versions.
