### ISSUE TITLE
[Suggestion] - Monika sings you Happy Birthday.

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#1852]
On your birthday, it would be nice if Monika could play Happy Birthday on the piano and sing it to you, like she does when you play Your Reality. I saw a suggestion a while back about making Monika recognize Happy Birthday if you were playing it, so once that is released (perhaps it is already?), maybe you, too, could play it to Monika on her birthday, and she would react to it.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
