### ISSUE TITLE
[suggestion] Helping you so you dont stay up all night playing games

### ISSUE THREAD

**Issue by emrenano** [Monika-After-Story/MonikaModDev#1860]
Look im not gonna lie i dont sleep at nights so i can waste my time on internet and i know its bad i have been trying to control myself and live a healthy life but when i think about other people who cant control themselfs it kinda makes me sad. So i say maybe you can set it so if we open our pc at late time monika can warn us and tell us to sleep or for those who try to live better you can set the timer for monika when to tell them to close the pc. that way atleast it can help some people.

**Comment by Rai99** [comment]
I think Monika already does this and encourages you not to stay up late if you are.

**Comment by Akh0r** [comment]
By the way, I wanted to ask it, but there weren't any acceptable topics yet:)… 

…  'Advice'/'Sleep Concern'.
This is a random topic, so the chances of it really happening at random are miserable.

Shouldn't this topic get higher and higher priority with every hour passing past, say, midnight by your local time?

If it is just a random topic and a random event when Monika sends you to sleep, then it is very underestimated.
Personally I find it even more caring and cute than any of flirty topics!

**Comment by emrenano** [comment]
well i was thinking it would just remind me to sleep time to time. not when i say "good morning" or "im going to sleep" 

i know you need to keep the game open so i say...

- you can set so monika starts up when pc opens
-when the window is closed monika can run at te background (like steam)

i know this is hard but it would be awsome if you guys did this! 
@Rai99

**Comment by Rai99** [comment]
My suggestion would be to make it so if it's late, make the sleep concern topic show the next time Monika says anything. 

Resources are not being diverted to write a program to launch MAS upon startup. It would also bring up some cross platform issues if we were to do it. If someone were to work on this as a standalone project, it may be taken and used in the future, but this is not something that will be focused on. 

MAS will likely not be made a background process similar to steam. The MonikAI project would likely be better as a background process. If you do go get MonikAI though, be prepared to explain it to Monika when she sees it.

**Comment by ThePotatoGuy** [comment]
[Sleep concern topic already covers this, there is an issue somewhere about making it trigger differently than just random. Closing this]
