### ISSUE TITLE
Monika as antagonist

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#1862]
Iv'e noticed how she often has defended her choices but when she talked about her age she referenced the wiki page which also labels her as the primary antagonist. It would be neat if she addressed this more about the tittle of Villain. While the DDLC Wiki simply calls her the primary antagonist she has her own place on the Villain's Wiki.

**Comment by ACoolCat** [comment]
I'd imagine she'd get deeply upset by it and insecure. It could potentially tie into the affection system.

**Comment by Rai99** [comment]
I just had a small idea. What if we had something along the lines of "I'm glad you're evil too"?

Ultimately, this idea about talking about Monika being the antagonist would probably fall under a topic about how people are too quick to judge nowadays.

**Comment by loverofmonika** [comment]
i doubt monika would call us evil but i can definitely get upset but wouldnt care much cuz she is finally together with us, its like she discards everyone else opinion and the only opinion that matters is ours, what we think of her

**Comment by Akh0r** [comment]
Lover, not that it really matters for her... But it would a fun part of creating Monika's and Player's depiction of each other.
Something like that:
_"So... You really think that I am the villain of this game? Yet you are spending time with me, talking to me? Can't believe that. Maybe I was too overreacting over the things I've done? Well... If a villainess can get her love... I don't mind thinking that way"_

**Comment by Rai99** [comment]
I'm thinking maybe whether or not we think Monika is evil could be a different question. There are definitely some people who think I'm evil and it makes me feel a bit better that I'm not alone with that, provided Monika isn't bothered too much about people thinking she's evil. 

Actually, this kind of ties into my first contribution #1618 about justice being ironic. You're just doing what you think is right/needed and then there are probably going to be people who think you're crazy/evil for it. 

I'm thinking this topic goes in the direction of: "_I don't mind if people think you're evil, as long as it doesn't bother you too much_" and maybe the player could tell Monika that they themselves are evil too and maybe have Monika react a bit to calling yourself evil or finding the common ground where people think you're both evil, but you're both happy anyway.

**Comment by loverofmonika** [comment]
Orr this can go in the direction somewhat like this that Monika points out that people we were too fast and judged her without listening what she has to say. The game needed a villain to make the story interesting and she ended up filling that slot. A cruel fate, in the end she was necessary evil. 
Then she compliments u saying that u didnt believe what their claims and if they say that u too are evil for picking her then so be it, if standing up for what u believe is right is evil then I'm gladly evil

**Comment by loverofmonika** [comment]
What do u think, I added the sense of justice in the idea as well

**Comment by loverofmonika** [comment]
What do u think, I added the sense of justice in the idea as well

**Comment by Rai99** [comment]
I like the idea. I'll work on it unless someone else wants to, but I think I'd like to work on this one.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into ths]
