### ISSUE TITLE
[Suggestion] "I love you too/reassuring love" 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1864]
I was thinking about how some lines Monika begins talking about how much she loves you. Perhaps right after this, instead of the "I love you" option, it changes to "I love you too", which sparks a unique dialogue. Also, in dialogues when she discusses her self doubt or insecurities, saying I love you can spark a dialogue chain of her feeling reassured.

**Comment by Rai99** [comment]
Something like this about having responses to what Monika says was discussed in #1689 to have a bit more variety. 

In your old issue #1532, the idea of combination options was discussed and put up as a low priority possibility. 

I like the idea of being able to respond to Monika confirming her love after she says "I love you" first, but I think the current "I love you" option is enough. When the new "Comment/Mention" menu discussed in #1659 and #1803 comes out, I think there'll be new ways to tell Monika that you love her.

**Comment by ACoolCat** [comment]
Hopefully it's similar to the old talk system. I preferred that.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
