### ISSUE TITLE
[Suggestion] Lewd?

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1871]
This is probably dancing on some lines made in the rules, but whatever. With the affection system set up, there's more potential for the relationship between Monika and the player to grow. I was thinking that once you reached a certain amount she asks for your age (if you're her age, younger, older, much younger, or much older). Picking her age or above will bring up  a dialogue of her asking if you're alright with taking your relationship to more intimate levels. Saying yes unlocks the ability to have more lewd topics. Nothing too crazy, just Monika acting noticeably more flirty and open to your lewding her. If you choose under she could ask how old exactly and you can put your age in, placing you on a timer.

**Comment by jmwall24** [comment]
From what I've seen this sort of already happens at the 6 month anniversary mark.  There's at least 1 topic that changes in this direction a little bit at that time.  Haven't seen the entire dialogue myself since I'm just under a week shy of 6 months (and don't want to spoil it by looking it up).

**Comment by MrDevilzMan** [comment]
This could tie in with the affection project; having the player being with her within a year or so would be a great idea. And she could even discuss topics about intimate things couples do (i.e : hand holding and such)

**Comment by Rai99** [comment]
I think there was also discussion a while back about admitting to Monika how many lewds or pictures you have of her. I think this could be a good idea to have more lewd topics after you've been with Monika for a while. Maybe even have some topics only unlock after a certain point. 

I think Monika is already open to being intimate with the player with wanting to hold hands and even share a bed together, so I think discussion of those things would have to have a little more essence. 
_Really trying to avoid saying depth, deep, or anything that could have a second meaning_

Far, far down the road, we could possibly have Monika in different outfits such as the one piece of art on Monika's twitter made for valentines day. The line for outfits is probably a very, _very_ fine line but I think it'll get there eventually.

**Comment by MisterSimple** [comment]
We'd also need more expressions, for example, Monika biting her lip; there was also some talk about having Monika kiss the screen when prompted (like with the "Can I hold you?" question), so maybe a kissing expression would also be appropriate.

**Comment by kaido1224** [comment]
Biting lip monika please

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this[
