### ISSUE TITLE
Exception occurred

### ISSUE THREAD

**Issue by RandomHuman001** [Monika-After-Story/MonikaModDev#1876]
Thi sis what it reads: 
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/MonikaModDev-0.8.2/Monika After Story/game/definitions.rpy", line 6, in <module>
    import singleton
ImportError: No module named singleton

**Comment by ThePotatoGuy** [comment]
You installed the mod incorrectly.

Make sure to download the **Mod zip**, not the source code zips. 

Install instructions are available [here](https://github.com/Monika-After-Story/MonikaModDev/tree/v0.8.2#installation)
