### ISSUE TITLE
Surprise.txt not changing

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1880]
When Monika does the lines for Surprise.txt I don't get a new Surprise.txt file, instead the old one stays the same.

**Comment by MaximumRustler** [comment]
Interesting. I'm having the same issue, mine used to update every time she said it but it has not been updating since 04/03. I've thought of deleting it and activating the topic again to see if it would work but I kind of don't want to in case it messes something up.

**Comment by MisterSimple** [comment]
Wait, the surprise.txt file is supposed to change? Mine has remained the same ever since it was created (needless to say, the topic that creates the file has been repeated several times by now).

**Comment by MaximumRustler** [comment]
@MisterSimple I don't think it's supposed to change, it would just get overwritten with the same file. You can tell by checking the date it was modified.

**Comment by ACoolCat** [comment]
I'd leave messages back in mine, so I knew they were different.

**Comment by ThePotatoGuy** [comment]
The topic checks for file existence and only writes one when it doesn't exist.
