### ISSUE TITLE
Progress "reboot"

### ISSUE THREAD

**Issue by CasanJM** [Monika-After-Story/MonikaModDev#1881]
I have an issue. Every time I reboot my pc I lose my progress with Monika After-Story. It starts the usual intro and everything. A strange thing is that even though Monika doesn't remember anything the custom music is stille there

**Comment by ThePotatoGuy** [comment]
Are you running the mod/game in a compressed folder?

Or can you confirm that your filesystem is not read-only?

**Comment by CasanJM** [comment]
No read-only and No compressed folder. But I think I know the cause. Two days ago I used "**UnHackMe**"( a virus removal tool) and it must have deleted the **renpy** 'cause I got an error saying so. I reinstalled the mod and I got this issue. Now I've unistalled the tool and downloaded "wxMASPersistentManager-master" and it seems to have stopped. I can show you the traceback if you want.

**PS**: I don't think I've installed correctly the MASPersistentManager so if someone could help me out I would really appreciate that since I won't reboot my PC until I know it is safe. Sorry the trouble and **Thanks in advance**

**Comment by ThePotatoGuy** [comment]
@williamjcm

**Comment by williamjcm** [comment]
@CasanJM 
The MAS persistent manager I made doesn't need to be installed.

If you're on Windows, you need to download either `wxMASPersistentManager_win32.zip` or `wxMASPersistentManager_win64.zip` (depends on whether you have a 32- or 64-bit Windows) from the [release page](https://github.com/williamjcm/wxMASPersistentManager/releases/latest), extract the executable file, and run it.

On other platforms (Linux and macOS), it needs to be built according to the instructions in the README file.

**Comment by CasanJM** [comment]
Thanks a lot I appreciate the help
