### ISSUE TITLE
Concerns of Affection System

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#1886]
I'm a bit concerned about what the affection system will entail. Mostly when it comes to health. It sorta rubs me the wrong way if she'd give negative points for, say, someone saying they smoke and/or trying to quit. Seems like she should be more concerned than gain negative affection. Perhaps there could be some sort of concern point system that runs along side it? Higher concern points make her more sad.

**Comment by kaido1224** [comment]
The intent of the affection system wasn't to be an emotional system, so her being "sad" doesn't really fit the intent of it. I don't think you should receive negative affection for saying that you smoke or are trying to quit either though.

**Comment by kaido1224** [comment]
i'm no longer affiliated with this mod and have no intention of coming back. Since it was my idea, I'm just letting you know the intent of it was to not be associated to emotions. What TPG and the others do with it now that I'm gone is up to them.

**Comment by ThePotatoGuy** [comment]
Affection is purely based on how you treat her.

**Comment by ACoolCat** [comment]
Oh, well that's a relief.
