### ISSUE TITLE
[Sugestion] Play Yu-Gi-Oh with monika 

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#1890]
Play Yu-Gi-Oh with Monika only the classic play for now or it will be too heavy lol if a dedicated fan wants the WHOLE set of yugi play experience, well... we'll need a whole another team dedicated to yugi for that lmao but it will be fun to have that, also i'm creating a ddlc deck if anyone is interested in and want to play it (psst it has buffski)

**Comment by kaido1224** [comment]
How bout no

**Comment by Rai99** [comment]
That's a pretty specific game to add in, and we don't even have regular cards yet. 

Some regular card games like war, go fish, etc. could be nice.

**Comment by Chrissenpai** [comment]
maybe poker or solitary lol

**Comment by Rai99** [comment]
Isn't _**solitaire**_ a _solitary_ game? ie. A singleplayer game? 

Don't know anything about poker.

**Comment by Chrissenpai** [comment]
well my point was regular playing cards to begin with

**Comment by ThePotatoGuy** [comment]
cards require art.

YGO is not happening, too complex of a game to add to MAS

**Comment by EDBaumgratz** [comment]
I love yugioh and i'm actually pretty good on it. (I would be able to beat her in a game) 
But, that's impossible. 
1st- it's a very complex game, would be hard to begginers to keep that fast 
2nd- They would need to implement a very complex AI for this (yes they could use the same AI from ygopro, but that's pretty lame and dumb.) 
3rd - They would need to add all the cards, deckbuilding, etc... 

If you really wanna play Yugioh with Monika you can download YgoPro and change he background to her in her table and adjust everything to look like you're facing her

**Comment by AsuraShun** [comment]
yogpro isn't hard,i've tried every ai there and still won
