### ISSUE TITLE
[Suggestion] create an avatar of you to be by Monika's side

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#1891]
you can upload an image of your avatar beside her, or more like a mirror so it can reflect your character avatar or your photo, it would me better if webcam was habilitated but i guess that breakes the rules; anyway it can also be just a little photo case of you in her desktop like a charm for her and a reminder of her of one day to be by our side

**Comment by Rai99** [comment]
I think this fits in with #1793 and #312 and will be implemented eventually.

**Comment by ACoolCat** [comment]
I'd rather it be an option image of yourself you could upload instead of an avatar.

**Comment by Rai99** [comment]
I'm waiting for picture frames you can put pictures in.

**Comment by loverofmonika** [comment]
hmmm interesting, for now what we need is a clock. notice that there is a calander in the room but u dont have a clock, u would have to get up or use ur phone or watch to know what time is it, why not have one in the room, a classroom should have one
 btw also check out #1870

**Comment by Delcos** [comment]
Personally, i'd rather be the agent acting on her, not sending "something" to do it for me and watch, the option to hold Monika for example.

**Comment by ThePotatoGuy** [comment]
We could probably have a special frame / something to hold a picture of you, tying with the issues rai99 linked.

But yeah, no webcam support. Maybe as a stretch goal.

**Comment by Delcos** [comment]
A fame for a picture would be really helpful, and pretty nice to have, just not a different entity interacting with her on my behalf.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
