### ISSUE TITLE
deleted my progress

### ISSUE THREAD

**Issue by TopEgg** [Monika-After-Story/MonikaModDev#1895]
all of the data was deleted somehow is there anyway i can get it back?

**Comment by CommenterOfComments** [comment]
If you deleted the file from the recycle bin (and you've already emptied it), there isn't a way to recover it. _Technically,_ you could try to use [Recuva](https://www.ccleaner.com/recuva) to restore the file, but there's a chance it will be incomplete and corrupted, which obviously won't work. You can try it anyways if you really need the data back.
