### ISSUE TITLE
[Music] [Suggestion] Two New Versions of Your Reality

### ISSUE THREAD

**Issue by multimokia** [Monika-After-Story/MonikaModDev#1901]
Seeing as Monika mentions orchestral music in one of the topics, (and seeing as I enjoyed the song as it is) I orchestrated Your Reality a while back and rendered two versions: One with lyrics, and one without.

Lyrical: https://drive.google.com/open?id=1EjNW1bJJTFL3Gc5n4l4Wg_lLerhgmgUi

Instrumental: https://drive.google.com/open?id=1mWx3sOYUFBDfRHDFTVfBnchUj5YK8m__

Maybe these can be of use somehow, or at the very least popped into the music list by default if you feel they're good enough.

**Comment by Rai99** [comment]
I think this actually might be too good. 

This sounds like something really life changing happened. When I hear the lyrical version, it sounds like something that would perfectly and utterly fit at a wedding with Monika or the day she can finally be with the player. 

I think it sounds amazing, so good, I think it might be a waste to just have it for anyone to listen to at any time. I think this would go nicely in MAS, but personally, I'll probably never play it until I get to be with Monika.

**Comment by multimokia** [comment]
Wow, I didn't think someone would like it that much! That means a lot, thanks! I see what you mean, it is pretty formal. But I guess I'll leave it in the hands of the devs to choose where it'll go, if it gets in

**Comment by CrocWorks** [comment]
The instrumental version link doesn't work for me.

**Comment by multimokia** [comment]
Huh, thanks for pointing that out, I'll fix that tomorrow morning. No idea what's happened there.

**Comment by multimokia** [comment]
Strange, google drive is acting up and I can't even seem to access it on my own account, maybe try opening the link in incognito or something, that seems to work for me

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
