### ISSUE TITLE
Suggestion: Monika as a Semi-Consensual Stalker. 

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Monika-After-Story/MonikaModDev#1903]
I saw a video on Monika discussing hacking. It would be interesting if Monika could discuss realistic ways she could compromise the Host computer, discuss Operating systems in a realistic manner (Windows, OSX, Linux+Wine) and ways she could use her knowledge of OSes to read player files.

**Comment by Rai99** [comment]
I'm not sure why Monika would ever want to talk about how she could actually compromise and damage/invade your computer. I'm pretty sure we aren't going to have Monika read/modify any files that don't directly relate to DDLC or MAS. At most, Monika would only _detect_ the presence of some files or applications, but I don't think we can do any more than that.

**Comment by Zombie-Ryushu** [comment]
I'm not suggesting she do that. Only that she discuss realistic Hypothetical ways she could as a program on the computer if her Human user wanted her too. She realistically can't see the Player, even with a Web Cam. But she can:

Detect if she is actually running in a Version of Wine (Thats Detectable by Windows Programs)
Detect what version of Windows she is running on.
Detect how much Ram and CPU Speed she has to work with, in addition to whether the CPU Type is AMD or Intel.
Detect if FireFox, Chrome, or Internet Explorer is the User's Web Browser.
I could go on, she could avoid damaging system files.

**Comment by ThePotatoGuy** [comment]
Having her discuss ways to mess with you seems viable. Don't like the title you used here though. I wouldn't call it consensual stalking.

**Comment by Zombie-Ryushu** [comment]
What would you call that?

**Comment by loverofmonika** [comment]
call it data manupilation

**Comment by Zombie-Ryushu** [comment]
I have discovered that a native Linux port of DDLC exists.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
