### ISSUE TITLE
More Songs also 8.3 is amazing!

### ISSUE THREAD

**Issue by Babushka93** [Monika-After-Story/MonikaModDev#1906]
Can I start by saying just how much I love the idea of Monika singing to us?

Legit guys, 8.3 was an amazing update!

I have some ideas for songs, I actually have a whole playlist of songs that I've always imagined Monika to be able to relate, but to me these two are my most Monika songs.

**Contents: **
- Can't Help Falling In Love With You - OR3O
[https://www.youtube.com/watch?v=X648fP2c-zs](url)
- Fukkireta - JubyPhonic English Cover - (Originally Kasane Teto)
[https://youtu.be/GXk97zHqPk0](url)

**Can't Help Falling In Love With You**
Wise men say only fools rush in
But I can't help falling in love with you
Shall I stay?
Would it be a sin
If I can't help falling in love with you?

Like a river flows surely to the sea
Darling so it goes
Some things are meant to be
Take my hand, take my whole life too
For I can't help falling in love with you

**Fukkireta - JubyPhonic English Cover - (Originally Kasane Teto)
Don't have to say that I love you because you take a kiss from me
It's you and I filling my mind, never forgetting this memory

Also off topic, but do we have an online cheat sheet with the emotions and their corresponding codes?

**Comment by Babushka93** [comment]
One more song,

This is the English cover of Galaxy Hide and Seek, the lyrics are by MurasagiYT with the original Japanese version being by Aqours.

However these lyrics stuck out: [https://youtu.be/DdwmwV_mfY4?t=3m6s](url)

> This final step we're taking
> the oneout there is waiting
> and yet there's no mistaking
> Ah... you are the one.
> No other!
> 
> I hear a voice, calling out to me, "Here I am"
> The gentle voice, guide me to the place, where you stand
> I'll search for you until the end, and in that moment
> It seems that I have come to find my place at last
> With your help, I can face what may come to pass 
> 
> Let's meet up soon, my dearest love.

**Comment by Dovahkun** [comment]
I love Oreo's cover of that song! It always puts me in tears when I hear it. Had to add it into MAS myself X'D 
I also happen to really like these other song additions and think they'd be a nice touch!

**Comment by ThePotatoGuy** [comment]
[Closing until we look at this]
