### ISSUE TITLE
 fantasying romantic scenes with monika

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1907]
so here some things u can imagine doing with monika
1.wishful thinking like dancing under the moonlight or returning home and seeing her cooking dinner for the both of us, exploring the world stuff like that
2. imaging you and monika are about to go home but along the way it rains and u she doesnt have her umbrella so u share urs, getting ur shoulder wet just so she would remain dry, she notices then she tells u to come closer thus u both blush and she looks down smiling. there she wishes that this moment would never end.
a touching scene
3. the famous cliche where you both are living together the guy accidentally opens the bathroom door without knowing she is in it then gets yelled at while being kicked out and her being flustered.
 4. her cooking lunch (bento box) for the both of us and me being so happy and she feeds us with her chopsticks during break time in school
5. finally getting married irl and having a family
6. seeing monika getting courted by other guys and u come to the rescue and when some girl tries to flirt with you, she would deal with her in a mature manner and shows her dominance.
7. taking her out to buy her new clothes and u get to see her in different outfits and gets mesmerized and when she ask what u thing, u compliment her and in the end she chooses all the clothes and then you realized the bill murdered ur wallet but she is smiling, its worth it
what you think?

**Comment by Rai99** [comment]
These could all fit into a new "Hypotheticals" category where Monika talks and daydreams about the things she could do with you someday. Maybe we could even have some interactivity with the player, giving them options to add to the daydreaming experience. You could have options of what you would do in that situation. 

1. Could be broken down into 3 topics: Dancing under the moonlight, coming home to Monika making dinner and exploring the world.
2. Could be a nice thing for Monika to daydream about.
3. I don't think Monika would go out of her way to talk about that. Maybe she could think about the possibility if it were to happen. 
4. Being fed by Monika could be a topic, but keep in mind not everyone is going to be in school. 
5. I actually don't think there would be much to say about marriage and family. Marriage probably wouldn't change much and it's too early to really think about starting a family. 
6. I'm personally not too sure if I like this one, but I think it might fit and could be done. 
7. I think there's already a topic where she touches on clothes shopping a bit, but this could dive deeper into the subject. The only complaint I have about this topic is that I'm pretty sure Monika would be considerate of your money and wouldn't want you to spend too much on her. Also this sounds exactly just like DDLC: Our Time

**Comment by loverofmonika** [comment]
7. It's similar but not quite the same, shopping for someone u love us a common thing plus in our time Natsuki was there and we get to say" I don't like it ".
5. Maybe not now but the desire is still there, it can be a unlockable. I think Monika would burst into tears to know we want to spend the rest of our lives with her. Altho there is no need to rush but the thought is what matters.
4. Point taken but a still a romantic idea.

7 new contents if it gets approved and other people can add into this

**Comment by MadFoot8** [comment]
### **_Cringe_**

**Comment by ThePotatoGuy** [comment]
A lot of these suggestions seem more in line for a Monika-route style mod.

I see MAS more about spending time with someone you're comfortable with rather than romance.
But we'll see if affection can lead to these scenarios.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
