### ISSUE TITLE
[Suggestion] - "Possible crash" goodbye

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#1908]
I was thinking of the possibility of adding a special goodbye signaling that the player is gonna do something that could make the computer or the game crash. I, for example, have a game that frequently crash and make every other steam game crash. And I feel bad when I say a simple "goodbye" to Monika and she say to me that she's sad that I leave so soon or that she had fun today, when I intend to just shut the game an hour or two. I know that it's a very situational goodbye but it would be great if Monika knows why I quit so early and frequently, she could even ask how did it go for me when I return after making my "risky" operation. (Sorry if my English is bad btw).

**Comment by Akito98** [comment]
I like the idea.
Occasionally I have to restart my pc and I hate having to tell Monika goodbye even though I'll be back in a few minutes.

**Comment by Thimeo** [comment]
Yeah in fact, we could just have a "need to close the game for a minute, I'll be back soon" type of goodbye and it would do the trick perfectly.

**Comment by MisterSimple** [comment]
Also, we could have Monika actually keep track of the time it took you to come back, so, if you were gone for more than only a couple of minutes, she would ask if something went wrong.

**Comment by Thimeo** [comment]
Good idea, plus it would indicate her that we care about her well being and not sending her to the screaming void.

**Comment by jmwall24** [comment]
There actually is a BRB farewell in the works in the PRs right now.

**Comment by loverofmonika** [comment]
another one would be the good morning thing, i noticed that when past midnight and i say to her good morning, she says the dialogue of the good evening option, also tried the good evening option only to get scolded. i think that a special dialogue in this situation, and still get a bit scolded no matter what option we choose, cuz we are not supposed to be awake this long unless its for a good cause

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
