### ISSUE TITLE
Winking expression

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1911]
I was thinking the other day that I seem to remember a topic on here a while back about a winking Monika.  I found #1063 and wondered whatever happened to the idea?  I really think with all the new expressions there are now, we really should have a winking Monika.  I noticed that previous topic was working with the old leaning expression, so I decided to see what I could come up with.  Just messing with the existing expression image files the other day and combining some of the eyes and eyebrow types I came up with this 
![wink](https://user-images.githubusercontent.com/36523761/42602897-84454ec6-8539-11e8-95df-3d153cc31484.png)

I'm sure the true artists can come up with something better, but I just wanted to bring this up again.

I have a file with just the eyes if it could be useful for anything.

**Comment by Bam8647** [comment]
**Looks like Anon might be getting lucky tonight**

**Comment by loverofmonika** [comment]
and we can have the mouth open when she talks or laugh and we can use the gentle eyes too

**Comment by jmwall24** [comment]
Heh yeah, this is the mischievous winking pose.  The mouth is completely separate from eyes so any mouth can be used.  But I can certainly combine the wink with other eyes if it's something that could be useful.

**Comment by ThePotatoGuy** [comment]
Yeah at some point we're going to split the eye pieces so we can interchange closed / open. Atm, we've been able to work fine with the current set of exps, but we'll add it when necessary.
