### ISSUE TITLE
Some criticism to the updated facial expression.

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#1915]
in the happily ever after topic, she starts getting big eyed twice. It doesn't quite match the the emotion of what she was saying. Also, the lines on her face when she blushes doesn't feel right either. The color of the blush was perfect and the blush lines kind of ruin that. And lastly, I love the new smug face added but the smile is kind of uneven and missing the lip shadow. Though all in all, this update, while short, was really well done.

**Comment by AnIdiotsavant** [comment]
just my opinion though

**Comment by Subzerosan** [comment]
Feedback from discord has been noted
closing issue
