### ISSUE TITLE
[Issue] Missing keys in piano for a song

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1923]
So, I was trying to add the song "clair de lune" (The first segment, not the full song) to MAS with the piano. But after figuring out the score, I noticed there are 3 notes the MAS piano can't play. It's a bummer to not be able to add the song just because of those 3 notes. I'm attatching to the issue the score for the song with the associated keybinds. 
[Piano clair.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2196263/Piano.clair.txt)

**Comment by ThePotatoGuy** [comment]
Piano is limited to its octave and a half since the original artist for the piano sprites left the team. Also the piano was made with the number and qwerty rows on the keyboard in mind. Addtional keys would have to be added outside of those rows, which can make the piano more complicated to play.

**Comment by Trilasent** [comment]
![untitled](https://user-images.githubusercontent.com/36512990/43304048-140dd71c-9138-11e8-8a76-db6a9972f2d7.jpg)

**Comment by ThePotatoGuy** [comment]
i think this kind of layout may work. would require a pretty large amount of dev though so low priority for now.

**Comment by Reviani** [comment]
I remember one thing that one game did was that you pressed a button to go up or down an octave. Maybe like, hold the shift or tab key to go up and down an octave respectively, but i donno

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
