### ISSUE TITLE
Everything is small

### ISSUE THREAD

**Issue by Montorni** [Monika-After-Story/MonikaModDev#1925]
So, whenever I try to select a topic to talk about with monika, Nothing shows and it's just little pink boxes that appear with no text in them. That's my only problem with this mod at the moment.
![boxes](https://user-images.githubusercontent.com/39040295/42783278-5bf575b6-8900-11e8-87e1-54777918d9e5.PNG)

**Comment by Montorni** [comment]
!   C:\Users\Worldwide\Downloads\ddlc-win.zip: Cannot open C:\Users\WORLDW~1\AppData\Local\Temp\Rar$EXa0.335\DDLC-1.1.1-pc\game\update\
    The system cannot find the file specified.
!   C:\Users\Worldwide\Downloads\ddlc-win.zip: Cannot open C:\Users\WORLDW~1\AppData\Local\Temp\Rar$EXa0.335\DDLC-1.1.1-pc\game\update\current.json
    The system cannot find the path specified.
!   C:\Users\Worldwide\Downloads\ddlc-win.zip: Cannot open C:\Users\WORLDW~1\AppData\Local\Temp\Rar$EXa0.335\DDLC-1.1.1-pc\log.txt
    The process cannot access the file because it is being used by another process.

And um.

**Comment by ThePotatoGuy** [comment]
See #1275 for a solution.
