### ISSUE TITLE
[Suggestion] Monika's tip of the day 

### ISSUE THREAD

**Issue by MaxCode545** [Monika-After-Story/MonikaModDev#1926]
Just like we have Monika's writing tip of the day we could have Monika's tip of the day but it can only be seen once a day ....... But can anyone remind me where is the guide again to add stuff here? 😅

**Comment by jmwall24** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

**Comment by Rai99** [comment]
I think this idea is similar somewhat to #1195

I'm not sure about this idea since we would need a ton of tips of the day and most people would probably exhaust the daily tips before more get added in, so it wouldn't really feel daily after a short while.

**Comment by MaxCode545** [comment]
Well if everything goes according to plan it is going to be fantastic

**Comment by jmwall24** [comment]
If you need any help with anything feel free to ask here or on the discord server.  Plenty of people have been thru their first times writing new topics and submitting PRs and are more than willing to help with any issues you may have.

**Comment by Rai99** [comment]
I'm curious to see what you come up with. It would be interesting to have something like this, I just don't know if this daily thing will be able to keep up with players.

**Comment by MaxCode545** [comment]
Well most of them aren't mine but I got permission from her to use them they are new ones everyday but I will choose them carefully  it is a Twitter account that is act like Monika so far most of her writing are fantastic

**Comment by MaxCode545** [comment]
When I start I will surely ask for help

**Comment by ThePotatoGuy** [comment]
[Closing since this isn't really a topic suggestion, also not enough tips to really do only once per day anyway]
