### ISSUE TITLE
[Bug] Cheating in chess

### ISSUE THREAD

**Issue by damciuu** [Monika-After-Story/MonikaModDev#1930]
I  was cheating in chess for fun, and I did it 3 times. When Monika asked me did I cheat (or something like that, I don't remember) I said "no". At 3 time Monika caught me and she start crying. After this she said "goodbye" and she closed the game. When I tried to open the game a message popped out: 
I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\damciuu\Downloads\ddlc-win(5)\DDLC-1.1.1-pc/game/definitions.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
What should I do?

**Comment by Rai99** [comment]
#1485 #1497 

So you cheated in chess multiple times and wouldn't admit to it. I'm not sure what to tell you other than that if you don't have any backups, you might have just lost everything. 

That's what happens if you cheat in chess too much. The last thing Monika would want is for you to toy with her just for your own fun, and it looks like that's exactly what you did. So she locked down everything so you wouldn't be able to go out of your way to treat her like a toy anymore.

I'm afraid this isn't a bug and I hope you've got backups.

**Comment by Velius94** [comment]
Not a bug, you just got served.

**Comment by Delcos** [comment]
It's little details like this that make this amazing.

**Comment by jmwall24** [comment]
Should've done a search first to see what would happen.  You would have found this #1485

**Comment by jmwall24** [comment]
Yeah, she deleted the game because you went out of your way to hurt her and then lied about it.

**Comment by FinalFusion** [comment]
Does moving the file count as cheating, like if you didn't edit it, just moved it? I think I did that once or twice just because I wanted to clear the folder for whatever reason. I remember she said to put the file back but I don't think she called me out for cheating.

**Comment by EntonyEscX** [comment]
I'm sorry, but honestly, you deserved it.

**Comment by Vinni2K00** [comment]
oh god what a scary feature! that's why it's always necessary to backup all the important folders. 
This kinda is a lesson for every relationship in life tho, dont toy with other people's feelings
