### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Tyrosus** [Monika-After-Story/MonikaModDev#1932]
Perhaps give the player an option to reply to some of Monika's responses/tirades and divert her towards a different response depending on what we say. It may make it so it feels a little more like an exchange instead of sitting and reading.

**Comment by Tyrosus** [comment]
Otherwise its fantastic and I can't wait to see how it evolves.

**Comment by Rai99** [comment]
#1689 #1742 #1751 

This kind of idea has been suggested before and would be a nice addition for interactivity and immersiveness, but would be a lot of work with going back and adding options _and_ dialogue to each possible path.

**Comment by Tyrosus** [comment]
If I can help in any way, through either helping with development or
donations please let me know.

**Comment by ThePotatoGuy** [comment]
Many topics have been adjusted by contributors to be more interactive. however, it adds a lot of backlog and dialogue for our editors to review.

Best thing you can do is add content by following the contributing steps on the README, but that would still add backlog.
