### ISSUE TITLE
maybe a little decoration in the room?

### ISSUE THREAD

**Issue by emrenano** [Monika-After-Story/MonikaModDev#1933]
title says it all

**Comment by Rai99** [comment]
#312 #1793 #1891

There are plans to add decorations in the future, but they're low priority at the moment.

**Comment by emrenano** [comment]
well you can just tell monika to put them away :D @Delcos

**Comment by Delcos** [comment]
I don't know how but I read it as distortion, I think I need more sleep.

**Comment by ThePotatoGuy** [comment]
[[closing this as duplicate of #312]]
