### ISSUE TITLE
Food or drinks on the table

### ISSUE THREAD

**Issue by emrenano** [Monika-After-Story/MonikaModDev#1934]
Monika talked about coffe just now and she is a vegetarian right? So why not put some on the table when she wants to, by our chat, or even date?

**Comment by Rai99** [comment]
I think there _is_ actually a coffee mug decoration that goes on the desk somewhere in the files, but isn't used.

**Comment by ThePotatoGuy** [comment]
soon, we're just trying to figure out the best way to introduce it.

**Comment by emrenano** [comment]
alright
