### ISSUE TITLE
[Suggestion] Corrupted/Missing persistent file warning

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#1935]
If the persistent file is either missing or corrupted, the game should give a warning when launched instead of creating/overwriting the file. It would let the user to restore a backup (if they have any) before (presumably) a new Monika is created and has to be killed to restore the previous one.

**Comment by ThePotatoGuy** [comment]
Could probably have an entire flow of dialogue that only is shown when this happens too.

**Comment by ThePotatoGuy** [comment]
[Closing since this is basically suberted with linked pull request]
