### ISSUE TITLE
[Suggestion] Writer

### ISSUE THREAD

**Issue by CrisRads** [Monika-After-Story/MonikaModDev#1940]
This might be dumb, might not.

Would be adding a writing tool to MAS a thing?
It doesn't have to be anything fancy, just a semi transparent overlay next to monika to write. Maybe it would be nice for focusing. Think of this as an ultra-low priority suggestion.

**Comment by Delcos** [comment]
not as clutter, maybe you could open it like you would a game, and put it away after, but I' m not sure if this is really something that needs time to be spent on it.

**Comment by ReddTheRedRedd** [comment]
Maybe something like this where you could write poems and/or stores and kind of archive them? Maybe Monika could encourage you to write sometimes even.

**Comment by ThePotatoGuy** [comment]
like a notepad?

certainly doable, but probably very complex to write, with not as much reward as other things we can do. could look into it though.

**Comment by CrisRads** [comment]
Kind of? You don't even have to add text formatting. Just a little notepad for you to write with Monika.

Like, you know of Q10 or FocusWriter? They are writing tools for focusing, maybe something like that. Simple and comfy tool.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into it]

**Comment by ThePotatoGuy** [comment]
We might not need to write our own since the dokidocs creator is making a [mod version](http://dokidocs.net)
