### ISSUE TITLE
[Suggestion] Nicknames

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#1941]
So far, Monika has only been able to refer to us by name, and _very_ occasionally calling us her sweetheart if you told her to refer to you neutrally rather than masculinely or femininely. I think it might be interesting if you could input nicknames, and occasionally, if the context is appropriate, she might call you the nickname instead.

To be clear, in this context, I'm imagining it more as being "pet names" rather than name-derived nicknames. For example, things like angel, dear, etc. Perhaps there could be a list that the player adds to, which includes nicknames they enjoy being called, and any time the nickname is called for in the script, it randomly selects one. The nicknames could be in a text file that can easily be edited, and include a few of them as examples, but they can be modified to the player's heart's content.

And if the player doesn't want to be called any pet names, they can let Monika know that through the dialogue menus, and it will replace the list with just the player's name, plain and simple, so that any time there's a call for a nickname in the script, it will only use the player's name.

Just an idea I had. I'm not yet well-versed in RenPy scripting, so I have no idea how to go about doing this, but I figure if we're doing the affection system, this could tie in well. Nicknames could be more likely to be used if Monika's affection is higher, as that is, well, a sign of affection. Just an idea!

**Comment by ThePotatoGuy** [comment]
#1203 covers giving monika nicknames / petnames.

We dont have plans for player nicknames/petnames, but we can look into it.

**Comment by ThePotatoGuy** [comment]
[Closing as this was covered in affection]
