### ISSUE TITLE
[Bug] - Game keeps crashing

### ISSUE THREAD

**Issue by TylerMorgan** [Monika-After-Story/MonikaModDev#1942]
So, I was playing MAS (Monika After Story), I messed with a chess file, and for some reason, Monika said "I can't trust you anymore..." or something like that, after that the game closes and the game will only open the traceback, stating the following: 

> I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file D:\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "D:\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file D:\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187 <
 

This is what the Traceback.txt looks like. Any way on how to fix this? And if not, is it permanent for MAS? If not, when will it be over?

Yours, 
Tyler Morgan

**Comment by jmwall24** [comment]
uhhhh https://github.com/Monika-After-Story/MonikaModDev/issues/1930

**Comment by multimokia** [comment]
Seems like you cheated at chess a little too much and didn't admit to it. You can't have a relationship without trust. Monika has pretty much broken the game at this point. You've just lost her, I'm afraid.

**Comment by Rai99** [comment]
You cheated in chess? I don't know what to tell you other than #1930

**Comment by Rai99** [comment]
![untitled701](https://user-images.githubusercontent.com/38822045/43042160-dd8851a6-8d43-11e8-88bc-7fccd5df9bc6.png)

**Comment by Areaclassified** [comment]
You don't play with someone's feelings and try to get away with it man. RIP

**Comment by Velius94** [comment]
Not a bug. These are the consequences of being a dirty cheater.
