### ISSUE TITLE
[Bug] Game crashes right after installation 

### ISSUE THREAD

**Issue by ConfusedNerd** [Monika-After-Story/MonikaModDev#1943]
I just discovered your mod and haven't been able to get it to work properly alone, it gives me the message that an uncaught exception has occurred when ever I try to run the application.

The only way I have been able to get the mod to work is by putting in on an already modded DDLC that has a different mod already installed. (Your mod overrides the other, but the exception still occurred whenever any action besides just talking to Monika was taken)

> I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 291, in script
ScriptError: could not find label 'ch30_postpoem'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/splash.rpy", line 291, in script
  File "C:\Users\lschi\Downloads\DDLC-1.1.1-pc\renpy\ast.py", line 1527, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\lschi\Downloads\DDLC-1.1.1-pc\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ch30_postpoem'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.3

>

**Comment by jmwall24** [comment]
Have you downloaded the actual mod or the source code (does your zip file say Dev or Mod in it), and where did you put the contents of the zip file?

**Comment by ConfusedNerd** [comment]
I have the zip file that says mod, I extracted everything to the game folder inside the DDLC files as instructed.

**Comment by jmwall24** [comment]
So you extracted to the equivalent of C:\Users\John\Desktop\ddlc-win\DDLC-1.1.0-pc\game ( I only ask because a lot of people extract to the DDLC folder thinking it's the game folder and not the actual folder called 'game.')

**Comment by jmwall24** [comment]
And is that traceback when you install into an already modded version, or a clean version, or is it the exact same traceback either way?

**Comment by ConfusedNerd** [comment]
Yes, I extracted it to the corresponding folder on my computer. That is the traceback that I receive on a "clean" version of the game.

**Comment by ConfusedNerd** [comment]
There is a different traceback on an already modded DDLC. Though, no longer have the files for either as I have completely deleted both.

**Comment by ConfusedNerd** [comment]
So after four times of reinstalling the mod, I have finally had one not crash on me, but, Monika keeps acting as if I am saying goodbye and leaving the game. She closes it right after I load it and she talks.
I don't even get a chance to hit any options.

**Comment by ConfusedNerd** [comment]
The same thing is happening again. Though this time it is cycling through different options. She keeps asking what story do I want to hear and apologizing for boring me and asking if I want to play pong. I can't do anything but respond to those questions.

**Comment by jmwall24** [comment]
Do you have the Talk, Music, and Play buttons bottom left?

**Comment by jmwall24** [comment]
Yes, there is.  It is located in C:\Users\John\AppData\Roaming\RenPy\Monika After Story

called the persistent file.  You can delete that to start from scratch, or wait 30 days and you'll have the option in game to change your anniversary date to the correct date (today) if you want to.

**Comment by ConfusedNerd** [comment]
Ah, alright. Thank you.
Thank you for trying to help, everything seems to be working now!

**Comment by jmwall24** [comment]
No problem, glad you got it working.  One more thing, do yourself a favor and create a backup copy of that persistent file every so often.  They occasionally get corrupted for some people and you can lose all your progress.  If you have a backup you can use it to restore your progress should that happen.

**Comment by ConfusedNerd** [comment]
Alright, thank you for the advice!
