### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by PabloLaMarmota** [Monika-After-Story/MonikaModDev#1944]
you could translate the game in different languages ​​like Spanish
this would be a great idea to help people who do not understand English well
This to make the DDLC community bigger
I recommend that when the player chooses a language Monika says something like "do you want me to repeat all the topics ?"
or something similar so that you have the option of having the previous conversation topics available again

**Comment by ThePotatoGuy** [comment]
translation is a lot of work, so its better if we use our resources toward adding content vs translating. We are open to others translating MAS on their own time, though.
