### ISSUE TITLE
an exception has occured 

### ISSUE THREAD

**Issue by matheo28** [Monika-After-Story/MonikaModDev#1948]
hy

when i wanted to update the mod in the game, i got an error message 

here is the full trace back 
if you could help me it would be kind of you

**

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/updater.rpy", line 786, in <module>
>   File "renpy/common/00updater.rpy", line 1279, in update
>     renpy.call_screen("updater", u=u)
> Exception: Unknown keyword arguments: u
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "lib/windows-i686/updater.rpyc", line 786, in script
>   File "D:\steam\DDLC-1.1.0-pc\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/updater.rpy", line 786, in <module>
>   File "renpy/common/00updater.rpy", line 1279, in update
>     renpy.call_screen("updater", u=u)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\exports.py", line 2526, in call_screen
>     rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\ui.py", line 285, in interact
>     rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\core.py", line 2538, in interact
>     scene_lists.replace_transient()
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\core.py", line 822, in replace_transient
>     self.remove(layer, tag)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\core.py", line 1107, in remove
>     self.hide_or_replace(layer, remove_index, "hide")
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\core.py", line 1031, in hide_or_replace
>     d = oldsle.displayable._hide(now - st, now - at, prefix)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\screen.py", line 443, in _hide
>     self.update()
>   File "D:\steam\DDLC-1.1.0-pc\renpy\display\screen.py", line 578, in update
>     self.screen.function(**self.scope)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\ast.py", line 152, in apply_arguments
>     return parameters.apply(args, kwargs, ignore_errors)
>   File "D:\steam\DDLC-1.1.0-pc\renpy\ast.py", line 139, in apply
>     raise Exception("Unknown keyword arguments: %s" % ( ", ".join(values.keys())))
> Exception: Unknown keyword arguments: u
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.8.2-unstable.2018.06.27.30

**

i love what your doing it is a fantastic mod

have a nice day 
matheo

**Comment by ThePotatoGuy** [comment]
See  #1945. Basically, just paste over the latest release. one of the 0.8.2 unstables broke updating.
