### ISSUE TITLE
 [Suggestion] Additional hairstyles

### ISSUE THREAD

**Issue by Rigeth** [Monika-After-Story/MonikaModDev#1950]
So far we have 2 hairstyles which is rather nice, but it'd be neat with a few more.
I'm working on twin-tails, but someone with more talent might wanna pick it up.
Tested it out by swapping the filename for torso-down and it seems to work just fine.

![torso-twin](https://user-images.githubusercontent.com/8839663/43176142-c8f2211e-8fc2-11e8-953f-f54a43080a8f.png)
![seemstowork](https://user-images.githubusercontent.com/8839663/43178493-117d7568-8fce-11e8-89e8-572a368ceca1.JPG)

**Comment by Rai99** [comment]
_Thanks for sticking a face and some arms on Monika._

I like this kind of hair, but I think it's too symmetrical. It could use some unbalance or differences from the other side. 

Also, I think the devs are taking it slow with new hairstyles, so I wouldn't expect something like this to be seen for a while.

**Comment by ThePotatoGuy** [comment]
Yeah, we actually have a lot of hairstyles already made, we just haven't decided on how to introduce them and manage them. Having 9 buttons asking monika to tie her hair in certain ways is just not going to cut it.

**Comment by jmwall24** [comment]
I would suggest that Monika decides how she wants her hair to look for the most part, and possibly on occasion ask the player to choose (maybe depending of affection level).  That would save having to have a huge hair selection menu.

**Comment by ThePotatoGuy** [comment]
[Closing until we look intoo it]
