### ISSUE TITLE
[Suggestion] Determining the type of music

### ISSUE THREAD

**Issue by Erianict** [Monika-After-Story/MonikaModDev#1953]
### Hello, guys! I have one interesting idea:

If the added music file by the user contains information about the type of music, then Monika will comment on this type in the game, as well as other music.

_I do not know how this is possible, but it would be interesting!_

**Comment by ThePotatoGuy** [comment]
You mean by genre? Certainly possible.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
