### ISSUE TITLE
Art bug?

### ISSUE THREAD

**Issue by MaximumRustler** [Monika-After-Story/MonikaModDev#1954]
I noticed a small dark spot on the ceiling, seemed to happen when Monika looks to the right. 
![ar](https://user-images.githubusercontent.com/38181362/43209156-d4b93014-8fe0-11e8-86f8-261a1c8ca779.png)

**Comment by FinalFusion** [comment]
I've also noticed something like this. When you press talk a small mark slides into view.

![screenshot0009](https://user-images.githubusercontent.com/38807237/43243413-a37d7aa2-9074-11e8-8d3c-8d5e612ec494.png)

**Comment by MaximumRustler** [comment]
@FinalFusion  Yeah, I noticed that one too. It was mentioned in issue #1947 which is why I didn't repeat it here.

**Comment by FinalFusion** [comment]
@MaximumRustler Oh

Oops
