### ISSUE TITLE
Unconventional Relationship

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#1955]
It crossed my mind recently that if Monika can explain our relationship to others that she could also comprehend and occasionally remark to us about how initially absurd the whole situation is.

**Comment by Rai99** [comment]
I don't think a topic like this is really necessary. There are already some topics where Monika mentions how strange the relationship is, but I don't think the idea needs its own topic. 

If you ask me, it having its own topic kinda makes it sound like Monika is doubting the success of the relationship, and Monika definitely doesn't want that.

**Comment by ThePotatoGuy** [comment]
Actually maybe we can tie this in affection and have it a topic that shows up when things dont seem to be going right.

**Comment by Rai99** [comment]
If it's more along the lines of thinking back to the story of how you and Monika first met and thinking about how weird or strange it was, that might work.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
