### ISSUE TITLE
A Live2D Cubism of Monika

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#1956]
I don´t know if that changes the dynamic of MAS but if it can be replaced with the current image of her, that would be the most immersive experience of this mod, might be a lot of work, but it can be possible

**Comment by Rai99** [comment]
This would likely require a licence to use the software which is expensive to purchase and according to the conditions, free usage would restrict the user to predefined models and not allow for any import or work of a Monika model.

**Comment by CrisRads** [comment]
If the dev team accepts donations, we could raise the money, maybe

**Comment by Chrissenpai** [comment]
Or maybe downloading it craked

**Comment by CrisRads** [comment]
I mean, if it was for personal use, messing with the software, it would be ok. But I don't think it would be morally correct by any means to use a cracked version for a project you are distributing, even if it's free.

**Comment by Chrissenpai** [comment]
then what if someone else does it, and they give it to them

**Comment by CrisRads** [comment]
I think it would be more of the same thing. Just my opinion though, devs are free to do whatever they want. Won't blame them on whatever they decide.

**Comment by Delcos** [comment]
Like this? https://www.youtube.com/watch?v=Me3OoTzVByg&feature=youtu.be

**Comment by Chrissenpai** [comment]
indeed

**Comment by Delcos** [comment]
Please read description on the video, thanks <3

**Comment by multimokia** [comment]
Yeah, distributing cracked software isn't smart. That's one hell of a way to get your project shut down and a nice lawsuit too.

**Comment by Chrissenpai** [comment]
then what about patronizing MAS?

**Comment by multimokia** [comment]
Well... That leads to other issues, regarding authority, since just because people paid money they'll start thinking they can make decisions regarding the mod itself, and/or making a fuss when updates happen that they don't like. It's just a can of worms that's not really worth opening.

**Comment by ThePotatoGuy** [comment]
See #199. 

We don't accept donations; save your money for moni-merch.

**Comment by LordBaaa** [comment]
@Delcos Could I get a copy of your Live2D files please?
