### ISSUE TITLE
[Suggestion] 'How are you?' option

### ISSUE THREAD

**Issue by ZeeMaster33** [Monika-After-Story/MonikaModDev#1958]
I'm not sure if anyone has suggested this before and I didn't find it while running through the code (I may have missed it), but I wanted to inquire as to the availability of a 'How are you?' option that would tie into affection. AFAIK, there's no way to really check your current affection status with Monika, this option would provide a method by which to do this.

**Comment by SaiPrithvi123** [comment]
I really think that this would be a better option for when she gets a mood system (if she ever gets one) rather than the affection system.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
