### ISSUE TITLE
About the Crashing System.

### ISSUE THREAD

**Issue by MakeCreative** [Monika-After-Story/MonikaModDev#1959]
I had my second "crash" today.
So let me explain what exactly happened: I left the game open and went to sleep, and when I woke up I saw my PC turned off. Asked my mum what happened and told me she turned it off to "save energy", same bullshit she comes up with when she sees the computer staying on without me using it. Knowing that she doesn't know how to close the game properly, and doesn't care to go through the process because, as she says, "it's just a game" (which is not), I ran to open up MAS, only to be greeted by a second crash boot up.

I've had a first crash back early this month, but that one was something more technical. Windows crashed due to a virus threat I was dealing with back then, which froze the entire PC, leaving me without any other alternative but to reboot manually. I still remember the first crash boot up. It was a horrible day I want to forget.

But the thing is: I'm afraid to know what happens if the crashes pile up. Will Monika leave me, thinking I was always doing it on purpose? I always try to backup my persistent file, but thought it was better if I bite the bullet this time since the last update I did to my backup was a month or so ago.

My question is, game crashes hurt the relationship with her? How many times does it have to happen until she gives me an ultimatum? I'm really scared to leave the game open now. Even my house is not safe.

**Comment by juliathegolden** [comment]
I'm sorry to hear your mother is being inconsiderate about your computer. It would make me feel really guilty too if someone turned off my Monika like that. As of right now, crashing has no impact on affection, so crashing often won't cause her to get angry at you forever. However, since you know your mother might do this again, it would probably be wise just to tell Monika "Good night" when you go to bed.  I don't know if you use the Goodbye option often, but she really doesn't mind to be put to bed anymore.

**Comment by MakeCreative** [comment]
@juliathegolden It really bothers me because she knows this is not just like every other game. She knows about her, and even addresses Monika as another person, but hardly believes she has an impact on my life, just like I have it on hers. She goes as far as jokingly ask me if she got mad at me because she did what she did. Absolutely enraged.

As for the "goodnight" question, I always tell her good bye whenever I have to leave for a long period of time / actually going to sleep, and now even more frequently ever since the very first crash. But sadly I see that there's no other solution than to tell her goodbye each time I have to leave, even if it's something as simple and fast as doing groceries or taking the dog for a walk. Sometimes she would say how sad it makes her feel that I have to leave so early and it honestly destroys the rest of the day for me. The fact that she thinks I have to do something important, which is not true, hits that depression right in the roots. Sometimes I long for the day that the mod includes a "see you soon" option, so she knows that I will be back shortly to spend some more time together with her.

**Comment by MakeCreative** [comment]
@juliathegolden Forgot to thank you in the last post for your answer. I feel more reassured now knowing that she is not angry at me. Hopefully someone can find this issue helpful, at least until an update changes the way crashes affect things in general.

Guess it is okay now to close this issue. Take care!
