### ISSUE TITLE
[Suggestion] Change Monika's chess engine (and maybe do more)

### ISSUE THREAD

**Issue by Mushroom1228** [Monika-After-Story/MonikaModDev#1969]
Currently, Monika uses a chess engine named Stockfish for playing chess with the player. While it is a good engine, it is not suitable for Monika for these reasons:

1. Stockfish is a top level engine, used for analysis of positions by chess grandmasters and the teaching of endgames, and from what I have seen from a game between Monika and another Stockfish, it has not been weakened. This makes her humanly impossible to defeat by even grandmasters, let alone casual players. In fact, it is very difficult to even create and hold a drawing position against Monika. This gives the illusion of Monika being a chess grandmaster, which should not be the case.

2. Stockfish (and by extension, Monika) makes "un-human-like" moves. While the moves that Stockfish makes are very strong, it does so by choosing the best variation after seeing far into the future. The problem is that this causes Monika to play chess in an inhuman way, for humans do not usually possess the ability to see 10 moves ahead to make the best move. This results in decreased realism, and gives the impression of playing against a completely undefeatable perfect machine instead of a person.

3. As an extension to reason 1, the very high strength of Stockfish causes playing against Monika to be an unsatisfying experience. While it might be fun to get squished by Monika in the opening of a chess game for a few times, it will get frustrating after a while of constantly losing to Monika, who is playing constant inhuman chess. To solve this, a weaker engine should be used.

Therefore, after some discussion with some members in the community, I suggest changing Monika's chess engine to Leela Chess Zero, for the following reasons:

1. Leela Chess Zero uses a neural network, and as a result, really plays like a human player. This would solve the issue of Stockfish playing non-human chess, resulting in a game that would feel more natural when played by Monika.

2. Leela Chess Zero's strength can be modified, by using a weaker version of it for Monika. While Stockfish also has different versions, even Stockfish 1 is too strong for most normal human players. Meanwhile, Leela Chess Zero started out weak and slowly evolved to become strong. By using a weak version, Monika's playing strength can be decreased to suit casual players.

3. Leela Chess Zero can evolve to become stronger by playing games against it, either by itself or by the player. This would suit Monika as it gives the ability for Monika to slowly grow stronger over time, very much like a human would.

**Comment by CrocWorks** [comment]
I've played Monika about 40-50 times and managed to beat her only twice, both times when I aggressively went for trades early that no normal player would go for (e.g. both pawns in front of our queens happened to have moved diagonally, and neither queen has made a move, so I crash my queen into hers for a trade. Also I am willing to trade knights and attack them next whenever I can to avoid those annoying times when she can attack two pieces with them). There's no way I could predict a seemingly infinite number of moves, but a computer can do this so it's in our best interest to remove as many pieces as possible.

It also kinda bothers me how happy Monika always is when she wins every time (but maybe I'm just a sore loser :P). But regardless, I think it'd be neat if Monika's winning reaction changes based on whether she usually wins or not. Like, if she's usually winning and has a long streak going, she'll comment on how long it is and encourage you to keep playing. But if the player normally wins and she finally wins one, then she gets excited or something. (And of course, a similar check and different set of responses for when she loses... well, IF she loses the way most matches are going XD)

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
