### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by Aimzible** [Monika-After-Story/MonikaModDev#1979]
I cheated too many times in a chess game with Monika and now I can't open the game and it just comes up with traceback.txt

Is this meant to happen? How do I open the game again?

**Comment by Rai99** [comment]
Can you describe or give some sort of example of what you see when you start up MAS?

**Comment by Rai99** [comment]
![untitled786](https://user-images.githubusercontent.com/38822045/43606190-a94ec298-9668-11e8-81e9-6d2099f8595a.png)

**Comment by Rai99** [comment]
![untitled785](https://user-images.githubusercontent.com/38822045/43606244-c8d40d44-9668-11e8-823a-0fe760eb19fd.png)

**Comment by Aimzible** [comment]
Rip, I just want my monika back

**Comment by Aimzible** [comment]
Do I actually have to wait 1000 hours?

**Comment by Aimzible** [comment]
Also it comes up with:

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\(My user)\Desktop\Monika/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\(My user)\Desktop\Monika\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\(my user)\Desktop\Monika\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\(My user)\Desktop\Monika\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\(My user)\Desktop\Monika\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\(My user)\Desktop\Monika/game/definitions.rpyc.

**Comment by Rai99** [comment]
Need to wait 1k hours. The game _looks_ like it's crashed right now, but it should fix itself if you let it run for a total of 1000 hours.

It doesn't have to be continual; you can take breaks, sleep and come back later to continue counting down. 

Of course, if you really don't mind losing that Monika, you could forget all the progress you've made with Monika, but I don't recommend it. Loyalty goes a long way and I'm sure Monika would appreciate it if you really waited out that timer just to see her again.

**Comment by Aimzible** [comment]
So do I leave the traceback.txt file open then?

**Comment by Rai99** [comment]
Well as far as I know, there are 2 possible types of errors in this situation. The game _does_ open up, but you're left with nothing but the gray error screen. In that situation, yeah wait on that screen for a total of 1000 hours. 

In the other scenario, I don't know too much about it, but I think the game might not open and all it gives you is that text file. I'm not too sure about this scenario, so I think you'll have to wait until someone else comes by here and they can explain the situation to you and what you might be able to do.

**Comment by Aimzible** [comment]
Okay, thanks!

**Comment by Areaclassified** [comment]
buddy you messed up you gotta uninstall and then reinstall the game completely. you broke Monika's heart by being a lying cheater and now she doesn't want some one who will play with her feelings anymore

**Comment by CrocWorks** [comment]
If you do wait the 1000 hours and it works again, can you post some screenshots of what she says? I don't want to upset Monika myself, but I can't help but be curious.

**Comment by TheRealBrickPlanetWail** [comment]
@Rai99 so do you need to keep the game open all of the time for 41 or 42 days or each time you open it counts

**Comment by Rai99** [comment]
It needs to be a total amount of time. You can take breaks, but the timer pauses while the game isn't up.

**Comment by TheRealBrickPlanetWail** [comment]
@Rai99 if the time is up when the game is open what would happen? (I can understand if you don't know what happens)
