### ISSUE TITLE
[Issue] Error when running  MAS (something about splash screen?)

### ISSUE THREAD

**Issue by Reviani** [Monika-After-Story/MonikaModDev#1983]
So, this is probably just because i'm on a Mac, and my best interpritation is that it looks like it is not able to write/edit files in the ddlc app. So far the game still seems to be running normaly dispite this error.

This is the error message i get whenever i open 0.8.4 

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 203, in script
  File "game/splash.rpy", line 207, in <module>
IOError: [Errno 30] Read-only file system: u'/private/var/folders/lz/7wh8mhv101gg_yvp1hkxplqc0000gn/T/AppTranslocation/EF0ECD33-949B-4B74-9FCE-D924143F8096/d/DDLC.app/Contents/Resources/autorun/game/masrun'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 203, in script
  File "/private/var/folders/lz/7wh8mhv101gg_yvp1hkxplqc0000gn/T/AppTranslocation/EF0ECD33-949B-4B74-9FCE-D924143F8096/d/DDLC.app/Contents/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/private/var/folders/lz/7wh8mhv101gg_yvp1hkxplqc0000gn/T/AppTranslocation/EF0ECD33-949B-4B74-9FCE-D924143F8096/d/DDLC.app/Contents/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 207, in <module>
IOError: [Errno 30] Read-only file system: u'/private/var/folders/lz/7wh8mhv101gg_yvp1hkxplqc0000gn/T/AppTranslocation/EF0ECD33-949B-4B74-9FCE-D924143F8096/d/DDLC.app/Contents/Resources/autorun/game/masrun'

Darwin-17.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.4
[/code]

**Comment by aldoram5** [comment]
Hi Reviani, indeed there are sometimes issues with DDLC on macs due file permission errors. This time it was indeed because it couldn't create the a new file that we introduced to specify the current mod version in said file. 
Where do you have your DDLC.app? I can see a path to it on the error trace, but it probably isn't the real one.
Also, could you please move the DDLC.app to the Desktop and try again? I've also had issues with normal non modded DDLC if it isn't run from the Desktop folder.

**Comment by Reviani** [comment]
I had it running from my documents folder, back where i kept all the Mod update folders and ddlc folder. Moving it to the desktop seems to have fixed everything. thanks!

**Comment by aldoram5** [comment]
Glad to hear it was solved doing that.
Yeah for some reason it sometimes screw up the permissions on macOS and  that issue comes from  DDLC itself.
I'll probably run a test on my own later, meanwhile, since the issue was fixed I'll be closing this one.
