### ISSUE TITLE
[Suggestion] Make a basic search engine for conversation topics?

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#1985]
I recall in a very early version, you could type a question to Monika and she'd identify a keyword which was assigned to a topic and then she'd automatically talk about it. I get that it was scrapped because the conversations didn't seem realistic the way Monika responded sometimes.

I'd like to suggest we bring something similar back, but it instead pulls up all the conversation buttons on the side so we don't have to fish through all the menus. There's so many topics out there and there's so much menu-ing that has to be done that I can't remember how to find them all. Having a way to type out a basic search for them would be really convenient.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
