### ISSUE TITLE
[Bug] exp_previewer

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#1986]
When using the expression previewer dev tool, Monika's hair resets to have her ribbon and doesn't update the monika_hair topic. 

When Monika has her hair down and is reset to her ribbon, the prompt for her hair asks her to tie her hair in a ponytail despite already being in one. as a result, the player must do this and then ask her to let her hair down to return to that hairstyle. 

I know that dev tools aren't the highest priority thing to perfect and a lot of people never touch them, but the exp_previewer is one of the tools that is more likely to be used by contributors and dialogue writers and I think it would be nice to have this small, quality of life fix for them. 

I was thinking either return Monika to her previous hairstyle if it was down, or at least updating the hair topic so it doesn't take twice as long to change back. 

I would imagine it would be as simple as adding these 2 lines at the beginning or end of the tool? 
    $ lockEventLabel("monika_hair_ponytail")
    $ unlockEventLabel("monika_hair_down")

**Comment by jmwall24** [comment]
Also noticed in the expression previewer that it is set as both a pool and random topic, so if anyone has in installed in the version of MAS they use on a daily basis, it can come up randomly on it's own. Should probably just be a pool topic.

**Comment by ThePotatoGuy** [comment]
All dev topics have rando set to True, they are dev topics for a reason so we don't normally expect people to have them.

but i guess we can drop the randos for all of them.

**Comment by jmwall24** [comment]
Cool thanks.  I use the Sprite previewer quite a bit so it's nice to just have it in my normal mas install and not have it be random.  I actually already changed it on my version awhile back.
