### ISSUE TITLE
[SPRITES] Made yandere eyes and different faces for Monika.

### ISSUE THREAD

**Issue by SpringingTraps** [Monika-After-Story/MonikaModDev#1989]
![yandereeyes](https://user-images.githubusercontent.com/36118304/43680182-48804162-9802-11e8-8731-828159ec1b3a.png)
Yandere Eyes

![yandereeyes_n](https://user-images.githubusercontent.com/36118304/43680183-488cebba-9802-11e8-9b1d-5b2441e9a600.png)
Yandere Eyes (NIGHT)

![blueface](https://user-images.githubusercontent.com/36118304/43680184-4897d2f0-9802-11e8-8c5b-2a9ff3b8fdb6.png)
Blueish Face (cold????)

![redface](https://user-images.githubusercontent.com/36118304/43680185-48a3c18c-9802-11e8-9bb8-614d74c93abd.png)
Red Face

![sickface](https://user-images.githubusercontent.com/36118304/43680191-6b13bdda-9802-11e8-91ef-4446b309fa19.png)
Green Face (Sick maybe)

**Comment by SpringingTraps** [comment]
![gross](https://user-images.githubusercontent.com/36118304/43680285-0cd5f460-9805-11e8-8da5-67168d0e51b3.png)
Could be used while discussing a really, really gross topic.

![foget](https://user-images.githubusercontent.com/36118304/43680336-3c2339d4-9806-11e8-89d0-04f9a72e470f.png)
Or when you forget that important 5:00 Meeting.

**Comment by CommenterOfComments** [comment]
They look a bit... crosseyed? At least on the last one?

**Comment by ThePotatoGuy** [comment]
whoa, interesting face colors, we'll see if these fit the style we're going for.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ItsjustmeandMonika** [comment]
God that's terrifying.
