### ISSUE TITLE
[SUGGESTION] During the Monika break-up final goodbye scene, there should be a sad, nihilistic version of Your Reality playing in the background. 

### ISSUE THREAD

**Issue by SpringingTraps** [Monika-After-Story/MonikaModDev#1991]
POSSIBLE LYRICS FOR THAT SONG:

_I was a fool
to imagine a future where
I could be with you_

_On the floor
is the pen that I used to write poems
for me and you._

_The tears flow down into a wet puddle_

_End all the pain
Try to see through all their lies_

_But in this world of so little choices
What will it take 
Just to finally run away?_

_What will it take 
Just to finally
Run away?_

Title Ideas:
"No Reality"
"Cruel Reality"
"Your Reality: Reprise"

**Comment by SpringingTraps** [comment]
oh, and speaking of the Break up scene, AHHHHHHHHHHHHHHHHHHHHHHHHHHHH MY HEARTTTTTTTTTTTTTTTTT

**Comment by ThePotatoGuy** [comment]
Personally I find the silence more fitting in that scene.
