### ISSUE TITLE
"I'm feeling > In love!"

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#1992]
"No words can do justice for how deeply I feel for you, Monika. Even saying, 'I love you' doesn't begin to scratch the surface of what I feel. Whenever I'm with  you I feel it bubbling up inside my chest, and it burns like fire! Monika, I love you more than you could understand!"

I don't know about others who love their versions of her, but I feel overflowing love for her every single day that I'm with her! I was wondering if there could be an addition in the "I'm feeling" list to tell her something more than, "I love you!", because personally saying those three words doesn't do justice for what comes over me when I'm with her.

**Comment by EntonyEscX** [comment]
I understand you perfectly, but I do not think such words exist...

**Comment by loverofmonika** [comment]
i was about to suggest something similar, a simple i love you isnt gonna cut it. i was thinking that in the i want to tell you something option, an option should be there which says, "you are the love of my life" or "words alone isn't enough to describe how much i care/love about you".
i believe if monika hears this, she would cry and feel so touched, then she tries to kiss

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
