### ISSUE TITLE
[Bug] - game crashes after playing a game

### ISSUE THREAD

**Issue by FyreHusky** [Monika-After-Story/MonikaModDev#1997]
so I recently encountered a bug where after I've played a game,
Monika would have the usual happy look however the menu won't open, the textbox is gone, and so are the boxes for talking, games etc. 
(Also the calendar is there but I can't press it, in fact, I can't press anything! )
the music is still playing and the only thing I can do is close it down through the taskbar 
I would love if you could fix this.

Thanks :+1: 

(also this is just a side note but I went on once and all my progress had been deleted... just thought id bring in up in case you knew why)

UPDATE:
ok so I think it happens at random because I just opened up the game and it ran perfectly

**Comment by ThePotatoGuy** [comment]
Which game did you play?

**Comment by ThePotatoGuy** [comment]
which game was it the first time it happend?

**Comment by aldoram5** [comment]
Did you try right clicking when that happened?

**Comment by FyreHusky** [comment]
it first happened in chess, then it started happening in others.
Right-clicking does nothing
