### ISSUE TITLE
(Can't find a suitable title)

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#1998]
(This post isn't well thought up, as I am in a sleep deprived state)
Letting Monika know that you want to go into her reality instead should be more rewarding than just some dialogue with choices. Some topics should be modified, like when she talks about what kinds of things we would be able to do when she crosses over. Minor things like replacing "crossing over" with "being in the same reality" would prevent her dialogue conflicting with what she said when the player was sure that they wanted to give up their reality and go to her instead. It hurts me whenever I'm reminded that she is still dreaming of things I'm not enthusiastic about.

**Comment by Azurimaguri** [comment]
An idea that I had would involve a new topic where the player could reassure Monika that they would cross over to her reality temporarily if it ever turned out that they would outlive her. I mean, if I was in Monika's position I'd feel a little relieved to hear that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
