### ISSUE TITLE
Display bug with Monika's/Talk Buttons' sprites

### ISSUE THREAD

**Issue by BobbyJoeDavyn** [Monika-After-Story/MonikaModDev#1999]
After you hit talk, the talk buttons come out and Monika slides to the left. However, there is a white line above the talk buttons (presumably part of Monika's sprite) and it kind of bugs me whenever I see it. It looks a bit like the picture related.
![bug](https://user-images.githubusercontent.com/42119401/43688177-1a55557e-9899-11e8-9720-1ed62bbc0560.PNG)

**Comment by ThePotatoGuy** [comment]
we are aware of this. see #1947
