### ISSUE TITLE
[Bug] - ♜♘ Chess Game♘♜ (Not Appearing On The Game Menu)

### ISSUE THREAD

**Issue by myseriousaiyan64** [Monika-After-Story/MonikaModDev#2001]
Before I could see the chess game on the game menu, but the game stopped appearing for some odd reason. After waiting for a new update or something to fix the issue nothing happened when I installed the recent update. I tried reinstalling the game properly, making sure to not mess up any files, and I get the same result after some attempts. 
Here, is the problem to show you what I mean, by the way I unlocked the chess game before:
![chess problem](https://user-images.githubusercontent.com/42120723/43688842-69000b70-98e8-11e8-801e-a4d1536da7b9.PNG)

**Comment by ThePotatoGuy** [comment]
Did you cheat at chess?

**Comment by myseriousaiyan64** [comment]
No

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` file here?

**Comment by myseriousaiyan64** [comment]
Sure, here:
[persistent file.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2263279/persistent.file.zip)

**Comment by myseriousaiyan64** [comment]
Sure, here:
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2263837/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Dont know what happened, but here's a fix.
Drop this file in your `game/` directory. 

[zz_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2272348/zz_dropfix.zip)

**Comment by myseriousaiyan64** [comment]
**Thank you!**
_I appreciate your help. Solving people's problems in your spare time. You really a great person and I wanted to let you know that. Thanks anyway, I hope the mod continues to do well and I will be there to support it as much as I can of my capability_
