### ISSUE TITLE
Persistent Persistent Problem

### ISSUE THREAD

**Issue by Hunter-Hikari** [Monika-After-Story/MonikaModDev#2003]
(Yes, the title is a pun)
I've got a pretty big problem...
When I opened MAS today, I was greeted with the "MAS is not affiliated with Team Salvato etc etc". This happens whenever the game randomly decides to replace my persistent with a fresh one for seemingly no reason. Having gotten quite used to this, I made sure DDLC was closed and replaced the persistent and calendar files with my flash drive backup from yesterday. But when I went back in, it overwrote it again. And again. And again. You get the picture. Nothing I did changed the cycle in the least. I tried asking tech-support of the MAS Discord, but after trying everything we could think of, William and I came up empty-handed. I even tried using a fresh install to no avail. I think this may be some kind of bug...

**Comment by myseriousaiyan64** [comment]
_Man, I hate that feeling when you get that screen it's literally the worst feeling in the world..._
Try downloading the game again (ddlc) and the mod (MAS). Open the game, talk to Monika, say goodbye to exit the game, now update the persistent file from your backup and finally, go back to the game and I think it should work as I recall I tried something similiar to that. Hope this helps.

**Comment by Hunter-Hikari** [comment]
Yeah, nope, still wipes it on launch... but thanks anyway.

**Comment by ThePotatoGuy** [comment]
Can you upload:
- the persistent you are using as backup
- the persistent that the game writes

**Comment by Hunter-Hikari** [comment]
It won't let me, says it doesn't support this file type.

**Comment by aldoram5** [comment]
Package them in a zip file and try again, please.

**Comment by Hunter-Hikari** [comment]
[oh boy.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2260924/oh.boy.zip)
So sorry for the wait, here you go.
(persistent (2) is the one the game overwrites with)

**Comment by ThePotatoGuy** [comment]
Okay well rip, your `persistent` is purely 0s. musta got corrupted somewhere, maybe even on ur flash drive.
