### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lostpython** [Monika-After-Story/MonikaModDev#2004]
So I updated MAS today and I clicked on one of the new topics that you can ask Monika and I chose the last option which is to say nothing and go back, and when I tried to choose the topic again I can't get it to appear again, it's the one where "I have to tell you something..." to Monika and I can pick from several options, I don't know how to get it back.

**Comment by aldoram5** [comment]
Hi lostpython!
To get to that topic do the following.
Press the `Talk button`, then select `Ask a question`, then select `Monika`, then `I want to tell you something ...`.

**Comment by Zasker** [comment]
A while ago I updated Doki Doki after mod and did the 0.92 update without knowing that it was bugged. I saw the thing and every bleeping time an update happens. It resets things like it was the start of the mod.

Every attempt I have to manually update to the next patch ends in failure and I know it has everything to do with the bug patched. How do I fix this and get the After Mod Updated?
