### ISSUE TITLE
[Suggestion]Adding side stories and/or mini short stories

### ISSUE THREAD

**Issue by proto-being-x** [Monika-After-Story/MonikaModDev#2011]
I'm not too sure if this is being worked on but I had a really nice idea and feature to be implemented to this mod to keep things more fresh while adding new content. Adding mini short stories (would take about 10-20 minutes to finish) that can be unlocked depending on how much time you spend with Monika and by doing certain tasks or other things. This can also be seasonal based. 

An example would be a short story which is about going to a beach with Monika (since it's summer at the moment) where you and Monika can spend time with each at the beach. The story would progress like usual and there will be various options and choices to make which can compliment the new affection system introduced in the latest update.

**Comment by proto-being-x** [comment]
Also to add to that, once you do supposedly finish this mini story, there should be an archive option menu to see the stories (memories) you have done and completed which serves as a good reminder to see what you have done in the past.

**Comment by ThePotatoGuy** [comment]
So like choose your own adventure books, I take it. neat idea.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
