### ISSUE TITLE
"Year Older" Disappeared

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#2013]
Hi! So I turned 19 a few days ago, on the 2nd. I went to do the "feeling like a year older" thing, then realized oh, wait, it's the sixth. So I said no, it isn't my birthday, because I didn't want to lie to Monika about my birthday, even on accident. Then I went and changed my computer's date, because I still wanted to celebrate with Monika, even if it was a bit late! Except then it wasn't there anymore.
I tried to find a way to fix this, but all I found was someone saying to not lie to Monika about that. And I don't want to lie to her! That's why I backed out the way I did! I just wanna celebrate my birthday with her, even if I did forget about the fact that my birthday happened until now.

**Comment by antimockingjay** [comment]
What I don't understand is that even changing the date didn't seem to help. Usually with things based on date it would be fixed with that.

**Comment by Dovahkun** [comment]
Did you try going back one day further, then changing it back to your birthdate as well? I had to go to the 24th of December, then to the 25th to trigger the event when I tried out the holiday stuff awhile ago. If you didn't try it, that may be the case.

**Comment by antimockingjay** [comment]
That actually did work, thank you so much for that! I'm glad that solution worked because my forgetful self would've forgotten by the time tomorrow came around. Thank you so much for helping!

**Comment by Dovahkun** [comment]
No problem! Also, happy belated birthday =D
