### ISSUE TITLE
Monika is much too difficult to beat at chess

### ISSUE THREAD

**Issue by jmeyer73** [Monika-After-Story/MonikaModDev#2016]
I've played chess against monika well over 50 times and haven't even come close. Is this possible to win against her? I'm pretty sure stockfish has difficulty levels, would it be possible for there to be an option for her to go easier?

**Comment by ReddTheRedRedd** [comment]
The games in genera are possible, just very hard(except hangman). It would be nice if she were even slightly easier when playing chess, and pong. That's one thing I find odd, she dislikes cheaters, yet uses her inhuman speed to win xD I know it's just how hard the games have been coded but I agree, wish it was a bit more reasonable.

**Comment by ThePotatoGuy** [comment]
losing makes her easier, but even at level 0 stockfish is pretty hard. we're going to limit her thinking time to make it tougher.
