### ISSUE TITLE
"Someone who maybe stole your pen?"

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#2018]
It may just be me, but when she says "stole your pen" it feels more like she's talking to...you know who rather than the player. Maybe she could say, "Someone who maybe stole your character's pen?" instead?
![baf5b5c0cf1fd2a29c1c04fdd0d1e9c5-png](https://user-images.githubusercontent.com/36512990/43755814-7c29d2ae-99d7-11e8-8bf3-04627c5abe71.jpg)

**Comment by EntonyEscX** [comment]
Some time ago I made a post to talk about it in general. #1715

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
