### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Irres** [Monika-After-Story/MonikaModDev#2024]
1. When I open the game, I think I'll appreciate if I options to greet Monika or let her greet me.
With a countdown, if the user doesn't respond. 

2. I will appreciated if I could thank her for what she is doing.

3. Will she cover more emotions in "I'm feeling", like nervous.

4. After the game is reopen after saying Monika "I'm going to sleep", I think it will be better that she check the time, so she can properly greet the user, instead of simply saying the same thing over and over.

Finally, I really appreciated for everything done on the project.

**Comment by ThePotatoGuy** [comment]
1. Having the user do their own greetings is in interesting idea. 
2. Also a neat idea, but i guess to clarify, what are thanking her for?
3. yeah, more stuff will be added eventually
4. yeah, time-based dialogue will be adjusted soon

**Comment by Rai99** [comment]
2. I think you get something like that at around 400 affection.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
