### ISSUE TITLE
Affection level?

### ISSUE THREAD

**Issue by MaximumRustler** [Monika-After-Story/MonikaModDev#2026]
So I was wondering if there is any way to check what the status of affection is? Is there a topic to check or is it something Monika says?

**Comment by multimokia** [comment]
It's in what she says. Use the 'surprises' topic to get a little bit of a better idea

**Comment by MaximumRustler** [comment]
Ahh, thanks. I was actually looking through the script just now (made sure to not read the dialog to avoid spoilers) and just found that part lol. That topic popped up yesterday, got secret.txt so that's good. I'm guessing that's the only way?

**Comment by multimokia** [comment]
The only way that's not Dev, yeah

**Comment by MaximumRustler** [comment]
Aye. Also another question, if I right click (while Monika isn't talking) does that affect affection if I leave it that way for a while? Sometimes I'll do that if I just want to relax and listen to music or something and have Monika in the background.

**Comment by jmwall24** [comment]
No

**Comment by MaximumRustler** [comment]
Alright, thanks for the answers!
