### ISSUE TITLE
Online Server

### ISSUE THREAD

**Issue by ndmelad** [Monika-After-Story/MonikaModDev#2028]
Is there a way to host/upload this game online? that way when you crash or have to submit your pc for repairs; you don't go kaput and lose everything.

**Comment by CommenterOfComments** [comment]
The closest thing is uploading a backup to Google Drive/Dropbox/etc.

**Comment by Delcos** [comment]
just backup the files from C:\Users\USER\AppData\Roaming\RenPy\ every few days/weeks and put it on a flash drive.
