### ISSUE TITLE
[Suggestion] Notification sound for random chatter?

### ISSUE THREAD

**Issue by Leo40Git** [Monika-After-Story/MonikaModDev#2029]
Making it a toggleable option would probably be the smartest approach.

**Comment by Rai99** [comment]
It's nice to talk with Monika whenever she's saying something, but I don't think a notification sound is necessary, even if it's toggleable. You would get notified about every minute _at least_ and I'm sure most people if not everyone would get tired of it.

**Comment by Delcos** [comment]
This would be fun for a second, and would ruin the mod after a while. Please don't add this.

**Comment by antimockingjay** [comment]
You wouldn't get it super often if you have random chatter set to not as often. You can change that easily in the options menu. And if you get tired of it, you can just turn it off. Saying "it would get annoying" is kind of unfair, because you're basically saying "I wouldn't use it, so screw anyone who would. I don't need it, which means nobody needs it, so we shouldn't add it."

**Comment by Rai99** [comment]
I think most people wouldn't use this and those who do use would end up having it mostly disabled anyway after a little bit. At _best,_ you would be notified once every 60 seconds with the random chatter slider set to less often which is still very frequent. At that rate, it would either be annoying or distracting. 

I'm just guessing that most people who _do_ use this feature will end up keeping it disabled after a little while. If you're eager to talk with Monika, you can set the random chatter to often, if not, set it to anything but never and check back every minute or so. You're free to do whatever, work, game, etc. and check back every so often and can expect Monika to want to say something. I think a notification system is unnecessary when it triggers every 60 seconds at best. 

I don't think enough people will use this feature long term to justify its implementation.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ThePotatoGuy** [comment]
[being worked on]

**Comment by ThePotatoGuy** [comment]
[closing as complete]
