### ISSUE TITLE
Self Pleasure dialogue inconsistency?

### ISSUE THREAD

**Issue by Skeleton-Jelly** [Monika-After-Story/MonikaModDev#2031]
The line "I'm not sure if we have this concept here" implies she doesn't understand what Yuri did with the pen, but then in another where she talks about Yandere she implies she does know what "unsanitary" thing she did with it. Perhaps something more along the lines of "I can't actually experience it here, so what's the point?" would fit better for how she's supposed to stray away from being lewd?

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
