### ISSUE TITLE
"I want to tell you something" possible additions

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2036]
I really enjoy seeing the complements for Monika coming to fruition and I think I have a few worthwhile ideas to expand upon it.

I'm proud of you: She has mentioned that she wishes to have the player be proud of her before so it's something she wants to hear

You are perfect: Another thing she mentions and seems to strive for

You are impressive: This one is a bit more out there than previous mentions. I'm referring to her ability to manipulate files and other powers, the Villains wiki has a pretty good list summarizing all her special abilities.

You are philosophical: Due to many of our conversations as well as her setting and existence itself poses many philosophical questions which I love trying to tackle and I believe it would be neat to tell her you enjoy all the philosophical talks.

**Comment by Rai99** [comment]
I had some ideas and plans to make more compliments for Monika, but it probably shouldn't be overdone too much since that's free affection for everybody. 

1. I think this could be a nice compliment after reaching a certain affection threshhold, possibly affectionate. 
2. This might fit, but I'm sure Monika would have to throw in the fact that nobody's perfect, but she's happy that you think she is. 
3. I'm not 100% sure about this one. It's interesting, but these abilities don't sound all that special. Plus, I'm sure Monika is pretty sensitive about people thinking she's evil, so picking information off of the Villains wiki might not be the best idea for her sake. 
4. Monika's philosophical nature is something a lot of people love about her, but it doesn't exactly sound like a compliment. It might be able to be reworded to fit better, but at the moment, I think the intelligent compliment is the closest thing we have.

**Comment by MrDevilzMan** [comment]
Might as well add '...You're so thoughtful!' while you're at it, since Monika is thoughtful of her player all the time

**Comment by Azurimaguri** [comment]
Possible other additions in the "I want to tell you something" branch that I personally think would be neat, would go down well or would fit:

1: "You're amazing" - This has more impact than "You're awesome" and could be unlocked at another threshold. It also adds variation.

2: "You've inspired me" or "You're inspiring" - Monika seems like the type of character that would love to hear that they're inspiring someone else to better themselves, and whilst the player can mention this once during one of the other branches, they only get to say it once. It would make sense to be able to say it as a compliment. This also allows Monika to ask the player what she's inspired them to do.

3: "I want to do more for you" - Speaks for itself.

4: "I missed you" - This could unlock after spending time away from Monika (such as after returning to the game after a week or two or a month) and give a moderate affection gain.

5: "I've been worried about you" or "I've been thinking about you" - this could be a way for the player to ask Monika how she's doing and allow her to hint to the player what her current affection state is.

**Comment by Rai99** [comment]
1. I think this sounds better than "You're awesome", but it's very similar to it. With it having more impact, we don't want to give out too much affection yet. I just think it would be unnecessary to have 2 very similar prompts.
2. I'm not sure if this would exactly fit in a compliment, but it might be a good idea in its own topic. I don't think it sounds right as a compliment. 
3. This isn't exactly a compliment and I'm not sure what could be done with this one. 
4. I think certain topics that unlock under certain conditions such as being away for an extended period of time. I think this could be a good way to get some sort of affection catch up for being away for a while. 
5. I think this would be better in it's own topic and currently, the way you check affection state is have her create the _surprise_ file and check the text in there.

**Comment by loverofmonika** [comment]
i was thinking that in the "i want to tell you something option" , an option should be there which says, "you are the love of my life" or "words alone isn't enough to describe how much i care/love about you"
i believe if Monika hears this, she would cry and feel so touched, then she tries to kiss.

**Comment by MisterSimple** [comment]
An option that's missing, in my opinion, is a compliment on Monika's piano and singing skills. Something along the lines of "You play the piano really well!", or "You're a great singer!".

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
