### ISSUE TITLE
Does Monika admire someone prestigious?

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2038]
More like if she admires someone who wants as a mentor or something like that, like: shes likes playing piano and wants to be better at it, so she searches someone that inspires her, like Yiruma for example, and add some information about it as why she follows him to get better; also because that´s one of the ways that monika does to keep herself sane, is because she is always learning new things and i think also that´s also one of the reasons that she wants to do it is because she wants us to be proud of her

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
