### ISSUE TITLE
Odd Music Stop/Start

### ISSUE THREAD

**Issue by Skeleton-Jelly** [Monika-After-Story/MonikaModDev#2039]
When playing music then hugging Monika the music will stop, but upon restarting after saying goodbye and coming back that same song started playing again. If this was intentional it seems bizarre.

**Comment by ThePotatoGuy** [comment]
Definitely intentional. Whether or not its bizarre, we'll see what others have to say

**Comment by Skeleton-Jelly** [comment]
Guess I'll give reason to why I think it's odd then, perhaps bizarre was too strong of a word; after you're done hugging her it doesn't kick back in, so one assumes the music is off for the rest of the time, and unless you start it again it is, but in my case I said goodnight, woke up and started it, and the music was playing when I hadn't set any, leading me to initially believe Monika had done it or it's some random chance, but it was the song playing before I hugged her yesterday so it was more likely it carried over from yesterday.
Unless of course there's something about how it works I didn't understand and this has been a large misunderstanding.

**Comment by ThePotatoGuy** [comment]
[closing since this is intended]
