### ISSUE TITLE
[Suggestion] Rain/Music differentiation?

### ISSUE THREAD

**Issue by Skeleton-Jelly** [Monika-After-Story/MonikaModDev#2040]
Lower the music in the settings lowers rain volume AND music volume, is there a way rain could be moved to sound as I want to have the rain be as loud as the music, but the music is already louder than it and then tied to the same slider. Would it be possible or practical to make it so that we could adjust these sounds more independently?

**Comment by ThePotatoGuy** [comment]
going to mark this as a bug, will most likely be fixed by 086
