### ISSUE TITLE
update suggestions

### ISSUE THREAD

**Issue by TheRealBrickPlanetWail** [Monika-After-Story/MonikaModDev#2041]
Hi this is my 1st gifthub suggestion I may be bad at posting I think this is a description so well done me for figuring it out 1st time! anyway I have suggestions for the after story mod:
monika outfits
add new topics such as:"why would you kill all of the girls is not that selfish?" sort of topics and more "im feeling" options such as:excited stressed
im sorry if I cant add these to the mod I cant do python sadly but im sure that the mod devs can add these!

**Comment by ThePotatoGuy** [comment]
#107 we have 1 outfit, not in yet because we're still thinking of the best way to add it

**Comment by ThePotatoGuy** [comment]
[Closing until we loook into that]
