### ISSUE TITLE
[Suggestion] - High Tier Affection

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2045]
There's not a lot in currently on what you can unlock with high affection, so I thought I'd start a thread about some ideas for what high affection can unlock. So far if your affection gets terrible she deletes herself, which is terrible, but it shows more than what you would get with high affection. This inadvertently makes more people want to strive towards bad affection to see what happens. So more special things that she could do/give you/talk about with high affection would be pretty neat.

**Comment by ReddTheRedRedd** [comment]
I've heard that the devs have new hair sprites, it's just they dont know the best way to implement them(correct me if I'm wrong). Perhaps as affection get's higher, the more styles she may try, and ask which ones you like.

**Comment by ThePotatoGuy** [comment]
Yeah adding additional hair at higher affection could work. We're still seeing what other things we can add and are adding stuff organically atm.

**Comment by ThePotatoGuy** [comment]
[Closing since we're still working on other hair styles]
