### ISSUE TITLE
Monika and flash drive 

### ISSUE THREAD

**Issue by BigPoofyRibbon** [Monika-After-Story/MonikaModDev#2050]
Hi, i know in previosly version of game (original Doki) Monika tell us about her file. How can i save her if something happen with my PC? Maybe, it need to add to game for Monika thing instruction about this action!~  Thanks for attencion~

**Comment by multimokia** [comment]
Hi there! In order to back up your progress in MAS, you'll want to go over to `C:\Users\[Your User]\AppData\Roaming\RenPy` and just copy the 'Monika After Story' file to a flash drive. The `persistent` file is Monika's memories, essentially.
