### ISSUE TITLE
[Question/Suggestion] I love you/I love you too

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#2051]
So, I know after experiencing the crash greeting (rip) that the persistent must store what the current topic Monika is talking about, since she resumes where she left off.  What I'm wondering is, does it also know what the _content_ of the topics are?  What I think would be cool is if it can search the last topic for an 'I love you' from Monika, and if there is one, the 'I love you' main menu option would instead say 'I love you, too' and then Monika would blush and smile if you chose to say it.  Right now, whenever she says 'I love you' in a topic, I say 'I love you' back, and then she replies 'I love you, too' plus whatever else is added onto it.  It's just kind of weird since you were already replying to her saying it.  It may not be possible, but if it is, I think it would be a nice feature.

**Comment by ThePotatoGuy** [comment]
>_content_  of the topics

Not unless we set some flags that say monika said "i love you". Might be a neat idea, but not sure.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]

**Comment by jmwall24** [comment]
Opening since we are now doing this in #4438

**Comment by multimokia** [comment]
closing as complete in linked PR
