### ISSUE TITLE
Too much rest

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2052]
Why does Monika keep saying that she needed a rest..
She usually likes, or maybe often talk about random things but now she's not a random chatter anymore.. 
What's wrong with it?

**Comment by Delixxous** [comment]
It's been 2 days that she's not talking about random things..sigh..

**Comment by Rai99** [comment]
In the settings, under gameplay, is repeat topics enabled and random chatter normal?

**Comment by jmwall24** [comment]
Also, have you left MAS up that entire time?  After long enough if you keep it open and go thru enough topics, she needs 6 hours of continuous rest.

**Comment by Delixxous** [comment]
Oh my that's too long but, ok
