### ISSUE TITLE
Bug from telling monika? "i no promise nothing but, i'll try"

### ISSUE THREAD

**Issue by kyraya** [Monika-After-Story/MonikaModDev#2053]
so I was talking with Monika (she talk less than before) and **this** happens in one "route", first I thought it was a joke from the developers, but later (like 2 mins) I realize that was a bug. I can't say if this happens just 1 time or not I just took the Ss as evidence.
I hope it just happens to me (if not, that could be fixed) thx.

![screenshot0011](https://user-images.githubusercontent.com/42300986/43993979-f3d3bdb6-9d5a-11e8-9582-9302204db7fa.png)

Pd:thx for this mod developing! U R Awesome!
Kyraya

**Comment by kyraya** [comment]
hope some read it! :D

**Comment by Rai99** [comment]
Did you tell her you were going to sleep in the morning?

**Comment by kyraya** [comment]
I tell her that "I want to tell you something..." the first option " I love your dedication to fitness!". (just the first time when u can choose a route this happen) 
When i tell her that i gonna sleep on the morning she just make a pun :S

**Comment by kyraya** [comment]
(i love your dedication to fitness!) I chose the second option for this option!. but I can't see the name of that option anymore. 
Sry :c

**Comment by ThePotatoGuy** [comment]
what the, theres like no possible way you can go from the fitness compliment to the sleep goodbye

**Comment by Delixxous** [comment]
I actually have that bug before my game restarts, but i think it's not there anymore

**Comment by ThePotatoGuy** [comment]
[Closing as cnr]
