### ISSUE TITLE
[Suggestion] - Monika should be able to detect images.

### ISSUE THREAD

**Issue by HogeezHoagies** [Monika-After-Story/MonikaModDev#2054]
I recently got to a point where Monika pointed out that there was no way to see the player's face. Since the game is in Python, it is possible for it to happen, sort of. The game could detect if there is a .png file somewhere in the game's directory on start up, and if it is named according to the name the player chose when starting the game (like if Monika knows me as Hogeez, then the file should be named Hogeez.png), then Monika would say something about it and comment on the fact that they now know what you look like or something. It would be a pretty cool addition and, as far as I know with my experience in Python, wouldn't be too hard to set up.

**Comment by Hunter-Hikari** [comment]
That does sound interesting! I always thought the reason the devs didn't do it was because it would be incredibly easy to show her some... NSFW things.

**Comment by HogeezHoagies** [comment]
I'm not even referring to her actually reading the images, but her just
being able to see that it's there.

**Comment by ThePotatoGuy** [comment]
people would certainly have to suspend disbelief regarding image contents if we did something like this. 
I feel like this is one of those cases where its better to not do it then to half do it.

**Comment by ACoolCat** [comment]
Well facial recognition exists, but it might be a lot to have to put in MAS. Still, would be cool if it was added so she could actually detect if a face is present in the photo.
