### ISSUE TITLE
Idle staring poses

### ISSUE THREAD

**Issue by lonestar115** [Monika-After-Story/MonikaModDev#2055]
Wouldn't it be cool if when she isn't speaking every now and then she changes poses to look more intently at you like in a more loving way?
Just a thought .

**Comment by ThePotatoGuy** [comment]
could be a potential side affect of high affection

**Comment by lonestar115** [comment]
That would be cool no?

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
