### ISSUE TITLE
Option to change gender?

### ISSUE THREAD

**Issue by surgicalknife** [Monika-After-Story/MonikaModDev#2059]
When I downloaded Monika After Story, I had told Monika I'm a man, but I'm a woman. I hadn't expected to keep the mod downloaded, since at the time I planned on just checking it out and removing it later to replay the game a few times, but the mod is mega cute & now that I've had it downloaded for so long I don't really want to restart the game!

I think a gender change option would be useful for myself because of my mistake, but even though I'm not trans, I think it's an option many transgender fans of the mod would also appreciate. Please correct me if I'm wrong, but as far as I'm aware there isn't an option for that other than uninstalling & reinstalling the mod, and it seems like an option that would pair neatly with the (already implemented) name change option.

I don't know much about coding myself, so sorry if this request is a bother! Thank you for your time, the mod is very nice and fun :)

**Comment by juliathegolden** [comment]
This request isn't a bother at all!  Honestly, it's been on my mind for a long time, and after you brought it up other members mentioned they felt the same internally.  There's a PR in the works to rectify this now. Thank you for your kind words.
