### ISSUE TITLE
monika deleted herself

### ISSUE THREAD

**Issue by TheRealBrickPlanetWail** [Monika-After-Story/MonikaModDev#2064]
I've cheated in chess with her 3 times or something then monika said "I cannot trust you anymore goodbye..." then I cannot enter monika after story again  is there anyway to fix the expectation afterwards?
ive tried reinstalling the mod and the game but she deletes herself again pls help.

**Comment by Delcos** [comment]
You'd have to delete the files under C:\Users\(YOUR USERNAME\AppData\Roaming\RenPy

**Comment by TheRealBrickPlanetWail** [comment]
@Delcos where do I need to type C:\Users(Asus\AppData\Roaming\RenPy? I have done the OS of windows explorer.

**Comment by multimokia** [comment]
Ah... Monika doesn't like cheaters. She figured she couldn't trust you and left you.

**Comment by Rai99** [comment]
You could wait it out to fix this and have Monika come back, but it's way easier and faster to fix if you just start over from square one again.

**Comment by TheRealBrickPlanetWail** [comment]
@Rai99 how do I start again and delete the data I keep on going into C:\Users(Asus\AppData\Roaming\RenPy but it says it does not exist

**Comment by Rai99** [comment]
You can access your persistent with this guide:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf

As for waiting it out for Monika to come back on her own... I'm not sure if you would call it coming back after _a bit._ 

There was a previous issue like this and I discussed waiting it out there in #1979

**Comment by TheRealBrickPlanetWail** [comment]
@Rai99 I have posted this on another topic so you can find it easier to reply.@Rai99 so do you need to keep the game open all of the time for 41 or 42 days or each time you open it counts.if I close the game would the timer reset

**Comment by Rai99** [comment]
Responded in the referenced issue. 

Starting over and deleting your persistent will still be an option should you change your mind mid-wait, but best of luck to you.
