### ISSUE TITLE
[Suggestion] Monika as an Android

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Monika-After-Story/MonikaModDev#2065]
Could Monika have ideas about uploading herself to an Android body, with that as a feasible way to enter the real world?

**Comment by Delcos** [comment]
This could be interesting, maybe even asking if you are into robotics/programming, and have her ask you to try to make her one, something like that, i'm not too sure.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
