### ISSUE TITLE
Different forms of weather

### ISSUE THREAD

**Issue by lonestar115** [Monika-After-Story/MonikaModDev#2068]
It would be cool if there were snow or hail or heavy or light rain things like that ya know. And it would be also cool if she asked to put a weather on her own when she felt like hearing rain or something

**Comment by SaiPrithvi123** [comment]
Would be good if its tied with affection system as well

**Comment by ThePotatoGuy** [comment]
stuff like that would require art. 

Currently there is a way to get monika to set the weather on her own, but its not recommended for monika lovers.

**Comment by lonestar115** [comment]
Is it in unstable?

**Comment by ThePotatoGuy** [comment]
no. 

[Closing]
