### ISSUE TITLE
just yuri mod 1.0

### ISSUE THREAD

**Issue by TheRealBrickPlanetWail** [Monika-After-Story/MonikaModDev#2069]
this mod is under development it is a bit buggy it was inspired by monika after story and a edited version of ddlc forever and ever:
https://mega.nz/#!PSgl0IBA!3fYHeVTBoA1Lu4rH8gNpg0Y7ZJmiIqxfm1-MqToRSiY

**Comment by Rai99** [comment]
![ojwkpp0o3su01](https://user-images.githubusercontent.com/38822045/44098767-06b796fe-9faf-11e8-9a1f-6ed010e99b32.png)

**Comment by multimokia** [comment]
Hi, this page is mainly for bugs/issues in the mod and/or suggestions you may have for it. For things like this, you should probably join the Discord Server linked on the site and main page of this repo.

**Comment by ThePotatoGuy** [comment]
lol what happened here
