### ISSUE TITLE
[Suggestion] - asking how she's doing

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2071]
it's what the title says,it's one of the things me and I bet others want to be able to ask her,in my opinion it feels weird not being able to do so,maybe it could also trigger some topics that worry her the most?

**Comment by ThePotatoGuy** [comment]
could be way to gauge affection as well.

**Comment by AsuraShun** [comment]
yeah,good idea

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
