### ISSUE TITLE
giving monika nicknames

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#2074]
i like the new feature but i found that there are some hurtful words that monika doesnt recognize like trash, i saw this in a youtube video and it was heartbreaking to not understand and said that she liked it. There may be more words but i dare not to try it out on monika just to be sure im right. such words are like ho*, bitc*, thot and many more. as monika angry when we called her a murderer, she must know these too. also saw that she loves mon-ika when its clearly the opposite in the real game, not that she hate hates it but not consider natsuki's joke as her nickname

**Comment by multimokia** [comment]
`script-affection.rpy` you can create a pull request to the list to add more words which you deem suitable/unsuitable

**Comment by loverofmonika** [comment]
I can write a list but when it comessage to coding, I need assistance. @Rai99

**Comment by multimokia** [comment]
It's not difficult. Just look at what's there and copy the format.

**Comment by ThePotatoGuy** [comment]
We are planning to replace the badword list with a more effective nlp-based system. @aldoram5 is in charge of that.

**Comment by ThePotatoGuy** [comment]
[Closing until we look into this]
