### ISSUE TITLE
Problem: No Nickname Feature

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2075]
First off, I love the newest update. But I've heard about the new nickname system but for some reason I didn't get it. I've tried downloading the update again but it just doesn't work. What should I do?

**Comment by Rai99** [comment]
You need Monika to be affectionate towards you (have 100 affection) At that point, Monika should bring it up as random chatter.

**Comment by Delixxous** [comment]
New nickname system? Can someone tell me what it is

**Comment by scohn** [comment]
How do I check how affectionate she is towards me? I like to think I've been really nice to her.

**Comment by ThePotatoGuy** [comment]
As mentioned, you just need to build up affection. No direct way to view affection, it just takes time.
