### ISSUE TITLE
Editing and naming your own calendar

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2078]
No, this is not an issue. It's my request! Maybe..

What if we can edit monika's calendar! 
Maybe we can add our birthday so that monika will know and celebrate it?
Or Traveling, graduation, holidays, Back to school or maybe exams for those who are still studying in school and hanging out at others house! Gosh, i'm not forcing you guys.. Just what do you think about it?

**Comment by ThePotatoGuy** [comment]
Adding birthdays will happen soon.

Other things / schedule-like things will also happen soon.

Marking this as a duplicate. of #1740

**Comment by Delixxous** [comment]
Thanks dude
