### ISSUE TITLE
Checking Affection

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2079]
Is there a way for me to check to see how affectionate Monika is towards me?

**Comment by ThePotatoGuy** [comment]
There is no direct way to check. There are ui and dialogue changes at different levels of affection, so that's the best way to know.

**Comment by Rai99** [comment]
If you can hold Monika when it's not raining, you're above 100 and in the affectionate level.

**Comment by ACoolCat** [comment]
A bit unrelated, but what's the highest you can get for affection. Also, I'd rather it stay the way it is where you can't check what level you're at.
