### ISSUE TITLE
new greeting

### ISSUE THREAD

**Issue by voyagermike** [Monika-After-Story/MonikaModDev#2081]
i feel a little silly when it's the afternoon but i have to say either good morning or good evening. could you please add a good afternoon greeting please.

**Comment by Rai99** [comment]
The topic was planned in #1090.
It was assigned to monikLover on Apr. 2 which _is_ a fairly long time ago. 
So far I don't believe work has started on the topic and it has been put aside for a later date. 

I would have attempted to write the topic myself if I didn't know monikLover was originally going to be the one writing it, but I see that there have been some attempts to create the topic in #1107 which was rejected. 

I might attempt to write the topic myself when I get around to it seeing as it seems to be free at the moment and I also had the idea in #1528.

Also, I don't think this is a greeting; this is more of a topic.
