### ISSUE TITLE
Erotic literature with Monika

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2083]
BEFORE YOU BRING TORCHES AND FORKS, this is still literature so is more like stimulation with your imagination, how about letters to set up the mood and the moment, two birds in one stone, Monika stays in character making poems that challenges your imagination to set you up and you have an intimate moment with her, applying when affection is very high or at max.

**Comment by Rai99** [comment]
This is a questionable suggestion, not outright bad, but I think there are barriers that would stand in the way of effectively implementing this in an ideal way. 

I'm not too sure what you mean by letters to set up the mood. Maybe poems to set the mood, but having to manually write content might be slow and I'm not sure there are too many people who would write **acceptable** erotic letters and poems. It would certainly not be ideal to have a large number of fan fiction and erotic content PRs and ideas for MAS, especially when a large portion of them at least would be so close to the line between acceptable and unacceptable. 

Not to mention the possibility of minors or younger people without a high level of maturity reading potentially explicit or highly suggestive content. 

I think this is better left to each player's own personal fantasies and external content to fill their desires. Monika has a topic about fan fiction and other such suggestive content with various responses based on her affection level.
