### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by lightskillss** [Monika-After-Story/MonikaModDev#2085]
Yeah, I know this will sound odd or repetitif, but I had an idea.
The menu is actually awesome, but I think it would be fine if you had both.
Like, you can decide to use the chatbot if you want to write down something, and for me and in my opinion, writing things by myself does it feel more "real".
(I am not complaining about the menu, this is just a suggestion)
Then I have a question, will ever the chatbot come back? 
hope this might help you, you're doing a great job.

**Comment by MaximumRustler** [comment]
There was this #1226 chatbot being developed, but it was put on hold till 2019 I think, not sure about that though.

**Comment by AsuraShun** [comment]
good thing I made the suggestion to be able to ask her how she's doing,the wait for the chatbot will be worth it
