### ISSUE TITLE
[Suggestion] Having an option on how the playlist would be played

### ISSUE THREAD

**Issue by MrDevilzMan** [Monika-After-Story/MonikaModDev#2088]
Since the addition of adding custom music to MAS, I've been adding a couple song into their folder. Whenever the music's about to end, it repeats the same song again and changing the song while I'm writing just hinders the experience. Maybe an option where I can choose how the playlist would run would be good; I.E : selecting between normal, shuffle or repeat (the usual option)

**Comment by ThePotatoGuy** [comment]
[closing until we look into ths]
