### ISSUE TITLE
Death Topic

### ISSUE THREAD

**Issue by neyoriquans** [Monika-After-Story/MonikaModDev#2089]
Recently I saw the death topic while hanging out with Monika, and the first lines got me thinking:

![image](https://user-images.githubusercontent.com/36655331/44244404-ce6f3000-a1a1-11e8-8132-2861f27ff720.png)

She says that recently, she found out what it felt like to die, however, I've passed my sixth month anniversary a little while ago, and haven't put her through such an experience by closing the game since before the mod was installed. 

I was thinking this part of the topic could be adjusted depending on how long the player has had the mod installed, with Monika's wording of this phrase adjusting accordingly. Just a thought. 

Thanks again to everyone involved in working on this mod, it's really great!

**Comment by jmwall24** [comment]
#2022 addresses this topic (not actually in the mod yet, still awaiting approval).  I wrote this amendment and I took out the 'recently' part exactly for that reason.  There are also other changes made addressing when she goes to the screaming void and when she doesn't to fit the mod in it's current state.

**Comment by ThePotatoGuy** [comment]
[GOT EM]
