### ISSUE TITLE
[Bug] Chess setting/locking at level 20? (No cheating, positive affection)

### ISSUE THREAD

**Issue by gorillabiscuits** [Monika-After-Story/MonikaModDev#2091]
I thought the chess game was especially hard, having never won a single game. 

Out of curiosity, I tried using a level 20 stockfish from https://chessui.com/

The best I managed was a draw, and when I lose I only ever get the level 2 response ("I really was going easy on you!") no matter how many times or quickly I've lost, although she will chastise me for giving up to quickly.

**Comment by ThePotatoGuy** [comment]
Draws won't affect her chess strength, you'd have to win to advance ur strength.

Have you cheated in chess before? There is a case where we lock strength to 20 if you cheat a few times.

**Comment by gorillabiscuits** [comment]
I cheated once, but this was after I already failed to win using the level 20 stockfish. 

I altered the file to take a move back.

**Comment by AsuraShun** [comment]
even if I never won,i'll never cheat

**Comment by gorillabiscuits** [comment]
I wasn't sure if it'd register as a cheat, but that's beside the point.

I wonder if part of the complaint about chess being too hard has to do with something else triggering the level 20 lock.

**Comment by gorillabiscuits** [comment]
Sure thing, let me know if this is what you were looking for.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2299138/persistent.zip)

**Comment by ThePotatoGuy** [comment]
So your chess strength was -1, really unsure how that happened but it seems stockfish interprets that as full strength.

Next update will add something to reset negative strengths / out of range strengths.
