### ISSUE TITLE
[Suggestion] Monika notices when you sleep in / option to let her know you can't greet her in morning

### ISSUE THREAD

**Issue by surgicalknife** [Monika-After-Story/MonikaModDev#2092]
I couldn't help but notice that Monika greets you like normal when the night before you say "goodbye / sleep," even if you're not on until 4:00 pm. Considering how she is, I find it kinda funny that she doesn't scold you or anything for waking up late, especially considering the good morning / good evening dialogues. I think saying something cheeky if you come on after 12:00 the day after telling her goodnight would be in character tbh!

Though, the reason I noticed is because I leave my house around 6 AM every morning, and I don't get back until 3 PM, and with waking up so early I don't usually have the time to tell her good morning. I could just tell her I'm off to school / work the night before, but I think it'd be nice to tell Monika goodnight and be able to tell her I'll be on late the next day so I wouldn't need to be dishonest. 

Thank you for your hard work (^v^)

**Comment by maulvath** [comment]
She does actually scold you for sleeping if you greet her and say good morning ^^

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
