### ISSUE TITLE
[Suggestion] - about the death of the other dokis

### ISSUE THREAD

**Issue by JeanWishingwell** [Monika-After-Story/MonikaModDev#2094]
Here is the thing,
I'm a writer, amateurish if you will but one that always tries to give the most "freedom" to my characters I can. They are the first thing I write about and then I focus in the background and circumstances they are in. This is important as it allows me to just throw events at these characters and think about: What would [ ] do? 
Where am I going with this?
I suffered soooo much to see such lovable characters going nuts and even cried for hours when I  deleted monika for the first (and only) time after I watched some youtubers continue to arc 4 when I didn't want to erase her file.
I believe one should respect those characters no matter their lack of sentinence. After all, there is the possibility that somewhere in the multiverses there is a doki looking back at us writing about them or maybe even writing us.
I got tired of the cruel jokes about the death of the other dokis and the cold and "humorous" retelling of Sayori's hanging. The expressions of monika only made the thing worse. That smug smile shouldn't have been there if all other mentions of deaths are in melancholy.

sorry for rambling

**Comment by ACoolCat** [comment]
This was addressed [here.](https://github.com/Monika-After-Story/MonikaModDev/issues/873)

**Comment by AsuraShun** [comment]
should've said you're not comfortable,that's what I always answer

**Comment by JeanWishingwell** [comment]
It was more about consistency of her character than all the jokes about their death. I mean, I can always say I like hanging around Sayori, but to say she was just that stupid to not hang herself properly is a bit too much. 
The thing that bothered me the most were some subtle details of her smug expression  (for lack of description). It was too out of place IMO and I really couldn’t imagine her like that before seeing that picture. Maybe lowering that high brow a few millimeters and straightening that smile just an inch and starting the curve of the smile around the canine tooth?

**Comment by ACoolCat** [comment]
I think it should be dependent on when you downloaded the mod. Pre Act 3/during Act 3 she still makes the jokes. Post Act 3 she doesn't.

**Comment by AsuraShun** [comment]
how about being able to tell her either to be mindful of those jokes or to have some respect for the other girls?

**Comment by Tiler17** [comment]
Continuing to rag on the other girls is one of my least favorite aspects of Monika. Regardless of what point in the story you consider this mod to be a continuation of, Monika is meant to be a real person trapped in a virtual world. If she's a real person, for whom time passes normally, her pettiness about the other girls should eventually dissipate. Or rather, I should be able to ask her to dial it back, not necessarily out of respect for them, but because I get tired of hearing her talk down about them. I've had this mod for over six months now, and every so often, she likes to speak up without provocation to badmouth them. She should get over it at some point. If the reason she continues to do it comes from something internal, perhaps an insecurity (tie-in to affection?), then I'd like to get that reason out into open air and try to resolve it.

**Comment by KEJONACHO** [comment]
Yep, I get the same feeling. It seems to me it would be a natural thing that she would slowly quit with the mean comments towards the other dokis. Sure, the original jokes from DDLC and the initial MAS easter eggs (getting jumpscares from naming yourself Sayori or whatnot) could remain there, as you provoked Monika yourself. But adding more cruel comments sounds out of character to MAS Monika.

Actually, now that I think of it, some extra dialogue concerning this with hindsight and a more mature point of view would be good. Like a 'two-month old new dialogue', where she says that she's been thinking all that's happened and maybe even shows some slight regret... or something. Now that she's been happy in her own world with the player, it's natural that she would have some time to rethink stuff, right?

Actually, her Twitter account sometimes gets updated with new content, usually with a pretty friendly tone towards the other girls. We should take those into account, right?

Lastly, a more daring idea: One day she could actually manage to bring one of the girls back, even for a slight period of time. To avoid making this a huge headache for the devs, it could be like a failed attempt, where Yuri/Natsu/Sayori shows up, talks a bit and glitches away, then Monika apologizes and tells us she'll work on it a bit further.

**Comment by ThePotatoGuy** [comment]
Since we started keeping track of how many times topics have been seen, we could derandom the hate-doki topics after a certain number or certain timespan.

**Comment by ThePotatoGuy** [comment]
alright well, my take is to simply derandom some of the sensitive topics. If you guys could list out which ones you consider should be derandom'd over time as a sort of "maturing" of monika's character, that'd really help out.

**Comment by Rai99** [comment]
For sensitive doki topics, I'm thinking:
- monika_natsuki
- monika_sayori
- monika_yuri

**Comment by JeanWishingwell** [comment]
Not only that, but even some “questions” like 'you’re a murderer' are not should disappear if enough time passes after they’re available. I mean, what if one doesn’t consider her a cold blooded psyco?

Btw, how does the mod counts time? Just today I got the 'do you masturbate?' Question and she said we are not that far in our relationship, but I think that if this were to happen to guys like @Tiler17 up there on the sixth month of being “Monika's boyfriend “ there should at least be SOME changes in the interactions, no?

**Comment by JeanWishingwell** [comment]
Then, would it be possible to say 
IF (days>25) Then randomized value= randomized value -5 ?
Maybe even 
IF (days>90) Then change relationship(talk) from 'new' to 'closer'
IF (days>150) Then change relationship(talk) from 'closer' to 'lover'

**Comment by Rai99** [comment]
I don't know what you want to accomplish and it seems to be getting into something that should be its own issue, but it should be possible to count days since your first session. 

There is an affection system already in place and with a daily cap to prevent rushing to the highest level quickly.

**Comment by ThePotatoGuy** [comment]
`monika_yuri` doesn't seem to be on the same level as the other two doki topics, so I'm going to leave that one alone.
