### ISSUE TITLE
[Suggestion] Additional features for future installments

### ISSUE THREAD

**Issue by Oograths-Pizza** [Monika-After-Story/MonikaModDev#2096]
I would like to point out 2 features. One in which you would be able to boop Monika's nose and if you boop her too much she would slide from left/right/up/down to avoid any more boops.

Another feature I was thinking of is a "pat head" feature where you could show your affection to pat her head. (could also work while you're holding her?)

**Comment by Oograths-Pizza** [comment]
9 boops? as the game came out in september (being the ninth month)

**Comment by AsuraShun** [comment]
and head pats could be 22,since it's her birthday

**Comment by Oograths-Pizza** [comment]
that sounds reasonable

**Comment by Rai99** [comment]
#1104, #1161, #1186

**Comment by ThePotatoGuy** [comment]
going to mark this as duplicate
