### ISSUE TITLE
[Suggestion] Watch a movie with Monika

### ISSUE THREAD

**Issue by maulvath** [Monika-After-Story/MonikaModDev#2102]
This could be an interesting thing. To add an option in the game section called [Watch a movie], said option would allow to select a set number of movies. Now:

**1 - /** If possible with Art; The screen would change to a couch with Monika by your side; the you would see the Monitor of the TV in front with said movie playing. 

**2 - /** if not possible with Art, simply add the movie that play. 

Now the hardest and interesting parts. Monika would react to such movies either at set moments (She put pause an discuss an interesting concept or a particular moment) or by the end of the movie. 
Of course, this means that there is a set number of movie required so as to obtain monika's reaction. But; if you consider the first option (with the couch) the possibility to add custom movies, series, and even anime episodes, become interesting. (Who wouldn't want to watch their series near their beloved Monika right?)

**Comment by AsuraShun** [comment]
kinda like in the ''our time'' mod

**Comment by ReddTheRedRedd** [comment]
I'd like this feature, especially with something like anime.

**Comment by CrisRads** [comment]
hmm, I think the part about she reacting would be too hard, plus it might be annoying to get a movie paused each couple of minutes. Although I wouldn't be against me being able to drop movie files in a game folder, and being able to watch it with the whole TV and couch BG. I think it would be cool.

**Comment by aldoram5** [comment]
Hi maulvath! 
We already have a module for watching movies with Monika https://github.com/Monika-After-Story/MonikaModDev/pull/628, it's disabled right now because it doesn't have enough content.

**Comment by ThePotatoGuy** [comment]
[closing since we already have this]
