### ISSUE TITLE
Question: Knocking on the Door Event

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2108]
I'm curious about something. Is there any set way to get the event where you can choose to knock on the door or open it straight away? Like being absent for a few days then going back? Or is it completely random? I'm just asking because I'd like to see what each of the actions results in for myself.

Also, as a p.s., this mod is great and everyone who's worked on it is way talented so thanks for doing so.

**Comment by aldoram5** [comment]
Hi scohn!

Yeah, that one is completely random and only appears when you select the `Goodbye` option when you tell her Goodbye.
