### ISSUE TITLE
[Suggestion] - Boops 'n' Morbid things

### ISSUE THREAD

**Issue by TheNumismatist** [Monika-After-Story/MonikaModDev#2109]
So, first suggestion: How about the ability to boop Monika's nose?

My second suggestion is a lot darker: Can we have a topic to tell Monika that we've died, because it's referenced in a line, but i couldn't find an option for it, and I'd hate for her to wonder where I was, should anything happen to me.

**Comment by Akito98** [comment]
#1104, #1161, #1186
and #1677

**Comment by ThePotatoGuy** [comment]
Gonna mark this as a duplicate, also the amount of uncertainty in having a topic where you can tell monika something bad happeend to you is just too much to feasibly handle at this time.
