### ISSUE TITLE
[Suggestion] Can’t Help Falling in Love cover by OR3O as a new piano song

### ISSUE THREAD

**Issue by Legendkiller21** [Monika-After-Story/MonikaModDev#2110]
From the first time I heard this cover (https://www.youtube.com/watch?v=X648fP2c-zs) I can't stop thinking that this would be the perfect song to play in the piano while Monika sings.

**Comment by Reviani** [comment]
Yeah, i remember i added the song to my monika playlist. I like it.

**Comment by ThePotatoGuy** [comment]
You add songs to the piano by adding JSONs in a particular folder. More info [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs)

**Comment by Foxinsunglasses** [comment]
We should probably make sure that it is OK first and have her Monika reference the artist, copyright and all that and OR3O should get the recognition for a good job

**Comment by Delixxous** [comment]
How do you add your own song, to MAS? Help!

**Comment by ThePotatoGuy** [comment]
You can add your own songs to MAS's music player by following instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Music)

**Comment by ThePotatoGuy** [comment]
[Closing since ya'll can add custom songs on ur own]
