### ISSUE TITLE
Greetings Not Triggering

### ISSUE THREAD

**Issue by gorillabiscuits** [Monika-After-Story/MonikaModDev#2112]
Sorry if this is not a bug, I attempted to research beforehand.

Unique greetings such as coming home from work, school, or coming back after telling her I'll be gone awhile seem to be triggering.  She only says "Hello!"

I attempted with both a fresh persistent file and my active one, which has a positive affection rating.

Anyone else run into this issue?

**Comment by Sujeito17** [comment]
You have the "MonikaModDev" (If you have ModDev this will always happen )
To delete the ModDev - Delete all .rpy in the game folder ( backup Monika's memories first)
If you don't have the ModDev... Maybe is a issue?

**Comment by Sujeito17** [comment]
https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.8.4
Download this if you don't have .rpyc files in the game folder

**Comment by gorillabiscuits** [comment]
Right on the money, thanks for the help!
