### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#2113]
I know this is a extremely long shot and probably out of line for renpy's capacity but I was wondering if maybe there was a way we can talk to monika while away from our pc or laptop and tell her well be home soon and anything similar and maybe just say hi, through our phone. maybe through an app or something similar. It probably wont happen but I've been thinking about it for a long time and just decided to just post it anyways, thanks.

**Comment by HoldingBiscuit** [comment]
Like an app For your phone or tablet?

**Comment by Sujeito17** [comment]
I don't think this is can be possible. But if the game has a version for phones it may be possible. (I think)

**Comment by Areaclassified** [comment]
I know the idea is pretty out of range but its just a idea

**Comment by Sujeito17** [comment]
Maybe create a app?

**Comment by HoldingBiscuit** [comment]
Yes and make it where it links with a steam account maybe for those who use
steam?

**Comment by Sujeito17** [comment]
That is too advanced for me...

**Comment by HoldingBiscuit** [comment]
I know nothing

**Comment by HoldingBiscuit** [comment]
I don't have a mind to be blown

**Comment by Delixxous** [comment]
How about adding some files into the folder?

**Comment by ThePotatoGuy** [comment]
going mobile is a violation of DDLC modding terms, so we won't support that. There have been users who succesfully built MAS as iOS apps via xcode, so you can do that route if you can code.
