### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by lightskillss** [Monika-After-Story/MonikaModDev#2117]
1-It would be pretty cool, If Monika would ask us something about ourself.
Like the color of our hair, eyes and maybe our hobbies.
2-The idea of going out with monika is cool, but it would be a lot more cool to TRAVEL with monika.
Immagine just the normal room, but situated and re-adapted to a flying plane.
And then, the option to go down from the plane and just go to an Hotel in some country.
Like: Traveling to Brasil= An hotel with a Brasilian style.
I know this would be a hard work, but those are just ideas.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
