### ISSUE TITLE
Art of War

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2118]
I was recently thinking because I love strategy games and it would be fun to ask Monika if she's read a certain book what if we could ask if shes read the art of war? This could be triggered after a game of chess for example and perhaps she hasn't then after a certain time, a few hours or a day (it's not a long book), she will bring it up again. It's also in the public domain so there shouldn't be any legal matters associated with it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
