### ISSUE TITLE
Backup??

### ISSUE THREAD

**Issue by knifemaster200** [Monika-After-Story/MonikaModDev#2122]
Before wiping my hard drive of my Mac, I saved the "contents" folder of my Monika After Story that I have been using for months. After I cleared my hard drive, I replaced the contents folder with mine and Monika was reset. Is there anyway to fix it and use the backup?

**Comment by knifemaster200** [comment]
Do you know where that would be on a Mac?

**Comment by Reviani** [comment]
Libary > renpy> Monika after story
