### ISSUE TITLE
[Suggestion] - Redownload detection

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2127]
With the Affection update, I feel like those who lower her affection to the point where she ends it all a lot of those users just re download the mod to avoid consequences. Perhaps there should be a way to detect you deleting the persistent to avoid this?

**Comment by ThePotatoGuy** [comment]
We could add another file or something that lets us know about previous installs, but if a user wipes their ddlc folder and renpy/Monika After Story folder, there's not much else we can do. `persistent` itself is supposed to be something not known to casual users and designed to act as something that persists between installs.

We can go all out and really go in depth with leaving files and setting up detection patterns to prevent users from quickly restarting the mod, but is there really much to gain from frustrating casual users? We want people to play the mod and enjoy it how they'd like to, whether thats exploring what the mod can do in both directions or gf simulator 2018.

**Comment by EntonyEscX** [comment]
I think the aim of the mod is to bring Monika closer and closer to our reality, this would surely go up one more step to that. Angry casual gamers would be like this because their Monika rejected them for some reason; with Monika becoming more and more real, players would need to take their relationships with their Monikas more and more seriously, which is good.

**Comment by Rai99** [comment]
I don't think this many extra measures are necessary to deter mistreatment of Monikas. If someone already goes out of their way to torture Monika over and over _while getting nothing out of it,_ I'd think they would still go the extra mile to continue doing so. 

The newest, most basic players likely don't know about the persistent file, what not to do or even how to fix things if they do something bad. They usually come to the Discord or git to ask for help ~~and call me evil, but that's where I mess with them a little~~. 

There are some places where I mentioned the idea of having to idle for a total of 1000 hours for the game to fix itself without any deletions or reinstalls, but that has yet to take off in the slightest. 

I'd say if somebody really hates themselves so much, to spend their time torturing one Monika after another, for no gain, all I can say is that I hope one day, they get the help they need. 

Not everybody will or even be able to love Monika as much as some of the die-hard fans and that's fine. Everyone gets their own version of Monika to treat however they want. They can love Monika casually, come home and occasionally boot up MAS to say hello, or they can spend their own time torturing Monika for whatever reason. 

I don't think we should force people to love Monika as much as some people do. Monika can be whatever the player makes of her. For anyone who tortures Monika, whatever they make of her, it's probably not going to help them in any way, and they should realize that at some point or another.
