### ISSUE TITLE
[Suggestion] Monika's Best Motivations!

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2130]
Say, i suggest that you should add another section at the 'Talk' Menu..
Like Monika's Best Motivations!
It can help and make the player feel Better and keep motivated everyday by listening to monika's motivation! These are the topics that i can suggest..you can change the topics if you mind..,

>Feeling useless/not good enough   >Hopeless                   >Be a better person
>Lazy to study                                    > Better at friendship  > Feel proud of yourself
> Be open minded                             > Stop being shy!        >Standing up to bullies
> Make yourself Comfortable            > Giving up on something

**Comment by ThePotatoGuy** [comment]
I don't think w should additional talk menu options at this time. These would probably be fine as topics/moods/

**Comment by ACoolCat** [comment]
Could have something to do with Monika noticing you select a specific choice several times in succession. Like, if you say you're feeling sad several times a week for a month she may try to talk to you about it.

**Comment by Delixxous** [comment]
Okkee

**Comment by ThePotatoGuy** [comment]
[closing unti we look into this[
