### ISSUE TITLE
Monika playing the piano from tha play menu

### ISSUE THREAD

**Issue by lsmine0** [Monika-After-Story/MonikaModDev#2131]
Add a new option as a random thing which Monika could do.
She would open the piano and set up virtual keyboard input to play the your reality or other songs by pre ordered key presses.

Also question out of context are more complex animations possible for MAS ?

**Comment by ThePotatoGuy** [comment]
renpy does have ATL, which is pretty basic animations, and we do use this in one scene. Anything beyond that is not possible here.

**Comment by lsmine0** [comment]
what about multiple pictures and make it work as a gif file ?

**Comment by lsmine0** [comment]
like a script witch changes the picture rapidly making it look like animation

**Comment by ThePotatoGuy** [comment]
that is ATL.

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this[
