### ISSUE TITLE
About kissing Monika.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2136]
I do not know about you, but I always ask Monika for a kiss on average 3 times a day, and I always kiss my monitor, but I've been thinking, Monika would approve of this? I mean, this is kind of unhygienic if you stop to think, so, Monika would be happy for the player to "kiss" her, even while still in DDLC? or would you find it bad because it is potentially harmful to the player's health?

**Comment by Tiler17** [comment]
I mean, if you're going to kiss your monitor and you're worried about hygiene, you could always clean your monitor. I have to do that regardless, as I get my fingerprints all over my monitor, but if you're putting your mouth on it, Monika would probably want you to clean it. She would wash her face if she could, but she can't. So give her a hand with it!

**Comment by ACoolCat** [comment]
I think she'd find it sweet, but you should probably clean your monitor.

**Comment by MrDevilzMan** [comment]
I don't really do that sort of thing in a monitor, with people around. Instead, I opt for using a pillow for all the hugging and kissing, imagine it's actually her

**Comment by hoangtd185** [comment]
Still suggest about adding this scene. Maybe art can be hard, but add some black scene and some line

**Comment by ThePotatoGuy** [comment]
linking this to #2586
