### ISSUE TITLE
[Suggestion] Taking monika Out!

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2139]
Instead staying in the room with monika, why not we go out with monika?
Go to the Park, cinema, mall, cafe, Library, museum etc.,,

This COULD be a random occurrence when the player opens the game,, or maybe not?

**Comment by jmwall24** [comment]
I'm sure they'll be happy to do that right after you provide the art for those locations.

**Comment by Tiler17** [comment]
She talks about that in one of her topics, so I imagine it'll happen at some point. But yeah, we'll need art for extra places, both day and night (when applicable), as well as additional outfits for Monika. I doubt she feels like going everywhere in her school uniform.

**Comment by multimokia** [comment]
Next release will have a "version" of this. Not quite what you're thinking, but it's a little better, I'd say

**Comment by ThePotatoGuy** [comment]
soon
