### ISSUE TITLE
[Bug] - Monika brings up topics while I'm looking out the window.

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2146]
So, when I click on a place while looking out the window, Monika tells me about that place, but immediately after she finishes talking, she brings up a random topic. Also, while this happens, I'm able to interrupt her by choosing to stop looking out the window, but after I'm back in the space classroom she continues until the topic is finished.

**Comment by ThePotatoGuy** [comment]
Additionally, it is possible to use talk/play during the islands event.
