### ISSUE TITLE
monika putting up or down when ever she wants

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#2148]
well the title speak for itself, when ever we close the game, sometimes she can put up or down her hair and one of the good times this can be implemented is when its late, she puts down her hair. this little feature would make monika look like she has dept and desires. fleshing out the character even more. the part where its late and the hair is down shows that she is ready to go to bed. what do you think

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this[
