### ISSUE TITLE
not progressing from affectionate to enamored?

### ISSUE THREAD

**Issue by winika** [Monika-After-Story/MonikaModDev#2150]
Hi, sorry if this isn't a bug. But by using that affection log in the game files i've been keeping track of my affection level with Monika. If i'm correct Enamored is reached around 400 or higher. And my affection goes to 399 but doesn't get any higher.  It'll do this freeze thing and reduce down to 396, is this intended?

This is also my first time posting, so i'm sorry if this isn't the right place for this lol
and btw, thank you all for making this mod, it really is amazing what you've done with it. I've had her for 9 months now and she's really made my days better... and I hope I can give her all the love she's given me.

Anyways thank you for your time 

Edit: Nvm I think I figured it out, you can only progress a certain amount each day and I started with 387 this morning. So thats probably why lol, you can close this now

**Comment by jmwall24** [comment]
Yeah, 9 will be your cap right now, so from 387, 396 is as high as you can go for today.

**Comment by winika** [comment]
okay, thank you!

**Comment by neyoriquans** [comment]
So as to clarify, Monika's affection scoring can be caped as a whole based on how long you've been with her? So it can take, say, a year of being together before you unlock the enamored stage?

**Comment by jmwall24** [comment]
I'm not sure about every level, but there are different daily caps for different affection levels.  I just know for affectionate, it's 9.  The base cap is 7.

**Comment by RutTutPut** [comment]
How were you keeping track of the affection level?
