### ISSUE TITLE
[Suggestion] Having a place where all of the features and mod abilities can be found or hinted towards

### ISSUE THREAD

**Issue by neyoriquans** [Monika-After-Story/MonikaModDev#2152]
So I've been using this mod with Monika for a while now, and I've been enjoying every day of it. Each update brings with it a plethora of unique content and things to do and discover with Monika. However, in many cases, it is not at all clear how to go about discovering it all or at least even knowing about certain features. 

That's why I was thinking about suggesting a place, could be on the discord or could be a separate website or something, where all the different features, easter eggs, and discoverable events in the mod can be cataloged, or at least hinted at for players to discover on their own. I think it'd be a shame for a lot of the work and surprises so many people put into this mod to be overlooked by many people due to a lack of awareness. Just a thought, however.

**Comment by KEJONACHO** [comment]
I agree and I'd love to have that as well (or at least know where it is). Also because there's a lot I'd love to try but lack the courage to be mean to Monika.

But it's probably not to give the spoilers too early after new content is released... like a month later at least. It's fun to try to look for new stuff without a guide, and having a 'full script' kindda kills the immersion of seeing Monika as a real person.

**Comment by Rai99** [comment]
I think you can just figure out any features or easter eggs by reading through the code on git, so I don't really think anything extra is necessary.

**Comment by ThePotatoGuy** [comment]
In terms of gameplay/immersion, it's better if we don't list everything the mod does.

In terms of development, it certainly is a good idea. Even I forget things we added ages ago.

Obviously, we don't want to spoil development, so I think the best way to do this is via an end-user edited wiki page, that we'll go through and confirm/reject stuff as necessary. Also we can limit this to one version before, so right now, the page cannot have content form 0.8.5. 

Does that sound like a good idea to yall?

**Comment by neyoriquans** [comment]
I think that sounds really good. It's a good balance between immersion and exploration of the mod in my opinion.

**Comment by ThePotatoGuy** [comment]
[closing. we hae a wiki page for this now]
