### ISSUE TITLE
[suggestion] Monika sleeps when she is held for a certain amount of time when it rains

### ISSUE THREAD

**Issue by CapnRNose110** [Monika-After-Story/MonikaModDev#2153]
Perhaps after a few hours or less of holding Monika, she sleeps. When the player tries to quit that action, she wakes up slightly embarrassed, and a special dialogue for that event proceeds.

**Comment by Rai99** [comment]
I like this idea a lot. I think it might fit in a bit better though after the sleep mode gets added in. Maybe have Monika fall asleep after 20-30 minutes of holding. Maybe give the player a chance to get an option to wake Monika up or let her sleep. They can set Monika down and possibly jump to sleeping mode or if they don't get the option, Monika would wake up herself when the player makes an action. 

Also add different paths based on affection. Maybe have Monika be a little more embarassed if the player can't hold her outside of the rain yet.

**Comment by ThePotatoGuy** [comment]
[closing until we look int ot his[
