### ISSUE TITLE
[bug] Monika's eyes seem to be "off" in this expression?

### ISSUE THREAD

**Issue by CapnRNose110** [Monika-After-Story/MonikaModDev#2154]
Her eyes don't seem to be sort of 'balanced'. The left one seems a bit lower than the right one, compared to her normal expression.
![screenshot 174](https://user-images.githubusercontent.com/25204708/44595064-6643ce00-a7e1-11e8-9f4b-449d3e68463b.png)

**Comment by ThePotatoGuy** [comment]
It looks much weirder perfectly straight, trust.

**Comment by jmeyer73** [comment]
It looks perfectly fine to me, I don't see what would need to be changed.

**Comment by ReddTheRedRedd** [comment]
I noticed that too. I think the thing is, is that one eye slightly off compared to the normal stare art. So when she changes to this art from the stare it seems noticeable. But this art on it's own looks better with the offset.

**Comment by CapnRNose110** [comment]
Point. False alarm.
