### ISSUE TITLE
[Suggestion] "Can we not talk about this?" button 

### ISSUE THREAD

**Issue by CGanimated1227** [Monika-After-Story/MonikaModDev#2156]
Can there be an option to tell her that you don't like a particular topic so that is removed as a random topic until you select it in the talk menu? Monika is supposed to be there for the player. If they are worried about nuclear war/death and don't want to talk about it until they are over their fear, monika shouldn't bring it up. But instead of removing those topics altogether, maybe they can be temporarily removed from the random topics list until the player selects that topic in the talk menu. You can select a button somewhere after she talks about a random topic to determine which topic you don't want to hear or something similar.

**Comment by jmwall24** [comment]
This has been mentioned before in #1405 and #2047 if you want to do some reading on the discussions about this idea.  Not sure if the stance has changed on this or not.

**Comment by CGanimated1227** [comment]
I forget, but is there not a button for the Nuclear war topic or the "what it feels like to die" topic? I was saying it would be added back to the random topics list that monka talks about once you select it in the talk menu. This could be done with a flagging system that will unflag it as a triggering topic and she will be able to talk about it without you starting it yourself. I wasn't talking about removal altogether or a permanent lockout.

**Comment by ThePotatoGuy** [comment]
as i mentioned in the last comment of #1405 , an exclusion menu would be something we'd add a while from now. its just super lower priority
