### ISSUE TITLE
[Suggestion] - Monika passing out

### ISSUE THREAD

**Issue by digiorgnope** [Monika-After-Story/MonikaModDev#2160]
I dont know if this suggestion has bee made before but I think having Monika fall asleep/ pass out would be a good addition. If you dont give her the six hours of rest she needs she would fall asleep and possibly not let you interact or anything until she woke up again or wake her up yourself if you really want to.
Also thank you for all the hard work and effort you have been putting into this. Including developers, artists, and anyone else who has helped this mod in any way. Keep up the good work.

**Comment by ThePotatoGuy** [comment]
See #987.

Marking this as duplicate
