### ISSUE TITLE
[Suggestion] The 'i'm going to sleep button'

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2161]
When the player opens up the game after they clicked the IGTS Button, monika will say things like..

"Did you sleep well?"

"Uuh [name],  did you have nightmares while you're sleeping?" or
 "[name],..Were you having nightmares while you're sleeping?"

"[name] Did you have a wonderful dream?" or 
"Were you dreaming about me?'

the options for the dreams are
 "Yes/ No../ I can't remember"

That's my suggestion, thanks~

**Comment by Tiler17** [comment]
She does have a couple of lines for that. "I hope you had a good rest!", stuff like that. More wouldn't be unwelcome, but I can't remember my dreams 99 times out of 100, so she'd be setting herself up for disappointment an awful lot

**Comment by ThePotatoGuy** [comment]
[closing utnil we look in to this][
