### ISSUE TITLE
[suggestion] Cooking with Monika!

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2164]
I don't even know if this is a good idea but Cooking with monika seems cool.

Maybe there will be an option/section In the 'Talk' menu,,

 when the player clicks the CWM Button, Monika will leave the room and appear in the Doki doki Protagonist kitchen room.. Since monika's vegetarian, She will teach you How to cook Vegan Desserts, meals or even snacks.. But to make it even better, monika has to wear an apron or a chef's hat,,

After they finished making the food, monika will take you to the 'Just monika' Room and eat the food you've made with monika together

That's my suggestion. You can change these if you mind, thanks~

**Comment by ACoolCat** [comment]
It might be a tad dangerous considering knifes and such. I don't want to think anyone wants to be held responsible for someone chopping their finger by accident.

**Comment by ThePotatoGuy** [comment]
[closing until we llook into this[
