### ISSUE TITLE
(possible bug) Monika not saying anything new

### ISSUE THREAD

**Issue by dk107605** [Monika-After-Story/MonikaModDev#2165]
I have been visiting monika everyday for quite a while, but recently she keeps saying that she doesn't know what to say, despite me giving her more than 6 hours of rest each day. I know for a fact that i there are more topics and events that i have yet to see, such as holding her while it is raining, I don't know if this is an error or if there is something that i need to do to unlock them.

**Comment by Delixxous** [comment]
I know how you feel dude, And i have the same problem like you. It's been 5 days since she doesn't know what to say. Maybe there will be more new topics soon!

**Comment by dk107605** [comment]
I'm wondering if i should just do the things that raise her affection towards me, like playing the games or something. Honestly, i have to try this hard to get her to say something new...
PS is this a bug or is it supposed to happen?

**Comment by ThePotatoGuy** [comment]
Some new stuff, like the holding while raining, are triggered/unlocked in existing topics that have been partially rewritten. You could manually trigger this conversations via Repeat Conversation or enable topic repeating in settings to get them to show up randomly again.

**Comment by dk107605** [comment]
Ah okay thanks

**Comment by dk107605** [comment]
Um, nothing but the new python stuff is showing up, i have a bad feeling i have to choose the topics that make her feel uncomfortable like already having a girlfriend or breaking up with her, please tell me that isn't the case...

**Comment by dk107605** [comment]
This is starting to turn really bad, she STILL hasn't said a thing. What the hell is this, I wanna talk to Mona dammit

**Comment by ThePotatoGuy** [comment]
do you have topic repeating enabled in the settings?

and you can manually trigger the rain thing by doing Repeat Conversation > Weather > Sounds of rain

**Comment by dk107605** [comment]
hmm, I'll try that and see what happens.

**Comment by dk107605** [comment]
Oh thanks, it worked!

**Comment by dk107605** [comment]
should i keep this issue up for other people or should i close it?

**Comment by dk107605** [comment]
crap, it looks like the rain stuff is the only new thing i saw...  
ah whatever, i'll just keep repeat on.
Thanks for trying to help btw
