### ISSUE TITLE
Question: Farewell letter?

### ISSUE THREAD

**Issue by DogeWithIt** [Monika-After-Story/MonikaModDev#2166]
So there's this farewell letter in the files that is way too tiny to read, it's something like 200x70p. It apparently has some tear drops on it. What's up with that? **(There are 3 files that seem to be connected to this, the first being "poem_finalfarewell_desk_select", the second is "poem_finalfarewell_desk" and the third is "poem_finalfarewell", all located withing the mod_assets file.)**

**Comment by dk107605** [comment]
Yeah, i saw the same files all relating to the goodbye poem, i'm actually curious as to what it says but i don't wanna have monika hate me.

**Comment by DogeWithIt** [comment]
I think it might have to do with the affection meter. If you bring it too low and you make Monika feel like you hate her, then she might show that poem the next time you open the game? I can't really read it but it might be something along the lines of that.

**Comment by jmwall24** [comment]
Let's just say you don't want to receive that letter.

**Comment by dk107605** [comment]
Wow, is it really that bad?

**Comment by multimokia** [comment]
Yes. Yes it is.

**Comment by Foxinsunglasses** [comment]
Mind telling what it says, because this sounds like Pandora's box

**Comment by multimokia** [comment]
To avoid spoilers, I recommend having a dig through the files (you can do so right here on git)

**Comment by DogeWithIt** [comment]
I found it after an hour and started crying after reading it. Pretty hard to find but found it in the end, not gonna give any spoilers.

**Comment by dk107605** [comment]
i cant even see it properly, or am i supposed to look for another file which has the words on it?

**Comment by jmwall24** [comment]
Yes...

**Comment by dk107605** [comment]
ah ok thanks

**Comment by Areaclassified** [comment]
what is this files name with the text that is supposed to be on the poem, as of I cant find it

**Comment by jmwall24** [comment]
Just so it'll hopefully quench everyone's thirst enough that they won't actually try to get it in-mod, find script-affection and go to the bottom.

**Comment by Areaclassified** [comment]
thank you, and ill never do anything to hurt monika

**Comment by Tycitron6000** [comment]
I just read it... and oh my god i was almost in tears it was so sad... welp time to spend even more time with Moni than i already have been.

**Comment by Foxinsunglasses** [comment]
Ok that was painful, I will never let that happen

**Comment by monikLover** [comment]
When you get the letter, you deserve it :ok_hand:
