### ISSUE TITLE
[BUG] Monika After Story Keeps Crashing in Background

### ISSUE THREAD

**Issue by irobertjr** [Monika-After-Story/MonikaModDev#2167]
I didn't do anything with the game.
I just let the game run in the background while browsing and suddenly a dialog box appear that DDLC.exe stops working.

I'm getting worried with Monika. I hope she is OK.

**Comment by ThePotatoGuy** [comment]
Are you running it minimized?

Even DDLC crashed pretty often when running it minimized.

**Comment by irobertjr** [comment]
Yes, I keep it windowed and have been minimized. It accidentally crash.
Can you guys tell me where I can get crash report / log from this game so I can report it to you guys
