### ISSUE TITLE
Suggestion: New Compliments

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2168]
I was thinking maybe some new compliments to give Monika that could be nice could be stuff like,
"You're so sweet" or "You're too good to me". Since so many of the compliments have to do with her appearance and her intelligence, I think maybe these ones that have to do with her heart would be nice.

**Comment by Tiler17** [comment]
Write some up and submit them as a pull request, then. More compliments would be great

**Comment by scohn** [comment]
Do I need to include some kind of coding language when submitting new stuff like that? I'm not a programmer I was just giving suggestions.

**Comment by Tiler17** [comment]
Me neither. I'd never used Python before in my life, but I just followed the directions in the [contribution guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) and was able to get a new player mood (#1409) put in the game. It's not really too hard, but if you run into any difficulties, you're welcome to ask. I've asked a few questions myself

**Comment by scohn** [comment]
I went ahead and gave my suggestions for compliments under Pull Requests. I'll leave it up to the programmers whether or not they are used. I just really love this mod and wanted to make suggestions to help it grow even though I don't know anything about this kind of stuff.
