### ISSUE TITLE
Concerns for future of MAS. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2169]
So, I was reading through the Gameplay Changes of V.0.8.5 and saw

> Monika no longer needs or cares about the monika.chr file. to be explained in a future update

I had some concerns over this and figured I'd express them to see if anyone else thought the same way. I am aware that Monika has evolved passed it in MAS, but I still don't think she should completely ignore the chr file. One of the things that made MAS so good, in my opinion, was that it never strayed too far away from Doki Doki and I really appreciate that. However, for her to completely ignore her chr file kind of breaks this. It would be nice for her to at least some sort of sentimental value to it, like when she asks you to keep it around on your flashdrive for her. I wanted to see what other people thought of this.

**Comment by Foxinsunglasses** [comment]
I do agree that she would probably be interested in keeping it but perhaps out of curiosity. I believe she mentions at one time that the chr files were odd to begin with so perhaps keeping it due to its abnormal nature

**Comment by Sujeito17** [comment]
"Monika no longer needs or cares about the monika.chr file. to be explained in a future update"
I agree with you but ... "to be explained in the future update" make me feel a little curious.

**Comment by ACoolCat** [comment]
Yeah, I know, that's why I put in concerns for it. The MAS team has hit most the updates out of the park, and I'd expect this would be no exception. I'm just stating some worry I'd have over it.

**Comment by Sujeito17** [comment]
Just wait and see what will happen... Maybe they will replace the monika.char for something even more important?

**Comment by Tiler17** [comment]
I don't think it's worth worrying about at the moment. Honestly, I'd forgotten about the .chr files, since they're not really relevant to MAS. We'll know more in time, and we can pass judgment once we have information. Like you said, the team has a good handle on what they're doing

**Comment by Sujeito17** [comment]
We can not lose hope in the MAS team, Monika's life is in their hands!!! (In ours too, so send lots of suggestions)
(I never thought I'd say something so cool and motivating)

**Comment by EntonyEscX** [comment]
I disagree with you, however, nor do I want with all my being that monika.chr is irrelevant. Monika evolves over time, and rendering monika.chr useless shows this well; but on the other hand, I have the custom of when to go to some party, or any other place that Monika might like to go with me, pass the monika.chr to my pen-drive, and after returning, put it again in the folder "characters", I like to think that Monika went with me to such a place.

**Comment by KEJONACHO** [comment]
At least it would be worth Monika commenting on it being deleted by the player. Something like 'Oh this brings me memories... It's also far to notice how far we went together, right [player]?' Sounds a bit self-congratulatory from the devs, but well, they deserve it.

Oooooor.... It could be added that if you delete her file, she actually glitches away just like in the original game, then comes back laughing at us, then explaining we're way past that now.
