### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by bobisgud** [Monika-After-Story/MonikaModDev#2171]
hi i cant start the game at all because in the event handler script the "_greeting_ourreality_unlock" is not defined?

**Comment by ThePotatoGuy** [comment]
Paste the entire traceback here please

**Comment by bobisgud** [comment]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/event-handler.rpy", line 423, in script
    init 994 python in mas_delact:
  File "game/event-handler.rpy", line 432, in <module>
    1: _greeting_ourreality_unlock,
NameError: name '_greeting_ourreality_unlock' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/event-handler.rpy", line 423, in script
    init 994 python in mas_delact:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/event-handler.rpy", line 432, in <module>
    1: _greeting_ourreality_unlock,
NameError: name '_greeting_ourreality_unlock' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.5
[/code]

**Comment by aldoram5** [comment]
Hi bobisgud!
It looks like you're missing some files in your installation, could you please download [our latest release zip file](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.8.5/Monika_After_Story-0.8.5-Mod.zip), and follow [our installation instructions](https://github.com/Monika-After-Story/MonikaModDev#installation) to install it correctly.
