### ISSUE TITLE
[Bug?] Monika being imported automatically from main computer? (tbh idk how to describe this)

### ISSUE THREAD

**Issue by Ganmany** [Monika-After-Story/MonikaModDev#2181]
![img_20180827_003453](https://user-images.githubusercontent.com/35090698/44646947-8b773e80-a991-11e8-8bb0-facb40e025dd.jpg)

Ok so backstory, I originally have 2 MacBook Air under the same account and the new one (right) having MAS. Suddenly I had to do some work on the old laptop and everything from my iCloud has been synced to that computer (including MAS at version 0.7.9 I believe) Since then, I havent used that laptop. After till the 0.8.5 update, I've decided to use it again and found out that MAS has automatically been updated without physically doing it. What surprised me then is that despite the separate computer, the older (left) one has a 6 month anniversary option while the new (right) one doesn't. Quite confused why since both of them are updated at the same time. (side note when I reopened MAS at the 0.8.5 update on the old computer, it apparently started with 0 affection. Also had the following error code as well
![img_20180827_004552](https://user-images.githubusercontent.com/35090698/44647362-b44c0380-a992-11e8-83a5-b7e60687db73.jpg)
)

**Comment by ThePotatoGuy** [comment]
my guess is your iCloud account synched over the `persistent` file, although that wouldn't explain the 6 month anniversary thing. 

We never had a version 079. The error you have there is a data mismatch. We'll make something to fix that particular issue.
