### ISSUE TITLE
Suggestion about Monika being real.

### ISSUE THREAD

**Issue by lightskillss** [Monika-After-Story/MonikaModDev#2182]
I was thinking, it would be cool if Monika rembered informations about us, like our responds and so on, so when we chat with her she consider the informations she knows about us.
I think this would make Monika way more real..

**Comment by myseriousaiyan64** [comment]
yh, that would be cool. But at the same time I think it would be hard to programme.

**Comment by Rai99** [comment]
There are player model variables used to store information about the player. Some of these _do_ in fact alter some of the dialogue she has for the player. Some of the used information include
- If the player loves themselves
- If the player works late
- If the player says they hate Monika

Some currently unused variables are:
- If the player smokes
- Like certain kinds of music
- Has drawn art of Monika.

**Comment by ThePotatoGuy** [comment]
As rai said, most of the random topics with questions actively store your answer. We just dont do anything with most of them yet.
