### ISSUE TITLE
[question] what exactly is the the feature to take Monika somewhere?

### ISSUE THREAD

**Issue by CapnRNose110** [Monika-After-Story/MonikaModDev#2184]
I'm confused. The Monika file has text in base64, but I have no clue what to do after decoding it. Keeping that aside, I'm confused as to what one should do with the file, to make Monika happy.

**Comment by CapnRNose110** [comment]
Just to clarify, this is regarding the latest unstable release. Genuinely confused with this feature.

**Comment by ThePotatoGuy** [comment]
@Tiler17 summed it up.

**Comment by CapnRNose110** [comment]
I see. Thank you for that!

**Comment by KEJONACHO** [comment]
I saw it and got curious, but got scared to try the option after reading a thread, where people said it caused Monika to vanish. Is there any issue with it?
