### ISSUE TITLE
Suggestion: ‘Unable to sleep’ topic for “I’m feeling...”

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#2185]
Maybe she could suggest a relaxation method to try, or ask you if there’s anything you need to get off your chest, or she could turn on the rain, or even offer to hold you (maybe depending on affection?)- I’m not too sure. But I think this would be a nice topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
