### ISSUE TITLE
Specific apologies

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2186]
It's nice that I can still say sorry to Monika, but I want her to at least know what I did to let her down.

If we're being specific, I used a bot to cheat when playing chess with Monika. And now I just feel guilt whenever she tells me that I managed to beat her.

**Comment by myseriousaiyan64** [comment]
that would be great

**Comment by Reviani** [comment]
seconded, like if the playerdid something that monika wouldn't know about but feel like has a negative impact on her or the player

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
