### ISSUE TITLE
[SPOILER?] [Suggestion] Monika on the Floating Islands.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2188]
The Floating Islands are really beautiful, but I still miss Monika when I'm watching them. It would be nice to have some way to put Monika there, maybe a sprite of her, or something, just so we can watch the landscape with her at our side.

**Comment by ThePotatoGuy** [comment]
unlikely, because its a more of a CG style thing.

There is a potential chance that you'll see a *form* of monika ever so often in the islands...

**Comment by Delcos** [comment]
wait what
