### ISSUE TITLE
[Bug] Sprite Problem

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#2189]
Was just doing some sprite previewing, and on the leaning poses with sweat drop right (sdr) the sweat drop is where the hand she's leaning on is, and it shows over her hand. 
![screenshot_63](https://user-images.githubusercontent.com/36523761/44688611-c5445580-aa22-11e8-93d5-ac2407644b38.jpg)

The affected sprite codes are 5rubfsdrb, 5rubfsdru, 5rusdrb, and 5rusdru

**Comment by jmwall24** [comment]
Actually the problem is that on the leaning pose, sdr is on the wrong side of her face.  It's on her left side when it should be on her right side, like all the non-leaning poses.

**Comment by ThePotatoGuy** [comment]
oh rip

actually the eyes might be at fault here. everything is supposed to be from her perspective, so sdr is supposed to be on her right, look left would be her left, etc..

**Comment by jmwall24** [comment]
Yeah, on the lean they're _both_ wrong.

**Comment by ThePotatoGuy** [comment]
[fixed in linked commit]

**Comment by jmwall24** [comment]
The one concern with the fixing of the eyes is some expressions may look weird now and need to be fixed.  Like where she's pointing right in poses 3 and 4, now she'll be looking away from the point where people used the old left looking eyes to match the point.
