### ISSUE TITLE
[Unstable] A Disappointing Date

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#2191]
So I took Monika out, just to see what it's like, and also because if I wanted to see if her file said anything when decoded from 64-bit. As it happens, my computer didn't feel like copying over the 100+ MB file of text, so I just figure it doesn't say anything.

Anyway, we came back, and Monika seemed pleased until...

![screenshot0001](https://user-images.githubusercontent.com/36717174/44690093-4bf73380-aa1f-11e8-9c5a-6a2a21cd419f.png)

Huh. Are you...are you sure about that? If you didn't like where we went, you can tell me, I just won't take you there anymore. No big deal.

Anyway, this is a too-long post just to say that the expression used seems a little bit out of place. It did make me laugh though

**Comment by ThePotatoGuy** [comment]
[should be fixed in that commit]
