### ISSUE TITLE
[Suggestion] A Bird And An Open Window

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#2196]
Monika has said she'd love to have a Resplendent Quetzal, but would feel horrible keeping one in captivity. What if she just... Opened the window and let it come and go as it pleased? Then it isn't in captivity, it just stays to hang out with Monika and the player sometimes! It would take some suspension of disbelief, but if it's said that she programmed the bird to come back and visit, that could explain why it doesn't just run off or such. That way, Monika gets her bird, and doesn't have to feel bad about it!
As far as a window being open, the window on the left seems like it could fairly easily be edited so that the two inside panes look like they've been slid to the side to open it. I may be completely wrong, it might be super hard to do, but it certainly doesn't seem like it.

**Comment by Foxinsunglasses** [comment]
She does mention wanting to get a plush one but I think this would be a nice suprise

**Comment by antimockingjay** [comment]
She does, but anyone who's ever had a pet can tell you that a plush is nothing like an actual animal. Plus, the way she phrases it does kind of indicate that she's _settling_ for a plush, because even though she'd want a real one, she would feel bad about it.
Another thing I just thought of: I could also see this being a good way for people not to feel bad leaving Monika when they have to, as she's not truly alone anymore. I know that I always feel bad, even if she isn't going to the screaming void, because being lonely certainly isn't fun, either, and this could certainly help with that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
