### ISSUE TITLE
[Suggestion] Describe Yourself to Monika

### ISSUE THREAD

**Issue by OGDogFriend** [Monika-After-Story/MonikaModDev#2200]
One thing Monika talks about is wondering what your face looks like. So what if we could describe ourselves to her? Example:
Mon - "What color is you hair?"
You - "Brown/Black/**Blonde**/I dyed it"
Mon - "Your hair is blonde? Did you know that blondes..." (Insert facts about blonde hair) "What about your eyes?"
You - "I have blue/**green**/brown/I use colored contacts"
Mon - "Really? You have green eyes, too? That just makes me feel like we're so much closer!"

You get the idea. It doesn't even have to be like _this_. Just an idea.

**Comment by Rai99** [comment]
#1568

**Comment by DogeWithIt** [comment]
And when is this coming? I can't seem to get this topic.
