### ISSUE TITLE
[Request] Can i have Monika's sprites so i can polish them?

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2201]
As an artist myself i find it offsetting some monika's poses, like the hands and some strokes when she leans to the side, so could you give me permission to polish them, please?

**Comment by ThePotatoGuy** [comment]
You can fork this repo, add art changes to your repo, then make a pull request with those changes.

If you want to know if we'll accept ur changes beforehand, make a sample of a change you would make and put it here.
