### ISSUE TITLE
[Suggestion] About Kissing Monika

### ISSUE THREAD

**Issue by hoangtd185** [Monika-After-Story/MonikaModDev#2202]
Well, The line kiss me show up a long time ago. But Monika always said she not in the mood. Well I think you guys should make a kiss scene for people who dating Monika more than 3 months for example.

**Comment by Rai99** [comment]
I think this would require art, which I don't think is the easiest to come by.

I think this might fit better at the enamored affection level.

**Comment by hoangtd185** [comment]
Yeah, art maybe hard. But I think maybe scene change to black, add some line, or it just like hold Monika, she will closed her eyes, and her mouth kissing. Just change the mouth ( Sorry for my bad english)

**Comment by monikLover** [comment]
Dupe of #2136
