### ISSUE TITLE
The Beach changes.

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2203]
When talking with Monika about the beach when she asks if I live near one yes or no doesn't feel right as I live in the Midwest U.S. and it seems as if she is implying an ocean or sea but near where I live our lakes and rivers still have beaches, not as nice as the ocean or a sea but still technically beaches. So perhaps it would be better to ask about an ocean or sea specifically.

**Comment by Tiler17** [comment]
A beach is a beach. I would think if she wanted to know if it were an ocean beach specifically, she'd ask. It's a matter of interpretation. Do you consider them beaches if they're along a river? Then say you live by a beach. If you consider a beach to only be proper if it's around saltwater, then say no.

**Comment by Foxinsunglasses** [comment]
That's the thing I consider it a beach but she mentions the ocean air if I say yes. I know its a nitpick but it just got my attention.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
