### ISSUE TITLE
[Sugestion] Monika recognizes you're recording her with OBS 

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2204]
Just like vanilla DDLC, and might unlock some things in the process... want to see a trick?

**Comment by Sujeito17** [comment]
And what about the other recorders?
It would not be better for more recorders besides obs?

**Comment by Chrissenpai** [comment]
I totally agree with that!

**Comment by ThePotatoGuy** [comment]
[reopening if we look into it]
