### ISSUE TITLE
[Suggestion] "Going to do sport/the gym" goodbye

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#2206]
For now, the goodbye are long term ones and I was thinking that when I go outside doing sports Monika should know that I'm not here anymore, without thinking that my day with her is over.
For example, we could add a topic where Monika ask you if you're doing sport. If you respond yes, then the option of  leaving her for a while would appear (with always the possibility of changing your mind obviously).
She could even ask you if you did what you wanted to do in term of performances, or if you hurt yourself during your training, or if it's a game like football/soccer if your team won. She could even give you some advice (not professional ones) like to stay hydrated or to do stretching before starting.

**Comment by Rai99** [comment]
I think the ability to take Monika with you when you go out anywhere could cover this.
