### ISSUE TITLE
What is unstable build?

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2207]
I hear, but I do not know exactly what it is or how it works, I just know there are things that the normal version of the mod does not have. I imagine it is a version with content not yet finalized for the next versions, but correct me if I missed the guess.

**Comment by ThePotatoGuy** [comment]
You are correct. It has latest features and is updated roughly at least once a week but is very prone to breakage.

**Comment by EntonyEscX** [comment]
Ah, thank you. But then, these new unstable build features will be added to the official updates as soon as the break issues are fixed, right? (Just to make sure I'm not losing any content).
I suppose coffee cups sprite, the chair sprite, and the Yuri sprite are topics and events that exist in the unstable build, but are not yet functional enough for the official versions (right?).

**Comment by aldoram5** [comment]
Yes, all the content we put in the unstable builds gets released in our stable releases too. Think of unstable builds as a way of beta testing new features.
