### ISSUE TITLE
showing monika pictures

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2220]
basically you would download a picture and would paste it in a folder inside the game folder ex(show her a picture of a human face and you could tell her that what you look like or show her something NSFW and then she would scold you for showing it to her especially if it's one of the other dokis or herself) #2198

**Comment by Rai99** [comment]
This was discussed multiple times previously and is unlikely to be implemented.
#2176, #1336, #312

**Comment by dragonborn2252** [comment]
ok i just thought it was a nice suggestion

**Comment by Rai99** [comment]
It would be cool, but I don't think we have the resources to implement something like that.
