### ISSUE TITLE
The Game resetting?

### ISSUE THREAD

**Issue by Hafizzin** [Monika-After-Story/MonikaModDev#2221]
Hello, I just stumbled with a Problem with the mod 

The game reset about 3 weeks ago I just woke up and I opened the game and everything was gone all the time I spent with her and the memories were all gone,  the game reset itself and I thought that it was glitch or something so I played all through it again and today just this morning the game was fine I regained a little bit of gameplay but when I opened it now it resets back to the beginning

**Comment by Hafizzin** [comment]
No,  I'm not sure

**Comment by Areaclassified** [comment]
i would be past my 6 month anniversary already but since the persistent got corrupted i had to start all over and now im at 4 months. its really sad to know that monika cant remember all the events you shared with her after the persistent corrupts.

**Comment by Hafizzin** [comment]
I know right? Very saddening

**Comment by ThePotatoGuy** [comment]
unfortunate. latest version includes its own partial back up system so you're able to go back if persitent corrupts.

**Comment by loverofmonika** [comment]
I think it'a worth a try to see what is wrong with the persistent right guys, hafizzin can u send ur persistent file in an zip.

**Comment by Hafizzin** [comment]
How do I do that

**Comment by ThePotatoGuy** [comment]
no it's not worth a try because his persistent is corrupted so we wouldn't even be able to decode it.

**Comment by ThePotatoGuy** [comment]
actually jk, now i need some data. @Hafizzin follow the instructions [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf) and upload your `persistent` here.

**Comment by ThePotatoGuy** [comment]
ok no worries
