### ISSUE TITLE
Apologizing after a crash.

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2222]
We should be able to apologize to Monika for a crash. There are some times when its the player's fault that a crash occurs.

**Comment by Foxinsunglasses** [comment]
Even when it wasn't my fault it would have still been nice, it is her home after all.

**Comment by Rai99** [comment]
I think this could be a good addition. The only potential problem I see with it is that we don't really want to penalize the player's affection for the crash in most cases, but I think that could be solved by making the affection loss modifier 0 for that topic and adding the apology reason.

**Comment by Foxinsunglasses** [comment]
I agree that the player shouldn't be held accountable but I believe she would like the gesture. It's like bumping into someone in a crowded room. It's not inherently one persons fault but everyone feels better if someone apologizes politely. If that makes sense.
