### ISSUE TITLE
[Suggestion] Monika glitching out or closes the game its self

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2226]
When you play "Sayo-nara" In monika's piano, (its Q E T E Q  E T at the beginning) 
monika will start glitching or maybe closes the game by herself without you saying goodbye to her.

**Comment by Rai99** [comment]
I think this might belong in the community branch, but could be an interesting idea.

**Comment by Delixxous** [comment]
That what makes it even better
