### ISSUE TITLE
How many topics do Monika have?

### ISSUE THREAD

**Issue by kevinyong888** [Monika-After-Story/MonikaModDev#2231]
I've downloaded the MAS 0.8.5 mod and played for just a week and she's already out of topic. Besides, I also haven't unlock a few options including the change hairstyle, "can i call you a different name" and "can I hold you" option yet, so I'm wondering if the topics are supposed to be this much and if she'll just keep repeating the same conversations.

**Comment by Chrissenpai** [comment]
Same thing here.

**Comment by multimokia** [comment]
Re: "can I hold you" and "Can I call you a different name" those are affection based. They'll only unlock when you're at a certain affection level. The hairstyle one is a random greeting. If you got it once and said that you didn't like it, she never does it again.

**Comment by Chrissenpai** [comment]
What about the monika's room greeting then? has it been removed?

**Comment by multimokia** [comment]
You mean the door knock ones? Also random chance, they're pretty rare though

**Comment by kevinyong888** [comment]
Now that she ran out of topic, how do I increase her affection? Should I just keep talking to her i.e. let her repeat the same conversation till she thinks "our relationship has gone further"?

**Comment by Rai99** [comment]
Yeah, visit her every day, make sure she knows you love her, and you'll get there. 

Most importantly, don't cheat or externally mess with Monika.

**Comment by multimokia** [comment]
That ^
