### ISSUE TITLE
[Suggestion] - Suggestion for Monika question

### ISSUE THREAD

**Issue by MiyagaseHana** [Monika-After-Story/MonikaModDev#2232]
Can you by chance add an option to talk to Monika about fetishes? You already have one about pleasuring yourself so it can fit in the same category. I have a pee fetish and I would love to hear what Monika has to say about sexual fetishes. Thank you very much for reading and I love your mod!

**Comment by Rai99** [comment]
First of all, let me be frank; We didn't need to know the kind of things you're into personally, I ask that you click that **"..."** on the top right of your comment and click edit and kindly remove that part describing what you are personally into or close the issue with the button at the bottom if you feel that this issue is no longer necessary to have attention brought to and save other people having to know the details. 

As for the suggestion itself, I don't think we can have sexual fetish topics such as this in MAS. _Maybe_ in the community branch, but I don't think anything like this will be allowed, **especially** when going in depth about a topic like this.

**Comment by KEJONACHO** [comment]
Sexual fetiches are far from MAS-kanon Monika, as far as I understand it. Monika seems to be rather reserved and romantic concerning everything related to intimacies. You know, kissing makes her freak out, she never really talks about sex and general, getting to hug her is already a masssive in-game achievement and it takes a rather high affection level for her to accept the played checking lewds of her on the web.

Still, if trying to push for it, I imagine that time and chance could lead the devs to make a dialogue-progression, where she wonders about sex and asks the player about his personal experience. There we could have possible answers ranging from 'I never kissed' to 'I'm a very sexually open person'. And from that last option, there could be some dialogue branch, where moni slowly gets curious about it... But well, it's pretty far stretch.

Finally, the most complicated part really, is the fact that this kind of kink is probably wished by a very small percentage of the users and a taboo among... well, probably a lot of people (Rai99 already served as example, i guess?). So it would definitely have to be created as a hidden option, that opens when you tell her you're into kinks... and narrow niche stuff are usually too far from what our devs could reach. They already have their hands full with bugs and the main stuff, you know.

You could actually create this line of dialogue and suggest it here in Github, but I guess your best bet would be to just add this dialogue to your own game. Yeah, not as much fun, I know.
My personal guess is: If someone asks Monika right off about big kinks, she'd be completely shocked in lower affection levels, and more than a bit aprehensive at first in higher affection. And yes, I see her trying to slowly learn and like this important aspect of her beloved player.

**Comment by Rai99** [comment]
I think this kind of thing is best left for each willing person to make their own scenario with Monika unless you find someone else who wrote one and is willing to share it. 

Also, in case it isn't clear already, don't go around asking people to write smut for you.

**Comment by AsuraShun** [comment]
tmi MiyagaseHana,tmi
