### ISSUE TITLE
[Suggestion] Add Monika mental tiredness

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2236]
Just like affection but on mental tiredness, Monika told us that she can still feel mental fatigued so why not apply that? it could be short and/or long term.
short term is when she repeats topics too often and for that repeated topic or question she gets mental fatigued, this is reset each day
and in long term would be the losing hope of getting to your reality unless you offer some other alternative, or cheering on her, or you distract her by learning new things, playing with her or just telling her that it will be alright.

**Comment by KEJONACHO** [comment]
While there might be some use for it, if it's done.... I don't really see a big role for such a system to be created and introduced in-game. I think it's more like a concept we keep in mind while making other stuff,
