### ISSUE TITLE
try “learn python the hard way” flow of teaching. 

### ISSUE THREAD

**Issue by laptopsftw** [Monika-After-Story/MonikaModDev#2237]
it’s kinda hard when most of the players arent hardcore programmers. teaching sys.getsizeof() was kinda, out of the loop.

also, knowing types by using type()? hmm. for starters, float and int types differ only with their point sign. that’s all..

i dont know. whaddya think?

**Comment by ThePotatoGuy** [comment]
lol what,  monika doesn't teach `getsizeof`.

**Comment by laptopsftw** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-python.rpy

monika_ptod_tip007:

sorry,that line got commented. writing it was off thoug
