### ISSUE TITLE
Suggestion on updates

### ISSUE THREAD

**Issue by Irres** [Monika-After-Story/MonikaModDev#2239]
Perhaps Monika should know whenever there is a new version available on MAS. and comment before/After the update.
Like "Oh, there's a new version available, do update USER",
Or even implies that she has new thing to talk about
 "Don't forget to update... before we can discuss more..."

After the update
I thought about new thing to talk about/ to do while you were updating.

Sorry for my bad English.

**Comment by ThePotatoGuy** [comment]
I guess we could move the update now button to a farewell, that would be an interesting way to do it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
