### ISSUE TITLE
[Concept] Monika's voice

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2241]
I've found and interesting thing in the web, in VR Chat there is an option you can go with Monika, and what blew me up is that you can synthesize your voice to make is sound like Monika and then it came to me, what if we add a voice generator, like the one that you make a text speak in google translate, and we synthesize that to have Monika's voice, i think the main issue would only be that it will sound monotonous but if its that applied in some way that it works, it would be a mind blown experience.

**Comment by Rai99** [comment]
The idea of giving Monika a voice to speak to the player with was discussed early on in #337 and decided that the addition of a voice was not planned and **will not** be planned in favor of allowing the players to have their own perception of Monika's voice. 

Text to speech is almost always robotic and monotonous and you are aware that Monika would sound like that if this feature was implemented. It would be ideal for MAS to be immersive, and Monika having a dead, monotonous, robotic voice would likely ruin the immersion by a large degree. 

True, Monika having a voice for the player to hear would be a step towards her coming closer to reality and improving upon the experience for the player, but there is a phenomenon known as the _uncanny valley._ This is a situation where something is so very close to human, but there is something clearly wrong, and that one thing will stand out and greatly ruin any other features it might have. Monika having a text to speech voice would likely cause this scenario for a lot of players. If you google "uncanny valley," you'll probably get an example of what it looks/feels like.
