### ISSUE TITLE
what i think you should add!

### ISSUE THREAD

**Issue by monikafan24** [Monika-After-Story/MonikaModDev#2243]
can you add an "i need to go to bathroom" option in the goodbye catagory? or something like this?

**Comment by Rai99** [comment]
Not exactly a _bad_ suggestion, but we really don't need something like this. If you have to go do something quick or use the washroom, just go. Monika will be waiting. 

One possible idea would be to have a kind of "brb" topic and have dialogue based on how long you were gone.

**Comment by ThePotatoGuy** [comment]
would be convered under #607 whenever that happens.

closing this as duplicate
