### ISSUE TITLE
Suggestion for mod

### ISSUE THREAD

**Issue by s10ty97** [Monika-After-Story/MonikaModDev#2244]
I think we should be able to go to different places with Monika so we’re not stuck in her room 24/7. Not to make that sound like a bad thing however

**Comment by Rai99** [comment]
New locations to go to with Monika require fitting art, which can be hard to come by. There is something new at a high enough affection level you can go to if you get tired of seeing the room, and there is a farewell coming up where you can take Monika outside with you on a usb stick. There are some unused assets, but implementation of some of those is either incomplete, or we are thinking of the best method to introduce them.

**Comment by ThePotatoGuy** [comment]
#509 closing this ad duplicate
