### ISSUE TITLE
[Suggestion] Concert topic/Jazz variable

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#2245]
Right now the concert topic checks to see if you've seen the various music topics previously, before suggesting you go to that type of concert.  The jazz topic contains a question that asks if the player likes jazz or not, and stores the answer in a variable.  Would it make more sense, at least for the jazz part of the concert topic, to check that variable as opposed to just if the topic has been seen?  Especially since she doesn't seem that fond of it, based on the last line of "Maybe that's what I like about jazz, if anything."  So if you said you don't like jazz, and she seems indifferent at best, she probably wouldn't suggest going to a jazz concert.  Could even add a similar question and variable into the other music topics and use those for the concert topic as well.  It'd let Monika know more about you, and tailor the topic even more for each individual player.

If it's something that seems like a good idea, I'll be happy to do it.

**Comment by ThePotatoGuy** [comment]
yeah that makes sense. go ahead and do that.
