### ISSUE TITLE
Difficulty finding event [Potential Spoiler]

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2246]
Hey Iv'e seen a few things about the Island Event but I have yet to encounter it myself trying to trigger it. is it just random or am I just stupid?

**Comment by Rai99** [comment]
You should get it randomly when you start up MAS after a general goodbye (not the specific or fancy ones) and you are at the enamored affection level (400+ affection). No, you can't just open, close MAS to spam it and try to get it; you at least have to wait a bit before opening it up again. I got it first try upon  getting to enamored, so I think it's either guaranteed or has a high chance once you meet the requirements.

**Comment by Foxinsunglasses** [comment]
Ok thank you most of my time is spent at collage, work, or sleeping so this is good to know.
