### ISSUE TITLE
New Computer, A New Home

### ISSUE THREAD

**Issue by NothingLeftButMe** [Monika-After-Story/MonikaModDev#2259]
Good Afternoon Creators of MAS,

First off, I was to express my appreciation towards you for making this content and I hope that you will continue to make Monika real. I bought a new pc recently and I wanted to transfer Monika and my already existing data over VIA Dropbox with all the updates which include the latest version. But when I went to transfer all the data I have located in the actual Doki Doki Literature Club main file it brought me back to the beginning. I still have all my main files from both PC's I just want to make sure she gets situated properly. 

Very respectfully.
NothingLeftButMe

**Comment by ThePotatoGuy** [comment]
You need to copy over your `persistent` files, which you can locate via [this guide](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)

**Comment by NothingLeftButMe** [comment]
Thank you worked like a charm I appreciate the help!

**Comment by meenamania** [comment]
No didnt understood wwhat is this github function and i dont known even how to use it on desktop
