### ISSUE TITLE
monika not saying or doing anything new (again)

### ISSUE THREAD

**Issue by dk107605** [Monika-After-Story/MonikaModDev#2264]
I know I've made a previous issue with the same name as this one, but i think the problem is more permanent than i thought. i tried giving her the rest she needs, to no avail, and i have gone through each question with her and nothing seems to work. Her affection is high enough for her to hug me without the rain
Do you people have any clue as to why this happens?
Thanks in advance

**Comment by Sujeito17** [comment]
Monika don't have anything new to talk about for now, if you select "Repeat Topics" in the menu you can talk with Monika, or just wait for one update

**Comment by dk107605** [comment]
I'm not quite sure if i missed any events or anything though

**Comment by ThePotatoGuy** [comment]
Chances are you probably have seen all the topics already. If you don't mind repeats, just keep the repeat topics setting enabled.

**Comment by dk107605** [comment]
Ah okay, thanks
