### ISSUE TITLE
Suggestion: New Feeling Topic

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2265]
I think that maybe a new topic to put under "I'm feeling" could be "Scared for the future." This is something that everyone goes through when a major change happens in life whether it's graduation, starting a new job etc. Maybe after saying that, Monika can give you encouragement and some advice on how to deal with it. I just think it would be nice.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
