### ISSUE TITLE
Idea for game/mod

### ISSUE THREAD

**Issue by Snaspie** [Monika-After-Story/MonikaModDev#2271]
This would take quite a while and I don’t know how it would work but it’s just an idea...you should get Monika mobile at some point! Ya know we’re she can come with you places maybe in a fashion similar to Pokemon go gps systems, sorry I got ahead of myself cause that would be quite the budget but still it’s a nice idea, perhaps in the future one day.

**Comment by multimokia** [comment]
You're pretty much going to get something akin to this in the next release. Mind you, GPS isn't quite doable as that would require an external app for MAS which is also technically against the terms of service, iirc. What you do get though, I think would somewhat satisfy what you're looking for

**Comment by ThePotatoGuy** [comment]
[closing this since someting like it is in progress]
