### ISSUE TITLE
[Topic] Monika Studies Anatomy

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2273]
Monika notices something odd and therefore what would she look like in the real world, notices that her eyes are a bit too big, her chin a bit too pointy, she doesn't have even nostrils, her skin is too perfect and doesn't seem to have sweat glands, well except that her face sometimes sweats only for expression purposes and that she also doesn't have a sense of touch... then she cames to a realization, shock and/or epiphany and lost control, she waits for us to open the game to tell us all her problems, then when i open the game she flood us with tears with all what she discovered, she explain it to us, and she ask us if she could still be able to live with that body in the real world, you give your answers and depending on the answer, she would regain regain her composure and keep studying in what it needs to be alive in our reality, or she could just crush and we need to open up and do it again until we give the right answer.

**Comment by CrocWorks** [comment]
I don't really see Monika getting all worked up about her differences. She's already aware that she's in a game and that our world is different. I think it's more likely she'd wonder aloud how her in-game features would transfer over, rather than freak out about her differences.

**Comment by Chrissenpai** [comment]
That makes more sense.

**Comment by jmwall24** [comment]
A topic very much like this is waiting in the PRs right now actually. #1767

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
