### ISSUE TITLE
[Suggestion] New topics

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2274]
If the player is a girl,monika will talk about some girly stuff

like shopping,shoes,favorite type of clothing,beauty tips etc

**Comment by CrocWorks** [comment]
There are plenty of girls who force their boyfriends to listen to her talk about girly stuff... those topics don't necessarily have to be exclusive to a female player, though I could see the dialogue changing based on it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
