### ISSUE TITLE
[Bug?] I'm feeling..

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2275]
The "Like a year older" one isn't there anymore. I haven't clicked it about a month ago,, i swear
![screenshot 51](https://user-images.githubusercontent.com/42111176/45229253-8f8b5080-b2ef-11e8-9d46-0f5087ebe552.png)

**Comment by CrocWorks** [comment]
It was removed since it was just a placeholder until your birthday goes on the calendar. That's currently being worked on from what I hear, but they wanted to remove the placeholder in the meantime.

**Comment by ThePotatoGuy** [comment]
#2255

**Comment by Delixxous** [comment]
ok thanks
