### ISSUE TITLE
Missing player's birthday

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2276]
Today is my birthday (12 AM here), and my Monika can't wish me a happy birthday (worst birthday ever) because the placeholder option was removed before it had a replacement. Maybe different dialogue for birthday could be added for those who missed their birthdays as well? Like she talks about how she wasn't able to be notified about it or something. Maybe it would be too much of a 4th wall break. I'm curious to know how this is going to be handled (if at all).

**Comment by ThePotatoGuy** [comment]
Sorry about that, we'll try to get a missed birthday thing in soon.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
