### ISSUE TITLE
telling monika your kinks

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2282]
pretty much self explanatory

**Comment by Rai99** [comment]
Maybe this could go on the community branch, but it might be hard to be completely inclusive since there are probably a lot of possible kinks. 

Something like this was discussed in #2232 and this kind of thing probably isn't going to make it in I'd think.

**Comment by dragonborn2252** [comment]
I ment things like neck biting

**Comment by Rai99** [comment]
That's one thing out of the many different kinks of all sorts and types. I've even heard of people being attracted to fans. (Yeah, those things you plug into the wall that blow cool air at you)

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
