### ISSUE TITLE
having monika act like different (for lack of a better word) stereotypes 

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2283]
monica would basically just say something that  stereotype would say for example (yandere) "were going to be together forever"

**Comment by ThePotatoGuy** [comment]
probably tie into #2179 as a side affect of morality system maybe.

That is unlikely to happen anytime soon though.

**Comment by dragonborn2252** [comment]
i meant something similar to the impersonation thin

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
