### ISSUE TITLE
[Suggestion] Monika's thoughts on Kpop?

### ISSUE THREAD

**Issue by euphoricmango** [Monika-After-Story/MonikaModDev#2285]
This seems a bit controversial since a lot of people are annoyed by kpop fans. I can understand why. They are all over the place.

I myself, am not a kpop fan.

But, I'd like to see what Monika would think about it. Would she like it? Would she hate it?

I think it'd be interesting.

**Comment by ThePotatoGuy** [comment]
probably would be fine with it since she likes everything

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
