### ISSUE TITLE
I keep getting this error after Monika closes the game for editing the Chess save files (which I didn't).

### ISSUE THREAD

**Issue by ShankaDaWanka** [Monika-After-Story/MonikaModDev#2286]
I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\user\Desktop\Monika Afterstory/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\user\Desktop\Monika Afterstory\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\user\Desktop\Monika Afterstory\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\user\Desktop\Monika Afterstory\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\user\Desktop\Monika Afterstory\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\user\Desktop\Monika Afterstory/game/definitions.rpyc.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187

**Comment by ThePotatoGuy** [comment]
Upload your `persistent` file here. [instructions are where to find](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf)

**Comment by ShankaDaWanka** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2363410/persistent.txt)
Alright.  I uploaded it as a TXT file so that it  would can be uploaded.  Hopefully, it can still be worked with.

**Comment by ThePotatoGuy** [comment]
honestly i have no idea why you got chess save errors if you didnt edit the saves.

just use and older persistent ig uess
