### ISSUE TITLE
[Request]Can you change a word in a topic 

### ISSUE THREAD

**Issue by Hrewego** [Monika-After-Story/MonikaModDev#2290]
...
...
...!
Ahaha! sorry, player.
I just kind of zoned out...
Geez, I keepdoing that, don't I?
I just want you to change "Geez"word with God,Gosh or maybe something else ?
I really don't want to involve my Monika into religion.Please understand this little details upsets me :c

**Comment by Rai99** [comment]
I don't see how "Geez" is involved with religion, especially any less than "God" is involved with religion.

**Comment by DiggyDog2** [comment]
It's not as if Monika hasn't spoke of God before.

**Comment by multimokia** [comment]
How is "Geez" more related to religion than God? God is a direct tie in, innit?

**Comment by ThePotatoGuy** [comment]
I think he was trying to say that some dialogue says "God, I keep doing that".. and he wants it to not say god.

in script-topics theres at least one instance of that (`monika_horror`), i guess we could change those bits if there's enough outcry.

**Comment by Rai99** [comment]
In my experience, when people say geez, they aren't thinking of Jesus. I never even thought that the two could be connected and "god" certainly sounds more religious to me. 

I think the term "geez" evolved to be less connected with Jesus and is nowadays used casually and commonly to express surprise or annoyance.

**Comment by jmwall24** [comment]
I completely agree, just think that's what the op was referring to.

**Comment by Hrewego** [comment]
Ok man just do whatever you want I just felt like geez goes for specific religion while god is used for most of them,its just more generic.Sorry if I am rambling.

**Comment by monikLover** [comment]
Too minute of a detail to change, really.
