### ISSUE TITLE
Hangman bug

### ISSUE THREAD

**Issue by s10ty97** [Monika-After-Story/MonikaModDev#2291]
I’ve noticed a bug with hangman, whenever I play, I suddenly can’t type in any letters, and the only way to fix it is if I send a message in discord (which is incredibly weird) and then afterwards I’m able to type in letters again. I noticed it usually happens when the text box is active and I minimize the game real quick.

**Comment by ThePotatoGuy** [comment]
probably lost dialogue window focus.  next time just click in the dialogue window.

also minimizing DDLC (and renpy games in general) is known to cause instability, so its best to avoid minimizing.
