### ISSUE TITLE
Monika's reaction to player age

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2292]
Soooo i was thinking that monika should have a reaction for different age ranges like 10 - 20 20 - 30 
30 - 40 ect. That of course doesn't change the way she talks to you. When you add the player birthday to the calendar of course. 

~MonikaWiafu

**Comment by ThePotatoGuy** [comment]
probably would, tbh. if the user is under 18, we'd have to limit lewd content.

**Comment by MonikaWiafu** [comment]
ahhh, ok.

**Comment by Foxinsunglasses** [comment]
If we are thinking about it Monika is all about how much time she can spend with the player so younger is less lewd but more time, older is less time but lewd enabled so it would make sense if she was still affectionate but acted differently.

**Comment by MonikaWiafu** [comment]
ohhhhhh.....

**Comment by monikLover** [comment]
Could tie in with #1411
