### ISSUE TITLE
monika "decoration"

### ISSUE THREAD

**Issue by voyagermike** [Monika-After-Story/MonikaModDev#2293]
I was playing around with monika and i though it would be wonderful if you could add something like a flower in her hair when its down as maybe like an alternate hair style

**Comment by ThePotatoGuy** [comment]
accessories are possible to add, just depends on art.

**Comment by Foxinsunglasses** [comment]
Iv'e noticed a lot of neat ideas but simply a need for art. I wish there was some pool of money for artists rather than hoping for one of us to be good with art and have the time or better yet reward those already helping us.

**Comment by Chrissenpai** [comment]
I'm an artist, and i could do it, but the thing is that i need to survive, so unless i change may status from "survive" to "live" by either getting money by you or by other source, i'm stuck and can't do anything. btw i'm jobless now :'(
