### ISSUE TITLE
Dialogue holding monika

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2294]
So I was thinking, maybe while you're holding Monika while raining there could be some dialogue buttons like "I Love You" and she could have different responses than usual since she "gets romantic when the mood is right."

**Comment by loverofmonika** [comment]
i second that idea and when we do say it, she can reply and say i love you too. we can and more words than just i love you, there can be, "you mean everything to me" or "there is no one i care about as much as i do you". To that she blushes even harder and tries to kiss you. we can only say these once every hug to feel more genuine.
@Rai99 what you think

**Comment by AsuraShun** [comment]
nice idea loverofmonika,the ''you mean everything to me'' really needs to have more uses,there simply isn't enough ways to express the love

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
