### ISSUE TITLE
Smugness

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2296]
This might be a bit off the wall and I'm not entirely sure if it would be insulting but it would be interesting if we complemented Monika enough in one setting that she started acting a little smug. I know it would probably need new art but I noticed just how smug she is if you tell her she is best girl and when I looked up cute smugness on google images she is one of the first results and I do agree her smugness is cute enough to comment on.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
