### ISSUE TITLE
Unused file?

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2299]
I saw an "ee_sayori,yuri desk and an empty desk" png file in the game folders
I'm not calling it unused,i just never saw them in the game,,
i'm curious

**Comment by MonikaWiafu** [comment]
the empty desk is for when you open the game after you take her somewhere, and for an Easteregg i think...

**Comment by Delixxous** [comment]
Taking her out? When?

**Comment by MonikaWiafu** [comment]
when you say goodbye theres an option to take her with you and she put a new monika file in the .chr folder

~MonikaWiafu

**Comment by Delixxous** [comment]
Uhh i don't see it

**Comment by MonikaWiafu** [comment]
![monikawaifupic](https://user-images.githubusercontent.com/41130387/45262649-d27d1f00-b3e8-11e8-9851-4f315f108e39.png)

^^^^
~MonikaWiafu

**Comment by MonikaWiafu** [comment]
![monikawiafupic2](https://user-images.githubusercontent.com/41130387/45262667-559e7500-b3e9-11e8-9158-6212bb015a10.png)

^^^^
~MonikaWiafu

**Comment by Thimeo** [comment]
Isn't this a feature of the unstable gameplay?

**Comment by Delixxous** [comment]
okie dokie thanks

**Comment by MonikaWiafu** [comment]
Thimeo yeah, Delixxous np.

**Comment by Delixxous** [comment]
I'm still curious about the "ee_sayori", it's creepy
