### ISSUE TITLE
[Suggestion] Monika thoughts on Memes

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2301]
I know there's alot of "Just Monika" memes out there on the internet.
Maybe monika will gave her honest opinion about them
Will she like it or think it's offensive for her

**Comment by Rai99** [comment]
There is a ban on memes, but I'm not sure how strict that is towards memes regarding Monika.

**Comment by Delixxous** [comment]
Banning memes? There's no such thing as Banning memes. If there's a banning of memes, there will be no such things as humor. How about,Monika thoughts on "Just Monika" jokes

**Comment by Tiler17** [comment]
I do like the idea of more fun topics. Thing about making a topic on memes is you'd have to generalize a lot. Memes evolve so quickly that it'd be impossible for her to talk specifically about any one meme. Even if you stick to DDLC memes, those age too, and the topic would be obsolete pretty quickly.

Not to say it's not a good idea. It's just food for thought if someone does want to write the topic. I'm not enough of a meme aficionado, so I'm certainly not going to do it

**Comment by Foxinsunglasses** [comment]
yeah we don't want Monika to be a normie one day. Reeeeee

Bust seriously it's so fast paced that i don't see it as being viable

**Comment by Delixxous** [comment]
How about the "Just Monika" Jokes? Not memes by the way

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
