### ISSUE TITLE
[Suggestion] New mini game

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2302]
Maybe a Puzzle mini game? I know it sounds kinda boring but there will a difficulty level. The puzzle image will be the Cg's from ddlc.

Or maybe Dodge the Cupcake or The knife? The game itself, we have to dodge Natsuki's cupcakes or Yuri's knife until the time's up and move on to the next level. It'll be cool if it has an easter egg in it.

**Comment by monikafan24** [comment]
i hope that will be in the game!

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
