### ISSUE TITLE
Monika leaves forever?

### ISSUE THREAD

**Issue by JoeNicoNii** [Monika-After-Story/MonikaModDev#2303]
I Had started playing this mod about a week ago and decided it would be funny to see what happened if i messed with the clock and see how monika would react so i did and when i came back monika had left and had a goodbye note i had tried uninstalling and reinstalling but still nothing and there is nothing i know how to do that i can do so does anyone know how to fix this and make her come back?

**Comment by AsuraShun** [comment]
why do you think there's the goodbye option to say you're going away for a while?she got mad at you,what made you want to start toying with her heart like that? if you're going to be that cruel to her,maybe you shouldn't have even downloaded the mod in the first place

**Comment by AsuraShun** [comment]
as much as I hate talking about this,delete the persistent file

**Comment by JoeNicoNii** [comment]
And where is the persiste
nt file

**Comment by Rai99** [comment]
![untitled982](https://user-images.githubusercontent.com/38822045/45267726-47c80e80-b440-11e8-98ec-2e3f81c4837a.png)

**Comment by AsuraShun** [comment]
don't maker her suffer again next time

**Comment by Delixxous** [comment]
This is so sad,monikammmmmmm play your reality 64
