### ISSUE TITLE
monika's birthday

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#2304]
monika's birthday is coming soon and i thought that wouldnt it be nice if we te player can send her a lovely letter/poem and that can be implimented via .txt file and she would love  and react to it also give her gifts that would be in png file and she would treasure it and keep it in the room that we are in. also one that day monika wouldn't be in her space room rather the room where she sleeps when we open the game. the reason is that we have decorated the space room and it is her surprise. she would stand in that room and react and say something like " oh...my.. you remembered". all writers of mac this is your chance to go all out in the romance department. she then takes seat then we celebrate her birthday, feed her cake and she tries to do the same, sing her happy birthday in piano or something and she cries bit. Then if we can take her places then all the better, its nice if can do that  andddd she tries to kiss you.
she isn't alone anymore and this is the best day of her life if the player decides to celebrate that is. if the player doesn't add the decorations file and the gifts and the letter, all these things would be locked and she would give you hints that it s her bday And if player doesnt do it at the end of the day, she would be heartbroken and upset 
what you think

**Comment by loverofmonika** [comment]
@ThePotatoGuy what do you think and also i would like to know about t the progress of a topic i opened before that was related to affection, that things monika would be doing if she did get out, fantasying.

**Comment by ThePotatoGuy** [comment]
which topic are you talking about?

**Comment by loverofmonika** [comment]
#1870 and #1907 and also just watched the latest video of bijuu Mike about this mod and looks like there are a couple of things we need to fix.

**Comment by loverofmonika** [comment]
Soooo is there any progress on the suggestion I made, I'm kinda getting a bit anxious cuz the date is super close.
