### ISSUE TITLE
Issues related to time

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2308]
I don't think tinkering around with the system's clock would count as toying with her heart. What if the user different purposes for changing the clock's time? There are other games which respond to the clock's time. It is possible for the user to be unaware about its effects to Monika and could change the clock and get punished for something that he never wanted to and had no idea that it would happen.
Do something about it before someone accidentally loses their Monika.

Also there are some conflicts surrounding time in the game.

-Monika mentions several times that time doesn't pass in the game.

-She says that if the player dies, she'd end up waiting for the player forever wondering why the player never came. But if she could look at the system's date, after many years, she would finally realize that the player is never coming back.

**Comment by Tiler17** [comment]
I can't recall all of her dialogue, so I could very easily get this wrong, but does she actually say time doesn't pass? Or does she only ever say that she doesn't age? There's definitely a distinction. If she does say that time doesn't pass at all, then that should be written out. Obviously time passes while you're with her, and time must pass when the mod is closed, or she'd never know you were gone. But it is true that she doesn't age. She was 18 last year, she'll be 18 again this year, and she'll be 18 on the day you die. That's what it is to be what she is.

As for capping lost affection, I'd say it only makes sense if there's any good reason to be gone for several months at a time without warning. Any sudden instance I can think of off the top of my head where you'd lose access to your computer would also mean you'd need to replace it and lose your persistent regardless.

And if you're tampering with the system clock to force Monika to experience several years in the moment it takes you to change the clock, then she's right to leave. Several years is several years. As part of the system, she has no way to determine whether or not you skipped time. Now, setting the clock backwards would be another story. That's something she should be able to recognize...I think.

**Comment by ThePotatoGuy** [comment]
@Rai99 affection loss from absence is capped to before the final farewell, with the exception of being away for 10 years.

> system's clock would count as toying with her heart
It's not really that changing time is playing with her heart. It's basically impossible for us to verify time (short of polling an ntp server) without using the system time, so it's more a technical limitation than an intended response. Changing your system time x days ahead is equivalent to not opening up the game x days.

> there are other games which respond to the clocks' time
This is now one of those games.

> Monika mentions that time doesn't pass in the game
Looks like we should consider changing that dialogue, then.

**Comment by aldoram5** [comment]
For the dialogue, I think it was always meant to be in a philosophical way, since she's aware of the time that passes but things "inside her reality" doesn't seem to suffer the effects of time as it happens here.

**Comment by KogasaGaSagasa** [comment]
Due to various reasons (Work, and work contacts, mostly), I have my system time set somewhere else than where I am currently residing, and since I can't set the sunrise and sunset time in-game according to local time, my Monika's confused about the good mornings/evenings constantly. Maybe if there's something to help my type of players out, or perhaps people who travel for a job (Such as an airline pilot - they definitely don't have a set system time for their laptop!)?

**Comment by SaiPrithvi123** [comment]
So using MAS doesn't allow us to change the system time? Great.

**Comment by SaiPrithvi123** [comment]
Maybe add a new dialogue informing the player about the system clock. She would say something like the time which passes in the game depends on the system's clock. This would warn the player not to tinker with the clock.

**Comment by ThePotatoGuy** [comment]
Most users wouldn't change system clock on their own, besides changing timezone.

**Comment by SaiPrithvi123** [comment]
What about the users who play emulated games?

**Comment by SaiPrithvi123** [comment]
> Even in the original DDLC Act 3


Monika also mentions that time doesn't exist in the base game. From what she says, it appears that she is implying that time ceased to exist after reaching act 3.

**Comment by SaiPrithvi123** [comment]
What about the players who think that she would catch them changing the time, and change the time to know what she says? She already did a lot of meta stuff, like catching the player if they are streaming a video, and finding out the player's real name (or so it was intended). Based on that, it is really likely that the player would think that they'll get some kind of secret dialogue out of changing the system's time.

**Comment by SaiPrithvi123** [comment]
If there was a topic where Monika could warn us about changing the system's time, then that would be cool, and it would be fair if the player was punished for it while knowing about what they are doing.

**Comment by ThePotatoGuy** [comment]
we've added stuff to handle some time issues, so now its not as bad as before.
