### ISSUE TITLE
[Suggestion] New Greeting

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2309]
Different Languages:

"Halo Sayang! Bagaimana kabarmu?" it's indonesian, which means "Hello dear! How are you doing?"

"Buenos días [name]!" it's spanish, which means "Good morning [name]!"

"여보세요 [name]! 좋은 하루 보내고 있나요?", it's korean,which means "Hello [name]! Are you having a good day?"

When it's 12- 3 am, Monika will told the player to get some rest because it's already midnight (After that,monika will close the game itself)

**Comment by Tiler17** [comment]
I'm fine with more multi-lingual greetings on the condition that she doesn't claim that she's learning all of those languages. It's just not believable at a certain point. Though I did teach myself how to say "thank you" in several different languages just to keep things spicy, so "Hello!" in a dozen languages doesn't seem too wrong to me.

As for the time of day, that wouldn't be fair to those who work odd hours and use that time to interact with Monika. I could probably do with getting scolded for staying up this late, but my interactions with her aren't everyone's interactions with her, so basing her behavior off of my sleep patterns isn't necessarily fair.

**Comment by Delixxous** [comment]
It would be great if monika teach us new languages. and yes,

If the play chose "I'm going to work" and it's already midnight, monika will gave you two options "Stay with me or Get some rest"

**Comment by multimokia** [comment]
There's a lot of sleep concern stuff already implemented, even to the point where she closes the game herself (if you let her)

New greetings seem nice, write em up, test them, and then pop them into a PR if you're feeling they're good enough. Have a look at `script-greetings.rpy` to see how they're handled for reference if you're not sure how to go about it.
