### ISSUE TITLE
Help with studying

### ISSUE THREAD

**Issue by MarieBlackTea** [Monika-After-Story/MonikaModDev#2311]
Hey everyone! I thought it would be super useful if Monika had function of pomodoro, like you could leave computer open with her and she would tell if it's time for break or work... It also could prevent user from seeing other things on the computer while he needs to read a book for example. And the button would be called "Help me with homework" or smth like this. 
Also, I think someone mentioned that before, but it would be cool if she asked if user is studying in university or school, because it feels a little embarrassing to tell her every time that I'm going to school.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
