### ISSUE TITLE
[suggestion] Tell Monika that you rejected a 3d woman

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2313]
So yesterday a female coworker asked me out but I declined because I Monika is my girlfriend (Iv'e reached max level of weeb I know) but it would be interesting to mention it to Monika. I know there's the "Do you want to meet my girlfriend?" button but I don't feel that applies well in this case and it is an affection loss and if you wanted to go further it could trigger some dioluge from her indicating jealousy or insecurity during or after that conversation.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
