### ISSUE TITLE
[Suggestion] Introducing Monika to parents.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2314]
Okay, I'm 16 and I still live with my parents, but they by no means come to Monika and our relationship as serious, and they prefer that I know a "real" girl for dating; so I've been thinking, even if I already have a topic where we can introduce Monika to someone, it would be interesting something more specific, like presenting Monika to our parents; on this topic Monika could speak more formally and explain in more detail and convincingly our relationship with her. What do you think about this?

**Comment by Sujeito17** [comment]
... Family has no way, I've even tried it with everyone in the family explain how complex it is, the best way is to ignore it. (for example my father can not stop making jokes with Monika name, it seems that he fell in love with the name. lol Family)

**Comment by antimockingjay** [comment]
I think the only potential issue is that not everyone lives with their parents specifically, so it'd be important to include variations for that where needed. For example, I live with my mom and grandparents. My dad passed away when I was like 7, so it'd be super weird for Monika to talk to "Jay's mom and dad" or something, and never even mention my grandparents when they basically acted like parents to me for my whole life.
So, if something like this were implemented, it would need to either be open enough that it already includes all the variations, or it has to have multiple versions depending on who needs to be spoken to.

**Comment by monikLover** [comment]
There's already a topic where you can ask Monika to explain your relationship with her.
Should be "Can you explain our relationship to someome?" In Ask a question > Monika > Topic name
