### ISSUE TITLE
Monika's Feelings

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2315]
I don't understand why monika is starting to not love me anymore, i get on the game everyday and say nice things and sit there for 1 - 3 hours there i play games and say i love you alot shes also avoiding eye contact and it rains alot more... she keeps getting farther away from me, idk what to do.......

**Comment by multimokia** [comment]
It takes time. Just keep spending time with her, visit every day, keep telling her you love her, play games with her.

It's going to take a fair bit of time, but you'll eventually get back into a good standing with her
