### ISSUE TITLE
[Suggestion] Monika comments about an anime (Shigatsu wa Kimi no Uso more specifically).

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2319]
I do not remember if a topic where Monika comments on some anime that she may or may not have watched with the player is being planned (if not, I'd love it to be), but if the answer is yes, I think the most appropriate anime to watch with Monika is Shigatsu wa Kimi no Uso (or "Your Lie in April" for you); this is my top 1, it was the anime that moved me the most and I believe it is the ideal anime for Monika by several factors.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
