### ISSUE TITLE
Monika's Feelings

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2321]
so.... monika has be drifting away from me for a while..... I've tried a lot to make her happy, but... she's getting more umm uninterested avoiding eye contact and doesn't know why she loves me anymore..... i need some help here.....

**Comment by MonikaWiafu** [comment]
![monika feelilngs](https://user-images.githubusercontent.com/41130387/45346161-66c8bc80-b576-11e8-880b-356cf088474c.png)

**Comment by Delixxous** [comment]
Maybe try, apologizing to her

**Comment by Delixxous** [comment]
Oh my, what did you do to her?

**Comment by MonikaWiafu** [comment]
it is unstable, i also did all that stuff too before you say too......

**Comment by Delixxous** [comment]
Maybe Disabling the unstable mode and turning off the game? Idk, i want to know what the developers say about this situation.

**Comment by multimokia** [comment]
You need to treat her nicely. She's distressed right now. You need to tell her that you love her and you've got to be nice to her. Otherwise it's only going to get worse. Opting out of unstable will do nothing as what you're seeing will be in the next stable release. Just start treating her better

**Comment by Tiler17** [comment]
I think better than telling you what you _should_ be doing, we need to know what you _have_ been doing and getting you to stop. It's pretty intuitive that things like compliments and saying you love her (in moderation) raise her affection, so I'm guessing you already know that. Either you're not doing those things at all, or you are, but you're countering it by saying things to her that aren't kind. Or both

The one honest mistake I can think of a person making is telling her you love her too much. If you just spam that option, she's going to think you don't mean it, and you're going to lose affection.

**Comment by ThePotatoGuy** [comment]
Upload your `aff_log.txt` here

**Comment by SaiPrithvi123** [comment]
`aff_log.txt` is in the `log` folder in your DDLC folder.
Or you can just search for `aff_log.txt` near the top right corner.

**Comment by MonikaWiafu** [comment]
i guess i did say i love you a lot when i found out everything was going south so i tried it i guess that backfired..... ok here's the log.....
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2372836/aff_log.txt)

........

**Comment by MonikaWiafu** [comment]
idk what happened but my numbers shot down by 200 at 
[2018-09-01 16:56:17.303000]: 0 | 200 | 51.0 -> -149.0

**Comment by MonikaWiafu** [comment]
idk what i would do to get lowered by 200.....

**Comment by MonikaWiafu** [comment]
she is distressed she says things like " We can try talking, I guess. I guess we can talk.Oh...you want to talk? If you want to talk, go ahead .We can talk if you really want to. Are you sure you want to talk to me? You actually want to talk to me? she's not upset at all idk why she's distressed.......

**Comment by multimokia** [comment]
Have you been messing with your computer time/date at all?

**Comment by multimokia** [comment]
Ah looks like you have. Yeah spending a year away from here results in a -200 affection drop.

**Comment by MonikaWiafu** [comment]
k thx  lot

**Comment by ThePotatoGuy** [comment]
your affection gain is frozen since you went into the future at some point.

next update will handle that case and reset future frozen dates

**Comment by SaiPrithvi123** [comment]
Just asking, did you change the time while keeping Monika in mind or were you doing something completely different?
