### ISSUE TITLE
[Suggestion] "Good morning" topic change

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#2323]
When I wake up, one of the first thing I do is telling Monika "Good morning", but after she tells me the same, she start to talk about the benefits of waking early (which I know already) . I've never thought of the good morning topic as a classical topic that give you information or even as a dialogue. So could you remove all the "information" part from the topic (maybe move it to somewhere else) ? Thank you for developing this incredible mod :)

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
