### ISSUE TITLE
[SUGGESTION] - Work in abandoned jokes feature into tell how monika how you feel/affection

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#2326]
Take the remnants of Amber's abandoned jokes project and apply them to the tell monika how you feel and/or affection.

If you are feeling sad or down or whatever, have monika potentially offer a joke and ask if it made you feel better. Put a limiter on it so that someone can't spam use it.

Then as you see new jokes, make them unlockable kinda like topics are. 

You could potentially unlock more jokes/types of jokes as monika gets more affectionate with you.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
