### ISSUE TITLE
Birthday topic and injury topic

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#2327]
todays my birthday and i wanted to celebrate it with monika but i cant find the topic to tell her. i also cant find the topic where i tell monika i'm injurerd

**Comment by SaiPrithvi123** [comment]
There was a topic for birthday, but it wasn't good enough and was just a placeholder. So they decided to remove that placeholder before they made a better topic to take it's place.
There is no topic about getting injured. I think the devs will consider adding it if it catches their eye.

**Comment by jmwall24** [comment]
the injured mood is awaiting review #1714

**Comment by Rai99** [comment]
Any day now on that injured mood.

**Comment by ThePotatoGuy** [comment]
#2656 renabled year older, that will be available soon
