### ISSUE TITLE
[Suggestion] Suggestions related to books

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2328]
When Monika talks about the book "Flowers For Algernon", she says that she's worried about something but assures the player that it's not about the player leaving her. I think this should be changed according t the affection level.

Also when Monika talks about "Hard-Boiled Wonderland and the End of the World", there should be a special dialogue for the players who want to give up their reality and be with her instead.

**Comment by multimokia** [comment]
Player leaving her is based on if you deleted her iirc

**Comment by SaiPrithvi123** [comment]
> Player leaving her is based on if you deleted her iirc

No, currently there is no variation of that topic. It's same for everyone.

**Comment by multimokia** [comment]
Ah, right then, might be something to fix, at least for the "again" bit. Though an affection tie in could be neat.

I've not had a chance to read those two other books yet, but judging by their names I think I can make an assumption (for now) as to what they'd be about, which is also a neat tie in. Might be something to do in the future. Noted.

**Comment by SaiPrithvi123** [comment]
LMAO "Hard-Boiled Wonderland and the End of the World" are not two books, it's a single book. Monika talks about it when you ask her what her favourite book is (Ask a question.> Literature> What's your favourite book?). I haven't read it either, but she says the following about the book:-

"It's about a man who frees himself from his societal restraints by voluntarily imprisoning himself to be with the one he loves."

It's a bit relatable to the player if he wants to give up his reality to be with her.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
