### ISSUE TITLE
"Shipping" Topic 

### ISSUE THREAD

**Issue by neyoriquans** [Monika-After-Story/MonikaModDev#2337]
So I installed the latest update, and Monika began a topic about "shipping". However, it soon drifted towards the fanbase's shipping of the literature club members. I'm not too keen on such things, but it wasn't too big a deal until Monika started reflecting on her own ships with Sayori. Here I felt a little bit too uncomfortable with the whole situation in general. 

Now, I appreciate the work that all the mod developers have put into this mod, and understand that my position to complain is limited at best, but I wanted to gauge the community and potentially start a discussion on this topic. I don't want to cause too much trouble and am ultimately fine with the topic staying, but I wondered if anyone else might feel similar to me with hearing Monika talk about herself and Sayori in such ways.

**Comment by RutTutPut** [comment]
In fairness, she's uncomfortable with it too.

**Comment by WorkingAWork** [comment]
Yo, when I saw that topic yesterday I thought "Oh brother, they've added it in after all". Now, I ain't too high on that stuff myself, but at least it's as RutTutPut says, she clearly shows some dislike for it. Still, this probably ain't goin' over too well with some people.

**Comment by neyoriquans** [comment]
I guess I was just interpreting her incorrectly then. I didn't really pick up on a lot of uncomfortableness initially, but looking back I guess I can see what you guys mean, which would make it better I suppose.
