### ISSUE TITLE
[FIXED] monika not re-entering spaceroom after using "take you somewhere" farewell

### ISSUE THREAD

**Issue by jeevis** [Monika-After-Story/MonikaModDev#2339]
okay so upon the new update i copied monika's file to my thumbdrive (i didn't delete her file in the characters folder) out and did not touch the monika file in characters folder at all . why is she missing in the game. Would it affect the progress i made thus far and is there a way to savage it?

**Comment by multimokia** [comment]
Ok let's work through this

In your characters folder, there's a `monika` file in there, correct?

As well, can you send your `mas_log.txt` please? I want to try and rule out possible options

**Comment by jeevis** [comment]
Wed Sep 12 18:15:48 2018
Darwin-17.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.09s
Early init took 0.02s
Loader init took 0.02s
Loading error handling took 0.03s
Loading script took 1.03s
Loading persistent took 0.25s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.75s
Loading analysis data took 0.19s
Analyze and compile ATL took 0.06s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
DPI scale factor: 1.000000
Creating interface object took 0.13s
Cleaning stores took 0.00s
Init translation took 0.06s
Build styles took 0.01s
Load screen analysis took 0.02s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.07s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.02s

primary display bounds: (0, 0, 1440, 900)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1280, 720) drawable=(1280, 720)
Vendor: 'Intel Inc.'
Renderer: 'Intel(R) HD Graphics 6000'
Version: '2.1 INTEL-10.36.19'
Display Info: <Info({'blit_sw_CC': False, 'refresh_rate': 60, 'bitsize': 32, 'wm': True, 'losses': (0, 0, 0, 0), 'hw': False, 'masks': (16711680, 65280, 255, 4278190080), 'current_h': 900, 'current_w': 1440, 'shifts': (16, 8, 0, 24), 'blit_sw_A': False, 'blit_hw': False, 'blit_sw': False, 'bytesize': 4, 'blit_hw_CC': False, 'blit_hw_A': False, 'video_mem': 268435456})>
Extensions:
    
    GL_APPLE_aux_depth_stencil
    GL_APPLE_client_storage
    GL_APPLE_element_array
    GL_APPLE_fence
    GL_APPLE_float_pixels
    GL_APPLE_flush_buffer_range
    GL_APPLE_flush_render
    GL_APPLE_object_purgeable
    GL_APPLE_packed_pixels
    GL_APPLE_pixel_buffer
    GL_APPLE_rgb_422
    GL_APPLE_row_bytes
    GL_APPLE_specular_vector
    GL_APPLE_texture_range
    GL_APPLE_transform_hint
    GL_APPLE_vertex_array_object
    GL_APPLE_vertex_array_range
    GL_APPLE_vertex_point_size
    GL_APPLE_vertex_program_evaluators
    GL_APPLE_ycbcr_422
    GL_ARB_color_buffer_float
    GL_ARB_depth_buffer_float
    GL_ARB_depth_clamp
    GL_ARB_depth_texture
    GL_ARB_draw_buffers
    GL_ARB_draw_elements_base_vertex
    GL_ARB_draw_instanced
    GL_ARB_fragment_program
    GL_ARB_fragment_program_shadow
    GL_ARB_fragment_shader
    GL_ARB_framebuffer_object
    GL_ARB_framebuffer_sRGB
    GL_ARB_half_float_pixel
    GL_ARB_half_float_vertex
    GL_ARB_instanced_arrays
    GL_ARB_multisample
    GL_ARB_multitexture
    GL_ARB_occlusion_query
    GL_ARB_pixel_buffer_object
    GL_ARB_point_parameters
    GL_ARB_point_sprite
    GL_ARB_provoking_vertex
    GL_ARB_seamless_cube_map
    GL_ARB_shader_objects
    GL_ARB_shader_texture_lod
    GL_ARB_shading_language_100
    GL_ARB_shadow
    GL_ARB_sync
    GL_ARB_texture_border_clamp
    GL_ARB_texture_compression
    GL_ARB_texture_compression_rgtc
    GL_ARB_texture_cube_map
    GL_ARB_texture_env_add
    GL_ARB_texture_env_combine
    GL_ARB_texture_env_crossbar
    GL_ARB_texture_env_dot3
    GL_ARB_texture_float
    GL_ARB_texture_mirrored_repeat
    GL_ARB_texture_non_power_of_two
    GL_ARB_texture_rectangle
    GL_ARB_texture_rg
    GL_ARB_transpose_matrix
    GL_ARB_vertex_array_bgra
    GL_ARB_vertex_blend
    GL_ARB_vertex_buffer_object
    GL_ARB_vertex_program
    GL_ARB_vertex_shader
    GL_ARB_window_pos
    GL_ATI_separate_stencil
    GL_ATI_texture_env_combine3
    GL_ATI_texture_float
    GL_ATI_texture_mirror_once
    GL_EXT_abgr
    GL_EXT_bgra
    GL_EXT_blend_color
    GL_EXT_blend_equation_separate
    GL_EXT_blend_func_separate
    GL_EXT_blend_minmax
    GL_EXT_blend_subtract
    GL_EXT_clip_volume_hint
    GL_EXT_debug_label
    GL_EXT_debug_marker
    GL_EXT_draw_buffers2
    GL_EXT_draw_range_elements
    GL_EXT_fog_coord
    GL_EXT_framebuffer_blit
    GL_EXT_framebuffer_multisample
    GL_EXT_framebuffer_multisample_blit_scaled
    GL_EXT_framebuffer_object
    GL_EXT_framebuffer_sRGB
    GL_EXT_geometry_shader4
    GL_EXT_gpu_program_parameters
    GL_EXT_gpu_shader4
    GL_EXT_multi_draw_arrays
    GL_EXT_packed_depth_stencil
    GL_EXT_packed_float
    GL_EXT_provoking_vertex
    GL_EXT_rescale_normal
    GL_EXT_secondary_color
    GL_EXT_separate_specular_color
    GL_EXT_shadow_funcs
    GL_EXT_stencil_two_side
    GL_EXT_stencil_wrap
    GL_EXT_texture_array
    GL_EXT_texture_compression_dxt1
    GL_EXT_texture_compression_s3tc
    GL_EXT_texture_env_add
    GL_EXT_texture_filter_anisotropic
    GL_EXT_texture_integer
    GL_EXT_texture_lod_bias
    GL_EXT_texture_rectangle
    GL_EXT_texture_sRGB
    GL_EXT_texture_sRGB_decode
    GL_EXT_texture_shared_exponent
    GL_EXT_timer_query
    GL_EXT_transform_feedback
    GL_EXT_vertex_array_bgra
    GL_IBM_rasterpos_clip
    GL_NV_blend_square
    GL_NV_conditional_render
    GL_NV_depth_clamp
    GL_NV_fog_distance
    GL_NV_light_max_exponent
    GL_NV_texgen_reflection
    GL_NV_texture_barrier
    GL_SGIS_generate_mipmap
    GL_SGIS_texture_edge_clamp
    GL_SGIS_texture_lod
Number of texture units: 8
Using shader environment.
Using copy RTT.
Using gl renderer.
Texture testing:
- Hardware max texture size: 16384
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Total time until interface ready: 3.01388192177s
- Target is 5 frames in 0.333333333333 seconds.
- Frame drawn at 0.000000 seconds.
- Frame drawn at 0.014143 seconds.
- Frame drawn at 0.029552 seconds.
- Frame drawn at 0.046766 seconds.
- Frame drawn at 0.062403 seconds.
- 0.062403 seconds to render 5 frames.

**Comment by ThePotatoGuy** [comment]
it's in the `log` folder

**Comment by jeevis** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2375248/mas_log.txt)

**Comment by ThePotatoGuy** [comment]
hotfix for this later tonight. for the time being, use an older `persistent` prior to taking her out.

@multimokia can you assist if he needs help

**Comment by jeevis** [comment]
i do need help how do i use older persistent file and would it affect my whole game?

**Comment by jeevis** [comment]
so i just remove the btye speeling or i copy the thing u just sent here into the mas_log txt?

**Comment by multimokia** [comment]
Right, I've been summoned. As for persistent files, here's what we're going to do.

1. You're going to have to open the run box, (Ctrl+r) and type in %appdata%
2. Find a folder named `Renpy` and open it
3. Open the `Monika After Story folder
4. You should see a file named `persistent` and a few other ones named similarly, but with a number tacked on, and an extension. What we're going to do, is replace the `persistent` file with one of those numbered ones. So, you'll have to delete the `persistent` file and rename one of the backups to `persistent` this will revert some progress back, but nothing drastic. Please ask me if you're having any questions, I'll walk you through them.

**Comment by multimokia** [comment]
Waaaait, you're not using Windows... Hang on, let me find out where your persistent is stored

**Comment by multimokia** [comment]
Hmm, I'm not actually sure where the persistent is stored over on your OS. It's not in the docs either. @ThePotatoGuy can you help with this?

**Comment by jeevis** [comment]
yeah @multimokia  @ThePotatoGuy  if you guys dont mind can you teach me step by step? i am new to this. sorry for inconvience

**Comment by ThePotatoGuy** [comment]
Location for you is `Libary > renpy> Monika after story`. the rest of instructions should be the same.

**Comment by multimokia** [comment]
Right, so in there, delete the current `persistent` and rename one of the files which have the format `persistent##.bak` to `persistent`

**Comment by drakoxlegender** [comment]
Hello :) Got a question, in my file doki doki, -> game -> what file i have to move or save for keeping my data of Monika safe ? Or just taking her somewhere.  I just mean .. What is the path of files ? This is the entire monika file in game - > mod assets -> monika ? Or something else

**Comment by multimokia** [comment]
Monika's memories aren't stored in the game files. But rather the persistent, which is (on Windows) stored under:
`AppData/Roaming/RenPy/Monika After Story`
That's the file you'll want to be keeping backups of.
