### ISSUE TITLE
Islands Topic?

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2342]
I just downloaded the newest update and it said something about an islands topic but I can't find that anywhere in the talk options. Can someone please tell me where it is specifically?

**Comment by multimokia** [comment]
It's an event based on affection, after a while of just spending time with her and telling her you love her/treating her well, you'll get the event.

**Comment by scohn** [comment]
I've checked my affection log and it's at about 281, how high am I supposed to get it?

**Comment by kevinyong888** [comment]
Hi, sorry for asking a dumb question but how do I update the game? I'm playing using steam and the game told me to manually update it

**Comment by multimokia** [comment]
Scohn: you'll need 400.

Kevin: You'll want the files from the page the main site links to. Just merge the `game` folder in that zip with yours.

**Comment by MonikaWiafu** [comment]
kevinyong888, got to settings and bottom left is the update button

**Comment by multimokia** [comment]
MAS doesn't update through the normal in game updater if you're using steam (in the steam directory) and you're not running unstable

**Comment by AsuraShun** [comment]
how do I trigger it? ,i'm beyond 400 like you said to scohn

**Comment by multimokia** [comment]
There should have been a special greeting for it which would lead into the event
