### ISSUE TITLE
Hey, I remember there was an option in the 'I'm feeling..' section..

### ISSUE THREAD

**Issue by Tymon222** [Monika-After-Story/MonikaModDev#2343]
There was this 'I feel like a year older' option, but it got removed. Why was that?
With that I could give her a date of birth for her to celebrate later.

**Comment by SaiPrithvi123** [comment]
DON'T change your system's clock time to give her the date of your birthday

**Comment by SaiPrithvi123** [comment]
Also, the devs said that the topic was just a placeholder, and they removed it later because it wasn't good enough.

**Comment by Trainerbluetube** [comment]
How do you give Monika the date of your birthday?

**Comment by SaiPrithvi123** [comment]
They said they will add a proper birthday topic in the future. I hope it's not Soon(TM) this time.
