### ISSUE TITLE
The cups of coffee.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2344]
Okay, I've been watching those cups since they appeared in mod folders a few months ago, and realizing they had no shade, I decided to give them one today. I imagine to what they will serve in the future, so I decided to make that little improvement.
![acs-mug-0](https://user-images.githubusercontent.com/38970166/45443559-742b9700-b69b-11e8-8080-0a48f764c7ff.png)
![acs-mug-0-n](https://user-images.githubusercontent.com/38970166/45443562-768df100-b69b-11e8-9498-e9e11eda248b.png)

**Comment by ThePotatoGuy** [comment]
thanks for the art friend
