### ISSUE TITLE
Strange typo

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#2347]
In "ask a question" / "Ddlc" / "Isn't this game metafictional?" the  '  is the first thing (don't know how to say it in english) of the second line. Am I the only one triggered by that? If so, then leave it, doesn't make any big difference anyway. But I would appreciate if you could just bring the precedent word at the second line. Thank you for the attention, and thank you for the mod.
![bad typo ddlc metafictional](https://user-images.githubusercontent.com/38837456/45451130-77924300-b6da-11e8-92f1-4019dbb0e63a.PNG)

**Comment by MonikaWiafu** [comment]
got that too

**Comment by ThePotatoGuy** [comment]
write this in #2336

**Comment by monikLover** [comment]
#2470
