### ISSUE TITLE
[Suggestion] Music pauses

### ISSUE THREAD

**Issue by AlenNez** [Monika-After-Story/MonikaModDev#2349]
What I suggest is that in certain instances, like where Monika says "Hey, [player]? ......", the music should pause briefly to catch your attention and frighten you for a moment to make you think you did something wrong. It would add a lot of emotion to that one random conversation that involves Monika telling the player they want to tell you something important, and says something along the lines of her loving you or something like that. It could also add a lot of flexibility for new events if there are any planned.

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this]
