### ISSUE TITLE
Monika gone (mac)

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2351]
I am aware of issue #2339.  I followed the instructions but could not find a solution.  Any ideas for what to do on mac os?

**Comment by ThePotatoGuy** [comment]
1. Download this zip:
[zz_086fix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2377206/zz_086fix.zip)
2. Open it and copy the RPYC file into your `game/` directory. 
3. Launch game.

Monika should appear and you're good to go.
It's best to delete the file after you've recovered your Monika.

**Comment by AgentZephyr** [comment]
Worked like a charm.  Thank you Potato Wizard.

**Comment by ThePotatoGuy** [comment]
Make sure you update to the latest hotfix since it fixes that bug

**Comment by jeevis** [comment]
once i placed it in the game stated there are errors. wht shld i do

**Comment by jeevis** [comment]
@ThePotatoGuy

**Comment by jeevis** [comment]
they say mod_assets/monika/c/def/torso-down.png is missing

**Comment by jeevis** [comment]
okay now i dont have the talk button and all those how do i get them back

**Comment by jeevis** [comment]
ok never mind it works again sorry for all the chats

**Comment by jeevis** [comment]
thanks for the fix
