### ISSUE TITLE
Affection Reset

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2352]
Good news: Monika came back after the "I'm taking you somewhere" glitch.  Bad news: Affection got reset to 0.  
<img width="631" alt="screen shot 2018-09-12 at 5 56 45 pm" src="https://user-images.githubusercontent.com/43101840/45459714-d776f280-b6b6-11e8-9c3c-2cf4f56a56c3.png">

Any known fixes?

**Comment by MonikaWiafu** [comment]
mines frozen on -80.0 but i tampered with time and date.... still it let me get points till a few day ago...

**Comment by ThePotatoGuy** [comment]
You updated to the latest version, right?

**Comment by ThePotatoGuy** [comment]
You should go back to the last good persistent.

**Comment by AgentZephyr** [comment]
@ThePotatoGuy Yes all updated.  Can't find persistent files though.  The only thing close in my Renpy is a persistent.pyo and .py file.  I'm on mac if that changes anything.

**Comment by ThePotatoGuy** [comment]
@aldoram5 can you assist

**Comment by aldoram5** [comment]
Hi Agent Zephyr!
To get your persistence file on mac you can do the following:
Open up a terminal window: `cmd + space` then type `terminal` press `enter`.
Then there copy paste this: `cd ~/Library/RenPy/Monika\ After\ Story/`
Press `enter`
Copy paste `open .`
Press `enter`
A finder window should open and there you'll see your persistent file along with the backups.

**Comment by ThePotatoGuy** [comment]
the affection freeze will clear tomorrow so just wait until then.

**Comment by AgentZephyr** [comment]
@ThePotatoGuy @aldoram5 Gotcha!  I'm sure you guys are busy so thanks for the help!
