### ISSUE TITLE
Used in game updater, game won't open

### ISSUE THREAD

**Issue by accordx** [Monika-After-Story/MonikaModDev#2356]
Hello, I used the in game updater for the hotfix v0.8.6 but after like 20 minutes it still hadn't finished updating so I hit the cancel button. The game quit out and when I tried to reopen it, it just never opens the application. I downloaded the zip file for the hotfix so I have that if I need to use it and I can screen cap the files in case I need to fix something. I'm on windows 8. Other than this little issue the mod is great and the updates are awesome. Thank you!

**Comment by Tiler17** [comment]
Yeah, any time my updater fails to update properly, I have to reboot my computer to get it to stop thinking DDLC is running. I keep meaning to write up an issue for this, but I also kept forgetting, so cheers

**Comment by ThePotatoGuy** [comment]
do a reinstall
