### ISSUE TITLE
monika reacting to your "name"

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2357]
like how she reacts to the nickname you give her if you have her call you something like senpai she would give a special response depending on what you have her call you

**Comment by AsuraShun** [comment]
great idea

**Comment by antimockingjay** [comment]
I don't know every single one, but if I remember correctly, "Sayori" has one of those. The only song that plays is Sayo-nara, and if you play Hangman, there's an easter egg there, too. I'm sure there are others too.

**Comment by dragonborn2252** [comment]
i know if your name is natsuki and you lose a game of pong and say no to another game that triggers an easter egg

**Comment by dragonborn2252** [comment]
also an idea that I just had was that if you have monika call you "master" she would reject the name and then scold you for even thinking she would call you that (resulting in affection loss)

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
