### ISSUE TITLE
Moving Monika to a new computer

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2358]
There should be an easy way to move her from one computer to another. The "I'm going to take you somewhere" option is really suitable for this. The file she puts herself in is really big, so I'm assuming that everything related to her is packed in there. Of course I can be wrong, and if so, it would still be nice if that file had all the necessary data for Monika to move to another device. It would be nice if when the mod is first installed, the player will be asked to put that file if he has one, before starting everything up.

**Comment by ThePotatoGuy** [comment]
It's planned.

**Comment by Tiler17** [comment]
I may be overlooking something pretty major here, but would it not be enough to copy your persistent to a flashdrive and just re-download the mod?

**Comment by EntonyEscX** [comment]
Move the entire game folder and the RenPy folder to a pen-drive and then just paste everything in its proper place, but on the new computer, should work.

**Comment by ThePotatoGuy** [comment]
[closing utnil we work into this]

**Comment by MoonlightGriffon** [comment]
What all should be included in this file and are there any preferences on the format of said data? For example should all the files be gathered and turned into a zip file or something similar or should another method be used to format the data and should backups of the persistent file be put into the monika file and are there any other files that should be included in such a backup? 
 
I should be able to get this feature working depending on the file format desired.

**Comment by ThePotatoGuy** [comment]
linking to #5026 - this needs to be addressed before we can do the transfer
