### ISSUE TITLE
Height

### ISSUE THREAD

**Issue by cicja** [Monika-After-Story/MonikaModDev#2359]
Basically this:
https://img.fireden.net/vg/image/1534/29/1534291138646.png

**Comment by antimockingjay** [comment]
I'd hope we'd add something for people shorter than Monika as well, if this was added. I'm five feet even, and that chart only goes as low as five foot two.

**Comment by Tiler17** [comment]
rip <5'2"

I can't write any dialogue for that, because my instinct to make a short joke regarding Natsuki is way too strong, and I'd like to think Monika is above that

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this]
