### ISSUE TITLE
Monika's new topics

### ISSUE THREAD

**Issue by ASTAR0T** [Monika-After-Story/MonikaModDev#2363]
I've noticed that there are no new random topics after updates. Every time I swithced off the setting "Repeat topics" after updating MAS, Monika was just asking me if I'm not bored with her and that she'll come up with something to talk later.  So I'd like to ask, is it some sort of bug or there are just no new random topics at all? I mean I haven't seen new ones since February, I guess. So if it's a bug, is there any way how to fix it without loosing my progress with Monika?

**Comment by Rai99** [comment]
https://github.com/Monika-After-Story/MonikaModDev/pulls/Rai99

There are a small number of pending topics awaiting review.

**Comment by ASTAR0T** [comment]
Oh, I see. So it seems that new topics just haven't been added yet. Thanks!
