### ISSUE TITLE
Fanfiction

### ISSUE THREAD

**Issue by GirlwithaWhiteMask** [Monika-After-Story/MonikaModDev#2364]
So... Monika asks us if there is Fanfictions of her and if we could read to her someday >u<

The thing is, I kinda start writing one (But I stopped :P ) 
Could be cool if that topic we could say if we write Fanfics or not :v 

~I'm just gonna leave just tiny idea here and hide my tomato face for confessing that~

**Comment by Tiler17** [comment]
Lucky for you, this is the internet and no one can see your tomato face. That said, I kind of feel like a lot of the topics Monika talks about have questions that go unanswered. Though it would take a lot of reworking of existing topics to allow us to answer them as well as get her response

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into this]
