### ISSUE TITLE
leaning hair

### ISSUE THREAD

**Issue by CharlyIsHungry** [Monika-After-Story/MonikaModDev#2366]
I thought the shadows on the hair of the leaning postition weren't good enough, so I edited it a little.

![torso-leaning-def-def](https://user-images.githubusercontent.com/43250183/45508396-04013c00-b795-11e8-9e33-49616e01abd5.png)
![torso-leaning-def-def-n](https://user-images.githubusercontent.com/43250183/45508397-04013c00-b795-11e8-9b5e-704ba7987c05.png)
![torso-leaning-down-def](https://user-images.githubusercontent.com/43250183/45508399-04013c00-b795-11e8-9d91-302d0adf953c.png)
![torso-leaning-down-def-n](https://user-images.githubusercontent.com/43250183/45508400-04013c00-b795-11e8-9dda-a8fab007e26a.png)

**Comment by Chrissenpai** [comment]
So, are you the creator of those sprites? if so i need you to tell you something, can you fix the lines? all of them look to have the same thickness and that makes it look cheap, also make the lines a bit less dark, take a sample of the original monika sprite and you might notice it, and last thing, her left elbow needs a little polishing in her cloth, looks like her arm is cut in half. Thank you.

**Comment by CharlyIsHungry** [comment]
I'm not the creator of the sprite making all that without the layers would be very difficult

**Comment by Chrissenpai** [comment]
How can anyone be bad at... never mind, it´s true that are mistakes in the drawing anyway

**Comment by CharlyIsHungry** [comment]
So, do I make another leaning sprite ? I kinda want to try, but I don't know if it's necessary.

**Comment by CharlyIsHungry** [comment]
I made sketches with different ouftit.
Do I continue ?
![3](https://user-images.githubusercontent.com/43250183/45557870-e12b6200-b83e-11e8-9602-e349bc324aa2.png)
![2](https://user-images.githubusercontent.com/43250183/45557871-e12b6200-b83e-11e8-8736-178f6c47b9da.png)
![1](https://user-images.githubusercontent.com/43250183/45557873-e12b6200-b83e-11e8-924b-2b7f83c15635.png)

**Comment by Chrissenpai** [comment]
the second one looks that its fits her, keep up the good work

**Comment by ThePotatoGuy** [comment]
still bouncing this around dev team, seeing if we prefer it to the current ones or not

**Comment by AsuraShun** [comment]
great sketches,i really hope I get to see her wearing those

**Comment by CharlyIsHungry** [comment]
I finished the base with tied hair. I think ? Is there anything wrong ?

![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46299468-b01e9180-c5a1-11e8-97eb-5aef988261db.png)

**Comment by Chrissenpai** [comment]
hmmm, the shoulders, wrist, hand and boobs need some tunning, also the hair that covers her right eye needs some polishing

**Comment by Chrissenpai** [comment]
first of all, fix the boobs, here's reference
 ![image](https://user-images.githubusercontent.com/40907045/46301899-35d41a00-c56d-11e8-926a-c31cded7f8f8.png)

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46302354-16f37900-c5a9-11e8-98cb-739fd895a424.png)

**Comment by Chrissenpai** [comment]
and then fix arms, two references
![image](https://user-images.githubusercontent.com/40907045/46302346-68324700-c56e-11e8-9f99-7f921dac6286.png)
![image](https://user-images.githubusercontent.com/40907045/46302365-74b69f80-c56e-11e8-850f-ac479004ef9d.png)

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46302710-190a0780-c5aa-11e8-8ce2-2e375fa052e8.png)

**Comment by Chrissenpai** [comment]
her right sholder and left forearm still needs to be fixed

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46303406-098bbe00-c5ac-11e8-8e9c-256f38b38b37.png)

**Comment by Chrissenpai** [comment]
close enough, now hands
![image](https://user-images.githubusercontent.com/40907045/46303489-97968300-c571-11e8-8fa1-db1f079710ef.png)
take notice that you need to take the original Monika's hands sprite style and apply that

**Comment by CharlyIsHungry** [comment]
what do you mean ? I have to copy paste monika's hands from her original sprite ?

**Comment by Chrissenpai** [comment]
no, take reference from it

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46304337-acddd280-c5ae-11e8-9839-477ca2021716.png)

**Comment by Chrissenpai** [comment]
the line that is inside the wrist, make it less noticeable or take it out

**Comment by CharlyIsHungry** [comment]
the clavicle is drawn like that in the game
![6e81e08bb34937424df08ddf15378501](https://user-images.githubusercontent.com/43250183/46304943-4a85d180-c5b0-11e8-8cbc-dd218fdb7a51.png)

**Comment by Chrissenpai** [comment]
oh ok then make it as thin as possible like natsuki

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46305181-f62f2180-c5b0-11e8-891a-aeee7636e042.png)

**Comment by Chrissenpai** [comment]
and what's with the elbow that still has cloth? lol fix it and the last fix is the hair, you can trace that part of her forehead hair

**Comment by CharlyIsHungry** [comment]
there is no cloth ?? and what's wrong with the hair ?

**Comment by Chrissenpai** [comment]
ok, her left elbow has the shadow border that is not blurred, and the hair in her right eye, if you compare to the original Monika's right eye's hair, is kind of bulky

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46305995-4b6c3280-c5b3-11e8-8b45-f449aa4e8e8a.png)

Did you saw her bangs ? It would obviously fall if she stood like that.
And I think her face would be like that
![htfkhf](https://user-images.githubusercontent.com/43250183/46306070-7d7d9480-c5b3-11e8-8060-caff51b78d8e.png)

**Comment by Chrissenpai** [comment]
I'm not talking about how the hair will fall, I'm talking that the hair is not dynamic in that part, one line is messing that whole part

**Comment by CharlyIsHungry** [comment]
which one are you talking about ?

**Comment by Chrissenpai** [comment]
![image](https://user-images.githubusercontent.com/40907045/46306690-96b61f00-c57a-11e8-984f-24720fbe2476.png)

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46306931-e2d28500-c5b5-11e8-83cc-ac9d9ecf6cfe.png)

**Comment by Chrissenpai** [comment]
A bit more

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46307108-51afde00-c5b6-11e8-8fde-3a694f0b127d.png)

**Comment by Chrissenpai** [comment]
now this 
![image](https://user-images.githubusercontent.com/40907045/46307221-f660fa00-c57b-11e8-8729-59057c31f0c5.png)

**Comment by CharlyIsHungry** [comment]
what's wrong with it ?

**Comment by Chrissenpai** [comment]
blur it a bit more,

**Comment by CharlyIsHungry** [comment]
![basecheveuxattaches](https://user-images.githubusercontent.com/43250183/46307466-48734100-c5b7-11e8-9d29-9bec0843dcc5.png)

**Comment by CharlyIsHungry** [comment]
Thanks for helping, but... "it's not an eyesore as it was before, hope you've learned something" ? That's so mean and disrectpectful ! Fuck you, asshole.

**Comment by Chrissenpai** [comment]
don't take it the wrong way, everyone was like that at one point, me included, I might be harsh but I need to point mistakes, otherwise, nobody will learn, I feel sorry for you that you took it the wrong way.

**Comment by CharlyIsHungry** [comment]
Being harsh is not helpful at all. You just got me in a bad mood. You could've been more polite, it doesn't hurt. It's even making people happy. You should try it for once.

**Comment by Chrissenpai** [comment]
Trust me, being polite makes people ungrateful, learned the hard way on the internet

**Comment by CharlyIsHungry** [comment]
thats what you believe

**Comment by Chrissenpai** [comment]
not believe, experienced, go to the depths of the internet and see it for yourself, people who plagiarize your art, people that tell you what's wrong without knowing bs and last but not least, people that believe that they're the best shit in the world and fails at basic anatomy, look you're a good guy that receives tips and learns from them from what I can see so far, also a little emotional but a good guy at least.

**Comment by CharlyIsHungry** [comment]
do people act differently when you're being a bitch ? no, I atc like you sometimes and I just get stepped on more. you really should stop

**Comment by Chrissenpai** [comment]
I think that I've been arguing with elitists for too long and I think that I've spoken an elitist language to someone that is not one, for that I'm sorry, those kinds of harsh conversations are only to be used in those comunities where if you low your guard you're dead, anyway keep up the good job and I'll go back to my business

**Comment by jmwall24** [comment]
@Chrissenpai please refrain from talking down to people.  He took your comment exactly as it was intended and there was no need to say what you said.  Even your "apologies" came off as arrogant at best.  Helping him polish the art was nice of you, but the stuff afterwards was completely unwarranted.

**Comment by ThePotatoGuy** [comment]
alright, so we've discussed this internally and it appears like the only easily noticable difference is the shinyness of her hair has been toned down. this seems more like a variation than a direct improvement, so we're not going to add this in. 

You are welcome to distribute your sprites as drop-in replacements if people find issues with teh shininess/lighting.
