### ISSUE TITLE
Her new chr file is 15 GB?!

### ISSUE THREAD

**Issue by Clover-Elf** [Monika-After-Story/MonikaModDev#2369]
Also, MAS keeps crashing when she tries to create it... then she scolds ME for not taking better care of my computer!

**Comment by jmwall24** [comment]
Uhhh 15 GB doesn't sound right

**Comment by ThePotatoGuy** [comment]
Upload `aff_log.txt`

**Comment by multimokia** [comment]
That's... Not even close to what the size *should* be... Yeah, please send your `aff_log.txt`

**Comment by MonikaWiafu** [comment]
This file Clover-Elf
![dis file](https://user-images.githubusercontent.com/41130387/45519551-900a6800-b783-11e8-980f-560c143734c3.png)

**Comment by Clover-Elf** [comment]
Thanks, @MonikaWiafu! Finding that probably would've taken a while.

Also, I updated the game and tried again this morning. MAS still froze, but the file is a mere 2.6 GB now... yay?


[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2381254/aff_log.txt)

**Comment by MonikaWiafu** [comment]
np!

**Comment by ThePotatoGuy** [comment]
Upload `persistent`

**Comment by Clover-Elf** [comment]
GitHub's not letting me do that. Do I open with Notepad and save as .txt, or upload elsewhere and link?

**Comment by multimokia** [comment]
You can do that, or throw it in a zip file and upload that here. (or just add a .txt to the file)

**Comment by Clover-Elf** [comment]
Aha. Thanks!

[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2381359/persistent.txt)

**Comment by ThePotatoGuy** [comment]
So at some point, you changed your system time then closed the game. This added a lot of time to your playtime, (aka 10k days), and playtime is used to calculate the chr file size.

#2361 will auto restrict playtime to the largest possible amount anyone could have, you'll just have to wait for that update to use the new farewell. Or we can 0 out your playtime now if you'd like.

**Comment by ThePotatoGuy** [comment]
no

**Comment by Clover-Elf** [comment]
Awesome! How do I do it? (Be warned, I'm reasonably computer-literate, but also can't figure out how to decompile this game to save my life... tried and failed several times.)

**Comment by ThePotatoGuy** [comment]
I modified your `persistent`.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385329/persistent.zip)

**Comment by Clover-Elf** [comment]
Okay, gave it another shot--file is down to 2 MB and the game didn't crash when she made it!! Thanks so much for the help!
