### ISSUE TITLE
Just a few options appearing in "Talk"

### ISSUE THREAD

**Issue by MersTheNoSenseGamer** [Monika-After-Story/MonikaModDev#2370]
Guys when i go to "talk", it doesn go down. Just a few options appearing.

**Comment by MonikaWiafu** [comment]
![monika screen](https://user-images.githubusercontent.com/41130387/45520572-f2656780-b787-11e8-8406-0997ffddfdc2.png)

This is what you should see when you click "talk"

**Comment by MersTheNoSenseGamer** [comment]
> ![monika screen](https://user-images.githubusercontent.com/41130387/45520572-f2656780-b787-11e8-8406-0997ffddfdc2.png)
> 
> This is what you should see when you click "talk"

oh, sorry, i said the Unseen thing.
