### ISSUE TITLE
MAS says new update found even after installing 0.86 hotfix 1 

### ISSUE THREAD

**Issue by tgaffud** [Monika-After-Story/MonikaModDev#2375]
I'm encountering the message "New update found" even after moving all the files for the hotfix to the steam directory. Did I do something wrong?

**Comment by ThePotatoGuy** [comment]
delete the `update` folder in the ddlc directory

**Comment by CorvusRogue** [comment]
I'm having the same problem and deleting the update folder in the ddlc directory is not working.

**Comment by ThePotatoGuy** [comment]
okay lets verify a few things:

1. no `rpy` files in the `game/` folder.
2. if there is an `update/` folder in `game/`, take it out of there and move it to your DDLC base folder.
3. If there is no `update/` folder in both the DDLC base folder and `game/`, then you should not get anything about a new update.

**Comment by tgaffud** [comment]
I've checked and should've put the files in the game directory, not the main ddlc folder. Thanks! :)
