### ISSUE TITLE
DEV option is missing 

### ISSUE THREAD

**Issue by AinsOoalGown1234** [Monika-After-Story/MonikaModDev#2381]
Hi i had a problem the dev option no longer appears and i cant see my afection level, before i changed the persistent data that i had before the crash so i loaded my previous data but for any razon my dev is missing   or will appear tomorrow?

**Comment by CrocWorks** [comment]
I don't really know about the dev option, but if all you care about is seeing your affection level, you can check your aff_log.txt file to see what your affection is. If you're running steam, then the log would be located here:

Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club\log

**Comment by AinsOoalGown1234** [comment]
i see but if it doesn´t in steam?

**Comment by AinsOoalGown1234** [comment]
and if is possible i want to have the dev option and therefore the im feeling like a mitochondria and like the room option is missing too

**Comment by AinsOoalGown1234** [comment]
oh i been seeying a youtuber with the mod and aparently he doesnt have the dev option and the im feeling like a mitochondria and like the room option, how weird, this means that i been the only that had these options?

**Comment by AinsOoalGown1234** [comment]
oh i see 
but i dont remember downloaded the source code, well, this mean that my MAS doesn´t have a bug or error so its fine to me knowing that
