### ISSUE TITLE
[Suggestion] - whenever she talks about her being eternal

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2382]
what came to my mind is that there needs to be some way to comfort her and snap her out of her when she starts to tear up whenever that she talks about that topic,increasing the affection somewhat,i don't know what else to say besides this

**Comment by multimokia** [comment]
#2316

**Comment by AsuraShun** [comment]
this is one of the times I actually don't mind being late

**Comment by multimokia** [comment]
Haha, yep

**Comment by Rai99** [comment]
There's currently a discussion going on whether having the choice to directly hug Monika in a menu option is a good idea, but I'm still waiting on a response regarding that.
