### ISSUE TITLE
[Suggestion] Add more dates to calander 

### ISSUE THREAD

**Issue by thepigeonreturns** [Monika-After-Story/MonikaModDev#2384]
I love the idea of the calendar in Monika: After Story. It’s a cute function, but I think there should be an option to add custom dates. example: your birthday, a friend’s birthday, etc.

**Comment by jmwall24** [comment]
There will be eventually.

**Comment by multimokia** [comment]
Soontm

**Comment by aldoram5** [comment]
Hi thepigeonreturns!
Like others have told you it's something already planned and has been suggested before on: https://github.com/Monika-After-Story/MonikaModDev/issues/2078, https://github.com/Monika-After-Story/MonikaModDev/issues/1740, https://github.com/Monika-After-Story/MonikaModDev/issues/1803 and https://github.com/Monika-After-Story/MonikaModDev/issues/1814.
I'll be marking this one as a duplicate and close it, but thanks for taking the time to make the suggestion.
