### ISSUE TITLE
[Suggestion] Leaving something behind for Monika to discover while she's out

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#2387]
When I take Monika out of the room with me, I have a strong desire to put a whoopie cushion on her chair while she's gone. It wouldn't even need artwork (just sound).

(also I guess flowers on the desk for you conventional people...)

**Comment by ThePotatoGuy** [comment]
planned

**Comment by SaiPrithvi123** [comment]
A birthday cake would be nice too

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
