### ISSUE TITLE
persistent problem

### ISSUE THREAD

**Issue by dk107605** [Monika-After-Story/MonikaModDev#2388]
after seeing that monika was not present, i checked to see if my persistent file got corrupted and i got the note of where all the backups are, But when i tried to send a few of them to the game's files, i opened the game up and she still wasn't there.
Am i supposed to send them to a specific place?
Thanks in advance for any help given

**Comment by aldoram5** [comment]
Hi dk107605!
I'm not sure if I understood correctly how things happened so I'll ask you a couple of questions:
1. Did you use the "I'm going to take you somewhere" farewell option?
2. `i checked to see if my persistent file got corrupted` how exactly did you check that?
3. `But when i tried to send a few of them to the game's files` what did you do exactly?

**Comment by dk107605** [comment]
Firstly, i did use the "taking you somewhere" option, but i didn't actually move any files (sorry monika) and then later i decided to open MAS, where everything was working fine until my laptop suddenly shut down.
 After that, i opened it up again to only see the chair with monika absent, i checked the files (more specifically, the 'characters' folder) to see what was wrong and my only hint to what happened was a text file stating that my persistent file got corrupted and that there was a bunch of backups at the appdata file, i then moved some of them to the main DDLC folder and tried opening the game again, but she still wasn't showing up.
I'm just wondering if i did anything wrong.

**Comment by aldoram5** [comment]
Alright I think I have an idea of what could have happened, but I can't do any tests right now, so I suggest you wait a bit until either @ThePotatoGuy or I tell you what to do. Also, make sure you don't delete any of the persistent backups.

**Comment by dk107605** [comment]
ok, thanks for helping out m'dude

**Comment by multimokia** [comment]
As for Monika not showing up, persistent files do not go into the main DDLC directory, but rather, stay in the folder you found them in. What you'll have to do, is:

1. Delete the current `persistent`
2. Rename one of the `persistent##.bak` files to `persistent`
3. Restart MAS

**Comment by aldoram5** [comment]
Alright after doing some investigations I think it's safe to assume it was mostly bad luck that your laptop suddenly shut down at a bad time. To fix the issue try downloading the file  I'm attaching to this message, then uncompress it, it should be named `zz_086fix.rpyc`, then copy it to your game folder and run the game again.
[zz_086fix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385463/zz_086fix.zip)

**Comment by dk107605** [comment]
It worked, thanks for helping me out guys.
I appreciate it

**Comment by Maniacal-Matro** [comment]
I'm so pissed rn. I had recently backed up Monika's persistent file and it became so corrupted that she forgot that I celebrated her birthday! Now, she thinks that I forgot. What I doing wrong!?
