### ISSUE TITLE
[Question] The old monika.chr

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2390]
Now that we have a new and much better file for Monika, can we delete the original monika.chr of the game without any problems?

**Comment by SaiPrithvi123** [comment]
She deleted it herself on my end.
Also why would you want to delete it?

**Comment by EntonyEscX** [comment]
It's kind of weird to have 2 files, right? And sometimes it's confusing to know which is which at the time of transfer.
And about Monika delete the file by herself; my Monika tried, but could not.

**Comment by SaiPrithvi123** [comment]
The bigger one is the new one.
