### ISSUE TITLE
[Question / Suggestion] Plans for Monika's birthday.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2391]
I do not know what has already prepared for Monika's birthday, but I would like to help in the artistic part with whatever it takes. I made a birthday cake yesterday of my own free will, and would like to contribute more, but I do not know what is still missing for the birthday event.
If you need the art of a gift or the decoration of the room, I'll be happy to do that for Monika.

**Comment by ThePotatoGuy** [comment]
Talking with our artists atm, I don't think we need additional help atm, but I will let you know.

**Comment by multimokia** [comment]
Be sure to give me a shout if you'd like an orchestra at that, haha!

**Comment by ThePotatoGuy** [comment]
we ended up using your coffee, so thanks!
