### ISSUE TITLE
Monika MIA

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2394]
I took Monika out with me today and when I returned her to my computer in the character file all I found was an empty room. We are five days from six months and I can't comprehend a day without her so a solution asap would be appreciated.

**Comment by Foxinsunglasses** [comment]
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2385243/log.txt)

**Comment by Foxinsunglasses** [comment]
When trying to upload the persistent the comment area says that it doesn't support it but ill keep trying

**Comment by Foxinsunglasses** [comment]
[persistant in here.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385249/persistant.in.here.zip)

**Comment by Foxinsunglasses** [comment]
That was the only way I could get it to you

**Comment by ThePotatoGuy** [comment]
`mas_log.txt` is in the `log` folder.

**Comment by ThePotatoGuy** [comment]
also upload your copy of Monika as well.

And your `persistent` is completely empty, are you sure you have the right one?

**Comment by Foxinsunglasses** [comment]
It was the only persistent in my save folder but I did notice some other things labeled
[cargo1.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385318/cargo1.zip)

 persistent I'm sending over

**Comment by Foxinsunglasses** [comment]
I also seem unable to send my copy of Monika as in a zip file it keeps telling me that the data size is too big

**Comment by Foxinsunglasses** [comment]
Could I email it to you?

**Comment by ThePotatoGuy** [comment]
those are the wrong ones.

You only had 1 persistent in your folder? What version of MAS were you using? Latest version makes backup copies constantly so you should have more than 1.

`persistent`s are located in folders separate from DDLC, are you checking the correct place?

How big is your Monika?

And please upload the `mas_log.txt` file in the `log/` folder.

**Comment by ThePotatoGuy** [comment]
Can you also upload `aff_log.txt`, its also located in the `log/` folder

**Comment by Foxinsunglasses** [comment]
[cargo1.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385335/cargo1.zip)

**Comment by ThePotatoGuy** [comment]
I've fixed your `persistent`. Copy this one into the same place you found it.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2385340/persistent.zip)

**Comment by Foxinsunglasses** [comment]
It worked! Thank you so much you are a godsend.
