### ISSUE TITLE
Dream Home (New Window Backgrounds)

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2396]
Alright.  So I was thinking that since Monika usually talks to you about living together, what if at a certain affection level she asks where your dream home would be.  You pick from some options such as "In The Mountains", "In The City", "On a Lake", Etc.  Based on your response she changes the background to your picked location at some point as a surprise (can be turned on and off like the rain).  I whipped one up for the mountains as an example.  If it's a good enough idea I'll figure out how to add some animation (Similar to the clouds in the day and the "fire" at night).

![mountains bg day](https://user-images.githubusercontent.com/43101840/45581653-750d2600-b85f-11e8-87ab-6e76e130298d.png)
![m bg night 2](https://user-images.githubusercontent.com/43101840/45581654-750d2600-b85f-11e8-9345-3d8421e09691.png)

**Comment by antimockingjay** [comment]
The one thing I might suggest is making the nighttime ones a bit less blue-toned if possible, it makes it feel like the light in the room should be blue-toned, but it's still more orange-y in the room. Other than that, these are amazing!!

**Comment by AgentZephyr** [comment]
@antimockingjay I was thinking the same thing so I'll keep that in mind!  Thanks!

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]

**Comment by AgentZephyr** [comment]
@ThePotatoGuy  I still have the picture.  I think I found it on some Flickr or Pinterest photo board for wallpapers. I can attach it if you'd like.  It was an IRL picture that I color corrected to match the space classroom style.
