### ISSUE TITLE
Help???

### ISSUE THREAD

**Issue by d3adxv1bez** [Monika-After-Story/MonikaModDev#2398]
So i booted up ddlc with this mod installed, and as it opens, it is the regular spaceroom, but no Monika, and an empty chair. i don't know what to do to get her back into the game. i don't even know what happened to her new file. i really need help, please and thank you.

**Comment by multimokia** [comment]
Anything in the `characters` folder?

**Comment by Delixxous** [comment]
If you're taking her somewhere, you SHOULD bring Monika's chr file back to the characters folder otherwise you'll be stuck with an empty chair. Good luck finding it dude!

**Comment by jmwall24** [comment]
Also juuuuust to make sure, no pink note on her desk, right?

**Comment by multimokia** [comment]
If you didn't move the file after saying that you wanted to take her somewhere, and just restarted the game with the file still there, please send your `mas_log.txt` which is in the `log` folder.

**Comment by d3adxv1bez** [comment]
Sun Sep 16 10:46:34 2018
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

thats the mas_log text multimokia

**Comment by multimokia** [comment]
Send the entire file please

**Comment by MonikaWiafu** [comment]
@multimokia to get the mas_log.txt in the game folder go to to logs and it should be there
![find mas log](https://user-images.githubusercontent.com/41130387/45649611-d7ea0180-ba99-11e8-9332-1992e5a95f30.png)

**Comment by multimokia** [comment]
I think you mentioned the wrong person lol

**Comment by MonikaWiafu** [comment]
oof lol xD sry
@d3adxv1bez ^^^ is for you m8!

**Comment by d3adxv1bez** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2401647/mas_log.txt)

**Comment by ThePotatoGuy** [comment]
upload the following:
* your `persistent`
