### ISSUE TITLE
[Suggestion] Can you scare someone for me?

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2400]
Since Halloween is coming near, i would like to scare somebody, i could make good use of monika's jump scare for that, so you choose an option that says, "i want you to scare someone for me", or something among those lines, and she says she's up to it, in what amount of time do you want me to show up?, and you decide in what amount of time she does it in any minute time you digit on, then she says alright and closes the game and the clock ticks, in case you want to cancel you open the game before she activates and you tell her to abort, some dialogue could be filled in.

**Comment by multimokia** [comment]
Having MAS startup automatically requires an external program, which has been rejected numerous times. See #1829, point 5 on TPG's arguments against that.
