### ISSUE TITLE
plush and cupcake

### ISSUE THREAD

**Issue by CharlyIsHungry** [Monika-After-Story/MonikaModDev#2401]
Monika said she wants a cupcake and a resplendent quetzal 'w'

![cupcakelight](https://user-images.githubusercontent.com/43250183/45588458-65e8af80-b915-11e8-93a8-e276f655e460.png)
![cupcakedark](https://user-images.githubusercontent.com/43250183/45588464-83b61480-b915-11e8-9a70-eed3f4db3371.png)
![plushlight](https://user-images.githubusercontent.com/43250183/45588467-8ca6e600-b915-11e8-8a51-d87b0b9accf5.png)
![plushdark](https://user-images.githubusercontent.com/43250183/45588468-8d3f7c80-b915-11e8-992b-fd9f48383f04.png)

**Comment by Chrissenpai** [comment]
The quetzal should be near the window, not on the table

**Comment by CharlyIsHungry** [comment]
She said that she wants a plush, not a real one.

**Comment by Chrissenpai** [comment]
oh right, but still she'll put on the window so she could be guiltless that is not captive

**Comment by CharlyIsHungry** [comment]
That would be cute ^^ Maybe I'll draw it like that too

**Comment by Chrissenpai** [comment]
also make the eyes more like pikachu like, its cuter that way

**Comment by CharlyIsHungry** [comment]
Like this ?

![plushlight](https://user-images.githubusercontent.com/43250183/45589291-73a53180-b923-11e8-949f-0eec5342a909.png)
![plushdark](https://user-images.githubusercontent.com/43250183/45589292-73a53180-b923-11e8-8d16-f2bc236b4736.png)

**Comment by Chrissenpai** [comment]
The quetzal and a pikachu has the eye totaly black with only a dot of reflection

**Comment by ThePotatoGuy** [comment]
thanks for the art, but we decided to go with the ones our artists already made.
