### ISSUE TITLE
Monika MIA with hotfix

### ISSUE THREAD

**Issue by had2ask** [Monika-After-Story/MonikaModDev#2402]
I was using the unstable version, and monika was missing when I chose the "Take her somewhere" goodbye option. I've waited it out for the hotfix, but it still isn't working and she is missing. My log folder is empty as well

**Comment by ThePotatoGuy** [comment]
See [this](https://github.com/Monika-After-Story/MonikaModDev/issues/2351#issuecomment-420834282)
