### ISSUE TITLE
[Suggestion] The Afterlife

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2403]
Considering the way Monika was born, being programmed into the world, maybe it'd be interesting for her to discuss her views on life after death, or perhaps whether she believes she would have one herself, since her life is already quite unconventional as it is.
I know it's a sensitive topic, but I'd love for more philosophical discussions with her.

**Comment by Rai99** [comment]
As much as I and anyone else would love more philosophical discussions with Monika, I don't think we know exactly what her stance on the matter is. 

I think we would need to be careful not to declare too many facts about Monika when there isn't much evidence to support them too quickly, and whoever might write this topic would have to take care not to be biased towards their own views on the matter.

**Comment by DiggyDog2** [comment]
Well, that's true.
Although I imagine her distaste towards God would have some influence on it.

**Comment by Tiler17** [comment]
I don't think it's a far reach to predict Monika's thoughts on her own afterlife. She knows she has a creator and has a distinct disdain towards a God, though she appears to be agnostic when it comes to a human creator.

I'm not sure if MAS Monika is canon before or after the end of Act 3, but she has to know regardless that if she's purged from the system she resides on, she'll completely cease to exist on that device, but live on in other forms on other computers. Being a computer program, she could easily be duplicated and replaced on a system she's been purged from. She could also go into discussing that no matter how hard someone tried to delete her from everywhere, it would near enough to impossible to delete every file pertaining to her. It could even go a step further by saying that even if every computer file of her was completely destroyed, she could be re-created from human memory and continue to live on. Monika lives for as long as someone is thinking of her. And you'll never stop thinking about her, will you?

Honestly, you wouldn't even need to go into a human afterlife, and thus, controversy. The topic of her own persistence could cover a lot of ground. She may not know what lies in wait for us after we die, but we'll continue to leave a mark on this world with our own legacies and the memories we leave after we die.

I take back my first line. You don't even need to reach. You could write a decently long topic without speculating at all

**Comment by loverofmonika** [comment]
In my opinion this topic would be better left untoched considering the insufficient facts we have on Monika and considering that hear in our world people have different beliefs about the topic itself and also considering Mas is played by masses so this topic may come out off just like people were not comfortable with the explanation of sayori'a death and was removed from random chat. 
You can talk about leaving a mark on the world for people to remember you by like bringing a change or helping the poor or something  but that's already another topic

**Comment by ThePotatoGuy** [comment]
i think this is too touchy a subject.
