### ISSUE TITLE
[Bug] - 200 affection gain out of nowhere

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2405]
So, I told Monika I was going to bed, but before actually going, I opened the DEV version, then went back to the normal version, and noticed I had gained 200 affection. Here's the chunk of the file that shows the 200 affection gain:

[2018-09-16 03:38:58.528000]: LOAD | 978.0 | 978.0 -> 978.0
[2018-09-16 03:38:58.528000]: !BYPASS! | 0 | 200 | 978.0 -> 1178.0
[2018-09-16 03:38:58.528000]: SAVE | 1178.0 | 1178.0 -> 1178.0

Is there any way I can delete that massive gain?

**Comment by ThePotatoGuy** [comment]
Not a bug, what happened was your dev version was older than 084, and when you went back to the newest version, the version_number was off and so all the migration scripts ran. 

You could just delete the gain manually in dev version, and with some buffer for the 200 gain.

**Comment by ThePotatoGuy** [comment]
`persistent._mas_affection["affection"]`
