### ISSUE TITLE
[Suggestion] Explaining the meaning of your name

### ISSUE THREAD

**Issue by AlenNez** [Monika-After-Story/MonikaModDev#2411]
In order to add more immersion, I think there could be a little side-project people could contribute towards. As we all know, there are over 5,000 different first names in use in the United States, and even more so when you look into places like the European region of the world. What I propose is this: 
Similar to how Monika mentions her own name, its meaning in Latin and Greek, I think instead of just saying "[player] is a lovely name, too.", she could have unique responses depending on the name you currently have for yourself. For example, simple names like Richard, Robert, and Alen could have unique responses, as John means "strong in rule", Robert means "famed, bright, or shining", and "Alen" means "fair or handsome". This of course sounds like a huge project, but it seems like a time-killer if some contributors have time to spare and want something to do. I don't expect this to get accepted, or even considered as it sounds far too large of an idea on paper, but I'm just throwing it out there because this seems like a fun idea. And the fact my irl name is Alen.

**Comment by MrDevilzMan** [comment]
Other parts of continent needs to be taken into account as well, such as Asia and Africa and all the other parts of the world. I think that instead of having a unique response of a specific name, we could make her ask about the meaning of our name without having to list all the available names.

**Comment by Thimeo** [comment]
I think that's quite a handsome project Alen (sorry for this one). For real, I think this is a great idea that would bring a fair amount of immersion to the game, this would require "only" 1 or 2 sentences per name and I'm sure that there is already a dictionary that translate the meaning of all the name in the world. I quite sure that if the we ask to the contributors something like : "write 1-2 sentences with the meaning of your name (etymologically) and the meaning of the name of your sibling(s)" we would already covered a big part of it in a fair amount of time. We could also said that only the 100 or 1000 most common names will be "translated" the others would have Monika say something like "Whoa that's a name I didn't know" "It's really unique, very suitable for you my love".

**Comment by multimokia** [comment]
So. Uh, there's actually more than thousands of even simple names, let's also add the idea that some names are unisex. Which means thousands of conditions to write up, separate conditions for unisex names (possibly), and then dialogue on top of that. This is straight up not feasible considering there's so many names that could be missed. Let's also add on that we'd have to actually *research* the names too? It's not like people have all the time in the world, you know.

**Comment by AlenNez** [comment]
As I said, this wouldn't be a project you'd be working on 24/7, I stated above that it could be contributed to when people feel like it. Missing out on a name doesn't matter all too much, it's just one less name that someone else could do for you.

**Comment by multimokia** [comment]
I get what you mean, but then you also get into the territory of overlapping names. Since the file would get so big, and people might want to do a name other than their own, they might not catch that there's already a reaction for which makes their bit kinda useless.

**Comment by Tiler17** [comment]
Not to mention that there's already a backlog of stuff that's yet to be properly added. Writing the dialogue is the smallest and easiest part of adding new content, so it would still fall on, at most, I'd say 10-20 people to write thousands upon thousands of dialogues for names. Only a fraction of able and willing contributors are able to review and test a new contribution to allow it to be added, and there are still a limited number of people who can properly merge new content into the game.

That doesn't even get into the concern people will have about being left out. You may only want to add the thousand most common names, but that wouldn't be good enough. For instance, Alen, your name would not make the cut, unless you added it yourself. But even if you did, I can assure you that the vast majority of those left out wouldn't know how to write it in, or even that they could.

I don't think it's a bad idea as content, it's just so overwhelmingly unreasonable that I can't see a day it'd ever be added
