### ISSUE TITLE
[Suggestion] - Spelling consistency

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2414]
I've noticed that, in most topics, Monika says "okay", as opposed to "ok", but she sometimes opts for the latter (namely, in the "Happiness" and "Do you like fast food?" topics). Similarly, in the "Waifus" topic, she contracts "because" as "'cause", but in the "Happy Just To Dance With You" song, she contracts it as "cos" (not to mention most of the time she simply doesn't contract "because" at all). I think there should be consistency across Monika's topics regarding spelling.

**Comment by AgentZephyr** [comment]
I've also noticed her use "Aww" and "Awe" in different dialogues

**Comment by aldoram5** [comment]
Thanks for reporting this, if you guys could list all the topics with the mentioned inconsistencies that'd be really helpful!

**Comment by MisterSimple** [comment]
Alright, I've checked the code, and here are the topics with inconsistencies:

**Topics that say "ok" instead of "okay":**
- Happiness
- Do you like fast food?
- Can you change my name? (also the prefferedname event, as they essentially have the same wording)
- I'll be going away for a while - A week

As for the "'cause", "cos" inconsistency, there's really only 1 topic for each contraction ("Waifus" and "Happy Just To Dance With You", respectively). However, in DDLC, Monika at one point says "Well...that's 'cause I have to sound confident.", so that leaves "'cause" as the correct way of contracting "because".

As for "aww" and "awe", I couldn't really find any dialogue where Monika said "awe", though I did find that she sometimes said "aw", and sometimes "aww". Are we planning on keeping the amount of "w"s consistent, as well? If so, let me know, so I can go back and list the topics where these inconsistencies are present, as well.

**Comment by MisterSimple** [comment]
That's right, perhaps different situations call for different spellings, but, if we plan to intentionally alternate between spellings depending on the dialogue, we'd have to go through every instance of "ok" and "okay" and assess whether they're fitting or should be replaced with the other variation. Same goes for "aw" and "aww".

**Comment by Rai99** [comment]
It'll probably happen over time and people can keep this in mind for any future topics. 

Some people do in fact go through everything for little things such as capitalization, punctuation, wording, etc.

**Comment by MisterSimple** [comment]
Yeah, that's true. I'd like to hear what others have to say about this, and settle how it should be handled.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
