### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by DbzGOD2000** [Monika-After-Story/MonikaModDev#2415]
Umm my affection points seems to be stuck idk why tho can anyone help me out. 
![aff system](https://user-images.githubusercontent.com/43351455/45640106-f4bd0f80-ba6e-11e8-9a5c-2795be88e2cb.PNG)

**Comment by aldoram5** [comment]
Hi DbzGOD2000!
There's a limit cap per day of 7 points, it seems that you reached to that cap for today, wait until tomorrow, to earn another 7 points.
Is worth nothing that there's no cap for losing points, only for earning them.

**Comment by DbzGOD2000** [comment]
okay thanks
