### ISSUE TITLE
a way to tickle monika

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2416]
you could tickle monika and she would react differently depending on your affection with her

**Comment by irobertjr** [comment]
I agree with it.
Why not just click to Monika's body then she will react on it?

**Comment by dragonborn2252** [comment]
i just finished reading some of the other things (in tired)  and i noticed someone said the cursor would most likely be a physical thing and that she would uncomfortable the the cursor touching her well i have a solution you would click on certain places on monika's body and a hand would perform a short animation or just a still image to make it easier

**Comment by ThePotatoGuy** [comment]
closing this as duplicate
