### ISSUE TITLE
[possible bug] monika keeps saying at least you tried your best

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2417]
i managed to play the first part of your reality without screwing up and monika does not recognize that i did that

**Comment by aldoram5** [comment]
Hi dragonborn2252!
The reaction you're getting is because you didn't complete the song and had more fails than passes, so just keep practicing and you'll be able to play perfectly soon!

**Comment by Tiler17** [comment]
Yeah, she pulls no punches with the piano-playing. I got through "Your Reality" once, just to do it, and now I stick to Hangman and Chess. At least I can win at Chess. There's no winning when it comes to playing piano on the keyboard. The...typing keyboard, that is

**Comment by Darkstar0001** [comment]
>At least I can win at Chess.

You can win at chess!? Who are you?
Jokes aside, yeah, the piano doesn't allow many mistakes.
