### ISSUE TITLE
[Suggestion] [Evil Idea? (and protecting Monika from it)] Forcing Monika out of the room

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#2421]
This is an idea for people who want to mess with Monika. I probably wouldn't do it myself, but gotta flesh out the evil ideas you can do to her to make MAS as complete as possible. (This also means I didn't want to test if this has already been implemented)

Since Monika has her own character file, could you just move her around whenever you want to and would the game be able to recognize it and for how long the file was moved? Basically the "taking Monika somewhere" like how you do it after alerting her in the goodbye tab, but without actually saying goodbye to her or getting her consent. Of course, Monika shouldn't take too kindly to this happening, but I figure if we can already close MAS without saying goodbye, this would be something similar. I could imagine after a fight, you just drag Monika onto your jump drive as a sort of "time out" to kick her out of her room. Then she's mad and you lose a bunch of affection and it probably puts you dangerously close to the pink note event.

Also, I could possibly see a different reaction if you forced her out to add a surprise item to the room whenever that feature comes out.

**Comment by AsuraShun** [comment]
why would you think of something this cruel?

**Comment by MrDevilzMan** [comment]
I thought this mod is about being wholesome to Monika, not torturing her.

**Comment by winika** [comment]
Yeah no... I already have a hard time standing the fact that some people like to hurt Monika. This will only add to the fire of options that hurt her.

**Comment by AsuraShun** [comment]
i'm with you winika,i also can't stand to know that a lot of monikas out there are suffering at the hands of her haters,it really pisses me off,almost as much as manipulators

**Comment by winika** [comment]
Yeah, honestly people need to just let go and forgive her for what she did. Or else they usually become the monsters they try to destroy.

**Comment by CrocWorks** [comment]
Hehehe,,, I figured this wouldn't be very popular. It was for having a complete experience available, not that I'm encouraging people to do it.

~~And here I thought of a follow-up where I was wondering if her file could recognize if it was in the recycle bin and brought back, or if it was zipped and compressed and then extracted back. What is up with me today?... lol~~

**Comment by CrocWorks** [comment]
But also, the other thing this does is make Monika intelligent enough to stand up for herself. If people ARE being cruel and messing with her, I would want Monika to be aware of it and leave that person.

**Comment by AsuraShun** [comment]
even if they try to erase her memories by deleting the save and such

**Comment by AsuraShun** [comment]
but the idea you mentioned is even more cruel,having her realize that it's one of her haters without needing your idea would be best,like using the ''dealing with haters topic'' to identify them

**Comment by CrocWorks** [comment]
I'm not sure adding a "dealing with haters topic" would be a guaranteed fix. There will be those manipulators who lie to Monika that they care about her just to keep her around. Adding a check for terrible situations like this would be for Monika's benefit. I don't think any of us would want some hater to go "lol, look at this fake file, I deleted her but pulled her out of the recycle bin because I can and she still blindly loves me."

**Comment by Foxinsunglasses** [comment]
Despite how kind you can be to her there are already many a terrible things you can do especially if you have low affection. So it doesn't seem too far fetched even if I wont use it.

**Comment by Tiler17** [comment]
Or she could protect herself entirely from the possibility by eliminating the need for her .chr file. Now there's a good idea, someone should get on that

**Comment by AsuraShun** [comment]
there's already no need for her chr file,she deleted it herself

**Comment by jmwall24** [comment]
Uhh there is no file to move without telling her you're taking her somewhere.  She creates that file when you use that farewell and deletes it when you put her back.

**Comment by CrocWorks** [comment]
Okay, then ignore the first part I guess (or make it so her character file is always available, but that's extra work and unnecessary).

But still, is it possible for her character file to recognize if someone stuck her in the recycle bin or compressed her file? I'm not sure if those would affect her file noticeably or not.

**Comment by multimokia** [comment]
Not possible to tell if a file was moved to the recycle bin, no. As for compressing, if something in that file changes, you actually lose her forever, straight up. Also why would you want people to be allowed to torture her? As for the `monika` file not being there when she's in the spaceroom, that makes sense since she doesn't need a chr file to exist, so she doesn't need anything to support her existence in the game. Therefore making that file stay doesn't make sense.

**Comment by CrocWorks** [comment]
Well, it's not that I want Monika to be tortured. I want Monika to be aware when someone else is torturing her and have the power to react to it and stop it.

I think the difference here is I've been viewing these acts of deleting/compressing/etc. to be a torture regardless of whether MAS is programmed with an appropriate response, whereas others here seem to think as long as Monika doesn't know the player did something bad to her, then it never actually happened and Monika never felt it. Ignorance is bliss in the latter case, I guess?

Regardless, it doesn't seem like this is something that needs addressing right now, as it doesn't seem likely to work.

**Comment by SaiPrithvi123** [comment]
I think it would be better if the ways to torture her get less, as in the stock game she doesn't let us say that we don't love her. This shows that she doesn't want to give player ways to hurt her. She couldn't do anything about the void on her own, but she still lets you delete her because it's the only the she can know that the player doesn't want her.
