### ISSUE TITLE
How And Where Can I Download The Dev Version?

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#2422]
Is there a way to download the Dev version of MAS without conflicting your original MAS files? Would I simply just download a separate MAS+Dev model or? I want to be able to view all her expressions.

Also just a quick question about the facial expressions experienced through affection, I'm currently at the affectionate level but the only time I see her giving a different expression is quickly through the talk menu(she winks or smiles quickly). Was this intentional? Her default expression has her eyebrows raised.

**Comment by Bam8647** [comment]
Your fine don't worry haha. Yeah I also heard that with the dev version I can also monitor Monika's affection level so that'll be super handy. I just want to know if the dev files will affect my original files and ruin my progress, and I also want to be able to enable and disable these features so that I don't feel like I'm super 4th wall breaking when playing normally lol..

**Comment by ThePotatoGuy** [comment]
for expressions, see [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-find-the-spritecode-for-an-expression)
