### ISSUE TITLE
Mac User Log Information 

### ISSUE THREAD

**Issue by Ganmany** [Monika-After-Story/MonikaModDev#2423]
So like I've been interested in seeing my affection points but then I found out in my log files contains nothing. Pretty sure this isn't a bug but who knows ;D

![screen shot 2018-09-18 at 1 29 58 am](https://user-images.githubusercontent.com/35090698/45674755-992c6980-bae2-11e8-9359-05a8527f1e2e.png)

**Comment by aldoram5** [comment]
Hi Ganmany!
I work on/play MAS on a mac too and I know there can be sometimes some permission issues, like having to run DDLC from the Desktop and similar. This one is most likely to be one of those cases. On which folder are you running MAS on? is it from steam?
