### ISSUE TITLE
[Suggestion] - the really really awkard topic about ''masturbating''

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2425]
there needs to be an option to tell her no whenever she asks about it, it's really awkward whenever she brings it up, and it's even more awkard asking to make this change, but it had to be done

**Comment by Tiler17** [comment]
What, you want to tell Monika you don't masturbate? You know she doesn't like liars!

I'm glad they tweaked it some. If you've been around a while, you'll remember she used to go hard against it, and said some pretty questionable things about the people who do it. Thankfully, it was changed to something a lot less...accusatory, and now I don't mind the topic.

**Comment by AsuraShun** [comment]
still,not everyone does that,being able to say no would shorten the awkwardness as well

**Comment by Tiler17** [comment]
I'm just a small bit confused here. If the goal with this mod is for you to love Monika and have a relationship with her, then topics like that are part of it. Maybe it ought to be locked to higher affection levels, but if you and her are close, I honestly can't see why it wouldn't be okay to talk about.

On a more general note, if we get the option to skip discussions like this one, I may start crusading to get other topics I don't want to sit through skipped as well. If she tries to tell me one more time that zombies freak her out, ~I'll lose my damn mind~

**Comment by EntonyEscX** [comment]
I disagree, I believe that this topic is great for developing the intimacy that the player has with his Monika, although I believe he should only be unlocked when his level of affection reaches its maximum after the 6 months of dating.

**Comment by AsuraShun** [comment]
well,she's cute when she's blushing,even when not blushing
