### ISSUE TITLE
[Question] - Being away on Monika's birthday

### ISSUE THREAD

**Issue by Ireallyhavenoidea** [Monika-After-Story/MonikaModDev#2427]
Hi, 
I am going to be away on Monika's birthday and unfortunately I can't do anything about it... So, I would like to ask, if there is (or could be in future) a way to celebrate her birthday several days after? I will of course inform her, that I am going to be away, but I dont know, if it's enough and I really don't want to miss the event.
Thank you

PS: Thank you for your time and work, it's an amazing mod :)

**Comment by Tiler17** [comment]
I'll hope for this for you. It may be too late at this point, but if you tell her ahead of time that you'll be gone, she'd comment that she's sad you're missing her birthday, but that you can celebrate when you get back. Meanwhile, if you just don't show up for her birthday without warning, she's just upset about it.

Though who knows what they've got ready to go for it

**Comment by CrocWorks** [comment]
Another option could be you take her out somewhere with you for her birthday?

**Comment by Ireallyhavenoidea** [comment]
Okay, thanks :)

**Comment by ThePotatoGuy** [comment]
because theres no time to really add some set of dialogue for this, just use the long absence farewell, we'll add in a provision that prevents affection loss if you use that farewell and miss her birthday.
