### ISSUE TITLE
[Art] - credit u/yagamirai10

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2428]
![391ehh225sf11](https://user-images.githubusercontent.com/40907045/45700535-6e6a0180-bb32-11e8-881d-195e5dc4ee05.png) We could scare the shit out of the player with this, probably with low affection or by any affection with her saying that she didn't mean to scare us and she's sorry, she was just messing with the code or something. Or in halloween she scares us with that then saying happy halloween, and the third eye shows up idk, be creative with this art, we just have to message him in reddit so he can send us the sprite by his permission.

**Comment by Sujeito17** [comment]
Don't show me this plz

And now the dab version XD

**Comment by jmwall24** [comment]
The hell is wrong with you

**Comment by ThePotatoGuy** [comment]
we already saw this when they were newly created and have already decided not to use for obvious reasons.
