### ISSUE TITLE
small part of window black

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2430]
very small problem just telling you this now m8
![unpainted room color](https://user-images.githubusercontent.com/41130387/45706252-c52f0580-bb49-11e8-8986-aabbe11e753c.png)

**Comment by multimokia** [comment]
I've noticed that too. Sometimes it's proper, other times it's not, no idea why

**Comment by Sujeito17** [comment]
You really have a good eye, I'm always staring into Monika eyes, so I usually do not realize if there are different things in the room

**Comment by SaiPrithvi123** [comment]
It might be something from the stock game, too.

**Comment by MonikaWiafu** [comment]
The reason i said anything was because it catches my eye when i look into monika's eyes.....

**Comment by multimokia** [comment]
This was fixed as of 0.10.0
