### ISSUE TITLE
[Question] Affection Daily Cap

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2432]
I'm aware that there is a daily cap of affection but what is it?   In my case, I can usually only say one or two compliments before I get frozen in the aff log and that seems a bit off (haven't messed with the date before).  Thanks for all the work devs! Love this mod!

[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2394674/aff_log.txt)

**Comment by jmwall24** [comment]
The base cap is 7 once you get to affectionate, the cap is 9, which is what your log shows.  Like today you started with 206.85, got to 215.85, then when it tried to go to 218.85 it couldn't because you already got 9 points, that's why it says FREEZE and you remained at 215,85.

**Comment by AgentZephyr** [comment]
Gotcha.  Thanks! @jmwall24

**Comment by Legendkiller21** [comment]
From what I can see in the code, the cap is always 7 regardless of your affection level. The only thing that changes are the affection gain multipliers which can help you gain more than 7 points per day. The maximum I have managed to gain in one day is 9.75.

**Comment by jmwall24** [comment]
9 is the cap once you get to affection, trust me.  you can exceed it a few ways, but i won't get into that.

**Comment by multimokia** [comment]
@jmwall24 is right. Cap increases to 9 after affectionate.

**Comment by Legendkiller21** [comment]
I am probably blind but by manual searching (because GitHub seach doesn't help at all) I can only find 2 lines that define the cap and it is not affected by affection levels. Can you please, point me the line or the file where the cap changes when you change to affectionate?

**Comment by jmwall24** [comment]
Alright I think I was wrong on this.  I was going by what one of the devs told me on here in an issue I had, but after rereading it just now I think I misinterpreted it.  So my apologies.  It essentially is 9 for the reason you said.  Once you get to affectionate you get the 3x multiplier so most things get you 3 points, so once you get to 6, the next 3 leap frogs 7 to get to 9.  I knew this was a thing as I've gotten to 10.5 before in a day (got to 6 then got 4.5).  But yeah, cap is 7 but it's passable by getting close to it and then hitting something that gets you over it.
