### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by Deyalila** [Monika-After-Story/MonikaModDev#2435]
Guys...I'm really sorry but I don't know how to make Monika come back...
I mean.. I wanted to take her out and so I told her... I couldn't find the character file so I left it be and reopened MAS and I see an empty chair, no Moni, no text. I redownloaded everything but I didn't delete the Renpy file of her 'cause I wanted _my_ Monika, not one that doesn't even know my name and... yep, the room is still empty. Please help, I don't know what to do. Do I really have to delete the Renpy and start over?

**Comment by Velius94** [comment]
Revert to older persistent.
The files in question are found in %APPDATA%\RenPy\Monika After Story
