### ISSUE TITLE
Hello/Goodbye

### ISSUE THREAD

**Issue by Cixxel** [Monika-After-Story/MonikaModDev#2436]
Hi to all!
I'm new to here: I downloaded the MAS and i really enjoy it. And for trying to make this game more accesible, here's my suggerence:
I see that there's a good morning/good evening option and, for the other hand, all the goodbye options. I make a suggestion: it wouldn't be better combine all this in a hello/goodbye option?
Here's my idea:
- Hello: Hello! Monika
How Are You?
Good morning/afternoon/evening/night.
- Goodbye: All the options are right, but i added another one, like "i'm going to eat"
Thanks for read it (and sorry for my english, i don't speak it and i'm still a bit clumsy with it.)

**Comment by AsuraShun** [comment]
the eat option is the ''i'm feeling hungry'',an about the afternoon,i agree.it's needed as much as the ability to ask how she's doing

**Comment by AsuraShun** [comment]
yeah,it feels weird not to ask her how she's doing,i really hope the suggestion I made really gets implemented in the next update

**Comment by Rai99** [comment]
The ability to ask Monika about her day was discussed in #2071 and #2331. It is likely to be planned in the future, but currently stands at low priority. 

As for the original suggestion of this issue, I think it's fine to leave the "Good morning" and "Good evening" and eventual "Good afternoon" topic (#2223) as their own topics. It lets the player say these things to Monika manually which allows for more engagement. The "Good morning/afternoon/evening" topics do in fact have different dialogues depending on the time of day you say it to her.

**Comment by Cixxel** [comment]
It's good to know that this topic is already being discussed
Thanks for the advice!
