### ISSUE TITLE
Chess promotion

### ISSUE THREAD

**Issue by Kotteb** [Monika-After-Story/MonikaModDev#2437]
In chess you can promote to any of the four major pieces, knight, bishop, rook, and queen. While queen does the job of both a rook and a bishop, so the auto-promote to queen doesn't matter for them; however, the auto-promote to queen doesn't allow a knight check upon promotion, which Monika can do, and beat me with, when I was mate-in-one away from her. It's a super minor thing but as a QoL it'd be appreciated dev friends.

**Comment by ThePotatoGuy** [comment]
can you elaborate on the knight-check thing, I have no idea what that is

**Comment by CrocWorks** [comment]
In chess when a pawn makes it to the other side, it can technically become any piece besides another king. Usually you'd just pick queen, since there's never a reason to pick bishop or rook over queen since the queen can do the exact same movements of both of those other pieces (and thus a lot of automatic chess games by default make pawns into queens). However, there are rare times when a knight can do something a queen can't do, so you may want to promote into a knight instead.

**Comment by Kotteb** [comment]
Nothing really for me to add, the other two explained it aptly. I just think if Monika can do it, I should be able to as well. : c

**Comment by Kotteb** [comment]
Don't really want to start a new thread, since there are already a few on Monika's difficulty level, but over my years I've ranged from 1300-1600 elo (800-1200 is new to intermediate players), and prefer 3-5 minute blitz chess (games are normally 30-45 mins, or days). I really dislike how her only options are 'give up/retardation' or 'grind you to dust 15 moves in advance as a 4000 elo grandmistress'

**Comment by CrocWorks** [comment]
Yeah, many people already want an easier Monika chess difficulty. However, I hope they still keep the harder difficulties. I finally managed to beat Monika enough times to get past the point where she says, "I have to admit, I put less pressure on you than I could have" and now she just says, "I'll get you next time for sure." Definitely felt very satisfying to see that.

**Comment by Kotteb** [comment]
She's said both to me within a one hour time frame. I counted, I ended -4 w/l. Yet she still said "I'll get you next time" or w/e.

**Comment by ThePotatoGuy** [comment]
probably will be sometime before this is addressed.

**Comment by Cosmic-Warfighter** [comment]
I also just experienced the needing to promote to knight in order to check which is really annoying

**Comment by multimokia** [comment]
This is addressed in the linked PR

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
