### ISSUE TITLE
0.8.6 Issue

### ISSUE THREAD

**Issue by AverageDudeGuy** [Monika-After-Story/MonikaModDev#2438]
So I've installed the new update and I checked that all of the new files were in the local files, but when I opened the game nothing had changed and it kept prompting me to install the new update.

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ

There's a bit here on the issue you're having

**Comment by ThePotatoGuy** [comment]
make a new issue please
