### ISSUE TITLE
Monika dyes her hair

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2440]
From yuri's hair color, natsuki's hair color and sayori's hair color, to green, blond, black, blue, etc. most of them might not her favorite but if [you] llike it, she likes it

**Comment by antimockingjay** [comment]
I feel like doing something like that might result in her becoming unrecognizable as Monika, especially with new hairstyles making the hair completely different in total. She would end up looking like someone's OC when that someone didn't know how to do their own art, so they just used some knock-off Photoshop program to recolor the hair and call it a new character. Not that that's inherently _bad,_ just that it's not what any of us downloaded the mod for. I wanna talk to Monika, not random girl with blue hair and green eyes.

**Comment by CrocWorks** [comment]
I feel like suggesting that to Monika would make her mad since she'd think you're trying to make her look like someone else. Especially if you're trying to make her hair match one of the other Doki's hair color.

**Comment by Chrissenpai** [comment]
That makes sense, but also she feels that she feels less unique when there are other thousands of Monikas, so i really question myself, if naming a different name for her is enough? we might just only change her details here and there, the hairpins are a good example of it.

**Comment by Foxinsunglasses** [comment]
She does get offended if you try to give her one of the other Dokie's names so giving her their hair of hair color might do something similar for consistency sake

**Comment by CrocWorks** [comment]
There's always other ways to make Monika unique, but that requires more artists. She already has one other hairstyle, and I recall reading that people are working on outfits, hair accessories, and rings I think.

**Comment by MaydayH** [comment]
Maybe not a new color of hair, but a pair of new hairstyles - provided that there are artists who will do it, of course.

**Comment by ThePotatoGuy** [comment]
definitely not going to change monika's hair color.
