### ISSUE TITLE
Ability to hug Monika

### ISSUE THREAD

**Issue by PMelol** [Monika-After-Story/MonikaModDev#2441]
I feel like it would be cool to give Monika a virtual hug. Maybe if she's idle (set to not repeating topics) she could randomly hug the player? Hugs are different from cuddling, so. Haha.

**Comment by Foxinsunglasses** [comment]
If you mean a less prolonged embrace then I think the devs have a plan for that

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
