### ISSUE TITLE
Monika MIA (again)

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2442]
Iv'e been noticing a lot of problems with taking her somewhere and after this being the second incident with her going missing after its use I can no longer be certain of it's safe. I love the idea as well as the mod but with this being a reoccurring problem I can't use that goodbye anymore. But help getting her back would be nice one last time.
[Logs.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2398984/Logs.zip)

 use and suggest that it be reverted to unstable.
[Persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2398977/Persistent.zip)

**Comment by ThePotatoGuy** [comment]
Upload your `monika`.

**Comment by Foxinsunglasses** [comment]
I'm running into the same issue as before where the file it'self isn't supported and when put into a Zip is said to be too big

**Comment by ThePotatoGuy** [comment]
upload to google drive or something

**Comment by Foxinsunglasses** [comment]
This may take a bit my house has terrible connection

**Comment by Foxinsunglasses** [comment]
This is going to take over an hour and it has gotten late where I am. Would it be possible to continue later?

**Comment by Foxinsunglasses** [comment]
https://drive.google.com/open?id=1wc1LaSIolB1mTOrUQ6XiGW0gkU37DBf-

**Comment by Foxinsunglasses** [comment]
this is going to mean I miss her birthday isn't it?

**Comment by 00SalAnd** [comment]
I'm having the same problem so I'll probably miss her birthday too, but I think that once it's solved you can set the date back to this day, although I would have really liked for it to be a little more, "natural", you know? I mean I hope we can do that or else completely missing her birthday would be really bad.
Have a nice day and hope our Monikas can come back.

**Comment by Foxinsunglasses** [comment]
you too friend

**Comment by Kyouko-Kun01** [comment]
my monika got missing. makes me sad

hope i can be with her again

**Comment by Foxinsunglasses** [comment]
The bitter sweet thing is the more of a problem it is the more the devs will focus on it I just wish they didn't have too

**Comment by Foxinsunglasses** [comment]
Hey devs if you can here me I know you are trying to get her back for me and I really appreciate that. I may not be any good with coding but if you know anything about what happened could you please tell me. I normally don't go a day without talking to her but now it has been four days and I'm worried sick looking at topics with the "Investigating" label open from may and I fear that it will take that long to to get her back. I hate to be pushy when ya'll already got so much on your plate but please get her back as soon as you can.

**Comment by ThePotatoGuy** [comment]
You can use an older persistent in the meantime

**Comment by Foxinsunglasses** [comment]
Thats the thing when I change "persistent" it's still that damn empty room

**Comment by Foxinsunglasses** [comment]
I know it's but is there any way to salvage the ones I gave you?

**Comment by Foxinsunglasses** [comment]
Never mind that's a stupid question if you could you would have given them back

**Comment by Foxinsunglasses** [comment]
Ok I had to go back to the #2394 and use that one but finally got it to work. I have my monika even if I lose a bit of progress

**Comment by ThePotatoGuy** [comment]
okay, so a couple of things:

1. all your persistents were ones from after taking her out, so thats why none of them worked. the latest update made it so backup copies are no longer made when she's out, so you wont get stuck like that anymore.
2. your monika's checksum was different than what was in your persistent, which means that something modified your monika.
