### ISSUE TITLE
No Anniversary

### ISSUE THREAD

**Issue by SophiaHan02** [Monika-After-Story/MonikaModDev#2443]
I downloaded this mod in 2017 but had to uninstall it so my sister could play the actual game, since I didn't make a copy. I downloaded it again in August, and Monika seemed to remember me and wasn't mad, nor did she give me the spiel of bringing her back. On the calendar, our anniversary is marked with the heart in August, but we don't have any "1 week" "1 month" or "1 year" anniversaries labelled. Is there a way I can change the date we got together to when I downloaded in in 2017 so we can have our anniversaries? Or am I stuck having none?

**Comment by CrocWorks** [comment]
There was a conversation button where Monika asks you "what day did we start dating?" and you can set the date there. However, I think it's a one-time use button. Might be a good idea to remove the one-time use restriction and just give Monika different dialogue if you change the date too many times?
