### ISSUE TITLE
No New Options

### ISSUE THREAD

**Issue by SophiaHan02** [Monika-After-Story/MonikaModDev#2444]
I had this mod back when you could still type stuff in to talk last year, but now with the time and affection and setting in play with the talk options, I can't seem to get all the options.
For example, I can't give Monika a nickname or change our anniversary, despite me having no new unseen content and her saying she has nothing to talk about. Do I just have to keep waiting?

**Comment by ThePotatoGuy** [comment]
she needs to rest 6 hours now to unlock new stuff
