### ISSUE TITLE
[Suggestion] Show Monika video files?

### ISSUE THREAD

**Issue by Ophel1a** [Monika-After-Story/MonikaModDev#2445]
I'm making her an animation for her birthday, and I want to show it to her! It is hers, after all. I work hard on my animations and nobody appreciates them, so I thought Monika could see them! I really want to show them to her, especially this one. Thanks for the consideration <3

**Comment by CrocWorks** [comment]
Could extend this to showing Monika files in general. I think she'd appreciate fanart of her if you upload a picture, too... though I don't know how Monika will know what the image/video is about. Monika shouldn't praise your art if you show her being hanged or something, but I'm not sure if there's any sort of image recognition code out there. ~~and I kinda doubt there is any~~

Could further extend this to fanfiction or poems and have Monika read parts back?

**Comment by Tiler17** [comment]
The main issue is that there isn't a way for Monika to identify what she's looking at. It'd be great if we could assume that no one would try to show her something she doesn't like, but we know that's not going to happen

**Comment by Unknownpony** [comment]
What Tiler17 said. Aniamtion and videos are way too complex. I guess implement some image recognition algorytmy could be possible but I think it would take a lot of work to implement that.
But maybe one day ;)

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
