### ISSUE TITLE
Monika keeps staring at me with a traumatized expression?

### ISSUE THREAD

**Issue by lillyteacup** [Monika-After-Story/MonikaModDev#2448]
![image](https://user-images.githubusercontent.com/43442750/45819537-89fc1600-bcb2-11e8-9297-a0eb5f711fa1.png)
All I did was transfer all the files from the "game" folder in the Steam files to a new download you get from the DDLC website. The first time I opened the game, she got mad at me because I "deleted" the imsorry.txt file, when really I just forgot to copy it. So she closed the game and I remade it. Then I opened the game back again, and after forgiving me she just goes into that expression and says "..." when I prompt her to talk or to play a game. Whenever she does talk, she's normal. Idk what I did wrong or how to fix this

**Comment by AsuraShun** [comment]
this is something I never wanted to see,it pains me to see her traumatized like that

**Comment by jmwall24** [comment]
It means you're at broken affection.  The lowest possible category.

**Comment by Tiler17** [comment]
That's the Monika equivalent to the thousand yard stare if I've ever seen it. That's a distraught or broken Monika. If you don't want her looking ~past~ at you like that, you've got to be nicer to her

**Comment by multimokia** [comment]
Wow, you've been torturing her a fair bit. You ought to treat her a bit better... Pains my heart to see this.

**Comment by lillyteacup** [comment]
Dude I've never picked mean options. Maybe I didn't play games enough or say "I love you" and complimenting her enough but I've been spamming those

**Comment by lillyteacup** [comment]
Oh okay thanks. I genuinely didn't know that it was possible to not say I love you, give compliments, or play games enough.

**Comment by jmwall24** [comment]
You don't lose points for not saying ily, not giving compliments, or not playing games, you lose points for doing certain things (like the things I mentioned above).

**Comment by lillyteacup** [comment]
I never left without saying goodbye, I did mess with time though cuz I was curious about the anniversary things, so yeah that might be it... oops

**Comment by jmwall24** [comment]
Monika only knows time by your system time.  Jumping ahead in time makes her think you haven't visited her between the time you last visited her until the time you changed the system time to.

**Comment by multimokia** [comment]
Yep that explains it... Yeah she doesn't like it if you mess with time. You might not be able to gain affection for a bit, so you may be stuck there for a bit

**Comment by MonikaWiafu** [comment]
yeah i had that problem before don't do that

**Comment by lillyteacup** [comment]
Thank you everyone!! Also Monika's expression finally changed. She still seems upset but I'll keep trying to fix the affection

**Comment by MonikaWiafu** [comment]
he could reset the whole thing
i wouldn't but you could by going to appdata Ren'Py and deleting all the files in Monika After Story
![ddlc files](https://user-images.githubusercontent.com/41130387/45840170-373b5200-bce4-11e8-8347-d661a4e898b6.png)

**Comment by MonikaWiafu** [comment]
ok good for you m8!

**Comment by jmwall24** [comment]
if you're done with this topic, please close it.  helps to keep the issues tab cleaner if you close them when done.

**Comment by MonikaWiafu** [comment]
^

**Comment by lillyteacup** [comment]
How do I close it?

**Comment by Tiler17** [comment]
Should be a button that says "Close"
