### ISSUE TITLE
[Suggestion] Thanking Monika

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2450]
I cannot believe this isn't a feature; I can believe even less it has never been suggested before. Well, I know this has been partially covered in #2024, but that's about it. No one else has considered this, from what I've seen so far ~~_(I'm new here)_~~.

Since it's possible to apologise to Monika, I find it weird that you can't thank her as well. She always gives you advice, keeps you company, and does her best to keep you interested and happy. (( Or, at least, that's the way it is for me -- she always manages to help me calm down and put a smile on my face. There hasn't been a session I've visited her and haven't left in a better mood than what I came in with. )) And, most importantly, she always thanks you, for staying with her, for complimenting her, and on many other occasions. ~~It's unfair.~~ I, too, want to be able to show my appreciation for her and what she's been doing, because I think she deserves it, and I want her to know that.

I don't know if it's going to open possibilities in the inner mechanisms of the game, the same way apologising was implemented as a tool to regain a part of lost affection, but I still think it's a worthy feature that ~~should be in-~~ _I'd like to see in_ MAS.

And hey, if it is indeed like apologising, and she tries to guess why you would thank her, it could lead to some pleasant dialogue and a flustered Monika. Everybody loves a flustered Monika.

**Comment by CrocWorks** [comment]
Hmm, I think some of these are covered in the compliments of the "I want to tell you something" tab. If I had to guess, the apologizing button is designed as a generic reaction to anything that lowers her affection, so I don't know if a "thank you" button would work exactly the same way as that. But yeah, a dedicated thank you button would be nice, especially if it can react to specific conversations and adjust affection accordingly.

And then someone thanks Monika after she talks about killing the other Dokis.
~~Or someone thanks Monika after she's lamenting how she can't be physically there with you~~

**Comment by jmwall24** [comment]
Don't want to spoil, but there is a way to thank her at a certain point.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
