### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by Trainerbluetube** [Monika-After-Story/MonikaModDev#2456]
I just noticed something, when Monika talks about meeting your family she mentions her family, existing. But then she talks about how no-one in visual novels has parents unless it is a convenient drama hook. Which is it? Does she have parents or no?

**Comment by Rai99** [comment]
Monika _does_ technically have a family, but since she knows they're fake, she doesn't really consider them family. They _are_ there and _do_ exist, but they're not too important to Monika. In some topics, Monika doesn't even consider them family since they were never real.

**Comment by Trainerbluetube** [comment]
Well, I'd make an edit to the script or something, so she doesn't just gloss over her parents, existing, like maybe the
