### ISSUE TITLE
Need help downloading.

### ISSUE THREAD

**Issue by LightFright** [Monika-After-Story/MonikaModDev#2458]
So I just downloaded the newest version of MAS, but I do not know where to put the files. Help.

**Comment by multimokia** [comment]
Updating follows the same process as the installation bit here: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ

Just be sure to replace the `update` folder with the one in the zip too.

**Comment by LightFright** [comment]
Ok. So I started playing and decided to try to bring Monika to someplace, what file do I put her back into to continue the game?

**Comment by LightFright** [comment]
> Updating follows the same process as the installation bit here: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ
> 
> Just be sure to replace the `update` folder with the one in the zip too.

So I started the game after I got it to work and decided to try to to take Monika to a file, what file do I put Monika in to resume the game?

**Comment by multimokia** [comment]
Put `monika` back into the `characters` folder

**Comment by LightFright** [comment]
> Put `monika` back into the `characters` folder

Thanks.

**Comment by multimokia** [comment]
No worries. Is your issue sorted?

**Comment by monikLover** [comment]
We will never know :thinking:
