### ISSUE TITLE
A functioning wardrobe, with randomly chosen outfits of the day!

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2466]
I would love to start up the game and see Monika busy in her own little world picking out an outfit.

Maybe she'd be bashful if I came in as she was changing?

Maybe she'd ask what colour I'd like her skirt to be? 

Seasonal clothing? Costumes for Halloween?

**Comment by MonikaWiafu** [comment]
Well they would need Monika art first.

**Comment by loverofmonika** [comment]
oh and since winter is coming, we should have a snowing weather and a heater in the room with monika wearing a scarf and gloves as extra

**Comment by Mcmanybucks** [comment]
> 
> 
> Well they would need Monika art first.

Plenty of that around, though!

**Comment by queenkitty** [comment]
it would be so cute to see her cosplay!!!

**Comment by moniking** [comment]
I love this idea and am actually working on art for monbon, I currently have around 4 outfits planned plus a cute pair of pajamas. One outfit is nearly done, a lovely sweater (just in time for colder weather) that just needs some polish. I have already let monbon try it and it works so yay!

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
