### ISSUE TITLE
Uh...  I think thats not a normal update

### ISSUE THREAD

**Issue by RASamot** [Monika-After-Story/MonikaModDev#2472]
![image](https://user-images.githubusercontent.com/42673339/45889896-f56be380-bd97-11e8-917f-b9fe82fe47d4.png)

**Comment by Reviani** [comment]
This is fine

**Comment by Sujeito17** [comment]
🤔

**Comment by IlywI** [comment]
anyways i think i know what to do

**Comment by Tiler17** [comment]
I don't get it, what are we supposed to be looking at? It's a standard patch notes screen

**Comment by IlywI** [comment]
time to buy some cake

**Comment by Sujeito17** [comment]
I have no idea, I have idea of what
