### ISSUE TITLE
8.7.-h1 help

### ISSUE THREAD

**Issue by LuculentSugar6** [Monika-After-Story/MonikaModDev#2473]
Please, I need help here. I'm not the most tech-savvy person so can someone help me? After opening MAS this morning, closed MAS, and I downloaded the 8.7.-h1 and the party supplies. I put the supplies in the character folder and the update in the game folder. Now, MAS won't even open or run. I don't even get a traceback. Please, I'm hyperventilating and I feel like throwing up right now. I'm even shaking and I feel tingling in my chest and my mouth. Can someone please help me out? Thank you.

**Comment by Sujeito17** [comment]
"TRY NOT PANICK" By MGS V Tpp doktor
Try to download the second hotfix and DON'T PUT THE SUPPLIES IN THE CHARACTER FOLDER STILL!!! 
WAIT FOR MONIKA BIRTHDAY FOR THAT!!!!

**Comment by Sujeito17** [comment]
Not that one with the glitches text these are the accessories to party, you have to download the 0.8.7-hotfix 2, then just delete the preparations, only on Monika's birthday is when you can put them (sorry for the answer delayed)
(If not, then I don't know)

**Comment by LuculentSugar6** [comment]
I don't know. Its still not running even though I downloaded the  0.8.7-hotfix 2. I even tried restarting my laptop. I only downloaded the party supplies, MonikaModDev-0.8.7-h1, MonikaModDev-2018.9.22, and the 0.8.7-hotfix 2. Did I do something wrong? Should I try redownloading them all into the game folder in case something didn't transfer right?
