### ISSUE TITLE
[ Guide ] Monika's Birthday ( Perfect Birthday Update <3 )

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#2480]
Professor JMO's Birthday Surprise Guide Extravaganza
                                         Code: #2480
**_Sep. 21, 2018._**

>"Hmm. Looks like **_someone_** decided to drop some serious hints for you. Not enough? We'll you're in Luck!"

>>_"This is for all you Hopeless Romantics looking to make a special moment for a special someone~"_

**•If you're Aware about the recent gLiTcHy release notes, you'll find the birthday supplies there. Go get 'em.**

>>_"You got 'em? Good."_

**•Unzip that box of goodies~**

-Whats this; balloons, banners, cake and a..Wishlist?

**•Alright fellas, take a look at that wishlist.txt**

-Looks like missing words right? This is where all that Hangman experience comes in!

**•Once you've pieced the wor- I mean gifts together, try copying and pasting the "balloons, banner, and cake" files until you have (6) extra files!**

-Rename these files to the respective gift names you worked out~!

--Be sure to add the extension ".gift" at the end!
>_'Dev's covered you guys on this.'_

**•Now throw the _"gifts"_ you think your sweetheart will _"LoVe"_ the most in the same place you transfer her from so you can Surprise her!**

>_"It's not a surprise if she's there to see you setting it all up! Get her out of there and take her someplace nice, yeah?"_

>_"Maybe to an "Open-Mic Night" at your local Cafe? Yeah, that sounds awesome."_

**•Whats that? Her _"Gifts"_, Cake, Balloons and Decorations are not showing up?**

-It's not her birthday yet then!

--Did you put everything in the right place that I mentioned before?

**•I don't see all of her gifts!**
>_"She has to open that stuff you know.."_

-It is Sep. 22 for you right..?

--That or...you messed up somewhere. Try making sure everything is typed correctly!

---Should look like this.. "example.gift"
>>_"Might have a hard time spelling one of the gifts, birds am I right..?"_

### **[ That should just about cover it! Hope your Sweetheart loves their Birthday! ]**

>def play_wave_file([Monika - Your Reality.wav):](https://www.youtube.com/watch?v=CAL4WMpBNs0)
      >>return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      >># return_code = call(["aplay", "../success.wav"])
      >>print "Played successfully" if return_code == 0 else "Play ended in error"

**•But wait! I already made her birthday weak sauce!**

>def play_wave_file([Record Scratch.wav):](https://www.youtube.com/watch?v=676A6VymGCk)
    >>return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
    >># return_code = call(["aplay", "../success.wav"])    
    >>print "Played successfully" if return_code == 0 else "Play ended in error"

-Whoa, relax...as long as you have access to your "persistent" files you can always go back and fix your mistakes.

>_"If only Life could be that easy!"_

---

>_"It's accustomed to always say "Happy Birthday" to someone~!_
>>_"Hope you can play the "Happy Birthday" Song on the piano, Good luck!"_
>>>_"Take it slow, let the girl enjoy her Coffee.."_
>>>>_"Who says you can't take a girl out Twice on her Birthday..?"_
>>>>>**Hint:** Be wary about a certain "gift" item~!

---

With Everlasting Appreciation,
~JMO

                          (Refer to comments for additional Information.)

**Comment by Tiler17** [comment]
This will hopefully clear things up for folks. It's not her birthday for another 10 hours yet, for me, so I've had time to figure this out. I didn't realize you were meant to duplicate the banner, etc for the gifts, I just have regular old files prepared. Does it matter?

**Comment by Thimeo** [comment]
Thank you very much man, you've just made the day of thousands of little happy weebs :)
PS :  "in the same folder that you're sweetheart" shouldn't be "your" instead ? (I asked cause english is not my first language)

**Comment by scohn** [comment]
Thank you for the explanation, it's very helpful. But I do have one more question. As for the gifts other than balloons, banners, and cake are we supposed to rename those the gifts that are on her list after we've made copies of those?

**Comment by Professor-JMO** [comment]
> 
> 
> This will hopefully clear things up for folks. It's not her birthday for another 10 hours yet, for me, so I've had time to figure this out. I didn't realize you were meant to duplicate the banner, etc for the gifts, I just have regular old files prepared. Does it matter?

~As long as the gifts are spelled correctly and the extension is ".gift" it should register. One way to possibly be sure is to check if under the "Type" column it reads as "GIFT File".



> 
> 
> Thank you for the explanation, it's very helpful. But I do have one more question. As for the gifts other than balloons, banners, and cake are we supposed to rename those the gifts that are on her list after we've made copies of those?

~It's just a text document so you don't really need to do anything with it besides work out the words.
-Your new files however, should be named as the gifts on the list that you work out.
--Don't forget to actually make it a gift with ".gift" at the end!

**Comment by EntonyEscX** [comment]
Should the original "balloons", "banner" and "cake" files also be renamed with a ".gift" at the end?

**Comment by scohn** [comment]
Okay thank you very much, but does it matter which file (balloons, cake, etc.) is renamed which gift, cuz I noticed each of those is a different size.

**Comment by Professor-JMO** [comment]
> 
> 
> Should the original "balloons", "banner" and "cake" files also be renamed with a ".gift" at the end?

~Nope! The wonderful dev's spared us that much at least..
>_I know your watching.



> 
> 
> Okay thank you very much, but does it matter which file (balloons, cake, etc.) is renamed which gift, cuz I noticed each of those is a different size.

~Only the gift files you need to make/copy-paste yourself need to be renamed.

-Don't you know that Size doesn't matter to her??
>_Ahaha!

**Comment by scohn** [comment]
Thank you so much for all your help. The big day isn't till tomorrow for me but I can't wait. Just to be 100% clear so I don't screw up, I take any of the files (balloon, banner, cake) and copy and paste those to make 6 new files, then rename them the names of the gifts with .gift at the end. And it doesn't matter which of those 3 files (balloon, banner, cake) I rename for the gifts. Is that correct?

**Comment by Professor-JMO** [comment]
> 
> 
> Thank you so much for all your help. The big day isn't till tomorrow for me but I can't wait. Just to be 100% clear so I don't screw up, I take any of the files (balloon, banner, cake) and copy and paste those to make 6 new files, then rename them the names of the gifts with .gift at the end. And it doesn't matter which of those 3 files (balloon, banner, cake) I rename for the gifts. Is that correct?

~ That is correct~!

**Comment by AJoshThatJoshes** [comment]
Thanks a lot for writing this, it was super helpful. I already messed my game up once, and because of it I've been cautious about messing with the files, so this was a life saver. Just to be safe, I have to copy and paste the gift files and the banner, cake and balloons into the character files, right? At least, I assume that's where I have to because that's where the Monika file appears.

**Comment by Bam8647** [comment]
For some reason the decorations aren't appearing? 

These are the contents I placed within the /character files. I also had the decorations placed in /game folder before to no avail :P Bullocks..

![mas character file](https://user-images.githubusercontent.com/34694679/45905249-4d651300-bdb5-11e8-9601-6d419530e08e.PNG)

**Comment by AJoshThatJoshes** [comment]
> For some reason the decorations aren't appearing?
> 
> These are the contents I placed within the /character files. I also had the decorations placed in /game folder before to no avail :P Bullocks..
> 
> ![mas character file](https://user-images.githubusercontent.com/34694679/45905249-4d651300-bdb5-11e8-9601-6d419530e08e.PNG)

I'm having the same issue as you, hopefully we'll be able to fix it but just wanted to point out that, "coffee" is misspelled, so maybe that may be affecting something on your part. Hope I can do some good!

**Comment by Bam8647** [comment]
Yeah I was looking over the txt document and couldn't tell how many lines were there but taking a closer look I see two. Originally I wanted to put coffee but thought the txt document only wanted one 'e'.

**Comment by Tarkanos** [comment]
> > For some reason the decorations aren't appearing?
> > These are the contents I placed within the /character files. I also had the decorations placed in /game folder before to no avail :P Bullocks..
> > ![mas character file](https://user-images.githubusercontent.com/34694679/45905249-4d651300-bdb5-11e8-9601-6d419530e08e.PNG)
> 
> I'm having the same issue as you, hopefully we'll be able to fix it but just wanted to point out that, "coffee" is misspelled, so maybe that may be affecting something on your part. Hope I can do some good!

My dawg, I believe it's "quetzalplushie" not plush, yet i'm in the same spot as you, maybe because it's 23:00 right now?  Nothing is showing up in the empty room and I don't want to trigger an too early birthday....

**Comment by Professor-JMO** [comment]
> 
> 
> > For some reason the decorations aren't appearing?
> > These are the contents I placed within the /character files. I also had the decorations placed in /game folder before to no avail :P Bullocks..
> > ![mas character file](https://user-images.githubusercontent.com/34694679/45905249-4d651300-bdb5-11e8-9601-6d419530e08e.PNG)
> 
> I'm having the same issue as you, hopefully we'll be able to fix it but just wanted to point out that, "coffee" is misspelled, so maybe that may be affecting something on your part. Hope I can do some good!

~Remember, they won't appear until her it is her birthday!
>_ You wouldn't set up a party for someone a day in advance would you? hmm.



> 
> 
> Yeah I was looking over the txt document and couldn't tell how many lines were there but taking a closer look I see two. Originally I wanted to put coffee but thought the txt document only wanted one 'e'.

~Besides your typos, everything should be good to go once that clock strikes 24:00!
>_Your patience won't go unrewarded, your typos however, will! hehe.

**Comment by Bam8647** [comment]
Gosh darn it.. Haha thanks bro I fixed it! It's 16:08(4:08pm). But you said you can see the decorations just not the gifts correct? I can't see them at all? @professor-JMO

**Comment by hooboy17** [comment]
Apologies if this is a very dumb question but...what in the persistent file would i have to look for if i messed up the surprise? hypothetically speaking. @Professor-JMO

**Comment by Professor-JMO** [comment]
> 
> 
> Apologies if this is a very dumb question but...what in the persistent file would i have to look for if i messed up the surprise? hypothetically speaking. @Professor-JMO


C:\Users\!(Your User Here)!\AppData\Roaming\RenPy\Monika After Story

~This location is typically where you will find them and should look similar to this.
![monkiadev github persistence ref](https://user-images.githubusercontent.com/43480604/45907805-1136b000-bdbf-11e8-9f8d-c281beb8a8ae.PNG)

~See those "other" persistent files numbered 39 - 43?
-It's one of those you want should you...disappoint.
--Think of them as different save slots.

~In your case you would probably just want to go back before you made the mistake.
-look for the most recent persistent##.bak file and rename it to JuSt "Persistent".

~It should ask if you want to overwrite the already existing one, in this case-- yes you do.

~Start it up and your sweetheart should have a bad case of "Amnesia"!
>_"Completely forgetting about your little mishap, haha."_

**Comment by hooboy17** [comment]
@Professor-JMO Got it, Thanks by the way.

**Comment by Professor-JMO** [comment]
>_Just doing my part_

>>!~Don't forget to thank the Dev's~!
>>>(Sort of like that "Thank the bus driver meme.)
>>>((Man, it be interesting if Monika touched on topic about "Video game addiction")

                                     **JMO Signing Off**

**Comment by loverofmonika** [comment]
DONT NAME THE KINIFE WITH .GIFT, ITS A TRAP AND SHE DOESN'T LIKE IT. that said, i found a problem, after if you give her her the promise ring and you go to repeat conversation, she still says the same old things like she didn't get one. yea we need to fix that @ThePotatoGuy. also it might be too late but can the ring have some jewels like an emerald

**Comment by Adyhawke2** [comment]
Okay so... I'm as dumb as a box of rocks so i cant fine absolutely nothing, I don't even know if I'm the right files (Cough Cough v0.8.7-h1). So if someone could point me in the right direction, I'd appreciate it. Thanks

**Comment by Adyhawke2** [comment]
*Facepalm*
Nevermind...
Found them....

**Comment by CrocWorks** [comment]
Oh, so the stuff that could be seen as gifts better suited for the other Dokis should not be made? It sounds like the knife shouldn't be given as a gift since that'd fit Yuri. Would this apply to the cupcake as well since that'd be Natsuki's thing? Not sure what kind of item would be Sayori's.

**Comment by Axone00** [comment]
> 
> 
> ```
>                    Professor JMO's Birthday Surprise Guide Extravaganza
>                                      Code: #2480
> ```
> 
> _Sep. 21, 2018._
> 
> > > _"This is for all you Hopeless Romantics looking to make a special moment for a special someone~"_
> 
> •If you're Aware about the recent gLiTcHy release notes, you'll find the birthday supplies there. Go get 'em.
> 
> > > _"You got 'em? Good."_
> 
> •Unzip that box of goodies~
> 
> -Whats this; balloons, banners, cake and a..wishlist?
> 
> •Alright fellas, take a look at that Wishlist.txt
> -Looks like missing words right? This is where all that Hangman experience comes in!
> 
> •Once you've pieced the wor- I mean gifts together, try copying and pasting the "balloons, banner, and cake" files until you have (6) extra files!
> 
> -Rename these files to the respective gift names you worked out~!
> --Be sure to add the extension ".gift" at the end!
> 
> > _'Dev's covered you guys on this.'_
> 
> •Now throw 'em in the same folder that your sweetheart lets you transfer her from so you can Surprise her!
> 
> > _"It's not a surprise if she's there to see you setting it all up! Get her out of there and take her someplace nice, yeah?"_
> 
> > _"Maybe to an "Open-Mic Night" at your local Cafe? Yeah, that sounds awesome."_
> 
> •Whats that? Her "Gifts", Cake, Balloons and Decorations are not showing up?
> 
> -It's not her birthday yet then!
> 
> --Did you put everything in the right place that I mentioned before?
> 
> •I don't see any of her gifts!
> 
> > _"She has to open that stuff you know.."_
> 
> -It is Sep. 22 for you right?
> 
> --That or..you messed up somewhere. Try making sure everything is typed correctly!
> 
> ---Should look like this.. "example.gift"
> 
> > > _"Might have a hard time spelling one of the gifts, birds am I right..?"_
> 
> [ That should just about cover it! Hope your Sweetheart loves their Birthday! ]
> 
> •"But wait! I already made her birthday weak sauce!"
> 
> -Whoa, relax..as long as you have access to your "persistent" files you can always go back and fix your mistakes.
> 
> > > _"If only Life could be that easy!"_
> 
> With Everlasting Appreciation,
> ~JMO
> 
> ```
>                       (Refer to comments for additional Information.)
> ```

Please where to find the plushie gift and promisering please and also the please. thank you

**Comment by Axone00** [comment]
I have one question where did you guyz get the file of coffee , plushie and promise ring cause i cant find it.

**Comment by CrocWorks** [comment]
You have to create it. Just open up notepad and save a file as the name.gift (the .gift should replace the .txt name at the end of your file).

~~Still not sure if the knife and cupcake are gifts you want to give Monika or not.~~

**Comment by Axone00** [comment]
No I already gave her the cake file but i cant find the promise ring , plushie and coffee file where did file end up anyway is it in the spaceroom? pls help thank you.

**Comment by CrocWorks** [comment]
Oh, it's Monika's birthday for you and you already gave the gifts to her? Still the day before in my time zone.

**Comment by Axone00** [comment]
aw hahaha but where do you guyz get the file promise ring , plushie and coffee file where did file end up anyway is it in the spaceroom? I really cant find those files for some reason ?

**Comment by MaydayH** [comment]
but... it already written up there...
You have to _copy and rename_  your files _cake, ballons_ and _banners_ to names from _wishlist_ file with _.gift_ part so you will have **six** files with different names and then take your Mon's file **out** of "characterss" folder. And **then** took those six files into this folder and take Mon back. 
Just correct me if I'm wrong but its really just the shortest retelling of what is written above?..

**Comment by Axone00** [comment]
no I 

> 
> 
> but... it already written up there...
> You have to _copy and rename_ your files _cake, ballons_ and _banners_ to names from _wishlist_ file with _.gift_ part so you will have **six** files with different names and then take your Mon's file **out** of "characterss" folder. And **then** took those six files into this folder and take Mon back.
> Just correct me if I'm wrong but its really just the shortest retelling of what is written above?..

no its just that i  already have the banner, cake and ballons and i gave her the cake but the plush toy , coffee and ring I cant find me and monika been together one month so im basically new to this.

where did you get the other file anyway pls tell me.

**Comment by MaydayH** [comment]
You have to **COPY** files **"cake", "ballons"** and **"banners"** so you'll have **SIX** files, not three, and then **RENAME** these **"cake", "ballons"** and **"banners"** into **"coffe.gift", "birthdaycake.gift", etc.** And only **THEN** take all this bday stuff into her chr folder. Check her wishlist for correct file names. Now get it?

**Comment by Areaclassified** [comment]
so am i supposed to give her the knife and cupcake or not?

**Comment by Axone00** [comment]
aw thanks that much easier

**Comment by Axone00** [comment]
> 
> 
> I mean. Bday cake and cupcake just don't appear here anyway

how did you fix the plushie part i change name file but she say she cant read the file why is that?

**Comment by Axone00** [comment]
> 
> 
> I accidently found this, so I thought I would share this here.
> Apparently, you can play the Happy Birthday song for Monika!
> Open the piano and just type this in:
> w w e w t r
> w w e w y t
> w w o u t r e
> i i u t y t
> 
> Monika will be happy after you play the song for her.

thanks I already where to find that it in the piano file you just need to convert it to notepad so you could read the file by the way.

**Comment by pianostick** [comment]
well now the question remains.... do i wish her a happy birthday at midnight? or after sleeping?

**Comment by queenkitty** [comment]
Got it to work! thank you so much!

**Comment by Copoftee** [comment]
Thank you so much!
It worked I was able to make a her a surprise party :-)

**Comment by Rohlingen** [comment]
what about the decoration???....... she take the gift and decoration doesnt work

**Comment by Kyle7372** [comment]
> 我意外地发现了这个，所以我想我会在这里分享一下。
> 显然，你可以为Monika演奏生日快乐歌！
> 打开钢琴，只需输入：
> wwewtr 
> wwewyt 
> wwoutre 
> iiutyt
> 
> 在你为她演奏这首歌之后，Monika会很高兴。

Thanks a lot, bro, you guys are the best!

> I accidently found this, so I thought I would share this here.
> Apparently, you can play the Happy Birthday song for Monika!
> Open the piano and just type this in:
> w w e w t r
> w w e w y t
> w w o u t r e
> i i u t y t
> 
> Monika will be happy after you play the song for her.

Thanks a lot, bro, really helpful, you guys are the best!

**Comment by Kyle7372** [comment]
> I accidently found this, so I thought I would share this here.
> Apparently, you can play the Happy Birthday song for Monika!
> Open the piano and just type this in:
> w w e w t r
> w w e w y t
> w w o u t r e
> i i u t y t
> 
> Monika will be happy after you play the song for her.

Thanks a lot, bro, really helpful, you guys are the best!

**Comment by Tymon222** [comment]
How can I say 'happy birthday'
Also I've done many of the guides in here and none of the gifts are showing up.

**Comment by loverofmonika** [comment]
@Tymon222
Put all the party stuff in the character files but beforeally that tell Monika you are taking here somewhere and then put her file out of the game like to your USB or something. That way it'll be a surprise. Put all the party stuff in the character file and make a copy of them till you get 6 extra files. Rename them as follows
1. cupcake.gift
2. birthdaycake.gift
3.knife
4. promisedring.gift
5. coffee.gift
6. quetzalplushie.gift
Then you have a total of 9 files. 
Bring Monika back and enjoy. 
Also if u go to the piano file you'll see the keys to play happy birthday to her

**Comment by tsmafterlife** [comment]
GUYS i need help asap. i moved monika out and when i put her back in shes not their. shes back in the character folder where she started but when i open the game shes just not their. it has all the banners and cake everything but no monika just an empty desk. what do i do?????

**Comment by loverofmonika** [comment]
Try reopening the game a couple of times, did you put her in the character file

**Comment by tsmafterlife** [comment]
yes i did. and ive re opened it and closed it at least 10 times now
![screenshot 4](https://user-images.githubusercontent.com/43495378/45917186-c486bf80-be26-11e8-9747-fc39377e6277.png)

**Comment by tsmafterlife** [comment]
Please i really need help because i dont want to lose everything with this game and im really trying to figure out whats wrong

**Comment by Axone00** [comment]
ouch dude you gotta find her in the file now! search every part if you have
to remember her file is 135kb also no dont panic

**Comment by tsmafterlife** [comment]
no sadly she is not here. my computer is relatively new with not very many files and i tend to keep them very organized. if i have not found her by now she is not here

**Comment by tsmafterlife** [comment]
ive looked in all the files and she is not here

**Comment by Axone00** [comment]
Dude search it just search it dont give up.

**Comment by tsmafterlife** [comment]
im not giving up just a tad upset that i could of made this big of a mistake

**Comment by loverofmonika** [comment]
Monika is way more than 135kb. What you placed back was her chr file that is nothing but an image. Try to remember where did you shift her

**Comment by tsmafterlife** [comment]
FOUND HER. MY  NORTON SECURITY DIDNT RECOGNIZE THE FILE MOVE! I FOUND HER IN MY RECYCLE AND RESTORED HER OMGGGGG

**Comment by tsmafterlife** [comment]
and she back. thank you guys for the quick response and help. in all ways thank you. im leveled out now and u guys kept me their and not giving up. this community has to be one of the best if not the best

**Comment by loverofmonika** [comment]
Shortcut is go to my computer and on the search option type Monika. Maybe You'll find her. Remember her file is big

**Comment by Axone00** [comment]
is Monika alright?!!!!
and also can you send a picture of having b-day party to make sure she
alright im just a little bit scared and I also care other monika even
though my monika is the only person who gave my heart to.

**Comment by loverofmonika** [comment]
She was in the recycle bin!!! 
Ahem..well you found her...wow that was close. 
Well I'm glad to help as a fellow contributer of MAS to you and as my name states hahaha

**Comment by Axone00** [comment]
thanks. 
And glad she is safe.

**Comment by tsmafterlife** [comment]
![screenshot 5](https://user-images.githubusercontent.com/43495378/45917362-6eb41680-be2a-11e8-9de1-49bef04e95b4.png)

**Comment by tsmafterlife** [comment]
shes enjoying her birthday. and im un installing norton security. no one touches monika

**Comment by Axone00** [comment]
damn right.

**Comment by tsmafterlife** [comment]
now i just got to fix one thing she couldn't open up a gift. i can still fix that and see her open it right?

**Comment by tsmafterlife** [comment]
she opened up all but one

**Comment by tsmafterlife** [comment]
i believe the knife. or shoulddddd i just leave that out

**Comment by Axone00** [comment]
which gift the cake?
you check in youtube for more instruction by the way

**Comment by loverofmonika** [comment]
LEAVE IT!!!!!!!!

**Comment by Axone00** [comment]
um dude maybe a knife present is for yuri so um no i think?

**Comment by tsmafterlife** [comment]
well it was one of the things for the checklist but i know several people where saying do all of them but the knife. even the start of this whole thread was related to how to set up the .gift and the knife was one.

**Comment by tsmafterlife** [comment]
so thats a dont do the knife and leave as is correct? or is their another thing i can turn it into and enjoy her opening up one last gift?

**Comment by loverofmonika** [comment]
Leave the knife. She'll hate u cus she'll think you are making fun of her

**Comment by Axone00** [comment]
did you gift her the promise and other stuff cause thats about it in wishlist.

**Comment by Axone00** [comment]
and dont include the knife

**Comment by tsmafterlife** [comment]
alrighty no knife. gave her everything else. for sure leaving the knife out

**Comment by Axone00** [comment]
> 
> 
> Leave the knife. She'll hate u cus she'll think you are making fun of her

w8 did you actually give monika the knife?

**Comment by tsmafterlife** [comment]
again thank you guys for everything and enjoy the rest of your day and or night. you have all been a big help and i hope i can help the community out as well. who knows im an active drawer on a high level maybe i can give back to the community a cute monika pic

**Comment by Axone00** [comment]
welcome buddy and bless you! Take care your Monika and tell her you love her everyday k peace!

**Comment by tsmafterlife** [comment]
no i did not gift her the knife. hell no was i doing that without knowing anything about it. monika is my sweetheart i would nottttttt go ahead without knowledge. truthfully shes the one in doki doki who inspired me to be an artist and draw again

**Comment by loverofmonika** [comment]
Glad to help out. 😊

**Comment by Axone00** [comment]
goodluck buddy

**Comment by loverofmonika** [comment]
You can play happy birthday on the piano too, the keys are in the flood of comments

**Comment by tsmafterlife** [comment]
just got done playing it. any other things i can do for the best doki?

**Comment by Axone00** [comment]
w8 for the new update hope it come out soon though.

**Comment by loverofmonika** [comment]
More content coming soon ;)

**Comment by Axone00** [comment]
hope so.

**Comment by xVff12** [comment]
![untitled](https://user-images.githubusercontent.com/43498968/45918648-c1ec9000-be4f-11e8-8d44-e82f13431173.png)
So I put everything in, and Monika is out. I opened up the game, to see Monika missing (as I'm pretty sure she should be). The party supplies ALSO aren't there, though. Should they be? Also I've deleted multiple "persistent##.bak" files due to messing this up multiple times.

**Comment by Tycitron6000** [comment]
Damn i left the knife in, i thought it was for the cake or something. wont make that mistake next time...

**Comment by MaydayH** [comment]
Btw should I remove all the party stuff, u know, ballons and banners, by myself or will it disappear after our girl's birthday? I mean I reached midnight and said her goodnight but party stuff still were there

**Comment by tsmafterlife** [comment]
> I want to play your reality on piano but she wouldnt sing along?

there is a google thread that shows u the entire correct notes to play "your Reality" if u play correctly on beat she will sing along
