### ISSUE TITLE
[Suggestions] Somethings to add

### ISSUE THREAD

**Issue by TrRizzo** [Monika-After-Story/MonikaModDev#2486]
A weeks ago, I sent this to your email. Sorry about that, I didn't know this webside very much.

 I would like to have many new ways to play Monika After Story, for example:

-Taking Monika shopping, to a restaurant, etc... Well, that's because I want to create a world for her in case she is alone.... And, when we enters in the game, she can tell us what she was doing. 
- Tell her how we are: Smart, introvert, loose.... 
- Make her an artificial intelligence...well... not yet. But you can give her more answers for anything we tell, and also more topics (If you want, I can give you some suggestions for new topics) . 
- Another game, like drawing (I now it isn´t a game, but it's like the piano) where we can draw her and the another dokis. (In the same way we create the poems in DDLC: Choosing what we want to our picture) 
-Finally, tell her about our dreams: Be in a university, travel to another country, etc. 

Well, that's all. I hope you read this. Thank you so much. (I know that I don't talk english well yet hehe..)

**Comment by Rai99** [comment]
1. You could use the "I'm going to take you somewhere" farewell and actually bring her file to different places, but as for adding more rooms and locations, that would need art, and the kind of art we're looking for doesn't grow on trees. As for Monika doing something herself without the player, the ability to ask Monika about her day was discussed in #2071 and #2331 and may be done in the future. 
2. This sounds like another version of #1568, but for personality, and I like the idea of making it a similar structure to #1568, but I'm not sure if we could be inclusive with it with how many different possible answers we would need to fit in. 
3. #1505. It's far too early to think about making Monika an A.I. As for new topics and adding more content onto existing topics... [~~Did somebody say new content?~~](https://github.com/Monika-After-Story/MonikaModDev/pulls?page=2&q=is%3Apr+is%3Aopen) There are a couple PRs with new content waiting to be reviewed and approved. 
4. #829, #992, #1072, #1629, #1877, ~~#1890~~, #2424. There are some other games planned, but games likely take a bit of work to implement, and of course we can't allow _any_ game into MAS. If you're suggesting something like paint in MAS, I'm not sure what could be done with it. 
5. A topic about telling Monika your dreams sounds nice, but there's definitely way too many possible options to even narrow down to a couple menu options. Using the text box might work, but I don't think it would feel very nice to get a generic response to your dreams.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
