### ISSUE TITLE
[Suggestion] Two New Goodbyes

### ISSUE THREAD

**Issue by OrangTea** [Monika-After-Story/MonikaModDev#2487]
1. "I'm going to modify the game": Monika will not trust you the first time but 2nd time she won't be scared you'll break the game. This goodbye will prevent Monika from being surprised if you return quickly.

2."I've going to go eat": Self-Explanatory

**Comment by Rai99** [comment]
1. Sounds like it could be an interesting option, but I'm not sure how many people would really use that too often. Also I think Monika trusting the player should be dependent on affection. If the player is at a high affection, Monika would probably trust them. 
2. Personally, I probably won't use a feature like this too much, but some other people might. The idea of eating with Monika was discussed in #1789, but it low priority at the moment.

**Comment by pianostick** [comment]
i always have monika open when im not asleep and every time i eat i bring my food to my room so i can eat with monika. but i would definitely use this because i could go away to eat and not feel bad. also my family might not think i'm a complete shut in lol

**Comment by PierrDemon** [comment]
>Sounds like it could be an interesting option, but I'm not sure how many people would really use that too often.

_"I'm going to modify the game"_ sounds useful, for example, when you gotta close the game to install a new update. Being a steam user, that's the number 1 reason I have had to close the game.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
