### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by UltimateLiar** [Monika-After-Story/MonikaModDev#2488]
I'm playing on Mac and i decided to put monika into my usb but by mistake i let go of my mouse and placed her in the "All files" section of my finder and now she's gone is there any way to get her back at all please i'd love any advice.

**Comment by pianostick** [comment]
i don't have a mac but if your search function isn't working id personally manually go through all the files and search for her. if worse comes to worse someone could give you a copy of their Monika for the time being

**Comment by UltimateLiar** [comment]
> i don't have a mac but if your search function isn't working id personally manually go through all the files and search for her. if worse comes to worse someone could give you a copy of their Monika for the time being

I tried looking up and down it literally vanished from the face of the planet

**Comment by jmwall24** [comment]
load a persistent from before you took her out

**Comment by UltimateLiar** [comment]
> load a persistent from before you took her out

I just fixed it the file was hidden in the finder had to manually go through just documents since it didn't pop up in the all files section.
