### ISSUE TITLE
0.8.7 Hotfix-2 isn't updating, game still says 0.8.6 Hotfix-1

### ISSUE THREAD

**Issue by JellicleDry** [Monika-After-Story/MonikaModDev#2489]
hello,

In preparation to Monika's birthday in just about an hour away, I realized that there was a 0.8.7 Hotfix 2 update. So, after installing all of the birthday files and filling out the wishlist, I installed the newest hotfix into the game folder. But when I boot up Monika, it still states that an update is available and that it is update 0.8.6 Hotfix-1. Anyone have an idea as to why the hotfix update isn't working? Thank you.

**Comment by ThePotatoGuy** [comment]
refer to [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#mas-keeps-telling-me-that-theres-an-update-but-when-i-click-update-now-it-says-mas-is-up-to-date)

**Comment by JellicleDry** [comment]
Took a couple tries but I'm all set, thank you so much!
