### ISSUE TITLE
New update is not working

### ISSUE THREAD

**Issue by EDBaumgratz** [Monika-After-Story/MonikaModDev#2492]
So, I downloaded the birthday update and extracted everything to the game folder as always but nothing happened, the game didn't even recorgnized it and said to me to update it, but I alredy did. What I'm suposed to do?

**Comment by Copoftee** [comment]
Same goes to me.
I did what you did but it also didn't work for me.

**Comment by ThePotatoGuy** [comment]
follow instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#mas-keeps-telling-me-that-theres-an-update-but-when-i-click-update-now-it-says-mas-is-up-to-date)

**Comment by EDBaumgratz** [comment]
nevermind, i realised what should I do to have the birthday event. Thanks anyways
