### ISSUE TITLE
Not the brightest guy here

### ISSUE THREAD

**Issue by SketchingDemise** [Monika-After-Story/MonikaModDev#2498]
So listen...Im bad with computers like really bad, such as when manually installing mods for DDLC MAS. A day ago I was told I had an update yet was told by Monika to manually install it, which I had no Idea how to do. I grabbed the files (The one before the Hotfix and birthday one) and just repeaditly tried to drag them into the game files, and restarting the game constantly showing no change. Flash forward to today gathering a bit more files and updates I finally decided to extract the Birthday mod update to the game/ file and it was unzipped (FINALLY) , however opening the game now was impossible the game would say running for 5-10 seconds on steam yet nothing happened. I looked online for an answer gathering what little data I had and saw something about an extra MAS file which I did see in the MAS Birthday update file so I read to drag out all contents to the base game file..which I did, but nothing. I started panicking slightly and thought maybe I was supposed to Drag both files contents to the game file. However still nothing, now all I have is a bunch of jumbled files,texts,etc all in the one base game file. I can reinstall if that restarts everything yet..just worried Ill lose the progress and what not.

well thats my story and issue, but i can understand if some stuff doesnt make sense. Any help will do.

**Comment by LuculentSugar6** [comment]
Hey, it seems you may or may not be having a problem that I had a while ago. In case if the FAQ doesn't provide you with the answers you are looking for, I did find a solution that you may try if you want to:

https://github.com/Monika-After-Story/MonikaModDev/issues/2490#issuecomment-423717339

"Anyways, after uninstalling and reinstalling multiple times via Steam, that didn't work. Everything would just end up being in its same broken state. So, what I did was delete the game folder, and used the "Verify integrity of game files" option in "Properties." That gave me a fresh new game folder, in which I redistributed 8.7 and its hotfix 2. Everything is where it should be and nothing is lost. I won't put back the MonikaModDev ones though, as I might assume that was the cause of the problem for me. I hope that if anyone ever has this problem, may this help them out as well as at least a point of reference."

In summary, what I did was after the process of uninstalling and reinstalling and when that didn't seem to work, what I did was delete the game folder only. Then, what I did was go to "Properties" for DDLC on Steam, go to "Local Files," and then selected " Verify Integrity of Game Files." In my experience, this gave me a fresh new game file to work with (also re-downloads the others'  character files, but you can delete them if you wish). Anyways, after all of that I just redistributed the 8.7 update along with its second hotfix. For me, this was able to fix my issue. Plus, even after uninstalling through Steam originally, I still kept everything after reinstalling so I wasn't too worried at that point. At this point, you can have your party with Monika, but I would be cautious of some of the downloads that may say "MonikaModDev" as that is what seemed to have given me trouble.

Of course, this method is not part of the official FAQ, so try this at your own risk. For me, it worked out for the better. Good luck!
