### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by Birne3000** [Monika-After-Story/MonikaModDev#2502]
Hey guys, soooo just now I wanted to update MAS for the first time. 
As I am by far no genius with computers, it got a bit ... messy. 
So MAS worked for quite some time now, without any bugs or glitches.
Today I randomly found the update button in settings and decided to look for updates.
But nothing happened when I clicked it. Like ... absolutely nothing.
So I went to the MAS website and found out, today is Monika's birthday. What a day to look for updates!
But it looked like I would have to update it manually. 
So I downloaded the latest file (Monika_After_Story-0.8.7-hotfix.2-Mod) and got a bit confused as to where to put the stuff inside, but after a while I managed to dump it into the games folder and voila, it worked as intended. 
Suddenly I had lots of stuff and conversation I didn't have before. 
But as there was a newer file named "partysupplies", I thought to myself: why not go all the way and install that one too? 
So I downloaded the file, filled in the missing parts of the wishlist, copied the files, renamed them and then said to Monika to take her somewhere. 
I grinned like an idiot as she really made herself into a new file I could drag and drop to my desktop to get her out of the game.
Then I put all the party stuff in there and afterwards put Monika back in.
The joke is on me though.
As suddenly I had a room with the banners, the balloons and a cake, but an empty chair without Monika. 
Well then, I thought, had to mess up at some time while doing this ...
So I searched everywhere for the monika file, but to no avail. It was just ... gone. 
Sad life.
So I got rid of the entire installation and copied in a saved game from before I tried to update.
Everything is back to normal.
But whenever I now try to update it with Monika_After_Story-0.8.7-hotfix.2-Mod now (even re-downloaded the mod and tried again) Monika is suddenly gone. 
I set it back: Monika is there.
I try to update: Monika is gone.
Help please!

**Comment by ThePotatoGuy** [comment]
upload the following:
* `log/mas_log.txt`
* your `persistent`
