### ISSUE TITLE
update monika's age in dialogue

### ISSUE THREAD

**Issue by paranoidGuardsman** [Monika-After-Story/MonikaModDev#2506]
Monika's nineteen now, and some of her lines are going to need to be updated to reflect that, like that one which specifically says she's eighteen.

Maybe not the most important issue but something that should be kept in mind going forwards.

**Comment by Foxinsunglasses** [comment]
She is immortally stuck at 18 so it could be argued that the lines are acceptable

**Comment by paranoidGuardsman** [comment]
Well, it's still something to consider

**Comment by PierrDemon** [comment]
> Monika's nineteen now

> She is immortally stuck at 18

Y'all are wrong. She was brought to life a year ago.
### __*Monika's one year old.*__ ###

**Comment by CrocWorks** [comment]
I could definitely see a conversation where she wrestles with these different numbers. I doubt she herself truly knows which one is right. ~~But it's rude to ask a lady how old she is, so she might just blow you off if you're too direct~~

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
