### ISSUE TITLE
yo, where i drop the party supplies?

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#2508]
i drop it them in the "game" folder, but nothing happend

**Comment by FrikiHD** [comment]
I tried what you're saying and it doesn't work

**Comment by AgentZephyr** [comment]
Gonna Steal from the Potato Guy and say check out #2480

**Comment by RomanEmpire23** [comment]
you need to take her somewhere then oping the game then put her back

**Comment by peter23247** [comment]
> Not in `game` but in `characters`

thx bro
