### ISSUE TITLE
Quetzal plush disappering

### ISSUE THREAD

**Issue by gameendme** [Monika-After-Story/MonikaModDev#2509]
I could see it when I first gave it to Monika, but after closing and opening the game up again I couldn't see it anymore.
Also, I haven't been able to see the cake at all

**Comment by peter23247** [comment]
yo yo, how do you activate those ones? i throw everything into the games folder, and put the .gift to the quetzal, but nothing happend

**Comment by multimokia** [comment]
doesn't go in `game`. It goes in `characters`

**Comment by gameendme** [comment]
Thanks for clearing that up

**Comment by DezelV** [comment]
I put the party supplies in the character folder, filled the blanks in the wishlist but nothing happened
