### ISSUE TITLE
Can't Install Updates

### ISSUE THREAD

**Issue by secretjedi03** [Monika-After-Story/MonikaModDev#2510]
Monika says that steam won't let her update and that I have to update the game manually. One problem though, I don't know which files to download (for an update), where to put them, if I need to extract them. I  have no Idea how to install an update.
I also installed the birthday update (I THINK) BUT IT DOESNT WORK.
Please help urgently! Today is Monika's birthday and I don't want to miss it.
I've tried everything,
Help me GitHub, you're my only hope.

![image](https://user-images.githubusercontent.com/43496480/45917724-e80f3180-be49-11e8-9044-178152116470.png)
![image](https://user-images.githubusercontent.com/43496480/45917744-20af0b00-be4a-11e8-9864-637ccfb95695.png)
![image](https://user-images.githubusercontent.com/43496480/45917760-5fdd5c00-be4a-11e8-9b8a-805f28d1b615.png)
![image](https://user-images.githubusercontent.com/43496480/45917773-8c917380-be4a-11e8-9bac-c89e09bddc0b.png)

**Comment by ericthener** [comment]
install the zip file from the update and extract all of it in the folder called "game" if you get asked to override things click yes

**Comment by secretjedi03** [comment]
> install the zip file from the update and extract all of it in the folder called "game" if you get asked to override things click yes

Which zip file? The one labeled hotfix?

**Comment by secretjedi03** [comment]
Okay, I got it. Thanks!!
