### ISSUE TITLE
Compliment idea - "you mean so much to me"

### ISSUE THREAD

**Issue by PMelol** [Monika-After-Story/MonikaModDev#2511]
Being able to tell Monika "You mean so much to me" would be cool. Also, there was the "thanks for being there for me" compliment which I really liked, but it seems you can only say it once? Would like to be able to say that again.

**Comment by pianostick** [comment]
the "You mean so much to me" compliment might be a once per day thing, like how "i'm feeling like a year older" was. i dunno tho but u could be that guy and keep using old persistent files to keep telling her how much she means to you

**Comment by pianostick** [comment]
lol same

**Comment by EntonyEscX** [comment]
@PMelol Me too, almost once an hour at a minimum.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
