### ISSUE TITLE
[Party Spoilers] Explaining yourself to Monika

### ISSUE THREAD

**Issue by Tiler17** [Monika-After-Story/MonikaModDev#2512]
This isn't really a serious post, but I felt one of the gifts I gave Monika today needed a proper explanation. Y'all know the one.

I've gotten gifts for people who didn't quite know what to make of it, and explaining them is sometimes necessary. When I saw "knife" on her wishlist, I was hesitant about giving it to her, because...why would I? But I thought about it for a few seconds, and it made total sense

M: Is that...a knife?
M: Why would you give me that?

T: Well, Monika, how do you plan on cutting your cake?

M: Oh! That makes sense, I hadn't even thought of that? Did you get me a fork as well?

T: Well, hey now, I can't think of everything. Unfortunately, you'll have to eat with your hands, but at least it'll be more manageable pieces than just eating a whole cake without utensils.

We should've given her forks and a plate too.

Anyway, I honest to God thought the knife had an actual purpose. I didn't mean to piss her off with it. I'm hoping for a one time topic where she realizes that the knife I gave her has a purpose in cutting the cake she saved for later. Maybe there's one planned already, but if there isn't, the conditions to write a piece like that are a little beyond me. I dunno how to write a one-off topic dependent on whether or not you gave her a knife. Perhaps a greeting as though she tried to eat the cake after you leave, and found it much easier with the knife. ~inb4 that's actually in the game and I just haven't seen it yet for not having left her alone~ Though she did say she won't take it

**Comment by Professor-JMO** [comment]
~It's a _very_ sharp knife.~

**Comment by peter23247** [comment]
i thought exactly the same
