### ISSUE TITLE
Where do I find the party supplies?

### ISSUE THREAD

**Issue by LightFright** [Monika-After-Story/MonikaModDev#2515]
The title is self explanatory. I just need help finding the cake, balloons, etc. files.

**Comment by DbzGOD2000** [comment]
here, just download the partsupplies.zip
https://github.com/Monika-After-Story/MonikaModDev/releases

**Comment by LightFright** [comment]
> here, just download the partsupplies.zip
> https://github.com/Monika-After-Story/MonikaModDev/releases
> 
> follow this thread on how to do the party supplies. #2480

Thanks.

**Comment by DbzGOD2000** [comment]
np
