### ISSUE TITLE
[Minor Issue] Monika's dialogue doesn't change when you ask her "When is your birthday?" on her birthday

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#2516]
What it says in the title. Was hoping for something like... "What do you mean 'When is your birthday?' You just gave me cake and a bunch of gifts. Ehehehe... silly [player]. I mean, sure I only recently learned that it was today... etc... " then continue into the rest of the normal dialogue or something.

Just thought it was funny is all.

Of course, I'd also expect dialogue to change if you haven't yet done anything for her on her birthday and you ask her... ~~but I'll let someone else imagine disappointed Monika's dialogue~~

But also, I figure her answer to this question might want to change now that we've celebrated (or forgotten to celebrate) with her.

**Comment by ThePotatoGuy** [comment]
[closing until we look at this]
