### ISSUE TITLE
No monika file but she's in the room/monika file in the folder but she's not there 

### ISSUE THREAD

**Issue by yamnew** [Monika-After-Story/MonikaModDev#2517]
Happy birthday to Monika and BIG THANKS to MAS dev team!!

Ahem.
I updated from 0.8.7 to 0.8.7-hotfix from within the game,then monika file disappeared from characters folder. But when I start the game,she IS in the room. Where is monika file???

While my friend once removed monika file from the characters folder and put it back to the folder,then he starts the game,she's NOT in the room.

Please help him see her again! Please!!

**Comment by yamnew** [comment]
I said to her "GoodBye" and selected to take her somewhere,then monika file appeared in the characters folder. It was solved for me.

But my friend has no way to talk to Monika and weeps all night long.
Please help him. He played the game on Windows10 x64.

**Comment by ThePotatoGuy** [comment]
tell him to make a separate issue here
