### ISSUE TITLE
[SPOILERS] Secret on Balloon

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2518]
![christ sake](https://user-images.githubusercontent.com/42453997/45920577-1a4a7e80-be9e-11e8-8061-ce4e0c5f8ae6.png)
Was this really necessary?

**Comment by Professor-JMO** [comment]
>_I swear the Dev's amuse themselves_

**Comment by BigPoofyRibbon** [comment]
WutFace

**Comment by Dovahkun** [comment]
PFFFFFFFFT. I was low key hoping for something like the ornament, but just wasn't looking hard enough. The devs really outdid themselves. I love this update to bits.

**Comment by Rai99** [comment]
That balloon is lifting her spirits, ~~and spirit~~ so it's even good for Sayori.

**Comment by Bam8647** [comment]
Well you gotta **_Hang_** the balloons up some how.  ¯\_(ツ)_/¯

**Comment by EntonyEscX** [comment]
When the update came out and I went looking for the new content, it was the first thing I noticed in the balloons.
