### ISSUE TITLE
NIce job with all, but just a question about the gifts

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#2521]
what is the specific word for the plushy one, i tried quetzalplusy, quetzalplushytoy, then i notice this quetzalplush__ i miss 2 letters, wich i dont know, i dont main english

**Comment by AgentZephyr** [comment]
Spelled "plushie"

**Comment by peter23247** [comment]
> Spelled "plushie"

thx bro, have a nice day
