### ISSUE TITLE
How to use a persistent file?

### ISSUE THREAD

**Issue by HexenVexen** [Monika-After-Story/MonikaModDev#2522]
I accidentally deleted my entire folder for MAS, however apparently I can get my progress back with the persistent files found in AppData/Renpy (I'm on windows.) However, I have no clue what to do with these, so how do I use them?

**Comment by ThePotatoGuy** [comment]
see [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-my-persistent)

**Comment by HexenVexen** [comment]
It worked, thanks.
