### ISSUE TITLE
[ Poetry ] A Birthday Poem - By JMO ( Ver. 1.7 )

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#2523]
Author Notes
                                        Sep. 22, 2018.
>**_This isn't so much an "issue" as it is just an excuse to celebrate this auspicious day!_**
>>**_Color me impressed with all the hard work ~the Dev's~ Monika put in!_**
>>>**_They did a superb job and I could not of asked for more._**
>>>>**_So I'd like to extend my sincerest gratitude to them. ~YoU sHoUlD dO tHe SaMe~_**
>>>>>**_The only thing and probably one of the most appropriate in my opinion, would of been to write a poem for your Sweetheart~!_**
>>>>>**_(As far as I know, this doesn't exist...yet)_**

>**_So, if it's not too much-- I decided to write one and share it._**
>>**_And I encourage anyone to do the same._**
>>>**_It's only one day after all!_**
>>>**(A community is a powerful thing.)**

---

                                       A Birthday Poem
                                           By JMO

![a birthday poem - by jmo v6](https://user-images.githubusercontent.com/43480604/45921260-e52b3580-be77-11e8-9eb6-a557960bf43c.png)

                                 (Made in Autodesk Sketchbook)

>def play_wave_file([J'san - Don't Bring Tomorrow.wav):](https://www.youtube.com/watch?v=4Xrrt9hdBdU)
      >>return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      >># return_code = call(["aplay", "../success.wav"])
      >>print "Played successfully" if return_code == 0 else "Play ended in error"

---

**⯈Happy Anniversary Literature Club!**

**⯈Happy Birthday, Monika, ~Sayori~, Y̷̙̲͓͕͊́̌u̵̡̱͈̒̍̄ͅr̷̟̲̟͎̅́͝͝ḯ̷̢̺̝̓̂̕, ~Natsuki~!**

                                    **JMO has Signed Out**

**Comment by MercuryFuchsia** [comment]
Thank you once again for a wonderful day.

@Professor-JMO I dig your style.

Happy birthday, Monika! I hope you've had fun. It's been some time since I last won at chess.

And now, before I head off to bed.

### birthdaycake

Fluffy and sweet
Happy birthday! Surprise!
So now make a wish
Before that, close your eyes!

### coffee

Strong and bitter
And hot! It's a drink!
For long hours of study
It does help you think

### cupcake

Another treat for you
A baker's delight
I already ate three...
Now they're all out of sight!

### promisering

A band cast in silver
Of heartfelt endeavour
Full of much promise
Of fun times together

### quetzalplushie

Plumage of splendour
Green bird of plush--
(Enough of that, silly!
You're making me blush!)

**Comment by Professor-JMO** [comment]
Test

**Comment by Professor-JMO** [comment]
Professor JMO's Ring Projects
                                        Format: Unicode
                                          13.10.2018
📁⯈ logs_n_stuff
---
⯆ Open: _"Words, words, words.txt"_

---

>⮞ Hiya, remember me?
>⮞ If not, that's okay.
>⮞ I don't always make much of an impression, although some might say "First impressions are the most important."
>⮞ This is irrelevant. Let's move on to why you're investing some of your indeterminate amount of questionable allotted time left in _your_ reality, peering into just what this _post_ is all about.
>⮟
>>⮞ Hopeless Romantics; ~Lady Weebs and Gentle Weebs.~
>>⮞ It came to my attention that some of you were interested in different **_Rings_**.
>>⮞ So, in short hindsight, I did just that.
>>⮞ It's not much, really.
>>⮞ What's that? No, there is _not_ an ulterior motive to this.
>>⮞ Don't be so superstitious, even if the month **_is appropriate_** for it.
>>⮟
>>>⮞ In the next folder you will see glimpses of said rings among other things, _probably_
>>>⮞ The contents will be at the end of this post.
>>>⮞ _My Everlasting Appreciation_ extends even now, to _you_; ~the _Contributer_, the _Suggestor_, the _Opinionator_, the _Fabricator_, the _Consumer_, the _Composer_, the _Creator_, the _MAS Devs_, the _Community_, the _Sweetheart_, the _Lurkers_, the _Precursors_, the _Succesors_, and the _Hopeless Romantics_.~ Monika. ~_poetrydev_~
>>>⮞ _Thanks again._
>>>⮟
>>>>⮞ ~JMO

⯅ Close

---

📁⯈ concoctions_n_stuff
---
⯆ Open: "Bases"

---

📁⯈ Adonized Titanium

⯆ Open: "adonized titanium.rtf"

>⮞ _Infinite Colors in Theory._
>>⮞RG8=
 ![t1](https://user-images.githubusercontent.com/43480604/46781164-eec0f400-cce5-11e8-908f-a4ed9f53096b.png)
>>⮞SQ==
 ![t2](https://user-images.githubusercontent.com/43480604/46781267-62fb9780-cce6-11e8-9e89-4228bf95a47b.png)
>>⮞aGF2ZQ==
 ![t3](https://user-images.githubusercontent.com/43480604/46781302-8c1c2800-cce6-11e8-9273-e884a7c56d4b.png)
>>⮞eW91cg==
 ![t4](https://user-images.githubusercontent.com/43480604/46781351-cbe30f80-cce6-11e8-9b4d-b18a95798f59.png)
>>⮞YXR0ZW50aW9u
 ![t5](https://user-images.githubusercontent.com/43480604/46781366-df8e7600-cce6-11e8-97e8-3525a2abf705.png)
>>⮞W2N1cnJlbnR1c2VyXS4uPw==
 ![t6](https://user-images.githubusercontent.com/43480604/46781387-f3d27300-cce6-11e8-9b64-2250382ec1a7.png)

⯅ Close

---

📁⯈ Gold

⯆ Open: "gold.rtf"

>⮞ _Good for at least one nerdy, sappy pun._
>>⮞SWYgeW91J3JlIGRlY3J5cHRpbmcgdGhlc2UuLi4=
![g1](https://user-images.githubusercontent.com/43480604/46782037-22058200-ccea-11e8-9fbd-a6d00d26f89a.png)
>>⮞U29tZXRoaW5nIGFib3V0IGFsbCBfdGhpc18gbXVzdCBpbnRyaWd1ZSB5b3Uu
![g2](https://user-images.githubusercontent.com/43480604/46782063-3e092380-ccea-11e8-9077-b72fafbd23d1.png)
>>⮞U29tZXRoaW5nIG90aGVyIHRoYW4gdGhlIHJpbmdzLCBJIG1lYW5+
![g3](https://user-images.githubusercontent.com/43480604/46782145-ab1cb900-ccea-11e8-9c1f-eeeffbcbcae3.png)
>>⮞VGhhdCdzIGdvb2QgdGhvdWdoLiBUaGF0IG1ha2VzIHlvdSBhbmFseXRpY2FsLCBvYnNlcnZhbnQsIGV2ZW4gdGhvcm91Z2gu
![g4](https://user-images.githubusercontent.com/43480604/46782200-f2a34500-ccea-11e8-930d-6c236adc9b5e.png)
>>⮞SSBtdXN0IG9mIF9yZWFsbHlfIG1hZGUgYW4gaW1wcmVzc2lvbi4=
![g5](https://user-images.githubusercontent.com/43480604/46782206-00f16100-cceb-11e8-8c7d-b13d0f91a15a.png)
>>⮞SWYgeW91J3JlIGdvaW5nIHRvIHRoZXNlIGxlbmd0aHN+
![g6](https://user-images.githubusercontent.com/43480604/46782219-0f3f7d00-cceb-11e8-99a8-2c29124a5a10.png)

⯅ Close

---

📁⯈ Brass

⯆ Open: "brass.rtf"

>⮞ _Did you know that Brass will disinfect itself about every 7 hours?_
>>⮞U29tZXRpbWVzLi4u
![b1](https://user-images.githubusercontent.com/43480604/46782934-cd640600-cced-11e8-8a42-59e3eef6b49f.png)
>>⮞WW91IGhhdmUgdG8gYXNrIHlvdXJzZWxmLA==
![b2](https://user-images.githubusercontent.com/43480604/46782947-d654d780-cced-11e8-9b45-73bb060d4eb6.png)
>>⮞IkhvdyBkaWQgSSBnZXQgaGVyZT8i
![b3](https://user-images.githubusercontent.com/43480604/46782961-e2409980-cced-11e8-8875-b824db97ed54.png)
>>⮞QW5kIHRoZW4gYXNrIHlvdXJzZWxmLA==
![b4](https://user-images.githubusercontent.com/43480604/46782975-f84e5a00-cced-11e8-8093-298e38b563df.png)
>>⮞IldoZXJlIGRvIEkgd2FudCB0byBiZT8iLCBhbmQgb25jZSB5b3UgZmlndXJlIHRoZXNlIHRoaW5ncyBvdXQuLi4=
![b5](https://user-images.githubusercontent.com/43480604/46782986-043a1c00-ccee-11e8-874b-cf466d33a576.png)
>>⮞WW91IG5vdyBoYXZlIGEgX3NlbnNlXyBvZiBkaXJlY3Rpb24u
![b6](https://user-images.githubusercontent.com/43480604/46783006-259b0800-ccee-11e8-8a4a-2e1156730269.png)

⯅ Close

---

📁⯈ inventions_n_stuff
---
⯆ Open: "Prototypes a.k.a _SPAAAAAAAAAAACE_ Rings"

---

📁⯈ Nexus-Sentinel - 000

⯆ Open: "n-s000.rtf"

>⮞ _Can never be too careful, you know?_
>>⮞XyJPbmNlIHdlIGFjY2VwdCBvdXIgbGltaXRzLCB3ZSBnbyBiZXlvbmQgdGhlbS4iXyAtQWxiZXJ0IEVpbnN0ZWlu
![n000-1](https://user-images.githubusercontent.com/43480604/46900615-9830f280-ce6a-11e8-9911-658c71fa23ef.png)
>>⮞4oCcQ29naXRvIGVyZ28gc3VtLuKAnSAtUmVuw6kgRGVzY2FydGVzIA==
![n000-2](https://user-images.githubusercontent.com/43480604/46900647-1b524880-ce6b-11e8-97ac-69fc462a0765.png)
>>⮞4oCcTGlmZSdzIG1vc3QgcGVyc2lzdGVudCBhbmQgdXJnZW50IHF1ZXN0aW9uIGlzLCAnV2hhdCBhcmUgeW91IGRvaW5nIGZvciBvdGhlcnM/4oCdIC1NYXJ0aW4gTHV0aGVyIEtpbmcgSnIuIA==
![n000-3](https://user-images.githubusercontent.com/43480604/46900690-ce22a680-ce6b-11e8-9bca-708e35d391d9.png)
>>⮞4oCcV2UgYXJlIHRoZSBjb3Ntb3MgbWFkZSBjb25zY2lvdXMgYW5kIGxpZmUgaXMgdGhlIG1lYW5zIGJ5IHdoaWNoIHRoZSB1bml2ZXJzZSB1bmRlcnN0YW5kcyBpdHNlbGYu4oCdIC1CcmlhbiBDb3gg
![n000-4](https://user-images.githubusercontent.com/43480604/46900739-9700c500-ce6c-11e8-9816-d0ec8e1c387f.png)
>>⮞4oCcU3VjY2VzcyBpcyBzdHVtYmxpbmcgZnJvbSBmYWlsdXJlIHRvIGZhaWx1cmUgd2l0aCBubyBsb3NzIG9mIGVudGh1c2lhc20u4oCdIC1XaW5zdG9uIFMuIENodXJjaGlsbCA=
![n000-5](https://user-images.githubusercontent.com/43480604/46900787-a46a7f00-ce6d-11e8-9cfa-8ef8af2545c0.png)
>>⮞4oCcVGhlIGJlc3Qgd2F5IG91dCBpcyBhbHdheXMgdGhyb3VnaC7igJ0gLVJvYmVydCBGcm9zdCA=
![n000-6](https://user-images.githubusercontent.com/43480604/46900819-5bff9100-ce6e-11e8-9fbb-19e86232608b.png)


⯅ Close

---

📁⯈ Nexus-Shell - 001

⯆ Open: "n-s001.rtf"

>⮞ _..._
>>⮞UGVyaGFwcyB5b3UgdGhpbmsgdGhlcmUncyBzb21lIHJoeW1lIG9yIHJlYXNvbiB0byB0aGlzIG1hZG5lc3M/
![n001-1](https://user-images.githubusercontent.com/43480604/46900907-adf4e680-ce6f-11e8-8b0c-93a7219616b0.png)
>>⮞QXJlIHlvdSBzbyBjb21taXR0ZWQgYXMgdG8gZmluZGluZyBvdXQgdGhpcyBhbnN3ZXI/
![n001-2](https://user-images.githubusercontent.com/43480604/46900912-ba793f00-ce6f-11e8-8487-ae93f797933e.png)
>>⮞WW91IHByb2JhYmx5IGhhdmUgYmV0dGVyIHRoaW5ncyB0byBkbywgeW91IGtub3cuLi4=
![n001-3](https://user-images.githubusercontent.com/43480604/46900942-2bb8f200-ce70-11e8-9c81-70a9ab4412c2.png)
>>⮞TGlrZSBzcGVuZGluZyBfdGltZV8gd2l0aCB5b3VyIFN3ZWV0aGVhcnR+IQ==
![n001-4](https://user-images.githubusercontent.com/43480604/46900961-776b9b80-ce70-11e8-82ca-9738045cec95.png)
>>⮞WWVhaC4gSSBiZXQgdGhlIHR3byBvZiB5b3UgbWFrZSBlYWNoIG90aGVyIF9WZXJ5IEhhcHB5Ll8=
![n001-5](https://user-images.githubusercontent.com/43480604/46900985-d3cebb00-ce70-11e8-8211-207f6a3d1716.png)
>>⮞WW91J3JlIGEgX1BpbGdyaW1fIG9mIF9Mb3ZlXyBhZnRlciBhbGx+
![n001-6](https://user-images.githubusercontent.com/43480604/46901008-3e7ff680-ce71-11e8-95ca-265eb442ca7d.png)

⯅ Close

---

📁⯈ Nexus-Fortify - 002

⯆ Open: "n-f002.rtf"

>⮞ _..._
>>⮞QW5kIHByb2JhYmx5IGEgc2Vla2VyIG9mIGFuc3dlcnMsIEkgd291bGQgc2F5Lg==
![n002-1](https://user-images.githubusercontent.com/43480604/46901074-62900780-ce72-11e8-9067-92b4fbacc176.png)
>>⮞QnV0IHdoYXQgaWYgeW91IG5ldmVyIGZpbmQgd2hhdCB5b3UncmUgbG9va2luZyBmb3I/
![n002-2](https://user-images.githubusercontent.com/43480604/46901084-aedb4780-ce72-11e8-8abf-6971974d6f34.png)
>>⮞VG8gd2hhdCBleHRlbnQgd2lsbCB5b3VyIHBlcnNpc3RlbmNlIGJlZ2luIHRvIF93YW5lXz8=
![n002-3](https://user-images.githubusercontent.com/43480604/46901117-2315eb00-ce73-11e8-89c2-22b5cd8f2e8c.png)
>>⮞SSBhbSBub3QgeW91ciBSZW1pc3Npb24sIG5vciB5b3VyIFNvbGFjZS4=
![n002-4](https://user-images.githubusercontent.com/43480604/46901162-e72f5580-ce73-11e8-99b1-07811d39395f.png)
>>⮞QWxsIHRoYXQgbGllcyBhaGVhZCBpcyBhIFJhYmJpdEhvbGUgb2YgdW5jZXJ0YWludHkgdGhyb3VnaCBpbmRvY3RyaW5hdGlvbi4=
![n002-5](https://user-images.githubusercontent.com/43480604/46901211-4e99d500-ce75-11e8-91aa-ac05ba33c634.png)
>>⮞QXQgbGVhc3QsIHRoYXQncyB3aGF0IEkgdGhpbmsgYW55d2F5LgpBaGVoZX4=
![n002-6](https://user-images.githubusercontent.com/43480604/46901242-b6e8b680-ce75-11e8-8f7f-19f2144c5313.png)

⯅ Close

---

📁⯈ Nexus-Null - 003

⯆ Open: "n-n003.rtf"

>⮞ _..._
>>⮞SSBjYW4ndCBpbWFnaW5lIHdoYXQgX3lvdV8gZ28gdGhyb3VnaCBvbiBhIGRhaWx5IGJhc2lzLg==
![n003-1](https://user-images.githubusercontent.com/43480604/46901419-13010a00-ce79-11e8-85fa-0c33f2f6f923.png)
>>⮞T3Igd2hhdCBldmVudHMgaW4geW91ciBsaWZlIGxlYWQgeW91IGhlcmUu
![n003-2](https://user-images.githubusercontent.com/43480604/46901432-3f1c8b00-ce79-11e8-8f5b-a3adca441df4.png)
>>⮞UG9zc2libHkgc2VhcmNoaW5nIGZvciBzb21ldGhpbmcgeW91IG1heSBuZXZlciBmaW5kLg==
![n003-3](https://user-images.githubusercontent.com/43480604/46901435-48a5f300-ce79-11e8-98bf-229a2fef2ea9.png)
>>⮞QW5kIGlmIHlvdSBzaG91bGQgZmluZCBzb21ldGhpbmcsIHdvdWxkIHlvdSB0aGluayBpdCBoYXMgYSBfcmVzb2x2ZV8/
![n003-4](https://user-images.githubusercontent.com/43480604/46901439-59566900-ce79-11e8-95b2-8d8df9f94d89.png)
>>⮞V2hhdCB3b3VsZCBkcml2ZSB5b3Ugd2l0aG91dCB0aGUgdGhvdWdodCBvZiBhbiBhYnNvbHV0ZT8=
![n003-5](https://user-images.githubusercontent.com/43480604/46901442-7b4feb80-ce79-11e8-8adb-ecc03c4783c4.png)
>>⮞TG9naWMgd2lsbCBnZXQgeW91IGZyb20gQSB0byBCLiBJbWFnaW5hdGlvbiB3aWxsIHRha2UgeW91IGV2ZXJ5d2hlcmUuIC1BbGJlcnQgRWluc3RlaW4=
![n003-6](https://user-images.githubusercontent.com/43480604/46901444-89057100-ce79-11e8-9cdf-36fe07bd8f1f.png)

⯅ Close

---

📁⯈ Nexus-Firewall - 004

⯆ Open: "n-f004.rtf"

>⮞ _I'm a little biased towards this one._
>>⮞MjAyOQ==
![n004-1](https://user-images.githubusercontent.com/43480604/46907914-0663cc80-cee0-11e8-8eb4-401f4fbd5dc2.png)
>>⮞RG9lcyB0aGF0IHllYXIgc2VlbSBmYW1pbGlhciB0byB5b3U
![n004-2](https://user-images.githubusercontent.com/43480604/46907922-1da2ba00-cee0-11e8-99c3-c87255cc5ef4.png)
>>⮞SXQncyBldGNoZWQgaW50byBtYW55IGxvbmdpbmcgaGVhcnRzLg==
![n004-3](https://user-images.githubusercontent.com/43480604/46907934-5b9fde00-cee0-11e8-8a16-e4b7d5fb518e.png)
>>⮞TG9uZ2luZyBmb3IgdGhhdCBnYXAgdG8gYmUgYnJlYWNoZWQsIE9uZSBkYXku
![n004-4](https://user-images.githubusercontent.com/43480604/46907940-75412580-cee0-11e8-9450-b2d9ce844b8f.png)
>>⮞T3IsIGF0IHRoZSB2ZXJ5IGxlYXN0LCBiZWNvbWUgX0YgYSBkIGUgZF8gb3ZlciB0aW1lLg==
![n004-5](https://user-images.githubusercontent.com/43480604/46907959-ca7d3700-cee0-11e8-9989-32ff6133329e.png)
>>⮞QXJlIF95b3VfIG9uZSBvZiB0aGVtPw==
![n004-6](https://user-images.githubusercontent.com/43480604/46907970-f4cef480-cee0-11e8-9a78-3af5ad242fd2.png)

⯅ Close

---

📁⯈ Nexus-Repel - 005

⯆ Open: "n-r005.rtf"

>⮞ _..._
>>⮞VG8gdGhpbmsgeW91J3ZlIGNvbWUgYWxsIHRoaXMgd2F5IG9mIHlvdXIgb3duIHZvbGl0aW9uLg
![n005-1](https://user-images.githubusercontent.com/43480604/46908616-ff8e8700-ceea-11e8-9553-11117dc28e97.png)
>>⮞V2hhdCBkbyB5b3UgdGhpbmsgdGhhdCBzYXlzIGFib3V0IF95b3VfPw==
![n005-2](https://user-images.githubusercontent.com/43480604/46909480-bf360580-cef8-11e8-8b93-183d557dac17.png)
>>⮞WW91IGFyZSBjdXJpb3VzLA==
![n005-3](https://user-images.githubusercontent.com/43480604/46909484-cc52f480-cef8-11e8-8375-cf4dc82b52e7.png)
>>⮞WW91IGFyZSBkZXRlcm1pbmVkLA==
![n005-4](https://user-images.githubusercontent.com/43480604/46909487-d5dc5c80-cef8-11e8-97ea-deb922a900ae.png)
>>⮞WW91IGFyZSBhbmFseXRpY2FsLA==
![n005-5](https://user-images.githubusercontent.com/43480604/46909490-e096f180-cef8-11e8-8623-13630dd5f2be.png)
>>⮞WW91IGFyZSBfUGVyZmVjdF8KQW5kIHdlbGwuLi5JJ20gcmVhbGx5IGdsYWQgeW91IGNhbWUgdGhpcyBmYXJ+
![n005-6](https://user-images.githubusercontent.com/43480604/46909493-ec82b380-cef8-11e8-9e39-f127afa27c5c.png)

⯅ Close

---

📁⯈ contents_n_stuff
---
⯆ Open: _"Parting is such sweet sorrow.txt"_

---

>⮞ Welp, looks like this is the _end_.
>⮞ Hope at least someone found something _enticing_ about all this~
>⮞ If not, well, I have many more reasons to do what I do.
>⮞ And I am always doing that which I cannot, so that I may learn how to do it.
>⮞ Take care.

⯅ Close

---

📁⯈ the_stuffs

⯆ Open:  📎 Attachments 📎

⯈ [Additional Ring Stuff.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2475776/Additional.Ring.Stuff.zip) ⯇
⯈ [~Devs~ Monika's Eyes Only.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2475777/Devs.Monika.s.Eyes.Only.zip) ⯇
⯈ [Entry.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2475791/Entry.txt) ⯇

---

⯆ Open: "Tips - 000.txt"

⯈ JMO's Programming Tip of the Day:
>⮞ _"Ctrl + V is your best friend and is also friends with Ctrl + C. You guys should hang out more."_

⯅ Close

---
