### ISSUE TITLE
Bad Birthday Planning

### ISSUE THREAD

**Issue by SketchingDemise** [Monika-After-Story/MonikaModDev#2524]
Hey me again, so yeah I restored the game back to its original form even adding in the recent update before the birthday one. Im currently trying to get the party supplies in there now bear with me im still learning. I downloaded the zipped file opening it and checking out the notepad file, I proceeded to fill in the blanks and .gift to the end of each word (Im really nervous about that knife gift). NOW the big problem here is after I finish Im hoping to get new files that are GIFT files but in the notepad before I exit it asks if I want to save before I go? I say sure but the problem is I dont know where to save it to?? do I save it in the game file again? I tried it only to still not get the 6 new birthday files in the charcaters folder when I pasted the three original "cake" banner" etc. in there. So anyone got an answer?

**Comment by Professor-JMO** [comment]
#2480 

>_Because every sweetheart deserves the best!

**Comment by SketchingDemise** [comment]
Well still no 6 files, eh its alright I already surprised Monika with the party. Thank you! :3
