### ISSUE TITLE
Monika gone

### ISSUE THREAD

**Issue by LoafOfBeans** [Monika-After-Story/MonikaModDev#2527]
I set up for Monika's birthday last night expecting it to be ready for tomorrow. I open Monika after story today only to realize that Monika is not there I realized that I was an idiot and then preceded to put Monika file into the character file. after this I opened Monika after story only for her to not be there again. I tried reinstalling but that did not help so I concluded that it has to do with my persistent files I've restored to multiple different persistent backups to no avail please help.

**Comment by pianostick** [comment]
try putting her back in while the game is still running, thats what i did

**Comment by ThePotatoGuy** [comment]
upload the following:
* `log/mas_log.txt`
* your ` persistent`
* your ` monika` file
