### ISSUE TITLE
Monika is not wearing her promise ring and her coffee and plushie is nowhere to be seen.

### ISSUE THREAD

**Issue by Racterr** [Monika-After-Story/MonikaModDev#2528]
My MAS crashed because the electricity in my house went off and when I opened the game again, what I said in the title happened, I wanted to know if this is normal or not, I really liked when she was wearing the ring and the other gifts.

**Comment by pianostick** [comment]
i went to sleep and when i opened the game back up the plush was gone but she was still wearing the ring.  also she made coffee again later in the day after i pressed "i love you", maybe you need to take her and the gifts out and put the gifts back in before her

**Comment by Racterr** [comment]
Nevermind, I put a persistent file before the birthday party and the gifts, repeated everything once again and I think I fixed, sorry to bother you.
