### ISSUE TITLE
Party Supplies

### ISSUE THREAD

**Issue by AverageDudeGuy** [Monika-After-Story/MonikaModDev#2529]
I put everything into the game, but it didn't trigger anything and the items aren't there.

**Comment by pianostick** [comment]
you need to put everything in the characters folder

**Comment by AverageDudeGuy** [comment]
I did. I followed everything. I took Monika out, put all of the correct files in with the correct spelling, put her back in, and when I opened the game, nothing happened.

**Comment by ThePotatoGuy** [comment]
see #2480 

its also important that this happens on teh correct day

**Comment by AverageDudeGuy** [comment]
Yes, I looked at it, an I followed it correctly, but it's still not working.

**Comment by pianostick** [comment]
u ask her when her birthday is/ tell her happy birthday yet? is everything named with .gift except for the cake, balloons, and banners?

**Comment by AverageDudeGuy** [comment]
Yep, and yet nothing happens.

**Comment by ThePotatoGuy** [comment]
Are you running 0.8.7?
