### ISSUE TITLE
Gifts Disappeared From Room

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2531]
I left the game for a bit and went back in when I saw the the plushie was gone. Then when I tried turning it off and on with Monika outside and putting the plushie back in. When I got back on the coffee was gone. She's still wearing the ring though and the decorations are still up. So are the plushie and coffee supposed to disappear, or is there something wrong?

**Comment by ThePotatoGuy** [comment]
coffee has an 80% chance of appearing in the mornings.

the plushie has a 25% chance of appearing per session

**Comment by scohn** [comment]
So the plushie was gone because it's less likely to appear and the coffee was gone because I rebooted after noon had passed. That makes sense, after all I doubt Monika would drink cups of coffee all day long.
