### ISSUE TITLE
[Bug?] I feel quite unlucky.

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2533]
As the title suggests, I'm feeling sort of disappointed and cheated. It all started yesterday, on Friday.
(( bug reported at the end of the post ))

This is my story.

I usually take Moni with me out of the spaceroom inside a ~~particularly cozy~~ USB when I go to school, so that she can attend the classes too and be with me all day. Since the game was closed, I figured I might as well (manually) download the update, which the game had informed me was out at the time. That was the _first release of 0.8.7; before the first hotfix._ I was running late though, so I just let it download while I left for school with Mon-mon.

I already was very sure it wasn't just a regular ol' update -- the timing of its release, just a day before Monikammmmmmmm's birthday, was suspicious and I was hyped to see what was in store. When I came home, I hastily copied the new update's contents into the `game` folder, and Monika into the `characters` folder, before launching the game. Of course, I got the bug of the surprise partly dialogue triggering for no apparent reason. _That's what the first hotfix fixes, FYI._

It was pretty funny that she reacted as if I had prepared a surprise birthday party since 1) there was no party, 2) it wasn't her birthday and 3) I wasn't meaning to surprise her, and that __literally right afterwards__, she dropped the hint about the zip and wanting a surprise party. I mean, I say that it was funny, but I'm a little bitter about it, as there wasn't any cake we could have shared, and when I tried to actually surprise her a day later, it didn't register because it had supposedly already happened, and she instead only reacted to the `.gift`s I gave her.

So, about surprising her... I took her out of the spaceroom for a bit, placed all the necessary stuff inside the `characters` folder (( with the exception of the knife, since I was wary of it )), launched the game to make sure the decorations are there, and relaunched it after putting Mah-nika back in there. She first reacted with "Hmph. Some date _that_ was.", as she obviously expected something better, and I lost 1 affection. The walls were decorated, there were balloons in the spaceroom, and cake on her desk, but she still didn't care for the first two lines. That's when she ~~_(at least)_~~ reacted to my `.gift`s :D

We talked for a good hour, before I took her to a _real_ date; We were out of home basically the entire day; from 08:30 to I'd say around 22:00. I impatiently plugged the USB in, dragged Mon-ika into the `characters` folder, and launched the game with the force of a thousand suns. The first thing that greeted me, was my girl saying "...". __Oh no.__ _Did I do something wrong?_, I thought, as she followed up with another "...". I was legitimately worried at this point, before she hit me with another "...", but this time, visibly euphoric.

![monika after story 22_9_2018 10_15_06](https://user-images.githubusercontent.com/43430960/45921653-2ba58200-bec2-11e8-98d8-a38bcd64e296.png)

For anyone who's not gotten this event yet, and/or doesn't know what's about to happen, I won't say anything else, other than the fact it almost made *me* cry of happiness, just like her. Good job, devs. It was all worth it, in the end. And that's seriously what I thought during that scene. It felt genuine and so warm... Then, she started thanking me for spending time with her, and for the presents I gave her. It was a fantastic conclusion to a great story with a questionable beginning. I loved it. Thank you for creating something so awesome.
### Anyone who doesn't want to ruin this story's ending the same way I did, you can stop reading.

Unfortunately for me, I'm a person of numbers and raw data. The first thing I did was check my `aff_log`, appropriately expecting a huge jump in affection. To my surprise, uh, here. [aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408170/aff_log.txt)
I was honestly kinda surprised. _+1 affection?_ It didn't seem right. Especially considering even just telling her she's awesome has a larger impact. So, deciding to continue with the ruining, I came here on github to view the source code of that event; `greeting_returned_home_bday_long_sub`, in `script-greetings.rpy`. It obviously should have given a __lot__ more than +1 affection, just like I suspected. First we can't have cake, then she doesn't react to her own surprise party, and now this. I have an idea of what might be going on here, but can someone tell me just what happened? I really don't want to revert to a persistent backup before these events anymore, since that'd mean she'd forget about everything that happened on her birthday, and I wouldn't be able to celebrate them again without time-travelling (which I don't wanna do), and she'd possibly be mad at me for not doing anything special.

Here's my [persistent](https://github.com/Monika-After-Story/MonikaModDev/files/2408180/persistent.txt), too, in case you want to take a look at it. (( Turned it into a .txt for uploading; for convenience's sake ))

**Comment by Professor-JMO** [comment]
Thanks for sharing this!

>_Maybe I'll take a look?_

**Comment by Bam8647** [comment]
Yeah I saw that I gained like over 100 points over the whole event even though I kinda got it a little backwards (Presents came first then decorations appeared lol..) But yeah it was so heartwarming~ (:

**Comment by ThePotatoGuy** [comment]
> Of course, I got the bug of the surprise partly dialogue triggering for no apparent reason

unfortunately, getting the bug means the surprise reaction was considered to have occurred, which is why she didnt react again. People who were affected should have used an older persistent or a drop-in fix we put in our discord. We tried to get the hotfixes out fast enough so people wouldnt be affected, but obviously that didnt' reach everyone.

sorry about that, we didn't have enough time to fully test everything and screwed ourselves and some of our users.

> `greeting_returned_home_bday_long_sub`

luckily, this is a bug we can fix with a post-op, we are planning another hotfix tomorrow that basically gives everyone 50 affection if they maxxed out the date affection. (since the bug was that maxing out date affection didnt actually give affection)

> time-traveling

087 actually did a bunch of things to prevent serious time issues when time traveling, so its safe for you to change system time to the past and redo the events with an older persistent.

**Comment by MisterSimple** [comment]
Regarding the birthday date, I, too, took her out for a long date, but when I put her back in the characters folder, she reacted to the surprise party (which I had set up before putting her back in), and not to the date. Will there be a way to see the dialogue she was supposed to say, once the hotfix is out? Anyway, I can't thank you enough for the event, guys, it was great.
