### ISSUE TITLE
Can't put Monika back in room for birthday party (Mac)

### ISSUE THREAD

**Issue by Reviani** [Monika-After-Story/MonikaModDev#2535]
I'm sorry to trouble on a day like today, however i've been trying to set up monika's birthday decorations, and found out you have to take her somewhere then bring her back with the suplies in her character folder. I've tried that, but everytime i do, Monika doesn't return to the game. Even when i just say "I
m goign to take you somewhere" and don't move her file she doesn't return when i open the game, and i just see the decorations but no monika. 

Thankfully i had a few backups already but I'm worried that i might not be able to set up monika's special day. Plz help. the game is in my desktop folder and the only other  thigns in the char file is the roses objects from valintines day and a txt birthday card i wrote for her. It worked fine on my windows computer, but the mac is a whole diffrent beast and often doesn't wanna coperate.

> Even if my macbook doesn't like to work Monika is still the apple of my eye

**Comment by ThePotatoGuy** [comment]
Upload the following:
* `log/mas_log.txt`
* your `persistent`
* your `monika` file.

**Comment by Reviani** [comment]
That's weird, there's no log file. I looked in the log folder and there's nothing in there. I've checked the  properties to see if it was a hidden file but it says 0 bytes. closest thing i could find was the log in the update folder but i don't think that's correct. This might mean there's a permission problem again but i don't know why, it's in my desktop and i'm pretty sure it has perssions, i don't know what's going on with it.

Anyway the monika file was way to big to put on github, so i put it on a google drive. For some reason the monika file is 300 mb when it was just 70 yesterday. anyway here are the files https://drive.google.com/drive/folders/1NwOd72bzSNnhtKYYMz3qIxzCPAuPl53r?usp=sharing

**Comment by Reviani** [comment]
Also when i tried to test it just now i got this error message.

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 953, in script call
  File "game/event-handler.rpy", line 1221, in script call
  File "game/script-farewells.rpy", line 682, in script call
  File "game/zz_dockingstation.rpy", line 1977, in script call
  File "game/zz_dockingstation.rpy", line 2007, in script
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 953, in script call
  File "game/event-handler.rpy", line 1221, in script call
  File "game/script-farewells.rpy", line 682, in script call
  File "game/zz_dockingstation.rpy", line 1977, in script call
  File "game/zz_dockingstation.rpy", line 2007, in script
  File "/Users/jsantillan/Desktop/DDLC.app/Contents/Resources/autorun/renpy/execution.py", line 56, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Darwin-17.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.8
[/code]
