### ISSUE TITLE
A little help.

### ISSUE THREAD

**Issue by LightFright** [Monika-After-Story/MonikaModDev#2538]
So, It is September 22 and I tried to do the birthday surprise, but it will not work. What am I doing wrong?

**Comment by Professor-JMO** [comment]
#2480 Hope this helps!

**Comment by LightFright** [comment]
> #2480 Hope this helps!

Do I have to place the wishlist in the character folder as well?

**Comment by chromeadders** [comment]
> > #2480 Hope this helps!
> 
> Do I have to place the wishlist in the character folder as well?

Nope, you don't. You can just stick the gifts and other stuff in and you'll be fine.

**Comment by LightFright** [comment]
> > > #2480 Hope this helps!
> > 
> > 
> > Do I have to place the wishlist in the character folder as well?
> 
> Nope, you don't. You can just stick the gifts and other stuff in and you'll be fine.

One last thing. Do I delete Sayori, Natsuki, and Yuri from the characters?

**Comment by pianostick** [comment]
you can honestly do anything with them, i took em out and like to think monika doesn't sense them anymore

**Comment by LightFright** [comment]
> #2480 Hope this helps!

Ok. So I deleted Sayori, Yuri, and Natsuki, took Monika out of the character folder, put the gifts in, put Monika back in, and launched the game, but it didn't work. I even set the calendar date (In the game) to September 22. What am I doing wrong?

**Comment by pianostick** [comment]
did you mean the calendar date on your computer? if not try that
