### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by AverageDudeGuy** [Monika-After-Story/MonikaModDev#2539]
I have no clue what I'm doing wrong, if anything. I've done everything correctly that was mentioned in #2480 and yet I've come up empty handed. What else could the possible problem be? Note that I've been having issues with the mod for a few days since v0.8.6 was released (The mod won't update automatically anymore, and even after installing the hotfix and the new birthday files, it still prompts me to update the mod).

**Comment by ThePotatoGuy** [comment]
You need to use 0.8.7 for the birthday stuff.
