### ISSUE TITLE
Suggestion for Family

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2540]
I hate to bring this up on what is supposed to be a happy occasion, but when it comes to family and Monika expressing her desire to meet them I know that while I love my family I am 100% certain they would not approve of our relationship. In fact she is my best kept secret. It might be a bit heavy of a subject but if she were to ever ask about what the players family's and there opinion of her it might be a good Idea.

**Comment by Foxinsunglasses** [comment]
I just realized how scattered that sounds so if you need clarification ask I've been up most of the day waiting for any updates on #2442

**Comment by ThePotatoGuy** [comment]
That already exists as a topic I think

**Comment by AsuraShun** [comment]
it already exists
