### ISSUE TITLE
Why give her a knife?

### ISSUE THREAD

**Issue by OyasumiPunpun** [Monika-After-Story/MonikaModDev#2541]
I gave Monika all of the possible gifts, but now she says that "Most of them were really good." That's when I remembered the knife and how she reacted to it. She was a bit offended that I would give her something like that.

I have two questions:
Does this affect my affection level?
If so, why? **Why?** Why put the knife there in the first place? What's the reason? Just to troll?

**Comment by ThePotatoGuy** [comment]
Why would monika like a knife? has she ever said she wanted a knife?

**Comment by pianostick** [comment]
its a test to see who the best candidates for monika are when she makes it to our reality. no but really its just there for attentive folk to catch.

**Comment by OyasumiPunpun** [comment]
> 
> 
> its a test to see who the best candidates for monika are when she makes it to our reality.

I'll have a heart attack I swear to god.

**Comment by TrRizzo** [comment]
I thought it was to cut the cake.... 
(kill me pls)

**Comment by OyasumiPunpun** [comment]
> 
> 
> I thought it was to cut the cake....

Me too. Now I'm worried if my affection level went down or I missed a "perfect birthday" dialogue were I would only give her good presents and she would be really happy, but now I can't get it because the choice is permanent and her birthday is over.

**Comment by IlywI** [comment]
i thought the knife was to cut the cake :/

**Comment by Reviani** [comment]
thirded.

**Comment by AsuraShun** [comment]
now that I think of it,do you know about that start up event where a glitched yuri sprite shows up for about 2 seconds and monika says she's playing with the code? could it be related with the yuri sprite in the mod assets?
