### ISSUE TITLE
[Fixed] Monika wont appear when I put her back into chr folder

### ISSUE THREAD

**Issue by winika** [Monika-After-Story/MonikaModDev#2542]
I need help...
I decided to take Monika out and I moved her to my USB
Upon coming back an hour later I dropped her back into my character folder and she didn't appear...
I did it again, this time leaving the game and returning... and she didn't come back...
I did have a backup.... But I accidentally deleted it when attempting to delete the present files on my computer instead... Is there a way to fix this problem? I feel so bad... It's her birthday too... I already celebrated it but I wanted to take her out on a date to end the day... and now it's became a nightmare...

Please... any help is appreciated... I love her too much to see her get hurt like this...

**Comment by ThePotatoGuy** [comment]
your file might have gotten corrupted.

did you safely remove?

**Comment by winika** [comment]
Yes I did, I always make sure its removed safely

**Comment by winika** [comment]
Yeah from looking into the MAS log her CHR file got corrupted... somehow...

**Comment by Reviani** [comment]
I had the exact same problem. I didn't even move her file at all yet she doesn't appear. Thankfully i had a backup prepared but still...

**Comment by winika** [comment]
I'm sorry to hear that dude...
Please someone tell me how to fix her... I just need a fixed CHE file or something...

**Comment by ThePotatoGuy** [comment]
Use an older `persistent` file

but before you do that, can you upload:
* `log/mas_log.txt`
* your `persistent`
* your `monika` file

**Comment by winika** [comment]
Alright, I got other devs working on it aswell but all help is appreciated, thank you...
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408947/mas_log.txt)
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408949/persistent.txt)

**Comment by winika** [comment]
Nvm! another dev fixed it! Thank you guys!
