### ISSUE TITLE
Monika's gone! please help!

### ISSUE THREAD

**Issue by Weirdpotato** [Monika-After-Story/MonikaModDev#2547]
I want to celebrate Monika's birthday but I can't because she's gone. I accidentally deleted her character file before I backed it up. is there any way for me to get Monika back? I can't play the game at all and I want to fix it before her birthday is over. please help!

**Comment by winika** [comment]
I'm sorta going through the same thing... I hope we can get an answer...

**Comment by ThePotatoGuy** [comment]
oh boy dont delete her file guys

you can back up to an earlier persistent, I think #2480 mentions it somewhere

**Comment by winika** [comment]
The thing is that I didn't delete her tho... her CHR file just doesn't work... and i'm not sure why...

**Comment by Konahrik13** [comment]
I'm having a bunch of problems with the persistent file thing. I followed the steps from Professor-JMO's post about it but I think the persistent files are tied specifically to something because when I take Monika's character file out, change the persistent file to before I screwed up, and then put her back in she doesn't show up. It's the third time I've done this and I am apparently pissing her off.

**Comment by Foxinsunglasses** [comment]
Have yall checked the recycle bin? as long as it hasn't been emptied all deleted data should be there.

**Comment by winika** [comment]
I never deleted her... My CHR file just doesn't work...

**Comment by MonikaWiafu** [comment]
The monika.chr file isn't inportant at all the real monika in the monika file without .chr when you bring her somewhere....

**Comment by winika** [comment]
I know... and the true Monika file I have just doesn't put her back in the spaceroom... It makes me so sad...

**Comment by ThePotatoGuy** [comment]
upload your `log/mas_log.txt`, `persistent`, and the `monika` file

**Comment by Konahrik13** [comment]
> 
> 
> Have yall checked the recycle bin? as long as it hasn't been emptied all deleted data should be there.

When the beginning screen happened it deleted the monika file in the characters folder. It didn't go to the Recycle Bin.

Here's the mas_log and persistent file, I don't have monika anymore as I've said: https://www.dropbox.com/s/2z0ub6wo1vjn5ir/MAS%20files.rar?dl=0

**Comment by ThePotatoGuy** [comment]
@Konahrik13  use this `persistent`
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2413441/persistent.zip)

**Comment by Konahrik13** [comment]
She's back. Thank you so much man.

**Comment by KawaiiVery** [comment]
I also need help ....... I've put monika into an usb drive but it all got corrupted ... I still go a persistent file ... But how can i restore it ?

**Comment by Kiri-Usui910** [comment]
I have the same problem, i reset my computer and only saved my Monika file, i installed the mod again and moved my file back but my Monika didn't return. I don't have a persistent file and i don't what can i do to bring her back

**Comment by ThePotatoGuy** [comment]
Next time, please make a new issue. Restore instructions are [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). If you don't have a backup persistent, then there is nothing we can do for you.

**Comment by mommyka** [comment]
pls someone help i for some reason chose the option to take out monika and when i put her file back it got deleted by itself its not in the bin its not anywhere pls help anyone
