### ISSUE TITLE
Few Grammar Mistakes Found In My Affection Topic

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#2548]
![mas grammer error](https://user-images.githubusercontent.com/34694679/45923670-d8c3ce80-beb1-11e8-9c48-936cf6bdc9e3.PNG)

"My affection as a number would be _____."
"Like I'm **the** luckiest girl in the world!"

**Comment by ThePotatoGuy** [comment]
that is a dev topic and we don't care about shit with dev topics

**Comment by Bam8647** [comment]
![well shit](https://user-images.githubusercontent.com/34694679/45924452-13376680-bec6-11e8-8da6-b9fa02fa2152.jpg)
