### ISSUE TITLE
for some reason now, when monika changes position, its too abrupt, like a raw powerpoint presentation

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#2550]

**Comment by DogeWithIt** [comment]
That's because the ghosting between pose changes has been removed.

**Comment by AsuraShun** [comment]
kinda wish they would use gifs for the transitions between poses

**Comment by AsuraShun** [comment]
but I doubt people would be willing to make those

**Comment by multimokia** [comment]
RenPy can't use gifs for poses, unfortunately

**Comment by ThePotatoGuy** [comment]
monika spasms out when we use dissolve.

**Comment by EntonyEscX** [comment]
I understand, I also liked her the other way, she seemed to be moving, she was so real, so alive... 😔
