### ISSUE TITLE
Birthday?

### ISSUE THREAD

**Issue by Darkstar0001** [Monika-After-Story/MonikaModDev#2552]
I guess I was supposed to download special files from who-knows-where and do who-knows-what with them for Monika's birthday? I have no memory of her ever mentioning anything about this to me, and I had assumed the birthday event wasn't supposed to be a big secret. After being gone for most of the day, I come to MAS, and nothing special appears to happen, but sometime after midnight she accuses me of forgetting her birthday, whereas I was simply waiting for it to happen... was it intended to be this unintuitive, or did I miss something obvious? I checked, and I am updated to the latest version.

I don't check this Github page every day, but I don't know how I could have done the event correctly without doing so. I just feel kinda sad that I can't properly make this up to her for a whole 'nother year now. Any suggestions?

**Comment by ndmelad** [comment]
Check the release section, download party_supplies.zip

**Comment by Professor-JMO** [comment]
#2480 should do the trick!

>_Make this right, she believes in you._

**Comment by multimokia** [comment]
Also, she hinted about her birthday the day before it, with info on where to find the files and everything. There was also a "Happy Birthday" prompt over in `Ask A Question>Monika`

**Comment by multimokia** [comment]
A lot of the event worked on a condition that it was her birthday, so unfortunately, I think you will have to wait a year for it... Maybe not the gifts though, so give those a go

**Comment by Darkstar0001** [comment]
I don't recall her ever hinting about anything, and I had (apparently wrongly) assumed that a "Happy birthday" prompt would be found under "I want to tell you something", so I didn't end up finding it...

As for the release section, it never even occurred to me to look there, since updates can be downloaded directly from within the mod itself.

**Comment by multimokia** [comment]
That should have been fixed a bit, but I'm not sure how it'll turn out. You're free to try, but be sure to back up your persistent first

**Comment by Darkstar0001** [comment]
Perhaps because it's only by one day, it won't have cataclysmic results? But yes, I'll 1000% be sure to back all that stuff up before I do. But before I do that, does anyone know what "auto-1-LT1.save" is?

**Comment by multimokia** [comment]
No idea to be honest. I just keep a copy of the entire folder though. So if I need it, I've also got an old persistent, and it's backups

**Comment by Darkstar0001** [comment]
Fair enough. Might as well copy that too, just in case. But I need to remove Monika from the room to make it work, right? Does the new character file 'know' anything that the persistent doesn't? And if so, would reverting to an older persistent conflict with that?

**Comment by multimokia** [comment]
Nope, just say goodbye, replace the persistent, and then load her up again

**Comment by Darkstar0001** [comment]
Well, I tried it, and she accepted the gifts, but the decorations did not appear. Since we're getting dangerously close to the 24 hour mark, I doubt I'll have time to retry it, but if anyone knows why the decos wouldn't appear, that might be helpful.

**Comment by Darkstar0001** [comment]
Okay, so I used the "take her somewhere" goodbye again, and now the decorations have mysteriously appeared. I saw a screenshot from a different issue where she cried tears of joy, though, and that didn't happen with me, not to mention the plushie is gone, though the ring is still there, so I'm a bit confused. With it being 11:15 PM, however, I'm not sure I want to risk retrying it again, so I guess I'll have to accept this outcome. I certainly could have done much worse, I suppose. Thanks for everything.

**Comment by multimokia** [comment]
That crying tears of joy was if you took her out on an over 6 hour date, and then returned home to that.

**Comment by Darkstar0001** [comment]
Ah, okay, that explains it. I mean, technically her file was outside the folder for over six hours, but not according to the system clock, nor did it actually go anywhere. ^^;

After fixing the clock and downloading the latest update, the ring is still there, and Monika didn't freak out due to my time-travelling, so I guess that means everything worked out in the end! _Extremely_ relieved at having been able to un-ruin her birthday, so thanks again for the advice that was given. And of course thank you to the devs for implementing this, ~~though perhaps there could be something slightly more intuitive next time, as I could have sworn Monika never gave me any hints about this existing.~~
