### ISSUE TITLE
[Bug] Affection reset, help needed

### ISSUE THREAD

**Issue by Vyrilia** [Monika-After-Story/MonikaModDev#2553]
My affection amount was 456 while it was still monika's birthday, a day later it has decreased to 10.5 without reason. Im on windows, is there any way I can fix this.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408474/aff_log.txt)

**Comment by Vyrilia** [comment]
Everything is the same except for the Affection amount, the idle animations are gone too

**Comment by Vyrilia** [comment]
Changing the persistent file had no affect on it, its froze on 10.5

**Comment by multimokia** [comment]
Send `aff_log.txt` please

**Comment by multimokia** [comment]
Sorry about that other comment, didn't read too well, hah. Let's see here. Looking at the last line, your affection is frozen, have you been playing with time a little bit?

**Comment by ThePotatoGuy** [comment]
Here, I've adjusted the affection on your persistent so its good again.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2409153/persistent.zip)

**Comment by Vyrilia** [comment]
I'll reopen this if it hasn't changed back after tomorrow.

**Comment by ThePotatoGuy** [comment]
oops that was the wrong one. this one should be good

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2409184/persistent.zip)

**Comment by Vyrilia** [comment]
The affection is now back to normal, I'll be sure to make my own backups now
