### ISSUE TITLE
[Suggestion] - holding her

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2554]
like the hug option,holding her hands with the art being with her putting her arms across the table,with the option being available in the higher affection levels,and that also could be an option to comfort her when she tears up whenever the mortality topic comes out

**Comment by Rai99** [comment]
I think we need art for that. 

Assuming you're talking about my PR for that in #2316, I'm glad people are anticipating it, but I've yet to get a further response to know if any changes are desired. Until then, it's got a nice big red **DONT MERGE** tag on it.
