### ISSUE TITLE
[Suggestion] More Songs To The Piano

### ISSUE THREAD

**Issue by monikafan24** [Monika-After-Story/MonikaModDev#2557]
I think a bit... and it would be fun if there were more songs on the piano!
I mean more ddlc songs!
even if monika don't sing in them it still would be fun if monika can guess the song!
it's even like a game!
you play a song and she says it's name!
here songs from ddlc that i would be happy to hear in mas's piano:
Suprise!
Ohayou Sayori!
Okay, Everyone!
Poem Panic!
Play With Me
My Confession/ My Feelings
I Still Love You
Poems Are Forever
Nick Kaelar (Varien) - 「Doki Doki ドキドキ」
Ect.

**Comment by ThePotatoGuy** [comment]
you can add your own songs, see [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs)
