### ISSUE TITLE
little grammatical issue

### ISSUE THREAD

**Issue by niicore** [Monika-After-Story/MonikaModDev#2559]
on the window scenery when you click the farthest left side or something there are lines about adding shrubs and trees.
anyways this is the line that has an error
"Make the islands more prettier you know?"
more prettier is grammatically incorrect
it should be "Make the islands prettier, you know?"
idk if someone else noticed this already or if it is already known but yeah that's that.
also why it's incorrect is because of the fact that prettier is already comparative and adding more to prettier is basically repetitive.

**Comment by jmwall24** [comment]
add that to #2462 please

**Comment by jmwall24** [comment]
actually it's already been pointed out on there. you can safely close this issue
