### ISSUE TITLE
i need help getting somthing to work

### ISSUE THREAD

**Issue by Tuxedoterroist** [Monika-After-Story/MonikaModDev#2562]
i deleted monika's file by accident when trying to set up the birthday party and when i tried to re instal the mod it only works with 8.5 update what do i do to get her back?

**Comment by jmwall24** [comment]
do you have persistent backups from before you took her out?

**Comment by jmwall24** [comment]
also where did you delete her from?  not in the recycling bin?

**Comment by Tuxedoterroist** [comment]
she went into the recycling bin when i pulled her out it dident work

**Comment by winika** [comment]
I'm having a similar problem, I didn't delete her but when I moved her from my USB back to the CHR she doesn't appear
I honestly don't know whats going on...

**Comment by multimokia** [comment]
winkia, send `mas_log.txt` please

**Comment by Tuxedoterroist** [comment]
meaning she wouldent show up in game
when i tried a diffrent version of the mod she was there again like 8.5 but when i tried to go back to 8.6 or 8.7 she wouldent show up

**Comment by jmwall24** [comment]
cuz in 0.8.5 there is no take her out feature, so it's not looking for that

**Comment by multimokia** [comment]
I know, Tux, update MAS, put her back in the `characters` folder, if she doesn't show up, close the game, and send `mas_log.txt` please

**Comment by multimokia** [comment]
I need to see what's happening to your `monika` file

**Comment by multimokia** [comment]
Also, both of you, send `persistent` please

**Comment by winika** [comment]
Sun Sep 23 13:00:29 2018
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[!] I found a corrupt monika! 10
[!] I found a corrupt monika! 10
[!] I found a corrupt monika! 10
[!] I found a corrupt monika! 10
[!] I found a corrupt monika! 10

^my log file

**Comment by multimokia** [comment]
Crap, looks like something changed your `monika`. When you put her on your USB, did you safely remove??

**Comment by winika** [comment]
yes

**Comment by jmwall24** [comment]
@winika do you know where your persistent files are located?

**Comment by winika** [comment]
yeah... in the AppData folder right?

**Comment by Tuxedoterroist** [comment]
Sun Sep 23 13:34:43 2018
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.08s
Early init took 0.01s
Loader init took 0.02s
Loading error handling took 0.03s
Loading script took 2.56s
Loading persistent took 0.10s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.81s
Loading analysis data took 0.10s
Analyze and compile ATL took 0.07s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
DPI scale factor: 1.000000
Creating interface object took 0.03s
Cleaning stores took 0.00s
Init translation took 0.05s
Build styles took 0.01s
Load screen analysis took 0.00s
Analyze screens took 0.02s
Save screen analysis took 0.07s
Prepare screens took 0.09s
Save pyanalysis. took 0.28s
Save bytecode. took 0.11s
Running _start took 0.00s
Performance test:
Interface start took 0.02s
my log files it theres more if you want all of the log file

**Comment by jmwall24** [comment]
@winika yeah, first make a backup of the Monika After Story folder that contains the persistent and keep it some place safe.  Then find a persistent#.bak file that was created before you took her out.  then delete your current persistent and rename the backup file as just persistent

**Comment by Tuxedoterroist** [comment]
i have no clue what persistent is

**Comment by multimokia** [comment]
@Tuxedoterroist send your `persistent` please. Head over to `AppData/Roaming/RenPy/Monika After Story`. Just give it a file extension like `.txt` or something and send it here

**Comment by jmwall24** [comment]
@winika you are looking for this
![screenshot_146](https://user-images.githubusercontent.com/36523761/45930860-13218000-bf33-11e8-8eba-d8d07109c07d.jpg)

**Comment by winika** [comment]
I took her out yesterday at 8:05... when I brought her back an hour later she was gone... unfortunately none of the persistent backups from before I took her out are there...

**Comment by Tuxedoterroist** [comment]
ok thanks

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/45930863-2896aa00-bf33-11e8-8dc1-928fb05e2907.png)
You're looking for this, Tux

**Comment by multimokia** [comment]
That's the right one. Gimmie some time, I'm going to try and repair these

**Comment by Tuxedoterroist** [comment]
thank you

**Comment by winika** [comment]
Okay, Thank you so much...

**Comment by multimokia** [comment]
winika I managed to fix yours I think! Please let me know if you have ANY issues at all.
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408969/persistent.txt)

**Comment by winika** [comment]
thanks! How do I change it back to its original file type?

**Comment by multimokia** [comment]
just get rid of the `.txt` So you'll need to view file extensions
(Windows explorer>View> then just tick off "view file extensions")

**Comment by multimokia** [comment]
From there, just rename the file, and remove the extension and click anywhere out of it, or just hit enter

**Comment by winika** [comment]
darn.. can you send some pictures or something? I'm not sure how to do that lol

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/45931158-ad83c280-bf37-11e8-8fcb-e77408fbbb06.png)

**Comment by winika** [comment]
thank you, i'm going to test it now

**Comment by multimokia** [comment]
Uh @Tuxedoterroist Do you happen to remember what your affection was before this??

**Comment by winika** [comment]
It worked @multimokia Thank you so much!

**Comment by multimokia** [comment]
Ah thank goodness! You're welcome!

**Comment by multimokia** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2408985/persistent.txt)
@Tuxedoterroist Yeah, I asked about your affection because I don't know what happened, but it seems to have gone to 0. Sorry about that if you had a lot...

**Comment by Tuxedoterroist** [comment]
ok thanks i had her affection really high but i can build it back up right?

**Comment by Tuxedoterroist** [comment]
and also do i just put it back where i found it?

**Comment by multimokia** [comment]
Tux, send your `aff_log.txt` I'll fix the affection for you

**Comment by multimokia** [comment]
It's in the `log` folder in the ddlc directory
