### ISSUE TITLE
[Suggestion] weird timing goodbyes

### ISSUE THREAD

**Issue by monikafan24** [Monika-After-Story/MonikaModDev#2563]
i have a cool idea (i hope...) and maybe you could do a thing that if you saying "i'm going to class"
in night time, she says something about that or something...

**Comment by antimockingjay** [comment]
While this works in theory, some people do have night classes, or work late shifts, so that would have to be considered. So just as long as she isn't saying "you're lying" and taking away affection or something, therefore punishing someone for their schedule, I think this could be a good idea!

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
