### ISSUE TITLE
[Suggestion] a corrupted Monika

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2564]
I don't know if this can be done, but we could portray a sick Monika with corruption sickness with everything in her glitched and stuff, and we need to heal her, how can this concept work?

**Comment by CrocWorks** [comment]
I'm now imagining Monika forgets about that birthday cake that she put away somewhere, then suddenly she remembers it and eats some after it's spoiled and gets the runs...

**Comment by pianostick** [comment]
i have mixed feelings about this, on one hand i get to take care of my sweetheart but on the other hand it would get my sweetheart would get sick. but i guess she might enjoy it more than i would worry about it tho

**Comment by scohn** [comment]
I understand where you're coming from with that. I even had the same thought at first, but look at it this way, Monika wants to come into the real world and experience it. Getting sick every now and then is a part of that. So, in a way, this idea helps her get just a little closer to her dream. Plus it gives any player the chance to show how much they care by helping her through it.

**Comment by Olliesama** [comment]
"Achoo! I think I caught a computer virus"

**Comment by AsuraShun** [comment]
I can't stand the thought of her suffering,this is no different

**Comment by Oharo** [comment]
Perhaps her getting sick could tie in with her needing to rest? It'd be really wholesome to be able to flip the watching-you-when-you-sleep thing around and be there for her when she's resting off her illness. It could also set up a real heartwarming moment if it was set up as a dialogue choice when she asks you to let her rest. (Maybe it's only able to be selected after a certain affection threshold?)

Plenty of potential here.

Anyway, I love the idea in general!

**Comment by Sujeito17** [comment]
Goodbye disease immunity ;-; F

**Comment by Mcmanybucks** [comment]
Hah, a bug in the script would equal a viral infection lmao

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
