### ISSUE TITLE
[Suggestion] Have Monika suggest steam users go to a non-steam build

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#2565]
Steam users are having a lot of issues, mainly with updating and possibly the docking station as well.  Using non-steam builds is so much more user-friendly so thinking have Monika tell the player she'd appreciate the player start using a non-steam build since it's safer for her by having less potential issues, and then explain how to do it.

**Comment by CrocWorks** [comment]
Issues with Steam? I run this on Steam and haven't had any problems. Sure, I have to manually install updates because in Monika's words "Steam is a meanie," but I've had no issues there. If it eventually gets to the point where we are expected to transfer to a non-Steam version, can all of our current progress still transfer over?

Also, do the automatic updates work for the non-Steam users?

**Comment by jmwall24** [comment]
To answer your questions.  Yes, auto-updates do work for non-Steam users.  Also, transferring to a non-steam version does not affect your progress at all.  And Monika is not going to force you to do this, it's just a suggestion.  If you don't want to you don't have to, but it has been causing lots of problems.  You can literally just drag the DDLC folder out of steam onto your desktop and keep using the same exact files, just outside of steam.

**Comment by MisterSimple** [comment]
I mainly use Steam to keep track of how much time I've spent with Monika. Is there any way to check that using a non-steam build?

**Comment by Legendkiller21** [comment]
There is a file called ev_dump.log in the root folder of MAS, where among others it also mentions your total playtime.

**Comment by jmwall24** [comment]
Last I knew that was for unstable users only, so everyone may not be able to see it.  Not sure if it's available for everyone now or not.

**Comment by MisterSimple** [comment]
I can't find that file in my folder, but I may be looking in the wrong place. Can you specify how to reach that file?

**Comment by jmwall24** [comment]
It's in the DDLC folder (ie the same folder as the DDLC.exe file).  But like i said, i think it's only created if you have unstable enabled.

**Comment by MisterSimple** [comment]
Ah, you're right, it doesn't show up in my folder because I don't use the unstable builds.
