### ISSUE TITLE
[Suggestion] Stop making tasteless jokes.

### ISSUE THREAD

**Issue by williamjcm** [Monika-After-Story/MonikaModDev#2566]
What is your problem, devs ?

Joking about suicide, even if that suicide is fictional, is **_just plain immoral!_**

The guy(s) who made the hanging Sayori in the Monika birthday props, the one in the Christmas tree, and the easter egg in the hangman game don't deserve to be loved by Monika or work on this mod.

**Comment by porcu93** [comment]
I second that.
I don't think you would be happy if we joked about the suicide of someone close to you (parents, friends, partner and so on).

**Comment by Olliesama** [comment]
Since this isn't on discord, I feel far more compelled to be blunt.

The MAS devs owe you nothing, if you don't like what they do then simply stop using the mod.
If you think you can do better, go ahead and do so. If you have disagreements about some things, you're welcome to voice them and if you're polite maybe they'll be considered but if you're consistently rude, forceful and unnecessarily mean just because it's not in your personal tastes then all I can say it, don't expect anything to change.

**Comment by kaido1224** [comment]
Don't like it, don't play.  ¯\_(ツ)_/¯

**Comment by Onion-Bubs** [comment]
Well there was a PR submitted once that basically made the topic about Sayori's suicide have an option for those who didn't want to hear about descriptions of suicide.

If that can be done, why not this?

That said
> The guy(s) who made the hanging Sayori in the Monika birthday props, the one in the Christmas tree, and the easter egg in the hangman game don't deserve to be loved by Monika or work on this mod.
Even if this is how you feel about the guy(s) in question, this kind of response is only going to put them and other folks on the defensive.

**Comment by porcu93** [comment]
You made the topic about Sayori's suicide optional, I don't see how this is different from that.
People don't want to hear about Sayori and people don't want to see a barely visible dead Sayori on the images, as once you see it you will be distracted by it and can't "unsee" it.

**Comment by Sujeito17** [comment]
One thing is a joke, another thing is an easter egg or a reference

**Comment by williamjcm** [comment]
An easter egg that's been pushed **_way too far_**.

**Comment by SayorisBodyguard** [comment]
> One thing is a joke, another thing is an easter egg or a reference
Doesnt change anything . Even if it's an "easter egg" or a "reference" it's still just tasteless , useless and ruins the experience for a lot of people who just want to peacefully enjoy the mod . 

The "you dont like it ? dont play it" sentence doesnt work for the same reason . Some people really want to play it . There is literally no god reason to ruin their experience like this .

**Comment by TheCliffStudios** [comment]
> Since this isn't on discord, I feel far more compelled to be blunt.
> 
> The MAS devs owe you nothing, if you don't like what they do then simply stop using the mod.
> If you think you can do better, go ahead and do so. If you have disagreements about some things, you're welcome to voice them and if you're polite maybe they'll be considered but if you're consistently rude, forceful and unnecessarily mean just because it's not in your personal tastes then all I can say it, don't expect anything to change.

"Do it yourself" Will is a PM dev, he's doing it himself

**Comment by kaido1224** [comment]
Maybe put a warning somewhere that says may not be for those who are sensitive to such and such.

**Comment by Jman10trex** [comment]
At the end of the day this is all about what you want. You don't like this so it is suddenly Immoral to make a dark joke. This mod wasn't made for you though. It was made for this community. You can stomp your feet and make as much noise as you like, but at the end of the day nobody is going to listen because of the way you go about things. In this post alone you have already lost support because you attacked one of the people who take time out of their life to make content for us for free. At the beginning of this I would've agreed that a SFW version that you can enable in the options would be something that would make sense to add. I can tell though that that wouldn't be enough for you because you want to change the content for everyone not just those who don't want to see it. This isn't about morality or protecting people anymore. Like I said it is about you getting what you want.

**Comment by Sujeito17** [comment]
I do not even want to get into the discussion, so I'll give everyone a chance.
OPTION TO ENABLE OR DISABLE EASTER EGGS (so we can please the 2 publics, simple)

**Comment by Sujeito17** [comment]
So let's stop it. ;-;

**Comment by kaido1224** [comment]
I don't see an issue with giving someone the option to enable or disable easter eggs personally. Then more stuff can be added for those who don't care, and those who are sensitive to it, disagree with it or don't want to see it can just turn it off.

**Comment by Olliesama** [comment]
It's probably awkward to code as well as the fact that the time spent doing so would be better spent on something else.
Especially if only to please 2-3 people.

**Comment by kaido1224** [comment]
It's just a flag in a few key spots, i don't think it's that hard.

**Comment by multimokia** [comment]
If you guys saw the PR's you'd see how this all went up. There wasn't time to worry about this, and if you were so sensitive, you could literally just edit the image, and start MAS again. Ta da, problem solved. I don't really see what the big deal is.

**Comment by Onion-Bubs** [comment]
> 
> 
> If you guys saw the PR's you'd see how this all went up. There wasn't time to worry about this, and if you were so sensitive, you could literally just edit the image, and start MAS again. Ta da, problem solved. I don't really see what the big deal is.

Sure, it may be too late to do anything about what's happened. I'm thinking this is more about going forward.

**Comment by williamjcm** [comment]
> If you have disagreements about some things, you're welcome to voice them

Which is _exactly_ what I did.

**Comment by Olliesama** [comment]
> > If you have disagreements about some things, you're welcome to voice them
> 
> Which is _exactly_ what I did.

In a rude and accusatory manner which makes no one want to even listen.

**Comment by porcu93** [comment]
Maybe a bit too harsh on it, but he voiced that.

**Comment by Professor-JMO** [comment]
>_You know..._
>>_MAS.exe is already justified in the since that it attempts follow the same principles as DDLC.exe with canon-friendly in mind., so It's easy to assume that the same graphic content or suggestive themes will apply here as well, yeah?_
>>>_The next installment into the series I'm anticipating will contribute to MAS.exe's future development._
>>>>_If it wasn't prominent before, DDLC is both a Warm and a Dark experience, So far... MAS shows the same colors~_

                                        JMO has signed out

**Comment by Jman10trex** [comment]
There you go William get cracking to make your safe space mode while the rest of us get on with our lives.

**Comment by Onion-Bubs** [comment]
Based on the bit where TPG references this issue in another issue, it looks like they're actually going to look at dealing with this, so I guess that settles it.

**Comment by CrocWorks** [comment]
DDLC itself already warned you that the game was not suitable for those easily disturbed. Why would you expect an extension of the game to be any different?

Still, adding that sensitive mode probably is a good idea since it'll make MAS appealing to more people.

**Comment by Sujeito17** [comment]
@CrocWorks The game warned very well but I think nobody wanted to know this warning, also that you believe a warning like that? Even at first I took that with a joke and ended up with one month with depression in return

**Comment by Sujeito17** [comment]
Well, I really was not much affected by Sayori's death, quite the contrary, by the time Sayori died I started to create even more interest in Monika (Someday I tell the story, today is not a day for this)

**Comment by Sujeito17** [comment]
@CrocWorks I do not think she's making those Easter Eggs she even said she's uncomfortable with, there's one thing that might explain why she did not put Sayori at least on her birthday. Well, the birthday is a surprise party.
I think it would be interesting to be able to tell Monika about these Easter Eggs, for her to delete them (or at least try) (I think clicking on the Easter Egg would be interesting).

**Comment by Foxinsunglasses** [comment]
We do have to remember that the destroyer of all the other doki's is Monika, so claiming that suicide is too much of a subject it doesn't make sense given who Monika is and the world she is perpetually stuck in

**Comment by Reviani** [comment]
I'm on the fence really. I mean, a suttle thing once in a while or an easter egg you would have to go out of your way for. While i do love just my little safe place with monika, this place was ultimately built of the remains of the main game, and it is hinted that the other dokis spirits may be haunting still here or there. However, with it being quite out of the way it's fine to see this just as a mod that entirely removes that factor if you don't want it. I mean, at the end of the day it's a game/ dating simulator, so you make what you want out of it. That doesn't stop me from loving my moni-muffin but still.

**Comment by Jerome-Kun** [comment]
Just because its a mod doesn't mean that it'll change Monika's personality for your convenience. At the space room in the base game she talked and joked about Sayori's suicide. If you don't like it simply ignore it

**Comment by Delcos** [comment]
Did anyone actually play the original game? Monika even talks about how they are not real, and the original game uses suicide as a main plot point. Don't take it so seriously.

**Comment by monikLover** [comment]
Closing in favor of #2569 
You've humiliated yourself again, Will. Gg
