### ISSUE TITLE
Suggestion: Leaving to Exercise Goodbye Option

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2571]
I was thinking that maybe another option for a reason to leave would be that you're going to go workout. Since health and fitness are some of Monika's favorite things to keep up with she could wish you luck. Then when you go back she could ask how it went. When you answer yes she could say she's really proud of you for keeping healthy and even tease you about wanting to see the results in person. But if you say no she can give you some loving encouragement.

**Comment by CloakedGhost** [comment]
Cool idea. Maybe you could also tell her if you're just doing "small" workouts at home or if you're going to the gym.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
