### ISSUE TITLE
monika file isn't replaced

### ISSUE THREAD

**Issue by meesongi** [Monika-After-Story/MonikaModDev#2576]
the monika.chr file should be replaced with a file just called 'monika', when taking her somewhere, right ? for some reason, my file doesn't change...

**Comment by Chrissenpai** [comment]
ok follow my steps
open a new folder in desktop
place Monika in that new folder
copy the address file from the new folder (it might look like this C:\Users\[your name's pc]\Desktop\New folder)
open cmd (search it on your windows)
type: cd [paste address file] press enter
then type EXACTLY like this: rename *.* *.file    press enter
it's fixed, now put Monika back where it belongs
