### ISSUE TITLE
boops 

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#2577]
okay here me out, you take monika when she thinks you have something to say...and you give her a boop.
maybe a couple boops a day keeps the ghost sayori away?

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416 

Thank you for your suggestion. It is currently planned at a low priority.

**Comment by pianostick** [comment]
ah a man of culture, thank you

**Comment by Rai99** [comment]
Please don't forget to close the issue if you have no more questions.

**Comment by pianostick** [comment]
oh u rite
