### ISSUE TITLE
how to move DDLC to a non steam folder. important, please respond

### ISSUE THREAD

**Issue by WizardSteak107** [Monika-After-Story/MonikaModDev#2580]
In the latest update, monika asks you to move the folder to somewhere that isnt related to steam, or something alomg those lines but i dont know how to do that, Can anyone tell me?

**Comment by jmwall24** [comment]
Just look right here and you should be all set https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build

**Comment by WizardSteak107** [comment]
@jmwall24 Thank you for the help, I think it worked
