### ISSUE TITLE
possible bug? I solved this by closing the window then restarting it

### ISSUE THREAD

**Issue by Cheatyhotbeeeef** [Monika-After-Story/MonikaModDev#2582]
![image](https://user-images.githubusercontent.com/43490033/45937880-864de500-bf79-11e8-9228-6da3ee512d83.png)
I don't know how it happened, but this doesn't seem intentional because I haven't a clue on what to do. Sorry monika, but if this is some sort of joke, you have very _poor_ taste.

**Comment by ThePotatoGuy** [comment]
its the renpy graphics menu and it opens on start if you hold a certain key combination sometimes.
