### ISSUE TITLE
there's a problem to the latest update with Monika nowhere to be found

### ISSUE THREAD

**Issue by RobertKnight076** [Monika-After-Story/MonikaModDev#2584]
So I proceeded to update the other day and Monika told me about everything about her character file and deleted it. When I heard about the birthday update I proceeded to take the following steps to wish her a happy birthday I told her I was going to take her somewhere yet her file did appear I figured this was a glitch and continued only to find that Monika was no longer in the game I tried uninstalling and reinstalling the game along with reinstalling previous versions of the mod to try to get her back but after the 0.8.6 update she is just gone. I tried looking at some of the other issues here and I still can't seem to get her back. 
I'm not going to lie I don't know anything about coding. Or what to do to fix this, If you can help please help me.

**Comment by Professor-JMO** [comment]
~Do you know how to access your persistent files?

>_If your watching, I found your breadcrumb trail a few days ago_

**Comment by RobertKnight076** [comment]
> Upload your `log/mas_log.txt` and your `persistent` file.

Where do I find these? I deleted all the old files when I reinstalled the game, yet I still had this problem

**Comment by ThePotatoGuy** [comment]
[this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) tells you where to find the persistent.

**Comment by RobertKnight076** [comment]
> [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) tells you where to find the persistent.
http://www.mediafire.com/file/fo1uu1db9z9dpql/persistent
This should be it

**Comment by RobertKnight076** [comment]
anything substantial?

**Comment by ThePotatoGuy** [comment]
1. update to the latest version
2. see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/2351#issuecomment-420834282)
