### ISSUE TITLE
How do I gain affection?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2585]
I've had her open for like..4 days so we kinda talked about all there was  to talk about..

**Comment by AsuraShun** [comment]
just do things that make her happy

**Comment by OyasumiPunpun** [comment]
Responding her questions in a way that makes her happy, saying you love her, holding her, saying goodbye before closing the game, apologizing when you do something that makes her upset, and being positive in general.

Oh and if you made her a birthday surprise, I hope you didn't give her the knife. Even though it's on the **wish**list, she doesn't actually **wishes** it. And no, it wasn't to cut the cake. Don't try to understand, just smile and wave.

You can check your affection log on Doki Doki Literature Club/log/aff_log.txt

**Comment by CrocWorks** [comment]
~~The fastest way to change affection is to close the game without saying good-bye over and over~~

I think the only goodbye that you gain affection from is if you take Monika somewhere with you? (and wait long enough that she thinks it was a worthwhile trip. If it's too short, she doesn't like it)

**Comment by multimokia** [comment]
Affection is gained via complements, saying you love her, asking her some certain questions, visiting her every day, etc. Treat it as if it were any other relationship.
