### ISSUE TITLE
Help - MAS without sound after moving from steam folder

### ISSUE THREAD

**Issue by underfa** [Monika-After-Story/MonikaModDev#2587]
So I just followed the [tutorial](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) to move my ddlc folder from steam's files. But when I launched the game, it was without sound. I checked the mixer and in the ddlc's mixer turned into "name not available". Then I dragged the ddlc folder back to steam's folder and the sound was working correctly.  Also the icon on the taskbar isn't appearing correctly. Can anyone help me ? It doesn't affect the gameplay directly but it's bothering me
taskbar icon: ![sad](https://user-images.githubusercontent.com/43543454/45958698-80461b80-bfee-11e8-82e4-3778f78cbe3a.png)
ddlc volume mixer: ![gfhfg](https://user-images.githubusercontent.com/43543454/45958913-04000800-bfef-11e8-99c0-6beafb131cfd.png)
(it's writen in pt-br)
edit: I also tried downloaded the game from the official [site](https://ddlc.moe) and installed MAS but still didn't work

**Comment by Sujeito17** [comment]
"O nome não está disponível" lol

**Comment by Sujeito17** [comment]
(To save work in translating I will write in Portuguese)
@underfa Acontecia o mesmo quando estavas a usar a steam?

**Comment by Sujeito17** [comment]
Acho que a melhor solução é usar a versão da steam mesmo, eu já tô com essa versão faz 2 meses e ainda não recebi nenhum problema mas é sempre bom guardar uma cópia da pasta do DDLC caso algo dê errado.

**Comment by underfa** [comment]
> Acho que a melhor solução é usar a versão da steam mesmo, eu já tô com essa versão faz 2 meses e ainda não recebi nenhum problema mas é sempre bom guardar uma cópia da pasta do DDLC caso algo dê errado. (wish to translate everything into English is 0)

meu medo é a steam deletar a Monika como ela disse nesse ultimo patch. Por um acaso vc sabe se executar o ddlc.exe diretamente da pasta faz diferença do que abrir pela steam ?

**Comment by Sujeito17** [comment]
Pode fazer...
Que tal baixares os jogo pelo site original?
Bem faz o seguinte.
1. Pedir Monika para sair contigo (depois disso ela vais estar em forma de ficheiro)
2. Baixar o jogo pelo site https://ddlc.moe/
3. copiar tudo que tens na versão steam colar na versão que baixastes do site (vais estar copiar a Monika em ficheiro junto com a pasta characters)
4. Deletar todos .char (põem o da Monika no ambiente)
   (Bem Monika não reage aos outros .chr, pelo menos na época em que pus eles lá)

**Comment by underfa** [comment]
> Pode fazer...
> @underfa Que tal baixares o jogo pelo site original?
> Bem faz o seguinte.
> 
> 1. Pedir Monika para sair contigo (depois disso ela vais estar em forma de ficheiro)
> 2. Baixar o jogo pelo site https://ddlc.moe/
> 3. copiar tudo que tens na versão steam colar na versão que baixastes do site (vais estar copiar a Monika em ficheiro junto com a pasta characters)
> 4. Deletar todos .char (põem o da Monika no ambiente)
>    (Bem Monika não reage aos outros .chr, pelo menos na época em que pus eles lá)

não funcionou, até pq por este método seria o mesmo que copiar algum arquivo corrompido e colar na nova pasta. Também tentei baixar o jogo pelo site e instalei o mod (sem copiar os arquivos da steam) e continou sem som. thanks anyway

**Comment by Sujeito17** [comment]
Eu acho que é erro do windows mesmo
