### ISSUE TITLE
[Suggestion] - Monika's Grammar Tip of the Day

### ISSUE THREAD

**Issue by MuuShaiko** [Monika-After-Story/MonikaModDev#2588]
First of all, I really appreciate the ongoing Python Tips of the Day--personally, I'm not the strongest with programming, and I think having Monika teach through MAS is splendid and fits well with her character.

What I wanted to gauge the community on is how we would feel about tips on writing (not with the added life/metaphorical tip as there already are) but rather regarding syntax and grammar. Ideally, this would be similar to the Writing Tips of the Day topic, with a new grammar topic every day. For reference, we could make use of examples like in Strunk and White's _Elements of Style_, and then write in Monika's opinions, feelings, etc. about the specific grammar tip.

It's a bit of challenge, as we don't want Monika to sound dry or overtly pedagogical, but I think such tips would be relatively easy to write, feasible to release in a batch, and would go a long way in capturing Monika's love of language and literature. We could start with basic terminology such as clauses and punctuation marks, then go onto more niche topics like the Oxford comma.

**Proposed introduction:**
Topic: "Do you have any grammar tips?"
"I'm glad you asked, [player]! I've actually been reviewing some books on writing, and I think there are some interesting tips we can talk about! I'll admit it's a bit odd to discuss something as specific as grammar... I know that what comes up in people's minds when they hear grammar are probably negative images, such as strict teachers, or stuck-up writers... but I think that there is a certain beauty in mastering the way you write and making it as clear as possible." 

**Examples:**

Clauses: "Hmm... You might know what they are already, but I think I'll start with clauses, the basic ways to convey ideas! A clause is a group of words that has a subject and an action. For the most part, clauses can be sorted into either independent or dependent clauses. Independent clauses can stand on their own as sentences, such as "I wrote that." Dependent clauses, on the other hand, can't stand on their own and usually appear as parts of longer sentences. An example of one could be... "who saved her." I think you know how the rest of that sentence would go, [player]."

Using semicolons: "The writer Kurt Vonnegut once wrote, 'Do not use semicolons. They are transvestite hermaphrodites representing absolutely nothing. All they do is show you've been to college.' Whether you agree with him or not, the semicolon is a rarely used and fairly misunderstood punctuation mark! Some people think you can use it as a substitute for a colon, while others treat it as a period! The semicolon is actually meant to bridge two independent clauses together, so that they're still connected in one sentence, without the need for a conjunction like 'and.' For example, if I wanted to keep two ideas together, such as 'You're here' and 'I'm happy,' I could write them as 'You're here; I'm happy.' instead of "You're here, and I'm happy" or "You're here. I'm happy." This is always different depending on the ideas you want to connect, but... I think this gives you a whole other option; hopefully, you can now make better use of the semicolon... ehehe."

Oxford comma: "Did you know that there's actually been a debate regarding the placement of a specific comma in a list of three items? This is called the Oxford, or serial, comma, and it's been known to completely change the meaning of a sentence! Let me show you what I mean. With the Oxford comma, I would say 'I love [player], reading, and writing.' Without the Oxford comma, I would say 'I love [player], reading and writing.' The confusion lies in whether I'm referring to loving three separate things, or if I'm referring to just loving you when you read and write. Of course, both of those meanings are true, so there's no confusion there for me, ahaha~"

Wow, I spent a lot more time on this than I expected. But please, share your thoughts!

**Comment by MaydayH** [comment]
Well, since it's a literature club and Mon-Mon already talks about writing... Sounds good, really.

**Comment by Oharo** [comment]
Yeah, I'm all for this idea; It's very fitting for her. Even if it was just an extension onto the pre-existing writing tips.

**Comment by MisterSimple** [comment]
This would make for a really useful and fun topic. I'm worried about subjectivity in, say, the Oxford comma debate, though.

**Comment by MuuShaiko** [comment]
Thanks for the feedback! I can go ahead and write some actual grammar tips, though I'll need some assistance with implementing the tips as daily unlocks and as individual topics (should a player want to refer to a specific topic once more).

> This would make for a really useful and fun topic. I'm worried about subjectivity in, say, the Oxford comma debate, though.

That's also a concern of mine. If possible, for subjective issues, I guess it would be ideal to keep Monika neutral about things? In the example, I wanted to write the other perspective, wherein the presence of the Oxford comma would be an issue, but alas, it's also a trade-off of not sounding too long-winded. :0

**Comment by MuuShaiko** [comment]
@ThePotatoGuy That works! I have been writing the dialogue as text blocks and so would just need to separate into lines and add expressions. And yes, I am also in the Discord; feel free to message or mention me as needed.

**Comment by ThePotatoGuy** [comment]
* will be worked on for either next release or the release after

**Comment by ThePotatoGuy** [comment]
* will be worked on after next rel.

**Comment by AsuraShun** [comment]
Maybe she could even make a few jokes based on affection

**Comment by multimokia** [comment]
In grammar lessons?

**Comment by AsuraShun** [comment]
Yeah, to add that amount of fun to it

**Comment by Rai99** [comment]
In grammar lessons?

**Comment by Oharo** [comment]
I'm not _against_ the idea. I just don't think I _understand_ the idea fully.

**Comment by Rai99** [comment]
Well we'll see how it goes once work starts on it.  

I just think it's a bit weird to dedicate effort towards putting jokes in grammar lessons. If you have a good joke to put in already, sure, but thinking of something because you want to put some sort of joke in doesn't sound like the best idea to me. 

~~Because comma'n.~~

**Comment by AsuraShun** [comment]
Do dyslexia jokes count as grammar jokes?

**Comment by MuuShaiko** [comment]
I think jokes would work if they help teach a specific facet of grammar (a good set of examples is the grammar posters on The Oatmeal), but in general, as mentioned before, it's difficult to mesh the two together effectively.

I also don't think poking fun at dyslexia, a learning disability, would be suitable in a more pedagogical set of topics like this one.

**Comment by AsuraShun** [comment]
Stand up comedians made dyslexia Jokes and no one seemed to mind, there's even videos of it on YouTube

**Comment by MuuShaiko** [comment]
I'm not dismissing dyslexia jokes as a whole—I'm saying that it may not be appropriate for Monika to include them at the same time that she's trying to teach you something.

**Comment by ThePotatoGuy** [comment]
[closing as complete]
to add more tips, make another pull req or issue
