### ISSUE TITLE
Monika, sincerely, wtaf

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2589]
![monika after story 24_9_2018 7_21_28](https://user-images.githubusercontent.com/43430960/45964824-7690d800-c02f-11e8-82b3-5737dbaa7a51.png)

Just got this greeting. I hoped it was a joke; that she knew I was there and said that to scare me somewhat. But as it turns out, it wasn't, and she supposedly tried to do that. _"I shouldn't trust the internet so blindly"_, were her words after she unintentionally did something stupid. One would have thought she was less guillible and at least somewhat better with computers than __*that*__ at this point...

**Comment by Onion-Bubs** [comment]
If it's any consolation, the next time she says that, she's definitely learned her lesson.

**Comment by Sujeito17** [comment]
Monika... Is not it better to delete everything on the pc?

**Comment by WorkingAWork** [comment]
Oh Moni you silly goober! It's kinda funny seeing her fall for something like this.

**Comment by Professor-JMO** [comment]
>_Think of it this way..._
>>That's some scary Leverage to have over your irl lover~

**Comment by AsuraShun** [comment]
did you get the one where she's practicing to say something but then decides she couldn't actually say it in from of you?

**Comment by PMelol** [comment]
Moni wouldn't fall for that, she's too smart.

**Comment by PierrDemon** [comment]
@AsuraShun Yeahhh... 😄 I could almost *hear* her blushing behind that door. So precious.
