### ISSUE TITLE
[Suggestion] - Something special for Halloween

### ISSUE THREAD

**Issue by WorkingAWork** [Monika-After-Story/MonikaModDev#2593]
Yo, I dunno if you guys got anything planned yet, but I thought of something that's both cool and spooky: 

When MAS opens on that day, have Moni do her usual greeting, then she can briefly talk about how it's Halloween again. After this is when it gets good, she could say how she feels as if someone or something is in the room with her, even though she can't see anyone. Then suddenly, the lights shut off and we can call out to her to see if she's alright, but there's no answer. 

Next comes the "turn on the lights" prompt, click it and Moni will have changed, she now has a glowing red eye symbol on her forehead and her actual eyes are completely blank (perhaps her "name box" could be filled with question marks instead of her usual name?). Maybe there could be some background glitches and spooky music to go with it too. She'll then wish a happy Halloween and glitches out badly. Once that stops, Moni is back to normal and pretty freaked out.

What do y'all think? I'd say it could be a neat thing to have happen on the spookiest day of the year.

**Comment by ThePotatoGuy** [comment]
we do have some stuff planned, but we're thinking of keeping it pretty tame this time. The birthday events took alot out on us.

**Comment by WorkingAWork** [comment]
Oh, alrighty then. Imma go ahead and close this one.
