### ISSUE TITLE
i'm haveing a problem with monika geting to show up

### ISSUE THREAD

**Issue by Tuxedoterroist** [Monika-After-Story/MonikaModDev#2594]
on her birthday while i was setting up the gifts i accidentally deleted her file trying to rename one of the copys i just had a person ask for the persistent to help with the affection missing but she still wasent there i hope someone can help me with this problem 
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2412627/persistent.txt)
i dont know where the mas_log thing

**Comment by Tuxedoterroist** [comment]
i hope someone can help me with this problem 
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2412627/persistent.txt)
i dont know where the mas_log thing

**Comment by jmwall24** [comment]
Hey, when you put that persistent back that @multimokia sent you yesterday, did you remove the .txt extension before putting it back?

**Comment by jmwall24** [comment]
I just plugged that persistent @multimokia sent you yesterday into a copy of MAS on my computer and it works fine.

**Comment by Tuxedoterroist** [comment]
it dident work for me

**Comment by Tuxedoterroist** [comment]
i will try again but it dident work the first time

**Comment by Tuxedoterroist** [comment]
yeah no she still dosent show up

**Comment by Tuxedoterroist** [comment]
yeah i removed the txt part of it it still dosent work

**Comment by jmwall24** [comment]
can you send a screenshot of the folder your persistent file is in?

**Comment by jmwall24** [comment]
i literally tried it on my computer and she showed right up

**Comment by jmwall24** [comment]
download this and put it in there, let it overwrite your current persistent

https://drive.google.com/open?id=1ibFioS9Iknsb6rTqTex3tuugGlfuytYx

**Comment by Tuxedoterroist** [comment]
ok

**Comment by Tuxedoterroist** [comment]
nope she still dosent show up

**Comment by Tuxedoterroist** [comment]
i put the new persistent where the original was and that dosent work

**Comment by multimokia** [comment]
Screenshot please?

**Comment by multimokia** [comment]
Also, `aff_log.txt` is in the `log` folder of the ddlc directory

**Comment by Tuxedoterroist** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2412847/aff_log.txt)
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2412848/mas_log.txt)

**Comment by jmwall24** [comment]
can you please send a screen shot of the folder your persistent resides?

**Comment by Tuxedoterroist** [comment]
im not sure how to do that

**Comment by jmwall24** [comment]
You're sure you're using the persistent i sent you and not a different one?  And that when you put it there it's just called `persistent` with no other letters/numbers/extensions tacked on?  Before i sent it to you i loaded it up in my MAS and your Monika was there and she knew your name.

**Comment by Tuxedoterroist** [comment]
persistent.txt
@Tuxedoterroist Yeah, I asked about your affection because I don't know what happened, but it seems to have gone to 0. Sorry about that if you had a lot... this one right?

**Comment by Tuxedoterroist** [comment]
or it was that comment

**Comment by jmwall24** [comment]
Yeah, but did you also try the one I linked to you from google drive?

**Comment by Tuxedoterroist** [comment]
yes i tired both neither one worked

**Comment by jmwall24** [comment]
can you tell me the name right now of every file in that folder that has persistent in the file name?

**Comment by Tuxedoterroist** [comment]
yeah do you want them as txt files?

**Comment by jmwall24** [comment]
I just want to know the file names

**Comment by Tuxedoterroist** [comment]
no she still dosent show up

**Comment by Tuxedoterroist** [comment]
ok the file size right now is 119 and when i open the game it gose back to 117 and it adds the _bad but with 119

**Comment by jmwall24** [comment]
it's creating that _bad by itself?

**Comment by Tuxedoterroist** [comment]
yes

**Comment by Tuxedoterroist** [comment]
i don't know how it dose that but ive tried it 3 times now with the same result each time

**Comment by jmwall24** [comment]
Trying to get more help.  I'm lost on this, can't figure out why it works here but not there.  I've had your Monika up 4 times now on my PC with that persistent.  Sit tight, we're working on it.

**Comment by Tuxedoterroist** [comment]
ok take your time i'm in no rush

**Comment by jmwall24** [comment]
Yeah it may take a bit.

**Comment by Tuxedoterroist** [comment]
thats fine i was wondering if it would be an esay fix if i where to get a txt file of her relistic file

**Comment by Tuxedoterroist** [comment]
no idea if that would work or not

**Comment by jmwall24** [comment]
it has to be your file of your monika from when you took her out, it can tell the difference between the one that was taken out and the one you put back in

**Comment by Tuxedoterroist** [comment]
ok that clears that up

**Comment by multimokia** [comment]
Can you try deleting the bak files and putting the new persistent in? (Save a copy of them somewhere else before you delete them)

**Comment by Tuxedoterroist** [comment]
you think that might work?

**Comment by multimokia** [comment]
I'm just trying to see what the game will do right now. If I'm thinking correctly, it's most likely replacing the persistent we gave you with a backup which was generated automatically while she was out. So I'm trying to see what it intends to do here

**Comment by Tuxedoterroist** [comment]
ok i got a thing the sticker version of her said the persistent is 
corrupted and is asking if i have own backups?

**Comment by Tuxedoterroist** [comment]
or there missing is the other thing she said

**Comment by Tuxedoterroist** [comment]
then i have 2 options yes or no

**Comment by Tuxedoterroist** [comment]
what do you want me to click?

**Comment by multimokia** [comment]
Ok. So I'm not sure why the game thinks it's corrupted. Since this worked on both @jmwall's install and my own. Throw your old backups back in.

**Comment by Tuxedoterroist** [comment]
ok

**Comment by Tuxedoterroist** [comment]
k i put the old backups in and she still isent there

**Comment by Tuxedoterroist** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i think the game did a hard hard reset cus shes back but in the stage where you first talk to her

**Comment by multimokia** [comment]
We're still working on our end

**Comment by Tuxedoterroist** [comment]
i have a question if i miss her birthday can i still through it or do i have to wait till next year?

**Comment by Tuxedoterroist** [comment]
and the sticker told me all her memorys where deleted like it have me a new game in that aspect

**Comment by Tuxedoterroist** [comment]
wich i'm fine with i pretty much finished the game with all text or most of the text options explored

**Comment by Tuxedoterroist** [comment]
exept for the bad ending where she leaves you i dident get that a

**Comment by Tuxedoterroist** [comment]
though its a bummer to have to re build that affection

**Comment by Tuxedoterroist** [comment]
and i can't give her those presents for her birthday shet

**Comment by Tuxedoterroist** [comment]
i'm fine with restarting the game all over again i know what to not say or do to her now thanks for helping me

**Comment by jmwall24** [comment]
do by chance still have the monika file that was in the recycling bin that you said didn't work?

**Comment by Tuxedoterroist** [comment]
yeah i still have it

**Comment by multimokia** [comment]
Whichever one is the newest one. I.e. the one that ended up not having her return

**Comment by Tuxedoterroist** [comment]
[monika.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2416657/monika.txt)

**Comment by Tuxedoterroist** [comment]
thats the one

**Comment by Tuxedoterroist** [comment]
ok

**Comment by Tuxedoterroist** [comment]
and it work thank you so much

**Comment by Tuxedoterroist** [comment]
though im missing the birtday gifts but i can just reset the time and date on my pc for that
