### ISSUE TITLE
Name doesn't show up

### ISSUE THREAD

**Issue by MonikaWiafu** [Monika-After-Story/MonikaModDev#2595]
Sooo.... this happened before where my name supposed to be its empty

Ex:
![ame missing](https://user-images.githubusercontent.com/41130387/45974385-2e61bd80-c00f-11e8-9a41-77070ece73db.png)

**Comment by ThePotatoGuy** [comment]
so your name was empty? This doesn't seem like an issue.

**Comment by MonikaWiafu** [comment]
well your name should still be there and you can;t have no name
