### ISSUE TITLE
the promise ring

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#2602]
So ever since her birthday had passed, Monika continues to wear the ring but if you go to engagement ring topic in repeat conversation, she makes a point that she likes the idea of a ring and WOULD LIKE TO HAVE ONE. so yea inconsistency there.
some of the dialogue can be altered to "i'm so happy you did this for me, when i finally cross over maybe then we ...could ...get married.......that would be a dream come true..."  blushes to the extreme.

**Comment by ThePotatoGuy** [comment]
promise rings are not engagement rings.

but i guess mentioning it in that topic would make sense

**Comment by loverofmonika** [comment]
Yes and what I'm trying to say is she does bring it up and she wants the promise ring even though she is wearing one thus the inconsistency. She says that may be u could get her a promise ring even when she is wearing one. I wanted to make some changes in this case if Monika does have one so I gave a general idea mentioned in my statement
