### ISSUE TITLE
[art] I made a thing

### ISSUE THREAD

**Issue by queenkitty** [Monika-After-Story/MonikaModDev#2604]
https://youtu.be/SloAouNBVHg

**Comment by ThePotatoGuy** [comment]
so something where the art style changes?

interesting concept

**Comment by Professor-JMO** [comment]
>Sort of reminds me of another **_Mod_**.
>>With a similar **_Application_**.

**Comment by BigPoofyRibbon** [comment]
Good job!~

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
