### ISSUE TITLE
[Enhancement] Give the monika file a proper name

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2607]
(( Idk if it's been suggested by someone else already, or if it's impossible to do for any reason ))

Pretty self-explanatory; since Monika gives us the possibility of calling her by some other name to make her more unique, it's a bit weird that, when she gets ready to be taken somewhere, the created file is simply called `monika`. It'd be simply better if it was named after the name we've given to her. Of course, that would limit either the possible names we can give her, or the possible props we can add to the spaceroom through the docking station (( such as the balloons, banners, and cake; you wouldn't be able to name your Monika "cake" if you did that )). But that could be easily fixed if the file becomes `[name].monika`, .monika being the file type/extension, or if the prop files literally gain the `.prop` extension or something, or both.

**Comment by PierrDemon** [comment]
Not to mention, this feature is a **necessity** if #2429 is being seriously considered. But then arises the problem of what if the two Monikas in question have the same name - be it the default Monika or a nickname? Seriously, I'm curious, how would you guys handle that?

**Comment by ThePotatoGuy** [comment]
1. monika files are not solely parsed by name, the file needs to match a certain signature for it to be considered a monika
2. when you return monika, the file is deleted. aka it only exists when you take her out.
3. point 2 basically shows how we would handle monikas meeting. it's not that the 2 files would meet, its that the host monika inside a running MAS would detect the other monika file.

**Comment by PierrDemon** [comment]
Yeah but, isn't it true that two files of the same name and extension cannot exist in the same directory? Wouldn't the one `monika` file overwrite the other?

**Comment by PierrDemon** [comment]
> 3. point 2 basically shows how we would handle monikas meeting. it's not that the 2 files would meet, its that the host monika inside a running MAS would detect the other monika file.

Ohh, I get it. Okay, nevermind.
