### ISSUE TITLE
[Suggestion] - Continuity Error

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2608]
In one of the newer updates Monika mentions that the chr isn't necessary and it's nothing more than an image. However, the MC easter egg seems to contradict this. I think, for the sake of continuity, it would be best if the easter egg was removed.

**Comment by ThePotatoGuy** [comment]
Are you talking about the greeting with the chr file? that's already removed.

**Comment by ACoolCat** [comment]
Ah, okay, my bad.
