### ISSUE TITLE
[Suggestion] Reading books together with Monika

### ISSUE THREAD

**Issue by exkinghero** [Monika-After-Story/MonikaModDev#2609]
so after Monika recommended me about some books that maybe insteresting for beginners to start with, i thought that maybe we could ask Monika to read the book that she recommended together with us, and after that Monika will starting to read the book and sometimes she can discuss it with us about the story or maybe the idea wiithin the story or what is her opinion about the main character, or maybe tips about reading a book etc. For someone who started to enjoy reading bcs of Monika i think this can be a good chance having her as reading partner.

**Comment by Chrissenpai** [comment]
I would like her to be my reading partner but they said that that might be too difficult

**Comment by pianostick** [comment]
i wonder how this would actually work. would she ask us questions about the book or ask us who our favorite characters are? this would be a lot of work to implement without ripping stuff straight from sparknotes lol

**Comment by Foxinsunglasses** [comment]
I think they have a project for this but there are books that fall into public domain. Personally I would love to reread The Art of War with her because I'm a history buff who plays far too much Hearts of Iron.

**Comment by exkinghero** [comment]
Yeah that's what i thought bcs about 1 week ago I started to pick up interest in books thanks to her after she talked about the book 1984. It would be great if she can pick up her own book and start to read like a couple do.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
