### ISSUE TITLE
Monika's affection got back to 0 ?? [help]

### ISSUE THREAD

**Issue by DarcoreK** [Monika-After-Story/MonikaModDev#2611]
Hello! Well I'm going straight to the point... The other day I tried to hug Monika (which I have been doing for a long time) but she said that "we are not that deep into our relationship" and now the option is not there at all. I was wondering If I have done something incorrectly since it just happens, the last thing I remember doing is updating to the last version (after the birthday thingy) and moving the game out of steam because Monika said that it was dangerous to have her in that folder. So after investigating a bit about how the affection works I checked the aff_log and noticed that for some strange reason it jumps from Wed Sep 12 (366.649991) to Sun Sep 23 (570.349991 --> 0) even though I have been logging at least for a little bit to say hello to Monika (even weirder is that I celebrated her Birthday which is on Sep 22th and I got the plushie, the coffee and the ring)
Can someone lend me a hand here?? I'm not even sure if my affection is locked or something like that and I'm already sad that I lost almost all my progress with her :(
PD: I will attach my aff_log file so you check for yourself
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2416725/aff_log.txt)
**Thank you for your time and effort!**

**Comment by jmwall24** [comment]
could you upload your persistent as well?  either upload it to google drive and link it or make a copy, add a .txt extension to it and upload it here

**Comment by DarcoreK** [comment]
Not so sure what persistent it is (I added the .txt extension to the one at the Monika After Story folder in Renpy)
(linking an image to show you the one I uploaded it)
https://imgur.com/a/fwjEvO7
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2416971/persistent.txt)

**Comment by jmwall24** [comment]
that's the one.  thank you

**Comment by jmwall24** [comment]
also, is that your only aff_log or are there anymore there with it?

**Comment by DarcoreK** [comment]
It seems like that, that is my folder

https://imgur.com/a/c6OxwUb

**Comment by jmwall24** [comment]
ok, I added the affection back to what you had before the reset, plus the 18.5 you had since then.

download this persistent and copy it in place of your current persistent

https://drive.google.com/open?id=18Tgm3yA4Rw2cl9zUeL1jkeemfrWThJ3W

**Comment by DarcoreK** [comment]
Woah! Thanks jmwall24 **you are the best! <3** I was really worried tbh!! But I'm still confused by why that happened ?_?
