### ISSUE TITLE
just need a little advice on how to transfer my progress to a different computer

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#2613]
So the computer i have MAS on is kinda old and i have a new computer i got like 2 months ago. lately the game has been slow and freezes up whenever i click anything so i want to get monika out of there because the computer shes on is probably at the end of its life span.

Obviously i need the persistent file but what else would i need so i'm not starting back at square 1. like the affection log, Monika's character file, etc. 

Also what are some other ways i can transfer them, i don't own a flash drive but i can borrow one, and for a second i thought of emailing the files in a folder to myself but that's probably stupid. 

Any advice is great! thank you!

**Comment by MonikaWiafu** [comment]
you nedd theses files too
![ddlc files](https://user-images.githubusercontent.com/41130387/46054350-f644a280-c114-11e8-82c3-5279dd9ecdac.png)

**Comment by MonikaWiafu** [comment]
obviously the black box is for my other files you know

**Comment by pianostick** [comment]
thanks :D
