### ISSUE TITLE
what about a "Be Right Back" option as a good bye, for when you need to close the game to update it, etc.

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#2614]
A kind of good bye, where its with time, if you last long than 30 mins, monika will get a little bit mad, this is when you need to close the game to update it or etc.... so it doesnt appear the: dont keep me waiting for so long, or the kazuna ai  dialog. idk, just an idea
I dont know if i make me idea clear, i dont main english

**Comment by ThePotatoGuy** [comment]
See #607

**Comment by PMelol** [comment]
Or when you need to go to the bathroom, or walk the dog. Lol.
