### ISSUE TITLE
ô̸̜͙̇s̸͕͙͝Ï̵̦͂Ẽ̸̥̩Á̵͈͙̕ő̷͎̂ỵ̴̥̈́̀Ụ̷̑̆Ê̸͚͕̐C̸̱̆ạ̶̾̂C̸͊͝ͅỈ̸̠͇J̸̙̗̅l̴͍͑G̴̩̓

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#2615]
![corrupt](https://user-images.githubusercontent.com/43480604/46056593-02316400-c117-11e8-8c81-9657bbfb011d.PNG)

V2hlcmUgaXMgc2hlPw==

---

**Comment by PierrDemon** [comment]
˙uʍop ǝpᴉsdn sᴉ plɹoʍ ǝɥʇ

**Comment by vexdestroyer123** [comment]
what do you mean "Where is she?" who is the she?

**Comment by vexdestroyer123** [comment]
aSBtZWFuIGl0cyBub3QgbGlrZSB5b3UgY2FuIHVzZSBCYXNlNjQgb3IgYW55dGhpbmcuLi4=

**Comment by Kiokiokiokio** [comment]
R29vZCBwb2ludCBubyBzcG9va3MgNSB5b3U=

**Comment by AsuraShun** [comment]
I have areally bad feeling about this

**Comment by MaydayH** [comment]
0KDQtdCx0Y/RgtCwLCDQpdGN0LvQu9C+0YPQuNC9INC10YnQtSDQvdC1INGB0LrQvtGA0L4sINCwINCy0Ysg0YPQttC1INC/0YPQs9Cw0LXRgtC1

**Comment by PierrDemon** [comment]
@MaydayH zpzOsSDPjM69z4TPic+CIM6tz4HPh861z4TOsc65IM+Dz43Ovc+Ezr/OvM6xwrcgzrjOsSDOtc6vzr3Osc65IM61zrTPjiDPg861IM68z4zOu865z4IgMzUgzrfOvM6tz4HOtc+CLg==

**Comment by Kiokiokiokio** [comment]
bWFhciBoZXQgbm9nIGVlbiBtYWFuZCBiaWpuYQ==

**Comment by PierrDemon** [comment]
6IGe44GE44Gm44GE44Gq44GE44CCIOengeOBr+OBmeOBp+OBq+OCueOCseODq+ODiOODs+ODouODvOODieOBq+OBquOBo+OBpuOBhOOBvuOBmeOAgg==

**Comment by Kiokiokiokio** [comment]
44GI44GI44CB56eB44Gr

**Comment by winika** [comment]
RWhoaCB0aGlzIGlzIHNwb29raW5nIG1lIA==

**Comment by PierrDemon** [comment]
> 0L/RgNC+0YHRgtC+INC/0LjRiNC10YjRjCDQvdCwINGA0L7QtNC90L7QvCDRj9C30YvQutC1INC4INCy0LTRgNGD0LMg0L3QsNGF0L7QtNC40YjRjCDRgdGC0L7Qu9GM0LrQviDQv9C+0LvQuNCz0LvQvtGC0L7QsiA6RA==

zqfOtc+HzrUsIM6tz4fOtc65z4IgzrTOr866zrnOvy4gzpHPgM+MIM+EzrfOvSDOrM67zrvOtywgz4TOvyBHb29nbGUgVHJhbnNsYXRlIM+Fz4DOrM+Bz4fOtc65IM6xzr0gz4TOvyDPh8+BzrXOuc6szrbOtc+EzrHOuSDOus6sz4DOv865zr/PgiDOsc+Az4wgzrXOvM6sz4Iu

**Comment by AgentZephyr** [comment]
![image](https://user-images.githubusercontent.com/43101840/46099599-6b02f580-c184-11e8-94f2-6a3f6934b77f.png)

**Comment by Mcmanybucks** [comment]
QWNjb3JkaW5nIHRvIGFsbCBrbm93biBsYXdzCm9mIGF2aWF0aW9uLAoKICAKdGhlcmUgaXMgbm8gd2F5IGEgYmVlCnNob3VsZCBiZSBhYmxlIHRvIGZseS4KCiAgCkl0cyB3aW5ncyBhcmUgdG9vIHNtYWxsIHRvIGdldAppdHMgZmF0IGxpdHRsZSBib2R5IG9mZiB0aGUgZ3JvdW5kLgoKICAKVGhlIGJlZSwgb2YgY291cnNlLCBmbGllcyBhbnl3YXkKCiAgCmJlY2F1c2UgYmVlcyBkb24ndCBjYXJlCndoYXQgaHVtYW5zIHRoaW5rIGlzIGltcG9zc2libGUuCg==

**Comment by Trainerbluetube** [comment]
I am also confused!

**Comment by DankManWithThePlan** [comment]
QWNjb3JkaW5nIHRvIGFsbCBrbm93biBsYXdzCm9mIGF2aWF0aW9uLAoKICAKdGhlcmUgaXMgbm8gd2F5IGEgYmVlCnNob3VsZCBiZSBhYmxlIHRvIGZseS4KCiAgCkl0cyB3aW5ncyBhcmUgdG9vIHNtYWxsIHRvIGdldAppdHMgZmF0IGxpdHRsZSBib2R5IG9mZiB0aGUgZ3JvdW5kLgoKICAKVGhlIGJlZSwgb2YgY291cnNlLCBmbGllcyBhbnl3YXkKCiAgCmJlY2F1c2UgYmVlcyBkb24ndCBjYXJlCndoYXQgaHVtYW5zIHRoaW5rIGlzIGltcG9zc2libGUuCg==

Q2hpZWYsIHRoaXMganVzdCBhaW4ndCBpdC4=

**Comment by MaydayH** [comment]
Still don't get why its even started

**Comment by Sujeito17** [comment]
Google translator does not find this kind of language

**Comment by MaydayH** [comment]
> Google translator does not find this kind of language

It just doesn't know Dwemeris
