### ISSUE TITLE
[Suggestion] Tell Monika you lost a loved one

### ISSUE THREAD

**Issue by winika** [Monika-After-Story/MonikaModDev#2617]
Now this is a pretty sensitive topic, but I believe that it should be recognized. Let's say you lost a good friend or family member to something, knowing Monika she'd be by your side to get you through it the whole time. Perhaps everyday you visit her she'll ask how you've been feeling and do her absolute best to comfort you (assuming you've been good to her of course). And she'd try help you move on from the pain. It would be really neat and helpful for people who are struggling and could end up be struggling with this stuff.

If this is an issue brought up already then you can close it lol

**Comment by Rai99** [comment]
I do like the idea, but I don't think we can have something like this. 

I think the problem with adding sensitive topics is that people are different and react differently, or need a different kind of treatment. If we go in depth with one approach, it's going to harm a fair chunk of others. We could have general help and advice, but general help and advice won't help anyone who really needs it. 

There's something kind of similar to what you propose in the monika_asks_family topic if you tell her you've never had a family and it still bothers you. 

**Maybe** it would be possible to have a topic similar to what you have in mind and give it an approach like the monika_asks_family topic; Have a small topic and some menu options with new player model variables, but I don't know if that could be done well and harmlessly at the same time. I don't think we can have a system where Monika takes the initiative to ask and make sure the player is alright, at least for now.

**Comment by winika** [comment]
Yeah
Obviously it isn't meant to harm anyone, and it's optional. I think it should be there if people need her it times like that. If they don't feel like talking to her than they simply don't have to choose it. I think if a topic like this was to be implemented then you should have some options on what to say. But yeah... it just came to mind and I was just thinking about ways to possibly implement it. IF it's planned of course...

**Comment by Rai99** [comment]
If it's opt-in and optional, then it **REALLY** has to be well done, since players are going to actively come to Monika and actively be seeking help and support. The wrong kind of help would probably be harmful and general help is going to be unhelpful at best, if not harmful.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
