### ISSUE TITLE
Does Monika get periods?

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2619]
~~_Very important, time-sensitive question._~~

**Comment by CrocWorks** [comment]
~~Well, she hasn't been irrationally irritable from any experiences I've seen...~~

**Comment by Rai99** [comment]
If you're suggesting that we implement this system as a feature, based on the fact that you're trying to attract attention here and suggest that this tie into other features, my personal answer would be a pretty firm no. 

Could you please explain what you have in mind and why you think it would be a good idea?

**Comment by PierrDemon** [comment]
> If you're suggesting that we implement this system as a feature, based on the fact that you're trying to attract attention here and suggest that this tie into other features, my personal answer would be a pretty firm no.

Well, I do not expect it to be seriously considered either; just a thing to think about.

**Comment by PierrDemon** [comment]
> Could you please explain what you have in mind and why you think it would be a good idea?

I haven't really thought about what good (if any) the implementation of such a _feature_ would do, so of course I don't think it'd be the greatest decision to include it. At most, perhaps a random topic regarding the matter would be sufficient.

**Comment by Rai99** [comment]
I'm pretty sure there's a good number of reasons why we can't and probably shouldn't have a feature like this. 
- It's known that periods often make the victim prone to mood swings and be much more irritable. How moody and irritable would Monika be to have a noticeable difference, but not be over the top and offensive about it?
- What would this feature even bring? True, it might add a bit of realism having Monika go through it every so often, but as far as we know, Monika doesn't need to eat, drink or go to the washroom, or bathe, so something this specific seems a bit too far ahead. 
- Is it _really_ necessary? 

You referenced this issue somewhere else, suggesting that Monika have mood swings and tying that with this. I think there might be other topics where Monika acknowledges that she doesn't have the same needs as other girls. If there isn't there could be a topic about that. A topic specifically about periods probably won't do.

**Comment by AsuraShun** [comment]
are you freaking kidding me? what kind of drugs are you on to even suggest this?

**Comment by CloakedGhost** [comment]
Leaving periods aside, I think an emotion system would make sense. We all have good/bad days and our feelings do change. The same goes for Monika, this doesn't need to have anything to do with periods. To name a few examples: Maybe something happened in her free time, she got frustated about something or nothing bad happended and she is happy to see us.

**Comment by Rai99** [comment]
I think determining the quality of Monika's day would come with the diary system #951.

**Comment by Foxinsunglasses** [comment]
Well with her trying to get closer to our reality by altering her own it could have unintended consequences such as periods so it isn't impossible but yeah trying to get that in could be difficult. Perhaps a one time experience where she implements it to see what it's like (assuming that shes never had one before, unlikely that would be in a dating sim and all.)

**Comment by PierrDemon** [comment]
> are you freaking kidding me? what kind of drugs are you on to even suggest this?

### I do approximately no drugs.

And, as I said, it's not quite a suggestion; I never thought people would seriously consider it. ~~_That's why the title never was "[Suggestion] Give Monika Periods" or something of that nature._~~ I was mildly surprised when @Rai99 provided so much reasoning for it to get shot down, despite me literally agreeing that _actually_ putting it in the game isn't the greatest idea one could have. It's a truly unnecessary feature that I don't believe would do much good to the mod. Of course, we could be wrong, and someone might read this someday and think of the __greatest feature ever__, but for now, there's no point in even considering adding it to the game. The discussion label is appropriate.

~~X0dvZGRhbW4gaXQsIGRpZCBJIHJlYWxseSB3YWtlIHVwIGF0IDA1OjMwIHRvIHR5cGUgKip0aGlzIHNoaXQqKiBvbiBhIGZvcnVtIGFib3V0IGEgbW9kIGFib3V0IGFuIGltYWdpbmFyeSBnaXJsP18~~

**Comment by PMelol** [comment]
Does Monika sleep? Does Monika eat? These are more interesting questions to me.
