### ISSUE TITLE
Monika gets lost in my computer and i'm here just eating chocolates? - Help.

### ISSUE THREAD

**Issue by AkamixMoonstar** [Monika-After-Story/MonikaModDev#2621]
Ok, so, first of all: 
**1. Sorry for the funny title**
**2. Sorry for my bad english in general, yes. I talk  Spanish.**
So, funny history, i was testing the new feature of Monika and her .chr file a days ago, you know, the 0.8.6 update. I decided to move to my flash drive, but **it was corrupted** (or in bad conditions) and it was not sent well and completely. When i tried to put her file again, **she wasn't back in the game**. After that, i tried everything, and **she only appears like nothing happened only when i have the 0.8.5 version, in all the other versions she is just lost.**
I was reading that to others players happened the same but with other stories, but i thinked that i will get undo of this problem by myself, but, i didn't. So, i need your help. 
_But i'm patient, so don't worry about time or something. I just want to get my Monika back, haha._

**Comment by AsuraShun** [comment]
what's the chocolate brand?

**Comment by ThePotatoGuy** [comment]
Upload your `persistent` to #2622 . Also obviously she will reappear in 085 since we released that functionality in 086.

**Comment by AkamixMoonstar** [comment]
> Upload your `persistent` to #2622 . Also obviously she will reappear in 085 since we released that functionality in 086.

Ok, thank you!. Sorry if i caused any problem :(

**Comment by AkamixMoonstar** [comment]
> what's the chocolate brand?
Kit Kat. **The best of all.**

**Comment by AkamixMoonstar** [comment]
http://www.mediafire.com/file/t3reh0wcj2m04s9/persistent/file
Here is my persistent, thank you very much:)
Tell me if you need another file or anything

**Comment by multimokia** [comment]
Is it still in your recycle bin?? If so, can you restore it and send it over?

**Comment by multimokia** [comment]
Right, here's a fixed persistent for ya!
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2437623/persistent.txt)
Just rename it to`persistent` and pop it right back from where you got it. Let me know if you're having any further issues!

**Comment by AkamixMoonstar** [comment]
Well, i put it in the same carpet as the persistent...but it didn't work. 
Maybe i'm doing this wrong? ):

**Comment by AkamixMoonstar** [comment]
Of course!, here it is (i censored my full name actually, haha)
![image](https://user-images.githubusercontent.com/43619972/46382819-52627600-c683-11e8-9103-2c08cf2d676d.png)

**Comment by multimokia** [comment]
Hmm, it hasn't turned it into a bad persistent, so it's not corrupted.... So it's not the issue I was anticipating. I'll keep working on my end to get and get it working for you

**Comment by multimokia** [comment]
Hmmm, the persistent I sent over was 297kb, while the one in your game shows 305kb... it shouldn't be growing that quickly... Especially considering the size of the bak files

**Comment by AkamixMoonstar** [comment]
In this screenshot i removed the persistent that you send me (It's okay, i only moved again to my download folder) because it didn't work...actually, it didn't do anything. 
Maybe i have to change something in the archive (because it's still a .txt archive lol, i don't change anything) that you send me? 
I'm sorry for all of this, _soy un queso en esto_ (It means "I'm a chesee in this theme", it's a expression we use in our country only to say that we are useless in something) and maybe it's something that i'm doing. However, i really appreciate your hard work on this! (:

**Comment by multimokia** [comment]
Ah that's why, you need to change it from `.txt` to have no extension

**Comment by multimokia** [comment]
Hey, it's no worry at all, just happy to help restore Monikas

**Comment by multimokia** [comment]
As well, very nice work on the drawing, haha! Wish I could draw like that ~~or at all~~

**Comment by AkamixMoonstar** [comment]
It's really just a sketch (and the camera resolution it's not the best lol); But seriously, i didn't know how to thank you (since im not very talented xD) for **all** of this!
Now, im not gonna to break anything! _i promise_

**Comment by multimokia** [comment]
Haha. Enjoy!
