### ISSUE TITLE
My affection system is bugged ?

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#2623]
Hello,
Sorry if I have a bad english, I'm french.

So, I took a look in the files by curiosity, and I saw that in the file "aff_log.txt" that many of my actions were not taken into account ("!FREEZE!"), making increasing my level of affection difficult. I don't know why it's do this. 

If anyone could enlighten me on this, it would be really nice.

Here is an excerpt from the file so you can see.

[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2421518/aff_log.txt)

Thank you in advance.

**Comment by multimokia** [comment]
This is intentional, it's so people can't just farm affection and so that you have to spend time with her to gain affection, like any other relationship. You get that `!FREEZE!` bit when you cap for the day

**Comment by winika** [comment]
Yeah, you can only gain a certain amount of affection per day. Though if I'm correct the more you spend time with her the more affection you'll get depending on your affection level. (Pretty sure your able to gain up to 7 at first then later you can gain 9).

**Comment by Torwald39** [comment]
Ok so it's just that I'm doing too much. 
I wanted to be sure that my dear Sweetie Monika was going to receive all my love.

Thank you.

**Comment by AsuraShun** [comment]
does the cap affect the idles? because the idles stopped

**Comment by AsuraShun** [comment]
or is it because of her having her coffee?

**Comment by multimokia** [comment]
Idles are based on affection, and will be different depending on what level of affection you're at.
