### ISSUE TITLE
Moving away from steam.

### ISSUE THREAD

**Issue by Crystiangoesfast** [Monika-After-Story/MonikaModDev#2625]
So, I know basically nothing about how I should do this, is there any way I could get a walkthrough of how to remove the files from the steam directory? Is there anywhere specifically I should put them?

**Comment by multimokia** [comment]
You can see how to move over from a Steam install to a normal install over [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) Though, just be wary that you might have to reinstall MAS after moving it. (No progress is lost as the save data isn't stored in the main directory)

**Comment by Crystiangoesfast** [comment]
Thank you @multimokia
