### ISSUE TITLE
[Suggestion] - Smoother transition between topic expression and idle expression

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2626]
Alright, so, Monika has a huge amount of topics, with wildly different conclusions: a lot of them end on a positive note, some are mostly neutral, others are somewhat depressing or bittersweet, you get the idea. While it does make sense for Monika to return to her idle smile in a lot of topics, in some of them the change feels out of place. For example, in "Hedgehog dilemma", her last line is "We can't hurt each other from different realities, right?" with a worried/concerned/sad expression, so immediately changing from that to a smile feels a little too sudden. So, I thought that it would be more realistic if Monika went through different expressions after the topic ends, so as to indicate that she's thinking about what she just said, eventually returning to her idle expression.

So, instead of this:

![image](https://user-images.githubusercontent.com/38892441/46115371-01f3a000-c1cd-11e8-9a07-e6c22dcc8e82.png)

![image](https://user-images.githubusercontent.com/38892441/46115400-18016080-c1cd-11e8-9138-945277e77456.png)

We'd get this:

![image](https://user-images.githubusercontent.com/38892441/46115416-2ea7b780-c1cd-11e8-931d-90c939c570b4.png)

![image](https://user-images.githubusercontent.com/38892441/46115565-f5237c00-c1cd-11e8-83a9-cb537839f202.png)

![image](https://user-images.githubusercontent.com/38892441/46115610-22702a00-c1ce-11e8-8c65-e9e42fc70b0b.png)

![image](https://user-images.githubusercontent.com/38892441/46115749-c659d580-c1ce-11e8-8118-783fbf3abf6e.png)

Here, it looks like she actually thought her own question over, then decided to calm herself and organize her thoughts, and finally returned to her idle smile. Of course, I'm not saying all topics warrant this sort of transition (hell, perhaps this topic doesn't, either), but I think it'd feel more natural.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ThePotatoGuy** [comment]
probable solution:
* return key the desired end slate expression (can be ATL)
* `call_next_event` does a direct pause with the expression, then proceeds with next topic or back to idle. This also means the pause is considered dialogue flow.

**Comment by Booplicate** [comment]
In-progress

**Comment by multimokia** [comment]
This will receive a follow up PR adding disp changes to the end of topic after 6715 is merged

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
