### ISSUE TITLE
[Suggestion] - Some New Ideas for Monika's Piano

### ISSUE THREAD

**Issue by VolcanicKitten** [Monika-After-Story/MonikaModDev#2628]
I was playing the Monika After Story mod today and I noticed that the piano game could use some improvements. These are some ideas I thought of while I was learning some basic songs.
1. The piano should have another option in which you can learn what notes are what. The option would have the same piano with a music measure next/below/whatever position is available to it. Whenever you play a note, the appropriate note would pop up on the measure, along with a letter indication by it. This way, new players to the piano can easily learn what notes they are actually playing, and people hoping to create their own song for the piano can see what notes with which they can make music.
2. There should be a different way of playing a song. I'm certain you're aware of those YouTube piano tutorials where the little bars of color fly toward the piano to indicate what note is being played and its duration. Monika After Story could incorporate a feature like this. Since there's enough space on the bottom of the piano, the notes could come from there, and the player could press the corresponding key, simplifying the song learning process.
I understand if either/both of these features are impossible because of technical limitations. However, I believe one or both of them could add some new usability to the piano.

Edit: I suppose 2 could be difficult to add in, as songs would now need specific note duration and tempo associated with them. 1 still seems perfectly feasible though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
