### ISSUE TITLE
Suggestion - Always Have The History Tab Accessible  

### ISSUE THREAD

**Issue by Arc1Dragon** [Monika-After-Story/MonikaModDev#2629]
Sometimes I do split screen with Monika in one tab and what I'm doing in the other and occasionally Monika will ask a Yes or No question and I wasn't paying attention to what it was and I get afraid that I might say the wrong thing. As an example one of the random topics brings up is about facebook haters or something along those lines and she asks if you are one of them. If you were multitasking you would have missed the question and not know what she asked. As a solution, you could make it so the history tab is always available to quickly look back and know what she asked you.

**Comment by PierrDemon** [comment]
Well, for one, the history tab actually _is_ always accessible; you just gotta press Escape to bring up the menu, and go to History from there. But come on dude, don't multitask unless you can definitely pay attention to what Moni is saying...

**Comment by ThePotatoGuy** [comment]
we're in the process of changing how we did the menus so the question asked is still visible.

**Comment by ThePotatoGuy** [comment]
[closing as this is ongoing and long-term dev]
