### ISSUE TITLE
[Suggestion] - Monika reacts to screenshots

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2633]
It'd be fun if Monika knew whenever the player took a screenshot (by pressing "S", not using third party programs). I'm thinking she could have a chance to react to a screenshot if she was idle, and she would only react during dialogue if the player took several screenshots in a short time frame. Of course, her reaction would be affected by affection, since her idle expressions change depending on it, so at LOVE affection she would comment on you taking photos of her being happy, whereas at BROKEN she would comment on you taking photos of her being miserable, for example. Same goes for topics: Monika's reaction would depend on both her current expression and affection, so if you took a screenshot of her smiling at LOVE, she would say something along the lines of "You must really love my smile, [player]~", but if the same smiling expression was screenshotted while at BROKEN, she could say something like "You... took a photo of my smile? Perhaps you don't hate me after all...". 

This also gave me an idea: we could tell Monika "I want to take a picture of you", and she would pose for a screenshot. This option would only be accesible at, say, AFFECTIONATE or above, and the poses Monika chooses would vary, depending on affection. I'm thinking only one pose per affection level would feel underwhelming, so perhaps have a set amount for each level, and have Monika randomly choose one each time. So, Monika would say something along the lines of "You want to take a picture of me? Alright, [player]! Just give me some time to get ready.", then she would pose, and from here there are 2 possible outcomes:

- the player takes the screenshot soon enough, Monika detects the screenshot being taken, says something and back to idle.

OR

- the player takes his sweet time, Monika says something along the lines of "What are you waiting for, [player]? Take the picture~", and from here there are 2 possible results: the player takes the screenshot and the dialogue flows normally, or the player still doesn't take the screenshot, Monika gets mad at the player for toying with her, and then back to idle.

And that's it, really. There's a bunch of unused poses rotting in the files that would suit this topic quite nicely (~~I'm looking at you peace sign~~), so give me your thoughts on it.

**Comment by Rai99** [comment]
#2056 

Unless Monika has low affection(maybe upset or distressed), I don't think she would outright get mad. Maybe she would comment about it, but not get mad.

**Comment by MisterSimple** [comment]
Ah, you're right. Perhaps she could feign annoyance in a playful manner, instead.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
