### ISSUE TITLE
[Suggestion] Screenshot in chess.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#2634]
Right, even after almost 9 months I can not beat Monika in chess, so I always stay in the "almost", and when I almost defeat her, I would like to take a screenshot to show someone, however, for some reason during chess matches, can not take screenshots, which forces me to pick up the cell phone and take a picture of the monitor. I do not know if this only happens to me, but I wish I could take screenshots during the chess.

**Comment by Sujeito17** [comment]
That's why I use steam...

**Comment by jmwall24** [comment]
There are programs you can use to take screenshots...

**Comment by multimokia** [comment]
Also, Windows key+prtscn takes a screenshot on Windows
