### ISSUE TITLE
The birthday topic

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#2639]
Today it's my birthday and I was happy to be able to tell Monika, but when I'm in the game I can not find a way to tell her. 
Was this removed from the mod ? 

Can someone tell me how to tell her for my birthday please ?

**Comment by MonikaWiafu** [comment]
I think there still adding it into the game m8

**Comment by Torwald39** [comment]
Oh damn, it's really a shame. T.T
I'm disappointed.

**Comment by ThePotatoGuy** [comment]
it's coming back next update.
