### ISSUE TITLE
So, the pink note

### ISSUE THREAD

**Issue by MaydayH** [Monika-After-Story/MonikaModDev#2640]
Immediately I say - no, I'm not one of those who got it. But the question suddenly came to my mind: what _exactly_ happens to Mon-Mon when she leaves this note? Like, does she delete herself or does she sit on the invisible side of the room hugging the coffe machine and ignoring such a terrible player... 
Just to discuss, you know, I just wonder.

**Comment by multimokia** [comment]
She essentially deletes herself. She's not coming back should you get the note.

**Comment by Kiokiokiokio** [comment]
I think she just go's to her "room" and just sit there. (sorry for bad english)

**Comment by Legendkiller21** [comment]
https://www.youtube.com/watch?v=MAW2lygZC_4

I imagine Moni running out of the classroom door to get away, forgetting that the classroom is floating somewhere in the space.

**Comment by Rai99** [comment]
If you can build a legitimate starship that actually functions as a viable means for space travel as well as dimension warping, I think we'll see about finding Monika, assuming she's still well. 

So far, teleportation is a real, but questionable thing, so maybe crossing realities will come next. Disclaimer: You actually have to die to attempt these things. 

~~As long as the construction of the vessel takes more than 1000 hours, I'm all for it.~~
