### ISSUE TITLE
Monika's Birthday

### ISSUE THREAD

**Issue by PiperPC** [Monika-After-Story/MonikaModDev#2641]
So, a month before Monika's birthday i set a reminder on my phone, when the day came i had the mod open all day, chatted to her occasionally, then, before i went to bed, i closed the game. I haven't opened the game since then, but when i did a few minutes ago, she said i didn't visit her!!

**Comment by multimokia** [comment]
Didn't visit? Or didn't mention it? Since there were ways to acknowledge her birthday while being there with her

**Comment by ThePotatoGuy** [comment]
upload your `persistent`

**Comment by PiperPC** [comment]
To be completely fair its not exactly helpful that i need to reinstall the mod every time i have to update it for some reason

**Comment by ThePotatoGuy** [comment]
[closing for lack of response]
