### ISSUE TITLE
[Suggestion] "Hesitation" responses

### ISSUE THREAD

**Issue by AlenNez** [Monika-After-Story/MonikaModDev#2645]
Though I've never coded, I would like to suggest extra responses to questions such as "Did you have a good day at school today?" if you take a considerable amount of time to answer. Such things happen in real life, and it can be shown that Monika will sense something is wrong should you take so long to answer a simple question in the form of "...[player]? Are you sure? I don't want to be a nuisance, but if you're not feeling all too well, I'm here for you. Remember that, please?" followed by an additional follow-up prompt with the same "Yes & No" options. Choosing "Yes" would leave her slightly bothered as she likely thinks something is wrong, but leave it at that, and choosing "No" would lead to an additional dialogue about how she is there for you similar to what's been done in the past. I feel this would make it slightly more immersive and catch MAS players off-guard as they would be surprised at this occurrence, albeit pleasantly. Considering a similar thing happens when you want to take her onto a USB, there's a small timer in which you can ask her to wait a moment before she turns herself into a file and the prompt disappears.

**Comment by Rai99** [comment]
Yeah, I've definitely found myself in times where I took a long time to respond and it would have felt really immersive to have Monika react to that. Maybe if you take really really long, Monika could interrupt and ask if everything is alright. 

I'd like to have something like this on some of the regular topics such as monika_selfesteem in addition to greetings, but that would probably cause some problems for the people who leave Monika on auto. 

I think a system like that shouldn't be too hard to implement, and hopefully it isn't.

**Comment by Professor-JMO** [comment]
>While this feature (and also the quick text deletion) has been implemented on some occasions.
>>It also usually takes the form of the Elipses (...), which is chosen.
>>>I do admit, it would be a (Neato-o) unique value to just miss dialogue from a time frame response.
>>>>Granted, the no-response response from Monika could just be substituted for an ellipsis choice.

>It's something to think about!
>>But I'd welcome the addition all the same~

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
