### ISSUE TITLE
[Suggestion] adding things to the calendar 

### ISSUE THREAD

**Issue by queenkitty** [Monika-After-Story/MonikaModDev#2647]
Hey!
no idea if this has already been suggested but, I think it would be cool if we could add things to the calendar and have Monika remind us about them. you know kinda like how a girlfriend would remind you of important things. idk i think it matches her character.
Ps: love you guys, love the mod,

**Comment by Rai99** [comment]
#1771, #1772, #2078, #2257, #2384. 

It has been suggested previously, but thank you for your input. 

I don't know if I would say it explicitly matches her character. It just seems more like an extra little thing you would do if you could.

**Comment by ThePotatoGuy** [comment]
markign this as duplicate
