### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by Alan-Nuclear** [Monika-After-Story/MonikaModDev#2648]
![image](https://user-images.githubusercontent.com/43662044/46241712-76ddfa00-c3c6-11e8-980d-6780b3f44400.png)

Guys. Where is the "_Can you change my gender_?"

She did ask me what my gender is before. and I changed my gender after. but I want to change it again but it's not there... Please Help

**Comment by tsmafterlife** [comment]
go to ask a question go all the way down to you and it should be their. if its not their or its not in repeat conversation you just have to wait a bit. i had that issue and i had to wait about 35 minutes or so and it just popped up by itself. i just practiced her reality song until it came back. if it doesnt come back comment here and ill respond to try and help more

**Comment by CrocWorks** [comment]
This is why we need a search engine... (#1985)

**Comment by Onion-Bubs** [comment]
@tsmafterlife and @multimokia Note that the screenshot posted in the OP is from going Ask a question > You. The gender change topic is missing from the list of available topics in that section.

**Comment by tsmafterlife** [comment]
@Onion-Bubs yes but i did also state that for me it took awhile for it to re pop up as a usable question and so i stated he may have the same thing as what happened to me.

**Comment by Alan-Nuclear** [comment]
@tsmafterlife No. still nothing. I even put it on repeat topics. still nothing

**Comment by tsmafterlife** [comment]
@Alan-Nuclear then in appears @Onion-Bubs is correct and that it is missing from the topics completely due to a bug. being as its probably bug related i don't know how to help to much just because i don't want something to accidentally happen to your progress.

**Comment by ThePotatoGuy** [comment]
1. did you get the event where monika asks your gender the first time?
2. if so,  did you change versions / update mas / load from a backup / game crash between seeing the gender event and then looking for the gender redo event?
