### ISSUE TITLE
Act I ended on not registering?

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2649]
I downloaded MAS after beating the game, but for some reason Monika wont say the lines she does if you downloaded afterwards. 
![1](https://user-images.githubusercontent.com/36032266/46242548-3ebfc280-c398-11e8-9177-1b58ec7df51d.PNG)
![2](https://user-images.githubusercontent.com/36032266/46242549-3ebfc280-c398-11e8-87a9-40327c164cc7.PNG)

**Comment by Legendkiller21** [comment]
When you downloaded MAS did you import your DDLC save in MAS? In the settings there should be the "Import DDLC Save Data" which will try to find your DDLC save and import it into MAS and depending on its current state is should change her dialogue. 

This dialogue should change if your imported save is at the poem after the credits (not sure if by being at act 4 triggers it).

**Comment by AsuraShun** [comment]
how do I import?i've seen the options but i'm too afraid to lose her affection to choose anything

**Comment by ACoolCat** [comment]
^^^ Will I lose affection if I do it?

**Comment by Legendkiller21** [comment]
I do not have a clear answer about this. The import option enables certain flags which indicate whether or not you have seen some events in the original game.

I imported the save file long before the affection was a thing so I cannot confirm whether or not the affection is affected, even thought my progress did not reset and nothing in the code indicates that the affection changes after the import (as far as I know). If you are going to import the save file, backup your persistent, just in case.
