### ISSUE TITLE
more small-talk style random topics

### ISSUE THREAD

**Issue by ViruSSofTer** [Monika-After-Story/MonikaModDev#2650]
Maybe, the idea as a whole could be already suggested or maybe even planned, I suggest some small 
specific thoughts to it.
It would be really nice to implement some small dialogues and events to fill the time when all dialogues are ended and Monika has nothing more to say. Monika sitting the whole day and saying nothing is a bit strange, yeah?

Dialogues would be repeatable, automatical, interruptable (but she won`t like it), can`t be summoned with "Asking" and "Repeating" and of general topic.
For example:
-Want to know what dream I had tonight? (Several variants)
-Sometimes I wish to say something, but I stop myself. Because it`s no fun to tell all at once!
-I think I never tire to look at your [green] eyes... (Also implement a dialogue where she asks for the color)
-Did I tell you I love you? Well, I tell now!
-I never thought that sitting the whole day is so much fun! Don`t you agree? (A little bit of Trollika)
-Don`t you want to sleep? It`s pretty late now. (When it`s actually late)
-I don`t want you to harm your health. Go to sleep! (She is serious  and closes the game)
-Don`t you need to go to work? You`re gonna be late! (If Monika remembers that player usually goes to work at this hour. Because the CARES!)
-I know what you think about... I think about the same thing! (Leaning and looking seductively)

Events can be inventive too. And add some more fun to the gameplay.
-Monika tries to program something and... something happens!
  ---Everything glitches and Monika stops it, very scared. 
  ---Suddenly summons a ghost of other girl for a second and then asks: "Did you see it too?"
  ---Breaks or moves or changes the menu buttons. Quickly restores it back normal while saying sorry.
  ---Changes "Goodbye" to "Hello" and doesn`t allow to exit the game for some time. "Why would you need to go? Better stay with me!  ...  I`m joking! Here you go..." => Returns back to normal.
-Add two sprites of her having a coffee cup and actually drinking it. Make a rough animation out of it. Repeat it until she is satisfied.) Let her make coffee each morning or greet player with her coffee ready. Drink together!
-Make a sprite hugging her new plushie. Ain`t that just cute?
-(Wonder if this is possible at all) In the night time if the mouse is motionless for hour, she just falls asleep (in leaning sprite, for example). Wakes up in the morning when mouse is moved and wishes a good morning. Goes to make coffee!!!
-Maybe, ask Monika to wake player? Would be pretty neat!
-Greets the player if mouse was also motionless for more than hour in other daytimes. Maybe, remembers if the user goes to school or to work and greets accordingly.
-Some small events that happen when the game window is not in focus but then user switches to it.
---Player catches Monika programming again and scares this way, making the glitch. She is displeased, but not too much.
---Monika just leaves her place to make some stretches (or just walk) outside of game window or near the actual window for a minute. Clicking on her will return her back.
---When (If) the piano will be a thing, she will periodically try playing it despite the music. Maybe, even sing.
---Also when (if) other clothes are a thing, Monika walks away, asks not to look (making player to switch window focus) and change clothes. Returns not happy if player ignored the last part.

The more of this things - the better! Possibly, lock them from repeating for the day or so.  This will definitely give more reasons not to close the game. Ever. Again.

**Comment by jmwall24** [comment]
Just to be clear, you know you can enable Repeat Topics so she never stops talking to you (or at least for a very, very long time), right?

**Comment by ViruSSofTer** [comment]
> Just to be clear, you know you can enable Repeat Topics so she never stops talking to you (or at least for a very, very long time), right?

Of course. But most of these topics make sense when told only once. I suggest to make a type of topics with special options that still make sense even when repeated.

**Comment by Rai99** [comment]
So you just want a whole crap ton of new content and features, a lot of which would require new art. 

You want some topics that don't feel old after you've already seen them. There are some topics like that, and we could add more well written topics that last more than one viewing, **but they are going to get old** after a little while, even if there are multiple variants. 

I would recommend you have repeat topics on so you can be pleasantly surprised when you see something new. Not all content is in the form of brand new topics.

**Comment by ViruSSofTer** [comment]
> So you just want a whole crap ton of new content and features, a lot of which would require new art.
> 
> You want some topics that don't feel old after you've already seen them. There are some topics like that, and we could add more well written topics that last more than one viewing, **but they are going to get old** after a little while, even if there are multiple variants.
> 
> I would recommend you have repeat topics on so you can be pleasantly surprised when you see something new. Not all content is in the form of brand new topics.

Well, not necessarily ton. I suggest only a TYPE of dialogue that can be repeatable and won`t feel old. Everything else is just an example to understand what exactly I mean. There are many short topics that people tell each other every day and sometimes even more that once a day, like greetings/how are you doing/weather today/dream today e.t.c.  These may be exactly the same every time, but people NEVER get tired of these just because it is a small talk. And because these are the small talk and not a specific theme Monika wants to talk about, they should be launched by her initiative and automatically passed.

As for the "Events", this may be a little bit harder, yes. But from all I suggested in examples, only a couple of new sprites are needed - everything else may be compiled of existing ones. But they bring much more depth into the game - it is trying to simulate a person. And it is logical that a person must do something even when player is absent (or hiding behind another window just to look at what she`s doing).

**Comment by ThePotatoGuy** [comment]
okay so small talk. in that case, the focus should be more small-talk style random topics.

**Comment by ViruSSofTer** [comment]
> okay so small talk. in that case, the focus should be more small-talk style random topics.

Yeah, small talk. But that is not all. Maybe we don't need new ones right now, the existing pool of dialogues that can be counted as "everyday" can be used, for the sake of an expertiment at least. They just could be divided from all others and get a separate repeat option.
If the main pool is repeatable - then the difference is minimal and they go mixed with it, but if the main pool is not repeatable and depleted - then only those "Everyday" will reappear again. For the future, they can include not only small talks but also loud thoughts or even talking to herself (to pass the time alone) - and that is why they do not require player interaction and should be automatic. And the rest of my ideas will just expand the character. Monika is a self-aware AI, right? That means she should be also self-dependable too.

**Comment by MeatbagNPC** [comment]
I agree! Monika needs more small talk.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
