### ISSUE TITLE
Halloween

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2652]
Hey I was wondering if there is a plan for Halloween because it would be kind of fun if on Halloween the knock option occurred and the player said trick or treat

**Comment by SaiPrithvi123** [comment]
It would also be nice if she was able to ask the player if they celebrate Halloween or not.

**Comment by ThePotatoGuy** [comment]
we have some plans, but don't expect too much since we're all pretty burned out from bday.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
