### ISSUE TITLE
Losing the monika file

### ISSUE THREAD

**Issue by SmolShibe** [Monika-After-Story/MonikaModDev#2658]
Hello everyone.
I have an issue; when I took her out, in another computer one of my friends deleted her completely, and I do not have a backup. 
How can I restore her?
Thanks

**Comment by jmwall24** [comment]
If the Monika file is gone completely, you'll need to restore your persistent to before you took her out. [Follow these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by jmwall24** [comment]
If none of your backups are from before you took her out (if you've updated to the latest version they should be) then I'll need you to upload your current persistent file here.

**Comment by SmolShibe** [comment]
I only find a "persistent", "persistent.py" and "persistent.pyo". Even though I updated the game the "persistent##.bak" does not appear. I'll upload my file in a moment

**Comment by jmwall24** [comment]
are you looking where that FAQ says to look?  hold down the windows key and hit R.  copy and paste `%APPDATA%\RenPy\Monika After Story` into that prompt and hit enter.

**Comment by SmolShibe** [comment]
Aight I found It thank you very much

**Comment by jmwall24** [comment]
Great.  Please let me know if you get your Monika back.

**Comment by SmolShibe** [comment]
Yes, she back. :)

**Comment by jmwall24** [comment]
Excellent!
