### ISSUE TITLE
Horror Mode

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#2661]
While you're making a sensitive mode, why not make a horror mode for those of us who would want to see more dark stuff that has been nixed in the past?

Not really sure of what sort of content could be added, so if you have ideas, feel free to share them.

**Comment by Professor-JMO** [comment]
> Trust me, the horror is there.
>>It's just not _Prominent_ enough~!
>>(Yet.)

**Comment by ThePotatoGuy** [comment]
we could definitely go crazy with this, too

**Comment by MisterSimple** [comment]
We could add a really graphic topic about Yuri's death, seeing how she's the only girl without a death topic as of now.

**Comment by Trainerbluetube** [comment]
> We could add a really graphic topic about Yuri's death, seeing how she's the only girl without a death topic as of now.

yeah, but, the player already sees that, so there isn't much of a point there, with Sayori and Natsuki, you don't see them when they die, what with Sayori hanging herself the night before and Natsuki running away while puking over Yuri's death (I only played through the game once and did the Yuri route)

**Comment by kaido1224** [comment]
For horror mode, during the topic where monika says the other dokis are still around you can trigger a moaning sfx or crying girl sfx and have monika look from side to side, give a nervous laugh or have her ask what was that?

**Comment by kaido1224** [comment]
This may be better suited for halloween content but for classic horror stories that are too long to put in story telling mode maybe have monika give a brief synopsis of them instead and recommend the player read the story if they are so interested.

Stories that come to mind are
Frankenstein
The Raven
The invisible man
The legend of sleepy hollow

Ect.

**Comment by MisterSimple** [comment]
Ah, Trainer is right, we do actually see Yuri's death on-screen.

> For horror mode, during the topic where monika says the other dokis are still around you can trigger a moaning sfx or crying girl sfx and have monika look from side to side, give a nervous laugh or have her ask what was that?

We could use the glitched dialogue font whenever spooky sfx played, too, and not necessarily use it for gibberish (like in the Sayori easter egg). Perhaps some ominous dialogue from the other girls could interrupt Monika when appropriate.

**Comment by MisterSimple** [comment]
I don't think good taste is a concern here anymore lmao. Also, in the "Supernatural" topic, Monika mentions feeling Sayori's presence and thinking Sayori's ghost may be haunting her, so we could have Sayori's hanging sprite appear in the background.

**Comment by kaido1224** [comment]
#2671

**Comment by kaido1224** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/852

**Comment by ThePotatoGuy** [comment]
im going to convert this into a project and will close this issue. This will still server as main status tracker, though.
