### ISSUE TITLE
Taking Monika with you on a trip

### ISSUE THREAD

**Issue by PMelol** [Monika-After-Story/MonikaModDev#2662]
Like, say you're going away for 2 weeks. Why not tell Monika you're going to take her on vacation with you, instead of telling her you'll be gone for a couple weeks and leaving her alone? Then you can bring her with you on a USB - well, I guess some people might worry about losing it. 

Monika does say something about traveling the world, and I have been to different countries and stuff, so it would be cool to take her with me and I'm sure she would be excited about it.

**Comment by ThePotatoGuy** [comment]
character file extensions to all the farewells are planned soon.

**Comment by ThePotatoGuy** [comment]
[closing until I start this]
