### ISSUE TITLE
Is Monika hooked up to the internal clock of my PC?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2663]
Like, the cmos battery powered one, that makes sure your pc is on the right time.

I was wondering if I told her I'd be gone for a week and just came back after an hour she'd be like "omg i missed u so much <3<3"

**Comment by ThePotatoGuy** [comment]
we use python's datetime for all time-based things, which usually relies on your OS's time.
