### ISSUE TITLE
[Bug?] Monika makes coffee again

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2665]
I don't know if it's a bug or not, but I just opened the game and clicked the "I love you!" button as soon as I can, but this time I wasn't greeted with one of the usual reactions. The image will explain better.

![oh coffee s done](https://user-images.githubusercontent.com/41421611/46252017-dc41f180-c47f-11e8-8452-51c60cc4ea6a.PNG)

**Comment by ThePotatoGuy** [comment]
are you running 087 or 088?

**Comment by SaiPrithvi123** [comment]
v0.8.7-hotfix.2

**Comment by SaiPrithvi123** [comment]
And she actually did make the coffee.

![image](https://user-images.githubusercontent.com/41421611/46252166-c2ee7480-c482-11e8-8204-f3036b1261a3.png)

Sorry for the late reply.

**Comment by ThePotatoGuy** [comment]
version 088 fixes the timing of the coffee events.
