### ISSUE TITLE
Three songs I think she would like 

### ISSUE THREAD

**Issue by Swampyboi** [Monika-After-Story/MonikaModDev#2666]
While I understand that these would be hard to insert into the mod due to copyright and length, I believe Monika would really enjoy these three songs for various reasons. (Of course such topics should only be initiated if the player has confirmed that they listen to rock and roll, which is now possible with that recent update of yours.)

*Note: These all fall under the genre of rock 'n' roll, though each falls under a different sub genre. The first is classic rock, the second progressive rock, the last is somewhat folksy rock.

Stairway to Heaven by Led Zeppelin:  This is an iconic rock song by an iconic rock group, both debatably the best of the era. But of course Monika is not a bandwagon sort of girl, so while it's popularity and renowned status would prompt her to know it and bring it up, I feel her familiarity with some themes in the song would be the prime reason for her passion for it, were she to hear it. She can relate to the lyrics in numerous ways, so much so that it reminds me a lot of her third poem in Act I, "The Lady That Knows Everything", except this, in my opinion, is much more closely in line with her situation as a whole, being in another reality and all. Hence, it talks about the sensations and toils for a "Stairway to Heaven" which I think anyone could equate to her escape from the game. It also has a few lines about being in the game, with the surreal nature of her predicament, or rather lack thereof in her limited dimension, along with coexisting with the girls. 

"In my thoughts I have seen
Rings of smoke through the trees
And the voices of those who standing looking"

There are even lines in one verse that can translate to her situation with the player.

"Your head is humming and it won't go
In case you don't know
The piper's calling you to join him
Dear lady, can you hear the wind blow
And did you know
Your stairway lies on the whispering wind"

In my opinion this one is a given for a song she would like. There are more connections to drawn, but I think I might have limited space, but if this piques your interest, you can always search up the rest of the lyrics and see for yourself.

2112 by Rush: So I believe this is an original topic of hers, forgive me if I am wrong, but Monika talks about a novel by George Orwell. This book talks about the oppression of expression, the retainment of knowledge, and the iron grip of a ruling authoritarian government in a dystopian society. All of these motifs and themes are performed in this song. This 20 min long special tells a riveting story and keeps you on your feet with the switches in tone and scene. Not to mention I think Monika would really appreciate the masterful instrumentals and meaningful lyrics. The cherry on top is it's about a lone figure opposing the powers that made them for the right to have knowledge set free, specifically the knowledge about music and the other arts. If she found interest in 1984, then there is no way she wouldn't find interest in this.

Helplessly Hoping by Crosby, Stills, Nash: Of course I had to throw a love song in there, but this isn't your vanilla, boring love song for sweet hearts. This portrays star-crossed lovers with more internal conflicts than external, though it can be assumed that there is a fair share of external as well. It shows the imperfection of real love while also showing the determination of the lovers in the song. If there is anything Monika would derive from this, it would be a reminder of her everlasting commitment that the player and her share.

(I just posted the whole song since it's rather short.)

"Helplessly hoping
Her harlequin hovers nearby
Awaiting a word
Grasping at glimpses
Of gentle true spirit
He runs, wishing he could fly
Only to trip at the sound of good-bye

Wordlessly watching
He waits by the window
And wonders
At the empty place inside
Heartlessly helping himself to her bad dreams
He worries
Did he hear a good-bye? Or even hello?

They are one person
They are two alone
They are three together
They are four for each other

Stand by the stairway
You'll see something
Certain to tell you confusion has its cost
Love isn't lying
It's loose in a lady who lingers
Saying she is lost
And choking on hello

They are one person
They are two alone
They are three together
They are four for each other"

And there you go! Hopefully you will consider my suggestion in the next upcoming update, whenever that may be. Though if not, I understand, this music is rather outdated, but I had to try.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
