### ISSUE TITLE
[Suggestion] Having Monika forgive the player for the lesser things

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2667]
I know you might have already planned about re-enabling Monika's nickname option after some time.

But I want to talk about the hair style thing.
I get it that she can't really forgive the player if she doesn't believe he did something wrong in the first place, which makes it unlikely to say that she forgives the player and re-enables the hair style options. But what can be nice is if the player got an option to apologise himself about it. It would both make her and the player feel a bit better. As for me, I really want to apologise to her for making her feel so bad. It's been a few months with guilt for me, and I think I've spent well over 1000 hours keeping the game open.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
