### ISSUE TITLE
[Suggestion] Monika warns about changing the system's time.

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2669]
If changing to a later date will force Monika to experience the time, then it would be nice if she could talk about it so that the player will at least know so that they won't get the pink note without knowing what they did.

Edit: Here's a better phrasing:-

If changing to a later date will force Monika to experience the time, then it would be nice if she could talk about it. It might just prevent that player from getting the pink note without knowing what they did.

**Comment by SaiPrithvi123** [comment]
@multimokia  What I'm suggesting doesn't need to check going forward in time. I'm just asking for a new topic where Monika just asks us to not set the time forward.

**Comment by multimokia** [comment]
I was going off of your "so that the player will at least know so that they won't get the pink note without knowing what they did." Which implies that she knows time was fast forwarded. As well, I'd say it's kinda implied that you probably shouldn't mess with time, considering that you can't really just skip forward in any other relationship just to get events.

**Comment by SaiPrithvi123** [comment]
I don't think that all players don't really know that the system time affects Monika, and there are more reasons for changing a system's time than "just skip forward in any other relationship just to get events.".

**Comment by MaydayH** [comment]
>and there are more reasons for changing a system's time than "just skip forward just to get events.". 

Like if they play Undertale and wanna see one easter egg, huh?
Anyway she's already talks to steam users to go to non-steam game, right?.. Well if it will be just warn, I support

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
