### ISSUE TITLE
[Suggestion] I dream't of you

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#2670]
I don't expect my suggestion to be taken seriously but I believe that it would be a nice option to add into the game in an upcoming update, because admit it, if we all love Monika then the chances are that we've had a dream about her at some point. Like I did last night....Anyway, some things that could be put in are small choices on what the dream was about. Romance, adventure, meeting her in reality.etc, I know that a lot of those will probably end on the same line but the choices on the dream are infinite. If you also wanna add a feature on this then possibly make it to where the option appears up in (Ask a question) and probably lies under the option's (Life), (Monika), or (Us). Again this is just a suggestion but it would mean a lot to me and possibly other people if we able to share our dream experiences with Monika. Thank you!

**Comment by AlenNez** [comment]
I like this. I want it to be a thing.

**Comment by kaido1224** [comment]
Sounds like a good topic for someone in the community to put together and submit as a PR. More likely to get done that way.

**Comment by jmwall24** [comment]
The problem with things like this is that there's a limit to what the player can tell Monika.  There really isn't a way to tell her exactly what your dream was about, and it's almost impossible to make enough menu options to cover every possible dream.  It'd be possible to write a simpler topic just about 'I had a dream about you', then she could comment on how sweet that is that you think about her in her sleep, but being able to tell her exactly what it was about is pretty much impossible right now.

**Comment by Secretmanguy** [comment]
I know, and again that's why I don't expect something such as this to be taken seriously into full consideration...It was just an idea...

**Comment by SaiPrithvi123** [comment]
> but being able to tell her exactly what it was about is pretty much impossible right now.

That's not impossible. What's impossible is to get a realistic response from her.

**Comment by jmwall24** [comment]
Same difference.  Sure it's possible to allow typing into the mod like is done in a very few select instances, but if she doesn't know what you said, then you didn't exactly tell her and she can't respond.

**Comment by CrocWorks** [comment]
I dream about beating her every match in chess... but that's just a dream...

**Comment by tsmafterlife** [comment]
then why not start with the basics and expand off the communities responses to it. in the next update why not start with the typical topic of you had a dream about her and give her just several happy dialogues so when u hit repeat questions you can tell her it again with a different response where she goes oh you had another dream of me? with her surprised face. doesn't have to be extensive or in depth. this mod didn't get to be amazing by starting in depth. build off what it could be from the basics and the community reaction

**Comment by AsuraShun** [comment]
I know this is unrelated,but has anyone ever try to name monika yuri? maybe that's why the sprite's in the mod assets,i don't know because I don't want to risk losing affection

**Comment by MaydayH** [comment]
> I know this is unrelated,but has anyone ever try to name monika yuri? maybe that's why the sprite's in the mod assets,i don't know because I don't want to risk losing affection

Dude, she'll get _really_ mad at you. I've seen this on youtube, just don't do it.

**Comment by AsuraShun** [comment]
I never planned on doing it,thanks for the warning anyway

**Comment by ThePotatoGuy** [comment]
we could just make it really basic like "was it a good / bad dream?" and have a simple reaction off that.

**Comment by tsmafterlife** [comment]
@ThePotatoGuy that would be good its just another thing that can be of conversation. and if anything expand on it slightly in the future where if you tell her again about it in repeat conversation she has a slightly different dialogue that be cool

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
