### ISSUE TITLE
[SUGGESTION] - Headless greeting for halloween / horror mode.

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#2671]
![torso-def](https://user-images.githubusercontent.com/35311136/46262333-6791a600-c4c5-11e8-8fe6-bf90eac2f817.png)

i'm shitty at art. But for halloween or for horror mode, maybe have a headless monika with a pumpkin sitting on the desk greeting that randomly spawns. Obviously this would need to be done by a far better artist than i and you probably want to use a spookier pumpkin too.

**Comment by Mcmanybucks** [comment]
Doki Doki Toru Hagakure

**Comment by AsuraShun** [comment]
just have her wearing a dullahan costume

**Comment by AsuraShun** [comment]
or something that doesn't actually mutilates her

**Comment by xfrodo1** [comment]
You know Monika does say something about the other dokis are still around somewhere "like whispers in her ear..." 

Just throwing that out there that somthing to do with the other characters might be more spoopy.... i mean we all got the mod for Monika. Imagine someone else greeting us. ^_^

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
