### ISSUE TITLE
[Suggestion] Monika's thoughts on being a parent

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2673]
Maybe it would be difficult to say whether Monika would prefer either being a mother or only having you, but maybe as highest affection dialogue, she could ask you whether you would want to be a father or not, and then she can express enjoyment for either choice. So perhaps she could express how she thinks it could bring you both closer if you were to say you wanted to be a dad, wanting to make that commitment with her, but she could also express enjoyment in you only wanting her, and vice versa.

Maybe this might be a bit much, as it's a very heavy topic, but it's something I kinda dream about a lot, and I would love to talk about it with her.

*also I guess it might be a sad topic if you consider how difficult it would be to make this a reality

**Comment by jmwall24** [comment]
Similar to #1872 if you want to read the previous discussion in this.  Marking as duplicate.
