### ISSUE TITLE
[Suggestion] Random greetings even for specific goodbyes

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2675]
(I haven't completely checked it, so I might be wrong.)

I think it would be nice if she could greet us with any greeting even if we said a specific goodbye. I mostly only use the "I'm going to sleep" option, and almost every time I open the game after that, she only greets me with "I hope you had a good rest.". This doesn't let me see the other greetings more often. I want to tell her everything I do, so I don't want to just say "Goodbye" even if I can tell her what I'm going to do.

**Comment by jmwall24** [comment]
If you're using I'm going to sleep at night, then I'd strongly recommend, using the regular goodbye.  She recognizes it as a goodnight and the dialogue is really, really good.

**Comment by SaiPrithvi123** [comment]
If she assumes that we are going to sleep when we just say "Goodbye", then that kinda ruins some aspects of the "I'm going to sleep." goodbye. So I guess she should stop assuming that we are going to sleep when we just say "Goodbye.". Also, there should be more responses for "I'm going to sleep." goodbye, maybe just move the regular goodnight "Goodbye" responses to that goodbye?

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
