### ISSUE TITLE
[Suggestion] Creepypasta (no, not for Halloween)

### ISSUE THREAD

**Issue by MaydayH** [Monika-After-Story/MonikaModDev#2679]
No, it's not Halloween suggestion, I'm sure devs will do everything cool by themself.
So here's the point. I know at least two creepypastas about game's characters - well-known Ben Drowned and I-don't-really-know-if-someone-else-ever-heard-of-it Princess - by the way they both from _Ocarina of Time_ <s>lol why</s>
So I thought that these are similar situation when on the basis of the game appears a horror story which is kinda metafictional could be an interesting topic. After all, DDLC is already metafictional too.

**Comment by AsuraShun** [comment]
ben drowned is from majora's mask

**Comment by MaydayH** [comment]
> ben drowned is from majora's mask

Wow, sorry, I meant this... franchise?.. Games about Link. I just didn't played but get that these two stories base on Link's franchise for some reason.

**Comment by SaiPrithvi123** [comment]
UNDERTALE creepypastas would be better choice. The devs even put an UNDERTALE easter egg at the beginning.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by AsuraShun** [comment]
a pokemon creepypasta calle Melissa,it's one of the few with a good ending,also,nes Godzilla creepypasta,it's good enough that it doesn't feel like a creepypasta
