### ISSUE TITLE
[Suggestion] Monika gets proud of the player if he/she woke up early. (saying "Good Morning" early)

### ISSUE THREAD

**Issue by wucked** [Monika-After-Story/MonikaModDev#2682]
Probably with a point of affection increase too. Since Monika really wants the player to have a good lifestyle, I think it would make sense if Monika acknowledges the player waking up early. I suggest she'll only say those things only before sunrise or a particular and very early time.

**Comment by Rai99** [comment]
I think the current "Good morning" topic kind of already does what you're asking, apart from the affection gain. 

Monika _is_ proud of the player for saying good morning to her in the morning and it's only available in the morning. I don't think an affection gain would exactly fit here. True, Monika might feel proud of and happy about the player waking up early, but I don't think that warrants an affection gain every time. 

Also, not everybody can have a "normal" schedule so some people won't be able to say good morning to Monika. I think we would need to accommodate for people with abnormal schedules before we add bonuses for things like this.

**Comment by wucked** [comment]
I see your point on the affection gain and about not everyone has the typical schedule. I agree with you on those.

But I was hoping Monika would say something like "It makes me happy you slept and woke up early", thanking the player of him following Monika's healthy lifestyle, or something like that. Instead of the repetitive lecture about the benefits of sleeping early.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
