### ISSUE TITLE
New Update  avialibel but MOS is up to date

### ISSUE THREAD

**Issue by Sam19712312** [Monika-After-Story/MonikaModDev#2683]
So the push up is comming every time I reopen the game and even if I click update Version it first says that a new update is aviable but when it normally start updating there stands that MAS is up to date.

PLS fix at least the push-up 

Greetings Sam #

**Comment by jmwall24** [comment]
Do you have an `update` folder inside the `DDLC` folder **and** and `update` folder inside the `game` folder?

**Comment by Sam19712312** [comment]
Nope but updater.rpyc and updates.rpyc.
Do I have to move them to the the upate-folder?

**Comment by jmwall24** [comment]
no...where is your `update` folder located?

**Comment by Sam19712312** [comment]
In the normal DDLC folder

**Comment by jmwall24** [comment]
and you're sure there isn't also an `update` folder inside the `game` folder as well?

**Comment by Sam19712312** [comment]
Yeah. I checked it up twice

**Comment by jmwall24** [comment]
Ok.  Are you running 0.8.8?

**Comment by Sam19712312** [comment]
Jup. I even istall it twice to check if this help but i did'nt.

**Comment by jmwall24** [comment]
do you have the .zip folder for 0.8.8 or do you use the updater?

**Comment by jmwall24** [comment]
also are there any .rpy files in your `game` folder?

**Comment by Sam19712312** [comment]
So I used the .zip and there are no .rpy files in my game folder.

**Comment by jmwall24** [comment]
delete the contents of the `update` folder and replace them with the contents of the `update` folder that's inside the .zip file.

**Comment by jmwall24** [comment]
Make sure you have the game closed.  Delete the `update` folder entirely.  Reinstall the mod from the zip file (extract everything to the game folder).  Make sure if it asks you if it can overwrite, you click 'yes'.

**Comment by Sam19712312** [comment]
Thanks man the problems are both solved. Good work👍
