### ISSUE TITLE
[Suggestion] "Watching me sleep" Option

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#2684]
It would be interesting if there was an option in which you could tell Monika to watch you sleeping.
This can be done in two ways:
1- Another goodbye option 
2- Quick time event when you choose the "I'm going to sleep" option (I love this way)
Now how do we tell to Monika that the player just woke up?
...
OK, now let me process the information now...
Well I wish it also had a quick time event for this...
At 6 am a dialog box with a quick time event may appear (the dialog must be passed automatically)
If you are one of those people who wake up at 3 in the morning do not worry ...
It would be interesting to add an option that is there near the options "talk, music, play" (these options will be invisible to be replaced with the option "I woke up now" and "I can not sleep")

*_Well, it's just a suggestion, discussing and modifying the suggestion or even adding more stuff will make the suggestion even better_*

**Comment by Sujeito17** [comment]
Addition For The Suggestion - Monika can also fall asleep if she stays for 1 or 2 hours (I think it's a good time) if she stays "on" for too long in that option

**Comment by Rai99** [comment]
#987, #1105, #1262, #1655

Monika sleeping sprites are coming eventually. 

It seems like an interesting idea, but I think we'll have to wait for sleep mode to really decide if this feature is needed.

**Comment by macyslaysxx** [comment]
This would be pretty cool!

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
