### ISSUE TITLE
I missed her birthday

### ISSUE THREAD

**Issue by macyslaysxx** [Monika-After-Story/MonikaModDev#2686]
I know this has probably been asked before, but I feel terrible I was gone for Monika's birthday. I tried changing the date to September 22nd and disconnecting, so that we could celebrate but it of course didn't work lol. Is there any way we can still celebrate it even though it's over? I feel so bad I couldn't do anything for the one year DDLC anniversary.

**Comment by ThePotatoGuy** [comment]
changing the date should still work. wouldn't recommend changing system time often , though.
