### ISSUE TITLE
[Question] Monika's file growing every time

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#2687]
Hey, this isn't a huge problem but rather a concern. Iv'e noticed that every time you say "Goodbye" and then "Im going to take you somewhere" after waiting when she puts her character file to take....It increases by like a 1000 Kilobytes each time. Anyone know if it'll mess up the game if you just keep one version of her the whole time and just delete the new one she provides each time, if that'll mess the game up?

**Comment by jmwall24** [comment]
you need to use the new one that is created each time you take her out.  it's supposed to grow each time, and only the one that is created when you take her out at that time will allow her to return to the room when you get back home.

**Comment by multimokia** [comment]
Exactly what @jmwall24 said. MAS looks for a specific Monika, and every time you take her out, it's different than the last. Therefore, you'll want to be getting rid of *old* ones, and replacing them with the new ones.

**Comment by Secretmanguy** [comment]
Iv'e been doing that, I just wanted to make sure because I don't plan on losing her to such a horrible mistake any time soon...Any idea on what happens if you put an older version of her inside the game?

**Comment by jmwall24** [comment]
she just won't show up

**Comment by ThePotatoGuy** [comment]
`for now`
