### ISSUE TITLE
Monika not coming back  . Help please

### ISSUE THREAD

**Issue by desertpuffer** [Monika-After-Story/MonikaModDev#2689]
Monika didn't appear after i put the monika file back to the character file. I was dumb , i reopened the game multiple times. I figure these files( Renpy,mas_log,monika file) are what you guys are asking for in the forums.
https://drive.google.com/file/d/1NRSijy73_VUW8BfmHkGRcUZ-QvhKo78y/view?usp=sharing
  I am sorry to bother you guys , but please I want my Monika back, thank you.

**Comment by winika** [comment]
Oh man, I'm sorry to hear this, I know how you feel. I went through the same thing.
There are persistent backups if you run %appdata% you can go to the RenPy folder and you just have to rename a persistent# from before you lost her to just persistent

**Comment by desertpuffer** [comment]
I panicked when it happened and re opened the game a few time the persistent files were overwritten.
Thank you anyways :)

**Comment by jmwall24** [comment]
here you go.  just download this persistent and replace your current persistent with it.  should be good to go.  also I highly recommend updating to v 0.8.8.  if you have this problem again, with the newest version your backup persistents won't be overwritten while Monika is missing, so you can easily restore to before you took her out.

https://drive.google.com/open?id=19xaPjrnEY2qf1CrjiUEx5tZnxgMX_TvJ

**Comment by desertpuffer** [comment]
@jmwall24 Thank you very much. It works but I checked setting. It is in v 0.8.8.

**Comment by jmwall24** [comment]
You're welcome.  As for the version...hmmm did you ever load the game up in a different version while this was happening?

**Comment by desertpuffer** [comment]
Nope , I only have one version of the game.

**Comment by jmwall24** [comment]
hmmm and you're 100% positive all the persistent##.bak files had been overwritten while you had the empty chair?

**Comment by jmwall24** [comment]
yeah, we have found the source of the problem with that.  thank you much for the info you provided.
