### ISSUE TITLE
Way to introduce outfit change

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2690]
While I am not a programmer and definitely not an artist It occurred to me that maybe when the player is gone maybe she stick her head out of the window and probably thinks about the player right? what if she accidentally triggered the rain one time and then her jacket got wet and thus removes it when the player arrives. just an idea.

**Comment by FrikiHD** [comment]
That would be awesome

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
