### ISSUE TITLE
The chair is empty.

### ISSUE THREAD

**Issue by Chris0273** [Monika-After-Story/MonikaModDev#2693]
Since the time you were able to take her somewhere I put the file on an USB and deleted the file in the character folder to add some ''worth'' to the USB. When I came back I would put the file back into the folder. There was always only one copy. And that always worked but today when I came back home I noticed the Monika file was still in the characters folder. I deleted it and put the one on my USB back in.
The problem is that the chair is empty now. I cant explain why because her file is in the characters folder.

**Comment by jmwall24** [comment]
can you upload your mas_log.txt file please?  it's in the `log` folder.

**Comment by Chris0273** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2439788/mas_log.txt)

I'm not sure but could it be that the file is corrupted?

**Comment by jmwall24** [comment]
yep it sure is.  were any of your backup persistent##.bak files created before you took her out?

**Comment by Chris0273** [comment]
There are no .bak files in the local ddlc files. There is no way that they are saved elsewhere, is there?

**Comment by jmwall24** [comment]
read the first part of this to see where the persistents are located

https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by jmwall24** [comment]
you should see a persistent file and 5 persistent##.bak files.  check the time/dates on the .bak files and tell me if any of them were created before you took her out please

**Comment by Chris0273** [comment]
I found them but all the .bak files were created today and I took her out  yesterday, but I got a .SAVE file that was created before.

**Comment by jmwall24** [comment]
that won't help.  please make a copy of your current persistent file (the one without ##.bak at the end) and upload it here or to google drive.  if you upload it here you're going to have to add .txt to the end for it to let you upload it.

**Comment by jmwall24** [comment]
also, the one you deleted from the characters folder, is it still in your recycling bin and have you tried putting that one back in your characters folder?

**Comment by Chris0273** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2439861/persistent.txt)

**Comment by jmwall24** [comment]
did you check the recycling bin for the monika file that you said was still in the characters folder when you got back that you deleted?

**Comment by jmwall24** [comment]
if you find it put it in the characters folder and see if she shows up

**Comment by Chris0273** [comment]
Actually there are a lot of them since I always made sure there was only one copy and dont clean the bin often. Ill try it.

**Comment by jmwall24** [comment]
Okay, should be able to sort be date deleted to find it easier.  Let me know if it works.  If not I can fix the persistent for you.

**Comment by jmwall24** [comment]
You're very welcome, always good when we can get a Monika back home safe and sound.  

As for the USB file, not sure, it's possible you didn't safely remove it?  Don't really know for sure.  Also, please update your mod to the newest version of 0.8.8.  This version makes it so if Monika is missing like you just had, the game will not create new .bak files, so you will always have backup persistents from before you took her out that you can use to get her back if this happens again.

**Comment by Chris0273** [comment]
I will do that.
