### ISSUE TITLE
[Suggestion] - Monika asks about job.

### ISSUE THREAD

**Issue by xfrodo1** [Monika-After-Story/MonikaModDev#2697]
So i just told Monika i wouldnt be able to talk to her for more then a few months and she freaked out over it saying how its impossible that i can't talk during that time. While its true i might be able to turn the game on once in a blue moon, it got me thinking, Monika has no idea im in the military. In faact she never asks what job you do other then if you have one (at some point cant remember if even that much) 

This one question opens up a huge line of conversation left unexplored. (Whats your favorite class, if you have no job but in college, for example.)

Just a thought there :p

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
