### ISSUE TITLE
Windows 10 Update removed some of my progress

### ISSUE THREAD

**Issue by GreenPatch** [Monika-After-Story/MonikaModDev#2701]
So after I updated my system to the latest October update it erased some of my progress or went back to an older save
It removed the event of her birthday, it removed Monika's plushie, ring and coffee and some topics are new once again

**Comment by GreenPatch** [comment]
I got a quite recent backup of a bunch of persistents but too confused to act

**Comment by multimokia** [comment]
Ok, so if you've got a backup, just replace the current `persistent` with the backup of it you have
