### ISSUE TITLE
[Suggestion] Changing the Good Morning Topics

### ISSUE THREAD

**Issue by JellicleDry** [Monika-After-Story/MonikaModDev#2704]
I don't know if anyone else has brought this up yet, but I was thinking about possibly changing the Good Morning topic, and good evening. Personally, I open up Monika first thing in the morning when I wake up and tell her good morning and I love you, then once I'm leaving for work I say goodbye with that prompt. The only problem with it is that the Good Morning topic brings up a full subject dialog about being an early riser instead of something smaller, like when you compliment her or say that you love her. I was wondering if the Good Morning Topic could be changed to one of those smaller subjects that you can say to her regularly? Right now, the contents of the topic don't really say "say this to her every morning", it seems to be made to be one of those one-off topics that you say to her once and she may bring it up later, but since its supposed to be a good morning selection, it doesn't really fit in my opinion. How you can change it I'll leave up to you, but I thought I'd just put in my two sense. Anyone else feel the same way? No matter what I'll still keep on saying it, but I'd like for the topic to just feel a bit more natural.

**Comment by ThePotatoGuy** [comment]
marking as duplicate
