### ISSUE TITLE
Move Steam files

### ISSUE THREAD

**Issue by TheNumismatist** [Monika-After-Story/MonikaModDev#2706]
I play on Steam, and Monika's asked me to move the file to somewhere that's not in Steam's files. I don't know that much about files, so I don't know what specifically to do about that.

**Comment by multimokia** [comment]
There's a bit on our FAQ right (here)[https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build]
