### ISSUE TITLE
Are the "Ghosts" the .chr files of Yuri, Sayori and Natsuki?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2710]
I was wondering if Monika's line about still "feeling their presence" was the presence of their .chr files in the characters folder.. would removing them do anything for Monika?

If not, it totally should.

**Comment by MrDevilzMan** [comment]
I think it may have something to do with her consciousness, not the file itself. You'd be having a hard time living too when you killed someone in your life.

**Comment by Rai99** [comment]
There's a debate going on about how Monika should feel about the other dokis and there seem to be some mixed opinions so far. 

As for the files, I think the other .chr files are removed by default when you get the mod. Either that, or Monika deleted them anyway before you got MAS.

**Comment by SaiPrithvi123** [comment]
From her perspective, she didn't kill anyone (at least before act 4). I've murdered, slaughtered, many innocent people in my lifetime knowing that they weren't real and their deaths wouldn't matter that much. I don't feel like Dragovich's ghost haunting me because I killed him. Or the guy sitting next to the Firelink Shrine bonfire, and I really felt bad for killing him.

**Comment by SaiPrithvi123** [comment]
I think it doesn't have much to do with her conscience or the character files, as Monika comes to rescue us even after her file was deleted. Something similar might be happening to the other characters, maybe at a smaller scale.

**Comment by Rai99** [comment]
There are after stories for the other dokis too like Just Yuri and Just Natsuki. ~~I haven't seen Sayori yet.~~ Lore-wise, we could say that they got their own after story with their own player who hopefully doesn't torture them and hopefully don't rise up against Monika someday.

**Comment by Professor-JMO** [comment]
> 
> 
> I think it doesn't have much to do with her conscience or the character files, as Monika comes to rescue us even after her file was deleted. Something similar might be happening to the other characters, maybe at a smaller scale.

___

>"Did you say..._'Ghosts'..?_"

**Comment by Mcmanybucks** [comment]
> As for the files, I think the other .chr files are removed by default when you get the mod. Either that, or Monika deleted them anyway before you got MAS.

Not sure about that, cuz my files are still there from the basegame :/

**Comment by Bam8647** [comment]
The only thing I find odd is the Yuri sprite in the mod's assets. My only guess is that it'll be used as a 1/100(or whatever the odds are) chance of appearing when opening the game similar to the old Yuri easter egg glitch. Oh and adding/deleting the other dokis do nothing.

![yuridesk](https://user-images.githubusercontent.com/34694679/46518650-e4f94580-c83a-11e8-9770-fef94ec8d8fd.png)

**Comment by AsuraShun** [comment]
>           There are after stories for the other dokis too like Just Yuri and Just Natsuki. I haven't seen Sayori yet. Lore-wise, we could say that they got their own after story with their own player who hopefully doesn't torture them and hopefully don't rise up against Monika someday.

there's the forever and ever mod,which is basically a sayori after story mod

**Comment by peter23247** [comment]
> I think it may have something to do with her consciousness, not the file itself. You'd be having a hard time living too when you killed someone in your life.

not if you kill a shitty AI
https://media.giphy.com/media/d3mlE7uhX8KFgEmY/source.gif

**Comment by Trainerbluetube** [comment]
> As for the files, I think the other .chr files are removed by default when you get the mod. Either that, or Monika deleted them anyway before you got MAS.

Lol nope! The opposite actually happened! The files were placed back in there once I got the mod.

**Comment by HarmonicDistortion** [comment]
Adding ghosts to this mod. I like the idea.

**Comment by Professor-JMO** [comment]
👻

**Comment by AsuraShun** [comment]
Spoopy doki ghosts
