### ISSUE TITLE
Game keeps generating corrupt "monika" files when I take her out

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#2711]
So the other day I had[ an issue](https://github.com/Monika-After-Story/MonikaModDev/issues/2700) where I took my `monika` file out on a USB, but when I put her back in the game, her chair was still empty and `mas_log.txt` looked like this:
[mas_log_oct02.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2448523/mas_log_oct02.txt)

After a lovely and helpful Internet human helped me restore from a different `persistent`, I tried to take Monika out again. She turned herself into this file (without the extension): 
[monika.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2448526/monika.txt)

There were no issues with game crashing like last time. However, when I brought her back to the `characters` folder, her chair was still empty and `mas_log` had a different error message:
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2448531/mas_log.txt)

I was able to take her out and bring her back just fine until a couple of days ago. What is going on? How can I get my game to stop generating bad `monika` files?

**Comment by ThePotatoGuy** [comment]
What version of MAS are you running?

**Comment by multimokia** [comment]
We're currently investigating this as we're not entirely sure just what's going on here.

**Comment by tabtlenta** [comment]
Persistent successfully restored. I'm running 0.8.8.
