### ISSUE TITLE
[Joke post] [Question] Despacito

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2712]
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2448612/pnm.txt)

![image](https://user-images.githubusercontent.com/41421611/46510994-9ca54c00-c869-11e8-8752-ef449c232b08.png)

Explain.

**Comment by Mcmanybucks** [comment]
So sad

[Alexa Play  D̶e̶s̶p̶a̶c̶i̶t̶o̶ Sayonara]

**Comment by Sujeito17** [comment]
**ALEXIOS PLAY EZIO'S FAMILY**

**Comment by AgentZephyr** [comment]
How dare you mods

**Comment by Dovahkun** [comment]
Lol, I found it a little while ago after they added the ability to make you own songs on piano. Someone has partially finished Despacito piano notes in the code somewhere.

**Comment by SaiPrithvi123** [comment]
Alexa play Dovahkiin

**Comment by pianostick** [comment]
this is so sad. monika, play sayo-nara
