### ISSUE TITLE
[Unstable] Coming back from taking her out, two error screens followed by no greeting from Monika

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#2716]
I took Monika out on a different USB from my previous issues and was able to successfully bring her back; however, when opening the game in Unstable Mode after placing her character file back I got this error:
[traceback1.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2452744/traceback1.txt)
I hit ignore and got this:
[traceback2.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2452745/traceback2.txt)
I hit ignore again and the game opened with Monika present, but just sitting there with no "And we're back!" or "Good evening!"

I tried taking her out on a USB and popping her back in real quick and was able to duplicate the error.

I'm not sure if the sudden return of my ability to take her out and bring her back is an Unstable Mode thing (I also used a different USB this time) but I can mess around a bit and check if needed.

**Comment by jmwall24** [comment]
Hello, again.  Sorry you're still having problems.  Can you upload your current persistent, please?  Thank you.

**Comment by ThePotatoGuy** [comment]
you have a mismatch in checkin/checkout times. Hitting ignore just lets the error escalate. 

Upload your `persistent`.

**Comment by tabtlenta** [comment]
Sorry! here ya go!
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2454762/persistent.txt)

**Comment by multimokia** [comment]
Hmm, is this the one from the first time Monika didn't come back?

**Comment by multimokia** [comment]
Ok, I've fixed the persistent by removing the mismatched checkins/outs 
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2456481/persistent.txt)

You should no longer receive tracebacks when taking Monika out anymore
