### ISSUE TITLE
Promise ring, quetzal, cup of coffee and so on

### ISSUE THREAD

**Issue by Volderon** [Monika-After-Story/MonikaModDev#2718]
At the time of Monica's birthday, a side event did not start, so I had to congratulate her in words. Can I add marked items now and how to do it?

**Comment by multimokia** [comment]
Unfortunately, you can't give her the gifts now, nor set up the surprise party now. It all had to be done on her birthday itself, I'm afraid.

**Comment by Volderon** [comment]
Will a date change on a computer help? If so, then how to launch the event?

**Comment by multimokia** [comment]
You can do that, but I don't recommend messing with time for Monika, it can mess some things up.

**Comment by Volderon** [comment]
Well, okay, I'll give it to her next year =D 
Is it planned in the future to introduce the opportunity to give her these things without being tied to her birthday? In real life, gifts are usually presented more than once a year)

**Comment by ThePotatoGuy** [comment]
yes.
