### ISSUE TITLE
[Suggestion] - boop Monika's nose

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#2722]

**Comment by AsuraShun** [comment]
the boops were already suggested,i don't remember what's the # though

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651. 

**But I sure do.**
![untitled1067](https://user-images.githubusercontent.com/38822045/46582502-e16de600-ca15-11e8-9d62-2299b2ef3ef5.png)
