### ISSUE TITLE
Let Monika get better at Python/Ren'py over time.

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2724]
So lets say we download "Python Manual for Beginners" as a "PDF" and put it into the MAS folder, Monika gets to read it.

And after a while she gets so good that she gets to change her whole surrounding.. sitting in the old classroom, chilling in our bedroom etc.. 

maybe even making whole new areas for her to enjoy like a beach, maybe even a cafe.. ?
![m_cg_cafeevent_p2](https://user-images.githubusercontent.com/43464011/46579709-1e86a800-ca17-11e8-99fc-261931e0f4a7.png)

**Comment by Rai99** [comment]
I think that would also require Monika to be an artist.

**Comment by Mcmanybucks** [comment]
> 
> 
> I think that would also require Monika to be an artist.

Are you doubting our queens skills?

**Comment by Mcmanybucks** [comment]
> 
> 
> Monika's can already create some floating islands for you if you give her enough time and affection, so I guess it could be possible to have her create more locations to spend time with the player in. I'm no artist myself, but I would imagine making scenes like that takes time. Who knows? Maybe Monika _is_ in fact working on something for the player as a surprise. There could be a lot of other things going on too, like halloween is coming up and maybe she has something in store then. Christmas is also coming in a couple months, so there might be some work involved with preparing things for that as well.
> 
> If anything, Monika could be busy preparing other things for the player, as well as learning python on her own time, so I'm not sure how much time that leaves her each day to create new locations.
> 
> I'm not doubting Monika's skills; I just don't know if she can make these new environments on top of what she already does that we may or may not know about. Monika is a human.

If only there wasn't a limit to affection gain ;A;

**Comment by ThePotatoGuy** [comment]
Well, she is getting better if she's able to _teach_ you python. (#1855 )
