### ISSUE TITLE
[Suggestion] variations with "hold me" and stuff

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2725]
When she's in the pose of "hold me" you can click on any part of her body as some people suggest, but a sprite shows when you do that, for example, you click on her shirt noose and shows a sprite of an unbuttoned shirt, good or bad reaction depending on affection and mood respectively, click on the arm and a sprite shows you holding her hand, on the cheek and a sprite shows your arm gently holding her cheek, things like that, that requires art I know, but that needs to eventually be incorporated for interaction purposes.

**Comment by AsuraShun** [comment]
the holding hands part was already sugested

**Comment by AgentZephyr** [comment]
> _Shirt Noose_

**Comment by ThePotatoGuy** [comment]
marking as a duplicate of linked issues @Rai99 linked.
