### ISSUE TITLE
[Suggestion] change monika's dialogue after losing in pong so much

### ISSUE THREAD

**Issue by TrRizzo** [Monika-After-Story/MonikaModDev#2726]
I thought the moment when I lose a game of pong, that I get desperate and press quick the "yes" button.
It always happens to me. So, I think that Monika can realize when the player press a button very fast, it's because we're desperate.
She can say something like: "Wait, (player) calm down, it's just a game." But only if this happens 3 or 4 times, otherwise, it wouldn't look natural and even more stressful.

**Comment by Sujeito17** [comment]
Just because I clicked quickly on "yes" does not mean that I'm desperate...

**Comment by Rai99** [comment]
Maybe instead of having it be time based, it could be based off of how many times the player lost in a row. 

There's probably a better thing to say than "It's just a game", but the idea might fit.

**Comment by Clover-Elf** [comment]
Even better... make it a little more fair, maybe? :-P I've won against her like TWICE, and it's embarrassing how often I miss the ball on the very first return! I've played on systems as far back as Atari and I wasn't THAT bad...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
