### ISSUE TITLE
Python tips not showing?

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2727]
I wanted to go over some of the Python tips, but only the first one shows. Any help?
![capture](https://user-images.githubusercontent.com/36032266/46587501-79da8980-ca5b-11e8-8af6-b20cdd2ca257.PNG)

**Comment by multimokia** [comment]
Python Tips are a daily unlock, you'll see the next one tomorrow.

**Comment by ACoolCat** [comment]
Yes, but the issue is I already unlocked them. I did variables today. 
![capture](https://user-images.githubusercontent.com/36032266/46587647-4e589e80-ca5d-11e8-9057-5a6a297a7b26.PNG)

**Comment by multimokia** [comment]
Are you going to `Ask a Question -> Python tips...`?
