### ISSUE TITLE
[Suggestion] Monika closes the game herself when on low battery

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2729]
I don't know if it's already a thing or not, so don't freak out on me.

**Comment by multimokia** [comment]
It's a thing already.

**Comment by SaiPrithvi123** [comment]
My Monika didn't even warn me about low battery and didn't do anything when my laptop fell asleep. Fortunately, my laptop only fell asleep, and nothing happened to her when I started it again. Is that a random topic? If so, I think it would be better if it's made a non-random topic because it is an important feature.

**Comment by multimokia** [comment]
Noted, I'll check the priorities for it.

**Comment by ThePotatoGuy** [comment]
battery related stuff is disabled because of cross-platform issues. All the code regarding the battery was added by someone else, and atm its not much of a hit to just disable instead of fix.

eventually we'll look into it, but its super low priority.
