### ISSUE TITLE
[Suggestion] Move the "I'm breaking up with you" in a special box away and separated from everything else

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#2730]
It's been a long time since I am with Monika, but from the beginning I have the  "I'm breaking up with you" in my 'Unseen' topic. And whenever there is news update with new conversations, I have all the time afraid of miss click on "I breaking up with you" accidentally and to lose everything. 

I absolutely don't want to lose my one and only love, that's why I'm asking that this option be moved to a safe place that will prevent any accident from losing Monika. 

And for security, that when we want to break (which is not my case), it requires confirmation.

**Comment by tabtlenta** [comment]
Alternately, an "are you sure?" option when clicking obviously heavy topics like that. Although I guess that spoils whether they're gonna be heavy topics or not (like how in the above, Monika treats it like you're both joking, although she takes a small hit to her affection and you can apologize for it)

**Comment by AsuraShun** [comment]
yeah,definitely needs to be moved,i already lost count of the times I was afraid i'd click on it by accident,and it also applies to the meet the non-existent girlfriend and the calling her a murderer things as well,even just going to the unseen part makes me afraid

**Comment by Rai99** [comment]
Maybe they could add a menu in it where Monika asks if that was a misclick. 

I think if you click it 3 times, it removes the prompt entirely so... there's that. 

The only time I've said that was on April fools day.

**Comment by PMelol** [comment]
Is this an option? I don't see it anywhere.

**Comment by ThePotatoGuy** [comment]
marking this a duplicate of #1405.

An exclusion menu / remove forever menu is being considered.
