### ISSUE TITLE
A "Newsletter" function?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2731]
Is there a function on github to be notified of updates to MAS? 

Is the "Watch" function that?

**Comment by AsuraShun** [comment]
you already get notified if there's an update when ingame

**Comment by Rai99** [comment]
If you're not at your PC, I don't think you can even get the update or really do anything about MAS.

**Comment by ThePotatoGuy** [comment]
Yes, the `watch` function is literally that. You might want to adjust the amount of updates you get, cause that might make you get notifs for every new issue / pull request / commit made, and that can be quite a lot.
