### ISSUE TITLE
[Suggestion] New Song?

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#2733]
Ordinary World by Duran Duran  _(even though I like the Red cover better)_

Specifically the Chorus I feel applies to Monika's situation
"But I won't cry for yesterday
There's an ordinary world
Somehow I have to find
And as I try to make my way
To the ordinary world
I will learn to survive"

Pretty Similar to Your Reality when you think about it I guess.

**Comment by AgentZephyr** [comment]
Never coded anything in my life but I guess I can give it a shot.

**Comment by jmwall24** [comment]
Honestly the coding for most topics is essentially copy and paste from existing topics and then changing a few things for what your topic is.  I had never done need it before either until I tried it the first time.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
