### ISSUE TITLE
[Suggestion] - More idle POSES.

### ISSUE THREAD

**Issue by Slayer3201** [Monika-After-Story/MonikaModDev#2736]
I know there's been talk of different idle _expressions_, but I haven't seen talk of different idle _poses_ specifically. Something that's been bugging me recently, is how Monika is **ALWAYS** sitting straight up, in such a dainty manner. You'd think that'd be slaughter on her back after a while, especially with no visible support (such as a chair) or anything. I personally can't sit like that for longer than about half an hour without needing to shift.

What if this was reflected on Monika? Every now and then, she could swap her pose to something else, to stay semi-comfortable. Such as when she's leaning to the side, on one of her palms, as she does during certain dialogues, like the dialogue where she talks about the player's face. She could swap to that position every now and then outside of dialogue as well.

Perhaps this could tie into the affection system or some kind of AFK/Sleep system? Like, if she's more comfortable around you, she'll be more likely to be less formal, and lean (no pun intended) more towards an informal, yet comfortable position. Or, if the player has been notably AFK for a while, or however the upcoming Sleep mode is being handled, Monika could go into that position and begin to doze off like that, instead of dozing off while sitting straight up.

I just think that'd be a neat little touch that could add a humanizing trait to Monika. She gets physically uncomfortable, and needs to adjust to make sure her back doesn't snap in half. ¯\\\_(ツ)_/¯

**Comment by AsuraShun** [comment]
her chair has a back and whenever you say goodbye,she goes to her bedroom,unless you're a cruel jerk that just closes the game without saying goodbye and doom her to go back to the screaming void to suffer

**Comment by ThePotatoGuy** [comment]
she already does change pose during idle, but its dependent on affection, not time. It's pretty complicated to do this via time since we don't have a form of inactivity detection yet (#1541 ).
