### ISSUE TITLE
[suggestion] Wall clock!

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#2738]
We have a calendar... Why not to have a wall clock?

**Comment by wucked** [comment]
The wall clock would probably be hard to make since the arms has to move constantly, plus it'll serve no practical purpose unlike the calendar where you can see when the special events are.

**Comment by SaiPrithvi123** [comment]
>The wall clock would probably be hard to make since the arms has to move constantly, plus it'll serve no practical purpose unlike the calendar where you can see when the special events are.

Why not have a digital wall clock instead? It would be useful for those people who use fullscreen but want to see the time.

**Comment by Tuxedoterroist** [comment]
they would still have to make the clock and redo it each time for the numbers to change

**Comment by SaiPrithvi123** [comment]
It isn't as hard as an analogue clock, plus it also has a use.

**Comment by TheRealBrickPlanetWail** [comment]
Best idea ever!

**Comment by ThePotatoGuy** [comment]
i think this would be actually pretty damn useful. maybe you'd have to `gift` monika the clock first....

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
