### ISSUE TITLE
[Bug] Piano

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2739]
I've been typing your reality and there seems to be another or extra type to keep with the song which is inaccurate, in other words, I've been stuck at the line "in my hand [extra erroneous note] is a pen...". The piano notes in the part of "in my hand..." should be like [opo uioiuyewq ewut] I thought it was just me but after some research, I can say that this is a bug

**Comment by jmwall24** [comment]
If you're in play a song mode you need to play the flourishes in addition to the melody.  The notes you list are correct for that line and work just fine for me.

**Comment by Chrissenpai** [comment]
I tried but to no avail, I think that is a personal bug can I send MAS to you to fix it?

**Comment by jmwall24** [comment]
At the end of this file it shows you exactly how to play it.  Make sure you match this.

https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/mod_assets/piano/songs/yourreality.json

**Comment by jmwall24** [comment]
Any luck?
