### ISSUE TITLE
[suggestion] letting monika learn some basic info about you

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#2740]
all of this this is probably in development but i just had ask. 

so i saw this one image on Reddit that had all the doki's reactions to learning how tall you are and it got me thinking of maybe implementing some sort of catalog monika can build of you (getting flashbacks to skynet over here) since she wonders what you're actually look like. maybe some basic questions like age, height, job, school, etc.

**Comment by Oharo** [comment]
I'm not sure how to properly reference other pull requests, but a topic has been created with this information and is awaiting approval / implementation.

Its' player's appearance #1568
