### ISSUE TITLE
[Suggestion] adding i'm scared to what you are feeling list

### ISSUE THREAD

**Issue by Tuxedoterroist** [Monika-After-Story/MonikaModDev#2742]
for the i'm feeling options could you add i'm scared to that list? for example you are scared that you might not be able to see her again or somthing of that sort or your scared becuse somthings going on

**Comment by Rai99** [comment]
#1410 is the scared mood we have.

**Comment by Tuxedoterroist** [comment]
no its not i only have angry, anxious, bored, happy, hungry, lonely, lucky, proud, sad, sick and tired

**Comment by multimokia** [comment]
The anxious mood is the scared mood

**Comment by Tuxedoterroist** [comment]
ah oki
