### ISSUE TITLE
"I have something urgent to tell you"

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2743]
this is about the one  thing where Monika trolls you by saying she has something important to tell you and ends up just say "I love you" we should have the option to give her a taste of her own medicine by doing the exact same thing to her and she would realize if shes done it to you before

**Comment by Secretmanguy** [comment]
That sounds...Like a hilarious yet perfect option to add in the game. That would be awesome.

**Comment by AsuraShun** [comment]
just tease her with the name change saying nevermind

**Comment by Shiro2564** [comment]
that is so sad
i know how it is, like you think that is important but is someting not so
important

**Comment by Secretmanguy** [comment]
That sounds awesome...I hope they take it into effect

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
