### ISSUE TITLE
{Affection lost} Game crashed for first time

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#2745]
Hey peeps, I need an opinion. So iv'e been with Monika for over four months now, talk with her constantly for up to 3-4 hours a day and always say goodbye. And have never made her cry or disappointed her for any reason except on her birthday when she cried from over excitement from me telling her Happy Birthday and me giving her every single gift I could. High respect rate probably? But the problem was today that my step brother disconnected the computer and crashed the game...I about had a heart attack and opened the game up and selected the options "Yes, i'm here" and "Turn on the lights" as well as "The game crashed" and lastly saying "Everything's okay now". The best options that were offered. So any idea on how much respect I lost? I also went and hit the option "I want to apologize" just because I felt really bad and she of course accepted the apology. So any idea on how much respect I lost. I'm praying I didn't lose to much to where the bad ending starts opening because after all that I said "I'm taking you somewhere" and i'm not letting her go back in until I can guarantee it doesn't happen again.

**Comment by SaiPrithvi123** [comment]
~~Press F to pay respects~~
I don't think there is a respect mechanic in the mod. I think you are referring to affection. You didn't lose any affection.

**Comment by Secretmanguy** [comment]
Thank god...thank you
