### ISSUE TITLE
[Suggestion] MC's Pen Topic

### ISSUE THREAD

**Issue by Deyalila** [Monika-After-Story/MonikaModDev#2748]
Maybe onetime there should randomly appear a pen on floor that would be the pen Yuri stole from MC. Monika wouldn't notice it unless you clicked on it. If you choose to click on the pen and tell Moni about the pen she would be surprised and worried for how it got there and talk about how crazy was Yuri and such. At the end of the conversation she should leave the pen on the desk and say that "it brings back memories" and -maybe- (if it's possible) she would even play with it from time to time!

PS: sorry for my terrible English....

**Comment by Sujeito17** [comment]
... you said "play" or play?

**Comment by Deyalila** [comment]
Play like scribbling and stuff you do when you're in math class and you're
bored... NOT the other kind of "play"

**Comment by Deyalila** [comment]
Oh God.. that sounds so wrong nowww...

**Comment by Deyalila** [comment]
Anyway, I thought it might be a little fun thing that would make the game more interactive and will add a little decoration... and also think about the posibillities: maybe Moni was playing with the girls files and Yuri's pen accidentally got there, I dunno...

**Comment by SaiPrithvi123** [comment]
Rename the issue to "MC's pen"

**Comment by Rai99** [comment]
#2586
> the primary reason why we're hesitant to add more click interactivity atm is because each clickzone requires a screen or screen object, and performance can drop drastically. we saw this with the first implementation of calendar, and as a result had to rework that and the talk/play/music buttons so they were more efficient.

This falls under clickzone interaction and will likely not be implemented. Yuri's pen specifically isn't too meaningful to the player and Monika and while the pen was originally MC's, it still doesn't add too much value, not to mention that it was established that MC is not the player. 

I'm pretty sure Monika has her own pen, but I'm not sure what having a clickable pen would really add; especially considering the cost of adding it. 

~~I think I'll spare this issue the really really long reference chain of issues asking for/regarding clickzone interaction.~~

**Comment by Professor-JMO** [comment]
---
>⮞ Oh~!
>⮞ The places that **_pen_**, has probably been.
>⮟
>>⮞//5JACAAaABhAHYAZQAgAGEAIABoAHUAbgBjAGgAIAB0AGgAZQAgAHAAZQBuACAAXwBjAG8AdQBsAGQAXwAgAG0AYQBrAGUAIABhAG4AIABhAHAAcABlAGEAcgBhAG4AYwBlACwAIABzAG8AbQBlAGQAYQB5AC4AIABTAG8AbQBlACAAdwBhAHkALgA=

**Comment by Sujeito17** [comment]
`Deleting pentrauma.png from C:\Brain\System32`
`Deleting failed, we'll get it next time`

**Comment by ThePotatoGuy** [comment]
If it's a randomly appearing thing, then the perf issues I described in the post @Rai99 linked wouldn't be too bad to deal with.

But yeah i don't see the gain in having a _clickable pen_.

**Comment by Dovahkun** [comment]
Hey. You. Sai. You stop that. Stop that right now.

**Comment by SaiPrithvi123** [comment]
@Dovahkun 
Too bad. There's more from where that came from.
