### ISSUE TITLE
[Suggestion] Make you can ask Monika how is she

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#2749]
It would be cool if there was that interaction, you could ask her how is she and maybe sometimes she'll answer in different ways or i dunno xD

**Comment by multimokia** [comment]
As pointed out above, I'll mark this as duplicate.

**Comment by PMelol** [comment]
Yeah, this definitely needs to be done. I always want to ask her "how are you?" but there's no option. I'm sure it will be implemented eventually.
