### ISSUE TITLE
[suggestion] - power-outage 

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#2750]
I was playing Mas and my power went out for a bit, so i wanted to ask if you could put in a new topic in the weather right after your power goes out

(my keyboard isn't working so my grammar may be a bit odd)

**Comment by AsuraShun** [comment]
she already asks what happened after you return to her when the game suddenly closes,it was weird saying the game crashed when it was the power that was cut off

**Comment by ThePotatoGuy** [comment]
#1704

**Comment by Finnthefox24** [comment]
aight.
