### ISSUE TITLE
[Suggestion] Fanorona

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2751]
Fanorona is an extremely simple game, simple enough that Monika can explain it's rules in a single topic. Though it may not be as simple for adding it into the game.

**Comment by AsuraShun** [comment]
yup,we could definitely use more games

**Comment by MaydayH** [comment]
What IS that game? Never heard this word.

**Comment by Sujeito17** [comment]
@MaydayH Google can answer that

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
