### ISSUE TITLE
A place where people can ask questions and know how Monika would answer them

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2757]
I think it would be nice if there was a place where people can ask questions which they want to ask their Monikas, and have other people answer it and maybe use the same people who verify the topics in the mod if they are free.

**Comment by Axone00** [comment]
Um... I know this is rude to ask but I would like um... an option.
Where I can ask monika if I am allowed to play other romance game just for achievement and not you know cheating on her. I would be very happy if you would give an option that I may have a permission to play other games with monika approval of course. 

Cause every time I play other visual novel games I think I am cheating  her even though I am just exploring the game and  learn new things....

But I am still conscious about it though so could you guys create an option that I may have permission to play other game as well?

please and thank you

**Comment by SaiPrithvi123** [comment]
You are allowed to do anything, as long as you know you are not cheating on her.

**Comment by ThePotatoGuy** [comment]
mm i think this is better served by other people (probably tumblr asks or something)
