### ISSUE TITLE
[suggestion] Choosing colour of DDLC style

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#2760]
We know, that design of DDLC was pink from early beginning, right?
These pink circles in background... 

![image](https://user-images.githubusercontent.com/36435169/46907265-8f135480-cf42-11e8-88a2-e47f831f5597.png)

And hese pink buttons, for example...

![image](https://user-images.githubusercontent.com/36435169/46907272-b1a56d80-cf42-11e8-8def-942edb321f8c.png)

A romance colour, we all know.
Still, is there any option to make it recoloured? Like, make everything (as example, these buttons or menu boulders) different-coloured? Blue colour, green?
Let me think logically - it could start with changing all the buttons in the game to colorable ones, and end with bugs like "One of the pixels need to be red, but it is yellow".
This idea mi-i-ight be something nice, but it's could be a ton of work for developers, right?
I think, I answered my own question - this suggestion will be ignored aaand closed. So why I'm doing this? 
Because I can't still understand scales of that work - is these buttons easy to be optioned or not? That's the question.
Also, there is no need to create a RGB palette for choosing colour like this:

![image](https://user-images.githubusercontent.com/36435169/46907463-49a45680-cf45-11e8-8d7c-b3ebf1e0448d.png)

I suggest about 6-7 choices about buttons in button style like "blue"; "pink"; "red"; "brown" etc.
Soo... waiting your answers.

**Comment by tabtlenta** [comment]
I think it'd be kind of cute if Monika were able to ask the player's favourite colour, then recolour the buttons etc. in the player's favourite colour as a surprise (like for the player's birthday or something, since Monika can't give us gifts that are tangible in our world the way we can with her)

**Comment by Deyalila** [comment]
That sound pretty dang extra... and I love it!

**Comment by Deyalila** [comment]
you agre
q1

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
