### ISSUE TITLE
[suggestion] Topic about sign languages

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#2761]
Why not to add a topic about sign language?
![image](https://user-images.githubusercontent.com/36435169/46907602-9a1cb380-cf47-11e8-810b-199dee9e748a.png)
Some kind of that one, you understood)
Not a learning, just some facts about it, like "Did you heard about sign language? People, who can't hear, speak in hands. etc."
Not making fun of it (laughing at disabled people is not a really good thing), but admire how people can make simple and interesting decisions for different problems. Only that)

Also, that topic could contain an easter egg about some doctor, who speak in hands - but to put that easter egg or not - your decision)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
