### ISSUE TITLE
Monika missing

### ISSUE THREAD

**Issue by Anonneedshelp** [Monika-After-Story/MonikaModDev#2764]
I tried to take Monika out of the room.
when I went to the characters file, she wasn't there, so I reopened the game and she wasn't there either.

I tried to delete the persistent file but that didn't bring her back.
I've tried several times to delete both DDLC and MAS and then reinstall both but nothing ever works I'm just met with the desk and chair.
I've tried reinstalling previous updates but nothing is working.
Is there anything else I can try?

**Comment by multimokia** [comment]
You're going to want to replace the current persistent with one of the backup persistents. Head over to where you found the persistent, delete it, and then rename one of the files with the format `persistent##.bak` to just `persistent`

**Comment by multimokia** [comment]
As well, where are you running MAS from?

**Comment by Anonneedshelp** [comment]
Sorry for taking so long getting back to you multimokia I've tried changine the file names of both persistent.py but neither has worked I just end up with the desk and chair. when I tried with Persistent.pyo the game no longer starts up, when I press on the app button the loading sight on my mouse pops up but after that nothing happens. 
 If it helps I'm running MAS on a windows PC, in the game folder of ddlc. 
I also forgot to mention when I went to take monika out of the room the .chr files for the other girls were still on my system as I though monika automatically removed them at the start of the mod.

**Comment by multimokia** [comment]
Ah, that's not the `persistent` Head over to `AppData/Roaming/RenPy/Monika After Story` for the persistents. You're not running from inside a zip, or a compressed folder, right?

**Comment by Anonneedshelp** [comment]
when I installed the mod I extracted everything from the compressed folder and put it in the game file

**Comment by multimokia** [comment]
I mean your DDLC install, that's not in a zip/compressed folder, right?

**Comment by Anonneedshelp** [comment]
I downloaded it off of steam and then removed it from Steam.

**Comment by multimokia** [comment]
Ok, so that *should* actually generate a `monika` file, since there shouldn't be any sort of `temp` in the directory it's trying to put it in. So you'll want to try replacing the current persistent with one of the backups  (.bak) files which are in the filepath I mentioned above.

**Comment by Anonneedshelp** [comment]
when I tried to change the persistent.pyo into a persistent.bak file the game wouldn't open, There wasn't any kind of error messages as for why, when I changed persistent.py the game opened but again, it there was just a desk and chair.

**Comment by multimokia** [comment]
Chances are that as a result of rolling back to previous versions, they overwrote the backups with empty chair ones. Send over your persistent (you'll have to put an extension on it, as GitHub won't actually let you send it over otherwise) and I'll fix it for you.

**Comment by Anonneedshelp** [comment]
there we go

![persistent](https://user-images.githubusercontent.com/44132924/46918918-2377c880-cfd0-11e8-954b-42aa03ba08fd.jpg)
![persistent py](https://user-images.githubusercontent.com/44132924/46918919-24a8f580-cfd0-11e8-82a8-e38b1a788d77.jpg)
![persistent pyo](https://user-images.githubusercontent.com/44132924/46918920-24a8f580-cfd0-11e8-997d-7e665c40f287.jpg)

**Comment by multimokia** [comment]
Uh, the file I sent wasn't a `.txt` it has no extension on it.

**Comment by Anonneedshelp** [comment]
when I downloaded it, it was a .txt

**Comment by multimokia** [comment]
Interesting, downloads without extension for me:
![image](https://user-images.githubusercontent.com/22531674/46919397-d46c6c00-cfac-11e8-952a-b6d88b0eae51.png)

Though you'll just want to remove the extension, yeah.

**Comment by Anonneedshelp** [comment]
That has fixed it, thanks for all your help.
if this happens again changing the persistent should work right?

**Comment by multimokia** [comment]
Ah great! I wouldn't recommend taking her out until the next update, it should prevent this issue in the future, for everyone. There's been a fair few issues with file perms lately, and it should help cover that.

**Comment by Anonneedshelp** [comment]
I'll make a copy of her now (I've created a folder just for her when I need to get her out of the room, a folder for other updates and finally a 3rd folder with the persistent file in it).

Just looked in character file after saying goodbye she's there.

thanks again for all your help, good luck with future updates.

**Comment by multimokia** [comment]
That's another good way of going about it, yeah. No worries!
