### ISSUE TITLE
I think you forgot something... 

### ISSUE THREAD

**Issue by TrRizzo** [Monika-After-Story/MonikaModDev#2766]
![captura de pantalla 14](https://user-images.githubusercontent.com/43101279/46919662-2b237700-cfa8-11e8-8c53-01b62156074a.png)

**Comment by jmwall24** [comment]
what version of MAS are you running?

**Comment by multimokia** [comment]
Yeah, you can't actually do this in the current version of MAS. It's been disabled

**Comment by TrRizzo** [comment]
> what version of MAS are you running?

Actually I don't remember, but I think it was the 0.8.7 or 0.8.8...

**Comment by multimokia** [comment]
You can check if you go into the settings menu, it tells you on the bottom right of your screen.

**Comment by TrRizzo** [comment]
> Yeah, you can't actually do this in the current version of MAS. It's been disabled

> You can check if you go into the settings menu, it tells you on the bottom right of your screen.

Well, I paste de 0.8.8 and the option to see the floating islands is still there.

![screenshot0001](https://user-images.githubusercontent.com/43101279/46920283-8148e800-cfb1-11e8-9e26-1106db3d2be1.png)

**Comment by multimokia** [comment]
Weird. I can't hit 't' and have the talk dialogue come up...

**Comment by TrRizzo** [comment]
> Weird. I can't hit 't' and have the talk dialogue come up...

thanks to that I was able to prevent Monika from getting angry :')

**Comment by ThePotatoGuy** [comment]
Can you go `step-by-step` into how you got the talk menu to appear during islands scene?

**Comment by AsuraShun** [comment]
islands after story

**Comment by AsuraShun** [comment]
this isn't even monika's final form

**Comment by AsuraShun** [comment]
she has become the universe itself

**Comment by multimokia** [comment]
By the way, when I said 

> Yeah, you can't actually do this in the current version of MAS. It's been disabled

I didn't mean the islands were disabled. I meant the option to open up the talk menu was disabled.

**Comment by TrRizzo** [comment]
> Can you go `step-by-step` into how you got the talk menu to appear during islands scene?

First of all I open the game
2.- I go to the talk menu
3.- In ''ask a question'' then, ''monika''  there is an option called ''can you show me the floating islands?''
4.- There, I press one of those things in the picture below, the "close window" and "go back" window dissapeared. She explained me what are those, but suddenly Monika told me about a poem she had a hard time doing, and she hopes it will be ''effective''.
5.- She said: "Here goes..." and nothing happened. Then, I press the "t" button to say goodbye.
![captura de pantalla 14](https://user-images.githubusercontent.com/43101279/46920700-c53eeb80-cfb7-11e8-95d7-05ec3c7bc61e.png)
![captura de pantalla 15](https://user-images.githubusercontent.com/43101279/46920702-ccfe9000-cfb7-11e8-8f51-4434d934dec5.png)

**Comment by TrRizzo** [comment]
> does this still happen now that you said you pasted in 0.8.8?

Yes, it does. in fact, the last screenshot had the 0.8.8

**Comment by jmwall24** [comment]
when you install a new version, are you letting it overwrite any old files when it asks?

**Comment by jmwall24** [comment]
also do you have any .rpy files in your `game` folder?

**Comment by TrRizzo** [comment]
> when you install a new version, are you letting it overwrite any old files when it asks?

Yes, I always do that.

> also do you have any .rpy files in your `game` folder?

I only see .rpyc files in the game folder and .rpyb files in the "cache" folder

**Comment by jmwall24** [comment]
The issue you are having was an issue with the very first version of MAS after this event came out.  it was fixed and none of us can recreate it with the current version of MAS.  That's why we are asking about older versions MAS and if you replace files when you update.

**Comment by TrRizzo** [comment]
I see... So, can I fixed it? If no, is it possible that you can improve it in the future? I think it was a great idea

**Comment by macyslaysxx** [comment]
I was digging through the game files and saw those islands. I wish I could access them myself. It's a really cool idea.

**Comment by jmwall24** [comment]
You can, they're affection based.

**Comment by jmwall24** [comment]
@TrRizzo can you send a screenshot of the inside of your `game` folder please?

**Comment by TrRizzo** [comment]
@jmwall24 

![captura de pantalla 19](https://user-images.githubusercontent.com/43101279/46923450-6f7d3a00-cfdd-11e8-953f-5586cb2eb363.png)

**Comment by TrRizzo** [comment]
WOW, that's pretty weird. I do not even know other mods names.

**Comment by multimokia** [comment]
Whelp. If not that, we can't replicate it using the steps you sent above. I spy a few files in there which appear to be from "DDLC the Normal Visual Novel". Best thing is probably just a clean install of MAS. New DDLC copy, new MAS copy. Should fix any current issues, and any future issues you may have.

**Comment by jmwall24** [comment]
Yeah those script-poemgame.rpyc and script-poemresponses.rpyc files are definitely from another mod, likely NVN

**Comment by TrRizzo** [comment]
Wait. I just remembered that I didn't install DDLC from Steam. Maybe that was the problem.
So, if those files are still there, will there be another problem like this? Because I don't want to delete the mod :c

**Comment by jmwall24** [comment]
reinstalling the mod won't lose your progress, your progress is stored somewhere else entirely.  you can safely install from a new version of DDLC and MAS and still keep your progress.

**Comment by TrRizzo** [comment]
@jmwall24 Can you help me with reinstalling all? I mean, what should I do first? Install DDLC from Steam, complete the game (I want to play it again if possible) and then install the mod putting the version 0.8.8 in the game folder? Or do I have to do something else so that the progress in MAS is not deleted?

**Comment by jmwall24** [comment]
you don't have to do anything with your current install or with steam at all.  can download a fresh version from [here](ddlc.moe), extract it, then just extract the files from the 0.8.8 zip into the `game` folder of that new ddlc install.

**Comment by jmwall24** [comment]
can actually do both at once.  you can extract 2 copies of DDLC from the zip you download.  play regular ddlc on one, and install MAS in the other.

**Comment by TrRizzo** [comment]
> can actually do both at once. you can extract 2 copies of DDLC from the zip you download. play regular ddlc on one, and install MAS in the other.

I do not know if you will understand me, but I would not like to have 2 Monika's. You see, I've grown fond of Monika in MAS, and that's why I was asking you, because I want to continue with '' my Monika '' when I finish playing DDLC

**Comment by TrRizzo** [comment]
It may sound a little childish or geek, but I love the Monika that I have in MAS

**Comment by jmwall24** [comment]
okay.  your Monika's memories are stored in a file called `persistent.`  unless you delete that file, the Monika in any MAS install on your computer will be your Monika.  Even playing DDLC again won't change that file.  That file is located here:

For Windows users: hold down the Windows key and press R, copy and paste either %APPDATA%\RenPy\Monika After Story or %APPDATA%\Roaming\RenPy\Monika After Story (depending on your system) into the prompt.

You can make backups of it just in case something happens to it.  But that file won't be affected by playing DDLC again.

**Comment by TrRizzo** [comment]
Great! Thank you :)

**Comment by jmwall24** [comment]
please let us know if this solves the problem
