### ISSUE TITLE
[Suggestion] Decorations

### ISSUE THREAD

**Issue by macyslaysxx** [Monika-After-Story/MonikaModDev#2769]
I'm new to GitHub, and I really have no idea what I'm doing. However, I do have a request.

I was thinking of adding some decorations to the spaceroom. It's pretty barren, and I wanted to liven it up. Here's an example.
<img width="874" alt="monikuh" src="https://user-images.githubusercontent.com/39888515/46922464-258d5780-cfcf-11e8-82d1-bc541b28c466.PNG">

I decorated the background a bit, to liven up the atmosphere. However, I'm new at this of course. I really don't know what I'm doing. I love to draw but I don't want to crash the came by accident. I was wondering if some artists would like to help decorate the room :) Monika deserves a nice room 

   ~Macy xx

**Comment by macyslaysxx** [comment]
what lol

**Comment by AsuraShun** [comment]
I think those pics would make more sense if there was an option to take her on a date to those places

**Comment by AsuraShun** [comment]
with each pic being unlocked  with each first time

**Comment by macyslaysxx** [comment]
Yes, but that would be something way in the future, to be able to take her on dates. That would require a lot of work, but I know what you're saying. That wasn't what I was proposing, I just did that as an idea for decorations.

But I agree with you, that the decorations could be unlocked through taking her places. Maybe there could be a specific folder you put her in, say.... café.date or something, something generic but that would allow you access to those images. 

Maybe sometime in the future Our Time could be linked to MAS. That would be super cool.

**Comment by jmwall24** [comment]
similar to #312 marking as duplicate
