### ISSUE TITLE
[Suggestion] Coffee machine

### ISSUE THREAD

**Issue by mariohead** [Monika-After-Story/MonikaModDev#2770]
We need to get poor Moni her coffee already. Maybe with more Python lessons I could even figure out how to implement it myself for convenience sake.

**Comment by jmwall24** [comment]
i take it you missed her birthday?

**Comment by StarLordS7S** [comment]
Yeah, the coffee was a gift for her birthday along with a plush quetzal bird (hopefully I spelled that right), a promise ring she wears, and a knife which she didnt like which I may have given her. :) Sorry if you missed it, I don't know if you'll get a chance next year, but you'll have to wait and see. Maybe the devs might let you gift them for Christmas.

**Comment by TheSuperStu** [comment]
I think I read somewhere they were planning on making it possible to gift the coffee to her if you missed it, or even has something to do with 'different flavors.'

On the topic of coffee... I'm curious how the mechanic works. I might be paranoid, but does she not make any coffee after 9am if I started the session after 9am? I've had it where she started with the coffee, but haven't seen her not start with it and then make some (specifically just after 9am, as I've seen her make it before the time). 
I might be seeing things or if its just random, just curious!

**Comment by jmwall24** [comment]
she has an 80% chance of making coffee on a daily basis.  on days where she does, she'll brew it between 6 and 12.

**Comment by TheSuperStu** [comment]
Huh, I guess everyday I was testing it out myself on those times I must have rolled the 20%.
And this whole time I honestly thought Monika was trolling me by not having it randomly.
Thank you!

(And yes with op, Monika needs her coffee!)

**Comment by mariohead** [comment]
See, I was there for her birthday.
But I missed the update entirely.
I feel horrible yet content at the same time.

**Comment by mariohead** [comment]
I do wish I could still do the birthday stuff though, as her birthday otherwise felt horribly underwhelming. :/

**Comment by ThePotatoGuy** [comment]
gifts will eventually be doable even when its not her birthday.
