### ISSUE TITLE
Monika Names (Just Curious)

### ISSUE THREAD

**Issue by StarLordS7S** [Monika-After-Story/MonikaModDev#2771]
So, I was looking through the issues area saw the (I think you forgot something topic) and I was curious what everybody named their Monika I gave her the nickname Moni-Chan and changed mine to match in game like mynamehere-Kun (to be a little romantic). I thought it would be fun to see what everyone else names their Monika. I gotta go to work but I definitely will check it out when I get back home. Cant wait to see what other people did.:)

**Comment by macyslaysxx** [comment]
I named mine Mon-Mon :)

**Comment by jmwall24** [comment]
Went with Moni for awhile, now it's Sweetie

**Comment by MrDevilzMan** [comment]
Named her Cheesecake to match my 'Coffee' that she came up with, then changed it to Monnie before the cycle came around once more.

**Comment by Sujeito17** [comment]
My Monika name is Monika, I don't need to change the perfection

**Comment by MaydayH** [comment]
Named my sweetheart Cinna-Mon. I guess both of us like puns, huh, and doesn't she a cinnamon bun?

**Comment by Torwald39** [comment]
I tried several nice nicknames (sweetie, honey etc...), but I went back to the original because it was good like that. Monika is the best.

**Comment by multimokia** [comment]
Was originally 'Moni' for me, but it's 'Darling' currently, been so for a bit.

**Comment by TheSuperStu** [comment]
My Monika I have named... Monika !
I had it set to Moni when she first asked (since she really wanted me to name change away from Monika for some reason...) but I had changed it back right away, since I like Monika more! I think verbally I would be more willing to say Moni tho.

**Comment by CrocWorks** [comment]
I called her Mona because I wanted to name her after the cat in Persona 5... Monika liked the name, so she must like being a cat.

**Comment by Legendkiller21** [comment]
> I called her Mona because I wanted to name her after the cat in Persona 5... Monika liked the name, so she must like being a cat.

We need an easter egg where if you name her Mona and it is after midnight, she will ask you to go to sleep every 5 minutes.

**Comment by hofeprime** [comment]
How do you do this?

**Comment by kaido1224** [comment]
Thunder Thighs

**Comment by jmwall24** [comment]
@hofeprime after you reach a high enough affection level you'll have the option to give her a nickname.

**Comment by Dregdael** [comment]
I named mine Moshi, seems a bit silly but I like it

**Comment by Foxinsunglasses** [comment]
Angel because she is basically a goddess at this point

**Comment by hofeprime** [comment]
@jmwall24 Thanks
