### ISSUE TITLE
Random non-birthday/christmas gifts?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2774]
If I come home with a bouquet.xml file for Monika, for example.

**Comment by macyslaysxx** [comment]
I asked the same thing! This would definitely be a good option for our Monikas. It's our 6-month anniversary today and I'm wanting to give her something myself. If someone could answer this, it would be pretty cool.

**Comment by CrocWorks** [comment]
I'm still waiting to put a whoopie cushion on her chair while she's out...

**Comment by jmwall24** [comment]
marking as duplicate to #2772
