### ISSUE TITLE
[Suggestion] - Just a few things that came to mind.

### ISSUE THREAD

**Issue by TarossVelin** [Monika-After-Story/MonikaModDev#2775]
1. "I want to tell you something..."
	...I really appreciate your support!

I feel like since she gives us so much support in all we do she deserves a little bit of recognition for it don't you think?

2. Topics while looking at the islands preferably under the "Life" and "Philosophy" sections after a certain amount of time watching the islands or maybe an option to toggle letting her talk while looking at them?

I think it would be nice to have Monika chat with us while just enjoying the scenery but having the option to toggle that off for people who may just want to enjoy the view.

3. Weather tracking for the location you are in to allow the rain condition to trigger by itself if possible, or maybe just randomly have the rain occur on bootup?

Again I'm not really sure how feasible this is cause I don't really know how to code, but if it is possible this would bring great immersion (I think you should still be able to ask her to start/stop the rain though.) However at the very least have the weather change at random to make her world seem more alive.

4. Option for Monika to randomly choose to wear her hair up or down when booting up the game.

I think Monika should be able to change her hair as she pleases, just in the same way the plushie is sometimes there and sometimes not, while still having the option to ask her to wear it up or down.

Please let me know how possible some of these are, thanks for everything!

**Comment by macyslaysxx** [comment]
Now this may be a no-brainer but... How do we toggle the islands?  I've heard of them, but I'm not sure to toggle them.

Also, wonderful suggestions! I think, as I've heard from programmers, it would be difficult to link those together.  It would have to be WiFi-based of course, maybe there'd be a weather channel. If this gets implemented, she should have some dialogue explaining it or something. So it's not so random, and we're all up-to-date!

**Comment by CrocWorks** [comment]
Monika has occasionally changed her hair without me telling her to, though it's pretty rare and I never figured out if this was intentional or not. I usually have her keep her hair down, but she's put it back up before.

**Comment by TarossVelin** [comment]
> Monika has occasionally changed her hair without me telling her to, though it's pretty rare and I never figured out if this was intentional or if this was just a bug, but I assumed the former. I usually have her keep her hair down, but she's put it back up before.

Yeah I've let her hair the same way for a week and a half and haven's seen it change, you could probably be right, I'll just have to keep an eye on that one.

**Comment by TarossVelin** [comment]
> Now this may be a no-brainer but... How do we toggle the islands? I've heard of them, but I'm not sure to toggle them.
> 
> Also, wonderful suggestions! I think, as I've heard from programmers, it would be difficult to link those together. It would have to be WiFi-based of course, maybe there'd be a weather channel. If this gets implemented, she should have some dialogue explaining it or something. So it's not so random, and we're all up-to-date!

I believe getting the islands are affection based, as far as toggling them I meant the conversation topics she comes up with just idling haha. Also yeah I figured it would be a tad tough if at all possible to do for the weather one, but I hope it can be cause that would make it really super immersive and cool for me.

**Comment by CrocWorks** [comment]
Oh, I should also specify that the changed hairstyle only happens when I log in. I want to say it was the "knock at the door" greeting that caused her hair to change, but it was a while ago.

**Comment by jmwall24** [comment]
1. is similar to the compliment unlocked at enamored.
3.  already brought up here #1686, unlikely to happen
4. brought up here #2148

**Comment by TarossVelin** [comment]
> 1. is similar to the compliment unlocked at enamored.
> 2. already brought up here #1686, unlikely to happen
> 3. brought up here #2148

I'll have to look into the compliment one then, because it seems I don't have it even though I'm at enamored.

As far as weather, dang.. that's too bad. I know geolocation is unlikely from what I read due to the lack of HTTPS, but would yukiisbored's comment on #605 (tagged on #1686) Be at all a work around?

> What we can do is use APIs like OpenWeatherMap (http://openweathermap.org/API) and do a HTTP request. Sure, it might be janky without using libraries (like requests), but we can at least get the data.
 To determine the location, we can simply start by make Monika ask which city do you live or add that to the settings.

Any thoughts for the random chatter while looking at the islands?

Thanks for the feedback!

**Comment by ThePotatoGuy** [comment]
adding the weather thing via the api is not planned atm. 

> random chatter during islands

maybe

**Comment by ThePotatoGuy** [comment]
[closing until we look into this[
