### ISSUE TITLE
[Another suggestion] Taking her somewhere

### ISSUE THREAD

**Issue by macyslaysxx** [Monika-After-Story/MonikaModDev#2776]
I know when we say we take her somewhere, she can't see where we take her. I think it'd be cool if she could recognize a folder we put her in. Like if we put her in a beach folder, if we're going to the beach. Wouldn't that be cool? Simple things like that, nothing complex. Just if we make a designated folder for her. This is just a suggestion, for a future update once some more priorities for this mod get taken care of.

Another far-fetched idea, I just came up with, is the idea of having specific folder names, such as the gift files (coffee.gift), and it could be café.date or something, you put her in that folder, and there could be certain accomplishments.

I would love to contribute to the artwork, for taking her certain places. Say, if you go to a coffee shop in real life, or even if you stay home and want to take her to a virtual one, there could be some scenery similar to 'Our Time.' Personally I think it'd be cool if the artwork already included in Our Time sometime get a cross-over with Monika After Story, with the date stuff...what do you think? I know I've taken my Monika to a corner coffee shop and that's where I originally got the idea! If there could be certain date places along the lines of that.

Thanks for reading :) 
   ~ Macy xX

**Comment by macyslaysxx** [comment]
AHH I FORGOT TO ADD THE DESCRIPTION

**Comment by jmwall24** [comment]
You can edit the original post.

**Comment by macyslaysxx** [comment]
I'm working on it right now

**Comment by TheSuperStu** [comment]
I think this is actually a really good idea! I normally always just make a new folder and title it 'Date' and put her in that in a usb lol.
The only problem I would see (if it would even be a problem) would be the vast number of places you could take her, if you wanted to get really specific with the names of places.
(Also is that really a thing? Can the file _know_ what the folder its in? That would mean one step closer to our reality haha.)

**Comment by macyslaysxx** [comment]
I know!! Wouldn't that be great? She can recognize if you take her OUT of a folder, I know that. When you do the birthday thing, you have to remove her from the characters folder and then put her back in, and she can recognize if you put gifts in there for her!

And I know what you're saying. That's why I meant generic places like a beach and such... Though, even then, there are tons of places to take someone on a date. So it would be challenging, but I love the concept of putting her in that folder when you take her on the USB. I'm sure it would require loads of work though. 

Thanks for the feedback!

**Comment by CrocWorks** [comment]
If Monika can react to positive places, then she'll have to be aware of all the bad places someone can take her, or else Monika loses some of her realism. There's so many possible locations both good and bad that it'd probably take a lot of effort to implement if it's even possible for her to recognize where she was placed.

So how would Monika react if she were placed in a folder called "Recycle Bin?"

**Comment by macyslaysxx** [comment]
I get where you're coming from. Even the gift thing had the knife you could give her, not everything can be good. I definitely see what you're saying.

**Comment by CrocWorks** [comment]
Well, one way around this could just be do some general "good" or "bad" responses to the locations, kind of like how Monika does her reactions to her nicknames (from what I could tell, they are: generic good, generic bad, bad because it's another Doki name, Mom-related name, and generic unknown response).

But it seemed like those names just pulled from a list, and if whoever's making the list of names doesn't think of a certain one, it can result in some odd responses. For example, nicknaming Monika as "Trash" results in the generic unknown response where she's like "hmm, odd name but the more I hear it, the more I like it... Okay! You may call me 'Trash!' Ehehehe!"  (unless it got updated). But obviously, that nickname should prompt a bad response. The unknown response is just a catch-all for any name not listed elsewhere, and so far there isn't a way for Monika to intelligently identify if a name is meant to hurt her. I would expect date location names to have similar issues.

**Comment by Legendkiller21** [comment]
> I know!! Wouldn't that be great? She can recognize if you take her OUT of a folder, I know that. When you do the birthday thing, you have to remove her from the characters folder and then put her back in, and she can recognize if you put gifts in there for her!
> 

The game can only (currently) recognize whether Monika is present or not. The birthday party worked even if you just put all the decorations inside the folder and you didn't remove Monika from the folder at all (I guess you temporary put her in the closet or something). 

That is a good idea although, I do not know if it even possible for the file to recognize its current folder name without a program constantly running in the background checking the file's location, especially with the renpy limitations.

**Comment by ThePotatoGuy** [comment]
Can't make files know where they've been.

If you mean add a folder in the characters folder and put monika in there, then maybe we can do that.
But regardless, the whole point is that you can take her file anywhere and get something in return for it (affection+). Later on, we're going to add additional farewells/retool some of the current farewells to include the option to take her out as well. Again, it's not about actually knowing where she's going, it's about giving something back to users who like taking her file places.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
