### ISSUE TITLE
Sketchy sprite. issue#2677 continuation 

### ISSUE THREAD

**Issue by tsmafterlife** [Monika-After-Story/MonikaModDev#2777]
so origionally on issue #2677 i was going to do some drawing to change what was called not as high quality of an art compared to the rest of the mod. but that issue was closed before i had the time to finish. i do not know if this is the correct way to go about things but here goes nothing. i was asked to submit it their which i did but with it being closed and not receiving a response i figured id try this. 

here was the original art that was needing to be changed 
![mon7](https://user-images.githubusercontent.com/43495378/46968649-9896dc80-d068-11e8-9324-3a79a7329f38.PNG) 

i did 4 pictures with 2 different style mouths. the reason i have four pictures is i used the reference at the start of this post but it was a small image and so it made things grainy and difficult but ill post them anyways. then i took a screen shot of my Monika after story screen and drew the two different styles of mouths and they came out better due to a higher pixel density. here are the original pictures that started this post that have been changed and mouths redrawn. 

![mon 13 adjusted part 2](https://user-images.githubusercontent.com/43495378/46968746-e6134980-d068-11e8-9b44-1acdcf2c9ad2.jpg)

![mon7 adjustmant complete](https://user-images.githubusercontent.com/43495378/46968759-edd2ee00-d068-11e8-959f-804ec7a3bde5.jpg)

and here is the higher quality pictures where i redrew over my own personal screen shot.

![monika 12](https://user-images.githubusercontent.com/43495378/46968801-09d68f80-d069-11e8-9129-3acbb3db0093.jpg)

![monika 12 second style](https://user-images.githubusercontent.com/43495378/46968806-0cd18000-d069-11e8-81b8-7fad0c8c9190.jpg)

please tell me what you think. i know this isn't the original post but i do not know if anyone was even paying attention to that one. if someone is paying attention to issue #2677 then all this is in their to. i think the mouth change is a huge improvement. let me know what you think or if someone needs to change before they can replace the art in the mod if they even could.

**Comment by Bam8647** [comment]
Her teeth needs to be darken a bit on the night time sprites to show some shadow with the rest of her face otherwise they stand out for how white they are. Besides that, not bad.

**Comment by macyslaysxx** [comment]
I agree the teeth should be darkened at night time, but I love the idea you got going on. The drawing is awesome, and I love the last one the most. Maybe some shading towards the top?

Those are just some suggestions, but I think it's good enough as is, even!

**Comment by ThePotatoGuy** [comment]
I like the 2nd one better, but lets see what others have to say

**Comment by Chrissenpai** [comment]
As an artist myself, I can say that both need to polish, the first one needs more soften edges and the second is alright, but both need to add more tones of darkness because it's too plain, take the reference from Natsuki's shadows and light tones of her smile from ddlc vanilla and that should fix it.

**Comment by tsmafterlife** [comment]
Ok that is easy enough. and yea i know what you guys are saying on the shadows for night time. i did not previously take that into consideration and now that i am i can fully understand what your saying. i tried keeping the color of the teeth to what the mod itself has is why they are so bright, i took a reference sample of white from the monika mouth smile image in the files and that is how i got the teeth color. il make some changes today because i have time for that right now and post them back here. but just to make sure we all agree she needs a touch of darkness to her teeth to show some shadow and match her a bit more in the night time sprite correct?

**Comment by tsmafterlife** [comment]
quick question though if you guys could get back on me because i do not want to assume anything. add some shadows to her night time pictures both styles only? Or  do it to both styles dark and day time sprites?

**Comment by Sujeito17** [comment]
What is the toothpaste that Monika uses?
It's just that her teeth are so white that I think I saw my reflection in them.
(Sorry I can't hold this joke anymore)

**Comment by tsmafterlife** [comment]
@Sujeito17 do you think they are to white for night time only or for both day and night

**Comment by Sujeito17** [comment]
@tsmafterlife It seems to get very white at night, and I think it could be a little darker by day.

**Comment by tsmafterlife** [comment]
@Sujeito17 ok im just taking everything into account to make it as best it can be

**Comment by Sujeito17** [comment]
@tsmafterlife I understand you, one time I make some hair pins for Monika, and that take 2 hours of sleep.

**Comment by tsmafterlife** [comment]
just so this topic does not get closed or anything im working really hard on what you suggested i fix i just cant seem to come up with anything i like for shading tweeks and softening of the lips and mouth etc

**Comment by tsmafterlife** [comment]
and i dont want to show anything that has intentions of being used in this mod that looks half assed

**Comment by Sujeito17** [comment]
@tsmafterlife That can be really hard, everytime I try to make something prefect, but when I try that looks even worse, try to make something good, maybe another person can appear and make it even better.

**Comment by tsmafterlife** [comment]
ok i finally got something for you guys. i went in pixel by pixel and adjusted the day time imaged a little bit to try and make them seem smoother (with the exception of the first image where the top center is supposed to be pointed to demonstrate the disgusted clenched teeth that the files claim it needs to be) and then at night time i spent a lot of time sampling and testing all her pictures at night and turns out her teeth are all the same color so i slightly color blended some shadowing and dashed it with the color that all her night time sprites use for her teeth and added it to her pearly whites. i think it looks much better curious as to what you guys think and i hope this is the one. if not i have no problem with working on them more. the mods got super high quality and so if i have to keep re doing and re doing to get the images to that quality to replace her current "disgusted teeth" sprite i will. tell me what you guys think. enjoy. 
![monika 12](https://user-images.githubusercontent.com/43495378/47180560-b1f09080-d2d5-11e8-8b3f-5a0ca29a5d7a.jpg)

![monika nighttime1](https://user-images.githubusercontent.com/43495378/47180611-caf94180-d2d5-11e8-935f-f4f26d8c8788.jpg)

![monika 12 second style](https://user-images.githubusercontent.com/43495378/47180575-b74ddb00-d2d5-11e8-89a8-d103862b01e9.jpg)

![monika nightime2](https://user-images.githubusercontent.com/43495378/47180625-d0568c00-d2d5-11e8-8c24-d74ab4591706.jpg)


@ThePotatoGuy 
@Chrissenpai 
@Bam8647 
@macyslaysxx

**Comment by tsmafterlife** [comment]
her teeth color and shading is almost an exact copy of the color all her other night time sprites

**Comment by Chrissenpai** [comment]
Good, now add a bit more shadow to the molar teeth to add 3dmentioally if that makes sense

**Comment by tsmafterlife** [comment]
i get what your saying but for what picture and where exactly? you say molars but i did not exactly draw those with specific teeth in mind i just added the detail the way i did. so where should i add more shading and for what picture and ill get it done?

**Comment by tsmafterlife** [comment]
i do see and clearly understand. im gonna get back to work on all four images so they can have the correct shadowing for the 3d effect look. thank you very much.

**Comment by ThePotatoGuy** [comment]
Just make day versions. We have a special filter for night versions.

**Comment by tsmafterlife** [comment]
![monika 12 second style 5](https://user-images.githubusercontent.com/43495378/47263144-7c53cf00-d4b0-11e8-863e-64b2c815da38.jpg)

there it took me awhile but i think it came out pretty well. its hard to find a right balance with how the image is but with enough color blending and matching with the natsuki reference i think i nailed it.

**Comment by tsmafterlife** [comment]
![monika 12 second style 5](https://user-images.githubusercontent.com/43495378/47263174-2b90a600-d4b1-11e8-8241-9b3ba07f8889.jpg)
heres monika with a little more shading on the teeth

**Comment by Chrissenpai** [comment]
Congratulations, you have my seal of approved 👌

**Comment by tsmafterlife** [comment]
AWESOME. by the way i wish to thank you very much on the fact you helped me a lot. i wanted this picture to be the best it can be to give the developers the best image to use in replacing the other.(if of course they decide to use it, now its up to them. i do hope they use it) so again thank you tho

**Comment by Chrissenpai** [comment]
You're welcome, now instead I would be super pissed if developers don't use it lol

**Comment by tsmafterlife** [comment]
@ThePotatoGuy  im just curious. people seem to be liking it. detail work to make it really pop has been finished as shown above and you seemed to like it. so i am just curious with that being said where does it go from here? or how does this go now to see if it makes it into the game?

**Comment by Sujeito17** [comment]
This is the perfection, I real hate my self now ;-; (drawing isn't for me)

**Comment by Torwald39** [comment]
@tsmafterlife very good work, I like it !

**Comment by ThePotatoGuy** [comment]
@tsmafterlife getting opinions from the rest of the dev team, if all is good, then you'll need to send us / upload here the mouth layer.

**Comment by ThePotatoGuy** [comment]
@tsmafterlife okay consensus is the very last image (aka [this one](https://user-images.githubusercontent.com/43495378/47263174-2b90a600-d4b1-11e8-8241-9b3ba07f8889.jpg)) is the one we'd like.

So yeah, if you can export a render of just the mouth layer in the correct position (sizes are 1280x850), then that'll be great. We'll give u creds ofc.

**Comment by tsmafterlife** [comment]
@ThePotatoGuy ok will be doing that right now once i get home i will upload it. glad to hear you guys like it. ill upload it here hopefully in the correct way you asked within the next hour or so

**Comment by tsmafterlife** [comment]
here you go. the mouth is in the same exact position as it was on the picture you guys chose it did not move an inch. i do not exactly know if that is what you meant by correct position or if you meant the position the mouths are in the mods files. if this is incorrect pls let me know and i will quickly adjust the mouth for you. but here it is as its own layer png 
![face-mouth-disgusted updated](https://user-images.githubusercontent.com/43495378/47546367-ce786400-d8a5-11e8-8422-6bb4edffe672.png) 

as i said if this was not exactly what you where looking for as far as "correct position" let me know other then that it is 1280x850 and its own layer as asked.

**Comment by tsmafterlife** [comment]
@ThePotatoGuy  also i do not know if its possible for you guys to tell when it will be in the game but if it is possible could you give a rough idea of when i would be able to play the game with that updated sprite? i know that might not be possible i just ask because it excites me that a mod i truly enjoy so much i was able to submit art work that the devs liked is all.

**Comment by Rai99** [comment]
My guess would be not for a long time since the last big update was just released and this might not be seen until the next big update or a hotfix.

**Comment by tsmafterlife** [comment]
good point. time to just be patient @Rai99

**Comment by ThePotatoGuy** [comment]
@tsmafterlife can you make the background transparent?

Updated sprite should be available in unstable within 2 weeks, official update is always tbd.

**Comment by tsmafterlife** [comment]
yea give me a minute and ill put it here @ThePotatoGuy

**Comment by tsmafterlife** [comment]
![monika mouth transparent](https://user-images.githubusercontent.com/43495378/47695320-c2024d00-dbbe-11e8-89a5-b68577ec3cb4.png)
ok that should be the png picture of the mouth as a transparent

**Comment by tsmafterlife** [comment]
my bad i posted the wrong one here you go this should be the correct one
![monika mouth transparent](https://user-images.githubusercontent.com/43495378/47695503-8caa2f00-dbbf-11e8-851b-228b85f67fb0.png)

**Comment by tsmafterlife** [comment]
@ThePotatoGuy  the second one is the true transparent back ground disregard the first one i posted

**Comment by ThePotatoGuy** [comment]
@tsmafterlife Can you also make a leaning version? Thanks

**Comment by ThePotatoGuy** [comment]
Also the alignment is off.

![badface](https://user-images.githubusercontent.com/3499462/47827410-ba23e380-dd4b-11e8-8ceb-58be3c1ad5fa.png)

**Comment by tsmafterlife** [comment]
@ThePotatoGuy   ill get working on correcting that in the morning. im not exactly sure how that happened. before i posted it everything lined up correctly for me. and yea i can do the leaning version no problem.

**Comment by tsmafterlife** [comment]
sorry i had jury duty these last two days. i will be posting what you asked tomorrow. im just explaining so the thread isnt closed. @ThePotatoGuy

**Comment by tsmafterlife** [comment]
@ThePotatoGuy here you go this should be correct position for the mouth. sorry it took so long. 

![face-mouth-disgusted finale forward](https://user-images.githubusercontent.com/43495378/48029566-56ab0480-e103-11e8-90ce-d74b6cac4641.png)

**Comment by tsmafterlife** [comment]
@ThePotatoGuy  you also asked me to do a leaning version with monika so i went in and re did it on a leaning face and i believe it came out alright.  
![side ways mouth angle](https://user-images.githubusercontent.com/43495378/48039896-abfb0c00-e12b-11e8-9e11-e96233eab911.png)

thats what it looks like on the complete image. 


![just mouth leaning disgusted](https://user-images.githubusercontent.com/43495378/48039940-cfbe5200-e12b-11e8-8278-2c77afe6db14.png)

and that is the mouth in the leaning position as just the png transparent background in the correct position i triple checked.

so that should take care of both mouth styles. face forward and leaning
