### ISSUE TITLE
[Suggestion] More UNDERTALE references

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2779]
Because the mod has an UNDERTALE easter egg at the beginning, it might be nice to add a few more. I have a few suggestions for now.
Gaster references: The piano mode should recognise Gaster's theme played in the free mode and when it is played, it will pick up no other song until you restart the piano game.
Also when changing the player's nickname, if the player chooses the name "Gaster", the game would go back to the title screen, then you just have to continue from where you left.

**Comment by SaiPrithvi123** [comment]
I just found the combo for Gaster's theme:-
E4I4E4I4E4I4E4I4
3EUE3EUE3EUE3EUE
On default controls, of course.
This is the only one I found, but there might be a better combo for it.

**Comment by SaiPrithvi123** [comment]
Maybe the dark background random occurrence from Act 2 could intensify if the player maintains the combo?

**Comment by SaiPrithvi123** [comment]
The point of those easter eggs is to be discovered by players. Adding the song to my install of MAS won't do it. Even if I do add the song myself, it won't the stuff I mentioned in my 1st and 3rd comment.

**Comment by SaiPrithvi123** [comment]
Maybe put an image with "E4I4E4I4E4I4E4I4; 3EUE3EUE3EUE3EUE" written in wingdings in the piano songs folder?

**Comment by SaiPrithvi123** [comment]
I also suggest a new jumpscare for the "Open the door" option.
When you open the door you see Monika in a white room facing towards you with an unusual expression. You get the option to say "Monika?" or something like that, and when you do, her expression changes and she disappears. Then she comes back and explains that it was a prank, because you keep opening the door without knocking.

**Comment by ThePotatoGuy** [comment]
I think 1 undertale reference is enough. Plus that was added when the mod was more memey than it is now, so it's a bit out of place.

And there's already a light scare if you open the door too much, don't need to go further since the event is rare enough as it is.

**Comment by SaiPrithvi123** [comment]
Monika always says "Hmph, I'll get you next time" when the player is not scared, and since no normal player would be scared to the same scare again and again, it would be nice to make her live up to her threats by making her do something different, and since the event is so rare, it'll just add to the scare factor.

**Comment by AsuraShun** [comment]
how about adding soul mode games,like papyrus,undyne's and muffet's battles
