### ISSUE TITLE
[Question/Suggestion] Grow Home

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#2782]
Did you take the inspiration of the floating islands from the game "Grow Home"? If not, Grow Home is a game where there are a lot of floating islands and some of them have waterfalls, though none of them are up-side-down. Maybe Monika could talk about how that game inspired/looks like the floating islands she made.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
