### ISSUE TITLE
[Suggestion] - about the ''game sudenly closing'' topic

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2783]
I don't know if someone mentioned this but,there needs to be a way to tell monika what she described is sensory deprivation torture,or at least have her say that she researched it and found out what it actually was

**Comment by TheGlader2** [comment]
Actually it sounds like she screams and then all of her thoughts and senses get splattered everywhere, not a overload or a void, but a cacophony of thoughts, feelings, sounds, lights and senses.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
