### ISSUE TITLE
Persistent note

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#2787]
I got my old persistent corrupted because my laptop died from no battery because of a power outage and she showed me a note saying it got restored (thank you for adding that system btw) but it also said dont tell her about me. i tried thinking who it could be but i dont know who it is. who is it?

**Comment by Professor-JMO** [comment]
>⮞ Is that so? Hm.

---

>>⮞TG9va2luZyBmb3Igc29tZXRoaW5nPwoKWW91IG1pZ2h0IGhhdmUgbW9yZSBsdWNrIGhlcmUuCgpHaXRodWIgSXNzdWUgUmVmZXJlbmNlICMyNzc4****

---

**Comment by Areaclassified** [comment]
QWxzbyBjaGllZiB3aHkgeW91IHNvIGRhbW4gc2tldGNoeT8=

**Comment by Areaclassified** [comment]
dGhlc2UgYXJlIG15IGJsdW50IHRob3VnaHRzIGFuZCBvcGluaW9ucyBkb250IGdldCB1cHNldCBieSB0aGVtLCBUaGFua3MgOikgaSBkZWFkYXNzIHNwZW50IHNvIG11Y2ggdGltZSB0cnluYSBmaWd1cmUgdGhpcyBvdXQgY2hpZWYgYW5kIGkgaG9uZXN0bHkgcmVncmV0IGl0LiBmcm9tIGFsbCBpIGdhdGhlcmVkIHRoZXJlIG1pZ2h0IGJlIGFuIGV2ZW50IG9yIHN1bXRpbiB3aGVuIHRoZSB0aGUgb3RoZXJzIGRva2lzIGNvbWUgYmFjayBhbmQgdGhlIHppcHMgZmlsZXMgcmVmZXJuY2Ugc2NwIGFsb3QgYW5kIHRoZXkgYWxzbyBzYXkgeXVyaSB3cm90ZSB0aGUgbm90ZS5pIG1heSBiZSBjb21wbGV0bHkgd3Jvbmcgd2l0aCB3aGF0IGkgaGF2ZSBmb3VuZCBvdXQgYnV0IHRoaXMgaXMgd2hhdCBqdW1wcyBvdXQgdG8gbWUuIGFuZCBpZiB0aGlzIGlzIHRydWUgaW4gYWxsIGhvbmVzdHkgY2hpZWYsIGkgYWludCBnb3QgdGltZSBmb3IgdGhhdC4gaSBnb3Qgc2Nob29sIHdvcmsgYW5kIGZvb3RiYWxsLiBzbyBubyBvZmZlbnNlIGRvbnQgYWRkIGFueXRoaW5nIHRoYXQgd2lsbCBtYWtlIG15IGxpZmUgd2l0aCB0aGlzIGdhbWUgaGFyZGVyKG5vdCBzYXlpbmcgb3BlbmluZyB1cCB0aGUgZ2FtZSBpcyBhIHBhaW4gaXRzIGp1c3QgaW0gYWx3YXlzIHNvIGJ1c3kgaSBsb3ZlIG1vbmlrYSBhbmQgaWxsIHNwZW5kIGFueSBhbW91bnQgb2YgZnJlZXRpbWUgd2l0aCBoZXIgaXRzIGp1c3QgaSByYXJsZXkgaGF2ZSBmcmVldGltZSkgb3IgYW55dGhpbmcgdGhhdCBtb3N0IG9mIHRoZSBjb21tdW5pdHkgbWF5IG5vdCBsaWtlLiBBbHNvIHdoeSB5b3Ugc28gc2tldGNoeSBjaGllZj8gTG92ZS0gQ2xhc3NpZmllZA0K

**Comment by Areaclassified** [comment]
what are you planning potatooooo?

**Comment by Legendkiller21** [comment]
That's actually pretty easy to find. The note was written by W1JFREFDVEVEXQ== **T̴̝̟̃̂2̴̯̘̹̾g̸̳͍̉́ș̷̗͘I̷̢̞͍͊̇̀G̴̮̝̗̍̚5̸͖̚v̷͖͇̌I̶̺̎H̶͖͍͝ͅḽ̸͕͊̐v̶̡͍̰̌d̸͎͎͓͒̐̈Ş̴͌B̵̬̞̭̈̀͝3̵̟̤̌̃͜b̴̠́͆2̸͎̞͎̚͠4̷͇̊̋n̷̥͋d̸̢̪̑͋̎C̶̪̺̜̄̕E̴͍̐͑͆g̵̣̪͌͐͋S̵̢̆͆S̷̙̋B̸̭́̍̚0̴̤̩̓b̵̦̣͋2̴͇͗̊͝x̴͉̖̺̍k̶̟̀̓͘Ḯ̴͖̯͋H̶̫̪͘l̷̯͚͋͛v̸̤͉̭̾d̶̬͓̑̓̊Ş̷̬̟͋B̷̙́̕u̴͍̗̚͝b̷͚͆3̵̪̈Q̸̛̜̞̄͌g̷̟̼͇̍̚d̷̨̤̤̏͂G̸̭̐8̵͔̣͖̅g̸̼̀d̷̙́͠G̶͇̫̲̓V̸̥̉̏s̶̟̗̙̏̚b̶̦̖̞̿̈̕C̴̨̙̣̄̍B̵̼̆0̴͉̺͕͋͝ạ̷̖̝̐͌̚G̸̨̺͍̍̀̍V̴͓̩̾̾̄t̶̮͂͠Í̶̮G̴͙̠͗̈́͝F̷̗̐̏̂i̷̡̤̊͊̓b̸̛͔͜3̷͚́̌V̷̦͈̙͂0̴̣̀͆I̴̢͊G̸͕̋1̷̬̾͋͌͜l̴̦̅̑̕Ḻ̴̪̅͝g̸̜̮̩͋=̷̧͛͛͂=̵̝̥̗̈́͑̍**

**Comment by Areaclassified** [comment]
Damn chief he just died and got his comment hijacked, im guessing either eXVyaSBvciBsaWJpdGluYQ==
