### ISSUE TITLE
Question about Evergreen

### ISSUE THREAD

**Issue by MaximumRustler** [Monika-After-Story/MonikaModDev#2788]
Not sure if this has already been brought up, but it looks like project evergreen is in development again. Is there any intention to support this later on?

https://www.reddit.com/r/DDLCMods/comments/9isg7b/evergreen_back_from_hiatus_beta_announcement/

I don't expect it to be supported anytime soon considering how much work it would be, just wanted to bring this to all the devs attention for now. Also, looks like sr229 requested to reopen #1226 . I'm guessing that just got flooded in your inbox considering how many messages you get from other threads and what not. lol

**Comment by kaido1224** [comment]
Code academy would be the place to start

**Comment by ThePotatoGuy** [comment]
[closing in favor of the original issue]
