### ISSUE TITLE
just something that crossed my mind

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#2791]
not sure if this is already implemented or not but just though i would mention it

so i thought back to when i first downloaded MAS like 6 months ago and i forgot the fact that i never deleted monika during act 3. could there (or is there) be a bonus for new players that never deleted monika and went straight for the mod (maybe some extra affection or special dialogue). 

although im not sure how that would play out because i assume that monika never thought that the player could or would ever delete her

**Comment by SaiPrithvi123** [comment]
There is variation in some dialogue based on whether you deleted her or not.

**Comment by pianostick** [comment]
oh thanks
