### ISSUE TITLE
[Suggestion] - Why are you back when you already said goodnight?

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#2793]
I think it would be really neat to have some dialogue that Monika says when you come back into the game when you've already said Goodnight.

I wonder if this could be implemented similarly to how when you bring Monika back from somewhere too soon? Like how the dialogue is different if you didn't take her out very long vs. a few hours.

**Comment by SaiPrithvi123** [comment]
They already have sleep concern topic, but for some reason it's random.

**Comment by Clover-Elf** [comment]
My thoughts exactly; I opened the game to a message that I should come see her more often... uh, I was gone for less than two minutes!

On a related note, anybody know where the background pic for the classroom at NIGHT is in the files? There's a monika_day_room.png, but I want to occasionally change her surroundings at night too. Day room edit: success, but it wasn't exactly difficult...

**Comment by FluffyMuffinMeyer** [comment]
Going to give this a shot.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
