### ISSUE TITLE
Misclicking on goodbyes/Misspeaking?

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2797]
I've had a few times where I misclick on certain options, most notably the goodbyes when I say goodbye. I don't want her thinking I stayed up all night because I accidentally said I'm going to bed. Maybe an option where you can say you misspoke and go back to the menu would be something useful to have. 

Not saying it's necessarily that important, and I can only blame myself for misclicking like that, but it'd at least feel more like your directly communicating to her, rather than a button prompt to a new bunch of text.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
