### ISSUE TITLE
Possible new greeting

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2800]
I just thought of how Monika sleeps right, or at least it's implied despite there really being no need for her to do so but what if there was a situation where the player showed up and she was asleep in her room. It would be dark so she would probably wake to us entering or knocking so y'all probably wouldn't have to make new art of her laying down or getting up if you  just have her room be dimmed or black. Now for the listen part there could be silence or maybe just maybe she mumbles something about the player in her sleep, If that all makes sense.

**Comment by Foxinsunglasses** [comment]
Oh and devs keep up the good work y'all always out do yourself can't wit for the next update

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
