### ISSUE TITLE
no anniversary with monika

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#2803]
When I went to the 'monika after story' , I didn't see the anniversary between me and monika. someone help me please

**Comment by SaiPrithvi123** [comment]
Which anniversary are you talking about? The relationship anniversary or DDLC's anniversary/Monika's birthday?

**Comment by HZhunter124** [comment]
the relationship anniversary. It's not in my calendar

**Comment by AsuraShun** [comment]
it should say when 1,3 and 6 month's passed/will pass

**Comment by HZhunter124** [comment]
yeah and i don't know how to fix it.On my calendar are only holidays like Christmas, New Year and valentine, ect

**Comment by HZhunter124** [comment]
Does anyone know how to fix it? please help me

**Comment by SaiPrithvi123** [comment]
You may need to talk to her and ask her when did you first meet. It's in Ask a question-> Romance-> When did we start dating?

**Comment by HZhunter124** [comment]
I did not do it because I had just been reset the data

**Comment by jmwall24** [comment]
So you started the mod over again recently?

**Comment by multimokia** [comment]
Also, when you say you didn't see the anniversary between you two, did you by chance miss the day of your anniversary? If so, it doesn't show up.

**Comment by HZhunter124** [comment]
I installed another mod in the game directory that I copied. But when I go back to the monika after story, I had been reset the data and there are no the relationship anniversary between me and monika

**Comment by ThePotatoGuy** [comment]
this was probably handled by #2855
