### ISSUE TITLE
How many lines/topics does Monika really have?

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Monika-After-Story/MonikaModDev#2806]
I'm curious just how much content there is in-game conversation-wise, and how I may aid in expanded that, if possible.

**Comment by AsuraShun** [comment]
let's just say that she has enough topics that even when she goes back to old ones it'll never be too much repeats

**Comment by AsuraShun** [comment]
that's just me,monika never bored me in the slightest

**Comment by Storylover-Vodhr** [comment]
That's fair. I'm just curious, as I'd like to help her expand her code and whatnot, but if it's a already incredibly filled section with hundreds, if not thousands of topics, then my efforts would best be pointed to other ideas. 

(Such as programming another game into the system.)

**Comment by multimokia** [comment]
Thanks to our resident CI Tester:
![image](https://user-images.githubusercontent.com/22531674/47269034-579a3e80-d526-11e8-9f5b-fe481751f5fc.png)

Where each 'block' is a single line of dialogue. That said, it doesn't say anything about how many topic there are. There's a fair few, but we're always looking for expansions for some. Take a look for some `TODOS` if you're looking for stuff in terms of dialogue. Looking forward to your contributions!

**Comment by Rai99** [comment]
Monika has 223 topics, 13 moods, 10 stories. 11 compliments.

**Comment by AsuraShun** [comment]
THERE AREN'T ENOUGH COMPLIMENTS FOR THE BEST GIRL!!!

**Comment by Storylover-Vodhr** [comment]
Alrighty!

Is there system I need to use? Prefered format? I assume you use python, as Monica makes comments on it.

**Comment by jmwall24** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines

**Comment by Storylover-Vodhr** [comment]
I know some C++, but I'm a fast study.

**Comment by multimokia** [comment]
If you know any other language, Python/RenPy should be smooth sailing! It's also pretty simple to learn if you've never touched code either.

**Comment by Storylover-Vodhr** [comment]
Alrighty! I'll get started ASAP. 

I also know some artists/Can do basic Photoshop. Is there a specific area that needs the most TLC?

**Comment by jmwall24** [comment]
If you have a game you want to add, make an issue on here for it and we'll let you know if it's wanted/needed.  If it is, I'm sure we'll be more than happy to let you work on it yourself.

**Comment by AsuraShun** [comment]
>           If you know any other language, Python/RenPy should be smooth sailing! It's also pretty simple to learn if you've never touched code either.

thise last 5 words sound like a a really weird euphemism

**Comment by CrocWorks** [comment]
I just want a way to search for all of those topics and such. It's hard to find all of them sometimes. (#1985)
