### ISSUE TITLE
greeting_returned_home Issue

### ISSUE THREAD

**Issue by FluffyMuffinMeyer** [Monika-After-Story/MonikaModDev#2807]
Whilst on discord discussing the maximum amount of affection being able to be gained daily, I stumbled upon an issue, here is an example.

[2018-10-18 20:03:04.227000]: SAVE | 1011.899982 | 1011.899982 -> 1011.899982
===================================================================
Thu Oct 18 22:08:28 2018
[2018-10-18 22:08:46.762000]: LOAD | 1011.899982 | 1011.899982 -> 1011.899982
[2018-10-18 22:09:19.008000]: !BYPASS! | greeting_returned_home | 5 | 1011.899982 -> 1016.899982

As you can see, the last time talked to monika was 20:03, and when she was returned home, at 22:09, two hours later, I was rewarded with a full 5 affection, rather than 2 for my two hours spent with her, as stated in the "Script Greetings"

            # (Lines 1764 - 1772)
            # you gain 1 per hour, max 5, min 1
            if hours_out > 5:
                $ aff_gain = 5
            elif hours_out == 0:
                $ aff_gain = 1
            else:
                $ aff_gain = hours_out

            $ mas_gainAffection(aff_gain, bypass=True)

I think this may just be an issue due to the order of the hours_out command?
Restructuring it as follows may fix the issue:

            # you gain 1 per hour, max 5, min 1
            if hours_out == 0 && hours_out !< datetime.timedelta(seconds=5*60):
                $ aff_gain = 1
            elif hours_out > 5:
                $ aff_gain = 5
            else:
                $ aff_gain = hours_out

            $ mas_gainAffection(aff_gain, bypass=True)

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent`?

**Comment by FluffyMuffinMeyer** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2499638/persistent.txt)

**Comment by ThePotatoGuy** [comment]
[closing since this was resolved on discord]
