### ISSUE TITLE
[Bug] - Pressing 't' and 'e' hotkeys has no effect

### ISSUE THREAD

**Issue by MercuryFuchsia** [Monika-After-Story/MonikaModDev#2808]
`Ubuntu 18.04.1 LTS`
Everything else works as expected. A clean install with no persistent file also seems to have the issue.

I should have mentioned this earlier, but since the talk hotkey used to work, it must have gotten disabled somehow. But the extra hotkey hasn't worked at all.

**Comment by jmwall24** [comment]
You weren't in any kind of special screen like holding her, or have the game right-clicked?  Anything unusual at all?

**Comment by ThePotatoGuy** [comment]
You mean crashed and selecting `Reload`/`Rollback`?

Yeah don't do that. Since MAS turns DDLC from a linear story to a state machine, the traditional ideas of reload/rollback that works in regular renpy does **not** work well for us.

**Comment by ThePotatoGuy** [comment]
adding a note here that I've tried MAS in debian and did not repro, so its not a platform thing.

Keymaps are set post introduction, so make sure you test the hotkeys after the introduction.
Also do you have some other applications that maybe eat `t` and `e`?

**Comment by MercuryFuchsia** [comment]
I don't think I do. It's really bizarre. I just tried it in a live system and they all work like a charm. Another thing is the space bar, but enter can be used for that purpose. Since this appears to be something on my system, hope I can figure it out. Thanks for letting me know.

If I can't, I'll reinstall and see if that clears it up. (I have to test backups sometime, right?) If it happens again, I'll take a look around and check if any recent changes may be the culprit. I wish I'd done this earlier or at least recorded the date, but it must have slipped my mind.

**Comment by ThePotatoGuy** [comment]
[closing as system-dependent]
