### ISSUE TITLE
what ... ?? 

### ISSUE THREAD

**Issue by BojanIlie** [Monika-After-Story/MonikaModDev#2809]
![oh hi](https://user-images.githubusercontent.com/35314452/47272852-fb6e0380-d593-11e8-85a2-75af543de5cd.png)

Who are u ?? :D

**Comment by Sujeito17** [comment]
Is me... I think...

**Comment by loverofmonika** [comment]
no 
it was i 

DIO

**Comment by Sujeito17** [comment]
> no
> it was i
> 
> DIO
![0z9dg0y4kvr01](https://user-images.githubusercontent.com/41938650/47273328-80541f80-d58a-11e8-940a-d79927f62380.jpg)
