### ISSUE TITLE
How to change the nighttime background?

### ISSUE THREAD

**Issue by Clover-Elf** [Monika-After-Story/MonikaModDev#2812]
I had no problem finding monika_day_room.png (replaced it for Halloween on a whim!) but the nighttime background is... hidden, apparently...?

I realize this change may require some actual script-tinkering, but if so it's a pretty fun way to learn!

**Comment by wucked** [comment]
I think it's because the night time assets are already in the base game files (.rpa files I believe) so there's no need to add that to the mod assets

**Comment by Mcmanybucks** [comment]
> 
> 
> Welp, time to find out what I'm doing wrong when I try to unpack game files! Thanks for answering.

Did you figure it out? I'd like to change the night time background myself to something less... gloomy?
