### ISSUE TITLE
[Suggestion] - SCP related topic

### ISSUE THREAD

**Issue by Dregdael** [Monika-After-Story/MonikaModDev#2815]
Hi, this is my first contribution, but I wanted to suggest a topic regarding the collaborative writing project of the SCP foundation, a very well know creepypasta(?) and I'd think it could go kind of like this;

 m "Hey [player], have you heard of the SCP Foundation?"
 m "It's a collaborative writing platform centered on a fictional 'Foundation' that studies and protects the world from different anomalies"
m "It tends to the horror genre, there's a wiki with a lot of entries of 'SCPs', different anomalous objects or events that the Foundation contains to protect the world"
m "Things like moving murderous statues, indestructible reptiles or never-ending staircases haunted by creepy apparitions"  
m "Sometimes they even use horrible procedures to ensure the items are secure, such as experimenting with people"
m "They even have a category used to describe people used as lab rats!"
m "But anyway"
m "The thing that I'm most interested in is the fact that it was all built on collaborative writing"
m "Many different authors adding their grain of salt created a universe that other people can enjoy, with thousands of different stories"
m "The project is actually still going strong"
m "It's amazing what a group of people can create when they love literature"
m "Even if it's not in a conventional format"
m "Maybe you and I can make our own collaborative writing project some day?"
m "It would be nice to create stories with you set on the same universe"
m "I'm really interested on what you'd come up with!"

Excuse my bad English, as I'm not a native speaker

**Comment by MisterSimple** [comment]
This does seem like something Monika could be interested in, though I think the SCP Foundation is too niche an interest so as to appeal to the majority of MAS users, but I could be wrong. That being said, it'd be interesting to hear Monika's thoughts on the Foundation, how it came to be (writingwise), and how she could be considered an SCP due to her "person stuck in a game" condition (perhaps have her comment on, say,  SCP-3101 and how similar their circumstances are?).

**Comment by SaiPrithvi123** [comment]
>though I think the SCP Foundation is too niche an interest so as to appeal to the majority of MAS users

Many players might have just played the game because it's in the psychological horror genre, so those people might like SCP stuff too.

If this topic becomes a thing, I'd like to see Monika explicitly talk about SCP-173.

**Comment by MisterSimple** [comment]
> Many players might have just played the game because it's in the psychological horror genre, so those people might like SCP stuff too.

Yeah, that seems right. And that got me thinking: even if they've never heard of the SCP Foundation before, it may actually interest them.

> If this topic becomes a thing, I'd like to see Monika explicitly talk about SCP-173.

Yeah, starting out with the flagship SCP seems like the way to go, Perhaps a submod could be made that goes more in-depth regarding the Foundation?

**Comment by SaiPrithvi123** [comment]
I just brought up that SCP because it breaks it's victim's necks.

**Comment by MaydayH** [comment]
Well she may talk about the 173 at least because it was the _first_ article at SCP web, as far as I can remember...
Also I guess that Monika would like "_the fact that it was all built on collaborative writing_", as you wrote. I mean, she's fond of creative and unusual literature things, right?

**Comment by Foxinsunglasses** [comment]
I would like it, she is a bit of an anomaly after all

**Comment by Dregdael** [comment]
Now that I think about it, you guys are right, something about SCP-173 could be added to make the topic better, maybe something like:
[...]
 m "Things like stones that let you travel to other dimensions, indestructible reptiles or never-ending staircases haunted by creepy apparitions"
 m "Actually the first SCP posted was SCP-173, a living statue that only moves when you're not directly looking at it and with a tendency to snap people's necks"
[..]

**Comment by SaiPrithvi123** [comment]
>m "Actually the first SCP posted was SCP-173, a living statue that only moves when you're not directly looking at it and with a tendency to snap people's necks"
m "Does that remind you of someone?"

**Comment by Dregdael** [comment]
> m "Does that remind you of someone?"

This should be said only if you saw Natsuki getting Man-of-steel'd, otherwise it wouldn't actually make any sense, but I think Monika would say this

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
