### ISSUE TITLE
a new topic or something about ddlc merch?

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#2821]
I saw that there were Monika plushies, so i thought about Monika's reaction... It would seem interesting.

**Comment by Dregdael** [comment]
> plushies

*Frantically checks bank account*

But really, I'd be pretty neat if she could tells us what she thinks about those or having one of the keychains from the Team Salvato store. Maybe she could think about them sort of like in the omamori topic, another way to be closer to her.

**Comment by MrDevilzMan** [comment]
I guess I could work on it, tho I don't know what Monnie would think about the rest of the merch because all I got is her keychain (that acts like a charm of sorts)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
