### ISSUE TITLE
[Bug]exp previewer unusable without crash

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#2823]
I was testing the exp previewer while zoomed in and thought about reporting this problem as seen here:
![untitled1100](https://user-images.githubusercontent.com/38822045/47398771-96d1b680-d703-11e8-88c1-247b74c7ebe7.png)
Yeah, you could just reset the zoom, but I think it would be useful to be able to preview expressions close up. 
It would also be really really useful to be able to enter in a sprite code and have Monika preview that expression in the previewer. 

---

Upon exiting the previewer, the game crashes. Upon selecting the reload option, that causes an issue brought up in #2808. 
I reset the zoom and tested again and still crashed. 

I am running v.8.8-unstable 2018.10.22.68

Contents of traceback: 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2508567/traceback.txt)

**Comment by ThePotatoGuy** [comment]
Use the latest exp previewer from the dev folder for unstable.
