### ISSUE TITLE
[Suggestion] In November, Monika talks about NaNoWriMo

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#2825]
It certainly seems like it would pertain to her interests as club president! She could talk about writing for sheer volume without editing as a strategy for combating writer's block, or question whether the novels that get written are any good (or talk about the "DecNoRejMo" phenomenon, where lots of writers submit their unedited novels to publishers and get rejected because it takes more than a month to write a decent novel). She could ask the player if they are participating, and say she's excited for them if they are

**Comment by Rai99** [comment]
I've never heard of this myself and my main concern is that it might not be well known enough to be put into MAS.

Another problem is time. It might be relevant now and be relevant for a month, but after that, it will be over and the topic would be out of date. Currently, I think the only seasonal topics are for the more well known holidays such as christmas and valentine's day. 

It seems interesting, but I'm not completely sure if it would fit into MAS.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
