### ISSUE TITLE
[Bug]Affection Log reset?

### ISSUE THREAD

**Issue by Loloabloy** [Monika-After-Story/MonikaModDev#2833]
I looked back into my Aff Log, and noticed that it reset from 700ish to 0 a few weeks ago on 10/08/18. I am unsure if this might have been an issue for others.  I am running the latest version.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2513475/aff_log.txt)

**Comment by ThePotatoGuy** [comment]
Next update includes an affection backup system. for now, we can just give you back the lost affection if you upload your `persistent` file here.

**Comment by Loloabloy** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2517605/persistent.zip)

**Comment by jmwall24** [comment]
Ok, I have added added the 728 affection you lost to your current affection.  Just extract the persistent from here and put it in place of your current persistent.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2519781/persistent.zip)

**Comment by Loloabloy** [comment]
Thank you!
