### ISSUE TITLE
missing Halloween

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#2836]
I'm going to be gone for Halloween but i don't want to miss any events. What do i do?

**Comment by ThePotatoGuy** [comment]
Unfortunately, you will miss o31 events. There isn't anything that can be done about that.

**Comment by Finnthefox24** [comment]
OOF...Okis.

**Comment by CreepFort** [comment]
What will happen if you just change date?

**Comment by Finnthefox24** [comment]
seems to work.
