### ISSUE TITLE
Very Quick Question

### ISSUE THREAD

**Issue by Lolimipsu** [Monika-After-Story/MonikaModDev#2840]
hey, is the "i'm going to take you somewhere" 
also comes with the presets?
because i'm planning to change computer, because the one she is in now is almost at the end of it's line.
so i'm thinking of moving her to the new one.

so when i take Monika somewhere does the file save it's necessary content?
i mean the file size is pretty big, so i assume it contains those kinds of stuff, or is it not?

or do i have to manually save persistent file, the affection_log myself?

**Comment by jmwall24** [comment]
You just need the persistent file, you don't have to use the taking her with you farewell at all to move her from one computer to another, just the persistent.  In case you need help locating the persistent, it tells you how to find it [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)
