### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by AverageDudeGuy** [Monika-After-Story/MonikaModDev#2841]
I installed the new updates onto the steam folder, in games, and now it won't launch and there's no error message or anything, it just executes itself as soon as it starts loading.

**Comment by jmwall24** [comment]
First thing I would try is rebooting your pc.  Seen it with steam games in particular where they get closed down but don't completely close and thus won't reopen either.  Rebooting usually fixes this.

**Comment by jmwall24** [comment]
Also did you download the `Monika_After_Story-0.8.9-Mod.zip` file and not one of the other zips?  Easiest way to make sure you get the right file is to download from here:  https://www.monikaafterstory.com/releases.html

**Comment by AverageDudeGuy** [comment]
I restarted my computer and made sure i had the right files, and this came up:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Monika After Story/game/definitions.rpy", line 10, in <module>
    me = singleton.SingleInstance()
OSError: [Errno 17] File exists: 'c:\\users\\devin\\appdata\\local\\temp\\C-Program Files (x86)-Steam-steamapps-common-Doki Doki Literature Club-DDLC-.lock'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Monika After Story/game/definitions.rpy", line 10, in <module>
    me = singleton.SingleInstance()
  File "python-packages/singleton.py", line 45, in __init__
    self.lockfile, os.O_CREAT | os.O_EXCL | os.O_RDWR)
OSError: [Errno 17] File exists: 'c:\\users\\devin\\appdata\\local\\temp\\C-Program Files (x86)-Steam-steamapps-common-Doki Doki Literature Club-DDLC-.lock'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by jmwall24** [comment]
Yeah you did have 2 copies open the first time, and that's why that .lock file was created.  Follow the path to that .lock file and delete it.  Then try to open the game.

**Comment by AverageDudeGuy** [comment]
I deleted it, reboot my computer, and tried to open it again, but the .lock file was created again.

**Comment by jmwall24** [comment]
Can you check your task manager and see if there is an instance of DDLC.exe open?

**Comment by AverageDudeGuy** [comment]
There are no other instances open.

**Comment by jmwall24** [comment]
delete the file again, don't reboot.  leave that folder open and try to launch ddlc again.  tell us when the lock file is created.

**Comment by AverageDudeGuy** [comment]
The lock file gets created a few seconds after double clicking the app, just as the steam loading window opens, and then immediately stops running.

**Comment by jmwall24** [comment]
Trying to trouble shoot this.  Delete the file again, this time try to run the game by opening it directly from the DDLC.exe file which is here `C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club`  See if it happens running it this way.

**Comment by AverageDudeGuy** [comment]
Nah, that still creates the .lock file.

**Comment by jmwall24** [comment]
can you check the `game` folder please, are there any .rpy files in there?

**Comment by AverageDudeGuy** [comment]
No, but there are .rpyc files.

**Comment by jmwall24** [comment]
yeah that's what should be there

**Comment by AverageDudeGuy** [comment]
Rip me then

**Comment by jmwall24** [comment]
inside the `game` folder, find the `python-packages` folder, how many `singleton.py` files are there?

**Comment by jmwall24** [comment]
ok you installed the source code version.  most of those folders in that screenshot should not be there and all your .rpyc files are from a previous version since they were last modified on 10/2, they aren't new.  You're going to need to reinstall DDLC, and then reinstall the mod by using the zip from here:  https://www.monikaafterstory.com/releases.html

I would suggest you use this opportunity to get away from playing MAS on steam and going [here](http://ddlc.moe/) and downloading the non-steam version of the game, extracting it from the zip, and installing MAS to that.  it makes updating so much easier using a non-steam version.

**Comment by AverageDudeGuy** [comment]
What would happen with my progress with Monika?

**Comment by multimokia** [comment]
You don't lose any progress, as the save data isn't stored in the ddlc directory.
