### ISSUE TITLE
yo, how i can change my 

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#2842]

**Comment by peter23247** [comment]
i accidently clicked on the yes, and now my birthday is today, wich isnt, so how can i change it? or at least, go back again

**Comment by jmwall24** [comment]
that option will be there again the next day.  just click it again and this time hit no and she'll ask you when it really is.

**Comment by Alan-Nuclear** [comment]
i dont even know how to set my birthday plz help

**Comment by multimokia** [comment]
Head over to: `I'm feeling -> A year older`
