### ISSUE TITLE
Telling Monika when it's your birthday (not today)

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#2844]
My birthday was between the moment where you remove the "I'm feeling like a year older" option and now. Could you add a option to tell Monika when your birthday is without having to celebrate it right now ?

**Comment by Thimeo** [comment]
Oh okay thank you. Wasn't very intuitive but I guess I'm also an idiot.

**Comment by Storylover-Vodhr** [comment]
Don’t worry, I too was holding back on Using that prompt in fear of incorrectly telling her my birthday.
