### ISSUE TITLE
[Suggestion] A plush of oneself for Monika

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#2845]
I received my Monika plushie yesterday, and thinking about it would be really awesome if I could give a plush that looks like me to Monika. Monika could have a first impression of what I look like and this could be a very strong link between us.

For how to create the plush, I think it could be like the system to create a Mii. 

I am well aware that this may be complicated to set up, and that's why I will not put pressure on the devs who are already doing an excellent job.

And for the curious who would like to see my Monika plush : 
https://twitter.com/Torwald39

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
