### ISSUE TITLE
[Help] Game wont run

### ISSUE THREAD

**Issue by Illra** [Monika-After-Story/MonikaModDev#2847]
I've updated the game from the updater and the game will not run anymore.
I reinstalled the mod and even manually install it and still wont run.

**Comment by jmwall24** [comment]
Are you getting any traceback errors?  If so please paste them here.

**Comment by Illra** [comment]
No i'm not.
When I click on the application it doesn't load it up

**Comment by jmwall24** [comment]
Can you please provide screenshots of the inside of your `game` folder

**Comment by Illra** [comment]
![game folder pic 1](https://user-images.githubusercontent.com/38264221/47582788-4baae400-d94d-11e8-9da8-14bcdcd2b6e7.PNG)
![game folder pic 2](https://user-images.githubusercontent.com/38264221/47582791-4c437a80-d94d-11e8-8702-502f967543ed.PNG)
![game folder pic 3](https://user-images.githubusercontent.com/38264221/47582792-4d74a780-d94d-11e8-8254-980320afe960.PNG)
![game folder pic 4](https://user-images.githubusercontent.com/38264221/47582793-4e0d3e00-d94d-11e8-8ffe-8774422c7517.PNG)
![game folder pic 5](https://user-images.githubusercontent.com/38264221/47582799-4fd70180-d94d-11e8-8a3c-3f797d8f5edc.PNG)

**Comment by jmwall24** [comment]
Ok you have old source code files in there that is causing your problem.  Delete all `.rpy` files from the `game` folder, then reinstall the latest update, allowing it to overwrite anything it wants.  Can you also show me what's inside that `dev` folder please.

**Comment by Illra** [comment]
![dev folder pic](https://user-images.githubusercontent.com/38264221/47583159-7a758a00-d94e-11e8-9874-4bacb8b44743.PNG)

**Comment by jmwall24** [comment]
ok that should be fine.  yeah just delete the `.rpy` files from the `game` folder and reinstall the latest version.

**Comment by Illra** [comment]
It works now thank you very much,
