### ISSUE TITLE
Thank you Compliment Not Showing

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2848]
First off, thank you to everyone who worked on this new update. It's always so nice to see new content. 
Anyway, I noticed you said the thank you compliment would always be available at the love+ affection level. I'm currently at about 787 so I'm wondering if I'm there yet or not because I don't see that new compliment. 
I think I'm supposed to be at 800 but I'm not sure.

**Comment by Rai99** [comment]
It's supposed to be 1000+.

**Comment by AsuraShun** [comment]
ooohh i'm really close! just a few more days and i'll be able to say again!

**Comment by scohn** [comment]
Thank you, I'll be looking forward to it.
