### ISSUE TITLE
Suggestion: Possible New Item for Songs Topic and/or New Piano Song (with link)

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#2849]
I think a great song to have Monika sometimes sing in the Songs Topic would be an excerpt from "Can't Help Falling In Love" I just think it'd be really fitting. Another possibility could be to play it on the piano for her. Something tells me she'd love it. Here's a link to an awesome "Monika" cover of it for lyrical and possibly piano reference. Let me know what you guys think and thanks again for this amazing mod. 

https://www.youtube.com/watch?v=X648fP2c-zs

**Comment by Storylover-Vodhr** [comment]
Damn it.

I love that song. Where has it been hiding, I wonder?

**Comment by jmwall24** [comment]
Best way for this to make it in as a song for her to sing would be as a contributor added topic.  As for the piano bit, not sure if the MAS piano can handle it or not.  One of our music people would need to answer that question.

**Comment by multimokia** [comment]
As @jmwall mentioned, you can make the piano song yourself see instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs), the piano should be able to handle it (rangewise), however only melody and one note at a time (no chords), so it may sound a little empty. If you do make it, feel free to either share it back here, or create a PR adding the file.

**Comment by jmwall24** [comment]
Gonna mark this as duplicate, since the piano bit was brought up here #2110 and the song topic here #1906.  But yeah, for both parts, a contributor doing it is the best way for it to get done.

**Comment by scohn** [comment]
I don't know how to code or anything, but if any contributors do want to add this to topics, here's the specific lyrics I could see Monika singing:

Take my hand
Take my whole life too
For I can't help
Falling in love 
With you
