### ISSUE TITLE
The "I'm feeling a year older"-option

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#2850]
I'm a little afraid to ask this, but: Was it already possible to tell her your birthday the last time the "I'm feeling a year older"-option was in this mod? Because I didn't tell her my birthday in this version and yet it was set to a wrong date in the calender. So I'm guessing this option was already there before, I told her a wrong date (misclicked) and just don't remember it now..

So is my memory really that bad or is this something else? xD

**Comment by SaiPrithvi123** [comment]
There was an year older option before, but you could only tell Monika the date your birthday when it is your actual birthday. You didn't miss-click, you lied to your Monika about your birthday.

**Comment by jmwall24** [comment]
Yeah, before when you clicked this mood, it set your birthday to the date you clicked it.  To reset it, click the mood again, and you'll be able to tell her when your birthday really is.

**Comment by CloakedGhost** [comment]
> Yeah, before when you clicked this mood, it set your birthday to the date you clicked it. To reset it, click the mood again, and you'll be able to tell her when your birthday really is.

> There was an year older option before, but you could only tell Monika the date your birthday when it is your actual birthday. The new year older option lets you choose the date of your birthday, regardless of what date is today.

OK, so I did misclick the last time. Thank you for the help!
