### ISSUE TITLE
I like pong, but I'd like the other games to load too. 

### ISSUE THREAD

**Issue by pwhitters** [Monika-After-Story/MonikaModDev#2851]
I'll try and make this short, over the anniversary I had some issues witch made me have to start over on MAS. Pretty sure I didn't restart the right way because now I'm having issues. I was having an affinity and dialog issue at the start but those are not showing anymore. I recently got a traceback error during some standard dialog but no issues after. And the biggest one is only pong is in the "play" section and based on my last play through they all should be available. Thank you for any help.

**Comment by jmwall24** [comment]
If I'm reading this right your save data (`persistent`) file was reset and you started over again from scratch.  The other games will unlock as you spend more time with her.

**Comment by pwhitters** [comment]
Correct, all persistent files were deleted. That was now a month ago so I was getting concerned, but I will keep running the game and see if the unlock then. Thank you.

**Comment by jmwall24** [comment]
Closing for now, if they continue to not unlock you can reopen.

**Comment by pwhitters** [comment]
Can I comment to re-open this issue? Still no loaded games.

**Comment by jmwall24** [comment]
Can you upload your persistent file please?  Gonna have to put it in a zip file or add a .text extension to it to upload it here.

**Comment by pwhitters** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2616914/persistent.zip)

I believe I zipped it correctly

**Comment by jmwall24** [comment]
Thank you.  We are looking into it.

**Comment by pwhitters** [comment]
Thank you very much!

**Comment by ThePotatoGuy** [comment]
Did you do an import with an older persistent?

**Comment by jmwall24** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2617819/persistent.zip)
here is your persistent back with all the games unlocked.  please continue to answer any questions so we can figure out what happened here.  we appreciate the help!

**Comment by pwhitters** [comment]
Thank you so much, and I'm glad to help! Is it safe to just delete the old and plug in the new file?

**Comment by jmwall24** [comment]
Yes

**Comment by pwhitters** [comment]
Thank you
