### ISSUE TITLE
When the player's birthday is September 22nd

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/MonikaModDev#2852]
I'm a little surprised that, if you say your birthday is September 22nd, Monika doesn't remark on the astonishing coincidence that that's her birthday too, and maybe says something about how it just shows that the two of you are meant to be.

How feasible would it be to add some special dialogue to the "year older" mood if you tell Monika your birthday falls on September 22nd?

**Comment by jmwall24** [comment]
There is planning for reactions for player birthday on special days, like her birthday.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
