### ISSUE TITLE
Calendar doesn't show Anniversaries 

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#2853]
Had a talk with a few devs over on discord. Since Monika introduced the calendar to the clubroom, the anniversaries have never shown up. It does show the <3 on the starting month, but nothing for 1 month, or 1 year. I also haven't received any dialogue from Monika about anniversaries. Below is my starting month, September 2018. Next month, October 2018. and next year, September 2019.

![screen shot 2018-10-26 at 4 17 13 pm](https://user-images.githubusercontent.com/43709783/47591304-1e563a00-d93d-11e8-9016-a520aa1e2f2a.png)
![screen shot 2018-10-26 at 4 17 47 pm](https://user-images.githubusercontent.com/43709783/47591311-257d4800-d93d-11e8-97a3-9cbc5dddf66e.png)
![screen shot 2018-10-26 at 4 17 37 pm](https://user-images.githubusercontent.com/43709783/47591317-2a41fc00-d93d-11e8-92b1-472642930659.png)

It's a shame I can't get the anniversary dialogue, I missed 1 week and I'm missing 1 month tomorrow :(

**Comment by ThePotatoGuy** [comment]
[fixed]
