### ISSUE TITLE
Expected Menuitem error

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Monika-After-Story/MonikaModDev#2857]
So, I keep getting the expected menuitem error through Ren.Py. It doesn't tell me what it wants, and referencing similar instances are yielding little results. 

Here is the code:

```
menu:
            $ colorname = renpy.input('What is your favorite color?',allow=letters_only,length=15).strip(' \t\n\r')
            $ tempcolor = colorname.lower()
            if tempcolor == "Red":
```

The "expected Menuitem" is 
`$ colorname = renpy.input('What is your favorite color?',allow=letters_only,length=15).strip(' \t\n\r')`
and it doesn't tell me what I'm failing at. I've adjusted it a half-dozen times, and I still haven't the slightest clue, and google is no help.

**Comment by Storylover-Vodhr** [comment]
I found a workaround, But I'd still like to figure out what I was doing wrong.

**Comment by MercuryFuchsia** [comment]
Is that the only `menuitem`? Try checking `tempcolor` for `"red"` instead of `"Red"` since you are using a lowercase method. I don't know much about renpy, but that's what sticks out to me. Good on you for working through all this, by the way.

**Comment by multimokia** [comment]
Ok, if you're trying to do that, you'll want to do the set for `colorname` before the menu. `menu` is for the buttons you click when Monika asks you a question. So, it's expecting a `string` as the text for the button, rather than an expression for variables, or a logic statement (`if`, in this case).

**Comment by Storylover-Vodhr** [comment]
Ah! Thank ya. 

I had it out of order, then?

**Comment by multimokia** [comment]
If you're just asking the player for their favourite colour, you don't actually need a `menu:`, as this shows up directly in the dialogue box Monika uses to speak to you.

**Comment by Storylover-Vodhr** [comment]
Oh! So, Menu is superfluous. 

That is very good to know.

**Comment by multimokia** [comment]
Yeah, all you needed was:
`$colorName = renpy.input("What is your favorite color?", allow=letters_only,length=15).strip(' \t\n\r')`

Now you can just reference `colorName` in the rest of the dialogue.

**Comment by multimokia** [comment]
Oh, minor thing, you're checking if `tempColor == 'Red'`
That condition will always fail, since `tempColor` is always in lower case. So:

`"red" == "Red"` returns `False`

**Comment by Storylover-Vodhr** [comment]
Really?

I actually got it running with a capital Red earlier...

**Comment by Storylover-Vodhr** [comment]
IT'S ALIVE

**Comment by multimokia** [comment]
Regarding running with the capital letter. It'll run, yes. But the condition will always fail, so any code within that `if` block is unreachable.
