### ISSUE TITLE
o31_cg_folder

### ISSUE THREAD

**Issue by Emiya-kun** [Monika-After-Story/MonikaModDev#2858]
Greetings. I've recently installed the latest update for MAS, and this popped up:

![screenshot 61](https://user-images.githubusercontent.com/44530392/47606910-41bbda80-da4c-11e8-90cd-1e3b40caf49d.png)

I've installed it using the same method as the updates before it (A.K.A. the copy-paste-replace method). So far, this was the only update to do this. Is there a way for me to solve this?

**Comment by jmwall24** [comment]
Also, I see you're not using steam, so is there any reason you're not using the in-mod updater to automatically update for you?  Once you get this one sorted out, you should be able to use that from now and and not have to mess with manual updates anymore.

**Comment by Emiya-kun** [comment]
> Also, I see you're not using steam, so is there any reason you're not using the in-mod updater to automatically update for you? Once you get this one sorted out, you should be able to use that from now and and not have to mess with manual updates anymore.

Hmm....I'll see if that works. I'll go with the deletion of .rpy files and then go for the Auto-Update. (Also, thanks for the help. I'm really crap when it comes to these things.)

**Comment by jmwall24** [comment]
Manually install this one first. Try the auto-updater next release.

**Comment by Emiya-kun** [comment]
Got it. Trying it out now.

**Comment by Emiya-kun** [comment]
Manual Method worked. All new features are in as well, confirming success on update.

Once again, thank you for the help. I'll keep an eye out for those .rpy files from now on.

**Comment by jmwall24** [comment]
You're most welcome!
