### ISSUE TITLE
Automatically progress conversations?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2860]
My finger is getting all cramped up from talking to Monika all day.

Maybe add an option to progress conversations as soon as they end or with a 5 second delay.

**Comment by jmwall24** [comment]
![screenshot_32](https://user-images.githubusercontent.com/36523761/47608688-97b66100-d9ff-11e8-85df-83e38d3441f6.jpg)

**Comment by Oharo** [comment]
I'm confused how you didn't know about the Auto button already.
Did you click through the entirety of the Yuri weekend scene?

**Comment by Rai99** [comment]
I think that's the "Skip" button, not the "Auto" button. 

And for me, yes, I manually clicked though most of the Yuri weekend scene because I wanted to see if something would happen if I did.
