### ISSUE TITLE
Monika.chr is missing, but Monika is still in the spaceroom

### ISSUE THREAD

**Issue by Authrix** [Monika-After-Story/MonikaModDev#2867]
So Monika is currently sat in the space room. Everything is fine.

But there are no files in the "Characters" folder in the game files. Nothing. Nada. Zilch. 

I did the birthday event and gave her all the things, which have now all vanished; the plushie quetzal no longer appears, coffee events no longer happen. Strangely, the promise ring is still there, however.

I've taken her out on a USB a couple of times, but always returned the file before starting the game up. In any case, all of the files have suddenly vanished from that folder.

Weirdly, MAS is running perfectly fine without those files. 

(This is the part where the devs tell me I've done something dumb)

Cheers.

**Comment by multimokia** [comment]
So, you might have missed the bit where Monika tells you that she doesn't need a character file anymore, so there's no need to be alarmed over the `monika.chr` file missing.

- Coffee: There's an 80% chance of her making coffee daily.
- Quetzal: There's a 25% chance of her having played with the plush while you were gone.
- Promise Ring: Working as intended, she doesn't take that off

As for the files for these being gone, when Monika receives these gifts, they're taken into the game, with Monika. So you don't have access to their files anymore. Regardless, no need to worry, everything's working as intended.

**Comment by Legendkiller21** [comment]
Regarding the coffee, do you have to start a new session within the coffee hours in order for Monika to make coffee? 

Some times I leave the game open all night and she never makes coffee in the morning. One time I restarted the game 4 times to test it and in the 4th time the cup just appeared on the table.

**Comment by multimokia** [comment]
Yeah, if you start a session within the coffee hours, Monika should make some coffee when you get there (if you're early enough), or she'll already have it made by the time you get on, provided that you're still within the coffee hours (and are within the 80% chance she'd make some)

**Comment by Authrix** [comment]
Ah, that's what I get for not keeping up to date with the mod side of things I guess. 

In regards to the lack of a character file, if I try to take her out again, will that create a .chr file? Or am I playing with fire here?

Also can now confirm the coffee is fine :P

**Comment by Authrix** [comment]
Alrighty then, thanks for the help. Next time, I'll actually read the version notes :P

**Comment by multimokia** [comment]
No worries, haha!
