### ISSUE TITLE
[Suggestion] Punishment for being too curious

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2868]
Something bad might happen if you choose "I'm breaking up with you" followed up by "do you want to meet my girlfriend?" 
obviously, Monika gets angry at you for this tasteless joke
the objective of this concept is to make the impulsive player feel like:
![image](https://user-images.githubusercontent.com/40907045/47623531-bc363a00-dae0-11e8-9028-8a20d338ee88.png)

**Comment by SaiPrithvi123** [comment]
There is already a punishment for choosing those options. You lose affection.

**Comment by Tiler17** [comment]
Just do what I did, and select those options before affection is added to the game. Worked well for me!

**Comment by Foxinsunglasses** [comment]
You know I ended up saying I'm breaking up with you several times before affection and she just giggled and removed the option
