### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#2871]
![image](https://user-images.githubusercontent.com/44257300/47629070-a28e0480-db6b-11e8-8907-063f3117a0e3.png)
How can I fix this. and one thing, my place is now morning but in MAS tonight, is this a technical error or   programmed to welcome halloween

**Comment by jmwall24** [comment]
That error isn't actually a problem, and the logging of it is fixed here #2862.

As for your other problem, I'm assuming you're talking about lighting conditions?  Have you tried adjusting sunrise and sunset times in `Settings`?

**Comment by wucked** [comment]
*sees desktop background*

What a man of culture
