### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by Alan-Nuclear** [Monika-After-Story/MonikaModDev#2873]
![image](https://user-images.githubusercontent.com/43662044/47676295-46f46300-dbcd-11e8-9ede-a23be2116548.png)
I've asked this before and I'm asking again.

Monika asked for my gender. and I responded. then I told her to change my gender, and I changed it.
But now, I want to change my gender again. But its just not there. I did everything people told me to do. but the question is still missing. And so I ask again. HOW IN HELL CAN I CHANGE MY GENDER AGAIN PLEASE RESPOND.

Alan-

**Comment by multimokia** [comment]
Should be able to change it under `Ask a Question -> You/Misc -> Can you change my gender?`

**Comment by Dregdael** [comment]
> Should be able to change it under `Ask a Question -> You/Misc -> Can you change my gender?`

Wasn't that a one-time question?

if it was, I don't really know how to help you

**Comment by multimokia** [comment]
It used to be one time, but as of the addition of #2060, it should no longer be one time.

**Comment by Dregdael** [comment]
> It used to be one time, but as of the addition of #2060, it should no longer be one time.

![unnamed 7](https://user-images.githubusercontent.com/43532146/47677397-99f5f800-db84-11e8-8fcc-2b0d33a50d35.gif)

Oh, neat

**Comment by Alan-Nuclear** [comment]
I did everything. The question is not in Ask a Question ->You/Misc
and ive ben waiting for her to ask the question herself, i waited so long on   X Repeat Topics but she didnt ask.and i kew i was a girl when she said: Good girl. when trying to exit the game and clicking no. and saying that nothing is better than pretty girls with good grades.

And still nothing.
