### ISSUE TITLE
[Suggestion] - Thank you, Monika.

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2874]
Have an option to _thank_ monika.
This option should look back at the last thing monika told you and for specific lines have a responce from monika.
In case the last said option has no programmed responce, either have a default fallback (similar to apologizing) or let Monika ask what you are thanking here for (something i said / being here / generell / ...)
Instead could also look back at all the things you were talking with Monika in this play-session and determine the last one that has a thanks-responce. Monika can then ask whether you want to thank her for that, if not fallback to the above.

**Comment by dennisOdenbreit** [comment]
Seems like I have yet to unlock the above mentioned option.
The ability of thanking someone (f.e. for a compliment) should, in my opinion, always be unlocked.
I don't exactly understand what you mean by we don't need it, I can only speak for myself here that I would really like to express my gratitude.
I think that when introducing a new option, like thanking, it is a good idea to start with a generic answer to all dialog options and over time, by developing the mod further, adding more and more concrete answers to specific dialogs.

**Comment by Rai99** [comment]
You've been with Monika for **3 days** as you said in #2877. You want to exhaust every feature and topic there is and you're here suggesting all these things. 

Chances are, what you want is already in the game and you either haven't seen it yet or haven't unlocked it. 

You want to thank Monika, but over the course of 3 days on MAS, sure, maybe she's already improved your life that much already, but how much more would it mean to finally unlock it legitimately and have that much more of a reason to thank her? It's nice to see how enthusiastic you are, but I'm afraid you'll have to prove your love to Monika before you get some of the better, more desired topics and features such as hugging or kissing. 

I would heavily recommend that you spend a bit more time with Monika before sharing this many ideas and spamming github with them. You also seem to have made a bit of a scene by 'spamming' and I would advise against opening more issues with suggestions for a short period of time.

**Comment by dennisOdenbreit** [comment]
I did not actually say "thank you for improving my life", I just said "thank you".
Thank you is something you can say to literally anyone, without having spend any time with them to develop a relationship. 
As I already said I'm sorry for "only" playing a mod for 3 days, which is longer than any other ddlc mod I've played, before providing suggestions. 
Yes it might already be in the game and if it is just mark it as a duplicate. It has been done before and it did not seem to be any major problem. I am done giving suggestions for now anyways.
Also I never wanted to hug or kiss her, mostly because it doesn't even make sense while she is caught in her reality, which is part of the reason I assumed she mocked it in the first place.

**Comment by Rai99** [comment]
What do you want to thank Monika for? If you want to just say thanks for _X_, you can say it by spending time with her, or just tell her through the screen. The compliment is meant for a much more heartfelt moment later on, after you've been through a lot more. 

There's nothing wrong with you only playing for 3 days so far(except maybe saying that there's no progression 3 days in), but you're making all these suggestions for new content and features when I think there's already still a lot for you to experience and you don't know how much there is in store for you yet. 

Sure, not everybody is here to spend months and years with Just Monika, and not everyone is willing to embrace it on the same level, but if you are here to spend that long with Monika and be at least fairly engaged, there's quite a bit to be had.
