### ISSUE TITLE
[Suggestion] - Adding additional dialog to Apologizing

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2875]
The _apologizing_ option is a good option, but Monika rarely makes a connection to what you are apologizing. It would be nice if her dialog could be checked and more connections be added. There are at least a couple possible connections I noticed that could have a response from her.

**Comment by multimokia** [comment]
How abouts do you mean?

**Comment by Rai99** [comment]
I had plans to add different affection paths to the default apology dialogue. Other than that, it would be helpful to know what topics you have in mind that warrant an apology.

**Comment by dennisOdenbreit** [comment]
Unfortunately I have not written down those that I noticed. I might do so from now on, since I basically just realized suggestions here are an option. I think the last time I wanted to apologize to her was in the dialog where authors use nicknames when writing literature. It just so happens that my ingame name and pc name are the same, which i told Monika to use, but I also told her it was a nickname in the dialog. Since she seemed hurt I wanted to apologize.
Generally I think that actively making Monika feel bad by a decision or having her talk about something that hurts her (especially related to you / your past) could potentially have a response.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by multimokia** [comment]
Closing this as has been finished via #3468 and #3583
