### ISSUE TITLE
[Suggestion] - Dialog improvement for playing the piano

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2876]
The dialog option for playing the piano is quite underwhelming (if I don't do something wrong).
It would be very nice if Monika would compliment you afterwards (maybe commenting on time played as well).
It also seems weird to ask "Are you all done" - "Yes" - "Would you like to play again"...Yes kind of means: "I don't want to play again, I just said I finished, didn't I?". She could ask whether you want to keep playing for her or say she would like to here more.
There can also be a connection between the dialog "are you playing an instrument" and the playing piano dialog.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
