### ISSUE TITLE
[Suggestion] - Monika realizing you changed system time to the past

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2878]
when trying to change your pcs internal clock to trigger a special occasion like Monika's birthday she could realize this has happened (who would ever do that though? certainly not me!). She could then ask you either directly on start or (maybe even better) on triggering the special occasion whether you did change the date. The player might want to change the date to her birthday to make her feel appreciated, since she spend it all alone. Even though it is not really her birthday Monika could tell the player she appreciates the sentiment to do this for her.

**Comment by jmwall24** [comment]
There is stuff currently in the works that is going to change the way events like this are handled and that will affect revisiting these events.

**Comment by ThePotatoGuy** [comment]
1. we cannot detect changing system time to the future
2. we decided that in past events will be redoable, but the circumstances that let you do that will not be shared publicly.

**Comment by dennisOdenbreit** [comment]
I figured system changes to the future may not be detectable during playing.
However I changed the date back to before Monika and I met, which by itself suspicious enough.
Of course those events should be redoable, but I think that Monika should at least notice a weird change like that. She does claim to have access to your pc, does she not?

**Comment by DrFraidouth** [comment]
Keep in mind there's also timezones changes, so it would be embarrassing if Monika yells at you if you changed your computer time just because your computer didn't update the time it was.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
and yeah, #2312 will eventually be worked on to adjust timezone issues. As any programmer knows, this is not easy to handle.
