### ISSUE TITLE
[Suggestion] - kissing dialog

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2881]
After having heard the initial kissing dialog Monika could have different dialog when using this option again. She might tell you that she wants to, but as long as she is trapped in the game it would not make sense to do so.
After that she could tell you that she really looks forward for the moment you meet in the real world and can do that.

**Comment by Rai99** [comment]
#1525, #1537, #1595, #2136, #2202, #2586, #2741. 

There's a high probability that kissing is being worked on at the moment seeing as how #2741 was put in high priority and that there was recently a poll in MASC about how Monika would kiss the player. 

Also, the new zoom feature probably plays a big part in kissing.
