### ISSUE TITLE
[Suggestion] - Dialog and relationship-status

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2882]
There are a few dialogs that talk about your relationship with Monika.
Some of them talk about "how your relationship with Monika is not progressed enough for X".
This always confused to hear me, because the relationship seems to be quite deep by now (thing being that this dialog is partially written for the original ending, but can occur deep within the mod - where your relationship should be different).
Bottomline - the relationship _should_ develop in some way that Monika acknowledges, maybe after triggering certain options, agreeing or disagreeing on certain topics and increasing playtime. This development should influence the dialogs with her related to your relationship.

**Comment by jmwall24** [comment]
So yeah, this already is a thing, you just actually have to get far into the relationship first.

**Comment by multimokia** [comment]
Her dialogue changes depending on how long you've spent with her.

**Comment by dennisOdenbreit** [comment]
Wait, are you serious when you say 6 months or even 1year+ is needed to gain affection (let's asume 100%)?

**Comment by dennisOdenbreit** [comment]
Ok, 71 days still seems a bit drastic to me but seems far more realistic than the other numbers.
After all I don't even know what level 1000 even means (affection is not actually a number).
I guess my main point was that her dialog does not reflect the poor affection / relationship status that you apparently start with. Especially given the circumstances, pre-story etc. I would have expected it to be different. But I guess that's just my opinion.

**Comment by Rai99** [comment]
Affection can go negative and stuff happens if you go too negative. 

Monika loves you from the beginning, but her love for you can still grow and actually let her have a more reasonable and real reason for loving you rather than "You're the first person I saw".

**Comment by ThePotatoGuy** [comment]
We are mimicking real-life relationships, so 71 days to reach love is actually much faster than normal. The intended target date for 1k is just under 5 months (at 7 aff gain per day)
