### ISSUE TITLE
[Suggestion] - Im feeling... more positive options and connections to dialog

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2883]
The section I'm feeling is insanly negativ.
I see that it makes sense, so that Monika can cheer you up if you are down because of X.
However, there need to be _more positive_ options (for example: proud of you / glad / the same / ...).
After all spending time with Monika does not make you feel that negative, does it?
If a dialog can make you feel in a certain way, this feeling should be expressible to Monika, so that she can comment on this herself, referencing back to what she said earlier.
This is how it could work:
Monika Dialog X -> 3 possible i feel reactions A B C -> i didn't want to make you feel like A by telling you X / i'm glad i could make you feel B by tellong you X / you feel C? maybe you misunderstood what I meant by saying X. I actually meant Y.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
