### ISSUE TITLE
[Suggestion] - Communication - Dialog, Comment and Response

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2884]
For me trying to communicate with Monika is _the_ striking feature of this mode.
This, however, requires a certain amount of intelligence from the partner.
This intelligence reflects in how well Monika can respond concretely to what you say.
Currently there are a lot of communication options that can have a concrete response, but rarely have one (mostly generic responses).
This applies to the _i'm feeling..._ section (mentioned in another suggestion) and _i want to tell you something..._ section.
Monika should get a few more concrete responses to matching communication options of those sections. This is the way to actually turn the inital real game monologue into more of a dialog experience. After all having her talk with you should be the ultimate goal, should it not? The more she can respond to your comments on her dialog the more it feels like a real communication.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
