### ISSUE TITLE
About the new update

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#2885]
I noticed two things in the update that are not there in my game : 

1) The Thanks compliment is not available 

2) The sensitive mode change nothing, the "tasteless topics" still present when he's activated.

If someone has an explanation for that ?

**Comment by ThePotatoGuy** [comment]
1. Thanks compliment is at love+. 
2. Which topics do you consider `tasteless`?

**Comment by Torwald39** [comment]
1. I had 860 affections, I had already had the compliment available in the pass but he doesn't come back.
2. The "breaking up" and "Meet the girl friend" still here.

**Comment by multimokia** [comment]
For 1. It unlocks permanently when you're at love. (1000+)

For 2. Those topics weren't the `tasteless` bits we were trying to remove.

**Comment by Torwald39** [comment]
okay
