### ISSUE TITLE
[Art Idea] Monika's Pupils Dilate More Through Affection

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#2891]
So I've heard numerous times through articles and videos about signs of attraction, and one of the most common signs repeated is the dilation of the pupils when looking at someone that arouses/romantically interest us. So I thought I'd suggest that we make Monika's eyes dilate the more she falls in love with the player.

![monii yandere](https://user-images.githubusercontent.com/34694679/47696980-0f8ab400-dbd7-11e8-9f84-2eb11e986c7a.jpg)

_Sorry, you know I had to ;)_

**Comment by Mcmanybucks** [comment]
Yuukiii~

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
