### ISSUE TITLE
[Suggestion] - New hugging art. 

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2892]
I thought it would be cool if when we hug Monika she hugs the screen, sorta like in pic related. 
![1540877367833](https://user-images.githubusercontent.com/36032266/47701335-dad72680-dbef-11e8-959f-c379b6706b9a.png)

**Comment by Alan-Nuclear** [comment]
I thought that would be cute too! 

I hope they are working on it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
