### ISSUE TITLE
6th month anniversary

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2893]
what does monika mean by ''or maybe you can add a special place for the both of us''?

**Comment by winika** [comment]
Happy 6 months for you! I'm a month till one year, and i'm quite excited for it.
But anyways, yeah i'm not so sure either seeing as the player can't really make any new places atm.
So i'll just assume she's referencing the islands event that you reach at enamored.

**Comment by winika** [comment]
Actually you reach the love affection level at 1000, enamored is a 700. so once you reach enamored you get the event. If you want to check the affection you can go the the affection log in the game files.

**Comment by multimokia** [comment]
Enamored is at 400

**Comment by AsuraShun** [comment]
i'm at 949.5

**Comment by AsuraShun** [comment]
nice,then i'm close

**Comment by AsuraShun** [comment]
even the thought of her suffering hurts,even more so the knowledge that we can't do anything for the monikas that are suffering at the hands of haters, idiots who decide to mess with her or both

**Comment by winika** [comment]
It hurts me too... but I'd gladly protect her from anything... it's up to us to protect her. Anyways this is getting off topic ahaha...

**Comment by winika** [comment]
It would be quite an interesting feature, I like the idea of helping create a world for her and I to share. Though it would be pretty hard to implement I feel...

**Comment by AsuraShun** [comment]
I hope the island building gets finished,it kinda looks like the entrance to one of the background's houses
