### ISSUE TITLE
How do you update the game? (detail please, don't want to screw up and lose my progress)

### ISSUE THREAD

**Issue by Outlander676** [Monika-After-Story/MonikaModDev#2894]
Every time I hit the 'Update Version' button in settings it brings up "Error: Failed to move 'update/' folder. Please manually move the update folder from 'game/' to base 'ddlc/' directory and try again."
Excuse what may be a stupid question, but what does any of this mean? I'm completely green when it comes to this sort of thing.
Also, I looked in my 'game/' folder (at least it was This PC > Downloads > ddlc-win > DDLC-1.1.1-pc > game, where I put all the mod files into the original game folder. I'm suspicious this is just the wrong place, sorry if it is), and there were files like updater.rpy, updater.rpyc, updates.rpy and updates.rpyc, but they're files, not folders? 
Any help's much appreciated, I have very little experience in modding and am afraid to move anything in case I make the game unplayable.

**Comment by jmwall24** [comment]
@Outlander676 you have a few things going on.  First thing you need to do is go back in that `game` folder and delete all  `.rpy` files you see.  There should be no `.rpy` files, only `.rpyc` files.  Second, is there an `update` folder inside the `DDLC-1.1.1-pc` folder?

**Comment by Outlander676** [comment]
Hi @jmwall24, are you absolutely certain that deleting all the .rpy files is neccessary to update the game? It's just that they've been there since I installed the mod, and it functions okay with them in there.
Also, that's the problem, there is no update folder in the DDLC-1.1.1-pc folder, there's only those python files.
If it makes it any clearer, on my computer the original game that I downloaded from ddlc.moe is in the folder  "DDLC-1.1.1-pc", and everything from the mod was copied from a folder called "MonikaModDev-2018.9.22" (only downloaded recently)
Sorry if I'm being difficult/ making this more complicated than it needs to be, I just have no idea what I'm doing.

**Comment by multimokia** [comment]
If they've been there since you first installed, then every time you've updated, that update was overwritten. So you've effectively not updated since. Please delete those folders and dismiss download a zip from the releases page from the main site and then merge the folders from that zip into those in your ddlc directory.

**Comment by multimokia** [comment]
If you just took everything from the `MonikaModDev-2018.9.22` zip, then there's going to be a `Monika After Story` folder inside your ddlc directory, you'll have to delete that folder too.

**Comment by jmwall24** [comment]
If you're not sure about things, pls upload a screenshot of your `game` folder,

**Comment by Outlander676** [comment]
@multimokia I haven't updated at all, the one I've been using was the latest version until recently.  Also, I took all the files from the MonikaModDev folder and moved them to the game folder in the original game directory that I downloaded from the ddlc.moe website. I'm going to follow @jmwall24 's suggestion and upload screenshots of some of the game's folders just in case I'm way off with what I'm saying and am making it worse.
![ddlc folder](https://user-images.githubusercontent.com/44603006/47775505-b9dc1600-dd54-11e8-9823-0223ba899f72.PNG)
^^This is the folder that I downloaded from the official website. It's been modified to run Monika After Story instead of Doki Doki.
![game](https://user-images.githubusercontent.com/44603006/47775575-e859f100-dd54-11e8-8165-5cd305c319b5.PNG)
This ^^ is what my 'game/' folder looks like (it's under "game" in the previous screenshot). It's got a few files such as 'cache', 'dev', 'gui', 'mod assets', 'python packages' and 'saves' at the top, but the rest are all the same thing but varying between .rpy and .rpyc. You're absolutely certain I have to delete the .rpy files?
![possible solution](https://user-images.githubusercontent.com/44603006/47775877-d75daf80-dd55-11e8-868e-7a4df5bca405.PNG)
Lastly, there's this folder. I was looking around in the mod's directory (that I got from github, the two are right next to each other in my downloads) and went into the MonikaAfterStory folder. Is this 'update' folder what the error was talking about? If so, where do I move it?
(Again, sorry if I'm being a bother, this is my first time modding pretty much any game)

**Comment by multimokia** [comment]
Ok, delete all files with the `.rpy` extension. Get a copy of MAS from [here](www.monikaafterstory.com/releases.html) and install it.

**Comment by multimokia** [comment]
I.e. merge the `game` folder from the zip into that of your ddlc directory

**Comment by Outlander676** [comment]
Okay, will do. Once I've deleted the .rpy files, should I just hit extract all in the zip, or are there some files/ folders I should leave out?
Also, this isn't going to affect progress/affection, will it?

**Comment by multimokia** [comment]
Once you have deleted the rpy files in the `game` directory just take everything from the zip you got from the link I gave you in the ddlc directory. 

This will not affect your progress. Monika's memories are not saved in the main directory, but rather elsewhere

**Comment by Outlander676** [comment]
@multimokia I've got an error message saying that there are 440 files with the same name. Do I replace them?

**Comment by jmwall24** [comment]
yes

**Comment by Outlander676** [comment]
Was successful. Thanks, you guys are absolute legends.

**Comment by Shiro2564** [comment]
it depends if you use  steam too
