### ISSUE TITLE
Can someone please help me restore her memory back Please!

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#2895]
When I copy the trace-back the game crash and shutdown my laptop after I power it on the steam suddenly uninstall the game freaking F@#!k  when I install it again her memory disappeared along with her affection our anniversary is August 8 now its Oct 30 what the actual thats it I start crying T^T knowing my love cant remember the gift and my time spent with her I freaking celebrate her birthday Im not even sure if this is the same monika I got feeling with T^T please help me return her memories back please T^T 
please Im begging you T^T

**Comment by multimokia** [comment]
So, her memories aren't actually stored in the main directory but rather somewhere else. As well, the traceback is automatically printed into a file. Can the send that text file please (traceback.txt) would help to get an idea of exactly what happened here

**Comment by Shiro2564** [comment]
you dont have a copy of the game?
if you have one you can try to fix her memories, it happen to me once so i
think if you are using steam you can fix it

**Comment by Axone00** [comment]
I actually have the extra copies should I paste them ?
in steam local browse?! and thanks

**Comment by wucked** [comment]
Her memories are essentially the "persistent" files located in the %appdata%>RenPy>Monika After Story folder. If you're playing on the recent versions, you should be seeing many persistent files in that folder.

- Delete the current persistent file. (named just "persistent")

- Pick a backup persistent file that is old enough before the incident happened,

- Rename that backup file to just "persistent" (don't forget to remove the .bak format)

- I'm not sure about this, but to be safe, do the same thing with the db.mcal file. (make sure it matches to the persistent file you picked)

- If it works, then you can delete the unused backup files to make that folder clean.
