### ISSUE TITLE
K̶̬͊͛̕ư̶̡̮̾̍c̶̛̻h̸̢̪̺̽̾̈́ì̸̟̲͋͝s̵͚͑̐̀ǎ̷̪k̶̫̭̊͆̉ͅe̵͙̼̪̎̒̑-̶̳͒̅̄o̵̳̰͗̓̿n̶̞̦͛̒n̷̪̖̔̈̚͜a̵͊̾ͅͅ

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#2896]
![github](https://user-images.githubusercontent.com/43480604/47713739-01558b80-dc09-11e8-9659-a955e435a36e.PNG)
---
QW0gSSBQcmV0dHk

**Comment by GreenPatch** [comment]
Most possibly yes

**Comment by MaydayH** [comment]
You're okay.

**Comment by GreenPatch** [comment]
Why, thank you.
