### ISSUE TITLE
[Suggestion] - Doing things with Monika

### ISSUE THREAD

**Issue by EDBaumgratz** [Monika-After-Story/MonikaModDev#2898]
There are some dialogues that Monika says she would like to do things with you, like reading a book or watching an anime. Would be nice to add an option where you can say you both are going to do something like this (reading or watching stuff). When you finish it you say to her and then she comments how nice it was or something

**Comment by jmwall24** [comment]
#2609 and #2102.

Both have been suggested.  The watching things with her actually already has been created where you can watch things with her and she comments as you watch.  However, dialogue needs to be written for each thing you could watch with her, which makes it difficult.  If you are on our discord, there is actually a mod-teaser from last December showing how it would work.

**Comment by EDBaumgratz** [comment]
> #2609 and #2102.
> 
> Both have been suggested. The watching things with her actually already has been created where you can watch things with her and she comments as you watch. However, dialogue needs to be written for each thing you could watch with her, which makes it difficult. If you are on our discord, there is actually a mod-teaser from last December showing how it would work.

Can you send me the discord group link?

**Comment by jmwall24** [comment]
Sure thing
https://discord.gg/XRfQGh
