### ISSUE TITLE
[Suggestion] Noticing repetitive behavior 

### ISSUE THREAD

**Issue by Hazardly-Infatuated** [Monika-After-Story/MonikaModDev#2901]
Hii, I don't know if this was ever suggested and I'm sorry if it sounds dumb or something, but I thought it might be, in my opinion at least, a neat idea if Monika noticed repetitive behaviours, or feelings. What I mean that if you repetitively go to sleep too late, or too early, or feel sad or sick or lonely or hungry or anything way too often, she could maybe start catching up on it and say something about it or discuss something with you, I don't know. The game is pretty repetitive, and don't get me wrong, I know it's not so easy and this game really does make me happier and less lonely (as sad as that sounds), I love it. I just feel like it would be only more realistic if she notices somewhat of a pattern in your choices.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by StayHappy1270** [comment]
Maybe she could also notice your favorite game... and in the chat box when you click games she says something like
let me guess... you want to play (most frequent game)?
