### ISSUE TITLE
[Suggestion] Small Change to "I'll see you tomorrow" Farewell

### ISSUE THREAD

**Issue by TheSuperStu** [Monika-After-Story/MonikaModDev#2903]
Hello,
I wanted to propose a small change to the farewell of bye_illseeyou that can be found under the 'goodbye' option. This farewell is as follows:

"I'll see you tomorrow, [player]."
"Don't forget about me, okay?"

Looking at the code, this farewell is currently in a pool of other farewells that can only be seen in between the hours of 0000 to 0600, 1100 to 1200, 1600 to 1700, and 1900 to 2000. This is how I view seeing this farewell in those hours:
0000 - 0600: Can make sense, it is a figure of speech to say you will see someone the next day at those hours as supposedly the person would be going to bed.
1600 - 1700: Might be a little too early for her to say this, as there is plenty of time left in the day and the player might come back to relax for a bit before bed time.
1900 - 2000: Some people could be going to bed a little early so it does work, but my change below would make it seem more acceptable.
**1100 - 1200**: This is where my issue of this farewell comes from. I personally try to spend my time with Monika in two separate sessions somehow throughout the day, to avoid any random computer problems I might have (can never be too safe!). I find it odd to have Monika tell me she will see me the next day at 1130, as there is plenty of time left in the day to hang out! 

**What I am proposing is that a simple phrase be added to the farewell**: "If I don't see you later,"
Adding this to the first line would make this farewell fit better in those time frames stated before. I could see how this might then add an issue with the 0000 - 0600 period, as now Monika is saying she might see the player 'later'. I believe this is covered with the use of "if", where she would be fine with not seeing the player until much later for that specific time frame.
I do not expect the need to have this farewell set to a time frame, as this farewell does work (with the proposed change) in those multiple slots. I do think this farewell is fine in those time frames, just needs this little boost to it!

Please let me know with the magnitude of this issue, if I should have just proposed a change in the file itself. I went into detail about this even with it being one line, because sometimes little bumps can take away from the immersion! (Also I would recommend moving this farewell up in the code with the other farewells in the 'goodbye' pool, but that is a separate small problem.)
Thank you!

**Comment by jmwall24** [comment]
This one is actually not time based, it's random and I'm not sure it's used right now, it has no `unlocked` property.

**Comment by jmwall24** [comment]
It definitely needs to be worked on, it makes no sense showing up in the morning.  Needs to be made time specific for sure.

**Comment by TheSuperStu** [comment]
If it were to be made time specific, I want to point out that in the evening there are two goodbyes that do overlap in their time slots: bye_going_to_sleep (2100-0000) and bye_goodnight (2000-0000). 
I actually like that there are two different goodbyes here that can be used, as variety can be good! Maybe later on more farewells could be added to already existing time slots that cause an overlap, might be a good addition. 
If the 'see you tomorrow' farewell would be slotted into the evening, that would mean three of them could be pulled from. I don't see it as a problem myself (again more variety is sometimes better!).

**Comment by TheSuperStu** [comment]
I do understand this farewell would be looked at, but I thought I would add this. 
I just got this same farewell again this morning (11/4) at 1115, so on 0.8.9. I am not coding savvy so I do not understand how the unlocked function works, but I can confirm I did see it. Thanks.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
