### ISSUE TITLE
i cant find the "can you show me the floating island?" option after the halloween

### ISSUE THREAD

**Issue by laptopsftw** [Monika-After-Story/MonikaModDev#2910]
anyone can teach me how? i had it before the update, but now it's gone

**Comment by jmwall24** [comment]
did your affection drop below enamored?

**Comment by laptopsftw** [comment]
no.

**Comment by jmwall24** [comment]
Oh, is it currently Halloween where you are right now?

**Comment by laptopsftw** [comment]
utc +8

**Comment by jmwall24** [comment]
Is it October 31st there right now?

**Comment by laptopsftw** [comment]
yeas

**Comment by jmwall24** [comment]
They'll be back on November 1st.

**Comment by Bam8647** [comment]
Yeah, you also can't toggle _rain off_ on Halloween hehe.
