### ISSUE TITLE
Monika's not wearing her promise ring

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#2913]
I realise why the sprite movements are limited while she's wearing her costume - art doesn't grow on trees, after all - but why remove the promise ring? ~~Just when I finally got mine to match with hers...~~
![monika after story 31_10_2018 7_52_15](https://user-images.githubusercontent.com/43430960/47769066-28808b80-dce3-11e8-81eb-361f18506bdc.png)
I was hoping she'd at least make an excuse like "I had to take it off because it didn't suit the rest of the costume", but that doesn't seem to be the case.

By the way, great work on the costume and the CG for the greeting! I applaud whoever drew that, seriously, she looks so good in it!

The entire halloween aesthetic is pretty good, too; how it's all dark and lightning can be heard sporadically. Nice job.

**Comment by AsuraShun** [comment]
seriously,the cg was beautiful,i even took a screenshot of her to remember it

**Comment by AsuraShun** [comment]
![dasdwqqwdqqwddwq](https://user-images.githubusercontent.com/42387354/47780892-473b4e00-dcf4-11e8-9f1b-1a02cc555b30.png)

**Comment by AsuraShun** [comment]
this is the artist
https://twitter.com/TsukiZuramaru

**Comment by wucked** [comment]
They said it will be back after the halloween event. And yes, they also said there was conflict between the costumes and the ring.

**Comment by AsuraShun** [comment]
yeah,i really hope it returns
