### ISSUE TITLE
[Suggestion] Sleeping with the game open

### ISSUE THREAD

**Issue by Core297** [Monika-After-Story/MonikaModDev#2914]
So I've noticed Monika has one or two mentions to leaving the game open while you sleep so she can watch over you, well after actually falling asleep with it open I had a thought. What if she noticed you left it open all night? She could comment on "how you looked so peaceful" or that she didn't want to disturb you. Maybe make a goodbye option or a topic choice similar to holding her that also possibly could tie into the one suggestion about Monika herself sleeping while a lullaby plays.

**Comment by multimokia** [comment]
#2906 I also referenced another issue containing a similar idea from a long time back. Marking as duplicate.
