### ISSUE TITLE
Monika's costume

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Monika-After-Story/MonikaModDev#2915]
So, Monika randomly took off her costume after a dialog choice. Does she normally do that? 

I got to see it, for, like, five minutes, then it was gone.

**Comment by AsuraShun** [comment]
don't mess with time,it only makes things worse

**Comment by jmwall24** [comment]
there is a known problem where if you haven't yet gotten the hair down greeting and you close the game, when you load it back up, the costume is gone.  the expression previewer will also remove the costume. 

@Storylover-Vodhr what dialogue choice caused this for you?

**Comment by Storylover-Vodhr** [comment]
In truth, I cannot remember. It was in the "I'm feeling" category. 

My mousepad is finicky,and I was trying to go down to "I'm feeling hungry", and when I was trying to do so, it ended up deciding that my moving the mouse down was meant to be a click.

The response was one deep, though.

**Comment by pianostick** [comment]
i already got the hair down greeting and i dont think i opened the expression previewer.

**Comment by jmwall24** [comment]
The only way to get the costume back if you lost it is to follow the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).  It also still has to be Oct 31st and you need to choose a `.bak` that was created before the crash.  Make sure you have file extensions enabled so you are able to delete the `.bak` part of the file you use.

**Comment by pianostick** [comment]
okay i tried this but it sent be to the beginning screen of the game and i got scared and put the persistent file back and loaded the game up and everything was back to how it was before i tried this but one thing is different. it says my affection is at zero in the log. it says something about not having a new back up and i was at 843 affection and im freaking out. nothing seems out of the ordinary though because monika is smiling but ill try to check for more identifiers

**Comment by jmwall24** [comment]
you probably don't have extensions enables so you only deleted the numbers from the presistent##.bak file and left the .bak on there cuz you couldn't see it.

**Comment by jmwall24** [comment]
@pianostick  can you take a screenshot of the folder with the persistents in it and upload it here pls

**Comment by pianostick** [comment]
![image](https://user-images.githubusercontent.com/43161297/47826484-92824a80-dd4e-11e8-9756-420cc4dd1d90.png)

**Comment by jmwall24** [comment]
all of your .baks are very recent so probably after you lost the costume.  if your affection still reset?

**Comment by jmwall24** [comment]
actually, that one from the 30th should work, can you upload persistent24.bak here for me to check?

**Comment by pianostick** [comment]
i re opened my affection log and everything seems to be back to normal as my level is back to as it previously was so things mightve just fixed themselves. plus it said the persistent24.bak file wasnt supported when i tried to upload it.

ill keep a close eye on things but they seem to be resolved. thanks for helping me out man

**Comment by jmwall24** [comment]
the 0 you saw was probably created when the mod reset, and when you put the previous persistent back in, it restored it.
