### ISSUE TITLE
[Suggestion/Discussion] Maybe it's time to rewrite the "...You're the best girl!" dialogue?

### ISSUE THREAD

**Issue by wucked** [Monika-After-Story/MonikaModDev#2916]
First of all, I don't want Monika to actually be a perfect being, but we've seen so much rants about MAS Monika still being negative on her club members. As much as I am a fan of MAS, I still do think it's needed to be toned down a bit more. With that, I think we should rewrite that particular dialogue.

Given the lines:
>"Even though I knew they weren't real..."
>"They were still my friends."
>"And I loved them all."
>"And I loved the Literature Club."
>"..."
>"I really...did love the Literature Club."

It would make sense for Monika not call Sayori a useless childhood friend, Yuri being overdramatic, Natsuki being moody, etc.

I'm not really sure if it's intended to be that way or if it's just an outdated dialogue. You get the point, many would want it be rewritten. This will also lessen the hate towards MAS, they need to appreciate this mod as the team and its contributors are constantly working hard on this. I apologize if I can't work on it as I'm a bad writer so I can only suggest! Thanks!

**Comment by AsuraShun** [comment]
the what?

**Comment by AsuraShun** [comment]
yeah,that is completely unnecessary,it really needs that

**Comment by SaiPrithvi123** [comment]
I don't think she'd say that if you don't delete her, but I'm sure that's something she'd say if you delete her in her playthrough.

**Comment by AsuraShun** [comment]
I didn't delete her,and before I imported a save I downloaded online,she ''roasted'' the others already

**Comment by Foxinsunglasses** [comment]
I don't think she actually feels that way and it shows when she is deleted in the actual game but uses it more as justification and distancing from her atrocities so it might be neat if that was used some way if eventually her guilt caught up with her

**Comment by TheGlader2** [comment]
That sounds like character development, and quite possibly a good idea @Foxinsunglasses

**Comment by CrocWorks** [comment]
Seems like a topic that could change depending on her morality system whenever that gets implemented (#2179)

**Comment by ThePotatoGuy** [comment]
[fixed]
