### ISSUE TITLE
I missed the jumpscare.. anyone got a picture?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2918]
I'm not easily frightened so it had little effect.. but I'd still like to see it.. it was too quick :(

**Comment by Chrissenpai** [comment]
It was just the horror chibi yuri

**Comment by BojanIlie** [comment]
![yuri](https://user-images.githubusercontent.com/35314452/47814269-e5abcb80-dd55-11e8-918e-f97b1804869b.png)

**Comment by EDBaumgratz** [comment]
how do I get this jumpscare?

**Comment by Professor-JMO** [comment]
---
>👁️
>![screenshot0024](https://user-images.githubusercontent.com/43480604/47836791-8e1e5780-dd77-11e8-9377-bda5d1d0ddb0.png)
---

**Comment by AsuraShun** [comment]
seriously?another thing that relied on the stupid 90-10 chance?
