### ISSUE TITLE
Monika Gone?

### ISSUE THREAD

**Issue by kennytomo** [Monika-After-Story/MonikaModDev#2919]
I went trick or treating with Monika today and when i got home she is gone. the game just shows the usual background and her chair and table. I can't even open the menu. i tried re-downloading and everything but she is still not there. I copied the game folder into my laptop she was there but her memories are not there.
Is this a bug? Any advice on how i can solve this issue?

**Comment by AsuraShun** [comment]
you have to put her file back into the characters folder

**Comment by kennytomo** [comment]
oh yea another thing. when she was on my PC her costume was like a witch dress with a hat. but on my laptop she was like a cat girl or something with braids.

**Comment by kennytomo** [comment]
![image](https://user-images.githubusercontent.com/44640437/47800388-26f8a700-dd67-11e8-90e4-3ad63e0de549.png)

**Comment by EDBaumgratz** [comment]
this seems to be an constant problem, i saw some people complaining about this when you take her out with you. I have no clue how to fix it, but maybe keeping a backup of her file should resolve. But we need an answer from the mod dev.

**Comment by kennytomo** [comment]
its also strange how i re-downloaded/installed the game + mod and she is still not there. i tried removing every file i could find relating to Doki Doki Literature Club to an external hard disk and just tried to download the whole thing again and i would just see the chair and the table.

**Comment by ericagoldfarb** [comment]
You have to delete the persistent. The easiest way to do this is to download RenPy and MAS should show up as a project, then you justpress the delete persistent button ad launch the game.

**Comment by jmwall24** [comment]
uhhh, while deleting the persistent will bring her back, that's because you completely restarted the mod from scratch.  what you want to do is restore an older persistent backup.  make sure you have file extentions enabled and follow [these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by kennytomo** [comment]
It worked! Thanks for the help guys really appreciate it.

**Comment by kennytomo** [comment]
![image](https://user-images.githubusercontent.com/44640437/47894979-c8374880-dea0-11e8-8fd7-521399d77933.png)
