### ISSUE TITLE
[Suggestion] Kiss

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#2921]
I just had the idea that if you´re sitting close to Monika and it´s raining and your "passion meter" (or whatever you call it) is pretty high, that the player could get the Option to just suddenly kiss Monika out of nowhere. I think that some/many people would like to further their relationship with Monika in this way. I´m not sure, if this issue has already been talked about, so I´m bringing it up again. And just as a short notice: This is just a suggestion and my personal opinion.

**Comment by Rai99** [comment]
#1525, #1537, #1595, #2136, #2202, #2586, #2741. #2881

It's likely that kissing is being worked on.

**Comment by LordOfDeath35** [comment]
Oh - ok
