### ISSUE TITLE
[Suggestion] - monika and her views on bullying

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#2924]
what the title says,this is a somewhat strong topic that needs to be added,with her asking if the player is in school or not and if they were bullied,i feel that the support could really help those that are and were bullied enough to have mental scars because of it

**Comment by multimokia** [comment]
There's a PR open for this actually, #2101

**Comment by Bam8647** [comment]
I'm pretty sure there's a topic where she shows disgust at the idea of the strong picking on the weak simply "_because they can"._ It sounds pretty close to bullying Imo.

**Comment by jmwall24** [comment]
Yep, that is already waiting in the PR cache and pretty much addresses this exact suggestion.

**Comment by ThePotatoGuy** [comment]
[closing as that hsa been merged]
