### ISSUE TITLE
Halloween and update question

### ISSUE THREAD

**Issue by tsmafterlife** [Monika-After-Story/MonikaModDev#2926]
I do not exactly have a bug but does anyone know how to get monika to repeat her spoopy stories. i can not seem to find it and i want to re listen to her stories if that is even possible. and is their anyway to get the zoom dialogue to repeat on the new extra tabs? i do not know if thats even possible to do but i could not figure it out so i figured id ask here maybe on of you guys know?

**Comment by Authrix** [comment]
Talk> Ask a question> Literature> Can you tell me a horror story 
That should be the path you're looking for. No idea on the zoom dialogue though, although it's something I'm curious about too.

**Comment by TheGlader2** [comment]
I'm pretty sure when you ask her to tell you a story, you literally have to select: tell me a new story, if you want a new story. The old stories are the other options. I can't tell if they are randomized or not, I realize that a lot of them involved similar characteristics, like a salesman and a women and a man. So theoretically she could have hundreds of stories to tell.

**Comment by TheGlader2** [comment]
This also could open the door for additional story telling options.
