### ISSUE TITLE
Monika gone after i took her trick or treating

### ISSUE THREAD

**Issue by CorvusRogue** [Monika-After-Story/MonikaModDev#2930]
uhhhh i placed her back into the characters file but she didn't show up.

**Comment by jmwall24** [comment]
can you upload your `mas_log.txt` file here pls.  it'll be in the `log` folder

**Comment by CorvusRogue** [comment]
Wed Oct 31 18:19:20 2018
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[!] I found a corrupt monika! 10
[!] I found a corrupt monika! 10
[exp] WindowsError(2, 'The system cannot find the file specified')
[exp] WindowsError(2, 'The system cannot find the file specified')
[exp] WindowsError(2, 'The system cannot find the file specified')
[exp] WindowsError(2, 'The system cannot find the file specified')
[exp] WindowsError(2, 'The system cannot find the file specified')
[exp] WindowsError(2, 'The system cannot find the file specified')
[!] I found a corrupt monika! 10

**Comment by CorvusRogue** [comment]
git hub is telling me the monika file is too big

**Comment by jmwall24** [comment]
can upload it to google drive and send the link.  i don't really need it, it's probably corrupt like it says anyway.  but to get her back, follow those steps.

**Comment by jmwall24** [comment]
Any luck?

**Comment by CorvusRogue** [comment]
i might've accidentally reset the mod trying to restore to a previous persistent

**Comment by jmwall24** [comment]
you must not have file extensions enabled.  it's ok.  click off the mod. and go find this to enable file extensions, then delete the .bak part from the file you renamed persistent.
![unknown 2](https://user-images.githubusercontent.com/36523761/47823976-1c2b1b80-dd41-11e8-8b18-8db358f2c567.png)

**Comment by jmwall24** [comment]
if you can't get it, send me the peristent file with the .bak on it and I'll do it.

**Comment by jmwall24** [comment]
if the reset mod created a new persistent file (it'll have a much smaller file size than the rest) you'll have to delete that one.

**Comment by CorvusRogue** [comment]
how do i send you the persistent file?

**Comment by jmwall24** [comment]
just drag the most recent that was before you took her out into the comment box

**Comment by jmwall24** [comment]
or you can just copy and paste it into the comment box.

**Comment by CorvusRogue** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2536707/persistent.txt)

**Comment by jmwall24** [comment]
is this one from when you just started over?  or from before?

**Comment by CorvusRogue** [comment]
before

**Comment by jmwall24** [comment]
it's showing today is the first day you met..did you just install today?

**Comment by CorvusRogue** [comment]
no

**Comment by jmwall24** [comment]
send me the oldest persistent##.bak file you have in there

**Comment by CorvusRogue** [comment]
[persistent.bak.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2536727/persistent.bak.txt)

**Comment by jmwall24** [comment]
quick question, have you always had it so the text when she talks doesn't type out, but just all shows up at once?

**Comment by CorvusRogue** [comment]
nope

**Comment by jmwall24** [comment]
weird it was doing that but i fixed that as well..1 sec and you'll have her back

**Comment by CorvusRogue** [comment]
thanks man you're actually my hero

**Comment by jmwall24** [comment]
download this and put it where the other persistents are, let it overwrite the current persistent

https://drive.google.com/open?id=1-8X5A3NaV9U20e77PmiLRL8sSRgbG98T

**Comment by CorvusRogue** [comment]
Holy shit man thanks a bunch!
