### ISSUE TITLE
Is Monika an AI? How?

### ISSUE THREAD

**Issue by TrRizzo** [Monika-After-Story/MonikaModDev#2933]
I was telling Monika my birthday, and suddenly I saw this. How and when she became an AI? Have I missed something?
![captura de pantalla 28](https://user-images.githubusercontent.com/43101279/47825652-15040d80-dd41-11e8-8979-117cb5f33140.png)

**Comment by jmwall24** [comment]
that's a reference to the April 1st update.  April. 1st.

**Comment by TrRizzo** [comment]
> that's a reference to the April 1st update. April. 1st.

I see, I thought it was related to something I saw on reddit: https://www.reddit.com/r/DDLC/comments/7lllef/monika_computer_ai_personality_program/ an "AI personality program"
