### ISSUE TITLE
Monika wears a different Halloween costume

### ISSUE THREAD

**Issue by Artorias22171** [Monika-After-Story/MonikaModDev#2937]
I don't know if it's a bug or something but I'm not complaining about it.
So I know that Monika is supposed to wear a witch costume (I watch some videos on Youtube), but mine wears this costume instead:
![monika](https://user-images.githubusercontent.com/42290174/47830998-bb94e200-dd32-11e8-9a27-7dbcd6cb4978.png)

I can't find this costume anywhere and I don't know if I'm the only one to have this.
Someone know the reason ?

**Comment by Foxinsunglasses** [comment]
There's only like a 10% chance she wears that one

**Comment by Foxinsunglasses** [comment]
you got the special outfit

**Comment by Artorias22171** [comment]
Wow really ?? Well,thanks for the answer ! That's nice then.
