### ISSUE TITLE
Unfinished Island (discussion)

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2938]
Does anyone else wonder what the mess is on the island? it looks like a house or a very nice shed but I can't help but wonder how it will be used. because it feels like https://media.giphy.com/media/joV1k1sNOT5xC/giphy.gif 

and I'm wondering what others think on the matter

**Comment by AsuraShun** [comment]
I don't think it's a shed,it could be or become a gateway for dating spots if that's ever implemented,kinda like a portal

**Comment by Foxinsunglasses** [comment]
That's actually a pretty neat idea

**Comment by Mcmanybucks** [comment]
I was hoping, what with the reference to "Feel Good Inc" that we'd see Monika on the island with a piano.
