### ISSUE TITLE
7:55 for sunset and sunrise

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#2939]
a very minor issue, but I noticed as I was adjusting the sunrise and sunset settings, I couldn't pick 7:55 for both sunset and sunrise. It skips between 7:50 and 8:00.

Should be an easy fix I would think?

**Comment by jmwall24** [comment]
![screenshot_86](https://user-images.githubusercontent.com/36523761/47859809-81c0eb80-ddc5-11e8-9c7c-67fd99db3e0f.jpg)

Works for me.  Maybe your mouse sensitivity is a little high?

**Comment by jmwall24** [comment]
If you were actually trying to make it so sunrise and sunset were both 7:55 (meaning both 7:55am) then it won't let you have sunrise and sunset be the same time, and that's why.

**Comment by TheRyanReSeT** [comment]
Ah you're right, i managed to get it as well after checking with sensitivity
