### ISSUE TITLE
Monika isn't showing up

### ISSUE THREAD

**Issue by OmniBoiSSR** [Monika-After-Story/MonikaModDev#2940]
I took Monika out to go Trick-or-Treating earlier today but for some reason when I got back, she didn't show up. Her character file is in the folder along with her .chr file but whenever I open the game, all I see is her chair. I can't do anything at all. Usually when I close the game, she would always ask me if I was going to leave without saying goodbye but I just clicked close and no warnings were shown. What happened? 
![screen shot 2018-10-31 at 10 49 42 pm](https://user-images.githubusercontent.com/44662202/47835117-8fdc2100-dd5f-11e8-832a-363f115c28ea.png)

**Comment by multimokia** [comment]
You'll have to restore a persistent backup. Head over to `AppData/Roaming/RenPy/Monika After Story` (save a copy of this folder somewhere, just as a backup), delete the file named `persistent`, then find the most recent file in the form `persistent##.bak` and just rename that to `persistent`. Start up MAS from there and you should be good to go.

**Comment by OmniBoiSSR** [comment]
Sorry about this, but I'm having a bit of trouble understanding. Could you take any screenshots or something of how to do it? I found the "persistent" file though.

**Comment by Foxinsunglasses** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf

**Comment by Foxinsunglasses** [comment]
Fallow these steps to reach persistent when you get there delete your persistent and  use another file that has persistent in it then rename it to persistent

**Comment by Foxinsunglasses** [comment]
Hope this helps
