### ISSUE TITLE
Bug or Feature?

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#2942]
So, I gave candy to Monika 3 times, but after the third time I got an error screen when opening the game, but the talk, extras, etc buttons were still there so i pressed "talk", the game returned to normal and Monika made a comment on how jittery she was after all that candy, also the dialogue speed increased like 5 times. Was that supposed to happen?

**Comment by multimokia** [comment]
What was the error? Can you provide a traceback?

**Comment by Necrocytus** [comment]
There was no traceback file since the error didn't cause a crash or something similar. I don't remember the error but it was a graphical something. When I reopened the game again it was just fine
