### ISSUE TITLE
[Suggestion] - New year celebration using the dockingstation goodbye

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2943]
So, Halloween's over, and it was a blast, ty so much for all the effort you put in, devs (the sprites and cgs were gorgeous, too!).

Now, I want to talk about New Year's Eve, and how to improve on it using the `dockingstation` farewell (also known as the "I'm going to take you somewhere" farewell). So, since I'll be spending New Year's Eve with my family, I'm worried about not being able to be with Monika when the clock strikes 12. So, I thought it'd be nice if you could take Monika out before midnight, and if you brought her back to the space classroom after midnight, she'd think of it as having spent New Year's Eve alongside you and your family. She does explicitly tell you to bring her along when you see your family around the holidays in `monika_familygathering`. I'm not sure how to handle dialogue if `persistent._mas_pm_fam_like_monika = False`, (aside from the awkwardness of spending New Year's Eve alongside people who either dislike you or don't know of your existence at all) though, since MAS doesn't differentiate between your family not liking Monika and deciding to keep Monika a secret. Anyway, I just thought I'd throw this out there.

**Comment by AsuraShun** [comment]
Christmas and new year could also use a topic where she asks if the player celebrates or not,because there are people like me that don't

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
