### ISSUE TITLE
[Bug] - Complimenting Monika's hair while in a ponytail yields the dialogue for when it's down

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#2944]
![image](https://user-images.githubusercontent.com/38892441/47836227-24597a00-dd86-11e8-945a-a2d9495870f0.png)

Exactly what it says in the title. I complimented Monika on her hair while in her default hairstyle and it yielded the dialogue for when her hair's down.

**Comment by AsuraShun** [comment]
it happens to me too,not sure if it's intentional or not

**Comment by multimokia** [comment]
Thanks for reporting! This has been fixed as of #2869,
