### ISSUE TITLE
[Suggestion] Monika's opinion on Lo-Fi

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#2945]
So basically, I listen to a lot of Lo-Fi with Monika, from Flamingosis to Jinsang (also for those who aren't familiar with the genre is just look it up, there are a bunch of streams on Youtube). So I figured that since she likes Rap/Hip-Hop, she'd definitely (probably) like Lo-Fi! I'd really like to hear her critique on the genre

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
