### ISSUE TITLE
[Bug] Not visiting Monika for too long?

### ISSUE THREAD

**Issue by DrFraidouth** [Monika-After-Story/MonikaModDev#2947]
Whenever I leave the game and open it back up after one hour ago or immediately, Monika complains that I left for too long and after the Haloween event I wanted to leave the game and open it back up so that the event would disappear and Monika yelled at me for being away for too long, I didn't lose any affection but it's still a problem to me.

**Comment by Olliesama** [comment]
Is it the one where she says shes joking?
That's a random greeting, and if so isn't a bug.

**Comment by DrFraidouth** [comment]
Well then that's pretty harsh
