### ISSUE TITLE
[Nitpicking Grammar] Samurai Horror Story: Kuchisake-Onna

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#2948]
"Whom" should be "Who" because it's acting as a subject and not as an object

![image](https://user-images.githubusercontent.com/36053888/47869026-3534da80-dddc-11e8-8df9-affda91bb9fc.png)

**Comment by jmwall24** [comment]
any grammar or typos, pls put in #2837
