### ISSUE TITLE
Repetitive Fun Facts

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2949]
I seem to always get the honey fun fact when I ask.
I used to get a few different ones at the very start (maybe 3 in total).
I ask max. 1 time per session.
Maybe just do it like the stories, or improve the randomness / scope.

**Comment by Olliesama** [comment]
You just got unlucky. If you get a good fun fact (90% chance) there's an equal chance to get any of them, in which there are twenty.
