### ISSUE TITLE
[Suggestion] Clicking = Touching

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2950]
Just putting it out there.
A no-brainer, actually.
Oh yeah, also moving while holding down...

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725.
This is my favorite duplicate. 

> the primary reason why we're hesitant to add more click interactivity atm is because each clickzone requires a screen or screen object, and performance can drop drastically. we saw this with the first implementation of calendar, and as a result had to rework that and the talk/play/music buttons so they were more efficient.

**But,** with the new Extras menu, clickzone interaction maybe coming.

**Comment by Mcmanybucks** [comment]
> and performance can drop drastically

Yea but.. I mean, we're not running windows 96 here.. Ren'py can't possibly be *that* taxing.. can it?

**Comment by jmwall24** [comment]
you'd be surprised
