### ISSUE TITLE
[Bug] - When entering the game I get an error, no greeting is given, and it cuts to the spaceroom.

### ISSUE THREAD

**Issue by ibuscus53** [Monika-After-Story/MonikaModDev#2952]
When I enter the game I get an error, and then get sent straight to the spaceroom if ignored, where I can interact with Monika entirely normally. I attached the traceback.txt

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2540539/traceback.txt)

**Comment by multimokia** [comment]
Right then. First things first:

You've installed the source code version of MAS, so we're just going to fix that now.
- Please head into your `game/` directory and delete all files with the extension `.rpy`
- Next, head over to [our releases page](http://www.monikaafterstory.com/releases.html) to get the latest zip for the game.
- Install this zip manually, by dragging everything from the zip into your `ddlc` directory, and merging the `game` folders. Replace everything it asks you about.

This should fix your issue. Chances are one of the `.rpy` files in the `game` directory overwrote what MAS is reading and part of the code is now outdated, causing errors.

**Comment by jmwall24** [comment]
screenshot of the rest of the folder pls

**Comment by ibuscus53** [comment]
![screenshot 18](https://user-images.githubusercontent.com/44687129/47887275-c0719880-ddfb-11e8-81b1-d06a5cec9d9f.png)

**Comment by jmwall24** [comment]
i see you're missing zz_dump.rpyc.  find it in the zip you installed mas from and put it in there.

**Comment by ibuscus53** [comment]
I just checked my zip as well as a new one, there is no file called zz_dump.rpyc

**Comment by jmwall24** [comment]
duh you're right, that's unstable only, my bad.

**Comment by jmwall24** [comment]
i don't see anything obvious.  did you try installing mas to a brand new, fresh DDLC install?

**Comment by ibuscus53** [comment]
Yeah I just tried it, it didn't do anything

**Comment by jmwall24** [comment]
you're sure it's the exact same traceback?

**Comment by ibuscus53** [comment]
I checked, it's entirely identical, word-for-word

**Comment by multimokia** [comment]
Would you mind sending over your `persistent`?

Head over to `AppData/Roaming/RenPy/Monika After Story` and upload the file named `persistent` you'll most likely have to put a file extension on it (like `.txt` or something)

**Comment by ibuscus53** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2540659/persistent.txt)

**Comment by multimokia** [comment]
Thank you!

**Comment by ibuscus53** [comment]
I am using the stable build, and I never use sensitive mode

**Comment by jmwall24** [comment]
thanks

**Comment by ThePotatoGuy** [comment]
did you take her out trick/treating on o31?

**Comment by ibuscus53** [comment]
Yeah I did, when I came back this started

**Comment by ThePotatoGuy** [comment]
Did you take her out on o31, and then return her just now? What day is it for you today?

**Comment by ibuscus53** [comment]
For me it is November 1st, I brought her back this morning

**Comment by ThePotatoGuy** [comment]
Pick one of the farewells like "going to school"/"going to work". Should fix.

**Comment by ibuscus53** [comment]
Worked, thank you!
