### ISSUE TITLE
Where the player is from

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#2953]
I've been thinking about being able to tell monika my country and I've thought up a possible way to do it. If she was somehow able to pull up a map and we clicked on the country or a list of flags to choose from. This would probably be a Herculean task considering there are 195 countries but it would be a cool implementation.

**Comment by Foxinsunglasses** [comment]
http://www.flags.net/UNNA.htm

a list if it helps

**Comment by Rai99** [comment]
Don't forget Sealand. Yes, this is a real country with it's own anthem, money, flag, etc. Can't be excluding anybody now can we?
https://en.wikipedia.org/wiki/Principality_of_Sealand

I remember it was said that having clickable objects slightly reduces performance as seen with the calendar. There are currently the 4 buttons and the calendar, and if the calendar had noticeable performance drops as the fourth clickable object, I can only imagine what 195+ clickable objects at once would be like. 

As you said, this would take a lot of work to add unique dialogue for each country, not to mention a pm variable for each country. I personally don't see what this adds for the amount of work it needs, so I'd say this is unlikely to happen.

**Comment by Foxinsunglasses** [comment]
fair enough

**Comment by Foxinsunglasses** [comment]
Could be something where you type the name in, she asks if it's correct, if yes then a simple thank you for reveling more about who you are

**Comment by Rai99** [comment]
I don't know about a pm variable for each and every possible answer. We could ignore that, but that's still a lot of dialogue to write that has at least a minimal amount of depth. If it's just that simple of a response, I don't think it really offers too much. 

If there isn't too much detail in the responses, not too much reason to have it in the first place I'd think. It would need a bit of detail while still being appropriate and accurate for that part of the world. 

Still, I don't know if anyone wants to try and implement this feature, not to mention how long it would take to review and test each and every outcome.

**Comment by MaydayH** [comment]
Or, to make a hard thing easier, there may be at leasr the question of which **continent** the player is from, May sounds silly but I guess it could be easier. Also, after answering "Asia/Europe/Africa/America South|North (Arctic? Antarctica???)", there may be some suggestive questions like if you're from East/West Europe (not sure if I call it right in English)... You know, from which part of the continent the player. 
I mean, yeah, making a phrases for **every** of 195+ countries would be too hard, but if it cames to some parts of continents there will be much less phrases to write aaand there could be some common things concerning countries in this parts, which Moni can mention. (the main thing is not to overdo it with stereotypes like, you know... ONLY sushi and anime in Japan? bears and extreme cold in Russia?)

**Comment by pianostick** [comment]
or like in the concert topic you can type where you are from?

**Comment by MaydayH** [comment]
@pianostick 
Then wouldn't it have to limit her answers to some common phrases? There are so many places in the world

**Comment by pianostick** [comment]
yeah i guess, but it might be a good alternative/placeholder while the real interaction is being made

**Comment by Mcmanybucks** [comment]
Maybe just adding in some code for ISO codes is easier.

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by ThePotatoGuy** [comment]
we are going to try to get player location via internet lookup (with an initial question asking if its okay to do this)

[closing until we look into it]
