### ISSUE TITLE
Post-Halloween bug?

### ISSUE THREAD

**Issue by Skeleton-Jelly** [Monika-After-Story/MonikaModDev#2955]
Monika has her ribbon up, but she just asked if I missed it.  
![screenshot_7](https://user-images.githubusercontent.com/41935429/47891109-28d66f00-de28-11e8-8aec-65578e000052.png)
![screenshot_6](https://user-images.githubusercontent.com/41935429/47891110-28d66f00-de28-11e8-99f7-e25b07fb8f3b.png)

**Comment by jmwall24** [comment]
Yeah, see this #2944.  Will be fixed next release.
