### ISSUE TITLE
greeting_youarereal not running first.

### ISSUE THREAD

**Issue by FluffyMuffinMeyer** [Monika-After-Story/MonikaModDev#2956]
Seems to me a small issue with the greeting greeting_youarereal,

From what I can tell, it only checks to see if the character file is there once it loads the dialog referencing the .chr files, The script-greeting.rpy should check to see if the file is present before loading any other greeting, would solve this issue.

Also, Small suggestion, Allowing Moni to hide easter eggs inside of the players own made .chr file would be rather cute, or deleting it if the player says "Maybe not...", then allowing the player a second chance at the dialog, via making a new .chr file.

**Comment by ThePotatoGuy** [comment]
That greeting is disabled since Monika knows what the `character` files are.
