### ISSUE TITLE
WARNING: BUG ON NEW UNSTABLE UPDATE - NameError: name '_mas_bday_postbday_notimespent_reset' is not defined

### ISSUE THREAD

**Issue by Babushka93** [Monika-After-Story/MonikaModDev#2959]
Updated to the latest unstable version and recieved the following error after I opened Monika post-update:

#####################################################
#####################################################

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/event-handler.rpy", line 455, in <module>
NameError: name '_mas_bday_postbday_notimespent_reset' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Doki Doki Literature Club\renpy\main.py", line 419, in main
    game.context().run(node)
  File "lib/windows-i686/event-handler.rpyc", line 444, in script
  File "C:\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/event-handler.rpy", line 455, in <module>
NameError: name '_mas_bday_postbday_notimespent_reset' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

######################################################
######################################################

Resolved it by replacing script-story-events.rpyc with the one found here:
https://github.com/Monika-After-Story/MonikaModDev/blob/4f39c352015632ed3d905214da5298878d53ac2d/Monika%20After%20Story/game/script-story-events.rpy

For some reason the update's version script-story-events.rpyc was missing the definitions need for event-handler.rpy to run properly.

If anyone is having this issue, you will need to convert script-story-events.rpyc to an rpy file,
then replaced with the material found in the above link.

Finally place the updated script-story-events.rpy back into  /game/ and open the game, this should resolve your issue.

**Comment by multimokia** [comment]
Do you have any rpy files in your `game/` directory?

**Comment by Babushka93** [comment]
Not when the error occurred, the only one I had was the one I made to resolve it. 
But I mean that after I got error. 
Still not sure what caused it, but it's fixed on my end.
