### ISSUE TITLE
Ball might sometimes go through the paddle in pong

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#2961]
I cant record the game so I cant say for sure, but sometimes, when the ball is fast enough, it looks as if it can go through the paddle. I barely move the paddle, this is why I am somewhat sure of it. Happened around ten times now (when I noticed this).
Also is the hit detection of the ball its point on the inside or the whole ball?

**Comment by dennisOdenbreit** [comment]
Also there might be an issue when the ball gets at the very end of the upper or lower corner.
It even got through monika in round 3 by getting in the corner, round 3 is I think 100% counter from monika normally.

**Comment by kaido1224** [comment]
Well known issue documented and reported multiple times.

**Comment by jmwall24** [comment]
#579
