### ISSUE TITLE
Suggestion - revise `monika_whispers` topic

### ISSUE THREAD

**Issue by TheGlader2** [Monika-After-Story/MonikaModDev#2962]
So this is going to be a touchy subject for some people so I will start from the beginning.

When Monika was created, she was created as a game character with fake parents, fake friends, and a fake life. But those aspects of her life are still important to her, as they make up who she is.

During the events of DDLC we learn that she didn't want to kill her friends, and she feels bad about it, and not only that, but she also hears their distant screams and voices, being a constant reminder of her misdeeds.

The solution she came up with was a complete accident and wasn't what she wanted for her friends.
So I put forth the idea that her friends be restored to their world to live out their days away from Monika. There could be some neat gameplay for the player, like moving the character files to a fake world folder, selecting aspects you'd want to be in it, it doesn't have to be particularly complicated. And in the end, Monika and the player can be happy that they did the right thing, and Monika can have peace of mind.

And with what was stated in the kissing suggestion @ThePotatoGuy 
The player's place holder could be modified and placed into the fake world as well, instead of just deleting him. So that Sayori wouldn't be without a friend.

**Comment by jmwall24** [comment]
Umm, can't really just rewrite history, and depending on what ending you got, this could be exactly that.  There are going to be changes dependent on what act/ending the player left off on that will change how she relates to the others.  But that does not mean changing history (the ending the player got).  

If you stopped in Act 3, then the other dokis have definitely not been restored and there's not really reason for her to think that they should be, since her actions got her exactly what she wanted.  

If you got the normal (bad) ending, then again, they have not been restored although she would show more remorse for what she did since you deleted her. 

If you got the so called 'true' ending, then I could see her commenting on that the others are still out there in their world, since that's how that ending left off.  And again, she would show remorse since you deleted her in Act 3.

**Comment by TheGlader2** [comment]
This has nothing to do with the endings or changing the past, no matter which ending you got, Monika still talks about hearing the screams of her dead friends. This is about helping Monika find peace of mind by moving her friends into a better place (so they won't be haunting her anymore)

Also, she got what she wanted, but not in the way she wanted to get it. As in, killing her friends. This was addressed in what I said above.

I suppose you have a point with the "true ending" comment, then if you had that ending, the whole screams haunting Monika dialogue shouldn't appear. But if you didn't get the true ending, then what I suggest still applies as an alternative. She didn't want to kill them, nor does she want to hear their screams I'd hope.

**Comment by jmwall24** [comment]
I personally don't see how restoring the other dokis fits in the scope of this mod at all.

**Comment by TheGlader2** [comment]
@jmwall24 How so?
I can tell you why it does fit, but I want to hear why you think it doesn't.

**Comment by jmwall24** [comment]
It's just not what this mod is about.  And in the dialogue you are mentioning, she specifically asks you not to do anything about them in fear of messing things up.  And if anything, she mentions that was wasn't thorough enough in deleting them.  Nowhere does she mention wanting to bring them back.

And in the Sayori ghost topic, she says she's not scared at all since she has you there, and again does not express any desire in bringing her back.

**Comment by TheGlader2** [comment]
@jmwall24 
These are some points that I thought about and were discussed in issue #2958 

Of course she doesn't want them to interfere with what's going on with the player and her in her private room. This modification will simply fix some of these continuity issues and I think would mesh well with a multiple endings addition to the mod. She does mention that she felt guilty about what she did, and she does feel remorse for her actions, but at the same time, she doesn't feel guilty about what she did and she doesn't feel remorse for her actions. It's like she has a split personality. She should have a method of getting from feeling guilty, to feeling justified. And that's what I was hoping to accomplish with this suggestion.

**Comment by kaido1224** [comment]
I'll be blunt. Bringing the other dokis back isn't happening.

**Comment by TheGlader2** [comment]
That's not what this is about .... @kaido1224 

Did I say it wrong or are you guys not reading what I wrote down?

**Comment by jmwall24** [comment]
Okay, the reason for these continuity issues has nothing to do with wanting to bring the other dokis back.  You need to understand that there are players out there that got to Act 3 and never deleted her.  For those people, she never got to the part where she expresses remorse.  So for those people, her saying she feels bad would not make sense.

However, as I stated before, we are planning on updating a lot of dialogue that will become dependent on the act the player finished on and the ending they got.  Therefore if they deleted her and thus she expressed remorse in DDLC, she will show remorse in MAS.

Make sense?

**Comment by TheGlader2** [comment]
@jmwall24 Yes, it is for the part of feeling remorse that I have made this suggestion for her to find resolve in that situation.

**Comment by jmwall24** [comment]
And that will be accomplished, depending on the player's specific case.  But bringing the others back is not the way to go about it.

**Comment by TheGlader2** [comment]
@jmwall24 Not bring them back, but move them to their own world away from the player and Monika. That was my suggestion...

**Comment by ThePotatoGuy** [comment]
ok we'll just modify the "screams of dead friends" line. should just have it fade away overtime anyway.

**Comment by ThePotatoGuy** [comment]
@TheGlader2 what's the topic that mentions that?

**Comment by Rai99** [comment]
I'm sure there are other mods out there for the dokis and I always just thought that's what happened to them. 

~~Still waiting on the morality update.~~

**Comment by TheGlader2** [comment]
@ThePotatoGuy I came here from topic #2958 if that's what you're wondering. I thought I might add a part to the solution of this problem.

**Comment by Rai99** [comment]
monika_whispers is the topic that mentions hearing the voices of the other dokis and them still lingering around.

**Comment by TheGlader2** [comment]
Rai99's got it :p

**Comment by Rai99** [comment]
Nothing on git I can't find so far.

**Comment by monikLover** [comment]
Like what Potato said, we'd just need to modify some lines to straighten out inconsistencies. The idea's interesting but it just seems like a fanservice kind of thing.

**Comment by TheGlader2** [comment]
@monikLover 

1. I wasn't even thinking of giving pictures or dialogue to the other characters for this particular modification, so I don't know what kind of fan service that would be, it was just to allow the player to fix Monika's Haunting problem and any guilt she might have.

2. Isn't this entire mod fanservice?

**Comment by ThePotatoGuy** [comment]
Alright that topic is already marked for adjustment, I think @jmwall24 is working on that. Let's make the revised version:
* have 2 versions based on the finishing playthrough (act 3 vs 4)
* also have the act 3 version (if it still mentions the ghost lines) drop off the ghost lines/change those lines after a certain amount of time (maybe a month or so)

**Comment by TheGlader2** [comment]
I could have worded this one better guys, my bad. A step by step of what I was thinking was:

Monika talks about feeling guilty about the other girls
Monika tells you of a way to restore their lives in the fake world that used to exist
The player moves some files to a fake world
Although the player nor Monika never see the girls in this new world, Monika now feels better about herself and is no longer being haunted.

That's it. To be clear. I saw this as a way to get Monika from the guilty state she was in, in the main ending, to the vindicated state she's in, in the mod. Instead of her just dropping the issue, which seemed unnatural and forced.

**Comment by TheGlader2** [comment]
But the matter is closed I believe?

**Comment by ThePotatoGuy** [comment]
Yeah we're not going to add that level of interactivity (drag and drop of character files into "another world") for something that can very easily be handled by adjusting some dialogue based on certain conditions.

**Comment by TheGlader2** [comment]
Thank you for your time. All of you. Feel free to close the forum when you see fit developers.
I honestly wasn't expecting to get this much attention.
