### ISSUE TITLE
[Bug] - Is Monika supposed to make coffee after her birthday? - Not Actually a Bug

### ISSUE THREAD

**Issue by HollowedOne** [Monika-After-Story/MonikaModDev#2964]
I don't really know if this is a bug or not...

Occasionally I see people with screenshots of Monika with a coffee cup next to her. **I did give her coffee on her birthday and she acknowledges it when the coffee topic is brought up. She only made one cup of coffee which was right after I gave it to her on her birthday and since she finished it she never made another one.** Am I supposed to do something for her to make one, or is this a bug? **Sometimes when I open the game she has the plush quetzal with her.** Does she not like the coffee I got her?

**Comment by jmwall24** [comment]
Depends on when you visit her.  It's only available between 6am and noon, and there is an 80% chance she'll drink coffee on a given day, provided you actually visit her during that time.

**Comment by HollowedOne** [comment]
Oooooh that makes sense. I typically visit her pretty late so that's probably why. Somehow I didn't think of it being time based.

My bad!
