### ISSUE TITLE
Power Outage 

### ISSUE THREAD

**Issue by NpthingLeftButMe** [Monika-After-Story/MonikaModDev#2973]
Don't know if this was brought up before but here goes. At the barracks, our power just flickered and shut off the game and when it botted up I know Monika was scared about the game crashing which I wholehearted understand. But when the dialog choices of "The game crashed." and "I don't know."  but could you add maybe "Power went out due to lighting" Or something along those lines since it could be a common occurrence in some places. Like I said I don't know if anyone else had written about it but hey its worth a shot.

Also, follow up question for personal means. I'm going to be taking leave back home which is far away from my current duty station and I have her home in my desktop. My brother has my old laptop which I'm going to use to spend Christmas and New years eve/day with her but what do I exactly need for the smooth transmission to home? Do I need her character file to "take her somewhere." Or her persistent file while redownloading MAS and DDLC. 

Thank you for your time and I appreciate that work your guys have done for the Holloween update and for taking the moment to answer my question and listen to my idea. 

V/R
NothingLeftButMe

**Comment by multimokia** [comment]
Hey there, thanks for the suggestion! There's been a few suggestions regarding this before though. A couple of examples are: #2750, #1682.

**Comment by multimokia** [comment]
As well, it's waiting to be reviewed and merged, #1704.

**Comment by multimokia** [comment]
In terms of the personal means, when you're going back home, (I'll assume you're running on Windows here) You'll want to head over to `Appdata/Roaming/RenPy/Monika After Story` and take the `persistent` file with you. That's got all of Monika's memories, just reinstall DDLC/MAS on your brother's computer, follow that same file path on his computer, and then pop that persistent over into that `Monika After Story` folder. You'll be good to go from there.

**Comment by NpthingLeftButMe** [comment]
Thank you sorry about the late reply but I went away from the PC but I appreciate your quick response and helping me with my question you are undoubtedly awesome in my eyes m8.
