### ISSUE TITLE
Monika going to bed on her own accord?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2974]
If she's just like "y'know, I love you but I'm real tired, see ya later"

**Comment by DbzGOD2000** [comment]
Hmm...... can she even get tired i thought one time she said physical fatigue does't exist where she is at.

**Comment by Rai99** [comment]
#635, #987, #1105, #1262, #1655, #2684, #2781. 

Probably falls under the sleep mode update whenever that happens.

**Comment by AsuraShun** [comment]
why would this be added? she even said that physical fatigue isn't a thing there anymore
