### ISSUE TITLE
Customize Promise Ring

### ISSUE THREAD

**Issue by DbzGOD2000** [Monika-After-Story/MonikaModDev#2975]
I'm not sure was this already suggested or not but you know the promise ring the player would give Monika on her Birthday it would be cool if the love player can customize the ring like giving it different colors like green, red, blue, gold, and etc. It would also be cool if we can give it different designs too.

**Comment by Olliesama** [comment]
Surely a ring would be customized before giving it to someone? :thinking:

**Comment by DbzGOD2000** [comment]
@Olliesama Yea, but i mean like how on MAS i would love to be able to customize the promise ring since no one couldn't customize it before giving the ring to her. Do you understand what i mean?

**Comment by DbzGOD2000** [comment]
lol

**Comment by wucked** [comment]
I believe you can customize the ring manually by editing the ring assets in the files. They're already in `.png` format so it should be not hard. Monika won't react to the changes of course.

**Comment by DbzGOD2000** [comment]
@wucked Thanks
