### ISSUE TITLE
"I wouldn't want you to get sick"

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#2976]
From.. staying up too late?

Is that even physically possible? 

I rarely get sick, last time I had anything more than a sniffle was 2012.. so the concept of getting proper sick from lack of sleep is odd to me.. I mean, there's proper sleep deprivation but we're just talking staying up on a saturday night..

**Comment by wucked** [comment]
Yes, messing up the Circadian Rhythm is devastating for some people especially for the long run. Organs will fail faster on older ages if the person has a consistent lifestyle of this.
