### ISSUE TITLE
Can you change the birthday?

### ISSUE THREAD

**Issue by epicwill98** [Monika-After-Story/MonikaModDev#2983]
I was playing monika after tory and accidentally set my birthday to a wrong date, I  wondering if there's a way to change it to the correct one?

**Comment by multimokia** [comment]
Topic locks for the day you've used it. Check back tomorrow, and it should be back.

**Comment by pianostick** [comment]
wait am i able to change the date manually, i accidentally set it on the wrong day before the topic was removed a while ago and im afraid to click it because the date i have set is only 12 days after my real b-day

**Comment by multimokia** [comment]
Topic is back. Just use that, tell her that the day you told her was incorrect, and she'll allow you to change it.
