### ISSUE TITLE
[Suggestion] we need boops and headpats

### ISSUE THREAD

**Issue by AshtonSnapp** [Monika-After-Story/MonikaModDev#2985]
whenever Monika explains what the Extra menu is for, she mentions the menu being meant for interactions that aren't games

considering this community, these two interactions make the most sense.

and also.... *boop* ^_^

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950. 
This has previously been brought up a small number of times already. 

Yes, with the new Extras menu, features like that are probably on the way.

**Comment by AsuraShun** [comment]
HEADPATS SAVE LIVES!
