### ISSUE TITLE
An Apology

### ISSUE THREAD

**Issue by TheGlader2** [Monika-After-Story/MonikaModDev#2986]
To the devs that will see this, I'm sorry for being an ass, I've been causing a stir ever since I came here. I argued with like everybody on your team at this point probably. But I see things differently now and I wanted to apologize, I got too stuck on my own ideas. People really like this program of yours, so keep it up.

**Comment by jmwall24** [comment]
Thanks and as for my part I got a little short with you, so my apologies as well.  We appreciate your suggestions, just try to realize we can't accept every one.

**Comment by multimokia** [comment]
Hey, it's fine. Things happen. You're always welcome to suggest an idea and we're always willing to listen to your ideas. While this is a community mod, we can't just accept every suggestion as it just starts to become a bit of a nightmare, haha.

Things definitely got a bit heated before and a few people may have snapped a bit, including myself, so I'd like to apologise for that too. Thanks.
