### ISSUE TITLE
[Bug] - I can't change Monika's hair

### ISSUE THREAD

**Issue by coolbeans147** [Monika-After-Story/MonikaModDev#2990]
I've been playing for quite some time and have been wondering when I'd get the random event for a new hairstyle, but it still hasn't happened. But today, she had some dialogue about me being able to change her hair whenever, but I still don't have the option to actually do it. "Do you miss my ribbon, MC?" "I can change my hairstyle whenever you want me to" and yet she still very much has her normal ribbon on, so I think this is a bug rather than me being too blind to find the right menu option. Any help would be appreciated!

**Comment by Bam8647** [comment]
If you don't see an option in _Talk>Ask a question>Monika>Can you let your hair down/Can you tie your hair into a ponytail?_ Then either your affection isn't high enough or it's a bug(especially if she's talking about wearing her ribbon when she already has it on..)

In fact I'm pretty sure this specific issue was being worked on by the devs just recently, so there should be a fix by the next update or so.

**Comment by jmwall24** [comment]
Yep.  Has been fixed here #2869.  Next release all will be well.
