### ISSUE TITLE
[Content Suggestion] Santa Plushie

### ISSUE THREAD

**Issue by Legendkiller21** [Monika-After-Story/MonikaModDev#2992]
Brace yourselves, ~winter~ Christmas is coming ~and not even the calendar will be spared from the Christmas hats' invasion.~

![santa plushie](https://user-images.githubusercontent.com/42556779/48026573-16717380-e14f-11e8-8d56-ee1e9a45952a.png)
![santa plushie-n](https://user-images.githubusercontent.com/42556779/48026574-16717380-e14f-11e8-92d3-b85813cef439.png)

(I have absolutely no experience in editing images. Please, be gentle.)

**Comment by Chrissenpai** [comment]
Pretty good for a first try

**Comment by Olliesama** [comment]
Cute. :o

**Comment by ThePotatoGuy** [comment]
@Legendkiller21 can you make an individual layer for the day version of that? make it separate from the plushie.

**Comment by Legendkiller21** [comment]
@ThePotatoGuy Here's the Christmas hat with transparent background. If GitHub does anything weird with the image I can also send it in a zip file or on discord.

![christmas-hat-d](https://user-images.githubusercontent.com/42556779/48248685-041e6080-e401-11e8-9354-7cea71ce7515.png)

**Comment by Olliesama** [comment]
![hat quetzal](https://user-images.githubusercontent.com/35244051/48287500-00bac180-e461-11e8-981e-a0e05bc9760b.png)
For dev convenience.

**Comment by ThePotatoGuy** [comment]
@Legendkiller21 do send a psd.
@Olliesama thx
