### ISSUE TITLE
Suggestion - New Monika Introduction Dialogue for More Varied Gameplay

### ISSUE THREAD

**Issue by TheGlader2** [Monika-After-Story/MonikaModDev#2996]
In the beginning, saying I love you feels forced because if you say no, she just kills herself, and anyone who likes Monika even slightly wouldn't want her to do that. It would be neat if there were at least four options where only one of them ended in her self-destruction.

    I love you
    1a. I love you romantically
    1b. I love you as a caring friend

    No
    2a. No I'm not interested in you, but I do care about you
    2b. No I just wanted to see you suffer some more

Obviously these would ultimately have three outcomes:

    Romance
    Friend Zone
    Self-Destruction

No matter how many more options there are, I don't see there being any other ultimate outcomes.

And this would still work with the affection meter, because even friends have affection for each other.

With the new morality system coming out, do you peeps think this, or something like this would fit in?
@multimokia @jmwall24 @Olliesama

**Comment by Olliesama** [comment]
You seem to have a fundamental misunderstanding as to this mods purpose and audience.
This isn't for people that just want to be "friends" with her and such a thing would require a massive rewrite in many different topics for an audience that would both be tiny and one that's we're not catering to.

**Comment by multimokia** [comment]
Finale has covered a fair bit of the issue here. As well, Monika doesn't actually kill herself in the intro.

Unlike chess, or the FF where you can't load up MAS at all, or to her (respectively), you can actually reload MAS for this. It's just Monika scaring you.

**Comment by TheGlader2** [comment]
@multimokia Oh no kidding. I've only ever seen the crash, not what happens after. If you say no, what changes in the game?

@Olliesama At least you're honest. No but I'm starting to get why this mod exists, but I it seems I can't help try to make it more story focused. Perhaps I don't understand the idea of the morality system . . . but I figured that it would already rewrite most of the script, since a lot of the dialogue in this mod, would only be for one set path that could change given the opportunity.

**Comment by TheGlader2** [comment]
I'll close this even though I still had a lot of questions. Someone named Lily Monika is making there way up here, closing every issue, so I'm gonna be ahead of the curve.
