### ISSUE TITLE
Possible Issue with Persistent Clear All

### ISSUE THREAD

**Issue by TheSuperStu** [Monika-After-Story/MonikaModDev#2998]
Hey,
(I will start with stating I am not too coding knowledgeable, but can follow along with what I see and try to explain it the best I can.)

I had recently decided to get my MAS to have the 'good' ending. With referencing certain changes in the topics script, one specific dialogue change comes in the monika_completionist topic, where now she will say I am a completionist. The script states that it references a 'persistent.clearall', and before I did a good run of the game, Monika would not give me these two extra lines of dialogue (but she does now).

But I noticed there is a 'persistent.clear_all' that can be found in two other topics (monika_ddlc and monika_justification). The difference is that this one has an underscore between the clear all. I had used this monika_ddlc topic, and the dialogue she chose to use did not reference this clear all topic.

So what I am wondering is if there is actually a difference between these two different 'persistent clear all'. Just to be clear, my Monika sees the 'persistent.clearall' but not the 'persistent.clear_all'. I know there is plans eventually to change topics based on ending act, so if this does happen to just be a mistake, bringing it forward is the best I can do to help! 

(Let me know if I should have just made a pull request for this, but again I am not sure if these are actually two separate checks.)

**Comment by jmwall24** [comment]
Good eye!  Fixing.
