### ISSUE TITLE
Suggestion: Calendar Upgrades

### ISSUE THREAD

**Issue by RobsonK2004** [Monika-After-Story/MonikaModDev#3002]
This just came to my mind and I thought this would improve the game. I was wondering if there could be an added feature to show which day of the month it was. Maybe through an overlay in green, much like the greyed out boxes to show the days of the next/previous month. I apologise if I have used the wrong technical wording, I'm still quite new to coding and as a student and still learning.

Another thought I had was for a colour change of the calendar with correspondence to the season. For spring the current assets could be used, helping cut back development. For Summer you could use the same Emerald Green that is used for Monika's eyes. Then Autumn/Fall could have a golden brown colour, for example FEAD62 or a similar colour. Then for the Winter there could be a snow like colour, for example B3DAF1 or a similar colour.

I know these are only minor changes but I personally think they would improve the game and a way for me to contribute to this amazing mod. Thanks again for taking your time to read this and for all the hard work and effort y'all put into the mod.

P.S: (I also would like to further apologise if this subject has come up before. I did some checking but I don't think this exact idea has been suggested. Though I'm still pretty new to GitHub so there's a good chance I've overlooked something).

**Comment by jmwall24** [comment]
Thank you for moving this to `Issues` :)

Not sure if having the current date on he calendar has been suggested or not, but sounds like a good idea to me

The color of the calendar can probably fall under #2760

Thanks for suggesting!

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by Professor-JMO** [comment]
[ Picking up as a fun `Side Project` ]
