### ISSUE TITLE
[Suggestion] Choice to stop using a pen name

### ISSUE THREAD

**Issue by XIIIDarkRoxas** [Monika-After-Story/MonikaModDev#3003]
A long while ago, I told Monika I was using a pen name but have recently decided to just stop using it altogether, as it fits better as a characters name rather than my own.

However, changing my pen name to my real name doesn't make her think that I've stopped using my pen name, but that she thinks that my real name is just a fake that I told her.

So I would like to propose another option for the "Are you still going by [pen name], [player]?" Question being "I decided to stop using a pen name" or something along those lines.

**Comment by Torwald39** [comment]
you just have to repeat the pen name conversation and tell her you change your mind

**Comment by XIIIDarkRoxas** [comment]
That seems kind of unintuitive, but I appreciate the answer.

**Comment by Torwald39** [comment]
Okay i will be more clear.

For change your pen name, select "repeat conversation" then the topic "pen name".
Then you'll have the normal conversation and Monika will ask you if you're pen name still the same, there you can tell her no and change your pen name.

**Comment by XIIIDarkRoxas** [comment]
I got that part, but I feel like there should be an option to clear the pen name so that there just isnt one for her to remember. It actually seems simple enough that I might be able to just write it myself so it wouldn't even be a problem.

**Comment by TheSuperStu** [comment]
I just played around with the topic, and it does not seem like it is possible to clear out having a name, even if you say you changed your mind and you do not want to share a new name. It does seems a little weird there is not a way to clear the pen name, so I see what your saying @XIIIDarkRoxas. 

Right now it looks like if you ever do give any name Monika will have to remember something. How the topic is right now, there would need to be an option to say your not using a pen name anymore. So when the topic is used later and she asks if you have a pen name, you can just say no.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
