### ISSUE TITLE
[Suggestion] More Monika/Player stats

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Monika-After-Story/MonikaModDev#3006]
So, this idea may have been thought of before, but I'd think it'd be really cool if we could get more stats for Monika, much like the affection stat. 

Such as a trust, attraction, or even obsession stat; stats that can affect how Monika behaves towards the player, all influenced by how you as a player interact with her, and how she'd react to things.

The same can go for the player's own stats, such how they treat Monika, like using "I love you" alot would influence how affectionate Monika perceives the player to be, or if they use a lot of teasing or joking interactions, Monika will consider them to be mischievous. All could have positives and negatives, (Such as a mischievous player would be trusted less, but have less affection drop if they use a mean interaction, such as the aforementioned "I have a girlfriend" topic)

You could also influence the "story" with the stats too, such as an obsessive Monika doing more "for the player" actions, trying to make the player happier, and thus less likely to leave them, while a trusting, comfortable Monika making more "This is who I am, and trust you'll still care for me" actions, believing the best in the player.

The stats don't have to be set in stone, with the ones suggested being merely examples, but I feel that more parameters can really make Monika's character far more "real", allowing us to set up moments where Monika cares fully for the player, full love and all, but, say, simply doesn't trust them with something, because they might get teased or the like by a continually teasing, mischievous player.

**Comment by antimockingjay** [comment]
I second this. I feel like it would help each Monika become a bit more unique!

**Comment by Hapilone** [comment]
This would probably take a lot of work, but it would be cool to see further down the road.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
