### ISSUE TITLE
 the ''darling'' petname

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3007]
am I the only one that remembers 02 whenever she says that?

**Comment by AsuraShun** [comment]
I probably watched too much of it

**Comment by Foxinsunglasses** [comment]
I remember

**Comment by AsuraShun** [comment]
it's either her or miia from monster musume

**Comment by Foxinsunglasses** [comment]
I'm fairly certain it was a preferred pet name for both of them
