### ISSUE TITLE
[suggestion] nicknames and full/real names

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#3008]
I thought that it would be appropriate for Monika to call you by your nickname or by your full/real name depending on the situation. For example, if Monika mentions you in a serious conversation, she would refer to you by your full or real name. If Monika mentions you in a regular conversation, she would refer to you by your nickname.

**Comment by AsuraShun** [comment]
but we'd need for a topic to set our real names for such thing to happen
