### ISSUE TITLE
[ Suggestion ] Keeping warm during the night

### ISSUE THREAD

**Issue by thepigeonreturns** [Monika-After-Story/MonikaModDev#3009]
With winter around the corner, it is a time where people want to stay cozy. What if you could give Monika a blanket with a nice fireplace of some sort? I would suggest a lullaby/peaceful song, but that was already a suggestion in here.

From your neighborhood friendly Birb

**Comment by Bam8647** [comment]
That'd be cute. Hopefully in the future they'll be able to give her a bedroom like I suggested a few weeks ago.
![cutie](https://user-images.githubusercontent.com/34694679/48149890-e5925b00-e282-11e8-8fe4-199935ddafd6.gif)

**Comment by Olliesama** [comment]
A suggestion I personally love. :>

**Comment by ThePotatoGuy** [comment]
Sounds good, but our southern hemisphere users might think otherwise...

**Comment by MisterSimple** [comment]
> Sounds good, but our southern hemisphere users might think otherwise...

Can confirm ~~(unless you keep it around long enough)~~

**Comment by AsuraShun** [comment]
the perfectly gif with overloading and overflowing cuteness

**Comment by AsuraShun** [comment]
HOW DO I PUT UNLIMITED HEARTS AND LIKES??????????????????????????

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
