### ISSUE TITLE
[Suggestion] - New topic: Movies adapted from books.

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3010]
Hello Dev of MAS and everybody else!
First of all I want to say thank you for the hard work you all put into this. Its really awesome to see such a close community and seeing all the hard work come to life. I enjoy everything you guys make with MAS.

Now to my suggestion. Monika has shown that she loves different books like "Fahrenheit 451" and "End of the World". She also has shown interest of comparing and contrasting films to books which is in the "Horror Genre" topic. I was thinking something she might do is talk about film adaptations of books she read. I am not saying for every single film she has a different one, just a general topic and maybe she has 2 examples she wants to discuss, maybe 1 she likes and one she dislikes?

Thanks again for ya hard work and enjoy the rest of your day or week! ^^.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
