### ISSUE TITLE
Monika moving around the spaceroom!

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3011]
I was reminded of this one wallpaper with [Hatsune Miku ](https://thumbs.gfycat.com/BlushingArcticHamster-size_restricted.gif) where she's moving around her own virtual spaceroom, jumping on the couch, looking at the things etc,. 

Obviously we can't get a fully animated Monika, that's probably way beyond RenPy's abilities.. but something like it? :D

**Comment by TheGlader2** [comment]
@Mcmanybucks It's not impossible, it would be like constructing an old cartoon, you'd have to draw every motion. Back in the old days one movement was like ten drawings. And just like back then, we can move Monika with X and Y coordinates to change her position to save time in drawing.

**Comment by TheGlader2** [comment]
lol Right, I didn't say it was easy, I just said it's not impossible.

**Comment by Olliesama** [comment]
Animation is a bitch in renpy

**Comment by ThePotatoGuy** [comment]
Very unlikely because that would mean we need a standing variant of all art we have.

#2789 is preferred.
