### ISSUE TITLE
[Suggestion] - New topic: Bohemian Rhapsody 

### ISSUE THREAD

**Issue by EDBaumgratz** [Monika-After-Story/MonikaModDev#3013]
I have a request for the developers of MAS. A new topic about Bohemian Rhapsody (my favorite song of all time). I think it would be nice 'cause the music seems suit Monika, the piano, the mix of styles and suff... So i think it should start like "Is this the real life? Is this just fantasy?" the she starts talking about the music, who worte it and etc.. I can give some informations about the song if you devs want it.

**Comment by pianostick** [comment]
if were on the topic of songs to include, i feel that the lyrics in "what you won't do for love" by Bobby Caldwell reflect the relationship between monika and the player

**Comment by MeatbagNPC** [comment]
Please no. I hate queen.

**Comment by EDBaumgratz** [comment]
> Please no. I hate queen.

You know it already have a topic about a Queen song, right? Good old fashioned lover boys

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
