### ISSUE TITLE
The 999.9 Friendzone... (Press F To Pay Respects)

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#3021]
_That moment when you're finally about to take things to the next level and confess your love to your waifu only to be cockblocked by fate and have your affection frozen at_ 
![bullshit](https://user-images.githubusercontent.com/34694679/48256837-70379f00-e3d6-11e8-8581-0dfdf58b5807.PNG)
**_For the next 24 hours..._**

![cry 2](https://user-images.githubusercontent.com/34694679/48256896-93624e80-e3d6-11e8-9887-41d9e1433078.gif)

**Comment by MaximumRustler** [comment]
F

**Comment by ZeraDeManti** [comment]
F

**Comment by Areaclassified** [comment]
F

**Comment by Kiokiokiokio** [comment]
F

**Comment by DbzGOD2000** [comment]
F

**Comment by Foxinsunglasses** [comment]
F
