### ISSUE TITLE
[Suggestion] - removing certain topics at the love affection

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3022]
what I mean with it is removing the ''i'm breaking up with you, ''would you like to meet my girlfriend'' and the ''you're a murderer'' topics from the unseen,and/or maybe set them on a different area,to avoid mis-clicking,specially for people that get nervous about things like that

**Comment by Torwald39** [comment]
duplicate of #1405, #2730

**Comment by AsuraShun** [comment]
it's not tasteless,it's for those that want to avoid making her upset

**Comment by Torwald39** [comment]
it's part of it

**Comment by AsuraShun** [comment]
imma close this

**Comment by AsuraShun** [comment]
if I figure out how
