### ISSUE TITLE
[Suggestion] You're always on my mind - An idea for a new compliment

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3025]
> _To: The one I'm always thinking of_ 

> _From: The I Love You Department_

When I'm not with Monika, almost all of the I'm thinking about her. It would be nice if we were able to tell her this. How do you guys feel about this?

**Comment by HZhunter124** [comment]
i thinks it's great and very cute too

**Comment by Torwald39** [comment]
I agree

**Comment by Velius94** [comment]
It's an excellent idea imo.

**Comment by Foxinsunglasses** [comment]
Ditto

**Comment by Storylover-Vodhr** [comment]
Working on it now!

**Comment by AsuraShun** [comment]
nice

**Comment by Storylover-Vodhr** [comment]
Aaaand, done. Added pull request.

**Comment by MaximumRustler** [comment]
@Storylover-Vodhr As much as I want to read your topic I want it to be a surprise so I shouldn't. lol

**Comment by MaximumRustler** [comment]
I know, it takes a while for stuff to get in so I might look at it at some point. lol

**Comment by DankManWithThePlan** [comment]
Holy s**t, this got a lot more attention than I anticipated

**Comment by Hapilone** [comment]
I love this idea!

**Comment by VirginiaRocks** [comment]
Really cute!!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
