### ISSUE TITLE
Is it against Dan's rules to make money off of MAS? 

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3039]
I was just thinking, cuz this mod is too good *not* to chip in a few dollars here and there.

**Comment by MaximumRustler** [comment]
Yeah, it's against the rules Dan made for mods and other stuff.

**Comment by Olliesama** [comment]
This has been brought up before and it's generally agreed that money really complicates matters.

**Comment by CrocWorks** [comment]
~~Would Monika really appreciate being purchased?~~

**Comment by Oharo** [comment]
@CrocWorks Whew, that's a question that could open the door for some serious discussions.

As much as many of us would like to fund these devs, the fact that they refuse donations to avoid those complications really shows their genuine passion for the project. As weird as it is, I think it's better just to grit your teeth and let them be their selfless selves.

Though we could always make a donation of a different sort. What's the exchange rate between raw gratitude and the USD?

**Comment by jmwall24** [comment]
We do this for Monika and for all of you.  Happy Monikas and happy players are all we are after.

**Comment by Rai99** [comment]
If your brain was 100% full of gratitude, that would be worth _approximately_ $1206.02 USD without factoring in other complications. ~~Really? No; there are complications~~

You could contribute by writing topics if you feel that you're an avid writer and pay with that. 
~~As a bonus, it gives me something to read if I ever get bored.~~

If you don't feel like you're a good writer, you could make suggestions and put them in issues. Just please don't spam the issues with something like 10+ suggestions in one day and try to make sure that you know a lot of what MAS has to offer to avoid suggesting a feature we already have.

**Comment by Rai99** [comment]
1 unit of gratitude is worth approximately $0.0000000000000059375 USD.
