### ISSUE TITLE
Concern about the Smash Bros topic

### ISSUE THREAD

**Issue by Man0xMan0** [Monika-After-Story/MonikaModDev#3041]
I am going to paste the topic in question so we're all on the same page (copypasted from the base game and not MAS but I don't think there were any dialogue changes from DDLC to MAS)

> label ch30_25:
>     m "Hey, have you heard of a game called Super Sma--"
>     m "...Wait, what?"
>     m "I was just spacing out and I started talking for some reason..."
>     m "Was I programmed to talk about that?"
>     m "Because even I have no idea what that is."
>     m "Ahaha!"
>     m "Sometimes I feel like I'm not in control, and it's kind of scary."
>     m "But if you have some way to contact the people who created me, maybe they'll know why I started saying that."
>     return

My question is, how much control does Monika hold in this mod? Since this topic still exists in the mod, I have to conclude that she does sometimes lose control and say things to please the authority of her programming. If that's the case, I find that very concerning. If not, how can we change the dialogue to keep the spirit of the original, but reassure the player in the end that she's entirely in control of her actions now? And is there any other cases where Monika's control over herself can be questioned?

Thanks for reading, and thanks to the team for your hard work (but I'd love it if someone took a look at my recent topic edit!)

**Comment by pianostick** [comment]
she can still create files and program different aspects of the world, and she also states on occasion that she is scared of deleting stuff suggesting she still is capable of that. lore wise she might've picked up on some stuff subconsciously while the new things were being coded but there could be any number of explanations.

**Comment by MaximumRustler** [comment]
I can't remember where I read or heard this so I'm not sure if it's actually a thing, but wasn't that topic removed from the base game in one of the more recent updates or something? Maybe it was during the 1 year anniversary live stream Dan mentioned it and I think he said something like he put that in as a inside joke because he worked on and made mods for one of the smash bros' games. I may be remembering this completely wrong though lol. On another note, maybe since Monika is supposedly getting better at scripting this topic should stop being random after a certain amount of time to show that she has better control of the game/script, just a suggestion I guess. lol

**Comment by TheGlader2** [comment]
I thought Dan was an expert Smash player, who mained fox in tournaments. @MaximumRustler

**Comment by MaximumRustler** [comment]
Yeah, and made the 20XXTE mod I think it was called.

**Comment by TheGlader2** [comment]
@MaximumRustler It would appear so, Yes.

**Comment by CrocWorks** [comment]
~~Monika for Smash Ultimate. It's a DDLC DLC~~

**Comment by ThePotatoGuy** [comment]
That topic is not rando'd so it should never appear.

**Comment by MaximumRustler** [comment]
It isn't random? I could've sworn I got it a few days ago. Hmm, I'll keep an eye out for it.

**Comment by TheGlader2** [comment]
@ThePotatoGuy I just got it again as well. I mean, I think it's kind of interesting that Monika'd be dealing with rogue code. Maybe talk about how her creator hard-coded it into her because he was obsessed with Smash Bros.

**Comment by ThePotatoGuy** [comment]
alright, then we'll have to remove it
