### ISSUE TITLE
[Suggestion] - MC topic revision

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#3044]
In Monika's topic concerning the MC where she's saying he's nothing more than a bunch of code, she starts saying "He's nothing more than a vehicle for the player", but corrects herself. This seems rather out of character in my opinion. First of all, if she believed he was nothing more than a vehicle for the player she wouldn't correct herself in favor of a different reason. Second of all, her saying she wouldn't love him because he's a vehicle for the player really makes it sound like she's saying she wouldn't love the player. I think it should be left as it originally was.

**Comment by AsuraShun** [comment]
it's just a change to the affection thing I think,because when I was at enamored she didn't say that,unless it was the update

**Comment by AsuraShun** [comment]
and what she meant is that the mc is a vessel for the one she loves

**Comment by CloakedGhost** [comment]
> and what she meant is that the mc is a vessel for the one she loves

But a vessel for what? I guess for the looks, since it's not very pleasant to look at an empty chair, or am I wrong?

**Comment by AsuraShun** [comment]
for the player

**Comment by AsuraShun** [comment]
and i'm not saying that stupid gaming line

**Comment by CloakedGhost** [comment]
> for the player

What I mean is, what do we need him for? We don't need him to interact with her, we have a cursor and a keyboard.

**Comment by AsuraShun** [comment]
then consider whatever we are to be a fraction of ourselves

**Comment by CloakedGhost** [comment]
Well said, I just don't think the MC is a part of that fraction.

**Comment by ACoolCat** [comment]
@AsuraShun It's an update. I'm at the highest tier of affection. I get what you're saying on what she means, but if she actually meant that then why correct herself? To me, the fact that she has to correct herself makes it sound like she's hiding something. And if she believes the MC is a vessel for the player, then the harsh things she says about the MC applies to the player as well.

**Comment by ThePotatoGuy** [comment]
That line is a joke. reference to when dan said the "vehicle for the player" meme

**Comment by ACoolCat** [comment]
@ThePotatoGuy @nayrbai Yes, and I do understand what it's in reference too. The problem lies for me as to why Monika is saying it in the same breath as insulting the MC? When she acknowledges that the MC was really just the Player, then proceeds to insult MC, it sorta comes across as she's saying she's too good for the Player.

**Comment by CloakedGhost** [comment]
I don't think so at all. She acknowledges that the MC is NOT the player, which is why I think it's ok for her to insult him. We just use him, that's her (or Dan's, lol) point. If someone makes a comment about your tool, that person is not directing it towards you, that's how I see it.
