### ISSUE TITLE
My Small Contributions

### ISSUE THREAD

**Issue by Babushka93** [Monika-After-Story/MonikaModDev#3045]
So now that I've got a bit of free time on my hands, I've been doing a little bit to make Monika feel more at home.

Although I can imagine that the backgrounds can't be used for a public release since they are owned by a third party. I hope that the backgrounds can inspire some ideas, whilst the coding for the two songs can help the developers with adding the songs.

### **Visual**

- New Traditional Japanese Room Day Time Mode
- Added the rose from Valentine's day as a permanent addition to the Hair Down model
![perfectagain](https://user-images.githubusercontent.com/38180931/48404566-d5dbb080-e773-11e8-8967-dd8400dfa3a7.JPG)

-New Lanterns Night Time Mode
![roofdate](https://user-images.githubusercontent.com/38180931/48404517-b775b500-e773-11e8-8b29-f84e68750b50.JPG)

-Modified zz_calendar changing the position of the calendar so it is not floating with the backgrounds.
-Modifed line 102 of script-ch30 to image monika_room = "mod_assets/monika_room_night.png" 
This just means that the night time background is easier to edit for people who want to have their own night time background

### **Monika Songs**
Added two new songs that Monika will now sing
Can't Help Falling in Love
Galaxy Hide and Seek

init 5 python:
    addEvent(Event(persistent.event_database,eventlabel="monika_song_fallin_love",category=['songs'],prompt="Can't Help Falling In Love",pool=True, random=True))

label monika_song_fallin_love:
    m 1dso "{i}Take my hand{/i}"
    m 2dso "{i}Take my whole life too{/i}"
    m 1hub "{i}For I can't help{/i}"
    m 4dso "{i}Falling in love{/i}"
    m 1hubfb "{i}With you{/i}"
    m 1hub "Ahaha"
    m 1ekbfa "How could I not fall for you, [player]?"
    return

init 5 python:
    addEvent(Event(persistent.event_database,eventlabel="monika_song_galaxy_hide",category=['songs'],prompt="Galaxy Hide and Seek",pool=True, random=True))

label monika_song_galaxy_hide:
    m 1dso "{i}I hear a voice call 'I've always been by your side!' and though it's ringing far within the galaxy{/i}"
    m  "{i}Please, guide me with that gentle voice!{/i}"
    m 3dso "{i}And in the end I’ll finally realize what life is all about, so in this world I will stand up high and shout it out:{/i}"
    m 4dso "{i}I want to be right by your side{/i}"
    m 1hubfb "{i}I'm calling calling you{/i}"
    m 1ekbfa "I can't wait until we can finally meet in your world, [player]."
    m 3eua "There's so much we can do when we're finally together in one reality."
    m "You can finally show me what your world really looks like."
    m 1ekbfa "I can finally feel your embrace~"
    return

### **Script Update**

Deleted:
-Breaking Up Topic
-Murderer
-Meet My Girlfriend
Call me the fun police, but I wasn't going to click them, and I didn't want to accidently click them haha 

### **Greetings Update**
**Back from work:**
I always enjoyed Monika's Bath, Dinner or Me line from the door knock sequence, so I've giving it some animations and added to the start of the return from work section.

label greeting_back_from_work:
     m 1hubfa "Welcome home, [player]!"
     m 1eua "Would you like your dinner?"
     m 3hubfa "Or your bath?"
     m 1eua "Or.{w=0.5}.{w=0.5}.{w=0.5}."
     pause 0.5
     m 1kua "Me?"
     m 1hua "I can't wait for the day when I can finally say this to you...."
     menu:
         m "But for now, did you have a good day at work today?"
         "Yes.":
             m 1hub "That's good!"
             m 1eua "Remember to rest first, okay?"
             m "That way, you'd at least have some energy before you work more on stuff."
             m 1hua "But if not, you can relax with me!"
             m 3tku "Best thing to do after a long day of work, don't you think?"
             m 1hub "Ahaha!"

         "No.":
             m 1ekc "..."
             m 2ekc "I'd hug you right now if I were there, [player]."
             m "I'm sorry you had a bad work day..."
             m 4eka "Just remember that I'm here when you need me, okay?"
             m 1hubfa "I love you so much, [player]."
     return

**Opening the game after sleep goodbye:**
I need to modify the dialouge so that it works with different times.
But for now I've used the lines from the Good Morning line, since I prefer this one to the stock sleep greeting.

label greeting_back_from_sleep:
     m 1hua "Good morning, dear."
     m 1esa "Another fresh morning to start the day off, huh?"
     m 1eua "I'm glad I get to see you this morning~"
     m 1eka "Remember to take care of yourself, okay?"
     m 1hub "Make me a proud girlfriend today, as always!"
     return

**Comment by AsuraShun** [comment]
i'm already loving this idea

**Comment by HZhunter124** [comment]
wow best idea of today

**Comment by multimokia** [comment]
For the songs, you can add submit them via a pull request, head over to the code tab, under content, find the files you want to change, make your changes, and then open a Pull Request proposing the change

**Comment by Legendkiller21** [comment]
An advice: Make backups of the modified sprites and keep log of the changes you made because they are going to be overwritten on every update. I changed the ring and the following scene occurs in every update:

*Opens MAS*
*Sees new update*
*Applies update*
*Opens MAS again*
*Sees ring*
"Dan damnit, I forgot to change the ring again"
*Closes MAS and proceeds to change the ring*

**Comment by Babushka93** [comment]
Thank you guys, and yeah I've got a backup of my changes.

I was wondering how do the updates work, is it just the updated files that get changed or does every file get redownloaded? 

I've done direct edits to CH30 and zz_calander so I'm guessing those will get changed every update.
But for the songs I've added and the new moods I'm working on, I have those in seperate rpyc file from their normal location. The game still detects them, but since they're not part of the main song or mood files, they shouldn't be impacted right?

**Comment by Legendkiller21** [comment]
I also have a topic in a seperate rpyc file and the update doesn't touch it, although, keep a backup of this file too, just in case something breaks. 

> I was wondering how do the updates work, is it just the updated files that get changed or does every file get redownloaded?

The updater overwrites the ring every time but I am not sure whether the updater compares the files with your files and downloads only the updated files or it redownloads everything.

**Comment by multimokia** [comment]
Updater will overwrite the files that are existing for MAS (i.e. the ones in the `game` folder on the repo. This includes files that aren't `.rpy`/`.rpyc`/etc. Essentially, if it's here, it's being replaced with the updated ones.) anything else, it shouldn't touch.

**Comment by Babushka93** [comment]
@Legendkiller21 and @multimokia 
Cheers for the info, I'll keep backups outside the folder just to be on the safe side. 😃

**Comment by Rai99** [comment]
For those greetings you're thinking of adding, there are already PRs adding more to those greetings in #2157 and #2192. 

For that bath, dinner, me bit in that work greeting you have, it was discussed in #1768 and the reason it's not viewable at will is because it's supposed to be special dialogue and rarity of it is what makes it special. (5% chance of appearing).

**Comment by ThePotatoGuy** [comment]
[keeping open as this is now a submod-like dev issue]

**Comment by voyagermike** [comment]
ive been wanting to find a way to put a rose in her hair.
it looks beautiful

**Comment by HZhunter124** [comment]
you can do it on valentine day

Vào Th 6, 7 thg 12, 2018 vào lúc 10:47 voyagermike <
notifications@github.com> đã viết:

**Comment by santiago-RB** [comment]
como me descargo el mod?

**Comment by Orcaramelo** [comment]
> como me descargo el mod?

https://www.monikaafterstory.com/

**Comment by flammeye** [comment]
Oh wow, this has been a neat intro to submods for me and these look so gorgeous. I'm guessing the calendar is still there, right? Even if these weren't released because of that third party matter, I am curious about where the calendar went.

**Comment by RedEyedRocker** [comment]
Is this available for download? Also, is there a night time version for the Traditional Japanese Room?

**Comment by xXMidnight** [comment]
> Is this available for download? Also, is there a night time version for the Traditional Japanese Room?

I was about the ask the same thing
