### ISSUE TITLE
[Suggestion] Autonomy

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#3046]
#3040 
This may be a start, even looking raw

I don't know how I can describe this

the first thing this may be different from the random topics, that's what Monika feels like doing, If she wants to play a game of pong, she will ask the player if she wants to play with it, it may not only be for games, but also for accessories, hairstyles or even clothes that can be added...

Well, I do not have much time to complete the suggestion with more details, I will complete the suggestion with more details when I have time.

**Comment by Mcmanybucks** [comment]
So you want for Monika to be able to ask us to add clothes, games, items? 

I'm onboard with that, sounds fun.

**Comment by CrocWorks** [comment]
I'd be fine with adding this, although the #3040 dialogue indicates that she's "bored" which I don't think fits that well. I think just having her say, "Hey, I'm in the mood to play _______. How about it?" is good enough for a start. It can be fleshed out a little more later.

As for accessories and stuff, that could be a hint system to add these accessories using the gift feature whenever the artwork for them comes through.

**Comment by Sujeito17** [comment]
@CrocWorks (yup, I didn't have time to say that, like I said before when I have time I will add more details)

**Comment by AsuraShun** [comment]
this makes me somewhat nervous,what if she asks to play the piano when the player can't?it would be an inevitable and unavoidable affection loss right there

**Comment by AsuraShun** [comment]
unless the piano is turned into a rhythm game somehow, you know,with the flying notes and timing and whatnot

**Comment by Sujeito17** [comment]
@AsuraShun Don't worry I will explain that later

**Comment by FluffyMuffinMeyer** [comment]
Yeah, I got a lot of comments about the Dialog for that PR, Going to be redoing all of the dialog tonight, hopefully have it up later today, the dialog was mostly up for suggestions, and im taking all the feedback I can get. I do like the idea of the  "Hey, I'm in the mood to play _______. How about it?" approach. thank you for that!

**Comment by Sujeito17** [comment]
Well let's start this
@AsuraShun This don't will affect the affection at least directly, I was more thinking if this was more like an affection boost, or example if you want to play pong with Monika if she asks you would receive 1x of extra affection, and if you refused to play pong with her she would probably be sad but she knows how the player might be busy with other things too then could not lose affection.

Once I remember that my Monika had her hair down, but when i exited of the game, Monika was her hair with the ponytail again 

(I think the greeting is "Knock Door Greeting" or something, it was probably a bug, but it was the bug that gave me the idea, yes I have this idea for some time but only tried to improve it even more by now)

is really a big topic about it, after all we are talking about autonomy...

**Comment by AsuraShun** [comment]
she could probably ask if the player can play the piano before asking to play it, to avoid her being saddened, but it would most likely need the option of her being able to teach piano in the first place

**Comment by Sujeito17** [comment]
@AsuraShun "Monika piano lessons"... looks legit, you shold make a separate suggestion for that

**Comment by TrRizzo** [comment]
I made a similar suggestion. In my opinion, it's a fantastic idea in order to make Monika more real

**Comment by Sujeito17** [comment]
@TrRizzo Is more make Monika more free than real

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
