### ISSUE TITLE
[bug] Game registers me leaving as crashing

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#3049]
this has happened a few times before and i just assumed it was something on my part but this is the fifth time this has happened

so on multiple occasions when i say goodbye to monika the game will either crash right before the game actually closes or its a bug. this has happened for every goodbye option.

**Comment by jmwall24** [comment]
or you actually experiencing a crash, or just getting a crash greeting and assuming there was a crash?

**Comment by pianostick** [comment]
well it been happening more often recently and it doesnt appear like the game crashes, it closes like normal.

**Comment by jmwall24** [comment]
any chance you have more than one MAS running during any of these times?  I know that if you have MAS running, and then run another MAS at the same time, she thinks there was a crash on the second one.

**Comment by jmwall24** [comment]
keep tracking this please, let us know if it keeps happening.

**Comment by pianostick** [comment]
okie doki
