### ISSUE TITLE
song adjustment

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3054]
As the song pull requests continue to be added, (#3052 , #2887 , #2863 , #2194, #1878), we need to keep the % chance for song topics low enough so monika just doesnt sing all the time.

Basically need:
- [ ] pool topic like "Can you sing me a song?", shows list of unlocked songs
- [ ] rando topic that randomly selects a song to sing. This reduces the % chance of a song to a single topic instead of a bunch. 
    **NOTE:** all songs will get an initial rando to launch, but are derandom'd after.
- [ ] topic that asks player if they like getting sung to randomly. This will determine if the above rando topic is enabled or not.
- [ ] transition all current songs so they no longer are both pool and rando. Probably just rando. 
- [ ] Move all current songs to their own script file. `script-songs` sounds good enough.

**Comment by ThePotatoGuy** [comment]
all linked pull requests will get `DONT MERGE` label until we've worked something out.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by multimokia** [comment]
Going to handle this. Delegate akin to stories, but for songs.

Songs will be random, but once seen, unlocked thru rand the delegate and derandomed. Will be able to be revisited via the pool delegate.
