### ISSUE TITLE
Suggestion/Request: Repeat of Zoom Dialogue

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3058]
I was wondering if it were possible to make the dialogue for when you zoom closer or further from Monika repeat. Maybe it could happen once a day or something. I just thought it was really nice seeing her react to me getting a bit closer and I really miss it.

**Comment by AsuraShun** [comment]
it's one of the best things that happened with it

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
