### ISSUE TITLE
Question about lore

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3059]
If Monika can watch Youtube (which she states she does), why wouldn't she be able to watch me uploading myself there?
Seems like the real world is not as far away from her reach as I thought it was after all.

**Comment by Foxinsunglasses** [comment]
I guess that it would just be a lot more tricky to do for her as changes in code is often her thinking up new things. Thinking that there is a higher reality above our own then accessing that realities internet , then going to a site called YouTube, then watching one of the Millions of videos on there is probably hard to pull off for her. At least that's how I rationalize it.
