### ISSUE TITLE
Favorite school subject

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3060]
wouldn't it be interesting if Monika could ask what our favorite main school subject is. Math, Science, Social Science, Language (because not everyone is taught English)

**Comment by AsuraShun** [comment]
she might as well ask if the player is in school or not before asking that?

**Comment by Sujeito17** [comment]
Are you talking about me?

**Comment by AsuraShun** [comment]
-_-

**Comment by AsuraShun** [comment]
there's no 17 there

**Comment by Sujeito17** [comment]
F

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
