### ISSUE TITLE
[Suggestion] The Singularity

### ISSUE THREAD

**Issue by hofeprime** [Monika-After-Story/MonikaModDev#3063]
I came up with an idea to finally be with Monika, and that is the singularity. I wonder if you could insert a dialogue choice for telling Monika about this, or if Monika would randomly bring it up.

**Comment by Bam8647** [comment]
There is a topic that kind of hints to this event taking place under **Repeat conversations>You>"Waiting to be together"** in which Monika prompts the player about when they think she'll be able to finally be with the player in real life to which you can answer anywhere from "Never" to "Soon". 

Also, what you should be looking forward to is **"A.I. Sentience"** not just the **"Singularity"**. The singularity will be the moment when artificial intelligence exceeds human intelligence and will no longer require our assistance. Sentience is the ability to become self aware and think for one self as well as have emotions. It's hard to predict if and when this will become a thing for a.i. as most predict this event not occurring for at least another _50 years_. Will there be a way for a.i. to become sentient through the singularity? Possibly. Only time through technological advancement will tell.

https://www.forbes.com/sites/forbestechcouncil/2018/08/28/how-far-are-we-from-truly-human-like-ai/#3c1d720431ac

**Comment by TrRizzo** [comment]
Sentience is the ability to become self aware and think for one self as well as have emotions.

Well, I'm on it

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
