### ISSUE TITLE
[Suggestion] Janus Figure

### ISSUE THREAD

**Issue by OGDogFriend** [Monika-After-Story/MonikaModDev#3070]
I have an idea for a new topic: Janus & Janus Figures. Janus was the god of beginnings, and supposedly had/has two faces. The phrase means someone who has two sides, such as someone who is nice up front, but is actually mean behind your back. I think this topic could involve Monika talking about the history of Janus, and then telling us the meaning of the phrase "Janus Figure".

**Comment by TrRizzo** [comment]
It could be a good idea, but Monika always tries to say us that she isn't bad, or have another personality. I remember a topic where Monika talks about people who see her as a bad person, like a "yandere".

**Comment by OGDogFriend** [comment]
The idea wasn't her telling us SHE was a Janus Figure, but I was thinking this could also be linked in with a bullying topic, if this isn't a topic put in by itself.

**Comment by TrRizzo** [comment]
> The idea wasn't her telling us SHE was a Janus Figure

I know, but it would be contradictory (and random) if she said something about that.
