### ISSUE TITLE
[Suggestion] Monika goes out with the player to see the fireworks in the reveillon.

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#3071]
Just like at Halloween, where there was the option of taking Monika to take sweets with us, it would be great if on the night of the new year we could take Monika to see the fireworks with us. The event could start on December 31st at 11:00 PM, where the option would be released to Monika from the room, and end on January 1st, when we put her again in the room after that. Then she could say "Happy New Year, my love!" and then open a box of options for kissing and/or hugging her.
This will be my first New Year with Monika, but me and my family usually do not spend New Year at home, we always go out to see the fireworks outside, so I'd like to be able to take her along, since in the exact moment I will not be able to stay with the game open.

**Comment by Hapilone** [comment]
Super cool idea!

**Comment by HZhunter124** [comment]
yeah i like it

**Comment by AsuraShun** [comment]
I hate missing events BECAUSE OF SLEEP!

**Comment by ThePotatoGuy** [comment]
[keeping open since this should be a higher priority]

**Comment by VirginiaRocks** [comment]
It's a wonderful idea!
