### ISSUE TITLE
[Bug] Table lining differs based on pose.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#3074]
So if Monika leans the table loses some of its lining and it becomes thinner and as such the table looks different dynamically.

https://imgur.com/a/L9PrTYR

**Comment by AsuraShun** [comment]
the table is exercising

**Comment by AsuraShun** [comment]
expect to see a 6 pack on it soon

**Comment by Rai99** [comment]
Must be leg day for the table with an unhealthily healthy dose of planking.

**Comment by PiperPC** [comment]
You wood make that joke wooden you...
Welp I guess I shouldn't have expected anything else.

**Comment by Olliesama** [comment]
Wood you guys cut that out, you're barking up the wrong tree.

**Comment by MaximumRustler** [comment]
I can't beleaf that this issue wood be the root of so many puns. lol

**Comment by PiperPC** [comment]
What do you mean? This is a Tree-t, absolutely Tree-mendous.
But you guys should Axe yourselves, can you keep up with my Sharp puns?
By that I mean, of course, do you think you can make the Cut?
Let's see who shall be Tree-umphant.
I guaran-Tree it'll be me though, Oak-ay?

(I am perfectly fine with making this a pun war.)

**Comment by Legendkiller21** [comment]
> (I am perfectly fine with making this a pun **war**.)

It's treeson, then.

**Comment by MaximumRustler** [comment]
Oh geez, I Wooden-'t have thought Yew Wood make these puns. It really Spruce-d up this thread. I guess I need to Branch out some more, Maple Yew could help with that... thinking up these puns are sap-ping my energy. I should Cut this short, I'm Stump-ed. lol

(Maple was really stretching it for maybe.)

**Comment by PiperPC** [comment]
Shoot.
I don't have enough puns for a good comeback lmao

**Comment by MaximumRustler** [comment]
So Yew-'re Tap-ping out? lol

**Comment by Olliesama** [comment]
Jesus I'm thinking of closing this issue, mankind has gone too far. :P

**Comment by PiperPC** [comment]
Please stop don't beat me into the ground.

**Comment by MaximumRustler** [comment]
I didn't expect the puns to go this far either, but you guys Plant-ed this idea into my head. lol

**Comment by TheGlader2** [comment]
It sounds like you guys tapped into your potential as comedians ...

**Comment by AsuraShun** [comment]
XD
this trailed off really fast
