### ISSUE TITLE
[Suggestion] Monika falls asleep

### ISSUE THREAD

**Issue by PatTraX** [Monika-After-Story/MonikaModDev#3076]
Me and my friend were talking late one night and I suddenly had an idea. I haven't done it yet but she said that if you leave MAS on for long enough she'll get bags under her eyes. However, my idea is a bit more forgiving. 

What about Monika falls asleep at random if either left on for long enough or simply at a certain time of night? Whats more is that you can wake her up and I was thinking of having four different options for this

-Say her name
-Poke her softly (maybe in a few different place (use your imagination ;3))
-Shake her
-Kiss her (again maybe on the cheek or lips, another choice here)

And so yeah. Hope you guys like it :D

**Comment by scohn** [comment]
I really like that idea, I heard that it'd take a long time before clicking her face to touch or kiss her could be implemented, but until then, I think making it a choice could be nice.

**Comment by AsuraShun** [comment]
no pervert ideas though

**Comment by HZhunter124** [comment]
cool idea, i really like this

**Comment by jmwall24** [comment]
#987 #1105 #2781
Sleep mode is a thing that has been accepted and will happen.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate] will refer to these ideas though for bedroom mode.
