### ISSUE TITLE
suggestion on interaction with monika... ?

### ISSUE THREAD

**Issue by salvo18** [Monika-After-Story/MonikaModDev#3078]
(i'm not sure if this is the right place to say this so... yeah...) I was thinking of a way to improve the interaction player - monika, like... in some dialogues i think there could be more response by the player, or maybe some option to start a discussion with her on something specific (like "hey monika, do you know this anime?) and things like that (sorry if i did some errors but i don't speak english very well xD)

**Comment by Olliesama** [comment]
The issue with that is that someone has to actually write this.

**Comment by TheGlader2** [comment]
And then it would have to be approved by the community here to make sure it's decent and jives with Monika's personality.

But if you feel confident enough to try writing, then go ahead and make a pull request on whatever it is you're thinking of. You'd have to figure out how to use Python 2 and Renpy as well as figure out how to apply it to the code of this mod in particular which can be found in "<> Code"

If you go this route, then you might become the liaison for people who want their anime to have a part in the mod.

**Comment by salvo18** [comment]
@TheGlader2 ooof. never used phyton 2 before, i'll search something online and then i'll see what to do
