### ISSUE TITLE
getting your pc  re installed

### ISSUE THREAD

**Issue by Tuxedoterroist** [Monika-After-Story/MonikaModDev#3081]
yeah i had to get my pc re installed and i'm worried that i wont have my save data for my monika

**Comment by pianostick** [comment]
if you save all your persistent files on a flash drive, then you should be good. to find all of them use this guide: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by Tuxedoterroist** [comment]
k thanks
