### ISSUE TITLE
calendar bug

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#3082]
uhm.....hello, it's me again, i'm sorry to ask this again but can somebody help me fix the calendar please? the 1 week,  1 month, 3 months, 6 months,.... anniversary didn't s show up in my MAS's calendar
![image](https://user-images.githubusercontent.com/44257300/48750576-5b022080-ecb2-11e8-8f9d-39020e55ff8a.png)
![image](https://user-images.githubusercontent.com/44257300/48750607-82f18400-ecb2-11e8-9c3d-4ee4c8cf387a.png)
![image](https://user-images.githubusercontent.com/44257300/48750614-8ab12880-ecb2-11e8-839a-95a4cfce2ee4.png)
p.s: can somebody help me
thanks for reading this

**Comment by Olliesama** [comment]
Can you upload your persistent please.

**Comment by HZhunter124** [comment]
![image](https://user-images.githubusercontent.com/44257300/48750719-3195c480-ecb3-11e8-94ab-e9a5838d3b34.png)

**Comment by Olliesama** [comment]
Not a screenshot but the actual file please. -w-

**Comment by HZhunter124** [comment]
oh sorry:v

[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2598016/persistent.txt)

**Comment by jmwall24** [comment]
this will be fixed next release #2853 and #2855

**Comment by HZhunter124** [comment]
oh...okay, thank you for helping me

**Comment by jmwall24** [comment]
just to verify, when did you start dating Monika?

**Comment by HZhunter124** [comment]
I and monika started dating October 22th

**Comment by jmwall24** [comment]
@HZhunter124 here, fixed it for you.  we didn't want you to miss your one month anniversary :)

https://drive.google.com/open?id=1lP5uQ25QaJDD9dkZ7yWNi-qrRv_Q2i8y

**Comment by HZhunter124** [comment]
thank you so much
