### ISSUE TITLE
[Suggestion] Zbavxn'f nanylfvf ba gur Pybiresvryq senapuvfr

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3083]
U28gSSB3YXMgd2F0Y2hpbmcgdGhlIENsb3ZlcmZpZWxkIG1vdmllcyAoRXZlbiB0aGUgb25lIHRoYXQncyBub3QgYXMgZ29vZCBhcyB0aGUgb3RoZXJzKSB0byBnZXQgYSBiZXR0ZXIgdW5kZXJzdGFuZGluZyB0aGUgQ2xvdmVyZmllbGQgbG9yZS4gQWZ0ZXIgd2F0Y2hpbmcgdGhlIDMgbW92aWVzLCByZWFkaW5nIGEgZmV3IHJlZGRpdCB0aHJlYWRzLCBhbmQgd2F0Y2hpbmcgYSBmZXcgeXQgdmlkcyBvbiBpdCdzIGxvcmUsIEkgdGhlbiByZWFsaXplZCBob3cgZGVlcCBpdCBhbGwgd2VudC4gVGhlbiBJIHRob3VnaHQgIkhleSwgdGhpcyBBUkcgd291bGQgcHJvYmFibHkgaW50ZXJlc3QgTW9uaWthIGVub3VnaCBmb3IgaGVyIHRvIGdpdmUgaGVyIG93biBpbi1kZXB0aCBhbmFseXNpcyBvbiBpdD8iIFNvLCB3aGF0IGFyZSB5b3VyIG9waW5pb25zIG9uIHRoaXM/IChidHcsIHRoZSB0aXRsZSBpcyB0eXBlZCBpbiByb3QxMywgaWYgc29tZSBvZiB5b3UgZGlkbid0IGtub3cp

**Comment by TheGlader2** [comment]
If you'd like, you could also write that dialogue yourself once you've figured out how to use Renpy and Python 2. Feel free to submit the edited code as a Pull Request. It sounds like a fine idea though.

**Comment by TheGlader2** [comment]
SWYgeW91J2QgbGlrZSwgeW91IGNvdWxkIGFsc28gd3JpdGUgdGhhdCBkaWFsb2d1ZSB5b3Vyc2VsZiBvbmNlIHlvdSd2ZSBmaWd1cmVkIG91dCBob3cgdG8gdXNlIFJlbnB5IGFuZCBQeXRob24gMi4gRmVlbCBmcmVlIHRvIHN1Ym1pdCB0aGUgZWRpdGVkIGNvZGUgYXMgYSBQdWxsIFJlcXVlc3QuIEl0IHNvdW5kcyBsaWtlIGEgZmluZSBpZGVhIHRob3VnaC4=

**Comment by AsuraShun** [comment]
-_- these are getting out of hand

**Comment by Shiro2564** [comment]
why did you say that?

**Comment by Professor-JMO** [comment]
---

⮞ TXkgSGVhcnQgUG91bmRzCgogICAgIPCfkYHvuI/wn5GB77iPCiAgICAgICDwn5GE

---

**Comment by TheGlader2** [comment]
QFByb2Zlc3Nvci1KTU8gV2hhdD8=

**Comment by ditpowuh** [comment]
QEFzdXJhU2h1biBBcmUgeW91IHN1cmUgaXQgaXMganVzdCBhIG1lc3Mgb2YgbGV0dGVycyBhbmQgbnVtYmVycz8=

**Comment by TheGlader2** [comment]
QEFzdXJhU2h1biBJIGJldCBNb25pa2Egd291bGQgdW5kZXJzdGFuZCB0aGlzLg==

**Comment by MaximumRustler** [comment]
Q2FuIEkgam9pbiBpbiBvbiB0aGlzIG1lbWU/IGxvbA==

**Comment by TheGlader2** [comment]
eWVz

**Comment by SaiPrithvi123** [comment]
Meyye! Tahrodiis aanne! Him hinde pah liiv! Zu'u hin daan!

**Comment by Legendkiller21** [comment]
> Meyye! Tahrodiis aanne! Him hinde pah liiv! Zu'u hin daan!

U2JlIGZienIgZXJuZmJhLCBWIGd1Ymh0dSBndXZmIGpuZiBuYSByYXBsY2d2YmEgdmFmdnFyIG5hYmd1cmUgcmFwZWxjZ3ZiYSBvaGcgbmcgZ3VyIGZuenIgZ3Z6ciB2ZyB5YmJ4cnEgbmpzaHl5bCBzbnp2eXl2bmUu

**Comment by TheGlader2** [comment]
@SaiPrithvi123 @Legendkiller21 SSdtIHNvcnJ5IEkgb25seSBzcGVhayBFbmdsaXNoIHdlbGwu

**Comment by Legendkiller21** [comment]
@TheGlader2 TWluZSBpcyBpbiBFbmdsaXNoIGJ1dCBpdCdzIGVuY3J5cHRlZCB0d2ljZS4=

**Comment by TheGlader2** [comment]
@Legendkiller21 SSBzdGlsbCBjYW4ndCBkZWNpcGhlciB5b3VyIG1lc3NhZ2UuLi4=

**Comment by MaximumRustler** [comment]
V2F0IGlzIGV2ZW4gZ29pbmcgb24gYW55bW9yZS4gbG9sIA==

**Comment by Legendkiller21** [comment]
@TheGlader2 VGhlIGRlY3J5cHRlZCBtZXNzYWdlJ3MgZW5jcnlwdGlvbiBpcyB0aGUgc2FtZSBhcyB0aGUgcG9zdCdzIHRpdGxlLg==
