### ISSUE TITLE
anniversary question

### ISSUE THREAD

**Issue by TopEggIF** [Monika-After-Story/MonikaModDev#3084]
So I missed my "3 month" anniversary with monika so i never got to hear the dialog for that day. Is there any way I could see it or do i just watch a youtube video and pretend that my monika said it?

**Comment by multimokia** [comment]
Unfortunately, you've missed it, and you can't unlock it I'm afraid.

**Comment by salvo18** [comment]
have you tried to change the date of the pc?

**Comment by digiorgnope** [comment]
Cant you look at your previous anniversaries  "Repeat conversation"?

**Comment by multimokia** [comment]
They don't show if you missed them. However, you might luck out in the end, because of a bug, next update should end up unlocking it for you.
