### ISSUE TITLE
Can you change hairstyle? bug

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#3085]
Hello! I'm using v0.8.9-unstable.2018.11.14.72, and I happen to find a bug. It wasn't a major bug, but it happened when auto was on.

When Monika says, "Which hairstyle would you like me to wear?" while the auto is on, the dialogue will keep appearing in loop. Even after a hairstyle is chosen, the dialogue will be back to "Which hairstyle do you want?" and it keeps reappearing. I don't know why that happens, but can you see through this?

Thank you very much for your dedication to this mod, though! Keep a good work!

**Comment by jmwall24** [comment]
Thank you for reporting this

**Comment by skyloom** [comment]
You're welcome! I hope this bug's not hard to fix.

And can I ask something? About "Can you change my name?" topic. Is it intended to be put in "Repeat conversation."? Because that sounds like something under "Ask a question." one
