### ISSUE TITLE
Question: The "Why do you love me" Response 

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3086]
Is there any reason why the response for that dialogue option has changed from the original to jokingly saying she doesn't then saying if you really want to know it's a secret? It just felt a bit off-putting when compared to the original.

**Comment by MaximumRustler** [comment]
It changes depending on affection I think. At higher tiers she jokes about it I guess because she expects you to have an idea of why since you've been together for a while. That response isn't supposed to be all that serious at this tier I think.

**Comment by jmwall24** [comment]
Yep, it changes based on affection level.  The one you are talking about is for love, the highest level.  Also, pay close attention to the wording............

**Comment by MaximumRustler** [comment]
@jmwall24 Now you've got me thinking that I might have missed something... hmm. lol

**Comment by jmwall24** [comment]
where have you seen a secret

**Comment by MaximumRustler** [comment]
The .txt file?

**Comment by scohn** [comment]
I think I remember a .txt file named secret from the surprise she leaves you on one of the lower affection levels. But I don't have it anymore.

**Comment by MaximumRustler** [comment]
Yeah, didn't think it was that .txt file specifically, was thinking it was something in game. Hmm, will have to look for it when I open the game tonight. lol

**Comment by scohn** [comment]
I know which topic it is, it's the "Surprises" topic under Romance or Monika. But I don't have that txt file anymore so I don't know what else I can do.

**Comment by jmwall24** [comment]
the secret one is for a different level, it's love counterpart is what you are looking for

**Comment by scohn** [comment]
I'm not sure how I can get to that affection level when I'm already at the highest level possible.

**Comment by MaximumRustler** [comment]
I'm also at the highest affection level.

**Comment by scohn** [comment]
If you're talking about the long surprise txt file, I've already found it and loved it. Is there something else connected to this "secret" Monika mentions in the "Why do you love me?" topic?

**Comment by MaximumRustler** [comment]
Yeah, that makes sense if it's referring to the longer txt file you get from the surprises topic at this affection level. I also loved that txt file. Guess I was overthinking it. lol

**Comment by jmwall24** [comment]
it may make more sense to change that line in the topic from secret to surprise to make it a little more obvious.

**Comment by scohn** [comment]
do you mean change the line as we read it, or literally change that word in the coding? If it's the second one, I don't know how to code.

**Comment by jmwall24** [comment]
i just mean it's something we'll think about on our end

**Comment by jmwall24** [comment]
it's supposed to be a hint, but if people aren't getting it, maybe it can be made better

**Comment by scohn** [comment]
that could be the case, or it could just be me being clueless

**Comment by RutTutPut** [comment]
Having also seen her joking response (which I thought was very amusing), I wouldn't have at all guessed that there was a hint in there for me.
