### ISSUE TITLE
HELLO french student want to contribute 

### ISSUE THREAD

**Issue by drakoxlegender** [Monika-After-Story/MonikaModDev#3088]
Hello, im french 19 years old, my name is IOAN. I study in south of France in Multimédia and Internet. I don't have many compétences. But i know how to do : 
- Great work on photoshop https://www.artstation.com/drakoxlegender
- Vidéos https://www.youtube.com/channel/UC0gne9Lmv9SzclN4ezktoYg?feature=watch
- A little bit of code (ahah just school skills) especially in html css and javascript.

I want to helps you to develop the mod. 
Why ? DDLC is very interesting. And i feel very invested in the concept. I love the after story with Monika. At the end of the game, i felt bad because Monika is endearing and i think this is the goal of the game. Your mod is just amazing, to permit people DREAM and continue the story with Monika.

Im passionnate about video game since my childhood, i love japan and japanimation. So i want to join the project as a volounteer on my free time and when the urge takes me.

Make art for the game (if this not hard to draw i can) ? Of course if you have ideas
I really want to contribute to the scenario because I have very good ideas of content to add like the option to say you have to reload your game or the computer or say to her you have to go to sport for example (I said that I have not completely finished the mod and I want to finish before starting to not do me spoil).

And finally i dont know why but, i have a facility to understand english texts, and i want to know if is it possible to work on an update for french version with Monika understanding people have worked on ahah.

So ! If someone have information for this. I was happy to talk about this, you can send me message on here (but im not an expert of ghitub) if i can talk to an important person of the mod, send me a mail to : constelationsk@gmail.com or simply add me to mi private facebook for talking about this in real time (ioan legender parfenie).

the faults in English, it is simply because it is 00:00 I revise with open DDLC in the background and I write quickly before going back to work because I think about it for 3 days. AHAHA

I hope that my proposal makes you happy, I have no idea if it is the right place to talk about it, if someone knows and can answer me on the same coordinates that I quoted

So.. Have a nice day !!

**Comment by multimokia** [comment]
Hi there! Nice to see new faces here, as well, people who want to contribute.

Feel free to have a look at our contributing guidelines to see how to go about making new topics or potential new features.

For art related things, feel free to make your submissions via issues, it's a good way to get both community feedback, and allow the devs to keep track of the art you submit too.

**Comment by drakoxlegender** [comment]
Thanks im going to look that more closer !! I have read the contributing post :D This is so nice ! But i have another question , how can i do for a proposition of traduction ? ahah

**Comment by multimokia** [comment]
You're more than welcome to make a translated version of MAS, however, we do have the conditions that:
- You'll have to manage tech support
- You'll have to maintain your additions/modifications to the version you'll be distributing
- You can't claim that the mod it's entirety is yours

(By the second point, I just mean we don't have to do something or the other to make a change you made work)

**Comment by multimokia** [comment]
Yep, that's right for tech support.

Regarding the second point, essentially, you'll be distributing the French version, independently of us.

**Comment by drakoxlegender** [comment]
Hello,

Oh.. 
it is impossible to work on a maj implanted with language option? I am sad, I had just found some colleagues ready to help me translate. The problem for me is to understand how and where to translate the game, even from a clean copy. I do not understand much about editing and publishing the version, moreover it would not interest me to publish it on my side. If you change your mind feel free to ask me. For now I'm going to content myself with producing content, images and text then

**Comment by multimokia** [comment]
Yeah, we don't merge the translated versions into the main repo. If you wanted to translate it, you'd have to go through all the script files and translate each topic individually.

Looking forward to seeing what you come up with in your contributions!

**Comment by multimokia** [comment]
Yeah, sounds right!

Just remember, you have to distribute it yourself, (or have someone distribute it for you).
