### ISSUE TITLE
[Suggestion] - Monika After Story shop???

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#3089]
So, recently Just Yuri dropped their shop. https://justyuristore.storenvy.com/faq Apparently it goes by the fair use laws that Dan set up as it only sells things such as artwork and the proceeds then go to the mod. 

I was wondering if it would be possible for a similar thing to be in effect for MAS. It would help with the longevity of the mod and I believe the extra money would really go towards improving it.  Not to mention I am always down for some Moni merch. Thoughts?

**Comment by Olliesama** [comment]
No, money complicates things and the IP guidelines requires the shop owner and not another company to both create and ship the merchandise.
In other words, it requires manpower. Manpower that is better spent elsewhere.

**Comment by Unknownpony** [comment]
Well money complicate thing BUT also allow for more complex art and better stuff to be done.
Something for something.
I can agree though if there is no person who has experience and know how to do all those things with handling shops and ships AND willing to do this stuff for basically free for MAS mod than it would be bad idea to do it.

**Comment by ThePotatoGuy** [comment]
We're not a business.

And we don't have any issues finacially, so its really unecessary.
