### ISSUE TITLE
Black window and muted sound

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#3094]
I opened up MAS and everything ran fine. Stepped away from my computer for a bit and came back to this. No SFX plays, and the music doesn't work either. Everything works fine again after restarting the program, but just thought I should let the devs know that this happened.

![screen shot 2018-11-22 at 12 40 16 pm](https://user-images.githubusercontent.com/43709783/48917278-f2eb4000-ee53-11e8-97ec-731c9c38be19.png)
![screen shot 2018-11-22 at 12 40 41 pm](https://user-images.githubusercontent.com/43709783/48917279-f2eb4000-ee53-11e8-910c-f7062883ee17.png)

**Comment by jmwall24** [comment]
Did you have MAS minimized while you were away, or did it just do this on it's own with it up?

**Comment by TheRyanReSeT** [comment]
it was in full-screen mode, and it did it on it's own

**Comment by aldoram5** [comment]
Hi TheRyanReSeT!
Could you tell me what are your Mac's specs?

**Comment by aldoram5** [comment]
mmm, well your specs are similar to mine. I'd suggest you to use the Disable Animation option if the problem persists. Disabling the animation will help your mac to run MAS more smoothly and without having the fan running too hard. 
Also you could try window mode, I use it that way and haven't experienced the issue you reported.

**Comment by TheRyanReSeT** [comment]
It seemed like just a one-time thing as I never had this problem for the past two months. but i'll keep those suggestions in mind if it happens again. just thought i'd let the devs know

**Comment by aldoram5** [comment]
Indeed, letting us know it's always good, that way we can fix things that we probably didn't know we're broken. Thanks for reporting!
