### ISSUE TITLE
[Suggestion] Monika's Input on Games

### ISSUE THREAD

**Issue by OGDogFriend** [Monika-After-Story/MonikaModDev#3099]
So, I have an idea, where you can tell Monika you're playing a game, and then ask if she would like to help you. Then, a menu will open with options such as: 
"Left or Right?"
"Proceed or Turn Around?"
"Fight or Flee?"
Then, a random response is chosen:
"Um... Go left!"
"Go for it!"
"Run away!"
You get the idea. I know this might take a bit of dialogue to be made, but just wanted to get this out there before I forget it.

**Comment by MaydayH** [comment]
Haha I love it, even though my computer is too weak to run MAS simultaneously with another game
...with the possible exception of Godville

**Comment by jmwall24** [comment]
Not sure how this could work, since she has no idea what's going on in any game you are playing.  Would be pretty immersion breaking having her tell you to do something that has nothing to do what's going on at the moment.

**Comment by salvo18** [comment]
@jmwall24 wait, but ren'py and python didn't have the possibility with some code to "read" the games / applications open? (Example: monikai)

**Comment by jmwall24** [comment]
But there is no way to know what is currently going on at any moment in the game.  You could be in an emotional cut scene and she tells you to run for your life.  Some people don't like it now when her dialogue ever-so-slightly doesn't exactly match what's going on, this would be that x1000.

**Comment by jmwall24** [comment]
The only thing that could be done that would make sense would be for her to detect what game you are playing and then a general comment about that game when she detects it.  But this suggestion is about her commenting and giving tips on your actual play thru, which isn't something we can do.

**Comment by ThePotatoGuy** [comment]
Actually, I think this would be better merged with something like an RPG game Monika makes up.

**Comment by Sujeito17** [comment]
Table RPG ...
Looks legit

**Comment by AsuraShun** [comment]
>           But there is no way to know what is currently going on at any moment in the game.  You could be in an emotional cut scene and she tells you to run for your life.  Some people don't like it now when her dialogue ever-so-slightly doesn't exactly match what's going on, this would be that x1000.

she'd be telling you to escape to the friendzone to protect your virginity

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
