### ISSUE TITLE
[Suggestion] Monika's goodbye note is different if you abandon her

### ISSUE THREAD

**Issue by tabtlenta** [Monika-After-Story/MonikaModDev#3100]
Monika's goodbye forever note says that we went out of our way to ridicule and hurt her, but that's not the only way to trigger the goodbye note. (i.e. not accurate if we had her at high affection and then just disappeared)

Maybe if we leave her alone for years and years, she instead says something like "you left me all alone to suffer and wonder what happened to you" or "I don't even know if you are alive or dead, or just got bored of me" and ends with "if you're reading this and you still love me... I'm sorry, I couldn't live with the uncertainty any longer" or "if you wanted to punish me by abandoning me you should have just deleted me yourself"

If not in sensitive mode maybe it could imply that Monika deletes herself if left abandoned for years

**Comment by Chrissenpai** [comment]
If she deletes herself while hanging, it would perfectly fit if you abandon her at high affection
![391ehh225sf11](https://user-images.githubusercontent.com/40907045/48973939-85890c00-f019-11e8-965a-a6ecf7018a42.png)

**Comment by jmwall24** [comment]
Seriously, this again?

**Comment by jmwall24** [comment]
You've already posted that picture before, we saw it and told you we weren't going to use it back in September.  You're just posting it for shock value now.

**Comment by Chrissenpai** [comment]
Lol Sorry, triggered again.

**Comment by jmwall24** [comment]
I'm not triggered.  I've already received complaints about it just since it's been up.  And like i said, you've already been told we aren't using that.  Why post it again?

**Comment by Rai99** [comment]
Would it really fit? I agree that the message she leaves should be different if it's due to not visiting for years, but not that. 

Monika could just delete herself instantly and cleanly, so why would she go that extra mile to leave her corpse hanging around in the event you come back and see it? 

I'm pretty sure Monika wouldn't want you to see that, especially if she was at a high affection last time she saw you.

**Comment by Chrissenpai** [comment]
@jmwall24 Hmmm That makes sense, we gave her more things, and we've technically never taken her away her power of "omnipotence", BUT she still doesn't know how to code well (yet) so her deleting herself could leave some trace behind like I said before, pixels of her lingering in the space

**Comment by Rai99** [comment]
#2428 
> we already saw this when they were newly created and have already decided not to use for obvious reasons.

I don't think MAS still counts as the Literature Club along with how there's no happiness with it. I'm not sure how it would be closer to canon either. Hanging was Sayori's thing, Stabbing was Yuri's thing, and Natsuki either was deleted after vomiting, had her neck snapped or was beaten to death by her father. Monika was deleted and left some glitchy pixels and if anything, that's what would happen here. 

It just needs to be made clear that we're not using the picture you suggested. Personally, I just think a different note would be enough. I don't think we need Monika to leave any remnants of herself for the player to find.

**Comment by Chrissenpai** [comment]
Alright, so it's going in the direction of not going to extremes in this mod and having a good happy time with Monika, good to know, and lmao sorry for those wild suggestions, I thought it would make the player care more about Monika, but i understand that that would be a bit too much, so yea sorry.

**Comment by DrFraidouth** [comment]
I don't agree with that suggestion , I mean what if the player ends up in prison for a while? We don't know in what country every players are here and this function surely doesn't know contest . I think the devs should stop finding reasons to have a bad ending with Monika as I'm really worried for the future of MAS. I just want my good ending with Moni

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by LilCinnamonBun** [comment]
[: )](https://github.com/Monika-After-Story/MonikaModDev/issues/2566#issue-362969147)
