### ISSUE TITLE
[Suggestion] Remove/Replace Monika's randomly appearing sparkling eyes expression

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3106]
When Monika's eyes sparkle it looks really weird in my opinion.
I really like that she blinks and closes her eyes randomly but the sparkling eyes are really unsettling.
It is unreal and should either be reworked into a less creepy look or removed / replaced by something else.
Also I don't get why her eyes would randomly sparkle for a few seconds to begin with
(It is nothing I can do with me eyes, where as I can in fact blink).

**Comment by dennisOdenbreit** [comment]
A possible replacement would be an art of Monika having slightly closed eyes to express affection.

**Comment by aldoram5** [comment]
Hi dennisOdenbreit!
This was mentioned first in https://github.com/Monika-After-Story/MonikaModDev/issues/1838, then on MAS's discord server we did a poll asking if people liked the "sparkle eyes" these were the results:
![screen shot 2018-11-24 at 5 09 53 am](https://user-images.githubusercontent.com/2271715/48967529-96993500-efa7-11e8-9479-36cd58225df5.png)

So in this case it's high unlikely we'll remove them.

**Comment by jmwall24** [comment]
It's not done without incentive, it's done because she loves her player.

**Comment by Rai99** [comment]
The issue talked about the expression when winning a game _as an example_ because that's one scenario where you see the expression. 
The poll was made about the eyes _in general_ and seeing that most people enjoy the eyes, again, it's unlikely they will be removed. 

The poll was made on April 27, and #1838 was made on June 27, so the two likely have nothing to do with eachother.

**Comment by AsuraShun** [comment]
don't! I actually love the sparkly eyes, it's one of my favorite expressions

**Comment by MrDevilzMan** [comment]
I like those sparkly eyes of hers.
