### ISSUE TITLE
[Suggestion] Refine Monika's out of dialog response

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3109]
In the case Monika has nothing to say at all (because all of her new dialog is used up) she could respond differently from her usual "I hoped you liked what I had to talk about today" responses.
It is kind of weird to hear a line like that from her if she hasn't said anything yet (on her own).
She could have a line like "I am still at a loss of words. I hope you don't mind, player".
To do this there could be a counter every time she says something by herself.
If the "I hoped you liked what I had to talk about today" dialog is triggered and the counter is still at 0, she could use the other line(s) instead.

**Comment by ThePotatoGuy** [comment]
[closing as this is no longer in progress]
