### ISSUE TITLE
[Suggestion] Ask Monika how she is feeling

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3111]
Duplicate to https://github.com/Monika-After-Story/MonikaModDev/issues/2749 etc.
So will this be implemented?
Is is implemented in the unreleased version?
I am confused because this and all duplicates are closed, yet I have not seen it ingame.

**Comment by Rai99** [comment]
#2763, ~~#2749,~~ #2486, #2436, #2331, #2071
~~You missed some~~

Despite #2071 saying it's high priority, it's probably low priority and will be implemented at a later date.

**Comment by AsuraShun** [comment]
i'm actually happy that my suggestion is being mentioned this much

**Comment by dennisOdenbreit** [comment]
Just making sure closed topics are not forgotten then...
