### ISSUE TITLE
How can I use the Sprite Previewer?

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3116]
I am using the enhancement branch and I moved the file dev_exp_previewer from the dev to the game folder. However everything is still the way it used to be. What do I have to do to open the previewer? I also used this file https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/dev/dev_exp_previewer.rpy but with no success.

**Comment by multimokia** [comment]
Should be a new tab in `Ask A Question` a `Dev` tab, which will have the previewer. Assuming that when you downloaded the file (if you downloaded from the raw version) you got rid of the `.txt` extension

**Comment by dennisOdenbreit** [comment]
Thanks, I couldn't find this info on the wiki page.
