### ISSUE TITLE
need help with a code

### ISSUE THREAD

**Issue by salvo18** [Monika-After-Story/MonikaModDev#3118]
I'm trying to do something with mas (I had an idea days ago) but searching online seems to not give me the results i was hoping for... can you tell me the code to make ren'py or python see if a process is opened?

**Comment by jmwall24** [comment]
this is where MAS detects in MonikAI is running
https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-story-events.rpy#L426

**Comment by salvo18** [comment]
@jmwall24 thanks!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
