### ISSUE TITLE
have player fill out survey in text file

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3121]
Dear [player] 

Here's a reminder of why I am mad at you, your behaviour made me angry and sad at day [#] by the [morning/evening].
therefore I hope to count on your cooperation in answering this questions
Have you arrived? [  ]
Are you alright? [  ]
Did you eat well? [  ]
Did you sleep well? [  ]
I hope you could answer those questions so I can help ease myself
since the fact that me being mad at you doesn't mean that I don't love you or that I don't care about your well being

                                                                                                                Yours truly: a still mad Monika

**Comment by ThePotatoGuy** [comment]
so something like putting a survey in a text file and having player fill it out?

interesting

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
