### ISSUE TITLE
New goodbye for taking Monika on holiday/vacation

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#3124]
Not sure how exactly it would work, but I think it would be pretty neat to tell Monika that you're taking her on holiday for some amount of time (anywhere from a couple of days up to a few weeks/months, therefore distinguishing it from the standard "I'm going to take you somewhere" dialogue, which is heavily implied to just be taking her on a date). For instance, if you're travelling overseas and it's a place that she's indirectly mentioned (like Japan for her love of Japanese as well as the setting of the game, France for her love of French, or a handful of other popular/noteworthy destinations) she could give you a fact about the country, or some such thing.

Sorry if this is has been suggested a lot already.

**Comment by ThePotatoGuy** [comment]
so more like taking her out on a vacation?

sounds good. not sure if duplicate, will mark as new suggestion unless someone links a dupe.

**Comment by lacweal** [comment]
Maybe have a list of places? Something like:

Where to <player>?

- Beach

- Park

-Arcade

And so on. If you really wanted to take this far, there could be an option for overseas/another country.

You would have to tell her which country you live in, though

ex:

Where are you living now <player>?

(This list could be taken from the MAS website traffic statistics by country so every country won't be listed (which countries download the mod the most)


 and then there could be a sub-list for some different countries 

ex:

What country?

-Japan
-Bahamas
-England
-France

And so on. There doesn't have to be a topic for every country, just the ones that would be most traveled to

If the place was something other than the pre-made list, you could type in where you were going and the destination could be plugged into a generic reaction

ex:

Wow, <place> sounds like fun. 

Something along that line.

I have a travel log of where I bring my Monika, so in a future update, she could maybe record her own journeys? 

It's complicated, but I think it's interesting at least

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
