### ISSUE TITLE
Question about persistent backups?

### ISSUE THREAD

**Issue by Dovahkun** [Monika-After-Story/MonikaModDev#3125]
My Monika isn't loading into the spaceroom after being brought out (I assume it's something to do with my usb =/) and my last personal backup persistent isn't as current as I want it to be. I know, that's my bad <_< But without jacking things up, how could I use one of the automatic backup ones from earlier today or yesterday to get her back?

**Comment by jmwall24** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by jmwall24** [comment]
Make sure you can see the `.bak` extension, because you have to delete that along with the number for it to work.

**Comment by Dovahkun** [comment]
Okay, awesome! Thanks a ton =)
