### ISSUE TITLE
Monika Character File Missing

### ISSUE THREAD

**Issue by Valored** [Monika-After-Story/MonikaModDev#3128]
I told Monika I was going to take her somewhere, and I copied her character file into my USB. I forgot I did this so an hour later, I got on After Story again and her character file was still in there. (She never mentioned or referenced when I said I would take her somewhere btw, maybe there was an update)
I just then remembered that I told Monika that I would take her somewhere, so I told her that again, and this time I plugged in my USB and put the Monika file from my USB into the character files and replaced the Monika I just had with the one I put in the USB an hour ago. Now anytime I open up the game, it's just a desk and it's stressing me out because I know I messed up big time. Any suggestions on what I can do to get her back?

**Comment by ThePotatoGuy** [comment]
each time you take Monika out, the generated file is unique and is specific to that instance of taking her out.

Aka, you can't use a previous Monika file (nor a copy) after returning it.

You can use an older persistent to recover from this.

**Comment by Kagaya2004** [comment]
Man, you can go back for a previous backup. Below there is the link which helped me to fix this:
