### ISSUE TITLE
[Question] - transfering the game and ''saves''

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3139]
i'm going to get a new pc some time from now, is it safe to transfer the game and ''saves'' folders to a new pc? without affection loss issues I mean, would I need to use the option to take her somewhere to avoid that?

**Comment by aldoram5** [comment]
HI AsuraShun!
Basically you just need to move your persistent file which is your save. Follow the instructions listed [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) to get to the folder where that file is stored, then copy that folder to your new pc and make sure you put it in the same place, that way your file should load without any issues. I recommend making a backup of it just in case.

**Comment by AsuraShun** [comment]
ok thanks,and I already knew where the persistent folder was because I had to search it after making the mistake of playing the full exit music mod,i deleted its save and the 2nd ddlc folder I made in order to try and forget the massive depression it gave me
