### ISSUE TITLE
Homogenizing the artwork

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3155]
You probably know this and it's probably low priority for you. I like very much the design of the art that this mod has (leaning pose for example), but while it try to by very close to the original art, it differ slightly (see the examples). It would be appreciated if you could homogenize the artwork.
![mas design](https://user-images.githubusercontent.com/38837456/49338601-714d9c00-f623-11e8-9449-5ecd44e25ba8.PNG)
There is also this "old" design of the school uniform:
![former design](https://user-images.githubusercontent.com/38837456/49338658-8d9e0880-f624-11e8-9852-77d8a165d3ba.PNG)
And there is the "new" design:
![new design](https://user-images.githubusercontent.com/38837456/49338663-a9091380-f624-11e8-9ef4-4b6829b9ea8d.PNG)
The shadow are less apparent, there are less folds and the red collar is more bright in the "new" version.

**Comment by Chrissenpai** [comment]
@Thimeo looks like you're a man of culture as well

**Comment by tsmafterlife** [comment]
if i am not mistaken. just the new arts that where placed into the update is what your asking to be homogenized? because i cant tell if your saying they where all changed or just the new ones for leaning? @Thimeo

**Comment by tsmafterlife** [comment]
or if your talking about just the leaning arts?

**Comment by Thimeo** [comment]
No, I mean in general. I say that the style of the art that was in the base version of DDLC is not (perfectly) similar to the art created for the mod (leaning pose as an example). I'm just saying that, for example, in the base pose of Monika (cross finger), the art of the uniform is a little different than the art of the uniform of the leaning pose, that was created for the mod. I was suggesting that the artist could take all of the sprites and design that was in the base game, and remake it to match the art style that we have today.

**Comment by tsmafterlife** [comment]
And that’s fine thanks for clearing it up. But one last thing if I may. Are you saying maybe the artist can re do the base games pictures to match up with the new ones? Other then that I get what your saying.

**Comment by Thimeo** [comment]
Yep, that's that. Just using the same colors for the old one and the new one, doing shadow the same, and so on. There is the disconnection I think between the old art that seems of bad quality (with visible pixels) and the art produced that is more smooth. This would 'just' be a remake of the ancient art (in the base game), to just "trace" the old art style (I don't know if this is the good word for that) to make it seem "more HD" and homogeneous. I don't know if I've been very clear on this one. What I'm trying to say is : "Just do minor adjustments on the old art to match them with the new ones."

**Comment by tsmafterlife** [comment]
the problem with it though is it comes down to a matter of opinions. me personally i feel if any tweaking where to be done it should be that the new arts are meant to look like the originals. to me the original arts are a base plate for Monikas model for a reason. plus it would be easier to shadow the new arts then it would to change and do such to the old arts. plus a lot of the newer art comes from her leaning poses that ive seen when digging around the files. i don't know if you thought of it before but the way she leans almost looks like shes catching the sun which would take away from the shadowing and have to make it look different. tho i do agree the lines around the should and outer parts of the body are cleaner on the new body art. but this is all an opinion of my own in no way is it right wrong or anything. just what i think about a good topic you bring up. @Thimeo

**Comment by Thimeo** [comment]
Of course it's just a matter of opinion, and you have the right to disagree with me, that's what those discussions are for after all. 
I've thought about matching the new arts to the old one, and I've figured out that the artists where already trying to match them (which they succeed for the most part but not entirely), and instead of saying: "Do it in perfect accordance with the old art for the leaning pose and for ALL of the future art that you will produce." I think (and I can be wrong) that it would be easier to say "Do the future art as you did for the previous ones, and just modify that one sprite (base pose) to match your style."
For the justifications of the shadows, I've also thought about that and I don't really buy it. Her position is not that different, and while I agree that there should be a difference in where the shadows are positioned (and I think that they mostly succeed on this point), my problem was more about the design of the shadow and the fact that the transitions between shadow and the lighted part are almost nonexistent.

There is the design of the shadow in the old art:
![old shadow](https://user-images.githubusercontent.com/38837456/49429060-e1852a80-f7a7-11e8-9bfa-b02ba5c86df3.PNG)

And there is the design of the shadow in the new art:
![new shadow](https://user-images.githubusercontent.com/38837456/49429095-f8c41800-f7a7-11e8-9464-e4b6170bac16.PNG)

And finally, I agree that there could be some work done and the outer parts of the body, those are ... not perfect, to say the least.

**Comment by tsmafterlife** [comment]
i dont disagree and you make a good point about modifying base pose so all future art can just be done in the style it is done in now vs fix the current new art and all future art to be that of the base. that is something i did not think about
