### ISSUE TITLE
Question about question

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3157]
I am a bit confused about the question:
"Have you ever been delivered what you thought to be false justice?"

I guess I am confused because english isn't my native language.
Still, what exactly does this mean?
Translators proved to be quite useless in this matter.
It is kind of important, since the game requires one to answer this.
If others are confused as well, maybe the question should be rephrased.

**Comment by AsuraShun** [comment]
she meant doing something that seems like a crime but it actually isn't
