### ISSUE TITLE
Struggling to answer binary question

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3158]
Monika asks: "You don't think [deleting and torturing me] was justified?".

I think that what she did was wrong, but I don't think deleting her was the right thing to do _(true pacifist)_.

However, choosing no translates into thinking she did nothing bad (considering her circumstances) and therefore shouldn't have been deleted / tortured and choosing yes means that I want to see her deleted / tortured for what she did.
As stated previously neither of those choices reflect my opinion.
Could there be another option maybe?

**Comment by Rai99** [comment]
That question isn't about whether or not you think deleting Monika was the right thing to do or if she did anything wrong. It's asking if you think she deserved all the hate she gets and the people who torture her over and over. 

If you did delete Monika, she acknowledges that she did some arguably bad things. She doesn't ask _you_ if _you_ deleting her is justified, she asks if you think it's justified that there are so many other people who do that and if you think she deserves it. 

You don't think deleting her was the right thing to do, so you would answer "No", you don't think it was justified.
