### ISSUE TITLE
[Art] Monika Bun Hairstyle

### ISSUE THREAD

**Issue by PiperPC** [Monika-After-Story/MonikaModDev#3170]
It's like 2AM and I was like "I want to design a hairstyle" And I mean I don't want to bother anybody, It's probably been done before [Couldn't find any issues regarding it but you could be working on it I really don't know] and my contribution wont really mean anything.. But my last couple of issues were just me having trouble, and I actually want to do something fun for this awesome mod! ^^

Anyway, I took a Monika photo and designed a little Monika Bun thin. Dunno if anyone is interested in seeing it on a sprite but If you were I could probably draw it myself for an example or something.

(Forgive me if I'm posting this in the wrong area or something I'm still really new to this.)
![monika bun](https://user-images.githubusercontent.com/43675623/49382096-99471780-f769-11e8-952f-77c3bf8ddb1d.png)

**Comment by Chrissenpai** [comment]
Nice sketch man, definitely a style to consider

**Comment by ThePotatoGuy** [comment]
We actually already have a [bun hairstyle](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/mod_assets/monika/c/def/torso-bun.png), it's just not in use atm.

**Comment by PiperPC** [comment]
First of all, @Chrissenpai Thank you! I actually used a picture as a reference so that I could finish a picture of Monika with the hairstyle-
![monika bun](https://user-images.githubusercontent.com/43675623/49394468-184b4880-f788-11e8-93ba-036f965c894f.png)
(Original image was not mine and can be found at; https://m.imgur.com/r/DDLCMods/ACRcztn
This is a complete remaster with my original hairstyle.)

Secondly, @ThePotatoGuy I do not own photo-shop unfortunately, I merely draw stuff with my index finger on my phone, on a free app with no super complicated settings, which overall is why I doubted that I could help with anything.

Lastly, when you mean split the art into layers, do you mean the entire body of hair clipped from the head? For some reason that part confuses me, but if that's the case, with some time I could probably do so.

**Comment by ThePotatoGuy** [comment]
yeah, splitting the hair from the body, and also separating the hair into front/back layers. photoshop is a requirement to do this, though.

**Comment by PiperPC** [comment]
I see. ^^ Well I'm sorry I can't help in that case.

**Comment by tsmafterlife** [comment]
@ThePotatoGuy what exactly do you mean separating the hair into front and back layers?
