### ISSUE TITLE
[Sugestion] unlock wardrobe at random days

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3171]
We have yet to unlock one or two costumes right? if it can't be shown because we weren't on that special day, and if the next special day is too far away or it won't arrive, we need to put a random day in the system so that the outfit is introduced and unlocked, how about that?

**Comment by multimokia** [comment]
I don't think it entirely makes sense. Under what context would Monika just pull out and wear one of the Halloween costumes on a normal day?

**Comment by Chrissenpai** [comment]
Um, because of unexpected surprise?

**Comment by AsuraShun** [comment]
since she has only those 3 clothes, it'd make sense for her to change into those, unless someone talented enough is willing to draw her more clothes for her to change into

**Comment by Chrissenpai** [comment]
Still saving for a graphics tablet...  then I'll be the main artist of MAS if possible :)
