### ISSUE TITLE
I'm curious 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3173]
I know that her birthday is over, but one thing still concerns me. The last thing I gave her was knife, but she got angry and threw it away. And then I realized : Before that I gave her a cake, so how did she cut it without knife? Or she just swallowed it whole? Did she even eat it? 
These thoughts are bothering me for two months.

**Comment by Sujeito17** [comment]
Monika is a ninja she can cut cakes with the hands (the cake must been rotten already, poor cake why I give it to Monika? ;-; What a bad destiny, if it were I the cake doesn't will have that terrible destiny )
(Monika needs to have more respect with cakes). (¬_¬)

**Comment by Foxinsunglasses** [comment]
She is pretty much a god in that room so maybe she just absorbed it?

**Comment by Rai99** [comment]
~~Was that cake named Yuri?~~

**Comment by Sujeito17** [comment]
̶E̶v̶e̶n̶ ̶i̶f̶ ̶t̶h̶e̶ ̶c̶a̶k̶e̶ ̶w̶a̶s̶ ̶c̶a̶l̶l̶e̶d̶ ̶Y̶u̶r̶i̶,̶ ̶i̶t̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶e̶a̶t̶e̶n̶,̶ ̶t̶h̶e̶r̶e̶ ̶a̶r̶e̶ ̶n̶o̶ ̶e̶x̶c̶u̶s̶e̶s̶ ̶f̶o̶r̶ ̶w̶h̶a̶t̶ ̶M̶o̶n̶i̶k̶a̶ ̶d̶i̶d̶
(¬_¬)

**Comment by Rai99** [comment]
Consuming up Yuri probably isn't in the best interest of most people, especially on Monika's birthday. It's a small thing, but it might be more appealing to consume a cake named Monika. 

She said she was going to save it for later and so she put it away. 
These were the cake's final moments:

m 6eua "I'll save this cake for later."
$ mas_docking_station.destroyPackage("cake")

**Comment by Sujeito17** [comment]
No matter what is the name of the cake, the cake should be eaten.
Maybe she frozen the cake. ¯\_(ツ)_/¯
