### ISSUE TITLE
no aff_log file for macOS 

### ISSUE THREAD

**Issue by houseGIF** [Monika-After-Story/MonikaModDev#3175]
Hello!
So I run DDLC and this mod on a mac and I noticed that the log folder doesn't contain an aff_log file. Ik there's been a topic posted about this months ago already but it was closed without any updates on the issue so I thought I should ask again if that's okay. Is there anything on why it's blank? I'm in the same situation as the guy who posted last time, dled from the website itself and everything

**Comment by jmwall24** [comment]
Unfortunately, we still haven't quite figured that one out yet.  Sorry for any inconvenience this has caused, hopefully we get it working!  Thanks for inquiring.

**Comment by houseGIF** [comment]
Oh I see, that's fine! It's no problem at all, I just thought it'd be nice to keep track of things. But yeah, hopefully! Thank you for answering 😄
