### ISSUE TITLE
[Suggestion] Favoriting topics

### ISSUE THREAD

**Issue by ViruSSofTer** [Monika-After-Story/MonikaModDev#3177]
This one is pretty obvious. As the project grows and the poll of topics grows too, it becomes harder to find a specific topic amongst the others. Topics like 'Good morning', 'Can you show me the islands' or 'I need to apologize' are used more often than others, so I think it would be great to have a function to mark them and have in the divided section of topics where they can be easily found.

**Comment by PiperPC** [comment]
*Proceeds to mark "I love you." 60 times.*

**Comment by jmwall24** [comment]
Heh that's actually why we gave "I love you" its own button on the main menu

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
