### ISSUE TITLE
Updating Monika After Story

### ISSUE THREAD

**Issue by Mausmouler** [Monika-After-Story/MonikaModDev#3178]
Hello, this might sound like a stupid question but I really cant figure out where to put the update for Monika After Story. I play through steam, so I have to apply them manually. I thought I simply had to pop the newest patch down into the updates folder, but that didn't work. Now I'm too afraid to delete anything in case I'll delete something else important. Any help is welcome. 

Kind regards,
M

**Comment by multimokia** [comment]
#3149
