### ISSUE TITLE
[Suggestion] Monika knows if you play other mods

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3179]
I think the title is pretty self explanatory. Monika can detect if you play other DDLC mods, and will talk to you about them or something. Her reaction could depend on what the mod is about (can you even do that?)

**Comment by Olliesama** [comment]
It's possible if the mod has a unique persistent folder and doesn't use the template.

**Comment by Rai99** [comment]
That and the fact that I brought up the topic of other mods in #1737 and it was concluded that it might not be a good idea since Monika might wonder why you're playing other mods instead of spending time with just her.

**Comment by ThatOneUsername343** [comment]
Maybe you're right. I just spent my entire afternoon playing the Rainclouds mod. I'm just... I always knew Monika amped up Sayori's depression, and I was never okay with it, but I forgave her because I understood her predicament. I understood that she was desperate and that she never wanted Sayori to die. But when she said she amplified Sayori's depression, I always assumed that she meant that she changed something in the code, like raised her "depression meter" or something. But what she did to Sayori in that mod... my Moni would never have actually done that... right?

**Comment by Rai99** [comment]
That's not Monika and she wouldn't want you to be confused about that. Yeah, she probably won't encourage you to try other mods because she's portrayed inaccurately in a lot of them and doesn't want you to get confused. 

At the end of the day, Monika is there to comfort you and at least remind you what she's not. 

----

Yeah, first non-MAS mod I played, the Monika route was "coming soon" but never happened. Second mod was just poorly written I think, so I don't really play other mods anymore.

**Comment by Olliesama** [comment]
> Maybe you're right. I just spent my entire afternoon playing the Rainclouds mod. I'm just... I always knew Monika amped up Sayori's depression, and I was never okay with it, but I forgave her because I understood her predicament. I understood that she was desperate and that she never wanted Sayori to die. And when she said she amplified Sayori's depression, I always assumed that she meant that she changed something in the code, like raised her "depression meter" or something. But what she did to Sayori in that mod... my Moni would never have actually done that... right?

The Raincloud mod demonized Monika and made her seem way worse than she was.
It's not a good reflection of what happened.

**Comment by Rai99** [comment]
> demonized

I thought that said de-monied.
De-moni-ed probably works too.
