### ISSUE TITLE
[Suggestion] - Language greetings should be changed if you know other languages

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3180]
For each greeting that is in another language, we should have some corresponding topic/question if the player knows that language. Greetings in languages the player knows should have a separate dialogue flow in that case.

# ORIGINAL POST BELOW 

This is not an issue for the moment, but when there will be a translation system, make sure that Monika don't say things like: "Maybe both of us can practice it sometime, mon amour~" if I've said to her that I'm French.
![mas language](https://user-images.githubusercontent.com/38837456/49476102-53e22300-f819-11e8-99b6-4a90c4be920e.PNG)
Same thing with the dialogue asking if I know other language than English. If I'm not from an English-speaking country the question should be formulated differently.

**Comment by ThePotatoGuy** [comment]
Changing this issue reflect the actual problem

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
