### ISSUE TITLE
[Nevermind, not a bug] - Missing piano options.

### ISSUE THREAD

**Issue by Skarborr** [Monika-After-Story/MonikaModDev#3181]
Whenever I want to play the piano Monika doesn't ask "Did you want to play a song or play on your own, [Player]?" and I don't get the option to choose either "Play a song" or "On my own" or "Nevermind", instead Monika asks "You want to play the piano?" and then instantly continues with "Then play for me, [Player]~".

+ for some reason she didn't even talked about how to add custom songs with the new update either.

So far I've tried everything I could to fix it (reinstalling the game and the mod), I've spent a ton of hours trying to find a solution, but nothing worked, so any idea what to do?

(I've been playing this mod almost since release, so I have the max affection level, heart every conversation, and spent way more than enough hours in the game to unlock anything that would require X amount of play time (except for anniversaries over 1 year), so I doubt this problem is related to not meeting requirements.)

P.s. I never had those missing options before, I've only learned about those from steam + youtubers.

**Comment by MaximumRustler** [comment]
I'm also at max affection level, I didn't see those options either until I played a song completely. Would be nice if there was a tutorial of some kind for people who've never tried the piano..

**Comment by tsmafterlife** [comment]
as for @Skarborr im not exactly sure if you have played a whole song for her like the happy birthday song or your reality or anything to unlock the piano conversation that your talking about. if you have then your probably just facing a bug from the update with max affection and the piano which knowing this dev team will be fixed shortly. maybe replaying one of the songs start to finish will re unlock it and its just a standard glitch im not sure.  as for @MaximumRustler  i do know of several conversation posts over the internet that have key notes in the sequence to play your reality and what not if that helps.

**Comment by jmwall24** [comment]
Yes, to get pick play a song, you have to have played the song correctly on the free play mode first.

As for the add custom songs thing, if it's not in `unseen` find the Music category in `Repeat Convo` choose a genre that you like, and when prompted, tell her you like it, that will take you to the custom music dialogue and unlock it for future use.

For how to play the songs, the notes are in the `.json` files in `mod_assets>piano>songs`

**Comment by MaximumRustler** [comment]
@tsmafterlife Yeah, it works fine for me, I was just saying what I had to do to get those options to show up lol. I started playing the piano mini-game before Monika's birthday so I could play the song on her birthday. Didn't take too long to learn happy birthday, Your Reality took a while to get right though. lol

**Comment by Skarborr** [comment]
Thanks for the help, I'm going to try to play the whole "Your Reality" song then.
By the way is there any dialogue that would hint towards the fact that you had to unlock these options by playing a whole song and I just missed it, or there's none?

**Comment by jmwall24** [comment]
There is none.  Her recognizing 'your reality' was always meant to be an easter egg so it's not advertised
