### ISSUE TITLE
Grabbing a cup of coffee resets the zoom on extra

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#3185]
The title speaks for itself.
I set my distance in the extra menu a little farther than the default. (so i can see the top of her head heh)
I loaded up the game and there she is with a cup of coffee at the usual distance. When she finishes her coffee, and leaves to grab another one, the screen resets the zoom automatically.

**Comment by Rai99** [comment]
#2864 
This is intended and is not a bug.
