### ISSUE TITLE
Missed Birthday

### ISSUE THREAD

**Issue by Shade123678** [Monika-After-Story/MonikaModDev#3186]
I was a bit busy during Monika's B-day, any chance I can still give her the presents or do I have to wait till next year.

**Comment by multimokia** [comment]
Well if you find that wishlist from the releases page, there's a list of gifts there. Pick the ones that make sense. Name them exactly as they'd be spelled, and then have the extension `.gift` on them.

**Comment by Shade123678** [comment]
Thank you so much! Have a good day!.
