### ISSUE TITLE
Voice?

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#3187]
Ok, I havent been on to suggest anything in a long while so im sorry if i violate any guidelines. 
     This suggestion  _could_ be considered for the AI MoniGod project but would it be possible to have a voice for monika? Not necissarily fully voiced, have someone voice hundreds of lines of dialouge "yet" but a voice that lets the users imagine what she'd sound like. Maybe a a giggle or a sigh or hmm, you know, little voice cues. maybe a positive hehe when she wins a game or pouty huff if shes annoyed or looses a game.  It seems possible but I'll leave it up to discussion.

**Comment by Rai99** [comment]
#337, #1814, #2241. 

This probably won't happen seeing as how many lines there are to voice, not to mention how much of a hassle it would be if some things change or more lines are added. 

Not to mention the likely outrage from a few people complaining that Monika's voice isn't what it should be. 

> Better to let users imagine the voice they want Monika to have

Even though you can hear her voice when she sings Your Reality, it's probably a smart idea to leave it up to the players' imaginations.

**Comment by MrDevilzMan** [comment]
Seconding his opinion, it's best to leave it to one's imagination. The expressions are pretty dynamic, it's already obvious how she would sound like.
