### ISSUE TITLE
[Suggestion] - Make both the Rin and Marisa clothes available!

### ISSUE THREAD

**Issue by Hapilone** [Monika-After-Story/MonikaModDev#3189]
I absolutely adore both of these costumes and would love to be able to switch between both! I completely understand if you guys don't want this, though, as it would of course take away a lot of the rarity of Rin's.

Thanks <3

**Comment by Luchosdf01** [comment]
They are in the game, the only think you need is affection at 1000 or more.

You're welcome <3

**Comment by Onion-Bubs** [comment]
> 
> 
> They are in the game, the only think you need is affection at 1000 or more.
> 
> You're welcome <3

Not quite true. You also need to have seen the costume on Halloween.

**Comment by Hapilone** [comment]
Thanks for responding everyone!

Okay, so if I got Rin last Halloween, then I can still unlock Marisa next time if I'm understanding correctly?

**Comment by AsuraShun** [comment]
then I'm screwed since I have terrible luck when it comes to unlockables with low chance

**Comment by Velius94** [comment]
Rin was rare in 2018 o31 (10%).
I suggest retuning the values once the event returns in 2019, with a higher chance of getting Rin, while making Marisa rare. Either that or 50-50.

**Comment by AsuraShun** [comment]
yeah,50 50 is better than the original rates

**Comment by AsuraShun** [comment]
or at least having it be guaranteed for those that didn't get rin

**Comment by AndriuxDev** [comment]
> then I'm screwed since I have terrible luck when it comes to unlockables with low chance

We're now two. ;-;
