### ISSUE TITLE
[Suggestion] A Sunflower for the Spaceroom

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3190]
So after listening to [this song](https://www.youtube.com/watch?v=ApXoWvfEYVU), for some reason I decided to google 'Sunflower'. I then discovered that Sunflowers are symbols for _'adoration, loyalty and longevity'_. I was thinking that Monika could program a sunflower (or sunflowers on the Floating Islands) into the Spaceroom, as a symbol for our love for each other. Your guys' thoughts?

**Comment by MaydayH** [comment]
That feeling when some sunflowers are taller than you, ahah

**Comment by AsuraShun** [comment]
a flower for a beautiful emerald colored rose

**Comment by AsuraShun** [comment]
that would be a good gift for her

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
