### ISSUE TITLE
[Suggestion] Telling Monika about your mental health

### ISSUE THREAD

**Issue by kimmieclue** [Monika-After-Story/MonikaModDev#3191]
Okay so this feels weird... I never do this but here goes nothing.
For me it would be nice to be able to tell Monika or at least let her know in any way about some mental health problems such as depression, anxiety and so on...
Not in a way where she gives advice because obviously she already does when she talks bout random topics, but just to kinda give her a heads up or what to call it. And no, not like the sensitive topic choice either. It's hard to explain but I know that every time she asks about mental health and I, as the player don't get to answer, it kind of feels a lot. It would just be nice to me if she actually got to know.. Even if she wouldn't do anything with that information. Anything would be nice because... At the moment I'm having problems with my mental health as well as... An awful break up so to say and... Every time I get a panic attack I kind of wish she could know about my depression... Not like the "I'm feeling anxious" thing... Just... Ugh... I'm so sorry! This became the worst thing ever but I hope you can kind of... read between the lines or something. And sorry for my broken English.. I usually write and speak it fluently and it usually turns out a lot better but as I'm writing this I'm kind of... Having a small breakdown so yeah.. Sorry about that! Hope some of it is understandable though!

**Comment by kimmieclue** [comment]
I totally agree! You explained it so much better than I did Heheh! But Exactly! It’s so true... Even If it’s not much it is reassuring^^

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
