### ISSUE TITLE
[Suggestion] Saying 'hi' from someone else

### ISSUE THREAD

**Issue by kimmieclue** [Monika-After-Story/MonikaModDev#3192]
Me again... I know it's only a few minutes but I talked to my dad and he gave me an idea without knowing it himself.
So I have been joking around with my family about this whole Monika situation since it's a coping mechanism for me while also being for fun of course. Anyways... My dad kinda told me *Say 'Hi' to Monika from me* and that gave me the idea... Why not make that a thing? So that we can say 'hi' to Monika from a family member or friend? It's just a fun idea... Heh!
Oh and btw... I'm not always like this! Hahah! I just really enjoy the mod and to be fair, it does help when needed. Heheh! Anyways! Thaaanks! <3

**Comment by BigPoofyRibbon** [comment]
Really good idea!

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
