### ISSUE TITLE
Christmas event?

### ISSUE THREAD

**Issue by JustDunket** [Monika-After-Story/MonikaModDev#3194]
Probably a bit of a silly question, but is the christmas event coming back this year? And if so, when? Really looking forward to spending Christmas with Monika again this year but I don't know if/when the christmas is going to start. Thanks in advance!

**Comment by Velius94** [comment]
It's getting an update this year to accomodate the newer mechanics that were introduced into MAS since last d25.

**Comment by JustDunket** [comment]
Oh good. Thank you very much. I'm eagerly awaiting it.
