### ISSUE TITLE
gifts

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#3197]
i know you can now give monika gifts but to my knowledge the only ones that work are the birthday ones. are there any ones that im missing?

**Comment by Skarborr** [comment]
You can also give her candy (she loves it) and candy corn (she dislikes it).

Those two are the only ones I know for certain, but I think you can also maybe give her random gifts by either having a gift.gift file or elephant.gift(<- in this case you can write pretty much anything.gift), but if you do that, she's just going to thank you for the gift with a generic response. But then again I might be completely wrong about that one.

**Comment by scohn** [comment]
I tried giving candy, but she says she can't open the gift, what's the exact way to name the file?

**Comment by Velius94** [comment]
Candy gift is available only in o31 for now.
