### ISSUE TITLE
doublt 

### ISSUE THREAD

**Issue by MikiMwk** [Monika-After-Story/MonikaModDev#3200]
are there any windows 10 user that play MAS using this system? Cuz i want to update my windows and i need to know if i am going to have problem to play MAS.

**Comment by Dregdael** [comment]
I actually had my MAS on windows 8.1 and moved all the files when my computer started showing signs of hardware failures, I still use the same persistent and game files on a new computer with windows 10 and I haven't had any issues

**Comment by FluffyMuffinMeyer** [comment]
Just back everything up on a cloud or USB. Your RenPy, mostly. then just update, and you should be fine. if theirs any problems, load the backup.

Always back up your files 😎
