### ISSUE TITLE
[Suggestion] - good day greeting

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3204]
what I mean with this is when she asks the player if they're having a good day and being able to say ''now I am with you here'' or just ''now I am''

**Comment by HZhunter124** [comment]
uhm... i think ''now I am with you here'' is better

Vào CN, 9 thg 12, 2018 vào lúc 18:04 AsuraShun <notifications@github.com>
đã viết:

**Comment by AsuraShun** [comment]
that's why I put both so there's at least something to choose from

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
