### ISSUE TITLE
weird numbers in the top left of the screen

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#3205]
not sure if i was always blind or i did something in my sleep but when i loaded mas up there are these numbers i haven't seen before, am i in dev move or something?

![screenshot0003](https://user-images.githubusercontent.com/43161297/49699598-1bd43a80-fba1-11e8-9dc3-6beb5482de78.png)

![screenshot0003 2](https://user-images.githubusercontent.com/43161297/49699608-33132800-fba1-11e8-99cc-c3bb5667fa83.png)

**Comment by jmwall24** [comment]
Not sure what those are tbh, but pressing `F2` toggles it on and off

**Comment by PC57** [comment]
I THINK those have something to do with the dialogue currently being displayed. Like a number on a powerpoint slide or something to that effect
