### ISSUE TITLE
New topics and features do not appear despite being fully updated

### ISSUE THREAD

**Issue by Mr-alexander10** [Monika-After-Story/MonikaModDev#3207]

**Comment by multimokia** [comment]
What specifically do you not have? Topics still have to unlock naturally through the normal progression, so it may take some time for them to fully unlock.

**Comment by Mr-alexander10** [comment]
I dont have any of the topics or the features from after v0.8.8.

**Comment by multimokia** [comment]
Can you send a screenshot of your `game` folder, please?

**Comment by multimokia** [comment]
Actually, looking at the link you posted here: https://imgur.com/a/1OORt9K, it seems like you installed 0.8.10 incorrectly, as all the folders (and `.rpyc` files) that are in your base directory for DDLC, should actually be in the `game/` folder. all the parts `game/` there, are the old ones, so essentially, your MAS is still running 0.8.8.

Simply just move all of the `.rpyc` files (and folders that are common inside the `game/` folder) into the `game/` folder, and then replace everything it asks you.

Alternatively, you could just grab a fresh DDLC copy, and install MAS on that (you won't lose any progress). That should fix your issue.

**Comment by Mr-alexander10** [comment]
Everything seems to be working correctly now! Special thanks to multimokia.
