### ISSUE TITLE
[Suggestion] "I was worried about you"

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3209]
A way to tell Monika that the player worries about her, maybe when the game crashes or other things like that.

**Comment by AsuraShun** [comment]
yeah, I really hope your idea gets implemented

**Comment by Foxinsunglasses** [comment]
Ditto

**Comment by Professor-JMO** [comment]
---

⮞ I'd like to capitalize on this.

**Topic**: _Worried Sick_

> If the last topic you engaged with _your_ Monika was "I'm feeling... Sick", then she will prompt you to rest and close the game.

>> My follow-up suggestions to this is that if the user is away for days at a time, oh...say...2-3+ days..? The user will return to a genuinely concerned Monika.

>>> I thought this might add a bit more depth to her character in the sense that I think would generate in a _real_ relationship sick hiatus.

>>>>Also, I was out of commission indisposed for a week when I had the thought.

---

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
