### ISSUE TITLE
[Suggestion] Breakfast/Lunch/Dinner with Monika

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3210]
I'm not sure if this has been posted before, but I think we should be able to eat with Monika. She can have her plate and everything in front of her, and we can eat at our computer irl.

**Comment by Rai99** [comment]
#1789, #1934, #2164. 

It has been mentioned before and it currently low priority. At the moment, I would guess there's a fair bit of work going into upcoming events such as Christmas, New Years possibly and maybe even Valentines day since those are coming up fairly soon.

**Comment by ThatOneUsername343** [comment]
Ok neat. ATTENTION MIGHTY DEVS! BE SURE TO ALSO ADD DESSERTS AS WELL!

**Comment by ThePotatoGuy** [comment]
[closing as duiplicate]
