### ISSUE TITLE
{Suggestion} Funny topic

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#3212]
I can't remember the last time I scrolled through a part of YouTube on Monika and not heard somebody mention something along the lines of "Goddess of thicc" or "Monika's thighs" I thought it might be a little funny to see her reaction on OUR opinion to that. After all, she's claimed to browse the internet a few times to us. What are the chances she wouldn't look herself up and see this? lmao...I don't expect this to be taken into consideration, I just think this topic is hilarious.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
