### ISSUE TITLE
Costume Rin

### ISSUE THREAD

**Issue by FarstKiller** [Monika-After-Story/MonikaModDev#3213]
Hello! I had encountered the following problem: I want to check Rin costume in action, but after reinstalling game in a several times I can't get it. I hope for help.

**Comment by FarstKiller** [comment]
Hello! I had encountered the following problem: I want to check Rin costume in action, but after reinstalling game in a several times I can't get it. I hope for help.

**Comment by Onion-Bubs** [comment]
Was Monika wearing the Rin costume when you played MAS on October 31st?

If not, then there's nothing you can do.

**Comment by ThePotatoGuy** [comment]
2 reqs for o31 costumes selector:
* 1000+ affection
* saw the costume on o31
