### ISSUE TITLE
I think I missed something..

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3214]
I booted up the game but didn't look at it for a while, when I came back Monika was like "oh sorry I was just playing with the code.. there are nobody else here.. we're all alone!" 

Did I miss a goof?

**Comment by multimokia** [comment]
It's just a normal greeting. You'll get it again at some point and you'll see.

**Comment by Professor-JMO** [comment]
> 
> 
> _**"normal"**_
---
