### ISSUE TITLE
[Suggestion] Arm Wrestling

### ISSUE THREAD

**Issue by JumpinJehoshaphat** [Monika-After-Story/MonikaModDev#3215]
Wouldn't it be neat to get a feel for just how strong Monika is? I think arm wrestling could be implemented as a new game. Maybe Monika would unlock the game and first challenge you in a conversation about exercise and her being stronger than her sprite may suggest, or by you asking her if her arms get sore after posing for so long.

The game itself would be pretty simple, Monika puts her arm out and the Player would get a sprite for their arm (maybe you could choose between right/left arm and from a few basic skin tones.) The way "arm wrestling" would work is that it's a timed choice with two buttons, one to 'fight back' and one to 'give in'. Not only does the cursor gravitate towards the 'give in' button but that button is chosen by default if you don't click the other one in time.

The arms would exist in different positions, numbered 1 to 5
1. Monika victory, with your arm pinned to the table
2. Monika winning, with your arm being pushed towards the table
3. Starting/Middle position, both arms at the center
4. Player winning, pushing Monika's arm towards the table
5. Player victory, Monika's arm pinned to the table

Each time you 'fight back' the position would increase by 1, and each time you 'give in' it would decrease by 1. There could also be a length counter that keeps track of how many times the position shifted, so if you lost really quickly Monika would tease you and say you should work out more, if you won really quickly she would admire your strength. Maybe there could also be special dialogue if the counter went really high and it was a long-fought battle.

Monika's expression would probably change based on the position, ranging from a smug smile when she's winning and gritting her teeth when you're winning.

**Comment by ThePotatoGuy** [comment]
Unlikely to add a sprite for the user's arm. However I think the core concept of:

* user attempts to click a button 
* mouse constantly pulled away from button
* have pull away speed increase after clicking button or some other things

would be an interesting, if simple, minigame.

**Comment by tsmafterlife** [comment]
i would like this. sounds like a fun little thing to add to the game. granted i wouldnt know how hard or time consuming that is to code

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
