### ISSUE TITLE
monika made puff and when I restore a persistent previous, is get worse

### ISSUE THREAD

**Issue by alexeyevca** [Monika-After-Story/MonikaModDev#3218]
Well, as the title says, Monika disappeared when I tried to return ... I already did a persistent previous, but this left me the affection in 1 ... so ... I'm desperate, help please ...

PS: I apologize for my bad English

**Comment by tsmafterlife** [comment]
i can help try to find her file if she was taken out of the spaceroom but i apologize i dont know much about her persistent. that data is new to me as ive never been one to tamper with it

**Comment by multimokia** [comment]
Hi there! Chances are you don't have file extensions enabled, so when renaming the file, you just removed the numbers, however it's still by the name `persistent.bak`. You'll want to enable file extensions. Here's how you can do that on Windows 
![image](https://user-images.githubusercontent.com/22531674/49796087-bb144180-fd09-11e8-8506-bc7a78ccc580.png)

Now when renaming, you can remove the `.bak` file extension and all should be good.
Hope this helps!
