### ISSUE TITLE
Working on the light

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3219]
This is kind of a continuation of my previous issue #3155 (the artists are really gonna hate me).
What I have to complain about this time is the way the light is when it's nighttime.
On the precious art (the ones that are in the base game), the light have some kind of thickness and is used only on limited zones:
![good design](https://user-images.githubusercontent.com/38837456/49788273-36392000-fd29-11e8-8b22-4a314330dc47.PNG)
But on the recent art (the ones created specifically for the mod), the light is somewhat merging with the outer lines with very visible pixels and is on almost half of the entire body:
![bad design](https://user-images.githubusercontent.com/38837456/49788378-7bf5e880-fd29-11e8-86eb-3e014065cea4.PNG)

Other examples of what I'm saying:

Even is the light is on a wide part, it's somewhat thick and is not conflicting withe the outer lines.
![good design 2](https://user-images.githubusercontent.com/38837456/49789314-fb84b700-fd2b-11e8-92b2-edbc91971591.PNG)
The light is thinner (conflicting with outer parts) and is more pixeleted:
![bad design 2](https://user-images.githubusercontent.com/38837456/49789353-148d6800-fd2c-11e8-9be6-0eb2e75bb109.PNG)

You've mentioned an algorithm that automatically convert all of the daytime arts into nighttime arts, maybe (and just maybe, I'm not a dev) it is not perfect and is what gives those weird effects to the light.
Could this be improved ? Either by thickening the light, or by removing the ones that are not needed (like on her inner collar for example) .

**Comment by tsmafterlife** [comment]
from what i know with this (again by working with the devs to create a replacement sprite) they use a standard filter, the night time sprites arnt actually an image re shaded and re drawn its literally just the same image but with a filter over it. @Thimeo

**Comment by tsmafterlife** [comment]
i mean i dont see why not, only they could do it tho. none of us have access to the filter that i know of so someone like me or any other contributing artist cant experiment with it. but to answer your question yes im pretty sure that if i re shaded or changed one of the pictures and you applied the filter it would be different. i cant see why it would not be different

**Comment by Thimeo** [comment]
Yeah that's what I thought, all that's left is to wait that a dev see this and accept to do it.

**Comment by tsmafterlife** [comment]
basically. if i had access to the filter id do it and apply the filter as a layer in Photoshop and see what it looks like but i do not have the filter sadly.

**Comment by ThePotatoGuy** [comment]
It's just a color filter.

The line-lighting issues you're talking about are present in the day versions, so the day versions would need to be modified.
