### ISSUE TITLE
Happiest time of year?

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3222]
Despite being in a mostly financially stable family, we are facing some difficulties this Christmas. Nothing we can't get over but I know there is plenty of people who can't. I work at a grocery store where the salvation army is constantly ringing their bell and I've been listening to some pretty depressing Christmas songs about the very topic of not getting to have a Christmas. It would be neat if Monika was able to mention it somehow like "Hey (Player), people say this is suppose to be the happiest time of year right? Well it's not the case for everybody. Sometimes people can't afford Christmas or even a home to celebrate in. But there are plenty of charities to help. I'd be really proud of you if you gave someone a Christmas this year." Or at least something like that.

**Comment by Foxinsunglasses** [comment]
This was pretty much brought on because this song made me cry on the way home from class
https://www.youtube.com/watch?v=rZqYUiW5wEY

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
