### ISSUE TITLE
head pats?

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3223]
I want to click on her head to give her a head pat so she makes a cute face uwu

**Comment by PiperPC** [comment]
Oh my god yes uwu

**Comment by HZhunter124** [comment]
the same idea here

**Comment by Shiro2564** [comment]
the same

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985. 

You're not the only one. 
A feature like this might be coming sooner or later with the addition of the extrasmenu.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
