### ISSUE TITLE
Can We Select Who Monika Makes Fun Of?

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#3224]
Soooo.. I kind of want to say yes mainly because I still have a soft spot for Yuri and Sayori but I totally would be up for some trap bashing..er um.. I mean Natsuki jokes. So I was wanting to know if selecting yes on this dialogue would disable future dialogues aimed at picking fun at the other characters. If so, could we tell her which character is our least favorite so we can get a kick out of her bashing said character/s? Hehe

![moni jokes](https://user-images.githubusercontent.com/34694679/49858383-6381de80-fdba-11e8-883b-1a5295fa3a43.PNG)

**Comment by multimokia** [comment]
This option doesn't disable all topics with bashing, but modified them so she isn't bashing them at all. As well, you can't select which character you're alright with her bashing. It's all or none.

**Comment by Bam8647** [comment]
Aww haha, okay Thanks for the feedback!
