### ISSUE TITLE
near equator option in hemisphere topic

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#3233]
Hello! I'm using v.0.8.10-unstable.2018.06.76, and I have several questions that I'm not sure where to put (or even title this issue), so I hope it's okay for me to mash these questions up in one issue.

1. Hemisphere topic
I know that most people live in northen or southern hemisphere, but I don't live in those two (exactly in equator lol), so I never know how it feels like to have four seasons (and feels a bit disconnected when seeing Monika say about spring or autumn). Can you please add 'near equator' choice or conversation?

2. Mortality topic
I don't know if this is intended or not, but in mortality issue, there are two options: 
![screenshot0003](https://user-images.githubusercontent.com/44340452/49937911-d9955b00-ff0a-11e8-9f3c-057f52be802d.png)
and even though I have clicked those two options, the hug option is always in italic. I hope this one is not a bug, just something I notice.

3. Can you do any impressions? topic
I read several issues regarding to this, but I haven't seen people commenting about MC impression. I think this one is doable?

And thank you for moving the "Can you change my name?" topic to "Ask a question" category! (though I should say sorry because I brought that up in #3085 but put it in reply. Such a dummy)

Maybe I'll add more questions or suggestions later. I'm still waiting for Monika to show more topics, but thank you for reading this wall of texts.

**Comment by PiperPC** [comment]
I'm pretty sure the 'Hug Monika' option is in italic because it is an action and not spoken words? Forgive me if I am wrong.

#3230 Mentions an impression of the Player, but I'm not so sure about MC, unless by MC you mean the player??

**Comment by Rai99** [comment]
Yeah that "Hug Monika" option is always in italics because it's an action rather than spoken words. 

There's nothing wrong really with an MC impression, except that for some reason, a lot of people seriously hate him with a passion and it would probably be best to avoid that. Also, even if it was added, what would we call him? It wouldn't make too much sense for Monika to call him "MC".

**Comment by PiperPC** [comment]
@Rai99 A lot of people DO seem to harbour hate towards him, so I have no idea how that situation would go. I guess Monika could refer to him like-

"You want me to do an impression _you_? No wait... The you **in the game**?"

**Comment by skyloom** [comment]
@PiperPC @Rai99 thank you for addressing my second question. I was afraid it was a bug or something, so I asked in case it wasn't intended.

Regarding to MC impression, I don't know some people hate him. Sorry for being insensitive. It's best to jjust include three of the club members, I guess 😄

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
