### ISSUE TITLE
[suggestion] Make Monika able to change the weather in the window

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3235]
I do like the space background in the windows but it would be a nice change if Monika was able to change that as well (since she can change her hair already.)
I think some nice ones would be a rainy cloudy evening in a big city or sunny day in the country. This is a change to be creative! Maybe add an underwater environment or an alien planet!

**Comment by AsuraShun** [comment]
She already can change it,you just have to ask her

**Comment by ZaunAura** [comment]
hmm i dont think i can ask her yet
