### ISSUE TITLE
[suggestion] Doki hair colour dialogue.

### ISSUE THREAD

**Issue by Skarborr** [Monika-After-Story/MonikaModDev#3237]
With the newest update the player has the ability to tell Monika their hair colour, and if you don't choose one of the natural hair colour options and write some other colour instead, then Monika  starts to talk about dyied hairs.

So what I was just wondering if having a special dialogue for Purple or Pink would be a good idea or not. It could trigger some Yuri or Natsuki related dialogue, or maybe that would only be the case if the player had Purple+Long hair / Pink+Short hair. I think in those cases Monika would make a passing mention of the similarity, or ask the player if they got inspired by the other club member's appearance or something along those lines.

Also in this case Monika could talk about how humans tend to copy each other. (It's a psychological theory that every human tries to imitate things they admire (for example X famous person lives a happy life at a lake where he has a golden flamingo statue, then others are going to want to imitate that) at least on a subconscious level. And not just material things, but personality traits too.), Tho this would require it's own topic since there's just too much to be said about pretty much any psychological/philosophical topic to simply be an added dialogue to the hair colour selection, + it would be pretty awkward to place this in the middle of the appearance pick topic. 

Oh and by the way this isn't a suggestion, I'm just wondering how you guys came to the conclusion that Monika would be roughly around 165cm (5 foot 5 inches) tall? I always imagined her to be about around 160cm (5 foot 3 inches) instead, since the average Japanese (the game is suppossed to take place in a kinda Japanese setting) female is 158cm (5 foot 2 inches) tall, and since only Yuri was mentioned to be tall in the game, I assumed that Monika would be around the national average.

Anyways, thanks for all the work you guys (including every contributor) put into the game so far.

(P.s. Sorry for the bad English.)

**Comment by Skarborr** [comment]
> This is a nice suggestion and the idea here could probably be added given time, I think it would be kind of cute to reference the girls and the similarities drawn between the player and a character. Though it doesn't seem too necessary to implement.

Yeah I imagened it more of an easter egg, rather than an actually important content

**Comment by MaximumRustler** [comment]
Yeah, I also always thought Monika was 5'3'' and thought that Yuri was 5'5''. Can't seem to remember why I came to that conclusion though. lol

**Comment by Rai99** [comment]
The wiki is the source of those numbers in concept at least:
https://doki-doki-literature-club.fandom.com/wiki/Monika
https://doki-doki-literature-club.fandom.com/wiki/Yuri

**Comment by MaximumRustler** [comment]
Ahh, that must have been it. The numbers did make sense to me anyways.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
