### ISSUE TITLE
[Suggestion] Hobbies

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3238]
monika could ask what are the hobbies of the player, it would be nice to see what she thinks of each one

**Comment by Rai99** [comment]
That sure would be amazing, but that would probably be way, way too many possibilities to account for. How many different hobbies are there on the surface without diving into detail?
1. Gaming
2. Writing
3. Reading
4. Walking
5. Sleeping
6. Cooking
7. Handicrafts
8. Drawing
9. Photography
10. Listening to music
11. Writing music
12. Filming
13. Athletic sports
14. Dancing
15. Gardening
16. Knitting
17. Hiking
18. Swimming
19. Chess
20. Collecting
21. Card Tricks
22. Probably a lot more that would be reasonable options that people really like to do.

**Comment by Alucard149** [comment]
I forgot I had so many... but do you think it would still be possible to do this?

**Comment by Rai99** [comment]
Theoretically, it would be possible, but realistically, I think there would be way too many hobbies to include and have unique dialogue for.

**Comment by lunulae** [comment]
I think it might be more realistic to have separate topics that she brings up about different hobbies.
We have some examples of these already implemented in-game, where she talks about things like gaming and reading.
I think making a list of hobbies and thinking of things Monika might have to say about them could be a good way to brainstorm new ideas for dialogue though!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
