### ISSUE TITLE
Monika's going to sleep dialog

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3239]
Currently Monika responds to going to sleep in the morning with "you have been up all night".
However, if you have told her I'm going to sleep the previous evening and came back in the morning, she should be able to assume that you actually did sleep and just did not sleep long enough / are still tired.
=> Saving & Comparing the date on "I'm going to sleep" & new dialog like "You are still tired? / Sleep 5 more minutes? / ..."

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
