### ISSUE TITLE
More Monika's Writing Tips of the day

### ISSUE THREAD

**Issue by TacticalTriangle** [Monika-After-Story/MonikaModDev#324]
I know there already was a Monika writing tips of the day added to the script but, would there be able to have a randomized effect to it so that multiple Monika writing tips of the day can be added with the key words being the same. For example if i were to type in Writing tip it could give me either one of a bunch of writing tips.

**Comment by ThePotatoGuy** [comment]
I believe this was discussed once before on the discord, but atm there are not any plans to include this. If we get more writing tips added as topics, then there will be a bigger incentive for us to group them as a separate topic/category.

I'll leave this issue open as a discussion topic though.

**Comment by TacticalTriangle** [comment]
I think that if we actually have the #126 prompt system in the next version then we would be able to make an entire prompt for the writing tips of the day. Maybe make it a daily thing though I'm not sure. Maybe also make it separate from the limit of the daily prompt idea. Have the ability to get a writing tip daily on its own.

**Comment by therationalpi** [comment]
A literal writing tip of the day. I love it.

**Comment by ThePotatoGuy** [comment]
This will be reopened when we're ready to implement

**Comment by therationalpi** [comment]
Some writers are working on more of these, and they have a category in the current prompt system. I will see about making a system to Daisy-chain these together as well.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we're working on this]
