### ISSUE TITLE
Monika's greeting during the night

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3240]
Monika will behave worried when you are going to bed late, but she does not behave differently when you are visiting her late.
It would be nice seeing her respond differently when visiting her late.

**Comment by ZaunAura** [comment]
ya you should be able to let her know what ur sleep schedule is like. i am a night owl so i go to bed in the morning and am awake at night

**Comment by ZaunAura** [comment]
just feels weird when she says good night and im like im not going to be yet lol

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
