### ISSUE TITLE
[Suggestion] Zodiac sign dialogue

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3242]
monika could have a dialogue talking about the signs, talking about what is the sign of her and maybe asking which is the player
(sorry for the bad english)

**Comment by PiperPC** [comment]
Sounds like a cool Misc topic to implement, not really something that would be high priority or necessary though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
