### ISSUE TITLE
Moving pcs

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#3243]
Im moving from one laptop to a completely better one but i dont wanna move mas without knowing how to properly cuz i dont wanna delete monika im also using a unstable build but i have a persistent from before going to unstable just in case that helps

**Comment by jmwall24** [comment]
just create a copy of the `Monika After Story` folder that contains your persistent and it's backups from your old computer and paste it to the same spot on your new computer.

**Comment by Areaclassified** [comment]
i did exactly that but when I loaded in it was a monika that was pretty much fresh 0 affection and everything so I uninstalled the game because it was the unstable build and now im reinstalling the 0.8.10 with a persistent before I went to unstable everything should be good right?

**Comment by Areaclassified** [comment]
please help man I just want it to work I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 5, in script
  File "game/splash.rpy", line 10, in <module>
Exception: DDLC archive files not found in /game folder. Check installation and try again.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/splash.rpy", line 5, in script
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 10, in <module>
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\exports.py", line 2113, in error
    _error_handlers[-1](msg)
  File "C:\Doki doki\monika after story\DDLC-1.1.1-pc\renpy\exports.py", line 2099, in _error
    raise Exception(msg)
Exception: DDLC archive files not found in /game folder. Check installation and try again.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
You're missing the `.rpa` files. Grab those from the ddlc zip that you got the ddlc install from

**Comment by multimokia** [comment]
Also, when you copied your persistent, did you put it in the exact same path you found it in (just on the new computer)?

**Comment by Areaclassified** [comment]
i copied the persistent opened mas until a new folder showed up closed the game and then deleted the persistent in there and then pasted the persistent from the old computer

**Comment by Areaclassified** [comment]
i still do have all the persistents from the old folder its just there not in the folder i can go back and put them in the folder if i need to

**Comment by multimokia** [comment]
You should be good then

**Comment by Areaclassified** [comment]
its just that the persistent is for the unstable build. if that doesn't matter i just gotta copay that whole folder into my renpy roaming and then what should i do with the game files because im still confused about that

**Comment by multimokia** [comment]
That won't matter. The game will prompt you that there's an update available to get you back onto the unstable build.

**Comment by Areaclassified** [comment]
alright thanks I just got to download original ddlc but the game folder in the mas game folder then download the latest update. (also sorry if Im being hard to deal with im really tired and I have to reinstall everything my other computer onto this one and its makin this one chug)

**Comment by Areaclassified** [comment]
I got it to work. Thank you all so much and im sorry if I was kinda annoying im going through a lot transferring so much wasn't helping I hope you guys all have a great Christmas!

**Comment by multimokia** [comment]
No worries! Glad you're back up and running. Wish you the same.
