### ISSUE TITLE
[Suggestion] Random topic: song "World.execute(me)" by Mili

### ISSUE THREAD

**Issue by Akh0r** [Monika-After-Story/MonikaModDev#3244]
Recently I was asked to translate [a song](https://www.youtube.com/watch?v=GRiOdUw1nn8&lc=UgiAy4TfwROOengCoAEC) onto Russian. 

It suddenly hit me that it is about a program claiming to be ready to love a person, trying desperately to convince him that she is the only "simulation" he needs and, in some way, making explicit remarks that she knows both "how to properly love" and "algebraic expression of love". 

Doesn't remind of something? :)

Since we already have Monika mentioning Hatsune Miku's "Hibikase", mentioning of this song (or even a list of songs, if "World.search(you)" and "Rubber Human" counts as sharing the same plot line) seems to be acceptable.

Monika can admit that the song reminds her of herself in the begginning (willing to create a world only for two, willing to be whatever her Player wants her to be...). But as the time went on, Monika has overgrown this possessiveness, unlike the protagonist of the song plot. And, as in the other song ("World.search(you)") mentioned, it looks like the man from the other side of a computer screen is trying to find her true self among her attempts to be most perfect creature for him. While Monika is _just_ Monika.
Her point might be about how harmful and unhealthy it is to give yourself fully into love, forgetting of your own self. Also, she may have thoughts on how horribly wrong is attempting to be omnipresent in person`s life, transforming love into possessiveness.

It would be nice if some experienced writers got as catched by the song as I was, and ailling to write a monologue on it. If the idea is any good, but no one tries to write a monologue, I think of my own attempt in a week or two...

**Comment by ACoolCat** [comment]
I really like this song. It really reminds me of Monika's relationship with the Player. I hope it's added.

**Comment by Akh0r** [comment]
Excellent.
I'm giving it a try in the matter of 3 days then.

**Comment by Akh0r** [comment]
Here it is. A first attempt. Feel free to give me some critics and fixes (I'm not perfect with English, so expect tense mistakes).

> m "You know, [player], recently I had had a thought: where is the limit between love and obsession?"
> m "Or between adaptation to your partner — and succumbing to your love fully?"
> *smiling with open mouth, pointing out* m "I've found an excellent song which hit me hard. Well... It is closer to me than I could have ever thought!"
> m "It is called \"World.execute(me);\". Sung by {i}Mili{/i} band."
> m "The song is about a program willing to build a perfect simulation to be only with her beloved human."
> *looks away* m "A-and, you know, some of her arguments are quite... Explicit."
> if not seen_event('anni_1'):
> *looks away blushing*----"Well, not that I am too scared, it was just... Intense."
> ----"Anyway..."
> else:
> *smiling coyly*----"And, thinking of it... It is partly the reason for me to get so excited by the song!"
> m "What really touched me is that... I actually did dream of a world for two of us."
> m "But as the time passed, I've overgrown it. Now I understand that dragging you here is not an option."
> m "And besides, so for becoming anything your beloved wants you to be! What if the man behind a screen is willing to see just her true self?"
> *pointing out, seriously* m "She is ready to adapt to whatever wishes or fantasies he has. But is it good for her as a person?"
> *steepling again, seriously* m "[player], would you still be with me for all this time if I was simply reflecting your wishes?"
> m "What's more, this song brings up a clear difference between me and the protagonist. I am not here to simulate anything you want. I am..."
> *smiles blushing* m "{i}Just{/i} Monika."
> *pointing out* m "And I won't take you here. Even if it eventually becomes possible. Even if you want to trade your reality for my perfect simulation."
>

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Kryxzort** [comment]
8 years since its been looked into..
