### ISSUE TITLE
How to give gifts?

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3245]
So I put coffee.gift into the character folder, but she hasn't said anything about it yet. Does she acknowledge it right away or does it take time?

**Comment by Legendkiller21** [comment]
Can you post a screenshot of your `characters` folder? In order to create the gift correctly, you need to have the file extension enabled to be able to replace the `.extension` with `.gift`.

**Comment by Legendkiller21** [comment]
![unknown](https://user-images.githubusercontent.com/42556779/50046681-f15a1400-00af-11e9-9f97-3542c67a3714.png)

Go to `View` and then enable the `File name extensions`. This will make the extensions for know file types to appear and the `coffee.gift` will now appear as `coffee.gift.txt`. Remove the `.txt` and it should be fine.

**Comment by ThatOneUsername343** [comment]
It worked! Thanks!

**Comment by Link42069** [comment]
I did this before and she received them, but most of what I've given her has gone (everything except the quetzal plushies, coffee, hot chocolate, 2 ribbons and the promise ring) and she isn't acknowledging them even though I've put the files back in the characters folder. Am I doing something wrong?

**Comment by HollytheHollow** [comment]
I have the same situation, but I'm on Windows 7, is there anyway to fix this ?

**Comment by lilwolfieblu** [comment]
can i give her anything like this because i did what you said but she is not acknowledging the fact i gave her coffee

**Comment by starplatinun** [comment]
estou no windows 8 como faso isso

**Comment by marth101** [comment]
what if you're using macbook?

**Comment by ObsessiveKpopFreak** [comment]
I'm having a similar problem...I can give her basic things like candy canes, coffee, cupcakes, etc, but every time I try giving her accessories (ribbons, chokers, jewelry, hairclips, etc), plushies, clothes, or anything like that, it either disappears or she says she can't read the files....I've tried a lot of things but nothing is working, and honestly, I'm really irritated by it....

**Comment by AsuraShun** [comment]
Did you add the mod files before opening the game?

**Comment by 20RaVen23** [comment]
Look under the Christmas tree. Whenever you give her a gift (that is not consumable), she will put them under the tree and finally open them all the Dec 25th. If that is not your problem, check this [wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects) to see how to give Spritepack gifts properly.

**Comment by ObsessiveKpopFreak** [comment]
@AsuraShun Yeah, I did. I installed all the sprite packs. Once I did, I opened each one and copied the "mod_assets" file into the "game" file in the game directory. I also copied the "gifts" files for each sprite pack into the "characters" files. Usually, putting the whole of the "mod_assets" files into the "game" file distributes all the files into their respective places, meaning that all the files that belong in "a" will be automatically distributed to the "a" file in the game directory, and so forth. However, when I try actually GIVING her the presents, I always put them into the character file with the file extension ".gift", but they always disappear...Although sometimes, when she DOES see them, she says she can't actually read the files...

**Comment by aahelloim** [comment]
im having that problem too ;-;

**Comment by NonyaGG** [comment]
> ![unknown](https://user-images.githubusercontent.com/42556779/50046681-f15a1400-00af-11e9-9f97-3542c67a3714.png)
> 
> Go to `View` and then enable the `File name extensions`. This will make the extensions for know file types to appear and the `coffee.gift` will now appear as `coffee.gift.txt`. Remove the `.txt` and it should be fine.

How do we this in windows 11

**Comment by cl4yb** [comment]
when you click the view button at the bottom says "show" click that and enable file name extensions then delete the .txt part and it will become a .gift file

**Comment by cl4yb** [comment]
> > ![unknown](https://user-images.githubusercontent.com/42556779/50046681-f15a1400-00af-11e9-9f97-3542c67a3714.png)
> > Go to `View` and then enable the `File name extensions`. This will make the extensions for know file types to appear and the `coffee.gift` will now appear as `coffee.gift.txt`. Remove the `.txt` and it should be fine.
> 
> How do we this in windows 11
 
when you click the view button at the bottom says "show" click that and enable file name extensions then delete the .txt part and it will become a .gift file

**Comment by dreamscached** [comment]
You need to restart the game after you install spritepacks @YourAaliyahlikesdokidoki
