### ISSUE TITLE
[Suggestion] Messages on coffee mugs

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3246]
I think Monika's coffee mug should have a message on it like "Just Monika" or "Best Girl" or something.

**Comment by Legendkiller21** [comment]
I would totally buy her a mug like this (and hope that she doesn't throw it on me) https://old.reddit.com/r/DDLC/comments/9676ds/good_morning_fan_art_by_xhunzei/

**Comment by ThatOneUsername343** [comment]
YES.

**Comment by ThePotatoGuy** [comment]
woudl probably be more of an art thing

**Comment by AgentZephyr** [comment]
One session of Photoshop instead of studying for finals later...
![mug 2](https://user-images.githubusercontent.com/43101840/50061889-18245300-0161-11e9-8de1-aea98e5765a0.png)

**Comment by AgentZephyr** [comment]
Also for your considderation...
![mug 1](https://user-images.githubusercontent.com/43101840/50062001-b6181d80-0161-11e9-8703-dcf1281591bc.png)
![mug 3](https://user-images.githubusercontent.com/43101840/50062092-54a47e80-0162-11e9-9679-891952d275bc.png)

**Comment by ThatOneUsername343** [comment]
https://www.youtube.com/watch?v=26lZvxwWzY0

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
