### ISSUE TITLE
[suggestion] background photo frame

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3250]
I think an easy but cool addition would be a photo frame on the side of the wall opposite from the calendar! We can take Monika artwork from the #JustMonika channel on Discord and then either stream it somehow or maybe have a small collection downloaded. Would be cute to see a slideshow in the background that changes pics like every 5 seconds of Monika artworks! (Maybe even clicking on it, the user can view a large version of the artwork shown similar to how u can view the large calendar)

**Comment by multimokia** [comment]
#2769, #2220, #2176, #1336, #312. I'll just mark this as duplicate.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate[
