### ISSUE TITLE
Game crashes after I set my birthday to 1894

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3253]
So i set my birthday and the game crashed. Sucks to have been in 1894 :/

**Comment by multimokia** [comment]
Do you have a traceback at all?

**Comment by ZaunAura** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2687956/traceback.txt)

**Comment by ThePotatoGuy** [comment]
oh wow, think we should limit the range when selecting pre-1900 then

**Comment by ThePotatoGuy** [comment]
this was covered in #3540
