### ISSUE TITLE
[Question] About unstable

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#3257]
Just how unstable is unstable?  How common is it to lose persistents/crash/all that good stuff?

**Comment by Areaclassified** [comment]
From my experience the game will crash every once in a while but most of the things in unstable that make your game crash have most likely been patched. i haven't had any issues with persistents since i've moved pcs.

**Comment by FluffyMuffinMeyer** [comment]
I'v never had a crash from unstable before. Usually its just an early peak at new dialogs and things, Most immersion breaking thing you'll find is some typo's.
