### ISSUE TITLE
"Back from work" Suggestion.

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3258]
["Would you like to eat, have a bath.. or would you.. have.. me?](https://youtu.be/xzu28Ua_keM)

Typical anime trope, but I think it'd be funny for Monika to joke about.

**Comment by multimokia** [comment]
I mean, there's a similar thing already in the mod

**Comment by Onion-Bubs** [comment]
Yeah, there's a greeting that sometimes comes up where you start with a black screen and three options: open the door, knock, or listen. If you pick listen, there's a chance Monika will say something like what you've written.

**Comment by ThePotatoGuy** [comment]
monika calls it out in the opendoor greeting, dont think we'll actually do it though since it is rather out of character
