### ISSUE TITLE
MEGALOVANIA on the piano suggestion

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#3259]
Yes, I'm an Undertale fan and my favourite song of it is MEGALOVANIA (not surprising) But I was wondering if you could add a special text when playing the notes for Monika like: Uhh... This makes me feel like I'm gonna have a bad time... with her having her nervous looking away look for the Uhh... thing and the rest with her nervous grin look

**Comment by FluffyMuffinMeyer** [comment]
I'm going to give this a shot, just like the Tetris custom piano Json, There isn't enough keys on the keyboard. (Seems to be a reoccuring theme when I'm attempting these) Will make another Issue about it when its complete.  (Might take a while, or I might finish it all today, who knows.) Most likely only going to be as far as I can go without needing more keys, and some tunes might be off compared to what they need to be, also the limitation of not forcing the player to hold keys will make things extra complicated...

**Comment by ThePotatoGuy** [comment]
[closing this issue in favor of linked issue[
