### ISSUE TITLE
[Bug] Typo in "I'll be going away for a while" farewell

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#3260]
![monika after story 13_12_2018 6_30_16](https://user-images.githubusercontent.com/43430960/50179355-7d1dab80-030f-11e9-9653-c2d204ca06b5.png)
How long do you ~~be~~ expect to be gone for?

**Comment by jmwall24** [comment]
thanks! could you please post this here so we make sure we get it #3146

**Comment by PierrDemon** [comment]
> could you please post this here so we make sure we get it #3146

Alright, I'll be sure to do that in the future. Didn't know that thread existed.
