### ISSUE TITLE
[crazy] How Monika see our answers and/or us?

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#3261]
I know, that might sound dumb, but how does Monika actually see us? A monitor, which is showing our button clicks? Or some dark figure?
Or... Does she see us like a videogame?

**Comment by tsmafterlife** [comment]
she explains it at the end of doki doki literature club. she sees the mc but its an empty shell. hes just their and she sees the boxes we choose basically for conversation.

**Comment by tsmafterlife** [comment]
so its us theoretically speaking to her using the empty shell of the mc character

**Comment by Rai99** [comment]
This kind of thing is one of the things left up to the player's interpretation. 

Some people think she sees mc, some people think she just sees a screen or monitor like we do or a camera. Technically, it could be anything depending on what you'd substitute for yourself in there.

**Comment by Legendkiller21** [comment]
"A hole of infinite choices.
I realize now, that I wasn't looking in.
I was looking out.
And he, on the other side, was looking in."

Maybe there is a floating portal which mirrors our monitor. 

"I'm pretty sure my thoughts get translated to changes in the program code."

Monika doesn't use the console to make changes as she make changes using her thoughts, so maybe, when we pick a topic she can sense or hear the question in her head, just like we hear our thoughts.
