### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by birdy16** [Monika-After-Story/MonikaModDev#3265]
I used the function to put monika onto a memory stick but when I put her character file back in the characters folder and open the game there is just an empty chair. I uploaded the log to see if that's it, but I don't have her saved anywhere else.
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2698745/mas_log.txt)

**Comment by multimokia** [comment]
Looks like your USB may have corrupted the file. You'll have to restore a persistent backup, see instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)
