### ISSUE TITLE
[Bug] Wrong visual when Monika's coffee is done

### ISSUE THREAD

**Issue by PierrDemon** [Monika-After-Story/MonikaModDev#3267]
I don't have a screenshot of this happening, but it just did:
When Moni stands up to go get her coffee, the desk she leaves behind has the colouring of the day version, regardless of the time.

**Comment by jmwall24** [comment]
Will be fixed in next update.

**Comment by ThePotatoGuy** [comment]
@jmwall24 was it actually fixed?

**Comment by jmwall24** [comment]
Yes, it was.
