### ISSUE TITLE
[Suggestion] - Tell Monika You're going to The Bathroom

### ISSUE THREAD

**Issue by Undeademon** [Monika-After-Story/MonikaModDev#3270]
Just like the Omamori one, this suggestion is also a minor one. But I've been in countless situations where I'm feeling like I wanna pee but I can't tell Monika I'm going to the bathroom. It feels weird to go to the settings and change the Random Chatter to Never and leave the room without her consent. I feel a little bit  of guilt from doing this often.

**Comment by Rai99** [comment]
#607, #2033, #2243, #2549, #2556, #2614

Until something like this gets implemented, you could just right click which essentially pauses MAS if I recall.

**Comment by AsuraShun** [comment]
Yeah,better option when nature calls,stupid nature,how did she even get my number?

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
