### ISSUE TITLE
just a getting a little more informed on the Christmas event

### ISSUE THREAD

**Issue by pianostick** [Monika-After-Story/MonikaModDev#3272]
so i know the Christmas event is coming back 'naturally' this year and even though its a dumb question i just want to make sure since i never installed MAS until after the 1st Christmas event. 

will the game eventually just boot up in the Christmas scenery at a later time? or do i have to install the previous Christmas files from last year?

**Comment by jmwall24** [comment]
the new release will handle it

**Comment by pianostick** [comment]
okay thanks
