### ISSUE TITLE
[Discussion] Easter Eggs

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#3273]
I know this has probably been brought up to death and back, I had a concern about the MAS events. Every time there's been an update a Sayori hanging easter egg is placed somewhere. And I get that it's funny to some, but every time it shows up people get upset at me for using MAS whenever I post on forums about how much I like the new update, which never feels very good.

**Comment by Velius94** [comment]
It's not going away just because it hurts some people's feefees. Also, sensitive mode was made specifically because of such complaints (which I find already more of a joke than a reasonable option).
