### ISSUE TITLE
[Question] Quetzal hat

### ISSUE THREAD

**Issue by MaximumRustler** [Monika-After-Story/MonikaModDev#3284]
Hi, first off I want to say that I love this update and thanks for all of your hard work! Now my question is, is it a bug that the quetzal doesn't have the little hat or is it a chance that it could have it?

**Comment by multimokia** [comment]
Is this on your first launch of the update?

**Comment by MaximumRustler** [comment]
Yeah it was.

**Comment by jmwall24** [comment]
next time you see the plush before Christmas day is over, it should have it on

**Comment by MaximumRustler** [comment]
Yep, it had the hat this time. Thanks for letting me know!
