### ISSUE TITLE
gifts question

### ISSUE THREAD

**Issue by tsmafterlife** [Monika-After-Story/MonikaModDev#3289]
will all new gifts within the new update only be allowed to be given to monika during Christmas day or is that just the ribbon because i cant give her hot chocolate or candy canes etc. i know the ribbon is only on Christmas but what about the other gifts?

**Comment by EmpressNael** [comment]
I would like to know too please

**Comment by Jparnaud** [comment]
So first off, here is a wiki page about punctuation, might help you being comprehend - https://en.wikipedia.org/wiki/Punctuation

After trolling, if I get what's going on, all gifts are giveable on the time christmas end (at least), the ribbon is the only exception and only is able to be gift on a "Special day" like someone called it...

Also, there seems to be a dialogue about "changing her ribbon" on the dialogue list now which make you change it from the new black one to the white one ... idk if you can give her all the ribbons on the special day to change it or whatever, but its probably related somehow ... idk X)

All I know is ... I'm gonna check everyday the discussion until I figure it out and the game too cause its Monika of course, I need to check it XD

No idea if that helps but ... *vanish*

**Comment by jmwall24** [comment]
the others should be working.  you probably just don't have file extensions enabled, so when you rename them, for instance `hotchocolate.gift` you are actually renaming it `hotchocolate.gift.txt`

**Comment by tsmafterlife** [comment]
if i read that wiki correctly then the correct punctuation would be "might help you be more comprehensible" @Jparnaud

**Comment by tsmafterlife** [comment]
all jokes aside, thank you for the responses everyone

**Comment by Jparnaud** [comment]
I'm sorry, english not my first language XD

Tho, I was mostly talking about coma and stuff ... like when we text, but this time with three phrases in one X)

**Comment by EmpressNael** [comment]
How does "punctuation" have anything to do with the topic? I am confused lol.

**Comment by Jparnaud** [comment]
Meh, not much now ... was more a discussion than anything on the little joke I made about the first post X)

**Comment by tsmafterlife** [comment]
at this point we are just throwing jokes around
