### ISSUE TITLE
make coffee zoom reset restore zoom after coffee is done

### ISSUE THREAD

**Issue by EmpressNael** [Monika-After-Story/MonikaModDev#3290]
I think just restoring the zoom level would fix this. - potato

=== OG POST BELOW ===

I liked to leave Monika in a certain zoom, but now with update that's been added to reset zoom on coffee dialogue, I would have to configure zoom every time it happens, I might as well not even zoom at all. I wish there was an option to disable that.

**Comment by jmwall24** [comment]
it's been doing that since coffee was instituted a few updates ago.  it has to do with the size of the empty desk sprite.

**Comment by EmpressNael** [comment]
Really? That's unfortunate, didn't know.

**Comment by EmpressNael** [comment]
Wow, thank you~

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
