### ISSUE TITLE
Christmas Gifts

### ISSUE THREAD

**Issue by Foffe123** [Monika-After-Story/MonikaModDev#3292]
Hi, I can not make the food gifts work. I know that the ribbon is for a special day. I have done Everything as i did for Monikas birthday. I put the candycane.gift for example in the char folder so idk what im doing wrong can someone please help me?

**Comment by Velius94** [comment]
I believe all of these work only during d25.

**Comment by Foffe123** [comment]
Well i have seen people making it work Before so idk :/

**Comment by tsmafterlife** [comment]
can you send me a picture of your gifts in the character folder? i think i know whats wrong but i dont want to give you false advice

**Comment by Velius94** [comment]
Tested it, works on my end.

You need to make a file with an extension .gift
Make sure you have "Show file extension" enabled. I believe you made a .txt file and added .gift by simply renaming it - this results in a file named candycane.gift.txt

**Comment by Foffe123** [comment]
Well how do i enable "show file extension" I cant find it. And if thats probs the problem cause i havent enabled anything just named the file

**Comment by Velius94** [comment]
https://www.file-extensions.org/imgs/articles/4/366/windows-10-show-file-extensions.png

I'm assuming you're using Windows. You need to tick "File name extensions" box.

**Comment by tsmafterlife** [comment]
in the end your character folder should look like this once your done
![2018-12-23 03_00_05-window](https://user-images.githubusercontent.com/43495378/50382947-fe9e7200-065e-11e9-92ed-e246b5f4f3e0.png)

**Comment by Foffe123** [comment]
Omg ty all so much it worked now! Im so happy cx so tyy

**Comment by tsmafterlife** [comment]
its what the communities for. now go enjoy yourself a good Christmas holiday

**Comment by underfa** [comment]
Hi, sorry for asking but the gifts files are available for download ? I didn't find in the MAS folder or in the site :/

**Comment by multimokia** [comment]
You make them yourself.

**Comment by underfa** [comment]
@multimokia So I just need to rename any file or  I need a specific one ?

**Comment by multimokia** [comment]
Yeah, just make sure you make it a `.gift` file when you rename it

**Comment by underfa** [comment]
Thank you :) Have a nice christmas

**Comment by Shramiro** [comment]
Ya im also having problems on the ribbon gift, excepting the other ones, i
tried gifting her a black one but i failed, so i just hope that is because
i gotta gift her that on Christmas and not another annoying error, glitch
or bug...

**Comment by multimokia** [comment]
Ribbons are only on special days i.e. big events.

**Comment by Shramiro** [comment]
Ah a'ight thanks for the info then, i guess i was right then, also idek
what i.e. meant but i guess that it means big events from what you told me,
heh, also Merry Christmas.

**Comment by multimokia** [comment]
Pretty much, yep. Merry Christmas to you as well.
