### ISSUE TITLE
[suggestion] Add a difficulty level for pong.

### ISSUE THREAD

**Issue by PremiumRares** [Monika-After-Story/MonikaModDev#3298]
The thing is, once the ball gets hit many times you cant even see where it goes. So please add the difficulty easy, medium and hard because for some people it can be hard and frustrating,

**Comment by Alucard149** [comment]
everybody has difficulty against monika, it seems until no one has won from her

**Comment by multimokia** [comment]
Nah, people have won pong against her. Even chess too. It's difficult, but it is possible

**Comment by CrocWorks** [comment]
I've only won against her 1 time in pong, but in that match every hit was at a sharp angle that bounced into the walls multiple times. The AI always moves the paddle back and forth to match the ball's location, so it can have struggle to keep up when it bounces back and forth enough. ~~It's still insanely hard to do, though...~~

**Comment by Alucard149** [comment]
I said it sounds, but it really is not impossible, even because I won it several times in pong, and in chess only 2
(sorry for the bad english)

**Comment by ThePotatoGuy** [comment]
[keeping open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as no longer in progress]
