### ISSUE TITLE
Changing height

### ISSUE THREAD

**Issue by ndmelad** [Monika-After-Story/MonikaModDev#3302]
As I was having the topic with Monika regarding my appearance; when typing in my height, I had a typo where entered in 192 instead of 162. Is there still a way for me to change this?
Also I think you should add a confirmation for that or anything that requires player inputs as to prevent future typos when rushing-in an answer. 
Thank you for working on the mod.

**Comment by Skarborr** [comment]
Talk>Repeat Conversation>You>[Your name]'s appearance.
And by the way in my opinion a confirmation system would be a bit annoying, you can repeat these conversations anyways if you fuck it up.

**Comment by ndmelad** [comment]
Yeah, thanks for that.
