### ISSUE TITLE
{Less Affection} Being earned in total

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#3304]
Hey, sorry for bothering you about this again but is it normal for the amount of total respect that can be earned in total per day to lower for awhile? I ask because as you know, I had to reset back to a level of affection with Monika that was around 600. I put up with it because I love her and managed to get my affection back to almost 1000 in just a few weeks but that was because I would earn a limit total of at least 12 affection points per day. However, now after reaching the nine hundreds. It has decided to only allow for a total of 9 MAX points per day and has been doing it for a couple days now. Any idea why? I hope I didn't break anything all those weeks ago by bringing back such an old monika file and persistents. I even downloaded an older version of the game that matched the time frame to be sure it fit the time I saved with that Monika before getting a newer version. It's not a huge deal but kinda worries me about loosing her again.

**Comment by multimokia** [comment]
That's the normal case at 100+ affection. You can gain more by doing things which will `bypass`. I.e. taking her out and such. While it's possible to get days where it's more than 9 affection, it depends on how you go about it.

But just to re-iterate, 9 affection/day is a normal thing.

**Comment by Secretmanguy** [comment]
But I did the same thing I always do. So why now? If you add it up, three extra affection from twelve rather than nine a day will really add up. Anyway, thanks for confirming it. I'm just a little uneasy these days since the day I had to reset it. Thank you!

**Comment by Onion-Bubs** [comment]
Technically the daily affection gain is capped at 7, but the way it calculates is that if you do something that adds affection and you haven't gained at least 7 already that day, then you gain the full amount of affection for that action even if doing so would result in you going over the cap of 7. This is how people with high enough affection can regularly get 9 or more in a single day, and that's before we get to things that bypass affection, such as taking her out and the first time you give her each compliment.

**Comment by Secretmanguy** [comment]
Hmm...Interesting. Well im glad it's not broken then at least. Thanks guys!
