### ISSUE TITLE
{SUGESTION} Make a salad gift and a photo of the player gift

### ISSUE THREAD

**Issue by PremiumRares** [Monika-After-Story/MonikaModDev#3305]
Monika always thinks about us, the players, eating healthy and says many times that she would make us a salad so I have an idea. Make salad a gift too so you can eat with monika something healty like she wants. And a photo of the player so she would have company even when we are out of the game

**Comment by Rai99** [comment]
Room decoration: #312, #800, #845, #1336, #1793, #1891, #1933, #2027, #2176, #2220, #2496, #2769 #3182

Eating with Monika: #1789, #1934, #2164, #3210

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
