### ISSUE TITLE
Eh.. my snow is going.. upside down?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3306]
Is it supposed to do that?

**Comment by PremiumRares** [comment]
No it is a bug. Try reopenings the game.  If the problem is not fixedit is good you said it so the developers can fix it.

**Comment by ThePotatoGuy** [comment]
It's a spaceroom, so snow there's no definitive up/down

**Comment by Akh0r** [comment]
Near a warm building the air stream may go upwards causing snow to follow it. And also...
> It's a spaceroom
Exactly my thought :D
