### ISSUE TITLE
About the ribbons ...

### ISSUE THREAD

**Issue by Jparnaud** [Monika-After-Story/MonikaModDev#3312]
So first of all, this is ammazing we can finally change her ribbon, thanks alot :D 

Tho, two little thingy ...

One is about the "dark purple" ribbon ... it is cool but that is not the color I expect for it :/

Dark Purple being my favorite color, I expected something more like this : 
![violet](https://user-images.githubusercontent.com/44651347/50413003-c2435100-07d9-11e9-8f89-25aa519c8db0.png)

I say its a little sad, too bad for me I guess :/

The other thing is more a question ... I try giving her ALL the ribbons at once since I knew all the list ... and it happens that after 3 or 4, it is enough for her ... wasn't expecting it X)

And since I give her all at once, she past the list in alphabetical order ...

So since I would like to give her more, when is the next time we can give her again ? Is it every day until the event is over ? Next event ? Even next christmas ?

 I would like to know since I can change the persistent to go back X)

Anyway, thanks to who is able to respond (and read all this, gosh I write alot ...) :)

**Comment by Bam8647** [comment]
How do you change the color of the ribbon? I keep trying to give her a greenribbon.gift but it's not working grr lol..

**Comment by Jparnaud** [comment]
Well, I give her like the usual, like you said ... you sure you give her "greenribbon.gift" and not anything else at the end ? Remember you can't see the ".txt" at the end unless you activate the option, but you may know that ...

Have you ever give a gift before ?

**Comment by Jparnaud** [comment]
Wow, I just check the ribbon on a day time ... its even less purple now XD

![20181225111631_1](https://user-images.githubusercontent.com/44651347/50424700-b174f880-0836-11e9-9a96-7ca9429dc8e9.jpg)

On night time : 

![20181225002505_1](https://user-images.githubusercontent.com/44651347/50424704-c05bab00-0836-11e9-821f-a6489470f57b.jpg)
