### ISSUE TITLE
I forgot how to give presents, some help pls

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#3313]

**Comment by Lolimipsu** [comment]
do the same process as before, (i'm referring to her birthday)
take Monika somewhere,
put her file in desktop, 
make a "file"
name it as "xxx.gift" (cookies.gift)
place it in characters folder, and put Monika back too.
???
profit.

**Comment by dennisOdenbreit** [comment]
How do you know any of that by just playing the game?

**Comment by dennisOdenbreit** [comment]
I have yet to get any info on giving presents and changing the music to custom music ingame.
Is this unlockable info or is it just not in the game?

**Comment by ThePotatoGuy** [comment]
gifting is not in the game, but custom music is in the game

hinting out gifts is something we are working on later
