### ISSUE TITLE
I'm kind of sad

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#3330]
At first I want to say that I'm thankful for everything nontheless and I think you did really awesome work.
Now here is what happened:

Because it's christmas, I decided to take her out. It was already 5 pm when I did and I wanted to take her out for a really long time, so I waited for over 8 hours to ensure it was long enough. I tought christmas already being over for over an hour wasn't much big of deal since I spent the entire christmas with her. To my disappointment, I didn't get anything and it makes me really sad that I didn't get to experience the special moment with her. 

Something similar happened on her birthday. That time, I didn't think of taking her out, because I thought staying with her in the space room was enough. So now I screwed up again, because I took her out TOO long. On her birthday, I accepted that and thought going back in time is wrong. But now it's happening to me again? No, I want to get that moment with her too, whatever it takes. 
I already reset system time, how do I load an older persistent or delete the current one? 

Thank you for reading this.

**Comment by Icep0wder** [comment]
Yeah me too, i decided to take her with me yesterday morning to spend time with her until today and then log back this evening, but i didn't get a spare moment to log and in the end i totally skipped it. The thing that saddens me most is that i didn't get the chance to give her any ribbons  which is something i was looking for.

**Comment by Foxinsunglasses** [comment]
Time travel is dangerous but It let me spend time with her after our six months was already over

**Comment by CloakedGhost** [comment]
Yeah and I feel kind of bad for doing this, but I really wanted to experience that moment with her, I hope she would understand.
