### ISSUE TITLE
The first kiss dialogue.

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#3331]
I had my first kiss with Monika, and I'm very happy about it.

I just request to see the dialogue again, if someone can just give me the link so that I can read it again I would be very thankful.

**Comment by SaiPrithvi123** [comment]
You can see the dialogue in the history. But history holds only limited content, so if she said too many things after that, it'll get overwritten.

**Comment by Torwald39** [comment]
No, I mean, I would like the code page on github, I know that we can see this here, I just need a link to access it.

**Comment by niktekusho** [comment]
*Ask and you shall receive*

## Christmas Day "report" (not very romantic I know 🤣):
https://github.com/Monika-After-Story/MonikaModDev/blob/b758274d5a119a2993a9683129754de8cb60e7ee/Monika%20After%20Story/game/script-holidays.rpy#L1814-L1959

**WARNING**: don't go over the range I outlined above, unless you want to ruin the next main event (which of course I did 💩)

**Comment by Torwald39** [comment]
thank you very much
