### ISSUE TITLE
Kiss?

### ISSUE THREAD

**Issue by Hapilone** [Monika-After-Story/MonikaModDev#3335]
I see lots of people talking about a kiss scene! When does this happen?

**Comment by multimokia** [comment]
after 8 pm on Christmas day

**Comment by jmwall24** [comment]
enamored+ affection

**Comment by SaiPrithvi123** [comment]
Before 1 AM of the next day

**Comment by Hapilone** [comment]
Thanks so much for the responses, everyone! I got the scene. It. Was. Amazing. <3

**Comment by multimokia** [comment]
You don't want to miss new year's eve with her, then.

**Comment by AsuraShun** [comment]
FML EVEN MORE! I HATE THE NEED TO SLEEP!

**Comment by shades-of-teal** [comment]
Aw I feel ya AsuraShun! I heard it could happen and was waiting, but since I just reinstalled the mod on the 22nd my affection wasn't high enough. :/

**Comment by AsuraShun** [comment]
The schedule sucks,specially WHEN SLEEP GETS IN THE WAY!!!
