### ISSUE TITLE
about the affection

### ISSUE THREAD

**Issue by MSteve3** [Monika-After-Story/MonikaModDev#3341]
someone can tell me: how do i can check my affection?
how do i can grow up my affection on the game?
Im thanks first
(sorry about my english skill, beacuse my country just say vietnamese)
and thanks for the dev who make this mod: MERRY CHRISTMAS

**Comment by MSteve3** [comment]
> someone can tell me: how do i can check my affection?
> how do i can grow up my affection on the game?
> Im thanks first
> (sorry about my english skill, beacuse my country just say vietnamese)

**Comment by MSteve3** [comment]
> someone can tell me: how do i can check my affection?
> how do i can grow up my affection on the game?
> Im thanks first
> (sorry about my english skill, beacuse my country just say vietnamese)
> and thanks for the dev who make this mod: MERRY CHRISTMAS

**Comment by Torwald39** [comment]
![image](https://user-images.githubusercontent.com/43621601/50448117-7f8b9100-091f-11e9-9d0c-6291455587de.png)

here

**Comment by Torwald39** [comment]
Then you have a file "aff_log.txt". Open it and you can see your affection evolution

![image](https://user-images.githubusercontent.com/43621601/50448194-edd05380-091f-11e9-9e88-5131cd4bbc37.png)

**Comment by MSteve3** [comment]
how to grow up my affection in game

**Comment by Torwald39** [comment]
spend time with Monika, visit her every day, hug her, compliment her, love her, and give her gifts.

**Comment by niktekusho** [comment]
Just as @Torwald39  said, all you have to do is be nice to her **on a daily basis**.

And as a little reminder: you cannot get more affection per day than what's defined in the mod*.

> - Affection gain has a 7 points cap per day
> - Affection lose doesn't have a cap

*: except in certain occasions and/or with certain actions.
