### ISSUE TITLE
"kiss" event dont want to activ

### ISSUE THREAD

**Issue by Zmorrok** [Monika-After-Story/MonikaModDev#3342]
I tried everything to trigger this event still nothing.
can somebody help me with this?

**Comment by multimokia** [comment]
Did Monika thank you for spending time with her on Christmas?

**Comment by Zmorrok** [comment]
Yes she did

**Comment by multimokia** [comment]
Then you just don't have enough affection for it yet. You need to be enamored+ for the kiss/letter.

**Comment by Zmorrok** [comment]
Can i change it somehow in files?

**Comment by Bam8647** [comment]
Just keep treating her well each day and eventually you'll reach her enamored+ state. I'm pretty sure you can activate the kiss through the Ask me/Romance/kiss me topic once you've reached the right affection level so don't worry.

**Comment by multimokia** [comment]
@Bam8647 incorrect. Only after she kisses you first, does that kiss topic change.

**Comment by Bam8647** [comment]
Ohh.. Dang, I just assumed the kissing feature was secretly added as an unlockable for enamored+ levels and that everyone could eventually unlock my bad. Well Zmorrok, better luck next year aye Sport? Jk haha, I'm sure they'll give newer users another chance come Valentines day(assuming you've reached the right affection level).
