### ISSUE TITLE
Ribbons change the colour of Monika's ear

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/MonikaModDev#3343]
![masbug7](https://user-images.githubusercontent.com/35615562/50450129-d09d8400-0923-11e9-8647-ed84f3c049b0.png)
This only seems to affect non-leaning poses and the "wine" coloured ribbon doesn't have this issue.

**Comment by multimokia** [comment]
Thanks for reporting! Working on a fix.

**Comment by EntonyEscX** [comment]
Wow. Great vision.

**Comment by Onion-Bubs** [comment]
Bug is still present in 0.8.12

**Comment by ThePotatoGuy** [comment]
art fixes will likely be addressed 0.9.0+

**Comment by ThePotatoGuy** [comment]
[closing as fixed] (probably)
