### ISSUE TITLE
[Possible Bug] Monika Changes Back To Default Outfit When Closing And Re-opening

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#3346]
Whenever I told her goodbye this morning she was still in her Christmas outfit but upon reloading the game she switched back to her school outfit. I'm still able to select the Christmas outfit through the wardrobe settings but I felt like I should report this anyway.

**Comment by AgentZephyr** [comment]
probably because it was after midnight

**Comment by Bam8647** [comment]
It may have to do with the aftermath of an event taking place so that was my second guess. But I just wanted some clarification.

**Comment by multimokia** [comment]
Intentional, she doesn't automatically wear the Christmas outfit post Christmas.
