### ISSUE TITLE
ribbons

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#3348]
I gave Monika all the ribbons you were able to on Christmas but i reopened today and none of them where there expect for the black and white ribbon

**Comment by jmwall24** [comment]
how many did she actually accept?  she would only accept 3 yesterday, even if you tried to give her all of them.

**Comment by Areaclassified** [comment]
she accepted all of them except like 3 and said maybe for another occasion. closed the game and reopened ribbons were gone and I tried giving them back because of the new update but she's saying she can't read any of them/
