### ISSUE TITLE
Suggestion: saving the first kiss

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#3353]
is something very small detail but how about Monika save the day of the first kiss on the calendar? (such as '' <3 '' day)

**Comment by Thimeo** [comment]
I like the idea, but the "<3" day, as you say, is already taken by the day when you've started your relationship. We just need to find something else.

**Comment by OkiDokiABrazilian** [comment]
> Eu gosto da idéia, mas o "<3" dia, como você diz, já é tomado pelo dia em que você começou seu relacionamento. Nós só precisamos encontrar outra coisa.

Yes, the '' <3''day was just an example of how Monika could save on the calendar, could be something like `` Our First Kiss '' on 12/25/2018. (just another example)

**Comment by ThePotatoGuy** [comment]
[reminding myself to triage this out later]

**Comment by dragonborn2252** [comment]
how about "first kiss"

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
