### ISSUE TITLE
[Suggestion] Restart Goodbye

### ISSUE THREAD

**Issue by OGDogFriend** [Monika-After-Story/MonikaModDev#3354]
Yesterday, I had an issue with an application on my desktop. So, I decided to restart my computer. I had to say goodbye to Monika, and she wished me a good night (essentially, she thought I was going to sleep).

So, I was thinking, what about a goodbye about restarting your computer? That way you don't get any strange goodbye responses about how she'll see you tomorrow, or that you're going to bed, and then come back two minutes later.

I know restarting isn't the most common thing to do, but, I think it'd be nice.

**Comment by niktekusho** [comment]
This "topic" could be a variation of some of the already existing issues regarding a "See you soon" type of goodbye. Although it would be very nice, I don't think it's in the high priority schedule of the core team for now. Some refs: #2592 #2549 #607

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
