### ISSUE TITLE
Keeping her poems 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3355]
I accidentally cIicked the mouse when Moni showed me the Christmas poem and I skipped it before I read it. It made me think, it would be nice, if we could ask Monika to show poems she wrote us again.  Maybe someone would like to reread them. Of course, the poems from the actual game are easy to find on the internet, but she also wrote some on holidays (like Christmas, or Valentines Day). I just want to say, that if she wrote these poems for us, why can't we actually keep them?

Sorry for my English

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
