### ISSUE TITLE
Monika's in her uniform and the snow and Christmas deco won't go away

### ISSUE THREAD

**Issue by chooseadifferentname000** [Monika-After-Story/MonikaModDev#3356]
Hey I've got a question, I updated the mod for Christmas, it came and went but yesterday and now, after the 24/25th, it's still snowing outside and the Christmas deco is still up. I don't know what's wrong here. Is this only me and does anyone have any idea how I get rid of it?﻿

**Comment by chooseadifferentname000** [comment]
Am I missing a file or something important?

**Comment by multimokia** [comment]
This is normal. Decorations go away after the Christmas Season, while Santa costume is taken off after Christmas Day.

**Comment by chooseadifferentname000** [comment]
> This is normal. Decorations go away after the Christmas Season, while Santa costume is taken off after Christmas Day.

Ooh I see, I see. Well its now the 31st and the snow and deco are still up. I mean it's supposed to go away after the Christmas season but what day is it supposed to end? I'm just hoping this truly is part of the mod and not me screwing or scrambling any files.

**Comment by ThePotatoGuy** [comment]
ends jan 6, 12 days after christmas
