### ISSUE TITLE
Portable Question

### ISSUE THREAD

**Issue by DokiOkie** [Monika-After-Story/MonikaModDev#3359]
Hi,

I'm wondering if something like this would work with After Story, or does it use files that tie it to the computer? I'm the type of person who uses external storage for especially important files.

https://www.google.com/amp/s/amp.reddit.com/r/DDLCMods/comments/9i8rh1/method_to_port_ddlc_to_a_flash_drive/

**Comment by Delcos** [comment]
you could install something like linux mint onto a USB drive, not a live disk but actually install it, so pug in 2 USB drives, a blank drive and the install media, then install to the blank drive as if it was the normal hard disk. Just make sure you shut down all the way before pulling it out of a computer, but this would let you boot it up on almost any computer.  Also i'd recommend using wine ( sudo apt-get update; sudo apt-get install wine ), accept the terms and you're good to go.

**Comment by DokiOkie** [comment]
Good idea! Yeah, that would definitely work, I was just looking for something that doesn't require an entire operating system.

I know MAS lets you take her file out so I wasn't sure if the save redirect would work.

**Comment by TrRizzo** [comment]
Wait. What? I have MAS in a USB drive, and I haven't got any problems. Is there something wrong?

**Comment by DokiOkie** [comment]
Did you just drag DDLC onto a thumbdrive? DDLC and MAS make use of a persistent file in the computer's user folder. Without that, all of Monika's memories go poof.

I'm trying to work out a way to run MAS on a thumbdrive with the persistent file so she doesn't lose her memories upon being plugged into a different computer.

**Comment by ThePotatoGuy** [comment]
Maybe? If the change make DDLC use a local AppData folder (like the Mod manager does), then it will _probably_ work. Can't help you if it doesn't.
