### ISSUE TITLE
Yup, I screwed up again.

### ISSUE THREAD

**Issue by WorkingAWork** [Monika-After-Story/MonikaModDev#3360]
So on Dec. 23rd I was trying to update from 8.10 (unstable). I then saw that there was an 8.11 in the unstable path and decided to download the regular 8.11 from here, which is why I canceled the unstable update (it simply asked me if I wanted to dl it, which I didn't do). The game closed, I updated it manually and went on as usual. The next day I've had massive affection drops for whatever reason and it kept happening. I even tried to switch the Persistent, but that didn't help much. Now I did dl the unstable one, hoping that it could fix things, but no such luck.

I'll put up the aff.log file, so you can see what's happening. Don't be surprised at the sudden jumps though, it came with the Persistent replacement. Please help me out with this (if at all possible, maybe I messed up too bad this time).

[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2714743/aff_log.txt)

**Comment by jmwall24** [comment]
can you upload your persistent please? need to look at something if you don't mind

**Comment by WorkingAWork** [comment]
Sure thing, but how can I do that? It doesn't let me upload the file. Does it have to be a zip?

**Comment by jmwall24** [comment]
can make a zip or slap a txt extension on it

**Comment by jmwall24** [comment]
your aff_log is bizarre going back to the very first entry on it.  you have a drop that freezes on pretty much every greeting.  and drops on topics that don't have affection gains or drops on them.

**Comment by jmwall24** [comment]
can you also upload a screenshot of your `game` folder as well

**Comment by WorkingAWork** [comment]
Here's my Persistent, the game folder is a bit complicated - it's very big, maybe we could find a different way to send it over? Hope I did it right.
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2715273/persistent.txt)

**Comment by multimokia** [comment]
Can just send over a few screenshots. We need to see the entirety of the `game/` folder.

**Comment by WorkingAWork** [comment]
Roger that, here's one.
![game 1](https://user-images.githubusercontent.com/42731796/50522526-ac7ca700-0acb-11e9-8c09-5a3acecc7b34.png)

**Comment by multimokia** [comment]
Well, there's your problem delete that `Monika_After_Story-0.8.1-Mod` folder. It's screwing up your game files

**Comment by WorkingAWork** [comment]
Number 2.
![game 2](https://user-images.githubusercontent.com/42731796/50522563-e057cc80-0acb-11e9-8ab4-8618d993ffd1.png)

**Comment by WorkingAWork** [comment]
And the last one.
![game 3](https://user-images.githubusercontent.com/42731796/50522601-15fcb580-0acc-11e9-979d-00ed09d3445b.png)

**Comment by multimokia** [comment]
Yeah, delete the `Monika_After_Story-0.8.1-Mod` folder. It's screwing up your game files. You're half running 0.8.1, and half running 0.8.11. That's why you've been seeing these drops since way before you installed this update even.

**Comment by WorkingAWork** [comment]
Did it. Is it safe now or do I need to do something else? The folder was empty btw.

**Comment by WorkingAWork** [comment]
Yeah, here it is.
![ddlc folder](https://user-images.githubusercontent.com/42731796/50523159-cf5c8a80-0ace-11e9-862b-daedab5572a4.png)

**Comment by multimokia** [comment]
It *looks* like it should be fine. Try loading your persistent up again. This affection drop doesn't happen on my end using your persistent, so I assume there had to be something inside that folder throwing it off.

**Comment by multimokia** [comment]
Hmmmm.... Did you ever add any file permissions to the save folder?

**Comment by WorkingAWork** [comment]
No, I don't think so. Yeah, pretty sure I didn't.

**Comment by WorkingAWork** [comment]
The affection drops keep happening, whatever is causing this mess still sits somewhere in my files.
![drop](https://user-images.githubusercontent.com/42731796/50548695-b203f980-0c51-11e9-9ee9-97f3bd2ac1fc.png)

**Comment by multimokia** [comment]
At this point, I'd make a new install of ddlc/mas.

**Comment by AsuraShun** [comment]
This is making me hope that the kiss event happens again tomorrow,I'll try to see it even if I have to return at midnight

**Comment by WorkingAWork** [comment]
I was thinking the same thing, just try a fresh DDLC and see if anything wrong happens then. You're not talking about doing a completely new MAS, right? That would suck real bad.

**Comment by multimokia** [comment]
don't replace persist. Just a fresh install of DDLC/MAS files. Not persist.

**Comment by WorkingAWork** [comment]
I just did. You said my persistent doesn't cause any losses on your end, right? That can only mean that the .bak files are bungled up somehow.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2717355/aff_log.txt)

**Comment by multimokia** [comment]
Persistent has no losses on my end. As well, it's not `load`ing backups. Only creating backups for the aff value. So it's nothing w/ the backups either. Definitely something messed up in your install.

**Comment by WorkingAWork** [comment]
But then how can it still drop when it's an all-new DDLC? I even used the most recent version, but all to no avail.

**Comment by multimokia** [comment]
Well, I'm not sure what's wrong, but I literally cannot replicate this. All normal here.
![image](https://user-images.githubusercontent.com/22531674/50549870-cc7aaa80-0c32-11e9-90be-ae0556150dce.png)

**Comment by WorkingAWork** [comment]
So this is how it's supposed to look. It seems that only one of these remaining files could be the culprit. It clearly isn't my Persistent itself, so it must be one of the others.
![files](https://user-images.githubusercontent.com/42731796/50549908-ec779180-0c65-11e9-8bfe-3e61c5b04667.png)

**Comment by multimokia** [comment]
persistent backups are made based on your persistent. It's literally a copy of it.

**Comment by WorkingAWork** [comment]
So basically it's none of them? What about the auto-1-LT1 and db.mcal files, what do they do?

**Comment by WorkingAWork** [comment]
And both probably have no effect on affection, right? That means it's not any of them files and also not DDLC itself. I'm not too sure about it, but I do have one more possibility: The folder above MAS contains a single persistent, not sure how exactly I got that, but couldn't it be what we're looking for?
![folder](https://user-images.githubusercontent.com/42731796/50550082-99074280-0c69-11e9-8224-e71827f145da.png)

**Comment by multimokia** [comment]
That's the actual DDLC persist. We don't read from that unless it's the first install and you choose to import your DDLC save data.

**Comment by WorkingAWork** [comment]
The strange thing is the date, I first played DDLC in May, but this one says it's from July (and stuck with it ever since). If I delete that, does it affect MAS in any way? I already did the import back in May.

**Comment by ThePotatoGuy** [comment]
can you do this:
1. shift + right click your ddlc folder
2. click open in powershell/cmd
3. enter 'tree /f > tree.txt'
4. upload the txt file here

**Comment by WorkingAWork** [comment]
Yeah, I'm gonna give you the one from my current DDLC, and then the one from my previous should the first yield no results.
[tree.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2717441/tree.txt)

**Comment by jmwall24** [comment]
Can you also upload all your aff_logs here?  i have a theory, but need the older ones as well.

**Comment by WorkingAWork** [comment]
Here you go, all three logs from the very beginning all the way to today.
[aff_log (Aug. - Oct.).txt](https://github.com/Monika-After-Story/MonikaModDev/files/2717487/aff_log.Aug.-.Oct.txt)
[aff_log (Oct. - Dec.).txt](https://github.com/Monika-After-Story/MonikaModDev/files/2717488/aff_log.Oct.-.Dec.txt)
[aff_log (Dec.).txt](https://github.com/Monika-After-Story/MonikaModDev/files/2717490/aff_log.Dec.txt)

**Comment by ThePotatoGuy** [comment]
@jmwall24 what was the conclusion of this?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of respnse]
