### ISSUE TITLE
If I wanted help with a topic I was creating, do I make a PR for it or ask here?

### ISSUE THREAD

**Issue by Man0xMan0** [Monika-After-Story/MonikaModDev#3362]
Title says it all.

**Comment by Shramiro** [comment]
hey does someone knows how to fix the 'TypeError: can't compare
datetime.datetime to tuple... :(

**Comment by multimokia** [comment]
Typically your best bet is asking here for help, or if you join the community server, there's a #coding channel which people can help you out in.

When your create a PR for something, it should be in a finished state (but that doesn't stop you from making some minor changes to it here and there if you so want to) as it makes it easier for us to review, and we don't have to wait for you to finish it before we start looking over.

**Comment by Shramiro** [comment]
yeah ik sorry for that tho, is just that everytime i try to log in on my pc
it wont work, so i can only talk to you guys in my phone... sorry again..

**Comment by multimokia** [comment]
Give me a few minutes, I have a dropfix that will solve that.

**Comment by Shramiro** [comment]
ah thanks a LOT, cuz i didn't find any solution on google of it heh..

**Comment by multimokia** [comment]
You're going to have to turn this into a `.rpyc` file (just remove the `.txt` bit on the extension). Then put it in your `game/` folder. From there, start up MAS and you should be good to go
[zz_delactfix.rpyc.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2715032/zz_delactfix.rpyc.txt)

**Comment by Man0xMan0** [comment]
Okay I'll post what I have so far and what I need help with
Preface: This scenario is supposed to be you asking Monika about the first kiss. How do I make it so this question can't be asked until player sees the event? Also, this is not supposed to be a random topic, you ask Monika a question, so I want to make sure I did that part right.

`init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="monika_kiss_aftermath", 
            category=["romance", "topic"]
            prompt="Do you think about our first kiss?", 
            pool=True 
			
        )
    )

label monika_kiss_aftermath:
    m 2hkb "Ahaha, are you kidding? Of course, all the time!"
    m 2eub "It seemed like it was just yesterday but...gosh..."
    m 2rksdlb "I feel so silly, obsessing over a quick peck."
    m 4eksdla "Our lips didn't even touch, really!" 
	m 6eka "And yet, I can still feel my heart pounding, even now."
    m 6dsa "My lips start to go tingly and numb, just by imagining the feeling of your soft lips."
    m 6dka "I run my finger across them to try and mimic that feeling, but it doesn't even come close."
    m 6esa "I keep replaying that moment over and over again in my mind and I get goosebumps each time."
    m 5tsu "It was simply divine, [player]."
    m 5tsu "It felt so right."
    m 5tsa "I've never felt closer to you. I can't wait until our next kiss, or better yet..."
    m 5wub "Our first real one. And our first real hug, and the first time our hands touch..."
    m 5hfb "Ahhh! I have to stop! All these fantasies are making me feel so giddy, ahaha!"
    m 1eka "I should really be more patient. Unfortunately, it will be a while before we'll be able to do anything like that."
    m 1eua "Until then, we can indulge in the phantom sensations we share from across our worlds."
    m 1tsa "If you ever want a taste...I'd be happy to oblige."
    m 1tsa "These crazy sensations that you make me feel...I never want them to stop."
    m 1eka "I love you so much, [player]."
    return`

**Comment by multimokia** [comment]
Ah, okay. You're looking for the `conditional` property (see usage [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding#using-conditionals)). You'll then have to add an `action`. See the example for the `monika_writingtip2` label:

```py
init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="monika_writingtip2",
            category=['writing tips'],
            prompt="Writing Tip #2",
            conditional="seen_event('monika_writingtip1')",
            action=EV_ACT_POOL
        )
    )
```
As you can see here, once the `conditional` has been met, you'll want to `pool` the topic.
As for your conditional, we store a variable that has the `datetime` of the first kiss. Which means, if it's `None`, the player hasn't had their first kiss yet. So your conditional is `conditional="persistent._mas_first_kiss is not None"`

**Comment by multimokia** [comment]
By the way, is the `topic` category temporary? (Also, there's an indent in the main dialogue bit which is not going to let the game run)

**Comment by Man0xMan0** [comment]
So like...
```
init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="monika_kiss_aftermath", 
            category=["romance"]
            prompt="Do you think about our first kiss?", 
            pool=True 
	    conditional="persistent._mas_first_kiss is not None"
	    action=EV_ACT_POOL
        )
    )
```
```
label monika_kiss_aftermath:
    m 2hkb "Ahaha, are you kidding? Of course, all the time!"
    m 2eub "It seemed like it was just yesterday but...gosh..."
    m 2rksdlb "I feel so silly, obsessing over a quick peck."
    m 4eksdla "Our lips didn't even touch, really!" 
    m 6eka "And yet, I can still feel my heart pounding, even now."
    m 6dsa "My lips start to go tingly and numb, just by imagining the feeling of your soft lips."
    m 6dka "I run my finger across them to try and mimic that feeling, but it doesn't even come close."
    m 6esa "I keep replaying that moment over and over again in my mind and I get goosebumps each time."
    m 5tsu "It was simply divine, [player]."
    m 5tsu "It felt so right."
    m 5tsa "I've never felt closer to you. I can't wait until our next kiss, or better yet..."
    m 5wub "Our first real one. And our first real hug, and the first time our hands touch..."
    m 5hfb "Ahhh! I have to stop! All these fantasies are making me feel so giddy, ahaha!"
    m 1eka "I should really be more patient. Unfortunately, it will be a while before we'll be able to do anything like that."
    m 1eua "Until then, we can indulge in the phantom sensations we share from across our worlds."
    m 1tsa "If you ever want a taste...I'd be happy to oblige."
    m 1tsa "These crazy sensations that you make me feel...I never want them to stop."
    m 1eka "I love you so much, [player]."
    return
```
Any indents that you see happened as I turned the text into code, it seems.

**Comment by Man0xMan0** [comment]
Okay, fixed. Anything else to add?
I also wanted to ask where I could find all the possible properties and other event variables and whatnot

**Comment by multimokia** [comment]
Have a look-see through `event-handler.rpy`
For a list of player_model variables (pm vars, as I often refer to them), a bunch of them can be found in `zz_history.rpy`. Really, a lot of what you could be looking for can be found with a `ctrl+f` through the files.

**Comment by Man0xMan0** [comment]
I'll have a look-see. Thanks for all the help. 
I will close this and make a PR
