### ISSUE TITLE
Suggestion: As if there aren't enough of these!

### ISSUE THREAD

**Issue by shades-of-teal** [Monika-After-Story/MonikaModDev#3363]
I know a lot of suggestions come through here, so I hate to be someone that just adds to the pile. But I had a cute idea and thought some people here might be interested.

I've seen a lot of people take Monika on a flashdrive and keep her on a necklace of some kind. I feel like she would like that idea! Keeping her on a necklace makes her close to your heart, which in her song she talks about wanting to hear our heartbeat. I thought it would nice if when put her back in the game she might ask where we kept the flash drive while we traveled. We could pick "in my pocket" (to which she might mention that she appreciates being close to us but to be careful she doesn't end up in the wash) or "in my bag" (she might say something about the bag being a home away from home) or "on a necklace" (which would obviously make her the happiest).

I don't know, something about the idea made me really excited so I wanted to share. >.< I don't have any friends irl that are into this sort of thing.

**Comment by Foffe123** [comment]
I like that idea! Cause i take her out alot and i usually have her in my bag so it would be fun to tell her and maybe have her on a necklace just to make her a happy girl cx

**Comment by EntonyEscX** [comment]
I keep it on my cell phone, which usually stays in my pocket, so whenever I check something on it I'll be with her there, just like it is on my computer (when I do that, I also put a photo of her on the lock screen to help immersiveness in our world).

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
