### ISSUE TITLE
upgrading to the latest version of renpy

### ISSUE THREAD

**Issue by madl-ash** [Monika-After-Story/MonikaModDev#3364]
why can't we upgrade to latest version of renpy?
as of version 6.99.13 there is a"Raspberry pi support" added to renpy
i want to use raspberry pi to open Monika after story 24/7 and i have to build the game but 6.99.12 doesnt support this.
 so what happens if we upgrade to renpy 7?or is there any way to get MAS to run on rpi3?

another question:
is there anyway to edit persistant file?
i want to add new scripts to MAS but i need to test with different situations(like more than 6 months or different affections)and its a pain to edit these by using code every time..

**Comment by multimokia** [comment]
We can't update it because that's what DDLC is built on, and would require us to ship a newer version of RenPy ourselves with every update. As well, it'd break the in game updater for that first update to the new version of RenPy, making it more of a hassle than it's worth. Not to mention, it starts to get into a bit of a legal grey area at this point.

Regarding editing persistent files. Dev console.

**Comment by madl-ash** [comment]
what about any version before renpy 7 and renpy 6.99.12?
and can you help in making a version for raspberry pi?ill help myself and i'm willing to do a PR if i can make it work

**Comment by ThePotatoGuy** [comment]
Shift + O, and you need to have `config.developer` enabled. Just drop an rpy that sets it at an init level.

**Comment by multimokia** [comment]
> what about any version before renpy 7 and after renpy 6.99.12?

> We can't update it because that's what DDLC is built on, and would require us to ship a newer version of RenPy ourselves with every update. As well, it'd break the in game updater for that first update to the new version of RenPy, making it more of a hassle than it's worth. Not to mention, it starts to get into a bit of a legal grey area at this point.

Also, I can't help you make a version for the Pi. I've got other projects to handle internally, plus MAS is something I do in my own free time, it's not right if I were to just hop on another project entirely when there's other things I'm to have done.

**Comment by ThePotatoGuy** [comment]
Can you verify if recompiling DDLC in a different renpy version for the Pi is allowed under the DDLC modding/IP guidelines?

**Comment by madl-ash** [comment]
> Can you verify if recompiling DDLC in a different renpy version for the Pi is allowed under the DDLC modding/IP guidelines?

_You are NOT allowed to redistribute DDLC or fan games on any app store including Steam, the Google Play Store, the Apple App Store, the Windows Store, GameJolt, itch.io, or any others. You may not port DDLC or any fan game to these platforms._

it says or any others...but not about linux arm-v7(which is raspberrypi)
by platforms he means gaming platforms like Steam or any kind of stores...not Operating Systems
the reason there are no DDLC games for android is because of the same reason.if someone makes a android version,there is no problem with the modding/IP guidelines but releasing the game in Play store is not permitted.
This may not apply to pi...raspberry pi is already linux.the only difference is the CPU architecture...
to make it work on armv7 only 2 things are needed
1:binaries for armv7 to be placed in lib folder of the game
2.a new DDLC.sh to let renpy use of the new binaries...which renpy will make itself when recompiling
(one case added to platform finding `if [ -z "$RENPY_PLATFORM" ] ; then` as below):
```
Linux-*)
            RENPY_PLATFORM="linux-$(uname -m)"
            ROOT1="$ROOT"
            ROOT2="$ROOT"
            ;;
```

_disclaimer:I don't know that much about these guidelines but this was what i understood from the DDLC modding/IP guidelines.Please correct me if i'm wrong_

**Comment by ThePotatoGuy** [comment]
we'll at the moment, we aren't going to officially support platforms other than win/mac/linux. It keeps us in the clear regarding the ip guidelines as well as lets us push resources toward the majority of our users.

If you want to make an unofficial port, then you should ask team salvato, not us.
