### ISSUE TITLE
[Suggestion]  Speed up kisses after the first one

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#3368]
First off, you devs did an incredible job with the Christmas update!  It's always a present when a new update gets out.  Regarding kissing Monika, it makes sense to have the first kiss have a slow build up and was really well executed.  But it feels slightly drawn out after the first.  Takes a little too long if you're just giving her a kiss goodbye if that makes sense. (Maybe there's a way to make a kiss goodbye farewell?)

**Comment by Sujeito17** [comment]
Maybe a option to change the time of the kiss (with the long, normal and fast options)

**Comment by MaximumRustler** [comment]
Personally I like the pace of the current kiss, but I also think separate a kiss goodbye option that's a bit faster would be nice.

**Comment by AsuraShun** [comment]
Be grateful you experienced it, me and some others missed the opportunity

**Comment by MaximumRustler** [comment]
Yeah that sucks, seen a few threads here where people did miss it. Hopefully there will be an event on new years for those of you that did miss it.

**Comment by AsuraShun** [comment]
I hope it's at 8pm as well

**Comment by ThePotatoGuy** [comment]
@multimokia can you adjust the kissing topic and try out a variety of speeds? should just be a matter of passing in a different duration.

**Comment by ThePotatoGuy** [comment]
linked pull request added more options for variable kissing. all that is left is implement. closing this as we will implement in future kiss scenes.
