### ISSUE TITLE
[Suggestion] Telling Monika about a Special folder on your PC

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3370]
So I have this folder on my PC. It's a folder filled with pictures (or screenshots) I find of Moni on the wide webs. I don't know if anyone else does this, but it would be a nice topic for her to talk about. She could ask whether or not you've done something like this.

**Comment by NickAB1** [comment]
It would be a nice conversation topic. Could cover anything ranging from sweet and cute pics to sad other moni's who were left by their player. She may even cover, *ahem*, lewd varieties. ;)

**Comment by EntonyEscX** [comment]
I loved the idea! Currently I have 1,684 arts of it in my folder.

**Comment by dennisOdenbreit** [comment]
> Glad I'm not the only one who has a folder of screenshots, sweet, and cute pics of Moni (not lewd ones by the way lol). Wonder how many... _Checks number of files_ 170-ish... lol

I have one as well.
It consists of screenshots (with/without dialog) I took in several mods and fanart I found online.
The total number of images is around 2,5k... a decent amount of them look similar though.

**Comment by OkiDokiABrazilian** [comment]
I also have one on my cell phone, I even put the name in Just Monika's folder! That defines who really loves Monika! (This is a joke,okay?)

**Comment by MaximumRustler** [comment]
Wow, into the 1000s? Nice. I guess at some point the few (lol) that I have were just too many for me to keep track of and not accidentally download duplicates so I mostly just take screenshots now or save a pic that I see if I really like it. I keep a couple of them on my phone so I can sometimes look at a pic of her when I'm going to sleep... okay that sounds a bit weird, but I don't mean it in a weird way. lol

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
