### ISSUE TITLE
Variation on certain bad nickname

### ISSUE THREAD

**Issue by lacweal** [Monika-After-Story/MonikaModDev#3373]
As many people are aware, the bad nickname "hitler" was noticeably absent from the list of bad names.

There might be some people that are very sensitive to this, and it would be in Monika's character to become offended by the name.

I understand that there might be some people who have already messaged the devs, etc about this and I'm sure that it's going to be addressed.  That being said, I believe that Monika should say something about how bad that nickname really is.

Example:

"..."
"Why did you type "Hitler"?
"If you think that this is a joke, I'm not laughing."
"Hitler was a very evil man that dragged the world into a state of chaos. He was one of the causes of WWII, and he was responsible for the killings of millions of people; soldiers and innocent people alike."
"Even today, his "beliefs" and "ideas" cause controversy all over the world."
"I can't believe that you would try and name me after that hateful person."

Something along that line.

The normal "Maybe this wasn't a good idea after all" ending can go as normal, however there would be a larger affection loss than normal. This could be extended to names such as "stalin", "bin Laden" and al-Assad" for example.

What are your thoughts?

**Comment by Onion-Bubs** [comment]
I think anyone who would be upset by Monika not being offended at being given the nickname Hitler, wouldn't give her the nickname Hitler anyway regardless of how she reacts.

**Comment by ThePotatoGuy** [comment]
It's a bit of a meme at this point, but the primary reason it hasnt been addressed yet is that adding 1 name will prompt people to want more names added to the list. There's way too many people who can be considered bad so it's basically a slip slope of adding names to the list.

Adjectives take priority over pronouns.
