### ISSUE TITLE
Clothes - Casual Clothing for Monika

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#3376]
#3174 - **UPDATED:** So, it's basically Monika's sprites in that casual outfit she used in Valentine's Day art by Satchely. I gave my best doing, I know she deserves much more than I can give, but here is my little contribution.

The sprites and accessories are all already at 2560x1700 and updated with the new MAS sprites bases.
Here is the PSD file: https://drive.google.com/drive/folders/1wcQoi8jS20sZ5mQWx_A2I5zuUXBiW3V0

![torso](https://user-images.githubusercontent.com/38970166/51340889-47d3bd00-1a77-11e9-9197-c885a15d7f52.png)
![torso-leaning](https://user-images.githubusercontent.com/38970166/51340898-4c987100-1a77-11e9-8456-cb476ae9eb5d.png)
![arms-steepling](https://user-images.githubusercontent.com/38970166/51340905-50c48e80-1a77-11e9-838a-6d8bb3394393.png)
![arms-crossed](https://user-images.githubusercontent.com/38970166/51340913-53bf7f00-1a77-11e9-8ea3-36509fbfe43c.png)
![arms-down](https://user-images.githubusercontent.com/38970166/51340919-56ba6f80-1a77-11e9-8ba1-e86ffa02628b.png)
![arms-pointright](https://user-images.githubusercontent.com/38970166/51340934-5fab4100-1a77-11e9-9731-04c751dc3bf9.png)
![arms-restleft](https://user-images.githubusercontent.com/38970166/51340946-65088b80-1a77-11e9-99be-24a0eb173c78.png)
![arms-restleftpointright](https://user-images.githubusercontent.com/38970166/51340958-6934a900-1a77-11e9-9232-394a6c7120a3.png)
![arms-peaceboth](https://user-images.githubusercontent.com/38970166/51340986-6f2a8a00-1a77-11e9-84d4-907f531d723e.png)
![arms-peaceleft](https://user-images.githubusercontent.com/38970166/51340992-72be1100-1a77-11e9-9b70-5e900d2c8113.png)
![arms-peaceright](https://user-images.githubusercontent.com/38970166/51340997-75b90180-1a77-11e9-9c9f-fb04b2edc8a9.png)
![arms-restleftpeaceright](https://user-images.githubusercontent.com/38970166/51341005-794c8880-1a77-11e9-81b4-f34029b96a84.png)
![arms-restrightpeaceleft](https://user-images.githubusercontent.com/38970166/51341009-7e113c80-1a77-11e9-8e85-03929845c97f.png)
![arms-leaning](https://user-images.githubusercontent.com/38970166/51341015-836e8700-1a77-11e9-95d5-c9cd86f73eb0.png)
![necklace](https://user-images.githubusercontent.com/38970166/51341026-88333b00-1a77-11e9-8d17-effd36ea23e7.png)
![necklace-leaning](https://user-images.githubusercontent.com/38970166/51341034-8bc6c200-1a77-11e9-9055-653722842afc.png)
![bracelet-steepling](https://user-images.githubusercontent.com/38970166/51341040-8ec1b280-1a77-11e9-8f5d-3d8e704c1438.png)
![bracelet-crossed](https://user-images.githubusercontent.com/38970166/51341043-92edd000-1a77-11e9-90fd-edd91503e63c.png)
![bracelet-point](https://user-images.githubusercontent.com/38970166/51341051-984b1a80-1a77-11e9-9054-c24797064551.png)
![bracelet-peace](https://user-images.githubusercontent.com/38970166/51341057-9bdea180-1a77-11e9-97d5-29acd2590ddf.png)
![bracelet-leaning](https://user-images.githubusercontent.com/38970166/51341064-9ed99200-1a77-11e9-8e70-c934136c3823.png)

Examples:
![example 1](https://user-images.githubusercontent.com/38970166/52166543-b52d5200-26f5-11e9-8811-4024295b7435.jpg)
![example 2](https://user-images.githubusercontent.com/38970166/52166544-b9f20600-26f5-11e9-855a-df747b66b9ea.jpg)
![example 3](https://user-images.githubusercontent.com/38970166/52166548-be1e2380-26f5-11e9-8c94-b17ec5836d2b.jpg)
![example 1 night](https://user-images.githubusercontent.com/38970166/52216763-2730a300-287e-11e9-976b-082b399d2ca1.jpg)
![example 2 night](https://user-images.githubusercontent.com/38970166/52216769-2ac42a00-287e-11e9-896b-fd34c5d9586f.jpg)
![example 3 night](https://user-images.githubusercontent.com/38970166/52216775-2dbf1a80-287e-11e9-9f63-0b4070410680.jpg)

**Comment by EntonyEscX** [comment]
@multimokia Ah, thank you. I'll do it.

**Comment by ThePotatoGuy** [comment]
some initial thoughts:
1. make the accessories a separate layer (if you have not done so already)
2. we have a base for all sprites now, I can send that to you during first week of jan, you'll need to make sure the outfit fits over the base. The base also has hair split from the body, so its **mandatory** that the outfit is separate from teh body or is separate from the hair.

**Comment by jmwall24** [comment]
First off, thanks for doing this, it looks pretty great.  My one criticism besides what has already been said is this wrinkle here.  It's in Satchely's because she is reaching so there is pull on the fabric.  In a normal pose it wouldn't be there and looks a little odd, so if you cold remove that so it looks more natural that'd be awesome.

![screenshot_83](https://user-images.githubusercontent.com/36523761/50541305-bdcbbf00-0b70-11e9-9245-4424964b4404.png)

**Comment by kaido1224** [comment]
Also the chain for the necklace is too thick compared to the actual one in the v-day outfit.

**Comment by multimokia** [comment]
Opening the PSD, it seems like the shadows for the necklace and bracelet are on a separate layer to their respective accessories themselves, if it's possible, could you put that shadow onto the same layer as those accessories?

**Comment by EntonyEscX** [comment]
First, thank you all for the compliments.
@ThePotatoGuy In the PSD file that is in the link above, the bracelet and the necklace are separate, but they are suitable for this clothing, the shadows they produce are on the same layer of the clothing itself. In order to use the clothing without the accessories, you will need a small repainting in the parts underneath them to remove the shadows they produce.
I would love to have the basis for everything. The basis I used to do this was the own school clothes sprites. The parts that are standardized on the different clothes (hands, head and hair) are also "separated" in some way from the rest of the costume in the PSD file, but I had to adjust them in a homemade way. And by the way, I'm sure the suit fits perfectly with the rings and the ribbons. 😁

@jmwall24 I had done it without that hinge at first, but then I decided to add it to make the dress more like the original costume, and give a more unique look to the clothing compared to the other costumes. I thought it would look better and more "professional" in a way with that. 😕

@kaido1224 In fact, but I thought it would be very hidden or invisible if it made it thinner. 😐

**Comment by jmwall24** [comment]
I get wanting to make it like the original, but the reason it's in the original isn't a part of this pose.  Just imo it doesn't look like there's a reason for it to be there.  There needs to be a reason for wrinkle and stretch lines.  Don't get me wrong, overall I love the job you did.  But to me, this part looks odd.

**Comment by ThePotatoGuy** [comment]
More thoughts:
1. For the accessories, take the shadows off the body and bake them into the accessory layer (or just not have the shadows at all), we want them to be complete separate layers for more versitality
2. Hair is officially being split from body, so you dont have to bake an outfit twice with both hair styles. just make the outfit neck-down, (**without any hair**), and we can add the hair pieces separately.

**Comment by MSteve3** [comment]
hey
how to add it in the game?

**Comment by ThePotatoGuy** [comment]
@EntonyEscX one more thing, we are going to use a different pose for leaning, will send you it later as psd, but it basically means the arms will be slightly different.

**Comment by ThePotatoGuy** [comment]
@EntonyEscX what is your google drive email?

**Comment by EntonyEscX** [comment]
@ThePotatoGuy Oh, really? I just did the repairs they asked me, even in the inclined pose. I came here to warn you of the update ... I even made a port to the size they wanted...
But, okay, my email is entonycamargo10@gmail.com.

**Comment by EntonyEscX** [comment]
@ThePotatoGuy I received it, and it was very beautiful! 😊
I will redo the pose for her. 🙂

**Comment by EntonyEscX** [comment]
@ThePotatoGuy Okay, I updated the leaning pose with your new version.

**Comment by jmwall24** [comment]
My specific concerns have been addressed.  Thank you and nice job.

**Comment by EntonyEscX** [comment]
Thank you, but no need to thank. Everything I do here is for her. 🙂

**Comment by ThePotatoGuy** [comment]
@EntonyEscX alright so, the the arms in the leaning pose need to be a separate layer, just as they are in the leaning base i sent you.

**Comment by EntonyEscX** [comment]
@ThePotatoGuy Yeah..., I figured there was a reason for that, but since the other leaning poses did not separate the arms from the torso, I did not even ask... 😕
I'll sort this out.

**Comment by EntonyEscX** [comment]
@ThePotatoGuy It's done. I took advantage of it and also improved the necklace. 😀

**Comment by ThePotatoGuy** [comment]
yeah, we're going to be changing all leaning poses to work with this format soon.

I'll look over the changes sometime this week.

**Comment by EntonyEscX** [comment]
Great. I loved the new leaning pose. I hope it comes soon! 😊
Thank you for saying what needed to be changed. I'm happy to help and be helpful to the existence of the mod.

**Comment by ThePotatoGuy** [comment]
We just got updated base sprites that include collarbone/cleavage lines, so yours will need to be changed to the ones that are on the base. I'm still compiling those changes into some psds, once that is done I will put them in the shared folder and let you know. Probably will happen tomorrow.

**Comment by ThePotatoGuy** [comment]
The folder currently has an updated leaning psd, but don't use it yet. We're still finalizing all the base sprites and that might take a week or more. Once we've finalized them, I'll let u know.

**Comment by EntonyEscX** [comment]
Thank you. When you are sure that everything is ready, let me know to make the adjustments.
And I will not need to redo the sloped sprite again? Just put the piece of clothing over the new skin, right?

**Comment by EntonyEscX** [comment]
@ThePotatoGuy The two bases are here. Can I upgrade the clothes sprites or will there be any other changes on these bases?

**Comment by ThePotatoGuy** [comment]
@EntonyEscX 

#3174 now has a link to the official base sprite psds.
I'm not sure if you will have to redo the leaning sprite. It has updated skin coloring and a slightly adjusted left hand, so maybe?

**Comment by EntonyEscX** [comment]
@ThePotatoGuy Right. Thank you very much.
So these are the definitive versions? I'll make the changes.

**Comment by EntonyEscX** [comment]
@ThePotatoGuy I finished updating everything, made an adjustment in the position of the leaning pose, remade the standing pose, adjusted the necklace again to suit the updated sprites and remade all the bracelets too.
The PSD file in my shared folder has also been updated.

**Comment by lunulae** [comment]
These are so beautiful, I'm absolutely amazed.
Do you have any donation or commission pages available? I would love to support you in doing more outfits like this if you wanted to!

**Comment by EntonyEscX** [comment]
@lunulae Thank you, how nice you liked it, but only the clothes, the necklace and the bracelet are my works, the skin parts, including the arms, are part of the sprites base that the MAS offers. At first I had done them too, but they did not come close to MAS's beautiful new base art.
I have nothing for supporters, but all the work I do for MAS is for Monika, I love her very much and I want to help her as best I can, so I do not have any lucrative goals here. But I would definitely love to make more clothes for her at other times.

**Comment by ThePotatoGuy** [comment]
Great work.

I'll look at it more closely this weekend, but I think it's probably ready.

**Comment by EntonyEscX** [comment]
@ThePotatoGuy Great! Thank you. If you need anything else, just let me know.

**Comment by ThePotatoGuy** [comment]
@EntonyEscX before I forget to ask, do you have a preferred link/acct to credit in release notes when this goes out?

**Comment by EntonyEscX** [comment]
@ThePotatoGuy How so? If I have a specific place to credit me? Well, as this is all exclusive to MAS, just using my GitHub profile is enough.
(I say this hoping I have correctly understood your question. My English is not very good 😐).

**Comment by ThePotatoGuy** [comment]
In the release notes we credit people who add non-code code assets. We also have a [credits wiki page](https://github.com/Monika-After-Story/MonikaModDev/wiki/Credits)

And sure we'll link the DeviantArt.

**Comment by ThePotatoGuy** [comment]
Just an fyi for future art, make sure when making boob cuts in the arm, cut into the boob a little. otherwise you end up with a thin sliver of transparency:
![armlinew](https://user-images.githubusercontent.com/3499462/51793224-97ef0580-2182-11e9-81e8-ec652ed5b012.png)

The line really only appears when the night filter is on, so thats the best way to check it.

Don't worry about fixing this for the current psd, I'm able to clean this up myself. I'm just letting you know for future ref.

**Comment by EntonyEscX** [comment]
Right. Thank you very much.
it's really hard to see those lines. You can make as many changes as you need.

**Comment by Rai99** [comment]
~~I'm really tempted to say it, but I think the meme is getting old~~

_boobs_

**Comment by ThePotatoGuy** [comment]
[closing this as completed]

**Comment by andersonantunes26** [comment]
I thank all hard work but I hope for this year ...
1-a piano on the floating island or Monika's drawing room
![yy7yjgosmln11](https://user-images.githubusercontent.com/11380696/53127167-39763680-3538-11e9-8e32-8d7599770318.jpg)
2- different hairstyles
![34998375-e8e48e22-faac-11e7-8388-e5f79e22c9f7](https://user-images.githubusercontent.com/11380696/53127254-69253e80-3538-11e9-8c47-32434150077c.png)
3-a little more movements like these and pokes na monika
![hqdefault](https://user-images.githubusercontent.com/11380696/53127447-d638d400-3538-11e9-9cbd-a2b9b20ad941.jpg)
https://i.redd.it/41q5ylgvcw301.gif
https://i.kym-cdn.com/photos/images/newsfeed/001/306/555/77b.gif

Thank you for all the work well done until this year continue like this.

**Comment by EntonyEscX** [comment]
**UPDATE:** https://drive.google.com/drive/folders/1Yy0D_2f_xspjv4PRAORG5TkYDJZ8qR7n
The clothe with the new leaning pose.

**Comment by andersonantunes26** [comment]
thanks for listening

Em sáb, 23 de fev de 2019 às 12:24, Entony Camargo <notifications@github.com>
escreveu:

**Comment by KunaiSomeone** [comment]
The drive link doesn't work anymore, is there any other way to download it?

**Comment by multimokia** [comment]
This is officially in the mod as of now. It's part of an event set. Spend Valentine's with her, there's always a little magic in the air!

**Comment by KunaiSomeone** [comment]
> This is officially in the mod as of now. It's part of an event set. Spend Valentine's with her, there's always a little magic in the air!

Ohh okay, I didn't know that. Thank you! Is there any other way to unlock the outfit before Valentine's day?
