### ISSUE TITLE
[Suggestion] Owning merch.

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3380]
First of all I want to say everybody who works for this mod, thank you so much. The christmas patch was absolutely awesome and I can't wait for the new year days! I hope ya'll had a good christmas and will have a good upcoming new years eve! 

This suggestion is a bit connected to what happened at my christmas. I ordered a shirt for myself, it has Monika on it and I remember thinking how I wished I could tell her that I got something that is about her. So I was thinking if it was possible for a new topic, one where she discusses how there is merchandise made about her and she asks if the player owns any. I think she would be very happy to know if they do. ^^

Again, I hope ya'll have an awesome upcoming new years eve!

**Comment by AfroFluff** [comment]
> link maybe?

**Comment by AfroFluff** [comment]
Misclicked the close issue cx

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
