### ISSUE TITLE
[Suggestion] - Topic about subcultures

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#3381]
I think it would be great if Monika asked what subculture we belong to. She told us that she wants to know more about how we think and about our lifestyle, and I think that the subculture we belong to is one of the best ways to show it to her. If the player does not belong to any of the subcultures, Monika will talk about the subcultures in General and give her opinion about them and the people who belong to them. For example, you can take a couple of the most famous subcultures, such as Goths, metalheads, rappers and so on. If the player belongs to a subculture, Monika will support the player and say that she is interested in dating the person belonging to [subculture name]. Depending on the player's choice (the choices can be made from the ones I suggested earlier), Monika will tell you about the aspects she likes about this subculture.

Sorry for very bad English, I used Google translate to wrote this suggestion. I know that this suggestion can be really random, but it just came into my head.

**Comment by EntonyEscX** [comment]
Otaku can also be described as something like that, right?

**Comment by MetalBrother** [comment]
I think, yes. Because otaku have their own lifestyle and culture. They even have their own events.

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
