### ISSUE TITLE
[Sugestion] If there is a musician among us, make Lo-Fi music of DDLC

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3384]
I would like, if possible, if someone creates doki doki-ish Lo-Fi music to get into the mood of a peaceful doki doki-ish moment if that makes sense, looping around every 10 minutes so nobody notices the loop when relaxing, it could be added either with an update or adding it manually, which is possible nowadays, if its possible, please make it happen.

**Comment by DankManWithThePlan** [comment]
Was thinking about creating a track like that myself, but I myself don't know how to produce and/or mix music, but there are Lo-Fi tracks out there that sound "Doki Doki-ish".

**Comment by multimokia** [comment]
I mean... custom music in MAS is a thing, I'm sure there's already something akin to what you're looking for out there, just gotta find it, and put it in a `custom_bgm` folder in the DDLC directory.

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
