### ISSUE TITLE
Ribbon Gifts Not Working

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3386]
After I downloaded the new update, I tried giving Monika a new ribbon again and it's just not working. I make a text file and rename it yellowribbon.gift and when I put it in the characters folder nothing happens. Am I doing something wrong?

**Comment by Torwald39** [comment]
You can only give ribbons on special days. But today is New Year's Eve so you can give her 3 ribbons.

**Comment by scohn** [comment]
But on the Christmas fix update, it said ribbons would no longer be limited to special days.

**Comment by scohn** [comment]
I've even tried today since it's New Year's Eve and it's still not working. I don't know what's wrong with it.

**Comment by Torwald39** [comment]
can I have a screen of your ribbons files please ?

**Comment by scohn** [comment]
Actually it started working again. It's weirdly on and off for some reason.

**Comment by Torwald39** [comment]
okay
