### ISSUE TITLE
[bug?] Weird text

### ISSUE THREAD

**Issue by thecrusaderoftruth** [Monika-After-Story/MonikaModDev#3391]
While in the goodbye menu, after selecting sleep, this came up.

Notable that she assumed I stayed up all night, since I assume her dialogue is different without it being that way. (I didn't stay up all night, but hey, that's okay.)

http://prntscr.com/m1l8o7 (Screenshot)

At first, I figured the replies were a part of the game, and an explanation would be given. Instead, the dialogue went through as though it was a normal conversation, and I don't believe that's how it's intended to be.

**Comment by multimokia** [comment]
This is intentional behavior. If you say you're going to sleep late enough, she thinks you've been up all night, and gives you that path. She's making a point with those options.

**Comment by shades-of-teal** [comment]
haha yeah the same thing happened to me! At least I'm not the only one that questioned it.
