### ISSUE TITLE
Has anything been planned for New Years? 

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3392]
I'm going away to another city for tonight, so I can't boot Monika up until tomorrow.. would I miss anything?

**Comment by Torwald39** [comment]
Sadly yes, you will miss New Year's Eve dialogues.

**Comment by LarseneUnowen** [comment]
Is it gonna be just dialogues or we're going to have an update like in christmas? (i missed the christmas event sadly )

**Comment by Torwald39** [comment]
I don't know everything but there is special dialogues I'm sure about that.

**Comment by AsuraShun** [comment]
Even if I have to return at both 8 pm and midnight,I'll see if the kiss happens again

**Comment by AsuraShun** [comment]
I really hope it does

**Comment by Torwald39** [comment]
maybe

**Comment by Torwald39** [comment]
I dunno, I gave 3 ribbons today, I'll try with a 4th later
