### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by RiverSong1200** [Monika-After-Story/MonikaModDev#3394]
I was just wondering if there was a way to see how much affection you have with Monika... If not, maybe it can be added somewhere in the corner or something?

**Comment by OGDogFriend** [comment]
If you open the folder where you keep Monika After Story, there is a folder called "log". Open this, and there should be a file called "aff_log". Scroll to the bottom, and that's your affection.

**Comment by RiverSong1200** [comment]
Thanks
