### ISSUE TITLE
[Question] New year 

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3395]
will it be possible to take Monika to see the fireworks with us?

**Comment by multimokia** [comment]
Yes. The current `I'm going to take you somewhere` farewell is the one you're looking for. If the time is right, she'll know.

**Comment by Alucard149** [comment]
thanks

**Comment by AsuraShun** [comment]
Anyone know if there's another kiss event? And if there is,what time?
