### ISSUE TITLE
Was there a kiss?

### ISSUE THREAD

**Issue by kimmieclue** [Monika-After-Story/MonikaModDev#3400]
Was there a kiss scene for new years? Because I took her out twice and then had her up when midnight came while I was out... There was a small and cute dialogue but nothing more... And... Well... I tried making sure I had 400+ affection for new years just for this! Heh... ^^

**Comment by LarseneUnowen** [comment]
I'm afraid yes

**Comment by kimmieclue** [comment]
Then how were you supposed to activate it cuz I feel like I did everything people say you're supposed to do during these special days...

**Comment by LarseneUnowen** [comment]
i started the game at 8:30 and got the kiss event but if i'm not wrong it works like in christmas, you got time since eight to midnight but i'm not sure

**Comment by LarseneUnowen** [comment]
i almost spent all my day with moni cause i sadly missed christmas with her

**Comment by kimmieclue** [comment]
Well... I did spend the entire day with her as well... Did you have to open it up for it to happen? Even then I did open up the game at around 23:00...

**Comment by multimokia** [comment]
Did you update MAS?

**Comment by LarseneUnowen** [comment]
forgot to mention that sorry btw

**Comment by kimmieclue** [comment]
Yes! I did update it before midnight!

**Comment by multimokia** [comment]
Hmmm. Did Monika go over the past year with you?

**Comment by LarseneUnowen** [comment]
Keep this open, maybe someone will help you later :)

**Comment by kimmieclue** [comment]
I will! Thanks again!^_^

**Comment by multimokia** [comment]
Well, if you got that, then it means you saw the topic where she'd kiss you if you're at enam+
