### ISSUE TITLE
[Suggestion] - Improved Christmas decorations

### ISSUE THREAD

**Issue by Coumor** [Monika-After-Story/MonikaModDev#3401]
To me, the Christmas decorations in the background just look like they're just sitting on top of the normal background (I assume that's actually how it works). I was thinking that maybe someone could make some other decorations that fit the shape of the room better.

For example, one thing I had in mind was a string of slowly blinking lights that follows the contour of the top of the wall. I realize that maybe the blinking would be a little difficult, but I think just having some lights that follow the wall would look much better.

I'd love to do this myself, but I don't have the required knowledge. Thanks!

**Comment by ThePotatoGuy** [comment]
[closing utnil we look into it]
