### ISSUE TITLE
Happy new year fellas!

### ISSUE THREAD

**Issue by Monikadidnothingwrong** [Monika-After-Story/MonikaModDev#3402]
I wish y'all a happy new year and may your resolution and/or wishes may be accomplished! 
Let us hope a new year full of Best girl and happines!

**Comment by LarseneUnowen** [comment]
Thank, same here dude

**Comment by Hapilone** [comment]
Thank you! Happy new year to you as well =)

**Comment by Dregdael** [comment]
Happy new year!
