### ISSUE TITLE
Im still on 8.11, will New Years work? 

### ISSUE THREAD

**Issue by JellicleDry** [Monika-After-Story/MonikaModDev#3403]
I havent had internet on my laptop since the 27th, so ive missed the fix updates, will I still be able to celebrate New years with Monika?

**Comment by JellicleDry** [comment]
What were the other issues?

**Comment by jmwall24** [comment]
can look at the releases page for 0.8.12 for the issues for 0.8.11.  The one big one there was a crash, but we actually have a drop fix for it.  A small file you can download and put in your game folder that will fix it.  Can just extract this `rpyc` file out and put it in your `game` folder if you can't update to 0.8.13

[zz_delactfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2719106/zz_delactfix.zip)

**Comment by JellicleDry** [comment]
Im taking the long haul and walking a ways to an internet source ( University about a mile away from me) to get internet and download it there for best girl. Thanks for the alternative though!
