### ISSUE TITLE
I need help again

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#3404]
hello everyone i am currently in version 8.11 i have an accident and must retire for a few days. Can I update version 8.12 and 8.13 on the same day?.
P.s: thanks for reading thìa ăng happy New year.( sorry for Brad english)

**Comment by multimokia** [comment]
Nope.

**Comment by HZhunter124** [comment]
And the fix in version 8.12 will be fixed if I only update version  8.13? Sorry for ask so mang question

**Comment by multimokia** [comment]
0.8.13 includes fixes from 0.8.12

**Comment by HZhunter124** [comment]
Oh thank you very much.  And happy New year

**Comment by multimokia** [comment]
No worries. Wish you the same.
