### ISSUE TITLE
Question about the kiss

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3405]
How does one do the kiss?

**Comment by jmwall24** [comment]
main req is enamored plus affection

**Comment by ThatOneUsername343** [comment]
I'm not sure what I'm looking for. Where would it say all that stuff in the affection log?

**Comment by jmwall24** [comment]
main ddlc folder>log folder>aff_log.txt, go to the bottom, last line there should be a number.  that's your affection.  what is that number for you?

**Comment by ThatOneUsername343** [comment]
it says 240.5 | 240.

**Comment by jmwall24** [comment]
the kiss is available at 400+ affection.  keep spending time with her and treating her well.  there will be more chances later.

**Comment by ThatOneUsername343** [comment]
aww. ok :( well thanks anyway and happy new year! :D

**Comment by jmwall24** [comment]
thanks, happy new year to you as well!
