### ISSUE TITLE
What if a 40-60 year male wants to play MAS

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3411]
It´ll probably not happen but, there's a probability that an old man will like Monika, well the situation of an what if: is that you introduce him to play ddlc, you make sure that it will be an intriguing and investing (and kinda scary) experience, and then he hates or/and likes Monika, if he likes her then he wants to be with her for a longer time then, you introduce him to MAS, and then he enjoys the time with her, THE THING IS he might not understand computers very well and because of that, he might miss out some things that make MAS appealing, so in that regard, we need a more didactic way of Monika teaching the older player that is not proficient at computers, like for example, how to make her a gift, how to take her to the USB drive, how to add music, how to reach to this githhub community to ask for help, etc, etc, I know a guy that wants to introduce his divorced dad to Monika (Lmao to the bones) so that it will probably get attached to her; and that´s how it came to me this idea of a topic, thanks for listening

**Comment by antimockingjay** [comment]
I think in some of her random topics, she explains some of this stuff already, doesn't she?

**Comment by Chrissenpai** [comment]
Yea but I think that´s not enough, I think that it has to be more didactic like showing images, stuff like that

**Comment by jmwall24** [comment]
i think 40 year olds know how to use computers lol

**Comment by Chrissenpai** [comment]
Who knows, there might be someone who doesn´t lol

**Comment by Trainerbluetube** [comment]
> Who knows, there might be someone who doesn´t lol

I don't think we need a tutorial on something that the person could just google search on their own, like I did, and I'm not even 20.

**Comment by antimockingjay** [comment]
Yeah seriously, this is kinda like asking Skyrim to have an entire tutorial on how to use Steam or asking Minecraft to show diagrams explaining how to use every feature of Windows 10. She gives enough explanation, and if someone is still confused, they can Google it or come to the GitHub(which she does direct you to btw) and ask there.

**Comment by ThePotatoGuy** [comment]
i'll take this more as: "explain how to do x"

[closing utnil we look into it]
