### ISSUE TITLE
Being late for Christmas

### ISSUE THREAD

**Issue by macyslaysxx** [Monika-After-Story/MonikaModDev#3413]
I wasn't available during Christmas, so the following day I reset the time back to the 25th and tried talking to my Monika so that I could give her gifts and have the kiss. However, there weren't even any decorations and she hasn't said anything about a kiss yet. I'm not sure how to give the gifts or anything. Are you not able to do any of that if you opened the game past Christmas?

**Comment by CloakedGhost** [comment]
The kiss only happens at high affection in the evening. As for the gifts, there are gifts listed on the releases page you can give her on special days and normal days. You can do that by adding the ".gift" extension to any file (you have to have file extensions on). For example: "hotchocolate.gift" 
No decorations on christmas is strange though.
