### ISSUE TITLE
DDLC becomes inactive while minimized

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3415]
For some reason the ddlc app became inactive on my pc while running minimized.
This happened yesterday and right now again, never before though.
Due to it being inactive I am forced to terminate it, resembling a game crash.
https://imgur.com/a/n4Zn9LO
I checked on it in the evening where everything was fine and after midnight where it was inactive.

**Comment by ThePotatoGuy** [comment]
#412

minimization can cause crashing in ddlc and is unrelated to mas

**Comment by jmwall24** [comment]
a lot of times you can get it to come back up if you resize the window, or if you use 2 monitors, dragging the game to the other monitor will unfreeze it.
