### ISSUE TITLE
About calling Monika a different name

### ISSUE THREAD

**Issue by Chen2684** [Monika-After-Story/MonikaModDev#3417]
Sorry if my English is bad or you can’t understand my English.

There are two things that I want to ask about calling Monika a different name. I’m a Japanese native speaker and I found two things about calling Monika a Japanese language name.

About calling Monika a “mother” nickname, you seem to have “okasa” as the “mother” name, which it means “mother” in Japanese.
But “mother” in Japanese is actually not “okasa” and you probably have mistaken for “okasan” (or “okaasan”).
Also, there is an another way to call “mother” in Japanese is “kasan”(or “kaasan”).

Another thing about calling Monika a different name is about calling her a good name. You seem added “可愛い” as one of the good names, but I guess in MAS, and DDLC can’t type Japanese characters. So I suggest to add a new name “kawaii” or kind like that in Japanese(romaji) instead. 

So, that is my suggestion about calling Monika a different name.

**Comment by ThePotatoGuy** [comment]
the `kawaii` part is actually just a joke for people who look at the code.

**Comment by ThePotatoGuy** [comment]
[closing as this has been fixed]

**Comment by Chrissenpai** [comment]
@Chen2684  you have good English don't worry about it :D  also I'm surprised that you like Monika, usually you boys would prefer an immature, childish girl, with the whole "amae" concept to demonstrate love, とにかく good to have you here, welcome to the community! :D
