### ISSUE TITLE
suggestion: options to change text font

### ISSUE THREAD

**Issue by moonstne** [Monika-After-Story/MonikaModDev#3418]
Allow us to change the text into monika's poem text. Like shown: 
https://user-images.githubusercontent.com/3181589/50620584-6190d400-0ebd-11e9-947f-61b0d577123c.png

**Comment by ThePotatoGuy** [comment]
[closing this until we look into it]

think the change wouldnt be too much, but could be a problem for longer dialogue entries. also the issue of deciding how to change the font: ui setting or direct monika question
