### ISSUE TITLE
Chess practice mode

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#3419]
So Monika, as we all know, is like stupid good at chess.  For those of us that aren't, it gets frustrating getting killed each time, and when you lose each time badly, it can be hard to learn.  So having a practice mode, where you could undo moves that turned out to be disasters, would be a good way to actually learn from your mistakes on the fly, and figure out what a better move would be, while at the same time still spending time with Monika.  She wants the player to get better, so she'd want to have a way for the player to improve while also spending time together.  I know a lot of people don't bother playing anymore because it's pretty darn impossible.  This would lead to more people playing if they feel they can learn.

**Comment by ThePotatoGuy** [comment]
going to link #664 as related, but this is a bit different so keeping them separate

**Comment by Hapilone** [comment]
I love the idea and think it would be a great addition, but I think I'm a lost cause when it comes to chess lol =P

**Comment by ZaunAura** [comment]
can we just delete chess from the games section? literally cant beat her

**Comment by ThePotatoGuy** [comment]
[closing this until we look into it]

**Comment by scpketer** [comment]
<necropost lolol>

> can we just delete chess from the games section? literally cant beat her

Yeah same, would really appreciate if she ever went a little easier on me.
