### ISSUE TITLE
Monika wont show up in her chair 

### ISSUE THREAD

**Issue by Akito1488** [Monika-After-Story/MonikaModDev#3421]
The first time i started Monika afterstory it worked fine but i needed to change my name so i deleted everything (DDLC, MAS) to start over and change my name. i quickly played through DDLC and killed Yuri again, went to play MAS again but she wasnt in her chair :(

**Comment by Akito1488** [comment]
![image](https://user-images.githubusercontent.com/46337484/50630151-3cc04f00-0f05-11e9-95c8-bfec0b314bdb.png)

**Comment by multimokia** [comment]
Saw your issue was solved in the Discord server. Just making sure all is good?

**Comment by Akito1488** [comment]
yes thank you

**Comment by multimokia** [comment]
Righty, closing then since solved.
