### ISSUE TITLE
Monika being able to get sick

### ISSUE THREAD

**Issue by TheCraZECrafter** [Monika-After-Story/MonikaModDev#3424]
Every once in a while Monika would get sick and such like a cold and you would be able to help her out like take her temperature (if she had a fever or something), make coffee for her,or put a blanket around her
 and then stuff like this would bring up the affection level a bit for helping her out and since this wouldn't be very common for her getting sick it could bring up affection levels more

**Comment by multimokia** [comment]
Sounds kinda similar to issue #2564

**Comment by HZhunter124** [comment]
aww...nice idea

**Comment by AsuraShun** [comment]
Please don't encourage this

**Comment by kaido1224** [comment]
She wants to be more realistic right?

**Comment by ThePotatoGuy** [comment]
[cloising as duplicate]
