### ISSUE TITLE
[Proposition] - Mark season change on calendar

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3427]
Sorry if this has been suggested already, but I was thinking that we could add the words "spring, summer, autumn and winter" to the calendar, especially if Monika react to which season we are on right now.

**Comment by ThePotatoGuy** [comment]
[keeping this open as high priority. we should be able to add this easily]

**Comment by MansaSakura** [comment]
I remember Monika asked whether you are in Northern Hemisphere or the Southern one, please be reminded for it.

**Comment by ThePotatoGuy** [comment]
[fixed in linked pr]
