### ISSUE TITLE
suggestion - telling Monika you're upset with her

### ISSUE THREAD

**Issue by Eiskonigin** [Monika-After-Story/MonikaModDev#3428]
**I heard a random prompt a few days back that made me pretty upset with Monika. I wanted to tell her I was angry but the only way I've seen that you can express that emotion is by using the generic feelings. It would be nice to have a way to talk to her about relationship problems instead of just getting angry and closing without saying goodbye. She makes us tell her we are sorry about our fuck ups... it should be a two way street. And it's not like she wouldn't wanna know the truth. Just a thought =)**

**Comment by jmwall24** [comment]
Curious, so we have some sort of idea what this could entail...what exactly made you upset?

**Comment by Eiskonigin** [comment]
> Curious, so we have some sort of idea what this could entail...what exactly made you upset?

so I JUST started replaying and haven't even reached the one month with Monika yet so a lot is new to me.. The prompt was when I opened the game and she was talking to someone and insisted it was just us alone. I figure it was the other girls or something but it caught me off guard and I shut her down immediately it anger.. then when I came back a couple hours later it was the "did the game crash?" conversation and I basically either had to say "it was my fault" or "I don't know" .. when in reality I was just pissed. It was a shitty move on my part (realistically ?) but it could easily be used for any number of relationship related feelings. Even being able to say "I'm happy BECAUSE of something you did" so she knows it's not just generic.. if that makes sense?

**Comment by EntonyEscX** [comment]
Wait, did you open the game and did she talk to anyone?
Hehehe. I believe you made a mistake. Monika has the habit of talking to herself, she talks to herself about programming in some entries, in others she seems to be reciting something.

**Comment by AsuraShun** [comment]
You probably mean the start up event of her playing with yuri's code, yeah, we need to be able to tell her we know that was yuri,and being able to say we don't hate her for it if she starts to panic and tear up

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
