### ISSUE TITLE
[Suggestion] - Speaking Japanese dialogue - question about native language

### ISSUE THREAD

**Issue by GOKOP** [Monika-After-Story/MonikaModDev#3432]
In the "Speaking Japanese" dialogue Monika asks you if you know any languages besides English - that would be a good moment to ask if English is even your native language, and if not, then what is. Also since this dialogue is basically Monika saying how cool Japanese is, so if your answer happens to be Japanese then she could react in some special way.

**Comment by Foxinsunglasses** [comment]
There are approximately 7099 living languages in the world so while it would be cool it is rather impractical if it was any more complex then a yes or no when it came to English being a first language

**Comment by GOKOP** [comment]
I'm not saying that she should have a unique reaction to every language, prompt to type in your native language and some generic dialogue would be fine. You know, the same way it works with your favourite music genre for example

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
