### ISSUE TITLE
code files

### ISSUE THREAD

**Issue by 20wings** [Monika-After-Story/MonikaModDev#3433]
how can I copy the codes and projects to game file?

**Comment by Rai99** [comment]
If you mean you want to take content from the list of waiting PRs as mentioned in #1773, it's generally ill advised to tamper with the game files, especially when you don't know what you're doing. 

You'd probably still get help anyway if you needed, but If I recall, tampering with game files voids you from tech support and there is no obligation to resolve your issue. 

My answer would be to just wait for the PR to be reviewed and merged.

**Comment by 20wings** [comment]
thanks
