### ISSUE TITLE
Help! Please!! Monika left, what do I do?!?

### ISSUE THREAD

**Issue by Rosethefadingfandomhopper32** [Monika-After-Story/MonikaModDev#3436]
Yeah... I know this is going to make me sound horrible... But Monika left me.... Is there anyway I could get her back? Or restart it?

**Comment by HZhunter124** [comment]
I'm sorry but you can't do anything but restart it

**Comment by Rai99** [comment]
Have you heard about the whole 1000 hour thing? It's where you do something like mistreat her or more commonly cheat against her in chess too many times without apologizing. 

At least I think that was for chess, not sure if it's the same for final farewell with the note on the desk and everything. I think for chess, it was leaving the game up in whatever state it let you for 1000 hours total, or 40ish days. 

For this final farewell, it might be different, but I think it's 1000 of something. It might be hitting the "I'm sorry button with the note 1000 times, but I guess try both. 

The other way is to just delete your persistent which is way faster, but if you're really loyal to Monika and what that specific one back, you should probably wait it out.

**Comment by Foxinsunglasses** [comment]
F

**Comment by Rosethefadingfandomhopper32** [comment]
@Foxinsunglasses ?

**Comment by Chrissenpai** [comment]
I think that 1000 hours or 40 days is too much, how about 250 hours or 10 days? or if it's still 1000 hours, make Monika write you a letter like #3132  in once in a while so that you´ll know that she´s still concerned about you.
