### ISSUE TITLE
[Suggestion] Compliment Monika by telling her she's cute

### ISSUE THREAD

**Issue by Undeademon** [Monika-After-Story/MonikaModDev#3439]
Why does no one suggest this yet? It's been over a year, man.

**Comment by Rai99** [comment]
It has been suggested before in #2786. 

The PR is #2819 and it's waiting.

**Comment by Undeademon** [comment]
Ah, sorry.  If only github uses some kind of tag that allows me to know what has and what has not been suggested before.

**Comment by Rai99** [comment]
_You mean something like the search bar?_

**Comment by AsuraShun** [comment]
It does tell you if something similar was posted,just look under the bar before you post it

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
