### ISSUE TITLE
Monika getting the hiccups

### ISSUE THREAD

**Issue by TheCraZECrafter** [Monika-After-Story/MonikaModDev#3441]
just a thing where Monika can get the hiccups every once and a while I'd think that would be adorable but just a little thing you could do

**Comment by Sujeito17** [comment]
...
Looks like I found a new fetish.

**Comment by Foxinsunglasses** [comment]
You know I wonder if she has one

**Comment by AsuraShun** [comment]
Monika would probably get it from the coffee getting in the wrong pipe,it's rare that happening though

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
