### ISSUE TITLE
Plushie/Ribbon inconsistency.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#3443]
I've noticed a bit of an inconsistency in dialogue regarding the quetzal plush.

Monika: "I bet you can't guess what sort of pet I'd like to have" 

*has plushie of pet she'd like to have*

Monika: "I can't bring myself to do something like that knowing what it's like. I'm so glad you gave me a plushie!"

As for the ribbon topic, she doesn't respond to the ribbons you give her, and despite wearing *gifts* that **you** gave to her she still states that it doesn't hold any sentimental value to her.

**Comment by ThePotatoGuy** [comment]
[keeping open as important topic issue]

**Comment by multimokia** [comment]
Closing as handled by #3596
