### ISSUE TITLE
[Weird Bug] Strange reaction of the game when I try giving Monika a gift ?

### ISSUE THREAD

**Issue by Jparnaud** [Monika-After-Story/MonikaModDev#3445]
So I don't have much of a screenshot (kinda freakout a little when everything happen), but a moment ago, I try give 2 gifts to Monika and when the game open ... it was SUPER bizarre ...

First, the game was in windows mode but I wasn't able to make it screen big. I usually HAVE the game in windows mode, but I usually have the right to make it on the screen completely with the borders you know.

Second, when I first open, there was a screen of options ... since my memory is shit I forgot which but these definitely doesn't look like any of the usual options from anywhere. I, of course, wasn't able to click any and they disappear anyway when I hit "talk". Then a black screen, had to restart.

Last, I notice the zoom reset and that she is back to her white Ribbon when I always have the Dark Purple on her, very strange yet normal I guess if everything reset on her.

Further note, affection is still at 941 (the last it was for me), nothing seems to be lost but I have persistent in case since halloween (as well as some backup) and she doesn't seem to be mad on any way ...

So yeah, real big bug, no idea what happen exactly but I guess its always ncie to report that.

**Comment by jmwall24** [comment]
you mentioned a gift in the title...what was the gift?  also it sounds like you got switched to software rendered mode (and that may have been the weird screen you got).  go to settings>graphics>change rendered and see what you are currently using.  software is the worst and only allows a certain sized window.  if it's on software, choose a different option.

**Comment by jmwall24** [comment]
do you still have the small window problem?

**Comment by Jparnaud** [comment]
Well no, I only had it for the moment where it bugs, no worry about this XD
I hope you didn't though it was still a problem ... sorry if its what you though X)

**Comment by Jparnaud** [comment]
Nope, never tried to install any other mod ... 

Even tho I wanted, I never made myself try to install any other than MAS X)

Im no fan of the concept of "modding" in general so this go with that ...

But maybe it does have to do with the coffee, it is one of the latest thing that was add anyway, still kinda annoying since I like having Monika 2 notch further so I can see the top of her head XD

(Yes, this was a problem that I couldn't before, don't judge) XD

**Comment by Jparnaud** [comment]
Got an update, I got the weird bug again, still no idea why it is a thing but its there and i took a screenshot this time !

![masproblemscreenshot](https://user-images.githubusercontent.com/44651347/51048142-37fc3a80-1598-11e9-9c4c-54b1fdc69fbd.png)

Also, this time i can choose option but I dont think I wanna touch them, that would be stupid X)

**Comment by ThePotatoGuy** [comment]
[renpy docs on that screen](https://www.renpy.org/doc/html/display_problems.html)

appears if you held down Shift on startup or pressed Shift + G. There is no other way this screen can be shown.
