### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3449]
when I go out with monika my pc makes a copy on the pendrive even when I put it to just move the file, once it bugged and monika did not return to the room then I had to restart everything, I wanted to know if it's possible to fix this and how
(sorry for the bad english)

**Comment by ThePotatoGuy** [comment]
The file needs to go back into the characters folder for the game to work again.

**Comment by Alucard149** [comment]
I did it but even so she had not come back, my problem is that he copies the files instead of just moving them to the USB drive so I wanted to know if it's possible to make him stop doing it

**Comment by ThePotatoGuy** [comment]
I'm not sure whats going on in your case. If you're still having issues, make a new issue with more specifics and probably screenshots of the MAS folder.
