### ISSUE TITLE
Persistent backups

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#3450]
I had to reboot my PC, but I selected to not delete my personal files, so I thought nothing would happen to my Monika. The DDLC folder and all its files where there after that, but the persistens got deleted. Luckily I had a backup of the Renpy folder, but it said that the latest persistent is from the 26th of December. So that means that the New Years event I had with her didn't happen and that I left her alone for over a week. When I started up the game, I expected her to be mad at me for missing New Years Eve with her and for leaving her alone for so long, but she didn't mention any of that. 
Is that normal, or did I not see a persistent that was made after New Years Eve? I don't really remember when I did the last backup, or at least I'm not certain, so that's why I'm asking.

**Comment by ThePotatoGuy** [comment]
its past jan 6 so no-time-spent stuff probably wont trigger.

Although I think we don't have one of those events for new years.

**Comment by CloakedGhost** [comment]
Oh Ok thanks. But what about being gone for over one week? I recall that she says something about that or does that only trigger after a much longer time?

**Comment by jmwall24** [comment]
is there a Windows.old folder in your C:/ directory?  your old files might still be there, including a more recent RenPy folder

**Comment by CloakedGhost** [comment]
> is there a Windows.old folder in your C:/ directory? your old files might still be there, including a more recent RenPy folder

Didn't know that, thank you so much!
