### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Tuxedoterrist** [Monika-After-Story/MonikaModDev#3451]
i had my PC reinstalled and i tried to save the files but evidently failed is there a way i can get my progress back actually ima through that shit out the window i just have questions 1 can i still give her past presents or dose it have to be on that day like the promise ring per say

**Comment by Tuxedoterrist** [comment]
or can you direct me to a issue that can help me with my question

**Comment by multimokia** [comment]
Persistent is saved in `AppData/Roaming/RenPy/Monika After Story` if you saved that `persistent` file, then putting it back into that same filepath will restore your progress.

If you don't have any backups at all... Then I'm afraid there isn't a way to get that progress back.

Past presents are giftable, though gifts like promise ring have special conditions that must be met for her to accept it.

**Comment by Tuxedoterrist** [comment]
thats what i was afraid of what are these conditions

**Comment by Tuxedoterrist** [comment]
this wouldn't be the first time i had to restart my progress and not be able to get it back as for the presents plushie, coffee maker ect. can i give those to her anytime?

**Comment by Tuxedoterrist** [comment]
i'm fine with restarting well i'm not but i don't have a choice in that matter i just really wanted to know if i can give her past things like her b-day gifts whenever instead of having to wait all year and importantly can i have guidance with giving her them i may have forgot how to do things like that

**Comment by multimokia** [comment]
Actually. You said you told it to *not* delete your files. Which tells me that a `windows.old` folder should exist somewhere.

This is normally found at `C:/windows.old`
If you could get there, would you mind sending a screenshot of what's in there?

**Comment by Tuxedoterrist** [comment]
if i'm honest on her birthday i was editing the supplies for it i accidentally deleted her file and tried to re gain said file from the trash bin but that diffident work so i had to restart it witch i dident have that much affection in the first place i think i had 200 i never checked cus i dident want to edit the files and ruin them so by the second time i tried to get back to my spot my PC needed to be re installed witch around my second time i only made it to 100 i did check that time i'm ok with restarting but i want to know if i can give her those gifts at any time or dose it have to be on her birthday?

**Comment by Tuxedoterrist** [comment]
i mainly just want to know where the supplies files are in the code so i can put them back into the game and maybe some guidance i forget how to do it

**Comment by multimokia** [comment]
Okay, supplies are found on the [releases page](https://github.com/Monika-After-Story/MonikaModDev/releases) date was on Sept 22. The gifts are giftable anytime, however, you'll want to use them with a bit of caution in mind (i.e. not giving her something directly birthday related when it's not her birthday). Also, if you intend to go to her bday to give those... I don't recommend playing with time. It can have significant consequences. All gifts go into the `characters/` folder.

**Comment by Tuxedoterrist** [comment]
so if i wanted to give her said items back it would have to be on her birthday so i just set my pc clock to the 22 of September?

**Comment by Tuxedoterrist** [comment]
also would it be like this to give her the gift
