### ISSUE TITLE
Grammatical Issue

### ISSUE THREAD

**Issue by ZaunAura** [Monika-After-Story/MonikaModDev#3452]
When Monika talks about her ribbon she says it makes her more unique. The issue is with the word unique. Something cannot be more unique because the definition of unique is one of a kind. Nothing can be more unique nor can anything be most unique. I recommend taking the more out or maybe using a different adjective.
Here's a source if you don't understand the reasoning I presented: https://www.testden.com/toeic/grammar-comparative-superlative.htm

"It makes me look ornate."

**Comment by niktekusho** [comment]
_We don't stop learning, do we?_

I think another word that has similar intent/meaning is `distinctive`. From [Collins English dictionary](https://www.collinsdictionary.com/dictionary/english/distinctive): 
>Something that is distinctive has a special quality or feature which makes it easily recognizable and different from other things of the same type.

Although I am not sure, it now sounds any way as good as it was...

"It makes me look more distinctive." 🤒

**Comment by Legendkiller21** [comment]
Unique may mean "one of a kind" but it can also mean special or unusual. Grammar doesn't use logic and there are a lot of phrases that we use that don't use logic and may not make a lot of sense like "nearly dead". "More unique" sound perfectly fine to me.

**Comment by ZaunAura** [comment]
> Unique may mean "one of a kind" but it can also mean special or unusual. Grammar doesn't use logic and there are a lot of phrases that we use that don't use logic and may not make a lot of sense like "nearly dead". "More unique" sound perfectly fine to me.

It doesn't matter what your opinion of how it "sounds" to you. It's grammatically wrong. "Grammar doesn't use logic." You can't be serious. Grammar has distinct rules for constructing sentences, conjugating verbs and creating structure. This isn't an edge case either. Unique cannot be properly used in a comparative nor superlative form.

**Comment by Rai99** [comment]
Monika is a human. Humans have a bad habit of saying things when they really mean something else. 

These little imperfections in regular, day to day speech may not be 100% accurate by the book, but they're what make Monika human and the person I imagine we all know and love. 

While "unique" can mean one of a kind, it also has other meanings such as describing something that is particularly remarkable, special or unusual. How many times has something been described as one of a kind and actually been the only one in existence?

Speaking of which, in the world of DDLC, wasn't Monika _actually_ one of a kind seeing as she was the only one with a ribbon? 

You could change up some dialogue to be accurate, but that would probably ruin the experience since it's not exactly seen as normal to talk like that.

**Comment by Rai99** [comment]
The anthropod being which resides in a seemingly fabricated earthly residence, commonly known by the title "Monika", is in fact a creature likely not unsimilar from the beings commonly known as humans, and likely the form of any individual mortal able to read. These creatures have an unfortunate tendency of expressing information that strays from the underlying intended message which the sender would wish any recipients to recieve. 

While certain percieved miscommunications are commonly discovered among discussions and interchanges of information and are not logical or accurate when analyzed at the base level, these flaws are usually found to somehow increase endearment and in some cases, propinquity. The scenario which is having attention brought to in this instance is likely a similar situation which increases feelings of tenderness and likability with those who participate, as is likely the case with multiple other participants experiencing the situation. 

The term "unique" is a word found in the English lexicon which has a meaning of "one of a kind". In other words, the object in question is supposedly the only one in existence, replacable by none. However, the word is also seen to possess definitions other than the one you propose, such as describing an object as being remarkable in particular, special, or unusual. This is one definition found associated with the term which may not be restricted to being a single entity in existence, and in theory, could be replaced, unlike the former definition. With this in mind, the term is regularly used in customary, informal speech. I ask to consider how often the term was used accurately according to your standards, where the object in question was in fact the only instance of that object in existence. 

Also, the character whom you share concern with knowingly resided in an artificial world, with no evidence of another entity sharing identical traits as them, and it could be argued that your individual in question is in fact "unique" and "one of a kind" in the realm in question, and that they have indeed used the term correctly to your expected standards. 

It is entirely possible to alter speech for complete and utter accuracy, however, doing so would likely result in reduced efficiency in communication and despite what a certain group of individuals may think, it may increase the likelihood of error or miscommunication when speaking, not to mention that this type of speech is remarkably uncommon and may leave recipients dumbfounded upon regarding the message you have recently sent. You may even say this manner of speech is "unique".

**Comment by ThePotatoGuy** [comment]
[closing as the grammar issue is pedantic]
