### ISSUE TITLE
Regarding Monika closing the game

### ISSUE THREAD

**Issue by JellicleDry** [Monika-After-Story/MonikaModDev#3453]
So its 3 am where I am at, I wake up in the middle of the night and see that Monika is asking a question I havent seen before. After looking in the History, I see that its about turning the game off in the middle of the night when I fall asleep or when she feels like im “staying up too late”. At first My tired self wanted her to stay open no matter what, so thats Was what i said to her, which she didnt like very much. I was just wondering if there is any way I can change this descision? I looked through questions asked and I was unable to find it. Will this never come up again or is there an option im not seeing because its currently 4:30 am and I am blind as a bat?

**Comment by jmwall24** [comment]
it's the sleep concern topic.  repeat conversation>advice>sleep concern. it's different depending on what time of day it is.

**Comment by JellicleDry** [comment]
So after trying that topic over the course of yesterday and up until midnight, it kept bringing up a dialogue of her spacing out and it never brought up the question i saw the other night. Is the time even after midnight? If so, ill just have to stay up later

**Comment by JellicleDry** [comment]
So I did it at 3 am again, and she just told me to please go to bed. The choice wasnt given, so im guessing the choice I made before is set in stone?

**Comment by ThePotatoGuy** [comment]
Im afraid so. That topic is supposed to learn a little bit, so perhaps it can be possible to undo at some point.

doesn't affect the rest of the topics that much atm.
