### ISSUE TITLE
[suggestion]About the conversation of instrument that I(player)play

### ISSUE THREAD

**Issue by Chen2684** [Monika-After-Story/MonikaModDev#3455]
At the "classical music" topic, Monika asks me that do I play the musical instrument, and if I answer nothing, Monika says, "I've always wanted to try the  out!""Oh!Would a duet between the  and the piano sound nice?"and it's kinda weird, so I suggest to set that the player can't answer "nothing".

Sorry for my bad English. (^_^;)

**Comment by jmwall24** [comment]
if you answered nothing, why did you say you played an instrument?

**Comment by jmwall24** [comment]
are you saying you didn't type anything at all or actually typed the word 'nothing'

**Comment by Chen2684** [comment]
I didn't type nothing.

**Comment by Chen2684** [comment]
I didn't type anything.

**Comment by ThePotatoGuy** [comment]
[keeping this open as we can easily solve this]

**Comment by multimokia** [comment]
Fixed this in new-f14 branch. Closing.
