### ISSUE TITLE
Monika's name won't change back after I picked a bad nickname

### ISSUE THREAD

**Issue by GreenPatch** [Monika-After-Story/MonikaModDev#3464]
I oofed pretty badly this time, 
I was toying around with the name change topic and after picking a bad name I got stuck with one of the previous names I picked and I can't change it back
And to top it all off the nickname I got stuck with is "Try again" and now it's been Monika's nickname for the past week or so

**Comment by FrikiHD** [comment]
Same dude :"V

**Comment by GreenPatch** [comment]
I feel your pain

**Comment by ThePotatoGuy** [comment]
[closing as this has been handled in linked issue]
