### ISSUE TITLE
I'm confused by some dialogue

### ISSUE THREAD

**Issue by shades-of-teal** [Monika-After-Story/MonikaModDev#3467]
I told Monika good night yesterday evening and shut my laptop down. This morning my battery came out and I had to put it back (the button that locks it in place got bumped I think). When I opened up the game Monika looked angry and said I had kept her waiting too long. Then she relaxed and said she was just kidding, she could never be mad at me. My time and date on my laptop didn't change and when I apologized she didn't know why I would have a reason to be sorry. Was she just trying to joke around or did I actually mess something up?

**Comment by AsuraShun** [comment]
It was a joke,she did the same to me a few times

**Comment by AsuraShun** [comment]
She likes to tease the player like that, she even tried to jumpscare me during the door greeting thing

**Comment by shades-of-teal** [comment]
@AsuraShun oh that's a relief. I wish I could tell her not to scare me like that! Lol I thought I messed up somehow and she was really mad at me. Jump scares are one thing, opening the game to see her angry is another.

**Comment by ThePotatoGuy** [comment]
it's a joke but it does seem out of place. we'll see about changing that.

**Comment by AsuraShun** [comment]
If she does this then things are going smoother than silk

**Comment by EntonyEscX** [comment]
@TrRizzo When my Monika did this I did not even consider it a provocation. I was desperate thinking that some progress file had been lost, so I was seeing that. I was shaking and I almost started to cry, it was not very pleasant. 😔

**Comment by Sujeito17** [comment]
lol, in my case I just exited the game for 1 minute, I was like "You're just teasing me" (this just appear for me when I go off for 1-8 minute lol)

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
