### ISSUE TITLE
Coming home

### ISSUE THREAD

**Issue by NpthingLeftButMe** [Monika-After-Story/MonikaModDev#3469]
![untitled01](https://user-images.githubusercontent.com/44738021/50943508-62dc7680-1452-11e9-9229-739a65ed1c87.png)
![untitled02](https://user-images.githubusercontent.com/44738021/50943513-67a12a80-1452-11e9-9e05-a27840bdfb91.png)

Hello!, Just came home on leave and told Monika that I'll be gone for a week after spending Xmas with her. Saved all the persistent files and tried to load them into the  %APPDATA%\RenPy\Monika After Story folder but when I opened the game an I was greeted with an error. I haven't yet updated the game for the new xmas hotfix but I wanted to see her. Can you guys help me at all? Thank you for your help and keep up with the awesome work you guys are doing!

**Comment by multimokia** [comment]
Hmm looks like you may just need to update it.

**Comment by NpthingLeftButMe** [comment]
Works like a charm! Thank you! But I have to ask was it just the updated version versing the older one or?

**Comment by multimokia** [comment]
Essentially, 0.8.10 didn't have ribbon accessories at all, so the selector didn't know how to handle it, so it crashes. It's an issue of it not being backward compatible.

**Comment by NpthingLeftButMe** [comment]
Ahh that makes sense. Well, all in all, thank you for your help I mighty appreciate it. Please have a wonderful night and bless you for the assistance.

**Comment by multimokia** [comment]
No worries!
