### ISSUE TITLE
[Suggestion] A topic about other characters that look like Monika

### ISSUE THREAD

**Issue by Monikadidnothingwrong** [Monika-After-Story/MonikaModDev#3470]
I think it would be interesting to know what monika thinks of look-alikes. Some examples would be Springfield from Girls Frontline and Tiramisu from Food Fantasy.
What do you guys think? Just so you know I totally confirm Springfield as Monika from the future top-tier raifu right there.

**Comment by Goooober** [comment]
I like the idea! Sounds like it would be a fun topic.

Monika also shares at least a slight resemblance to Chrisa from danganronpa. Its not quite as strong of a resemblance compared to the characters you've mentioned but the similarities are there.

**Comment by Foxinsunglasses** [comment]
The resemblance is rather uncanny

**Comment by ACoolCat** [comment]
I always thought Aerith looked like Monika.

**Comment by dennisOdenbreit** [comment]
Giffany

**Comment by Reviani** [comment]
Brigette From Overwatch...

**Comment by Dovahkun** [comment]
Whenever I see Rwby's Pyrrha, I can't help but see Monika now lmao

**Comment by softombre** [comment]
Sailor Jupiter also looks a lot like her, they even have the same hairstyle

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
