### ISSUE TITLE
About greeting_japan misspelling

### ISSUE THREAD

**Issue by Chen2684** [Monika-After-Story/MonikaModDev#3471]
There was a misspelling in label greeting_japan .
Monika is saying "Watashi ha itsumademo anata no mono desu!"
But, it should be "Watashi wa itsumademo anata no mono desu!"
I understand that it will get confused because it is the same character(hiragana)「は」but it has different reading...

**Comment by EntonyEscX** [comment]
The pronunciation is different, but the romaji will not necessarily change for that.

**Comment by Chen2684** [comment]
Yes, that could be a reason too...

**Comment by Hunter-Hikari** [comment]
Actually,
in that sort of context, は is never supposed to be read and pronounced as 'ha'. You always say it as 'wa'. So you're right, Chen-san. However, it's a common mistake beginners make, so I just thought it was a little joke.
