### ISSUE TITLE
Is there an intro that's supposed to crash?

### ISSUE THREAD

**Issue by Icep0wder** [Monika-After-Story/MonikaModDev#3472]
I just opened the game, and monika said she wanted to show me something special, and then, when she said it was "good to go", i noticed that the music wasn't set (i usually turn it off when i'm watching an episode of something or a movie, but don't always remember to put it back on) so i opened the tab to activate it and, as soon as i clicked on the track name, the game crashed. When i reopened the game immediatly after there was a new intro with monika scared and saying that she shouldn't mess with the game files. Was this all part of a special event? Or did i get an unexepctedly good dialogue fit between the greeting event and the crash event? And if this is the case, is there a possibility that i'll never be able to see the complete version of the greeting event?

**Comment by jmwall24** [comment]
hi there @Icep0wder can you give me a little more information?  if you try to play this same track now, does it crash?  also what version of MAS are you running?

**Comment by jmwall24** [comment]
also can you upload your `aff_log.txt` please?  it'll be in your `log` folder

thanks

**Comment by Icep0wder** [comment]
1) No, it doesn't seem to crash (the track was "My Feelings")
2) I'm playing on the latest stable version (v0.8.14) 
3) Of course, here it is:
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2751475/aff_log.txt)

Also, the event triggered again today, and this time it played out smoothly, although i didn't try to change the music this time

**Comment by Icep0wder** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2751591/traceback.txt)

**Comment by jmwall24** [comment]
thanks.  when it crashed the other day, did it say anything at all or just close?

**Comment by jmwall24** [comment]
also just to 100% verify, this was the islands event greeting?

**Comment by Icep0wder** [comment]
1) The game freezed for a second and then it closed; I don't remember seeing any error messages from Windows either (but I'm not completely sure since I reopened the game almost immediately and I may have closed it without noticing it if there actually was one)
2) Yes, it's that one (and on this note, I know this is not on topic but, is the scenario supposed to evolve as time goes on, or is supposed to be a one-time event? And is there a way to look at it again? I didn't find a dialogue about it in "repeat conversation")

**Comment by jmwall24** [comment]
`Ask a Question > Monika > Can you show me the floating islands?`  If it's currently snowing or raining or anything but the normal day or night sky, you're going to have to go to `Ask a Question>Weather>Can you change the weather?` and set it to default for that prompt to appear.
