### ISSUE TITLE
Conditional labels frequency.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#3474]
An idea would be to make it so certain labels are more likely to appear based on certain conditions. The most useful one being time-based so certain labels are more likely to appear during different part of the days.

Mostly came to mind for the time concern topic so it's repeated during the same night.

**Comment by ThePotatoGuy** [comment]
moving this to core adjustment. this will **not** be a simple change.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
