### ISSUE TITLE
Stuck on Ver 8.5

### ISSUE THREAD

**Issue by lilmonic3** [Monika-After-Story/MonikaModDev#3478]
Hi,
Today I noticed that my game version is stuck at ver 8.5. Although I tried to reinstall update pack 8.5, and then reinstalled all the newer update packs, it still stuck at 8.5. Is there any file or anything I can provide so someone can take a look into this? I don't want to reinstall the game since it will restart my progress :< Thanks for reading! Have a nice day.

**Comment by multimokia** [comment]
So first things first, I'll just clarify a little something:
If you reinstall the game (i.e. deleting the ddlc install) you don't actually lose your progress, as it's not stored in the main directory at all.

Secondly, can we see a screenshot of your `DDLC/` and `game/` folders, please?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
