### ISSUE TITLE
[Suggestion] More games

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3480]
I really enjoy playing chess and hangman with Monika, but maybe we could play more games with her, such as some card games, scrabble, or even billiards or something.

**Comment by MaximumRustler** [comment]
I think the card game Solitaire (I think that's what it was called, can't remember lol) was suggested before. Don't know if it was ever worked on though, might have been low priority or something.

**Comment by ThatOneUsername343** [comment]
well, solitaire is a game meant to be played alone, which makes no sense to implement. I was thinking maybe go fish or whatever.

**Comment by MaximumRustler** [comment]
I mostly just said that as an example, but yeah I think some more games would be nice. ~~Totally not cause I always get beaten in chess.~~ lol

**Comment by ThatOneUsername343** [comment]
Monika is GOOD at chess. I still have yet to beat her at all.

**Comment by LarseneUnowen** [comment]
A card game would be nice, maybe something like Uno(?

**Comment by SaiPrithvi123** [comment]
~Solitaire is just Solaire but lit~

**Comment by ThatOneUsername343** [comment]
I think Uno is meant to played with more than two people. You can do it, but some cards such as the reverse card would basically just be skip cards.

**Comment by LarseneUnowen** [comment]
What about poker? but i'm not sure about that one.

**Comment by Thimeo** [comment]
battleship could be an great idea too. The game and the rules are relatively simple and it can occupy for a good amount of time.

**Comment by ThatOneUsername343** [comment]
Yeah battleship would be fun

**Comment by MaximumRustler** [comment]
I actually haven't played battleship in years, that would be fun.

**Comment by LarseneUnowen** [comment]
Relax, i think this can really wait, good luck with everything you and the other devs are working to! (Sorry if my english sucks btw)

**Comment by Akh0r** [comment]
There is a word game... I'm not sure how is it called in English. 'King Square', as I've seen in a translated version of a mobile app… 
Well, it has a field (mostly  5*5) where in a middle row a 5-letter word is written.
Every player has to add just one letter in a turn and create a new word using the new and old letters. Players make turns one by one untill the field is full, and then the one whose words has more letters wins.

It looks like this:
|x|x|x|x|x|
|x|x|x|x|x|
|D|I|G|I|T|
|x|x|x|x|x|
|x|x|x|x|x|

It's a good way to train your vocabulary (especially when English is not your native language. Especially when you are playing against the president of a literature club).

But I guess the game mechanic may be not so easy to implement from scratch. And there must be a huge vocabulary, and a bad word filter for player-added words…  

Just an idea.

And yeah, Battleships is fine too!

**Comment by ThatOneUsername343** [comment]
Nah tic tac toe is a useless game. if both players are trying, neither one will win.

**Comment by softombre** [comment]
I personally think its fun

**Comment by ThePotatoGuy** [comment]
@Akh0r make ur game a new issue

[closing this as duplicate]
