### ISSUE TITLE
[Suggestion] Tron topic

### ISSUE THREAD

**Issue by lacweal** [Monika-After-Story/MonikaModDev#3481]
Disney released a movie called Tron in 1982 and released a sequel to it in 2010 called Tron Legacy.

In both movies, a programmer is transported into the digital world of a computer called the Grid. Computer programs are represented as humans. If you want to look into it more, check [this out](https://en.wikipedia.org/wiki/Tron).

It would be interesting if there was a topic that had Monika talking about the movies. What if we could go into our computers, find Monika and bring her out ourselves? 

There could be an emphasis on one of the characters from the sequel; her name is Quorra. A short summary is below:

"Quorra is a strong young woman and one of the Grid's greatest drivers. A digital life form that came into existence within the computer system itself, she was rescued in the Outlands by Kevin Flynn and now acts as his trusted apprentice. Her mentor's  stories about the real world beyond her virtual reality has filled Quorra with a desire to experience it for herself."

Quorra is similar to Monika because they both know of a world beyond the reality of what they know, and they both have a strong desire to get out. It is in my view that Monika would definitely have watched these movies and resonate with the ideas, characters and the reality the series is set in.

What do you think?

**Comment by lacweal** [comment]
That would be a cool separate topic!

**Comment by DankManWithThePlan** [comment]
I like this idea, as a both nerd, and an avid Tron fan

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
