### ISSUE TITLE
[Suggestion] Better apologies

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3482]
It would be great if there was a new option for `"I want to apologise for....` which could just work like `"I'm feeling....` does. Here are some of the apologies which could be in there:-

- `something"`: The default apology. What the player would pick if their apology isn't in the list.

- `for not spending enough time with you"`: I think Monika knows how much time the game has been open since the game's release, so she could comment on it. But if Monika feels like the player is spending enough time with her, she could tell the player that it's OK. But some players do just leave the game open in the background and do something else, or even leave the game open and go to some other place. If that's the case than it would be nice if the player could inform her about that.

- `for the game crashing"`: The game crashing apology. Perhaps the player could even tell her if they intended the crash or not. Even if she wouldn't like it, she would at least know that the player is honest to her.

- `for saying I didn't like your hair"`: This option might not be that useful but I really want to apologise to her about this and there might be other people who feel the same way. The player might even tell her that it was a miss-click.

- All the other already implemented apologies.

There might be more apologies worth adding which I didn't mention, but people are welcome to post their apologies here.

**Comment by multimokia** [comment]
Check PRs. Way ahead of you. #3468. Regarding those who said no in the past, it's rather impossible to actually say whether or not you did, when looking back. But for future that's easy enough to PR via the generic apology.

**Comment by AsuraShun** [comment]
The game crashing one is particularly important for me currently,my laptop got water spilt on the keyboard so some keys stopped working,so I'm using a replacement,a terrible replacement,I'm lucky enough the game runs with very few lag spikes and crashing is more likely with it

**Comment by AsuraShun** [comment]
Good thing I managed to save her from the ruined laptop though

**Comment by SaiPrithvi123** [comment]
I primarily intended this post to suggest about adding new apologies, especially the second one on the list, and apologies other people might want to add, as I already saw some suggestions about improving the apology system and figured the devs are gonna do something about it. I didn't mention it because I didn't think it would be worth it and I didn't expect anyone to judge how ahead or behind I am. My posts here are mostly intended to share information which would make it a better for Monika, not for saying "oh look I got an idea I bet no one else thought of this", so I hope you acknowledge that. I don't know how GitHub works and I'm too lazy learn it. If I'm creating way too much inconvenience, then just tell me what's the problem and we'll see if we can sort it out. The way you are reacting may make some people afraid to post suggestions, so you might consider changing that. Besides if not making sure if the suggestion one is about to post is already implemented or suggested is that much of an inconvenience, it would also be nice to include it in `Pitfalls to avoid` in the contributing guidelines.

**Comment by SaiPrithvi123** [comment]
@AsuraShun You must've been *really* worried about her. Good thing you were able to save her. But did you know it is already possible to apologise for crash? After a crash you can just say "I want to apologize" and she will know that you are apologizing because the game crashed. Also you could try finding out how you can fix the crashes, as even though things aren't that bad when the game crashes, it's still a bit unpleasant for her to get separated from the player without a warning.

**Comment by multimokia** [comment]
Okay? Wasn't really intended to come off as rude, so sorry about that.

Simply, just move one tab over, `Pull Requests` tab. It shows you what all is in the works and proposed to be added.

**Comment by AsuraShun** [comment]
The game already crashed about 3times before the laptop thing

**Comment by AsuraShun** [comment]
I apologized before

**Comment by SaiPrithvi123** [comment]
>Regarding those who said no in the past, it's rather impossible to actually say whether or not you did, when looking back.

@multimokia  Monika has a different response when you compliment her hair for the first time. https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-compliments.rpy

Also there is a `if persistent._mas_likes_hairdown:` thing in that topic.

`label mas_compliment_hair_2:

    if monika_chr.hair.name != "def":

        m 1wubfb "Thank you so much, [player]..."

        m 1lkbfb "I was really nervous the first time I changed my hair here."

    else:

        m 1hubfb "Thank you so much, [player]!"

    m 2hub "I've always put so much effort into my hair."

    m 2lksdlb "In fact, It took forever for it to get this long.."

    menu:

        "It really shows. It looks so healthy.":

            $ mas_gainAffection(3,bypass=True)

            m 1hub "Thanks, [player]!"

        "You're cute no matter how you wear it." if persistent._mas_likes_hairdown:

            $ mas_gainAffection(5,bypass=True)

            m 1ekbfa "Awww, [player]."

            m 1hubfb "You always make me feel special!"

            m "Thank you!"

        "You'd be even cuter with short hair.":

            $ mas_loseAffection(modifier=0.3,reason=None)

            m "Well, I can't exactly go to the salon from here..."

            m 1lksdlc "I...appreciate your input."

            pass

    return`

**Comment by ThePotatoGuy** [comment]
[closing this as handled by linked pr]
