### ISSUE TITLE
Full Size Default Ribbon Sprite

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#3483]
Hii! I love Monika After Story and I'd like to make some new ribbons (with patterns such as dots etc) but as mentionned in #3174 , the sprites need to be 2560x1700 pixels and in the game files they're 1280x850. Does anyone have the full size default ribbon sprite?

**Comment by kaido1224** [comment]
The ribbon sprites can be found in the mod files however i recommend waiting because some adjustments are going to be made soon that will require new sprites.

**Comment by EntonyEscX** [comment]
You can get the ribbons the size of the game and then increase the size of the image to 2560x1700 to work (if you're using Photoshop in this case), that's how I did. But if you are going to make ribbons, I recommend you wait a bit, since the leaning pose will be changed, and then the leaning ribbons will also be changed.

**Comment by softombre** [comment]
@EntonyEscX yeah that's what I wnated to do but the quality gets rlly fucked up when i increase the size like that :/
But I think I'll wait for the new sprites

**Comment by ThePotatoGuy** [comment]
Please wait a bit before doing any art. We're very very close to having a full set of base sprites people can use to make new art. I will make an announcement in #3174 and on the masc discord when its ready.

**Comment by ThePotatoGuy** [comment]
Ribbon sprites are not available yet though, will be releasing a full psd set and maybe xcf set in the near future.

**Comment by ThePotatoGuy** [comment]
probably next week.

**Comment by ThePotatoGuy** [comment]
[keeping open so I remember to do this soon]

**Comment by ThePotatoGuy** [comment]
#3174 has been updated with new ribbons xcf
