### ISSUE TITLE
[Suggestion] Monika comments if the player asks too many kisses in a short time

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3485]

**Comment by AsuraShun** [comment]
There's never enough romance!

**Comment by Chrissenpai** [comment]
That already happened, she teased me that she wouldn´t give me one, and then kissed me lol

**Comment by MaximumRustler** [comment]
Wait what? That's a thing? lol

**Comment by SaiPrithvi123** [comment]
That scared the crap out of me when it happened. I thought something went wrong.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
