### ISSUE TITLE
[Suggestion] Monika falls asleep

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3486]
When you are holding Monika, I think she should fall asleep after being held for a long time. Also, there should be a CG of you and Monika cuddling near the window watching the rain/snow.
(Also holy shit that rain is relaxing to listen to.)

**Comment by ThatMonkeyBiz** [comment]
There should also be a CG of just flat-out holding her, maybe her head is overlapping yours (the player's) in the image so you don't have to design the face. And, yes, having her fall asleep in your arms would be ADORABLE.

**Comment by ThatOneUsername343** [comment]
YES.

**Comment by Rai99** [comment]
#635, #987, #1105, #1262, #1655, #2684, #2781, #3076, #3172. 

I do have something in the works for this, but no guarantees when or if it'll be done before sleep mode possibly renders it obsolete. 

I'd imagine work is going towards vday/whiteday or any other upcoming holidays, so it probably might not happen for a little while is my guess.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

sleep/bedroom mode is the ideal solution to this. inactivity detection may also play a role. Regardless, it needs to wait.
