### ISSUE TITLE
Suggestion: Adjustment to Natsuki's Cupcakes Topic

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3487]
Whenever Monika brings up Natsuki's cupcakes she asks me if I bake but doesn't let me answer and just assumes I do. I feel like a yes or no prompt would be good here. I don't bake, but if someone answered yes then the rest of the dialogue would be the same, but if no then she could be like, "oh that's too bad, but that's okay maybe the two of us could learn together," something like that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
