### ISSUE TITLE
Coding Question - Event rules

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#3492]
I wanted to change whether or not an event is selectable.
To be more specific, I wanted to make the monday-morning greeting displayable once per day.

I found that there are rules like:
MASSelectiveRepeatRule.create_rule(weekdays=[0], hours=range(5,12))
that are used to determine whether events can be selected.

Is it possible to have custom expressions like myVar == X as an event rule?
If not is there a different possible solution to solve this problem?

**Comment by ThePotatoGuy** [comment]
greetings are getting reworked right now, i can add conditional eval to them

**Comment by ThePotatoGuy** [comment]
Although in this particular use case (show once per day), an additional piece to the greeting rule would be more appropriate.

**Comment by Groudonx** [comment]
Alright, so the possibility is not but might get implemented.
