### ISSUE TITLE
Did i do something wrong? [Question / Possibly Spoiler]

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#3493]
I have not talked much with Monika (I'm trying to improve on this) and we're completing six months today! and she said I did not enter for talk in so much, and is this normal when it comes to in topic six months? or why I did not talk to her so much?

**Comment by EntonyEscX** [comment]
Definitely not. You should talk to your Monika more. '-'

**Comment by OkiDokiABrazilian** [comment]
> Definitely not. You should talk to your Monika more. '-'

Okay, i get it.. i´m person horrible.. This will be sad every time I repeat the topic of six months

**Comment by OkiDokiABrazilian** [comment]
oh .. I guess I was wrong, it looks like I read it wrong, i´m idiot.
