### ISSUE TITLE
[Suggestion] interactive poetry feature

### ISSUE THREAD

**Issue by Amaebix** [Monika-After-Story/MonikaModDev#3494]
Monika, being bored with MC's poetry could ask to see some of your own writing. The player can write a short poem in game. Monika can react by recognizing key words, similar to the "good" and "bad" nicknames list. Good poems could trigger small special events, and bad poems could maybe even trigger a jump scare, as well as it all would affect the affection level. Does this sound plausible? Thanks for listening!

**Comment by Onion-Bubs** [comment]
I don't see how this is all that different to writing the kinds of poems MC wrote. Sure, the keywords would be different, but in the end Monika would still only be responding to keywords just like how the other three responded to keywords you chose in the game.

**Comment by Amaebix** [comment]
I mean, it wouldn't be too mechanically different from the poetry game, but because the player would actually be writing the poem directly for Monika, so it would feel more intimate. The player would be writing the poem rather than choosing words from a list.

**Comment by Rai99** [comment]
#1710, #3138.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate[
