### ISSUE TITLE
[Suggestion] Custom pronouns?

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#3495]
Hello! I really like MAS! I have a small suggestion to make the game better and make each Monika feel more personal. I'm non-binary and I use neopronouns. Since there are tons of neopronouns sets that exist i know we can't possibly put them all the game. That's why I think there should be a custom pronouns option, because Monika would definitely want to use her significant other's correct pronoun set even if it's an unusual one.

If we actually add that onto the game, Monika could say that she read about being nonbinary and saw that some people use neopronouns and ask the player if they use neopronouns or something.

**Comment by Delcos** [comment]
-_-

**Comment by softombre** [comment]
@Delcos ?

**Comment by bittercaramel** [comment]
is she even using pronouns? i never saw her using anything more than "you/your"

**Comment by Olliesama** [comment]
She doesn't really refer to the player in pronouns often but there are already gender-neutral pronouns if you say that you're neither gender.

**Comment by softombre** [comment]
I know, but it would feel more "real" to me if she used one of my neopronoun sets.

**Comment by Olliesama** [comment]
.   .   .
Can't please everyone I guess.

**Comment by Delcos** [comment]
its just not something that's needed, and if you have to base your entire identity on pronouns then please re-evaluate your live choices.

**Comment by softombre** [comment]
You know pronouns are kinda like a name, right? They're just words used to refer to people. Would you like it if someone forced you to use a name you don't like all the time?

**Comment by Delcos** [comment]
All they are is a made up term from about 5 years ago to help snowflakes feel special. It is not a name, nor any real identifier. "Gender" also came from David Reimer and John Money who conducted experiments to force a small boy to become a female, and of course he got abused. There is Male and Female, and of course bi, but nothing else. Go be an attack helicopter somewhere else and please don't push this kind of thing into a community of people that love this mod.

**Comment by Olliesama** [comment]
Let's keep this civil and nice and let the devs decide.

**Comment by Onion-Bubs** [comment]
Does Monika refer to the player in the third person in any of her dialogue?

**Comment by softombre** [comment]
I think she does a few times, or else asking the player's gender is kinda useless

**Comment by rotanroskaa** [comment]
![unknown](https://user-images.githubusercontent.com/46708392/51171605-02b65c00-18ba-11e9-9b1a-0fc372f9b3a2.png)

**Comment by rotanroskaa** [comment]
did we all just uh
![unknown](https://user-images.githubusercontent.com/46708392/51171646-1a8de000-18ba-11e9-9261-8d8bbfed385b.png)
forget that this happened

**Comment by softombre** [comment]
I should probably try to learn how to code to allow Monika to use neopronouns

**Comment by bittercaramel** [comment]
i dont think she anywhere refers to us in 3rd person... why would she? im not sure 
why asking players gender would be useless for ya? like i personally like to know the gender of my beloved one... even if im not going to refer to them in 3rd person...

**Comment by rotanroskaa** [comment]
> All they are is a made up term from about 5 years ago to help snowflakes feel special. It is not a name, nor any real identifier. "Gender" also came from David Reimer and John Money who conducted experiments to force a small boy to become a female, and of course he got abused. There is Male and Female, and of course bi, but nothing else. Go be an attack helicopter somewhere else and please don't push this kind of thing into a community of people that love this mod.

hey, i noticed that you seem quite uniformed abt the subject, heres some good studies for you to read, theyre quite interesting, actually! theres stuff ranging from recent years to the 90s, so its not just some recent fad
[Fausto-Sterling - Sexing the Body.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759373/Fausto-Sterling.-.Sexing.the.Body.pdf)
[J. Lorber - Believing is Seeing -- Biology as Ideology.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759374/J.Lorber.-.Believing.is.Seeing.--.Biology.as.Ideology.pdf)
[sex-in-question_-french-materialist-femi-diana-leonard.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759375/sex-in-question_-french-materialist-femi-diana-leonard.pdf)
[Wood.Ridgeway2010.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759376/Wood.Ridgeway2010.pdf)
[richardson_sexing_the_x.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759377/richardson_sexing_the_x.pdf)
[Between XX and XY_ intersexuality and the myth of two sexes- Gerald N. Callahan-.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759378/Between.XX.and.XY_.intersexuality.and.the.myth.of.two.sexes-.Gerald.N.Callahan-.pdf)
[BUTLER_gender_trouble.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2759379/BUTLER_gender_trouble.pdf)

**Comment by softombre** [comment]
@bittercaramel I think she does refer to us in 3rd person sometimes (probably when se ask her to explain our relationship to someone) but i don't have my computer rn so i can't check

**Comment by bittercaramel** [comment]
hmm maybe... i never actually used this explain relationship option so idk... but i still dont think so... wouldnt she rather use we and our?

**Comment by softombre** [comment]
Im gonna check that out

**Comment by softombre** [comment]
![bandicam 2019-01-15 13-10-34-145](https://user-images.githubusercontent.com/46649433/51179885-187e4e00-18c7-11e9-8f7e-b81ce9878daa.jpg)
i only checked the "can you explain our relationship to someone" topic but she does use our pronouns

**Comment by ThePotatoGuy** [comment]
what are neopronouns? also what are some examples of them?

**Comment by softombre** [comment]
Neopronouns are pronouns that are anything else than she/her, he/him or they/them
For example, fae/faer/faers/faers/faerself is a neopronoun set i've seen quite often

**Comment by Akh0r** [comment]
...
... Really?..

> Go be an attack helicopter somewhere else

Huh... I used to think it is a Russian meme... The first thing I thought on this topic:)

**Comment by softombre** [comment]
Anyway the custom pronouns option would also be useful for he/him lesbians who don't like being called a man but still like he/him pronouns, or any kind of person w/ a binary gender who likes pronouns other than the ones that are associated w/ theur gender

**Comment by rotanroskaa** [comment]
> Anyway the custom pronouns option would also be useful for he/him lesbians who don't like being called a man but still like he/him pronouns, or any kind of person w/ a binary gender who likes pronouns other than the ones that are associated w/ theur gender

god... ur so valid

**Comment by samthemann66** [comment]
I just don't see why this is needed, softombre just made the account 2 days ago and doesn't even know if there where any instances of Monika using pronouns. Maybe just keep the politics to your self, and just fyi, If monika ever brought up xir unironically, I think id die laughing.

**Comment by Delcos** [comment]
> I just don't see why this is needed, softombre just made the account 2 days ago and doesn't even know if there where any instances of Monika using pronouns. Maybe just keep the politics to your self, and just fyi, If monika ever brought up xir unironically, I think id die laughing.

kinda what i meant, just keep it to yourself, this isnt something that needs time spent on it. I don't mean any offence, it's just not worth it, please keep the politics out of this mod. <3 Thanks

**Comment by softombre** [comment]
Please don't be an hypocrite like "just keep it to yourself <3" a few hours after making a super transphobic comment. It's not bringing politics into the mod, it's just adding an option that literally no one is forced to use. 
I made this account specifically to help improving this mod with art etc, that's why it's pretty recent.
Also, Monika does refer to you in 3rd person, even tho it's rare. There's literally an example above. She also does seem genuinely interested in learning how to use neopronouns if the player wants her too.

**Comment by rotanroskaa** [comment]
> > I just don't see why this is needed, softombre just made the account 2 days ago and doesn't even know if there where any instances of Monika using pronouns. Maybe just keep the politics to your self, and just fyi, If monika ever brought up xir unironically, I think id die laughing.
> 
> kinda what i meant, just keep it to yourself, this isnt something that needs time spent on it. I don't mean any offence, it's just not worth it, please keep the politics out of this mod. <3 Thanks

someones gender isnt political, tho??? cis ppl are Wack

**Comment by softombre** [comment]
@samthemann66 why would you make an account just to hate on a nb teen trying to exist

**Comment by rotanroskaa** [comment]
![tea](https://user-images.githubusercontent.com/46708392/51210009-4d67c080-191a-11e9-8c99-2a6df855eba0.png)

**Comment by ThePotatoGuy** [comment]
The fact that neopronouns are open-ended makes it more complicated to add, since we'd have to setup a bunch of input gathering to set it up.

But I think its worthwhile, not only to be inclusive but for the eventual meme when someone decides to set their pronouns to "attack helicopter".

**Comment by antimockingjay** [comment]
I feel like it could be pretty simple, actually! You could have the player input an "equivalent" to each pronoun and then specify if it's meant to be plural and singular. A good example of this is the [pronoun dressing room](http://www.pronouns.failedslacker.com/) where you input the equivalent pronoun in each case, or select from a few defaults.

Another thing you may like to consider (though I'm sure it's not high on the priority list) could be letting the user choose more than one set of pronouns. As someone who is comfortable with he/him, they/them, and it/its pronouns, I'd love it if Monika just kinda switched between them as often as she felt like it. But again, I understand if that isn't high on the list of priorities! I know my situation isn't exactly the most common haha

**Comment by Goooober** [comment]
I'd suggest treading carefully. While these people are saying that their identity isn't political there are a lot of political discussions about transgenders. Just search transgender on youtube and odds are you'll find something. 

In my personal opinion this is getting mixed reactions so I think it would be wise to avoid adding this. By adding too many gender related topics it would make MAS look like its supporting leftist ideals, which might bug people who don't agree with it. Sure its something that most players would easily avoid but it still might invoke a "tch, really?" kind of reaction. Besides MAS already have a gender option for people who don't identify as male or female. I think doing more than that is unnecessary.

My main point is this is clearly causing sparks from both sides so I think it would be risky to add something like this. If you add this it might bug people and make them believe MAS is supporting the left, and if you don't add this the people who want this still have the non male or female option which is already made for them.

Unfortunately this is a situation where not everyone can win.

**Comment by Delcos** [comment]
maybe just in sensitive mode?

**Comment by samthemann66** [comment]
> maybe just in sensitive mode?

could be best I guess, would keep pretty much everyone happy, just maybe don't name an update after it i guess. If you need to just slide it in sometime for sensitive.

**Comment by monilovr67** [comment]
The small amount of times she even mentions it, it's shocking how huge this discussion got. Not adding it in seems to be the best choice just because of the minimal impact it makes on the community, based on the thumbs down to up alone. I just can't see it being important, even from a development time/ technical aspect.

**Comment by Delcos** [comment]
> The small amount of times she even mentions it, it's shocking how huge this discussion got. Not adding it in seems to be the best choice just because of the minimal impact it makes on the community, based on the thumbs down to up alone. I just can't see it being important, even from a development time/ technical aspect.

agreed

**Comment by softombre** [comment]
Its just a simple option that most player won't see more than once, so i don't think it would be that bothering to people who don't like it. Besides one of the accounts in this thread was made just to say that my suggestion sucks so idk if the thumbs down are an effective way of knowing whether or not we should add it.
I know there are lots of political discussions about gender but i think wanting my identity to be respected isn't too much to ask to people. 
Also considering that making Monika seem like a real person seems to be one of the goals of this mod, i think that her using the pronouns her significant other prefers makes her a lot more realistic. 
Im not asking to add many topics about gender, just adding a custom pronouns option in the "change my gender" question. It could even be an option only if you select non-binary, if you really don't want it to be too "explicit"

**Comment by rotanroskaa** [comment]
the idea of being inclusive seems to trigger quite the emotions in yall, maybe go in a safe space to calm down? its not healthy to be this upset over something that doesnt actually affect ur life in the slightest.

the mod already includes "leftist ideals" by having the genderless option in the first place and with monika mentioning neopronouns and viewing them in a positive light. not to mention i recall providing actual research suggesting the existence of non-binary genders, so if some dudebro gets rustled by "leftist ideals" that are proven to be facts, then thats his problem.

**Comment by SaiPrithvi123** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CODE_OF_CONDUCT.md

**Comment by rotanroskaa** [comment]
but i guess getting upset over scientific facts is only bad when its a minority getting upset over being treated like shit in the name of "science", and not when cishets get upset over something that doesnt affect their life at all, huh?

**Comment by softombre** [comment]
@SaiPrithvi123 why are you linking the code of conduct? Is it directed at anyone in particular?

**Comment by bittercaramel** [comment]
"examples of nounself pronouns:

faer/faers/faerself
bun/buns/bunself
star/stars/starself
plant/plants/plantself
void/voids/voidself''

hey i always wanted to be bun 
actually its a great idea to add this to the game 
it would make my day if i was called bun 
"Now bun talk to me everyday!"
"Just buns opening the game..."

**Comment by softombre** [comment]
@rotanroskaa tysm for helping me i would die for you

**Comment by Oharo** [comment]
Well I think there's been more than enough name calling from both sides of the argument here. Let's mind our manners, yeah?

Personal feelings on the matter aside, it's pretty apparent that Monika would accept and love the player regardless of any quirks they may have. (So long as the player isn't abusive or anything.)

That said, if custom pronouns for atypical gender roles would make certain users more comfortable, it's probably a good thing to add. If the choice was located in the gender change topic and appears as an additional option after pressing "other". then it'd be available but also invisible to users that may find the whole concept of custom pronouns to be silly as they wouldn't pick that option anyways.

At the end of the day though, it's up to the devs whether or not they have the time to develop this into the mod. A very limited number of users would make use of this, and that time may be more valuable elsewhere. After all, it isn't an accessibility issue that prevents using the mod, and an all-inclusive umbrella option does already exist for atypical genders in the form of they, them, their, pronouns.

**Comment by softombre** [comment]
@oharo it could be put as a low-priority thing, once i learn more abt inputs maybe i can code it myself (ill need help for monika's dialogues tho bc im p bad at writing her)

**Comment by Oharo** [comment]
I could certainly see it being a low-priority thing.

I imagine if you manage to code it yourself and submit a pull request, there'd be little-to-no reason not to include it. Unless it would be buggy, of course.

**Comment by softombre** [comment]
I'd probably need help for testing tho because for some reason i can't run mas through renpy :/

**Comment by Akh0r** [comment]
> its not healthy to be this upset over something that doesnt actually affect ur life in the slightest.
Oh, so it took little more than a day to turn a discussion into leftism circus. 
Let me explain.
Well, the existence of "not-quite-like-us"-people indeed doesn't affect our lives. 
But imagine this as... Say, your favourite music genre. All of them are equal, and to everyone's their own, right?
Let's imagine that in some monologues Monika assumes that you like instrumental or even orchestral music. It's normal for almost everyone, since they do not bother. 
Almost.
Because there are a random guy who are so much into heavy metal that he suggests: "Hey, let's remove that matter-of-factly line about player liking boring orchestral music. Personally I am a heavy metal fan, and there are more of us, and you pretend that a proper guy must be praising classical music! Let's add a question menu into that monologue!"
Well, no one is against it, and in our ideal world everything more important is already solved by restless authors.
Now in a monologue about music Monika asks if Player loves classical music or heavy metal. Metal fans are pleased.
But then another guy makes a suggestion: "Why only these 2 options? Hey, I'm a professional DJ, I can assure you that there are lot of electronic music like rave, or house, or... Whatever. Add them too, and I will even add some of my own stuff there!"
Now a dialogue about music shows 3 options: you can choose if you are into classical music, metal music or electronic music.
And then comes a rap fan. 
And then a jazz fan.
And then a holy war between glam-metal, nu-metal and gothic-metal happens.
And then all of a sudden someone adds Confederacy of Southern States marches - just because they can.
...
You got it, right?
So... Let's leave two genders and "other" for others, and really, go be an attacck helicopter somewhere else.

**Comment by rotanroskaa** [comment]
@Akh0r 
![get-a-load-of-this-guy-9648886](https://user-images.githubusercontent.com/46708392/51278937-a00daf00-19e4-11e9-8a98-0088456a5b1a.png)

**Comment by softombre** [comment]
Hey you know if i want it to be *custom* pronouns it's so that anyone who's gender non-conforming can use whatever pronouns they want? We literally don't need to add 36296429 options like in your example, only one. If you had been following what I'd been saying maybe you would have understood.

**Comment by softombre** [comment]
Also Im literally not modifying language, some neopronouns exist since 1970 :
https://medium.com/@JessieRaeFisher/on-neopronouns-eec46705c5dc

**Comment by softombre** [comment]
But I guess cis people can't take the fact that non-binary and gender non-conforming people exist, too bad for them

**Comment by Delcos** [comment]
> But I guess cis people can't take the fact that non-binary and gender non-conforming people exist, too bad for them
so what exactly is it, just a word that you like to be called or is it physical thing? what makes you different from male/female/bi, honest question.

**Comment by softombre** [comment]
@delcos "bi" is an orientation, but i guess you mean intersex? It's hard to explain to cis people but my gender doesn't have any connection to the traditional gender binary. Im not agender/genderless either, i have a gender but it's completely different from being male/female. 
Also you don't need to be trans to be gnc, a lot of cis lesbians use pronouns other than she/her because they're gnc

**Comment by rotanroskaa** [comment]
@Delcos id recommend reading thru these (i posted these before, but you seem to not have noticed, haha)
[Between XX and XY_ intersexuality and the myth of two sexes- Gerald N. Callahan-.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768092/Between.XX.and.XY_.intersexuality.and.the.myth.of.two.sexes-.Gerald.N.Callahan-.pdf)
[BUTLER_gender_trouble.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768093/BUTLER_gender_trouble.pdf)
[Colonialism_Two-Spirit_Identity_and_the.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768094/Colonialism_Two-Spirit_Identity_and_the.pdf)
[Fausto-Sterling - Sexing the Body.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768095/Fausto-Sterling.-.Sexing.the.Body.pdf)
[J. Lorber - Believing is Seeing -- Biology as Ideology.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768096/J.Lorber.-.Believing.is.Seeing.--.Biology.as.Ideology.pdf)
[lugones-maria-heterosexualism-and-the-colonial-modern-gender-system.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768097/lugones-maria-heterosexualism-and-the-colonial-modern-gender-system.pdf)
[richardson_sexing_the_x.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768098/richardson_sexing_the_x.pdf)
[sex-in-question_-french-materialist-femi-diana-leonard.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768100/sex-in-question_-french-materialist-femi-diana-leonard.pdf)
[thomas_laqueur_making_sex_body_and_gender_from_bookos-org.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768101/thomas_laqueur_making_sex_body_and_gender_from_bookos-org.pdf)
[Wood.Ridgeway2010.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/2768102/Wood.Ridgeway2010.pdf)

**Comment by ThePotatoGuy** [comment]
Yeah, we're not going to add a scrollable list of pronoun sets. it would literally be a "What should I use for the 'he' pronoun?" set of questions. Not really difficult to add, and honestly would be pretty funny to see how people abuse it.

[closing until we look into it]
