### ISSUE TITLE
[Suggestion] A theory to cover up dialogue inconsistencies

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3496]
I've been thinking about this for a while. This theory states that what the player sees on the text box isn't always what Monika meant to say. Here are two hypothetical scenarios which might be the cause:-

- Monika doesn't follow a script, so she has to manipulate the game in order to project her words into a form the player can understand, i.e. the text box. She isn't perfect at it so sometimes what she tries to say is not the exact same as what the player sees, and Monika fails to notice it sometimes. It's like when someone accidentally says something they don't mean to, except this time the error is less noticeable to both the speaker and the listener.

- The addition of MAS caused/intensified these (same as the first one, except this wasn't a problem before MAS was installed).

This would cover up some inconsistencies and typos with the mod. It would also make the additions made by MAS appeal to more people's beliefs, for example, if Monika says something a person does not believe, they can just assume that it was an error in her projecting her thoughts. If we can't give too much information we can't confirm about the stock game, then we could just go with the second scenario, where all of this started happening *after* the mod was installed.

If you consider making this a part of MAS, Monika could say something like `"There are some times when you don't see exactly what I try to tell you, and I don't notice it. It only happens rarely, and what you see isn't *that* different than what I want to say. But sometimes the smallest changes can change the meaning of the whole sentence. Don't worry though, If I find out such things, then I'll be sure to correct them."`

Note: I came up with this theory while I was trying to find a work-around for the inconsistencies, and I didn't prioritise it being correct.

My intention behind this post: To share an unrefined solution I'm aware of so that the devs can refine it or take reference from it and act it out. Or find a different solution for the same problem.

**Comment by Foxinsunglasses** [comment]
Make sense as I'm fairly certain she mentions that if she loses focus changes to the script and the game can go haywire
