### ISSUE TITLE
[Suggestion] Monika talks about the Luv(sic.) series.

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3500]
After listening to the hexalogy a couple 100 times, the songs started to sound more and more like poetry. Poetry about love, and life. The songs are also of the hip-hop genre, which is a genre that Moni likes. If you want to listen to all 6 songs, then go [here](https://www.youtube.com/watch?v=PJktY5gVIZA&t=5s). Anyways, I would like to hear Monika's analysis on some of the lyrics in some of the songs. The Luv(sic.) hexalogy seems like something she would like.

> _Song about life_

**Comment by ThePotatoGuy** [comment]
Lyric analysis might be difficult, but I am definitely for introducing more people to nujabes

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
