### ISSUE TITLE
[Bug] - Can't disable music right away on first ever session

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3501]
On a fresh persistent, right after Monika finishes her intro dialogue, trying to choose `No Music` doesn't actually do anything. Choosing any song (including `Just Monika`, which is the one that plays during the intro), then choosing `No Music` works just fine. Finishing the session and starting a new one fixes the problem as well.

**Comment by ThePotatoGuy** [comment]
[keeping open as investigation is ongoing]
