### ISSUE TITLE
[Bug] - monika_stoicism inconsistency if first ever session

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3502]
The Stoicism topic has a line that says `"I've been reading up on some ancient Greek and Roman philosophy whenever you're away, [player]."` This doesn't make sense if it's a player's first session, as they have never been away at that point.

**Comment by ThePotatoGuy** [comment]
[keeping this open as its a single line fix]

**Comment by multimokia** [comment]
Fixed in new-f14.
