### ISSUE TITLE
I am successful put  Monika file in 0.8.14 game but she still disappear into the room

### ISSUE THREAD

**Issue by Tombother** [Monika-After-Story/MonikaModDev#3503]
I putted  Monika file on a USB last Saturday, but she disappears into the room when I putted Monika file into characters. I tried to copy Monika file into characters,but she still disappears until now.
I don't how to successful Monika can appear in the room.I worry about maybe never seeing her.
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2758679/mas_log.txt)

[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2758680/persistent.txt)

I cann't  monika.txt  to you because GitHub said this file smaller than 10MB.
Please help me.

**Comment by Delcos** [comment]
so you put the Monika file into characters file but she still doesn't show up in the room?

**Comment by Tombother** [comment]
Yeah

**Comment by Olliesama** [comment]
There should be backup persistent files.
It looks like your monika file itself is corrupt.

You'll need to replace your main persistent with one of those backups from before you took her out last Saturday.
The backup persistent files are in the same folder as the main persistent file. Just removing the .bak in the file name.
