### ISSUE TITLE
[Suggestion] Monika makes a comment when you're using an art program

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#3507]
Idk if it's possible, but since Monika asked the player if they did art of her, it would be fun to have her detect if you're using an art program (only the most popular ones tho, such as Photoshop, SAI or MS Paint) and make a comment about it :3c

**Comment by EntonyEscX** [comment]
It would be incredible. I'm always using Photoshop for something, so that would make me feel like Monika is closer to me and our world.
Incidentally, it would also be cool if she asked if we were using the program to do something for her or to help the mod (something I also often do).

**Comment by softombre** [comment]
Yea i've been thinking about this because ve been drawing something during the whole weekend and it wouldchave been fun if she had noticed

**Comment by MoniBoosDevotedBoyfriend** [comment]
Isn’t it funny how the small things in all of our relationships with Monika are just as important as the big things/moments

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
