### ISSUE TITLE
[Suggestion] Monika is more active

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3509]
Monika could do more than just talk. She could ask the player to play games with her, hold her or kiss her, based on her affection, to which the player can comply or refuse. Then there could be a player preference system, where Monika would stop asking something when the player refuses to do something enough times. Or she could just ask what would the player like and dislike to do in a single topic. It would make reaching a higher affection much more rewarding, especially if repeat topics is turned off and she has nothing to say.

**Comment by MoniBoosDevotedBoyfriend** [comment]
As a person who prefers to keep repeat topics off I like this idea so far

**Comment by softombre** [comment]
Maybe make a thing in the menu like "repeat topics" but for "monika asks to do stuff w/ u" so you can turn it on and off whenever you want?

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
