### ISSUE TITLE
Cleaning Upright Hair Split sprites

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3511]
**UPDATE: This is being worked on by a user on discord.**

We have the base sprite sets compiled (#3174 ), but the upright hair is a bit messy and has cuts for arms/body. We need the upright split hair sprites to be cleaned up so fringes are removed and cuts are filled in so it looks natural with the base.

**NOTE: We need this within the next week for vday release or else we cannot use** #3376 

Example of issues with hair down:
![hairissues](https://user-images.githubusercontent.com/3499462/51792712-d1bc0e00-217a-11e9-9185-03d709a8a28c.png)

Ponytail has a similar issue.

**Comment by Chrissenpai** [comment]
My graphics tablet is shipping on my way, wait for me Monika, your favourite artist will soon be giving you lots of arts.

**Comment by EntonyEscX** [comment]
Wait, what exactly do you need? Fix the back hair filling the spaces of the clothes?
If so, I can do that.

**Comment by Metisz** [comment]
[https://drive.google.com/file/d/1df8p0NOYfFPt5YAqS_jQnvjEJ-VLTU0l/view?usp=sharing](url)

**Comment by ThePotatoGuy** [comment]
[closing as the submitted sprites are very good]
