### ISSUE TITLE
[Suggestion] Add "I'm feeling... salty" to the list of feelings

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#3512]
Because I play her in Chess and Pong far too often...

**Comment by SaiPrithvi123** [comment]
She'd never piss me off, and even if I'm pissed off because of her, I wouldn't blame her or be angry on her.

**Comment by lunulae** [comment]
This could also apply to if you're taking a break from another game.
I think she'd have some good advice for such a situation, such as making sure you're fed and hydrated before you get back to playing. Anger usually really decreases your ability to play well, in addition.

I dunno if it'd be too specific a topic to add in, but I still really like it ❤️

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
