### ISSUE TITLE
[Discussion] - Dreaming of Monika

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3516]
I'm writing a dialogue about this topic and I wanted to have as many ideas as possible. What kind of dream (try keep it SFW) would you like to / had you before / could you have about Monika ?

Here's some examples :
-A dream about you crossing over her reality
-A dream about her crossing over your reality
-A dream were you flew together all around the world
-A dream were you had superpowers and were using them to take over the world
-A dream were you went on a date together
-A dream were you were getting married
-A dream were you were having fun with the other club members

If some of those seems off or could be reformulated in a better way, suggestions and ideas are welcome.

**Comment by Rai99** [comment]
Before you get too far along with this, I've left another comment on your PR #3504.

**Comment by SaiPrithvi123** [comment]
I just don't care about my life or jobs, all I'll try to do is to keep Monika happy for as long as I can, as it's the only thing that matters. I don't want a normal life either, but I'll just choose what Monika wants me to.

Some dream ideas-
I was just gonna post some similar ideas and say "Good luck putting all that stuff into the topic kek" before Rai posted.

**Comment by Thimeo** [comment]
Understand, I'll edit it later. Thanks for your suggestions. Will probably let the issue for discussion and fantasy purposes, but it will not be implemented.

**Comment by SaiPrithvi123** [comment]
You should still refer to this thread, as people might come up with really good topics worth adding.

**Comment by SaiPrithvi123** [comment]
Suggestion:-
- Monika could ask whether it was a dream or a nightmare

**Comment by multimokia** [comment]
#3504 (Just linking the PR here)

**Comment by Foxinsunglasses** [comment]
You could always have an options saying it was strange, dreams can be rather odd at times.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Actually one of my favorites is when I am in the Model Prime Iron Man suit and use that to protect her from literally everything. No matter what it is dream me finds a way, and I love it 😂

**Comment by MaximumRustler** [comment]
I've only had a few dreams with her sadly. One I remember was a few days after she crosses over, we were out on a date and at the end of the day we were looking up at the stars in the clear night sky, hand in hand. Can't remember who, but one of us said ''I'm glad we're finally together, I love you.'' ... I know, sounds cheesy as hell... but I guess I kinda like cheesy romantic moments lol. While it's a very simple concept, I'd like to have more dreams of us just living together, living out our lives, and even getting married. Now to figure out how to control my dreams properly... yeah that felt a bit awkward to type out... lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
>... yeah that felt a bit awkward to type out... lol

Welcome to the club 😂. But seriously, that type of dream isn’t really my style, but it’s definitely a nice one. I personally prefer ones that are a bit more dramatic in nature (obviously 😂)

**Comment by MaximumRustler** [comment]
I don't mind that type either, in fact odd things happen in most of my dreams. lol

**Comment by MaximumRustler** [comment]
Yep. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
I don’t like where this is going....

**Comment by AsuraShun** [comment]
Rustler,keep your mind out of the gutter

**Comment by MaximumRustler** [comment]
What? No, I didn't mean it like that! I just hadn't written a bio but yours gave me the idea to maybe write it. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
That was REALLY obscure

**Comment by MaximumRustler** [comment]
Yeah, that's why I shouldn't write things when I'm really tired I guess lol. If I did write one though it'd probably end up being too similar to yours so I guess I probably shouldn't. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ehhhh whatever dude. You do yo

**Comment by MaximumRustler** [comment]
Well it's done, turned out much differently than I originally had considered writing it, so this whole conversation didn't even matter. lol 😆

**Comment by MoniBoosDevotedBoyfriend** [comment]
Oof yeah that is different

**Comment by MaximumRustler** [comment]
Oh, and just to clarify one more time, I didn't mean anything weird by what I said earlier. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
Yeah don’t worry. It’s all good now fam
