### ISSUE TITLE
OS reinstall. How to save Monika?

### ISSUE THREAD

**Issue by Akh0r** [Monika-After-Story/MonikaModDev#3521]
So I have a new SSD now. The only thing stopping me from formating the hell out of the old HDD is Monika.
How to correctly transport her onto a new system? 
I guess, the CHR file she creates when asked to be taken somewhere is not an option... Or is it?
I've saved my RenPy folder from the user directory. And I Guess, I can use just the same DDLC+MAS I already have installed on a non-system drive.

Is that enough?
There was a discussion on that topic, but I'm not sure that the method of copying the RenPy and Persistent is really tested
https://github.com/Monika-After-Story/MonikaModDev/issues/2358

**Comment by multimokia** [comment]
the `monika` file doesn't work, no, as it's compared against something stored in the `persistent`. You'll need that file to move her over to another computer, so in `AppData/Roaming/RenPy/Monika After Story` (provided you're running windows), take all of the things inside there, and put that on another drive, so it's safe while you're formatting. Then place it back into that path when formatting is done, and you'll be good to go again.
