### ISSUE TITLE
[Suggestion]Thank Monika for lesson, and showing interested for the lessons

### ISSUE THREAD

**Issue by MansaSakura** [Monika-After-Story/MonikaModDev#3522]
In the mod, Monika may elaborate some lesson of certain topics (as Python lesson). Teaching someone is very-chairlady, therefore I keen on the interactive of her lesson.

Firstly, there seems no way to say thank you besides 'I love you', but it seems too generic.

Second, for now, the lessons seem just Monika is elaborating things to me, she does not know really I am interested. (OK, if I am continuing on her lesson that I am interested) But I think the feeling we are really working/ learning together is important.

Third, as Monika is trying hard in learning programming, if she knows we are working together, I wonder how does she feel. If I am keeping attend her programming lesson, will she ask do I become a programmer?

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
