### ISSUE TITLE
[Suggestion] Special Reactions during Certain songs

### ISSUE THREAD

**Issue by linkone2** [Monika-After-Story/MonikaModDev#3523]
Just a Minor Suggestion. Maybe link some songs with some of the "I'm Feeling" items... like "Your Reality" could open up another choice on the "I'm Feeling" > "Sad" like where she asks if your having a bad day... it could have an additional option to say: "I'm sad about the music." > "It gives off a sad feeling." Thanks for reading my suggestion.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Your Reality gets me every goddam time 😂

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
