### ISSUE TITLE
About News and Updates in MAS' main website

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#3529]
Hello.

No, this is not related to the mod (like literally the mod that we download and use), and I'm pretty sure you'll tag this as (very) low priority, but I'm noticing something in MAS' webpage. In the **News and Updates** section, the newest version that is still listed is version 0.8.10. I know this is super unimportant, I just want to bring this to your attention in case people who only checks your main page in website doesn't know about newer version.

Thank you very much. I hope devs and all of us having a great day!

**Comment by ThePotatoGuy** [comment]
okay just updated it.
