### ISSUE TITLE
Redone leaning pose + hair fix 

### ISSUE THREAD

**Issue by MaxGreenKiki** [Monika-After-Story/MonikaModDev#3530]
I edit the shadows on a hair so that it looks good now and similar to default + i add some shadow overall 
(on shirt, bow and right hand) + added a missing button on her arm which for some reason wasn't there  previousli 
![torso-leaning-def-def](https://user-images.githubusercontent.com/46846616/51429234-c4080500-1c1d-11e9-8559-92f03536651d.png)
![torso-leaning-def-def-n](https://user-images.githubusercontent.com/46846616/51429244-cff3c700-1c1d-11e9-8bc4-da3825b586d7.png)
![torso-leaning-down-def](https://user-images.githubusercontent.com/46846616/51429249-de41e300-1c1d-11e9-994c-a2a31cb24d43.png)
![torso-leaning-down-def-n](https://user-images.githubusercontent.com/46846616/51429255-e69a1e00-1c1d-11e9-8efc-acc07a5ed790.png)
I think now everything looks more finished, so I would like to see it in the game, if not then well ill leave it for myself and for those who liked it

**Comment by MaxGreenKiki** [comment]
Here is BEFORE/AFTER picture:
![before after](https://user-images.githubusercontent.com/46846616/51429311-92dc0480-1c1e-11e9-8e6e-83612d3ade47.png)

**Comment by EntonyEscX** [comment]
It looks great, but the inclined sprites will change.

**Comment by MaxGreenKiki** [comment]
@EntonyEscX OMG really? i would love to see it))) do you know when it may came out?

**Comment by EntonyEscX** [comment]
@MaxGreenKiki Probably in the next versions. If I were to risk a number, I would say 0.9 by the new way of separating the sprites (but this number is just my speculation). 
If you go to the fixed issue about art, you will see a link with the bases for the new sprites.

**Comment by MaxGreenKiki** [comment]
@EntonyEscX i can't seem to find it((

**Comment by EntonyEscX** [comment]
@MaxGreenKiki I made casual clothes for Monika recently, had to redo the leaning pose to fit the new version of it. The arms, hair, chest, position of the leaning pose were totally redesigned. Apparently the hair will now be separated from the body, with a part for the hair from behind and a part for the hair in front, with the body in the middle. And the arms of leaning pose will be separated from the body.
Also, for new sprites, the size has to be twice the original size (2560x1700), and do not need to make the nightly versions, since they have a filter for them.

**Comment by EntonyEscX** [comment]
@MaxGreenKiki This one: #3174

**Comment by multimokia** [comment]
Yeah, as a result of the new base sprites, the leaning hair was already fixed. Shading on the leaning here looks great though.

**Comment by EntonyEscX** [comment]
@MaxGreenKiki Yes, these are the new sprites.

**Comment by MaxGreenKiki** [comment]
@EntonyEscX i meen this is just sad( in no offence but before it looked more natural and now it's just tilted and the lighting could just be fixed (as I actually did) .-. the pose overall is better but idk about that head(( 
![sad](https://user-images.githubusercontent.com/46846616/51430519-7e533880-1c2d-11e9-9d2b-583afec154aa.jpg)

**Comment by EntonyEscX** [comment]
@MaxGreenKiki I disagree, I find the new pose better and more beautiful, both in matter of proportion and angle when in graphic quality.

**Comment by dragonborn2252** [comment]
quick uestion why is monika nude

**Comment by EntonyEscX** [comment]
@dragonborn2252 I think "just skin" is a better term. This is the basis used for artists to create new clothes for Monika to wear on MAS. With this base, the creators can draw the clothes over this so that they all have the correct physiognomy.

**Comment by bittercaramel** [comment]
omg yas
u know how much annoyed me this shine on her hair? it totally didnt fit.... 
i hope it will be added because ngahhh

**Comment by ThePotatoGuy** [comment]
yeah so the hair in the current base set is what we are going to use in all art going forward. closing this.
