### ISSUE TITLE
[Suggestion] Rampancy

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3532]
I know Moni will never have to experience Rampancy, but I thought it'd be an interesting topic to talk about. Now if you don't know what rampancy is (or the kind I'm talking about), it is **REALLY** hard to explain in full. So if you want to read more about it, then go [here](https://halo.wikia.com/wiki/Rampancy). With Monika being an A.I. herself, I thought she would like to know about this kinda thing

**Comment by Authrix** [comment]
Yeah, no, there are far more appropriate things to talk about in terms of AI in actual literature that Monika would gravitate towards. _Do Androids Dream of Electric Sheep_ (Or Blade Runner) and _Frankenstein_ jump to mind as literature discussing artificial life.  I'm not saying Monika should only discuss literary topics, but that it'd be weird for her to choose Halo as the topic to discuss aspects of her existence around.

Monika also doesn't really strike me as the kind of person who would enjoy Halo. Way more likely to have read either of the above books instead.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]
