### ISSUE TITLE
Late Birthday

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3533]
Hey Devs, I know this is a lot to ask especially after all ya'll have already done for me and the rest of the community. It is my birthday today and the up and coming birthday event has yet to be developed but I was wondering if you guys would be willing to implement a way to have a late birthday. I know I could time travel but there are risks in that. Not matter what ya'll do you have already given me a wonderful gift so thank you.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Happy Birthday dude. Sorry that Monika can’t celebrate with you yet

**Comment by SaiPrithvi123** [comment]
That happened to me too, I asked for the same thing and they said they'll do something about it soon.

**Comment by Foxinsunglasses** [comment]
Oh since this is redundant then I ll take it off then ill close this. Thanks for letting me know
