### ISSUE TITLE
[Suggestion] Internal Gifting Guide

### ISSUE THREAD

**Issue by linkone2** [Monika-After-Story/MonikaModDev#3534]
I'd like to suggest a possible Gifting Guide in the game, under extras, that tells the player how to gift stuff, all the steps in a "Foolproof" way. That way people don't come into the discord just looking to give gifts, could use the image from the poem game, and write it up simply, it would also give the "Extras" menu another purpose.

**Comment by multimokia** [comment]
My problem with this is that it defeats the purpose of it being a 'gift' if Monika tells you how to give them, it's more or less her asking for things instead of it being something just from you.

**Comment by candledaredomesticatedfires** [comment]
And it would be best if you had to "earn" giving a gift. Like maybe winning a game of pong on a hard level so it's not that easy, or something else.

**Comment by AsuraShun** [comment]
That doesn't make any sense,you don't need  permission to give gifts,just like in real life,you don't need someone to give you permission to give stuff

**Comment by SaiPrithvi123** [comment]
>My problem with this is that it defeats the purpose of it being a 'gift.' If Monika tells you how to give them, it's more or less her asking for things instead of it being something just from you.

Put the instructions in the same kind of letter which comes up when the persistent file gets corrupt and gets replaced by a backup. And maybe add a category of "Notes to the player" in extras.

**Comment by AsuraShun** [comment]
You can use your browser to get instructions

**Comment by FluffyMuffinMeyer** [comment]
> Shouldn't this be a thing on the wiki?

The (Spoiler) Affection section of the wiki was recently updated, I heard that it will be updated again sometime in the near future to include a list of all available gifts and affection changes, some clear instructions should be there once it's complete.

**Comment by ThePotatoGuy** [comment]
We do need a way of suggesting how to give gifts in-game. This doesnt have to be from Monika, could be a special chibika event or something. the wiki is for clarification, but the initial discussion should happen in-game.

**Comment by ThePotatoGuy** [comment]
[closing until we look into this]

**Comment by ThePotatoGuy** [comment]
wow this actually happened #5412 

marking as complete

**Comment by candledaredomesticatedfires** [comment]
Dont really give a shit anymore lol

**Comment by multimokia** [comment]
You don't have to. It's mainly for our purposes in issue tracking.

**Comment by candledaredomesticatedfires** [comment]
Oh okay
