### ISSUE TITLE
[Bug?] - Just spotted a little graphic issue

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3542]
When I was in the expression preview, I noticed that there was a little dot that appear only when the sweat is on one side of Monika, and not on the other.
![dot sweating](https://user-images.githubusercontent.com/38837456/51468801-1b1def00-1d70-11e9-898e-68ac195b9bc3.PNG)
There is the one with the dot

![non-dot sweating](https://user-images.githubusercontent.com/38837456/51468830-2a9d3800-1d70-11e9-8d9c-1d4274927116.PNG)
An there is the one without the dot.

**Comment by MaxGreenKiki** [comment]
It's probably a stupid question but how did you opened that "expression preview" ? О.о

**Comment by Thimeo** [comment]
That information is in the FAQ:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/FAQ.md#how-do-i-find-the-spritecode-for-an-expression

And if you're wondering how you "copy it in your game directory":
Go to the file you want to download.
Click it to view the contents within the GitHub UI.
In the top right, right click the Raw button.
Save as...
Copy it in your "game" directory

**Comment by jmwall24** [comment]
Fixed #3545
