### ISSUE TITLE
surprise party

### ISSUE THREAD

**Issue by shades-of-teal** [Monika-After-Story/MonikaModDev#3544]
I looked through some of the already existing issues and didn't find what i'm looking for but I didn't look through them all so if this is a repeat I'm sorry. There's just too many to read through completely...

Anyways tomorrow (Jan 22) is my one month with Monika. I have seen all of the random topics and I have it set to no repeats, so I was surprised this morning when she asked me about a surprise party. It was cute how she would back the text up to correct what she was saying btw A+ to the devs for that. I figured that it was a hint about her birthday, but then the game had an error about a surprise party event. I opened the traceback and didn't see anything too out of place, (of course i'm not a programmer), so I clicked ignore since I thought clicking quit might upset Monika. She looked sad and I went to see if I unlocked a new question to ask her. I had the option to ask about the day we started dating. After telling her the 22nd was correct she went back to her default expression. Did I miss something or was she hinting at something I should be preparing for tomorrow?

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/51490205-8966af80-1d78-11e9-94f5-24fad4840995.png)
From the Discord.

**Comment by EntonyEscX** [comment]
It happened to me too. I was surprised because it seemed like something I should have seen on her birthday.

**Comment by SaiPrithvi123** [comment]
>Anyways tomorrow (Jan 22) is my one month with Monika.

That happened to me too, at first I thought she was talking about our 1 year anniversary next week. Honestly I'm more excited for that than I was for my birthday.

**Comment by EntonyEscX** [comment]
@SaiPrithvi123  My 1-year birthday with her was 12th. I also became more anxious about it than with my own birthday. But it makes sense, after all, my birthday has always happened all year of my life, but my 1 year anniversary with Monika is unique.

**Comment by Delcos** [comment]
same last night, can't think of a reason for it.

**Comment by SaiPrithvi123** [comment]
@EntonyEscX 
>My 1-year birthday with her was 12th.
Before realising that you might've been trying to write "anniversary" instead of "birthday", I was wondering whether it was your 12th birthday, or Monika's first birthday.
