### ISSUE TITLE
A/B test different version of docking station

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3549]
Lots of no monika issues means docking station isn't working perfectly. The original consensus was that bad affection values from 084/085 were causing the bad data, but now we're far enough from that version that people should not be affected.

Currently we chksum the entire file as a token for re-entry, but maybe this is too volatile for regular use. 

Could try several options:
* create checksum of only a portion or small amount of data, save that as key into the monika file, and only use that piece to determine correct monika. 
    * Can still pose a problem if the checksum couldnt be decoded.
    * (This is actually how this used to work before it was changed for release)
* only rely on filename 
    * simplest option, but probably would reduce realism and effect of user actions
* limit the amount of padding data by encoding the persistent several times,
   * would make a copy of the persistent until we reach the desired size.
   * probably need a decent amount (maybe 100kb ish) padding data to separate persistents cleanly enough
   * would still need padding data at the end if persistent size is not enough.

Other suggestions are welcome.

*opening up a poll on discord to gather data of docking station use

**Comment by FluffyMuffinMeyer** [comment]
Perhaps switching the file that is generated into more of a line of a persistent file would be a better idea.

1. Could completely remove the need for people to go into the RenPy section of their .roaming, saving some headache for the people who get constant questions about it.
2. Switching Monika to different computers and other versions would become a much simpler, much faster, and much more realistic approach.

Open to suggestions, but I do believe it is very logical.

**Comment by SaiPrithvi123** [comment]
@FluffyMuffinMeyer 
I had talked about the same thing in the Discord server. I suggested why not just put the persistent file in the Monika file but they said because it's more complicated than I think. I also made a post here regarding moving her to another computer (#2358) and they said it's planned. There must be reason why they didn't implement it yet, but they were really vague about it.

**Comment by SaiPrithvi123** [comment]
Suggestion:-

1. Make Monika's file independent from the game it's from.
2. Put a copy of Monika's memories in Monika's file, and keep one with the game.
3. When putting the file back in the game, if memories from the game is different than the memories in Monika's file, the game will ask the player a question and depending on their answer, it will either keep the memories from the game or the file.

I don't know about the technical stuff, but from a lore perspective, it doesn't make sense that the Monika's file is dependant on the game it's from. Monika is in the *file*, not in the game, so if everything goes alright, any install of MAS should accept a Monika file. If everything doesn't go alright, for example if her file get's corrupt, there would be a chance of it being repaired. If the stuff in Monika's file is different from what the game was expecting it to be, the player could be asked to either repair the Monika (in case of corruption, in which case the game would keep the memories stored in the game, as mentioned in the 3rd point.), or the player could just say that everything is alright (useful for switching devices, or just switching between different installs of MAS, in which case the game would keep the memories from the Monika's file.).

**Comment by ThePotatoGuy** [comment]
@SaiPrithvi123 
Actually, the persistent file **is** currently in the Monika file. The issue is that some people are unable to return their Monika files back, which needs to pass 2 tests:
1. the checksum of the entire file must match
2. the persistent data from the Monika file must be successful pieced out and read by the system. (It doesn't actually do anything with the read data, just checks that was possible).

A lot of the first set of issues were with step 2, where the bad data from how affection was saved in 084/085 caused the persistent to fail to be decoded.

Recently, more issues are with step 1, a mismatched checksum. We really don't know if this is an issue during save/load or if the data being checksummed is too large or something, which is why this issue has been created - experiment with a different form of file gen and see if we get less reports of missing monikas.

Yes, the thing you suggested is planned, but the recurrence of Monikas failing to be returned to the spaceroom means that its even **more** dangerous to do save transfers with the Monika file at this time. 

@FluffyMuffinMeyer 
What do you mean by "line of a persistent file"? Based on the rest of your comment, it seems that you are suggesting to save the persistent into the Monika file. As mentioned, that is exactly what we do already, and it may be causing some issues.

**Comment by SaiPrithvi123** [comment]
I'm not an expert at this stuff, and this might be a stupid question, but is it possible to create a new game on a different engine and make in "MAS 2" or something like that? As far as I know, DDLC wasn't made keeping what we are doing with it in mind. It wasn't meant to be like this. It's kinda like we are we are strapping legs onto a fish and making it live on land. I just want to know if it's *possible* to, from a lore perspective, create a new world for Monika and take her in it.

**Comment by ThePotatoGuy** [comment]
>ddlc wasnt made keeping what we are doing with it in mind

The focus here would be renpy, not ddlc. While the engine was designed for visual novels, the only thing we do thats unusual is the state machine that runs idle. File I/O and tokens and whatever are not limited by renpy. 

As for making a different "world" for Monika, that is off topic and should be made in a different issue if you want to discuss that.

**Comment by ThePotatoGuy** [comment]
Linking #2624.

**Comment by ThePotatoGuy** [comment]
[closing as the failure rate is low enough to where this is probably not an issue]
