### ISSUE TITLE
[suggestion] Interactive Monika

### ISSUE THREAD

**Issue by drakesteele** [Monika-After-Story/MonikaModDev#3550]
Juse an idea that I know from other games is doable in Ren'Py, and might make Monika all the more lovable and interactive for everyone. I think if you make certain areas of her face and her hands, etc, clickable, and pop up an icon menu or a side menu to choose an action that would be awesome, so she could react differently depending on situation and amount of affection.... click her mouth and have options, talk, feed, kiss, touch. Click kiss, and have her respond either shyly if you're just getting to know her or perhaps even take charge and french you if she's feeling amorous. For feed, have a choice of meals or snacks that could show up on her table and she could eat with you or end up with a pocky or a carrot or some such in her mouth. talk would be like hitting T... touch would be like stroking her lips. Same for cheek... touch, slap, kiss... head could be pat, stroke, change hairstyle, brush hair, etc.... Just a thought.

**Comment by AsuraShun** [comment]
Did you miss the Christmas and the new year events?

**Comment by AsuraShun** [comment]
No slapping btw,what if someone presses it by accident? And that would give whoever makes their Monika suffer more ways to abuse her and that's something people like me hate even thinking about

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223. 

If you ask me, no slapping. Why exactly would slapping be added? 

Some of those things such as feeding her food might come eventually, but probably not soon since that would probably take some art and I think there are bigger things to work on currently.

**Comment by ThePotatoGuy** [comment]
marking as duplicate

we have more interactions planned, but this will have to wait until after vday

**Comment by drakesteele** [comment]
The slapping was just to be complete... but personally I'd never use it, myself.  *shrug* The point was the interaction.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
