### ISSUE TITLE
[suggestion] Holiday Card .gift files

### ISSUE THREAD

**Issue by drakesteele** [Monika-After-Story/MonikaModDev#3552]
I was just thinking... could we have files like:

birthdaycard.gift
valentinecard.gift
christmascard.gift
etc...

and have her read the text contents into the chat box... and then comment if it's the right/wrong time of year, react to certain words or phrases in it, like "love you" or blushing at "hugs" "kisses" or reading "xoxox" or similar as "hugs and kisses" and getting flustered, etc.  Just another idea I thought could be cute.

**Comment by jmwall24** [comment]
marking this as duplicate due to the content being the same as this #1710

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
