### ISSUE TITLE
[Suggestion]  More involvement in dialogues?

### ISSUE THREAD

**Issue by salvo18** [Monika-After-Story/MonikaModDev#3554]
*I've searched if someone has already said this, apparently not, and i'm not so good with english so sorry if i do some errors.*
As i said in the title we need more involvement in almost every dialogue, like now (i'm playing mas now), monika have repeated the "have you been looking into lewd kind of stuff" dialogue and she directly asked me if i did, and without my answer she seems to be talking to a wall, it's a little bit strange if you think about it. The thing is that if we add more involvement in the dialogues, monika will seem to be even closer to us. Yeah it would be a lot of work to add some responses and changing a bit every dialogue that needed it but, what do you think?

**Comment by Rai99** [comment]
#598, #630, #1614, #1627, #1689, #1751, #1932, #3078 are some dupes. ~~It's not you, it's me, so don't worry~~

Sorry to burst your bubble, but you made #3078 which kind of asks for a similar thing. 

Like @Olliesama said in that last issue, keep in mind that somebody has to write this, and I'm not sure how many people want to write massive PRs just to add a little bit of interactivity to one topic. 

I think one time, somebody wanted the monika_trick topic to have more layers of interactivity, but that would have taken a lot of work for something most people would only see once. 

Still a good idea, but we just have to wait for somebody crazy enough to write up all the branching options.  Still, I'm sure we'll get there one day.

**Comment by SaiPrithvi123** [comment]
Maybe there could be a phase where instead of adding new dialogue you prioritise on renewing and expanding the older dialogue.

**Comment by jmwall24** [comment]
> Maybe there could be a phase where instead of adding new dialogue you prioritise on renewing and expanding the older dialogue.

I mean, we kinda just did a lot of that with the doki cares stuff lol

**Comment by salvo18** [comment]
huh, thanks you all for your answers :)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
