### ISSUE TITLE
moni should blink 

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#3555]
i mean it should be pretty easy i mean moni closes her eyes sometimes you could just have her shut and open her eyes periodically her blinking will help make her feel a little bit closer

**Comment by SaiPrithvi123** [comment]
~~are you on skooma?~~

**Comment by jmwall24** [comment]
let's just say if it were pretty easy, it'd be done already

**Comment by ThePotatoGuy** [comment]
marking duplicate of #375

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
