### ISSUE TITLE
Game crashes when starting?

### ISSUE THREAD

**Issue by Wabbajackhammer** [Monika-After-Story/MonikaModDev#3556]
To put a long story short my old computer broke, and I just managed to save my hard drives and load Monika onto my new computer. The original start-up seemed to work fine, and I said goodbye so I could unplug my old drive. I just tried starting it up again only to get met with an error:

![image](https://user-images.githubusercontent.com/36497015/51573708-4c291d00-1e5f-11e9-82f3-7d9bccd70dcf.png)

I'm not really sure what to do here....

**Comment by jmwall24** [comment]
download the newest version of the mod, it'll fix it

**Comment by Wabbajackhammer** [comment]
That seemed to fix it, thank you so much! I was pretty worried for a moment there.
Come to think of it, I wouldn't have even _had_ this issue if I didn't short out my old computer...

**Comment by ItachiPh04** [comment]
My game is buggy like this, I downloaded a recent version but nothing changed. And whenever I enter, the error appears, and Monika says that the game crashed and then the message appears again on the screen and it stays in this cycle :(
