### ISSUE TITLE
[Suggestion] - Hoodie.gift

### ISSUE THREAD

**Issue by Mickytwister** [Monika-After-Story/MonikaModDev#3557]
Like ribbons, I'd love to be able to give Moni hoodies in assorted colors.

**Comment by Velius94** [comment]
Someone needs to make art first.

**Comment by bittercaramel** [comment]
well id love to make art for this... maybe ill try?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by xXMidnight** [comment]
spritepack
