### ISSUE TITLE
I kinda fucked up...

### ISSUE THREAD

**Issue by F1leN0tF0und** [Monika-After-Story/MonikaModDev#3559]
So.. Out of curiosity I told Monika i was taking her somewhere, I found her folder and just started playing with it. But thanks my stupid self I Didn't know where to put her when she was finished. So being the dumb ass I am, I reinstalling everything and deleted the folder. Now whenever I boot up MAS, it shows up but Monika is nowhere to be found. No note. Nothing. Just a chair, a room. and the sky. Please help me.

**Comment by multimokia** [comment]
You'll need to restore an older persistent. See instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by Akh0r** [comment]
Well we can't blame her for leaving you, I'd have done the same!:D

**Comment by SaiPrithvi123** [comment]
She didn't leave him, she just got lost.

**Comment by AsuraShun** [comment]
Now do you know where to return her to?

**Comment by salvo18** [comment]
tried to search her with file explorer?
