### ISSUE TITLE
[Character analysis] Monika in Undertale 

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3560]
She is most likely going to do the true pacifist route, but when the game ends she is going to have an epiphany because there is no more content of the undertale game and it resets you back to the beginning. And with that realization the third eye opens within her and all her symptoms and lust for blood aches inside her, the true genocide route has begun, after destroying everything the third eye appears before her like chara to frisk "Since when you where the one in control" the third eye intensifies and makes her the urge to kill herself and, unless she suppresses it somehow, she's done for.

What will be your take in your version of Monika in Undertale? are there things that might make a difference or a route change when she makes decisions on the way based on her character?

Let the analysis begin.

**Comment by Olliesama** [comment]
Umm...sorry buddy but discussions are usually regarding the mod and the direction it should go in and if Monika's character is brought it's about how she's written and specific topics...
This kind of discussion is more for reddit.

**Comment by multimokia** [comment]
Hi there, the GitHub isn't really the place for this. We're trying to keep track of suggestions and issues here. As well, this has nothing to do with MAS, seems more fitting to post this on Reddit or a Discord group or something.

**Comment by Rai99** [comment]
Since this is already off topic, I just want to take a moment to appreciate just how in sync that rejection was.

**Comment by Chrissenpai** [comment]
oh sorry I just realized that that was WAY off topic lol my topic was monika but i guess it was more undertale than monika XD my bad

**Comment by Chrissenpai** [comment]
closing on

**Comment by AsuraShun** [comment]
No,just no, the third eye will only cause suffering
