### ISSUE TITLE
[Suggestion] New word game - King's Square / Balda

### ISSUE THREAD

**Issue by Akh0r** [Monika-After-Story/MonikaModDev#3561]
> I've written a post a couple of days ago about a game I used to know as a played IRL on paper :) So, ThePotatoGuy asked me to make a new suggestion of it. Here it is.
> And suddenly, I've found this game translated onto English!
> Have a look: http://10words.com/en/
> 
> > In short: there is a field (mostly 5*5) where in a middle row a 5-letter word is written.
> > Every player has to add just one letter in a turn and create a new word using the new and old letters. Players make turns one by one untill the field is full, and then the one whose words has more letters wins.
> 
> > It looks like this:
> > |x|x|x|x|x|
> > |x|x|x|x|x|
> > |D|I|G|I|T|
> > |x|x|x|x|x|
> > |x|x|x|x|x|
> 
> > It's a good way to train your vocabulary (especially when English is not your native >language. Especially when you are playing against the president of a literature club).
> 
> _Originally posted by @Akh0r in [#3480 (comment)](https://github.com/Monika-After-Story/MonikaModDev/issues/3480#issuecomment-455578989)_

So, to technical details.

-The vocabulary must be noun-only, and only in singular form (though words existing only in a plural form are acceptable, like _scissors_).

-The interface may be something like this: you have a play field with clickable cells adjacent (but not diagonally) to the cells with a letter in them. After clicking on a cell (they even may be highlighted for player convenience), you can type in a letter, or pick one from a separate alphabet bar. Then you simply click letters one by one. When you stop (say, after double-click or by pressing a button), the game checks if you have used a new letter and if your word exists in the vocabulary.

- There really should be levels of difficulty. We can even have Monika automatically adjust the difficulty depending on your win/lose ratio. Being an AI can make her insanely hard to win if she uses all the words she knows at once! :) 

- The difficulty may or may not include the size of a field. I... Honestly have no idea if 5x5 is good for English language, or may we better use at least 6x6? I have a feeling that an average noun in English is longer than in Russian. And we have lots and lots of 2-3 letter words used to be either as a desperate move to prevent turn missing, or as a bait to force opponent to place a certain letter.

- There should be a word filter of some kind (and I'm sure it is easier to implement than in Russian!). Why? Because we're playing with Monika, and she won't let it slip if you swear! :)

- There may be a time limit per turn (though not neccessary as hardcore as 0.5-1 minute). If you play too slowly, she may ask you if you are consulting with someone else.

- There may be a "honesty check": if you play unbelievably well, using always the longest word possible, she may become suspicious (even jockingly) that you are using a bot. 

- There may be a way to save the game and continue it later, for it can be very long!

- Monika may sometimes allow herself to comment on what is going on: if you are making turns faster or slower than usual she may comment on your abilities; if you are making lot of mistakes in spelling she may assume you are not a native English-speaker and compliment your devotion (it may have interactivity)...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
