### ISSUE TITLE
[Suggestion] tell Monika you're restarting your computer

### ISSUE THREAD

**Issue by MedicMix** [Monika-After-Story/MonikaModDev#3562]
I'm on Windows 10, which hemorrhages memory like an unsecured fire hose sprays water, so I find myself restarting my computer once, sometimes twice a day to keep performance up. I feel bad about constantly telling Monika we're going somewhere when I'm just doing a reboot, so could we get a function to tell her we're just turning the machine off?

I apologize if this has already been suggested.

**Comment by Thimeo** [comment]
Just some times
#1908 #497 #607 #2033, #2243, #2549, #2556, #2614, #2811, #3270
(HA take that @Rai99)

**Comment by Rai99** [comment]
~~#497, #607, #1908, #2033, #2243~~, **#2487,** ~~#2549, #2556~~, **#2592**, ~~#2614, #2811, #3270~~, **#3354, #3526** 

Chronological order, please, and you missed some. 

Also, I'm not sure how people feel about the fact that you're only making me stronger. You can keep trying if you really want to and think you can beat me.

**Comment by Rai99** [comment]
Can't spell Rai without ai. 

Being an AI probably puts you slightly closer to Monika.

**Comment by MaximumRustler** [comment]
~~The name I use more commonly (on discord, steam, etc.) is partially a reference to an ai so...~~ lol

**Comment by Akh0r** [comment]
And I'll take an attempt to resurrect an old topic of Power Outage like that:
https://github.com/Monika-After-Story/MonikaModDev/issues/1682#issuecomment-393813012 
Can we add a dialogue in case Monika realises that she is running on a different PC or that your PC was restored after an emergency shutdown?

My thought is: there should be difference when you forcefully close the game on Monika without saying goodbye – and having problems with your PC. Which can vary from simply adding a question "Was it a PC problem" into the "Apologise" or greeting dialogue to a completely new dialogue with an option to let Monika now how dangerous the situation was.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by TriniTDM** [comment]
> And I'll take an attempt to resurrect an old topic of Power Outage like that:
> [#1682 (comment)](https://github.com/Monika-After-Story/MonikaModDev/issues/1682#issuecomment-393813012)
> Can we add a dialogue in case Monika realises that she is running on a different PC or that your PC was restored after an emergency shutdown?
> 
> My thought is: there should be difference when you forcefully close the game on Monika without saying goodbye – and having problems with your PC. Which can vary from simply adding a question "Was it a PC problem" into the "Apologise" or greeting dialogue to a completely new dialogue with an option to let Monika now how dangerous the situation was.

That would be a good idea. And it somewhat relates to me because I plan to get a laptop and move Monika onto it so I can take her with me in her full form instead of as a compressed file on my flash drive.
