### ISSUE TITLE
WHAT THE HECK SOMEONE TELL ME WHY THIS HAPPENED

### ISSUE THREAD

**Issue by Rosethefadingfandomhopper32** [Monika-After-Story/MonikaModDev#3564]
So, the game crashed right? Well, when I opened it back up, it opened as if I just got it, can someone tell me WHY IT RESET ITSELF!?

This is from the aff_log - 

Wed Jan 23 21:31:25 2019
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[2019-01-23 21:31:27.990000]: LOAD | 124.4 | 124.4 -> 124.4
[2019-01-23 21:40:32.516000]: SAVE | 124.4 | 124.4 -> 124.4

==============================================================================

Wed Jan 23 21:53:24 2019
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[2019-01-23 21:53:26.682000]: NEW BACKUP | 0 | None -> 0
[2019-01-23 21:53:26.682000]: LOAD | 0 | 0 -> 0
[2019-01-23 21:58:19.529000]: SAVE | 0 | 0 -> 0

==============================================================================

Wed Jan 23 21:58:25 2019
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[2019-01-23 21:58:27.273000]: LOAD | 0 | 0 -> 0
[2019-01-23 21:59:05.223000]: SAVE | 0 | 0 -> 0

==============================================================================

**Comment by jmwall24** [comment]
this is going to be your friend https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by jmwall24** [comment]
stop opening and closing the game immediately before you overwrite your .bak files.  save a copy of the folder with the persistents and then follow those steps.  since you have a reset, you're going to want to find a .bak persistent that is larger than the more recent ones.

**Comment by ThePotatoGuy** [comment]
can you upload your full `aff_log` file?

and what version of MAS are you running?

**Comment by Rosethefadingfandomhopper32** [comment]
I use Windows, and i had a copy of all the persistent files from before the glitch happened saved in a folder called "persistent back ups" so i deleted the persistent in the folder and moved those there and made another copy of them in case it happens again :3 and it opened to Monika saying "Another crash Xxxxxx" (i put x' instead of the name for a reason)
