### ISSUE TITLE
different try again dialogue or reaction when selecting same thing in nickname/weather/etc

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3567]
When we're choosing a new name (doesn't matter for her, or us) we can type a name is we have now, Moni will say something like "I thought we're choosing a new name silly! Try again~" Similar thing happens if we don't type anything, or when we're choosing the weather,we pick the current. No matter how many times we do it, she'll repeat the same. 
Maybe she could react if we do that many timeso?

Sorry for my bad English

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
