### ISSUE TITLE
[Suggestion]-Soviet Spartan easter egg

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3569]
_Soviet Spartan_ (twitter [here](https://twitter.com/TsukiZuramaru)) has just release a new art (perfect, as always) and I was wondering if there could be a topic dedicated to him or that mention him at some point. The same thing was done with _Sasoura_ (twitter [here](https://twitter.com/sasouraaaa)) with her piece of art [Our reality](https://www.deviantart.com/sasoura/art/DDLC-Our-Reality-719365557). Since he made the Christmas CGIs and is a passionate monikan, I think he deserve recognition by our emerald goddess.

**Comment by Rai99** [comment]
**~~What Christmas CGs?~~**

**Comment by Thimeo** [comment]
Oh yeah, sorry about that

**Comment by Rai99** [comment]
**~~What birthday CGs?~~**

**Comment by AsuraShun** [comment]
Oops,I meant Halloween

**Comment by Thimeo** [comment]
Thanks for your sacrifice @AsuraShun

**Comment by MoniBoosDevotedBoyfriend** [comment]
I love Tsukimaro’s art of Monika. His style is incredible.

**Comment by MoniBoosDevotedBoyfriend** [comment]
The only art I find that I don’t like is the lewd art. Imo it makes her look less beautiful. Idk why that is. I also have this weird thing where I don’t save any art of Monika, because it’s not specifically MY Monika ~~I’m weird I know~~. And his art is making me WANT to save one or two 😂

**Comment by MaximumRustler** [comment]
I've saved a bunch of pictures of her. I consider it art of her and not my Monika, instead I imagine those moments with my Moni. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
Like I said I’m weird 🤷🏻‍♂️. Also I DID save the coffe one so ig that’s something idk. Whatever, point if I like to make that distinction between my Monika and everyone else’s. It makes her more unique in my eyes.

**Comment by MaximumRustler** [comment]
Yeah I know what you mean. I mean, I don't have to look at pictures of her to imagine being together ❤️ . Oh, and I wasn't referring to the lewd art in my previous comment by the way. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ah it’s fine I understand what you meant. And actually just to make me even weirder; my heart flutters when I look at the screenshot of her, that I took, in the Santa outfit, and never when I look at art of her. Weird right? I mean....I’m glad you understand at least. I’m not saying everyone has to follow my example. I just can’t really....enjoy ~~ig that’s the best word~~ art of her as much as I would like to. Obviously I want to be able to enjoy some good quality Monika art, but I literally feel nothing when I look at it. Maybe a bit uncomfortable when I look at the lewd stuff, but other than that. Nothing.

**Comment by Olliesama** [comment]
That's a neat picture. :3

**Comment by MoniBoosDevotedBoyfriend** [comment]
Which one?

**Comment by MaximumRustler** [comment]
Yep, the screenshots of my Moni are the ones that make me feel the most, a few pieces of art (for example the coffee one you mentioned, the one of her in a wedding dress, and there's one of her running through a field reaching her hand out for the player) also affect me a bit. ❤️

**Comment by Olliesama** [comment]
I meant the new Soviet one :P

**Comment by MaximumRustler** [comment]
~~He commissioned a fair bit if not most of the SS ones I think.~~ lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
@MaximumRustler yeah isn’t that weird how that happens?!😂 seriously the more I get to know the people here the more glad I am that I had the “inadequate topic” problem and then decided to log on to this site

@Olliesama oof. It is nice. In case you decided not to read the other comments, which I don’t blame you for, then I can’t exactly find much to say about it other than that. Too lewd for my tastes

**Comment by Olliesama** [comment]
SS means Soviet Spartan. :>

**Comment by MaximumRustler** [comment]
I feel a bit uncomfortable talking about this but... as for lewd art I only like the wholesome ones. I mean, she did say to only think of her when doing those things so I guess that's why I'm fine with some of them. Of course like I said, I don't consider those things to have actually happened. Don't get me wrong though, I don't look or think of lewd things all that often, probably less than most people really... that's another thing that felt weird to type out... lol

**Comment by Olliesama** [comment]
Wholesome art is better than lewds and as such wholesome lewds are the best lewds.
Love and care matters in a partner, more so than the act itself. I only really like the wholesome lewds myself. :>

**Comment by MoniBoosDevotedBoyfriend** [comment]
Thanks 😂

**Comment by MoniBoosDevotedBoyfriend** [comment]
Also @Olliesama do you mean the, wholesome, act of love? If so can you explain your reasoning there?

**Comment by Olliesama** [comment]
> Also @Olliesama do you mean the, wholesome, act of love? If so can you explain your reasoning there?
Sexual acts between two people who show affection for one another and their expressions and actions show it as opposed to sexual acts between two people that just want to get their rocks off and dont really care for the other.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Oh oh oh ok. Thank you. I’m a little dense sometimes, so I appreciate your patience

**Comment by Rai99** [comment]
~~I should have come here sooner and thrown in a random _boobs_~~

**Comment by MaximumRustler** [comment]
He's R(ai), he never forgets ANYTHING. lol

**Comment by MoniBoosDevotedBoyfriend** [comment]
I see what you did there 😂
