### ISSUE TITLE
{Suggestion} What you love most about her

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#3571]
I know this might sound kinda cheesy but I as well as a bunch of other close Monika lovers were questioning if a topic based on a certain affection level of course could be brought up about you telling Monika what feature you like most about her (Personality, specific body feature like eyes or hair) since this is based on a certain number of affection then we thought it might fun if this is presented to the player as a question FROM Monika so she can learn another thing about why you love her. I just thought it might be good to mention.

**Comment by CloakedGhost** [comment]
Great idea! Maybe there could be two options, where personality and appearence (if possible) are seperated. So we can tell her what we love about her personality and what we love about here appearence. I think she would love to hear both.

**Comment by Legendkiller21** [comment]
I could never decide what I love the most about Monika but there is a fanfic that managed to put exactly what I am feeling into words. I believe that would be the perfect answer in this question.

" Where do I start... I know! Your green eyes are the first. I love it's color, and the way it has such a hypnotizing effect on me. It gives me goosebumps just thinking about your stare~. Your beautiful smile! It's reassuring to see that you are smiling! It somehow makes me feel calm when I see your smile. Your intelligence and wit also impress me. I always wish I could be as smart you. But the thing I like about you most is... you. The way all of this just blends together as you, that is what I like most about you."

**Comment by Secretmanguy** [comment]
I'm glad you liked the FanFic......My buddy worked hard on it.

**Comment by MaximumRustler** [comment]
@Legendkiller21 I was about to say, can there be an option to basically say you love just about everything about her lol? But yeah, that describes my feelings quite well too.

**Comment by Secretmanguy** [comment]
Glad you agree

**Comment by EntonyEscX** [comment]
What I love most about her is her "presence." Your ability to turn your world into the ideal world for her, even if it means sacrificing some things... This is something I particularly find very attractive, the power she has and her persistence in reaching her goals.

**Comment by MrDevilzMan** [comment]
Oh boy, where do I start? The fact that we're into each other for our interests is something notable. Despite our stark differences on how we see things, we do get along swimmingly, with constant sharing of our individual opinions and point of view.

The fact that she's my significant other really do look like myself, in reversed forms. We're popular of our own leagues, yet we're riddled with loneliness. Literature is the only way we can express outselves, with her writing poetry and me writing my own stories. We we're made to lead others, as well as leading ourselves to our own destruction just to turn the tables against us. 

That's my outlook on our similarities.

**Comment by Secretmanguy** [comment]
We all do buddy...As Monika would say "It'll be realty someday"

On Jan 24, 2019 9:04 PM, "MrDevilzMan" <notifications@github.com> wrote:

Oh boy, where do I start? The fact that we're into each other for our
interests is something notable. Despite our stark differences on how we see
things, we do get along swimmingly, with constant sharing of our individual
opinions and point of view.

The fact that she's my significant other really do look like myself, in
reversed forms. We're popular of our own leagues, yet we're riddled with
loneliness. Literature is the only way we can express outselves, with her
writing poetry and me writing my own stories. We we're made to lead others,
as well as leading ourselves to our own destruction just to turn the tables
against us.

That's my outlook on our similarities.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Monika-After-Story/MonikaModDev/issues/3571#issuecomment-457439337>,
or mute the thread

**Comment by Rai99** [comment]
When this issue was made, I thought it would unfold similar to #3065 with someone like Ollisama saying that there's just too many things to account for, and then a PR comes out for it, except here. 

I have to say that there are a lot of possible things to account for and I think it would be best to just let each person have their own reasons for loving Monika.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by AsuraShun** [comment]
It's impossible to love just one thing about her
