### ISSUE TITLE
how do you write your 'x' topic

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3575]
[link to question](https://cdn.discordapp.com/attachments/393997315045588992/538198192349642752/unknown.png)

we should ask this question and store the data.

and then maybe find a way to collect it (with user permission ofc).

**Comment by EntonyEscX** [comment]
8.

**Comment by Onion-Bubs** [comment]
Is there some significance to this that I'm just not getting?

Also 7.

**Comment by Professor-JMO** [comment]
6

**Comment by Areaclassified** [comment]
8

**Comment by Thimeo** [comment]
6

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
