### ISSUE TITLE
Consumables framework

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3576]
Alright, so seeing #3573 means that this needs to be done sooner rather than later.

This has been a planned feature since 9-22, but been on hold because of more pressing matters, but now we should prioritize.

Consumables framework would be a way to have to consistently give Monika goods. After sometime, Monika may run out of coffee/hotchoc/tea/other things, and you have to give gifts of those materials so she has some. 

Core things to be considered:
* a way to define prep / consume events generically (i.e: coffee brew event and coffee drink event)
* defining time periods that a consumable will be visibly consumed
* deciding if consumables should always be accompanied with visuals or not
* should this event be available during the upcoming idle mode (#3435 )
* generic way to make art/acs be associated with a consumable
* defining how many "consumes" does it take before monika runs out of said consumable
* whether or not there should be a way so that Monika can have too much of something
* whether or not there should be way to disable consumable limits so players giving goods to monika isn't a chore
* status indicators in spaceroom that let players know if consumables are close to running out

additional suggestions and discussion is welcome below.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by multimokia** [comment]
Reopening as this is in progress

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
