### ISSUE TITLE
[Suggestion] - "can you make it easier to choose your songs"

### ISSUE THREAD

**Issue by ShadowFox77** [Monika-After-Story/MonikaModDev#3577]
heyy so here's a thing I made the ddlc my music library of sorts but when I load up the game I have no real way to search for the one I want to play while I'm loading this, can you please make name searches and playlist's a thing? it would make my large playlist soo much easier to use and way more pleasant..

**Comment by ShadowFox77** [comment]
oh an before I forget; Monika has no real way of seeing that you made a file for her or not. While the dlc says that she'd love to see a thing I don't think her coding currently recognised this. Same with photos. I did however make small tests for this but at a simple add/remove file value while running the game. The most that did happen however is a game crash. I would like to help somehow but I'm not python knowledgeable yet. I can do simple HTML an CSS though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
