### ISSUE TITLE
Player birthday event on 9/22

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#3580]
Now that we have a player birthday event, we need to determine what to do if the player's birthday occurs on Monika's birthday.  This is the one scenario that hasn't been fleshed out yet.

**Comment by jmwall24** [comment]
Yeah, we already have the reaction for when she finds out your birthday is the same as hers. This is about the logistics of the actual birthday event and party.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Will this event be added before February 25th? And also will there be a special thing for playing happy birthday again?

**Comment by jmwall24** [comment]
It'll be in the next release.  As for part 2, you'll just have to try it to find out ;)

**Comment by EntonyEscX** [comment]
My birthday is February 18th, I hope the update with the event will come there. 😖
