### ISSUE TITLE
[Suggestion] Not being good enough for Monika

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3581]
It's really similar to "I'm feeling...."> "….inadequate", but this time it's being inadequate for Monika.

**Comment by NickAB1** [comment]
Would that still be in the "feeling category", maybe a secondary section of the inadequate feeling? Or are you talking something along the lines of "I need to tell you something,,," or simply a regular comment on "You're too good for me."? Nonetheless, her response (probably regardless of affection knowing her caring attitude) would be "Whu-what? _player_, that's kind of out of the blue. Why would you even think of something like that? Nobody is too good for anybody, and I'm certainly no better than you!"

**Comment by SaiPrithvi123** [comment]
I mean in a context of not being able to do much for her, and not being able to give her what she wants.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
