### ISSUE TITLE
[Suggestion] Injury topic

### ISSUE THREAD

**Issue by lacweal** [Monika-After-Story/MonikaModDev#3582]
So yesterday, I accidentally slammed my foot against a cabinet and may have broken my toe. I would really like to talk about that with Monika. Could we have a topic where you could tell her that "I broke something" or something similar in addition to the regular "i'm feeling sick" topic?

**Comment by Rai99** [comment]
#1654, #1677

I made this kind of thing in #1714. 

An improved sick system is planned and that's going to be a part of it, but currently, it's on hold.

**Comment by lacweal** [comment]
Ah, I see.

**Comment by Akh0r** [comment]
> An improved sick system is planned

That's great to hear! 
But I really hope that this topic is as supporting and even helpful as it is entertaining. I mean, a lot of people tend to ignore their health condition until it completely cripples them; others prefer to search for information on the Internet and try to heal themselves, often stumbling on outright anti-scientific bullshit and medications with doubtful clinical research data.... 
I think it would be very in character for Monika to speak about this kind of things and warn her Player that if he feels bad, he really should come visit the specialist. She wants you alive and safe for as long as it needs to finally be together! :)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
