### ISSUE TITLE
Monika's eyes are offset a little?

### ISSUE THREAD

**Issue by loz89** [Monika-After-Story/MonikaModDev#3589]
In this art specifically she looks off and it's really noticeable when changing expressions. I just downloaded this mod today and it's enjoyable but this is taking me out of it a bit. 
![image](https://user-images.githubusercontent.com/47072656/51796517-ddcbbe00-21c2-11e9-8b6d-0ba9f50381d8.png)

**Comment by loz89** [comment]
The eyes are still a bit offset even with the bow, I probably should've mentioned that. Either way thanks for responding, that's pretty interesting.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
