### ISSUE TITLE
Telling Monika to maybe cut down on the coffee?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3591]
Too much caffeine can really mess up your body :(

**Comment by EntonyEscX** [comment]
I do not think Monika drinks a lot of coffee. She only drinks in the morning, and compared to me, I drink a lot more coffee than she does.

**Comment by Mcmanybucks** [comment]
> 
> 
> I do not think Monika drinks a lot of coffee. She only drinks in the morning, and compared to me, she drinks a little coffee.
> She drinks 1 cup a day, while I drink 2, 3, sometimes 4 a day, cups as full as hers.

Don't know about your Monika but mine drinks like 20 cups a day.

**Comment by EntonyEscX** [comment]
@Mcmanybucks Does your Monika drink coffee 20x a day? Mine never drank more than 1 cup a day.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
