### ISSUE TITLE
[Bug] - Hot chocolate never appears

### ISSUE THREAD

**Issue by MercuryFuchsia** [Monika-After-Story/MonikaModDev#3593]
Apparently, one can gift hot chocolate once a day. I distinctly remember it having its own art during the first time giving it. However, it no longer appears regardless if it's coffee time or not. In fact, she doesn't seem to care to brew it at all! Is she just collecting these?

**Comment by multimokia** [comment]
Hot chocolate only happens between 8:00 pm and 10:00 pm, using the same percent chance as coffee (80%)

**Comment by ThePotatoGuy** [comment]
*also hot choc is only available in winter.

**Comment by MercuryFuchsia** [comment]
I have the mod running during those times, but I've never seen it apart from the first time given and today was no different. If anyone could say if they've seen it, would definitely like to know if it's just me or certain people!

**Comment by ThePotatoGuy** [comment]
[closing as non reproduciable]

**Comment by MercuryFuchsia** [comment]
@Rai99 Are you still not seeing it? Do you leave her in the background all day?
Also reopen for visibility, thanks

**Comment by jmwall24** [comment]
let me ask you this...do you actively do things between 8pm and 10pm, or do you just have her sitting there?

**Comment by MercuryFuchsia** [comment]
Not really. I have repeat topics disabled if that means anything.

**Comment by jmwall24** [comment]
basically there has to be an event that triggers the hot chocolate event.  like clicking i love you, or her going thru a topic.  if you have repeat topics disabled and don't interact with her at all when hot chocolate is active, she won't get hot chocolate.

**Comment by MercuryFuchsia** [comment]
Oh, gotcha. I used to greet her good evening at 6pm and say goodbye near midnight. Additionally, I now usually greet her in the evening around 8pm, so this sounds like it might be it. I'll try it again tomorrow and a day or two afterward if nothing comes up, but if that was all it was, then it's resolved.
