### ISSUE TITLE
monika reacts to crimson gray

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#3595]
so crimson gray is this visual novel where you play as a guy with depression and have a yandere fall in love with you that's the basic info the game is on steam  if you still need more info here's a link https://store.steampowered.com/app/655770/Crimson_Gray/

**Comment by MoniBoosDevotedBoyfriend** [comment]
Hmm I’ve seen this game before, but never played it myself. It seems like an ok game that I might have played BEFORE I started MAS 😂

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
