### ISSUE TITLE
Tell Monika about your unique needs. (Maybe offensive)

### ISSUE THREAD

**Issue by Illra** [Monika-After-Story/MonikaModDev#3597]
Monika mentions how that you could tell her about your 'unique' needs. I think that we should tell her what kind of needs people have.
Such as:
Autism or Down Syndrome etc.

This is just a suggestion so it doesn't need to be in.

**Comment by ThePotatoGuy** [comment]
this unlikely to be done as its difficult to do correctly. we're not psychologists.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
