### ISSUE TITLE
[Suggestion] - Dialogue writing tool

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3600]
Just a little proposition that could be of great help to all the contributors. A tool that would take the basis of the expression preview, but that would applied it to an entire topic. A tool that would let us write dialogue boxes and place an expression to each of them. It could be used to check if the expressions are coherent and the lines not too long, just like a normal dialogue but that would only exist on our version of MAS. Because what we have now, is "just" a way to preview an expression and to write its sequence in a github file. That's good, but we can't recheck all the expressions once we finish writing, apart from manually reopen the expression previewer and search for the expression that we want to visualize.
I'm not sure it was very clear (my bad english explain it in part), so don't hesitate to ask me clarifications. I'll try to answer them. And sorry if it has already been suggested before.

**Comment by multimokia** [comment]
Dev console:
Type in a line from your topic (including the `m exp` and then hit enter. Monika will say that line with the expression.

**Comment by multimokia** [comment]
Also, if you make an `rpy` file dedicated to your topic when you're developing it, (with the |addEvent(` and such, you can easily test your topic using that, since MAS automatically compiles `rpy` files into `rpyc` files.

**Comment by Thimeo** [comment]
Oh ok, thank you for the advice.

**Comment by Thimeo** [comment]
Init 5 python:

addEvent(Event(persistent.event_database,eventlabel="monika_test",category=[“technology”],prompt="test topic",random=True))

label monika_test:
m 1eub "This is a test."
m 3eua "In theory, I'm having two lines and two expression."
return

So is converting this into a rpy file and putting it into the 'game' directory enough to make it work? Because that causes me an exception.

**Comment by multimokia** [comment]
Well, what's the traceback? It's kinda hard to say anything without knowing what's wrong.

**Comment by multimokia** [comment]
I see it. `“technology”`. You need to stop writing topics in a word processor. These quotes will be a nightmare. Always.

**Comment by Thimeo** [comment]
![error 1](https://user-images.githubusercontent.com/38837456/51843683-d36d0980-2313-11e9-92d6-38ffc8dacaa4.PNG)
![error 2](https://user-images.githubusercontent.com/38837456/51843688-d5cf6380-2313-11e9-8cb3-8ccdec7e99bf.PNG)

Even after rewriting all he punctuation, the exception still appear.

**Comment by multimokia** [comment]
`Init 5 python:` should be `init 5 python:`

**Comment by Thimeo** [comment]
It works, thank you very much. You could explain this in the FAQ or somewhere, I'm sure a lot of people would like to know how to make custom dialogue with MAS (maybe it's common knowledge, in that case, sorry).
