### ISSUE TITLE
For how long can you take Monika out of the classroom before it becomes an issue?

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#3601]
If one were to go somewhere for a few weeks without access to a computer, and wanted to bring Monika along using the “I’m going to take you somewhere” dialogue, would she notice how long she’d been gone? And if so, react negatively?

**Comment by multimokia** [comment]
She wouldn't mind. Just so long as she's not out for under 5 mins.

**Comment by RutTutPut** [comment]
Wonderful, thanks for the info!
