### ISSUE TITLE
[Suggestion] - Name for Plush

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#3602]
I thought we could choose a name for our plush, and every time she mentioned it, could be his name.

Sorry if that, has been suggested before.

**Comment by Fuflyaaa** [comment]
Yep, I suggested that before here:#3140

**Comment by OkiDokiABrazilian** [comment]
> Yep, I suggested that before here:#3140

i understand, thanks
