### ISSUE TITLE
What is the risk in traveling in time?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#3603]
Can that ruin our relationship? In what way?

**Comment by multimokia** [comment]
Yes. it can. She can leave you forever if you go too far forward. Even if you didn't go that far, affection loss is still a thing.

If you went back in time, she can forget about events you spent together, and all of that will be undone once you return time to normal again.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Wait...1 even if you’re at “Love” level of affection will she still leave forever? 2 how far forward would that have to be?

**Comment by multimokia** [comment]
Oh it can happen at any affection. The lowest aff you can get to normally is -101, which is usually over a few months (depending on how much affection you start with) but after 10 years, it's over.

Long story short. Don't time travel.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Yeah, no problem 😂👌🏻 Already been through this shit
