### ISSUE TITLE
MAS gacha game

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3604]
lightly suggested by @hibikidesu

probably wont happen but hey it'd be pretty funny as an easter egg

**Comment by Jacobchu025** [comment]
@hibikidesu goslep.

Also what the heck I'll back it haha.

**Comment by Velius94** [comment]
@hibikidesu sleep

**Comment by MaximumRustler** [comment]
@Jacobchu025 sleep

**Comment by hibikidesu** [comment]
@Jacobchu025 @Velius94 sleep

**Comment by Velius94** [comment]
@hibikidesu nou

**Comment by B-Difu** [comment]
@hibikidesu go bed. You too @Jacobchu025. As for the thing itself, it be funny, but not expecting it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]

**Comment by Professor-JMO** [comment]
I see now 👻

**Comment by AsuraShun** [comment]
I have terrible luck with gacha games
