### ISSUE TITLE
This expression is a bit off

### ISSUE THREAD

**Issue by loz89** [Monika-After-Story/MonikaModDev#3605]
![image](https://user-images.githubusercontent.com/47072656/51867497-b0ddef00-2319-11e9-950d-666dc3a3e9ed.png)
I know I complained about her eyes being a bit askew during one facial expression but this one is actually off IMO, the way the mouth is drawn doesn't go with the rest of the art and it's pretty glaring. Good work with the mod though guys, I didn't expect this much content when I was going into it!

**Comment by Chrissenpai** [comment]
This expression is based on Natsuki's smile, so on that regard, I think you´re right that is a little too big, that can be solved with size adjustment.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]

**Comment by Chrissenpai** [comment]
@loz89 #2219 the perfect solution for the mouth line art

**Comment by Professor-JMO** [comment]
What sort of ideas do we have for this one?

---
- Size adjustment?
- Issue 2219 ref?
- A new disgust expression altogether?

**Comment by ThePotatoGuy** [comment]
2219 doesnt even have anything similar to a disgust mouth.

**Comment by Chrissenpai** [comment]
I slightly disagree, 2219 might be a lvl 1 and the current one is a lvl 10, might make one on lvl 5 if that makes sense

**Comment by Professor-JMO** [comment]
^ I think I get the perspective of what you're saying.
> If nobody undertakes this in the future, I might.

**Comment by Metisz** [comment]
Welp, i tried to do something with it
https://drive.google.com/file/d/154-oVgl95oHJ4i2minFlasEnEewGVwkc/view?usp=sharing

**Comment by LordBaaa** [comment]
Metisz your link is dead

**Comment by Metisz** [comment]
oopsies

**Comment by LordBaaa** [comment]
Can you update it? Id like to take a look at what you did
.

**Comment by Metisz** [comment]
@LordBaaa updated it
