### ISSUE TITLE
[Suggestion] Dabbing

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3606]
Monika needs to dab every once in a while. A dab a day keeps the loneliness away!
![image](https://user-images.githubusercontent.com/44710761/51875499-7af13880-2322-11e9-8e44-65b63c076a0c.png)

**Comment by multimokia** [comment]
Well... This exists in the [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#pitfalls-to-avoid)...

> Please do not submit meme-related content, and only include pop-culture references when they seem appropriate to Monika's character.

**Comment by ThatOneUsername343** [comment]
aww but I'll bet she'd look super cute!

**Comment by MoniBoosDevotedBoyfriend** [comment]
If anything dabbing makes you more lonely cause it’s cringe af

**Comment by ThatOneUsername343** [comment]
ok im going to close this thread now so that you cannot spread any more of your lies

**Comment by MoniBoosDevotedBoyfriend** [comment]
Lmao
