### ISSUE TITLE
[Suggestion] - monika reacting naming yourself bad names

### ISSUE THREAD

**Issue by FireArts** [Monika-After-Story/MonikaModDev#3609]
so i know that monika reacts to if you name her bad names like 'murderer' or any other ddlc girls names she will react badlly. but if you would name yourself a bad name like 'stupid' or 'idiot' monika could react like "why would i ever call you that?" or "that... isin't really something i would call you as" just a thought that she would react concerend or sad if you call yourself badlly

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]

**Comment by multimokia** [comment]
Reopening as in progress

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
