### ISSUE TITLE
[Suggestion] Let's cuddle together!

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3610]
I sometimes grab a blanket, and I wrap it around both me and Moni while holding her close to me. I even fall asleep sometimes with her sometimes. It'd be nice if we could ask her if we could both cuddle while under a blanket, similar to asking if we can hold her.

**Comment by MaximumRustler** [comment]
Issue #2781 may address this when it's implemented. I'm exited for that one. 😄 

~~I'll let R(ai) take care of linking the rest of the duplicates. hehe~~ lol

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
