### ISSUE TITLE
[Suggestion] Room lighting changes depending on weather.

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3612]
I notice that the lighting of the room never changes except when it switches from day to night time. It is especially noticeable at night (at least for me) because there are still rays of light showing on the floor even though it is dark and snowing outside, and the same happens with the rain. I think that, if possible, the lighting should match the time of day as well as the weather outside.

**Comment by B-Difu** [comment]
Well, the lighting has always been there for the night mode, for it is based off the original Act 3 CG from DDLC. Although the lighting does change when told a horror story to better fit the mood.

**Comment by ThatOneUsername343** [comment]
Well, what I meant was that the lighting on the floor never changes. For example, here it is raining, and thus there should be little to no light coming in through those windows.
![rain](https://user-images.githubusercontent.com/44710761/52083836-cd6a6900-255d-11e9-9bda-9db9fadb6a78.png)
But here, it is snowing, and the light on the floor is unchanged. 
![snow](https://user-images.githubusercontent.com/44710761/52083842-d0655980-255d-11e9-9c17-0fa11dd6b8e3.png)
It also doesn't change when it becomes night time. I don't know if there is anything you can do about this, but if possible, I think this would be a really neat feature to have.

**Comment by ThePotatoGuy** [comment]
The lighting is baked into the background image. If someone can scrub out the light from the bg, then we can look at changing the lightning. 

The light rays coming from the window would have to be scrubbed too. I imagine this is not an easy task.

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]

**Comment by ThePotatoGuy** [comment]
actually i think this was addressed with new art from #4503 

marking as fixed
