### ISSUE TITLE
Complimenting Monika's costumes [Suggestion] - 

### ISSUE THREAD

**Issue by NoodleJoodle** [Monika-After-Story/MonikaModDev#3613]
I think it would be cool if you could compliment stuff like Monika's halloween costume on halloween. Was kinda disappointing when I found out you couldn't not gonna lie, so I think this would be a great addition to the mod

**Comment by AsuraShun** [comment]
Probably going to be implemented when she gets casual clothes

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
