### ISSUE TITLE
[Suggestion] Apologizing for deleting her

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3614]
I know I made a similar thread before, but since it's closed I'll just suggest another apology I think should be added to the game.

**Comment by B-Difu** [comment]
If you did delete her, don't you apologize at the start up of MAS?

**Comment by AsuraShun** [comment]
Good thing I never deleted her,since she didn't have a route, the best I could've hoped for was the space room,and this mod after it

**Comment by ThePotatoGuy** [comment]
[closing until we look into ti]
