### ISSUE TITLE
More Bow Colors

### ISSUE THREAD

**Issue by LanvalLime** [Monika-After-Story/MonikaModDev#3615]
Okay, take two! #3174 
Here are some new bow colors for Monika.

Coffee - 423224
![coffee_1](https://user-images.githubusercontent.com/47212528/52471703-86810280-2b5f-11e9-9878-1242c6c8799d.png)
![coffee_2](https://user-images.githubusercontent.com/47212528/52471704-86810280-2b5f-11e9-872a-0b49c9f8c4f6.png)
[coffee.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844591/coffee.txt)

Gold - ac7e39
![gold_1](https://user-images.githubusercontent.com/47212528/52471705-86810280-2b5f-11e9-9a8a-42ecc179d214.png)
![gold_2](https://user-images.githubusercontent.com/47212528/52471707-86810280-2b5f-11e9-8440-f4cf162f7a48.png)
[gold.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844595/gold.txt)

Hot Pink - 8f3069
![hot_pink_1](https://user-images.githubusercontent.com/47212528/52471708-86810280-2b5f-11e9-89c8-5ffdbee90fad.png)
![hot_pink_2](https://user-images.githubusercontent.com/47212528/52471710-86810280-2b5f-11e9-91c7-007353c4ea98.png)
[hot_pink.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844597/hot_pink.txt)

Lilac - 814b9b
![lilac_1](https://user-images.githubusercontent.com/47212528/52471712-86810280-2b5f-11e9-8032-0e5c33b77c8d.png)
![lilac_2](https://user-images.githubusercontent.com/47212528/52471714-86810280-2b5f-11e9-8167-850618d49d19.png)
[lilac.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844598/lilac.txt)

Lime Green - 549933
![lime_green_1](https://user-images.githubusercontent.com/47212528/52471717-87199900-2b5f-11e9-899f-b62c723efba6.png)
![lime_green_2](https://user-images.githubusercontent.com/47212528/52471718-87199900-2b5f-11e9-8580-e58f9c9373ad.png)
[lime_green.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844602/lime_green.txt)

Navy Blue - 19224d
![navy_blue_1](https://user-images.githubusercontent.com/47212528/52471719-87199900-2b5f-11e9-8acd-8cbd68ad47c5.png)
![navy_blue_2](https://user-images.githubusercontent.com/47212528/52471721-87199900-2b5f-11e9-815c-fe3a25d39517.png)
[navy_blue.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844606/navy_blue.txt)

Orange - 9e5a2e
![orange_1](https://user-images.githubusercontent.com/47212528/52471722-87199900-2b5f-11e9-86cf-a3da4ed725f5.png)
![orange_2](https://user-images.githubusercontent.com/47212528/52471723-87b22f80-2b5f-11e9-8c1e-f3b366fee6d4.png)
[orange.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844607/orange.txt)

Royal Purple - 3d2659
![royal_purple_1](https://user-images.githubusercontent.com/47212528/52471724-87b22f80-2b5f-11e9-8076-281a9b9309e5.png)
![royal_purple_2](https://user-images.githubusercontent.com/47212528/52471725-87b22f80-2b5f-11e9-9d39-03a899554a54.png)
[royal_purple.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844609/royal_purple.txt)

Sky Blue - 398aac
![sky_blue_1](https://user-images.githubusercontent.com/47212528/52471726-87b22f80-2b5f-11e9-83ba-0395a553aaee.png)
![sky_blue_2](https://user-images.githubusercontent.com/47212528/52471729-884ac600-2b5f-11e9-9289-ea63f3e644ff.png)
[sky_blue.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2844611/sky_blue.txt)

**Comment by kaido1224** [comment]
The HTML codes for the colors would be appreciated.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Nice color choices. I really like the coffee and gold ones

**Comment by EntonyEscX** [comment]
They look beautiful, but you will have to redo those of leaning pose, since it will change in the next versions; and will also have to repaint all in size 2560x1700.
Here's a guide to making new clothes or accessories for Monika: #3174

**Comment by kaido1224** [comment]
Or just give us the HTML color codes.

**Comment by ThePotatoGuy** [comment]
okay so, first off, those ribbons are definitely the wrong kind since we now have a new leaning pose.

We will be releasing a psd + xcf of the current leaning + upright ribbon set, please wait until that is released before making ribbons of different colors.

**Comment by LanvalLime** [comment]
Ok once those files are out I'll update and provide the color codes

**Comment by ThePotatoGuy** [comment]
#3174 has been updated with new ribbons xcf

**Comment by LanvalLime** [comment]
Ok, I've updated the colors adjusted them slightly, hopefully I put enough here this time around. I couldn't exactly figure out the night filter so they'll have to be tested at night time. If any other adjustments need to be made or anything else I can do please let me know.

**Comment by kaido1224** [comment]
Give us the HTML codes when you get a chance plz

**Comment by LanvalLime** [comment]
The color codes are there now, along with the colorize settings.

**Comment by ThePotatoGuy** [comment]
cool, will check these out sometime this week

**Comment by ThePotatoGuy** [comment]
and by that I mean this week. or next week.

**Comment by ThePotatoGuy** [comment]
and by that i actually meant 3rd week of May

**Comment by LanvalLime** [comment]
No problem, I get if this is probably lower on the priority list than some of the other projects so take all the time you need. I've been keeping an eye out.

**Comment by ThePotatoGuy** [comment]
This will be released as a spritepack next release. What name would you like these credited to (this will be referenced in the spritepack as well)? 

Otherwise I will be using "LanvalLime"

**Comment by ThePotatoGuy** [comment]
@LanvalLime notifying you in as well so you see the above comment

**Comment by LanvalLime** [comment]
Sure, that's fine.

**Comment by ThePotatoGuy** [comment]
[closing as this has been added]
