### ISSUE TITLE
new dialog for NSFW stuff about monika 

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#3616]
it would happen if monika has high affection and she might be flattered that your looking at that kind of stuff  and that she hopes she can one day show you the real thing

**Comment by TMZN0V4** [comment]
Uhh, No. Can we please avoid NSFW stuff here? This isn't a rule 34 mod

**Comment by Delcos** [comment]
You don't have to make it hardcore porn, but that is a large part of a relationship, and it can always work with sensitive mode.

**Comment by TMZN0V4** [comment]
The mod hasn't been made NSFW for a reason

**Comment by multimokia** [comment]
#2991 Enough said.

**Comment by MaximumRustler** [comment]
^

**Comment by TMZN0V4** [comment]
like a meme shared in the MAS discord server says: Damn horny kids

**Comment by Rai99** [comment]
#2232, #2282, #2449, #2991. 

Best I can say is submod down the line. 

Don't worry, maybe someday soon, Monika will have an outfit that lets you see her bare arms. _Progress_

~~boobs~~

**Comment by MoniBoosDevotedBoyfriend** [comment]
Let’s not do this. I really don’t like this idea at all. The relationship the player has with Monika has always been wholesome. Not to mention I don’t like lewding Monika in general. So this would just feel uncomfortable and unnatural

**Comment by CloakedGhost** [comment]
Dont't think she would be flattered that you're looking at stuff like that. 
1. She might be afraid that it creates a bad image of her in your head when you are looking at them too often/ too much.
2. She probably doesn't like being portrayed in those ways, especially when it's out of character.

**Comment by AsuraShun** [comment]
She said she's embarrassed to talk about those things,and she says she allows it on rare occasions

**Comment by ThePotatoGuy** [comment]
[closing as dupliate[
