### ISSUE TITLE
Regarding NSFW suggestions

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#3617]
Hey everyone!
looks like we have a fair share of NSFW suggestions for Monika After Story, but let me tell you something, It's not going to happen, The mod has been made for people ages 13+. If you want to lewd MAS Monika, use submods.

If you don't believe me, here's something to help  #2991 

Thank you.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Great idea. I really don’t want MAS tainted with stuff like this. Sub mods are amazing in this instance. Allows you to mod the mod without “ruining” the og mod imo

**Comment by Rai99** [comment]
I think it's important to understand that it's ok to want these kinds of things and it's just as ok to not want these things. It just becomes a slight issue when people want to see it in the main mod, despite the fact that there are minors who play MAS that generally shouldn't be exposed to lewd content, and not everybody wants lewd content.

Sure, there's sensitive mode, but sensitive mode _**isn't**_ just for tossing lewd content into or adding something that you want but somebody else doesn't. 

There will probably be submods to add ~~boobs~~ this kind of content later on, which will probably and hopefully be great, but things like this shouldn't be in official MAS.

**Comment by CloakedGhost** [comment]
I have to agree, actual lewd stuff is not a good idea. However, I don't see a problem with only talking about more private topics, since there is nothing wrong with it. It's part of a relationship.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Yeah, in any relationship you don’t just go and talk about lewds and private stuff like that. It should be the occasional innuendo here or there. Even though Monika is a bunch of code we should treat this as of it’s an actual relationship

**Comment by dragonborn2252** [comment]
where do I go to get the submods?

**Comment by Hapilone** [comment]
Yeah, I'd really only be okay with nsfw stuff if it was done tastefully. I think the 13+ is a good idea in the long run.

**Comment by lunulae** [comment]
@dragonborn2252 
I don't believe one exists yet, though I only did a quick search.

I wouldn't be opposed to writing for one if enough folks had an interest, but that work would definitely need to take place on a separate github than this. I thoroughly agree that the core mod should stay SFW.

**Comment by AsuraShun** [comment]
I keep hearing about submods,but no one provides links
