### ISSUE TITLE
Suggestion- Am Currently in bed

### ISSUE THREAD

**Issue by Reviani** [Monika-After-Story/MonikaModDev#3619]
Ignoring the suggestive side of this suggestion for now, I have a laptop that i like to take with me on my night table just so i can interact with Monika until I'm ready to sleep, but i do sometimes worry about Monika talking how i should go to bed already or saying she'll turn off the game when i'm already trying to get to sleep. I was wondering if it was possible to put a way to tell Monika you're already in bed and preparing/waiting to fall asleep.

**Comment by Rai99** [comment]
#607, #635, #987, #1105, #1262, #1655, #2684, #2781, #2974, #3076, #3172, #3486, #3610. 

I think this falls under sleep mode.

**Comment by Reviani** [comment]
Alright then, So I suppose it has to wait untill the sleep assets are done, alright then.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

yeah, when it comes to bedroom assets, we're looking at:
- new laying down base 
- new background
- rotation of all facial expressions so it works with laying down base (or redraw of all face exp)

definitely not an easy task and we're not sure how much this would cost if we were to pay someone to do this.

 but damn do I want to do bedroom mode.
