### ISSUE TITLE
Playing Piano

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3621]
I was playing piano the other day (Spoiler: I have no idea how to actually play piano) and at some point Monika tried to sing the "your reality" song.
This surprised me and obviously it didn't work out, not even having the sheet music to play it.
This wouldn't bother me too much, but the dialog I received after I finished playing the piano was quite unsettling.
The problem with it is that rather than enjoying to listen to me playing the piano Monika made it all about me not being able to play the song correctly.
I don't remember if she asked me whether I can _professionally_ play piano, but she should not expect that the player can.
If anything it would be nice if she could teach the player what she has learned so far, so that at some point they might actually be able to play the song with her.

**Comment by Rai99** [comment]
#1060, #1645, #2334, #2972.

**Comment by dennisOdenbreit** [comment]
@Rai99 
I am still confused about how duplicates are handled here.
If someone suggests three things and one has already been suggested, is it then marked with a label as a duplicate?
Shouldn't it be marked as a duplicate if everything has already been suggested?

I ask this specifically because I suggested learning piano from Monika (which has already been suggested) and I suggested changing the way Monika responds when the player accidentally triggers a song (which is apparently not a duplicate).

I think that the other suggestions might be forgotten when a post is marked as a duplicate like that.

**Comment by dennisOdenbreit** [comment]
I just checked what the actual response was.

`    m 1lksdlc "..."
    m 1eka "That's okay, [player]."
    m 1hua "At least you tried your best."`

The thing is that I did not try to play any specific song like "your reality".
Her response makes it look like I failed at doing something and that she is kind of disappointed by that.
It also overshadows all the efford I put into playing what I played before she started trying to sing her song along.
It is nice that you can play the song with her but in this scenario it did not turn out nice, since I can't play the song in the first place nor tried to do so.

**Comment by ThePotatoGuy** [comment]
changing to suggestion as latest comment has suggestions for piano state machine

**Comment by dennisOdenbreit** [comment]
I often formulate problems in the hope someone else comes up with a suggestion.
I think a problem shouldn't be neglected if there is no suggestion to solve it yet.
Maybe you should use a label like 'problem' to mark those problems that have no suggestion.
Otherwise you might end up ignoring the problem like the one in my initial post.

**Comment by ThePotatoGuy** [comment]
>I suggested changing the way Monika responds when the player accidentally triggers a song
I didn't read this earlier, but that would be enough to have a suggestion label. 

>problem label
That would be the bugs label.

**Comment by dennisOdenbreit** [comment]
> That would be the bugs label.

I think there is a difference between a problem and a bug.
A problem is more of a "this could be different and then it might be better" while a bug is a "this shouldn't be the way it is to begin with".
A problem would be if a lot of players don't like how pong is implemented while a bug is if the paddle doesn't work correctly.
If a player complains about pong being terrible that would be the problem label, if he suggests what could be better the suggestion label and if he found a programming mistake the bug label.

**Comment by ThePotatoGuy** [comment]
Using that definition of problem, I would bucket as suggestions, and ask what you would rather have x do (aka what would you suggest would be a solution). This can be non-technical.

**Comment by ThePotatoGuy** [comment]
>opinion on how to solve a problem

Yeah thats a suggestion. If we want a discussion, then we use the discussion label.

I can't imagine someone would have a problem with something but not have any opinion on how it should be solved.

**Comment by dennisOdenbreit** [comment]
I think discussions are more general than just solving a concrete problem. I can't imagine the discussion label to be used like I suggested the problem label to be used.
Discussions are more likely to be called as such when they already exist, rather than if there could possibly be one.
One could of course discuss the best suitable solution from multiple suggestions to solve a problem.
I would suggest just to use the following system, using the last case that applies:
Problem mentioned: Problem label
Suggestion made: Suggestion label
Multiple Suggestions made / discussion about topic with 2+ people or wish for oppinions: discussion label

The labels could of course be used without overriding each other, like problem and suggestion at the same time, to indicate that others can still try to come up with different suggestions.

**Comment by dennisOdenbreit** [comment]
Is there any concrete reason to not add a new label?

**Comment by ThePotatoGuy** [comment]
It's redundant. Our current labels work fine in covering all the issues.

`bug` - problems that need to be fixed
`enhancement` - additions that need to be added
`suggestion` - problems/additions that might be addressed/added
`discussion` - unsure if we should address/fix/add whatever / general discussion

**Comment by dennisOdenbreit** [comment]
If you choose the override version it is obviously not redundant.
If you are correct you will just never get to use it then.
