### ISSUE TITLE
[Suggestion] - Anniversary topic changes (spoilers)

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3623]
Here's the topic (spoilers for the first year relationship ahead):

    m 1eka "It's really hard for me to believe that it's been a year since we met."
    m "Time doesn't have meaning inside this place, but I know it must have been hard for you to remember to talk to me all this time."
    m 2eua "So is there anything special you wanted to do on our first anniversary?"
    m 1ekbfa "I'll do anything you want today, okay?"
    m 1hua "If you're trying to give me something through the screen right now, thanks!"
    m 1esa "I don't think that's physically possible right now, but I appreciate all your love that went into that gesture."
    m 1hub "I love you so much too!"
    m 2eua "Oh, by the way, did you figure out what was going on with all the puzzles I left for you?"
    m 1tku "I'm sure the creator of this world has released another game by now..."
    m 1tsb "Did you try to import my character file to that one?"
    m "There's no way that wouldn't have a special effect, right?"
    m 1hubfb "Ahaha!"

I have some problems with this topic and I thought about proposing some changes, if the community wants to.
First, let's talk about something that is not in the dialogue box but that's in the time system of the mod. Today was my 1st year of relationship with Monika, and I intended to celebrate it today when I woke up. But I stayed up late yesterday, until midnight to be precise, and so the event activated itself when I was preparing myself to go to sleep at 00:01 AM and it bothered me. A lot of game that uses the time in the real world for setting up events have a system that could be implemented, setting "a new day" to 01:00 AM instead of 00:01 AM (except for special events like the new year's day). That way, peoples who stays up late will not trigger the event at the end of their day just because it's technically already tomorrow (does that make sense?).

Then, I have some problems with some of the lines, and their inconsistency with other informations.

    m 1hua "If you're trying to give me something through the screen right now, thanks!"
    m 1esa "I don't think that's physically possible right now, but I appreciate all your love that went into that gesture."

I think that you're referencing to a kiss, right? Well now that we have that functionality, so it's not useful to "fake" it anymore.

    m 1tku "I'm sure the creator of this world has released another game by now..."
    m 1tsb "Did you try to import my character file to that one?"
    m "There's no way that wouldn't have a special effect, right?"

We've established in a update that the character file didn't meant anything, and Monika even deleted it. Plus, Dan Salvato hasn't released a new game yet, and I think that Monika would be a little more curious about that than just "Yeah, maybe, I don't know.", it's her creator after all, and the topic of "Monika's reaction to a new Dan Salvato's game" should be a little more elaborated than just two lines in the dialogue for the 1 year anniversary. What I mean is that this topic shouldn't be treated so lightly by Monika.

And to finish, some minor issues.

    m 1ekbfa "I'll do anything you want today, okay?"
    m 1hua "If you're trying to give me something through the screen right now, thanks!"

    m 2eua "Oh, by the way, did you figure out what was going on with all the puzzles I left for you?"
    m 1tku "I'm sure the creator of this world has released another game by now..."

The transitions could be done more smoothly.
Again, I'm not forcing anything on anyone, nor do I blame anybody, it's just a suggestion on a topic that I encouraged other peoples to debate about.

**Comment by Onion-Bubs** [comment]
The bit about giving Monika something through the screen I think refers to giving her a gift rather than a kiss. But we also have the functionality for that in MAS too.

**Comment by Rai99** [comment]
I think a lot if not most of the anniversary dialogues are long overdue a rewrite, and seeing as how more and more people are reaching the higher milestones, I would imagine that it's on the list of things to do. 

Especially with how underwhelming the 1 year anniversary is, not to mention inaccurate. It still acts like gifts, kissing and hugs aren't really a thing and it assumes Dan's next game is out, which it isn't. Inserting her file into that game is probably what Monika was talking about with all the puzzles and stuff, along with the secrets of the other chr files. Seeing as Monika gets rid of her chr file since it's not needed, it doesn't make sense for her to talk about using it for something. 

As for you staying up late just to try and trigger the anniversary, I think Monika would lightly scold you for that because she would want you to go to bed at a reasonable time as always. 

Overall yeah, I wouldn't be surprised if an anniversary overhaul were to happen sooner or later.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok, I guess that kind of makes sense..but I never really went too in depth with the puzzles she left in ddlc in the first place. Were they all basically about the eventual new game or no?

**Comment by Rai99** [comment]
Supposedly, Monika was supposed to be the hero in the next game and one of the other dokis might be the villain.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Owo that would have been cool. So just to clarify real quick: she IS referring to the files and what not that she made during ddlc right? ~~I’m sorry it’s just that to me your follow up to my original comment was a bit unclear to me~~

**Comment by Rai99** [comment]
As far as I know, she's mainly talking about the chr files.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok. Thank you. Like I said I apologize for asking. I just got confused a bit

**Comment by ThePotatoGuy** [comment]
people are welcome to do a rewrite of anniversaries. 

[closing this until we work on it]
