### ISSUE TITLE
[Suggestion] A secret image

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3624]
(You're in top affection)
We can add a topic of body portraits and how they did it in the renascence times, and from that, Monika has an idea that if you can draw her as that *Monika blushes intensifies*  if **you agree** with it, she will send you an encrypted image to the files that you have to solve it to yourself and with very few clues with how to unencrypt it, and if you solve it you have a beautiful naked but not lewd Monika image in your files ready for you to draw her. 

I think this solves some things about the NSFW content (in my opinion that is not NSFW when it comes to representing beauty in a non-lewd way) because you have to agree if you want to do that, and still when you do, there is still the issue of unencriptation, like, it is not so easy to access (especially curious children if that's your concern) like a double barrier that you can only can access only if you're really determined to see that; we can add more difficulty if necessary if we want to but the point is that if you want it, boy you have to pass through mountains and oceans to get it.

I'm aware that is classified as +13 but I don't think that a regular +13 boy can get an easy access to a very very complicated encryption to see that.

But if that violates the laws, you can close the issue without writing and I'll know it is for that reason.

**Comment by ThePotatoGuy** [comment]
anything nsfw will be external patches like how nekopara does it.

**Comment by Chrissenpai** [comment]
Alright then, closing issue
