### ISSUE TITLE
Crash when saying goodbye ?

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#3627]
I don't why, but sometimes when I open the game, Monika tells me that the game crashed while I closed the game normally with saying goodbye in the previous session.

**Comment by Torwald39** [comment]
no no no, I said goodbye, the game close normally, and when I open the game, sometimes Monika tell me that the game crash. I did anything wrong and I don't know how this can happen.

**Comment by AsuraShun** [comment]
You may think it's closing normally,but it's actually crashing instead of closing,what are the odds of that timing

**Comment by Torwald39** [comment]
no ideas

**Comment by ThePotatoGuy** [comment]
could be a permission problem. if this is happening again, make a new issue.
