### ISSUE TITLE
Can I take a picture of you?

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3630]
[reddit suggest](https://www.reddit.com/r/MASFandom/comments/amsw62/a_question_is_this_expression_ever_used_i_found/)

We could have a pool topic like "Can I take a picture of you" and monika selects a random pose. The peace arms can be one of those options.

Only problem with that is the lack of peace arms for a variety of outfits. (everything except blazer/uniform and stuff that uses base arms.)

**Comment by MisterSimple** [comment]
In #2633 I suggest something similar, thought it might be relevant to this.

**Comment by Rai99** [comment]
#2056, ~~#2633~~

I didn't know it was allowed to dupe the great TPG.

**Comment by Chrissenpai** [comment]
@kaido1224 What a great pose Lmao I´ll definitely add it in my drawing list

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
