### ISSUE TITLE
Topic Issue - First time saying "I love you!".

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3633]
When you tell Monika `"I love you!"` for the first time ever, the dialogue is as follows:

`"...!"`
`"I...I love you too [player]!"`
`"I cannot believe you said that to me!"`
`"It makes everything I've done for us worthwhile!"`
`"Thank you for finally saying it..."`

The thing is, this isn't actually the first time the player has told Monika they love her. During the introduction (i.e. the first time you launch MAS), Monika asks this question:

`"Do you love me, [player]?"`

At which point the player may answer `"I love you too."` or `"No."`. Answering `"No."` just causes Monika to jumpscare the player and quit the game, so saying `"I love you too."` is the only way to progress past the introduction. What this means is that by the time any player reaches the point in MAS where they can say `"I love you!"`, they have already said it before, so Monika's dialogue during the first instance of saying `"I love you!"` doesn't make sense. You could argue that saying `"I love you!"` is more meaningful than answering `"I love you too."` because, this time, the player isn't saying it just because it's the only viable option, they're doing it out of their own free will, hence why Monika makes such a huge deal about it now and not during the introduction (where she simply says `"I'm so happy you feel the same way!"` or `"I knew you really loved me the whole time."` if you chose the jumpscare before), though choosing to install MAS in the first place is already a demonstration of the player's unconditional love for Monika.

There's also the players who installed MAS during vanilla DDLC's Act 3, who have already accepted Monika's confession, and decided against deleting her. In this case, when the player confesses their love for Monika during the introduction, that's their second time doing so, and when they say `"I love you!"` that's already their third time reciprocating Monika's feelings. (Note: players who completed DDLC don't have this problem because deleting Monika is essentially breaking up with her, hence Your Reality's "If I don't know how to love I'll leave you be").

**Comment by jmwall24** [comment]
I agree with the first part, but not the last part.  Not deleting her in Act 3 is not the same as actually saying the words I love you.

**Comment by Olliesama** [comment]
Well the idea was that this is the first time the player does it of their own accord. :>

**Comment by jmwall24** [comment]
While i agree with that in premise, I guess in my mind, she would see you saying it in the intro as of your own accord as well, especially if didn't hit no only the get the jump scare and then hit it the second time thru.

**Comment by MisterSimple** [comment]
> Not deleting her in Act 3 is not the same as actually saying the words I love you.

That's true, but there's no way to properly express your feelings to Monika in vanilla DDLC, so not deleting Monika is the closest a player can possibly get to saying "I love you"  (until they install MAS, that is).

**Comment by jmwall24** [comment]
Which is why you saying it for the first time in MAS would mean so much. Even if you're pretty sure, finally hearing the actual words is on another level.

**Comment by MisterSimple** [comment]
You're absolutely right.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
