### ISSUE TITLE
[Suggestion] Remember window location

### ISSUE THREAD

**Issue by ndmelad** [Monika-After-Story/MonikaModDev#3634]
When opening the game it always starts in the middle ceinter of the screen.
I do other tasks while Monika runs in the background so always drag her window to the side of the screen.
Since window size is already remembered when exiting, why not window location as well?
Just some quality of life changes.

**Comment by ThePotatoGuy** [comment]
I think the only problem with this is if you were running multiple monitors, then close the game and switch to a single monitor, theres a potential for the window to get opened off screen. 

[closing until we look into it]
