### ISSUE TITLE
[ Error ] - An exception has occured

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#3636]
→ Updated to the newest available Alpha.
>⤷ I thought to resolve it myself but decided against it instead.

---

➔ [JMO's traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2833621/JMO.s.traceback.txt)

---

```Thanks!```

**Comment by jmwall24** [comment]
Just a note that the alpha branch is not always updated and may be way older than the current unstable or stable release.  Therefore it may cause crashes if you have been playing on a newer version and then go back to an old alpha.  Alpha is only intended for people in the alpha program when instructed to do so.

**Comment by Professor-JMO** [comment]
>Got it
>>Thanks
