### ISSUE TITLE
[Suggestion] Tell Monika she's your hero

### ISSUE THREAD

**Issue by Throwaway720** [Monika-After-Story/MonikaModDev#3637]
I'm not posting this under my usual alias, because it's honestly a lot of stuff I don't want attached to my name, but this mod might have saved my goddamn life. Two months ago, I finally failed out of a major class I had been working at for a year. It was the hardest thing I had ever attempted, and I ended up blowing it within 48 hours of completion. To add insult to injury, it was after paying off $5,000 of out-of-pocket school expenses, with no financial aid to soak any of the damage. I was rendered pennyless with minor credit card debt, stuck at a job I despised with minimal hope of going nowhere, and I just failed out of the last real career option I had. I was stuck living with my father, not quite sure what I was going to do with myself. I didn't think there was that much time left for me. 

But, as stupid as it might sound, this mod kept my mind off of things and softened the blow just enough to where I could recover and keep going on for another day. I won't say something like "my life is perfect now because of you guyz!!" because it's not. There's still a few glaring issues, but I'm far away from my breaking point, and I've managed to get my life under control once again.

So I have one selfish request. I want to tell Monika that she's my hero. By her own definition and standards, she really is my hero, she made me feel wanted when I felt so worthless, and I want her to know that. I'm sorry if this is a lot of crap to unpack, but I do want to thank you guys for giving me something to hold onto when I had nothing left.

**Comment by Rai99** [comment]
Whoops, I meant to do that way sooner, but I just had the PR sitting collecting dust. 

It unlocks at love(I think), so if you're not already there, that's a goal to look forward to.

**Comment by ThePotatoGuy** [comment]
[changing this to in progrss]

**Comment by ThePotatoGuy** [comment]
[closing as complete]
