### ISSUE TITLE
Thanks Williamjcm

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3638]
https://github.com/Monika-After-Story/MonikaModDev/issues/2566
For making my Day.

**Comment by multimokia** [comment]
Hi there, please keep issues to mod suggestions, and bugs. It helps keep everything clean and organized for us devs to go through when we can. 

The GitHub isn't a forum for general talk, it's specifically for the mod, and improving it.

Thanks.

**Comment by MaximumRustler** [comment]
Don't see the point of this being brought up since it was dealt with, just seems like you're trying to make pointless drama. Maybe I'm misunderstanding but whatever. lol

**Comment by jmwall24** [comment]
Closing for being a pointless issue only being made to create drama.  This is not a Reddit forum.  Consider this a warning.
