### ISSUE TITLE
 The points of affection change some events like: Valentine's Day?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#3640]

**Comment by multimokia** [comment]
I'm not entirely sure what you're trying to ask here.

**Comment by LarseneUnowen** [comment]
I think he means like in christmas, that you needed to have 300 or more of affection to unlock the kiss event.

**Comment by Andrenika** [comment]
> I think he means like in christmas, that you needed to have 300 or more of affection to unlock the kiss event.

Yes, that's what I mean
