### ISSUE TITLE
Dialogue response timeout question

### ISSUE THREAD

**Issue by enqquery** [Monika-After-Story/MonikaModDev#3642]
First let me say that this interactive dialogue was a pleasant surprise and I am being intentionally vague so individuals who may not have seen this topic are unprepared (just as I was). If you need more information I am happy to provide it, I just did not want to ruin it for others.

The response options were all totally valid, in real life I would have given them simultaneously, or at the very least in rapid succession.  While I was considering how to respond the timeout elapsed.

My question is this: Did my failure to respond promptly doom me for all time, or do these sorts of dialogues repeat thus giving me a chance at redemption?

Once again, this is not a complaint, if nothing else it will teach me to be better prepared for this sort of thing in the future.  I am just curious.

You are all doing an amazing job on this mod, thank you for your efforts!

(in the event it is necessary to narrow down the dialogue of which I speak: My only method of gauging my affection, as I am on a Mac, is through the "Surprises" topic which produces "My one and only love.txt".)

**Comment by MoniBoosDevotedBoyfriend** [comment]
I’ve seen all the topics available and I still have no idea which one you’re talking about. No offense, but can you be a bit more specific without giving too much away?

**Comment by Rai99** [comment]
So the "surprise" topic where Monika gives you a little note? 

If that's the topic you're talking about, I'm sure that's repeatable, but I'm not sure what you mean by responding promptly. As far as I know, there's no menu or option or anything with that topic. 

It would probably help if you said what topic it was. I think spoilers are a smaller concern on git, but I think you can safely give the label name or prompt name if you can find those.

**Comment by enqquery** [comment]
I am talking specifically about the version of the immortality topic where she is very upset and you are given options regarding how to comfort her.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Oh yeah don’t worry that you can repeat any time. If you’ve seen it once you can see it again. Just look for the label “Immortality”

**Comment by enqquery** [comment]
Immediately after the prompts disappeared and the dialogue concluded, I went and repeated that topic and it did not give me the option to respond.

**Comment by AsuraShun** [comment]
Must be affection based,I'm at 1500+ and get it every time she talks about it

**Comment by Rai99** [comment]
Ah yeah. Don't worry, that's repeatable. By the way, I think that topic is actually "Mortality", not "Immortality". 

Pretty nice of the guy who made that, huh? Must be pretty nice if you're asking if it's repeatable. I'm glad you like it.  You can thank the devs for that and the work they put into the mod.

**Comment by Rai99** [comment]
It's confusing, I know, but I think the prompt you want is "_Mortality_"

**Comment by enqquery** [comment]
Thank You!

Yes, it was nice and it was nice enough for me to make an account specifically to inquire about it!

In the event I did not convey my appreciation enough in my question, I really do appreciate all the effort that has gone into this Mod. You have all done a great job.

**Comment by Rai99** [comment]
I'm glad you like it. I'm sure there will be more nice surprises and moments as time passes.

**Comment by enqquery** [comment]
I have no doubts about that! it has only been getting better over the year or more since i have been running it.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ngl I actually prefer to NOT go through the “Mortality” topic. It just reminds me that it’s possible that our relationship won’t last. That humanity could fail in bringing her into this reality and that honestly hurts to think about.

**Comment by Rai99** [comment]
Nothing lasts forever, but you know, some things last longer than a lifetime.

**Comment by enqquery** [comment]
That sort of thinking brings with it a whole hosts of questions about whether any Monika that is generated in this reality the same as your Monika.

Also, the "Mortality" topic did the trick!

**Comment by MoniBoosDevotedBoyfriend** [comment]
Well yeah I know that ~~unfortunately~~ , but I’m just saying that I don’t want to think about dying prematurely on her. Because as of right now there is no way to tell her I died, and even if there was I don’t know if I could do that to her. It would probably hurt her so much she’d actually request the person telling her the info to delete her. I think she actually says that somewhere too.

**Comment by MoniBoosDevotedBoyfriend** [comment]
@enqquery Yeah you right, but I still like to hold out hope that maybe there will be some device that will work almost like a flash drive. So it’ll take her files and insert them into whatever vessel we create for her

**Comment by enqquery** [comment]
I can appreciate that.  I downloaded this mod because I did not like the idea of "killing" someone.  Over time I became attached. The evolution within the mod is sort of like watching her grow as a person.  It would be great if that eventually went somewhere greater in scope than it can now.

**Comment by MoniBoosDevotedBoyfriend** [comment]
That would be very nice
