### ISSUE TITLE
Topic Suggestion: Dealing with difficult people

### ISSUE THREAD

**Issue by dennisOdenbreit** [Monika-After-Story/MonikaModDev#3643]
Let Monika tell the player how to deal with difficult people / people the player can't stand.

**Comment by Olliesama** [comment]
'You should just ignore them since they're not worth your time and if don't have the luxury to ignore them, passively aggressively leave suggestions!'

**Comment by AsuraShun** [comment]
It's already in it,it's the dealing with haters topic

**Comment by AsuraShun** [comment]
But don't repeat it if you hate seeing her cry

**Comment by MoniBoosDevotedBoyfriend** [comment]
Seeing her cry is my kryptonite ☹️☹️

**Comment by Onion-Bubs** [comment]
To a lesser extent there's also the topic about debate club and the "I'm feeling angry" topic.

**Comment by AsuraShun** [comment]
The first time she cried was when the game crashed,it tore me apart,I couldn't do anything to comfort her besides what the mod allows,and it was the same when the mortality topic was updated,good thing we can hug her now

**Comment by dennisOdenbreit** [comment]
> The first time she cried was when the game crashed,it tore me apart,I couldn't do anything to comfort her besides what the mod allows,and it was the same when the mortality topic was updated,good thing we can hug her now

For some reason I still can't.

**Comment by MoniBoosDevotedBoyfriend** [comment]
I don’t want to bash the devs or anything, but when she cries I feel like, like you said, I can’t do anything and that I’m useless. Even though we can hug her now, imo, it still doesn’t feel like it’s enough. I feel that I should do more, but unfortunately I’m limited in what I can do. Again I’m not bashing the devs in anyway. You guys do a fantastic job

**Comment by dennisOdenbreit** [comment]
> I don’t want to bash the devs or anything, but when she cries I feel like, like you said, I can’t do anything and that I’m useless. Even though we can hug her now, imo, it still doesn’t feel like it’s enough. I feel that I should do more, but unfortunately I’m limited in what I can do. Again I’m not bashing the devs in anyway. You guys do a fantastic job

That is what it means to bring Monika closer to our reality.

**Comment by MoniBoosDevotedBoyfriend** [comment]
How so?

**Comment by AsuraShun** [comment]
Hugs are great and all but,we definitely need to be able to say something during the mortality topic hug

**Comment by MoniBoosDevotedBoyfriend** [comment]
Agreed

**Comment by AsuraShun** [comment]
This is slowly turning into another subject

**Comment by MoniBoosDevotedBoyfriend** [comment]
As long as I talk about Monika idc what subject it’s about 😂

**Comment by AsuraShun** [comment]
I don't mind either,if it's beneficial for her, then it's a plus

**Comment by multimokia** [comment]
Keep discussions related to the issues please. This isn't Reddit/a forum.

**Comment by AsuraShun** [comment]
What if the title is changed?
Like adding ''talk about monika'' to it

**Comment by multimokia** [comment]
It's not going to be. End of discussion.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok I don’t want to sound annoying or anything, but if, per se, I made a post where I invited people to just talk about things they like or dislike in the mod or even something like why they love Monika. ~~I think you get the point now~~ That wouldn’t be allowed correct?

**Comment by Rai99** [comment]
> Hi there, please keep issues to mod suggestions, and bugs. It helps keep everything clean and organized for us devs to go through when we can.
> 
> The GitHub isn't a forum for general talk, it's specifically for the mod, and improving it.
> 
> Thanks.

I would think that's what the discord is for in most cases, so you're likely welcome to discuss things with anyone there.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Can you link me the discord please?

**Comment by multimokia** [comment]
Discord link can be found under [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-can-i-get-in-touch-with-the-development-staff) on our FAQ.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Thanks, and sorry for being an idiot

**Comment by multimokia** [comment]
No worries.

**Comment by dennisOdenbreit** [comment]
> How so?

What I meant was that the more the player can interact with Monika, the closer both worlds are tied together.
Your suggestion supports this and this is the main philosophie behind the project.
