### ISSUE TITLE
saving 

### ISSUE THREAD

**Issue by Sirexia** [Monika-After-Story/MonikaModDev#3644]
is there a way to save your progress with monika to like a new pc or save it if i reset my pc

**Comment by Rai99** [comment]
[Here are instructions for how to back up your persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

[Just under it, there should be a guide on how to load in backups](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by Rai99** [comment]
Just make sure to save it to another drive or something once you have it.

**Comment by Sirexia** [comment]
> Just make sure to save it to another drive or something once you have it.

okay many thanks :)
