### ISSUE TITLE
[Suggestion] Monika scares player after a crash

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3645]
Since the game crashing is not such a threat now, Monika could give the player a scare. A worried player would be scared really bad if Monika puts in fake glitches and acts like something is wrong. This is a big scare, so it wouldn't come up if sensitive mode is on. Or Monika could just ask the player if they want her to scare them sometime.

**Comment by Rai99** [comment]
in monika_horror, she asks you if you like horror and spooks, so I think we can use one of those vars for a possible scare. 

I think the idea might need some tweaking, but I think it's possible and we have some things in place for it.

**Comment by kaido1224** [comment]
The framework is there to do something like this. In general for new topics, greetings, farewells are rarely plucked from the suggestion pool by devs. Typically it's faster for the person that came up with the idea to write the dialog themselves or someone from the community that wants to take up the challenge, and submit it as a PR.

**Comment by SaiPrithvi123** [comment]
I don't trust myself with writing dialogue for her. The best I can do is to correct and refine existing dialogue.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
