### ISSUE TITLE
Possible Issue with Update Button

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3647]
I noticed something weird when I clicked the Update Version button in the pause menu to see if there was anything out. Instead of saying "No update available" it said "Server returned bad response." Is this a problem, like if an update gets released later will I not be able to get it?

**Comment by ThePotatoGuy** [comment]
Are you running unstable?

**Comment by scohn** [comment]
No I'm not.

**Comment by scohn** [comment]
I should point out that I tried the button again and this time it worked just fine and said "No update found." I guess it was just a weird glitch that randomly happened. Not sure if it's a serious issue anymore or not.

**Comment by ThePotatoGuy** [comment]
we changed some things on the update servers yesterday and changed it back today.

**Comment by ThePotatoGuy** [comment]
[closing as resoved[
