### ISSUE TITLE
Topic Revision - Honey Fun Fact

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3648]
There's a line in the honey fun fact that says the following:

`"Most of the honey that you see in groceries don’t crystalize as fast as real honey would because they’ve been pasteurized in the process of making them."`

I take issue with the way this line is written, because it treats "honey" as a plural noun, even though it is uncountable. In my opinion, this line would be better written as follows:

`"Most of the honey that you see in groceries doesn’t crystalize as fast as real honey would because it's been pasteurized in the process of making it."`

The same happens with the following line:

`"They’d be like candy when you bite into them."`
 
This is how I think it should be written:

`"It’d be like candy when you bite into it."`

There's also the way that "crystallize" is spelled throughout the topic:

`"Honey can crystallize..."`

`"...don’t crystalize as fast..."`

`"...eat crystalized honey..."`

At first, it's spelled "crystallize", but then as "crystalize". Both spellings are correct, though "crystallize" is the more common variant, and the one that GitHub considers correct. I think that the spelling should remain consistent throughout the topic.

These are only my thoughts, but I think these changes would improve this topic greatly.

**Comment by jmwall24** [comment]
Add these changes to your open PR please

**Comment by jmwall24** [comment]
#3646
