### ISSUE TITLE
Monika's base sprite body is too red.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#3651]
The new base sprite in the new PSD's in #3174 has Monika's new body sprite look too red, she's a pretty dang pale person.

I have made the new base sprites skin paler to match it better.
https://drive.google.com/file/d/1nEFSd4CnJEKtqqt6DWzjd9bYnHBAJoOw/view?usp=sharin
https://drive.google.com/file/d/16uY1sBdNbtF2BcJ22TRPyQRCLfvcsX_G/view?usp=sharing

**Comment by ThePotatoGuy** [comment]
@Olliesama can you upload images as well so we can see overview of changes

**Comment by ThePotatoGuy** [comment]
@Olliesama did you change coloring of hands / wrist / forearms as well?

**Comment by Olliesama** [comment]
https://imgur.com/a/YMYzhBr
Here's a comparison of old and new.
Old is first, new is second.

**Comment by Chrissenpai** [comment]
Oh my, that detail of the colour skin never noticed before, you´re right, I thought it was just because it was a dark room, learned something new today.

**Comment by Olliesama** [comment]
I believe I've fixed the issue.
https://drive.google.com/file/d/1GT5ual5I_s2ZdfDzxAZ1hp4RILd4o2dS/view?usp=sharing
https://drive.google.com/file/d/1GKNmDETCtY0kh5F9jlWbF_PpbWF4z_oa/view?usp=sharing

**Comment by Delcos** [comment]
not to be annoying or anything but where do you find the newer base sprites/ new PSD's. Thanks

**Comment by Olliesama** [comment]
@Delcos https://github.com/Monika-After-Story/MonikaModDev/issues/3174
Google drive inside.

**Comment by Olliesama** [comment]
<details><summary>Spoilers, no clicking for those that don't want to be spoiled.</summary>
<p>

Valentines day psd.
https://drive.google.com/file/d/14Dja_0v223fnWf3140x8XmCVKCFSYRUb/view?usp=sharing
https://drive.google.com/file/d/1ah1assmjQnlWjcKb_Gucv_KmfRSjzQAq/view?usp=sharing

</p>
</details>

**Comment by EntonyEscX** [comment]
It really look better this way. In the previous version, with the night filter, it seemed that Monika had burned with the sun.

**Comment by Velius94** [comment]
Gonna use these for blazer rework. Great job Finale!

**Comment by ThePotatoGuy** [comment]
[closing as this has been addressed and added to main issue as well]
