### ISSUE TITLE
Add Safe Wrapper functions around dict accessors

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3652]
we have a ton of places where we assume that items exist in an dict. This is unsafe and will cause crashes if data integrity issues occur.

All spots that access data from a dict must use an accessor (get) function that handles cases where the value is not found. This can be passed to the caller via defval params if necessary

**Comment by ThePotatoGuy** [comment]
[keeping this open as a reminder]

**Comment by kiraboris** [comment]
Hmm with default values, I guess it could break the dialogue style and logic a bit if a "normal" default value was used in a dialogue. Maybe though Monika should explicitlely comment on that some data is corrupt? Could be fun, I guess.

**Comment by ThePotatoGuy** [comment]
sort of already implemented with the `pdget` function. Only some places are using it though.
