### ISSUE TITLE
[Suggestion] Have Monika comment when you keep asking her the same question to see different dialogue options.

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#3655]
Whenever there's a new dialogue option with branching choices, I always go through and re-ask the question and click the other choices just to see the other paths. I think it would make a good addition to have her be aware when you do that and make a comment on it (especially if the dialogue is flagged as something that Monika will remember in the future). ~~Because it's also unrealistic to ask a person the same question multiple times, but I do the same thing all the time in other video games.~~

Though, how would you guys think she'd react? It'd probably differ based on what the dialogue itself was about ~~(custom dialogue for each one for our ambitious writers)~~. I could see her reaction having a wide range of possibilities: being sad and self-conscious about being stuck in a game, getting mad that the player treats these dialogue options so flippantly, or thinking it's cute that the player is such a completionist to name a few. Probably a lot more feelings could exist other than the ones I mentioned. Any thoughts?

**Comment by dennisOdenbreit** [comment]
This is a very good suggestion.
It will require a lot! of work though to do it for all topics individually.

**Comment by dennisOdenbreit** [comment]
Where's the suggestion label?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
