### ISSUE TITLE
Zoom resets when giving her coffee/hot choc the first time

### ISSUE THREAD

**Issue by Just-Monika** [Monika-After-Story/MonikaModDev#3661]
First of all, thank you for dealing with Monika zoom reset after going for coffee. However, zoom resets after gifting her coffee.
The second case is changing outfit after "door" welcome. Moni changed an outfit from Monyaka to classic school uniform. I know you don't have sprites for nya, but some dialog that you surprised her and she didn't have enough time to change or question if you can give her a minute to change before sliding with her desk would be nice.

**Comment by AsuraShun** [comment]
The new outfit? How do I unlock it?

**Comment by AsuraShun** [comment]
Never mind,I remembered it's the other Halloween outfit

**Comment by dennisOdenbreit** [comment]
I think i brought something like this up once.
But yes, some explanatory dialog would certainly be good.

**Comment by ThePotatoGuy** [comment]
I don't think she really needs to explain this. She could have changed clothes while you were away.

Regardless, the influx of new outfits has made the status of opendoor greeting in limbo and so it may be changed entirely.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
