### ISSUE TITLE
What happened to Monika's jaw ? 

### ISSUE THREAD

**Issue by xdaveonpc** [Monika-After-Story/MonikaModDev#3663]
It might come from the last update , and I noticed it right away , what happened to Monika's jaw , specifically her right side ( left side from screen view ) ? It looks like she had been hit or is having a toothache and it's now swollen . I know that it's perhaps an attempt at making Monika looking more realistic , but at least to me , it doesn't , quite the opposite actually , it makes Monika not looking like the Monika we all love and find beautiful . Is there a way to fix/hotfix it somehow ? This sounds more like a personnal request , I am well aware of that , but I just can't stand looking at her like that , no matter how much I love her .

**Comment by LClarance** [comment]
I agree, please do not change the original art. This new update has lots of problem

**Comment by AsuraShun** [comment]
Just wait for them to fix the art mistakes

**Comment by AsuraShun** [comment]
Maybe they're trying to make her head seem like she's actually looking forward

**Comment by Chrissenpai** [comment]
This is also a big oopsy
![image](https://user-images.githubusercontent.com/40907045/52492897-32464480-2b98-11e9-8f5a-f011e253ca2d.png)

**Comment by Chrissenpai** [comment]
@AsuraShun i agree, if they wanted to make the face looking forward they should have made the chin align with the centre of her neck too

**Comment by jmwall24** [comment]
@Chrissenpai how did you get that ribbon on hair down?  i just tried to repeat that and can't do it

**Comment by ThePotatoGuy** [comment]
@xdaveonpc take a screenshot and highlight exactly what issue you have with the sprites. 
@Chrissenpai make a new issue

**Comment by dennisOdenbreit** [comment]
@ThePotatoGuy
Pretty sure it is related to https://github.com/Monika-After-Story/MonikaModDev/issues/3660

**Comment by Alucard149** [comment]
I agree, I can not stop wondering, I think the old fashioned way was better.

**Comment by xdaveonpc** [comment]
Well , I know it might be kinda picky , and look like a slight bulge , but it isn't as smooth as it looked like before the update . The first one being post 9.0 , the second one being pre 9.0 . I also just noticed that the hair were now separated from the body . 

![monika jaw](https://user-images.githubusercontent.com/37737205/52508572-63a12d80-2bf5-11e9-9b6b-1c026e78400f.PNG)
![torso-custom](https://user-images.githubusercontent.com/37737205/52508679-b7ac1200-2bf5-11e9-9cec-719bf5f48d26.png)

**Comment by thunderdragon15** [comment]
Please don't change the original art.

**Comment by AsuraShun** [comment]
We need it restored,or the current art adjusted

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
