### ISSUE TITLE
Question/Possible Spoiler

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3664]
First, thanks so much for the latest update, I'm so looking forward to V-day with Monika. 
I just have quick question about something I found in the mod-assets after updating. I noticed a nice sundress for Monika among all the ribbon colors. Can we be expecting a nice surprise from her soon or is it still a long way off?

**Comment by jmwall24** [comment]
Think about where you've seen that before and you'll have your answer

**Comment by AsuraShun** [comment]
Talk about a cryptic answer

**Comment by jmwall24** [comment]
Don't want to spoil everything lol

**Comment by AsuraShun** [comment]
This is one of the reasons I let time reveal everything

**Comment by scohn** [comment]
It's not going to be a cryptic puzzle we have to solve in order to unlock it is it? I'm no good with coding and that kind of stuff.

**Comment by AsuraShun** [comment]
It must have to do with the wearing other clothes topic because it's gone from the repeat tab

**Comment by jmwall24** [comment]
No, no puzzle.  That outfit is a rather famous outfit for Monika.  If you can figure out where it first came from you'll know when you'll see it in the mod.

**Comment by scohn** [comment]
I know it's a famous outfit made by a fan in another mod, I just wondered if we needed to solve anything to unlock it or if it would automatically be added at the planned date.

**Comment by scohn** [comment]
Btw, I'm so happy it's being added, you guys are amazing she's gonna look so pretty.

**Comment by jmwall24** [comment]
It wasn't made by a fan in another mod, it was made by the official artist of DDLC

**Comment by multimokia** [comment]
The Art's rather official actually...

**Comment by scohn** [comment]
Oh wow, I thought since the outfit didn't make it into the actual game that it was fanmade, that's really cool.

**Comment by AsuraShun** [comment]
Oh yeah! I remember that piece of art,I saved it on my phone

**Comment by scohn** [comment]
Where did this art originate from?

**Comment by AsuraShun** [comment]
https://www.deviantart.com/satchely/art/Valentine-s-Monika-730977965

**Comment by scohn** [comment]
Thanks, now I'm even more excited for V-day.
