### ISSUE TITLE
Hair Ribbon Oopsy

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3666]
![image](https://user-images.githubusercontent.com/40907045/52494918-3e80d080-2b9d-11e9-82c9-8aa7a837a94e.png)

**Comment by ThePotatoGuy** [comment]
going to need exact replication steps because we have not been able to reproduce

**Comment by AsuraShun** [comment]
Why not just turn this into an actual hairstyle? It wouldn't be the first time a bug was turned into something official,kinda like what gave gta its origins

**Comment by AsuraShun** [comment]
But the bow would need to be smaller,and a tiny bow on both bangs

**Comment by Chrissenpai** [comment]
I repeated the steps but it actually got fixed, I guess the bug was because I changed the clothing right after the download of the game, so therefore I just closed and opened the game and it got fixed.

**Comment by jmwall24** [comment]
what clothes hair style did you start from?  was this from uniform with hair down ->santa

**Comment by Chrissenpai** [comment]
actually, I started with school clothes with white ribbon, but the ribbon was partially cropped, like an incomplete work at photoshop, then I changed the ribbon colour to see if the problem persisted and it got fixed, afterwards, I´ve changed back to Santa hair down, being first santa and then hair down, then, i wanted to change again and it appeared to me the change ribbon option (i said hmmm interesting, will it crash?) then I chose that and it displayed just like in the screenshot, with all the different colours available. Thats my story.

**Comment by jmwall24** [comment]
you had the change ribbon option available when hair was down?

**Comment by Chrissenpai** [comment]
indeed

**Comment by ThePotatoGuy** [comment]
[leaving this as a non-producible issue. investigations will reopened if we get another report]

**Comment by ThePotatoGuy** [comment]
[closing as no reports have come in]
