### ISSUE TITLE
Adding Items to MAS

### ISSUE THREAD

**Issue by nohumanallow3d** [Monika-After-Story/MonikaModDev#3667]
I would like to know how to add items such as ribbons and coffee/hot chocolate to MAS. I am not informed about how to and would appreciate someone telling me.

**Comment by AsuraShun** [comment]
Colorribbon.gift
Coffee.gift
Hotchocolate.gift
Quetzalplushie.gift
Promisering.gift
Cupcake.gift

Put them in the character folder,she'll detect them after a topic
Btw replace the color word with one of the available colors

**Comment by nohumanallow3d** [comment]
> Colorribbon.gift
> Coffee.gift
> Hotchocolate.gift
> Quetzalplushie.gift
> Promisering.gift
> Cupcake.gift
> 
> Put them in the character folder,she'll detect them after a topic
> Btw replace the color word with one of the available colors

thanks mate

**Comment by AsuraShun** [comment]
Np
