### ISSUE TITLE
Fixing issues with logs on Mac

### ISSUE THREAD

**Issue by aldoram5** [Monika-After-Story/MonikaModDev#3670]
As mentioned on: https://github.com/Monika-After-Story/MonikaModDev/issues/2423, https://github.com/Monika-After-Story/MonikaModDev/issues/3175, logs on the release version for mac don't work.
 I ~~finally~~ found why this happens. It seems that Ren'Py itself disables logs on mac apps, this can be confirmed by looking at the following links to the Ren'Py source code: [__init__.py#L333](https://github.com/renpy/renpy/blob/master/renpy/__init__.py#L133) and [log.py#L88](https://github.com/renpy/renpy/blob/master/renpy/log.py#L88). This basically means that using renpy.log on a Ren'Py game running inside a `.app` will never work.

We need to find a way to address this, some key aspects to consider

- There's definitely a reason why Ren'Py deliberately disables logs on mac apps.
- We could write or own/use another logging tool and keep the log on the same relative paths across platforms, but we may end up finding issues.
- If trying to write logs inside the `.app` package is somewhat troublesome/ makes more issues, we can always put them on a different place. Based on this [SO question](https://stackoverflow.com/questions/3820613/where-the-application-should-store-its-logs-in-mac-os), storing them on a hidden folder in the user's home folder would be the way to go.

**Comment by ThePotatoGuy** [comment]
approach from SO seems sensible.

could just replace `mas_log` with a direct file handler when on Mac, but i think we should extend the existing renpy log class and make a mac-only version so we don't lose out on any optimizations or whatever that code has.

**Comment by aldoram5** [comment]
I agree with that solution.

**Comment by ThePotatoGuy** [comment]
[fixed]
