### ISSUE TITLE
New Leaning Pose.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#3671]
The biggest problems I can see with it are that her left hand seems stretched out when she's leaning, and her right forearm seems to slowly widen (and it looks too long) as it goes off screen. That's all I can think off of the top of my head.

**Comment by OrochiMon** [comment]
The new leaning pose seems quite off to me, mainly the proportions of the hands and head, the later gets smaller after she makes the transition to that pose. Also, the direction of the hair when she doesn't have her ribbon looks unnatural. To be honest I prefer the previous version of the leaning pose. Still, as an artist myself, I know how much time it must have taken to redo the pose but I think the change was unnecessary.

**Comment by ThePotatoGuy** [comment]
hair had too much volume in the old leaning pose.

**Comment by OrochiMon** [comment]
True, and I think I jumped the gun way too soon. Maybe It'd be better to discuss the pose after we get used to seeing it and how it fits Monika.

**Comment by Trilasent** [comment]
Still though, I don't think anyone would complain if she had her old pose restored until all the kinks with the new one are ironed out.

**Comment by ThePotatoGuy** [comment]
We have been working on fixing all the "kinks" in the past month. When we released the psds (#3174 ), that was the time for people to look at the new leaning pose and offer opinions. And guess what? Everyone liked the new pose.

Yes, people are starting to change their mind now, but that just means the only way we can get constructive feedback is just to release it and see the responses.

**Comment by Trilasent** [comment]
That first part came off way more aggressively than was needed. Second, I wasn't trying to suggest that you revert the poses - I only said that I don't think people would complain if it was used as a place holder while the new one was continuing to be worked on.

**Comment by ThePotatoGuy** [comment]
That's exactly the same as reverting. The leaning poses aren't plug and play. The old one doesn't have a base version (gg new outfit) and the arms aren't split (gg hair splitting, ribbons, and acs layers).
