### ISSUE TITLE
[Bug] The new Quetzal plushie topic was both in the "ask a question" thing and the random topics

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#3675]
Ok, so I downloaded the latest unstable release, and i saw there was a new topic in the "ask a question" thing. I clicked it, and Monika thanked me for the plushie. But right after that i let monika talk randomly and she repeated the exact same thing? So i think theres a problem here

**Comment by multimokia** [comment]
Quick question for some clarification:
Did you find the topic in the `unseen` category? Or was it in the `ask a question` category? I'm not able to get it pooled. (it won't show up in `ask a question`)

**Comment by softombre** [comment]
I found it in the unseen category!

**Comment by multimokia** [comment]
Thank you!

**Comment by LClarance** [comment]
I did not have the plushie topic in unseen even tho I already gave it to her. May I know where to find it?

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
