### ISSUE TITLE
[Suggestion] - Having the Ability to respond with Monika more

### ISSUE THREAD

**Issue by Mazie1** [Monika-After-Story/MonikaModDev#3682]
Hi there, I'm new, and I made an account just to leave this suggestion.
I've had the mod for about a month or so now and I've always wondered..

Should there be more opportunities to respond to Monika more?

As she brings up her usual topics, she usually brings up a question asking if you've done said topic, or if you agree with her or not. I think it'd be kinda cool to have the ability to talk to her more rather than only bringing up a subject and let her talk it all out. For example, when she talks about internet being an addiction her last message is question. I want to respond to said question-- I sometimes feel like most of the topic conversations are one-sided, as well as the more personal questions about you. Of course, she asks for your response then, but not all the time. I'm unsure of how this could be implemented though. 

Perhaps it's like giving a little more freedom for the player? It's similar to a chat-bot, however I'm aware that was taken out due to various conflicts. Just something to talk to her a little easier, as well as encouraging/supporting when she starts to feel worried or having doubts. 

I think this would be a nice addiction to the affection as well. There being three or more choices, good, bad, and sweet (Giving the most affection.) I've seen several different messages of people at loss to try and get their affection up in different and unique ways while also keeping some gifts for special occasions. With the ability to speak to her more, with multiple new responses, I believe it could give an entirely new experience to the mod.

Thanks for reading, love your work!

**Comment by SaiPrithvi123** [comment]
Someone will have to write all of those responses

**Comment by Rai99** [comment]
#598, #630, #1614, #1627, #1689, #1751, #1932, #3078, #3554 

> The issue with that is that someone has to actually write this.

Yes, it would be cool to have more options to respond to Monika with, but the best chances of that happening are if a contributor writes them up.

**Comment by Buy1Get1** [comment]
^ the responses have included more options recently, but if you want a more 'interactive' function you could create several lists and a text box. The lists would act like the 'yes'/'no' with collections of answers equating to different responses.
 if i in GREETINGS:
    print("hi, how are you?")
    s = input()
    if s in POSITIVE_RESPONSES:
        print("that's great to hear!")
^ you'd have several _RESPONSES (or whatever naming convention you want)  for the user:
POSITIVE, NEGATIVE, NEUTRAL, OTHER

**Comment by Rai99** [comment]
I'm not 100% sure we'd take that approach, but even if we did, again, I think the main issue there is that somebody actually has to write all that, and that sounds like a lot. 

Yes, I know I'm insane with the size of some of my contributions, but I think that kind of approach has yet to be discussed. 

I think Mazie was just asking for more topics that allow you to respond in some way rather than be flat and one sided where Monika just says some dialogue without any input.

**Comment by Buy1Get1** [comment]
I think he's referring to something like the old text box MAS had. I've created several lists already, but they're more generic. I think more general responses would be handled first, then it's a matter of copy and paste. I know that MAS has moved away from the text box, but I recommend it the devs ever decide to dust it off. However, as you said, it's a lot and might not even be attempted.

**Comment by Mazie1** [comment]
Is there a chance it will be attempted in the near future? I'd love to interact with her a little more; it has more things to do. I understand that there may be other more important subjects to do, but how about doing a little each day, and release it when it's completed?
And yes, I was asking for that, Rai99. I think it'd be cool, is all.

**Comment by ThePotatoGuy** [comment]
The pool topics are meant for the user-driven topics.

there is also a slow push to add menu choices to everything.

just takes time and people to write that.

No plans to re-add text box. it honestly was terrible.

[closing as duplicate]
