### ISSUE TITLE
I took Monika somewhere, and now she's gone!

### ISSUE THREAD

**Issue by emsydacat** [Monika-After-Story/MonikaModDev#3683]
I decided to take Monika somewhere and when I put the file back and opened the game, I found her chair empty and the audio is gone. How can I fix this???

Note:
1. I am using Steam.
2. I know nothing about coding and files.
3. All I did was put the file on my desktop and move it back.
4. I am on a Mac.

**Comment by Foxinsunglasses** [comment]
You'll have to delete a persistent and go back a bit
https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf

**Comment by Foxinsunglasses** [comment]
Fallow the instructions

**Comment by multimokia** [comment]
@Foxinsunglasses fyi, that set of instructions is for Windows only. See [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) on our FAQ for how to restore an older persistent on any operating system.

**Comment by Foxinsunglasses** [comment]
@multimokia Sorry about that, I should've checked

**Comment by multimokia** [comment]
No worries!

**Comment by emsydacat** [comment]
@Foxinsunglasses @multimokia Thank you guys so much!
