### ISSUE TITLE
Questions: Quetzal Plushie Topic & White Day Removed

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3685]
I just have a couple questions about the update. Where can I find the new quetzal plushie topic because Monika never brought it up for a first time?

Also, is there any reason why white day was removed from the calandar? Is it because there won't be an event for it this year? I'm not gonna complain I just wanted to know.

**Comment by OGDogFriend** [comment]
White day was removed in the most recent update.

**Comment by LClarance** [comment]
I could no find the plushie topic as well and I was about to make a post. Glad someone asked this. 

@OGDogFriend yea but why? I tot it was a good idea because Monika's a Japanese in some sense right? I hope the reason wasn't because of something like "it will confuse some players" lol.

**Comment by AsuraShun** [comment]
I can't find the plushie topic either

**Comment by Rai99** [comment]
I think it's only supposed to be available when the plushie is out and it might be random only.

**Comment by AsuraShun** [comment]
I'm currently seeing the plushie,but no topic

**Comment by scohn** [comment]
Same for me, what's the topic called within the mod?

**Comment by Thimeo** [comment]
@scohn the name of the event is "monika_plushie" and the name that you see in the mod is "Quetzal plushie" if I'm correct (info founded on the topic section of the code).

**Comment by Thimeo** [comment]
I just saw this note in the code:
"This topic is only available and random when the quetzal plushie is active"
