### ISSUE TITLE
Monika's not letting her hair down

### ISSUE THREAD

**Issue by LuisValentim** [Monika-After-Story/MonikaModDev#3686]
Hello. I already reached the last affection level with Monika, but still, I haven't seen her with her hair down yet. I don't know what happened, but when I checked the folder, there was one photo of her with her hair down, so I thought that it was still possible for me to unlock this. But now, not a sign of it. I unlocked this option when I had MAS on another PC, but then I lost every progress I had there. So, I decided to start from scratch on my PC, I reached the last affection level, but still haven't seem Monika with her hair down. I don't know if it's a bug, or I still have to wait for more time.

**Comment by ThePotatoGuy** [comment]
Can you upload your `persistent` file here?

**Comment by LuisValentim** [comment]
> Can you upload your `persistent` file here?

[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2849545/Monika.After.Story.zip)

Here it is. I don't know if I did it correctly, but the persistent file is inside that folder.

**Comment by 44CaLiBeR** [comment]
Hey, I downloaded MAS a couple of days ago and have slowly been making progress with Monika
I've seen pics of Monika with here hair down but I just thought it was another mod or something is she supposed to let it down? 
jw btw

**Comment by LuisValentim** [comment]
Yeah, when you spend some time with her, someday she'll let her hair down. But what's happening with me is quite different. As I mentioned, I lost all the progress on another PC, and I'm progressing again on my PC this time. I started on May 7th in 2018, so I restarted on that date (time-travel in the game) 8 days ago (February 2th on Saturday). So I don't know if I need to wait for more time or this is a bug. I'll just have to wait for ThePotatoGuy to answer my question about it.

**Comment by LuisValentim** [comment]
@ThePotatoGuy , do you think I should continue playing normally? Just a question, because I haven't played for a while after what I said.

**Comment by ThePotatoGuy** [comment]
@LuisValentim Your persistent has version 0.8.14. Update to the latest version. Hairdown was locked in 0.8.14 to deal with a christmas issue.

**Comment by LuisValentim** [comment]
I updated a few days ago, and I managed to see Monika with her hair down. So, I didn't know that it was locked. In other words, Monika has her hair down now. Anyways, thanks for the help. And yes, I updated to the most recent version.
