### ISSUE TITLE
Clothes - Nightgown

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#3689]
#3174
The nightgown first seen in the [sleepover art.](https://pbs.twimg.com/media/DeeegbzU0AAq4O7.jpg:large) Related to sleep mode.
note: Will start working on it after being done with blazer rework (#3631) and the base is finalized.

**Comment by AsuraShun** [comment]
awesome!She looks beautiful in it

**Comment by AsuraShun** [comment]
Can't wait to see how it'll look in the mod

**Comment by EntonyEscX** [comment]
We trust in your work!

**Comment by ThePotatoGuy** [comment]
@Velius94 , for sleep/bedroom mode, we're also looking to have a laying down version of Monika so users can sleep next to their laptops like they actually sleeping next to Monika. For that we need a laying down base. For expressions, we're thinking of just rotating them to fit said base.

If you want to do nightgown, think you can do a laying down version + base for it?

**Comment by Velius94** [comment]
Not quite sure about the base, never tried doing that before. Might wait for someone to make one instead.

**Comment by Velius94** [comment]
[closing until relevant assets are available]
