### ISSUE TITLE
[Suggestion] - Monika's suit

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3690]
Yesterday, I saw [this post](https://www.reddit.com/r/DDLC/comments/aout2x/thats_how_mafia_works_hej_monika/) on reddit, and I thought that it rendered quite nicely for just a changing of color of her school uniform and some minor adds (like the tie). So i wanted to submit the idea that if we need a suit for Monika (even if I have no idea for what purpose), that it could be done easily and looking somewhat good and professional, without the glasses of course.

**Comment by AsuraShun** [comment]
I really hope the glasses aren't added

**Comment by kaido1224** [comment]
Monik in a business suit is already in our wish list i believe.

**Comment by ThePotatoGuy** [comment]
I have added our outfit wishlist to #3174 . Art suggestions that are already in our wishlist should be makred as duplicate from now on. (and linked to our main issue)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate[
