### ISSUE TITLE
Normal Monika sprite bug?

### ISSUE THREAD

**Issue by truesonic53** [Monika-After-Story/MonikaModDev#3691]
Just a small thing I noticed when I got Monika in the MC's room (that one greeting when you open the door)
There's some space between composite parts of her normal sprite: there are lines between her body and her head and also between two halves of her body. Pic attached (it's pretty easy to notice in fullscreen mode)
![screenshot0023](https://user-images.githubusercontent.com/39985357/52539794-4a35e800-2d93-11e9-9f65-d63dac1455e1.png)

**Comment by dennisOdenbreit** [comment]
I didn't see it at first, but yeah, the parts seem to be placed a pixel too far apart.
I wonder how that has happened...

**Comment by AsuraShun** [comment]
I have to ask,what exactly did you do for her to have that disappointed face?

**Comment by truesonic53** [comment]
@AsuraShun when I launched the game it greeted me with open the door/knock/listen choice and I picked the first one

**Comment by ThePotatoGuy** [comment]
known bug, very low priority to fix though since the greeting is relatively rare.
#3490

**Comment by ThePotatoGuy** [comment]
[closing this as duplicate]
