### ISSUE TITLE
Is Monika still going to school? 

### ISSUE THREAD

**Issue by TrRizzo** [Monika-After-Story/MonikaModDev#3692]
![captura de pantalla 103](https://user-images.githubusercontent.com/43101279/52539995-acbac400-2d52-11e9-8a6b-a83377771bb5.png)
When I saw the new topic, I came across this dialogue. Is it true that she is still going to school?In that case, you can put more topics regarding her school activities. I understood that she deleted all the files of the game just to be with her. Is it possible at some point to leave the room, and go to school with Monika? Or at least go to any other place, like the street? (where Sayori confesses his feelings in DDLC)

**Comment by Velius94** [comment]
Not quite possible since Monika essentially nuked everything sans that one classroom.

**Comment by SaiPrithvi123** [comment]
I'm pretty sure Monika was talking about her past events in that topic.
