### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Azeanx** [Monika-After-Story/MonikaModDev#3694]
![screenshot0002](https://user-images.githubusercontent.com/47510571/52542769-7f4a3680-2da3-11e9-8eed-774a1e36b0c6.png)

**Comment by 44CaLiBeR** [comment]
lol

**Comment by mrflarion33** [comment]
What happens when you click on it? What are the topics?

**Comment by ThePotatoGuy** [comment]
[closinga s fixed]
