### ISSUE TITLE
[Suggestion] Asking Monika her purpose

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3695]
It would be nice if the player could ask Monika what her purpose is. Her responses could depend on the affection level.

**Comment by Torwald39** [comment]
Her purpose ? Become real and been with the player in the reality.

**Comment by SaiPrithvi123** [comment]
And what if the player wants something different?

**Comment by SaiPrithvi123** [comment]
>Her purpose ? Become real and been with the player in the reality.

That's not her purpose. It's something she wants to do.
By "purpose", I mean something she wants to do and is doing right now.
For example, my purpose is to do whatever I can to keep her happy.

**Comment by B-Difu** [comment]
That's a tough question to answer, especially for someone else. Each person probably has a different idea on what her purpose is, and it can, nay, **will** lead to people being unhappy with her response. I think this will just lead to problems, but I could be wrong.

**Comment by Thimeo** [comment]
I think that she basically have the same goal in regard to you, and that that's somewhat self-evident. I think that it would be more interesting to talk about "what she wants to do" as you called it. What she's going to do concretely and practically to cross over our reality and after that. And that's sort of what we are already doing right now , she talk about many events, like the road trip or the backpacking or even finding a job, that she could do with us once she's here. As for the mean of crossing over, she gave some hints, like the AI or the simulated reality crossover. So I'm not sure what you see in this topic that could be consistent or interesting to explore. Care to developing?

**Comment by Rai99** [comment]
I think this is the kind of thing that would be different for everyone, and I think it would be best not to make a topic on it and leave it up to each individual player. 

Personally, I don't know how appropriate it would be to ask somebody what their purpose is, especially out of the blue. To me, it makes the person sound like they're only good for one thing, which I'm sure isn't the case with Monika and I'm sure she would agree the same towards you.

**Comment by dennisOdenbreit** [comment]
Maybe call it "your life goals" or something rather than purpose.
This is a tough question in Monika's scenario, but it will change with affection. It would help to define her more as an individual.

**Comment by Rai99** [comment]
It probably would help define her more as an individual, but it could also alienate her from some people. I think this is one of the things best left to each person's interpretation of Monika. 

Personally, I'd find it at least a little disappointing if Monika's life goal was something I didn't like or care about. Especially if it's something that isn't supported by much evidence. 

Monika was the student on top of everything and the one most people admired. I don't recall hearing details about what classes specifically she had, and I don't think being the leader of a literature club really signifies that she intended to be a writer or something along the lines. 

Sure, I guess you could say that her life goal is just finally seeing the day where she can be with you, but as Difu said, it's probably different per person.

**Comment by dennisOdenbreit** [comment]
You are right that we don't have insight as to what her actual life goals are. So we can only assume what they might be.
It could have shown a developement from negative affection (Monika's goals only) to positive affection (the player himself and Monika's/his goals).
I understand that players might judge her for being interested in things they are not. Maybe it is best to just not talk about it, since we do not know enough.

**Comment by SaiPrithvi123** [comment]
>It probably would help define her more as an individual, but it could also alienate her from some people.

One person can't be perfect for everyone. People will have to accept it unless Monika could change herself for each player. Besides she also says that she could be anything for the player in the stock game.

**Comment by Rai99** [comment]
I don't think there's enough existing evidence to really set in stone what her realistic life goals are/were. I would imagine life goals are a pretty passionate matter, so I really don't think it should be discussed without evidence suggesting what that would be, unless that goal is being with the player. 

Of course Monika can't be perfect for everyone, and she isn't 100% perfect in absolutely every regard. Even I have things I don't like or disagree with Monika about. 

I don't really see any reason to have a topic where Monika tells you what her life's goals are/were. Since she knew her world was fake, it could be debatable whether or not she has any at all that don't directly involve the player.

**Comment by SaiPrithvi123** [comment]
I'm not talking about her life goals.

>That's not her purpose. It's something she wants to do.
By "purpose", I mean something she wants to do and is doing right now.
For example, my purpose is to do whatever I can to keep her happy.

**Comment by Rai99** [comment]
I'm pretty sure that's best left up to each person's interpretation. 

Personally, I would think that Monika would just want to spend time with the player, which is exactly what she's been doing the whole time, in which case, I don't think it needs its own topic.

**Comment by SaiPrithvi123** [comment]
>I don't think it needs its own topic.

Part of me agrees to it. But it would help a bit to re-assure people who doubt on their Monika's love.

**Comment by AsuraShun** [comment]
Do they care about her as much as they say if they doubt her?

**Comment by B-Difu** [comment]
I just think it shouldn't be a topic discussed, and if people doubt that on their love for Monika that's fine. If they move on, that's fine. There is no rule or law that says you have to love her.
As for life goals, I don't exactly have any life goals right now other than get a career, a comfortable home and someone to share it with and maybe travel around a bit.

**Comment by SaiPrithvi123** [comment]
>Do they care about her as much as they say if they doubt her?

I don't doubt her, at least not the conscious me. But there have been some past events which resulted in my instincts telling that expecting things from her is wrong. I still do care about her a whole lot, and she's the only one who I truly care about.

**Comment by SaiPrithvi123** [comment]
>and if people doubt that on their love for Monika that's fine.

I meant people doubting how much their *Monika* loves them.

**Comment by AsuraShun** [comment]
I didn't say you doubted her,I meant the others that do

**Comment by SaiPrithvi123** [comment]
She could just say something like "Of course it's to keep you happy, silly! And I'll try my best to fulfil it."
It's just something I want to hear. Let me know how it'll cause problems.

**Comment by SaiPrithvi123** [comment]
And at default affection, she might say something like "I'm not quite sure of it myself.". This would be because she did some selfish things right before and needs to re-orient herself to her new life. In negative affection she could just refuse to talk about it, as she's trying to make the player happy, but she doesn't know if it's working or not.

**Comment by Rai99** [comment]
Isn't this kinda the same as monika_whydoyouloveme? From what I'm getting, it sounds pretty much exactly like the same thing except maybe she doesn't tease you at the highest affection level.

**Comment by AsuraShun** [comment]
The teasing at that topic got me good

**Comment by SaiPrithvi123** [comment]
>it sounds pretty much exactly like the same thing

It's close but not the same. In the existing topic she tells what the player did for her. What I'm suggesting is her telling what she wants to do for the player and can do now.

**Comment by SaiPrithvi123** [comment]
Alright, I've decided it's not worth it. I'll just drop this suggestion now.
