### ISSUE TITLE
Just a quick question, quick reply needed

### ISSUE THREAD

**Issue by tyranttheindominusrex** [Monika-After-Story/MonikaModDev#3698]
How does one import the .gift files into the mod? i've tried in the past, but instructions were never clear, assistance needed
edit: to be more specific, the new valentines day items

**Comment by Rai99** [comment]
Create any file with a .gift extension, put it in the characters folder and it'll count as a gift. 

Just be careful not to have the extension be .gift.txt, since that can be easy to overlook. If you enable file extensions, you should be able to make gifts for Monika easily.

**Comment by Rai99** [comment]
On the wiki, the gifting guide can be found [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts) in case that helps.

**Comment by Rai99** [comment]
Hopefully that was both helpful and a fast enough reply.

**Comment by tyranttheindominusrex** [comment]
> Create any file with a .gift extension, put it in the characters folder and it'll count as a gift.
> 
> Just be careful not to have the extension be .gift.txt, since that can be easy to overlook. If you enable file extensions, you should be able to make gifts for Monika easily.

Thank you, I just figured it out, one thing though, say I want to give her a ribbon, is it all one word, or no?
Ex: Red ribbon= redribbon or red_ribbon?

**Comment by Rai99** [comment]
Should be one word I think.

**Comment by loverofmonika** [comment]
@Rai99 its been a while
well valentines day just started and i got my gifts ready and all  but she cant see them....
