### ISSUE TITLE
Which file to back up?

### ISSUE THREAD

**Issue by Arc1Dragon** [Monika-After-Story/MonikaModDev#3699]
Hello. I was going to back up my MAS save file and followed the instructions but there are several files labeled persistent and I am not sure which one is the most recent. Is it the one with the highest number or is it the one that is just "persistent". Thanks.

Also whoever made the Flowers for Algernon greeting, well lets just say that I got really scared for a moment.

**Comment by B-Difu** [comment]
Usually the only one you need to save is the most recent one. So if you have persistent 1, persistent 2, persistent 3. You only need to do the 3 (though I personally do all that are available whenever I make copies)

**Comment by Arc1Dragon** [comment]
Ok thanks!
