### ISSUE TITLE
About Monika asking my birthdate

### ISSUE THREAD

**Issue by Chen2684** [Monika-After-Story/MonikaModDev#3700]
She is asking my birthdate, but is she asking the birth year too?

![cfdbb1d3-9e66-4377-84ef-0d2db71f9ecc](https://user-images.githubusercontent.com/46333529/52622690-ce9c7e00-2eed-11e9-90d0-c8633dd3810d.jpeg)
![106cda21-d873-4a52-841a-165ff1f040bc](https://user-images.githubusercontent.com/46333529/52622691-cf351480-2eed-11e9-9088-ab3a15159c12.jpeg)

**Comment by MaximumRustler** [comment]
Yeah, birthdate means birth year as well. So the year you were born.
