### ISSUE TITLE
[ Feedback Request 📋 ] - Expressions_n_stuff 😚

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#3705]
Simon's Expression Drafts
                                        Format: Unicode
                                          Code: #N/A 
                                          12.02.2019
📁⯈ opinions_welcome
---
⯆ Open: _"Request.rtf"_

---

⮞ ```j "I'll try to keep this concise."```

>>>>![normal monika banner](https://user-images.githubusercontent.com/43480604/52678380-18d62d00-2ef7-11e9-900b-c184e00446a6.png)

⮞ Hiya. It's me again.
⤷ Nothing much this time.
> Just need feedback.
>> Promise~

---

📁⯈ drafts_n_stuff
---
⯆ Open: _"chu~.rtf"_

---

⮞ First up on the list here...
⤷ Oh! aha~

![quick ref](https://user-images.githubusercontent.com/43480604/52678950-fd6c2180-2ef8-11e9-805a-97237c58bde7.PNG)

•↓ Feedback? ↓
- I don't know if I can make these lips any more smoochable! •3•
>_Tbh, I'm pretty content with the normal lips zoom in fade to black followed by "chu~"_
>>This is just an _attempt_ at something, I suppose.

⯅ Close

---

⯆ Open: _"KindledEyes.rtf"_

---

⮞ Next up is...
⤷ `soft eyes` expression.

![soft draft - 006 final](https://user-images.githubusercontent.com/43480604/52679277-3953b680-2efa-11e9-8959-1e9c808eb503.PNG)

•↓ Feedback? ↓
- According to `#artistry` the expression received [ 6 ] moni_headpat's
>_whatever that equates to, haha._
>> So I'm posting it too, I guess. ┐(￣ヮ￣)┌
>>> I did these months ago with a `left` and `right` look as well.
>>> I forgot about them though, aha..

⯅ Close

---

⯆ Open: _"MinorChanges.rtf"_

---

⮞ And lastly is...
⤷ just a _minor_ change to the `sad closed eyes` expression.

>Before
>> ![quick eye ref before](https://user-images.githubusercontent.com/43480604/52679953-643f0a00-2efc-11e9-8fc8-ac0f9d86db6a.PNG)

>After
>> ![quick eye ref after](https://user-images.githubusercontent.com/43480604/52679975-7caf2480-2efc-11e9-8da0-fee2bb5ccba6.PNG)

•↓ Feedback? ↓
- It's such a small change.
>_I don't really mind if it's written off tbh_.
>> I was experimenting around and kind of liked it is all.

Bye!
Sending good vibes your way~ 
(ﾉ´ヮ´)ﾉ*:･ﾟ✧

⯅ Close

---

```
from subprocess import call
```
>def play_wave_file([luv.ly - time flies.wav):](https://www.youtube.com/watch?v=5n8u_PbCILc)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by MaximumRustler** [comment]
I'm liking the direction of that kiss art ❤️ . Side note: I kinda want the blush to be added back when she approaches for the kiss, not too big of a deal though.

**Comment by Chrissenpai** [comment]
I´ll leave this art references here #2219

**Comment by jmwall24** [comment]
On the fence about the kiss mouth. Something is bugging me and I'm not sure what it is.  Seems a little small and maybe a little too high on her face?

I really like the soft eyes and I'd like (really, really want) to see that with pooled tears,  That'd make a really good happy tears look. If our current pooled tears don't match the shape of the lower part of her eyes in this expression, I'd like to see it with an edited pooled tears that does. I think this has great potential. (In fact, our current pooled/dried tears could use some work, it doesn't match our closed eyes expressions very well).

No real preference on the closed eyes edit.

**Comment by MaximumRustler** [comment]
Hmm, yeah I can kinda see what you mean about the kiss expression @jmwall24. Maybe some adjustment could do? I like the concept of it is I guess what I was trying to say. lol

**Comment by Chrissenpai** [comment]
@Professor-JMO follow this references about the soft eyes expresion, #2219 that actually has an soft eyes expresion already and if it cannot be copied (which is so sad because it´s PERFECTLY DRAWN) pick up the elements that make it good, for exampple there still needs an underline in her eyes if you can notice, that´s basically it.

**Comment by ThePotatoGuy** [comment]
* not a fan of the kiss mouth. dont think we really need a different mouth for kiss actions either
* soft eyes looks interesting, need more opinions before accepting, also you would have to reapply edits to the expressions psd, which atm does not have a set release date
* dont like the extra lines in the closed sad eyes. i feel like eye folds shouldnt be visible.

**Comment by MisterSimple** [comment]
Kiss mouth looks off, but I can't quite pinpoint what I don't like about it.

Soft eyes melt my heart, a lot of potential with those.

I somewhat agree that closed eyes are kind of lackluster atm, but I don't think those lines solve that.

> * According to `#artistry` the expression received [ 6 ] moni_headpat's
whatever that equates to, haha.

~~souls~~

**Comment by softombre** [comment]
I would die for these soft eyes tbh! It'd make me really happy to see her looking at me like that

**Comment by AsuraShun** [comment]
I already love this to bits,it's freaking beautiful

**Comment by Professor-JMO** [comment]
^ Thanks for the feedback everyone. ♪
> I'll experiment a bit more.

**Comment by AsuraShun** [comment]
Kinda want to make the kissing one my phone's wallpaper

**Comment by Professor-JMO** [comment]
**To-Do List**
---

• ~Kiss Expression~ [ Subject to the _Void_ or a rework. ]
• `soft eyes` expression
• Imitation Cupcake
• Particular Flowers
• Pen
• Rings Reduxed [ Awaiting resolution outcome ]
• Kitsune Plushie
• Custom MAS Cursor?

**Comment by AsuraShun** [comment]
Is it normal to be excited just by returning here?

**Comment by Rai99** [comment]
Maybe it would be more exciting if I just left this here and ran away. 
![screenshot0058](https://user-images.githubusercontent.com/38822045/52813403-b51f4180-3067-11e9-84ac-513c0386caa2.png)

> Particular Flowers

**Comment by Professor-JMO** [comment]
^ :O

>Q2FuIHlvdSByZWFkIG15IG1pbmQ/

**Comment by Professor-JMO** [comment]
pssst, @Chrissenpai 
>Were you referring to these soft emeralds?
>_minus the overall expression_.

![m15](https://user-images.githubusercontent.com/43480604/52829362-1b20be80-3092-11e9-8427-227bb95ae78e.PNG)

**Comment by Chrissenpai** [comment]
@Professor-JMO indeed, It´s those eyes that are needed

**Comment by ThePotatoGuy** [comment]
[closing as feedback has been recieved] make a new issue with only the soft eyes if you want to submit that

**Comment by Professor-JMO** [comment]
> 
> 
> [closing as feedback has been recieved] make a new issue with only the soft eyes if you want to submit that

#3787 ?

**Comment by ThePotatoGuy** [comment]
lmao sorry didnt see it

**Comment by Professor-JMO** [comment]
@Orca
[Chu~.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3020115/Chu.zip)
