### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Jose190** [Monika-After-Story/MonikaModDev#3706]
![screenshot0015](https://user-images.githubusercontent.com/47601477/52718451-e3265800-2f79-11e9-8373-153f3dd14e5f.png)

''The birds paid no heed to the Shallow's words, AND BY AND BY the hemp grew up was made into the cord, ¿and of the cords nets were made?.''

**Comment by dennisOdenbreit** [comment]
Typo.
I guess "and by" should be "the time".

**Comment by Rai99** [comment]
Maybe there should be a comma after the second "by" and that might help with the flow of the sentence. 

A comma after "cord" could probably help with flow as well.

**Comment by ThePotatoGuy** [comment]
put all typos in #3656
