### ISSUE TITLE
V-Day Gifts Spoiler

### ISSUE THREAD

**Issue by NpthingLeftButMe** [Monika-After-Story/MonikaModDev#3707]
Hello,

I'm preloading Monika's gifts for tomorrow and I got the most things that were already on the list. But snooping through the assets files I found the bracelet and necklace and was wondering what is the specific words to add them for tomorrow. Thank you and have a great day, cheers. Also great work guys once again.

**Comment by AsuraShun** [comment]
They're related to this 
https://www.deviantart.com/satchely/art/Valentine-s-Monika-730977965

**Comment by NpthingLeftButMe** [comment]
No i mean whats the specific key words ie. Nitenecklacegold.gift or bracelet.gift kinda way for those two.

**Comment by AsuraShun** [comment]
They're part of the outfit

**Comment by NpthingLeftButMe** [comment]
Ah. Awesome thank you for the information.
