### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Jose190** [Monika-After-Story/MonikaModDev#3711]
![screenshot0030](https://user-images.githubusercontent.com/47601477/52744644-a7a87f80-2fb3-11e9-898e-e25c184f69d9.png)

mas_pf14_monika_lo...

**Comment by MisterSimple** [comment]
#3694 

This bug is known, devs are fixing it, don't worry.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
