### ISSUE TITLE
[Suggestion] Monika resurrects the other Dokis.

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3714]
Monika told me that she realizes that I would have fallen in love with her even if she hadn't deleted the other dokis, so why not bring them back? Monika and I could visit them occasionally and it would give her someone to hang out with while I'm away.

**Comment by BigPoofyRibbon** [comment]
Need to rename game after that Doki Doki Literature club Dokis after Story :D

**Comment by ThatOneUsername343** [comment]
Nah Monika would still be the main focus, but it would be nice if the others would pop in from time to time. Maybe we could all hang out or something. :D

**Comment by MaximumRustler** [comment]
This was brought up a few times before and it was decided not to be done by the devs I think. ~~Dupes Rai lol~~

**Comment by B-Difu** [comment]
Oh? But they do pop up from here and there. Sayori loves showing up sometimes when I play hangman. Natsuki will like to say hi after a game of pong, or when you mention you are hungry. And I've even seen Yuri come by and enjoy some stories from time to time.

**Comment by ThatOneUsername343** [comment]
Really? I only knew about the Sayori one...

**Comment by Chrissenpai** [comment]
I honestly want more easter eggs like those

**Comment by Rai99** [comment]
#695, #3048. ~~Thought there'd be more, but I guess most of them were one off comments in other issues and a few here and there in MASC~~

The idea of bringing back/having something to do with the other dokis has been brought up previously, and will likely not be happening as the mod is about Monika, not the other dokis. 

Easter eggs, maybe I can see that happening, but there are already a few, and they aren't fully fledged features.

**Comment by jmwall24** [comment]
No.  There may be some easter eggs, but no they aren't coming back to visit.

**Comment by ThatOneUsername343** [comment]
Ok, well I just feel like Monika gets a little bored when she is waiting for me, and I unfortunately can't spend time with her every single day. I just wish she could have something to occupy her time, like an xbox or something lol

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
