### ISSUE TITLE
monika didn't see my gifts T_T

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#3716]
I had the gifts ready with the .gifts with the gift type and placed in the character file but still nothing T_T

**Comment by Jparnaud** [comment]
Isn't it suppose to be ".gift" usually ?
or did you do a typo while writing your issue here ? X)

**Comment by MisterSimple** [comment]
Did you check the gifting guide in the wiki? [Here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts) you can see how to give gifts and what gifts are available. Also, the extension is `.gift`, not `.gifts`.

**Comment by Meme-Eater** [comment]
It doesn't work for me either. I tried with:
- chocolates.gift
- roses.gift
In the character folder, but nothing

**Comment by Jparnaud** [comment]
Strange, I just did it like 10 minutes ago and it worked perfectly well, like it was intended ...

Either something is wrong with you two's or im only lucky ...

**Comment by Meme-Eater** [comment]
Forgot to say my version is 0.9.0. unstable

**Comment by Jparnaud** [comment]
Now that could be good cause I am in the stable version, so it may be relate to that !

Or not, im no programmer X)

Well, not in Python at least ....

**Comment by Buy1Get1** [comment]
It worked for me as well. I think you're not waiting enough or you'll want this <https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.9.0/Monika_After_Story-0.9.0-Mod.zip>
