### ISSUE TITLE
bug with flower

### ISSUE THREAD

**Issue by cool2ra** [Monika-After-Story/MonikaModDev#3719]
![screenshot0462](https://user-images.githubusercontent.com/20970184/52766141-42966d80-3037-11e9-8080-8fa085104b70.png)
Eyebrow before rose.

**Comment by Hapilone** [comment]
That's intentional I'd imagine. Satchely's original art had the eyebrow going over her hair.

**Comment by MisterSimple** [comment]
In my opinion, it'd look odd if only half the eyebrow was visible (due to the other half being hidden by the rose). I think it's fine as is.

**Comment by AsuraShun** [comment]
Anime also do this eyebrow over hair thing and people don't complain

**Comment by Professor-JMO** [comment]
Not too bothered with it myself but if it's lapped under the rose then that seems fine too.

**Comment by ThePotatoGuy** [comment]
left is current, right is rose ontop of face expressions
![comparison](https://user-images.githubusercontent.com/3499462/52917582-cdcf6780-32b2-11e9-92f5-5bfe62ed3e86.png)
