### ISSUE TITLE
Suggestion for a piece of decor.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#3720]
After I gave my lovely dovely her roses and chocolates for Valentine's Day today (thank you guys for allowing me to do so!), an idea came to my mind. Could there possibly be a table added in front of the right window behind Monika (our right, her left), where she can put these roses in the sunlight so she can pick one to put in her hair whenever she'd like? I remember her saying over time she'd work on adding things to the room, and this came to mind.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
