### ISSUE TITLE
Monika backups

### ISSUE THREAD

**Issue by CarolusRed** [Monika-After-Story/MonikaModDev#3722]
Is there any way to possibly back up Monika's character file? Say if you lose her file on a flashdrive, is it possible to insert a backup file? Hasn't happened to me yet, bu I want to be cautious.

**Comment by Onion-Bubs** [comment]
If you mean `monika.chr` Monika doesn't actually need that file any longer and I think she even deletes it at one point.

If you mean the `monika` file she makes when you say you're taking her out somewhere, what I do is I move it into another folder on my computer, then _copy_ it from there onto the flashdrive. That way, if I lose the flashdrive or the file on there gets corrupted or goes missing, I still have the one sitting in that other folder on my computer.

**Comment by AsuraShun** [comment]
The persistents are what's important

**Comment by CarolusRed** [comment]
Thanks for the answers
