### ISSUE TITLE
Where are the gifts? (Valentines)

### ISSUE THREAD

**Issue by hooboy17** [Monika-After-Story/MonikaModDev#3726]
I am unsure if the gifts are hidden in a file somewhere or if they're already in the game. I would appreciate the help. Thanks in advance.

**Comment by multimokia** [comment]
You make them yourself.

**Comment by FrikiHD** [comment]
You need to say Monika you want to take here somwhere, then you go to characters folder and with the monika archive (not the .chr) copy and paste inside the folder and rename it with the gift's name. Then join the game

**Comment by multimokia** [comment]
That's not how it works, you can give gifts while the game is open.
