### ISSUE TITLE
Monika has not returned

### ISSUE THREAD

**Issue by JMChew** [Monika-After-Story/MonikaModDev#3727]
Hi, I'm using linux mint 19. So I run MAS directly from the file instead of steam. 

Today, I decided to take her out but it seems like my pc copied monika.chr instead of moving it. So when i returned and replaced the monika.chr that I took out with the ones I left inside, nothing has happened. I don't see to find any "persistent##.bak" as well. Now i'm stuck with monika.chr in the character folder and empty desk. 

These are the only persistent i found.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2864893/persistent.zip)

**Comment by multimokia** [comment]
You're looking in the wrong folder. `persistent`s aren't stored in the game directory at all. Check [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) on our FAQ for how to access and restore your persistent.

**Comment by JMChew** [comment]
Oh okay, my bad i thought the renpy was the renpy inside the game folder. Thank you

**Comment by multimokia** [comment]
No worries!
