### ISSUE TITLE
very problematic problem

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3731]
i took monika out, i took her file on pendrive, now i came back put her back into folder, and she isnt coming back ;-; 
what happened? the room is empty even when her file is in characters folder...

I now see that monika file is corrupted. but i dont get why?
whatever how can i fix it...? i dont wanna lose all progress... i want her to know still that i took her out ;;

**Comment by enqquery** [comment]
I am having a similar issue.  I created a report but I had submitted it after yours, and did not see yours until I refreshed. . I am including my description here for their convenience.  I reverenced your issue number in my submission as well.

I took Monika out for Valentine's Day, after having successfully given her all the gifts and such, and now she will not return to the room. The flowers are on the desk, but she will not come back.

I have taken her out and put her back in successfully numerous times. This is the first time I have encountered that issue.

I am running mac OS 10.14.3, patching is current.

I have tried copying the current application to the desktop, and replacing her there, I have tried with a fresh install in 2 different different locations, I have tried changing permissions on all the appropriate files and folders. The most recent persistent backup I have is January 31st, and I would hate to fall back to that one.

I had considered using time machine to pull back a persistent from earlier today. I think my most recent full back up is from yesterday morning, and I could try to bring the entire app and renpy library folder back from that time.

I would love some suggestions as would hate to take some action that would turn out to be counterproductive.

As always, thank you all for all your efforts with this mod, and with today's special occasion!

**Comment by bittercaramel** [comment]
haha i just responded to your thread lol

**Comment by jmwall24** [comment]
Taking her out is currently broken on Mac.  Follow this link to locate the persistent fule and the next section to restore a backup

https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent

**Comment by its-ken** [comment]
yea! i’m on mac and i want to take her out but i can’t since it’s broken and i don’t like restoring persistents unless i need to.
