### ISSUE TITLE
i cant update

### ISSUE THREAD

**Issue by Hentai-Master** [Monika-After-Story/MonikaModDev#3734]
its seems that every time I copy the files and launch the game, it keeps telling me there's an update

**Comment by multimokia** [comment]
Are you also copying the `update` folder?

**Comment by Hentai-Master** [comment]
Yes

**Comment by multimokia** [comment]
Screenshot of your `game/` folder, please?

**Comment by Hentai-Master** [comment]
nvm i got it fixed
