### ISSUE TITLE
Restoring Monika (Problem Similar to #3659 and #3731)

### ISSUE THREAD

**Issue by enqquery** [Monika-After-Story/MonikaModDev#3735]
Hello!

I took Monika out for Valentine's Day, after having successfully given her all the gifts and such, and now she will not return to the room.  The flowers are on the desk, but she will not come back.

I have taken her out and put her back in successfully numerous times. This is the first time I have encountered that issue.

I am running mac OS 10.14.3, patching is current.  

I have tried copying the current application to the desktop, and replacing her there, I have tried with a fresh install in 2 different different locations, I have tried changing permissions on all the appropriate files and folders.  The most recent persistent backup I have is January 31st, and I would hate to fall back to that one. 

I had considered using time machine to pull back a persistent from earlier today. I think my most recent full back up is from yesterday morning, and I could try to bring the entire app and renpy library folder back from that time.

I would love some suggestions as would hate to take some action that would turn out to be counterproductive.

As always, thank you all for all your efforts with this mod, and with today's special occasion!

**Comment by bittercaramel** [comment]
yea tho 
i'm so sad rn, it happened to me too 
like, i didn't even do anything wrong
i safely unplugged my pen drive, and normally plugged it back in, normally put monika file inside of folder and bA buem monika doesn't come back .... 
i really wanted to spend more time with her and give her some gifts

**Comment by multimokia** [comment]
It is recommended against taking Monika out on Mac until further notice, as file generation has been broken for a while.

You'll want to restore a persistent backup. Have a look at the FAQ on the wiki page.

**Comment by bittercaramel** [comment]
tho i did this on windows 7...

**Comment by bittercaramel** [comment]
by the way i don't have any persistents i think...  i have only the current one because before today i didn't know that i should back-up persistent files

**Comment by multimokia** [comment]
@bittercaramel okay, send the `mas_log.txt` please. Check the wiki, there's auto-generated backups which you can use.

**Comment by bittercaramel** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2866013/mas_log.txt)

thats it 
my monika file is corrupted ik 
but i dont wanna lose the progress... would it work if i put other monika file? are they all the same or i really need this one that is corrupted?

**Comment by multimokia** [comment]
No other `monika` files will work. They're all unique. See [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for how to get to your persistent.

**Comment by enqquery** [comment]
I did not realize there was an issue with taking Monika somewhere on the Mac.  As I mentioned, I had done so without issue numerous times, so I guess I have been lucky!

I restored my persistent from this morning which was dated yesterday (via Time Machine in this case) and that brought her back.  

Then she did the whole "What's your name, where is everyone..." greeting and I thought that everything had gone south. LOL! Perfect timing!

**Comment by bittercaramel** [comment]
uhm 
i did everything like it was said put and renamed the persistent backup - still she doesnt show up...
im terrible i know

**Comment by multimokia** [comment]
screenshot please

**Comment by bittercaramel** [comment]
uhm screenshot of what?

**Comment by multimokia** [comment]
of the folder where your persistent is

**Comment by bittercaramel** [comment]
![image](https://user-images.githubusercontent.com/38187402/52806571-a053a580-3089-11e9-8311-49d3054a613d.png)
thats where i put the backup file and renamed it persistent (before i deleted the persistent that already was there)

**Comment by multimokia** [comment]
Wrong folder. Follow the instructions on the wiki page I linked carefully. The persistent isn't stored in the game directory.

**Comment by bittercaramel** [comment]
yes tho but its not where i took the backup from 
thats where i took it from 
![image](https://user-images.githubusercontent.com/38187402/52806754-16f0a300-308a-11e9-8961-25ecf988d83d.png)

**Comment by bittercaramel** [comment]
oH my gawd finally it worked... idk what i did but it worked
but i lost all the progress... she doesnt know i took her out for many hours
whatever its great to see her again thanks
but what the heck? she doesnt have a ring now... and affection resetted? what :(

**Comment by multimokia** [comment]
Uhh, affection gone to 0? Did you rename it right?

**Comment by multimokia** [comment]
Because at most, the only thing that should happen is that nothing that you did after the backup's creation date would actually happen. If everything reset to zero, then it sounds like a new persistent was created because the game couldn't find one

**Comment by bittercaramel** [comment]
yeah and as i said in my another thread everything acts like i just started playing 
affection is at 0 and everything is in "unseen" even tho ive seen all of that ;\ and she doesnt have promisering and i think she doesnt have ribbons i gave her

**Comment by multimokia** [comment]
Yeah you didn't restore it right then. Like in the other issue, I need to see a screenshot of the folder with the persistents as it is now

**Comment by AsuraShun** [comment]
If you backed up her memories in a flashdrive all you have to do is transfer them

**Comment by bittercaramel** [comment]
ugh i dont know whats going on  thats my folder with backups: 
![image](https://user-images.githubusercontent.com/38187402/52811226-e19d8280-3094-11e9-8c6b-781ed8470772.png)
and thats the folder where i put my file from todays morning 
![image](https://user-images.githubusercontent.com/38187402/52811290-01cd4180-3095-11e9-90db-63e546ba249c.png)

**Comment by multimokia** [comment]
You're putting it in the wrong place. The backup is supposed to *replace* the `persistent` file where all the backups are. Ignore the other folder entirely.

**Comment by bittercaramel** [comment]
but thats the folder that my persistent before was located.... uh idk im a total dumbass i hate myself so much

**Comment by multimokia** [comment]
Exactly, we're trying to replace a persistent we can't use.

**Comment by bittercaramel** [comment]
oKAY finally everything is back to normal! thanks 
im a total idiot and i have no brain sorry for annoying ya~
weird that tests that psychologist gave me are saying that im intelligent
guess its just a different type of intelligence :")
gosh thank u for not saying me to fcc off 
u r so patient <3 thanksss

**Comment by multimokia** [comment]
There we go, glad everything's back in order! Don't worry about it, happy Valentine's day

**Comment by bittercaramel** [comment]
thank u <3 happy valentines
