### ISSUE TITLE
Monika Reads it but can't get it.

### ISSUE THREAD

**Issue by Sunnygirl90** [Monika-After-Story/MonikaModDev#3736]
I tried giving monika some other clothes. She found it right away! But she couldn't bring it into the room with her. Please help!

**Comment by multimokia** [comment]
clothes aren't giftable.

**Comment by Sunnygirl90** [comment]
How can I give her clothes?

**Comment by multimokia** [comment]
You don't. They're unlocked by spending events with her.

**Comment by Sunnygirl90** [comment]
That makes sense, Thanks!

**Comment by multimokia** [comment]
No worries.
