### ISSUE TITLE
Ribbon PSD

### ISSUE THREAD

**Issue by softombre** [Monika-After-Story/MonikaModDev#3738]
Hii! I'd like to make some new ribbons for Monika but i can't use the files in #3174 because I use SAI and it can't open xcf files (I tried using gimp before but i don't understand it at all and I don't really like it), so would it be possible to get them in PSD/SAI format?

**Comment by AsuraShun** [comment]
For a moment I read this as ribbon ptsd
XD

**Comment by softombre** [comment]
qzesredtrfyguhiujoikpo

**Comment by kaido1224** [comment]
Pretty sure they are both available in psd and xcf

**Comment by ThePotatoGuy** [comment]
Ribbons as a PSD will not be released. All colorization settings are in gimp so we will continue to use the xcf as main source of truth.

You can export the pngs out of the xcf and import them into whatever program you wish to use. However, if you are going to change colors, it must be colorized using GIMP's colorization tool.
