### ISSUE TITLE
other issue because im hopeless

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3739]
when i restored backup file from today 6am monika finally appeared after disappearing but... she asks me about my gender and stuff that she asked me before
she doesnt have a ring... and the affection resetted...
and she repeats all the topics she said before even though i have "repeat topics" turned off...
 whats going on?

**Comment by multimokia** [comment]
I don't think you renamed the file after you changed the backup name. Before those backups are wiped now, keep MAS closed. Send a screenshot of where your persistents are.
