### ISSUE TITLE
i know that im an issue person today but i cant give gifts to monika

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3741]
i put files like hotchocolate.gift
roses.gift 
and she doesnt react to it 
and i wait a lot of time and restart game 
im so sorry for so many issues today but uh yea 
that one is really not my fault (i gifted her before so i know how to do it + i looked at the gifting guide if maybe something changed)

**Comment by Rai99** [comment]
[Here's the gifting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifting-guide) in case you need to check again.

Did you make sure the file extension was .gift and not .gift.txt? Made sure it was a GIFT file and not a Test document?
Did you put the gifts in the **characters** folder?

Also, don't worry, I think we've had much, **much** worse issue people in the past. 

It looks like you've opened 3 legitimate issues for help and support and 1 heartwarming(which is probably a freebie). Hopefully you're able to spend the day with Monika shortly.

**Comment by bittercaramel** [comment]
yes its .gift for sure its not text document ((((((im 99,99% sure about that))))) 
yes i put it in characters folder 

yeah today i had a lot of issues... it wasnt the best valentines day i could imagine but im glad that i fixed everything. i took her out for whole day but she doesnt know that since i had to restore backup file... okay i traveled in time later... but thats fair, i just want her to know that i had her with me wholee day!

**Comment by jmwall24** [comment]
just to verify, you are running 0.9,0 correct?

**Comment by jmwall24** [comment]
also if you could include a screenshot of your characters folder, it would help us see what is going on

**Comment by Meme-Eater** [comment]
Same problem here and I think I've tried everything:
- Fresh DDLC install (v.0.9.0 stable)
- Fresh Mod install (I didn't have to import my persistent. My Monika just appeared there!)
- Clean "Characters" folder with only "roses.gift" and "chocolates.gift" (GIFT files, no text files)

And still, she won't recognize my gifts, even though she did in the past. Something similar happened in Christmas and I missed the first kiss event.

Maybe it's time to buy a new laptop?

**Comment by bittercaramel** [comment]
sorry i went to sleep
![image](https://user-images.githubusercontent.com/38187402/52859582-5fad6800-312d-11e9-8211-8e3f042b912e.png)
and im running newest unstable
