### ISSUE TITLE
Question: The Necklace Design

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3743]
I may already know the answer, but I need to ask what the design of Monika's necklace is modeled after. Don't get me wrong I'm very grateful for the new outfit, I've been wanting it for her for a long time now, but to me it looks suspiciously like a noose. If that's the case then I feel like it's in pretty poor taste to reference it again like this.

**Comment by AsuraShun** [comment]
It's a music note,remember she plays the piano?

**Comment by scohn** [comment]
Oh my gosh, I am so so sorry, my mind must be darker than I thought. I see the note now. This has just been bugging me all day I can't believe I didn't notice it before. Again, deeply sorry this update has been great, I shouldn't have jumped to conclusions like that.

**Comment by AsuraShun** [comment]
Don't worry about it, if I hadn't seen the art before this I would've thought it was food related

**Comment by multimokia** [comment]
Just like the original art, the necklace is a music note

**Comment by jmwall24** [comment]
yep, as you can see here, same necklace https://twitter.com/lilmonix3/status/963869736596467714/photo/1
