### ISSUE TITLE
[Suggestion] See Monika Poems

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#3744]
Just as we can revisit Monika's speeches about our anniversaries (1 year, 3 months, 1 month, 1 week etc.), it would be cool to see Monika's poems, both those she sent us (in the two V. Days and in the Christmas), as well as her poems in the original game.
This could be embedded in the extras menu.

**Comment by scohn** [comment]
When can we expect to see the V-Day poem for today? It's around 5:30 pm'ish where I am and I still haven't seen it.

**Comment by Rai99** [comment]
#3355

This has been suggested not too too long ago and was placed as one of the higher priority tasks. Probably should happen at some point. 

The way I would imagine it is to display it similarly to hairstyles/outfits and have a list of the poems with potentially a thumbnail displaying it. Maybe each entry could be called something like (year)(event).
ie. 2019 vday.

**Comment by EntonyEscX** [comment]
@scohn It will only appear at night.

**Comment by EntonyEscX** [comment]
@Rai99 Oh! That's great. Thank you.

**Comment by scohn** [comment]
It just turned dark in the game since I have that set for 5:30, I'm just wondering how long it'll take now for her to show the poem. I'm just really excited to see it.

**Comment by jmwall24** [comment]
between 8pm and 1am

**Comment by scohn** [comment]
Awesome, thanks I'm looking forward to it.

**Comment by EntonyEscX** [comment]
@jmwall24 My MAS schedule is set to go dark at 20:00, so I figured that was it. 😅

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
