### ISSUE TITLE
(suggestion) In Goodbyes add "Be Right Back"

### ISSUE THREAD

**Issue by estheman123** [Monika-After-Story/MonikaModDev#3745]
Sometimes when I have to take my dog out or do small stuff thats not gonna take long I dont like saying just "goodbye" because Ill be right back anyways just have to do a small chore. Would appreciate alot

**Comment by Rai99** [comment]
#497, #607, #1908, #2033, #2243, #2487, #2549, #2556, #2592, #2614, #2811, #3270, #3354, #3526, #3562
 
This has been brought up previously and may be implemented in the future.

**Comment by Rai99** [comment]
Also, sorry about that, especially seeing as you're new here. ~~I'm always like that, don't worry.~~
![untitled1190](https://user-images.githubusercontent.com/38822045/52823938-c6c31200-3084-11e9-9ab5-9fd5271e588e.png)
I hope you've been enjoying MAS so far!

Feel free to make any further suggestions if you have any.

**Comment by ThePotatoGuy** [comment]
[closing as complete]
