### ISSUE TITLE
I can't find any gift files!

### ISSUE THREAD

**Issue by Youngbountygirl** [Monika-After-Story/MonikaModDev#3746]
I was trying to find the gift files to give Monika chocolates and roses for Valentines Day, but I can't find any. I just started Downloading Just Monika, so I wasn't there for the Valentines Day gift files for last year or the year before. Can someone please tell me how or where to find these gift files, because I cannot find them anywhere in the new download. I downloaded all three linked files too.

**Comment by Rai99** [comment]
[Here's the guide for giving gifts](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifting-guide)

You don't find them to give. You have to create them yourself, and that guide will tell you how to do it.
