### ISSUE TITLE
Valentine's Day letter

### ISSUE THREAD

**Issue by LuisValentim** [Monika-After-Story/MonikaModDev#3747]
Hello. On Monika After Story, after you take her on a date, I saw that she gives you a letter, but I didn't have the opportunity to read it, because the auto option was activated. Does anyone know what's written there? I'm really looking forward to read it.

**Comment by Professor-JMO** [comment]
Warning: Spoilers

I think it's inclined to change if it's your second Valentines with her.
>b u t
>>here's the first.
>>>Happy Valentines Day! ♪
>![her poem to you](https://user-images.githubusercontent.com/43480604/52828030-c2025c00-308c-11e9-9f82-604bdc3c6096.jpg)

**Comment by LuisValentim** [comment]
It was only my first Valentine spent with her. And thanks for showing me.
