### ISSUE TITLE
Christmas decorations not going away

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#3748]
Pretty self explanatory, and I couldn't find anything else about this. It's Valentine's Day and my Christmas Decorations are still up. I heard they were only meant to last a few days into the New Year. They don't bother me, I just think it's a bit weird to have roses and chocolates on the table with a Christmas tree in the background. Did I do something wrong?

**Comment by DeadManStanding** [comment]
I have the same problem, christmas decorations are still hanging. Can we have an option to choose decorations for background? Similar to Monika's clothing?

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
