### ISSUE TITLE
[Suggestions] Monika reacting to the player's age?

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#3750]
With the new topic about the player's birthdate, I played around with some of the things. Monika reacted the same way to being really old, really young, and an average age. Maybe I did something wrong and it's already in the game, but maybe Monika could react to the player's age?

**Comment by Rai99** [comment]
#1026, #2292, #3513 

Monika reacts a little if you tell her that you're under 13 and I don't think she accepts it if you tell her you're under 5. 

As for reacting to older ages, I don't think there's anything currently.  

Even if there was a feature like this, I'm not sure if there'll be too many opportunities to really use it for the older ages.

**Comment by Rai99** [comment]
~~Whoops, don't fire me~~

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
