### ISSUE TITLE
Monika not going back to spaceroom

### ISSUE THREAD

**Issue by AgentZephyr** [Monika-After-Story/MonikaModDev#3753]
I'm on unstable if that helps.  Took Monika out earlier and she's isn't showing up even though she is in the characters folder.  Thanks for the awesome V day stuff Devs! Looking forward to whats next!

**Comment by jmwall24** [comment]
Are you on mac?

**Comment by AgentZephyr** [comment]
Yes I am

**Comment by Private-Project-001** [comment]
This problem exists for me as well however I am on windows.

**Comment by ThePotatoGuy** [comment]
We've recently pinpointed the root cause on macs and will address it next release. 

If you're on windows and your default PC encoding is in latin-1, then that might be a reason why it doesn't work for you, but I would need to see your `mas_log.txt` to make sure.

**Comment by ThePotatoGuy** [comment]
For now, just restore an earlier persistent/

**Comment by ThePotatoGuy** [comment]
linking to #3868
