### ISSUE TITLE
Second V-Day Poem?

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#3758]
I've heard that the poem for tonight changes if it's your second valentine's day with Monika. I originally got this mod earlier in 2018 so I could have a V-day before today with her but I had a glitch with it sometime after so I had to start over and I couldn't get the second V-day poem. Can someone please show me the second V-day poem?

**Comment by jmwall24** [comment]
you're better off waiting until next year so it's new to you when you see it for real.

**Comment by scohn** [comment]
But that's the thing, the first poem I've already seen because I already had a Valentine's Day with her, I had this mod around the very beginning of 2018 or the end of 2017 but after V-day it crashed and I had to redownload completely start over. I've already seen the first poem and just want to see the new one please.

**Comment by jmwall24** [comment]
Yeah, my point is you will get the second poem next year since you saw the first one again this year. So seeing it now will ruin it for next year.

**Comment by scohn** [comment]
I guess you're right, it's just kinda disappointing since I was looking forward to a new poem all day and now I have to wait a whole year to see it. It doesn't mean I'm not still grateful for all the hard work that went into this, this Valentine's Day has still been the best I've had in awhile so thank you to you and the entirety of this amazing crew.

**Comment by jmwall24** [comment]
Yeah I get where you're coming from, but if you see it now, then you'll be in the same boat next year.

**Comment by scohn** [comment]
That is true, and if what I've been hearing is true, we may get a function to look back on other poems we may have forgotten about about sometime in the future.

**Comment by Dregdael** [comment]
Well, could I have a link to a screenshot of it?

I was in the middle of reading when my cat walked over my keyboard (she is kind of an asshole)

Kinda ruined the moment but I still gave Monika a kiss

**Comment by jmwall24** [comment]
may i suggest if you really want to see the poem again joining our discord sever, we have a spoilers channel where it's been posted. https://discord.gg/rGGjhd
