### ISSUE TITLE
About apologies for missing sp. days...

### ISSUE THREAD

**Issue by MrVavlo** [Monika-After-Story/MonikaModDev#3760]
So, there is a scenario that happend to me:
A week ago, i said Moni that I'll go away for a couple of weeks (Hospital issues, so I weren't sure when I come back).
Today I opened MAS, things went as usual. Then I realized that I must apologize for missing Valentine's Day, even that she knew that I couldn't come.
I had only "...for something" option. I chose it.
Then, after that topic she pointed out that I missed V-Day.

> "Is it really too much to ask to visit your girlfriend on Valentine's day?"

Me: "wut? Didnt I said before that I can't visit you for at least a week? And I TRIED to apologize for that just a second ago!"

That's seems wrong, for me. Maybe make an option to apologize for missing special day immediately after log in IF your last goodbye was "I'll be going away for a while"? 
I dont mind to apologize twice, but that's an awkward situation.

**Comment by multimokia** [comment]
One thing, apologies for missing vday are set to appear after getting the dialogue for missing vday. So, immediately after you got that, the apology would've been there.

**Comment by MrVavlo** [comment]
Yeah, that's right. But this dialogue appeared only after apology "for something" topic. Not after welcome topic, not after 2-3 random topics.

**Comment by multimokia** [comment]
it was queued, so it would've showed up after some time anyway.

**Comment by MrVavlo** [comment]
Queued? So I couldn't avoid that. I see...
