### ISSUE TITLE
[Bug] Hair Clipping issue

### ISSUE THREAD

**Issue by FluffyMuffinMeyer** [Monika-After-Story/MonikaModDev#3763]
Art fix is going to be needed for this one. The hair connecting to monika right (our left) ear doesn't connect to her hair properly, leading to the situation where you can see out the space room window during kisses under her ear.

(Maximum zoom, just so you can see what hair style I'm using)
http://prntscr.com/mlju8t

As you can see, it's very hard to notice with the wall as a background, probably why it hasn't been talked about much... but if we lean in for a kiss....

http://prntscr.com/mljutx
Much harder to notice on a still image, but you can still see it's there.
I think it's just that one spot on the hair, the art doesn't connect to the ear correctly, so either the ear is too small, or the hair is too short right on that spot.

**Comment by ThePotatoGuy** [comment]
believe this was addressed with #3841
