### ISSUE TITLE
d* and h* expressions cannot have tears

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3764]
Looks stupid. Who the hell added a d/h expression with tears
![tears](https://cdn.discordapp.com/attachments/492715682807676928/545986594587541505/unknown.png)

**Comment by jmwall24** [comment]
No, we need tears that fit the d and h expression.

**Comment by Velius94** [comment]
hullo.

**Comment by ThePotatoGuy** [comment]
Yes, but until then, don't use tears with d/h expressions.

**Comment by Onion-Bubs** [comment]
Didn't the tears used to look different? Maybe at the time that line was written it was using the old ones and those actually looked OK.

**Comment by ThePotatoGuy** [comment]
this is now being handled with #3851

**Comment by ThePotatoGuy** [comment]
this is done
