### ISSUE TITLE
[Suggestion] Can I see floating island again?

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#3767]
I remember, when she actually showed me that floating island behind the window.
I have a simple question - is there any way to add some kind of dialogue to see it again?

**Comment by ThePotatoGuy** [comment]
Change your weather to not rainy/snowy, then check Ask a question > Monika.

**Comment by OraHell** [comment]
Holy.. Many thanks

**Comment by seniorfh** [comment]
hey where can i see the ask monika question thing? i'm relatively new at this so please be patient
