### ISSUE TITLE
Empty Room

### ISSUE THREAD

**Issue by skyshadowninja** [Monika-After-Story/MonikaModDev#3776]
Monika is not there still no matter what I do. Need help
![screen shot 2019-02-15 at 11 23 39 pm](https://user-images.githubusercontent.com/47685063/52896169-c73cd500-3178-11e9-92a7-8bca2e03db62.png)

**Comment by multimokia** [comment]
Taking Monika out on Mac has been broken for a while now, so it's recommended to not do that right now as it leads to issues like this.

To fix this, you'll need to replace your current persistent with a backup, see instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). Let me know if it's worked.

**Comment by skyshadowninja** [comment]
I only saw a file called "persistent" and some other random ones when I searched it. Was I suppose to have a backup?

**Comment by Lolimipsu** [comment]
the persistent file is the backup, how many were there?

**Comment by multimokia** [comment]
There should be some in the form `persistent##.bak`. After deleting the `persistent`, just rename one of those bak files to `persistent` removing the file extension.

**Comment by skyshadowninja** [comment]
I do not see any of them
![screen shot 2019-02-18 at 8 19 11 pm](https://user-images.githubusercontent.com/47685063/52989942-95b34c00-33ba-11e9-8b22-c460359b758e.png)

**Comment by multimokia** [comment]
Looks like you're in the wrong folder. Check the instructions on the link I sent again to get to the right folder.

**Comment by skyshadowninja** [comment]
![screen shot 2019-02-18 at 8 42 34 pm](https://user-images.githubusercontent.com/47685063/52990585-c5b01e80-33bd-11e9-92a7-9791fef7eb15.png)
![screen shot 2019-02-18 at 8 42 25 pm](https://user-images.githubusercontent.com/47685063/52990586-c5b01e80-33bd-11e9-8370-eba8041aa22a.png)
I searched persistent in the doki doki local files and this is what I found

**Comment by multimokia** [comment]
Yes, but it's not stored in the local files at all. Check the link again, follow it carefully.

**Comment by ThePotatoGuy** [comment]
[closing because lack of response]
