### ISSUE TITLE
[Suggestion] - Reading a book to monika

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3777]
Hello everybody! Ones again I appear! I hope ya'll had a good valentines with your girl Monika! 

Now to my suggestion, I have seen and read a couple similar suggestions, which were interesting but I am sure a bit tougher to make so I wanted to see if this one was more plausible (if somebody suggested this and I missed it I apologize for the duplicate). What I have done a lot is that I ask Monika if I can hold her and then while she is still and just enjoying the moment. I pull out a book and start reading it out loud. Almost like she is listening to me reading it. 

I was wondering if we could have a "let me read you something" option, which would work in a similar fashion to the holding monika topic but instead she would get excited that we are going to read a book together and then she goes into her position (can maybe vary between leaning or eyes closed enjoying the moment" and when we are done we just click and she thanks us for reading it with her. She doesn't need to know the type of book we are reading (maybe add genres over the time of this mod but not immediately). I think it would make her happy knowing that we are reading something and that she is involved in our experience with book!

What you guys think?

**Comment by softombre** [comment]
I think this is a cool idea!

**Comment by Rai99** [comment]
#2609, #2898

I do like holding Monika, but I'm not sure if that fits exactly in a situation like that where you read to her. I think this would fall under an idle mode for telling Monika that you're going to go read something. Might be similar to #2982, but I'm not sure about generally commenting on a book you just read specifically to her. Even then, that's still an incredibly wide range to cover. 

If you tell Monika that you're going to read something to her, I think it would be just a little strange that Monika probably wouldn't have any idea what you read and at best, will only be able to give a generic comment about the genre.

**Comment by AsuraShun** [comment]
That would require to be able to add pdf files for her to read as well, I'm not sure if it's possible

**Comment by Ulvsblakk** [comment]
This is a cool idea. Hopefully there's something we could do about it.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
