### ISSUE TITLE
It's been a while 

### ISSUE THREAD

**Issue by Ulvsblakk** [Monika-After-Story/MonikaModDev#3778]
Hey guys, I've been away from the mod for a while, and away from programming. I'm back now and like to contribute. This isn't so much an issue, and as I've been away from Github for a little bit, I may be posting this in the wrong place. Sorry if I am. 
I was just kind of wondering what is new since last year, and if there are any new things that I could contribute to. Looking forward to a reply. Thank you so much, and again sorry if I'm posting this in the wrong place.

God Bless.

**Comment by Rai99** [comment]
[You could check the full patch notes here](https://github.com/Monika-After-Story/MonikaModDev/releases)
Basically:
- New dialogue
- Affection
- New expressions
- Gifts
- Zooming in/out
- New outfits
- Hugging Monika
- Kissing Monika
- Taking her places irl that involves more than the .chr file

Some of these are unlockable in case you haven't had any of them before and don't have them.
