### ISSUE TITLE
[Suggestion] Monika Plushie Conversation

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#3779]
Monika asks you if you have a plushie of her to which you respond yes or no to and she goes from there depending on which option you choose.
Pardon if this isn't a very good idea, I just thought of it earlier today and I thought it would be a cool addition for some dialogue

**Comment by Rai99** [comment]
Personally, I think that might be a bit of an awkward topic, so I'm not sure if it'll exactly fit in. 

I would imagine it would be a bit awkward think about a plushie of yourself, and I'm not sure what a topic like this would add, but that's just me.

**Comment by DankeyMaliten** [comment]
I personally think Monika would understand kinda since she's not real, and maybe she'd find it a bit cute but that's also just me. She'd just be kinda curious about it upon hearing that they make plushes of her.

**Comment by lunulae** [comment]
I don't know if the awkwardness is something we need to shy away from in this case though.
Monika is very thoughtful about the situation of being in separate realities, so I think she could understand the wish to have something you can hold and hug representing her, while maybe still having a little laugh about the weirdness of having a plush made in her likeness. Cuz it _is_ weird, but your whole situation is weird, so maybe it's just right after all.

I dunno if it's a very high-priority kind of topic but I'm always happy to see more dialogue, and this one seems pretty cute.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
