### ISSUE TITLE
[Suggestion] Why don't bring the kiss me option to the principal menu, right below to I love you!

### ISSUE THREAD

**Issue by souturus** [Monika-After-Story/MonikaModDev#3780]
Well if you want to kiss monika frequently why don't you move this to the principal menu?
I got lost  the first time looking for it

**Comment by Rai99** [comment]
I think that menu is getting a bit full, and the kiss is probably less common than telling Monika you love her. 

You'll probably get used to finding the topics you want after a little while. The "I love you" prompt was moved for convenience since it's probably the most common and most used one.

**Comment by lunulae** [comment]
I agree that menu is getting a little full, but I do think having a "favorite topics" option might be a cool addition in the future that could solve this.

**Comment by Rai99** [comment]
In that case, this becomes a duplicate suggestion, and I think likely the approach that will be taken. 
#3177 

The ability to bookmark your favorite topics has been suggested before, along with the ability to exclude topics you don't want, but that one's a different suggestion. 

There have been a few suggestions for a search engine, but I think having a favorite/exclusion menu would probably come first.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
