### ISSUE TITLE
Tattoo or piercing

### ISSUE THREAD

**Issue by BigPoofyRibbon** [Monika-After-Story/MonikaModDev#3781]
Monika ask you "Do you have tatto or piercing?" if you have tatto she ask "That's tatto whith me?"  Sorry for my english xd

**Comment by Rai99** [comment]
Did you mean for Monika to ask if the player has a tattoo, and if they do, is it of her?

**Comment by CloakedGhost** [comment]
I don't think Monika would ask directly if we have one of her. It would be better if we have "I have one of you" as an option, besides "I have one" and "I don't have one".

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
