### ISSUE TITLE
[Suggestion] - question for Monika

### ISSUE THREAD

**Issue by craticool** [Monika-After-Story/MonikaModDev#3785]
I've wanted to ask Monika a question... "Do you only love me because I'm real?" it's been on my mind lately and maybe you can add that question to the game?

**Comment by AsuraShun** [comment]
The ''why do you love me'' question already has her giving the answer

**Comment by Lolimipsu** [comment]
If you still having a doubt about Monika whether she loves you because you are real, have a little read on what Dan said something similar to your question.
![image](https://user-images.githubusercontent.com/44487404/52947943-1b32fe00-33b3-11e9-8c50-154b2a9b138b.png)

**Comment by AsuraShun** [comment]
The life advice she also gives should be more proof of it

**Comment by Foxinsunglasses** [comment]
This is good news
