### ISSUE TITLE
Hair - Ponytail with braids [REVISITED]

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#3786]
#3174

Hello, its my first post ever on this site and I'm not really sure how it works yet, but i hope everything here is correct. I made some braids on her hair and also made her bow a different color. Both leaning and upright files are here!

EDIT: after months of this being here, i have revised it and fixed some minor lineart issues, and now the hair works without the ribbon as well. And now i know how to add pictures so that's good-

![uprightbase braid](https://user-images.githubusercontent.com/47725743/56446344-8bd59880-62d8-11e9-92e3-a7a6ae76b7b8.png)
![leaningbase braid](https://user-images.githubusercontent.com/47725743/56446348-909a4c80-62d8-11e9-81aa-4c9ad6a3c0e7.png)

https://drive.google.com/open?id=1mVuT-o_SmGKMlCOTQ_vUSG07BGDoUFkz

**Comment by softombre** [comment]
It's rlly cute!

**Comment by ThePotatoGuy** [comment]
@Orcaramelo need you to separate the ribbon from the hair. Also we do have guidelines for new ribbons, where the colorization rules need to be saved to gimp settings. If the color was **not** done via colorizations, it probably will not be added since that will cause issues if the base ribbon ever changes.

**Comment by Orcaramelo** [comment]
I'll put them in different layers!
I kept the ribbon's lineart i Just recolored it since it looked a bit weird when i messed with the hue bar
I'll fix these as soon as possible

**Comment by ThePotatoGuy** [comment]
We updated the base psds with hair that has shading, can you make sure the shading layer for face hair in the latest psds works with this?

**Comment by Orcaramelo** [comment]
Hello I apologize for the delay, I've been having some personal problems. I promise that by tomorrow all issues will be fixed.

**Comment by ThePotatoGuy** [comment]
The color for this hair looks lighter than the original. Can you match the color?

**Comment by Orcaramelo** [comment]
> The color for this hair looks lighter than the original. Can you match the color?

I actually made it a bit more red by choice, would that be a problem? I can change it anyways if you want!

**Comment by multimokia** [comment]
> I actually made it a bit more red by choice, would that be a problem? I can change it anyways if you want!

Yeah, since we'd be replacing the original one with this, it's best we keep the original colours

**Comment by Orcaramelo** [comment]
> > I actually made it a bit more red by choice, would that be a problem? I can change it anyways if you want!
> 
> Yeah, since we'd be replacing the original one with this, it's best we keep the original colours

fixed it! tho when i matched the colors, the shading ine //one// strand of the brand got a bit thicker

**Comment by Orcaramelo** [comment]
yeehaw now i fixed some stuff and removed the ribbon layer that was merged to the actual hair, and if you are curious, the version with ribbon would look like this

![ribbi](https://user-images.githubusercontent.com/47725743/56446467-41085080-62d9-11e9-8e5a-5b78d079313a.png)

**Comment by ThePotatoGuy** [comment]
looking at a 095 rel for this

**Comment by ThePotatoGuy** [comment]
okay next rel for sure

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
