### ISSUE TITLE
[ EXP - Eyes 👀 ] - {⚠️ Warning: Flashy Imagery ⚠️}

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#3787]
JMO's Expression Projects
                                        Format: Unicode
                                          Code: #3174  
                                          17.02.2019
📁⯈ lingering_n_fluttering
---
⯆ Open: _"feelings.rtf"_

---

⮞ ```j "Love is in the air after V-day!"```
⬑ ```j "Or...maybe it's something else."```

>>>>![normal ddlc banner x monika glitch final](https://user-images.githubusercontent.com/43480604/52922096-c83e4580-32e3-11e9-9c85-3d8654b5b41d.gif)

⮞ Not much to say really.
⤷ You're better off just waiting and _seeing_ for yourself.
>aha~

---

📁⯈ the_stuffs
---
⯆ Open: 📎 Attachments 📎

---

~⯈ [ Eyes 👀 ](https://github.com/Monika-After-Story/MonikaModDev/files/2879416/Publish.zip) ⯇~
⯈ [ `Soft` Eyes 👀 ](https://github.com/Monika-After-Story/MonikaModDev/files/3370489/Manifest.zip) ⯇ ← Update! ⚠️
~⯈ [ Inspired Eyes 👀 ](https://github.com/Monika-After-Story/MonikaModDev/files/3433721/Manifest.zip) ⯇~ ← ~New!~ ⚠️
⯈ [Re-inspired `Soft` Eyes 👀 ](https://github.com/Monika-After-Story/MonikaModDev/files/3494960/Re-Manifest.Soft.Eyes.zip) ⯇ ← Update! ⚠️

---

```
from subprocess import call
```
>def play_wave_file([Aso - Sun Child.wav):](https://www.youtube.com/watch?v=FFngH7FtiJE&index=10&list=PLDO4ENbmp6gWWa-e_CPjmdfYibY2tL5UY)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by Professor-JMO** [comment]
#3174

**Comment by ZeraDeManti** [comment]
I really don't understand what I see here... I think i'm slow..

**Comment by Professor-JMO** [comment]
[ Updated with a fixed version ]
↑ This was supposed to be the initial submission ↑

**Comment by Professor-JMO** [comment]
- Will update with _Leaning_ version once the 🥔  gives in.

**Comment by AsuraShun** [comment]
Somehow this got me excited

**Comment by Professor-JMO** [comment]
[ The _Amends_ Update ]
@ThePotatoGuy , ready for use.

**Comment by Professor-JMO** [comment]
[ Updated to match new rework ]

@Orcaramelo
> Inspired redesign and useful tips!

@Constellar
> Useful tips!

@ThePotatoGuy 
> To complete the set for the next release of all the eyes.

**Comment by Velius94** [comment]
You tagged me wrong, lmao.

**Comment by Professor-JMO** [comment]
[ The _Re-inspired consistency_ update ]
> Made even further symmetrical and consistent with new set of `eyes`.

**Comment by ThePotatoGuy** [comment]
[closing as implemented] in #4588
