### ISSUE TITLE
Hair - Art style matching ((updated²))

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#3788]
#3174
Hello again! I am back and this time it's more of a correction other than a new hair, i noticed that on Monika's sprites where her hair is down, the style doesn't match very nicely, so in these edits i have tried my best to recreate the original hair coloring style, but her hair is down now
The shading style is not perfect tho

edit: white spots and transparency issues fixed! having a neon color on the bg helps a lot finding mistakes
edit edit: unshaded strand removed and I modified the shade layer for the long strands in the front(?), but the face's shading fits perfectly. also covered the part of the head that was sticking out with hair since it had been erased, I hope all works now.
edit² fixed the color difference from the original! and made the shading transparent.
https://drive.google.com/open?id=1TK9NbgCR7Mu6sZEA15SI9Nf9Z6NKvPGJ

**Comment by ThePotatoGuy** [comment]
first glance, this looks good. will do a full look over sometime this week

**Comment by its-ken** [comment]
these look so good! i hope they get implemented bc the art bugs have been bothering me :3

**Comment by Orcaramelo** [comment]
> these look so good! i hope they get implemented bc the art bugs have been bothering me :3

Thank you very much!! Also, it bothered me too, I tought it would be more pleasing to the eye to try and match the style! I did try to use only her original strands of hair, but ended up having to paint new ones too

**Comment by Velius94** [comment]
You might want to fix that twilight filter overlay on the hair sprites in the upright version.
Overall, it's a massive improvement.

**Comment by ThePotatoGuy** [comment]
Couple of things:

* I saw you deleted part of the base in your psd, that isn't gonna fly in release. All outfits use the same base, so the front hair should extend out enough to cover the entirety of base. You could just copy the back hair piece that goes over the base here and stick it to the front hair layer.
![basevisible](https://user-images.githubusercontent.com/3499462/52983413-ae1e6900-33b0-11e9-8195-37d50e9c65f2.png)

* there is what appears to be a line shift in 2 spots? It doesn't look that great, so this will need to be addressed.
![lineshift](https://user-images.githubusercontent.com/3499462/52983414-ae1e6900-33b0-11e9-88f4-e0eab7393268.png)
![lineshift2](https://user-images.githubusercontent.com/3499462/52983415-ae1e6900-33b0-11e9-8abf-58608662bf9e.png)

* also found some transparency holes that need to be dealt with. Most of these are only visible with twilight filter.
![transparencyholes_01](https://user-images.githubusercontent.com/3499462/52983416-aeb6ff80-33b0-11e9-9294-2e57457c7ec4.png)
![transparencyholes02](https://user-images.githubusercontent.com/3499462/52983417-aeb6ff80-33b0-11e9-8977-9f508dee6cb9.png)
![transparencyholes03](https://user-images.githubusercontent.com/3499462/52983418-aeb6ff80-33b0-11e9-91e8-8f5d6eeba9e4.png)
![transparencyholes04](https://user-images.githubusercontent.com/3499462/52983419-aeb6ff80-33b0-11e9-9032-e82a5e54f8a6.png)

**Comment by Orcaramelo** [comment]
I'll fix these as soon as possible today! Those are easy fixes I should have payed more attention!

**Comment by Orcaramelo** [comment]
Im sorry for the delay, I ended up getting busy yesterday, I'm going to edit this post with all the issues you pointed out fixed, and lineart a bit more polished!

**Comment by Velius94** [comment]
Upright variant still has the permanent twilight filter issue.

**Comment by Orcaramelo** [comment]
> Upright variant still has the permanent twilight filter issue. Disable the filter on your working psd and reupload it.

I use paint tool sai instead of photoshop and the filter doesn't work there, maybe that's what is causing this? I could try deleting the layer

**Comment by multimokia** [comment]
Looks like the leaning pose also suffers from the bit where her skull shows:
![image](https://user-images.githubusercontent.com/22531674/53280984-83554d00-36ef-11e9-8074-7b65be339fbf.png)

**Comment by jmwall24** [comment]
Love this hair.  My only complaint is this single strand here.  It's significantly lighter than the rest and it makes it look out of place and like it's not shaded at all.  Could use a little work to make it not stand out quite so much.

![screenshot_472](https://user-images.githubusercontent.com/36523761/53281405-f1047780-36f5-11e9-9289-f204dd72c289.png)

**Comment by multimokia** [comment]
Also, looks like the leaning version of this also has the issue of the head being clipped:
![image](https://user-images.githubusercontent.com/22531674/53287676-ae6e8980-374d-11e9-9e2f-12e1976fcbff.png)

**Comment by ThePotatoGuy** [comment]
we just added some shading layers to the latest base psds, can you check if they would work with this or if they would need adjustment?

**Comment by Orcaramelo** [comment]
Hello I apologize for the delay, I've been having some personal problems. I promise that by tomorrow all issues will be fixed.

**Comment by ThePotatoGuy** [comment]
So the color on these looks lighter than the original. Can you fix the color? Otherwise there's no way we can replace hairdown with these unless all other hair sprites match the color. (Am open to using as separate hairstyle, though).

**Comment by ThePotatoGuy** [comment]
*Additionally, the shading on the hair strands over the body should be a soft darkening, not a straight color. A flat color looks bad on outfits.

**Comment by Orcaramelo** [comment]
I fixed the color issue! I only had to match it on the upright base since when i pasted the original over the leaning one, they matched exactly. Maybe there was an extra layer when i originally made it and i didnt notice it, I just uploaded the new versions to my drive!

**Comment by Orcaramelo** [comment]
> *Additionally, the shading on the hair strands over the body should be a soft darkening, not a straight color. A flat color looks bad on outfits.

fixed that, they are now transparent.

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/54482912-11b97c00-4821-11e9-9d2d-1cfa04267290.png)
Looks like this bit has become transparent here too.

**Comment by Orcaramelo** [comment]
> ![image](https://user-images.githubusercontent.com/22531674/54482912-11b97c00-4821-11e9-9d2d-1cfa04267290.png)
> Looks like this bit has become transparent here too.

just fixed that!! I'm so sorry açaldklçasd when i was matching the colors i messed up the layer

**Comment by Orcaramelo** [comment]
![Capturar](https://user-images.githubusercontent.com/47725743/54569002-1d8b7680-49b8-11e9-855f-4ce03800a5b8.PNG)
just if anyone wants to check the progress so far without downloading the file, here is what it looks like!

**Comment by Velius94** [comment]
Now it's perfect.
Also, you might want to hit up #artistry on the discord server.

**Comment by Orcaramelo** [comment]
> Now it's perfect.
> Also, you might want to hit up #artistry on the discord server.

Thank you! If any more changes need to be made just lemme know! Also, where can I find the link? It would be sooo much easier to contact me from there so I should probably join

**Comment by Velius94** [comment]
You can find the link on the main website.

**Comment by Orcaramelo** [comment]
> https://discordapp.com/invite/K2KuJeX

thank you! I joined, just reading the rules rn

**Comment by ThePotatoGuy** [comment]
[closing as this this has added in the linked pr]
