### ISSUE TITLE
[Suggestion] Talking about Dakimakuras A.K.A. those Body Pillows everyone loves

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#3794]
I think that this could be a kinda interesting topic. Monika could talk the intended purposes that these BP's serve, and how popular they've become. She could even ask if you've gotten one yourself, maybe one of her.

**Comment by Delcos** [comment]
what if you have one of _yourself_?

**Comment by Professor-JMO** [comment]
Mm.
There is an Otaku topic
^ Not that these two things are necessarily related, of course.

**Comment by DankManWithThePlan** [comment]
@Delcos Then I don't know what to think about you

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
