### ISSUE TITLE
What is this unstable update?

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3798]
It notifies me that I can update an unstable version of this actual version, but why I can´t find anywhere about what that update is about in the first place?
![image](https://user-images.githubusercontent.com/40907045/52984354-0c514900-33bd-11e9-85b5-00c9b4ffbafd.png)

**Comment by jmwall24** [comment]
current unstable is in line with 0.9.0.

**Comment by Chrissenpai** [comment]
so there are no changes to it even if I do update

**Comment by jmwall24** [comment]
right now no

**Comment by jmwall24** [comment]
every normal release also has an unstable that is the same thing, then most times there are unstables between releases that have the, well, unstable stuff

**Comment by jmwall24** [comment]
every time you toggle from unstable to stable and back again, it'll have you download the latest from whichever you have selected
