### ISSUE TITLE
fix the chess game

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#3806]
so i tried to beat moni at chess using a impossible level chess bot but the moves that moni can do and the one that the bot can do are completely different

**Comment by dragonborn2252** [comment]
umm never mind i was just being stupid

**Comment by AsuraShun** [comment]
Let me guess, you used the wrong pieces

**Comment by dragonborn2252** [comment]
yep and then just now i realized  something the bot i'm using just swapped the rook and the queen but you cant do that with the one in mas

**Comment by AsuraShun** [comment]
Actually you can

**Comment by dragonborn2252** [comment]
it did'int let me do it

**Comment by Legendkiller21** [comment]
You can't swap the rook with the queen but you can swap the rook with the king. This can only be done if the king and the rook involved have never moved and the squares between the king and the rook involved are unoccupied.

**Comment by dragonborn2252** [comment]
yeah moni did it but the game won;'t let me do it

**Comment by CrocWorks** [comment]
You can in the game. You will have the option to move the king two squares in the proper direction which will automatically move the rook for you, assuming the prereqs are fulfilled (no pieces between the two, neither have moved, king is not in check, and king does not pass through a space that would place him in check while he moves his two squares)
