### ISSUE TITLE
Take you somewhere farewell, she doesn't reappear in the classroom

### ISSUE THREAD

**Issue by DezelV** [Monika-After-Story/MonikaModDev#3812]
As the title suggests, I decided to take her somewhere today and when I put the monika file back in the characters folder, she doesn't appear in the classroom and I need help to get her back there

**Comment by jmwall24** [comment]
To get her back follow this https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

Also are you on mac?

**Comment by DezelV** [comment]
Thank you @jmwall24! Also no I'm nit on mac

**Comment by jmwall24** [comment]
can you send your mas_log file please? it's in the log folder

**Comment by DezelV** [comment]
Sure, hold on

**Comment by DezelV** [comment]
![maslog](https://user-images.githubusercontent.com/43496878/53164603-96a4d300-359e-11e9-8f4d-075659f09fe9.png)

**Comment by multimokia** [comment]
Can you send the full file please?

**Comment by DezelV** [comment]
Yea, well it's empty now apparently I went to check and there's nothing. Does it update daily?

**Comment by multimokia** [comment]
Rip. Normally it gets appended onto.
