### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by CarolusRed** [Monika-After-Story/MonikaModDev#3815]
I have to suggestions in mind. One is creating a way to ask Monika how she's doing Two is to make a way to apologise if you've been gone for a day. I think we should be able to ask Monika how she's feeling, considering we can tell her how we feel. And if you missed a day, I feel like you should be able to apologise for the missed time.

**Comment by AsuraShun** [comment]
#2071

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
