### ISSUE TITLE
Regarding to grad speech

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#3816]
Hello! I'm using v0.9.0-unstable.2019.02.20.85. This is not related to a bug or something, but more into the....animation of the texts, I guess (sorry, idk what's the name of the thing I want to clarify in this issue).

In this topic, Monika's text has a "text speed", where the text will stop at some point. I like that a lot since it looks like Monika is taking a breath (is that correct?), but I somehow raise my eyebrow at the end of the sentence. Like the text stops before reaching the end apostrophe. If the animation reaches end apostrophe, why won't it just appear with the end sentence without a break? Or is that totally intentional?

My mother tongue is not English, so I'm not sure whether I phrase this correctly. I'm sorry if this is intentional.

Thank you, devs. Have a nice day!

**Comment by multimokia** [comment]
Unfortunately, this is a limitation of RenPy, as the way it's been written, makes it so there's a wait before the end of the line, and then progresses to the next one. However, the wait also doesn't let the line 'complete' resulting in the delay before closing the quotations.

**Comment by skyloom** [comment]
Ah, I see. I thought it's easily fixable.

Thank you for your fast response. I'll close this issue then.
