### ISSUE TITLE
Visual bug at the table when monika gets more coffee

### ISSUE THREAD

**Issue by Jose190** [Monika-After-Story/MonikaModDev#3819]
![screenshot0054](https://user-images.githubusercontent.com/47601477/53181241-95d76580-35cd-11e9-92d0-1ba10be5a193.png)

**Comment by ThePotatoGuy** [comment]
going to mark as duplicate of #3820 as this is a result of not having functionality in linked issue

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
