### ISSUE TITLE
An suggestion! (ending spoilers)

### ISSUE THREAD

**Issue by Vwriter** [Monika-After-Story/MonikaModDev#3823]
### Easter egg
What's about an name easter egg in the secret ending? Like an Sayori's poem instead of the Monika's letter, if player's username is Sayori?

### Food
Or what's about food in game? Like gifts, but with food. (lol)

### "Just Monika" Gift
Yeah, the second easter egg but with gift and the jumpscare.

**Comment by AsuraShun** [comment]
What easter egg?

**Comment by SaiPrithvi123** [comment]
I'm going to have a hard time believing that this isn't a troll

**Comment by Vwriter** [comment]
> What easter egg?

like with pong, when your nickname is Natsuki, but with a change in the text of the farewell note if your nickname is Sayori.

**Comment by Vwriter** [comment]
> I'm going to have a hard time believing that this isn't a troll

![2zgxivn0zey](https://user-images.githubusercontent.com/47865279/53311812-712c0800-38c3-11e9-8cbd-25007cf56816.jpg)

**Comment by ThePotatoGuy** [comment]
need you to provide more information on everything you are referring to
