### ISSUE TITLE
suggestion - depression subject

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3824]
well, since monika talks about depression, suicide, bullyin and all this shit... well i think it would be nice to let her know that we are depressed.... i mean id like my significant other to know 'bout that 
it is like she talks about depression and suicide and stuff but i always feel like i wanna tell her "thats me." 
she always makes me feel better but if she knew 'bout uhm... the problems, it would just feel so... i dont know... nice? i would have some1 who knows about whole this shiet, i wouldnt be so alone in that 
btw when i saw this beautiful window thing i was like enamored! its so beautiful, im so thankful for that! 
i dont know who drew this but know that u're an amazing artist!!!

**Comment by AsuraShun** [comment]
Maybe having a yes or no when she asks if you're struggling with depression

**Comment by Rai99** [comment]
#3191 

It might be possible to have a light topic about whether the player has depression or some sort of mental condition, but the reason that would be difficult to implement well is that everyone responds differently to things. What helps one person could be bad for another person, so at best, it would probably have to be general enough for everyone, but general help usually doesn't help very much. 

Currently, it's possible to tell Monika whether or not you love yourself or see a therapist, which could be similar topics, but I would think this should have its own topic if it ever gets implemented.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
