### ISSUE TITLE
ACS - Silver Necklace.

### ISSUE THREAD

**Issue by GwendolyX10** [Monika-After-Story/MonikaModDev#3825]
#3174 - Her classic necklace, but silver.
PSD: https://drive.google.com/drive/folders/13HX7EQAaMLpjTUC8OlkXUhbGXmOSKivm
![silvernecklace](https://user-images.githubusercontent.com/38970166/53205635-998adc80-360d-11e9-808d-8a37567bac85.png)
![silvernecklace-leaning](https://user-images.githubusercontent.com/38970166/53205638-9c85cd00-360d-11e9-834a-0d28577d3bb1.png)

**Comment by VirginiaRocks** [comment]
It's really cute :)

**Comment by ThePotatoGuy** [comment]
@EntonyEscX what name would you like to be credited with when I add this (and your other stuff) to the spritepacks?

The name will be refernced in the spritepack names and acs ID

**Comment by ThePotatoGuy** [comment]
It appears that we already have a silver version in the vday psds. Since you made the gold ones, I'll assume the ones we have were also from you.
