### ISSUE TITLE
[Translation] - Alternate Russian translation

### ISSUE THREAD

**Issue by Neko-Monika** [Monika-After-Story/MonikaModDev#3826]
It's the same version as the #3761, but with many grammar, stylistic and technical mistakes fixing.

Here's the link on our translation (check "Последняя версия, переведённая на данный момент времени"):
http://fufsob.ru:4567/wiki/Monika_After_Story#.D0.A1.D1.81.D1.8B.D0.BB.D0.BA.D0.B8

**Comment by Qwerdy123** [comment]
If you guys need some kind of feedback, I can do that. Some of the translations could use polishing. I have no idea how to fix them though. Just need a place to report.
