### ISSUE TITLE
I cant put in more custom music

### ISSUE THREAD

**Issue by KRSSPR103** [Monika-After-Story/MonikaModDev#3827]
I can't put in more custom music. I dled two songs (best day ever & ocean man) I wanna play in the mod, but when monika goes to check the folder, she can only find one song (best day ever), and not the other. I dled another song (sweet victory) I wanted to play to see if that song was the problem, but again, she couldn't find that or the other. is there something wrong that im doin?

**Comment by multimokia** [comment]
Screenshot of your `custom_bgm` folder, with filepath, please?

**Comment by KRSSPR103** [comment]
<img width="675" alt="custom bgm" src="https://user-images.githubusercontent.com/47894013/53250485-74719900-36f5-11e9-8f27-804dfadb4c7e.PNG">

like this?

**Comment by multimokia** [comment]
What's the filetype on those songs?

**Comment by KRSSPR103** [comment]
MP3 all

**Comment by multimokia** [comment]
Hmm. Mind trying this in a MAS install *not* in a Steam directory?

**Comment by ThePotatoGuy** [comment]
upload `log/mas_log.txt`

**Comment by KRSSPR103** [comment]
what do you mean by that?

**Comment by multimokia** [comment]
In the main ddlc directory, there's a `log` folder. Inside there should be a `mas_log.txt` file. Would you mind sending that over, please?

**Comment by KRSSPR103** [comment]
I tried to put it in this comment, but it says "This file is empty"?

**Comment by ThePotatoGuy** [comment]
[closing as cannot reproduce]
