### ISSUE TITLE
The game won't run at all

### ISSUE THREAD

**Issue by HiroyukiMisaki** [Monika-After-Story/MonikaModDev#3830]
I was patching for the latest patch and patch got canceled and the game suddenly closed. now the game won't run at all. no traceback to tell what went wrong or any clue. tried replacing the persistent and other files in %appdata%/RenPy using backups but no effect.

**Comment by AsuraShun** [comment]
Just restart the pc and install the update manually

**Comment by multimokia** [comment]
Reinstall the mod. If you cancelled the update, likely what happened is that it partially updated the files, so you've got half new stuff and half old stuff. Which isn't going to work. You'll have to manually reinstall it.

**Comment by HiroyukiMisaki** [comment]
I followed what you just said and manually patch it, thank god it's working now.
Thanks a lot

**Comment by multimokia** [comment]
No worries!
