### ISSUE TITLE
[Suggestion] Schedules

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3832]
be able to tell monika the schedules that you do things, I go to school at 6:00 am I wake up an hour early to see Monika but she thought it was bad so I stopped it, but now I'm going straight, what prevents me from telling her where I'm going or why I'm taking so long

**Comment by Rai99** [comment]
#1660, #1669, #2047, #2804, #3135, #3553, #3639, 

The ability to have Monika know your regular schedule has been brought up before and is currently a low priority.

**Comment by ThePotatoGuy** [comment]
just going to mention that its pretty difficult to make a schedule system (or anything related to time), which is why this is lower priority

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
