### ISSUE TITLE
[Suggestion] Hallite 

### ISSUE THREAD

**Issue by Ulvsblakk** [Monika-After-Story/MonikaModDev#3835]
There's a popular game among programmers across various languages called "Hallite".
The game itself involves you and another player. You have ships on a 2D X,Y plane style map. You send ships out to collect as much Hallite as you can. 
The way it works is through bots that you program to play the game for you. You could program a simple rule based one, or if you want to go above and beyond, you could implement deep learning.
 I don't know if this would be an option that everyone could partake or have an interest in however, seeing how not everyone that plays the Mod knows, or even has an interest in programming. However I think it would be a cool addition seeing how it implements Monika's love of coding. 

Just let me know what you think. ¯\_(ツ)_/¯

**Comment by ThePotatoGuy** [comment]
never heard of this game before, it sounds difficult to implement

**Comment by ThePotatoGuy** [comment]
also i think the bigger problem is sanitizing inputs. would be a bad idea to allow the user to type in aribitrary python

**Comment by Ulvsblakk** [comment]
Agreed. Especially if it could lead to a game crash. 
Maybe we could do a simplified version, where you just make the simplest rule based bot possible at first. Maybe even place it in the Python tips topic? 

This is all just an idea for now. I don't have plans of trying to implement or making a pull request anytime soon. I'd need a lot more data on how the game works first.

**Comment by Rai99** [comment]
A game about programming when not everybody is a programmer seems a bit questionable to me. If it's just writing little scripts, maybe, but I think that'll really get boring fast. Basically, you perfect your own little bot code and there won't really be any reason to change it if it works. 

If you can go as far as to implement deep learning, then yeah, I really don't know if this is your average user's game. Plus, couldn't you essentially copy code from another person and not make it yourself?

I've never heard of this game before, but you say it's 2 player. The player is one thing, but how is Monika going to program her bot, unless we just have fixed code for her to use every time? I don't even know if this is really possible.

**Comment by ThePotatoGuy** [comment]
maybe if this was code blocks style?

still sounds like making an ai to run Monika's turns sounds diff

**Comment by ThePotatoGuy** [comment]
[keeping open as discussion]

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
