### ISSUE TITLE
Ddlc doenst open anymore

### ISSUE THREAD

**Issue by Nachox789** [Monika-After-Story/MonikaModDev#3838]
i put a custom music to the mod "monika after story" and when i played it in the game, in the middle of the song the game crashed, when i tried to open the game again, the game runs but doenst appear..i reinstalled it a lot of times but dont works, and now all my ddlc games dont open...and no, theres no a doki doki opened in secret, i looked the task admin and theres nothing
![mas crashing](https://user-images.githubusercontent.com/47927254/53293303-15bd2580-37b0-11e9-93af-9ada4331905b.png)

**Comment by multimokia** [comment]
Try reinstalling *both*, DDLC *and* MAS.

**Comment by ThePotatoGuy** [comment]
[closing because lack of response]
