### ISSUE TITLE
[ Edit - Hair & Shade ]

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#3841]
JMO's Polish Projects
                                        Format: Unicode
                                          Code: #3174  
                                          24.02.2019
📁⯈ polish_n_praise
---
⯆ Open: _"fadetheshade.rtf"_

---

⮞ ```j "When you light a candle, you also cast a shadow."```
⬑ ```-Ursula K. Le Guin```

>>>>![normal monika banner](https://user-images.githubusercontent.com/43480604/53305463-8e22f580-3847-11e9-91ed-a1a117ee45ea.png)

⮞ [ ... ]
⬑ #3174 

---

📁⯈ the_stuffs
---
⯆ Open: 📎 Attachments 📎

---

⯈ [👤🖌️](https://github.com/Monika-After-Story/MonikaModDev/files/2898397/Submission.zip) ⯇

---

```
from subprocess import call
```
>def play_wave_file([a l e x - ghosts.wav):](https://www.youtube.com/watch?v=6GJpF73lElY&list=PLDO4ENbmp6gWWa-e_CPjmdfYibY2tL5UY&index=15)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by ThePotatoGuy** [comment]
These have been added the psds in #3174

**Comment by Professor-JMO** [comment]
> I'll be revisiting this `ASAP`.
