### ISSUE TITLE
better night filter

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3842]
the current night filter has some problems:
- only on photoshop
- removes cyan/blues when all layers are applied
- requires us to export each sprite twice, one for day and one for night
    - this also means double the art assets/double the size
- some people say it makes monika's skin look too yellow

There has to be a better way to do night images, ideally a type of filter that can be used in renpy so we don't have to make a separate night version of each image.

Couple of options for a new night filter
* simple image overlay that can be shown over everything in-game 
    * would also overlay over bg, so bg + windows would be affected
* use [image manipulators](https://www.renpy.org/doc/html/displayables.html#im-matrixcolor)
    * this would most likely cause per slowdowns
    * this would be very hard to preview in photoshop/gimp, as its done by renpy so it would be hard to see the actual effect out of the game.
    * this would allow us to only darken monika sprites instead of affecting everything

**Comment by jmwall24** [comment]
an image overlay would be nice since we could use it to dull the light and rays that come in the window at night.  currently the same amount of light comes in at night as during day.  it looks like an unnatural amount of light for night time.
![screenshot_497](https://user-images.githubusercontent.com/36523761/53310056-3309f680-3879-11e9-9b27-b73d0a2a474d.png)

**Comment by Olliesama** [comment]
Sad to say but there isn't really a single universal overlay that would look better than the current filter. >.<
Probably be better to tweak with the current one.

**Comment by ThePotatoGuy** [comment]
from @aldoram5 

>I was waiting to hear about the json sprites work because of how the night filter can work, so on that front first thing to note is that im.Matrix doesn't work with live composites, it just like working with images only, which means that for the night filter we'll be using one for each part of the sprite if we do go that way, which can prove to be beneficial and also make things a lot more complicated, since we could store the params for the filter on the properties of each sprite object on the json so we have full control of how each sprite is rendered(blue colored sprites can get the exact tones this way). The parts that will add more complexity are: 
>- The functions that makes the string that gets parsed will be more complex to work with and maybe even harder to maintain
>- Performance impact, I haven't noticed much impact on using 3 im.matrix functions over the Monika sprite but that may change as we add more "layers" of accessories, etc.
I tried with just a simple image overlay but that doesn't quite look good

going to drop night filter in renpy for the time being. doesnt' seem worthwhile despite that it would allow us to break away from psd filters.

**Comment by ThePotatoGuy** [comment]
it has been done
