### ISSUE TITLE
[Suggestion] - The "Thank you" button

### ISSUE THREAD

**Issue by ManuEcheveste** [Monika-After-Story/MonikaModDev#3845]
Hi to all the MAS team! First of all I want to tell all of you that you have been doing an excellent job with this little mod!
My suggestion is one I've been thinking for some weeks and have a very clear idea is the "Thank You" button, like the "I want to tell you something" or the "I want to apologize" buttons. Obviously I looked if someone else posted something similar, but the idea is quite different from mine (In my opinion). Some examples for this button are:
"Thank you"
For being here with me.
For helping me feeling better (if you tell Monika you was feeling angry, sad, anxious, etc.).
For forgiving me (if you apologize before)
There can be lot's of options to tell Monika how thankfull you are with her! (even it can help the affection variable to grow up or down)
I´m suggesting this because I don't have the time and the skills to do that in a short time. I'm still an amateur, but I'm sure I'll try to do it (in a long time but well done) or with other topics.
For your time and attention, thank you~

**Comment by skyloom** [comment]
If I'm not mistaken, that feature exists, but only if your affection is higher. Maybe you haven't just seen it yet?

**Comment by AsuraShun** [comment]
It does exist already

**Comment by bittercaramel** [comment]
I never saw it, can someone tell me where is it? id like to thank monika but idk where is this option

**Comment by multimokia** [comment]
Check the affection wiki for where it is/when it unlocks.

**Comment by bittercaramel** [comment]
tho ive got enamored aff and i dont remember having this option even once
where should it be located if i never did it before?

**Comment by ManuEcheveste** [comment]
I didn´t realized that that button really exist, because I didn't saw it on the game or in the code (I just wanted to be sure that the button doesn't exist checking the code before I upload this, but I can see that I didn't search it well)
Anyway, thank you all for the participation!
I'll try doing my best on the topics I'm working on :D ~
