### ISSUE TITLE
Clothes - Casual Blue Shirt.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#3846]
#3174 

https://drive.google.com/drive/folders/19zoJRgDQrQyFxu7fWxtzZB1CnS71wpJ8

Based upon this outfit.
https://i.redd.it/hw3pckvumdg01.png
Done by EroNeko.
https://www.deviantart.com/eroneko-senpai

**Comment by EntonyEscX** [comment]
Yay! Another outfit for Moni! >w<

**Comment by lunulae** [comment]
Absolutely love this one <3

**Comment by ThePotatoGuy** [comment]
So I think the crease lines between arms/base shouldn't be black since the clothing is light. However, the edits to fix that are kind of small, so I think we can do that ourselves. But this will have to be low priority as a result.

**Comment by moniking** [comment]
It's funny you should post that I'm actually doing this outfit and several of the other ones from OurTime ,I've got quite a few of them done but I need to do some tweak work to fit the required specifications. Do you have any other outfits you think might be nice I can try them out when I get these done, I'll try to add some pictures here to show my progress

**Comment by ThePotatoGuy** [comment]
for now, we'll be just removing hair shadows. Will aim to get this in 095ish maybe

**Comment by ThePotatoGuy** [comment]
okay so blue shirt is a little difficult in that the blue parts have to be night composited separately. this will continue to be low priority and will likely be pushed to 096 instead.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
