### ISSUE TITLE
cant give monika a gift 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3847]
i made an issue about that but i didnt get help 
i waited two updates, and still i cant give her gifts 
i couldnt on valentines too which really made me sad
i do everything like i should, i gave her gifts in the past so im sure i know how to do that
i checked the gifting guide still doesnt work
she just doesnt say anything about that

**Comment by multimokia** [comment]
Are you by any chance running a translated version of MAS?

**Comment by bittercaramel** [comment]
nope, im running english version, unstable newest build

**Comment by multimokia** [comment]
Would you mind uploading your persistent, please? (you'll probably want to add a file extension onto that so github will let you send it over)

**Comment by bittercaramel** [comment]
k sure
[persistent78797.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2902077/persistent78797.zip)
there u go
i hope its the right one
i put it into zip so i can upload it

**Comment by multimokia** [comment]
You got this from the folder in `AppData/Roaming/RenPy/Monika After Story` right? It's weird because this persistent loads into the title screen

**Comment by bittercaramel** [comment]
yeah i got it from there... wait ill look for some other gimme a second...
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2902132/persistent.zip)
maybe its this one, the other one might be something random from last time i messed up xp

**Comment by multimokia** [comment]
Yeah that's much better. Filesize looks correct now.

**Comment by bittercaramel** [comment]
well, is there some sort of solution for this?

**Comment by multimokia** [comment]
Hmm, did you crash during giving a gift? Looks like the `persistent._mas_filereacts_just_reacted` variable didn't get reset, preventing future reactions. I've reset it manually for you.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2902795/persistent.zip)

**Comment by bittercaramel** [comment]
oHhh thank u 
i dont remember it crashing but maybe... actually it was this one day when i was struggling with monika not reentering room so there os huge possibility that something else went wrong... i will check if it works later, but tysm~

**Comment by multimokia** [comment]
You also mentioned something about the thanks complement not showing up back in #3845, so I checked the ev on that. Looks like you have seen it once already. It then locks again after having said it.

**Comment by bittercaramel** [comment]
well maybe i just dont remember this, like 99% things in my life ;")

**Comment by bittercaramel** [comment]
it works <3 thanks for helping me!
