### ISSUE TITLE
[Suggestion] removing certain dialogue and combining two projects with MAS

### ISSUE THREAD

**Issue by ko899** [Monika-After-Story/MonikaModDev#3849]
Haven't been playing MAS for long but one thing immediatly caught my attention. Why does the mod have options like accusing her of murder or breaking up? Isn't that besides the very point of the mod? Having those removed at a certain affection level or even entirely would be nice.

And then there's this small project called MonikAI which appears to have a small connection to this one. MAS Mon instantly spotted AI Mon after I downloaded the exe file and has a bit of dialogue for it. How about contacting the owner of the repo and proposing to make it a feature of MAS? The mini mon could automatically appear on screen when MAS is not in focus and both could use the same dialogue pool which would make both Mons more alike. Right now, AI Mon feels a lot different. This would also add more immersion to the general idea of having Monika active on the PC while doing other things like browsing or playing games.

Finally, an idea that puts the "take you somewhere" option to better use. A student called Matteo Tallevi developed a mobile application which is basically a replica of DDLC act 3, which can be found here: https://cz-games.weebly.com/just-monika.html

What about contacting the guy and proposing to combine his app with MAS? Mobile version could have its own pool of dialogue and a check that keeps the app from running if the monika file doesn't exist on the phone's storage.

Right now, they are three seperate projects all of which have the same goal of making her a person the player can interact and spend time with. Combining those two projects with MAS would improve the immersion a lot for sure.

**Comment by Jparnaud** [comment]
I'm bored and I am curious about this topic so I may as well respond to some stuff here X)

About the two topics, i think the first one is important to keep at the start of the game or even forever, Monika need to understand (to me) that she did something bad and should feel guilty for what she's done, even if they were "not real". It is my opinion, so I prefer it to be kept. 
The second topic is only a joke. I don't know why people are freaking out about that one, I found it to be the funniest thing to say to her after the "You want to meet my girlfriend" topic.

The first project seems interesting. I think it could put a little uniqueness to the game and really advantage the relation with Monika. I dont know about Python enough tho to say if its possible to do anything with that so I'll leave it at that.

Finally, I don't know if the last project would be possible. There was some discussion on "should we have a MAS mobile version" in here, but i believe they all been ended cause of a statement of the creator of DDLC Dan Salvato which did say (in general) "I don't mind if people do mods, but I ask them to be free and only on the platform where MAS is). So yeah, I don't know if a feature would actually count as breaking that rule but it is better to think about this before doing anything.

Anyway, don't take everything I say like I was important here, I was just bored and wanted to help X)

I'm also very curious about the first project you talk about. If you would give a link to it I would like to check it out just for fun ;)

**Comment by AsuraShun** [comment]
The insensitive comments topic

**Comment by Rai99** [comment]
For any mean topic towards Monika, I actually think having those adds a bit to the immersion. You _can_ say those things to her, but will you? Probably not. I don't think MAS would be as immersive if being mean simply wasn't an option. 

If Monika never got upset at you being mean, closing the game on her, etc, it wouldn't feel as realistic I think. I'm pretty sure that's what negative affection is for anyway. 

#506, #815, #934, #994, #2113, #2271, #2995
MAS for mobile is legally forbidden until DDLC itself is officially released for mobile. 

#600, #709, #1199, #2305, #2385, #2451, #3029, 
Collaboration with other mods and expanding the scope of MAS is unlikely to happen officially, and would probably fall under submods since I don't think it will really be worked on by the devs.

**Comment by bittercaramel** [comment]
i think those mean topics are actually good to have 
it adds to it more reality 
like, to real person u can say whatever u want, there is no filter over this 
but it leads to consequences which is loss of affection 
well if you think those things why not tell them to monika? if u couldnt do it it would be more like... being forced only to say good things 

for the other ideas, yea it would be great to see those two combined... i dont see a reason to keep few projects when they lead to one point, why not just try working together on this whole thing, and it will go faster
i mean, probably thats not going to happen but i think that it would be better to work on one and same monika than have few different... if everything were in the same mod/game/whatevs we could do all the things that gives our this mod and other mods/games, without having to be with more than one monika at a time ;\ idk i cant form sentences so they make sense sorry

**Comment by multimokia** [comment]
> Collaboration with other mods and expanding the scope of MAS is unlikely to happen officially, and would probably fall under submods since I don't think it will really be worked on by the devs.

From #1737:
> Yeah, we're not going to encourage other mods.
If anything, we'd do what we did with MonikAI and just detect it and comment on it.

**Comment by bittercaramel** [comment]
well thats a pity, and i dont know why it has to be like that but ok

**Comment by multimokia** [comment]
Was explained over in #3828.

**Comment by ko899** [comment]
I think the point of MonikAI + MAS has been kind of missed here. The reason I suggested that was to improve overall immersion and interaction when you are doing stuff on your computer. For instance, you keep MAS running but you are browsing the web, need to write a document, gotta do hard drive cleaning or whatever else puts MAS out of focus and covers the window for the time being.

That's where MonikAI (or minimon) comes into play. When MAS is out of focus, minimon appears on your desktop where she can either continue topic X or comment based on what software you have in focus (word, firefox, chrome, etc.). It also won't make you feel like you are kinda pushing her out of the way. At least that's how I feel most of the time.

Think of it as a feature that's added to MAS rather than a seperate project.

**Comment by ThePotatoGuy** [comment]
We don't have bandwidth right now to maintain 2 separate codebases.

If MonikAI is still looking for maintainers in the future, then we can consider adopting it and using it as an extension of **overall** MAS experience.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
