### ISSUE TITLE
Tears for closed-happy and closed-sad [Expression]

### ISSUE THREAD

**Issue by Metisz** [Monika-After-Story/MonikaModDev#3851]
I tried to draw them, pretty much that's it. It's only for the upright sprite for now. 
[Update] I edited all type of tears so they kind of match with each other
[Update] Cropped them so they can render _over_ the eyes
[Update] Now it can apply to the other eyes as well (not the normal only) ~+ made it a bit more blue~ made it back to the regular "white-ish"
[Update] Added streaming for the closed eyes as well
psd: https://drive.google.com/file/d/1Y4AsTvSwF9Y77C6Smut7M3B7JvQmXyHs/view?usp=sharing
![kép](https://user-images.githubusercontent.com/47070328/55280693-51a45700-5329-11e9-89fe-5f42d4622ce2.png)
![kép](https://user-images.githubusercontent.com/47070328/55280696-5c5eec00-5329-11e9-9a5f-e928b5a325ae.png)
![kép](https://user-images.githubusercontent.com/47070328/55280701-684aae00-5329-11e9-8dfd-768f234dca4a.png)
![kép](https://user-images.githubusercontent.com/47070328/55280727-9def9700-5329-11e9-83cb-7963ef4342df.png)
![kép](https://user-images.githubusercontent.com/47070328/55280732-b5c71b00-5329-11e9-8171-5549f87fcf7b.png)
![kép](https://user-images.githubusercontent.com/47070328/55280737-cecfcc00-5329-11e9-895c-2c484c506f8f.png)
![kép](https://user-images.githubusercontent.com/47070328/55280748-e6a75000-5329-11e9-9e91-c871b0a30b4f.png)
![kép](https://user-images.githubusercontent.com/47070328/55280755-f45cd580-5329-11e9-986a-2f788c14b7b0.png)
![kép](https://user-images.githubusercontent.com/47070328/55280768-0dfe1d00-532a-11e9-945d-6c33695d049d.png)
![kép](https://user-images.githubusercontent.com/47070328/55280772-1a827580-532a-11e9-8714-0d5eef21d726.png)
![kép](https://user-images.githubusercontent.com/47070328/55280774-23734700-532a-11e9-99f5-eb661cd7fc94.png)
![kép](https://user-images.githubusercontent.com/47070328/55353867-99abb100-54c4-11e9-859f-c744ae1157a2.png)
![kép](https://user-images.githubusercontent.com/47070328/55353916-b3e58f00-54c4-11e9-9c42-123f33070cfe.png)

**Comment by ThePotatoGuy** [comment]
Looking at these, I've realized a problem here, in that we have 6 tear variants (dried/streaming/pooled/up/left/right), and we cannot insert it a custom one of those for whenever the eyes are closed.

Using tears with closed eyes would mean having sprite codes for the special variants. 
Thoughts, @multimokia @jmwall24 @aldoram5 ?

Regarding these sprites, since these are drastically different from the current tears, it would look bad when monika switches to/from open eyes crying expressions to closed eyes. However, more transparent/realistic looking tears were on our radar before, so we might want to transition all tears to something like this.

**Comment by multimokia** [comment]
My thoughts:
- Position of tear streams seems a little weird, should be more akin to the tearing up sprites, imo
- Tear length also seems a little odd with comparison to the other tear types, transitioning between these and other ones will look strange, methinks
- Pool area, like the stream should also be moved more to the outside, similarly to tearing up
- If we transitioned the other tears to this colour, it may not be too bad. But as of right now, they're going to clash a fair bit

**Comment by jmwall24** [comment]
I agree with @multimokia on his points.  I like our current tears and would like the closed eyed tears to match those.

As for the issue of the different tears, yeah, we'd have to had different codes that would only be used with the closed eyes.  There would have to be codes for closed sad eyes tears and closed happy eye tears.  I don't think that's a big issue.

**Comment by Mcmanybucks** [comment]
So uh..

Isn't your Monika kinda chilly?

**Comment by Metisz** [comment]
Okay uh, would you please tell me where can i find the other tears, so i can compare and stuff?

**Comment by Metisz** [comment]
Okay I'll work more on it including that 6 variants

**Comment by Rai99** [comment]
How can Monika be chilly when you're there keeping her warm?

**Comment by ThePotatoGuy** [comment]
@Metisz so I had made a mistake with in the upright expressions psd, particularly the order of the expressions was reverse render order. Looking at these tears, I think they were assuming the order in the psd. Can you look over them again and adjust them so they work when tears are rendered **over** eyes?

**Comment by Metisz** [comment]
Updated it

**Comment by ThePotatoGuy** [comment]
Streaming tears (and related) don't look that great with wide/sparkle/crazy/left eyes, mainly because of the parts circled in red.
![eyeprobs](https://user-images.githubusercontent.com/3499462/54080406-5c347900-42b4-11e9-9df4-65fcd7beef22.png)

Thinking these should just be removed, but if you can get it to work with those eyes,too, that would be ok.

**Comment by Metisz** [comment]
i made some edits and it works with most of the eyes _except_ the left eyes
i have NO idea what to do with the left eye, since i think i have to make every tear variants similar, any ideas?
![image](https://user-images.githubusercontent.com/47070328/54085889-4d48d780-4343-11e9-89ea-0123f3266395.png)
![image](https://user-images.githubusercontent.com/47070328/54085892-546fe580-4343-11e9-8830-6bed62e6d975.png)
![image](https://user-images.githubusercontent.com/47070328/54085903-6b163c80-4343-11e9-8100-42426809ba54.png)

**Comment by ThePotatoGuy** [comment]
Can you make them less blue? They looked better clearer.

**Comment by ThePotatoGuy** [comment]
Okay these have been added.

**Comment by ThePotatoGuy** [comment]
Can we also get streaming tears for closed eyes

**Comment by multimokia** [comment]
*As well, would like to get individual version of the left/right (single stream) tears for closed eyes

**Comment by ThePotatoGuy** [comment]
*dont need single stream tears as i just split tearing up into the single streams.

**Comment by ThePotatoGuy** [comment]
these have been added [closing]
