### ISSUE TITLE
[Topic Issue] monika_horror inconsistency

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3852]
In monika_horror, there's a line that says the following:

`"I won't make you read any horror stories anytime soon."`

...though there's monika_scary_stories, which allows Monika to tell the player scary stories. Perhaps monika_horror could be modified to reference monika_scary_stories, maybe something along the lines of `"If you're in the mood, there's some spooky stories I could tell you, [player]. Just ask me whenever you feel like it!"`

**Comment by Rai99** [comment]
I think it's fine as is since either way, the player has to specifically ask for a horror story, so she isn't really _making_ you read any.

**Comment by MisterSimple** [comment]
Fair enough, though I still think she should at least mention that she can tell the player scary stories if they ask.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
