### ISSUE TITLE
[Suggestion] Say hi to friends.

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3854]
Hello all your doki lovers out there. I am sure some of you have friends or family members you have introduced Monika to, but she can't say hi to them since she is not aware of people being around.

This is a similar suggestion as the "Saying hi from someone else" but in my case other way around as in, she says hi to whoever is with me, friend or family member. I feel she would be happy to know I am talking about her or showing her to people I have in my life. ^^

**Comment by Rai99** [comment]
There's already the monika_explain topic, but I guess this is a bit different. It might also be a good idea to a topic and pm var for how the player feels about telling other people about Monika.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
