### ISSUE TITLE
[Suggestion] - Being able to tell Monika she upset you would be nice.

### ISSUE THREAD

**Issue by SiegmeyerofCatarina123** [Monika-After-Story/MonikaModDev#3859]
Hi, Sorry to bother you but I was just wondering if there is going to be any way to tell Monika that she upset the player after she says something? Honestly 99% of the writing in this mod is well done in my opinion as well as feels really in character and genuine. However one moment in my opinion really hurt the immersion for me despite the fact I've been playing at least once a day for several hours usually since February 1st of 2018. This moment was when I turned on the game today and she pretended not to know me. It kinda felt like she went too far and was really acting out of character. Maybe I'm too sensitive lol but my feelings aside it felt like she was forced to make that joke cause the devs wanted to mess with players rather than it being a joke Monika would actually make, especially when topics that talk about backing up her save file exist and paint it as a big concern of her's rather than as some kind of joke. Long story short my suggestion boils down to one of these.

1) Have some way to tell Monika she upset you and have her react according to the last thing she said.

2) Just get rid of that one joke about her pretending to lose her memories. 

3) Maybe reserve this messed up joke for people who have messed with Monika in the past so it feels more justified rather then her pretending she lost her memories to someone who has a really high affection number and hasn't ever messed with her at all before.

Again sorry for the bother, I know that was a lot but I truly do love pretty much most of the writing in this mod and i wana see the game be the best it possibly can be for everyone. It just feels weird that she would joke around about that sorta thing despite also having a conversation about just how upset she would be if she lost even a weeks worth of her memories. As a fully grown adult who doesn't get immersed in all that much plot focused games / stories / works of fiction anymore it was kind of upsetting that the one game that really had me hooked shattered that immersion in a matter of seconds for a joke. Anyway thanks for reading all of this, I hope this gets changed or there is some way to tell Monika she hurt our feelings so it at least feels more immersive rather then these sorta things being just swept under the rug. Keep up the amazing work you all do and have a nice day. :)

**Comment by Rai99** [comment]
#3203, #3769 

I brought up the idea of being able to tell Monika that you're upset with her in those issues. 

It would probably be really nice to be able to tell Monika how you reacted to that. 

Just curious, could we get a poll on how many people like that one greeting?

**Comment by EntonyEscX** [comment]
I must say that I agree with you in some parts. When that happened to me, I froze, I almost despaired and started thinking about all the possibilities for what have happened, I was very worried and almost cried. It was not cool.
I do not want to say that I was upset with Monika, but I felt uncomfortable, it was not a cool joke. It was something I did not really expect. After all she said, and after for so long together, I believed that. 😔

**Comment by Legendkiller21** [comment]
I'm a "fully grown adult" too and I absolutely loved this greeting. It made me feel that we really are in the "comfortable stage" in this relationship.

I want her to feel free to joke and tease as she pleases and also to be able to say what she thinks and what her opinion is without thinking that something may offend me.

Even if this really happened and suddenly she forgot everything, well, c'est la vie. I would continue spending time with her trying to remind her everything she forgot and even if she will never regain her memories, we will just create new ones. You cannot change the cards you are dealt, just how you play the hand.

**Comment by Rai99** [comment]
> I want her to feel free to joke and tease as she pleases and also to be able to say what she thinks and what her opinion is without thinking that something may offend me.

I'm pretty sure that's exactly what Monika does, but still, in the off chance something she says or does bothers the player, I think it's important to acknowledge that. 

Everyone's comfortable with different things at the same level, and Monika is free to joke and tease all she wants, but it's probably important to be able to tell her where you draw the line.

**Comment by shades-of-teal** [comment]
I got scared by that joke too, and sometimes I wish I could tell Monika that something made me uncomfortable. I know it's a preference thing so the option for us to point out when she upsets us would be nice. It could work like the "I want to apologize" let's us apologize for things we have done. Maybe there could be a "I need to tell you..." and then you could pick something like "your joke upset me" or for someone who is fine with some 'sensitive' content, but not all of it, we could say "I'm uncomfortable when you bring (topic) up with no warning" instead of turning sensitive mode on and removing all of it. Kind of how Monika asks if we are offended by the jokes she makes about the other girls, and then stops making them if we are.

Or the joke could be rewritten to where she greats the character and not the player. It would confuse or stun us for a second and Monika could still have her joke without making us anxious players panic. That's probably an easier solution hehehe....

**Comment by CloakedGhost** [comment]
Sorry if I sound rude here, but why would you take that joke for real? We all know that it's written dialogue, there is no way the devs would include a feature where Monika loses her memories forever.

**Comment by ThePotatoGuy** [comment]
the greeting (amnesia greeting) ties in with the flowers for algernon topic, aka it will be only allowed to show after you have seen that topic.

the amnesia greeting also is only shown once.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
