### ISSUE TITLE
[Suggestion] (Topic included) - Monika's Real Life Body and Robotic Ethics

### ISSUE THREAD

**Issue by dragonsni** [Monika-After-Story/MonikaModDev#3864]
Hi guys, I wanted to make a contribution of some sort so I decided to write my first dialog for Monika.
As much as I want to, I don't know enough about Python yet to write this in code so I made it in a text document.
Any feedback on this would absolutely be appreciated.

[monika_roboethics.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2912283/monika_roboethics.txt)

**Comment by Rai99** [comment]
I think it looks like a nice topic, but I'm sure there are also a few other science fiction stories with at least a slightly different spin on the whole AI/android concept. 

I think it could be expanded a bit to discuss a bit more about each of the 3 laws and potentially why they're likely important. It seems like a bit of a dark topic, but that should be fine. 

It might also be an interesting idea to talk about how a robot uprising could actually happen, but that might be a completely separate topic. 

If you do plan on submitting this in a PR, don't forget to add sprites to each line. The contributing guidelines can be found on the wiki.

**Comment by dragonsni** [comment]
Alright I appreciate the feedback, Once i learn python more I'll be sure to add all that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
