### ISSUE TITLE
Working on Split Neko / Witch hair

### ISSUE THREAD

**Issue by linkone2** [Monika-After-Story/MonikaModDev#3870]
What would I need to separate from the images? How would I need to do it?
So Far I've got: 
Witch Hair Split from Body
Witch Hair Split Front and Back
**Front:**
![outfit1_hair-hat_front](https://user-images.githubusercontent.com/8854901/53580610-05a79c00-3b4a-11e9-8442-18bad06dc742.png)
**Back:**
![outfit1_hair_back](https://user-images.githubusercontent.com/8854901/53580643-19530280-3b4a-11e9-93d0-d1f44a1e60f8.png)
**Mock Up:**
![outfit1_hair_mock-up](https://user-images.githubusercontent.com/8854901/53580673-25d75b00-3b4a-11e9-8485-712e4ef4fda0.png)

Neko Hair Split from Body
Neko Ears Split from Hair
**Hair with No Ears:**
![outfit2_base_no_ears](https://user-images.githubusercontent.com/8854901/53580765-53240900-3b4a-11e9-9e05-b7aa16158ffc.png)
**Ears:**
![outfit2_ears](https://user-images.githubusercontent.com/8854901/53580906-99796800-3b4a-11e9-974c-8c63eeda53ba.png)

**Currently:** Doing the Neko Bows.

So what else would I need to do?

**Comment by Rai99** [comment]
Would you mind posting a preview or two here for people to see? Last I checked on the discord, there was a bit of a lingering outline, and I'm not sure if that's still the case. 

#3174.

**Comment by linkone2** [comment]
Fixed the look of the Witch Hair and Witch Hair Back
**Front:**
![outfit1_hair-hat_fix](https://user-images.githubusercontent.com/8854901/53582609-d2670c00-3b4d-11e9-9c5a-d0f92953146a.png)

**Back:**
![outfit1_hair_back_fix](https://user-images.githubusercontent.com/8854901/53582636-dabf4700-3b4d-11e9-8292-6d0f715d5e20.png)

**Mock Up:**
![outfit1_mock-up_fix-2](https://user-images.githubusercontent.com/8854901/53582654-e0b52800-3b4d-11e9-872b-cb91bdf7370c.png)

**Comment by ThePotatoGuy** [comment]
Ideally, we'd want the witch hat also split off from the hair.

**Comment by linkone2** [comment]
**Witch Hat:**
![outfit1_witch_hat](https://user-images.githubusercontent.com/8854901/53593695-524da000-3b67-11e9-9294-13b2314cbf20.png)

**Small Ribbon:**
![outfit1_small_ribbon](https://user-images.githubusercontent.com/8854901/53593720-5bd70800-3b67-11e9-9b9d-9b14a1666935.png)

**Mock Up:**
![outfit1_hat small_ribbon_mock-up](https://user-images.githubusercontent.com/8854901/53593741-672a3380-3b67-11e9-9e1e-f2d0666d1b65.png)

Anything Else?

**Comment by ThePotatoGuy** [comment]
![braidback](https://user-images.githubusercontent.com/3499462/53604671-c776a080-3b7a-11e9-97eb-93aa23b553a0.png)
The braids circled in red have the appearance that they go behind Monika's back. In that case, they should be part of the back hair layer. Could you separate the braids layer from the rest of the hair?

**Comment by linkone2** [comment]
**Front(Could be used on it's Own):** 
![outfit2_bow_hair_front](https://user-images.githubusercontent.com/8854901/53615630-d0806580-3bac-11e9-93e2-24c82b9b4809.png)

**Back(Doesn't Look Bad with Witch Hat):
![outfit2_hair_back](https://user-images.githubusercontent.com/8854901/53615643-e3933580-3bac-11e9-92bd-d22e270ccf74.png)

**Mock Up(Front Only):**
![outfit2_no-braid_mock-up](https://user-images.githubusercontent.com/8854901/53615650-ec840700-3bac-11e9-81cd-84c40c8db349.png)

**Mock Up(Front+Back):**
![outfit2_braided_mock-up](https://user-images.githubusercontent.com/8854901/53615653-f3127e80-3bac-11e9-98b6-8bdf13d0cf5c.png)

**Mock Up(Witch Hat):**
![wow](https://user-images.githubusercontent.com/8854901/53615656-fa398c80-3bac-11e9-9f2b-4c09877dc614.png)

Anything Else?

**Comment by linkone2** [comment]
**Leaning Neko Hair:**
**Front:**
![outfit2_leaning_bow_front](https://user-images.githubusercontent.com/8854901/53642834-a6f12980-3c00-11e9-8253-1dac2546ea81.png)

**Back:**
![outfit2_leaning_braids_back](https://user-images.githubusercontent.com/8854901/53642850-af496480-3c00-11e9-8418-152581b384fb.png)

**Front Only Mock Up:**
![outfit2_leaning_bow_mock-up](https://user-images.githubusercontent.com/8854901/53642868-bc665380-3c00-11e9-9a64-ed9ae2e14112.png)

**Both Mock Up:**
![outfit2_leaning_braided_mock-up](https://user-images.githubusercontent.com/8854901/53642891-c7b97f00-3c00-11e9-95ac-3313965b1c88.png)

**Comment by ThePotatoGuy** [comment]
These look good.

Can you check if the neko hairs you've made work with the upright/leaning base psds? (aka no gaps?)
Just upscale the hair to match the psd size since they don't match.

If there's gaps, you don't have to fix them, I just want to know if they exist.

**Comment by IRgsteredDletedMselfAndCmeBckJstForThis** [comment]
I don't mean to sound rude, but I it looks like this mod turned into a dress-up game while I was away. :/
(Joking)

**Comment by linkone2** [comment]
There are gaps at 200% scale on the hair, around the spot where I split the braids on the bottom right side bow, and a little behind her right ear, and a bit above the left side bang.

I'll post an image in a bit...

**Comment by ThePotatoGuy** [comment]
Can you remove the hair shade from the leaning neko hair? That shade is going to be replaced.

**Comment by ThePotatoGuy** [comment]
okay so, neko hair splits are good except for the shade gaps, but I dont think its worth trying to fix the gaps at a downscaled resolution. I'm going to create a TODO for upscaling the neko hairs and cleaning them up so they look good upscaled. (after you remove the shade, ofc)

The witch hat and ears have some gaps, but I can fill them in at a downscaled resolution. ACS isn't as universal as a hairstyle, so they don't need to be upscaled.

The small ribbon for the hair will have to wait a bit since we might change hair the standard hair strands.

**Comment by ThePotatoGuy** [comment]
and i have just remembered that witch hat and neko ears do not have leaning variants, meaning those will be marked as todos as well

**Comment by linkone2** [comment]
Sorry, I haven't been responding here, been feeling pretty crap lately. Do you have any shadeless base hair? I could try to mix them as, I didn't do the hair myself. I did the separation but not the drawing.

**Comment by linkone2** [comment]
PSD of the work I had ClipStudioPaint make:
https://drive.google.com/file/d/1dl9qi03PXUj4amje0zCYeTXrdSHTd2H6/view?usp=sharing

**Comment by ThePotatoGuy** [comment]
hairs are currently being potentially reworked so, i'll only be using the acs in here for now.

**Comment by ThePotatoGuy** [comment]
when we have leaning versions of this, then we can use it. For the time being, its in limbo

**Comment by kkrosie123** [comment]
[Closing as completed.]
