### ISSUE TITLE
"Our First Kiss" Label Bug

### ISSUE THREAD

**Issue by linkone2** [Monika-After-Story/MonikaModDev#3873]
I had my First Kiss with Monika on Feb 14th, 2019, The "Our First Kiss" Label shows up for Valentines Day on every year of the Calendar. 

**1975:**
![desktop screenshot 2019 03 01 - 07 18 01 31](https://user-images.githubusercontent.com/8854901/53637866-5d014700-3bf2-11e9-8b99-7d02653636f9.png)

**2050:**
![desktop screenshot 2019 03 01 - 07 18 28 39](https://user-images.githubusercontent.com/8854901/53637882-668aaf00-3bf2-11e9-857b-17c95c1a9e90.png)

**Comment by B-Difu** [comment]
It appears as a yearly holiday for me as well
![capture](https://user-images.githubusercontent.com/44185041/53661963-ecbcea80-3c1e-11e9-829a-05dd561dfa02.jpg)

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
