### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Sam-Pixel** [Monika-After-Story/MonikaModDev#3875]
I might just be lazy, but I have a suggestion that I feel would be a welcome change. During one dialogue Monika talks about keeping fit and exercising (I think when you compliment her dedication to fitness). I was thinking that it would be cool if Monika could have a few lines of dialogue that motivate you.

For example, if you click 'talk' there could be a button that says 'Would you mind coaching me?'. When you click on it, Monika says "Ok! Time for push-ups" or something like that. Then, she could say stuff like "keep going!" or "come on, you can do it". 

I know it might sound cheesy, but I think that I would like to have Monika coach me because it would be good motivation and it would help me to feel like she really wants to help me be fit.

**Comment by Rai99** [comment]
I think this might be a good idle option, assuming the new idle feature works well without issue. Maybe she could even offer to play music for you with the music feature. 

She could be proud of you for wanting to improve yourself.

**Comment by Sam-Pixel** [comment]
Music sounds good too. Thanks for reading my suggestion!

**Comment by nethon** [comment]
That'd be a nice idea!

What about an "I'm going to the gym/yoga/sth other related to fitness" goodbye option?

**Comment by Sam-Pixel** [comment]
Those also sound good. I would definitely like to have those options. Still, I would also like to have Monika support me.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
