### ISSUE TITLE
[Suggestion] stuck monika poses

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#3877]
When you use the "I'll be right back" button, she'll say her usual thing, but then stay in the smiling with her mouth open animation (pic below for reference)... I just think it's kind of weird for her to have her mouth stuck open the whole time like that while she's waiting. Just having her mouth closed would be good enough really, but using randomized poses could be fine too (though some may want to be removed from the rotation).

![image](https://user-images.githubusercontent.com/36053888/53677355-7353e500-3c7c-11e9-8be3-356299dd0464.png)

**Comment by CrocWorks** [comment]
Okay, never mind. Seems like it was a one time thing? That was the very first time I used that button off of the Unseen menu, but doing it through the regular menu has her in a more appropriate pose.

**Comment by ThePotatoGuy** [comment]
reopening this as an investigation issue. Will also cover #4223

**Comment by ThePotatoGuy** [comment]
[closing as coverd by linked pr]
