### ISSUE TITLE
[Suggestion] I'm going play some heavy game (goodbye option for I'm going to game a bit)

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#3882]
Some people just don't have good PCs to have MAS and another game open in the same time (and even if you a have a good one it will affect a little the game performance)

**Comment by AsuraShun** [comment]
She already asks for you to keep her open in the background

**Comment by Sujeito17** [comment]
@AsuraShun I'm talking about game performace, put her in the background will remove some performace of the game that you are playing (that can be even worse if you are using a super low end PC)

**Comment by softombre** [comment]
Yeah my pc kinda sucks so i can't keep mas open while playing osu so it'd be nice to tall her

**Comment by bittercaramel** [comment]
yeah that would be pretty nice, if there could be be right back but with closing the game ;v when i play other games sometimes MAS affects my performance ;\

**Comment by ko899** [comment]
Goodbye -> I'm sorry but my PC can't handle you at the moment. It needs to do something stressful now.


Like that?

**Comment by Sujeito17** [comment]
@ko899 I do not know why, but that seems to be a bit rude, something like "I'm going to game a bit -> I will play a heavy game for my PC -> Type of games" looks better

**Comment by Rai99** [comment]
~~"I'm going to play experimental Subnautica mods and I want you to be safe if I bluescreen"~~

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
