### ISSUE TITLE
[Suggestion] "I have to do chores/cleaning"

### ISSUE THREAD

**Issue by ko899** [Monika-After-Story/MonikaModDev#3883]
On my end, the idle mode works fine with the two new options but how about an option that's suitable for when you gotta do houseworks? "BRB" doesn't feel right for something that usually takes up half an hour or more in many cases.

**Comment by MedicMix** [comment]
I can take this one, if someone would like to assign it to me.

**Comment by Rai99** [comment]
Feel free to write it up and PR it when you're ready to have it reviewed.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
