### ISSUE TITLE
[Suggestion] - Add fifth option on "favorite car" topic

### ISSUE THREAD

**Issue by lucianotgm** [Monika-After-Story/MonikaModDev#3888]
A "hatchback" option could be added when Monika asks you what kind of car the player has. I want to assume some people who use the mod have one instead of a sedan or a sports car, or even instead of an SUV.
![screenshot0001](https://user-images.githubusercontent.com/48166721/53689258-9b048500-3d30-11e9-882c-258e7e78ad0b.png)

**Comment by Onion-Bubs** [comment]
Yeah, I drive a hatchback too.

Really, though, if there's going to be a fifth option, it should just be "other". There's too many different kinds of vehicles to do a thing on each one.

**Comment by lucianotgm** [comment]
> 
> 
> Yeah, I drive a hatchback too.
> 
> Really, though, if there's going to be a fifth option, it should just be "other". There's too many different kinds of vehicles to do a thing on each one.
> 
> EDIT: Having seen the dialogue for picking sedan, I think that same dialogue would work for hatchbacks too, so maybe renaming that particular option to be more inclusive of cars that aren't particularly big, off-roady or fast. What you'd call such an option I don't know, but sedan is too specific.

Maybe that would be easily solved with changing the option to "Sedan or Hatchback", in reality they aren't that different from one another apart from the extra trunk space, and Monika's dialogue is pretty on par with both of them. I think that's the better approach, very good idea indeed, Onion.

**Comment by ThePotatoGuy** [comment]
[closing as complete]
