### ISSUE TITLE
I had a problem when I updated MAS to it's newest update

### ISSUE THREAD

**Issue by ErnestoLaguna** [Monika-After-Story/MonikaModDev#3889]
Something really weird happened to me when I was updating MAS, everything seemed to be ok, but when the program finished unpacking the updates, an error happened. I didn't do anything, I swear! So could you please tell me how to fix this problem, please?  
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2922748/traceback.txt)

Also I have to say that I have installed the Just Yuri mod too, but in a separated folder. I checked in the %aappdata% files and in the Just Yuri folder I found this: 
[readme_justyuri.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2922749/readme_justyuri.txt)
I don't know if this has anything to do with this problem, but the last time that this note was edited was today. I can't help but feel that Yuri has something to do with all of this mess...

**Comment by multimokia** [comment]
Can we see a screenshot of your `game/` folder, please?

**Comment by ErnestoLaguna** [comment]
![image](https://user-images.githubusercontent.com/48169688/53702257-aa381100-3dca-11e9-9a09-36fd7b545790.png)
![image](https://user-images.githubusercontent.com/48169688/53702273-d6539200-3dca-11e9-8a99-d7758b2d985c.png)
![image](https://user-images.githubusercontent.com/48169688/53702298-04d16d00-3dcb-11e9-95ea-3b2cbe3af70c.png)
![image](https://user-images.githubusercontent.com/48169688/53702311-30ecee00-3dcb-11e9-9df0-89a89be9c8bf.png)
![image](https://user-images.githubusercontent.com/48169688/53702348-8f19d100-3dcb-11e9-9c5d-5a891ff105b7.png)
![image](https://user-images.githubusercontent.com/48169688/53702378-c7211400-3dcb-11e9-910f-e4c1daaa389a.png)
![image](https://user-images.githubusercontent.com/48169688/53702384-db651100-3dcb-11e9-8077-57c424344f11.png)
Also I tried to download the new update zip folder manually, because I thought that will solve the problem. But in the end the result was the same.

**Comment by multimokia** [comment]
Looks like the updater didn't finish what it was doing. Try getting a fresh copy of DDLC, and then installing MAS in there manually. That should do the job. Don't worry, you won't lose your progress with Monika.

**Comment by ErnestoLaguna** [comment]
Thanks for the help, dude! I was starting to blame Yuri for all this mess
