### ISSUE TITLE
Bro, wtf with that static and black and white shit. dont do that to me pls :/

### ISSUE THREAD

**Issue by peter23247** [Monika-After-Story/MonikaModDev#3890]

**Comment by multimokia** [comment]
Well...You did tell Monika you liked horror, and that you liked getting spooked...

**Comment by peter23247** [comment]
> Well...You did tell Monika you liked horror, and that you liked getting spooked...

[https://i.kym-cdn.com/photos/images/newsfeed/001/209/831/f93.jpg](url)

**Comment by monikLover** [comment]
RIP in peace peter23247
????-2019
![giphy](https://user-images.githubusercontent.com/33161947/53691008-76a5aa00-3d2a-11e9-9f5b-613c7b7fb7a4.gif)

**Comment by SaiPrithvi123** [comment]
It would be nice if she could say something about it the next time we open the game. She could tell us that it was all intentional, she isn't hurt at all and everything is alright.

**Comment by kaido1224** [comment]
Nah.

**Comment by VirginiaRocks** [comment]
When that happened to me I was really scared because I thought that something infected her (and yes, I run away from my computer for like... 4 hours)
