### ISSUE TITLE
0.9.1 graduation speech typo

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#3892]
![image](https://user-images.githubusercontent.com/37001133/53692134-89cf6e80-3d58-11e9-8b88-a0649fb42862.png)
Yup, found a typo

**Comment by MisterSimple** [comment]
Hey, nice find. Typos should go in #3876, though.

**Comment by jmwall24** [comment]
closing as this has been added to #3876
