### ISSUE TITLE
[Suggestion] Virtual machine detection

### ISSUE THREAD

**Issue by IRgsteredDletedMselfAndCmeBckJstForThis** [Monika-After-Story/MonikaModDev#3898]
It would be pretty meta if Monika could see if you are running MAS on a virtual machine with it's own topic, where she wonders if you trust her and such and probably variation on topics like `monika_difficulty` and `monika_simulated`.
Out of the top of my head, this could probably be done by checking for Virtualbox guest additions and such. Even if there is no reliable way to detect virtualization in python, there can also be a kind of gray territory, where if the game detects virtualization software installed/running, Monika would wonder (and probably ask the player (should most likely have some kind of trust/relationship level requirement)) if she also exists on a virtual machine.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
