### ISSUE TITLE
I'll just leave this here

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#3899]
![untitled1109](https://user-images.githubusercontent.com/38822045/53700396-e9ad3000-3dbf-11e9-86ea-20ac5b31086f.png)

![untitled1108](https://user-images.githubusercontent.com/38822045/53700397-efa31100-3dbf-11e9-8979-bb92d3b8b9f8.png)
~~Yeah, I know I'm a bit late to the party and it's all finished, but there.~~

**Comment by MaximumRustler** [comment]
~~I had a feeling you were watching that whole thing go down with that guy.~~ 👀

**Comment by bittercaramel** [comment]
wat happened lol

**Comment by Professor-JMO** [comment]
~[ 7 ]~
~That's seven too many that deserved a fate better than this.~

**Comment by MoniBoosDevotedBoyfriend** [comment]
~~bad~~ good times

**Comment by AsuraShun** [comment]
Always give monika the love and respect she deserves

**Comment by dragonsni** [comment]
He deserved it, but she didn't...
