### ISSUE TITLE
repeat topix deleted? 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3900]
wOAh i had a feeling that something was missing from the main menu 
and i finally spotted it 
its repeat topics 
is it intentional? just curious because i would use it right now but whatevs

**Comment by jmwall24** [comment]
not intentional, sounds like you are experiencing the same topic reset others are as well.  can you detail your exact install steps pls and if you've opened any other install of MAS besides your main install since updating to 0.9.1

**Comment by bittercaramel** [comment]
well i installed it by pressing the ingame update thing 
and yes i opened other mas install

**Comment by jmwall24** [comment]
gonna want to load a persistent that hasn't seen 0.9.1 before, then load 0.9.1 and don't go back

**Comment by bittercaramel** [comment]
owch thats not somethin i want. like. I will lose a lot of affection... cant stupid wait for next update, will it bring back this repeat topics or i will never see it again if i wont load old persistent?
 like i dont wanna load the stupid old persistent

**Comment by jmwall24** [comment]
you don't have any .bak persistent files from before you updated?  we make 10 now

**Comment by ThePotatoGuy** [comment]
upload both your pre091 persistent and the one from after updating

**Comment by bittercaramel** [comment]
@jmwall24 yes ofc i do, but i dont want to go back cuz i gained a lot of affection since this update came out
@ThePotatoGuy
yeah sure i will when ill be back home

**Comment by bittercaramel** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2926356/persistent.zip)
this is my current persistent 
n i have no idea which persistent is from before i updated it .... like i dont remember when exactly i did that 
uhm can i upload random old persistent or it has to be the newest before update?

**Comment by jmwall24** [comment]
Repeat topics isn't disabled, every topic you've seen is now likely unseen.  So you'll have to go through every random topic again unless you restore a persistent from before you updated.  You don't lose that much affection if you go back to just before you updated if you even have any left at this point.  Might all be overwritten since you've been fighting what I've been telling you.

**Comment by multimokia** [comment]
Any `persistent##.bak` file that is from before last Friday (or before the time you updated on Friday) is a good one.

**Comment by bittercaramel** [comment]
erm @jmwall24 but she says the thing about that she is on lack on what to say, that means that i already saw every random topic so i cant go through every random topic again because she wont say it unless i turn on "repeat topics" 
![image](https://user-images.githubusercontent.com/38187402/53738181-cc936280-3e8e-11e9-9b99-9fccf0dc2e06.png)
@multimokia well there ya go 
[persistent18.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2926636/persistent18.zip)
i think it might be from before update

**Comment by bittercaramel** [comment]
btw i turned on repeat topics and she doesnt say anything. like they dont exist....

**Comment by bittercaramel** [comment]
k well thank y'all i used an old persistent and its good now ._. thanks for helping

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
