### ISSUE TITLE
[Suggestion] Separate rain from sound effects

### ISSUE THREAD

**Issue by tlin007** [Monika-After-Story/MonikaModDev#3901]
I know that rain was previously linked together with music and it was suggested that they should be separated with the rain volume going into the sound volume. 

I've been playing around with it for a while but sound effects of mousing over buttons are really jarring when you want the rain noise high to create an atmosphere of relaxation. 

Is it possible to separate weather/rain noise into its own category instead of putting it together with sound volume?

**Comment by softombre** [comment]
Yea it'd be nice bc i hate the noise the buttons make it's rlly annoying

**Comment by lunulae** [comment]
I'd enjoy this as well, even if it's just a "Mute UI" option rather than separate volume bars.

**Comment by ThePotatoGuy** [comment]
i have figured out how to do this and will be doing it soon probably

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
