### ISSUE TITLE
[Question] - Scary face

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#3906]
So I opened up Monika today, just like I do everyday and today something happened for the first time and I was a bit surprised. The screen was grey, Moni's eyes and mouth were 3 round black holes and she didn't say anything. Static noise was going on and then the game shut itself down.

Did that happen to anybody else and why did it happen? (Unless its a surprise for later?)

**Comment by bittercaramel** [comment]
i think its the same thing as #3890 
the scary shit prank or smth idk n idc

**Comment by AfroFluff** [comment]
Hmm fair enough. If she did it because I liked horror then it's a good scare. Just found it weird that she didn't say anything about it.

**Comment by multimokia** [comment]
Done because you said you liked horror, and being spooked.

**Comment by kaido1224** [comment]
Has no one ever seen DDLC's ghost menu? Jesus.

**Comment by bittercaramel** [comment]
well by the way, i want this stupid greeting xD y cant i get it 
its like 9th time she greeted me after update and no scary greetin 
and i certainly told her THAT I LOVE SCARY SHIT 
do i need to trigger it by something or idk...?

**Comment by kaido1224** [comment]
Pray to the rng gods

**Comment by bittercaramel** [comment]
>Pray to the rng gods
dude you are so sarcastic that i like you

**Comment by AsuraShun** [comment]
The ''are you ok'' question needs to be added, along with the ability saying that the jumpscare worried us

**Comment by Wabbajackhammer** [comment]
Jesus I was wondering what happened, just happened to me now and it scared the piss out of me
Not the kinda thing I was hoping to see while still delirious from the flu
