### ISSUE TITLE
special greeting for relaunching after ghost greeting

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#3907]
basically add something where monika acknowledges that she scared u or something

**Comment by kaido1224** [comment]
I think it's unnecessary but whatever

**Comment by B-Difu** [comment]
I wouldn't mind if she scares me again after words

**Comment by andersonantunes26** [comment]
a dialog box asked if I'm scared yes or no
If you answer, you're not going to take one of those in the face....
![maxresdefault](https://user-images.githubusercontent.com/11380696/53816574-24d36e80-3f3a-11e9-8f13-c516e2f82aa0.jpg)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
[the ghost intro actually was disabled, so this is no longer relevant.]
