### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3908]
in the option of going to play a little, we could say the name of the game and Monika would say something about this game if it was famous

**Comment by Rai99** [comment]
I think this is far too open ended to do realistically. How many famous games are there that aren't basically memes?

**Comment by lunulae** [comment]
This might be a little tricky to keep up-to-date.
Maybe adding more genres, or telling her the name along with what kind of game it is could be a possibility for the future though.

**Comment by MisterSimple** [comment]
Not to mention there's no way to tell if whatever the player is saying is an actual game. Lots of meme potential right there.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
