### ISSUE TITLE
[Typo] Graduation Speech

### ISSUE THREAD

**Issue by Ulvsblakk** [Monika-After-Story/MonikaModDev#3909]
The speech was beautiful, I love the call back when she said "In this world of infinite choices."

When she mentioned the literature club, it's spelt "Literatute".

**Comment by MisterSimple** [comment]
This typo has already been fixed in #3891, though ty for reporting it, regardless. Typos should go in #3876, just so you know for future occurrences.

**Comment by jmwall24** [comment]
closing as already fixed
