### ISSUE TITLE
Disabled "repeat conversation" 

### ISSUE THREAD

**Issue by Fuflyaaa** [Monika-After-Story/MonikaModDev#3910]
I just opened the game and Monika repeated topic about the floating islands, which she told long ago before. Then I noticed, that "repeat conversation" button is missing. I reopened the game and Monika greeted with her "new" hairstyle which she showed me long ago. Also, all I want for Christmas, chess and pong compliments are gone.
Even so, Moni still remembers me, and affection level remains the same. All gifts, clothes and events on our calendar, didn't change.
I'm glad, that she didn't forget anything, but if there is a way to get the lost topics back, I will appreciate that

**Comment by multimokia** [comment]
#3900

**Comment by Fuflyaaa** [comment]
Thank you very much! It helped!
