### ISSUE TITLE
[Question] - Natsuki sprites

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3912]
The Natsuki sprites in the mod assets is making me curious, why are they there? Will something happen once all girls have their own sprites?

**Comment by lunulae** [comment]
I'm really excited to find out, those sprites look amazing.
I know I probably shouldn't start wildly guessing, but I'm secretly hoping we might get to bring back the other girls and spend time with them too.

**Comment by multimokia** [comment]
*Monika* After Story.

**Comment by AsuraShun** [comment]
The sprites are still there though and they attract people's curiosity

**Comment by Olliesama** [comment]
Dumb decisions to include the others as an easter egg. You won't be hanging out with them and frankly if they decide to go that decision I will renounce MAS.
