### ISSUE TITLE
Monika stopped talking

### ISSUE THREAD

**Issue by Yaree-Ka** [Monika-After-Story/MonikaModDev#3914]
It's almost three days and Monika doesn't talk, i tried closing and re-opening the game but she just says that she needs some rest.

PD: Sorry if my english is bad

**Comment by softombre** [comment]
I think you just ran out of random stuff to see, unless you have repeat topics on

**Comment by Yaree-Ka** [comment]
I downloaded the mod less than a month ago

**Comment by softombre** [comment]
Well i once read every topic in like 3 days so yknow

**Comment by multimokia** [comment]
If you have repeat topics disabled, then Monika will just say that she doesn't have anything to say. Though since she's saying she needs some rest... How long do you keep MAS running (without closing) on average?

**Comment by Yaree-Ka** [comment]
Six hours

**Comment by multimokia** [comment]
Hm, sounds like you might just be out of topics then. Is repeat topics enabled?

**Comment by Yaree-Ka** [comment]
No

**Comment by multimokia** [comment]
Yep, out of topics.

**Comment by ThePotatoGuy** [comment]
What version are you running? (Hit escape, go to settings, check bottom right)

**Comment by Yaree-Ka** [comment]
0.9.1

**Comment by ThePotatoGuy** [comment]
can you upload your `persistent` file

**Comment by ThePotatoGuy** [comment]
[closing because lack of response]
