### ISSUE TITLE
Clothes - Swimsuit & Flower

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#3917]
#3174
HELLO EVERYONE, ITS ME AND I'M BACK AGAIN
This time i took my chances  making a swimsuit, I made cuts to fit each arm pose and left an untouched version there too in case it's needed, I also made a flower for her hair.

![capturarwsa](https://user-images.githubusercontent.com/47725743/53846884-6b05ed80-3f8d-11e9-99a0-3f462fa30806.PNG)

![2](https://user-images.githubusercontent.com/47725743/53846654-8e7c6880-3f8c-11e9-8e80-a88b25e2e7b2.PNG)

![1](https://user-images.githubusercontent.com/47725743/53846648-8a504b00-3f8c-11e9-80d0-8c7cebdd58a6.PNG)

Here are the files: https://drive.google.com/open?id=1YzUvjcNJLZ2SuBz53fPHHDb89gOoKedm

The only note i have to make is, to take the screenshots i copy pasted her front hair strands over the swimsuit, just so it looks nice. But it has no cuts for the hair tho.
Oh and here is the inspiration for it: http://d2a2wjuuf1c30f.cloudfront.net/product_photos/41858271/MO4D_()MYO_7BQ_7DTE_S1OG330_original.png

Please let me know if there are any mistakes!! i'll be home most of the day tomorrow so I'll be able to fix it quickly.

edit: face and hair removed from the file as requested!

**Comment by Rai99** [comment]
Not exactly the kind of swimsuit I'd expect Monika to have, but still, it looks good.

**Comment by Rai99** [comment]
I think the hair and face are supposed to be made separate from the sprites, so you might need to remove the hair and face in the files.

**Comment by Orcaramelo** [comment]
> Not exactly the kind of swimsuit I'd expect Monika to have, but still, it looks good.

At first I was gonna do that one monika was wearing in that beach illustrarion that got popular (with all 4 girls), but when I made this hair I thought it looked like a mermaid's one, so I found a mermaid looking swimsuit to 'complete' the look

**Comment by Orcaramelo** [comment]
> I think the hair and face are supposed to be made separate from the sprites, so you might need to remove the hair and face in the files.

oki doki, done! Anything else that I gotta fix?

**Comment by Rai99** [comment]
I'm not sure if this part is completely necessary, but I think you might also have to separate the flower into its own accessory so it doesn't conflict with others such as the vday rose. 

You're the artist and it already looks good, but I would have imagined Monika wearing a more common, conventional swimsuit. 

Other than that, I think it's all good.

**Comment by Orcaramelo** [comment]
> I'm not sure if this part is completely necessary, but I think you might also have to separate the flower into its own accessory so it doesn't conflict with others such as the vday rose.
> 
> You're the artist and it already looks good, but I would have imagined Monika wearing a more common, conventional swimsuit.
> 
> Other than that, I think it's all good.

Oh, do you mean a separate issue? Never thought about that, thank you!!

**Comment by Rai99** [comment]
I meant separate the flowers to be on their own instead of tying them to the swimsuit sprites. I think that would still fit under this issue.

**Comment by Chrissenpai** [comment]
This has my seal of approvement

**Comment by Andrenika** [comment]
How can I add it? Is it possible?

**Comment by VirginiaRocks** [comment]
Really good!! I especially like the flower!

**Comment by ThePotatoGuy** [comment]
first glance these look good. Because of large number of outfits needing review, going to make this low priority for now. this will be reviewed later.

**Comment by ThePotatoGuy** [comment]
@Orcaramelo what name would you like to be credited when I add these to the spritepacks. This name will be used for the spritepack name and acs ID

**Comment by AsuraShun** [comment]
Love it already

**Comment by Rai99** [comment]
Are all these outfits going to have quips upon mouseover or selection like the current outfits?

**Comment by ThePotatoGuy** [comment]
ofc, thats built into the json sprite framework

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
