### ISSUE TITLE
Bring back the default weather when entering the game

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3918]
We already got past winter and it still is showing winter as starting default weather, tweak it back, please.
Also, you should divide day weathers and night weathers so it will become normal and darkened respectively in completely different animations.

**Comment by jmwall24** [comment]
Past winter? We've been through this before.  Winter is an actual season with start and end dates.  There's still a few more weeks of winter yet.

**Comment by Rai99** [comment]
#3217, #3252 

Season changes should be marked on the calendar.

**Comment by ThePotatoGuy** [comment]
Still snowing where I live.

The only weather that doesn't have a night version is rain.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
