### ISSUE TITLE
Add shading to base sprites

### ISSUE THREAD

**Issue by Rai99** [Monika-After-Story/MonikaModDev#3919]
With more revealing outfits such as bikini swimsuits such as #3917, I think the area just under the boobs might look a bit too much of a flat color. 

I would imagine that Monika's chest would at least warrant some shadows underneath them, so I was thinking why not add shadows onto the base sprite in case they get to be seen with some outfits ~~and so Monika's chest doesn't look unnaturally flat~~.

**Comment by Professor-JMO** [comment]
[ Current Project alongside `Summer Bikini`. ]

**Comment by kkrosie123** [comment]
[Closing as completed.]
