### ISSUE TITLE
[Suggestion] - pin board, more games, custom events

### ISSUE THREAD

**Issue by Astixx** [Monika-After-Story/MonikaModDev#3921]
Okay, so I have a serval ideas for MAS.
1. Pin board
Create a pin board up or down to the calendar. In this pin board, you will be able to pin a photos from your computer and describe what the photo is about to Monika.
2. More Games
Maybe some card games? Like Macao, or solitaire (With Monika help). These are my favourite card games so I hope It'll get added.
3. Custom Events
I'm talking about the calendar, Creating custom events...
- You selecting a right topic.
- Then you selecting a date.
- You have an ability to type something on keyboard.
- Here you go, In the day when this event will happen, Monika will remind about it. + Some extra dialogue.

I hope you like it ^.^
Sorry for bad English btw...

**Comment by multimokia** [comment]
Courtesy of #3770:
>Room decoration: #312, #800, #845, #908, #1336, #1793, #1891, #1933, #2027, #2176, #2220, #2496, #2769, #2811, #3182, #3305

More games can be found a bit with #3480, (there's more)

Custom Events: #3553, and courtesy of #3832:
>#1660, #1669, #2047, #2804, #3135, #3553, #3639,
>
>The ability to have Monika know your regular schedule has been brought up before and is currently a low priority.

**Comment by Rai99** [comment]
Games: #829, #992, #1072, #1081, #1629, #1877, #1890, #2424, #2486, #2759, #2811, #2934, ~~#3480,~~ #3561,

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
