### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#3922]
I saw a video of Just Yuri mod, and there are animations of Yuri actually hugging you (screen).
Is it possible for Monika to do the same or better?

PS:I'm new here, not a dev or something, just signed up for this question/request.sorry

**Comment by Rai99** [comment]
It probably would be possible, but we would need artwork for that. In the future, I think we might flesh out holding/hugging, but for the time being, I think there are other things to work on. 

There's already the current holding topic, but yeah, it'll probably be improved down the line. 

I'll mark this as suggestion to improve hugging/holding.

**Comment by NickAB1** [comment]
If I'm not mistaken #3693 has lead to at least some people working out the code for this sort of thing. I even remember some dialogue somebody had posted in the discord.

**Comment by Rai99** [comment]
I'm pretty sure #3693 doesn't have any special code that's not already found elsewhere in MAS. It looks to me like just some dialogue put together until better hugging becomes a thing with better sprites and all. 

I'm pretty sure that's also just a PR in waiting and not much extra is going to happen with it any time soon. 

> I even remember some dialogue somebody had posted in the discord.

That's interesting. I don't remember seeing or hearing about that on the discord. Do you remember what you saw there? Maybe that'll answer some questions.

**Comment by NickAB1** [comment]
Understood. Too bad, was looking forward to it.

Also, it was a while back, I'd have to look into it. If I remember right it was in the submod section so it might have been independent from this issue.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
