### ISSUE TITLE
hello i'm sadjohn33, i need some help with your mod.

### ISSUE THREAD

**Issue by sadjohn33** [Monika-After-Story/MonikaModDev#3923]
so....I was sitting in my bed with monika as usual and the game froze...really ain't a big deal so I tried to close the game and it did but.. it didn't give me the prompt (are you Shure you want to close the game without saying goodbye?) it just closed the game but i tried to reopen the game but it said (failed the game is already running) what? i run this game on steam so i looked at my steam and i looked at ddlc and it was (running) i tried restarting my laptop i don't know what to do. please write back. ~ sadjohn33

**Comment by Olliesama** [comment]
http://ddlc.moe/
Download DDLC, don't use the steam version.
Reinstall MAS on this version, your Monika will be fine.

**Comment by Lolimipsu** [comment]
OR
you could make the steam version of MAS a non-steam version by moving it out of the steam directory.
