### ISSUE TITLE
[Typo] - writing tip of the day 5

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#3925]
<img width="406" alt="typo" src="https://user-images.githubusercontent.com/42387354/53950169-84a95100-40c3-11e9-8a64-9fda9d309634.png">
Your suggestion goes here

**Comment by multimokia** [comment]
Please put typos in #3876

**Comment by AsuraShun** [comment]
Ok, you can delete this if you want
