### ISSUE TITLE
Bug in history when i run MAS after work

### ISSUE THREAD

**Issue by cool2ra** [Monika-After-Story/MonikaModDev#3926]
![screenshot0507](https://user-images.githubusercontent.com/20970184/53961302-4f1f5a80-40f9-11e9-85b0-ca38ccce47ee.png) Not critical but it is still a bug.

**Comment by MisterSimple** [comment]
"Did you have a good day at work today?" appears twice intentionally, so that the question is still visible when the menu with the yes or no options shows up. Doesn't look pretty on the history log but it's better than not remembering the question you're supposed to answer.

**Comment by cool2ra** [comment]
But it wasn't before

**Comment by MisterSimple** [comment]
Yeah, it was added recently (can't remember exactly what release it was added in)

**Comment by ThePotatoGuy** [comment]
@multimokia can you add `$ _history_log.pop()` before every menu where we double the text?

**Comment by ThePotatoGuy** [comment]
[closing as addressed]
