### ISSUE TITLE
[Enhancement] - Expression inconsistency

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#3930]
In the monika_kiss_tease topic, after the pauses, Monika burst into laugh. And I think that the face she's making at that moment is not the one that she should be making.
Here's the original face:
![capture1](https://user-images.githubusercontent.com/38837456/54022084-f8b22a80-4191-11e9-90dc-dc6938cbc82e.PNG)
And I think it would be better if she'd make this face instead:
![capture2](https://user-images.githubusercontent.com/38837456/54022115-0ebfeb00-4192-11e9-888b-f171eaf80c8b.PNG)
Which then would be followed by the this face (it's the original):
![capture3](https://user-images.githubusercontent.com/38837456/54022183-34e58b00-4192-11e9-9b6e-7b9e39c93ac1.PNG)

**Comment by multimokia** [comment]
I don't see what's wrong with it, it's a teasing laugh, hence the furrowed brows and smug eyes.

**Comment by Thimeo** [comment]
If this is suppose to be some kind of evil laugh, then something like "ehehe" with the mouth closed would be more appropriate. "Ahaha" seems more like the kind of laugh you do when you have a happy face and your mouth open. What do you think?

**Comment by multimokia** [comment]
I've seen people do a similar laugh with a similar expression, it's not all that uncommon. Ehehe is a different context entirely, one that I don't exactly think fits as well as Ahaha. I personally think this expression is fine.

**Comment by Thimeo** [comment]
Fair enough, you probably know better than me.
