### ISSUE TITLE
Extra menu

### ISSUE THREAD

**Issue by andersonantunes26** [Monika-After-Story/MonikaModDev#3931]
it would be cool if he showed the whole body monika. what do you think?
![tumblr_p2wij1bpll1udi70ko1_1280](https://user-images.githubusercontent.com/11380696/54031730-f34ee300-4185-11e9-9776-a40a75e08266.jpg)

**Comment by bittercaramel** [comment]
it would be cool if it showed her panties
wait where is the art for that?

**Comment by CloakedGhost** [comment]
It's supposed to be like you're sitting in front of her. Would be a little weird if you were sitting on the floor.

**Comment by NickAB1** [comment]
Problem with this is that it would need to adopt her other clothing. So this one picture would have, what, four variants? That's four arts, drawn by artists who would need to spend their time on this. Personally, I think our efforts would be better spent working on our other high priority goals than a simple different POV. Not being mean, just my opinion :)

**Comment by kaido1224** [comment]
Pass

**Comment by bittercaramel** [comment]
> It's supposed to look like you're sitting in front of her. Would be a little weird if you were sitting on the floor.

y , sitting on the floor is cool

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
