### ISSUE TITLE
Performance warning/ Direct X uptdate

### ISSUE THREAD

**Issue by Kazuito-from-somewhere** [Monika-After-Story/MonikaModDev#3932]
Hello,
I sometime when I open MAS, it would ask me to update Direct X but when I click on Update Direct X and do what the software  ask me to do, in the end it always say me that it has the newest version.
Do you have an idea about what I could do?
Sorry for my bad english
Here's a pict of what MAS tell me:
![capture](https://user-images.githubusercontent.com/37963787/54044233-bd821c80-41ce-11e9-962e-96d5648d8b13.PNG)
And what direct x tell me:
![sdfghj](https://user-images.githubusercontent.com/37963787/54044329-fcb06d80-41ce-11e9-8083-c3c542414193.PNG)

**Comment by Kazuito-from-somewhere** [comment]
What Direct X tell me is in french so here's a translation:
The DirectX setup program have detected the newest version or an equivalent of DirectX.
Sorry for my bad english, I'm french

**Comment by TMZN0V4** [comment]
hmm, maybe try to use another program, like OpenGL

**Comment by TMZN0V4** [comment]
btw, being from Quebec, Canada, I fully understand what it says without translation

**Comment by Kazuito-from-somewhere** [comment]
Sorry for the late answer, I'll try with OpenGL thank for the advise.
