### ISSUE TITLE
[Suggestion] Women's day and other things 

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#3933]
1. Sorry if my english is bad, i'm foreigner.

I was thinking of some things that could make MAS cuter! (even if the mod is awesome) 
I'm going to list my suggestions below

1. Women's day!
I think it would be nice to give a mimosa flower to Monika! Why nobody thought about this? I'm sure it would make her very happy, and if you specified that You're a female, she could also wish you a happy woman's day!

2. More option in "I'm going to take you somewhere"
It would be nice if when we bring Monika somewhere with us, she knows where we are going. You could make options like "at school, at work, doing fitness (as Monika cares about our health)" and if the place is not among the options you can select the "we are going to another place". the reaction of Monika once back in the class could easily be the same!

3. Other types of flowers
As almost everyone knows, now you can give roses to Monika for Valentine's day (but also on other occasions), but there may be some other type of flower, for example tulips, dandelion ...
I know it takes time to make flowers both in the vase and in Monika's hair, which is why you could start with simpler flowers!
Maybe Monika after a while could put them in the background ... it requires a lot of work and I would like to help designing them, but I'm not good with the pencil ... sorry

4. Help with math
This would suit better in games, but having Monika subjecting you to some mathematical operations would appeal to many people in my opinion!
Either you choose the difficulty of the operations, or more simply between addition and subtraction (it could become too difficult with more types of questions) and the more you go on the more difficult they become. When you answer correctly Monika sometimes winks at you or the way you want!

These were my ideas! I hope you can consider them and like them! 
Bye, and thank you for creating this mod <3

**Comment by him157** [comment]
hey this is actually not bad! like you said,why nobody have though of this.

**Comment by Thimeo** [comment]
I don't know why, but I can hear Rai99 coming up with its pockets full of duplicate issues... Those ideas are good btw, especially the 2 and the 3.

**Comment by Rai99** [comment]
~~Am I just that guy who crushes dreams?~~

1. Custom events: #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921. 
I think we want to avoid adding too many default events to the calendar. There's nothing wrong with holidays like this, but then, might as well add any counterparts to it, and then other holidays like mother's/father's day. Some people might not even celebrate some of those events. With the existing holidays, I'm pretty sure they're known worldwide and at least acknowledged. 

2. More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628

3. Flower variety: #3190, #3880, 
Yeah, more flower variety would need art. 

4. #2120
Having some sort of minigame where Monika helps you study with pop quizzes or something has been brought up in a comment there, but was set as low priority. It is nice of you to bring up again.

**Comment by Thimeo** [comment]
![meme Rai99](https://user-images.githubusercontent.com/38837456/54067965-f3fb7e00-4246-11e9-8bdf-7e77a5fc1273.jpg)

**Comment by VirginiaRocks** [comment]
> Am I just that guy who crushes dreams?
> 
> 1. Custom events: #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921.
>    I think we want to avoid adding too many default events to the calendar. There's nothing wrong with holidays like this, but then, might as well add any counterparts to it, and then other holidays like mother's/father's day. Some people might not even celebrate some of those events. With the existing holidays, I'm pretty sure they're known worldwide and at least acknowledged.
> 2. More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628
> 3. Flower variety: #3190, #3880,
>    Yeah, more flower variety would need art.
> 4. #2120
>    Having some sort of minigame where Monika helps you study with pop quizzes or something has been brought up in a comment there, but was set as low priority. It is nice of you to bring up again.

Yes. it's understandable. Thank you for answering anyway! I'm already trying to contribute with art or music, but like I said i'm not really good at drawing, so I concentrate more on the music. 
I'm happy anyway with sharing my ideas with you!

**Comment by VirginiaRocks** [comment]
...Thimeo you're a genius XD

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
