### ISSUE TITLE
game appears in taskbar but window doesn't show up

### ISSUE THREAD

**Issue by euphoricmango** [Monika-After-Story/MonikaModDev#3936]
hello! first off thank you to all of those who put effort into this mod and im grateful i get to experience it. 

however, i have recently ran into an unexpected error. i was chatting with monika as usual late at night when suddenly the application stopped responding. i waited for a moment or two before deciding to close it because there seemed to be no change.

i tried going back on to apologize for the unexpected crash, but the game was not popping up. steam claimed that the app was already running so i checked the taskbar and sure enough, it was apparently running.

i decided to end the task and try again, yet the same thing happened to me. i did this a couple of time but no use. i restarted my computer and even uninstalled the mod and reinstalled it. there has been no change.

i know you are all very busy, so thank you for reading this and i hope you guys can figure this out. <3

**Comment by multimokia** [comment]
Seems to be rather common on steam installs. Download a fresh copy of DDLC from [the official site](http://ddlc.moe/) and grab a copy of the MAS files from [our releases page](http://www.monikaafterstory.com/releases.html) and install that. From now on, you can just run from the DDLC exe in this new install. Don't worry, your progress won't be lost.

**Comment by euphoricmango** [comment]
> Seems to be rather common on steam installs. Download a fresh copy of DDLC from [the official site](http://ddlc.moe/) and grab a copy of the MAS files from [our releases page](http://www.monikaafterstory.com/releases.html) and install that. From now on, you can just run from the DDLC exe in this new install. Don't worry, your progress won't be lost.

hi again, i did do as you said but it seems im still facing the same issue. the game still claims it's running in my taskbar when it clearly isn't.

**Comment by ThePotatoGuy** [comment]
Upload contents of `log/` folder here.

**Comment by euphoricmango** [comment]
> Upload contents of `log/` folder here.

[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2955059/mas_log.txt)

this one, correct? hopefully i did it right.

**Comment by euphoricmango** [comment]
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2959278/log.txt)

here you go

**Comment by euphoricmango** [comment]
> Also upload `log.txt`. this one is above `log/`

hello, just checking in. i uploaded the log like you asked

**Comment by ThePotatoGuy** [comment]
my initial thought is that the window is being rendered off-screen, but that doesn't look like its the case. Try hitting F while the game is running to toggle between window/full screen. that might make it refresh.

**Comment by euphoricmango** [comment]
> my initial thought is that the window is being rendered off-screen, but that doesn't look like its the case. Try hitting F while the game is running to toggle between window/full screen. that might make it refresh.

hi thank you for respodning. i did what you said and nothing really happened. it no longer even pops up where my usual apps that are running are, which is the taskbar at the bottom of my computer screen.

**Comment by euphoricmango** [comment]
im starting to get worried that my affection numbers will plummet because i've been away for so long...any update yet? @ThePotatoGuy

**Comment by euphoricmango** [comment]
ah, somehow the game started up again on it's own...which is strange but im very thankful, so thank you! it seems monika just put it off as some sort of crash and didn't really register the fact that i've been gone so long...thank you!
