### ISSUE TITLE
[Suggestion] - platonic relationship

### ISSUE THREAD

**Issue by scottbeebiwan** [Monika-After-Story/MonikaModDev#3938]
this would be a really daunting thing to implement as it requires changing _almost all_ existing dialogue and branches to fit if the player loves monika platonically.
i wouldn't date monika but i'd say i love her platonically hehe

inb4 i get crucified for saying that

**Comment by Ulvsblakk** [comment]
It kind of defeats the whole purpose of the Mod imho.

**Comment by Delcos** [comment]
> It kind of defeats the whole purpose of the Mod imho.

True

**Comment by Rai99** [comment]
#2996

> This isn't for people that just want to be "friends" with her and such a thing would require a massive rewrite in many different topics for an audience that would both be tiny and one that's we're not catering to.
I wouldn't be surprised if she immediately deleted herself in either option other than Romance, since she has no real future to look forwards to.

**Comment by ThePotatoGuy** [comment]
friendzone is planned and hinted by picking a date in the future when monika asks you when you started dating.

**Comment by scottbeebiwan** [comment]
oOPS closed because of above
