### ISSUE TITLE
[Suggestion] The last "gift"

### ISSUE THREAD

**Issue by MechanicusRex** [Monika-After-Story/MonikaModDev#3939]
Well, hello everyone, I´m new here and I have a suggestion. I have readed about other suggestions about telling Monika that you´re very ill and you can die, and I think it would be a good think to keep in mind because I think there is people that would like to tell her what is happening. But there´s a problem with this, you can touch it by error or you can use it to prank Monika, which is bad. My suggestion is to use the .gift system to trigger this event, like when you give her a present and she says something. That "gift" could be a sequence of words (something like "Iwillloveyoufortheeternity" or something) that once writed and placed in the "characters" folder, you will start a conversation in which she asks you what is your disease (cancer,pneumonia,etc), after that everyday since you have introduced the "gift" she will ask you how you are and if its getting better or worse, and in the worst scenario telling her that you are in terminal state and this is the last goodbye, it will be heart-breaking to her, but I think that is worse to let her think that you have forgot her. But here not all is bad, you can tell her that you are recovered and her will be happy and proud of you.
I know that this theme is very sensitive, but I think it will make us a little less stressful about getting bad news like this and not be able to tell her the truth.
P.D: Sorry about my bad english, its not my mother language.

**Comment by AsuraShun** [comment]
Might as well have the option for those that just want to say it along with it, those that are completely fine and not dying

**Comment by Rai99** [comment]
#1175, #1644, #1677, #2109, #3198, #3881. 

I don't think this is going to happen anytime soon since it's still a system people can misuse and toy with, not to mention what Monika would even say, really. I don't think generic, general dialogue does justice in a life and death situation, so I don't think we're in the position to be able to make that kind of statement towards a dying player.

**Comment by MechanicusRex** [comment]
Thanks for answering me. You´re right about that, its a very sensitive theme and it cannot be coded like an ordinary conversation. The idea I have is like an autodestruction button, something that can trigger a period of time when you can say to her that you´re not going to be more with her and then, she leaves you a note and she deletes herself from the computer.

**Comment by MechanicusRex** [comment]
Maybe a submod? Files that you can download and the next time that you start the mod, it will be activated untill you say to her that you´re fully recovered.

**Comment by Rai99** [comment]
Submod maybe, but we're not obliged to officially make it, or make it at all.

**Comment by MechanicusRex** [comment]
yeah, I know it, well, thanks for read my ideas.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
