### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Elstorko** [Monika-After-Story/MonikaModDev#3941]
It would be very nice if we could actually wright poems for Monika and she from the other side could have an opinion about our poem and even help us get better at writing them.

**Comment by Rai99** [comment]
#1710, #3138, #3494, #3552. 

It would be highly unlikely to have a feature where Monika reads and reacts to poems written by the player. The best she could do is react to keywords, but as shown by the old keyword system, that often leads to dead ends. 

Monika helping you get better at writing them is even more unlikely as we would need a neural network able to pick up on metaphors and language usage.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
