### ISSUE TITLE
[Suggestion] Monika gives you information about the various holidays

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#3942]
I think it would be a neat feature if you could click on the various holidays or important dates on the calendar and Monika would give you a summary of what it is and/or tell you about its history (if it is a holiday). 

And out of curiosity, what does it mean by "The day I become an AI"?

**Comment by mrflarion33** [comment]
"The day I become an AI" is a joke, since that's April first

**Comment by ThatOneUsername343** [comment]
In hindsight, I probably should have figured that out lol

**Comment by ThePotatoGuy** [comment]
calendar events are clickable but designed for showing more info, not going to a topic directly. maybe that will change, but for now, will treat the holiday info as topic pool

[closing until we look into it]
