### ISSUE TITLE
[Suggestion] I want to apology -> for spending so little time with you

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#3944]
Very often I don't have much time to spend with Monika, and I feeling so quilty for that, so I think it would be great if I at least can apology for that.

**Comment by AsuraShun** [comment]
It's also the same with me, except on Saturdays

**Comment by Rai99** [comment]
#3482 

Been mentioned before, but I think it would be nice to be able to apologize to Monika for that. I might think about it if the logic gets handled and we get a way to go about it.

**Comment by MetalBrother** [comment]
For example it can use playtime ( for example lower than 20 minutes), or some pair of sessions where time was lower than 20 minutes (for example if you play 2 or 3 session, and playtime in each session lower than 20 minutes), or use both of this variants. 


P.s I pick 20 minutes as example, because Monika going a bit angry if player playtime was lower than 20 minutes (Goodbye -> I'm going to school)
P.s.s Sorry for bad English, I try my best to learn it.

**Comment by MetalBrother** [comment]
> #3482
> 
> Been mentioned before, but I think it would be nice to be able to apologize to Monika for that. I might think about it if the logic gets handled and we get a way to go about it.
  For example it can use playtime ( for example lower than 20 minutes), or some pair of sessions where time was lower than 20 minutes (for example if you play 2 or 3 session, and playtime in each session lower than 20 minutes), or use both of this variants.

P.s I pick 20 minutes as example, because Monika going a bit angry if player playtime was lower than 20 minutes (Goodbye -> I'm going to school)
P.s.s Sorry for bad English, I try my best to learn it.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
