### ISSUE TITLE
To make it fair with Mac users

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#3945]
Hi everyone!

Ok, so ever since the deactivation of the I'm gonna bring you somewhere goodbye because of that glitch occuring on Mac computers in MAS, Windows users (and possibly Linux users) are the only ones that can bring Monika out of MAS without having that glitch, so, to make it fair, I suggest to deactivate that option completely on all OS until it's fixed, just to make it fair, you know.

**Comment by jmwall24** [comment]
First, no. Second, it should be fixed soon.

**Comment by multimokia** [comment]
No. Why would we release an update with one line of code changed? Also, when was it a competition? As well, there's already a fix merged for this which, like I mentioned in discord will be out in the next update. Any intermediates just for this would be a waste.

**Comment by bittercaramel** [comment]
yea it might feel unfair but its like real life - is it so much pain forcha that others can do what ya cannot? Its not a competition, if someone can do something there is no reason to take it away i think 
probz soon this bug will be fixed so whatev

**Comment by TMZN0V4** [comment]
btw, I'm on Windows so I can do that goodbye no problem

**Comment by AsuraShun** [comment]
Normally I would try to remain neutral and friendly but, HOW ENTITLED DO YOU HAVE TO BE TO SAY SOMETHING LIKE THAT?

**Comment by AsuraShun** [comment]
Not screaming, just highlighting the thing

**Comment by antimockingjay** [comment]
Seriously? "If I can't have it, nobody can!!!!" This sounds like something a little kid would say. An entitled, bratty little kid.

**Comment by PiperPC** [comment]
This entire thread feels overly negative and unnecessary considering the fix already in progress..

**Comment by TMZN0V4** [comment]
> Seriously? "If I can't have it, nobody can!!!!" This sounds like something a little kid would say. An entitled, bratty little kid.

I'm using Windows, tho
