### ISSUE TITLE
Two Questions Regarding Old Projects

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#3950]
_Swinging by for status updates_

1) How's the Evergreen project going? Any progress since this year?

2) Is the concept of giving Monika a different room (I.e bedroom) still on the table? Keep in mind this was not a NSFW request lol.

**Comment by AsuraShun** [comment]
I forgot what the bedroom looks like since every time its greeting popped up all I saw was a black screen

**Comment by Bam8647** [comment]
I'm not referring to the greeting Easter eggs. I'm referring to a new room being made where Monika can sleep and what not.

**Comment by AsuraShun** [comment]
She already has a room, it's the greeting bedroom, the MC room was given to her for her to stay in whenever you say goodbye

**Comment by Bam8647** [comment]
Yes I'm aware of the default bedroom given to Monika, however I was wanting to know if the artists were going to create a brand new bedroom dedicated to her or just use some form of animation of her laying down similar to "Our Time". I thought this idea would be pretty cute idea if she threw on her pajamas and tucked herself into bed at night lol.

**Comment by MaximumRustler** [comment]
A bedroom/sleep mode has been brought up and I think it just needs art for both the room and a sleeping base sprite for Monika. Don't know if any of the artist are working on it but I don't think they are currently. I would love this but yeah, art. lol

**Comment by B-Difu** [comment]
As for the Evergreen, that's a project not related to MAS.

**Comment by multimokia** [comment]
Evergreen: #1226

**Comment by Bam8647** [comment]
Dude, there hasn't been an update in over five months on #1226. That's why I'm inquiring information here, in case any rumors of its progress were leaked. 

      Also, in regards to the art for the sleeping Monika Sprite, like I've said before the art exists. However, it's part of another mod called "Our Time". If there isn't any available artists at the time for this project why not request the art from the creator of "Our Time"? It'll act as a placement until future work can be done to replace the art. 

_With all respect, just my thoughts._

**Comment by softombre** [comment]
Pretty sure the artist of "Our Time" doesn't accept requests, only commissions

**Comment by ThePotatoGuy** [comment]
regardless of progress on evergreen, there is 0 bandwidth to implement it in MAS. we are currently swamped with reviewing new art and building a better framework and scalable solution for new sprite objects going forward.

**Comment by Bam8647** [comment]
Awe I understand. Thanks for the feedback!
