### ISSUE TITLE
Leaning Pose Hair Down Remake

### ISSUE THREAD

**Issue by MisakiCRT** [Monika-After-Story/MonikaModDev#3951]
I know the leaning pose is being remade and all, but I wanted to try my skill a bit and remake the Down-Hair's back shading since it just looked a bit way too simple. Take this as an example of what I could do. It's very messy for now, and kinda rushed, but I hope it looks good so far. I just did a part of the back hair though. If you wish for the full hair just reply or contact me.
![hair-leaning-def-down-front](https://user-images.githubusercontent.com/48454513/54152475-fbd54100-4445-11e9-823f-36379537fc5a.png)
![hair-leaning-def-down-front-n](https://user-images.githubusercontent.com/48454513/54152477-fd066e00-4445-11e9-86ef-d1871657c705.png)

**Comment by multimokia** [comment]
#3788 has another set of hair down hair which we're likely going to use.

**Comment by ThePotatoGuy** [comment]
yeah, we're going to use the other one or keep what we currently have. this does not have any major improvements compared to the current set.
