### ISSUE TITLE
I want to send you some topics

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#3952]
I did with the rempy program some topics that I think will fit in with Monika's way of talking and general knowledge.
If I'm not mistaken I can send you with an option on github, but I don't know how to do it ... could you please explain it to me?
The dialogues are not very long because it was difficult to know what Monika would have said in these kinds of topics I based myself on the tips of the wiki page to contribute, but maybe you can see them again and correct where even the spelling could be wrong, or in general about all points.
Thank you :)

**Comment by multimokia** [comment]
Hi there!

Always nice to see new contributors. Please give our [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) a read for instructions on how to submit a Pull Request.

Thanks for contributing!
