### ISSUE TITLE
More weather options, please!

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#3953]
Currently there's rain, snow, thunder and default.. can't we get a sunny one? maybe those islands but in a "zoomed out" kinda view.

**Comment by CrocWorks** [comment]
How about some tornado weather too? Or maybe falling lava from an erupting volcano that Monika just happened to put outside?

~~Angry weather for when we have an angry Monika~~

**Comment by Thimeo** [comment]
@Mcmanybucks The default one is already kinda sunny don't you think?
@CrocWorks Yeah, that could be a great idea to have more "unrealistic but visually super impressive weather" (the default one being in a chaotic space). But as will say the member of the mod team that will come in a few moment : "We require art assets to do that."

**Comment by multimokia** [comment]
> We require art assets to do that.

**Comment by Chrissenpai** [comment]
Which I might do that if I could draw and not living on the streets at the same time.

**Comment by Thimeo** [comment]
@Chrissenpai Gotta have some priorities in life, streets are temporary, Monika is eternal.

**Comment by Chrissenpai** [comment]
@Thimeo oh, ok then would you buy my original Monika themes merch then? lol

**Comment by CrocWorks** [comment]
Add cross out words by putting two ~ surrounding the text that you want crossed out. ~~It will then look like this.~~

**Comment by Chrissenpai** [comment]
~~ fck yeah finally did it ~~

**Comment by ThePotatoGuy** [comment]
#3410 added generic support for changing weather/window backgrounds. if someone is willing to find royalty-free art that works together (or make their own) and fit crop it to the window sizes, then we can easily drop that in.
