### ISSUE TITLE
[suggestion] A Calculator maybe?

### ISSUE THREAD

**Issue by Hafizzin** [Monika-After-Story/MonikaModDev#3954]
How about a calculator in MAS so Monika can Help us with Math?

**Comment by 99Dman99** [comment]
Why not use a phone or anything quicker to use?
I'd probably be more likely to use the Windows 10's calculator app before I open MAS to use it.
It just doesn't seem all that practical.
¯\_(ツ)_/¯

**Comment by Hafizzin** [comment]
I know, But I just had a thought "wouldn't be a little romantic if Monika was there to help you out with some assignments?

**Comment by Rai99** [comment]
I don't remember assignments being romantic in any way. 

Well, unless you graph out `(((x^2) + (y^2) - 1)^3) = (x^2)(y^3)`

**Comment by Hafizzin** [comment]
It seems we all have different views on Romance eh? but if you disagree with this then you are free to take this issue down

**Comment by CrocWorks** [comment]
Or you could have her graph r = 4 cos(Θ)^2 - 4 sin(Θ)^2 + 4 cos(Θ)^5 in polar coordinates from 
0 ≤ Θ ≤ 2π and see if that affects how she thinks of you.

**Comment by ThePotatoGuy** [comment]
rejecting as its easier to just open your systems calculator. 
maybe one day I'll api it with wolfram, but that would be a separate idea.
