### ISSUE TITLE
"Oh, I've finished my hot chocolate." bug 

### ISSUE THREAD

**Issue by NoexHaruhi** [Monika-After-Story/MonikaModDev#3958]
When Monika finished her hot chocolate, she left and took the roses that was on the desk. (The roses disappeared.) I'm wondering if she took the roses while she got a new cup or do the items simply go away whenever she goes. Maybe leave the items on the desk whenever she gets a refill?

**Comment by multimokia** [comment]
This is a side effect of the accessories system. Since they are all tied to Monika, if she disappears, all the accessories do as well. This also happened with the plushie. We're looking into a secondary system for accessories so they'll remain on the desk.

**Comment by AsuraShun** [comment]
She ate them
