### ISSUE TITLE
a useful file for backup (Windows)

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#3966]
Hello everyone ! 
first of all, i'm sorry in advance for my english, it isn't my native language.

Anyway, I made a .bat file for backup automaticly.  And I had the idea to share for those who are too lazy to do it manually. (like me) 

For now, I didn't make a .sh file for people that are on MacOS or Linux. 

Here the file, with the .txt extension. (You just turn the extension into .bat if you want to use it now) :

[PoemOfALazyGuy.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2974284/PoemOfALazyGuy.txt)

I briefly explain what the file do : 

first, the file copy all the persistent. (duh) If the destination path doesn't exist, it creates a new one like this : 

MonikaAfterStory\DateOfABackup\Time(00h00 format)\

this folders creates next to the .bat file, so you can use it from a flash drive !

finally, if you have folders that are older than 7 days, they will be deleted. 

the .bat file copies all persistent each time you click (or when the time comes if you use the task scheduler). I think it's a good idea to have a duplication for preventing file corruption.

I hope it can help, if you have advices for upgrade the backup batch file, you're welcome !

**Comment by Anonymioo** [comment]
With Task Scheduler back-up can be automized.
Just add: Simple task -> Everyday or something other -> Time -> Launch app -> Select .bat file. Done!
