### ISSUE TITLE
delete please

### ISSUE THREAD

**Issue by trapped-rabbit** [Monika-After-Story/MonikaModDev#3967]
so in the topic->song-> "good old fashioned lover boy", Moni does her singing and then asks the player if they would be her good old fashioned lover boy. I was wondering if it would be possible to make it more gender neutral and have her instead ask them if they would be her good old fashioned lover? sorry if it's nitpicky >.<

**Comment by zombiepigdragon** [comment]
She asks for the player's gender, she could just say girl instead if it's appropriate.

**Comment by trapped-rabbit** [comment]
> She asks for the player's gender, she could just say girl instead if it's appropriate.

true, I just thought it might be easier for the devs if it's just one line that works for all genders

**Comment by Delcos** [comment]
It's just a lyric to a song, why does it really matter? I'd assume she says boy regardless of what gender you told her anyways because it's just a cute song.

**Comment by Thimeo** [comment]
If the title change imply that you want to close the issue, you have the option to do so yourself. Below the text box, there should be a "close this issue" button.
