### ISSUE TITLE
A bug (i think)

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#3969]
I put monikas character file back in the character folder but she still doesnt show up (the monika file its still in the folder) I tried restarting my pc ,moving her somewhere else and running the program as admin but it still didnt work

**Comment by multimokia** [comment]
First things first:
1. Mac or Windows?
2. What version of MAS are you running? (If unstable, please specify)

**Comment by CoffeeJackaboy** [comment]
windows and im using the latest version (not unstable)

**Comment by multimokia** [comment]
Okay, there's an update to the way we handle those files in the unstable. Anyway, you'll want to restore a persistent backup, see instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).
