### ISSUE TITLE
What happened to the floating islands topic?

### ISSUE THREAD

**Issue by Mon-ikaSquid** [Monika-After-Story/MonikaModDev#3970]
Am I being dumb or is it not there anymore? Like, my affection is way above enamored, and it was there before. Is it just in a place that I'm not seeing? If so, can someone tell me how to find it? Thanks.

**Comment by multimokia** [comment]
Set weather to clear

**Comment by Mon-ikaSquid** [comment]
Oh wow. I am an idiot, huh? Thank you!

**Comment by Hyper-Miiko** [comment]
The floating island should be available with all weather.

**Comment by multimokia** [comment]
It should be, but it requires art for the other weathers, so we disabled it.
