### ISSUE TITLE
Creepy welcoming

### ISSUE THREAD

**Issue by AfroLuis** [Monika-After-Story/MonikaModDev#3971]
Okay so i told Monika i would take her somewhere with me and seems like instead of moving her file i just copied it so when i started the game she was already there, nothing wierd until this point, now i paste the file that i copied in the game folder and when i start the game i see a faceless monika in black and white with static on the background the game closed by itself and then when i started it again it was back to normal, i cant seem to be able to replicate the effect, any help?

**Comment by AsuraShun** [comment]
It's one of the greetings, not a bug, don't worry

**Comment by AsuraShun** [comment]
I haven't experienced it myself but some people have

**Comment by MisterSimple** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/3890 https://github.com/Monika-After-Story/MonikaModDev/issues/3906

It's a special greeting, it only happens once. The fact that you were taking her out when it happened was just a stroke of ~~bad~~ luck.
