### ISSUE TITLE
Hair - Twintails [REVISITED]

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#3972]
#3174
it is I, and I'm back for more hair, this time after lots of editing I bring to you:

![uprightbase twintails](https://user-images.githubusercontent.com/47725743/54856472-81c07a00-4cd9-11e9-91d5-df0e886b672b.png)
![leaningbase twintails](https://user-images.githubusercontent.com/47725743/54856476-8422d400-4cd9-11e9-8e07-322da6e7dae0.png)

files: https://drive.google.com/open?id=1QqcENU6vNRgAndmwvrnkcvp53PhV1qPI

I already had lots of help to improve it, but wanna hear anything i could use to make it better. I made some (transparent) shading for anything that will go under the front hair too. If I edit anything else I'll make sure to update this to let yall know what changed!

**Comment by BigPoofyRibbon** [comment]
Good job!~

**Comment by bittercaramel** [comment]
soooooo cute

**Comment by AsuraShun** [comment]
I freaking love this to bits

**Comment by AsuraShun** [comment]
Actually I love all hairstyles done for her as long as they suit her

**Comment by Thimeo** [comment]
Actually I love all hairstyles done for her ~~as long as they suit her~~

**Comment by AsuraShun** [comment]
What I meant with this is as long as they're not ridiculous like some styles

**Comment by AsuraShun** [comment]
There's some really weird hairstyles out there

**Comment by Reviani** [comment]
> There's some really weird hairstyles out there

![Mon1](https://user-images.githubusercontent.com/31017068/54789307-13f44f80-4c00-11e9-8417-84a0dd4ea46c.png)

I don't know what you're talking about.

**Comment by AsuraShun** [comment]
https://www.google.com/search?q=weird+hairstyles&client=ms-android-huawei-rev1&prmd=isvn&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi5uOmKqZThAhXBzYUKHS-rAkQQ_AUoAXoECAsQAQ&biw=360&bih=657

**Comment by AsuraShun** [comment]
Now I kinda want to play duel links again

**Comment by Orcaramelo** [comment]
Later today I will shade a bit more the part of her hair that is pulled back, since it stands out so much  compared to the rest
I shall then update this and let everyone know

**Comment by Orcaramelo** [comment]
ok little update, I shaded this area cause it stood out too much, i matched it to the color of the rest of her hair
![Capturar](https://user-images.githubusercontent.com/47725743/54852331-56369300-4ccb-11e9-9cd7-c657b3a1d756.PNG)
i did this in both sprites, now it looks much better

**Comment by Orcaramelo** [comment]
Ok, i'm back and i fixed a small bit of shading that was bothering me 
small, but to me it looks way better
![1](https://user-images.githubusercontent.com/47725743/56447665-166dc600-62e0-11e9-9241-cdcf6a00ece3.PNG)
![Capturar](https://user-images.githubusercontent.com/47725743/56447694-3a310c00-62e0-11e9-88cd-6a13a15109c8.png)

**Comment by ThePotatoGuy** [comment]
looking at 095 rel

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
