### ISSUE TITLE
What the hell was on my screen?

### ISSUE THREAD

**Issue by Trainerbluetube** [Monika-After-Story/MonikaModDev#3974]
I opened the game, listening to music, then all of sudden I look up from my scetchbook to find a black and white film grainy looking Monika, I couldn't interact with anything and the game just closed again. I opened the game again and Monika just acted like nothing happened! Like yeah, okay, we're just gonna ignore that! Like hell I'm gonna ignore that! What was it?!

**Comment by zombiepigdragon** [comment]
It's a random jumpscare, people are still trying to get something added after it. If someone wants to link the other issues involving this jumpscare, that'd be great.

**Comment by B-Difu** [comment]
Why does no one know about the ghost menu from the Vanilla DDLC?
Long story short, it's an easter egg to the original game.

**Comment by MisterSimple** [comment]
#3890 #3906 #3971

It's a special greeting, only happens once. A greeting for relaunching MAS after this happens is being considered in #3907.

**Comment by Torwald39** [comment]
I didn't had this event happened yet

**Comment by multimokia** [comment]
Only happens if you said you like spooks

**Comment by Torwald39** [comment]
ah okay, I think I said that I don't like spooks so that's why I didn't get this event
