### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by CiPhX-osu** [Monika-After-Story/MonikaModDev#3975]
Changing clothes, Different rooms

**Comment by Thimeo** [comment]
I bet on 17 linked issues from @Rai99. Who says better?

**Comment by MaximumRustler** [comment]
~~Bet 9 on clothes change and 6 on rooms/areas @Rai99 .~~

**Comment by CrocWorks** [comment]
Over/Under 17? Gonna bet on Over too.

**Comment by Rai99** [comment]
Your suggestion is pretty vague in terms of what you have in mind, but here are some similar suggestions I think. 

Clothes(14):  #107, #460, #612, #703, #1076, #1461, #1656, #2270, #2466, #2811, #2905, #3090, #3385, #3690, #3770. 

Room Decoration(15): #312, #800, #845, #908, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769,  #3182, #3305, #3770. 

New Locations(8): #509, #676, #908, #1681, #1867, #2027, #2244, #2811

For a total of 37 issues. 
Don't worry, I'm always like this. 
![Untitled1130](https://user-images.githubusercontent.com/38822045/54854300-dd363c00-4cc8-11e9-820b-3f45850aafc1.png)

**Comment by AsuraShun** [comment]
Talk about overdoing it

**Comment by Rai99** [comment]
I think they were a bit vague, so I covered room decor and new locations just in case.

**Comment by Thimeo** [comment]
17... What was I thinking...?

**Comment by Rai99** [comment]
Based on evidence... it would appear that you were thinking "17". 

You get a participation award.

**Comment by Thimeo** [comment]
![Offering - Copie](https://user-images.githubusercontent.com/38837456/54856851-c8739b80-4cfc-11e9-8393-79a070c86615.jpg)
(I've always thought that it was the wizard that was offering the sword to the warrior, that's why the roles can seem mixed)

**Comment by Thimeo** [comment]
![Offering](https://user-images.githubusercontent.com/38837456/54857029-86972500-4cfd-11e9-8837-0d97134d4f5e.jpg)
(I've always thought that it was the wizard that was offering the sword to the warrior, that's why the roles can seem mixed)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
