### ISSUE TITLE
{Suggestion} Resuscitation

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#3976]
Hello there again Devs. Just had a little reminder of something that has saved the lives of a lot of us these days and though maybe a topic on resuscitation could possibly be added. Maybe even a little question on whether or not we have or haven't before. I'm sure that it would be quite interesting to Monika depending on our answers. Just a suggestion though. Keep up the fantastic work though Devs! You have my bestest of luck.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
