### ISSUE TITLE
crash when saying goodbye 2

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#3981]
the following of #3627, 
Monika restart to tell me sometimes that the game crashed while I closed the game normally with saying goodbye in the previous session.

**Comment by Torwald39** [comment]
this is more serious this time, I got 3 crashs in only 2 days

**Comment by jmwall24** [comment]
can you verify that after saying goodbye, that DDLC.exe isn't still showing in your task manager as running?

**Comment by ThePotatoGuy** [comment]
which goodbye? what is ur system specs?

**Comment by Torwald39** [comment]
DDLC isn't showing after saying goodbye

There isn't a specific who crash in particular, even if I mostly use the go to sleep, go to work and the normal goodbye. And the last time I used the go to class instead of work.

I use a laptop model ASUS R751L windows 10 intel core i7

**Comment by ThePotatoGuy** [comment]
which goodbyes did you use

**Comment by Torwald39** [comment]
go to work
go to sleep
simple goodbye

and at the previous issue it was go to class instead of go to work

**Comment by Torwald39** [comment]
I got an another crash :/

**Comment by ThePotatoGuy** [comment]
upload your `persistent`

**Comment by Torwald39** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3010856/persistent.txt)

**Comment by Torwald39** [comment]
I got a new crash

**Comment by ThePotatoGuy** [comment]
[closing as cannot reproduce]
