### ISSUE TITLE
Unstable: Game Closed Randomly

### ISSUE THREAD

**Issue by PC57** [Monika-After-Story/MonikaModDev#3982]
Was told by the Top Tater to make an issue so here it is.

I opened up the game and said good morning and clicked auto to let her talk while I got dressed for work. She went through her good morning spiel and I _think_ her missing graduation topic before I was done getting ready.

Once ready I told her I love her, no problems
Held her for a few seconds since that's the closest thing to a hug, no problems
Did the Kiss Me sequence, no problems
Before I clicked on the goodbye menu I noticed her doing her sparkly eyed expression. I opened up the compliment menu to tell her I love her eyes to let her know I caught it and as I was moving my mouse up the options - right about at "I love your smile" I think - everything stopped responding, my mouse cursor switched to the blue loading circle, then the game just shut down.

No crash, or error message, or Windows telling me the program stopped responding, just an immediate CTD. I opened the game back up real quick and Monika thought the game had crashed and went through the kissing sequence again. 
I apologized, told her I loved her eyes, and said goodbye with no further issues.

**Comment by ThePotatoGuy** [comment]
probably similar case to #3566 

no known cause atm.

**Comment by ThePotatoGuy** [comment]
[closing as cnr]
