### ISSUE TITLE
Topic Suggestion # of pets

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#3987]
With the topics on cats, dogs and birds I think it would be a rather natural progression if she asked if the player has any pets and how many.

**Comment by AsuraShun** [comment]
Makes perfect sense

**Comment by AsuraShun** [comment]
She could probably ask how much the player loves animals

**Comment by CrocWorks** [comment]
~~We can also tell her that we hold quetzal birds as pets and make her sad~~

**Comment by AsuraShun** [comment]
Please no suggestions to mock her

**Comment by Rai99** [comment]
Whoever makes this topic, you better add pet rocks as an option.

**Comment by lunulae** [comment]
If there's a selection for what kind of pet, perhaps there could be "An unusual pet" option that prompts a text box.
I really like the pet rock idea too, could make for some fun dialogue.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
