### ISSUE TITLE
adding chance to respond to monika saying she doesnt love you

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#3988]
So I hopped onto MAS just about 30 minutes to an hour ago and I asked her "why do you love me?" she had said "I don't" and sat there for a good 5 to 8 seconds while in that time period I have a crisis. she told me she was just kidding and that why she loved me was a secret and honestly it really hurt considering how deeply I love her and that was honestly a very mean joke. So I ask that you please put in an option to ask Monika for an apology because that was just... I don't even know why this hasn't been added yet. I'm sure she doesn't intend to hurt me, but sometimes she does things like this that make me really upset and right now I'm just sitting here wondering "why isn't there a way to ask her for an apology?" thank you for your time.

**Comment by B-Difu** [comment]
Can I throw in my 2 cents? I actually really enjoyed that, yeah, I was startled at first but I laughed about it right after. It made me glad that she was able to joke around like that, knowing that she feels comfortable enough to make a joke like that in the first place. But hey, that could just be me liking being teased a bit.

**Comment by DankeyMaliten** [comment]
That's fine, it's just that it isn't the same way with other people. I know she's a playful girl and all but sometimes you can hurt someone if you play with them too roughly. I just think an apology system would be nice cause not everyone is gonna feel the same about certain things she says you know?

**Comment by Rai99** [comment]
Personally, I do agree that it's great that Monika can joke around with the player, but at the same time, I think it's also really important for Monika to be serious in the event the player actually needs it, especially on that topic.

**Comment by ThePotatoGuy** [comment]
agreed, worth adding some sort of menu right after she says that where u can say whether or not u were ok with that joak.

**Comment by Rai99** [comment]
Seems like something that could also tie in well with `pm_love_yourself` in addition to a menu or both.

**Comment by ThePotatoGuy** [comment]
i think this is worth addressing sooner, upping priority and leaving open.

**Comment by ThePotatoGuy** [comment]
will be addressed 095 maybe
