### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3989]
When I tell Monika that I'm going to sleep at 5:00, two options appear after her dialogue, but they are illegible, I would send a screenshot, but I forgot to pick it up.

**Comment by multimokia** [comment]
Wait, you can't read it? (Intentional)

**Comment by Alucard149** [comment]
I thought it was a mistake of the game I feel stupid

**Comment by ThePotatoGuy** [comment]
[closinga s not bug]
