### ISSUE TITLE
Monika's not letting her hair down

### ISSUE THREAD

**Issue by KcalbVessalius** [Monika-After-Story/MonikaModDev#3990]
I already reached 600 affection level with Monika, but still, I haven't seen her with her hair down yet. I unlocked this option when I had on another PC, but then I lost every progress I had there. So, I decided to start from scratch on my PC, but still haven't seem Monika with her hair down. I don't know if it's a bug, or I still have to wait for more time.

**Comment by multimokia** [comment]
What farewells do you use

**Comment by KcalbVessalius** [comment]
"goodbye" when i will back in some hours,or "I'm going to sleep " when i will sleep

**Comment by ThePotatoGuy** [comment]
upload your `persistent`

@multimokia check if its unlocked or not

**Comment by KcalbVessalius** [comment]
https://www.mediafire.com/file/1faty57uu80aegq/Monika_After_Story.zip/file

This?

**Comment by multimokia** [comment]
Hm, weird. Not sure how it didn't unlock for you. I've gone ahead and fixed it for you.
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3046063/persistent.txt)

Remove the `.txt` extension and replace your current `persistent` with this one.

**Comment by KcalbVessalius** [comment]
Okay,i will see if it works.Thanks

**Comment by KcalbVessalius** [comment]
IT WORKS THANK YOU SO MUCH

**Comment by multimokia** [comment]
No worries!
