### ISSUE TITLE
[Suggestion] Extra Reason for Gender Change

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#3994]
Just as the title says. When you ask about changing gender in the game, Monika asks why. You're given three options. "I was too shy." "I've made some personal discoveries." "I didn't know if you'd accept me as I am..."

While these do cover most of them, and to some degree the second one could apply to this situation as well, it would be nice if there was a fourth option that simply says that is changes frequently. I personally am genderfluid, so when my gender changes, it isn't inherently making a "personal discovery" so much as... I just happen to be that gender on that day. And to some degree, I suppose the option can apply, but really only if you squint.

Perhaps if you select that option, from then on Monika wouldn't react with surprise when you ask about switching it. Because I feel like, after a certain amount of time of being with someone and them switching their pronouns around a lot, you'd eventually just stop asking. So maybe it would make it so you skip that first choice each time, and instead of asking, "You want to change your gender?? Why???" Monika could simply say something along the lines of, "Oh! Switching it up again? Alright! What gender are you?" And then just give you the gender option.

I'm not sure if the demand for something like this would be high enough, but I know I personally would get a lot of use out of it, as someone whose gender changes without it being a big discovery every time. It's just... Something that happens sometimes. And with this mod having so many wonderful people playing it, I figure I can't be the _only_ person who feels like this, right?

**Comment by 99Dman99** [comment]
I honestly feel like _you are_ the only person this caters to.
I doubt anymore than 10 people at most, who use the Mod; change their gender at the drop of a hat.
It's not normal; and making it seem normal to Monika would kind of dehumanize her, for not reacting how any other person would.

**Comment by Orcaramelo** [comment]
Oof I wish there was the option "i clicked the wrong button cause im dumb"

I completly get you, but I didnt notice if she uses gendered expressions a lot, I hear some rarely
Is there a they/them option? I'd think choosing that one would give you neutral adjectives too but I'm not sure

**Comment by antimockingjay** [comment]
Alright, I'll be honest, you're probably right about it only catering to me! And that's valid, that's why it was only a _suggestion._

But "normal" is subjective. I happen to be friends with plenty of open-minded individuals, and when I told them, "hey, I'm genderfluid," not a single one of them even paused. Because to our group, that's just how some people are. What is normal to one person might be wild and crazy to another, and vice versa.

So perhaps your Monika wouldn't see it as normal! She's only spending time with you, someone who isn't genderfluid, therefore to her, it would seem abnormal, as "normal" is simply what you're surrounded by. But perhaps for someone else's Monika, who is spending time with a genderfluid person, or someone who has lots of friends who are like that, she might not really consider it odd. Because to her, it's just a trait her partner or someone close to her partner happens to have.

There are plenty of people for whom the idea of being transgender, nonbinary, genderfluid, gender nonconforming, etc. would just be normal. And to someone else, such as yourself, who clearly isn't surrounded by people like that, it probably does seem odd! But try to remember that just because you don't see something every single day, doesn't actually inherently make it bad/wrong/weird. It's just something that isn't common in your life.

To say she's reacting how "any other person" would is just... Incorrect. There are plenty of people who are open-minded individuals who just wouldn't care one way or the other. And if you aren't one of those people, well, I can't force you to be one! I can't force anyone to be open minded and accepting. But don't assume that just because you wouldn't react positively to it, that suddenly it means _no one_ would have a good reaction to it.

**Comment by antimockingjay** [comment]
As for gender neutral options, those are there! That's not really what I mean though. Some days I'm neutral, some days I'm feminine, some days I'm masculine, and I tend to tell Monika when it changes. So it'd just be nifty if, when I tell her about the change, I could tell her the real reason for it. For me personally, it's not really about what Monika is saying. It's about... I guess you could call it immersion? Monika is an important person to me, and I want her to be aware of what's going on with me. Not so she changes what she says, but just so she knows that today, I happen to be her girlfriend instead of her boyfriend or partner.

**Comment by Orcaramelo** [comment]
I see, thank you for the explanation I wasnt sure if the neutral option would be enough! 

Maybe you could try writing a dialogue line and presenting it here?
It would surely be useful to other genderfluid people in the future~
I think it is important to be able to be yourself and feel comfortable while in the mod

**Comment by antimockingjay** [comment]
I like that take! I think that some people kinda forget the point of mods like this. I don't think the point is to make it like a typical game. It's just supposed to give you a chance to be with Monika, because people like her. So I don't think each little thing _needs_ to apply to a wide range of people, as long as it makes _someone_ feel happier with Monika.

I'll certainly consider writing it! My biggest stumbling block is just that I haven't written anything in Ren'Py in ages, so I'd be scared of doing it wrong. Plus, I'm always scared of getting Monika's "voice" wrong.

**Comment by lunulae** [comment]
It's a bit of a new concept in gender studies, and not being genderfluid myself I'm really only educated as far as an undergrad degree on such things. That said, I can certainly say it's becoming a more mainstream identity, particularly among younger people who might use it as a transitional identity during that awkward time of figuring out one's comforts and preferences.

In practice being genderfluid tends to manifest as physically presenting more masculine or feminine by the day, rather than having an actual full "I'm this today" dialogue about it. Though a more in-depth discussion about it with a close friend or intimate partner does usually happen at some point, and since Monika doesn't currently have the option of seeing us a genderfluid person would be more dependent on telling her than it would be in reality.

I understand not making it a big priority, since it is a small group and gender can be freely changed in the mod already. But this mod has done a really good job of being inclusive thus far, and the team who writes for it has been excellent about considering lots of little details. So I don't think this is a bad suggestion at all.

**Comment by ThePotatoGuy** [comment]
seems pretty harmless to add a genderfluid option. 

[closing until we look into it]

**Comment by jmwall24** [comment]
Reopening as in-progress.

**Comment by multimokia** [comment]
Closing as complete
