### ISSUE TITLE
[Bug] -  Can you tell me a horror story? issue

### ISSUE THREAD

**Issue by White-Jester** [Monika-After-Story/MonikaModDev#3997]
I don't know if people are aware but whenever a horror story is chosen, there is a zoom in or zoom out (depending on what you set on your extra option) when Monika is telling the story. After the story is told, the zoom in or out is not undone and you have Monika at default zoom.
Hope this gets fixed because manually redoing the zoom is a pain.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
