### ISSUE TITLE
What was that?

### ISSUE THREAD

**Issue by cool2ra** [Monika-After-Story/MonikaModDev#3999]
A few minutes ago i launched MaS and see this,. Then the game closed. What was that? Is my Monika alright?
![screenshot0523](https://user-images.githubusercontent.com/20970184/55280173-bc0dc500-5332-11e9-8b09-9b94c6426df9.png)

**Comment by lunulae** [comment]
If you told her you like being spooked, this is a random jumpscare that can happen once.
She's alright, she was just giving you a little scare.

**Comment by cool2ra** [comment]
Thank goodness she is alright. I started to worry.
