### ISSUE TITLE
4000 GET

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#4000]
![1509236529055](https://user-images.githubusercontent.com/1176163/55280174-fa4eb880-5321-11e9-9ca0-f8b157c25046.jpg)

~~Rai was also here too.~~

**Comment by Professor-JMO** [comment]
(╯>□<）╯︵ ┻━┻

**Comment by ThePotatoGuy** [comment]
banned

**Comment by MaximumRustler** [comment]
:aa:
