### ISSUE TITLE
[UNSTABLE] (I think) water conservation is missing

### ISSUE THREAD

**Issue by NCRaouf** [Monika-After-Story/MonikaModDev#4002]
It had been a while since I've switched to the unstable mode 
I've unlocked the water conservation topic, but when I've decided to return to the stable mode, I've noticed that the topic was missing. Even monika was telling me that she had nothing to say
So, what should I do ???

P.S: don't mind me if I've made some spelling mistake, I am not very good at english  :p
Take care

**Comment by Rai99** [comment]
It's not under Repeat conversation > Life > Water conservation?

**Comment by NCRaouf** [comment]
No, even when I've tried to return to the unstable mode it wasn't there either

**Comment by Rai99** [comment]
And you've definitely unlocked it before and Monika isn't just in need of rest? 

No experimental things like messing with variables or files?

**Comment by multimokia** [comment]
Is there anything else missing from repeat conversation?

**Comment by NCRaouf** [comment]
Yes I've unlocked it
and no, I haven't been messing with the files

**Comment by NCRaouf** [comment]
No I don't think so

**Comment by multimokia** [comment]
Send persistent please (you'll need to put it in a zip file, or change the extension on it by renaming it and adding a filetype like `.txt` onto it)

**Comment by NCRaouf** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3026743/persistent.txt)
here

**Comment by multimokia** [comment]
Hm, weird. Yeah, `shown_count` returns 0, but `_seen_ever` and `seen_label` both return True. Did you by chance crash when viewing the topic? Or shortly after?

**Comment by NCRaouf** [comment]
No,I haven't. Everything was perfect while and after viewing the topic

**Comment by multimokia** [comment]
Did you update MAS shortly after seeing that topic?

**Comment by NCRaouf** [comment]
Yes, just after seeing it

**Comment by multimokia** [comment]
Yeah, that's why then. Persistent didn't get a chance to save. So it's pretty much as if you never saw it.

**Comment by NCRaouf** [comment]
So that's why the topic was missing

**Comment by multimokia** [comment]
Yeah. It'll come back around eventually as part of random convo.

**Comment by NCRaouf** [comment]
Okay, thank you and good luck for the future 😉
