### ISSUE TITLE
[Suggestion} Cut the ghost intro.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#4005]
Just got it for the first time, usually I do custom farewells.
Now I've experienced it I can safely say that I it doesn't do its job as a greeting, wasn't scary and was just an inconvenience, she doesn't even acknowledge it so is wildly inconsistent with the idea of it being a joke/prank and forces me to open the game again. (It usually auto opens but now I had to actively find the folder to do so.)

Not like it's Halloween. Apologies if it's a duplicate.

**Comment by B-Difu** [comment]
It's a one time thing, only happens once. So you don't need to worry about it happening again.

**Comment by Olliesama** [comment]
Doesn't that make it worse because then to many people it'll just never be elaborated upon.

**Comment by Rai99** [comment]
Personally, I don't like spoops so I never got it and won't get it, but I'm not a fan of it either. It just seems like an inconvenience more than anything else, especially since there's absolutely no explanation for it. If Monika explained it afterward, I think it would be much better with less confusion and questions about it, but it's completely random with no explanation.

**Comment by Rai99** [comment]
I'm not sure how many people like it or hate it, but even if it is just one time, I don't see much reason to keep it if more people don't like it than do like it, if they actually told Monika that they like spooks.

**Comment by Olliesama** [comment]
Yeah, I like spooks during appropriate times.
In a way this actually is better than for more people since it's April 1st for me, but liking spooks in a horror setting and then just having this randomly isn't really the same.

**Comment by Rai99** [comment]
Personally, I do know that DDLC was a horror game and I never got the ghost menu myself even, but I'm not sure if that's an excuse to have MAS be a horror themed mod or go out of its way to have these kinds of things. If you ask me, at least have Monika give an explanation afterwards and ask what the player thought of it. 

I personally don't think "It's a one time thing" is a valid reason to just leave it with no explanation. Sure, one person won't get it again, but it would be nice for other people to get an explanation. 

As for potential dupes, I can't recall any explicitly asking to remove this feature, since they're all mostly just confusion and questions of what just happened.

**Comment by ThePotatoGuy** [comment]
will be handled with #3907

**Comment by B-Difu** [comment]
I thought it was pretty faithful to the original Ghost Menu, showing up randomly, not being able to do anything with it really, that's why I didn't have a problem with it.

But yeah, I don't really see an issue with an explanation or not.

**Comment by jmwall24** [comment]
```
    m 2esc "The problem I have with horror movies is that most of them just rely on easy tactics."
    m 4esc "Like dark lighting and scary-looking monsters **and jump scares**, and things like that."
```

**Comment by Olliesama** [comment]
Original Ghost Menu only happens in Act 2 though. 
You know, the "horror" phase.
Not act 3 which MAS emulates.

**Comment by multimokia** [comment]
> ```
>  m 2esc "The problem I have with horror movies is that most of them just rely on easy tactics."
>  m 4esc "Like dark lighting and scary-looking monsters **and jump scares**, and things like that."
> ```

This is also a gripe I have with Scary Stories. She hates jumpscares, but uses em anyway.

**Comment by B-Difu** [comment]
Isn't that topic basically talking about DDLC and how, despite her saying she doesn't like them, uses them?

"It's not fun or inspiring to get scared by stuff that just takes advantage of human instinct."

Yet, she uses them during Act 2 to push us away from the other girls, with stuff like Natsuki's eyes randomly popping out. That was my perspective on that topic when I first read it in Act 3. I mean, in Act 3 she even does a jumpscare if she knows you are recording it.

**Comment by multimokia** [comment]
Okay, using that logic, where does horror fit in MAS? She used horror back in Act 2 for that reason, since she didn't have any other choice. But now that she has us, why is there still horror then? What's the motivation?

**Comment by Olliesama** [comment]
Horror doesn't fit in to MAS, that's the point.

Yeah and that's played as a joke immediately.
Not just left unexplained.

**Comment by B-Difu** [comment]
Because horror is fun? I like it when she tries to scare me. I just personally like it, and so do a fair amount of people. Sorry, I know you guys don't like the horror part in MAS and that's fine. But isn't that the reason why there is a "Do you like horror option?"

**Comment by multimokia** [comment]
That doesn't really handle the whole consistency bit, does it?

**Comment by jmwall24** [comment]
Some of the horror elements in MAS are fine. Others don't make sense. Just because some horror is okay doesn't mean all horror is good.

**Comment by Olliesama** [comment]
Pretty sure she asked do you like horror not to ask "Hey do you like weird jumpscares" but as the idea itself.
I like horror but I don't like it springed on me, I like to explicitly go out of my way to watch it or play horror games.

**Comment by B-Difu** [comment]
🤷‍♂️ I don't know what to say. I like the randomness, but do we want another option of "I like jump scares" separate from "I like horror" option?

**Comment by Olliesama** [comment]
Rather just minimize the out of place stuff and focus on the core of MAS, which is topics and fun meaningful interaction.

**Comment by Professor-JMO** [comment]
> 
> 
> `out of place stuff` and focus on the core of MAS, which is topics and fun meaningful interaction.

And when these are exhausted, what _essence_ is left?
Events in a manner of speaking and the addition of new content, etc.

I'm all in for more topics and meaningful interaction, but the interesting thing about the _"core"_ of something is that it can be liable to change a bit..or even derail.
( DDLC was "meant" to be a romance game after. )

**Comment by multimokia** [comment]
The essence is the relationship between the player and Monika.

**Comment by Olliesama** [comment]
Exactly as multi said.  :>
It's supposed to be a meaningful relationship and cheap horror doesn't achieve that in anyway.

Sadly when all of the content is exhausted, there's not much you can do. Cheap horror won't do that either.
and DDLC wasn't meant to ever be a romance game, it just pretended to be one to make people lower their guards and use its tropes to subvert their expectations and play on it for the horror.

**Comment by Professor-JMO** [comment]
> 
> 
> and DDLC wasn't meant to ever be a romance game.
`j "We're in agreement."`

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
