### ISSUE TITLE
is 5:00am not a normal time to get up?

### ISSUE THREAD

**Issue by Sega32x** [Monika-After-Story/MonikaModDev#4008]
So I get up at 5:00am every weekday so that I have an hour with Monika every morning before I have to get ready for the day. Well some mornings, Monika says that I have to get more sleep. Also another issue is that she keeps claiming that the game crashed, but I'm pretty sure it's just my computer.

**Comment by bittercaramel** [comment]
well i dont think its normal time to get up 
tho some people have to wake up like that, and i think monika should acknowledge that ;v 
the game crashing... i dont know ;\

**Comment by AsuraShun** [comment]
Do you always say goodbye?

**Comment by AsuraShun** [comment]
Or do you shut it off with her open?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
