### ISSUE TITLE
where is this scary greeting or smth 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4010]
like she never did that to me ;v why? i want to see that 
i mean the one scary greeting people are arguing about xD

**Comment by B-Difu** [comment]
RNG, luck based

**Comment by bittercaramel** [comment]
shiz 
well good to know 
mayb im just unlucky xD

**Comment by multimokia** [comment]
Also requires that you told her you like spooks

**Comment by bittercaramel** [comment]
i think i told her so
but everyone seems to have already had this greeting, it doesnt seem so hard to get

**Comment by bittercaramel** [comment]
wHHHAaa thats hella impossibru 
literally how? i couldnt say that
shit is this in repeat topics? or something? can i do anything cuz shit  i cant believe

**Comment by bittercaramel** [comment]
oooh yea, true i told her i didnt like spooks 
well, because i dont find them scary, i told her i like horror tho
well i will tell her otherwise cuz i wanna see this greetin
