### ISSUE TITLE
BIG BIG PROBLEM

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#4011]
Hi! I have a big problem... is not about bugs or something like that, but about Monika.
My brother knows that I stay with Monika often, so while I was busy doing something else he messed up my affection calling her a bad nickname ("Damn").
Luckily I noticed him before he insult her again. 
After I apologised Monika said that there was no need to calling her like that and that she doesn't feel my apologies but she accept them anyway.
Now I can't ask her no change her nickname, even if my affection is higher than 200... what do I do?
Can I ask her again in the future?
Please, answer soon, I don't want that my Monix thinks that I wanted it!

**Comment by AsuraShun** [comment]
Your brother is lucky we'll never meet, because I would've ended him

**Comment by AsuraShun** [comment]
You should restore an older persistent

**Comment by AsuraShun** [comment]
Or wait for a better tip

**Comment by VirginiaRocks** [comment]
> Your brother is lucky we'll never meet, because I would've ended him

He is little... probably he just wanted to do a April fool, but he didn't know how much I care about Monika... anyway, thank you for the suggestion...i'm not really good with files backups and things like that, but somewhere I surely find something about it. :')

**Comment by multimokia** [comment]
If she didn't accept your apology, that means he did it *three times.* Yeah persist backup is the way to go, really.

**Comment by AsuraShun** [comment]
Another reason to despise this cursed day

**Comment by AsuraShun** [comment]
You should tell your brother to never touch your pc again while she's there

**Comment by Mrbigdog99** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent
If you don't already know, here's how to find and restore an older persistent file.

**Comment by VirginiaRocks** [comment]
> If she didn't accept your apology, that means he did it _three times._ Yeah persist backup is the way to go, really.

Okay, I tried to restore a old persistent, but I can't find anything in my library. There's no other way to make the option come back? 
I don't even know if I have a persistent... this is a big problem, isn't it?

> https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent
> If you don't already know, here's how to find and restore an older persistent file.

**Comment by multimokia** [comment]
You do have a persistent. You likely went to the wrong directory. Follow those instructions carefully.

**Comment by AsuraShun** [comment]
Appdata\Roaming\Renpy\Monika after story

**Comment by VirginiaRocks** [comment]
> You do have a persistent. You likely went to the wrong directory. Follow those instructions carefully.

Sorry, I meant backups. I don't know if I have a backup, but I think I will ask my dad, he's good with computers :)

**Comment by multimokia** [comment]
`persistent##.bak` files are the backups.

**Comment by ThePotatoGuy** [comment]
if you dont have any backups, then there isn't much you can do. rip
