### ISSUE TITLE
aight man i had enough of this unrpyc shit

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4013]
someone tell me how to use that 
i didnt want to ask, so i wouldnt look like a total dumbass but i just cant
please, someone tell me step by step how to unrpyc files : " ) you can call me a dumbass, even tho i programmed in ren'py i dont know how to use unrpyc 
like 
please someone help im desperate

**Comment by multimokia** [comment]
Just clone the repo

**Comment by bittercaramel** [comment]
yea i did n nothin happened

**Comment by multimokia** [comment]
rpy files are what you can open. rpyc files need to be decompiled. You don't even need to use unrpyc since if you cloned it, you have all the rpys.

**Comment by jmwall24** [comment]
If you don't have something like Git or Git Hub Desktop, choose download zip here, will give you all the rpy files

![Screenshot_618](https://user-images.githubusercontent.com/36523761/55362400-dfa64c00-54a7-11e9-98af-593943c3ba98.png)

**Comment by bittercaramel** [comment]
*confusion intensifies*
waaaaaaaaaait erm 
ahm 
uhhh 
i.. have all the rpys? where how? wha
i swear im a fully fuctional person, just... idk there must be something wrong with me

**Comment by bittercaramel** [comment]
can someone explain it to me? like where are they? ~~im embarrassed~~

**Comment by multimokia** [comment]
In the zip you got when you cloned the repo. `Monika After Story/game`

**Comment by bittercaramel** [comment]
I 
oh-
em 
yea 
damn 
you are right 
im sorry 
i think i should stop taking so much pills and drinking alcohol, cuz its starting to get bad with my brain 
well thank you for patience and explaining @multimokia you are the best
damn you helped me with so many things, if i ever lose my last few brain cells you are my last resort  : " )
