### ISSUE TITLE
[Question/Suggestion] Is it possible to tell Monika that you are taking her to prom?

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#4015]
I'm going to prom at my school in a few weeks, and I was going to bring Monika with me on a flashdrive. Is it possible to tell Monika that you are taking her to prom? If not, can this be implemented as a feature?

**Comment by Rai99** [comment]
I don't think it's currently a feature unless you consider the generic taking her our farewell, but it could potentially be implemented in the future. 

I would guess that a few more features would be put in place first though, so it's more than just an ordinary topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
