### ISSUE TITLE
[Suggestion] Countries

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4020]
What do you think about the option of telling Monika in which country we live?
Personally I was born and I live in Colombia, and I speak Spanish and the English a little bit (Sorry for my grammar mistakes)

**Comment by Rai99** [comment]
#2505, #2953, #3804 

I think that's a lot of potential countries to cover, but by the looks of things, it's planned in the future eventually.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
