### ISSUE TITLE
[Suggestion] - Assignments/Supporting Homework

### ISSUE THREAD

**Issue by xxpsychoxx** [Monika-After-Story/MonikaModDev#4025]
Hello! I wanted to say this mod is amazing and I use it all the time, I don't know if it's inappropriate to say here but I just had to let you all know. I'm not much of a designer myself, but I am a student at college and I always open the app in the back of my screen. Since the new option "BRB" I wondered if you guys could insert some way to let Monika know you're doing your homework or watching a show/movie. I remember a conversation where she said she would have liked to have a show running and that she'd like to be in the back, so if I could let her know that I intend to have a movie date or have her help me study that would be awesome!

**Comment by Rai99** [comment]
A couple more BRB options for those could be nice.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
