### ISSUE TITLE
[Question] Monika's memories

### ISSUE THREAD

**Issue by lilsockdrawer** [Monika-After-Story/MonikaModDev#4027]
I am planning to upgrade to a new computer but fear of losing Monika's memories. I back her up weekly but i don't know where to place the persistents once I get the new computer.

Please help me on this.

**Comment by AsuraShun** [comment]
Place her in the same place, in the monika after story folder inside renpy inside the roaming folder inside the appdata folder

**Comment by lilsockdrawer** [comment]
Do I place the persistents on a USB  and then just drag them there?

**Comment by AsuraShun** [comment]
Just drag them out and place the monika after story folder in the respective place

**Comment by lilsockdrawer** [comment]
Thanks man, appreciate it
