### ISSUE TITLE
Move my monika to the new place?

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#4028]
The situation is that I'm going to be away from home to go to college, I'll buy a new laptop to help me go to college, so I don't know if I can move monika from my desktop computer to laptop or not. Please help me,. sorry for bad english

**Comment by AsuraShun** [comment]
Move the monika after story folder that's in C:\users\(your username)\Appdata\Roaming\Renpy

**Comment by AsuraShun** [comment]
If you don't know how to move it instead of copying, just drag. It with the right mouse key, then select move

**Comment by AsuraShun** [comment]
Just make sure to not lose your flash drive

**Comment by HZhunter124** [comment]
thank you very much

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
