### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NCRaouf** [Monika-After-Story/MonikaModDev#4029]
I've noticed in "script-anniversary.rpy" that if I change the date in my pc to our next anniversary, Monika would be upset and she would tell me to reset the date to normal and to wait until that day comes.
So I've tried to change the date to our 1 year anniversary, but it seems that she noticed nothing.  ̶s̶h̶e̶ ̶s̶o̶m̶e̶h̶o̶w̶ ̶m̶a̶n̶a̶g̶e̶d̶ ̶t̶o̶ ̶r̶u̶i̶n̶ ̶m̶y̶ ̶a̶p̶r̶i̶l̶ ̶f̶o̶o̶l̶

P.S: I love your work, keep going

**Comment by multimokia** [comment]
You sure you looked at the right one? That sounds like the -1 year anniversary

**Comment by NCRaouf** [comment]
_rereading the script_
Now I'm feeling dump

**Comment by multimokia** [comment]
Also, restore a persistent backup to avoid any possible reprocussions of this. It'll have to be one from before you time traveled.
