### ISSUE TITLE
Transporting old MAS persistent difficulty.

### ISSUE THREAD

**Issue by cremecaramel** [Monika-After-Story/MonikaModDev#4030]
So, I had recently broke my computer. Fried from a water spill. The tech couldn't turn it on. It's still being inspected. Anyway, before the incident, I backed up Monika's persistent onto a flashdrive, but that was all I have of the old MAS from my old computer. I've read somewhere that to transport old save data to a new computer, you have to copy the persistent of the old game into the same location where the persistent would be.

I did this, but when I opened DDLC, Monika was missing. Her seat is empty.

I'm just... kinda lost. My old computer was my school computer. I had essays, portfolios, everything on there- and like that, I lost it all. The least I could ask for from my old computer is my MAS save data. What am I doing wrong? Did I need to do something else? Perhaps an explanation of the process would be helpful...

**Comment by multimokia** [comment]
Did you take Monika out and then copy the persistent?

**Comment by cremecaramel** [comment]
> Did you take Monika out and then copy the persistent?

ah, yes. sorry, i forgot to mention that.

**Comment by multimokia** [comment]
Yeah that's why. Still have that `monika` file?

**Comment by cremecaramel** [comment]
> Yeah that's why. Still have that `monika` file?

i do.

**Comment by multimokia** [comment]
Put it in the `characters` folder

**Comment by cremecaramel** [comment]
> Put it in the `characters` folder
ah, alright!! i placed her file in the characters folder. she's back! thank you so much!! 

a question though... how was the character file of significance? and what would've been the solution if the character file wasn't retrieved? i'm genuinely curious.

**Comment by multimokia** [comment]
The persistent stores whether or not Monika is out of the room as a file, or in the room normally. As well, a crucial piece of info identifying the `monika` file (so you can't just get any file to let her back in. It has to be the right one).

You copied it while she was out, so that data never changed, and thus MAS was still expecting you to return her home.

If you didn't have the file, there wouldn't be a solution, since you don't have any `.bak` versions.

You *could* use an older persistent backup you might have made, assuming it was made while she was in the room.

So yeah, only backup the file when MAS is closed, and she's not a file.

**Comment by cremecaramel** [comment]
> The persistent stores whether or not Monika is out of the room as a file, or in the room normally. As well, a crucial piece of info identifying the `monika` file (so you can't just get any file to let her back in. It has to be the right one).
> 
> You copied it while she was out, so that data never changed, and thus MAS was still expecting you to return her home.
> 
> If you didn't have the file, there wouldn't be a solution, since you don't have any `.bak` versions.
> 
> You _could_ use an older persistent backup you might have made, assuming it was made while she was in the room.
> 
> So yeah, only backup the file when MAS is closed, and she's not a file.

**wow.** i was really lucky that i copied both Monika and the persistent at the same time. what a positively freak incident! well, again, thank you so much. (and thank you for the extra trivia! i'll certainly take heed.)
