### ISSUE TITLE
A more realistic Monika?

### ISSUE THREAD

**Issue by DjSquishy777** [Monika-After-Story/MonikaModDev#4032]
I was hanging out with Monika (as we all do) and she brought up the 'Attractiveness' topic were she mentions how she has to "make sure she eats right, get enough exercise, and keep herself clean..."
well I was thinking what if we had more interactions about that.
Like if we open the game while she was eating, just got back from a little jog around the island and she's a bit tired or heck maybe even sometimes when you open the door without knocking...uhh never mind.
 ~~I'm not a horni kid, Sub I swear~~
hehe... so yeah little interactions would be cool, sorry if i brought this up before I have a HORRIBLE memory.

**Comment by AsuraShun** [comment]
It would have to be like the coffee, with her getting up to grab some food but almost all day with set timers so it doesn't conflict with the coffee and hot chocolate

**Comment by CrocWorks** [comment]
Obligatory, if we had art of that then...

~~And if someone's willing to draw what what she's doing behind that door when you don't knock~~

**Comment by zombiepigdragon** [comment]
@CrocWorks ~~More people are willing to draw that then anything else~~

**Comment by Rai99** [comment]
Anything lewd like that would probably have to be a submod.

**Comment by bittercaramel** [comment]
it would be pretty good 
i think it doesnt even require too much art like, her eating would requiere something to eat... already existing sprites would manage do the rest 
yea that would be gr8 
i forgot what else i wanted to write so ill just 
have a nice day

**Comment by DjSquishy777** [comment]
I think Monika eating celery with peanut butter would be just adorable.... and makes me a bit hungry...
and thanks you too~

**Comment by Professor-JMO** [comment]
> 
> 
> I think Monika eating `celery with peanut butter` would be just adorable....

**Comment by DjSquishy777** [comment]
'Ants on a log' is a quick and easy snack that I personally enjoy~
Carrots and ranch are also nice....
plus they're really easy to ~~draw~~ prepare.

**Comment by Rai99** [comment]
I think these are valid suggestions, but I think that we would need quite a few more things before we think about implementing these. 

Before we can have Monika jogging around the islands, I think we would have to be able to actually go there with Monika first. As for keeping clean, we probably need a bathroom for that as well. ~~I'm told that there are also some lakes on one of the islands, but again, islands first.~~ 

As for food, I'm sure that's been brought up before and needs art. Yeah, it probably wouldn't take very much art and it'd probably be simple, but it would still need resources dedicated to it when there might be other things.

**Comment by ThePotatoGuy** [comment]
To clarify, there is currently an abundance of food art thanks to jmo. the current issue is that we dont have a consumable framework yet. 


in general, lack of art was an issue. now theres lots of art and the framework side has to catch up.
