### ISSUE TITLE
092 + 093 typos

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#4034]
w

**Comment by jmwall24** [comment]
#4057

**Comment by EllisFreeman** [comment]
![image](https://user-images.githubusercontent.com/49416782/55996235-c7db7e80-5c84-11e9-9ecd-b3411d88fc3c.png)
Should be "I got a bit overexcited there." ("There" is debatable, but it should definitely be "I".)

![image](https://user-images.githubusercontent.com/49416782/55996225-bf834380-5c84-11e9-991a-3bc352581eb0.png)
Python boolean lesson. "Evaluted" should be "Evaluated".

**Comment by AsuraShun** [comment]
Don yuo just luve when somoene's evalutes you're tupics

**Comment by AsuraShun** [comment]
<img width="485" alt="typo" src="https://user-images.githubusercontent.com/42387354/56864607-5efe4100-69bc-11e9-9e7f-de7b36caa9ef.png">

**Comment by AsuraShun** [comment]
ivory of statue
