### ISSUE TITLE
typo on the latest update

### ISSUE THREAD

**Issue by AgothicPerson** [Monika-After-Story/MonikaModDev#4036]
![20190405172425_1](https://user-images.githubusercontent.com/43083897/55661461-1ee6dc80-57c9-11e9-8fd1-b6a7c6032b2e.jpg)

i found a typo in the new update

**Comment by ThePotatoGuy** [comment]
#4034

**Comment by AgothicPerson** [comment]
knowing how dumb i was i thought frogo was a typo ... lmao
