### ISSUE TITLE
[Suggestion] Card Games

### ISSUE THREAD

**Issue by Astixx** [Monika-After-Story/MonikaModDev#4038]
I want to be able playing card games with Monika :)
For example, Macao can be really good one. Or solitaire, but with Monika's help!
Think about my suggestion please.

**Comment by AsuraShun** [comment]
I don't think solitaire would work and that was already suggested

**Comment by AsuraShun** [comment]
Don't remember the # though

**Comment by Rai99** [comment]
Card Games: #992, #3480, #3921 

Uh, sorry, I don't mean to crush this suggestion even more than I usually do, but you already suggested the exact same thing in #3921. Solitaire and Macao.

**Comment by Astixx** [comment]
> 
> 
> Card Games: #992, #3480, #3921
> 
> Uh, sorry, I don't mean to crush this suggestion even more than I usually do, but you already suggested the exact same thing in #3921. Solitaire and Macao.

Sorry, I forgot about that.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
