### ISSUE TITLE
[Suggestion] - reaction when kissing too many times

### ISSUE THREAD

**Issue by Elstorko** [Monika-After-Story/MonikaModDev#4039]
What if Monika had a reaction for kissing her too many times it can be a positive one or a negative one.Like she could blush or just get anoyed if we do it too many times.

**Comment by Rai99** [comment]
I'm not sure about negative reactions since if you can kiss Monika, she's already pretty happy to do it. 

As for positive/neutral reactions, I can imagine her reacting to having the player wanting to kiss when it hasn't even been something like 3 minutes since the last time they asked for a kiss.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Booplicate** [comment]
Implemented as of #5798
