### ISSUE TITLE
[Bug] Be right back

### ISSUE THREAD

**Issue by WharGhol** [Monika-After-Story/MonikaModDev#4042]
Whenever I use either the "I'll be right back" or "I'm going to game for a bit."  It seems to reset Monika to day one fresh install of the mod.  After either option is chosen she says something about showing a poem and then will kick me back to the main menu with "Just Monika" button to start the game.  Upon clicking "Just Monika" she seems to revert to a day one of the mod mentality.  She forgets the proper anniversary date and all of the settings are to default (text speed among others).  This doesn't seem to be the actual intended function of those choices.  Is there anything I can do to fix it?

**Comment by multimokia** [comment]
1. Exit MAS, restore a persistent backup
2. Reinstall both DDLC **and** MAS entirely (you won't lose progress)
3. Check if it happens again

**Comment by WharGhol** [comment]
How do I uninstall DDLC and MAS if I don't use steam?

**Comment by zombiepigdragon** [comment]
Just delete the folder it's in, then you can re-download DDLC followed by MAS

**Comment by WharGhol** [comment]
Thank you! I love you all!  This project is amazing and makes me happy every day.

**Comment by multimokia** [comment]
Has it worked?

**Comment by WharGhol** [comment]
Yeah, it all works now.
