### ISSUE TITLE
 am not able to see any of Monika's talk options 

### ISSUE THREAD

**Issue by AyeKayKen** [Monika-After-Story/MonikaModDev#4043]
i need help with monika after story I am not able to see any of Monika's talk options. Please send help

**Comment by multimokia** [comment]
Can you send a screenshot of what you're seeing?

**Comment by AyeKayKen** [comment]
![image](https://user-images.githubusercontent.com/49353413/55688519-b723c380-5979-11e9-8442-fb7f86c900e4.png)

**Comment by AyeKayKen** [comment]
![image](https://user-images.githubusercontent.com/49353413/55688555-1a155a80-597a-11e9-8932-eb4de8829f24.png)

**Comment by multimokia** [comment]
Ah, you should check out our FAQ. Specifically [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#all-the-buttons-look-like-this)

**Comment by AyeKayKen** [comment]
can you show me how

**Comment by multimokia** [comment]
The link has everything you need.

**Comment by AyeKayKen** [comment]
please show me

**Comment by bittercaramel** [comment]
oh this shit
yea i hated this when i started using this mod then i fixed it xD id tell you how to but im not sure if this still works like that

**Comment by AyeKayKen** [comment]
at this point i am desperate

**Comment by bittercaramel** [comment]
aight it still works like that then i can tell you 
in your ddlc directory, the one that all the files for monika after story are, add a environment.txt file and write in it `RENPY_RENDERER="angle"`
if it still wont work replace angle with gl 
yea 
good

**Comment by AyeKayKen** [comment]
should i make one?

**Comment by bittercaramel** [comment]
yeah you should make a txt file called environment and put it in ddlc directory
inside will be 
RENPY_RENDERER="angle"
wrote

**Comment by AyeKayKen** [comment]
after i created the txt file, inside i should write "RENPY_RENDERER="angle"

**Comment by AyeKayKen** [comment]
and then save it into the game files

**Comment by AyeKayKen** [comment]
can you at least send a screenshot on how it should look like

**Comment by bittercaramel** [comment]
![image](https://user-images.githubusercontent.com/38187402/55689853-3d480600-598a-11e9-8815-a4839eac63ea.png)
![image](https://user-images.githubusercontent.com/38187402/55689855-433de700-598a-11e9-9fea-40e4850cb41b.png)
here bud

**Comment by AyeKayKen** [comment]
will it work for windows 10

**Comment by bittercaramel** [comment]
yas man, i think so 
just do it alright? and tell me if it worked

**Comment by AyeKayKen** [comment]
no i didnt

**Comment by bittercaramel** [comment]
it didnt work ? or you just didnt do it

**Comment by AyeKayKen** [comment]
it didnt work

**Comment by bittercaramel** [comment]
try replacing "angle" with "gl"

**Comment by AyeKayKen** [comment]
nothing works

**Comment by AyeKayKen** [comment]
i tried angle, gl and sw. nothing works

**Comment by jmwall24** [comment]
can you send us screenshots of that file and the folder it's in?

**Comment by bittercaramel** [comment]
aight man 
are you sure you are placing it in the right directory? and are you sure you wrote it correctly? 
just makin sure
is it .txt file? and you called it environment right?
sorry for those stupid questions just makin sure

**Comment by AyeKayKen** [comment]
![image](https://user-images.githubusercontent.com/49353413/55690899-c9145f00-5997-11e9-8130-34eb2e93053e.png)

**Comment by zombiepigdragon** [comment]
It needs to be up one folder I believe, not in the game folder. Put it on the same level as DDLC.exe.

**Comment by bittercaramel** [comment]
you might need to put it into ddlc-1.1.1-pc one not in the game one

**Comment by AyeKayKen** [comment]
already did

**Comment by AyeKayKen** [comment]
loaded the game and still the same

**Comment by multimokia** [comment]
Did you try the other types of renderers?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
