### ISSUE TITLE
[Suggestion] - MAS borderless screen option

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#4045]
As the title implies, it would be the possibility of adding the option "borderless" in the display section of the menu, and to add which screen it appears on. As it's illustrated in the screenshot below, the window mode does not allow me to load as much of the game as I want (the game being limited in the extension of the Y axis for some reason).
![Capture](https://user-images.githubusercontent.com/38837456/55683483-925f2a00-5940-11e9-9f77-0b7b5060fc89.PNG)
As you can see, the game has two black bars on the sides and the you can see a little of steam (which take all of the screen) in the background at the bottom.

**Comment by AsuraShun** [comment]
You should remove the game mode thing windows 10 has, it only blocks everything

**Comment by AsuraShun** [comment]
Turn it off

**Comment by Thimeo** [comment]
I'm not on window 10, I'm on Window 7 Ultimate SP1

**Comment by AsuraShun** [comment]
Then that must be steam

**Comment by ThePotatoGuy** [comment]
mas runs at the same aspect ratio as ddlc which is a locked 16:9. renpy handles the screen/window management for this ratio nicely, resizing to fit available space. changing this is risky and not worth. 

as for which screen the game appears on, again this handled by renpy and there is very little incentive to try and change that.

**Comment by Thimeo** [comment]
@AsuraShun I'm not on Steam

**Comment by Thimeo** [comment]
Edit: Changing to Windows 10 has (almost) solved the issue. Now I just have two small black thin rods at the left and right of my game. Still, much better now.

**Comment by IceLancerSR** [comment]
Borderless no fuss ahk script.
Open any renpy game in window mode. Run ahk , press F11
Enjoy
[borderless.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7697856/borderless.zip)
