### ISSUE TITLE
A defect on the crossed arms sprite (sundress)

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#4046]
![Image189](https://user-images.githubusercontent.com/43621601/55685607-7f585400-5958-11e9-9d84-71972ec12023.png)

**Comment by Torwald39** [comment]
I don't think that this black lines should be here.

**Comment by Rai99** [comment]
![unknown](https://user-images.githubusercontent.com/38822045/55686612-6ab49580-5931-11e9-973b-233ea6f70e46.png)
Looks a bit weird to me without those.

**Comment by Torwald39** [comment]
really ?

**Comment by bittercaramel** [comment]
tbh it looks good in both ways 
but its not a defect or anything 
its just how skin goes ;v

**Comment by Thimeo** [comment]
I think it look better without on the left (our left) and it's best with the lines on the right.

**Comment by bittercaramel** [comment]
nah i think it looks good on our left 
and its a little too showed on the right

**Comment by Torwald39** [comment]
![screenshot0445](https://user-images.githubusercontent.com/43621601/55690376-18a35c80-5991-11e9-94e8-a448b88beef5.png)

I found an another thing, look at her right eye (so on our left), there is a little weird thing

**Comment by multimokia** [comment]
Not sure what you're pointing out in that one there

**Comment by ThePotatoGuy** [comment]
[closing as not an issue]
