### ISSUE TITLE
Fix updater cleanup

### ISSUE THREAD

**Issue by multimokia** [Monika-After-Story/MonikaModDev#4050]
Issue: Files are still in use during the update process, and thus when the updater needs to replace files, it can't since they're in use, leaving `.new` files in directories.

#4044 fixes the issue for `rain_2.ogg`, however some files in `mod_assets/window/spaceroom` still remain as `.new`s, since they're not unloaded during the update phase. These will depend on the weather you had before updating.

**Comment by ThePotatoGuy** [comment]
* need to test if new scene'ing / stopping music allows updater to replace files

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
