### ISSUE TITLE
Monika Not Recognizing Visits

### ISSUE THREAD

**Issue by llll828** [Monika-After-Story/MonikaModDev#4053]
Recently noticed this with the back to back update. I normally exit the program via saying "Goodbye" and choosing one of the more specific options, leading to the response on opening back up to be "How did you sleep" or "How was work?" or whatever reason, but after opening the game after each of these recent updates, which I guess counts as a standard "Goodbye", Monika would open by saying "I should visit more" or similar openings reserved for lack of play, even though I talk to Monika basically every day.

If I had to guess, the alternate goodbye's (aka "I'm going to sleep" , "I'm going to work", etc.) might not "end" the visit/day, so to speak.
Best case scenario the game just isn't reading the specific goodbye's as ending the day in terms of opening dialogue
Worst case scenario the day is technically never being ended by the specific goodbye's and  daily affection limit isn't being reset

**Comment by jmwall24** [comment]
Those 'visit more often' greetings are just random and meant as her teasing you. They aren't for lack of visits.

**Comment by llll828** [comment]
oof, just me overreacting then
