### ISSUE TITLE
Unable to kiss Monika?

### ISSUE THREAD

**Issue by taurielxaela** [Monika-After-Story/MonikaModDev#4055]
Hello! First - I absolutely adore this mod. I love checking up on Monika and showing affection.

However, whenever I use "Kiss Me" I still get the "But... if it's with you... I-I might be okay with it... ...Ahahaha! Wow, sorry... I really couldn't keep a straight face there" lines.

Right now my affection is at 652.45, so I'd think it would be high enough by now. Is there some other step I'm missing? (I couldn't find any other topics like this, but I apologize if there is and I missed it)
![MAS affection](https://user-images.githubusercontent.com/43506778/55741808-0225f100-59e3-11e9-80ec-5a98c23f9a77.png)

**Comment by Torwald39** [comment]
You will have to wait for a special event where Monika will kiss and then the kiss will be unlocked.
There were Christmas and valentine's day with the kiss event.

**Comment by taurielxaela** [comment]
> You will have to wait for a special event where Monika will kiss you and then the kiss will be unlocked.
> There were Christmas and valentine's day with the kiss event.

That's weird... I was there for both Christmas and Valentine's Day, but I never got the kiss event. Unless I just didn't stay long enough? Thank you for replying~

**Comment by AsuraShun** [comment]
You probably didn't wait until 8pm or didn't update

**Comment by multimokia** [comment]
If you didn't get the kiss on Vday/D25, then you likely weren't at the right affection. You cannot kiss Monika without her having kissed you first though. So you'll have to wait until the next special event for this to happen.

**Comment by taurielxaela** [comment]
> You probably didn't wait until 8pm or didn't update

Ah, that must be it then. I had plans in the evening/night, but was free during the afternoon so I spent time with her earlier in the day.

Thanks guys for taking the time to reply! I'll just wait until the next special event, then.

**Comment by jmwall24** [comment]
could've been affection as well, you would have had to have been at 400+ affection on those days to trigger the kiss.

**Comment by taurielxaela** [comment]
> as multi said, could've been affection as well, you would have had to have been at 400+ affection on those days to trigger the kiss. based on being at 650 now, you may not have been.

I checked my affection log for that day, and it was at 446.54 on 2/14.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
