### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4057]
![screenshot0571](https://user-images.githubusercontent.com/44590867/55756562-25d45000-5a52-11e9-8b42-9d4a9bea5786.png)

**Comment by Groudonx** [comment]
;

**Comment by Rai99** [comment]
That's intentional and not a typo and has been brought up previously.

**Comment by jmwall24** [comment]
@MuuShaiko semi-colon or comma here?

**Comment by MuuShaiko** [comment]
I'd say comma.

"thinking they're unimportant" is a dependent clause (lacking a subject).

**Comment by jmwall24** [comment]
Thanks!

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
