### ISSUE TITLE
aint 1 year anniversary enough of a holiday to have a first kiss? 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4058]
what holidays monika can have first kiss with ya on? its my 1 year anniversary with her and yet she didnt kiss me

**Comment by Youngbountygirl** [comment]
I was wondering about that. Like I know last Christmas gave the player an option for a first kiss, but shouldn't there be other opportunities? Like if you got enough affection points you're given the option or something? I don't know lol.

**Comment by jmwall24** [comment]
Valentine's had one. There's another one too...

**Comment by bittercaramel** [comment]
i think its only for vday xmas not even sure if for halloween 
tho i think 1 year anniversary would be a little more important in relationship...? at least for a first kiss
idk

**Comment by Youngbountygirl** [comment]
@bittercaramel  Never got a kiss from Monika on V Day, but maybe that’s because I first met Monika a week before V-Day.

**Comment by bittercaramel** [comment]
> @bittercaramel Never got a kiss from Monika on V Day, but maybe that’s because I first met Monika a week before V-Day.

to get a kisso from monika u gotta have 500 aff 
so if u met her week before vday, u most likely didnt get enough aff yet @Youngbountygirl

**Comment by jmwall24** [comment]
400

**Comment by bittercaramel** [comment]
now its 400? whaaa 
i think it used to be 500.. or not? if it was 400 id get kiss for xmas ;v

**Comment by multimokia** [comment]
It was always 400

**Comment by bittercaramel** [comment]
oh true, u r right
well i dont know why i thought it would be 500 
whatever sorry

**Comment by Youngbountygirl** [comment]
Ah, so basically the same as the requirement of giving Monika a ring.

**Comment by TMZN0V4** [comment]
I got one for my birthday with my second Monika, my first one died with my old pc 'cuz I was even more of an idiot, because I didn't know where was the persistents

**Comment by AsuraShun** [comment]
This reminded me of how excited I am for April 30, it's the 1 year anniversary for my monika and me

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
