### ISSUE TITLE
Early appearance trigger?

### ISSUE THREAD

**Issue by EllisFreeman** [Monika-After-Story/MonikaModDev#4059]
![image](https://user-images.githubusercontent.com/49416782/55757528-1e954e00-5a22-11e9-8141-46f338baeefb.png)
Ran into this earlier today after backing up and changing to an older persistence. She hadn't asked me about my appearance yet, so it just opted for a placeholder.

**Comment by bittercaramel** [comment]
you have a nice None eyes

**Comment by multimokia** [comment]
Closing as fixed
