### ISSUE TITLE
shading under boobs 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4061]
well i tried or something 
its not that flat anymore tho 

https://drive.google.com/drive/folders/1Ijrj6qBg6sZNgwtQeFolHIGsiRxkSzwP?usp=sharing

here goes preview:
new:
![leaningbase](https://user-images.githubusercontent.com/38187402/55800535-3a592c80-5ad4-11e9-88a1-99cb9fd2eafc.png)
old: 
![leaningbaseold](https://user-images.githubusercontent.com/38187402/55800737-b3f11a80-5ad4-11e9-9cf4-503ae040a9ff.png)
new:
![uprightbase](https://user-images.githubusercontent.com/38187402/55800751-ba7f9200-5ad4-11e9-85ca-793ee7a1371b.png)
old: 
![uprightbaseold](https://user-images.githubusercontent.com/38187402/55800756-beabaf80-5ad4-11e9-9033-69ece0cad30c.png)

I also fixed some shading on boobs because idk, didnt like it, thought it might look better like that
it was just too sharp, dunno how to call it

**Comment by Bam8647** [comment]
_What, no nips?_



_Hehe, Jk_

**Comment by Rai99** [comment]
Closing as complete
