### ISSUE TITLE
Outside windows turn black

### ISSUE THREAD

**Issue by StaticEncounter** [Monika-After-Story/MonikaModDev#4065]
So I just noticed this now, but for some reason when I'm tabbing back into the game, the outside texture switches to pitch black. It stays like that until I change the weather, but it just switches back after a bit. Not sure if it's a bug or not.
![Monika Bug](https://user-images.githubusercontent.com/48573990/55844134-1fe57a00-5af9-11e9-8490-9ee972c8b1e4.png)

**Comment by Cristianmvv** [comment]
No worry, that's not a bug, sometimes in my town we have V̴̜̞̲̙̠̦̰̙͂̾͑͆͢͞O̠͖͍͋͌ͣ͒̆̕I̴͙͔̅̾̄̈́̒D̶̨̜̽̉́͊̐̀͞ storms so it's pretty normal

**Comment by AsuraShun** [comment]
Animated background failed to load

**Comment by ThePotatoGuy** [comment]
renpy does not handle being minimized well, so visual issues may occur.

**Comment by StayHappy1270** [comment]
@ThePotatoGuy idk what that means the renpy being minimized how do i fix it? can u show me?? (ty in advance)

**Comment by squishycatz** [comment]
I have started experiencing the same problem after a few months of using this game. It started turning black whenever i minimized and then opened the game. does anyone know a solution.

**Comment by dreamscached** [comment]
That's an upstream issue with the RenPy engine. Wait for MAS updates, where engine update may help.

**Comment by Booplicate** [comment]
Just don't minimise the game
