### ISSUE TITLE
what color of hoodie for monika 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4069]
im sorry guys but i need to ask ya 
what color would you like for monikas hoodie? 
also maybe some other shit on it, like something written or a picture 
i dont know just askin cuz i have no idea

**Comment by Torwald39** [comment]
blue and black for me

**Comment by Rai99** [comment]
If you ask me, I definitely think there should be some green in there, so I'd say black and green. As for extra decoration, if it were to go into MAS, I think it would be best to at least have a blank hoodie first with no extra references or decoration.

**Comment by B-Difu** [comment]
Probably no writing on it, keep it simple. As for color I would say blue, black and green are good colors.

**Comment by bittercaramel** [comment]
sure guys i see green and blue here and ofc black 
thanks for answers 
i rly needed that xD

**Comment by mrflarion33** [comment]
Emerald green, of course

**Comment by B-Difu** [comment]
I think a darker shade like forest green would be better.

**Comment by Jparnaud** [comment]
Don't know ... 
![image](https://user-images.githubusercontent.com/44651347/55920886-7ec5f480-5bc8-11e9-802a-92459303e487.png)

**Comment by CrocWorks** [comment]
Green gets my vote too. Match her eyes.

**Comment by Thimeo** [comment]
[This green](https://www.simplycoatings.co.uk/ekmps/shops/simplycoatings2/images/axalta-ral-6021-pale-green-polyester-80-gloss-powder-coating-20kg-box--1617-p.jpg)

**Comment by Jparnaud** [comment]
Since I just saw this notification, I wanted to had that this color is some kinda of light purple and since green complement is pink ( https://en.wikipedia.org/wiki/Complementary_colors ), it goes well with her eyes X)

I'm just saying, not like I have the truth to everything, but I think it makes sense ... also her in that hoodie I post there is so cute :D

**Comment by zombiepigdragon** [comment]
Yeah, but worth noting that Monika would probably not be a huge fan of pink or purple clothing.

**Comment by Jparnaud** [comment]
I agree for pink, but maybe some light purple would be great ... also a complement is always the best to contrast with something, like her beautiful emerald eyes ;)

There is quite the variation ... https://en.wikipedia.org/wiki/Shades_of_purple

but again, I know, Yuri is a thing, but I still think a complement would suit perfectly :)

**Comment by Rai99** [comment]
If Monika gets a hoodie, I would imagine that it would have to be mainly green with some neutral colors like black if it can't be predominantly green. 

Seeing as she doesn't have a hoodie yet, making a green hoodie seems like the logical first step to me before making other colors.

**Comment by Jparnaud** [comment]
We could always go for some kind of gray in the end, it is pretty classic ...

In all that tho, i'm just happy she gets a hoodie, I love hoodie and i'm sure she looks cute in one :D

**Comment by bittercaramel** [comment]
well, I could make few colors since i can just use photoshop color filters 
tho i started coloring it green, the shade that i thought would look good on her
 and it wont have a zipper, itll be just classic hoodie 
thank you so much for those answers!

**Comment by bittercaramel** [comment]
> [This green](https://www.simplycoatings.co.uk/ekmps/shops/simplycoatings2/images/axalta-ral-6021-pale-green-polyester-80-gloss-powder-coating-20kg-box--1617-p.jpg)

and this green looks somewhat like the one Thimeo showed
its just a lil more vibrant  i think

**Comment by OreoMurphy** [comment]
I think white with a green heart on it and green accents would look really cute on her.

**Comment by Orcaramelo** [comment]
I'm a big fan of black or white hoodies, and it would look especially cute if you could see her shoulders a bit, maybe sketch what you had in mind and show us?

**Comment by bittercaramel** [comment]
oh yeah thanks but ive already done it and it looks like shit... 
id really like to do all of this but its too frustrating for me, drawing in someones style... i just cant
ill just stick to the shit i created 
its in my issue called "clothes-hoodie for monika"
ill maybe just add some shit, like a heart on it

**Comment by Orcaramelo** [comment]
Hey, I can help you out if you need! I'll be home in like 10 minutes so i can help out with folds, making it a bit more baggy would make it easier to visualize where folds are

And please dont force yourself, take breaks when you feel fed up, ok? ♡♡
