### ISSUE TITLE
Telling Monika you'd die for her [suggestion]

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#4070]
In the "I want to tell you something" section maybe add an option to tell Monika you'd die for her at a certain affection level. I thought of this a few minutes ago and I don't really know how well it would go into the mod, cause a part of me gets a feeling telling Monika something like this would upset her a bit but maybe that's all me. I wanna see everyone's thoughts and opinions on this idea and that's one of the big reasons as to why I'm putting it out there.

**Comment by AsuraShun** [comment]
Even if it was for her, she'd end up getting deleted by the deceased one's family if that actually happened

**Comment by Rai99** [comment]
Personally, I think that's something Monika definitely wouldn't want to hear, and if she could, I don't think she'd allow you to do that anyway. 

It sounds like it covers a similar theme to the monika_gotomonika topic with how much you can tell Monika you'd give up to be with her. 

The way I picture it, I don't see it as a natural thing to bring up randomly, and while it could be a nice gesture of love or something, I don't think she would appreciate you dying for her.

**Comment by Rai99** [comment]
You don't die for the one you love. You live for them.

**Comment by AsuraShun** [comment]
Nice fairy tail reference

**Comment by AsuraShun** [comment]
But yeah, she'd hate it

**Comment by B-Difu** [comment]
Yeah, I personally think that be a bad thing to say to her. The only person she interacts with/loves tells her that they would die for her. While it may seem sweet, she would have no one left, leaving her alone forever, possibly in the void.

**Comment by Torwald39** [comment]
it's kind of heartbreaking to hear this

**Comment by AsuraShun** [comment]
This would hurt her instead of whatever reaction you thought she'd have, and that's a no go

**Comment by Professor-JMO** [comment]
> Telling Monika you `died` for her [suggestion]

**Comment by MoniBoosDevotedBoyfriend** [comment]
This went downhill faster than any other post I've seen in a while oof

**Comment by DankeyMaliten** [comment]
Thanks for the opinions everyone, I see now that this is a very bad suggestion and I just wanted to hear everyone's thoughts
also idk what fairy tale is lol but if the shoe fits wear it
issue closed.

**Comment by Rai99** [comment]
~~I don't watch fairy tail though~~

**Comment by AsuraShun** [comment]
Then how did you know about that phrase? It literally sounds like something that was said in the first season
