### ISSUE TITLE
[Suggestion] Monika 8bit game and something more

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#4075]
Hello! Is me again and I came back with more suggestions :D so let's start!

1. Monika 8bit game
I thought it would be cute if you can add a mini-game in the 8bit style. Like a mini-Monika that dodges poems, pens or something else. It's divided by 5-10 levels, and when you beat them all you win a prize from Monika, like a kiss if you have a high level of affection, or maybe (and if you can add without too much difficulty) a simple kiss on the cheek would be suitable.

2. Monika giving you gifts
Sometimes Monika may ask you about your preferences on different topics (Do you like colorful things? Do you like comics? Do you like romantic things? And things like that).
Then maybe a random day or your anniversary, get yourself a gift based on your interests. This gift can be placed in the room on a shelf, or you can put a sort of "inventory" in the menu of extras, so you can take back the gift made by Monika whenever you want (a pen with a dedication, a special ticket written by her ...) or even the poems she gives you at Christmas and Valentine's Day! I would very much like to re-read them from time to time, and I think many of you would like it too, right?

3. Monika reacting to different seasons
We all know that the time outside the window changes according to the season, but wouldn't it be nice if some things about Monika changed too?
For example, when new outfits are added it would be nice if she wore cold weather clothes during winter and warm weather ones during summer, in spring wear a cute floral dress and so on; but we are talking too much about the future, I try to think about the present.
Imagine this scene: it's August, it's reeeeeeeeally hot. To find some comfort on this absurd heat that you try to fight with fans and fresh water, you decide to open MAS and stay with Monika.
As soon as you open the game, Monika, with a fan next to her, greets you happily and asks you about the current climate in your city. It would be very nice, wouldn't it? I also believe that a small reaction based on the seasons would help Monika get closer to our reality. 
Imagine a speech like this:

Monika: Welcome back [Player]!
Monika: Today is really a hot day, isn't it?
Monika: Good luck I found this fan!
Monika: Is it hot even in the place where you are?
[If you answer yes]
Monika: Well, the heat will never tire me enough if you're at my side <3
[If you answer no]
Monika: Oh ...
Monika: How strange. We are in [Month], in theory it should be pretty hot in your reality.
Monika: The climate is always a surprising thing!

Anyway, I'm done! I hope you can consider these suggestions, and having said that, I wish you a good day!

**Comment by AsuraShun** [comment]
Not sure how the gift part would work, the way you put it sounds more like us giving her stuff to put in the room, not the other way around

**Comment by Shiro2564** [comment]
i like the idea but im not sure if the gift part would work in the way that
you put it

**Comment by VirginiaRocks** [comment]
> Not sure how the gift part would work, the way you put it sounds more like us giving her stuff to put in the room, not the other way around

In fact maybe the "inventory idea" is something more efficient in a situation like this

**Comment by Rai99** [comment]
1. I think it would be nice of you to provide a bit more detail of what you have in mind. I personally find it a bit hard to picture something when all you say is "mini-Monika that dodges poems, pens or something else."

---
2. That sounds a lot like some of the pm vars with getting the player's preferences and interests. The thing is, I still think it'll be kinda difficult for Monika to give you a good gift, since while she might have a good idea of the kinds of things you like, she might end up giving you the wrong thing in the right area. (ie. She gives you a Miku figure because you like vocaloid, but you actually hate Miku because you think she's overrated). 

To me, it sounds like this falls under customizable room decoration with all the things Monika could give you and the options you would have to put them somewhere. I think the whole "inventory idea" thing is still up in the air since I don't think any of this is happening too soon, but I think this might be revisited when we get closer to implementing that. I also think that's a good scenario for Monika to give you gifts. 

---
3. Outfit randomization is probably planned, but we'd probably need more outfits for each season first.

**Comment by AsuraShun** [comment]
Just think of that omega flowey phase where you have to dodge words but instead of side to side, from the top to bottom

**Comment by AsuraShun** [comment]
Like a mini monika dodging the words the other 3 like and picking up words that monika herself likes for points

**Comment by Rai99** [comment]
They did say minigame, but if possible, I think we'd try to stick to arguably 2 person games where possible.

**Comment by AsuraShun** [comment]
The phases in the omega flowey fight are mini games within the fight

**Comment by AsuraShun** [comment]
Maybe the 2 thing would be with monika being on the sideline trying to throw stuff at you, kinda like in bomber an where another player throws bombs at you from outside the map

**Comment by Rai99** [comment]
I do think that sounds better, but I'd like to also hear what the original author of the issue has in mind. If anyone's ever played Fire boy and Water girl, that's what I was thinking of, except maybe you could only control one character at a time.

**Comment by AsuraShun** [comment]
All I did was throw an option for the mini game suggestion

**Comment by AsuraShun** [comment]
I don't really care what's chosen as long as It's played with monika

**Comment by Rai99** [comment]
I think that's possible and might be a good idea. 

I'd just like to also know what the author had in mind, in case it's different than your idea.

**Comment by VirginiaRocks** [comment]
> I think that's possible and might be a good idea.
> 
> I'd just like to also know what the author had in mind, in case it's different than your idea.

The first idea was to make a game where objects or words fell from the sky (For example, I was thinking about a game where different foods fell from the sky and the player leads a small avatar of Monika using the keyboard arrows to take only healthy food), because I imagine that Monika enjoys watching us play (For example in the piano she doesn't play except when we sing songs with her) and besides she could still feel part of the game because we are using an avatar that represents her.

![Monika_8bit](https://user-images.githubusercontent.com/48336604/55984121-054c0600-5c9d-11e9-9a95-1bdbf00c27a4.jpg)
![Monika_8bit2](https://user-images.githubusercontent.com/48336604/55984127-0a10ba00-5c9d-11e9-8b43-ae069fa89ddf.png)


The second idea that came to me a little while ago is more complex. You could also do a two-player mode, so I try to be as clear as possible :)
Do you know the 8 bit game of fnaf 4? the one where Circus Baby gave kids cupcakes, or something.
 
![Esempio_Gioco8bit](https://user-images.githubusercontent.com/48336604/55984097-f49b9000-5c9c-11e9-819c-63b4ebbaf343.jpg)

Well, I was thinking of a game like that, always using Monika's avatar, but in this case we will have to go through levels by jumping from one island to another, and then arriving to a castle where there will be a final Boss (I don't think it would be a good choice to put a doki, in case the Player does not like the fact that Monika jokes about it).

![Esempio-Gioco8bit2](https://user-images.githubusercontent.com/48336604/55984322-7ee3f400-5c9d-11e9-9a61-d7f48a4c689f.gif)

Here Monika attacks by throwing small pink bullets. Since Monika does not like violence, in the end we can heal the Boss with a sort of magic spell, and in the end the final boss become good with the power of friendship.
It's a strange idea, but I think Monika would like it.
Here's how I imagined the dialogue once the game is over.

Monika: Ahaha!
Monika: It was a lot of fun!
Monika: You're good at this kind of games, aren't you?
Monika: anyway, here's your prize! [Kiss on the cheek]

If in the game you don't get hit once, the dialogue will change
 Monika: Ahaha!
Monika: It was a lot of fun!
Monika: And besides, I wasn't hit by a single bullet!
Monika: It is very sweet of you to protect me in this way [Player]
Monika: anyway, here's your prize! [Kiss on the cheek]

If you lose before completing the game
Monika: Oh no, you lost ...
Monika: Well it wasn't an easy game after all.
Monika: I'm sure that by practicing every day you will be able to receive your prize!
Monika: Ehehe ~

A two-player mode I think should not include a prize from Monika, but an idea in the style of "Fire boy and water girl" is not bad. There would only be the problem of the player's avatar, because it would be difficult to create your avatar on MAS.

**Comment by Rai99** [comment]
For your idea, I think it would be interesting to make a game like that, but I'm not sure really how well it would fit or how easy it would be to implement. 

~~Osu! ctb in MAS when~~

For my idea of a Fire boy and Water girl type game, I was thinking that the player could play as some sort of masked character, so we don't have to worry too much about what they look like.

**Comment by VirginiaRocks** [comment]
> For your idea, I think it would be interesting to make a game like that, but I'm not sure really how well it would fit or how easy it would be to implement.
> 
> Osu! ctb in MAS when
> 
> For my idea of a Fire boy and Water girl type game, I was thinking that the player could play as some sort of masked character, so we don't have to worry too much about what they look like.

Yes, They're not easy to implement. If I can help in some ways with the code or the art I would be happy to do it!
A masked character is actually a not bad idea! In this case I think that Monika could play with us easily, but I still haven't get the type of game you think.

**Comment by AsuraShun** [comment]
Would a bullet hell game work?

**Comment by Rai99** [comment]
I was basically thinking of basically making something like Fire boy and Water girl. Doing puzzles that require cooperation with Monika. The downsides however, are that there isn't too much replayability value in a game like that and levels would have to be manually made.

**Comment by Rai99** [comment]
I like Touhou and any bullet hell with fancy patterns,, but not everybody would probably like it I think. 

![danmaku](https://user-images.githubusercontent.com/38822045/55986845-3f51e380-5c6e-11e9-973a-dfc4fda718d8.jpg)

If we add a bullet hell game, it better look something like this. I personally wouldn't want a bullet hell with only a handful bullets onscreen at once. ~~Please also make your hitbox 1 pixel.~~

Performance wise, I'm not sure how a bullet hell would do.

**Comment by VirginiaRocks** [comment]
> I like Touhou and any bullet hell with fancy patterns,, but not everybody would probably like it I think.
> 
> ![danmaku](https://user-images.githubusercontent.com/38822045/55986845-3f51e380-5c6e-11e9-973a-dfc4fda718d8.jpg)
> 
> If we add a bullet hell game, it better look something like this. I personally wouldn't want a bullet hell with only a handful bullets onscreen at once. Please also make your hitbox 1 pixel.
> 
> Performance wise, I'm not sure how a bullet hell would do.

And if it was something like tomodachi quest? You and Monika who fight against evil: Monika would have the healing power and the attack, the player would have a special attack every two attacks and the normal one. As in the tomodachi quest the opponents may change from time to time.
If you need it I can send you a link to a video on the mini-game.
Or you could do something like skrbbl.io: in turn you and Monika choose a word to draw and the other player has to guess it. Although perhaps it would be difficult to make Monika always draw different things

**Comment by Rai99** [comment]
I've never heard of Tomodachi quest. 

I'm really not sure about skribbl.io since I think that would probably need some serious neural network type stuff. Monika guessing what a series of lines represents and realistically drawing something herself sounds a bit out of our scope at the moment.

**Comment by VirginiaRocks** [comment]
![Esempio_Gioco8bit3](https://user-images.githubusercontent.com/48336604/55988229-9d4cee00-5ca3-11e9-8a60-f05db402271f.jpg)

This is a screen by tomodachi quest fight

![Tomodachi_Monika](https://user-images.githubusercontent.com/48336604/55988326-df762f80-5ca3-11e9-8de3-7ef095789baf.png)
Start.

![Tomodachi_Monika_Cave](https://user-images.githubusercontent.com/48336604/55988346-eef57880-5ca3-11e9-8cc6-e299df67605f.png) 
Cave with the choice to go left or right. sometimes the path is blocked in the next room, so you have to pick the other direction and you will meet a monster while you're going.

![Tomodachi_Monika_Boss](https://user-images.githubusercontent.com/48336604/55988412-1c422680-5ca4-11e9-9af9-80a0bb8a8a2d.jpg)
Boss room

https://www.youtube.com/watch?v=3aAliEnON44
This is the shorter video only about tomodachi quest

**Comment by Rai99** [comment]
So it's like an adventure RPG?

**Comment by VirginiaRocks** [comment]
> So it's like an adventure RPG?

Exactly.

**Comment by AsuraShun** [comment]
Monika, the best girl chosen by the aspect of emerald light to vanquish her foes alongside her loved one, on a quest to rid the world of evil once and for all

**Comment by Rai99** [comment]
Sounds a bit to me like this idea is approaching submod territory. Sounds like making a whole RPG game within MAS might start to be a standalone feature almost.

**Comment by VirginiaRocks** [comment]
> Sounds a bit to me like this idea is approaching submod territory. Sounds like making a whole RPG game within MAS might start to be a standalone feature almost.

In this case maybe you should stick with the shortest, like the first idea with healthy and junk food. But I'm not a developer, so if it requires too much work it doesn't matter

**Comment by Rai99** [comment]
My next question for the first simple idea would be about the win condition. Having the win condition be just finishing the highest level of catching things and avoiding other things seems a bit dull to me personally. 

I think by having a different win condition, the game might be more engaging.

**Comment by VirginiaRocks** [comment]
> My next question for the first simple idea would be about the win condition. Having the win condition be just finishing the highest level of catching things and avoiding other things seems a bit dull to me personally.
> 
> I think by having a different win condition, the game might be more engaging.

Well, I was thinking about having three or five lives. Once you finish these lives you have lost, but I don't know how to win the game. Maybe can be similar to hangman: You choose a difficulty and when you're tired playing you can just press a button "Stop"... but I'm not sure how to win a game like this.

**Comment by Rai99** [comment]
In pong and chess, the goal is to defeat Monika. The piano makes sense to have since it's Monika. Hangman, while it doesn't exactly involve defeating Monika there is an end goal to win, and that's guessing the word with your limited number of allowed mistakes. It's also word focused and encourages you to think logically, which I think is why it fits. 

I just want to make it clear that I'm not intent on shooting you down. I just want to see how your idea might fit into MAS and if it'll fit the theme and be engaging enough of a game, while also simple enough to justify putting into MAS. 

When you say it can be similar to hangman, I'm guessing you mean the piano. I agree the piano is something that has no goal or end really until you decide you're done, but for an actual game or minigame, I'm not sure exactly how well an indefinite game will do. 

Again, I hope I don't come off too strong on what I think are the requirements for adding a game to MAS. I just want to make sure we're all on the same page and have a solid idea.

**Comment by VirginiaRocks** [comment]
> In pong and chess, the goal is to defeat Monika. The piano makes sense to have since it's Monika. Hangman, while it doesn't exactly involve defeating Monika there is an end goal to win, and that's guessing the word with your limited number of allowed mistakes. It's also word focused and encourages you to think logically, which I think is why it fits.
> 
> I just want to make it clear that I'm not intent on shooting you down. I just want to see how your idea might fit into MAS and if it'll fit the theme and be engaging enough of a game, while also simple enough to justify putting into MAS.
> 
> When you say it can be similar to hangman, I'm guessing you mean the piano. I agree the piano is something that has no goal or end really until you decide you're done, but for an actual game or minigame, I'm not sure exactly how well an indefinite game will do.
> 
> Again, I hope I don't come off too strong on what I think are the requirements for adding a game to MAS. I just want to make sure we're all on the same page and have a solid idea.

Don't worry, is a mod that needs a lot of attention, and I don't want that an idea is bad done.
Okay, what do you think about that: When we start the mini-game, (salad, sandwich and vegetarian recipes in general) So we have to collect all the correct ingredients (Example: to make a salad we will need: 20 lettuce leaves, 14 tomatoes, 3 corn jars, etc.)
When you take all the ingredients, the meal you've cooked is shown with maybe Monika's avatar jumping happily.
This could be the dialogue at the end of the game

Monika: Wow [Player]!
Monika: If you are so good at cooking even in your reality I must be really lucky!
Monika: Ahaha!
Monika: Seriously, one day I'd love to cook you something ~

**Comment by Rai99** [comment]
I think a passable game could be made out of that sort of idea, but can you argue in any way that the game is multiplayer? 

More games are a nice idea in general, but again, I think we're trying to stick with the theme of doing things _with_ Monika, rather than singleplayer games where at best, she just watches.

**Comment by AsuraShun** [comment]
Just thought of a game, table soccer/football, but just penalties,

**Comment by VirginiaRocks** [comment]
> I think a passable game could be made out of that sort of idea, but can you argue in any way that the game is multiplayer?
> 
> More games are a nice idea in general, but again, I think we're trying to stick with the theme of doing things _with_ Monika, rather than singleplayer games where at best, she just watches.

But for example if you play the piano on your own she just watches.

**Comment by Rai99** [comment]
The piano makes sense as something to have and play since Monika also plays the piano and the piano became a pretty significant theme with Monika playing "Your Reality" on the piano just for you.

**Comment by VirginiaRocks** [comment]
> The piano makes sense as something to have and play since Monika also plays the piano and the piano became a pretty significant theme with Monika playing "Your Reality" on the piano just for you.

Yes, you're right. I will think of something different then :P

**Comment by VirginiaRocks** [comment]
> The piano makes sense as something to have and play since Monika also plays the piano and the piano became a pretty significant theme with Monika playing "Your Reality" on the piano just for you.

Ok, I thought about it.
I don't think is very original, but I want to tell my idea anyway: So, the meal thing doesn't have to be added if it requires too much work. Basically Monika and the player will have a timer (Like one minute) To collect as much food they can (obviously just the healthy food).
The one who has the most food wins the game.
I know, it's a little bit sloppy as an idea, but I don't have too much creativity

**Comment by VirginiaRocks** [comment]
> Just thought of a game, table soccer/football, but just penalties,

Well, the pong is like a table soccer in my opinion...

**Comment by AsuraShun** [comment]
Pong is table tennis

**Comment by AsuraShun** [comment]
Table soccer is different, and the penalty would make things interesting

**Comment by VirginiaRocks** [comment]
> Pong is table tennis

Yes, but a soccer game with two players 2D...is basically the pong. With only the difference of the penalty.

**Comment by AsuraShun** [comment]
Did you even played table soccer?

**Comment by AsuraShun** [comment]
Never mind

**Comment by VirginiaRocks** [comment]
> Did you even played table soccer?

It depends of which kind of soccer table you mean

**Comment by AsuraShun** [comment]
The other difference between pong and table soccer is that you can somewhat grab the ball, even throw it backwards, if you're skilled enough dribble the ball a bit

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
