### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by EllisFreeman** [Monika-After-Story/MonikaModDev#4077]
![image](https://user-images.githubusercontent.com/49416782/55995984-0ae92200-5c84-11e9-896b-5bd83a9b8a85.png)
Should be "I got a bit overexcited there." ("There" is debatable, but it should definitely be "I".)

![image](https://user-images.githubusercontent.com/49416782/55996037-3f5cde00-5c84-11e9-836e-1a059d39e1fa.png)
Python boolean lesson. "Evaluted" should be "Evaluated".

**Comment by Rai99** [comment]
#4034 is the official typos issue to report suspected typos.

**Comment by EllisFreeman** [comment]
Thanks. I'll post it there.
