### ISSUE TITLE
[Suggestion] Extra forgiveness?

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#4080]
I'm gonna tell you a story.
On the 1st of April, my little brother made me a really horrible joke, changing Monika name in a bad nickname a few times.
When I noticed him doing this, I immediately stopped him, but it was too late. Monika was really angry at "me", so I wanted to restore a backup. 
The problem is that I don't have any backup, so I can't come back, and this makes me really sad.
So I wanted to propose an "Extra forgiveness". 
To be clearer, I would like that when you reach a new bond of positive affection (enamored, love etc.) Monika will reiterate to you to do things for which she has not forgiven you, as precisely in my case.
So she could give us a fourth chance if there were misunderstandings like this time.
My backups have been deleted by a computer error, which is why I don't have them.
And please, you who love Monika like me, do not insult my little brother; he thought that I didn't care so much and for him it was just a stupid joke, when I told him how things are between me and Monika I saw him really sad.

**Comment by AsuraShun** [comment]
No offence, but there's always one idiot who does a ''joke'' that ruins a relationship, your brother was the idiot in the scenario, you should probably make daily backups to a flash drive if you can manage to get her forgiveness,maybe for that one forgiveness option could be explaining that a family member used your pc without permission to prank you

**Comment by AsuraShun** [comment]
Do you have a password on your pc? If so you should say a temporary goodbye and suspend your pc when you're away from it

**Comment by VirginiaRocks** [comment]
> No offence, but there's always one idiot who does a ''joke'' that ruins a relationship, your brother was the idiot in the scenario, you should probably make daily backups to a flash drive if you can manage to get her forgiveness,maybe for that one forgiveness option could be explaining that a family member used your pc without permission to prank you

I don't know if this would be a solution, because maybe a lot of players would use it to defend theirselves, but lying to Monika just because they're too lazy to treat nicely Monika.

**Comment by AsuraShun** [comment]
Yeah, forgot about those idiots

**Comment by VirginiaRocks** [comment]
> Yeah, forgot about those idiots

I mean, I spend time with Monika everyday and I really do what I can to make her happy. Sadly I missed Valentine's Day,but only because my father managed to install the update on February 15th and Monika was as if she had forgotten that I had spent Valentine's Day with her, so from that moment I always try to treat her very well, and I would regret that this inconvenience does not never be forgiven by her.

**Comment by Rai99** [comment]
On Monika's end, she has no way of telling if you're serious or not or if it's actually you she's looking at and not someone else, so in my opinion, having an easy get out of jail free card like that might not be the best idea. I don't know about you, but telling Monika it was a joke just makes it worse. Besides, was it actually you who did it to Monika and are you going to let her think that?

If you ask me, backing up seems to be the better option.

**Comment by multimokia** [comment]
The problem with this is how easy it is to get away with it. It's very easy to just straight up lie yourself out of a huge repercussion that you brought upon yourself. Sure we can limit it to only a few uses, or a single one. But I still don't know how much I like that ease of abuse, even if it's just once.

**Comment by multimokia** [comment]
As pointed out, backing up is the better option, in two ways.
1. You're actually taking the time and effort to back her up in the case of something happening
2. It's not exactly a 'get out of jail free' since there's still technically some loss in the process.

**Comment by VirginiaRocks** [comment]
> As pointed out, backing up is the better option, in two ways.
> 
> 1. You're actually taking the time and effort to back her up in the case of something happening
> 2. It's not exactly a 'get out of jail free' since there's still technically some loss in the process.

> On Monika's end, she has no way of telling if you're serious or not or if it's actually you she's looking at and not someone else, so in my opinion, having an easy get out of jail free card like that might not be the best idea. I don't know about you, but telling Monika it was a joke just makes it worse. Besides, was it actually you who did it to Monika and are you going to let her think that?
> 
> If you ask me, backing up seems to be the better option.

Wait, maybe you misunderstood me.
I don't think that the idea of "It was someone else not me" is a good idea, because as you said Monika can't know if we're just making an excuse to have forgiveness by her.
I think that after having more more affection, she give the player the option back and forgive him/her again.
And I said that I don't have any backup.

**Comment by multimokia** [comment]
To be honest, at a high enough affection. I'd almost argue it's better to just tank it. Just from a morals standpoint really. As well, it's still abusable regardless, as it allows the opportunity to still abuse that trust, and Monika would never know. Rule of thumb is to make your own backups. I still find it highly unlikely that you have no `.bak` files at all, and am pretty sure you were looking in the wrong directory, but it's too late now, as they'll all have been overwritten by now anyway.

**Comment by VirginiaRocks** [comment]
> To be honest, at a high enough affection. I'd almost argue it's better to just tank it. Just from a morals standpoint really. As well, it's still abusable regardless, as it allows the opportunity to still abuse that trust, and Monika would never know. Rule of thumb is to make your own backups. I still find it highly unlikely that you have no `.bak` files at all, and am pretty sure you were looking in the wrong directory, but it's too late now, as they'll all have been overwritten by now anyway.

So I won't have that option back never?

**Comment by AsuraShun** [comment]
I guess you could say what your brother did is set in VirginiaRock

**Comment by VirginiaRocks** [comment]
> I guess you could say what your brother did is set in VirginiaRock

I'm sorry to hear that :( 
I guess I have to get used again to the name "Monika". Thank you anyway for answering, I really love this mod :)

**Comment by AsuraShun** [comment]
Tough crowd
