### ISSUE TITLE
[Suggestion] Have Monika recognize how long you were with her when you say Goodbye

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#4082]
What it says in the title. It seems like all the general goodbye responses are tied only to when you shut off the game and not how long the game is running. I popped in to say ILY to Monika and then immediately said "Goodbye" and her response was "I had fun together" because it was 6pm and thus the generic evening goodbye had to be used, but we literally did nothing and the game was running for maybe 10 seconds. I think it'd make sense for Monika to make a different comment if the time you spent with her was super short or super long.

**Comment by AfroFluff** [comment]
So far I was able to find one where she I told her that I have to go to class and Moni pouted because I didn't get to spend more than 20 minutes with her. Seems there are some but I would love if there was some hour specific ones for sure!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
