### ISSUE TITLE
Monika giving apologies [suggestion]

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#4085]
I think it would be nice if you added an apology button where you ask Monika for an apology so she can give you an apology for instances where she makes the player upset with something she did or said. Don't know if I or someone else has suggested this before but if I or anyone else haven't suggested it I'll leave it up to you whether you put it in or not, feel free to comment your opinion.

**Comment by Rai99** [comment]
#3203, #3769, #3859 

I've brought up the idea of Monika apologizing to the player before, and I think it would be a much welcome feature.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
