### ISSUE TITLE
[Suggestion] Unique dialogue for waking Monika

### ISSUE THREAD

**Issue by AlenNez** [Monika-After-Story/MonikaModDev#4086]
I really like the new feature of having her fall asleep if held long enough. As perfect as it already is, I'm curious whether new dialogue is possible for it. What I intend is that if Monika falls asleep during the nighttime (I believe 6 PM or after, when the windows get dark) and she is held until the morning comes by (sun shines outside), she would have unique dialogue to talk about it and ask how you slept, maybe add a suggestive joke or two there as well to lighten the mood. It's an insignificant suggestion, I agree, but it would just be nice considering how if you do the steps listed, the light outside doesn't change (sunny stays sunny, nighttime stays nighttime) as long as Monika is held.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
