### ISSUE TITLE
[ ACS - Wearable: Hair clips/pins 🔗🧷 ] "Good things come in trios." [ Build: Ver 1.12 ]

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#4087]
ʃ i m o n's Craft Projects
                                        Format: Unicode
                                          Code: #3174 
                                           04.14.2019
📁⯈ A_band_for_bonds
---
⯆ Open: _"Style.rtf"_

---

>>>>![Corrupt Monika Banner ( In use )](https://user-images.githubusercontent.com/43480604/56098113-ac5db700-5ec2-11e9-9139-085e72e18b71.png)

⮞ ```¿ "One of these may appear edgier than the rest."```
⮞ ```m "I'm pretty proud of my fashion sense."```
⤷ ```m "You get a certain feeling of satisfaction when you stand out from the normal population, you know?"```

⮞ It's come to my attention for awhile now..
⤷ That Hair clips/pins were _desired_!

⮞ "Why not?" I say!
⤷ _Ribbons_ aren't the only way to accessorize!

⮞ Besides, the nice thing about fashion..
⤷ Is when it _compliments_ itself.

---

>>>>![Corrupt Sayori Banner ( In use )](https://user-images.githubusercontent.com/43480604/56098187-84228800-5ec3-11e9-8418-35956a87137f.png)

⮞ To the clips/pins!

![Bound](https://user-images.githubusercontent.com/43480604/56098275-77526400-5ec4-11e9-832b-12c79b5ceac2.PNG)

⮞ With [ 3 ] variations!

• Where's the third clip/pin?
⤷ Don't worry about that right now.

• Framework ready?
⤷ Not necessary unless otherwise intended.

• Is that a new hat for Monika?
⤷ Close b u t **NO**.

• How can I use this?
⤷ You **can't**
> The item is currently stuck in [Limbo.](https://www.youtube.com/watch?v=CdqCGc_L8ZQ)
>> Only time and circumstance will tell.

⮞ _Don't be neglectful_.
>⮞ _"It's important to understand that our actions have ramifications, or lack thereof."_ 

⮞ If you browse GitHub regularly.
⤷ [Stylish: Custom web page themes](https://userstyles.org/styles/browse?search_terms=github&type=false)
> Dark looks so much better here. 👌

⯅ Close

---

📁⯈ accessories_n_stuff
---
⯆ Open: "hairaccessories"

---

📁⯈ Clip_n_pins

⯆ Open: "assortedhairclips.rtf"

>>>>![Corrupt Yuri Banner ( In use )](https://user-images.githubusercontent.com/43480604/56098464-702c5580-5ec6-11e9-9f9f-8bc05e45e1cb.png)

>⮞WW91IHNob3VsZG4ndCByZWFkIG90aGVycyB0aG91Z2h0cywgdGhhdCdzIGludmFzaXZlIHlvdSBrbm93IQ==
![In league](https://user-images.githubusercontent.com/43480604/56098503-be415900-5ec6-11e9-84b0-95a41f22e02a.PNG)

General Information
---

⮞ A barrette (American English), also known as a hair clip, hair slide or clasp (British English), is a clasp for holding hair in place. They are often made from metal or plastic and sometimes feature decorative fabric. In one type of barrette, a clasp is used to secure the barrette in place; the clasp opens when the two metal pieces at either side are pressed together.
⤷ Barrettes are worn in several different ways partly according to their size, with small ones often used at the front and large ones in the back to hold more hair. They are used to keep hair out of the eyes, or to secure a bun, a French twist or a ponytail. Short metal "clip" barrettes are sometimes used to pull back front pieces of hair. Barrettes are also sometimes used purely for decorative purposes. 
> Many different kinds of hair clips were invented in the 20th century. The ones that are more famous are, the elongated hair clip which was invented in 1972 by Marnie Bjornson and the simple "clips" hair-clip, which works by snapping the clip from a concave to convex position, springing it into a locked position, or opening it.

⯅ Close

---

📁⯈ contents_n_stuff
---
⯆ Open: _"Sayonara.rtf"_

---

>>>>![Corrupt Natsuki Banner ( In use )](https://user-images.githubusercontent.com/43480604/56098617-b504bc00-5ec7-11e9-8d3e-187b480efc30.png)

⮞ This area will serve as a continuation for more hair clip/pin/band content updates.
⤷ _But before I go.._

⮞ I'm always open to requests from the community.
⤷ _I just can't promise I'll get around to them._
> In other words..
>> If there's a clip/pin/band you want to see made..
>>> This will be an applicable place to _request_ one.

• #3174 
• #4012 

⯅ Close

---

📁⯈ the_stuffs
---
⯆ Open: 📎 Attachments 📎

---

Meme of the Theme!
---

>>>>![httpswww reddit comrDDLCcomments9qyfdorelatable_yuri_meme](https://user-images.githubusercontent.com/43480604/56097970-b088d500-5ec0-11e9-98d1-3bb2c9332040.png)

---

⯈ [Hair Clips/Pins 🔗🧷 ](https://github.com/Monika-After-Story/MonikaModDev/files/3077849/Manifest.zip) ⯇ ← 🎩 ?

---

```
from subprocess import call
```
>def play_wave_file([You're in my head - Moow.wav):](https://youtu.be/aVSGRX-apDA)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by Professor-JMO** [comment]
To-Do's for hair clips.
---
> Music Note
>> Firefly

**Comment by Rai99** [comment]
Are these _technically_ hats?

**Comment by AsuraShun** [comment]
I can already tell that if this is added, the yuri clip is a no go

**Comment by bittercaramel** [comment]
darn if she had this cute natsuki hairclip 
she would look soo sweet

**Comment by Rai99** [comment]
I'm not sure if Monika would want to be wearing hairclips from the other dokis.

**Comment by Professor-JMO** [comment]
> 
> 
> darn if she had this `cute` `Natsuki hairclip`
> she would look soo `sweet`

**Comment by AsuraShun** [comment]
Yeah, like the knife gift, she was offended by it

**Comment by Professor-JMO** [comment]
[ The `Emerald Eighth` Update ]

>>>>![Corrupt Monika Banner ( In use )](https://user-images.githubusercontent.com/43480604/56232544-a4c71b00-6046-11e9-8acb-ffe62b91ae92.png)

`m "Hey, what's your favorite color?"`
`m "Mine is emerald green."`
`m "It's the color of my eyes!"`
`m "...That's not conceited or anything, is it?"`
`m "I just meant that I feel some kind of special connection to it."`
`m "Like it's part of my identity."`
`m "Does it happen to also be your favorite color, [player]?"`
`m "It's just a guess..."`
`m "...because you've been looking into my eyes for a while now."`
`m "Ehehe~"`

![For you](https://user-images.githubusercontent.com/43480604/56232215-da1f3900-6045-11e9-89d4-06a7d55e243b.PNG)
---

>>>>![Corrupt Natsuki Banner ( In use )](https://user-images.githubusercontent.com/43480604/56232513-924ce180-6046-11e9-9bdf-11a1439454f8.png)


⯈[ Emerald Eighth 🎵 ](https://github.com/Monika-After-Story/MonikaModDev/files/3086225/Manifest.Emerald.Eighth.zip) ⯇

**Comment by AsuraShun** [comment]
I hope that when this is added that those expressions go along with it

**Comment by Professor-JMO** [comment]
[ The `Cute Ribbon` Update ]

⮞ ```¿ "Time is an illusion that once realized, is lovingly embraced, none the less."```

`Ask a question` > `Club members...` > `Can you do any impressions?`

![Sassy, idk](https://user-images.githubusercontent.com/43480604/56309682-a577b400-610f-11e9-8f79-ace2cb046ecb.PNG)

---

>>>>![Corrupt Natsuki Banner ( In use )](https://user-images.githubusercontent.com/43480604/56232513-924ce180-6046-11e9-9bdf-11a1439454f8.png)


⯈ [ Cute Ribbon 🎗️ ](https://github.com/Monika-After-Story/MonikaModDev/files/3090840/Manifest.Cute.Ribbon.zip) ⯇

**Comment by Sujeito17** [comment]
This is the art God

**Comment by ThePotatoGuy** [comment]
Alright, I'm going to use these for testing #3416 , as witch hat/neko ears dont have leaning versions.

**Comment by ThePotatoGuy** [comment]
okay but unlikely to use the purple hair clip lmao

**Comment by ThePotatoGuy** [comment]
@Professor-JMO just fyi, double check ur layers and make sure theres no subtle shadows or anything.

Using the twilight filter and a grey bg clearly shows faint colored regions:
![watchoutjmo](https://user-images.githubusercontent.com/3499462/56783489-9d73e000-67b1-11e9-8bb5-af85c9e912a7.png)

These kinds of things I can fix easily, so no worries, but just letting you know.

**Comment by Professor-JMO** [comment]
^ Huh, that's unusual.
Were these subtle shadows exported with the clips?
I can't imagine why those are there.

**Comment by ThePotatoGuy** [comment]
they were in all the clips (not sure about the purple ones since I didn't check those).

The layer was I think the clip layer. Whatever was above shadow.

**Comment by Professor-JMO** [comment]
Yeah, it's the clip layer for whatever reason.
~( The purple is simply a template if not an ACS of its own **Volition**. owo )~

I'll be sure to _watch out_ from now on concerning these discrepancies.
> Harnessing the power of `Twilight` would do wonders for me, I think. 🌔

**Comment by bittercaramel** [comment]
OMG 

damn i just saw this damn "cute ribbon" its so frickin cute 
i love it, my goodness 
AaaaaaaAAAAAAaaa

**Comment by TriniTDM** [comment]
Well, the hair clips are good, but Monika would probably get mad at me if I tried to use the "cute ribbon", since she'd likely think I was trying to make her more like Natsuki. I mean, she already gets mad if you try to name her Natsuki, and the hair dye suggestion got shut down for the same reason, so it's not a stretch to imagine she would be against wearing what is pretty much an obvious copy of Natsuki's hair thing.

**Comment by ThePotatoGuy** [comment]
[closing as these were added already]

**Comment by Professor-JMO** [comment]
[ `Bonds` Update. ] 🔗
