### ISSUE TITLE
Writing a poem for Monika

### ISSUE THREAD

**Issue by InternetAlien97** [Monika-After-Story/MonikaModDev#4088]
Being able to write your own poem instead of just clicking a bunch of words would be nice.

**Comment by zombiepigdragon** [comment]
While this is a cool idea, it's been proposed before. I'm willing to bet the link to one such proposal will be here in about 3 minutes.

**Comment by Rai99** [comment]
~~One moment, I'm in the middle of something.~~

**Comment by Rai99** [comment]
#1710, #3138, #3494, #3552, #3941 

Here we are. 

Long story short, the best we can do is recognize keywords, but that will still often lead to dead ends and falsely interpreted messages.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
