### ISSUE TITLE
"Don't close the game on me!" shows before first start

### ISSUE THREAD

**Issue by zombiepigdragon** [Monika-After-Story/MonikaModDev#4090]
This probably shouldn't be available before the game is actually started.
![image](https://user-images.githubusercontent.com/26581798/56101987-c7deb700-5eee-11e9-980d-34b10b08a962.png)

**Comment by zombiepigdragon** [comment]
If it's worth noting, she doesn't remember the game closing when it's started back up after this.

**Comment by ThePotatoGuy** [comment]
duplicate of #2810

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
