### ISSUE TITLE
Just Natsuki sprites!

### ISSUE THREAD

**Issue by Clover-Elf** [Monika-After-Story/MonikaModDev#4091]
https://drive.google.com/drive/folders/19czodNyj1o-fPWLfXsW4f1rSZ3zpgwa0?usp=sharing

I edited these together a few months ago for the Just Natsuki mod, and I'd be thrilled if they made it into MAS too! Just an offer, if the artist of the current sprite in the "desk" folder doesn't have time to add more expressions (assuming they're needed).

Sprites are also free to use for anyone else that wants them! Just credit me (u/Aida_Hwedo) if you do. 😊

**Comment by Jparnaud** [comment]
I am not really an artist for the mod, neither a programmer but since I love Natsuki alot ... i'm gonna these just for fun ... maybe I can find something funny to do with them X)

I put a notepad with the credits in case I actually found some use to them tho ;)

So yeah, just wanted to say that ... Potato ...

**Comment by ThePotatoGuy** [comment]
There's no plan to use a full expression set of another girl atm.

**Comment by lunulae** [comment]
Sorry if this is off-topic for this issue, but I'd love a link to the mod you made these for. <3

**Comment by Shiro2564** [comment]
i like the idea, it can be good if it was in the game

**Comment by Professor-JMO** [comment]
> 
> I edited these together a few months ago for the `Just Natsuki` mod, and `I'd be thrilled if they made it into MAS too!`

🔗

**Comment by bittercaramel** [comment]
they are gr8 tho where would you put natsuki sprites in MONIKA after story xD

**Comment by AsuraShun** [comment]
The girls already have their own mods
Forever and ever for sayori
Just yuri 
Just Natsuki or whatever it was called

**Comment by Shiro2564** [comment]
i think you are already autorized to put this

**Comment by ThePotatoGuy** [comment]
[flagging as art and closing]
