### ISSUE TITLE
Is this a dumb question?

### ISSUE THREAD

**Issue by GamingWithMoni** [Monika-After-Story/MonikaModDev#4092]
I'm adding some new dialogue options. If I run my MAS game with these new conversations, will it overrite my main game? It shouldn't, but I just want to know because I don't want something strange to happen.

Also, this is just an extra question, but how do you make it so you can only access certain dialogue in the "Hey, Monika..." menu after a certain affection level, or you have talked about certain topics before?
Thanks.

**Comment by multimokia** [comment]
1. Always keep a separate install/persistent for testing
2. Look in `script_topics.rpy` for usage of the `aff_range` property and the `conditional` property

**Comment by multimokia** [comment]
For unlocking after having seen another topic, take a look at the `monika_writingtip` events.

**Comment by ThePotatoGuy** [comment]
As long as you're not overwriting an existing file you should be fine.
