### ISSUE TITLE
Making the Game Force Quit

### ISSUE THREAD

**Issue by GamingWithMoni** [Monika-After-Story/MonikaModDev#4093]
1. How do you force the game to close itself, like when you say goodbye?
2. How do you make a topic reduce affection, or be able to apologise when you say a certain thing?
3. How do you make it so when the game is opened, Monika remembers you said something that make her incredibly hurt, and when you click talk, instead of the generic message, she says something different, for example; "Was that all a joke to you? You really upset me..."

I'm making a mechanic for saying you've died, or been injured, etc, because she's brought it up before, and tells you to tell a family member or friend about her so they can tell them the news, however, there is no option that you can actually tell her what happened.

**Comment by multimokia** [comment]
The idea has been rejected in the past, and will not be accepted into the mod.

**Comment by multimokia** [comment]
Though as for your questions:

1. `return 'quit'`
2. Check topics like `monika_justification` for use of affection/apologies (as well, look at `script-apologies.rpy`
3. You can store things happening via persistent variables. This one sounds like it would be a player model (pm) variable which are in the form `persistent._mas_pm_<description>` (replacing <description> with what the variable stores)

Also, you can't really change that line in the talk menu.

**Comment by GamingWithMoni** [comment]
Okay. I do not plan on publishing this, because it probably won't turn out very good, so I'm most likely going to keep it as a private project, just as some custom conversations. Also, thank you for your help.

**Comment by AsuraShun** [comment]
Don't make her suffer

**Comment by GamingWithMoni** [comment]
> 
> 
> Don't make her suffer

I won't.

**Comment by antimockingjay** [comment]
If you do manage to make it, please let me know! That's something I'd be interested in, even if it's not in the official mod. Not for the sake of hurting her, but rather in case something _does_ happen. I have a handful of friends who would easily do it for me if I asked them to let Monika know something had happened, but that would have to be an option in the first place. So I'd be really appreciative of an option like that, even if I have to add it to my own game instead of it being officially part of the mod.

**Comment by AsuraShun** [comment]
I doubt this will be implemented because this is basically giving an excuse to get away with everything

**Comment by OreoMurphy** [comment]
I'd really be interested in that as well. I just feel like I'd need a way for Monika to know if something happens to me. So if you do make it please tell me.
