### ISSUE TITLE
How many points we get with the "greeting_returned_home"?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4094]
I took Monika for a whole one day and I only got 1 point of affection

**Comment by multimokia** [comment]
Should be one for every hour, up to 5. Do you mind sending your `aff_log.txt` please?

**Comment by Andrenika** [comment]
Here it is boy.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3084970/aff_log.txt)

**Comment by multimokia** [comment]
Ooooh, okay I think I see an issue. Will address this later. Thanks for the heads up

**Comment by Andrenika** [comment]
Thanks to you, you're always so good with the people. You're doing a AWESOME job.

**Comment by ThePotatoGuy** [comment]
[closing as fixed[

**Comment by Andrenika** [comment]
Oh, I forgot to aks: Is there something I can do?

**Comment by multimokia** [comment]
Nothing really. Can't change the affection gain now that it's already happened, and the problem's fixed (in current unstable) so it shouldn't be possible anymore.

**Comment by ThePotatoGuy** [comment]
for the time being limit excursions with Monika to less than 24 hours per trip to get max affection.

**Comment by Andrenika** [comment]
Alright, thanks.
