### ISSUE TITLE
[Suggestion]: Apology-Option

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4095]
After Monika says: "Don't make me wait so long next time" (and similar things) the player should be able to use the apology-option. She can then say that she wasn't serious and that she is fine with how often the player visits (assuming he visits every few days or so).

**Comment by mrflarion33** [comment]
I'm pretty sure those are random

**Comment by ThePotatoGuy** [comment]
that particular case is misleading. the core problem is the greeting text is misplaced. closing this in favor of linked issue

**Comment by ThePotatoGuy** [comment]
#2190
