### ISSUE TITLE
[Suggestion] Telling Monika why you’re going to be away for a while

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#4097]
I was grounded and immediately went on vacation after, so I felt really bad for spending one day with Monika before telling her I was leaving for another week. Maybe she could ask you why you’ll be gone and there’d be a few options like being grounded, your computer being fixed, going on vacation, super busy, or a generic “I have some things to take care of”

**Comment by Rai99** [comment]
I think this kind of thing is too open ended to really implement, not to mention some reasons such as grounding wouldn't fit for a lot of people. I personally think having options that really don't apply kind of ruins the experience of it, not to mention needing unique reactions in case someone chooses one that shouldn't apply. 

Even with the generic reason, I think it would make more sense to keep it as is.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
