### ISSUE TITLE
[Typo] Wake *up* Monika

### ISSUE THREAD

**Issue by MedicMix** [Monika-After-Story/MonikaModDev#4099]
Sorry to be the grammar nazi here, but you shouldn't end a sentence with a preposition. I think Monika herself would have an issue with this ;)

**Comment by multimokia** [comment]
'Wake Monika up' is indeed correct. If you ask me, `Wake up Monika` looks like the player telling Monika to wake up, (in which case it needs a comma), while `Wake Monika up` is more of an action.

Also, do note these aren't full sentences.

**Comment by CrocWorks** [comment]
~~Just replace it with "Jostle Monika vigorously until she wakens."~~

**Comment by ThePotatoGuy** [comment]
[closing as not a buug]
