### ISSUE TITLE
Nothing in Log Folder

### ISSUE THREAD

**Issue by SweetiePie2020** [Monika-After-Story/MonikaModDev#4102]

**Comment by multimokia** [comment]
Are you on mac?

**Comment by SweetiePie2020** [comment]
Yes, I am.

**Comment by multimokia** [comment]
Okay, your logs are stored elsewhere. Since Mac has file permission problems. They're in a hidden directory over in `~/.MonikaAfterStory/log`, which you can access by the terminal. Check the spoilers wiki, under affection, and how to check your affection. That has instructions for Mac users.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
