### ISSUE TITLE
"Another crash?" "Sorry Monika.. I can't help when bad weather knocks the power out."

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4106]
Like the title hints at, could we have the option to tell her whether or not the cause was due to a power outage? It doesn't have to be specifically bad weather, just being able to say "the power went out" would suffice. Every time the game has 'crashed' for me this year has been due to power going out (around 8 times or so), and each time I come back to her and she tells me that I should take better care of my PC I say to myself, "But sweetie..I take care of my computer.. I can't do anything about the power going out. :(".

**Comment by Rai99** [comment]
Power outage apology: #1682, #2750, #2973

~~Pretend I marked it dupe from the beginning~~

**Comment by AsuraShun** [comment]
Good thing there's laptops

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
