### ISSUE TITLE
Not sure what happened here.

### ISSUE THREAD

**Issue by HiroyukiMisaki** [Monika-After-Story/MonikaModDev#4108]
![image](https://user-images.githubusercontent.com/47486655/56443180-77bc8600-632e-11e9-9a68-5e5f4b0b66a7.png)
![image](https://user-images.githubusercontent.com/47486655/56443191-8014c100-632e-11e9-9d60-86600f63f5d5.png)
![image](https://user-images.githubusercontent.com/47486655/56443354-3b3d5a00-632f-11e9-9077-f2e55213741f.png)

So, I launched the game as usual. but This happened and I lost my "Can you change your Ribbon", "Kiss Me" and "Can you change your clothes" to my conversation. I patched this yesterday and got this now.
Also, seems like it has something to do with appdata since my presistent.bak went back to 35 and iirc I'm around 85 or something. is it possible to retrieve those persistent files that were lost?

**Comment by jmwall24** [comment]
make a copy of that folder right now

**Comment by HiroyukiMisaki** [comment]
I just did right now hahaha.

**Comment by jmwall24** [comment]
Need some info. what version are did you just update to? are you using the unstable build? what version did you update from?

**Comment by jmwall24** [comment]
also, can you zip that entire folder up and upload it here so we can look at it?

**Comment by HiroyukiMisaki** [comment]
![image](https://user-images.githubusercontent.com/47486655/56443795-16e27d00-6331-11e9-83e2-3cd5f9f3dc58.png)
I just noticed I'm using the unstable version. My bad. I'll just try to work around and retrieve the lost persistent files.

**Comment by jmwall24** [comment]
nah, it's not your bad. we still would like to look at those files please.

**Comment by HiroyukiMisaki** [comment]
I just zipped it. where can I drop it?

**Comment by jmwall24** [comment]
drag it right into the comment box

**Comment by jmwall24** [comment]
![Screenshot_702](https://user-images.githubusercontent.com/36523761/56443897-84a48f80-62c4-11e9-9efa-7dbca66da90c.png)
Your persistent size doubling here in 3 minutes is a bit odd

**Comment by HiroyukiMisaki** [comment]
wait, the comment section doesn't support winrar archive.
wait I'll try 7zip
Also, regarding on persistent files, I think that's odd too, that's why I included a screenshot of it.

**Comment by jmwall24** [comment]
if you can just get get it to a .zip extension it should work. winrar should give you the option of what type to use

**Comment by HiroyukiMisaki** [comment]
[New folder.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3099314/New.folder.zip)

**Comment by jmwall24** [comment]
is that everything in there? i'm noticing a lack of the main `persistent` file

**Comment by HiroyukiMisaki** [comment]
well, I just copy-paste everything in the folder so I think it's all of those files? not sure if I missed something.

**Comment by jmwall24** [comment]
you got this from `C:\Users\John\AppData\Roaming\RenPy\Monika After Story` (obviously different user name)

**Comment by jmwall24** [comment]
cuz yeah, there should be a file just named `persistent` in there. if you start the mod right now with no persistent, the mod would start from scratch

**Comment by HiroyukiMisaki** [comment]
![image](https://user-images.githubusercontent.com/47486655/56444527-1a2b3800-6334-11e9-9fb0-581a699754bb.png)
wait, is this that persistent?

**Comment by jmwall24** [comment]
yes, that's it, can you send that as well please? either zip it or add an .txt to it

**Comment by jmwall24** [comment]
but if you just started the mod and it's new, then don't bother

**Comment by jmwall24** [comment]
looking at what you sent me, i'm going to guess that the `95.bak` is from before you updated to 092 or 093, since we did some cleaning of persistent data. i loaded your `35.bak` and it looks fine. if you delete the current `persistent` and rename `persistent35.bak` to just `persistent` you should be ok. i was showing 1296 affection when i used `35.bak`

**Comment by HiroyukiMisaki** [comment]
well, I just started the mod and it's new.

**Comment by jmwall24** [comment]
after you followed those steps?

**Comment by HiroyukiMisaki** [comment]
yep. the persistent is now okay. thanks a lot. the game was okay now too.
But yeah, tbh the first pic were kind of an issue to me from time to time (randomly) and I just restart the game again, it's just the lost persistent files kind of worried me for a moment here
Btw, thanks a lot. I hope I can contribute something in the future.

**Comment by jmwall24** [comment]
so you're back to where you were now with everything unlocked?

**Comment by HiroyukiMisaki** [comment]
![image](https://user-images.githubusercontent.com/47486655/56445245-341a4a00-6337-11e9-92a0-2fbfddd6c519.png)
yeeeeees owo
thanks a lot :'D

**Comment by jmwall24** [comment]
okay good. you're welcome. we'll look into why this happened in the first place.
