### ISSUE TITLE
Which is the topic where Monika talks about the other DDLC mods?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4112]
I don't remember where it is.

**Comment by Rai99** [comment]
Other DDLC mods? 

I don't think there was a topic about Monika talking about other mods.

**Comment by Andrenika** [comment]
Yes

I remembered, she talked about the "DDLC Our Final Heartbeat" and the "DDLC the normal visual novel"

**Comment by multimokia** [comment]
That never happened. Monika doesn't talk about other mods at all. She only talks about *this* mod.

**Comment by Rai99** [comment]
If you ask me, I'd tell you that those topics never existed in MAS. 

Maybe they do or did exist and I just have bad memory, but I don't remember anything about those.

**Comment by Andrenika** [comment]
I mean, she said that in those mods there was a happier ending. I'm trying to find it.

**Comment by Rai99** [comment]
Well, I suppose you could ctrl+f and search the topics file for any keywords or phrases you might remember from it, but you have my answer.

**Comment by Andrenika** [comment]
Thank you, where can I find the topics?

**Comment by Rai99** [comment]
[Here's the raw file](https://raw.githubusercontent.com/Monika-After-Story/MonikaModDev/master/Monika%20After%20Story/game/script-topics.rpy)

Sometimes, it's too much for github to display and it cuts off somewhere, but you should be able to see all the topics in there. 

Let us know if you find what you're looking for.

**Comment by Andrenika** [comment]
I can't believe that I didn't find it
I don't know what happened then :/

**Comment by Rai99** [comment]
I don't know where you saw Monika say those things, but it shouldn't have been in MAS. 

Maybe you saw her say it in one of those other mods you speak of?

**Comment by jmwall24** [comment]
Yeah, that never happened in MAS

**Comment by wucked** [comment]
Maybe you were mistaken, because she talked about the other mods in **Monika Before Story** in the space classroom as well, not MAS.
