### ISSUE TITLE
[Suggestion] - Telling Monika you can't sleep

### ISSUE THREAD

**Issue by OreoMurphy** [Monika-After-Story/MonikaModDev#4113]
I often can't sleep, but all I can tell Monika is that I'm tired. It'd be nice to be able to communicate this to her, rather than her thinking I'm not sleeping on purpose. I'd really like it if I could talk to Monika about my sleeping problems. Sorry if this has already been suggested!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
