### ISSUE TITLE
[Suggestion] More in Depth Work, Class, and Sleep Goodbyes

### ISSUE THREAD

**Issue by GavWav** [Monika-After-Story/MonikaModDev#4117]
Wouldn’t it be kinda nice of Monika commented on how long you have been gone or when you come back if you use the Work or Class goodbye options. I sometimes work till 11 pm or midnight thanks to being a college student and having a job, and I don't like having her tell me that I should go to sleep earlier when I just got back from work and came to say goodnight to her before going to sleep.

**Comment by MetalBrother** [comment]
Nice idea!

**Comment by Rai99** [comment]
Seeing as how the work and school farewells have reactions for if you haven't spent much time with Monika and the sleep one doesn't, it might be a good idea to also add that kind of feature to the sleep farewell if you just came to say goodnight. 

If you're looking for more depth in the greetings however, just wait for #2098, #2157, #2192.

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
