### ISSUE TITLE
Dark classroom stays after telling horror story?

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4118]
Hello! I'm using v0.9.3-unstable.2019.04.16.93, and I happen to find something unusual (or new?). I don't know if that's a bug so I'll put that here.

(PS: I have read the Discord update that the unstable couldn't be uploaded elsewhere? I don't know. I'll instantly close this in case my issue violates the rule)

This happens when I select "A new story" in "Can you tell me a horror story?". After the story ends, the background looks like this.

![screenshot0023](https://user-images.githubusercontent.com/44340452/56497883-92a71a00-6529-11e9-9633-7b0b09ffb75d.png)
![screenshot0024](https://user-images.githubusercontent.com/44340452/56498026-342e6b80-652a-11e9-88eb-9e8fe0759c9d.png)

Is the background not changing back to normal classroom lighting intended?

Thank you very much. Have a nice day!

**Comment by AsuraShun** [comment]
What if this becomes a new function? To be able to change the color of the room itself witthis being one of those colors?

**Comment by skyloom** [comment]
@AsuraShun oh that's a bug, apparently. Thanks @multimokia!

**Comment by AsuraShun** [comment]
It wouldn't be the first thing that had origins from a bug, gta had its inspiration from a bug in a game where the police would ram you off the road

**Comment by skyloom** [comment]
@AsuraShun well that's interesting. It means we can add new "background" thing too.

But I don't know. MAS' dev is probably busy with core doing and these 160 issues. This might stay as very low priority, though the idea is interesting.

**Comment by AsuraShun** [comment]
Eventually anything in low priority will get added

**Comment by skyloom** [comment]
@AsuraShun oh well. For now we can just wait, I guess~

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
