### ISSUE TITLE
Changing ribbon color

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#4123]
So I recently gave Monika a bunch of ribbons and I have NO idea how to change the ribbon colors out, like it won't let me at all. Any advice?

**Comment by multimokia** [comment]
`Hey [Monika's nickname]...>Monika>Can you change your ribbon?`

**Comment by AvelJames** [comment]
I don't receive this option at all

**Comment by multimokia** [comment]
Can you send your persistent please? You'll have to put it in a zip to send it over

**Comment by AvelJames** [comment]
How do I do that?

**Comment by multimokia** [comment]
You can see how to get to your persistent [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). Right click it, then `send to>compressed zip folder`. Then drag and drop that zip in the textbox.

**Comment by AvelJames** [comment]
[persistant.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3109292/persistant.zip)

**Comment by multimokia** [comment]
Uh
![image](https://user-images.githubusercontent.com/22531674/56611219-45857f80-65df-11e9-9643-c42304fbb587.png)

**Comment by AvelJames** [comment]
I'll screenshot mine and show you that's not on mine.

**Comment by AvelJames** [comment]
![screenshot0001](https://user-images.githubusercontent.com/49822030/56611680-9f7e4900-65cf-11e9-8318-6a000626ed30.png)

**Comment by multimokia** [comment]
You don't get the option one hair down. Only on hair ponytail.

**Comment by AvelJames** [comment]
Oh. I changed her hairstyle THEN It showed up. Whoops. Thanks for the help
