### ISSUE TITLE
ACS - Wearable: Twin Ribbons

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#4127]
#3174

Heya everyone, how are you doing tonight?
Sometimes we just gotta try something new!
Monika is not Monika without some kind of cute ribbon, so i thought I could make this hairstyle more interesting! They come in blue, pink and green (ah yes the 3 genders) and criticism is welcome! 
![ribbons!](https://user-images.githubusercontent.com/47725743/56696511-696dc180-66c2-11e9-9a32-126a4b518ad3.png)
![leaningbase twintails](https://user-images.githubusercontent.com/47725743/56696534-77bbdd80-66c2-11e9-8add-709902226b86.png)
ribon pngs in drive: https://drive.google.com/open?id=1h0bDKFK3YHC-tn3qDKvTxWRl9XRSHyf5

also you get to peek at a possible new table, tho its still a big work in progress.

**Comment by Chrissenpai** [comment]
... yep, it gets my seal of approvement, good job.

**Comment by softombre** [comment]
She looks like Miku and its super cute

**Comment by AsuraShun** [comment]
Except monika is cuter

**Comment by softombre** [comment]
I think both are equally cute in different ways

**Comment by Professor-JMO** [comment]
_Insert Miku Hatsune reference topic here._
> _Now that we have `Twin Tails`..._
>> Perhaps a new ACS or [ 2 ] is worth considering? 👀 
![Was this your childhood](https://user-images.githubusercontent.com/43480604/56749502-77195a80-6747-11e9-915a-8939a9038ffc.png)

**Comment by Rai99** [comment]
Sounds like a halloween outfit.

**Comment by Orcaramelo** [comment]
I love miku so moni is legally required to have that hair
Maybe i could make a miku outfit lmao

**Comment by Rai99** [comment]
You better include those accessories on each of Miku's twin tails.

**Comment by Orcaramelo** [comment]
I will dnsjkw i love them

**Comment by ThePotatoGuy** [comment]
are the twin ribbons usable in other hairstyles? if so, which ones?

**Comment by ThePotatoGuy** [comment]
this is being mvoed up

**Comment by ThePotatoGuy** [comment]
moved to 0.10.5

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
