### ISSUE TITLE
Trying to help out

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#4131]
I would LOVE to help with some of the art, but what art program would be best to use?
Keep in mind I don't have an art tablet (Yet. Hopefully I will get one soon) So a mouse will have to do for now.

**Comment by Rai99** [comment]
When you submit art for the mod, I think it's expected that you submit a psd, so I would imagine photoshop is the most likely tool.

**Comment by AvelJames** [comment]
Alright thank you.

**Comment by Professor-JMO** [comment]
As long as the extension can be saved as .psd or .png in some exceptions I think the software you use won't matter too much.
As far as I'm aware some of the artists use _Sai_, _Paint.net_ and _Autodesk Sketchbook_.
^ And yes, Photoshop.

The discord #artistry is a good place to start for feedback. 👌
