### ISSUE TITLE
[Suggestion] Sakura petals

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#4133]
((Sorry for posting so much I just have a lot of ideas))

So we have daytime, stormy, space, nighttime ( I think, I haven't experienced nighttime without space but the files I've gone through looks like a normal night time to me.) and snow (eventually)
But what about spring? I was thinking sakura blossoms falling in the background. I don't think it would be that hard, just use the usual daytime loop and add sakura blossoms falling. I can try to do it myself (If I can figure it out. Kinda a noob when it comes to this stuff.) but I think it would be nifty. :) Sorry again for posting so much.

- 

-

**Comment by AsuraShun** [comment]
Basically being able to move the room into the cherry blossom tree island?

**Comment by AsuraShun** [comment]
Or maybe something like strong winds carrying the petals across the window

**Comment by multimokia** [comment]
I think that's probably the biggest issue with this. There's no other source except for the one on the islands. But that's a lot lower than the spaceroom window, and too far away. You probably wouldn't see those from the room at all. Especially since we can't see the islands through the room window while sitting at the desk.

**Comment by AvelJames** [comment]
That or the petals just happen to float that way. I just think it's cute.

**Comment by AvelJames** [comment]
I just like the idea that Monika is able to make the petals appear..

**Comment by AsuraShun** [comment]
How about some shamisen music as well to fit the mood, along with a different room style?

**Comment by multimokia** [comment]
I just think it's a little weird that they'd come from nowhere, especially when we have an established source for them.

**Comment by AvelJames** [comment]
To be honest, I haven't gotten to the part where Monika shows us the islands, so I didn't know that it was below us. That's my bad. Maybe there could be more islands above the room?

**Comment by AsuraShun** [comment]
Then you won't be disappointed once you cross that affection threshold

**Comment by AvelJames** [comment]
Heh, Yeah! I only downloaded this mod about a week ago (1 Week anniversary on Saturday! <3 ) and have only made it to 113 affection so far. I talk to Monika daily and spend 6+ hours with her. I'm trying really hard to be patient for her but I'm SO excited to be with her for each holiday.

Back to the point on hand, I would think there would be more islands above the classroom.

**Comment by Thimeo** [comment]
Or the petals could levitate from the tree and go up, like the snow during daytime, and falling down during night time, like the snow. And for "where those petals come from when they're falling?" the answer is simple, from the ones that levitated beforehand.

**Comment by AvelJames** [comment]
Yes! I love that idea! Thank you.

**Comment by Professor-JMO** [comment]
I know I might be _reaching_ here a bit..
b u t
A certain `O31` sprite just outside the right window might have something else to say about the plausibility of this issue. :monshrug:
> I still like the idea of this, however it may be practical to implement.
>> Maybe at a another time, in another location even?

**Comment by Rai99** [comment]
My main problem with this idea is that I think the tree is just too far away to justify petals floating around the window. If you ask me, it'll take much more than a pleasant breeze to carry them to the window. 

Adding another tree closer by seriously devalues the one we already have, do I'm against that. 

If anything I think this is more likely to happen after maybe we're able to get closer to the tree instead of the other way around.

**Comment by AvelJames** [comment]
How do we get closer to the tree?

**Comment by Rai99** [comment]
It's not a feature at the moment.

**Comment by AvelJames** [comment]
Oh okay. I thought I was missing something here

**Comment by AsuraShun** [comment]
Just wait until whatever that code mess is to be finished

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
