### ISSUE TITLE
need leaning versions of witch hat and neko ears acs

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#4136]
#3174 

Currently we have upscaled versions of the witch hat and neko ears, but to use them as acs, we need leaning versions.

If you are willing to do this, comment that and I will send you the existing acs images we have.

**Comment by Professor-JMO** [comment]
_Lay it on me._

**Comment by ThePotatoGuy** [comment]
@Professor-JMO 
https://drive.google.com/open?id=1AYPtJ2eX5uSKY9ChzV0R6veHJOf1wM7U

**Comment by Professor-JMO** [comment]
[ _Finally_ adding to projects. ]

**Comment by Professor-JMO** [comment]
[ _Establishing **Link**..._ ]

@ThePotatoGuy , Let _mi_ know if there are any issues with these. 👌 
https://drive.google.com/open?id=1VrW7ZKXNCUcVoO3Bsmq7G2XYSxF67WRP

**Comment by ThePotatoGuy** [comment]
this has been completed at some point.

**Comment by ThePotatoGuy** [comment]
covered in #5330 and #6556
