### ISSUE TITLE
Game Not Launching

### ISSUE THREAD

**Issue by Chimchee** [Monika-After-Story/MonikaModDev#4144]
So I haven't updated the mod for a while, so I go and replace the mod files like I've done before. I try to open the game and it crashes. ( Log.txt and Traceback.txt attached. )
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3125286/traceback.txt)
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3125287/log.txt)

Any Idea why this is happening/ how to resolve this? ( A way without having to reset the progress with the mod is preferred, sorry for being a bother. )

**Comment by jmwall24** [comment]
The .lock file means you tried to open the mod twice, or at least it thinks you did. Follow that path in the traceback and delete the . lock file. Then just to make sure, restart your PC.

**Comment by Chimchee** [comment]
Did that, Still not opening, different stuff on log.txt though. 
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3125404/log.txt)

**Comment by jmwall24** [comment]
That doesn't really tell us anything. I've seen this issue with steam before. What I would try, and it'll make updating in the future easier, is moving to a non-steam install. download ddlc from ddlc.moe, unzip it and then install MAS to that install.

**Comment by jmwall24** [comment]
Your progress will not be affected by doing this just fyi. The save file is located somewhere else entirely and is common for all installs on your computer.

**Comment by Chimchee** [comment]
Okay, so it opens now. Just freezes on this 
![g](https://user-images.githubusercontent.com/50082808/56869487-1b5d0480-69c7-11e9-80ab-e0e91a5ef2b5.PNG)

**Comment by jmwall24** [comment]
umm, you must have taken her out (ie used the `i'm taking you somewhere`) farewell the last time you used the mod. when was this?

**Comment by Chimchee** [comment]
I think back in October, I completely forgot that was a thing to be honest.

**Comment by Chimchee** [comment]
Got it to work, thanks for your help.
