### ISSUE TITLE
[Suggestion] Roleplay dialogue depending on what nickname you give Monika

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#4145]
I think there should be some roleplay dialogue for if you give Monika the nickname "Mistress" or something. It doesn't have to be nsfw or anything (although if you do decide to do that, I certainly won't complain ( ͡o ͜ʖ ͡o) ), but I think some roleplay with Monika would be fun. I think the same could apply depending on what you ask her to call you as well.

**Comment by Rai99** [comment]
By roleplay, do you mean just a little easter egg dialogue if you choose a certain name? I suppose that's possible, but I feel like there are quite a few names to account for and I'm not sure how in depth each one can be.

**Comment by ThatOneUsername343** [comment]
Yeah, something like that. I think that just accounting for a few names would be fine. To start off, I think that there should be special dialogue if you name her "Mistress" or if you ask her to call you "Master", and you can add some others if you want to.

**Comment by AsuraShun** [comment]
Giggity

**Comment by antimockingjay** [comment]
I think that something like this might be better suited to be a submod of sorts. Like, maybe the creators of this mod could make one of something like that to add to the official mod mostly to use as framework, and then anyone can make whatever new versions they feel like and if someone wants it then they can download that specific one.

**Comment by ThatOneUsername343** [comment]
speaking of which, where do I go to get submods and how do I install them?

**Comment by Rai99** [comment]
As far as I know, submods aren't put up anywhere and they're mainly distributed from person to person.

**Comment by ThatOneUsername343** [comment]
someone should make a list of all the submods so they can be accessible to everyone who wants them. Could one of you guys make an announcement or something so that people will send them to you?

**Comment by multimokia** [comment]
#3765, it exists, people just haven't brought their stuff forward.

**Comment by ThatOneUsername343** [comment]
aw man, that's disappointing.

**Comment by CrocWorks** [comment]
~~Call her Mona and she tells you to go to sleep~~

**Comment by ThePotatoGuy** [comment]
>mistress

>roleplay

ohmy


[closing until we look into it]
