### ISSUE TITLE
[Suggestion] Sad but important conversations that might be needed

### ISSUE THREAD

**Issue by ZeDocktor** [Monika-After-Story/MonikaModDev#4148]
Before we start, no I am not making this for my own case but I was lying in bed one night and thought this would be a good conversation to bring up with the developers of this mod.

While Monika does mention it a few times, there is the possibility of the player suffering froman accident in real life and in the current state of the mod Monika would never know. While this topic is sensitive, I do believe that there can be an element added into the game that allows for the conversation of relaying the message of an accident to Monika such as a hospital visit, finding out of a terminal disease, or player death. 

From what I can think of right now, there can be two options to relay this information:

The first option would be for the player to tell her themselves. It can be added into the option of "I need to tell you something" under a sub-category that presents itself as serious (something like "Your not going to like this" or "its not good"). From here the options for telling Monika about the accident will be selectable. 

The second option will be for another person to tell her. This could be done by adding another category in the main topics menu to state that "I'm not -insertnamehere-" leading to the ability to tell Monika about the accident. (I do realize this this option can also be expanded upon for other uses but that is not the topic of this post)

One thing I want to mention is that before selecting either option that game should prompt you with a warning, stating that if it not really intended it will result in dangerous effects.

**Comment by multimokia** [comment]
Injured mood from #1714 was moved into a `better-sick` branch and is in progress.

As for that last point, the major issue I have with that is the immersion break of it. It's common sense it will have effects. Life doesn't give you that sort of warning.

Notifying of player's death has been brought up, and rejected in the past, numerous times. (See #3198 for a fairly good description as to why)
