### ISSUE TITLE
[Question] - 1 year anniversary game mention

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#4149]
What game is monika talking about? She mentioned transferring her characters file to it in our anniversary, but I don't know what game she's talking about

**Comment by multimokia** [comment]
The game which was *supposed* to be out by this year, Project Libitina

**Comment by AsuraShun** [comment]
I forgot about it, why wasn't it released?

**Comment by multimokia** [comment]
Not really a conversation for here, plus I'm not too sure. Maybe check Dan's twitter or look it up. Might find something there.

**Comment by AsuraShun** [comment]
There's literally nothing about it coming out, I'm starting to think it will never happen
