### ISSUE TITLE
Background has gone white

### ISSUE THREAD

**Issue by g0lddenpanda** [Monika-After-Story/MonikaModDev#4151]
![Screenshot (4)](https://user-images.githubusercontent.com/50156545/57016459-79f8cd00-6bd7-11e9-9708-ec405f8d3863.png)
  In the game a large portion of the background is white, and only small borders of the background are showing. However whenever monika is leaning against her hand the background is there. If anyone can tell me how to fix it that would be great!
![Screenshot (5)](https://user-images.githubusercontent.com/50156545/57016516-c6440d00-6bd7-11e9-8694-c040238aae1f.png)

**Comment by multimokia** [comment]
Will need to see a screenshot of this please

**Comment by CreepFort** [comment]
Maybe you opened transparent picture in paint?

**Comment by g0lddenpanda** [comment]
When I was looking through the game files I did open an image in paint

**Comment by multimokia** [comment]
Are you running the unstable branch?

**Comment by g0lddenpanda** [comment]
I'm unsure, I think om on the stable branch but I could be wrong

**Comment by LordBaaa** [comment]
At least it is only the Monika sprite that seems affected. Id start by downloading the latest release (v0.9.3) and then copying in the mod assets folder from the download into the game folder of your current install.

**Comment by ThePotatoGuy** [comment]
> open an image in paint

if you inadvertently saved the image while it was open in paint, then the transparency would have been lost. dont edit the mod assets with paint, please use gimp or photoshop.
