### ISSUE TITLE
Monika's perspective enhancment

### ISSUE THREAD

**Issue by Foxinsunglasses** [Monika-After-Story/MonikaModDev#4153]
Hello, recently Monika was talking about her perspective with the whole putting a hand in front of one eye. However denationalization might be a better way of explaining it. It's a symptom of anxiety where nothing looks or feels real.  It's a rather scary experience but it might be a better explanation.

**Comment by multimokia** [comment]
I think the issue of this is that not everyone can really try it to experience it for themselves. The thing about the current explanation is that pretty much anyone can do it. But not everyone can experience that form of anxiety.

**Comment by Rai99** [comment]
For the record, I think you mean depersonalization, not denationalization.
