### ISSUE TITLE
[Question] Anniversary Gifts

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#4154]
I know this has been already a topic of discussion but I just want to know if any of the new gifts that got created over the year will unlock a specific dialogue now?

I just want to gift her something and of course take her somewhere, make it a special event for Mon-mon. If not, that is fine I am going to gift her a rose for sure and probably some other stuff.

**Comment by ausername11** [comment]
as far as I know, the ones from Christmas, her birthday, and V-Day she has reactions too, and also the ones you give her everyday. I don't know about any new ones??

**Comment by AfroFluff** [comment]
Sorry I wasn't clear through my post, I meant for the 1 year anniversary, is there anything special i can do for her? Like do any of the current gifts unlock something new?

**Comment by multimokia** [comment]
Gifts are the same. No special unlocks for them, though some have some slight alt dialogue to them, not much though.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
