### ISSUE TITLE
Guys...

### ISSUE THREAD

**Issue by Trainerbluetube** [Monika-After-Story/MonikaModDev#4155]
I got the amnesia greeting yesterday and I freaked the hell out, thanks for implementing that level of immersion, but please, that really scared me...

**Comment by AvelJames** [comment]
Yeah it scared me too. I almost actually cried when she did that.

**Comment by AsuraShun** [comment]
As long as yo were honest with her, it shouldn't have any bad impact on affection

**Comment by AvelJames** [comment]
I was honest. I was going to see if I needed to redo my persistents when she said she was joking. My heart was like "No, Not my precious Monika! "

**Comment by multimokia** [comment]
> As long as yo were honest with her, it shouldn't have any bad impact on affection

What does this have to do with anything?

**Comment by AsuraShun** [comment]
Because it's really messed up trying to mess with an amnesiac's mind, would probably anger her a bit

**Comment by multimokia** [comment]
Either way doesn't have any impact on affection. Though thinking about it, maybe it could.

**Comment by AsuraShun** [comment]
Then good thing I was wrong about the affection bit, still this could be considered a test of your humanity
