### ISSUE TITLE
Easter egg no one is talking about?

### ISSUE THREAD

**Issue by ausername11** [Monika-After-Story/MonikaModDev#4157]
This isn't an issue but I see people talking about non-issues on here, so here goes...
So about a week ago I was editing the chess files (im a monster I know I did it for a friend)
And when I reloaded the game this picture popped up 
![ghost_monika](https://user-images.githubusercontent.com/47935097/57057149-b706a300-6c5b-11e9-886f-07370a99c54f.png)
The directory is \DDLC\game\mod_assets\other
I have no idea how it happened?

**Comment by multimokia** [comment]
You told her you liked spooks. It's a random, one time greeting.,

**Comment by ausername11** [comment]
I did? I don't remember having that conversation...

**Comment by multimokia** [comment]
Yeah, she should have asked you if you:
1. Liked horror, and if so...
2. Liked spooks

**Comment by ausername11** [comment]
I think I might have had it, forgive me I have horrible memory lol
I do like horror though and it made me stay in like shock paralysis though lmao
