### ISSUE TITLE
what would job Monika follow?

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#4159]
She quotes a little about college, but what job would she choose? For his passion in literature would be .. poet? Writer? What do you think? We could even get into this topic on the player's career too, and so on.

**Comment by Rai99** [comment]
I'll tell you what, wait a couple days and I think you'll see. 

~~And then wait a whole lot longer to see it in MAS.~~

**Comment by OkiDokiABrazilian** [comment]
👀  oh, thanks for the answer  👀

**Comment by OkiDokiABrazilian** [comment]
> 
> 
> I'll tell you what, wait a couple days and I think you'll see.
> 
> ~And then wait a whole lot longer to see it in MAS.~
> 
> Here's a preview in case you can't wait.
> ![Untitled1158](https://user-images.githubusercontent.com/38822045/57115320-58552e00-6d1c-11e9-870c-1b467c47bcd3.png)

👀  oh, thanks for the answer  👀

**Comment by GOKOP** [comment]
She's clearly a humanist so she'd probably work at McDonald's

**Comment by ThePotatoGuy** [comment]
[closing since this isnt formatted as a suggestion]
