### ISSUE TITLE
Chibika plushie

### ISSUE THREAD

**Issue by DjSquishy777** [Monika-After-Story/MonikaModDev#4162]
Possible new gift for Monika, like the Resplendent Quetzal~
Maybe she'll find it a bit weird or think it's very sweet? maybe both idk.
I just put mine on my head and was like "Woah! That'd be cool gift for her~"
Apologies if I'm not making sense, I'm pretty sick.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
