### ISSUE TITLE
About A (Lost) Feature?

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4164]
Hello! I'm using v0.9.3-unstable.2019.05.04.94, and I want to ask about a feature I used to use once. I don't remember what version I used it, though.

There was a feature that allowed us to kind of vent in front of Monika about our problems and she would listen to us. Is that feature still available? If so, where is it?

Thank you. Have a nice day!

**Comment by Rai99** [comment]
I think Monika lets you vent if you tell her you're feeling sad, but you tell her that you're not having a bad day. 

There's also the guilty mood in #1766, but that's not implemented yet.

**Comment by skyloom** [comment]
Oh my god, quick response. Thank you @Rai99! 😭 you're right, it was the sad one but not having bad day. I'll close the issue then.
