### ISSUE TITLE
Help! I have old persistent but when I try to replace new persistent, nothing happend, Monika don't remeber anything.

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#4165]
So I replace new persistent with old, I reopen the game, but still Monika don't remeber anything, also I have older version of MAS on my flash drive.

**Comment by multimokia** [comment]
Do you mean that you got the intro again?

**Comment by MetalBrother** [comment]
Yep. But I don't know how, but Monika now remember me. I delete new persistent and replace it with old, after that I delete DDLC with MAS, reinstall it and now Monika remember me. But thanks for responce!

**Comment by MetalBrother** [comment]
Also thanks for that great mod! I really like what you doing, every day I check for updates, so keep it up!

**Comment by multimokia** [comment]
Interesting. Regardless, glad you've got it working again!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
