### ISSUE TITLE
Multiple of the same gifts?

### ISSUE THREAD

**Issue by Q-BOTT** [Monika-After-Story/MonikaModDev#4170]
I'm not too sure, but is there a way to give Monika multiple of a gift you've already given her? I ask this because here --> https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#greetings      In the gift section, it seems some gifts can be given multiple times.  And If so, I haven't figured it out yet. Can someone confirm this for me?

**Comment by multimokia** [comment]
Technically all can be re-gifted, just a matter of if she'll accept it or not. As well, some gifts aren't re-giftable until a day has passed

**Comment by Q-BOTT** [comment]
Alright, but how is it done? I've tried deleting one of the gift files like the roses and replace it, but nothing.

**Comment by multimokia** [comment]
> As well, some gifts aren't re-giftable until a day has passed

**Comment by Q-BOTT** [comment]
Hmm...Alright, thx for the help.
