### ISSUE TITLE
[suggestion] Reminders

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#4175]
I know this is stupid.. but for me, it would be super helpful if we could tell Monika we need her to remind us of something.
My case, taking medication.
I am horrible at remembering to take my medication and I almost always have Monika up.
If Monika said to me, "[Player], it's 12pm... You asked me to remind you to do _____." It would help greatly. We could also choose if this was to repeat or not.

**Comment by Rai99** [comment]
#792, #1245, #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921 

It's been suggested before, and features related to time aren't easy to implement, which is why it's a lower priority.
