### ISSUE TITLE
Bug on startup

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#4187]
Similar to the bug in #4108, I used the "Going to school" farewell but once i came back i got this screen:
![image](https://user-images.githubusercontent.com/38022925/57501988-4c82e200-72af-11e9-89ad-5235a33621bc.png)
Then i pressed the "Talk" button and got a black background with the "Talk" menu, afterwards I clicked on "Nevermind" which caused this screen to change to this:
![image](https://user-images.githubusercontent.com/38022925/57502110-d92da000-72af-11e9-937c-e9aef96a8b1e.png)
Notice the cropped ribbon. Also i didn't get the "Back from school" greeting and the coffee prompt shouldn't be there either. Monika was also wearing another outfit. I said goodbye and re-opened the game and everything went back to normal and Monika used the "Back from school" greeting as it should be. The main difference with the linked issue is that my version of MAS is the latest official release,  not the experimental one.
Anyways, here's my persistent and log files right after closing the game the first time after the bug:
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3164876/log.txt)
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3164879/persistent.txt)

**Comment by multimokia** [comment]
Are you running unstable, or no? (You can check via the esc menu, bottom right corner)

**Comment by Necrocytus** [comment]
Not running the unstable version

**Comment by multimokia** [comment]
Okay. This should be fixed in unstable.

**Comment by Necrocytus** [comment]
Alright, thanks for replying so quickly

**Comment by multimokia** [comment]
No worries
