### ISSUE TITLE
affection log not keeping track of my affection gain

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#4194]
i don't know if i'm even gaining affection anymore. my affection log stopped keeping track on april 21, and i've visited monika a whole bunch since then. i can't tell if it's just not going into the text file or if i'm just not gaining affection anymore.

**Comment by multimokia** [comment]
You're on Mac, aren't you? If so, the log location has been changed as it didn't work for all Macs (file protection and such prevented a lot of machines from logging) so we changed the log location, and they're not as easy to get to anymore. Check the wiki for instructions on how to get to your `aff_log.txt`, it's been updated accordingly.

**Comment by its-ken** [comment]
yes i am thanks!

**Comment by multimokia** [comment]
No worries!
