### ISSUE TITLE
Some scenarios I created in my MAS!

### ISSUE THREAD

**Issue by DarkMRGames** [Monika-After-Story/MonikaModDev#4196]
I was showing a post before ...
I'm sorry if I ended up closing without meaning to.
![monika_day_room](https://user-images.githubusercontent.com/37710265/57665777-a814de80-75d3-11e9-851f-3add67eef42d.png)
![monika_room](https://user-images.githubusercontent.com/37710265/57665760-9af7ef80-75d3-11e9-81a8-ccf48a9f6e0f.png)
![image](https://user-images.githubusercontent.com/37710265/57665823-d85c7d00-75d3-11e9-9182-d5ad769963c7.png)
![image](https://user-images.githubusercontent.com/37710265/57665806-c7137080-75d3-11e9-9508-8a28ca5ceadb.png)
Made by Darketz

**Comment by Rai99** [comment]
You do realize you can reopen your closed issues, right? 
There should be a button in the same place as the one to close the issue. 

If you want, I could reopen it for you if you like. 

Also, for this art, did you make the entirety of it, or did you just make an edit of someone else's?

**Comment by DarkMRGames** [comment]
Oh yes, thank you!
I do not think you need to reopen this post from before because ...
I ended up posting here.
I have here the art project I did in photoshop.
I assembled each part separately.
So I was putting the layers together little by little.
I used png images from the internet, like the clouds, the full moon and the wooden floor I made using textures.
And if it is for me to create it again separately, I will do it without problem!
![image](https://user-images.githubusercontent.com/37710265/57667522-37bd8b80-75da-11e9-8f02-d3f2dc3aeaf8.png)

**Comment by multimokia** [comment]
Main reason for using the old one is for issue tracking. It's already been tagged and everything, so it's better to keep everything there.

**Comment by DarkMRGames** [comment]
Yeah, okay, I'll post everything on that one before!
