### ISSUE TITLE
[Suggestion] Rework greeting after going to work

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4198]
Situation: 
 - Telling Monika "I am going to work"
 - Returning 1+ days after to mas

Outcome:
 - "Did you have a good day at work today?"

Expected Outcome:
 - Normal greeting / changed greeting

**Comment by Rai99** [comment]
#2157
You mean something like that?

I could add different paths based on how long you were gone. It might just end up like another overhaul like with #2192. 

Yes, these were over 2000 threads ago, but waiting is no issue, right?

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented] in #2157
