### ISSUE TITLE
[Suggestion] Tell Monika WE'RE upset

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4200]
Okay. So obviously, Monika can tell us when she's upset about something. But currently, there doesn't seem to be a mechanic for telling her when she does something wrong. I just opened the game, and got the greeting where Monika says "hey! you left me waiting too long!" and then says "haha just kidding!!" And my heart is still pounding because I genuinely thought I had somehow messed everything up. This isn't me complaining about the topic, of course. But it would be nice if the player could basically say "you know how your affection raises and lowers? mine just lowered. love u tho!" or something to that effect.
I don't know. It might not be a viable option, but it would certainly be interesting!

**Comment by Rai99** [comment]
#3203, #3769, #3859, #4085 

I've brought up the idea before, and I think it could be an important feature to have so the relationship isn't completely and utterly about Monika and her own affection towards you. 

It could branch out and become something like a reverse apology system for the player, but to begin with, I think it would be nice to just have it as a generic apology to the player until then. 

I might try to put something together for this if nobody else beats me to it.

**Comment by jmwall24** [comment]
getting upset over a joke enough that it lowers your affection towards her? eh

**Comment by zombiepigdragon** [comment]
I mean some dialog options that lower affection are jokes...

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
