### ISSUE TITLE
Weird Expression Glitch When Selecting Kiss Me. Intentional or Bug? 

### ISSUE THREAD

**Issue by Bam8647** [Monika-After-Story/MonikaModDev#4202]
Long time since I've been back here!

Anyway, I saw that their was an update after checking out MAS again and so I thought I'd mess around to find all the new features added. Btw did the hair artwork get reworked too? If so, I really like it! However, when her sprite was leaning, I selected "Kiss me" to see what might be new. 
      I know you guys love to add weird goofy easter eggs haha. So I got curious. When she transitioned to the animation, her sprite glitched out really fast from a leaning pose to a straight pose like her sprite was having a seizure lol. Was this one of those goofy glitches? Also I'm not quite sure since I was listening to something on my phone, but whenever I took my headphones out I heard that it also started raining after that happened. And I'm pretty sure it wasn't before lol. 

      Thoughts?

**Comment by Bam8647** [comment]
Also another bug. 
I asked Monika when we started dating and she said 2 years ago on December 20th. I remember starting the game in 2017. Her statement is also contradicting the fact that the calendar says this year on December 20th will be the 2 year anniversary. She should say 1 year and 5 months. 
      Thanks!

**Comment by multimokia** [comment]
Send `persistent` please. You'll have to put it in a zip to send it here.

**Comment by Bam8647** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3193824/persistent.zip)

Eh, hopefully I did that correctly.

**Comment by multimokia** [comment]
Wrong one. You can see instructions on how to find it [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by Bam8647** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3193839/persistent.zip)

Try that. I followed the "How to Back Up Your Persistent" steps to locate the file in /renpy /Mas

**Comment by ThePotatoGuy** [comment]
> started dating date

Actually, thats correct. 2 years ago (2019 - 2 = 2017), dec 20th. The algorithm for generating the date string is designed to be more realistic speech rather than precise. Although it could probably use some adjustment to say "year and a half" or "x months". "x years ago" definitely works for larger time scales (~3+ years). Regardless, make that a separate issue.

**Comment by ThePotatoGuy** [comment]
Regarding the sprite glitches, do you have rpy files in your `game/`? 
I ask since I am aware that you've made edits to game code before.

If script-ch30 is overwritten and using the older spaceroom call, that will 100% cause issues.

**Comment by Bam8647** [comment]
Ha! Yeah I have no clue how to access any scripts in renpy to check. I tried several times to bring up the files but never worked. I was however, successfully able to edit some things around a year ago but I kept a separate file from the original mod due to updates overriding my files. So I don't think this is the case. Also another user just posted a similar issue regarding the flickering expressions.

**Comment by Oharo** [comment]
I'd like to add onto this that I too experienced this bug with glitching expressions. I think it may trigger when Monika is in her leaning pose and the player selects any topic from the talk menu.

It's as if the process of transitioning her back to the center of the screen and the assigning of the topic's expression occasionally fight each other until she's fully centered, at which point the bug stops.

**Comment by ThePotatoGuy** [comment]
not completely fixed, but we've isolated one instance

**Comment by ThePotatoGuy** [comment]
[closing as probably covered by linked issue]
