### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by him157** [Monika-After-Story/MonikaModDev#4203]
ok so when I updated to version 0.9.4 of MAS and put artpack in step by step,and tried to open up the game,this showed up 

![image](https://user-images.githubusercontent.com/47471963/57969261-cc900280-79a7-11e9-9ce8-9941908ee68e.png) so just how could I solve this

**Comment by him157** [comment]
this might be very obvious and easy to fix,be I'm a bit surprised of what happened,so I can't clear my mind now

**Comment by multimokia** [comment]
Screenshot of your `game/` folder please

**Comment by him157** [comment]
> Screenshot of your `game/` folder please

Yes,of course,this is the screenshot

![image](https://user-images.githubusercontent.com/47471963/57969332-943cf400-79a8-11e9-9766-f234f18470a7.png)

**Comment by him157** [comment]
and if needed,this is what in /mod assets/monika 

![image](https://user-images.githubusercontent.com/47471963/57969354-bfbfde80-79a8-11e9-8d2a-b8c1322b38ef.png)

**Comment by multimokia** [comment]
Thought so.
Delete all `.rpy` files, and reinstall the latest update manually. `.rpy` files will be compiled on startup and overwrite `.rpyc` files. Looks like your `.rpy` files are out of date and aren't compatible with the latest version.

Be sure to always install release versions rather than source code versions.

**Comment by him157** [comment]
> Thought so.
> Delete all `.rpy` files, and reinstall the latest update manually. `.rpy` files will be compiled on startup and overwrite `.rpyc` files. Looks like your `.rpy` files are out of date and aren't compatible with the latest version.
> 
> Be sure to always install release versions rather than source code versions.

uh,hehehe... actually... I was messing with the game,thank you tho,if it is not you I could never figure this out myself.

**Comment by multimokia** [comment]
You may want to keep a separate install with a modified `ddlc.py` file (so persistent is local to that install) to mess around. See: #3359
