### ISSUE TITLE
[Question] How do I get the new accessories in game?

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#4204]
I downloaded the art pack just as the wiki says and I just don't know how to get those to appear in game. Is it random or can we ask Monika to change her accessories? Do you have to have the "Love" level of affection or something?

**Comment by AsuraShun** [comment]
I want to know as well

**Comment by AsuraShun** [comment]
Figured it out, just make a file named either musicnotehairclip.Gift, hearthairclip.Gift or cherryhairclip.gift

**Comment by AsuraShun** [comment]
You already know where to put gift files

**Comment by moonstne** [comment]
just an extra note, having mas open while adding the new files, makes her unable to recognize the gifts. So make sure to add the files while it's not running, or restart the session.

**Comment by AsuraShun** [comment]
You named the gifts wrong, I gave them with mas open and she recognised them

**Comment by Andrenika** [comment]
She said she can't recognize the file

**Comment by ThePotatoGuy** [comment]
make sure to read [wiki[(https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs)

[closing as resolved].
