### ISSUE TITLE
Monika Cloned/Flickering Poses

### ISSUE THREAD

**Issue by llll828** [Monika-After-Story/MonikaModDev#4206]
Had left the game running while taking a nap with auto forward off, then after waking up, went thru the dialogue that was up. The weather was currently raining in-game, so I wanted to change it to something nicer to fit the irl weather. After selecting "Can you change the weather for me?", before the choices of weather appeared, a second Monika appeared in the middle of the screen, next to the normal question position one, and both quickly went thru several of the poses. The weather had also changed to the normal/clear before my input.

Most likely has something to do with the new "progressive" weather option, which I assume takes affect after Monika starts saying a new message after the weather is set to change, similar to how the day/night cycle works in game.

**Comment by Bam8647** [comment]
Same thing happened to me whenever I chose the "Kiss me" dialogue. I think multiple animations are trying to take place at once because I noticed it starting to rain right in between the kiss animation. Her sprite flickered for me too.

**Comment by ThePotatoGuy** [comment]
leaving talk menu does some things. pending investigation

**Comment by ThePotatoGuy** [comment]
actually closing this in favor of #4202
