### ISSUE TITLE
Need Assistance: New Hair Clips Download not Working

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4207]
I don't know where to put the artpacks file for the hair clips. Also, does it need to stay in the Winzip format or can I change to windows file because I don't have winzip on my computer?

**Comment by Silvery55** [comment]
Here's how you add the Hair clips. first take the mod_assets folder from the art pack then at the ddlc directory move that mod_assets to the games folder now
Before you open the game go to the character folder make a text file for each hair clips:
cherryhairclip.gift
hearthairclip.gift
musicnotehairclip.gift
And that how you add them hope this helps

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
