### ISSUE TITLE
Offering myself for new posses of Monika

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#4209]
I think now I've mastered the color art
https://imgur.com/a/ukcDyvG
Can now contribute with portraying Monika from off the table and anywhere on the room and even outside of it, just ask me and in due time I'll do it.

**Comment by Delcos** [comment]
well done

**Comment by LordBaaa** [comment]
Great work! It would be nice to have her sitting at a piano. I have a model I was planning on adding in the room as a sprite. Also monika standing with legs would be cool and a behind view (like her facing away from you).

**Comment by ThePotatoGuy** [comment]
[closing, but we'll keep this issue on file incase]
