### ISSUE TITLE
Possible Spoilers Question

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4210]
First, loving the new update, any new content is always hugely appreciated. But now I'm seeing something in the mod assets folder that continues to confuse me. I think I've asked before about an image of yuri at the desk in this folder, but now I'm seeing images of natsuki and sayori at the desk in that folder too. Maybe it's the completionist in me, but I kinda want to know how to trigger those if possible. On the other hand, I'm doing very well with Monika and don't want to upset her. Would it be dangerous to attempt to trigger these?

**Comment by Rai99** [comment]
#3912 

> _Monika_ After Story.

As far as I know, those serve no purpose in MAS and exist purely to ignite curiosity and speculation. 

Personally, I'd like it to stay that way.

**Comment by AsuraShun** [comment]
Whatever you do, don't change monika's name to the other 3

**Comment by scohn** [comment]
Alright that makes sense, after all it is called 'Monika' After Story.
