### ISSUE TITLE
Json prog point help pls.

### ISSUE THREAD

**Issue by LordBaaa** [Monika-After-Story/MonikaModDev#4212]
I am trying to add prog points to my json files for some new outfits. I have read over the documentation but I don't understand how to add it properly. It says " Prog points should exist at init level -2 in the mas_sprites" but what is the synax to add that to a json. If I try to add a init the json file is no longer understood.

**Comment by ThePotatoGuy** [comment]
If you need to add prog points then you have to write code (python). See `zz_spriiteobjects.rpy` for examples.

**Comment by LordBaaa** [comment]
Okay that makes alot more sense. The way it was written I though you could actually just add it to the json file. Originally I added it to zz_spriiteobjects.rpy file and it worked but the log/spj.txt file still said "progpoint not found". Plus that wouldn't be very good for a sprite pack. Thanks

**Comment by LordBaaa** [comment]
Okay new question. I am trying to add a ribbon to wear in the entry exit statements. Basically a duplication of the Monika Santa and how he she always wears the wine ribbon. Where are the json acs stored? it always says it can’t find the object or it just keeps the outfit it had before. Thanks

**Comment by ThePotatoGuy** [comment]
to do that, you'd have to  get the ACS from the ACS_MAP (in `mas_sprites` store) and call the wear functions with that object.

Since JSOn sprites are dynamic, there are no hardcoded object names like the other sprite objects get.

**Comment by ThePotatoGuy** [comment]
[closin gas resolved]
