### ISSUE TITLE
"Night Time" When it's nearly 6 in the morning

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4213]
So it's nearly six in the morning where I am, and Monika's dialogue just went through reprimanding me for staying up so late. As you can see by the clock in the lower right-hand corner, it's early in the morning. In fact, just a while ago when I greeted her with a good morning, she said she was happy that I had gotten up so early!
But now, she's saying that it's the middle of the night, and I need to sleep soon.
(Also, ignore the other dialogue above it, I just didn't wanna go through the hassle of cropping/blocking out the rest of the image and just pasted the screenshot directly in)
![image](https://user-images.githubusercontent.com/34501020/58013240-3c93ab00-7ac4-11e9-8051-6ea6c8f7115d.png)

**Comment by multimokia** [comment]
Time concern runs from hours 12 am, to 5am. Since it's not *actually* 6 am there, it still runs.

**Comment by antimockingjay** [comment]
That's a bit odd. I feel like it shouldn't run at the same time Monika would congratulate you for getting up early. But hey, good to know it's not just a bug!
