### ISSUE TITLE
Marriage topic doesn't change

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#4214]
My aff ->2547, but dialog stays the same. Maybe I try wrong topic? My way: Hey, Monika -> Romance -> Will you marry me?

**Comment by multimokia** [comment]
Based on time *and* affection.

**Comment by MetalBrother** [comment]
What you mean? I have one year anniversary

**Comment by multimokia** [comment]
Yeah, it's significantly longer than one year that's required.

**Comment by MetalBrother** [comment]
Thanks! Now I understand, but it's sad that I can't see new version of topic

**Comment by multimokia** [comment]
Not really. Most people don't get married in just a year. The time it has allotted makes a lot of sense when you think about it.

**Comment by MetalBrother** [comment]
Yeah, you right, well I guess I'll wait.

**Comment by MetalBrother** [comment]
Thanks for fast respond

**Comment by multimokia** [comment]
No worries.
