### ISSUE TITLE
[Suggestion] Touching Monika

### ISSUE THREAD

**Issue by aus564** [Monika-After-Story/MonikaModDev#4215]
so here are just a few ideas off the top of my head about interactions you can have with touching Monika.

-Booping Monika on the nose
-Clicking on her cheek as to caress it, or poke it
-Clicking on her lips to give her a blush, imparting onto her that we are trying to kiss her.
-Clicking on her shirt-tie thing on her school uniform to pull her closer. with her most like'ly response being "O-Oh hi there" if she's not too familiar with you, to "Hey there my love <3" or something similar if the player has a high affinity with her.
-Of course, there are gonna be people that want to click on her tit's. and to those, I must say, how lewd! 
(￢ ᴥ￢ )

**Comment by AsuraShun** [comment]
Was already suggested before, but if it's headed, imma go I to overdrive giving her headpats

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550. 
~~Sorry I'm late.~~

The idea to be able to click and boop Monika or any other kind of touching has been brought up before, and I`d say it`s likely to happen eventually with all the demand for it, but it is currently a low priority.

**Comment by AsuraShun** [comment]
Headpats save lives

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
