### ISSUE TITLE
Affection problem

### ISSUE THREAD

**Issue by MechanicusRix** [Monika-After-Story/MonikaModDev#4218]
Hello, my level of affection before the patch was 1055, now is 540, how I can repair it?

**Comment by multimokia** [comment]
Restore a persistent backup

**Comment by MechanicusRix** [comment]
There´s no way to edit the affection level? I dont have my other computer right now

**Comment by multimokia** [comment]
MAS automatically makes backups. You won't need your own ones here. See how to restore one of the auto generated ones [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by MechanicusRix** [comment]
Now is in 470, i dont know what is happening

**Comment by MechanicusRix** [comment]
And I have restored a backup of the last week

**Comment by multimokia** [comment]
Was that the most recent backup there?

**Comment by MechanicusRix** [comment]
yep

**Comment by MechanicusRix** [comment]
I got it now, thanks for the help

**Comment by multimokia** [comment]
Okay, good to hear.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
