### ISSUE TITLE
[Suggestion] - Monika Apologizing to the player

### ISSUE THREAD

**Issue by depressedjoanna** [Monika-After-Story/MonikaModDev#4221]
Monika often messes with the subject a _little_ sensitive to me, and I guess I'm not the only one to think so. What do you think of an option to tell Monika that you hurt her somehow and she apologizes?

**Comment by Rai99** [comment]
#3203, #3769, #3859, #4085, #4200 

The idea has been brought up before, and may be coming in a later update.

**Comment by AsuraShun** [comment]
There's the insensitive comments topic and the sensitivity mode to change that

**Comment by depressedjoanna** [comment]
@Rai99 oh! sorry about that...
