### ISSUE TITLE
Monika after story earrings

### ISSUE THREAD

**Issue by SoulReapers** [Monika-After-Story/MonikaModDev#4222]
I feel like giving Monika earrings as an accessory would be a great feature for Monika After Story

**Comment by multimokia** [comment]
If people are willing to make and submit them, then sure. Would be easy to add via json sprites.

**Comment by Olliesama** [comment]
Think I have the files still for this.
https://streamable.com/rirod

**Comment by multimokia** [comment]
Rip blinking

**Comment by Rai99** [comment]
Is that a body pose 5 with no dissolve

**Comment by ThePotatoGuy** [comment]
as mentioned, we are not pursing this ourselves, but are open to spritepack submissions
