### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DankeyMaliten** [Monika-After-Story/MonikaModDev#4226]
So Monika randomly wanted me to hold her and I did, afterwards she said that I can do it any time, and all I need to do is ask. So I went to find where that would be, I checked "Monika" "Romance" "Misc" basically everything even the repeated topics versions and I can't find the button to ask her if I can hold her again. Does anyone know where it is or is this some kind of glitch?

**Comment by Rai99** [comment]
It should be under `Hey, [m_name]... > Monika... > Can I hold you?`

**Comment by DankeyMaliten** [comment]
![Screenshot (327)](https://user-images.githubusercontent.com/47207309/58217984-36274e00-7cd3-11e9-853d-f8ca76d6f1c6.png)
Yeah it's not there.

**Comment by multimokia** [comment]
visit the sounds of rain topic

**Comment by DankeyMaliten** [comment]
It's there now, thanks!
