### ISSUE TITLE
Monika greets in French and Japanese

### ISSUE THREAD

**Issue by MansaSakura** [Monika-After-Story/MonikaModDev#4228]
And so, as I am learning French and Japanese, and she talks about practicing the languages together, is it possible to tell her indeed I can speak those?

**Comment by multimokia** [comment]
Technically you already can. At some point in the beginning of the mod she asks if you can speak other languages, asking if japanese/if not japanese, anything else.

**Comment by MansaSakura** [comment]
Specifying French is because of her greeting, is it possible to change the answer (as I cannot speak Japanese before).

**Comment by MansaSakura** [comment]
> Technically you already can. At some point in the beginning of the mod she asks if you can speak other languages, asking if japanese/if not japanese, anything else.

Specifying French is because of her greeting, is it possible to change the answer (as I cannot speak Japanese before).

**Comment by multimokia** [comment]
`repeat conversation>misc/you>Speaking Japanese`

**Comment by MansaSakura** [comment]
> `repeat conversation>misc/you>Speaking Japanese`

With my deep thanks.

**Comment by Hyper-Miiko** [comment]
Another thing will be a good idea :
Tell her about us native language...
I'm french, so when she ask me if i can speak another language than english is pretty silly^^
