### ISSUE TITLE
how to install sprite packs on mac?

### ISSUE THREAD

**Issue by pericopter** [Monika-After-Story/MonikaModDev#4229]
I tried to install the sprite pack into the 'game' folder like the guide says, but my mac is telling me to either replace the current mod_assets folder. I think that folder is essential so I don't want to, and it won't let me keep both. Any tips or ideas?

**Comment by multimokia** [comment]
Does it not allow you to merge the folders? If not, you'll have to put everything in the corresponding filepaths (as they are in the zip) in your install, manually.

**Comment by pericopter** [comment]
so do I put the contents of the sprite folder into the main one?

**Comment by multimokia** [comment]
wherever the actual files are in the zip, they should go in your install.

**Comment by pericopter** [comment]
sorry, I'm kind of confused here. If you don't mind, could you help me out?

**Comment by multimokia** [comment]
Example: the `.json` files in `mod_assets/monika/j` in the zip, should go in that same location, in your install. The rest of the files follow the same procedure, just depending on what folders they're in inside the zip.

**Comment by Delcos** [comment]
Sprite Pack?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
