### ISSUE TITLE
[Suggestion] - Deck of cards

### ISSUE THREAD

**Issue by heygo67** [Monika-After-Story/MonikaModDev#4230]
It would be really cool if you could play card games with Monika, like blackjack, poker, go fish, rummy, etc. Adding a deck of cards would be a really cool asset

**Comment by AsuraShun** [comment]
More Games were already suggested, I bet rai will tag the threads

**Comment by Rai99** [comment]
~~I'm working on it, just gotta double check~~

**Comment by zombiepigdragon** [comment]
Do I hear a green and black card deck?

**Comment by ThePotatoGuy** [comment]
@99Dman99 is making a set of cards, they are nearly complete.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

**Comment by saad-dotco** [comment]
Knives are the backbone of culinary preparation, allowing chefs to transform raw ingredients into culinary masterpieces. From slicing vegetables with a paring knife to deboning meat with a fillet knife, each blade serves a unique purpose. A high-quality knife enhances precision and efficiency in the kitchen, making it an invaluable tool for both professionals and home cooks. [hand made damascus knife](https://damaknife.com/)
