### ISSUE TITLE
[Suggestion] - Ordering the anniversaries by date

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#4231]
Probably a duplicate issue ~~please @Rai99 have mercy on me~~ but just in case, the date of the anniversaries should be in this order : 1 week / 1 month / 3 months / 6 months / 1 year... Instead of being by alphabetical order.
![Capture](https://user-images.githubusercontent.com/38837456/58351917-66552500-7e6a-11e9-9dab-fbe1f808d70a.PNG)

**Comment by ThePotatoGuy** [comment]
ordering is not manual, so this would be difficult to do.
