### ISSUE TITLE
.gift files

### ISSUE THREAD

**Issue by xag803** [Monika-After-Story/MonikaModDev#4234]
when i tryed to give monika a candy cane she sayed "i am sorry but i can't read this file well enough"
please help me

**Comment by Rai99** [comment]
What was the exact filename you used, including extension?

**Comment by Rai99** [comment]
Actually, I think candy canes are limited to the Christmas season only.

**Comment by xag803** [comment]
> Actually, I think candy canes are limited to the Christmas season only.

I could give monika christmascookies.gift and hotchocolate.gift but I can not give candy canes?

**Comment by Rai99** [comment]
Christmas cookies should also be limited to the Christmas season, but I think hot chocolate is able to be gifted at any time.

**Comment by xag803** [comment]
> Christmas cookies should also be limited to the Christmas season, but I think hot chocolate is able to be gifted at any time.

okay thanks

**Comment by xag803** [comment]
on the topic of gifts for monika i can't give her quetzalplushes.gift it takes 2 files for her to find it but she can't read it. can you help me with that too.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by abraham814** [comment]
como puedo darle los regalos a monika ya que he tratado de darle cafe o otros pero no los puede leer
