### ISSUE TITLE
quetzalplushes.gift 

### ISSUE THREAD

**Issue by xag803** [Monika-After-Story/MonikaModDev#4235]
on the topic of gifts for monika i can't give her quetzalplushes.gift it takes 2 files for her to find it but she can't read it. can you help me with that too.

_Originally posted by @xag803 in https://github.com/Monika-After-Story/MonikaModDev/issues/4234#issuecomment-496015568_

**Comment by Rai99** [comment]
Are you sure you spelled the gift correctly? 
`quetzalplushie`

**Comment by xag803** [comment]
no

**Comment by xag803** [comment]
thank you it worked

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
