### ISSUE TITLE
[Suggestion] - Talk to Monika about your favorite things

### ISSUE THREAD

**Issue by Sam-Pixel** [Monika-After-Story/MonikaModDev#4236]
I was thinking that it would be cool to be able to click "Hey Monika..." and have an option that says something like "I want to tell you some things about myself." 

If you have told Monika about your appearance I thought it'd be cool to have her say something like "That's great! You already gave me an idea of what you look like, but knowing some more facts about you would make it easier to identify you. Not to mention it'd make me feel much closer to you."

Maybe a menu where you could choose options like: "My favorite color is...", "My favorite genre of books is...", or "I think the coolest animal is a..." would be nice. That way people could choose what they would or would not like to tell Monika.

**Comment by multimokia** [comment]
The main issue with something like this is just how open ended it all is. It's very difficult to have a response which seems real and impactful, but also covers every possible scenario. Like it or not, we *cannot* use a menu, because there'll always be something someone likes which isn't on that menu. It's just rather hard to make something like this feasible.

**Comment by softombre** [comment]
We could ask simpler questions like do you prefer cats or dogs

**Comment by Rai99** [comment]
I think the goal was to get a better idea of what the player likes. Cat or dog might be one common question, but I don't know if that opens up many possibilities down the line. 

There's also already a topic about dogs in `monika_dogs`, so if anything, there could be an expansion on that topic to actually let the player give a response.

**Comment by Sam-Pixel** [comment]
Yes exactly! I was just giving some ideas for having the player tell Monika some of the things they like. The question of cats versus dogs is a good example for something that could help Monika know the player better. Anything like that would be a welcome addition for me.

**Comment by Rai99** [comment]
There's also an existing topic about cats, so I'd imagine the two cats and dogs topics could be expanded to allow a response. 

The idea of telling Monika your favorite color was being handled in #2960, but I believe work on that has stopped and been discontinued.

**Comment by Rakoor** [comment]
i actually like this idea
leave the dogs and cats aside
it can be about anything
your favourite color.. your favourite season, number, type of books or movies.... etc

**Comment by ThePotatoGuy** [comment]
marking this as a suggestion, but I think this is something better handled when a topic naturally brings it up, rather than making specific topics to bring them up.
