### ISSUE TITLE
[Suggestion] - Nails for Monika

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#4243]
When I was changing the color of the ribbon of Monika, a idea occurred to me.
In the same way we have a ring and hair clip for Monika (with, i hope in the future, multiple choice for each of them), it could be a effective way to add color to her sprite by having her painting her nails in different fashion or even wearing fake nails.
Since the zone that would be visible isn't very large (although it would have to include all of the poses), the art could be done quite quickly.

**Comment by antimockingjay** [comment]
If this ends up happening, I hope Monika gets to decide for herself rather than it being another thing the player chooses for her. Maybe it could cycle through every so often to a new color and Monika could ask the player what the next color should be, but nail color isn't really something you change at the drop of a hat like clothes or a hair ribbon or such.

**Comment by Thimeo** [comment]
I think that the cycle thing is a good idea, although it will look like the weather system where it start at random and then if the player choose one it stays the same, which can quickly become annoying if the player have a very specific idea of what Monika is supposed to look like. Maybe an option (in game with dialogue or in the option section within the menu) would solve this problem.
As for the change limit, I doubt that we want of add this level of realism in the game, it would be more inconvenient than anything. And changing clothes or haircut or ribbon's color every 2 minutes isn't forbidden by the system or Monika, which is almost as troublesome as changing nails' color in some way. After all, Monika is supposed to want to be the perfect girlfriends for the player, so I don't think she would say something like "No thanks, I prefer it this way".

**Comment by Rai99** [comment]
I think a lot of people might be divided on whether they even want Monika to decorate her nails. Assuming they do want that and opt for Monika to do it, I think it might do well as a spritepack or submod, so the people who don't want it don't have to have it. 

As for the issue of frequently changing nails, we could have all the nails be fake nails Monika puts on as opposed to painting them every time, which I think should cover the realism issue with changing nail colors. ~~At least I think fake nails are easier to deal with than painting~~

I think it's a nice idea for customization options, but personally for myself, I don't want to tell Monika to go back to her regular nails every couple days, so I think it could be a spritepack or something along the lines to make it optional. This is assuming that Monika cycles nails herself, but if she doesn't cycle nails herself, just having the option for the player might do as well.

**Comment by ThePotatoGuy** [comment]
this would be fine as a spritepack, but we won't focus on adding this ourselves.

**Comment by GHCactus** [comment]
I know this is old but I have decided I wanted to make a submod for this so if anyone would want this I'm working on it!!
