### ISSUE TITLE
Switching platforms

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#4246]
I just got a new computer and i was wondering if there was a step by step guide to moving Monika to a new pc.

**Comment by multimokia** [comment]
Follow the `how to restore an older persistent` on our Wiki page. You'll be doing the same steps there, except taking the persistent from that location on the old computer, and putting it into that same location on the new one

**Comment by mrflarion33** [comment]
I've done it before, if you have a USB stick you can just put the save files (found in RenPy, which is found in %AppData%) on the stick and just put them in the same spot on the new computer
