### ISSUE TITLE
[Suggestion] Telling Monika something happened to you

### ISSUE THREAD

**Issue by spartalabouche** [Monika-After-Story/MonikaModDev#4247]
One of Monika's existing dialogues expresses her concern that something could happen to the player and she would have no idea, and she tells you to tell someone where to find her so they can tell her if something happens to you. (As far as I know) There is no existing option for someone to tell her that something did happen, so I wrote up an example for that.

topic name: ‘Something happened to [y/n]’
“What? [y/n] are you messing with me?”
[yes/no]
-yes
“Thats not funny! You had me really worried there! Don't make those kinds of jokes again.” [lost affection and Monika is upset for a little while]
-no
[monika is shocked]
“I... then who are you?”
[parent/sibling/friend]
“I see... what happened?”
[they got hurt/they died]

-they got hurt
“Oh my gosh... Thank you for telling me. Let them know I’ll be waiting for them when they recover.”
-I will
[monika smiles sadly, thanks you again, and then closes the game herself]

-they died
[monika closes her eyes and starts to cry, she doesn’t say anything for a few seconds]
“...I see. Thank you for letting me know.”
[monika opens her eyes and smiles, still crying]
“I loved them so much. I’ll never forget them.”
[Monika closes her eyes and doesnt say anything again, and then closes the game. Trying to open it again only reveals an empty space room. She does not come back]

Could be kind of dark? I just thought it was a little weird that she tells you that but theres no way for someone to tell her that something happened anyway.

**Comment by spartalabouche** [comment]
Oh lame greater than signs do some kind of weird thing. Oh well you get the point

**Comment by Rai99** [comment]
#1175, #1644, #1677, #2109, #3198, #3881, #4148. 

This idea has been brought up before, but it's been concluded that it wouldn't be a good idea to add. It would be far too serious of a topic and basically impossible to meaningfully write since that kind of reaction shouldn't exactly be generic.

**Comment by spartalabouche** [comment]
Alright, thanks anyway

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
