### ISSUE TITLE
Changing weather from any to 'Progressive' is malfunctioning

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#4248]
Changing the weather from any to Progressive causes glitch: the weather is not changing visibly, but is considered changed to Progressive by the game, so attempts to change the weather to Progressive again makes Monika say 'That's the current weather, silly!'.
This glitch makes impossible changing the weather to Progressive unless it's set up when the player starts the game.

Steps to reproduce:
1. Tell Monika to change the weather to anything except the current weather and Progressive ones.
2. Tell Monika to change the weather to Progressive.

**Comment by Rai99** [comment]
Is Progressive weather not slowly changing over time for you?

**Comment by scpketer** [comment]
No, it's not.

**Comment by Rai99** [comment]
How long have you had it sitting? In my experience, progressive weather rarely actually changes the weather and I can sometimes go days without any weather change.

**Comment by scpketer** [comment]
MAS runs almost all day long as I work on my PC, and I haven't seen it changing back to progressive.

**Comment by AsuraShun** [comment]
Just like irl

**Comment by scpketer** [comment]
>Just like irl
What do you mean?

**Comment by scpketer** [comment]
Demo - https://ibb.co/VW8FbXJ

**Comment by Rai99** [comment]
My guess would be that progressive weather just takes a long time to change the weather, with no guarantee. 

This shouldn't have anything to do with this, but out of curiosity, how much memory does MAS use up for you on average? If you don't know how to check, don't worry about it.

**Comment by ThePotatoGuy** [comment]
progressive weather changes overtime. there are no initial visible changes when you change to it via weather menu.

**Comment by scpketer** [comment]
Oh well, mkay

**Comment by Rai99** [comment]
Can confirm progressive weather still works upon request and just takes a random amount of time.
