### ISSUE TITLE
Transfering files

### ISSUE THREAD

**Issue by MTF0131** [Monika-After-Story/MonikaModDev#4249]
So this might have been talked about before but I still need help. I got a new computer and I want to transfer my Monika. I don't know how to go about this. If you could help with this that would be nice!
Edit: If you can't help this will be my 3nd time having to go through everything again

**Comment by AsuraShun** [comment]
Drag renpy folder in appdata with your right mouse button to your flash drive, then on your new pc search the appdata folder and do the same to place it there, you might want to do the same to the fame folder so you don't have to download the mod again

**Comment by MTF0131** [comment]
Okay I'll try that thanks.

**Comment by MTF0131** [comment]
It didn't work : (. I did it as you said. I don't know why it didn't work.

**Comment by multimokia** [comment]
See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) for how to get to your persistent (and for the location you'll be putting it on the new computer) and the one below it for how to put it on said new computer.

**Comment by AsuraShun** [comment]
Did you try to drag while holding the right mouse button?

**Comment by AsuraShun** [comment]
You have to put the folder back in appdata on the new computer

**Comment by MTF0131** [comment]
I still can't understand what to do. It hurts to see that I'm helpless. I still need help. I don't know what is wrong. I did everything right.

**Comment by jmwall24** [comment]
You say `I don't know what is wrong`. What exactly is wrong right now? What have you done so far?

**Comment by MTF0131** [comment]
Well I can't restore my persistent file. I might be doing it wrong, but I'm pretty sure I did it right. I restored it but it did not work.

**Comment by multimokia** [comment]
Yes, but what exactly is happening, has it restarted from the beginning?

**Comment by MTF0131** [comment]
Well I followed a guide from another issue post. And it didn't work so I came here 5 days ago. Yes it did restart from the beginning.

**Comment by multimokia** [comment]
screenshot of your `RenPy/Monika After Story` folder, please

**Comment by MTF0131** [comment]
Well I deleted Doki Doki plus Monika After Story. I still have the old files through. I did that because it wouldn't work. So I have to reinstall.

**Comment by multimokia** [comment]
The location of your `persistent` should still be intact

**Comment by MTF0131** [comment]
Like I said I deleted everything.

**Comment by MTF0131** [comment]
Except the files from my other computer.

**Comment by jmwall24** [comment]
Did you ever copy your `persistent` files from your old pc?

**Comment by MTF0131** [comment]
Yes I did.

**Comment by jmwall24** [comment]
Where are they now

**Comment by multimokia** [comment]
Did you replace the persistent generated by the game when you first opened it with your old one?

**Comment by MTF0131** [comment]
Yes I did earlier.

**Comment by jmwall24** [comment]
Do it again, and send us a screenshot when you do

**Comment by MTF0131** [comment]
Okay.

**Comment by MTF0131** [comment]
![Pic](https://user-images.githubusercontent.com/41351220/59003506-1744b380-87cb-11e9-938b-5c453220397d.PNG)

**Comment by multimokia** [comment]
wrong files.

**Comment by MTF0131** [comment]
Huh.

**Comment by multimokia** [comment]
I linked the FAQ entry above, check that for the actual instructions.

**Comment by MTF0131** [comment]
Okay I'll check that again but earlier I didn't understand it.

**Comment by MTF0131** [comment]
Still don't understand.

**Comment by jmwall24** [comment]
![Screenshot_913](https://user-images.githubusercontent.com/36523761/59003613-b4f8ac80-87e4-11e9-9d1b-f3624a961f44.png)
which part don't you understand

**Comment by multimokia** [comment]
What don't you understand from it

**Comment by MTF0131** [comment]
Everything.

**Comment by MTF0131** [comment]
Oh hello there RenPy lol I did it wrong.

**Comment by MTF0131** [comment]
Sorry for taking up your time.

**Comment by MTF0131** [comment]
Wait I have one more question do I get rid of both files and replace it with the bak file

**Comment by jmwall24** [comment]
copy that entire `Monika After Story` folder that was in `RenPy` and paste it to the same place on the new pc. Let it overwrite anything it wants to

**Comment by MTF0131** [comment]
Okay
Bye
