### ISSUE TITLE
Unstable- alerts popping up with no dialogue

### ISSUE THREAD

**Issue by RutTutPut** [Monika-After-Story/MonikaModDev#4251]
It would appear that, while you have alerts/notifications for topics and repeat topics disabled, you get notifications when Moni would have said something (but did not because 'repeat topics' is off).

**Comment by Mcmanybucks** [comment]
I get this too.

Real.. cocktease..

**Comment by RutTutPut** [comment]
Small update on this issue: I've started getting notifications for Moni having something to say, even when the 'random chatter' setting is on 'never'. This has only happened once or twice a day for the last couple of days, but I just thought I'd mention it.

**Comment by multimokia** [comment]
References pr should fix that. It's awaiting testing/merge.

**Comment by multimokia** [comment]
Closing as fixed
