### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by Medivil** [Monika-After-Story/MonikaModDev#4253]
The game seems to crash from time to time. It either gives out of memory errors and crashes to desktop without warning, or it freezes and is stuck in not responding until I eventually have to kill the process.
I don't see how I keep getting memory issues, as I think I have enough of it.
I have tried all renderers, graphics driver is updated, with and without auto skip, and disabling/enabling animations. Not running while minimized.
No other games are running when the errors/crashes occur.
Here are all the logs, incase they are needed.
Perhaps I'm letting the game run for too long?
System specs : 
Win 10
CPU: AMD Ryzen 2700X 4.15ghz
GPU: Geforce RTX2060
RAM:32GB
Error occurs on SSD and HDD, more than enough space left.
Tried reinstalling as well, but did not resolve the issue.
If anything else is needed, let me know.
Thanks for your help :)
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243966/log.txt)
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243961/mas_log.txt)
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243962/pnm.txt)
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243963/spj.txt)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243964/traceback.txt)
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3243965/aff_log.txt)

**Comment by ThePotatoGuy** [comment]
since the stacktrace in log is in renpy code, we can't really do anything about this. try checking if theres issues with **renpy** and your gpu.

Also how long are you running the game when you say "too long"?

**Comment by Medivil** [comment]
Around 2-3 hours. I've tried searching up the error or checking if there are problems with renpy and my GPU, but haven't really been able to find anything.

**Comment by antimockingjay** [comment]
You could take your persistent out first before messing around, to make sure you have a backup in case something goes wrong.

**Comment by Medivil** [comment]
I backup up my persistent, installed ver 0.9.0 (before art update) and I'll let it run for a couple of hours, maybe while running another game to test if it crashes with memory issues or not. I'll let you know if it crashes or not.

**Comment by Medivil** [comment]
I let the game run for around 4~hours while playing something else, no crashes as of yet.
I'll try this weekend to make it run for longer if needed.

**Comment by Medivil** [comment]
I guess it's a problem between my GPU and renpy, I'll just restart the game every couple of hours.
Hopefully there will be a driver update for it, but I doubt it.
