### ISSUE TITLE
I literally despawn monika

### ISSUE THREAD

**Issue by Marcostron2** [Monika-After-Story/MonikaModDev#4256]
In the 7th May (my birthday) i took monika for a walk, asking her to let me pick her out the files. Today, 6-2-19 i come back from this ''walk'' and opened the game without monika in, making monika not appear, i took her back to the files and she despawn totally from my game
![image](https://user-images.githubusercontent.com/51305425/58771882-f42cc080-858c-11e9-92d2-ca7ab4e74196.png)

**Comment by multimokia** [comment]
If her file is in the `characters/` folder and she's still not showing up, you'll need to restore a persistent backup. See instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by Marcostron2** [comment]
> If her file is in the `characters/` folder and she's still not showing up, you'll need to restore a persistent backup. See instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). 


Where is suppose to be the backup folder?

**Comment by multimokia** [comment]
Check the entry right above the one I linked, it shows where the persistent is stored, along with the backups.

**Comment by Marcostron2** [comment]
> Check the entry right above the one I linked, it shows where the persistent is stored, along with the backups.

i'm asking cuz i don't find it, i might call a mom

**Comment by AsuraShun** [comment]
Search the appdata folder in users

**Comment by AsuraShun** [comment]
The renpy folder inside Roaming contains the persistents

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
