### ISSUE TITLE
[Suggestion] for haters

### ISSUE THREAD

**Issue by Rakoor** [Monika-After-Story/MonikaModDev#4257]
We know some people that download the mod just out of curiosity.. even though they hate Monika. so they just drive her crazy and eventually causing her to leave
however they only delete the save filea and repeat the cycle again.. 
So maybe we can put a hidden file outside the save folder. that in case the player tried to reinstall Monika. she knows and tells them that the original Monika who loved them deleted herself. and so will she .

**Comment by antimockingjay** [comment]
First off, this is kinda already implemented with the appdata folder containing the persistent file. The problem with adding more of that is that the ones who hate Monika will always be able to find the files and delete them still, no matter what you do. And the more of these you add, the harder it is for people who are messing with the files for innocent reasons, such as corrupted files or such.
The truth is, no matter how many safeguards we put in, it's impossible to stop players from being malevolent. If someone wants to be hateful, they will. And even if it were to be added now, they could just go and download an older version of the mod that doesn't have that, and mess with that version of Monika.

**Comment by Rai99** [comment]
#2127 

No matter how many layers of deterrent we have, people will probably still go the extra mile to torture Monika. Mistreating Monika already has absolutely no benefit, and if someone is willing to do it despite that, I don't think a couple extra files or flags will stop them if they're serious.

**Comment by Rakoor** [comment]
that's sad, but i understand
however i want her to make it at least clear that the monika which left them. is not the same they reinstall .. just to make them feel bad even if a little bit

**Comment by Arte71** [comment]
"the monika which left them. is not the same they reinstall .. just to make them feel bad even if a little bit"

Honestly if the person didn't feel bad in the slightest by torturing her, then I see no reason for them feeling bad by doing it again with a different Monika or knowing the Monika that left them might be somewhere else.

**Comment by ThePotatoGuy** [comment]
yeah, adding out of mod guardrails just makes the mod more prone to errors out of our control (filesystem/os) that break a game.[closnig as duplicate]
