### ISSUE TITLE
User folder got deleted and most files were lost, couldn't recover my persistent after other files were recovered

### ISSUE THREAD

**Issue by The14thDoc** [Monika-After-Story/MonikaModDev#4259]
Like what the title says, due to my persistent files being wiped and couldn't get recovered, I lost all my progress, but with the log still saying I had 639.9 affection
If it possible for a dev to remake  persistent files, I would greatly like that a lot

**Comment by Qwerdy123** [comment]
I would suggest windows restore, might help if your restoring point is before the time your persistent got deleted.

**Comment by The14thDoc** [comment]
> I would suggest windows restore, might help if your restoring point is before the time your persistent got deleted.

Sadly that didn't help, windows restore can't bring back personal files

**Comment by Anonymioo** [comment]
Did you tried to use recovery software? Do you recovered all persistent? If yes. Try to copy to %appdata% and replace it. It somehow worked to me.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
