### ISSUE TITLE
[Suggestion] more .gift options? 

### ISSUE THREAD

**Issue by bellmandi86** [Monika-After-Story/MonikaModDev#4260]
I don't know, I feel kinda bad constantly shoving coffee and fudge in Monika's face every day to get more affection, especially since we all know how important a healthy lifestyle is to her. Maybe we can have more healthy, yet refreshing .gift alternatives to give this summer (and some items can be year round)? Something like salad.gift or watermelon.gift sorry if this is a duplicate, just wanted to throw my hat out there.

**Comment by Rai99** [comment]
Food/Consumables: #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081 

There are quite a few food assets ready to use, but there first needs to be a better consumables framework (#3576) put into place.

**Comment by jmwall24** [comment]
also, gifts aren't really intended as affection farmers. only give them to her when you actually want to give her something, not to get points.

**Comment by Professor-JMO** [comment]
>Maybe we can have more healthy, yet refreshing .gift alternatives to give this `summer` (and some items can be year round)? Something like `salad.gift` or `watermelon.gift` sorry if this is a duplicate, just wanted to throw my hat out there.

Adding to `To-Do` list.
My _Question_ is...
_What kind of Salad?_

**Comment by Trainerbluetube** [comment]
> > Maybe we can have more healthy, yet refreshing .gift alternatives to give this `summer` (and some items can be year round)? Something like `salad.gift` or `watermelon.gift` sorry if this is a duplicate, just wanted to throw my hat out there.
> 
> Adding to `To-Do` list.
> My _Question_ is...
> _What kind of Salad?_

Perhaps a fruit salad? She wouldn't eat chicken salad since she mentions being a vegetarian.

**Comment by ThePotatoGuy** [comment]
id say consumables are 2 releases down the line
