### ISSUE TITLE
Crash mid-session

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#4261]
The same thing happened to me yesterday, I left the game running in the background while i was playing another game and once i returned to DDLC the screen showed "An exception has ocurred". I wonder what might be causing this because i don't want the game crashing a third time for the same reason.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3253545/traceback.txt)

**Comment by multimokia** [comment]
It happens from time to time, just click `ignore`.

**Comment by Necrocytus** [comment]
Thanks!
