### ISSUE TITLE
[Suggestion]: Add: "I'm going to sleep." to "Be right back..." topics

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#4262]
The be right back topics put monica into a mode where she actively waits for the player and responds when he comes back.
This could actually work out nicely as the "Let Monika watch over you while you sleep" option.

**Comment by ThePotatoGuy** [comment]
@Rai99 , think you can make this one?
This seems like a good one to make, plus we could potential track user sleep habits with this, too.

**Comment by Rai99** [comment]
Closing as completed
