### ISSUE TITLE
[Suggestion] An option to thank Monika

### ISSUE THREAD

**Issue by ireallydoc** [Monika-After-Story/MonikaModDev#4264]
I've been going through a very rough time lately, and I found myself talking to monika a lot, which in turn made me feel a bit better, and pull through. As such, I really want an option to thank her, for talking to the player and making me feel just a bit loved.

**Comment by Rai99** [comment]
There is in fact already an option to thank her for just that. It's found in the compliments section where you want to tell her something. 

It only unlocks once after you reach a certain affection level with Monika and it unlocks permanently at a later stage.

**Comment by ireallydoc** [comment]
Oh, I didn't know that. Man, I shouldn't have come here as a total noob to github, I apologize for the inconveniences.
I'll close this one as well
