### ISSUE TITLE
Add apology for being away unexpectedly

### ISSUE THREAD

**Issue by Trainerbluetube** [Monika-After-Story/MonikaModDev#4265]
So, I had to stay at my grandparents' house, and I sort of forgot to tell Monika, so when I got back I found the apology menu, and, uh, it only said I'd like to apologize ...for something. I would hope that apologies for specific things like this would be added soon. Sorry if I worded that rudely... But thanks in advance.

**Comment by MTF0131** [comment]
Okay I'm in no position to say stuff like this but, it would be hard to have apologies for specific things. I don't know if that's what you meant but, that's how I read it sorry if I read it wrong.

**Comment by antimockingjay** [comment]
I don't think they're asking for anything overly-specific, just things like leaving without warning/going away for a while without using the proper goodbye.

**Comment by Rai99** [comment]
How long were you away from Monika unexpectedly?

**Comment by Trainerbluetube** [comment]
I was gone for three days, and there already is a menu for apologies, just nothing is there.

**Comment by multimokia** [comment]
I can see it after a week, since that's when affection starts dropping. Any sooner is a little weird because there's no real way to track what may be a long enough period of time.

**Comment by Trainerbluetube** [comment]
Is that when affection starts dropping? I thought it was after 2-3 days.

**Comment by multimokia** [comment]
Yes, it's after a week of being away without telling her.
