### ISSUE TITLE
Regarding to settings information

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4266]
Hello! I'm using v0.9.4-unstable.2019.05.31.97, and I happen to find something that caught my eyes. I don't know if this is intended and, if not, it's definitely low priority, but I'll still put that here.

It happens on the settings information. Since one of the newest feature has longer explanation than others, it overlaps with the MAS' version. I don't know whether I explain this correctly, so I'll put the screenshot here.

![screenshot0012](https://user-images.githubusercontent.com/44340452/59033015-d8c5fc00-8891-11e9-8c4c-934bf6ceaf34.png)

Sorry for the censor. I'm afraid that's too spoiler-y for people that don't use unstable.

Thank you. Have a nice day!

**Comment by multimokia** [comment]
~~*you missed one bit to censor*~~


But thanks for pointing that out.

**Comment by skyloom** [comment]
@multimokia whoops should I just censor it all? 😂

Thanks for your fast response!

**Comment by multimokia** [comment]
Lol, why not lmao.

**Comment by skyloom** [comment]
@multimokia ((I forgot whether the right side has new feature so I just censor them all 😂))

**Comment by multimokia** [comment]
Lol it wasn't that, is the new tab on the left

**Comment by skyloom** [comment]
@multimokia since I totally forgot I just censor them all (and onein the menu that I missed lmao) 😂

**Comment by Andrenika** [comment]
What is the unstable mode?

**Comment by multimokia** [comment]
Unstable is a branch which gets some somewhat in-dev features. It's a means of beta testing, essentially, just to ensure that everything which is in that works correctly, so we have less problems overall when making the actual update.

Be warned that there are some instabilities, of course, so if you're going to opt into unstable updates, be sure to back-up your persistent often, just in case.

If you're in MASC, there's a `#unstable` channel, where patch notes are put. If you're running unstable, let a mod know and they can give you access to said channel.

**Comment by ThePotatoGuy** [comment]
[closing as fixed in #4300]
