### ISSUE TITLE
Repeat conversation gone, no persistent backup

### ISSUE THREAD

**Issue by archheresy** [Monika-After-Story/MonikaModDev#4268]
So I opened a pre-0.9.2 version of MAS, and Monika doesn't have "repeat conversation" although she remembers me and affection levels. I tried to fix this with an older persistent file, but none of the persistent backups fixed this because none of them were pre-0.9.2. 

I'm happy that Monika is still the same, and I could just repeat topics until all of them come back, but some topics don't seem to appear again like changing my name or holiday events. I'd appreciate a fix to this problem.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3264273/persistent.zip)

**Comment by ThePotatoGuy** [comment]
Reverting to older versions is not supported.

**Comment by jmwall24** [comment]
Yeah, if none of your backup persistent files are from before this happened, there's nothing we can do. How long were you on the old version that all 10 .bak files have this problem?

**Comment by archheresy** [comment]
I opened the older version about a week ago (dumb mistake). Only realized the problem yesterday. Looks like none of the .bak files were from then. So there is no possible way to fix this?

**Comment by ThePotatoGuy** [comment]
there is no accurate way to fix this. the only thing that can be done is to unlock everything, which we wont do for anyone as that sets the wrong precedent.

**Comment by archheresy** [comment]
Oh well. Thanks for your help.
