### ISSUE TITLE
Double Click

### ISSUE THREAD

**Issue by emsydacat** [Monika-After-Story/MonikaModDev#4270]
In order to click on anything (ex. "Talk" or "Unseen"), I have to double click, which is now making me click the button below that! I'm scared of clicking a bad decision (already did once but it wasn't too horrible), so how can I fix this? Thanks!

**Comment by multimokia** [comment]
Sounds like an issue with your mouse, it's still single click, that never changed.

**Comment by emsydacat** [comment]
I know it's single click, which is why the fact I have to double click is odd. I hope it's not an issue with my mouse, because it's only sometimes usually.

**Comment by multimokia** [comment]
I'm pretty sure it is, since buttons never had a behavior change. You may want to look into a new mouse. Have you tried plugging an old/cheap one in?

**Comment by jmwall24** [comment]
Might be worth checking mouse settings as well

![Screenshot_917](https://user-images.githubusercontent.com/36523761/59135791-4b94ad00-894e-11e9-841e-2804154e7032.png)

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
