### ISSUE TITLE
[Submod] [Outdated] MAS-Additions with facial recognition, MIDI support for piano and more

### ISSUE THREAD

**Issue by CaptainHorse** [Monika-After-Story/MonikaModDev#4271]
Noticed there is now a submod label, here is old and currently outdated collection of submods made by me.

https://github.com/CaptainHorse/MAS-Additions

If there is any interest, I'll update it to (hopefully) work with the current MAS version.

The submod has an odd way of going around some issues Ren'Py has, using an external binary which has an embedded Python 3 interpreter to load things like opencv2-python for facial recognition needs. It's not issue-proof though, there are multiple problems loading DLL's required for things like webcam access, MIDI input and such. Some systems are free of these issues but others are not.
This is why I have left the submod outdated for so long, I need to find a good consistent way to fix the loading issues.

**Comment by multimokia** [comment]
Mind moving this over to #3765? That's the main tracking issue for all of this.

**Comment by CaptainHorse** [comment]
Allright, closing this.
