### ISSUE TITLE
[Suggestion] - Monika reads a book while she waits.

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#4273]
This topic was inspired on Moni falling asleep after you hold her long enough. Which btw I absolutely love, great job on that one, especially the music!

I was thinking that if a certain time passes as she waits for her loved one to come back, she pulls out a book and starts reading. It doesn't need to be a specific book, it can just have a blank cover. When you come back she says something along the line of how she wants to put the book away (similarly on how she would put her cup away).

I just feel bad when I say "be right back" and it takes longer than expected and she doesn't do anything at all the entire time.

**Comment by MetalBrother** [comment]
Nice idea!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
probably would need art of her reading a book. not a bad idea. maybe you can then gift her books to read.
