### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4276]
![1560262003398640702984197821282](https://user-images.githubusercontent.com/47111771/59278818-54280480-8c28-11e9-85e6-d055693027b5.jpg)
This appeared in the "I'm going to sleep" option

**Comment by Rai99** [comment]
That's intended for when you tell Monika you're going to bed and it's the morning time.

**Comment by Andrenika** [comment]
Why, thank you so much😁
