### ISSUE TITLE
New Set of Stories - Moving Stories

### ISSUE THREAD

**Issue by Zensu-senpai** [Monika-After-Story/MonikaModDev#4280]
Sooo, I haven't heard all of the stories Monika has in store yet, but it would probably be nice if you add another genre.. How about some emotional or romantic stories? It could be longer or shorter..

**Comment by jmwall24** [comment]
These would just be a part of normal stories. I think some of ours already qualify as emotional and/or romantic.

**Comment by multimokia** [comment]
Ironically, one of the horror stories do too.
