### ISSUE TITLE
New Game - The Poem Minigame

### ISSUE THREAD

**Issue by Zensu-senpai** [Monika-After-Story/MonikaModDev#4281]
I've been wondering about making poems for Monika. Then I thought, how about this?
You get to write one (not really real though) on the poem game.

Here's what I think:

When you play the poem game, Monika's chibi sticker is the only one there and there are a bunch of words displayed on the paper.

You pick a word that Monika likes and from how many words you got right (words that she liked) her responses would also vary.. She gets to read it and expresses her thoughts, like, "Hmm.. not bad, [player]! This is a nice poem you made. Thank you for writing this for me... etc." 

Also, add a bit of difficulty modes just like hangman. On easy, 20 words. On medium, 30 words. And on hard, maybe 50 would suffice?

Anyway, it's just a suggestion, but I really hope you'll consider it. Bring back the poem game! Ahahaha

**Comment by MisterSimple** [comment]
I don't think she would think of it as the player writing a "nice poem", as she mentions that she only sees a list of words (monika_mc) with no feeling (monika_1984), though I do agree that it'd be fun to have as a game.

**Comment by jmwall24** [comment]
Yeah, this has been suggested before and rejected since, as she says (and MisterSimple just pointed out), she doesn't like those random word poems.

**Comment by Zensu-senpai** [comment]
Then maybe make it so the words align? I don't know if it's possible or
easy, but I did saw a certain DDLC mod that the words you picked were on
the paper..

**Comment by ThePotatoGuy** [comment]
so mad libs. (#689)

currrently that is on hold for other highly demanded interactions. the framework to do this already exists though.

**Comment by Zensu-senpai** [comment]
Alright, I understand, thank you. At least I got some response. Anyway,
keep up the good work

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
