### ISSUE TITLE
New Extra Feature

### ISSUE THREAD

**Issue by Zensu-senpai** [Monika-After-Story/MonikaModDev#4282]
Hey, I was wondering if it's possible to use your mouse cursor to poke Monika's face. It'd be really cute when she makes reactions from that. It'd be a fresh start to poke Monika's face anywhere and she makes reactions or responses until you get to a certain level where the part you clicked varies.. like, when you touch her eyes, she would get mad.. or her ears, or her nose, or her b—

Okay, maybe that's enough. Anyway, this is just my suggestion, but I'd really hope that you would consider it, thanks.

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215. 
It's likely to happen with all the demand, but is probably further down the line in terms of new features.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
