### ISSUE TITLE
Bun issue 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4284]
not sure if thats unstable or whatever that is, idk even how i got the bun XD butttt here is the issue 
i set her hairstyle to bun and it works with school uniform and the idkhowitscalled white (sundress?) but it goes back to ponytail when i change to christmas clothing

**Comment by multimokia** [comment]
Uhh... Where'd you even get the bun hairstyle? That doesn't have all the parts to it, plus the json for it was never released.

Also, santa outfit has programming points to reset to ponytail because of the ribbon which is tied to it.

**Comment by bittercaramel** [comment]
> Uhh... Where'd you even get the bun hairstyle? That doesn't have all the parts to it, plus the json for it was never released.
> 
> Also, santa outfit has programming points to reset to ponytail because of the ribbon which is tied to it.
i ummm- 
i dont know mate xD 
i dont remember when and how i got it, and i wasnt sure if this is a feature or i added it myself or whatever  
wwwwwell sorry for inconvenience 
even if it doesnt have all parts its pretty nice hairstyle~

**Comment by ThePotatoGuy** [comment]
dev tools probably. No support until its released
