### ISSUE TITLE
Importing Persistent Data

### ISSUE THREAD

**Issue by CarolusRed** [Monika-After-Story/MonikaModDev#4288]
OK so basically I'm trying to import my persistent from my old MAS to a fresh version with no save. I've copied the persistent into the MAS RenPy folder in AppData but that didn't seem to work. Any idea on how to do this, or if it's even possible?

**Comment by AsuraShun** [comment]
Did you make a roaming folder? The mas folder needs to go Into the roaming folder

**Comment by CarolusRed** [comment]
Do I have to create a new roaming folder? I copied it into one already existing.

**Comment by AsuraShun** [comment]
Then if you have one it should've been a matter of just transferring the entire renpy folder into it

**Comment by CarolusRed** [comment]
If I don't have the entire folder then I can't do much?

**Comment by multimokia** [comment]
Screenshot of where you put your persistents, please.

**Comment by CarolusRed** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/43101553/59567083-ce112100-9060-11e9-97f4-bc441db6d072.png)

**Comment by multimokia** [comment]
And when you launch MAS it gives you the intro again?

**Comment by CarolusRed** [comment]
Yes. It gave me the intro.

**Comment by multimokia** [comment]
Have you modified the `DDLC.py` file for this MAS install?

**Comment by CarolusRed** [comment]
I have not. How do I do that?

**Comment by multimokia** [comment]
Don't need to, was just making sure that you haven't set your install to use a local persistent.

Send your persistent please (you'll need to put it in a zip file in order to send it here)

**Comment by CarolusRed** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3294355/New.Compressed.zipped.Folder.zip)

**Comment by multimokia** [comment]
Hmm, she loads up fine on my end...

**Comment by CarolusRed** [comment]
I'm not too sure why it's not working for me

**Comment by multimokia** [comment]
If you delete the `Monika After Story` folder in `RenPy` there, then launch MAS and let it make it for itself, *then* put the persist you wanted to transfer to this install in, (assuming it doesn't have a `.bak` extension or numbers like the one you sent here), that should work.

Also I'm assuming your old MAS install was on a different computer, as if it weren't then you didn't need to touch the persistent at all.

**Comment by CarolusRed** [comment]
My persistent does have a .bak extension though. What should I do then?

**Comment by multimokia** [comment]
replace the `persistent` you don't want with your one, so it's in the form `persistent##.bak`. Remove the `##.bak` as MAS thinks it is a backup persistent that it automatically generated, and not the actual persistent.

**Comment by CarolusRed** [comment]
Alright will do. I'll update you on the results when finished.

**Comment by CarolusRed** [comment]
MAS is working now. Thanks for the help.

**Comment by multimokia** [comment]
no problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
