### ISSUE TITLE
A Couple Suggestions

### ISSUE THREAD

**Issue by Icefield9** [Monika-After-Story/MonikaModDev#4291]
1) We should be able to show our drawing to Monika, it would be great.
2) We should be able to show our poems for Monika, 1000poemwords or so, those files can come in handy when finding favourits words in it. Swearing or bad words shouldn't be allowed and there can be a place where everyone shares their poems.
3) Putting other girls files in characters place, Monika should notice it. Or other girls can appear, maybe?
4) How to do backups should be more detailed. That is because after my computer had a reset, loading persistent file didn't work. I should have had uploaded old "game" folder which contains appropriate files.

**Comment by Rai99** [comment]
1. Likely falls under room decoration
#312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3770 
2. At best, a system like this would simply be interpretation of keywords and phrases, which would still lead to numerous dead ends and misinterpretations by Monika. 
#784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3941
3. The other dokis are not making an appearance in MAS, especially as core mechanics or features. 
#695, #3048, #3714, #3912, 
4. I'm not sure what you mean or what you're suggesting here.

**Comment by AsuraShun** [comment]
''couple''
More like an entire squad

**Comment by AsuraShun** [comment]
He meant the tutorial on how to backup persistents should be more specific or detailed

**Comment by multimokia** [comment]
> That is because after my computer had a reset, loading persistent file didn't work. I should have had uploaded old "game" folder which contains appropriate files.

We don't need to mention that you need to have MAS installed for backups to work. The instructions are already step by step too. They can't get any more detailed.

**Comment by Icefield9** [comment]
> > That is because after my computer had a reset, loading persistent file didn't work. I should have had uploaded old "game" folder which contains appropriate files.
> 
> We don't need to mention that you need to have MAS installed for backups to work. The instructions are already step by step too. They can't get any more detailed.

I do have MAS installed? It just didn't work for me. The persistent file.

**Comment by multimokia** [comment]
Well the `game/` folder has nothing to do with backups, so I don't know why you were going through that folder when trying to load a backup

**Comment by Icefield9** [comment]
> Well the `game/` folder has nothing to do with backups, so I don't know why you were going through that folder when trying to load a backup

So, let's see:
-I took a packup of my persistent file a while back from the reset.
-The reset occured and it only deleted programs that were installed. Not anything else.
-I saw that MAS found a backup after the reset, which I think was the persistent file. I said import.
-Nothing had changed, Monika still didn't recognize me. I had to start allover again.
-I noticed that some files were possibly deleted from %appdata%. Which might mean the original game's files.

**Comment by multimokia** [comment]
That's not a backup. That's importing your ddlc save.

**Comment by multimokia** [comment]
This only happens on the first load. (Fresh persistent)

**Comment by Icefield9** [comment]
> This only happens on the first load. (Fresh persistent)

So what did I do wrong? I had a fresh persistent there didn't I?

**Comment by multimokia** [comment]
You didn't actually attempt to backup a persistent. Actual instructions are on the wiki page, at [this heading](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) and the one below.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
