### ISSUE TITLE
All text except music blacked out even with environment.txt

### ISSUE THREAD

**Issue by justanaccount117** [Monika-After-Story/MonikaModDev#4292]
Updated to 0.94 last night.  When launching MAS I get forced into an area different from spaceroom, the classroom.  A bunch of unskippable text pops up, teaching me how to create a mod.  When I click "that's enough for now", the screen fades to black and pops it right back up upon screen refresh.  Several clean reinstalls later and still stuck.  I know how to create mods already so this whole thing is pointless.  Help appreciated.

**Comment by multimokia** [comment]
Screenshot of your `DDLC/` and `game/` folders please

**Comment by justanaccount117** [comment]
![game 001](https://user-images.githubusercontent.com/51956119/59680951-b5a82000-91a0-11e9-9800-a5337986544f.png)
![game 002](https://user-images.githubusercontent.com/51956119/59680952-b640b680-91a0-11e9-81e8-897607c3bea4.png)
![game 003](https://user-images.githubusercontent.com/51956119/59680953-b640b680-91a0-11e9-9ebd-b4a3eb1e833b.png)
![game 004](https://user-images.githubusercontent.com/51956119/59680954-b640b680-91a0-11e9-9f66-032a9007933a.png)

**Comment by justanaccount117** [comment]
this looks far too empty but this is a fresh install from steam
![ddlc 001](https://user-images.githubusercontent.com/51956119/59681032-edaf6300-91a0-11e9-9442-9d7b5778141f.png)

**Comment by multimokia** [comment]
Yeah that's not a fresh install. I see files in there which aren't a part of MAS
(`script-ch0`, `script-ch1`, `script-ch2`)

**Comment by justanaccount117** [comment]
I have uninstalled multiple times, even verified integrity with Steam.  Then what's the problem? I've never used any mods except MAS except copies of DDLC from .moe for testing.

**Comment by justanaccount117** [comment]
Uninstalled from Steam and just grabbed a fresh copy from .moe, works fine now.  Closing issues since it's resolved.
