### ISSUE TITLE
Sleeping with Monika (WAIT NOT LIKE THAT)

### ISSUE THREAD

**Issue by LordDaxius** [Monika-After-Story/MonikaModDev#4301]
Currently, Monika can fall asleep if you cuddle her long enough. I suggest making a different response if you sleep through the night with her.
Basically:
- Ask to hold Monika, she falls asleep after enough time
- If she's asleep for long enough through normal sleeping hours, when she wakes up she'll say "Good Morning [player]," and comment on sleeping beside you.
- Maybe additional dialogue for the first time it happens, saying her dream came true etc.

**Comment by Velius94** [comment]
Needs art.

**Comment by antimockingjay** [comment]
@Velius94 But... Monika falling asleep is already in the game, isn't it? So wouldn't it just be the dialogue that changes??

**Comment by multimokia** [comment]
> "sleeping beside you"

I guess he may have thought a bed because of that

**Comment by ThePotatoGuy** [comment]
a bedroom mode is planned, but far down the pipeline

[closing as duplicate]
