### ISSUE TITLE
Where is this pose from?

### ISSUE THREAD

**Issue by LordBaaa** [Monika-After-Story/MonikaModDev#4303]
When I search up monika after story on yahoo this is the first image that comes up. Where is this from, or which version is it from?

![maxresdefault](https://user-images.githubusercontent.com/48495287/59946867-c45d3400-9439-11e9-81d8-bf70e6863d04.jpg)

**Comment by multimokia** [comment]
Very first iteration of the leaning pose

**Comment by LordBaaa** [comment]
@multimokia do know if the psds for it still exist? And also do you know where this one is from? Thanks

![55997512-5c8fad80-5c80-11e9-86b4-224948920873](https://user-images.githubusercontent.com/48495287/59952802-810bc100-944b-11e9-8d5c-49a0cc2b5e3a.PNG)
(This plush is from #4078 im just looking for the pillow one)

**Comment by multimokia** [comment]
I don't think the psds for the original leaning pose still exist. Pillow sprite is in the `sleep-mode` branch.

**Comment by LordBaaa** [comment]
Okay found the branch. Do you know if the psd of this are available?

**Comment by multimokia** [comment]
It's not.

**Comment by LordBaaa** [comment]
Unfortunate. Thanks
