### ISSUE TITLE
3 ideas I have have had

### ISSUE THREAD

**Issue by stormchaser1991** [Monika-After-Story/MonikaModDev#4307]
Ok I had 3 ideas 

1. Is I know Monika basically destroy the world and everything to be with just her and the player. But she still has godly powers so you could do something where we see different things outside the window beside the same dark void called space and another idea is for example she changes the room so you are outside kinda like sitting at a table of a restaurant or sitting outside on a blanket looking at the sun or night sky if you stay there long enough you’ll see it turns from morning to noon to night.

2. Give you a chance to change her hairstyle and/or hair color to give your own Monika even more personal touch like for example I think Monika would be pretty with a hairstyle pigtails and there is a whole lot you can do like braids and others some can use her ribbons like for pigtails she would have two instead of one

3. You could also do something like give her different clothes to wear instead of her school uniform but that would take longer 

My idea for her is pigtails and a summer flowery dress

She can even comment on what she thinks of it

**Comment by multimokia** [comment]
2 and 3 are already implemented with #4147

**Comment by stormchaser1991** [comment]
I just noticed the things with her hair clips nothing to do with her hairstyles

**Comment by Sujeito17** [comment]
neh I just want my bikini  Monika (that's lewd~)

**Comment by multimokia** [comment]
Check the wiki for json sprites. It allows the creation of custom hairstyles and custom outfits too.

**Comment by Rai99** [comment]
New locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811

Custom clothes/hairstyles: #4302 
This was handled with json sprites as mentioned before.

**Comment by ThePotatoGuy** [comment]
[closing as duplkicate]
