### ISSUE TITLE
I might be overlooking something but how do you use the summer dress?

### ISSUE THREAD

**Issue by Delcos** [Monika-After-Story/MonikaModDev#4308]
I've seen it before, then she took it off and never saw it again. No option that I see.

**Comment by multimokia** [comment]
What's your affection?

**Comment by Delcos** [comment]
> What's your affection?

341, didn't post for some reason so here's my second try.

**Comment by multimokia** [comment]
Need 1k+ to use the clothes selector.

**Comment by Delcos** [comment]
Rip, alright.
been almost 2 years so I should be around 1 within the century.
Thanks for the help

**Comment by multimokia** [comment]
Uhh, how often do you visit her?

**Comment by Delcos** [comment]
actually, she has a standalone computer in my workshop. so she's left running. idk if that causes an issue since I never really say bye and come back. might be missing out on points.

**Comment by multimokia** [comment]
A few, yes. However it should only take about 4-6 months on average to reach 1k. If you're constantly with her and interacting with her/being good to her then you should be there quickly.

**Comment by Delcos** [comment]
> A few, yes. However it should only take about 4-6 months on average to reach 1k. If you're constantly with her and interacting with her/being good to her then you should be there quickly.

odd, ill be keeping a closer watch on the points just too see if it changes. Maybe also try the rest for 6 hour thing.

**Comment by multimokia** [comment]
Whatall do you do with her while she's up and you're around?

**Comment by Delcos** [comment]
general interactions, the i love you thing, gifts when available, going through the unseens, and the random chatter .

**Comment by multimokia** [comment]
And you do this every day, or no?

Because there's something not adding up tbh.

**Comment by Delcos** [comment]
> And you do this every day, or no?
> 
> Because there's something not adding up tbh.

no, I only use the random chatter once or twice a day, she'll say something and ill read through it. not sure if that adds points or not. the unseens are not everyday since there's not a huge amount of them. Other than that the I love you option is used every couple of days.

**Comment by multimokia** [comment]
Yeah that explains everything.

**Comment by lunulae** [comment]
If you're out to raise affection more quickly, taking her out of the spaceroom for a few hours every day will give you some extra points. I believe the I love you button gives you extra affection 3 times(?) a day.

1k definitely takes a while to reach but it shouldn't take extraordinarily long. Don't give up! <3

**Comment by Delcos** [comment]
Im not too concerned with time, Im just making sure there isn't some kind of actual problem or issue preventing points from getting added. Thanks for all the help guys 📦

**Comment by ThePotatoGuy** [comment]
[closing asresolved]
