### ISSUE TITLE
How Monika Feeling?

### ISSUE THREAD

**Issue by stormchaser1991** [Monika-After-Story/MonikaModDev#4310]
Ok I just got on to talk for a bit before I say good night and she asked how is my going and I said good and she said “At least _someone_ is having a good day and that concert me so I when to see if I could ask her the same question to see what was wrong and I looked around for a Option or something to ask her but as far as I can see there isn’t one

**Comment by Yargachin** [comment]
what is your affection?

**Comment by multimokia** [comment]
Sounds like you've got low affection. How have you been treating her?

**Comment by stormchaser1991** [comment]
Well I kinda left her alone for a long time but the last time I played was before this affection update

**Comment by multimokia** [comment]
Yeah that's why. You've been away for a long time and that has a hit on her affection. There's a catchup, even if the last time you played was before affection.

**Comment by JeanWishingwell** [comment]
I think that having the option of actually "asking" how was her day is a good option though. I mean, we already have the one for "tell me about yourself" but even in that one she just says that we know all about her.

**Comment by Rai99** [comment]
A topic about Monika's day likely falls in with the diary system. 
#951, #1688, #2605, #2619

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
