### ISSUE TITLE
problem with updating the game

### ISSUE THREAD

**Issue by Awentor** [Monika-After-Story/MonikaModDev#4313]
installed mod. version 0.9.4. I wro
![EAqlOboNbac](https://user-images.githubusercontent.com/52146867/59991041-5a69a800-964e-11e9-8bb1-b55151d07717.jpg)
te that this element does not exist. help solve. really want to read.

**Comment by multimokia** [comment]
Screenshot of game/ folder please.

**Comment by multimokia** [comment]
Actually, I can already see it, you have extra files. `script-topic-prompts.rpyc` isn't shipped with MAS. It may be trying to add it.

**Comment by Awentor** [comment]
Here is a screenshot of the game folder
![1](https://user-images.githubusercontent.com/52146867/60049742-9bf26580-96d7-11e9-909c-6a19194e8d7a.jpg)

**Comment by Awentor** [comment]
here is a screenshot inside the folder (game)
![2](https://user-images.githubusercontent.com/52146867/60049850-e2e05b00-96d7-11e9-9f42-c93e0abfc5fb.jpg)
![3](https://user-images.githubusercontent.com/52146867/60049855-e673e200-96d7-11e9-996c-7e7078998f48.jpg)
![4](https://user-images.githubusercontent.com/52146867/60049861-e96ed280-96d7-11e9-9b9f-590ccac3840b.jpg)

**Comment by multimokia** [comment]
You're running a translated version of MAS. I'm afraid this isn't our place to help, you'll want to contact the person who's supplying the translation.

**Comment by Awentor** [comment]
want. how do i contact him?

**Comment by multimokia** [comment]
Not really sure. But as per rules for translations, those who make and distribute translated version of MAS are supposed to handle the tech support for it. Not us. We can only really help you if the problem is caused by something on our end.
