### ISSUE TITLE
Adding hair and dresses

### ISSUE THREAD

**Issue by stormchaser1991** [Monika-After-Story/MonikaModDev#4314]
Can someone help me with adding things I have the pages I think but is there a way to simplify it?

**Comment by LordBaaa** [comment]
I got you fam. I have been adding a bunch of stuff. I’ll comment again when I am home and can help.

**Comment by stormchaser1991** [comment]
> I got you fam. I have been adding a bunch of stuff. I’ll comment again when I am home and can help.

Thanks all that just goes over my head

**Comment by LordBaaa** [comment]
I just remember about this I got caught up in some other stuff. Sorry I forgot about it today. I'll try to remember to talk with you tomorrow. If I forget just pm me on the MAS Discord.

**Comment by bittercaramel** [comment]
woah so im not the only one that thinks that the official instructions are kinda unclear xD 
tho i worked my own way to do this, but since lorbaaa already got that i will just let him explain it

**Comment by LordBaaa** [comment]
Yeah I was planning on writing this anyways so yeah 2 birds but I am just I am double checking everything and covering a lot uses so it is taking longer to write then I though but like is say it will be worth it. It is gonna include all I know includIng condensed templates for various types of sprites an explaination of major items, basic prog points, reactions, some troubleshooting of common errors and some useful console commands when debugging all of which will he in more everyday English. But like I say I am running all of the code I put out so want to make sure all of it will be just plug and play.

**Comment by LordBaaa** [comment]
#4400
