### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Juniorini** [Monika-After-Story/MonikaModDev#4315]
Hi, MAS team! First off, amaizing job, your mod is the best one out there hands down.
Now let's talk about my suggestion. It's a little tidious but i think it would improve the game quie a bit. COuld you make a sequence of Monica singing and playing at the piano her song, Your Reality? I know you can play the song but seeing her performing it should be awesome!

**Comment by multimokia** [comment]
Needs art for this to be possible. Plus getting her hands to move in a way that seems at least somewhat realistic would require some insane timing and a very long atl script to do. It's almost not really feasible to do.

**Comment by Juniorini** [comment]
Where do you get art?

**Comment by multimokia** [comment]
People make it, and for something of this scale, it requires a fair bit of it since it needs a piano image, and several images of her hands moving in different places along the keyboard. (I'll mention that art doesn't exactly come cheap either)

Also, RenPy's animation language (atl) isn't very good, so it's by no means going to be smooth even if we got the art for it. Would be kinda choppy.

**Comment by Rai99** [comment]
![Tem_pay_4_colleg](https://user-images.githubusercontent.com/38822045/60054574-f0322100-96a8-11e9-91e7-a018fe617a1d.gif)

or

Politely and respectfully ask an artist to make what you have in mind, and then you wait.

**Comment by Juniorini** [comment]
What about a crowdfunding to get the art done? Btw I didnt' mean seeing her pressing each tile but just seeing her hands and face change at times. Obviously inlcluding the piano in the image

**Comment by Rai99** [comment]
#1956, #3039, #3089

In short, money complicates things in ways we aren't willing to handle. MAS does not accept donations and is not a business.

**Comment by Juniorini** [comment]
Alright, got it. You may have noticed for my account that I’m new, so I wanted to ask you, do you make little updates frequently or big ones every while? How can I be aware of the latest version of the game?

**Comment by multimokia** [comment]
big ones every while. MAS will notify you if there's an update available.

**Comment by Juniorini** [comment]
Alright I’m gonna close this thread, thank you guys, I may come back with some suggestions next time
