### ISSUE TITLE
Affection problems?

### ISSUE THREAD

**Issue by 00SalAnd** [Monika-After-Story/MonikaModDev#4319]
I'm having problems (I'm not sure though) with my affection. After I say goodbye and I go to check it out, it stops for some reason at Thursday 11 April, although my computer tells me that the file has been modified, so I can't see at what point I am. I'll send the file for whoever checks this out, so just tell me if there are any problems, and if there aren't just how to check affection thanks.

**Comment by 00SalAnd** [comment]
/Users/Me/Desktop/Doki Doki Literature Club/log/aff_log.txt

**Comment by 00SalAnd** [comment]
Wait no

**Comment by Anonymioo** [comment]
Tried to reinstall?

Before doing it you need to backup aff_log. (Optional)

**Comment by multimokia** [comment]
Are you on mac?

**Comment by 00SalAnd** [comment]
@multimokia
Yeah I am

**Comment by 00SalAnd** [comment]
@Anonymioo
I'll try

**Comment by multimokia** [comment]
Your aff_log.txt isn't stored in the main directory anymore because of file permissions. There's updated instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#how-to-view-your-affection) for mac users

**Comment by 00SalAnd** [comment]
@Anonymioo
To be sure I did it right by reinstall you meant redownload the mod and copy-paste it right?

**Comment by multimokia** [comment]
No need to reinstall.

**Comment by 00SalAnd** [comment]
@multimokia
Oh ok thanks

**Comment by 00SalAnd** [comment]
@multimokia
Lifesaver

**Comment by 00SalAnd** [comment]
Hey if you are in the mood to help me how do I ask to hold her?
I can't find it any more and my affection is near 900 so I should be able to.

**Comment by Anonymioo** [comment]
By default it's should be in "Talk -> ... -> Monika... -> Can i hold you?"

**Comment by 00SalAnd** [comment]
It's not there though.

**Comment by 00SalAnd** [comment]
Boy I am dumb as shit
It's only when it is raining and I always prefer the sunny weather I'm stupid

**Comment by 00SalAnd** [comment]
Ok I'm not dumb it's still not there

**Comment by multimokia** [comment]
Repeat Conversation > Weather > Sounds of Rain

**Comment by 00SalAnd** [comment]
Thank you
