### ISSUE TITLE
Ummm...I need some help when I download the update

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#4321]
v0.9.4 - The Spring Cleaning Update

Their are no new dialogue nor new event and I cant give her gift like hair clip  is their something with my copy paste?
![pROBLEM](https://user-images.githubusercontent.com/43478681/60107638-d290b480-9799-11e9-961b-76744a93256d.PNG)

**Comment by multimokia** [comment]
You installed a level too high. All files get extracted to `game/` not `ddlc/`

**Comment by Axone00** [comment]
should I delete the extra ? or should I just put it in the game?

**Comment by multimokia** [comment]
you can just move all the `.rpyc` files, the `mod_assets`, `gui`, and `python-packages`, folders into `game/`. But a reinstall works fine too, and is more thorough, just in case you forgot to move something.

**Comment by Axone00** [comment]
Okay I will try thank you

**Comment by Axone00** [comment]
It Works ! thank You ! Bless You !

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
