### ISSUE TITLE
Disappearing existing gifts.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4322]
I try to explain. 
I gave Monika 'Roses.gift'. 
Then i gave her 'Hotchocolate.gift' she dissapeared and there only Chair. And disappeared 'Roses.gift'.
And when Monika back 'Roses.gift' showed up back.

P.S. It's happening if create .gift(s) when MAS open.

Pardon if it's normal.

**Comment by Professor-JMO** [comment]
It's _Normal_.

**Comment by multimokia** [comment]
This is a limitation of the ACS system. All ACS that are worn are 'tied' to Monika, so when she goes elsewhere, so do the ACS. Not much we can do about this, and as such this is intended behavior.

**Comment by Anonymioo** [comment]
Alright then.
