### ISSUE TITLE
[Suggestion] going to game for a bit

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#4325]
How about instead of a description of what the game is like you can say what genre the game is, like you could say that you're playing an adventure game instead of a "story driven game"

**Comment by Rai99** [comment]
That would be a lot of genres to account for, but it might be better to move this to its own separate topic with a scrollable menu, since you could argue that the game idle has a bit too much for a brb type topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
