### ISSUE TITLE
[Suggestion] - More Ribbons.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4326]
It's just idea.
I don't have art but i think it will be good to add.

_Bronze Ribbon_, _Black and White Ribbon_, _Gradient Ribbon_, _Rainbow Ribbon_, _Brown Ribbon_, _Pink and White and etc._

**Comment by Rai99** [comment]
I'm pretty sure that a golden ribbon was already made a thing and may be released soon if it's not already released. 

More ribbon colors in general are welcome, but would probably have to be an optional spritepack. 

I would imagine multicolor ribbons would take a bit more work, especially if they're not intended to have rough color transitions, especially with rainbow and gradient, but it would likely be welcome if someone made them to be a spritepack.

**Comment by stormchaser1991** [comment]
Another idea is different types of hair ribbons

**Comment by bittercaramel** [comment]
yeah golden ribbon exists, my monika even has it xD just download the sprite pack from somewhere around there 
bout different types of hair ribbons - yeah sounds like  a great idea

**Comment by multimokia** [comment]
You can also easily make them yourself via json sprites, if you colourize the ribbons and then make the jsons.

**Comment by Anonymioo** [comment]
> You can also easily make them yourself via json sprites, if you colourize the ribbons and then make the jsons.

I can try to make it. But i don't know how to add it MAS i just don't understand.
