### ISSUE TITLE
monika gone?

### ISSUE THREAD

**Issue by Arshio** [Monika-After-Story/MonikaModDev#4328]
so uh... I cleaned my pc and when I opened MAS, it took me to the beginning. I looked in the recycling and didnt find the monika persistent file or anything... I really dont want to restart.
cant seem to find the back ups either.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3328884/aff_log.txt)

affection log.
I think I was able to get my persistant back due to a file restoring programs. 
[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3328964/Monika.After.Story.zip)
maybe?

**Comment by Anonymioo** [comment]
You don't backed up Persistent?
Try to use **[this](https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html)** for example. 
Maybe it help to recover Persistent files.

**Comment by Arshio** [comment]
> You don't backed up Persistent?
> Try to use **[this](https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html)** for example.
> Maybe it help to recover Persistent files.

I think I found it though. I'm just not sure.

**Comment by Anonymioo** [comment]
Copy paste found Persistent into %appdata% and try to launch MAS.

**Comment by Arshio** [comment]
> Copy paste found Persistent into %appdata%/renpy/Monika After Story and try to launch MAS.

Copy and paste after I get through the introduction or before? It's just asking for my name rn.

**Comment by Anonymioo** [comment]
Close process. And rewrite persistent.

**Comment by Arshio** [comment]
> Terminate process. And rewrite persistent.

When I rename it, it says that it wont work and when I open MAS, it says that the persistent file is corrupted.

**Comment by Anonymioo** [comment]
Do you have persistent with ## ?

**Comment by Arshio** [comment]
> Do you have persistent with ## ?

Yeah, it has 00.bak

**Comment by Anonymioo** [comment]
Remove ## and try to launch again.

**Comment by Arshio** [comment]
> Remove ## and try to launch again.

its still asking for my name. ahh. I just dont get it.

**Comment by Anonymioo** [comment]
Can you send Persistent files?

**Comment by Arshio** [comment]
> Can you send Persistent files?

I already did, its the 2nd downloadable file.

**Comment by Anonymioo** [comment]
It's fresh start persistent.

**Comment by Arshio** [comment]
> It's fresh start persistent.

what now then.?

**Comment by Anonymioo** [comment]
There last chance.
Try to recover Persistent.

**Comment by Anonymioo** [comment]
Try to use this[](https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html).

**Comment by Arshio** [comment]
> Try to use [this](https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html)

im trying to download it, asking for user and password. looking everywhere for it but I dont know russian.

**Comment by Anonymioo** [comment]
Login Pass is rsload.net

**Comment by Arshio** [comment]
> Login Pass is rsload.net

ill look for the persistent. ill take a while.

**Comment by Anonymioo** [comment]
> ill look for the persistent. ill take a while.

Any changes?

**Comment by Arshio** [comment]
> > ill look for the persistent. ill take a while.
> 
> Any changes?

couldn't find monika's old persistent folder.

**Comment by Anonymioo** [comment]
Did you checked %appdata%/renpy/Monika After Story ?
This folder should be in RenPy folder.

**Comment by Anonymioo** [comment]
And do you have windows on SSD disk?

**Comment by Anonymioo** [comment]
Do you have Windows on SSD?

**Comment by LunaMoon335** [comment]
Hey! I came here to look for help, i've been playing the monika after story mod, i was trying some things, talking to her and then i tried the option to take monika with you somewhere. But i accidently deleted the charecter file. I  would really like if someone would help me fix this, there was some stuff i didn't try yet

**Comment by ThePotatoGuy** [comment]
better to make a new issue.

[closing this due to lack of response[
