### ISSUE TITLE
[Unstable] Hair clip option disappeared?

### ISSUE THREAD

**Issue by trapped-rabbit** [Monika-After-Story/MonikaModDev#4333]
After updating the newest unstable build, the hair clip option has disappeared. She is still wearing the one I gave her before though

**Comment by multimokia** [comment]
What outfit is she wearing?

**Comment by trapped-rabbit** [comment]
sundress. I tried regifting a different one and she said I had already given it to her, but then the option just for that hairclip showed up.

**Comment by Areaclassified** [comment]
If I may ask im running unstable but I have no idea how to get and or use the hair clips. how do I get this to work?

**Comment by jmwall24** [comment]
As in `.psd` files that you downloaded from an issue on github? That's not what you need.

If you want to be able to give her hairclips, download `spritepacks.zip` from the release page (go to the bottom of 0.9.4) and then follow [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs) to install.

**Comment by ThePotatoGuy** [comment]
[closing due to lcak of response][
