### ISSUE TITLE
[Suggestion] - Ability to speak out Monika.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4336]
It may be can useful. 
For example M: Is there something disturbing you? Tell me i'm listening.

Or it's already implemented?

**Comment by multimokia** [comment]
Only problem with this is that there's no way for her to hear you, let alone have a genuine response to what you did, even if she could hear you since it's too open ended to respond to.

**Comment by Anonymioo** [comment]
Hmmm it was bad example.
I meaned i know she can't 'hear'. 
But she can use response like: 'Do you feel better?'. After ending. Or something like that.
It can help when you're angry or just want to speak out about some things.

**Comment by multimokia** [comment]
Iirc we already have this in one of the moods (either angry or sad)

**Comment by Anonymioo** [comment]
Alright i didn't knew it was added only in 'sad' how i remember or idk.
