### ISSUE TITLE
[Suggestion] - Fading poses.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4337]
For example when Monika tells something and blushes. In the end she sharply back in default pose.
It can be a little confusing. She moment ago was blushed and now she just sitting.
Maybe it can be somehow smoother?

Or just make last pose in topic continue for some seconds? 
Is it possible to do?

**Comment by multimokia** [comment]
There's a reason we don't do this, dissolving into idle has a bit of a seizure effect to it, which we *think* we've finally fixed with #4317. Adding more dissolves may just bring this back and make it worse.

**Comment by Anonymioo** [comment]
Alright. Closing
