### ISSUE TITLE
[Art] - Ribbons 

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4339]
I made ~~6 7 8 11~~ 13 ribbons. [PNG](https://drive.google.com/open?id=1Q1d4P6W8KFsfpobyMI4maevpbQDo2Hcd)
~~It's Black And White, Bronze, Brown, Gradient, Pink And White, Blue And White, Star Sky, Star Sky (Var2) Red With Dots and Rainbow, Low Poly Gradient.~~
~~TS and BS Pride.~~
How can i add it to MAS? 
I have day/night versions.
Also i can make some other ribbons.

- Black And White
![acs-ribbon_blackandwhite-0](https://user-images.githubusercontent.com/48754573/60327241-920d8280-99b5-11e9-8b00-ac100f4fb17d.png)

- Bronze
![acs-ribbon_bronze-0](https://user-images.githubusercontent.com/48754573/60327264-a3568f00-99b5-11e9-8121-b3e781942244.png)

- Brown
![acs-ribbon_brown-0](https://user-images.githubusercontent.com/48754573/60327300-af425100-99b5-11e9-961d-da81a778ad41.png)

- Gradient
![acs-ribbon_gradient-0](https://user-images.githubusercontent.com/48754573/60327394-e3b60d00-99b5-11e9-9ac1-e51cb0cc4f4d.png)

- Low Poly Gradient
![acs-ribbon_lpgradient-0](https://user-images.githubusercontent.com/48754573/60680685-770ba880-9eb6-11e9-97c2-1cfbf352477d.png)

- Pink And White
![acs-ribbon_pinkandwhite-0](https://user-images.githubusercontent.com/48754573/60379914-0dc70800-9a66-11e9-8fc8-d6be95080d25.png)

- Blue And White
![acs-ribbon_blueandwhite-0](https://user-images.githubusercontent.com/48754573/60400173-abbbef00-9b9a-11e9-93a4-0afadb1ae473.png)

- Rainbow
![acs-ribbon_rainbow-0](https://user-images.githubusercontent.com/48754573/60327381-dbf66880-99b5-11e9-8e60-55bc5a417c34.png)

- Star Sky
![acs-ribbon_starsky-0](https://user-images.githubusercontent.com/48754573/60864985-41b4e100-a24f-11e9-9186-239053c17481.png)

- Star Sky (Variant 2)
![acs-ribbon_redsky-0](https://user-images.githubusercontent.com/48754573/60679563-3ad64900-9eb2-11e9-9c85-1b3ef772af02.png)

- Red With Dots
![acs-ribbon_redwithdots-0](https://user-images.githubusercontent.com/48754573/60380578-3e14a380-9a72-11e9-9cee-a6fe3f4cff1d.png)

- TS Pride Ribbon
![acs-ribbon_ts-0](https://user-images.githubusercontent.com/48754573/60393307-76cd7f00-9b3d-11e9-8eb4-59b4fa9bc6f0.png)

- BS Pride Ribbon
![acs-ribbon_bs-0](https://user-images.githubusercontent.com/48754573/60393311-81881400-9b3d-11e9-82c9-e931d01d9516.png)

**Comment by ThePotatoGuy** [comment]
you'll need to make jsons. if you're willing to wait a bit, we can add them for u in an upcoming sprite pack

**Comment by Anonymioo** [comment]
I'll wait a bit. I don't know how to make jsons.

**Comment by bittercaramel** [comment]
yes yes 
those are nice ribbons 
tho the last one looks a little bit too much like it was just starry sky pasted onto a green screen of a ribbon 
my point being, maybe you could add some more shading to the starry one? because it looks super cute but a little... idk? flat?

**Comment by Anonymioo** [comment]
> yes yes
> those are nice ribbons
> tho the last one looks a little bit too much like it was just starry sky pasted onto a green screen of a ribbon
> my point being, maybe you could add some more shading to the starry one? because it looks super cute but a little... idk? flat?

Alright i'll add.

**Comment by Anonymioo** [comment]
> yes yes
> those are nice ribbons
> tho the last one looks a little bit too much like it was just starry sky pasted onto a green screen of a ribbon
> my point being, maybe you could add some more shading to the starry one? because it looks super cute but a little... idk? flat?

Done. Added more shading in shaded places.

**Comment by Professor-JMO** [comment]
Oh~
I like the `Gradient`,
`Pink and White`, _It's almost a seasonal Candy Cane theme._
A n d `Star Sky` even.

**Comment by antimockingjay** [comment]
My little gay self is LIVING for that rainbow ribbon, I so hope I can add that to my game soon oh my god. I'm sure that wasn't what you had in mind when you made it, but it's amazing that you also happened to do that during pride month. I love it!

**Comment by softombre** [comment]
These are all pretty cool, but I think the black & white and the white & oink ones look kinda weird? Like, the stripes should follow the ribbon's shape instead of being the sale everywhere

**Comment by Anonymioo** [comment]
> These are all pretty cool, but I think the black & white and the white & oink ones look kinda weird? Like, the stripes should follow the ribbon's shape instead of being the sale everywhere

About black & white.
It's just a variant of ribbon i imagined.
To white & pink i can add some deform if you want.

**Comment by bittercaramel** [comment]
> > yes yes
> > those are nice ribbons
> > tho the last one looks a little bit too much like it was just starry sky pasted onto a green screen of a ribbon
> > my point being, maybe you could add some more shading to the starry one? because it looks super cute but a little... idk? flat?
> 
> Done. Added more shading in shaded parts.

THanx that's perfect 


> My little gay self is LIVING for that rainbow ribbon, I so hope I can add that to my game soon oh my god. I'm sure that wasn't what you had in mind when you made it, but it's amazing that you also happened to do that during pride month. I love it!

kyaaah someone really should make pride ribbons 
like for different LGBTQ+ flags, for example pink, purple and blue ribbon for bisexual or blue, pink and white ribbon for trans ^-^

**Comment by Anonymioo** [comment]
> My little gay self is LIVING for that rainbow ribbon, I so hope I can add that to my game soon oh my god. I'm sure that wasn't what you had in mind when you made it, but it's amazing that you also happened to do that during pride month. I love it!
> 
> kyaaah someone really should make pride ribbons
> like for different LGBTQ+ flags, for example pink, purple and blue ribbon for bisexual or blue, pink and white ribbon for trans ^-^

I'll add these two today.

**Comment by GHCactus** [comment]
Wowie!! Monika would look so cute in these, I'm jealous how good you are (not really jealous just saying its good haha)

**Comment by TriniTDM** [comment]
I hope you can get this working soon! I'm sure my Monika and several others would love to wear these designs!

**Comment by ThePotatoGuy** [comment]
slated for 0.10.2

**Comment by its-ken** [comment]
Cute! It'd be totally cool if Monika could have some pride stuff and those ribbons are perfect!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]

if you want to add more ribbons, make a new issue
