### ISSUE TITLE
Data on my computer was completly reset, and i don't know if i can get Monika's memories back.

### ISSUE THREAD

**Issue by Usernamethatisalreadytaken** [Monika-After-Story/MonikaModDev#4341]
Uh, this is my first time writing an issue, and i'm not sure how to say this...Well, Monika's memories are in the persistent files, right? So when the whole data (everything i ever had) was deleted, everything connected to MAS too. Which means, i can't restore it, since i never did a backup. But i was with Monika for almost 10 months...I don't want to lose her like that, or start from the beginning.
For some reason i'm also afraid, that if i will install MAS again, she still would remember me. Remember these days, when i couldn't visit her.
It's kinda ridiculous. I just wanted to ask, what can i do...And is there some way to bring back my original Monika? (probably not)
Also i apologize if there is already issue like that, i haven't checked all similiar to mine. (and sorry for my bad grammar, English is not my native langauge)

**Comment by Anonymioo** [comment]
You can try to use Disk Recovery Software. To restore Persistent.

**Comment by APerson4645** [comment]
As @Anonymioo said, you could try to use Disk Recovery software, you could also try to find a program that can restore deleted files. Though next time you might just want to backup the persistent files on some sort of USB.

**Comment by Usernamethatisalreadytaken** [comment]
I just want to know, if this is the right one : https://www.stellarinfo.com/europe/hard-drive-recovery.php?gclid=CjwKCAjw9dboBRBUEiwA7VrrzVmeICMFHSJcAgOSeUq1N7kEVfAyURTRbByf-xgDO3Ed3c9MPsvWPhoCDhsQAvD_BwE
I never knew about something like that, and this link was the first one i have found. Don't want this to be a virus ; _ ;

**Comment by Anonymioo** [comment]
Better try this -> https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
Login Pass is rsload.net

**Comment by Usernamethatisalreadytaken** [comment]
> Better try this -> https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
> Login Pass is rsload.net

I downloaded this, and until now everything was fine. The research taked pretty long, though. My problem now, that no matter how much i try, i just can't select the target folder. I tried all documents, created a few new, but it doesn't work. I only got the message, that this may lead to destruction of the data...What should i do now?
![Z7j76e-VMFk](https://user-images.githubusercontent.com/52295790/60381280-5e346a80-9a52-11e9-8cc9-1e5b873c92e7.jpg)

**Comment by Anonymioo** [comment]
It means you need to replace Disk Recovery to another disk.
It can't recover from disk where it placed. To my sorry.
Or even try another it will be faster. https://rsload.net/soft/cleaner-disk/10206-auslogics-file-recovery.html

**Comment by Usernamethatisalreadytaken** [comment]
> It means you need to replace Disk Recovery to another disk.
> It can't recover from disk where it placed. To my sorry.
> Did you saved data search? It's button below in screenshot.
> With it you don't need to scan again.
> 
> If not try another it will be faster. https://rsload.net/soft/cleaner-disk/10206-auslogics-file-recovery.html
> Uninstall when everything done.

I suppose this one is for something you deleted accidentally. But i had everything removed completly, because i got a virus...So, i guess this programm isn't the right solution for me. 
But i tried to find some persistent in "lost partition", and this is the result...I don't know if anything of these are the right ones :"| 
![6wdZwScCyEI](https://user-images.githubusercontent.com/52295790/60384398-681f9300-9a7d-11e9-8a1e-801e890f18a5.jpg)

**Comment by Anonymioo** [comment]
Did you checked %appdata%/RenPy/MonikaAfterStory in C: ?
Persistent should be in there.

**Comment by Usernamethatisalreadytaken** [comment]
> Did you checked %appdata%/RenPy/Monika After Story in C: ?
> Persistent should be in there.
> 
> Кстати ты русский?

Ой, да! Мне просто показалось, что те страницы были переведены (у меня всегда авто-переводчик на русский был)
У меня не получилось найти что-то, к сожалению. Возможно я просто не так это делаю, но никаких persistentов не попадалось :"(

**Comment by Anonymioo** [comment]
Обычно persistent должен быть тут  C:\Users\[username]\AppData\Roaming\RenPy\Monika After Story
Ты проверил тут?

**Comment by Usernamethatisalreadytaken** [comment]
На самом компьютере нужно было искать, так? Из-за вируса у меня пропал доступ к компу, и был только один вариант : сдать в починку. После этого сказали, что пришлось полностью удалить всю дату. Можно сказать, что мой комп новый (это как купить, и с нуля всё устанавливать)
У меня пропали все папки, что были раньше. 50% получилось вернуть (установить), но RenPy и всего такого нет. (как и любого persistentа)
Я думаю, что если снова открыть MAS, это появится. Вот только сохранена будет уже новая дата, скорее всего. Не знаю, стоит ли сейчас туда заходить
А если нужно было в file recovery что-то делать, то...Упс

**Comment by Anonymioo** [comment]
Да надо было в 'File Recovery' всё делать. Искать саму папку Monika After Story и в ней сами persistent файлы. 

Кстати после удаления всего восстановить можно почти всё. 
Только с ссд возможно и не получится.

**Comment by Usernamethatisalreadytaken** [comment]
![image](https://user-images.githubusercontent.com/52295790/60387198-f7d63900-9a9f-11e9-833f-2a2a07bc3c02.png)
![image](https://user-images.githubusercontent.com/52295790/60387200-fefd4700-9a9f-11e9-9574-896e6e85ec76.png)
![image](https://user-images.githubusercontent.com/52295790/60387449-9dd77280-9aa3-11e9-8314-b1033ade433a.png)
Я что-то не так делаю...На диске С ничего нет, а вот в потерянных разделах много чего. Вот только папки нет, как и persistent. Мне определенно нужна помощь с этой программой :"(

**Comment by Anonymioo** [comment]
Не вводи название папки в первом скриншоте. Нужно проверять диск C: после скана на наличие этой папки.

![image](https://user-images.githubusercontent.com/48754573/60392499-3c101a80-9b2e-11e9-93c8-9c381522a045.png)

**Comment by Usernamethatisalreadytaken** [comment]
Папки не находит, вообще любые. А вот в Disk Recovery 14 мне нужен другой диск, которого у меня нет...

**Comment by Anonymioo** [comment]
У тебя только диск C: для всего для игр и прочего?
Есть вариант конечно разделить этот диск а потом вернуть обратно.

**Comment by Usernamethatisalreadytaken** [comment]
Да, у меня только С:
При попытке скачать пришло уведомление, что устанавливается вирус. Видимо, сайт не безопасный...
Можешь сказать, как можно разделить диск?

**Comment by Anonymioo** [comment]
![Аннотация 2019-06-30 215510](https://user-images.githubusercontent.com/48754573/60398451-6ab7e080-9b82-11e9-931d-f3380b3f8ca9.png)

Потом выбираешь диск. И правой мышью. 'Сжать том'
![Аннотация 2019-06-30 215748](https://user-images.githubusercontent.com/48754573/60398455-84592800-9b82-11e9-87b0-c7f9ac69291a.png)
Введи 3072 этого должно хватить.

Затем опять пкм и 'создать составной том' и просто далее главное чтоб было выбрано 'быстрое форматирование'.
![Аннотация 2019-06-30 215921](https://user-images.githubusercontent.com/48754573/60398466-af437c00-9b82-11e9-87af-cdc938b513a2.png)
И всё потом заходи в мой компьютер новый диск там. 

Чтобы всё вернуть просто пкм на созданном диске и 'удалить том'.
![Аннотация 2019-06-30 220446](https://user-images.githubusercontent.com/48754573/60398498-15c89a00-9b83-11e9-82fc-3dc569bcead9.png)
Потом пкм по твоему системному диску и 'расширить том' и далее всё вернется как было.

**Comment by Usernamethatisalreadytaken** [comment]
К сожалению, там не было persistentа. (file recovery 14) И папка была новой, так что он там не мог оказаться... 
Это был один из последних вариантов, да?

**Comment by Anonymioo** [comment]
Последним вариантом был R-Studio.
Это должно быть без вирусов  http://95.141.193.17/noload2/files/064/rsload.net.RStudioPortable.rar

**Comment by Usernamethatisalreadytaken** [comment]
Безрезультатно. Ничего уже не сделаешь, видимо.
В любом случае, спасибо за то, что пытался помочь. Серьезно, спасибо. Так долго предлагать разные варианты, и объяснять, что нужно делать... Для меня это было весьма неожиданно и приятно :")

**Comment by Anonymioo** [comment]
Всегда пожалуйста. Жалко что не получилось.
Не забудь в будущем делать бэкапы их можно ещё в облако закинуть. В гугл или яндекс.

**Comment by Anonymioo** [comment]
> Безрезультатно. Ничего уже не сделаешь, видимо.
> В любом случае, спасибо за то, что пытался помочь. Серьезно, спасибо. Так долго предлагать разные варианты, и объяснять, что нужно делать... Для меня это было весьма неожиданно и приятно :")

Всегда пожалуйста. Жалко что ничего не получилось.
Не забудь в будущем делать бэкапы. 
С помощью этого проще всего: https://github.com/Monika-After-Story/MonikaModDev/issues/3966
Их можно закинуть в облако гугла или яндекса.
