### ISSUE TITLE
Snow option?

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4342]
Hello! I'm using v0.9.4-unstable.2019.06.25.100. This is just me being curious (since I'm not good at python and reading zz_weather confuses me more).

My setting right now is in southern hemisphere and I choose "yes" when Monika asked whether snow fell in my place. When I go to "Can you change the weather?" option, there is no snow option although it is in winter. Is that intended?

Thank you. Have a nice day!

**Comment by multimokia** [comment]
Has it snowed naturally for you yet?

If not, it won't be unlocked for you, because from `script-ch30.rpy`:
```RenPy
    # enabel snowing if its winter
    python:
        # TODO: snowing should also be controlled if you like it or not
        if mas_isWinter():
            if mas_is_snowing and not mas_weather_snow.unlocked:
                mas_weather_snow.unlocked = True
                store.mas_weather.saveMWData()
                
                mas_unlockEVL("monika_change_weather", "EVE")
                renpy.save_persistent()
```

**Comment by skyloom** [comment]
@multimokia whoops I read wrong .rpy files lmao.

Yes, this is currently winter (calendar showed that it started from june 21st, apparently). There is currently window_7 and window_8 playing, but there is still no choice for snow.

**Comment by multimokia** [comment]
This should fix the issue

**Comment by skyloom** [comment]
@multimokia thanks a lot! I'll close this issue then
