### ISSUE TITLE
[Suggestion] - Achievement System

### ISSUE THREAD

**Issue by Zensu-senpai** [Monika-After-Story/MonikaModDev#4347]
Would be worth thriving if you put up achievements and players would have to unlock them, making them stay a bit longer to spend time with Monika. No offense to people out there that literally spends longer time with her, but, I think it's worth staying while having objectives in the game.. Like, for example: 'Beat Monika at Chess' or 'Reach Affection at 200' and Monika would be the one to deliver a message once unlocking an achievement. Could be nice though..

**Comment by Rai99** [comment]
If anything, I think just reaching the next affection level is its own reward. I don't think MAS would benefit from this kind of gameification. Personally, I don't think this fits the theme of MAS, and I think it would be pretty immersion breaking for Monika to tell you that you got an achievement. The focus should be Monika, not some achievements Monika announces to you. 

Even then, I don't know what meaningful achievements there could be. They would probably encourage people to do things they might not want to, such as playing certain games, and we don't want to impose that kind of incentive if they don't want it. It might also encourage people to cheat to get a specific achievement, despite not meaning anything.

**Comment by ThePotatoGuy** [comment]
this is considered using the ddmm api in the `achievements` branch. No plans atm.

[closing until we look into it]
