### ISSUE TITLE
[Suggestion] - Expand on the "I'm going to game"?

### ISSUE THREAD

**Issue by MASSuggestion** [Monika-After-Story/MonikaModDev#4350]
Personally, I like the "I'm going to game" option. But my computer also isn't powerful enough to run DDLC with another game. I figure that there could be an extra segment to the "I'm going to game" that allows you to tell her that you can't run DDLC with another game due to the specs of your computer or something like that. Might be poking around too much for the user comfort but Monika could check your computer specifications and decide for herself whether or not your computer is powerful enough but I think she'd trust you enough to not do that.

**Comment by Anonymioo** [comment]
Goodbye -> I'm going to play another game.

**Comment by MASSuggestion** [comment]
> Goodbye -> I'm going to play another game.

Not sure if that's already an option in the game, I don't see it. But yeah, something like that would be nice.

**Comment by Anonymioo** [comment]
It's already in game. In unstable.

**Comment by MASSuggestion** [comment]
> It's already in game. In unstable.

Guess I'll have to grab the unstable version then. Been thinking of downloading the developer version anyways.

**Comment by Anonymioo** [comment]
Same. I just thought in unstable will be more features.

**Comment by ThePotatoGuy** [comment]
everything in unstable will reach official version at some point, do not use unstable unless you are fine with the risks it entails.

**Comment by ThePotatoGuy** [comment]
added in #4130
