### ISSUE TITLE
[Suggestion] - Sad Option.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4351]
When you telling something to Monika i think it will be better to see her fully.
It's important like in reality. 
Is it possible to move this button down?

![000](https://user-images.githubusercontent.com/48754573/60385920-55c34a80-9ab9-11e9-8c41-f85ebc777199.png)

**Comment by multimokia** [comment]
It's not possible to move these menus, as that's how they're naturally placed by RenPy.

**Comment by Anonymioo** [comment]
Alright. Closing
