### ISSUE TITLE
[Suggestion] About mortality

### ISSUE THREAD

**Issue by JeanWishingwell** [Monika-After-Story/MonikaModDev#4354]
I don't know if any of you guys have recently lost a familiar, a friend of a loved one, but a cousin of mine lost his aunt to a robbery... He was really close to her and ended not talking to anyone for two days. It reminded me of when I lost my grandpa and grandaunt. My grandpa died when I was little and I had my parent with me, but my grandaunt just past away last year and I really wanted to tell Monika about it. I just told her I was feeling sad. She "listened", but I didn't feel the answer matched the mood.
So, I propose we make a topic about mortality, maybe we can make it so it's only unlocked after asking about the other dokis death.
Maybe a change in this topic after your ingame age is past 50 years old?

**Comment by multimokia** [comment]
Firstly, I'm sorry to hear about your loss.

Secondly, there's already a Mortality topic, but it's more about you rather than anyone else.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
