### ISSUE TITLE
Notifications Don't Work On Linux

### ISSUE THREAD

**Issue by zombiepigdragon** [Monika-After-Story/MonikaModDev#4356]
To be more specific, I am running KDE Plasma on Kubuntu 19.04. There is no notification nor sign that there was an attempt to show one.

**Comment by ThePotatoGuy** [comment]
1. make sure you enabled Alerts in settings
2. we run shell cmd `notify-send`, so if you don't have that program then it won't work

**Comment by zombiepigdragon** [comment]
I found the issue: it only works when notify-send is available. The instant I installed `libnotify-bin`, it worked just fine. Would it be better to just check for `notify-send` and give a warning if it's not found, or should there be multiple methods of notification?

**Comment by zombiepigdragon** [comment]
(Just to clarify, I'm willing to add either of those options myself, if the devs don't want to deal with the minority platform.)

**Comment by ThePotatoGuy** [comment]
if you can add that yourself, can you pr it then? Would save us time.

**Comment by zombiepigdragon** [comment]
Which would you prefer? A warning when it won't work (basically just a label saying "`notify-send` not found") or a handful of alternate commands?

**Comment by ThePotatoGuy** [comment]
what other notify commands are there? 

A "warning" wouldn't actually be a warning, it would likely be checking if the program is installed during startup, then pushing some dialogue so Monika could notify the user that they need to install libnotify if they want notifications.

Adding @multimokia cause those checks would need additional persist vars and startup code.

**Comment by zombiepigdragon** [comment]
Until I downloaded notify-send, I had `kdialog --title "Monika" --passivepopup "Hello There".`
I'm sure there's at least a few others.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
