### ISSUE TITLE
Noticed she is blinking 0.9.5

### ISSUE THREAD

**Issue by LordBaaa** [Monika-After-Story/MonikaModDev#4359]
Monika is now blinking for me and someone I know. I didn't see this in the releases information. Also I was looking though the code to try and find the code for it, I can't seem to find it. I personally think the blinking is a bit two fast and I would like to tweak it. Thanks

**Comment by multimokia** [comment]
#4241 
Fair warning, it's a lot of lines you're going to need to change.

**Comment by LordBaaa** [comment]
Uh could you give me an idea of where they the lines I'm looking for are? When I search for blinking I find nothing and the issue you linked I didn't really what I was looking for.

**Comment by LordBaaa** [comment]
Or actually I think I found it but I don't understand how it works

**Comment by multimokia** [comment]
Blinking involved modifying every single sprite definition to a new type in ATL format. You're looking at editing literally all of `sprite-chart-20.rpy` and `sprite-chart-21.rpy`

**Comment by LordBaaa** [comment]
Okay well first of all I can just do a find and replace so no big but it says time between blinks. I want to know how adjust how fast the blink is not how often it happens

**Comment by jmwall24** [comment]
also, you'd have to do this literally every single update

**Comment by ThePotatoGuy** [comment]
if you want to change blinking for yourself, then go ahead, but we're not going to offer support for doing so.

**Comment by LordBaaa** [comment]
So you are saying you are not gonna tell me how to do it?

**Comment by multimokia** [comment]
https://www.renpy.org/doc/html/atl.html
