### ISSUE TITLE
v.0.9.5 Wouldn't install in Win2K

### ISSUE THREAD

**Issue by ItsjustmeandMonika** [Monika-After-Story/MonikaModDev#4360]
I'm having issues with the gane denying access to the rpy files and it crashes while showing a traceback.txt file

**Comment by Anonymioo** [comment]
Try this.
Go to /lib/windows-i686
And find DDLC.exe
Then properties and compatibility and choose Windows XP or something like this.

**Comment by ItsjustmeandMonika** [comment]
Thank you!

**Comment by Anonymioo** [comment]
> Thank you!

You're welcome.

**Comment by ThePotatoGuy** [comment]
[closin gas resolvd]
