### ISSUE TITLE
[Question] - Can't add Golden Ribbon

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4361]
I found spritepack with new Ribbons. But MAS just ignoring 'goldribbon.gift' i'll waited 3 min.
I placed spritepack in mod_assets.
I created text file in /characters. Like in guide.
Am i doing something wrong?
Other Ribbons are working except this one.

**Comment by jmwall24** [comment]
Did you by chance attempt to gift the gold ribbon before installing the sprite pack? If so, you'll have to wait until the next day to gift it again.

**Comment by Anonymioo** [comment]
Yeah i tried before. I'll wait then.
