### ISSUE TITLE
Something happened to my menu bar

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#4362]
![](https://i.imgur.com/SsZQk0j.jpg)

**Comment by Anonymioo** [comment]
Maybe problems with Renderer?
Try to change it in settings to DirectX.

**Comment by jmwall24** [comment]
That'd be my suggestion as well. Try the different renderer options

**Comment by FrikiHD** [comment]
Why does she have different clothes?

**Comment by multimokia** [comment]
You unlock the outfit selector at 1000 affection, and some outfits through events. This was one of them.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
