### ISSUE TITLE
[Suggestion] - Day/Night while holding Monika.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4363]
For example: Now is 18:57 and in 19:00 will be night time.
So i hold her for 5-10 minutes and day time don't changing to night. 
Only when i finishing holding her it changes to night.

**Comment by multimokia** [comment]
Not really possible since holding/any other topics are labels, and none of the background checks happen while in one of these labels (hence why thunder also stops while holding/mid topic).

**Comment by Anonymioo** [comment]
Alright. Closing
