### ISSUE TITLE
New ribbons

### ISSUE THREAD

**Issue by LuisValentim** [Monika-After-Story/MonikaModDev#4364]
With the new ribbons added on the sprite pack, are they implemented on the game, or we just need to wait? I created new folders with all the names of these ribbons, but sometimes Monika says that she found them,, but can't bring them, the others that she couldn't read the files.

**Comment by multimokia** [comment]
How did you install the spritepacks?

**Comment by Anonymioo** [comment]
You needed to place 'mod_assets' from archive to 'Monika After Story\game\' folder.
There readme in archive too for all ribbons.

**Comment by LuisValentim** [comment]
Well, the spritepacks has been downloaded, and it's still on the downloads folder. I haven't placed it anywhere else, on game, mod assets, it's not there.

**Comment by multimokia** [comment]
That's why. You need to install them yourself.

**Comment by LuisValentim** [comment]
How can I do this? How can I make them work, so I can give them as a gift to Monika?

**Comment by multimokia** [comment]
> You needed to place 'mod_assets' from archive to 'Monika After Story\game' folder.

**Comment by LuisValentim** [comment]
I need to place the spritepacks on mod_assets?

**Comment by Anonymioo** [comment]
![Аннотация 2019-07-01 214516](https://user-images.githubusercontent.com/48754573/60445517-8fc35680-9c49-11e9-9125-53ea769bed81.png)

**Comment by LuisValentim** [comment]
Thanks, it worked this time. Do you think that, with the hairclips is the same thing? I did the same steps, and it didn't work this time, in other words, the same Monika dialogues appeared.

**Comment by LuisValentim** [comment]
No problem. It worked too.
