### ISSUE TITLE
[Outfit - Casual] Pink Shirt

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#4367]
![upright pinkshirt](https://user-images.githubusercontent.com/1176163/60513617-04dd6d00-9cd8-11e9-8bdf-704e9aed1bf4.png)

![leaning pinkshirt](https://user-images.githubusercontent.com/1176163/60467688-98228e00-9c57-11e9-94c3-cb090795832a.png)

Based on this piece of art (by kokomi on Pixiv):
![1512014706045](https://user-images.githubusercontent.com/1176163/60467081-d7e87600-9c55-11e9-9d06-5b1abc8940de.png)

PSDs:
[Gdrive](https://drive.google.com/drive/folders/1ujoaBzWPMvOmnPbzNIWDNQeWkgf-pfQM?usp=sharing)

**Comment by zombiepigdragon** [comment]
Looks cool man!

**Comment by ItsjustmeandMonika** [comment]
So pretty,even with the game sprite...

**Comment by antimockingjay** [comment]
Oh my god, I love this more than I can even put into words. Amazing work!

**Comment by Velius94** [comment]
Decided to give it a bit of rework, so there's now actual details. Leaning soon.

![new shades](https://user-images.githubusercontent.com/1176163/60928002-10b6c980-a2ac-11e9-9413-a399bc469143.png)

**Comment by LordBaaa** [comment]
Looks great, can't wait to add it to my MAS!

**Comment by Velius94** [comment]
Leaning redone.
![leaning night](https://user-images.githubusercontent.com/1176163/60963639-9b7ddf80-a311-11e9-91a3-f0a771e4855d.png)

**Comment by Jancio2137** [comment]
How to add? this this looks amazing

**Comment by LordBaaa** [comment]
@Jancio2137 you can read my article about it here #4400 or you wait and I'll make a sprite pack. I was planning on doing that anyway so yeah check back later today

**Comment by LordBaaa** [comment]
[Pink_Shirt_Spritepack.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3383576/Pink_Shirt_Spritepack.zip)

**Comment by Jancio2137** [comment]
Can i ask you a question are you gonna making spritepack for that neclacke
and bracelets? I would really appreciate it because i think it looks really
good.
I know you said you made a guide but i really don't know what im doing.
So can you think about that?
https://github.com/Monika-After-Story/MonikaModDev/issues/4352

czw., 11 lip 2019, 21:25 użytkownik LordBaaa <notifications@github.com>
napisał:

**Comment by Jancio2137** [comment]
Also really thanks for spritepack for that shirt

czw., 11 lip 2019, 22:23 użytkownik Jancio Games <janciogames@gmail.com>
napisał:

**Comment by multimokia** [comment]
Going to take more than a spritepack.i suggest leaving it for official since we need to add a selector and such fit for it to even be usable. Plus programming points etc

**Comment by Jancio2137** [comment]
Okay i really appreciate that spritepack for shirt

czw., 11 lip 2019, 22:25 użytkownik multimokia <notifications@github.com>
napisał:

**Comment by LordBaaa** [comment]
Yeah np. Also I mean I could probably make you something temporarily to add it. Or I could make you another outfit with with her wearing that stuff

**Comment by LordBaaa** [comment]
Also @Jancio2137 yeah I plan to make more sprite packs of community assets so just wait and it will come.

**Comment by Jancio2137** [comment]
Can't wait

pt., 12 lip 2019, 00:38 użytkownik LordBaaa <notifications@github.com>
napisał:

**Comment by Jancio2137** [comment]
So if i understeand correctly you gonna make more spritepacks to easy add
to MAS for pepole who don't know how to add things (like me).


pt., 12 lip 2019, 16:33 użytkownik Jancio Games <janciogames@gmail.com>
napisał:

**Comment by multimokia** [comment]
I'd probably hold off on public stuff because we release them officially as spritepacks, with reactions too. For your own purposes it's fine but public I'd probably wait.

**Comment by Jancio2137** [comment]
Like this hairclips?

pt., 12 lip 2019, 17:20 użytkownik multimokia <notifications@github.com>
napisał:

**Comment by multimokia** [comment]
Yeah, but for other things too.

**Comment by LordBaaa** [comment]
@multimokia Okay if they aren't in the next update then I'd release what I have. Also all my sprite pack have reactions. Or maybe you could make a section for user sprite packs like the submod section.

**Comment by lunulae** [comment]
@LordBaaa 
The pink shirt spritepack works fantastic! I noticed a small typo in the reaction text though, I figured I should tell you in case you wanted to patch it up.
There's an unnecessary comma in the sentence "I've always wanted more casual clothes."

:D Thank you again for your fantastic work!

**Comment by LordBaaa** [comment]
@lunulae Thanks I'm glad you like it! Actually that comma was on purpose. I was trying to indicate a pause of her saying like I have always wanted some more... casual clothes. Just to emphasize casual clothes more compared to like the dress I posted here #4427 (Shameless plug btw) or the new Miku Miku outfit. I am not sure if I to keep that or remove it but thanks for letting me know.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]

**Comment by QuaraPlayz** [comment]
This is great! I need to add this but idk how in steam...

**Comment by Velius94** [comment]
Steam is not supported.
Also this is included in the latest spritepack, check the official site.
