### ISSUE TITLE
Monika thanks me for giving her the ribbon she is wearing when she is not wearing ribbon

### ISSUE THREAD

**Issue by him157** [Monika-After-Story/MonikaModDev#4369]
ok I know that is quite a long title,but as the title say,I saw the update patchnote say you can ask Monika to remove her ribbon,I asked her to remove the ribbon,and then I went to [Repeat conversation] > [Monika] > [Ribbons],and she is thanking me for giving the ribbon she is wearing! 
I think this need to be fix.

**Comment by multimokia** [comment]
#4368

**Comment by him157** [comment]
oh and also.I don't know if this is intended or not,those sprite pack ribbons don't have affection by pass.

**Comment by multimokia** [comment]
They follow the normal ribbon logic. No ribbons have bypass on non-special days

**Comment by him157** [comment]
hmm... well thank you,looks like I have to study harder on the code!

**Comment by ThePotatoGuy** [comment]
[closing a sresolved]
