### ISSUE TITLE
Notifications don't work 

### ISSUE THREAD

**Issue by Artorias22171** [Monika-After-Story/MonikaModDev#4371]
So apparently, the first you install the 0.9.5 update, Monika present the new notification system and ask for a try. I answered yes and at this moment a notification was supposed to appear but nothing for my case. After that, I enabled the both "Window reacts", "Use Notifications" and "Sounds" in "Alerts". I spent like 2 hours on the internet and no notification until now.

Someone could help me, please ?
I'm on windows 10.

**Comment by Anonymioo** [comment]
Did you tried to watch some videos in Youtube notification should appear. Same with Github (This page,)

**Comment by Artorias22171** [comment]
Well yes, nothing new appear on my screen.

**Comment by Anonymioo** [comment]
> Well yes, nothing new appear on my screen.

There problem in settings of your Windows maybe?

**Comment by Artorias22171** [comment]
> > Well yes, nothing new appear on my screen.
> 
> There problem in settings of your Windows maybe?

Um... no, nothing's wrong here. No particular problems.

**Comment by Anonymioo** [comment]
> Um... no, nothing's wrong here. No particular problems.

I mean can you check notification settings in Windows. 
There checkbox "Receiving notifications from apps..."

**Comment by Artorias22171** [comment]
> > Um... no, nothing's wrong here. No particular problems.
> 
> I mean can you check notification settings in Windows.
> There checkbox "Receiving notifications from apps..."

It's already done since a long time.

**Comment by Anonymioo** [comment]
Other popups working?

**Comment by Artorias22171** [comment]
Yeah

**Comment by Anonymioo** [comment]
Check this: Confidentiality -> Background apps. Is there checkbox is on?

**Comment by Artorias22171** [comment]
It's on.

**Comment by Anonymioo** [comment]
Alright. Type cmd and launch it with admin rights. Then type sfc /scannow to check windows.

**Comment by Anonymioo** [comment]
Another variant is reseting action center.

**Comment by Anonymioo** [comment]
And last can you check in MAS in Alerts "Use Notifications" is it on?

**Comment by Artorias22171** [comment]
Ok, so the scan finished, it found some corrupted files, fixed them but it didn't solved the problem. I won't reset the action center, it's a long mess to do and I don't think this is the problem. And I just check that "Use Notifications" is on.

**Comment by Anonymioo** [comment]
Action center can be reset with reg file easily it require only reboot. But alright. 
Then we need to wait for devs.

**Comment by Artorias22171** [comment]
Yeah, I better wait. It's their mod after all.

**Comment by multimokia** [comment]
Send a screenshot of your alerts settings please

**Comment by multimokia** [comment]
Also, we've had cases where they start working after a restart

**Comment by Artorias22171** [comment]
![Base Profile Screenshot 2019 07 02 - 00 23 25 60](https://user-images.githubusercontent.com/42290174/60505605-c2784980-9c5f-11e9-8b99-208a3536acb0.png)

Here.

**Comment by multimokia** [comment]
Hmm okay, so you'll only get windowreacts. And you said the intro one didn't work for you. Maybe give your PC a restart, one person who had the same issue had their notifications work after a restart. No idea why.

**Comment by Artorias22171** [comment]
restart ? you mean reboot ?

**Comment by multimokia** [comment]
Yeah

**Comment by Artorias22171** [comment]
ok let's try this.

**Comment by Artorias22171** [comment]
no, nothing's change.

**Comment by Artorias22171** [comment]
just a question : it's supposed to work if i say goodbye, if i quit the game, right ?

**Comment by multimokia** [comment]
I meant saying goodbye and restarting your computer, as that had worked for another user. Thought it would work for you too

**Comment by Artorias22171** [comment]
Then I don't understand...

**Comment by Artorias22171** [comment]
Ok, I tried it on an other pc and it didn't work either. That's really weird.

**Comment by him157** [comment]
huh... I was _kinda_ like like earlier,just sound and only the DDLC  icon pops on at taskbar in notification,and after some notification setting it worked for me,but it is not the case for you... strange...
oh and seeing how hard you work on it you must like your Monika a lot just trying to get this to work.

**Comment by multimokia** [comment]
From another user in MASC who got it working:
> If you have problem in win 10 with notifications:  Go to "Windows Settings" menu, then "Notifications & actions", switch "Get notifications from apps and other senders". As soon as you get a new notification from Monika, windows will show DDLC.exe in list below that switch. Now turn everything on for DDLC.exe. Done!

**Comment by Artorias22171** [comment]
> From another user in MASC who got it working:
> 
> > If you have problem in win 10 with notifications:  Go to "Windows Settings" menu, then "Notifications & actions", switch "Get notifications from apps and other senders". As soon as you get a new notification from Monika, windows will show DDLC.exe in list below that switch. Now turn everything on for DDLC.exe. Done!

Sorry for the wait. So I have to switch on "Get notifications..." ? It was already done by default. Btw DDLC.exe isn't in the app list for notifications.

**Comment by Artorias22171** [comment]
hum...an other question, is this ok if DDLC is under steam ?

**Comment by ThePotatoGuy** [comment]
better to use non-steam ddlc. update intros are one-time only.

[closing as resolved][
