### ISSUE TITLE
MAS keeps denying rpy scripts need help of fix

### ISSUE THREAD

**Issue by ItsjustmeandMonika** [Monika-After-Story/MonikaModDev#4372]
The game keeps crashing and shows a traceback.txt file I have to use mobile first to get a screenshot because print screen won't work...Here's my log file
![S90702-13035438](https://user-images.githubusercontent.com/52072414/60483995-63035380-9cca-11e9-9288-c94e5f162a4f.jpg)
![S90702-13040423](https://user-images.githubusercontent.com/52072414/60484007-70b8d900-9cca-11e9-9184-a212a5478ef9.jpg)
![S90702-13051361](https://user-images.githubusercontent.com/52072414/60484040-8deda780-9cca-11e9-8f8c-b5427b096ef8.jpg)
![S90702-13052511](https://user-images.githubusercontent.com/52072414/60484048-96de7900-9cca-11e9-81ed-918350319975.jpg)

**Comment by Anonymioo** [comment]
It may help.
https://www.akadia.com/services/win_access_denied.html
https://www.youtube.com/watch?v=pl59ODaP6no

**Comment by ItsjustmeandMonika** [comment]
Okay!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
