### ISSUE TITLE
[Suggestion] - Adding new answer to Hemisphere question

### ISSUE THREAD

**Issue by Roxis88** [Monika-After-Story/MonikaModDev#4373]
Well, until just now, I only seen two options when she asked about the place of hemisphere, the northern and southern.
I live at the Equator, and so, I just kinda choose which one that closer to mine, which is southern hemisphere.
But I hope that some day, a new option to answer "At the Equator" or such will be available, and having follow-up discussion about that.

Thank you, and stay healthy!

**Comment by ItsjustmeandMonika** [comment]
Yep!I live in the equator too,she rhinks it's night time but it's daylight in my area lol

**Comment by skyloom** [comment]
Oh this is similar to my issue! #3233

So far, devs implemented a topic where Monika asked whether snow fell in player's place. I think it's kind of verifying that?

**Comment by ItsjustmeandMonika** [comment]
Yep I read yours and I do think that as well..Maybe we could get a response now?

**Comment by Anonymioo** [comment]
> Yep I read yours and I do think that as well..Maybe we could get a response now?

This suggestion have low priority. It will be added after high priorities and important things.

**Comment by ItsjustmeandMonika** [comment]
It's alright though.I'm okay with it.

**Comment by jmwall24** [comment]
@ItsjustmeandMonika where you live has nothing to do with if she thinks it's day or night. On the `settings` page you can change the sunrise and sunset times to whatever you want.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
