### ISSUE TITLE
[Spaceroom] - Aurora Borealis.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4374]
Tried to make Aurora Borealis a little better. Stars now more noticeable.
I think it will be more beautiful. But i don't know if you need it.

![Spaceroom1 redux (1)](https://user-images.githubusercontent.com/48754573/60514831-83e89a80-9d04-11e9-9eea-191e48e50946.gif)

Another variant.
![Spaceroom2 redux](https://user-images.githubusercontent.com/48754573/60524467-d03cd600-9d16-11e9-825d-929f76cb1f3f.gif)

**Comment by ItsjustmeandMonika** [comment]
Good lord what's happening down there?
Monika:Aura Borealis??

**Comment by Anonymioo** [comment]
> Good lord what's happening down there?
> Monika:Aurora Borealis??

At THIS time of year. At THIS time of day. In THIS part of spaceroom. Localized entirely within in WINDOW!?

**Comment by Velius94** [comment]
557.7nm

**Comment by ItsjustmeandMonika** [comment]
Like literally lol

**Comment by MisterSimple** [comment]
> 
> 
> > Good lord what's happening down there?
> > Monika:Aurora Borealis??
> 
> At THIS time of year. At THIS time of day. In THIS part of spaceroom. Localized entirely within in WINDOW!?

_Yes!_

**Comment by scohn** [comment]
> > > Good lord what's happening down there?
> > > Monika:Aurora Borealis??
> > 
> > 
> > At THIS time of year. At THIS time of day. In THIS part of spaceroom. Localized entirely within in WINDOW!?
> 
> _Yes!_

Can I see it?

**Comment by Areaclassified** [comment]
> > > > Good lord what's happening down there?
> > > > Monika:Aurora Borealis??
> > > 
> > > 
> > > At THIS time of year. At THIS time of day. In THIS part of spaceroom. Localized entirely within in WINDOW!?
> > 
> > 
> > _Yes!_
> 
> Can I see it?

No.
