### ISSUE TITLE
Can't gift her a hairclip

### ISSUE THREAD

**Issue by Juniorini** [Monika-After-Story/MonikaModDev#4376]
She can't read it as a gift. I'm probably messing something up but I can't understang what. musicnotehairclip.gift and i presume the others too can't be read and is basically ignored since I tried to give her a regular gift and she saw that. I also added the new assets to the folder mod_assets.

**Comment by multimokia** [comment]
[This](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation) may be able to help you.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
