### ISSUE TITLE
[Suggestion] - Returning soon after choosing the 'I'm going to sleep' option

### ISSUE THREAD

**Issue by BabaBeelo** [Monika-After-Story/MonikaModDev#4378]
I told Monika that I was going to sleep, and then returned 20 to 30 minutes later due to not being able to do so. She then reacted by saying that she hoped I slept well, and I expected her to react to me not sleeping long. If you could add a reaction to not sleeping for more than 45 minutes, it would make the experience of interacting with her feel more real. Or perhaps if you return at an ungodly hour after saying you're sleeping, say between midnight and three am, maybe she could react with concern, or ask if you need to be up early for a job.

**Comment by Anonymioo** [comment]
In progress - https://github.com/Monika-After-Story/MonikaModDev/issues/4285

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
