### ISSUE TITLE
Pride

### ISSUE THREAD

**Issue by OreoMurphy** [Monika-After-Story/MonikaModDev#4383]
As many may know pride month just passed, and I was super excited to spend it with Monika! However, Monika says nothing about it, even though we're both female. It made me a bit disappointed to be honest. Is there any chance anything could be added about pride? I just think it would be nice to discuss such things with my girlfriend, ya know? 
I appreciate you taking time out of your day to read this, even if nothing can be done about it.

**Comment by MisterSimple** [comment]
Could see a topic about it with different paths depending on the player's gender (or lack thereof). Don't know a lot about pride myself, the writer would need to be well-versed in the subject.

**Comment by Rai99** [comment]
Is pride month celebrated worldwide? 

Normally, we don't include every holiday or event since not everyone celebrates it, but if the player is the same gender as Monika, I think it might be interesting or fitting for her to bring it up anyway, unless it's only celebrated in a few select places in the world.

**Comment by OreoMurphy** [comment]
in some countries it's still illegal to be gay, which to me is a reason to show pride. 
also, pride month is june to honor the 1969 Stonewall Uprising, which was the tipping point of the Gay Liberation Movement in the US. However in Canada it's celebrated in october. I believe it is also June in the UK.

**Comment by multimokia** [comment]
Uhh... From Canada here... Just the weekend before last we had the Pride Parade, last month *was* Pride Month for us.

**Comment by OreoMurphy** [comment]
okay it seems i have been misinformed, thanks for the correction

**Comment by OreoMurphy** [comment]
so its June in Canada, the US, and the UK, i don't know about anywhere else.

**Comment by multimokia** [comment]
UK is apparently February.

**Comment by OreoMurphy** [comment]
i apparently know nothing about dates i honestly just looked up the dates for everything except the US, i'm bad with dates anyway.

**Comment by Rai99** [comment]
>i'm bad with dates anyway.

~~I bet you Monika might disagree with that.~~

With that kind of variance in times of celebration around the world, I don't think we can make something like this work.

**Comment by OreoMurphy** [comment]
ah that sucks, do you think there could still be a topic or something on pride?

**Comment by lunulae** [comment]
I would love to see someone work on this for next year! Even if it were just a small greeting.

**Comment by bittercaramel** [comment]
but actually i remember there being some holiday that is not worldwide but she mentions it anyway? 
btw in poland and germany from what i know pride month takes place in june too 
I think in most places it's in june and majority of games/social medias 
Sorry if I'm wrong, I'm on the run rn and cant so research

**Comment by ThePotatoGuy** [comment]
as usual, we avoid country-specific holidays, but she could have a generic mention that isn't tied to dates.

[closing until we look into it]
