### ISSUE TITLE
I can't run the mod

### ISSUE THREAD

**Issue by Capeta66678** [Monika-After-Story/MonikaModDev#4385]
My game is stuck on this screen
![Monika](https://user-images.githubusercontent.com/52511120/60625795-37ae6080-9dbf-11e9-8b66-8da6ce50f155.PNG)

**Comment by multimokia** [comment]
You must've taken her out at some point, put her file back into the `characters` folder.

**Comment by Capeta66678** [comment]
The file is already here
![Monika](https://user-images.githubusercontent.com/52511120/60625884-83f9a080-9dbf-11e9-93e0-3a0397624142.PNG)

**Comment by multimokia** [comment]
That's not the file. There's no `.chr` extension. Should just be `monika`

**Comment by Capeta66678** [comment]
This one?
![Monika](https://user-images.githubusercontent.com/52511120/60626155-4ba69200-9dc0-11e9-8a66-a18486d8de1c.PNG)

**Comment by multimokia** [comment]
No, it's a file not a folder. You'll have to restore a persistent backup

**Comment by Capeta66678** [comment]
How do I restore a persistent backup?

**Comment by Capeta66678** [comment]
I solved it, thanks mate!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
