### ISSUE TITLE
[Suggestion] - More sleep options 

### ISSUE THREAD

**Issue by BabaBeelo** [Monika-After-Story/MonikaModDev#4386]
This is a follow up to a previous suggestion I made about Monika reacting to you returning only minutes after you told her that you were going to sleep. ( https://github.com/Monika-After-Story/MonikaModDev/issues/4378 ) Maybe you could add a 'I'm going to nap' option as well, so when you return she asks you how your nap was, if you feel well rested, etc. ( And if you think it would be a good addition, maybe if you tell her you're going to take a nap and then return 6+ hours later, perhaps she could react with concern and ask if you are getting enough sleep at night, or if you're sick. )

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
