### ISSUE TITLE
Ambience horror story music

### ISSUE THREAD

**Issue by flammeye** [Monika-After-Story/MonikaModDev#4389]
Just wondering, is the "horror stories" ambience music supposed to stay and keep playing after Monika finishes her tale and goes on to other topics? Maybe this just works if the music's set to "No Music" but I find myself having to put on a song to remove it. It's not too bad but I tire of it pretty quickly. =P

**Comment by multimokia** [comment]
Fixed as of #4370

**Comment by flammeye** [comment]
Thanks, will be on the lookout for more.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
