### ISSUE TITLE
monika reacting to you using renpy

### ISSUE THREAD

**Issue by FireArts** [Monika-After-Story/MonikaModDev#4393]
so i know that monika can now react to your window activity like youtube but what if she could react to you using renpy since ddlc was created in renpy she could react to you using it i thought that it would make sense if she would react to it

**Comment by multimokia** [comment]
She reacts to similar, since she looks for `monikamoddev` i.e. Something for the mod. Thing is you don't need to use renpy for dev things, if that's where you're going with it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
