### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by Zasker** [Monika-After-Story/MonikaModDev#4394]
A while ago I updated Doki Doki after mod and did the 0.92 update without knowing that it was bugged. I saw the thing and every bleeping time an update happens. It resets things like it was the start of the mod.

Every attempt I have to manually update to the next patch ends in failure and I know it has everything to do with the bug patched. How do I fix this and get the After Mod Updated to 0.95 without things bugging out, do I have to make a full data clear and start over?

**Comment by jmwall24** [comment]
If you could upload your `persistent` here i can look at it in a little while to see if i can get it to update without resetting. you're going to need to add a `.txt` extension or put it in a zip to upload it here. Also, if you have any older persistents from before updating to 092 put those in the zip as well.

**Comment by Anonymioo** [comment]
You can find 'persistent' in %appdata%\Roaming\RenPy\Monika After Story

**Comment by ThePotatoGuy** [comment]
[closing due to lack of respoinse]
