### ISSUE TITLE
About the floating islands...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#4396]
The messed up square underneath the Cherry Blossom tree, definitely looks like a small "Yoda type" house. Is there a way to really "clean it up" that messy code or it will unveil in a future update where  she will finally be good at it like she mentioned?

**Comment by lunulae** [comment]
I'm curious about this as well. I don't believe there's anything currently in the game files(?) for it, but perhaps it's going to be a surprise for later.

**Comment by bittercaramel** [comment]
honestly im pretty sure there is nothing in this place 
no messy code or anything, it's just a picture that looks like it's glitched and there is no way to access anything else in this place unless you make something yourself

**Comment by Akh0r** [comment]
Hey, how can we see those isles at all? I've seen it only once and I don't remember how was that thing brought up...

**Comment by multimokia** [comment]
`Hey Monika...>Monika>Can you show me the floating islands?`

Make sure weather is clear.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
