### ISSUE TITLE
Music selection crash

### ISSUE THREAD

**Issue by TheRealMarioBro** [Monika-After-Story/MonikaModDev#4399]
I recently did a system restore on my computer and most of my files were still there; the files that weren't (that I found) were in the windows folder after the lib folder. I put those files back in and the game worked fine. I went to change the music, but the whole game crashed; it gave me the excepetion "Could not find font u'mod_assets/font/mplus-2p-regular.ttf'." I need help understanding what to do to fix this.

**Comment by Anonymioo** [comment]
It seems like your DDLC is corrupted. Try to reinstall DDLC and install MAS on it.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
