### ISSUE TITLE
I cannot open the mod anymore

### ISSUE THREAD

**Issue by MarcySun** [Monika-After-Story/MonikaModDev#4401]
I have already tried re-downloading the game and going to a previous persistent, but I still cannot open the game. 
It happened after I updated to 0.9.5 through the game not manually, and monika was talking about the new features, and just when she was supposed to show that she can now send notifications, the game crashed. I had already deleted the main files when reinstalling everything so I couldnt find the traceback file, but I did get this one when trying to open the game with nothing happening.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3361151/traceback.txt)

However, one thing that does happen is that the app pops up in the task bar like so:
![its just there](https://user-images.githubusercontent.com/52557087/60698575-3f4c3300-9ead-11e9-8c36-3c472ee97fff.PNG)
Thank you for your time.

**Comment by Anonymioo** [comment]
Alright. 
1. You re-downloaded only MAS? 
2. Did you tried to run DDLC.exe as Administrator? What about 'Compability Mode'?
3. Maybe it help? - https://steamcommunity.com/app/698780/discussions/0/1488866813771554172/
4. Traceback says something about python2.7/traceback.py in lib. Do you have Python?
5. Or maybe there something with lib folder so renpy can't launch DDLC.
6. And where your MAS placed?

**Comment by multimokia** [comment]
Screenshot of your `game/` folder, please? This is by no means a normal traceback.

**Comment by MarcySun** [comment]
Not just MAS, I downloaded ddlc from the official page and downloaded the new update
I did try to run it as administrator
Apparently I do have Python, but I havent actually used it
Its placed as it was before, I had been using it for a month so Im sure it isnt placed incorrectly _probably_
Im gonna try doing what it says there on the steam post soon, thanks!
![gamesfolder](https://user-images.githubusercontent.com/52557087/60745894-90a20400-9f39-11e9-8968-cf047a367f10.PNG)
(also that was the only traceback file I found when I tried searching for it, so it might now be the regular traceback file)

**Comment by MarcySun** [comment]
Even after trying out those 2 ways to fix it from the steam link, it still does not work

**Comment by multimokia** [comment]
What's with those `.txt` files? Are you running a translation, or a submod?

**Comment by MarcySun** [comment]
I havent added any translation or submods, not sure what those are

**Comment by multimokia** [comment]
Have you ever installed another mod into this copy of ddlc before MAS?

**Comment by Anonymioo** [comment]
Can you try to install DDLC in another folder, and install MAS on it? 
Just to make sure if your folder don't conflicting with something.

**Comment by MarcySun** [comment]
Nope, that copy is brand new
Ill give it a try

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
