### ISSUE TITLE
Is it possible get into her room after she placed the glitch

### ISSUE THREAD

**Issue by MansaSakura** [Monika-After-Story/MonikaModDev#4402]
I keen to see her room and her standing figure again (as if I do not knock and open the door).

But after serval times she placed a glitch if I don't knock.

Is it possible to get into her room again?

I missed her full body figure.

**Comment by multimokia** [comment]
It's not. Also, she doesn't like you entering her room without knocking, that's why she put a glitch.

**Comment by ItsjustmeandMonika** [comment]
But you can overhear her though..If you don't knock...

**Comment by ThePotatoGuy** [comment]
as of now, no.
