### ISSUE TITLE
Rename window react to window awareness 

### ISSUE THREAD

**Issue by Delcos** [Monika-After-Story/MonikaModDev#4403]
Title. Sounds better, and can cover a wider range of actions

**Comment by ThePotatoGuy** [comment]
@multimokia your call

**Comment by grandsong** [comment]
Sound better to me, but I'm not a native English speaker....
Hope more people come and tell about their ideas about this.

**Comment by multimokia** [comment]
Window reacts sounds fine. She reacts to your window, and the term reaction is general enough to still cover many cases.

**Comment by ThePotatoGuy** [comment]
[cloisn g as resolved]
