### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4410]
Found in PSD file (Leaning). There something with layers.
![image](https://user-images.githubusercontent.com/48754573/60753451-a75d5f00-9ffc-11e9-8aa9-a307f76ccd3a.png)
And when i'm hiding 'leaning base' layer. It's becoming normal.
![image](https://user-images.githubusercontent.com/48754573/60753459-bc39f280-9ffc-11e9-99e9-d51fa1961db1.png)

**Comment by ThePotatoGuy** [comment]
the transparency line? seems small enough to where it isnt an issue

**Comment by Anonymioo** [comment]
Got it.
