### ISSUE TITLE
I need some help please! about a gift

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#4413]
Whats the gift name about the hair clip and bracelet or the necklace?

**Comment by multimokia** [comment]
Gift names are in the txt file provided in the sprite packs

**Comment by multimokia** [comment]
Bracelet and necklace are not implemented yet. Sure you can make a json and gift it but there's no selector for them

**Comment by Axone00** [comment]
Aw.... 
Thank you! for the respond and info
