### ISSUE TITLE
[Suggestion] New Outfit For The Summer

### ISSUE THREAD

**Issue by AhmedElmemy** [Monika-After-Story/MonikaModDev#4414]
Well I wanted to see Monika wearing some new outfit for the summer because the schools change the school uniform in the summer and its weird to see her wear that uniform in the summer I saw many people making artwork for Monika wearing summer outfit like that 
(https://user-images.githubusercontent.com/52626211/60768486-cb847300-a0c4-11e9-81ae-976ddb38ea0a.jpg)

**Comment by Chrissenpai** [comment]
Now that´s quality content, might make a similar one if that summer outfit can´t be used

**Comment by kkrosie123** [comment]
Holy cow! That's adorable! I would love to see that outfit added to the game uwu

**Comment by bittercaramel** [comment]
yea adorbs clothing but her eyes and smile are scaring me... is she going to eat my soul?

**Comment by AsuraShun** [comment]
That's cute af

**Comment by ThePotatoGuy** [comment]
Due to sprite system overhaul 2.0, many outfits will not make it until august. should be better prepared for next summer though,
