### ISSUE TITLE
Cannot Open the game

### ISSUE THREAD

**Issue by Ukage** [Monika-After-Story/MonikaModDev#4415]
When I tried to open the mod (Fresh install)
Windows say " The program can't start because SDL2.dll is missing. "
If I take the SDL2 in /lib folder
Windows say " The program can't start because python27.dll is missing."
When I run the .exe in /lib
Nothing
When I copy SDL2.dll and python27.dll only,error 0xc00007b
When I copy all the /lib folder in /ddlc but don't replace the .exe,Nothing

I've Redownload (I was in 0.9.4,I've Updated in 0.9.5 same problem)
I've reinstall
Delete Everything and re copy
Nothing work

Please Help me,i've tried everything

**Comment by multimokia** [comment]
Fresh install of the mod, or DDLC entirely?

**Comment by Ukage** [comment]
DDLC entirely

**Comment by Ukage** [comment]
I can run The mod through Renpy

**Comment by Anonymioo** [comment]
Do you have updated DirectX, .NET, VC Redist?
### 0xc00007b this error appearing because of this.

Source - https://forums.tomshardware.com/faq/0xc00007b-error-fix.1612086/

**Comment by Ukage** [comment]
So,it’s good 
It work again 
When renpy started to crash
I don’t understand my computer 
But everything it working again

**Comment by Ukage** [comment]
So,it’s good 
It work again 
When renpy started to crash
I don’t understand my computer 
But everything it working again
