### ISSUE TITLE
Cannot give Monika lanvellime gifts

### ISSUE THREAD

**Issue by FugusFalafel** [Monika-After-Story/MonikaModDev#4416]
The most recent update comes with a seperate file allowing us to give Monika new gifts that comes with new ribbon colors as well as hairclips. I've put all the .png and .json files into the a folder under the monika folder which is found under mod_assets. I even put the ribbon and hairclip gifts as .gift but she still can't read them. Have I done something wrong? I've been doing this for two days and I still keep getting the same result.

**Comment by multimokia** [comment]
Json files don't go in the `a` folder. They go in the `j` folder. The thumbs go in the `thumbs` folder in `mod_assets`. You just needed to merge the two `mod_assets` folders together. That would have put everything in the right place.

Once you fixed the paths, you'll be able to gift them tomorrow.

**Comment by FugusFalafel** [comment]
Okay I've put them all into their respective folders. I'll try again tomorrow and see it if works. Thanks a bunch!

**Comment by FugusFalafel** [comment]
I figured it out and now I'm able to give her the new gifts! Thanks for your help!
