### ISSUE TITLE
got a gray screen but had a different error

### ISSUE THREAD

**Issue by UWUOWOXD** [Monika-After-Story/MonikaModDev#4418]
so i tried to put the mod into ddlc got a gray screen but it says that there is no module named eliza, what does this mean?

**Comment by Anonymioo** [comment]
Did you installed MAS correctly?

**Comment by multimokia** [comment]
You're missing something from python packages. Try reinstalling MAS

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
