### ISSUE TITLE
[Suggestion] Random Encounters Entertainment Just Monika label:suggestion 

### ISSUE THREAD

**Issue by pauljb336** [Monika-After-Story/MonikaModDev#4419]
A question to ask Monika. What does she think of the video made by Random Encounters Entertainment and of Or3o's performance as her? Also, add their "Just Monika" song to Music.

**Comment by Anonymioo** [comment]
> Also, add their "Just Monika" song to Music.

There Copyright for this Music :(
Hope this will be added sometime too https://www.youtube.com/watch?v=E9A7G9rENyc.

**Comment by multimokia** [comment]
Custom music can already be added. There's pretty much no reason to add these officially.

**Comment by ThePotatoGuy** [comment]
closing until we look into it[
