### ISSUE TITLE
Custom notification sounds?

### ISSUE THREAD

**Issue by niicore** [Monika-After-Story/MonikaModDev#4420]
something minor but would be nice if there was a feature to be able to change notification sounds

**Comment by multimokia** [comment]
Just change the `notif.wav` file with something else.

**Comment by niicore** [comment]
any other way so that instead of having to rename and replace we can have a sort of list or something? like a combobox?

**Comment by multimokia** [comment]
Probably too minor of a thing to really warrant it imo.

**Comment by niicore** [comment]
okay thanks for fast response though ❤

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
