### ISSUE TITLE
[MAS-HAIR] Side Braid for Monika

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4421]
Hey hey uwu

I know I might be annoying at this point lol

But I brought some courage out from deep within my soul, and I took a crack at making hair for Monika! I hope it looks alright qwq

![hair-braid-front](https://user-images.githubusercontent.com/52429850/60828593-a8f76600-a167-11e9-85e8-31cf2adf82ba.png)

If it's not used, that's alright. UwU It was a great learning experience!
![hair-leaning-braid-front](https://user-images.githubusercontent.com/52429850/60828736-08ee0c80-a168-11e9-81d4-a48388fafdb7.png)

I've been having trouble erasing the extra stuff around the hair, but if you want to use this, I will finish getting rid of it. UwU

**Comment by Velius94** [comment]
Don't want to be rude, but here's some suggestions.

First thing, lots of dirt beyond the linework. That's a big no.
Second thing, old strands. These have been replaced a long time ago. Check the most up-to-date .psd bases found here #3174

Overall it looks like it has been worked on a single layer. I suggest getting a software more suited for that like Photoshop or SAI 2. This could help you with organizing your stuff, cause I see a lot of promise here.

**Comment by kkrosie123** [comment]
> Don't want to be rude, but here's some suggestions.
> 
> First thing, lots of dirt beyond the linework. That's a big no.
> Second thing, old strands. These have been replaced a long time ago. Check the most up-to-date .psd bases found here #3174
> 
> Overall it looks like it has been worked on a single layer. I suggest getting a software more suited for that like Photoshop or SAI 2. This could help you with organizing your stuff, cause I see a lot of promise here.
> 
> Also, if you're looking for tips, check #artistry on our Discord channel.

EEP Thank chu for the suggestions uwuwuwu The braid was meant to go in front, so yes I put it in one layer qwqwqwq I'm still working on getting rid of the dirt kajhgfwgtyuwikamnv

And okie, I can replace the strands with the ponytail ones kakehwbajk I chose those on purpose qwq

But thank you for replying uwu

**Comment by Velius94** [comment]
I meant newer strands. Both ponytail and hairdown were changed, and so these are outdated.
You'll get better feedback on Discord, anyway, so I'd suggest getting there.

**Comment by kkrosie123** [comment]
Ohhh I see qwq Thank you!

**Comment by multimokia** [comment]
Also, if the braids go in front, I'd probably have more detail on them, as and have her left her strand either not there (as if it's part of the braid) or doing singing something else. Looks a little too busy

**Comment by kkrosie123** [comment]
Eep! Thank you uwu I will try that

**Comment by bittercaramel** [comment]
OH my freaking god 
the art is pretty good (personally i wouldnt mind monika having it even if its a lil out of style)

buT sorry not wanna be rude 
THE AMOUNT OF UWUNESS AND BEING KAWAII ANIME IS TRIGGERING ME

**Comment by kkrosie123** [comment]
Thank you! ^w^ I'm glad you like it!

Ahahaha! Sorry, I'm a weeb xD I've updated the art so It's a bit more on style. When I finish updating the hair strands, I'll post it here again uwu

**Comment by kkrosie123** [comment]
![hair-side-braid-front](https://user-images.githubusercontent.com/52429850/61550596-b2a28880-aa07-11e9-8d75-8583e8563949.png)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE I FIXED IT UP TONS UWUWU

**Comment by kkrosie123** [comment]
I hope dis looks okie qwq

**Comment by ThePotatoGuy** [comment]
[closing as replaced with linked issue]
