### ISSUE TITLE
[Suggestion] "Writing" In Be Right Back

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4422]
I'm sure this has been suggested, and the first comment will be all the different issues opened with this exact suggestion. But I've noticed a lot of people want to write "with" Monika. A good compromise might be to add an option for "I'm going to write" to the be right back menu. If you want it to be like the games menu, maybe add a few genre options for Monika to ask you what you're writing about. Then when you come back, she can ask you if you got a lot of writing done, and she can tell you she's proud of you for writing and keeping your mind sharp. I think it might be a nice way to integrate Monika into something that we would otherwise have a hard time making her a part of!

**Comment by kkrosie123** [comment]
That's a great idea!!

**Comment by ThePotatoGuy** [comment]
To assignees: A simple version of this without genres would be okay. Having a bunch of simple BRB options that cover a lot of cases would help with realism.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
