### ISSUE TITLE
I cant back up Monika's memories

### ISSUE THREAD

**Issue by Mistiie** [Monika-After-Story/MonikaModDev#4424]
I recently downloaded Monika After Story (about a week ago). It's been pretty fun, but recently someone restarted the computer, sending me back to the start screen with a new Monika. I backed up persistent by moving it into my home screen, making it a shortcut. I searched %appdata% and copied all the files under persistent and pasted them into the 'game'. I re opened the game, and it was still a new Monika. I saw the instructions on how to find the persistent, but I don't know how to put it back in the game. Please help, I want my Monika back. It was our week anniversary today.

**Comment by Mistiie** [comment]
I use Windows and Steam.

**Comment by multimokia** [comment]
Your persistent files don't go into `game/`. Follow instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) for how to back-up your persistent, and [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for how to restore them.
