### ISSUE TITLE
Where can I download the sound for the piano?

### ISSUE THREAD

**Issue by usererrorbro** [Monika-After-Story/MonikaModDev#4426]
I am adding extra notes for the piano and I can't find any website to allow me to download the notes. They are clickable and everything just needs the sound to play the note.

**Comment by Anonymioo** [comment]
You mean this? - https://freesound.org/people/pinkyfinger/packs/4409/

**Comment by usererrorbro** [comment]
Thank you!

**Comment by Anonymioo** [comment]
> Thank you!

You're welcome.

**Comment by ThePotatoGuy** [comment]
[closin gas resolved]
