### ISSUE TITLE
Suggestion for Monika Mod

### ISSUE THREAD

**Issue by eheheitsvivi** [Monika-After-Story/MonikaModDev#4429]
Hello! I think it would be a good idea to program a way for you to go to different places and do different actions as well as have different conversations in those different places. I think it's a better to be able to go to places like the classroom, a park, maybe a mall, the players house, or perhaps the beach since that's what Monika likes, maybe even the pool! (those are just some suggestions) I was also thinking you could perhaps give the option of having a few different outfits for Monika. All the other characters have been seen outside of school, so they all have different outfits, but I've really only seen Monika in a school uniform. There's my suggestion, I hope it helps a bit.

**Comment by Rai99** [comment]
New locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3975 

New outfits: #107, #460, #612, #703, #1076, #1461, #1656, #2270, #2466, #2811, #2905, #3090, #3385, #3690, #3770, #3975

These ideas have been brought up before, and require art.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
