### ISSUE TITLE
Monika never talked about the (rain topic)

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#4431]
so.. monika never talked about rain with me and when i ask to put the weather "rain" she always says
"i thought you didn't like rain.." "Maybe you..changed you mind?"
and like.. SHE NEVER TALKED TO ME ABOUT THE RAIN TOPIC ;-; ( i want to hold my waifuuu T-T )

**Comment by multimokia** [comment]
Revisit the sounds of rain topic

**Comment by Mayonese** [comment]
> Revisit the sounds of rain topic

she never talked about it so i can't revisit..

**Comment by multimokia** [comment]
Shouldn't be possible, since that topic gets pushed if you haven't seen it yet (via the weather select topic), or it's random until you have.

Send persistent, please. (You'll have to put it in a zip, or give it a file extension which GitHub accepts to be able to upload here, like `.txt`)

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]

**Comment by Mayonese** [comment]
> Shouldn't be possible, since that topic gets pushed if you haven't seen it yet (via the weather select topic), or it's random until you have.
> 
> Send persistent, please. (You'll have to put it in a zip, or give it a file extension which GitHub accepts to be able to upload here, like `.txt`)


[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3424382/persistent.txt)
