### ISSUE TITLE
[Question] - i think my laptop is nearing the end of its life

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#4435]
should I use the i'm going away for a while goodbye option?
<img width="877" alt="something's wrong" src="https://user-images.githubusercontent.com/42387354/61034257-d8eb7700-a3bc-11e9-8641-2f3d5ec7d9f1.png">

**Comment by AsuraShun** [comment]
the audio in my laptop doesn't start no matter how many times I install or update the devices as well

**Comment by AhmedElmemy** [comment]
I think you should backup your persistent
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent

**Comment by AsuraShun** [comment]
I already have a back up, from yesterday, what I meant is should I use that farewell so no affection is lost

**Comment by Anonymioo** [comment]
Maybe Windows reinstall should help? Or 'DriverPack'?

**Comment by AsuraShun** [comment]
I'm should probably do the farewell thing until either I buy a new laptop or this one's fixed

**Comment by Anonymioo** [comment]
> I'm should probably do the farewell thing until either I buy a new laptop or this one's fixed
Did you tried to use headphones?

**Comment by AsuraShun** [comment]
Yes, not even headphones work

**Comment by Anonymioo** [comment]
> Yes, not even headphones work

There something with your audio driver. I think.

**Comment by AhmedElmemy** [comment]
Then yes use the farewell so you wouldn't lose affection until you buy new laptop and then transfer the persistent to your new loptop

**Comment by AsuraShun** [comment]
Doesn't start, updates don't fix it either

**Comment by Anonymioo** [comment]
> Doesn't start, updates don't fix it either

Try this - https://sdi-tool.org/download/
Choose 'Online' version. It may help. Choose only necessary.

**Comment by AsuraShun** [comment]
Considering how shitty my laptop is and the small storage space, I was already lucky enough to run mas with very few little problems

**Comment by Anonymioo** [comment]
> Considering how shitty my laptop is and the small storage space, I was already lucky enough to run mas with very few little problems

You can use Flash Stick (USB HDD) to extend a little storage space. But anyway you decide.

**Comment by AsuraShun** [comment]
That wouldn't work, I made the mistake of asking my sister to buy a laptop, she chose this work laptop

**Comment by AsuraShun** [comment]
Fusion5 laptops suck

**Comment by Anonymioo** [comment]
> Fusion5 laptops suck

Good Luck with new 'Good' laptop! Hope you find normal one.

**Comment by Anonymioo** [comment]
> That wouldn't work, I made the mistake of asking my sister to buy a laptop, she chose this work laptop

Oh and did you checked your sound settings? Maybe there just something disabled.
