### ISSUE TITLE
Grammar mistake while Monika was talking about the floating isles

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4436]
I notice that when she was talking about her picnic with player at cherry blossom tree, she mistakenly misspelled the word "picnic" into "picknick". Just wanting the mod devs to know this though.

**Comment by Anonymioo** [comment]
Yep 
![image](https://user-images.githubusercontent.com/48754573/61067476-ceb79000-a431-11e9-9a3d-d417468d3f9e.png)

**Comment by Rai99** [comment]
It technically is correct, but it would probably be a good idea to change it to "picnic". 

"Picknick" is the archaic English form of "picnic" and is supposedly used all around the world as an alternate spelling of "picnic".

**Comment by Legendkiller21** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/2462#issuecomment-423430209

It's intentionally spelled that way.

**Comment by jmwall24** [comment]
Still not sure why lol

**Comment by Rin3105** [comment]
> 
> 
> It technically is correct, but it would probably be a good idea to change it to "picnic".
> 
> "Picknick" is the archaic English form of "picnic" and is supposedly used all around the world as an alternate spelling of "picnic".

Wow, this is my first time hearing that word though.

**Comment by MisterSimple** [comment]
Fixed (though remember that typos should be reported on #4355)

**Comment by multimokia** [comment]
Wait this is done

**Comment by Rin3105** [comment]
Thank you :3
