### ISSUE TITLE
[Suggestion] Say today on the calender

### ISSUE THREAD

**Issue by LordBaaa** [Monika-After-Story/MonikaModDev#4439]
I have been meaning to say this for a while but forgot about it. When I look at the MAS Calendar sometimes I feel lost cause it doesn't say what today is. Sure I can just look down at my computer clock but I think it would be more immersive if in game you could see the day. Or like you know how some ppl cross out the days on a calendar to tell where they are. Not necessarily that but just some kind of mark or text.

**Comment by Rai99** [comment]
#3002 

The idea of showing the current date on the calendar has been brought up some time ago, and is on the list of calendar improvements for the future at low priority.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
