### ISSUE TITLE
Clothes- MIKU MIKU NI SHITE AGERU

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#4440]
#3174
it is I, and today i bring you h̶a̶t̶s̶u̶n̶e̶ ̶m̶i̶k̶u̶ , ahem i mean misterious and totally not famous vocaloid outfit!!!
![uprightbase twintails](https://user-images.githubusercontent.com/47725743/61096262-46cf8700-a42d-11e9-9e96-259997226b5d.png)
![leaningbase twintails](https://user-images.githubusercontent.com/47725743/61096269-4b943b00-a42d-11e9-9fa4-3d01dea83ab4.png)

the clothes actually extend waay past the table and i'm still sour about the fact you wont be able to see most of it,,,
![miku sketcho](https://user-images.githubusercontent.com/47725743/61096321-7bdbd980-a42d-11e9-9270-7347662b7428.png)

I'm not yet sure if I'll have the energy to make her sleeves, but maybe sme day i will. Tho her hair acs and mic are surely on the way!!!
Please lemme know if i have anything to fix.

**Comment by LordBaaa** [comment]
Looks good! Can’t wait to see it finished

**Comment by Jparnaud** [comment]
I am approving this outfit, I give you my energy to finish your work ;)

**Comment by Orcaramelo** [comment]
> I am approving this outfit, I give you my energy to finish your work ;)

Thank you! i should probably resume work on the hair loops

**Comment by kkrosie123** [comment]
Yes 👏 Yes 👏 Yes 👏 Yes👏 Yes

**Comment by Jparnaud** [comment]
I really can't wait to see the final result ... 
I would have ask for Megurine Luka's outfit after but I have no idea if you would be up for it X)
But anyway, I'll wait for this one first in any case, can't wait :D

**Comment by PollenTheCat** [comment]
> I really can't wait to see the final result ...
> I would have ask for Megurine Luka's outfit after but I have no idea if you would be up for it X)
> But anyway, I'll wait for this one first in any case, can't wait :D

Well then we'll need Gumi! (And Rin, Meiko, etc) XD

**Comment by Orcaramelo** [comment]
after decades, here is her headset! will work on leaning now!! sleeves to come soon too
![image](https://user-images.githubusercontent.com/47725743/63135812-9dd4f880-bfa5-11e9-851e-6ae60e092ea2.png)

**Comment by Jparnaud** [comment]
Man this just gets better and better ! Can't wait for this to come into the mod :D 
I can tell you that your efforts will not be wasted ;)

**Comment by Orcaramelo** [comment]
> Man this just gets better and better ! Can't wait for this to come into the mod :D
> I can tell you that your efforts will not be wasted ;)

thank you! I'll be working hard to make this set look good!

**Comment by Orcaramelo** [comment]
am currently working on sleeves! got 2/8 arms done yeeeehaw
this might take a lil bit but i sure will do my best!

**Comment by Orcaramelo** [comment]
ive done it yall
![image](https://user-images.githubusercontent.com/47725743/63226864-317d1380-c1b6-11e9-9108-803797c0e1a8.png)
all arms done and headset for leaning is done too
miku is ready to po pi po

**Comment by Jparnaud** [comment]
Hey congratz ! It. Looks. Amazing. Really can't wait to have Monika wear this ! :D 
Hopefully this could also make my friend play this since he's a fan of Miku X)
(Now to find someone who would do Luka)
But really, good job, I couldn't see a better result ;)

**Comment by Orcaramelo** [comment]
> Hey congratz ! It. Looks. Amazing. Really can't wait to have Monika wear this ! :D
> Hopefully this could also make my friend play this since he's a fan of Miku X)
> (Now to find someone who would do Luka)
> But really, good job, I couldn't see a better result ;)

Thank you so much, this took quite a long time and i would never have finished if not for everyone's incentives!! It sure would be nice to have Luka, maybe even Rin since i love her bow thingy, and yos **_bring your friend into our cult_**

**Comment by Rai99** [comment]
![S5CuN](https://user-images.githubusercontent.com/38822045/63229109-b83beb80-c1ca-11e9-954f-0407eaa2aa42.png)
Now all we need is for somebody to make a leek food item and then she'll be the same as this image. 

The "01" on her upper arm is missing, but I guess that's not really part of the "outfit".

**Comment by Orcaramelo** [comment]
> ![S5CuN](https://user-images.githubusercontent.com/38822045/63229109-b83beb80-c1ca-11e9-954f-0407eaa2aa42.png)
> Now all we need is for somebody to make a leek food item and then she'll be the same as this image.
> 
> The "01" on her upper arm is missing, but I guess that's not really part of the "outfit".

I did think abt adding the 01 but moni wpuld have to paint it by hand since its not something you just put on, so iended up deciding agains it
Tho maybe instead of a single leek, a little plant vase with leeks planted on it? That would be cute!

**Comment by Rai99** [comment]
I guess you could call the 01 a temporary tattoo, but I agree it's a little extra.

**Comment by LordBaaa** [comment]
Firstly great job! I am excited to add it to my MAS. Secondly I am a little lost on the whole leek thing. I mean if you were to draw it I could easily make it an ACS to be worn like in in the point right down arms pose. Could make it so it is worn when she puts on the outfit or as an optional thing.

**Comment by Orcaramelo** [comment]
> Firstly great job! I am excited to add it to my MAS. Secondly I am a little lost on the whole leek thing. I mean if you were to draw it I could easily make it an ACS to be worn like in in the point right down arms pose. Could make it so it is worn when she puts on the outfit or as an optional thing. P.S I have been keeping an eye on this project and I am happy for you that it is finally done.

having her hold the leek miht be a bit weird, and i had a little plant pot in my mind for a while, im discussing the possibilities of it with multi! if she held a leek, i'd have to make it so each pose the hand that holds it shows, the leek shows too, and that would look a bit awkward imo esp when in some arm poses the leek would simply vanish (down, steepling, crossed)
unless it was a consumable, but besides miku, **_who eats pure raw leeks?_**

**Comment by LordBaaa** [comment]
Well you could write some special dialogue where she pulls it out. You could equip and dequip it for a MIKU scene. Maybe for the gift section. Just a thought though the case sound sounds cool to. Also the 01 could be a temporary tatoo instead of hand piant.

**Comment by its-ken** [comment]
adorable! i want this in my game !

**Comment by Orcaramelo** [comment]
> adorable! i want this in my game !

Thank you!! And same tbh, we need some quality cosplay around these parts

**Comment by FrikiHD** [comment]
This looks frikin awesome!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
