### ISSUE TITLE
[suggestion] sing for monika

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4445]
I wanted to sing something to monika just like i can play the piano for her 
nothing special just option "im gonna sing you something" or something and then clicking when you are done 
i have no idea if it was already suggested and sorry for being too lazy to research 
thx for readin

**Comment by Andrenika** [comment]
It would be a good idea

**Comment by kkrosie123** [comment]
Here's an addition to the suggestion.

Talk -> Hey, Monika... -> You... -> Can I sing for you?

"Sure, [player]!" 
"I would love to hear you sing."
"I don't want to interrupt you, so let me know when you're finished, okay?"

[Player Options]
_I'm done._

"..."
"Wow, [player!] That was really good!"
"I really enjoyed that."
"If you ever want to sing to me again, just ask, okay?"

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
