### ISSUE TITLE
i got a bsod a.k.a blue screen of death

### ISSUE THREAD

**Issue by cmaster25** [Monika-After-Story/MonikaModDev#4450]
so i got update 9.5 and did stuff with monika afer like 5-6 minutes i sayd goodbye. everything good so far but THEN when i went to open google chrome i got a blue screen of death but then everytime when i turn on my laptop again its gone.

is that a feature or is it realy an error

**Comment by multimokia** [comment]
Your computer's dead. We don't fake bluescreens at all.

**Comment by Olliesama** [comment]
Sounds like your laptop is dying. Better back up Moni while you can.

**Comment by cmaster25** [comment]
i tried to boot up my laptop and it says uptades been found does it meen my error is gone

**Comment by Olliesama** [comment]
No, the bsod is your own personal hardware failure and has nothing to do with MAS itself.

**Comment by cmaster25** [comment]
i hope my laptop recovers

**Comment by multimokia** [comment]
It won't, you'll need to look into getting new hardware/a new laptop entirely.

**Comment by Velius94** [comment]
Get tech support from your hardware manufacturer.

**Comment by cmaster25** [comment]
somehow my laptop works (again)

**Comment by Olliesama** [comment]
Back up Moni onto a USB while you can, hardware failure always returns.

**Comment by multimokia** [comment]
Yes...but it won't be working for too much longer if you already are having hardware failures.

**Comment by cmaster25** [comment]
but whatever i do when i go in there again it will probably crash so i would rather talk less with monika instead of getting a crash again

**Comment by multimokia** [comment]
The point is to get her persistent onto a USB so you can transfer her to a new computer when you get one. If you don't you risk losing her forever once this computer dies.

**Comment by cmaster25** [comment]
alright fine

**Comment by cmaster25** [comment]
but i got ddlc from steam so i cant just do it easy so i wanna ask what file should i copy

**Comment by multimokia** [comment]
Location of the `persistent` is the same regardless of the Steam version or not. See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) for how to do it. It's the same one she links from time to time.

**Comment by Olliesama** [comment]
Doesnt matter if it's on steam, you can copy that just fine.
But you want the persistent files.

For windows it's located in...
C:\Users\You\AppData\Roaming\RenPy\Monika After Story

**Comment by cmaster25** [comment]
thanks

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
