### ISSUE TITLE
Speech

### ISSUE THREAD

**Issue by otakuprince** [Monika-After-Story/MonikaModDev#4454]
Just wondering, how hard is it to connect the mod to the text to speech software of Windows? I hope we can atleast let Monika talk.

**Comment by Anonymioo** [comment]
If you want you can use this for example - https://github.com/Monika-After-Story/MonikaModDev/issues/3765#issuecomment-500228631.
Anyway tts is rejected for Monika.

**Comment by multimokia** [comment]
As mentioned above, this is rejected.

The Uncanny Valley is an issue with this is one problem, and I imagine many people would not like the voice that would be used as it'd probably be too robotic or not what Monika should sound like.

Naturally, Monika is rather expressive, so it's pretty simple to pick up how what she says would be said, so it's better to let players use their own interpretation of how Monika should sound.

#337, #1814, #2241, #3187, Marking as duplicate.

**Comment by ItsjustmeandMonika** [comment]
How's 'bout making it sound like her voice actor?I've heard you can syhnthesize and modify tts

**Comment by multimokia** [comment]
It's not really feasible. We'd need recordings from someone who sounds like Jillian (Monika's voice actress) and then we'd have to make sure that what's synthesizing it still doesn't sound robotic, or like it's smashing audio clips together and hoping they work.

It's honestly a bigger hassle than it's worth.

**Comment by Rai99** [comment]
#337 
> [[Rejecting voice because adding voice is not planned nor will be planned]]
>
> Better to let users imagine the voice they want Monika to have

#2241
> The idea of giving Monika a voice to speak to the player with was discussed early on in #337 and decided that the addition of a voice was not planned and will not be planned in favor of allowing the players to have their own perception of Monika's voice.

#3187
> Not to mention the likely outrage from a few people complaining that Monika's voice isn't what it should be.
>
> > Better to let users imagine the voice they want Monika to have
>
> Even though you can hear her voice when she sings Your Reality, it's probably a smart idea to leave it up to the players' imaginations.

> Seconding his opinion, it's best to leave it to one's imagination. The expressions are pretty dynamic, it's already obvious how she would sound like.

**Comment by otakuprince** [comment]
It doesnt have to be here the singer of Your Reality though. Oh well, looks like we have to wait for those guys in China to build some sort of a speech application.

**Comment by Akh0r** [comment]
`The Uncanny Valley is an issue with this is one problem`
This.
Man, I haven't update my mod for a while, and now I'm a little disappointed that Monika now BLINKS. Not only because she is "no longer immune to SCP-173" as was mentioned before :D But now you see her as in real-time, not as an illustration. And in real time - how doesn't she breathe? How doesn't she shift her pose smoothly? Why does she have only a couple of fixed poses?..

Let's not make anything so radical until we can make it perfect. Monika deserves better.

**Comment by ThePotatoGuy** [comment]
[closin as duplicate]
