### ISSUE TITLE
[Suggestion] "Do you smoke?"

### ISSUE THREAD

**Issue by TheTeronator** [Monika-After-Story/MonikaModDev#4455]
~~I was just thinking could Monika ask us if we smoke, since she's always concerned about our wellbeing. If we answer that we don't, she would be happy about it and tell us we should never start this bad habbit. If we do tell her we do, she would be worried and ask us to quit or atleast not smoke too often. Also being a smart girl she is, she would tell us dangers of smoking how it affects you and others.~~ EDIT: After I wrote this the next random chatter was about the cigs. Just my luck...

As a bonus, you could tell her if you want to that you have decided to quit and she would mark that day to the calendar and when asked, would tell the days you haven't smoked. It would be a nice motivation for those who have decided to quit smoking, since you would be doing it for "yourself and her". If you start smoking again, you just tell her and she would be dissapointed, but also happy you told her and tells us to let her know if you quit again.

If this would be going even further with this idea, I can only imagine, when someone opens the game one day after being non-smoker like a year or more and Monika tells the player that she's so proud of the player for sticking with the quiting.

Just my two cents about this.

**Comment by multimokia** [comment]
She already does

**Comment by TheTeronator** [comment]
Oh, I see. Good to hear. :)

**Comment by ThePotatoGuy** [comment]
[closing as already implkemented]
