### ISSUE TITLE
option to stay with monika when sick

### ISSUE THREAD

**Issue by ThatMonkeyBiz** [Monika-After-Story/MonikaModDev#4456]
I'm currently down with a case of Strep Throat. I decided to go to Monika, maybe for a little comfort, I'm not sure, but it brought up the idea, what if when you insisted to stay with Monika when you were sick, the dialogue would change a bit? I don't know if this is something that has been suggested already, but it would be very nice if Monika might be caring towards the sick.

**Comment by lunulae** [comment]
I could see a few things that could be done with this. Maybe if you've told her you're feeling sick in a particular session, she'd have a different response for things like "I'm going to go to sleep." I'd maybe add a little teasing dialogue if you ask for a kiss while sick too. 

I'm not really sure how to do conditional dialogue but I am considering trying to give this a go :D

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
