### ISSUE TITLE
'Auto Hair Change'

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4457]
![image](https://user-images.githubusercontent.com/48754573/61430176-4fefb500-a953-11e9-88e2-5e015672ae08.png)
When Moni changing her hair. Why she saying this? She do it by herself. I don't asked to change.
_And thanks for this submod._

**Comment by multimokia** [comment]
One thing since this is a submod it should probably go on the issues page on my repo, but anyway, you can still ask her to change her hair, so you're not locked out of control.

**Comment by Anonymioo** [comment]
> One thing since this is a submod it should probably go on the issues page on my repo, but anyway, you can still ask her to change her hair, so you're not locked out of control.

Oh. Alright.
