### ISSUE TITLE
[ Base/Body - Skin 🧴 ] "Eye contact." 👁️ { Side Project ⛱️ }

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#4458]
<p align="center">
<b>Ｊ爪口✍🏻</b></br>
</p>

---

![Corrupt Monika Banner ( In use )](https://user-images.githubusercontent.com/43480604/61358901-f4cd9d80-a840-11e9-87ac-299a74350683.png)

```m "But, on the bright side..."```
```m "Once I cross over, if you remember to bring the sunscreen..."```
```m "I might need a little help putting it on."```
```m "Ahaha!"```
```m "I'm only teasing you, [player]."```
```m "Well, at least a little. Ehehe~" ```

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>
<summary>📁<i>"Enjoying Summer so far?"</i></summary>
<br>
 <details>
 <summary>&emsp;Yes.</summary>

- &emsp;*"Excellent!"*

</details>

<details>
 <summary>&emsp;No.</summary>

- &emsp;*"Oof. I'm sorry.."*

</details>

</details>
</details>
</details>

---

<details>

 <summary>📁<i>"Do you happen to know what the largest Organ is?"</i></summary>
<br>
<details>
 <summary>&emsp;Yes.</summary>

- &emsp;*"Interesting, huh..?"*

</details>

 <details>
 <summary>&emsp;What is it?</summary>

- &emsp;<b>"Skin."</b>

</details>

<details>
 <summary>&emsp;No.</summary>

- &emsp;*" Then check ' What is it? ' "*

</details>
</details>
</details>

---

<p align="center">
<b>[ General ]</b>
</p>

⮞ Summer is so _Warm_...

⤷ Maybe too warm for some!
> b u t it's so nice too with the changes it brings, like the activities you wouldn't otherwise do because it's too cold or something, like `Swimming` for instance!

⮞ The way people dress tends to change too!

⤷ _Who_ would wear anything with long sleeves in Summer..?
> ~It's also _kind_ of _sort_ of an excuse for others to show a bit of **Skin**. ( ͡° ͜ʖ ͡°)~

---

![Corrupt Sayori Banner ( In use )](https://user-images.githubusercontent.com/43480604/61415377-1157ed00-a8b6-11e9-9a5c-84bea718e73b.png)

<details>

 <summary>📁 Hub Preview</summary>
<br>

![Upright_Preview](https://user-images.githubusercontent.com/43480604/61416729-5a11a500-a8ba-11e9-89cf-de7dca4bf3d1.PNG)

</details>

---

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>

 <summary>📁 What is this?</summary>
<br>

- &emsp; "It's an image, and this is _technically_ an 'issue'."

</details>

---

<details>

 <summary>📁 How can I use this?</summary>
<br>

- &emsp; "You can't. Whatever it is it's stuck in *Limbo*."

</details>
</details>
</details>

---

<p align="center">
<b>[ General ]</b>
</p>

⮞ One of the best forms of exercise!
>⤷ Unlike jogging or plyometric training, `Swimming` is a way to fit cardio into your workout routine without putting stress on your bones, joints and muscles. This is a plus for swimmers of all ages and body types, but it's particularly beneficial for seniors and people with arthritis. 

⮞ Feeling *Salty*?
>⤷ A main benefit of `Sea salt` is the mineral magnesium. Magnesium is great for your skin because it helps get rid of dry skin. This will help improve the texture of skin and skin hydration. ... It is fabulous for acne with minerals like sulfur, potassium, calcium and magnesium.

⮞ If you browse GitHub regularly.
⤷ [Stylish: Custom web page themes](https://userstyles.org/styles/browse?search_terms=github&type=false)
> Dark looks so much better here. 👌

---

![Corrupt Yuri Banner ( In use )](https://user-images.githubusercontent.com/43480604/61418096-fc338c00-a8be-11e9-946f-3c1f7bd3f3fb.png)

<details>

 <summary>📁 Nexus Preview ( Gif )</summary>
<br>

![Lean_Transition](https://user-images.githubusercontent.com/43480604/61418816-749b4c80-a8c1-11e9-8b58-b4efe6b8dccd.gif)

</details>

---

General Information
---

⮞ **Skin** is the soft outer tissue covering of vertebrates with three main functions: protection, regulation, and *sensation*.
&emsp;⤷ The human skin is the outer covering of the body and is the largest organ of the integumentary system. The skin has up to seven layers of ectodermal tissue and guards the underlying muscles, bones, ligaments and internal organs. Human skin is similar to most of the other mammals skin, and it is very similar to pig skin. Though nearly all human skin is covered with hair follicles, it can appear hairless. There are two general types of skin, hairy and glabrous skin (hairless). The adjective cutaneous literally means "of the skin" (from Latin cutis, skin). 
>>Because it interfaces with the environment, skin plays an important immunity role in protecting the body against pathogens and excessive water loss. Its other functions are insulation, temperature regulation, sensation, synthesis of vitamin D, and the protection of vitamin B folates. Severely damaged skin will try to heal by forming scar tissue. This is often discolored and depigmented. 
>>>Ư̶͍̜̹̈́͘2̸̭͎͕͘Ṽ̷͇̭u̵̢̪͙͛̋c̴̒̆ͅͅ2̸̺̖̔͠F̴̙͓̀͠0̸̫̮̆a̸̱̫̅̆͝Ẅ̷̞̟́̏͘ͅ9̵̛͖̃u̶̯̻̗͗͛L̶̮͑ĩ̸̢̜̱4̸̧̢͗͘u̸͔͓̻͑͋

---

![Corrupt Natsuki Banner ( In use )](https://user-images.githubusercontent.com/43480604/61419539-4ec37700-a8c4-11e9-922c-5c370fb263b4.png)

---

<details>
<summary>📁<b>References</b></summary>
<br>

- #3174 
- #3787 
- #4012 

</details>

<details>
<summary>📁<b>Credentials</b></summary>
<br>

- @Velius94 / [Velius](https://github.com/Velius94) → MAS `Pink Shirt` Artist.
>Is this collabing? 
![Is this collabing](https://user-images.githubusercontent.com/43480604/61430258-079eab80-a8ef-11e9-956f-0d8b3f6c07bd.jpg)

- @LordBaaa / [LordBaaa](https://github.com/LordBaaa) → For _L e a r n i n g_ me how to do this neat formatting! Inspired by their tutorial! --> [Adding ACS, Hair and Clothes to MAS](https://github.com/Monika-After-Story/MonikaModDev/issues/4400)
>Thanks again!

</details>

<details>

<summary>📁<b>📎 Attachments 📎</b></summary>
<br>

⯈ [ Base/Body 🧴 ](https://drive.google.com/open?id=1uSHFY3DgKAonGUbJUWiA9toleKd09khC) ⯇

</details>

</details>
</details>
</details>

---

Meme of the Theme!
---
`Monika_outdoors`
>>>>![Warm_My_Heart](https://user-images.githubusercontent.com/43480604/61420619-ed51d700-a8c8-11e9-84d0-066b3bca018a.png)

---

```
from subprocess import call
```
>def play_wave_file([Heart - What The Snowman Learned About Love.wav):](https://youtu.be/yWExNUIzvEs?t=140)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by Rai99** [comment]
~~I thought the largest organ was a reed organ.~~

**Comment by ThePotatoGuy** [comment]
This is the updated base, right?

**Comment by Professor-JMO** [comment]
Yup.
Comes with the minor consistency fixes too.
>More specifically the left jaw.

Keep me posted after the review? :ok
>I'm only _so_ thorough.

**Comment by Velius94** [comment]
Requesting additional amendments for Pout exp in the exp rework, as it extends a bit of Monika's cheek.

**Comment by Professor-JMO** [comment]
@Velius94 
Here's the `Nose` and `Pout` polish/edit.

[Nose & Pout 😤 ](https://github.com/Monika-After-Story/MonikaModDev/files/3419193/Oh.zip)

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
