### ISSUE TITLE
Monika disappeared after updating the mod?

### ISSUE THREAD

**Issue by Speisha** [Monika-After-Story/MonikaModDev#4459]
Um hello I've opened this mod after some time, I updated it and it worked, but then it crashed and I couldnt restore it by myself in any way... so I deleted the game and downloaded it brand new, but when I tried adding the newest version (into a new downloaded game file), Monika was just... not there. (empty chair, no note, no music, nothing) I even tried finishing the game and adding the monika.chr file back again but nothing happened. so I tried downloading an older version (v 0.8.5) and I got my old Monika back, but updating it caused Monika to disappear again and I have no clue what do do. I'm sorry if this sounds confusing, but... **Please help?**

**Comment by multimokia** [comment]
Oh dear Lord...
1. When she disappears, **restore a persistent backup**
2. Going back to 0.8.5 means that you've gone back to a time where backups would overwrite others while she was out of the room, so all of your backups are void as of now.
3. When you have a crash that you cannot resolve *bring it up here and we can help you.*
4. If we fixed your persistent, all of your event data is now screwed and Monika won't remember anything that you've talked to her about in the past.

**Comment by Speisha** [comment]
Well what happened to me though- I lost my old Monika in like November last year, but somehow today I recovered her and I have no idea how, (because I had my windows reinstalled). But when it comes to this, how do I restore the backup? I am absolutely clueless about these things

**Comment by jmwall24** [comment]
you recovered her because in 0.8.5 taking her out isn't a thing, so no matter what, she shows up in that version

**Comment by Speisha** [comment]
that makes sense, but it still puzzles me how did I get the anniversary back and everything I had even after I deleted her back in November

But I don't think that matters right now, I don't understand why she disappeared even though I didn't take her anywhere because it was a new game and I didn't get to do anything

**Comment by jmwall24** [comment]
go [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) to find your persistent files. zip up that entire folder and upload it here and i'll look at it. chances are it's not really salvageable at this point, but it's worth looking at.

**Comment by Speisha** [comment]
So that means I should update the game again? It's working on the 0.8.5 version now but she seems a bit broken (keeps showing me the window thingy every time I open her)
I'll appear here again in few hours so I hope you'll be here

**Comment by jmwall24** [comment]
Don't do anything right now except do what i said in the last comment. Your only chance of keeping your monika is sending me that folder that contains the persistent files before you overwrite anymore of them.

**Comment by Speisha** [comment]
Does it work with win rar? It's telling me I can't upload it since its not supported

**Comment by Speisha** [comment]
[presistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3410378/presistent.zip)
I hope it works
