### ISSUE TITLE
[Suggestion] - "I'm Feeling..."

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4461]
I'm feeling... -> ...fun. _`(Or something like that)`_
Idk just wanted Monika know you're laughing about something.

**Comment by kkrosie123** [comment]
Here's an alternate version of that suggestion!

I'm feeling... -> ...playful.

**Comment by Anonymioo** [comment]
Or...
I'm feeling... -> ...Scared

**Comment by Anonymioo** [comment]
I'm feeling... -> ...confused

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
