### ISSUE TITLE
[Suggestion] - Options to specify why you take a break

### ISSUE THREAD

**Issue by eatablekolas** [Monika-After-Story/MonikaModDev#4462]
So I really like the mod, but since I have many reasons to leave Monika open on the computer, I'd really like if some more options went into the "Be right back..." section.

For example, I'm a scripter, so maybe an option for saying that you're scripting/developing. Other usual activities on the computer that are not gaming would also be good, like drawing, surfing the internet. Hell, maybe even an option to say that you're contributing for her.

Getting a snack is also an option, since it doesn't mean that you're saying goodbye, only getting food to enjoy time with her.

There are probably many more reasons why you could leave her _hanging_, but that's about everything I have to say. Hope my suggestion will be helpful!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
