### ISSUE TITLE
[MAS HAIR] Side Braid for Monika - UPDATED VERSION

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4463]
Opjihuygtresdtfyguhjiokp I fixed it up a bit

![hair-side-braid-front](https://user-images.githubusercontent.com/52429850/61551972-77a25400-aa0b-11e9-8e2a-c1d39e4a58a3.png)

I hope it looks a bit more on style qwq If you ever plan to put this in-game, I can fix up the linework! ^w^
#3174

**Comment by ThePotatoGuy** [comment]
Keep revisions on the same issue next time. (#4421 )

**Comment by kkrosie123** [comment]
eep sorry qwq
But anywhoo, here is a wayyy better one!

![hair-braid-front](https://user-images.githubusercontent.com/52429850/61820420-c3893a80-ae09-11e9-8799-d80d698f27f4.png)

**Comment by kkrosie123** [comment]
Changes:
- Updated the colors so they fit more with the style of Monika's hair
- Added highlights to the hair
- Cleaned up some edges around the hair
- Smoothed out the transition between Monika's hair and the braid
- Added shading

![hair-braid-front](https://user-images.githubusercontent.com/52429850/61964146-0ec65900-af82-11e9-9f72-4ab4375ed9fe.png)

**Comment by kkrosie123** [comment]
**August 1st Update**
- added hair shadow
- restored missing linework
- erased dirt behind the linework
- erased random pixels scattered throughout the image

![hair-braid-front](https://user-images.githubusercontent.com/52429850/62303096-61938b00-b430-11e9-96c9-bd84fa7dca25.png)

**Comment by kkrosie123** [comment]
**August 1st Sprite Preview**
_Sorry that this looks a bit messy. I don't have access to my regular tools at the moment, and I did this with a mouse. I'm used to using my finger. Ahaha-_

![braid_hair_preview](https://user-images.githubusercontent.com/52429850/62340037-fe871000-b492-11e9-9f64-6f82deda8be1.png)

**Comment by kkrosie123** [comment]
**September 1st**
A proper preview :D (featuring my donut thing!!)
![6](https://user-images.githubusercontent.com/52429850/64084815-924b3680-ccf4-11e9-8ac9-9453cfc00cf6.PNG)

**Comment by ThePotatoGuy** [comment]
the braid seems too thick, but I guess I'm not really an expert on what braids should look like. Regardless, can you let me know when you're done making changes/have a final version.

**Comment by Rai99** [comment]
In my opinion, I'm not sure it fits the art style of the mod.

**Comment by kkrosie123** [comment]
Yess I tend to have really weird shading and honestly I agree with both of you. I did fix it up a bit, though!

**September 9th, 2019**
- It looks better : D
- It's not as thick
- Now it actually looks like it's coming from behind the head (huge thanks to multimokia for pointing this out)
![7](https://user-images.githubusercontent.com/52429850/64571864-d52b9080-d32a-11e9-87e6-110b315952d4.PNG)

**Comment by kkrosie123** [comment]
But yeah I still need to make the shading look more like the mod's, haha

**Comment by frostcattooo** [comment]
its looking super cute, good job! <3

**Comment by kkrosie123** [comment]
Thanks! <3

**Comment by kkrosie123** [comment]
**September 21st Update**
- Reshaped the hair
- Yes, I see that little patch of the braid that needs to be re-shaded. I'll get to that in no time
- Added some linear shading

![11](https://user-images.githubusercontent.com/52429850/65375563-99fb5c80-dc5c-11e9-9e35-ea21234ddfcd.PNG)

**Comment by kkrosie123** [comment]
**September 21st)
- Smoothed out the highlights to match the art style better (Even though my artist's brain was screaming at me to make it function like real hair lmao)
- Added a thin black outline to the hair to match the art style better

![12](https://user-images.githubusercontent.com/52429850/65379252-dfcf1980-dc8a-11e9-9dff-3020805231a6.PNG)

**Comment by kkrosie123** [comment]
**September 25, Update**
- Blended shading
- Color correcting
- Added small highlights

![13](https://user-images.githubusercontent.com/52429850/65643106-7b77c700-dfb6-11e9-9e3a-258b280e34b6.png)

**Comment by Velius94** [comment]
Alright, gonna leave some criticism for you, hopefully you don't take it the wrong way, but here's something you should work on improving:

One of my major gripes with it is the pixelated 'jagged edges' stuff that seems to have happened post-edit, it significantly affects the quality of the entire thing. It's a _big no-no_. Compare how the edges look in the unedited version and yours. 

Another thing is the braid's rendering style is far too inconsistent with the rest of her hair. Try analyzing how it's made in the unedited parts and attempt to replicate that type of rendering. 

Also what software are you using? Do you use layers or just slap everything on one canvas? All of these, while might seem unimportant at the first glance for inexperienced artists actually make a huge difference in your workflow and overall quality control.

Hope this helps.

**Comment by kkrosie123** [comment]
Of course I won't take it wrong! Thank you for taking the time to give me criticism!

  Ah, I see. Is the quality lowering every time I render it? I'll put it on a larger canvas and try to fix that.

  Yes, agreed! I'm still trying to figure out how to get the hair like that.

  I'm using Medibang (And I use my finger on my phone, so yeah, the quality might falter because of that, lol), and yes, I am using layers. I've been doing digital art for a few years and I'm just very used to shading in my own style, haha.

**Comment by Velius94** [comment]
What I mean is that the entire outlines get really dirty and jagged, but I'm unsure of the reason for that. Maybe it has something to do with using mobile software which hurts the image's optimization; it's just a guess though, can't really confirm that.

The recommended way to edit these is using PC tools (be it Medibang, SAI, Photoshop or Clip Studio Paint), since it's pretty much the way it was done originally and our bases are optimized for PC editing, which is also much easier to do.

**Comment by kkrosie123** [comment]
Maybe - Another reason might be that I'm adding soft shading and I'm leaving it to be erased later on.

_Man I wish I could draw with a mouse lol_

I'll try that once I'm able to get the shading correct.

**Comment by Velius94** [comment]
Hmm, if you're placing a shading layer, you can create a clipping mask for the base color layer. That way it won't leak out of it.

**Comment by kkrosie123** [comment]
_Holy crap why did I never think of that_

**Comment by kkrosie123** [comment]
Oops accidentally closed it lmao

**Comment by kkrosie123** [comment]
But thank you for the criticism. I'm a teeny 13-year-old who doesn't know what she's doing x"D

**Comment by Velius94** [comment]
You're welcome, you have plenty of time to learn and you're on a good path!

**Comment by kkrosie123** [comment]
Thank you! That means a lot!

**Comment by kkrosie123** [comment]
**September 25th Update**
- Blended shading even more
- Drew over the braid with colors from Monika's unedited hair
- Attempted to begin adding highlights to the hair
- Unfinished
- Thank you to Velius for the criticism!

![15](https://user-images.githubusercontent.com/52429850/65650189-622f4480-dfcf-11e9-9a47-38141fa0b78e.png)

**Comment by kkrosie123** [comment]
**September 25th Update**
- Corrected braid anatomy
- Added outlines
- Recolored some areas
- Added more highlights

![16](https://user-images.githubusercontent.com/52429850/65651674-d4565800-dfd4-11e9-9aba-b232b91c7e53.PNG)

**Comment by kkrosie123** [comment]
**September 26th, 2019 Update**
- Added shading
- I'd say I'm about 90% done but probably not lmao
![17](https://user-images.githubusercontent.com/52429850/65735226-1bf3e700-e09c-11e9-9012-2c05f06e3e0f.PNG)

**Comment by PollenTheCat** [comment]
There's a tiny little thing I noticed about it: The back of the hair looks a bit strange to me. (See picture) What I mean is that it gets a bit smaller there and it just looks a bit unnatural... Idk how to explain it, I hope you understand what I mean.
![Monika braid circle thing shrug](https://user-images.githubusercontent.com/53543937/65840395-2e5d6300-e2de-11e9-957d-de3a97e6a283.png)

**Comment by kkrosie123** [comment]
aa, ty vm!

**Comment by kkrosie123** [comment]
Closing as there is an updated version of this.
