### ISSUE TITLE
[MAS] New Topic Concept

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4464]
This would be found in Talk -> Repeat Conversation -> Winter. It could be called, "Building Snowmen."  This topic might occur during winter for the player.

"Hey, [player]?"
"I've been thinking a little bit about winter activities we could engage in, together."
"Have I talked to you about ice skating, yet?"
"Well, I was also thinking that maybe we could build a snowman together!"
"Ahaha, that sounds a bit silly saying that out loud."
"But I never really got the chance to build a true snowman during the wintertime."
"I would just make tiny piles of snow, eheh."
"Would you like to do that, [player]?"
"Of course, it would have to snow quite a lot where you are to build a large one."
"Does it snow often there?"

_[Player Options]
Yes, all year long._ 
 - "Oh! It must be freezing there." 
"I'm not a fan of cold weather myself, but if it meant I could be with you, I wouldn't mind at all!"

_No, never._
 - "Oh. That's alright. I just thought it would be fun, Eheh."
"Even so, I still can't wait to spend my winters with you! Eheheh! <3"

_Sometimes, during the winter._
- "That's great!"
"I can't wait to spend my winters with you, [player]. Ehehe!"

_Only during the winter._
- "That's great!"
"I prefer warm weather, but I still enjoy some winter activities!"
"I can't wait to enjoy those activities with you, [player.] Ehehe!"

Just a small concept. I hope you like my idea 😄

**Comment by Rai99** [comment]
There are already some winter only topics, so this would have to be mindful not to overlap any of them, but I think a topic specifically about building snowmen could work.

**Comment by kkrosie123** [comment]
Awesome! Thank you for considering uwu

**Comment by ThePotatoGuy** [comment]
[closnig until we look intoit]
