### ISSUE TITLE
being able to tell monika your last/full name

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#4465]
it's a simple idea i just had and a simple idea for how she would react that i had in mind is "monika *insert last name here*

**Comment by Rai99** [comment]
#1297, #1529

**Comment by kkrosie123** [comment]
Are you saying that Monika would talk about having the player's last name? I think that would be cute! I could imagine her saying something like the following:

"What a lovely last name!"
"It fits you so well!"
"[player] [player's last name]."
"Yeah, I love that!"
"Maybe even I could use it?"
"Monika [player's last name]."
"Eheheh!"

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
