### ISSUE TITLE
[Suggestion] - Poetry for Monika

### ISSUE THREAD

**Issue by Doodlet** [Monika-After-Story/MonikaModDev#4470]
So, poetry was a central theme to the game and something Monika especially loves. We can give her gifts already, so how about being able to write poetry for her? It wouldn't have to be a super detailed addition, but could eventually grow into something like that if enough interest in making it goes on.

If it goes complex, she could help critique it and give you ideas to improve (or if you're a monster and you wrote something specifically to hurt her, it would make her upset) and even reference the crap you wrote during your time as MC if you write something like that.

Or it could be something simple and she won't necessarily read the poem (or will recite it aloud if its not too long) and afterwards give you a poem of her own depending on her affection score, which could lead to the adorable scenario of the two of you constantly trading poems each day. (or more, but only the first one each day should count for affection score)

As for how it can be done? There are two ways I can think of. Either a new poem.gift file where you type the actual poem inside, or she will acknowledge any .gift file with a name not recognized as an actual gift to be a poem if it has actual text in it, and the file's name would be the poem's title.

Even better, she could hang your latest poem on the wall of the room so you can always go back and look at it, which quite honestly would be super adorable.

Personally, I think its an open-ended idea with promise to be either as simple or as detailed as it can be depending on how its done.

**Comment by Rai99** [comment]
#784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3941, #4088 

Long story short, the best we can do is recognize keywords, but that will still often lead to dead ends and falsely interpreted messages. 

Even just looking at the presence of a gifted poem, there isn't much we can do or react on appropriately.

**Comment by kkrosie123** [comment]
Monika would need some serious artificial intelligence for this feature!

**Comment by ThePotatoGuy** [comment]
[closin gas duplicate]
