### ISSUE TITLE
A funny thing I found with the sprites

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4472]
![Monika idfc](https://user-images.githubusercontent.com/52429850/61597335-12de2980-abc4-11e9-891e-1c7e403cb09e.PNG)

This angry expression of Monika just happens to spell out, "idfc" 🤣 

I thought this was funny, sorry x"DDD

You probably already knew that - it just made me laugh xD

**Comment by Rai99** [comment]
Github is meant for mod suggestions/bug reports/sometimes questions ~~or when I need to post a joke, but won't use the discord~~ and the occasional `heartwarming` thank you issue.

As such, please keep issues on the topic of suggestions, bug reports, or questions if necessary.

**Comment by kkrosie123** [comment]
Woops! My bad qwq I'll keep that in mind. Thank you uwu
