### ISSUE TITLE
[Art - EXP] Mouth Expressions Redux

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#4474]
A side project I've been working on in tandem with another outfit some of you may have already seen.

Given that the quality of the original default expression was degraded, I decided to rework it, but later extended this to the entire mouth expression set + added a long-requested Disgust exp.

![big](https://user-images.githubusercontent.com/1176163/61598127-439c7e00-ac19-11e9-96d0-ec8c41ad47c6.png)
![disgust](https://user-images.githubusercontent.com/1176163/61598128-439c7e00-ac19-11e9-9de7-ffe565adcaca.png)
![gasp](https://user-images.githubusercontent.com/1176163/61598129-439c7e00-ac19-11e9-8355-9e875c88635c.png)
![pout](https://user-images.githubusercontent.com/1176163/61598130-44351480-ac19-11e9-8aca-11634d780488.png)
![small](https://user-images.githubusercontent.com/1176163/61598131-44351480-ac19-11e9-80c2-8244652466f6.png)
![smile](https://user-images.githubusercontent.com/1176163/61598132-44351480-ac19-11e9-98ff-899b8aae7d79.png)
![smirk](https://user-images.githubusercontent.com/1176163/61598133-44cdab00-ac19-11e9-94bc-b5edce8f7b7b.png)
![smug](https://user-images.githubusercontent.com/1176163/61598134-44cdab00-ac19-11e9-8fe6-8a3eef04b302.png)
![wide](https://user-images.githubusercontent.com/1176163/61598135-44cdab00-ac19-11e9-8508-486b8f2349ad.png)
![angry](https://user-images.githubusercontent.com/1176163/61632022-1f2db980-ac8c-11e9-8646-d8bd24bb1629.png)

PSDs:
[LINK](https://drive.google.com/open?id=1i5ZpULWk614vrbJq8MzOSdl7qe8RXJ05)

**Comment by kkrosie123** [comment]
These are very nice. Great job!

**Comment by LordBaaa** [comment]
You link doesn't work it redirect to https://camo.githubusercontent.com/7d9896e51e4a16e876af51fb3a4006afab1de7e9/68747470733a2f2f64726976652e676f6f676c652e636f6d2f6f70656e3f69643d3169355a70554c576b3631347672624a71384d7a4f53646c3771653852584a3035

**Comment by Velius94** [comment]
Fixed link.

**Comment by Velius94** [comment]
Updated with amendments provided by @Professor-JMO

**Comment by TriniTDM** [comment]
The expressions look good, but mostly it seems like she's pissed off because you're staring at her naked torso.

**Comment by Rai99** [comment]
Well, nobody likes to feel disarmed.

**Comment by LordBaaa** [comment]
Seems she could really use a hand with this one.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
