### ISSUE TITLE
[Question] Accessing PSD Files 

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4475]
Hello! So, I don't have access to photoshop and I wanted to make some clothes for Monika. Is there any other way to use Monika's base?

**Comment by Orcaramelo** [comment]
You can open them on sai1 and sai2
Im sure drawing programs such as Krita should be able to support pds files as well

**Comment by kkrosie123** [comment]
Awesome, thank you so much!
