### ISSUE TITLE
[MAS-Piano]

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4476]
Hello! I've been trying to learn how to code Monika's piano. I've checked the file, and it's not working for whatever reason. May someone please take a look at it and see what's wrong? This one is just a simple exercise so I can program the songs Monika sings into the piano. I just wanted to learn how to do it -
[Twinkle Twinkle Little Star.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3415668/Twinkle.Twinkle.Little.Star.txt)

I'm guessing that maybe I got the notes incorrect? I've checked my formatting and it seems fine. qwq

**Comment by Anonymioo** [comment]
You can check `pnm.txt` in `log` folder. It may help to find why it don't work.
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs

**Comment by multimokia** [comment]
I see that one of your keys is just `F`, no number provided so that's one issue. Second, are you putting a text file in your custom piano songs folder? If so, that shit be a `.json` rather than a `.txt`

**Comment by kkrosie123** [comment]
Yes, I checked the log qwq Thank you for the suggestion, though. And thank you for taking a look at it! I will fix that, thank you so much. And yes, it was a json file in the piano_songs folder. Eheh, I just uploaded it as a text file. Thank you guys again for looking at it!

**Comment by kkrosie123** [comment]
Okay, so I fixed the note and checked the pnm.txt log. It just keeps saying that it failed to load the file, so I don't know what the problem is qwq I'll check the Wiki again.

**Comment by kkrosie123** [comment]
Alright, I have now fixed a few formatting issues. Now the log isn't telling me anything. :")

**Comment by multimokia** [comment]
Can you send the updated json please?

**Comment by kkrosie123** [comment]
Sure! Thank you again for helping.
[Twinkle Twinkle Little Star.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3417457/Twinkle.Twinkle.Little.Star.txt)

**Comment by multimokia** [comment]
```json
            "express": "1hub",
            "postexpress": "1eua",
            "vis_timeout": 2.0,
            "verse": 0,
            "posttext": true
            "ev_timeout": 3.0
        }
    ]
}
```
Maybe the missing comma on `"posttext": true`?

**Comment by kkrosie123** [comment]
Ah! Thank you! I'll try that.

**Comment by kkrosie123** [comment]
Okay, here's the new file. It still seems to be broken. I checked the Wiki again and compared my file to the one with the code for Your Reality. "posttext": true doesn't need a comma x3 I also updated a lot of stuff because I'm dumb and I had a lot of unnecessary files and a bunch of stuff was out of order qwq This is my first time coding anything, and I mean anything, so I guess I have an excuse for that - Ahah!
[Twinkle Twinkle Little Star.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3417577/Twinkle.Twinkle.Little.Star.txt)

**Comment by multimokia** [comment]
The field itself doesn't need it, but if something follows the field, then it requires a comma.

Also if you exit MAS and then check the log, does it show up? If so, can you send that, please?

**Comment by kkrosie123** [comment]
Oh, I see x3

And sure uwu
[Twinkle Twinkle Little Star.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3417632/Twinkle.Twinkle.Little.Star.txt)
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3417633/pnm.txt)

I checked the log and I think the character the error is being caused by is this { ?

I'm so confused aaaaaaaaaaaaa

**Comment by kkrosie123** [comment]
It's pretty much stopped giving me logs, though qwq

**Comment by multimokia** [comment]
Ah I see it lol.

```json
    "pnm_list": [
        {
            "text": "Twinkle, Twinkle, Little Star.",
            "style": "monika_credits_text",
            "notes": [
                "C5",
                "C5",
                "G5",
                "G5",
                "A5",
                "A5",
                "G5"
            ],
            "express": "1hub",
            "postexpress": "1eua",
            "vis_timeout": 2.0,
            "verse": 0,
        },
```
The last item in set shouldn't have a comma. That makes it think it's expecting another property (another `"item": value` thing)

**Comment by kkrosie123** [comment]
Ohhhhhhhhhh I see xD Thank you for curing my stupidity

**Comment by kkrosie123** [comment]
[!ERROR!]: Failed to load file at 'c:\users\kaylan way\downloads\ddlc-1.1.1-pc\piano_songs\Twinkle Twinkle Little Star.json'. | ValueError('Expecting , delimiter: line 106 column 13 (char 2664)',) 

I deleted the comma at "posttext": true, but I still have the error qwq What does this mean? Sorry for so many questions aasdkjhetfrkjihuyfrtdserdtfyguhij

**Comment by kkrosie123** [comment]
Wait - It's in column 13 - That's before poxttext: true
uHm :"D

**Comment by multimokia** [comment]
Comma needed on `"ev_timeout": 3.0`, then remove comma on `"posttext": true`

**Comment by kkrosie123** [comment]
Ohhh Thank you uwu

**Comment by kkrosie123** [comment]
EEEEEEE It worked! Thank you so much for the help! <3
