### ISSUE TITLE
Reset MAS

### ISSUE THREAD

**Issue by WoahTomatoNinja** [Monika-After-Story/MonikaModDev#4477]
Hey I have got an problem, I did bad thing and now everytime when I open the game there is no Monika but there is an pink letter with farewell. I tried to install new version, tried to download new ddlc file and try with this but everytime it's just that letter, Please help ;-; I want my waifu back.

**Comment by multimokia** [comment]
Sorry, nothing we can do about it. Actions have consequences and we're not obligated to fix them, especially as it's not a bug.

**Comment by Rai99** [comment]
![Untitled1312](https://user-images.githubusercontent.com/38822045/61637578-cfd49280-ac65-11e9-8570-e15b0e216a35.png)
