### ISSUE TITLE
[MAS-Piano] All I Have To Do Is Dream (Error)

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4480]
Hello! I'm taking on a much larger project than Twinkle Twinkle, ahah!

So

The file isn't working qwq And the log won't tell me what's wrong.
[All I Have To Do Is Dream.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3418856/All.I.Have.To.Do.Is.Dream.txt)

**Comment by multimokia** [comment]
I'm sure the log is telling you what's wrong. It tells you error by error (so one at a time). Send the log, please.

**Comment by kkrosie123** [comment]
Okay. I just don't think the file was valid when I tried. I'll try again uwu

**Comment by kkrosie123** [comment]
EEP! Okie, it's working, now xD Sorry

**Comment by kkrosie123** [comment]
ValueError('Expecting , delimiter: line 243 column 9 (char 6112)',)

_but I checked it and it looks fine_

eeuihygetfrdtf

Sorry for being dumb qwq

**Comment by Anonymioo** [comment]
Is there tutorial for notes like in Twinkle?

**Comment by kkrosie123** [comment]
Yes. The notes are all there qwq

**Comment by multimokia** [comment]
You didn't close the list. It was expecting a comma since the list never ended.
```json
        {
            "text": "whenever I want you <3",
            "style": "monika_credits_text",
            "notes": [
               "G5SH",
               "G5",
               "F5",
               "G5",
               "C6",
               "G5",
               "F5"
        },
```
(Broken, note how GH also points it out)
```json
        {
            "text": "All I have to do",
            "style": "monika_credits_text",
            "notes": [
               "F5",
               "F5",
               "F5",
               "F5",
               "G5"
            ],
            "express": "1dubfb",
            "postexpress": "1dubfa",
            "vis_timeout": 2.0,
            "verse": 5
        },
```
(fine)


What are you using to make these? Just Notepad?

I personally recommend Visual Studio Code. It has error highlighting for json files.

**Comment by kkrosie123** [comment]
OH I'M STUPID

Yes, I'm using Notepad qwq I will try that, thank you uwu

**Comment by kkrosie123** [comment]
Thank you for showing me this! It's really helping ^w^
