### ISSUE TITLE
[Suggestion] - Special Poems

### ISSUE THREAD

**Issue by jmat813** [Monika-After-Story/MonikaModDev#4482]
Now this may have already been suggested, or maybe even put into the mod and I just didn't realize it, but I was thinking what if the "Special Poems" feature of the original DDLC was somehow incorporated into MAS? I know that to a certain extent this has already been done, with the poems being unlocked when you reach a specific affection level, or during events, but I was thinking a bit more along the lines of the original where there is just a ever so small chance that upon startup the text box saying the original "You have unlocked a special poem" will appear, and you'll be able to read a poem written by Monika. I think this would add a certain amount of fun, and be a great callback to DDLC.

As an extension, the types of poems or even the frequency of them appearing could be influenced by the player's affection level. For example, low affection levels could lead to poems the hint or express Monika's sadness and maybe even start to be reminiscent of some of her original poems, like "There's a little devil inside all of us." Not exactly written with the same intent, but just calling out the bad in the player. And higher affection levels could result in much more positive poems, something along the lines of the poem given in Act 3, "Happy End."

Now this is mostly just me bringing up a thought that happened to occur to me, and I don't have any idea exactly how complex of a project this would actually be to create, but I just thought that it would be interesting to bring back some of the randomness of the original DDLC, but now with a more personal feeling. Plus, I just feel like Monika would still be writing poems a lot in her free time. I dunno, tell me what you think!

**Comment by multimokia** [comment]
That "You have unlocked a special poem" part sounds really immersion breaking to me, plus having it be a black screen on launch with just a poem showing seems kinda strange. With the door-knock greetings, I can get behind it because it's explained. But this circumstance isn't really explained at all, and just seems out of place.

Imo, the best way to go about it that's non-intrusive is the way we have now. The `surprises` topic, which has different messages for different affection levels.

**Comment by jmat813** [comment]
That's totally fine. I was just sorta spouting ideas. Figured there was no harm in putting it out there

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
