### ISSUE TITLE
Monika got the lyrics wrong

### ISSUE THREAD

**Issue by Mon-ikaSquid** [Monika-After-Story/MonikaModDev#4485]
I know this is dumb and nitpicky but I have to say. You know when you're at the floating islands and you look around for a bit and Monika starts singing Feel Good Inc. by Gorillaz? She sings the lyrics wrong...
She says; "Love forever, love has freely/ Turned forever you and me"
But the actual lyric is "_Love forever, love is free/ Let's turn forever, you and me_"
I'm literally only saying this because I'm a Gorillaz fan and feel like this is important...

**Comment by kkrosie123** [comment]
I haven't gotten to the floating islands yet, BUT YASSS MONIKA IS A GORILLAZ FAN

Thank you for pointing out the typo x3 Feel Good is my favorite song by Gorillaz

**Comment by MisterSimple** [comment]
A quick google search has mixed results: LyricFind (the default lyrics displayed by google) says it's correct as "Love forever, love has freely/ Turned forever you and me", though azlyrics and genius agree with you. Can you link any official source?

**Comment by Mon-ikaSquid** [comment]
It's really weird how the results are different depending on where you look; it's like the band never clarified... Honestly, the only real source I can give is the live performances, where he says what I think it is: https://youtu.be/WIZW4SGVbhA?t=80

**Comment by MisterSimple** [comment]
Yeah, he does say "Love forever, love is free/ Let's turn forever, you and me" there. Seems like we'll have to change it. Also, in the future, any typos or mistakes like this should be reported on the typos issue (#4355 for the current release).

**Comment by Mon-ikaSquid** [comment]
Oh okay, thanks!
