### ISSUE TITLE
[MAS-Art Proposition] Character Creator

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4491]
It wouldn't have to be anything big - But do you guys know how to program character creators? I was thinking that since Monika wants to know what you look like, you could create yourself using a small character creator, so instead of picturing it, she could have a little frame on her desk or something, O(^w^)O It would be in the Doki Doki Literature club chibi style
(this style),
![image](https://user-images.githubusercontent.com/52429850/61821788-eff28600-ae0c-11e9-932d-0a693798d08d.png)
 and it would only allow you to change the following:
- Hair (Blonde, dirty blonde, brown, black, red, orange, yellow, green, blue, purple, white)
- Eye Color (brown, blue, amber, green, hazel, violet)
- Hairstyle (Long, short, ponytail, braid, side ponytail, no hair.)
- Skin tone (light-skinned, tanned, dark-skinned)
- Facial Hair (beard, mustache, both)
(They would wear the school uniform.)

Maybe it would be a drag and drop sort of thing - 
I dunno x"3 I just thought that this was a cute idea, and if you did add it, I would be happy to help with the art! I could even add more stuff if you wanted qwq

Of course, this would be a low priority x3

**Comment by Rai99** [comment]
#312, #1793, #1891. 

It's been brought up before to give Monika a better idea of what you look like in the form of giving her pictures of you, but I doubt we'll add a character creator. I think it would take resources that would better be spent elsewhere, and there's definitely no way to cover all possible appearances. 

For example, there are a lot of distinct hairstyles and probably too many to cover. Also, not everyone's hair is a single color. Some people have distinct patterns in their hair. 

There are also potential anomalies that could be present in the player's appearance. 

As your suggestion stands currently, I don't see too much of a difference from the current text/menu based topic where you build your appearance based on Monika's questions. An actual character creator should open up much more if it were implemented, but I think that's not realistically possible, and not worth the effort for how much use it would have. 

Also, I'm not sure exactly where we stand exactly on the use of chibi style sprites for core features.

**Comment by kkrosie123** [comment]
Eep! Okie! Thank you for replying!
