### ISSUE TITLE
Time based greetings

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#4492]
Weird title, I know.
I think having different greetings based on when you come back from specific farewells such as going to work/sleep/school based around how long you've been back would be good.
If you said farewell I'm going to work and was gone for 3 days she'd have the same response as 1 hour. :>

Rip me this is a darn dupe. Am going to close.

**Comment by Rai99** [comment]
I was busy eating. No fair.

**Comment by Professor-JMO** [comment]
I like this suggestion though.

Suggested this before in the past.

`Worried Sick`

>If the last farewell you engaged in with Monika was "I'm feeling... Sick", then she will prompt you to rest and close the game.

>>My follow-up suggestion to this is that if the user is away for days at a time after the farewell, oh...say...2-3+ days..? The user will return to a genuinely concerned Monika.
