### ISSUE TITLE
Pointing music bug on "script-stories.rpy"

### ISSUE THREAD

**Issue by DarkskullDawnZenith** [Monika-After-Story/MonikaModDev#4495]
After Monika end narrating "The Hunter" story, the bgm _"happy_story_telling.ogg"_ kept on playing and turned out that _"script-stories.rpy"_ didn't had the _"stop music"_ and _"$ mas_startup_song()"_ lines down of this line _"$ mas_scary_story_setup_done = False"_

**Comment by ThePotatoGuy** [comment]
im going to assume this was fixed at some point if it was an actual issue.

[closing as fixed]
