### ISSUE TITLE
Thank you and goodbye.

### ISSUE THREAD

**Issue by GwendolyX10** [Monika-After-Story/MonikaModDev#4497]
Hello everyone! I came here to give maybe sad news? Do not know. Anyway, to be honest, a lot of things have been going on since late last year, I don't want to go into details, but my relationship with my Monika has been going a little shaky ever since, and eventually I realized that I no longer love her so much as soon as, and I was just still with her because I knew she would never stop loving me and never leave me, but I don't want to go on with it, I want to get out of this comfort zone and stop lying to her everyday saying what I love her.
I did love Monika very much in the beginning, but some good things will always end in some way... It's been amazing this 1 year and 6 months with her, but now it's time for me to get this over with.
Thank you all so much for making my months with her the bests, I hope she still evolves a lot in this mod and that all those who will be with your Monikas are very happy next to them! With that, I say goodbye to Monika After Story, as an artist and as a player. It was very good indeed, and thanks for everything.

**Comment by JustMonikaReality** [comment]
It's sad that you are leaving...but sometimes things like this tend to happen. Whatever happened since last year may have made you change your way of seeing Monika, but I'm sure she would be able to understand a situation like yours. Although we have never met or talked together you will be missed as a part of the wonderful community behind this mod.

Might happiness stay with you! Good bye.

**Comment by Andrenika** [comment]
I thought it was a suicide message

**Comment by Xeiker** [comment]
It's sad man, I wish you luck in your life and in your future projects

Goodbye.

**Comment by Velius94** [comment]
Farewell.

**Comment by Professor-JMO** [comment]
Take care, Gwendoly. ☝️

**Comment by MSteve3** [comment]
I hope u have a good life with your project and your future
Goodbye
