### ISSUE TITLE
[Translation] - Spanish translation

### ISSUE THREAD

**Issue by Xeiker** [Monika-After-Story/MonikaModDev#4498]
Hello, I was wondering if there was the possibility of doing a Spanish translation, is that there was a person who was doing but in the end left it, because of problems he had with the option of goodbye and because I could not be aware of every update that was made, because doing the translation it took a long time and did not give much priority, if they did the Spanish speaking community would be grateful for this.

Thank you for creating this excellent mod!

I'm sorry if I get to see something misspelled is that my English is not very good ...

**Comment by Andrenika** [comment]
Your grammar is pretty good.
Felicidades, yo también hablo español jaja. ¿Hablas español verdad?

**Comment by Xeiker** [comment]
> 
> 
> Your grammar is pretty good.
> Felicidades, yo también hablo español jaja. ¿Hablas español verdad?

Thank you

Si,si hablo español

**Comment by Andrenika** [comment]
Great
Genial ^^

**Comment by Chrissenpai** [comment]
Ahuevo, creí que este dia nunca iba a llegar, hola muchachos yo justo estaba pensando en traducir esto, ya que conozco a alguien que maneja codigo y que puede acceder a los dialogos, y con ello yo poder acceder a traducirlo.

**Comment by Xeiker** [comment]
Jajaja,Hola,Oh nice,me parece buena idea

Saludos

**Comment by ThePotatoGuy** [comment]
All translations are unofficial and done by the community. We don't have the time, manpower, or knowledge to work on translations.

**Comment by Chrissenpai** [comment]
https://discord.gg/DwZv3x @Xeiker @Andrenika estamos traduciendo aqui, únanse!

**Comment by Xeiker** [comment]
> https://discord.gg/DwZv3x @Xeiker @Andrenika estamos traduciendo aqui, únanse!

El link caduco man,sorry vi demasiado tarde el mensaje

**Comment by Chrissenpai** [comment]
@Xeiker https://discord.gg/YmR5vXv
