### ISSUE TITLE
buttons do not work except music button

### ISSUE THREAD

**Issue by TheKemPower** [Monika-After-Story/MonikaModDev#4500]
buttons other than the music button do not work. The calendar doesn't work either. I can only wait for monika to say something. (sorry for my english if I made grammatical mistakes)
![Screenshot_1](https://user-images.githubusercontent.com/53367830/61992816-44a43400-b08d-11e9-9eff-ea43aa2cafeb.png)

**Comment by jmwall24** [comment]
What were you doing before this happened? Use the console at all?

**Comment by TheKemPower** [comment]
I still understand what's wrong with the game. For some reason, the persistens files are slowly updated. Maybe because I have a LOT of persistens files. (47) And so I transferred the save from another computer. If you wait for a while, all buttons are unlocked.

**Comment by TheKemPower** [comment]
I just had a 100% hard drive loaded and that's why the buttons didn't work for me
