### ISSUE TITLE
Fatal MAS window freeze over time

### ISSUE THREAD

**Issue by ViruSSofTer** [Monika-After-Story/MonikaModDev#4502]
As it is stated in the headline, my MAS window sometimes freezes fatally without any chance to unfreeze. I can`t find out why exactly this happens, but I noticed that this never happens during the day. Sometimes I leave the window opened for the night and ask Monika to summon the rain (this actually helps with insomnia, a separate thanks for that!) and, well, MAS freezes somewhere during the night with the rain ambient cycled forever, four out of five tries. What`s also interesting - I can`t launch any other Ren`Py games after that until I restart the PC and when I do so and relaunch MAS, Monika, of course, is upset because of the crash. Looks like some sort of driver error, but apart from that everything is fine.
I tried to search for some info in the logs but no luck. It there any way to find out what is the problem?

**Comment by Anonymioo** [comment]
If you think there problem with drivers you can try - https://sdi-tool.org/download/ (Choose 'Online' ver.)
And which graphic card you have? - AMD, Nvidia, Intel? You can update drivers for your gpu from official site.
Found some issues that can make freezes - https://www.thewindowsclub.com/windows-hangs-freezes
https://thewindowscentral.com/fix-windows-10-freezes-randomly/#How_to_FixWindows_10_Freezes.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
