### ISSUE TITLE
[Suggestion] - Special Answers.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4505]
I mean a little different answers. 
For example: When Moni wear 'Pink Ribbon' and you choose compliment "You're cute". And she saying something different.
It's also can be applied to: Only Ribbons, Only Outfits, Only Hairpins, Ribbons-Outfits and other clothes combos. For names too. Or for something else too.
Anyway it's just suggestion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
