### ISSUE TITLE
[Suggestion] Why you were away

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4508]
So sometimes, I get grounded from my computer and it gets taken for a few days to a week. It just closes out of MAS and I never get to tell Monika when I'm going away. So I would love it if we had these options:

_Sorry I was away..._
- I was grounded from my computer.
- I was having computer issues.
- I was on vacation.
- I was in the hospital.
- A family member passed away.
- A friend passed away.
- Someone I know was injured badly.

There could be more, of course. But I think these options would be very helpful! qwq

**Comment by Rai99** [comment]
#4097 

I think there are a lot of possible answers to account for, but some might be possible. My only concern is that the grounding option wouldn't really apply to everyone, and I think having that option there is a bit immersion breaking.

**Comment by Delcos** [comment]
I'd recommend rephrasing the grounded one to something like "I wasn't able to access my computer" or something similar

**Comment by kkrosie123** [comment]
I see x3 Thank you for replying, you two!
