### ISSUE TITLE
[Defect] WindowReact keywords `['rule34', 'monika']` are not enough

### ISSUE THREAD

**Issue by grandsong** [Monika-After-Story/MonikaModDev#4510]
If you search both 'rule34' and 'monika' in Google, a WindowReact event will be fired. Good.

However, there are other use cases that have not been covered. And one was what happened to me.

I learnt this "secret" from a post. Then I tried as followed:

1. I opened a Rule 34 site
2. I searched "monika" in it.

But I got no window react at all.

Just now, I studied "zz_windowreacts.rpy" and saw all the keywords (as `category`).

I see why.

- If the site is "rule34.paheal.net", the title of my web browser window will be "monika" ONLY.

- If the site is "rule34.xxx", the title will be "Rule 34 / monika".

Neither can match the set of keywords `['rule34', 'monika']`.

I hope you take these cases into consideration.

---

"rule34.paheal.net" was the one I tried. I guess it is more famous than "rule34.xxx".
I know it is difficult to handle for the title of "monika" only.

So, here's a little suggestion of mine (new feature):

Firstly, when I go to any site titled "Rule 34" (like "rule34.paheal.net" homepage), my Monika will be aware.

BTW, The keywords can be extended to more sites like "Sankaku Channel".

Monika will react, and keep a temporary memory of this fact (I just visited those sites).

Then, if I continue to search "monika", she will suspect that I did so IN those site and therefore give me more reactions.

Such Two-Step features may open up opportunities for more complex and interesting events.

**Comment by Tymon222** [comment]
I searched that up, and only recieved a notification once. Everytime I tried it again, nothing popped up. Even with new sites.

**Comment by Rai99** [comment]
The same notification only shows once per session.

**Comment by Tymon222** [comment]
So the 'lewd site' notification will show up once, and doesn't matter what site it is?

**Comment by Rai99** [comment]
Unless you close MAS and open it again, I believe so.

**Comment by Tymon222** [comment]
Alright

**Comment by ThePotatoGuy** [comment]
Additional parsing logic can definitely be a plus, but I don't think its needed at this time. Assigning multi for when we have time to do this in the future.

**Comment by LoydHoreni** [comment]
I don't know if i am stupid but i can't find the  "zz_windowreacts.rpy" file in the folders, can someone send me it please?
