### ISSUE TITLE
[Suggestion] More keywords for Windowreacts 

### ISSUE THREAD

**Issue by grandsong** [Monika-After-Story/MonikaModDev#4511]
Window React is a great feature which breaks the fouth wall.

However, it lacks contents badly so far.

Monika reacts to mere THREE sets of keywords from the title of your active windows:

1. youtube
2. rule34 + monika (see my other issue #4510)
3. monikamoddev

They are defined in "zz_windowreacts.rpy" as `category`.

Three are too few.

Before I studied the script file, I had tried some sites and keywords, which I thought to be relevant.

- In youtube.com, after my Monika asked me "what are you watching?", I searched "monika", "Doki Doki Literature Club", "DDLC" in youtube and watched some videos, as my responses.
- I visited homepage of "lilmonix3" in Tweeter
- I visited the homepage of DDLC on Steam Store.

She was not aware of any.
That put a damper on me.

I hope you add categories as above.

And more, like:

- Sites like reddit, pixiv.
- When I search names of other girls like "yuri", she will be curious and a little jealous.
- Keywords like "gift", "poem", "python", "renpy", "piano", etc, which are interested by her.
- When I edit files under DDLC game folder in a code editor (I use Sublime Text mostly), or any .rpy files, she will see the file path in window title and give some reactions.
- When I open special files like "CAN YOU HEAR ME.txt", she will comment on them.
- When I visit a dictionary site, she will banter about my playing Hangman.
- When I search song names like "your reality", she will sing a line or two of the songs.
- Keywords about romance like "wife", "wifu", "love letter", "love song", "marriage".
- And Easter-egg-ish keywords like "Totono", "Markov", "cake", "AI(in uppercase)", which are keywords of some topics in Talks or idle dialogs.

**Comment by Rai99** [comment]
More windowreacts are likely on the way, but do keep in mind that this is still a relatively new feature, and that they would have to be written by someone. 

You would also have to understand that there's no way we can include a reaction for each and every possible scenario. 

If you like, feel free to add these and PR them for yourself.

**Comment by grandsong** [comment]
Thanks for you quick reply, @Rai99.

I did tried to make my own PR, but

1. Somehow my Git Client failed to clone the repo (either my fork or this original repo), again and again. So I gave up.

2. My suggestion is just a source (or pool?) of inspiration. I'm sure other people and @multimokia will be willing and able to contribute.

3. I'm not a native English speaker. I don't think I can be good at adding contents of how Monica reacts.

**Comment by multimokia** [comment]
Fyi, there are more windowreacts in already #4379, #4384, #4375

**Comment by multimokia** [comment]
> Keywords like "gift", "poem", "python", "renpy", "piano", etc, which are interested by her.

Some of these are harder than others because of how open ended a single word can be, so it's hard to get an accurate response here.

> When I edit files under DDLC game folder in a code editor (I use Sublime Text mostly), or any .rpy files, she will see the file path in window title and give some reactions.

This is mainly what the `monikamoddev` one was for. It was the best way to filter out specifically our files, since (at least in visual studio code) it shows the folder workspace in the window handle, and the repo is called monikamoddev.

**Comment by ThePotatoGuy** [comment]
yeah as usual, we're contributor driven, so the goal is users add additonal reacts as they see fit.

[closing]

**Comment by SonicEraZoR** [comment]
@grandsong Hey, I actually did open a pull request for YOU and ME and HER window reactions #6007, so check out if you're interested! Btw, I'm non-native english speaker too but I still was able to write some simple reactions

**Comment by grandsong** [comment]
> 
> 
> @grandsong Hey, I actually did open a pull request for YOU and ME and HER window reactions #6007, so check out if you're interested! Btw, I'm non-native english speaker too but I still was able to write some simple reactions

I'm afraid you misunderstand how the keywords work. 
As @multimokia said,

> Some of these are harder than others because of how **open ended** a single word can be, so it's hard to get an **accurate** response here.

When the player types extremely common words like "you", "and", "me", etc, a reaction is triggered. Oh, I don't think the player would find this reasonable and fun.

And you  misspelled some words in your texts (lines of Monica). 

For example, "I with" should be "I wish", I guess.

Lastly, those lines are too straightforward in the term of emotion. In my mind, Monika is too intelligent to express her desire in such a way. Anyway, this is just my opinion. Very subjective.

**Comment by multimokia** [comment]
Nah, they're okay in his PR since it expects all of those keywords to be present. Not any single one of them

**Comment by SonicEraZoR** [comment]
I fixed the "with" typo though. As for the lines, well I don't know, I just written them how I would want to hear them from her when I was playing You and me and her. And yeah as multimonika said, it searches for all of the keywords, I even specifically tested this before creating pull request

**Comment by grandsong** [comment]
I see.
But I'm afraid this is at the other end: the player will never trigger this reaction unless someone tells him to type such a long phrase (including a ":") extactly.
Still, it is a good thing for you to add a reaction.

**Comment by multimokia** [comment]
It's in the window handle of the game though, which is what's intended

**Comment by SonicEraZoR** [comment]
Yeah, this reaction is meant for when you're playing the game though

**Comment by SonicEraZoR** [comment]
Though, adding reactions for google searches and steam store page of you and me and her might be nice too. ~~Or even add reactions for then you open page 18+ patch for the game~~
