### ISSUE TITLE
Question - What is affection?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4514]
When looking through the update patch notes I often hear about "Affection" and I just assume that it kinda "unlocks" or "triggers" stuff..? (I really don't know how to word things) Anyways, can someone explain affection to me? Thank you!

**Comment by jmwall24** [comment]
This should help https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#affection

**Comment by kkrosie123** [comment]
Your amount of affection can be viewed in the affection log. The wiki jmwall24 sent should help you understand what it is and what it does.

**Comment by ThePotatoGuy** [comment]
[closing a sresolve]
