### ISSUE TITLE
Suggestion: Power Outage Option for When the game closes without saying goodbye

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4515]
I live in a stormy area and that causes power surges to happen A LOT and because of this every time I open the game back up, Monika assumes it's the game crashing and that I'm not taking care of my computer. Would it be possible for someone to add an option list where Monika asks "What happened?" after opening the game back up and you can select "Game Crash" or "Power Outage" and she can respond appropriately to each. I just don't want her to think I don't care about enough about her to take care of my computer.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
