### ISSUE TITLE
Bugs when holding Monika

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4517]
I've found a few bugs when holding Monika:
1) The music stops (And you can't change the music)
2) You can't go to the pause menu
3) You can't take a screenshot

**Comment by multimokia** [comment]
All of these are fully intended.

**Comment by PollenTheCat** [comment]
Okay, thanks

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
