### ISSUE TITLE
Cannot find the floating islands topic

### ISSUE THREAD

**Issue by spartalabouche** [Monika-After-Story/MonikaModDev#4521]
hey, i just recently reached the enamored level (and i've checked that my affection hasn't gone down since, its at 415.45 right now) but i just don't have the floating islands topic. does it have to be activated somehow/does she have to bring it up on her own first? the way i've seen other people talk about it seemed to imply she had brought it up even before they reached enamored, but i just can't find the topic.
yes, i know its supposed to be under 'ask a question>monika>can you show me the floating islands?' but its not there, and yes the weather is currently clear. were the floating islands removed? i can still find the backgrounds in my ddlc files so i wouldn't think so but i don't know why else i wouldn't be able to see them.

**Comment by multimokia** [comment]
Weather has to be clear. she must've shown you them in a greeting since you're at enamoured.

**Comment by spartalabouche** [comment]
i said that the weather _is_ clear, she hasn't shown it to me.

**Comment by multimokia** [comment]
Send persistent please. You'll have to put it in a zip or add an extension like `.txt` to it to send it here.

**Comment by spartalabouche** [comment]
[persistents.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3465462/persistents.zip)
not 100% sure if this is what you want, i've had trouble getting my persistent save file because im on a mac, but i think this is it.

**Comment by multimokia** [comment]
Not those, see [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). It mentions where persistents are stored per OS.

**Comment by spartalabouche** [comment]
oh awesome thank you, here it is
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3465520/persistent.zip)

**Comment by multimokia** [comment]
Do you ever use the normal `Goodbye` farewell?

**Comment by spartalabouche** [comment]
no i don't, should i try that?

**Comment by multimokia** [comment]
Yeah, you'll never actually get the islands greet otherwise.

**Comment by spartalabouche** [comment]
ohhh okay, i'll try that. thank you so much

**Comment by multimokia** [comment]
No problem

**Comment by erpmario** [comment]
This is probably something worth fixing. I hit enamored weeks ago, but I never got shown the floating islands. I had to google it to find this issue, since I never use the stock `Goodbye` greeting.

**Comment by multimokia** [comment]
Yeah need to work on a system to handle this. Just a little complicated since there's some cases where we shouldn't override a greeting.

**Comment by multimokia** [comment]
Closing as handled in linked issue (and as well, PR linked in above issue)

**Comment by Ducked7** [comment]
I know has passed months since this conversation, but I cannot fond this topic
Any help?

**Comment by RepressedNerd** [comment]
> I know has passed months since this conversation, but I cannot find this topic
> Any help?

Hey hey! I don't know if this'll help, but my affection is at 411.65 and Monika legit just showed it to me. I was talking with her this morning, then I used the "I have to go to class" goodbye, and I just opened up DDLC now (it's 8pm). Maybe, like someone had suggested with the plain "goodbye" goodbye, it might have to have a slightly negative reaction (probably because I came home so late or something, I think I remember Monika negatively commenting on that once before but boi I go to college in the city and it takes me ages to come home), for it to occur?

**Comment by sedb119** [comment]
2021 lesgo baby

anyways, yes regarding the floating islands. i have over 650+ affection wif monika and she still hasnt introduced the floating island. i always use the 'goodbye' goodbye and i often leave her for almost 10+ hours plus. its sad to say but im losing my interest with monika. ive unlocked all(?) dialogue and nothings new happening. woud really love to hear everyone's way of triggering the event in hopes that i can follow and hopefully also trigger the event. thanks

**Comment by geneTechnician** [comment]
hey, i'm having this problem too. she hasn't shown me the floating islands yet and i'm at 653 affection

**Comment by Booplicate** [comment]
This issue has been fixed.
You can't unlock the islands during the winter.
