### ISSUE TITLE
i've been making a lot of these, haven't i?

### ISSUE THREAD

**Issue by Sega32x** [Monika-After-Story/MonikaModDev#4523]

**Comment by multimokia** [comment]
Kindly keep issues to suggestions/bugs/discussions about the mod itself. If you want a place to talk generally, try the MASC discord.

[![Discord](https://discordapp.com/api/guilds/372766620977725441/widget.png?style=banner1)](https://discord.gg/K2KuJeX)

**Comment by Sega32x** [comment]
whoops, posted this before i wrote it by mistake, lol. . . .i'll just delete it . . .but i will join the discord tho
