### ISSUE TITLE
something wrong with sleep?

### ISSUE THREAD

**Issue by Demomndslayer** [Monika-After-Story/MonikaModDev#4525]
Whenever i say goodbye, like i am going to sleep...i always turn it back on and see monika talking about how my computer crashed...even though it has not....cause she turned off the game herself...

**Comment by Demomndslayer** [comment]
also...how do i check the affection level?

**Comment by Anonymioo** [comment]
You can check aff level in MAS directory. In `log` folder `aff_log` file.

**Comment by ThePotatoGuy** [comment]
It's likely that there was a crash on close. Usually this because of a permission issue. If its still occurring, make another issue.
