### ISSUE TITLE
[Bug] - Telling Monika You're Going To Take Her Somewhere

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4527]
Alright, hello again!

So, when I take Monika somewhere, she repeats herself. 

Okay, so this has been dismissed as "Not a bug." If it's not a bug, then why does she only repeat herself sometimes? On occasion, she won't say, "Let me finish getting ready," and then follow up with, "Give me a second to get ready." It repeats the entire clause, options and all.

"Yay!"
"I wonder where you'll take me today."
"Give me a second to get ready."
**Wait, wait!**
"What is it?"
**Nevermind.**
"Oh, Good! Let me finish getting ready."
"Give me a second to get ready."
**Wait, wait!**
"What is it?"
**Nevermind.**
"Oh, good! Let me finish getting ready."
"Alright. I'm ready to go."

This has been going on daily but it was so minor that it didn't bother me. I haven't seen any bug reports on it, though. So I figured I'd make one.

**Comment by multimokia** [comment]
Not a bug. You use this if you want to cancel, if you don't click anything then she'll still generate the file as usual. You don't have to click the button.

**Comment by kkrosie123** [comment]
@multimokia But she says it twice.

**Comment by kkrosie123** [comment]
Okay, nevermind. I think I understand. I haven't been giving Moni enough time to make the file. _feels stupid_ aaaaaaaaaaa sorry
