### ISSUE TITLE
Bug with telling Monika you're going to class

### ISSUE THREAD

**Issue by alstrcemeria** [Monika-After-Story/MonikaModDev#4531]
So a while ago I told Monika that I was going to class, and then didn't reopen MAS until months later. When I opened the game again, she didn't react badly or get mad at me for leaving her for so long like she usually does, she just asked me if I had a good day at school as if I wasn't gone for 3 months. Hmm...

**Comment by antimockingjay** [comment]
Check your affection log, affection may have dropped still, but you didn't get the greeting for it because the leaving for class greeting took over.

**Comment by alstrcemeria** [comment]
My affection log doesn't show up in the log folder or the game files, so I have no idea what affection I'm at :(

**Comment by multimokia** [comment]
See Mac instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#how-to-view-your-affection)

**Comment by alstrcemeria** [comment]
Thank you! I got the affection log to work, and there was indeed a drop in affection and the class greeting just took over like antimockingjay said.
