### ISSUE TITLE
[Art] - Background Redux.

### ISSUE THREAD

**Issue by Anonymioo** [Monika-After-Story/MonikaModDev#4534]
Made it more colored so it feels more saturated and warm plus added light-medium sharping to some places. 
And some changes like floor is smoother than old ver and walls smoother too. And some improvements. Mainly only smoothing.
Idk if you need it.
Old:
![monika_day_room1](https://user-images.githubusercontent.com/48754573/62697142-3d254900-ba04-11e9-8f80-d2cf349d0a07.png)
New:
![monika_day_room1 Redux 1-Edit](https://user-images.githubusercontent.com/48754573/62714081-137e1900-ba28-11e9-86f4-1168a9b41718.png)

**Comment by Oharo** [comment]
Am I seeing it wrong or did you also tint the transparency zones on the windows?
Wouldn't that break their function?

**Comment by multimokia** [comment]
We're already changing all of the weather masks, and a more yellow tint won't really make much sense overall. Even now, on a blue sky it doesn't make that much sense since the Sun isn't shining directly in. Also, floor was changed slightly because of other rooms. See #4503

**Comment by Anonymioo** [comment]
Ok. I'll close then.
Windows is ez to fix. And i can delete yellow tint.
