### ISSUE TITLE
[Suggestion] I'm feeling -> Freely

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#4536]
Option to tell Monika, that with her, [player] feeling freely and can be himself. Also, Monika once said that she really wants to be such a person for a [player].

**Comment by Thimeo** [comment]
I think it would be best suited to "I want to tell you something..." "I feel comfortable (or, "like being myself") around you."

**Comment by Rai99** [comment]
Feeling themselves doesn't quite sound right as a mood to me, but it might work better as a comfortable mood.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
