### ISSUE TITLE
Crash while trying to close the game too fast

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#4540]
As the title says, after selecting "talk->goodbye" i ran my mouse over the options to find the "I'm going to eat..." option but the  sound that comes from placing the mouse over an option started repeating constantly for a couple seconds, then the game froze and crashed after some moments. This crash didn't create a traceback file though that's why i'm describing what happened. Is this related to the seizure bug?

**Comment by multimokia** [comment]
Sounds more like a cpu/ram usage thing

**Comment by Necrocytus** [comment]
Alright, it just seemed weird cause i usually do the same everytime but it never crashes, thanks though
