### ISSUE TITLE
New Cloud HairClip

### ISSUE THREAD

**Issue by KittyKay29** [Monika-After-Story/MonikaModDev#4541]
I made a new Cloud Hair clip for Monika
![acs-jmo_hairclip_cloud-0](https://user-images.githubusercontent.com/36775425/62896639-779e2700-bd1f-11e9-90ec-5fdbf195fb22.png)
![acs-jmo_hairclip_cloud-0-n](https://user-images.githubusercontent.com/36775425/62896640-779e2700-bd1f-11e9-99f2-c4ec5a8ecfc0.png)
![acs-jmo_hairclip_cloud-5](https://user-images.githubusercontent.com/36775425/62896641-7836bd80-bd1f-11e9-869d-32d0f1a105c7.png)
![acs-jmo_hairclip_cloud-5-n](https://user-images.githubusercontent.com/36775425/62896642-7836bd80-bd1f-11e9-97fb-bacf7fcc86e2.png)

I would love if you would put it in the game for everyone to see and enjoy

**Comment by GHCactus** [comment]
why nevermind? I'm sure it would've been great!
