### ISSUE TITLE
Hangman Suggestions

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4544]
It's sort of confusing in my brain how Monika says the same response every time you win a game of hangman.
Perhaps some new dialogue could be added for certain win conditions, e.g.:
"Wow! No mistakes; nice one!" for zero-mistake wins;
"You were very close there; good job on finishing!", when the player is on their last 'life' and they win and similarly for (longer, not shorter) words that have one or two spaces remaining when the player loses.
Maybe some extra dialogue could also be added depending on whichever girl's words are answered the most.

**Comment by MetalBrother** [comment]
Maybe some extra dialogue could also be added depending on whichever girl's words are answered the most.

Yeah! Like if I don't guess, for example, five words that relate to Monika, she will be upset.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
