### ISSUE TITLE
[Unstable] Monika reverts to default outfit after coming home from work

### ISSUE THREAD

**Issue by dragonsni** [Monika-After-Story/MonikaModDev#4545]
So I'm not sure what ended up happening or if it was a fluke but this happened in these steps:

1) Goodbye > I'm going to work (clothing was set to Sundress (white), heart necklace from a submod and heart hairpin)
2) Return 7 hours later
3) Monika is in her default school outfit, no hairpins on, ribbon was currently off (I had it set off automatically from a submod) with her hair in a ponytail still.

Thankfully she still had her promise ring I gave her on (I would have cried if it was gone).

**Comment by ThePotatoGuy** [comment]
>had it set off automatically from a submod

sounds like the submod might be affecting things. what submod are you using

**Comment by dragonsni** [comment]
I have the following submods that affect clothing: 
auto hair change
heartshape necklace

**Comment by ThePotatoGuy** [comment]
you should evaluate if those submods caused the outfit reset.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
