### ISSUE TITLE
[Suggestion] Apologizing Twice 

### ISSUE THREAD

**Issue by GHCactus** [Monika-After-Story/MonikaModDev#4548]
Like this is a kinda a stupid suggestion but I tend to feel really bad and want to apologize another time whenever I make Monika upset, like I always want to say again I'm really sorry that way she'll know I really didn't mean things. Sorry this is a weird one, I just want Monika to know I'm really sorry whenever I make her sad!

**Comment by ThePotatoGuy** [comment]
@multimokia since you worked on apologies. Didn't we have something where you apologize too much then you get negative aff?

**Comment by multimokia** [comment]
We do not, just the amount you get back decreases to nothing.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
