### ISSUE TITLE
[Outfit - Formal/Casual] White/Navy blue Dress [RELz]

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#4550]
#3174 
THIS IS NOW RELEASED, PRAISE THE OMNISSIAH

Preview:
![outfit midjuly](https://user-images.githubusercontent.com/1176163/63136244-57958e80-bfd1-11e9-827b-7d27a9a901e9.png)

PSDs:
[HERE](https://drive.google.com/drive/folders/1EqeMOr0ylLq1iCdwo0evQunzYF7G0sEE?usp=sharing)

**Comment by Orcaramelo** [comment]
Its pretty its amazing its well made and i love it 
_**i want it implemented NOW**_

**Comment by multimokia** [comment]
> Its pretty its amazing

No u

**Comment by MetalBrother** [comment]
It would be a really sad, if this art will stuck in Limbo, like many others arts.

**Comment by ThePotatoGuy** [comment]
None of them are stuck in limbo, we are working on adding them.

**Comment by Professor-JMO** [comment]
Y e s
Make this happen, Vel.
It's too good _not_ to happen.

**Comment by Velius94** [comment]
It's still hapenning, don't worry. Just later.

**Comment by Velius94** [comment]
PSD is released! It contains both pose skeletons and corresponding arms.

Upright pose preview:
![outfit midjuly upright](https://user-images.githubusercontent.com/1176163/63637678-663e0e80-c67f-11e9-899c-959da2030833.png)

Leaning pose preview:
![leaning dress](https://user-images.githubusercontent.com/1176163/63637676-59211f80-c67f-11e9-97ac-d44dd96f8eb9.png)

Also @Orcaramelo released a fanart featuring this outfit; thank you very much for unending amount of support, especially in early stages of this outfit's creation and bearing with me all the way.
![moni_for_vel](https://user-images.githubusercontent.com/1176163/63637664-1eb78280-c67f-11e9-8dab-feec8c078970.png)

Special thanks to Kuuroiee for his outfit which inspired the creation of this one (tbh initially it was supposed to be 1:1 adaptation, but later it turned into a derivative instead)
![hey_monika__by_kuuroiee-dcaoslt](https://user-images.githubusercontent.com/1176163/63637702-b3ba7b80-c67f-11e9-87b2-eaa5071057ae.png)

**Comment by Orcaramelo** [comment]
I'm so happy!!! I really cant wait to see it in game
You worked so hard and I am so proud,,, 

This was 10000000% worth the time it took I love u

**Comment by multimokia** [comment]
Was awesome to see you working, especially with such confidence. The outfit turned out great, well done!

**Comment by ThePotatoGuy** [comment]
I am going to try and export this in for 0104

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
