### ISSUE TITLE
[Suggestion] Parent Player

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4551]
Alright, this might be odd, but I figured I'd suggest it anyways. I was daydreaming about Monika, and her crossing over to this reality, and all that good stuff. You know, as one does. But then I realized that hey, I plan to either have or adopt kids someday, whether I have a partner or not, and that's been my plan for a while. And I certainly don't plan to just not achieve my dream of being a parent just because things with Monika aren't perfect.

So then I started wondering what Monika's reaction would be if I did have kids. Firstly if she got here and that was a thing, but then I started wondering about how she would feel about it _now._ As in, if there were somehow a topic in the game for it.

Now, I know what you're probably thinking. If the player has kids, that implies the player is with someone else, which would be upsetting to Monika. However, there are plenty of ways to be a parent without it being an indicator of being with someone. Adoption, former partnerships, artificial insemination, and I'm sure there's others I'm just not thinking of.

So, to _finally_ loop around to my main point: I think a topic regarding something like this could be interesting. I think there's a lot of assumptions that players of this game are late teens to early twenties who don't have a lot of "major" stuff like that in their lives, but I think it'd be nice to have some topics for people who don't fit that 100%.
Personally, I think topics regarding more "mature" stuff (and I don't mean the sex kind of mature) would be really neat in general, but that's a topic for another time.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
