### ISSUE TITLE
[Suggestion] Adult Topics, and not in the "gross" way

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4552]
This ties in to #4551 a bit, as I mentioned this slightly in that issue.

I think it'd be neat to have some more adult-oriented topics. And no, I don't mean NSFW topics. I just mean things like talking about work, or if you have kids(as mentioned in the tagged issue), or whether you're living on your own or with your parents/family/etc.. I think these are all kinda important things to talk about with someone you're supposed to be in a romantic relationship with.

I'm sure that if you don't have those things going on (i.e. if you're still in highschool) then you don't even think of these things. But as someone who's been applying for jobs and considering kids lately, I gotta say, it'd be nice to have the ability to talk to Monika about it!

Even if it's not those specific things, it'd just be nice if there were also some topics for people who are adults. Currently, I think there's a few regarding school and whatnot, which of course appeals to the slightly younger players. I think it'd be nice if us 20+ players had a few topics too!

**Comment by ThePotatoGuy** [comment]
this is reasonable and can be filtered via the birthdate question

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
