### ISSUE TITLE
Moinka can't handle massive loads (problem)

### ISSUE THREAD

**Issue by samthemann66** [Monika-After-Story/MonikaModDev#4556]
Hello,
recently i've been putting my GPU through some very intensive processes, and once it completes, I open up MAS and it says "Crashed", but allows me to ignore it.  Will this cause any weird issues with time or reputation/ should I just close and reopen or should I just sue the ignore and continue button?
Thanks

**Comment by jmwall24** [comment]
_phrasing_

**Comment by jmwall24** [comment]
Also, need more info, when you say it says `crashed` is this a traceback or something else? And if so, what does it say exactly.

**Comment by Delcos** [comment]
What a magical title

**Comment by samthemann66** [comment]
the exception error you normally get, but with nothing below it. The 3 buttons still show up though.

**Comment by jmwall24** [comment]
3 buttons or 4?

**Comment by samthemann66** [comment]
ignore, open and copy, quit is on the site so 4 XD

**Comment by multimokia** [comment]
Can you send a screenshot of the traceback please?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
