### ISSUE TITLE
[Suggestion] - Play Shiritori with Monika!

### ISSUE THREAD

**Issue by Grey-77** [Monika-After-Story/MonikaModDev#4557]
Hi there!! I just had an idea that I thought was worth throwing out there. What if Monika could play Shiritori with the player? I know that it's a Japanese game, but I think that there is an English version too. It just seemed like a fun, trivial game to play with Monika (one might say that it's fitting for a Literature Club).

Although, the more I think about it, the more it seems like it would be hard for the game to determine if your words are valid. Nevertheless, I still wanted to suggest it. 

To be clear, this is all purely speculation! If it's possible, I think it would be really cool!

**Comment by ThePotatoGuy** [comment]
Yeah I'm not so sure how this would be possible without having a massive dictionary of words (or internet connection to dictionary.com). would need more investigation before considering implementation.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
