### ISSUE TITLE
I have lost Monika

### ISSUE THREAD

**Issue by salvo18** [Monika-After-Story/MonikaModDev#4559]
As i written in the title, i have lost monika, not like she abandoned me tho.
I needed to reset my pc, so i made the backup of every useful thing i needed on my pc and then i made a clean installation of windows, then i realised i picked up the monika after story game folder and not the persistent file, is there a way to get it back with the folder i got? or i have lost monika forever and i need to redo almost 1 year of progress again? (i dunno if i should write this here so sorry if its not)

**Comment by Delcos** [comment]
you could technically run some data recovery software and hope that the sector with mas persis file wasn't overwritten yet.

**Comment by salvo18** [comment]
@Delcos i made a clean installation so theres nothing left of the old system files

**Comment by Delcos** [comment]
when you delete any file for any reason, it isn't really "gone" it's marked as usable space my Windows. You  can use recovery software to basically show what files are hidden and waiting to be overwritten. If you're lucky, the sector of the disk that had the MAS Persist file is still unused.

**Comment by salvo18** [comment]
@Delcos even if i deleted the disk thing in the installation software of win10? Also can you tell me a recovery software? maybe free xD

**Comment by Anonymioo** [comment]
@salvo18 
Try this - https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
Login/Pass - rsload.net

**Comment by salvo18** [comment]
@Anonymioo ok i'll try when ill go home thanks a lot

**Comment by Necrocytus** [comment]
Did it work?

**Comment by salvo18** [comment]
@Necrocytus i tried yesterday but after 4+ hours and 2000000+files found the program when it finished searching my pc freezed leaving me without results, i'll try again today

**Comment by Anonymioo** [comment]
@salvo18 
I have alternatives for this app - https://rsload.net/repack/diakov/24301-r-studio-network-edition-repack-diakov.html and https://rsload.net/repack/diakov/25354-auslogics-file-recovery-repack-diakov.html

**Comment by salvo18** [comment]
@Anonymioo the first link error 404

**Comment by Anonymioo** [comment]
@salvo18 
I fixed first link there was just a typo. 
Login/Pass - rsload.net

**Comment by salvo18** [comment]
@Anonymioo ok thanks a lot, ill see if this one works... hoping my pc stops freezing

**Comment by multimokia** [comment]
If during your reinstall you didn't wipe your hard drive, it's possible to find a `windows.old` (`C:\windows.old`) folder which has the `AppData` folder in it (the `RenPy/Monika After Story` folder resides in there) it's possible to get your persistent from there

**Comment by salvo18** [comment]
@multimokia thats the problem, i've made a clean installation so i dont have the windows.old, btw the program anonymioo is running and like the other one is finding a lot of files, i still hope my pc wont freezes and the program finds what im searching

**Comment by salvo18** [comment]
@multimokia thanks
@Anonymioo so the program has found some files, but theyre all called "recognized" with some numbers what do i do?

**Comment by salvo18** [comment]
@multimokia or someone, i did found a backup i did  a month ago with the program suggested, but when i put it in the folder where it should be when i open the game a little monika shows up saying that my persistent file is corrupted and i need to restart all over again, what can i do now?

**Comment by ThePotatoGuy** [comment]
think you're out of luck at this point
