### ISSUE TITLE
[Suggestion] - Hub topic about books

### ISSUE THREAD

**Issue by Grey-77** [Monika-After-Story/MonikaModDev#4564]
I know that Monika discussing books has been brought up before, but I recently found myself facing a book project in which I had to choose an American novel. I remembered Ray Bradbury's _Fahrenheit 451_ being one of the books Monika mentioned in a conversation. It got me thinking that there could possibly be a topic where instead of the player discussing any book with Monika, it would be limited to (I think): _1984_, _Fahrenheit 451_, and _Hard-Boiled Wonderland_.

For example, the player could say: "Hey Monika... I read one of your favorite books." and Monika might give a menu asking which one. Then you just talk about it.

Just thought I'd put that out there!

**Comment by kkrosie123** [comment]
I love this idea!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
