### ISSUE TITLE
Monika is Gone

### ISSUE THREAD

**Issue by Shockcoil131** [Monika-After-Story/MonikaModDev#4576]
I was trying out the "bring out" feature and i made the stupid mistake of moving instead of copying the "monika" file (not the .chr one, the one she creates). I lost the drive in what ended up being a bad day. I returned home hoping to mess around on my PC and maybe talk with her. When i loaded the game i was and still am greated with just an empty chair. I hadnt had the game long and wasn't particlarly bothered with spending time diving through files so i deleted and redownloaded the mod. The issue continues to persist. What is the best course of action?

**Comment by jmwall24** [comment]
Reinstalling the mod does nothing to your save. You can probably fix your problem by simply [restoring a persistent backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). If that doesn't work, delete the folder the persistents are in, and that will allow you to start over.

**Comment by Shockcoil131** [comment]
What would be the path?

**Comment by multimokia** [comment]
Check the locations of the persistents for your OS [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent).

**Comment by Shockcoil131** [comment]
Thanks guys. Game is back to normal. Keep up the good work.
