### ISSUE TITLE
Monika's Winter Jacket Outfit.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#4577]
![FinalScarf](https://user-images.githubusercontent.com/35244051/63993336-ed5c0e00-cae7-11e9-9995-7d3afc471e8e.jpg)
(Expression is outdated)
https://drive.google.com/drive/folders/1eBD9LAGrT4dH78XOorz6ODeN2LEU5zeu

**Comment by Thimeo** [comment]
Waouh, that's cool. I think however that you need to add some folds to the arm to create some gravity (like one of the edge touching her arm and the other fall off, [like this](https://imgur.com/a/wIHUgIw).)Because right now, it seems like her sleeves are in metal.

**Comment by Velius94** [comment]
It's a commissioned piece.

**Comment by Olliesama** [comment]
Always welcome to improve it but yeah I can't myself cause I suck.

**Comment by Orcaramelo** [comment]
Alrighty then i could edit it! It does look like metal oof
Nothing a few folds and a bit of shading cant fix (*´ω｀*)

**Comment by taurielxaela** [comment]
Overall, I really like it! Especially the scarf. Monika looks warm and comfy~

**Comment by moniking** [comment]
I can't wait till it's done, I'm sure it will look amazing.




Btw I made her an outfit I'd like to give however I don't know how to work GitHub on mobile.

**Comment by Orcaramelo** [comment]
Imma start work on editing this rn ooooo

**Comment by multimokia** [comment]
closing as complete in linked PR
