### ISSUE TITLE
A Possible Solution To Telling Monika Your Sexuality

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4579]
Hello! It's been a while since I've contributed here, LOL. 
  But anyway, I've been thinking a lot about this topic. Many people want to tell Monika their sexuality, but if they're gay, for example, it would be difficult to come up with a response. The idea for her reply has been, "Well, I guess I'm the exception!" It has been thought to sound a bit homophobic.
  I thought of a lot of different ways for her to say that in a _nicer_ way, ahah. 

Here's one idea:

"Oh?" (1wud)
"..." (1duc)
"Ahaha, sorry, I just didn't expect you to say that!" (1rksdla)
"You know since you downloaded this mod and all." (4eksdlb)
"I don't really know the right way to put this..." (2rksdlb)
"But with all the time we've spent together," (1ekbla)
"I think you know that that could never affect the way I see you."(3ekbla)
"Just know that I support you no matter what, _player._" (1hubfb)
"Thank you for being open-minded enough to spend your time with me, though." (1ekbfa)
"I personally am _player_-sexual." (1kua) - Maybe we wouldn't include this part LOL. It's just something I would say. But I know Monika likes to make jokes - so I don't know.
"Ahahah!" (1hksdlb)
"Sorry, that was weird." (1lksdla)
"I'll always love you, _player_!" (3hubfb)

And somewhere in there, maybe there could be a, "I don't have anything against that stuff. Love who you want!"
But I feel like in this example it may sound a bit homophobic (because it would imply she was the exception). It would also have to be left out for an example such as when a female player says she's straight or something.

  If this still sounds a bit homophobic, I'm sorry. I never intended for it to sound that way - I, myself, am a lesbian. I just think this sounds better than, "I guess I'm the exception!"

This may be a duplicate, and if so, I'm sorry. Anywhoo, I hope this helps some!

Edit: I'm still learning how to add dialogue. I hope I can contribute topics sometime soon!

**Comment by CrocandCo** [comment]
Not bad. I understand it is a bit tricky to word your thoughts correctly when something unusual occurs. I do wish to see more people contribute to this mod.

**Comment by kkrosie123** [comment]
Closing, seeing as this has gone nowhere and is obviously never going in.
