### ISSUE TITLE
[MAS-Art] Donut (WORK IN PROGRESS)

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4580]
**August 31st, 2019**

Here's the first sketch for a donut I'm making!! : D

**NOTE:**
- The sketch may be resized and moved around a bit. : 3
- The linework may differ from the sketch.

![Donut sketch](https://user-images.githubusercontent.com/52429850/64069989-09f96280-cc1c-11e9-8631-52126bacc041.png)

**Comment by kkrosie123** [comment]
**Color Update**
- Fixed up linework
- Colored
- Added basic shading
- (Still a WIP)
- Moved to center of table
- Design and shape WILL be altered

![1](https://user-images.githubusercontent.com/52429850/64070101-6c079700-cc1f-11e9-9160-1fae16045cb6.PNG)

**Comment by kkrosie123** [comment]
**August 31st, 2019**

**Shading Update**
- Fixed the shape of the donut
- Started fixing the shape of the plate
- Added shading
- Smoothed out lines
- Erased dirt

![2](https://user-images.githubusercontent.com/52429850/64070283-6790ad80-cc22-11e9-8e1f-ec004eebcb55.png)

**Comment by kkrosie123** [comment]
**August 31st, 2019**

**Shading Update**
- Added shading to plate
- Cleaned up sprinkles
- Defined lines
- Made donut hole more defined

![3](https://user-images.githubusercontent.com/52429850/64070506-218a1880-cc27-11e9-9944-1957aea1af8e.PNG)

**Comment by kkrosie123** [comment]
**August 31st, 2019**

**Plate Update**
- Fixed the shape of the plate
- Fixed the symmetry of the plate
- Evened out the shading
- Smoothed out the lines

![4](https://user-images.githubusercontent.com/52429850/64070755-b04e6380-cc2e-11e9-865b-4378c1e03b8d.PNG)

**Comment by GHCactus** [comment]
looks good so far

**Comment by Orcaramelo** [comment]
Lemme give you a bit of guidance here :0
So, the plate can't really be in the center of the table, since crossed arms and leaning arms would be on top of it, but it can be on the side instead! Take JMO's Hanami Dangos for example:
![image](https://user-images.githubusercontent.com/47725743/64080733-150ccb00-ccce-11e9-9f9f-a72902b8c44c.png) https://github.com/Monika-After-Story/MonikaModDev/issues/4031
They are located on the side, so that it doesnt interfere with other acs! Try to keep that in mind when positioning the donuts!

**Comment by Professor-JMO** [comment]
Heyo, JMO here!
Would you be interest in our _Plate Template_, @kkrosie123 ?
You're more than welcome to 👌 

⯈ [ Plate 🍽️ ](https://github.com/Monika-After-Story/MonikaModDev/files/3563805/Nexus.Export.zip) ⯇

**Comment by hlepnamingblyat** [comment]
A cop's favourite meal XD

**Comment by kkrosie123** [comment]
Ahhhh I see!!! Thank you! I didn't even think about Moni's crossed arms lol

And thank you, JMO!

**Comment by kkrosie123** [comment]
**Placement and Color Update**
- Swapped plate to plate template
- Moved donut to left side of table
- Increased brightness and saturation
![5](https://user-images.githubusercontent.com/52429850/64084507-c113dd80-ccf1-11e9-80ca-c6b207cd9517.png)

**Comment by kkrosie123** [comment]
**September 1st**
- A proper preview! : DD
- Featuring my braid thing! : D
![6](https://user-images.githubusercontent.com/52429850/64084831-b27af580-ccf4-11e9-9eb2-6debc184630c.PNG)

**Comment by kkrosie123** [comment]
Bad
