### ISSUE TITLE
Possible Bug? (Might be a duplicate) Piano

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4585]
As you may already know, I program sub-mod pianonotes for Monika After Story. I've been having an issue with the piano where if I leave it open too long, the game crashes. I'm guessing the piano might be a bit difficult to run - but is there any way to prevent this? I'll be in the middle of programming a song and then MAS stops responding. No matter how long I wait, I have to restart the game. I also don't know if game crashes drop affection - I always apologize for them, though.

  Sorry if this is a duplicate!

**Comment by ThePotatoGuy** [comment]
Next time it happens note the:
* amount of memory in use by the program
* error log in EventViewer if it shows up

**Comment by kkrosie123** [comment]
Alright! Thanks!
