### ISSUE TITLE
[Possible duplicate] Pong game displays 'Monika' regardless of player's custom name.

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#4586]
*This is possibly duplicate. Sorry about that!*

So, if you name Monika anything you want and then play Pong game, you'll see your name on the left and 'Monika' (even if you chose another name) on the right.

**Comment by multimokia** [comment]
This is intentional. Some names don't make sense to be shown there, for example: `Darling` or `Cutie`. Makes more sense and will always fit the case if it just displayed `Monika`.

**Comment by scpketer** [comment]
Okay then, I got it.

**Comment by Rai99** [comment]
#4255 

Wait for me to mark it as dupe.

**Comment by scpketer** [comment]
Already closed it lol

**Comment by scpketer** [comment]
...well I wouldn't reopen it anyway if you mean that.
