### ISSUE TITLE
[MAS - Art] Different Hairs, Clothes, and Accesories (CHECKLIST)

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4593]
I like making these checklists. It's easier to find things. LOL.

If you have any suggestions for accesories you would like to see on Monika, let me know! I will add them to the list.

**September 3rd, 2019**

**Hairstyles**
- [Side Braid](https://github.com/Monika-After-Story/MonikaModDev/issues/4463) (In progress!)
- Braid _behind the head_
- Side Ponytail
- Curled Hair
- Short Hair (I've seen a lot of people who wanted to see Monika with a bob! This one is a huge maybe for me! Haha!)

**Bangs**
- Straight (I've seen some people who wanted it like that.)

**Hair Accessories**
- Cat Ear Headband
- Striped Headband
- Green Headband
- Jeweled Headband
_like [this](https://www.fashiongonerogue.com/wp-content/uploads/2015/12/Nasty-Gal-Aphrodite-Headband-Faux-Pearls.jpg)_

**Necklaces**
- Green O-Mamori Necklace (For the player!)
- Silver 'Monika' Necklace
- Black Simple Choker **Done by someone else!**
- Music Note Choker (Maybe Moni would rather wear a choker some days, who knows?)

**Bracelets**
- Green Simple Bracelet

**Clothes**
- [Green Hoodie](https://github.com/Monika-After-Story/MonikaModDev/issues/4658) (In Progress!)
- Pink Pajamas (Will be in progress soon)
- Turtleneck Tanktop (From experience, these are comfy!)

**Comment by lunulae** [comment]
I've seen quite a few amazing MAS sprites for TsukiZuraMaru's work being submitted, but the one I most sorely want is [this set of pajamas.](https://www.deviantart.com/tsukizuramaru/art/Waking-up-with-Monika-2-0-729809430)

**Comment by multimokia** [comment]
It's already on our wishlist in #3174

**Comment by kkrosie123** [comment]
Oooh! I was actually thinking of working on that! I just can't until I get an app that gives me access to the psds so I can edit them lol

I work with my phone :"D
