### ISSUE TITLE
[Suggestion] - Writing on the calendar

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#4596]
This would be a very low-priority suggestion, but on most months the calendar is pretty empty. I'd love to be able to write little notes of my own in there, just to make it seem a little more interactive and alive.

It wouldn't really be anything for Monika to react to, just a little extra flavor for the room. I'm not sure how the calendar is currently programmed, so don't worry about it if it seems like it'd be awkward to add.

**Comment by ThePotatoGuy** [comment]
marking as duplicate of #1771

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
