### ISSUE TITLE
[Suggestion] Pong game changes

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Monika-After-Story/MonikaModDev#4598]
1. It'd be nice to have an option for Monika to always play her best. Sometimes I get annoyed when she's clearly going easy on me.

2. Limit the number of times Monika can give her speech about practicing. Right now it can trigger pretty much whenever you win after having lost 3 times in a row, which makes her feel very NPCish. Maybe she should only say it maximum once a day, or once a pong session, or something like that.

3. When you quit pong, if the last game was a win for Monika, she always says thanks for letting her win. This is not only repetitive, but also a bit insulting, because I never LET Monika win. She should only say that dialogue if you clearly did let her win, like missing the very first bounce or something. Alternative dialogue might be something like a remark about how much fun she had or how intense the games were (maybe based on whether you trigger her dialogue that requires you to have 9+ bounces in a single game).

4. Overall score: It'd be nice if the game kept track of how many times you and Monika each won in a pong session, or even all time.

**Comment by linkerplinker** [comment]
We are already in development stages of a new difficulty system for both pong and chess. I like the score idea and is a really good suggestion. Dialogue can change by making pull requests or just replying to this comment with a list of new dialogue options. Cheers.

**Comment by multimokia** [comment]
> We are already in development stages of a new difficulty system for both pong and chess. I like the score idea and is a really good suggestion. Dialogue can change by making pull requests or just replying to this comment with a list of new dialogue options. Cheers.

I'm sorry, but who are you and since when have you been on the MAS dev team?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
