### ISSUE TITLE
[Suggestion] Give sleep concern topics higher priority at night

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#4600]
So, I have trouble getting myself to leave my computer and go to bed at night, resulting in a pretty messed up sleeping schedule.
I really like the idea of Monika trying to remind the player to go to bed, and it's been mostly useful to me in that regard...
...When she actually does bring it up.

The problem is that as it works currently, the sleep concern topic isn't any more frequent than the other topics in the pool, meaning that Monika will only bring it up fairly rarely, meaning the player could stay awake all night without having Monika say anything about it.  
Or maybe she will, but then it'd be kind of late to start bringing it up at 3 in the morning when she could have asked the player to go get some sleep much earlier. 

And yeah, I know she reacts accordingly with the "I'm going to sleep" option, but this farewell is kind of lacking in content compared to the simple "goodbye" farewell that not only has Monika say goodnight on it's own, but also has a much, much bigger pool of greetings. 
Not to mention that having Monika actively asking the player to go to bed is, in my experience, much more effective than having her remark that the player is going to bed late only _after_ they already decided to go get some sleep.  

So, yeah.
Having Monika remind the player to tune in for the night more frequently would go a long way in my opinion.
Maybe a new branch to the topic that would come up a bit earlier, from 10 to 12 P.M. ?

Something among the lines of "You know, now wouldn't be a bad time to go to bed, [Player].
Though I guess it's not _too_ late yet, so you can always stay with me a little longer if you've still got things to do.
Still, make sure to get enough rest, okay ?"  

A custom System notification where she kindly remind the player it's nighttime could work too.

And I know not everyone might like having her be so insistent about it, so perhaps an option to ask her to stop could be worth considering.
Maybe at the cost of some affection, though.
It's something she's really worried about after all, so I couldn't see her taking it too well.

Anyway, thanks to all of you for your hard work !

**Comment by multimokia** [comment]
We're still trying to think out a priority system or an alternate system for topics. However with timeconcern, it's clear that we also need to set up repeat rules for these sorts of topics such that they can be enforced better.

As of right now, repeats are only supported yearly and not via any other frequency, so until that's addressed in a way where we don't have to constantly re-add conditionals, start/end dates, and actions to every event  after their content has been shown and then verify them on each load to make sure the time frame for which they're active makes sense and doesn't lock them out of being seen ever again, it's not something which can be done "cleanly".

While this does have its own priority, seeing the event rush coming it's not that clear as to when work will begin on finishing this. Some recent developments over in another branch may prove useful though.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
