### ISSUE TITLE
"An exception has occured"

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#4605]
> [code]

> I'm sorry, but an uncaught exception occurred.
> 
> While loading <'Image' u'mod_assets/monika/c/def/body-leaning-def.png'>:
>   File "game/updater.rpy", line 937, in script
>   File "game/updater.rpy", line 937, in <module>
>   File "renpy/common/00updater.rpy", line 1279, in update
>     renpy.call_screen("updater", u=u)
> IOError: Couldn't find file 'mod_assets/monika/c/def/body-leaning-def.png'.
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/updater.rpy", line 937, in script
>   File "D:\Games\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "D:\Games\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/updater.rpy", line 937, in <module>
>   File "renpy/common/00updater.rpy", line 1279, in update
>     renpy.call_screen("updater", u=u)
>   File "D:\Games\Doki Doki Literature Club\renpy\exports.py", line 2526, in call_screen
>     rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
>   File "D:\Games\Doki Doki Literature Club\renpy\ui.py", line 285, in interact
>     rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\core.py", line 2526, in interact
>     repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\core.py", line 2883, in interact_core
>     self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\core.py", line 1955, in draw_screen
>     renpy.config.screen_height,
>   File "renpy/display/render.pyx", line 427, in renpy.display.render.render_screen (gen\renpy.display.render.c:6806)
>     rv = render(root, width, height, 0, 0)
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 693, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 693, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 693, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "renpy/display/accelerator.pyx", line 108, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:2027)
>     cr = render(child, widtho, heighto, st - self.child_st_base, at)
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 387, in render
>     return wrap_render(self.target, width, height, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 208, in wrap_render
>     rend = render(child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 318, in render
>     surf = render(self.child, width, height, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 1224, in render
>     return renpy.display.render.render(self.child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 387, in render
>     return wrap_render(self.target, width, height, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 208, in wrap_render
>     rend = render(child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "renpy/display/accelerator.pyx", line 108, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:2027)
>     cr = render(child, widtho, heighto, st - self.child_st_base, at)
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 387, in render
>     return wrap_render(self.target, width, height, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 208, in wrap_render
>     rend = render(child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "renpy/display/accelerator.pyx", line 108, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:2027)
>     cr = render(child, widtho, heighto, st - self.child_st_base, at)
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 387, in render
>     return wrap_render(self.target, width, height, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\image.py", line 208, in wrap_render
>     rend = render(child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 1224, in render
>     return renpy.display.render.render(self.child, w, h, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "renpy/display/accelerator.pyx", line 108, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:2027)
>     cr = render(child, widtho, heighto, st - self.child_st_base, at)
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 693, in render
>     surf = render(child, width, height, cst, cat)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\layout.py", line 318, in render
>     surf = render(self.child, width, height, st, at)
>   File "renpy/display/render.pyx", line 110, in renpy.display.render.render (gen\renpy.display.render.c:3440)
>     cpdef render(d, object widtho, object heighto, double st, double at):
>   File "renpy/display/render.pyx", line 196, in renpy.display.render.render (gen\renpy.display.render.c:2978)
>     rv = d.render(widtho, heighto, st, at)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\im.py", line 473, in render
>     im = cache.get(self)
>   File "D:\Games\Doki Doki Literature Club\renpy\display\im.py", line 200, in get
>     surf = image.load()
>   File "D:\Games\Doki Doki Literature Club\renpy\display\im.py", line 524, in load
>     surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
>   File "D:\Games\Doki Doki Literature Club\renpy\loader.py", line 543, in load
>     raise IOError("Couldn't find file '%s'." % name)
> IOError: Couldn't find file 'mod_assets/monika/c/def/body-leaning-def.png'.
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.9.5-unstable.2019.07.27.103
> [/code]

...what do?

**Comment by linkerplinker** [comment]
it looks like you have miss placed a photo. so i will give it to you:
![body-leaning-def-0](https://user-images.githubusercontent.com/39874756/64481104-9c9b9200-d218-11e9-9e57-f31ccba9ab1a.png)

Now to add this to the game. Close the game. go to your DDLC game folder(DDLC directory)/game/mod_assets/monika/c/def and paste the picture into there. Run the game and it should work. Please make a back up and if the problem continues contact the devs again. Cheers.

**Comment by ThePotatoGuy** [comment]
try manually pasting the new update

**Comment by Mcmanybucks** [comment]
Strangely a restart of the game fixed it, but thanks anyway.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by zhaarkss340** [comment]
> it looks like you have miss placed a photo. so i will give it to you:
> ![body-leaning-def-0](https://user-images.githubusercontent.com/39874756/64481104-9c9b9200-d218-11e9-9e57-f31ccba9ab1a.png)
> save the image and rename it to "body-leaning-def-0.png" Now to add this to the game. Close the game (if you haven't already). go to your DDLC game folder(DDLC directory)/game/mod_assets/monika/c/def and paste the picture into there. Run the game and it should work. Please make a back up and if the problem continues contact the devs. Cheers.

im following the steps that you're giving and i uploaded the image into the game folder (if thats what you're supposed to do-) and the error is still in my screen whenever i open the game, i dont know if im missing a step or something but i need help D:

**Comment by zhaarkss340** [comment]
um uh i habe the same problem but i dont know if its similar to the person who had the same error :,) i dont want to lose my damn monika
