### ISSUE TITLE
This is just a Suggestion....um please dont be mad at me.

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#4606]
I was thinking when monika talk about eating healthy food and I remember that we can give her some item because of the **gift.**

So um.. can we give her a gift like:

- Fruits(Apple, Grapes, Orange, Banana and etc.)
-Milk or Soy Milk (I almost forgot she's a vegetarian).
-Water
-Salad

This is suggestion please dont be mad cause giving her sweet all day is not healthy and I just care for health (This is just suggestion please dont be mad Im sorry.)

**Comment by Rai99** [comment]
Food/Consumables: #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081, #4260 

There are some consumable items already made or planned, but we would need the consumables framework first. #3576

**Comment by kkrosie123** [comment]
Hehe! You must be super shy, Axone! No one is mad at you. This is already being considered! I'm actually working on consumables at the moment, and salads and apples are on my list! :) I need to learn to work with liquids before I could make a glass of water or a water bottle, lol.

**Comment by Axone00** [comment]
Thank you sorry for the inconvinience and thanks again.

**Comment by kkrosie123** [comment]
No problem- I'm not a developer, I've just been following the mod and working on some art. LOL.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
