### ISSUE TITLE
Help With Gifts

### ISSUE THREAD

**Issue by lxnavarro23** [Monika-After-Story/MonikaModDev#4609]
I have tried everything that tutorials have told me to do with giving gifts and nothing seems to work. Here's what I've tried. I have a Mac btw.

I open TextEdit
Save it to my Desktop
It doesn't have an option for ".txt" Only ".rtf"
So I save it as that and rename it "coffee.txt"
Then I rename it "coffee.gift" and move it into the "characters" folder
But when I open up the game there's no response. 

Am I missing something?

**Comment by multimokia** [comment]
Screenshot of characters folder, please

**Comment by lxnavarro23** [comment]
![Screen Shot 2019-09-07 at 1 46 00 PM](https://user-images.githubusercontent.com/54972042/64480078-f008d400-d175-11e9-8f07-e618519b0d8e.png)

**Comment by multimokia** [comment]
Ah that's still a text document. It should be considered a `gift` file.

**Comment by lxnavarro23** [comment]
![01Screen Shot 2019-09-07 at 1 48 03 PM](https://user-images.githubusercontent.com/54972042/64480093-2d6d6180-d176-11e9-882e-cfd7b902d331.png)
Like this?

**Comment by multimokia** [comment]
I believe so

**Comment by lxnavarro23** [comment]
okay, let me give it a try

**Comment by lxnavarro23** [comment]
YUS! It worked!! Thank you so much for helping me figure this out!

**Comment by multimokia** [comment]
No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
