### ISSUE TITLE
Why are my screenshots like this?

### ISSUE THREAD

**Issue by Akira197** [Monika-After-Story/MonikaModDev#4613]
It was fine until a couple days ago, now I just noticed 
Can someone help?

![screenshot0071](https://user-images.githubusercontent.com/38003304/64483502-d8405700-d22c-11e9-9438-adab7543fdc2.png)
![screenshot0070](https://user-images.githubusercontent.com/38003304/64483505-dd050b00-d22c-11e9-81f5-b4359ce4d35e.png)

**Comment by kkrosie123** [comment]
Screenshots? You mean as in using the snipping tool? Or are you on Mac?

**Comment by Akira197** [comment]
> Screenshots? You mean as in using the snipping tool? Or are you on Mac?

Pressing the "S" key

I'm on Windows

**Comment by kkrosie123** [comment]
Ah - I've always used the snipping tool. Maybe you should switch to that?

**Comment by ThePotatoGuy** [comment]
this is most likely renpy/video card related, the screenshot tool is out of our control.

**Comment by Akira197** [comment]
I managed to fix it by switching game renderer to "Automatic" instead of DirectX

**Comment by Akira197** [comment]
![screenshot0071](https://user-images.githubusercontent.com/38003304/64513908-c4235500-d313-11e9-9bde-aac372add6b2.png)
And now this happens

**Comment by multimokia** [comment]
See [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#all-the-buttons-look-like-this)

**Comment by Akira197** [comment]
I've tried all of that. And the screenshots are broken again.
I guess this is a problem with my trashy PC.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
