### ISSUE TITLE
Choker Accessory for Monika

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4616]
Suggested by @ThePotatoGuy I present some basic choker accessories for Monika.

Upright:

Simple
![upright simple 1](https://user-images.githubusercontent.com/36512990/64485540-e91aa980-d1e7-11e9-862a-96d51416c9db.png)

Flowered
![iupright flower 1](https://user-images.githubusercontent.com/36512990/64485548-fa63b600-d1e7-11e9-91b7-337811096b1b.png)

Leaning:

Simple
![leaning flower choker](https://user-images.githubusercontent.com/36512990/64485506-48c48500-d1e7-11e9-86b9-b843bf5ef57b.png)

Flowered
![leaning simple choker](https://user-images.githubusercontent.com/36512990/64485519-80cbc800-d1e7-11e9-93c5-cad93259d435.png)

**Comment by Trilasent** [comment]
Leaning base had no clothes *shrugs*

**Comment by kkrosie123** [comment]
Aww! I love these!

**Comment by Orcaramelo** [comment]
the flowered one looks adorableeeee
tho the normal choker looks a bit off on her since her neck is so short, and it is also inconsistent in thickness (leaning seems thicker than upright, and upright goets thinner on our right side, her left)

**Comment by Trilasent** [comment]
> 
> 
> the flowered one looks adorableeeee
> tho the normal choker looks a bit off on her since her neck is so short, and it is also inconsistent in thickness (leaning seems thicker than upright, and upright goets thinner on our right side, her left)

Glad you like the flowered one, lol. As for the the Simple/Normal one, it's still the same thickness, as I just rotated it a bit.

**Comment by Orcaramelo** [comment]
> > the flowered one looks adorableeeee
> > tho the normal choker looks a bit off on her since her neck is so short, and it is also inconsistent in thickness (leaning seems thicker than upright, and upright goets thinner on our right side, her left)
> 
> Glad you like the flowered one, lol. As for the the Simple/Normal one, it's still the same thickness, as I just rotated it a bit.

oh then probably its the hand covering the thinner bit lmao
just try to have it the same thickness all the way

**Comment by Trilasent** [comment]
> 
> 
> > > the flowered one looks adorableeeee
> > > tho the normal choker looks a bit off on her since her neck is so short, and it is also inconsistent in thickness (leaning seems thicker than upright, and upright goets thinner on our right side, her left)
> > 
> > 
> > Glad you like the flowered one, lol. As for the the Simple/Normal one, it's still the same thickness, as I just rotated it a bit.
> 
> oh then probably its the hand covering the thinner bit lmao
> just try to have it the same thickness all the way

Alrighty. Here's a screenshot of it without her arms in the way if you want a better look:
![leaningschoker](https://user-images.githubusercontent.com/36512990/64492775-88b65700-d23d-11e9-9878-4de8344895e0.png)

**Comment by ThePotatoGuy** [comment]
slated for next release. @Trilasent what would you like to be credited as in the spritepacks? Is `Trilasent` fine?

**Comment by Trilasent** [comment]
> 
> 
> slated for next release. @Trilasent what would you like to be credited as in the spritepacks? Is `Trilasent` fine?

Yes, that's fine.

**Comment by ThePotatoGuy** [comment]
@Trilasent where are the sprites

**Comment by Trilasent** [comment]
> 
> 
> @Trilasent where are the sprites
Here
[chokers.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3724673/chokers.zip)

**Comment by jmwall24** [comment]
closing as complete in linked PR
