### ISSUE TITLE
Appearance options for Monika disappear 

### ISSUE THREAD

**Issue by EmpressNael** [Monika-After-Story/MonikaModDev#4617]
Some tabs in appearance options tend to disappear as I am switching outfits or other appearance changes. I seem to fix it when I have Monika in witch outfit. Not sure why this happens. I think it's partially due to sprite packs.

**Comment by kkrosie123** [comment]
Yes, that tends to happen, LOL. I may be interpreting this wrong -

Are you referring to options such as, "Can you change your ribbon?" or, "Can you change your hairstyle?"

I think the team is working on splitting the psds for the Rin (neko) outfit and the witch outfit. I saw an issue featuring the separated parts.

**Comment by ThePotatoGuy** [comment]
Some hairstyles/clothes are not compatible with other hair/clothes/ACS, so they selectors are disabled while that hair/clothes is active.

**Comment by EmpressNael** [comment]
I mentioned this on Discord tech support. This happens randomly, I be on default outfit, and option to change hair, or put ribbons, or put hairclips tends to disappear, not always. Even when I have hair down, for some reason, ribbons tab opens lol

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
