### ISSUE TITLE
Submods?

### ISSUE THREAD

**Issue by SasWarrior** [Monika-After-Story/MonikaModDev#4619]
Hi, i play mas for a long time now and i wanted to try the "submods", the thing is that idk how to install them and what issues i may encounter installing them and if there will be issues with future updates etc. Thank you

**Comment by ThePotatoGuy** [comment]
Submods are available at #3765 . Install instructions probably differ among them, you'd have to talk to the submod dev if they didn't provide instructions. There can be issues with future updates, but we try to avoid completely removing certain api functions so if something isnt art heavy it probably will still work in a future update

**Comment by SasWarrior** [comment]
Okay thank you c:

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
