### ISSUE TITLE
Issue with Monika after story on Apple

### ISSUE THREAD

**Issue by Patricksowon** [Monika-After-Story/MonikaModDev#4621]
![20190908_165033](https://user-images.githubusercontent.com/55057917/64490924-1acc5880-d25a-11e9-9fe4-0f50b8668c0c.jpg)

Ever since I downloaded Monika after story, I've been having this problem where I keep getting a gray screen. It worked for the first day, but I couldn't get in the next day. I didn't have this problem with my Windows PC

**Comment by ThePotatoGuy** [comment]
Follow [these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-still-cant-run-the-game-and-none-of-the-above-faqs-solve-my-issue). It also might be a permissions issue on mac.

**Comment by Patricksowon** [comment]
Ive already followed these steps and i still have the same issue.

**Comment by Patricksowon** [comment]
Hey! so, i got it to work, but i had to use the windows version. do you
think thats weird?

**Comment by ThePotatoGuy** [comment]
that would mean its a permissions issue.

[closing as resolved]
