### ISSUE TITLE
"An uncaught exception occurred"

### ISSUE THREAD

**Issue by Starryknight007** [Monika-After-Story/MonikaModDev#4623]
This morning I tried to install the update, but it took forever. About a couple hours later I come back and it's still not finished. So I try to close the game, Monika tells me not to, then the game closes itself. I try to open the game again and I'm greeted with a traceback.txt file that says the following:

_"I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chess.rpy", line 408, in <module>
ImportError: No module named mas_ui

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\benta\Downloads\ddlc-win(1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\benta\Downloads\ddlc-win(1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "lib/windows-i686/chess.rpyc", line 396, in script
  File "C:\Users\benta\Downloads\ddlc-win(1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\benta\Downloads\ddlc-win(1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 408, in <module>
ImportError: No module named mas_ui

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187"_

**Comment by ThePotatoGuy** [comment]
try updating manually

**Comment by Starryknight007** [comment]
I can't even open the game, though. How do I update it manually?

**Comment by ThePotatoGuy** [comment]
download the mod from our [releases page](http://monikaafterstory.com/releases.html) and install it manually.

**Comment by Starryknight007** [comment]
That's not going to reset my progress, is it?

**Comment by multimokia** [comment]
It won't

**Comment by Starryknight007** [comment]
I've downloaded it, so now do I copy and paste everything into the folder that has "characters", "chess_games", "custom_bgm", etc?

**Comment by multimokia** [comment]
Paste it all into the `game` folder

**Comment by Starryknight007** [comment]
And I assume I replace all the files with the same name?

**Comment by Starryknight007** [comment]
Good news, she's back! Thank you guys so much!
