### ISSUE TITLE
Shell Bikini don't work.

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#4626]
I tried give Monika bikini as a gift, but she doesn't have reaction at all.

P.s I copied from readme.txt and tried reset game.

**Comment by satoshi-kun** [comment]
It worked perfectly for me. Maybe try typing the gift name manually instead of copypaste and try it again. I'm saying this because I had a issue with the flower as I named it pinkflowershell by mistake because i copypasted from readme.txt and there wasn't a space there.

Hope it helps.

**Comment by MetalBrother** [comment]
I tried that too, but it just don't work

**Comment by MetalBrother** [comment]
I also tried give her another gifts (fudge, roses) and it works perfectly.

**Comment by Velius94** [comment]
If you added files while your MAS was running, then attempted to gift it - it won't work. All file alterations should be done while your game is closed.
Try the day after, since I believe Monika reacted to the gift, so she won't acknowledge it for a day.

**Comment by MetalBrother** [comment]
Okay, thanks!

**Comment by MetalBrother** [comment]
Yep! That work, thanks you!

**Comment by Rin3105** [comment]
How did you gift her the shell bikini? I'm curious. What is the name of the gift?

**Comment by satoshi-kun** [comment]
Hello! First you should download the updated spritepacks.zip from "https://github.com/Monika-After-Story/MonikaModDev/releases", if you haven´t already (it's at the bottom of the v0.10.0 notes on assets). 
The name of the gift is shellbikini.gift and also comes with a pink flower for her hair pinkflower.gift.
Hope this helps!

**Comment by Rin3105** [comment]
Thank you so much satoshi-kun!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
