### ISSUE TITLE
The "Auto" button doesn't stay highlighted while in dark UI mode

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#4628]
Title.
the Auto option is highlighted just fine when you move the cursor above it, and it works as intended during day mode, but in night mode, the text has it's default color whether Auto mode is activated or not.
(I would add a screenshot, but I don't think it would illustrate the issue really well.)

**Comment by jmwall24** [comment]
Yeah, we see it, no screenshot required. Thanks for reporting.

**Comment by jmwall24** [comment]
Closing as fixed in referenced PR.
