### ISSUE TITLE
How do I insert the new mod assets?

### ISSUE THREAD

**Issue by Codsty** [Monika-After-Story/MonikaModDev#4629]
Im trying to give Monika gifts, but she cant read them. Im assuming because I inserted the assets wrong. Is there a proper way to do it?

Thank you.

**Comment by kkrosie123** [comment]
Yes, there is. Have you read the guide [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D)? It's under "Gifts." Are you putting it in the character file? Or are you doing it correctly and the gifts aren't being read?

**Comment by Codsty** [comment]
> Yes, there is. Have you read the guide [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D)? It's under "Gifts." Are you putting it in the character file? Or are you doing it correctly and the gifts aren't being read?

Iv been putting them in the character file and she says she cant read them
