### ISSUE TITLE
[Suggestion] Going AFK

### ISSUE THREAD

**Issue by frostcattooo** [Monika-After-Story/MonikaModDev#4630]
We can tell Monika that we're going to be right back, but she never knows where we're going, and I thought it would be a good idea to let her know. For example, if we told her "I'm going to eat", we have an option to keep the game open or not.

**Comment by Rai99** [comment]
You mean like the `Be right back` feature?

**Comment by Rai99** [comment]
You can tell her that you'll be right back, which I think is exactly what you're asking.

**Comment by frostcattooo** [comment]
@Rai99 yes, but telling her where you are going to go. i suppose i should edit that to make it more specific, lol

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
