### ISSUE TITLE
How leaning arms should look like

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#4631]
The leaning pose arms looks like a male artist looked itself at the mirror and copied its arms on Monika lol. Now instead of just speaking with my text with how it should look like, I'll propose with images my version of how would be her arms would be down below based on the original sprites of DDLC 
![image](https://user-images.githubusercontent.com/40907045/64493920-f36e8f00-d24b-11e9-9b5d-9c4e99f3bf1f.png)

![image](https://user-images.githubusercontent.com/40907045/64493848-19476400-d24b-11e9-8850-9087bda447a0.png)

here is the line art that I propose, shown in green for clarity

![image](https://user-images.githubusercontent.com/40907045/64493901-b5716b00-d24b-11e9-984f-daca8bc20bb5.png)

Here is the before and after shown here for visual comparison

So if you like I'll leave here the modified file in the comments if you want to adapt to this artline. The skin tone is good so you can keep creating the same formula tone that you have.
Also I'll leave a message here.
To me, you are making her a bit too polished. Like she still has to be a real person, not a 100% anime girl, I mean there could 4 sprites two different bodies if you want to make them: real and anime, but you must not mix them, you must keep the Satchel art style consistent.
I hope I'm not alone with this.

**Comment by Orcaramelo** [comment]
Are you on discord? Check or WIP in spoilers channel! We are editing it there and will certainly take this into consideration :>

**Comment by Chrissenpai** [comment]
#4620

**Comment by jmwall24** [comment]
Don't agree with one part of that edit. Just because she's female doesn't mean she can't have a bicep at all. You making her right arm (our left) almost completely flat isn't really correct.

**Comment by Chrissenpai** [comment]
As I said: based on the sprites of DDLC
![image](https://user-images.githubusercontent.com/40907045/64494670-7fd17f80-d255-11e9-986e-16ab34f587b0.png)

**Comment by Chrissenpai** [comment]
and wait a second, bicep?

**Comment by ThePotatoGuy** [comment]
The Act 3 sprite, however, is a way better reference point than that one.

**Comment by Chrissenpai** [comment]
![image](https://user-images.githubusercontent.com/40907045/64494703-f1113280-d255-11e9-9c7d-1769175bde09.png)
almost not seeing much difference

**Comment by ThePotatoGuy** [comment]
Regardless, you're going to have to be real convincing because the changes you've proposed will affect partial sleeveless outfits, and rexporting leaning sprites for the 3rd time because of perceived leaning issues is not something I'm just going to do without good reason.

**Comment by Orcaramelo** [comment]
Satchel's art style does not have perfect anatomy, (take yuri's broken wrist for example) We can't copy their mistakes over to our version, we have to adapt and improve 
And yeah do keep in mind every single cothing sprite and ac will need to be edited.

**Comment by jmwall24** [comment]
You are comparing clothed arms with bare arms @Chrissenpai . Not really the best way to make your case.

**Comment by jmwall24** [comment]
A shirt and a blazer will cover-up curves that are visible on bare skin.

**Comment by Chrissenpai** [comment]
![image](https://user-images.githubusercontent.com/40907045/64494768-9debaf80-d256-11e9-8495-20a3fca33634.png)
Oh wait here it is, you're right it has some of it but on the current sprite it is still to big, we might have to find the middle ground

**Comment by jmwall24** [comment]
It may be possible. Slight changes to the bare arms and hand/wrist are probably doable, but as mentioned, huge positional changes are unlikely at this point, since it affects a ton of other things.

**Comment by Chrissenpai** [comment]
ok then if so might fix the hands for example

**Comment by Chrissenpai** [comment]
so yea in conclusion we need the curves on the arms less noticable

**Comment by Chrissenpai** [comment]
I've found the main problem of all, the arms are not consistent between upright and leaning base @ThePotatoGuy upright: arms consistent with the original sprite of just Monika act 3, but leaning: arms not consistent with upright sprite of MAS that was adapted from just Monika act 3

**Comment by Orcaramelo** [comment]
![image](https://user-images.githubusercontent.com/47725743/64495613-8cb09c00-d272-11e9-8a98-89692ee36f37.png)
we got to this.
clothing edits have been made, wrist fixed. thickness was also ajusted.

**Comment by Chrissenpai** [comment]
oh thank you!

**Comment by Chrissenpai** [comment]
wait hold on
![image](https://user-images.githubusercontent.com/40907045/64495850-48b69a80-d264-11e9-8627-78565545af51.png)
sorry for the nitpick but if you can do that, that would be nice since the lower arm is not so thick

**Comment by LClarance** [comment]
@Orcaramelo thank you for the fix! I hope you guys can release the update before her birthday and umm I've said it in my own thread but I agree with Chrissenpai on making her left arm thinner, it does feel weird looking at her thick arm, hope you guys can fix it. Again, thank you very much

**Comment by LClarance** [comment]
@Orcaramelo sorry to disturb you but its been days since your last comment but may I know if you are planning to reduce the thickness of Monika's lower right arm? Reason I am concerned about this is because her arm aren't as thick in her other sprites and in her official artworks as well so I think I need to bring this up since you haven't implemented the other fix and I figured it would be easier if you release them all at once instead of more people noticing about it in the future update and you guys have to go through extra troubles again. Or maybe if you prefer me to join the discord server and talk there? Sorry if I sounded offensive, but I think I need to clear my own mind sometimes, I've been thinking bout this for days tbh lol.

**Comment by Orcaramelo** [comment]
> @Orcaramelo sorry to disturb you but its been days since your last comment but may I know if you are planning to reduce the thickness of Monika's lower right arm? Reason I am concerned about this is because her arm aren't as thick in her other sprites and in her official artworks as well so I think I need to bring this up since you haven't implemented the other fix and I figured it would be easier if you release them all at once instead of more people noticing about it in the future update and you guys have to go through extra troubles again. Or maybe if you prefer me to join the discord server and talk there? Sorry if I sounded offensive, but I think I need to clear my own mind sometimes, I've been thinking bout this for days tbh lol.

So, that screenshot was the most we could do about the arms. They have already been passed onto potato and cuts were made, so we arent messing with the thickness any more.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
