### ISSUE TITLE
[Suggestion] Notification window icon / windowreact

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4634]
Hello! So I had this idea the other day of making a "Minika" icon to replace the "CustomIconWindows.ico" on the DDLC folder, in order to test if this new icon would appear on the windowreact when opening youtube ie.. Sadly for some reason this new icon file would "transform" back to the old DDLC icon as soon as I placed it into the folder (My programming skills are next to none).
Still I think it would be a neat feature (if it is even possible to do that), instead of having just the default logo on those windowreactions, having "Minika" there calling your attention.
Just an idea for consideration.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
