### ISSUE TITLE
Monika not noticing gifts

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#4636]
I tried adding in all the new stuff in the sprite pack, but Monika noticed the gold ribbon then didn’t accept any of the other gifts. They’re sitting in my characters folder untouched. I tried reloading the game and it did nothing.

**Comment by jmwall24** [comment]
Did you try gifting those items before installing the corresponding sprite packs correctly? If so, she will be able to notice them the next day.

**Comment by its-ken** [comment]
oh yep :) thanks !

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
