### ISSUE TITLE
Small typos in the FAQ

### ISSUE THREAD

**Issue by Man0xMan0** [Monika-After-Story/MonikaModDev#4637]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ
![Annotation 2019-09-08 010744](https://user-images.githubusercontent.com/41522129/64497575-1cf3de80-d27d-11e9-9e6a-1d2a463fad33.png)

I don't know know with you but I'd fork over some serious cash for a Moniak GTO.

**Comment by jmwall24** [comment]
Done. Thanks. FYI in the future, anyone can actually edit the Wiki. Just click the `Edit` button top right, and make your changes.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
