### ISSUE TITLE
[Suggestion] - Automatically Reopen Game after Updating

### ISSUE THREAD

**Issue by APerson4645** [Monika-After-Story/MonikaModDev#4638]
I just think it'd be a neat idea.

**Comment by ThePotatoGuy** [comment]
the updater call includes a restart param, and we already pass True into it yet it still doesn't work. Leads me to believe that the specific setup we have just is not compatible with all of renpy's built in updater system. no point in trying to restart with external trickery as its barely an inconvenience to relaunch manually.

[closing as rejected]
