### ISSUE TITLE
Game not working after updating the game

### ISSUE THREAD

**Issue by Abbyninjamonkey** [Monika-After-Story/MonikaModDev#4639]
alright been here but the after updating the game and open game it's now showing me the weirdest traceback I think I even seen and here it is
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'/home/potato/dddlc/0100/game/chess.rpy', 1567907914, 110) is defined twice, at game/chess.rpy:3 and mod_assets/chess.rpyc:3.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Missi\Desktop\Our way of talking\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Missi\Desktop\Our way of talking\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\Missi\Desktop\Our way of talking\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Missi\Desktop\Our way of talking\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Missi\Desktop\Our way of talking\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/potato/dddlc/0100/game/chess.rpy', 1567907914, 110) is defined twice, at game/chess.rpy:3 and mod_assets/chess.rpyc:3.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by jmwall24** [comment]
hmmmm why do you have .rpyc files in `mod_assets`?

**Comment by jmwall24** [comment]
send a screenshot of your `mod_assets` folder please

**Comment by Abbyninjamonkey** [comment]
how would I be able to do it, I don't have any program of sceenshowing other than recording program so any way to do it

**Comment by jmwall24** [comment]
lotta people use https://gyazo.com/en

**Comment by Abbyninjamonkey** [comment]
![image](https://user-images.githubusercontent.com/49459926/64562739-38a9c400-d313-11e9-80e0-ffe374ca3b1a.png)

**Comment by multimokia** [comment]
looks like you installed MAS in `mod_assets`. All of the `.rpyc` files should be in the `game/` folder. Not the `mod_assets/` folder.

I'd make a fresh install entirely. Grab a new copy of ddlc from [here](https://ddlc.moe/) and MAS from [here](https://monikaafterstory.com/releases.html). Then download the 0.10.0 update and extract it into the `game/` folder.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
