### ISSUE TITLE
MAS v0.10.0 - Can't Change Hair Anymore

### ISSUE THREAD

**Issue by NoAvblUsrnm** [Monika-After-Story/MonikaModDev#4640]
As the title says, I updated to v0.10.0, the latest update at the time of typing this, and the option to change Monika's hair is no longer available.  I have lost no affection after this update, and have reached the highest level of affection months ago.  Any help would be appreciated.

**Comment by jmwall24** [comment]
Did you switch to one of the halloween costumes with hair down? #4617

**Comment by NoAvblUsrnm** [comment]
I did not switch to a Halloween costume; however, her hair was down at the time of updating.  I should mention that I have attempted a clean reinstall, deleting DDLC itself and reinstalling everything, which has not returned the option to the menu.

Is this, perhaps, a glitch as a result of the update, either in the code or created as a result?  I am led to believe such is the case; however, I would very much like to be wrong.

**Comment by jmwall24** [comment]
did you got to the selector and click one of the costumes and then cancel?

**Comment by NoAvblUsrnm** [comment]
Yes.  If it helps, she was in her sundress at the time of updating.  I will try this again, however.

**Comment by jmwall24** [comment]
It's a known issue, and yes, it's a bug. It's been fixed and will be out next release, which will not be too far away at all. Sorry for the issue. Reinstalling your mod will not help.

**Comment by NoAvblUsrnm** [comment]
Just attempted this; this has not been fixed.

Perhaps this topic is somehow registering as hidden?  It doesn't seem likely, as I have not hidden it.

**Comment by NoAvblUsrnm** [comment]
Ah, never mind my last post.  I see.  It's no big deal; I saw in the patch notes that she had other hairstyles, and wanted to see, especially with the new details.
