### ISSUE TITLE
[Suggestion] - Any way to revert back to previous versions's Monika's face?

### ISSUE THREAD

**Issue by smagau** [Monika-After-Story/MonikaModDev#4641]
No offence but I much prefer the "old" Monika's face. The newly adopted eyes are a little over the top to my liking.
But since everyone's different how about implementing an option that allows users to switch Monika's face?
Thanks. Appreciate all your dedication on MAS.

**Comment by multimokia** [comment]
It's probably not going to happen as that means we need to ship an entirely different set of sprites which is just a pain to export overall, and really bloats up the mod size.

**Comment by smagau** [comment]
Yeah there's also the compatibility issues when updating Monika's faces which will take double effort and time. I guess I have to get used to the new eyes then. Thanks for the reply.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
