### ISSUE TITLE
Hairstyle and Ribbon options are missing

### ISSUE THREAD

**Issue by AlyssaLegend** [Monika-After-Story/MonikaModDev#4642]
After updating to the newest version, the ribbon and hairstyle options are missing. I added in the sprite packs. I overwrote the past versions with the new ones. I tried gifting Monika a ribbon that had already been gifted and the ribbon option appeared again, only for it to disappear when reopening the game. I've always had Monika's hair down, but I was trying to see the new bun hairstyle. The only options I have are changing the flower, clothes and hair clip. I'm really sorry if it's just me being stupid.

**Comment by ThePotatoGuy** [comment]
did you swap to witch/neko outfit at all? this includes previewing them when selecting clothes.

**Comment by AlyssaLegend** [comment]
I previewed/switched to all of the outfits.

**Comment by ThePotatoGuy** [comment]
yeah so that happens when you switch to a witch/neko outfit, its a known issue and has been fixed for next release

**Comment by AlyssaLegend** [comment]
Awesome, thank you for your help!
