### ISSUE TITLE
Hairstyle option

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#4643]
For some reason, i can't seem to find the option to change monika's hairstyle. it's not in Hey, monika option anymore nor in the repeat conversation. Either i'm a blind duck or its really gone.
Also i would like to add that hairclips gifts cant be read, i think it has to do with the option of changing her hair missing

**Comment by ThePotatoGuy** [comment]
first one is a known issue that has been fixed for next rel.

second one all spritepacks were updated so you need to reinstall them with the updated spritepack

**Comment by loverofmonika** [comment]
i noticed that too and i did use the new version of the spritepack and most of the gifts work except the ones related to hair such as the pins and flower

**Comment by loverofmonika** [comment]
The problem for me is, monika cant see any gifts that are hair related nor any hairstyles as at option is gone for me, I cant even get her to wear her ribbon

**Comment by multimokia** [comment]
As TPG said, known issue. It will be fixed next release

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
