### ISSUE TITLE
Question: New Blazerless Uniform

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4645]
First off, I love the new art style for Monika it looks so nice, almost softer somehow like she's a bit more approachable. Really, everyone who worked on it is awesome.
Anyhoo, when it says in the update that she'll randomly introduce the new outfit, does that mean she'll randomly wear it when opening up the game, also will this not work if you've already had her wear it? I just don't wanna miss out on any new interactions with her.

**Comment by satoshi-kun** [comment]
*SPOILERS* I was lucky enough to had this event as soon as I installed the new update. Basically she will tell you that she is gonna make herself more comfortable, then she will leave briefly and return without the jacket. This will also unlock the "change outfit" option, if you don't have it unlocked yet like me.

**Comment by scohn** [comment]
Well I've had the "change outfit" option for awhile now so I'm not sure if that would work for me. Also, I'm guessing she was wearing her uniform right?

**Comment by multimokia** [comment]
As of #4654, if you're not wearing uniform, she won't change into it on her own. But it's already unlocked.

**Comment by scohn** [comment]
So then if the outfit available but she's wearing something other than the uniform, does that mean I could have her change back to the uniform then have the event of her changing into the blazerless one unlock?

**Comment by multimokia** [comment]
No, it won't show the event, but the outfit itself should already be in your outfit selector.

**Comment by scohn** [comment]
Oh okay then, just cuz I'm curious does she comment anything else after returning with the outfit?

**Comment by multimokia** [comment]
Can just check the dialogue in the linked Pull Request

**Comment by scohn** [comment]
Thank you, I guess it's just the completionist in me wanting to see every option. I do still love the new outfit.

**Comment by jmwall24** [comment]
Yeah, the intro was more a way to introduce people to that fact that there is a clothes selector available that didn't have it yet, since they wouldn't even know to look for it.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
