### ISSUE TITLE
Help with sprite packs?

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4647]
I keep seeing it said that all the sprite packs were updated, but the link on #3765 just leads to an empty search for sprite packs. I want to download the updated versions, but I can't seem to find any of them. Would someone be willing to help me out here?

**Comment by satoshi-kun** [comment]
You should refer to the releases update page "https://github.com/Monika-After-Story/MonikaModDev/releases". 
At the bottom of the v0.10.0 update notes you should find the assets to download including spritepacks.zip,

**Comment by antimockingjay** [comment]
Oh! Thank you! I didn't see that because I just do auto-updates as opposed to going to the page every time I wanna update. That oughta teach me to check the page when I update, haha! Thanks again for helping!!
