### ISSUE TITLE
[Suggestion] Having Breakfast/Dinner/Lunch together with Monika

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4648]
I think it would be a good idea to be an option, where you eat your food with Monika, and she could eat her meal too. It's just a suggestion

**Comment by kkrosie123** [comment]
Consumables are in progress at the moment. This should be implemented in the future, but right now the developers of the mod are working on #3576. All consumables are waiting for those requirements to be finished. :)

**Comment by kkrosie123** [comment]
And I'll put these here to Rai99 doesn't have to -
 #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081, #4260 #4606

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
