### ISSUE TITLE
Bun reaction in "Can you change your hairstyle?" menu

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4649]
Hello! I'm using v0.10.0-unstable.2019.09.07.105. I don't know whether this is tied to #4643, but I'll put it here.

In the "Can you change your hairstyle?" menu, when the player selects bun hair, Monika doesn't give any reaction like other hairstyle. It just shows, "Which hairstyle would you like me to wear?" again. Is that intended?

Thank you very much. Have a nice day!

**Comment by Orcaramelo** [comment]
yeahhhh for other hairs too! I was wondering if it was meant to be that way too, she has no comments for some of them...

**Comment by ThePotatoGuy** [comment]
Intended. @Orcaramelo if you want custom select/hover dialogue, let us know exactly what you want. By default we don't add any in most cases unless requested with actual lines to use.

**Comment by Rai99** [comment]
It sure would be cool if somebody made some witty quips to go with the hair.

**Comment by ThePotatoGuy** [comment]
Additionally, anyone can submit those bits of dialogue for any selectable item by making a pull request with the necessary changes. Selector dialogue for spritepacks is located in the `spritepacks/released` folder.

**Comment by Rai99** [comment]
I would think they would have to pass by the creator if it's for a spritepack.

**Comment by skyloom** [comment]
Alright. Thank you for the clarification! I'll close this issue then
