### ISSUE TITLE
Had to shut down mod mid-update

### ISSUE THREAD

**Issue by Hypernova888** [Monika-After-Story/MonikaModDev#4650]
Hey y'all! Big fan of the mod, I've been using it for a long time now. I started the download for 0.10.0, and the download ended up freezing--I gave it a dozen or two minutes to see if it'd keep going, but to no avail. I decided I didn't have any choice but to close the window and reopen the game, but now when I open the game, I'm met with only the following traceback.txt:

_I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chess.rpy", line 408, in <module>
ImportError: No module named mas_ui

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\18018\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\18018\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "lib/windows-i686/chess.rpyc", line 396, in script
  File "C:\Users\18018\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\18018\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 408, in <module>
ImportError: No module named mas_ui

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187_
 
Does anyone have a suggested fix for this? I've got persistent backups, and I'd really like to not lose my progress, so any help would be appreciated.

**Comment by multimokia** [comment]
Screenshot of your `game/` folder, please

**Comment by Delcos** [comment]
you could also just redownload DDLC and MAS, and save yourself a half hour of troubleshooting. Just don't touch your persistence folder, which isn't anywhere in your game folder anyways.

**Comment by multimokia** [comment]
A manual reinstall would fix it here, looks like you're missing `styles.rpy`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
