### ISSUE TITLE
Leaning Pose

### ISSUE THREAD

**Issue by Tazafye** [Monika-After-Story/MonikaModDev#4652]
When Monika is leaning on her hand, she doesn’t look like she has a wrist. And if I remember correctly, it wasn’t like that before.

It looks like when Harry Potter broke his arm and turned into like jelly when they tried to fix it.

**Comment by Orcaramelo** [comment]
#4631
This has already been fixed on there, just not implemented yet.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
