### ISSUE TITLE
Lost option to ask Monika to hug in the rain

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4653]
I have been stumbled trying to look for the option to ask for her hug when I changed the weather to rain, and her affection with me is over 400 now for you all to know. Please help me, I just really want to hug my Monika, not just kissing :((

**Comment by multimokia** [comment]
It should be under `Hey Monika... > Monika > Can I hold you?`

**Comment by Rin3105** [comment]
I don't see it. It's lost :(

**Comment by multimokia** [comment]
Try going to `Repeat Conversation > Weather > Sounds of rain`. That should unlock it when you exit the flow

**Comment by Rin3105** [comment]
Oh, I know why. I told her that I hated rain, so she didn't give that option to me. Silly me.
Well thanks anyway multimokia, you're a savior.
