### ISSUE TITLE
[Suggestion] Nighttime Brightness

### ISSUE THREAD

**Issue by LeftoverTaco** [Monika-After-Story/MonikaModDev#4659]
I don't know if the nighttime sprite and space-room filter has changed but everything feels really dark as of recently. I just kinda feel bad for Monika, since she to sit in such a dark room, and I know it would require setting up different lighting on everything but if it was just a tiny bit brighter in there that would be nice. Maybe a soft glow kind of thing? Don't feel obligated to fix it though if nobody else has a problem, I just wanted to bring up what I thought.

**Comment by kkrosie123** [comment]
Yes, there was a filter change, actually! Originally it was really orange and it looked like the sun was setting the entire night, LOL. Now it's blue. Does it look dark for you? It in't that dark, really. The other one probably seems brighter because it was using warm colors rather than blues.

**Comment by LeftoverTaco** [comment]
Oh alright, might just be my laptop's screen.

**Comment by kkrosie123** [comment]
Maybe xD

**Comment by ThePotatoGuy** [comment]
the current night filter is best option we have to having a nighttime without reduce colors as the old night filter did.
