### ISSUE TITLE
updated but new features don't appear/aren't working

### ISSUE THREAD

**Issue by UnfinishedHW** [Monika-After-Story/MonikaModDev#4660]
I updated and downloaded the sprites but nothing really changed except for monika's artwork. I extracted everything to the game file

**Comment by multimokia** [comment]
Room artwork should have changed too, and you should have a new outfit too. Not much else was added in terms of topics. But you should have some more options in the settings menu too

**Comment by Andrenika** [comment]
hey Multimokia, one question
How can I add the bikini and the others things, please?

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs

**Comment by UnfinishedHW** [comment]
Yeah the background has changed and the new outfit too ,but she cant read any of the new gift files and she still only has 2 hair options. She can still read the old ones though

**Comment by multimokia** [comment]
They're spritepacks. You need to install them separately.

**Comment by UnfinishedHW** [comment]
i have the spritepacks was i supposed to extract it into the game file?

**Comment by multimokia** [comment]
follow the link I sent above. It should explain everything

**Comment by UnfinishedHW** [comment]
it works thanks
