### ISSUE TITLE
Ribbon is not locked for twin bun, twintails, and usagi hairstyle?

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4661]
Hello! I'm using v0.10.0-unstable.2019.09.07.105. I'm sorry for opening another issue on the similar topic just several days after the first issue since I forgot to check this. Again, I don't know whether this is tied to #4643, but I'll put it here.

When I saw those three hairstyle doesn't lock ribbon selector in "Appearance", I thought that twin bun, twintails, and usagi hairstyle had different ribbon style. These are the screenshot of those hairstyles with her iconic, usual ribbon.

![screenshot0015](https://user-images.githubusercontent.com/44340452/64690813-819c7c80-d4bb-11e9-8847-53f1b0a280e7.png)
![screenshot0016](https://user-images.githubusercontent.com/44340452/64690815-82cda980-d4bb-11e9-83d4-c8e7039a422d.png)
![screenshot0014](https://user-images.githubusercontent.com/44340452/64690817-82cda980-d4bb-11e9-931e-4ab1976e0848.png)

Is this intended?

Thank you very much. Have a nice day!

**Comment by multimokia** [comment]
Yes this is intended

**Comment by skyloom** [comment]
Alright. Thank you very much! I'll close this issue then
