### ISSUE TITLE
Monica isn't there even though I put Her file back

### ISSUE THREAD

**Issue by Beanutputter** [Monika-After-Story/MonikaModDev#4662]
So I tried doing the "I'm taking you somewhere" option because I was going to be away from my home for a month and thought it would be fitting if i "took her on a trip with me" when i come back and put her file in the character folder, she is not there when I boot up the game.

[MAS.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3603281/MAS.zip)

**Comment by multimokia** [comment]
Restore a persistent backup

**Comment by multimokia** [comment]
Also, something's up with your install. Do you have any read/write permissions in your install anywhere?

**Comment by ThePotatoGuy** [comment]
yeah theres a lot of permission errors in your log. regardless, your monika file got corrupted so you need to restore a persistent backup for sure. I'll assume you already did so since you havent responded in 10 days.
