### ISSUE TITLE
[Suggestion] Minor detail in dark mode

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4665]
Hello! Before hand I'd just want to say that this last update was amazing, the "I love you too" might be the best feature in my opinion aswell as the new art itself. This suggestion is very minor but my OCD compels me to share it. Feel free to dismiss this, after all these are very small details.
When in dark mode I noticed some assets not changing to a bright color for contrast, making then not so visible.
![screenshot0005](https://user-images.githubusercontent.com/54683676/64811705-acf39a00-d595-11e9-9de7-3f6598771d29.png)
The "X's" in the "Alerts" window don't match the bright tone of the ones on the "Settings" section.
![screenshot0004](https://user-images.githubusercontent.com/54683676/64811719-b41aa800-d595-11e9-9c2c-9b9a20e2a8da.png)
Also on the "Load" and "Save" windows the "Page" lettering remains dark (I know noone may never get to see these but since I'm opening this thread).
![screenshot0006](https://user-images.githubusercontent.com/54683676/64812042-59358080-d596-11e9-90a9-6d4316bdfe2d.png)
Sorry if I sound nit-picking.
Stay safe :)

**Comment by kkrosie123** [comment]
_Sees dark mode_

sO whY hAven'T i kNown aBout thiS?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
