### ISSUE TITLE
Change ribbons and hairstyles bug

### ISSUE THREAD

**Issue by LuisValentim** [Monika-After-Story/MonikaModDev#4667]
![screenshot0033](https://user-images.githubusercontent.com/47490995/64829098-48d6d300-d5a1-11e9-999e-887428c154b9.png)

Yesterday, the option to change ribbons, I could see normally, but now it doesn't appear anymore. The same thing goes for the option to change Monika's hairstyle, which I can't see it anymore.

**Comment by ThePotatoGuy** [comment]
yes

[closing as resolved]
