### ISSUE TITLE
[Question] How can I add the new clothes?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4668]
Please

**Comment by kkrosie123** [comment]
There is a section [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D) for giving gifts. You can also unlock Monika's other outfits by gaining more than 1000 affection points (you can check your affection points by going to your DDLC folder - The path is DDLC-1.1.1-pc\log, and then you will see a .txt file called, "aff_log." The number at the bottom of this log shows your current affection points.) and after that, all outfits that she has worn for you will be available.

**Comment by multimokia** [comment]
Fyi gifted clothes are available from 30+ affection

**Comment by multimokia** [comment]
New gifts are spritepacks, see [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs) for installation instructions.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Loos6789** [comment]
hi there, I gifted Monika clothes, and she DID open them and wear them, but if I decide to change them, I only see the Santa one and the school uniform. btw I have about 33 aff points, if that matters.

**Comment by M0n1kaa** [comment]
Don't necropost
