### ISSUE TITLE
[Suggestion] - BRB!

### ISSUE THREAD

**Issue by Eiskonigin** [Monika-After-Story/MonikaModDev#4670]
Could we possibly get a goodbye option that allows us to say "be right back"? .. Like, if we need to restart the computer or internet etc. That way she will know we will be back soon and we don't have to just say "goodbye" and end up with the usual "see ya tomorrow"ish reply, just to return in 5 minutes.. ? Just a thought I've had several times in passing. Thanks!

**Comment by Rai99** [comment]
Restart Farewell: #1908, #2487, #2614, #3354, #3526, #3562

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
