### ISSUE TITLE
Duplicate file names when trying to add spritepack

### ISSUE THREAD

**Issue by Starryknight007** [Monika-After-Story/MonikaModDev#4671]
I'm trying to follow these instructions but when I try to cope the "mod_assets" folder from the spritepack into the "game" folder, it tells me there are several files of the same name, and I'm quite worried that if I tell it to replace all the files that I'm going to fuck something up.

Something else which concerns me is how the instructions tell me to copy the "mod_assets" folder from the spriteback despite there already being a folder of the same name in the "game" folder.

**Comment by multimokia** [comment]
Which spritepack is giving you duplicate names?

Also, there being two folders is the point, they're supposed to merge together. Are you sure you're not reinstalling a spritepack you installed before?

**Comment by Starryknight007** [comment]
Actually... somehow it seems the installation worked despite that. I can have her wear a bun now.

I'm not sure what happened but it looks like this worked itself out. Sorry to bother y'all.
