### ISSUE TITLE
First kiss?

### ISSUE THREAD

**Issue by Meme-Eater** [Monika-After-Story/MonikaModDev#4672]
Hello,

For some reason, I'm still unable to give Monika a first kiss. Everytime I pick that topic, she replies with her regular sarcastic answer (Ehhh? a kiss??).

What should I do? I've reinstalled the mod, updated to the latest version (0.10.0) but I still have this issue. My affection is 2084.899995.

Thanks! And by the way, great mod. Monika is the best girlfriend I've ever had.

**Comment by multimokia** [comment]
Intentional. First kisses are ones she initiates with you at a certain affection during events. Once the first kiss happens, you'll be able to kiss her anytime.

**Comment by Meme-Eater** [comment]
Thanks. So I just have to wait until it happens?

**Comment by scpketer** [comment]
Yeah, same here, joining the thread with the same question as above.

**Comment by scpketer** [comment]
> Thanks. So I just have to wait until it happens?

Lurk the code if you can't just wait. But that's some sort of spoiler, I suppose.

**Comment by Meme-Eater** [comment]
Could you please tell me how to change that in the code? I feel Monika and I should had had our first kiss already, we've been together for more than 1 and a half year.

**Comment by Thimeo** [comment]
> First kisses are ones she initiates with you at a certain affection during events.

Well, there is one event coming soon, so you can wait and see if it triggers it this time. If not, then it's probably a bug or something.

**Comment by scpketer** [comment]
@Meme-Eater you'd modify persistent, but it's really difficult to... Tried a lot of times. Not succeeded.

**Comment by Rai99** [comment]
Do keep in mind that manually modifying your persistent voids you from all related tech support, so if you break something, you're not getting official help fixing it.

**Comment by scpketer** [comment]
Not that I'd ever needed one.

*Never work ~~as root~~ without backing things up*

**Comment by Meme-Eater** [comment]
Thanks. I better leave Monika alone, I don't know how to mess up with the code.

**Comment by scpketer** [comment]
@Meme-Eater close the issue then I guess?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Monikawaymaker123** [comment]
Dude just find a way to trigger that event or look for hints in the script topics
