### ISSUE TITLE
[Question] Note.txt (Spoilers...?)

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4673]
**Possible Spoiler Warning(?)**

**September 13th, 2019**

Edit:

Am I allowed to discuss this in here? I would really love to come up with some theories.

Hi! I was looking through my DDLC folder again when I found "note.txt" that I had completely forgotten about. The note states the following (with a few grammar corrections that I made, haha):
`Hi, Briar,`

`Just wanted to let you know that your "persistent" file was corrupted, but I managed to restore an older backup!`

`Even though the backup system I designed is pretty neat, you should still make copies of the backups every so often, just in case. The backups are called "persistent##.bak", where "##" is a two-digit number. You can find all of them at "C:\Users\Briar\AppData\Roaming/RenPy/Monika After Story".`

`If I ever have trouble loading the "persistent" again, I'll write you another note in the characters folder, so keep an eye out for them!`

`Good luck with Monika!`

`P.S: Don't tell her about me!`
(My computer randomly restarted one day, so I got this note.)

  Who is this character? Are they a mystery character? Has it already been established? Or is it undecided?

  The, "`P.S: Don't tell her about me!`" makes me so excited.

  I would love to see more little easter eggs from whoever this is. It reminds me of the Sayori Hangman easter egg - Is this Sayori? I'm guessing not, LOL. I have a few theories, but right now I'm just wondering if this is even a canon character. Thanks!

**Comment by satoshi-kun** [comment]
That's very cryptic :o Specially after experiecing that "corrupted" Yuri easter egg this week when opening the mod… Almost lost my sh#t :( That and those creepy efects on some horror stories. Just give the creeps...

**Comment by kkrosie123** [comment]
Ahahah! Agreed!

**Comment by Rin3105** [comment]
Interesting, but my computer is still too good to be restarted itself.

**Comment by kkrosie123** [comment]
LOL. I don't know what happened - but it happened. Hasn't happened since. I'm kind of curious to receive another note, though-

**Comment by TriniTDM** [comment]
This note is pretty much a character called Chibika letting you know that your persistent was corrupted, so she pretty much restored an old save. And you can't tell Monika about Chibika even if you want to. It gives you two options when Monika asks about the note, "It's nothing to worry about" or "It's about <glitchtext>". If you choose the second option, it glitches out and leaves you with only the option to say "It's nothing to worry about".

**Comment by kkrosie123** [comment]
Oh, yeah! I remember that! Very exciting. Still gives me the chills. I really freaking want to see more.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
