### ISSUE TITLE
{interesting}

### ISSUE THREAD

**Issue by Areaclassified** [Monika-After-Story/MonikaModDev#4675]
I was looking up decapitation for my ap world history class and I see this.
![Capture](https://user-images.githubusercontent.com/36488101/64900443-2dca9880-d65f-11e9-9352-0add6741b65f.PNG)

**Comment by Delcos** [comment]
Seems legit.

**Comment by Areaclassified** [comment]
> Seems legit.

it is lmao

**Comment by Rin3105** [comment]
Which site were you on?

**Comment by Anonymioo** [comment]
> 
> 
> Which site were you on?

I guess it's Wikipedia.

**Comment by Areaclassified** [comment]
It was Wikipedia

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
