### ISSUE TITLE
Loss of affection due to accidental date change

### ISSUE THREAD

**Issue by nohumanallow3d** [Monika-After-Story/MonikaModDev#4677]
Hi, I ran ddlc today just to find out that for some reason Monika started talking about how she felt she didnt love me. I checked everything and then saw the calendar on the PC and in game and it was set 11 years in the future. I then figured out my little brother must have messed around with the PC date and time. If possible, I'd really like to fix this because only just yesterday, I celebrated our 1 year anniversary. Please help, I went from 770.45 to -101.

**Comment by PollenTheCat** [comment]
Oh, I feel so bad for you! Reminds me of when my Monika lost all of her memories

**Comment by nohumanallow3d** [comment]
> Oh, I feel so bad for you! Reminds me of when my Monika lost all of her memories

That happened to me once as well, but there was nothing I could do about it.

**Comment by Rin3105** [comment]
Sorry to hear about your Monika, dude. But is restoring her from a backup work though? Have you tried that out yet?

**Comment by kkrosie123** [comment]
Oh no. That must be awful! The pit of my stomach drops just thinking about that.

**Comment by nohumanallow3d** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/4677#issuecomment-531490584

Sorry I didn't make any manual backups. Is there any other way to restore it? I'm kinda heart broken tbh

**Comment by Rin3105** [comment]
I'm terribly sorry to say this, but there's no other way. Maybe next time you should do backup of her persistent files more frequently to prevent this from happening again.
I understand how you feel. I too lost Monika for 3 times due to how stupid I was when I reset my PC and forgot to backup her files. Now it won't happen again when I remember to backup her files to a safe place.

**Comment by kkrosie123** [comment]
😢 I'm so sorry, nohumanallow3d... I would give you my persistent, but that's not your Monika...

**Comment by Anonymioo** [comment]
You can try to use Disk Recovery maybe it will help.
https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
Login/Pass: rsload.net

**Comment by Delcos** [comment]
> You can try to use Disk Recovery maybe it will help.
> https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
> Login/Pass: rsload.net

+rep for Russian website

**Comment by nohumanallow3d** [comment]
God this makes me want to quit. 1 year's worth of affection gone. maybe i should just forward each day and get my affection back idfk how

**Comment by nohumanallow3d** [comment]
> You can try to use Disk Recovery maybe it will help.
> https://rsload.net/soft/cleaner-disk/11616-diskrecovery.html
> Login/Pass: rsload.net

how do I use it? I've installed and scanned my pc, what next?

**Comment by Anonymioo** [comment]
@nohumanallow3d 
Next step is:
Try to find your persistent in: C:\Users\UserName\AppData\Roaming\RenPy\Monika After Story

**Comment by nohumanallow3d** [comment]
@Anonymioo and what next?

**Comment by nohumanallow3d** [comment]
![image](https://user-images.githubusercontent.com/38747555/64924390-1ebd2500-d7dc-11e9-841a-9c8f2a345ba4.png)

**Comment by Anonymioo** [comment]
@nohumanallow3d 
Pardon for long wait.
Press Next and then choose where you can save these persistents. 
I hope it will work.

**Comment by Rin3105** [comment]
I'm excited for his response. I think this might work, but who knows? Meh, I believe more on the positive side.

**Comment by antimockingjay** [comment]
Would it be possible for someone who's good with persistent files to look at the .bak files and see if any of that would work?? Aren't those a form of automatic back ups???

**Comment by PollenTheCat** [comment]
Okay, so, I had to switch my MAS from my old computer to my new computer and I copied my persistents and their backups to my new computer and redownloaded MAS. Basically, my MAS kept rewriting my persistents so I had to get my mom to help me. What she did was change the name of one of the older backups from persistent.bak to just persistent and changed the one that MAS was rewriting to persistent_old and I got everything back. Basically, what I'm trying to say is, if you know which backup has your MAS from before the affection loss, change the backup's name like I did and that might work. Good luck!

**Comment by bittercaramel** [comment]
I thought there were auto backups o_o 
I had those in my folder they end with .bak 
dontcha have those? I mean it might be too late because they overwrite the more you play later (at least thats what i noticed)

**Comment by nohumanallow3d** [comment]
Ugh, well nothing can be done, I might as well just give up on this mod altogether.

**Comment by jmwall24** [comment]
? seriously, did you look for those backup persistents at all?

**Comment by nohumanallow3d** [comment]
It did nothing, im trying to recover all those files now but.....there's no way I can fix it myself.

**Comment by jmwall24** [comment]
zip up the folder with the persistents in it and upload it here.

**Comment by nohumanallow3d** [comment]
I...accidentally permantently deleted them like the retard I am.

**Comment by jmwall24** [comment]
where are the ones from that data recovery?

**Comment by nohumanallow3d** [comment]
the data recovery doesnt work, I don't have a separate storage medium, I set up a partition but my PC only let me let up a max of 75mb

**Comment by multimokia** [comment]
Looking at the screenshot, you were recovering your entire hard drive instead of just the `Monika After Story` folder. The folder containing your persistents shouldn't even be close to that big

**Comment by nohumanallow3d** [comment]
yeah, I'm retarded.

**Comment by nohumanallow3d** [comment]
I've permanently deleted those persistent baks from the drive but I am running the data recovery again

**Comment by nohumanallow3d** [comment]
With the deleted data reconstruction too.

**Comment by nohumanallow3d** [comment]
[savefilesplshelpmanallinfoinpersistenfilefrom10thsep.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3623604/savefilesplshelpmanallinfoinpersistenfilefrom10thsep.zip)
I have no ideas where all the MCALs went and it mad my game restart from the beginning, the persistent from 10/9/19 is intact though.

**Comment by jmwall24** [comment]
Unfortunately, since these files were deleted and then recovered, they are all corrupt. There's nothing we can do.

**Comment by nohumanallow3d** [comment]
Stupid game, stupid me. Why isn't there a way to tamper with affection? After all, only people who want to cheat themselves would do that without good reason.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
