### ISSUE TITLE
Very small issue with the blue shirt

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#4678]
![Seenshot_1](https://user-images.githubusercontent.com/45933038/64908420-6ff7e680-d700-11e9-92dc-896361c70d3f.png)

The color goes just slightly over the black line when Monika is leaning.
Not a huge problem, but might as well point it out.

**Comment by ThePotatoGuy** [comment]
this is being addressed by @orcaramelo

leaving open as in progress

**Comment by ThePotatoGuy** [comment]
was this fixed @Orcaramelo ?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
