### ISSUE TITLE
[Suggestion] Let Monika have her own pet in the room

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4679]
Like the title says, I want my Mon-Ika to have her own pet in the room during the time she's stuck in her world. I have two cats at home and would love her to experience the cuteness of those cute little hairballs. I know this might be hard due to constant art animations and bigger files, and it is just a suggestion, but yeah, I really wish her to have at least a pet to make her feel happy all the time, even when I'm not around. :3

**Comment by FrikiHD** [comment]
That's a really good idea!

**Comment by Rai99** [comment]
#1888, #3115

> I think this is better served as a submod. Adding it to official release adds a layer of complexity that I don't think the dev team is willing to maintain.

**Comment by Rin3105** [comment]
Alright, sorry about that. I will close this issue now.
