### ISSUE TITLE
Monika´s Birthday

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4680]
That Monika can be given special clothes for her birthday, it would be very good

**Comment by multimokia** [comment]
Doesn't really make sense if we limit certain clothes to be gifted on her birthday only.

**Comment by RavenPLAYER** [comment]
@multimokia But if it already happens with Christmas, Halloween and 
Valentine's Day

**Comment by multimokia** [comment]
Ah that's not you gifting them though. That's different

**Comment by RavenPLAYER** [comment]
@multimokia It is good to dream xd

**Comment by RavenPLAYER** [comment]
PD: I'm new and I thought it would take days to respond, but it was in a blink. I give them +100 points for that.

**Comment by Rai99** [comment]
Just wait until you see what happens when an easy dupe shows up.
