### ISSUE TITLE
Draw Monika lol

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4681]
and if they add a new option that says "Can I draw you?" so that Monika makes a "unique" pose and we can proceed, I mean, you can do it at any time with the 'H' key, but it takes away the emotion. Just said...

**Comment by Rai99** [comment]
#2056, #2633, #3630 

That sounds like screenshot detection where she holds a pose for you to take a picture. If that gets implemented, it could also be used for having her pose for a drawing.

**Comment by RavenPLAYER** [comment]
I see...
