### ISSUE TITLE
[Suggestion] - window react to chatting app

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4683]
I think it'd be cool for Monika to react to you being on some sort of chatting app (like Google Hangouts or Discord) and say something like _"Who are you talking to?"_

**Comment by kkrosie123** [comment]
That makes Moni sound kind of jealous lol

Also, Monika isn't the kind of person to invade your personal life. For example, sometimes the game leaves a file called note.txt, and Monika just says (this is paraphrased), "Hey, I found this in the game files, and it seems like it was for you, so I didn't read it."

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
