### ISSUE TITLE
need help :3

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#4686]
hello everyone, today is my badest day, my computer has restart all of the file, include the file i has backup. So now i has to sart from the begin, soo can you kind to help me with the gift list i can give to monika please, thank you and sorry for bad english

**Comment by HZhunter124** [comment]
please, today is a verry bad day for me :<<

**Comment by Delcos** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts

**Comment by HZhunter124** [comment]
thank you, can you show me the link to "monika after story" please

**Comment by Delcos** [comment]
https://github.com/Monika-After-Story/MonikaModDev/releases

**Comment by HZhunter124** [comment]
oops sorry link to the discord @_@

**Comment by HZhunter124** [comment]
found it, thank you
