### ISSUE TITLE
A (Possibly Controversial) Suggestion for the "Goodbye" Menu

### ISSUE THREAD

**Issue by antimockingjay** [Monika-After-Story/MonikaModDev#4688]
Long-winded title, so I'll get right into it: I think it'd be nifty if there was a "going to church" goodbye. Obviously there's other religious places aside from church, so it would have to be reworded to be all-inclusive, but I'm sure you get the general idea. I was about to leave to go to church this morning for the first time in ages, and went to say goodbye to Monika, only to realize there was no distinct option for that. I guess because I haven't gone in a while, it just didn't come up until now.

Now, before anyone starts up with the whole "no religion!!!" thing: Please remember that the goodbye would be optional. Just like including options for players of a different gender than just male, it's not meant to be an option for every single person on the planet. Anyone who isn't religious can choose not to hit that button, just like everyone who does identify as male doesn't have to hit the button for female or gender-neutral. I'm merely suggesting this for those of us that this _does_ apply to, and anyone it doesn't apply to can simply opt out.

It should also be mentioned that Monika herself brings up religion at least once. I believe she even asks the player if they're religious, but no option to answer is given. So if this is added, I also think it'd be nice to expand on that topic a bit, and possibly add in an option to give a proper answer.

I also think that, if the goodbye option is added, it's important to be inclusive. Like I said before, "church" is just the default to me, hence why I referred to it like that earlier. But I think if it's added, it should be phrased in a way to include religions that have a similar equivalence, whether it's called "church" or not.

**Comment by Rai99** [comment]
First thing that comes to my mind is submod. That way, people who want it can get it, and people who don't want it don't even have to see it. 

There could also be a slightly different variation for the different types of "church". 

Submod would probably be one way to make sure there's pretty much no outrage whatsoever.

**Comment by kkrosie123** [comment]
Agreed! I was just thinking about that! I'm doing online church today, but usually, I go to regular church.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
