### ISSUE TITLE
Clothes- It's getting warmer yall

### ISSUE THREAD

**Issue by Orcaramelo** [Monika-After-Story/MonikaModDev#4689]
#3174
--no longer working on this--
ho boy orca is back at it again
but this time i bring you...
![ooo look](https://user-images.githubusercontent.com/47725743/64926149-79508400-d7d0-11e9-9fa5-587add71c783.png)
something lighter for spring and also for the summer that is coming soon!!

this was 100% inspired by a dress i got from nizikano, tho i decided to change some aspects, as well as make it sleeveless (the little bow on her hair is from another project :> but no spoilers here ehehe)
opinions on it?
![image](https://user-images.githubusercontent.com/47725743/64926175-cf252c00-d7d0-11e9-899a-bb0c1a9d4207.png)

**Comment by multimokia** [comment]
*But it's getting colder here*

**Comment by Orcaramelo** [comment]
> _But it's getting colder here_

_silence mortal_

**Comment by multimokia** [comment]
> silence mortal

No.
`>:(`

**Comment by Orcaramelo** [comment]
> No.
> `>:(`

**_banned_**

**Comment by Velius94** [comment]
no u

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/64926235-59699200-d7c9-11e9-86f1-0fbb18271dbe.png)

**Comment by Orcaramelo** [comment]
![image](https://user-images.githubusercontent.com/47725743/64926252-d993f580-d7d1-11e9-9fbe-19f6236493cf.png)

**Comment by Delcos** [comment]
what a wonderful world

**Comment by multimokia** [comment]
Wow rude

**Comment by Delcos** [comment]
![c9d](https://user-images.githubusercontent.com/28798918/64926302-cd4b7080-d7b0-11e9-90c9-783249b0ef3a.png)

**Comment by Professor-JMO** [comment]
Excellent quality 👌

**Comment by GHCactus** [comment]
omg she's so cuuutee!! I'm so jealous of your art talentsss!

**Comment by Rai99** [comment]
What are the straps made out of? It almost looks like magic. 

Regardless of the weather, Monika just keeps getting hotter, so this should be nice for her.

**Comment by Orcaramelo** [comment]
I tried to reproduce lace texture but i dunno if I pulled it off lol

And thank you so much cactus!!

**Comment by Rai99** [comment]
When I first looked at it, I thought it was a bunch of magic sparkles, not that there would be anything wrong with that.

**Comment by Orcaramelo** [comment]
Lol its a textured brush
Does it look bad tho

**Comment by Rai99** [comment]
Are the straps supposed to join at a single point at the back? That's kinda what it looks like to me. Maybe make them a bit more vertical if not?

Overall, I think it turned out really well, but I'm not sure if the straps were what you were going for. 

Also, is that a mini ribbon in the hair?

**Comment by Orcaramelo** [comment]
> Are the straps supposed to join at a single point at the back? That's kinda what it looks like to me. Maybe make them a bit more vertical if not?
> 
> Overall, I think it turned out really well, but I'm not sure if the straps were what you were going for.
> 
> Also, is that a mini ribbon in the hair?

Will move them then! And yes it is, its from another project (a secret??? Maybe...)

**Comment by taurielxaela** [comment]
Looks so cuuute! I'd love to see Moni in this~

**Comment by Orcaramelo** [comment]
Btw this looks so neon on my phone lol
I swear pc makes it look better

**Comment by Rin3105** [comment]
I want this to be on official soon, the outfit looks fit and nice on Monika :)

**Comment by antimockingjay** [comment]
To me, it looks really similar to lace, and it looks almost like they cross over in the back as opposed to connecting at one specific point.

**Comment by antimockingjay** [comment]
Good job on the artwork!
