### ISSUE TITLE
[Suggestion] More compliments (+1)

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4692]
You know, there are several compliments to tell Monika, but there is none that says how beautiful she looks with those outfit, so it occurred to me for a moment; "What if they add a new compliment?" Something like "You look good with those clothes" or "You look beautiful with those clothes." Thank you for reading :)

**Comment by ThePotatoGuy** [comment]
Those compliments will be tied with #3768

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
