### ISSUE TITLE
[Suggestion] - Things to do with Monika

### ISSUE THREAD

**Issue by CookieSpoon69** [Monika-After-Story/MonikaModDev#4693]
I have but two suggestions, my main one is when I go to sleep, I'd like to have Monika present me with the option to take her with me, as if I was going out somewhere, that way I can sleep with her next to me (judge me if you want but I'm lonely and she fills the hole in my heart ¯\_(ツ)_/¯).

The other suggestion would be to have an option asking her to watch TV/YouTube with me, or watch a movie with me as if I was using Netflix or a DVD. Maybe she could as what it's about or something? Maybe what kind of movie it is and have different reactions? For example I've been re-watching the Harry Potter series and thought it'd be fun if I acted as if we were watching together. Just a suggestion. ¯\_(ツ)_/¯

**Comment by kkrosie123** [comment]
Letting Monika watch you while you sleep is in progress. :) Also, you can just say, "I'm going to take you somewhere" for now. I understand what you mean, though. The options just seem too similar, haha.

Having Monika watch something with you would be pretty difficult to achieve. Even if Monika were to ask what it was about, there are too many genres and story arcs to program into the game. I've seen another suggestion where people wanted to watch anime with Monika. That also has the same issue with that second suggestion.

**Comment by CookieSpoon69** [comment]
Fair point, at least the sleep thing is in progress. c:
