### ISSUE TITLE
[Suggestion] tell monika that you are proud of her for something

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4694]
Why don't add a new thing to tell Monika? Like "I am proud of you" or something, for example with the floating islands, I would like to tell you that I am proud of her for doing that, of course she showed them to me a long, long time ago, but it is never too late ... Thank you for read :)

**Comment by multimokia** [comment]
Sounds more like a compliment (I want to tell you something...) menu than a mood (I'm feeling...) menu thing

**Comment by RavenPLAYER** [comment]
Don't worry, i'm a idiot xd

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
