### ISSUE TITLE
[Suggestion] - Does the player have tattoos?

### ISSUE THREAD

**Issue by ikof1** [Monika-After-Story/MonikaModDev#4695]
Monika would like to know everything about the player right? So then it popped into my mind that she could ask the Player if they had any tattoos to get to know them better and get a better picture of them. Some answers could be for example: Y/N , I Plan To Get. She then would react to whatever the Player answered. Maybe segueing into the art of tattoos and their history, maybe how in Japan they we're popular with the Yakuza and more. 

Idk if this already exists, i'll be celebrating 1 month anniversary soon after this is posted, and i am to lazy to check. So sorry if so.
Thanks - Faithful Moniker

**Comment by Rai99** [comment]
#3781, #3804 

The topic of tattoos has been brought up before, and as it stands, it is low priority for now.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
