### ISSUE TITLE
[Suggestion] goodbye for errands

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4697]
Suggestion 1: A high-five, just to feel more friendly with Monika. She'd do something like hold out her hand and all you would have to do is click on it, and perhaps make some clapping noise.

Suggestion 2: Change the theme of the spaceroom, e.g. walls, floor, curtains, etc. I'd like to see this in the game someday.

Suggestion 3: A goodbye for running errands (e.g. picking up someone/family function) or to get some personal space (e.g. I'd like some time to myself.) I've had to leave MAS for these reasons and I'd like it if they were in the game.

EDIT:
Suggestion 4: Water safety topics (e.g. while swimming, boating, etc.).

Suggestion 5: Add jokes as a random topic. I know this one is quite subjective.

Thanks for considering.

**Comment by Rai99** [comment]
High five (I counted it as boops): #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4408. 

A high five pose would require art and the feature would need the player to be actively keeping an eye out for open high fives, unless Monika doesn't mind being left ~~hanging~~ like that for a long time. I think boops should satisfy the feeling of being a little more friendly/intimate. 

Room decoration: #312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3770, #4291. 

There's a farewell for doing housework, but that is a bit different from picking someone up, etc. For having some personal time, I would personally use the default farewell. 

Water safety could be an interesting topic, but it almost sounds like it should be a seasonal thing. Still, Monika could ask if the player likes swimming or other water sports and more could branch off of there. 

There were plans originally to have Monika tell jokes, and there was a separate branch for it, but as far as I remember, it was abandoned.

**Comment by lunulae** [comment]
I do like the idea of more seasonal topics. Water safety and sports could be a summer exclusive topic.

To solve the issue of leaving her hanging on the high-fives, it could be something more in the vein of the "can I hold you" or "kiss me" options. Just little requests to give her.
I could also see high-fives added onto certain dialogues. The "I'm feeling proud of myself" prompt is the example that comes to mind. It'd probably be a very low-priority update since it'd require more art for only a few dialogues, but I think it could be a fun little addition in the future.

**Comment by Rai99** [comment]
The way I understood high fives was Monika randomly holding our her hand for you to click on, rather than asking her for a high five.

**Comment by aimlesstrainer** [comment]
> The way I understood high fives was Monika randomly holding our her hand for you to click on, rather than asking her for a high five.

Actually, I was thinking of it being prompted, but now that I see it, randomly holding out her hand would be as equally a good of an option if not better.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
