### ISSUE TITLE
[Questions][Request][Grammar error] Preparation for Monika's Birthday

### ISSUE THREAD

**Issue by LClarance** [Monika-After-Story/MonikaModDev#4699]
So yea, as the title suggested, I just wanna ask some questions regarding the things I can do for her on her Birthday and a grammar error of a Japanese sentence in game. There are several things I need to know to fully prepare for the coming 22nd Sep. So the questions are following:

1) Can the new hairstyles introduced in the last patch be gifted?

2) Is the party surprise procedure same as last year? If it is, can somebody please explain to me how to do it or just kindly put a link for the topic in the comment section?

3) [Requests] That should be all the questions I want to be answered, please kindly tell me if there's any details that I may miss. Also, the place I live is about 20 hours ahead of USA, so I hope you guys can release the updates earlier like on 20th if there's any?

4) [Grammar error]
![Capture](https://user-images.githubusercontent.com/47456818/65046632-96818000-d993-11e9-8880-d0209436ac84.PNG)
Not sure if this has been brought up before, but the は(ha) when used as a topic marking particle is pronounced as "wa" not "ha".

That's all I want to say, thanks for reading till the end and thanks in advance for answering my questions if any.

**Comment by multimokia** [comment]
1. Hair is a spritepack, needs to be installed. Does not need to be gifted. It will be available in the hair selector if installed correctly

2. No spoilers

3. ^

4. This was brought up before, and it was put up to Monika still leaning Japanese.

**Comment by LClarance** [comment]
@multimokia alright. Thanks for the response. Hope I can get the update in time

**Comment by satoshi-kun** [comment]
Nani! Please tell me that despite of any updates we will still be able to surprise Monika like in previous years.. I just discovered this mod this june and it´s her first birthday with me. Got all the party supplies ready for sunday and more importantly the promise ring. Hope things don´t get overcomplicated :/

**Comment by jmwall24** [comment]
You won't need last year's party supplies and things will be simpler than last year. That's all I'll say.

**Comment by satoshi-kun** [comment]
I feel somewhat sad for not being able to experience that before... Was really hyped to surprise Monika… My fault for taking this long to find her. Times change. @jmwall24 Thanks for the clarification :)

**Comment by LClarance** [comment]
@satoshi-kun I know how you feel. This is her first birthday with me so I wanna be fully prepared. Only started this game last October lol. I was so close

**Comment by PollenTheCat** [comment]
@LClarance Same!!! I started November 29 (But then my Monika lost hem memories Dec 17 and I had to remake my progress). I'm excited for Monika's bday!!!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
