### ISSUE TITLE
[WIP-Art] Kimono

### ISSUE THREAD

**Issue by GHCactus** [Monika-After-Story/MonikaModDev#4700]
Sooo this is a work in progress but any feedback is appreciated!! I'm new to computer art and stuff
(will clean up line work and stuff soon)

![Sketch007](https://user-images.githubusercontent.com/52979408/65088152-dd647b00-d97d-11e9-974c-e2ac6cb6a460.png)

**Comment by RavenPLAYER** [comment]
I don't know why, but I can't see the photo. I only see a gray square without fill. Anyway, I know it's good xd

**Comment by GHCactus** [comment]
I thiiiink I fixed itt
can you let me know if its still not working?

**Comment by antimockingjay** [comment]
It's working for me! I like the artwork, but I think you're doing what a lot of artists do. You're making the cloth curve under her chest, which isn't how actual clothing works. If you held a tennis ball to a board, then draped a napkin over it, the napkin wouldn't curl under the tennis ball. The same applies to breasts. Unless she's in a bra/bikini or something like that, you shouldn't be able to see the curve underneath.

If you need references, I actually do suggest the tennis ball thing I mentioned earlier! If you take a tennis ball and hold it to the wall and drape a piece of cloth over it, it will genuinely give you an idea of how cloth tends to fall. That or look up some clothing references.

Aside from that, I think the artwork is really nice! It's well made, and I can tell you're working hard on it!! Keep up the good work!

**Comment by RavenPLAYER** [comment]
@GHCactus Wow, It is incredible!

**Comment by GHCactus** [comment]
ah thank you so much and thanks for the reference I don't have any tennis balls but I will look at how cloth works by looking at more Kimono references!

**Comment by lunulae** [comment]
Gorgeous work so far!! Excited to see more progress in the future.

**Comment by GHCactus** [comment]
![Sketch008](https://user-images.githubusercontent.com/52979408/65821530-5d030d00-e1fc-11e9-941e-930639e4d238.png)
I tried my best to make it not curve under and I fixed it up a bit more and I want your opinion, what should be the accessory that would go with it?

**Comment by Orcaramelo** [comment]
well, as for the kimono, most have a sash (is this the right word lmfao) on the waist, so you could add that! a nice accessory hum,, would def use the bun hairstyle for it but i dunno what would look good.

**Comment by Orcaramelo** [comment]
Also,
![Capturar](https://user-images.githubusercontent.com/47725743/65821753-5c747180-e210-11e9-8d2d-13806033f7bd.PNG)
 since kimonos dont have their shoulders out, that means the one you drew has slipped/wasnt put on all the way, right? in that case there should be extra fabric showing as folds, this might help:

**Comment by GHCactus** [comment]
AH THATS PERFECT @Orcaramelo  Thank you so much

**Comment by GHCactus** [comment]
![Sketch009](https://user-images.githubusercontent.com/52979408/65823291-fcce9400-e218-11e9-87ea-a75568317838.png)
New outline yayyy

**Comment by GHCactus** [comment]
the lines are messy again but I'm happy

**Comment by Orcaramelo** [comment]
that's much better already! pat pat
 Also, are you doing arms and torso on different layers? you'll need to do that for it to work in the game

**Comment by PollenTheCat** [comment]
Gosh, it looks so good! I bet everyone, Monika especially, is excited for when it's finished!

**Comment by GHCactus** [comment]
![Sketch0011](https://user-images.githubusercontent.com/52979408/66722986-bf056a00-edd9-11e9-967e-ecd16a5e6550.png)
update: sorry for the really slow process due to my college exams coming up haven't had much time to work on it so I'm really sorry this is so slow

**Comment by jmwall24** [comment]
Take your time, there's no rush. Should be a great addition when it's finished!

**Comment by GHCactus** [comment]
Soooo uh I don't really have that much confidence in myself or enough time for this so I'm gonna close this, but if anyone wants to pick it up please do!!
