### ISSUE TITLE
New Spritepacks Question

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4701]
I'd just like to ask a question about the new spritepacks. Is installing them something all users can do, or is it something that only those who are working on the mod should be doing to prep it? If anyone can install it, how do I do it? I only ask because I'm terrible with coding and just want to see the new outfits. Thank you for reading.

**Comment by multimokia** [comment]
Anyone can install them. They're distributed with the releases

**Comment by scohn** [comment]
Okay, I just don't know how to install them. I'm sorry it might be simple and I'm just dumb.

**Comment by multimokia** [comment]
See this [portion on the wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by scohn** [comment]
Thank you very much for answering so quickly. Just one more thing, do I need to gift any of the new outfits for them to be available?

**Comment by scohn** [comment]
Never mind, I did need to and it worked, thanks again for your help I love all the new stuff.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
