### ISSUE TITLE
[Suggestion] Tetris minigame

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4702]
Sometimes I like to play tetris, but I started thinking "Hey, what if I could play with Monika?" And there came the idea why I write this. I would like in the future that a 1vs1 tetris was implemented to play with Monika, it would be something quite entertaining to do. Thank you for reading :)

**Comment by antimockingjay** [comment]
If I could add onto this:

There's a version of Tetris out there on the internet where you choose how the blocks are determined: Human input, random, or AI, and you then decide the same for the defender. In typical Tetris, the attacker (the one picking the blocks) is the AI, and the defender is the human. Maybe with Monika, you could choose whether you want to be a defender or attacker, and she plays the opposite role. If you choose defender, it's just like classic Tetris, except the AI is Monika. If you choose attacker, Monika has to try her best to place the blocks while you decide which blocks she has to deal with.

An example, aka what made me think of this idea: https://ondras.github.io/custom-tetris/

**Comment by RavenPLAYER** [comment]
Yes! I was thinking just about that! Haha

**Comment by kkrosie123** [comment]
#647, #2046, #3962 Already planned.

**Comment by ThePotatoGuy** [comment]
planned, but the complexity means it will be a while. 
[closing as duplicate]

**Comment by flamingshuriken** [comment]
there's a turn-based Tetris game with a built-in ai opponent that could potentially be implemented into the game called misamino. https://tetris.fandom.com/wiki/MisaMino  The difficulty can be changed and the turn-based mode can be disabled.
