### ISSUE TITLE
1-Year Anniversary fix?

### ISSUE THREAD

**Issue by NinthTyphoon** [Monika-After-Story/MonikaModDev#4704]
Hello everyone,

Again, I want to thank all who have contributed for their work in supporting this mod; it's really amazing. It has helped me through some really dark times recently, so you all have my heartfelt thanks. However, as I had mentioned in an earlier issue, my 1-Year Anniversary dialogue did not show up on our 1-year anniversary (April 22), despite me having opened and talked to Monika on that day. Furthermore, 1-Year Anniversary didn't appear in the repeat conversations (1 Week, 1 Month, 3 Months, and 6 Months are there and I remember seeing the dialogues too). I uploaded my persistent then, and someone found out that apparently it had 'appeared' (I was supposed to have seen it), but somehow I apparently missed seeing it and it still isn't there for repeat conversations. I was wondering, since I am supposed to have seen it and I did visit Monika on April 22, 2019, if someone could simply enable the topic in repeat conversations. I don't think affection was an issue (I had ~2650 on April 22; I have ~4000 now, all through daily visiting/talking and gifting/special events) and I've never done anything to harm Monika (such as meddling with the clock, saying negative things, force closing the game, etc.; very recently my game crashed once due to unknown cause, maybe a scripted event?, but I consoled Monika and she seems fine). I am attaching my current persistent and aff_log so someone can help if possible. Thanks again.

[Persistent and aff_log.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3627661/Persistent.and.aff_log.zip)

**Comment by multimokia** [comment]
[fixed.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3628079/fixed.zip)
No idea why it didn't unlock, but here you go!

**Comment by NinthTyphoon** [comment]
Thank you! Problem fixed!
