### ISSUE TITLE
[Suggestion] New topic

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4706]
I came up with an idea for a romantic date with Monika (Of course it's not an action, but a conversation). It would be a "Tunnel of love", how it already tells us about wanting to go in a carriage with us, sledding and stuff, a tunnel of love would be something quite nice to do with Monika ... (Ok, maybe something else happens there in xdxd)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
