### ISSUE TITLE
[Potential Spoiler I don't know] Help with a note

### ISSUE THREAD

**Issue by bringerofstorms** [Monika-After-Story/MonikaModDev#4707]
Leaving this intentionally vague just in case, but can it be any kind of file?

**Comment by Velius94** [comment]
I think extensionless is the best bet.

**Comment by bringerofstorms** [comment]
Thanks. And it's okay to put it in the place right now?

**Comment by Delcos** [comment]
just rename the current file to the thing and leave it alone there
next time you start mas it will be taken.

**Comment by bringerofstorms** [comment]
Will do. Appreciate the help!
