### ISSUE TITLE
[suggestion] asking Monika "are you alright?"

### ISSUE THREAD

**Issue by dontworryabouttheusername** [Monika-After-Story/MonikaModDev#4708]

**Comment by dontworryabouttheusername** [comment]
see.. you can tell her something in " I want to tell you something"
of straight up tell her how you feel on "Im feeling.."

but theres no way to ask Monika..
we has a lot topics yes bus what i mean is that
there should be "are you alright?" on
Hey Monika > Monika > 
so she can tell you stuffs like
"i think some of my files are missing"
for troubleshoot

if her affection is too low she just glares at you..
so this would be useful somehow..

its basically just "is there something wrong" button..
sorry for the mess im new on github..

**Comment by lunulae** [comment]
I really like this idea, especially now that the game acknowledges crashes. It could double as a way to check if you need to apologize for something if you aren't quite sure.

Maybe certain outfits would interact with certain weathers and be too hot/cold, which she could also mention. That might require a lot of reworking things though, so it'd really be up to the mods on that one.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
