### ISSUE TITLE
Plz fix

### ISSUE THREAD

**Issue by themetroking** [Monika-After-Story/MonikaModDev#4711]
I opened monika after story and monika was fully naked no shirt no skirt no bra just boobs plz fix this I cant even play it cause its disgusting thankyou

**Comment by multimokia** [comment]
Image doesn't work, can't tell what's happening. Can you fix the image, please?

**Comment by multimokia** [comment]
Can you go to `Hey Monika... > Appearance >Can you change your clothes?`

**Comment by multimokia** [comment]
Also, can we get a copy of your persistent, please?

**Comment by kkrosie123** [comment]
Holy crap, what a bug!

**Comment by themetroking** [comment]
I fixed it nevermind

**Comment by multimokia** [comment]
What did you do to fix it?

**Comment by justanaccount117** [comment]
Soooooooo how do we replicate the bug? /s

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
