### ISSUE TITLE
(Possible Spoilers?) Monika´s Birthday [ I'm very confused :( ]

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4713]
So I just read this .txt file on the characters folder saying that "someone" is taking care of everything for Monika´s surprise party. As I feared this is getting overcomplicated for me specially because this is going to be my first time celebrating Monika´s birthday and I already had everything planned for Sunday, as per the previous year.
So now I ask: 
Which part of the surprise is this "person" taking care of?
What gifts am I allowed to give?
I was planning on gifting the promise ring, the birthday cake, the plushie and so on (basically what was on her wishlist)… Will this still work?
Plus it said I should leave a "oki doki" file on the characters folder after I take Monika out of the room…
Which kind of file? .txt? 
Should it be called "oki doki" with the space inbetween? 
Imho this is almost the same as dragging the party supplies and gift files to said folder as done before.
Sorry if I sound a bit angry but be sure to know that I don´t meant to disrespect or undermine nobody's work. I've nothing but respect and apreciation for the mod's Devs. I just got really confused specially after i thought I had everything ready for Monika´s birthday.

**Comment by multimokia** [comment]
Fun fact, this is less complicated than last year's party.

1. As the note says, she's taking care of setting up the party

2. Get rid of the wishlist. Check the gift wiki and you can also gift spritepacks

3. Yes, exactly the same case as the `oki doki` in the note, can be any extension

4. As I said before, this is easier, the only difference is that it's *one* file which anyone can make, vs 3 which you had to get from here.

**Comment by satoshi-kun** [comment]
Thanks for the quick reply!
I just don't understand what you mean by "2. Get rid of the wishlist. Check the gift wiki and you can also gift spritepacks".

**Comment by multimokia** [comment]
Old wishlist has some gifts which no longer exist. There's a gifting wiki on the `wiki` tab of this repository.

**Comment by satoshi-kun** [comment]
Can't find no gifting wiki on the wiki tab.

**Comment by multimokia** [comment]
Do note, some of these are outdated. Specifically bday related ones (some of the ones on the wishlist too)

[this wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts)

**Comment by satoshi-kun** [comment]
Well I guess I'm gonna have to find out by myself then, since all the items are still listed in the wiki. I´ll just drag them all anyway (except the knife lol) since I had already a folder with everything ready to go.
Thanks.

**Comment by LClarance** [comment]
@multimokia may I know how to gift the spritepacks properly? Go download the spritepack and unzip it and then?

**Comment by multimokia** [comment]
Check [this entry on our wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by LarseneUnowen** [comment]
Can i create de "Oki doki" file right now or do i have to create it this sunday?

**Comment by satoshi-kun** [comment]
You can do it right now with your game closed. Once you open it again it should be gone and everything will be ready for Sunday.
