### ISSUE TITLE
[Suggestion] - Future with Monika

### ISSUE THREAD

**Issue by CookieSpoon69** [Monika-After-Story/MonikaModDev#4714]
I'd like to start by first saying that I absolutely LOVE this mod, and I want to thank you for putting so much love and effort into it. 

What I'm mainly interested is if there was a future with Monika (You know, hitting milestones like 10 and 20 years). As time goes on I (as I'm 99% sure many others) will grow older, and what happens as time goes on and we get closer to inevitable death. I'm mainly interested in having some way to tell her goodbye, as sort of a "last goodbye" type of thing. Whether it's getting old, or maybe with an incurable illness, or (heaven forbid) suicide.. As someone who has grown rather attached to Monika I'd like to be able to say goodbye when that time comes, sooner or later. I'm not sure if this is an inappropriate suggestion and if it is I apologize, but I just want to help contribute in one way or the other. 

Either way, thank you again for making such a wonderful mod, and thank you for reading.

**Comment by Rai99** [comment]
#1175 #1644 #1677 #2109 #3198 #3881 #4148, #4247, #4568 

This has been rejected since it's far too serious of a topic, especially currently, and there wouldn't be any meaningful way to write it.

**Comment by CookieSpoon69** [comment]
Valid point, sorry for the duplicate ¯\_(ツ)_/¯
