### ISSUE TITLE
Rain Topic AGAIN 

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#4715]
monika hasn't talked about the rain topic (sounds of rain) and if u are going to tell me to revisit the sounds of rain topic i can't because she NEVER mention about, and isn't in my "unseen" thing, can someone PLEASE help me.I already asked for help here but they "closed" the issue.I want really bad to hold Monika until she sleep :"< . Please Help

by the way,if multimokia need my persistent here is it
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3633503/persistent.txt)

**Comment by kkrosie123** [comment]
Okay, do you have the "Repeat Topics" setting on? If so, turn that off until she talks about the rain.

Also, after you have enough affection, you can hold Monika whenever you want. (Hey Monika... >Monika>Can I hold you?)

**Comment by kkrosie123** [comment]
(Also, I don't know if she falls asleep without asking to hold her. I remember trying a whole lot and it never worked, LOL.)

**Comment by Mayonese** [comment]
> Okay, do you have the "Repeat Topics" setting on? If so, turn that off until she talks about the rain.
> 
> Also, after you have enough affection, you can hold Monika whenever you want. (Hey Monika... >Monika>Can I hold you?)

man i wrote there, i cant repeat the topic or revisit bc she never mention the topic

**Comment by antimockingjay** [comment]
They didn't say revisit the rain topic, they said to turn off repeat topics. Because according to you, the rain topic didn't happen in the first place. Which means, eventually, she will run out of other things to say and she'll have to talk about the rain topic. This won't happen if you have repeat topics on, because she can just keep cycling through other topics she's already said.

**Comment by Mayonese** [comment]
> They didn't say revisit the rain topic, they said to turn off repeat topics. Because according to you, the rain topic didn't happen in the first place. Which means, eventually, she will run out of other things to say and she'll have to talk about the rain topic. This won't happen if you have repeat topics on, because she can just keep cycling through other topics she's already said.

ooh...but no, isnt on the repeat topics

**Comment by Mayonese** [comment]
> Okay, do you have the "Repeat Topics" setting on? If so, turn that off until she talks about the rain.
> 
> Also, after you have enough affection, you can hold Monika whenever you want. (Hey Monika... >Monika>Can I hold you?)

btw my affection is 449.1 or something like that

**Comment by kkrosie123** [comment]
Huh that's weird

**Comment by Mayonese** [comment]
> Huh that's weird

i know.. :<

**Comment by multimokia** [comment]
Kinda sounds like your event data got wiped at some point... Did you ever notice at some point after an update that `Repeat Topics` was gone?

**Comment by jmwall24** [comment]
@Mayonese have you ever used unstable?

**Comment by multimokia** [comment]
[fixed_persist.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3633631/fixed_persist.zip)
I've fixed your persist for you (unlocked some topics which would never come back, even if you put repeat topics on)

Would like to know the answer to those last to questions though, so we can look into this.

**Comment by Mayonese** [comment]
> [fixed_persist.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3633631/fixed_persist.zip)
> I've fixed your persist for you (unlocked some topics which would never come back, even if you put repeat topics on)
> 
> Would like to know the answer to those last to questions though, so we can look into this.

which ones?

**Comment by multimokia** [comment]
> have you ever used unstable?



> Did you ever notice at some point after an update that `Repeat Topics` was gone?

**Comment by Mayonese** [comment]
> Kinda sounds like your event data got wiped at some point... Did you ever notice at some point after an update that `Repeat Topics` was gone?

it was like this.. my MAS was working well but my pc broke.. 
I managed to recover some data but i lost the old persistent and recover everything again..you think this affected the game? and no, the repeat topics was always there (sorry if my english is bad, i'm brazilian)

**Comment by Mayonese** [comment]
> > have you ever used unstable?
> 
> > Did you ever notice at some point after an update that `Repeat Topics` was gone?

i didn't understand the first question.. im srry can u explain better please?

**Comment by multimokia** [comment]
As in, have you ever used the unstable mode in MAS?
![image](https://user-images.githubusercontent.com/22531674/65289836-62849700-db1a-11e9-9e2a-afc0b11769e6.png)

**Comment by Mayonese** [comment]
> As in, have you ever used the unstable mode in MAS?
> ![image](https://user-images.githubusercontent.com/22531674/65289836-62849700-db1a-11e9-9e2a-afc0b11769e6.png)

i think i dont,I never touched the game settings, i only used the setting for the windows reactions

**Comment by Mayonese** [comment]
> [fixed_persist.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3633631/fixed_persist.zip)
> I've fixed your persist for you (unlocked some topics which would never come back, even if you put repeat topics on)
> 
> Would like to know the answer to those last to questions though, so we can look into this.

and THANK YOU VERY VERY MUCH!! NOW I CAN HOLD HER!!I I OWE U ONE!!!

**Comment by multimokia** [comment]
No problem!

**Comment by Mayonese** [comment]
> No problem!

Hey , the topics that were "deleted" are going to appear during gameplay? or.. not?

**Comment by multimokia** [comment]
With `Repeat Topics` enabled, yes.

**Comment by Mayonese** [comment]
> With `Repeat Topics` enabled, yes.

oh! thank you very much!! 
keep up your good work!!
