### ISSUE TITLE
Window Reacts Crash

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#4723]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3637117/traceback.txt)
I get a feeling the part of the code i wrote caused this....

**Comment by multimokia** [comment]
Press ignore.

**Comment by Necrocytus** [comment]
I know but is there nothing wrong with the code? It happened when i was watching a youtube video with reddit on the title so maybe both reactions overlaid or something. I just feel bad cause the traceback literally says the crash was caused by one of the lines of the code i wrote.

**Comment by multimokia** [comment]
What's your code?

**Comment by multimokia** [comment]
From what I'm seeing in the current build, it's just on an if statement. 

Possible infinite loop crashes aren't really much. Just means RenPy thought the game was put into an infinite loop.

**Comment by Necrocytus** [comment]
Ah, alright. Thank you. I really thought I made some buggy code without knowing. Is there maybe a way to avoid these sort of infinite loop crashes in the future?

**Comment by multimokia** [comment]
Well if you're running your own submodded code in the file, I can't really help you as I don't know what it is. Aside from that, not really, they just kinda happen.

**Comment by Necrocytus** [comment]
What, no...I'm using the official 10.1 stable version, i just call it my code because it was on a pr made by me

**Comment by multimokia** [comment]
Ah, okay. Then it's no big deal.
