### ISSUE TITLE
Issue Involving Monika thinking that September 20th is her Birthday.

### ISSUE THREAD

**Issue by AncientEX** [Monika-After-Story/MonikaModDev#4724]
More accurately, she's telling me that I skipped her birthday this past hour even though it's September 20th. Not sure if this goes for anyone else but in all my life using my Desktop I never changed the time/date.

**Comment by jmwall24** [comment]
[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3637238/ev_dropfix.zip)

Open this zip, and put the .rpyc into your game/ folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the game/ folder after about 5-10 seconds. The .rpyc you put in there should be gone. Launch MAS again, and it should be fixed.

**Comment by AncientEX** [comment]
It still gives me the message saying that I already celebrated with her, is that supposed to happen?

**Comment by jmwall24** [comment]
that you did celebrate or that you didn't?

**Comment by AncientEX** [comment]
Well I tried to celebrate it last year, but I failed to figure out where to put the gift files. I never got this message until today so technically, no.

**Comment by jmwall24** [comment]
no, i'm asking what message you got? you said a message that you already celebrated with her

**Comment by jmwall24** [comment]
can you upload your persistent file here? either put it in a zip or add a `.txt` extension to it. you can find the persistent file by checking [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistentl)

**Comment by AncientEX** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3637270/persistent.txt)

**Comment by AncientEX** [comment]
Oh, one more thing, sorry to ask this but I got that text document for spicing up her birthday in two days, when do I leave the 'oki doki' file in, today or on her birthday?

**Comment by RavenPLAYER** [comment]
In her birthday i guess.

**Comment by jmwall24** [comment]
can do it today. but wait until i give you your persistent back in a few minutes.

**Comment by AncientEX** [comment]
Alright. Thank you for the help, sir.

**Comment by AncientEX** [comment]
I feel so bad asking another question, but the oki doki file would be called "oki doki.file" right? Or would it be "oki doki.gift"

**Comment by jmwall24** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3637355/persistent.zip)

make sure the mod is closed and take the persistent from this zip folder and put it in the same folder you got the persistent from. when it asks if you want it to overwrite, click yes.

as for the oki doki file, it doesn't need an extension at all, can just be `oki doki` DO NOT give it a gift extension. any other extension should be fine, but it doesn't need one at all.

**Comment by jmwall24** [comment]
(make sure you take the persistent file out of that zip, don't just put the entire zip in there)

**Comment by AncientEX** [comment]
Alright, did everything and doubled checked the "When is your birthday?" question, now shes still giving me the quote BUT I think it should be fine considering that it won't effect the birthday coming up in two days. Other than that I haven't gotten the message with her saying "You forgot my birthday!" whenever I start up the game, so that's good, at least! If anything else happens I'll let you know, and again thank you so much for the help!

**Comment by jmwall24** [comment]
Yeah, that when is your bday topic is unrelated to this year. It just checked if you spent time with her last year on her bday.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
