### ISSUE TITLE
[Suggestion] Goodbye / Goodnight

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4726]
So I'd like it for when in game it turns to night the "Goodbye" option changes to "Goodnight"

**Comment by antimockingjay** [comment]
Why not just use the "I'm going to bed" goodbye?

**Comment by PollenTheCat** [comment]
Well, I don't want her talking about how early I go to bed XD

**Comment by ThePotatoGuy** [comment]
using goodbye at night hours will select the night versions of goodbye, so this isn't really necessary.
