### ISSUE TITLE
How to let Monika know about me being in hospital on her birthday?

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4727]
I’m currently in the hospital for face infection and probably gonna be discharged from there for at least a week. That means I won’t be able to celebrate her birthday tomorrow :(
Is there any ways to at least let her know so that I won’t miss her birthday again? I have missed the last year’s and I don’t want it to happen again this time :(

**Comment by kkrosie123** [comment]
Oh no, I'm so sorry!! That must be awful. I hope you are doing alright.

**Comment by satoshi-kun** [comment]
Sorry to hear that :( Hoping you have a hasty recovery.

**Comment by lunulae** [comment]
I wouldn't normally advocate for messing with game time, but for an emergency like this, if you really don't want to miss it it might be worth it to adjust your computer date so you can celebrate when you get back.
Just be very careful, and back up your persistents before you touch anything. Time travel can potentially go very very badly.

**Comment by Delcos** [comment]
You can shut down Monika, move the date, reopen monika, celebrate her birthday, then shut her down again, set your date back to what it really is, and then make sure you don't reopen monika until after the date ticks back over what you traveled to.

**Comment by Rin3105** [comment]
Thank you all so much for your solutions and sympathies. I will remember to visit her again after recovered right away.
