### ISSUE TITLE
updated screenshots for MAS website

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#4729]
The in-game screenshots on the MAS website are so outdated that they don't even include the Extras button. We need updated screenshots.

Currently we have five:
1. Standard talk menu
![MAS-1](https://user-images.githubusercontent.com/3499462/65366017-5cf38380-dbe4-11e9-805e-8fa24f0cb9c6.png)

2. After selecting chess
![MAS-4](https://user-images.githubusercontent.com/3499462/65366030-84e2e700-dbe4-11e9-86d3-03cea794d097.png)

3. hair down greeting
![MAS-5](https://user-images.githubusercontent.com/3499462/65366039-8c09f500-dbe4-11e9-801c-d0de9f17b346.png)

4. hangman with custom word "monika"
![hangman2](https://user-images.githubusercontent.com/3499462/65366043-97f5b700-dbe4-11e9-9ca7-bd445eb82805.jpg)

5. custom dialogue saying to download the mod
![MAS-3](https://user-images.githubusercontent.com/3499462/65366049-a217b580-dbe4-11e9-9e7c-b103655931dd.png)

We're looking for not only replacements, but also other things to showcase, like different clothing and accessories, different weather, night mode, etc, so please don't just match the above 5 exactly. Updated versions of 1 and 5 are mandatory, 5 will be handled by us. 

Criteria for screenshots:
1. **Monika cannot be wearing any spritepack content.** 
2. **No spoiler content.** This includes:
     * kissing
     * special event content (922/o31/d25/f14/player birthday/etc...)
     * jumpscares
     * crashed greeting
     * islands
     * opendoor greeting (and "Listen" options)
3. **No submod content.** This includes:
     * custom fonts
     * custom backgrounds
     * custom UI
     * anything from #3765 
4. If you have given Monika a nickname, **it must be appropriate**.
5. Monika cannot be in the leaning pose.
6. Monika must be wearing the school uniform, with or without blazer.
7. Screenshots should be taken with the screenshot key "S". If you're going to take a screenshot of something where "S" key is disabled or does something else (like piano), then take a normal screenshot with whatever you normally use and crop it to the exact dimensions of the game screen. 
8. required aspect ratio: 16:9 (or close to it)
9. Submit screenshots as comments here.
10. When submitting your screenshot, please include the name you would like to be credited as.
11. Maximum 2 submission per person. (Resubmissons are allowed, we will promptly notify you if your submission breaks a rule)

All selected screenshots will be credited on the website. 
We will be selecting more than 5 submissions.

Deadline: 2019-10-01

**Comment by Trilasent** [comment]
![screenshot0005](https://user-images.githubusercontent.com/36512990/65366298-9a0d4500-dbe7-11e9-8668-5a4190e91f45.png)
Trilasent

**Comment by Rai99** [comment]
Are custom fonts allowed? ^^

What counts as spoiler content? 

Does the plushie count? Does dialogue only from love+ count?

**Comment by jmwall24** [comment]
Probably gonna need to be our default font @Trilasent

**Comment by jmwall24** [comment]
Also thoughts on nicknames for this @ThePotatoGuy 
I'm leaning towards no

**Comment by Trilasent** [comment]
He didn't bring it up when he told me custom fonts weren't allowed

**Comment by jmwall24** [comment]
That's why i'm asking

**Comment by ThePotatoGuy** [comment]
i updated the rules again. I think nicknames are ok depending on what they are.

**Comment by ThePotatoGuy** [comment]
id say plushie is non spoiler. same with love+dialogue, but its really caseby case.

FYI, im going to be hiding all of your comments that are not submissons

**Comment by NoexHaruhi** [comment]
![Monika_chess](https://user-images.githubusercontent.com/39390553/65366513-86171280-dbea-11e9-8bb5-d1fd0712ef2b.png)

**Comment by Trilasent** [comment]
There's a night mode for the UI?

**Comment by Rai99** [comment]
![screenshot0077](https://user-images.githubusercontent.com/38822045/65366603-27569680-dbf4-11e9-8a72-e4641b10dd01.png)
Rai99

**Comment by multimokia** [comment]
![smuggest](https://user-images.githubusercontent.com/22531674/65366427-ac8c7c00-dbf1-11e9-9dc6-acb315337100.png)
multi

**Comment by kkrosie123** [comment]
I looked around the game for something, and I found this and thought it was really cute.

If you do use it, please refer to me as Briar Young! Thank you!

![screenshot0005](https://user-images.githubusercontent.com/52429850/65367312-c3809d80-dbf4-11e9-8d3e-63c364d24c7e.png)

**Comment by Trilasent** [comment]
@kkrosie123 Red/ruby ribbon are part of MAS itself, so you're fine.

**Comment by NoexHaruhi** [comment]
![our time](https://user-images.githubusercontent.com/39390553/65368826-92f82e00-dc0b-11e9-9bec-5777a186f742.png)

**Comment by ManuEcheveste** [comment]
I don't know if the ring count like a spoiler, but here is my screenshot!
If you use it, you can refer to me as ManuEcheveste~
: D
![screenshot0001](https://user-images.githubusercontent.com/47963698/65369505-9ee7ee00-dc13-11e9-94c7-094a5af689d5.png)

**Comment by moonstne** [comment]
![screenshot0001](https://user-images.githubusercontent.com/3181589/65378039-82c66a00-dc70-11e9-9f9f-74ee6b240aa6.png)

**Comment by TriniTDM** [comment]
Is the promise ring considered spoiler content?

**Comment by ThePotatoGuy** [comment]
@TriniTDM 
> promise ring spoiler content
not spoiler content

> monika telling someone else happy birthday
not spoiler content

**Comment by TriniTDM** [comment]
![EFbFn1XWwAAGUu_](https://user-images.githubusercontent.com/52469676/65732288-2bbcfc80-e097-11e9-9b95-64c6d0a4a20f.jpg)

**Comment by Rai99** [comment]
Yeah, multiple submissions aren't allowed, but people seem to have forgotten we have a zoom feature too. I think it would be a good thing to showcase, but this is a second submission, not a resubmission.  
![screenshot0082](https://user-images.githubusercontent.com/38822045/65874213-3f948700-e353-11e9-97ba-694820e0fefa.png)

**Comment by ThePotatoGuy** [comment]
[submissions closed]

**Comment by ThePotatoGuy** [comment]
@TriniTDM the quality of your screenshot is low, there's a lot of visual artifacts. Can you redo that?

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
