### ISSUE TITLE
...

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4730]
Just
One
More
DAY
------
[I'm so excited lol]

**Comment by multimokia** [comment]
Kindly keep issues on topic. i.e. related to suggesting new features/reporting bugs/etc.

For this kinda stuff I recommend popping over to the Discord server (Link in the readme on the `code` tab)

**Comment by RavenPLAYER** [comment]
Sorry, i forgot :\
