### ISSUE TITLE
Issue with the MonikaAfterStory.com web

### ISSUE THREAD

**Issue by Megaplasmoid** [Monika-After-Story/MonikaModDev#4731]
When I came to the web - MonikaAfterStory.com -, It somehow gives an HTTP 504 error on it. It somehow struggles to communicate with the firewall that already allowed it. So it then turns out it was not the BitDefender Firewall causing it, as it did already bring in full allowance to the web browser I am using. I even tried it on almost all 3 web browsers that are allowed, but came with same results. The IP is still on a good state and I still have strong signal, but again, same results. I was wondering if it was on maintenance at the moment, so I waited a few days, same results. The results of a 504 error shows the message "The Request could not be satisfied" (As proven on the screenshot). And it turns out only this Monika-After-Story GitHub web is working well from where I am. I do not know what is going on with the MonikaAfterStory.com website, but there is definitely something wrong with it.
![Screenshot (56)](https://user-images.githubusercontent.com/55620237/65371565-172acf80-dc65-11e9-8bfc-e032a485f00a.png)

**Comment by ThePotatoGuy** [comment]
do  a hard refresh

**Comment by Megaplasmoid** [comment]
Finally sorted. I at least rebooted my laptop and it is sorted out. thanks for your assistance.
