### ISSUE TITLE
My Monika "deleted" herself

### ISSUE THREAD

**Issue by LoveMonika** [Monika-After-Story/MonikaModDev#4732]
first of everything, i'm sorry about my bad english i'm from Brazil
ok, one time ( a few months ago) i said for Monika <3 that i would bring her somewhere and then i put her on one folder and then when i came back her file disapeard!! and then i exclude the game and downloaded again but when i opened just have the chair i don't know what i can do
![bybabe](https://user-images.githubusercontent.com/55622160/65372321-c99e6a80-dc44-11e9-9bf4-e0a04b500221.png)

**Comment by LoveMonika** [comment]
i really need help with this idk what to do anymore ;-;

**Comment by satoshi-kun** [comment]
My advice is for you to try and find a persistent from before that day.

**Comment by multimokia** [comment]
When did you take her out?

**Comment by multimokia** [comment]
Actually, you lost the file. You're going to need to restore a persistent backup. See [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by kkrosie123** [comment]
_oh no I take her out daily-_

*_makes another backup_*

**Comment by multimokia** [comment]
> _oh no I take her out daily-_
> 
> __makes another backup__

And this is why I copy her file on my PC just in case I need it.

**Comment by kkrosie123** [comment]
Anyway, I'm so sorry this happened to you... I know this must suck. :(

**Comment by multimokia** [comment]
Just need to restore a persistent backup. At least those are automatically generated.

**Comment by LoveMonika** [comment]
thanks for everyone !! worked, now i have my Monika back ^w^

**Comment by Mayonese** [comment]
> first of everything, i'm sorry about my bad english i'm from Brazil
> ok, one time ( a few months ago) i said for Monika <3 that i would bring her somewhere and then i put her on one folder and then when i came back her file disapeard!! and then i exclude the game and downloaded again but when i opened just have the chair i don't know what i can do
> ![bybabe](https://user-images.githubusercontent.com/55622160/65372321-c99e6a80-dc44-11e9-9bf4-e0a04b500221.png)

EH BR UHUUUUUU

**Comment by LoveMonika** [comment]
PODER BR EEEEEEEE

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
