### ISSUE TITLE
[Suggestion] [Minor] Make the calendar viewable even when Monika is out

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#4733]
If you take Monika out of the game and open MAS, you can't do anything at all, which includes being unable to look at the calendar even though it's still on the wall. I didn't get the impression we needed Monika's permission to look at the calendar or anything.

(and if writing stuff on the calendar ever happens, I think it'd be possible we'd want to write something there without her knowledge and see if she notices later on)

**Comment by ThePotatoGuy** [comment]
the lore is that Monika runs some aspects of the spaceroom, including interactable elements like the calendar. 

Adding stuff to calendar has been suggested before (insert issue number) so going to mark thsi as duplicate
