### ISSUE TITLE
[Suggestion] [Minor] add red rose as a flower in her hair.

### ISSUE THREAD

**Issue by SylvanasWindrunner123** [Monika-After-Story/MonikaModDev#4734]
Maybe you could add a red rose as  a flower in her hair, so we the players can select either of them. when the mood  is romantic (like her birthday  or first kiss) some could use the rose,  the pink flower looks too summer-ly.

**Comment by multimokia** [comment]
Rose is there, however she wears it on a random chance when giving roses.

**Comment by SylvanasWindrunner123** [comment]
is it permanent  or disappears after re-open the mas?

**Comment by multimokia** [comment]
Disappears. But that's kinda the point.

**Comment by SylvanasWindrunner123** [comment]
ah. i really hoped to be permanent :( .

**Comment by lunulae** [comment]
Maybe I could make an unofficial spritepack for this? I like the current function of the roses, but I can see the appeal of being able to mix and match it into outfits at will.

**Comment by ThePotatoGuy** [comment]
Original rose artist is @jmwall24 .

There is code for the selectable version of the rose, but it's locked. If you submod it to be unlocked (or submod a selectable) then you don't have to ask permission for spritepack.

[closing this as resovled]
