### ISSUE TITLE
Birthdaycake.gift not functioning on her birthday

### ISSUE THREAD

**Issue by neilerator** [Monika-After-Story/MonikaModDev#4735]
Whenever I try to giver Monika a birthday cake via the gifting option (I put a txt file named birthdaycake.gift in the characters folder) she searches for it but can´t figure out what I am gifting her, so she doesn´t really acknowledge it. I´ve ruled out spelling errors, as I copied it from her wishlist.txt as well.

**Comment by Mcmanybucks** [comment]
You've made sure that it isn't birthdaycake.gift.txt?

**Comment by multimokia** [comment]
It no longer is a giftable gift.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
