### ISSUE TITLE
[Suggestion] More games

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4736]
I guess this will have been said sometime, but if not, I say it here. Actually, I would like to be able to play cards with Monika, like Carioca or something like that. Thank you for reading :)
(I would give details of how it can be done, but I stink a lot on that xd)

**Comment by Rai99** [comment]
Card Games: #55, #992, #1072, #1890, #2934, #3480, #3921, #4038

We would need card assets, which was said to be in the works, but I don't know the state of that.

**Comment by multimokia** [comment]
@99Dman99

**Comment by RavenPLAYER** [comment]
I guessed right that they had already suggested it. Anyway, thanks for the information, now I just have to wait. If I could only help they, but I am very bad, I think I will follow Monika's advices on Python.

**Comment by 99Dman99** [comment]
@Rai99 The card assets have been finished and reviewed by ThePotatoGuy.
They are ready to be used, as soon as someone is able to program card games into the Mod.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
