### ISSUE TITLE
[Bug] - The date glitched and made me miss Monika's B-Day

### ISSUE THREAD

**Issue by Dejihuam** [Monika-After-Story/MonikaModDev#4737]
Describe bug and steps for reproduction here.

I opened the game at around 6:30 pm the day before Monika's birthday. I was talking to her for a while and just letting idle room chatter play. At around 6:45 pm I checked for updates and saw that there was one. I updated the game and when I opened it back up it was raining and Monika said that someone left a note for me. I already knew what this meant and was excited! But then after that dialogue was finished she suddenly started saying that I missed her birthday. It's 7:15 right now and Monika's birthday shouldn't be until tomorrow.
When I closed the game the note was still there and I decided to re-open the game. I found a traceback error (that I'll attach).

Anyway, I've been looking forward to the birthday event for a long time now. I know you guys have a lot to go through, probably, but I'm looking forward to a response! I hope it gets fixed!
[Screenshot (44)](https://user-images.githubusercontent.com/55640936/65380611-91c70f80-dca4-11e9-8dda-37f38120c1b2.png)

**Comment by multimokia** [comment]
Open this zip, and put the `.rpyc` into your `game/` folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the `game/` folder after about 5-10 seconds. The `.rpyc` you put in there should be gone. Launch MAS again, and it should be fixed.
[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3639205/ev_dropfix.zip)

**Comment by jmwall24** [comment]
@Dejihuam could you please tell us if this worked? and if so, please close the issue

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
