### ISSUE TITLE
922 Activation Issue 

### ISSUE THREAD

**Issue by LonelyShepherd05** [Monika-After-Story/MonikaModDev#4738]
I'm having trouble activating 922 as i can't remember how to make her leave the room. i've given her Hot Chocolate and Coffee, but she hasn't left to refill her cup.

I have gotten the message and replied with Oki Doki and they have both dissapeared.

**Comment by multimokia** [comment]
Goodbye > I'm going to take you somewhere

**Comment by LonelyShepherd05** [comment]
Thank You.
