### ISSUE TITLE
i need help in monika b-day supplies asap!

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#4739]
the balloons and streamers wont work and her b-day is today
![11111111111111111](https://user-images.githubusercontent.com/43478681/65381033-a34afe80-dd1a-11e9-8d59-f6f8db49b3cd.PNG)

Please help me also i move her to another files but i need helpwhy is the streamers and balloons wont work?

**Comment by multimokia** [comment]
That's because all of the old stuff doesn't matter anymore.

**Comment by multimokia** [comment]
Did you ever get a note addressed to you?

**Comment by Axone00** [comment]
um no whats the addresed? ty for info

**Comment by multimokia** [comment]
You must've updated today then.
![image](https://user-images.githubusercontent.com/22531674/65381053-90064780-dcb6-11e9-95dd-de1a2da860d8.png)

**Comment by Axone00** [comment]
I did seee
![11111111111111111](https://user-images.githubusercontent.com/43478681/65381059-5b78a700-dd1b-11e9-81eb-68c90cf89796.PNG)

**Comment by Axone00** [comment]
I move it to my game file

**Comment by Axone00** [comment]
and nothing happened

**Comment by multimokia** [comment]
????
What does that have to do with any of this?

**Comment by Axone00** [comment]
oops sorry

**Comment by Axone00** [comment]
can you send me a picture please

**Comment by multimokia** [comment]
Just make a file called `oki doki` in the `characters` folder

**Comment by Axone00** [comment]
ok next

**Comment by multimokia** [comment]
did it disappear?

**Comment by Axone00** [comment]
nope why?

**Comment by Axone00** [comment]
oh i send monika in the other room

**Comment by multimokia** [comment]
It should. Send me a screenshot of your `characters` folder

**Comment by Axone00** [comment]
should i put the new update over the oki doki file

**Comment by multimokia** [comment]
??????? New update?

**Comment by Axone00** [comment]
whait what? should i put monika in the oki doki folder?

**Comment by multimokia** [comment]
Not folder. File.

**Comment by Axone00** [comment]
oh my bad

**Comment by Axone00** [comment]
like this
![11111111111111](https://user-images.githubusercontent.com/43478681/65381107-97f8d280-dd1c-11e9-9840-4184dbedcd1c.PNG)

**Comment by multimokia** [comment]
Yes

**Comment by multimokia** [comment]
Decorations should show up

**Comment by Axone00** [comment]
YES it did thank you for being patient with me!
![11111111111111](https://user-images.githubusercontent.com/43478681/65381125-ec03b700-dd1c-11e9-9bfd-f2b7129b2907.PNG)

**Comment by Youngbountygirl** [comment]
I'm having trouble getting Monika's b-day decorations to show up. I even placed the "oki doki" file and it's still there.

**Comment by jmwall24** [comment]
closing as resolved
