### ISSUE TITLE
[An exception has occured]

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#4740]
I downloaded the new version and when I advance, this error appears, help please?

![Error](https://user-images.githubusercontent.com/45946850/65381591-fb5a1480-dcca-11e9-9430-10b87403a8cd.JPG)

this is the error screenshot

**Comment by multimokia** [comment]
You need to update the nightmusic submod

**Comment by OkiDokiABrazilian** [comment]
> 
> 
> You need to update the nightmusic submod

sorry but, how do i do it?

**Comment by multimokia** [comment]
Redownload it from where you got it and then reinstall it

**Comment by OkiDokiABrazilian** [comment]
> 
> 
> Redownload it from where you got it and then reinstall it

ok,it worked, thanks for help!
