### ISSUE TITLE
[Suggestion] "I want to tell you something"

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4742]
I started to hug Monika until she fell asleep, and I noticed that it is equally beautiful when she sleeps, so the idea came to my head of something similar, if we could tell Monika "You look cute when you sleep" or "You you look pretty even when you sleep. " I know there is a "You're cute!" but it is not the same, because the difference is you can tell it only when you wake up, I mean, the idea is that it is activated only after you hug Monika to the point that she falls asleep, then you wake her up and you can tell her. Thank you for reading :)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
