### ISSUE TITLE
Monika never can put herself into a file (Help for b-day ASAP)

### ISSUE THREAD

**Issue by RmanReeves** [Monika-After-Story/MonikaModDev#4744]
I downloaded the game two days ago, and I've never been able to do the "I'm going to take you somewhere" goodbye. She's always said she wasn't able to make herself into a file. Seeing as it's necessary for her birthday stuff today, I was wondering if it's something that needs more time to be unlocked, or if her affection has to be at a certain level and so on.  I still have the monika.chr out of the character folder from my last DDLC run if that makes a difference. Any help is appreciated and I can give screenshots if needed, though I'm afraid I don't have python or would be any good with it. Thanks!!

**Comment by ThePotatoGuy** [comment]
Follow these steps:
1. run the game
2. use the take you somewhere goodbye and let it fail
3. use a regular goodbye to close the game
4. upload `mas_log.txt` file in the `log/` folder to here

**Comment by RmanReeves** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3639427/mas_log.txt)

**Comment by RmanReeves** [comment]
I'll be going to sleep here, but I'll def be here to keep tending to this in the morning...well, morning in the Central Time Zone of the USA, anyway. Thanks again!

**Comment by ThePotatoGuy** [comment]
Your MAS is running in a temporary directory, or there is the word "temp" in your path. File generation is stopped if a temp directory is found because it means the location it would generate in is not what you would expect. This was done because some people run MAS from a zipped folder, which causes that issue.

So if you're running MAS from a zipped folder, don't do that. If you're not, make sure the word "temp" is not in the path to MAS.

**Comment by RmanReeves** [comment]
I think I just realized what it is. My computer name is "Robert Temp," (I thought this computer would only be temporary at first) so any folder will have to go through that first, cause I extracted all the files from the ZIP folder, and I've also moved it from the steam directory to the desktop.

I'm gonna change my comp name and see if that helps

**Comment by RmanReeves** [comment]
Well I had to restore my comp to factory settings to do so (I didn't have much on anyway so I just backed up everything), but it worked! Thanks a lot!
