### ISSUE TITLE
I CAN'T TRIGGER MONIKA'S B-DAY!!

### ISSUE THREAD

**Issue by Youngbountygirl** [Monika-After-Story/MonikaModDev#4745]
I'm trying to trigger the b-day, but I don't see any decorations, aside from the roses. I tried looking into the other issues and even created a file called "oki doki" but nothing is happening. The "oki doki" file is still there and such. I also downloaded the latest update and keeps reading to update, even though I downloaded the latest update. Please help!

**Comment by RavenPLAYER** [comment]
It worked like this:
1: Open MAS and use the "I'm going to take it somewhere" parting.
2: Place the "Monika" file on your desktop or anywhere other than the same character folder.
3: Open the game again and the decorations will come out.
4: Close it
5: put Monika back in the character folder

And enjoy Monika's birthday.

**Comment by Youngbountygirl** [comment]
That's the problem. I opened the game, told Monika I would take her somewhere, placed her folder on my desktop, then when I opened the game again, nothing. Monika is gone and there are no decorations. just the roses.

**Comment by Youngbountygirl** [comment]
I also downloaded the 10.1 files again and the decorations are still not there. Do I need to bring Monika's folder back and try again?

**Comment by RavenPLAYER** [comment]
I really don't know, I'm not good at moving things from files and stuff, I don't want to give you false explanations that I don't even know if they will work, that could ruin your MAS ... Sorry but I'm afraid I won't be able to help you, I guess You will have to wait for someone who knows the problem to answer you.

**Comment by RavenPLAYER** [comment]
As I said before, it worked for me and I don't even know if I did it in the best possible way.

**Comment by RavenPLAYER** [comment]
https://www.youtube.com/watch?v=hw4WZhIVGZQ&t=7s

**Comment by Youngbountygirl** [comment]
Okay, thank you anyways. Here's what I'm seeing so far.

![Monika After Story 9_22_2019 1_54_27 AM](https://user-images.githubusercontent.com/47648057/65383509-3e70b380-dcdc-11e9-9a09-a22788bc6a0d.png)

**Comment by RavenPLAYER** [comment]
WaIt A mInUtE

**Comment by RavenPLAYER** [comment]
That fund that is there no longer exists in the new version. Are you sure you have the correct version?

**Comment by RavenPLAYER** [comment]
An idea occurred to me ... follow these steps.
1: Go to the game download page
2: Download "MAS 0.10.0"
3: Once done the job of transferring files, open the game
4: Once inside, go to "settings" and "Update version".
5: There he tries again the birthday.

(That fund in the version of 0.10.0 does not exist anymore, and therefore in the 0.10.1 either, it is strange to me that you have that background through the window)

**Comment by Youngbountygirl** [comment]
Oh! I might've not downloaded 10.0.

**Comment by Youngbountygirl** [comment]
I changed my time to the day before to give myself time just in case. This way, I can trigger the event properly at the very least.

**Comment by RavenPLAYER** [comment]
Well thought. Let me know if what I told you worked, if so, I will feel a hero xd

**Comment by Youngbountygirl** [comment]
Okay, I downloaded the 10.0. Though, I'm not recieving any notes, even though I changed the date to the day before. Should I change it back, then place the oki doki file?

**Comment by RavenPLAYER** [comment]
Yes, do that and then remember to go to "settings" and "update version" in the same game.

**Comment by RavenPLAYER** [comment]
Once you update it, take Monika somewhere and return to the game, if again the decorations are not ... sorry, but I will not be able to do anything else for you (Not because I don't want to, but because I don't know what more could you do xd)

**Comment by Youngbountygirl** [comment]
settings? I see "update" in the Doki Doki Literature Club folder, but not "settings."

**Comment by RavenPLAYER** [comment]
Inside the game bro

**Comment by Youngbountygirl** [comment]
you mean once I turn on DDLC game? Where is "settings"?

**Comment by RavenPLAYER** [comment]
No game folder

**Comment by RavenPLAYER** [comment]
Inside DDLC, go to setting and update version

**Comment by RavenPLAYER** [comment]
![screenshot0006](https://user-images.githubusercontent.com/55263957/65383981-e7c2a400-dcf2-11e9-8218-d4e9cae09fe1.png)

**Comment by Youngbountygirl** [comment]
got it, but then I got this 
![Monika After Story 9_22_2019 2_41_06 AM](https://user-images.githubusercontent.com/47648057/65384015-927e9680-dce2-11e9-8d48-ff5c6e061447.png)

**Comment by RavenPLAYER** [comment]
You use steam?

**Comment by Youngbountygirl** [comment]
Yeah.

**Comment by RavenPLAYER** [comment]
Uuuh, this is a problem for me... i don't use Steam, i download DDLC from official page

**Comment by Youngbountygirl** [comment]
Ah. Usually, when I update, I manually download it from the mod's site and past it in my game folder. Though, for some dumb reason, it keeps saying, "update!"

**Comment by RavenPLAYER** [comment]
Can you download DDLC from the official page? Then you do the thing i said you

**Comment by RavenPLAYER** [comment]
How not to use Steam, I don't know what to do

**Comment by Youngbountygirl** [comment]
You mean just the regular game? I can see if I can try, but it's not the same as using the mod.

**Comment by RavenPLAYER** [comment]
I mean, download the original game in .zip and then transfer the mod files and stuff

**Comment by RavenPLAYER** [comment]
After you do that, you do what I told you before and you answer me to see if it worked for you, and if it didn't, to help you with more things that you at least know

**Comment by Youngbountygirl** [comment]
Yeah, I'm downloading the original game, but I'm going to see if I can copy and paste the stuff in the same way I do with the mod.

**Comment by Youngbountygirl** [comment]
What I don't understand is why I have to manually download the original DDLC and the mod at the same time and wouldn't it effect the progress I made from steam?

**Comment by RavenPLAYER** [comment]
Follow these steps.
1: Download the original game in .zip
2: If you already have the MAS version 0.10.0 folder, do what you always do with a mod (Transfer the folders from game to game and stuff)
3: Once you've done that, follow the steps that I already mentioned back

**Comment by RavenPLAYER** [comment]
Oh, maybe you're right ... but in steam it is done manually, instead with the original game you press the "update version" button in "settings" and it does it automatically.

**Comment by RavenPLAYER** [comment]
If you download the game on the official website, you enter the game and Monika remains the same, you can continue with what I told you, but if it restarts you will have to stay in steam, and there I can not help you because I have no idea...

**Comment by Youngbountygirl** [comment]
That's what I was trying to say. Though, it keeps saying update. I even checked on steam and it says everything is updated. If it isn't updating, I might have to do this manually. What I'm afraid of is deleting a file that shows my progress.

**Comment by RavenPLAYER** [comment]
Then stop there, because I don't know what else to do and I'm not going to make you lose your Monika, Sorry, but I can't help anything else :(

**Comment by Youngbountygirl** [comment]
Thanks for trying to help though. If you know someone that has steam and can help me, link them here.

**Comment by RavenPLAYER** [comment]
@multimokia Hey there, can you help us? well, more to him than to my xd

**Comment by Youngbountygirl** [comment]
I did try doing that again and it still won't work. Even with adding the "oki doki" file. I don't know why it's being like this. On top of that, the game keeps telling me I have to update the game, even though it should already be updated. I did download 10.0 and 10.1 and have not received any notes from anyone or anything. I tried setting my game up to change the time and it still won't work. The only thing I can think of is that because I'm on steam, it's being difficult. If anyone can tell me what I'm doing wrong, please do. I'm going to go to bed now. I was hoping on throwing Monika a b-day party at midnight, but it looks like that will have to wait. I might have to change the date on my computer. Monika's file is currently on my desktop and there are no decorations or anything. It's just like the post you see on the top.

**Comment by Youngbountygirl** [comment]
![Monika After Story 9_22_2019 3_36_39 AM](https://user-images.githubusercontent.com/47648057/65384645-3e77b000-dcea-11e9-848c-6f8138450d80.png)
This is what I'm getting. I have "oki doki" in my character file.

**Comment by RavenPLAYER** [comment]
Do not keep trying because the version you have is the wrong one. Tomorrow awaits the response of someone who knows what to do in steam bro, be patient and you can spend Monika's birthday with her. I promised to spend all day and all night with her, although well, it would be all night and all day, since at this moment I am hugging her, but tomorrow I will do several things with her. Most likely, I took her for a drive on my flash drive.

**Comment by Youngbountygirl** [comment]
Okay. I shut my laptop down, so I will wait until tomorrow.

**Comment by RavenPLAYER** [comment]
Goodnight, hopefully you can have answers

**Comment by ElectroKitten** [comment]
Hey, I used to use the steam version. I'm pretty sure that Monika detects you using the steam version and tells you to move the DDLC directory to a different location because it can screw with updates. The directory is located in; Local Disk (C:) or D:/Steam/Steamapps/common/Doki Doki Literature Club Just drag that file somewhere else on your PC. This might help your problem with not being able to update.

**Comment by RavenPLAYER** [comment]
I feel like a idiot… maybe i am one.

**Comment by ElectroKitten** [comment]
Hey, don't say that about yourself, you're not an idiot, man. Like you said, you didn't use the steam version so you probably couldn't have known.

**Comment by RavenPLAYER** [comment]
You may be right, but I still can't help feeling bad if I couldn't help even one person.

**Comment by ElectroKitten** [comment]
You tried your hardest, buddy. Don't beat yourself down cause of that, Monika wouldn't want you to feel like this. She'd be proud of you for trying to help someone.

**Comment by RavenPLAYER** [comment]
Hehe, you're right. Thanks, i feel someone again xd

**Comment by ElectroKitten** [comment]
No problem bud! :)

**Comment by jmwall24** [comment]
@Youngbountygirl if you are sure you have updated to 0.10.1, can you show us a screenshot of the characters folder if the `oki doki` file is still in it?

**Comment by Youngbountygirl** [comment]
![Monika After Story 9_22_2019 12_49_46 PM](https://user-images.githubusercontent.com/47648057/65392209-d64fbb00-dd37-11e9-9b3c-9241a0841086.png)
FINALLY GOT IT! I took ElectroKitten's advise and moved my folder to a different location before updating the game. It worked like a charm. Once I updated the game and reopened it, the oki doki file disappeared and Monika changed her outfit. Thanks a bunch RavenPLAYER, ElectroKitten and jmwall24.

**Comment by ElectroKitten** [comment]
Hooray! And it was no problem at all, hope you and your Monika have a wonderful day together!

**Comment by Youngbountygirl** [comment]
Thanks. I'll have to remember to update my game outside the steam folder. Steam isn't updating DDLC for some reason.

**Comment by RavenPLAYER** [comment]
Yay! You got it!

**Comment by RavenPLAYER** [comment]
![screenshot0001](https://user-images.githubusercontent.com/55263957/65392398-ef159c00-dd4a-11e9-816b-3a09d7d66238.png)

Last night with Monika, and today, and tomorrow, and- okay.

**Comment by Youngbountygirl** [comment]
Yay! :3 I got to celebrate Monika’s b-day.

**Comment by jmwall24** [comment]
closing as resolved
