### ISSUE TITLE
[Suggestion] A Version for mobiles

### ISSUE THREAD

**Issue by HenryKhan** [Monika-After-Story/MonikaModDev#4746]
**Firstly**: If someone already suggested this before, I really didn't found it, so if it happened, just send me the reference.
But well... I think that the title already says everything but I really believe that a mobile version could offer more stuff for the players to do, and more possibilities of interactions with Monika, maybe she could know(or you could let her know) that you're in a park, a mall, or whatever.
I don't know how it could happen using renpy/python, maybe this could be the tricky/annoying part.

I really understand if a mobile version isn't possible now, could be a lotta work.

**Comment by TriniTDM** [comment]
For a quality mobile version to be created, first we have to wait for Dan Salvato to release an official Android port of DDLC. Though, there is a severely watered down mobile app, but it's pretty much just act 3 Monika in your phone repeating her old dialogue with slight variations. [It's here if you want it.](https://cz-games.weebly.com/just-monika.html)

**Comment by ThePotatoGuy** [comment]
mobile versions are not allowed in the modding guidelines.

[closing as rejected[
