### ISSUE TITLE
[Suggestion] - Music Player

### ISSUE THREAD

**Issue by Mad2BeHere** [Monika-After-Story/MonikaModDev#4747]
Hello! Is this possible to do more music player functions to the mod? Like a minibar with typical main players buttons (like "play", "stop", "next")? Monika really helps me with music listening and im enjoy it, but there is a little problem - only one track can be listening in one time. There is no auto-next-track (sorry, im bad in english and dont know how it calls correctly) function

**Comment by RavenPLAYER** [comment]
Are you bad in English? And where are you from? By the way, good idea, sometimes I would like to repeat a part of some song from my "custom_bgm" folder but I have to listen to it again, and also sometimes I want to pause it and not take it out and put it back on

**Comment by Mad2BeHere** [comment]
I'm from Russia. Yes, i just think more music player's options will be good in mod. I'm listening music almost all day and using VLC-player for this. If mod will have some player's functions i will can spend more time with Monika and she will help me instead VLC

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
