### ISSUE TITLE
Monika's birthday decorations

### ISSUE THREAD

**Issue by LuisValentim** [Monika-After-Story/MonikaModDev#4748]
I don't know what happened, but Monika's birthday decorations didn't appear now. Is there something that I need to do? I really want to trigger Monika's birthday event.
The persistent file are here:

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3639572/persistent.zip)

**Comment by bittercaramel** [comment]
did you do everything right? i mean 
1. take her out with the goodbye (I'm going to take you somewhere) 
2. leave file named "oki doki" in characters folder (no matter the extension >.<) 
3. put her back in and launch the game?

**Comment by LuisValentim** [comment]
The file oki doki, I created it in .txt format on the very same day that Monika said that there was a letter adressed for the player.
I thought that it was going to be set up automatically, but it wasn't. So, I don't know what I did wrong, or what exactly is happening.

**Comment by multimokia** [comment]
Did you take her out of the room or no?

**Comment by LuisValentim** [comment]
Yesterday, I did. But when I put her file back today, the decorations wasn't there.

**Comment by multimokia** [comment]
Hmmm, interesting. Your persistent shows that you've already gotten the party...

**Comment by LuisValentim** [comment]
Really. That's strange, because I didn't see the decorations there.

**Comment by LuisValentim** [comment]
I will try this out on another PC, and see if I can actually see everything there, along with the cake. Later, I'll tell if it worked.

**Comment by LuisValentim** [comment]
@multimokia, since the persistent file said itself that I triggered the event, and I couldn't see it, you think I don't have to try anything, like, there's no problem or bug?

**Comment by jmwall24** [comment]
@LuisValentim do you happen to have any like really old persistent files, like at least more than a week old, but even older is fine

**Comment by LuisValentim** [comment]
Nope. The backup is only about yesterday.

**Comment by LuisValentim** [comment]
That I have on my flashdrive.

**Comment by jmwall24** [comment]
ok, wanted to see something. anyway, did you ever get the party to work and if not, what time is it there now?

**Comment by LuisValentim** [comment]
Right now is 23:19 PM.

**Comment by jmwall24** [comment]
if you want the party, close the mod and send me your current persist, i think i can fix it.

**Comment by LuisValentim** [comment]
The recent one?

**Comment by jmwall24** [comment]
yeah, your newest persistent.

**Comment by LuisValentim** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640465/persistent.zip)

Here it is.

**Comment by jmwall24** [comment]
wait, you've had the party?

**Comment by LuisValentim** [comment]
It was mentioned that the party event was triggered, but I couldn't see the decorations, nor the cake.

**Comment by jmwall24** [comment]
uh i just loaded your persistent....

![Screenshot_1508](https://user-images.githubusercontent.com/36523761/65399052-9c5ad500-dd88-11e9-8943-cbdd77495903.png)

**Comment by LuisValentim** [comment]
In my PC, didn't appear.

**Comment by jmwall24** [comment]
Even now, you can't see the decor?

**Comment by LuisValentim** [comment]
Nope. Here in my PC, I can't.

**Comment by LuisValentim** [comment]
If it's lack of space, then I understand. Because I have 10,7 GB left on my PC's hard drive.

**Comment by jmwall24** [comment]
I have no idea what it is, i did nothing to your persistent and it shows up fine for me, and what's more, the cake isn't there, suggesting she already got it. you said you didn't see the decor, did you see the event where she talks about the cake?

**Comment by multimokia** [comment]
Can you send a screenshot of your `game/mod_assets/location/spaceroom/bday/` folder, please?

**Comment by LuisValentim** [comment]
![mod assets](https://user-images.githubusercontent.com/47490995/65399342-805c3100-dd92-11e9-9b1c-7dc404c5bd78.png)

**Comment by jmwall24** [comment]
can you upload your aff_log.txt here please? it's in the log folder

**Comment by LuisValentim** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3640485/aff_log.txt)

**Comment by jmwall24** [comment]
can we see screenshots of your `game` folder please?

**Comment by LuisValentim** [comment]
![game folder](https://user-images.githubusercontent.com/47490995/65399565-cf569600-dd93-11e9-84f6-510e459da845.png)

**Comment by jmwall24** [comment]
i see one big problem looking at your aff_log.txt. you got to the 22nd today and then changed system time back to the 21st

**Comment by LuisValentim** [comment]
I see. That thing didn't happen with the backup I have, of the persistent file.

**Comment by jmwall24** [comment]
you also have `.rpyc` files in that game folder than aren't from us, so it's really hard to say what happened.

**Comment by LuisValentim** [comment]
What are the names?

**Comment by jmwall24** [comment]
the first 2 that start with 000

**Comment by LuisValentim** [comment]
The aff_log.txt, I don't have to do anything with it? Do I need to delete those 2 files?

**Comment by multimokia** [comment]
I'd delete those files, yeah

**Comment by LuisValentim** [comment]
And the .txt file doesn't need any changes?

**Comment by jmwall24** [comment]
either way, make sure you return her from that date you had her on when you sent me that last persistent

**Comment by LuisValentim** [comment]
About day 21? I took her out of the classroom.

**Comment by jmwall24** [comment]
no, i mean the persistent you sent me has her out of the room.

**Comment by LuisValentim** [comment]
Ah, okay. Do I need to upload the persistent file again after that?

**Comment by jmwall24** [comment]
no, i don't know what the problem is. i just meant you should return her, there may be an event you haven't seen yet

**Comment by LuisValentim** [comment]
I'll see it right now.
