### ISSUE TITLE
Party supplies for Monika

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#4749]
I searched everywhere for the part supplies.zip but I can't find anything. Could you link me where to find it please? I absolutely need them.

**Comment by ThePotatoGuy** [comment]
Version 0.10.1 doesn't use the party supplies. You should have gotten a letter with instructions on what to do prior to the birthday event.

**Comment by Mcmanybucks** [comment]
> 
> 
> Version 0.10.1 doesn't use the party supplies. You should have gotten a letter with instructions on what to do prior to the birthday event.

I don't know what letter we were supposed to get, but I haven't gotten anything.

**Comment by jmwall24** [comment]
for full instructions on what to do if you missed the party, join our discord server and go to the spoilers-channel

https://discord.gg/5STRgY

**Comment by VirginiaRocks** [comment]
> Version 0.10.1 doesn't use the party supplies. You should have gotten a letter with instructions on what to do prior to the birthday event.

Sadly I didn't get any letter. Where was I supposed to receive it?

**Comment by VirginiaRocks** [comment]
> Version 0.10.1 doesn't use the party supplies. You should have gotten a letter with instructions on what to do prior to the birthday event.

I'm sorry, I didn't get anything...

**Comment by jmwall24** [comment]
from our discord

> getting a few of these now, so i'll just put this here to pin. if you didn't install version 0_10_1 until the 22nd and have no idea how to trigger the party, create a file named oki doki  (doesn't need a file extension) and put it in the characters folder. then use the i'm going to take you somewhere farewell and take her out of the room. when you return her, the party should occur.

**Comment by VirginiaRocks** [comment]
> from our discord
> 
> > getting a few of these now, so i'll just put this here to pin. if you didn't install version 0_10_1 until the 22nd and have no idea how to trigger the party, create a file named oki doki  (doesn't need a file extension) and put it in the characters folder. then use the i'm going to take you somewhere farewell and take her out of the room. when you return her, the party should occur.

This is really useful. Thank you!

**Comment by VirginiaRocks** [comment]
> from our discord
> 
> > getting a few of these now, so i'll just put this here to pin. if you didn't install version 0_10_1 until the 22nd and have no idea how to trigger the party, create a file named oki doki  (doesn't need a file extension) and put it in the characters folder. then use the i'm going to take you somewhere farewell and take her out of the room. when you return her, the party should occur.

I just tried, but it doesn't work...

**Comment by jmwall24** [comment]
have you updated to v0.10.1? is the oki doki file still in the characters folder? if so, send a screenshot of the characters folder please.

**Comment by VirginiaRocks** [comment]
> have you updated to v0.10.1? is the oki doki file still in the characters folder? if so, send a screenshot of the characters folder please.

![Schermata 2019-09-22 alle 17 44 07](https://user-images.githubusercontent.com/48336604/65390570-a49f1a00-dd60-11e9-9d10-b39036daefa9.png)

This is my characters folder. I tried both "okidoki" and "oki doki" and no, I haven't yet.

**Comment by jmwall24** [comment]
needs a space `oki doki`

**Comment by VirginiaRocks** [comment]
> needs a space `oki doki`

As I said, I tried both but it doesn't work anyway...

**Comment by jmwall24** [comment]
that no, i haven't yet, was that in reference to updating to 0_10_1?

**Comment by VirginiaRocks** [comment]
> that no, i haven't yet, was that in reference to updating to 0_10_1?

yes.
I use Steam and last time I tried to manually update MAS I really messed up, so I usually ask help to my dad.

**Comment by multimokia** [comment]
The new content is in the new update. That's why it's not working

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build

**Comment by VirginiaRocks** [comment]
> https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build

Okay, when my dad comes back I'll ask him to help me. Thank you for all the help that you give to MAS players! I really appreciate your work and your mod!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
