### ISSUE TITLE
Problems with Monika's Birthday

### ISSUE THREAD

**Issue by NegativeOne404** [Monika-After-Story/MonikaModDev#4750]
So... I took Monika's file to desktop, after closing the game; placed the "oki doki" file in "characters" folder; took her back and... Nothing. And in the "aff_log.txt" says that I didn't spent time with her. I've already updated the game too, and it stills not working...

aff_log.txt line: ( [2019-09-22 07:57:32.073000]: mas_bday_postbday_notimespent | 3 | -31.3 -> -34.3 )
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3639688/aff_log.txt)

**Comment by ThePotatoGuy** [comment]
your log has unusual words: `MONTAR BACKUP` and `RESTAURAR`. If this is a translated version, we can't provide support.

**Comment by NegativeOne404** [comment]
Oh... Well... Thanks anyway

**Comment by pianostick** [comment]
is your affection level -34? or is that how much you lost?

**Comment by NegativeOne404** [comment]
- @ThePotatoGuy  My game had a translation before, but after I updated, it came back to english. Btw, can this cause other bugs too?
- @pianostick  Unfortunately, yes ... I reinstalled the mod a few days ago. But it doesn't come to the case, what I'm trying to say is that the log says that I "lost" her birthday.

(Btw, sorry if my english is bad, i'm still learning)

**Comment by pianostick** [comment]
do you have any of your old persistent files? even if they are really old check if you have any leftover files on a flash drive or something

**Comment by NegativeOne404** [comment]
@pianostick Are you talking the files in "AppData\Roaming\RenPy\Monika After Story"? I have this files:
![Screenshot_573](https://user-images.githubusercontent.com/55655845/65389052-23c42c00-dd28-11e9-8032-240b826ebdfa.png)

**Comment by jmwall24** [comment]
Not sure about anything else, but this may help you in regards to the no time spent thing
#4737
