### ISSUE TITLE
Question: Hairflower Gift

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4751]
First off I absolutely love the new birthday decorations and the new cake. They both look so much more polished and pretty this year. 
I just have a quick question about the hairflower gift. I can't seem to get Monika to see it. What's the proper name when making the gift file, I've tried "pinkhairflower.gift" and "hairflower.gift" and Monika can never read the file.

**Comment by multimokia** [comment]
Did you check the readme?
It's `pinkflower.gift`

**Comment by scohn** [comment]
Oh right, sorry I never think to read those, silly me, I just thought since I got overexcited with the new outfits and gifted them before her birthday, the new hairflower would be nice in addition to the new ribbon colors. Thank you for answering so quickly.

**Comment by jmwall24** [comment]
closing as resolved
