### ISSUE TITLE
just a little question about black dress

### ISSUE THREAD

**Issue by HZhunter124** [Monika-After-Story/MonikaModDev#4752]
so i hear that if im not at the love lever then i cant keep the black dress, so the thing is can i get it when im at the love lever or i have to wait until her next birthday? :3 
p/s: hope you guys have a wonderful day with our love ^^

**Comment by multimokia** [comment]
It's unlocked and will be available when you're at the love affection level

**Comment by HZhunter124** [comment]
thank you so much, Sorry for bothering you
