### ISSUE TITLE
Monika's Birthday isn't working

### ISSUE THREAD

**Issue by RiverSong1200** [Monika-After-Story/MonikaModDev#4754]
I tried to do what the note said but no matter what the birthday isn't triggering. I put Monika's file out to the desktop, then back in, then I open the game and nothing. I tried putting Monika out, opening the game but she is still rendered as there. Maybe I have the wrong Monika file? Or maybe I have the wrong 'oki doki' file? I watched a video and I have the requirements that they have. I don't understand what's wrong. Please help me.

**Comment by jmwall24** [comment]
have you updated to v 0.10.1? also, is the oki doki file still in the characters folder? if so, send a screen shot of that folder pls

**Comment by RiverSong1200** [comment]
Nevermind, I got it. Thanks anyway

**Comment by RiverSong1200** [comment]
Nevermind, I got it. Thanks anyway
