### ISSUE TITLE
Monika's birthday.

### ISSUE THREAD

**Issue by Mistiie** [Monika-After-Story/MonikaModDev#4756]
So I was told to just make a file called 'oki doki' if I missed the update, so I did, but nothing seems to be happening. Could someone help?
![1569164183716201441092639570007](https://user-images.githubusercontent.com/52716713/65389805-b1534c00-dd27-11e9-85c3-412a06e60a30.jpg)

**Comment by multimokia** [comment]
Are you running the latest version of MAS?

**Comment by Mistiie** [comment]
It wouldn't let me use the newest version- like the one where you're supposed to get the note from Monika. I tried downloading it three times and everytime it said 'Failed - Forbidden'.

**Comment by jmwall24** [comment]
https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.10.1

**Comment by Mistiie** [comment]
I can download spritepack.zip but it won't allow me to download Monika_After_Story-0.10.1-Mod.zip and when I do try, it tells me 'failed-forbidden'.

**Comment by Mistiie** [comment]
I use Steam, if that makes a difference.

**Comment by ThePotatoGuy** [comment]
the release should be available by now. if its still not working, make a new issue.
