### ISSUE TITLE
Moving the DDLC files out of Steam.

### ISSUE THREAD

**Issue by Mistiie** [Monika-After-Story/MonikaModDev#4757]
I know I just posted an issue- but now I've caused another. I moved the DDLC files out of Steam, but now it won't let me open it. When I click on the files I've dragged out, it just redirects me into the files.
![15691671906874604411063498560892](https://user-images.githubusercontent.com/52716713/65390594-a819ad80-dd2e-11e9-9e76-5f0f04aae2e3.jpg)
![15691672159335232771726567670465](https://user-images.githubusercontent.com/52716713/65390598-b4056f80-dd2e-11e9-859d-ebb6957a159e.jpg)

**Comment by jmwall24** [comment]
you only moved a shortcut to the folder out, you have to move the entire folder out, and also leave the ddlc.exe file in the folder

**Comment by Mistiie** [comment]
how do i move the entire folder out? sorry, i'm not very good at computers- i got myself in this mess trying to get the monika birthday

**Comment by jmwall24** [comment]
Did you follow this? https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build

**Comment by Mistiie** [comment]
Yes- I went back to the 'common' folder and dragged DDLC onto my desktop, but now I can't even open it without an error showing up

**Comment by jmwall24** [comment]
but it only made a short cut of it. go back there to that same folder and click cut and then paste it on your desktop

**Comment by Mistiie** [comment]
I tried again, and the same thing happened. It's a shortcut. I went to the 'common' folder, copied Doki Doki Literature Club and then cut it. Then I pasted it on my desktop and it's still a shortcut. Am I missing something?

**Comment by jmwall24** [comment]
i don't know what to tell you. can you at least still run the mod from steam?

**Comment by multimokia** [comment]
alternatively, you can just get a copy of ddlc from https://ddlc.moe/, put it on your desktop or something, and install MAS into it. Your progress won't be lost.

**Comment by Mistiie** [comment]
I can still open it in Steam. But I will try getting a copy of DDLC. Thank you, I'll tell you what happens. Thank you for your time

**Comment by Mistiie** [comment]
So I downloaded the new DDLC- do I copy everything from each file of my old one and paste it into the correct folder?

**Comment by multimokia** [comment]
No, just install MAS into it https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.10.1

**Comment by Mistiie** [comment]
Will I lose my current progress? Or do I just need to replace the persistent file?

**Comment by multimokia** [comment]
You won't lose any progress. The persistent isn't stored in the game files.

**Comment by Mistiie** [comment]
I'll try that- thanks

**Comment by Mistiie** [comment]
I feel dumb asking- but once I download it from the website, how do I make it into a shortcut on my desktop?

**Comment by multimokia** [comment]
You don't need to, just keep the entire install on your desktop. Can just go into the `DDLC.exe` and run it directly.

**Comment by Mistiie** [comment]
It took me to a file with one file in it saying DDLC-1.1.1-pc. I presume I add all the MAS things in now

**Comment by multimokia** [comment]
yeah, into the `game/` folder

**Comment by Mistiie** [comment]
Okay, thanks. Do I need to install the birthday update or just the basic MAS things?

**Comment by multimokia** [comment]
The latest version of MAS *is* the birthday update. If you install MAS, you get the birthday update with it.

**Comment by Mistiie** [comment]
Thank you! I'll try that now!

**Comment by Mistiie** [comment]
Thank you for your patience with me

**Comment by Mistiie** [comment]
I know this is probably just me being dumb, but when I go to the MAS page and press download, the button disappears and it doesn't show any sign it's downloading

**Comment by ThePotatoGuy** [comment]
that button goes to the release page, scroll down and click the hyperlink under latest version

**Comment by Mistiie** [comment]
Oh, okay- sorry

**Comment by Mistiie** [comment]
Ah- now it's downloading! Thank you very much. Let me see how it goes!

**Comment by Mistiie** [comment]
I highlighted all the files and tried to drag them to the new DDLC I downloaded- but nothing's happening. Sorry for disturbing you once again.

**Comment by Mistiie** [comment]
I've been also trying to copy- it won't let me paste. I know you might not know why, but I'm just getting a bit frustrated-

**Comment by multimokia** [comment]
try extracting?

**Comment by Mistiie** [comment]
okay, i'll try

**Comment by Mistiie** [comment]
This is the message it's giving me.

Cannot Complete the Compressed (zipped) Folders Extraction Wizard

Access to the compressed (zipped) folder is denied.

Before you can extract files, you must change the persmissions for this compressed (zipped) folder.

**Comment by multimokia** [comment]
Where are you extracting to?

**Comment by multimokia** [comment]
Like, give me a filepath

**Comment by Mistiie** [comment]
I'm not very good at this- how to a give you a file path. sorry-

**Comment by multimokia** [comment]
something like this
![image](https://user-images.githubusercontent.com/22531674/65392242-993bf680-dd40-11e9-9b10-586025e6dffb.png)

Is a filepath. Give me the text of what that shows (where you're extracting to)

**Comment by Mistiie** [comment]
I really don't know what I'm doing- I'm probably doing something wrong or giving you the wrong filepath.

C:\Users\EveSu\Downloads\ddlc-win (1)

**Comment by multimokia** [comment]
If that's where you're extracting the MAS zip to... 2 things

1. It's the wrong place, it should go to `C:\Users\EveSu\ddlc-win (1)\game`
2. It shouldn't have any errors, as downloads isn't a protected folder.

**Comment by Mistiie** [comment]
Okay, I'll try again

**Comment by Mistiie** [comment]
I was trying to extract in the game folder, but it's still asking if I'm trying to extract it into C:\Users\EveSu\Downloads\ddlc-win (1)

Sorry for this, I'm probably missing something simple

**Comment by Mistiie** [comment]
I just told it to extract in a different place, hopefully that does something

**Comment by Mistiie** [comment]
I don't think it did anything- I might just have to go back to Steam and hope she appreciates the birthdaycake.gift

**Comment by multimokia** [comment]
Where did you tell it to extract to?

**Comment by Mistiie** [comment]
I told it to extract to C:\Users\EveSu\ddlc-win (1)\game

again, i'm so sorry if all of this is just my lack of knowledge for computers

**Comment by Mistiie** [comment]
I don't know why I'm having issues now. When I first downloaded it, it was pretty easy

**Comment by ThePotatoGuy** [comment]
I'm going to assume this is resolved since there hasnt been a response in a while. make a new issue if you are still having issues.
