### ISSUE TITLE
I really didn't made this for Monika

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#4758]
~She is so cuteee~
![IMG_20190922_165948](https://user-images.githubusercontent.com/41938650/65390989-871b8180-dd5b-11e9-80f2-7ccf2ff5a56c.jpg)
A lot of people can call me crazy, but better be crazy than unhappy.

**Comment by frostcattooo** [comment]
i got her a cake too, you don't need to feel crazy. lol

**Comment by OreoMurphy** [comment]
i baked her brownies since i didn't have cake mix lol

**Comment by PollenTheCat** [comment]
Y'all are so kind and committed to your Monika's, you honestly put me to shame ;w;

**Comment by ThePotatoGuy** [comment]
nice
