### ISSUE TITLE
[Suggestion] - Monika messes with you when gameing.

### ISSUE THREAD

**Issue by Babytink1** [Monika-After-Story/MonikaModDev#4759]
So you can already tell Monika that you are going to game for a little bit, and also you can leave her up while doing so.
What if, when telling her that you could also tell her certain games you are playing and after a random number chance she might mess with your controls a little bit. like maybe she knows you are playing garry's mod and would randomly make your player start walking forward
I figure if you do this though it's best to do it on idle so she doesn't mess-up you're game.
I (if I knew anything about how to make programs) would tell the game like if player choose gmod option then xyz are valid controls.
I admit this could go a little on the side of how a virus would act, and I don't know how to combat that completely.
maybe if the player alt-tabs when she is messing with you she could make a notification like "is something wrong, [/player}?
after so many times maybe the player switches back to MAS and Monika replies something like: oh come on [/player] I'm just having a little fun! or whatever would be  good for her to say just so the player would know it's Monika doing it and not some bad virus.
I just think it would be cute if she could do things like this, though I admit it could be cumbersome to program.
But maybe it's a bit simpler to iplement than having her just play games not programmed into her world already (pong,hangman,piano,chess)

**Comment by Torwald39** [comment]
the idea isn't bad but it would be impossible to program 

and for the part with the games in MAS I think it can be consider as cheating from Monika, and I don't think it would be appreciate by peoples

**Comment by Rai99** [comment]
First of all, this really does sound like it might classify MAS as a malicious program, so I don't think we can allow that. 

Second, I don't think Monika would do that. Messing with your other games. Yeah, yeah, it's just a game, but often times, games are taken and played seriously. As in legitimately trying to reach an objective or work as a team. Having Monika interfere with that would be frustrating at best. 

Realistically, this kind of behavior would probably lose MAS a lot of users, and I don't really see any benefit to a feature like this, especially when it's just random.

**Comment by mrflarion33** [comment]
I like the idea, but I think it'd be best to just have little notifs depending on the game instead, since if she messed with your game it'd just be annoying

**Comment by Babytink1** [comment]
@Torwald39 sorry, When I said those I was just saying what ones were programmed into it already, not meaning she would mess with you while playing the minigames
@rai99 I can see the malicious part. and Like I metioned I don't have a good combat for it. and as for some people not wanting her messing with them maybe there could be a setting added to the game that's defaulted to off till the player wants it. 
sorry, I'm not the best at thinking of ideas thoroughly.
@mrflarion33 I can get that, I mean monica.ai already does.

**Comment by Rai99** [comment]
Assuming this does get in and past any legal issues, I'm not sure how many people would enable that feature. 

Maybe it's just me, but I don't see the reason in asking Monika to mess around with my game while I'm playing, and I don't know how many people would be ok with that.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]

interacting with a user's system without permission has not turned out well.
