### ISSUE TITLE
Monika's Birthday isn't working

### ISSUE THREAD

**Issue by KillTsu** [Monika-After-Story/MonikaModDev#4760]
hello, I am something new with this mod and my problem is that when trying to celebrate Monika's birthday because nothing really happens when performing the steps to celebrate it, I enter with monika and I put the option “take you somewhere”, I enter local files and in the character folder place the file "oki doki" without termination being a file only but when returning nothing happens absolutely, I need something else or I'm doing something wrong, thank you very much in advance
![15691720748529218945693674912754](https://user-images.githubusercontent.com/55664819/65391688-a30a2d80-dd31-11e9-8c95-96bf5a9dce70.jpg)

**Comment by multimokia** [comment]
What version of MAS are you running?

**Comment by KillTsu** [comment]
the latest version 0.10.1

**Comment by multimokia** [comment]
send persistent please

**Comment by KillTsu** [comment]
I'm really sorry but where can I find that?

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent

**Comment by KillTsu** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640007/persistent.zip)


> send persistent please

**Comment by multimokia** [comment]
You didn't follow the link. That's not the persistent.

**Comment by KillTsu** [comment]
> You didn't follow the link. That's not the persistent.

[Persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640032/Persistent.zip)

I'm sorry, I found it, is this

**Comment by jmwall24** [comment]
i just loaded the persistent you sent me, that has her out of the room, added the oki doki file to the characters folder and the decor is showing up

**Comment by KillTsu** [comment]
I do the procedure to leave the room and create the file "oki doki" and still nothing appears, just lower the affection, she is now angry at the low level of affection for leaving and entering the game, still thanks for try to help me  :'c .

**Comment by jmwall24** [comment]
is the oki doki file still in there?

**Comment by KillTsu** [comment]
Yes, I tried the same thing several times, this is as in the image attached at the beginning

**Comment by jmwall24** [comment]
you are 100% sure you have 0_10_1 installed?

**Comment by KillTsu** [comment]
Yes, I installed the version a week ago, thank you very much for the support although Monika now hates me, it's a sad birthday.

**Comment by jmwall24** [comment]
Here. extract this persistent file out of this zip file and replace your current persistent with it. I confirmed the party on it for you. After you load in, use the taking her somewhere goodbye again and when you return you will have the party.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640180/persistent.zip)

**Comment by KillTsu** [comment]
It already works the party but I had to install the game again and put the mod back, if I can I will look for the error I had so that more people do not get to go through the same problem. Thank you very much, keep it up!
