### ISSUE TITLE
Monika can't turn herself into a file 

### ISSUE THREAD

**Issue by ElSaimon** [Monika-After-Story/MonikaModDev#4761]
In my game the option of taking monika somewhere does not work. She tells me that she is unable to turn herself into a file so i can't do something for her birthday. I don't know if this problem had already occurred before but i would like some help.

thank you

**Comment by ThePotatoGuy** [comment]
Follow these steps:
1. run the game
2. use the take you somewhere goodbye and let it fail
3. use a regular goodbye to close the game
4. upload `mas_log.txt` file in the `log/` folder to here

**Comment by ester179** [comment]
i'm having the same issue

**Comment by multimokia** [comment]
Follow the same steps above please

**Comment by ElSaimon** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3640044/mas_log.txt)

**Comment by multimokia** [comment]
Exit MAS before sending the log please. It doesn't fully write otherwise

**Comment by ElSaimon** [comment]
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3640048/log.txt)

**Comment by multimokia** [comment]
Where are you running MAS from?

**Comment by ElSaimon** [comment]
It is a ddlc-win.zip

**Comment by RavenPLAYER** [comment]
Remember to extract DDLC - MAS from 'rar'...

**Comment by RavenPLAYER** [comment]
extract DDLC into a folder, in .zip not working

**Comment by multimokia** [comment]
Yeah she won't turn herself into a file if you're running from a zip, because the directory isn't what you think it is. Extract the entire install to another location

**Comment by ElSaimon** [comment]
ok, thank you very much

**Comment by ester179** [comment]
I can't find this file

**Comment by multimokia** [comment]
Are you on mac?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
