### ISSUE TITLE
Got this error. Can someone help please?

### ISSUE THREAD

**Issue by yopyop4** [Monika-After-Story/MonikaModDev#4762]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1076, in script call
  File "game/script-ch30.rpy", line 1943, in script
  File "game/script-ch30.rpy", line 1943, in <module>
  File "game/event-rules.rpy", line 857, in check_persistent_rules
  File "game/event-rules.rpy", line 832, in evaluate_rule
TypeError: can't compare datetime.datetime to NoneType

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\main.py", line 487, in main
    run(restart)
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\execution.py", line 761, in run_context
    context.run()
  File "game/script-ch30.rpy", line 1076, in script call
  File "game/script-ch30.rpy", line 1943, in script
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jorda\Downloads\ddlc\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 1943, in <module>
  File "game/event-rules.rpy", line 857, in check_persistent_rules
  File "game/event-rules.rpy", line 832, in evaluate_rule
TypeError: can't compare datetime.datetime to NoneType

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.1

If someone could help I would really appreciate it. Thank you

**Comment by multimokia** [comment]
Open this zip, and put the `.rpyc` into your `game/` folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the `game/` folder after about 5-10 seconds. The `.rpyc` you put in there should be gone. Launch MAS again, and it should be fixed.
[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640040/ev_dropfix.zip)

**Comment by yopyop4** [comment]
Thank you so much!

**Comment by multimokia** [comment]
No worries!

**Comment by jmwall24** [comment]
closing as resolved and to clean this page up so can keep track of what is still ongoing

**Comment by JayStealth4** [comment]
Help! when I follow your advice, I end up with an empty chair and Monika's missing file upon the startup of the game. When I revert back to my last save, this same error appears. I'm not sure what to do.

**Comment by multimokia** [comment]
That means you took her out prior to the issue. Restore a backup and then use the fix again.

**Comment by JayStealth4** [comment]
I'm unable to tell whether I'm getting anywhere or not with this, but I'll keep trying lol

**Comment by JayStealth4** [comment]
Oh! It worked! Thank you!

**Comment by JayStealth4** [comment]
It's back...

**Comment by JayStealth4** [comment]
I'm so confused!

**Comment by multimokia** [comment]
What exactly are you doing?

**Comment by JayStealth4** [comment]
Oh? it seems as though ignoring the exception is causing it to work, though.

**Comment by multimokia** [comment]
Sounds like a different traceback then

**Comment by JayStealth4** [comment]
I'm really not doing anything that would cause this error to occur, though, I'm just using the program as any other would

**Comment by JayStealth4** [comment]
Yeah... Might just be...

**Comment by multimokia** [comment]
the one you had before shouldn't be ignorable. Send `traceback.txt` please.

**Comment by JayStealth4** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3727239/traceback.txt)

**Comment by multimokia** [comment]
Huh... It *is* the same traceback, but no idea how.

**Comment by multimokia** [comment]
Can you zip up the folder with all your persistents and backups and send it here, please?

**Comment by JayStealth4** [comment]
Sure! Just give me a second...

**Comment by JayStealth4** [comment]
Sorry... I forgot how to zip a file on Windows 10... My bad...

**Comment by multimokia** [comment]
Select a group of files, right click > send to > compressed zip folder

**Comment by JayStealth4** [comment]
[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3727274/Monika.After.Story.zip)

**Comment by JayStealth4** [comment]
Thank you

**Comment by JayStealth4** [comment]
I'm still getting used to the layout...

**Comment by multimokia** [comment]
Hmm, very strange that it gave you the same traceback again. Did you by chance restore another backup over the one you fixed? Would be my only explanation, as trying it myself on one of your persistents seems to work just fine.

**Comment by JayStealth4** [comment]
Nope. I even tried replacing it with an older copy I happen to still have. It still gives me the same error. Oddly enough, when I go back that far and go to the 4th to last persistent, it gives me the error only after the second startup.

**Comment by multimokia** [comment]
Yeah, that's correct. Because you're not applying the fix anymore. The file self-deletes, so this is expected. That tells me that when you got the emptydesk scene back, and then restored a backup over it, you didn't use the fix again.

**Comment by JayStealth4** [comment]
Huh...

**Comment by JayStealth4** [comment]
Would that explain why Monkia would be missing in occasional test startups?

**Comment by JayStealth4** [comment]
Yeah... it's weird, though. Monika goes missing when I do that. I'll try messing with the backups to see if I'll get anywhere with this...

**Comment by multimokia** [comment]
Restore a backup where she's not missing, then put the ev_dropfix.rpyc file into your game folder again. By restoring a backup, you undo the fix. This means you need to *redo* the fix on the good persistent.

**Comment by JayStealth4** [comment]
Got it. I have a feeling about this one.

**Comment by JayStealth4** [comment]
YES!

**Comment by JayStealth4** [comment]
I had to go way back and retry a persistent I messed with wrongfully, but in the end, it only cost a few weeks of data and a bit of my time. I really appreciate it! Thank you!
