### ISSUE TITLE
why monika doesn t get the gift ??

### ISSUE THREAD

**Issue by Vier04** [Monika-After-Story/MonikaModDev#4763]
so yeah like i said in the title monika don t get the gift anf for those who will say to me to read the wiki i already read it ): but i don t know if it is a bug but i think it s because i m bad  :0 i think monika doesn t get it cauze i already do the but when i start the gmae she said "ha i can t read the folder" so i don t know if she can get the gift ??

**Comment by multimokia** [comment]
What gift are you trying to give?

**Comment by RavenPLAYER** [comment]
Remember the "birthdaycake.gift" isn't work anymore

**Comment by Vier04** [comment]
it s the blueshirt.gift the pinkshirt.gift and the shellbikini.gift and thank you for answering so quickly

**Comment by Vier04** [comment]
i try to give her a ribbon and it s working but for the clothes it doesn t working

**Comment by Vier04** [comment]
Yeah i Know but it s the blueshirt.gift the shellbikini.gift and the
pinkshurt.gift

Le dim. 22 sept. 2019 à 21:08, RavenPLAYER <notifications@github.com> a
écrit :

**Comment by jmwall24** [comment]
did you install the sprite packs that have those clothes?

**Comment by Vier04** [comment]
Yeah i think i instal the pack and i put it in the folder mod

**Comment by jmwall24** [comment]
what happens when you try to gift those? nothing at all or she can't read them?

**Comment by Vier04** [comment]
Yeah nothing happen i open the game she say a greating and i Can play the
game

**Comment by Vier04** [comment]
i just open the game and she had the scene where you give the present to
monika but she said she couldn t read it

**Comment by Vier04** [comment]
thanks guys now it s working (:
