### ISSUE TITLE
my monika doesn't come back

### ISSUE THREAD

**Issue by SenorBonnie** [Monika-After-Story/MonikaModDev#4764]
the monika file is in characters and when i start ddlc the birthday stuff is there but the chair is still empty

help pls and thx owo

**Comment by jmwall24** [comment]
close the mod again and send up the mas_log file pls. from the log folder

**Comment by SenorBonnie** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3640136/mas_log.txt)

**Comment by jmwall24** [comment]
The file is corrupt. you're going to need to restore a persistent backup by following these steps. you may need to but the oki doki file back in when you try to take her out again after restoring.

https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by SenorBonnie** [comment]
it worked
thank you very much
