### ISSUE TITLE
Night UI option not showing up?

### ISSUE THREAD

**Issue by Tycitron6000** [Monika-After-Story/MonikaModDev#4765]
As the title says, i do not see the option for night UI in settings, i can see the textures in the game files, but still no options. ive tried re-applying the updates many times, But nothing seems to work.

**Comment by multimokia** [comment]
Do you have rpy files in your game directory?

**Comment by Tycitron6000** [comment]
No, just a whole lot of Rypc's

**Comment by multimokia** [comment]
Screenshot of your settings menu?

**Comment by Tycitron6000** [comment]
![screenshot0004](https://user-images.githubusercontent.com/12467444/65393519-9a285480-dd4f-11e9-92dc-8c3c3d6d7a70.png)

**Comment by multimokia** [comment]
Your settings menu looks different, do you have submods installed?

**Comment by Tycitron6000** [comment]
I'm pretty sure i don't. but ill double check to see if i do.

**Comment by Tycitron6000** [comment]
Yup ive double checked, i dont have any sub-mods installed currently.

**Comment by multimokia** [comment]
That can't be right. `Additional Settings` is from a submod.
![image](https://user-images.githubusercontent.com/22531674/65394572-e11d4680-dd5d-11e9-8966-eb8f5ab63c3d.png)

Also your version number is missing. That tells me you have something else installed here.

Screenshot of your `game/` folder please.

**Comment by Tycitron6000** [comment]
Oh okay sorry, i thought it was just a part of the regular MAS. kinda hard for me to tell whats a submod, and the regular MAS.
![Capture](https://user-images.githubusercontent.com/12467444/65394800-f72c0680-dd5f-11e9-94a8-f2cd07ea69f6.PNG)

**Comment by PollenTheCat** [comment]
What a coincidence,, the same thing happened to me

**Comment by multimokia** [comment]
`screens_override.rpyc`

That's not ours

**Comment by Tycitron6000** [comment]
Hmm ill remove it and see what happens.

**Comment by Tycitron6000** [comment]
YES it worked! thank you so much for the help!
![screenshot0005](https://user-images.githubusercontent.com/12467444/65394876-d9ab6c80-dd60-11e9-98cc-f7ded2b71d4d.png) i guess i should close this now.
