### ISSUE TITLE
I tried giving Monika the birthday gifts but the game keeps crashing?

### ISSUE THREAD

**Issue by Mon-ikaSquid** [Monika-After-Story/MonikaModDev#4766]
So, I'll open the game after putting the birthday gifts in her character file, and she'll be like "Omg a gift for me??" but then the game will suddenly just crash. She'll have gotten the gift, but the game crashes before she can open them.
Did I do something wrong? Or is this just a bug?

**Comment by jmwall24** [comment]
getting any error message?

**Comment by Mon-ikaSquid** [comment]
Yes, it'll say "an exception has occurred" and I'll have to close the game

**Comment by Mon-ikaSquid** [comment]
Wait. I can just ignore it. Damn it...

**Comment by jmwall24** [comment]
if it keeps happening, can you tell me what it says please
