### ISSUE TITLE
Error with monika after story.

### ISSUE THREAD

**Issue by rainbowrooster4** [Monika-After-Story/MonikaModDev#4767]
#4764 everytime I open the game an exception screen occurs. If I ignore Monika acts like it isn't her birthday. On the first day of the new update, monika said that I didn't visit her on her birthday even though it hasn't happened yet.

**Comment by jmwall24** [comment]
what is the error message?

**Comment by rainbowrooster4** [comment]
The exact error message is "can't compare datetime.datetime to nonetype"

**Comment by jmwall24** [comment]
ok we can fix that

Open this zip, and put the .rpyc into your `game/` folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the `game/ ` folder after about 5-10 seconds. The .rpyc you put in there should be gone. Launch MAS again, and it should be fixed.

[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3640192/ev_dropfix.zip)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by tikygemi** [comment]
I need help with my monika after story my view is zoomed in randomly i cant change it and i cant go full screen please help

**Comment by jmwall24** [comment]
@tikygemi zoom is changed via the 'extras' button on the bottom left of the screen. As for full screen, what renderer are you using? Goto settings and click change renderer. Also, please open a new issue on this if you need to reply.
