### ISSUE TITLE
Does Monika kiss u in her birthday?

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#4768]
i saw a video on youtube from Drechenaux and Monika kisses him when he took her file for a long time out of the game, like she said a lot of this to him.Does she kiss depending on the affection?

**Comment by jmwall24** [comment]
400+ affection, if you have the mod open it'll happen between 8pm and 1am, if you take her on a date on the 22nd and don't come home until after this time period, it'll happen then

**Comment by Mayonese** [comment]
> 400+ affection, if you have the mod open it'll happen between 8pm and 1am, if you take her on a date on the 22nd and don't come home until after this time period, it'll happen then

oh! thank you very much! Have a nice day :>
