### ISSUE TITLE
[Suggestion] More "fun facts"

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4769]
I don't know why, but I think the "Curious facts" are somewhat ... abandoned? I mean, there are about +13 fun facts and they are all over. What they could do is investigate the internet looking for curious data, such as "Goats jump and run without stopping, but strangely, they also faint at the slightest provocation. The reason why it happens is because some types of goats share a congenital alteration recognized as 'Thompson's disease' in which the muscles contract absolutely and immediately when they panic, that is, when they hear or see something stressful, their muscles become completely paralyzed." And do not feel bad for laughing, when suffering this temporary paralysis, the goats do not suffer from any type of pain, in fact they do not lose consciousness at any time and will recover completely in about 10 seconds.

(I will upload another of these with several curious facts that you could add).

**Comment by multimokia** [comment]
There's more than 7, but now that they exist in their own event database, it's a lot easier to add more yourself. See `script-fun-facts.rpy`

**Comment by RavenPLAYER** [comment]
But it doesn't make sense if I do it, the idea is that everyone can see it. I could add something like "more fun facts.rpyc" and upload it for others to download, only if they want, of course ...

**Comment by Rai99** [comment]
So like a submod for custom fun facts?

**Comment by multimokia** [comment]
The idea is to contribute to the mod so *everyone* gets them.

**Comment by multimokia** [comment]
I don't see why you'd submod them (unless they're completely unfitting)

**Comment by RavenPLAYER** [comment]
It's just because they repeat and repeat, anyway... it was just an idea...

**Comment by Rai99** [comment]
If you ask me, I'm just waiting for the PR backlog to start clearing up a bit before I go clogging it up even more.

**Comment by fromulus** [comment]
Actually, while we're on that topic...
Would it be possible to add the fun fact topic to the random pool of topics ?
I never really understood why it wasn't in the first place.
It's already a fairly extensive topic with a lot of variations, and not one that wouldn't make sense to repeat every once in a while either.
It'd be a really simple way of adding a lot of variation for people who have Monika on repeat topics, I'd like to think.

**Comment by HenryKhan** [comment]
uuh, what about the [player] to tell "fun facts" to Monika? that could be stored somehow and used  in the next updates.
I don't know if that could bring more (unecessary)work to you guys but... it's just an idea.

**Comment by HenryKhan** [comment]
yeah precisely...

**Comment by ThePotatoGuy** [comment]
closing this as its a general "add more of x" statement. suggestions should be concrete.
