### ISSUE TITLE
Can't give Monika gifts

### ISSUE THREAD

**Issue by ElectroSfere** [Monika-After-Story/MonikaModDev#4770]
I tried giving her some clothes (shell bikini, hairclips, etc) but after a few failed attempts, she stopped recognizing there was a .gift file. I named everything properly and had all the files in the correct locations, but after failing twice she just doesnt see it anymore. Any fix?

**Comment by multimokia** [comment]
Did you install the spritepacks?

**Comment by ElectroSfere** [comment]
> Did you install the spritepacks?

Yeah i installed both the monika and thumb folders under Doki Doki Literature Club > Mod_Assets

**Comment by multimokia** [comment]
Screenshot of the `game/mod_assets/monika/j` folder please?

**Comment by ElectroSfere** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/54016284/65395739-3ce6d000-dd5c-11e9-8bc1-9eecd9762050.png)

**Comment by multimokia** [comment]
That's not where `mod_assets` goes. It should be inside `game/`

**Comment by ElectroSfere** [comment]
is there two separate mod_assets that are named the same, one under Doki Doki Literature Club and one under game? i never made a second one

**Comment by multimokia** [comment]
There should only be one. The one inside `game/`

**Comment by ElectroSfere** [comment]
so its safe to delete the DDLC/ one?

**Comment by multimokia** [comment]
Yes

**Comment by ElectroSfere** [comment]
Ok thank you so much!

**Comment by ElectroSfere** [comment]
she still doesnt recognize them even in the proper file location

**Comment by multimokia** [comment]
You have to wait until tomorrow.

**Comment by ElectroSfere** [comment]
Ok, again thank you

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
