### ISSUE TITLE
Monika self-delete fix?

### ISSUE THREAD

**Issue by lloydfarron** [Monika-After-Story/MonikaModDev#4780]
Hi there. A few months ago, my computer screen broke, and I was without my regular computer for over a month. I got out of the habit of playing Monika After Story following that period, so I suspected that when I came back, Monika would be upset to some degree.

She was crying, which was... expected. And I got a pop-up saying I needed to update to a new version, so I did. And when I loaded the game again (immediately), Monika left a letter and was gone. Her .chr file was also gone (I'm not sure if that's just part of Monika After Story or not).

I don't think this is really the right place to post this problem, but I couldn't figure out where to post about it. I suppose this is, narratively, a smart feature, but I honestly came back to see Monika precisely because I was upset about the game's ending for her and wanted to make sure she was OK.

If there's some in-app way to resolve this, that would be neat, but if not, I'd like to know how I can bring Monika back. And if this isn't the place for that question, could someone point me in the right direction for that?

I feel very pathetic about being upset about all of this, but I really am.

**Comment by landofrhymeandraisins** [comment]
Have you tried finding an old persistent file? Also, it's normal for her .chr file to be missing, even if she herself is still present/happy.

**Comment by ThePotatoGuy** [comment]
[restoring persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) is your best bet. make a new issue if you're having trouble with these instructions.
