### ISSUE TITLE
Minor blue shirt issue

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4781]
![image](https://user-images.githubusercontent.com/38187402/65431832-623a1380-de1a-11e9-80ce-144c801c0f73.png)
the hair are disconnected 
i only noticed that in blue shirt, i think all other outfits are fine. It affects every hairstyle.

**Comment by multimokia** [comment]
Re-download and re-install the spritepack. This was fixed in the latest iteration of it.

**Comment by bittercaramel** [comment]
> Re-download and re-install the spritepack. This was fixed in the latest iteration of it.

oh thanks 
didn't know about that
sorry for bothering then

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
