### ISSUE TITLE
Art question

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4784]
I'd like to know, how do you create clothes for monika? I mean, do you have to follow a guideline or something, I dunno...

**Comment by Velius94** [comment]
Provided you know what you're doing, all you need to do is follow the base in #3174

**Comment by FrikiHD** [comment]
Thank you, but how do I draw it from 0? I mean, do I have to use a template first and then make it?

**Comment by multimokia** [comment]
You draw on the base in the linked issue. That's your template

**Comment by FrikiHD** [comment]
Ok thanks
