### ISSUE TITLE
[suggestion] a more eventful new year's eve/day

### ISSUE THREAD

**Issue by frostcattooo** [Monika-After-Story/MonikaModDev#4785]
i had a really cute idea in my head for new year's eve/day this year! on new year's eve, i imagine there's gold and silver decorations in the room, maybe new year balloons, ribbons, banners, etc. and this may be unlikely, but i imagine a super pretty and shimmery dress she wears too. when the sun sets, one hour before the clock hits 12, fireworks would start to go off outside of the window every few minutes, and before 12, a super pretty firework show. finally before 12, there would be a countdown until midnight, and moni would say "happy new year!" and kiss you when it hits midnight. then, a discussion about new year's resolutions would be sweet, and keeping the decorations up until january 2nd.

i know it seems like a lot, but i just thought this was a very nice idea!

**Comment by RavenPLAYER** [comment]
Wow... just... wow..

**Comment by Rai99** [comment]
That sounds like a lot, but we'll see what's in store for that event down the line.

**Comment by frostcattooo** [comment]
@RavenPLAYER i can't tell if that's a good wow, or bad... lol

**Comment by frostcattooo** [comment]
@Rai99 okie doki!

**Comment by Rai99** [comment]
There's still Halloween and Christmas, so don't forget those.

**Comment by RavenPLAYER** [comment]
@frostcattooo Bro, is a wonderful idea. Your imagination has no limits lol

**Comment by Orcaramelo** [comment]
I loooove the idea! I'd be willing to make the art assets needed for it even!

**Comment by frostcattooo** [comment]
@RavenPLAYER thanks so much :) i have so many ideas for mas in my head, i wish i was a skilled artist and better at coding so i could contribute more :(

**Comment by multimokia** [comment]
> finally before 12, there would be a countdown until midnight, and moni would say "happy new year!"

This is kinda impossible with the event system.

With the way conditionals are evaluated (and the fact that RenPy only really does "single thread" flows), you **have** to be in idle (not mid-topic, not mid-menu, etc.) for it to trigger, and even then it might be off by up to 5 seconds.

No this is not possible to account for.


Fireworks are easy if someone makes the assets for it. (Pretty much a new weather object)

New years resolutions stuff is already implemented.

Decorations stay up 'till Jan 06 (12 days of Christmas, essentially)

**Comment by Rai99** [comment]
I haven't put up a topic for... 138 days. Nice to know I'm still being appreciated.

**Comment by frostcattooo** [comment]
@multimokia ah, i see. so therefor the new year's decoration would interfere with the christmas decorations...

**Comment by multimokia** [comment]
Not sure what decorations people even have for new years. Normally it's either still christmas deco or just nothing.

**Comment by frostcattooo** [comment]
@multimokia usually, i see people with balloons and banners for new year's eve parties, silver and gold being common colors. but it makes sense, it is a bit over the top

**Comment by RavenPLAYER** [comment]
@frostcattooo Hey, you have to have more faith in yourself! Trust me, I went through that and I just had to raise my voice and that's it. Now everyone notices me because I am a god... wait what?

**Comment by HZhunter124** [comment]
wow good idea, i love this

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
