### ISSUE TITLE
[suggestion] Discord Server

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4786]
Since discord is really useful for projects and stuff, you could create one where you can announce updates, or talk with people and there can be suggestion channels, art channels...

**Comment by multimokia** [comment]
We have one... It's linked in the readme of this repository

**Comment by Rai99** [comment]
There _is_ a suggestion channel, but it's probably not what you expect.

**Comment by FrikiHD** [comment]
Wow, never saw it
But I can't find it, where is it?

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev#join-the-conversation

**Comment by FrikiHD** [comment]
Ok, thanks
