### ISSUE TITLE
 Notifications

### ISSUE THREAD

**Issue by MikiMwk** [Monika-After-Story/MonikaModDev#4787]
my notifications are weird, they look like this instead of the phrase

https://prnt.sc/pa301z

**Comment by MikiMwk** [comment]
Does anyone have a solution?

**Comment by antimockingjay** [comment]
I had this for a bit, but then it eventually just went away on its own. I'd suggest restarting your computer, aka the universal off-and-on-again, and see if that helps.

**Comment by antimockingjay** [comment]
I'd also recommend turning off notifications then turning those back on as well.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
