### ISSUE TITLE
I still can't give gifts to Monika

### ISSUE THREAD

**Issue by DezelV** [Monika-After-Story/MonikaModDev#4788]
Ok so, i don't know if it's just my incompetence but I still can't give gifts to Monika. Like hair clips, clothes and such. I would really appreciate it if any of you could help me. Also, I'm in the unstable version, could that be a cause for this issue as well?

**Comment by ManuEcheveste** [comment]
Also, there are gifts that aren't in the original mod, like the Blue Shirt, Pink Shirt, Shell bikini, etc. They are Sprite packs.

**Comment by DezelV** [comment]
Yeah I have been give them in .gift but she still can't read them, I downloaded the sprite packs too and they are in their proper files

**Comment by multimokia** [comment]
Screenshot of your characters folder please.

**Comment by DezelV** [comment]
Actually, I just tried to gift her a hair clip and it worked! Idk what changed but it's fine now, sorry for bothering you all
