### ISSUE TITLE
[suggestion] thanking monika

### ISSUE THREAD

**Issue by frostcattooo** [Monika-After-Story/MonikaModDev#4793]
it's quite a simple concept, but i think it would be really nice to thank her. after she says something comforting (ex: after you tell her you're feeling sad, angry, after she talks about you being bullied or being depressed, etc) there would be a "thank you" option in the talk menu. i just want her to know that her care is appreciated. i know that we can tell her "thank you for being here for me", but i just think that this is an extra little touch to let her know that what she said was acknowledged and appreciated.

**Comment by MetalBrother** [comment]
It was brought many times in other suggestions. Rai99 I chose you!

**Comment by Rai99** [comment]
Original dupe chain for thanking Monika, but I think this is slightly different. 
#2024, #2450, #4263 

There's already that one compliment, and I think that covers most cases for thanking Monika, but maybe there could be just a generic "Thank you" for fun or whatever people would want to thank her for.

**Comment by satoshi-kun** [comment]
I find that suggestion really good. The same way that when the "I love you, too" option was added (which by the way I don't think it needs a comma), it brought another layer of interactivity that I found just great for the mod. This suggestion seems to follow the same line and all in for it!

**Comment by dxguann** [comment]
Was about to write a suggestion about this. I agree. Is my birthday and I really wanted to thank her.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
