### ISSUE TITLE
Sprite arm issue

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4794]
Not sure if this is known yet, so I'm posting this here. Just noticed this coloring was a bit *out of line* today.
![698dcc9f497e92c193ab9aeb5bcd313f](https://user-images.githubusercontent.com/36512990/65644848-05c22a00-dfbb-11e9-8c5a-13444c31aac2.png)

**Comment by PollenTheCat** [comment]
I just looked in the files and it's _arms-right-restpoint-1_

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
