### ISSUE TITLE
Aff_log is nowhere to be found

### ISSUE THREAD

**Issue by PaperPlate1** [Monika-After-Story/MonikaModDev#4796]
The "Log" folder in the DDLC game directory is empty and nothing can be found upon searching "aff_log.txt". I am playing on v0.10.1 (via Steam for Mac) and I just can't seem to find the solution to this issue. Any suggestions/response would be much appreciated!

Thank you.

**Comment by multimokia** [comment]
This was moved a long time ago because of Mac's file permission issues.

See [this entry on our wiki page](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#how-to-view-your-affection).

**Comment by PaperPlate1** [comment]
Ah, thank you very much! Must have glanced over that one. Thanks for the swift response! 👍
