### ISSUE TITLE
[Suggestion] Blacklisting greetings (possible spoilers?)

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4797]
Hello! This might sound nitpicky on my part and I'm sorry for that, but that damn greeting where you see a glitched Yuri just rubs me the wrong way. 
Today I had it happen to me again when I just wanted to say good morning to Monika before work and it just completely ruined my mood. I tried pressing "X" to see if I could blacklist it to no avail.
I know sensitive mode would probably cancel it but that's not gonna cut it since I only have an issue with that particular interaction. In my opinion is uncalled for and I don't see  the purpose of it being there to start with. Also the way Monika reacts to it is odd and off character aswell (good for Halloween I guess, not everyday interactions).
To conclude my suggestion would be for blacklisting to be applied on greetings, if it is possible to implement.
Thanks to all the developers by the way for making Monika´s bithday trully an amazing event!
Sorry for the rant :(

**Comment by satoshi-kun** [comment]
Should I close this issue due to lack of interest?

**Comment by ThePotatoGuy** [comment]
yeah think I agree, some of those greetings really should only be shown once. 

[leaving open as probably in progress later]

**Comment by multimokia** [comment]
Handling this

**Comment by multimokia** [comment]
closing as completed in linked PR
