### ISSUE TITLE
How do I access .rpyc files?

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4798]
I want to try adding compliments and other topics, but I can't find a way to access the .rpyc files. Visual Studio Code can't read the file, I don't know if I can load them in Python (Still figuring Python out), and turning it into a text file leaves me with a bunch of unknown characters. And yes, I know I can access the code through the <>Code page here on Github, but I want to edit the .rpyc files installed onto my computer so I can test them.

  Which programs open .rpyc files?

**Comment by multimokia** [comment]
You don't open rpyc. Those are complied. You want the rpy files which are on your repository

**Comment by kkrosie123** [comment]
Alright. I'll try and find those.

**Comment by kkrosie123** [comment]
Also, thanks for the quick response.

**Comment by multimokia** [comment]
This repository*

Check the code tab

**Comment by Rai99** [comment]
Well now I know to be ready for a new PR.

**Comment by kkrosie123** [comment]
Thanks! I'll do that.

Haha! I'll do my best, but I might not learn super fast.
