### ISSUE TITLE
[Suggestion] Telling Monika where you live

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4808]
So, as it says in the title, telling Monika where you live, meaning where you live in the world. It can just be her asking you which continent you live in since there are only 7 and that's it. You don't need (and frankly shouldn't have) to go deeper into her asking which country you live in because there are SO MANY countries. So yeah, that's my suggestion. Have a nice day!!

**Comment by Rai99** [comment]
#2505, #2953, #3804, #4020 

Continents might be a way to keep things general enough.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
