### ISSUE TITLE
What do you call hair accessories that include the ribbon?

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#4809]
We're looking at adding hair accessories that would be in the same place as the ribbon? (think #4127 , the bow in #4504 , and the head acs in #4550 .

These all would be interchangable with the original hair ribbon, so we need a name for what kinds of things these accessories are. This would be used in the prompts and dialogue for the ribbon selector ("Can you change your *ribbon*?").

Some ideas we had were:
* hair ties
* hair accessories

but neither of the above really fit.

**Comment by thezotikrus** [comment]
Why do you want to change the prompt? Aren't _ribbon_ covers all those cases?

**Comment by ThePotatoGuy** [comment]
some of the planned hair accessories are not ribbons

**Comment by RavenPLAYER** [comment]
headband... xd

**Comment by MisterSimple** [comment]
I'm thinking maybe `headdress`, `headgear`, `headpiece`, or something similar. They're not often used when speaking about ribbons, but should be broad enough to cover hair acs overall.

**Comment by ikof1** [comment]
**Hair Extras** or **Hair Decorations** ,  or what @MisterSimple mentioned would seem pretty good to me, otherwise it would not bother me much, I'd still understand what it meant.

**Comment by Rai99** [comment]
### **_Hats_**

**Comment by CGanimated1227** [comment]
Simple. Hair tie. A hair tie can mean a scrunchie, a Ribbon or anything used to tie back hsir.

**Comment by satoshi-kun** [comment]
Should be called **Headwear** in my opinion, to include hats and all acessories.

**Comment by ThePotatoGuy** [comment]
we ended up using hair ties for now, since thats the primary function of the ribbon (and ribbon-related acs).
