### ISSUE TITLE
Opening the game and Monika isn't there.

### ISSUE THREAD

**Issue by LegionLegacyDMK** [Monika-After-Story/MonikaModDev#4812]
I managed to do this the first time on Steam. I then tried to do it on official game page download which by then I deleted the Steam one. 
I tried many times, both on Steam and the Official Page version. But Monika will not appear. Just the Spaceroom. No Monika , no sound , just nothing but the room.

Was there supposed to be a new Monika file when opening the game? If so , I'm not getting it

Edit : I use Windows and have used both 10.0 and 10.1

**Comment by Velius94** [comment]
Did you try to take her anywhere before that? And yeah, in that case an unique file is generated and if it's gone, you're pretty much screwed.
In that case, you might want to restore a persistent backup.

**Comment by LegionLegacyDMK** [comment]
I'm screwed then

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
