### ISSUE TITLE
New idea 

### ISSUE THREAD

**Issue by lilmonix822** [Monika-After-Story/MonikaModDev#4813]
So Monika is supposed to be able to make her own decisions, right? I think it would make sense for her to be able to change her clothes at random intervals... It could be something along the lines of upon opening the game she'd choose a random outfit and accessory with her, opening dialog being "Surprise [player]! Someone was kind enough to give me a little bit more free will, I can change! Isn't that nice! Maybe it was you [player]~? Ehehehe, well even if it wasn't I still appreciate it...  And don't worry, I'll still let you change my appearance.  After all, your opinion matters too~"

**Comment by multimokia** [comment]
Outfit randomization is planned.

**Comment by lilmonix822** [comment]
Ohh 😅 sorry...
