### ISSUE TITLE
Can't gift the blue shirt, the pink shirt, nor the bikini

### ISSUE THREAD

**Issue by Lepisc-Cloud** [Monika-After-Story/MonikaModDev#4814]
Basically title, i put everything in their proper files from the sprite packs. Used .gift files to gift to her but she can't read it, I've been trying for the past few days help pls :( But I did manage to gift the accessories like the flower and the hair clips for example.

**Comment by multimokia** [comment]
Screenshot of your `mod_assets/monika/j` folder please, including filepath.

**Comment by Lepisc-Cloud** [comment]
![Json files](https://user-images.githubusercontent.com/56007916/65927212-c20a5e80-e3c6-11e9-89e0-a045d4590fd7.png)

**Comment by multimokia** [comment]
Okay, send `spj.txt` (in the `log/` folder)

**Comment by Lepisc-Cloud** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3673966/spj.txt)

**Comment by multimokia** [comment]
So, looks like you copied the jsons, but not the image files

**Comment by Lepisc-Cloud** [comment]
And how does my dumb self copy those? lol

**Comment by multimokia** [comment]
Just copy the `mod_assets` folder from the spritepack you want to install, then paste it in `game/`. It'll merge with the `mod_assets` folder we ship with the mod and everything will be placed correctly.

You will be prompted to replace files (the jsons), just replace and it'll be good.

**Comment by Lepisc-Cloud** [comment]
All right thank you very much :)

**Comment by multimokia** [comment]
No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
