### ISSUE TITLE
[Suggestion] - 'I love you, too' after 'looove yoou' greeting

### ISSUE THREAD

**Issue by thezotikrus** [Monika-After-Story/MonikaModDev#4816]
Don't see a reason why not. We kinda caught her off guard, let's make her blush a little.

```
label greeting_visit4:
    m 1hub "I looove yooou, [player]. Ehehe~"
    m 1hksdlb "Oh, sorry! I was spacing out."
    m 1lksdla "I didn't think I would be able to see you again so soon."
    return "love"
```

**Comment by satoshi-kun** [comment]
I like this suggestion! But shouldn't the comma be removed? It doesn't appear to be correct. "I love you too" is enough, the comma isn't doing anything there.

**Comment by jmwall24** [comment]
Good catch, that should indeed have it.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
