### ISSUE TITLE
Can't find the "can you change the weather" option.

### ISSUE THREAD

**Issue by bondrewd623** [Monika-After-Story/MonikaModDev#4817]
I was told that it'd be by the "Hey Monika > Weather > Can you change the weather?" as I've already unlocked the "Sounds of rain" option since it's located in the Repeat Conversation section. There's a chance that it's not there because my affection is at -23ish (due to having to leave because of depression) but I'm not sure... 
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3678006/persistent.zip)
It didn't let me attach my persistent directly so I had to zip it, sorry for the inconvenience...

**Comment by multimokia** [comment]
Option unlocks at 100 affection.

**Comment by bondrewd623** [comment]
Thank you so much! I'll take a while but I'll get there one day again!
