### ISSUE TITLE
[Enhancement] - Contrast of buttons in night mode

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#4818]
It's kinda difficult to tell if the options under the dialogue box are activated or not during night mode.
![Capture](https://user-images.githubusercontent.com/38837456/65991004-f0eb0800-e48c-11e9-95f8-92b1b7a8b33a.JPG)

**Comment by Velius94** [comment]
Will do some tuning to the nightmode color scheme later on, but no concrete ETA.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Velius94** [comment]
#4887
