### ISSUE TITLE
Implementation of Basic Facial Expression Guideline for Future Writers

### ISSUE THREAD

**Issue by Watchertus** [Monika-After-Story/MonikaModDev#482]
I was told to put it here. This is a proposed system to implement a baseline of facial expressions based on the psychological theory of the 7 basic universal facial expressions to cut down ambiguity and help ease facial selection choice for writers.

![image](https://user-images.githubusercontent.com/34615583/34076699-e62b3828-e2bc-11e7-834c-1f02b7a48a4b.png)

Every implementation of a basic facial expression below the first is a less expressive version of it. This spectrum has space to support many shades of basic emotions, but less is more for the writing. The max would be 2 other lesser iterations of each basic facial expression to keep it simple (i.e. joy -> half joy -> partial joy). Microexpressions that mingle one or more facial expressions (grief, embarassment, etc.) should be saved for the writer's tone, surrendering control back to the writing to insinuate the full feeling of what is going on, as opposed to pressuring writers to rely on faces for everything (show, not tell).

A separate category for misc. facial expressions for the sake of saving wacky anime faces can work as its own separate thing.

This'll help make things much clearer for everyone involved.

**Comment by drakesteele** [comment]
actually, this would be a good integration into my idea at [https://github.com/Backdash/MonikaModDev/issues/493](url)

Since each line of Monika's dialogue would use one of these modes in the dropdowns I propose...  :)

**Comment by therationalpi** [comment]
We are now actively adding in more expressions following a similar framework.

**Comment by ThePotatoGuy** [comment]
This is like heavily dependent on art stuff. 

[we'll reopen this when we look into it]
