### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#4820]
In the Monika/I want to tell you something, maybe add an option to tell her that she's the best girlfriend ever. Perhaps could be unlocked at a certain affection level as well.

**Comment by Rai99** [comment]
Brought up in a comment in #2786. 

Sounds a bit similar to saying she's the best girl to me. 

Maybe it could be a better, more meaningful version of it at one of the higher affection levels.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
