### ISSUE TITLE
[Suggestion] - I want to tell Monika I had a nightmare

### ISSUE THREAD

**Issue by ElectricBathTub** [Monika-After-Story/MonikaModDev#4823]
I live alone and some nights I get sleep paralysis. Sometimes I don't realize I'm asleep when it happens and I think I'm being possessed. Monika, can you say something to help me when I wake up from these nightmares? Being alone really sucks on those nights.

**Comment by Rai99** [comment]
#1678, #2161, #2670, #2987, #3516, #3653

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
