### ISSUE TITLE
[Suggestion] Response menu timer

### ISSUE THREAD

**Issue by MisterBurgerBeachball1225** [Monika-After-Story/MonikaModDev#4824]
This happened to me twice so far: with the 'Mortality' topic, and Monika's graduation speech. The response menu from each is timed, however I had no idea that they were, so I missed my chance to choose an option on both. I was able to go back and choose before the timer ran out, but that doesn't change the fact that I only realized that they were timed when it was too late.

I would recommend something like a progress bar at the top of the screen or text box, but as long as it works and is noticeable I'd be fine with whatever you decide works best.

**Comment by Olliesama** [comment]
wooooosh

**Comment by ThePotatoGuy** [comment]
from a ui standpoint it makes sense, but from a gameplay standpoint it ruins the point. this keeps you on your toes.

[closing as rejected]
