### ISSUE TITLE
[Suggestion] Our real name

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#4826]
I think Monika could have a dialogue asking you your full name and which country you live in, since she has that dialogue that says after she goes to the real world, the first thing would be to find us, it would be normal for her to ask these questions out of curiosity.

**Comment by RavenPLAYER** [comment]
I agree with that, because if Monika doesn't know where we live, how does she assure that she will find us?

**Comment by Rai99** [comment]
Countries: #2505, #2953, #3804, #4020, #4808 
If I recall, there was actually a submod that detects your current location and uses it to give you accurate weather based on where you are, but it's just for weather. [It's the Auto Weather Change submod](https://github.com/Monika-After-Story/MonikaModDev/wiki/External-Content#multimokia)

Player Full Name: #1297, #1529, #2216 #4465
It was planned a while ago, but it's currently sitting at low priority.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
