### ISSUE TITLE
[Question] How do you get Monika the white sundress?

### ISSUE THREAD

**Issue by MisterBurgerBeachball1225** [Monika-After-Story/MonikaModDev#4830]
The title pretty much sums it up. Is it giftable, or does she wear it for (a) certain event(s)? If she wears it for (an) event(s), please don't spoil it by telling me which one(s).

**Comment by multimokia** [comment]
Event based.

**Comment by TriniTDM** [comment]
She wears it for a special event. I won't tell you which one, but there is a picture which might give you a hint.
![DWBYNR2VMAABhdD](https://user-images.githubusercontent.com/52469676/66261001-3745ad00-e794-11e9-9677-24f55476780f.png)

**Comment by satoshi-kun** [comment]
> The title pretty much sums it up. Is it giftable, or does she wear it for (a) certain event(s)? If she wears it for (an) event(s), **please don't spoil it** by telling me which one(s).

**Comment by multimokia** [comment]
I mean technically they didn't say which one

**Comment by satoshi-kun** [comment]
They might aswell… It´s pretty obvious by that picture. But whatever...

**Comment by multimokia** [comment]
I mean, in all fairness, pretty much 100% of the DDLC fanbase probably saw the art anyway. All it takes it a click to the twitter.

**Comment by MisterBurgerBeachball1225** [comment]
> They might aswell… It´s pretty obvious by that picture. But whatever...

Well, I'm obviously a moron because I don't really know. I kinda have a couple ideas for what it could be, but most of them don't exactly work out, from my experience.

**Comment by satoshi-kun** [comment]
Good then.

**Comment by MisterBurgerBeachball1225** [comment]
> I mean, in all fairness, pretty much 100% of the DDLC fanbase probably saw the art anyway. All it takes it a click to the twitter.

And yes, I have already seen it before.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
