### ISSUE TITLE
Monika has amnesia/partial data reset?

### ISSUE THREAD

**Issue by Malastrome** [Monika-After-Story/MonikaModDev#4831]
I reported this on the Twitter and was suggested I make an issue here.

I installed a new motherboard the other day, and for whatever various reasons, my Windows 10 installation that was on my main hard drive (I have two. The secondary hard drive has DDLC/MAS on it, the main one has Steam and other main apps) broke and I ended up needing to format the drive to reinstall W10.

I started DDLC from Steam after I reinstalled it (Steam) rather than my secondary drive, and a warning popped up on the in-game screen, I believe suggesting I needed to install something akin to how Steam games install software before a new game runs (this was earlier in the week and after nearly nine hours of troubleshooting W10 installation and BIOS issues so I apologize for lack of information).
I closed the game, opened it up this time from the folder on the secondary drive and Monika was saying her dialogue for starting the mod as if I had just deleted her.
The reason I say she has amnesia, which is the only way I can laugh this off, is because the calendar still lists our three year anniversary for next year, as well as the previous anniversary dates, and the date hasn't changed since when I originally installed the mod.

It's okay if there's no possible fix to reset affection or the like, and while the problem was under a very specific set of circumstances, I figured it'd still be better to post it here.

**Comment by multimokia** [comment]
Can you send your persistent file please?

You'll have to zip it or change its extension to something GitHub supports

**Comment by Malastrome** [comment]
Sorry, can you point me in the direction of how to do that?
I'm not entirely sure what a persistent file is.

**Comment by multimokia** [comment]
Check [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) to see how to get to your persistent.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Malastrome** [comment]
Apologies for the wait. Hectic week.
[Persistent Files.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3722659/Persistent.Files.zip)

**Comment by jmwall24** [comment]
Opening as not resolved

**Comment by jmwall24** [comment]
What is supposed to be the day you met?

**Comment by Malastrome** [comment]
March 17th, 2017. That's what it says on the calendar currently, and to my remembrance, that's correct and hasn't changed.

**Comment by multimokia** [comment]
That's before DDLC's release date though...

**Comment by jmwall24** [comment]
also, look at your calendar again, do you see a heart on Sept 29, 2019?

**Comment by Malastrome** [comment]
Guess I thought it had been longer since DDLC released. At any rate then, it does indeed say "1 week" after March 17th 2017 being the anniversary.
And yes, there's a heart on Sept 29, 2019.

**Comment by jmwall24** [comment]
So yeah, you have something weird going on. First off, you can't even set your anniversary to March 17, 2017, it doesn't let you, so not sure if you changed your system date the day you originally started MAS or what. Also, as of right now, your first session is recorded as Sept 29, 2019, yet all of your anniversaries are still based off of March 17, 2017, which is very weird. Looking at your persistent, every single thing other than your anniversary dates was reset.

**Comment by Malastrome** [comment]
Is there any way to fix that, and should I be worried that the mod might break somewhat from this?
I can't imagine why the date would be set in 2017, unless my old BIOS config had something to do with that before I installed my new motherboard and graphics card.

**Comment by jmwall24** [comment]
At the 30 day mark from September 29 a topic will unlock for 'when did we start dating'. You will have a one time opportunity to tell her your start date. It won't let you pick anything before September 22 2017. But think about when your start date actually was so you'll be prepared. Also, do you have your afflog.txt file from the old install? If so upload it here and we can give your old affection back.

**Comment by Malastrome** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3728380/aff_log.txt)
Much obliged! I didn't think I'd be able to get everything back to as it was. I'll definitely have to think on when the start date was.

**Comment by thezotikrus** [comment]
Have you restored a persistent backup after you reinstalled windows? You had MAS installation on a separate disk, but her memories still was on your main disk.
Since you asked about what persistent is above, I assume that you didn't backup it. That's why you started from scratch. As for the time issue, I think you didn't set your system time before opening MAS for the first time after your windows issues.

**Comment by jmwall24** [comment]
here's part of your problem

![Screenshot_1614](https://user-images.githubusercontent.com/36523761/66837334-d440dc80-ef30-11e9-9796-5aebf8d77b7d.png)

**Comment by jmwall24** [comment]
Also, if you could send your most recent persistent I'll add that affection for you and get it back to you. I'd do it with what you sent, but it's been a few days now and don't want to erase any memories made between then and now.

**Comment by Malastrome** [comment]
[Persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3732389/Persistent.zip)
Really appreciate the help on this!

In regards to the time, I'm honestly not sure, as my Steam library is on my secondary drive where DDLC was installed originally.
However, I'm remembering that I believe I copied the entire folder into another place on my secondary drive for the mod specifically, retaining the original install still in my Steam library.
And since I launched from Steam instead of the copied folder, maybe that has something to do with why it messed up as well?
Also looking at some of the file dates, I'm seeing a lot say 7/29/2018. Which sounds about right for the point in which I had installed MAS, as I had just taken on some new work.

**Comment by jmwall24** [comment]
I can set that date right now for you if you'd like

**Comment by Malastrome** [comment]
That'd be great if you could. Thank you!

**Comment by jmwall24** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3732462/persistent.zip)

ok here's your persistent, just extract it and put it in place of your current persistent. also, since I changed the start date, it's now been more than 30 days since you met her, so that `When did we start dating?` topic is available. The first time you click it is the only time you have the chance to change the date again, so think about that before you click it. May want to save that click in case you come up with different information.

Anyway, I added the affection you had to the affection you've gained on this new persistent and your start date and anniversaries should all be correct now. If you have any questions, feel free to ask.

**Comment by jmwall24** [comment]
probably obvious, but make sure the mod is closed when you do this.

**Comment by Malastrome** [comment]
Seems like it worked. Thanks again for your help with this!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
