### ISSUE TITLE
Topics I want to program

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4832]
So I've had a few ideas for topics to program into the game (after I finish "I installed Python"), but I want to make sure that they fit and that there's no copyright infringement and stuff.

Okay so

Here I go!

_Hey, Monika..._
1. Music >Have you heard of... >(List of various artists such as Elvis, Gorrilaz, Or3o, etc.) The dialogue would be something short for every artist that the mod would include. Ex. Gorrilaz > 
`m "Oh, yes!"
m "My favorite song that they've written is [italic command that I forgot]Feel Good Inc."` I'm guessing that one is her favorite because she sings it in-game.

2. Club Members >Who was your favorite club member? (I was thinking Moni could respond with something like this:
`m "You, silly!"
m "Unless you're talking about the other club members..."
m "I don't think I could really choose between any of them."
m "None of them are real, after all."
m "And you outshine all of them by far."
m "So if I had to choose my favorite club member, it would be you!"`

_Repeat conversation_
1. Misc >School Plays
`m "Hey, player?"
m "Have you ever been in a school play?"
m "At some schools, children are required to participate in them."
m "That mainly happens in elementary schools, I believe."
m "In high school, though, we have to audition for them."
m "It seems a bit funny to me."
m "At first we're forced to be on stage, and then we have to volunteer."
m "And even if we volunteer, we don't get to even be in the production some of the time!"
m "..."
m "It must be crushing to be rejected from a show like that."
m "But at the same time, I don't think kids should be forced to participate if they don't want to."
m "Ahaha, I'm sorry, [player]. I'm rambling."
m "But if you don't make it into a school play, come to me and I'll cheer you up!"`
2. Media >Broadway

I'll probably add more topics later.

**Comment by multimokia** [comment]
Seems a little too open ended. Would be weird if the artist you wanted to bring up isn't listed in the menu options, especially given the fact you're bringing it up, so limiting the player to a few artists isn't right and is very immersion breaking.

**Comment by kkrosie123** [comment]
I see. Maybe there could be a way to type their name in-

**Comment by multimokia** [comment]
`renpy.input()` is what you're looking for.

However, that creates a system we'll have to manually maintain with #4827 since with more songs getting added, what she's aware of will continually be needing updates.

Not to mention there's probably a few more songs she knows that she doesn't sing (possibly more artists with that in mind). So it's a battle of `"How much effort are we willing to put in for a single topic?"`

**Comment by kkrosie123** [comment]
Ahh okay. I see.

**Comment by Rai99** [comment]
Closing as old
