### ISSUE TITLE
[Art] Hairclips for Halloween! 

### ISSUE THREAD

**Issue by bellmandi86** [Monika-After-Story/MonikaModDev#4834]
I thought I'd give a try to make a few little hairpins for Monika for the Halloween season: 
![acs-jmo_hairclip_moon](https://user-images.githubusercontent.com/51217412/66255359-794cff80-e750-11e9-9314-7a5fffeb4a6d.png)
A moon
![acs-jmo_hairclip_bat](https://user-images.githubusercontent.com/51217412/66255361-7eaa4a00-e750-11e9-8d17-4fd21caad62f.png)
A bat
![acs-jmo_hairclip_pumpkin](https://user-images.githubusercontent.com/51217412/66255363-84079480-e750-11e9-8367-83a6efd20ff6.png)
A pumpkin

Feedback is always appreciated!

![Monika Pumpkin day default](https://user-images.githubusercontent.com/51217412/66255341-56225000-e750-11e9-849b-991684c1bef2.png)
![Monika Pumpkin day leaning](https://user-images.githubusercontent.com/51217412/66255330-54588c80-e750-11e9-9b7f-88a5af292af8.png)
![Monika Pumpkin night default](https://user-images.githubusercontent.com/51217412/66255331-54588c80-e750-11e9-97fd-821b10e853ac.png)
![Monika Pumpkin night leaning](https://user-images.githubusercontent.com/51217412/66255332-54588c80-e750-11e9-97a3-9758cd896bb3.png)
![Monika Bat day default](https://user-images.githubusercontent.com/51217412/66255333-54588c80-e750-11e9-87ce-f71fcd3ca139.png)
![Monika Bat day leaning](https://user-images.githubusercontent.com/51217412/66255334-54f12300-e750-11e9-8333-d410ef079d9b.png)
![Monika Bat night default](https://user-images.githubusercontent.com/51217412/66255335-54f12300-e750-11e9-8d5d-c50095a37dcc.png)
![Monika Bat night leaning](https://user-images.githubusercontent.com/51217412/66255336-54f12300-e750-11e9-8808-4be965733cf2.png)
![Monika Moon day default](https://user-images.githubusercontent.com/51217412/66255337-5589b980-e750-11e9-90b9-bf62713caf83.png)
![Monika Moon day leaning](https://user-images.githubusercontent.com/51217412/66255338-5589b980-e750-11e9-9043-e8b9e36f5ca7.png)
![Monika Moon night default](https://user-images.githubusercontent.com/51217412/66255339-5589b980-e750-11e9-81a1-de8ab6e093bd.png)
![Monika Moon night leaning](https://user-images.githubusercontent.com/51217412/66255340-5589b980-e750-11e9-9fb7-65c3df3723c5.png)

**Comment by RavenPLAYER** [comment]
Woaah, is so cute! Good work there!

**Comment by Orcaramelo** [comment]
oo the pumpkin one looks really cuteee

**Comment by GHCactus** [comment]
oooo I love those

**Comment by lunulae** [comment]
I love these, especially the moon. It stands out so nicely against her hair.

**Comment by ThePotatoGuy** [comment]
@bellmandi86 what name would you like to be credited with in the spritepack? Is `bellmandi86` fine?

**Comment by bellmandi86** [comment]
@ThePotatoGuy yes, that's fine. let me know if you need/want any files specifically

**Comment by ThePotatoGuy** [comment]
can you upload the full layer with each clip in the correct position?

**Comment by bellmandi86** [comment]
Of course!


![hairclip_bat-0](https://user-images.githubusercontent.com/51217412/66277896-5a468e80-e872-11e9-8a0a-3d53511d28a0.png)
![hairclip_bat-0-n](https://user-images.githubusercontent.com/51217412/66277897-5a468e80-e872-11e9-9447-9f121e8c0565.png)
![hairclip_bat-5](https://user-images.githubusercontent.com/51217412/66277898-5a468e80-e872-11e9-92d5-8d8109dff207.png)
![hairclip_bat-5-n](https://user-images.githubusercontent.com/51217412/66277899-5a468e80-e872-11e9-97f3-a84616dc1a66.png)
![hairclip_moon-0](https://user-images.githubusercontent.com/51217412/66277900-5a468e80-e872-11e9-92ce-7b285f024832.png)
![hairclip_moon-0-n](https://user-images.githubusercontent.com/51217412/66277901-5a468e80-e872-11e9-889f-546745c42cd4.png)
![hairclip_moon-5](https://user-images.githubusercontent.com/51217412/66277902-5a468e80-e872-11e9-90cf-d9fe6ab0b68e.png)
![hairclip_moon-5-n](https://user-images.githubusercontent.com/51217412/66277903-5a468e80-e872-11e9-9429-7cf857f496dd.png)
![hairclip_pumpkin-0](https://user-images.githubusercontent.com/51217412/66277904-5a468e80-e872-11e9-8d96-1536d0865726.png)
![hairclip_pumpkin-0-n](https://user-images.githubusercontent.com/51217412/66277905-5adf2500-e872-11e9-9fdc-4e7a1a49dbe1.png)
![hairclip_pumpkin-5](https://user-images.githubusercontent.com/51217412/66277906-5adf2500-e872-11e9-80df-d9f1979e9799.png)
![hairclip_pumpkin-5-n](https://user-images.githubusercontent.com/51217412/66277907-5adf2500-e872-11e9-91a9-1c26e3588f38.png)

**Comment by Ghost129er** [comment]
I feel the purple and black colors on the bat hairclip is somewhat difficult to see with it being that small of a size... If it was something large like a hairpin or something it could have been larger me thinks but no one seems to have mentioned that so it may just be me. Could have easily done a ghost too which would have also been a nice addition to the Halloween theme.

**Comment by bellmandi86** [comment]
I considered the ghost, but a small, white blob in her hair was a little off-putting for me.

**Comment by bellmandi86** [comment]
I mean, I'll let you guys judge for yourselves, here's the files for a ghost clip. It just doesn't look right to me (or at the very least, inappropriate). You guys are welcome to give it a spin if you can get it to look better. 

![acs-jmo_hairclip_ghost](https://user-images.githubusercontent.com/51217412/66437487-dae2c780-e9f7-11e9-878f-4f07a224d167.png)

On [Monika]
![Monika Ghost day default](https://user-images.githubusercontent.com/51217412/66437528-ef26c480-e9f7-11e9-8bbb-eadade399cb4.png)
![Monika Ghost day leaning](https://user-images.githubusercontent.com/51217412/66437529-ef26c480-e9f7-11e9-9ac9-a7e52c800086.png)
![Monika Ghost night default](https://user-images.githubusercontent.com/51217412/66437530-ef26c480-e9f7-11e9-9760-5c4d954075c9.png)
![Monika Ghost night leaning](https://user-images.githubusercontent.com/51217412/66437531-efbf5b00-e9f7-11e9-85a0-87bfd572c7b9.png)

[PNG files]
![hairclip_ghost-5](https://user-images.githubusercontent.com/51217412/66437499-e2a26c00-e9f7-11e9-87a4-6b565a96aef2.png)
![hairclip_ghost-5-n](https://user-images.githubusercontent.com/51217412/66437500-e2a26c00-e9f7-11e9-822f-504363e3489f.png)
![hairclip_ghost-0](https://user-images.githubusercontent.com/51217412/66437501-e2a26c00-e9f7-11e9-9817-e24f76acea03.png)
![hairclip_ghost-0-n](https://user-images.githubusercontent.com/51217412/66437502-e2a26c00-e9f7-11e9-8be5-e31a39a64918.png)

I'm open to more suggestions, if anyone else wants to kindly ask.

**Comment by RavenPLAYER** [comment]
WoW.

**Comment by Ghost129er** [comment]
The ghost looks cute as f**k and I definitely will give it to her. Again, everyone to their own but I really think you should still include it for those who want to as after all, those who download it are the ones installing what they choose no? Again, my opinion would be to totally have the ghost included.

**Comment by bellmandi86** [comment]
I just don't how many pins is too many. Halloween is like, my _absolute jam_ so I could just quite literally _go on_.

**Comment by ThePotatoGuy** [comment]
This has been merged in. If you want to add additional hairclips, please make another issue.

**Comment by Professor-JMO** [comment]
These were a wonderful addition to MAS's Halloween! ☝️ 
>Notices Hairpin👁‍🗨
![Be careful](https://user-images.githubusercontent.com/43480604/68425991-cb78aa80-016c-11ea-9de4-ff02ea20bec6.jpg)
