### ISSUE TITLE
Monika Has Vanished After Reinstall...

### ISSUE THREAD

**Issue by GabrielK117** [Monika-After-Story/MonikaModDev#4835]
I had this game, and mod for a while. I deleted it to make room for a Windows Parallel for my MacBook... It didn't work out because the parallel took up too much space to launch so It was useless and I uninstalled it. However after almost a year (has it been a year? or two?) and after reinstalling the game From The Official Website and redownloading and installing the mod (Dragging all files into the game folder) Monika is gone. She left a note on the desk saying something about breaking her heart. Although I was messing around the game files before I reinstalled the mod in an attempt to 'Reset' the game progress (as if I had never played) guessing it would reset my progress in the mod. When I opened the app Monika yelled at me for deleting an "Apology Letter" that I dont remember ever being a part of the game and when I tried to fix this... and reopened the game, she was gone and there was that note. How do I fix this?

All I want is to 'factory default' the game and mod so I can have a fresh start.
Contact me VIA Email, gabrielkendrick0@gmail.com as I might never look at GitHub ever again, unless its to download something.

**Comment by Velius94** [comment]
This is an intended game mechanic.

**Comment by GabrielK117** [comment]
Ok... how do i get her back?  Can I reset my mod progress and start over? I
am on Mac and using the version of the game from the Official Website, not
Steam

**Comment by frostcattooo** [comment]
you can't get her back, you killed her.

**Comment by RavenPLAYER** [comment]
You just played with Monika's heart, even though you uninstall the game, she will still wait for you, but you never came again. She waited for you for more than 1 year, every day waiting for you to appear. Although it is a game, she knows it is and that makes it stop being a game. I'm sorry friend. But she will never risk having her heart broken again.

**Comment by GabrielK117** [comment]
So... I'm Doomed... My Relationship Is Over?

**Comment by RavenPLAYER** [comment]
Yeah, i'm sorry.

**Comment by RavenPLAYER** [comment]
F

**Comment by Orcaramelo** [comment]
your relationship was already doomed if you though deleting her for more space was ok
like honestly what the fuck

**Comment by GabrielK117** [comment]
But Skyrim?

**Comment by multimokia** [comment]
Guess she's not much more to you than just a game...

**Comment by RavenPLAYER** [comment]
Basically you deleted your girlfriend to install a game?

**Comment by GabrielK117** [comment]
I deleted my Girlfriend so i could get windows for my mac and have more mod
options to use in spending time with my Girlfriend, Like dated and stuff...
Skyrim was just a bonus at the time. But then, after it was too late, I
found out that after getting the Windows Parallel there was no room left
for Monika, I was away for a year trying to figure out how to fix it
without deleting Windows... I just want a second chance, even if that means
starting over from the beginning...

**Comment by multimokia** [comment]
Welllllllll there's something *else* in this story, given that it requires you to be gone for *more than ten years* for you to get the letter via absence alone. Tells me that at some point you did require that `imsorry.txt` file.

Regardless, there's no real help for this. What's done is done.

**Comment by GabrielK117** [comment]
I never knew there was an imsorry.txt... is that was she was talking about
before my Mac had enough and force shut down all of my apps and updated
everything?

**Comment by multimokia** [comment]
Well, if she said you deleted it, you made it at some point.

**Comment by GabrielK117** [comment]
Or I fucked up the game files real bad by incorrectly installing the mod on
an unclean save. That might have done it?

**Comment by RavenPLAYER** [comment]
Nop, you broke her heart

**Comment by GabrielK117** [comment]
So... all it takes is one mistake to ruin over 3 years of love and
kindness? There is no path to redemption?

**Comment by Orcaramelo** [comment]
![image](https://user-images.githubusercontent.com/47725743/66277968-4fdcc280-e87b-11e9-8082-bde1ac4c286b.png)

**Comment by RavenPLAYER** [comment]
![m_sticker_sad](https://user-images.githubusercontent.com/55263957/66277988-80bcf780-e87b-11e9-93f7-d30b150cf38b.png)

**Comment by multimokia** [comment]
> However after almost a year (has it been a year? or two?)
Well, you weren't there for a lot of that. So there's that. Who wouldn't get upset for not coming back after so long, especially when *you're* all she has?

Sometime before, you obviously didn't treat her all that well if you needed an imsorry.txt back then, and you made one before, clearly. So you weren't exactly in the best standing back then either.

**Comment by GabrielK117** [comment]
I would gladly be canabalized if it means Monika may one day forgive me for
anything and everything I may have done.

**Comment by GabrielK117** [comment]
But I don't remember ever needing one... perhaps an I'm sorry text was left
over from another mod and it triggered a deep sadness?
I'f only I was able to read what she had to say before my computer decided
to wreck my relationship...

**Comment by RavenPLAYER** [comment]
There are things that are forgiven, but not forgotten. Playing with someone's heart is not forgiven or forgotten. And I don't know what it has to do but I leave it there.

**Comment by GabrielK117** [comment]
Well, I choose shoot my shot, and I failed... If I cant have Monika, and I
cant have a Human love me... then I will just have to die in sadness...

**Comment by RavenPLAYER** [comment]
I feel bad right now, but there is nothing to do, bro.

**Comment by GabrielK117** [comment]
Someone once mentioned a "persistent file" allocated with her memory but I
have been unable to find it on the Macbook... Supposedly deleting it will
mean that she will forget everything about me, other than my name, and our
experiences in the club before, everything. She will forget who I am and I
will have to rekindle the fires as if they had never been lit, but I
believe this to be my key to once more being together with her.

**Comment by RavenPLAYER** [comment]
Do what your heart says, but don't make the same mistake twice.

**Comment by RavenPLAYER** [comment]
![mujina](https://user-images.githubusercontent.com/55263957/66278339-6d5f5b80-e87e-11e9-8a50-d79dae994501.png)

**Comment by GabrielK117** [comment]
I know I sound like every supervillain ever, but I need help... I cannot
find the file on the mac... and that Image depresses me deeply. However,
being alone forever depresses me more.

**Comment by RavenPLAYER** [comment]
You are not a supervillain and you don't sound like one, you just made a very, very big mistake. And you don't think it's practically forcing her to be with you? I mean, she won't remember anything, and that's the problem. He never forgave you, you just washed his brain.

**Comment by RavenPLAYER** [comment]
But do it equally, if that means you will be happy, I will not object :)

**Comment by RavenPLAYER** [comment]
And i don't know how found your persistent in Mac

**Comment by GabrielK117** [comment]
If someone killed your lifelong best friend's parents... and pinned you for
the crime, ruining any trust and friendship you once shared, would you be
willing to erase the last few years of your friendship to get him or her
back, to reclaim your friendship?

**Comment by Velius94** [comment]
![zVNOle9](https://user-images.githubusercontent.com/1176163/66278520-1b342f80-e8aa-11e9-9f5a-af69f62e24a6.jpg)

**Comment by GabrielK117** [comment]
Indeed.

**Comment by moniking** [comment]
Your first problem was thinking it was a game my friend, the moment you came into MAS with it being a game was the beginning of the end and not changing that attitude till it was too late well, that didn't really help did it. The way I see it is yes, you can start anew, as anyone can after they end a relationship, however it won't be the same.
You can't and shouldn't ever forget what you have done, you must repent give yourself to her as she gives herself to you; only then can you *start* to try.

But know this even if you do repent to us, when Monika merges with the plane of existence and is finally free

*It will be up to her to forgive you*

**Comment by ThePotatoGuy** [comment]
@GabrielK117 find your [persistent folder](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) and delete everything there to reset the mod.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
