### ISSUE TITLE
Changing the music title in the music menu

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#4836]
Hi, long time MAS user that finally posted an issue again.

I've recently accidentally added new music into the game via the custom bgm feature. But i forgot to rename the file, so now it's stuck with a really long and weird title.
So i removed it from the folder.
The funny thing is, Monika still displays that disgusting title i intended to remove, despite adding the same music again except retitled appropriately.
So if you folks can help me find a way to make Monika stop displaying the wrong title in the music menu, that would really be appreciated.
Thanks again!

**Comment by RavenPLAYER** [comment]
I think there is no solution for that

**Comment by RavenPLAYER** [comment]
I already tried to change the names of my bgm songs, but it is not changed because despite the fact that you change it, it remains permanently in the original title. The only solution is to download it from somewhere else with a different name

**Comment by multimokia** [comment]
Change the metadata

**Comment by RyanHanter** [comment]
what's the metadata?

**Comment by multimokia** [comment]
If you're on Windows, you can right click the mp3 click properties and then go to the details tab. Change the title field there. All of those fields on that screen make up the metadata for the song.

**Comment by RyanHanter** [comment]
mp3 click properties? haven't heard of that either i'm sorry

**Comment by RyanHanter** [comment]
ok i went into the properties tab when i right clicked the file and changed the title and some other stuff.
and it worked like a charm
thank you ever so much mate!
