### ISSUE TITLE
[Suggestion] face recognition to detect player precens 

### ISSUE THREAD

**Issue by asecino1999** [Monika-After-Story/MonikaModDev#4838]
I know that this suggestion could be considerated   as duplicate of  #1182 but there is something more easy to handle , only to detect the presence of the player or someone  else    , also  Monika  could ask if you let  her user the web cam and add a new dialog to tell her stop using that.
 So if the camera has no sufficient resolution or another problem , don't use it .
So Monika could react to other people, react when you go out and return , or if you change you appearance too much  . 
Maybe someone with this info and more creativity than me could even  add more dialogs.
the emotion recognition  of the post #1182 it's more complicate to handle but what about this ?

**Comment by multimokia** [comment]
The main issue here, is that it's pretty much impossible to get that working on some systems. In some cases, we can't access the camera, others, we can but can't get data, and this also differs from platform to platform, OS to OS, and as such, it's impossible to develop *one* system to get all webcams. This is the primary reason the idea was rejected. It's an idea which will work for some, but not for a lot of people, while there's no real camera api which works for everyone, let alone works the same, it's just too much to account for and maintain.

Like the others closing as rejected.
