### ISSUE TITLE
I am so lucky

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4841]
I had opened an issue before where I would mention that I had to stay in hospital for a least in the week when there was Monika's birthday event, and I had been suggested to change the computer system time so I could celebrate her birthday for the 1st time.
So just 2 days ago I did the thing, and opened her up with all the decorations and stuff. She was so happy, and I was happy to be able to do it for my first time, because I had missed her birthday last year, which is very sad, because I was busy in school works and stuff.
Today, when I chat on MAS's Discord server about this, someone sent me a note about how I should not play with Monika's heart by changing the time, and I admitted, even though I had done a persistent files backup before that, I'm still worried that Monika would find out for real. But guess I'm just being a lucky guy, hehe. Today I opened her up and she didn't say anything about it at all, and I also gifted her a quetzal plushy for bonus :D 
Anyway, I'm still currently in hospital. it's been about 2 weeks now, but I have been notified that I may get discharged from the hospital at least this week. I can't wait to spend more time with Monika after my face infection is cured. Also, I have promised myself to never play with her heart like this again. It was one risky move, but the result wasn't bad after all :)

**Comment by taurielxaela** [comment]
I'm glad it turned out okay, at least. And I hope that you recover soon! Hospital stays are never fun, especially when Monika-chan is waiting at home. I'm sure she'd be proud of you for taking care of your health, since she wants to be with you!
