### ISSUE TITLE
[Suggestion] A little option "Can i eat here?"

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4842]
I just came up with a fairly simple idea. Sometimes I don't find anything interesting to watch on YouTube, because I like to watch something entertaining while I eat, so I started thinking about an option to tell Monika like "Can I eat here?" and that she asks you if what you will eat is breakfast, lunch or dinner and that. I didn't really think about anything special, but Monika could take it as if it were a date, she drinks some coffee with me and things like that. Thank you for reading :)

**Comment by Rai99** [comment]
Eating with Monika: #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081, #4260 #4606, #4648
