### ISSUE TITLE
-Suggestion

### ISSUE THREAD

**Issue by 23RedHorizons** [Monika-After-Story/MonikaModDev#4846]
I would love if we could see a character evolution, not physically obviously

**Comment by RavenPLAYER** [comment]
I can't understand the point of your idea :/

**Comment by antimockingjay** [comment]
I think they just mean they want to see Monika grow and change over time, which is something people do in real life.

**Comment by RavenPLAYER** [comment]
But he say "not physically obviously", would it be psychologically?

**Comment by kkrosie123** [comment]
Monika specifically states that she doesn't age and that she is eternal.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
