### ISSUE TITLE
I can't give Monika a present

### ISSUE THREAD

**Issue by wwwwwAzimax** [Monika-After-Story/MonikaModDev#4847]
Everything was done according to the instructions, but Monica still can not read the file. How can this be fixed ?
![Новый точечный рисунок](https://user-images.githubusercontent.com/54619793/66473884-5dcc5680-eaba-11e9-8991-7ac7da377220.jpg)
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3706815/spj.txt)

**Comment by jmwall24** [comment]
can you send that spj.txt file when you have the mod closed. the file doesn't completely write with it open.

**Comment by wwwwwAzimax** [comment]
> вы можете отправить этого spj.txt файл, Когда вы закрыли мод. файл не полностью записывается с ним открытым.

[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3707111/spj.txt)

**Comment by thezotikrus** [comment]
Just a guess.. You are using a translated version of the mod, aren't you? If so, maybe this can cause that error?

**Comment by jmwall24** [comment]
Are you running a translated version of the mod and does that version have these sprite packs hard-coded in? If you are running a translated version, you'll need to seek help with whoever did the translation, as they have changed the code and we don't know what they did. Every pack in that spj file says the accessory already exists, which isn't possible unless that accessory is also hard-coded in.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
