### ISSUE TITLE
ily2 for Attractiveness Topic?

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4848]
Hello! I'm using v0.10.1-unstable.2019.09.18.106, and I have question regarding to ily2 for a topic.

The topic is Repeat conversation > Club members > Attractiveness. Actually, this topic has Monika saying 'I love you' although it's not in her end statement (it's right before her last statement actually. Second to last? I don't know the right term for it). Here is the screenshot of her saying 'I love you' in that topic.

![screenshot0019](https://user-images.githubusercontent.com/44340452/66481096-5745db00-eaca-11e9-9f96-fe081528bc5f.png)

But once I click 'Talk', the 'I love you!' button doesn't change into 'I love you, too!' button.

Is this intended?

Thank you. Have a nice day!

**Comment by jmwall24** [comment]
On the fence on this one. We omitted it on purpose initially but are rediscussing internally.

**Comment by skyloom** [comment]
@jmwall24 thank you for your answer! Should I leave this topic open or will it be better if I close it?

**Comment by multimokia** [comment]
Best leave open until we decide so that can be tracked

**Comment by multimokia** [comment]
closing as completed.
