### ISSUE TITLE
Sweater for monika

### ISSUE THREAD

**Issue by moniking** [Monika-After-Story/MonikaModDev#4852]
Heya, I've been working on this outfit for a hot minute and wondered if you think it could be used.

I figured a nice warm sweater for Monbon would be good :)
(What's that? Her shoulders are exposed so it really wouldn't help? Well I say it's animu art so shhhh)

It probably ( most likely) needs some work from your main art doods like shading and such, I'm not that good at it sorry.

![upright sweaterbase2](https://user-images.githubusercontent.com/42454179/66564426-948b8680-eb25-11e9-9d0c-6ccd67d44e94.png)
![upright sweaterbase](https://user-images.githubusercontent.com/42454179/66564427-948b8680-eb25-11e9-9400-fa82a2f18ed2.png)
![upright sweaterbase3](https://user-images.githubusercontent.com/42454179/66564428-948b8680-eb25-11e9-9593-216493e9866c.png)

**Comment by Orcaramelo** [comment]
Oooo i really love the concept!
Those hand on the secod pic are unused tho
I dont even know where one of them came from
You seem to have only non updated sprites, did you paint that on a different layer so that you can transfer it over to new sprites?

**Comment by Orcaramelo** [comment]
But that shading has amazing placement, its very nice!!!
Would you mind sending us the .sai/.psd file so we can make touch ups?
Are you on the discord server?

**Comment by moniking** [comment]
-Oooo i really love the concept!
Those hand on the secod pic are unused tho
I dont even know where one of them came from
You seem to have only non updated sprites, did you paint that on a different layer so that you can transfer it over to new sprites?-

 I figured I would make sweater separate so it can be edited easily
By the team if they need to, and I used the peace pose just cause I wanted too.

-But that shading has amazing placement, its very nice!!!
Would you mind sending us the .sai/.psd file so we can make touch ups?
Are you on the discord server?-

You really think it's that good? I was actually worried about the shading most. Thank you though!
As for discord, I'm not part of it but I have discord so ill join and give you the files :)

**Comment by moniking** [comment]
I joined, where do you want me to give them to you?

**Comment by moniking** [comment]
Oh and before anything else, I didn't come up with the outfit idea just altered it and made a version for mas.
The original belongs to George flay who I think sadly quit working on his project.

**Comment by Orcaramelo** [comment]
I'll be on artistry!! Lemme ping you

**Comment by GHCactus** [comment]
Ohhhhh looks really cute!! I love it so far!!!

**Comment by moniking** [comment]
GHCactus thank you! I handed it over to orca and I can't wait to see the final version :)

**Comment by moniking** [comment]
While he does that I'd like to work on some other designs however several have been done I know like the black dress, and pink and blue shirts, so need to make sure I don't work on anything already worked on.

**Comment by frostcattooo** [comment]
oh my god i love this, you did really good! im sure with your great art, and orca's touch ups, it'll become even cuter <3 i've always wanted more long sleeves for moni, especially sweaters :)

**Comment by Orcaramelo** [comment]
update! sorry for the long wait until i started work!
most of the progress has been working to blend in what was blurry! i really like the shading so i'm keeping all of it, mostly just doing touch ups! Tho there seem to be some transparency holes i'll have to be looking out for!
![image](https://user-images.githubusercontent.com/47725743/66683835-d5cb8580-ec4e-11e9-83df-2e5ebf5efa80.png)

**Comment by frostcattooo** [comment]
looks super cute so far !!!

**Comment by Orcaramelo** [comment]
thank you so much! im so excited for this tbh, because this sweater is just so cute,,,

**Comment by frostcattooo** [comment]
it really is, sweaters on moni are adorable.

**Comment by Orcaramelo** [comment]
![uprightbase sweater](https://user-images.githubusercontent.com/47725743/66693534-4b037e80-ec80-11e9-8d0c-97bd21c04beb.png)
still have to touch up down arms, crossed arms and leaning, but i added some texture to it!
so, 6 arms and a body, ooooof 
i'm gonna sleep now its pretty late luv yall

**Comment by moniking** [comment]
My goodness, it's gorgeous!!
You made it ten times better, love it!! ❤️v❤️


And yeah I thought it looked amazing when I played our time so I had to remake it for MAS, i was also working on the black dress but that's already been done better than I could. 

I want to work on the pajamas next so Moni has something nice and snuggly to sleep in but I don't know if anyone else is working on some, if they are I'll do something else I have in mind.

As for transparent holes... Sorry I'll check better next time hehe 😅

**Comment by moniking** [comment]
frostcattooo thank you, I'm glad you like it~<3

**Comment by frostcattooo** [comment]
awwh it looks so so nice, and of course @moniking <3

**Comment by Rin3105** [comment]
I love the sweater so much! When is it gonna come out as a downloadable clothe sprite?

**Comment by GHCactus** [comment]
Ahhhh that's so cuuute

**Comment by Orcaramelo** [comment]
I keep color matching the body of the sweater, but i thinks that's been worth it! I finally finished upright, will start work on touching up leaning soon! But that's gonna take a while since leaning looks a quite messy
![uprightbase sweater](https://user-images.githubusercontent.com/47725743/66709061-9d9d7300-ed32-11e9-9b01-9019db9cf1d4.png)

**Comment by Orcaramelo** [comment]
![uprightbase sweater](https://user-images.githubusercontent.com/47725743/66718136-d97a1c00-edb6-11e9-93f6-e570edcef07e.png)
its finished yall! thank you so muh monikinf for the sending me the file <3, i love this concept so much tbh, i hope i honored the project lol

**Comment by frostcattooo** [comment]
aa i love it so much! when do you think it will be available as a sprite pack?

**Comment by Orcaramelo** [comment]
I hope it comes on next spritepack update bc i really love it
Also vel's shirt skirt combo
And simon's bikini 👀

**Comment by frostcattooo** [comment]
yeah me too. i love all of those sm

**Comment by moniking** [comment]
Honored it? You knocked it out of the ballpark! Sorry the leaning was messy, I will try harder on the pajamas 💪😤

**Comment by satoshi-kun** [comment]
Pajamas!? :O
*Looses his sh#@" ;D

**Comment by taurielxaela** [comment]
Monika in a sweater makes my heart so happy! Both the original and touched-up versions look so cute!!Thank you both for working on this~
I would definitely put my Moni in this sweater so she can be comfy and warm~

**Comment by moniking** [comment]
@taurielxaela thank you❤️ I'm glad I could help out and make something people like.

**Comment by moniking** [comment]
@satoshi-kun yes p.j's! They are my current project and I am excited as it seems like a widely desired outfit.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
