### ISSUE TITLE
[Suggestion] Topic: "I Miss you!"

### ISSUE THREAD

**Issue by zephobear** [Monika-After-Story/MonikaModDev#4853]
I want to be able to tell Monika "I miss/missed you(too?)" like the "I love you" thing somehow since she kinda says it quite a bit.

Additional: 
Telling her your feeling frustrated.
Telling her you're actually depressed instead of just sad.
Pretty sure I had more in mind, but that's it for now I guess...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
