### ISSUE TITLE
How do I use the spritesheets?

### ISSUE THREAD

**Issue by moniking** [Monika-After-Story/MonikaModDev#4855]
I'm re-posting cause my stupid self put spreadsheets and not spritesheets *-*

Anyway can someone please tell me how?

**Comment by multimokia** [comment]
Are you trying to add sprites?

**Comment by moniking** [comment]
Yes, the pink and blue shirts, hair flower, etc

I read they are treated as gifts or something similar since they give affection however I don't know how to integrate them.

**Comment by multimokia** [comment]
Sprite *packs*. Big difference.

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs

**Comment by moniking** [comment]
Oh...... Sorry hehe...

I goofed again it seems,
Thank you.

**Comment by moniking** [comment]
I've put the files where they belong so all I need to do is gift the outfits and accessories normal right?

**Comment by multimokia** [comment]
Yeah. Assuming you haven't already tried to gift them today. If you have, try again tomorrow

**Comment by multimokia** [comment]
Read the readme in the spritepack fonder

**Comment by moniking** [comment]
I see, I'll try it and if it doesn't work I'll figure it out :).
Thank you again.

**Comment by moniking** [comment]
Update! It worked so thank you ~<3
