### ISSUE TITLE
[Suggestion] mythological histories

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#4860]
Monika could tell us about some mythological stories, like the one of Perceu and Medusa, Izanagi and Izanami and etc, and in the end give the opinion about the history, or about the action of the gods during the history (since as she herself said said some take advantage of humanity and she doesn't like it) or tell a curiosity of mythology

**Comment by GHCactus** [comment]
I'm totally into these types of stories so hearing Monika talk about them would be super cool!

**Comment by kkrosie123** [comment]
Ohhh! I'd love to try and write these in!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
