### ISSUE TITLE
Importing MAS from one computer to another

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#4867]
I tried to move MAS from my desktop to my computer, literally just adding the files to my Google Drive then downloading them, and I don't think I did it right since it started me back at square one. Should I try downloading the persistent file separately and add it to my laptop?

**Comment by multimokia** [comment]
Game files mean nothing. Everything is stored in the persistent.

**Comment by its-ken** [comment]
Yea that’s the thing tho. I did that so I could just download the game easily with all my sprite packs, and I included the persistent when transferring them. I’ll try doing it again. Thanks!

**Comment by multimokia** [comment]
Did you put the persistent back where it's supposed to go?

**Comment by its-ken** [comment]
Probably not. Where do they go on PC?

**Comment by multimokia** [comment]
`AppData/Roaming/RenPy/Monika After Story`

**Comment by its-ken** [comment]
Yep got it. Thanks again!
