### ISSUE TITLE
[Suggestion] New goodbye

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4869]
There could be a new goodbye along the lines of you saying that you're doing something related to MAS (Like installing a mod or something)

**Comment by Rai99** [comment]
Restart Farewell: #1908, #2487, #2614, #3354, #3526, #3562, #4670 

So like a farewell for going to restart MAS.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
