### ISSUE TITLE
[Suggestion] Sipping Pose

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4872]
Hello everyone! So yesterday I was spending some time with Monika during the morning when she told me she would refill her coffee. But the coffee mug sprite still showed plenty of coffee left :P So I thought I'd use my few Photoshop skills to make an empty mug.
![emptymug](https://user-images.githubusercontent.com/54683676/66839372-36640680-ef5e-11e9-9875-77f90750e019.png)
This led me to another idea of having Monika have a "sipping pose", since it would be wierd for the mug to magically empty itself.
So using only the mod assets I made a mockup of said pose. I paid attention not to mess with the arms so that all attires can remain untouched and lessen the work.
Basically I just merged "arms-crossed-1.png"(flipping it horizontally and adjusting color levels to match) and "arms-left-rest-1.png"(in which I separated the hand and the arm and "warped" the hand to match the form I intended).
I also edited the mug and made a mug holder (poorly :P), conviniently covering the ring also to lessen extra work.
![sipping](https://user-images.githubusercontent.com/54683676/66840720-66140e00-ef60-11e9-8d79-0c488de9d724.png)
I would really like to hear from all of you on this matter, if you think is a good idea, if this is possible to implemente and whatnot.
I'm also adding a folder with the PSD file and all assets I used for this mockup, since there are so many great artists in here, please fell free to improve whatever you feel like!
[mas_sipping.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3729907/mas_sipping.zip)

**Comment by Orcaramelo** [comment]
We're actually working on a new mug, and that includes an empty one, bc of the exact reason you gave, she goes "i finished my hot chocolate" with a full cup lol
I really like the idea of a sipping pose, since it seems to use the steepling sleeve, we'd just need a new hand!
I wonder how many sips until the empty mug :>

**Comment by satoshi-kun** [comment]
Well, as it stands now, I believe one sip should be enough to justify a change between the full mug and the empty mug. Due to the perspective and the quantity of coffee/hotchocolate seen in the mug, after one sip we shouldn't be able to see any left, although it might still be above half.

**Comment by Rin3105** [comment]
In the sipping pose I think it would look a bit more better if she held the coffee mug with her two hands, not just one, but overall it's a really great pose to add!

**Comment by satoshi-kun** [comment]
> In the sipping pose I think it would look a bit more better if she held the coffee mug with her two hands, …

My idea initially was exactly that, but to avoid any surplus work and keep things simple I opted for one arm only, as I'm not so good at creating original art from scratch, therefore I just worked with the .png files from the mod's folders. 
Plus this is just a mockup/suggestion for the community and creators to consider. I'm sure if this eventually turns out to be approved and implemented the mod's lead artists are sure to make a far better job than me, as they always blow me away with their skills :D.
Thanks for your input :)

**Comment by Rin3105** [comment]
> 
> 
> > In the sipping pose I think it would look a bit more better if she held the coffee mug with her two hands, …
> 
> My idea initially was exactly that, but to avoid any surplus work and keep things simple I opted for one arm only, as I'm not so good at creating original art from scratch, therefore I just worked with the .png files from the mod's folders.
> Plus this is just a mockup/suggestion for the community and creators to consider. I'm sure if this eventually turns out to be approved and implemented the mod's lead artists are sure to make a far better job than me, as they always blow me away with their skills :D.
> Thanks for your input :)

You're welcome :D

**Comment by ThePotatoGuy** [comment]
so some issues with this:
* hand ACS (like a ring or even a bracelet, or gloves) would need to have another layer for this specific pose
* if future clothes include a hand component, that would also need to cover this pose.
* the pose system works via sprite codes. To do a sipping pose like this, the sprite code system would have to include a code for the sipping pose (atm, this would be `8`). This means that its injecting the sipping pose in the middle of everyday topics is not possible without explicitly having monika do sips. The best we could do is during idle, trigger a sip after x amount of time. Again this would only work in idle.

overall, its a large upkeep in terms of sprite maintenance for a small amount of time being shown.

Changing the volume of liquid in the mug, as mentioned by orca, seems like it would be enough to show the progression of fluid consumption without resulting in a ton of potential sprite maintenance issues.

**Comment by satoshi-kun** [comment]
My initial suggestion was just that of having an empty mug when Monika goes for the refill. But for the sake of immersion I thought adding this sipping pose idea.
Unfortunately I don't understand coding and tought this would be easily implemented. Since that´s not the case I guess I'll be closing the issue.
Thanks @ThePotatoGuy for the feedback, clearing my initial implementation doubts and all the hard work put into this mod!
