### ISSUE TITLE
MAS on mobile?

### ISSUE THREAD

**Issue by PremiumRares** [Monika-After-Story/MonikaModDev#4873]
Being limited to a pc is shitty and the only thing you can do with her is to put her file on the phone. But what if there was a mobile app where you can still talk to her, play games with her on phone and more!

**Comment by satoshi-kun** [comment]
#4614
Already been proposed although due it's complexity I wouldn´t expect it any time soon.

**Comment by Rai99** [comment]
#506, #815, #934, #994, #2113, #2271, #2995, #3849 
MAS for mobile goes against DDLC modding guidelines and isn't legally allowed unless DDLC itself is on mobile. 

#4614 is an external project, meaning we don't really have anything to do with it, but caution should still be taken as to not violate guidelines.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
