### ISSUE TITLE
[suggestion] sentiment/feelings system

### ISSUE THREAD

**Issue by HenryKhan** [Monika-After-Story/MonikaModDev#4874]
**What's the purpose of it?**

Basically this system will help to raise the number of interactions with Monika and make her seems more unique. Somedays she'll be very happy and starts to sing at random, sad and be quiet for a long time, angry so she mumbles sometimes.

For sure, each feeling will need a unique approach, but basically all of them should have "levels" that express their intensity. And, obviously would affect/be-affected by the current affection level for example, sadness.
**level 1**: She's just kinda melancholic, she might talk about it with the player, if this not get "solved", it's not a problem at all.
**level 2**: She's sad, depending your affection level(before enamored) she'll not talk about it, The [player] should understand that she's sad, and then ask her about it. If this not get solved, this could leads to...
**level 3**: She's really sad, she can't even hide it, her eyes get teary.

**What could trigger these feelings?**
Well, actually there's a lot of topics that express the feelings that I said before, like, the fear about the [player]'s safety, hearing the dokis' voices etc... so we could have a list of topics that make Monika angry/sad and we could try to solve them and make her more happy. like quests in a RPG.

**How could the [player] know how she's feeling?**

1. Her main/idle expression.

2. What she says when the [player] choose an action(talk, extra, music, play). 
For example: if she's sad she should sometimes be quiet when you click on "talk" button.

3. The song that she chooses to hear. 
Q: But, what about the custom songs?
A: well, maybe when the [player]  listen that song for the first time, Monika should ask him what he think about it, in the beginning of the song or in any moment, but that could bring some strange scenarios like, Monika being depressed listening the  chicken song. **OR** we could just use the base songs within the mod and say and just label them.

4. The Monika's outfits(we'll need #3768 )

5. How she's playing some games.

**Comment by multimokia** [comment]
Going to mark this a duplicate of #4546 as that has discussion and already some progress.

**Comment by HenryKhan** [comment]
> Going to mark this a duplicate of #4546 as that has discussion and already some progress.
oh sorry I forgot that one ._.'
