### ISSUE TITLE
[Suggestion] Multiple Suggestions

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4875]
Suggestion 1: Scrabble
I'm not a god at Scrabble but I'd like to play against Monika and improve my vocabulary at once. I find it quite fun, and, from my perspective, Monika looks like the kind of person who enjoys Scrabble, however, I understand if it's a big undertaking (it certainly seems like one to me).

EDIT:
Suggestion 2: Pong Options Menu
It'd also be interesting to see an options menu for Pong where you can select how the game will play (e.g. best of [x], randomly changing ball direction, speed, etc.)

Suggestion 3: Brief 'unclickable' period when showing choices in dialogue
Sometimes I find myself accidentally clicking the wrong option by mistake the moment they pop up; a 0.5-1 second delay before the boxes become active would help to rectify this.

**Comment by kkrosie123** [comment]
1. Ooohh yess! That would be so much fun to play.
2. Ahahaha, this is a bit immersion-breaking, don't you think?
3. Yes, I like that, too

**Comment by aimlesstrainer** [comment]
> 2. Ahahaha, this is a bit immersion-breaking, don't you think?
What about it seems immersion-breaking?

> the perfect balance would be different for everyone.
I agree with this statement, so I think that maybe there could be a slider or something in the options menu to determine the delay?

**Comment by Rai99** [comment]
I think having a dedicated slider for this little thing is too much. How often does it happen where you accidentally click something too fast, and is it really that bad?

**Comment by aimlesstrainer** [comment]
> I think having a dedicated slider for this little thing is too much. How often does it happen where you accidentally click something too fast, and is it really that bad?

It happens occasionally (trivial to have a slider then, yes, I agree), and I've accidentally used the wrong length of time for a goodbye (I believe it was 2 weeks).

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
