### ISSUE TITLE
[MAS-Art] Laying Down Base

### ISSUE THREAD

**Issue by kkrosie123** [Monika-After-Story/MonikaModDev#4876]
Hello!! I heard that the team was in need of a Moni "laying down base" in #3689, so I did my best to try and make one!

If you're interested in this, I'll send the separated parts and the order in which they go in.

![19](https://user-images.githubusercontent.com/52429850/66917261-b03dd380-efe2-11e9-8ddc-f7e2c97b027a.PNG)

I wasn't exactly sure how she was supposed to lay down. It said to "make it look like she was sleeping next to the player," so that's what I tried to do.

I know my art is pretty crappy sometimes lol so if you want to edit this or not even use it at all, I understand 100%.

Have a nice day, everyone!

**Comment by kkrosie123** [comment]
#3174

**Comment by Orcaramelo** [comment]
Great idea as always briar, luv u
Im interested  👀
Tho we should find a way to make her (top) shoulder look a bit more relaxed

And i think her waist should be showing a little less where she is laying on her arm since her arm would be covering that curve, but im not 100% sure abt that
I really wanna see it usedddddd

**Comment by satoshi-kun** [comment]
That's just great! :D
Who's gonna sleep now? ¯\_(ツ)_/¯
Also, this would probably require a new background (bedroom maybe, it would break my heart to see Monika just laying on the floor), therefore maybe her head shouldn´t be so tilted if a pillow was to be added as part of this.
But that's just me probably being over-excited with this possible option :) and for the time being it looks just great!

**Comment by FrikiHD** [comment]
So well made mate!

**Comment by kkrosie123** [comment]
Thanks qwq I luv you too aaaa

Yessss I got the same criticism from another person :0 I'm trying to think of a good way to do that eee

And Ooooh yes I didn't even notice that.

Maybe I should angle the torso down...? xD

Thank you for replying eee

**Comment by Orcaramelo** [comment]
I made a sketch that tweaks the pose but its nowhere near ready and its very messy
![1571262976874](https://user-images.githubusercontent.com/47725743/66962135-ab127000-f046-11e9-8f49-2136a741c051.png)

**Comment by kkrosie123** [comment]
:0000000 OMG THIS IS SO GOOOOOODD!!

**Comment by GHCactus** [comment]
Seeing this is exciting!

**Comment by Rin3105** [comment]
I'm imagining after this one is complete, we will rebuild that same scene that we see in Our Time mod when we are on the bed with Monika, of course this time will have more customization. :)

**Comment by Orcaramelo** [comment]
We gotta think more about customization tho, because hairclips and hairstyles wouldnt make a lot of sense when sleeping, since that would be pretty uncomfortable 🤔
Am open to different ideas tho, we'll be def able to customize clothes

**Comment by satoshi-kun** [comment]
In my opinion a night gown and pjs should be enough to cover hot and cold weather. What can be done is adding some colour/pattern variations and suddently you got plenty of outfits to choose from. As for the hair I'd leave it just straight loose as I also agree it is the most confortable when sleeping.

**Comment by kkrosie123** [comment]
@Orcaramelo 
I messed around with your sketch a bit :o 
![21](https://user-images.githubusercontent.com/52429850/67030800-cd9f9a00-f0d5-11e9-9b92-9f6e6a0c8073.PNG)
![22](https://user-images.githubusercontent.com/52429850/67030803-d001f400-f0d5-11e9-893c-5953ba989064.PNG)
![20](https://user-images.githubusercontent.com/52429850/67030816-d55f3e80-f0d5-11e9-90b2-1403ceda1bed.PNG)
![23](https://user-images.githubusercontent.com/52429850/67030855-ead46880-f0d5-11e9-9fa4-13223e961e29.PNG)

**Comment by Orcaramelo** [comment]
Her boobs need to be squished because of the positioning of the arm, they cant go that far back, will report back after editing later bc im still in class lol

**Comment by PollenTheCat** [comment]
WOAH THIS LOOKS AMAZING!! Just imagining the bedroom mode made me excited, but seeing base sprite draft things for it made me even more excited!!

**Comment by ThePotatoGuy** [comment]
fyi, orca is leaving and requested us to not use their laying down base, so if we want to do this we will have to start with @kkrosie123 's original creation.

**Comment by kkrosie123** [comment]
aaaa oki! Yes, I heard about orca ><

**Comment by kkrosie123** [comment]
I might redo it or maybe just keep working

**Comment by kkrosie123** [comment]
Closing, seeing as new art has been commissioned.
