### ISSUE TITLE
Error when trying to launch the game

### ISSUE THREAD

**Issue by heygo67** [Monika-After-Story/MonikaModDev#4877]
Hey!
I tried to launch MAS through steam, but when I did, I received this error.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3735922/traceback.txt)
I have the newest update, and the game worked fine last night. I haven't done anything different to it since I last launched it.
If you need any more info, please let me know.
Thanks!

**Comment by jmwall24** [comment]
Open this zip, and put the `.rpyc` into your` game/` folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the `game/` folder after about 5-10 seconds. The `.rpyc` you put in there should be gone. Launch MAS again, and it should be fixed.

[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3735955/ev_dropfix.zip)

**Comment by heygo67** [comment]
Thanks @jmwall24 ! It works now
