### ISSUE TITLE
[Suggestion] Make welcomes after some goodbyes more time specific.

### ISSUE THREAD

**Issue by Ogermo** [Monika-After-Story/MonikaModDev#4878]
It's weird when you are saying you are going to sleep and then when you open the game next evening she ask you how you slept.  This kind of answers make it fell like she don't aware how much time has passed and what time is it.

**Comment by lunulae** [comment]
If I recall correctly ones for the Goodnight goodbye are specifically being worked on right now. I'm not sure about the others though?

**Comment by jmwall24** [comment]
#2192

We're getting there

**Comment by Rai99** [comment]
#2024, #3383, #4117, #4285, #4565

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
