### ISSUE TITLE
[Question] Love affection level events

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4880]
I saw in the All Features page (https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#affection) an event in "Love" level that says the following: "When given the "surprise.txt" file from Monika. She will give you a full love poem." What does it mean and where is that .txt file?

**Comment by thezotikrus** [comment]
She makes those files sometimes. They are different at each ~~affection level~~. You will get a dialog from Monika when she made one. You can find them in your main game directory. Like `\Doki Doki Literature Club` or whatever you named it.
I'm sure you need to have `Repeat Topics` turned on after you got your first note. Although, if you've seen the first note, you can trigger it again by asking her to `Repeat conversation` via `Talk` menu.
