### ISSUE TITLE
Typo(?)

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4881]
Hello! First of all I'm not 100% sure on this one, more like 80ish.
After I wake up Monika after holding her for enough time, she ends up saying "Who knows when I'd let go when i finally **_got_** the chance?" which I think should've been "Who knows when I'd let go when i finally **_get_** the chance?"
Please let me know what you think.

**Comment by MisterSimple** [comment]
Thanks for pointing that out, we've decided to rephrase that line, check out #4772 if you'd like to see it. Also, for future reference please keep report all typos on #4709. Closing.

**Comment by satoshi-kun** [comment]
I'm sorry, I didn't notice there was already an issue opened.
