### ISSUE TITLE
[Suggestion] Clicking Monika

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4882]
I had an idea recently and here I tell you in more detail. Actually, I would like that little and at the same time great detail of being able to click Monika, for example, click her nose to blush, or click her hair and tell us something like "You really like my hair, right [player]? " and be able to click her eyes and stuff. I know there is the "I want to tell you something" but it is quite different after all. Thank you for reading :)
Reference image:
![Boopika](https://user-images.githubusercontent.com/55263957/67058893-39612180-f12d-11e9-8ae3-46ff201e19d4.jpg)
https://www.pinterest.cl/pin/860539441275868737/?nic=1

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346.

**Comment by RavenPLAYER** [comment]
Ups...
