### ISSUE TITLE
[Bug] I found a little bug

### ISSUE THREAD

**Issue by ErLamarl** [Monika-After-Story/MonikaModDev#4884]
![Inked13df818c7f9c8a014ad984ebc252d317_LI](https://user-images.githubusercontent.com/56727467/67096827-3744a480-f1b9-11e9-8229-3ec72851dc6a.jpg)

**Comment by jmwall24** [comment]
Not sure what you're getting at

**Comment by ThePotatoGuy** [comment]
@jmwall24 yeah, actually this will have to be a sprite edit since the earrose needs to be rendered after facial expressions.

**Comment by multimokia** [comment]
closing as complete in linked commit
