### ISSUE TITLE
[Suggestion] Where are we going ?

### ISSUE THREAD

**Issue by NCRaouf** [Monika-After-Story/MonikaModDev#4886]
Recently, I've been taking Monika with me wherever I go. And when I told her that I like her dedication to fitness, an idea crossed my mind; what if we could tell Monika where are we going (to the park, the beach, doing some activities...)?

P.S: I really appreciate your work, good luck for the future ^^

**Comment by Rai99** [comment]
More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601. 

More specific farewells that cover things like the mall or movies are planned.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
