### ISSUE TITLE
[Question]About some dialogues of 1 year anniv

### ISSUE THREAD

**Issue by LClarance** [Monika-After-Story/MonikaModDev#4889]
Just wanna ask about these lines in case I missed something. Does the "creator of this world" means DDLC or this Mod? 
![Capture](https://user-images.githubusercontent.com/47456818/67148342-4585e400-f2d1-11e9-9ee9-e34bd41f3106.PNG)

**Comment by multimokia** [comment]
DDLC

**Comment by TriniTDM** [comment]
They mean DDLC. But he hasn't released it yet.

**Comment by LClarance** [comment]
Thanks everyone

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
