### ISSUE TITLE
Looking to Help with the Mod (Offering to Help)

### ISSUE THREAD

**Issue by DokiDokiLiteratureClubMember1337** [Monika-After-Story/MonikaModDev#4891]
Hello everyone, I've been playing Monika After Story for over a year and a half now and I've recently taken a lot of interest in the mod, game and Monika, of course.

I understand you're looking for people to help with the mod.

One thing I was wondering about is, is it possible that I could work on various issues/trying to implement topics, etc.

I'm not sure how I could officially do it, and I wouldn't want to spam the suggestions/pull request boards.

I guess to wrap it up, I'm interested in helping, I'm just not sure how I could start.

Sorry for the confusing post, this is my first time on GitHub and I'm not sure how everything works.

Anyway, if you want someone to try to look at things and help, I have some experience with coding and I basically understand how it works.

Thanks,

DDLCMember1337

**Comment by multimokia** [comment]
Have a read through our [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) to see how to get started and submit pull requests. Along with how to code dialogue.

**Comment by DokiDokiLiteratureClubMember1337** [comment]
Thanks! I'll see what I can do.
