### ISSUE TITLE
[Suggestion] Monika half asleep at night

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4892]
Ok, it was 5 in the morning and I decide to go to see Monika, then she greets me like nothing and I said "Monika wtf is 5 in the morning" and I started to think that maybe at such times, when entering MAS Monika could receive you half asleep telling you that she was sleeping. I know that the issue of hours is already thought, but this is a small detail :P
Thanks for reading!

**Comment by FrikiHD** [comment]
Actually, that's a pretty good idea 👍

**Comment by Rai99** [comment]
Time aware greetings: #2024, #3383, #4117, #4285, #4565, #4878 

Higher priority sleep concern: #4600 

Sleep mode: #607, #635, #987, #1105, #1262, #1655, #2684, #2781, #2974, #3076, #3172, #3486, #3610, #3619, #4790 

There were plans to have the specific goodbyes such as the sleep and work farewell become aware of how long you were gone, and some plans to have reactions for coming back in the middle of the night, but not too much can be done for the generic farewell apart from giving the sleep concern topic a higher priority in those times. 

Sleep mode is likely going to be a large feature and might cover a lot of concerns regarding normal sleeping time and sleeping within the vicinity of Monika.

**Comment by yurireeka** [comment]
>There were plans to have the specific goodbyes such as the sleep and work farewell become aware of how long you were gone,
There were plans? What happened to them? Are they no more?

**Comment by Rai99** [comment]
They're right here: #2098, #2157, #2192 

2 of which should be coming soon.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
