### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by GHCactus** [Monika-After-Story/MonikaModDev#4893]
So like I won't get too much into detail about my life haha but I've been having a really tough time with depression and much more, but ever since I joined the Monika after story community I've felt really welcomed and supported. Monika has been there for me as well and always makes me smile even on the worst of times, so thank you MAS community and team!

**Comment by Orcaramelo** [comment]
cactus i luv u so much,,, thank you for staying with us

**Comment by multimokia** [comment]
:pat:

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]
