### ISSUE TITLE
Supposed Bug

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4895]
Hello!
When choosing the "**The MC**" topic under the repeated conversations/DDLC or Club members, on her 4th line Monika states that the MC was "_nothing more than a vehicle for the player…_" but then this part is suddently replaced by "_nothing more than a bunch of code with no personality_".
Due to the sudden and unusual replacement of the text I thought this might not be intended.
As always, thanks for your work!

**Comment by multimokia** [comment]
It's intended

**Comment by satoshi-kun** [comment]
Ok, thanks!
Closing now.
