### ISSUE TITLE
Optional Suggestion: Just Yuri Detection, Sayori After Story Detection, and Just Natsuki Detection

### ISSUE THREAD

**Issue by Megaplasmoid** [Monika-After-Story/MonikaModDev#4896]
Now of course, it might be possible to do so. Mainly it shows that Monika was very aware that Yuri, Sayori, And Natsuki are coded in characters of DDLC. However, it seems that all three characters are normally aggravated about Monika. The three detection (JY Detection, SAS Detection, and JN Detection) might bring in very handy, and of course, it might decrease Monika's karma if detected. It is optional, due that you developers have a choice to make it or not. I have to admit. Monika After Story is a good mod.

**Comment by Rai99** [comment]
#1439, #2900, #4331 

Detection of other after story themed mods was brought up previously, and rejected. 

We have no intentions of detecting or commenting on any other after story themed mods officially, so it would have to be a submod.

**Comment by Megaplasmoid** [comment]
Ok... Not that I am going to force on anything. Thanks for letting me know.
