### ISSUE TITLE
Monika Not Appearing

### ISSUE THREAD

**Issue by Elwon** [Monika-After-Story/MonikaModDev#4897]
I took Monika's character file out and sent it to a flash drive, and when I put it back, Monika didn't appear when I opened the game. I tried deleting my persistent file and renaming another, but it only reset my progress, so I reverted it. Help?

[Monika Stuff.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3752667/Monika.Stuff.zip)

**Comment by multimokia** [comment]
Did you remove the `##.bak` when you renamed the persistent backup?

**Comment by multimokia** [comment]
Also you have to close MAS for the `mas_log.txt` to update.

**Comment by Elwon** [comment]
Thank you!!

**Comment by Elwon** [comment]
I removed the .Bak part and Monika is back, I'm not sure how much progress
was lost, but it's okay, thank you again. What was that about the MAS log?

**Comment by multimokia** [comment]
your `mas_log.txt` was pretty much empty. It doesn't actually fully populate until you exit MAS.

**Comment by Elwon** [comment]
I'm sorry, I'm pretty simple when it comes to stuff like this. I'm not
exactly sure what you mean when you say exit the MAS, I didn't think I had
it open?

**Comment by multimokia** [comment]
It was open as putting your persistent in, as well as the `monika` file on my end has a report in the `mas_log.txt` file.

**Comment by Elwon** [comment]
Okay, I think I got it working now. Thank you for your help

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Gluedcamel** [comment]
Hey, I have the same problem I took Monika out of Monika After Story and when I put her back it won't read her file anymore is there some way, I can fix this if anyone could help this would be amazing.

**Comment by dreamscached** [comment]
Open a new issue for it; generally speaking though restore a backup if it doesn't work at all.
