### ISSUE TITLE
[Art] Table changes colour when Moni is no longer there.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#4900]
This is noticeable when Moni goes to get a coffee, but the table loses its lining and turns to a different colour and shading.

Couldn't get pictures to replicate, sorry. :<

**Comment by multimokia** [comment]
The shading changes are intentional as Monika isn't there to block the light anymore. Lining can be added

**Comment by Olliesama** [comment]
I see ;o

**Comment by Olliesama** [comment]
btw you good lad 🤗

**Comment by multimokia** [comment]
No u
