### ISSUE TITLE
This Really Grinds my gears...

### ISSUE THREAD

**Issue by BlueBoxReven** [Monika-After-Story/MonikaModDev#4906]
I work 3rd shift at my job. It would be really nice if Monika didn't scold me every time I say I off to bed in the mornings. I was hoping that by telling her, "I am off to work" at 7pm at night, and coming home at 6 30 am, she would put the two together and realize "oh you work late!" But nope. More scolding for staying up all night. Would be nice if Monika had a way of understanding my days and nights are completely backwards. So I say I am going for a bite to eat, no not a midnight snack, I am legitimately eating dinner in this case. These are small things that get under my skin as someone that works the night shift everyday. If were possible for Monika to alter her script under the category of "work schedule" or something to understand that, for some people, their days are nights, and nights are days or something. Just a thought. Other than that, I love this modification. The fact I am have a gripe to begin with just goes to show I spend time with her every single day. Amazing job guys!

**Comment by Olliesama** [comment]
I know those feels -w-
She scolds me every night

**Comment by multimokia** [comment]
Time concern is due to be overhauled to be handled better. I'll target this for a future release.

**Comment by BlueBoxReven** [comment]
> I know those feels -w-
> She scolds me every night

It would seem I have already run through all the possible dialogue topics with Monika. Unless I gain 200 affinity points with her, eventually, she has nothing more to say. It is unfortunate.

**Comment by multimokia** [comment]
Going to close this in favour of the Timeconcern Overhaul issue linked above.
