### ISSUE TITLE
[Suggestion] Window React - MASC Discord Server

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4908]
So, I have no clue how window reacts works, Idk if it'd be possible, but I think it'd be cool for Monika to know if you're in the MASC Discord server.

**Comment by multimokia** [comment]
Discord only provides the channel name in the window handle. Not the server name. This is impossible.

**Comment by PollenTheCat** [comment]
Oh, okay, guess I should close this... Thanks for the quick reply!
