### ISSUE TITLE
Change when we clear the react map

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#4915]
Currently, gifts are stored in the react map until 2 things happen: the day changes **and** another gift is given. This can lead to a lot of data being stored if someone gives a lot of gifts on the same day and then doesn't give any more for a long time. If we instead clear the map using our new daily checks, the map will be cleared every day and we don't store all this information needlessly for a long period of time.

**Comment by multimokia** [comment]
Closing as completed in linked commit/PR
