### ISSUE TITLE
Monika does her own impressions for screenshot pictures

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#4918]
Like the title says, I am thinking of an idea when we have a new option to ask her to do her own impressions (not any other dokis impressions). It can be in all different kinds of poses, cute, wholesome, silly, anything like that, and when she does, we can take screenshot pictures and share to other players if we like. It's really okay if it takes a lot of time because I know this will rely a lot to arts and sprites, but just a cute suggestion anyway :3

**Comment by thezotikrus** [comment]
Before grumpy booblicate comes here to set a label, I'll say I like it

**Comment by Rai99** [comment]
Who?

**Comment by thezotikrus** [comment]
_hiding_

**Comment by Rai99** [comment]
Posing for screenshots/drawings: #2056, #2633, #3630, #4681.

**Comment by Rin3105** [comment]
Duplicated mostly, I know, but hopefully those issues there would be done soon, I can't wait.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
