### ISSUE TITLE
Goodbye and Discussion Topic Suggestions

### ISSUE THREAD

**Issue by Salty-PopTato** [Monika-After-Story/MonikaModDev#4923]
Hey there! I've had a couple of ideas for some things Monika could say.

One goodbye interaction could be "I'm going to go play a sport..." MonMon could be proud of you for doing so, and might even ask the player what sport they would be playing, which would prompt them to pick one of the sports. Maybe it could list things like basketball, soccer, tennis, netball and rugby, to name a few, as well as an 'other' option. 

Another goodbye option might be to say 'I'm going on a date'. Of course, this would probably lower your affection and would be similar to the 'I want you to meet my girlfriend' discussion. When asked, the player could say 'it was a joke', '...with you!', or agree that they are, in fact, going out with someone other than Monika.
Whoever would do the latter is heartless, but oh well.

Finally, if it hasn't been mentioned before, I think Monika should talk about Team Trees. It's been all over the internet lately, and I think it would be great if MAS could get on board, too, and it would definitely be right up MonMon's alley.

Anyways, thank you for listening to my suggestions; I hope you found them interesting!

**Comment by Rai99** [comment]
Exercise farewell: #1576, #2206, #2571, 
Exercise brb/idle: #3875 
The sports topic lets you tell Monika if you play tennis or a different sport, but it might be possible to have a textbox to enter what sport you play if any. 
___
For the option to leave and go on a date with someone other than Monika is probably something we wouldn't do. I don't think we need to add a feature like that. 
___
As for team trees, we tend to avoid large/controversial/viral current topics, especially memes, as they eventually tend to lose their luster and/or become outdated after a while. 

It might be more in line with the mod to have a topic about trees for example. We already have a topic about global warming and if we live in a city, and smoking, but I don't think we're going to jump on the bandwagon of team trees directly. 

I think we can still show our support by making a topic or two or fun facts about trees or the environment.

**Comment by Salty-PopTato** [comment]
Oh, cool, I'll have to double-check the sports topic.
The dating goodbye wouldn't really be useful, so yeah, I understand that. Probably better for Monika too aha.
I agree with you on adding a few fun facts on trees - that would definitely be better than talking about it directly whilst also showing support and, well, adding cool tree facts to the game! Who doesn't like cool tree facts?

Thank you very much for your reply! :)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
