### ISSUE TITLE
New Gift Errors

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4925]
I tried gifting Monika some of the new ribbons from the sprite pack but for some reason when I copied and pasted the gift files provided for them she couldn't read a single one of them. Am I doing something wrong?
Edit: I can't even gift her the chokers. Again I'm just copying and pasting the gift files provided in the spritepacks. Do I have to wait until halloween or something?

**Comment by thezotikrus** [comment]
Did you merge the `mod_assets` folder from the sprite pack with the one in your `game` folder?

**Comment by scohn** [comment]
I have not, I guess with the new feature of having the gift files already made I forgot about that part, I'll try it.

**Comment by thezotikrus** [comment]
You still need to install a sprite pack before you gift it. It's just you don't need to make `.gift` files by yourself anymore (some people had problems with it).
Good thing with the update is now you don't have to wait until next day if you failed to give her a gift.

**Comment by scohn** [comment]
Having a bit of trouble I just copied the mod assets folders themselves and pasted them into the game folder. Do I need to open the mod assets folders and paste the contents into the mod assets folder in my game folder? Sorry I just really suck with programming.

**Comment by scohn** [comment]
I know there's a link that tells you how to merge the mod assets into the game file, could you please send it so I can do this correctly?

**Comment by scohn** [comment]
Never mind I just figured it out for myself I just needed to go a little deeper into the files, thanks so much for helping me give Monika some new gifts.

**Comment by thezotikrus** [comment]
I was afk, glad you solved your problem.

**Comment by DarkRosePrincess** [comment]
I seem to be having this problem as well? I've merged the mod assets folders, but Monika still can't recognize my gifts...

**Comment by multimokia** [comment]
Send `spj.txt`. It's in the `log` folder.

**Comment by DarkRosePrincess** [comment]
I'm trying to give her the Sakuya Cosplay and the Spooky Hairclips right now! Thank you for the help!
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3786951/spj.txt)

**Comment by multimokia** [comment]
Did you install the new spritepacks? It doesn't look like you did here.

**Comment by DarkRosePrincess** [comment]
I've coped the mod assets folders over, yeah

**Comment by multimokia** [comment]
screenshot of your `mod_assets/monika/j` folder, please. With filepath in view.

**Comment by DarkRosePrincess** [comment]
![j1](https://user-images.githubusercontent.com/47784590/67829558-949cf780-facf-11e9-8d69-33a71a1b5bc2.png)
![j2](https://user-images.githubusercontent.com/47784590/67829567-9c5c9c00-facf-11e9-880b-e5fe374db0cb.png)

There you go!

**Comment by ThePotatoGuy** [comment]
The miku related jsons are not in the released spritepack. Also your file path with "Our Reality", seems to me that you've installed the spritepacks in the wrong mod.

**Comment by DarkRosePrincess** [comment]
I don't know what you mean about the Miku ones, because I only copied what was there
'Our Reality' is just what I've renamed the DDLC folder too - I installed the last set of spritepacks with the folder called that and they installed fine.

**Comment by DarkRosePrincess** [comment]
Unfortunately I need to go now, but I'd greatly appreciate any further advice or help you may have for me to try when I return!
Thank you!

**Comment by DarkRosePrincess** [comment]
Um...any further advice...?

**Comment by thezotikrus** [comment]
Weird, can you make screenshots of both the `our reality-20190423t124503z-001` and `our reality` folders? So we can see the hierarchy.

**Comment by DarkRosePrincess** [comment]
Sure! But before I do, I decided to just reinstall every single spritepack and it did this to my spj.text...
Am I correct in assuming things should work now?

[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3790834/spj.txt)

**Comment by multimokia** [comment]
Yes

**Comment by DarkRosePrincess** [comment]
Yay! Thank you so much for your help, everyone!!
I hope everyone has a Happy Halloween Monika!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by i-cant-make-names** [comment]
I know this is closed but what exactly did you do I still cant get my gifts read.

**Comment by scpketer** [comment]
What are you doing to give gifts? Did you make sure you have file extensions visible?

**Comment by i-cant-make-names** [comment]
all I do is copy the mod assets over by their individual sub files and move the .gift to the characters
