### ISSUE TITLE
Spritepack doubt

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#4929]
Sorry to bother you with this, but apart from the new content added in the spritepack folder, should I be replacing any of the other items already present on 0.10.1 into my game folders again? (like the new hairstyles or the pink and blue shirt)
I mean, I already have them since the last update, it´s just in case any of them had been updated/fixed in some way and need replacement.
Thanks for the new update!

**Comment by multimokia** [comment]
If any get adjusted, they will be mentioned in the release notes. If nothing's mentioned, nothing changed.

**Comment by satoshi-kun** [comment]
Thank you for the quick reply! 
It was just this note that I didn't understand that set me off.
_- Hairstyles by Orcaramelo has been updated to include the twintail ex prop._
