### ISSUE TITLE
[Spoiler?] choker isn't locked for specific outfit for the first time gifting

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#4932]
Hello! I'm using v0.10.2-unstable.2019.10.28.108, and I just want to report a thing regarding to choker gifting when Monika is currently using "specific outfit". This probably contains a spoiler, though.

I have been here since last year, so Marisa outfit has been unlocked for me. For the last several sessions, I have been using Marisa outfit (before build 108 update). When I updated it, I gave her several gifts from spritepack (just for testing).

After that, I opened Talk > Hey, Monika... > Appearance. To my surprise, the choker wasn't unlocked and couldn't be tried on. This problem solved itself once I changed my outfit to other and changed it back to Marisa, though. This doesn't happen for ribbon and bow gifting, though.

I know that you want to redraw Marisa and Rin outfit. I'm here only to report this. Sorry, I can't check whether same problem ensues for Rin outfit.

Thank you. Have a nice day!

**Comment by ThePotatoGuy** [comment]
The only selector that should be usable when wearing marisa/rin is the clothes selector.

**Comment by skyloom** [comment]
After changing the clothes into something else and changing back, the selector is hidden, so only when choker is given when Moni is using Marisa outfit. The thing is, it doesn't happen to bow, ribbons, and even the hairclips

**Comment by ThePotatoGuy** [comment]
I'm going to leave this behavior as is. Baked outfits are intended to be replaced so adding handling for this behavior would only be temporary.
