### ISSUE TITLE
[Bug] Changing from non-Miku outfit to Miku outfit w/out outfit mode yields no headset

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4939]
Title, again.

Is the headset supposed to be an accessory separate to the Miku outfit (i.e. can I select it in some selector)?

**Comment by frostcattooo** [comment]
select outfit mode and the headset will be back.

**Comment by RavenPLAYER** [comment]
taking advantage, what is the name of the gift? I tried the "hatsunemikucosplay.gift" and it doesn't work for me, I went to the json file of the gift and it's exactly the one I wrote but to make sure I copied it and pasted it from the json file of "Sublime Text" and nothing.

**Comment by multimokia** [comment]
Miku outfit is currently not giftable.

**Comment by RavenPLAYER** [comment]
I see, you can get it at the even-... Alright. THK! :)

**Comment by lunulae** [comment]
I don't believe the headset can be used on its own with clothes other than the Miku ones at this time. Same goes for the Sakuya headpiece+bow.

**Comment by ThePotatoGuy** [comment]
the ACS specific to certain outfits are not separately selectable and may stay that way going forward. kind of depends on if an ACS plays nicely with other outfits.
