### ISSUE TITLE
I can't give her the Hatsunemiku clothes

### ISSUE THREAD

**Issue by Monikw** [Monika-After-Story/MonikaModDev#4941]
I tried to give her the Hatsune Miku clothes but it doesn't work even though I already but the file in Mod asset-monika-j and everything in thumbs but I still can't give her the clothes

**Comment by multimokia** [comment]
they are currently not giftable.

**Comment by Monikw** [comment]
ok

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
