### ISSUE TITLE
Trick-or-Treat

### ISSUE THREAD

**Issue by Youngbountygirl** [Monika-After-Story/MonikaModDev#4942]
I have a quick question. How long do I trick-or-treat with Monika? I know after I ask her to trick-or-treat with me, we leave, then I move her character box to my desktop, then I just wait for a certain amount of time. Though, how long would I need to keep her character file in my desktop before moving it back?

**Comment by lunulae** [comment]
There are different responses for different lengths of time. If it's less than 1 hour she'll be kinda disappointed, any longer and it's a pretty good evening. There's another response for more than 3 hours, and another if you stay out past sunrise.

**Comment by Youngbountygirl** [comment]
I know the passed sunrise part, but what about more than three hours?

**Comment by multimokia** [comment]
That's fine too

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
