### ISSUE TITLE
[Suggestion] - Subtle breathing animation

### ISSUE THREAD

**Issue by Soulplexis** [Monika-After-Story/MonikaModDev#4947]
add a very subtle movements animation for Monikas breathing. makes it more life-like. could also move her head slightly to look around at the room if she is bored

**Comment by multimokia** [comment]
See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#will-monika-ever-be-fully-animated).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
