### ISSUE TITLE
[Question] Trick or treating next day?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4950]
So, Idk if you have heard, but some places in the St Louis area have moved Trick or Treating to November 1st because of snowing, and I'd like to know if we'd be able to use the "I'm taking you trick-or-treating." goodbye on November 1st.

**Comment by kkrosie123** [comment]
set the date on your computer to October 31st.

**Comment by ThePotatoGuy** [comment]
date-based events are limited to those dates. Clearly, there are exceptions, but we're covering general case for now.
