### ISSUE TITLE
[Suggestion]: sleeping monika expression with pose 5

### ISSUE THREAD

**Issue by Xalvidor** [Monika-After-Story/MonikaModDev#4955]
When you hold Monika, after an hour or so she falls asleep and has a really nice music box tune to indicate she's asleep. would it be possible to make it so she tilts her head down or to the side slightly when she is asleep. it'd be mighty cute so i think it may be worth the add if possible.

**Comment by Xalvidor** [comment]
![sleepy image](https://user-images.githubusercontent.com/57244912/68002561-5a635f80-fc61-11e9-9e31-b33ddfc77428.JPG)

so after speaking with member of dev team, primarily on bases im thinking that we could use this head tilt along with using the current body posture she uses for sleeping at the moment because obviously she falls asleep with you holding her so keeping her being held posture would make sense now in my mind the head tilt along with the posture would look cute but thats just my perci pinion

**Comment by ThePotatoGuy** [comment]
renamed the issue to be what it really needs - a sleeping facial expression that can fit with pose 5. Not really sure how that will work with the current sprite system, so closing until we look into it
