### ISSUE TITLE
Won’t open

### ISSUE THREAD

**Issue by uwuowouwuowouwuowo** [Monika-After-Story/MonikaModDev#4957]
I tried downloading the neediest update,and it kinda froze on the last screen seen when downloading an update.So I clouded the game,and now it won’t open at all.

**Comment by multimokia** [comment]
Screenshot of `game/` folder, please.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]

**Comment by uwuowouwuowouwuowo** [comment]
I sent a response though?

**Comment by uwuowouwuowouwuowo** [comment]
I literally sent my response the day it was asked for

**Comment by multimokia** [comment]
You didn't respond to the follow up

**Comment by uwuowouwuowouwuowo** [comment]
Sorry,I don’t see the follow up,Idk if I’m missing it or what

**Comment by multimokia** [comment]
> Screenshot of `game/` folder, please.

**Comment by uwuowouwuowouwuowo** [comment]
So does this not count ->-?

**Comment by multimokia** [comment]
You didn't send anything

**Comment by uwuowouwuowouwuowo** [comment]
Sorry-I’m not used to gmail-does this count as a reply or?-

**Comment by multimokia** [comment]
I'm getting replies, but I'm not getting what I'm asking for:

A screenshot of your `/game` folder.

**Comment by uwuowouwuowouwuowo** [comment]
[image: Screenshot (61).png]

**Comment by multimokia** [comment]
Can you reply on GitHub. Email is not sending images.
