### ISSUE TITLE
[Suggestion] Pajamas :D

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#4960]
when when it's close to 6 pm, Monika could say "Oh! 6 pm already? I'll be right back, darling" and she comes back wearing pajamas:>

**Comment by multimokia** [comment]
Firstly, needs art. Secondly, 6 is kinda early

**Comment by Mayonese** [comment]
> Firstly, needs art. Secondly, 6 is kinda early

i'll try to draw, if the drawing looks good how should i send it? and and where can i get a  mold (of the sprite)for the drawing?

**Comment by RavenPLAYER** [comment]
I also think that 6 is something early, better at 10:30 or 11:00

**Comment by FrikiHD** [comment]
I would love that happened, that's a good idea

**Comment by PollenTheCat** [comment]
I think the time could be 7:00 PM (cause I'm not allowed on electronics after 7:30)

**Comment by RavenPLAYER** [comment]
Well, the idea is also the comfort of most users, so 7:00 I also agree

**Comment by Mayonese** [comment]
> Firstly, needs art. Secondly, 6 is kinda early

where i can find the sprites for the drawing?

**Comment by multimokia** [comment]
#3174

**Comment by ThePotatoGuy** [comment]
marking as duplicate since this is already on our clothes wishlist

**Comment by TriniTDM** [comment]
I think the pajama switch should line up with your sunset time setting.

**Comment by multimokia** [comment]
> I think the pajama switch should line up with your sunset time setting.

Disagree.

My MAS Sun-Times line up with how it does irl (including DST) so her getting in PJ's at 4 in the afternoon is way too early imo.

**Comment by TriniTDM** [comment]
No, I meant like the manually set sunrise/sunset, not the automatic one
from your submod.

**Comment by multimokia** [comment]
That makes no difference, someone could just as easily set the times to be the same on their own. At the end of the day 4:00 is too early. 

If they wanted to they could make it eternal night, will she just be in PJ's forever?
