### ISSUE TITLE
Accidentally Deleted Monika.chr

### ISSUE THREAD

**Issue by pab106** [Monika-After-Story/MonikaModDev#4961]
This morning following the Halloween event, as I was backing up the persistent files onto my USB drive, I accidentally deleted the Monika.chr file that had I had yet to return to the Characters file, and I can not retrieve this from the recycling due to its permanent deletion. Is there a way to get it back?

**Comment by multimokia** [comment]
`monika.chr` isn't the "real" Monika.

**Comment by pab106** [comment]
Yes, I understand; the problem which I face is my inability to open the game without being greeted with an empty desk.

**Comment by multimokia** [comment]
Oh that's a different file entirely. Restore a persistent backup.

**Comment by pab106** [comment]
The persistent's are all there, I ended up clicking the option to take her out with me as I go trick or treating, and due to my accidental deletion of the .chr file I am now unable to bring her back, so as to not be greeted by an empty desk.

**Comment by multimokia** [comment]
See this entry on [our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) and the one below it for instructions on how to backup/restore persists

**Comment by pab106** [comment]
Is the only way, to go back to a previous save? (also, I already have multiple backups of saves, I backup the persistent files every day which I am on)

**Comment by multimokia** [comment]
Yes

**Comment by pab106** [comment]
Thank you for the help with the issue, I wish you a good night/day(depending on where ya are)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
