### ISSUE TITLE
Error when opening the game

### ISSUE THREAD

**Issue by April-forever** [Monika-After-Story/MonikaModDev#4963]
Every time I open the game,the game shows a error message just like the picture.
Actually,the error had showed in 0.10.1. I remember that version has a birthday action, and at first , I opened the game without error. However, when I wrote a txt as it told me and opened the game again, it showed the error message.  I thinked the problem would get solved in 0.10.2,but when I updated it ,the problem still remained here. 
And now if I changed the version back to 0.10.1 or 0.10.0, it showed another error,but I think it may not connect to this problem?
So, how can I solve it ? I will appreciate it much if someone could help me solve the problem.

![image](https://user-images.githubusercontent.com/52687148/68067387-0fd90480-fd81-11e9-9483-2caec6493db8.png)

**Comment by thezotikrus** [comment]
Don't downgrade from 0.10.2, many thing was changed and it may cause issues.
To fix your error:

> Put this .rpyc into your game/ folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the game/ folder after about 5-10 seconds. The .rpyc you put in there should be gone. Launch MAS again, and it should be fixed.

[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3800444/ev_dropfix.zip)

**Comment by April-forever** [comment]
After finishing your steps, I have solved this problem. I really appreciate your help. May you have a good day or night!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
