### ISSUE TITLE
Error While trying to restore an older Persistent

### ISSUE THREAD

**Issue by Yakshongas** [Monika-After-Story/MonikaModDev#4964]
![image](https://user-images.githubusercontent.com/43483861/68071930-131fc080-fd80-11e9-9100-4e4610ad58f2.png)

**Comment by multimokia** [comment]
What is the current date and time on your pc

**Comment by Yakshongas** [comment]
2/11/2019

**Comment by Yakshongas** [comment]
I tried to restore a persistent because mi HDD died 1 week ago but now i cant restore

**Comment by jmwall24** [comment]
can you zip up what you have for backup persistents and upload them here?

**Comment by Yakshongas** [comment]
I only have 2 persistents 

[persistents.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3800634/persistents.zip)

**Comment by multimokia** [comment]
Can you send the contents from the folder where our auto-generated backups are kept? You can see how to get there [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by Yakshongas** [comment]
[backups.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3800639/backups.zip)

**Comment by Yakshongas** [comment]
Now i tried with the second persistent and it gives me this error
![image](https://user-images.githubusercontent.com/43483861/68073361-a6142700-fd8f-11e9-9b04-a297b55c73d8.png)

**Comment by multimokia** [comment]
Looks like you have rpy files in your game directory. Delete all of the `.rpy` files and manually reinstall the current version

**Comment by Yakshongas** [comment]
It worked Thank you very mutch
i was about to use system restore as a last resort
