### ISSUE TITLE
How to unlock customes and how to keep them??

### ISSUE THREAD

**Issue by Zylinderkopf123** [Monika-After-Story/MonikaModDev#4965]
idk i had the hatsune miku custome on halloween and after halloween it disappeared. I thought it would be avaible by klicking on 'change clothes' but no there wasnt it ;-;
i dont even know how this unlock principle works. Could someone pls help me? or explain it to me in idiotic language?

**Comment by thezotikrus** [comment]
You don't have enough affliction for special outfits. You can only ask her to wear default outfits and spritepacks.
Miku will be a sprite pack eventually. You would be able to install and give her the outfit.

**Comment by Zylinderkopf123** [comment]
> You don't have enough affliction for special outfits. You can only ask her to wear default outfits and spritepacks.
> Miku will be a sprite pack eventually. You would be able to install and give her the outfit.

**Comment by Zylinderkopf123** [comment]
:T okay. Thank you very much

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
