### ISSUE TITLE
Sound of Rain holding hand error

### ISSUE THREAD

**Issue by BabiRanger** [Monika-After-Story/MonikaModDev#4966]
when i try to repeat conv with monika about the rain to unlock the hold hand option... i recieve this error.. i try redownload the mod but it wont fix.. please help
![Monika After Story 11_3_2019 3_58_22 AM](https://user-images.githubusercontent.com/57300712/68076393-e5259500-fdee-11e9-8733-2dc7a0406314.png)
![Monika After Story 11_3_2019 3_59_08 AM](https://user-images.githubusercontent.com/57300712/68076386-d2ab5b80-fdee-11e9-89f9-eeae5d3b94dc.png)
![Monika After Story 11_3_2019 3_59_15 AM](https://user-images.githubusercontent.com/57300712/68076400-f53d7480-fdee-11e9-85a2-c0594c60442c.png)

**Comment by multimokia** [comment]
Fixed in next update. I'd stay away from this topic for now. If you have it unlocked already `Hey [m_name]... > Romance > Can I hold you`

**Comment by BabiRanger** [comment]
thank you so much.. so i just need to wait for next update?

**Comment by BabiRanger** [comment]
@multimokia thank you for the information.. so i just need to wait for next update?

**Comment by multimokia** [comment]
Yeah
