### ISSUE TITLE
Minor Feedback for improving Immersion

### ISSUE THREAD

**Issue by RedEyedRocker** [Monika-After-Story/MonikaModDev#4967]
So I have a minor feedback, today, I woke up like around 4 AM and Monika greeted me and hoped I had a good rest. After an hour, I told her that I'll be going away to eat and then she says that it's middle of the night and if she were me, she would've eaten earlier and also been in bed by now and tells me goodnight. Later after I came back, she tells me that I should really get some sleep. This kind of breaks immersion so it'd be better if she says what she usually says during the day when she knows the player has already slept.

**Comment by Rai99** [comment]
Late night topic reactions are likely going to be handled with #4914 to make more sense when it comes to those scenarios.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
