### ISSUE TITLE
Altering official art outfits for spritepacks?

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#4969]
I've been thinking about making some alternate colored/slightly modified versions of currently existing official outfits, like the sundress and blazerless uniform. 

I know that doing this just for my personal use is probably alright(?) but I wasn't sure if it was okay to post my results as an unofficial spritepack. The blazer uniform and ribbon seem pretty safe since they're DDLC assets to begin with, but stuff made by the MAS team seems like more of a grey area to me, so I didn't want to do so without checking in first.

**Comment by Rai99** [comment]
As far as I know, people are free to make spritepacks of anything they want. You can make anything for yourself, and you can probably release it for other people, but even if you can't, you should be free to use it in your own game. 

There are already released ribbons with different textures and patterns released, so I don't see why this wouldn't be allowed.

**Comment by thezotikrus** [comment]
As long as you use those assets for MAS you should be fine.
https://github.com/Monika-After-Story/MonikaModDev/issues/3174
> Creations/Modifications/Edits based off these sprite sets are not permitted for use outside of the Monika After Story Mod without express consent from the Monika After Story team or the creator of said art.

**Comment by Orcaramelo** [comment]
If only official MAS assets are being used that should be fine! But yeah spritepack assets would need permission from artists.
And of course, MAS assets don't leave MAS.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
