### ISSUE TITLE
[Suggestion] - Change Piano mixer

### ISSUE THREAD

**Issue by thezotikrus** [Monika-After-Story/MonikaModDev#4970]
Right now the Piano game uses UI (`audio`) mixer. I suggest to change it to the `music` mixer as more appropriate.
I don't like the UI sounds and turn them off mostly, so I have to adjust setting every time I play the piano. While I understand it can be a inconvenience only for me, I want to at least bring it up to discuss.
- it won't hurt anyone who uses UI sounds, but will help people who don't use them at all
- It should be very easy to do (like a line of code, I think)
- we play music on the piano ffs

And while we discuss mixers, can I also suggest to make one for notifications? And set its volume in the alerts menu? (Although it's even more minor thing than the piano)

**Comment by ThePotatoGuy** [comment]
audio is the only mixer that allows for simultaneous sounds so its ideal for a piano.

 notifications sounds i think is controlled by windows @multimokia

**Comment by multimokia** [comment]
Notifs depends. If you disabled the windows based ones, then it's an in MAS sound as well. Uses the ui sounds one

**Comment by ThePotatoGuy** [comment]
since notifications are basically UI, i think we should keep things as is.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
