### ISSUE TITLE
MAS files won't update

### ISSUE THREAD

**Issue by trimiowo** [Monika-After-Story/MonikaModDev#4972]
Hey, so I noticed my game started to lag a little and I wanted to get a save file just in case I crash or something. But, the files hasn't updated til 10/27/19 which scares me a little. Is there a way to fix this?

**Comment by multimokia** [comment]
Which files are you looking at which haven't updated?

**Comment by trimiowo** [comment]
my persistent

**Comment by multimokia** [comment]
Where exactly are you looking for your persistent?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
