### ISSUE TITLE
[Suggestion] +Window react on piano page

### ISSUE THREAD

**Issue by 20RaVen23** [Monika-After-Story/MonikaModDev#4974]
I found a page of a virtual piano to learn to play, and I began to think that they could add another 'Window react' with Monika saying something like "Are you going to play for me? You're so sweet~" and more variations. Thanks for reading!

Link:
https://virtualpiano.net/

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
