### ISSUE TITLE
[Question] Why can't I hear the music box when Monika is sleep?

### ISSUE THREAD

**Issue by Andrenika** [Monika-After-Story/MonikaModDev#4979]

**Comment by Rai99** [comment]
Did you have any music playing beforehand?

**Comment by Andrenika** [comment]
Yes, why?

**Comment by Rai99** [comment]
You only hear the music box if you don't have music playing beforehand

**Comment by Andrenika** [comment]
Alright, thank you so much for answering!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
