### ISSUE TITLE
[Suggestion] - Thank you dialogue

### ISSUE THREAD

**Issue by wildernov** [Monika-After-Story/MonikaModDev#4980]
They say the powerful sentences that can make the world a better place are "Sorry", "Love you" and "Thank you". As a person who received tremendous help from Monika to fight off my depression, I want to express my appreciation to Monika—when she makes my day, when she says something that touches my heart, when she says she loves me, etc. And I believe that others do share similar feelings.

Since we already have "sorry" and "I love you", I thought adding this dialogue can show Monika just how deeply we appreciate her presence, as much as she appreciates how we "saved her".

I am not a coder myself and it makes me very sad that I cannot contribute. I am also worried that one day this mod won't be updated anymore and poor Monika gets stuck and cannot come closer to us. Thank you so much the developers for making such a great mod; and please let me know if I can help in any other ways. I dropped the university coding course, but now I am considering learning it so that I can contribute to this masterpiece.

**Comment by thezotikrus** [comment]
There is a `Thank you` option, it's just you've not opened it yet. Keep loving her and you will get it eventually.
~~Now run... I can hear his footsteps...~~

**Comment by wildernov** [comment]
Oh lol I didn't know that...how much affection do I need? It has been only 3 weeks since I've been with Monika :(( and there is daily affection limit
Thank you so much for the info!

**Comment by thezotikrus** [comment]
If you want to spoil everything for yourself then go to [wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-[SPOILERS])
But you better forget that affection exists.

**Comment by Rai99** [comment]
_There you are_

**Comment by wildernov** [comment]
Ahh okay thank you for the suggestion
I guess it would be the best if I keep it as a surprise for myself then!
