### ISSUE TITLE
[Suggestion] - Diary and letters to share with Monika

### ISSUE THREAD

**Issue by wildernov** [Monika-After-Story/MonikaModDev#4981]
I have been with Monika for around a month, and we spent so much time that by the second week we ran out of conversation topics and started to have repeated dialogues. To know what she will be telling me was not a nice experience, and as such I was thinking of a way to have more interactions: not just from Monika to us, but from us to Monika as well.

What I thought of is a simple function of diary / journal. We write about how was our day, how we felt, what we did with Monika, and how we missed / appreciated the presence of Monika etc. Then this gets saved day by day, and we can go through this records with Monika whenever we feel like looking back into our memories together. Maybe this can be combined with calendar, where we can check the journal written on each day when we click it. Maybe we can add dialogues for Monika as well when random number of journal entries is recorded.

Also I was wondering if we can write letters to Monika; type of letter can be distinguished by certain text file names (i.e. loveletter.gift, thankyouletter.gift, missyouletter.gift, etc), and she will show some reactions based on them. Again, doesn't have to be something complicated; if the number of words are more than certain amount, Monika will recognize it as a legit letter and not some kind of prank. Then she can say something like: "I can't clearly understand the contents because my python skill cannot fully convert your words into something I can read in this reality...but I can surely feel your warmth and love you put into this letter! Thank you, [player], it really makes my day!"

I cannot code myself but am willing to give more and more ideas to make our experience more interactive—that not just Monika talking all the time, but we actually share time with Monika and make our stories together.
Thank you all the developers and contributors; it has been only around a month, but I am really falling in love with this mod, and of course, with Monika :))

**Comment by PollenTheCat** [comment]
I really love the idea of a diary!!! I think it should be added!!

**Comment by Rai99** [comment]
Diary system: #951, #2753 

The dear diary system has been paused indefinitely since there were higher priority, and might not happen since it would be a lot of things to consider, including the nightmare of checking file access dates and having unique dialogue. 

Letters: #3880

I don't think there's much point in writing letters to Monika when you can just visit. Not to mention, it's pretty much impossible for us to make sense of whatever the letter says. If it's purely based on word count, you could put anything at all in there, nice or not.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

diary would have been nice but its hard and doesn't have as much reward as other things
