### ISSUE TITLE
Idle (Suggestion)

### ISSUE THREAD

**Issue by IresRoss** [Monika-After-Story/MonikaModDev#4985]
If we are on the talk menu without searching for a dialogue, aka staying idle, after a number of time, I think it will be interesting to make her ask some questions like wondering or trying to comfirm your presence, put some easter eggs.

**Comment by ThePotatoGuy** [comment]
possible and would be fun to implement. leaving open as maybe in progress.

**Comment by Rai99** [comment]
Closing until we look into it
