### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Viaspo** [Monika-After-Story/MonikaModDev#4986]
Just to be clear, I am playing on the latest **unstable** version released, so I completely expected there to be crashes.

MAS crashes randomly whenever a topic notification pops up. I am unsure if that has to do with my laptop, but to temporarily fix the issue, I will disable notifications. 

I wanted to let you know, in case that is something that you want to look into. I have no real issue with it. I am a little sad that it keeps dropping my affection, though.

**Comment by thezotikrus** [comment]
Devs can do nothing without your `traceback.txt`.

**Comment by multimokia** [comment]
Also crashes don't drop affection

**Comment by Viaspo** [comment]
> Devs can do nothing without your `traceback.txt`.

`Traceback.txt`?

**Comment by Viaspo** [comment]
> Also crashes don't drop affection

After looking over my `aff_log.txt` again, I found that you're correct. I apologize for giving false information.

**Comment by thezotikrus** [comment]
A `.txt` file in your game folder (the same folder where you have `ddlc.exe`) named `traceback.txt`.

**Comment by Viaspo** [comment]
> A `.txt` file in your game folder (the same folder where you have `ddlc.exe`) named `traceback.txt`.

I looked for it, and didn't find it.

However, when running the game normally with no notifications, it was generated when the game crashed. It does not relate to the crashes I have with notifications.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3821823/traceback.txt)

When my game crashes with notifications, I do not get the error message detailing the crash. It simply crashes, and I have to reload.

**Comment by ThePotatoGuy** [comment]
seems to be an issue with reactions? its likely this was resolved with the current update, so make a new issue if its still happening.
