### ISSUE TITLE
[Question] Does Monika know that I have been absence for a long time? 

### ISSUE THREAD

**Issue by Andy0the00Dovokino** [Monika-After-Story/MonikaModDev#4987]
I haven't talked to for Tuesday- Thursday (Nov.5-7) and when I came back, she hasn't noticed that I have been absence for 3 days, unless I have to increase my affection for her to unlock that feature.

**Comment by multimokia** [comment]
Affection drops after 7 consecutive days of absence. If you're within that, you're fine.

**Comment by Andy0the00Dovokino** [comment]
Well I wasn't asking for that specifically, but thanks for the answer.

**Comment by ThePotatoGuy** [comment]
I don't think there are any dialogue triggers for absence time, but there is a function to check for this so its very much possible to do.
[closing as resolved]
