### ISSUE TITLE
[Suggestion] Class Goodbye Dialogue

### ISSUE THREAD

**Issue by Nik15GH** [Monika-After-Story/MonikaModDev#4989]
I noticed while randomly stumbling upon bidding Monika Goodbye to go to class that she doesnt question this when doing so on a Sunday. I think it would be interesting if she would have a dialogue questioning it if you tell her goodbye to go to class on Saturday/Sunday

**Comment by RavenPLAYER** [comment]
Good idea!

**Comment by lunulae** [comment]
I like this idea, though I'd like if it doesn't lock the option. I'm no longer in school but I attend hobby classes at times, which can be anytime in the week.

**Comment by Nik15GH** [comment]
That could probably also be put in, just that I had the idea she asks a bit more when you bid her goodbye for class on weekends.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
