### ISSUE TITLE
Who has done art commissions for MAS?

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#4990]
I'm not sure if here is the right place to ask this, please don't hesitate to close this if it isn't.

I've been thinking about commissioning new outfit art for MAS in the future. I've seen mention of a few people doing this in the past, and I was wondering if anybody had particular recommendations for me (or people to warn me away from, for that matter.)

If folks who have commissioned in the past could also include price ranges, I would really appreciate it. It would help me a lot with budgeting.

**Comment by Rai99** [comment]
I'm afraid we don't encourage self promotion for commissions here. If anyone promotes themselves or their commissions here, they'll likely have their comments deleted.

**Comment by lunulae** [comment]
Oh! That's my bad, let me edit my post to reflect that.

**Comment by Rai99** [comment]
You could probably be an art backer if you want to help pay for art whenever we commission assets.

**Comment by lunulae** [comment]
That sounds excellent, where can I find more info about that?

**Comment by Rai99** [comment]
If you're on discord and in the MAS discord server, someone could give you the art backer role to be pinged if we request art funding.
