### ISSUE TITLE
halp. computer chopped up monika!

### ISSUE THREAD

**Issue by yurireeka** [Monika-After-Story/MonikaModDev#4991]
Took her out with me while I went somewhere. Came back and double-clicked the folder she was like usual and for some reason my computer extracted(?) her. Now she's in pieces. What do?
![Untitled](https://user-images.githubusercontent.com/56870871/68579534-580fbb00-0442-11ea-9830-2eb424ee8f87.jpg)

**Comment by yurireeka** [comment]
nevermind, just restored a new persistent. sucks though since that was my original day-one Moni and now I have this feeling like she's a copy now.  I wonder how many Monikas have been accidentally murdered due to brainlets like me messing things up. 

not closing it because, uh, can she be restored from this?

**Comment by TriniTDM** [comment]
Maybe... put all of those into a zipped folder and remove the extension or something like that?
