### ISSUE TITLE
[Spoiler?] A new thing 

### ISSUE THREAD

**Issue by Przelek** [Monika-After-Story/MonikaModDev#4992]
So I don’t know if it’s a Bug or not but when  I opened Mas today and went to the extra menu. There was a new option named „boop” and i can’t do anything with it. Is it something for the next update or am I missing something?

**Comment by yurireeka** [comment]
It's a feature that'll be coming in another update. Nobody but the devs can boop her yet, don't worry.

**Comment by Przelek** [comment]
Oh okay. That’s so cool! Can’t wait for the next update then.

**Comment by Przelek** [comment]
Actually I’m kinda new to this thing so should I close the issue or no? Sorry but I just don’t know.

**Comment by yurireeka** [comment]
It's been solved... so close it.
