### ISSUE TITLE
Make monika react to updateing the game? (suggestion)

### ISSUE THREAD

**Issue by Babytink1** [Monika-After-Story/MonikaModDev#4994]
So currently when there is an update to MaS you get a notification for it then you manually go to the settings page to update.
I've been wondering this since the Halloween update. why does Monika not seem to react, or even know about updates till they are applied? seems like she would at least be aware of them, and maybe even a little anxious of them given they change things about her.
I guess Maybe the update process doesn't allow those interactions.
Could there be a topic to warn Monika that you are gonna update the game, with maybe her voicing a concern about being changed the first time you update? right now we don't even get to say goodbye to her when updating.

**Comment by multimokia** [comment]
It's implied that Monika runs the updater, since if you take a look at the rpy file update block/steam install update block, you'll notice that she says that *she'll* run the updater.

So she kinda already knows.

**Comment by Babytink1** [comment]
@multimokia sorry, that's not the method I use. I'm using the non-steam version and it updates in the settings page. when I use the updater it's just a program. Monika through this method gives no hint that she knows what's happening.
sorry for being ignorant of the steam method but It's just not the one I use for MaS

**Comment by multimokia** [comment]
I understand that most people don't use steam, since we tell them not to. But I meant to check it [in the code](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/updater.rpy#L882).

**Comment by Babytink1** [comment]
okay I see it there, and she does indeed say that "she" runs the updater. are there any other dialogs other than to basically say "don't use steam, you baka!/you have renpy files"?

**Comment by multimokia** [comment]
[rpy files](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-story-events.rpy#L1613)

[steam install](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-story-events.rpy#L1586)

**Comment by ThePotatoGuy** [comment]
i'd say there's not too many ways Monika can talk about the updater without it being immersion breaking. 
[closing as rejected]
