### ISSUE TITLE
[Suggestion] "Virtual YouTuber" topic follow-up

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4995]
At the end of the Virtual YouTuber topic, Monika says she 'can't wait to finish the series'.
I was thinking perhaps we could have a follow-up that comes after some time, about her thoughts on how Ai-chan reacted to her, etc?

**Comment by FrikiHD** [comment]
Good idea

**Comment by ThePotatoGuy** [comment]
agree that this should be done since it's been a while since the series was finished. marking as high priority, but closing until we look into it.
