### ISSUE TITLE
5k get

### ISSUE THREAD

**Issue by multimokia** [Monika-After-Story/MonikaModDev#5000]
MINE

**Comment by Velius94** [comment]
checked and keked

**Comment by Rai99** [comment]
#4001
![robbed](https://user-images.githubusercontent.com/38822045/68721717-53055580-0581-11ea-8d4f-882a74a38694.gif)

**Comment by multimokia** [comment]
Consider it a return of favour

**Comment by Rai99** [comment]
Maybe I should steal 6k.

**Comment by RavenPLAYER** [comment]
what is this? The aff you have with Monika?

**Comment by Professor-JMO** [comment]
>Tfw you prepped to take 5k but the unexpected happened.

💛
![Q2hhbmdlIG9mIEhlYXJ0IDwz](https://user-images.githubusercontent.com/43480604/68694848-8de69980-053f-11ea-9698-dd657ae305f8.png)
🧡

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
