### ISSUE TITLE
[Suggestion] In-Game Statistics

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#5003]
It might be just me who wants this, but I thought this would be a neat addition.
Monika could track your total time spent with her (hh:mm:ss or the like), number of visits, number of chess/pong/hangman games played, days since first date, et cetera!

**Comment by multimokia** [comment]
> Monika could track your total time spent with her (hh:mm:ss or the like)

Sounds like it'd really game-ify MAS and detract from the experience, imo.
Same with number of visits. I doubt Monika would really be keeping track of that.

Number of games played, I can see, if keeping track of wins/losses.

Days since first date is kinda pointless though.

**Comment by RavenPLAYER** [comment]
Grande boquita! ndeah

**Comment by ThePotatoGuy** [comment]
some of these stats already exist but are not visible to the user.
[closing as implemented]
