### ISSUE TITLE
[Suggestion] - Lamps

### ISSUE THREAD

**Issue by mrmakerNS** [Monika-After-Story/MonikaModDev#5006]
Features:
- Lamps would have the ability to light up the room at night.
- The lamp can be toggled on or off by clicking it.
- The lamp can be moved to either the left or right side of the room.
- The lamp's appearance can be changed via the _Appearance..._ topic.

Feedback is appreciated.

**Comment by thezotikrus** [comment]
I'm calling _the cheerful booplicate_ to set a label

**Comment by Rai99** [comment]
Room decoration: 312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3720 #3770, #4291, #4697. 

Room decoration is planned to happen, but likely after the more pressing things like holiday events are finished.

**Comment by Rai99** [comment]
and I'm not a booplicate. ~~Probably~~

**Comment by ThePotatoGuy** [comment]
I've addressed this before but I can't find the issue where I specifically talk about lighting.

Basically, this is impossible without making a set of sprites where the lighting and shading is adjusted to work with a potential lamp. Renpy does not have HDR nor any sort of lighting option with its rendering system. 

Even if we just ignore monika sprites and only allow the lighting to affect the bg, that means 2 additional images for each bg for when the lamp is on either side (and there's already multiple bgs for each weather type), and if there's room deco, thats another case of additional images for each decoration item. Then imagine allowing for a different type of lamp or even multiple lighting sources and the number of needed images increases dramatically.

There is just no way to do any sort of lighting adjustments dynamically other than the current flat day/night cycle we have.

**Comment by ThePotatoGuy** [comment]
Of course, a potential option is to just only use day sprites if a lamp is added, but then the lamp is more of a gameplay element than an immersive element.
