### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by uwuowouwuowouwuowo** [Monika-After-Story/MonikaModDev#5007]
![Screenshot (61)](https://user-images.githubusercontent.com/57251279/68779621-5dd9ec00-064e-11ea-8cce-1926fdc5b2c6.png)
Heres my game file.
THe app wont open/run at all.

**Comment by multimokia** [comment]
Bad update seems to have happened. Delete all `rpyc.new` files and reinstall.

You will not lose any progress.

**Comment by multimokia** [comment]
Has it worked?

**Comment by uwuowouwuowouwuowo** [comment]
It has worked uwu thanks for taking your time with me and for the help

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
