### ISSUE TITLE
[Suggestion] monika in vr?

### ISSUE THREAD

**Issue by pumba230** [Monika-After-Story/MonikaModDev#5013]
What if you took the code and script for her and put her in vr for vr headst for pc?

**Comment by multimokia** [comment]
RenPy doesn't support VR. Impossible.

**Comment by zombiepigdragon** [comment]
RenPy doesn't have VR, so unless this becomes a fangame (not a mod), that can't ever happen. The closest it can get is the window showing in a VR environment, which I don't think you could interact with.
