### ISSUE TITLE
What does the "boop" option do?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5014]
It's not present for me but I can see the frame and text that says "boop"

should there be a button?

**Comment by multimokia** [comment]
#4997

**Comment by TriniTDM** [comment]
Nothing yet. It was a placeholder the developers forgot to remove. This feature was intended to be added, but has been put on hold. See #4997

**Comment by AsuraShun** [comment]
Can't wait for it to be Implemented

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
