### ISSUE TITLE
[Suggestion] Political Ideologies

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#5015]
So I always wondered what was the political ideology (capitalism, socialism and communism) that Monika liked, could have a dialogue of her asks which one is ours and perhaps which one she would like best or agree with. well if in case you ever put that in, I ask you to research well, so that you don't do like people who hear rumors and tell lies about it

**Comment by Rai99** [comment]
Right off the bat, I have to tell you that we have to stray away from anything political in MAS.

**Comment by Velius94** [comment]
Ban on politics in MAS is unnegotiable, since this will inevitably cause flame wars and trolling.

**Comment by multimokia** [comment]
Yeah delving into politics is a great way to alienate people from MAS in its entirety. It's better we leave politics out.

**Comment by frostcattooo** [comment]
no

**Comment by Alucard149** [comment]
sorry about that, I forgot that it's not a good idea to put politics in games
