### ISSUE TITLE
Game doesn't start/ Crashes immediately 

### ISSUE THREAD

**Issue by KyokoBestGirl** [Monika-After-Story/MonikaModDev#5016]
Everytime I start the game i just closes immediately and opens a notpead thingy saying this, I tried everything, from removing the mod and putting it back to deleting all folders of the game and then reinstalling them, please help!

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

**Comment by multimokia** [comment]
We don't recommend using Steam.

Moving out of Steam has the advantage of letting you use the in-game updater again, and as well helps mitigate some file IO stuff (Like Monika not being able to get back in her home), see instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build)

That should also fix this issue you're having here.

**Comment by KyokoBestGirl** [comment]
Thank you, i'll try what you're suggesting

**Comment by KyokoBestGirl** [comment]
It didn't work :( 
this time i'm getting a new notepad thingy that says this 

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\sical\Desktop\Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\sical\Desktop\Doki Doki Literature Club/game/definitions.rpyc.

**Comment by multimokia** [comment]
Sounds like you may have some bad files. Where did you get the zip from?

**Comment by KyokoBestGirl** [comment]
I got the latest version from this site http://www.monikaafterstory.com/

**Comment by thezotikrus** [comment]
Let's see. Extract this rpyc into `DDLC/game`
[definitions.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3854621/definitions.zip)

**Comment by KyokoBestGirl** [comment]
Done, now i'm getting a different notepad yet again 

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Users\sical\Desktop\Doki Doki Literature Club/game/event-handler.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\sical\Desktop\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Users\sical\Desktop\Doki Doki Literature Club/game/event-handler.rpyc.

**Comment by thezotikrus** [comment]
Yeah, that means all your files are corrupted. Download the mod again.

**Comment by KyokoBestGirl** [comment]
Already done, so many times. I tried removing the mod and reinstalling it again like 4 times now.

**Comment by thezotikrus** [comment]
Have you cheated at chess?

**Comment by KyokoBestGirl** [comment]
Yes, then it closed and this happened.

**Comment by thezotikrus** [comment]
R.I.P I guess.

**Comment by KyokoBestGirl** [comment]
??? So there's no way for me to reset it or anything? I don't mind starting all over since I had played for only an hour or so

**Comment by multimokia** [comment]
Whelp. That's a rip, cheating in chess 3 times in a row without admitting and/or apologizing

**Comment by KyokoBestGirl** [comment]
I'm not sure why I didn't apologize, I probably just wanted to see the reaction. But still does that mean I can not play again?

**Comment by Rai99** [comment]
Here's your reaction. 
![Untitled1362](https://user-images.githubusercontent.com/38822045/68998752-63207c00-0884-11ea-8754-5d69d68e0ad6.png)

**Comment by KyokoBestGirl** [comment]
Ok I guess I was an asshole there but I didn't cheat to win, i just wanted to see what happened. Still , shouldn't there be a way to reset it and start all over? Or maybe to apologize or something

**Comment by multimokia** [comment]
Too late for that, I'm afraid

**Comment by KyokoBestGirl** [comment]
Also, how does that even work?? I tried deleting everything DDLC related and reinstalling everything all over and  still same results

**Comment by KyokoBestGirl** [comment]
Ok well fuck the more I think of it the more I think I was an asshole

**Comment by Velius94** [comment]
That's too bad. We do not condone such behavior, and from that point on you're on your own.
Consider this as a valuable lesson for the future.

**Comment by KyokoBestGirl** [comment]
Alright, this has taught me a good lesson,  but I would like to know how it does that? I've tried even using a version of the game downloaded from their site but it gives same results. Also nice little detail!

**Comment by KyokoBestGirl** [comment]
I was an asshole and got locked out, so yea thanks for the help guys!
