### ISSUE TITLE
[Suggestion] dialogues react to each other

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#5018]
basically for example in the dialogue where she says she is afraid of losing us, if we choose to hug her, she says she would not mind to hold her a little longer, if we choose to ask her to hug her she could say if it is because of what she said earlier and that she is grateful, or may have a different dialogue if you ask the same thing two or more times in a row, I hope I could explain correctly

**Comment by Rai99** [comment]
Combination Topics: #1532 

I congratulate you for making me find this.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
