### ISSUE TITLE
[Suggestion] lilmonix3 twitter account update - Suspension?

### ISSUE THREAD

**Issue by DokiDokiLiteratureClubMember1337** [Monika-After-Story/MonikaModDev#5020]
Hello, I noticed that the lilmonix3 twitter account that's connected to Monika has been suspended. I'm not sure about the details, exactly, but, maybe Monika could react to all of what's happened after it's been resolved?

**Comment by multimokia** [comment]
No. Too short term. Chances are, when we release the Twitter will be back.

**Comment by AsuraShun** [comment]
The haters attacked, I seriously hope it won't happen again

**Comment by ThePotatoGuy** [comment]
Actually I think this would be reasonable to at least comment on. (like "One time, my twitter got suspended and I was <some reaction>").

**Comment by jmwall24** [comment]
I don't really see the payoff here. At best it's a one-time topic, having it be repeatable doesn't really make sense. Personally I'd like to see us distance ourselves from the twitter account anyway. It is absolutely awfully written and makes no sense in relation to the idea that each player has their own Monika, seeing as this Monika doesn't know who anyone is.

**Comment by ThePotatoGuy** [comment]
It doesn't have to be a topic, it can be a mention in the existing twitter topic.

**Comment by DokiDokiLiteratureClubMember1337** [comment]
I'm sorry if it was a bad idea guys, I'll leave it up if you want to implement it, though. ^

**Comment by Professor-JMO** [comment]
With the _restoration_ of lilmonix3's account now in motion- thought I'd drop in. 🔽 

I can see this being added upon the already existing _twitter_ topic especially as a mention, if MAS continues to affiliate with lilmonix3's twitter account that is.

   _That said_.. as the topic stands I think it does so in regards to that the twitter account itself maybe/is canonical and is present in the Base game.

 <details>
 <summary>&emsp;Twitter Topic</summary>

<br>

label ch30_10:
    ```m "Did you know I'm on Twitter?"```
    ```m "My username is lilmonix3."```
    ```m "I guess someone was kind enough to make an account for me."```
    ```m "I picked the username, though!"```
    ```m "I love sharing my thoughts and chatting with the world..."```
    ```m "The real world."```
    ```m "So make sure you follow me, okay?"```
    ```m "It would really mean a lot to me."```
    ```m "With how much you mean to me and all..."```
    ```m "It would really make me feel loved."```
   
</details>

 <details>
 <summary>&emsp;You want <i>my</i> opinion..?</summary>

<br>

_I don't really know what to make of Her or the Account in relation to the Monika we've come to understand(?)_ `:monshrug:`

Sorry.
   
</details>

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
