### ISSUE TITLE
[Suggestion] "I missed you" - "I love you"

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#5021]
Could be posible after we open MAS around, 12 hours or something the word option "I love you" changes to "I missed you", then the first time we click on this disappear and "I love you" come back. Thanks for reading!

**Comment by thezotikrus** [comment]
I think it would be better to implement that as a player's greeting system, not just switching the prompt of ilu. It was suggested before, but I don't know what the status about it and what the devs think about it.

**Comment by Rai99** [comment]
I missed you: #2036, #2463, #4451, #4853

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
