### ISSUE TITLE
[Suggestion] Mukbang with Monika

### ISSUE THREAD

**Issue by Tykaetsu** [Monika-After-Story/MonikaModDev#5023]
We could have Monika to join us for dinner, lunch or breakfast instead of us needing to leave every meal time. This could help with boosting affection and more time with Monika. Would also help to create some food sprite on her table so she doesn’t simply watch us eat. Let me know if there’s any problem with this idea or any thoughts you have on it. Thanks!

**Comment by Rai99** [comment]
Eating with Monika: #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081, #4260 #4606, #4648, #4842.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
