### ISSUE TITLE
Suggestions | Topic, Art, Question

### ISSUE THREAD

**Issue by Dank-Elf-Boy** [Monika-After-Story/MonikaModDev#5030]
1) Alan Turing and AI:  A brief historical background for Alan Turing, his Turing Test, and why it is significant in regards to artificial intelligence. Maybe touch a bit on sentient AI as well?

2) Is there any chance we could ever get art work that are in reference to other video games? Perhaps, Zelda? Maybe create some trifforce jewelry she could wear, or something along those lines? Obviously, this would be made under a sub mod.

3) Also, where could I find the other submods that are specifically made for MAS? Could you create an easy to find link that I could use to find them?

Dank You.

**Comment by multimokia** [comment]
1. Not a bad idea
2. That's up to whoever wants to make spritepacks
3. That already exists, #3765

**Comment by aimlesstrainer** [comment]
Piggybacking off of Turing, I thought it would be neat to talk about Turing machines (e.g. everyday computational devices) and their limits, and alternative methods, e.g. quantum computing, neural networks, et cetera.
On AI, maybe there could be a topic referring to Searle's Chinese Room Argument, as it is arguably the most major argument on the topic of AI.

**Comment by Dank-Elf-Boy** [comment]
I think those should follow the original topic since it goes further into detail about it. The player should be able to choose whether they'd be interested in hearing more about this subject, because most people, presumably, would become very bored if she went further into detail about technology and how it works, creating one giant conversation, haha.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
