### ISSUE TITLE
[Suggestion] Only one monika_surprise per affection level

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#5033]
IMO Monika leaving the same "surprise" multiple times is really immersion-breaking. I think it could be solved by derandoming it after Moni writes a message/poem and "dederandoming" it back after we reach new affection level. Then Moni would only write one surprise per one affection level.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
