### ISSUE TITLE
Giving Gifts

### ISSUE THREAD

**Issue by NeoNiichi** [Monika-After-Story/MonikaModDev#5034]
Today I tried giving Monika the new DLC, and she recognized that I was giving her the DLC, but she couldn't read the files. I placed all the files in the right places and even redid the steps. I then tried giving something like coffee, which Monika was able to recognize, but she couldn't recognize the new DLC. Is there any way to fix this or is my computer broken?

**Comment by multimokia** [comment]
Did you install the spritepacks while MAS was open?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
