### ISSUE TITLE
window react 

### ISSUE THREAD

**Issue by Sirexia** [Monika-After-Story/MonikaModDev#5035]
window react does not work for me and i have it enabled does anyone know what could be wrong

**Comment by multimokia** [comment]
Do you have the alerts enabled in the `Alerts` menu?

**Comment by Sirexia** [comment]
> Do you have the alerts enabled in the `Alerts` menu?

yeah its enabled

**Comment by thezotikrus** [comment]
Enabled both **Windows Reacts** and **Window Reactions**?

**Comment by Sirexia** [comment]
> Enabled both **Windows Reacts** and **Window Reactions**?yes
