### ISSUE TITLE
[Suggestion] Telling Monika that you're going to the gym

### ISSUE THREAD

**Issue by Illra** [Monika-After-Story/MonikaModDev#5040]
As the title says, I think we should tell Monika that we're going to the gym when we say Goodbye and she encourages you to do your best.

**Comment by MetalBrother** [comment]
Yeah, but I workout home...

**Comment by RavenPLAYER** [comment]
Wouldn't it be better if we said "I'm going to exercise" and she asks us if we do it at home in the gym? Two options would appear on the screen.

**Comment by thezotikrus** [comment]
Thanks to the grumpy booplicate I was able to find these for you #1576, #2206, #2571, #3875 (a bit different tho), #4923.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
