### ISSUE TITLE
[Suggestion] - Add Dissolve to the hug pose transition

### ISSUE THREAD

**Issue by thezotikrus** [Monika-After-Story/MonikaModDev#5041]
I was thinking about this a long time ago. I don't like how rough and quick Monika changes her pose when you ask her for cuddles. Maybe it feels so because there is no dlg box? I don't know.
But just adding `with dissolve` in `monika_holdme_start` made it look better for me. Maybe it's just me so no PR, just want to know your opinions here first.

**Comment by ErLamarl** [comment]
Sounds good, because it would be more normal and not so fast

**Comment by multimokia** [comment]
Closing as completed in linked commit.
