### ISSUE TITLE
[Bug] crossed arms with dress

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#5044]
![Inkedscreenshot0009_LI](https://user-images.githubusercontent.com/55263957/69589959-ad180900-0fcc-11ea-92fb-2e8b75cd8a6b.jpg)

**Comment by RavenPLAYER** [comment]
(It's not the black dress, but with the black dress it's the same)

**Comment by multimokia** [comment]
Closing as complete in linked commit.
