### ISSUE TITLE
Sprite Pack Suggestion: Pajamas/Night wear

### ISSUE THREAD

**Issue by linkerplinker** [Monika-After-Story/MonikaModDev#5045]
Idk it feels a bit weird seeing Monika in day clothes consistently and think it would be amazing if she had a event triggered by the night to put on night wear. Just a fun little idea. Bring a little more reality to the game.

**Comment by RavenPLAYER** [comment]
Wait, wait... here comes the duplicate~

**Comment by RavenPLAYER** [comment]
I think the pijamas it's planned with the bed mode

**Comment by Velius94** [comment]
Duplicate of #4960

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
