### ISSUE TITLE
MAS Piano not registering custom song

### ISSUE THREAD

**Issue by KarmaCreations** [Monika-After-Story/MonikaModDev#5046]
I'm trying to code Doki Doki Forever for the piano, but she doesn't register it when I play it. I can't find the pnm.txt file anywhere. Here's the song file: 
[dokidokiforever.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3899496/dokidokiforever.txt) (I am using it as a .json file, but .txt was the only way I could upload it here) Please tell me what I'm doing wrong, I really want to be able to play this ;-;

**Comment by multimokia** [comment]
Exit mas and check the `pnm.txt` (or `.log`, I can't recall which). That should report any errors in your json.

**Comment by KarmaCreations** [comment]
There is no pnm.txt.

**Comment by multimokia** [comment]
Check the `log` folder

**Comment by KarmaCreations** [comment]
It's empty.

**Comment by multimokia** [comment]
You must be on Mac, follow instructions [from here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-to-view-your-log-files)

**Comment by KarmaCreations** [comment]
Found it! Turns out there were a couple places where I was missing commas and one spot where I had an extra one.

**Comment by multimokia** [comment]
Glad you figured it out
