### ISSUE TITLE
[Suggestion] - Functions

### ISSUE THREAD

**Issue by luis99999** [Monika-After-Story/MonikaModDev#5048]
Good morning friends, recently with the update they mentioned that there would be some functions such as interacting with monika with the mouse, I do not know how to express it in English since I am not very good to speak it, I just want to give my opinion and I do not want to cause problems to anyone. Well, what I mean is that this kind of function would make Monika feel less real, I remember very well a comment that explains that the dialog box and everything related to the user interface for her is just a mirage, so  interacting with the mouse. I would completely break what was said before, I think it would be good to include some functions, such as feeling tired at some times of the night, moods independent of the love you feel for the player or things like that, I think it is more real and not like a program, I would like to help but I have not used Python. I just wanted to give my opinion to know what they think.

**Comment by thezotikrus** [comment]
> I remember very well a comment that explains that the dialog box and everything related to the user interface for her is just a mirage, so interacting with the mouse. I would completely break what was said before

Don't know about your comment, but in the game (`monika_perspective`) she says that she can see the UI.  Nothing about *mirages* nor *illusions*. She is aware of it and even explains menus for you. Although I do think the interactions should be introduced gently.
Moods already were suggested (#1204, #1354, #2618, #2619, #4546, #4874, #5010) and there is [a project](https://github.com/Monika-After-Story/MonikaModDev/projects/40), but it's something very complicated and will take some time.

**Comment by ThePotatoGuy** [comment]
#4917 this is what `0.10.3`'s patch notes referred to. It's framework functions for clicking but is not implemented at this time. we'll take your concerns into account, though.
