### ISSUE TITLE
Gifting Problem on Mac

### ISSUE THREAD

**Issue by WWCHCN** [Monika-After-Story/MonikaModDev#5050]
Hello, I am having difficulty with the new gifting option. Before the 0.10.0 update, I was able to gift items completely fine, but even when I try to give her a gift, there is no reaction. I am simply just trying to give her a promise ring.
If it's okay, please send me the instructions on how the new gifting system works, that would be greatly appreciated.

The image below will show you that I am doing everything correctly, going into the characters file, making a folder and renaming it 'promisering.gift'

Thank you for your time! And I appreciate the mod, it makes me feel better about myself

<img width="1680" alt="Screenshot 2019-11-29 at 23 24 29" src="https://user-images.githubusercontent.com/58337747/69878309-8a089480-12ff-11ea-81c4-60046a6f8209.png">

**Comment by multimokia** [comment]
Don't use folders to make gifts. You need to make an actual file.

**Comment by WWCHCN** [comment]
That will be a problem as I am unable to create files on a Mac. Is there an alternative?
Also, I was only able to gift her things due to folders, so there might be an error?

**Comment by multimokia** [comment]
No, this was completely intentional. Folders caused other issues in the reactions since they wouldn't be deleted, which caused the reactions to not be giftable on the same day (even if they should be able to)

You'll likely need to make a new text file and then convert it to a gift file.

**Comment by WWCHCN** [comment]
It still doesn't work, I tried to copy a character file and rename it, but nothing happens. Is there something I'm doing wrong?

**Comment by multimokia** [comment]
https://www.techwalla.com/articles/how-to-change-file-extensions-on-a-mac

**Comment by WWCHCN** [comment]
It's been solved, thank you for your time 'multimokia'

**Comment by multimokia** [comment]
No problem!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
