### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by KcalbVessalius** [Monika-After-Story/MonikaModDev#5053]
I know now that Monika can do something for you in you birthday, but my birthday is on the same day of the christmas and on the christmas already have a "event" so im afraid that some bug occur because will have two "events" on the same day (Christmas and my birthday)

**Comment by multimokia** [comment]
We test for these things specifically when it comes to event updates. You need not worry.

**Comment by KcalbVessalius** [comment]
thanks,i feel relieved now
