### ISSUE TITLE
Suggestion: Love and Christmas Songs.

### ISSUE THREAD

**Issue by RobsonK2004** [Monika-After-Story/MonikaModDev#5057]
I'm currently not sure if this request has been made, if it has then I apologise then mark as duplicate and enjoy your day.

If not then I thought, why not add some more love songs to MAS in Moni's music section. Maybe due to the time of the year, some ChristMASsy songs could be added (sorry for my horrendous pun :D ).

Just a few personal suggestions:
When I Fall In Love - Nat King Cole,
Dream A Little Dream Of Me - Ozzie Nelson,
Fly Me To The Moon - Frank Sinatra,
Yesterday - The Beatles,
Baby It's Cold Outside - Dean Martin,
Have Yourself A Merry Little Christmas and 
I'll Be Home For Christmas - Frank Sinatra.

Maybe just a few lines, a chorus or a verse - maybe both. All is up to you. Thanks for reading my suggestion, Happy Holidays all and enjoy your day :)

**Comment by PollenTheCat** [comment]
Those are wonderful song ideas! I hope they get added :)

**Comment by TriniTDM** [comment]
Maybe this song? ;) https://youtu.be/dQw4w9WgXcQ

**Comment by MetalBrother** [comment]
Also Ozzy Osbourne - I Just Want You.

**Comment by TriniTDM** [comment]
Okay, joking aside, we should add All I Want For Christmas Is You.

**Comment by PollenTheCat** [comment]
All I want for Christmas is you is already in MAS

**Comment by PollenTheCat** [comment]
![image](https://user-images.githubusercontent.com/53543937/70486924-2c233c00-1ab9-11ea-9b06-b36f4d690ed5.png)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
