### ISSUE TITLE
[Suggestion] Sunset Change | Adding Calendar Events

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5058]
I have two suggestions for MAS that I think would be cool!

Instead of quickly changing from a bright sky to a dark night, there could also be a sunset in between. It doesn't have to be anything quite to detailed. It could be bluish-purpleish fading to a sunset orange, and at the top, there could be a few faint stars sprinkled about. That's just an idea of how the sunset could be, feel free to do something different.

Being able to add your own calendar events to Monika's calendar would be nice. By that I mean being able to click on one of the dates and being able to type the event name. Monika could bring up that it's the day of that event upon opening the game. It doesn't need to do anything more than that if you don't want it to. Though, if you don't mind there being more, maybe Monika could react to certain keywords in the event's name, or when you create the event, Monika could ask if it's good or bad and react accordingly. As I said in the sunset suggestion, feel free to change anything to work for MAS.

Those are my suggestions! Have a wonderful day!

**Comment by MetalBrother** [comment]
Yeah, I like that idea. Always thought that this is strange, how day change to night in one second. I think your calendar idea was suggested before.

**Comment by lunulae** [comment]
It's something I'd like to see done, but it would require making a third set of each weather variant, as well as a new light filter for clothes and spritepacks. Now that we have a lot of spritepacks already out those would require editing as well, so it'd probably be a longer-term project.

A middle ground could be finding a way to make the fade from day to night a longer transition, though it wouldn't exactly have the same effect as a sunset it might look more natural.

**Comment by ThePotatoGuy** [comment]
#2753 - previous mention of sunsets/transition phases. Not possible unless we're all fine with Monika lighting that doesn't match the background.

#1771 adding events to calendar, something we want to do but is currently pending

[closing as duplicate]
