### ISSUE TITLE
[Suggestion] Your Reality bgm pronouns

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5059]
So, I've recently gotten into a habit of, when singing along with Your Reality (as I do so much), changing the He/Him pronouns sang in Your Reality to She/Her, and I thought, "Wouldn't it be nice if in MAS, the pronouns in Your Reality would change to the player's pronouns." And so here we are! For example: If Monika knows the player as female, instead of Your Reality singing "Just move your hand; write your way into his heart!" it'd sing "Just move your hand; write your way into _her_ heart!" Vice versa, for neither, it'd sing "...your way into their heart!" I know it's a small change and might be hard, and I completely understand if you decide not to. It was just an idea. Anyways, have a wonderful day!

**Comment by TriniTDM** [comment]
You know, that would probably be a pain to edit.

**Comment by multimokia** [comment]
Editing the vocals of the song is borderline impossible. We don't have the clips of Jillian singing the right words to do this, plus it won't sound remotely good if we just pasted them over in the song even if we did have them.

We can do this for piano, but not the actual song. That much is impossible.

**Comment by PollenTheCat** [comment]
I assumed it would be impossible, but I thought to bring it up just in case it was possible. I'll close this, now.
