### ISSUE TITLE
List of expressions

### ISSUE THREAD

**Issue by KarmaCreations** [Monika-After-Story/MonikaModDev#5060]
I've been looking to add some variety into the expressions used in the piano songs I make, but I only know the ones used in Your Reality. Does anyone know where I could find a list of the codes for the different expressions (for example, happy w/ eyes closed and mouth open: 1hub; sad smile, eyes open: 1eka; etc.)?

**Comment by multimokia** [comment]
There's too many to list. Use the expression previewer.

Codes in red don't exist, codes in pink do.

**Comment by ThePotatoGuy** [comment]
[closing as implemented] via expression previewer
