### ISSUE TITLE
Gift Idea: Plushika

### ISSUE THREAD

**Issue by AngeryTwitch** [Monika-After-Story/MonikaModDev#5061]
Maybe add Plushika as a one-time gift, a high-level gift with high aff. reward, idk what the specifics would be but a Plushika on her desk would be adorable imo

**Comment by Rai99** [comment]
Plushie of Monika/Chibika: #2931, #4162 

As mentioned in #3779, it might be awkward to have a plushie of yourself, but if someone were to make art for it, it would probably be a welcome spritepack at the very least.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
