### ISSUE TITLE
Unable to run MAS outside Steam

### ISSUE THREAD

**Issue by KarmaCreations** [Monika-After-Story/MonikaModDev#5063]
Before I updated my computer to macOS Catilina (10.15.1), I was able to run MAS outside Steam just fine by simply dragging the folder onto my desktop. However, ever since the new update, if I remove the folder from the Steam files then attempt to open the game, the app bounces once then does nothing. It's a pain in the neck to have to update the game by hand, so I'd really like to know what's causing this and if/how I can fix it. Thanks!

**Comment by multimokia** [comment]
You'll have to downgrade your OS.

Mac OS Catilina dropped 32 bit support, meaning no 32 bit apps will run at all. This includes base DDLC too.

There is nothing we can do about it as RenPy is 32 bit.

**Comment by ThePotatoGuy** [comment]
this cannot be fixed by us.

[closing as wont fix]
