### ISSUE TITLE
[Suggestion] - Quick access to the history tab

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#5065]
Like many other people, I discovered Visual Novels with DDLC. Since then, I've played a lot more of them and I noticed that there's one feature that is common to most of them but is missing in MAS.
The fact that when you scroll up, it gives you direct access to the history tab. And with that, also comes the possibility to quickly close the history tab by scrolling down one more time when you're already at the bottom.

Since the scrolling is almost never used and that it's a common feature in VNs, it thought it would be a good addition to make. It would also give a quick way to go to the menu without having to press escape or click on "Talk" and then clicking on "Settings" or "History", instead doing it with the mouse.

**Comment by ThePotatoGuy** [comment]
potentially qol, but would require active disabling and enabling when viewing a screen with scrolling (selectors/menus/etc). Probably more risk than gain.

[closing until we look into it]
