### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by WWCHCN** [Monika-After-Story/MonikaModDev#5068]
I know that I asked previously about the gifting problem, and it's now fixed. But I recently took out all the files to play another mod...

Afterwards when i put them back in again, I am unable to open the game. It always says that a file has a missing line but I don't know.

I even tried reinstalling the MAS files and replacing them, but it again, it doesn't work.

Does anyone know how to fix this problem? Thanks

**Comment by multimokia** [comment]
Send your traceback please

**Comment by WWCHCN** [comment]
<img width="1680" alt="Screenshot 2019-12-08 at 00 43 00" src="https://user-images.githubusercontent.com/58337747/70377820-e4cf6b00-1953-11ea-9ef9-8fcabf6395dc.png">
![Uploading Screenshot 2019-12-08 at 00.44.14.png…]()

**Comment by WWCHCN** [comment]
<img width="1680" alt="Screenshot 2019-12-08 at 00 44 14" src="https://user-images.githubusercontent.com/58337747/70377827-f153c380-1953-11ea-8bcf-e681760af670.png">

**Comment by multimokia** [comment]
Reinstall mas. You're missing some python packages

**Comment by WWCHCN** [comment]
I tried, still gives me the same error, am I doing something wrong?

**Comment by multimokia** [comment]
Are you copying the python packages folder too?

If so, is there a `singleton.py` file in there?

If not, grab a new copy of the mod zip and install that. Your zip is missing it for some reason

**Comment by WWCHCN** [comment]
singleton.py is there, on both new and unworking one

**Comment by WWCHCN** [comment]
Is there something wrong?

**Comment by thezotikrus** [comment]
But `import singleton` is at line 9?

**Comment by WWCHCN** [comment]
How do I check that?

**Comment by thezotikrus** [comment]
Yeah, you have `definitions.rpyc` from vanilla DDLC. Reinstall the mod and agree when it will ask to overwrite.

**Comment by WWCHCN** [comment]
Never mind, It's suddenly working now. Thank you for all the help though

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
