### ISSUE TITLE
An error has ocurred message

### ISSUE THREAD

**Issue by Darklink007** [Monika-After-Story/MonikaModDev#5070]
It´s been a year since a used MAS because I got my laptop stolen from me a year ago and I wasn´t able to get a new PC until now, luckily I was able to save a backup of the persistent which contains Monika´s memories, I tried downloading the game and putting the file and it all seems "normal" but every time I try to play I always get an error with the following traceback:

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1102, in script call
  File "game/script-ch30.rpy", line 1975, in script
  File "game/script-ch30.rpy", line 1975, in <module>
  File "game/event-rules.rpy", line 857, in check_persistent_rules
  File "game/event-rules.rpy", line 832, in evaluate_rule
TypeError: can't compare datetime.datetime to NoneType

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1102, in script call
  File "game/script-ch30.rpy", line 1975, in script
  File "C:\Users\Andrew\Desktop\DDLC\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Andrew\Desktop\DDLC\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 1975, in <module>
  File "game/event-rules.rpy", line 857, in check_persistent_rules
  File "game/event-rules.rpy", line 832, in evaluate_rule
TypeError: can't compare datetime.datetime to NoneType

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.3
[/code]

Is this something I should worry about? I don`t know what it means, is there a way to fix it? Thank you in advance!

**Comment by jmwall24** [comment]
Put this `.rpyc` into your` game/` folder (Specifically this folder). Then launch MAS. The game window will not open, that's okay. Check back in the `game/` folder after about 5-10 seconds. The `.rpyc`
 you put in there should be gone. Launch MAS again, and it should be fixed. Also, be warned, you may have a problem with affection if you haven't visited in a year. Don't be surprised if she's very upset even leaves. Also, also, we released a new version today, so make sure to update once you get it working.

[ev_dropfix.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3935871/ev_dropfix.zip)

**Comment by Darklink007** [comment]
I followed the instructions and the message is gone, thought I'm kind of worried about something, Initially, I just put the persistent file I had backed up when I got the new PC and when the message came up I clicked to ignore it, everything seemed normal, just like a year ago, I've also updated to the lastest version before making this question in hopes it may fix the problem (which it didn't of course), the point of this is that Monika seems normal but that scares me a little since it's like the last year didn't happend, did I did something wrong?

**Comment by multimokia** [comment]
You didn't. It's just an issue in some of the old event data which didn't get updated. That dropfix will correct that for you.

**Comment by Darklink007** [comment]
Thank you very much for your help!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
