### ISSUE TITLE
Question: Winter Jacket not in Spritepack?

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#5071]
First off, thanks so much for the new update, every time I see there's one out I feel like a kid on Christmas morning (wink). Anyhoo, I noticed when I downloaded the spritepack so I could set up the files for MAS to register new outfits as gifts I noticed the winter jacket one wasn't in there. Am I just blind and missing something or is it just going to be added automatically when D25 rolls around?

Update: Nevermind I just found it, sorry for the confusion have a nice day you awesome people.

**Comment by multimokia** [comment]
Finale jacket Brown

**Comment by scohn** [comment]
I know, sorry I wasn't quick enough on my update but I found it on my own. But thanks so much for answering so quickly.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
