### ISSUE TITLE
[Bug?/Troubleshooting] Outfits not showing up in the appearance menu after spritepack installation.

### ISSUE THREAD

**Issue by AVRGForum** [Monika-After-Story/MonikaModDev#5072]
I've installed the latest 0.10.4 spritepack, however shortly after I had gifted everything and gone through the dialogues, my computer suddenly restarted. Monika doesn't react to the gifts being resent, giving a generic "I already have this!" response, but none of the outfits/bows/chokers are showing up in the appearance menus... 
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3935815/spj.txt)
Any help or insight would be appreciated. If I need to send other logs, please let me know.

**Comment by jmwall24** [comment]
I would suggest loading a backup persistent from before you gave the gifts, and then give them again. Your computer restarting after giving the gifts made have messed it up. Check [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for how to do that.

**Comment by AVRGForum** [comment]
That did seem to work, honestly should've tried it... I feel silly now. Thank you for entertaining my obvious question lmao
