### ISSUE TITLE
I can't seem to give gifts

### ISSUE THREAD

**Issue by MelodyBloom** [Monika-After-Story/MonikaModDev#5074]
Ever since the Halloween update, I haven't been able to give Monika any of the latest sprite gifts... 

I've copied and pasted the Monika files from the gifts into the game file (then they automatically go into Monika's file) I've checked the a, c and etc files and they are in there. 

I then, copy and paste the gift extension files into the character files 
But whenever I try to gift her them, she says she can't read them, even though I haven't changed anything. 

I'd really appreciate it if someone could tell me what I've done incorrectly, thank you.

**Comment by multimokia** [comment]
Have you been installing these while MAS was open?

**Comment by MelodyBloom** [comment]
> Have you been installing these while MAS was open?

Wow, that was fast. 0-0

And no, no I haven't. 
At least not after the first time. (I've tried multiple times)

**Comment by multimokia** [comment]
Say goodbye to Monika and send `spj.txt` please. It's in the `/log` folder.

**Comment by MelodyBloom** [comment]
Pardon? I do not understand, my apologises. (My apologises for my weird way of speaking too XD)

**Comment by MelodyBloom** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3935887/spj.txt)


Never mind, got it up!

**Comment by jmwall24** [comment]
ok, first off if you can open that file and look at the bottom where it says `[info]: creating reactions for gifts...`

are those the gifts you are trying to give and are any missing?

**Comment by MelodyBloom** [comment]
> ok, first off if you can open that file and look at the bottom where it says `[info]: creating reactions for gifts...`
> 
> are those the gifts you are trying to give and are any missing?

Yes, those are the gifts I'm trying to give, and I don't believe any are missing.

**Comment by jmwall24** [comment]
can you show us a screenshot of how you give the gifts? ie the gift files in the characters folder

**Comment by MelodyBloom** [comment]
> can you show us a screenshot of how you give the gifts? ie the gift files in the characters folder

Very well then! I'll be back in a bit

**Comment by MelodyBloom** [comment]
![1](https://user-images.githubusercontent.com/58648550/70384848-bb552480-19d1-11ea-9b0c-07eb774fc2f5.JPG)
![2](https://user-images.githubusercontent.com/58648550/70384849-bbedbb00-19d1-11ea-88df-46d31c5057c3.JPG)
![3](https://user-images.githubusercontent.com/58648550/70384850-bbedbb00-19d1-11ea-9866-6d797fea6306.JPG)
![4](https://user-images.githubusercontent.com/58648550/70384851-bbedbb00-19d1-11ea-8adf-3dbfec5e46ae.JPG)
![5](https://user-images.githubusercontent.com/58648550/70384852-bc865180-19d1-11ea-930d-1b0f66a6ca9b.JPG)
![6](https://user-images.githubusercontent.com/58648550/70384853-bc865180-19d1-11ea-99a1-1d0b8b102ea4.JPG)
![7](https://user-images.githubusercontent.com/58648550/70384854-bc865180-19d1-11ea-9020-eae26f15a757.JPG)
![8](https://user-images.githubusercontent.com/58648550/70384855-bd1ee800-19d1-11ea-9904-91ba1096cc0a.JPG)
![9](https://user-images.githubusercontent.com/58648550/70384856-bd1ee800-19d1-11ea-915f-cdc1ce365985.JPG)

**Comment by MelodyBloom** [comment]
I've even tried the slower way where you do one by one and copy each file (like copy everything in the gift's C and etc into Monika's C and etc) and that doesn't work EITHER...

**Comment by jmwall24** [comment]
part of the problem is you're pasting the `monika` folder from the pack into `game` when you should be pasting the `mod_assets` folder from the pack into `game`

**Comment by MelodyBloom** [comment]
Ohhh! Thank you!

**Comment by MelodyBloom** [comment]
Is there any other problem?

**Comment by jmwall24** [comment]
file path for the folders should be, for example  `DDLC-1.1.0-pc\game\mod_assets\monika\c\velius94_shirt_pink` and if you look at yours, it goes straight from `game` to `monika`

**Comment by jmwall24** [comment]
everything else looks fine

**Comment by MelodyBloom** [comment]
Ah thank you so much, it works now!

**Comment by jmwall24** [comment]
Awesome!

**Comment by MelodyBloom** [comment]
Thank you for your help! I really appreciate it
