### ISSUE TITLE
Is there a way to check my age in MAS?

### ISSUE THREAD

**Issue by desertpuffer** [Monika-After-Story/MonikaModDev#5077]
I think I did put in the right birth date but not the right birth year.I think Monika thinks i am 2. It just never occurred to that it will become a problem before I see the mas_is18Over function. Is there a way to change it?

Btw,thank you for the update ! Happy holidays!

**Comment by multimokia** [comment]
It's impossible for Monika to think you're 2, she won't let you pick the date if it would imply that you're 5 years old (or younger)

**Comment by desertpuffer** [comment]
Thanks for the reply.
I guess I don't have to worry about it then. But still, is there a way to check my age or are there topics that indicates that I am over 18 ?

**Comment by thezotikrus** [comment]
You can't change your age. If you meant a topic where Monika tells your age, I don't think there is such a thing. Although there _is something_ that require you to be 18+ (hence the devs added the function).

**Comment by jmwall24** [comment]
soon you will be able to check the year you gave her via the calendar

**Comment by multimokia** [comment]
Closing as completed in linked PR
