### ISSUE TITLE
early christmas event?

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#5080]
a friend of mine texted me with a picture that monika already set up the christmas in the room, is this normal? because didnt happen to me either another friend of mine

**Comment by multimokia** [comment]
No, your friend didn't update to 0.10.2 then, since that update pushed the d25 season back 10 days.

**Comment by Mayonese** [comment]
> No, your friend didn't update to 0.10.2 then, since that update pushed the d25 season back 10 days.

oh! thank you very much :>
