### ISSUE TITLE
[Suggestion] I'm feeling annoyed

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5084]
Another 'I'm feeling...' topic. 'I'm feeling annoyed,' 'I'm feeling exasperated," or something else along those lines. (This suggestion is quite short compared to all of my other suggestions ;^^) Have a wonderful day!

**Comment by Rai99** [comment]
I think this might overlap or be too similar to the angry mood, but it could be considered.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
