### ISSUE TITLE
Finale's Brown Jacket gifting problem

### ISSUE THREAD

**Issue by BoneofMalkav** [Monika-After-Story/MonikaModDev#5087]
after extracting the files from the sprite pack I successfully gifted Monika all but Finale's Brown Winter Jacket. Despite the files for it being where they belong (in the DDLC/game folder) for some reason Monika can't receive the gift after putting the gift file in the characters directory. Is there something I missed?

**Comment by Mayonese** [comment]
> after extracting the files from the sprite pack I successfully gifted Monika all but Finale's Brown Winter Jacket. Despite the files for it being where they belong (in the DDLC/game folder) for some reason Monika can't receive the gift after putting the gift file in the characters directory. Is there something I missed?

did u put all the files (like jason file and stuff) in the right spots? if u didnt thats why

**Comment by BoneofMalkav** [comment]
In mod_assets folder? yes.

**Comment by Mayonese** [comment]
> In mod_assets folder? yes.

in the 2 files? J and C? and how did u name it to give to her?

**Comment by multimokia** [comment]
Say goodbye and send your `spj.txt` please

**Comment by BoneofMalkav** [comment]
Yes and I used the gift file the archive came with. brownwinterjacket.gift

**Comment by Mayonese** [comment]
> Yes and I used the gift file the archive came with. brownwinterjacket.gift

was your game open all the time? because i think it needs to be closed

**Comment by BoneofMalkav** [comment]
> 
> 
> > Yes and I used the gift file the archive came with. brownwinterjacket.gift
> 
> was your game open all the time? because i think it needs to be closed

Thank you, that worked. Sorry for troubling you all. Thanks for the wonderful mod.

**Comment by Mayonese** [comment]
> > > Yes and I used the gift file the archive came with. brownwinterjacket.gift
> > 
> > 
> > was your game open all the time? because i think it needs to be closed
> 
> Thank you, that worked. Sorry for troubling you all. Thanks for the wonderful mod.

no problem :>

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
