### ISSUE TITLE
Clothes Issue

### ISSUE THREAD

**Issue by GT1337** [Monika-After-Story/MonikaModDev#5088]
So basically i gave Monika 3 gifts ( sweater, skirt and the jacket all from new spritepack) and everything was fine until my game wasn't responding and i had to close it ( i left game running for about hour and i went back it happened) And after that Monika can't wear clothes that i gave her, they don't show up in the clothes menu. So all i'm asking that is there's way to fix it or something. 
btw my affection is 610 

Thanks.

**Comment by thezotikrus** [comment]
Can you put your persistent in a `zip` archive and upload it here?

**Comment by GT1337** [comment]
> Can you put your persistent in a `zip` archive and upload it here?

Can you explain how to do that?

**Comment by thezotikrus** [comment]
[Here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)
No need in the whole folder, just `persistent`.

**Comment by Mayonese** [comment]
> So basically i gave Monika 3 gifts ( sweater, skirt and the jacket all from new spritepack) and everything was fine until my game wasn't responding and i had to close it ( i left game running for about hour and i went back it happened) And after that Monika can't wear clothes that i gave her, they don't show up in the clothes menu. So all i'm asking that is there's way to fix it or something.
> btw my affection is 610
> 
> Thanks.

did u close the game? many people do this mistake that when u put the files from the clothes for monika, they dont close the game and just give it to her,but you need to close it

**Comment by GT1337** [comment]
> [Here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)
> No need in the whole folder, just `persistent`.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3945709/persistent.zip)
here 

> > So basically i gave Monika 3 gifts ( sweater, skirt and the jacket all from new spritepack) and everything was fine until my game wasn't responding and i had to close it ( i left game running for about hour and i went back it happened) And after that Monika can't wear clothes that i gave her, they don't show up in the clothes menu. So all i'm asking that is there's way to fix it or something.
> > btw my affection is 610
> > Thanks.
> 
> did u close the game? many people do this mistake that when u put the files from the clothes for monika, they dont close the game and just give it to her,but you need to close it

yes i closed the game and when i opened it again clothes were gone but monika were still wearing the skirt until i changed it to the old clothing. And from that moment i can't choose the new ones.

**Comment by ThePotatoGuy** [comment]
Try regifting them

**Comment by GT1337** [comment]
> Try regifting them

Thanks, that actually worked, i tried doing that with only one gift i didn't work.
But when i gave her all 3 it worked for some reason. Thank you again!
