### ISSUE TITLE
Is there a legal way to change playername?

### ISSUE THREAD

**Issue by YarikTH** [Monika-After-Story/MonikaModDev#5089]
I started from a localized version of MAS but I gave up using it because it is outdated.
I used letters that are not present in the original English fonts. 
![image](https://user-images.githubusercontent.com/21075945/70472088-918a2380-1adf-11ea-973d-ed1bb571a5f3.png)
So, now I literally have no name(
I want to change my name using English letters, but I don't see any menus for it. I see "change gender" dialog though.
I'm more or less advanced python user, so I can hack the code by myself, but I want to know if it is some legal way to do so that I don't know.

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/70472800-beb5e200-1a9d-11ea-86b8-adedaaf8f325.png)
`Hey [m_name]... > You... > Can you change my name?`

**Comment by YarikTH** [comment]
![image](https://user-images.githubusercontent.com/21075945/70472991-35280380-1ae1-11ea-87fe-0a864852bf0b.png)
Did I miss some conditions?

**Comment by multimokia** [comment]
It's possible your translated version of MAS did not unlock it correctly. If you could send your persistent over, I can fix that for you (you'll have to put it in a zip for GitHub to accept the upload)

**Comment by YarikTH** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3941857/persistent.zip)
Done. Thank you in advance.

**Comment by multimokia** [comment]
Try this one
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3941987/persistent.zip)

**Comment by YarikTH** [comment]
Working. The menu entry is unlocked
