### ISSUE TITLE
Christmas on December 11th?

### ISSUE THREAD

**Issue by GehorLef** [Monika-After-Story/MonikaModDev#5092]
I don't think this was supposed to happen, but for some reason D25 event was triggered, even though it's only December 11th.
![christmas](https://user-images.githubusercontent.com/58762756/70595077-60027c80-1bf3-11ea-8d97-38efbe4a00ae.png)

**Comment by RavenPLAYER** [comment]
Remember Christmas decorations are put before it. I guess it's normal (It happened to me too).

**Comment by lunulae** [comment]
Yup! Monika puts out the decorations a few weeks before the actual day, this is normal. It used to be even earlier, right at the start of the month.
I wish she'd do the same before Halloween, it's a lovely way to get in the holiday spirit.

**Comment by GehorLef** [comment]
She just said 'Happy holidays', so I assumed that she thinks that it's Christmas today. That's why I brought it up here. Anyways, thanks for the explanation!

**Comment by Booplicate** [comment]
Yeah, you're good. The decorations should appear on 11th.
