### ISSUE TITLE
Question about D25 gifts (possible spoilers?)

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#5093]
If I want Monika to keep a gift under the tree til Christmas morning, is it okay to gift it anytime during the d25 season, or should I save it until Christmas Eve itself?
And is it only certain gifts, or any given within the right time period? I was hoping to do the spritepacks from this update, but no worries if that isn't an option.

**Comment by Booplicate** [comment]
I think you can give her gifts between 20th and 24th.
Spritepacks will work for sure.

**Comment by yurireeka** [comment]
So, how do you do that? Will giving her gifts normally make her put it under the tree?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
