### ISSUE TITLE
Typo found during Monika's Christmas event

### ISSUE THREAD

**Issue by Rin3105** [Monika-After-Story/MonikaModDev#5094]
Should be "excitement" instead of "excitemet"
![screenshot0001](https://user-images.githubusercontent.com/52498640/70602497-29def000-1c27-11ea-855b-119823c85acf.png)

**Comment by Booplicate** [comment]
I blame the rat.
But next time post typos in the [appropriate issue for typos](https://github.com/Monika-After-Story/MonikaModDev/issues/5069) (it's usually pinned).

**Comment by Rin3105** [comment]
Alright, I will do that next time.

**Comment by multimokia** [comment]
Closing as fixed in #5104
