### ISSUE TITLE
Monika doesn't count the number of holidays season spent together accurately

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#5097]
![Screenshot_1](https://user-images.githubusercontent.com/45933038/70652516-0336ae80-1c53-11ea-883c-f715ffc1462d.png)

The line above suggests that this is our second Christmas with her, but I got this dialogue even though in my case, this is actually the third time.  
If counting the number of Holidays spent together is possible, it might be interesting to use a counter to alter this line slightly as to be more accurate ("two whole years have gone by", "three whole years", and so on).

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
