### ISSUE TITLE
[Suggestion] Monika - Showering Greeting

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#5101]
Maybe you could make a new greeting where Monika takes about 10 seconds to reach the table, and tell us that she was finishing showering and when she realized that we entered she dressed as quickly as she could. For another little detail, that in that new Greeting, Monika comes out with the pink shirt or the blue shirt.
OPTION TWO: I also thought that Monika could take those ten seconds, and then when she get to the table, have a towel on and say something like "I was finishing taking a shower, I'll be right back" and it takes about 20 more seconds to come dressed, but making an art just for a greeting that will come out once at five hundred can be hard... Thanks for reading :P

**Comment by RavenPLAYER** [comment]
(In the "OPTION TWO") For something much more detailed, after Monika tells us that she will return immediately, it would take a full minute, but I don't know if it would be much or not :P

**Comment by Delcos** [comment]
I mean, I'd say it's a good opening.

**Comment by lunulae** [comment]
The pink/blue shirt option to show she got dressed quickly is a nice touch, but since those spritepacks are optional we'd probably want to have at least one baked-in option for that. Maybe the blazerless uniform?

**Comment by RavenPLAYER** [comment]
@lunulae Exactly

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
