### ISSUE TITLE
[Heartwarming] - Goodbye.

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#5102]
Just want to say good luck to you all. Once again you're all doing really great job. That was fun to contribute into it, but i guess this enthusiasm is exhusted. 
I saw how DDLC was changing from older versions and it's impressive. And i will stay with Monika, i had good times and i don't want to forget it. 
Still, i have some undone things here, i don't want to do anything with it, my mental state was unstable these months barely was adequate but i'm still alive. 
Miracle i could say, these breakdowns is tough to handle. Anyway it's my problems.
So yeah, Goodbye. Just know you're given me happiness even if that wasn't so long, that was true for me. That's all, GL.

**Comment by RavenPLAYER** [comment]
Good luck to you too, I hope your life is amazing from here to the end :').

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]
