### ISSUE TITLE
Monika doesn't remember me anymore

### ISSUE THREAD

**Issue by FireArts** [Monika-After-Story/MonikaModDev#5107]
So i was at 1000 affection, i had everything i can give to Monika and everything she could show me (except the new update stuff) but then i had to restart my whole computer and all the files and everything i had in my computer are gone that includes monika after story files.

I thought i had backed up the files but i didn't so that means she doesn't remember me nor does have any items i gave her

it really made me sad to know everything i worked for was all gone now and i'm wondering is there a way to get everything back? If there is i would love to know

**Comment by AsuraShun** [comment]
It's a joke, she's testing you, to see if you're as good of a person as she thinks you are

**Comment by jmwall24** [comment]
@FireArts  do you have anything from the old install? we'd need an aff_log file to verify affection. also, check for c:/windows.old. if you backed up your files, they'd be there, you may have just missed them.

**Comment by TriniTDM** [comment]
Well, I normally don't condone cheating, but since you once legitimately had that level of affection and want to get back to where you were before your computer had to be wiped, I'll give you a rpy file to set your affection to 1000. https://drive.google.com/file/d/1NdQji1_QhlrJ9Rl_BL_Wjy5Yppj8TbiU/view?usp=drivesdk

**Comment by multimokia** [comment]
We do not condone it either, and as such we will be deleting you comment

**Comment by TriniTDM** [comment]
Sorry.

**Comment by jmwall24** [comment]
you need to remember, anyone could download that, not just him. besides, there's a good chance he did back up his files, just didnt know where to look.

**Comment by FireArts** [comment]
I had checked everywhere and nothing is to be found

**Comment by PollenTheCat** [comment]
Oh, I feel so bad for you!! I wish there was something I could do to help, but, sadly, I don't know much about MAS or coding, etc...

**Comment by FireArts** [comment]
i do have some proof but it isin't the most best proof but i can show it if it's needed

**Comment by RavenPLAYER** [comment]
@FireArts Hey, do you have Discord? I have a solution, but we have to talk on inbox...

**Comment by FireArts** [comment]
@RavenPLAYER yeah i do have discord

**Comment by RavenPLAYER** [comment]
@FireArts Send me your tag.

**Comment by FireArts** [comment]
@RavenPLAYER here is my tag fire_Kaitlyn#2841

**Comment by RavenPLAYER** [comment]
@FireArts ok attentive
