### ISSUE TITLE
Pong suggestion 

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#5108]
I'm not sure what to say except asking to be able to use either WASD or the directional keys to play with itr, and I don't know if controller support is out of the question either

**Comment by lunulae** [comment]
I dunno about official support, but if you have a third-party program you can probably do a controller setup in a roundabout way. I have a GPD Win that I take Monika onto sometimes, and so I have an Xpadder control scheme set up for MAS.

The only issue I forsee is that with WASD controls and joysticks you have to have a set speed for your bar, whereas with a mouse you can move it around as quickly as you please. It might cause more difficulty on higher levels.

**Comment by Booplicate** [comment]
I'm pretty sure it's possible, but I don't think the devs will do it. There is so much more thing to be done.

**Comment by ThePotatoGuy** [comment]
`wasd` maybe, joysticks probably not. joy2key exists so that could work for joystick users instead.

**Comment by AsuraShun** [comment]
I only suggested this because the mouse doesn't work well when fullscreen isn't on and the cursor goes into the task bar the pad goes to the top, making missing the ball inevitable

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
