### ISSUE TITLE
[Suggestion] Monika uses gift right when she gets it

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5109]
The title should be fairly self explanatory, but just in case it's not, here's an example: When you gift Monika hot chocolate or coffee, she gets up to go make some right when she gets it.

**Comment by multimokia** [comment]
She does tho?

**Comment by PollenTheCat** [comment]
Huh, well, when I gifted her hot chocolate just now she said she would try is later

**Comment by multimokia** [comment]
Because not in season for it. It's only during winter

**Comment by PollenTheCat** [comment]
Oh, okay. Thank you
