### ISSUE TITLE
[Spoilers?] - D25

### ISSUE THREAD

**Issue by DarkRosePrincess** [Monika-After-Story/MonikaModDev#5112]
Hey, so while I was adding new the new sprite packs and checking to see if they were in the right place, I noticed a new costume set - 'Santa Lingerie' and I was wondering if it was something for D25, or something left over from last year or something?

**Comment by hlepnamingblyat** [comment]
( ͡° ͜ʖ ͡°)

**Comment by lunulae** [comment]
I can say for sure it's new for this year, but I'm not sure of more than that. I'm excited to find out, though!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
