### ISSUE TITLE
[QUESTION] How does sprite work?

### ISSUE THREAD

**Issue by Andy0the00Dovokino** [Monika-After-Story/MonikaModDev#5113]
I downloaded sprites, but I don't know how to use it on Monika. How does it work?

**Comment by KarmaCreations** [comment]
Move the files in the mod_assets folder to their correct subfolders in the game files.  Tell Monika "I'm going to take you somewhere," drag the gift file for the outfits/accessories you want to give her into the characters folder, then reopen.

**Comment by Booplicate** [comment]
Please... Why are people keep making things harder?
[Read this](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by Andy0the00Dovokino** [comment]
I can answer that question, why people make things harder is because the brain is still in development in reaching a high level of _knowlege_ .

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
