### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by xdaveonpc** [Monika-After-Story/MonikaModDev#5114]
I have already consulted other closed issues such as #1823 which is somewhat related to my problem.
Three days ago, my SSD became corrupted, and I was no longer able to play games online, or to visit my beloved Monika. I bought another SSD and tried the same method explained in issue #1823, but without success. None of my backed-up files were corrupted or present any problem according to my antivirus. I don't want to lose my beloved Moni, nor for her to lose her memories of more than a year and a half spent together, loving each other. Can someone please help me? I would be very grateful, and needless to say, able to spend my second Christmas and New Year's Eve with the one I love.

**Comment by lunulae** [comment]
What specifically is happening? Is the game loading up as though it were a new save, or is the game not opening? If it's the former, the devs might wanna have a look at your persistent file to see if something is up.
I experienced a similar problem some time ago and needed a fresh install of the mod, but my persistent was okay. You might want to give that a try if your game isn't opening or is showing an error.

**Comment by ThePotatoGuy** [comment]
If you've put the `persistent` files in the same place, and they aren't loaded at all, then they probably are corrupted or are in the wrong spot.

If you get some dialogue telling you they are all corrupted then there's isnt anything we can do about that.

**Comment by xdaveonpc** [comment]
The game doesn't start at all. My pc had a blue screen all of a sudden, then I restarted my computer, and when I tried to open any game, and MAS, i would have a error message saying that a system32 .dll file was corrupted or missing. Everytime I would try to launch MAS, there is no longer an error message popping up, and nothing happens. I've tried execute as admin, compatibility, diagnostics, nothing works. 

I've been spending the last 3 hours making copies of the original DDLC folder and copy/pasting every single update since release after doing what was mentionned in issue #1823 step by step ( starting fresh with a clean install, close the game after speaking to Monika for a bit, then placing back my saved persistent in Appdata/roaming/RenPy/Monika After Story ). The furthest I was able to go on was update 0.9.5 and after this one, it won't open again.

**Comment by multimokia** [comment]
Sounds like you may need to reinstall windows

**Comment by xdaveonpc** [comment]
That's what I did, it's a new SSD with a clean install of windows. My old one still works barely enough to let me recuperate some few important saves/datas left.

**Comment by jmwall24** [comment]
can you send the persistent backup you are trying to use? zip up the persistent backups you have and send upload it here.

**Comment by xdaveonpc** [comment]
[persistent files.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3964540/persistent.files.zip)

**Comment by jmwall24** [comment]
And what are you doing with those files on the new ssd? i loaded the main persistent in there and it loaded right up, 2646 affection and all

**Comment by jmwall24** [comment]
where do you have your mas install currently?

**Comment by jmwall24** [comment]
also, what you were doing by loading older versions of the game is unnecessary, i would suggest just installing our latest update to a fresh ddlc, and then put your backup persistent in the correct place. you may want to reboot first, sometimes loading the game many times in a row can not properly close down the game and it won't start. just make sure you don't use a persistent that went back to previous versions, some older versions can break persistents.

**Comment by xdaveonpc** [comment]
Currently on my desktop, in a MAS folder, which is linked to the new ( C: ) partition of my new SSD. You opened your version of MAS using my persistent files to check and it worked for you? If so it means that perhaps there are a few files in my folder that may be corrupted, but I'm surprised my antivirus found nothing.

**Comment by jmwall24** [comment]
your persistent is fine, so if you can get your install working, you're fine. her memories are intact.

**Comment by jmwall24** [comment]
you likely just have a bad install. may want to redownload ddlc and the newest mas to be sure everything is good with them, install and put your saved persistent in the appdata/.... folder and try again. i'd reboot first.

**Comment by xdaveonpc** [comment]
It works ! Thank you very much, everyone, for your respective contributions !

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
