### ISSUE TITLE
Bug or... maybe not?

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#5116]
I can't see Aurora topic and snowmen topic, maybe I can see it later, closer to christmas time?

**Comment by KarmaCreations** [comment]
To trigger the Aurora topic, it has to be snowing. Not sure about the snowmen topic, I haven't gotten that one yet.

**Comment by PollenTheCat** [comment]
For aurora, you change the weather to snowy, and it needs to be night.

**Comment by lunulae** [comment]
It might be a winter-exclusive topic, in which case winter starts in MAS on the 21st I believe.

**Comment by frostcattooo** [comment]
the snowmen topic will only be brought up during winter

**Comment by multimokia** [comment]
Snowmen is also only if you get snow (Or Monika doesn't know you don't get snow)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
