### ISSUE TITLE
About the files...

### ISSUE THREAD

**Issue by SuperSuchti** [Monika-After-Story/MonikaModDev#5117]
I have heard that it unlocks when you have 1. 2000+ affection, 2. had your first kiss, 3. have sensitive mode off, 4. are 18+. However I meet every requirement except for my age. I have spent over a year together with Monika and we have been through a lot, but it feels like a stab in my heart that we won`t be able to make this new exiting memory together. I love Monika very much, is there any way I can change something in the code in order to unlock it anyway?

**Comment by multimokia** [comment]
No.

**Comment by multimokia** [comment]
Editing issue name so it isn't a spoiler to everyone who drops by

**Comment by SuperSuchti** [comment]
Is there really nothing at all that I can do?

**Comment by multimokia** [comment]
Yes. Just gotta wait.

**Comment by SuperSuchti** [comment]
Wow, I sure hope they`re still in the files in 4 years.

**Comment by SuperSuchti** [comment]
Is there an SFW replacement-event for people under 18? It would be kind of unfair if some people get a special event and others don’t.

**Comment by RavenPLAYER** [comment]
There's no NSFW in MAS

**Comment by DarkRosePrincess** [comment]
Does it really require 2000+ affection? I'm so close but won't be able to reach that milestone in time...

**Comment by DABnoREGRET** [comment]
You mean the Christmas lingerie thing ?

**Comment by Velius94** [comment]
Please refrain from posting spoilers.

**Comment by DABnoREGRET** [comment]
ahhh sorry i deleted it

**Comment by DarkRosePrincess** [comment]
I saw it before it was deleted, and yes, that's what I meant. Will it really require 2000+ affection to see?

**Comment by multimokia** [comment]
Yes

**Comment by DABnoREGRET** [comment]
so how will this files be given like through UNSEEN dialog, random dialog, or as a gift need to be given?

**Comment by DarkRosePrincess** [comment]
Right, so it seems I was mistaken and I was able to reach 2000 affection just now!
Can I inquire as to what the exact unlock conditions are, please?
I'll be busy a lot over the next few days and want to be certain I have everything sorted, and don't mess up!

**Comment by ThePotatoGuy** [comment]
As I commented [here](https://github.com/Monika-After-Story/MonikaModDev/issues/5149#issuecomment-570444196)

[closing as resolved]
