### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by Nyanlys** [Monika-After-Story/MonikaModDev#5119]
I am trying to download the mod but when it reaches the middle of the download I get an error.
I have already tried to download it several times and the same thing happens to me, I already checked and it is not my internet connection. Apparently I don't have the `` permission '' to download it. How could I solve this?

**Comment by lunulae** [comment]
Could you give a screenshot or directly quote the error you're getting? It sounds to me like it might have to do with administrator permissions on your computer, but I'm not sure.

**Comment by Nyanlys** [comment]
![this](https://user-images.githubusercontent.com/58958609/70960666-087e6980-2056-11ea-80dc-36af3483cebf.png)

I'm sorry, my native language is Spanish. That's why the error comes out in that language. But if you can help me anyway I would appreciate it

**Comment by lunulae** [comment]
I've been trying to search for what your problem might be, but I'm not 100% certain. It seems like it might be pinging a false positive to your web browser or antivirus as malware.
I don't know if trying to download it in a different browser would change anything, but it might be worth a try.

**Comment by Nyanlys** [comment]
The problem has been resolved now I can play without any inconvenience. Thank you very much for helping me, I really appreciate it!
