### ISSUE TITLE
[Suggestion] - Othello / Reversi Game

### ISSUE THREAD

**Issue by Hobiron** [Monika-After-Story/MonikaModDev#5122]
Good Day, 

I just wanted to suggest a mini game feature: "Othello / Reversi" as another mind-strategy mini game aside from Chess.

Kindly take my suggestion into consideration.

Thank you and God Bless
 - Hobiron

**Comment by Rai99** [comment]
Reversi: #778

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
