### ISSUE TITLE
[Suggestion] Monika getting better at programming

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#5124]
It could be shown Monica's improvement in programming, in the floating islands themselves, that as time went on Monika would add the things she would like to put on and she would finally show that house she's working on.

**Comment by Rai99** [comment]
Adding more to islands: #2984 

There was some discussion about the glitched area in #4396, and I'm sure there are plans to put something there at a later date.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
