### ISSUE TITLE
How do I give Monika gifts that she can only open on christmas?

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#5129]
Title basically says it all.

**Comment by multimokia** [comment]
Like you would do normally. They'll end up under the tree.

**Comment by ThatOneUsername343** [comment]
so i just put a .gift file in the character folder and it will appear under the tree?

**Comment by multimokia** [comment]
Yes

**Comment by ThatOneUsername343** [comment]
noice thanks

**Comment by ThatOneUsername343** [comment]
is there a list of all the gifts i can give her?

**Comment by multimokia** [comment]
Check the wiki tab of the repository. Under the spoilers section

**Comment by ThatOneUsername343** [comment]
okay, i gifted her some things, but she immediately started opening them

**Comment by multimokia** [comment]
What did you gift?

**Comment by ThatOneUsername343** [comment]
roses, yellow ribbon, christmas cookies, and chocolates

**Comment by multimokia** [comment]
edibles (coffee/hotchocolate, cookies, fudge, etc.) and roses won't be stored, since that makes no sense

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
