### ISSUE TITLE
Suggestion What if Monika could be hungry, and her stomach growled

### ISSUE THREAD

**Issue by Dashuki-Dev** [Monika-After-Story/MonikaModDev#5131]
What if Monika could be hungry, and her stomach growled
How it'll work, it'll work like this.
Randomly between breakfast time or lunchtime, or dinner time, her stomach can growl 2 times.
Then she can ask you to cook something, if you'd say sure, she'd eat the thing you'd make if you say no, she'd make food herself.
I hope I explained it well enough...

**Comment by lunulae** [comment]
I think there's something in the works to give Monika food, though I'm not sure if there's a hunger system to go with it. Once the consumables framework is finished, though, I'm sure more could be done with it.

**Comment by Rai99** [comment]
Eating with Monika: #1789, #1934, #2164, #3210, #3305, #3795, #4032, #4081, #4260 #4606, #4648, #4842, #5023. 

We would first need the consumables framework before we go adding hunger.

**Comment by ThePotatoGuy** [comment]
im not too sure about stomach growling, at least not audibly. dialogue where she brings up that shes hungry would be more in-line with the game.
[closing as duplicate]
