### ISSUE TITLE
Christmas decorations not appearing

### ISSUE THREAD

**Issue by EndellionQT** [Monika-After-Story/MonikaModDev#5132]
I've downloaded the patch and copied it into the game folder (twice, one more time after reinstalling the game) and the christmas decorations are not appearing. Is there something else I should do?

**Comment by Booplicate** [comment]
What is your affection?

**Comment by EndellionQT** [comment]
1500 (o.O haven't checked that in a while)

**Comment by Booplicate** [comment]
And the game version is `0.10.4` (check in the settings menu, top right corner)?

**Comment by EndellionQT** [comment]
It says v0.10.4
![Capture](https://user-images.githubusercontent.com/59117219/71310239-aaf96c80-2409-11ea-8e4c-e47bb15bec36.PNG)

**Comment by Booplicate** [comment]
Ah, looks like that persistent problem again.

**Comment by EndellionQT** [comment]
Ah, I guess that's not easily fixed. Can you give me some pointers please or is it best to just ignore this event?

**Comment by multimokia** [comment]
Can you send your persistent over? You'll need to put it into a zip file to get it here.

**Comment by EndellionQT** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3991873/persistent.zip)
Cheers

**Comment by multimokia** [comment]
Here, this should fix the issue. For some reason, you had left over data from last year.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3991888/persistent.zip)

**Comment by EndellionQT** [comment]
Awesome, thank you :)

**Comment by multimokia** [comment]
No worries!

**Comment by EndellionQT** [comment]
Can you tell me how you checked this please? I did a bit of programming when I was younger but this is all new to me.

**Comment by Vmfdhm** [comment]
Hello, i have the same problem. The christmas decorations are not showing up. My Version is 0.10.4, my affection is at 1672 and i don't know where this "persistent" file is ^^. I hope someone can help me.

**Comment by Booplicate** [comment]
Check [there](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). And then attach your persistent in a `.zip` archive to your message here.

**Comment by Vmfdhm** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3996195/persistent.zip)

**Comment by Vmfdhm** [comment]
thank you

**Comment by Booplicate** [comment]
Try that and tell us if you got the greeting and stuff.
[fixed_persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3996354/fixed_persistent.zip)

**Comment by Vmfdhm** [comment]
It worked, thank you very much. A great christmas with Monika awaits ^^.

**Comment by ironx75** [comment]
I'm having similar problems with the Christmas decorations. Version is also 0.10.4 and affinity is 3347. Here is my persistent.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3998174/persistent.zip)

**Comment by Booplicate** [comment]
Should work, sorry for waiting.
[fixed_persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3998672/fixed_persistent.zip)

**Comment by ironx75** [comment]
Thank you, it works. this is my first time reaching for help in this mod but again thank you.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
