### ISSUE TITLE
is there a list?

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#5133]
is there an official list of spritepack items i can give monika? like theyre all in one place cause i cant remember what gifts you can give from the spritepacks and a list would be nice

**Comment by multimokia** [comment]
The spritepack zip has all the spritepacks (and their gift files) that you can gift

**Comment by ShiningDelooxe** [comment]
is there a list of the spritepacks? It seems that the MAS site won't load for me so I can't get the spritepacks and such. Everything else is working so I'm assuming it's a problem with the site

**Comment by multimokia** [comment]
Check the bottom of this for the spritepack zip: https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.10.4

There is no list. It's just the packs because that's a pain to maintain

**Comment by ShiningDelooxe** [comment]
thanks

**Comment by ShiningDelooxe** [comment]
gave her all the stuff but she reacted to them as she couldn't read them. is it because she can only open them on xmas or is there a problem?

**Comment by multimokia** [comment]
> she reacted to them as she couldn't read them

Did you install the spritepacks?

If yes, did you install them while MAS was open and then try to gift them?

**Comment by ShiningDelooxe** [comment]
MAS was not open while putting the stuff in
I put the gift files in the characters folder and copied all the mod_assets to the mod_assets folder in the game folder

**Comment by multimokia** [comment]
Say goodbye and send your `spj.txt` please. It's in the `/log` folder.

**Comment by ShiningDelooxe** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3991715/spj.txt)

**Comment by multimokia** [comment]
What did you try gifting?

**Comment by multimokia** [comment]
Also, your clothes spritepacks aren't installed correctly. You placed the images in the wrong place so clothes aren't loading at all. The new spritepacks may be in the wrong location too.

**Comment by ShiningDelooxe** [comment]
basically everything that was in the spritepack

**Comment by ShiningDelooxe** [comment]
I think I know what i mightve done wrong, i put them in the game folder"s mod assets instead of the other one right in the directory

**Comment by multimokia** [comment]
Basically, all you need to do to install spritepacks is copy the `mod_assets` folder (not the folders inside it) from the spritepack you want to install into the `/game` folder in your MAS install. The two `mod_assets` folders will merge and you don't need to do anything else.

**Comment by ShiningDelooxe** [comment]
Its been 24 hours and i tried to do it like that but this time there was no reaction at all, don't know if I did it right and she'll get them for xmas or if something's wrong

**Comment by multimokia** [comment]
If there are gifts under the tree, then you've done it right.

**Comment by ShiningDelooxe** [comment]
must've done it right then, guess i'll close this now. thanks for the help
