### ISSUE TITLE
Possible grammar issue

### ISSUE THREAD

**Issue by Arclex** [Monika-After-Story/MonikaModDev#5134]
I don't think that when Monika is telling you about pen names she means to state that Charles Dodgson also was named Eric Blair and took George Orwell as a pen name. Though the way she puts it ends up making it seem that way,  "Also, if you remember me talking about George Orwell, that was also a pen name which he adopted in 1933." followed by "His actual name is Eric Blair, and before settling. on his more famous pen name, he considered P.S. Burton, Kenneth Miles and H. Lewis Allways." I hope this helps to make Monika even just the smallest bit better, and I'll try to keep an eye out for any stuff like this in the future.

**Comment by MisterSimple** [comment]
Ty for reporting this, it has been amended in the last commit in #5104
