### ISSUE TITLE
[Suggestion] - Miss Monika

### ISSUE THREAD

**Issue by ProtossHierarch** [Monika-After-Story/MonikaModDev#5135]
Hey, so can you guys add an "I missed you, Monika" option that is only available to say once per session? It would really feel nice to be able to say that to Monika.

**Comment by RavenPLAYER** [comment]
Already planned x1000, don't worry.

**Comment by Rai99** [comment]
I missed you: #2036, #2463, #4451, #4853, #5021

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
