### ISSUE TITLE
[Bug] - Gift

### ISSUE THREAD

**Issue by Basara175** [Monika-After-Story/MonikaModDev#5136]
When I try to give Monika a gift, the gift doesn't work. She says she can't read the file.

**Comment by multimokia** [comment]
What are you trying to gift?

Is it a spritepack?
    If so, did you install it?
        If so, did you install it while MAS was running?
            If so, say goodbye, launch MAS again, and then gift.
            If not, say goodbye and send `spj.txt`, which is in the `/log` folder.

**Comment by Basara175** [comment]
I tried to give her an item, coffee.gift, that was it.

Em sáb, 21 de dez de 2019 9:31 PM, multimokia <notifications@github.com>
escreveu:

**Comment by ThePotatoGuy** [comment]
We need answers to all the above questions to help you.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
