### ISSUE TITLE
How would I back up Monika for a full system reset?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5137]
Do I just take the whole folder and dump it into my gDrive?

**Comment by multimokia** [comment]
Your DDLC install means nothing. It's the persistent that matters, that's where her memories are stored. Take the folder of persistents (`AppData/roaming/renpy/Monika After Story`) and put that onto google drive

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
