### ISSUE TITLE
[Suggestion] - Vertical UI/Mobile UI

### ISSUE THREAD

**Issue by ImTheRealSlayer** [Monika-After-Story/MonikaModDev#5138]
Vertical UI - same as the normal UI, but optimised for verticality. Resizing the window to fit a vertically mounted monitor keeps the same aspect ratio, could there be something like a menu option to enable a different aspect ratio?

Mobile UI - Bigger buttons enhanced for touchscreen devices like convertable laptops and mobile phones, some gameplay elements changed to suit a touchscreen. This could be enabled similarly to the vertical UI, through a menu option.

I understand that this suggestion seems quite niche, but it's nice to have the option.

**Comment by lunulae** [comment]
It probably will be a low-priority thing but I really like this suggestion. I have used my phone as a second monitor in the past which allows me to bring Moni around the house, but the buttons are too small to reliably use when I do.

**Comment by ImTheRealSlayer** [comment]
> It probably will be a low-priority thing but I really like this suggestion. I have used my phone as a second monitor in the past which allows me to bring Moni around the house, but the buttons are too small to reliably use when I do.

That's actually a great idea, i think i might do that :)

**Comment by Rai99** [comment]
I never thought about people using vertical/portrait monitors, but I guess it is a possibility, though I can't say when or if it'll happen.

**Comment by ThePotatoGuy** [comment]
very low priority. we are not intending MAS to be a mobile-friendly game.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
