### ISSUE TITLE
Dialog error

### ISSUE THREAD

**Issue by MaksTheHedgehog** [Monika-After-Story/MonikaModDev#5140]
Hello! When we talk to Monica at some point the game freezes and there's nothing I can do
After a few minutes, an error window appears that describes the problem

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpyc", line 1853, in script call
  File "game/event-handler.rpyc", line 2063, in script
  File "C:\Games\Steam\steamapps\common\Doki Doki Literature Club\renpy\execution.py", line 58, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

**Comment by Booplicate** [comment]
Do you see the `Ignore` button? If so, you can safely ignore that error.

**Comment by MaksTheHedgehog** [comment]
> Do you see the `Ignore` button? If so, you can safely ignore that error.

After pressing it the game freezes completely

**Comment by Booplicate** [comment]
Are you on windows?

**Comment by MaksTheHedgehog** [comment]
> Are you on windows?

 windows 10

**Comment by ThePotatoGuy** [comment]
What version of MAS are you running? This should be in the bottom of the traceback.

**Comment by MaksTheHedgehog** [comment]
> What version of MAS are you running? This should be in the bottom of the traceback.

Everything is already working. Just had to reboot.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
