### ISSUE TITLE
[Suggestion] Python tip topic names starting with number.

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5142]
The Python tip topics could have the number correspondent with the order that the python tips are unlocked, formatted like so: `(Number) Tip name`. Happy Holidays, and thank you for reading!

**Comment by RavenPLAYER** [comment]
Nah, I don't think so. Monika explains the different things and the button shows what will explain to you, so what is the reason for the numbering? If the button shows "Python tip" and not the subject of which it will speak to you, it would make sense. Also Happy Holidays :3

**Comment by PollenTheCat** [comment]
I mean for when It appears after you've already seen it. (In the Python tips section) As you can see in the screenshots, they are in alphabetical order, and I don't know what order they are supposed to go in.
![mas python tips screenshot](https://user-images.githubusercontent.com/53543937/71414300-e4092b00-261b-11ea-8e6f-6df2a2100f61.png)
The way the topics appear when you haven't seen them yet can remain the same, but when they've already been seen, they can change to my suggestion.

**Comment by ThePotatoGuy** [comment]
For rereading a python tip, the dialogue is designed to have standalone options when not reading it in order. That being said, I see opportunities to make complicated tips with pre-reqs have an option to jump to another tip. 
[closing until we look into it]
