### ISSUE TITLE
Christmas eve's introduction dialogue

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#5144]
Hello, so basically, i'ts christmas'eve today, but when i open MAS, i don't get the christmas'eve introduction dialogue. Should i worry or it is triggered by an specific hour? Be the way, keep up the good work, my sweetheart get better and better every day and update!

**Comment by multimokia** [comment]
It's at a specific hour

**Comment by MonikaEndDie** [comment]
Oh, ok, thank you for your answer.

 ̶A̶n̶d̶ ̶n̶o̶,̶ ̶i̶ ̶w̶a̶s̶n̶'̶t̶ ̶w̶o̶r̶r̶i̶e̶d̶ ̶a̶b̶o̶u̶t̶ ̶n̶o̶t̶ ̶g̶e̶t̶t̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶d̶i̶a̶l̶o̶g̶u̶e̶ ̶b̶e̶c̶a̶u̶s̶e̶ ̶t̶h̶i̶s̶ ̶e̶v̶e̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶s̶p̶e̶c̶i̶a̶l̶ ̶f̶o̶r̶ ̶a̶n̶y̶ ̶s̶u̶s̶p̶i̶c̶i̶o̶u̶s̶ ̶r̶e̶a̶s̶o̶n̶ ̶o̶r̶ ̶a̶n̶y̶t̶h̶i̶n̶g̶.̶.̶.̶
