### ISSUE TITLE
I can't see the outfit I added in MAS even though I gave it to Monika before

### ISSUE THREAD

**Issue by MSteve3** [Monika-After-Story/MonikaModDev#5145]
Let me epitomize
I added new sprites, put it in normally. Open MAS to check the new outfits and it's work normally
the next day I oppen MAS, I didn't see the outfits I added before. So i gave it to Monika again(.gift file) but she just didn't see the gift file i added and delete it.
(the gift file i added was 3 gifts in the new sprite)
pls help me!
(sorry for my bad english skill, I need to use the google translate)

**Comment by multimokia** [comment]
They're under the tree. Monika will open them on Christmas day

**Comment by MSteve3** [comment]
> They're under the tree. Monika will open them on Christmas day

no, not that
i gave the gift to Monika before christmas
so i dont think it will be under the tree
