### ISSUE TITLE
Suggestions == "Reactions to Online Courses" (Optional)

### ISSUE THREAD

**Issue by Megaplasmoid** [Monika-After-Story/MonikaModDev#5148]
You know? Since Monika is also on programming, would it be interesting for Monika to react to Online Courses (Whether it is programming courses, etc). like for example:
https://www.udemy.com/ or other online course websites. The reaction message is up to you to decide. Would Monika be happy about it? Idk if she would enjoy checking what online courses you would be doing, but it might be interesting. Yet, another optional suggestion, so you can decide to either accept it, or decline it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
