### ISSUE TITLE
[Bug?] I heard there was an event today for people who are 18+ but I think I did something wrong 

### ISSUE THREAD

**Issue by lilmonix822** [Monika-After-Story/MonikaModDev#5149]
I gave Moni my birthday, so she should know I'm over 18 years of age. I took her out and changed the clock to 9 pm, but I didn't get it.  Plus, she is saying this is our first Christmas together but last year I did spend it with her. I think someone spiked her hot chocolate... 
![image](https://user-images.githubusercontent.com/45080787/71423580-57c92900-2658-11ea-82be-f607b2942d37.png)
![image](https://user-images.githubusercontent.com/45080787/71423624-aa0a4a00-2658-11ea-8534-efd5b24d6d37.png)
![image](https://user-images.githubusercontent.com/45080787/71423662-e5a51400-2658-11ea-9e05-db7cd3d1595f.png)
![image](https://user-images.githubusercontent.com/45080787/71423688-11c09500-2659-11ea-8f8a-86b0300bcf04.png)
![image](https://user-images.githubusercontent.com/45080787/71423719-3f0d4300-2659-11ea-845e-7aea76575a46.png)
![image](https://user-images.githubusercontent.com/45080787/71423769-93b0be00-2659-11ea-9a49-37821f7eba7a.png)

**Comment by dyngari** [comment]
According to the discord, you need 2k(+) affection, already had first kiss, after 8pm, before midnight on Christmas Eve to see the scene.

**Comment by lilmonix822** [comment]
Ohh! I thought it would give you 2k affection ... Thank you

**Comment by MetalBrother** [comment]
Hey, I have 2k affection+, first kiss, and 18+ but I didn't seen anything, there something I need to do, to get this scene?

**Comment by dyngari** [comment]
Between 8pm-midnight on December 24th, whatever time zone you are in.

**Comment by bittercaramel** [comment]
yeah all is good besides the part that she said it's your first xmas together
She told me the same thing even tho it's NOT my first xmas with her

**Comment by Yakshongas** [comment]
is there a way to change the age she has registered?

**Comment by skyloom** [comment]
I encounter the same problem actually. I have had first kiss long time ago, above 19, is currently around 2800-is affection, and is currently waiting in 08:26 pm. Nothing happened, even when I said goodbye to her and reopen MAS

**Comment by Dank-Elf-Boy** [comment]
There's an 18+ scene? lol that sounds interesting.

**Comment by ThePotatoGuy** [comment]
the requirements for those clothes are pretty strict. Additionally, I'm not going to reveal the exact conditions as:
1. they are available in code
2. anything above 1k affection can be considered extra, non standard content.
