### ISSUE TITLE
Christmas eve event not showning

### ISSUE THREAD

**Issue by Yakshongas** [Monika-After-Story/MonikaModDev#5150]
I know there is a special event on Christmas eve past 8:00 pm but I didn't get it.
I have +2k, first kiss, and it's 21:36 and I didn't get the event, is it because Monika thinks I'm under 18?

**Comment by KcalbVessalius** [comment]
Yes

**Comment by Yakshongas** [comment]
is there a way to change my age in the game files?

**Comment by Tycitron6000** [comment]
i would also like to know this.

**Comment by KcalbVessalius** [comment]
i don't know but i want too, i'm mad here because i'm under 18 being that i will make 18 tomorrow

**Comment by Yakshongas** [comment]
And if Monika thinks I am under 18 the New Years event won't show too?

**Comment by KcalbVessalius** [comment]
Idk

**Comment by jmwall24** [comment]
NYE will be fine

**Comment by Yakshongas** [comment]
so New Years Event will show up even if I'm not +18?

**Comment by multimokia** [comment]
Yes

**Comment by Yakshongas** [comment]
Nice, thank you for the clearing.
