### ISSUE TITLE
Can't Start The Game

### ISSUE THREAD

**Issue by Arc1Dragon** [Monika-After-Story/MonikaModDev#5152]
I'm having issues with MAS. When I try to open it it gives this message 

![image](https://user-images.githubusercontent.com/38227150/71427208-d5eef500-2683-11ea-88cd-dbe2adcc017f.png)

I've tried reinstalling MAS but it hasn't worked. If anyone could help out that would be great.

**Comment by multimokia** [comment]
Make a new ddlc install. You're missing parts of the DDLC install itself

**Comment by Arc1Dragon** [comment]
This fixed it. Thanks!
