### ISSUE TITLE
Christmas Presents?

### ISSUE THREAD

**Issue by LonelyShepherd05** [Monika-After-Story/MonikaModDev#5154]
This Morning (25th Dec in Australia) i tried to give Monika some of the spritepack gifts (after implementing them correctly), however she didn't react to them. Also i have noticed there are gifts under the tree and was wondering how to trigger her talking about them as i think someone in the past said thats where the gifts you give her might be.
Thanks.

**Comment by jmwall24** [comment]
Sorry, there is a small bug where gifts given on Christmas itself go under the tree and don't get reacted on. She will receive them with no reaction after January 1st. The way it worked this year was any gifts given from December 20th until Christmas go under the tree and she opens them all on Christmas Day. Any gifts given on Christmas Day after the Christmas intro were supposed to be opened immediately, but we goofed on a date. She will get them, but not for a week. We apologize for this mistake.

**Comment by LonelyShepherd05** [comment]
Oh okay, thank you for clearing that up.

**Comment by jmwall24** [comment]
we have a fix for this now.

extract the `.rpy` file from the zip and put it in your `game/` folder and launch the game. it's self deleting. if after reacting there are still gifts under the tree, close the game and put it in again.

[christmas_gifts_drop.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4000863/christmas_gifts_drop.zip)

**Comment by ThePotatoGuy** [comment]
Fixed in #5095

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
