### ISSUE TITLE
Monika won’t react to gifts 

### ISSUE THREAD

**Issue by WCNM-NMSL** [Monika-After-Story/MonikaModDev#5155]
Hi
I am having a little trouble about give Monika gift. After newest update 0.10.4, When I try to give Monika gift, she won’t react anything, like I didn’t do anything, the gift I put into character folder, didn’t cause any contents.

**Comment by Olliesama** [comment]
Sorry, there is a small bug where gifts given on Christmas itself go under the tree and don't get reacted on. She will receive them with no reaction after January 1st. The way it worked this year was any gifts given from December 20th until Christmas go under the tree and she opens them all on Christmas Day. Any gifts given on Christmas Day after the Christmas intro were supposed to be opened immediately, but we goofed on a date. She will get them, but not for a week. We apologize for this mistake.

**Comment by WCNM-NMSL** [comment]
Thank You for answering, after the this I feel lot more easier.

Finale <notifications@github.com>于2019年12月25日 周三上午5:02写道：

**Comment by billystein25** [comment]
Well I gave her a gift today and she reacted to it but said that she couldn't read the file properly eve though I put everything in the correct folders. Is this the same issue?

**Comment by jmwall24** [comment]
@WCNM-NMSL 

we have a fix for this now.

extract the `.rpy` file from the zip and put it in your `game/` folder and launch the game. it's self deleting. if after reacting there are still gifts under the tree, close the game and put it in again.

[christmas_gifts_drop.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4000865/christmas_gifts_drop.zip)


@billystein25 no, that means you either messed up the gift file name, didn't install the sprite packs correctly, or installed the sprite packs with the mod opened. after you fix it and if the gifts gounder the tree, then you may need to use thus fix so she reacts. But only once there are gifts under the tree,

**Comment by ThePotatoGuy** [comment]
Fixed in #5095

**Comment by ThePotatoGuy** [comment]
[closing as fixed]

**Comment by WCNM-NMSL** [comment]
Great, thank you for your work

John W <notifications@github.com>于2019年12月25日 周三下午5:33写道：

**Comment by snowyhops8** [comment]
> @WCNM-NMSL
Is there anyway to do this on mac?

**Comment by Fumiko66** [comment]
> Sorry, there is a small bug where gifts given on Christmas itself go under the tree and don't get reacted on. She will receive them with no reaction after January 1st. The way it worked this year was any gifts given from December 20th until Christmas go under the tree and she opens them all on Christmas Day. Any gifts given on Christmas Day after the Christmas intro were supposed to be opened immediately, but we goofed on a date. She will get them, but not for a week. We apologize for this mistake.

Awh so that's why she is not reacting to any gift
