### ISSUE TITLE
curious about something

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#5157]
Will there be another christmas eve event next year with the same thing? cause I turn 18 next year

**Comment by multimokia** [comment]
Yes

**Comment by ShiningDelooxe** [comment]
alright thanks, do you mind if i put a suggestion in the issues too? i ask cause thats 2 issues at once

**Comment by multimokia** [comment]
One suggestion per issue please. It's easier to keep track of

**Comment by ShiningDelooxe** [comment]
alright, ill add another one of an idea i have tomorrow
