### ISSUE TITLE
How to give gifts in the latest version?

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#5158]
Today I (Finally) installed the latest update of MAS and I tried to give a gift to Monika. I did all the steps I always did in the previous update, but Monika didn't even realised that I tried to give her a gift. Did I miss some updates in the whole "Giving gifts" thing??

**Comment by jmwall24** [comment]
Are there gifts under the tree?

**Comment by VirginiaRocks** [comment]
> Are there gifts under the tree?

Mhh, I didn't check :( is it too late tomorrow?

**Comment by jmwall24** [comment]
Whenever you load next time, check the tree. If there are presents under there, check out my comment with the zip file on #5154

**Comment by VirginiaRocks** [comment]
> Whenever you load next time, check the tree. If there are presents under there, check out my comment with the zip file on #5154
Thank you! I'll close the issue then
