### ISSUE TITLE
Very small bug- Christmas Cookies

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#5160]
Hello! During the Christmas event I ran into a tiny continuity issue.
Monika is reacting to the Christmas Cookies gift as though the ones I gave from last year were recent ("I still haven't finished the last batch!")
It wasn't much of an issue, but I figured it wouldn't hurt to drop here in case others had the same occur.

Hoping all the devs had a lovely holiday!

**Comment by multimokia** [comment]
Fixed in #5095 already, but thanks for reporting!

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
