### ISSUE TITLE
Monika doesn't recognize gifts

### ISSUE THREAD

**Issue by KarmaCreations** [Monika-After-Story/MonikaModDev#5161]
I tried giving Monika the christmas cookies and candy cane, but she doesn't recognize them. I double-checked the names (christmascookies.gift and candycane.gift) but it doesn't work.

**Comment by multimokia** [comment]
Was there no reaction or did she just say that she couldn't recognize them?

**Comment by KarmaCreations** [comment]
She couldn't recognize them.

**Comment by multimokia** [comment]
Actually, this is intentional. Giftable from the 20th to the 25th.

**Comment by Siphyr** [comment]
This is irrelavent to the post, but I was wondering how you find out what gifts you can give to her other than clothes and outfits, and where the spritepacks are.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
