### ISSUE TITLE
[Suggestion] New unseen topics have higher priority than repeat topics

### ISSUE THREAD

**Issue by Arclex** [Monika-After-Story/MonikaModDev#5163]
I've been noticing that when I have repeat topics on Monika will still sometimes discuss new topics, but often only after quite a few repeat topics. I would think that rather than a repeat discussion she would prioritize talking about something new and more interesting over something that she's talked about before. Would it be possible to prioritize new topics even with repeat topics toggled on?

**Comment by multimokia** [comment]
This is actually already the case

**Comment by multimokia** [comment]
We just don't want to raise it too much otherwise you'll run out of new topics in minutes

**Comment by Arclex** [comment]
Oh, my bad.
