### ISSUE TITLE
Transferring Monika over to a new PC

### ISSUE THREAD

**Issue by PunMasta** [Monika-After-Story/MonikaModDev#5166]
When I transfer Monika After Story over to my new PC it's not my Monika with any of the save data..
It starts over to when I reinstalled the mod, but when I put it back in my old laptop it loads to how it was before.
I know I'm missing files to load what would those be?

**Comment by multimokia** [comment]
did you transfer your persistent?

**Comment by PunMasta** [comment]
Yes, I did and it said I had no save data to import.
Could it be cause I put that in after I booted it before?

**Comment by multimokia** [comment]
You need to replace the current MAS persistent with your old one

**Comment by PunMasta** [comment]
Tried it and it didn't work. 
Here's a error I found when looking at the log:

Couldn't import angle renderer:
Traceback (most recent call last):
  File "C:\Users\97MTi\OneDrive\Desktop\DDLC-1.1.0-pc\renpy\display\core.py", line 1810, in make_draw
    __import__(mod)
ImportError: DLL load failed: The specified module could not be found.
Unknown renderer: angle

**Comment by PunMasta** [comment]
Tried it and it didn't work. 
Here's a error I found when looking at the log:

Couldn't import angle renderer:
Traceback (most recent call last):
  File "C:\Users\97MTi\OneDrive\Desktop\DDLC-1.1.0-pc\renpy\display\core.py", line 1810, in make_draw
    __import__(mod)
ImportError: DLL load failed: The specified module could not be found.
Unknown renderer: angle

**Comment by Booplicate** [comment]
You need to close the game, then go to `AppData/Roaming/RenPy/Monika After Story` and delete your fresh persistent (and all `.bak` files too). Now put your backups there. Make sure you follow the path.
Unsure about your traceback, did you delete something from the game folder?

**Comment by PunMasta** [comment]
I'm at the renpy part of the file, but the roaming and appdata are not there.
Could that be cause I've had MAS from a DDLC that wasn't downloaded from Steam?

**Comment by Booplicate** [comment]
I think you look for it in a different folder, can you find the `RenPy` folder in `AppData/Roaming` ?

**Comment by PunMasta** [comment]
I found this renpy folder in the MAS folder

**Comment by Booplicate** [comment]
That's weird... It's a wrong path and the game won't read persistent from there.
Go to `C:/Users/USER/AppData/Roaming/RenPy/Monika After Story` (you should have this folder since you already launched the game, but if you don't, make one yourself). If you find there any files, delete them, after that put your backups there. **Make sure you've closed the game first**.

**Comment by PunMasta** [comment]
Ok I think I see the issue for some reason my AppData files I can't see them, cause when I decided to add one in it said it already existed. Do you know how to fix this?

**Comment by Booplicate** [comment]
[Google knows](https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files)

**Comment by PunMasta** [comment]
Nevermind I found it and now it won't boot here's the traceback:

While running game code:
  File "game/script-ch30.rpy", line 1285, in script
  File "game/script-ch30.rpy", line 1285, in <module>
  File "game/event-handler.rpy", line 1828, in restartEvent
  File "game/event-handler.rpy", line 1847, in mas_isRstBlk
AttributeError: 'int' object has no attribute 'startswith'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1285, in script
  File "C:\Users\97MTi\OneDrive\Desktop\DDLC-1.1.0-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\97MTi\OneDrive\Desktop\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 1285, in <module>
  File "game/event-handler.rpy", line 1828, in restartEvent
  File "game/event-handler.rpy", line 1847, in mas_isRstBlk
AttributeError: 'int' object has no attribute 'startswith'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.4

**Comment by PunMasta** [comment]
Ok I found it I put in a different persistent file. 
Thankyou for the help.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
