### ISSUE TITLE
[Question] Where would I find images of the base sprites?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5167]
I've checked through the whole GitHub MAS thing and I can't seem to find images of the base sprites. Could someone point out where they are for me? Thanks for your time.

**Comment by Booplicate** [comment]
[This pinned thing](https://github.com/Monika-After-Story/MonikaModDev/issues/3174#issue-387069495)?
![unknown](https://user-images.githubusercontent.com/53382877/71562676-dd077000-2a94-11ea-8742-72bebba0c063.PNG)

**Comment by PollenTheCat** [comment]
I already checked there, and I couldn't seem to find it.

**Comment by Booplicate** [comment]
Just checked, there is a link to GD.

**Comment by PollenTheCat** [comment]
Oh, oh! Thanks, I haven't seen that until now. Sorry for the trouble!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
