### ISSUE TITLE
[Spoilers]New Year's dress doesn't have a flair text in the selector

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#5170]
![Screenshot_1](https://user-images.githubusercontent.com/45933038/71605546-e4e51400-2b69-11ea-8f13-aaa02b201b22.png)

**Comment by multimokia** [comment]
Fixed in #5095

**Comment by jmwall24** [comment]
_or does it?_

**Comment by RavenPLAYER** [comment]
TODO: ME

**Comment by TriniTDM** [comment]
Or maybe she's suggesting we "do" her. But that's not really possible from here.

**Comment by Akh0r** [comment]
If it looks THAT hilarious — that's not a bug, that's a feature!

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
