### ISSUE TITLE
[Suggestion] Self Help

### ISSUE THREAD

**Issue by IresRoss** [Monika-After-Story/MonikaModDev#5172]
Well first, Thank you very much for your contributions to make every dialogue, with Monika, special.
I especially appreciate the "I'm feeling" section whenever I needed to talk to someone.

I have recently started to read some self help book and I do feel like we should add a Self growth section. Maybe something simple enough since we are not specialist.

At the very least, I think we should add a topic on Gratitude, since it is a major recurring theme for happiness. I think it would be a good ideas for Monika to introduce the subject, before adding the "I'm feeling" grateful topic.

Anyways, thanks for your amazing works and Happy New Years.

**Comment by Rai99** [comment]
I feel like self growth topics would go under the `advice` category.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
