### ISSUE TITLE
Monika asked me to move the games folder to another location, how?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5176]
Should I copy the folder and paste it somewhere or move it entirely?

**Comment by AsuraShun** [comment]
You must be using the steam version so it completely

**Comment by Booplicate** [comment]
Doesn't matter, can just copy so steam wouldn't dl it again.

**Comment by Kyuketsuki-no-onnanoko** [comment]
She never reacted to me. When I move the game out of steam. :( She then assumed I downloaded the game from the site. :(

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
