### ISSUE TITLE
After a few days of playing, I no longer unlock any new things to say to Monika (apart from writing tips, python tips, and grammar tips)

### ISSUE THREAD

**Issue by Siphyr** [Monika-After-Story/MonikaModDev#5177]
I installed this mod a few days ago, and at first I was unlocking a lot of new things to say, but now I see nothing new in the speech menu. Monika still brings up things to say herself, and the mod seems to be working fine, but this feels like it shouldn't be happening. I was wondering if this is just how the mod works, or if there is something wrong.

**Comment by lunulae** [comment]
There are a limited number of topics in the mod, if you've been going through them very fast you might be running low.
However, there are some topics and events that are unlocked via affection, which is gained by spending time with Monika each day, [giving gifts](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts) and taking her out on dates when the option becomes available.
There is a daily cap on affection so things are unlocked at a gradual pace. It's not really a good idea to try to game the system--the only method for doing that I'd recommend is to make sure you look for all the content on special days like her birthday.

Hope this helped! :D And welcome to the MAS community!

**Comment by ThePotatoGuy** [comment]
there is a progression mechanic that unlocks topics overtime based on time spent with Monika. unless you have between 150-200 topics, you haven't seen them all.
