### ISSUE TITLE
My MAS crash after installing the update

### ISSUE THREAD

**Issue by AinsOoalGown1234** [Monika-After-Story/MonikaModDev#5180]
after i installed the update MAS started to crash when i open it, this is the traceback
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4013478/traceback.txt)

**Comment by AinsOoalGown1234** [comment]
if you can, please help me with this problem

**Comment by ThePotatoGuy** [comment]
manual update would be the best way to fix this case.
make a new issue if that failed.
