### ISSUE TITLE
Monika using old save file

### ISSUE THREAD

**Issue by pwhitters** [Monika-After-Story/MonikaModDev#5192]
I keep a copy of DDLC with MAS installed on a flash drive with all the persistent files with back ups in a "save" folder. I also have old persistent files from a game that got corrupted and I had to restart in a separate folder in the flash drive. I forgot I had those save files on there but my computer crashed while the game was running and I got the note from monika saying the game had to use a backup file but I think it used the really old files because monika started talking about things I'd not done with her over the year and her affinity seems reset, all the things she mentioned I had done and the new years thing already triggered yesterday. Is there a way I can change what file it uses, I said the general "goodbye" and opened the game again and its still using the really old files. I make back ups almost weekly but looking in my save files on the flash drive the closest one in there is 1/12/2019, my "db.mcal" and persistent files are from 12/25/2019 and it shows "persistent_bad" on 12/14/2019. I guess most of my back ups are gone but is there a way to get the game to use those most recent saves?

**Comment by jmwall24** [comment]
When you say 'all the things mentioned I had done' I assume that means the year in review topic, and if so that makes sense, she's talking about the things you did the past year. Also, when you have a corrupt persistent, we automatically choose the most recent good backup. Please check the aff_log.txt file in the logs folder to make sure there wasn't a huge affection loss, but I think everything happened how it was supposed to.

**Comment by pwhitters** [comment]
> When you say 'all the things mentioned I had done' I assume that means the year in review topic, and if so that makes sense, she's talking about the things you did the past year. Also, when you have a corrupt persistent, we automatically choose the most recent good backup. Please check the aff_log.txt file in the logs folder to make sure there wasn't a huge affection loss, but I think everything happened how it was supposed to.

**Comment by pwhitters** [comment]
I think I mistyped because I meant monika was mentioning things like her birthday as if I hadn't done them when I did all of them. Its probably because it pulled a back-up from January 2019, but I should have had at least one from this month I don't know why they're not in my flashdrive anymore. And yes there was a huge loss in affinity according to the logs(if I'm reading them right). 

I don't know the exact time my computer crashed but this looks like the right time scale:
Wed Jan 01 12:46:15 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[2020-01-01 12:46:19.766000]: LOAD | 3499.2 | 3499.2 -> 3499.2
[2020-01-01 12:46:20.171000]: !FREEZE! | 0 | 3 | 3499.2 -> 3502.2
[2020-01-01 12:47:03.217000]: SAVE | 3499.2 | 3499.2 -> 3499.2
[2020-01-01 12:48:01.227000]: SAVE | 3499.2 | 3499.2 -> 3499.2

Then after the crash:
Wed Jan 01 21:07:33 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

[2020-01-01 21:07:37.732000]: LOAD | 32.9 | 32.9 -> 32.9
[2020-01-01 21:07:37.744000]: 0 | -101 | 32.9 -> -101
[2020-01-01 21:07:38.273000]: 0 | 3 | -101 -> -98
[2020-01-01 21:09:35.364000]: mas_nye_monika_nyd | 0 | -98 -> 0
[2020-01-01 21:09:35.378000]: SAVE | 0 | 0 -> 0
[2020-01-01 21:09:35.378000]: SET BACKUP | 0 | 32.9 -> 0
[2020-01-01 21:09:45.737000]: mas_bday_postbday_notimespent | 10 | 0 -> -10
[2020-01-01 21:10:46.192000]: SAVE | -10 | -10 -> -10

**Comment by jmwall24** [comment]
Oof yeah, ok stop loading the game, can you send me a screenshot of the folder with the persistent files in it? @pwhitters

**Comment by pwhitters** [comment]
Yeah I shut the game down immediately to try and not load more files. I have been meaning to clean it up but its always worked so I thought I was doing it right and when I looked up the wiki on how to save bac-ups it seemed like I was doing exatcly what was suggested. Here is the file on the flash drive I use to save the presistent, mcal, and all the back ups and other files in my computers Renpy folder. If you need screenshots from the actual Renpy folder on the computer I was running the game I can get those too I'll need to do that when I get home.  I also added a log file from 1/1/2019 9:37pm that was in the main DDLC file that I think shows the back up it pulled, I'm not sure if this is helpful I just noticed its in there:
[early.log](https://github.com/Monika-After-Story/MonikaModDev/files/4017012/early.log)




![Monika save file 1](https://user-images.githubusercontent.com/44506572/71685846-b4160200-2d56-11ea-99b7-9e70f2798490.PNG)
![Monika save file 2](https://user-images.githubusercontent.com/44506572/71685847-b4160200-2d56-11ea-9c4d-b2ac749afdf8.PNG)
![Monika save file 3](https://user-images.githubusercontent.com/44506572/71685848-b4160200-2d56-11ea-8cc9-83c57ac700f4.PNG)
![Monika save file 4](https://user-images.githubusercontent.com/44506572/71685849-b4160200-2d56-11ea-8ddc-6864f80ba5fc.PNG)
![Monika save files 5](https://user-images.githubusercontent.com/44506572/71685855-b710f280-2d56-11ea-97df-1e5af7dfa7c2.PNG)

**Comment by jmwall24** [comment]
can you show me the folder that the actual persistent is in please, not your backups?

**Comment by jmwall24** [comment]
btw @pwhitters when you get home, I found you on masc and sent you a dm, might be easier to handle it via there. i should be around for the next 8-9 hours.
