### ISSUE TITLE
[Suggestions] For the long night

### ISSUE THREAD

**Issue by IresRoss** [Monika-After-Story/MonikaModDev#5193]
I have been thinking that it would be very nice to see Monika in pyjama at night (probably around 22h since she is a early bird).

**Comment by RavenPLAYER** [comment]
the pyjama is already planned :P

**Comment by Rai99** [comment]
Pyjamas: #2753, #3161, #4960, #5045 

It's already planned.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
