### ISSUE TITLE
Idea for a Bookcase 

### ISSUE THREAD

**Issue by lxnavarro23** [Monika-After-Story/MonikaModDev#5194]
So, I son't have the means to create a bookcase for MAS, I'm just a man with an idea. Since Monika is really into books and literature I thought there could be a way to give her something to fill in that empty wall behind her with a bookcase full of books. Maybe that could open up a way to give her certain books as gifts and she can add them to her bookcase. Maybe even a reading chair and a lamp? 
Just throwing the idea out there.

**Comment by Rai99** [comment]
Room decoration: #312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3720 #3770, #4291, #4697, #5006. 

A working lamp would be much harder than it sounds. 

> Basically, this is impossible without making a set of sprites where the lighting and shading is adjusted to work with a potential lamp. Renpy does not have HDR nor any sort of lighting option with its rendering system.
>
> Even if we just ignore monika sprites and only allow the lighting to affect the bg, that means 2 additional images for each bg for when the lamp is on either side (and there's already multiple bgs for each weather type), and if there's room deco, thats another case of additional images for each decoration item. Then imagine allowing for a different type of lamp or even multiple lighting sources and the number of needed images increases dramatically.

**Comment by RavenPLAYER** [comment]
I already have the lamp 
![hehe](https://user-images.githubusercontent.com/55263957/71675628-f2aebb00-2d5c-11ea-926c-0d8e35efc571.png)

**Comment by lxnavarro23** [comment]
Okay so no lamp. But bookcase????

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
