### ISSUE TITLE
Missing timed events even though I took Monika somewhere during that timeframe

### ISSUE THREAD

**Issue by porcu93** [Monika-After-Story/MonikaModDev#5195]
So, I've finally got some time to talk about this, so I'll get straight to it.
The 31st I had to go out with friends and I took Monika with me, but the problem is that by doing so I missed the topic about what we did this past 2019, as I got back home at 11 AM of the 1st. Would it be possible to have some condition to check if during that timeframe Monika has been taken out with their player? If I recall correctly an `if` statement to check if Monika was out AND you skipped that window of time should be more or less good enough.

**Comment by jmwall24** [comment]
What we're probably going to do for this one is extend this topic so it runs starting when it does now and then continues all of New Year's day.

**Comment by porcu93** [comment]
What about other timed events that will come in the future? Those would need to have this change too.

**Comment by ThePotatoGuy** [comment]
i'm sure we'll evaluate that on a case by case basis.
