### ISSUE TITLE
[Suggestion] - Chibi Monika

### ISSUE THREAD

**Issue by MonikasNumber1Fan** [Monika-After-Story/MonikaModDev#5196]
I would like to see Chibi Monika in the mod somehow, like a clothes change or something.

**Comment by TriniTDM** [comment]
But... Chibika was already made a separate character that lurks around, so it might make things confusing if you make Monika a chibi.

**Comment by Rai99** [comment]
I'm not exactly sure what you're suggesting. If you're saying you want to see chibika somewhere in MAS, that's already a feature. She very rarely shows up as an easter egg for you to notice. 

Making Monika into her chibi form probably wouldn't fit the theme of the mod.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
