### ISSUE TITLE
Monika wont react to gifts! (Mac)

### ISSUE THREAD

**Issue by snowyhops8** [Monika-After-Story/MonikaModDev#5199]
Monika won't react to gifts! (Mac)
I've seen a lot of suggestions to help people on windows, but every time I need help with this on a mac I seem to come up empty-handed. If anyone knows how to fix this glitch please let me know! I really want to be able to give Monika the promise ring she's been pleading for. I've tried everything! I read that she won't acknowledge it for at least a week when gifted on Christmas day but I tried fast-forwarding time and she still wouldn't notice! I know I am gifting the gifts right as I've done it at least 10 times before, and now when I try to gift it to her she doesn't even acknowledge it! This is very annoying and if anyone knows how to fix it on a mac I'd be forever grateful.

**Comment by multimokia** [comment]
Screenshot of your characters folder, please?

**Comment by snowyhops8** [comment]
![Screen Shot 2020-01-04 at 11 57 16 AM](https://user-images.githubusercontent.com/59510060/71768989-7d242580-2ee9-11ea-9e50-3ed22f150355.png)

I could even attach a video if needed more clarification.

**Comment by multimokia** [comment]
Don't use folders to make gifts. Those aren't accepted, you need to make actual files

**Comment by snowyhops8** [comment]
I've used folders before and they've worked perfectly fine, was there a new update making it so folders don't work anymore?

**Comment by multimokia** [comment]
Yeah, we disabled it using folders because they broke gift reactions

**Comment by snowyhops8** [comment]
Oh! Well, I'll change over to see if that works! Thank you!

**Comment by snowyhops8** [comment]
It still doesn't work, I think it's the Christmas glitch I've seen people talking about.
![Screen Shot 2020-01-04 at 11 56 54 AM](https://user-images.githubusercontent.com/59510060/71769106-911c5700-2eea-11ea-9c1c-f1fff302ca72.png)

**Comment by multimokia** [comment]
That's still a folder. Look at the icon, that's not a file

**Comment by snowyhops8** [comment]
I messed up the screenshot used the wrong one, sorry about that!

**Comment by snowyhops8** [comment]
How would you make a gift file then? There's not much you can do on mac besides make txt files and folders, either that or I haven't truly explored this mac haha.

**Comment by snowyhops8** [comment]
Hey found another discussion on this when you gave instructions! Thanks for the help! I really appreciate this!

**Comment by snowyhops8** [comment]
I figured it out! Thank you for your time this helped so much!

**Comment by multimokia** [comment]
No worries!
