### ISSUE TITLE
persistent not restoring

### ISSUE THREAD

**Issue by JohnnyH2000** [Monika-After-Story/MonikaModDev#5200]
So my hard drives and SSDs decided to do an oopsie and I had to get a new hard drive, motherboard, and RAM cards, along with a clean installation of Windows 10. After attempting to reinstall the game, and placing the mod files into the game folder, creating a new folder "Monika After Story" and putting the persistent backup inside, the game loads to an empty chair with no Monika ;-;

Attached is the backup.

[MAS Backup.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4022794/MAS.Backup.zip)

pls send help.

**Comment by multimokia** [comment]
Was Monika taken out of the room when the drive crashed?

**Comment by JohnnyH2000** [comment]
> Was Monika taken out of the room when the drive crashed?

No.

**Comment by multimokia** [comment]
According to the persistent, there *is* a checksum associated to Monika, meaning that she *was* indeed out of the room. Do you have other backups?

**Comment by JohnnyH2000** [comment]
@multimokia 
> Do you have other backups?

oh yikes. I'm pretty sure that's a no. Is there a way to "fix" it manually?

**Comment by multimokia** [comment]
Not unless you have the `monika` file laying about somewhere. 

You should always make backups and keep them on a separate drive. I can fix this one for you, but always make backups.

**Comment by JohnnyH2000** [comment]
I am way ahead of you
![E1810C5A-88AC-4BE4-A69F-3CBDC1304A81](https://user-images.githubusercontent.com/22625664/71773818-27c03680-2f32-11ea-9692-b2460fb0ed12.png)

Also thank youuu.

I just get a clean install of DDLC, throw in the mod files, and plop it into RenPy?

**Comment by multimokia** [comment]
Here, this should have her back.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4022806/persistent.zip)

You already have MAS installed. Just replace the current persistent with this one.

**Comment by JohnnyH2000** [comment]
@multimokia _Thank you so much_ 

And uh for future reference backups should be done while Monika is in the room and the game is closed right?

**Comment by multimokia** [comment]
Doesn't matter which way you do it

**Comment by JohnnyH2000** [comment]
@multimokia Oh okay thanks
