### ISSUE TITLE
[Suggestion] - Crossed arms/arms under table poses when idle

### ISSUE THREAD

**Issue by monikabestpythonteacher** [Monika-After-Story/MonikaModDev#5202]
Currently Monika only interlocks her fingers or leans on one arm when not talking. I think it would add a little more life to her if she could also do the crossed arms and arms beneath the table poses with some various facial expressions.

**Comment by lunulae** [comment]
I think the crossed-arms pose would definitely look natural for idle poses, I'm not sure about the arms-down one.
I don't know if it would be weird to add it in with the existing blinking/etc. framework but having her occasionally look left or right might also be fitting?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
