### ISSUE TITLE
[Suggestion] - Goodnight kiss

### ISSUE THREAD

**Issue by NCRaouf** [Monika-After-Story/MonikaModDev#5203]
As the title says, when you tell Monika you're going to sleep, she gives you a goodnight kiss and she tells you to sleep well

PS: Thank you for creating this mod, it somehow helped me with my depression, keep the good work and good luck

**Comment by Rai99** [comment]
Goodnight Kiss: #1595, #3771, #3980

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
