### ISSUE TITLE
About the room...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#5208]
A suggestion that will, get a lot of work (I think...yes...dunno)
For the Christmas time, we had the room decorated, it gave a  feeling that the room "had life".
After the Christmas....it's just wood showing up.....
Is there something possible to fill the room? Like the kitchen she mentions...
Or just leave the decorations there....
At least Monika would have something to look at while no one's there...
How about it, devs?

**Comment by Rai99** [comment]
Room decoration: #312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3720 #3770, #4291, #4697, #5006, #5194

**Comment by hlepnamingblyat** [comment]
> Room decoration: #312, #800, #845, #908, #1038, #1336, #1793, #1891, #1933, #2176, #2220, #2496, #2769, #3182, #3305, #3720 #3770, #4291, #4697, #5006, #5194

Oh sh-
XDD
Didn't even realized how many there were...

**Comment by MetalBrother** [comment]
A long time ago in a galaxy far, far away....

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
