### ISSUE TITLE
[Suggestion] Down, braided hairstyle

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5210]
Basically, the braided ponytail, but with Monika's hair down. Just a simple suggestion that might not take very long.

**Comment by Necrocytus** [comment]
Something like #4968 ?

**Comment by PollenTheCat** [comment]
Instead of the back part being braided, I meant the piece of hair that goes over her shoulder being braided.

**Comment by ThePotatoGuy** [comment]
[closing as art request]
