### ISSUE TITLE
Does anybody know what went wrong here?

### ISSUE THREAD

**Issue by Chris0273** [Monika-After-Story/MonikaModDev#5212]
After I updated the game I got this:

While running game code:
ScriptError: Name (u'/home/potato/dddlc/0104/game/chess.rpy', 1575761872, 110) is defined twice, at game/chess.rpy:3 and mod_assets/chess.rpyc:3.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/potato/dddlc/0104/game/chess.rpy', 1575761872, 110) is defined twice, at game/chess.rpy:3 and mod_assets/chess.rpyc:3.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please

**Comment by Chris0273** [comment]
![Screenshot2](https://user-images.githubusercontent.com/43796465/72207732-01ebe200-349c-11ea-8549-58521d926d72.PNG)
![Screenshot1](https://user-images.githubusercontent.com/43796465/72207734-03b5a580-349c-11ea-863c-ccb15e22c6fd.PNG)

**Comment by multimokia** [comment]
Hmmm, where did you put the updated files? Your modified dates on the script files are outdated

**Comment by Chris0273** [comment]
I just put them in the game folder, like always.

**Comment by multimokia** [comment]
Oh I see, you installed into `mod_assets` rather than `/game`. Looking at the traceback: `game/chess.rpy:3 and mod_assets/chess.rpyc:3`

So there's one in `/game` (where it should be) but also one in `/mod_assets`. Seeing the modified dates, I assume you accidentally dropped the update into `/mod_assets`

**Comment by Chris0273** [comment]
Thanks
