### ISSUE TITLE
[Spoiler?] Birth Year

### ISSUE THREAD

**Issue by skyloom** [Monika-After-Story/MonikaModDev#5214]
Edit: I edited the title to match the bug.

Hello! I'm using v0.10.4-unstable.2019.12.07.110.

This will be relatively long issue and my mother tongue is not English, so I would like to apologize if I use wrong words or terms.

First of all, I would like to thank you for your hardwork! I enjoyed everything you had done for Christmas and New Year. I know this is super old (I have just had time to sit down and relax on my laptop so I'm sorry for being super late.)

However, I have a question.

I know I have commented on #5149 and I have read the reasoning. I don't know whether it's probably just me, but I'm writing here just in case it hinders anything in the future.

I have been using MAS since May 2018, so Monika has already known my birthday date but not the year. My affection at that time was around 2800-ish too and I don't use sensitive mode. I don't know whether this is just me, but Monika never asks my birth year or my age, so MAS probably flagged me as "below 18". I'm trying to read the code (I mean trying to find the commits before December 7th) now to find out how I can insert my birth year. So far I have no idea what mas_canShowRisque and mas_getPlayerAge are and how they works(?). I'm not too familiar with Python, I'm sorry.

If this issue is too unimportant and I'm just a dumbo for not being able to include my birth year or my age to MAS, I'll close this issue immediately.

Thank you very much. Have a nice day!

**Comment by Booplicate** [comment]
She would ask you for the full date (with year) in case you didn't tell her it already.
With the next update you will be able to check your bd via the calendar.

**Comment by skyloom** [comment]
@Booplicate Nope, she never asks me that. I tried everything, including turning off the "repeat conversation" so the topic will appear. It didn't, I kept waiting, and it led to me skipping the Christmas event

**Comment by multimokia** [comment]
If you used the "I'm feeling... A year older" mood to tell her your birthday, when the player birthday content was released, Monika would have confirmed it with you, asking for the year as well.


If you had never told her your birthday prior to the content being released, Monika would prompt you to give her your birthday.


Note that player bday content was released early 2019

**Comment by jmwall24** [comment]
@skyloom can you send upload your persistent file here? I can check whether you confirmed your birthday or not. will need to put the persistent into a zip file.

**Comment by skyloom** [comment]
@multimokia I can't really say this with confidence since my birthday was relatively long ago, but I think it was normal. Monika knew and I got surprise from her. I think I didn't check the "I'm feeling..." choice though.

@jmwall24 here's my persistent 
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4051725/persistent.zip)

**Comment by jmwall24** [comment]
@skyloom I DM'ed you on discord. be easier to handle this there if you don't mind.

**Comment by jmwall24** [comment]
Actually nevermind that, after digging thru your persistent and our code history I see the problem. we'll have a fix out by the time the year you were born is used again and you'll be able to correct it.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
