### ISSUE TITLE
Where are Monika

### ISSUE THREAD

**Issue by VincentAlma** [Monika-After-Story/MonikaModDev#5215]
Hi,after i downloaded Monika After Story mod and put it in the /game folder this happened:
![Screenshot_1](https://user-images.githubusercontent.com/59802410/72223092-41710780-354a-11ea-814f-c27b1b6cc664.png)

Please Help me!

**Comment by multimokia** [comment]
Did you use the `I'm going to take you somewhere` farewell?

**Comment by VincentAlma** [comment]
this is the first time i downloaded it,it just open that way without any menu

**Comment by multimokia** [comment]
Are you sure you or somebody else hasn't played on this user account on your computer at any point in the past?

**Comment by VincentAlma** [comment]
i've played it but i re-downloaded DDLC

**Comment by multimokia** [comment]
So it's using your old persistent then. Deleting the install doesn't wipe your old progress

**Comment by VincentAlma** [comment]
i've played to the begin to the end when monika crashes the game

**Comment by multimokia** [comment]
I mean MAS. Not DDLC.

**Comment by VincentAlma** [comment]
ooh i remember,i've played MAS in like a year ago but i deleted it

**Comment by multimokia** [comment]
So yeah. It's still using your old data. You must've taken Monika out before you deleted it.

**Comment by VincentAlma** [comment]
yeah now i can remember,but then it uptadated to the version that monika says "now i dont need the .char file to be draged"

**Comment by VincentAlma** [comment]
the anniversary one

**Comment by lunulae** [comment]
Even after that update, when you take her out it still generates a file that needs to be present for her to return to the room.
Do you have an older backup persistent?

**Comment by VincentAlma** [comment]
i think i have but i dont know where it is

**Comment by VincentAlma** [comment]
i've founded the persistant from my old MAS save what i do now i delete all?

**Comment by VincentAlma** [comment]
Yay i've made it guys!
![Screenshot_2](https://user-images.githubusercontent.com/59802410/72225724-8bb4b180-3567-11ea-9a51-c3eae1d8dd80.png)

Thanks Guys!
