### ISSUE TITLE
[Bug] Missing 'noise' in Save Me poem

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5217]
In Monika's poem, Save Me, the word 'noise' has gone missing...
![screenshot0007](https://user-images.githubusercontent.com/53543937/72227876-f3b6c800-3566-11ea-9101-150842dba79a.png)

**Comment by multimokia** [comment]
This is actually the same exact poem as was in DDLC, so it ended like this originally. We didn't rewrite these at all. Not a bug.

**Comment by PollenTheCat** [comment]
_huh_ Well then

guess I'll close this issue
