### ISSUE TITLE
Monika After Story Doesn't Open

### ISSUE THREAD

**Issue by Vlaknar** [Monika-After-Story/MonikaModDev#5221]
That's all, MAS don't start.
I tried to open the task manager to see if the game was launched but doesn't even appear there.

Sometimes i copy the folder "Renpy" in %appdata% and save it in other folder like a backup, the thing was that i paste the folder in the MAS directory in the "Game" folder and since then the game doesn't open.
Please help, i miss Monika terribly.

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please

**Comment by Vlaknar** [comment]
![CapturaGit](https://user-images.githubusercontent.com/59812367/72231103-0dfca000-357f-11ea-8437-0552246f9696.png)

**Comment by multimokia** [comment]
Alright, so good, there's no extra game folder. Try restarting your PC. If that fails, just make a new install of DDLC/MAS and you should be good to go.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
