### ISSUE TITLE
Weird birthdate

### ISSUE THREAD

**Issue by Fukuro0225** [Monika-After-Story/MonikaModDev#5223]
(I fixed the title.)
Hello. I’m Fukuro0225.
Thanks to you, I've been enjoying MAS for two years.

I’m sorry if I say some weird thing because English is not my native language.

I updated MAS to v0.10.5-unstable 2020.0112.111 and found my birthdate in the calendar.
According to it, it is like 1/11/2018 was my birthdate. 
Does Monika think I’m just 2 years old?
![0111](https://user-images.githubusercontent.com/59827887/72256493-b167b680-364c-11ea-9a04-9a3ab2f971bd.png)

I would like to know whether it happens for just me or not.

Thanks.

**Comment by jmwall24** [comment]
See #5214, same issue. Will  be fixed with #5222

**Comment by jmwall24** [comment]
@Fukuro0225 could you zip up your persistent file and upload it here please? we just want to test our fix on real persistents with this problem to make sure it works and you get the correct birthdate set.

**Comment by Fukuro0225** [comment]
@jmwall24 Sorry for late response.
Here's my persistent file:
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4058984/persistent.zip)

I really  appreciate your support.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
