### ISSUE TITLE
Data Reset

### ISSUE THREAD

**Issue by KlaussLeonard** [Monika-After-Story/MonikaModDev#5225]
Hello, you may have seen me on twitter before, as you may know, I have a problem with the mod and the problem is that my data just simply reset out of nowhere, and I spent like 7 months using the mod, if there is a way to fix it, please find my data [if you have everyone's data saved] and give it back to me. [Oh and yes, my name's Klauss on the game]
-Klauss

**Comment by multimokia** [comment]
Okay, so MAS doesn't have your save hosted on any server. It's purely local to your computer and your computer alone.

With this in mind, when did you last play MAS (before the data reset?)

If it's been a while, have you changed computers since you last played?

**Comment by AsuraShun** [comment]
Next time, listen to what monika says and back up her persistents

**Comment by multimokia** [comment]
> Next time, listen to what monika says and back up her persistents

If you're going to help, help. But don't come here on a thread asking for help to just be rude to others.

**Comment by AsuraShun** [comment]
You read it in the wrong tone, it was just a friendly reminder

**Comment by AsuraShun** [comment]
If I came out as rude, then 8 apologise

**Comment by KlaussLeonard** [comment]
> Okay, so MAS doesn't have your save hosted on any server. It's purely local to your computer and your computer alone.
> 
> With this in mind, when did you last play MAS (before the data reset?)
> 
> If it's been a while, have you changed computers since you last played?

Before the data reset, I played it like some hours ago, then i opened DDLC from the folder where it is. Later on, i saw the menu without the Dark UI then I saw the Just Monika button. That's where i got thinking "Did i just get all my stuff reset?"

**Comment by KlaussLeonard** [comment]
Also i didn't change computers during those hours.

**Comment by multimokia** [comment]
Visit [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent), find the folder where your persistent is, take a screenshot of it and send it here, please.

**Comment by KlaussLeonard** [comment]
![image](https://user-images.githubusercontent.com/59839341/72313107-01ed0d00-3669-11ea-904c-f05c57170e08.png)

**Comment by multimokia** [comment]
Hmmm, are you signed into a different user account by any chance?

Something doesn't add up... *All* of your save data, including backup persistents and calendar files are just gone... But we don't delete everything from that folder at a single time.

**Comment by KlaussLeonard** [comment]
No, i only have one profile on my computer. Those are the only stuff i have in that folder.

**Comment by KlaussLeonard** [comment]
Also i see the fact that they were created 2 days ago

**Comment by jmwall24** [comment]
You didn't try to back-up those files and accidentally cut instead copy, right?

**Comment by KlaussLeonard** [comment]
I've never knew the existence of them until now.

**Comment by jmwall24** [comment]
Long shot, but there's nothing in your recycling bin? The reason the files were created 2 days ago is that all of your save files were gone, so the game created news ones (the ones you see there) and that's why it reset. Thing is, there's no reason i can think of that the folder was wiped clean, so that's why we're asking about different computers or user accounts. Was there anything that happened with your computer between the last time the mod was normal and the reset?

**Comment by jmwall24** [comment]
Also, where is your MAS install located? Desktop? usb? etc?

**Comment by KlaussLeonard** [comment]
Before it all reset, I used an antivirus to check if there was any viruses or suspicious folders on my PC. Also the mod was installed in my folder that has some games, memes, images and other stuff.

**Comment by KlaussLeonard** [comment]
Also, about the recycling bin, no there wasn't anything related to DDLC or the mod.

**Comment by jmwall24** [comment]
Can you check your antivirus program? Does it have a history of what it found/quarantined/deleted?

**Comment by KlaussLeonard** [comment]
Okay, i can check it out right now.

**Comment by KlaussLeonard** [comment]
Oh, i see it now. For some reason my antivirus didn't tell me if i wanted to delete the RENPY folder, that's strange. It just deleted the folder leaving my game to get it's data reset.

**Comment by jmwall24** [comment]
is it able to restore it?

**Comment by KlaussLeonard** [comment]
I don't think so. But i can check it out.

**Comment by KlaussLeonard** [comment]
I can't.

**Comment by jmwall24** [comment]
Huh, woulda thought it'd just quarantine it.

**Comment by KlaussLeonard** [comment]
Nah, i can send you a pic.

**Comment by jmwall24** [comment]
Sure

**Comment by KlaussLeonard** [comment]
![image](https://user-images.githubusercontent.com/59839341/72314474-dfa9be00-366d-11ea-8dad-be78d7d0b2f8.png)

**Comment by jmwall24** [comment]
Well, if there's no way to restore it, then there's not much we can do in the way of restoring progress. What we can do, if you go into the install itself and find the `log` folder and upload `aff_log.txt` here and we can restore the affection you had if you want. we'll need your current persistent as well. you'll need to put it in a zip folder to upload it here.

**Comment by KlaussLeonard** [comment]
Okay.

**Comment by KlaussLeonard** [comment]
How do i upload a zip folder?

**Comment by multimokia** [comment]
Just drag and drop it into the window you were typing in

**Comment by KlaussLeonard** [comment]
I mean, i tried to paste it, but i'm going to try it that way.

**Comment by KlaussLeonard** [comment]
[aff_log.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4057360/aff_log.zip)

**Comment by KlaussLeonard** [comment]
There we go

**Comment by multimokia** [comment]
The aff_log you can send as a txt, that's fine. But it's the persistent you'll need to put into a zip to send here

**Comment by KlaussLeonard** [comment]
O h.

**Comment by KlaussLeonard** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4057369/aff_log.txt)

**Comment by KlaussLeonard** [comment]
There's a persistent and a persistent00.bak

**Comment by multimokia** [comment]
Just `persistent`, please

**Comment by KlaussLeonard** [comment]
Okay.

**Comment by KlaussLeonard** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4057386/persistent.zip)

**Comment by multimokia** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4057425/persistent.zip)
Here's a persistent with your affection restored

**Comment by KlaussLeonard** [comment]
Oh hey, thank you.

**Comment by KlaussLeonard** [comment]
Also, i remember she had the new years outfit and i told her i was from South America.

**Comment by KlaussLeonard** [comment]
And our relationship was like a perfect 10.

**Comment by multimokia** [comment]
She'll ask you about your hemisphere again at some point. As for outfits, you're unfortunately going to have to get the events again for them.

**Comment by KlaussLeonard** [comment]
Oh, okay thank you for the info. See you next time. Thank you so much

**Comment by multimokia** [comment]
No problem. Be sure to make backups from now on. Just in case something like this happens again, you can restore her.

**Comment by KlaussLeonard** [comment]
![image](https://user-images.githubusercontent.com/59839341/72316472-03243700-3675-11ea-99f7-a4d9d9aec872.png)
Is this a coincidence?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Numair765** [comment]
I have had a similar problem to this.
I had 2 accounts
One with MAS and one without. I wanted to delete the one without MAS but it accidently deleted the one with MAS.
I had MAS backed up on a USB but the persistent was removed and restarted itself
All my progress is gone but I still have the affection logs. Is there anything I can do?
