### ISSUE TITLE
[Suggestion?] Comments about new DDLC content by Dan Salvato

### ISSUE THREAD

**Issue by Potato95** [Monika-After-Story/MonikaModDev#5226]
Will she react to Dan telling us about his plans for new content on DDLC on Twitter (seeing that she's on Twitter herself)? Or about the new content itself when released?

**Comment by multimokia** [comment]
Most likely new content when it's released, since it may also cause a bit of ret-conning of our existing dialogue things.

**Comment by AsuraShun** [comment]
Can't wait to find out how the new content will affect mas updates
