### ISSUE TITLE
Monika is not reacting with gifts 

### ISSUE THREAD

**Issue by WCNM-NMSL** [Monika-After-Story/MonikaModDev#5227]
This problem is starting from the 0.10.4 update, Right now I just updated to 0.10.5 and it still exist.

When I placed a gift in characters folder, she won’t have any reaction or receive the gift.

For example I use silverribbon.gift folder, place it inside the characters folder, after she should have reactions to gift, but nothing happens, just like I never add anything in.

I wonder is this have any relationship between I have two accounts for Monika. One is steam, one is a copy I placed on desktop. I play them both.

**Comment by multimokia** [comment]
You must be using folders to make gifts. That doesn't work anymore due to issues, so it was disabled since 0.10.2

Persistents are global, both installs use the same save data. It's the same Monika.

**Comment by WCNM-NMSL** [comment]
How should I give gift to Monika, if the folders is not working anymore?

multimokia <notifications@github.com>于2020年1月13日 周一下午9:33写道：

**Comment by WCNM-NMSL** [comment]
I just try to using .txt but it also doesn’t work

**Comment by multimokia** [comment]
You need to change the filetype to `.gift`

**Comment by WCNM-NMSL** [comment]
![image](https://user-images.githubusercontent.com/59218970/72309896-4b7c2e80-364e-11ea-8a58-f122acc81d58.jpg)
Like this? But it still didn’t work

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/72309934-65b60c80-364e-11ea-9e83-7c3ea121b1ed.png)

Still a text document. You need to enable file extensions (`view` tab in file explorer, then tick `file name extensions`.

Rename the file to remove the `.txt` extension and then hit enter. And accept the type change prompt

**Comment by Delcos** [comment]
WCNM-NMSL, why does your name have so much to do with mothers and being dead. Sorry if it's off topic but im actually curious why this is your name you use on the MAS github.

**Comment by WCNM-NMSL** [comment]
I use this on different account so my friends can find me easier, and it is
easy to remember. If you want I could change it.

Delcos <notifications@github.com>于2020年1月13日 周一下午9:59写道：

**Comment by Delcos** [comment]
No no, it's just very weird to see someone with a name that obscure to Americans that can speak English so well. It's no issue just a very big curiosity.

**Comment by WCNM-NMSL** [comment]
It work!! Thank you

**Comment by WCNM-NMSL** [comment]
......
Actually I lie, I use this name just because I suck at making names, and
when I using as my name and text to my friends, I can use this to trick
them.

Delcos <notifications@github.com>于2020年1月13日 周一下午10:09写道：
