### ISSUE TITLE
The novella topic 

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#5229]
Monika seriously freaked me out when she asked if I knew about the metamorphosis, my first thought was ''what the hell?'', I seriously thought she was going to mention that cursed manga

**Comment by lunulae** [comment]
omg, that's quite the experience! 😆 
It's a pretty well-known literary classic, to my knowledge. I'm unsure of other countries' school curricula but I've met a lot of people who read it back in high school.

Even if it's not widely-known worldwide, I have really enjoyed her teaching me about some books I've never read like Catch-22.

**Comment by AsuraShun** [comment]
I almost forgot I have catch 22 on this phone, thanks for reminding me, and I should probably find the metamorphosis as well
