### ISSUE TITLE
Suggestion for new Clothes

### ISSUE THREAD

**Issue by Rakoor** [Monika-After-Story/MonikaModDev#5230]
Hi,
First of all I'd like to thank everyone who helped in anyway making this mod.
I have a suggestion: how about we make monika cosplay like other anime girls? I know it might take very long to make the art, I would've done it if only i was able to.
so, can anyone here please make this come true? a cosplay event would be great.
Monika dressing like Makise Kurisu from S;G ? I might give my whole fortune to see it happen!

**Comment by ThePotatoGuy** [comment]
we have a [wishlist] of desired clothing and she is already on there

**Comment by Rakoor** [comment]
Wow, I did not expect that!
someone else looked at monika and said (she should do makise kurisu cosplay)?!
I love the intrnet!
However, I have some photoshop experience.
so, if I wanted to help by making the art, should i just edit the sprites in the mod-assest folder or is there more to it? is there a tutorial I could use to help?
Thanx in advance

**Comment by multimokia** [comment]
See #3174 for a link to official PSD files
