### ISSUE TITLE
[Suggestion] I`m going to draw for a bit

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#5231]
since you added that we are going to write, there should be one for those who draw, and maybe an additional button to ask Monika to do one of the poses in the game to draw

**Comment by Rai99** [comment]
Related, but general: #4462,

**Comment by lunulae** [comment]
The pose idea is super cute, I like that a lot.

**Comment by Rai99** [comment]
That has it's own dupe chain. 
Posing for screenshots/drawings: #2056, #2633, #3630, #4681, #4918.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
