### ISSUE TITLE
miss changing hairstyle function

### ISSUE THREAD

**Issue by ASTAR0T** [Monika-After-Story/MonikaModDev#5232]
Hello everyone, I had to reinstall MAS on my laptop due to some technical issues, so I used original DDLC files and the last available update of MAS, as well as my old RenPy filed connected to DDLC and MAS. Unfortunately, something happened and now function of changing Monika's hairstyle is not available for me anymore.
Also while I was typing it I remembered that before update 10.+ was released I was updating MAS and some errors appeared. I saw them only once and they never appeared again, but if I remember it right, this issue with hairstyle has started from there. Honestly, I have no idea how to fix it. I don't think this is about low affection level, because I can change Monika's clothes, but not a hairstyle or ribbon. So if you have any ideas about my problem, or any possible solution I could use, please, let me know. Thank you!

**Comment by jmwall24** [comment]
What's the current hairstyle she is wearing?

**Comment by multimokia** [comment]
Also, what clothes is she wearing right now?

**Comment by ASTAR0T** [comment]
so, I made couple of screenshots describing how it looks like. If some more info is needed, I can make it. P. S. clothes can be changed, I highlighted it on 2nd screenshot. 
![Monika - 1](https://user-images.githubusercontent.com/37943810/72472784-8bc1e500-37e5-11ea-8494-bb11469dcaac.png)
![Monika - 2](https://user-images.githubusercontent.com/37943810/72472785-8c5a7b80-37e5-11ea-9fa5-a3d0aa4d2ffe.png)

**Comment by Booplicate** [comment]
> I was updating MAS and some errors appeared

Do you remember what Monika was wearing when you got those errors?

**Comment by ASTAR0T** [comment]
> > I was updating MAS and some errors appeared
> 
> Do you remember what Monika was wearing when you got those errors?

If I remember it right, it was that white summer dress which appeared with one of updates. at that moment she had only 4 types of clothes, original school suit, Halloween and Christmas costumes and the white summer dress

**Comment by multimokia** [comment]
Which halloween costumes?

**Comment by ASTAR0T** [comment]
A Witch dress

**Comment by multimokia** [comment]
Have her change into that and then change back out

**Comment by ASTAR0T** [comment]
I will try it now, thank you

**Comment by ASTAR0T** [comment]
Perfect, it worked. How didn't I think about it before... thank you all guys once again, I was afraid that I've got some glitch in persistent data or something...

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
