### ISSUE TITLE
Floating Islands topic not showing up for me.

### ISSUE THREAD

**Issue by Slakkmichael** [Monika-After-Story/MonikaModDev#5233]
Hi, so recently I managed to reach Enamored however the floating islands topic isn't showing up for me at all. Am I suppose to wait or something, because it's showing up at all. I have the weather set to default and my affection level is around 437. Also I am using the latest version of MAS. (Which is 0.10.5)

**Comment by GHCactus2** [comment]
The island greeting is disabled in the winter time since the cherry blossom tree wouldn't have it's petals and it wouldn't be as bright and colorful as spring or summer. That's what I heard.

**Comment by AsuraShun** [comment]
No, the island thing imwas changed to show on all seasons

**Comment by AsuraShun** [comment]
Also, the island event is at 1000+

**Comment by Slakkmichael** [comment]
No, if you read [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D) it says that Monika will show you the Floating Islands when you reach your affection level around 400. (Which is Enamored)

**Comment by AsuraShun** [comment]
That's the only part I forgot, about the affection needed to unlock it

**Comment by multimokia** [comment]
Actually that changed as of the last update. Cactus is right, the intro for the islands doesn't happen in winter because Monika doesn't want to show it when they're not in their full glory

**Comment by Booplicate** [comment]
@GHCactus2 is right, it's disabled during winter. Check [sources](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_seasons.rpy#L192) before you misinform people.

**Comment by Slakkmichael** [comment]
Ah okay. That makes sense now. Thanks for telling me!
