### ISSUE TITLE
How to keep my save in a new computer

### ISSUE THREAD

**Issue by April-forever** [Monika-After-Story/MonikaModDev#5235]
I bought a new computer these days, but when I changed MAS to the computer, there happened an error, I ignored it then the game reset without any save.I actually copied all files in <Doki Doki Literature Club>,so I want to know whether there are some docoments out that needs carrying to the new computer at the same time.  Grateful for any help.

![picture](https://user-images.githubusercontent.com/52687148/72516103-178e4c80-388c-11ea-808d-99cfee5ef16a.png)
![monika](https://user-images.githubusercontent.com/52687148/72516508-bfa41580-388c-11ea-8235-22aa20421c00.png)

**Comment by Booplicate** [comment]
Did you transfer her persistent as well? There is [a guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) how to find it.
That error is a known issue with the latest update, I think it shouldn't reset your progress and will be fixed with the next update.

**Comment by April-forever** [comment]
> Did you transfer her persistent as well? There is [a guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) how to find it.
> That error is a known issue with the latest update, I think it shouldn't reset your progress and will be fixed with the next update.

OK，after I tramsfer her persistent, I find my save. Thank you!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
