### ISSUE TITLE
[Unstable] Update from "Settings->Update version" give up to work due to timeout

### ISSUE THREAD

**Issue by YarikTH** [Monika-After-Story/MonikaModDev#5237]
Update from settings menu worked for me till recently but since about a few weeks it stopped working due to timeout.
I used "unstable" releases for a while and it seems that timeout started to appear in one of the unstable updates in December. Last timestamp of successful update is 10.12.2019 20:50 UTC+3.
Then I updated to v0.10.5 manually in another folder not using a file from the unstable version. But update still don't work due to timeout. But popup about new version (unstable) was shown correctly.

![image](https://user-images.githubusercontent.com/21075945/72575711-5c42d380-38de-11ea-85aa-c28f58eb6253.png)

**Comment by ThePotatoGuy** [comment]
if this is still happening, make another issue. Sometimes timeouts will happen if the server is under heavy load.
