### ISSUE TITLE
Monika cannot realise any gift i am typing

### ISSUE THREAD

**Issue by Panos-77** [Monika-After-Story/MonikaModDev#5239]
When i am trying to give to her a gift for ex. roses.gift or blueshirt.gift she doesn't say anything,since that black screen on the game appeared the gifts haven't worked

**Comment by Booplicate** [comment]
Can you try to gift them again, but this time make a screenshot of your `characters` folder with gifts in it.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
