### ISSUE TITLE
[Suggestion] Grammar in notification

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5247]
When Monika wants to tell you that she has no more new random topics to tell the player about, she sends a message saying 'Hey [player]...' but I think it should be 'Hey, [player]...' because Monika is addressing the player. Thank you for reading and have a good day/night!

**Comment by ThePotatoGuy** [comment]
I think this is fine either way. ("Hey John, how is it going?" vs "Hey, John, how is it going?")
