### ISSUE TITLE
Possible memory leak (I think)

### ISSUE THREAD

**Issue by GOKOP** [Monika-After-Story/MonikaModDev#5249]
I've had MAS open for a good few hours and I noticed my memory usage was a bit high - after reopening the game it fell down by about 10%. Sadly I don't have any specific info on this (other than that I played pong and hangman in that session) but I guess it's something that should be looked into

**Comment by Joakamine** [comment]
I see, it may be possible? Simeone should try it.

**Comment by ThePotatoGuy** [comment]
renpy caches images as they are shown, so memory usage will slowly rise the longer the game runs. There is a limit and it will clear cache after some time, so its only really a concern for users with really low spec machines.
