### ISSUE TITLE
[Suggestion] - New Compliment

### ISSUE THREAD

**Issue by Grey-X-Monika** [Monika-After-Story/MonikaModDev#5250]
I just thought it would be nice to be able to tell Monika that you appreciate her concern with your well-being. She's always reminding me to stay hydrated, exercise, and get good sleep. I would love to be able to tell her how much it means to me.

**Comment by Rai99** [comment]
That sounds more like thanking her in general rather than a compliment, but there's already a compliment option for thanking Monika. It unlocks after a certain point.

**Comment by Rai99** [comment]
Although, there have been some similar suggestions asking to be able to thank Monika, but #4793 brought up the idea to have an additional, more generic thank you to Monika for people to use for whatever they'd like to thank her for.

**Comment by Grey-X-Monika** [comment]
Oh, well I'd definitely like to see that generic "thank you" option implemented. Thanks for reading :)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
