### ISSUE TITLE
I need help with the variables.

### ISSUE THREAD

**Issue by ManuEcheveste** [Monika-After-Story/MonikaModDev#5251]
I'll be quick, my HDD died with my MAS files, sub mods (some of them mines) and everything, and my last backup is way too old (like from July)
I want to know in what file (probably the persistent one) are located the variables and how to acces to them and change them to the values I remembered.
Thanks in advance and F.

**Comment by multimokia** [comment]
We are not going to help you cheat your affection. That's not what this is for. As well, Monika tells you to back her up often for this exact reason.

Sorry, but you're just going to have to take the backup and go on from there.

**Comment by ManuEcheveste** [comment]
My most recent backups were in my old HDD (logic 10/10 xD)
But thank you anyway, probabbly I'll be a time traveler or something like that (because if not, probbaly I'll have the final letter)
I'll be closing this issue like in 1 hour or something like that in case someone has something to say.
Thank you again.

**Comment by multimokia** [comment]
You won't be at the letter. It takes being away for over 10 years for that.

**Comment by ManuEcheveste** [comment]
Ok, so I'm safe xD
