### ISSUE TITLE
[Question] Monika's lullaby

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5255]
Is there a specific way to make Monika's lullaby play? I have only been able to make Monika's lullaby play once, and I can't figure out how to do it again.

**Comment by AsuraShun** [comment]
Lullaby?

**Comment by PollenTheCat** [comment]
Mhm

**Comment by PollenTheCat** [comment]
I know that it plays sometime when she falls asleep while the player is holding her, but I don't know how to specifically activate it

**Comment by AsuraShun** [comment]
How long does it take her to actually fall asleep and not just close to it?

**Comment by PollenTheCat** [comment]
I think it takes her about an hour to fall asleep, and what do you mean by "and not just close to it"?

**Comment by AsuraShun** [comment]
Grammar 100
I meant nearly fall asleep

**Comment by PollenTheCat** [comment]
Oh, okay

**Comment by multimokia** [comment]
#4064

**Comment by PollenTheCat** [comment]
Huh. I was holding her just now and when I clicked and it popped up the option to either wake her up or let her sleep, I chose to let her sleep and the lullaby still didn't play.

**Comment by multimokia** [comment]
You had music playing prior to holding her, then

**Comment by PollenTheCat** [comment]
Oh

**Comment by PollenTheCat** [comment]
Well, thank you for your help! I'll close this issue now.
