### ISSUE TITLE
[suggestion] custom room + mug menu

### ISSUE THREAD

**Issue by Silvery55** [Monika-After-Story/MonikaModDev#5259]
In the Monika Subreddit I seen people make custom rooms and one guy Making custom mugs also but instead of replacing the asset of the mug and classroom I want a menu the can allow the user to change the style of the mug and classroom.

**Comment by multimokia** [comment]
The latter half is already implemented as of #4503. The event is commented out but the label and it's workings are still active. It is possible to add your own backgrounds and add the event for this via submod to use the background changing framework.

As for changing the mug, I'm not sure how much sense that makes. I mean, from Monika's perspective, it doesn't really make sense to basically say `"Hey, I want you to drink from this cup."`, so having a menu for it is kinda strange. Changing the files is probably the better way to go for this bit in my opinion.

**Comment by lunulae** [comment]
A menu for mugs might not be a good fit, but I do like the idea of being able to store multiple mugs which she could randomly select from.

**Comment by softombre** [comment]
yea, having different mugs she randomly chooses from would be nice!!!!

**Comment by ThePotatoGuy** [comment]
### custom rooms
depends on what you are referring to. If its room decoration, then that has already been suggested in #312 and is in development. If its bg changing, then its the issue multi linked.

### different mugs
randomized mugs could work, would need additional mug art and would probably be added via gifting

[closing as probable duplicate and look at later]
