### ISSUE TITLE
Monika closing game before 1 AM

### ISSUE THREAD

**Issue by tw4449** [Monika-After-Story/MonikaModDev#5260]
I'm not sure if the most recent update caused this, but twice in the last three days Monika has commented on me being up too late once it's past midnight, the first time closing the game and most recently saying she'd let it go "just this once." I know that's a normal function for her to have that ability past a certain time, but shouldn't it only happen after 1 AM, since the mod was updated to where she'll still say goodnight up until 1? It seems pointless to me to have the option to keep her open that late if it runs the risk of the game closing itself. Like I said, this never happened until after the last update, so I don't know if I've gotten unlucky with the timing or if that actually changed.

Either way, my point is that the game probably shouldn't do this until after 1 AM.

**Comment by fromulus** [comment]
I'm not sure how that is a problem.
Anytime after midnight _is_ a pretty late time to go to bed, so it'd make even less sense in my opinion to have her stop triggering the sleep concern features before 1AM just because she now says goodnight up until that point.

After all, just because someone goes to bed late doesn't mean you shouldn't tell them goodnight, right ?

**Comment by tw4449** [comment]
The issue is less of realism than it is of consistency and gameplay, as I see it. It seems counterproductive to open the door to letting her say goodnight up until 1 (which greatly helps those like me with weird hours to have extra time with her) while at the same time making it possible for her to abruptly shut the game on you. The cutoff should be consistent; either both at 12, or both at 1.

My secondary point is whether this is something the last update may have affected. Since the update a while back that moved the goodnight cutoff to 1, I have spent most nights with her up until 1 with no issues. But since the last update, the "too late" events have happened twice. This leads me to suspect that the update changed something to this effect, either intentionally or unintentionally. If intentional, I'm curious why it was changed. If unintentional, it's a bug.

**Comment by multimokia** [comment]
#4914 intends to handle the timeconcern issues here.

The current issue is that it's somewhat randomly enforced at the moment since it's a random topic, so sometimes she'll do it two to three nights in a row, other times it may be weeks between the next time she'll bring it up.

**Comment by thekill9714** [comment]
> I'm not sure how that is a problem.
> Anytime after midnight _is_ a pretty late time to go to bed, so it'd make even less sense in my opinion to have her stop triggering the sleep concern features before 1AM just because she now says goodnight up until that point.
> 
> After all, just because someone goes to bed late doesn't mean you shouldn't tell them goodnight, right ?

I never had this happen, but I work graves and get annoyed that she thinks I am up to early/late since I sleep in the day, so this could be very annoying, but apparently they plan to fix these issues.

**Comment by ThePotatoGuy** [comment]
any discussion on this should be on the linked issue.
