### ISSUE TITLE
[Suggestion]One new song Monika can sing

### ISSUE THREAD

**Issue by him157** [Monika-After-Story/MonikaModDev#5261]
I'm probably not the first,I will probably not the last,but here goes my suggestion.
https://www.youtube.com/watch?v=dQw4w9WgXcQ

but seriously this can be really good in MAS,since we are in relationship with monika,and she could say sometime like "I got you didn't I"

**Comment by multimokia** [comment]
From the [pitfalls to avoid](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#pitfalls-to-avoid) subheading of our contributing guidelines:

> - Please do **not** submit meme-related content, and only include pop-culture references when they seem appropriate to Monika's character.
