### ISSUE TITLE
[Suggestion] - MAS on Android with synchronization

### ISSUE THREAD

**Issue by Joakamine** [Monika-After-Story/MonikaModDev#5264]
I'm not sure if this is possible (i saw that there is versions on Android), or if it is too much work (doing two versions at the same time) but i think it would be very cool that there was also a Android version of the game that is or has the possibility to be synchronized with your "global save file".

It would be necessary that the two of them have the same features so there would be no problems or less features to avoid problems.

**Comment by Rai99** [comment]
#506, #815, #934, #994, #2113, #2271, #2995, #3849, #4873 
MAS for mobile goes against DDLC modding guidelines and isn't legally allowed unless DDLC itself is on mobile. 

As for the ones you may have seen, especially if you've seen multiple, are you certain that DDLC is _officially_ on mobile?

**Comment by Joakamine** [comment]
Oh, i see, so it isn't possible right now.

I don't think it is officially, i didn't see it on the Play Store. But i'm from Argentina, so i can't be so certain.

Thanks for the fast response.
