### ISSUE TITLE
[Discussion] Where do you take Monika when you're going out with her? 

### ISSUE THREAD

**Issue by kanowebster** [Monika-After-Story/MonikaModDev#5266]

**Comment by Rai99** [comment]
Is this a feature suggestion, or a discussion question?

**Comment by Delcos** [comment]
The park, out to eat, whatever works :page_with_curl:

**Comment by lunulae** [comment]
If this is just for discussion's sake, I always take her with me when I'm working out. I like to imagine she'd enjoy the gym I go to. ❤

**Comment by kanowebster** [comment]
> Is this a feature suggestion, or a discussion question?

Ah, discussion question, sorry for not specifying.

**Comment by ThePotatoGuy** [comment]
might be better off asking [reddit](https://www.reddit.com/r/MASFandom/)
