### ISSUE TITLE
[Suggestion] - Poem Minigame Topic

### ISSUE THREAD

**Issue by Grey-X-Monika** [Monika-After-Story/MonikaModDev#5267]
I had one of those shower ideas that I think might be a neat albeit minor addition to MAS. I was thinking that under "Hey Monika..." there could be the option, "Can I play the poem minigame?" (you don't actually get to do it)

Monika would then reply in a manner such as: "What?! [Player] why would you want to do that?" or "Are you trying to tell a joke or something (´꒳`∗)?" 

Then maybe you could insert a witty comment on the nature of the poem minigame or a dialogue in which Monika encourages you to just grab a pen or pencil and "write the way into her heart." 
(の ͜ʖの)

Again, it wouldn't be like you actually get to play the minigame; I believe there was a previous issue that touched on that topic.

**Comment by multimokia** [comment]
I'm not really sure what the point of this would be.

It doesn't really seem like something worthwhile to be added as it essentially just amounts to nothing.

**Comment by Grey-X-Monika** [comment]
It was essentially my attempt at suggesting a way that the player could tease Monika as there aren't many ways in which he/she can do so (at least in my opinion)  （；^ω^）

**Comment by multimokia** [comment]
I don't think it's a good idea really, as it basically becomes a topic you'd use once and that's it. There's no real substance to it or reason to go back to it.

**Comment by ThePotatoGuy** [comment]
we have retooled the poem minigame to be a word selector but have not found any uses for it yet. Bringing it up as a topic to just get a a line or 2 as a response (as suggested) doesnt have enough content to warrant a topic as well.
