### ISSUE TITLE
[Suggestion] Tell Monika that she have a great sence of humor

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#5270]
Title pretty much tells everything. I think Monika very funny when she is joking, so I think that a great idea if player being able to say that she have a great sence of humor.

**Comment by WingdingsMaster** [comment]
Well, You do have a point

**Comment by thekill9714** [comment]
I agree, I wanted to say the same to her. I think it also be nice to have more additional compliments as well such as saying I love your fun facts or tips, or complimenting how well read she is or saying you liked the face she just made :D.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
