### ISSUE TITLE
[Suggestion] - a new promise ring that can be swapped in the appearance menu 

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5271]
I could not stop thinking about this today so I feel obligated to post it here
When you give Monika the promise ring she could tell you if you like it or not, and there should be 3 options: Its beautiful, ...its okay..., do you have any others?
The first option should have her thank you and say there was another and could be swapped in the appearance menu. the second option should go the same way but less confident and she should ask the reader if she should try the other one. the last option should have her say Yes, do you dislike this one?its okay to, then have her wear the other ring. Also, If it is at night, Could the ring slightly glow white?
here is a example of the other ring:
https://i.ibb.co/BTtc59B/Queen-Ring.png
(Another Example):
https://i.ibb.co/PNs3Q4c/db8zj4f-a334acff-f158-4aea-af86-2c910d7f59db.jpg
Thank you very much!
           ~WM

**Comment by ThePotatoGuy** [comment]
customizable promise rings are already planned

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
