### ISSUE TITLE
How do you exactly download the sprite previewer?

### ISSUE THREAD

**Issue by AryMishor** [Monika-After-Story/MonikaModDev#5273]
I'm a bit new to GitHub, but how do you download the file to put into the game folder? Just asking.
Thanks in advance!

**Comment by paragonfist** [comment]
Here, mate:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/dev/dev_exp_previewer.rpy
On that link, where it has the buttons "Raw | Blame | History" - right click "Raw" and then "Save link as".

**Comment by AryMishor** [comment]
Thank you!
