### ISSUE TITLE
[Suggestion] Minimized-game optimization

### ISSUE THREAD

**Issue by Joakamine** [Monika-After-Story/MonikaModDev#5276]
I usually leave the game open and do other things in my PC. It would be very nice if when minimized for a little time (1 minute for example) the game would disable some unnecessary things to use less resources. 

In a simplified example fashion: 
```
If ➝ Game minimized for 1 minute ➞
   * Disable background
```

You got any ideas for this? What to disable? When to disable? A better way to do it?
Let's discuss this if possible.

**Comment by multimokia** [comment]
First of all, detecting if minimized sounds like a bit of a cross platform nightmare if not possible with more libs.

Secondly, RenPy already doesn't like to be minimized, causing a few graphical issues for some people who do.

Thirdly, disabling sounds doesn't make sense on minimize. Notifications use a custom sound played by the game and people may want the music playing from MAS to be in the background too.

**Comment by Joakamine** [comment]
> First of all, detecting if minimized sounds like a bit of a cross platform nightmare if not possible with more libs.
Hmm, i think it maybe somewhat easy with Windows, but i'm not sure about other os.

> Secondly, RenPy already doesn't like to be minimized, causing a few graphical issues for some people who do.
Oh, damn. For me it just freezes for a few seconds after i maximize it, this if i left it open minimized for a time. It depends on the drivers, or the renderer, or what?

> Thirdly, disabling sounds doesn't make sense on minimize. Notifications use a custom sound played by the game and people may want the music playing from MAS to be in the background too.
Hmm, yeah, you're right. That should be out of the list.

**Comment by ThePotatoGuy** [comment]
as mentioned, minimization causes issues with renpy so we won't write anything for minimization scenarios.
