### ISSUE TITLE
[Suggestion] - Option to leave to read or read a book with Monika.

### ISSUE THREAD

**Issue by thekill9714** [Monika-After-Story/MonikaModDev#5281]
Alike to the addition of I'm going to go write, I think it be nice to say I am going to go read and have her comment on that, maybe with a reading suggestion or two every now and then. 

Also alike to how she asks you to tell her whats bothering you and the game somewhat pauses expecting you to actually speak out loud your problems, why not have an option to read a book out loud. If that would be to embarrassing it can be treated alike to the Can I hold you topic where she simply acts if she is reading along with the user and make a comment at the end that is generic and could be applied to anything. Such as additional reading or writing advice that after can be brought up on their own under the writing tips topic as special unlocked advice which she just thought about while reading with you making it a little more meaningful.

**Comment by Rai99** [comment]
Reading a book with Monika: #2609, #2898, #3777

Reading idle: #2311, #3896, #4528 

I'm not sure what generic thing Monika could say after any book that would still be meaningful.
