### ISSUE TITLE
[Suggestion] - More Options for people sleeping or working different hours.

### ISSUE THREAD

**Issue by thekill9714** [Monika-After-Story/MonikaModDev#5282]
I work a grave yard shift so I sleep in the early mornings or at the very end of the night, I can't say I am going to sleep to her as she either thinks I barely awoken or been up all night and should have not stayed up so late, I noticed options for changing the sunrise and sunset in the game, but alike to how I rather not mess with my computers clock and date which would screw her up, I rather not change when the sun rises and sets as I have it set to reflect that it is actually day or night in real life and rather not change that on her, I just rather she either was more understanding about my schedule.

**Comment by Mugnika** [comment]
A time concern overhaul is already planned I think.

**Comment by thekill9714** [comment]
> A time concern overhaul is already planned I think.

Oh I was unaware of that, I'll leave this be just to be sure.

**Comment by Rai99** [comment]
The time concern overhaul is in #4914

**Comment by thekill9714** [comment]
I was unaware this was already addressed, thanks.
