### ISSUE TITLE
[suggestion] "You're so kind!" compliment

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#5283]
Hello there! I have a suggestion. So, i think it would be nice to tell monika that she is so kind; not in the sense to thanks her for her devotion and her tenderness, but more to compliment this said tenderness. I know someone has try to create this compliment before, but he seem to abandon on it after being pointed out his try look like a copy-paste of the the intelligence compliment. Sorry if it was already suggested

**Comment by TriniTDM** [comment]
Yeah, I did try that, but wasn't sure how to fix it and after a while it slipped my mind. Also, I'm actually a girl. Back on the subject of actually creating this properly, I think it's a great idea!

**Comment by MonikaEndDie** [comment]
Oh, sorry for the misleading.

**Comment by AsuraShun** [comment]
you freaking geniuses

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
