### ISSUE TITLE
Affection problem

### ISSUE THREAD

**Issue by NoahManson** [Monika-After-Story/MonikaModDev#5286]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4144266/aff_log.txt)

So, I have been playing this recently, and it doesn't seem to update the log. The last date was April 2019, but I'm playing it as of right now and I can't see my current affection. May I know why? Thanks in advance!

**Comment by multimokia** [comment]
I assume you're on mac. The place logs were stored were moved due to many users having file permission issues.

See [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#how-to-view-your-affection) from our FAQ to see how to access it.

**Comment by NoahManson** [comment]
@multimokia Okay, thanks.
