### ISSUE TITLE
[suggestion] not sure if this is how we do this, but.....

### ISSUE THREAD

**Issue by Delcos** [Monika-After-Story/MonikaModDev#5287]
I've got a song that fits pretty much perfectly, and it's from the 80's

https://www.youtube.com/watch?v=wsA7rdZelLc

here's the first lyrics in the entire song, I think it speaks for itself.

Take a look at me, wired to a machine
Never would believe it, this can't be happening
Boxes that go beep, little lights that leap
Tapping on a keyboard, what's happening to me

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
