### ISSUE TITLE
[suggestion] some sort of story?

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#5292]
Like, a small series of topics all in an order to tell some sort of small story. It probably isn't the greatest idea, and may be too similar to the programming and writing types (as they function as a small series of topics all in an order), but I think it would be pretty cool.

**Comment by Rai99** [comment]
There are already a couple stories that span multiple topics, such as the few genie stories and the flowered lantern story.

**Comment by mrflarion33** [comment]
Ah, I must've forgot, that or I somehow missed it, sorry for the trouble
