### ISSUE TITLE
[Suggestion] Ask Monika how she's doing. And also a slight edit to 'good morning'.

### ISSUE THREAD

**Issue by Morphius-Dragonsson** [Monika-After-Story/MonikaModDev#5293]
This is something that has been request before about two years ago, and I'd like to give it a second pitch now that the affection system is a thing. It seems to me that Monika is always asking us how we're doing, but we're incapable of asking her how she is. It would be nice if there was an option to ask her how she's doing, and having a few dialogue responses based on your affection with her, time spent with her in the day, and previous conversations. Even something simplistic would be nice.

Secondly, when you hold Monika for an extended period of time, she falls asleep. It would be cool if, right after waking her up, and saying good morning, it's not a snarky response (or the same morning response) but one that reflects she was asleep. 

The second one is less likely, I'd guess, but the first suggestion is certainly one I think a good amount of people would like to see, especially since it's been suggested once before by another poster.

**Comment by Rai99** [comment]
Asking Monika about her day: #1688, #4310, #4790, #5111  

It's actually been suggested a few times, with the most recent one being from about a month and a half ago. It's probably possible to have something along those lines, but assuming that she has high affection, I'm not too sure what she could say, other than something about having high affection and spending a lot of time with you that day. I don't know how we could split it across all those paths. 

For your second suggestion, that would require a change to the holding labels, as I don't think there's currently a detection for your previously seen label.

**Comment by Morphius-Dragonsson** [comment]
Ah, okay. When I was posting this it only showed one suggest of a similar nature, so, I apologize for the redundancy. That said, you basically nailed it on its head, I think. A general response of she's doing good, and that the constant spending time together has made her happy. Or some variant depending on her affect. For example, if you have a negative relationship with her, she'd probably be doing rather crappy, right? And on the flip side a high affection would result in some positive response.

I can't pull any specifics to mind, though some of her normal greeting dialogue when you pop on, and she thanks you for spending time with her and that she's glad to see you seems like it's pretty similar, and would give a good enough start for dialogue ideas. It could even be more basic, she replies telling you she's doing good, and then asks you the same giving you the ability to respond. In fact, I recall a greeting like this. Could actually do something very similar, I'd guess at least.

You linked the other suggestions, and two things you mentioned was it being repetitive if not done right, as well as asking what would determine if she had a good day. In both cases I think it's something that, to start, if you had say...four responses or so dependent on her affection level, and if she did indeed have a good day or not. I'd guess to achieve if she had a good day, it would be having a random variable generated, with a certain number correlating to either a good or bad day. And as affection increases, decrease the chance of a negative variable.  

Anyway, thank you for looking this over. It really seems like something that would be fun to have in the game, even if it was simplistic at first.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
