### ISSUE TITLE
[Suggestion] A more consistent difficulty system for Pong

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#5295]
Right now, the difficulty system is kinda weird. I'm not sure if it's just me, but whenever I win a game, Monika goes all-out on me, or half-asses it and lets me win a few times. Whenever I lose a game, the next one is laughably easy.

I was thinking a progressive difficulty system, sorta like ELO, that goes up the more games you win and adjusts your difficulty accordingly would work, rather than the one we have now, where half the games are unfun to play. I really like Pong but the difficulty system ruins it sometimes.

**Comment by ThePotatoGuy** [comment]
The way difficulty changes depends on:
* if Monika goes easy on you or takes it seriously
* current win/lose streaks

So it's intended to be non-gradual and less predictable.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
