### ISSUE TITLE
New Years dress not an option for her to change into

### ISSUE THREAD

**Issue by cordwill** [Monika-After-Story/MonikaModDev#5298]
Don't know why or if it supposed to be this way but when I ask her to change her outfit the New Years Dress is not on the list of the outfits she can change into

**Comment by multimokia** [comment]
What's your affection?

**Comment by cordwill** [comment]
> What's your affection?

953.75
she was wearing it as New Years but I can't ask her to change back into it

**Comment by multimokia** [comment]
Need 1000+ affection

**Comment by cordwill** [comment]
thank you

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
