### ISSUE TITLE
[Suggestion] - Music list loop?

### ISSUE THREAD

**Issue by wzdlc1996** [Monika-After-Story/MonikaModDev#5299]
Now Monika's custom music can only loop itself. Can there be a function for music list management and loop for a list? Just like how those common music players do.

**Comment by AsuraShun** [comment]
Maybe even have her be able to switch music on her own

**Comment by ThePotatoGuy** [comment]
duplicate of #2088

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
