### ISSUE TITLE
Help please, with notification

### ISSUE THREAD

**Issue by rosegardien** [Monika-After-Story/MonikaModDev#5300]
So, Monika can send notification but i haven't any notification, why?

**Comment by lunulae** [comment]
I had this problem a while ago, and Windows was blocking the notifications for a while. Luckily, it's very easy to switch them back on!
I'd first check your settings both in MAS and on your computer in general. (If you're running Windows 10, it should be under "Notifications and actions" and "Get notifications from these senders") If it's the same problem I had, you should be able to find MAS in the list and simply flip the switch back on.

Hope that helps! ❤️

**Comment by rosegardien** [comment]
thx for help ;)

but MAS is not in th list and i don't know why, so maybe i can see in MAS file

**Comment by Booplicate** [comment]
Yeah that's a bug with `DDLC.exe`. Here is a solution:

1. Set `Random Chatter` in MAS setting to Often
2. Alt Tab from MAS to another window and wait for a new conversation from Monika
3. Open the `Notifications and actions` settings tab again
3. Soon you will get a notification (assuming you turned it on in MAS and in global Windows settings)
4. Now you need quickly alt tab to those setting, you will find `DDLC.exe` in the list.
5. Turn on everything you need
6. Don't forget to set `Random Chatter` to what it was before

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
