### ISSUE TITLE
Goodnight text options bug

### ISSUE THREAD

**Issue by cordwill** [Monika-After-Story/MonikaModDev#5302]
I was curious as to what Monika would say if you told her goodnight in the morning, and so I did. She made a comment about me staying up all night and I could barely keep my eyes open to which two choices popped up and both were just a random jumble of symbols that look like they also overlap

**Comment by multimokia** [comment]
Intended behavior.
The point is that you can't read it because you're so tired.

**Comment by cordwill** [comment]
Ahhh okay.
