### ISSUE TITLE
[ 🌡️ ACS - Thermos Mug ☕ ]  Cozy  [ Request 💌 ]

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#5305]
<p align="center">
<b>𝒮𝓅𝒾𝓇𝒾𝓉 𝒮𝒶𝑔𝑒</b></br>
</p>

---

![Stable DDLC ( Preview )](https://user-images.githubusercontent.com/43480604/72648384-8927d280-3940-11ea-859e-d90692980ccd.png)

<details>

 <summary>📁 Hub Preview</summary>
<br>

![ OK   Thermos Mug](https://user-images.githubusercontent.com/43480604/74082857-d240e300-4a23-11ea-8452-e91f99922897.png)

</details>

---

```m "I'm not really a fan of cold weather...are you?"```
```m "If I had to choose between too cold and too hot, I would always pick too hot."```
```m "When you're cold, it can actually be painful..."```
```m "Your fingers get numb..."```
```m "And if you wear gloves, you can't use your phone."```
```m "It's so inconvenient!"```
```m "But when it's too hot, it's not that hard to stay cool with a cold drink, or by staying in the shade."```
```m "Although...I do have to admit one thing."```
```m "Cold weather makes for better cuddle weather. Ahaha!"```

<details>
<summary>📁<i>More Warmth...</i></summary>
<br>

<details>
<summary>&emsp;Daydream</summary>

<br>

```m "the two of us reading a book together on a cold winter day, snuggled up under a warm blanket...",```
```m "us having a duet together, with you singing my song while I play the piano...",```
```m "us having a wonderful dinner together...",```
```m "us having a late night on the couch together...",```
```m "you holding my hand while we take a stroll outside on a sunny day...",```

---

```m "the hope I used to have for our future..."```

</details>

<details>
<summary>&emsp;Concerts</summary>

<br>

```m "Do you know any bands or musicians that we should see live, [player]?"```
```m "I would {i}love{/i} to see them if {i}you{/i} like them."```
```m "And if you were to take me,{w=1} then that would truly be a dream come true!"```
```m "But if you're not that interested in concerts..."```
```m "Then we could always snuggle under a blanket and put on a record or CD at home!"```
```m "That would be more than enough for me hehe~"```

</details>

</details>
</details>
</details>
</details>

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>
 <summary>📁Enjoying <i>Winter</i> thus far? ❄️ </summary>
<br>

<details>
 <summary>&emsp;Yes!</summary>

<br>

That's the Spirit!
- &emsp;<i>Snowmen...</i> ⛄️ 
- &emsp;<i>Snow Angels...</i> ❄️ 👼 
- &emsp;<i>Snowball Fights...</i> 
- &emsp;<i>Snow Sports...</i> 🏂 
- &emsp;<i>Ice Skating...</i> ⛸ 
- &emsp;<i>Ice Fishing...</i> 🎣 
- &emsp;<i>Cozy Fireplaces...</i> 🔥

You get it.
There are lots of enjoyable Winter activities!

</details>

<details>
 <summary>&emsp;<i>Southern</i> Hemisphere...</summary>

- &emsp;![Oh Welp](https://user-images.githubusercontent.com/43480604/74082377-e7674300-4a1e-11ea-99b9-d8bb8e426d0d.jpg)

</details>

<details>
 <summary>&emsp;No.</summary>

<br>

Who can blame you?
- &emsp;The risk of fall-related injuries is typically higher.
- &emsp;Cold weather causes muscles to contract, causing tightness throughout the body. Joints get tighter, muscles can lose their range of motion too.
- &emsp;It's easy to feel cooped up whether by choice or not and in some cases, the infamous <i>Cabin Fever</i> has been known to set-in as a result.
- &emsp;If you drive a car you may have to start it earlier as well as deal with any snow or ice build-up!
- &emsp;Home plumbing can run the risk of actually exploding! 💣 
- &emsp;Vegetation, in general, is typically dead- making for seemingly lifeless and gloomy scenery.

So yeah! There are lots of reasons to want to forgo a season altogether as well. ☝️ 

</details>

</details>
</details>
</details>

---

![Stable Sayori (  preview )](https://user-images.githubusercontent.com/43480604/72650736-f0e11c00-3946-11ea-8ead-ab63809423a9.png)

---

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>

 <summary>📁 What is this?</summary>
<br>

- &emsp; It's a <i>Stainless Steel Thermos Mug!<i>

- &emsp; Included within the `Attachments` portion of this issue is an [ OK boomer ] alteration of the label for the mug.

- &emsp; Among the files included in this issue's _attachments_ is the PSD format for the sprite(s).
>Anyone is welcome to attempt to polish, rework or edit the sprite(s) for the re-purposing for MAS potential use and the effort is appreciated. Thanks! ☝️ 

</details>

---

<details>

 <summary>📁 How can I use this?</summary>
<br>

- &emsp; You can't. Whatever it is it's stuck in lukewarm Limbo.

</details>

---

<details>

 <summary>📁 How are you by the way?</summary>
<br>

- &emsp; <i>Snug as a Bug in a Rug.</i>
> Thanks for asking! 💙 

</details>
</details>
</details>

---

<p align="center">
<b>[ General ]</b>
</p>

⮞ Did you know?

- &emsp;The average snowflake falls at about 3 mph.
- &emsp;While it seems counterintuitive, Earth is actually closest to the sun in December.
- &emsp;The Winter Solstice marks the longest night and the shortest day in the Northern Hemisphere.
- &emsp;Chionophobia is the persistent fear of snow, especially becoming trapped by snow. The term is derived from the Greek words chion and phobos, meaning “snow” and “fear,” respectively.
- &emsp;A New Zealand insect called the Weta freezes completely solid when temperatures drop during the winter. However, when temperatures warm back up, the insect unfreezes, thaws, and resumes its activities.
- &emsp;Sunsets are typically prettier in the winter. Cold, non-humid air is clearer than warm summer air, which allows the colors of the sun to shine through more clearly.

</details>
</details>
</details>

---

![Stable Yuri ( Preview )](https://user-images.githubusercontent.com/43480604/70763454-bff34300-1d19-11ea-8b6b-c818595dabe9.png)

<details>

 <summary>📁 Nexus Preview </summary>
<br>

![ OK Boomer   Thermos Mug](https://user-images.githubusercontent.com/43480604/74083479-2e0e6a80-4a2a-11ea-8c93-2c11e742c94a.png)

</details>

---

⮞ If you're warm on browsing `GitHub` through Light 💡 - Don't turn a cold shoulder to the Dark? 🕶  
⤷ [Stylish: Custom web page themes](https://userstyles.org/styles/browse?search_terms=github&type=false)
> Dark looks so much better here. 👌
>> Only looking out for your _Vision_! 👁‍🗨

---

Thermos Mugs
---

**General**

- &emsp;A mug is a type of cup typically used for drinking hot beverages, such as coffee, hot chocolate, soup, or tea. Mugs usually have handles and hold a larger amount of fluid than other types of cups. Typically, a mug holds approximately 8-12 US fluid ounces (350 ml) of liquid. A mug is a less formal style of drink container and is not usually used in formal place settings, where a teacup or coffee cup is preferred.

<details>
<summary>📁<b>I'm curious...</b></summary>
<br>

**Travel Mugs**

- &emsp;Travel mugs (introduced in the 1980s) generally employ thermal insulation properties for transporting hot or cold liquids. Similar to a vacuum flask, a travel mug is usually well-insulated and completely enclosed to prevent spillage or leaking, but will generally have an opening in the cover through which the contents can be consumed during transportation without spillage. As the primary mechanism by which hot (not warm) beverages lose heat is evaporation a lid, even a thin plastic one as used on disposable coffee cups which conducts heat quite quickly, also serves a vital role in keeping the drink hot. 

- &emsp;Mugs with inner and outer walls, but not vacuum treated, are generally called double wall mugs. Usually stainless steel will be used for the inner wall while the outer wall can be stainless steel, plastic, or even embedded with other materials. 

<details>
<summary>📁<b>Keep it coming...</b></summary>
<br>

**Amusement Mugs**

- &emsp; The whistle mug or hubblebubble is an amusement mug. It has a hollow handle which can be blown through the mug like a whistle. With an empty mug, only one note is emitted, whereas a filled mug produces melodious trills and warblings.

- &emsp;A puzzle mug is a mug which has some trick preventing normal operation. One example is a mug with multiple holes in the rim, making it impossible to drink from it in the normal way. Although it is tempting to grasp the body of the mug covering the visible holes and drink the liquid in the usual manner, this would pour the liquid through hidden perforations near the mug's top. The solution is to cover the holes in the rim with hands, but to drink not through the top, but through a "secret" hole in the hollow handle.

A puzzle mug called fuddling cups consists of three mugs connected through their walls and handles. The inner holes in the mugs walls are designed in such a way that the mugs must be emptied in a unique sequence, or they will drain.

**Decorative Mugs**

- &emsp;As a ubiquitous desktop item, the mug is often used as an object of art or advertisement; some mugs are rather decorations than drinking vessels. Carving had been traditionally applied to mugs in ancient times. Deforming a mug into an unusual shape is sometimes used. However, the most popular decoration technique nowadays is printing on mugs, which is usually performed as follows: Ceramic powder is mixed with dyes of the chosen color and a plasticizer. Then it is printed on a gelatin-coated paper using a traditional screen-printing technique, which applies the mixture through a fine woven mesh, which is stretched on a frame and has a mask of the desired shape. This technique produces a thin homogeneous coating; however, if smoothness is not required, the ceramic mixture is painted directly with a brush. Another, more complex alternative is to coat the paper with a photographic emulsion, photoprint the image and then cure the emulsion with ultraviolet light.

<details>
<summary>📁<b>Got a Link?</b></summary>
<br>

👉 [Here!](https://en.wikipedia.org/wiki/Mug) 👈 

</details>
</details>
</details>

<details>
<summary>📁<b>Comfy Quotes...</b></summary>
<br>

- &emsp;"In the winter she curls up around a good book and dreams away the cold."
― Ben Aaronovitch, Broken Homes

- &emsp;“Some days you get up and you already know that things aren't going to go well. They're the type of days when you should just give in, put your pajamas back on, make some hot chocolate and read comic books in bed with the covers up until the world looks more encouraging. Of course, they never let you do that.”
― Bill Watterson, There's Treasure Everywhere 

- &emsp;“I like to hear a storm at night. It is so cosy to snuggle down among the blankets and feel that it can't get at you.”
― L.M. Montgomery 

- &emsp;“She liked this. Liked the closeness. With lover’s she’d taken in the past, things had been short and sweet. She certainly hadn’t stuck about to snuggle in case they started to get ideas, not after the first time. Killing a guy you’d fxcked was one thing, but to kill one you’d snuggled with damn near broke a girl’s heart”
― Mina Carter, Tamed by the Mistress 

- &emsp;“Sometimes happiness quietly curls up in your heart just to snuggle.”
― Richelle E. Goodrich, Being Bold 

- &emsp;“I will not play at tug o' war.
I'd rather play at hug o' war,
Where everyone hugs
Instead of tugs,
Where everyone giggles
And rolls on the rug,
Where everyone kisses,
And everyone grins,
And everyone cuddles,
And everyone wins.”
― Shel Silverstein, Where the Sidewalk Ends 

- &emsp;“How long has it been since you and me? Hugs and kisses. Blankets and snuggles. Our sparks smoldering without a fireplace. Losing time is not losing you. It strengthens my yearning for you.” 
― FIDELIS O MKPARU, 2019

</details>

---

![Stable Natsuki ( Preview )](https://user-images.githubusercontent.com/43480604/70763334-56733480-1d19-11ea-8958-b83b7be0b538.png)

---

<details>
<summary>📁<b>References</b></summary>
<br>

![Ok Boomer](https://user-images.githubusercontent.com/43480604/74083938-1d142800-4a2f-11ea-96c2-ddbe27b36a92.PNG)
#3174 
#3573 
#4504 

</details>

<details>
<summary>📁<b>Credentials</b></summary>
<br>

- @jmwall24  / [John W](https://github.com/jmwall24) → For requesting the production of this ACS!
>I can never design enough of these!

</details>

<details>

<summary>📁<b>📎 Attachments 📎</b></summary>
<br>

⯈ [ 🌡️ Thermos Mug ☕ ](https://github.com/Monika-After-Story/MonikaModDev/files/4174090/Thermos.Mug.Export.zip) ⯇

</details>

</details>
</details>
</details>

---

Meme of the Theme!
---
`Hey, Monika...` > `Can I hold you?`

<div align="center">

![Meme of Theme](https://user-images.githubusercontent.com/43480604/74084037-513c1880-4a30-11ea-9df9-642024303dd8.jpg)

</div>

---

```
from subprocess import call
```
>def play_wave_file([j'san. - cozy winter.wav):](https://youtu.be/cKSxbgGoXUo)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by AsuraShun** [comment]
Incredible like always

**Comment by Professor-JMO** [comment]
Thank you!

**Comment by multimokia** [comment]
Implementing into consumables

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
