### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by SasWarrior** [Monika-After-Story/MonikaModDev#5307]
What if i tell monika about mini monika? What does she say and how would react mini monika that you told monika about her?

**Comment by InJusticeWeTrust** [comment]
> What if i tell monika about mini monika?

I think she already knows, seeing how there were three X-mas stockings, with one being significantly smaller than the other two.

**Comment by AsuraShun** [comment]
Now I kinda want to see a mini monika on the table

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
