### ISSUE TITLE
Problems with the latest spritepack

### ISSUE THREAD

**Issue by JoSnake** [Monika-After-Story/MonikaModDev#5312]
Monika can't seem to recognize the twin ribbons and the S-type ribbons that were recently released with the last update. I've installed the mod_assets archives in the correct way, as I've been doing for the last 4 months, but when I try to give them as gifts in the 'characters' folder, Monika recognizes the file as a gift in MAS, but then she says she can't recognize the content of the gift file. I tried replacing them in the 'mod_assets' folder, but nothing changed. It's the first time it happened to me since I installed this mod, so I'm not sure what to do.

They're described as 'Twin Ribbons by Orcaramelo' and 'S-Type Ribbons by Velius94' in the release page.

[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4180675/spj.txt)

**Comment by Booplicate** [comment]
In your logs I don't see those sprite packs. I think you misplaced them. Can you send a screenshot of this folder: `/game/mod_assets/monika/j`
Btw, the next time you will send logs, please say goodbye to Monika first.

**Comment by JoSnake** [comment]
Oh, sorry about the log :v 

Here you go

![Screenshot_1](https://user-images.githubusercontent.com/60880213/74155945-25699000-4bf4-11ea-9510-11c0c47ca356.png)
![Screenshot_2](https://user-images.githubusercontent.com/60880213/74155946-269abd00-4bf4-11ea-9e67-d6231dbf7c8f.png)

**Comment by Booplicate** [comment]
Aha, maybe you installed those while the game was open? Try to open the game and gift them again.

**Comment by JoSnake** [comment]
Oh god, I feel so dumb right now, I forgot that the first time I tried to add a spritepack, I put it on the wrong folder, but I completely forgot that I've been putting those sprite files files on both folders, the one that's in the 'game' folder and the other one that I've created. I'll delete this 2nd folder :v

Sorry for the trouble, and thank you for your help, things are back to normal now :D
