### ISSUE TITLE
Which files was it that Monika wanted me to move from Steam to elsewhere?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5316]
I can't remember if it was the whole folder ..

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
