### ISSUE TITLE
[Suggestion] - Housespouse Topic(Player

### ISSUE THREAD

**Issue by pab106** [Monika-After-Story/MonikaModDev#5317]
I would like to inquire about the possibility of a housespouse topic; which would allow the player to ask Monika about them becoming a Housespouse.

**Comment by multimokia** [comment]
This already exists, `Hey, [m_name]... > Monika > Would you be my housewife?`

**Comment by pab106** [comment]
It's about the player becoming Monika's housespouse.

**Comment by multimokia** [comment]
Not sure it's too good of an idea, given the point of the career topic, which has Monika thinking that there's not much point in thinking about that now. Since this would directly make her think about it, it seems kinda out of place.

**Comment by pab106** [comment]
While I do understand your reasoning, could the question not be phrased in a way that includes financial viability as a condition in this hypothetical?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
