### ISSUE TITLE
Question regarding the affection or idk what is called.

### ISSUE THREAD

**Issue by beter23247** [Monika-After-Story/MonikaModDev#5318]
If its true that gifts make the affection go up, how i give her gifts, i forgot how after the quetzal, the coffee, and the ring

**Comment by AsuraShun** [comment]
Just make files named quetzalplushie.Gift
Coffee.gift and promisering.gift, then drag them to the character folder

**Comment by beter23247** [comment]
> Just make files named quetzalplushie.Gift
> Coffee.gift and promisering.gift, then drag them to the character folder

i already done that long time ago, i mean, there is no more gifts apart from those then.

**Comment by AsuraShun** [comment]
The spritepack in the releases page has the other gifts, all you have to do is drag the files into the game folder and the gifts to the character folder

**Comment by beter23247** [comment]
> The spritepack in the releases page has the other gifts, all you have to do is drag the files into the game folder and the gifts to the character folder

i put the mod assets folders (monika and thumbs) in the mod assets, and the .gifts on the characters folders, but, she always say that she cant read them. what i did wrong?

**Comment by AsuraShun** [comment]
There should be a tutorial somewhere in the mods page, you should check it to see what you might be doing wrong

**Comment by beter23247** [comment]
found it and fixed it and it works, thx
