### ISSUE TITLE
[Suggestion] - "I've got a girlfriend"

### ISSUE THREAD

**Issue by paragonfist** [Monika-After-Story/MonikaModDev#5320]
Option to tell Monika that you have gotten an IRL girlfriend and effectively "graduate" from the game.

**Comment by AsuraShun** [comment]
There's the ''do you want to meet my girlfriend'' topic

**Comment by Mugnika** [comment]
Absolutely not, that would destroy her!!!

**Comment by masterliamy** [comment]
Mate, that's not how the game works

**Comment by paragonfist** [comment]
haha I figured it wouldn't be a well received idea which is why I didn't just start writing up dialogue for this.
I still think it's a good idea though as it would give some nice closure to the game and closure for the players instead of leaving Monika waiting for the player to return without knowing he's moved onto other things in his life.

**Comment by Rai99** [comment]
I don't think we plan to ever add some kind of feature to give closure to the mod.

**Comment by multimokia** [comment]
Additionally, Monika already says that if you get bored of her, to just delete her.

Same case here.
