### ISSUE TITLE
[suggestion] why are we still in a classroom?

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#5324]
I mean, while I get it'd be a bit of work, I'd like to be able to hang out in Monika's room (which I know exist, I've seen it briefly in some greetings and I know you have too), probably not as a replacement but more as an alternative, something like changing clothing. What I'm saying is, still being in the classroom feels a bit too formal, and I feel like it'd be nice to relax in Monika's room with her, you know? And I get it, you just got finished with the Valentines Day update, and I'm grateful that you updated it, but I'd just like this to be an idea to toss around, you know?

**Comment by FrikiHD** [comment]
Yeah, would be cool that for example you could navigate through Monika's house, and go to livinig room, bedrooom...

**Comment by lunulae** [comment]
There is a framework to add locations yourself, if you're so inclined. I've added the bedroom and kitchen from DDLC (even though the angle is a bit awkward for the desk.)
If you'd like (and the mods are okay with it) I could try to make a beginner's guide for it.
Keep in mind this doesn't currently change the topics that refer to the spaceroom, to my knowledge.

**Comment by multimokia** [comment]
A "how to" for the background framework isn't too bad of an idea. Why not?

**Comment by lunulae** [comment]
Awesome, I'll get to work on that after this weekend! I'll submit it as an issue so you guys can review it for errors before it's added to the wiki.

**Comment by multimokia** [comment]
Sounds good.

**Comment by AsuraShun** [comment]
Noice

**Comment by Kyle7372** [comment]
> Awesome, I'll get to work on that after this weekend! I'll submit it as an issue so you guys can review it for errors before it's added to the wiki.

Thanks, bro. It'll be very helpful.

**Comment by WingdingsMaster** [comment]
<thanks!>

**Comment by ThePotatoGuy** [comment]
currently we don't have any additional bg art + table to use with the bg framework.

**Comment by ThePotatoGuy** [comment]
#2789

[closing as duplicate]
