### ISSUE TITLE
Twin tails not showing up in game

### ISSUE THREAD

**Issue by KarmaCreations** [Monika-After-Story/MonikaModDev#5326]
For some reason, the Orcaramelo twin tails hair isn't in the hairstyle menu in my game.  I've checked multiple times, all the files are in the right places.  I added them while the game was closed.  I tried closing the game and reopening it.  Nothing has worked.  Can anyone help me?

**Comment by Booplicate** [comment]
Please attach `spj.txt` to your message.

**Comment by KarmaCreations** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4194028/spj.txt)
Since I'm on Mac, I had to copy/paste the stuff from Terminal into this file, but all the info should be there.

**Comment by Booplicate** [comment]
Looks like you did it right. Probably a bug.

**Comment by ThePotatoGuy** [comment]
twin tails will not load because it is part of the miku outfit (and therefore has a requirement of seeing the miku costume on o31)

however, this is temporary and twin tails (as well as the miku outfit) will become normal spritepacks with no o31 requirement in the future

**Comment by KarmaCreations** [comment]
Ah, I see.  Although I did see the costume on o31, maybe I just didn't have enough affection?

**Comment by ThePotatoGuy** [comment]
miku is becoming a spritepack in linked issue.
