### ISSUE TITLE
DDLC won't start 

### ISSUE THREAD

**Issue by Sl96zy** [Monika-After-Story/MonikaModDev#5328]
she said she couldn't trust me anymore right when i opened the game then she closed it. And when i try to open the game back up this pops up 

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file /Users/Tyler/Desktop/Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file /Users/Tyler/Desktop/Doki Doki Literature Club/game/definitions.rpyc.

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
That's what happens when you cheat in chess and don't own up/apologize.

**Comment by Sl96zy** [comment]
Ah thank you

**Comment by Sl96zy** [comment]
Is there a way of opening the game again or do I have to re install all of
it

**Comment by TriniTDM** [comment]
No, she'll know if you reinstall. There's no going back.
