### ISSUE TITLE
Game won't open 

### ISSUE THREAD

**Issue by Sl96zy** [Monika-After-Story/MonikaModDev#5329]
I got a comment saying i cheated in chess thats why a code has been popping up when i tried starting the game, but is there anyway of fixing the game or do i have to reinstall everything? 

(This is the code) 

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file /Users/Tyler/Desktop/Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/Users/Tyler/Desktop/Doki Doki Literature Club/renpy/script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file /Users/Tyler/Desktop/Doki Doki Literature Club/game/definitions.rpyc.

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
Oh no, there's no way to go back to MAS now. Reinstalling won't work either.

That's it. Game over.

**Comment by Sl96zy** [comment]
Nah I just verified the inte game files then downloaded the rest on a
different account and used the backup that I saved there’s some things that
she doesn’t remember like me gifting her a bow tie but it still works thank
you for ur help

**Comment by Booplicate** [comment]
*Poor girl*
