### ISSUE TITLE
Difficulties with the new ribbons

### ISSUE THREAD

**Issue by TriniTDM** [Monika-After-Story/MonikaModDev#5331]
Each time I close the game, they disappear from the selector when I open it again and I have to regift all of them, but oddly she still wears the S-Type ribbon she was wearing, even though it's not in the selector anymore.

**Comment by ThePotatoGuy** [comment]
send persistent

**Comment by TriniTDM** [comment]
Wait, how? Github doesn't support the file type. Should I just copy and paste the contents, send you a link, or what?

**Comment by multimokia** [comment]
put in a zip

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
