### ISSUE TITLE
Unable to take Monika somewhere

### ISSUE THREAD

**Issue by LilianReaper** [Monika-After-Story/MonikaModDev#5338]
I'm dumb and dunno what is wrong nor how to fix my files so i can take monika somewhere. Each attempt has given back the resulting response of It seems like I'm having difficulties turning myself into a file. I run the nonsteam version of the game for windows. Most current version. Help is greatly appreciated.

**Comment by Booplicate** [comment]
Iirc it should be logged in `mas_log.txt`. Can you upload it here?

**Comment by LilianReaper** [comment]
Okay, that log is corrupted... isn't that a problem?

**Comment by LilianReaper** [comment]
just told me the file is empty

**Comment by Booplicate** [comment]
Where is your game folder located? Is it like in an archive or some kind of a system folder? Can you give the full filepath?

**Comment by LilianReaper** [comment]
it won't let me upload the zip file saying it's too big. I can upload the contents of each folder if that works for you

**Comment by LilianReaper** [comment]
actually... i know a way to reduce the file size

**Comment by Booplicate** [comment]
👀 No need in the whole folder. Just need to know the path. You can open the game folder and make a screenshot so we can see where it is.
Like this is where I have my game folder.
![Unknown](https://user-images.githubusercontent.com/53382877/74565852-3400d000-4f83-11ea-9adf-2fb9e59e553f.png)

**Comment by LilianReaper** [comment]
oh...okay

**Comment by LilianReaper** [comment]
i have it located off of desktop\DDLC - ModTest_Success and then for the zip file winrar opens it in it's own window

**Comment by LilianReaper** [comment]
Give me a second i apologise for the delay, i'm stupid.

**Comment by LilianReaper** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/61065552/74566942-a9987c00-4f42-11ea-9f2b-7012ed0cf6e4.png)

**Comment by Booplicate** [comment]
Yeah, don't launch anything from archives. You need to extract the game somewhere. For example make a folder on you desktop and extract it there.

**Comment by multimokia** [comment]
Where do you run MAS from?

**Comment by LilianReaper** [comment]
Windows.
I have the file in a folder on the desktop already... and the i placed the zip file in the folder afterwards after first installing the mod. Opened up the zip, winrar did its thing and opened it's own window and then i tranferred the needed mod files into the game folder.

**Comment by LilianReaper** [comment]
okay. I went ahead and extracted the files to a new folder on my desktop

**Comment by LilianReaper** [comment]
It fixed the problem...I am pretty dumb... Okay thank you for the help.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
