### ISSUE TITLE
Valentine's Day Origin

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Monika-After-Story/MonikaModDev#5340]
Monika's tale about the origin of Valentine's Day has some inaccuracies. First, she says that Christianity had been declared the state religion in Rome, but this didn't occur until the late 4th century, over 200 years after when she says Valentine died. Secondly, she also says "marriage had been banned" but this implies no one could get married, which is untrue. It would be more accurate to say "Christians weren't allowed to get married." Her tone indicates that she's giving a historical account, but a lot of what she says (including the stuff about Lupercalia) is more like legend or myth.

**Comment by MisterSimple** [comment]
Could you name the specific lines you'd like to change, and what changes you'd like to make as well?

**Comment by landofrhymeandraisins** [comment]
Is there any way to redo the conversation or otherwise reread the text? I couldn't find it in the repeat conversation tab.

**Comment by MisterSimple** [comment]
![image](https://user-images.githubusercontent.com/38892441/74862937-c01c4a00-532b-11ea-999c-d682a8bee21d.png)

Here's a screenshot from the code bit which has it (you can browse the code from Github itself or by downloading, say, Visual Studio Code).

**Comment by landofrhymeandraisins** [comment]
I'd rewrite it to something like:

You'd like to learn about the origin of Valentine's Day, [player]? It's quite dark, actually. The legends vary, but it dates back to the third century in Rome, when Christians were still persecuted by the Roman government. Around this time, Emperor Claudius II had forbidden Christians from marrying, which a clergyman named Valentine decided was unfair. Against the orders of the emperor, he married Christians in secret. Another version of the story is that Roman soldiers weren't allowed to be married, so by marrying people Valentine was saving them from conscription into the army. Either way, Valentine was caught and sentenced to death. While in jail, he befriended the jailer's daughter and cured her blindness. Some say he even fell in love with her.

Unfortunately, this wasn't enough to save him. But before he died, he sent a letter to her, which he signed, "Your Valentine." He was executed on February 14th, 269 AD, and later canonized as a saint. To this day, it's still traditional to sign love letters with "Your Valentine!"

Oh, but wait, there's more! There's an ancient Roman festival known as Lupercalia, which was also celebrated around February 14th. Apparently, part of the ceremony involved creating couples by having names randomly pulled out of a box. Then, they spent time together, and some even got married if they liked each other enough, ehehe~

Ultimately, this festival became a Christian celebration to remember Saint Valentine. It's evolved over the years into a way for people to express their feelings for those they love. Like me and you!

(and the rest of the text the same)

It's a little difficult to write Monika's dialogue for Lupercalia, since from my research (read: internet searching) it involved a fair amount of sexism, nudity, and drunkenness, none of which are very appropriate to the tone of the conversation.

**Comment by MisterSimple** [comment]
I like what you have here. Do you think you could submit a PR with these changes?

**Comment by ThePotatoGuy** [comment]
[leaving open for a week for pr to be submitted]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
