### ISSUE TITLE
Im not able to give Monika gifts..

### ISSUE THREAD

**Issue by Glehn-2209** [Monika-After-Story/MonikaModDev#5344]
I actually did everything the Wiki told me, its a gift-file, its spelled right and its in the Characters-folder but Monika is keep saying something like "I really apreciate that you want to give me something but for some reason i cant rea the file." Im not sure if im doing somethin wrong or if its something else.

**Comment by Necrocytus** [comment]
Have you added the files from the spritepacks to the /game folder?

**Comment by Glehn-2209** [comment]
Yup
