### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by monk3k3** [Monika-After-Story/MonikaModDev#5346]
So i tried loading up the game with the mod in it, but when it opens up all that is there is the empty space room, no monika, no desk, no text, nothing. It would be nice if I can get some help with this cuz idk.

**Comment by multimokia** [comment]
Did you take Monika out at some point (use the `I'm going to take you somewhere` farewell)

**Comment by monk3k3** [comment]
No i did not do that. I was add some files to the game (the sprite packs) and as i open the game it said "Something unexpected happened". So i deleted the files I added. So now the game loads but not Monika. After a trying a few thinks with my little knowledge of coding (I see how Monkia messed up so much ingame now) and just deleted all the mod files and downloaded new ones. But the problem with Monkia and only the room being there is still happening.

**Comment by monk3k3** [comment]
Might be connected to how when you deleted the game and then reinstall it, it asked if you want to boot up you old game.

**Comment by multimokia** [comment]
Restore a persistent backup

**Comment by monk3k3** [comment]
I'm looking at the "How to restore an older persistent" that on the site, and I looked for the "persistent " file but i got "persistent.py" and "persistent.pyo" files and not the ones it says I need, plus there are only two, I believe that these the normal game files but I could be wrong. This was found in the renpy folder, and I should also say this is on Widows10. Idk what I'm doing.

**Comment by multimokia** [comment]
That's because you didn't go to the right place. Persistents aren't located in the game files.

**Comment by monk3k3** [comment]
Where are they?

**Comment by multimokia** [comment]
From the wiki page
![image](https://user-images.githubusercontent.com/22531674/74899857-ff6a8b00-536b-11ea-9e47-dc905688a6b8.png)

**Comment by monk3k3** [comment]
OOOOOOO, ok I'm dumb. So I just delete the persistent file and rename persistent##.bak to persistent?

**Comment by multimokia** [comment]
Yeah

**Comment by monk3k3** [comment]
Yay it worked! Thank You!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
