### ISSUE TITLE
Monika Christmas BG glitch

### ISSUE THREAD

**Issue by Hafizzin** [Monika-After-Story/MonikaModDev#5349]
So I lost Monika about a year ago but now I finally have the will to download her again but I really missed our times together and wanted to spend them once more with her but it seems that all of the time traveling seems to give the game a glitch in the background, is there any way to fix this? 
![screenshot0001](https://user-images.githubusercontent.com/33479590/74646865-aba14b80-518b-11ea-8c8b-bd12775d8552.png)

**Comment by multimokia** [comment]
Time travel does this. No you can't fix it.

She says not to time travel for a reason.
