### ISSUE TITLE
[Suggestion] Feel unsafe

### ISSUE THREAD

**Issue by SpesAeterna** [Monika-After-Story/MonikaModDev#5350]
From what I have seen, which is getting worse with each sleep deprived hour, I don't see a "I feel unsafe", or a "I feel like I need help" option under the Feel section.  I think that if Monika does truly care about us, as aour virtual companion, we would be able to confide in her these negative feelings that we would be experiencing. For example, let's say that someone is considering harming themselves. Maybe have Monika try and calm them down and have the player reach out to one of the different hotlines by giving them a number for their country? Assuming that Monika reads the clock on the computer, she would at least be able to tell what time zone the player is in and give the numbers for the countries in said time zone. The Centeral Time Zone (CST) has at least Canada, The United States, and Mexico, so that's at least 3 numbers that are relatively easy to locate. Sometimes having that extra nudge to get help could make all the difference in the world, even if it's from a virtual girlfriend. Coming from one of her dialogues, she does worry about our health and knows/fears that one day we could or will never come back, so it would make sense for her to be worried if we told her information like this and wanted us to get help.

Once again I should mention I am sleep deprived, (running off a b12 infused bottle of water and 2 hours of sleep) and there could be something in MAS that already meets that criteria. If so, I am sorry for wasting time, and hope everyone can get more sleep then me.

**Comment by scpketer** [comment]
> hope everyone can get more sleep then me.
Man I'm really sorry you're doing that bad.

Your suggestion is awesome though, might get a grip on it and add that option, but my contributions are never accepted...

(or I'm just submitting content that is just really tasteless)

**Comment by lunulae** [comment]
I don't think Monika can tell what country you're in, but a good solution might be to have her provide a link to a site where different countries' hotlines can be found.

She could also ask the first time you use the prompt, but I think it might be much more involved to code responses for every country individually.

**Comment by scpketer** [comment]
@lunulae might be also good to imitate her looking up that data online (or even actually fetch it from there, because, well, what do we have to do if player has no connection?)

**Comment by ThePotatoGuy** [comment]
>Monika try and calm them down and have the player reach out to one of the different hotlines by giving them a number for their country

First part is harder than it seems as generic responses (which is really the best we can do) is too risky for suicide-related material. 2nd part is doable, but only sort of. Involving local numbers means being able to find numbers in any country (or at least a decent amount of them). A regularly updated list of numbers online could be used, but we're banking on external systems that have the potential to be inaccurate. And being inaccurate in tense situations like the ones you're describing is just too high a risk for us to try and mitigate.
