### ISSUE TITLE
[Suggestion] - I'm feeling Tired

### ISSUE THREAD

**Issue by CookieSpoon69** [Monika-After-Story/MonikaModDev#5351]
It's a small thing but since Monika will react to you staying up all night when you tell her you're going to bed after 0500, I wish that if you tell her you're feeling tired after 0500 she had a unique thing to say, rather than if you woke up that early and told her you were tired. It's something my insomnia and I have noticed for a while and figured we should submit a suggestion.

Either way thank you guys for your hard work, it means the world to me.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
