### ISSUE TITLE
i did a thing

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#5352]
I hit a button while looking away from the screen, then looked over at the screen and saw "this topic has been flagged for removal"???? I didn't mean to hit that, and would like to know if there's a way to undo that, also whatever button I hit to bring that up in the first place, if you know which one that was

**Comment by multimokia** [comment]
You pressed `x` mid topic. This will derandom the topic as it tells Monika you don't really want to talk about it.

If you're still mid topic, press x again. If not, there's a new option in `Hey [m_name]... > You`

**Comment by mrflarion33** [comment]
thank you for the help
