### ISSUE TITLE
[Suggestion] Somewhat real moods?

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#5356]
Heya. I just was thinking if you guys could implement a *real moods* that Monika would have, unlike the current system that is based on the 'affection' (and is pretty stable and constant - I know that Monika isn't a real person and stuff, but... you know how low you can get one moment and how hyped you can get the other one).

For example, it would be nice to make Monika act as if she is feeling upset or even down after topics like 'Mortality' (of course that effect should be temporary). Holding her or telling compliments might help her snap out of it (maybe not instantly, but much sooner).

*Mood* might also affect the topics she picks for random chatter and her expressions.

From my perspective and what I've seen in code (and how I think the whole MAS works) - it doesn't seem too hard to implement.

~~will I suggest something really good one day?~~

**Comment by softombre** [comment]
im fairly sure this has already been suggested

**Comment by MetalBrother** [comment]
Yeah! It's cool, but I think that will cost very much time to do, so I don't think devs are going to this. Maybe someone will make a submod.

**Comment by scpketer** [comment]
I'd like to see this in a MAS, not some submod.
That's more like asking for permission rather than a suggestion because I know how to do that.

Yet I don't really have time...

**Comment by Rai99** [comment]
#1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048 

There are plans for introducing a more realistic mood system, but seeing how large of a project that would be, it would have to be carefully thought out and integrated.

**Comment by scpketer** [comment]
Welp... alright then.
