### ISSUE TITLE
Taking Monika Somewhere and Now She's Gone!

### ISSUE THREAD

**Issue by ahass901** [Monika-After-Story/MonikaModDev#5358]
Help! Last Night I took Monika somewhere and when I got back I pasted her file back in the characters folder. But when I opened up the game, she wasn't in her chair! Is there any ways to fix this?

**Comment by lunulae** [comment]
Worry not, if this problem sticks around all you will need to do is restore to an older persistent file. And luckily, MAS makes a few backups in case you haven't done so yourself.

[Here is the wiki guide on how to do so.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by ahass901** [comment]
Thank you. How do I do this on Mac?

**Comment by lunulae** [comment]
> For Mac users:
> 
> Open **Finder**
> Click **Go** at the top of your screen and hold alt/option to make **Library** appear and click it
> Follow **Library > RenPy > Monika After Story**

**Comment by ahass901** [comment]
Thank you so much! It worked, you're a life saver!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
