### ISSUE TITLE
Discussing another Topic from earlier

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#5360]
So, not that long ago, there was a topic that brought up a thing that would be left in your game if you were a certain age (18), and had hit a certain affection (2000+), I'm not asking about what that is, I just want to know if that's real, and if it is real, how would I know I'd received it? (this topic was from a few months ago, but it's left me in a state of confusion since I read it)

**Comment by mrflarion33** [comment]
I mean Topic on here, on Github, it is important that I add that

**Comment by mrflarion33** [comment]
someone was discussing that, I really needed to add more information on this post

**Comment by lunulae** [comment]
Yes, this is referring to the checks for whether or not risque things will be shown in MAS.

Since you asked not to know what it was, all I'll say is it's currently only relevant for a few holiday-specific things. Other than those days, there is not yet an in-game indicator.

**Comment by mrflarion33** [comment]
Oh, alright, I was just a bit confused on it, thank you for clearing that up
