### ISSUE TITLE
[Suggestion] - Gameday

### ISSUE THREAD

**Issue by Legend15679** [Monika-After-Story/MonikaModDev#5361]
Maybe you could add a game day. This day could be at the beginning of the summer holiday, where the player needs to beat Monika in games, pong or chess with a timer or a point system. No reason towards it, just another event to make things look cooler.

**Comment by Olliesama** [comment]
That's a lot of coding for something that achieves nothing tbh. :S

**Comment by AsuraShun** [comment]
Not trying to sound rude, but there's literally no point in a game day,it'd just be a waste of time and effort to make that

**Comment by multimokia** [comment]
Yeah, seems like a needless push to do something. Not everyone wants to play the games and not everyone has the time, so forcing them to do it seems a little much, and it might make that day a chore for many players.

**Comment by Legend15679** [comment]
Thanks for not sounding toxic :)
you people are amazing!
you don't see that a lot
