### ISSUE TITLE
Windows Reacts isn't working on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by d3adpan** [Monika-After-Story/MonikaModDev#5362]
On Ubuntu 18.04.4, Monika doesn't react to websites like Reddit or Youtube as she does in Win7 and Win 8.1.  In 'Settings' I have 'Window Reacts' enabled, and in 'Alerts' I have all options selected.
Thanks in advance for your time and assistance!

![Screenshot at 2020-02-19 15-36-41](https://user-images.githubusercontent.com/61102477/74873791-d88d6400-532d-11ea-8eed-3e88730b0288.png)

![Screenshot at 2020-02-19 15-36-53](https://user-images.githubusercontent.com/61102477/74873796-daefbe00-532d-11ea-8c5d-fcb9783107b2.png)

**Comment by multimokia** [comment]
Window reacts are only on Windows. There's no lib to get the active window on Linux (which works across all versions) so Monika can't see your active window.

Only notifications are enabled for Linux/MacOS

**Comment by d3adpan** [comment]
Gotcha, I wondered if that might be the case.  I recall the dev of the MonikAI project saying something similar.

Thank you!

**Comment by d3adpan** [comment]
Thank you for adding this in 0.11.3!
