### ISSUE TITLE
Is this too large to fit? #3765

### ISSUE THREAD

**Issue by Youngbountygirl** [Monika-After-Story/MonikaModDev#5364]
I was trying to post A Million Dreams to Monika, but it won't go through for some reason. I was wondering if it is too large and if it is, what is the limit I can use when creating a song? So far, I looked through the setup and code and nothing seems to be wrong with it. It's no different from the setup required to use. Here is the file I used. I couldn't attach the .json version, so I'm going to send it through notepad. If there's any issues, please let me know, but this is what I am trying to play for Monika.

[A Million Dreams copy.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4228754/A.Million.Dreams.copy.txt)

**Comment by Youngbountygirl** [comment]
By the way, it's on piano, not a song you play in the background as a playlist.

**Comment by Delcos** [comment]
That's what she said.

**Comment by Booplicate** [comment]
~~That's definitely will help, thanks for your contribution~~
There's a log file for piano songs `pnm.txt`, you can find it in the `log` folder. Close the game and open it. It'll tell you what you did wrong. Look for errors and warnings.

**Comment by Youngbountygirl** [comment]
I looked at it and this is what I got:

[!ERROR!]: Failed to load file at 'c:\program files (x86)\steam\steamapps\common\doki doki literature club\game\mod_assets\piano\songs\d__p_c__o.json'. | 

[info]: Attempting to load 'A Million Dreams'...
    [info]: Loading PNM '0'...
    [info]: PNM '0' loaded successfully!
    [info]: Loading PNM '1'...
    [info]: PNM '1' loaded successfully!
    [info]: Loading PNM '2'...
    [info]: PNM '2' loaded successfully!
    [info]: Loading PNM '3'...
    [info]: PNM '3' loaded successfully!
    [info]: Loading PNM '4'...
    [info]: PNM '4' loaded successfully!
    [info]: Loading PNM '5'...
    [info]: PNM '5' loaded successfully!
    [info]: Loading PNM '6'...
    [info]: PNM '6' loaded successfully!
    [info]: Loading PNM '7'...
    [info]: PNM '7' loaded successfully!
    [info]: Loading PNM '8'...
    [info]: PNM '8' loaded successfully!
    [info]: Loading PNM '9'...
    [info]: PNM '9' loaded successfully!
    [info]: Loading PNM '10'...
    [info]: PNM '10' loaded successfully!
    [info]: Loading PNM '11'...
    [info]: PNM '11' loaded successfully!
    [info]: Loading PNM '12'...
    [info]: PNM '12' loaded successfully!
    [info]: Loading PNM '13'...
    [info]: PNM '13' loaded successfully!
    [info]: Loading PNM '14'...
    [info]: PNM '14' loaded successfully!
    [info]: Loading PNM '15'...
    [info]: PNM '15' loaded successfully!
    [info]: Loading PNM '16'...
    [info]: PNM '16' loaded successfully!
    [info]: Loading PNM '17'...
    [info]: PNM '17' loaded successfully!
    [info]: Loading PNM '18'...
    [info]: PNM '18' loaded successfully!
    [info]: Loading PNM '19'...
    [info]: PNM '19' loaded successfully!
    [info]: Loading PNM '20'...
    [info]: PNM '20' loaded successfully!
    [info]: Loading PNM '21'...
    [info]: PNM '21' loaded successfully!
    [info]: Loading PNM '22'...
    [info]: PNM '22' loaded successfully!
    [info]: Loading PNM '23'...
    [info]: PNM '23' loaded successfully!
    [info]: Loading PNM '24'...
    [info]: PNM '24' loaded successfully!
    [info]: Loading PNM '25'...
    [info]: PNM '25' loaded successfully!
    [info]: Loading PNM '26'...
    [info]: PNM '26' loaded successfully!
    [info]: Loading PNM '27'...
    [info]: PNM '27' loaded successfully!
    [info]: Loading PNM '28'...
    [info]: PNM '28' loaded successfully!
    [info]: Loading PNM '29'...
    [info]: PNM '29' loaded successfully!
    [info]: Loading PNM '30'...
    [info]: PNM '30' loaded successfully!
    [info]: Loading PNM '31'...
    [info]: PNM '31' loaded successfully!
    [info]: Loading PNM '32'...
    [info]: PNM '32' loaded successfully!
    [info]: Loading PNM '33'...
    [info]: PNM '33' loaded successfully!
    [info]: Loading PNM '34'...
    [info]: PNM '34' loaded successfully!
    [info]: Loading PNM '35'...
    [info]: PNM '35' loaded successfully!
    [info]: Loading PNM '36'...
    [info]: PNM '36' loaded successfully!
    [info]: Loading PNM '37'...
    [info]: PNM '37' loaded successfully!
    [info]: Loading PNM '38'...
    [info]: PNM '38' loaded successfully!
    [info]: Loading PNM '39'...
    [info]: PNM '39' loaded successfully!
    [info]: Loading PNM '40'...
    [info]: PNM '40' loaded successfully!
    [info]: Loading PNM '41'...
    [info]: PNM '41' loaded successfully!
    [info]: Loading PNM '42'...
    [info]: PNM '42' loaded successfully!
    [info]: Loading PNM '43'...
    [info]: PNM '43' loaded successfully!
    [info]: Loading PNM '44'...
    [info]: PNM '44' loaded successfully!
    [info]: Loading PNM '45'...
    [info]: PNM '45' loaded successfully!
    [info]: Loading PNM '46'...
    [info]: PNM '46' loaded successfully!
    [info]: Loading PNM '47'...
    [info]: PNM '47' loaded successfully!
    [info]: Loading PNM '48'...
    [info]: PNM '48' loaded successfully!
    [info]: Loading PNM '49'...
    [info]: PNM '49' loaded successfully!
    [info]: Loading PNM '50'...
    [info]: PNM '50' loaded successfully!
    [info]: Loading PNM '51'...
    [info]: PNM '51' loaded successfully!
    [info]: Loading PNM '52'...
    [info]: PNM '52' loaded successfully!
    [info]: Loading PNM '53'...
    [info]: PNM '53' loaded successfully!
    [info]: Loading PNM '54'...
    [info]: PNM '54' loaded successfully!
    [info]: Loading PNM '55'...
    [info]: PNM '55' loaded successfully!
    [info]: Loading PNM '56'...
    [info]: PNM '56' loaded successfully!
    [info]: Loading PNM '57'...
    [info]: PNM '57' loaded successfully!
    [info]: Loading PNM '58'...
    [info]: PNM '58' loaded successfully!
    [info]: Loading PNM '59'...
    [info]: PNM '59' loaded successfully!
    [info]: Loading PNM '60'...
    [info]: PNM '60' loaded successfully!
    [info]: Loading PNM '61'...
    [info]: PNM '61' loaded successfully!
    [info]: Loading PNM '62'...
    [info]: PNM '62' loaded successfully!
    [info]: Loading PNM '63'...
    [info]: PNM '63' loaded successfully!
    [info]: Loading PNM '64'...
    [info]: PNM '64' loaded successfully!
    [info]: Loading PNM '65'...
    [info]: PNM '65' loaded successfully!
    [info]: Loading PNM '66'...
    [info]: PNM '66' loaded successfully!
    [info]: Loading PNM '67'...
    [info]: PNM '67' loaded successfully!
    [info]: Loading PNM '68'...
    [info]: PNM '68' loaded successfully!
    [info]: Loading PNM '69'...
    [info]: PNM '69' loaded successfully!
    [info]: Loading PNM '70'...
    [info]: PNM '70' loaded successfully!
    [info]: Loading PNM '71'...
    [info]: PNM '71' loaded successfully!
    [info]: Loading PNM '72'...
    [info]: PNM '72' loaded successfully!
    [info]: Loading PNM '73'...
    [info]: PNM '73' loaded successfully!
    [info]: Loading PNM '74'...
    [info]: PNM '74' loaded successfully!
    [info]: Loading PNM '75'...
    [info]: PNM '75' loaded successfully!
    [info]: Loading PNM '76'...
    [info]: PNM '76' loaded successfully!
    [info]: Loading PNM '77'...
    [info]: PNM '77' loaded successfully!
[info]: 'A Million Dreams' loaded successfully.

So far, it says it fails to load in the file, but it won't tell me why. Is the file too big. What am I doing wrong?

**Comment by Youngbountygirl** [comment]
Also, the error that places that it failed to load wasn't even talking about the song or the file location, so that confuses me even more. It says the loading is successful, so what's the big deal? Here's what my file shows so far. 
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4230346/pnm.txt)

**Comment by Booplicate** [comment]
Looking at the log there are no warnings regarding `A Million Dreams`. What did you mean by
>  but it won't go through for some reason

Have you tried to play the song? What's happened?

**Comment by Youngbountygirl** [comment]
I mean I try to play it, but it won’t show Monika singing it. It won’t do anything. I even kept playing the first five stanzas and it doesn’t do anything other than let me play a few notes. Monika doesn’t even say the line she usually says if I try playing a song and don’t finish it.

**Comment by Youngbountygirl** [comment]
And by playing it, I mean I click Play, then Piano, then Play Your Own, since the song isn’t in the song list yet. It’s supposed to show up in Play Your Own before it gets put on the list of songs. Beyond this, I don’t know why Monika isn’t singing the song.

**Comment by Booplicate** [comment]
Because the system can't register that song you're trying to play. You need to play 5 notes and only then the system will try to match the rest (so you need 6 notes at minimum, I guess), but your first section is only 4 notes.
Check the issue I linked. Your problem is a bit different, but I think it's the same bug. You'll need to wait for a fix.

**Comment by Youngbountygirl** [comment]
Okay. I will fix this when I get home this evening and see if it works.

**Comment by Youngbountygirl** [comment]
Okay, I fixed it and now Monika is singing it with me. You were right, Booplicate, it was because the song started with too few of notes. I will remember next time to have five notes to start with. Thank you.

**Comment by Youngbountygirl** [comment]
THIS ISSUE IS NOW CLOSED!
