### ISSUE TITLE
[suggestion] Birthday outfits/bows/clips unlocks (spoilers)

### ISSUE THREAD

**Issue by TheawesomeMCB** [Monika-After-Story/MonikaModDev#5365]
So I thought of something with the addition of unlocking more outfits or locked outfits you haven’t acquired yet (like the 2k ones) on birthdays... within reason of course. Let me explain. So on your birthday she decorates the room and surprises you. However what if there was a special gift option that lets you either pick 1 or randomly chooses a outfit that you haven't gotten. It could be a special Birthday one each year with either a outfit or bow or clip. Or it could be one you haven’t gotten yet that you could unlock. Like for example you can’t have 500 affection and be able to unlock a 2k affection item. I just thought it would be awesome to get a outfit you want to unlock like the other Halloween costume or can get with a certain amount of affection on your birthday for the special 2k like the Christmas and valentines one, or just get a totally new outfit/bow/clip just a idea.

Thanks for reading my suggestion.

**Comment by ThePotatoGuy** [comment]
so far the only outfits with 2k affection requirements are the really adult ones. We're not planning on making regular outfits/acs have similar strict requirements.

we're also expecting spritepack outfits/acs to make up the bulk of clothing options so users should have more choices as content is created.
