### ISSUE TITLE
Grammar issues/wrong wording?

### ISSUE THREAD

**Issue by InJusticeWeTrust** [Monika-After-Story/MonikaModDev#5366]
I noticed some rather off things in the "living in your world topic" (no clue what it's really called right now), namely the use of "how" instead of "what" (**"how it's like to live where you are/to be in your place"**, when it should be **"what it's like"** instead"). 
Then there's the **"in your place"** thing, which probably should be **"at your place"**, as the former implies that she wants to replace us in our world or something of that nature.

https://dictionary.cambridge.org/us/grammar/british-grammar/how-is-or-what-is-like
https://ell.stackexchange.com/questions/81938/in-at-your-place-on-at-your-end
Added these for reference.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
