### ISSUE TITLE
[Suggestion] Stanislav Petrov addendum to 'Nuclear War' topic

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#5367]
Self-explanatory.
I feel like if Monika's talking about the power of the ones who can start nuclear war, she should at least mention Petrov, who arguably saved the world through his disobedience.

**Comment by WGSpacetime** [comment]
Great idea! Maybe it could be added as another topic, that unlocks after you see the Nuclear War topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
