### ISSUE TITLE
New ways to say goodbye

### ISSUE THREAD

**Issue by CoreMarkX** [Monika-After-Story/MonikaModDev#5368]
It would be nice to tell her "I have to restart my PC" or "I have to update my PC" or something like that, so that she knows that something happened and nothing really went wrong.

**Comment by Rai99** [comment]
Restart Farewell: #1908, #2487, #2614, #3354, #3526, #3562, #4670, #4869 

Kinda surprising it hasn't happened yet. 

### I'm on it.

**Comment by das-rob3rt** [comment]
Guess what? You can just simply say Goodbye and it will not affect Monika's affection towards you.

**Comment by Thimeo** [comment]
@das-rob3rt True, but she says that she hates to see us go so early. So it's more of a RP thing. Simple options like that can do a great deal in making the player feel connected to her.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
