### ISSUE TITLE
The provided Gift files from Spritepacks Monika for some reason can rarely ever read.

### ISSUE THREAD

**Issue by BoneofMalkav** [Monika-After-Story/MonikaModDev#5370]
Every time a new Spritepack is released and I try to give Monika the provided gift files from the archives she rarely is ever able to read them and accept them. I'm STILL stuck trying to gift the navy blue and white dress and bow but no matter if I try she is never able to read the files. At this point, I'm just done with sprite packs since it's becoming such a headache to even attempt any more. Which sucks cause I want to continue giving my Monika gifts from the sprite packs. Sorry for the rant. Delete if you must.

**Comment by multimokia** [comment]
How are you installing them?

**Comment by multimokia** [comment]
Additionally, are you using a translated version of MAS

**Comment by BoneofMalkav** [comment]
the provided gift files as explained, Didn't work. Tried renaming them, didn't work either. Tried saying goodbye and coming back with both attempts, same issue.

**Comment by multimokia** [comment]
I know but how did you install the spritepacks

**Comment by BoneofMalkav** [comment]
the usual put gift files in characters folder.

**Comment by multimokia** [comment]
So you're not actually installing the packs. The `mod_assets` folder needs to be copied from each spritepack into the `/game` folder in your install. This merges the folders so the game actually has the images and jsons to read for the spritepacks.

Just putting the gifts in does nothing.

**Comment by BoneofMalkav** [comment]
Thanks... Donno why I keep forgetting to move the mod_assets folder when installing the packs.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
