### ISSUE TITLE
grouping in the selector screen

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#5371]
some ACS (ribbons) have too many options. All selectors are organized alphabetically but there might be better ways to do this:

### add collapsible/expandable groupings based on subtype/`acs_type`
* since selectors are filtered by group, grouping by `acs_type` would work out fine
* would need to dynamically hide/show displayables (probably just via a branch), but would need to evaluate potential performance issues
* restoring/canceling should close/reopen a grouping as well

### color groupings (from [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/5334))
* again, grouping by `acs_type` but iterating over color per grouping
* need buttons (could use the `MASClickzone`) on the sides of a selector
* restoring/canceling should scroll back if needed
* would be a UX nightmare if a specific type has a ton of colors

more ideas will be listed here...

**Comment by ThePotatoGuy** [comment]
also search function maybe?
* text field, needs to be focusable/blurrable
* probably search as you type for ideal behavior. sorry future self.

**Comment by ohnoitsavon** [comment]
I believe I have a solution to some of this.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
