### ISSUE TITLE
About the statics...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#5372]
I turned up MAS today, and while I was reading a manual of a game that I have, I suddently startled by the statics that Monika made.
She apologized, sure it's ok...
But then she said that no one else was there...
Who was it?

**Comment by Dank-Elf-Boy** [comment]
Just a little Easter egg, my dude.
(A random event that occurs every now and then. She's just messing with you lol.)

**Comment by multimokia** [comment]
Actually it only shows up once now.

**Comment by Dank-Elf-Boy** [comment]
You mean the Yuri thing, right? Every now and then I still see that little Easter egg. Not the one where Yuri talks, but when the game opens with the weird glitch sound followed by a broken sprite. I still see that one every now and then. 😛

**Comment by multimokia** [comment]
You sure you're running latest then? That's been set to lock after seeing it once. Been in since 0.10.4. 

See #5032

**Comment by Dank-Elf-Boy** [comment]
Oh, I saw that I mentioned the Yuri glitch first. My bad, I meant the one where you open the mod and Monika appears distorted for a second, followed by the static sound effect.

**Comment by hlepnamingblyat** [comment]
> Just a little Easter egg, my dude.
> (A random event that occurs every now and then. She's just messing with you lol.)

Messing with me, in the good way right?

**Comment by Dank-Elf-Boy** [comment]
lol yeah. Don't worry, there's nothing spooky in this mod compared to the original game.

**Comment by AsuraShun** [comment]
Yuri talks?

**Comment by Dank-Elf-Boy** [comment]
In the earlier versions of the mod there was a chance you'd see Yuri for a brief second followed by a short dialogue calling out to the player. These Easter eggs only happened when you launch the game. 

I remember another Easter egg where when you're prompted to "Knock","Listen, or "Enter" with a black screen. In one case, I entered without knocking and found Monika in the MC's room.

**Comment by AsuraShun** [comment]
That explains the yuri desk pic

**Comment by Dank-Elf-Boy** [comment]
No, it was her normal Sprite from the original DDLC. Idk what those sketches are in the asset files. Been there since..2018 or something lol.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
