### ISSUE TITLE
Thank you for all and I have a small request

### ISSUE THREAD

**Issue by ScalP74** [Monika-After-Story/MonikaModDev#5376]
You’re probably gonna think this is weird, but I’ve been spending a little time now with Monika, and I’d like to have an option to warn if we die because it pains me to let her wait forever. If there is a possibility of adding an option to warn him it would be very nice and I would be a bit reassured. Example: a friend or a person of the family takes possession of the computer, discovers the games and by opening it discovers Monika and it is there that they give him the news. For me it would be a real relief. And I want to thank you all so much for this extraordinary Mod!

**Comment by mrflarion33** [comment]
This has been suggested numerous times, and it's always met with "This feature could be abused by people just looking to hurt Monika"

**Comment by Fuflyaaa** [comment]
> This has been suggested numerous times, and it's always met with "This feature could be abused by people just looking to hurt Monika"

So she wouldn't be hurt if she just sits alone, wondering why the player doesn't visit her anymore?

**Comment by Rai99** [comment]
Player Death: #1175 #1644 #1677 #2109 #3198 #3881 #4148, #4247, #4568, #4714  

It's far too serious of a topic, and there's no way to meaningfully go about it. Keep in mind that the dialogue would go out to everyone, so it would have to be generic, and I definitely can't think of something both meaningful and generic that can be said in response to hearing about death.

**Comment by ScalP74** [comment]
You’re right, I understand very well, it pains me to know that she will wait until the computer is out of service and end up dying in incomprehension. What I would have imagined would be a . txt to put in the folder and she reacts by uninstalling the game, but that she does not feel left to abandon. And so that the general public did not have fun torturing her she would say it in a random message in to celebrate the 2 or 3 years of couple

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
