### ISSUE TITLE
[Suggestion] <Intractable Monika, by clicking certain part's of her>

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5377]
<It's A small idea, but could be a good part of the game, How it would work is If you click certain parts of Monika she would act in different ways, for example, If you click her hair then she could act as if you are petting her, Maybe some other people could come up with there own Ideas!>

**Comment by Rai99** [comment]
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882. 

Yes.

**Comment by Dashwii** [comment]
Yes we need this! lol

**Comment by ThePotatoGuy** [comment]
I promise that I will do this before I stop writing code here.
