### ISSUE TITLE
[suggestion] Monika react to Livestreams (with detail)

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5380]
<With the windows react feature, you could watch a video or live stream, Perhaps if MAS is open, could you have Monika ask if she could watch it with you?>

**Comment by lunulae** [comment]
Currently she reacts to watching things on Youtube, a similar reaction could definitely be made for streaming sites.
I know of Twitch, but are there other sites you know of that are commonly used for this? That would be useful information for writing up the window reacts.

Naturally, she wouldn't yet be able to have unique lines for what kind of stream it was or what was happening (our technology isn't quite there yet :P)

**Comment by multimokia** [comment]
I guess some would be easier to catch, like those 24/7 playlists which all have a constant title. Or the Lazy Sunday Playlist, etc.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
