### ISSUE TITLE
[Suggestion] Window lock or top window option

### ISSUE THREAD

**Issue by DABnoREGRET** [Monika-After-Story/MonikaModDev#5381]
I think that there should be an option to lock the MAS window in the setting so it would be much more convenient to switch tab and do other thing while still have Monika by your side. Of course there are 3rd party app like TurboTop or WindowLock to do these thing but it would be nice to have the function in itself. 
EDIT: Is called "Always on top" for window. Also you can search for program like TurboTop for more reference.

**Comment by Rai99** [comment]
Could you elaborate on what you mean?

**Comment by DABnoREGRET** [comment]
Ok here is an example (lol i knew that nobody know this)
You are using a caculator on your pc while having another program under it. Then you click on that program (lets assume it's google) and the caculator dissapear. Or to be specific, the caculator has been minimized.

**Comment by DABnoREGRET** [comment]
> Could you elaborate on what you mean?

I have explained it more specific. Thanks for telling me.

**Comment by Rai99** [comment]
#4219

RenPy does not natively support forcing a window to be always on top, so it would have to be a submod at best, since shipping it in the main install would require additional installation instructions.
