### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by st0nkz** [Monika-After-Story/MonikaModDev#5382]
I'm using Linux as my main OS and I am using wine to run games that haven't ported to Linux yet (including this one), however I'm getting the following error when running the game:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 200, in script
  File "renpy/common/000statements.rpy", line 383, in execute_pause
    renpy.with_statement(Pause(delay))
IOError: [Errno 13] Permission denied
```

Other mods work fine but it seems that MAS is the only mod I've tried that requires some sort of file permissions, how do I fix this?

**Comment by Booplicate** [comment]
I don't know about your error, but jfy there's a version of DDLC for Linux. And the mod should work on Linux too. You could try to run the game from Linux if you want.

**Comment by st0nkz** [comment]
> I don't know about your error, but jfy there's a version of DDLC for Linux. And the mod should work on Linux too. You could try to run the game from Linux if you want.

Is that what the DDLC.sh file in the game directory is for?

**Comment by Booplicate** [comment]
Unsure about Mac (tho I would think so). Windows and Linux versions are distributed in one archive and Mac one is in its own separate archive. So if you have version for Windows, you have for Linux too for sure.
I'm not a Linux user, but afaik yes, you need to use `.sh` files to run programs on Linux.

**Comment by st0nkz** [comment]
> Unsure about Mac (tho I would think so). Windows and Linux versions are distributed in one archive and Mac one is in its own separate archive. So if you have version for Windows, you have for Linux too for sure.
> I'm not a Linux user, but afaik yes, you need to use `.sh` files to run programs on Linux.

I ran the .sh file and it works perfectly, thanks!
