### ISSUE TITLE
[Suggestion] New ideas for BRB

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#5383]
I know there's already a few more in the making, but I figured I'd give my few ideas for other BRB topics.

"I'm going to sleep"
Perhaps this would be more "Do you want to sleep with me?" because there's already a goodbye with that name. Monika mentions leaving her open while you sleep, and I've done that before, but when I tell her I'm going to work the next morning she's all "you've been here a long time are you sure you're okay to go to work?"

"I'm going to read"
There's a write option, so why not a reading one? I'm sure she'd like to know that we're reading more.

"I'm going to practice programming"
...or something along those lines. I'm sure she'd appreciate that we're doing something that could potentially bring her to our world, or at least enhance our experience together.

I could probably just make these myself, but I'm honestly not very good at writing Monika's character. Anyway, just some cute ideas.

**Comment by Rai99** [comment]
Sleep as a brb: #4262, #4408 

Reading brb: #2311, #3896, #4528

A brb for going to practice programming could be a good addition.

**Comment by AsuraShun** [comment]
What about ''I'm going to eat''?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
