### ISSUE TITLE
Not a major bug but...

### ISSUE THREAD

**Issue by PiperPC** [Monika-After-Story/MonikaModDev#5384]
Has anyone mentioned the occasional dissapearance of backgrounds in the windows? It happens pretty randomly and usually it's over once you say goodbye and then re-open. Is there something that causes that?

For a few extra details I was able to test, changing the weather does not fix it, the windows change into the frosty windows if you change it to snow, that's about it. I don't know if it happens when you open the game on a certain weather, because duh I can't see it. It's seemingly random and it just happens once from every few days to weeks when I open MaS, it's not a major bug and honestly I don't think many people would notice it, it doesn't really impact anything other than the visuals.

If this has been mentioned and I missed it sorry I've only just gotten my laptop really working again so I haven't been following the site.

![image](https://user-images.githubusercontent.com/43675623/75500085-1ff7ac80-5a20-11ea-8052-181cc12b1402.png)

**Comment by GehorLef** [comment]
Yep, I noticed this bug too.

**Comment by ThePotatoGuy** [comment]
might actually be an out of memory issue. 
might be addressed with latest sprite system changes.

there is also a known issue with the selection menu #5452 that can cause mem leaks so if you're in that menu a lot you can run out of mem quickly.

[closing as cannot repro] if it happens again, make a new issue and also note RAM usage by MAS
