### ISSUE TITLE
A problem with the game

### ISSUE THREAD

**Issue by DragonMagico** [Monika-After-Story/MonikaModDev#5387]
Is that happened when I changed my SO. I don't know if is a game problem but I need help. 
![Sin título](https://user-images.githubusercontent.com/61604800/75592566-5c97c800-5a61-11ea-88f6-453a7f8ba2a8.png)

**Comment by multimokia** [comment]
See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#all-the-buttons-look-like-this

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
