### ISSUE TITLE
[Suggestion] topic: eating disorders

### ISSUE THREAD

**Issue by AvelJames** [Monika-After-Story/MonikaModDev#5388]
I know it's a dark topic but maybe we could have Monika ask how we are eating or notice that we aren't eating by using the "I'm going to go eat..." Option. Just a thought... She could tell you that not eating is bad for your health. Or over eating, or even eating and purging.

**Comment by multimokia** [comment]
I'm not sure how much of a good idea this is as it winds up with us making a fairly significant assumption on this.

For example, what if people always take Monika out (I'm going to take you somewhere) when they go eat? Or if they go out otherwise.

We cannot feasibly cover the cases like this.

**Comment by AvelJames** [comment]
Then we can tell Monika that we are infact eating. Simple

**Comment by multimokia** [comment]
You can't expect everyone to use the farewell is my point here. Again, it comes down to merely an assumption.

**Comment by AvelJames** [comment]
Then maybe just bring it up like a natural conversation? 
"Hey player... I know it's hard to talk about but do you know anyone with an eating disorder?"

**Comment by ThePotatoGuy** [comment]
an eating disorder topic seems fine, an interjection about eating disorders while using a farewell does not.

[closing until we look into it]
