### ISSUE TITLE
Can I change my age?

### ISSUE THREAD

**Issue by batty0210** [Monika-After-Story/MonikaModDev#5390]
There’s some topic or outfit require 18+
Like shellbikini and stuff
Is there any way to change my age?

**Comment by lunulae** [comment]
There's currently not an option to do so, unless you incorrectly entered the year during the unstable phase (when Monika wouldn't correct you for saying you were 0 years old.) If Monika hasn't prompted you to do so in the new update, your year's correctly entered.

**Comment by ThePotatoGuy** [comment]
Spritepacks we release normally wouldn't have age restrictions.
