### ISSUE TITLE
Contradictions

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#5391]
In the "Human functionalism" topic Moni stated that free will is a lie and tells us that we're both just calculation machines, but in the "Determinism" topic she says she doesn't think life is predetermined and in "Solipsism" topic she says "we're both people that can think for ourselves." And there was one more topic, that I can't recon, in which she also says that we have free will... so in short, this is a contradiction, that'd be corrected.

Another, less intrusive contradiction, is Moni reciting Hamlet, when in "Trying to fit in" topic she said she actually found Shakespear kind of boring... it's not strictly a contradiction, but imo it still doesn't fit in...

**Comment by Rai99** [comment]
Monika never said she actually believed any of those ideas. She only brought them up for conversation. 

As for her reciting Hamlet while finding Shakespeare boring, not all his works have to be disliked for her to generally find them boring. There may be one or two gems that stick out while the rest are generally boring.

**Comment by mrflarion33** [comment]
But wouldn't it be best to include a quick line of dialogue to indicate that?

**Comment by ThePotatoGuy** [comment]
yes

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
