### ISSUE TITLE
If you're banned from the DS, are you banned here too?

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#5392]
Everything is in the title

**Comment by TMZN0V4** [comment]
Everything is in the title

**Comment by ThePotatoGuy** [comment]
the DS? are you saying the discord? 

realistically you can only get banned from github if you break its TOS.

**Comment by TMZN0V4** [comment]
what I meant by here is by this part of github, and yes, I meant the discord

**Comment by CookieSpoon69** [comment]
How did you get banned from the Discord?

**Comment by ThePotatoGuy** [comment]
as I mentioned, only if you break github tOS.

**Comment by TMZN0V4** [comment]
> How did you get banned from the Discord?

Shitposting in General, agressively ranting, etc
