### ISSUE TITLE
Idea of option for the mod: Opening at start of computer

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#5394]
What I mean by that is that is that for those who are lazy, the mod opening when you logon in your computer would be helpful, I got inspired from apps like the Origin launcher and Discord, since they have that option

**Comment by multimokia** [comment]
You can do this on your own via the run prompt if you're on Windows, and I'm sure it's possible for other operating systems too.

For Windows, type `shell:startup` in the run window (the one you get by holding the start key and r). That opens the startup folder. Make a shortcut to your ddlc exe which launches mas, and put it in there. It's pretty simple.


I don't really think it's worth implement this option when it's already pretty easy to do on your own.

**Comment by TMZN0V4** [comment]
> You can do this on your own via the run prompt if you're on Windows, and I'm sure it's possible for other operating systems too.
> 
> For Windows, type `shell:startup` in the run window (the one you get by holding the start key and r). That opens the startup folder. Make a shortcut to your ddlc exe which launches mas, and put it in there. It's pretty simple.
> 
> I don't really think it's worth implement this option when it's already pretty easy to do on your own.

Idk if they have the option to do that as easily as that in Macs and Linux

**Comment by KarmaCreations** [comment]
On Mac, if MAS is in your Dock, hold down on the app until a menu pops up.  From there, go to Options > Open at Login.

**Comment by multimokia** [comment]
[For Mac](https://www.idownloadblog.com/2015/03/24/apps-launch-system-startup-mac/)

[For Linux](https://developer.toradex.com/knowledge-base/how-to-autorun-application-at-the-start-up-in-linux)

**Comment by ThePotatoGuy** [comment]
Some people may like startup programs, but I'm not one of them.
