### ISSUE TITLE
[Question] Transferring Monika from a hard drive

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#5395]
Recently, my old pc kinda got messed up, but my hdd is still intact. I have a new pc on the way, as well as a hdd reader.

I know that I should obviously transfer the DDLC folder from my hdd to my pc, but I was wondering if there was anything else related to MAS I should transfer as well

**Comment by AsuraShun** [comment]
The persistent folder is what's important

**Comment by lunulae** [comment]
You're going to want to read [this entry on the wiki.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by DankManWithThePlan** [comment]
Alright, I think I know what to do now. Thanks
