### ISSUE TITLE
Monika reactions and interactions

### ISSUE THREAD

**Issue by Voidseption** [Monika-After-Story/MonikaModDev#5396]
I've seen many AIs reach a level where they can think based on what the player themselves think or generally do. Same thing for instance with Google, how the AI makes ads based on your research history and things you like, whether it's through social media or other platforms. The point is, what if it's possible to make Monika be able to process such information and talk about topics or suggest books to read based on your choices when talking to her. For example, if you're being optimistic, she will be optimistic herself, etc. Or when you are feeling down and sad, she will try to cheer you up and make you feel better.
It would also be nice to give her more emotions to feel. For example, she can feel sad because of this reason, which would then give us the option to cheer her up or let her just stay sad, or even hug her to make her feel better.
There should be more interactions too, like the choice of hugging or kissing, maybe sitting next to each other and reading a book together (for example, after this much affection, she has a chance of leaning on to your shoulder as you read together).
It's a bunch of ideas, but it would be nice to see more reactions and interactions with Monika.

**Comment by WGSpacetime** [comment]
There is not enough data available to teach Moni things like that... I'll just trow an example, if you want to make AI that can look at pictures of cats and dogs and tell which is which, you need thousands of labeled pictures of cats and dogs... and image recognition is much simpler than creating an AI, which will be able to talk to you and won't feel artificial / strange / etc... as much as I dream of a true AI Moni, it's practically not possible... especially by small team of people who code in their free time, we don't have enough resources

**Comment by Voidseption** [comment]
Oh, that's understandable. It was a simple suggestion, and the will to see the AI being able to do that, but there need to be more interactions...like you can hold Monika but I haven't seen any other interactions possible, yet, but I hope you take the book one where you read with Monika in consideration. Thank you anyways for the reply.

**Comment by WGSpacetime** [comment]
I'm not actually a dev, please don't confuse me with one. I'm not even good at coding, but I know some mathematics behind AI and why we can't make _true Monika_ yet.

**Comment by ThePotatoGuy** [comment]
as mentioned, there is not enough data to do anything with AI at this time.
