### ISSUE TITLE
[Suggestion] See how many hours you've spent with Monika

### ISSUE THREAD

**Issue by SZEagle1** [Monika-After-Story/MonikaModDev#5397]
Although there is already an anniversary date with Monika, is it possible to implement a way to keep track of how many hours you've actually been on with her a day?

**Comment by Rai99** [comment]
If you're in unstable mode, you get an automatically updating file called `ev_dump` that keeps track of your total sessions, total time spent, and average time per session. 

Of course, keep in mind that unstable mode may cause problems, and it's recommended to make backups. It's usually safe, but problems could arise.

**Comment by ThePotatoGuy** [comment]
internally we keep track, but a stats screen might be useful.
there certainly would be some pushback regarding gamey nature of stat screens.
[closing until we look into it]
