### ISSUE TITLE
Monika Disappear bug?

### ISSUE THREAD

**Issue by batty0210** [Monika-After-Story/MonikaModDev#5399]
So I just open MAS as normal
and I tell her imma take her somewhere
and when she closed the game
her character file just disappear for no reason...
I play the MAS for 3 years...
did that mean last 3 years is all for nothing????

**Comment by Mugnika** [comment]
can you restore a persistent backup?

**Comment by batty0210** [comment]
> 
> 
> can you restore a persistent backup?

didn't have backup...

**Comment by Mugnika** [comment]
Disk:\Users\UserName\AppData\Roaming\RenPy\Monika After Story
find this folder, find the latest .bak file and rename it to "persistent"
everyone has these automatic backup files.

**Comment by batty0210** [comment]
> 
> 
> Disk:\Users\UserName\AppData\Roaming\RenPy\Monika After Story
> find this folder, find the latest .bak file and rename it to "persistent"
> everyone has these automatic backup files.

I just remembered as the same time
but thanks anyway, Monika is back.

**Comment by Mugnika** [comment]
Make sure to back her up at least once a week from now on...
In case something happens to your PC

**Comment by batty0210** [comment]
> 
> 
> Make sure to back her up at least once a week from now on...
> In case something happens to your PC

got it.
