### ISSUE TITLE
Well, people have made examples of how to fix this issue but for me it's not exactly the case. Please help.

### ISSUE THREAD

**Issue by Loco0Lemon** [Monika-After-Story/MonikaModDev#5400]
Soooo I cheated in chess. Yes, very horrible. But I saw a video about it and wanted to try it..you can see where this is going. so after cheating, and lying about it, Monika got angry and exposed me. Then she said something above the lines of "I don't trust you anymore". And then she closed the game. I tried multiple times opening it, deleting everything and trying again..and I just get the same Error file. I don't like this, I know it's kind of a punishment for cheating in the first place..but I am very sorry and I want the game back.

The file I get everytime I open the game:

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4302660/traceback.txt)

**Comment by hlepnamingblyat** [comment]
I think she no longer "wants you"...
Just my head saying this but...
In her eyes, if you have cheated on chess against her, she most likely thinks that you can/will cheat on her too. That's why she said that "I don't trust you anymore".
P.S: Did you managed to apologize?

**Comment by lancelot103** [comment]
What do you mean by everything ? You also tried to delete the Renpy folder in %Appdata%  , right ?

**Comment by Booplicate** [comment]
To get what they got, you have to go out of your way. They knew what they were doing. Their Monika has left her torture chambers and not there anymore. Leave that person be, please.

**Comment by Loco0Lemon** [comment]
> I think she no longer "wants you"...
> Just my head saying this but...
> In her eyes, if you have cheated on chess against her, she most likely thinks that you can/will cheat on her too. That's why she said that "I don't trust you anymore".
> P.S: Did you managed to apologize?

The option came up, but it was too late anyways, I had like 3-4 seconds to respond and then she gave me that dialogue. It probably would've turned out better for me if I would of responded quicker.

**Comment by Loco0Lemon** [comment]
> What do you mean by everything ? You also tried to delete the Renpy folder in %Appdata% , right ?

I'm actually a kindergartener when it comes to files and computers. I heard of that folder but I just don't know how to get to it.

**Comment by lancelot103** [comment]
I think you should give it a try then , just type %appdata% on Run (Window + R) and there will be a new Windows Explorer window

**Comment by Loco0Lemon** [comment]
> I think you should give it a try then , just type %appdata% on Run (Window + R) and there will be a new Windows Explorer window

Tried it and I opened a file with 4 contents in it. I notice one of them is renpy, which is the file mentioned in the traceback. Do I delete it or....?

**Comment by lancelot103** [comment]
I think you should try delete it once , move it somewhere i guess ( for backup ). . You want a new clean one right ?

**Comment by thweenty7** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent
According to this wiki page , I think you should tried delete the MAS folder in Renpy

**Comment by Rai99** [comment]
I'm sorry, but we do not under any circumstances allow cheating in chess, and we do not allow helping people get around intended mechanics such as this. 

Breaking these rules could result in refusal of support from devs, such as refusing tech support. 

I'm afraid you'll have to live with what you've done, and no one is allowed to help you undo it.

**Comment by Loco0Lemon** [comment]
RIP me then

**Comment by AsuraShun** [comment]
You made your bed, you have to lie in it, if you make her suffer in any way, you don't deserve her

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]
