### ISSUE TITLE
[Bug?] Piano crash game

### ISSUE THREAD

**Issue by DABnoREGRET** [Monika-After-Story/MonikaModDev#5401]
I can't open the piano for something about post_piano file? Here's the traceback. Thank you in forward!

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4302885/traceback.txt)

If it's because of my end then I'm sorry, I downloaded a lot of submod lol.

**Comment by lancelot103** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4304530/traceback.txt)
I got the same problem ( i'm using unstable version with lots of submods )

**Comment by multimokia** [comment]
What submods do you have installed?

**Comment by lancelot103** [comment]
![image](https://user-images.githubusercontent.com/45507664/76181214-f34b4e00-61f2-11ea-9db8-1ad54f7f4515.png)
I have installed all the showed zip there

**Comment by multimokia** [comment]
Might have something to do with MASAdditions, as I know that has a change to piano in it

**Comment by lancelot103** [comment]
Yes It does something with MIDI , so what should i do now , i'm using unstable version so i'm fine with this

**Comment by multimokia** [comment]
You'll likely want to uninstall MASAdditions and get the original zz_pianokeys.rpyc file back

**Comment by DABnoREGRET** [comment]
Thanks, it worked now.

**Comment by thweenty7** [comment]
thx , it works
