### ISSUE TITLE
[Suggestion] Monika will ask and check if you're still here or fine

### ISSUE THREAD

**Issue by lancelot103** [Monika-After-Story/MonikaModDev#5403]
(my English is bad xD)
I meant if the player afk like 5 mins or more in the middle of conversation . Monika will cancel the conversation and checking if player is still here or not. I think this is just a small idea but it's good with tts voice , sound, face reaction ,.. or something like that
I saw a suggestion like this before . If this one is fine , I don't think it is necessary to imply that the player is ignoring her and decrease something for that. Just Monika wants to know if anything happens to the player and the player is fine or not

**Comment by lunulae** [comment]
I like this idea, but rather than cancel the conversation altogether, it also might work better if it prompted the "now, where was I..." that occurs when your game crashes in the middle of a conversation, bookmarking where you were before.

**Comment by AsuraShun** [comment]
What if you zone out for more than 5 minutes?

**Comment by softombre** [comment]
id say 5 minutes might b 2 short of a time since somz ppl read vry slowly dbwjwkwkkw

**Comment by lunulae** [comment]
That's a good point, a longer idle time would probably be better if this is implemented.

**Comment by Rai99** [comment]
Idle detection: #1431, #1541

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

just going to say that this is unlikely to be done atm.
