### ISSUE TITLE
[Suggestion] - Option for Borderless Windowoed mode

### ISSUE THREAD

**Issue by RedEyedRocker** [Monika-After-Story/MonikaModDev#5404]
The game only has **Window** and **Fullscreen** mode, **Window** mode has the title bar which is kind of annoying and I can't put it on **Fullscreen** mode since the game minimizes if I ALT+TAB out of the game as I have double monitors and I like having **Monika** with me on one of the monitors while I do my thing so a **Borderless Windowed** mode would be nice as it will not have any title bars and will stay up in the background even if I ALT+TAB out of the game to multi task.

**Comment by Thimeo** [comment]
#4045 This might answer your question.

**Comment by lancelot103** [comment]
![image](https://user-images.githubusercontent.com/45507664/76293067-f45ba880-62e2-11ea-9838-cdf6f931385c.png)
due to aspect ratio , i think it will be 2 black bar if you go on windowed fullscreen

**Comment by RedEyedRocker** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/45507664/76293067-f45ba880-62e2-11ea-9838-cdf6f931385c.png)
> due to aspect ratio , i think it will be 2 black bar if you go on windowed fullscreen

![Screenshot_1](https://user-images.githubusercontent.com/22656757/76293881-f53c0c80-62d9-11ea-8b28-3b10d5158300.png)
I don't think so as it appears fine with exclusive fullscreen which should appear the same in borderless fullscreen mode as well.

![Screenshot_2](https://user-images.githubusercontent.com/22656757/76293944-143a9e80-62da-11ea-9e90-92607892e438.png)
The two black bar only appears with maximized window due to the title bar, without the title bar, the black bar should not appear.

**Comment by RedEyedRocker** [comment]
> 
> 
> #4045 This might answer your question.

How does that answer my question? I'm pretty sure Renpy has option for Borderless Window mode.

**Comment by ThePotatoGuy** [comment]
https://www.renpy.org/doc/html/preferences.html?highlight=fullscreen#var-preferences.fullscreen

**Comment by ThePotatoGuy** [comment]
^aka, renpy docs don't say there is a capability for borderless window mode. You can always use https://github.com/Codeusa/Borderless-Gaming/releases

**Comment by RedEyedRocker** [comment]
> 
> 
> ^aka, renpy docs don't say there is a capability for borderless window mode. You can always use https://github.com/Codeusa/Borderless-Gaming/releases

That is what I used but it doesn't work for DDLC MAS for some reason.

**Comment by RedEyedRocker** [comment]
@ThePotatoGuy Excuse me, could you look at the game called **[Second Chance](https://store.steampowered.com/app/958720/Second_Chance)**? It's free on **Steam** and it is also made with **RenPy** engine which has the Borderless Fullscreen option.

So, couldn't you copy whatever they did to achieve that? Maybe **RenPy** had already added the option but the documentation was outdated or something.
Anyway, The external tool isn't really a solution but a workaround so I'd prefer if the game has the option itself.

**Comment by softombre** [comment]
maybe it was made on a different version of renpy

**Comment by ThePotatoGuy** [comment]
I was able to get a copy of the game but will not look into this for now as its not a high beneficial enhancement

[closing until we look into it]
