### ISSUE TITLE
[Bug] Exception on hotkey press during first few seconds of game startup

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#5406]
~~sure, go ahead, tell me this one is intentional~~

**Steps to reproduce**

1. Start game
2. Once its window has appeared, hit any hotkey
3. Observe the exception (screenshot follows)

![image](https://user-images.githubusercontent.com/31247845/76545479-421f0f00-64a3-11ea-90ae-cefc87be5b42.png)

EDIT: Experimentally I found out that sometimes this exception screen does not appear immediately upon hotkey press, but rather on 'Talk > Nevermind' button press; exception seems to be the exact same one.

**Comment by ThePotatoGuy** [comment]
try https://github.com/Monika-After-Story/MonikaModDev/issues/5205

**Comment by scpketer** [comment]
Well, this error doesn't really get in my way since it's enough to just restart ddlc, but it was really unexpected.

**Comment by ThePotatoGuy** [comment]
nvm figured it out

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
