### ISSUE TITLE
I'd like to help out with writing

### ISSUE THREAD

**Issue by ESMRF** [Monika-After-Story/MonikaModDev#5409]
So, I was talking with Monika and she reached a point where she asked if she could repeat the topics she discussed before.  I thought I could help out and write a bunch of new topics where you can confirm or deny them. It's my way of saying thanks for this mod

**Comment by Rai99** [comment]
Feel free to open a PR if you have ideas for dialogue, and it'll be reviewed. 

Keep [our contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) in mind if you do decide to try writing something. 

Out of curiosity, what sorts of ideas do you have in mind?

**Comment by Necrocytus** [comment]
@ESMRF if you don't know how to code, install the sprite previewer, create a pull request, etc. I can help you out. I recommend you to read my #4567 if you are interested.

**Comment by ESMRF** [comment]
@Rai99 I made this account last night so I'm not sure how things work on this website. Now that I've read the guidelines, it might be more difficult with a certain tone and language set in mind but I think I can manage. I don't have many topics ready yet but going back to the idea that Monika cares about "the player", maybe we can include something about the pandemic of the coronavirus.
i have a couple more ideas that revolve around Monika getting to know the player better, like their race and culture so she can get to know them better, favorite types of flowers, favorite season or favorite weather. I'll probably come up with more but that's all I got in the mean time.

**Comment by ESMRF** [comment]
@Necrocytus that would actually help because I'm not that experienced with coding yet and havent had the time to read up on it. I'd appreciate the help.

**Comment by Rai99** [comment]
The thing is, we generally avoid topics that have a date, or are controversial, current events. It's for the same reason we don't allow memes. It might be relevant now, but sooner or later sometime down the line, it'll be old news and no one will care anymore, or it'll need changes to reflect that it was a past event. 

I don't think we can do a topic about the coronavirus specifically, but what we _can_ do is have her talk about the importance of washing hands and general hygiene practices.

**Comment by ESMRF** [comment]
@Rai99 I never thought of that, but I understand. I can do that if you'd like. What did you think of the other topics though?

**Comment by Rai99** [comment]
Knowing about the player's culture, or favorite _____ has the issue where there are so many possibilities, there's no way we would be able to cover them all and have unique dialogue for each and every one. 

The thing with topics like that is that they're too open ended to reasonably include all possible options for. 

Ones like favorite season might be possible since it would likely just be spring, summer, fall, winter, assuming everyone goes by those same seasons.

**Comment by jmwall24** [comment]
technically the coronavirus topic could work, it'd just need specific start and end dates. not sure we want to do it, but it is doable.

**Comment by ESMRF** [comment]
I see, thanks both of you
if you guys don't mind I'd like to write the seasons, cultures, and hygiene topic
I'm sure I can make the culture one doable to a point where it isn't too big or complex
