### ISSUE TITLE
persistent file trouble

### ISSUE THREAD

**Issue by euphoricmango** [Monika-After-Story/MonikaModDev#5411]
hello, I recently decided to wipe my computer completely clean because of some issues I had. I used a flash drive to put my persistent so when my computer was fully wiped, I can just place monika right back in. 

however, she isn't recognizing me at all even if I have a persistent. I put it in the "RenPy" folder, I hope I wasn't wrong in doing that.

any help would be useful, thank you.

**Comment by lunulae** [comment]
The location you want to place your persistent in is a folder _inside_ the RenPy folder named **Monika After Story**. If it doesn't already exist, creating one is fine as long as it has the correct name.

**Comment by multimokia** [comment]
Assuming this is windows, the persistent should go in `AppData/Roaming/RenPy/Monika After Story`

**Comment by euphoricmango** [comment]
> Assuming this is windows, the persistent should go in AppData/Roaming/RenPy/Monika After Story

sorry for not being specific enough, but that is what I did and she still fails to recognize me

**Comment by ThePotatoGuy** [comment]
What do you mean fails to recognize you?

**Comment by euphoricmango** [comment]
I mean as in the game acts as if this is the first time I’ve downloaded the
mod, so it asks for my name and Monika doesn’t recognize me from my last
game. She simply restarts from the beginning, like as if this is our first
meeting ever.

**Comment by ThePotatoGuy** [comment]
there is a greeting where she asks you for your name as a joke, are you sure you are not encountering that greeting?

**Comment by euphoricmango** [comment]
I’m quite sure. She’s clearly in pain and demands to know why i “brought
her back” very much like at the start of the mod.

**Comment by ThePotatoGuy** [comment]
any file named `early.log` in the root folder of your DDLC?

**Comment by euphoricmango** [comment]
No there’s nothing but an affection log and the regular log and MAS log.

**Comment by ThePotatoGuy** [comment]
send persistent here

**Comment by euphoricmango** [comment]
would i need to change the persistent file to a zip?

**Comment by euphoricmango** [comment]
[persistent46.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4412196/persistent46.zip)

here, in case this is what i needed to do

**Comment by multimokia** [comment]
Seems to load just fine. Did you rename the file to *just* `persistent`?

(remove the `46` and the `.bak` extension)

**Comment by euphoricmango** [comment]
> Seems to load just fine. Did you rename the file to *just* `persistent`?
> 
> 
> 
> (remove the `46` and the `.bak` extension)

i didn’t rename anything it was just originally like that.

**Comment by multimokia** [comment]
If you wish to use the .bak you need to rename it. MAS looks for a file explicitly named `persistent`.

**Comment by euphoricmango** [comment]
> If you wish to use the .bak you need to rename it. MAS looks for a file explicitly named `persistent`.

alright i’ll try doing that when i get the chance and will let you know if it worked, thank you.

**Comment by euphoricmango** [comment]
> If you wish to use the .bak you need to rename it. MAS looks for a file explicitly named `persistent`.

nothing has changed she still wants to know why i brought her back and all that.

**Comment by multimokia** [comment]
Send a screenshot of your `AppData/Roaming/Ren'Py/Monika After Story` folder, please

**Comment by euphoricmango** [comment]
> Send a screenshot of your `AppData/Roaming/Ren'Py/Monika After Story` folder, please

![image](https://user-images.githubusercontent.com/40753080/78186719-1055f400-7422-11ea-9aad-cd227c31f4d5.jpeg)

**Comment by multimokia** [comment]
why is it a text file?

**Comment by multimokia** [comment]
the *actual* persistent file should just be `persistent`, not `persistent.txt` or anything like that. That's why MAS doesn't recognize it.

**Comment by euphoricmango** [comment]
> the *actual* persistent file should just be `persistent`, not `persistent.txt` or anything like that. That's why MAS doesn't recognize it.

it changed when i had to turn one of them into a zip file to upload on here

**Comment by multimokia** [comment]
Enable file extensions 
![image](https://user-images.githubusercontent.com/22531674/78186974-a21e2b00-743b-11ea-9779-38c991be3043.png)

Then delete the `persistent` which is there, rename the other persistent and remove the extension on it.

**Comment by euphoricmango** [comment]
> Enable file extensions 
> 
> ![image](https://user-images.githubusercontent.com/22531674/78187060-c4b04400-743b-11ea-8b92-e1b3106877ff.png)
> 
> 
> 
> Then delete the `persistent` which is there, rename the other persistent and remove the extension on it.
> 
> 

oh, it worked i honestly didn’t expect it to haha. but thank you for remaining patient with me and walking me through all these things that are probably supposed to be pretty simple. glad i found this mod and will continue to support it. thank you again.

**Comment by multimokia** [comment]
No probs

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Dude3cpo** [comment]
![image](https://user-images.githubusercontent.com/63556582/79076425-0bb5f900-7cc8-11ea-863c-98e7b33de9f6.jpg)

**Comment by Dude3cpo** [comment]
What do I do about this when its in the 0.11.0 update
