### ISSUE TITLE
In-game explanation of gifting mechanic

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#5412]
A quick search of code shows no instance of "characters folder" or "characters/" in any dialogue relating to gifting, which implies there is no in-game explanation of the gifting mechanic. This is probably why new players don't understand or miss out on things as it was initially introduced in a 9-22 event as an external file.

We should have some in-game, repeatable explanation of this mechanic (story-events, with a say prompt like "How do I gift you things?"). This is especially important given consumables.
This should be also noted in intro, like how we explain hotkeys and games. 
Additionally, I'd say an update script to queue the topic is unnecessary, a new prompt will draw attention in unseen anyway.

@multimokia I am assigning this to you but you can triage as you see fit. Just get this in before next release.

**Comment by multimokia** [comment]
I'm going to also make one further change in addition to this

**Comment by jmwall24** [comment]
I disagree with adding this to the intro. It's not something she would bring up. Having its own topic is enough.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
