### ISSUE TITLE
New Game Idea

### ISSUE THREAD

**Issue by ESMRF** [Monika-After-Story/MonikaModDev#5414]
Recently I was watching a video from Markiplier where he played against an AI. It was Rock, Paper, Scissors. Maybe it's possible to implement the game into the mod since it seems simple

**Comment by MetalBrother** [comment]
This was definitely suggested before.

**Comment by Rai99** [comment]
Rock Paper Scissors: #55, #762, #3770

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

quite simple to do probably. games are little low priority rn
