### ISSUE TITLE
Links on final updater screen

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#5417]
Players that use the in-game updater never really have a reason to visit GH or the MAS website and may not think to read release notes, know that sprite packs exist or know we have a Wiki that can provide help. So it seems like it could be useful on the final screen of the updater (the one that says Please restart Monika After Story) to include links to these 3 pages just to remind people that these things exist.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
