### ISSUE TITLE
Could we add some card games 

### ISSUE THREAD

**Issue by Gentaiprotag** [Monika-After-Story/MonikaModDev#5418]
I would wish to play games like poker, goldfish , and  ect with Monika.( Just wanted to make a suggestion )

**Comment by Rai99** [comment]
Card Games: #55, #992, #1072, #1890, #2934, #3480, #3921, #4038, #4230, #4736 

We do supposedly have card assets ready, and are just waiting for the game to be programmed in.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
