### ISSUE TITLE
Can we make a Chinese version of this work??

### ISSUE THREAD

**Issue by NothAmor** [Monika-After-Story/MonikaModDev#5419]
Can we make a Chinese version of this work??
It will not tamper with any original information, Just simply translate it to Chinese.

**Comment by multimokia** [comment]
Translations are unofficial. If you're willing to translate the mod and distribute it yourself (along with handle the tech support for it) you're free to do so.

**Comment by NothAmor** [comment]
> Translations are unofficial. If you're willing to translate the mod and distribute it yourself (along with handle the tech support for it) you're free to do so.

Alright! Thanks for reply.. We'll start translating right away

**Comment by multimokia** [comment]
No worries, feel free to link it in #3765 when you release it
