### ISSUE TITLE
Reactions to notepad texts.

### ISSUE THREAD

**Issue by ESMRF** [Monika-After-Story/MonikaModDev#5424]
I wish could code myself but I'm useless for now.
I had an idea where certain Notepad or files could react as a message in a way.
like the imsorry.txt one
maybe some new ones could be implemented.
I can't think of one but maybe it can affect the game once you enter.
A special reaction and some affection that don't contribute to the daily limit

**Comment by lunulae** [comment]
I think some people have talked about adding something like "loveletter.txt" but there have been concerns about giving a generic response to something that could be very varied.

It's also possible that the devs might want to do something more involved with it, like having Monika keep the letters and letting the player review them.

**Comment by Rai99** [comment]
Reacting to text files: #784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3880, #3941, #4088, #4981, #5211 

It's not easily possible, since there's not really any feasible way for us to meaningfully make sense of its contents.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
