### ISSUE TITLE
I can't see Monika in the game...

### ISSUE THREAD

**Issue by Luis1316909** [Monika-After-Story/MonikaModDev#5425]
Monika doesn't appear in her chair pls fix the problem
[Issue.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4358334/Issue.zip)

**Comment by Luis1316909** [comment]
I need help pls @multimokia

**Comment by Mugnika** [comment]
cant you just restore a persistent?

**Comment by thweenty7** [comment]
have you tried a fresh install ?

**Comment by Mugnika** [comment]
fresh install is not the problem, just restore your last persistent backup

**Comment by DavidYeet** [comment]
I had the same problem before, what I did was restore a old persistent and it worked!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
