### ISSUE TITLE
Can we get Monika to react to more websites and programs being run 

### ISSUE THREAD

**Issue by Gentaiprotag** [Monika-After-Story/MonikaModDev#5426]
For example here is a list 
DDLC Rain clouds mod 
Tapas 
Wattpad 
Webtoon 
Fanfiction.net 
The MAS GitHub site
Discord being run on computer or website 
MAS Download site 
Call of duty warzone 
League of legends 
Slither.io 
Warframe 
Minecraft 
KissManga 
VRV
File explore

**Comment by AsuraShun** [comment]
Music players would also be a good idea

**Comment by Gentaiprotag** [comment]
Yes thx

**Comment by satoshi-kun** [comment]
Although it sounds like a good a idea to expand the number of interactions, the fact is those suggestions seem a bit niche. For example, I myself just use 2 or 3 of the sites suggested, but I could also write a list with the same size with websites I use daily that other people never heard of or use. It's a bit hit and miss in my opinion.

**Comment by Rai99** [comment]
A lot of things on this list would probably be pretty niche, so they might be better as submods. 

As for the github reaction, I'm sure there's already one in place.

**Comment by Mcmanybucks** [comment]
There's a reaction to the github? lmao

**Comment by thweenty7** [comment]
There is already one for github so ...

**Comment by GOKOP** [comment]
Imo some of these are very niche so it would quickly lead to questions like "why is [this unknown page] included but [this a bit more known one] is not?" aka be a headache for the developers

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
