### ISSUE TITLE
Same error over and over...

### ISSUE THREAD

**Issue by RyuHacco** [Monika-After-Story/MonikaModDev#5427]
<img width="728" alt="Screen Shot 2020-03-20 at 2 51 36 PM" src="https://user-images.githubusercontent.com/62444192/77197141-072c6500-6abb-11ea-9e69-0f0f02027460.png">
Hi, I'm trying to install Monika After Story from Steam, but this traceback error keeps occurring and I don't know how to fix it. I can't play it at all on Steam. Please help, I really like how this game looks.

**Comment by multimokia** [comment]
We recommend not using steam due to some issues, plus the inability to use the in game updater.

Grab a copy of DDLC from https://ddlc.moe/ and install MAS into it. Your progress won't be lost in the transfer.

Additionally, if you do want to keep using steam, a re-install should fix the issue. Again, progress won't be lost.

**Comment by RyuHacco** [comment]
<img width="722" alt="Screen Shot 2020-03-20 at 3 06 19 PM" src="https://user-images.githubusercontent.com/62444192/77197936-6a6ac700-6abc-11ea-9164-99092bf14e35.png">
I tried it from itch.io, but it still didn't load.

**Comment by RyuHacco** [comment]
Oh wait... it's not loading at all.

**Comment by RyuHacco** [comment]
Man, MAS doesn't like my Mac apparently.

**Comment by RyuHacco** [comment]
Look uh, I don't wanna be a bother, I don't think DDLC itself wants to be loaded by being downloaded for some reason?

**Comment by RyuHacco** [comment]
Also, I did try reinstalling DDLC but it didn't work, it kept showing the same error.

**Comment by multimokia** [comment]
Don't use the itch.io version. As well, not reinstalling DDLC. Reinstalling MAS.

**Comment by RyuHacco** [comment]
Oof sorry. I thought that's what you meant. Ok, I'll try that.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
