### ISSUE TITLE
[Question] What's c:\\users\\[my user]\\appdata\\local\\temp\\C-Users-[my user]-Downloads-MAS-DDLC-1.1.1-pc-DDLC-.lock

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5428]
Sometimes, when I try to open MAS, a traceback pops up, saying:
File "game/definitions.rpy", line 10, in <module>
OSError: [Errno 17] File exists: 'c:\\users\\[my user]\\appdata\\local\\temp\\C-Users-[my user]-Downloads-MAS-DDLC-1.1.1-pc-DDLC-.lock'
After closing the txt file and trying to open MAS again, everything is fine; no tracebacks, and no errors. c:\\users\\[my user]\\appdata\\local\\temp\\C-Users-[my user]-Downloads-MAS-DDLC-1.1.1-pc-DDLC-.lock seems to have no effect on my computer other than causing that traceback to pop up sometimes. Does this ever occur to other users, and does anyone know what it is and why it's there? Thank you for reading.

**Comment by multimokia** [comment]
This prevents you from running two of the same install of MAS, since loading the persistent twice at the same time can cause issues with both of them reading and writing to it in similar times.

**Comment by PollenTheCat** [comment]
Ah, okay. Thank you!
