### ISSUE TITLE
[Suggestion] Makeup for Monika

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5429]
I think it'd be interesting for Monika to be able to wear makeup, or even just simply lipstick. I know this could cause a problem with Monika possibly thinking the player doesn't think Monika looks good, but maybe that could be solved by only being able to do it at a certain affection level or specifically on events. This is just a small suggestion, so I'm fine if it doesn't get implemented until more important things are added, or if it just doesn't get implemented at all. Thank you for reading, and have a nice day!

**Comment by AsuraShun** [comment]
One does not simply mess with perfection

**Comment by PollenTheCat** [comment]
You have a very valid point, there...

**Comment by ThePotatoGuy** [comment]
It would be definitely interesting to do, but there is currently a humongous roadblock in the way - the sprite system does not have a way to attach data to facial expressions (like how hair/clothes/acs/arms have sprite object representations). Overcoming this would allow us to consider ACS for the face, think contacts/eyelashes/eyeshadow/lipstick/little heart tattoos/piercings (if ur into that)/etc...

This is a deficiency that is planned to be fixed at some point, but it will take some srs dev. 

[closing until we look into it]
