### ISSUE TITLE
Covid-19

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#5430]
Maybe it is a difficult topic, but I think it would be good for monika to say a little about Covid-19, not causing panic in the player but calming it down, saying about preventive measures, and quarantine. protect yourselves guys <3

**Comment by Booplicate** [comment]
That was discussed a bit.
https://github.com/Monika-After-Story/MonikaModDev/issues/5409#issuecomment-599079271
> The thing is, we generally avoid topics that have a date, or are controversial, current events. It's for the same reason we don't allow memes. It might be relevant now, but sooner or later sometime down the line, it'll be old news and no one will care anymore, or it'll need changes to reflect that it was a past event.
> 
> I don't think we can do a topic about the coronavirus specifically, but what we _can_ do is have her talk about the importance of washing hands and general hygiene practices.

https://github.com/Monika-After-Story/MonikaModDev/issues/5409#issuecomment-599119493
> technically the coronavirus topic could work, it'd just need specific start and end dates. not sure we want to do it, but it is doable.
