### ISSUE TITLE
First kiss dialogue

### ISSUE THREAD

**Issue by TMZN0V4** [Monika-After-Story/MonikaModDev#5433]
I kinda messed up with the First Kiss dialogue, where can I find it?

**Comment by multimokia** [comment]
What do you mean messed up?

**Comment by TMZN0V4** [comment]
> What do you mean messed up?

I kinda clicked the option saying I don't really think of our first kiss

**Comment by multimokia** [comment]
Ah. That topic is one time only. No way to see it again nor change your answer I'm afraid

**Comment by TMZN0V4** [comment]
oof, closing as solved
