### ISSUE TITLE
About the player character

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#5435]
So Monika calls the MC "a vehicle for the player" so does that mean that he is still in the game and if so during the kissing cutscene who is Monika kissing ?(there is also the chance that i am reading too much into this but still).Also is there any chance we can throw him out the window?

**Comment by fromulus** [comment]
It's kind of willingly left ambiguous, but I'm pretty sure we're going off the idea that he's no longer here.

**Comment by multimokia** [comment]
The idea is that he's no longer there.

**Comment by CoffeeJackaboy** [comment]
Thanks for the answers
