### ISSUE TITLE
Maybe we can use a recommendation algorithm

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5436]
Monika seems to choose the topic by random. Maybe we can set some rules or write a recommendation algorithm to make it more efficient.
For example, if the player is a teenager (we told Monika our birthday) and watches anime, then talk more about it.

**Comment by ThePotatoGuy** [comment]
current alg is based on seen count. Anything more complicated requires more tag data. Currently topics have around 1-3 tags, which isn't really enough to build a decent recommendation framework.

would be good for immersion though

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
