### ISSUE TITLE
Guardian angel of the programmer

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5438]
Maybe we can add questions like "Are you a programmer"?
if so, try to be a guardian of our code files, or ask to keep her running while we are coding.
Just pray for no bugs.

**Comment by Rai99** [comment]
If I'm understanding this right, you want to be able to ask Monika to keep your code safe while coding and pray for no bugs? 

I think this is a pretty niche suggestion, since only people who program might ever use it, and even then, I think it's a pretty random thing to ask.

**Comment by LittleSaltFish** [comment]
> If I'm understanding this right, you want to be able to ask Monika to keep your code safe while coding and pray for no bugs?
> 
> I think this is a pretty niche suggestion, since only people who program might ever use it, and even then, I think it's a pretty random thing to ask.

# NoBugs_JustMonika
I use some website tools to create ASCII arts.
Monika can create them as a txt file.
And let player add them in their programs as an easter egg or amulet
*(Willing to see more Monika’s ASCII arts on the website or something else)*
They works very well on my VS code.
But due to different font settings, I worry about if it still work.
(Some of them even don’t work very well on my Windows notpad, the font makes it a mess)

## Words:
//*(English is not my mother tongue, maybe there are some mistake…Sorry for that)*

### #1
[ Hey $player's_name$,Are you a programmer or text worker? ]
[ I’m learning program these days.]
[ I hate bugs. They are always sly and very hard to find out.]
**when in low aff:**[ So…guess what?]
**when in low aff:**[ I “DELETE” them all]//*(maybe a jump scare here)*
**when in high aff**:[ Whish you never be troubled by them.]
**when in high aff**:[ Ehehehe]

### #2
[ Hey $player's_name$,have you heard about the “**Rubber Duck Debugging**”?]
[ When bug shows, programmer explain every line to a rubber duck.]
[ It helps them clarify their thoughts and fing the bugs]
[ But… you have me now!]
[ When you meet some troubles, I’m just there waiting for you!]
[ You can tell me everything.]
[ Maybe you’ll find the answer while talking]
[ Just consider me as your “Rubber Duck”]
[ Quack! Quack!]
[Ehehehe~]

### #3
[ Hi, I made a amulet for you these days]
[ In your game folder,Check it out then~]
//*(add the txt file)*
[ You may paste them in your codes.]
[And I will guard your program forever~]
[Relax,I won’t delete anything.]
[ Just teasing you.]
[Ehehehe]


## The website I use:
http://patorjk.com/software/taag/#p=display&f=Big&t=Monika

## Sample on my VScode:
![image](https://user-images.githubusercontent.com/45428395/77840710-07181d80-71bd-11ea-83d4-1f3ce0ded200.png)

## sample file:
[amulet_sample.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4398313/amulet_sample.txt)

**Comment by ThePotatoGuy** [comment]
>keep her running while coding

basically an idle mode topic where u say ur coding. sounds good.

>keep your files safe

depends on the level of depth here. Realistically we could just have users drop in files into a folder called `lockbox/` or something and have Monika checksum them. If something is off, then she can apologize. Can't say its super useful or enticing but seems potentially interesting.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
