### ISSUE TITLE
Plant together

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5439]
Maybe we can give some seeds to Monika and plant together.
Just set them in the background, click them to see the situation, watering from time to times.
We can set the kind of seeds unknown, and can only recognized while grow up.
It must be very excited to see the flowers plant together with Monika.

**Comment by Rai99** [comment]
This would require art, and probably a bit of work towards an at least semi realistic, gradual plant growing system. 

The idea for idle style minigames was brought up in #3201, but we want to keep the focus on Monika, and not some background feature. 

I'd say it's possible to have a feature like this, but I wouldn't guarantee it, and it would probably have to come at a later date.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
