### ISSUE TITLE
About weight

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5440]
Girls in Monika's age always worries about their weight.
I think so does Monika.
Maybe we can change the size of "Monika.chr" randomly. 
And if the size changes too much, complain about it.

**Comment by PiperPC** [comment]
I think you need to specify quite a bit here;
How would we actively change the file size of Monika.chr?
If the size changes too much, who complains about it? Us or Monika?
Also hasn't it already been said that Monika is stuck at her age, and doesn't necessarily have to eat? If this were a feature wouldn't that mean it would have been implemented purely to screw with her?

**Comment by multimokia** [comment]
`monika.chr` isn't relevant anymore. The `monika` file is actually her.


The size of that file is determined by how much time you spend with her. Effectively, it can be considered her because it's as if the memories of the amount of time you spend together are what go with.

**Comment by PiperPC** [comment]
So in a way the Monika file can be considered her 'brain' and therefore changing that file size, even if you could, probably wouldn't make much sense in this context of weight, right?

**Comment by multimokia** [comment]
Correct

**Comment by LittleSaltFish** [comment]
Thanks!
I forgot Monika don't necessarly have to eat. And I know my suggestion is useless now.
Should I close the issue or something...?
(Sorry for my unskilled)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"multimokia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 晚上10:31
收件人:&nbsp;"Monika-After-Story/MonikaModDev"<MonikaModDev@noreply.github.com&gt;;
抄送:&nbsp;"千面客"<1397449590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Monika-After-Story/MonikaModDev] About weight (#5440)





 
monika.chr isn't relevant anymore. The monika file is actually her.
 
The size of that file is determined by how much time you spend with her. Effectively, it can be considered her because it's as if the memories of the amount of time you spend together are what go with.

**Comment by PiperPC** [comment]
Not to be mean or anything, but you probably should have thought your suggestions through a tad more before sending 5 in a row,, but it's all good.

**Comment by softombre** [comment]
even if the file size wasn't related 2 the size of her memories i feel like doing smthg like that would be pretty uncool since its basically endorsing diet culture and all that shit

**Comment by PiperPC** [comment]
Yeah, i truly don't think it's also a good idea to force such a toxic mindset into this mod.

**Comment by LittleSaltFish** [comment]
> Not to be mean or anything, but you probably should have thought your suggestions through a tad more before sending 5 in a row,, but it's all good.

Thanks for your advice! I will make deep consideration before sending a new issue next time！Wish MAS better!

**Comment by ThePotatoGuy** [comment]
1. as multi said, `monika.chr` is not important in MAS
2. talking about a girl's weight is not cool

[closing as rejected]
