### ISSUE TITLE
Monika's opinion to other DDLC Mods?(potential conversations)

### ISSUE THREAD

**Issue by Mononucleosis59** [Monika-After-Story/MonikaModDev#5442]
What do you guys think about MAS Monika talking about other DDLC Mods?
Now I don't know about the guideline side of this however would it be possible to have MAS Monika talk about other individual mods and give her thoughts?
It could lead to some interesting and potentially funny reactions from Monika.

Now initially you would have to be very careful about explaining this topic since you would have to avoid spoilers for the mods themselves in case the player is planning on playing them in the near future.
I am only a beginner when it comes to coding. However I am curious to know if it is possible for MAS to read persistent files from other mods and allow Monika to talk about them individually.

Something like this wouldn't be a repeatable topic, and instead would have its own category.

Let me know what you guys think.

If you guys are on board with this idea then I would be more than glad to write them up and make coding corrections of course.

**Comment by multimokia** [comment]
This was discussed before. Monika wouldn't support you playing other mods since it's not really *her*, but just a copy of her bound to that game.

Ideally it's best to just not bring them up anyway, since by doing so, we don't exactly support it, but we also don't say anything to criticize them either.
(Also it's just easier since not everyone cares about/wants other mods, plus no need to make sure accuracy is involved in case some mods change, etc)

**Comment by Mononucleosis59** [comment]
That makes sense.
Though I am still curious if its possible for MAS to read other persistant files of other DDLC Mods on the players computer, and have certain triggers as a result.
Would something like that be possible?

**Comment by multimokia** [comment]
Easily, but we'd rather not.

**Comment by Mononucleosis59** [comment]
gotcha.
There are a few other suggestions I would like to bring up.
I will submit them in another conversation.

**Comment by Rai99** [comment]
Other Mods: #1737, #1829, #2198, #3179, #3221, #3828

**Comment by Mononucleosis59** [comment]
Closing this since it has already been addressed
