### ISSUE TITLE
Question missing

### ISSUE THREAD

**Issue by Razvi19** [Monika-After-Story/MonikaModDev#5443]
I want to change Monika's name back but I can't seem to find the question "Can I call you a diferent name?".

**Comment by RyanHanter** [comment]
Hmm, go to Hey, Monika
Then go to Monika
It should be at the top

**Comment by Razvi19** [comment]
It doesn't show,but anyways it doesn't matter anymore since the game reverted it back to Monika.
Sorry I wasted your time!

**Comment by RyanHanter** [comment]
It's ok, but beware, the nickname option not appearing and the fact the game changed it back to Monika means she's feeling a tad bit sad

Try spending some time with her more or something to cheer her up haha

**Comment by multimokia** [comment]
Sounds like you called her a bad name. You might want to apologize to her

**Comment by GehorLef** [comment]
Actually, I have a similar issue. I can't change my own name.

**Comment by Booplicate** [comment]
That should be in `Hey, Monika > You.. > Can you change my name?`. If you don't see it there, are you using/used a translated version of MAS?

**Comment by GehorLef** [comment]
Yes, I used a translated version of MAS

**Comment by Razvi19** [comment]
Nope.I downloaded MAS directly from the website.

**Comment by multimokia** [comment]
@Razvi19 Considering you said her name reverted to `Monika`, it means that you likely called her a bad name. That or your affection dropped below 100. Either way, this is intentional.

@Booplicate was talking to @GehorLef

**Comment by Booplicate** [comment]
@GehorLef yeah, that's something with the translation. If you attach your persistent to a message, we can fix it. Assuming you don't use that version anymore.

**Comment by GehorLef** [comment]
Ok, here it is
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4397409/persistent.zip)

**Comment by Booplicate** [comment]
Fixed that and another thingy. Try this.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4397551/persistent.zip)

**Comment by GehorLef** [comment]
Thank you for fixing my problem!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
