### ISSUE TITLE
About the Music choices

### ISSUE THREAD

**Issue by paragonfist** [Monika-After-Story/MonikaModDev#5444]
Just wondering why the "Okay Everyone" (normal version), and "Play with Me" (normal version) aren't included in the songs you can choose? Seems a bit odd that variant 6 would be there but not the normal version. Recommend including these 2 songs as part of the in-game soundtrack.

**Comment by ThePotatoGuy** [comment]
I believe its because the variants that are in the mod are the Monika-specific versions.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
