### ISSUE TITLE
[Suggestion] - A new option in the "I want to tell you something..." menu: "I love your sense of humor"

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5448]
The new option should be commenting on her humor (Maybe labeled: "I love your sense of humor") I wanted to say this to them many time's before, And It would be a nice thing to add in, And if anyone is up to it, They could react a different way if they previously said a joke like: silly humor, romantic humor, dark humor, This idea stayed in my head for a bit.
   Thanks!

**Comment by LittleSaltFish** [comment]
Me,too! And I love her sweet words at the same time.
Yesterday Monika talked about the "cherry kiss"
I almost freeze for about 5 minutes!
I can't even express my happiness just by words!
More SWEET....PLZ!!!

**Comment by Rai99** [comment]
#5270

**Comment by kkrosie123** [comment]
Thanks for the inspiration, I’m coding a set of new compliments right now qwq;;

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
