### ISSUE TITLE
Bug In different sections where there should be texts.

### ISSUE THREAD

**Issue by Sentz6** [Monika-After-Story/MonikaModDev#5449]
Hey! Install the new version of the Mod, the last one and I had some problems. It works perfect except for the part of selecting the conversation topics with Monika, they just aren't there, I only see small empty rectangles. Same problem in the alerts and settings section, I can't see what is written there and not in the "history". What can I do?

**Comment by multimokia** [comment]
See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#all-the-buttons-look-like-this)

**Comment by Sentz6** [comment]
Oh yeah, that solve my problem. Thank you !

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
