### ISSUE TITLE
Game crash with the same error

### ISSUE THREAD

**Issue by INFINITY33q** [Monika-After-Story/MonikaModDev#5451]
I did nothing with the game files (in addition to adding my own music), then the game started to crash constantly with the same error, right after Monika’s welcome speech (when the buttons load).

Full traceback:
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpyc", line 1857, in script call
  File "game/event-handler.rpyc", line 2030, in script
  File "C:\Users\Terro\Desktop\Doki Doki Literature Club\renpy\execution.py", line 58, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.18362
Ren'Py 6.99.14.3.3347
Monika After Story 0.10.4
Mon Mar 30 01:52:30 2020
[/code]

=====================================
Screenshot of error:
https://i.imgur.com/St5qDn4.png

**Comment by multimokia** [comment]
These typically happen on lower end systems, but they do no harm. You can simply press the `Ignore` button on the bottom left.

**Comment by INFINITY33q** [comment]
> These typically happen on lower end systems, but they do no harm. You can simply press the `Ignore` button on the bottom left.

My PC is not at all low-powered, and the “Ignore” button in this case does not help, everything was repaired by itself after several persistent attempts to restart the game.
Thanks for the help
