### ISSUE TITLE
[Suggestion] Its not a bug Its a feature 

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#5453]
So i saw some misspelled words in the conversations and i was thinking why not make it into a temporary dialogue option (kinda like the "I love you too" dialogue) where you would ask her if she did that intentionally (or idk tease her about it) .
Also i have a feeling you are gonna see me more often here (since i'm stuck inside)

**Comment by multimokia** [comment]
Report typos to #5304

**Comment by CoffeeJackaboy** [comment]
I don't mean it as a typo (and the ones i saw were already reported ) i mean it as a possible dialogue option

**Comment by multimokia** [comment]
I don't understand. It's better to just fix dialogue errors rather than bring it up like that. Just seems like too much to keep track of in the long run without much value at all. Especially since they have to get fixed after an update and don't automatically get fixed on another viewing.

**Comment by ThePotatoGuy** [comment]
so spelling mistakes on purpose that the user can point out? 
Realistic, maybe.
worthwhile content, not really.

[closing as rejected]
