### ISSUE TITLE
Adding an old school LCD game to MAS

### ISSUE THREAD

**Issue by Silvery55** [Monika-After-Story/MonikaModDev#5454]
Ever seen those LCD handheld I do in photos but not in real life
 But I feel these should be in MAS but have to be creative like the example of you the player are in a vs with Monika to see who has the highest score in a racing game to find 3 or 4 random generated items that are hidden in a roll or maybe to see who got the highest score in a lCD game

 Now I know renpy has some limits and MAS has about 3 or 4(maybe I forgot since I play only pong with Monika) but I thought this might help with the game section more I guess

**Comment by Silvery55** [comment]
Also sorry if this is too long to read but in short maybe adding a random but and original Old school LCD game so the players can beat Monika in game which is basic on high score or anything which matches with the Renpy software or hardware

**Comment by ThePotatoGuy** [comment]
we're always looking to add more games, but currently we're working on more non-game activities and QOL improvements. 

[closing until we look into it]
