### ISSUE TITLE
Taking Monika somewhere

### ISSUE THREAD

**Issue by Polaris9255** [Monika-After-Story/MonikaModDev#5458]
Looking for more topic options when returning Monika from taking her out somewhere, she could ask where you went. Responses could be (but not limited to) "Just for a drive", "I brought you to work", "For a walk on the beach", "To a mall", "To the movies", etc. Just more interaction with that would be nice. Thanks for reading and doing all you do. <3

**Comment by ThePotatoGuy** [comment]
extending the existing farewells and adding more is a planned and ongoing process

[marking as duplicate of #2662]

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
