### ISSUE TITLE
I can not open - [uncaught exception occurred]

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#5461]
I tried to put one translation, I don't know if it was because of that, but I can't open it and a traceback appears.

![error](https://user-images.githubusercontent.com/45946850/77990361-7db93600-72f7-11ea-8bc2-c8c22a8dca85.PNG)

**Comment by Booplicate** [comment]
All translations are unofficial, I think you need to ask for the help the one who made it.

**Comment by ThePotatoGuy** [comment]
[closing as translations issues are handled by the translator]
