### ISSUE TITLE
[ 📦 ???? - Sayori, Yuri, Natsuki 👥 ]  :Wut:  [ Request 💌? ] {⚠️Warning: Flashy Imagery⚠️}

### ISSUE THREAD

**Issue by Professor-JMO** [Monika-After-Story/MonikaModDev#5466]
<p align="center">
<b>𝒮𝓅𝒾𝓇𝒾𝓉 𝒮𝒶𝑔𝑒</b></br>
</p>

---

![—Pngtree—happy april fool day_4098257](https://user-images.githubusercontent.com/43480604/78201250-c3404500-7456-11ea-98af-d51e3af37e3b.png)

---

![Unstable_M_Banner](https://user-images.githubusercontent.com/43480604/78396079-4c20c300-75b4-11ea-9442-06feb48b906b.gif)

<details>

 <summary>📁 Hub Preview</summary>
<br>

![I'm Thinking Catty](https://user-images.githubusercontent.com/43480604/78200954-f6360900-7455-11ea-8f56-1c4fa9ecbc8b.png)

</details>

</details>
</details>
</details>

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>
 <summary>📁Enjoying <i>Today</i> so far? </summary>
<br>

<details>
 <summary>&emsp;Yes!</summary>

<br>

That's the Spirit!

</details>

<details>
 <summary>&emsp;Yes!</summary>

Cool!

</details>

<details>
 <summary>&emsp;Yes!</summary>

<br>

Awesome!

</details>

<div align="center">

![DokiDokiChibiDance](https://user-images.githubusercontent.com/43480604/78202757-c76e6180-745a-11ea-86c0-f46afa576e2b.gif)

</div>

</details>
</details>
</details>

---

![Unstable_S_Banner](https://user-images.githubusercontent.com/43480604/78397228-82f7d880-75b6-11ea-8abc-bfc16ad65b97.gif)

---

<p align="center">
🗣️<b>[ Questions & Answers ]</b>💬
</p>

---

<details>

 <summary>📁 What is this?</summary>
<br>

- &emsp; <i>~~Heresy!~~<i>

- &emsp; ~~Utter nonesense!~~

- &emsp; Fun?

</details>

---

<details>

 <summary>📁 How can I use this?</summary>
<br>

- &emsp; You can't. Whatever it is it's stuck in Still Limbo.

</details>

---

<details>

 <summary>📁 How are you by the way?</summary>
<br>

- &emsp; :p 

</details>
</details>
</details>

---

<p align="center">
<b>[ General ]</b>
</p>

⮞ Did you know?

- &emsp;In France, April 1st is called "Poisson d'Avril."

- &emsp;French children fool their friends by taping a paper fish to their friends' backs.
When the "young fool" discovers this trick, the prankster yells "Poisson d'Avril!"

- &emsp;In Scotland, April Fools' lasts two days. Victims of pranks are called gowks (cuckoo birds). The second day is known as Taily Day, and pranks involving the backside are played. Supposedly, it is the origin of "kick me" signs.

- &emsp;In England and Canada, pranks are only played in the morning of April 1st.

</details>
</details>
</details>

---

![Unstable_Y_Banner](https://user-images.githubusercontent.com/43480604/78397791-7aec6880-75b7-11ea-9d0f-d056ded12049.gif)

<details>

 <summary>📁 Nexus Preview </summary>
<br>

![Crazy Catty](https://user-images.githubusercontent.com/43480604/78201755-0b139c00-7458-11ea-8a2d-a48e17d0f4fc.png)

</details>

---

⮞ If you're on `GitHub` browsing through Light 💡 - You must be joking not using Dark. 🕶  
⤷ [Stylish: Custom web page themes](https://userstyles.org/styles/browse?search_terms=github&type=false)
> Dark looks so much better here. 👌
>> Only looking out for your _Vision_! 👁‍🗨

---

Historic Hoaxes
---

**Crop Circles**

- &emsp;A crop circle, crop formation, or corn circle is a pattern created by flattening a crop, usually a cereal. The term was first coined in the early 1980s by Colin Andrews. Crop circles have been described as all falling "within the range of the sort of thing done in hoaxes" by Taner Edis, professor of physics at Truman State University. Although obscure natural causes or alien origins of crop circles are suggested by fringe theorists, there is no scientific evidence for such explanations, and all crop circles are consistent with human causation.

<details>
<summary>📁<b>I'm curious...</b></summary>
<br>

**Bower and Chorley**

- &emsp;In 1991, self-professed pranksters Doug Bower and Dave Chorley made headlines claiming it was they who started the phenomenon in 1978 with the use of simple tools consisting of a plank of wood, rope, and a baseball cap fitted with a loop of wire to help them walk in a straight line. To prove their case they made a circle in front of journalists; a "cereologist" (advocate of paranormal explanations of crop circles), Pat Delgado, examined the circle and declared it authentic before it was revealed that it was a hoax. Inspired by Australian crop circle accounts from 1966, Bower and Chorley claimed to be responsible for all circles made prior to 1987, and for more than 200 crop circles in 1978–1991 (with 1,000 other circles not being made by them). According to Professor Richard Taylor, "the pictographs they created inspired a second wave of crop artists. Far from fizzling out, crop circles have evolved into an international phenomenon, with hundreds of sophisticated pictographs now appearing annually around the globe."

<details>
<summary>📁<b>Keep it coming...</b></summary>
<br>

**Paranormal**

- &emsp;Since becoming the focus of widespread media attention in the 1980s, crop circles have become the subject of speculation by various paranormal, ufological, and anomalistic investigators ranging from proposals that they were created by bizarre meteorological phenomena to messages from extraterrestrial beings. There has also been speculation that crop circles have a relation to ley lines. Many New Age groups incorporate crop circles into their belief systems.

Some paranormal advocates think that crop circles are caused by ball lighting and that the patterns are so complex that they have to be controlled by some entity. Some proposed entities are: Gaia asking to stop global warming and human pollution, God, supernatural beings (for example Indian devas), the collective minds of humanity through a proposed "quantum field", or extraterrestrial beings.

<details>
<summary>📁<b>Other Hoaxes?</b></summary>
<br>

👉 [Here!](https://en.wikipedia.org/wiki/List_of_hoaxes) 👈 

</details>
</details>
</details>

</details>

---

![Unstable_N_Banner](https://user-images.githubusercontent.com/43480604/78397958-d3bc0100-75b7-11ea-9def-0a4204a6a469.gif)

---

<details>
<summary>📁<b>References</b></summary>
<br>

 #5430 

![Huh](https://user-images.githubusercontent.com/43480604/78202606-634b9d80-745a-11ea-864f-3620748181f2.PNG)

</details>

<details>
<summary>📁<b>Credentials</b></summary>
<br>

- kun.nee → For requesting the unusual addition of this!

</details>

<details>

<summary>📁<b>📎 Attachments 📎</b></summary>
<br>

⯈ [ 📦 Cardboard Cutouts 👥 ](https://github.com/Monika-After-Story/MonikaModDev/files/4418531/Cardboard.Props.zip) ⯇

</details>

</details>
</details>
</details>

---

Meme of the Theme!
---

<div align="center">

![Everywhere I look](https://user-images.githubusercontent.com/43480604/78200913-c5ee6a80-7455-11ea-895f-5b2465e20a2b.png)

</div>

---

```
from subprocess import call
```
>def play_wave_file([OMC - How Bizarre.wav):](https://youtu.be/qceCB4OL-8k)
      >return_code = call(["ffplay", "-nodisp", "-autoexit", "../success.wav"])
      ># return_code = call(["aplay", "../success.wav"])
      >print "Played successfully" if return_code == 0 else "Play ended in error"

**Comment by ThePotatoGuy** [comment]
shading on these are great, would be a shame not to use anywhere

**Comment by ThePotatoGuy** [comment]
oh with room deco that may change lmao
