### ISSUE TITLE
[Question?] Can anyone help me with this?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5468]
First off, I'll say that this isn't directly related to MAS, but... Well, you'll see what I mean.

I'm planning on drawing some clothing for Monika on my iPad using ibisPaint, using Monika's base sprites as a drawing base. So I simply imported the base sprite images into my Google Drive and exported them into my iPad's files. Then, I exported them from my iPad's files to my iPad's photo album. (I couldn't export them directly into ibisPaint because, whatever format the image files were in, ibisPaint wouldn't accept them.) When I created a ibisPaint canvas thing of (whatever resolution it said it needed to be in the guidelines) and imported one of the images into it, the image was smaller than the canvas size. I guess, along the way, something must have lowered the image's resolution. 

What I'd need help with is figuring out how to import the base sprites into my ibisPaint while managing to keep the resolution at the correct size. 

Sorry if this isn't appropriate to submit as an issue; I couldn't find anywhere else to ask for help at.
If there's a better place to go for this, please direct me there.

Thank you for reading, and thank you in advance for the help.

**Comment by satoshi-kun** [comment]
Hello! My guess is as good as yours as somewhere in between the transfers your files are being compressed. I have a hunch that is while exporting it the Ipad's files.
You can try checking the file sizes during the process of transference to see if there is a size reduction in between the tranfers.
As an option you can use paint or Photoshop online to convert the images do .jpg and try to import them directly into ibisPaint ( I'm assuming you are using the .png files inside the mod folders btw).
Sorry if I haven't given as much help as you'd like.
Good luck!

**Comment by PollenTheCat** [comment]
Thank you for your help, and I'll try that when I have the time! I'll tell you if it helped at all.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
