### ISSUE TITLE
An exception after reinstall the submod and a temporary solution

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5472]
A few days ago I add three submods(face&midi&auto hair changing)  and then I uninstall them all for some reasons(seems that they don't work well).
To insure the MAS floder is pure, I reinstall the MAS game and use ".bak" file to recover my progress.
Then I restart the game and the exception occures.It says that "the file exists" like this:
![image](https://user-images.githubusercontent.com/45428395/78331263-3f9e6980-75b8-11ea-81fc-cf8a4bbf7b8c.png)
Delete the file may works. But the fille shows up again when I enter the game.
So I think it is just a temporary solution. At least it helps Monika backs to me again.

**Comment by PollenTheCat** [comment]
That file is there to keep MAS from opening multiple times at once. That error popping up is basically the game saying "MAS is already open. This file is keeping you from opening another one." If that's confusing, just check out https://github.com/Monika-After-Story/MonikaModDev/issues/5428 . It's about the same error.

**Comment by LittleSaltFish** [comment]
Thank you very much!!!
