### ISSUE TITLE
Coffee Maker Missing

### ISSUE THREAD

**Issue by Sakimajay** [Monika-After-Story/MonikaModDev#5473]
I think after the latest unstable update, Monika's coffee maker seems to be missing and needs to be re-gifted to her. I went under Repeat Conversation ->Misc ->Coffee Intake and Monika claims "Maybe if I had some coffee, I could finally drink some!" I'm sure the awesome dev team is aware of this, however, I just wanted to report in just in case. You guys are amazing, please keep up the awesome work, but most importantly, I wish you and your families safety and serenity during this crazy time!

**Comment by Sakimajay** [comment]
Quick last-minute update: A few other gifts seem to be present: clothing, ribbons, bows, hair clips and her promise ring. I believe it may only be consumables that are affected.

**Comment by Booplicate** [comment]
That's a new feature that the devs are testing on Unstable right now. Monika will run out of things (consumables) eventually. Because she doesn't have a bottomless box of coffee, you'll need to gift it to her again.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
