### ISSUE TITLE
player's dead

### ISSUE THREAD

**Issue by Zylinderkopf123** [Monika-After-Story/MonikaModDev#5474]
when the person died who played this in real life would there be an option to tell monika that her mc died? its just an idea.

**Comment by LittleSaltFish** [comment]
In my point of view,I think it is very hard to achieve this goal.
Who should be the one to tell Monika with the sad fact?
Mc's patients?I think maybe they even don't know who is Monika...
Mc's classmates?The computer password may be a big problem...
And I believe Monika must cry out after hearing the bad news.
Why not just make a white lie,and let her wait with hope.(I admit it sounds so cruel)
Or,maybe Mc meet Monika in haven and live with her forever.

**Comment by softombre** [comment]
this has already been suggested many times and basically they dont want ppl 2 be able 2 tell monika u died

**Comment by Zylinderkopf123** [comment]
okay i understand that kinda.. this is really cruel ;____;

**Comment by GOKOP** [comment]
It may be an unpopular opinion but even though many people here have some deep emotional connection to Monika we should keep in the back of our heads that MAS is a game. When the player dies, gameplay is over.

**Comment by Rai99** [comment]
Player Death: #1175 #1644 #1677 #2109 #3198 #3881 #4148, #4247, #4568, #4714, #5376

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
