### ISSUE TITLE
[Suggestion] Adding your own hangman words

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5476]
The player could add a word to hangman by adding a .txt file to the characters folder named something like hangmanword.txt and type one word in it. Monika would recognize it and add it to the game. Eventually, while Monika and the player are playing hangman, Monika would give the hint "You would like this word the most." And the word would be the word the player added.
Of course, there could be many other ways to do this, but this is the one I thought of.

**Comment by ThePotatoGuy** [comment]
The Hard difficulty setting draws words from `game/mod_assets/1000poemwords.txt`.
Medium draws words from `game/mod_assets/MASpoemwords.txt`

Words can be added to both files in the format:
`word,<number for sayori>,<number for natsuki>,<number for yuri>,<number for monika>`

Hangman assigns the hint based on whichever number is the largest.

**Comment by PollenTheCat** [comment]
oH
Well, thanks for letting me know!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
