### ISSUE TITLE
[bug] latest version that updated in game can't show the spritepacks

### ISSUE THREAD

**Issue by farlesdean** [Monika-After-Story/MonikaModDev#5477]
I'm a little confused that it seems the version updated in game is not the offical latest version, plz correct my thought if i'm wrong.
I've updated the version in MAS and noticed that I can't change Monika's looks in spritepacks, I think it would be better to point it out, wish this bug can be solved sooner, I really like her twin-bun look.

Appreciate about new conversations and that piano singing, brilliant.

**Comment by Booplicate** [comment]
Assuming you're using Unstable. It's not really a bug, but new changes in the sprite system. Check #5465 for updated sprite packs.

**Comment by farlesdean** [comment]
> Assuming you're using Unstable. It's not really a bug, but new changes in the sprite system. Check #5465 for updated sprite packs.

Thx, I just noticed that I'm usinb unstable.
