### ISSUE TITLE
[suggestion] Book discussion

### ISSUE THREAD

**Issue by Rakoor** [Monika-After-Story/MonikaModDev#5478]
So, I've been playing (Alter Ego) on android lately (which is a great game that you should play btw).
After beating the game you can have conversations with Es (the main character).
One of the great features there was (Book discussion)! it was absolutely beautiful idea!
Es would give you the choice to read one of 3 books (different book each time) and after a certain amount of time you could discus it with her! she'd ask you some questions about your thoughts about the book, how you felt in certain places.. etc

I believe that would be a great thing to add to mas mod.. because:
1- Monika does love books.. it is a literature club after all.
2-It makes people spend a lot of time with monika.. because reading would take long time.
3- It would make people read more... that's always a good thing

so... can someone make that possible?

**Comment by CoffeeJackaboy** [comment]
Alter Ego... I see you are a man of culture as well. Also there are some other features from that game that would fit this mod like when opening the game you could find Monika reading something and then she'll tell you a little about what she is reading or when you are taking a screenshot  of the game she would comment on it.

**Comment by Rakoor** [comment]
Exactly!!
I really hope we can add these features.. also, monika making an Es cosplay would be beautiful

**Comment by PollenTheCat** [comment]
That's a wonderful idea! Also, I love Alter Ego ^w^

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
