### ISSUE TITLE
[Suggestion] Some kind of "physicall" interactions with Monika

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#5479]
So first i have a question: When we get a choice option does Monika make those choices ?(I know its actually the fellas who write the code but that would mean Monika is still running on a script wich is kind of immersion breaking). Well if the answer to that question is that 'Monika creates those options for you' then i have a proposal:Add the option to say something like "Hey what's that over there" and then be prompted with a bunch of good choices for example:"boop her nose", "kiss her on the cheek", "give her the gift" (this could also work for giving gifts)  and some bad choice "slap her face", "push her "(please don't do any of these things or i will personally come to your house and beat you with an aluminum bat).
And this could also be affected by affection (of course the first time she'll act surprised) say for example when your affection level is high she would giggle or go along with your act or assuming you have a low reputation she will straight up refuse or even remove the option to do that.
Also idk how the suggestions work but if you would like to take only one part of this thing or change it feel free and if my english made anyone gouge their eyes out i apologize.

**Comment by CoffeeJackaboy** [comment]
why did i write reputation instead of affection?

**Comment by GOKOP** [comment]
> Well if the answer to that question is that 'Monika creates those options for you' (...) and some bad choice "slap her face", "push her "

Why would Monika give you these options?

**Comment by AsuraShun** [comment]
There won't be any bad options, it would give some people an opportunity to harm her, and the boops are still being worked on

**Comment by CoffeeJackaboy** [comment]
As i said you can take only one part from this suggestion i just wrote something i thought about yesterday at 2 am. (Why i was awake at 2 am? Well i wish i knew that myself) I thought these things could be something similar to the compliment option ("I want to tell you something...").

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377 

There are plans to add simple interactions such as boops down the line.

**Comment by CoffeeJackaboy** [comment]
Now that is a lot of boops
