### ISSUE TITLE
[Bug or maybe not] All spritepacks stuff gone after update

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#5481]
So that pretty much it. All spritepacks stuff is gone, I tried to reinstall spritepacks and regift it to Monika, but she tells every time that she can't see what I'm gifting, I also tried to restart a game and computer, but it didn't work. So I'm asking is this in plans to get rid of spritepacks, 'cause if not, I will be very worried.

**Comment by multimokia** [comment]
Sounds like you're using unstable. See #5465 for reason + fix

**Comment by MetalBrother** [comment]
I have a question. Do I need to regift everything?

**Comment by multimokia** [comment]
You do not

**Comment by MetalBrother** [comment]
Thank for fast response, you really helped me so fast, thank you!

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
