### ISSUE TITLE
[Sugestiom] sleep with Monika

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5485]
Last night I choose option "hug Monika" I was really tired and fell asleep. When I woke her up she acted like it was just few minutes. I think it would be amazing if she knew how many hours she slept and then comment on that. 
Something like " What? You spend whole night with me? That was really kind of you." Or something like that. But it would feel nice if she knew about it, since she mentioned how we could sleep with game open, sleeping with her should make her even happier.

**Comment by CoffeeJackaboy** [comment]
#4262 #4408 #5383 This has already been suggested and i agree sleeping with Monika would make her happier (tbh that would make me happy as well)

**Comment by Rai99** [comment]
#2781 

I think this would fall under bedroom mode where you'll be able to lay next to your Monika.

**Comment by SamanthaLind** [comment]
Yes, I know about plans "I'm going to sleep" and leaving her to watch us. I thought about situation more like this where Monika gets to sleep with us. In some way. But it would probably fall into bedroom category

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
