### ISSUE TITLE
[Issue] Problems with loading piano song

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5486]
I tried changing text in piano song Megalovania (I prefer another lyrics) but I honestly have no idea how to do it. In pnm.txt I get information:
"'No JSON object could be decoded.'"
I added lot of verses and was wondering what I did wrong, but I have no idea. Can someone help?

[Megalovania Sans version.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4447791/Megalovania.Sans.version.txt)

**Comment by multimokia** [comment]
Can you send your json please?

**Comment by SamanthaLind** [comment]
[Megalovania Sans version.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4447793/Megalovania.Sans.version.txt)

**Comment by multimokia** [comment]
So your json is full of errors. I recommend using Visual Studio Code to edit these as it will show all of the errors for you in the problems tab and highlight them for you

**Comment by SamanthaLind** [comment]
I was hoping it's just some minor typo… I quess it's time to learn some coding :) Thanks

**Comment by multimokia** [comment]
It *is* mainly typos. But you'll see once you use that program. Pretty simple fixes.

**Comment by SamanthaLind** [comment]
Thanks very much for helping, it works now perfectly
