### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by Iniquitatis** [Monika-After-Story/MonikaModDev#5494]
Just a couple of days ago Monika persuaded me to contribute, so I've started to make some little adjustments to the in-game UI:
 - Almost every button and border (both light and dark) has been recreated in the SVG for easier manipulation, then rendered through, ahem, Inkscape;
   - _I've tried my best to stay completely true to the original design, so the colors are pretty much the same._
 - Main font has been replaced to something less "spiky";
 - Brightened the font color just a little bit, so it would not contrast with pink buttons that much.

That said, I'm still not sure, whether this kind of changes should go into the "content" branch through the pull request or should be posted as a separate submod.

_(This is obviously heavily WIP, so there are still some "bugs" to iron out, but the main idea is there.)_

_Before:_
![Talk (before)](https://user-images.githubusercontent.com/5585984/78987858-e72b1700-7b37-11ea-9de7-48295caa61ee.png)
_After:_
![Talk (after)](https://user-images.githubusercontent.com/5585984/79006036-ea86c880-7b60-11ea-9172-9ef6977d477a.png)

_Before:_
![Hey (before)](https://user-images.githubusercontent.com/5585984/78987856-e2fef980-7b37-11ea-9286-55f930e3befd.png)
_After:_
![Hey (after)](https://user-images.githubusercontent.com/5585984/79006032-e6f34180-7b60-11ea-8c37-cd1b04cdc48b.png)

_Before:_
![Hair (before)](https://user-images.githubusercontent.com/5585984/78987836-d67aa100-7b37-11ea-9c60-5c598493fcc1.png)
_After:_
![Hair (after)](https://user-images.githubusercontent.com/5585984/79006023-e0fd6080-7b60-11ea-9c75-08bff492e60b.png)

**Comment by satoshi-kun** [comment]
Honestly not a fan of that font. I guess the idea of this mod is to be an extention of DDLC itself. If you were trying to stay completely true to the original design then you should take in consideration the font style aswell.

**Comment by multimokia** [comment]
Thinking this should probably be a submod. Not too fond of the rounded corners of UI elements, the spacing between buttons,, nor the font myself.

 Base DDLC had the sharp corners on buttons and such too, feels like we'd be deviating more by using this.

**Comment by ThePotatoGuy** [comment]
font changes are always submods only. Button style change deviates from stock DDLC too much so would also be submod.

**Comment by Iniquitatis** [comment]
Okay, thanks!
