### ISSUE TITLE
[Question] [Possible Bug] Calendar appearing in night colors during day?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5496]
I might be seeing things, but I think my calendar is in its night colors, even though it's day. I'm not sure, though. It might just be my eyes seeing things. It's just that the calendar looks darker than usual to me...
![screenshot0013](https://user-images.githubusercontent.com/53543937/79002628-79babe80-7b16-11ea-9495-22ee96cfed06.png)

**Comment by satoshi-kun** [comment]
Mine also appears to be same shade as yours but I don't know if it is any different from before...
![screenshot0038](https://user-images.githubusercontent.com/54683676/79011119-44848f80-7b5b-11ea-95f6-c9e54eb539a9.png)

**Comment by satoshi-kun** [comment]
Ok, I believe it's just a mind trick. I've just made a comparison side by side with a night time screenshot and the calendar is far darker at night.

**Comment by PollenTheCat** [comment]
Ah, okay! Thank you!
