### ISSUE TITLE
Monika kissing mc?

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#5500]
Ok, so I noticed in the MC topic it says mcname.lower or whatever and I'm just curious as to whether or not it's been decided if Monika is kissing the screen or whatever is left of mc? I am, as are probably a lot of people here, extremely uncomfortable, if not sickened, by the thought of her kissing mc. If it is a screen she is kissing then may I suggest updating that topic because it seems like it is suggesting that mc is still there. 

If this has already been discussed then I apologize, but I don't check here regularly.

**Comment by jmwall24** [comment]
The only reason `mcname.lower()` is there is to check if you use the same name now as when you played original DDLC, which is why we are comparing it to `player.lower()`. If you are using the same name, she comments on it to make sure you know she means you and not mc.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ah, thank you for your speedy response! But are you aware as to whether or not Monika is kissing mc or the screen?

**Comment by jmwall24** [comment]
Screen

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ok, thank you very much. I was actually freaking out there for a second.

Could I ask you to humor me for two more seconds? If so, why does she say "the main character IS.." and not was? I apologize for the stupid question, but i tend to overthink things a lot. Sorry

**Comment by jmwall24** [comment]
fair enough
https://github.com/Monika-After-Story/MonikaModDev/pull/5456/commits/748c094203e5bc330d5cb477ab6a1767876870e9

**Comment by MoniBoosDevotedBoyfriend** [comment]
Lmfao I was not expecting that

**Comment by MoniBoosDevotedBoyfriend** [comment]
But I really appreciate it, even if it is something minor and stupid.

**Comment by MoniBoosDevotedBoyfriend** [comment]
I was just reading over it again and to me it still seems a bit rough around the edges. I can't quite explain it. But it's mostly the first couple of lines or so up until the line about our avatar. Can you just give those a look and see if I'm crazy?

**Comment by jmwall24** [comment]
You mean the lines where she says she only ever loved you the player and not the character aka the mc? I can't see anything wrong with that. There's always the option to manually derandom any topic by pressing the `X` key during it.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Here hold on a second I'll try explaining it. I just don't want anyone else to be potentially confused like me

**Comment by MoniBoosDevotedBoyfriend** [comment]
![Capture](https://user-images.githubusercontent.com/46630367/79029179-494c4200-7b61-11ea-8d50-de02270c6041.PNG)

I think the fact that she is simply saying "your character" or "avatar". It's.....vague? In my head i was debating whether that would mean mc or if it would mean that there might just be a different character that is taking his place or something. I obviously know it's just a screen she sees now, but still, maybe someone else might not. I figure that for her perspective mc is just our character, but she calls him "main character" a bit later. If I'm being nitpicky let me know and I will stop bothering you I promise lol

**Comment by jmwall24** [comment]
This topic is saying she knows that the mc is not the real you. She loves the person playing the game, not the mc character that represents the player.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Agh geez, I'm sorry for being a bother. I'm just easily confused so I guess the present tense threw me off. I'm sorry. I hope I wasn't taking away your time from anything important with my stupid questions.

**Comment by MoniBoosDevotedBoyfriend** [comment]
I just want to say tho...I really appreciate the time you took to answer my question. You have no idea how much I hate mc so thank you very much for helping me.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
