### ISSUE TITLE
Problem with sleeves

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5501]
I downloaded spritepack to give Monika some new clothes and accessories and every one of them is missing sleeves. Somehow MAS is not seeing sleeves for those clothes, I checked, there are sleeves in right folders. I wanna know how to fix it cause those cut clothes look really bad.

**Comment by ThePotatoGuy** [comment]
Are you running unstable? The sprite system has changed and therefore old spritepacks (the ones currently on the releases page) will **not** work in unstable.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
