### ISSUE TITLE
issue? all clothes are gone

### ISSUE THREAD

**Issue by Mayonese** [Monika-After-Story/MonikaModDev#5503]
idk if it because you guys (the team that works in the mod) took all the clothes away or my game did something from the new update

**Comment by ThePotatoGuy** [comment]
The sprite system changed so you will need to update all of your spritepacks.

**Comment by Mayonese** [comment]
> The sprite system changed so you will need to update all of your spritepacks.

i need to give back to her or just change all the files again?

**Comment by ThePotatoGuy** [comment]
Just copy the files from the new spritepacks as if you were installing them. You should not have to regift.

**Comment by Mayonese** [comment]
> Just copy the files from the new spritepacks as if you were installing them. You should not have to regift.

ok thank you

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
