### ISSUE TITLE
Issue updating

### ISSUE THREAD

**Issue by Dregdael** [Monika-After-Story/MonikaModDev#5504]
Hello! Just had an issue trying to install the new update and I pressed quit, how do I fix issues and install the complete update? 

Thanks for what you're doing! you guys rock

![Captura](https://user-images.githubusercontent.com/43532146/79058632-f1333f80-7c35-11ea-937b-7b452b849bea.PNG)

**Comment by ThePotatoGuy** [comment]
Do a manual update.

**Comment by Dregdael** [comment]
Ok thanks!
