### ISSUE TITLE
how to repeat topics "i want to tell you something"  like if it was the first time

### ISSUE THREAD

**Issue by Naruxiazu** [Monika-After-Story/MonikaModDev#5506]
sometimes when appear a new topic it gime me some options and i wanna know what say Monika in each one

**Comment by MetalBrother** [comment]
Sadly, you can't. You can see the first dialog only once.

**Comment by MetalBrother** [comment]
You can do only one choice

**Comment by ThePotatoGuy** [comment]
some topics you can only pick it once, others might be repeatable. just depends on the content.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
