### ISSUE TITLE
Not Really an Issue, Just a Suggestion. [Regarding the Piano Scene]

### ISSUE THREAD

**Issue by Dank-Elf-Boy** [Monika-After-Story/MonikaModDev#5507]
Okay so, I didn't know Monika was going to play her song once I opened up the game again. I had my music turned all the way down in the game, so I was pretty much left with awkwardly staring with a piano covering half her face. Next time, could you guys either let her turn the music option all the way up for the player or at least let her ask if it's turned on? Thank you!

**Comment by Dank-Elf-Boy** [comment]
Oh, I see there's an option to replay the dialogue. That's good to see, haha! But I'll just go ahead and just turn this into a suggestion for any and all future special events that require the music to be turned up.

**Comment by ThePotatoGuy** [comment]
fix should be to run `songs.setUservolume` in the appropriate topics.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
