### ISSUE TITLE
Cant give monika hatsune miku cosplay

### ISSUE THREAD

**Issue by Geekyyy** [Monika-After-Story/MonikaModDev#5508]
i put the mod-assests from the sprite pack into the game folder and put the gift in the characters folder, monika says she found it but cant bring it here because she cant read it well enough?

**Comment by Dank-Elf-Boy** [comment]
Yeah, for some reason I can't recover any of my previous outfits. And to add to this problem, I goofed something up while messing with my files and then this happened...

![ErrorAA](https://user-images.githubusercontent.com/34694679/79064872-075ef100-7c72-11ea-8fed-dd65fa18dfaa.PNG)


Instead of creating another issue, I'll just piggy back off of yours.

**Comment by Geekyyy** [comment]
oh no! that sucks ;w; im not very good at coding so i cant help you-

**Comment by Dank-Elf-Boy** [comment]
Ah. Okay, I fixed my problem. [Just re-downloaded the latest update zip to override the files I messed up]

Now, I'll just wait and see what they say to do for our outfit issue. I just suck at putting files in the right place half the time lol smh.

**Comment by Geekyyy** [comment]
Epic! and tbh.. same lmao

**Comment by SamanthaLind** [comment]
I had the same issue but when I downloaded new spritepack it all started to work fine.
Could you check in "log" the file "spj" I believe it's the right name. It should tell you what's wrong

**Comment by ThePotatoGuy** [comment]
If you are having issues with spritepacks follow instructions [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by Geekyyy** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4466132/spj.txt)
uhhh i couldnt see any

**Comment by SamanthaLind** [comment]
Go to mod_assets, then "Monika" then "j" find file with Miku in name and in one of first few lines there should be "version:2" or something like that. Change 2 to 3, it worked for me

**Comment by Geekyyy** [comment]
She still cant read it, though now it says that the things already exist.

**Comment by Geekyyy** [comment]
Also, the hair change option dissapeared ramdomly, i didnt lose affection, how do i get it back? ;-;

**Comment by Booplicate** [comment]
> Go to mod_assets, then "Monika" then "j" find file with Miku in name and in one of first few lines there should be "version:2" or something like that. Change 2 to 3, it worked for me

Wtf? Don't do that. Just update your sprite packs.

**Comment by Geekyyy** [comment]
aaa how do i do that

**Comment by Booplicate** [comment]
Did you read [this](https://github.com/Monika-After-Story/MonikaModDev/issues/5508#issuecomment-612587748)?

**Comment by Geekyyy** [comment]
yeah- its just late and im confused lol

**Comment by Geekyyy** [comment]
nEVERMIND ITS FIXED!!

**Comment by Geekyyy** [comment]
aaaaandddddddd nevermind its not fixed- but i think i can solve this on my own

**Comment by Geekyyy** [comment]
but yeah i cant change her hair anymore? affection never went down

**Comment by Dank-Elf-Boy** [comment]
I wished they just added the sprites in with the main mod rather than making them a submod feature. I mean, you still have to gift her these outfits before you unlock them. Why not make it toware all the player has to do is enter the gift in the characters folder? The spritepack files (after unzipping) should be able to be copied and pasted effortlessly into the /game/mod_assets folder. The user shouldn't have to mess with the files and logs in order to get them to work, respectfully in my opinion.

**Comment by multimokia** [comment]
The point is so we're not increasing the mod size with outfits and accessories not everyone will use. Mod bloat makes it worse for people with lower end internet who wish to download it, plus it also means a bunch of extra sprites which may go unused. The best solution is to make them drop in, install on your own content. 

They're very forgiving, all it requires is a copy/paste of a ***single*** folder (`mod_assets` from the spritepack) into `/game` into your install), and then the copy/paste of a gift file into the characters folder. This is literally the simplest approach to this.

**Comment by ThePotatoGuy** [comment]
We dont include spritepacks in the main mod so users can pick and choose which ones they want. Right now theres only a few packs, but we're hoping to have tons of them in the future. Additionally, the system is mean to be expandable so people who arent us can make the appropriate files and add spritepacks without any sort of code. 

As multi mentioned, the `mod_assets` folder is all you need to copy and paste into the correct place so its pretty seamless on a per-spritepack level. We group all of them in one zip so you dont have to download a bunch of separate zips, but if people think that is more user friendly then we can swap to individual one zip per spritepack.

**Comment by Dank-Elf-Boy** [comment]
Okay, so I'm going to re-download the latest spritepack release and paste them into /game. If and when I can't unlock one of the outfits from simply entering in the correct gift, I'll begin posting screen shots for assistance.

**Comment by Dank-Elf-Boy** [comment]
Okay, so here we go. I'm going to walk you through my process lol.

**Sprite Pack is downloaded and unzipped**

![SP Issue 1](https://user-images.githubusercontent.com/34694679/79079195-41141400-7cd3-11ea-9080-a017f45d48c3.PNG)

**Sprite Pack files are then copied and pasted into the mod_assets folder**

![Mod asset issue 2](https://user-images.githubusercontent.com/34694679/79079207-5c7f1f00-7cd3-11ea-8cde-6c204c746f20.PNG)


**Snap shot of the mod_assets folder**
![Mod asset issue 3](https://user-images.githubusercontent.com/34694679/79079228-7de00b00-7cd3-11ea-88f2-40f0b73d294a.PNG)


**I selected an asset to gift Monika**
![Mod asset issue 4](https://user-images.githubusercontent.com/34694679/79079255-9e0fca00-7cd3-11ea-8a64-7e79863d15cf.PNG)


**This is a screen shot of my /characters folder with the gift inside**
![Mod asset issue 5](https://user-images.githubusercontent.com/34694679/79079287-dca58480-7cd3-11ea-8fd0-40ef1dc448a0.PNG)

**And this is the result**

![Mod asset issue 7](https://user-images.githubusercontent.com/34694679/79079305-f5159f00-7cd3-11ea-84f8-ac186e844e4d.PNG)

**Mod does not recognize the gift**

![Mod asset issue 6](https://user-images.githubusercontent.com/34694679/79079325-0c548c80-7cd4-11ea-8469-69e3fcebf7e2.PNG)

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/79079401-d2d44f00-7cdc-11ea-8689-c19361cd36a2.png)
this is incorrect. You did not copy the `mod_assets` folder from each of those folders into the `/game` folder of your install


Secondly, if you have spritepacks of `version 2`, then you have an outdated spritepack zip. But I'm assuming those are the old ones from before updating since these are not installed correctly.

**Comment by Dank-Elf-Boy** [comment]
I literally installed the sprite pack listed under the latest update? How is it out of date?

**Comment by multimokia** [comment]
>But I'm assuming those are the old ones from before updating ***since these are not installed correctly.***

**Comment by Dank-Elf-Boy** [comment]
Then how do I install them correctly?

**Comment by multimokia** [comment]
Inside each of those folders is a `mod_assets` folder. It is *that* folder you need to copy to your `/game` folder. Not the one containing it.

**Comment by Dank-Elf-Boy** [comment]
What about the gifts folders?

**Comment by multimokia** [comment]
You don't need to copy that. Just copy the gift *file* from inside it and place it in your `characters` folder.

**Comment by Dank-Elf-Boy** [comment]
Ahhhh. Okay, I got it! Yeah, I didn't think about going into each file and dragging the mod_assets file and merging them with the mod's mod_assets file. Haha, sorry for the head ache man, sometimes I get boomer moments when it comes to this stuff. But anyways, thank you for the support!
