### ISSUE TITLE
Getting an error screen when saying goodbye or asking for changing clothes

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#5509]
![Screenshot_1](https://user-images.githubusercontent.com/45933038/79065002-a523e180-7cad-11ea-8e1f-dcd45a55cc78.png)

It appears to be related to one of the Halloween costumes, the one I haven't unlocked.
I've updated the spritepacks, and the game seems to continue working as normal when choosing to ignore the error.

Edit : apparently, the error pops up randomly every now and then, even without input.

**Comment by ThePotatoGuy** [comment]
upload your persistent

**Comment by fromulus** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4466110/persistent.zip)

**Comment by Booplicate** [comment]
Looks similar #5463

**Comment by ThePotatoGuy** [comment]
Probably is that since I cant remember ever putting the rin clothes in a conditional.

**Comment by fromulus** [comment]
Yeah, I have the auto hair change submod installed.
After updating it, the error seems to be gone.
Thanks for the help and apologies for the inconvenience caused.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
