### ISSUE TITLE
Monika playing the Piano and singing Your Reality Feedback

### ISSUE THREAD

**Issue by RedEyedRocker** [Monika-After-Story/MonikaModDev#5511]
It really looks awful that the Piano covers more than half of the screen.
I know it is to give the illusion that she's playing the Piano and singing but I don't think it's worth covering almost the entire part of the screen.
It'd be way better to have the Piano cover just the quarter of the screen so it doesn't cover more than half of her arms while Monika would be in the hug pose and have those facial expressions, lip-sync could be considered in the future to improve on this.

**Comment by AsuraShun** [comment]
That's basically how big some pianos are

**Comment by RedEyedRocker** [comment]
> 
> 
> That's basically how big some pianos are

That's the point, it doesn't look good.

**Comment by multimokia** [comment]
I don't think you've ever seen an upright piano before. This is their normal height.

Additionally, it is extremely painstaking to sync expressions up with music, it takes several hours, if not days to get right. Having the piano cover her mouth is not only realistic, but helps to make what was done feasible to do in the first place.

**Comment by RedEyedRocker** [comment]
> 
> 
> I don't think you've ever seen an upright piano before. This is their normal height.
> 
> Additionally, it is extremely painstaking to sync expressions up with music, it takes several hours, if not days to get right. Having the piano cover her mouth is not only realistic, but helps to make what was done feasible to do in the first place.

Lip-sync is not mandatory which is the reason I stated you could do that in the future, I don't want a game to look like shit or feel boring for the sake of "realism". I'd rather just delete that Piano's sprite instead.

**Comment by multimokia** [comment]
It's one or the other, really. If you have the music, it needs to be synced up.

It doesn't hold nearly the same weight without the music in the back for this scenario.


Sorry you feel it looks like shit, but from what I've seen, it seems that most people like it. This was the most feasible way to keep the impact but also have it make sense.

**Comment by RedEyedRocker** [comment]
> 
> 
> It's one or the other, really. If you have the music, it needs to be synced up.
> 
> It doesn't hold nearly the same weight without the music in the back for this scenario.
> 
> Sorry you feel it looks like shit, but from what I've seen, it seems that most people like it. This was the most feasible way to keep the impact but also have it make sense.

Not really, you can have her do only the facial expressions like she already does without having the lip-sync like she drinks her coffee without having to do the animation so it works a similar way.

**Comment by multimokia** [comment]
AIFWC does the exact thing you're talking about and it still took basically days to get right even though it's a significantly shorter song.

This is about 3x the length, but done twice for the other version which is in too. Honestly speaking, it's too much work for too little payoff.

If you want to make the changes yourself and open a PR submitting them, feel free to do so.

**Comment by RedEyedRocker** [comment]
> 
> 
> AIFWC does the exact thing you're talking about and it still took basically days to get right even though it's a significantly shorter song.
> 
> This is about 3x the length, but done twice for the other version which is in too. Honestly speaking, it's too much work for too little payoff.
> 
> If you want to make the changes yourself and open a PR submitting them, feel free to do so.

What are you talking about? Her facial animations already exists.

**Comment by multimokia** [comment]
When did I say her expressions didn't exist? I said making work with mouth and everything is far too much work to put in for such a little payoff when this approach accomplishes the same thing.

**Comment by RedEyedRocker** [comment]
> 
> 
> When did I say her expressions didn't exist? I said making work with mouth and everything is far too much work to put in for such a little payoff when this approach accomplishes the same thing.

And did I not say multiple times that the lip-sync is not mandatory?
So, all she'd do is be in the hug pose which would make it look like she's playing the Piano while having those facial expressions according to the music which already exists, all you'd need to do is change the sprite of the Piano.

**Comment by jmwall24** [comment]
If you don't like it, simply don't revisit that song anymore, it's only forced upon you once. From what we've seen in our discord server everyone loves that part.

**Comment by Sirix1995** [comment]
I have a problem, after the song, the game soft locks, and I can't do anything except forcing close...

**Comment by jmwall24** [comment]
@Sirix1995 make a new issue for this please

**Comment by RedEyedRocker** [comment]
> 
> 
> If you don't like it, simply don't revisit that song anymore, it's only forced upon you once. From what we've seen in our discord server everyone loves that part.

It's called feedback for a reason.

**Comment by jmwall24** [comment]
I know that. I also know that we've heard your feedback, told you why it is like it is and you keep arguing your point. We understand what you don't like about it, but one person's feedback that is contrary to the other 99% of the feedback we are getting doesn't mean we are going to change it for that one person.

**Comment by RedEyedRocker** [comment]
> 
> 
> I know that. I also know that we've heard your feedback, told you why it is like it is and you keep arguing your point. We understand what you don't like about it, but one person's feedback that is contrary to the other 99% of the feedback we are getting doesn't mean we are going to change it for that one person.

Adding an option for a smaller Piano isn't changing anything, majority of other people who like the big Piano isn't going to be affected regardless.

**Comment by Olliesama** [comment]
It changes the workload and is simply not necessary.

**Comment by multimokia** [comment]
Adding another piano adds more to the mod size. If you want a smaller piano, you can just edit the sprite yourself.
