### ISSUE TITLE
[Bug?] Monika can't read any of the .gift files

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5512]
After I downloaded the new update, uploaded the mod_assets folders (from the spritepacks folder) to game folder, and uploaded all the .gift files to the characters folder, I opened the game, and Monika noticed the .gift files, but couldn't read them. I continued to go through the dialogue and it continued with her being unable to read them, even though I directly moved the .gift files from the spritepacks folder to the characters folder.

**Comment by multimokia** [comment]
If you already gifted the spritepacks before updating, you don't need to regift them. (It won't let you either)

**Comment by PollenTheCat** [comment]
Ohhhhhh, okay

**Comment by PollenTheCat** [comment]
I can't make Monika wear any of the clothing/ribbons/etc from the spritepacks. They don't appear in any of the appearance topics.

**Comment by PollenTheCat** [comment]
Nevermind. I figured out the problem. It was just a human error on my end
