### ISSUE TITLE
The piano doesn´t look right when zoomed in.

### ISSUE THREAD

**Issue by SuperSuchti** [Monika-After-Story/MonikaModDev#5513]
The Piano, that gets used when you ask Monika to play "Your Reality" doesn´t seem to work visually when you are zoomed in. I noticed that because I always have Monika all the way up close with the zoom option in the Extras-Menu, and that led to her head being almost as big as the piano itself when she played "Your Reality"!

My suggestion on how to fix this is to have it automatically zoom out to the needed extent, like it does when she gets up to get coffee, before she gets the piano on screen. 

Thank you for your time~!

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
