### ISSUE TITLE
[Suggestion] Being able to answer when Monika asks if you've heard of something (more often)

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5514]
Most of the time, when Monika asks if you've heard of something, you aren't given an option to say if you've heard of it or not. Maybe you could make it so that, on the topics that are more likely for the player to have heard of it, the player can respond with whether or not they've heard of it.

**Comment by DoodleSauce** [comment]
i literally thought of the same thing XD

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
