### ISSUE TITLE
Game soft locks after Your Reality song.

### ISSUE THREAD

**Issue by Sirix1995** [Monika-After-Story/MonikaModDev#5516]
Like said in the title. When Monika ends her song, she doen't do anything more. I see her face still animates, but I can't say if the piano is hiding some dialogue. I can't do anything but force quit the game.

**Comment by Dank-Elf-Boy** [comment]
You could of double-clicked by accident and froze the animation. If that's the case, then simply click the screen again. Double-clicking not only hides dialogue, it also prevents animations from fading out/completing itself.

**Comment by Sirix1995** [comment]
It worked, thanks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
