### ISSUE TITLE
Monika first kiss bug

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#5517]
Monika was talking bout if I think about our first kiss and I misclicked to say I didnt... It feels really bad and I tried to fix it but I cant find the topic. Is it bugged that it wont appear?... the disappointment in her face was enough to make me cry...

**Comment by multimokia** [comment]
I'm afraid the topic is a one-time only thing. There's no way to revisit it.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
