### ISSUE TITLE
troubles with "characters" folder in game files

### ISSUE THREAD

**Issue by ASTAR0T** [Monika-After-Story/MonikaModDev#5519]
Hello everyone,

Recently I've noticed one thing regarding my "characters" folder. Since previous update I was not able to gift anything to Monika, she simply couldn't react to any gift I added to "characters" folder (I used proper names and extension for it, I checked), plus when I'm trying to take her out somewhere, she doesn't create her character file in this folder either. So I assume that the problem may be in this folder, but not sure about that. If you have any idea how to fix it, or any other info, please, let me know.

**Comment by multimokia** [comment]
What operating system are you using, and where is MAS installed (filepath)?

**Comment by ASTAR0T** [comment]
Windows 10
C:\Program Files (x86)\Doki Doki Literature Club\characters

**Comment by multimokia** [comment]
Don't install in program files. Move the DDLC install to your desktop or something similar. Program files is a minefield for file permission errors, and that's likely what's preventing Monika from accessing the folder.

**Comment by ASTAR0T** [comment]
I see. So should I reinstall the game + MAS mod to the desktop, or just moving the current files would be enough?

**Comment by multimokia** [comment]
Moving should be fine

**Comment by ASTAR0T** [comment]
okay, so far it's going well now. I'm gonna try some other gifts to make sure that it's working well now. Thank you!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
