### ISSUE TITLE
What solution is there to fix this update problem or is it something else please tell me how to fix this in Monika After Story 

### ISSUE THREAD

**Issue by Dude3cpo** [Monika-After-Story/MonikaModDev#5523]
![image](https://user-images.githubusercontent.com/63556582/79076279-dc52bc80-7cc6-11ea-9ec7-9a3d2e551177.jpg)

**Comment by multimokia** [comment]
Can you send a screenshot of your `\game` folder, please?

**Comment by Dude3cpo** [comment]
![8D23579C-E12E-47A8-8B24-407FEA9DB536](https://user-images.githubusercontent.com/63556582/79076838-0ad29680-7ccb-11ea-960f-e938d48a3908.jpeg)
![Uploading EAC5F735-D38B-4BCB-BE9D-C17EA1B0AC25.jpeg…]()

**Comment by Dude3cpo** [comment]
I’ve sent it

**Comment by Dude3cpo** [comment]
The picture of the game folder I meant

**Comment by Dude3cpo** [comment]
Uhm is this the problem
![B78B8DDE-CB9F-4FC7-AEB8-7C582AFA83DF](https://user-images.githubusercontent.com/63556582/79078061-c7305a80-7cd3-11ea-88b2-3a4e681021ca.jpeg)

**Comment by multimokia** [comment]
I need to see filepaths here

**Comment by Dude3cpo** [comment]
It is the common file

**Comment by ThePotatoGuy** [comment]
check step 4 of https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-still-cant-run-the-game-and-none-of-the-above-faqs-solve-my-issue

**Comment by Dude3cpo** [comment]
I managed to fix the problem it was the rpa’s file that were missing

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
