### ISSUE TITLE
gifts problem

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#5524]
After adding all the files in the appropriate places, i added the gift in the character files 
the only thing that was gifted was the hatsuni miku cosplay clothes, the rest were all unseen. 
please help

**Comment by ThePotatoGuy** [comment]
did you update your spritepacks? follow troubleshooting checklist [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by loverofmonika** [comment]
i did, also i followed the checklist, it worked. i downloaded it whilst having MAS open, that was the issue.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
