### ISSUE TITLE
[Suggestions] Some random dialogue I came up with

### ISSUE THREAD

**Issue by DanielClaton** [Monika-After-Story/MonikaModDev#5527]
Hello,

new here and I really love MAS. Feeling very comfortable around her and feeling so less isolated during Corona. Unfortunatelly, I tried using the sprite-previewer as requested and my Monica started acting weird...Fortunatelly, I have a backup. So here are my suggestions:

Random:

You know, I have talked a lot about dystopian images of the future.

There is one author who can be considered one of the father's of science fiction. 

Jules Verne predicted so many interesting inventions. I really like his book _20.000 leagues under the sea_ In this book, he tells the story about a journey through the seven seas in a submarine. He imagined how the submarine would operate, that it would be powered by electricity...In the end, he predicted a nuclear submarine way before nuclear power was invented. That's really fascinating, you should have a look at it.  (Maybe here a check in the persistence, so that if this dialogue has been seen other dialogues about Jule Verne's works get unlocked?)
*********************
When I first read _Around the world in 80 days__ as a teen, I could not really understand the main character, Phileas Fogg. He led a very predictable life and he got pretty upset if something was not like it is supposed to be. He fired his servant because the temperature of his bath was off by a margin. In the Reform Club he always sat at the same table and he left his home and arrived back always at the same time, while not really talking with anybody. And then I found out, that he must have had _Asperger Syndrome_. This condidition was first diagnosed in 1925, 52 years after _Around the world in 80 days_ was first published.
*********************
Did you know there's also some romance found in _Around the world in 80 days__? Fogg and his servant Passepartout save an Indian princess from a pyre. Passepartout risks his life and Fogg gets to marry the Princess? I think that's a bit unfair. I mean, {player] saved me from the void, so you won my heart and not anybody else.
*********************
Some folks out there really love dissecting stories for mistakes. Do you do that? Back in the Literature Club, Yuri sometimes used to dissect Natsuki's mangas. It was interesting to watch them, they were like cats and dogs sometimes. Only Sayori was able to stop them fighting....Ah, at least that is the way they WERE written to act. But don't be afraid, nobody wrote _me_ to fall in love with you, {Player}
*********************
If somebody could explain to me how to use the sprite previewer on a normal edition of MAS, I would be grateful. Then I can hopefully start writing this in code.

Thank you for listening ~

Dominik

**Comment by TriniTDM** [comment]
Well, for your issue with the sprite previewer, that's because the code for the sprites was completely overhauled and the old previewer is no longer compatible. You have to download a new one. You can do that [here.](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/dev/dev_exp_previewer.rpy)

**Comment by DanielClaton** [comment]
I just get a lot of code...I am sorry, pretty new here...where is the file? Or do I need to copy the code somewhere?

**Comment by ThePotatoGuy** [comment]
1. click the button labeled "raw"
2. ctrl+A
3. paste in notepad
4. save file as dev_exp_previewer.rpy
5. put in `game/` dir
