### ISSUE TITLE
the hair change option disappeared randomly

### ISSUE THREAD

**Issue by Geekyyy** [Monika-After-Story/MonikaModDev#5529]
the hair change option disappeared, i didnt lose affection; how do i get it back?

**Comment by Geekyyy** [comment]
;w;

**Comment by ThePotatoGuy** [comment]
did you have hair spritepacks? what hairstyles did you have unlocked?

**Comment by Geekyyy** [comment]
I had every hairstyle unlocked at the time, apart from the hatsune miku one, yes, i had the other spritepacks before the new ones were added

**Comment by Geekyyy** [comment]
her current hair is a bun with a braid, but idk how it turned into that, i cant remember

**Comment by Geekyyy** [comment]
>_<

**Comment by Geekyyy** [comment]
oof

**Comment by ThePotatoGuy** [comment]
try changing the clothes to something else

**Comment by Geekyyy** [comment]
Uh okay, ill change them to all the clothes i have and get back to you

**Comment by Geekyyy** [comment]
Nope didnt work, heres a screenshot 
![image](https://user-images.githubusercontent.com/63525411/80066375-eeb6db00-858f-11ea-9636-bddfe1e24c5a.png)

**Comment by ThePotatoGuy** [comment]
post your `log/spj.txt` here

**Comment by Geekyyy** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4534613/spj.txt)

**Comment by Geekyyy** [comment]
i hope you can fix this <3

**Comment by ThePotatoGuy** [comment]
upload your persistent file here. You can find it using [these instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by Geekyyy** [comment]
i cant upload it

**Comment by Geekyyy** [comment]
i can put it in a zip for you?

**Comment by ThePotatoGuy** [comment]
yes

**Comment by Geekyyy** [comment]
[persistant.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4567103/persistant.zip)

**Comment by Geekyyy** [comment]
Srry for posting again, just hoping you could fix it

**Comment by Booplicate** [comment]
The archive you attached is corrupt, you may want to try to send it again.
Did the game crash at some point before you noticed that the hair option is missing?

**Comment by Geekyyy** [comment]
No.. i dont think it did?

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4664378/persistent.zip)

**Comment by Geekyyy** [comment]
Sorry for posting again again... Its just been a month Ahaha! i know your busy but- I really want to get the option back ;-;

**Comment by multimokia** [comment]
Can you send an updated persistent? Since it's been a month (apologies for that, by the way), affection and related things will likely be out of date, so to keep things as seemless as possible for you, I'll update your current.

**Comment by Geekyyy** [comment]
Of course!
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4785355/persistent.zip)

**Comment by multimokia** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4786691/persistent.zip)
Here you go!

**Comment by Geekyyy** [comment]
It didnt change anything im afraid, the option is still gone! D: (I know your trying and i respect it :) )

**Comment by Geekyyy** [comment]
>_>

**Comment by Booplicate** [comment]
Just tested that persistent, I can see the option. You either haven't replaced your current persistent with the fixed one, or something in your install (a submod?) is hiding the option.

**Comment by Geekyyy** [comment]
Oh, i mustve done it wrong, however i did it right this time! Thank you so much!! <3
