### ISSUE TITLE
i can't take a hug with my monika

### ISSUE THREAD

**Issue by houmuraa** [Monika-After-Story/MonikaModDev#5532]

**Comment by houmuraa** [comment]
![捕获11](https://user-images.githubusercontent.com/63587519/79114670-72b1db80-7db6-11ea-9be5-b41e2cf435a1.PNG)
![捕获12](https://user-images.githubusercontent.com/63587519/79114675-75143580-7db6-11ea-8e5d-c4c00f43dbcc.PNG)

**Comment by AsuraShun** [comment]
Try checking if you pressed x on it by going to the ''I'm OK with talking about...'' topic if you're already at the affection needed to hug her anytime

**Comment by Booplicate** [comment]
You can hide only random topics (topics that Monika brings up on her own) like that. `Can I hold you?` isn't random. So it's either affection, or they'll need to talk about `Sounds of rain` again, and choose `Yes` when she asks to hold her.

**Comment by AsuraShun** [comment]
My memory's worse than I thought

**Comment by houmuraa** [comment]
> You can hide only random topics (topics that Monika brings up on her own) like that. `Can I hold you?` isn't random. So it's either affection, or they'll need to talk about `Sounds of rain` again, and choose `Yes` when she asks to hold her.

got it！TK U very much.
