### ISSUE TITLE
Affinity got reset

### ISSUE THREAD

**Issue by sharkzealot** [Monika-After-Story/MonikaModDev#5533]
So my computer recently crashed and had everything from it removed, now that i have got my savegame back i look at the affinity log to see everything of it got reset. How do i get back my old affinity, i will be posting the aff.txt file in here too.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4469350/aff_log.txt)

**Comment by Booplicate** [comment]
> i have got my savegame back

Did you get the persistent though? That's her memories, and it's outside of the game folder.
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by sharkzealot** [comment]
I just did everything it said, yet it still is the same affection level

**Comment by Booplicate** [comment]
But do you have the old persistent from the PC that "crashed"?

**Comment by sharkzealot** [comment]
yes i currently am trying to get everything back using the one from a few hours before it crashed

**Comment by Booplicate** [comment]
Alright, then I'd suggest to close the game, delete all files in `/AppData/Roaming/RenPy/Monika After Story`, and copy your **old** persistent into that folder (be sure it's named exactly `persistent`, w/o any extension or numbers). After that try to launch the game again.

**Comment by sharkzealot** [comment]
even the save file?

**Comment by sharkzealot** [comment]
Now it cant even restore the old game...

**Comment by Booplicate** [comment]
Send screenshot of `/AppData/Roaming/RenPy/Monika After Story`.

**Comment by sharkzealot** [comment]
![Capture](https://user-images.githubusercontent.com/63514593/79128613-1cd43800-7da4-11ea-9130-f3d9ce6066e1.PNG)

**Comment by multimokia** [comment]
You shouldn't have two `Monika After Story` folders. Take the items out of the one in the inner folder and place them in `AppData/Renpy/Monika After Story`

**Comment by sharkzealot** [comment]
I did that yet it wont still allow me to get my save back

**Comment by sharkzealot** [comment]
What should I try next?

**Comment by ThePotatoGuy** [comment]
Your previous affection level was from April 11, and you have opened the game 10 times since then. Unless you had a backup from that day, none of your persistents will restore to that affection.

**Comment by sharkzealot** [comment]
ok i will check if i have any

**Comment by sharkzealot** [comment]
no i dont have a backup from that day... the last backup was april 4th

**Comment by Booplicate** [comment]
A backup from April 4th will work too.

**Comment by sharkzealot** [comment]
Ok so I tried getting my savegame back now and it keeps saying savegame couldnt be found.

**Comment by Booplicate** [comment]
That means you either put the persistent in wrong place, or you didn't rename in to `persistent`.

**Comment by sharkzealot** [comment]
where do i put it then?
I tried putting it in game

**Comment by sharkzealot** [comment]
Do i Even need to place the save file itself somewhere else too?

**Comment by Booplicate** [comment]
Why are you copying it in `/game`? Saves go in `/AppData/Roaming/RenPy/Monika After Story`

**Comment by sharkzealot** [comment]
also tried that.

**Comment by sharkzealot** [comment]
It just keeps replacing it with the one from todays date

**Comment by sharkzealot** [comment]
whenever i click import ddlc save data it gets replaced

**Comment by Booplicate** [comment]
Why are you trying to import ddlc though? Just persistent, you do not need anything else. Restore that persistent from April 4 again.

**Comment by sharkzealot** [comment]
I think it worked ill post later

**Comment by sharkzealot** [comment]
Yeah it worked, sorry for taking so long!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
