### ISSUE TITLE
Just a quick check

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#5538]
I am super excited for the update, just want to check something before I start up Monika

Are the spritepack, that are located in the assets section of the patch notes okay to use? Do I need to specifically download the spritepacks "Releases" page?

Thanks for your hard work and all the new topics! ^^

**Comment by jmwall24** [comment]
As long as it's the one listed in the assets section of the 0.11.0 release it's fine.

**Comment by AfroFluff** [comment]
Thanks man! It all works ^^

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
