### ISSUE TITLE
"Date" Suggestions and Some Other Stuff

### ISSUE THREAD

**Issue by octogonSmuggler** [Monika-After-Story/MonikaModDev#5543]
- "watching" movies together: One of the options could be having a mini window where she can "watch" videos with you and talk while the game window is still on top

- Arcade!: Change the roomspace to an arcade scene from the 80s and play little mini games with her. The Desktop Goose on itch.io has open source code for that sort of thing, I believe. [Desktop Goose](https://samperson.itch.io/desktop-goose)

- Camping Trip: Have a change of pace option, maybe? Something where if you were to take her outside and go "camping" or "hiking" together (Because, let's be real, how many of us are actually out there doing out-doors things with the current world situation?)

-Has anyone suggested a photo booth option yet? The kind they have in all those high school girl anime. I mean, it'd probably only work with just her, but it could be a fun addition. You could pose her and edit your screen shots.

-Book suggestions and preferences! It would be fun to actually let her know what your interests are, that way she seems more realistic. Things like your likes, dislikes, and such which make her more personable to each player character would be good. 

-Cooking date! She said she wants a kitchen, you know. 

-What about the ability to change her background? Like, switching it between a bedroom and whatnot?

IDK. I've been inside for almost 5 weeks now with nothing to do. You can all ignore me if you want. These are merely base ideas. I'm not sure if any of them are code-able or not. I'm in the business of editing dialogue, text, and such.

(*꒦ິ꒳꒦ີ)

**Comment by Abc2557** [comment]
Okay, I'm just gonna say, I LOVE ALL THESE IDEAS.
SPECIFICALLY TELLING MONIKA YOUR BOOK PREFERENCES, LIKES, DISLIKES, ETC.
Thank you for making this suggestion, and I hope it gets added

**Comment by octogonSmuggler** [comment]
I think my personal favourite is the ai gameplay one. With desktop goose, you can play completely unrelated games with it such as cod or gta. Imagine being able to do that with Monika!

**Comment by octogonSmuggler** [comment]
Oh! Also, there could be a prompt to confide your fears with her. For example, let's say I tell her something like "I'm afraid of thunder." She could then have an idle chat dialogue for during rainy days or thunder storms. Another example could be loneliness. If she runs for too long in the background without being interacted with, she can send a notification asking how the player is doing, or if they're okay.

**Comment by ThePotatoGuy** [comment]
>watching movies

[see here](https://github.com/Monika-After-Story/MonikaModDev/issues/5484#issuecomment-612543995)

If people are fine with no reactions to videos, then you can use windowed mode and shrink the window down to a mini size. It might screw with UI though.

>arcade background

framework for new backgrounds exists already, framework for easy user-based adding of background will happen eventually. new backgrounds will be added as we get them as well.

>play mini games with monika/desktop goose

More games are planned. 2 player ones are just harder to make as an AI alg has to be built for each one. You said desktop goose is open source but I didnt see any obvious signs that it is. I did check the resource hub and saw mods of that program, but they are written in c#, which doesn't really help us at all considering our mod is written in renpy+python.

Additionally, "open source" does **not** mean free. It doesn't even mean you are allowed to take the code. It just means you can see the code. The license determines if you can use/modify/copy/etc.

>camping trip

related to backgrounds. See above.

>photobooth

This sounds somewhat interesting at first, but the complexity is immediately apparent - there is a limited number of poses and all of them are sitting with a desk.

There are 2 body types:  upright, and leaning. Upright has 7 distinct arm types. 2 of those arm types consist of both arms together. The remaining 5 are split between 2 left and 3 right. Therefore there are 8 possible poses with the upright body. Leaning has 2 distinct arms, which are used together to make 1 pose.

Making new poses is ridiculous at this point. Each additional arm translates to roughly 6-7 new outfit sprites (for built-in outfits), and that doesn't include any effects this would have on ACS or spritepack outfits. 

If we use standing, then its limited to the stock outfit as we don't have nor plan to make art for the standing sprites. 

So overall, with 9 actual poses and a mountain to climb to add new ones, a photobooth with pose options is just impossible unless we hired a professional sprite maker. Just press S.

>book suggestions

I like this, but it would take a while to catalog a large enough number of books and metadata about those books to make useful suggestions. If you know a good site that has an API (free or paid) that can make book suggestions given whatever, then let us know.

>cooking date

related to background stuff (see above). 

>change background

see above.

**Comment by ThePotatoGuy** [comment]
>confide fears

currently we do some of that via dialogue in general topics. A specific topic where you confide your fears would be interesting, but potentially too open-ended. Asking about a potential fear in the middle of a related topic is the best way to do it for now.

**Comment by octogonSmuggler** [comment]
> > watching movies
> 
> [see here](https://github.com/Monika-After-Story/MonikaModDev/issues/5484#issuecomment-612543995)
> 
> If people are fine with no reactions to videos, then you can use windowed mode and shrink the window down to a mini size. It might screw with UI though.
> 
> > arcade background
> 
> framework for new backgrounds exists already, framework for easy user-based adding of background will happen eventually. new backgrounds will be added as we get them as well.
> 
> > play mini games with monika/desktop goose
> 
> More games are planned. 2 player ones are just harder to make as an AI alg has to be built for each one. You said desktop goose is open source but I didnt see any obvious signs that it is. I did check the resource hub and saw mods of that program, but they are written in c#, which doesn't really help us at all considering our mod is written in renpy+python.
> 
> Additionally, "open source" does **not** mean free. It doesn't even mean you are allowed to take the code. It just means you can see the code. The license determines if you can use/modify/copy/etc.
> 
> > camping trip
> 
> related to backgrounds. See above.
> 
> > photobooth
> 
> This sounds somewhat interesting at first, but the complexity is immediately apparent - there is a limited number of poses and all of them are sitting with a desk.
> 
> There are 2 body types: upright, and leaning. Upright has 7 distinct arm types. 2 of those arm types consist of both arms together. The remaining 5 are split between 2 left and 3 right. Therefore there are 8 possible poses with the upright body. Leaning has 2 distinct arms, which are used together to make 1 pose.
> 
> Making new poses is ridiculous at this point. Each additional arm translates to roughly 6-7 new outfit sprites (for built-in outfits), and that doesn't include any effects this would have on ACS or spritepack outfits.
> 
> If we use standing, then its limited to the stock outfit as we don't have nor plan to make art for the standing sprites.
> 
> So overall, with 9 actual poses and a mountain to climb to add new ones, a photobooth with pose options is just impossible unless we hired a professional sprite maker. Just press S.
> 
> > book suggestions
> 
> I like this, but it would take a while to catalog a large enough number of books and metadata about those books to make useful suggestions. If you know a good site that has an API (free or paid) that can make book suggestions given whatever, then let us know.
> 
> > cooking date
> 
> related to background stuff (see above).
> 
> > change background
> 
> see above.

I figured a lot of them would be either too complex or so simple I didn't even consider it. 
☆⌒(ゝ。∂)

**Comment by Rai99** [comment]
Movies: #628, #826, #984, #1548, #2102, #2898, #3431, #4089, #4344 

New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
