### ISSUE TITLE
Where do I put spritepacks?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5544]
Sorry if this was posted somewhere, but I don't know how to search on this website..

**Comment by multimokia** [comment]
See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by Mcmanybucks** [comment]
I did copy "Mod Assets" and paste it in to \game, but they didn't show up..

**Comment by multimokia** [comment]
Did you do it while MAS was open?

**Comment by Mcmanybucks** [comment]
No.

**Comment by ThePotatoGuy** [comment]
Follow the troubleshooting checklist below the FAQ link.

**Comment by Mcmanybucks** [comment]
Ah I had to add the gifts? but I didn't get a gift prompt.. o.O

**Comment by multimokia** [comment]
There has never been a gift prompt?

**Comment by Mcmanybucks** [comment]
No? is it only for birthday and christmas? like when I gave her the bird plushy she opened a pack and was like "oh thanks!"

**Comment by multimokia** [comment]
Wait, what do you mean by prompt?

**Comment by Mcmanybucks** [comment]
Maybe its the wrong word, sorry it's early and I'm not natively english lmao.


Like, when I gave her the plushy I added a quetzal.gift file to her folder, she noticed and was like "oh, a present?"

**Comment by jmwall24** [comment]
send spj.txt please. it's in the log folder

**Comment by jmwall24** [comment]
oh, say goodbye before you do so

**Comment by Mcmanybucks** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4479051/spj.txt)

**Comment by jmwall24** [comment]
Sorry, i meant say goodbye to Monika before you send it, not close this haha

**Comment by Mcmanybucks** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4479058/spj.txt)

**Comment by Mcmanybucks** [comment]
Yea misclick lmao

**Comment by jmwall24** [comment]
Ok, are you putting the gift files in the characters folder or the gift folder? so like for the pink shirt, pinkshirt.gift should be in the characters folder, so `characters/pinkshirt.gift` not `characters/gifts/pinkshirt.gift`

**Comment by Mcmanybucks** [comment]
Yea I put it in the characters folder like the guide said, and pinkshirt did show up.. but Trilasentchoker didn't.

**Comment by jmwall24** [comment]
is that choker gift still in the characters folder? if so can you send a screenshot?

**Comment by Mcmanybucks** [comment]
![billede](https://user-images.githubusercontent.com/43464011/79297696-362dcf00-7edf-11ea-8b9d-f24021aed46e.png)
highlighted files show up, the rest dont

**Comment by jmwall24** [comment]
ok, all of those files are in the wrong folder, they need to be in `characters/` not in `characters/gifts`

**Comment by Mcmanybucks** [comment]
Ah.. they just sorta created the gifts folder as I pasted, thought that was suppoed to happen.

**Comment by jmwall24** [comment]
nah, you need to copy the gift files that are inside the gift folder of each sprite pack, not the entire folder

**Comment by Mcmanybucks** [comment]
Aah, gotcha.. yea she noticed it all now! thanks :D

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
