### ISSUE TITLE
[Question] Topic labels for topics about the player

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5547]
In the Dialogue Coding page on the MAS GitHub Wiki, it states that topic labels usually have monika_ at the beginning. Would this be different for topics about the player? If so, what would it usually have at the beginning?

**Comment by multimokia** [comment]
If it's a topic she brings up which you can see again (via `Hey [m_name]` or `Repeat Conversation`), then it will still be prefixed with `monika_`.

Some examples are `monika_playersface`, `monika_players_control`, `monika_player_appearance`, etc.

**Comment by Abc2557** [comment]
Ah, okay. Thank you!
