### ISSUE TITLE
No Window Reactions

### ISSUE THREAD

**Issue by Arisu-oss** [Monika-After-Story/MonikaModDev#5549]
Ran in Windows 10, MAS latest unstable.

![image](https://user-images.githubusercontent.com/39315312/79370184-872adb00-7f52-11ea-99f9-a0adbdab0a46.png)
![image](https://user-images.githubusercontent.com/39315312/79370199-8c882580-7f52-11ea-9c6b-e14f96a90847.png)

I run vivaldi as my browser, its handle does display the name on the page, but Monika won't react.

**Comment by multimokia** [comment]
You have `Use Notifications` disabled. They won't run.

**Comment by Arisu-oss** [comment]
I'm so dumb, thank you

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
