### ISSUE TITLE
The ability to change Monika's hair color

### ISSUE THREAD

**Issue by Silvery55** [Monika-After-Story/MonikaModDev#5550]
For a long time I always wanted Monika to fully Change her hair color. 

Since last year she wore a Miku costume I feel like this should be possible at least to change the color of hair by maybe using a color filters or change the color of hair Sprite.

At least this will give some way to customize her looks a bit without making a big change

**Comment by AsuraShun** [comment]
One does not simply mess with perfection

**Comment by lunulae** [comment]
A few dye colors for cosplay and such might be cool.

Something to keep in mind is that this would kind of operate like making a new hairstyle entirely, making a new set of sprites with the edited color. As such it might be easier (and less bloat in the hairstyle selector) to make these for specific hairstyles (i.e. making Miku-blue twintails and/or a blonde version the Marisa hairstyle, rather than variations for every single hairstyle.)

If I tried to make the Miku one, I might try to make an alternate .json for the Miku costume so people could decide whether or not to use the dye color in Outfit Mode.

**Comment by octogonSmuggler** [comment]
What about makeup options, or nail polish colours? I could easily go into photoshop and work up the art for it if someone else does the coding. We could have a makeover prompt or something.

**Comment by octogonSmuggler** [comment]
Makeup and nail polish would be considerably easy to create as overlays.

**Comment by ThePotatoGuy** [comment]
Currently you can add colored hair as additional hairstyle spritepacks. 

>Makeup and nailpolish

Blush-style makeup is easy. lip/eyes is not. There is no mapping for facial expressions and there will not be for some time.

Nail polish should be an ASE ACS.

**Comment by octogonSmuggler** [comment]
![face-mouth-smile_pink](https://user-images.githubusercontent.com/63683308/79388531-1b854580-7f33-11ea-8e19-d045f9cc1aa0.png)

![face-eyes-normal](https://user-images.githubusercontent.com/63683308/79393456-fe547500-7f3a-11ea-9fa1-7e222cf97743.png)

![arms-steepling-10](https://user-images.githubusercontent.com/63683308/79395858-301c0a80-7f40-11ea-8ec8-555b17d4916f.png)

![hair-orcaramelo_usagi-front](https://user-images.githubusercontent.com/63683308/79395866-3611eb80-7f40-11ea-87cb-283057658569.png)

![hair-orcaramelo_usagi-back](https://user-images.githubusercontent.com/63683308/79395868-390cdc00-7f40-11ea-9fca-782fe94571b8.png)



Does this look okay to anyone??

**Comment by octogonSmuggler** [comment]
> Currently you can add colored hair as additional hairstyle spritepacks.
> 
> > Makeup and nailpolish
> 
> Blush-style makeup is easy. lip/eyes is not. There is no mapping for facial expressions and there will not be for some time.
> 
> Nail polish should be an ASE ACS.

Photoshop is my jam, so if you ever want me to edit sprites for public use, hit me up. (ﾉ๑˘︶˘๑)ﾉ*: ･ﾟ

**Comment by Rai99** [comment]
Makeup: #5429 

Nail Polish: #4243 

Different colors of hair would probably function as separate hairstyles.

**Comment by TriniTDM** [comment]
> Does this look okay to anyone??

Most of it looks okay, but the hair color kinda hurts my eyes.

**Comment by Silvery55** [comment]
> Does this look okay to anyone??

do you mind doing the hair color miku has?

**Comment by ThePotatoGuy** [comment]
@octogonSmuggler if you wish to submit those images as spritepacks, make a new issue.

[closing as duplicate]
