### ISSUE TITLE
Can we add more holidays and such to fill up that calendar and make it more exciting?

### ISSUE THREAD

**Issue by octogonSmuggler** [Monika-After-Story/MonikaModDev#5551]
As a secondary note, I just realized, there's not a cute festival kimono or yukata. Since DDLC technically takes place in Japan, shouldn't there be a yukata or kimono for varying national festival days or something?

Here's a very basic list of some holidays:

Hanamatsuri: April 8th
Hanami: Late March-Early May
Hinamatsuri: March 3rd
Setsuban: Febuary 3rd
Shichi-Go-San: November 15th (Technically this is a festival for children (ages 3, 5, and 7. However, it would be fun to hear her mention it.)
Tanabata: July 7th
White Day: March 14th (This would be a fun day for gift giving to get extra affection points. Unless we already have it lol)
Autumn Equinox: Around September 23rd
Spring Equinox: March 20th or 21st
Summer Equinox: June 20th or 21st 
Winter Solstice: December 21st or 22nd
Boxing Day: December 26th
Mardi Gras: The Tuesday before the start of Lint, which begins on February 17th
Chinese New Year: February 12th
St. Lucia Day: December 13th
St. Patrick's Day: March 17th (She could dress all in GREEN!!)
May Day: May 1st (Ok. This is literally a ribbon celebration for the coming of spring!! A special May Day ribbon could be fun!)
Midsummer's Eve/Day: June 23rd/24th
Day of the Dead: November 1st
Labor Day: The 4th Monday of October (New Zealand) September 7th (USA) May 1st (Most other nations)

Now, I'm not saying that we should have a special event for every single holiday in the world or something, but we could absolutely just put stuff on the calendar, right? It's so blank that it sort of upsets me in a weird way....??

**Comment by DoodleSauce** [comment]
that looks cool

**Comment by Dank-Elf-Boy** [comment]
I mean... you could just ask for a feature that allows calendar customization lol. 

Then again, that sounds like it's been mentioned before. Can't remember.      ❓

**Comment by Rai99** [comment]
Custom Events: #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3832, #3921, #3933, #5402

Custom Calendar: #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058, #5402 

The thing with having more holidays on the calendar, is that they're holidays most people would celebrate, or at the very least, know about. With a custom calendar, people would be free to add whatever events they might like.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
