### ISSUE TITLE
ubuntu 19.10 alerts tab not existing

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5552]
OK so im using Ubuntu 19.10 and i use MAS via ddlc.sh file when i wanted to try window reacts for fun 
i realized something, the alert tab doesn't exist
i want to know if it is a issue or a feature that isn't here yet for Ubuntu users

edit: i found this if it can help 
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4484288/mas_log.txt)

im new in github btw

**Comment by multimokia** [comment]
You need to install notify-send on your computer. This is what allows MAS to send notifications. Since this is missing, the Alerts tab doesn't show up.

**Comment by DoodleSauce** [comment]
thank you but how i do so

**Comment by multimokia** [comment]
http://vaskovsky.net/notify-send/linux.html

**Comment by DoodleSauce** [comment]
ok i did it then what should i do if the alerts tab isnt here

**Comment by multimokia** [comment]
Did you do it while MAS was running?

**Comment by DoodleSauce** [comment]
no

**Comment by DoodleSauce** [comment]
ok i had MAS closed i went and installed notify-send in terminal then i went and opened mas and went check the settings it wasnt there

**Comment by multimokia** [comment]
@ThePotatoGuy

**Comment by DoodleSauce** [comment]
i tried to restart it dosent work

**Comment by ThePotatoGuy** [comment]
does `mas_log.txt` still say notify-send not found?

**Comment by ThePotatoGuy** [comment]
Additionally, are you able to run `notify-send` from terminal

**Comment by DoodleSauce** [comment]
1. yes it still says `[WARNING]: notify-send not found, disabling notifications.`




![screen](https://user-images.githubusercontent.com/63757604/79406761-e6461b00-7f65-11ea-9d19-955155722f89.jpg)

**Comment by DoodleSauce** [comment]
i tried to use sudo apt install libnotify-bin because it asked me and now its giving me another error



![screen1](https://user-images.githubusercontent.com/63757604/79407319-32de2600-7f67-11ea-8614-413667e9f9e2.jpg)

**Comment by DoodleSauce** [comment]
nvm
thank you so much
multimokia and thepotatoguy


honnestly im so happy thank you guys from the depth of my heart :D
