### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5553]
i have an idea (wich can be hard to make) but concerning monika asking you to play with you a video game.

instead of making monika an entity *like she says* we can make her user like a multiplayer game for example minecraft portal2 etc and for monika actually knowing how to play we can to make her an AI

PS: its a crazy weird idea i know

**Comment by Delcos** [comment]
As in make her an NPC in other games? Or have her play with you in multiplayer games as basically a bot?

**Comment by DoodleSauce** [comment]
yeah a bot

**Comment by GOKOP** [comment]
Dude good luck writing a bot that will play minecraft like a human

**Comment by BoogeymanTao** [comment]
Alpha-Monika.LOL.
That sounds interesting,but I don't think our PC have the capability to run such ai (probably require a lot of memory and hard drive? I'm not sure.)

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
