### ISSUE TITLE
Question on translation

### ISSUE THREAD

**Issue by INFINITY33q** [Monika-After-Story/MonikaModDev#5556]
Hi, I saw the new version 0.11.0, and I can’t find a translation into it (into Russian), I would like to clarify if it is available at the moment, and if not, when will it be ready?

**Comment by multimokia** [comment]
We don't make and/or distribute translations ourselves. That's up to the rest of the community to do. You'll want to ask the person who distributed the person who made the translation you're using.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
