### ISSUE TITLE
[Suggestion] - Adding "time delay" for random topic/coffee cup refill to pop up after player chosen interaction ends

### ISSUE THREAD

**Issue by pisangrf** [Monika-After-Story/MonikaModDev#5557]
Is it possible to make it so Monika won't immediately pop up random topics or goes to refill her cup of coffee immediately after the player chosen interaction ends (ie. after we chose some talk options)? 

Most of the time its fine. But its frustating that she just had to refill her cup of coffee in the middle of our "moments". And considering how often it happens in those "moments", I'm starting to have doubts whether Monika loves me or her cup of coffee more lol XD.

So my suggestion is,
1) instead of doing those things immediately, she'll wait for x time of seconds in idle. 
2) If in those x time of seconds the player does not chose any further interactions, then she will proceed to pop up a random topic or goes to refill her cup of coffee. 
3) But if in those x time of seconds the player chose another interaction, then she will wait another x time of seconds again (back to point number 1)

I can't code so I don't know how to really implement it, or if it is even possible, or if there are better ways of doing it. 
Anyway, thank you for listening and also for the amazing work put into this mod :D

**Comment by ThePotatoGuy** [comment]
Topics happening right away its a side effect of the async nature of topics + idle. 

I can definitely look into building in a delay, but we use the immediacy in some workflows so the effects would be non-trivial.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
