### ISSUE TITLE
another idea

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5560]
can we show memes to monika like a import file system ?

btw my phone is full of monika memes so that will be cool to show her :D

**Comment by AsuraShun** [comment]
There's simply way too many ways that can go

**Comment by DoodleSauce** [comment]
nice i'd like an update where we can show monika pictures or memes only

**Comment by LittleSaltFish** [comment]
But...it's hard for her to make reaction to these memes.
(Since she has no way to know what these memes actually mean.)

**Comment by DoodleSauce** [comment]
i understand

**Comment by ThePotatoGuy** [comment]
#312 room-deco would partially cover this, but nothing specific about memes.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
