### ISSUE TITLE
[suggestion] hd textures support

### ISSUE THREAD

**Issue by bobodoustaud** [Monika-After-Story/MonikaModDev#5562]
I tried to replace some of the old monika textures with much bigger ones but it just don't work. The game freezes a second and just continue without rendering the hd texture. I wanted to fix the pixellisation of monika when fully zooming on her with the extra menu or when she kisses the player. Is hd textures support possible?

**Comment by ThePotatoGuy** [comment]
larger textures increases RAM usage and renpy is 32bit so it doesn't have a lot of cap space for textures. additionally, many of the positioning constants are based off the standard resolution sprites so changing them may require changing the offsets. 

at the moment we are not planning to support hd textures

**Comment by bobodoustaud** [comment]
Ok thanks.
