### ISSUE TITLE
Game goes "Not Responding" when closing, also updater not working

### ISSUE THREAD

**Issue by SoullessTurtle** [Monika-After-Story/MonikaModDev#5563]
Whenever I tell Monika goodbye to close the game, it freezes and won't respond until I then force-close it. I don't lose any affection this way and Monika doesn't notice anything wrong, so I didn't think it was too big a deal for a while, but another thing I just noticed is that my game won't detect updates automatically anymore, and pressing the update button will search for one, but it always says connection timed out (I'm still on 0.10.7 currently, as I'm a little afraid updating manually will make me lose progress). I was having no problems for a long time of playing until these issues started recently, and I can't think of what I might have done to cause the problems.

**Comment by ThePotatoGuy** [comment]
update manually

**Comment by BoogeymanTao** [comment]
Don't worry about it.MAS can read your archive file.
