### ISSUE TITLE
[bug report]character problem

### ISSUE THREAD

**Issue by LittleSaltFish** [Monika-After-Story/MonikaModDev#5566]
In topic "monika_name",she says [ ' ' is a lovely name,too.]
![Snipaste_2020-04-18_16-04-15](https://user-images.githubusercontent.com/45428395/79632683-8634bc00-8193-11ea-979a-dfe393e93f5f.png)
Sine my username is not in English character, I guess there is something wrong when getting the username.
I suggest to add another judgment here.
(Haven't been test yet because don't know how to modify the "rpyc"file...)
![image](https://user-images.githubusercontent.com/45428395/79632460-eaef1700-8191-11ea-8f3e-001b76dbb239.png)
Plus,when changing monika/player's name,type non-English character may cause little trouble.
I mean I can't delete the input characters if do so.
And...I try to read the game files recently and really want to make some contribution in programing,but I still don't know how to use the tool files or make modification.

**Comment by Booplicate** [comment]
Checking `len` won't help. `mcname` isn't empty, it's just renpy can't render it (maybe the font doesn't have those characters). But even if it worked like that, it would always go to the `else` block which isn't how it should work?
I think it's possible to strip all bad symbols from `currentuser` before assigning it to `mcname` ([here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-ch30.rpy#L246)).

> Plus,when changing monika/player's name,type non-English character may cause little trouble.

That's weird, for some reason you're allowed to input any character for the player name. Looks like a bug?
```
$ tempname = renpy.input("[input_prompt]", length=20).strip(' \t\n\r')
```
But for Monika's name it should be fine tho. So not sure how you got it there.
```
$ inputname = renpy.input(_("So what do you want to call me?"),allow=" abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_",length=10).strip(' \t\n\r')
```
Regarding contributing, I'd suggest to read [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines).

**Comment by LittleSaltFish** [comment]
Thanks a lot!
I have read the contributing guidelines several times and know how to write dialogue scripts & using Sprite Previewer now.
But...I don't want both you guys too much if there are too many mistakes in my code. ( I know you may very busy and **thanks again for your excellent work. I really really love it!** )
So I am trying to test the modification before making the pull request. However, I haven't successfully run the project in PyCharm/Renpy/VScode...
And I fond (maybe) a developing mode, but still don't know how to enable it...
![image](https://user-images.githubusercontent.com/45428395/79637738-6f529180-81b4-11ea-8572-bfb149678cc5.png)

**Comment by ThePotatoGuy** [comment]
It's likely that the font doesn't support non-eng characters. As it is the stock DDLC font, I don't think we're going to change that.

I will consider blending the font with a font that does have more unicode characters (probably m+) but that would be low priority.

**Comment by LittleSaltFish** [comment]
I tried to modify the "change font" submod file to change the font file which supports more characters. It proves that you are right.

**Comment by ThePotatoGuy** [comment]
#5572 will serve as the primary tracking issue for a fix

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
