### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5569]
can someone give me a link to a program available on linux to open the persistent file (aka the MAS save data file)
thanks

**Comment by jmwall24** [comment]
we're not going to tell you here how to edit your save file

**Comment by DoodleSauce** [comment]
ok
sorry if i was rude

**Comment by jmwall24** [comment]
you weren't, but we're still not going to tell you how to edit the save file ;)

**Comment by DoodleSauce** [comment]
das ok my broda :D
