### ISSUE TITLE
Game can not read the sprite pack.

### ISSUE THREAD

**Issue by WCNM-NMSL** [Monika-After-Story/MonikaModDev#5571]
The game is not react with all sprite pack.

I think I follow the correct rule to install sprite pack, but they are failed to work.

The game still can read I give gift, however it just cannot fully read the files.

[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4497950/spj.txt)

The problem shows in the log/spj.txt is repeating saying 
[!ERROR!]: version mismatch. expected '3', found '2'

**Comment by ThePotatoGuy** [comment]
Update your spritepacks by installing the latest versions.

**Comment by WCNM-NMSL** [comment]
I just go to double check the game and spritepacks both is in newest
version.

But sadly the problem still remains, still version mismatch.

ThePotatoGuy <notifications@github.com>于2020年4月18日 周六下午6:40写道：

**Comment by ThePotatoGuy** [comment]
[ensure that you have updated them correctly](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

If spj.txt says version mismatch, it means it is loading older versions of spritepacks.

**Comment by WCNM-NMSL** [comment]
I know this may sounds little bit wired, but I just downloaded the latest
version of spritepacks on Monika after story website, and reinstalled into
the game. Then it still shows the same issue.

ThePotatoGuy <notifications@github.com>于2020年4月18日 周六下午7:02写道：

**Comment by WCNM-NMSL** [comment]
I am wondering is this have anything to do with I have two Monika after story in one computer.

I have one on steam and one on my desktop, even they both are latest version.

But I am not sure do this have any effect in this situation.

**Comment by WCNM-NMSL** [comment]
[spritepacks (2).zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498015/spritepacks.2.zip)
This is the spritepacks I am currently using.

**Comment by ThePotatoGuy** [comment]
double-check the [first step](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation) of the troubleshooting instructions. 

Particularly this line:
>Aka, there should **not** be a folder like `author-spritepackname` in `game/` nor `mod_assets/`

And since you have separate installs, you should check that  you updated the spritepacks in the Monika After Story install that you are using.

**Comment by ThePotatoGuy** [comment]
And make sure to **overwrite** all files when updating spritepacks.

**Comment by WCNM-NMSL** [comment]
I just reinstall spritepacks to both Monika After Story, and I double check I am install correctly, but the problem still remain.

**Comment by WCNM-NMSL** [comment]
[j.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498059/j.zip)
This is the J file from my Monika After Story, I wonder is this will help

**Comment by ThePotatoGuy** [comment]
Can you post the `spj.txt` from both of your installs?

**Comment by WCNM-NMSL** [comment]
desktop
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4498124/spj.txt)
steam
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4498125/spj.txt)

**Comment by ThePotatoGuy** [comment]
These are both referencing the desktop install.
To clarify, did you restart Monika After Story after updating the spritepacks?

**Comment by WCNM-NMSL** [comment]
Yes

ThePotatoGuy <notifications@github.com>于2020年4月18日 周六下午9:06写道：

**Comment by WCNM-NMSL** [comment]
Do you think should I delete the game and reinstall again?

率概 <gailvcaixiang@gmail.com>于2020年4月18日 周六下午9:07写道：

**Comment by jmwall24** [comment]
That j folder zip you sent is from the desktop install?

**Comment by WCNM-NMSL** [comment]
Yes

John W <notifications@github.com>于2020年4月18日 周六下午9:18写道：

**Comment by jmwall24** [comment]
Also, please say goodbye to Monika, then send us the spj.txt file. it won't fully load with the mod open.

**Comment by WCNM-NMSL** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4498161/spj.txt)

**Comment by multimokia** [comment]
The `j` folder you sent before, can we have the full filepath on that?

**Comment by jmwall24** [comment]
Basically the json you are sending us doesn't match the `j` folder you sent us. Pretty sure you installed the sprite packs today into the wrong folder. Show us a screenshot please of the `j` folder you sent us so we can see the file path.

**Comment by WCNM-NMSL** [comment]
[h.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498176/h.zip)
[f.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498177/f.zip)
[j.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498178/j.zip)
[t.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498179/t.zip)
[NjM2ODZmNjM2ZjZjNjE3NDY1NzM=.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498182/NjM2ODZmNjM2ZjZjNjE3NDY1NzM.zip)
[a.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498168/a.zip)
[b.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498169/b.zip)
[c.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498173/c.zip)
[cg.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498175/cg.zip)

**Comment by jmwall24** [comment]
We just need a screenshot of the `j` folder in your install like this that shows us the file path
![Screenshot_3](https://user-images.githubusercontent.com/36523761/79677328-0c65f800-81be-11ea-8924-342371b34bda.png)

**Comment by WCNM-NMSL** [comment]
![9E671757-8C73-4525-819D-A9689EA993B4](https://user-images.githubusercontent.com/59218970/79677373-9b731000-81be-11ea-9255-64f6c15b800f.jpeg)
![Uploading 692875F1-2E0D-4625-9FB7-DACAFCDC04D9.jpeg…]()

**Comment by WCNM-NMSL** [comment]
![CEADBF99-1D92-4746-BEEB-8C910A607E8A](https://user-images.githubusercontent.com/59218970/79677377-a0d05a80-81be-11ea-98c7-ced30f7d250c.jpeg)
![3F053D9E-7AC3-460D-8448-BB4E0072DA88](https://user-images.githubusercontent.com/59218970/79677379-a29a1e00-81be-11ea-9916-76415dde9aff.jpeg)

**Comment by WCNM-NMSL** [comment]
![3D020C65-C0FA-4302-80DA-BA3BCB63C9D6](https://user-images.githubusercontent.com/59218970/79677391-c198b000-81be-11ea-8308-162a85d4696b.jpeg)
![Uploading A84ED44B-DD77-4F51-8EE0-EA39B80CDCEE.jpeg…]()

**Comment by WCNM-NMSL** [comment]
![E4BFD8CE-6DA3-42B0-9C73-15898913A7B2](https://user-images.githubusercontent.com/59218970/79677397-cc534500-81be-11ea-8f03-c4715c959c3b.jpeg)
![Uploading DCEE2DB6-8A18-4577-A13E-A549ADF985F0.jpeg…]()

**Comment by jmwall24** [comment]
You're a folder too high. The `mod_assets` folder from the sprite packs need to be pasted into the `game/` folder, not the `ddlc/` folder

**Comment by WCNM-NMSL** [comment]
Yes! It work

**Comment by WCNM-NMSL** [comment]
Thank you for you guys helping
