### ISSUE TITLE
Patch the stock DDLC font for better non-en support

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#5572]
The stock DDLC font is known as `Aller_RG` and has very poor support for other languages. This is the reason why the music menu uses [m+ 2p](https://mplus-fonts.osdn.jp/about-en.html) as that font has a much larger base of supported characters.

My limited incursions into fontforge taught me that there is a way to fill in a broken font with another font's glyphs, but I don't quite remember the process. If someone can do this, this would be really helpful.

I recommend using m+ 2p as it looks similar `Aller_RG`. Both fonts are free to download online (and we ship m+ with the mod).

**Comment by Iniquitatis** [comment]
https://www.renpy.org/doc/html/text.html#font-groups
Should be pretty easy to do.

**Comment by LittleSaltFish** [comment]
One more suggestion. It seems that m+2p doesn't support Korean characters and simplified Chinese characters...
I suggest using SourceHanSansCN (it's free)  to fill in the characters which both Aller_RG and m+2p don't have. Thanks again!
The file is here:
[SourceHanSansCN-Normal.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4498401/SourceHanSansCN-Normal.zip)

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
