### ISSUE TITLE
Question about the Floating Islands

### ISSUE THREAD

**Issue by bringerofstorms** [Monika-After-Story/MonikaModDev#5575]
Are there any plans to do anything with them or are they just a thing that exists outside the window?

**Comment by GOKOP** [comment]
It would be cool if that mysterious thing in the middle got finished, I wonder if the devs actually have some plans for it

**Comment by ThePotatoGuy** [comment]
we are not revealing any future plans regarding the islands at this time

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
