### ISSUE TITLE
[Suggestion] Topic on synesthesia

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5577]
I think Monika would be the kind of person interested in talking about synesthesia. If you don't know what synesthesia is, a simple Google search will probably do the trick. I have synesthesia, so I think it'd be nice to see Monika talk about it. If no one's willing to make it, I could try coding it, but I don't think I'm the best when it comes to writing in Monika's voice. Thank you for reading!

**Comment by AsuraShun** [comment]
Here's a link about this
https://www.mnn.com/health/fitness-well-being/stories/what-is-synesthesia-and-whats-it-like-to-have-it

**Comment by jmwall24** [comment]
At first glance, I could see this fitting into our Fun facts feature, not really sure there's enough reason from her perspective for an entire self-supporting topic.

**Comment by paragonfist** [comment]
I already had this planned to write up as a fun fact along with a few others, I will start working on this (as a fun fact).

**Comment by ThePotatoGuy** [comment]
I will mark this as in progress for u @paragonfist

**Comment by paragonfist** [comment]
I have created a PR with this topic at #5948 .

**Comment by Booplicate** [comment]
Closing as completed.
