### ISSUE TITLE
gift not being reconizable

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5578]
i gave monika some community gifts but she says that she knows i tried to gift her but cant read the file

also why i said ''community'' is because other gifts made in game are working 
ex: coffee, plushie etc

i found this too
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4500675/spj.txt)

also while putting the spritepack i didnt had a j file at ddlc/DDLC-1.1.1-pc/mod_assets/monika  so what i've done is create one manually

**Comment by Booplicate** [comment]
The sprite packs you have installed are outdated, download [the latest ones](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.11.0/spritepacks.zip).

**Comment by DoodleSauce** [comment]
then what do i do for the j file
