### ISSUE TITLE
[Suggestion] Monika writing poetry

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5584]
Monika could write some poetry, and she could show them to the player, one poem per day. When you open the game on a day that you haven't been shown a poem, a random chatter topic will be unlocked and, when Monika brings up the topic, she could tell the player that she wrote a poem and show the player it. Though, it might take a while for the dev team to write that many poems. You could also have it once every one or two days (if that's possible), so it can be more random.

**Comment by multimokia** [comment]
Given that the dev team does this in their free time and do not get paid to do this as their job, it's simply not feasible to continually write so many poems.

Additionally with the release dates not being extremely consistent, we cannot plan in advance to account for this and therefore need to backlog a lot of them. 

Overall this takes dev time away from other features which would help expand MAS and Monika's character in other ways.

**Comment by ThePotatoGuy** [comment]
or users can contribute poems, but vetting them all would be harder to do than regular dialogue.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
