### ISSUE TITLE
[Suggestion] new window react and gifts from player

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5585]
I saw that Moni comments on visiting this side something about "helping her get closer to our reality." I think it would be cool if she could react to working in programs like Photoshop and said something "you're doing something for me". I don't know if she already does it cause I don't use exactly that program to paint, but if she's not then it would be pretty cool. Also there could be an dialogue option when player make something for Monika (just in his/her version) like making her new clothes or something, it would be cool to told her about it. Something like "you like that clothes/accessory? Actually it's present from me." Of course there's no way she knew it, but it would be cool. Or option "goodbye, I'm going to give you something I made myself." And when we come back with some gifts she knows it's from player. Not just downloaded by player, but made by player for her.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
