### ISSUE TITLE
Question about the “game”

### ISSUE THREAD

**Issue by QLQland** [Monika-After-Story/MonikaModDev#5588]
Hello guys！One of my friends can only play pong though his affection is already 170+，so I wonder if it is a bug.If not，can you tell me the conditions for playing games other than pong?
My English is not good，so if I have a wrong grammar，please ignore it.

**Comment by multimokia** [comment]
There's a small bug regarding the adjustments to the exp system which unlocks games in the current release. This is addressed in #5535 and will be granted properly next release.

That said, game unlocks *will* take a bit longer to happen now, but still should be pretty early on.

**Comment by QLQland** [comment]
Thanks for your reply and it really helps.
