### ISSUE TITLE
Persistent weather

### ISSUE THREAD

**Issue by LooseEthics** [Monika-After-Story/MonikaModDev#5589]
Just a small quality-of-life improvement I'd like to suggest.
Whenever the game is started, the default weather is progressive (at least that's what I'm assuming since it changes on its own). What I'd like to suggest is making Monika able to remember the weather between instances.
One way would be to just hard code it.
Another, more interactive, way would be to implement it via the Weather tab. There could be a one time event that triggers when the player asks Monika to turn on a specific type of weather a given number of times (either globally or in a row) where Monika remarks on it and asks if you'd like it to be set as default.
`You sure seem to enjoy the snowfall/sound of rain/whatever, [Player]. Would you like it to snow/rain/etc whenever you come here?`
After this happens a new option gets added to the Weather tab which lets you ask Monika to change the persistent weather.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
