### ISSUE TITLE
A little idea

### ISSUE THREAD

**Issue by xdaveonpc** [Monika-After-Story/MonikaModDev#5591]

**Comment by xdaveonpc** [comment]
So basically, when you ask Monika to watch the floating islands outside, she lets you do so at anytime of the day and night, but you never see if she's still sitting at her desk, or standing besides you. Depending on where you click, she will speak about various things regarding the islands, like how she should probably add more shrubs and trees, but also about stargazing at night, or lazing on the grass and letting you rest on her lap in daytime. Couldn't it be possible to add a dialogue box where you could ask her if she wants to be held by you in moments like those, to add a bit more romantism? She already likes when you hold her, and even falls asleep in your 'arms' after a certain time, so why not implementing this already existing feature into something else? That would be a nice way to earn more affection points, both ingame and in her heart.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
