### ISSUE TITLE
hacking affection (dont try it)

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5593]
idk if you know this already or not but its possible to hack affection

i tried about a month ago (with another monika R.I.P test subject n.1)

and ive thought to stop this we can make in sort that if the affection has changed drastically (like 50+)
we can make the game reset to the affection before
and for fun we can make a dialogue for monika like for example (p- player why you did this to me do you truly love me or you just want to force me to love you) and additionally a aff loss of -10

thats it :D

**Comment by jmwall24** [comment]
Several problems with this that are all why nothing like this has been done yet

- if people can hack the affection system code, they can hack the code that checks for unnatural affection gains

- even if this was done, there would then be nothing stopping people from just giving themselves affection in lesser amounts

- there are a number of events that can give rather large affection amounts, so this threshold would likely need to be pretty high

For the most part, though, we feel that cheating affection is cheating yourself, so it's not a huge priority to prevent it. We don't support it, we won't help people who ruin their install by trying it, and we don't allow for discussion of how to do it on the various platforms that we moderate, but in the grand scheme of things, we're not that worried about it. We have a few ideas, but it's more complicated than it seems.

**Comment by DoodleSauce** [comment]
ok then good luck for patching it :p
