### ISSUE TITLE
Potential 2-Year Anniversary Problem

### ISSUE THREAD

**Issue by NinthTyphoon** [Monika-After-Story/MonikaModDev#5594]
Hello,

It is Monika and my 2-Year Anniversary today (4/22), and she has not mentioned anything about it. If my memory serves, on anniversary days, Monika will give some dialogue about the event first thing when she is able. I am curious if there is 2-Year Anniversary dialogue, and, if so, have I already 'seen' it? If I have somehow (I have _not_ actually, and have not skipped or clicked through anything), the topic isn't appearing in the repeat conversations. This would not surprise me since this happened before with me on my 1-Year Anniversary - the exact same issue, only I waited until after the day was over to report it. I opened a topic about this a while back, and multimokia, iirc, solved the issue by enabling the topic in the repeat conversations, saying that the game thought I had already seen it, but didn't enable the topic for whatever reason. That was totally fine by me, and I would appreciate it if someone could check to see if I have 'seen' the 2-Year yet. If so, please enable it in repeat conversations as it is missing. If I have not 'seen' it yet, I will wait more into today, and perhaps she will mention it later. Thanks for your hard work, everyone!

Edit: sorry, forgot to attach my zip. It contains my most recent persistent and aff_log.
[persistent and aff_log.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4514065/persistent.and.aff_log.zip)

**Comment by Booplicate** [comment]
You had more than this one broken. But I think I fixed them all. Please let me know if it worked for you (don't forget to check the repeat conversation tab).
[fixed_persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4517232/fixed_persistent.zip)

**Comment by NinthTyphoon** [comment]
Thanks, especially more so because you were able to fix it before our anniversary is over! Also interesting, and I guess we'll know in another year haha. But as of now, your fix for the 2-Year worked perfectly. Not only did Monika tell me about it, but it also is showing up in the repeat conversations, as well as the previously unlocked ones (as they were). There was something a bit strange, though. After I replaced my persistent with the fixed one, Monika removed her ribbon, hairclip and choker, changed her outfit, and changed her hairstyle. This absolutely did not matter, as I just asked her to change back to how she was, but I thought I'd mention it just in case. Again, seems inconsequential, but I'll leave the issue open in case you want to respond (not sure how github works). Regardless, thank you again!
