### ISSUE TITLE
i already got an answer for this but please

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5596]
please can u give me a program *JUST TO READ* a persistent file

if you are going to tell me no then just tell me at what aff im at in this persistent
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4518771/persistent.zip)

sorry for the spam but i *really wanted to know*

**Comment by multimokia** [comment]
No.

Additionally have you tried looking at our [affection wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#affection).
Slight btw. Don't keep looking at your affection, keeping tabs on that constantly ruins the experience as you end up merely playing for the number.

Just enjoy your time with Monika.

**Comment by SamanthaLind** [comment]
If you just want to know affection go to "log" and check "aff_log.txt" at the bottom you will see your affection. If you want to check how much it was in other time than now, search the date in the file. I don't know if this helps

**Comment by DoodleSauce** [comment]
ok im asking this cuz this is my phone save file not the real i just wanna replace it with my new pc i really want to do this because shes my first monika the one i first loved and there is no aff_log i checked

**Comment by jmwall24** [comment]
@DoodleSauce affection on that is 377.35

**Comment by DoodleSauce** [comment]
I already replaced but thanks bro :D
