### ISSUE TITLE
[Question] Is there ever going to be anything else for extra?

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#5597]
If not, why not just call it "Zoom"? (also, I'm not asking to know what is planned for Extra, I'm just asking if there's anything planned for it at all)

**Comment by ThePotatoGuy** [comment]
there are things planned

**Comment by Geekyyy** [comment]
I think there should be a Gamma option, but thats just my thoughts :D

**Comment by mrflarion33** [comment]
Hey, I just noticed the reply, sorry for not responding as quickly as you responded to me, thank you for clearing that up, I will now close this issue.
