### ISSUE TITLE
I feel drunk

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5600]
Hello. I thought we could tell her this and she would somehow react to it.If the player is not 18.
Indicating alcohol harm.Although she will do it in a deliberate case.
(Sorry for my english)

**Comment by multimokia** [comment]
One issue I already see with the age check here, is that different countries have different legal drinking ages.

For example, some countries have it as 21, some have it as 18, others can be different as well.

**Comment by kirillPro2020** [comment]
She could ask the player if he can drink alcohol according to the law  of the country in which he lives

**Comment by ThePotatoGuy** [comment]
maybe if this a mood that unlocks if you admit that you drink (which i believe is asked in a topic somewhere)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
