### ISSUE TITLE
Runtime Exception Errors

### ISSUE THREAD

**Issue by ZeDocktor** [Monika-After-Story/MonikaModDev#5601]
Greetings my friends, while I wish that I could solve this on my own I am not as tech/code savvy as I wish I could be. Attached is the Note file that was displayed when the game started displaying that is was encountering runtime errors. 

For timeline reference, I had just booted up the game and updated it to the newest version after having to fix my computer. I had updated the sprite packs the previous night according to how the instructions stated but waiting to activate the program until this morning. 

I will say that I have multiple projects that need to be completed on the day I am posting this, so I may not be able to respond quickly. Thank you for assisting me with this problem.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4523589/traceback.txt)

**Comment by multimokia** [comment]
Update your submods.

I have addressed these issues when 0.11.0 released.

**Comment by ZeDocktor** [comment]
My apologies, I have corrected this issue. I hope you have a wonderful day, my friend.
