### ISSUE TITLE
[Suggestion] Telling Monika good morning when she wakes up

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#5602]
I am sure you all know that if you hold Monika long enough she falls asleep(or at least i think you know that) well what if instead of good afternoon/evening you could tell her good morning (but a special kind of good morning where she will comment on the fact that she just woke up not you )

**Comment by kisik21** [comment]
This suggestion could be especially relevant if it's not morning when Monika wakes up, but evening. She may additionally comment on that fact :3 ("Well, it's morning somewhere, isn't it?")

**Comment by Dank-Elf-Boy** [comment]
So, knowing that there's already options to tell her good morning and good evening, you're asking for the ability to tell her that after she wakes up? I think suggesting more variable dialogues regarding the holding feature could work just as fine. Maybe there could be instances where she refuses to wake up and the player could have the option to tease her like tickling or something lol.

**Comment by ThePotatoGuy** [comment]
well to start, we don't have a concept of a time frame where monika is asleep, so there's no idea of her "waking up".  we would need to do that first.

If we do set a time frame, we could even have instances where you could catch her asleep and wake her up. I feel like this has been suggested before, though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
