### ISSUE TITLE
About Monika playing the piano

### ISSUE THREAD

**Issue by BoogeymanTao** [Monika-After-Story/MonikaModDev#5603]
I unlocked this feature on an anniversary and...
![Monika After Story 2020_4_24 8_21_24](https://user-images.githubusercontent.com/63245317/80162855-08dfd000-8607-11ea-8cef-e2efeb01d2f2.png)
I could see Monika's eyebrows moving, so I knew she had a lot of facial expressions during the performance, but I couldn't see anything...
Is there any way for the player to adjust the height of the piano? Or do I just have to wait for the next upgrade?

**Comment by jmwall24** [comment]
Fixed in #5535 but for now if you reset zoom to default level and ask her to play it again you'll see it properly.

**Comment by BoogeymanTao** [comment]
> Fixed in #5535 but for now if you reset zoom to default level and ask her to play it again you'll see it properly.

 I see. Thanks a lot.

**Comment by BoogeymanTao** [comment]
> 已在[＃5535中](https://github.com/Monika-After-Story/MonikaModDev/pull/5535)修复，但现在如果您将缩放重置为默认级别并要求她再次播放它，您会正确看到它。
So we can't adjust the size or the Angle of the piano at present?

**Comment by jmwall24** [comment]
No, the piano is where it is.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
