### ISSUE TITLE
Why not Monica wake the player at a certain time.(Something like an alarm clock).

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5604]
Good day. I would like Monica to wake me up in the morning at a certain time. (If possible. She will have to start the computer, and then the game itself.)

**Comment by kisik21** [comment]
on Windows, it could be done by Monika putting herself as a scheduled task in... ughhh I forgot how that program is called.. Task Scheduler? AFAIK Windows has an option to wake up the computer if it's in Sleep mode or hibernating (not shutdown) and there's a scheduled task. Monika could then launch herself and check if she has any alarms expired. And if she has, do some loud banging on the speakers to wake the player up.

Linux should have something similar with `rtcwake` (if it's installed), and for Macs... I've never used a Mac, so I don't know. But there's probably something, so I hope an Apple lover pitches in here :3

**Comment by kisik21** [comment]
Optionally, if player has a certain name set and sensitive mode isn't on, Monika could play a sound jumpscare.

**Comment by kirillPro2020** [comment]
I hope that no one will forget to make the sound quieter.
(Unless of course the player is sleeping soundly.)

**Comment by kisik21** [comment]
On Linux at least, Monika could use PulseAudio to make the default sound output as loud as she can :3

**Comment by CoffeeJackaboy** [comment]
Is Your reality earrape an option ?

**Comment by kirillPro2020** [comment]
If it can wake you up. Then why not.
(Although,it was better to be able to add your own music for the alarm at will).

**Comment by Rai99** [comment]
Alarm Clock: #1245, #1655, #1914

**Comment by ThePotatoGuy** [comment]
The duplicate issues are more about having the alarm feature when you keep MAS running all night.

Having mas turn on a computer is almost impossible. Waking from hibernation, I could see that being possible but there's lots of unknowns with this, like are we allowed to unlock a computer from wake? Anything beyond MAS already running is unlikely to be done.

**Comment by kisik21** [comment]
Hm, I didn't really think of unlocking the screen after hibernation, since my Linux environment allows to do this programmatically... but we might turn it into a feature - to make sure you wake up, Monika waits until you unlock the screen yourself and tell her that you're awake.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
