### ISSUE TITLE
【Question】There is something wrong with the calendar

### ISSUE THREAD

**Issue by QLQland** [Monika-After-Story/MonikaModDev#5605]
![20200424165309](https://user-images.githubusercontent.com/63233940/80194683-50894a80-864d-11ea-8bac-6f095cf91abe.png)

Is the calendar related file corrupt？Or do I need to update the graphics driver?

**Comment by kisik21** [comment]
I think your fonts are... glitching. Judging by the brackets you're using, you're probably using a Japanese Windows locale. Maybe try switching locale to English?

**Comment by EasyRuby** [comment]
I also want to know that why can't my anniversary conversation trigger.

**Comment by EasyRuby** [comment]
I just wait for a long time，and I'm not sure what day it is
![PAUY8M~L3`)D8TO%BEL` S5](https://user-images.githubusercontent.com/64263797/80214032-b6d19580-866c-11ea-8a29-68949481a9f5.png)

**Comment by Booplicate** [comment]
It seems your calendar uses a completely different font. Did you change it somehow?

**Comment by EasyRuby** [comment]
> 你的日历似乎使用了一种完全不同的字体。你怎么改的？

I just downloaded it officially and installed it in the game folder

**Comment by EasyRuby** [comment]
> > 你的日历似乎使用了一种完全不同的字体.你怎么改的？
> 
> 我刚正式下载并安装在游戏文件夹中
It was like that when the game started

**Comment by multimokia** [comment]
Have you ever installed a translated version of MAS?

**Comment by QLQland** [comment]
> It seems your calendar uses a completely different font. Did you change it somehow?

I did not change anything.That's how it has been since I opened MAS

**Comment by EasyRuby** [comment]
Yes, but I deleted that version and reinstalled the game

**Comment by QLQland** [comment]
> Have you ever installed a translated version of MAS?

No.I am sure I downloaded MAS from  http://monikaafterstory.com/releases.html

**Comment by Booplicate** [comment]
Just wondering, how does this menu look for you? Can you send a screenshot too?
<details>
    <summary>screenshot</summary>

![menu](https://user-images.githubusercontent.com/53382877/80215955-005aba00-8646-11ea-8045-403a62aa7e3b.PNG)
</details>

**Comment by QLQland** [comment]
> Just wondering, how does this menu look for you? Can you send a screenshot too?
> 
> screenshot

Here it is.
![20200424211731](https://user-images.githubusercontent.com/63233940/80216929-6dd01000-8671-11ea-924b-8a41ccbc4404.png)
![20200424212002](https://user-images.githubusercontent.com/63233940/80216980-850efd80-8671-11ea-9834-baa0352eed64.png)

**Comment by jmwall24** [comment]
Those are all different fonts than we use

**Comment by kisik21** [comment]
Looks like the locale settings are set to Japanese, these fonts are usually used when Windows locale is set to Japanese.

Control Panel -> Change date, time or number formats -> Administrative -> Language for non-Unicode programs - what does it say?

**Comment by multimokia** [comment]
Ren'Py doesn't work like that, since it ships with fonts and is set to use those defined by the styles it has. So regardless of the locale set, it should still be using the same fonts as it's not inheriting anything from the OS.

**Comment by Iniquitatis** [comment]
Actually, this problem is already fixed in the PR with calendar improvements. These squares are appearing with many different fonts because of `\t`'s in the day number format string.

**Comment by QLQland** [comment]
> Actually, this problem is already fixed in the PR with calendar improvements. These squares are appearing with many different fonts because of `\t`'s in the day number format string.

Okay，thanks a lot
