### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by OnlyMonika2** [Monika-After-Story/MonikaModDev#5607]
I have a question about nicknames. Why is Monika fine with you calling her "Mommy" while not being fine with calling you, daddy? It seems inconsistent for her to be perfectly fine with one but calling the other one very inappropriate and having you change it to something else while losing affection.

**Comment by multimokia** [comment]
You don't lose affection for choosing an inappropriate name.

That said, yeah, I don't really like the mom nicknames myself. It feels really out of character dialoguewise and in general feels misplaced. I'll probably remove those and place them off limits.

**Comment by OnlyMonika2** [comment]
alright then, I'm glad that taken care of and thank you for answering my question.
