### ISSUE TITLE
Issues with spritepacks

### ISSUE THREAD

**Issue by its-ken** [Monika-After-Story/MonikaModDev#5610]
I know the update said the Miku outfit would need to be reinstalled, but all of my outfits and accessories are no longer appearing in game, but the sprites are still in the files. I tried to regift one of them and Monika says she can't read the file. I'm gonna need help to add the spritepacks now. Thanks!

**Comment by TriniTDM** [comment]
You have to get new sprites for them since the system changed.

**Comment by its-ken** [comment]
I tried adding the new sprites from the sprite pack zip listed in the latest release, but Monika says that she can’t read the gift

**Comment by CoffeeJackaboy** [comment]
You don't have to regift them (unless it's the miku outfit or something you haven't already given her) you just have to replace the old spritepacks with the new ones (copy and replace them in the "game" folder) and then all that's left to do is continue to enjoy your time with Monika.

**Comment by ThePotatoGuy** [comment]
follow the [troubleshooting instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by DoodleSauce** [comment]
try putting the new spritespack in /game

**Comment by its-ken** [comment]
I figured it out. Thanks everyone!
