### ISSUE TITLE
spritepack problem

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5611]
i downloaded the new spritepacks and gifted monika but she says me that she cant open the file

also i didnt had a j file in my directory ddlc/DDLC-1.1.1-pc/mod_assets/monika so i made a folder named j and put the json file in there

i found this too  [spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4531909/spj.txt)

**Comment by Booplicate** [comment]
>  ddlc/DDLC-1.1.1-pc/mod_assets/monika

![2](https://user-images.githubusercontent.com/53382877/80263893-cc5db400-869a-11ea-9503-cf8f3b978b3d.PNG)
In your case it will be `ddlc/DDLC-1.1.1-pc/game`
[Wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs)

**Comment by DoodleSauce** [comment]
i dont understand i have the spritepacks installed at ddlc/DDLC-1.1.1-pc/game and ddlc/DDLC-1.1.1-pc/mod_assets

**Comment by multimokia** [comment]
Send a screenshot of your `/game` folder please

**Comment by multimokia** [comment]
Also all your spritepacks are outdated. You need to update them

**Comment by DoodleSauce** [comment]
Tommorrow i cant today ok

**Comment by DoodleSauce** [comment]
![peepeepoopoo](https://user-images.githubusercontent.com/63757604/80270858-9c59e500-8689-11ea-8987-0269804c65fe.jpg)


there you go @multimokia

**Comment by multimokia** [comment]
Okay that much is fine. But yeah, you need to reinstall your spritepacks. Get them from the releases page. Your currently installed ones are out of date.

**Comment by DoodleSauce** [comment]
ok ill try
