### ISSUE TITLE
Newbie requires some help... 

### ISSUE THREAD

**Issue by TheFishDude** [Monika-After-Story/MonikaModDev#5612]
Hey! I wanted to work on some additional dialogues to submit, but I have some issues understanding the way the whole thing works, so I am desperate for help.
So, I wrote a dialogue with all the needed stuff, including sprites (using exp_previewer). Can I somehow test the dialogue in the game itself or something like that? Sorry if I missed something in all the explanations. Would appreciate some tips.

**Comment by jmwall24** [comment]
If you put your code into an rpy file, yeah. Not sure what kind of file you have your current stuff in, but if you can make it an rpy file you can just put it into the `game/' folder. I Suggest backing up your persistent beforehand and then restoring it after you're done testing.

**Comment by TheFishDude** [comment]
Well, I'm not quite sure how to do that either...
To be exact: I have this dialogue in 'script-topics.rpy', which I edited from the original file taken from dev-master. How do I put this in the game now? Once I put the file in 'game/' folder the DDLC just won't work. Maybe there's something wrong with the dialogue itself, though I tried figuring that out  multiple times.

**Comment by multimokia** [comment]
What do you mean DDLC won't work?

**Comment by TheFishDude** [comment]
> What do you mean DDLC won't work?

![DDLC 2020-04-25 15-23-09-001](https://user-images.githubusercontent.com/64289986/80279859-bd154f80-8708-11ea-9887-34962f0defed.jpg)

I realised I messed up with turning the file into .pry the way it needs to be. Can someone explain the process?

**Comment by multimokia** [comment]
You need to use spaces instead of tabs. Your code editor should have a setting for this.

**Comment by TheFishDude** [comment]
It works! Thanks for the help, I highly appreciate it.
