### ISSUE TITLE
[Suggestion] Make Monika sing again.

### ISSUE THREAD

**Issue by Daiozen** [Monika-After-Story/MonikaModDev#5616]
So, this is just my two cents on the subject, but I miss Monika singing out of the blue; it's something that always helped put a smile on my face. Having to ask her directly to sing does not feel the same...

I know it was derandomized so she wouldn't keep singing all the time as the number of songs kept increasing, but if there was a way to still let her sing once in a while, that's something I'd really enjoy.

**Comment by DoodleSauce** [comment]
you can activate repeat topics maybe she will sing for fun like this

**Comment by fromulus** [comment]
She doesn't sing again even with repeat topics enabled, sadly.
Perhaps a solution could be to have a way to toggle specific songs on and off in the dedicated menu.

**Comment by jmwall24** [comment]
We can set something up for this.

**Comment by multimokia** [comment]
Closing as complete
