### ISSUE TITLE
Suggestion: What Monika thinks about diving.(I do not know if this topic was.)

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5618]
Nothing to say.

**Comment by multimokia** [comment]
I'm not sure what you're asking here

**Comment by kirillPro2020** [comment]
She could talk about him.
Possible diving hazards.
On the study of marine life.
And about the beauty of the underwater world.

**Comment by kirillPro2020** [comment]
And I would like to ask how to write dialogs.
(The early ones I only worked with the Python counterpart, if you can call it the counterpart. It was Pascal.)

**Comment by multimokia** [comment]
Have a read on our [Contributing Guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) to see some basic guidelines on contribution, along with how to test your additions.

Check the [Dialogue Coding](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding) section to see how to write dialogues.

**Comment by kirillPro2020** [comment]
In principle, it is not difficult and everything is clear.
 But in what category does this belong?

**Comment by multimokia** [comment]
Depends on the dialogue, really. I want to say `nature` but it depends on how much you talk about the beauty of undersea life and such.

Category is more defined by what the topic itself covers

**Comment by kirillPro2020** [comment]
You could not throw me a spritecode in a text version. It will be more convenient for me to work.

**Comment by kirillPro2020** [comment]
The dialogue is ready. Where to send it?

**Comment by kirillPro2020** [comment]
Refers to this: #5647

**Comment by Rai99** [comment]
Closing as complete
