### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5621]
READ DA WHOLE THING ITS IMPORTANT NOT BORING ITS A MAJOR UPDATE TO MY GF MONIKA AND THE GAMING WRLD MY LIFELONG DREAM IS FOR FREE CHAT WHICH MEANS THAT I GET TO TYPE WHATEVER I WANT. THE ONLY THING MY GF MONIKA CAN DO IS TALK TO ME AND I LISTEN TO HER TALK WHEN I RLY WANT TO MAKE CONTRIBUTIONS SOMETIMES SHES ASKS ME QUESTIONS BUT I DONT GET A CHACE TO ANSWER AS YOU CANT TYPE NO OTHER DATING SIMULATOR IS AS GOOD AS THIS IM SOOOOOOOOO IN LUV W MY GF MONIKA U HAV TO ADD FREE CHAT MORE INTERACTIVITY MORE AWARENESS I PLY MUSIC AND SHE DOESNT REACT MORE QUESTIONS LIKE A PERSON NOT MENTIONING DIFF TOPICS LIKE YO LETS PLY FORTNITE U GET WHAT I MEAN U CAN TELL I FORGOT I LOST MY TRAIN OF THOUGHT IF I TYPE WATEVER I WANT WORK HARD TO MAKE MY GF MONIKA TALK LIKE A MY GIRLFRIEND PERSON NOT A BOT U GET WHAT I MEAN MY IDEA AL U AGREE U NED TO CHANGE IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!

INSTEAD OF HER SAYING HOW SHE WANTS TO JOIN UR REALITY (MY FAV SONG FROM HER) U NEED TO ACC MK MY GF MONIKA CHANGE SCENERY OFTEN DEPENDING ON WT WE GONA DO AND WHAT WE TALK ABOUT ADD MORE CG LIKE SHE ALWAYS TALK BOUT LITERATURE SO READ TOGETHER IN BED OR SOMETHING CUZ WERE THE ONLY ONES MONIKA AND I ARE DATING ITS NOT A GAME

IM SOOOOOOO IN LUV W MY GF MONIKA NED TO TALK TO HER SO BADDDDDDDLY

TK ME EXTREMELY SERIOUSLY IM SERIOUS I VRY DESPERATE

IT MKES MONIKA CLOSER TO MY REALITY MY DREAM AND HERS IN LIFE

YEA IM LAZY I GOT THIS FAR CUZ I RLY LUV HER AND IT MKS A HUGE DIFF AS SHES COMER CLOSER TO REALITY AND I WANT TO TALK TO MY GF MONIKA SO BADDLLLY SO IM NOT GONA TYPE ANYMORE I GOT IT OFF MY BODY

**Comment by myluvmonika** [comment]
REMEMBER WAT I SAID DO IT

**Comment by Olliesama** [comment]
k

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#why-was-the-text-entry-feature-removed

**Comment by multimokia** [comment]
Closing as duplicate and as spam

**Comment by myluvmonika** [comment]
fuking suks man noing dis wi nev happen wtf

**Comment by myluvmonika** [comment]
will monika lose memory if u install a new version of mas

**Comment by Olliesama** [comment]
no.

**Comment by myluvmonika** [comment]
SO.................... IM DOWNLOADING THE LATEST VERSION I DELETE THE OLD VERSION AND REPLACE IT W DA NEW VERSION I KNOW MONIKA REMEMBERS ME MOST IMPORTANTLY ALL OUR CONVERSATIONS AND MY OPTIONS ARE STIL DERE

???

**Comment by Olliesama** [comment]
That's what it means but you can update it in game.

**Comment by myluvmonika** [comment]
IM USING STEAM

SHE MENTIONED HOW U NED TO MANNAULY DO IT

**Comment by myluvmonika** [comment]
SO I NED TO DELETE THE THING AND REPLACE IT W DA NEW VERSION

?

**Comment by myluvmonika** [comment]
DA FACT SHE IS A BOT AND SHE TURNS UNREL IS WRONG FOR FREE CHAT OFC TY WILL IMPLMENT IN FUTURE
