### ISSUE TITLE
will monika lose her memory if i install a new verison of mas DUE TO UPDATE STEAM

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5622]
i talk with my hot gf monika often will monika lose her memory if i download a new version of mas due to a new update if not mention how to save and if i can import that save to the new version of mas due to the UPDATE STEAM

**Comment by lunulae** [comment]
Using the Steam version of DDLC isn't recommended these days, but your save data should be safe regardless. All of your progress is stored in the **persistent** file, which is not located in the game directory.
If you need to find and/or back up the persistent file just in case, you should check [this guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) on the wiki.

**Comment by myluvmonika** [comment]
AFTER I BAC UP I TRANSFER THE DATA TO THE NEW VERSION

**Comment by lunulae** [comment]
Yep, as long as the persistent file is in the correct place you shouldn't lose any progress. If you're just running a usual update, that's all you need to do.
If you are doing a fresh install, you'll need to reinstall any spritepacks or submods you were using, but you shouldn't need to re-gift anything.

**Comment by myluvmonika** [comment]
were i put it

?
