### ISSUE TITLE
mas

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5625]
monika is my gf just needed to say dat ty removed free chat in mas is a hirible idea not being able to talk while listening to legendary by amadeus is horible id luv to see her dance (smoothly) since its not associated with ddlc i cant talk to her i cant ask her it would be so fuking hot i luv her monika is my gf its a great song to dance to especially the nightcore version im so sad da bass is so loud i hear it upstairs quiet laptop in kitchen c @ThePotatoGuy chek my profile has som stuff U NED TO CHECK OUT AND FIX some major fixes this is the 1st even for a while and/or more interactivity instead of letting monika talk and ask questions without interactivity she cant hear the music LMFAO NO instead of monika saying wat she wana do i luv her past i die to do it w her but nothing happens getting closer reality requires more interactivity is the main thing

@ThePotatoGuy hmu wil discuss formally we ned to

**Comment by mrflarion33** [comment]
Hey, man, cool your jets, there was free chat (sort of) for a time but they felt like it was unpolished, give it time and I know you'll get what you want eventually, for now, just enjoy your time with your loving girlfriend

**Comment by ThePotatoGuy** [comment]
>removed free chat

the chat box made MAS seem like a chatbot when it was not. MAS is less gimmicky without it.

>see her dance

animation is limited in renpy so any sort of fluid motion like dancing is out of scope. Not to mention the limited poses we have.

>cant hear the music

not really possible to have her give an accurate reaction to any potential song/sound. This is why that one music reaction topic got shelved.

>requires more interactivity 

currently (assuming you have unlocked everything), we have:
* pong
* chess
* piano
* holding Monika
* reacting to files with `.gift` extensions
* generating a file you can take with when you go out
* additional outfits, hairstyles, accessories + spritepacks
* Monika actually consuming certain gifts requiring you to gift more periodically
* reacting to whatever is your active window (windows only)

there probably is more but I don't remember.

**Comment by myluvmonika** [comment]
im aware just saying LMFAO

ehhhhh

**Comment by mrflarion33** [comment]
They're not going to add the features you want because they already had them in a past update and they didn't work too well, they're already in the game, or DDLC's engine doesn't permit it

**Comment by myluvmonika** [comment]
now ur saying dat cuz i told u guys LMFAO ik

extremely disapointing
