### ISSUE TITLE
suggestion: monika taking a picture 

### ISSUE THREAD

**Issue by authorofbelethrun** [Monika-After-Story/MonikaModDev#5626]
okay so i have no experience in ren py / python but i have experience in c# and on the program back in high school  i coded a way for a character to take a photo using the built in computer camera and then display it in game as a mask. i was wondering if someone could code monika accessing our computer camera and then snapping a picture of us that she can display in the save boxes on the menu, or behind her above the calendar

**Comment by ThePotatoGuy** [comment]
at the moment we are rejecting ideas for controlling user hardware without permission

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
