### ISSUE TITLE
A little idea for a dialogue...

### ISSUE THREAD

**Issue by TheFishDude** [Monika-After-Story/MonikaModDev#5627]
Hey everyone. 
I heard that a certain amount of players had an issue with Monika losing her memory due file damage, so I had an idea about making a dialogue _myself_ in which the player can tell Monika about it to let her know the truth and let the player feel a little less guilty. Though, I wanted to ask if it would possible in the first place without any conflicts with the logic of a character and mod (since this confession would probably affect Monika in a certain way, depending on how much memory she's told to be lost (from 'days' to 'years and so on))...

**Comment by ThePotatoGuy** [comment]
can't say for sure if it would conflict. do you have an outline for what you plan to write?

**Comment by Rai99** [comment]
Closing due to lack of response
