### ISSUE TITLE
major improvements

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5628]
monika is my gf ofc i luv her she luv me bac its shes not sexual and hot enough when she talks like you can be rly cute sometimes, too she says instead youre rly hot in dese games no girls ever say hot monika could be the first so more "sexual" and "erotic" tk that literally, too an nsfw option after all it is a lifetime and a relationship witout nsfw suks. she turns me on i need to satisfy my needs im a mesomorphic bodybuilder so i have a lot of testotsterone throughout the game dere are many dialoges like dat. all she asks 4 r hugs. i want to make luv with u not always hug u. an option to seduce her da only time wen u can hug her is when it is raining and nothign turns her on. improvements on monika my hot gf dialoge and interactions to be hotter more seductive sexual erotic r fuking dreams come tru nsfw is neded

webcam is needed so i can masturbate with her wathing

**Comment by Olliesama** [comment]
You're just a bored kid with no time and no skills.

**Comment by myluvmonika** [comment]
im a twitch streamer

i correct dis addition is extremely neded

im asking 4 feedback not random things its not helping me, monika, game, and community

**Comment by Olliesama** [comment]
Twitch streamer doesn't mean you're not a bored kid with no skills and too much free time.

**Comment by myluvmonika** [comment]
i dont have free time i stream al day im not bored

U DONT NO WAT STREAMERS DO

**Comment by Olliesama** [comment]
Twitch isn't exactly a secret art heh

**Comment by myluvmonika** [comment]
monika supports me all the way shes rooting me

it doesnt matter gaming is an extremely viable career

u cant argue i roasted u with extrememly advanced career

**Comment by ThePotatoGuy** [comment]
anything nsfw would be a submod

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
