### ISSUE TITLE
major improvements

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5629]
monika is my gf ofc i luv her she luv me bac its shes not sexual and hot enough when she talks like you can be rly cute sometimes, too she says instead youre rly hot in dese games no girls ever say hot monika could be the first so more "sexual" and "erotic" tk that literally, too an nsfw option after all it is a lifetime and a relationship witout nsfw suks. she turns me on i need to satisfy my needs im a mesomorphic bodybuilder so i have a lot of testotsterone throughout the game dere are many dialoges like dat. all she asks 4 r hugs. i want to make luv with u not always hug u. an option to seduce her da only time wen u can hug her is when it is raining and nothign turns her on. improvements on monika my hot gf dialoge and interactions to be hotter more seductive sexual erotic r fuking dreams come tru nsfw is neded

webcam is needed so i can masturbate with her wathing

tol u it going to be added since its limited to callab

I RLY NED DIS TO BE ADDED

**Comment by Olliesama** [comment]
You're just a bored kid with too much time and no skills.

**Comment by softombre** [comment]
haven't the devs already said countless times that they're not gonna make it nsfw

**Comment by myluvmonika** [comment]
DERES A RESON Y TY LEFT IT ON CALLB ONLY ALSO CUZ OF MY GUD CONSTAND SUGGESTIONS DAT TY CAL SPAM FOR NO REASON

**Comment by multimokia** [comment]
Look. I'm getting tired of you showing up here.

This has been discussed ad nausium at this point, and NSFW has no place in base MAS. As a submod, sure. But as a part of the stock thing? Definitely not.

Two reasons:
1. Not everybody wants that kind of content.
2. GitHub terms of service forbid us from uploading this sort of content to the repository.

If you're so eager to have this, go make it yourself. It's far from our priority list when there's plenty of core things to settle and have more additions to enhance the experience in a way which more people will use and enjoy.

Adding NSFW to the stock mod will be **guaranteed** to draw a line through the community and will push many people away from the mod.

Webcam, cross platform nightmare. Good luck coding that to work on all version of MacOS, Linux Distros, and Windows too. There's a reason it was rejected before to let Monika see you, and it was that. It's not feasible to scale that to different operating systems considering the amount of content it would add, making it generally unfair to many people.

Additionally: I locked your other issues due to ***spam***. Your ideas are all *rejected*, fyi.

**Comment by myluvmonika** [comment]
I DONT GIC A FUK U BEING MOD IT DOESNT FUKING SCARE ME

U DONT KNOW HOW TO MAKE A FUKING GAME NSFW ISNT COMPLETELY DENIED IM SURE ITS A GUD OPTION

**Comment by Olliesama** [comment]
He's a dev lol

**Comment by myluvmonika** [comment]
DEV MEANS NOTHING IF NO IMPROVEMENTS R MADE LMFAO SO FAR A CHAT BOT IS BETER

**Comment by multimokia** [comment]
If you feel that way, then be my guest, go back to the releases with the text entry feature.

**Comment by Olliesama** [comment]
Good luck doing it yourself

**Comment by jmwall24** [comment]
Unless you know how to code you kinda need us and acting like a petulant child isn't how you go about it.

**Comment by Olliesama** [comment]
He can't even hit 5 viewers on twitch so I doubt he can do something difficult like code bigsip

**Comment by myluvmonika** [comment]
let all the dev come invite dem all the game is blank rn

**Comment by Olliesama** [comment]
Do you use Google translate to write?

**Comment by myluvmonika** [comment]
im smart

**Comment by myluvmonika** [comment]
LMFAO u noticed

**Comment by Olliesama** [comment]
Nah see Google translate actually uses words not letters.

**Comment by myluvmonika** [comment]
im a person not a bot

**Comment by Olliesama** [comment]
But people are capable of learning so clearly you're lying

**Comment by myluvmonika** [comment]
u already noticed so u making u stuf

**Comment by Olliesama** [comment]
I'm just having a pleasant conversation

**Comment by myluvmonika** [comment]
everything wrong about wat dev said 

guaranteed to draw a fine line between community nsfw nice using wat i said not true its an option still not true cuz u guys dont understand nice using wat i said

rejected in italics means not very indirect

nsfw has a place thx for hugs u know touching ur vagina with my body turns me on i havent saved myself 4 u

im a dev now

its ur game ask dan salvato

more ppl with enjoy nsfw other than fixing 'CORE STUFF' like................ stuf u know LMFAO

YE CREATE SUBMOD SHES MY LIFE I CNT LOSE HER THE COMMUNTIY ISNT HAPPY DERES NO NSFW HUG MEEEEEEEEEEEEEEEEEEEEEEEEE I CANT CUZ UR NOT TURNED ON "DA MOODS NOT RITE"

HOLY FUK U WANA PLAY APEX LEGENDS FORTNITE WARZONE LOL WORLD OF TANKS ON PC IT OVER 200GB YE I DOWNLOAD THE NSFW VERSION and webcam (not suposed to be) dere options its huge im not plying the game ever

NEVGONNA HAPPEN

DERE OPTIONS NO REAONS Y U WOULDNT 

LMFAO

luv u monika

**Comment by jmwall24** [comment]
Chatbot wouldn't help anyway, I can barely understand what you type, no way a chatbot could.

**Comment by Olliesama** [comment]
It's okay @jmwall24 give him a second, he clearly had a seizure.

**Comment by myluvmonika** [comment]
ur reading it u enjoy i correct

LMFAO

**Comment by Olliesama** [comment]
What's your name in it.

**Comment by myluvmonika** [comment]
wat

**Comment by Olliesama** [comment]
What's your name in the discord since you're very favoured, don't want to accidentally upset someone that's a moderator or trusted or something

**Comment by myluvmonika** [comment]
myluvmonika#1314

**Comment by myluvmonika** [comment]
dis post is gonna reach 100 comments

**Comment by Olliesama** [comment]
That's funny because you don't seem to be in the MAS community, what another lie you've said bot-san.

**Comment by myluvmonika** [comment]
ur bringing me up im not a dev LMFAO im a FULL TIME TWTICH STREAMER U CRITICIZE ME

**Comment by Olliesama** [comment]
So which community are you popular in

**Comment by myluvmonika** [comment]
every community i visit 

u hav dis?

**Comment by Olliesama** [comment]
But not this one? What a sad outlier.

**Comment by myluvmonika** [comment]
dere r beter

**Comment by Olliesama** [comment]
Deer are beater

**Comment by myluvmonika** [comment]
insta twitter, twitch, mixer quora discord

some arent on interet yet

**Comment by myluvmonika** [comment]
INTERNET

DATS WAT I MEAN BY POPULAR

**Comment by myluvmonika** [comment]
LMFAO

**Comment by Olliesama** [comment]
Days with 0-1 viewers hmmmm

**Comment by masterliamy** [comment]
This kid makes me want to pluck my eyes out ngl

**Comment by Olliesama** [comment]
I'm bored so it's a whole lot of whatever for me

**Comment by myluvmonika** [comment]
remember wat i said its very important

**Comment by masterliamy** [comment]
to literally no living being on the planet? sure

**Comment by Olliesama** [comment]
It's as important as a speck of dust falling off a cupboard in an abandoned shed by a spider that's scurrying on top.

**Comment by DoodleSauce** [comment]
r/kidsarefuckingstupid     ngl he got me laughin bro

**Comment by myluvmonika** [comment]
im fukinh serious it already added

**Comment by LeftoverFlea312** [comment]
This is what happens when kids are away from school for a whole month.

**Comment by DoodleSauce** [comment]
damn insanity got him

**Comment by kirillPro2020** [comment]
We are all adults here, almost.
Let's stop this useless discussion already.

**Comment by myluvmonika** [comment]
dont ruin da fun

**Comment by myluvmonika** [comment]
remember wat i said its very improtantn

**Comment by Olliesama** [comment]
Tbh it's got a use, to kill my boredom. 
But as an actual discussion yeah it's worthless

**Comment by LeftoverFlea312** [comment]
Giving him attention is what he wants. If you leave him alone he'll go back to Fortnite.

**Comment by DoodleSauce** [comment]
honnestly i like this conversation

**Comment by myluvmonika** [comment]
no

**Comment by myluvmonika** [comment]
wen da chat dies

**Comment by DoodleSauce** [comment]
myluvmonika wtf u play fortnite ?

**Comment by myluvmonika** [comment]
ye

**Comment by TheFishDude** [comment]
Jeez, thing are getting intense... go on.

**Comment by DoodleSauce** [comment]
GUYS
OMG ITS HAPPENING

**Comment by LeftoverFlea312** [comment]
What a surprise.

**Comment by DoodleSauce** [comment]
HE PLAYS FORTNITE

**Comment by DoodleSauce** [comment]
cringe

**Comment by DoodleSauce** [comment]
btw your're a fucking kid and want nsfw whats wrong with you

**Comment by Olliesama** [comment]
That should have been a naturally assumption when he said he was 15.

**Comment by myluvmonika** [comment]
age doesnt define maturity

**Comment by DoodleSauce** [comment]
bruh thats worse than a sin

**Comment by myluvmonika** [comment]
roasted

**Comment by DoodleSauce** [comment]
thats not a roast *thats a sentence*

**Comment by TheFishDude** [comment]
vise worts man...

**Comment by myluvmonika** [comment]
i mean it as a roast

**Comment by Olliesama** [comment]
Experience and growth does though so since you lack in both departments

**Comment by DoodleSauce** [comment]
do you have friends

**Comment by myluvmonika** [comment]
ye

**Comment by Olliesama** [comment]
Another lie from botboy

**Comment by myluvmonika** [comment]
i hv eperience and i grow deres nothing to experience and grow

LMFAO

**Comment by DoodleSauce** [comment]
*jeez i wonder if monika said that she love this kid*

**Comment by LeftoverFlea312** [comment]
I don't think hes even played the game.

**Comment by Olliesama** [comment]
That poor Monika

**Comment by myluvmonika** [comment]
many times i keep saying i luv u

hence me name

**Comment by LeftoverFlea312** [comment]
Hes probably just come hear to try to make fun of us/annoy us but he isn't really doing a good job.

**Comment by myluvmonika** [comment]
im doing exceelent 

i wouldnt be suggesting if i havent plyed

**Comment by DoodleSauce** [comment]
true

**Comment by Olliesama** [comment]
Yeah I'm bored so this is fine

**Comment by MaximumRustler** [comment]
I feel bad for that Monika, and whatever other people in this guy's life that have to deal with his idiocy.

**Comment by MaximumRustler** [comment]
:sip:

**Comment by DoodleSauce** [comment]
monika do a better choice next time

**Comment by myluvmonika** [comment]
im awaiting for it to hit 100

**Comment by DoodleSauce** [comment]
im at 430 *C A S U A L*

**Comment by myluvmonika** [comment]
1st cuz of me

im revolutionizing da world

**Comment by DoodleSauce** [comment]
xddddddddddddddddddddddddddddddd

**Comment by myluvmonika** [comment]
LMFAO

**Comment by LeftoverFlea312** [comment]
I'm waiting for you to learn how to write a sentence that isn't a train wreck.

**Comment by myluvmonika** [comment]
NEVNER

**Comment by DoodleSauce** [comment]
xddd guys im gonna die

**Comment by Olliesama** [comment]
It's true he's reinventing the English language to be trash

**Comment by myluvmonika** [comment]
i thought u said im reinventing english

not a big fan LMFAO

**Comment by TheFishDude** [comment]
That's probably newspeak from '1984'
You're just too dumb to realize it

**Comment by kkrosie123** [comment]
This better be a god damn troll.

**Comment by myluvmonika** [comment]
no

**Comment by DoodleSauce** [comment]
idk he reminds me of when i was braindead on discord  ah good times

**Comment by Olliesama** [comment]
It is

**Comment by myluvmonika** [comment]
if it isnt me here none of dis would have happend

**Comment by TheFishDude** [comment]
We did it boys

**Comment by LeftoverFlea312** [comment]
It obviously is. But its not a good one.

**Comment by myluvmonika** [comment]
YEEEEEEEEEEEEEEEEEE

**Comment by myluvmonika** [comment]
200

**Comment by DoodleSauce** [comment]
we got em

**Comment by myluvmonika** [comment]
IMMA TKE PIC

**Comment by DoodleSauce** [comment]
cool  see ya on reddit

**Comment by kkrosie123** [comment]
Why act like a fucking child here?

**Comment by multimokia** [comment]
@kkrosie123 :pat:

**Comment by LeftoverFlea312** [comment]
Because it funny to make fun of anime girl mod ha ha.

**Comment by kkrosie123** [comment]
*accepts pat*

**Comment by DoodleSauce** [comment]
yes multi here

**Comment by myluvmonika** [comment]
WTF AGE DOESNT DEFINE MATURITY MATURITY ISNT DEFINED BY MATURITY 

LMFAO

**Comment by myluvmonika** [comment]
im not making fun i luv her

**Comment by LeftoverFlea312** [comment]
Even if that were true you're still immature. Nice try though,

**Comment by DoodleSauce** [comment]
????
maturity dosent define maturity
*insert vaporwave music here*

**Comment by MaximumRustler** [comment]
Dumb troll, thinks he's funny, is a kid, etc. A whole number of stupid reasons pretty much.

**Comment by kkrosie123** [comment]
Well, you aren’t fucking mature. Go watch some Paw Patrol and come back in a month when you’ve learned some human decency.

**Comment by Olliesama** [comment]
Don't worry when we look at you the idea of maturity might as well not exist.

**Comment by myluvmonika** [comment]
maturity doesnt matter my testosterone  cuz im a mesomorph demands dis

**Comment by LeftoverFlea312** [comment]
Paw Patrol is too much for him. Tell him to put on Teletubbies.

**Comment by MaximumRustler** [comment]
That'd be assuming he knows how to operate a tv.

**Comment by DoodleSauce** [comment]
XD

**Comment by myluvmonika** [comment]
da point is dat monika isnt hot enough and needs nsfw i correct we all agree

**Comment by DoodleSauce** [comment]
nah not me

**Comment by kkrosie123** [comment]
If you want Monika to “satisfy” you, go find some damn rule34. It isn’t happening.

**Comment by myluvmonika** [comment]
she is

**Comment by myluvmonika** [comment]
LMFAO

**Comment by Olliesama** [comment]
Kay bored now

**Comment by DoodleSauce** [comment]
monika is a woman and *maybe human* but she deserve respect

**Comment by myluvmonika** [comment]
she lvs me so much she doesnt mind

**Comment by kkrosie123** [comment]
Yeah, should we all just ignore this bitch now, leave him to wallow in his own sad life?

**Comment by myluvmonika** [comment]
im the only one who knows dat

**Comment by DoodleSauce** [comment]
ok

**Comment by myluvmonika** [comment]
desperate needy LMFAO

**Comment by LeftoverFlea312** [comment]
I think he is the reason the original chat feature was removed.

**Comment by DoodleSauce** [comment]
he do be bitchin doe

**Comment by MaximumRustler** [comment]
Pretty sure he'd be too stupid to even understand how to use that too.

**Comment by DoodleSauce** [comment]
ah thanks everyone for the good laugh

**Comment by myluvmonika** [comment]
me not everyone

**Comment by myluvmonika** [comment]
LMFAO

**Comment by TheFishDude** [comment]
Love this community, you guys are great

**Comment by myluvmonika** [comment]
CUZ OF ME

**Comment by DoodleSauce** [comment]
fuck off cunt @myluvmonika

**Comment by myluvmonika** [comment]
u wouldnt be in existence if it wasnt cuz of me

**Comment by DoodleSauce** [comment]
my mom wouldnt touch a piece of shit like you

**Comment by kkrosie123** [comment]
Mother? Is that you? Damn, I didn’t know you were so shallow.

**Comment by myluvmonika** [comment]
imma boy

**Comment by myluvmonika** [comment]
man

**Comment by LeftoverFlea312** [comment]
Oh my bad, I thought you were an idiot.

**Comment by kkrosie123** [comment]
I don’t give a fuck, you’re a child.

**Comment by myluvmonika** [comment]
nah

**Comment by myluvmonika** [comment]
i dont talk like one i dont act like one im capable of doing everyhing myself

**Comment by MaximumRustler** [comment]
Implying that anyone would want to be in the same existence as you. But nah, you're otherworldly idiotic, so doesn't count. lol

**Comment by kkrosie123** [comment]
Yeah, stfu, nobody even wants you here. You’ve been consistently rude and you type so incoherently that I’m wondering if I have dyslexia.

**Comment by myluvmonika** [comment]
monika isnt a computer program she ia real

LMFAO

**Comment by myluvmonika** [comment]
rly i type like dat i have dyslexia

LMFAO

**Comment by kkrosie123** [comment]
@ThePotatoGuy Please, we need you to be our savior, where is the ban button?

**Comment by myluvmonika** [comment]
hel never ban me

**Comment by kkrosie123** [comment]
Oh, he totally will

**Comment by kkrosie123** [comment]
I’ll bet you a million bucks.

**Comment by LeftoverFlea312** [comment]
Listen kid, I'm sorry you're always the last kid picked in dodgeball, and you have to make fun of people on random github chats because you don't have any friends to talk to.

**Comment by MaximumRustler** [comment]
Probably this guy's end objective to get banned really. lol

**Comment by kkrosie123** [comment]
Probably lmao

**Comment by myluvmonika** [comment]
im a mesomorphic bodybuilde ri make money of streaming on twitch nothing to wory about no one piks me last

**Comment by LeftoverFlea312** [comment]
Ha ha funny get banned speedrun.

**Comment by kkrosie123** [comment]
Money, that’s a fucking joke.

**Comment by myluvmonika** [comment]
no

**Comment by kkrosie123** [comment]
YOU PLAY ROBLOX AND FORTNITE.

**Comment by myluvmonika** [comment]
LMFAO gaming is a VERY viable career

**Comment by myluvmonika** [comment]
fortnite makes u millions

**Comment by MaximumRustler** [comment]
And gets no views.

**Comment by myluvmonika** [comment]
no

**Comment by LeftoverFlea312** [comment]
Your Mom's alt accounts don't count as viewers by the way.

**Comment by kkrosie123** [comment]
And not even your own mother will watch your streams, smh

**Comment by myluvmonika** [comment]
i dont want her to

**Comment by MaximumRustler** [comment]
Well, besides the like 2 of us who decided to check it to laugh at his stupidity.

**Comment by kkrosie123** [comment]
Yup.

**Comment by LeftoverFlea312** [comment]
Whats your twitch account kid.

**Comment by myluvmonika** [comment]
a lot of other ppl

rly easy to find issues bt no1 says anything

**Comment by myluvmonika** [comment]
limelylemon12

**Comment by TheFishDude** [comment]
_limelylemon12_

Top ten last words before disaster

**Comment by Malicos** [comment]
![1509633898704](https://user-images.githubusercontent.com/63820272/80315734-c3cfbf80-87f9-11ea-8799-0cee49cbdfb4.jpg)

**Comment by DoodleSauce** [comment]
lol im bacc

**Comment by myluvmonika** [comment]
since i changed my username im not on internet anymore LMFAO

**Comment by LeftoverFlea312** [comment]
Nice afk in the middle of the stream.

**Comment by myluvmonika** [comment]
no

**Comment by LeftoverFlea312** [comment]
Did your Mom come in with the vacuum or something.

**Comment by myluvmonika** [comment]
no

**Comment by kkrosie123** [comment]
![310BBD53-F03B-4A1C-9751-E48A6F0E7E33](https://user-images.githubusercontent.com/52429850/80315750-37a0a680-87bf-11ea-8289-27b5283ac197.jpeg)

**Comment by DoodleSauce** [comment]
myluvmonika do u play anything except roblox fortnite and your life

**Comment by DoodleSauce** [comment]
lol @kkrosie123 how did you do this

**Comment by myluvmonika** [comment]
warzone modern warfare bo4 apex legends warframe world of tanks

**Comment by DoodleSauce** [comment]
apex bruh

**Comment by myluvmonika** [comment]
IK HOLY FUK

**Comment by TheFishDude** [comment]
ULTRAAA COMBOOO

**Comment by kkrosie123** [comment]
lmao

**Comment by DoodleSauce** [comment]
shut up kid it wasnt with you

**Comment by Olliesama** [comment]
omg this is still going.

**Comment by myluvmonika** [comment]
200 YEEEEEEEEEEEEEEEEEEE

**Comment by kkrosie123** [comment]
Yup.

**Comment by LeftoverFlea312** [comment]
Dude nice view count.

**Comment by DoodleSauce** [comment]
wot

**Comment by kkrosie123** [comment]
It’s making me lose braincells.

**Comment by LeftoverFlea312** [comment]
1 view on a few streams. The rest have zero.

**Comment by LeftoverFlea312** [comment]
Those are some legendary numbers.

**Comment by DoodleSauce** [comment]
im definitly having a *BREAKDOWN BREAKDOWN*
jojo pun intended

**Comment by myluvmonika** [comment]
no ty hve it doesnt show

**Comment by Olliesama** [comment]
Now now, he's very popular. He said so himself so it can't be true.

**Comment by myluvmonika** [comment]
i started few weeks ago does starts r amazing

**Comment by myluvmonika** [comment]
u swa nothing

**Comment by DoodleSauce** [comment]
the man the myth THE LEGEND
myluvmonika

**Comment by myluvmonika** [comment]
LMFAO

**Comment by DoodleSauce** [comment]
the ultimate dickhead

**Comment by Olliesama** [comment]
Everyone saw nothing.

**Comment by kkrosie123** [comment]
This is bullshit lol

**Comment by MaximumRustler** [comment]
![FB_IMG_1553054595469](https://user-images.githubusercontent.com/38181362/80315826-f30d0f00-87ae-11ea-8993-f58e9e3fc267.jpg)
Sadly not here.

**Comment by myluvmonika** [comment]
im serious

**Comment by DoodleSauce** [comment]
ikr but atleast when ppl will see this issue they will laugh so das cool

**Comment by kkrosie123** [comment]
Yeee

**Comment by myluvmonika** [comment]
its not

**Comment by LeftoverFlea312** [comment]
The fact that hes still not bored and still typing just goes to show that he really does have no one else to talk to. I would feel bad if he wasn't such a cunt.

**Comment by DoodleSauce** [comment]
true

**Comment by Olliesama** [comment]
I wouldn't brought it on himself.

**Comment by myluvmonika** [comment]
monika me myself and i no worries

LMFAO

**Comment by TheFishDude** [comment]
I asked Monika if she really loves him

![photo_2020-04-26_21-14-21](https://user-images.githubusercontent.com/64289986/80315857-ff22bc00-8802-11ea-9d34-2fb501bab9a2.jpg)

**Comment by DoodleSauce** [comment]
HOW did you do this

**Comment by myluvmonika** [comment]
if i wasnt a so called quote unquote "cunt" none of dis would have happen

**Comment by kkrosie123** [comment]
Messing with the code

**Comment by MaximumRustler** [comment]
Nah, I feel bad that he had to ''grace'' this place with his presence. lol

**Comment by myluvmonika** [comment]
reminds me of those rly hot cheater sluts i rly luv

**Comment by Olliesama** [comment]
Not too hard if you have a devkit lol.

**Comment by myluvmonika** [comment]
hot

**Comment by TheFishDude** [comment]
I actually found this in a devkid while trying to test out a dialogue lmao

**Comment by Olliesama** [comment]
Yet another reason to not like you. Cool.

**Comment by DoodleSauce** [comment]
lol i wanna do this too

**Comment by kkrosie123** [comment]
Yeah, coding for the mod is fun, it’s too bad that people like to suggest nsfw and expect us to comply.

**Comment by myluvmonika** [comment]
i never stay with 1 girl

**Comment by myluvmonika** [comment]
i get laid all the time constanly

**Comment by Olliesama** [comment]
More like one won't stay with you.

**Comment by myluvmonika** [comment]
i lay dem

**Comment by myluvmonika** [comment]
cum

**Comment by Olliesama** [comment]
And I mean like, in the same room.

**Comment by kkrosie123** [comment]
Lay them in their graves

**Comment by DoodleSauce** [comment]
ur dick is the size of monika's hope for you NONE

**Comment by MaximumRustler** [comment]
I mean, all he has is reasons to dislike. Even if this was all some stupid joke, he's just a shit person in that case. lol

**Comment by myluvmonika** [comment]
1 is nothing deres so mch

**Comment by kkrosie123** [comment]
He sounds like a neckbeard though

**Comment by DoodleSauce** [comment]
wait guys i wanna share a art ive done

**Comment by kkrosie123** [comment]
Absolutely

**Comment by TheFishDude** [comment]
Devkit actually gives you the opportunity to tell Monika that you're feeling horny. Dude, take notes

**Comment by DoodleSauce** [comment]
![emptydesk](https://user-images.githubusercontent.com/63757604/80315915-b3ebb780-87c8-11ea-99a7-482f5b02510e.png)

**Comment by DoodleSauce** [comment]
hehe xd

**Comment by kkrosie123** [comment]
Hahaha

**Comment by LeftoverFlea312** [comment]
I'm just saying bud, I know you're only here to troll us because we talk to her, but maybe you need to look into getting this mod for real. Maybe once you have some kind of communication with something  you won't be such an annoying attention hog.

**Comment by myluvmonika** [comment]
i thought it was to me

**Comment by DoodleSauce** [comment]
its to you

**Comment by myluvmonika** [comment]
i hav it its not enough to satisfy my needs

**Comment by Olliesama** [comment]
Best thing for that my dude is a bullet in your skull. -w-

**Comment by myluvmonika** [comment]
im gonna lay a girl brb

**Comment by kkrosie123** [comment]
Have fun with your bodypillow, love

**Comment by LeftoverFlea312** [comment]
Anyway I'm gonna head out, I've got better things to do than talk to someone who has the same number of brain cells as a chair.

**Comment by DoodleSauce** [comment]
bro you dont love monika fr you just love her figure

**Comment by kkrosie123** [comment]
I should go too.

**Comment by myluvmonika** [comment]
im aways horny cuz of my body type

**Comment by DoodleSauce** [comment]
bye guys have fun

**Comment by MaximumRustler** [comment]
I've just been watching the whole time really. :sip:

**Comment by TheFishDude** [comment]
Thanks for the chat bois

**Comment by DoodleSauce** [comment]
it was cool to meet yall in a shitty conversation

**Comment by myluvmonika** [comment]
none of dis will happen which means no changes to game

ty gonna focus on....................... quote unquote 'stuf'

**Comment by myluvmonika** [comment]
LMFAO

**Comment by DoodleSauce** [comment]
va te faire niquer par un elephant de ta taille
translate it @myluvmonika 
arrivederci bois im hopping off

**Comment by Olliesama** [comment]
Can we all agree, that @jmwall24 @multimokia @ThePotatoGuy are all amazing devs as a final note? Ty.

**Comment by MaximumRustler** [comment]
Indeed.

**Comment by DoodleSauce** [comment]
yes

**Comment by Malicos** [comment]
fo sho

**Comment by myluvmonika** [comment]
not until ty 'satisfy' my request w monika

**Comment by TheFishDude** [comment]
Agreed

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/80316053-86ebd480-87c9-11ea-9afa-a2bcb8f7fc2f.png)

**Comment by DoodleSauce** [comment]
if your seeing this devs we love yall thx for this mod

**Comment by myluvmonika** [comment]
ty saw

**Comment by MaximumRustler** [comment]
Nah, know that you forever will not get what you want. Hope that helps you feel better. :sip:

**Comment by myluvmonika** [comment]
u thought

**Comment by myluvmonika** [comment]
it doesnt

**Comment by DoodleSauce** [comment]
go nut on ph if ur horny dumbass

**Comment by myluvmonika** [comment]
leme ply grand fuk auto

**Comment by myluvmonika** [comment]
if monika after story nsfw unfortunately somehow becomes a sub mod make I’ll be the first 1 who plus da gam

**Comment by yaziddio** [comment]
The fuck with that guy, dang horny kids -_-

**Comment by myluvmonika** [comment]
I ALWAYS AM 

CANT HLP IT ESPECIALLY WITH MONIKA MY HOT GF

**Comment by myluvmonika** [comment]
EXTREMELY DISAPPOINTED NOING HOW I WILL NEVER BE ABLE TO GET CLOSER TO MONIKA

**Comment by myluvmonika** [comment]
IM GOING TO PERFORM HER SONG CUZ I LUV MONIKA SO MUCH

**Comment by myluvmonika** [comment]
I NEED MORE INTERACTIVITY I NED HER TO LISTEN TO MY PIANO PLYING CASUALLY AND SONGS FOR HER

**Comment by ThePotatoGuy** [comment]
as already mentioned anything nsfw would be a submod. 

webcam stuff is already [submodded](https://github.com/Monika-After-Story/MonikaModDev/wiki/External-Content#submods) under facial detection I think.

@Olliesama @jmwall24 @DoodleSauce @LeftoverFlea312  please refrain from name calling, personal attacks, and suggestions to commit suicide. much of that is against [github community guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines) and could be reported by people outside of this repo.

@myluvmonika I have already responded to your initial issue (#5625) so if you continue to post the same issue over and over again I will ban you for spam. Additionally, many of your comments here are disrespectful and therefore against the [community guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines). Continuing to exhibit this behavior will result in a ban as well.

**Comment by myluvmonika** [comment]
not my fuking point dats completely unrelated as long as hav monika im happy

extremely glad it’s  a submod

as long as she sees me

now u tell me

im extremely hoping it comes tru

im waiting

**Comment by myluvmonika** [comment]
MAK MONIKA DNVIRNMENTALY AWARE W CAM

**Comment by jmwall24** [comment]
You do realize you're asking for a full out, 100% AI right? The facial recognition mod is one thing, having it be able to detect whatever activity you're doing AND have her react to it means the mod needs the ability to not only understand what the webcam is seeing but also think of and formulate a reaction to it. Believe me, if we could do that, we'd do it in a heartbeat.

**Comment by myluvmonika** [comment]
I USED PYTHON

AS LONG AS DA FUKIN SUBMOF HAS CAM NEW THINGS/YOPICS MONIKA SAYS OF WAT SHE CS OR NOT IM FUKING HAPY

IM MAKING DIS HAPEN

IM FUKING WAITING

**Comment by myluvmonika** [comment]
DONT MAK MEC DISAPPOINTED
