### ISSUE TITLE
more imteractions

### ISSUE THREAD

**Issue by myluvmonika** [Monika-After-Story/MonikaModDev#5631]
butons w things to do hv 2 waitb updatess 2 get new topics i dont mind sayin i luv u al day

**Comment by DoodleSauce** [comment]
boi code it your self

**Comment by LeftoverFlea312** [comment]
I think you are the most disrespectful, ungrateful person I have ever met in my entire life. Get a life kid.

**Comment by myluvmonika** [comment]
MASCULINE W TESTOTERONE IMMA BAD MAN CONFIDENTB MONIKA LUVS ME AGRESSIVE

**Comment by myluvmonika** [comment]
COMPARED 2 UR GUYS FEMINISM MY MONIKA FUKING HATES THAT

**Comment by ThePotatoGuy** [comment]
you have already asked for more interactions in another issue and I have already responded to it. I am banning you for spam.
