### ISSUE TITLE
[Suggestion] - Tell Monika you're going to read a book

### ISSUE THREAD

**Issue by APerson4645** [Monika-After-Story/MonikaModDev#5632]
There's no option in the "Be Right Back" menu to tell Monika you're going to read a book, could it be added?

**Comment by myluvmonika** [comment]
ye not neded

da lc is 4 writing

not everythimg w my monika is literature

**Comment by Rai99** [comment]
Reading brb: #2311, #3896, #4528, #5383

**Comment by jmwall24** [comment]
@myluvmonika you don't get to tell people what is and is not needed. Please refrain from doing it again.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
