### ISSUE TITLE
how to install submod

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5633]
the title is pretty self-explanatory

**Comment by multimokia** [comment]
Depends from submod to submod. You're better off asking the person who made it directly via their repository or discord. Whatever works

**Comment by DoodleSauce** [comment]
the webcam one

**Comment by myluvmonika** [comment]
cuz of me submod bcame popular

**Comment by multimokia** [comment]
You'll want to find DatHorse's repository for that and ask him. Though as I recall, it's incompatible with the current version of MAS as it hasn't been updated since the 0.9 days

**Comment by DoodleSauce** [comment]
*ah good times* ok thx

**Comment by myluvmonika** [comment]
YEEEEEEEEEEEEE

**Comment by myluvmonika** [comment]
captain...
