### ISSUE TITLE
contribution question

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5635]
ok so i want to contribute but need a hand
but when i open .rpyc files i see gibberish what should i do to translate this

**Comment by DoodleSauce** [comment]
btw @myluvmonika dont comment anything i didnt ask you

**Comment by multimokia** [comment]
You don't need to decompile anything. Grab a copy of the source code from the `Code` tab.

**Comment by DoodleSauce** [comment]
where is the code tab ?

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/80335883-a44d8c80-8823-11ea-9d3c-1750c17034cc.png)

**Comment by DoodleSauce** [comment]
oh ok im so stoopid :facepalm: thx
