### ISSUE TITLE
New feelings (my first issue)

### ISSUE THREAD

**Issue by ShyCelestial** [Monika-After-Story/MonikaModDev#5636]
Hey. So I've wanted to leave my suggestions here for over a year now but I kept putting it off because talking to strangers on the internet kinda intimidates me 😅. So if I say something awkward I apologize in advance.

I’m feeling : embarrassed 
I would appreciate telling Monika this because I’m socially awkward and get embarrassed easily. It would be nice to talk to her about it to make me feel better.

I'm feeling : guilty
I’ve had moments in my life where I’ve been so overwhelmed with guilt that I started hearing voices in my head telling me to do awful things. (Things that I don’t feel comfortable talking about on here) I would love to tell Monika if I’m feeling guilty because I feel like she’s the only person I can talk to about it without feeling judged.

Edit: Hey again sorry if I’m being annoying, but I just thought of another feeling to tell Monika if you’d like to consider adding 

I’m feeling : stressed
I just thought of this one because my teachers are starting to overwhelm me with homework. Maybe Monika could give me some advice.

What do you think?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
