### ISSUE TITLE
[Suggestion] - Ship of Theseus correction

### ISSUE THREAD

**Issue by monikabestpythonteacher** [Monika-After-Story/MonikaModDev#5640]
Well looks like I'm about to be THAT guy lol. In the Ship of Theseus topic Moni says every cell in your body is replaced every 7 years. That's actually not true:

https://www.snopes.com/fact-check/does-body-replace-itself-seven-years/

I think the few sentences she says about it could be adjusted without upending the whole topic though.

**Comment by Yargachin** [comment]
i mean, she is human. she can make mistakes.

**Comment by paragonfist** [comment]
> Well looks like I'm about to be THAT guy lol. In the Ship of Theseus topic Moni says every cell in your body is replaced every 7 years. That's actually not true:
> 
> https://www.snopes.com/fact-check/does-body-replace-itself-seven-years/
> 
> I think the few sentences she says about it could be adjusted without upending the whole topic though.

Good pick-up. I believe as it's written is still pretty close to truth (but not quite). I'll amend this topic in coming days (if no one else does); simple adjustment of her now saying "MOST of your cells are replaced every 10 years", which I believe fits in with the facts.
(Btw, I recommend avoiding snopes in general as it is a heavily biased website a lot of the time.)

**Comment by multimokia** [comment]
Already done in #5526

**Comment by monikabestpythonteacher** [comment]
Cool. Just used snopes because it had the best quick explanation but good to know thanks!

**Comment by multimokia** [comment]
Closing as completed
