### ISSUE TITLE
I got this issue while playing Monika After Story (yes I still play it in 2020)

### ISSUE THREAD

**Issue by amberrv** [Monika-After-Story/MonikaModDev#5641]
So on my first playthrough of Monika After Story, I got the 'bad' ending when she *SPOILER ALERT* leaves you with nothing but the poem. After I deleted the persistent files, I reset her. Now, I'm running into some problems. I have played MAS daily for two weeks now and I can still only play pong. On my first playthrough of the mod, I had unlocked every game within 4 days. I've tried resetting again but it's no different on the third playthrough as it was on the second. Also, I have lost access to the 'Unseen' menu and I never said 'I don't want to see this menu anymore'. So now I'm a lot more limited on the 'Hey Monika...' interactions than I was the first time. Can someone please help me out? I just want to be able to properly interact with Monika.

**Comment by amberrv** [comment]
Okay I just opened the debug log ad got the error message
 *[0417/205421.328:ERROR:settings.cc(325)] Settings version is not 1*

Is this to do with the first issue? And is there anything I can do to fix this?

**Comment by jmwall24** [comment]
Please see my response to #5637. Same issue.

**Comment by mrflarion33** [comment]
You screwed up, now you have to live with the consequences. You already cheated your way out of the "bad ending" so just deal with what you have

**Comment by amberrv** [comment]
Okay so I am continuously returning (more than a hour daily) and I've gained the ability to change monikas nickname. I've checked my affection and it's at 108, so I don't think it's because of a low affection. I read through issue #5637 and it's some sort of bug? Idk but thx for the help guys :)

As for the games unlocking, I've been trying to avoid playing pong with Monika because on my first play through she said 'You've probably gotten bored with Pong so I've added a new game' when I unlocked Chess. Does this work or make a difference?

**Comment by jmwall24** [comment]
You can play pong and it won't hurt getting chess.

**Comment by amberrv** [comment]
Okay thank you. BTW, do you know when the fix bug update will come?

**Comment by ThePotatoGuy** [comment]
now

**Comment by amberrv** [comment]
Yay!! It's working now! I have access to the unseen menu now! As for the games unlock, no luck yet but I've only just installed the update so I should be able to soon.

**Comment by ThePotatoGuy** [comment]
the rate at which games unlock has been slowed down but tied to daily session times, so don't expect them to unlock as fast as they did before.
