### ISSUE TITLE
How do I control Monika's face when adding a new conversation?

### ISSUE THREAD

**Issue by Vision-kong** [Monika-After-Story/MonikaModDev#5642]
hi,everyone
I've been playing Monika after story for a while , and I've experienced all the topics in the mod,so I want to add some new topics myself, but I don't know how I should control Monika's expression,so who can tell me what is the abbreviation of each expression of Monika? I really  really want to contribute to this game.

**Comment by Booplicate** [comment]
Use [expressions previewer](https://github.com/Monika-After-Story/MonikaModDev/blob/master/FAQ.md#how-do-i-find-the-spritecode-for-an-expression).
I'd suggest to read [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#introduction), it has answers on most of your questions, and will help to avoid the pitfalls.

**Comment by Vision-kong** [comment]
Oh, thank you. It's really useful!

**Comment by Vision-kong** [comment]
Oh, thank you. It's really useful!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
