### ISSUE TITLE
Someone discard me please spritecode.(If not difficult).

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5643]
It will be more convenient for me to work with the test option

**Comment by multimokia** [comment]
What are you asking for?

**Comment by kirillPro2020** [comment]
When writing a dialogue, I came across this type of command m 1rusdla and as I understand it, they are responsible for changing Monica's positions. It will be strange if she is sad or something else during a conversation.
(I want these commands to be dropped and what they mean).

**Comment by multimokia** [comment]
`1rusdla` is a sprite code. It corresponds to a sprite to show for the line it's on. These will not be dropped as they've been in place for a while now and are quite functional (and clear what exact sprites they are) when you get used to the system.

If a sprite doesn't work for the line, just change the code to something that works

**Comment by kirillPro2020** [comment]
I mean, how do these teams influence Monika, her emotions during the dialogue.
(Probably it should have been said right away, I have not installed the modification at the moment. For some reason. And I can’t see the sprite code).
Because of this, I ask you to drop me a sprite code.

**Comment by multimokia** [comment]
Use the [expression previewer](https://github.com/Monika-After-Story/MonikaModDev/blob/master/FAQ.md#how-do-i-find-the-spritecode-for-an-expression) to build sprite codes visually.

**Comment by kirillPro2020** [comment]
How to download this file?
I can not find the download button.

**Comment by multimokia** [comment]
Click the `Raw` button, then right click the page it opens and click download. Just make sure it downloads as an `rpy` file and not a `txt` file

**Comment by kirillPro2020** [comment]
Thank.

**Comment by kirillPro2020** [comment]
Remind me how to put spritepacks. Which directory should I throw this file into?

**Comment by kirillPro2020** [comment]
No longer needed.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
