### ISSUE TITLE
[Suggestion] - I think parts of Monika's Lullaby can be unsettling.

### ISSUE THREAD

**Issue by bo28111** [Monika-After-Story/MonikaModDev#5644]
> I'm very new to GitHub, I hope I'm doing this right.
> If you hold Monika for long enough, music starts to play in the background. The "Your Reality" cover sounds lovely, but what I think is supposed to be "Okay, Everyone!" is kind of unsettling. The way it's slowed down makes it sound off-key, and more like something you'd hear in the second half of the original game. I'm still not entirely sure if it's actually off, or if it's just me. It's not a big issue, but it definitely spoiled my first experience with it when I woke up and thought I was back in act 2.

I'm rewriting this because I understand more about the subject than I did initially. Monika's Lullaby, the song that plays when Monika falls asleep while you hold her, sounds great in about the first half. However, I think the second half of it's a bit too off putting. Some of the notes reach a _very_ high pitch, and I feel like for anyone who's played this game before, the slightly too long notes can feel a bit too reminiscent of something from act 2. This could just be personal preference, in which case it's not a big deal. But If any substantial amount of people also feel this way, I think changing/cutting out that part would make it a better experience.

**Comment by DoodleSauce** [comment]
its because its a easter egg
maybe.

**Comment by Dank-Elf-Boy** [comment]
It's basically just a cute, slowed down version of "Your Reality" with a bell chime theme added.

**It's suppose to let you know when she has fallen asleep.**

**Comment by bo28111** [comment]
> 
> 
> It's basically just a cute, slowed down version of "Your Reality" with a bell chime theme added.
> 
> **It's suppose to let you know when she has fallen asleep.**

As I said, the slowed down version of "Your Reality" is fine. There seems to be two songs that it repeats though. If you wait long enough the one I'm referring to should start playing. It's definitely a different song, and I'm 90% sure it's a slowed down version of Okay, Everyone!

**Comment by Dank-Elf-Boy** [comment]
Huh. Well I usually keep the music off because it gets repetitive. I'll take another listen when she falls asleep. You're probably referencing the part where the theme kind of lingers in between the "Your Reality" music.

Most of the themes played in DDLC sound very similar. But I assure you, this song you're hearing has no reference to Act 2. The mod only spooks you if you activate it's Easter eggs.

**Comment by bo28111** [comment]
> 
> 
> Huh. Well I usually keep the music off because it gets repetitive. I'll take another listen when she falls asleep. You're probably referencing the part where the theme kind of lingers in between the "Your Reality" music.
> 
> Most of the themes played in DDLC sound very similar. But I assure you, this song you're hearing has no reference to Act 2. The mod only spooks you if you activate it's Easter eggs.

Ah well, thanks for at least being willing to check. I'm not sure exactly how long to suggest you wait, but hopefully it'll be recognizable when it loops/switches songs, whichever is _actually_ going on. Get back to me when you're able, I want to make sure I'm not going crazy 😛

**Comment by bo28111** [comment]
Ah. Well. I went into the files and it is indeed one song. I apologize for the misunderstanding. I do still think however that the notes in the second half of the song are a bit.. wrong. I'm not sure what to do here now, since only a part of this issue is accurate.

**Comment by Dank-Elf-Boy** [comment]
Haha, well if you feel like this no longer needs a discussion, you can close the issue. Or, if you want you could keep it up and just recommend a new theme. It's up to you.

**Comment by fromulus** [comment]
[Monika's Lullaby.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4544074/Monika.s.Lullaby.zip)

Quickly edited the music in audacity to remove the _Okay, everyone!_ part.
Just replace the one that's already in your mod folder with this one.  
And make sure to keep a backup of it somewhere, because the game will revert it back to the original one every time a new update is out.

**Comment by bo28111** [comment]
> [Monika's Lullaby.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4544074/Monika.s.Lullaby.zip)
> 
> Quickly edited the music in audacity to remove the _Okay, everyone!_ part.
> Just replace the one that's already in your mod folder with this one.
> And make sure to keep a backup of it somewhere, because the game will revert it back to the original one every time a new update is out.

Ah thank you so much. I'll close this now. I suppose I should have just thought to do that myself.
