### ISSUE TITLE
Did I do something wrong? I can not send the finished dialogue.

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5645]

**Comment by multimokia** [comment]
Open a pull request with the dialogue to submit it. Check the contributing guidelines to see how.

**Comment by kirillPro2020** [comment]
That's exactly what I did.

**Comment by kirillPro2020** [comment]
I CAN NOT SEND.

**Comment by ThePotatoGuy** [comment]
Not much we can say other than ensure you were following the instructions. You could also review [how to make a pull request on github](https://help.github.com/en/desktop/contributing-to-projects/creating-an-issue-or-pull-request#creating-a-new-pull-request).
