### ISSUE TITLE
I can't find the thread I need...

### ISSUE THREAD

**Issue by octogonSmuggler** [Monika-After-Story/MonikaModDev#5649]
Can someone link me to the thread about how to fix the issue with Monika disappearing after taking her somewhere?

**Comment by kirillPro2020** [comment]
That is, she is there, but you do not see her?

**Comment by jmwall24** [comment]
You need to restore a backup persistent from before you took her out. Please refer to https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by LegoshiM** [comment]
I need help, I already tried everything but I can't play the MAS mod, always giving this error:

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-topics.rpy", line 8460, in script
  File "game/script-topics.rpy", line 8474, in <module>
  File "game/event-handler.rpy", line 1315, in addEvent
NameError: name 'mas_seenLabels' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-topics.rpy", line 8460, in script
  File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-topics.rpy", line 8474, in <module>
  File "game/event-handler.rpy", line 1315, in addEvent
  File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'mas_seenLabels' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.7
[/code]

**Comment by multimokia** [comment]
Why did you roll back to 0.10.7?

**Comment by LegoshiM** [comment]
i'm from brazil and my english is not very good yet, the latest version translated into portuguese is 0.10.7

**Comment by multimokia** [comment]
You need to restore a persistent backup from before updating

**Comment by LegoshiM** [comment]
I had downloaded it once and I was able to play it smoothly, but asked to update and when I tried to download 0.10.7 again this is giving this error

**Comment by LegoshiM** [comment]
> Você precisa restaurar um backup persistente antes de atualizar


as well? and how do i do it?

**Comment by LegoshiM** [comment]
do I need to have a backup of the original game before changing it into a mod?

**Comment by multimokia** [comment]
Check the link above to see how to restore an older persistent.

**Comment by LegoshiM** [comment]
has no file called "persistent"

**Comment by LegoshiM** [comment]
I delete the files that worked the first time; _; I don't think it will be possible to restore them, I used a new copy from there

**Comment by LegoshiM** [comment]
> Preciso de ajuda, já tentei de tudo, mas não consigo jogar o mod MAS, sempre dando este erro:
> 
> [code]
> Sinto muito, mas ocorreu uma exceção não capturada.
> 
> Durante a execução do código do jogo:
> Arquivo "game / script-topics.rpy", linha 8460, no script
> Arquivo "game / script-topics.rpy", linha 8474, no
> Arquivo "game / script-topics.rpy ", linha 1315, em addEvent
> NameError: o nome 'mas_seenLabels' não está definido
> 
> - Full Traceback ---------------------------------------------- --------------
> 
> Traceback completo:
> Arquivo "game / script-topics.rpy", linha 8460, no script
> Arquivo "C: \ Usuários \ Pedro Moura \ Desktop \ DDLC-1.1.1-pc \ renpy \ ast.py", linha 814, em execute
> renpy.python.py_exec_bytecode (self.code.bytecode, self.hide, store = self.store)
> Arquivo "C: \ Usuários \ Pedro Moura \ Desktop \ DDLC-1.1.1-pc \ renpy \ python.py", linha 1719, em py_exec_bytecode
> exec bytecode em globais, locais
> Arquivo "game / script-topics.rpy", linha 8474, no
> arquivo "game / event-handler.rpy", linha 1315, no
> arquivo addEvent "C: \ Users \ Pedro Moura \ Desktop \ DDLC-1.1.1-pc \ renpy \ python.py ", linha 1749, em py_eval
> retorne py_eval_bytecode (código, globais, locais)
> Arquivo" C: \ Users \ Pedro Moura \ Desktop \ DDLC-1.1.1 -pc \ renpy \ python.py ",linha 1743, em py_eval_bytecode
> return eval (bytecode, globals, locals) O
> arquivo "", linha 1, em
> NameError: name 'mas_seenLabels' não está definido
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.10.7
> [/ código]

there is nothing i can do about this error?

**Comment by multimokia** [comment]
You have to have a persistent. That's your save data.

The issue here is that there's functions from the new version in your persistent data, they don't exist in the older version and are causing the error.

Again, there ***has*** to be a persistent, follow the instructions from that link carefully to see how to find it. But if you're getting this now and you didn't have any manual backups, there's no way to roll back and you'll have to stay with the current version until the translation gets updated.

**Comment by LegoshiM** [comment]
I didn't find the part "persistent" :,) maybe it's a sign for me to practice the language
thanks for trying to help me

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
