### ISSUE TITLE
how do i download files from the code tab

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5650]
i dont know there isnt a download button.
neither when i right click

**Comment by Abc2557** [comment]
I'm pretty sure there is a "Raw" button that lets you download a file

**Comment by DoodleSauce** [comment]
lemme check

**Comment by DoodleSauce** [comment]
oh thanks im so dumb i just found the clone and download button thx bro

**Comment by Abc2557** [comment]
Oh, okay!
