### ISSUE TITLE
(Question) How to check for Unstable Edition Patch Notes?

### ISSUE THREAD

**Issue by Cloverhood** [Monika-After-Story/MonikaModDev#5651]
I got my copy of MAS (unstable) updated but I dont know what to check out. Is there a page made for this?

**Comment by DoodleSauce** [comment]
for contributing or coding its on the wiki

**Comment by multimokia** [comment]
If you join the community discord, ask staff for the `Unstable` role.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
