### ISSUE TITLE
next time i souldnt touch things that i dont know

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5652]
ok so i was searching for the spritecode thingy and clicked test prog point. After monika tells me that shes gonna test it then the renpy crash log screen appears i quit and reopen the game but monika tells me that she crashed and that shes going to repeat this prog test and now im in a infinite loop
 

(no jojo puns intended) XD

**Comment by DoodleSauce** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4542007/traceback.txt)

**Comment by Booplicate** [comment]
You don't need all the dev tools, remove them from the game directory. Also I hope you're not doing it in your main install...

**Comment by DoodleSauce** [comment]
oh shiet

**Comment by DoodleSauce** [comment]
i have backups will that work

**Comment by DoodleSauce** [comment]
WOOOOOOOOOOOO thx mate it worked

**Comment by DoodleSauce** [comment]
also i want a test subject monika how do i make one ?

**Comment by Booplicate** [comment]
[This](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) can help, I suggest to read it.

**Comment by DoodleSauce** [comment]
ok thanks again i was having one of the hardest anxiety tbh :p
