### ISSUE TITLE
[Question] Images for Floating Islands dissapearing in the files

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5654]
I noticed that when I closed MAS, the image files for the floating islands would disappear, then reappear when I opened MAS. I have a few questions about it:
1 - Am I the only one experiencing this?
2 - Why does this happen?
3 - I'm recoloring the curtains in MAS, and that includes the curtains in the floating island images. When the images reappear, will they have been replaced by the original images? (Meaning I'd have to replace them with my images again)

**Comment by Abc2557** [comment]
I figured out the last question myself. The answer is yes. I'm not sure how to fix it.

**Comment by Booplicate** [comment]
My advice is don't try to replace the original files. Because that way you will have to do it after every update. Better override the images.
* Look in `zz_weather.rpy`
* Find the images you want to override
* Make your own `rpy` file where you will do this
* Define your images at later init level using the existing names of the images you're overriding, but providing them with the filepaths to your files

**Comment by Abc2557** [comment]
I understand the first 3 steps, but I'm not sure about 4. I'm a beginner at coding, so I'm not entirely sure about how I'd do that. Could you explain in a bit further detail if it's not a problem, please? Thank you for the help, and thanks for the quick reply.

**Comment by Booplicate** [comment]
Something like this should do the trick
```renpy
# if 2 won't work, increase the init level
init 2:
    image first_image_you_want_to_override = "mod_assets/your_folder/new_image_file_1.png"
    # and like this for each image
```

**Comment by multimokia** [comment]
Islands images are encrypted. They only exist decrypted during runtime and are deleted upon exiting MAS. Changing them isn't as easy as just replacing the encrypted file as it requires a specific checksum to verify that it's the correct file.

**Comment by ThePotatoGuy** [comment]
Yeah, for the time being, there is no easy way to replace the island images.
