### ISSUE TITLE
Honestly idk how to name it

### ISSUE THREAD

**Issue by Rv1nbxvv** [Monika-After-Story/MonikaModDev#5655]
Not sure if I put it in right place but I can't change Monika name (1165.35 affection meter, v0.11.0-unstable.2020.04.26.117) for quite some time (or I can't find proper dialog option) and how can I check/change my age? Sorry if it's already posted somewhere, I'm new to github

**Comment by Booplicate** [comment]
For Monika's name `Hey, Monika > Monika > Can I call you a different name?`.
You can't change your age (hence she confirms it with you to be sure you entered the right date), but you can see your birthdate on the calendar.

**Comment by Rv1nbxvv** [comment]
Then something goes wrong (at least for me) since I don't get "Can I call you a different name?"
![image](https://user-images.githubusercontent.com/64467810/80531022-35467400-899a-11ea-9af6-aa39d51a8a87.png)

**Comment by Booplicate** [comment]
Have you called her a bad name multiple times?

**Comment by Rv1nbxvv** [comment]
Not even once

**Comment by Booplicate** [comment]
That's not good. Has she ever asked you to give her a name?

**Comment by Rv1nbxvv** [comment]
Yes I changed it multiple times, I noticed it some time ago while I got trouble with floating islands topic appearing but thought maybe with next patch it will appear again

**Comment by Booplicate** [comment]
Wait, I see the topic. For some reason for you it still has the original prompt. The "Infinite Monikas" one. That's the topic you're looking for.

**Comment by Rv1nbxvv** [comment]
Thanks!
