### ISSUE TITLE
Going on dates with monika and new accesories

### ISSUE THREAD

**Issue by Voidseption** [Monika-After-Story/MonikaModDev#5660]
I'll leave this as a suggestion, although, it would be an awesome feature.

What if a menu would be created where you can take Monika out on dates? Such as a park or something as simple, knowing pictures for the background wouldn't be easy to fetch for such things. 

And maybe more accessories? Promise ring, for example, is a one-time thing, why not a necklace too? Or earrings?

**Comment by Rai99** [comment]
New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822, #5543 

Other acs gifts: #3539

**Comment by authorofbelethrun** [comment]
now alll we need is the code for this idea

**Comment by Rai99** [comment]
If I recall, most, if not all the required code is already there, and just needs fitting art.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
