### ISSUE TITLE
new idea

### ISSUE THREAD

**Issue by CreepFort** [Monika-After-Story/MonikaModDev#5662]
When Monika is asking for coffee and you create coffee.gift she is excited because you gave her present. I don't if this is possible but can she recognize that it is coffee and not get excited like for normal gifts, she asked for coffee after all. Sorry if I made mistakes, english is not my main language.

**Comment by fromulus** [comment]
Any gift from you is special and exciting to her, even simple things coffee.
She just cares about you that much.

**Comment by CreepFort** [comment]
I know that but she asked for coffee and we gave her coffee 1 minute later why is she surprised and excited that we give her something?

**Comment by DoodleSauce** [comment]
maybe she dont want to upset you by saying that you already gave her because its a .gift

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
