### ISSUE TITLE
Tea Changing colors (also adding tea bag boxes)

### ISSUE THREAD

**Issue by QuadILOP1** [Monika-After-Story/MonikaModDev#5664]
Why not just start a new suggestion for tea when implemeted

**Comment by QuadILOP1** [comment]
so if we could get the tea .gift file to be teabagbox.gift that would be AMAZING

**Comment by emerdite** [comment]
Yeah, and It'd be cool if the tea was also to brew on-screen, and after some time monika would be like "Okay, I'm gonna take the teabag out now, give me a second." And left to throw it out. Also, for the on-screen brewing part, it could be that there would be a couple tea colours, and that it would pick one of those colours, and change the water into the colour of one of the teas. Hope whatever I said here makes sense ^^;

**Comment by Iniquitatis** [comment]
> And left to throw it out...

... of the window.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
