### ISSUE TITLE
windows reaction unintended trigger?

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#5669]
Hello! 
I´ve just wanted to report something about windows reactions.
When on youtube watching a video where the title mentions "twitter" it will trigger the reaction for the Twitter page (I haven't tried other keywords but already happened with twitter multiple times).
Just a minor quirk that I thought I should share in case no one was aware.
Take care!

**Comment by Booplicate** [comment]
That's the way WRs work. For example it can give you false positives for `youtube` too if you open any window containing `youtube` in its title.
