### ISSUE TITLE
Question:Monika does not respond to gifts

### ISSUE THREAD

**Issue by QLQland** [Monika-After-Story/MonikaModDev#5673]
![ab71e9071d950a7b60e640ad1dd162d9f3d3c907](https://user-images.githubusercontent.com/63233940/80777041-802cdb00-8b96-11ea-8b38-f3edf2724c60.png)
Here is the screenshot.
These gifts has been in the file for several days and Monika does not react to them.So I wonder if it is a 
bug?

**Comment by multimokia** [comment]
Are you using a translated version of MAS?

**Comment by QLQland** [comment]
> Are you using a translated version of MAS?

I'm sorry to have kept you waiting.
I am using a original version of MAS

**Comment by freshnewname** [comment]
sorry for interjecting here, but the monika.chr file should've been deleted at the start of mas right? so maybe you got the wrong folder?

**Comment by multimokia** [comment]
Where is your MAS install located? (Can you give a filepath please)

**Comment by QLQland** [comment]
> Where is your MAS install located? (Can you give a filepath please)
It's on the desktop

**Comment by multimokia** [comment]
Can you send your persistence here please? You'll have to put it into a zip to send it.

**Comment by QLQland** [comment]
> Can you send your persistence here please? You'll have to put it into a zip to send it.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4564317/persistent.zip)
Here it is.

**Comment by multimokia** [comment]
I see you've done a bit of time travelling. As a result, the reacted map never clears until a day after the date you time traveled (and gave a gift on) so basically it's impossible to gift those again until then.

I suggest restoring a backup from before time travelling.

**Comment by QLQland** [comment]
> I see you've done a bit of time travelling. As a result, the reacted map never clears until a day after the date you time traveled (and gave a gift on) so basically it's impossible to gift those again until then.
> 
> I suggest restoring a backup from before time travelling.
Okay,thanks a lot.
