### ISSUE TITLE
How to activate topics

### ISSUE THREAD

**Issue by Hartsaxena** [Monika-After-Story/MonikaModDev#5678]
Hello! This is my first issue/question so I don't know the routine for these sorts of things. I'm just gonna state the question.

I'm trying to code my own topics into the game, and I want to test them out, but I don't know how to activate them manually. Do I have to talk to Monika and wait for her to get to my topic, or is there an easier way? Thanks! c:

**Comment by ThePotatoGuy** [comment]
Best way to activate manually is to make it an unlocked pool topic with no `aff_range` restriction. it will then show up in the "Hey Monika" menu.

If you have already launched the game once with your topic in the code, you will be unable to change the unlocked/pool properties, in which case ur plan of action depends on the properties you have set for the topic.
