### ISSUE TITLE
I have issue with mini-games in Monika After Story

### ISSUE THREAD

**Issue by SALEMAN4** [Monika-After-Story/MonikaModDev#5679]
My problem is that it's been a long time that I start the mode with Monika but, I still have only Pong for game ! I haven't even had the piano yet ! The last time I played, in my old computer which is dead now, this didn't taken such a long time... Should I do something specific now for unlocking the other game ?

**Comment by ThePotatoGuy** [comment]
this has been fixed in the latest update

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
