### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by LegoshiM** [Monika-After-Story/MonikaModDev#5682]
I need help, I already tried everything but I can't play the MAS mod, always giving this error:

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
File "game/script-topics.rpy", line 8460, in script
File "game/script-topics.rpy", line 8474, in
File "game/event-handler.rpy", line 1315, in addEvent
NameError: name 'mas_seenLabels' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
File "game/script-topics.rpy", line 8460, in script
File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
exec bytecode in globals, locals
File "game/script-topics.rpy", line 8474, in
File "game/event-handler.rpy", line 1315, in addEvent
File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1749, in py_eval
return py_eval_bytecode(code, globals, locals)
File "C:\Users\Pedro Moura\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
return eval(bytecode, globals, locals)
File "", line 1, in
NameError: name 'mas_seenLabels' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.7
[/code]

i'm from brazil and my english is not very good yet, the latest version translated into portuguese is 0.10.7

**Comment by ThePotatoGuy** [comment]
You either have some files from the latest version installed or have rpy files in your `game/` folder.

**Comment by LegoshiM** [comment]
![image](https://user-images.githubusercontent.com/64665792/80851507-98cddd00-8bf8-11ea-8f87-5e599fdf911f.png)
![image](https://user-images.githubusercontent.com/64665792/80851518-ab481680-8bf8-11ea-8e33-f213ffc92243.png)
![image](https://user-images.githubusercontent.com/64665792/80851533-c31f9a80-8bf8-11ea-83d1-bdeed5527a53.png)
![image](https://user-images.githubusercontent.com/64665792/80851543-cca90280-8bf8-11ea-8aaf-64e21fef507c.png)
![image](https://user-images.githubusercontent.com/64665792/80851553-d92d5b00-8bf8-11ea-8895-403b0ae6ca81.png)
![image](https://user-images.githubusercontent.com/64665792/80851563-e21e2c80-8bf8-11ea-9506-e2d0f6ee3749.png)
![image](https://user-images.githubusercontent.com/64665792/80851574-e8aca400-8bf8-11ea-867f-936c575483fe.png)

**Comment by LegoshiM** [comment]
> Você tem alguns arquivos da versão mais recente instalada ou arquivos rpy na sua `game/`pasta.

how do i solve it?

**Comment by LegoshiM** [comment]
;_;

**Comment by ThePotatoGuy** [comment]
your issue has already been responded to [here](https://github.com/Monika-After-Story/MonikaModDev/issues/5649#issuecomment-622583919)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
