### ISSUE TITLE
Few issues about Monika After Story mini-games

### ISSUE THREAD

**Issue by lordkelwin** [Monika-After-Story/MonikaModDev#5684]
Hi!

I have some concerns about the piano mini-game because it's not part of the list of unlocked mini-games. I've already unlock the other three mini-games. Also, I noticed that the pmn.txt log does not finish loading all piano music. What should I do or what actions I need to take in order to solve this problem.

I'll attach the said log file. Hope that the concern will be addressed soon. Thanks.
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4566954/pnm.txt)

**Comment by ThePotatoGuy** [comment]
the log may not be complete while the game is open. Close the game before checking the log.

**Comment by lordkelwin** [comment]
Okay, I'll reupload the file.

But the end line says this:
[!ERROR!]: Failed to load file at 'c:\program files (x86)\steam\steamapps\common\doki doki literature club\game\mod_assets\games\piano\songs\d__p_c__o.json'. |
[pnm.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4566962/pnm.txt)

**Comment by ThePotatoGuy** [comment]
That line is expected.

**Comment by lordkelwin** [comment]
I see, which mean that the file will created sooner or later, according to my understanding, right?

**Comment by ThePotatoGuy** [comment]
that is a secret
