### ISSUE TITLE
about promise ring

### ISSUE THREAD

**Issue by Death0Justice** [Monika-After-Story/MonikaModDev#5689]
I first misgive monika the ring before her aff value is over 400 today earlier(399.2, i
 think), and she refuses normally. But now when her aff value is 402.2, she wont response to my ring gift. The other gifts work perfectly. Does that mean I need to postpone my giving? Or should I take other measures to get this fixed?(uploaded in a hurry, so please ignore grammar error)

**Comment by multimokia** [comment]
Try again tomorrow. It'll work once the reacted map clears.

**Comment by Death0Justice** [comment]
ok, I will try it later before replying further.

**Comment by Death0Justice** [comment]
thanks for informing

**Comment by Death0Justice** [comment]
ok it finally works, thanks again for informing.
