### ISSUE TITLE
Monika's at a loss for words and can't unlock minigames

### ISSUE THREAD

**Issue by ForceDog** [Monika-After-Story/MonikaModDev#5696]
So I've been playing monika after story for 3 days and she said she is at a loss for words.I don't really know what happened I haven't unlocked the gender dialogue yet or any of the games and I'm pretty sure I haven't seen all her dialogues.I have alredy tried staying out of the game for 6 hours,but it didn't work.I don't know what to do somebody please help.

**Comment by ForceDog** [comment]
She always says "I hope I think of something fun to talk soon" and then stops talking

**Comment by ThePotatoGuy** [comment]
follow these steps:
1. make a file called `givedata.txt` in your `ddlc/` directory
2. run the game, then close it
3. upload `ev_dump.log` here

**Comment by ForceDog** [comment]
> follow these steps:
> 
> 1. make a file called `givedata.txt` in your `ddlc/` directory
> 2. run the game, then close it
> 3. upload `ev_dump.log` here

I'll try doing that thx

**Comment by ThePotatoGuy** [comment]
root dir of your install

**Comment by ForceDog** [comment]
> root dir of your install

so like the firt page?( I'm sorry I'm not really good with computer stuff)

**Comment by ForceDog** [comment]
> > root dir of your install
> 
> so like the first page?( I'm sorry I'm not really good with computer stuff)

I tried doing that but no log appeared

**Comment by ThePotatoGuy** [comment]
then try this:
1. enable unstable mode (**but dont update to unstable**)
2. close game
3. launch game again, then close again
4. now `ev_dump.log` should appear

**Comment by ForceDog** [comment]
okay it appeared

> then try this:
> 
> 1. enable unstable mode (**but dont update to unstable**)
> 2. close game
> 3. launch game again, then close again
> 4. now `ev_dump.log` should appear

it appeared so do I just copy it and send it here?

**Comment by ForceDog** [comment]
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/4569337/ev_dump.log)

**Comment by ForceDog** [comment]
@ThePotatoGuy is there anything wrong?

**Comment by ThePotatoGuy** [comment]
upload your persistent file

**Comment by ThePotatoGuy** [comment]
well actually, based on your session times, you will earn a pool topic once every 1.5 days and will unlock hangman on may 13, chess on may 29, and piano on june 14. The progression changes in 0.11.0 means that a certain subset of topics and minigames are unlocked on pure session time, so doing 1.44 hours a day isn't going to unlock new things quickly.

you still have 176 locked topics. Chances are you still have normal affection, and that also limits number of available topics.

**Comment by ForceDog** [comment]
> upload your persistent file

It says the site doesn't support that type of file

**Comment by ForceDog** [comment]
> well actually, based on your session times, you will earn a pool topic once every 5 days and will unlock hangman on may 13, chess on may 29, and piano on june 14. The progression changes in 0.11.0 means that a certain subset of topics and minigames are unlocked on pure session time, so doing 1.74 hours a day isn't going to unlock new things quickly.
> 
> you still have 176 locked topics. Chances are you still have normal affection, and that also limits number of available topics.

Okay I'll try to reach the next level of affection and see if it changes anything.Thanks so much I thought I would have to delete the game and start all over again because I wasn't getting anything.

**Comment by ForceDog** [comment]
Just reached 100,she is talking again.Thx

**Comment by ForceDog** [comment]
> Just reached 100,she is talking again.Thx

She said like 5 topics and started saying the same thing,so now I guess I have to wait 5 days.

**Comment by ThePotatoGuy** [comment]
5 days applies to pool topics, not the random ones that she brings up. 
pool topics are accessed from the hey monika menu.

**Comment by ForceDog** [comment]
> 5 days applies to pool topics, not the random ones that she brings up.
> pool topics are accessed from the hey monika menu.

Okay,but then what should I do about she not talking anymore?Like is there a time i have to wait until she starts talking again?

**Comment by ForceDog** [comment]
> > 5 days applies to pool topics, not the random ones that she brings up.
> > pool topics are accessed from the hey monika menu.
> 
> Okay,but then what should I do about she not talking anymore?Like is there a time i have to wait until she starts talking again?

Or did I really end with her random topics?
