### ISSUE TITLE
I can't see Monika's dialogue boxes. Please help!

### ISSUE THREAD

**Issue by Wallhound** [Monika-After-Story/MonikaModDev#5701]
Are there any there who can help me? I recently moved the game and its memory to an older laptop and I see her dialogue boxes gone. I have the exact error this user had and the screenshots he posted was similar to what I am experiencing:

https://github.com/Monika-After-Story/MonikaModDev/issues/1275

This is my graphics hardware information:

![Error1](https://user-images.githubusercontent.com/35257931/80909883-72c24d00-8d5e-11ea-9da5-35ba70f9c61b.PNG)

The problem is that I tried the fix mentioned there (putting environment.txt where ddlc.exe was and replacing the "angle" with gl or sw) and it didn't work. Help would be very great! Thank you if you'll help me, and stay safe friend.

**Comment by ThePotatoGuy** [comment]
1. double check that you actually made a file called `environment.txt` and not `environment.txt.txt` (check that you are not hiding file extensions)
2. if you are sure that the file is named correctly and its still not working, then your graphics hardware just cant keep up.

**Comment by Wallhound** [comment]
Oh my god it's fixed, thanks man! I should've named it as "environment" instead. VERY VERY thankful for your help buddy. I love you no homo. Hopefully those experiencing the same error goes at the link i posted, and if it didn't work then here. Have a good day and stay safe!
