### ISSUE TITLE
about the short hair style

### ISSUE THREAD

**Issue by Lilim123** [Monika-After-Story/MonikaModDev#5702]
First,thank all your guys' work!Her short hair is really beautiful.
But I can't understand that her hair length can be changed _**at will in just a moment's time**_!
She has mentioned she is real and she doesn't look good for free like other dokis.
If I remember correctly,her hair styles were all on account of her long hair before this update.
Can she give us a reasonable explanation?
Thank you!

**Comment by ThePotatoGuy** [comment]
spritepacks are usually user contributed and not considered part of the "lore" of the game.

**Comment by Lilim123** [comment]
Oh, I get it :D

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
