### ISSUE TITLE
[Piano Notes] (No JSON) Home (Undertale)

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5706]
I'm in a very piano-ey mood today 
Piano notes for someone to make into a JSON for the in-game piano:

Q 4 T Y
4 T Y
W 4 T I
4 T Y
2 4 T Y
4 T Y
4 T I
Q 4 T Y
4 T Y
W 4 T Y
4 T Y
E 4 T I
4 T Y
- P I
4 T 4
Q 4 T Y
4 T Y
W 4 T Y
4 T Y
2 4 T Y
- P I
2 4 Y 4
4 T 4

I think I got it right. The last 2 lines (the 2 4 Y 4 and  4 T 4) were really confusing cause of the background notes heheh. Good luck to whoever decides to make the JSON for this!

(EDIT: Oh no the dashes turned into bullet points aaaa. Well, before the "P I"s there's a dash)

**Comment by ForceDog** [comment]
[pianosong.json.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4571423/pianosong.json.txt)
I'm not sure if it's supposed to be like this(because it's my first time making it) so idk if it's right

**Comment by ForceDog** [comment]
[pianosong.json.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4571428/pianosong.json.txt)
I'm not sure if it's supposed to be like this(because it's my first time making it) so idk if it's right or not

**Comment by ForceDog** [comment]
{
    name: Home,
    verse_list: [0, 5, 10, 19],
    pnm_list: [
        {
            text: (Playing home from undertale),
            style: monika_credits_text,
            notes: [
                Q4TY,
                4TY,
                W4TI,
                4TY,
                24TY,
                4TY,
                4TI,
                Q4TY,
                4TY,
                W4TY,
                4TY,
                E4TI,
                4TY
            ],
            express: 1eub,
            postexpress: 1eua,
            vis_timeout: 2.0,
            verse: 0,
            posttext: true
        },
        {
            text: (Playing home from undertale),
            style: monika_credits_text,
            notes: [
                4T4,
                Q4TY,
                4TY,
                W4TY,
                4TY,
                24TY
            ],
            postnotes: [
                24Y4,
                4T4
            ],
            express: 1eub,
            postexpress: 1eua,
            ev_timeout: 1.0
        }
    ]
}
