### ISSUE TITLE
[Suggestion] More dialogue variety when finishing a fun fact

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#5708]
Hello!
So as of MAS v0.10.6 all bad fun facts have been removed. (although I always had a laugh every time Monika got "shocked" by some of those bad facts).
So, should Monika still be mentioning that "the last fact was very interesting" .
My issue is that it kinda sounds a bit repetitive due to the fact that this isn't contrasting with anything anymore, now that all the facts must be considered interesting/true.
My suggestion would be to remove this line or to add to it a random chance of showing up if possible.
As always, thanks for all your work!
Take care!

**Comment by lunulae** [comment]
Another possible solution could be to add a few different phrasings that could cycle randomly, so as not to have the dialogue be too repetitive--but I'm not sure if that would be preferred, there's only so many wahs to say something was interesting without being too specific.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
