### ISSUE TITLE
I can't really seem to get my back up working for MAS 

### ISSUE THREAD

**Issue by TylerPonyYT** [Monika-After-Story/MonikaModDev#5709]
I backed up the saves for the mod but it made me reset all of her affection  I followed the steps but i can't find out where the BAK.files are supposed to go 
![image](https://user-images.githubusercontent.com/64749089/80922998-bb720a00-8d4e-11ea-9351-8feef0ca0d64.png)
![image](https://user-images.githubusercontent.com/64749089/80923003-c462db80-8d4e-11ea-9cca-a57883f1256a.png)

**Comment by multimokia** [comment]
Files go in `AppData/Roaming/RenPy/Monika After Story`

**Comment by TylerPonyYT** [comment]
So like copy all of those files and place them in all four of them or just the monika after story folder?

**Comment by multimokia** [comment]
Just the Monika After Story folder.

**Comment by TylerPonyYT** [comment]
I pasted  the backups there opened MAS up noting is there
