### ISSUE TITLE
(Piano notes)Home undertale song

### ISSUE THREAD

**Issue by ForceDog** [Monika-After-Story/MonikaModDev#5711]
So I tried to make a piano song json with the notes that @Abc2557 posted in the issues and since it's my first time doing it I don't know if it's right or wrong
[pianosong.json.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4571482/pianosong.json.txt)

**Comment by ForceDog** [comment]
{
    name: Home,
    verse_list: [0, 5, 10, 19],
    pnm_list: [
        {
            text: (Playing home from undertale),
            style: monika_credits_text,
            notes: [
                Q4TY,
                4TY,
                W4TI,
                4TY,
                24TY,
                4TY,
                4TI,
                Q4TY,
                4TY,
                W4TY,
                4TY,
                E4TI,
                4TY
            ],
            express: 1eub,
            postexpress: 1eua,
            vis_timeout: 2.0,
            verse: 0,
            posttext: true
        },
        {
            text: (Playing home from undertale),
            style: monika_credits_text,
            notes: [
                4T4,
                Q4TY,
                4TY,
                W4TY,
                4TY,
                24TY
            ],
            postnotes: [
                24Y4,
                4T4
            ],
            express: 1eub,
            postexpress: 1eua,
            ev_timeout: 1.0
        }
    ]
}

**Comment by multimokia** [comment]
All json keys should be in string format (inside `"`s).

Note names should also be in string format. Though those don't look like actual note names like what's defined.

**Comment by ForceDog** [comment]
> All json keys should be in string format (inside `"`s).
> 
> Note names should also be in string format. Though those don't look like actual note names like what's defined.

Now that i went to the page hwre it says how to do it and looked at the notes I saw that I did it all wrong.Gonna try to do it right again
