### ISSUE TITLE
[help needed]Trying to find a method to solve the problem of hitting “cancel” in the updater

### ISSUE THREAD

**Issue by Death0Justice** [Monika-After-Story/MonikaModDev#5713]
I always accidentally hit cancel when updating because of my terrible network. Then it won't open. I heard in another issue that this is because the update is half new, so it doesn't work.
I found a easier way rather than re-install another MAS to initialize the update. 
First, go to the task manager to close a program called "zsync.exe". Second, find the "update" folder at the folder where you installed the MAS. Delete all the files except one called "current.json", then you can reboot the game, and it works.

However, there're something I don't understand. 
The first one is whether this method works in a correct way, or it's just a scratch to make everything seems right.
The second one is that when the update bar doesn't move, and I can't detect any data flow between my computer and internet, how should I fix it without hitting cancel?

**Comment by ThePotatoGuy** [comment]
Normally I'd say just wait it out, but if you know for sure that your connection is always bad, you should just manually download each update and install them manually by overwriting files.

**Comment by Death0Justice** [comment]
well ok, so another problem...is there any source where I can download the unstable update? The problem above is not that obvious when I try to find some stable version like 0.11.1, since I can acquire them from my friends who have a good network. But the unstable version can only be updated in the game where the network sometimes doesn't work well. If there's no such source, just inform me. I think then the whole thing is pretty much understandable.

**Comment by ThePotatoGuy** [comment]
There is no consistent source for unstable updates. We only offer them via the ingame updater.

**Comment by Death0Justice** [comment]
ok. Thanks for your patience through this issue. By the way, is this method effective? How and where should I put this kind of suggestion? should I close this issue now?

**Comment by ThePotatoGuy** [comment]
yes, it is fine to ask questions on this platform. If your questions have been resolved, then you are free to close the issue. otherwise I will close it after a week.
