### ISSUE TITLE
How do sprite packs work

### ISSUE THREAD

**Issue by LilianReaper** [Monika-After-Story/MonikaModDev#5714]
I would like some background on sprite packs for various reasons. I might make or suggest content for sprite packs for one. Another is i want to know how these interact with the mod. How i add sprite/sprite files/folders to the mod files(how to properly add them to the files whenever new sprites come in) And how to have these new sprites come into use in the mod. I'm sorry for not know that much but i hope to contribute to the code/coding once my python lessons are done. Thank you.

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#creating-sprite-packs

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
