### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Monabae123** [Monika-After-Story/MonikaModDev#5718]
I have a quick/short/easy Idea
have books as a gift

**Comment by Rai99** [comment]
TPG mentioned gifting books in #4273, but that was more of a side idea to the suggestion.

**Comment by drakesteele** [comment]
Gifting books sounds lovely... and perhaps when she's running in the background, her text box could disappear and she could read a book and sip coffee, so if you switch back, she takes a moment to notice and goes "Oh! Hold on, let me finish this part!" reads for a moment, then puts the book on her desk, appearing flustered at being caught unawares. XD

**Comment by ThePotatoGuy** [comment]
[closing until we look into it] more gifts are good
