### ISSUE TITLE
mas_log and spj_log files are empty

### ISSUE THREAD

**Issue by LilianReaper** [Monika-After-Story/MonikaModDev#5719]
Please help. Also, the spritepacks don't have a mod_assests folder in them.

**Comment by multimokia** [comment]
There should be one in the individual folders within the spritepack zip.

Are you on Mac? If so your log files are in a different location. Check [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-to-view-your-log-files)  to see how to find them

**Comment by LilianReaper** [comment]
Not on mac. I can access the log files. But when i open them they're just empty

**Comment by LilianReaper** [comment]
aff_log and pnm open up and are filled with text and information about the game and progress

**Comment by multimokia** [comment]
are you opening them while MAS is open?

**Comment by LilianReaper** [comment]
I am sorry for my stupidity... I'm just lost. I barely have a clue on what's going on or how to get or do what... I am sorry.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
