### ISSUE TITLE
Clarification about Monika giving Python tips

### ISSUE THREAD

**Issue by lordkelwin** [Monika-After-Story/MonikaModDev#5720]
Hi! Good day devs!

I would like to know if the "Python Tips" feature in MAS was removed in latest version. Because in previous versions, that feature was existent but in recent versions (which I used 0.10.7 at first), the said features was already not there.

I want to clarify in that case. Thank you.

**Comment by multimokia** [comment]
They're all still in. We don't have any intent to remove them

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
