### ISSUE TITLE
I made some of Monika's outfits in Animal Crossing New Leaf

### ISSUE THREAD

**Issue by octogonSmuggler** [Monika-After-Story/MonikaModDev#5725]
I made the off shoulder sweater, her blazerless uniform, the white sundress, and the mermaid bikini. Also, I made Natsuki's casual outfit because it's kinda cute. I thought I'd post them here as both QR and Grided formats incase anyone wants them or wants to edit them. :3 

![Spica](https://user-images.githubusercontent.com/63683308/81096379-e46bd980-8ecb-11ea-9a8d-68ff256d4568.png)
![Sundresssss](https://user-images.githubusercontent.com/63683308/81096380-e5047000-8ecb-11ea-8802-a61d4a536fb4.png)
![sweater vest](https://user-images.githubusercontent.com/63683308/81096381-e5047000-8ecb-11ea-9ce6-ee0c30a4f10e.png)
![Mermaid](https://user-images.githubusercontent.com/63683308/81096778-8986b200-8ecc-11ea-933c-355eba883543.png)
![Sundresss](https://user-images.githubusercontent.com/63683308/81096824-9a372800-8ecc-11ea-927d-3a6019713bcd.PNG)
![Moni No Blazer](https://user-images.githubusercontent.com/63683308/81096826-9a372800-8ecc-11ea-8018-69a261cac6ab.PNG)
![Off Shoulder](https://user-images.githubusercontent.com/63683308/81096827-9acfbe80-8ecc-11ea-85e6-28719163cd72.PNG)
![Natsuki](https://user-images.githubusercontent.com/63683308/81096829-9acfbe80-8ecc-11ea-9418-0932c09ccdf1.PNG)
![Mermaid](https://user-images.githubusercontent.com/63683308/81096830-9acfbe80-8ecc-11ea-9c1a-a1066f2359a1.PNG)

**Comment by multimokia** [comment]
Our GitHub isn't really the place for this. Over here we just stick to mod-suggestions, bug reports, and other similar discussion. You're more than welcome to share these in the community server though!

**Comment by octogonSmuggler** [comment]
> Our GitHub isn't really the place for this. Over here we just stick to mod-suggestions, bug reports, and other similar discussion. You're more than welcome to share these in the community server though!

Oh! I'm sorry! I'll post them there instead, then.
