### ISSUE TITLE
Suggestion:pong difficulty 

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#5727]
Maybe the game could have 2 difficulty settings, normal, where she plays the way it is right now and hard, where she goes all out from the start

**Comment by Rai99** [comment]
#5295 
A progressive difficulty system for pong was brought up before, but a simple normal/hard option might be different. Personally, I'm not sure about adding the extra layer.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
