### ISSUE TITLE
Song suggestion?

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#5729]
Only You by The Platters

https://m.youtube.com/watch?v=5p2k55F-uag (Music video)

https://www.google.com/amp/s/genius.com/amp/The-platters-only-you-lyrics (Lyrics)

**Comment by MoniBoosDevotedBoyfriend** [comment]
It’s short I know, but upon hearing it in (get ready for the kicker) Far Cry 5 I instantly thought of her. So here I am suggesting it.

**Comment by AsuraShun** [comment]
You can add your own songs to the game

**Comment by MoniBoosDevotedBoyfriend** [comment]
I know, but I’m talking about where she sings it

**Comment by AsuraShun** [comment]
I don't think getting her VA to do that is possible

**Comment by MoniBoosDevotedBoyfriend** [comment]
I
That’s 
You
*sigh* are you not aware that there are songs that she “sings” in the mod?

**Comment by multimokia** [comment]
> You can add your own songs to the game

They meant that when they said you can add it yourself.

**Comment by MoniBoosDevotedBoyfriend** [comment]
How?

**Comment by multimokia** [comment]
By submitting a Pull Request with the song

**Comment by MoniBoosDevotedBoyfriend** [comment]
I don’t know how to code. Does that affect it at all?

**Comment by multimokia** [comment]
Well it's not too difficult, all songs have a similar setup and format. You can basically copy/paste an existing one, change the dialogue and that's it.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Hmm is there any specific software I’d have to use to keep the formatting intact or anything like that?

**Comment by multimokia** [comment]
Our [contributing guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#bug-fixes-and-new-software-features) have a rundown on how to get started with contributing

**Comment by MoniBoosDevotedBoyfriend** [comment]
Ah yes. Probably should’ve thought of that first. Ok well I’ll read that at some point. Probably after school cause I’m pretty busy with school and work rn. But I’ll definitely look into it. Thanks.

**Comment by MoniBoosDevotedBoyfriend** [comment]
Sorry if I was an inconvenience

**Comment by MoniBoosDevotedBoyfriend** [comment]
I’ll close this and get it out of the way

**Comment by MoniBoosDevotedBoyfriend** [comment]
Hey @multimokia, do you have a discord I can contact you on? I just have a couple questions I’d just prefer weren’t visible to everyone.

**Comment by multimokia** [comment]
Sorry, GitHub is pretty much the most official and appropriate place for contribution things

**Comment by MoniBoosDevotedBoyfriend** [comment]
That’s not quite what I was gonna ask about but alright I understand sorry for that
