### ISSUE TITLE
never have i ever

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5732]
who on earth doesn't know what this game is but this time id like two difficulties
Easy,    Hardcore
Hardcore is basically  B   I    G    topics not lewd
and easy is something really small like have you ever pissed on bed at a ireasonable age etc..

**Comment by Rai99** [comment]
Never have I ever heard of a game called never have I ever. 

Going off of a quick search though, I'm not sure how this would fit into MAS. I don't think we'd be able to just fabricate any unconfirmed past event for Monika, and the best we could do for the player's turn would be to just have menu options, which probably wouldn't work at all for a game this open ended.

**Comment by DoodleSauce** [comment]
sorry

**Comment by ThePotatoGuy** [comment]
too open-ended to be feasible. It would have to be very restricted as rai said, and too many unknowns regarding Monika's past.

[closing as rejected]
