### ISSUE TITLE
I can’t give Monika new haircuts

### ISSUE THREAD

**Issue by Sipher95** [Monika-After-Story/MonikaModDev#5735]
After the most recent updates, for some reason I just can’t give Monika new hair styles. I’m using the new spritepacks, but when I copy the files over and start the game up, they just aren’t there anymore.

**Comment by multimokia** [comment]
Say goodbye and send your `spj.txt`, it's in the `\log` folder

**Comment by Sipher95** [comment]
send the spj.txt where?

**Comment by multimokia** [comment]
Drag it into the message box and it'll upload when you click the comment button

**Comment by Sipher95** [comment]
Thanks!

**Comment by multimokia** [comment]
Not quite what I meant there, you accidentally hit the close button?

**Comment by Sipher95** [comment]
Oh, it’s just that I moved spj.txt to the character folder and now it’s working. I didn’t realize you were talking about sending it as a comment here

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
