### ISSUE TITLE
Problem for the install of sprite pack

### ISSUE THREAD

**Issue by SALEMAN4** [Monika-After-Story/MonikaModDev#5736]
I wanted to add the sprite pack in to the game. But in the files of the game, there no files with "J", what should I do ?

**Comment by Booplicate** [comment]
That doesn't matter for you. All you need to do is merge 2 `mod_assets` folders and put the gift in `/characters`. [Full instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
