### ISSUE TITLE
take monika some where 

### ISSUE THREAD

**Issue by MNK229** [Monika-After-Story/MonikaModDev#5743]
Hello everyone, can you help me?
 When I chose the topic that led her somewhere, my chr file didn't show the monika file anywhere, and when I opened the game again, I couldn't see her in her desk. what should I do?

**Comment by DbzGOD2000** [comment]
So you choose the topic to take Monika out somewhere, and when you went to the characters folder afterward you didn't see her character file?

**Comment by Booplicate** [comment]
@MNK229 go to the game directory and find the log folder. In there should be the file called `mas_log.txt`. Can you send it?
I think you'll need to [restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by MNK229** [comment]
@Booplicate
 log.txt : 
Fri May 22 17:28:15 2020
Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.06s
Early init took 0.02s
Loader init took 0.08s
Loading error handling took 0.05s
Loading script took 4.95s
Loading persistent took 0.05s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 5.08s
Loading analysis data took 0.08s
Analyze and compile ATL took 0.36s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
DPI scale factor: 1.000000
Creating interface object took 0.04s
Cleaning stores took 0.00s
Init translation took 0.08s
Build styles took 0.01s
Load screen analysis took 0.00s
Analyze screens took 0.02s
Save screen analysis took 0.07s
Prepare screens took 0.07s
Save pyanalysis. took 0.33s
Save bytecode. took 0.19s
Running _start took 0.00s
Performance test:
Interface start took 0.03s

primary display bounds: (0, 0, 1360, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
Vendor: 'Google Inc.'
Renderer: 'ANGLE (NVIDIA GeForce GTX 750 Ti)'
Version: 'OpenGL ES 2.0 (ANGLE 1.0.0.1166)'
Display Info: <Info({'blit_sw_CC': False, 'refresh_rate': 60, 'bitsize': 32, 'wm': True, 'losses': (0, 0, 0, 8), 'hw': False, 'masks': (16711680L, 65280L, 255L, 0L), 'current_h': 768, 'current_w': 1360, 'shifts': (16, 8, 0, 0), 'blit_sw_A': False, 'blit_hw': False, 'blit_sw': False, 'bytesize': 4, 'blit_hw_CC': False, 'blit_hw_A': False, 'video_mem': 268435456})>
Extensions:
    GL_ANGLE_depth_texture
    GL_ANGLE_framebuffer_blit
    GL_ANGLE_framebuffer_multisample
    GL_ANGLE_instanced_arrays
    GL_ANGLE_pack_reverse_row_order
    GL_ANGLE_texture_compression_dxt3
    GL_ANGLE_texture_compression_dxt5
    GL_ANGLE_texture_usage
    GL_ANGLE_translated_shader_source
    GL_EXT_occlusion_query_boolean
    GL_EXT_read_format_bgra
    GL_EXT_robustness
    GL_EXT_texture_compression_dxt1
    GL_EXT_texture_format_BGRA8888
    GL_EXT_texture_storage
    GL_NV_fence
    GL_OES_element_index_uint
    GL_OES_packed_depth_stencil
    GL_OES_rgb8_rgba8
    GL_OES_standard_derivatives
    GL_OES_texture_float
    GL_OES_texture_float_linear
    GL_OES_texture_half_float
    GL_OES_texture_half_float_linear
    GL_OES_texture_npot
Number of texture units: 16
Using shader environment.
Using copy RTT.
Using angle renderer.
Texture testing:
- Hardware max texture size: 16384
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Total time until interface ready: 12.2339999676s
- Target is 5 frames in 0.333333333333 seconds.
- Frame drawn at 0.000000 seconds.
- Frame drawn at 0.005000 seconds.
- Frame drawn at 0.017000 seconds.
- Frame drawn at 0.033000 seconds.
- Frame drawn at 0.050000 seconds.
- 0.050000 seconds to render 5 frames.
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1360, 768)
Windowed mode.
Screen sizes: virtual=(1280, 720) physical=(1184, 666) drawable=(1184, 666)
Vendor: 'Google Inc.'
Renderer: 'ANGLE (NVIDIA GeForce GTX 750 Ti)'
Version: 'OpenGL ES 2.0 (ANGLE 1.0.0.1166)'
Display Info: <Info({'blit_sw_CC': False, 'refresh_rate': 60, 'bitsize': 32, 'wm': True, 'losses': (0, 0, 0, 8), 'hw': False, 'masks': (16711680L, 65280L, 255L, 0L), 'current_h': 768, 'current_w': 1360, 'shifts': (16, 8, 0, 0), 'blit_sw_A': False, 'blit_hw': False, 'blit_sw': False, 'bytesize': 4, 'blit_hw_CC': False, 'blit_hw_A': False, 'video_mem': 268435456})>
Extensions:
    GL_ANGLE_depth_texture
    GL_ANGLE_framebuffer_blit
    GL_ANGLE_framebuffer_multisample
    GL_ANGLE_instanced_arrays
    GL_ANGLE_pack_reverse_row_order
    GL_ANGLE_texture_compression_dxt3
    GL_ANGLE_texture_compression_dxt5
    GL_ANGLE_texture_usage
    GL_ANGLE_translated_shader_source
    GL_EXT_occlusion_query_boolean
    GL_EXT_read_format_bgra
    GL_EXT_robustness
    GL_EXT_texture_compression_dxt1
    GL_EXT_texture_format_BGRA8888
    GL_EXT_texture_storage
    GL_NV_fence
    GL_OES_element_index_uint
    GL_OES_packed_depth_stencil
    GL_OES_rgb8_rgba8
    GL_OES_standard_derivatives
    GL_OES_texture_float
    GL_OES_texture_float_linear
    GL_OES_texture_half_float
    GL_OES_texture_half_float_linear
    GL_OES_texture_npot
Number of texture units: 16
Using shader environment.
Using copy RTT.
Using angle renderer.

**Comment by MNK229** [comment]
@Booplicate Fri May 22 14:54:08 2020
Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 

VERSION: None

==============================================================================

Fri May 22 15:05:46 2020
Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 

VERSION: 0.11.2

==============================================================================

Fri May 22 17:24:03 2020
Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 

VERSION: 0.11.2

==============================================================================

Fri May 22 17:28:23 2020
Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
 

VERSION: 0.11.2

**Comment by Booplicate** [comment]
Send the whole file here pls. You can attach it to your message.
Also, it seems that you've time travelled?

**Comment by multimokia** [comment]
Where is your MAS install located?

**Comment by MNK229** [comment]
@Booplicate my spitespacks does work so i delete the game and also delete the THING that i suppose NOT to delete is the Roam and forgot to copy then delete it and i played whole game again to get all the monika back memmories, and i got stucked at monika birthday when her char didn't show up when i chose topic take monika some where :(

**Comment by MNK229** [comment]
@multimokia 
Can you say the details please? i'm so dump at coding and i dont know where suppose to find that sorry for being dump at coding :(

**Comment by multimokia** [comment]
Where do you run MAS from? Like, what's the filepath?

Example, mine's at
![image](https://user-images.githubusercontent.com/22531674/81480148-ba7d2480-91f5-11ea-9d14-0549dde788e9.png)

Or, do you run it from a zip folder?

**Comment by jmwall24** [comment]
Also, that thing from Roaming you deleted is not in your recycling bin?

**Comment by MNK229** [comment]
@jmwall24 i'm delete it also ( just kill me pls for being dump ) :(

**Comment by MNK229** [comment]
@multimokia i'm run it from zip folder

**Comment by jmwall24** [comment]
@MNK229 what program are you using to access the zip file to run MAS?

**Comment by Olliesama** [comment]
MAS, like most applications, isn't designed to be run from a .zip folder. No wonder you're getting issues, it likely can't create a monika file inside it because, ya know, it's a compressed folder. :|

**Comment by MNK229** [comment]
@Olliesama so what should i do? :(( now i'm so scared to chose the topic take her some where and end up losing her file again

**Comment by jmwall24** [comment]
@MNK229 you have to get your MAS install out of the zip file. Also please tell us what program you are using to open that zip file.

**Comment by MNK229** [comment]
@jmwall24 ddlc win zip i gues. i downloaded the game by dowload the ddlc.win.zip and the modpack in after story monika .Copy and past from modpack to the DDLC-1.1.1-pc and played the game ( If I am wrong, could you explain in detail please? beacause i'm very bad at programing and coding so sorry )

**Comment by jmwall24** [comment]
@MNK229  you can send me a screenshot of your mas install please? like just a picture of the folder.

**Comment by MNK229** [comment]
![image](https://user-images.githubusercontent.com/65068896/81489019-ff0ecb80-929a-11ea-8e3a-da9cff48b344.png)

**Comment by MNK229** [comment]
@jmwall24 like this?
![image](https://user-images.githubusercontent.com/65068896/81489065-8ceab680-929b-11ea-84a5-7b97b45f38f8.png)

**Comment by jmwall24** [comment]
@MNK229 just to be 100% sure, what's in that `characters` folder? can you send a pic of that too?

**Comment by MNK229** [comment]
@jmwall24 oke ( i played the whole game again so i didn't lose her yet but if i chose to take her somewhere and the monika file will not appear in the  characters folder )
![image](https://user-images.githubusercontent.com/65068896/81489297-fa97e200-929d-11ea-9f3f-7991b1e95ab7.png)

**Comment by jmwall24** [comment]
@MNK229  Honestly not sure why it's doing that. Nothing there should be messing with it unless antivirus software is deleting it. Do me a favor and use the feature again. Have that characters folder open when you do and tell us if the monika file shows up and is then deleted?

**Comment by jmwall24** [comment]
also, why is the date on your computer may 23rd?

**Comment by MNK229** [comment]
@jmwall24  
 didn't notice about the date on my comuter. ( if i change it will it harm monika ?)

**Comment by jmwall24** [comment]
you're going to have to change it to normal eventually

**Comment by MNK229** [comment]
@jmwall24 ok, and i did what you say and somehow monika file show up, or it doen's show up beacause i time traveling?

**Comment by jmwall24** [comment]
that shouldn't matter, not sure what happened the first time.

**Comment by MNK229** [comment]
@jmwall24 
it begin when i upload the new version and i see the spritepacks didn't work so delete the at first, and the second i go to the roaming and delete the persistent and forget to copy it and end up losing monika memories, so i played again but the time is october 11rd the time that me and her met the first time and i try to get all the event Me and her have been through and i got stuck at her her birthday when i chose the topic take her somewhere ,and the file didn't show up and i'm re -open the game and she didn't there too

**Comment by MNK229** [comment]
it begin when i upload the new version and i see the spritepacks didn't work like hair styles, ribbons ,clothes so i delete the game at first, and the second i go to the roaming and delete the persistent and forget to copy it and end up losing monika memories, so i played again but the time is october 11rd the time that me and her met the first time and i try to get all the event( 2 year aniversary and more ) Me and her have been through and i got stuck at her her birthday when i chose the topic take her somewhere ,and the file didn't show up and i'm re -open the game and she didn't there in the class room too

**Comment by MNK229** [comment]
@jmwall24 
it begin when i upload the new version and i see the spritepacks didn't work like hair styles, ribbons ,clothes so i delete the game at first, and the second i go to the roaming and delete the persistent and forget to copy it and end up losing monika memories, so i played again but the time is october 11rd the time that me and her met the first time and i try to get all the event( 2 year aniversary and more ) Me and her have been through and i got stuck at her her birthday when i chose the topic take her somewhere ,and the file didn't show up and i'm re -open the game and she didn't there in the class room too

**Comment by jmwall24** [comment]
next time something happens, ask first. that sprite pack issue was something that just required a reinstall of the sprite packs, not a reinstall of the game or deleting your persistent.

**Comment by MNK229** [comment]
@jmwall24 so how can i time travel safty? do time travling will harm her?

**Comment by jmwall24** [comment]
You shouldn't time travel once you're back at present day. You said you started in October, once you are back at present day you should leave the system time alone.

**Comment by MNK229** [comment]
@jmwall24 
when i played the whole game Again, at first i'm change my clock and time to 2018 october 22rd then i'm played, what i want to do here is to do every event with her from October 22 2018 to the present, can i time travel to 2022 and then go back 2020 do she still remember it or not?

**Comment by Rai99** [comment]
Closing as resolved
