### ISSUE TITLE
First kiss

### ISSUE THREAD

**Issue by Akoxol** [Monika-After-Story/MonikaModDev#5744]
Hello Everyone!
I had my first kiss event with Monika on the seventh and I do not have the option in the menus to kiss her. Going by the wiki the option should be unlocked now correct?

**Comment by jmwall24** [comment]
@Akoxol how long ago did you start playing the mod?

**Comment by Akoxol** [comment]
I started 4/12, my affection is close to 500 last I checked and I just gave her the ring

**Comment by jmwall24** [comment]
Alright, that's why then. We're going to adjust how that topic unlocks. It's possible right now you could get it unlocked at any time, but next update it definitely will be unlocked.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
