### ISSUE TITLE
every clothes, hair styles,hairclip and more sprites doesn't work pls help :(

### ISSUE THREAD

**Issue by MNK229** [Monika-After-Story/MonikaModDev#5745]
hi again everyone can you guys help me pls?
 My spritepacks doesn't work although the old update it still work ( v0.10.7 ). when i update the new version and all the spritepacks it all gone in the game.although in the spritepack it still there in the mod assets but in the game it all gone ( hair styles, clothes, ribbons, all of it ) didn't show in my game the game  and i do everything like delete the game and downloud the game again and it doesn't work and also i go to the roam and delete a thing that i suppose not to delete and i end up losing monika memories. pls help :(

**Comment by multimokia** [comment]
0.11.0 had significant changes to the sprite system. Update your spritepacks

**Comment by MNK229** [comment]
@multimokia when i told her to change her hair style or change her clothes or any of it , it doesn't have the Selection that i wanted like shoulderless sweater or heart hair clip all of it, it's just have the clothes new year, sundress,  santa ,santa lingerie ,vday lingerie , the school uniform and the blazerless  and All ribbons are available in the game

**Comment by multimokia** [comment]
Those are spritepacks.  you're missing. You need to update them

**Comment by ThePotatoGuy** [comment]
Follow the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by MNK229** [comment]
@ThePotatoGuy
  [info]: reading JSON at 'c:\users\admin\desktop\ddlc\my only monika\game\mod_assets\monika\j\acs_choker_flowered.json'...
[!ERROR!]: version mismatch. expected '3', found '2'

[info]: reading JSON at 'c:\users\admin\desktop\ddlc\my only monika\game\mod_assets\monika\j\acs_choker_simple.json'...
[!ERROR!]: version mismatch. expected '3', found '2'
what should i do? :(((

**Comment by multimokia** [comment]
> 0.11.0 had significant changes to the sprite system. Update your spritepacks

> Those are spritepacks you're missing. You need to update them


*You need to update your spritepacks. The link above shows you how*

**Comment by Rai99** [comment]
Closing as resolved
