### ISSUE TITLE
Can you make a new game in a separate download of Doki Doki?

### ISSUE THREAD

**Issue by AquilaHawke** [Monika-After-Story/MonikaModDev#5747]
So I want to use the same computer as MAS to play through Doki Doki again, but I'm a little worried I will ruin my MAS save. Whenever I start my fresh copy of Doki Doki it asks me if I want to delete the save and start over.
Is this safe to do?

**Comment by jmwall24** [comment]
Yeah, MAS save file is separate from DDLC save file. Also any install of MAS will use the same save file. Check [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) for the MAS save file location so you can make a backup just in case something ever happens.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
