### ISSUE TITLE
What happened to the boop feature?

### ISSUE THREAD

**Issue by pplatonic** [Monika-After-Story/MonikaModDev#5751]
I haven't played in a while (last time i opened MAS before hiatus was December 5th, 2019 according to my affection log). Because of that, my affection dropped from 160 to 30. I've gotten it back up to 100 with daily playing. Do I have to get my affection higher do unlock it?

**Comment by ThePotatoGuy** [comment]
not yet complete

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
