### ISSUE TITLE
After update there is an exception

### ISSUE THREAD

**Issue by April-forever** [Monika-After-Story/MonikaModDev#5753]
When I updated the version to 0.11.2 today, an error happened with the following traceback:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_games.rpy", line 108, in script
  File "game/zz_games.rpy", line 116, in <module>
  File "game/event-handler.rpy", line 1317, in addEvent
EventException: EventError: Given db is not of type dict

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/zz_games.rpy", line 108, in script
  File "E:\steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_games.rpy", line 116, in <module>
  File "game/event-handler.rpy", line 1317, in addEvent
EventException: EventError: Given db is not of type dict

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.0

I want to know how to solve it.

**Comment by multimokia** [comment]
You have rpy files in your game directory so your updates are being overwritten by old content. As you can see, the version in your traceback is 0.11.0.

Delete all `.rpy` files and manually update it again.

**Comment by multimokia** [comment]
Additionally it's not recommended to use steam as it can cause issues, plus you can't use the in game updater

**Comment by April-forever** [comment]
> You have rpy files in your game directory so your updates are being overwritten by old content. As you can see, the version in your traceback is 0.11.0.
> 
> Delete all `.rpy` files and manually update it again.

Yes, I have solved the error, thanks for your help!
Actually, I rarely use steam to open it and it is just a habit, but I will change the path now.
Thank you again!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
