### ISSUE TITLE
A G A I N

### ISSUE THREAD

**Issue by DoodleSauce** [Monika-After-Story/MonikaModDev#5758]
i verified the existence of the 2tublb expression but monika still disapears
```renpy
init 5 python:
    addEvent(
        Event(
            persistent._mas_compliments_database,
            eventlabel="mas_compliment_voice",
            prompt="I love your voice!",
            unlocked=True
        ),
        code="CMP"
    )

label mas_compliment_voice:

     m 1eubla "Aw thank you so much [player]"
     m 2tublb "But you know, i don't have a real voice"
     m 2tublb "It was actually Jillian Ashcraft who voiced me"
     m 1eubla "Im quite glad she voiced me"
     m 2tublb "She had a cute voice did she?"
     m 1eubla "-Ehehe" 
    
return 
```

**Comment by DoodleSauce** [comment]
ill be responding tomorrow btw

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/81512296-a0267200-92ed-11ea-9a7e-e1c668633679.png)

If a spritecode is in red in the expression previewer, its sprite isn't made and it won't work outside of the previewer

**Comment by DoodleSauce** [comment]
oh ok thanks does it means that its not be available available for use

**Comment by multimokia** [comment]
Not unless you make the sprite with the spritemaker tool (documented on the [Dialogue Coding](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding#the-tools-menu) section of our wiki)

**Comment by DoodleSauce** [comment]
does it need python 2 or i can run it with python 3

**Comment by multimokia** [comment]
It needs python 2

**Comment by DoodleSauce** [comment]
ok

**Comment by DoodleSauce** [comment]
how do i run it with python 2
(its already installed 2.7.17)

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/81586017-f72a5680-9382-11ea-9a2f-9361b472aea8.png)

**Comment by DoodleSauce** [comment]
im using linux

**Comment by multimokia** [comment]
If python is installed globally then, you can

```bash
cd '/path_to_tools_folder'
python toolsmenu.py
```

**Comment by DoodleSauce** [comment]
it says `bash: cd: too many arguments`

**Comment by ThePotatoGuy** [comment]
there's no expectation that you, as a dialogue writer, need to add the sprite code using the tools. If you submit a PR, we will add the missing sprite for you. 

however we will not provide a step-by-step tutorial on how to run python scripts in term. there are plenty of resources online on how to do this.

**Comment by DoodleSauce** [comment]
Ok thanks i'll look for it have a great day
