### ISSUE TITLE
[Suggestion] - Monika reacts to programming softwares

### ISSUE THREAD

**Issue by ElPolloRicolin** [Monika-After-Story/MonikaModDev#5759]
I dont know if its already or not implemented yet (i havent received any windows reaction of Monika) but since Monika mentions of tinkering with the code/ try to learn to programm for getting a job in the real world, maybe Monika should say when you have, for example idle or Visual study code something like "Oh! you are learning to code? maybe we could learn together!" or something like that

srry if already implemented or suggested already ;;

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
