### ISSUE TITLE
Suggestion for windows reactions

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#5763]
What I wanted to suggest is monika reacting to these websites if possible
http://www.themoongolf.com/headpat
https://www.davg25.com/apps/ddbc/?src=v0.8-b01

**Comment by DoodleSauce** [comment]
wait what i never knew those exist

**Comment by AsuraShun** [comment]
I found these last year

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
