### ISSUE TITLE
[Bug] - The game crashes before even start. 

### ISSUE THREAD

**Issue by Toja212** [Monika-After-Story/MonikaModDev#5771]
I just started the game as I always do, but this time the game crashes and never opens.
I tried to reinstall the entire mod again in the original game but it's still crushing.

I left attached the traceback here.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4628979/traceback.txt)

Thanks for the help and sorry for my bad english.

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please

**Comment by Toja212** [comment]
Here is the entire folder.

![Game folder 1](https://user-images.githubusercontent.com/65352689/81951254-38ca3400-9605-11ea-8e6a-435e9b09b738.JPG)
![Game folder 2](https://user-images.githubusercontent.com/65352689/81951260-3a93f780-9605-11ea-8c49-33aa377742c7.JPG)
![Game folder 3](https://user-images.githubusercontent.com/65352689/81951268-3cf65180-9605-11ea-9011-7bd9613aaa0f.JPG)

**Comment by multimokia** [comment]
You've got stuff from another mod installed here too

Every mod needs its own DDLC install to work correctly.

Grab a copy of DDLC from https://ddlc.moe/ then extract it to your desktop. Install MAS into that an run it from the exe file.

**Comment by Toja212** [comment]
Really?! Gosh I'm such an idiot.

Sorry for wasting your time and thanks a lot.
