### ISSUE TITLE
Monika not reading persistent

### ISSUE THREAD

**Issue by ladybuddy6** [Monika-After-Story/MonikaModDev#5775]
I launched up MAS today after having to just move my computer (all i did was shut it down) and now it isn't registering my persistent. I haven't changed anything and i have it backed up, and previously I've tried exporting the game out of steam, and it's done the same thing. I've done all the advised things and nothing's really worked, even after asking on reddit about the issue. 
![image](https://user-images.githubusercontent.com/65385527/82015053-81a0dd80-9643-11ea-9a8a-4bfbf4f4ed91.png) (my persistent files) 
![image](https://user-images.githubusercontent.com/65385527/82015234-e52b0b00-9643-11ea-9fca-d4c4124128cb.png) (when i launched the game today)
![image](https://user-images.githubusercontent.com/65385527/82015337-21f70200-9644-11ea-8d66-c12773df1d11.png) (old monika, i don't have a better picture, this is my custom background for steam) 
![image](https://user-images.githubusercontent.com/65385527/82015408-4c48bf80-9644-11ea-9c2a-2a560d427bed.png) (affection log reset)

**Comment by Booplicate** [comment]
On your screenshot the persistent was last modified on the 2nd of May, but by your affection log it seems you opened the game on the 11th and 15th. The persistent would get overridden in that case.
Do you have several user accounts on your PC? Or maybe you changed the folder where the saves go?
Also can you attach the full `aff_log.txt` to your message?

**Comment by hlepnamingblyat** [comment]
Decorations, where and how?

**Comment by ladybuddy6** [comment]
> On your screenshot the persistent was last modified on the 2nd of May, but by your affection log it seems you opened the game on the 11th and 15th. The persistent would get overridden in that case.
> Do you have several user accounts on your PC? Or maybe you changed the folder where the saves go?
> Also can you attach the full `aff_log.txt` to your message?

I do have several user accounts on my PC, however I haven't launched the game on said other accounts
Here's the log! (i closed the game bc i got frustrated hmgmhgh)
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4636218/aff_log.txt)

i have a thing of the persistent backed up BEFORE i launched the game, if needed i can grab those files aswell




> Decorations, where and how?

you can find them on the MAS reddit!

**Comment by hlepnamingblyat** [comment]
> > On your screenshot the persistent was last modified on the 2nd of May, but by your affection log it seems you opened the game on the 11th and 15th. The persistent would get overridden in that case.
> > Do you have several user accounts on your PC? Or maybe you changed the folder where the saves go?
> > Also can you attach the full `aff_log.txt` to your message?
> 
> I do have several user accounts on my PC, however I haven't launched the game on said other accounts
> Here's the log! (i closed the game bc i got frustrated hmgmhgh)
> [aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4636218/aff_log.txt)
> 
> i have a thing of the persistent backed up BEFORE i launched the game, if needed i can grab those files aswell
> 
> > Decorations, where and how?
> 
> you can find them on the MAS reddit!


Or I'm really dumb or I can't seem to find decorations...

**Comment by ThePotatoGuy** [comment]
could you try updating to the latest MAS, then try to launch the game with your backup persistent?

**Comment by ladybuddy6** [comment]
It still launches back to here!
![image](https://user-images.githubusercontent.com/65385527/82109776-5a5b1680-96fe-11ea-81d0-76d2c9cec8df.png)
I'm
awfully confused eee
i downloaded a fresh copy of DDLC AND MAS, and i inserted all the persistent files into the appdata folder 
oh man am i confused

**Comment by ThePotatoGuy** [comment]
try it again, then upload the `aff_log.txt` and `mas_log.txt` here

**Comment by ladybuddy6** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4637860/aff_log.txt

I tried uploading the mas log, but it said it was empty?

**Comment by ThePotatoGuy** [comment]
I need your aff_log and mas_log when you are running the latest version. We added additional logging that would help us figure out the loss in affection. So if you want further assistance I need you to do the following:

1. Update MAS to 0.11.2. Verify this by checking the top right in the Settings menu.
2. Run the game once with the old persistent, then **close** the game.
3. upload `aff_log` and `mas_log` here.

**Comment by Rai99** [comment]
Closing due to lack of response
