### ISSUE TITLE
Topic unlocks with pre-existing dependencies

### ISSUE THREAD

**Issue by LooseEthics** [Monika-After-Story/MonikaModDev#5776]
Suppose a new topic (A) is written which requires the player to have previously seen some already implemented topic (B), like the amnesia greeting or the Python tips. My understanding is that the unlock code for A would run when B is viewed. This, however creates a problem - an older player might not think to re-read an old topic if they've already seen it, leaving A locked permanently, especially if B doesn't show up in Monika's random chatter. Is some mechanism which would handle cases like these implemented?

**Comment by Booplicate** [comment]
Use the [`conditional` property](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding#using-conditionals).

**Comment by LooseEthics** [comment]
Alright, thanks.
