### ISSUE TITLE
How do I edit the archive?

### ISSUE THREAD

**Issue by Vision-dong** [Monika-After-Story/MonikaModDev#5779]
I have some unexpected problems...I need to edit the archive to solve them, but the archive is encrypted. Is there any way to edit the archive...?
I really need it

**Comment by multimokia** [comment]
What problems are you having and why do they require you to edit script files?

**Comment by Vision-dong** [comment]
It's really hard to describe, but specifically I need to delete some eventlabels written to the archive

**Comment by Booplicate** [comment]
Just removing some labels can break your game. Not to mention that you'll have to do it every update.
What's your plan? There may be a more easier solution for you. By archive you mean an `rpyc` file, right?

**Comment by Vision-dong** [comment]
No，I mean the BAK file in the renpy folder of the system disk，as for the eventlabels, I added them by myself. I just need to delete them once

**Comment by multimokia** [comment]
We don't tell people how to edit their persistents. If you're testing dialogue and such you should be doing it in a test install with a local persistent as to not interfere with your own.

You'll want to restore a backup prior to your code changes.

**Comment by Vision-dong** [comment]
Well, anyway, thank you. I just need to reopen an archive

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
