### ISSUE TITLE
[Suggestion] Update Totono/You and Me and Her topic

### ISSUE THREAD

**Issue by Feenie** [Monika-After-Story/MonikaModDev#5781]
We have an official release of Totono in English, and I feel the dialogue could use updating. While Miyuki does wish she could hurt the player for her betrayal, she hurts the player character instead. She _was_ proactive in Aoi's route in trying to get Shinichi to stop, but ultimately fails if you continue Aoi's route.

Maybe change it so Monika acknowledges Miyuki at least tried to stop Shinichi and actively hurt the player character?

**Comment by ThePotatoGuy** [comment]
for our reference, this is `monika_totono`

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
