### ISSUE TITLE
How do i give coffee to Monika, also, for some reason, she cant detect the cloths a give her

### ISSUE THREAD

**Issue by beter23247** [Monika-After-Story/MonikaModDev#5782]
I changed computers, and restored the persistent, since all the progress was saved, but the cloths i give here and my old pc, i tried giving her them again, and she dont read them. Also, how do i give her coffee?

**Comment by multimokia** [comment]
You need to install the spritepacks for gifted clothes. If you didn't install them, then that's why she can't read them.

Coffee is `coffee.gift`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
