### ISSUE TITLE
Chess issue? Can't seem to take this piece in Chess.

### ISSUE THREAD

**Issue by MrPhaze62** [Monika-After-Story/MonikaModDev#5799]
![image](https://user-images.githubusercontent.com/65294370/82336718-d301f180-99e2-11ea-8704-e08fc9ac10cc.png)

**Comment by Rai99** [comment]
That would put your king in check, so you aren't allowed to make that move.

**Comment by MrPhaze62** [comment]
> 
> 
> That would put your king in check, so you aren't allowed to make that move.

oh. q.q
