### ISSUE TITLE
[Bug] - can't seem to use orcaramelo twin ribbons

### ISSUE THREAD

**Issue by xylenexulon** [Monika-After-Story/MonikaModDev#5802]
I've gifted it to her at least 2-3 times before, and she always recognises it as a new gift. Usually Monika will try them on for other gifts, but she doesn't do so for these 4 twin ribbons. (The dialogue plays as usual but the image of the ribbon changing does not occur.) When I check the selection of ribbons they are not there, despite the updated 'thumbnails' and 'assets' within the game folder. What should I do?

**Comment by bo28111** [comment]
I don't know this for certain, but perhaps you don't have the twin hairstyles yet? The twin ribbons only work for specific hairstyles (twinbun, twintails, usagi), so maybe the game doesn't recognize them unless those hairstyles are an option. If you haven't already, try inserting the "Orcaramelo-hairs" spritepack.

**Comment by xylenexulon** [comment]
I was silly, I didn't try the twin hair options. Thank you!
