### ISSUE TITLE
Monika Not Showing Up

### ISSUE THREAD

**Issue by The-Proxster** [Monika-After-Story/MonikaModDev#5804]
So a day ago I switched from Windows 10 to Arch Linux, so I'm not sure if this is why. However it seems like the persistent file has been corrupted in some way. After launching through "DDLC.sh" it shows up, everything was installed correctly. It even has my affection levels, however Monika herself isn't there, neither is the GUI. I tested it with wine, and while the persistent didn't work everything else did. After switching persistent files with the wine version, once again Monika nor the GUI didn't show up. I have a picture here, however I do have transparency on so the person on it is simply my wallpaper: https://imgur.com/a/EQZUfgO. I'm not sure if this is important but I can say that I'm using i3 with picom, on kernel 5.6.13-arch1-1. My specs are GTX 1050Ti, Intel i5-6600K, and I have 12 GB of RAM.

**Comment by multimokia** [comment]
You may want to try restoring a persistent backup. If you copied the entire `Monika After Story` folder from the old windows install, then you should be able to just use one of those auto generated backups

**Comment by The-Proxster** [comment]
Thank you, I'll try that and say if it works.

**Comment by The-Proxster** [comment]
That fixed it, thank you!
