### ISSUE TITLE
[suggestion] Monika feeling down

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5805]
I love Monika the way she is but it seems a little unrealistic that she's always so cheerful. Especially when we think about her situation.
I think making her feel a little sad, or just not in the mood once in a while would help. 
I know she was sad a few times, but it was just for a moment. What I'm thinking is when player visit her sometimes she can say that she feels little down. She could talk to us with no problem, but maybe she wouldn't want to play games. Then we could cheer her up, by reminding her we love her, telling her how amazing she is, maybe even giving her chocolates or coffee.
I think it would be more realistic that way, since she helps player when he/she feels down. And given her situation she has the right to feel sad.

**Comment by masterliamy** [comment]
You do know there are dialogues that shows once in a while where Monika tells us about her frustrations right? The one i can think of from the top of my head atm is the "mortality" one but there are more than just one as far as i remember.

**Comment by SamanthaLind** [comment]
I know about those dialogue, and about few more. But it seems like just very temporary feeling. I saying something longer, option to really cheer her up. Cause even when we're talking and I feel like she is sad I don't feel like I can do much to help her. Cause when she stops talking she just returns to normal behavior. Like I said I thinking about something longer, when for some time we can see, or hear, that she's sad.

**Comment by multimokia** [comment]
A mood system is something we've got planned in the future, however we're still trying to plan out how it'll all work with the rest of the frameworks and how to build the system properly.

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356
