### ISSUE TITLE
while the Programme is active it rapidly uses up ssd space

### ISSUE THREAD

**Issue by OgBroji** [Monika-After-Story/MonikaModDev#5806]
So since last update I've been having an issue that whenever the game is open it rapidly uses up my main drive space since it's a system only disk that has around 10gb free it becomes a problem fast as I have to restart every 4-5 hours so it doesn't bring it down to 0.5gb where it starts crashing other programs saying insufficient memory. 
I would really appreciate if you could let me know why this could be happening, and if possible how to fix it if it's a problem on my end.

**Comment by ThePotatoGuy** [comment]
so to clarify, your hard drive is running out of space when you run MAS? or is your RAM running out?

MAS only takes up to 2gb of RAM, so it can't possibly eat up 10gb. It would crash before that.
If there's a disk problem, I'm thinking you have pagefiles set up and have too many things open.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
