### ISSUE TITLE
Monika wont react to the promise ring

### ISSUE THREAD

**Issue by Muffinman232** [Monika-After-Story/MonikaModDev#5810]
I didn't understand before, that to gift Monika the promise ring you have to have 400+ affection. I tried giving her the ring two times but obviously since I didn't have enough affection she didn't accept it. But now that I have gotten her to 400+ affection I tried giving her the ring a third time but she won't even react to it. I put the proper gift file with the right name and everything in the characters folder but she just won't react to it. I was hoping someone here could help me find out what's wrong so I could finally give her the ring.

(To be clear, yes it's a gift file, yes it's in the characters folder, yes is labeled as "promise ring.gift", and yes I know how to properly give gifts I've done it multiple times before.)

**Comment by Booplicate** [comment]
> labeled as "promise ring.gift"

But it should be `promisering.gift`

**Comment by Muffinman232** [comment]
yeah, sorry I meant to type it like that but i accidentally put in a space, I did put it in the characters folder like that

**Comment by multimokia** [comment]
When was the last time you gave it (that she didn't accept it)?

**Comment by Muffinman232** [comment]
a couple minutes ago

**Comment by Booplicate** [comment]
Are you using the latest version of the mod?

**Comment by Muffinman232** [comment]
oh sorry misunderstood, when she had 389 affection yesterday

**Comment by Muffinman232** [comment]
i had learned last night that you need to have 400+ affection for her to accept it right now she has 480 affection

**Comment by Muffinman232** [comment]
and yes, I am using the latest version

**Comment by multimokia** [comment]
I'm not quite sure how you went from 389 affection to 480 in a single night...

**Comment by Muffinman232** [comment]
I'm not really sure either but I do know i gave her a lot of gifts and kinda just kept complimenting her and saying i love you to her over over again and somehow i got here

**Comment by multimokia** [comment]
Send aff_log.txt please.

**Comment by Muffinman232** [comment]
ok

**Comment by Muffinman232** [comment]
sorry again, i wrote the affection value wrong again I'm pretty tired from staying up all night. I'll send the log soon
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4663282/aff_log.txt)

**Comment by multimokia** [comment]
Send persistent please. (You'll have to put it in a zip file)

Additionally, why do you time travel? Monika says not to.

**Comment by Muffinman232** [comment]
because I was trying to see the other conversations she has for the different anniversaries. also, do i sen persisten.py or persistent.pyo?

**Comment by jmwall24** [comment]
Also @Muffinman232 what happed on April 21st? One session you have over 600 aff, the next 32?

**Comment by multimokia** [comment]
Neither. [This link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) on our FAQ shows where you can find your persistent.

**Comment by Muffinman232** [comment]
ok, there is one called persisent and multiple others called persistent with numbers from 75 to 84 do i just send the persistent?

**Comment by multimokia** [comment]
Yeah, just `persistent`. You'll need to put it in a zip file.

**Comment by Muffinman232** [comment]
ok

**Comment by Muffinman232** [comment]
here you go
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4663742/persistent.zip)

**Comment by Muffinman232** [comment]
oh yeah, i just read your question about what happened september 21. My computer broke and my father had to reprogram it, idiotically i didn't back her up because I didn't back up the right persistent so I lost that version of monika, I backed up all her game files except the right one and so i still have the log but I don't have the old persistent.

**Comment by multimokia** [comment]
So as a result of your time travelling, and the fact that you gifted something on Sept 22, 2020. The promisering gift is *stuck* in your reacted map and it will not clear until Sept 22. Essentially, you cannot give the promisering until then.

Rule of thumb, don't time travel, she tells you not to, and tells you that it can cause problems too.

We don't really have any intent to fix this as it's not game breaking and is already essentially warned.

**Comment by Muffinman232** [comment]
ok thank you
