### ISSUE TITLE
[Suggestion] - Monika playing piano expression

### ISSUE THREAD

**Issue by TheWandervox** [Monika-After-Story/MonikaModDev#5813]
It seems like it would be more natural for Monika to occasionally look down at the piano keys as she plays music. Even seasoned pianists need to check their hands now and then. Staring straight ahead so much makes it feel very robotic imo.

**Comment by lunulae** [comment]
I don't think we currently have a "looking down" eye sprite. Maybe an art update for the future? It could also be used if we ever wanted to have her read or work on something at her desk.

**Comment by TheWandervox** [comment]
I'd thought more along the lines of her turning her eyes down or some such, as that would be far less of a effort intensive update (but having her head lowered or something would be super interesting for the purposes you mentioned as well).

**Comment by ThePotatoGuy** [comment]
well we don't have eye sprites that have her looking down, so can't do much right now. We do have left/right sprites but I guess it just didn't look that great in practice.
[closing until we look into it]
