### ISSUE TITLE
Topic question - Should this be a story or a random topic?

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#5817]
I was thinking about writing a topic (born out of a deep wiki dive) about the supposed origins of coffee. It seems that there isn't a definitive answer for where it was first discovered, but there are a few legends that tell of possible discoveries.

Firstly, I was wondering if it would be a good fit for the mod, since most of these legends do have some religious origins. I would try to write in such a way as not to favor a particular faith or telling, but I know that it might be best to check in about it just in case.

Second, if it gets the go-ahead, I was wondering if folks would prefer this as a random topic, fun fact, or a "tell me a story" prompt. I'm leaning toward a story format, but I'm not sure.

**Comment by multimokia** [comment]
Sounds like a fun fact to me
