### ISSUE TITLE
[Assistance] Need help coding secret project!

### ISSUE THREAD

**Issue by SirNimblyBottoms** [Monika-After-Story/MonikaModDev#5818]
Can't put too much information here as I'm planning to release a special sprite addition to MAS that is going to be a surprise.  I am having a difficult time coding the sprite as it is unconventional to the current ACS categories. I'm not sure if this is the main reason why Monika can't read the file, or if its because of my amateur coding abilities (lol). Anyway, if there's somebody here that is proficient with sprite coding I would be forever great full for your help!

p.s. Don't want to post the files here so the project gets spoiled, but I can DM them or find another private method of sending them.  Thanks

**Comment by Delcos** [comment]
feel free to pm, though I may be sow to respond.

**Comment by SirNimblyBottoms** [comment]
> feel free to pm, though I may be sow to respond.

HI! Thanks for getting in touch. Where would you like me to PM you?
