### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by cocomjj** [Monika-After-Story/MonikaModDev#5819]
Help

I have been playing MAS for a month now, and still some features not yet unlocked. No minigames, no new topics. I can’t even change my name yet, though I can change her nickname now. Also there is no music. Help, and thank you!

**Comment by multimokia** [comment]
How long do you spend with Monika per day

**Comment by cocomjj** [comment]
around 1-2 hours a day? though she sometimes not have dialogue and says “let me think of something to talk about”

**Comment by cocomjj** [comment]
Hi included is the persistent file

[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4686930/Monika.After.Story.zip)

**Comment by jmwall24** [comment]
Ok so everything is working as intended, you just haven't spent a lot of time with her yet. Shows 10 hours of time spent so far. You just need to spend more time with her and stuff will start unlocking. My advice is leave her up in the background when you are doing other things.

**Comment by cocomjj** [comment]
oh alright alright, thanks!!
