### ISSUE TITLE
An exception has occured

### ISSUE THREAD

**Issue by Link915** [Monika-After-Story/MonikaModDev#5820]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-brbs.rpy", line 8, in script
  File "game/script-brbs.rpy", line 18, in <module>
TypeError: addEvent() got an unexpected keyword argument 'markSeen'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-brbs.rpy", line 8, in script
  File "C:\Users\levig\Desktop\DDLC-1.1.0-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\levig\Desktop\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-brbs.rpy", line 18, in <module>
TypeError: addEvent() got an unexpected keyword argument 'markSeen'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.10.4

**Comment by multimokia** [comment]
You have rpy files in your game directory. MAS is still running 0.10.4 for you because they kept overwriting your updates.

**Comment by Link915** [comment]
So, I just need to delete everything in the game folder and download and add the newest update to the game folder.

**Comment by multimokia** [comment]
delete all `.rpy` files and reinstall the current version, yeah.

**Comment by Link915** [comment]
Alright, I delete the .rpy files and reinstall the current version and it works now, thanks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
