### ISSUE TITLE
[Help Wanted] Looking for rockstar coder

### ISSUE THREAD

**Issue by SirNimblyBottoms** [Monika-After-Story/MonikaModDev#5821]
Hi! My previous request had a problem with it, so my apologies on the repost. I’m working on a special jewelry item for MAS that I’m having trouble coding. Particularly because I’m not sure where to group this specific item as there’s no menu select option for it, and  I’m also an amateur at coding lol. If anybody would be interested in helping me out with this project, that would be awesome! Due credit will of course be given to you when the item is released. I can be reached on the MAS discord with the same username. If you’d prefer a different method of contact please let me know. Thanks for reading!

**Comment by multimokia** [comment]
If this is a personal project. Please refrain from asking for someone to help you work on it here as this is mainly related to development for everyone. If you intend to release this to everyone via official spritepacks, we can handle the json creation/reaction creation for you.

**Comment by ThePotatoGuy** [comment]
as i mentioned in dms yesterday, we need to address #5027 before we can make a selector for ur ACS. for now you will have to manually wear the ACS or temporarily group it with something unrelated. 

i also thought you were going to send me ur spj log.

**Comment by SirNimblyBottoms** [comment]
I dont't have any intentions of releasing this to the official spritepacks as of right now.  Once issue #5027 is addressed I might be open to it. My spj log is linked below:

[log.spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4674295/log.spj.txt)

I can take my request elsewhere if posting it here is an issue. My apologies.
