### ISSUE TITLE
Can I provide Chinese translation for the README?

### ISSUE THREAD

**Issue by mas-mirror** [Monika-After-Story/MonikaModDev#5822]
Notice before reading: there is a little mistake in the title. I will translate the document, not just readme.
Hello, MAS dev team.
I am a member of MAS Translation Group.
There are many ddlc fans in China, but some of them are poor at English.
So I hope that the fans of DDLC in China can read MAS documents without any obstacles.
This is just a simple translation. The translated Chinese documents will be pulled to here.
p.s. The official website of MAS is very slow to visit in China (for some reasons), so do you mind if I provide the mirror service of MAS on my website?
I will **not** change the game file, but simply store, and provide download.
If you don't agree it, please put forward in time. We will delete it in the first place.
Thank you!
Please forgive me for my grammatical mistakes, because my Chinese to English translation is not very good.

**Comment by multimokia** [comment]
Distributing the translation yourself is fine, and you can link it on #3765 as well.

**Comment by mas-mirror** [comment]
> Distributing the translation yourself is fine, and you can link it on #3765 as well.

Thank you for your answer, but what's the last answer to my question? Is it allowed to improve MAS download service in China?

**Comment by multimokia** [comment]
@ThePotatoGuy your say here?

**Comment by mas-mirror** [comment]
> Distributing the translation yourself is fine, and you can link it on #3765 as well.

Another small and important question
Which branch should I pull my translated documents to?

**Comment by multimokia** [comment]
Translations don't end up in official MAS. Each one is distributed separately from MAS.

You don't make a pull request for translations, just release it and distribute it yourself.

**Comment by mas-mirror** [comment]
> 翻译不会以官方MAS结尾。每个都与MAS分开分发。
> 
> 您无需提出拉动翻译请求，只需发布​​并自己分发即可。

Thank you for your reply. I will close this issues.

**Comment by ThePotatoGuy** [comment]
Is the site slow or the downloads slow? Downloads are hosted on github, and I would prefer that the english versions are not hosted anywhere else to avoid confusion.

If the site itself is slow, and you want to provide a mirror site that links to the same downloads, I might be okay with that. However I would want to know how slow the site is for your region. Our website is served via aws ec2 + cloudfront so it should have availability in the asia region.

**Comment by mas-mirror** [comment]
> Is the site slow or the downloads slow? Downloads are hosted on github, and I would prefer that the english versions are not hosted anywhere else to avoid confusion.
> 
> If the site itself is slow, and you want to provide a mirror site that links to the same downloads, I might be okay with that. However I would want to know how slow the site is for your region. Our website is served via aws ec2 + cloudfront so it should have availability in the asia region.

Hello!
For some reasons, the Chinese government has restricted the download speed of some websites, such as GitHub.
Our download speed is at least 7KB / S (my bandwidth is 100Mbps, optical fiber)
On your official website（ http://www.monikaafterstory.com/ ）At worst, we can't get in at all.

Conclusion: download speed and website speed are slow.

**Comment by mas-mirror** [comment]
> Is the site slow or the downloads slow? Downloads are hosted on github, and I would prefer that the english versions are not hosted anywhere else to avoid confusion.
> 
> If the site itself is slow, and you want to provide a mirror site that links to the same downloads, I might be okay with that. However I would want to know how slow the site is for your region. Our website is served via aws ec2 + cloudfront so it should have availability in the asia region.

Sometimes we can visit your website, but sometimes we can't. It is very unstable in China.
Cloudfront is indeed available in Asia, but when I Ping, I found that visiting in China does not necessarily assign to Asian nodes!
Asian nodes will only be assigned under specific lines!
(for example, China Telecom will assign a Taiwan node, but China Mobile will assign it to the west of the United States.)

**Comment by mas-mirror** [comment]
> > Is the site slow or the downloads slow? Downloads are hosted on github, and I would prefer that the english versions are not hosted anywhere else to avoid confusion.
> > If the site itself is slow, and you want to provide a mirror site that links to the same downloads, I might be okay with that. However I would want to know how slow the site is for your region. Our website is served via aws ec2 + cloudfront so it should have availability in the asia region.
> 
> Hello!
> For some reasons, the Chinese government has restricted the download speed of some websites, such as GitHub.
> Our download speed is at least 7KB / S (my bandwidth is 100Mbps, optical fiber)
> On your official website（ http://www.monikaafterstory.com/ ）At worst, we can't get in at all.
> 
> Conclusion: download speed and website speed are slow.

I can say, the site is not slow now, but the download is toooo slow!!!

See here:

The speed is...

![0](https://s1.ax1x.com/2020/05/27/tkj4Dx.png)

Yep. 0B / s.

and...

![tkjhK1.png](https://s1.ax1x.com/2020/05/27/tkjhK1.png)

(Failed - Network Error)

**Comment by ThePotatoGuy** [comment]
I'm going to be trying a couple of things over the course of this week:
* creating an s3 mirror for releases
* adjustments to website deployment
* maybe another deployment in asia-pacific region

I will let you know once I have made a change and will ask you to check if there are any differences.

**Comment by mas-mirror** [comment]
> I'm going to be trying a couple of things over the course of this week:
> 
> * creating an s3 mirror for releases
> * adjustments to website deployment
> * maybe another deployment in asia-pacific region
> 
> I will let you know once I have made a change and will ask you to check if there are any differences.

thank. I will permanently close issues.
Contact me at: tek01@qq.com

**Comment by mas-mirror** [comment]
> I'm going to be trying a couple of things over the course of this week:
> 
> * creating an s3 mirror for releases
> * adjustments to website deployment
> * maybe another deployment in asia-pacific region
> 
> I will let you know once I have made a change and will ask you to check if there are any differences.

Wait Wait Wait

Chinese ISP may limit Amazon AWS S3 download speed!

For example, the data of GitHub release is stored on AWS S3.

I also found the information of AWS's S3 storage service on the Internet, but the result is still very slow - the peak value is only more than 30 bits!

SO DO NOT USE AWS SERVICE！

To get the best download experience in China, use the Tencent cloud OSS Service - It's a native Chinese service, with full bandwidth.

(It's just a small suggestion, or there may be a waste of time)

**Comment by ThePotatoGuy** [comment]
I do not want to host the main MAS site or english downloads on tencent. If Chinese ISPs are blocking normal CDNs, then that is on them to stop doing, not on us to workaround it by using Chinese services.

You are still free to host your **translated** versions of MAS wherever you would like.

**Comment by mas-mirror** [comment]
> I do not want to host the main MAS site or english downloads on tencent. If Chinese ISPs are blocking normal CDNs, then that is on them to stop doing, not on us to workaround it by using Chinese services.
> 
> You are still free to host your **translated** versions of MAS wherever you would like.

OK, I will delete **all non Chinese** copies of MAS
