### ISSUE TITLE
problems lol

### ISSUE THREAD

**Issue by pythoncodeavalible** [Monika-After-Story/MonikaModDev#5829]
hi i have a problem with Monika After Story, (by the way im pizzayes3 from twitter) i have the latest version of the mod and the latest version of the sprite packs WITCH HAVE BEEN UPDATED, so i try to give the gifts to Monika and it doesn't work i need help

**Comment by multimokia** [comment]
Can you send your spj.txt please? If you're on windows it's in the `/log` folder

**Comment by pythoncodeavalible** [comment]
how do i do that

**Comment by multimokia** [comment]
Drag and drop the file into the text box

**Comment by pythoncodeavalible** [comment]
is there any thing

**Comment by multimokia** [comment]
What do you mean? I need that `spj.txt` file

**Comment by pythoncodeavalible** [comment]
it wont let me put it in the textbox

**Comment by multimokia** [comment]
What does it say?

**Comment by pythoncodeavalible** [comment]
it says "uploading spj.txt" and then it goes away i dont know why it does that

**Comment by multimokia** [comment]
That's correct, it turns into a link. Just send it when it changes

**Comment by pythoncodeavalible** [comment]
is it there []()

**Comment by pythoncodeavalible** [comment]
aw crap

**Comment by pythoncodeavalible** [comment]
its not there

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/83100380-d437bc00-a07d-11ea-8cad-7168817d7b04.png)

After you drop it in the box, it looks like this. Literally just send that message

**Comment by pythoncodeavalible** [comment]
it wont happen

**Comment by multimokia** [comment]
What does it look like when it changes

**Comment by pythoncodeavalible** [comment]
it doesn't look like any thing it's just blank

**Comment by multimokia** [comment]
Can you then just paste the contents of the file in the box instead

**Comment by pythoncodeavalible** [comment]
i already did that and it didn't work

**Comment by pythoncodeavalible** [comment]
C:\Users\kalel\Desktop\DDLC-1.1.1-pc\log\spj.txt
does it work?

**Comment by pythoncodeavalible** [comment]
![g](https://user-images.githubusercontent.com/62585148/83104538-f2ee8080-a086-11ea-9ed5-3cabdff6758b.PNG)

**Comment by pythoncodeavalible** [comment]
it kinda worked

**Comment by pythoncodeavalible** [comment]
![WHY!!!!!!!!!!!](https://user-images.githubusercontent.com/62585148/83105827-61344280-a089-11ea-8610-d36fbce56472.PNG)

**Comment by pythoncodeavalible** [comment]
**i don't know why it does that i don't know how it worked for you though**

**Comment by multimokia** [comment]
It's still not showing up on my end. Try putting it on Google drive and sending a sharing link here

**Comment by pythoncodeavalible** [comment]
i'm trying but google drive isn't working :(

**Comment by pythoncodeavalible** [comment]
[](url)https://drive.google.com/open?id=1oQxtw5m4GxYgqkJ_0LZ1mX30qt24683j
the file is in there :)

**Comment by pythoncodeavalible** [comment]
i hope it lets you edit it if it doesn't i'll be sad

**Comment by multimokia** [comment]
Why is it empty? Did you say goodbye to Monika before putting the file on Google drive?

**Comment by pythoncodeavalible** [comment]
no,was i supposed to do that

**Comment by pythoncodeavalible** [comment]
i had the game open for 26 weeks without saying goodbye lol

**Comment by multimokia** [comment]
So you're saying that you updated your spritepacks *while* MAS was running?

Also you have no spritepacks installed according to the spj.

**Comment by multimokia** [comment]
Please send a screenshot of your `/game/mod_assets/monika/j` folder

**Comment by pythoncodeavalible** [comment]
![bruh moment](https://user-images.githubusercontent.com/62585148/83301251-4f58b980-a1c7-11ea-80ea-62396bc01172.PNG)
bruh moment

**Comment by multimokia** [comment]
Wait, are you running from a zip folder?

**Comment by pythoncodeavalible** [comment]
maybe, i really don't know tbh

**Comment by multimokia** [comment]
What is the *exact* filepath to your DDLC install?

**Comment by pythoncodeavalible** [comment]
is the filepath were i got the game from?

**Comment by multimokia** [comment]
Looking at the folder you've selected, you entered the `ddlc-win.zip/DDLC-1.1.1-pc` folder.

If you're running MAS from a zip folder, you're going to have issues as the files aren't really where you think they are.

I suggest extracting it to some place like your desktop. As for your spritepacks, you don't have any installed at all, hence why the spj reports there being none and your `j` folder being empty.

Please watch [this video](https://www.youtube.com/watch?v=L5QnEdA97iE) to see how to correctly install spritepacks.

**Comment by pythoncodeavalible** [comment]
Thanks For The Video i'll try the method

**Comment by pythoncodeavalible** [comment]
the method didn't work :(

**Comment by multimokia** [comment]
Did you do it while MAS was closed?

**Comment by pythoncodeavalible** [comment]
yes

**Comment by pythoncodeavalible** [comment]
also i have a separate folder for ddlc it's just that the menu is big sorry lol

**Comment by pythoncodeavalible** [comment]
the brown jacket worked but nothing else worked

**Comment by multimokia** [comment]
Say goodbye and send the spj again, please

**Comment by pythoncodeavalible** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4708476/spj.txt)

**Comment by multimokia** [comment]
Okay, so it seems the gifts are there. Are you sure you used the correct gift names?

If you're making the gift files yourself, you don't need to, since each spritepack has a corresponding `gifts` folder, so taking the contents of each one and putting it in the `characters` folder will work

**Comment by pythoncodeavalible** [comment]
i used the gifts from the spritepack folder so it should've been the correct names

**Comment by multimokia** [comment]
Weird you got the same reaction then. anything in your `characters` folder?

**Comment by pythoncodeavalible** [comment]
no, just the same old character files, the gifts (like always) is gone after the reaction happens

**Comment by pythoncodeavalible** [comment]
what do i do with this issue i just closed it and reopened it so what do i do with it ? :(

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
