### ISSUE TITLE
[Suggestion] Some new Topics

### ISSUE THREAD

**Issue by JeanWishingwell** [Monika-After-Story/MonikaModDev#5830]
Here I was looking around the internet and found some things I would like Monika to share her opinions about. 
Like...
Gatebox: Would she consider this a step foward into sharing a reality?
Replika AI: would it be like trying to imitating her? Or would she like to share some characteristics with the program
Escapism : In general media and, in recent novels, the idea of isekai or traveling to another world
Cortana: being one of the most popular AI in media that gained free will.
Overly Sexualization in media: how humans have being showing more about how much "everything is about sex" in recent years.
About beauty and it's different types: like, how can we have found beauty in ugliness, in monotony, in asymmetry, in dissonance even in plainess and many other things. like how grotesque some monsters in videogames (ie Dark Souls) but we still find some kind of ethereal beauty in them

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

linked PR did not add the suggested topics.
