### ISSUE TITLE
Some Dialogue and Nickname Reaction (Possible Spoiler?)

### ISSUE THREAD

**Issue by JmDemisana** [Monika-After-Story/MonikaModDev#5834]
Ey guys. So I have a little addition to the the dialogue. Sorry, I don't know how to manipulate GitHub code, so I'll just add it here. Just two because I only do this in my free time and my free time is thin, lol.
[This is about Manga versions of Visual Novels](https://github.com/Monika-After-Story/MonikaModDev/files/4699591/dialogueaddition1.txt)
[This is about the secret CG on The DDLC Store](https://github.com/Monika-After-Story/MonikaModDev/files/4699910/dialogueaddition2.txt)

Also, I played with Monika's reactions to the nicknames the player gives her, and I might add up as well.
[Nickname Reactions](https://github.com/Monika-After-Story/MonikaModDev/files/4699589/nicknamereactions.txt)

I get it if it's discarded tho. Or you can edit it to be Monika-like. hehe

**Comment by LooseEthics** [comment]
imo both of the topics would need to be at least partially rewritten. For example, I don't think Monika asking you to buy the merch really has a place here.
The nickname reactions are pretty good tho.

**Comment by JeanWishingwell** [comment]
I think there are some reactions already, but I'd love to see more like yours in the game.
But maybe we're looking at it wrong? Shouldn't we expand this idea and make something similar to the daydreaming topic? Something like a "Flirt" option where you randomly say something to her and she reacts to that. We could even ask for the community to send their best pickup lines and make a poll to chose 5 lines to upload per update.
could be

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
