### ISSUE TITLE
[Suggestion] Topic on why do people wear engagement (or promise) rings on their ring finger on the left hand

### ISSUE THREAD

**Issue by CoffeeJackaboy** [Monika-After-Story/MonikaModDev#5835]
The title pretty much explains everything, also the reason is because the Romans believed that the vein in the ring finger on the left hand ran directly to one's heart (wich unfortunately isn't ) and because of this they called that vein "vena amoris"(or vein of love in english).

**Comment by multimokia** [comment]
Sounds like it can be an extension of the existing promise ring topic

**Comment by ThePotatoGuy** [comment]
attaching to both topic pool and issues in case we decide to either.

[closing until we look into it]
