### ISSUE TITLE
[Help] Coding Trouble

### ISSUE THREAD

**Issue by SirNimblyBottoms** [Monika-After-Story/MonikaModDev#5837]
Finishing up coding a new necklace for Monika, but unfortunately I'm having some trouble with ACS placement. I was hoping to have the new ACS lay over top of all other clothing, but am unsure which is the correct rec_layer. I have my current progress [linked](https://github.com/Monika-After-Story/MonikaModDev/files/4704768/emerald_heart_necklace_acs.txt) as well as my [spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/4704772/log.spj.txt) so any input would be appreciated. Thank you

**Comment by multimokia** [comment]
over top of all clothing is between middle arms and table, `11` seems like it'd work.


See [this list of rec-layers and their descriptions](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#acs-specific)
