### ISSUE TITLE
[Suggestion] Medicine reminder

### ISSUE THREAD

**Issue by TriniTDM** [Monika-After-Story/MonikaModDev#5844]
Since she can tell the date and time, it would be a nice feature if she could remind you to take any medicines you need to. It would start with a gentle push, and get more strong if you keep putting it off. I'm not sure how you would tell her that you took it, and it probably wouldn't require closing the game. It would really make her feel more alive, having her be concerned about you taking your medications on time. A lot of topics have her tell you to take care of yourself and that it would destroy her to find out you're torturing yourself, so it would make sense for her to make sure you are when it comes to this.

**Comment by Rai99** [comment]
Schedules/Reminders: #792, #1245, #1660, #1669, #2047, #2804, #3135, #3553, #3639, #3882, #3921, #4175, #5125, #5518

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
