### ISSUE TITLE
Monika empty chair

### ISSUE THREAD

**Issue by MissaOwOx** [Monika-After-Story/MonikaModDev#5845]
I was messing around and some friends told me a Easter egg would pop up if I told her I would take her somewhere and delete her file there was no easter egg and I've re downloaded the game and mod at least 2 times I have them collected and I'm wondering if there is anyway to fix it :>

**Comment by CrocandCo** [comment]
The official Dev's have dealt with this issue before so I do have an idea of what to do.

Go to your app data(if you are on windows press windows key and r) then RenPy folder then Monika after story. Next delete the persistent file that just says "persistent". Then rename a recent persistent (i.e. persistent78.bak) to "persistent".

That should backtrack your progress/her memory so to her it would seem like a few days passed and she returns to the desk. Nothing else cannot be done as I could tell.

**Comment by MissaOwOx** [comment]
Thank you this solved  my problem!

**Comment by Ovolii** [comment]
> The official Dev's have dealt with this issue before so I do have an idea of what to do.
> 
> Go to your app data(if you are on windows press windows key and r) then RenPy folder then Monika after story. Next delete the persistent file that just says "persistent". Then rename a recent persistent (i.e. persistent78.bak) to "persistent".
> 
> That should backtrack your progress/her memory so to her it would seem like a few days passed and she returns to the desk. Nothing else cannot be done as I could tell.

Um, I did that too, but how do you do it?

**Comment by Ovolii** [comment]
I

> I was messing around and some friends told me a Easter egg would pop up if I told her I would take her somewhere and delete her file there was no easter egg and I've re downloaded the game and mod at least 2 times I have them collected and I'm wondering if there is anyway to fix it :>

Can you tell me what you did?
