### ISSUE TITLE
More below 

### ISSUE THREAD

**Issue by MissaOwOx** [Monika-After-Story/MonikaModDev#5846]
I was messing around and some friends told me a Easter egg would pop up if I told her I would take her somewhere and delete her file there was no easter egg and I've re downloaded the game and mod at least 2 times I have them collected and I'm wondering if there is anyway to fix it :>

**Comment by multimokia** [comment]
Monika tells you not to delete the file for a reason. It's quite literally her, so you basically just deleted her.
