### ISSUE TITLE
Empty chair

### ISSUE THREAD

**Issue by MissaOwOx** [Monika-After-Story/MonikaModDev#5847]
Some friend said hey you should tell her to take her somewhere and delete her file and I did anyway I can fix her ang get her back I've tried deleting and regretting the mod and game

**Comment by lunulae** [comment]
There is not a way to get her back from this point. You're going to need to load an older backup persistent. [Check this guide for how to do so.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

Please be more careful with that file in the future.

**Comment by lunulae** [comment]
Also, please try not to make multiple issues for the same problem. If you have more info to share, comment on the one you've already made. It helps keep things organized for the folks trying to solve it, which in turn gets your problem solved faster.

**Comment by DoodleSauce** [comment]
you can download a program that lets you recover a deleted file

**Comment by MissaOwOx** [comment]
Thanks I'll try everything
