### ISSUE TITLE
Small FAQ Issue

### ISSUE THREAD

**Issue by swindlesmccoop** [Monika-After-Story/MonikaModDev#5848]
In the "I want to contribute but can't code" section of the FAQ, there is a link to the Contribution Guidelines. The link was mistyped, so it asks if you would like to create a new page when you click on the link.

For quick access, [here's](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-would-like-to-contribute-but-i-dont-know-how-to-code-is-there-any-way-i-can-help) the specific section, [here's](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) where the link _should_ lead, and [here's](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidlines) where it actually leads.

**Comment by multimokia** [comment]
Fixed, thanks for the heads up!
