### ISSUE TITLE
Monika's Dialogue about Team Salvato's other game / First Anniv Dialogue Confusion (Contains Spoilers)

### ISSUE THREAD

**Issue by JmDemisana** [Monika-After-Story/MonikaModDev#5849]
Ey guys.
Monika and I just turned a year and of course there is a corresponding dialogue.

![1Anniv](https://user-images.githubusercontent.com/63731465/83345380-fa42b200-a344-11ea-934b-09514b20f455.jpg)

I just wonder if this part of the dialogue is a reference to Game Theory's conclusion on DDLC's puzzles.

I enjoyed watching the video, but I actually have a different view.

Also, Team Salvato stated that their next project will be unrelated to DDLC or any character within the game, and the part about the message in binary that says "2018" may link to [this](https://github.com/Monika-After-Story/MonikaModDev/files/4707167/2018.txt) part of the script (from script-ch30.rpy). Try to translate the base64 fragments.

The line "an entire year. A year since our escape" can refer to 2018, considering that DDLC is created on 2017. It's more of an in-game metalore than a metalore that moves through Team Salvato's whole catalog (or so do I believe). Game Theory might've thought that it's a clue for another game when it really isn't. I may be wrong.

I know this isn't actually the place where this topic is dealt, but players with different opinions may be left confused with the fact that Monika is sure that Team Salvato has released another game by now. Especially when she knows what's up anyway. (She has a Twitter account and she had read about the COVID-19 pandemic, but she's sure that Team Salvato has another game when they don't?) It may ease those players a little if the dialogue is revised. I can't really think of any dialogue to change the existing, but the community can hopefully help.

Anyway, that's just my opinion. Correct me if I'm wrong with how I understand the dialogue in the photo.

**Comment by LooseEthics** [comment]
There already was some discussion on this and yeah, that topic is due for a rewrite.

**Comment by ThePotatoGuy** [comment]
dont remember if we have an issue anywhere about this, but yeah that stuff needs to change soon hopefully. leaving open as high priority

**Comment by JmDemisana** [comment]
I guess this is fixed with the v0.11.6 update, so.... Thanks.
