### ISSUE TITLE
Error: I unlocked "monika_change_weather" and now i cant open the game.

### ISSUE THREAD

**Issue by solman252** [Monika-After-Story/MonikaModDev#5850]
So yeah i used the code: $ mas_unlockEVL("monika_change_weather", "EVE")
and now i get this traceback:
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-holidays.rpy", line 177, in script
    init -810 python:
  File "game/script-holidays.rpy", line 195, in <module>
    end_dt=datetime.datetime(2019, 11, 2)
  File "game/zz_history.rpy", line 544, in __init__
    self.setTrigger(trigger)
  File "game/zz_history.rpy", line 727, in setTrigger
    impossible_trigger = _trigger <= first_sesh
TypeError: can't compare datetime.datetime to unicode

**Comment by multimokia** [comment]
I'm not sure *what* you did, but unlocking the weather change label (which, is unlocked by default anyway), wasn't the only thing, since unlocking labels has absolutely nothing to do with the history saver.

You'll need to restore a persistent backup

**Comment by solman252** [comment]
Yeah seems so, if i open an unedited version of MAS it still opens traceback :(

**Comment by solman252** [comment]
Is there some sort of code checker fir mas i could use to find the problem?

**Comment by multimokia** [comment]
Restore a persistent backup. The error is a persistent issue. You cannot fix it via the install alone.
