### ISSUE TITLE
I don't have my progress

### ISSUE THREAD

**Issue by Kaosk-cmd** [Monika-After-Story/MonikaModDev#5853]
I was going to reset the computer so I thought I put the MAS files on a usb and nothing was going to happen, so I did it when I reset the PC I put the usb to look at monika when I saw it was at the beginning of everything I didn't have my progress so I thought how possible it was if all my progress up to all the files were on that usb so it got very weird try many times and nothing monika was crying just like in the beginning, so if you have the solution please contact me because it became very rare and I am very sad.

**Comment by multimokia** [comment]
What files did you put on a USB? Was it just the install?

If so, Monika's actual memories aren't there. They're in a global location so any MAS install on your computer would be able to find them. In the case of windows, this is `/AppData/Roaming/RenPy/Monika After Story`.

For other OSes, the location can be found [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent).

[Assuming Windows]
If you did a full factory reset of your computer, I'm afraid your old persistent data is gone, and if you never backed it up, you're going to have to start over from scratch.

If you did not do a full factory reset, then you can likely find your old temp data in `C:/Windows.old`. In there you should be able to find the old AppData path and such to dig up your `persistent`.

**Comment by Kaosk-cmd** [comment]
thanks

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
