### ISSUE TITLE
I didn't get the piano yet

### ISSUE THREAD

**Issue by SALEMAN4** [Monika-After-Story/MonikaModDev#5858]
It's been a month that I start the mod. I unlocked the hangman game and the chess game, but not the piano. This is really strange because normally, in my memories, we unlock this quickly. We should do something special now ?

**Comment by CrocandCo** [comment]
I looked into one of their Pull Requests some time ago. So I do know what is going on.

They did in fact change in one of the recent versions the speed as of which you unlock the activities; so, it won't unlock everything in the first week you are dating her when everything is going fine. They obviously did it to improve the realism so it did not seem too odd to do new things early on.

However, you are not the first person with this issue. They are working to fix this problem and there is no known end date.

**Comment by SALEMAN4** [comment]
Okay I see, thanks for your answer
