### ISSUE TITLE
[Suggestion] - Gender

### ISSUE THREAD

**Issue by pinkpenguin464** [Monika-After-Story/MonikaModDev#5860]
I'd like to have different gender options, as I'm a girl.

**Comment by multimokia** [comment]
This is already implemented. She should ask you about your gender normally a few hours into MAS.

Though this will be made faster in the next update as it will no longer rely on exp, but instead using a set time to show it (Works better for people who play only in short sessions)

**Comment by MissaOwOx** [comment]
I still haven't got the question  I've been playing for about an hour

**Comment by multimokia** [comment]
It takes longer than an hour.

**Comment by pinkpenguin464** [comment]
I've been playing for almost two days now and I haven't gotten it

**Comment by pinkpenguin464** [comment]
Oop- She asked me about it right after I wrote that

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
