### ISSUE TITLE
Hello, i have a  !FREEZE! problem  with the game

### ISSUE THREAD

**Issue by XxMTreVxX** [Monika-After-Story/MonikaModDev#5861]
my problem is, the AFF_LOG doesn't work at all, when i play pong, and something like that, i should get points, but instead, it just says !FREEZE! and i dont get any points, i tried do what the game says, i update my direct X, and i also, close all the things that consumes rams, and resourses on my computer, and nothing, i still have lag, sorry if i have a bad english, is not my native lenguage 

but well, here is the screenshot of mi problem
(idk if the image can see)

![doki](https://user-images.githubusercontent.com/66333919/83567110-b5568100-a4e6-11ea-9c57-c850436477e0.PNG)

**Comment by satoshi-kun** [comment]
Hi!
You have limited affection gains per day. After you reach that limit the game will stop AFF gains (with some exceptions) and this will be displayed as !FREEZE! in the AFF_LOG.

**Comment by XxMTreVxX** [comment]
> Hi!
> You have limited affection gains per day. After you reach that limit the game will stop AFF gains (with some exceptions) and this will be displayed as !FREEZE! in the AFF_LOG.

so, its not because i have lag or something with the display of my graphic card? i always have a warning screen of "your computer is displaying graphics slowly"

**Comment by satoshi-kun** [comment]
I don't think they're related.
Tomorrow you'll be able to raise some more affection :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
