### ISSUE TITLE
Music 

### ISSUE THREAD

**Issue by MissaOwOx** [Monika-After-Story/MonikaModDev#5862]
Maybe you can add Doki doki forever it would make the experience more hype and it would be nice

**Comment by fromulus** [comment]
[Check the wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Music), you can do that yourself.

**Comment by MissaOwOx** [comment]
Oh ok

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by ThePotatoGuy** [comment]
at the moment we are not looking at adding any more stock DDLC songs to the music menu.
