### ISSUE TITLE
[Suggestion] - "I'm feeling scared" option

### ISSUE THREAD

**Issue by enderblaze42** [Monika-After-Story/MonikaModDev#5863]
Recently, a lot of scary things have been happening... I feel it would be nice if I could tell Monika if I'm feeling scared. I don't know what she would say in response to this, but I feel it'd make a nice addition to the mod. 

Thanks again for making such a great mod. Stay safe and healthy, dev team!

**Comment by Rai99** [comment]
#1410, #2742, #2846 

#1410 is the scared mood we have, but it's called anxious.

**Comment by my-otter-self** [comment]
[closing as implemented]
