### ISSUE TITLE
Is it possible to give gifts to Monika on android?

### ISSUE THREAD

**Issue by leWallaper** [Monika-After-Story/MonikaModDev#5866]

**Comment by kirillPro2020** [comment]
As far as I know, there is no official MAS port on android.

**Comment by leWallaper** [comment]
> As far as I know, there is no official MAS port on android.

I downloaded DDLC on android, and then just downloaded the mod from VK. It worked. So idk, there should probabky be.

**Comment by kirillPro2020** [comment]
What language mod?

**Comment by multimokia** [comment]
The Android version of MAS was not released by us and is not supported by us.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
