### ISSUE TITLE
Sing me a Song suggestion: The Glory of love

### ISSUE THREAD

**Issue by dramones09** [Monika-After-Story/MonikaModDev#5867]
Lyrics:

You've got to give a little
Take a little
And let your poor heart
Break a little
That's the story of
That's the glory of love...

You've got to laugh a little
Cry a little
Until the clouds
Roll by a little
That's the story of
That's the glory of love...

As long as there's the two of us
We've got the world and all it's charms
And when the world is through with us
We've got each other's arms

You've got to win a little
Lose a little
Yes and always
Have the blues a little
That's the story of
That's the glory of love...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
