### ISSUE TITLE
[Suggestion] - New Apologies

### ISSUE THREAD

**Issue by mhumanworldm** [Monika-After-Story/MonikaModDev#5868]
How about new apoligies. For example, you lied about something and you feel bad, and now you want to apologize. Btw thats me...

**Comment by kirillPro2020** [comment]
It seems that this is already in fashion.

**Comment by CrocandCo** [comment]
If it's one of the topics that you discussed with her then it's reasonable. If it is about something else then that is not really a good improvement. Maybe options that you can choose as a sub-menu? In any case I think it's too general.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
