### ISSUE TITLE
[Suggestion] A toast to fun facts! (Fun fact about why toasting is called toasting)

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5869]
~~Please correct me if I'm wrong about this fun fact.~~
Iirc, the term toasting came from people putting a piece of spiced toast in their drinks (most commonly in wine).

**Comment by kirillPro2020** [comment]
Too many options for origin.
For example: in the early Middle Ages, when the heyday of chivalry occurred, especially in France. So, in the 7th century, the French king Charles I began to invite knights to his feasts. All the warriors who were at the same table pushed their goblets to the center of the table. And then they sharply shifted and knocked cups against each other. Such a ritual symbolized the strength and unity of the knightly fraternity. In addition, in this way glorious warriors showed trust in each other.
(If I understand you correctly).

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
