### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by LoneKorok** [Monika-After-Story/MonikaModDev#5871]
Everytime I try to open the game I get this error and I have no idea what it means.
ScriptError: Name (u'/home/tom/ab/renpy/renpy/common/000atl.rpy', 1480466919, 25) is defined twice, at lib/windows-i686/000atl.rpyc:25 and lib/windows-i686/Monika After Story/DDLC-1.1.1-pc/renpy/common/000atl.rpyc:25.

**Comment by multimokia** [comment]
Seems you might've copied the contents of one of the internal renpy folders somewhere else by mistake. You're probably best off just making a new DDLC + MAS install.

Your progress won't be lost in doing so.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
