### ISSUE TITLE
Suggestion. Tic-Tac-Toe game

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#5872]
I can implement this game.
(But which Python?).

**Comment by kirillPro2020** [comment]
Ok

**Comment by kirillPro2020** [comment]
Let's say. I made it, but it's a simple game, not a mod
(I don’t know how to import and configure it for the mod).

**Comment by xXMidnight** [comment]
Techncially if you were very skilled at tic tac toe there would be a draw everytime. It's like pitting two tic tac toe computers together that are like super good and they keep drawing. Unless you put a 5x5 ( ͡° ͜ʖ ͡°)
