### ISSUE TITLE
Changing Player Name Dialogue Needs Cancel Option

### ISSUE THREAD

**Issue by Dank-Elf-Boy** [Monika-After-Story/MonikaModDev#5876]
When you select the name change option for the player, the system doesn't contain a cancel option. Could you add a nevermind option to changing the player's name for those who decide to keep their current name? Thanks.

**Comment by multimokia** [comment]
You can type "nevermind" and that cancels it

**Comment by ThePotatoGuy** [comment]
I'll agree it's not the most intuitive way to cancel, but it works unless you intend to be called `nevermind`.

**Comment by Dank-Elf-Boy** [comment]
Ah, okay. My bad I glossed over the beginning dialogue thinking there would be a menu option ahead. I'll go ahead and close.
