### ISSUE TITLE
Having problems when trying to restore my progress

### ISSUE THREAD

**Issue by ErnestoLaguna** [Monika-After-Story/MonikaModDev#5878]
Hello there, I'm trying to recover my progress on MAS, but I think I might be doing something wrong. My first attemp was just putting the persistent to the new folder cerated in the Renpy folder, but it looked like I was playing the game from the very beginning. My next attempt was putting all the data of MAS in that folder but only this happened:  
![screenshot0001](https://user-images.githubusercontent.com/48169688/83933549-29a35580-a76f-11ea-80b0-c555ef50c477.png)
I hope you can help me with this little problem

**Comment by multimokia** [comment]
Looks like a persistent from having taken her out of the room. Do you have any persistent backups?

**Comment by ErnestoLaguna** [comment]
Yes, I have one from February of last year, the one I put was from November of the same year

**Comment by ThePotatoGuy** [comment]
since some time has passed, I'm going to assume this was resolved. make a new issue if there is still a problem.
