### ISSUE TITLE
I keep getting the sound notification for window reacts, but I go into MAS and see nothing.

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5879]
I even got a sound notification as I was writing this issue. I alt+tabbed back into MAS, and she's just sitting there. No facial expressions, no text, no nothing. I've been playing it for two days if that helps, and I'm using the website version, not steam.

**Comment by ManuEcheveste** [comment]
Maybe you get the windows react notifications, for example when you use YouTube, it sends you a notifications saying "Watching something interesting" or something like that, but only the notif, no topic in game at all
