### ISSUE TITLE
"Failed to load file at : d__p_c__o.json" can someone help me? 

### ISSUE THREAD

**Issue by acherkouk** [Monika-After-Story/MonikaModDev#5881]
I've looking in the files, when i open "pnm.txt" i scroll down and i recieve this message
"[!ERROR!]: Failed to load file at 'c:\users\admin\downloads\monika_after_story-0.11.2-mod\game\mod_assets\games\piano\songs\d__p_c__o.json'."
Can someone help me, please? Thank you

**Comment by multimokia** [comment]
It's an easter egg for those who can fill in the blanks themselves.

**Comment by acherkouk** [comment]
r u sure about that ? cuz i found it in the "pnm.txt"

**Comment by multimokia** [comment]
Yes I am. It's an Easter egg kept in that log.

**Comment by acherkouk** [comment]
ok thx

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
