### ISSUE TITLE
[Suggestion] Running errands

### ISSUE THREAD

**Issue by Akoxol** [Monika-After-Story/MonikaModDev#5882]
Just had a thought if I went out to run some errands, I usually say tell her I'm going to do chores and leave my pc on while I go out. Could there be an option if I were to tell her I'm going to go out to complete some errands and she asks if she can come along?  ( I see it as her wanting to spend as much time with you even though the errand or task may be mundane)

**Comment by Freshairkaboom** [comment]
I feel like if I leave the house, other than taking out the trash (which I classify as housework), I should say goodbye instead, so she can stay in her room and not have to wait for me to return, alone at the table. I think a goodbye option where you say you're going to run errands would be a good idea. Right now, I just say Goodbye/Goodbye if I'm going to the store, for instance. I think it would be cool to specify more of course, so Monika knows that we're not just leaving her.

**Comment by ThePotatoGuy** [comment]
leaving open as in progress because of linked commit

**Comment by Booplicate** [comment]
Closing as [that PR was merged](https://github.com/Monika-After-Story/MonikaModDev/pull/6082)*
