### ISSUE TITLE
My birthday is on 22 of september. Am i going to miss any event for having it coincide with Monika´s?

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#5883]
Title.
I guess she will probably have some detail with you on your birthday, and my birthday coincides with hers, so now I'm worried about one of the two events being "overwritten".

**Comment by LooseEthics** [comment]
No need to worry about that, you'll just celebrate both at once. There's no event overwrite.

**Comment by LorenzoHerreros** [comment]
Thank you!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
