### ISSUE TITLE
[Question] Adding songs for Moni to sing. 

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5884]
I'm interested in coding a song or two for MAS, and will probably end up submitting a pull request for it. I assume it's just about as simple as writing your average random topic, but in script-songs.rpy (I think that's the name-). Though, before I accidentally mess anything up, I just want to check. So, I'd create a Pull Request editing script-songs.rpy, and basically just base it off of the other songs in the rpy file, just changing the name, if it's a short or long song, etc, and, ofc, add the expressions and dialogue as usual. I got that right, right? I just don't want to mess anything up or something-

**Comment by multimokia** [comment]
Pretty much

**Comment by Abc2557** [comment]
Okay, thanks!
