### ISSUE TITLE
Every time I'm opening MAS this appears

### ISSUE THREAD

**Issue by ThatMorgan** [Monika-After-Story/MonikaModDev#5892]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1056, in script call
  File "game/script-ch30.rpy", line 1934, in script
  File "game/script-ch30.rpy", line 1934, in <module>
  File "game/event-rules.rpy", line 880, in check_persistent_rules
  File "game/event-rules.rpy", line 839, in evaluate_rule
AttributeError: 'NoneType' object has no attribute 'eventlabel'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1056, in script call
  File "game/script-ch30.rpy", line 1934, in script
  File "E:\DDLC\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\DDLC\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 1934, in <module>
  File "game/event-rules.rpy", line 880, in check_persistent_rules
  File "game/event-rules.rpy", line 839, in evaluate_rule
AttributeError: 'NoneType' object has no attribute 'eventlabel'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.2

**Comment by multimokia** [comment]
Can you send your persistent, please? (You'll need to put it in a zip file to send it here)

**Comment by ThatMorgan** [comment]
I wasn't sure which persistent I had to sent. So I placed all the persistents I could find.
[persistens.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4754907/persistens.zip)

**Comment by multimokia** [comment]
Looks like you made some changes to game files in your main install. I'm seeing some extra eventlabels in your undo action rules dict.

What are you trying to do there?

Additionally, to fix this, you'll need to restore a persistent backup from before you made the changes.

**Comment by ThatMorgan** [comment]
I don't remember changing any game files unless downloading sub mods. Only what I do remember, is that I got this exception after downloading new version of MAS. I tried to reinstall game and mod but it wasn't unsuccessful.

**Comment by multimokia** [comment]
Yeah it's a persistent issue. What submods did you install?

**Comment by ThatMorgan** [comment]
I remember installing MAS-Additions.

**Comment by multimokia** [comment]
Don't use it. It's severely outdated and is known to cause issues with current MAS.

Restore a persistent backup from before you installed the submod

**Comment by ThatMorgan** [comment]
Excuse me, but how do I do it? Is there any guide to do so?

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
