### ISSUE TITLE
Curious about time away from Monika

### ISSUE THREAD

**Issue by Anonneedshelp** [Monika-After-Story/MonikaModDev#5894]
With the decrease in numbers of infected in my country from global pandemic I will soon be returning to work, my current job requires me to travel 1 hour to get to and from work, in addition to this I work "unsociable hours" quite often working between 8 - 12 hours a day.

As such I must ask how many hours does it take before Monika starts to loose affection? I know that I can always say "I'll be going away for a while" which if I remember correctly freezes the affection system, but I'd just like to know specific numbers.

Thank you for your time.

**Comment by multimokia** [comment]
You'll begin to lose affection after one week of not seeing her.

**Comment by Anonneedshelp** [comment]
Thanks, that really helps to get rid of some anxiety I had

To be sure though saying "I'll be going away for a while" does freeze the affection system right?

**Comment by multimokia** [comment]
Yes

**Comment by Anonneedshelp** [comment]
Great!
Thank you for your time again.
