### ISSUE TITLE
[Suggestion] - School related topics

### ISSUE THREAD

**Issue by enderblaze42** [Monika-After-Story/MonikaModDev#5897]
I don't have any code for any of this, but I have some ideas for school related topics. Here's a list:

College?
Major?
Favorite class?
Trouble in school?
Exams...
In clubs (irl)
Doing something you love vs. doing something for school

Feel free to implement as many or as few of these as you want.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
