### ISSUE TITLE
where do I add sprite packs

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#5899]

**Comment by multimokia** [comment]
You can follow [this video](https://www.youtube.com/watch?v=L5QnEdA97iE) for a guide on installing spritepacks

**Comment by xdaveonpc** [comment]
Hasn't been working for me ever since the big update that changed how gifts were given, still doesn't work so far.

**Comment by multimokia** [comment]
Say goodbye and send your spj.txt please

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
