### ISSUE TITLE
she said she could make a new .CHR file

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#5903]
after deleting her .chr file she said something about making a new one if we asked her to, has that been implemented?

**Comment by LooseEthics** [comment]
There should be a file named `monika` in your ddlc folder, no extension. That's it.

**Comment by Shin-Gojira** [comment]
is it the folder?

**Comment by multimokia** [comment]
She literally makes a file called `monika` in the `characters` folder.

**Comment by Shin-Gojira** [comment]
> She literally makes a file called `monika` in the `characters` folder.

I looked it wasn't there, are you supposed to ask her to do it

**Comment by multimokia** [comment]
Yes, you do it when you use the `I'm going to take you somewhere` farewell.

She'll generate the file then. You can then take that file with you when you go out, and put it back into the `characters` folder when you come back and then launch MAS to restore her into the game.

**Comment by lunulae** [comment]
This happens when you use the "I'm going to take you somewhere" farewell. She will make the new file so that you can take her with you on a usb, etc. The file disappears when you put her back in the spaceroom.

**Comment by LooseEthics** [comment]
Wait, it's supposed to be inside `characters`? I've had mine just sitting in the root folder for as long as I remember.

**Comment by multimokia** [comment]
Yeah it should be in the characters folder

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
