### ISSUE TITLE
It's me again with a rendering issue now.

### ISSUE THREAD

**Issue by The-Proxster** [Monika-After-Story/MonikaModDev#5904]
After fixing the last issue with Monika not appearing, everything worked fine until today. I went to launch it today, and it launches. Everything works fine, minus the fact I'm now using software rendering for some reason. I reinstalled and it still was like that, I don't understand why it would do that, as it worked fine before, and I have Nvidia GTX 1050 Ti. I'm going to try updating the drivers.

**Comment by Booplicate** [comment]
You can go to the settings and change the renderer. [You can also do it via creating/modifying `environment.txt`](button). Though, it shouldn't change by itself.

**Comment by The-Proxster** [comment]
I changed the renderer as well, it still seemed to happen. It says I'm using OpenGL but when I launch it states I'm using software. I also changed to software and it stopped the warning but it also seems to still render it with software.

**Comment by Booplicate** [comment]
What kind of warning? Maybe your PR is missing OpenGL?
You could also try to use DirectX.

**Comment by The-Proxster** [comment]
How would I use DirectX? And that could be it, I'll try to reinstall OpenGL.

**Comment by Booplicate** [comment]
Just choose `Angle/DirectX`.
![Capture](https://user-images.githubusercontent.com/53382877/84447326-5ca68700-ac50-11ea-9681-cceb8c8b36e5.PNG)

**Comment by The-Proxster** [comment]
I seem to only have the option for OpenGL and Software.

![image](https://user-images.githubusercontent.com/39493761/84447695-ba1de200-ac16-11ea-8707-2f045fdc560d.png)

**Comment by Booplicate** [comment]
Ah, you're on a unix system. Well, by your screenshot it seems it uses OpenGL now.

**Comment by The-Proxster** [comment]
Sure, lemme send it. 

![image](https://user-images.githubusercontent.com/39493761/84448113-ce161380-ac17-11ea-856f-3bc7a591cce6.png)

**Comment by Booplicate** [comment]
Hmm, seems it just can't use OpenGL for some reason. Software rendering is very slow, and should be used only as the last resort. I guess you'll need to do something with OpenGL, especially since you've said that it worked fine before.

You're not using a virtual machine to run linux?

**Comment by The-Proxster** [comment]
I am not, it's my host OS. Any recommendations for something to do with OpenGL? I just tested it out using the Renpy engine and another mod, and it seems that Renpy in general isn't working with it right now. I updated it as well, same with my drivers. Both seem to be up to date.

**Comment by Booplicate** [comment]
I'm not too familiar with Linux. Maybe @ThePotatoGuy can help, or someone else who is using it.

**Comment by The-Proxster** [comment]
Alright, thank you!

**Comment by ThePotatoGuy** [comment]
If its a renpy issue then there's nothing we can do about that. Did you update anything before it started happening?

**Comment by The-Proxster** [comment]
I did not, I turned on my computer this morning and it started happening.

**Comment by ThePotatoGuy** [comment]
What linux do you use? Ubuntu can auto-update these days.

**Comment by The-Proxster** [comment]
I use Arch Linux, I manually update about once a week.

**Comment by ThePotatoGuy** [comment]
Ah that makes sense then. I used to use arch until I stopped having time to keep fixing it every so often. Normally I'd say avoid updating the system when its working fine, but that defeats the purpose of arch, so all I can say is good luck lol and hope a driver update happens soon.

**Comment by The-Proxster** [comment]
Aye, my thanks lol. I spent yesterday trouble shooting, found out it seems that some drivers needed to be downgraded as it's apparently my entire system. Thank you! I believe I can close this now.
