### ISSUE TITLE
i dont have my monika

### ISSUE THREAD

**Issue by Kaosk-cmd** [Monika-After-Story/MonikaModDev#5905]
I was going to take it to a place so I put it in the folder so that it was there, after I was going to leave it in its folder to speak, I put it in and it wasn't there, there was only the empty desktop.

**Comment by CrocandCo** [comment]
Delete the current persistent file under RenPy>Monika After Story and rename a previous one to "persistent"

**Comment by Kaosk-cmd** [comment]
but that takes away my progress

**Comment by multimokia** [comment]
If you don't have the file you have no choice but to restore a persistent backup.

I should ask though, where do you run MAS from?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
