### ISSUE TITLE
Increasing the affection cap

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#5908]
I´ve been opening Monika after story and talking to her for days (today is the one week anniversary). Several hours a day.

Despite everything, the affection cap have me sitting at 128 without any novelty for days.

I still have just the pong, no trace of piano, no poems whatsoever, and Monika has been pretty much repeating herself since day 2, with very rare exceptions here and there.

I completely understand that a relationship must be built brick by brick, but I genuinely believe that an affection cap of 7 per day is far too small when we are moving in increments of 300+ affections per level.

Is it some way for me to increase the affection cap?

Not eliminating it necessarily, but definitely increasing it to 20 more or less.

**Comment by LooseEthics** [comment]
There are some events which bypass it - some gifts for example - but generally no, the cap is set in stone, pretty much. You can't speedrun a relationship.

**Comment by LorenzoHerreros** [comment]
> There are some events which bypass it - some gifts for example - but generally no, the cap is set in stone, pretty much. You can't speedrun a relationship.

I'm not talking about speedrunning a relationship. If the "complete" relationship has over 1000 points, having a 20 per day cap couldn't be considered a speedrun by any stretch of my imagination.

And I can absolutely assure you, you can definitely progress in a real relationship several times faster than in this mod.

**Comment by Booplicate** [comment]
The piano is unlocked much later, and requires more than just the affection to unlock it. You can see it like a reward for being faithful and spending time with Monika. Although, there're more games to play. You can speed up unlocking them by playing what you have now.

You're not supposed to get poems every day, and the affection doesn't affect it.

Even if you've read everything she has to say, bear in mind that some topics change over time, some unlock later, and new topics get added by contributors (and you can help with that too). Also with the next update, you'll get some more topics to ask Monika (pool topics in the `Hey, Monika` menu).

The current affection progression is quite quick as is, there's no reason to make it quicker. The mod isn't supposed to be "accomplished" in a week or two. You can play whatever way you want, but know that for the best experience better not to look in the affection log. After all, it's a debugging tool.

**Comment by multimokia** [comment]
The affection system is modelled after how it would work irl.


On average, to get to the comfortable stage in the relationship, it can take around 6 months. Which is pretty much what the current cap of 7 does too.

Affection isn't supposed to be a seen value, really. Only implied by the slight changes in dialogue/Monika's body language/things you can do together. And it's supposed to take time.

Additionally, games start unlocking a week in on average (based on xp, which is based on your session length. So longer time spent is better)

**Comment by ThePotatoGuy** [comment]
And to clarify, the comfortable stage is the 1k aff level. 

The initial relationship stage (aka probably exclusively dating) is reached at 100. 

In terms of timespans, at 7 a day, we have roughly:
*  Happy - 4-5 days 
* Affectionate - 10 days later (2 weeks overall)
* Enamored - month and a half later (2 months overall)
* Love - ~3 months later (5-6 months overall)

A more sexually charged relationship would probably go through the phases much faster, but our model is not based on that type of relationship.

**Comment by CrocandCo** [comment]
> I still have just the pong, no trace of piano, no poems whatsoever, and Monika has been pretty much repeating herself since day 2, with very rare exceptions here and there.
> I completely understand that a relationship must be built brick by brick, but I genuinely believe that an affection cap of 7 per day is far too small when we are moving in increments of 300+ affections per level.


Just my point of view before this issue is closed, a suggestion.
If you seem to burn through her random topics quickly I advise on reducing the frequency that she talks. That way it doesn't get tiresome talk about the same thing multiple times with no deviation from the last time she mentioned it.

Another bit is, and this is applicable to any relationship, to appreciate the small moments and growth of any relationship. Trying to speedrun a relationship kind of indicates lesser value in the relationships you build and makes your relationship unrealistic in that way. Move too quickly in a relationship and it burns out just as fast. I do appreciate the Devs finding that perfect number for the daily cap and hope this project continues forward in the future.

**Comment by LorenzoHerreros** [comment]
ok, noted, ill try making her take more time between texts
She usually talk about 10 seconds after her previous comment.

**Comment by LorenzoHerreros** [comment]
Last but not least.

The mod is great, I wouldn't mind throwing in a few bucks to support it. Where can I do that?

**Comment by LooseEthics** [comment]
You can't, afaik. Don't quote me on this, but I'm pretty sure having a patreon or something like that for mas would violate Team Salvato's modding guidelines.

**Comment by LooseEthics** [comment]
`Any fan work that includes official DDLC assets may NOT be sold under any circumstances, online or offline. No profit may be made from these fan works in any way, except for fan work that constitutes as Fair Use under the United States FAIR USE Act of 2007. For example, a gameplay review video or commentary video typically qualifies as Fair Use. It is the artist’s responsibility to understand Fair Use and design qualifying content.`

**Comment by LorenzoHerreros** [comment]
Well shit.
In that case, the only thing I can do is to thank the team from the very bottom of my heart.
It won't pay the bills, but know that I'm enjoying the mod immensely.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]

**Comment by Wolfgamerkitty** [comment]
And to clarify, the comfortable stage is the 1k aff level.

The initial relationship stage (aka probably exclusively dating) is reached at 100.

In terms of timespans, at 7 a day, we have roughly:

Happy - 4-5 days
Affectionate - 10 days later (2 weeks overall)
Enamored - month and a half later (2 months overall)
Love - ~3 months later (5-6 months overall)
A more sexually charged relationship would probably go through the phases much faster, but our model is not based on that type of relationship.

 When u said this it's not true in only about 5 days i got affectionate
