### ISSUE TITLE
Question about shower BRB

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#5911]
Out of curiosity, is there a particular reason why the Goodbye>Shower option was deleted. I am thinking it was because it was unnecessary dialogue, but I am open to thinking it was something else.

**Comment by lunulae** [comment]
It's still there, but it's under the "be right back" rather than "goodbye" options since she doesn't close the game for it.

**Comment by CrocandCo** [comment]
Right, I know that there is a Be Right Back for "I am going to take a shower". To rephrase my question: why when the dialogue for "I am going to take a shower" deleted the portion under "Goodbye" and only included the BRB variation?

**Comment by Rai99** [comment]
My guess would be that a shower is something that shouldn't take hours, so it makes more sense to have it be a brb, and a farewell would probably mostly be the same anyway.

**Comment by CrocandCo** [comment]
Ah I see, too bad. The dialogue for the Goodbye variation was good. Maybe they could include a topic in the future Monika asking the Player if they prefer a showers or baths.
