### ISSUE TITLE
I'm sorry, but an uncaught exception occurred. (MAS)

### ISSUE THREAD

**Issue by miluxo** [Monika-After-Story/MonikaModDev#5914]
Hello, I recently installed a new version of Monika After Story but at the end I got an error and the game closed, when I opened it again, this message appeared.

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chess.rpy", line 394, in script
  File "game/chess.rpy", line 456, in <module>
NameError: name 'mas_games' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\luisg\OneDrive\Escritorio\ddlce\DDLC-1.1.1-pc - just monika\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\luisg\OneDrive\Escritorio\ddlce\DDLC-1.1.1-pc - just monika\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/chess.rpy", line 394, in script
  File "C:\Users\luisg\OneDrive\Escritorio\ddlce\DDLC-1.1.1-pc - just monika\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\luisg\OneDrive\Escritorio\ddlce\DDLC-1.1.1-pc - just monika\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 456, in <module>
NameError: name 'mas_games' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

Could someone help me solve it please :c.

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please

**Comment by miluxo** [comment]
![1](https://user-images.githubusercontent.com/66882421/84575911-8659ce00-ad76-11ea-815d-62c8e25aaa03.png)
![2](https://user-images.githubusercontent.com/66882421/84575916-8a85eb80-ad76-11ea-919c-b225fd821e7c.png)
![3](https://user-images.githubusercontent.com/66882421/84575917-8bb71880-ad76-11ea-875f-a4d5da1664ad.png)
![4](https://user-images.githubusercontent.com/66882421/84575921-8e197280-ad76-11ea-8b87-f0d17880bae9.png)
![5](https://user-images.githubusercontent.com/66882421/84575924-8fe33600-ad76-11ea-86b3-4326f475098c.png)
![6](https://user-images.githubusercontent.com/66882421/84575925-91146300-ad76-11ea-85aa-14ac8dc0eeec.png)
![7](https://user-images.githubusercontent.com/66882421/84575928-94a7ea00-ad76-11ea-94f1-36861c3cec67.png)

**Comment by multimokia** [comment]
Ah okay. So you'll likely want to update manually. You can get the mod zip from here: http://monikaafterstory.com/releases.html
Simply extract it to your `/game` folder and you should be good.

But I'd delete all `.new` files as well before extracting the zip into the `/game` folder just to be safe

**Comment by miluxo** [comment]
Ok, try when the download is finished, thanks :)

**Comment by multimokia** [comment]
no problem

**Comment by miluxo** [comment]
It worked, really thank you very much: ')

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
