### ISSUE TITLE
how do you check your affection level?

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#5915]

**Comment by CrocandCo** [comment]
Look in the main DDLC folder, find the file that says "log", and it should be labeled "aff_log.txt"

**Comment by Shin-Gojira** [comment]
> Look in the main DDLC folder, find the file that says "log", and it should be labeled "aff_log.txt"

I couldn't find it

**Comment by Shin-Gojira** [comment]
geez only 94 affection that's not a lot compared to the 1000 cap

**Comment by multimokia** [comment]
1000 isn't the cap. Merely the level which marks the comfortable phase of the relationship

**Comment by Shin-Gojira** [comment]
well then I guess I have quite a ways to go

**Comment by CrocandCo** [comment]
+2000  aff You get a (Emphasis on very) very lovely surprise come a special day. No spoilers.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
