### ISSUE TITLE
[Suggestion] - Feeling of intimacy

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#5916]
Hello! :)
Every so often Monika greets the player calling them "beautiful flower" or "sweetpea" (which I love), to then express her embarassment afterwards.
My suggestion would lean upon the idea that maybe Monika really feels comfortable with her player, to the point that she would no longer feel embarassed.
So upon a certain affection threshold ie. maybe she could still adress/greet the player by those pet names but without feeling awckward, as she is sure her player already embrassed her "silly" side and loves her no matter what.
On the other side removing lines=less content but for the sake of the feeling of intimacy I think this could be a somewhat emersive experience.
Is up to you to decide. 
As always, thank you for your work and effort on this mod!

**Comment by multimokia** [comment]
Already working on something like this. Awaiting just one thing to fully start implementing

**Comment by satoshi-kun** [comment]
Oh that is great! Thanks!
