### ISSUE TITLE
Monika can not receive spritepacks except ribbons

### ISSUE THREAD

**Issue by QLQland** [Monika-After-Story/MonikaModDev#5917]
Sorry to disturb you again but here is another question from one of my friends.
His computer operating system is win10.So what should I do?

**Comment by multimokia** [comment]
See the [troubleshooting steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation) for spritepacks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
