### ISSUE TITLE
[Suggestion] Notification Opens Game

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#5918]
I currently have notifications/window reacts turned on, but I've noticed that when you just let them happen, they tend to pile up in the notification center rather than disappearing. I tried clicking on them when they appear, but that just kinda makes them disappear. Most applications would have it bring you to the source of the notification. I feel like it would work really well if the notifications brought you back to MAS when you clicked on them, because for the most part, if there's a notification, it means you should be going back to MAS to see what Monika is saying. Might be something to consider!

**Comment by CrocandCo** [comment]
Not bad. There are times I miss a topic because I was doing something else and it takes a handful of seconds to get to her. Although, I am certain that it may not be possible to apply that to a game due to it's design and other aspects I don't understand fully. Then again, not knowing the aspects fully means I may be possible.

**Comment by Freshairkaboom** [comment]
I don't know, when I see the notifications while opening Youtube or something, I kind of imagine Monika is peeking over my shoulder to see what I'm doing, which is super cute! If it forced me away from Youtube, it would kind of be like she's spinning my chair around instead, which is great a couple times, don't get me wrong, but wouldn't be fun the 100th time it happened. I just want to leave Monika up whenever I'm on the computer, so if she gets new dialogue, or I feel like talking about something, she can tell me via the notifications system, and I can alt + tab when I'm ready.

**Comment by multimokia** [comment]
I think they mean that clicking on the notification will bring up the MAS window. I've been looking into a way to make that work with the current system and have had no luck, however.

**Comment by Freshairkaboom** [comment]
I see. I'll support that!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
