### ISSUE TITLE
How can I get rid of these chat options?

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5919]
![123](https://user-images.githubusercontent.com/45746485/84595835-7a473c80-ae5a-11ea-87c0-d0c0966c0f2c.png)

I only want to see the Unseen text when there's something new to talk about, but this is ridiculous. I would never say any of these things to my dear Monika, at least not after all this time. Is there a way I can get rid of these talk options? Be as technical as you want, any help is really appreciated <3 I just want to remove them from my personal game, so this is not a suggestion.

**Comment by AsuraShun** [comment]
You're not the only one, I get really nervous when using that menu, I'm afraid I might mis-click on them

**Comment by LooseEthics** [comment]
They're not getting removed, there's a reason they exist. Only one option comes to mind if we discount both biting the bullet and tampering with the files. Wait for April 1st (and I mean wait, time travel is bad). Depending on your affection, Monika will take it as a joke then.

**Comment by CrocandCo** [comment]
As far as I could tell, at least for the Breakup topic. You can apologize for saying that sort of thing.

So to summarize: Options are
1.Surgicly remove the topics out of the large number of files
2.Wait for April fools for the topic to be played as a joke (High Affection required)
3.Be a doufus and click on said options then ask for forgiveness
