### ISSUE TITLE
I feel like how fast affection is gained is too slow

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#5922]
so since the max cap for affection you can gain is 7 per day that means that it takes 143 days or roughly 5 months to reach the "comfortable" phase which seems kinda long when you think about it so i think it should be doubled

**Comment by Rai99** [comment]
You're absolutely right. It is pretty slow, just like how it usually is in real life, and that's what we aim to model. It's not supposed to be fast. 

MAS isn't something you're supposed to be able to rush through and be done with in a couple weeks or months. The idea is that you're supposed to slowly work your way up, and earn what rewards you get from higher affection. 

If you're really in a rush to get up there, I think you might be disappointed when it actually happens.

**Comment by Shin-Gojira** [comment]
> You're absolutely right. It is pretty slow, just like how it usually is in real life, and that's what we aim to model. It's not supposed to be fast.
> 
> MAS isn't something you're supposed to be able to rush through and be done with in a couple weeks or months. The idea is that you're supposed to slowly work your way up, and earn what rewards you get from higher affection.
> 
> If you're really in a rush to get up there, I think you might be disappointed when it actually happens.

fair enough

**Comment by Shin-Gojira** [comment]
> You're absolutely right. It is pretty slow, just like how it usually is in real life, and that's what we aim to model. It's not supposed to be fast.
> 
> MAS isn't something you're supposed to be able to rush through and be done with in a couple weeks or months. The idea is that you're supposed to slowly work your way up, and earn what rewards you get from higher affection.
> 
> If you're really in a rush to get up there, I think you might be disappointed when it actually happens.

fair enough, but still some might want the option

**Comment by multimokia** [comment]
Not really an option we intend to provide honestly. It's not about your pace here. There's a pace also Monika should be getting into the relationship.

Additionally, I linked to #5908 on your other issue specifically because it addresses the content of this very issue and ergo, the results of it.

**Comment by CrocandCo** [comment]
There is/was a discussion on a casual mode #4851 and it was a thorough one. I can see why the casual mode would be cast aside in the project. Personally to sum it up, it makes the surprises less meaningful and the "relationship" a joke.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
