### ISSUE TITLE
battleship suggestion

### ISSUE THREAD

**Issue by mastergamer117** [Monika-After-Story/MonikaModDev#5923]
i posted a suggestion on r/MASfandom and got a pretty good response and they suggested i put it here, i was thinking, what if we could play battleship with monika?

**Comment by Freshairkaboom** [comment]
If you post "Battleship" in the title, it will be easier for people to find your issue probably. I like it. More things to do with Monika is always good! ^_^

**Comment by Rai99** [comment]
Battleship: #1081, #2759, #3480, #5415

**Comment by mastergamer117** [comment]
sorry about that, hope somebody figures it out soon

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
