### ISSUE TITLE
7am and the game is in night mode?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5924]
Monika even responds as if it's night time.

I've set "sunrise" to 7am, so what do I do..

**Comment by lunulae** [comment]
Couple questions so I can understand your problem better:
Is this problem persisting even when you say goodbye and reload the game?
Did you change your sunrise/sunset times on this session or earlier?
The shift from day/night can sometimes take a couple extra minutes in my experience, and can't change mid-topic (iirc) but if it's failing to change after an extended period of time this might need investigation.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
