### ISSUE TITLE
[Suggestion(s)] Spotify Connection/Music Reactions

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#5926]
Monika has mentioned in the past that she likes different kinds of music and would love it if we played it, but the issue is that she can't tell what we're listening to unless it's in-game. While thinking about this, I recently realized that when I listen to something on Spotify, Discord displays it on my profile. You have to specifically enable it in the settings, but Discord does detect what Spotify is playing and displays it for your friends to see, if you let it. So this got me thinking: What if we added this to MAS?

Monika would, in theory, be able to detect what song is playing, and give unique dialogue for certain songs. Obviously, it wouldn't be for every single song on the planet, but perhaps it could be similar to the window reacts, in that there's a handful and people can add more later. I know that currently, not a lot of window reacts get added because of how difficult it can be for Monika to register certain pages, but I feel like song titles would be a lot less subjective, making them easier to add.

An alternative to this, if connecting Spotify is impossible for some reason(be it legal or technical limitations), would be to change how the in-game music player works. Rather than just dropping in a track to a file and then it plays, maybe there could be a way to at least categorize certain songs, at least by genre. Then Monika could at least appreciate when we put on the music types she mentions wanting to hear!

I don't know if any of this would be possible, I just think it'd be neat if Monika could react to the music being played.

**Comment by Abc2557** [comment]
I’m not sure about the Spotify part, but I really like the Genre idea! I’d assume the player would be the one to put the songs into their respective genres. Maybe the player could make folders within the custom bgm folder, and whatever the folder’s name is would be the genre’s name? Just thinking out loud here. Anyway, I hope that something similar to your suggestion could be added in-game, or at least as a submod

**Comment by SamanthaLind** [comment]
I would love so happy if it's get added. Especially to see Monica reactions. Also it would be nice to consider marking what songs are about. Nothing special, but I think it would be sweet if we get to see her reactions for playing love songs. Honestly I play almost only love songs for Moni and it would be amazing if she knew about it.

**Comment by Rai99** [comment]
Having players add music reactions to the mod sounds like it'll end up like the movies module, where people can add reactions to watching things together. It's empty, and nobody ever adds content to it. 

Having it be per-player to make their own folders with genres would probably need pre-programmed dialogue per genre, and there are a good number of genres out there, not to mention the potential for mismatching genres in the wrong folder, and having Monika say some thing about music that she probably shouldn't.

**Comment by ThePotatoGuy** [comment]
yeah there's just so much variety when it comes to reacting to music, I don't think we can ever really do this justice. We maybe could have her react to very specific songs if the song name and artist is in spotify's title bar, but that requires focus. For discord status, we might be able to do something with the API, but currently there are no plans to look into that for now. 
[closing as rejected]
