### ISSUE TITLE
Underestimated Curiosity - Expanding on fun facts

### ISSUE THREAD

**Issue by RyanHanter** [Monika-After-Story/MonikaModDev#5927]
Hi there, this is really just a small nitpick but, I recently heard the bananas fun fact in my daily fun facts from my sweet Moni. She mentions several interesting things like reverse geotropism, or that the banana isn't a fruit but actually a berry.  What's the issue is that, she just brushes those topics off as if I'm not interested in any of them. I would want to ask Monika, why is banana curve growth categorised as reverse geotropism (where plants grow in the opposite direction of gravity) instead of phototropism (where plants will grow towards the sunlight), or even the difference between a fruit and a berry. 

Perhaps adding an option to learn more of those facts with Monika would be a something I would suggest haha.

**Comment by SamanthaLind** [comment]
Actually I think it's a problem with most, if not all, fun facts. I would be very glad for even small option at the end of topic to choose if we found that topic interesting or not. Even that little detail would improve communication between player and Monika. Cause I feel bad when I can't tell her that what she's saying is really interesting to me. Maybe option to elaborate on most topics would be too much to add, but even that chance to tell her what we think about what she just told us would be amazing. Even if it would be kinda repetitive.

**Comment by lunulae** [comment]
I don't know if I could see this being added for all facts, but I actually think it could be very cute in this case.
I could see it having three dialogue options, one to show that you were genuinely interested, one to tell her that you weren't (possibly derandoming the banana fact?) and maybe a middle-ground one where you keep the mood light (maybe with a cheesy banana joke) without having to tell her it was interesting if you didn't think so.

**Comment by CoffeeJackaboy** [comment]
> I don't know if I could see this being added for all facts, but I actually think it could be very cute in this case.
> I could see it having three dialogue options, one to show that you were genuinely interested, one to tell her that you weren't (possibly derandoming the banana fact?) and maybe a middle-ground one where you keep the mood light (maybe with a cheesy banana joke) without having to tell her it was interesting if you didn't think so.

I like the dialogue options, especially the pun option....i guess you could say i find it quite a-peeling

**Comment by RyanHanter** [comment]
Oh, besides the whole adding a "learn more feature," I also wanted to remark how Monika assumes we're not interested in the fun fact she just told us. That's also a main issue I had with that particular fun fact.

**Comment by ThePotatoGuy** [comment]
renaming issue to be more representative of the suggestion - being able to talk more about a fun fact. 
[closing until we look into it]
