### ISSUE TITLE
Wrong Hemisphere

### ISSUE THREAD

**Issue by Dom6Player** [Monika-After-Story/MonikaModDev#5928]
On first time playing the mod i accidentally choose wrong Hemisphere, so Monika now thinks that it is winter instead of summer. And i don't know how to change it or fix it. If someone would know, i would be glad.

**Comment by multimokia** [comment]
Repeat Conversation > Location > Hemispheres

**Comment by Dom6Player** [comment]
Thanks a lot! I didn't know how to fix it for long time. Thank you so much!
