### ISSUE TITLE
About reality songs

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#5929]
Hi! Just wanted to make sure of something: in one of the latest patch, there is an event where Monika sing to the piano. For me it was" Your reality". But i've discovered there is another song very similar, "Our reality" if i'm not mistaken. When looking in the files, either the former or either the latter is choosen to be sung, wich depend if Monika has been delected or not, but i've kind of seen that this event trigger once and if your reality is choosen, our reality will never be sung, but the dialogue implie that she can sing our reality after she sung your reality. So: if she sang your reality, could she sing our reality too in the futur? (sorry if my english gave you a heart attack)

**Comment by multimokia** [comment]
It's only one or the other. Lorewise, if you never deleted Monika, "Your Reality" was never written, therefore she sings the other instead.

If you did delete her, "Our Reality" was never written, so you get the other.
