### ISSUE TITLE
Consumable regifting

### ISSUE THREAD

**Issue by kennytomo** [Monika-After-Story/MonikaModDev#5932]
I am still confused on how to regift monika her consumables after reading the patch notes and even watched a video https://www.youtube.com/watch?v=yJyWzb5YRE8 (It didn't work). so i was wondering if anyone could give me any advice or instructions on how to regift?

**Comment by fromulus** [comment]
Simply redo the same .gift file you did the first time.

**Comment by kennytomo** [comment]
so i just create a text file or new folder and name it coffee.gift? because i tried that and it didn't work

**Comment by Booplicate** [comment]
It must be a file with the `.gift` extension. Not a folder. There's a [gifting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-[SPOILERS]#gifting-guide) for Windows.

**Comment by kennytomo** [comment]
It worked! Thanks guys!  \(^-^)/

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
