### ISSUE TITLE
I keep running into an uncaught exception.

### ISSUE THREAD

**Issue by Mr-alexander10** [Monika-After-Story/MonikaModDev#5936]
After exhausting Monika's dialogue for the day, an exception pops up. Here is the full traceback.

  File "game/script-ch30.rpy", line 1431, in script
  File "C:\Users\1324g\Desktop\Doki Doki Literature Club\renpy\execution.py", line 56, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.2

**Comment by multimokia** [comment]
As of #5703, these are gone. They're pretty much inconsequential and cause no harm, so you can safely hit the ignore button.
