### ISSUE TITLE
Your Reality Piano Bug

### ISSUE THREAD

**Issue by AuroraRose54** [Monika-After-Story/MonikaModDev#5937]
I asked Monika to play Your Reality on the piano. The piano animation came up (with her eyes moving and blinking and all), and the song started playing, but there was no text. Once the song ended the piano stayed there and took a reeeaaallly long time to disappear. Something to look into!

**Comment by multimokia** [comment]
No lyrics during that is intentional (she's singing, via the actual song, basically). How long exactly did it take for her to remove the piano?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
