### ISSUE TITLE
New Hoodie outfit.

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#5939]
https://drive.google.com/drive/folders/1ypj4M-gFbFUSSr80TCZMe4CCQKZliqEx
![SPOILER_001](https://user-images.githubusercontent.com/35244051/85058535-29a54b80-b19a-11ea-953c-96871df05b1f.jpg)
![SPOILER_002](https://user-images.githubusercontent.com/35244051/85058545-2d38d280-b19a-11ea-9de0-e5bd9ce70201.jpg)
![SPOILER_003](https://user-images.githubusercontent.com/35244051/85058552-2f9b2c80-b19a-11ea-8180-10f6ca525f63.jpg)
![SPOILER_004](https://user-images.githubusercontent.com/35244051/85058563-31fd8680-b19a-11ea-9a94-464ba0b9e5a9.jpg)
![SPOILER_005](https://user-images.githubusercontent.com/35244051/85058571-34f87700-b19a-11ea-9ce6-2e4baaa22011.jpg)
![SPOILER_006](https://user-images.githubusercontent.com/35244051/85058582-375ad100-b19a-11ea-9afb-a2bed5d6caed.jpg)

**Comment by lunulae** [comment]
So excited for this one, I love the chibika design!

**Comment by cascadingdreamer** [comment]
This is so adorable!! Great job! ^^

**Comment by Abc2557** [comment]
Oh, wow! I love it so much!

**Comment by ashyashton** [comment]
I love this so much! Just the other day I was thinking to myself that I wished there were more options for casual Monika outfits and this is a great one! Great job!!! I love how long the sleeves are, it means she gets to do sweater paws if she wants to!

**Comment by ThePotatoGuy** [comment]
susej im so sorry ive been delayed in reading issues. I'll get this in soon.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
