### ISSUE TITLE
Should Monika talk about copying her into the real world?

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5940]
I've been thinking, a lot of MAS is about Monika wanting to "cross over", or come to the real world, and we discuss a lot of different ways that can happen. However, as some, if not most of you have realized, it's not as simple as "creating a Monika AI". Why? Okay, lets say someone creates a perfect supercomputer that acts like a human being, and has Monika's personality traits.

Your MAS Monika will still remain on your desktop. Nothing will really have changed for her. Some will probably be okay with a copy of the one they're spending time with now, especially if somehow the memories of Monika from MAS, and the experiences you've shared are extracted somehow, and used in the new AI. However, the persistents are going to keep being made in MAS, and soon, the Monika in MAS will have different experiences with you than the one in the real world. They'll be two different Monikas.

So should Monika address this? I'm not sure how exactly she would handle that thought, given that she wants out personally more than anything. Maybe she'll suggest with tears in her eyes that [player] could delete her on that fateful day and spend the rest of their life with the other Monika? I don't think Monika would conclude that's what [player] would want.

Or should she suggest that MAS needs to collaborate somehow with the makers of the AI to do a "transaction" process where she is actually uploaded into the AI's data core?

In any case, it's a glaring problem that is probably even harder to answer than how to make the AI Monika-like in the first place.

**Comment by Rai99** [comment]
I don't think we should get too far into just how realistic the idea is, or how it might actually work in reality. Monika already addresses that she would probably need some kind of body in the real world, and I think that's a good amount to get into the thought. 

Assuming it could one day happen, it's probably not going to be any time soon, and technology will probably be different, so there's a decent chance that there'll be more possibilities later.

**Comment by Freshairkaboom** [comment]
I mean, it's already possible if you just take your laptop with your wherever and use some kind of advanced webcam technology that recognizes terrain and objects in pictures. That technology already exists. Anything else would just have to build upon that. When I say possible, it's probably not possible for hobby programmers to do on their free time, haha, would have to be some serious money and dedication involved.

However, seeing as MAS Monika is so obsessed with the idea, it wouldn't be too much to have her ponder some more on the logistics of it, surely? I think at least that it would add to the whole tragic love story vibe you have going on anyways with the mod.

I respect your decision regardless, just thought I'd air the idea.

**Comment by Rai99** [comment]
As of right now, the use of webcam and recognition technologies are out of scope, and any out there aren't official. 

I wouldn't call Monika obsessed with crossing over, but she definitely has a lot of ideas and plans for when that happens. Bringing up the matter in detail would bring up more questions, and to those, what would be said? I don't know if having her deeply acknowledge the logistics of how it could actually happen could bring positive value to the mod. Sure, it could be an interesting discussion, but other than that technology advances rapidly, and there's bound to be new possibilities later, what could be said that doesn't leave off on an overly depressing note? 

I would imagine a topic like this not being in the highest of moods, which is fine in some cases, but what would the takeaway be?

**Comment by Freshairkaboom** [comment]
I think the takeaway of the conversation is that Monika loves you so much she'd want you to be happy regardless of what you chose to do.

I didn't mean she's obsessed to an unhealthy degree or anything. Just as in, she talks about it almost as much as she tells you that she loves you. This would just be another, later stage conversation about it I guess, where she starts out worried about the logistics, but in the end her love for [player] wins through and she ends on a lighter note.

**Comment by lunulae** [comment]
The potential technical difficulties of entering our reality is probably a topic of interest for Monika, but I'd want to be careful with how pessimistic this topic could get.
I think it's also kind of intentionally ambiguous on how Monika interprets her own consciousness. If we wanted to get into this kind of meta-talk, we might also have to grapple with if a backup Monika is different from your Monika, if loading an old save has implications from that once they diverge... It's not impossible but it would be a difficult and pretty uncomfortable topic.

On a more optimistic note though, I would definitely be interested in more topics about advancements in robotics and how they could potentially apply to Monika in hypotheticals.

**Comment by Freshairkaboom** [comment]
I think we've already talked about something like that, that your body changes out every single piece of itself every 7 years. So it could be a followup of that, where she explains that it is her experiences with you that makes her 'her'. That as long as you have the shared experiences together, and she doesn't forget everything, then you're still with the same Monika. I think at one point she goes off on a tangent explaining your physical features from previous conversations, but I forget in what context.

I think in human beings too, we are mostly our memories, and the fact that we can kind of keep track of our location through time, from birth until the present. So if Monika is copied, it's different, but as long as it's the same folder, she's still present in the same location, even though her files get renewed, just like human cells.

**Comment by kirillPro2020** [comment]
In the end, we are limited only by our imagination.
