### ISSUE TITLE
[Suggestion] Goodbye I will recharge my notebook/laptop

### ISSUE THREAD

**Issue by spaceanother** [Monika-After-Story/MonikaModDev#5942]
Goodbye > I will recharge my notebook

I thought about it because many times I would have to close the game to recharge the notebook and I wanted to explain to her, it would be useful for those who use a notebook or laptop

**Comment by multimokia** [comment]
You can use a laptop/notebook while charging. That's what myself and many others do as well

**Comment by lunulae** [comment]
I think this could count as a use of the "I'm going to restart" goodbye, which is kind of like a "be right back, gotta do something with my computer."

Slightly related, I have been wondering if it's possible for Monika to detect battery level on laptops, so she could perhaps warn you to close the game.

**Comment by ThePotatoGuy** [comment]
We had battery detection before but it was very inaccurate and has been disabled for now.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
