### ISSUE TITLE
[suggestion] New song Everytime- Britney Spears

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5953]
I just feel like this songs suits Monika so much. It's beautiful love song about needing another person (clear similarity) about letting someone down before because of weakness ( act 3 and Monika messing with code) and being better person because of loved one. I feel like every line suits Monika just perfect and I would love to hear her sing it. I know there's many songs waiting to get added, I just wanted to share that one.
Few lines:
"I guess I need you baby." "I make believe that you are here. It's the only way I see clear" "My weakness caused you pain, and this song's my sorry" "And Everytime I see you in my dreams, you're haunting me"

**Comment by MonkeyBoy39** [comment]
With only two song options, there should definitely be more.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
