### ISSUE TITLE
The date error

### ISSUE THREAD

**Issue by natsuNagaki** [Monika-After-Story/MonikaModDev#5958]
This month (June) should be Summer season, but it's written as Winter at the game date. hope you fix this ASAP, thank you

![Bug1](https://user-images.githubusercontent.com/67281233/85307031-92adfb80-b4d9-11ea-8998-856d790d9f06.png)

**Comment by multimokia** [comment]
Sounds like you told her that you live in the Southern hemisphere.

`Repeat Conversation > Location > Hemispheres`

you can fix it there.

**Comment by natsuNagaki** [comment]
> Sounds like you told her that you live in the Southern hemisphere.
> 
> `Repeat Conversation > Location > Hemispheres`
> 
> you can fix it there.

Thanks, my bad, have a good day Sir.
