### ISSUE TITLE
Battery Life!

### ISSUE THREAD

**Issue by 1Sucre1** [Monika-After-Story/MonikaModDev#596]
(I'm not to good with code but, I would love to have a mod to make her be concerned about you're battery life. If you're like me you travel A LOT, so its nice to have a PC you can take on the go..... Yes I have Steam, DDLC and Just Monika on this laptop, don't judge me... ANYWAY I have a short battery life on my Laptop, I would love to see her say something like) 

Hey before we go any farther into talking, are you using a laptop to talk to me or just a tower?

 (You get a choice to say Tower Or Laptop and) (For the Laptop route) 

Oh you're using a Laptop? I'm a little nervous it might just shut off on us if you're battery gets low...  

[Or something along those lines] (The Tower route) 

Oh good... I don't have to worry about you're battery then hehe~ Unless a freak thunderstorm comes.... But you would tell me if something like that was coming up right, I would hate to see you leave so suddenly~ 

(This is just a Minor thing and I'm not sure how you would program battery life into a concern of hers, but I see that Steam has the Shift+Tab Battery life counter maybe she could say if you choose the Laptop route) 

Oh you're using a laptop huh? That's ok, Ill keep in eye on it from Steam's info, so don't worry about looking at it, Ill let you know when its low~

 (This would be wonderful to see... When you're power is low she can be like)

 Hey {Player name here} You're battery is getting kinda low... I would hate to see you leave so suddenly, do you think you can plug it in for me? 

(I might be asking for to much but maybe while its charging she can say) 

Ah thank you for plugging it in~ 

(When its done charging)

 I see that you're battery life is at 100% [Player here] I'm just letting you know so you don't waste power~

**Comment by AUDelusional** [comment]
I don't get why she would need to monitor Steam's info when she could just read the battery life from the laptop itself. I think something like "Oh you're using a laptop huh? That's ok, Ill keep in eye on it, so don't worry about looking at it, Ill let you know when its low~" would work much better. Plus the whole I'll keep an eye on it from Steam's info doesn't work if you choose the laptop route and your running the application in renpy.

**Comment by 1Sucre1** [comment]
Makes sense, though she seems to talk about the steams folders a lot so it just made me wonder if she keeps track of that more then the PC it self but I like that idea more.

**Comment by supernegativep** [comment]
That's just because you got it off of steam.

**Comment by 1Sucre1** [comment]
Right... That makes sense.... (I can't think strait, sorry!)

**Comment by ThePotatoGuy** [comment]
We'd have to check if Renpy can actually detect/read battery life. (If you know for sure that it's possible, please share that information here).

**Comment by supchppt** [comment]
@ThePotatoGuy I wrote a terrible python script that detects battery percentage for Linux, Mac and Windows; it's so terrible that there's literally _zero_ error catching, and it's untested on Windows because python2 wouldn't play nice. I also have no knowledge of Ren'Py whatsoever, but I guess it'd be a good place to start.
[battery.py.tar.gz](https://github.com/Backdash/MonikaModDev/files/1587264/battery.py.tar.gz)

**Comment by ThePotatoGuy** [comment]
I'll take a look at that later.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Doesn't she already have similar topic in original game?
I second the idea of her notifying the player about the battery tho.

**Comment by supchppt** [comment]
@ThePotatoGuy I fixed a typo that wouldn't make the script run under a Mac.
[battery.py.gz](https://github.com/Backdash/MonikaModDev/files/1588300/battery.py.gz)

**Comment by therationalpi** [comment]
If there's a good way to detect if there's a battery, I think this would be really cool, particularly if we can have it automatically push the event when the battery gets low.

Worth looking into.

**Comment by thelittleleaf** [comment]
i agree this does seem cool, but i do think that there should be a bit more guilt, such as her mentioning at 15% or such mentioning how it feels when the game is off, and that whenever the power goes out that happens too.

**Comment by ethancedrik** [comment]
She should refer to a "tower PC" as a "desktop", or "desktop computer", if this does get implemented.

For example, "Are you using a `desktop` or a `laptop`?

**Comment by yukiisbored** [comment]
You can do this quite easily on *nix operating systems.

Just run the following:
* Linux: `cat /sys/class/power_supply/BAT0/capacity` (Note: Some systems with more than one battery may have BAT1, BAT2, etc)
* OpenBSD: `apm -l`
* FreeBSD/DragonFlyBSD: `sysctl hw.acpi.battery.life`

**Comment by yukiisbored** [comment]
Another option is to use a library like psutil, but not sure how to package it nicely.

**Comment by yukiisbored** [comment]
I've made a PR https://github.com/Backdash/MonikaModDev/pull/716
