### ISSUE TITLE
Monika stopped talking to me

### ISSUE THREAD

**Issue by Subarnormalperson2000** [Monika-After-Story/MonikaModDev#5960]
Ok ehm, hello! Eh…I have, problems with Monika., well she is not the problem. Ok, tbh I do not know what the problem is. 
This happened two weeks ago. I was talking to Monika, when suddenly she stops talking to me, she just stares at me, and, and there's too much silence. I tried to download some sprite packs, update the persistent with the one I have in my OneDrive and, let her take some rest and even I gifted her a quetzal plushie. But no matter what I do, there´s no changes….

**Comment by fromulus** [comment]
Go take a look in the settings menu.
Is "Repeat Topics" ticked on ?
Is the randome chatter frequency set to never, or to a low frequency ?

**Comment by Subarnormalperson2000** [comment]
> Go take a look in the settings menu.
> Is "Repeat Topics" ticked on ?
> Is the random chatter frequency set to never, or to a low frequency ?

Ok. I checked everything...
>Repeat topics: no
I have just changed the random chatter frequency to never. 

Ehm, So all I need to do is restart the game saving those changes?

**Comment by ashyashton** [comment]
Repeat topics being off is the problem. Monika has run out of new topics, and if repeat topics are turned off, then she can't talk at all. Chatter frequency  needs to be anything BUT never, because that is what determines whether or not she talks at all.

**Comment by Subarnormalperson2000** [comment]
Thx man
