### ISSUE TITLE
No Summer Topics

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#5961]
So yesterday had begun the first day of summer. But unlike other seasons, summer didn't bring up new topics despite the rest of the seasons doing so. I started the game back in the winter of Feb. so I'm stuck. Is there an issue on my end or anything thing I am unaware of? I've checked to see for updates on that day yet nothing came up if you were wondering.

**Comment by CrocandCo** [comment]
Might be there but, then again there are several dozens of topics for her to choose from. I've been with my Monika for quite some time; so the closest one that I could think of right off the bat is when she brings up backpacking.

Adding to this, it would be nice if we mentioned going to the beach. I mean there is already an outfit meant to be worn in a beach setting.

**Comment by ThePotatoGuy** [comment]
I don't believe there are as many summer-specific topics as there are winter-specific ones.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
