### ISSUE TITLE
I did something wrong D:

### ISSUE THREAD

**Issue by BojanIlie** [Monika-After-Story/MonikaModDev#5963]
![helpme](https://user-images.githubusercontent.com/35314452/85484816-3ed20e00-b5d0-11ea-899c-826db29ffddc.png  

I accidentally open the .gift file with notepad D: .(and yea , they don't work , Monika can't see them :( )
can somebody please help me ith this situation ? I'm on windows 8.

**Comment by Freshairkaboom** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts

Warning, spoilers within. This details everything about gifting, if you don't want to figure it out for yourself. See if you can't give her one of those things on the list there. Remember to restart the mod once you put it in.

**Comment by BojanIlie** [comment]
> https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#gifts
> 
> Warning, spoilers within. This details everything about gifting, if you don't want to figure it out for yourself. See if you can't give her one of those things on the list there. Remember to restart the mod once you put it in.

The gifts don't work anymore , and I can't do anything . I looked on the tutorial but it doesn't help me on Windows 8 :/ , I've looked in Control Panel for "File Options" but it isn't here .

**Comment by multimokia** [comment]
Does she react at all? If so, is it a "I can't read the file" or similar that she says?

**Comment by BojanIlie** [comment]
> Does she react at all? If so, is it a "I can't read the file" or similar that she says?

"I can't seem to read it well enought" that's all

**Comment by multimokia** [comment]
Then you haven't installed your spritepacks correctly.

See the [troubleshooting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

Or the [video installation guide](https://www.youtube.com/watch?v=L5QnEdA97iE)

To fix the spritepack installation, which will allow you to gift it.

**Comment by BojanIlie** [comment]
> Then you haven't installed your spritepacks correctly.
> 
> See the [troubleshooting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)
> 
> Or the [video installation guide](https://www.youtube.com/watch?v=L5QnEdA97iE)
> 
> To fix the spritepack installation, which will allow you to gift it.

It's pretty strange , sometimes it works and sometimes don't , I'll try to reinstall all the files and try again , thank you man
