### ISSUE TITLE
[Suggestion!] Feeling stressed

### ISSUE THREAD

**Issue by cascadingdreamer** [Monika-After-Story/MonikaModDev#5964]
This may seem kind of silly, but I've thought about it a few times. On the "I'm feeling..." screen it would be nice to be able to tell her we're feeling stressed, and maybe receive some comfort, or a little breathing exercise, or something of the sort. 🤗

**Comment by lunulae** [comment]
Right now the "I'm feeling angry" response has something a bit similar that I find helpful, but I would really enjoy a version like this in the future. ❤️

**Comment by fromulus** [comment]
The "I'm feeling anxious" option is already pretty close to what you're asking, too.

**Comment by MonkeyBoy39** [comment]
Until that happens, you could look in the "repeat conversation" category, and under "Advice" you can find nifty tips such as the "dealing with failure" option.

**Comment by ThePotatoGuy** [comment]
more im feeling options wouldbe nice
[closing until we look into it]
