### ISSUE TITLE
Monka can´t read gift files

### ISSUE THREAD

**Issue by ItzAlice7** [Monika-After-Story/MonikaModDev#5966]
I gave gifts to monika before and she didnt say anything about it but everytime I try giving new gifts to her she says she cant read the Files well enough can someone pls help me T^T

**Comment by CrocandCo** [comment]
Did you install spritepacks (that is, if you are giving her clothes)?
Did you use files (like the .CHR files) or did you use actual folders?
Did you end it with .gift?

**Comment by YBP-043** [comment]
I mean I did the same exact thing, I installed the latest sprite packs, put them in the character folder, and they all ended with .gift, but I just get the "can't read" issue.

**Comment by ThePotatoGuy** [comment]
Follow troubleshooting steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
