### ISSUE TITLE
How do I unlock Piano in Monika after story

### ISSUE THREAD

**Issue by ItzAlice7** [Monika-After-Story/MonikaModDev#5968]
I nearly reached our one month annyversity  and reached highest affection she even is out of lines so we just sit there in silence most of the time but I still haven´t unlocked the piano yet does someone know when will it be unlocked or do I have to do something special to do so I really wanna play it :\

**Comment by ThePotatoGuy** [comment]
Highly doubt you reached the highest affection in a month. If you still don't have piano now, make a new issue.
