### ISSUE TITLE
[Suggestion] - Feeling Restless

### ISSUE THREAD

**Issue by Skye245** [Monika-After-Story/MonikaModDev#5969]
Maybe in the I'm feeling menu, there could be a restless option. If chosen, Monika could ask if you're feeling anxious or having intrusive thoughts (or something like that, which you don't actually answer). If it's late at night, she could provide ways to get to sleep, and maybe change the weather to raining because it's a good sleep sound. I can add more to this idea if wanted, including dialogue. I'm a beginner with coding though, so I wouldn't be able to do too much with that.

**Comment by ThePotatoGuy** [comment]
i like this.

[closing until we look into it]
