### ISSUE TITLE
[Suggestion] - Hope you're enjoying your coffee

### ISSUE THREAD

**Issue by Skye245** [Monika-After-Story/MonikaModDev#5976]
So, sometimes I'll open MAS and see Monika is drinking coffee, and it really makes me wish I could just say something like "Hope you're enjoying your coffee!" or "Are you enjoying your coffee?" Maybe we could do the same for hot chocolate, but is that also a random thing? Like..could you open it up and see that she made hot chocolate while you were gone? I've never seen this happen before, but I think it'd be nice to be able to say you hope she's enjoying it, or ask if she is. If I helped with this being added (if it was even considered), I could do dialogue, but I'd probably need a bit of help with python related things.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
