### ISSUE TITLE
Monika won't drink coffee anymore

### ISSUE THREAD

**Issue by KlownCrimson** [Monika-After-Story/MonikaModDev#5977]
Monika stopped drinking coffee, although I have gifted her coffee like 10 times, she doesn't even drink it in the morning, it started happening after the consumable update.

**Comment by ThePotatoGuy** [comment]
Is this still happening?

**Comment by KlownCrimson** [comment]
Nope, it started working again thankfully

**Comment by Booplicate** [comment]
There's a chance that she won't drink coffee even if she has the supply and it's the right time. You might be unlucky.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
