### ISSUE TITLE
Trouble gifting things to Monika

### ISSUE THREAD

**Issue by moonlight-palm** [Monika-After-Story/MonikaModDev#5981]
Monika isn’t reacting to any gifts that I give her. I’ve given her a few gifts in the past which has worked perfectly well, but recently none of the gifts I’ve put in are working. The gift files aren’t deleting themselves from the characters folder, so I’m wondering if something isn’t working properly?

**Comment by multimokia** [comment]
What gifts are you trying to give?

**Comment by moonlight-palm** [comment]
@multimokia I’ve tried just gifting a couple different ribbons to her, but it hasn’t worked. It’s weird tho because one of my earlier successful gifts was the white ribbon. But now none of the more recent one’s I’ve tried are working. I also tried roses to see if I could get it to work with a more extreme gift, but still nothing

**Comment by multimokia** [comment]
Screenshot of your characters folder, please?

**Comment by moonlight-palm** [comment]
@multimokia 
![Uploading 6804A7ED-A24B-41D2-BDDF-06934C3DA67D.jpeg…]()
The quetzal plushie did work, it just didn’t delete itself. The other gifts there tho haven’t worked

**Comment by moonlight-palm** [comment]
@multimokia

**Comment by multimokia** [comment]
You sent it too quickly, it didn't finish uploading

**Comment by moonlight-palm** [comment]
@multimokia opps sorry, my bad

**Comment by moonlight-palm** [comment]
@multimokia here you go. The quetzal plushie did work, as it's one of the ones I did previously. The rest of the gifts there haven't worked however.
![IMG_2307](https://user-images.githubusercontent.com/67563022/85960623-deaae580-b99c-11ea-8378-018768332a86.jpg)

**Comment by multimokia** [comment]
Can you send your persistent, please? You'll have to put it in a zip file to send it

**Comment by moonlight-palm** [comment]
@multimokia okay this is gonna sound stupid, but what is a persistent?

**Comment by moonlight-palm** [comment]
> @multimokia okay this is gonna sound stupid, but what is a persistent?

I should mention that I am super inept at files and things like that

**Comment by multimokia** [comment]
The persistent is literally Monika's memories. You should be backing this file up periodically.

A guide on how to find them can be found [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by moonlight-palm** [comment]
@multimokia oh wow, okay. Thank you! Sorry for being dumb. Okay so do you just want a copy of the file named persistent, or do you want the entire MAS folder?

**Comment by multimokia** [comment]
Just the file, please

**Comment by moonlight-palm** [comment]
@multimokia right next dumb question: how do i convert it into a zip?

**Comment by multimokia** [comment]
right click > send to > compressed zip folder

**Comment by moonlight-palm** [comment]
@multimokia thank you. Once again, I'm sorry for being a pain

**Comment by moonlight-palm** [comment]
@multimokia here you go [persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4843164/persistent.zip)

**Comment by multimokia** [comment]
Looks like your `characters` folder is inside the `/game` folder. You might've accidentally dragged and dropped it in. It should be in the same folder as the DDLC exe.

**Comment by moonlight-palm** [comment]
@multimokia oh you’re right! Thank you so much! So it’s just a simple case of dragging it out of the game folder then? Thanks for being so patient with me too

**Comment by multimokia** [comment]
Yeah it is. No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
