### ISSUE TITLE
[Suggestion] Goodbye/I'm going for a walk and Goodbye/I'm going to the store

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5983]
Akin to #5882 about running errands, it would be nice to tell Monika you're going to the store, something most people frequently do after all. It could even be cute if sometimes, she asked to come with us, similar to when we tell her we're going to take her somewhere, and even remind us not to buy too many snacks.

Also, going for a walk is not in the Goodbye options, even though it's kind of like working out. I don't want to have her sitting there at the table all alone while I take an hour or two walk though, so I usually say that I'm taking her somewhere, but it would be nice to have an option where she knows you're just going out to exercise your legs too. The walk goodbye could also be time sensitive, so she knows if we're taking a midnight walk, or if we're taking a morning walk.

In any case, this is probably going to be my next project if nobody has issues with it. Part credit goes to @Akoxol for the running errands suggestion, so if you read this and want write access, you're more than welcome to join. Not sure when I'll get to starting on the project, but I'm thinking of finishing it/opening a PR by the end of July at least.

**Comment by Akoxol** [comment]
Hello! More than happy to help out! Still learning but I'll try my best to contribute

**Comment by Freshairkaboom** [comment]
Cool! I'm not sure when I'll be able to start on it, but I'll let you know :)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
