### ISSUE TITLE
Game crashing when i want to see the floating islands

### ISSUE THREAD

**Issue by NegativeOne404** [Monika-After-Story/MonikaModDev#5984]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4845415/traceback.txt)
I've just updated the game to _v0.11.2-unstable.2020.06.28.124_  and when i gone see the floating islands i got a crash. Here it is the traceback

**Comment by NegativeOne404** [comment]
I was stuck on a loop, whenever the game closed it returned to Monika trying to show me the floating islands anyways. But in the crash screen i pressed to ignore it a few times and then clicked in exit. After that the game returned before the dialogue.

**Comment by Booplicate** [comment]
Nice catch! You'll have to avoid the islands until we fix this.

**Comment by NegativeOne404** [comment]
Thx
