### ISSUE TITLE
[Suggestion] Hold me, [Player]

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#5989]
I think it would be romantic if sometimes, when it's raining, she can randomly ask the player to hold her. After all, we're not the only ones getting something from that experience, she seems pretty happy about it too. It would have to be a fairly low chance occurrence to not make it happen every time it's raining, but it should be something that's possible I think. 

Would it be possible to make this happen independently of repeat topics and random chatter settings too? I feel like this shouldn't be treated as just another topic.

**Comment by fromulus** [comment]
There's already something like that in the mod, where she'll rarely asks you for a hug.
Making it happen more frequently depending on the weather could always be interesting, but I'm not sure the framework allows for things like that as of right now.
