### ISSUE TITLE
[Suggestion] Asking 'How are you?'

### ISSUE THREAD

**Issue by ViruSSofTer** [Monika-After-Story/MonikaModDev#5991]
I think it`s pretty obvious what it means, but it definitely is a pretty simple thing (from the programming perspective) that will mean A LOT. Just like Monika asking us about our day after a hard work, we should be able to ask her the same. And the answer varies, depending on latest interactions or are absoutely random, like:

-Much better, now that you are here! (high aff, nothing special).
-I'm fine, thanks. And how are you? (with some chance) --> Proceed to I'm feeling... topic.
-I missed you! (After more than day of absence).
-I am a little sleepy. (Just turned the game on in the morning)
-It's late, want to sleep! (when late in the night)
-I think I have a small surprise for you. Check the updates! (when new update is available)
-I don't want to talk to you... (when you have something serious to apologize)
-Oh, I just wanted to talk to you about something... Do you want to listen? (Yes/No) ---> jump to random topic.
-I have some cool fact for you! Wanna listen? (Yes/No) ---> jump to random fact.
-I think, I should change something in my appearance, wouldn't you agree? (Yes/No) ---> jump to changing clothes/hair e.t.c. When nothing changed for long time.
-I`m bored. Let's play! (Yes/No) ---> jump to games.
-It's too quiet here... How about some music? (Yes/No) ---> open music panel.
-'Monika starts complaining about her life just to troll the player. Or glitches to scare him. All for lulz.'
-'Monika talks about her trying to code (something randomly generated) but failed with some funny but useless result.'
-'Monika tells you she accidentally deleted/broke the coffee jar you gave her. Please, give her another one!'

This will add more life to the everyday mini-stroyline and give some depth to the off-scene events that player cannot see. Make a limit to once/twice per day, and this feature will become very cool to uncover for days to come!

**Comment by SamanthaLind** [comment]
I love this idea. Especially that it gives Monika chance to tell player that she wants to play. Right now she has very little to say about when we play games. It depends only on player. It would be awesome to have her sometimes suggest to play with us. 
And of course to learn how she spends her time, maybe cheer her up when she doesn't feel so good.
Oh, and glitches and trolling the player, that seems pretty cool too. Maybe it's just me but I love those times when Moni plays a little joke, like that random topic where she's really serious about telling player something important, and then she says she loves player. I would love to see more of her joking around

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805 

A mood system for Monika is planned for the future, but it's still being planned how to integrate it with other frameworks and how to build the system properly.

**Comment by ViruSSofTer** [comment]
> Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805
> 
> A mood system for Monika is planned for the future, but it's still being planned how to integrate it with other frameworks and how to build the system properly.

Well, the idea is not exactly about the mood. It is basically about giving a **new topic** that can be random every day based on what you did with Monika recently, thus diversifying the basic interaction. Just like 'I love you', but sometimes causes Monika to interact with player by herself. Asking about well-being every day is the base of relationships, and this little feature will fit in perfectly, even in its most primitive form based only on RNG.
But if/when the mood system is implemented, it should be connected, of course.

**Comment by ThePotatoGuy** [comment]
The mood system described in those issues would be use RNG to determine Monika's base mood, and your interaction in the day can change it. So it's definitely required to have coherent responses when asked "How are you"

[closing as duplicate]
