### ISSUE TITLE
[Doubt] Update something for better experience.

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#5992]
I recently changed my computer, and everything was fine, but something came up so I could update better in terms of animation or graphics, I think? and everything is really crashing on with Monika, I just wanted to know the name of the app for updating because I put it "not to see again", because I'm an idiot sometimes.

**Comment by multimokia** [comment]
DirectX. It normally displays that message if images are loading/displaying slowly.

**Comment by OkiDokiABrazilian** [comment]
> DirectX. It normally displays that message if images are loading/displaying slowly.

Oh, okay thanks.
