### ISSUE TITLE
[Suggestion] Favorite color

### ISSUE THREAD

**Issue by AuroraRose54** [Monika-After-Story/MonikaModDev#5994]
So, a suggestion here. I know Monika already asks for your favorite color (though you don't get to tell her, she just thinks it's green, like her eyes). What if you could tell her your actual favorite color, and then she randomly changed her ribbon or clothes to match that? Then said something like "Did you notice anything different? I'm wearing your favorite color!"

**Comment by Rai99** [comment]
Favorite color: #2834, #2960 

It's possible, but there are a lot of possible favorite colors. We probably won't go in depth as to have Monika change and wear something that's your favorite color.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
