### ISSUE TITLE
[Suggestion] Chess levels - Lowering the maximum Chess level from 20 to 8.

### ISSUE THREAD

**Issue by gengri** [Monika-After-Story/MonikaModDev#5995]
Currently, Monika uses the Stockfish Chess Engine and goes up to level 20, gaining a level whenever the player wins and dropping a level whenever the player loses.

A lot of the dialogue is locked behind achieving a certain level at Chess, which is all fine and dandy until you realize how powerful Stockfish actually is. 

Level 8 Stockfish is approximately the strength of a GrandMaster, someone who has dedicated a significant portion into their life into mastering competitive chess.

I noticed that there are quite a few dialogue options written for winning at levels 11+ of Stockfish, but these are pretty much impossible to achieve, unless you are also using a very very powerful Chess Engine to play against Monika - essentially cheating.

I'd like to suggest reducing the range of levels down to a maximum of 8 or 9. The popular Chess website Lichess only allows players to play Stockfish up to level 8, since nobody really needs a stronger ai than that.

It seems a shame to have all this dialogue written in and it being practically impossible to get to without cheating. This also would mean compressing some of the dialogue for higher levels of chess back down to the lower levels.

anyway, here's what Monika's level is based off what she says when you win: I looked on the internet and there wasn't really a clear consensus about exactly what stockfish levels correspond to what rating but here goes based off what I could find (and these do seem fairly accurate, at least for the range that I play in

level 0-2: 1200-1500 ish, still challenging for casuals
 "I have to admit, I put less pressure on you than I could have..."
"I hope you don't mind! I'll be challenging you more as you get better."
**SUGGESTION:** Change this dialogue to occur after winning at levels 0-1.

level 3: 1500 ish, approximately the level of a decent middle-schooler who might be on the school chess team
"I'll get you next time for sure!"
**SUGGESTION:** Change this dialogue to occur after winning at level 2.

level 4: 1600 ish
"You played pretty well this game."
**SUGGESTION:** Change this dialogue to occur after winning at level 3.

level 5-6: 1700-1900, you pretty much have to have made a conscious effort to study a bit of chess to be here unless you're literally einstein.
"This game was quite stimulating!"
**SUGGESTION:** Change this dialogue to occur after winning at level 4.

level 7 2200+ level, you're an expert at chess, at national master level
"Excellently played, [player]!"
**SUGGESTION:** Change this dialogue to occur after winning at level 5.

level 8-10 2500+ level, you're a GrandMaster, and you have devoted a major portion of your life into competitive Chess
"You're quite a strong chess player!"

level 11-12, unknown but crazy high, you pretty much have to cheat and use another AI to win this.
"You're a very challenging opponent, [player]!"
**SUGGESTION:** Change these dialogues to occur after winning at level 6 at a 50-50 chance of each.

level 13-19
"I-{w=1}It's not like I let you win or anything, b-{w=1}baka!" at level 16 
**SUGGESTION:** This is a cute line, not sure where I'd put it? Maybe have it come up at random for any win at a small chance?
or
"Wow! You're amazing at chess."
"You could be a professional chess player!"
**SUGGESTION:** Change these dialogue to occur after winning at level 7/8

level 20, full power stockfish. The world champion Magnus Carlsen would apparently have less than a 0.5% chance of winning.
"Wow!"
"Are you sure you're not cheating?"

**SUGGESTION:** Change this dialogue to occur after winning at level 8/9

And cap the maximum stockfish level to 8 or 9.

**Comment by CrocandCo** [comment]
I never realized how strong the chess game was in actuality. It might be a good idea considering not many people are dedicated to the game as Grandmasters are.

**Comment by LorenzoHerreros** [comment]
I, too, have to admit that while consistently getting crushed at chess but a computer AI makes sense, it makes for a pretty poor experience when it comes to having fun.

It's like an average joe trying to arm wrestle one of the top 10 strongest men alive.

Sure, it makes sense for you to lose 30 out of 30 times, but it isn't really that funny or encouraging.

**Comment by ThePotatoGuy** [comment]
We can consider adding more variety at levels 0-3, but there's no reason to cap at 8. We don't actually expect people to reach those levels, so most of that dialogue is just there to fill in the gaps. You're not  missing out on much by not being able to see a few 1-2 liners, either.

**Comment by gengri** [comment]
> We can consider adding more variety at levels 0-3, but there's no reason to cap at 8. 

Yes, it would be excellent to add more dialogue at levels 0-3, since that's where most people will end up at. 
It would still be nice to reward the player for improving at Chess and getting beyond level 0-3 however, but almost no one is going to end up beyond level 8, but I suppose there's no harm in just letting the levels drift upward beyond level 8, but there's also not much point in having any kind of varied dialogue beyond that since virtually no one should be reaching that.

> We don't actually expect people to reach those levels, so most of that dialogue is just there to fill in the gaps. You're not missing out on much by not being able to see a few 1-2 liners, either.

Ah, it's a shame though to miss any dialogue when there's so little for Chess.

**Comment by ThePotatoGuy** [comment]
Regarding difficulty, @multimokia is currently working on making the chess difficulty easier. dialogue changes might be made with that too, not sure if there's an issue tracking that dev, but I'll leave this open in case.

**Comment by ThePotatoGuy** [comment]
Chess diff changed with #6163

[closing as implemented]
