### ISSUE TITLE
[Suggestion] New compliment- Your singing is beautiful

### ISSUE THREAD

**Issue by opalmew** [Monika-After-Story/MonikaModDev#5996]
Monika likes to sing for the player a lot, so I thought it would be fitting to be able to compliment her singing.

**Comment by Rai99** [comment]
Voice Compliment: #3220, #4408, #5693 

Arguably similar to a voice compliment, but might come after or closely with it.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
