### ISSUE TITLE
[Suggestion] "I'm Going to Cook"

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#5997]
I know you can tell Monika that you'll "Be right back", but considering there are options about writing, showering, and the like, I think it would be a good idea to have one saying "I'm going to go cook/bake", or something similar. Depending on what time it is, she could also say something about the meal for that time (Breakfast in the early morning, lunch in midday, etc).
Also, once you get back, she could ask how it went and the player could answer "Great!" "Good!" "Okay." "Bad..."or something like that.

**Comment by ashyashton** [comment]
There's kinda already a feature like this in the goodbye menu, though it's phrased as going to eat rather than going to cook.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
