### ISSUE TITLE
[Bug] [Unstable] "expected string or buffer" in Hangman

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5998]
I'm on the most recent unstable update. Went to go play hangman and got..... this:
![screenshot0005](https://user-images.githubusercontent.com/53543937/86302659-f8cc0a00-bbce-11ea-9673-c789b0c975e4.png)

**Comment by multimokia** [comment]
I think you're using my English Localization Settings submod as this works fine under stock conditions. I'll have to fix that when I have time

**Comment by multimokia** [comment]
This is fixed in the English Localization Settings 1.0.1 release. Closing as not a MAS bug
