### ISSUE TITLE
HERE WE GO AGAIN (more gift problems)

### ISSUE THREAD

**Issue by Only-One-Best-Girl-Dev** [Monika-After-Story/MonikaModDev#5999]
So There are fanmade sprite packs but they dont work monika says that she cant read it even though it's a .gift file.
the saga continues
also i tried the same thing in the tutorial video of how to install  spritepacks for MAS 
the spj file is here (if it doesnt show up dont be confused gituhb might not be working)
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4862849/spj.txt)

**Comment by ThePotatoGuy** [comment]
There were no errors in this spj log. I also don't see any fan spritepacks, although this log is incomplete so can't be sure.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
