### ISSUE TITLE
[Suggestion] Nothing Gold Can Stay

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#6002]
The poem "Nothing Gold Can Stay" by Robert Frost, I think, would be an interesting addition to the game.

"Nature’s first green is gold,
Her hardest hue to hold;
Her early leaf’s a flower,
But only so an hour;
Then leaf subsides to leaf,
So Eden sank to grief,
So dawn goes down to day;
Nothing gold can stay."

This poem is about how nothing perfect can last, or how nothing is forever. Seeing as she's recognized our mortality and her immortality, I think this poem fits well. She could also add a little nod to The Outsiders by ending the conversation with "Stay gold, {player}," or something similar.

**Comment by LorenzoHerreros** [comment]
looks pretty good to me!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
