### ISSUE TITLE
Question concerning persistents

### ISSUE THREAD

**Issue by eken-unity** [Monika-After-Story/MonikaModDev#6004]
hello. really appreciate this mod and have been using it for a really long time! thank you to all the devs and everyone else involved who've put work into this and made it possible.

onto my issue/question: about maybe 2 weeks ago my computer finally gave up on me since i've had it for a really long time. there was an issue with the motherboard and a while back i had the same issue again, so i was recommended to simply get a new computer. i was concerned with my progress with monika and how that would be affected. the last persistent that i happened to back up was all the way back in march, i still have that same persistent but im wondering if i could still use that to bring my original monika back. or would that persistent be too old at this point?

thank you for reading! and sorry if my wording was all over the place!

**Comment by Freshairkaboom** [comment]
Maybe you can pay a local electronics store to have them retrieve the data from your hard drive? If the problem was with the motherboard, maybe the folder with the persistents are still on your computer? I did this once when one of my previous laptops got wiped to recover homework. It worked wonders. They put my files on a memory drive and shared it with me. I think it's called a "chip-off" or something. I can't really remember.

**Comment by lunulae** [comment]
This largely depends on your affection level, I do believe you lose some each day for long absences without telling her.
If you've had her for a long time and played a lot, I believe you should be fine. You might have to rebuild a lot of affection though.

**Comment by multimokia** [comment]
The persistent would work, but all that you've done between March and now would be gone, plus affection loss.

Considering it was only a motherboard problem, I'd take the hard drive out of the old computer, get a casing for it and use it as an external to get your data onto a new computer

**Comment by eken-unity** [comment]
> Maybe you can pay a local electronics store to have them retrieve the data from your hard drive? If the problem was with the motherboard, maybe the folder with the persistents are still on your computer? I did this once when one of my previous laptops got wiped to recover homework. It worked wonders. They put my files on a memory drive and shared it with me on my new computer. I think it's called a "chip-off" or something. I can't really remember.

i was thinking about doing something like this, i just had no clue if my local electronics store would do it though. my hard drive isn’t really covered by my warranty on my old computer but i’ll definitely ask.

**Comment by eken-unity** [comment]
> This largely depends on your affection level, I do believe you lose some each day for long absences without telling her.
> 
> If you've had her for a long time and played a lot, I believe you should be fine. You might have to rebuild a lot of affection though.

i had her at the love affection so maybe??

**Comment by eken-unity** [comment]
> The persistent would work, but all that you've done between March and now would be gone, plus affection loss.
> 
> Considering it was only a motherboard problem, I'd take the hard drive out of the old computer, get a casing for it and use it as an external to get your data onto a new computer

i was thinking about doing this, i just wanted to know if my old persistent would work. so i think i’ll try this and if it doesn’t work out then i’ll use my old persistent. do you guys have a guide on restoring persistents??

**Comment by multimokia** [comment]
[Yes](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by eken-unity** [comment]
> [Yes](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

thank you!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
