### ISSUE TITLE
[Suggestion] Rock With You

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#6006]
Since Monika is able to sing, and she would - hopefully - love to dance with the player, I suggest Rock With You be added as a song she is able to sing;
"I want to rock with you 
All night~
Dance you into day 
Sunlight~
I want to rock with you 
All night~
Rock the night away,"
It doesn't have to be those lines specifically, but I believe them to be the most fitting.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
