### ISSUE TITLE
An exception involving Windows_reacts...

### ISSUE THREAD

**Issue by monika-koide** [Monika-After-Story/MonikaModDev#6013]
Updated to 0.11.3 this morning, and Windows Reacts was working fine until suddenly this popped up...
![image](https://user-images.githubusercontent.com/67838118/86518022-c0723900-be25-11ea-82c8-99a9b5cf3547.png)
Here's a list of files found in /game
[list_of_files.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4873515/list_of_files.txt)

**Comment by adam-desu** [comment]
Same issue but why does it say "zz_windowreacts._rpy_" because if you look in the game folder, there are no .rpy files...? Just asking for clarification.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
