### ISSUE TITLE
When you say "I'm going to take you somewhere"

### ISSUE THREAD

**Issue by icyguard** [Monika-After-Story/MonikaModDev#6016]
Sometimes when I tell Monika 'I'm going to take you somewhere', she'll repetitively repeat when you have the two options of 'actually I can't take you' and 'nothing' when I click the 'nothing' option, it takes me to 'oh, okay!' but instead of when she says 'okay...I'm ready to go.' it instead takes me back to the 2 options... it'll repeat the process 5-6 times, making me wonder if this is a bug or it's just my computer it doesn't do this every time though, only maybe 3-4 times in total now. What do you think?

**Comment by multimokia** [comment]
You only tell her to hold on if you can't take her. Just leave her to get ready and she'll come back on her own when she's done.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
