### ISSUE TITLE
Music Menu and Settings Issue

### ISSUE THREAD

**Issue by swindlesmccoop** [Monika-After-Story/MonikaModDev#6017]
When clicking the Settings button, there is a period of time in which you can still do things with the keyboard while it's fading into the Settings menu. If you press the "M" key and pull up the music menu during this fade, it opens the settings menu in the background and prioritizes the music menu. If you select a song in this menu, it will start playing it, and it immediately jumps to the Settings menu. Upon hitting Return in the Settings menu, however, it reverts to the previous song you were playing.

**Comment by ThePotatoGuy** [comment]
elevating this to high priority. I saw a streamer do this in the intro and I think it broke a bunch of things

**Comment by ThePotatoGuy** [comment]
this also applies to other hotkeys - in other words, this is very bad.

**Comment by Booplicate** [comment]
Untested, but one solution could be remove all transitions from the menu screen. Then it'd appear immediately and there wouldn't be time for hotkeys events. As a downside, it'd look worse w/o the animation, so maybe we should consider other ideas.

Alternatively, use a custom function for opening the menu. Before it'd show/hide the screen, it'd run functions to disable/enable hotkeys.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]

**Comment by swindlesmccoop** [comment]
Let's go
