### ISSUE TITLE
[Spritepack Submission] Heart Choker for Monika

### ISSUE THREAD

**Issue by SirNimblyBottoms** [Monika-After-Story/MonikaModDev#6020]
Hi! I was surprised at the lack of chokers currently available in the official MAS sprite packs, so I thought I would submit a suggestion for another choker addition. Please let me know your thoughts, and I can submit the entire folder if interested. Thanks!
![monika choker screenshot](https://user-images.githubusercontent.com/65722725/86525348-a9464200-be4b-11ea-8d53-146ece798261.png)

**Comment by cascadingdreamer** [comment]
Super cute!!

**Comment by jack-ship-it** [comment]
Looks amazing

**Comment by ThePotatoGuy** [comment]
@SirNimblyBottoms sorry for the late reply, if you still want to submit the chokers to the official sprite packs, send the images/psds here and we can add it promptly.

**Comment by SirNimblyBottoms** [comment]
@ThePotatoGuy Here is the files for the choker 
[Sirnimblybottoms-heart-choker.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4973772/Sirnimblybottoms-heart-choker.zip)

**Comment by ThePotatoGuy** [comment]
Thanks! we'll have those in shortly.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
