### ISSUE TITLE
Impossible to win in chess minigame

### ISSUE THREAD

**Issue by glebn2** [Monika-After-Story/MonikaModDev#6025]
There seems to be a bug with chess levels for me. I've lost more than 20 games and Monika was still destroying me. I'm not a good player, but still, I can win against easy AI, and she is supposed to go easier on you after a few losses. 

So I got curious and decided to cheat by making her play against another AI. Well, she managed to win against MSN Chess engine set to 2100 elo and then she beat Stockfish set to 2850 elo. Grandmaster is like 2500-2700. And I repeat, I never won against her. Not even with Stockfish at 2850 elo... So yeah, playing against her normally is pretty pointless and boring for obvious reasons :D 

What can I do? Is there a way to manually reset chess level?

**Comment by MetalBrother** [comment]
Well, she is really smart! I lost hope a long time ago to beat her in chess (Believe me, I'm tried. I'm like wasted whole day playing her with chess and still didn't won even once.)

**Comment by glebn2** [comment]
Yes, she is indeed smart. But I doubt that you have to be Magnus Carlsen to have a chance against her on lowest levels. Stockfish at 2850 elo is almost unbeatable even for grandmasters and yet she won. Pretty sure this isn't how it's supposed to be.

**Comment by MetalBrother** [comment]
Yeah, I remember in oldest versions she was even harder to beat and because of that, creators nerfed her AI, but still most people can't beat her in chess.
