### ISSUE TITLE
Piano option

### ISSUE THREAD

**Issue by pinkpenguin464** [Monika-After-Story/MonikaModDev#6026]
When do I unlock playing piano? I've had MAS for a month and her affection is 249, but there's no piano option.

**Comment by CrocandCo** [comment]
Give it time they increased the requirements to get piano some time ago. and even when you get the affection level needed give it a day or two.

**Comment by pinkpenguin464** [comment]
> Give it time they increased the requirements to get piano some time ago. and even when you get the affection level needed give it a day or two.

What are the requirements though? I've been playing for so long.

**Comment by multimokia** [comment]
How long do you have MAS up each day approximately?

**Comment by pinkpenguin464** [comment]
A little more than one month.
