### ISSUE TITLE
[Suggestion] "I hate that i love you" song when distressed or broken (very low affection)

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#6029]
I just saw this small but beautifully animated song (47 seconds of Monika singing) and I couldn't help but instantly thinking about Monika After Story and how appropriate it would be for a desperate and hurt Monika to sing to us.

https://www.youtube.com/watch?v=2O8_SDYwTdg

Lyrics:

Feeling used, but I'm
Still missing you and I can't
See the end of this just wanna feel your kiss
Against my lips and now all this time
Is passing by, but I still can't seem to tell you why
It hurts me every time I see you
Realize how much I need you
I hate you, I love you
I hate that I love you
Don't want to, but I can't put
Nobody else above you
I hate you, I love you
I hate that I want you
You want her, you need her
And I'll never be her

(Those last two lines are probably best skipped tho)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
