### ISSUE TITLE
executable installers

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#6031]
would be nice to make the install process a one-click deal, at least for win/mac users. This is open issue, welcome to anyone who wants to try.

# feature requirements
* simple, non-invasive way to auto-extract the mod to the correct DDLC directory using an executable
* easy way to build the executable package for multiple OS
    * ideally this should be a script I can run on Debian, potentially github actions, to build installers for the other OS's as needed.

if you want to work on this, add a comment stating so.

**Comment by ThePotatoGuy** [comment]
Currently looking at inno setup. looks like it can work but I would need to brush up on my pascal.

**Comment by scpketer** [comment]
@ThePotatoGuy, just so you know - in case you'd consider installing DDLC programmatically as well, [there is a library](https://github.com/raising-controversy/ddlc-dl) providing some assistance.

**Comment by Booplicate** [comment]
We don't have permissions to do that, it's a slippery slope.

**Comment by kirillPro2020** [comment]
I'll see what I can do

**Comment by kirillPro2020** [comment]
There are 2 options. This is a quiet installer, that is, without music and other things. Just an executable file. Or a full-fledged installer. With a beautiful design.

**Comment by ThePotatoGuy** [comment]
full-fledged would be preferred.

**Comment by ThePotatoGuy** [comment]
An additional note for myself - could do an executable jar installer like optifine - cross platform and allows us to do rudimentary path searching to find ddlc install paths.

**Comment by Booplicate** [comment]
This has been achieved with https://github.com/Monika-After-Story/mas-installer
Keeping open until we start using it.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
