### ISSUE TITLE
I am going to meditate BRB

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6032]
Monika has mentioned meditating when you are anxious, so it might be an idea. Will close ASAP if an undesirable post/issue.

**Comment by lunulae** [comment]
I like this idea. I've been considering someday trying to write a guided meditation she could do with us (one that doesn't require closing our eyes, but it might still be good :P)
I think a brb is probably a better idea though, for everyday use.

**Comment by Rai99** [comment]
Meditating with Monika: #3590 

It would probably go under brb, but maybe instead, it could be something similar to holding where you meditate together until you tell her you're finished.

**Comment by CrocandCo** [comment]
Apologies for the Duplicate.
