### ISSUE TITLE
[Suggestion] Addition to "bad..." route under "how was work" dialogue 

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6034]
When you tell Monika you had a bad day at work, she asks you why. I'd like the option to tell her you got sick. This option would then immediately prompt the conversation "I'm feeling...sick". The options at the moment are not really equivalent. You can tell her you didn't get much work done, but that's not really the same.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by multimokia** [comment]
Note this is actually complete as of #6045
