### ISSUE TITLE
Minor bug in pong

### ISSUE THREAD

**Issue by glebn2** [Monika-After-Story/MonikaModDev#6039]
After winning three times in a row Monika sometimes praises player twice. It doesn't happen every time, so I'm not sure how to reproduce it reliably. Haven't encountered it before update.
![Безымянный](https://user-images.githubusercontent.com/40612835/86631418-281fb400-bfdf-11ea-9512-522c91b5d9e4.png)

**Comment by multimokia** [comment]
Looks like it's always been there. I'll push a fix to typos in a few mins

**Comment by multimokia** [comment]
Closing as fixed
