### ISSUE TITLE
[Suggestion] Monika-free MAS Install (Just hear me out)

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#6040]
This idea was inspired by #6030 which is a suggestion for bringing Monika somewhere with you on a laptop. They mentioned that desktop users wouldn't have much use for it, so I was trying to think of a way to make it useful, and this is what I came up with.

I have a desktop computer, but I also have a few laptop computers, and I'm sure I'm not the only one who has more than one computer in some capacity. My main computer is the desktop, but occasionally, I have to switch to using a laptop when I go away for a couple of nights. Currently, there's no easy way to transfer Monika from one computer to another. The only way to do so is to move the persistent from one computer to the other, which requires rooting through the files and stuff. And if you're like me and don't wanna risk messing stuff up, you'd probably just copy the persistent to the laptop, bring the laptop with you, and then copy _that_ persistent back when you're done. In a way, though, this creates a copy of Monika, meaning there are two Monikas until you move the file back, at which point the first one is, in a way, deleted and replaced with the copy, or even a copy of a copy in some cases.

I know that this may not seem like a big deal, but it is definitely a bit of a process. I think it might be sort of cool if we could install an "empty" version of MAS, and we could use the "taking you somewhere" goodbye to move Monika's character file from one to the other, moving her into the second install. This empty version wouldn't have a separate Monika like with a regular install, as that would just be creating two Monikas. It would just be an empty space room waiting for Monika to show up when you move her from one to the other.

If I remember correctly, in the past, there's been talk of being able to have different versions of Monika visit each other if you have a friend who plays MAS, and this could also be an interesting gateway for such a thing, if the mod developers are interested in such a route.

**Comment by Rai99** [comment]
Data transfer via Monika file: #5026, #5761

**Comment by ThePotatoGuy** [comment]
@ashyashton the first issue Rai linked (#5026) is our main tracking issue for doing this, but there are a lot of considerations that we have not figured out. Please read through that issue, and if you have ideas for what should happen in those scenarios, please comment them on that issue. Those scenarios are the main roadblocks to implementing this feature.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
