### ISSUE TITLE
How can I use the dark UI in my DDLC mod?

### ISSUE THREAD

**Issue by stake2** [Monika-After-Story/MonikaModDev#6043]
How can I use the dark mode UI used in MAS in my DDLC mod?

**Comment by ThePotatoGuy** [comment]
The dark mode frame images we use are **not permitted for use in other mods**.
Everything else can be done via [style properties](https://www.renpy.org/doc/html/style_properties.html#)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
