### ISSUE TITLE
Question about extra rooms

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6046]
I was messing up with those options a little and it's perfect for taking Monika outside. So I thought, is there a way to not have desk and chair? Only in one location of course. Maybe have her sit on something different, but change how it looks? Not in all backgrounds, just in one, kinda chain them with specific background? Anybody knows if that's possible? And if not then I think it would be great option

**Comment by ThePotatoGuy** [comment]
all current sprites have been made with the desk and chair in mind, which means some sprites don't have extensions below the desk line. this would be a significant amt of work to extend sprites, especially since none of the original artists are on the team anymore.

Also, poses 1/3/5/7 would probably look bad without some sort of table. While there is a framework in place that can remap those poses to others, it was not meant for dynamic usage and can have disastrous affects with the current partially-cached sprite system framework.

**Comment by SamanthaLind** [comment]
I know about need to have something cover her body. But she could rest her arms on picnic table or even on pillow (it would require lot of work for that to look good but I think it's achievable).
Also I'm not asking to remove table, since it's doable now by changing the look of it. What I was asking was "is there a way to chain different looks of desk with different locations". Like having standard desk in spaceroom, move with Moni to another location (outside) and there have desk look like a picnic table. Later move with her to another room and have dining table with comfy chair behind. 
And if comes down to art then I could help, my style doesn't match up MAS style perfectly but it's not that bad.

**Comment by ThePotatoGuy** [comment]
Oh, this actually can be done already, but there's come caveats.

The table can be switched out dynamically in game with other tables via a `MASTableChair` object. There is no swap framework yet, though, so changing [the tablechair property](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/sprite-chart.rpy#L2268) will immediately change the table/chair. 

To do the above, you would need to define a [`MASTableChair`](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/sprite-chart.rpy#L3647). The key things are the `table` and `chair` tags, which should correspond to partial filenames in the [`mod_assets/monika/t/`](https://github.com/Monika-After-Story/MonikaModDev/tree/master/Monika%20After%20Story/game/mod_assets/monika/t) folder.
Again, you'd have to set the appropriate `monika_chr` property manually when you want to change it.

There's also nothing set up for a `MASFilterableBackground` to determine a default `MASTAbleChair`.

We definitely are planning to implement the missing pieces once we actually have a released background in a different location, but progress on that part is still ongoing. If this is something that you really need now, we could prioritize implementing the missing functionality, specifically:
* better API for queuing a table/chair change so it can happen with a transition
* selector for table/chair changing
* defaulting a table/chair based on background.

**Comment by SamanthaLind** [comment]
Alright, thank you so much. I will try to work with that and see what I can do on art side. 
No, it's not something really important, I just thought about it while playing with that new locations option. And I'm so happy that you're working on that since it will be a great option

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
