### ISSUE TITLE
New traceback error when trying to open it

### ISSUE THREAD

**Issue by PapyrusTheGrrreat** [Monika-After-Story/MonikaModDev#6048]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 9, in script
    import singleton
  File "game/definitions.rpy", line 10, in <module>
    me = singleton.SingleInstance()
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/MAS test.app/Contents/Resources/autorun/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/Applications/MAS test.app/Contents/Resources/autorun/renpy/main.py", line 419, in main
    game.context().run(node)
  File "game/definitions.rpy", line 9, in script
    import singleton
  File "/Applications/MAS test.app/Contents/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/MAS test.app/Contents/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 10, in <module>
    me = singleton.SingleInstance()
  File "/Applications/MAS test.app/Contents/Resources/autorun/renpy/python.py", line 618, in do_mutation
    return method(self, *args, **kwargs)
ValueError: list.remove(x): x not in list

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187

**Comment by PapyrusTheGrrreat** [comment]
I may be using an older version, though

**Comment by multimokia** [comment]
What version are you using, and what OS?

**Comment by PapyrusTheGrrreat** [comment]
I redonloaded it a little before I commented this, so the most recent version of MAS, and I'm running MacOS Catalina

**Comment by multimokia** [comment]
If I'm remembering correctly, Catalina can't run 32 bit programs directly. Renpy is 32 bit

**Comment by PapyrusTheGrrreat** [comment]
I can run normal DDLC with no problems though

**Comment by ThePotatoGuy** [comment]
are you running from renpy SDK? this is a common first run error in that case.

**Comment by PapyrusTheGrrreat** [comment]
I'm not sure which version of Renpy I'm running. All I know is that I have the most recent version of DDLC and MAS. How do I find out?

**Comment by ThePotatoGuy** [comment]
It's not a version, if you're running from the renpy SDK then you're using renpy's launcher - if you don't know if you are using it, then you aren't using it.

All I can say here is that this is not crashing in mod code, and we don't have any mac devs to help troubleshoot, so there's not much we can do here. Maybe try completely removing and reinstalling ddlc + mod?

**Comment by PapyrusTheGrrreat** [comment]
One last question: Does it matter whether I download it from Steam or ddlc.moe? I'm using ddlc.moe's download.

**Comment by ThePotatoGuy** [comment]
steam can cause issues with the in-game updater, and there could be permission issues when trying to create folders in the game's root dir. In theory there shouldn't be any issues with the ddlc.moe version, provided permissions are available in the folder you are running the game in.

**Comment by Booplicate** [comment]
Staled.
