### ISSUE TITLE
Gifts not working

### ISSUE THREAD

**Issue by WizardSteak107** [Monika-After-Story/MonikaModDev#6049]
Monika cant read new gifts from sprite packs I just installed even though I have installed the sprite packs and the files are ended in .gift. I also lost the clothes and ribbons and hairstyles I had previously gifted her and installed from spritepacks like the seashell bikini. I've ry to regift and she says she can't read it but she has them before. What's the deal?

**Comment by multimokia** [comment]
Say goodbye and send spj.txt. it's in the log folder

**Comment by WizardSteak107** [comment]
Where do I send it?

**Comment by multimokia** [comment]
Drag and drop it here (the textbox) please

**Comment by WizardSteak107** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4898053/spj.txt)

**Comment by multimokia** [comment]
Most of your spritepacks our outdated. Update your spritepacks

**Comment by WizardSteak107** [comment]
where are the updated spritepacks?

**Comment by multimokia** [comment]
On the [releases page](http://monikaafterstory.com/releases.html)

**Comment by WizardSteak107** [comment]
ive downloaded the latest sprite packs but some of the content is working when i give it to her and some of it says she can't read the file

**Comment by multimokia** [comment]
Which ones don't work?

**Comment by WizardSteak107** [comment]
nevermind i figured it all out. thank you for your help
