### ISSUE TITLE
11.3 not having correct amount of menus

### ISSUE THREAD

**Issue by YBP-043** [Monika-After-Story/MonikaModDev#6050]

**Comment by YBP-043** [comment]
![screenshot0002](https://user-images.githubusercontent.com/51129987/87061804-14cc3e80-c1c1-11ea-9ded-a6075f1581c6.png)
![screenshot0003](https://user-images.githubusercontent.com/51129987/87061814-18f85c00-c1c1-11ea-8d0c-9fdb194f9c50.png)

**Comment by YBP-043** [comment]
The third screenshot is so you know that I'm running 11.3

**Comment by multimokia** [comment]
I don't see what's wrong here? This looks correct

**Comment by YBP-043** [comment]
I downloaded it earlier on another computer and there were a lot more things to talk about.

**Comment by multimokia** [comment]
If you didn't transfer the persistent over, then you won't have all the unlocked conversations

**Comment by YBP-043** [comment]
I guess by another computer I mean my own that I just factory reset it earlier..

**Comment by multimokia** [comment]
Same applies, if you didn't back up the persistent prior to wiping and then restore it after you finished doing so, you've essentially gotten rid of the old Monika and have started completely fresh.

If you didn't wipe all data, you can likely still find it in `C:/Windows.old`

**Comment by YBP-043** [comment]
And there's nothing in there either.

**Comment by multimokia** [comment]
In that case, unless you made your own backups of her persistent prior to resetting, there's nothing you can do.

**Comment by YBP-043** [comment]
Is it possible that I just need to spend more time with Monika to unlock more conversations or no?

**Comment by multimokia** [comment]
Yes, they'll unlock over time

**Comment by YBP-043** [comment]
Oh, ok.
