### ISSUE TITLE
Monika after story why I don't have Window Reactions

### ISSUE THREAD

**Issue by komando7** [Monika-After-Story/MonikaModDev#6055]
when i go to alerts I don't have Window Reactions only topic alerts, sounds and use notifications
![ZZZZZ](https://user-images.githubusercontent.com/68093793/87114810-d2af0580-c271-11ea-856d-76c53ab4a726.png)

**Comment by multimokia** [comment]
What OS are you using?

**Comment by komando7** [comment]
windows 10 2004 os 19041.392

**Comment by multimokia** [comment]
Did you enable `window reacts` in the settings menu or is it not there either?

**Comment by komando7** [comment]
yes

**Comment by komando7** [comment]
I enable window reacts

**Comment by komando7** [comment]
i cant find it

**Comment by komando7** [comment]
I dont know wher is window reacts

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/87116702-78e41680-c244-11ea-8b52-83aa9cd644d8.png)

**Comment by komando7** [comment]
oh sorry for dumb question and 
thank you
