### ISSUE TITLE
(Low Priority) Song Reaction?

### ISSUE THREAD

**Issue by blurp259** [Monika-After-Story/MonikaModDev#6058]
I dunno if this would be possible or not, but I thought it might be interesting if Monika could react to the player playing a song that she sang for him/her before (i.e. Monika having a blushing/surprised face and saying "I love this song" when the player plays "Your Song", since it's something she can "sing"). Maybe this could be a random occurrence?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by ThePotatoGuy** [comment]
not trivial as music can be changed in a variety of places, and spaceroom expressions are ATLs which mean performance is a concern.
