### ISSUE TITLE
How to disable "Update" or change update source

### ISSUE THREAD

**Issue by mas-mirror** [Monika-After-Story/MonikaModDev#6062]
Hello there. We provide unofficial Chinese translation of MAS. However, due to incorrect operation, many players have updated it to the official English version. I hope there is a way to disable updates or change the update source.

**Comment by multimokia** [comment]
`updater.rpy` has links to the update source. Change those to redirect

**Comment by mas-mirror** [comment]
> `updater.rpy` has links to the update source. Change those to redirect

tks.
