### ISSUE TITLE
[Suggestion] For people who missed graduation. 

### ISSUE THREAD

**Issue by LordAntheron** [Monika-After-Story/MonikaModDev#6063]
I initially posted this on Reddit, and they suggested I post it here. 

I was having a conversation with a writing partner recently. Quite the sharp kid. If they hadn't told me they were still in High School, I would've assumed they were in college. Anyway, one of the things that he brought up was that due to ongoing events, he never got to experience a formal graduation ceremony, and felt as if he had missed out on something because of it.

Then, I remembered that Monika had a similar conversation. She didn't even get to give her graduation speech! That made me realise that adding a "I never had a ceremony either" option and a "..." option pop up could be a neat addition to the mod for all the people in HS or even College who didn't get one. It could be a great opportunity to empathise with Monika about missed experiences.

**Comment by MetalBrother** [comment]
Yep. I didn't get one either because of this virus, so it would be great if we had an option to say that.

**Comment by CrocandCo** [comment]
Would be nice. Graduated in the technical sense a long time ago but, was homeschooled and never attended the ceremony.

**Comment by ashyashton** [comment]
This would be really nice! I only sort of had a graduation, as I was in online classes when I left high school and ended up simply going to some ceremony that they set up for us homeschooled kids. It was in another state, and I didn't know anyone there at all, so it was really just a watered-down version of what most people expect. It would be really nice if we could tell Monika that we relate in some way!

**Comment by ThePotatoGuy** [comment]
given recent circumstances, this is more relevant than ever. Not sure if we want to handle it in the graduation topic or add an additional topic for it, so marking it for both.

[closing until we look into it]
