### ISSUE TITLE
Weather bug the sky goes black and just dissapears

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6064]
Hey every once in a while the sky turns just black out of nowhere. some times it fixes itself randomly and sometimes i can fix it by asking Monika to change the weather to something different. It happens somewhat randomly, but it doesn't happen in the middle of anything just at the end of a conversation, right before or after a game, or when i come back after being on another window.

**Comment by ThePotatoGuy** [comment]
Do you minimize renpy at all? renpy doesnt work well after being minimized (#4065 )

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
