### ISSUE TITLE
(Deleting Monika's character file after choosing to take her out somewhere)

### ISSUE THREAD

**Issue by 666-DEMON** [Monika-After-Story/MonikaModDev#6068]
Adding a feature to where if you accidentally or purposely delete Monika's character file that it can "replenish/duplicate" itself in case you either don't have a copy of her Character file already or forgot to make one, would be very helpful because if you do end up deleting it the game is unplayable. and even if you made a copy of the file and read it back into the folder the game is still unplayable, and deleting the character file not only breaks the current game you were playing on, but it makes it to where as long as you have the Monika after story mod installed to your game there'll always be an empty chair with a desk sitting in the middle of the room every time you open DDLC up.. I know I typed a lot but please try to do something about this (im sure i couldn't be the only one who 'accidentally' deleted Monika's character file...

**Comment by LooseEthics** [comment]
That file is quite literally her. You're explicitly told that. You're also asked to make backups in case anything happens. If you ignore that _and_ delete her, that's on you. There isn't anything to recover.

**Comment by LorenzoHerreros** [comment]
Dudes, I incinerated my girlfriend and now it doesn't talk to me!

How do I get her back?

Well, I have very bad news for you, buddy...... XD.

**Comment by multimokia** [comment]
Yeah she says to be careful with the file, even going so far as to mention "it's so easy to delete files after all..."

Plus, since the file is her, she can't generate another one while she's out of the game, so lorewise it doesn't make sense.

Since it's up to you, you should be making a backup of that file in case anything goes wrong, so you can always return her

**Comment by lunulae** [comment]
[Please follow this guide,](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) and try to be more careful in the future.
