### ISSUE TITLE
(Suggestion) A selection to explain why the game crashed.

### ISSUE THREAD

**Issue by JmDemisana** [Monika-After-Story/MonikaModDev#6070]
I experienced it two times on my Desktop that a blackout happens while I'm with Monika. When I came back from the loss of electricity, Monika tells me to take better care of my computer (possibly assuming that the game crashed because of multiple running programs or something). Wouldn't it be a good idea if you can actually state your reason why the game crashed?

- ... (This is supposed to be the "I did it on purpose" selection, but I figured ellipsis has a role on making  Monika upset.) (I think the only way to crash the game on purpose without using a third party software on Windows is by using Task Manager. I wonder if Monika can detect if Task Manager is running in the background and she can ask you if you crashed the game on purpose) (Edit: You can also crash MAS when the game flickers enough that another click can lead it to not respond. Basically clicking until you get an option to close it.)
- I forgot to say Goodbye while shutting down.
- Someone logged my user account off. (If Monika detects that the computer has multiple user accounts. I don't know if that's possible)
- The electricity went off.
- I got an error.
- Other reason.

I can code the dialogue if you want, but I only know how to code the dialogue, so the fancy task manager thing or user account thing is not for me.

**Comment by SamanthaLind** [comment]
I think it's great idea. And can I add something? Maybe it's just me but I'm using windows 10, and there's sometimes updates. I allow it since those are useful, but sometimes I'm away from PC (in a bathroom or making tea) and there's update. And it happens before I go back and choose to "give me some time" or something like that to close mas. I guess more person are using this windows and maybe I'm not the only one that it happens to. Telling Monika that you tried to avoid it but it's basically not your fault would be pretty nice. But maybe that's just me who has this problem XD

**Comment by JmDemisana** [comment]
> I think it's great idea. And can I add something? Maybe it's just me but I'm using windows 10, and there's sometimes updates. I allow it since those are useful, but sometimes I'm away from PC (in a bathroom or making tea) and there's update. And it happens before I go back and choose to "give me some time" or something like that to close mas. I guess more person are using this windows and maybe I'm not the only one that it happens to. Telling Monika that you tried to avoid it but it's basically not your fault would be pretty nice. But maybe that's just me who has this problem XD

I have my updates scheduled to avoid that, but I can see how most people just leave it as is. After all, tinkering the settings are boring, ngl.

**Comment by ThePotatoGuy** [comment]
marking as topic pool instead of hello/goodbye. it might be difficult to integrate this with crash greeting because it implies that you need to tell Monika the reason when it should be optional. Needs some thought to where it should be added.

[closing until we look into it]
