### ISSUE TITLE
Location submod concerns

### ISSUE THREAD

**Issue by Cdino11** [Monika-After-Story/MonikaModDev#6071]
I  have some questions that can not be answered from the guide page regarding the cans and can not's of changing locations 

1. are the  floating islands disabled when not in the space room on purpose? For example since the islands are outside the space room and if you go to ...  say a "beach location" it wouldn't make sense for you to see them, or is there a way to enable it or disable it in the .rpy 

2. i did a test and found that decorations from events stay on when changing locations which I am fine with, but i was wondering if there is a way i can disable or enable it in the .rpy 

3. the snow ss image isn't something i saw as an option for weather in the framework. is it something i can add in or is there a reason it was left out

**Comment by multimokia** [comment]
Floating islands are always disabled when not in the spaceroom.

It doesn't make sense to use the same image as spaceroom (plus the window open/close ones which literally have the windows from the spaceroom in them) 

As for decorations, you'll have to hide them. We just never really did this ourselves given that for the most part, the bday decor works with backgrounds (plus they're submod and not a part of official lines). Come closer to events, we'll start handling the way deco works a bit more. Ideally would also be handled better with #5540 once it becomes a complete framework

snow_ss is an option and it is used

**Comment by Cdino11** [comment]
how would i go about hiding the decorations, i am really new with with coding
and as far as the snow ss image i was refrencing this framework:
def __init__(
            self,
            background_id,
            prompt,
            image_day,
            image_night,
            image_rain_day=None,
            image_rain_night=None,
            image_overcast_day=None,
            image_overcast_night=None,
            image_snow_day=None,
            image_snow_night=None,
            hide_calendar=False,
            hide_masks=False,
            disable_progressive=None,
            unlocked=False,
            entry_pp=None,
            exit_pp=None
        )
its not included here, and i was wondering if this was intentional and only intended for the space room, instead of locations added via submod
and thank you for answering so quickly

**Comment by multimokia** [comment]
This version of creating backgrounds is deprecated. Have a look at `MASFilterableBackground` in zz_backgrounds. That's what should be used now for full flexibility.

As for hiding decorations. You'll want to look into script-holidays to find the decoration hide functions and add it to your background's entry programming point

**Comment by Cdino11** [comment]
thank you so much

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
