### ISSUE TITLE
Window React Question

### ISSUE THREAD

**Issue by blurp259** [Monika-After-Story/MonikaModDev#6072]
I dunno if this was asked before, but I'm just curious. Will the "window react" feature ever be implemented on Mac/Linux (and if it already is, how do I enable it)? :D

**Comment by JmDemisana** [comment]
It is on Linux. I think the changelog explains it.

**Comment by blurp259** [comment]
Aw damn, are there any plans for a Mac release?

**Comment by JmDemisana** [comment]
I guess the lead devs don't have a Mac and can therefore not make it work. Probably if a contributor decides to help.

**Comment by blurp259** [comment]
ah... I see. Thanks :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
