### ISSUE TITLE
[Suggestion] I'm feeling...energetic/excited

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#6073]
Hey everybody, long time Moni lover, 6th time suggester.

I am loving all the new stuff Mon-Mon is getting and this excitement is something I want to share with Monika a lot of times. Whenever I feel super energetic to do something or something is about to happen that i am excited about I want to tell her but there isn't an option for that...yet. I think the closest is "I'm feeling happy" but that is more like being satisfied with something that already happened. Now excuse me, I got some more attention to give to a certain girl ^^

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
