### ISSUE TITLE
[Suggestion] Be right back... I'm going to read for a bit.

### ISSUE THREAD

**Issue by LeonidasZero** [Monika-After-Story/MonikaModDev#6075]
A be right back option to go read a book. With all the literature topics and the fact that you and Monika are/were in a literature club, it would be nice to have an option for reading. Obviously going above and beyond Monika could possibly join in with a book of her own, afterwards asking the player how much they read, and if they finished it how much they liked it.

**Comment by Rai99** [comment]
Reading brb: #2311, #3896, #4528, #5281, #5383, #5632

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
