### ISSUE TITLE
Coffee options

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6076]
Seems limited for Monika to love coffee so much and never really drink in in other occasions. Hot Cocoa is a thing but only available in the winter close to Christmas. Perhaps someone could work on the art and coding for iced coffee. and have it only available for the summer months.

**Comment by Rai99** [comment]
Iced coffee: #4081

**Comment by CrocandCo** [comment]
Apologies, never realized this was brought up before.
