### ISSUE TITLE
{suggestion} MAS Mobile with License Check

### ISSUE THREAD

**Issue by SpinnerChris** [Monika-After-Story/MonikaModDev#6077]
I understand having a standalone game is against the guidelines, but what if you made it so that it requires the PC version of DDLC? An example is for it to work is that you have to move a certain file from DDLC from your PC to your phone. That sort of thing, that way the game isn't really standalone, but instead requires you to move the PC files over. I think that would solve the standalone problem, because you aren't providing the ddlc files and instead are requiring the user to get the files themselves.

**Comment by LooseEthics** [comment]
I think that would fall under the 'no porting to different platforms' clause.

**Comment by ThePotatoGuy** [comment]
That would still be a standalone game since it's no longer a mod running off an instance of DDLC. there is no workaround unless an official DDLC mobile game is released.
