### ISSUE TITLE
[Issue opened for a friend] MAS0.10.7 on macOS High Sierra : no log file

### ISSUE THREAD

**Issue by mas-mirror** [Monika-After-Story/MonikaModDev#6078]
Version: *Monika After Story* 0.10.7
OS Version: ~Mac OS X 13.6 High Sierra~ Mac OS X 15.4
Issue : no log files, and it isn't hidden
(sorry for the wrong title)

**Comment by ThePotatoGuy** [comment]
see the wiki section [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-to-view-your-log-files)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
