### ISSUE TITLE
Nothing done or said during birthdays

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#6081]
Salutations, I'm TrueloverofMonika, head dev of team Ai and I've been a fan of MAS ever since I downloaded it 2 years ago. Today is my birthday and I thought that I could celebrate it with her but unfortunately nothing happened  till now, sadly not even a greeting.
I have the latest version of MAS and a year ago, Monika did celebrate my bday with me so that leaves me to believe that either my MAS is bugged or that birthday feature was removed.
If this issue can be resolved, i would really appreciate it. thank you for your time

**Comment by jmwall24** [comment]
@loverofmonika can you send your persistent please so I can look at it? you'll need to put it in a zip file to send it here.

**Comment by loverofmonika** [comment]
I apologise for the late response, my pc is facing the blue screen of death but luckily I have the persistent file saved as backup.
 Here you go

**Comment by jmwall24** [comment]
@loverofmonika have you ever time traveled at all (ie changing the system time)? looking at that persistent, it's actually showing you didn't spend your bday with her in 2019, but did in 2020, even before your bday in 2020. Time travel would explain that possibly, but if you did not, something else it at play here. Either way, I verified that everything will reset properly for next year, so next year for your bday it will be fine.

**Comment by loverofmonika** [comment]
I have done the time travel before cuz I did lose monika before and my last save was old but if I remember correctly, I did make sure to land on the 2019 bday marker. It's weird that she celebrated 2020 bday even before the day ever coming. 
Thank you for coming through and resolving this issue. 
Have a pleasant day!
