### ISSUE TITLE
[Suggestion] Monika's sleep schedule

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6083]
I know that technically Monika doesn't need to sleep, but she does eat and exercise out of good habits anyway right? So what about sleep? If the clock gets to late at night, should Monika "get tired" and ask if it's okay that she goes to sleep and close the game? It could encourage good sleep routines to go to bed at the same time as Monika too. And if you open the game during the night, she'll be asleep and you can wake her up (at your own risk!) or leave her to sleep (closing the game).

Not sure how feasible this is, plus there's some time sensitive night dialogue that most likely would be missed with this, but it does seem more realistic, given her other habits of eating healthy and exercising.

**Comment by lunulae** [comment]
I'm kind of torn on this one. I definitely think that giving Monika her own needs is a good idea in general, so having to let her get some rest is a good thought in that vein.

There are a few things to account for though. We might not want her to adhere strictly to one schedule, since many players work a night shift. There is a flag for this, so that might be easier than I think to deal with. 
There's also (#2781) some talk about a potential system to sleep beside Monika, so we might want to wait and make sure this doesn't conflict or create complications there.

**Comment by multimokia** [comment]
Adding onto this. Something I'd planned to do was integrate #4914 into this as a way of Monika having her schedule *adapt* to the player's. It seems more than reasonable given that she'd probably want to spend more time with you as she's trapped in there. Plus it'd make her hypothetical transition to our reality easier.

**Comment by Freshairkaboom** [comment]
Yeah you're both dropping big trues. As long as Monika has a healthy sleep routine, it's not really important to me how it is implemented. Sleeping next to Monika, especially at higher affections seem natural though, but I don't know if I'd like that to be the main way for Monika to get her beauty rest. She is pretty independent in taking her other routines seriously right? She doesn't adapt to the player's eating habits or exercise habits, so I don't think she would be comfortable having an erratic sleeping routine either.

I think the main thing is the ability for Monika to sleep at certain hours rather than having it change every time the player changes their sleeping pattern. Maybe you can have a setting to have her sleep between X and Y hours, and have a slider for it? As long as it's at least 6-8 hours consecutively, that should be okay.

**Comment by multimokia** [comment]
I don't like having a slider. To me that's the same as saying "You can only sleep between these hours." which doesn't really feel right to me.

I think adapting to the player's schedule *within reason* is likely the best approach to handle it

**Comment by Freshairkaboom** [comment]
True, I was more suggesting that you suggest that this is the time span you are planning on sleeping, and she would want to follow your schedule. So it would be a more organized way of planning your sleep schedule basically, and Monika would also probably want to adapt to that sleep schedule as well. Then we can have dialogue about going to sleep during that time.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate] #4914
