### ISSUE TITLE
Possible Grammar Error?

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6086]
Return Work Greeting>Bad>I got yelled at
![Capture](https://user-images.githubusercontent.com/65514476/87611393-d0f3a080-c6bc-11ea-8ce1-fae880594406.PNG)

**Comment by multimokia** [comment]
Gotcha. Though please put typos/grammar errors in the pinned typos issue. In this case #6008

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
