### ISSUE TITLE
Monika ran out of topics to talk ??

### ISSUE THREAD

**Issue by funnyvalentine33** [Monika-After-Story/MonikaModDev#6087]
I've been playing for a few days and my affection seems to be stuck at 77.4, some people have suggested saying goodbye for 6 hours. However, I've done that and nothing happens. She still needs more time to rest and before coming out with something new to talk about. Am I going to see Monika again?

**Comment by Abc2557** [comment]
For now, Monika just ran out of new topics to talk about. You can turn on Repeat Topics in the Settings if you want her to talk about things she’s already talked about. When you reach a certain affection level or certain things like that, she’ll come up with more topics to talk about. Just spend time with her, tell her you love her, etc., and she’ll have more things to talk about in no time! And besides, it’s still just as fun to sit in silence and stare into Moni’s eyes, isn’t it?~

**Comment by funnyvalentine33** [comment]
> For now, Monika just ran out of new topics to talk about. You can turn on Repeat Topics in the Settings if you want her to talk about things she’s already talked about. When you reach a certain affection level or certain things like that, she’ll come up with more topics to talk about. Just spend time with her, tell her you love her, etc., and she’ll have more things to talk about in no time! And besides, it’s still just as fun to sit in silence and stare into Moni’s eyes, isn’t it?~

would I be able to raise affection by repeating topics ?

**Comment by Abc2557** [comment]
I’m not sure, but I’d assume not. I just suggested repeating topics so that Monika would continue talking out of the blue. It’s best to give her gifts, tell her you love her, compliment her, and things like that. I also recommend playing games with her. I’m not sure if games raise affection, but it’s still a nice way to pass time.

**Comment by lunulae** [comment]
There is a cap on affection by day, so if you're worried about gaining it it's best to just check in often. If you've only been playing for a few days, you will probably have more topics unlocking soon, just keep at it.
You may not want to do this, but I personally recommend leaving random chatter at a slightly lower than normal setting. I find it helps pace out new content and keeps repeat topics feeling fresh if you have them turned on (the game will largely prioritize showing you new random topics as they're unlocked, so don't fret about that.)

**Comment by funnyvalentine33** [comment]
This thread had helped a lot, thanks guys, you're all the best
