### ISSUE TITLE
Sunrise/sunset doesn't work with the background adder submod? 

### ISSUE THREAD

**Issue by karrylarry23** [Monika-After-Story/MonikaModDev#6088]
I followed the guide given on the [wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Backgrounds) to make the custom background adder submod and it worked fine when I tested it. But I noticed that the sunrise/sunset feature doesn't seem to work with any custom backgrounds I use.

Does that filter only work with the default spaceroom backgrounds? Is there a way to fix that so that I can get sunrise/sunsets with any backgrounds I use?

**Comment by ThePotatoGuy** [comment]
The wiki page has not been updated with the new background API. @multimokia lmk if you need me to write something up.

**Comment by lunulae** [comment]
Sorry about that, I've been meaning to learn the code so I can update it. For now it's still out-of-date, I will add a disclaimer while I'm figuring out the new one.

**Comment by ThePotatoGuy** [comment]
leaving open until wiki is updated

**Comment by ThePotatoGuy** [comment]
[closing as wiki is updated]
