### ISSUE TITLE
does monika still say "good night, sleep tight, don't let the bedbugs bite" ?

### ISSUE THREAD

**Issue by comrade-pingu** [Monika-After-Story/MonikaModDev#6090]
in the latest update, 0.11.3 i've noticed that when i click "goodbye" at night she'll ask if i'm going to sleep now. and when i click yes
she'll say "i'll be seeing you in your dreams"

but i like it when Monika says "good night, sleep tight and don't let the bedbugs bite, ehehe", it still gets me after 3 years

so does she not say that anymore or i just need to pick a different option?

**Comment by multimokia** [comment]
That's still a thing. There's two very similar farewells at that time. Both have the menu. You might just be getting unlucky and she opts for the "I'll be seeing you in your dreams" one.

**Comment by comrade-pingu** [comment]
yep, it's really random. thanks for the help o7
