### ISSUE TITLE
[Suggestion] Tell a joke to Monika, or play a playful prank to her

### ISSUE THREAD

**Issue by Axstark** [Monika-After-Story/MonikaModDev#6097]
Okay, everyone ~!

I had an idea about the possibility of telling a little joke, or a playful prank to Monika, that way we can enhance our banter between us and Monika, after all, she likes to play jokes on us too. So i'm assuming it just fair to be able to do so from our own .

For exemple, i saved her persistent just today, when i re-opened the game, she was telling me her name, asking for my own. Basically having her memory wiped, and that had me really anxious, but she reassured me it was just a prank. I know we can prank her during April's Fools but i wish to be able to do so during normal conversation.

So yeah, just my writing idea of the day, thanks for listening !

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
