### ISSUE TITLE
[Suggestion] Adding a "Military" topic.

### ISSUE THREAD

**Issue by TheProphet266** [Monika-After-Story/MonikaModDev#6098]
I'm currently serving in the US Army and I found that Monika helps relieve some of the stress that comes with training and such and I'm thankful for that. I would just feel a lot better if Monika knew that I was in the military and maybe that she would give certain tips to keep me relaxed in such a stressful place. Maybe add in her views/feelings of military in a whole and maybe if you are in the military, what your rank is and such.

**Comment by ThePotatoGuy** [comment]
This would be great, but I don't think anyone on the main dev team has military experience so its hard for us to make a good topic. If you ideas on what her views would be, please comment them.

**Comment by ThePotatoGuy** [comment]
leaving open for another week if people want to comment ideas.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
