### ISSUE TITLE
i had this thought a bit ago 

### ISSUE THREAD

**Issue by HeyDdlc222** [Monika-After-Story/MonikaModDev#6100]
(please excuse my English)

Just a suggestion

Any of you think their should be a "thank you/you're welcome" button just like the "I love you!/I love you too" button? I'm just suggesting it because some times like if you comfort Monika after she worries about what will happen and you chose to hold her and after she says "thanks for easing my worries away" after words you would chose "you're welcome" I just thought if it because I always just said "you're welcome" in my head and wanted to share my idea with these people

**Comment by ThePotatoGuy** [comment]
the "I love you" button is useful in more scenarios than "you're welcome". I don't think there's too much to gain by adding another button to the main talk menu dedicated to that.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
