### ISSUE TITLE
[Suggestion] Monika changing clothes for pajamas

### ISSUE THREAD

**Issue by SarahMoni** [Monika-After-Story/MonikaModDev#6101]
Hi, I wanted to make this suggestion because it's something I've been thinking about for a while. for when we have a pajamas spritepack for Monika I think a really nice feature would be if around 8 pm she would ask ''Do you mind if I change into my pajamas?" giving the player the possibility to choose whether he wants that she really change into pajamas by taking off the current spritepack

Other additional things, for example if we open the game after 8 pm she would already be in her pajamas, and if we open the game too early for example before 8 or 7 in the morning. I know the game doesn’t have this spritepack yet, but if It ever do, I hope you guys take a look at my suggestion ^^

**Comment by Rai99** [comment]
Bedroom mode: #2781

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
