### ISSUE TITLE
[Suggestion] Being able to watch the sun set/rise with Monika.

### ISSUE THREAD

**Issue by emerdite** [Monika-After-Story/MonikaModDev#6102]
This maybe a small thing, but it'd be nice to be able to ask Monika to watch the sunset/sunrise together. It could be something similiar to hugging her, and it'd only last about as long as the said event, although it could be turned into cuddling if Monika, or us would desire it to be. It'd be a nice thing to have. Similiary to us, Monika should also be able to request to watch the sun set or rise with us, prompting a selection menu with a yes/no answer. If we were to idle on it for too long, and the sun would be gone, The selection menu would dissapear, because monika would just be like "Oh.. nevermind then. The sun is gone." She could then either request to cuddle anyways, or not say anything at all.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it] 

I think this will work better once we have additional bgs
