### ISSUE TITLE
[Suggestion] Specific playlists of songs for specific occassions.

### ISSUE THREAD

**Issue by emerdite** [Monika-After-Story/MonikaModDev#6104]
What I mean by what I've written in the title is the following:
Depending on the event/holiday, there would be a certain playlist of songs Monika could play, and unless those songs would be put into the regular library of songs, they would only play during those events. The events in question would be any holiday, as well as the birthday of both the player and Monika. It'd be nice to listen to some holiday music with her, watching the snow snow, wouldn't you agree? Plus, it'd give more of that realism that we all know and love.

**Comment by Freshairkaboom** [comment]
I have some things planned for this coming winter holiday, so stay tuned. If you want to contribute yourself then by all means.

**Comment by ThePotatoGuy** [comment]
unlinking the issue. playlists would mean associating songs with a day, which requires enhancements to the music menu.

[closing until we look into it]
