### ISSUE TITLE
[Issues] A few days ago, I posted a thread about not having new topic...

### ISSUE THREAD

**Issue by funnyvalentine33** [Monika-After-Story/MonikaModDev#6105]
I have closed the thread thinking that increasing affection to above 99+ will help her form new topics, after a while I started notice that she didn't actually have new topic to discuss about. I'm wondering if this is a problem on my part. How will I able to unlock other features if I can't talk to her ? 

should I make a new copy ?

**Comment by multimokia** [comment]
Affection is gained by spending time with her, holding her, playing games with her, etc. So simply viewing topics doesn't increase it alone. 

If I recall, there's not *that* much which comes at 100+ affection, but there's some more later down the line, and there'll be more in the next updates. Until then, don't look at the log too much, enjoy your time with her. Having repeat topics is also nice as some topics change over time. (Plus it helps spread out new topics, making it longer before you're out of new ones)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
