### ISSUE TITLE
I can't give Monika clothes or hair clips

### ISSUE THREAD

**Issue by Macaroonxx** [Monika-After-Story/MonikaModDev#6107]
I've been trying to give Monika clothes and hair clips and every time I do she can't bring it in the room, gifts like coffee and chocolate I can give easily but clothes and hair clips never work. I don't know if it's because I use a MacBook or I'm using a text file it never works. Is there something I can do to fix this?

**Comment by multimokia** [comment]
Have you installed the spritepacks?

**Comment by Macaroonxx** [comment]
yes I have and I've put the files where they need to be

**Comment by ThePotatoGuy** [comment]
Try the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by Macaroonxx** [comment]
thanks, it finally worked I guess it was either the spj.txt or the gift file I was missing
