### ISSUE TITLE
[Suggestion!] Vacation

### ISSUE THREAD

**Issue by cascadingdreamer** [Monika-After-Story/MonikaModDev#6111]
It would be nice if in goodbye-> I'm going away for a while, you could say I'm going away for a while and taking you with me. 
She could be excited to go on vacation together, and such!

**Comment by Rai99** [comment]
More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
