### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by MikiMwk** [Monika-After-Story/MonikaModDev#6116]
About new backgrounds, do you have a specific name to add and in which folder do I add it?

**Comment by SamanthaLind** [comment]
There's a whole tutorial about making those. It's here (if I didn't messed up something)
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Backgrounds
Also, if you would still have troubles with making those I can send you some examples which should make it easier.

**Comment by MikiMwk** [comment]
Thank you very much
