### ISSUE TITLE
Little problem with spritepacks

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6118]
I know I'm not the only one with that problem. Bunch of spritepacks can't be read by Monika, when restarting the Game and regifting those everything finally works. From what I remember it's not problem with official spritepacks, just those published on reddit, like recolors.
I know it's nothing too important since all it takes is too restart and give them to Monika once again, but I wanted to address the issue and maybe tell someone who has the same problem about solution.

**Comment by ThePotatoGuy** [comment]
the next time Monika can't read the spritepacks, close the game and upload `log/spj.txt` here.

**Comment by SamanthaLind** [comment]
Alright. But I'm not sure when that will happen since I don't plan on installation more spritepacks... Anyway, when I'll do I surely will upload nesesery file

**Comment by Booplicate** [comment]
Are you sure you were installing sprite packs with the game closed?

**Comment by SamanthaLind** [comment]
I'm pretty sure. Also, like I said, not only I have that problem and I think other person's would install it with game closed too. Like I said, it's nothing too important but I wanted to mention it anyway.

**Comment by multimokia** [comment]
Honestly it sounds like an issue in how the spritepack folder structure is handled. Check the `spj.txt` with MAS closed and look for the spritepack. You'll be able to see an error log if the spritepack failed to load (error in json/missing images)

Or if you don't see the spritepack in the `spj.txt` at all, then the json for it is either missing or in the wrong place (not in `/game/mod_assets/monika/j`)

**Comment by SamanthaLind** [comment]
I wish I post about it sooner cause now I don't have option to look into it. I installed almost all spritepacks so... But if I get that problem again I will upload nesesery file

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
make a new issue if it happens again with the desired information
