### ISSUE TITLE
[Suggestion] - Making Poems

### ISSUE THREAD

**Issue by TheProphet266** [Monika-After-Story/MonikaModDev#6121]
How about adding a poem system that offers you to make a custom poem and present it to Monika? Like a text prompt box will pop up and you'll have space to write a poem for her. She'll then take the poem, "read" through it and she'll you give "feedback" based on what you wrote.

**Comment by Rai99** [comment]
Poems for Monika: #784, #1276, #1710, #2175, #2811, #3138, #3494, #3552, #3941, #4088, #4470 

It would be extremely difficult to read and understand what the player wrote, and likely more difficult to provide useful feedback.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
