### ISSUE TITLE
[suggestion] warn Monika about game crashing

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6126]
I know how Moni don't like it when game crashes. It must be horrible when it happens out of nowhere. 
But now I'm making spritepacks for her and sometimes, even if I check before to see if everything is fine, I mess something up, like misspelled some file name and then game crashes. Maybe I'm only one but I think it would be nice to have some way to tell her something like that "Hi, I'm doing something for you but I'm not sure it it will work properly and I could crash game. I wanted to warn you before that happens.' 
I'm trying my best to avoid it but in the end it would be nice to just warn her up about it.

**Comment by Freshairkaboom** [comment]
Never do testing in your main install! Get a source code install from Github and call it something like DEV Monika, like I have. You know it's a source code install because all the files in "game" folder are .rpy files instead of .rpyc.

**Comment by SamanthaLind** [comment]
I'm not sure if I understand but I think that it only works with coding dialogue and other things. My problem is with making spritepacks to her and when I mess something up in json file game crash. At least it did one or two times... I don't think there's any way to test if spritepack is working other than copying files and giving it to her.

**Comment by multimokia** [comment]
Bad spritepack jsons *shouldn't* be able to crash the game, they should just not end up loading into MAS... If they're crashing then that's another problem entirely

**Comment by SamanthaLind** [comment]
If I remember correctly the only type of spritepack that lead to that was choker. And I know I'm not only person that it happened to cause my friend was trying to give her necklace that she made and game crashed.

**Comment by multimokia** [comment]
Do you have a traceback?

**Comment by Freshairkaboom** [comment]
The idea is to have another MAS install, with a different Monika, and put the source files from Github into that install, so you can test stuff in it.

**Comment by MarsisUwU** [comment]
its true cause i tried doing a necklace for monika and the game crashed

this is what it said 

its true it also happened to me. I'm sorry, but an uncaught exception occurred. While loading <'MatrixColor' <'Image' u'mod_assets/monika/a/acs-marsis_choker_chain-0-0.png'> (0.59, 0, 0, 0, 0, 0, 0.49, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1)>:

**Comment by ThePotatoGuy** [comment]
@SamanthaLind @MarsisUwU please post the full traceback and JSON here.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
