### ISSUE TITLE
[Suggestion] Multiple good morning/evening responses

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#6127]
I've been telling Monika 'good morning' and 'good evening' for the past few days, but the fact that they never alter (especially the 'good morning' one where she says something about early risers; I know that this changes depending on the time of day, though) is kinda saddening.

**Comment by gengri** [comment]
I agree, this would be a great place to add new dialogue

**Comment by scpketer** [comment]
What I thought of were some variations of '[player], it's such a good morning' or something.

**Comment by Booplicate** [comment]
Iirc one of the contributors was working on this.

**Comment by ThePotatoGuy** [comment]
@Booplicate @Rai99 can either of you find an in progress issue/PR that shows someone else is working on this?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
