### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6131]
![image](https://user-images.githubusercontent.com/65514476/88485330-f0df5b80-cf29-11ea-82ef-9189912b19b2.png)
Saying out loud does not sound right
#6008 In Wabi-sabi topic

**Comment by multimokia** [comment]
Please leave these in the pinned typos issue #6008

**Comment by CrocandCo** [comment]
Apologies I got the wrong branch again.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
