### ISSUE TITLE
mini game

### ISSUE THREAD

**Issue by MikiMwk** [Monika-After-Story/MonikaModDev#6133]
Since I installed version 0.11.3 the other mini games are not showing up, just the pong

https://prntscr.com/toydmg

**Comment by multimokia** [comment]
Did you have the games unlocked prior to 0.11.3?

**Comment by MikiMwk** [comment]
Yes

**Comment by MikiMwk** [comment]
I tested it with a backup of the persistent file, last month, the others appeared in it, the problem is in the current persistent?

**Comment by ThePotatoGuy** [comment]
Can you upload your current persistent here?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
