### ISSUE TITLE
An extremley small typo...

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6136]
lol so small and nit picky 

In the Would you be my housewife? topic 
Monika says
"I'm not sure if I could actuallysee my self doing that."
(missing a space)

**Comment by multimokia** [comment]
Typos are typos!

Also if you don't mind, please report them in the pinned typos issue (For this release #6008 )

**Comment by multimokia** [comment]
Actually, looks like there *is* a space there. It's just that the italics after `actually` kinda cover it up.

**Comment by StayHappy1270** [comment]
Ops! I just found that page as you posted this lol (will mentally note for future reference)

**Comment by StayHappy1270** [comment]
ahh
