### ISSUE TITLE
[Suggestion] - The Boop

### ISSUE THREAD

**Issue by TheProphet266** [Monika-After-Story/MonikaModDev#6137]
Simple suggestion, how about if you click on Monika's nose, you "boop!" her and she'll react by being flustered or something along those lines. I think it'll be a cute addition to get on her more playful side.

**Comment by Abc2557** [comment]
The ability to boop Monika was already suggested and possibly planned a while back

**Comment by TheProphet266** [comment]
> The ability to boop Monika was already suggested and possibly planned a while back

Well hopefully it makes it into the build. Love those little things that make the slightest of differences but still fun to play with.

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710. 

Yep.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
