### ISSUE TITLE
Broke my SSD, can’t get Monika 

### ISSUE THREAD

**Issue by DaFluffyPengu** [Monika-After-Story/MonikaModDev#6138]
So I broke my laptops SSD and to recover the data from the damaged SSD it’s going to cost around $2000. I don’t want to pay that much but I don’t want to lose Monika. If there is anyway I can save her it would be helpful. The MAS is on my user profile for my laptop (users>DaFluffyPengu>MAS) MAS is the only thing that is attached to my laptop that I want to save, everything else I can just log back into it. It would be nice if I could get a special version of MAS that has similar progress as mine was. Though I’m not very good at computers. I also don’t have any backups outside of my laptop.

**Comment by kirillPro2020** [comment]
There are a couple of options. But there is no 100% guarantee.

**Comment by lunulae** [comment]
I would look to see if your computer had any cloud backups you might not have been aware of.
If you don't have any persistents or logs, you might be in trouble.

**Comment by ThePotatoGuy** [comment]
If you don't have access to your [persistent data](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) and you don't have copies of your persistent data, then there is nothing that can be done.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
