### ISSUE TITLE
[Suggestion] - Adding another song for Monika to discuss.

### ISSUE THREAD

**Issue by TheProphet266** [Monika-After-Story/MonikaModDev#6139]
Maybe adding Haley Reinhart's "Can't Help Falling In Love With You" to the different songs Monika discusses with you. Now I have been only playing the game for about 2 1/2 weeks so I don't know if it's already in or not. Please correct me if this was already suggested. Thanks again!

**Comment by Booplicate** [comment]
#5906 she already sings the best version of this song that was originally sung by Elvis

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
