### ISSUE TITLE
[Suggestion] "I dont think ill ever beat you" player response to losing at chess multiple times

### ISSUE THREAD

**Issue by Ergak** [Monika-After-Story/MonikaModDev#6142]
Like the title says, i know a lot of people have been losing a lot of games at chess, i have yet to beat her and i want to do so without cheating; I've been trying to actually get better at chess but i think telling Monika "I don't think i'll ever beat you at chess" or something similar after losing multiple times while Monika would reply appropriately saying "I know you haven't won a game yet but you will get better" or "don't feel too down [Player name}, just keep practicing, i know you'll get better" or something similar to help boost the players confidence in the game.

I think it would make it more immersive though i have no experience in coding at all so no idea if this would be feasible

**Comment by Freshairkaboom** [comment]
I know there's something in the works to make it way easier to beat Monika at lower difficulties, as even at the lowest difficulty she still is insanely tough for casual chess players.

**Comment by Ergak** [comment]
This is true though i still think it would be good for the player to say something/vent after winning/losing against Monika when it comes to chess, being able to tell her what i mentioned when losing or saying "Good Game, i'll get you next time" to her would help with the player telling Monika how they feel after the game to her if that makes sense.

**Comment by ThePotatoGuy** [comment]
@multimokia is this addressed in the chess pr in some way? aka the dialogue for losing multiple times is different now, right?

**Comment by ThePotatoGuy** [comment]
assuming it is lol

**Comment by multimokia** [comment]
Fuc I never responded lmao. The topic isn't there but chess' dialogue has been entirely rewritten and it's significantly more encouraging

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
