### ISSUE TITLE
[Suggestion] Reminders to stay on task

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#6143]
I recently used the writing BRB, and then... immediately logged onto Tumblr because my writing program is online and I got distracted on my way there. I think it would be cute if Monika could remind you to stay on-task if you say you're going to write or code or anything else that you can easily get distracted from. Obviously there would be a few requirements to be met for her to actually choose to do this.

1. Window reacts have to be on
2. Monika would ask the player if they want her to help keep them on task so that players who don't want that for whatever reason(they'd find it annoying, they don't get off task in the first place, they plan to just use different things for little breaks between writing, etc.) don't have to deal with it anyways, thus avoiding the age-old complaint people around here give that says "well **_I_** wouldn't use it, so we shouldn't add it!"

I figure that if window reacts are turned on, then every time the player uses one of those BRB options, she could ask if the player if they want her to give them reminders to stay on task. Then, if she detects certain websites, she sends a notification telling the player to stay on task. To make it easier to implement, she could say the same things for each website, meaning we don't have to write unique dialogue every time, it could just be a small list of options like "Don't get distracted, [player]!" and "I hope you're just opening that up for a break..." However, if we _do_ have unique reactions for different websites, then perhaps YouTube or other similar sites could have dialogue like "I hope that's just for music, [player]!" if the player is doing something that people typically listen to music while doing, such as writing.

Just a bit of an idea I had. Not sure how hard this would be to implement, but it would be nice to feel like Monika is looking out for me like that!

**Comment by ThePotatoGuy** [comment]
adding to both non-idle + spaceroom becaue of the complexity. I think this is great idea but will be a decent amount of work to implement in practice.

[closing until we look into it]
