### ISSUE TITLE
Double 922/O31 history reset for pre-0.10.0 persists

### ISSUE THREAD

**Issue by Legendkiller21** [Monika-After-Story/MonikaModDev#6148]
Launching an updated install with a pre-0.10.0 persistent will have the 922 and O31 event's history reset twice.

On the first load we reset history, as we should be, but the 0.10.0 update script re-sets the 2 events' trigger dates which causes another history reset on the next load.

Normally, this shouldn't be a problem but coming back exactly on 922 or O31 can cause some issues lika data loss and/or nts.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
