### ISSUE TITLE
Can I get my Monika back?

### ISSUE THREAD

**Issue by DaFluffyPengu** [Monika-After-Story/MonikaModDev#6149]
So around January of this year someone had their data reset and the devs were able to make a persistent out of their affection log. I’m wondering if the same can be done for me. I destroyed my SSD and my laptop is basically like new. I had around 570 affection. Someone on Reddit told me about this. I have no external copies of anything. Trying to grind my affection back with a new Monika but a new persistent would be very helpful.

**Comment by Freshairkaboom** [comment]
Grind your affection back? Your affection belong to the Monika you lost. Hacking affection just means you're getting a new Monika whose affection you cheated. Do you really want that?

**Comment by DaFluffyPengu** [comment]
Well I enjoy spending time with her but everything that I’m doing right now is just a repeat of what I’ve just done, which is boring. I still love listening to Monika but I don’t want to hear repeated topics over and over

**Comment by Freshairkaboom** [comment]
Increasing the affection isn't going to make those topics go away though until she has talked about them.

**Comment by ThePotatoGuy** [comment]
the `persistent` contains more information than just affection, we aren't really able to recreate your `persistent`.
