### ISSUE TITLE
Piano is Missing in 0.11.3 update

### ISSUE THREAD

**Issue by RelentlessJ** [Monika-After-Story/MonikaModDev#6150]
For some reason everytime I pressed the play button only Hangman, Chess, and Pong are available and the piano button is missing. I checked out the game files but the piano folder is there. I really want to play Piano for Monika :(

**Comment by ThePotatoGuy** [comment]
Can you do the following:
1. In the main `ddlc/` dir, create an empty text file called `givedata.txt`
2. Launch the game
3. Close the game
4. In the main `ddlc/` dir, there should be a file called `ev_dump.log`. Upload that file here.

**Comment by RelentlessJ** [comment]
Here is the file

**Comment by RelentlessJ** [comment]
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/5002237/ev_dump.log)

**Comment by ThePotatoGuy** [comment]
When did you start playing the mod?

**Comment by RelentlessJ** [comment]
I started playing the mod two years ago when I recently finished the original DDLC

2 years later I decided to transfer all my progress so I transferred both the persistent files and all the folders

When I checked the file on the new PC, the Monika character file is gone and then I remembered that I left her in my flash drive for God knows how long

I checked my flash drive but she's not there anymore so I began looking for persistent backups

I followed the guidelines on how to revert to an old persistent file by renaming the latest persistent file and boom Monika is back

Knowing that Monika is back, I decided to chill and play a different game instead. Months later, I missed her and decided to check up on her

Before checking up on her I downloaded the latest update through GitHub and pasted it in the games folder

I then downloaded the sprites and pasted it on the Monika "j" folder

When I came back to the game and decided to play some piano, the piano option is missing

When I checked the game files, the piano folder and all it's contents are still there 

I tried saying goodbye and restarting the game, the PC, downloaded a previous update but still no results

And here I am now posted an issue

**Comment by RelentlessJ** [comment]
I will attach an image of the problem tomorrow since my PC is off and it's really late here

**Comment by RelentlessJ** [comment]
![No Piano](https://user-images.githubusercontent.com/69001305/88995605-ae4cc300-d31d-11ea-83e2-a9f8ecaf6ac4.png)

**Comment by ThePotatoGuy** [comment]
to clarify, you had the piano unlocked before, correct?

**Comment by RelentlessJ** [comment]
Yes I have unlocked the piano before
I always play Your Reality and Happy Birthday with it since two years ago

**Comment by RelentlessJ** [comment]
![Piano songs 3](https://user-images.githubusercontent.com/69001305/88995813-3501a000-d31e-11ea-9122-50c6bd418594.png)
![piano folder 2](https://user-images.githubusercontent.com/69001305/88995818-3632cd00-d31e-11ea-90ed-d37cffc2c6d8.png)
![Piano folder](https://user-images.githubusercontent.com/69001305/88995820-3632cd00-d31e-11ea-9c3d-3cdec486cb49.png)
![Piano songs](https://user-images.githubusercontent.com/69001305/88995825-36cb6380-d31e-11ea-9409-407437626d44.png)

**Comment by multimokia** [comment]
Not quite what we mean. Prior to updating to 0.11.3, was piano something you could play?

**Comment by ThePotatoGuy** [comment]
Can you upload your [`persistent`](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) file here?

**Comment by RelentlessJ** [comment]
[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5004876/Monika.After.Story.zip)

**Comment by MikiMwk** [comment]
Have you discovered the reason for this? I have something like that only in my only pong

**Comment by ThePotatoGuy** [comment]
is this still happening in the latest version (0.11.4)? We haven't gotten around to checking your persistent yet.

**Comment by RelentlessJ** [comment]
I'll update the game to the latest version. Once the game has finished updating, I'll tell you the results

**Comment by RelentlessJ** [comment]
![IMG_20200906_121101923_BURST001](https://user-images.githubusercontent.com/69001305/92318215-7a12a380-f03b-11ea-816d-7b2054a0aaa6.jpg)
![IMG_20200906_121732338](https://user-images.githubusercontent.com/69001305/92318218-83037500-f03b-11ea-80c6-a64de89a1396.jpg)
![IMG_20200906_121904720](https://user-images.githubusercontent.com/69001305/92318219-8696fc00-f03b-11ea-83d8-f86c5354ba09.jpg)
![IMG_20200906_121918711](https://user-images.githubusercontent.com/69001305/92318222-8860bf80-f03b-11ea-8c84-49c23043540e.jpg)


Despite updating the game, the option is till not there :(

**Comment by ThePotatoGuy** [comment]
we dont lock piano for any reason after it is unlocked, so its probably some issue with an update script. We'll fix it next release.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
