### ISSUE TITLE
[Suggestion] Second Guessing Song

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#6154]
I have yet another song suggestion for Monika to sing. This one is "Second Guessing" by Florida Georgia Line;
"Since I met you, I
I ain't spent one second guessin'
I made up my mind
I never knew I
Just had to find my direction
Gettin' lost in your eyes
'Cause I've turned days into nights
And spent all of my life askin' questions
Now I don't spend one second guessin',"
The Southern twang of the apostrophe could be changed if needed, but I just thought Monika has spoken/sang about other genres, why not include a bit of country music? Love songs, at that.

**Comment by CrocandCo** [comment]
While there is one country song already implemented "Sunshine" by Johnny Cash. I think it might be a better to have some different songs that are more akin to the classics and not modern variations.

**Comment by lunulae** [comment]
I think this one is pretty cute, although I agree to drop the twang apostrophes. Much as I think she'd love the melancholy of country love songs, I can't imagine Monika putting on a fake accent to sing them, lol. ❤️

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
