### ISSUE TITLE
Topic Submod Help

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#6155]
Hey there! I keep seeing people talking about how this topic or that topic should just be a submod, but I haven't been able to find any topic-based submods. Most of them are just appearance-based. I also have a few topics I would like to make into submods specifically because they're incredibly niche and I know there wouldn't be a place for them in the official mod. So I have three questions:

One: Where do I find the topic/text-based submods, i.e. the ones that add new topics to the mod?
Two: How do I go about safely adding these submods to my game?
Three: How would I go about making my own topic submod, i.e. a small submod that adds a topic about a particular series for other fans of said series to download?

If anyone is willing to help answer these questions, I'd really appreciate it!

**Comment by SamanthaLind** [comment]
If you want to make submod topic for yourself just make new "submod" folder in "game" folder. Then make text file, change extension to rpy and write dialogue in that. You can open it in notepad if you don't have any program to write in renpy. If you don't know how to write dialogue look on wiki here or even better check script file where you can see examples of dialogue. I don't know if anyone publish those submods but if you want to make yours that's way to do it. If you have any more questions I'll be happy to help since I already made few dialogue for my Moni that couldn't make its way into mod

**Comment by ashyashton** [comment]
> If you want to make submod topic for yourself just make new "submod" folder in "game" folder. Then make text file, change extension to rpy and write dialogue in that. You can open it in notepad if you don't have any program to write in renpy. If you don't know how to write dialogue look on wiki here or even better check script file where you can see examples of dialogue. I don't know if anyone publish those submods but if you want to make yours that's way to do it. If you have any more questions I'll be happy to help since I already made few dialogue for my Moni that couldn't make its way into mod

Thank you so much! I wasn't sure if just randomly adding a .rpy file would mess something up with my game, so I was afraid to do so. Doesn't it need to be converted to .rpyc or something? Or am I remembering incorrectly?

As far as help adding dialogue, I'd really appreciate that! The thing I think I have the most trouble with is the expressions, like how to make her face look a certain way. I don't know any of the codes for any of that, which is what's really stopping me from getting started.

**Comment by SamanthaLind** [comment]
There special code file to have expressions shown in the game, just copy it into new file and add to submod folder. As long as those files will be in that folder everything will be alright, rpy files can cause issues only if in main game folder. And when you laugh the game it creates by itself copy of files in rpyc format. I'm not sure how it exactly works but making it is really simple. And like I said, when it comes to expressions there's specific code file that you can find on GitHub. Just look around wiki, I'm not sure where I found it, but it was somewhere here

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
