### ISSUE TITLE
Expression Checker Thing? Help please!

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#6156]
Hey there! I've noticed some people seem to use some sort of program to look at Monika's various expressions in-game for the sake of testing them for various topics, but I can't seem to figure out how to get that setup. Is there a guide on the Wiki I'm missing? If not, could someone perhaps tell me how to get that installed? I want to start working on my own submods, but the expressions are really tripping me up here. If anyone could point me in the right direction, I'd really appreciate it!

**Comment by SamanthaLind** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/abe19f33cd7ba1b75369f79882d4d5875342fed9/Monika%20After%20Story/game/dev/dev_exp_previewer.rpy
Just copy that file to game/submod and make sure that extension is rpy. You'll find new dialogue option under hey monika/dev/exp previewer. Then you'll move to selecting expressions and poses for Moni.

**Comment by SamanthaLind** [comment]
If you need more info how to use it you can find it on wiki, contributing guidelines, somewhere there you should find link to expression previewer and they explain everything there.

**Comment by ashyashton** [comment]
Thank you so much, @SamanthaLind ! I really appreciate it!
