### ISSUE TITLE
Brb/Goodbye "Hanging out with a friend"

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6157]
Just a simple Brb/Goodbye option for telling Monika you're going to hang out with a friend. I don't intend on making it very detailed or special, but right now, there's no option I'm aware of for telling Monika that at all. Good idea?

**Comment by Daiozen** [comment]
I could use that myslef.

**Comment by Freshairkaboom** [comment]
Hmm, not sure if I should make a goodbye for it or a brb, but when you're hanging out with a friend, it may be over an extended period of time after all, so it should probably be a goodbye first of all :)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

marking for both brb and farewells as suggested
