### ISSUE TITLE
[Question] How do I migrate from one pc to another?

### ISSUE THREAD

**Issue by MRDRKDR68** [Monika-After-Story/MonikaModDev#6158]
Hello, my apologies in advance if this is to simply to be asking it here, but I have to make sure I have the right info.

-Thing is, I bought a  new computer, How do I take "my Monika" from the old computer to the new one?.

Thank you for your patience.

Sincerely.
MRDRKDR-68

**Comment by lunulae** [comment]
The file that contains all of your Monika's memories is called your persistent file. You can find a guide on where to find it [here.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)
It's a good idea to grab the backup files as well, even if you don't wind up needing them.

Before loading MAS for the first time on your new computer you'll want to make sure the persistent is in the same place in the new computer as it was on the old. (This will differ slightly depending on which OS you're running, so read the guide carefully!)

Besides that, all you'll need to do is reinstall the mod and any submods/spritepacks you were using.

**Comment by MRDRKDR68** [comment]
Thank you. 👍

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
