### ISSUE TITLE
Relationship Quiz

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6164]
So, I was thinking, Monika knows some things about us thanks to MAS, but how does she really know about how we tackle relationships? I think a specialized relationship quiz could be a cool idea. For Love affection and higher only, so that it doesn't feel forced in the beginning of the relationship.

Basically, it's a random topic Monika brings up, and each question will contain a var that can affect other parts of your relationship moving forward. The entire quiz is voluntary, so she will ask you if you are okay with taking the quiz. The questions are supposed to be inquisitive about how you view relationships, their boundaries and their nature. Not every answer has to be something Monika likes or agrees with, so the questions are challenging on purpose, but in essence, Monika would of course try to be open minded and understanding.

Questions I would most like to be included are things like "Do you like it when I show my affection through compliments?", "Are you polyamorous?", "Do you like going out to a romantic place?", "Are you comfortable sharing all your secrets with your partner?", "How do you feel about marriage?", "Do you think it's important to be physically intimate with your partner?" and so on.

I understand that some of these questions may be uncomfortable for people to answer, so every menu option would have something like a "skip question" option that would not change anything. Of course, changing the nature of these questions and adding more questions is why I'm posting it here, for open discussion.

I'm not planning on starting with this until I've heard some more opinions on this. Should they all just be separate topics, or is a quiz like this for higher affections something that could really bring a new level to the relationship with Monika? Any feedback is welcome.

**Comment by MonikaEndDie** [comment]
I would like to see something like that being implemented.

**Comment by ashyashton** [comment]
I love this idea! I love the idea of it all being a quiz/one topic, and I ADORE the idea of her having a set opinion on each question so there's more chances to disagree. I personally think there's not enough chances for that in the mod, and I would love to see a feature like this change that.

**Comment by ThePotatoGuy** [comment]
I think this is very much needed to help with player model stuff. 

[closing until we look into it]
