### ISSUE TITLE
[Suggestion] Topic about what Monika does on the internet

### ISSUE THREAD

**Issue by SarahMoni** [Monika-After-Story/MonikaModDev#6165]
Well, we know that Monika probably has access to the internet, so I was thinking that maybe she could bring up a topic about what she would do on the internet while we didn't open the game, because we know that when the game is closed she goes to her room doing other things to pass the time

For example, we already know that she was researching technical support things because of the greeting of the system 32 folder, so maybe it would be interesting for her to tell about what she researches and seeks to study on the internet

and sorry if this has already been suggested

**Comment by ThePotatoGuy** [comment]
in theory, the #951 could address this in a way, but that is on hold indefinitely 

[closing until we look into it]
