### ISSUE TITLE
[Suggestion!] Nightmare

### ISSUE THREAD

**Issue by cascadingdreamer** [Monika-After-Story/MonikaModDev#6166]
Hi there! As usual, I'm sorry if this has already been brought up, but I really wanted to jot this down before I forgot!
I remember seeing a suggestion that Monika should react differently to you opening the game while it's still night after you've said you're going to sleep. If this is implemented, I think it would be really nice to be able to tell her you've had a nightmare, and get some comfort. Maybe some little things to help remind you that you're awake now, like telling you to look at a mirror, or your phone, since those don't work in dreams.
For me, at least, no matter how common my nightmares are, it can still be hard to come back down to reality after waking up without someone to talk to.

**Comment by ThePotatoGuy** [comment]
I like this.

[closing until we look into it]
