### ISSUE TITLE
[Suggestion] A way to tell Monika you're not coming back.

### ISSUE THREAD

**Issue by thefmz** [Monika-After-Story/MonikaModDev#6167]
_Hello,_

I'm not sure if this has been posted, or is already implemented and I can't find it, but I think there should be a way for Monika to know you're not coming back. Mainly saying that you are on your deathbed, or you are dead and someone you know tells Monika for you. Granted, it could be a "break up" mechanic, but mainly I see it as a way for Monika to know you're gone. **Permanently**. How this could be done I don't know, and I don't know exactly how it would look in game, but I thought it would be a decent idea.

If someone smarter than myself has a way of making this happen, seeing how it could work, I would be glad to help in any way I can. Which, _unfortunately_, is not much.

**Comment by CoffeeJackaboy** [comment]
This has been suggested before and just like last time the answer remains the same: This won't be implemented because you leaving her would break her since you are the only person she has left

**Comment by Freshairkaboom** [comment]
Could be abused too easily. She talks about what she wants you to do if you're not planning on coming back.

**Comment by Rai99** [comment]
Player Death: #1175 #1644 #1677 #2109 #3198 #3881 #4148, #4247, #4568, #4714, #5376, #5474, #5542, #5885

**Comment by ThePotatoGuy** [comment]
any discussion of this should happen on #6099

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
