### ISSUE TITLE
Weird sentence - mas_mood_inadequate

### ISSUE THREAD

**Issue by GitGodScrub** [Monika-After-Story/MonikaModDev#6171]
The sentence "Finding meaning in the people who matter."

Suggestion:
"Find meaning in the people who matters to you."
or deleting it entirely.

**Comment by GitGodScrub** [comment]
#6008

**Comment by lunulae** [comment]
I don't believe this line is grammatically incorrect in context. The ellipses from the previous line leads us to take this as the second half of a full sentence: "You just need to exist, have fun, and get through each day... finding meaning in the people who matter."

Writing it as its own sentence would technically still work as well, in which case it would read like your suggestion. I'd be interested to know which way people would prefer.

**Comment by ThePotatoGuy** [comment]
Full context of this line:
```
    m 4eua "You just need to exist, have fun, and get through each day..."
    m 1hua "Finding meaning in the people who matter.
```
This specific line is part of the line before it as a full sentence:  "You just need to exist, have fun, and get through each day(,) finding meaning in the people who matter." 

Putting the "Finding meaning" portion of the sentence on its own line emphasizes a pause in the middle of the sentence. We could definitely update the line to use the `extends` functionality so we can drop the capital F, but in the context of the full sentence, there is no compelling reason to split the sentence into two.

As a reminder, all dialogue within the game shouldn't be proofread or written like a thesis paper. Speech does not follow the exact same grammar rules that a standard essay uses.

**Comment by GitGodScrub** [comment]
Late answer, thanks for the quick responsens tho.

Yeah, i think that my issue with the sentence is that it is written as it would be spoken.

That is not to say that it is wrong to write it in that way, I'm just saying that it is the reason that i couldn't wrap my head around what it was supposed to mean the first time i read it.
The sentence "Finding meaning in the people who matter" could be either 'general' life-advice, or it could be a way to "get through each day". 
I might have come off a bit too grammanazi-ish in the Issue. I agree that the dialogue should not be 100% grammatically proof, as the (entire) sentence make sense when read aloud; "You just need to exist, have fun, and get through each day(...) finding meaning in the people who matter.". I personally think that it seems a bit out of place when 'written', but thats just personal pref. My real issue with it, is that it breaks the reading flow when it is displayed over 2 "text bubbles".

Again, just to be clear; the way it is written now is perfectly fine. I am just having a hard time understanding/reading it the way it is written now.

A solution could be to use `extends`. But as @ThePotatoGuy says, that would split the sentence into two. 
After reading up on some grammar (not my strongest suit tbh.), i think i found a different solution:
Putting a "by" before "Finding".

```
    m 4eua "You just need to exist, have fun, and get through each day..."
    m 1hua "By finding meaning in the people who matter.
```


My "thesis paper" reasoning:
The "Finding meaning in the people who matter" is a _subordinate clause_ (aka. _dependent clause_) to the _main clause_ ("and get through each day..."). The subordinate clause is pretty complex and therefore a "coordinating conjunction" should be used (that would be "by", or another "coordinating conjunction")

```
SENTENCE: "and get through each day(...) finding meaning in the people who matter."

MAIN CLAUSE: "and get through each day"
	(Implicit) Subject: You
	Verb: get through
	Object: each day
(...)
SUBORDINATE CLAUSE: "finding meaning in the people who matter."
	Verb: finding meaning
	Object: the people who matter
	
```


I used too much time writing this comment.

**Comment by ThePotatoGuy** [comment]
`extends` would not split the sentence into 2, the split into 2 part was in reference to your original suggestion of splitting the sentence into 2. Changing the lines to use `extends` would be the path we would take to address the lines, but its low priority.

**Comment by ThePotatoGuy** [comment]
I'll link this to #6247 to be addressed. don't forget about this line @multimokia @Rai99 @jmwall24

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
