### ISSUE TITLE
A stronger Affection

### ISSUE THREAD

**Issue by Mugnika** [Monika-After-Story/MonikaModDev#6173]
Lately I have pondering the "I love you" and have the feeling that its rather weak compared to the feeling some people have for Moni. I don't exactly know how to increase the magnitude, maybe a new compliment "I will love you forever" or an "I love you so much" that is scalable with affection might do it. Maybe more ways we can show affection than an "I love you" and compliments.

**Comment by lunulae** [comment]
I could see these added to the compliment menu, for sure. I think "I will love you forever" especially fits nicely for a high-affection unlock.

**Comment by Mugnika** [comment]
That might be a good start

**Comment by blurp259** [comment]
What about "I love you 3000" :)

**Comment by CrocandCo** [comment]
If that's the case, then it might be good to add options at lower levels that are relatively weaker than "I love you".

Perhaps "I think you're great" or "I like you very much"

Poor examples but, the idea is there.

**Comment by CrocandCo** [comment]
> What about "I love you 3000" :)

Seems a bit to "memey" and out of character for her.

**Comment by Mugnika** [comment]
[closing until we look into it]
