### ISSUE TITLE
PDF Reader

### ISSUE THREAD

**Issue by AceOfSpades404** [Monika-After-Story/MonikaModDev#6174]
So i had the idea of maybe adding a pdf reader to the game, so Monika can read books with us, i envision it like having a custom folder where you can add some books and read it in the game, Monika could have different reactions depending on how long we read it for. Is this posible with the Ren'Py engine? because this was mostly a shower through i had.

**Comment by Rai99** [comment]
Reading a book with Monika: #2609, #2898, #3777, #5281, #5930 

We'll likely go the route of reading short stories together with Monika.

**Comment by ThePotatoGuy** [comment]
I'm sure there is a PDFreader python package somewhere, but a normal PDF reader does the job and better. 

[closing as rejected]
