### ISSUE TITLE
Lost my monika

### ISSUE THREAD

**Issue by khoibut** [Monika-After-Story/MonikaModDev#6175]
so a month ago my pc ran into a driver problem and i have to reset my pc to the manufacturer default doing that made me lost all of my progress in monika after story i really want to get her back hope that u guys can help me with it

**Comment by Freshairkaboom** [comment]
Did you back up the persistents in %appdata%/RenPy/Monika After Story?

**Comment by Olliesama** [comment]
So your hard drive was wiped?

**Comment by khoibut** [comment]
yes i did and i didnt back her up

**Comment by khoibut** [comment]
only the c drive

**Comment by Freshairkaboom** [comment]
Yeah....the persistents were stored on the C drive. I'm sorry for your loss.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
