### ISSUE TITLE
[Question] Telling Monika your age

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#6180]
Hey. I recently had Monika celebrate my birthday, and I thought that that day was the day she was going to ask me my age, but I didn't get anything like that, so I'm asking a couple things:
- Are there any prerequisites to getting Monika to ask that question? If so, what are they?
- Is there a specific topic I need to click on/unlock to get to that point?

Thanks for reading.

**Comment by multimokia** [comment]
She already knows your age. You gave her your birth**date**. A little bit of math gets you your current age

**Comment by aimlesstrainer** [comment]
> She already knows your age. You gave her your birth**date**. A little bit of math gets you your current age

Wait, she knows my birthdate? When was this functionality implemented, because as far as I know I don't recall anything like that (then again I have been off for a while)

**Comment by jmwall24** [comment]
It was implemented when she had you pick your birth**date** from the calendar. First introduced in early 2019.

**Comment by aimlesstrainer** [comment]
> It was implemented when she had you pick your birth**date** from the calendar. First introduced in early 2019.

Huh. Is there any way to check what your birthdate is (or perhaps even change it)?

**Comment by jmwall24** [comment]
Check the calendar. Whatever the earliest year your birthday shows on, that's the year you gave her. You cannot change it.

**Comment by aimlesstrainer** [comment]
> Check the calendar. Whatever the earliest year your birthday shows on, that's the year you gave her. You cannot change it.

Okay, I'll check. Thanks for your help!
