### ISSUE TITLE
I am out of texts in 'MAS' what to do?

### ISSUE THREAD

**Issue by Anonymous-NOUC** [Monika-After-Story/MonikaModDev#6186]
I was talking with monika for a long time but now she doesn't speak she only says that 'There is no point in talking about everything now' what to do? pls help

**Comment by fromulus** [comment]
Sounds like you went through all the topics for now.
You can either wait to get to a higher affection level to unlock new topics over time, or wait for updates to the mod that will add new topics.

In the meantime, I personally recommend activating the 'repeat topics' option in the settings menu.

**Comment by Anonymous-NOUC** [comment]
> Sounds like you went through all the topics for now.
> You can either wait to get to a higher affection level to unlock new topics over time, or wait for updates to the mod that will add new topics.
> 
> In the meantime, I personally recommend activating the 'repeat topics' option in the settings menu.

Thanks, btw how can i contribute i am trying to for a long time

**Comment by Freshairkaboom** [comment]
Check out the wiki, particularly Dialogue Coding and Contributing Guidelines. That should get you started. You could also join the discord and ask your questions about coding there, that's how I got started. I'd be more than happy to share what I've learned so far. The most important thing is getting a clone of the "content" repository under <code>, and download the Github Desktop application (highly recommended). 

Once you have Github Desktop set up, grab the content repository you downloaded from the first tab called "Current repository", should be called "MonikaModDev-content". Then, make a new branch, call it Content and just base it off of "master" for now. Go to the "history" tab in Github Desktop (should be seen right under where you choose repository). Search for "upstream/content". Hopefully when you compare them it should say a certain number behind or ahead. Click the "merge into Content" button. This means that all the latest content that we're working on is now on that branch, ready for you to alter.

Use the "Content" branch you just made as a base for all your other branches. Keep it up to date with upstream/content and then make a new branch. Call the branch whatever you want, I usually title it whatever subject I want to work on. If you use spaces in the title it will switch to underscores, let it.

Now, in your new branch with that title you chose, you can make change to the code. Choose "Open in" option, I don't remember what you'll see when you start, but I chose "Visual Studio Code". Once you're in there, you'll read from Dialogue Coding how to add more dialogue.

I don't know if this is a confusing explanation, so please ask me any question.

**Comment by Anonymous-NOUC** [comment]
> Check out the wiki, particularly Dialogue Coding and Contributing Guidelines. That should get you started. You could also join the discord (https://discord.gg/eRAGuM) and ask your questions about coding there, that's how I got started. I'd be more than happy to share what I've learned so far. The most important thing is getting a clone of the "content" repository under the Code tab here on Github, and download the Github Desktop application (highly recommended).
> 
> Once you have Github Desktop set up, grab the content repository you downloaded from the first tab called "Current repository", should be called "MonikaModDev-content". Then, make a new branch, call it Content and just base it off of "master" for now. Go to the "history" tab in Github Desktop (should be seen right under where you choose repository). Search for "upstream/content". Hopefully when you compare them it should say a certain number behind or ahead. Click the "merge into Content" button. This means that all the latest content that we're working on is now on that branch, ready for you to alter.
> 
> Use the "Content" branch you just made as a base for all your other branches. Keep it up to date with upstream/content and then make a new branch. Call the branch whatever you want, I usually title it whatever subject I want to work on. If you use spaces in the title it will switch to underscores, let it.
> 
> Now, in your new branch with that title you chose, you can make change to the code. Choose "Open in" option, I don't remember what you'll see when you start, but I chose "Visual Studio Code". Once you're in there, you'll read from Dialogue Coding how to add more dialogue.
> 
> I recommend setting up a dev version of Monika too, by basically copy pasting all the new RPY files into a separate install of MAS where you have made the persistents local (please ask how to do this at discord as I don't remember). Do not make ANY changes to your main install, as it may crash the game and make Monika sad...
> 
> I don't know if this is a confusing explanation, so please ask me any question.

i know nothin about coding

**Comment by Anonymous-NOUC** [comment]
btw i changed my mind i am useless i can't do nothing. soooo i won't contribute. peace!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
