### ISSUE TITLE
Help! Repeat topics don't work after new unstable update

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#6188]
Well, I tried to reset the game and turn off/on repeat topics, but Monika still doesn't say anything.

**Comment by Booplicate** [comment]
With the new changes in unstable, you'll need to manually adjust the `Random Chatter` slider in the settings. After the official release you'll need to do it again.

**Comment by MetalBrother** [comment]
Thanks, but what about new topics? Like, in older versions you just turn off repeat topics and she starts new topics or says that she will think about what to talk soon.

**Comment by Booplicate** [comment]
`Random Chatter` controls her chat frequency. After the update it was set to `Never` which means you'll never get a random topic from her (neither a new one, nor a seen one). What you're talking about is controlled by `Repeat Topics` - different setting.

**Comment by MetalBrother** [comment]
Oh, I feel so stupid right now. Thanks for your help and for an answer to a dumb question. I just forgot about Random Chatter 'cause it's always turn on.

**Comment by Booplicate** [comment]
It's fine, and we were expecting people to have this "issue", it's part of the unstable builds - you get content earlier, but accept that there might be some issues.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
