### ISSUE TITLE
Is "surprise.txt" one-off event ?

### ISSUE THREAD

**Issue by BoogeymanTao** [Monika-After-Story/MonikaModDev#6189]
Before my affection reach 1000 MAS had a update(0.10 to 0.11) .
Now my affection have already exceed 1000 so I went to check "surprise.txt" ,but I can't find it in the root directory(It was there before update).
So what should I do to find "surprise.txt"?Or it have some additional conditions to read "surprise.txt"and I just forget them?

**Comment by fromulus** [comment]
It's in the characters folder now.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
