### ISSUE TITLE
Waking up at night and talking to Monika

### ISSUE THREAD

**Issue by oneoutoftendentist** [Monika-After-Story/MonikaModDev#6191]
If we open the game after choosing the “I’m going to sleep” option from the goodbye menu, Monika says “hope you had a good rest” no matter what the time is. It would be great if Monika could check the time and if it’s 2-3 a.m she could say something like “Couldn’t sleep [player]?”.

**Comment by CrocandCo** [comment]
#4892 #4914
 They are working on the task at hand, it is just a big project.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

**Comment by Rai99** [comment]
#4113, ~~#4892,~~ ~~#4914,~~ #5896 

> [closing as duplicate]

but it's still open.
