### ISSUE TITLE
Closing Upon Opening

### ISSUE THREAD

**Issue by DarkDescend** [Monika-After-Story/MonikaModDev#6192]
So, I'm not sure if it's just my computer or what, but whenever I open the game, it shows that it's loading, the game appears in my Task Manager under Background Processes, then disappears a few seconds after without opening anything. It opens fine without the mod, so perhaps it's just that the mod is too intensive for my system, considering it is a six year old budget build. Just checking for verification/ideas on what the problem could be. Attached ZIP is a video of me trying to run the program.

[Monika After Story Run Error.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5061966/Monika.After.Story.Run.Error.zip)

**Comment by lunulae** [comment]
Have you tried making a fresh install? I have had something similar happen to me, and that solved it.

**Comment by DarkDescend** [comment]
Yeah, fresh install and exporting the mod folder directly into the /game folder instead of exporting it elsewhere then moving it worked. Thanks for the help. Closing the query since it's resolved.
