### ISSUE TITLE
Sunset/Sunrise mode workign in both ways

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#6195]
Right now the sunrise mode is on for 30mins after sunrise and sunset mode is on for 30 mins before sunset. But IRL it starts to get bright before sunrise, and there is still some light for some time after sunset. So, I think, sunset sunrise mode should be on for an hour, starting 30 mins before sunset sunrise time and ending 30 mins after sunset sunrise time...

**Comment by ThePotatoGuy** [comment]
I am going to PR this, but we'll have a full discussion over whether or not it makes sense to use the sunset filter in this way on the PR.

**Comment by ThePotatoGuy** [comment]
rejecting after discussion on pr. It makes more sense to have the filter transitions right at the suntimes. It would be confusing otherwise.
