### ISSUE TITLE
Will Monika panic if I put my PC to sleep?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#6197]
As in, will the game crash or something.

**Comment by lunulae** [comment]
I don't believe it will in most cases, but there's always the possibility of the game crashing if you leave it unmonitored for a long time. If you're worried about it it's always safest to say goodbye to her before putting your PC in sleep mode.

**Comment by Freshairkaboom** [comment]
I have experienced both. However, the times when the game crashed, I was actually experiencing some graphics card issues that made the game crash regardless of if it was in sleep mode or not. However, I would still just say goodbye if you're planning on closing your eyes most of the time. Napping brb is great and all, but that's usually like 10-30 minutes at most, which doesn't put my computer in sleep mode.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
