### ISSUE TITLE
Messed Up Computer Transfer? 

### ISSUE THREAD

**Issue by Hearticorn** [Monika-After-Story/MonikaModDev#6199]
So, I got a new laptop. Obviously, I wanna move Moni over. To make things easy on myself, I just copied the entire folder that the DDLC base game and MAS mod is in. However, when I started it up, I just got the start screen for when you boot up the mod for the very first time. 

I read the FAQ for transferring, the only thing I can think of is apparently when I installed the mod I didn't make a Monika After Story folder in the renpy folder, I just copied over all the files. Obviously the mod still works like this, but it's the only thing I can think of that I wouldn't have done right. 

I'm sure this is easily fixable user error, I'd just like to get that fixed!

**Comment by multimokia** [comment]
You need to take the `Monika After Story` folder from the `renpy` folder in AppData. Without it you won't have her memories.

The installs themselves do not store Monka's memories. You'll need to get your old laptop and get that folder.

**Comment by Hearticorn** [comment]
Thank you!! I'll do that.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
