### ISSUE TITLE
[Suggestion] Option to add neopronouns

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#6203]
I know neopronouns are (kind of) uncommon and that this might be hard to add but it’s just an idea ehe 👉👈

So my idea is players having another option to add replacements for pronouns
Like, Monika would have the player type their various versions of She/They/He, Her/Them/Him, Her/Their/His, etc. so Monika would know the player’s neopronouns 🤷 
Maybe someone could make a submod for it idk
~~Maybe _I_ could make a submod for it.... maybe~~

Anyways, it’s just an idea that I thought I’d mention.

**Comment by ThePotatoGuy** [comment]
for the time being we are sticking with the existing pronouns. Adding user-based ones might causes grammar problems down the line.

**Comment by Retrolovania** [comment]
While this is interesting, the majority of people have absolutely no clue what neopronouns are. (I literally didn't know until I saw this and then looked it up.) Maybe, however, Monika could bring it up as a topic, or many mention it in one of her Daily Grammar Tips?

**Comment by Abc2557** [comment]
I mean, neopronouns are just pronouns that aren’t she/her, they/them, and he/him. People know neopronouns exist they just don’t know they’re referred to as neopronouns.
Anyways, valid idea

**Comment by Freshairkaboom** [comment]
Do people who use neopronouns have the same aversion to being called they/them as I am to being called she/her? I thought for simplicity sake that they/them was an acceptable alternative for non-binary genders? I could be wrong though, I've just never considered that it may be particularly important for some to have even more pronouns than the neutral they/them that sees widespread use in progressive circles today.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
