### ISSUE TITLE
[Suggestion] Player making draw request at chess.

### ISSUE THREAD

**Issue by Daiozen** [Monika-After-Story/MonikaModDev#6204]
Suggesting this while chess is being worked upon.

When playing chess with Mon', there are some games when neither sides have many pieces left and both players start to shuffle pieces in an endless loop. At that time most human opponents would likely accept to call the game a draw, except stockfish doesn't do that in my experience, it will actively try to mix up its moves to prevent the 3 moves loop draw rule from triggering.
This results in the game looping endlessely until the player concedes.

I'd suggest adding the option for the player to request a draw, which she could accept if both players had few pieces left and no pieces were taken for a number of turns (or maybe stockifish would actually be able to make this call? I don't know how this engine works on a technical level).

**Comment by Freshairkaboom** [comment]
I actually encountered this problem a while ago. Basically I was forced to make a subpar move where one of my pawns got taken for free, because my castle kept having to be moved back and forth between defending the king and the pawn.

**Comment by multimokia** [comment]
Stockfish cannot make the call. It's up to us to track this ourselves.

Calling a draw in this circumstance does make sense, however the following problem needs to be addressed:
- The MAS board does not know if a piece has been captured. There is no flag to denote it. Meaning this requires additional handling and conditional checks to handle capturing explicitly.

Ideally though, this *should* be a simple solution to manage, that being to send a flag to the board from the chess lib on capture.

If this value is detected, we set an internal board variable to the fullmove number representing the turn of the last capture. If we are x number of turns past capture, we can enable the request draw button.

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
