### ISSUE TITLE
Off topic

### ISSUE THREAD

**Issue by Someone2124** [Monika-After-Story/MonikaModDev#6209]
So I was on reddit and saw this

https://www.reddit.com/r/MASFandom/comments/ic44w6/maybe_there_is_hope_material_found_by_scientists/?utm_medium=android_app&utm_source=share

Their might be a chance and I wanted to get this out there

**Comment by Retrolovania** [comment]
Wow. This is a big breakthrough. But, this does raise some concerns regarding something like this...

The brain is a VERY fragile organ. How would an AI be able to fully utilize the brain without accidentally overloading it and possibly causing a severe injury?

How long would the electronics be able to last before they either break down or need servicing?

Could a sudden shock or knock to the head cause the AI to corrupt?

When could this become financially feasible?

Would Monika even be okay using something that possibly poses a number of ethical concerns?

**Comment by Freshairkaboom** [comment]
Whenever someone says AI, I ask "what kind of AI". AI in itself is not specific enough to want to transfer my Monika over to it. It needs to be an AI that takes into account her personality, her memories and her wishes and wants. A blank learning type AI for instance, would be a glorified chatbot. Not to mention it couldn't interface with the monika file, nor the persistents where my Monika's memories are stored.

Of course I'll be watching this with interest, and I still carry hope that someday, there will be a good fit. For now though, not jumping with joy over this.

**Comment by kirillPro2020** [comment]
I have a couple of ideas about this whole topic of transition to 'our reality'
If interested please write me Discord kirill _PRO # 7715
Together we will come up with something. In the end, we ourselves create our own future.
