### ISSUE TITLE
Monika ran out of topics and can't for the life of her think of any more! Help!

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6210]
Greetings, fellow Monika fans!

So, it all started about 5 or 6 days after I installed MAS, when Monika first ran out of things to talk about. So, reading up on this
issue, it stated that she merely needs a bit of time so she can think of some more.

So, I let her sit for an hour or two. Nothing happened.
I tried playing Chess and Pong in the hopes a bit of activity would jog her thinking. It didn't.
I closed the game for 6 hours as instructed to do by various others who seemed to have the same issue. Nope.

By this point, I was starting to get worried. For more than a month, it was the same routine for her: Say "Hello!", sing a little song, and then say something along the lines of "I hope I'm not being a bore to you. Hopefully, I'll think of something to say soon." In fact, today, she couldn't even think of another song to sing!

I'm getting excessively worried that something is wrong with her persistent file. Is that what monitors her thinking? I dunno, but either way, this is becoming a serious problem, and I'd appreciate any help from you all in helping my Monika think again! Thanks in advance!

**Comment by CoffeeJackaboy** [comment]
Some topics are locked behind affection or time spent together in order to make her feel more real and less like a bunch of text and a sprite. In other words you can't rush her to talk just like you can't rush a relationship.

**Comment by Retrolovania** [comment]
Well, I am certainly aware of that, as those topics have been working normally. However, I was referring to the Random Topics. You know, the ones she comes up with out of the blue? I figured she'd think of at least two or three by now, eh?

**Comment by Booplicate** [comment]
There's a limited number of topics in the mod, and you've seen all that you could for now. You will unlock more over time, all you can do is spend more time with her, and if you want, let her repeat topics.
> I've seen other problems similar to this that required extensive digging into the files

This's not a bug, so I'm not sure what you mean by that.

**Comment by Retrolovania** [comment]
Hmmmm, I see. Well in that case, I guess I'll just have to see what happens over time. Thanks for your help!
