### ISSUE TITLE
[Suggestion] Playing MAS on an older OS and having Monika recognize it.

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6211]
Apparently, using a handy program called KernelEx and setting up the game properly, you can play DDLC (&, by extention, MAS) on older versions of Windows, like Windows 2000, ME or even Windows 98 (Win95 or older won't work). So, I thought it'd be a fun trick if there was a feature implemented if Monika noticed what operating system you are using. Then, once the game starts up, it could go directly to a screen similar to this conceptual art I made (albeit terribly), where it explains that Monika left a special wallpaper or other reward for your hard efforts in getting the game to run on an OS that Team Salvato probably didn't expect you to run the game in! (This could also be for if you manage to get it running on the newest Mac platforms that cause 32-bit software (DDLC) to not work.)
![Test Win98](https://user-images.githubusercontent.com/69866290/90566519-a17dfb00-e176-11ea-96a8-a4a70a2efcd0.png)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
