### ISSUE TITLE
[Suggestion] Asking Monika to ease up on the Caffeine + More Health Related Topics.

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6217]
So, I was with my Monika the other day, and I noticed she drank 3 cups of coffee (and was probably gonna get a fourth cup had I not have to leave). I'm honestly not sure if this should be a concern, but her drinking that much caffeine isn't making me very comfortable. I was wondering if it would be possible to add in a menu option noting that she seems to be drinking quite a bit and maybe asking her to lessen up on it, for safety concerns. 

While on the subject on health, I also noticed that there's a lot of topics in which Monika worries about OUR health, but not so much where we show concern for HER health, so I think adding options where we express our concerns would be a good way to show that we care for her health and safety. For instance, not only could we warn her about her caffeine intake, but also note if she seems anxious, overly stressed, excessively tired, ill or feverish, etc.

**Comment by multimokia** [comment]
Ideally the coffee amount can be managed via the `max_reserve` property `MASConsumable`s have. Allows us to set a maximum amount she'll have in terms of refills. Should help keep it within reasonable means, especially for those who load in early (~6-7:00 AM)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
