### ISSUE TITLE
[Suggestion] April Fool's Update Idea

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#6218]
I just had an interesting shower idea. Now here me out guys. I think it could spark quite the conversation and be relatively fun to watch. 

So it plays out like another update but this time, the update includes 2 sprite packs to enter and a new .gift file to give to Monika, sake! The notes state that it will be one time only on that specific day (April 1st) is when it can be used and given. 

After installing the pack and update, a sake bottle will appear and will Monika will respond with confusion stating, “[Player name], is this...sake? I’m quite sure I don’t wish to drink this, but thank you anyway.” Then the player will be promoted to say, “Try it anyway.” Monika will be quite shocked, “Try it?! But...I’ve never tried alcohol before. I can’t be sure what will happen afterwards. Are you sure?” The player will be given another response being, “Yes”. She sighs but accepts the sake. However, the game will resume as normal. It’s when it’s closed that it begins.

After reopening the game on that same day, the same bottle appears to be emptied out with some drops over the table. Monika will appear with her flushed face, a “...”, and her eyes closed. The player will be given another response with, “Monika?” She will open her eyes with something different going on with her.”

“[Player name]! I’m so glad you’re *hiccup* here. I’ve missed you so much!” Naturally you will be shocked. She continues on with, “After you *hiccup* left, I got bored. So I took the bottle and gulped it all down! It’s your fault for *hiccup* leaving me for so long (The time left will actually be irrelevant.)!” Afterwards 2 new topics will spawn. One being “Are you ok?” and another being “The bottle”. 

“Are you ok” selection.

Monika: “Hmm? Of course I’m ok. I’m feeling great actually *hiccup*. I feel so free and relaxed now. I haven’t felt this way in forever. So thank you for that nice drink *hiccup*.

“The bottle” selection.

Monika: “What about the bottle? Sure, I drunk it *hiccup* but I’m fine [Player name]. It would’ve been rude not to *hiccup* accept it. Plus I feel so relaxed now. That and a bit tingly...hehehe. [Player name]…did it ever tell you how much I love you. Well because I do...a whole lot! 

Note: Monika will continue blushing throughout the entire game until you close the game again or the day ends.

After that whole experience, if the day ends or you try to leave again, she will say this. “Oh? Trying to hiccup leave. I understand. This day was been enlightening for the both of us. Thank you for hiccup spending time with me. Also...[Player name]. She is silent and is leaning towards you. Then, she giggles. “...hehe. Haha haha! April Fool’s! I had you fooled didn’t I! I never drunk it. I just emptied it. But yes, I won’t be trying alcohol anytime soon. Enjoy the rest of your day, [Player name].

And there it ends. I hope you all enjoyed this nice essay. Be sure to tell me what you think.

**Comment by Freshairkaboom** [comment]
I mean, it would be funny, but not sure if this kind of prank fits her character. Also, just to mention one thing, this only works if the player knows to close the game and open it again later. In any case, since it involves the downloading of spritepacks, it has to be entirely optional and not part of the main game, so I'd say it would fit more as a submod regardless.

**Comment by Retrolovania** [comment]
Okay, I will be honest, I do NOT like the thought of seeing a drunk Monika. Sure, she's gonna be 21 soon, but the thought of her being tipsy just....I don't know. I really wouldn't want to see harmful substances implemented.

**Comment by multimokia** [comment]
The above comment is one reason to say now

Additionally, I'll add that it's a *lot* of changes just to make this work. Seems like too much work for *far* too little of a payoff. Especially considering not everbody celebrates April Fools and it's not even a fullon event.
