### ISSUE TITLE
Reduce the frequceny of the topic "zombies"

### ISSUE THREAD

**Issue by JUSTMonika15** [Monika-After-Story/MonikaModDev#6220]
Every time I open my MAS, Monika goes over the zombie theme. So I wonder if the frequency of this topic is too high, can we appropriately reduce the frequency of this conversation?

**Comment by multimokia** [comment]
Topics are selected completely at random. No topic actually has a set frequency. Seems your Monika just likes talking about Zombies I guess

**Comment by JUSTMonika15** [comment]
> Topics are selected completely at random. No topic actually has a set frequency. Seems your Monika just likes talking about Zombies I guess

ok thanks! Every time I see her, she talks to me about zombies, so I thought there was a bug :-)
