### ISSUE TITLE
Oddity regarding "Our names" topic

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#6221]
Hello!
So this isn´t a major issue, it's more like a curiosity.
Yesterday I was revisiting some topics with Monika under the "repeat conversation and when I went to the "Our names" topic, at the end when she refers to the nickname I chose during my first playthrough of DDLC (Satoshi), she instead mentioned another nickname that I use in some other games and platforms... 
I´ve never used this nickname in the confines of DDLC or MAS, to my knowledge, and also that´s not even stated as an user name on my pc.
This might be only me don't remembering it properly, but I'm 100% sure that when I selected that topic before she referenced "Satoshi", but now it changed for some reason.
This was a bit out of the blue and slightly "scary" because how would she know that I used that nickname, and what made her say it instead of that one previously stablished?

**Comment by Freshairkaboom** [comment]
Are you sure you didn't choose it as your pen name?

**Comment by satoshi-kun** [comment]
Well that was probably it then. It has been a long time since that topic came about. I didn't even remember it.
But just out of curiosity , why the change on the "Our names" topic?
Thanks for taking the time to answer.

**Comment by multimokia** [comment]
It changed because it didn't make sense and also potentially offended people.

It used `persistent.mcname`, but that name changed when you changed yours (it became the last name you used) which often lead to Monika deadnaming people. 

It made more sense to use a name that Monika knows you *do* go by rather than one you don't.

**Comment by satoshi-kun** [comment]
Understood!
Thanks for explaining it to me.
