### ISSUE TITLE
How do I install the "enhanced idle"?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#6225]
https://github.com/multimokia/MAS-Submod-Enhanced-Idle/releases/tag/EI_1.0.1

I downloaded it and it came with a README file, but its filetype is MD.. I don't know how to read that..

**Comment by multimokia** [comment]
Would've been best if you left a comment on the Enhanced Idle repository itself, but just merge the game folder in the zip with the game folder in your DDLC install

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
