### ISSUE TITLE
Unstable version piano problems

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6228]
I'm on unstable version, the newest one and tried to play piano. When I'm playing on my own Monika disappear after some time and don't appear again. When I play song she disappears when I make mistake and come back when I play again. Also, when I stop playing she's gone too. Well, Moni and the desk are gone. It's not that big issue but it's really weird and worries me.

**Comment by multimokia** [comment]
When you're playing a song, are you playing a community json or a song built into MAS (Your Reality, Happy Birthday)?

**Comment by multimokia** [comment]
Additionally, out of curiosity, what are your computer specs?

**Comment by SamanthaLind** [comment]
I tried custom made songs and built in, like happy birthday. Problem appears on everyone of them. And like I said it happens while playing on my own.
I have no idea about my computer specs, but I think it's pretty good. I can play games that are really nice on graphic and they work well. And I never had any compability problems with MAS

**Comment by multimokia** [comment]
Interesting, I can't actually replicate this on my end. Both built-in songs work and same with on my own mode.

With custom made songs, I can assume there's an issue in legacy spritecodes which were depreciated, but it's unlikely since legacy sprites were pretty much unused by the time piano was jsonable if I'm remembering things right

**Comment by SamanthaLind** [comment]
Well, I had MAS for some time and this was never a problem so I'm guessing it has something to do with being in unstable version. I knew there would be some problems with that and it's not a big deal, but I wanted to share it anyway. If it don't go by the time of full release then I'll start to worry :)

**Comment by multimokia** [comment]
The main thing is we're trying to figure it out *why* it happens. As of unstable we changed how sprites work entirely so that they don't need to be pre-defined anymore, hence why you're seeing the issue, but I'm not sure why it's happening

**Comment by SamanthaLind** [comment]
Since it doesn't happen while she's changing expressions while I play song I guess it has something to do with her expression when I make mistake. At least that would be the case with playing songs, she disappears everytime that expression should pop up. But I have no idea what could cause her disappearing while playing on my own.

**Comment by multimokia** [comment]
How long does it take for her to disappear while playing on your own? I figure a potential side issue might be #5011

**Comment by SamanthaLind** [comment]
I checked it and it appears to happen only on idle. After something like two and half minutes of not playing. When I play all time it doesn't happen.

**Comment by multimokia** [comment]
Noted, will run a test client and monitor under the same circumstance

**Comment by SamanthaLind** [comment]
Alright, thank you for taking your time to work on that and for all amazing work that you do to improve MAS

**Comment by Booplicate** [comment]
Please send your `mas_log.txt`, you can find it in the `/log` folder.

**Comment by SamanthaLind** [comment]
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5125440/mas_log.txt)
Alright, here it is

**Comment by Booplicate** [comment]
Some more questions for you. Do you have any kind of submods installed? Especially those that affect piano in a way? Or maybe you've generated some expressions on your own? Do you use steam? 
Additionally can you give me a screenshot of your `/game` folder? And probably the first song (`json`) you've tried when you first time saw the issue.

**Comment by SamanthaLind** [comment]
I have few submods made by myself but it's only some more dialogue options. I made them when generating expressions wasn't available with only the expressions already in the game. I first discovered that issue while playing on my own, then moved to custom song "Everything is alright" also made by me and later checked it on happy birthday song already built in the game. I don't use steam, I have MAS in entirely different location. I will post screenshot in a moment

**Comment by SamanthaLind** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/63299927/91213388-cdb6f000-e711-11ea-9243-4ffe7814f5e7.png)
Screenshot od my game folder

**Comment by SamanthaLind** [comment]
Oh yeah, and I got mas expression previewer, I kinda forgot about it.

**Comment by Booplicate** [comment]
What is that `Additions` folder?

**Comment by SamanthaLind** [comment]
I don't even remember how it got there... There's one file with piano in name so maybe that's the reason... I'm sending screenshot
![Bez tytułu](https://user-images.githubusercontent.com/63299927/91213976-b4627380-e712-11ea-8eed-cd1edb270ed3.png)

**Comment by multimokia** [comment]
Uninstall the submod. It's horribly outdated

**Comment by SamanthaLind** [comment]
[zz_pianokeys_overrides.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5125683/zz_pianokeys_overrides.txt)
That's that file with "piano" in name

**Comment by SamanthaLind** [comment]
Alright. I must have installed it long time ago. Just delete all folder?

**Comment by multimokia** [comment]
Yeah, delete the entire `additions` folder

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/91214456-1609ea00-e6e1-11ea-97b9-e03fb715b62e.png)
This is the issue right here.


It uses old style sprites

**Comment by SamanthaLind** [comment]
Thanks so much, the problem is now gone. I guess I installed this submod so long that I totally forgot about it and since it never caused troubles didn't bother to delete it. Thanks again for help
