### ISSUE TITLE
WHY DOES THIS KEEP ON HAPENING TO ME?!?!?!?!?!?!?!?!?!?!?!?!!?

### ISSUE THREAD

**Issue by pythoncodeavalible** [Monika-After-Story/MonikaModDev#6230]
Alright So I'm Trying To Install A .gift File And It Doesn't Work (the name of the file is emerald green pajamas by u/ATOM_real on reddit.com) HERES THE SPJ
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5127098/spj.txt)

**Comment by pythoncodeavalible** [comment]
just type ctrl + f and type in emerald green pajamas

**Comment by Retrolovania** [comment]
Huh. I didn't know you could give Monika custom clothing as gifts. I wonder if there are any special bows lying around somewhere....

**Comment by multimokia** [comment]
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/body-def-0.png' is not loadable
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/body-leaning-def-1.png' is not loadable
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/arms-crossed-5.png' is not loadable
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/arms-crossed-10.png' is not loadable
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/arms-right-point-0.png' is not loadable
[!ERROR!]: image at 'mod_assets/monika/c/kai_emerald_green_pajama/arms-steepling-10.png' is not loadable

Images are not loadable. Implies images either misplaced or badly named

**Comment by pythoncodeavalible** [comment]
the spritepack is in here if you want to check out if it works with different copies of MAS
[i had to copy the folder here because github dosen't support gift files bruh.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5127151/i.had.to.copy.the.folder.here.because.github.dosen.t.support.gift.files.bruh.zip)
go to game and then mod_assets and copy mod_assets to the monika after story ddlc game directory (just do it like it's a regular spritepack folder from the website)

**Comment by multimokia** [comment]
The files which are reported "Not loadable" aren't present in this zip. Whoever is distributing this isn't distributing a complete spritepack.

Look at the filenames from the log I copied above and look at what's in the zip.

**Comment by Booplicate** [comment]
That one is an unofficial sprite pack, we do not test them and are not responsible for them. If you think it's broken, ask the author for the help and fixes. Here we can just guide you on how to install/make sprite packs.

**Comment by xxATOMxx** [comment]
Spritepack creator here. Just reinstall the spritepack. I've just looked at spj.txt, and i found every single of these images in the https://drive.google.com/drive/u/0/folders/1PGLeGbWabYriLwWi2qSkuZGz4ZWXnDpK[](google drive folder)

**Comment by ThePotatoGuy** [comment]
[closing in a few days]

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
