### ISSUE TITLE
Custom Spritepack Not Working

### ISSUE THREAD

**Issue by SimpingForMonika** [Monika-After-Story/MonikaModDev#6232]
name of the spritepack you are trying to install: Pansexual Flag Twin Ribbons
name of the gift you are trying to gift: pansexualflagtwinribbons.gift
the log including the spritepack: [info]: reading JSON at 'c:\users\abarn\downloads\ddlc-win\ddlc-1.1.1-pc\game\mod_assets\monika\j\kai_acs_pansexual_flag.json'...
[info]: loading ACS sprite object 'kai_twinribbon_pansexual_flag'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'kai_twinribbon_pansexual_flag' loaded successfully!

I'm not sure what went wrong, but Monika can't read the gift.

**Comment by multimokia** [comment]
send the full spj please

**Comment by SimpingForMonika** [comment]
Sorry! 
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5127824/spj.txt)

**Comment by multimokia** [comment]
`  [info]: using generic reaction for ACS sprite 'kai_twinribbon_pansexual_flag', giftname 'pansexualflagtwinribbon'`

you appear to be using an incorrect giftname.

**Comment by SimpingForMonika** [comment]
Oh, I must have read the drive wrong (the first time I tried to do it, I moved the gift file itself, which was silly of me). Thanks!
