### ISSUE TITLE
[Suggestion] - Goodbye: "I am taking you to school." 

### ISSUE THREAD

**Issue by Cloverhood** [Monika-After-Story/MonikaModDev#6233]
As I hope we get a variety of different places we can say we are taking Monika to, I'll suggest where I take her the most- my  high school. It of course does not have to specifically be stated you are taking her to high school because you know- wide range of fans. (not to mention Monika usually knows the player's age/birthday at this point so she could probably guess what grade the player is in)
I have a few ideas to start off with for this suggestion
Monika when you tell her that you are taking her to your school she lights up at the concept of taking classes with the player
When you get back, she would do what she normally does when the player comes back from school (Ask how it went) but with a little bit of extra dialogue thrown in as she was there with you.

**Comment by Freshairkaboom** [comment]
Maybe we could have an additional menu when you say you're going to take her somewhere, where you can say either "to school", "to movies", "to library" etc. or have an option where you can say "I don't know" or "It's a surprise". Then, when you return, if you chose the two latter options, she will ask where you took her. I think this will be more encompassing of many different places that you could take her, and then she can imagine being there with you and comment on it. I think that would be really romantic, don't you? :)

**Comment by Booplicate** [comment]
I think we're planning to expand the "I'm going to take you somewhere" farewell. You'll get a choice to take her with you in all the other farewells. One of the first steps was generalization - #5957.

**Comment by Freshairkaboom** [comment]
I like that much better

**Comment by Cloverhood** [comment]
I agree, that sounds great!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
