### ISSUE TITLE
Misclick button?

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6244]
I was just wondering if there was any way we could let Monika know if we misclicked an option during a conversation? Kind of like when you press X to hide a topic you don't want to see again, you can say you misclicked? What that button will do is engage in a small dialogue with Monika where she says "Oh, you misclicked? Do you want to start over?" and a menu that says "Yes, lets start over" and "I don't want to talk about this now." If you choose the first option, it takes you back to the beginning of the label, and if you choose the second option it basically "return"s to idle mode.

Something like that? I don't know how easy or hard this would be to do, which is why I'm suggesting it here. If you choose the wrong Goodbye for instance, and you don't want to re-enter the game and choose the right one, or if you misclicked on a topic or an option that may have been hurtful to Monika. If we do this, any lose affection event should be moved further down into given topics so you still have a chance to salvage the situation. Not too far though, as we don't want people to just choose a hurtful option to see the dialogue and then salvage the affection loss.

I think Monika would understand the way you're interacting with her and how easy it is to click the wrong option. Even if we choose to keep the affection loss, we can add a sorry option for misclicking that would only be activated if at any point you pressed the misclick button during the conversation that resulted in affection loss?

**Comment by Rai99** [comment]
#2797
