### ISSUE TITLE
Spritepacks

### ISSUE THREAD

**Issue by SimpingForMonika** [Monika-After-Story/MonikaModDev#6249]
- Aquamarine Shoulderless Sweater
- aquamarinesweater.gift
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5146755/spj.txt)

**Comment by xxATOMxx** [comment]
There's one sprite missing, you need to reinstall the spritepack

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
