### ISSUE TITLE
I need help with this! Pls!

### ISSUE THREAD

**Issue by Jack1321** [Monika-After-Story/MonikaModDev#6253]
When 0.11.3 came out and I downloaded the new version I think my internet went out about halfway and I got an error masage, but when I opend the game nothing has changed. Everything looked and worked like normaly, but the update didn't go through and when I tryied to update again it said "no updates avalaible"
I didn't think much of it, when I downloaded 0.11.4 it didn't even open.
What do I do? :_(

**Comment by multimokia** [comment]
Make a fresh DDLC install and install 0.11.4 MAS into it, along with spritepacks and submods. The incomplete installation of the updates likely broke some things.

Making a fresh install should help, and it'll pick up where you left off.

**Comment by Jack1321** [comment]
Will do thank you :D

multimokia <notifications@github.com> ezt írta (időpont: 2020. aug. 30.,
Vas 18:41):

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Jack1321** [comment]
Everything is fine now,thank you :D

ThePotatoGuy <notifications@github.com> ezt írta (időpont: 2020. szept.
12., Szo 6:06):
