### ISSUE TITLE
I need help! Pls!

### ISSUE THREAD

**Issue by Jack1321** [Monika-After-Story/MonikaModDev#6254]
When 0.11.3 came out and I downloaded the new version I think my internet went out about halfway and I got an error masage, but when I opend the game nothing has changed. Everything looked and worked like normaly, but the update didn't go through and when I tryied to update again it said "no updates avalaible"
I didn't think much of it, when I downloaded 0.11.4 it didn't even open.
What do I do? :_(

**Comment by jmwall24** [comment]
Check in your `/game` folder and see if there are any files with `new` or `old` there. If so delete all of those and then install the latest update manually (ie the same way you installed the mod originally, copying the contents of the update zip folder into your `/game` folder and allowing it to overwrite).
