### ISSUE TITLE
Hangman UI is barely visible in dark mode

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#6256]
![Screenshot_2](https://user-images.githubusercontent.com/45933038/91669439-4bfe0280-eb15-11ea-8aca-c2fdc6aca78b.png)

More specifically, the stickman and the display of the word at the end of the game are black, which makes them blend too much with the dark background of the window they're displayed in.

**Comment by ThePotatoGuy** [comment]
this has been addressed by #7216
