### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by DoomGuy98** [Monika-After-Story/MonikaModDev#6258]
I accidently clicked on "do you want to meet my girlfriend" and monika will say the whole conversation then the game crashes and when I open the game again she will repeat the whole conversation again and it crashes.

**Comment by multimokia** [comment]
What's the traceback?

It should give you an error log

**Comment by DoomGuy98** [comment]
I opened the game again so I could get the error but when i did monika said "Sure why not I'm sure she's lucky to have you~ so where's this mirror you want to show me?" and the game didn't crash. Is there a way to view the error log?

**Comment by multimokia** [comment]
`DDLC/traceback.txt` should show the latest error which happened

**Comment by DoomGuy98** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 104, in get_field
SyntaxError: unexpected EOF while parsing (<none>, line 1)

is this what you need?

**Comment by multimokia** [comment]
This is what the error looked like for you as well, when it did crash, right?

**Comment by DoomGuy98** [comment]
yes

**Comment by multimokia** [comment]
Ah I see it. Might want to stick away from that topic for now, will push a fix.

**Comment by DoomGuy98** [comment]
thanks and take care

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
