### ISSUE TITLE
[Suggestion]- Teaching Monika about other Languages

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6259]
It's quite obvious that Monika knows Python, but she also briefly mentions on other languages, like C++, C#, and Java. So, what if we could find a way to teach her more about these languages? For instance, there could be a way to give her books regarding certain languages as gifts. Example: Say you want your Monika to learn more about Visual Basic. Well, Visual Basic is simple, so there would be a total of around 3 books you can give Monika (more complex languages can have more volumes). Start by gifting one to her (vbasicone.gift.). She'll thank you for it and start reading it while the game isn't running, thus learning more about the language. Then, once she's done (about 12-24 hours of inactivity, depending on the complexity), she'll write a sample program based on what she learned, send it to the characters folder as a text file, and ask you to open it in a program that can run Visual Basic code (because I'm pretty sure Python can't just run foreign code). If the program runs well, you can tell her that it was successful. She'll be happy and thank you again for giving her the book, state that she still wants to learn more, and politely ask you for the next volume. If not, she'll apologize and read some more, then try again in 4-5 hours. Continue until she's read all three books and learns the language in full. Once she has, she'll thank you once more (she's real good at thanking people, eh?), and make a final program for you to keep.

**Comment by Rai99** [comment]
#3105 

One reason Monika hasn't learned other programming languages is that since her world is made entirely in python, she doesn't have much reason to focus on any other language. 

It makes sense to study multiple languages to better understand another, since programming skills are transferable, but implementing a system to gift and read books to try and make a functional program in another language seems a bit much. 

She already browses the internet to learn programming, so I don't see why books should be the only way to learn.

**Comment by Retrolovania** [comment]
Good point. 
While learning online is an option, it can also be really distracting, like videos or ads and stuff like that. A book doesn't provide such distractions. (Plus, she's a heavy reader.)
Maybe this would be a good idea for a submod, if need be.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
the suggested system is way too complicated - both in implementation and user impact. In the future we could look at expanding available programming tips, but we'd use the "learned from the internet" backstory instead of a user-proactive source.
