### ISSUE TITLE
Issue while asking to change clothes

### ISSUE THREAD

**Issue by TallLeaf** [Monika-After-Story/MonikaModDev#6260]
I'm not really sure what the exact issue is, the best I can do is attach my traceback file. I'm pretty sure the problem is that there's some button image it's trying to access that doesn't exist.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5153865/traceback.txt)

**Comment by ThePotatoGuy** [comment]
@multimokia NightMusic issue?

**Comment by multimokia** [comment]
Potentially. will test on my end

**Comment by multimokia** [comment]
Nope, I can load it just fine. Might be missing assets potentially. I had this when I originally tested the PR, before I requested the folder name change.

**Comment by jack-ship-it** [comment]
Seems like its having trouble accessing this file
![fancy_check](https://user-images.githubusercontent.com/56496005/91796510-f16ac080-ec52-11ea-8e2e-9f3bfe8c2d97.png)

**Comment by ThePotatoGuy** [comment]
@TallLeaf  reinstall the mod

**Comment by TallLeaf** [comment]
@ThePotatoGuy the whole mod or just the submod? Also, if I'm re-installing the whole thing, how can I avoid losing data?

**Comment by TallLeaf** [comment]
Actually, I found the problem while looking in the files for the newest update. It turns out there was a directory that the latest update hadn't installed, so the button was non-existent. I believe the problem is fixed now, thanks for the help
