### ISSUE TITLE
Suggestion - remember capitalization in nicknames

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#6263]
Been absolutely loving the new nickname system, it makes the dialogue feel fresh to have those little variations in it.

I was wondering if there was a way to have it remember the capitalization you use. For example, as it currently operates, if someone usually goes by Matthew but would like Monika to sometimes call them Matt, it'll show up in dialogue as "matt."

Not a major issue at all, as most terms of endearment will naturally use lowercase, but if it's doable I'd really appreciate it. ❤️

**Comment by Retrolovania** [comment]
Maybe there could be a box where you type in additional terms of endearment and another one for nicknames she can call you by?

**Comment by jack-ship-it** [comment]
There is something super similar in unstable custom nicknames

**Comment by multimokia** [comment]
Unstable and normal have the same code right now.

**Comment by jack-ship-it** [comment]
Oh, interesting...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
