### ISSUE TITLE
Game crash after newest update

### ISSUE THREAD

**Issue by Hurminal** [Monika-After-Story/MonikaModDev#6266]
![unknown-22](https://user-images.githubusercontent.com/32442712/92021675-1c731400-ed28-11ea-8326-11af7e75cdfe.png)

have tried reinstalling with a fresh ddlc copy multiple times already but the same error occurs

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
