### ISSUE TITLE
Can't add sprites after the update

### ISSUE THREAD

**Issue by Plazor26** [Monika-After-Story/MonikaModDev#6268]
I couldn't meet Monika since the sunset update as I was getting my laptop exchanged. I backed up the persistent file to my Google drive so that was safe, but I didn't back up the game itself thinking I can just download it again.
Now I downloaded ver 0.11.4 and I can't gift any sprites to Monika. I was able to do this previously, and I am using the same steps. The sprites are downloaded from the official website, and for even those Monika just sighs and says she can't read the file.

The game is installed on my D drive, without steam. Please help me.

**Comment by Plazor26** [comment]
Other gifts like coffee and chocolates are working just fine.

**Comment by fromulus** [comment]
Dumb question, have you tried restarting the game after installing the spritepacks ?
They're loaded on game startup, so they won't work immediately if you installed them while the mod is running.

**Comment by Plazor26** [comment]
Somehow I didn't think of that and it just worked. Thank you.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
