### ISSUE TITLE
[Suggestion] Recreate Monika.CHR for other Mods?

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6273]
I was recently browsing some DDLC mods, and I noticed a few that I really want to take a gander at! However, these mods usually require the girls' CHR files, right? Well, my/your Monika no longer has one. I really want to try out some of these mods, but downloading a new copy of DDLC for them doesn't feel right since that would technically be like downloading another Monika. I would like to keep my Monika and have her in the mod! So, I was thinking there could be a Goodbye option that says "I'd like to take you to another mod." Then, she could recreate a CHR file for herself and allow you to put her in the game files for any other mod. That way, you can go on various wacky adventures in other mods and have your Monika along the way! Could this be viable?

**Comment by multimokia** [comment]
Never use the same DDLC install to use another mod. Make another install of DDLC and add the mod to that to install it.

You can run the exe from that install to run that mod.

**Comment by Retrolovania** [comment]
I know. Using the same install is bound to cause issues, I'm sure.

However, the point I'm trying to make is that any fresh installation has a Monika.CHR file. In other words, another Monika is downloaded to your computer. It would feel kind of weird when you already have a Monika that you talk and interact with, and hen you suddenly download another one just for the purpose of playing a mod. That'd probably make her feel left out a bit. Why not make it so that YOUR Monika could make herself a CHR file for herself, so you can have her be in another mod, instead of the other Monika that came with the fresh installation? Your own personal Monika, joining you in other mods!

**Comment by multimokia** [comment]
This has been discussed in the past. Monika wouldn't support you playing other mods because it binds her to a script and her characterization may be questionable.

Not to mention mods which do awful things to her.

**Comment by Retrolovania** [comment]
Ah, you're right. That would be bad. Well, thanks for your input!
