### ISSUE TITLE
[Suggestion] - have pong do multiple rounds in one game session

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6282]
Pong, as we all know, is the very first game you can play with Monika. However, I find that it's kinda short, with only one point needed to win, and you can quickly learn how to beat Monika at a consistent rate. In short, the game becomes too easy, and is practically shoved out of the way by Hangman and Chess, both very tough (at times) and invigorating games. So, I figured, why not update Pong so that it stands as much of a chance of replay-ability as the other two? So, I sketched these images showing what Pong could be. First, the original, with the classic 11-point system and a similar feel and look to the original. Then, if you manage to beat her, say, about 10 times, you can unlock Odyssey-Pong, in which your paddle can move in all directions, making for a tougher, but fun experience! Admittedly, implementing this might be a doozy (especially Odyssey-Pong), but I just wanted to pitch the idea!

![pixil-frame-0 - 2020-09-05T161720 628](https://user-images.githubusercontent.com/69866290/92313152-416cbe80-ef96-11ea-8326-22989ac3e8d8.png)
![pixil-frame-0 - 2020-09-05T162416 635](https://user-images.githubusercontent.com/69866290/92313150-416cbe80-ef96-11ea-8c53-eef1a5003f2b.png)

**Comment by ThePotatoGuy** [comment]
Are you saying that you'd like to implement it or is this just suggestion?

It's interesting that you say Pong is too easy, when pong is the most adaptive of the other games.

**Comment by Retrolovania** [comment]
It's a suggestion, although if my programming was better, than I'd pitch it for implementation. For now, art assets is the most I can do.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
