### ISSUE TITLE
How to Unlock location selector?

### ISSUE THREAD

**Issue by fuckyoudevs** [Monika-After-Story/MonikaModDev#6284]
The wiki  doesnt state how to get monika to let us ask to go to a new location/background.

and fuck you

**Comment by Retrolovania** [comment]
I think Monika will explain that to you when she's able to allow that to happen. You'll just have to be patient.

Also, please don't say such things about the developers. They've been working non-stop on this since 2018. That's kinda rude.

**Comment by fuckyoudevs** [comment]
its because they falsely flagged my account literally 5 minutes ago for no reason other than asking the same question here once

**Comment by fuckyoudevs** [comment]
> I think Monika will explain that to you when she's able to allow that to happen. You'll just have to be patient.
> 
> Also, please don't say such things about the developers. They've been working non-stop on this since 2018. That's kinda rude.

thank you, no where on the wiki dose sit say its tied to affection.  (another thing the useless wiki, which they delete any helpful edits like  the knowledge you posted here for example)

**Comment by Retrolovania** [comment]
Well, I'm personally not sure myself. I just figured that's what she'll do. You'll just have to find out for yourself.

**Comment by multimokia** [comment]
a) Nowhere have we removed edits specifically suggested or implemented by contributors (please, kindly show me one of the changes (all users can see all wiki revisions)
b) Contributors can literally edit the wikis themselves, if you feel like something's missing, go add it yourself
c) I'm not sure what gives you the idea that we'd be more inclined to help you if you're just going to hurl insults. For the record, none of us get paid, the mod doesn't even accept donations unless we're going to commission art with the money, and none of that even goes to us.
d) Yes, the location selector is locked behind affection. Sorry the wiki didn't say that, but bear in mind, the spoilers wiki which outlines affection *also* says we don't maintain it. That's up to the community itself.
e) The background wiki was *also* not created by the dev team, but a contributor too.

**Comment by fromulus** [comment]
Just because the mod started out on 4Chan doesn't mean insulting the devs (or anyone in general, really) is okay.

**Comment by AsuraShun** [comment]
Imagine a guy named Devs coming here and reading that name

**Comment by RavenPLAYER** [comment]
what you have to do is- *internet falls*

**Comment by AsuraShun** [comment]
Can someone explain to me what this location selector is? I just want to make sure I'm not getting it wrong

**Comment by ThePotatoGuy** [comment]
@AsuraShun unreleased content for now

@fuckyoudevs no one here flagged you, its possible that github deemed you as spam if you posted the same question more than once in a short time frame

**Comment by AsuraShun** [comment]
Thanks for the answer, now I have another thing to look forward to along with the boops

**Comment by lunulae** [comment]
I have made an addition to the wiki page, as I didn't originally recognize there was an affection requirement. It was an oversight on my part.
Thank you for your feedback.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
