### ISSUE TITLE
[Suggestion] New Game: checkers

### ISSUE THREAD

**Issue by letoking77** [Monika-After-Story/MonikaModDev#6285]
To be honest I am much better a checkers then chess. (So far have yet to win.) but in my opinion might be a nice break from chess 
(hopefully I made this a suggestion correctly...) and would be a fun game that's like chess but not and has the same board so it might be easier to put in. (I think.)

**Comment by Rai99** [comment]
Checkers: #829, #1629, #2014, #3221, #4913
