### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by opalmew** [Monika-After-Story/MonikaModDev#6289]
i recently updated monika after story and when i try to boot up the game, i get this message:

"[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/updates.rpy", line 377, in script
  File "game/updates.rpy", line 409, in <module>
NameError: name 'mas_loseAffection' is not defined"
is there any way to fix this?

**Comment by Booplicate** [comment]
Just press `Ignore`.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
