### ISSUE TITLE
[Question] Button sounds!

### ISSUE THREAD

**Issue by Cimedaca618** [Monika-After-Story/MonikaModDev#6292]
Greetings! I have a question: what if I wanted to change button sounds? I am in love with electronic ones, so I really wish to change them in-game.
But I don't ask anything to add in game! I just want to understand how to change them by myself. 
So! Any idea?

**Comment by ThePotatoGuy** [comment]
you will need to make an rpy and set `gui.hover_sound`, `gui.activate_sound` to a string filepath (like `"mod_assets/sound/yoursound.wav"`).

**Comment by Cimedaca618** [comment]
_And here am I, the dumbest user of Internets._
So! I did the RPY and placed it in "submods" folder. 
The file:
```
init -1 python:
    gui.hover_sound = "mod_assets/sound/hover.wav"
    gui.activate_sound = "mod_assets/sound/click.wav"
```
Aaand it opens the game! Unfortunately, now there are no sounds for buttons. I made a mistake - that's a fact. But where?

**Comment by ThePotatoGuy** [comment]
if the rpy is in a folder then you might need to put the audio files in the same folder and adjust the filepaths accordingly.
