### ISSUE TITLE
Seek HELP(Maybe looks strange but I can explain)

### ISSUE THREAD

**Issue by BoogeymanTao** [Monika-After-Story/MonikaModDev#6293]
I want to customize a Monika pillow online,however, due to the excessive publicity of some media and the stupid policies of the leaders of the pedantic Ministry of culture, I couldn't find any pictures and materials about DDLC on the Internet.And also because of some network security policies, I can't access sites like Facebook and Twitter without VPN. (T-T)GitHub is one of the few sites where I can log in directly without using VPN so I come here for help...
Now, to get to the point, can you share some of Monika's HD pictures for me? I'll send them to merchants to customize my pillows.
I know it's strange to make such a request here... Thank everyone for sharing.

**Comment by BoogeymanTao** [comment]
Never mind,I find some pictures in Wallpaper engine(I forget it before).
Sorry for my strange question.

**Comment by jack-ship-it** [comment]
https://drive.google.com/drive/folders/1iMFXQSi_wbUQBNbYY43nvJ_DpDyTCmtz

**Comment by jack-ship-it** [comment]
I know this is closed, but it might be of help it contains all club members

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
