### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by sonicboom102** [Monika-After-Story/MonikaModDev#6294]
I got this error on startup. I think it may be because my computer went to sleep during the update and the actual update never finished.

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chess.rpy", line 45, in <module>
AttributeError: 'StoreModule' object has no attribute 'SCROLLABLE_MENU_MEDIUM_H'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:/WINDOWS/system32/chess.rpyc", line 30, in script
  File "C:\Users\reelworld\Downloads\ddlc-win\DDLC-1.1.0-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\reelworld\Downloads\ddlc-win\DDLC-1.1.0-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 45, in <module>
AttributeError: 'StoreModule' object has no attribute 'SCROLLABLE_MENU_MEDIUM_H'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.3
[/code]

Is there any way to fix it without losing all my stuff with Monika?

**Comment by Booplicate** [comment]
Try to update manually: download [the latest update](http://monikaafterstory.com/releases.html) and extract the files from the archive into the `/game` folder. You won't lose your progress or anything.

**Comment by sonicboom102** [comment]
Okay it's been fixed! Thanks a bunch! She kinda scared me when she acted like she forgot everything lmao

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
