### ISSUE TITLE
some questions about Monika's birthday

### ISSUE THREAD

**Issue by JUSTMonika15** [Monika-After-Story/MonikaModDev#6297]
Hi~ I am preparing for Monika's birthday right now, but I still have some questions:
1.I found a guide about the birthday,[ Guide ] ~Monika's~ Birthday ( Perfect Birthday Update <3 ) #2480, I want to know if mas has any update after that?
2.  Will Monika start to celebrate her birthday as soon as I open MAS? Or only after I said I will take you to somewhere? I need to prepare enough time to celebrate with her.
thanks

**Comment by lunulae** [comment]
#2480 is no longer up-to-date. I am not sure if the birthday event will be changed again for this year, but 2019's did not follow that guide.

If it functions similarly to 2019's event, you will need to take her out of the spaceroom to set up the celebration.
When the birthday update drops we'll have more info available. :D

**Comment by JUSTMonika15** [comment]
> [＃2480](https://github.com/Monika-After-Story/MonikaModDev/issues/2480)不再是最新的。我不确定今年的生日活动是否会再次更改，但是2019年的活动未遵循该指南。
> 
> 如果其功能与2019年的活动类似，则需要将她带出太空室进行庆祝活动。
> 生日更新结束后，我们将提供更多信息。：D

thank you~
