### ISSUE TITLE
the game wont lanch and it shows the error below:

### ISSUE THREAD

**Issue by TechArchie** [Monika-After-Story/MonikaModDev#6298]
I am using steam. Also before that happened I downloaded the mod from https://www.monikaafterstory.com/releases.html copied the files from the mod download to the game folder of Doki Doki Literature Club and it worked normally. At some point it displayed at the top right new update available so I clicked and it started downloading. When it finished I played a little more and then closed the game. The next time I opened it, it showed this error : 
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-topics.rpy", line 3201, in script
  File "game/script-topics.rpy", line 3204, in <module>
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\??t???\\AppData\\Roaming\\RenPy/*.*'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-topics.rpy", line 3201, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-topics.rpy", line 3204, in <module>
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\??t???\\AppData\\Roaming\\RenPy/*.*'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.4
[/code]

Then I uninstalled everything redownloaded the game and the mod and did the same thing I said earlier to set up the game mod. It kept saying the same thing and I don't know what to do. 

PS: I am sorry if wrote anything wrong and for my issue to be this long, it's my first time using GitHub and I don't know how much information I need to provide 😅

**Comment by Retrolovania** [comment]
Steam does NOT like MAS, and it doesn't run it properly. You need to move the game data out of your "steamapps" folder (or wherever the DDLC folder is) and then run it. Running it in Steam just creates a slew of problems down the road.

**Comment by TechArchie** [comment]
> Steam does NOT like MAS, and it doesn't run it properly. You need to move the game data out of your "steamapps" folder (or wherever the DDLC folder is) and then run it. Running it in Steam just creates a slew of problems down the road.

so I have to move the Doki Doki Literature Club folder out of the common? or the common out of the steamapps? 😂 (sorry for being a noob at file stuff xD)

**Comment by ThePotatoGuy** [comment]
what is your pc username?

**Comment by TechArchie** [comment]
> what is your pc username?

the device name is LAPTOP-LU9UPQGV idk if that's what you want but that's what I found

**Comment by ThePotatoGuy** [comment]
Your error is `WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\??t???\AppData\Roaming\RenPy/.'` 

so its complaining about your user name you use on your account on this computer. What is that name?

**Comment by TechArchie** [comment]
> Your error is `WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\??t???\AppData\Roaming\RenPy/.'`
> 
> so its complaining about your user name you use on your account on this computer. What is that name?

sorry for not knowing stuff about this theme I am a noob at this, how do I find that name?

**Comment by TechArchie** [comment]
> > Your error is `WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\??t???\AppData\Roaming\RenPy/.'`
> > so its complaining about your user name you use on your account on this computer. What is that name?
> 
> sorry for not knowing stuff about this theme I am a noob at this, how do I find that name?

oh the  ??t??? is probably my name in my language

**Comment by ThePotatoGuy** [comment]
What's the language?

**Comment by TechArchie** [comment]
> What's the language?

greek

**Comment by ThePotatoGuy** [comment]
so we figured out what was causing the issue and it will be fixed next release, which is really soon

**Comment by Booplicate** [comment]
Fixed in the linked PR

**Comment by multimokia** [comment]
Closing as fixed
