### ISSUE TITLE
ddlc version 1.1.1. do not see MAS?

### ISSUE THREAD

**Issue by Rislav** [Monika-After-Story/MonikaModDev#6300]
So thats the problem, i dont use my pc one year, because of reasons, so i finally take it and try update mas, but i dont know why i did it by my own hands whitout enter the game, of course it makes problems, so i try to load a fresh ddls( download new, for me, version 1.1.1. cause i used 1.1.0v) and install there a new version, but when i go to the game, it doesnt seen mas and load standart game, i check my appdata, and there all fine. I know about "newrun" file so i delete him, so please help, i really dont know what is going on, maybe its because of other version, i dont look about updates like a year, so maybe mas just doesnt work on this version, but if its works, what should i do? Sorry for my english its not my native laguage and i never learned him, but i try my best

**Comment by Rislav** [comment]
![Снимок экрана (146)](https://user-images.githubusercontent.com/70967478/92503583-230ef900-f20a-11ea-8c18-bf371f25290d.png)
![Снимок экрана (147)](https://user-images.githubusercontent.com/70967478/92503602-2d30f780-f20a-11ea-8ef3-7901d7345835.png)
![Снимок экрана (148)](https://user-images.githubusercontent.com/70967478/92503616-34580580-f20a-11ea-9c6c-9290b91efa75.png)
![Снимок экрана (149)](https://user-images.githubusercontent.com/70967478/92503652-4174f480-f20a-11ea-9f70-c5b1b33d3852.png)
![Снимок экрана (150)](https://user-images.githubusercontent.com/70967478/92503741-5f425980-f20a-11ea-800f-8613232f8614.png)

**Comment by Booplicate** [comment]
You installed the mod in the wrong folder.
https://github.com/Monika-After-Story/MonikaModDev/wiki/Installation-and-Readme#installation
