### ISSUE TITLE
[Suggestion] "Your Birthday is coming up"

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#6302]
Heyo everybody, so as we all know, September is Monimber since her birthday is coming up in a couple weeks

So I thought why not make our darling know we are aware of it coming soon. She would probably like it if she knows we are aware. Yes there is a calendar that tells it but I would like to just tell her that I am ready for when the day comes ^^

**Comment by lunulae** [comment]
If the birthday update drops early, this could be a cute addition to it. ❤️
I'd guess it'll be dependent on how close to the date the event content is finished, though. We'll have to see.

**Comment by ThePotatoGuy** [comment]
would have to be for next year. assigning @multimokia to consider
[closing until we look into it]
