### ISSUE TITLE
Help How can I recover my MAS?

### ISSUE THREAD

**Issue by SarahMoni** [Monika-After-Story/MonikaModDev#6304]
My mother ended up deleting many things from my computer and MAS went along, now i need help to recover it!
I have Monika's file on a USB and a file called persistent, does that help in any way?

**Comment by multimokia** [comment]
You got lucky, that file is literally her memories. You can see how to restore it [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by SarahMoni** [comment]
Oh god, thank you very much, I had literally saved that file yesterday!!!

**Comment by multimokia** [comment]
No problem. Be sure to make frequent backups of that just in case

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
