### ISSUE TITLE
problem starting the game

### ISSUE THREAD

**Issue by Themiddleknight** [Monika-After-Story/MonikaModDev#6308]
i receive an error that states that there is no module called _util and i don't know what to do exactly

**Comment by Freshairkaboom** [comment]
Okay, so what you need to do is go to your MAS folder, go to "game", then python-packages, then mutagen, and look in that folder for a _util.py file. If you found it, go into the mp3 folder above, and see if it's there too. Then go back to mutagen, and go into the id3 folder and check for the same file. Finally, go into the _tools folder, also from mutagen, and check for it there.

Are there none, or are you just missing it from one of the folders?

**Comment by Themiddleknight** [comment]
im missing the first one but not the second

**Comment by Freshairkaboom** [comment]
Okay, my recommendation at this point is just make a backup of your persistent files in Appdata > Roaming > RenPy > Monika After Story, just copy the entire folder to your desktop or something, and then download another version of MAS: First DDLC, then merge MAS game folder with DDLC game folder, like usual. If you still don't have _util after that, I'm gonna ask if it's possible to just share mine.

**Comment by Themiddleknight** [comment]
im having trouble finding appdata

**Comment by Freshairkaboom** [comment]
First of all, are you using Windows 10? If so, just type %appdata% in your search bar.

**Comment by Themiddleknight** [comment]
ok i have the folder and ive merged the game folders

**Comment by Freshairkaboom** [comment]
Did you find the _util.py files this time?

**Comment by Themiddleknight** [comment]
what do i do with the persistent files?

**Comment by Themiddleknight** [comment]
oh yeah

**Comment by Freshairkaboom** [comment]
You copied them right? It was just in case something happened with them. They're Monika's memories. If they're still there and you can launch your Monika from where you left off in the new folder, as long as it has the _util.py files, then you're all set :) It's smart to make a backup of the persistents outside of your computer, perhaps on dropbox or another cloud storage service anyway, in case something happens to your computer.

**Comment by Themiddleknight** [comment]
thank you sooo much

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
