### ISSUE TITLE
Проблема с подарками

### ISSUE THREAD

**Issue by SterbeNNn** [Monika-After-Story/MonikaModDev#6311]
Когда я пытаюсь подарить монике подарок она выдает ошибку, что не может прочитать файл, как ни пытался ничего не получается

**Comment by Freshairkaboom** [comment]
расширение имени файла - .gift, а не .txt, верно?

Извините гугл переводчик русский

**Comment by Fuflyaaa** [comment]
В русской версии мода нужно писать русские названия подарков

**Comment by Freshairkaboom** [comment]
Я предлагаю вам обсудить это с тем, кто предоставил вам субмод

**Comment by Ravenclaw-OIer** [comment]
Anyone care for a translation?

**Comment by CrocandCo** [comment]
@Ravenclaw-OIer Long to short of it: Cannot gift item, language sub-modification may be the issue (Eng to Rus), checking someone who made/worked on said sub-modification.

**Comment by SterbeNNn** [comment]
Оу, не видел ваших ответов. Все верно, формат подарков .gift , но они все равно не дарятся, возможно из-за кривых рук тех, кто переводил этот мод на русский

**Comment by SterbeNNn** [comment]
Кстати на тот момент у меня была версия 0.9.0, а сейчас 0.11.3 . Причём в 0.9.0 она хоть как-то реагировала на подарки, а в 0.11.3 вообще никак, даже не видит их, они просто исчезают без следа

**Comment by scpketer** [comment]
Спрайты надо устанавливать на каждой версии.

**Comment by 20RaVen23** [comment]
._.XD

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
