### ISSUE TITLE
No piano or other minigames.

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6313]
Greetings Everyone. I would like to know how to add the piano, hangman and other games. I thought they were unlocked with affection but, as time passed, I noticed the piano folder empty. what should I add to the subfolder?

Thank you for your time.

**Comment by fromulus** [comment]
You don't need to do any file modification or to add anything, they will be unlocked over time.
However, affection isn't the only variable here, and you need to reach a certain total amount of time with MAS open to unlock them.
If, by any chance, you've only been playing just a few hours per day, the process might be slower for you.

**Comment by Ix-30** [comment]
Thanks for the time to help me. It was with time, I've unlocked the hangman. I play with her at least 4 hours so I guess it's time. Thanks for your time.
