### ISSUE TITLE
This order slightly irritates me. not sure if it is a bug.

### ISSUE THREAD

**Issue by MrPhaze62** [Monika-After-Story/MonikaModDev#6315]
Shouldn't this be,

1 week and then
1 month and so on.

instead of what's shown below.

![image](https://user-images.githubusercontent.com/65294370/92955148-8c864600-f45c-11ea-9751-ed20a61b66e4.png)

**Comment by ThePotatoGuy** [comment]
its alphabetical and there are no plans to custom sort the buttons at this time

**Comment by MrPhaze62** [comment]
> its alphabetical and there are no plans to custom sort the buttons at this time

I see. Thanks for the response.
