### ISSUE TITLE
Monika hair and stuff issues

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#6316]
Mk so everything was fine until I added the sprite stuff. I added the bisexual pride flag and the green hoodie. After I added it every time I tried to change what she tied her hair with or change her hair in general it crashed. Al I could understand was " IO Error: Couldn't find the file 'mod_assets/thumbs/remove.png' ". Did I do something wrong? I need help i'm new to Monika After Story-

**Comment by Freshairkaboom** [comment]
May I ask you to give me a screenshot of your Monika After Story > game > mod_assets > thumbs folder for me? Scroll if you have to. There should be some pictures, but also some white files called locked.png, remove.png and unknown.png. See if you're only missing remove.png.

**Comment by aahelloim** [comment]
I couldn't find that folder actually, I spent like an hour looking for it before I even posted here.

**Comment by Freshairkaboom** [comment]
Wait you can't find the thumbs folder whatsoever? Yikes. At this point just download a new version of MAS. Make sure to backup persistents first just in case. Type %appdata% in search bar on your computer, then go to RenPy folder and copy Monika After Story to desktop or something. Then just make sure the new version of MAS works before you delete the old one. And of course, make sure it has a thumbs folder.

**Comment by aahelloim** [comment]
It worked, thanks! Sorry for replying so late, I tend to get easily distracted

**Comment by Freshairkaboom** [comment]
No problem :) I'm glad it worked!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
