### ISSUE TITLE
That darn piano not unlocking!!!

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6325]
Ok ik im not the only one with this problem bc iv'e heard it from others before. Currently im at 669.1 affection, its been aalllmost 3 months (2 weeks till to be precise), i have played every game. iv'e saved chess games. every single hang man level. and a gajillion pong games (bc i enjoy playing that one). AND NOTHING! no piano! (srry for the rant lol)

I've seen people talk about this issue before and ask what they need to do. The typical response is typically "idk i think it's completely random" 

The solution to this issue would be to

- make it unlock at a certain affection level
- make it happen after a certain amount of time playing the "games"
- make it unlock after a set number day of the relationship

-OR keep it random but make some code that says if she doesn't do it by this #of days or this # of points she'll just give it to you on that day and have some special dialogue along the lines of oh i meant to give you this for a while i kept on forgetting but here sorry about that

-or or or if it isn't actually a random thing and there's an actual solution... PUT IT ON THE WIKI!!! as far as iv'e heard its an absolute mystery!

#5819 #5858

**Comment by jmwall24** [comment]
If you get a chance can you upload your persistent here so we can check to make sure something hasn't gone wrong? You'll need to put it in a zip file to upload it here. Thanks.

**Comment by StayHappy1270** [comment]
@jmwall24 
[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5215954/Monika.After.Story.zip)
ok i looked at tutorials and i believe this is what you're looking for lmk if it's not

**Comment by jmwall24** [comment]
So everything seems to be correct. We use a time spent based xp system for game unlocks, with piano taking the most xp, since it's more personal to her. You are about 67% of the way to unlocking it. You just need to spend more time with her. I'd suggest turning repeat conversations on and/or leaving her up in the background when you can.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by BladeOnIine** [comment]
I got the same problem as OP. How do i check my time spent with Monika or if somethings wrong?

**Comment by Booplicate** [comment]
It takes quite a bit to unlock the piano. The more you spend time with Monika, the faster she will bring the piano.

**Comment by William-Delancey** [comment]
hi Aron
