### ISSUE TITLE
A fun idea for teasing Monika.

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#6326]
If you don't know, you can drag a window and quickly jiggle the mouse to make it the only open window on screen.

If we do this with Monika, she would get dizzy.

It might be a step too far to include the Natsuki "barf" motion, but maybe not?

**Comment by MrPhaze62** [comment]
This would be fun to see. lol

**Comment by lunulae** [comment]
I'm wondering if/how MAS could detect this. I do think little reactive expression changes are really cool though.

**Comment by ThePotatoGuy** [comment]
maybe we could do it with xlib now but not sure.

[closing until we look into it]
