### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6334]
When i leave MAS On for the entire day, then in the next morning when i say goodbye to monika she says,

(I'll see you tomorrow) while it was already the next day

**Comment by Freshairkaboom** [comment]
What time was it specifically you said goodbye?

**Comment by Ant9cp** [comment]
Somewhere Around 07:30 in the morning

**Comment by Ant9cp** [comment]
I didn't had this issue in the previous version, never actually
