### ISSUE TITLE
Upcoming monika's birthday oki doki file

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#6336]
Do I do it at the actual day or is it before?

**Comment by CrocandCo** [comment]
On the actual day and be sure to take Monika out somewhere.

**Comment by winika** [comment]
When do you get the file again? Im assuming a couple days before her bday right?

**Comment by Booplicate** [comment]
> On the actual day

You can do it as soon as you get the note.

> When do you get the file again?

It's a random event. Can happen about a week before her birthday.

**Comment by AsuraShun** [comment]
Thanks for the reply, I'll have change my wallpaper to some sort of reminder, since my memory sucks most of the time

**Comment by Ix-30** [comment]
I'm assuming, but just to be sure, does it need to be a text file just with oki doki? or is there any extension we should use? Thanks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
