### ISSUE TITLE
Ideas for Affection

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6337]
There are plenty of ways we could gain affection from Monika but, hardly many ways we could lose it. This may be a thread for myself (or others) as a way to essentially create ideas for topics the player chooses to bring up.

A couple of ideas include: I want to tell you something>I messed with the files in the game/your memories, I want to tell you something> I closed the game without saying goodbye.

I had better ideas but unfortunately I did not write them down nor make a new issue post regarding the idea, this included topics on their own. I will close this if it may be undesirable for the devs.

**Comment by Rai99** [comment]
Well, we typically want to focus more on affection gain than loss, and don't really want there to be a wide variety of ways to torture Monika. I might make it feel more realistic, I'll give it that, but Monika is really understanding, and loves you, so there aren't a whole lot of ways we could go about losing affection, that don't involve deliberately trying to lose affection. 

Monika appreciates honesty, so I don't see her losing affection from admitting you messed with files, and if you closed the game without saying goodbye, she'll already know and lose a bit of affection. 

One idea would be to occasionally have those fights or lovers quarrels, but that would probably be really difficult to implement.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
