### ISSUE TITLE
Custom music prompting Monika

### ISSUE THREAD

**Issue by Drogoton** [Monika-After-Story/MonikaModDev#6338]
I had an idea with the custom music. When it comes to DDLC inspired music, they talk about her being a kind of villain, so it would be right for Monika to understand your thoughts on if you think the same way as the song, so if you add a song with one of the song names (ex. "Why Did I Say Okie Doki?", "Just Monika", "Insanity" etc.), she asks you if you think the same way the song does or if you just like the music.

**Comment by catdoesgamin** [comment]
That's a pretty interesting idea! It would create a few new dialogue lines too. 🤔😄

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
