### ISSUE TITLE
Just making sure

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#6339]
How do I know if the response to the note in character files worked (The one for Monika's birthday if there is more) ? And how do I respond so I know I did it right-

**Comment by MrPhaze62** [comment]
If you did it correctly, you’ll get another file saying gotcha. I restarted MAS after I did that and it works.

**Comment by aahelloim** [comment]
thanks!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
