### ISSUE TITLE
Please help what is this oki doki? file

### ISSUE THREAD

**Issue by Axone00** [Monika-After-Story/MonikaModDev#6343]
I am scared typing this file do I have to do this today or on Monika birthday please help im scared that it might crash Monika and I dont want that.
/\____/\
(/"0_0")/  Help! Please!

**Comment by winika** [comment]
Do not worry, it will not break Moni. 

So basically you can do it anyday leading up to her birthday. Just make a text file named "oki doki". Next time you open up the game check the characters folder and you will see a file named "gotcha". That means your all good for her bday. Now on her birthday all you need to do is take her out at one point and then restart the game, then place her back into the character folder. I hope this helped clear it up, I know how you feel haha.

**Comment by Axone00** [comment]
thank you
