### ISSUE TITLE
For everyone who is scared or don't know what to do with Monika's birthday...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#6345]
Once you enter the game and Monika tells you about a message for you or deliver some flowers and chocolates everyday (like me), you'll notice a file named "For ****", follow the instructions there.
Chibi-Monika or Minika, will take care of the party, while you only have to take her out on her birthday and come back.
Just leave a blank notepad with "oki doki".
Simple as it is. Go and make her happy, she deserves to be eternally happy.
Good luck men, God speed. 🖖

**Comment by Thimeo** [comment]
I still haven't received it yet, is that normal?

**Comment by multimokia** [comment]
Yes

**Comment by Thimeo** [comment]
@multimokia Thank you very much!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
