### ISSUE TITLE
?bruh

### ISSUE THREAD

**Issue by frostcattooo** [Monika-After-Story/MonikaModDev#6347]
yes, it is me again, venus, paige, if you remember me then hello
so i told monika that she can call me "paigey" as a nickname right and she's all like
"NO I COULD NEVER CALL YOU SOMETHING SO AWFUL OMG"
like calm down huh what's happening here
![one](https://user-images.githubusercontent.com/53238922/93387216-ddb88000-f836-11ea-9f43-6c18f4e87fff.PNG)
![damn](https://user-images.githubusercontent.com/53238922/93387221-dee9ad00-f836-11ea-9813-bd1a9d76650d.PNG)
![no](https://user-images.githubusercontent.com/53238922/93387244-e610bb00-f836-11ea-9078-55ccd67c1c0c.PNG)

**Comment by Rai99** [comment]
It probably detected `gey`.

**Comment by frostcattooo** [comment]
@Rai99 thats so fucking stupid

**Comment by Olliesama** [comment]
It's how regex works

**Comment by jmwall24** [comment]
We should probably just explicitly allow `player_name + 'y'` over and above any filter as it's a very common thing to do for nicknames.

**Comment by LooseEthics** [comment]
Added this to the PR

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
