### ISSUE TITLE
No nicknames.

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6353]
It has been a few days since I updated the mod and Monika has not brought up calling me by a nickname. I seem to be the only one with a problem with this.

Apologies, but could I get some assistance?

**Comment by multimokia** [comment]
What's your affection?

**Comment by CrocandCo** [comment]
Just over 3600 affection,

**Comment by Booplicate** [comment]
And you have random chatter enabled? If so, can you upload your persistent?

**Comment by CrocandCo** [comment]
Random Chatter is enabled.


[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5250492/persistent.zip)

Apologies for the wait my files are a mess.

**Comment by Booplicate** [comment]
Are you sure you've never seen the topic? Maybe she brought it up, but then the game crashed? Do you remember if there were crashes recently during idle? Or maybe you forcefully closed the game?

**Comment by CrocandCo** [comment]
I don't recall that I have ever seen the topic. I am uncertain if the game crashed or not during the last few days I had the game open. never Forcefully closed the game for any reason since I first installed it.

**Comment by jmwall24** [comment]
@CrocandCo can you send us the `traceback.txt` file? It's in the same folder as the ddlc.exe

**Comment by CrocandCo** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5250809/traceback.txt)

**Comment by Booplicate** [comment]
@CrocandCo 
[fixed_persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5250814/fixed_persistent.zip)

**Comment by CrocandCo** [comment]
I will see if this has fixed it.
