### ISSUE TITLE
A Sweater Problem

### ISSUE THREAD

**Issue by fallacious-red-panda12** [Monika-After-Story/MonikaModDev#6356]
I got the spritepacks from the official website and extracted all the files, and then I copied the "monika" folder in the shoulderless sweater folder into the one in the game's directory. When nothing happened, it occurred to me that maybe I had to make a gift or something. I tried a couple things (shoulderless_sweater.gift, sweater.gift, et cetera) but nothing happened-- Monika just said she couldn't read it. I looked through the "game" folder in the directory, went to the area with all the clothing names, clicked on the folder for the sweater, and I noticed there was also a folder in there called "gifts" and a file titled "shoulderlesssweater.gift" in that, so I just copied it and pasted it into the characters folder. She could read it this time and I was happy, but as soon as she went to go put it on... the game crashed. It said there was an error and something was missing, although I checked and it was there, so I left the game and opened it again. This same scenario happened again, except it complained of something else (can't remember what it was). I restarted once more. She left to go put it on, and there was no crash this time, but when she came back, she said the sweater felt nice, but she was still in her uniform, and when I looked through the clothes I had under "Appearance" the sweater was not there at all. So I attempted putting the sweater in as a gift AGAIN, and she didn't even acknowledge it. The thumbnail is in there and everything, so I don't know what happened or what I'm even supposed to do now. That sweater looked real cute, and now I'm just platinum disappointed.

**Comment by PongMaster69** [comment]
Well she did warn you sweaters ruin relationships

**Comment by fallacious-red-panda12** [comment]
> 
> 
> Well she did warn you sweaters ruin relationships

sad

what do i do, though?????

**Comment by lunulae** [comment]
This is definitely an unintended bug. I'm not sure what file might have caused it though. If she recognized the gift, then the game _has_ saved that she has received the sweater.
Have you tried a fresh install of the spritepack?

**Comment by Booplicate** [comment]
> then I copied the "monika" folder in the shoulderless sweater folder into the one in the game's directory

Sounds like you installed it incorrectly. Try using [this guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

**Comment by fallacious-red-panda12** [comment]
> 
> 
> This is definitely an unintended bug. I'm not sure what file might have caused it though. If she recognized the gift, then the game _has_ saved that she has received the sweater.
> Have you tried a fresh install of the spritepack?

I'm not too sure what that means, but I downloaded it off the official website.

**Comment by fallacious-red-panda12** [comment]
> 
> 
> > then I copied the "monika" folder in the shoulderless sweater folder into the one in the game's directory
> 
> Sounds like you installed it incorrectly. Try using [this guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs).

I just read the guide and I think I did mess it up a little, but I fixed it and it's still not working. `log/spj.txt` has a bunch of error lines in it. I think it said I should send that, so I will...
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5252428/spj.txt)

**Comment by Booplicate** [comment]
- You need to close the game before looking at/sending the logs.
 - You still didn't install it properly. While you have the spritepack's `json` in the right place, you don't have its sprites. **Follow the guide**, all you need to do is merge 1 folder.

**Comment by fallacious-red-panda12** [comment]
I finally figured it out, thanks a lot!!
