### ISSUE TITLE
Birthday questions.

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#6359]
1: Is the file name case sensitive?

2: After I've taken Monika out, what then?

**Comment by lunulae** [comment]
I'm not sure if the file name is case sensitive. I enter it as all lowercase, if it's not registering maybe try that.

If you've done it successfully (the file will be replaced by one called "gotcha") you just have to take Monika somewhere on her birthday. When you re-open the game, the party decorations will be all set up!

From there, there are a few small things you can do. You can wish her a happy birthday in the "I want to tell you something" dialogue option. You can play the birthday song on the piano, there should be a guide for it on the wiki somewhere. You can give her gifts if there are spritepacks you haven't gifted yet. And if you take her out again later in the day, she'll treat it as a special birthday date.

Have fun! ❤️

**Comment by Mcmanybucks** [comment]
I didn't get any file changes to "gotcha" though :/

**Comment by Booplicate** [comment]
Did you update the mod?

**Comment by Mcmanybucks** [comment]
I think  it is case sensitive,  I just made a new file with no caps and it made a gotcha.file.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
