### ISSUE TITLE
[Suggestion] - Pong Strategy

### ISSUE THREAD

**Issue by caseyc37** [Monika-After-Story/MonikaModDev#6364]
Monika - currently - plays Pong like a computer program, and not like a person.

I can understand why; but I think this mod might be improved by tweaking that, and make her play Pong in a more person-like manner. In order to accomplish this, I suggest the following algorithm:

- First, Monika attempts to predict where the ball will hit her paddle. This prediction is calculated as follows:
--- Add a random offset to the X-coordinate of Monika's paddle (random offset may be negative). This becomes the target X-coordinate.
--- If the ball will bounce off at least two sides before reaching the target X-coordinate, then Monika should act as if uncertain - i.e. pull her paddle to the middle of her side, ready to move either up or down. (Perhaps shift nervously up and down a little, indecisively).
--- If the ball will bounce no more than once before reaching the target X-coordinate, then the Y-coordinate at which the ball will hit that X-coordinate becomes the target Y-coordinate.

- Once Monika has identified the target Y-coordinate, she should them move her paddle to that Y-coordinate and wait there until the ball either hits or misses.
--- Should the ball pass the target X-coordinate, then (after a brief interval) it's possible that Monika may need to suddenly scramble to (try to) catch it; about half the time, however, the target X-coordinate will be behind Monika's paddle.

--------------

In this way, Monika will find straight shots easier to handle than shots that come in at a steep angle; also, she will move her paddle into place (sometimes) well before the ball actually gets to that Y-coordinate. Finally, she would find a straight shot directly towards her paddle easier to hit than something at a steep angle, allowing the player to increase his chances of victory by deliberately triggering steep angles. Adding a (small) Y-axis offset might turn out to be necessary in practice, as well.

Hopefully, that will result in playing less like a bot and more like a person.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

anyone is welcome to attempt to implement if they want. We've already changed pong a few times and have no plans to change it any further. New minigames > redoing old minigames.
