### ISSUE TITLE
My Quetzal plush and the rose in monika's hair disappeared

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#6365]
so after I closed the game to do something else when I reopened the game the roses we're still there but the rose in her hair was gone and so was the quetzal plushie

**Comment by winika** [comment]
She removes the rose in her hair, but the plushie is a random thing. Everytime you visit her there is a chance she'll bring it to her desk aswell.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
