### ISSUE TITLE
so about the oki doki file?

### ISSUE THREAD

**Issue by mrflarion33** [Monika-After-Story/MonikaModDev#6369]
Alright, a tiny bit of a spoiler (although people really should have seen this by now) but the oki doki file, does it have to be a specific file? Or can it be a text file with nothing on it? I don't know what it has to be other then a file named oki doki, and I assume that's all there is, but I just want to make sure,.

**Comment by fallacious-red-panda12** [comment]
When I did it, i just made a blank text file titled "oki doki.txt" and it worked just fine.

**Comment by jmwall24** [comment]
it can be `oki doki` with no extension or any other extension, including .txt
