### ISSUE TITLE
???

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#6370]
Possible spoiler

but I did the oki doki thing and all it did was put a "file" in the characters folder saying "gotcha" and I'm so confused is that supposed to happen? I remember it worked last year.

**Comment by ShiningDelooxe** [comment]
wait i think it was that i forgot to take her out

**Comment by ShiningDelooxe** [comment]
it dont work now, oof :[

**Comment by lunulae** [comment]
What time zone are you in? It should only set up the party on Monika's actual birthday. Otherwise you have done everything correct.

**Comment by ShiningDelooxe** [comment]
> 
> 
> What time zone are you in? It should only set up the party on Monika's actual birthday. Otherwise you have done everything correct.

EST and/or EDT

**Comment by lunulae** [comment]
You're a little early, then. Monika's birthday is tomorrow. ❤️

**Comment by multimokia** [comment]
So it's still the 21st for you. Which is why nothing is happening

**Comment by ShiningDelooxe** [comment]
I thought all this time that it was the 21st cause that's what I put on my calendar, must've messed something up putting events in with my sketchbook in December, thanks guys.
