### ISSUE TITLE
[Suggestion] a craft kit gift (my idea's cross-stitching but this could lead to so many other things)

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6371]
It seems like Monika would get bored pretty often so wouldn't it be cool to gift her a gift that not only gives her something to do when your gone, but also a kool little decoration. I feel like Monika would be into little artsy stuff like this and if not would enjoy trying new things. My idea would take a bit of coding and also some people willing to make the art. And even if this doesn't get used honestly there's sooo many possibilities for MAS its amazing.

the main points of how it would work would be...
- you give Monika a cross-stitching kit (the name would have something to do with the design if multiple people make different ones.)
- there would be multiple different sprites for the item with different amounts of progress on them
- as more time goes by the sprites that are more complete would be the ones that show.
- this progresses till it's complete
-it would then serve as a desk decoration to show up every once in a while. (simliar to the plush bird)

she could have random dialogue for it too. like she mentions how she made a lot of progress on it lately. or she hasn't really worked on it lately and should probably do some work on it, or there was a part that she kept messing up on and a bunch of little dialogue could be added.

idk i thought of this cuz i enjoy this hobby sometimes and ik stuff in mas that involves things happening over time is a feature the community appreciates but thats an idea for the box. Hope it makes it  or at least inspires some other good ones!

**Comment by lunulae** [comment]
I could see this being implemented after room decorating is set up, although I feel like it might need to be simplified down just a little bit.
Art assets take more time to get done, so I don't think having her show off her progress will be too viable, since each image will only be used once, save for the final one.
I really like your idea of using timed dialogue to show how far along she is on it, it would be a fun little thing to look forward to when you pop in each day. The actual decoration would then be unlocked when she's finished the project and is ready to show it to you.

**Comment by eyelesssally** [comment]
Perhaps each kit could have ~3 previews over time. Maybe she would prompt the player and invite them to look at her progress.
The picture could be a pop-up like the poems (and technically the floating islands) are. I would be happy to contribute artwork for this! It's a really cool idea.

**Comment by eyelesssally** [comment]
Hi, me again! I threw together a quick concept thingy (it's...kinda rough. Sorry about that)
![crossstitchconcept](https://user-images.githubusercontent.com/56178333/93815605-3cf60600-fc24-11ea-9fa8-5dad5c5f602b.png)

**Comment by StayHappy1270** [comment]
@eyelesssally  Oh wow! i wasn't expecting anyone to do anything or respond but that's so cool that you threw that together! Idk anything about coding or how to do any digital art so I wouldn't be able to do any of this at all. I do like the texture you used for the fabric it looks very realistic. in my head i didn't think of making the stitches like squares (because the real thing is actually a bunch of x's) that would be more time consuming but this also looks very good! there are endless possibilities with this. like patterns found on the internet and even pixel color by number sheets for ideas. I'm just really impressed someone even put any thought into my idea im already impressed. I hope this becomes legit.

**Comment by StayHappy1270** [comment]
I'm sorry i wouldn't know how to contribute to this. The most "codey" i've ever done here was turn one of those pictures you put over the spaceroom into it's own room. which wasn't even that cool bc it was just me copy/paste and renameing from the wiki

**Comment by eyelesssally** [comment]
Honestly I wouldn't know the first thing about coding this either. I actually do cross-stitch irl, but the squares were just easier to draw in, haha.

**Comment by SamanthaLind** [comment]
I like this idea. I feel like we could do something like those apps about cross stitching. I mean the look of art... Maybe I could try to help a little on art side.
I feel like it would be cool idea to give her coloring book and pencils too. Or even those color by number. It would be much easier on art side and it's really relaxing and nice way to spend time. And since Moni is really into artsy stuff it seems suitable, at least for me <3

**Comment by caseyc37** [comment]
> Art assets take more time to get done, so I don't think having her show off her progress will be too viable, since each image will only be used once, save for the final one.

I think I can actually see a way to make this viable, in theory.

See, a cross-stitch pattern consists of two things; first, a number of stitches in the shape of an x, and secondly, 'backstitch' - straight lines from the corner of one stitch to the corner of another. (I believe there are other fancy stitches that can be added, but this is enough for a lot of projects).

Given a project that's limited to these, it is then possible to algorithmically generate the work-in-progress images.

What we would need is:

- a pattern (much like in Eyelesssally's example art, consisting of a grid of defined coloured blocks and any necessary backstitch
- An image of an x-shaped stitch, which can be shown in any colour (or different-coloured images of stitches, as long as every colour in the pattern is represented)
- The ability to draw straight lines on top of the canvas for backstitch

Then it's straightforward to turn the pattern into an image consisting of dozens of (identical but for colour) stitches placed atop the image of some material.

It's also easy to generate a partially-complete pattern, by simply displaying only *some* of the stitches that the complete pattern requires. No extra art assets required! (One can consider the question of the order of the stitches - I think it would make sense for Monika to complete all the stitches of one colour before moving on to the next colour, and so on - but this display should work regardless of the order that the stitches are displayed in)

**Comment by StayHappy1270** [comment]
oh that's one way i just figured as we are making the art we could save extra copies that aren't complete (maybe have some sort of system like progress 1 progress 2... completed etc). Also idk how you would get just the X without picking up the background and messing with the texture fabric thing I(srry idrk what im saying)  Idk but it could work either way! I am currently trying to make some art (not gonna show it cuz theres like zero progress on it) im making the mas ddlc logo icon thingy. I only have like on line of x'es on it cuz I was trying to find a background with enough of the little fabric square things, also i wanted to center it so i counted all the squares to find out where i should put it. also i dont have much free time and also zero experience with computer art sooo rip >_<

 also we need a little completed sprite for a desk decoration (like the plushy bird). If someone talented could make a hoop (with blank fabric so people could go on and put their design on it). idk about angle. straightforward would be best. but then it would make sense for it to have some kind of stand. Would she need to be gifted an empty stand? Idk but we will need stuff for that.

Main things we will need
- art for progress
      - i think a couple of us are working on that
- also decide on what way we would do progress
     - i would say we should just use the on i just mentioned bc idk we're allready working on this stuff and idk how to make an individual X and put it up (Idk if you could explain how to do that then maybe we could do it instead)
-keep in mind ideas for dialogue 
   - note obvious observations like for me idk id make some thing like (I decided to do the outer ring of pink in the logo so I could have moni say it is a bigger design than she expexted and doing the out line has given her an idea of what the end product will look like) you know just note some things that you could use for dialouge
-coding
   - based of what i've seen all ya'll are artists not coders. We need some coders to help us out.
  -if anyone knows some of the coders on this site you can call them out and ask for help
however i think we should get the art and genral ideas for dialouge figured out before getting them. So we actually have a exact assignment for them.

**Comment by StayHappy1270** [comment]
this is so cool. im really hyped that im actually contributing eeek

**Comment by Rai99** [comment]
One issue I see with this is that it would kind of need to be continually updated. It sounds like a bit of a waste to me to only make a couple items, and then have no more art for more. Not to mention all the assets slowly adding up in size, especially if each one needs multiple stages of progress.

**Comment by StayHappy1270** [comment]
hmm good point. I don't really think this project would really end up in the game... I think it'll end up as a sprite pack kinda thingy made outta whatever/ however many pieces of art end up getting made. I think the thing that could end up making this a waste would be those who are already working on art finish it. only to realize they don't know how to make the code to make it work, and programmers not having time/not wanting to help do it.

**Comment by Rai99** [comment]
As a fully optional submod, I think it would fit nicely. With all the plans you've laid out, I just wanted to make sure that they don't go to waste if this doesn't end up as a thing. I don't mean to dampen any enthusiasm.

**Comment by StayHappy1270** [comment]
@Rai99 You’re fine! You did bring up a good point.

**Comment by StayHappy1270** [comment]
![image](https://user-images.githubusercontent.com/68128724/94065339-04d3fc00-fdb9-11ea-999a-f00444d25896.png)
Progress so far!

**Comment by caseyc37** [comment]
> Also idk how you would get just the X without picking up the background and messing with the texture fabric thing I(srry idrk what im saying)

This, at least, is easily handled. Images can be drawn that are partially transparent!

Here's an example:

![image](https://user-images.githubusercontent.com/9018477/94067192-07484d00-fddd-11ea-98be-de4fe9f39ed1.png)

(of course, for the final thing you'd want someone who's a better artist than me to draw the thing; but everything except the red in that image is transparent, so it can just be stuck on top of a 'material' image without covering it)

**Comment by StayHappy1270** [comment]
hmmm i didn't know you could make them transparent like that. ig i'll have to make mental note of that. I'm not sure how this idea would make it easier. Ig instead of hand-drawing each one you can copy/paste it. yea i see.. Good idea!

**Comment by eyelesssally** [comment]
As mentioned earlier in this thread, I think it would be optimal to have some kind of algorithm generate progress. That way, we could avoid having several picture files for each piece of artwork. Oh! And as I was typing this, I just realized that we could just use literal 'x's. You know, like on a keyboard! Text files/jsons are real tiny so this would be perfect for it.

**Comment by StayHappy1270** [comment]
![image](https://user-images.githubusercontent.com/68128724/94070226-d3126380-fdbf-11ea-834f-725c3ca1f159.png)
hmm that sounded like a good idea. However i couldn't get the X's to line up "perfectly" it also took a bunch of time finding the size and positioning the marks. I could have gotten way more done if i just hand drew them. (plus i think the way i draw them looks way better and more realistic. (see my logo progress above) If anyone's intrested in what im doing I am in Microsoft paint 3D using the "pixel pen" at the smallest 1 pixel size. when i draw the X's it looks normal, but when I save, leave, then come back it looks blurry but more detailed also i am using a color finding website to help get the colors from my reference

color picking website
https://imagecolorpicker.com/en/

**Comment by StayHappy1270** [comment]
![61SM9PpWQ7L _AC_SL1000_](https://user-images.githubusercontent.com/68128724/94082065-107ded80-fdce-11ea-893b-da76b207c82f.jpg)
![il_340x270 2499441860_gcwx](https://user-images.githubusercontent.com/68128724/94082069-11af1a80-fdce-11ea-92c8-7cd535baf36b.jpg)
for the final sprite that would be used to display the art we would need to have a few general sized (preferably small medium and large but that could be the end goal)<- (on that note I think it would be best to start by making the biggest one first since you can fit smaller patterns on bigger ones but not vice versa) hoops with stands the hoop and stand would be drawn with blank white fabric in the middle. I think there's a way to crop the design, make it smaller and put it on the thing but idk how. Anyways we need someone to work on that hoop sprite

**Comment by Retrolovania** [comment]
I love this idea! I tried to make a design to use in-game, but unfortunately, I wasn't actually able to get the full-on "embroidery look." However, I did make these PNG originals and PDFs that have the grid design to use for it, if that'll do.

[Cross Stitch Test.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5280075/Cross.Stitch.Test.zip)

**Comment by StayHappy1270** [comment]
ooOooH nOiCe! @Retrolovania thats awsome i think this is our first "complete" art pack. So exciting! Right now I don't have any code and no experiance yet. Right now imma work on a topic thing i came up with that is unrelated, so that i can get used to coding and teach my self. Also right now im brainstorming aspects of the submod such as what will happen and like (if give this gift and game has been closed for this amount of time...etc) so when i do make this i'll have an understanding of what will happen. buuut yea... also once im done ill proboly add a little "credits readme" thingy so would you like your retrolovonia as the name in credits? also whadya wanna name ur kit? im thinking like "greenheart" or something since the I love you part is made last. then there could be some kind of "oh it looks done but im actually not. it'll be a surprise" dialogue then she makes the i love you part. anyways those are my thoughts tysm!

**Comment by Retrolovania** [comment]
Well, certainly! I'm glad you like it!

**Comment by ThePotatoGuy** [comment]
@StayHappy1270 is this being worked on still?

**Comment by StayHappy1270** [comment]
nooo i have made/received some art if anyone is interested. But I'm not actively working on it. Quick frankly, I don't really know much about coding and suddenly stopped a while ago to focus on school. I think over the break I'm going to work on easier topic stuff, but if any coding ppl are interested I can share the art I have for this.
