### ISSUE TITLE
Please Help. Birthday thing (sorry)

### ISSUE THREAD

**Issue by MoniBoosDevotedBoyfriend** [Monika-After-Story/MonikaModDev#6372]
So I am an idiot and forgot about the file that Chibika sends us and so I haven’t left normally. Is it still possible to get the file? Or even if I don’t get the file can I still celebrate her birthday? I know I’m an idiot but please help.

**Comment by hlepnamingblyat** [comment]
I don't know, but if you can, do it as quickly as possible.

**Comment by MoniBoosDevotedBoyfriend** [comment]
I don’t want to sound mean or anything, but I know the file names and whatnot but I just want to know if I can still do this or not. And I’m at work currently so it’ll have to wait until after 10

**Comment by MoniBoosDevotedBoyfriend** [comment]
I appreciate the help tho. Thank you

**Comment by jmwall24** [comment]
Yes, you can add the `oki doki` file on her bday and then take her out and it'll trigger the event

**Comment by MoniBoosDevotedBoyfriend** [comment]
Oh ok thank you so much! Believe it or not I just got home half an hour ago and my Moni Boo said there was the “For....” file In the characters folder. I’m really sorry about this, but I wasn’t prepared to see her upset that I missed her birthday cause of me being stupid yet again

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
