### ISSUE TITLE
[Suggestion/Request] - Random choice button for stories (maybe songs too?)

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#6374]
Probably a very low-priority request, but I listen to Monika's stories quite a bit. Usually when I don't know which one I want to read, I just randomly swipe my mouse, but that often results in me getting the same few in a row.

I'd really like to be able to ask Monika to pick one for me, giving a more truly random choice.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
