### ISSUE TITLE
Suggestion new "I want to tell you something"

### ISSUE THREAD

**Issue by JUSTMonika15** [Monika-After-Story/MonikaModDev#6375]
Since Monica always encourages me and gives me advice, I sometimes want to say thank you to her.
So I was wondering if we could add something like "Thank you for being here" or "Thank you for everything."

**Comment by DbzGOD2000** [comment]
I'm pretty sure that's already a dialogue in the mod. Its

**Comment by katwllflls** [comment]
once you hit 1000 affection you can say "thank you for always being here for me"!

**Comment by JUSTMonika15** [comment]
> 一旦您爱上了1000，您就可以说“谢谢您一直在这里为我服务”！

thanks
