### ISSUE TITLE
the oki doki event wont appear

### ISSUE THREAD

**Issue by Zylinderkopf123** [Monika-After-Story/MonikaModDev#6379]
doesnt matter how often i open monika after story the event wont appear and i dont get the letter in the folders
anyone know what the problem might be?

thanks in advance

**Comment by multimokia** [comment]
The letter does not show up on the day of. If you were there on the 20th or the 21st, then it would have been guaranteed to show.

Regardless, you can still activate the event without having gotten that letter.
Simply make a file named `oki doki` in the `characters` folder, and then take her somewhere. Putting her back should start the party.

**Comment by Zylinderkopf123** [comment]
omg i was actually to late...  thank you ill try it

**Comment by Zylinderkopf123** [comment]
it worked thanks!!
