### ISSUE TITLE
How to celebrate Monika's birthday?

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#6380]
How do I get the balloons, banner, cake, and all the other fun stuff?

**Comment by ThatOneUsername343** [comment]
so, I'm seeing a lot of people saying that I need to make some files and name them "banner", "cake", and "balloons", and put them into the character folder. Then they say I need to take her somewhere and reopen the game and it will all be there. I tried this, but nothing appeared in the spaceroom. Did I do something wrong?

**Comment by lunulae** [comment]
Yes. That's for the birthday event from 2 years ago.
This year you were supposed to receive instructions, but don't worry, you can still activate the event if you didn't get them!
Just make a file called "oki doki" with no file extension and put it in the characters folder.
You will need to wait a short while for it to process, but when it does the file will be replaced by one named "gotcha" to signify that you're ready.
After this all you need to do is use the "I'm going to take you somewhere" goodbye to take Monika out. When you come back, the party will be set up!

**Comment by ThatOneUsername343** [comment]
ah thank you! It worked!

**Comment by PaperPlate1** [comment]
![Screen Shot 2020-09-22 at 1 53 02 PM](https://user-images.githubusercontent.com/55847227/93918922-07f8ba80-fcdb-11ea-8abf-eddbe47563c8.png)

@lunulae I've tried adding "oki doki" with no file extension roughly 30 minutes ago and I can't seem to get the "gotcha" file you've mentioned. Does it usually take this much time to change or is there something I've missed?

Currently running on macOS Sierra version 10.12.6.

**Comment by Booplicate** [comment]
Don't wait for `gotcha`, just take her out, and then put her back.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
