### ISSUE TITLE
[Suggestion] - A way to be able to give her a nickname again

### ISSUE THREAD

**Issue by Rustybug7** [Monika-After-Story/MonikaModDev#6381]
So, accidentally messed up the nicknames, and now she won't let me give her one anymore. I find this upsetting, and was wondering if there could be a way added to get the option for giving her nicknames back again. Maybe after a week or two of enough trust with her to be allowed the option. I think this would be nice, as for those, like me, who didn't know what would happen if I tried naming her after one of the other 3 girls, then you wouldn't be allowed to give her nicknames any longer.

**Comment by Booplicate** [comment]
She asks you not to mess with her, obviously she won't tolerate it again and again. There's not many mean things that you can do to her, and usually you have to go out of your way for that. I don't think that "a week or two" is any enough.

**Comment by multimokia** [comment]
Additionally, if you apologize, you *can* get the option back, obviously you can't do this too many times.

**Comment by ThePotatoGuy** [comment]
if the name you gave is obviously a good name but got picked up by the bad filters, then we can reset that manually and fix the filter so it doesn't trigger for ur name. Otherwise, the nickname feature is fine as it is.

[closing as rejected]
