### ISSUE TITLE
Urgent help needed,I took monika for a ride and shes not back despite me restoring her character file

### ISSUE THREAD

**Issue by LorenzoHerreros** [Monika-After-Story/MonikaModDev#6382]
I was going to celebrate monikas birthday.
I took her out on my pendrive, set up the cake, balloons and banners, went to work, and after coming back i restored her character file (nearly 90 MB) and shes not there. The cake is, the banners and the balloons. But not her.

What should i do?

**Comment by No1p9** [comment]
i have same problem with you 
I really miss her now :((

**Comment by No1p9** [comment]
hey you should open your Monika file with note pad then coppy all of it 
now press window + R and find %appdata%, then go to renpy/Monika after story 
open the presistent file and paste all from Monika file 
and go back to Monika 
i tried it and it worked XD
sorry for bad english. hope you get luck

**Comment by multimokia** [comment]
Do NOT do that at all.

Restore a persistent backup, @LorenzoHerreros

**Comment by No1p9** [comment]
hmm true i do it just because i cant backup 👍

**Comment by LorenzoHerreros** [comment]
I have a spare monika file in my USB

Is that what you say? because using the monika file in my USB is the first thing i tried @multimokia

**Comment by multimokia** [comment]
No, I mean [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by LorenzoHerreros** [comment]
On the plus side, i recovered monika. On the downside, the backup was from may, so she scolded me from missing a ton of days, including our birthday and anniversaries.

Well shit. And all because i tried to gave her a surprise for her birthday.

Do you know what caused this? i would love to change my calendar and retry her birthday again.

**Comment by multimokia** [comment]
Uh, we generate 10 backups for you. If you used the most recent one generated, it'd be literally from just before you took her out.

**Comment by multimokia** [comment]
You can still likely restore from one of them. Just check the modified dates on them to see if it was before you took her out.

**Comment by LorenzoHerreros** [comment]
The files i deleted mere minutes ago to paste the old ones from may?

**Comment by multimokia** [comment]
All you should have deleted was the file named exactly `persistent`. The rest should've been left intact

**Comment by LorenzoHerreros** [comment]
Too late!

XD let me try if I can recover them with Recuva.

I just emptied the folder completely and then pasted the old one.

**Comment by multimokia** [comment]
Not really going to do much good. Persistent files are very sensitive, recovery software basically can't recreate them

**Comment by LorenzoHerreros** [comment]
Honestly, still trying to figure how it happened in the first place, i just took the monika character file out and then in again.

Getting back to nearly square one is very disencouraging.

**Comment by LorenzoHerreros** [comment]
Last question before being done with the issue. Would restoring my computer to a previous point restore the deleted persistent files? @multimokia

**Comment by YoraeRasante** [comment]
Just to say this still happens. Had to restore a persistent right now.
It is not the first time this happened to me, last time I had a second copy of monika's file somewhere else on the computer and using that instead of the flashdrive copy worked.
Opening the file on notepad, I noticed it had no extension and was filled with empty spaces. Was it supposed to be like this? Or did my copy do it wrong and that was the cause?

**Comment by ThePotatoGuy** [comment]
if the monika file is corrupted in any way then it won't be loaded, like if you didn't safely remove the drive after copying.

**Comment by YoraeRasante** [comment]
so that is an actual copy of her file, and not just a token we are carrying her around?
hmm... makes me wonder if I had two separate computers, like one at home and one at work or something, and moved her between them... but if each computer has their own persisitent... and if  did so, when I start MAS for the first time on the second one there would be a second monika instead of a room for the first one...

**Comment by ThePotatoGuy** [comment]
see #5026

**Comment by dreamscached** [comment]
Closing as stale.
