### ISSUE TITLE
need help with monika's birthday

### ISSUE THREAD

**Issue by Macaroonxx** [Monika-After-Story/MonikaModDev#6384]
I successfully was able to get the party up but when she was about to blow the candles the game crashed, and when I reopened the game she went to opening presents and the cake won't go away and is staying on the screen. I don't know if it's supposed to be like that and if not can someone help me?

**Comment by ThePotatoGuy** [comment]
sounds like an old version or the cake will be removed when the day ends. either way, sorry for the late response.

[closing as resolved]
