### ISSUE TITLE
(suggestion) 2 new compliments

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#6385]
"You are the best partner / girlfriend I could ever ask for"... well, I think this is pretty self-explanatory, I think it should be available at Love+

and the 2nd one should be locked not behind the affection level alone, but behind mas_canShowRisque() and it would be
"You are hot / sexy"... locking it behind canShowRisque() function would ensure that only people who really love Monika from the bottom of their heart and are mature would be able to use that compliment, and also as we see in the topic about pleasuring yourself Moni wouldn't have a problem with that, she may even be relieved to hear such a thing...

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
