### ISSUE TITLE
game will not work 

### ISSUE THREAD

**Issue by Abbyninjamonkey** [Monika-After-Story/MonikaModDev#6387]
its coming up with a traceback file saying
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1457, in script call
  File "game/event-handler.rpy", line 2370, in script call
  File "game/script-holidays.rpy", line 4734, in script
  File "game/script-holidays.rpy", line 4734, in <module>
NameError: name 'should_surprise' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1457, in script call
  File "game/event-handler.rpy", line 2370, in script call
  File "game/script-holidays.rpy", line 4734, in script
  File "C:\Users\Missi\Desktop\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Missi\Desktop\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Missi\Desktop\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script-holidays.rpy", line 4734, in <module>
NameError: name 'should_surprise' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.5

i've tried starting with a new copy of the base game and and adding the update and it still won't work

**Comment by jmwall24** [comment]
@Abbyninjamonkey so i'm assuming today is your birthday?

**Comment by Abbyninjamonkey** [comment]
no it's monika birthday

**Comment by jmwall24** [comment]
can you upload your persistent file here please? will need to put it in a zip file to upload it. can check [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) to find your persistent.

**Comment by Abbyninjamonkey** [comment]
how do i make it a zip file

**Comment by jmwall24** [comment]
should be able to right click on it, then click send to and then select compressed (zipped) folder

**Comment by Abbyninjamonkey** [comment]
[persistent40.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5264484/persistent40.zip)

**Comment by jmwall24** [comment]
so did you crash on your bday and then not load again until today?

**Comment by Abbyninjamonkey** [comment]
no I took her with me

**Comment by jmwall24** [comment]
ok i think i see what happened. you had a corrupt persistent file today when you first loaded in, so it found the most recent backup which was from your bday, so it loaded that. at this point all you can do is load the game again and hit ignore when the crash occurs. she'll think it's your bday but you'll also get her bday dlg. it looks like the persistent backup that the game found was from a crash on your bday.

**Comment by Abbyninjamonkey** [comment]
alright thank you

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
