### ISSUE TITLE
Help me please file party supplies.zip I can't find it on the web page

### ISSUE THREAD

**Issue by Fernando8cho95** [Monika-After-Story/MonikaModDev#6390]
Help me please Monila Birthday
I'm looking for the file party supplies.zip I can't find it on the web page

**Comment by multimokia** [comment]
Party supplies zip is not used. It hasn't been used since 2018

**Comment by CrocandCo** [comment]
Did you get a message from Chibi Monika? Those were the instructions on how to prep.

**Comment by nickwilde15** [comment]
CrocandCo, do we ever see her again, or is that it?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
