### ISSUE TITLE
[Question] Giving Monika a flower crown?

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#6393]
So I’ve been looking in the mod_assets/Monika/ a, and I’ve been seeing the flower crown a lot. Is it possible to give her the flower crown as a .gift file?. Or is this from a old update?. Sorry, I’m just confused.

**Comment by lunulae** [comment]
That crown is a part of the New Years' event outfit. It currently is only wearable in outfit mode with the dress it comes with.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
