### ISSUE TITLE
[Song Suggestion] Strawberry by Paul Baribeau

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6397]
(sorry idk where you put song suggestions for Monika to sing at)

Lyrics Genius
https://genius.com/Paul-baribeau-strawberry-lyrics

YouTube video of the song
https://www.youtube.com/watch?v=lML1XA9JXSQ

Personally this is one of my favorite little love songs. Idk if this doesn't make it in i hope you enjoy it!
I may turn it into a dialogue code myself and put it in here. It would be a good beginner project since im still new.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
