### ISSUE TITLE
"Unseen" topic won't go away

### ISSUE THREAD

**Issue by arijog95** [Monika-After-Story/MonikaModDev#6399]
Hi, I'm having this topic called "X's control" that keeps appearing over the Unseen menu even after I discussed it. Is there a way to sort this out?

Thanks.

**Comment by multimokia** [comment]
#6398 addresses this.

This is actually caused by the room selection pack. It overrides certain topics, which in turn, means their base labels aren't marked as seen.

**Comment by arijog95** [comment]
Great, looking forward to it. Thanks!!
