### ISSUE TITLE
Nose boop?

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6400]
Could you add the feature where if you click on her nose, she has some kind of reaction, maybe she says boop or something?

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137. 

That's another one for the list.

**Comment by nickwilde15** [comment]
Didn’t see it, thanks though

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
