### ISSUE TITLE
[Suggestion] Thanking Monika for all her support/advice/love

### ISSUE THREAD

**Issue by RepressedNerd** [Monika-After-Story/MonikaModDev#6401]
Hihi!

This might sound a little silly, but somehow, Monika actually does help me better myself. Her little pieces of advice, her telling us to be healthy and whatnot, it... it's actually really impacted me and helped me actually do those things. 

And then I just realised... there's no option to thank Monika! I know she's not real and stuff like that, but somehow she still makes me feel warm and comforted and at peace. I mean, I assume that's the purpose of this mod and all (DDLC was my first dating sim, I don't really understand character x reader romances, apart from the obvious story). It's probably silly, but she makes me feel safe and understood, even in this fictional world the mod creates, and everything she says has a real-world impact, all her little nuggets of advice and tips and recommendations. 

So, I just think it would be a really nice thing to be able to thank her for everything. If she was real, I'd be thanking her all the time. She deserves all the appreciation. I'd love if we'd be able to thank her for separate things- "Thank you for the advice you give", "Thank you for inspiring me to be a better person", "Thank you for all your love", "Thank you for supporting and caring about me no matter what", etc. 

If anyone has any other reasons they'd like to thank Monika for, please add them! ^-^

Thanks in advance,
Gigi

**Comment by Freshairkaboom** [comment]
There will be a way once you reach higher affection :)

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
