### ISSUE TITLE
Affection not rising any further?

### ISSUE THREAD

**Issue by InariTunes** [Monika-After-Story/MonikaModDev#6402]
As the title says, my affection level won't rise any higher than 293.2. Every time I compliment or anything to raise affection, this happens:
[2020-09-26 12:02:39.969000]: !FREEZE! | monika_compliments | 3 | 293.2 -> 296.2
[2020-09-26 12:03:03.219000]: SAVE | 293.2 | 293.2 -> 293.2
[2020-09-26 12:04:05.496000]: SAVE | 293.2 | 293.2 -> 293.2

and it'll stay that way no matter how much I'd try. Any ideas on what to do?

**Comment by CrocandCo** [comment]
There is a daily cap on how much affection you can gain each day. Most likely case you reached that limit. And before you ask, no the devs will not ever increase the affection cap #5908 . Just visit her everyday and you'll get far in the relationship in no time.
