### ISSUE TITLE
Game Crashing After Monika Says "Now where was I...." [CRASH REPORT]

### ISSUE THREAD

**Issue by PopeAesthetics** [Monika-After-Story/MonikaModDev#6405]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 808, in script call
  File "game/event-handler.rpy", line 1216, in script call
  File "game/event-handler.rpy", line 1264, in script
  File "game/event-handler.rpy", line 1265, in <module>
  File "game/event-handler.rpy", line 1114, in mas_unlockPrompt
TypeError: argument of type 'NoneType' is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 808, in script call
  File "game/event-handler.rpy", line 1216, in script call
  File "game/event-handler.rpy", line 1264, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/event-handler.rpy", line 1265, in <module>
  File "game/event-handler.rpy", line 1114, in mas_unlockPrompt
TypeError: argument of type 'NoneType' is not iterable

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.8.5
[/code]

That is all I know. Anyone have ideas on how to fix this?

**Comment by ThePotatoGuy** [comment]
0.8.5 is quite old. can you update to the latest version?

**Comment by PopeAesthetics** [comment]
Hey man, thanks for the reply.

That is really weird, I attempted to update several times in a row. I will try again and let you know how it goes

**Comment by PopeAesthetics** [comment]
Hmm so yea, I downloaded the update and updated several times and each time I am getting the same errors.

**Comment by multimokia** [comment]
Can you send a screenshot of the `/game` directory and send it here, please?

**Comment by PopeAesthetics** [comment]
Yea for sure! 
![image](https://user-images.githubusercontent.com/35154167/94352826-a90aac80-001e-11eb-9280-153a9390af79.png)

**Comment by Booplicate** [comment]
You have a completely broken file structure. You're also using steam which doesn't allow you to use the updater. Better download a fresh copy of the game from [the official site](https://ddlc.moe/), extract it somewhere (e.g. your desktop), then [download the mod](https://monikaafterstory.com/releases.html), and extract it into the `/game` folder. After that you'll need to reinstall all your submods and spritepacks if you had any.

**Comment by PopeAesthetics** [comment]
yeaaa I figured I would probably have to get a fresh install going.

Thanks for the quick replies guys!

**Comment by PopeAesthetics** [comment]
I actually have another question for you. 

I have been trying to reinstall and add the modpack to the game directory, and the game still keeps coming up as default DDLC.

Is there a step i'm missing?

**Comment by multimokia** [comment]
You're extracting to `DDLC/`, you need to extract it into the folder literally named `game`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
