### ISSUE TITLE
All boops 

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6406]
Thanks to Rai99
#736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400,

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
