### ISSUE TITLE
Change the Pong compliment (Suggestion)

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6407]
Can we change the pong compliment from "you're really good at pong" to "I really enjoy playing pong with you" and make  some dialouge for that. Personally I really enjoy playing pong with Monika, and I really don't like the dismissive response to the you're really good compliment. It would be nice to give Monika a valid pong compliment.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
