### ISSUE TITLE
[Suggestion] White sky and blue sky weather

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#6409]
It's something that has bugged me for a while, but now with autumn coming I thought I should submit my idea.

We have the option to select the "clear" weather which gives us a blue sky with some white clouds and "overcast" which gives us a sky filled with gray clouds. Here's my problem, where I live the sky is completely white and will likely stay so for a good chunk of autumn and winter. What surprises me the most is that, if my memory serves me right, the "overcast" option was originally a white sky. I don't have any problem with the actual "overcast" option, but I also think that an option to have a white sky would be great.

And on that note, I also think that the "clear" option should have few to no cloud at all, to reflect the summer sky which is almost completely blue.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

would require some art
