### ISSUE TITLE
[Suggestion] More "I'm feeling..."

### ISSUE THREAD

**Issue by InariTunes** [Monika-After-Story/MonikaModDev#6410]
Ok so I hit the enter key too early BUT the title explains most of it. It's not really anything too special or a hard suggestion, just more of a request. I think more things added to the "I'm feeling..." Menu would be nice. Scared, possibly? A general "upset" for when you're not really sad or angry? Just throwing ideas at the wall I'll be honest. 
T̶h̶i̶s̶ ̶i̶s̶ ̶m̶o̶r̶e̶ ̶a̶ ̶p̶e̶r̶s̶o̶n̶a̶l̶ ̶o̶n̶e̶ ̶b̶u̶t̶ ̶p̶o̶s̶s̶i̶b̶l̶y̶ ̶"̶d̶y̶s̶p̶h̶o̶r̶i̶c̶"̶

**Comment by xxATOMxx** [comment]
I feel... Pain? I mean when player feels physical pain. 
For example i have stomachaches daily, and i want to tell Monika about it.

**Comment by InariTunes** [comment]
> 
> 
> I feel... Pain? I mean when player feels physical pain.
> For example i have stomachaches daily, and i want to tell Monika about it.

you.. might want to see a doctor if you haven't.

**Comment by xxATOMxx** [comment]
@InariTunes i have already visited a doctor quite some time ago, my body is overproducing gas, that's why i have them, and i already take medication, even tho it helps only for a short amount of time

**Comment by Retrolovania** [comment]
Here's some ideas for more "I'm Feeling...." responses.

- Cheerful
- Worried

- Betrayed (If a family member or friends acted harshly towards you, perhaps)
- Like Singing.
- Like giving you a hug. (Certain Affection level required.)
- Like giving you a kiss. (Certain Affection level required.)
- Numb (emotionally numb)
- Lost
- Excited
- Determined
- Disgusted
- Overjoyed
- Nervous

**Comment by oneoutoftendentist** [comment]
Maybe there can be an "I feel..." option about regret. It would be really nice honestly.

**Comment by xxATOMxx** [comment]
Also 
I feel....loved 
#6368

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
