### ISSUE TITLE
(Topic Suggestion) More topics on neurodivergence

### ISSUE THREAD

**Issue by opalmew** [Monika-After-Story/MonikaModDev#6415]
I've noticed that Monika has several topics on depression and how it can affect physical health. This makes sense as Sayori had depression in the main game. However, I thought it would be interesting to hear her discuss other forms of neurodivergence such as ADHD/ADD, the autism spectrum, PTSD, bipolar, DID and OSDD, dyslexia, and so on. As someone with ADHD myself, and who is interested in learning about other forms of neurodivergence, I think this would be a good topic.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
