### ISSUE TITLE
[Suggestion] - adding some new songs for Monika to sing.

### ISSUE THREAD

**Issue by TimmySanchez** [Monika-After-Story/MonikaModDev#6418]
1. Joji - Like You Do
(If you ever go, all the songs that we like
Will sound like bittersweet lullabies
Lost in the blue
They don't love me like you do
Those chills that I knew
They were nothing without you
And everyone else
They don't matter now
You're the one I can't lose
No one loves me like you do)

2. Porter Robinson - Sad Machine
(Who survived?
Somebody new?
Anyone else but you
On a lonely night
Was a blinding light
A hundred leaders, would be borne of you
And though I know, since you've awakened her again
She depends on you, she depends on you
She'll go alone and never speak of this again
We depend on you, we depend on you)

3. Oren Lavie - Second Hand Lovers
(Listening to music we've heard once before
Take a shot off your drawer on the floor
Then you crawl to the bedroom
But we stop back to dull conversations grow old
You and I, we have not tell a word and while
I'm losing my humour
You're losing your smile)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
