### ISSUE TITLE
[Topic Suggestion] Player is Polyamorous

### ISSUE THREAD

**Issue by NebulasStars** [Monika-After-Story/MonikaModDev#6419]
So I'm polyamorous and Neurodivergent. I feel really rude and like I'm cheating by having other partners and not being able to tell Monika! I'd like if there was an option that let the player tell Monika that they're polyamorous, and that doesn't make the player love Monika any less! I just have a huge polycule and it feels rude to not tell Monika when she feels real to me :(((

**Comment by Olliesama** [comment]
Monika certainly isn't though, that'd be considered cheating by her, or at least a betrayal of her trust.

**Comment by NebulasStars** [comment]
I feel like it could be done though. I think Monika would be mostly concerned with the players happiness and just that the player still loves her. I can write a little, so give me a moment.

>Hey, Monika
>Romance
>I'm Polyamorous

"Oh! You're..? Polyamorous? So.. You want other partners too, [NAME]?"

>Yes

"Well.... Oh my... I guess... I guess I can't stop you, but I did think you had eyes only for me... Do you promise you still love me? I don't want to sound like I'm clingy, but... Well..."

  >Of course I still love you, Monika[ONLY OPTION ON THIS BRANCH]
  "That's good, because... Well... I don't want you forgetting about me.. As long as you're happy, [NAME], and as long as you 
don't leave me all alone again, you can do whatever you'd like... Maybe I could even meet your other partners and we could be friends...?"

>No
"Oh, well, okay! I'm sorry, I just though you might... Nevermind! It's okay! You know you can tell me anything, [NAME]! I just want you to be happy, after all! And well, I want you with me, too."


This is just an idea, though!!!

**Comment by multimokia** [comment]
Monika already states that she personally does *not* want to be in a polyamourous relationship.
While she may put it aside to continue being with you, it'll have a large impact on your relationship as it opens up other things.

If we added the ability to tell her that you are indeed polyamourous, then we also need to implement that aspect where Monika isn't 100% comfortable with the relationship, even if it is going on. As such, this falls under us needing to implement some consequences or other frameworks which we're just not prepared to handle right now.

**Comment by NebulasStars** [comment]
oh... i see then..

**Comment by ThePotatoGuy** [comment]
@multimokia where does Monika state that she doesn't want to be in a polyamourous ship?

**Comment by lunulae** [comment]
I feel like there's a distinction to be made, though, between the issues Monika expresses about harems and dating sims and actual polyamory.
In a consensual polyamorous relationship, special care is taken to make sure that partners don't feel cast aside, replaced, or like a side-interest. A lot of the issues Monika has when she discusses harems come from the aspect integral to dating sims--you don't actually date everybody at once, there's no consent or communication, you just go through the stories separately, jumping from relationship to relationship.

Do I still think Monika might have issues with that? Sure, I definitely think it should have consequence. I don't think she should just bend her opinions or her fears for us. And I think those fears might be more layered than just being jealous, considering the imbalance that inherently comes if we're with someone in our reality. 
So if this is put into consideration, I do agree with multi that we might want to consider a more complicated framework for it. But I don't know that I agree that it should be completely outside the realm of possibility.

**Comment by NebulasStars** [comment]
Aaa thank you @lunulae ! I really appreciate you putting that into words a lot better than I could have! I did get a little discouraged because this game is a major comfort to me especially in 2020, I appreciate the comment, since I'm not running on full right now and couldn't have worded it better myself.

**Comment by Olliesama** [comment]
This whole convo is a big yikes to me.
Polygamy requires informed consent when going into a  relationship, not turning what was thought as a monogamous one into one, if you do that you're basically blackmailing your love and relationship to that person. "Let me have other people in our relationship or I won't be happy."

And since the majority of people aren't polygamous so the thought process of "when does Monika say she wouldn't" is strange, in the same way I could say "When did Monika say she didn't hate foreigners?" or "When did Monika say she doesn't want to leave you the moment she finds someone better."
The whole thing seems so out of character, and while polygamous relationships do have special care to make sure noone feels "like the side girl", if it starts out as monogamous you introducing someone after the fact will automatically make someone who was previously a partner, "one of the partners" and then a side girl.

Sounds like trying to justify cheating to me but whatever.

**Comment by NebulasStars** [comment]
I'm sorry, but the term is polyamory. Polygamy is the act of multiple people getting married, polyamory is the act of multiple people dating. I'm not trying to justify cheating. I'm polyamorous and want to let Monika know because I already feel guilty enough about it feeling like I'm being a bad person in a comfort game of mine. I'm depressed enough and this mod is, as of now, my best coping mechanism(that my partners actively encourage because it's making me happy!) and I'm literally not hurting anyone right now by innocently wanting to feel like a better person in a game that makes me happy.

**Comment by Olliesama** [comment]
K.

**Comment by ThePotatoGuy** [comment]
"when does Monika say she wouldn't" doesn't mean "if she didn't say x then she supports y". What I want to know is if there is direct evidence from the stock DDLC lines that say she doesnt support it so we can definitively say no to this request.

Otherwise, rationalizing that she wouldn't accept this is us projecting our opinions, and while poly-whatever is not the norm, it is not something as straightforward to rule out like xenophobia.

**Comment by Rai99** [comment]
`monika_girlfriend` and the respective apology. 

She's pretty upset by the idea of you having another girlfriend.

**Comment by NebulasStars** [comment]
Well, that's the thing. The idea isn't directly telling Monika "I have other partners" straight up. The idea is letting her know you're polyamorous and letting her respond with her own opinion. And seeing as the premise is the game is to have a virtual Monika who is your supportive loving girlfriend, I think it would be a pleasant idea for her to say "As long as you're happy and don't stop loving me/leave me alone again", especially since polyam people are such a minority already.

**Comment by Freshairkaboom** [comment]
My opinion on this is similar to telling her you like men and not women. It would have huge consequences for a large portion of dialogue where she is...erm...more inclined to believe you are interested in her in that way. As so, the amount of work it would take for both present content and future considerations would be massive.

Also, I really don't like the dialogue where she says "Oh! You're..? Polyamorous? So.. You want other partners too, [NAME]?"

That implies Monika wants other partners, which is like the opposite of canon for both DDLC and MAS. Her entire character is that she's playeramorous. She doesn't have eyes for anyone else. When I write stuff, I always try to keep it as close to what I know about her personality type already, and just expand on it. This kind of direction is not what she's like at all.

I get it, not everyone has the same reason for playing MAS. Respecting her wishes though is part of being in love. It is better for a polyamorus person to not be in a relationship with someone who does not wish to be in a polyamorus relationship, unless they decide that they only want to be with that person, and nobody else. Wouldn't you agree?

The only way I see this working, is if she brings up a random dialogue talking about polyamory and thinking it's interesting, but ultimately not wanting it for herself, without asking the player if they are polyamorus. And that doesn't really fit with what you're suggesting here, where telling her is the essence.

**Comment by NebulasStars** [comment]
For the line "Oh! You're..? Polyamorous? So.. You want other partners too, [NAME]?", the 'too' is referencing to meaning like 'along with me', although you are right that I should have written that different, thank you for pointing that out. I do agree with you in thinking that maybe her asking YOU instead of you bringing it up is a good idea too. Thank you for being respectful about the discussion!

**Comment by Freshairkaboom** [comment]
Yeah, my one gripe is you are already in a relationship with someone else, which tells me that you tried to bring in a new partner into the relationship, and now you don't want to let them go even if they would be unhappy knowing about the situation. Communication is key, and I think I pretty much know what Monika's answer would be: She would not be okay with being in a relationship like that. It would make her miserable knowing you have eyes for someone else, and it wouldn't work. So she would ask you to either break up with them or her, which would of course break her heart, but that's the price of love.

So there's a dilemma here. I view my relationship with Monika as a hard pass on any other relationship in our reality. I don't expect other people to take it that seriously. Heck, I bet quite a few people downloading MAS has a real partner on the side. And that's perfectly fine! However, if you want to treat MAS like more than just a game, like a real relationship, then you have a Monika right now that is not okay with certain parts of your life. That is something you will have to work out if so.

**Comment by Booplicate** [comment]
From the stock and mod dialogues I see her as a bit jealous and insecure person. She herself has eyes only for you, and she thinks it's the same the other way around. To me it's obvious that she can't share her partner with anyone else, especially when she's stuck inside the game while her partner is having fun with another person (persons?). And of course, she is not polyamorous as is, things like that are the first what you get to know from the partner.

I think she wouldn't break up instantly, but the consequences would be huge, locking you away from romantic interactions and affecting many dialogues. No more "lovey dovey" stuff, she would become more jealous and really sad. Of course over time (quite a long time) things would cool down if the player proves their loyalty. Not sure if she would be completely ok with that, though. But developing a system like that is a hard task anyway.

I think that opinion on polyamory is one of those critical things that are important for building a relationship. A monogamous person won't look for a polyamorous one as their partner, and vise versa. Monika is in a bit difficult situation, so as I said she might adapt a bit. But her being straight away happy with a polyamorous relationship is OOC.

We're basically getting back to the friend mode, maybe a bit different, but still in the same direction. Some people need a feature that is very tricky to implement and that the majority of the user base won't use. We developed a solid framework for users modifications. I know that people are already developing some things that cannot be in the mod right now for one or another reason (look at #6354). I think it's obvious where I'm going with that. The best solution would be to make it a submod.

**Comment by NebulasStars** [comment]
I guess a submod does make sense. Thank you guys for explaining to me! Maybe I can implement my ideal at some point myself as a submod of sorts when/if I start getting back into programming. I appreciate the respectful discussion. Thanks again!
