### ISSUE TITLE
[Suggestion] - Customizable player(Text based or not)

### ISSUE THREAD

**Issue by NebulasStars** [Monika-After-Story/MonikaModDev#6422]
My sibling came up to me and insisted I suggest this, but being able to let Monika know how you look would be nice! Whether that be in the DEV EXP PREVIEW style or just by going through a little explanation where Monika asks about your appearance and you tell her how you look, it'd be cute!

**Comment by Rai99** [comment]
>  a little explanation where Monika asks about your appearance and you tell her how you look

That's a thing already.

**Comment by NebulasStars** [comment]
> That's a thing already.
Ohhhh okay sorry! My sibling recommended smth like the DEV EXP PREVIEW(Gameplay context would be Monika giving you a mirror?) but I thought specifying text-based too would be helpful, pfft. Do you know how you can re-explain your appearance to Monika?

**Comment by lunulae** [comment]
Repeat Conversation > You... > [Player]'s appearance

**Comment by NebulasStars** [comment]
Thank you very much! I'll let my sibling know!!!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
