### ISSUE TITLE
[Suggestion] New "I'm feeling ..."

### ISSUE THREAD

**Issue by NebulasStars** [Monika-After-Story/MonikaModDev#6423]
"I'm feeling Panicked." Maybe Monika could offer help for Panic attacks and Anxiety attacks!
[I feel like I should apologize for suggesting so much in one day, I'm just flowing with ideas today, pfft!]

**Comment by nickwilde15** [comment]
Also I feel hurt, she could ask if physically or emotionally maybe?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
