### ISSUE TITLE
[Suggustion] A new check for

### ISSUE THREAD

**Issue by Cloudy-Horizon** [Monika-After-Story/MonikaModDev#6425]
Maybe you could check for gifts?

**Comment by lunulae** [comment]
Do you mean a manual option to have her check, like the "Can you check for new music" option?

**Comment by ThePotatoGuy** [comment]
gift checking works roughly once a  minute, and you can force the next check by opening and closing the Talk menu. Music does not get checked regularly, which is why there is a prompt for it.

[closing as rejected]
