### ISSUE TITLE
(Suggestion) A New promise ring 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6427]
For example a emerald ring or green ring

(JUST MONIKA)

**Comment by Olliesama** [comment]
Could make one yourself and replace the sprite :>

**Comment by CrocandCo** [comment]
#2909 They have been working on it for quite a long time.

**Comment by Ant9cp** [comment]
@Olliesama I'm not a (computer) expert on any of that stuff, i don't even know what to do
