### ISSUE TITLE
A small story topic fix

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6429]
ok (i mean i've already done the stories but i remember this really annoying me) So when you're in the tell me a story topic. If you've unlocked "A mother's trees" its above "A new story" (they're all alphabetical so that's why) would it be possible to go in and make it so the new story topic is always at the top no matter what. It was really annoying when it was pushed down one. (ik small nit-picky thing. but hey would be nice if someone did)

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
