### ISSUE TITLE
This year Halloween topic idea [Time sensitive request]

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6430]
Ik Halloween's coming up. (ik this fun fact because imma bit of a witch and im on witch-tok aloot)Fun fact that I feel like Monika could bring up on Halloween is There is a full moon on Halloween! But this isn't the only cool thing about it! There are actually 2 full moons in the month of October. When this happens it's called a blue moon. A blue moon only happens about every 2 and a half years, so it's already pretty rare, but the fact that its on Halloween just makes it even cooler. 

If someone made a dialogue for Monika to mention this phenomenon on Halloween, that would be pretty cool.

**Comment by ashyashton** [comment]
There's also an extra hour of Halloween because of the time change!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
