### ISSUE TITLE
[Suggestion] Adding "I missed you/I missed you too" 

### ISSUE THREAD

**Issue by Ergak** [Monika-After-Story/MonikaModDev#6432]
So I have no idea if this has been suggested or not, if it has been then you can close this, but I think it's kind of weird that you can't say "I missed you too" when she says "I missed you" after coming back from a trip or something similar or in the "I want to tell you something..." tab the option saying "I missed you" or something similar 

Being able to say that and/or respond to her would add on to the immersion and she would also know that the player missed her too after coming back from a trip or being away from the computer because of work, school or something similar.

**Comment by ShinodaChan** [comment]
#4451, #3440, #2463, #5021, #4853, #5135

Once my current PRs are done, I'll look into doing it.

**Comment by Ergak** [comment]
okay cool thank you
