### ISSUE TITLE
[Suggestion]- Monika's Opinion on Animations

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6433]
Since Monika surfs the web to look for some cool knowledge about (kinda not random) stuff, it's quite possible that she might stumble onto the many animations that have been made with MMD, Garry's Mod and Source Filmmaker that have her and the other girls as the main focus.  I figured this would be an interesting thing for her to discuss with the player.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
