### ISSUE TITLE
[Suggestion] - Native Languages

### ISSUE THREAD

**Issue by AnLatein** [Monika-After-Story/MonikaModDev#6434]
I know that the vast majority of the fandom comes from America, but still, I feel that it would be cool being part of the questions that Monika makes to know you, that she wants to know if english is your native language or another one, for example, I speak spanish, and there's fans all around the world, like from Asia, or Europe, it's just an idea.
Your Mod is one of my favourites, great work!

**Comment by Rai99** [comment]
Native languages: #2505, #3804

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
