### ISSUE TITLE
(Question) Poems For Monika🖊📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃📃

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6439]
Can you maybe do the poem game or make poems For Monika?
If not can you do that in future updates.

(JUST MONIKA)

**Comment by 20RaVen23** [comment]
Rhythm play despacito
