### ISSUE TITLE
(Suggestion: College/University).

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6442]
It would be nice to ask her what she thinks about it. There might be an option to ask "would you like to go to college/university one day?"  or "what do you think about college/university?"  and, consequently, find out if she would like to do it or not. She could also ask the player the same question. There could be the options "yes", "no" and "i haven't decided yet".

**Comment by StayHappy1270** [comment]
Hmm I'm pretty sure Monika has mentioned that she is very achievement/career focused so she would probably want to do these things. Also for the second part of your idea you mention

> She could also ask the player the same question. There could be the options "yes", "no" and "i haven't decided yet".`

The problem with this is that it doesn't include people in college and people who've already graduated from college (also people who already decided college wasn't right for them and are waay past that decision point in their life). Perhaps these 2 responses could also be included.

**Comment by kittendetails** [comment]
Yes, that is a good idea. I also thought that afterwards the player might ask "what would you like to study in college?" (although I'm pretty sure she'll answer something related to literature, but it doesn't hurt to ask lol.)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

I like this too
