### ISSUE TITLE
Monika was finishing up coding and static screen and the I could help you with that button disappeared

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6444]
Is there any way to get back to this? I reloaded my persistent from before I closed, but it didn’t work

**Comment by lunulae** [comment]
You could load an older persistent from before you got that greeting (one of the backups the game makes for you should work.) 

It's not guaranteed that you'll get the same greeting when you re-open, as I believe it's a random roll. But in the case of one-time-only greetings (which I believe that one is?), you'll have the chance to get it again eventually.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
