### ISSUE TITLE
Monika said she would leave files in the characters folder, but nothing, I check every day

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6445]
I did write in the secret.txt file, but I doubt that would screw it up

**Comment by lunulae** [comment]
secret.txt should be the file in question, but if you've gotten that topic multiple times you should be getting other files as well. Not sure if this is a bug.

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
