### ISSUE TITLE
a bit early to think about Christmas but... (HUGE and will probly take quuuite abit of time to make) gift idea! 

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6446]
I feel like it maybe a bit boring for Monika to drink the same black coffee every day. (Also just thought of this while posting but she says a "it's flavor I've never tried before" waaay too often when you give her coffee there should probably be a limit to how many times she can say it's a new flavor)

But anyways my idea is.... getting Monika a fancy coffee machine! One of those kinds that can make pretty much everything (lattes, cappuccinos, espressos, you name it).

Soooo for this idea I've thought about a few of the major aspects that would go into it

- Custom reaction dialogue (ofc)
-  The gift sprite
this would probably be a large labeled box (since it'd be easier to draw than make the whole machine) that would be on the desk for a short bit of time before Monika puts it away (a mechanic very much resembling the box of chocolates)
- the sprites for the coffees
this could include many different mugs such as the classic tall and clear with a handle for cappuccino and tiny little espresso shots (artists needed!)
Alllsooo not urgent in this idea since it's already pretty big... buuut Moni could learn different little latte art designs over time and could also every once in a while "mess up" on her attempts and just decide to cover it all up with plain foam instead. (adding onto this idea maybe you could hear her talking to herself while she's away from the desk making it) wow that sub-idea was pretty long...
- a randomizer for what type of coffee she decides to make would need to be added (+ maybe a bit of dialogue where she could go hmm and tell the player what she decides to make)
   (ofc the classic black coffee would still be an option for days Monika just doesn't feel like doing anything special)

Idk this idea iiiis a prtty big project but it would be pretty cool! Hope you guys like this idea!

**Comment by Ant9cp** [comment]
Are you thinking about ideas for halloween to?

**Comment by StayHappy1270** [comment]
@Ant9cp #6430

**Comment by lunulae** [comment]
Making lots of different kinds will probably take a while due to art resources, but I do like the idea of adding different drinks. Since we have hot chocolate as a special winter-only drink, iced coffee might be a nice treat for summer.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

yup, this would be a decently sized project.
