### ISSUE TITLE
(Suggestion: Children.)

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6448]
So, i don't know if this topic has already been implemented (maybe i still don't have enough affection to talk about it) but, if it doesn't already, i think it would be nice to ask if she would like to have children. Something like "would you like to have children?", her answer may be based on the level of affection with the player, if she is still a little unsure, her answer could be something vague, like "i still don't feel comfortable talking about that, but maybe we can talk about it when we are more advanced in our relationship". This topic could be addressed later when she feels more comfortable, and unlock the questions "how many children would you like to have?" or "do you have a preference between a son or a daughter?" and she could talk about her opinions/concerns about it. I know it's more about her fantasies than the reality itself, but i think it would be interesting to talk about it with her. (Sorry for any grammatical errors :P)

**Comment by lunulae** [comment]
This topic has been discussed a few times in the past. (I believe the current discussion thread is on #6291?)

It's a fairly touchy subject for lots of different players and it's a huge life decision, so essentially the consensus is that if it gets added, we'll want to be pretty careful about how we handle it. There's also a bit of discussion about what to do in the case that the player already has kids of their own, which will take some extra thought.

**Comment by kittendetails** [comment]
Oh, i understand. I'll take a look at this topic. Thanks for the answer, btw. :)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

use the linked issue (#6291) to discuss this further.
