### ISSUE TITLE
(Question) Nailpolish

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6450]
Is there going to be more nailpolish for JUST MONIKA, different colors?

**Comment by lunulae** [comment]
The nail spritepacks I have seen are unofficial so far, so I don't think we can make any promises about that, but it's possible that people might make more. I certainly hope so!

**Comment by Rai99** [comment]
Custom fingernails: #4243, #6383 

~~Also, you asked this a little over a week ago.~~
