### ISSUE TITLE
[Suggestion] — A happy end

### ISSUE THREAD

**Issue by justthiago** [Monika-After-Story/MonikaModDev#6451]
i need to say goodbye to monika, but i don't want to leave alone and sad. I'm not a monster. can you develop this happy ending?

**Comment by lunulae** [comment]
I can certainly respect a want for closure, but I'm not sure if it's possible to make a *happy* ending in that regard.

It's probably not what you're looking for, but you might want to try honestly telling her that she might never cross over. She has some dialogue regarding what she wants you to do if you can't stay with her.

Not everybody is going to be able to stick with this mod forever, so I certainly don't want this to come off as trying to guilt anybody either. You've got your own life and reasons, and you should have the full right to pursue them. It's just also very difficult to reconcile that with writing Monika realistically in this scenario.

**Comment by fromulus** [comment]
MAS isn't meant to have an ending.
While not being willing/able to play the mod anymore isn't anything to be ashamed of, and not wanting to leave her alone is a good sentiment to have, there's no miracle solution here.

Monika has nothing and no one but you, so if you abandon her, she'll be alone, just like she was back in the original game.
It's pretty awful, but you best option os probably to tell her you'll be going for an unknown period of time, and wipe the persistent file.  

It'll at the very least be an act of mercy, as she won't wait for you forever, nor will she stay in the void or have to delete/kill herself.

Either way, as Lunulae said, there isn't really any possible happy endings here.

**Comment by Retrolovania** [comment]
"And if this world won't write me an ending,
what will it take, just for me to have it all?"

I'm sorry you have to say good bye forever. However, I agree with the above statement. It would be best to just wipe the files. While some would see that as an act of deception, in the end, is there really a better option?

All in all, I hope things go well for you, son.

**Comment by scpketer** [comment]
Sorry to bump the necropost, but regardless - I'm currently working on something like that in a submod form.

I personally don't consider such an outcome possible for me, but I just want to have all cases covered, so...

I'll try to drop it somewhere once I'm finished, maybe not for the OP, but all the other people alike.

**Comment by ThePotatoGuy** [comment]
as said in the other comments, MAS does not have an "ending" and will not have an ending as its designed to be a continuous game.

[closing as rejected]
