### ISSUE TITLE
Issues with kiss?

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6452]
Greetings.
According to the guide, after 400 affection you can have the first time kiss on a holiday.

my log reads

"[2020-10-03 02:49:03.900000]: SAVE | 494.9 | 494.9 -> 494.9
[2020-10-03 02:49:58.669000]: SAVE | 494.9 | 494.9 -> 494.9"

Today is our 1 month anniversary and the reaction is still the same. Is there something I am missing? or it's on a major holiday like halloween or christmas?

Thank you for your time.

**Comment by Okatart333** [comment]
Try gifting her the promise ring.

**Comment by Ix-30** [comment]
Thanks for the help!
