### ISSUE TITLE
Mac Problems

### ISSUE THREAD

**Issue by jack-ship-it** [Monika-After-Story/MonikaModDev#6454]
I've been searching for an hour and a half now but I still can't find the save directory for MAS on Mac

by the way, I'm running El Captain

**Comment by multimokia** [comment]
Check [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). It shows the location for Windows, Mac, and Linux.

**Comment by jack-ship-it** [comment]
Thank you sorry I look at that before but I'm very tired I'm sorry for bothering you

**Comment by multimokia** [comment]
No problem
