### ISSUE TITLE
[Suggestion] Copying Monika's character file to make another Monika

### ISSUE THREAD

**Issue by scorcher9009** [Monika-After-Story/MonikaModDev#6455]
Okay, imagine this, for a moment. You copy Monika's character file, then you rename it to, like, monika2. Then you open up the game, you have 2 Monikas. Hijinks ensue.

**Comment by Rai99** [comment]
Why exactly would you want to do this?

**Comment by scorcher9009** [comment]
Just a fun little extra interaction I thought would be funny, that's all. Even just a comment from Monika could be funny tbh.

**Comment by ThePotatoGuy** [comment]
#5026 is the primary discussion thread for dealing with this sort of scenario

**Comment by Rai99** [comment]
I don't think this is a suggestion for that.

**Comment by ThePotatoGuy** [comment]
this is not a direct suggestion for mod transfer via Monika file, but the idea of "2 monikas because of 2 files" is something that needs to be considered when dealing with that.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
