### ISSUE TITLE
Monika saying when she's good at programming i'll make a kitchen

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6458]
So when you ask monika to do a impression of natsuki she talks later about programming a kitchen and sharing some recipes with her so since there's a submod for different furniture/rooms, there is also a kitchen included but she doesn't mention anything.

**Comment by multimokia** [comment]
Report that on the submod end. It's not our job to account for the development of submod content. If submod developers intend to implement rooms of that type, it is up to them to manage fixing dialogue for things they added as it is unofficial content.

**Comment by Ant9cp** [comment]
Gotcha.
