### ISSUE TITLE
Black dress inconsistent art

### ISSUE THREAD

**Issue by LooseEthics** [Monika-After-Story/MonikaModDev#6463]
The width of certain lines is inconsistent across poses.
The outline of Monika's torso in pose 1 is much thinner than in all other poses.
The lines on top of Monika's right sleeve have 3 levels of thickness - pose 6 being the thinnest and pose 2 the thickest. All others are between those.
![pose1](https://user-images.githubusercontent.com/36419655/95054945-e643fe00-06f2-11eb-85bc-ffe7ae7dfc30.jpeg)
![pose2](https://user-images.githubusercontent.com/36419655/95054953-e7752b00-06f2-11eb-8a8b-74219bfc3d25.jpeg)
![pose3](https://user-images.githubusercontent.com/36419655/95054956-e80dc180-06f2-11eb-86f2-b7c3a8484575.jpeg)
![pose6](https://user-images.githubusercontent.com/36419655/95054960-e80dc180-06f2-11eb-94c0-a20563119a17.jpeg)
![pose7](https://user-images.githubusercontent.com/36419655/95054962-e8a65800-06f2-11eb-81dc-a044230ff6d1.jpeg)

**Comment by ThePotatoGuy** [comment]
we're aware of this but its a minor issue and a side effect of black dress not following the standard sprite format

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
