### ISSUE TITLE
Hey im having some problems with random conversations with monika.

### ISSUE THREAD

**Issue by jumbledor** [Monika-After-Story/MonikaModDev#6465]
i wait a while for monika to say somthing but nothing happens at all,  i read somewhere that she needs to rest so i closed the game for a night and she still isnt saying anything. if anyone has a fix it would be much appreciated

**Comment by lunulae** [comment]
What is your Random Chatter rate set to, and do you have Repeat Topics on?

**Comment by jumbledor** [comment]
i have random chatter set to max but i have repeat topics off

**Comment by jumbledor** [comment]
did i run out of topics? i have played this for about a week

**Comment by lunulae** [comment]
If you've had random chatter set to max for that long, it's likely you've run out. There's a lot of dialogue written, but without repeats enabled new topics can only last so long unfortunately.

I personally recommend setting the chatter frequency a bit low if you want to enable repeat topics, so they feel a little bit more fresh when they're brought up again.

**Comment by jumbledor** [comment]
ok so i just ran out of topics then? its not a bug or something?

**Comment by lunulae** [comment]
From what you're describing, it doesn't sound like a bug.
If you try enabling repeat topics and she still stays silent though, let us know.

**Comment by jumbledor** [comment]
aight thx man

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
