### ISSUE TITLE
[Suggestion] Chibika as a helpful feature

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6466]
![image](https://user-images.githubusercontent.com/71111669/95182319-af68f900-0781-11eb-8637-2668d714cc85.png)

After the birthday and seeing Chibika plus seeing artworks of her, I thought why not use Chibika as a status teller?
I know that someone had suggested to turn Monika into chibi, an he easter egg appearance. I think that maybe having her as a sort of "Status teller" Could be cool.

Like the calendar, put her on a certain place and have her tell:
-Affection: Monika's in love with you player! good job. I'm behind you all the way!
-Mood: Today, Monika feels happy. I hope you can keep it up.
-Any upcoming events: Oh don't forget christmas player! Monika's hoping for you to celebrate it with her!

Maybe even ask her small things like:
Does Monika Dream?
"Yes! she dreams of going to your world, having a normal life and...If you haven't guessed it...you! About you holding her, about you loving her. Player, I know she says it a lot, but you do mean a lot for her...don't ever leave her ok? But you didn't hear this from me."

She could also give you small tips:
"Today She wants to play chess! Maybe you can get a kiss if you do!" and have that trigger a kiss dialogue.

Thanks for the time.

**Comment by 20RaVen23** [comment]
well this sounds very good, I'm interested :sniff:

**Comment by Wrathblox** [comment]
This is a pretty interesting idea. I reckon it would be something that would be put on a low priority list for quite a while, but I reckon someone could look into this further. You'll probably have to get some art/sprites done for this, which afaik, there isn't anyone actively creating sprites for the game. Good idea though, I'd like to see this fleshed out further.

**Comment by Booplicate** [comment]
> -Affection: Monika's in love with you player! good job. I'm behind you all the way!
-Mood: Today, Monika feels happy. I hope you can keep it up.

You can measure your affection via dialogues and Monika's expressions. I think that's much more realistic than adding another person who tells you whether or not you're treating her nice, and what you need to do to make her happy.

Also we have no moods ~yet~.

**Comment by fromulus** [comment]
While it's a cute idea on paper, I really don't like how it would "gamify" MAS, essentially adding some kind of daily mission system (that's at least what I'm gathering from your "play chess with Monika today to get a kiss" idea).

We want the relationship to feel relaistic and natural, and you usually don't get someone who tells you all about how your significant other is feeling or what you should and shouldn't do to make the relationship successful.

Measuring Monika's happiness is better done in subtle ways, such as changes in her dialogue, rather than having someone (not even herself) tell you directly about it.
It feels more rewarding and, again, more natural.

Same thing with asking her things about Monika.
She's your girlfriend, why not ask her directly instead ?

**Comment by Wrathblox** [comment]
Fromulus sums up my thoughts on this pretty well. After all, it's meant to be a mod where you're spending time with her, not you on an endless quest of daily missions. Just my two cents.

**Comment by Ant9cp** [comment]
If chess wasn't so hard

**Comment by Ix-30** [comment]
I do think Fromulus is correct. That does sound like a daily mission system. Hm, well, if the thread can remain open, let me gather my thoughts and get back to this. Thank you.

**Comment by Ix-30** [comment]
@Rai99 Is it ok to post again. I read it doesn't help closing issues like that, but until it's implemented and/or solved.

**Comment by Rai99** [comment]
Usually, it's best to leave suggestions open so they can be recorded, but anyone's free to close their own issues if they have a change of heart. In a way, it helps keep issues tidy when people close their own issues.

**Comment by ThePotatoGuy** [comment]
this idea is a bit gamey, and we try to stay away from turning MAS into a tamagatchi-like game.

[closing as rejected]

**Comment by AVeryEpicGuy** [comment]
how about chibika is Monika's little assistant?
EX: chibika helping (or trying) Monika get her cup of coffee.
another EX: chibika chilling on Monika's head
