### ISSUE TITLE
(Suggestion) Different dialogue after losing in pong

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6467]
When you stop playing pong with monika when you didn't mean to let her win, she always says thanks for playing pong with me and letting me win

**Comment by StayHappy1270** [comment]
hmm @Ant9cp any ideas for what we could say instead?

**Comment by Ant9cp** [comment]
(Example) That was fun (nickname) if you want to play again just ask me, and i'm sure you'll win next time, and make sure you practice to, Remember practice makes perfect after all 

@StayHappy1270

**Comment by scpketer** [comment]
That seems like something that #6477 is about, I'm sorry for bumping the necropost.
