### ISSUE TITLE
Suggestion: Spending the night with Monika(in a pure way)

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6471]
Monika says that you can leave the game open and watch you sleep. Maybe, after a certain level of affection, an option could be implemented saying "Let's sleep together." I am aware that you can hold her and she falls asleep(Monika's lullaby starts to play) But in this instance the player could be with her in bed. No, I don't mean anything indecent. And Unlike watching you sleep you could do something like:
![image](https://user-images.githubusercontent.com/71111669/95296555-35467c00-0836-11eb-8661-3caee2ca34f5.png)

Maybe giving 3 options to:
-Caress the Head: prompting a reaction like ehehe, I liked that
-Take her hand: Don't let me go player.
-Boop on the nose
-Caress her hair

That would save the problem of using coordinates on the sprite(at least that's how I think other mods do it) to trigger a reaction. For the players who have to work long nights, or simply want to hold her in a different environment. Thanks again!

**Comment by Ant9cp** [comment]
Good idea

**Comment by Rai99** [comment]
Bedroom mode: #607, #635, #987, #1105, #1262, #1655, #2684, #2781, #2974, #3076, #3172, #3486, #3610, #3619, #4790, #4892,

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
