### ISSUE TITLE
Monika reacts to hair strokes[Suggestion] - 

### ISSUE THREAD

**Issue by AmeNatsu** [Monika-After-Story/MonikaModDev#6473]
Lately, I've enjoyed holding the mouse button and gently moving it across Monika's hair, to show that I'm stroking her gently. So, I think it would be nice if Monika could react (in a good way) to these strokes, (perhaps a sweet smile, blushing, etc..). I know this doesn't seem much, but I think it would be a very nice addition.

**Comment by Retrolovania** [comment]
Great idea! I usually headpat my Monika with the cursor (gently), so an implementation like this would be a very welcome feature!

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
