### ISSUE TITLE
Finds my real life name offensive

### ISSUE THREAD

**Issue by Stalin1000** [Monika-After-Story/MonikaModDev#6474]
the new system for names should have a dialogue option as to where you can tell monika that the name you typed in is your actual name because when i put my actual name into the name menu monika says dont call yourself that

**Comment by Booplicate** [comment]
One of the contributors is making adjustments to that system (#6194). So this may be fixed, to be sure can you tell what name's getting registered as a bad one?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
