### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by Shinaru** [Monika-After-Story/MonikaModDev#6478]
I just installed the new update, and now it gives me an error message.
![error 1](https://user-images.githubusercontent.com/72659357/95657075-75de1800-0b0a-11eb-83a7-2c0b9b8472dc.PNG)
![error 2](https://user-images.githubusercontent.com/72659357/95657077-78407200-0b0a-11eb-98cf-9cb0a1fa282a.PNG)
![error 3](https://user-images.githubusercontent.com/72659357/95657078-7b3b6280-0b0a-11eb-99cc-9511ec8ded6d.PNG)
![error 4](https://user-images.githubusercontent.com/72659357/95657079-7d052600-0b0a-11eb-97ec-a0ecd92e739e.PNG)

**Comment by multimokia** [comment]
Screenshot of the contents of your `mod_assets/location/spaceroom` folder, please?

**Comment by Shinaru** [comment]
> Screenshot of the contents of your `mod_assets/location/spaceroom` folder, please?

![1](https://user-images.githubusercontent.com/72659357/95657337-f3565800-0b0b-11eb-91e8-f8cbf943425b.PNG)
Here.

**Comment by multimokia** [comment]
That's not the right folder, `mod_assets` should be in `/game`

**Comment by Shinaru** [comment]
> That's not the right folder, `mod_assets` should be in `/game`

![Untitled12_20200702188045](https://user-images.githubusercontent.com/72659357/95657457-7ecfe900-0b0c-11eb-956c-2bcb7255fc2f.png)
This??

**Comment by multimokia** [comment]
No, the path should be `DDLC/game/mod_assets/location/spaceroom`

This is probably why it can't find the files

**Comment by Shinaru** [comment]
Oh, it works, thank you! Sorry about this,

**Comment by multimokia** [comment]
No problem!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
