### ISSUE TITLE
[Suggestion] - Set Times for BGM

### ISSUE THREAD

**Issue by JustABLUToon** [Monika-After-Story/MonikaModDev#6479]
Sorry if this was already suggested before, I'm new here, hope I'm doing this right.

Anyways, I was thinking, what if with the background music you have a few you really like? But at the same time, these songs fit with different times of day? I was thinking, what if you could set songs to be played during specific time periods (like morning, afternoon, night, etc.) or be very specific with, say, "this song will play between 1 and 2 PM", et cetera. I feel it would be a neat addition, especially considering the fact that the overall mood of the Space Room changes depending on the time of day.

Hoping I formatted this right, and I'm hoping its a good idea. Again, sorry if it's been suggested already.

**Comment by Booplicate** [comment]
One of the submods can do something similar, but only for night. I suggest to check out the `Nightmusic` one in [External Content](https://github.com/Monika-After-Story/MonikaModDev/wiki/External-Content).

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
