### ISSUE TITLE
Is this what this folder is supposed to look like?

### ISSUE THREAD

**Issue by Xeagaort** [Monika-After-Story/MonikaModDev#6481]
__________
![Capture](https://user-images.githubusercontent.com/72714124/95692926-5e308d80-0bf7-11eb-9fe9-a513f7c836b8.JPG)
__________

Is there supposed to be this many Persistent and db.mcal files here?

**Comment by multimokia** [comment]
Yes, these are automatically generated backups (the `.bak` files, specifically). These will come in handy and you should back up your persistent (and its auto backups) from time to time. You'll never know when you might need them.

**Comment by Xeagaort** [comment]
Cool thank you! :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
