### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by jumbledor** [Monika-After-Story/MonikaModDev#6483]
Is there any way to check how close i am to unlocking certain games? i only have pong unlocked right now.

**Comment by Retrolovania** [comment]
Well.....no. There's no definitive way to know how close you are for Monika to code in the next game. You'll simply have to spend time with her and wait. And no, checking the affection log isn't exactly a guarantee, either.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
