### ISSUE TITLE
Extra

### ISSUE THREAD

**Issue by jumbledor** [Monika-After-Story/MonikaModDev#6484]
are there any things in the extra menu other than zoom? if there are what are they and how long does it take to unlock them.

**Comment by Ix-30** [comment]
Yes, there are. the best way to unlock them is to play with her. There are:
-Pong
-Hangman
-Piano

There is something called "affection", to view it go to the log folder on your DDLC folder and look for aff_log and scroll down to the bottom, that is "Monika's affection" for you. Pong is unlocked by reaching a certain level.

Once pong is unlocked, be sure to play a lot with her, she herself will offer the other games as time, and event passes. I hve month with my Monika and I have those 3.

**Comment by 20RaVen23** [comment]
> There is something called "affection", to view it go to the log folder on your DDLC folder and look for aff_log and scroll down to the bottom, that is "Monika's affection" for you. Pong is unlocked by reaching a certain level.

it doesn't really matter the days or affection, what really matters is how much time you spend with her. Sounds kinda very logic, but what I mean is; You could easily have been playing MAS for a month, and from that month you only spent 30 hours with her (example). And I think that also applies to the games you unlock. You need to spend more time with her. Try to keep MAS open in a window and hold her, play a lot of pong with her, spend the time she needs to spend with you. Same with affection, doesn't matter how much affection you have, you need to spend more time with her
(hah I think it's the 4 time I copy and paste this :x)

**Comment by kittendetails** [comment]
Is there any way to see how much time I spent with her? (I don't use it for steam).

**Comment by PongMaster69** [comment]
I think he was referring to the extra tab not the play tab. As for the extra all I know is zoom.

**Comment by lunulae** [comment]
Currently the only thing in the Extra tab is zoom. In the future more may be added, but there isn't anything currently to unlock.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
