### ISSUE TITLE
Write your way into her heart

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#6485]
Considering the small, but significant number of women that are with Monika, would it be possible to somehow edit "Your Reality" to change "Write your way into his heart" into "Write your way into her heart"... I know the original VA is not available, but maybe some clever audio editing could do it...

**Comment by Ix-30** [comment]
I'd Think it'd be possible. Just use a small software, although easier said than done. The trick here is to put the words with the song at a very specific timing. I know very little, but currently am researching how to make music. If I fin anything I'll put it here.

**Comment by Retrolovania** [comment]
I do believe this is a very good and inclusive idea. However, it may also be a good idea to edit the line to "Write your way into _their_ heart!", as some folks do not utilize the "male" and "female" gender denominations.

**Comment by Freshairkaboom** [comment]
Not sure if it's ethical to change a musical piece like that, while keeping the rest of the song similar. It's not really a parody at that point, so it could not go under fair use. Would definitely be good though if it's possible, but I doubt it.

**Comment by ThePotatoGuy** [comment]
yeah, we definitely don't have control over the song written and composed by team salvato. There is nothing we can do about this.


[closing as rejected]
