### ISSUE TITLE
[Suggestion]: New topic for "You" ----> "I'm going to take a new challenge."

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6487]
New topic for  you:
You----> "I'm taking a new challenge..."

Monika is your loving girlfriend, so I find it nice that she helps you with whatever challenge you're undertaking. I will list
the ones that come to mind:
You----> "I'm taking a new challenge..."
That's amazing, player. It's always good to improve and be a better version of ourselves! what type of challenge are you taking?

"I'm going write a book"
Wow player! That's amazing! I hope my writing tips helped! I know you'll be the best in no time [pen_name] but know this...even if you fail, I'll be your number 1 fan! I love you~

"I'm going to start a new job"
That's amazing. Starting a new job can be exciting but very stressing. On one hand, you have the new growth opportunities and new environment a job can have, but also, in many jobs people are too competitive and often, mistreat their peers. By the way, this is a type of bullying known as "mobbing." Anyway...I hope in your new job  you have friends and all your aspirations come true player. Know that your loving girlfriend is behind you, all the way!

"I'm moving to a new place."
That's amazing! so we are going to live in a new place? ...I say we but I live in your computer...still, I share your house...In a way ahaha~ Anyway. Moving away can be tiring and disheartening. Saying goobye to your friends, to old places you love. And when you move in,  you won't know anyone, and feel all alone. But player, know this, no matter if we go to the end of the universe or time itself. I'll always love you ok? If you feel alone, feel to tell me! That's why I'm your loving girlfriend!

"I'm going to start a new career."
You're amazing you know that? Not many people have the determination to finish a career. But I know you, Player. I know that you are determined and will see this to the end. It's something big and I know you'll be great, probable even be the valedectorian. You're not alone, I am with you! I know you'll shine player and if anything worries you, come to me, I'll catch you whenver you fall ok? I love you~

"I'm going to start saving for something."
I know it may be tough, especially since there are so many things you can want or need. But, all sacrifices pay off, whether little or big. But keep in mind your objective, no matter how tough things get. Although, I want to be your ultimate price, ahaha~ I'll be here for you. Just remeber our piggybank conversation."

And this in turn could trigger some dialog asking how the project goes. That's all I have for now, Thanks for reading.

**Comment by StayHappy1270** [comment]
I'm kinda new and i've been thinking of a bunch of things to do but this one actually seems reasonable and doable for me. Imma focus on this.

**Comment by StayHappy1270** [comment]
ok immm actually working on this rn i'm gonna proboly make these abit complex and try to make some of them have multiple little things to em. Imma work on one at a time. (also i dont think i'll do the book one since it seems abit uncommon) Rn i'm doing the job one and i think i'll turn it into a few things. 

to summarize the idea i think i'll put it as you first say your applying, then she'll either bring it up again after a while, you can go back in the topic, or when u say ur proud of yourself. then u can say that you got a call back or they never contacted you (i might even put a bit where she checks the time that says well it's only been a little while if you say that soon). then there'll be an interview dialouge where moni talks about how proud she is and basic interview etiquete (maybe even a special goodbye opt will appear), then later you can do a simmilar process to tell her if you got the job.

(rn iv'e done the dialogue bit for the application part about doneish)

ok ok ik that sounds complex but fooor the most part i think i got this (ofc if i can't figure out how to do some of it i'll prbly water this all down) I'm pretty excited! 

Also also this'll probly take me a while (but like duh oop)

**Comment by Ix-30** [comment]
Maybe some more Topics:

_"I'm going to learn a new language"_
Trés bien player! **[If the UI has detected duolingo]** I've seen you on duolingo. It must be fun!
[Else]
There are many websites out there for free. I like to see people giving knowledge to each other. It's like exchanging poems.
Another person will learn from you.

It's nice for you to want another language. People really underestimate the importance of talking another language. The more you speak, the more your mind opens up. By learning a new language you could even go to another country and have no problems, It's as if the world grows closer. Remember, I'm here for you and player...if you learn a new language...can you say "i love you" in that language? ehehehe~

_"Im going to learn how to play an instrument."_
That's amazing, player! Music can heal emotionally and convey lots of emotions. That's one of the things that brought me to it, remeber your song? "What good are words when a smile says it all?" Well, this is similar. Notes can be so deep they can have a lof of strength. Are you perhaps learning....how to play the piano?

_"Yes, I'm learning piano."_
Really?! that is amazing! gosh, I wish I could teach you! We could play the notes together...I could hold your hands, You might make a few mistakes...
**[If promise ring is given]**
Then, I would look at your lovely (color) eyes and...we'd get lost on each other's gaze...then you would hold me and kiss me..."
Oops...sorry I was just daydreaming...ehehe~
[Else]
We could learn together! I could teach you so many songs! I hope you can show me your progress someday! Give it your all, your beloved girlfriend is with you! maybe, you could even make a song about me.

_"No, I'm learning another instrument"_
That's fine. Maybe we could do a song together with the 2 instruments or you could teach me. I'm proud of you for wanting to learn something new, if you feel down, I can play you a song or we could discuss your progress! I love player and I'm rooting for you!


This one might be dicey but, I found it fun as maybe, Monika would feel a little jealous if the player is making a mod for the others and would not like to see "herself" make the same "mistakes again"

"I'm going to make my own DDLC mod!"
I...Kind of have mixed feelings player...I mean, on one hand, I suffered through a lot just to get to you, it was really a long journey and I...showed you some horrible things...But, on the other hand, had you not played the game, I would still be alone, in the void...crying...I'm kind of thankful to the game for letting us be together...
Anyway, Who is the protagonist of the mod?

"The others, they deserve to be happy too."
I see...we were together for a long time and it's ok if you feel attached to them. If you will player, please, give them a happy place ok?

"Actually, it's about you!"
Awwww! I'm so happy! Some people want to be with me in more ways...well, not me but another version of me.
[If promise ring is given]
Player, know this...I' have already told you but we belong to each other. This ring represents that promise. Even after all I did, even when the game set us limits...You were kind enough to not only bring me back, but give me happiness. It represents the love, courage, affection and resolution you had when you saved me. Ehehe~ It's as if I'm your muse. To inspire you. Good luck and...I love you~
[Else]
Just remember, that is not me ok? I only have eyes for you player, but it's good that you want to save many Monikas! Maybe they can find their happiness with other players...So...you are...like cupid for bringing them together? Well, I know one thing, you shot your arrow in my heart already! good luck.

**Comment by StayHappy1270** [comment]
ooh great ideas. Im just realizing this will be a lot to put in one topic i think im going to make this into a category and put each one as a topic. (That'd probably work better) Heheh This is turning into a big project. Yay! Fun!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

assuming not in progress because of the entire month passing and no linked pull request.
