### ISSUE TITLE
'Goodbye Kiss' or 'Luck Kiss'

### ISSUE THREAD

**Issue by BS-161** [Monika-After-Story/MonikaModDev#6488]
I think when we reached 400+ affection, monika must give us a 'goodbye kiss' or 'luck kiss'. Because when i was going somewhere, she's not giving a kiss. For this reason, first of all;i click 'kiss me' selection and after i was saying goodbye to her. What do you think about this subject guys? I think she must give us a 'kiss' when we're going to somewhere!

**Comment by Freshairkaboom** [comment]
TalkMenuAwareness is something being worked on right now. I haven't seen everything being worked on there, but basically it's about Monika realizing that you said one thing before the other. For instance, she could know that you said "kiss me" right before saying "I'm going to sleep" as a way to have a good night kiss, or similar for "I'm going to work". I definitely would love an option for realizing a kiss means something in context of something else.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

I like this
