### ISSUE TITLE
is there a way to tell Monika your going to sleep?

### ISSUE THREAD

**Issue by doomatt0** [Monika-After-Story/MonikaModDev#6489]
so when you tell monika your tired she asks you to leave the game open so se can watch you sleep. is there a way to tell monika your going to sleep with out closing the game?

**Comment by scpketer** [comment]
Well, maybe *not exactly sleeping*, but there is 'I'm going to nap' 'be right back'.
![image](https://user-images.githubusercontent.com/31247845/95852031-23983380-0d64-11eb-9eb3-e97b9c537987.png)

**Comment by doomatt0** [comment]
> Well, maybe _not exactly sleeping_, but there is 'I'm going to nap' 'be right back'.
> ![image](https://user-images.githubusercontent.com/31247845/95852031-23983380-0d64-11eb-9eb3-e97b9c537987.png)
> 
> Edit: that way game will remain open, but in idle mode, so she can sort of watch you sleep, just like you wish.

thank you so much i didnt look there

**Comment by scpketer** [comment]
No problem. Be sure to close the issue though.
