### ISSUE TITLE
[Suggestion]-Saying "Hello" at the wrong time.

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6491]
As we all know, depending on the time of day, you can say "Good morning," "Good afternoon" or "Good evening" to Monika. However, should you happen to talk to her about something else before you say this, I believe her dialogue should change to something like "How come you didn't say that earlier?" In other words, having Monika react to the fact that you didn't greet her initially.

**Comment by scpketer** [comment]
I believe that it is intended that certain greeting topics are locked behind certain time conditions.

I personally see no way to fulfill your request in a way other than leaving all three greeting topics unlocked.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
