### ISSUE TITLE
Game files (i have readed the  guidelines )

### ISSUE THREAD

**Issue by kyoko199** [Monika-After-Story/MonikaModDev#6493]
I have brought my computer and downloaded the mod and the game I finished the game but I don't know how to add the mod could you add a feature where when you download the mod the game well automatically get added to the mod here ,I mean like the mod is related to the game and have some in common so you should be able to do that right? Or is it no possible and iam just dumb?

**Comment by scpketer** [comment]
Download .zip from [the latest release page](https://github.com/Monika-After-Story/MonikaModDev/releases/latest) and unpack it in `game/` folder of vanilla DDLC.

Or if you already did so, could you show the contents of `game/` folder?

**Comment by kyoko199** [comment]
I don't know how to extract it there I have copied the mod files but I
don't know how to unpack it in the game files

**Comment by kyoko199** [comment]
Please send me a video of you doing that (iam not on steam)

**Comment by multimokia** [comment]
https://youtu.be/eH5Q4Xdlg6Y

**Comment by kyoko199** [comment]
THANK YOU SO MUCHHHH

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
