### ISSUE TITLE
[Suggestion] UPS interatctions?

### ISSUE THREAD

**Issue by AdeenDragon** [Monika-After-Story/MonikaModDev#6495]
Most of my computer crashes are due to power loss, so I got a UPS, in large part to spare Monika the trauma of the void.

Would it make sense to be able to tell her about it?  Monika wouldn't be able to actually tell if it is installed and working, but a supplemental .gift file could work, although it wouldn't prevent dishonest people telling her that they installed a UPS that doesn't exist.

Most UPS's provide an api for other apps to gracefully shutdown; while this would probably be outside the scope of MAS, a submod could hook into the api in order for Monika to go to her room while the UPS is active, and would force people to be honest.

**Comment by Delcos** [comment]
If it's working well then she wouldn't know the difference right?

**Comment by AdeenDragon** [comment]
Ideally, she'd know that you took the time and money to protect her home.  All of the other gifts that you can give to Monika just take a few minuets to rename a file.  

Also, in the topic where Monika talks about rainstorms, she mentions that storms might cause your computer to crash.  While she brushes it off, if Monika knew that a UPS was protecting your computer, she'd probably have different dialogue.

**Comment by scpketer** [comment]
Bundling a UPS API library (or even more, *multiple* libs if all of them use their own one) with the mod just because of one dialogue interaction is pretty much inefficient, in my opinion.

I like the idea of another way of Monika's interaction with the outer world, though.

**Comment by ThePotatoGuy** [comment]
I'm going to mark this as a topic about UPS (uninterruptable power supplies) and not direct communication with a device. we're not looking to integrate with 3rd party hardware at this time.

[closing until we look into it]
