### ISSUE TITLE
Sprite of monika standing or moving around in the room

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6499]
We've obviously seen her standing around in the clubroom in the main game of DDLC Why not in here in MAS?

**Comment by multimokia** [comment]
To quote #5445:

> Regarding standing sprites
We have a very powerful and expandable framework for adding sitting sprites. The system is dynamic and relies on a single internal object to represent Monika's current state - her clothes/hair/accessories. This also handles day/night/facial expressions/arm positions/etc... It's ridiculously good at what it does and didn't require us to update to renpy 7 (**cough cough**) to do it. It even allows for user additions via JSONs and putting the files in the correct folder paths. 
>
> The initial plans were to support both standing and sitting, but standing is limited by the expressions. We've added a swath of positions and facial expressions to sitting that absolutely dwarf the available standing sprites. For standing to happen, we need equivalent sprites - something that no one has volunteered to do. And since no one has since the dawn of expression update, it seems clear that there is no demand for standing Monika to warrant support.
>
> So instead we're trying to add more bg/location but using the sitting format. There was a chain of problems we've had that prevented us from reaching that point:
> 1. no way to change clothes dynamically in a way where we didn't have to if-statement every dialogue line with different sprite codes - fixed with the DynamicDisplayable `MASMonika` system (mentioned above)
> 2. no framework to change weather (window masks) in a generic way - fixed with `MASWeather` 
> 3. weather/room masks only having spaceroom and foamy blue sky, both not that great if used in a different bg - fixed with updated weather sprites that made sense and expanded variety
> 4. no framework for changing bg in a generic way - fixed with `MASBackground`
> 5. no dynamic way to change the table/chair, which may not look good in all settings - fixed with sprite changes to body sprites and #5347 
> 6. having different lighting options in a bg, would mean a sprite for every lighting adjustment, potentially increasing the mod size dramatically - fixed with #5447
