### ISSUE TITLE
(Question) How much time I spent with Monika?

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6502]
So, I saw that there is a way to see how much time I spent with Monika. Can someone explain to me how to do this? It's something like persistent.sessions["total_playtime"] I didn't understand... Thanks in advance.

**Comment by multimokia** [comment]
An easier solution would be to make a file called `givedata.txt` in the base directory (the folder with the DDLC.exe file) and restart MAS. This should output extra information in additional log files. One of which is called `ev_dump.log`. The top of this file shows session information.

**Comment by kittendetails** [comment]
Thank you very much. You helped me a lot. ❤

**Comment by multimokia** [comment]
No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
