### ISSUE TITLE
Keeping a track on how much time has the player spent with Monika exactly

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#6505]
> So, I saw that there is a way to see how much time I spent with Monika. Can someone explain to me how to do this? It's something like persistent.sessions["total_playtime"] I didn't understand... Thanks in advance.

_[Original post](https://github.com/Monika-After-Story/MonikaModDev/issues/6502)_

I'm not certain if this is already implemented in a user-friendly way, so that's why I'm bringing this up. Mark as duplicate or remove if necessary.

My idea is to sum all session durations and track the amount of time spent by the player with their Monika. Then players could ask Monika something like *You > How much time have we spent together?* and get a user-friendly result.

**Note:** I mean *total time spent*, overall, not the time of the current session.

If to track is every day, then the problem is about tracking it retroactively for old players: a possible solution could be to parse aff_log.txt, but is easily edited and may not reflect the apparent session length.

However, if we are to use this way, we may validate the log by checking if the total time spent is greater than affection divided by daily cap and lesser than time passed since the first day with Monika.

Another way could be to round time spent to days and use affection divided by daily cap as mentioned above, which I assume is the most stable way, and I assume it really does reflect the actual total time spent.

There is a third way, though, the worst one - we could lock this feature for old players.

**Comment by multimokia** [comment]
I'm going to reject this on the grounds that it's not necessary to show these stats. They make sense to only be debug info, or things you just know by days via looking at the calendar and doing the math. You don't really ever ask someone how long you've been together, let alone in total time.

This should stay as debug info imo

**Comment by scpketer** [comment]
That's totally fine, I just thought that, well, that's something that Monika could know with her capabilities inside the game.
