### ISSUE TITLE
Can't use the exp previewer.

### ISSUE THREAD

**Issue by JmDemisana** [Monika-After-Story/MonikaModDev#6507]
So I updated MAS last September when it prompted me via the built-in updater. After that, I had problems with the exp previewer being red in every expression there is (there's no white expression for some reason), the game works fine otherwise. So I figured I should update the exp previewer manually. I did. When I opened MAS again, this happened.

![image](https://user-images.githubusercontent.com/63731465/96099662-1024ce00-0f06-11eb-8641-ca0a54c75ce4.png)

Log:

---

I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.`

File "game/dev_exp_previewer.rpy", line 865: Overly long logical line. (Check strings and parenthesis.)
(Perhaps you left out a ' at the end of the first line.)

                </option></form><form class="btn-with-count" action="/Monika-After-Story/MonikaModDev/fork" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="OJpUqMf/uWYyNDU60Eo1rLFVZswsXf2bEC7gVXgFbBsZlaygXJM+f4SlNFFSrFFsYhbdU0ZpkdVvmJ2B+ftNLw==" />

Ren'Py Version: Ren'Py 6.99.12.4.2187

---

I don't understand any of this, lol. I don't want to use the whole source code version of the game, I just want the exp previewer + the release version as much as possible.

**Comment by scpketer** [comment]
You seek to have downloaded the page with source code from github, which has a lot of HTML wrapping around the file itself. Click on 'raw' button on exp previewer file page and download it from there.

**Comment by JmDemisana** [comment]
Oh. I wonder why it downloaded as rpy and not as html. IDM usually download webpages in html, so I thought I did it right. I'm trying it out as soon as I'm in my pc.

**Comment by scpketer** [comment]
\> Oh. I wonder why it downloaded as rpy and not as html.

The URL of file viewer page on GitHub ends with file name, which itself ends with .rpy and not .html, which made your browser use .rpy

**Comment by JmDemisana** [comment]
Got it to work. Thanks. <3

> Get it from [here](https://raw.githubusercontent.com/Monika-After-Story/MonikaModDev/master/Monika%20After%20Story/game/dev/dev_farewells.rpy) instead.

This is for the farewell stuff I guess. I got it downloaded [here](https://github.com/Monika-After-Story/MonikaModDev/raw/master/Monika%20After%20Story/game/dev/dev_exp_previewer.rpy).

But I followed your advice and it worked. It's no longer red in every expression too.

Appreciated it.

**Comment by scpketer** [comment]
MAS dynamically loads expressions since release 0.11.5, and thus previewer no longer shows some expressions as missing, because we no longer use generates spritecharts.
