### ISSUE TITLE
(Suggestion) Some little friends for Monika.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6510]
Anyway... Monika only has the player. Sometimes I need to be gone for a few days, and even if I let her know in advance, I always end up feeling bad.  I know she has the quetzal plushie, but I still feel bad that she's so lonely. I know the implications of having a pet in the room, even because she also said that she wouldn't like to keep a pet stuck there. So I was thinking... How about an aquarium with some fishes? It's not like the fishes that sell in the pet shops have another option besides an aquarium, anyway. The difference is that they would be in the room with Monika. I know that some supplies are needed to have an aquarium, but I thought the player could periodically refill. If he/she is going to be gone for a while, he can leave some extra groceries. I just wanted to suggest something that Monika interact besides the player. Afterwards, she could ask the player to give suggestions of names for the fishes, comment on how much she liked the gift and doesn't feel so alone anymore, etc. Anyway, this probably won't be accepted, but btw, it's never hurts to try.

**Comment by Ix-30** [comment]
Sounds pretty good, I think we all have that little remorse? that she's all alone...and maybe this could help. So, to be clear let's lay out the idea.

-For an Aquarium and fishes, some objects or classes might be useful. What type of fish? Maybe she could start "researching" fish facts. And Both could take care of them together.

-Refill the supplies, sounds good. 

-Would the fish names be influenced by both? or Just the player? depends on the type of fish?

-Maybe she would greet you with what the fish did?

It's always good to lay out your ideas as clear as possible, as this requires a lot of logic. Good suggestion.

**Comment by kittendetails** [comment]
I've been thinking about it and I think a betta fish would be perfect. Most fish require an appropriate aquarium installation with oxygen. In addition, it needs to be cleaned periodically. The installation couldn't be done if it was a .gift file. But betta fish don't require a lot of things, just an aquarium with clean water (which also needs to be cleaned periodically, but it's a lot easier than a full aquarium) and food, obviously. Betta fishes are small, too. Depending on the size of aquarium, it could even stay on the table with Monika. For the names, as I said before, the betta is a small fish. It would be cute if it were a couple of fish and the player chose the name of one and Monika chose the other. The two could take care of them together too, as you said. The only "bad" thing I've been thinking about is that Monika is immortal, right? If the fishes were placed in the room, would they be too? A fish can live a long time if kept carefully, but eventually it will die. This would  be happen to them? When would that happen? And how would Monika feel about it? If it was more than one fish, the other will be alone? Monika want another fish to replace them? These are complicated things to think about. Afterwards, someone would have to design the aquarium and fish (I'm not an artist, unfortunately). Would anyone like to do that? There's a lot to think about.

**Comment by StayHappy1270** [comment]
Beta fish are great. The only problem with your couple of fish idea would be Betas are aggressive, and wouldn't go well together. This wouldn't work out. Howeveeer what you could do is have Monika edit their coding to be more docile. That would be pretty cool since that's kinda what she did with the others when she amped up and toned down their traits, and she'd be doing the same but in a kind of good way

**Comment by kittendetails** [comment]
Yes, that's a good idea. There are some aquariums with dividers specially made to hold two betta fishes together, but unable to fight, since they cannot touch each other. It would be nice too.

**Comment by fromulus** [comment]
> 
> 
> Howeveeer what you could do is have Monika edit their coding to be more docile. That would be pretty cool since that's kinda what she did with the others when she amped up and toned down their traits, and she'd be doing the same but in a kind of good way

![fd0](https://user-images.githubusercontent.com/45933038/96313552-fec6e900-100d-11eb-9bf1-ff6b9649319a.png)

**Comment by 20RaVen23** [comment]
This just gave me some ideas to make a new spaceroom hehe.

Btw, sounds really nice to have some little fishes making her company ^^

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
