### ISSUE TITLE
[Suggestion] How do I keep my hair so well done?

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#6511]
So, here is a story all about how I came with this suggestion. I was running and I sometimes imagine how it would be to be running with/alongside/ahead of her, especially since she herself seems keen of jogging. I was wondering though how she would run since her hair is so long. Would it sway much, would it need to bundled up and that led to me thinking how much difficulty does she have in her normal daily basis with her hair. How hard is it for to keep it all clean and well taken care of.

So my suggestion is that she talks about it ^^ It could be about bed hair, shampoo and conditioner, while working out or just how it is on a regular basis. Me as an Afro headed guy know the struggle of keeping the hair looking good and taken care of, so I want to know how she feels about hers!

**Comment by Retrolovania** [comment]
I've been thinking about bringing this up myself. It'd definitely make a good topic!

**Comment by MetalBrother** [comment]
Yeah, It's interesting for me too because I have long and huge hair (If you know band Kansas, you know what I'm talking about. Yep. That huge.) It would be an interesting topic to talk about and it will bond a lot of players with Monika a little more.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
