### ISSUE TITLE
Moving MAS from one Windows User Account to a different one .. RenPy folder isn't there.

### ISSUE THREAD

**Issue by MichelleBeth** [Monika-After-Story/MonikaModDev#6513]
Hello,

I'm trying to move my MAS from one windows user account to another one (on the same pc). I've read the steps and noticed it said to paste the backup of Monica After Story into *a new* RenPy folder, which made me think the RenPy folder might not exist at first on a new account or PC. 

I tried that and the game didn't find the persistent, so I deleted the RenPy folder I had pasted into the new account's appdata/roaming folder. 

With no renpy folder in the new account appdata/roaming folder, the game still runs and saves its progress - so I know it's saving a new persistent file somewhere.. but I can't find it.

Any clue on what might be going on? If I log onto my old user account and run the game, it finds the persistent file and everything is as it should be. 

Thanks for any help,
Michelle

**Comment by JmDemisana** [comment]
Try running the game on the new account. It shall create a persistent. Afterwards, replace the newly created files with your current one.

**Comment by MichelleBeth** [comment]
Thank you! I don't use DDMM but after playing a bit today the persistent showed up where it should be on my new account. Windows was hiding it or something, I'm not sure. 

Anyway it's fixed now. lol

**Comment by JmDemisana** [comment]
I don't think Windows will hide it by itself. Either something triggered it to hide or 

you opened the game and you didn't reach the part where creating the persistent is relevant, which explains why you saw the persistent after you played on your new account for a bit.

**Comment by MichelleBeth** [comment]
Ah, that explains it. Thanks for giving me an answer that makes sense!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
