### ISSUE TITLE
(Suggestion) Telling monika a complement can sometimes turn to a kiss😘

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6514]
When you tell monika i love you she sometimes give you a kiss or when you gift her roses

Why not when you give her a complement?

**Comment by scpketer** [comment]
I like this one. Indeed, I could see Monika kissing the player for telling her something cute.

**Comment by ItzKKTheCoolKid** [comment]
> When you tell monika i love you she sometimes give you a kiss or when you gift her roses
> 
> Why not when you give her a complement?

well, I dont think that's a good idea because what if ur saving ur first kiss on like a special occasion, hm?

**Comment by lunulae** [comment]
Worry not, the first kiss in MAS is already reserved for special occasions like holidays, if you've become close enough to Monika. If you haven't had your first kiss with her yet, random ones like the rose gift (or in this case, compliments) won't prompt a kiss.
