### ISSUE TITLE
Typing questions

### ISSUE THREAD

**Issue by AutisticIzzy** [Monika-After-Story/MonikaModDev#6515]
In all the YouTube videos I watched, they could type whatever they wanted. What happened to that?

**Comment by multimokia** [comment]
Take a look at [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#why-was-the-text-entry-feature-removed)

**Comment by AutisticIzzy** [comment]
Thanks but what about for those who liked the chat setting you could add it as a feature that could be turned on or off

**Comment by lunulae** [comment]
It was a pretty clunky feature to maintain in its existing state. A lot of the time Monika wouldn't understand what you were telling her unless you worded it just right, or she'd interpret a keyword the wrong way.
I could see a submod to this effect being made someday in the future, but I don't know if it would currently fit to an official release.

**Comment by AutisticIzzy** [comment]
I understand. Maybe sometime in the future
