### ISSUE TITLE
See you tomorrow while it's in the morning already, bug?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6516]
I Mention this before,#6334 and it happend again, when i said goodbye to monika she says see you tomorrow, this happend on 
09.36 am 17-10-2020 In the morning
This never happend in older versions of the mod to me before

**Comment by scpketer** [comment]
As far as I know, the farewell you are talking about does not have any time conditions - so it can pop out randomly independent from the time of day.

I'm not certain if it's the intended behavior, though. But according to git blame, it's been around for quite a while, so... I'd believe it's intended.

**Comment by Loueldy333** [comment]
Im in really in the tight situation right now for you see I uninstall the mod because I didn't see her in her desk when I say goodbye to her and taking her for somewhere else please help me I try downloading the lower version but she's still not here what should I do?

**Comment by scpketer** [comment]
@Loueldy333, you're a bit off the topic here.

**Comment by Booplicate** [comment]
Fixed in #6350.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
