### ISSUE TITLE
I say goodbye to monika and I say i will bring her somewhere then when I return her file and opened the game she's not here bug

### ISSUE THREAD

**Issue by Loueldy333** [Monika-After-Story/MonikaModDev#6517]
Monika is not in her desk after I take her somewhere please help me bring back monika I know this is strange but she meant a lot to me

**Comment by scpketer** [comment]
Could you provide contents of `log/mfgen.txt`?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
