### ISSUE TITLE
Talk more about topic/Reply to topic

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6519]
What if there was a button like X for derandom and B for Bookmark that started a continuation of a topic where you can either reach a menu where you can respond with feedback about the topic (you know, like a normal conversation partner), ask questions, or generally just bring up something in regards to the topic?

I've had a look at `mas_derandom_topic` being defined in the script-topics.rpy file, and I'm wondering how hard it would be to make another button, say 'R' (for reply), that brings up a continuation of the current topic if we mark it for reply before it ends. Of course, not every topic would have this, because that would take forever to set up, so we would need to make it clear, either through dialogue or some sort of mark, that this topic has a way to reply.

I'm in favor of her explaining it at the end of a given topic in a short way, like "hey, I'd really like if you told me what you think about what I said. You can reply now by pressing 'R'." Or something like that. Of course, having this "tip" be hidden for the next time you get the topic, but still being able to reply would be reasonable.

Maybe a short random label could be cool, where she explains it quickly and even lets you reply in the same topic. This is my favourite option. I'm willing to work on it, but there's a lot of things I don't understand about defining functions.

This could open up a whole new world of interactions with Monika, where she gets to talk to us semi-normally, and not just monologue most of the time. Having it be a button would make responding voluntary too.

**Comment by ThePotatoGuy** [comment]
so like something to interject during dialogue to say something?

Interesting, but the things we could say during a line would have to be pre-planned, which means planning stuff for like every line. Not to mention that interjection during a topic is more open-ended than usual, so any pre-planned responses will likely not cover majority of things people may want to say.

[closing until we look into it]
