### ISSUE TITLE
[Suggestion] - BOOP!

### ISSUE THREAD

**Issue by GhostCommander44** [Monika-After-Story/MonikaModDev#6520]
A good day, sorry to bother you but i thought maybe it would be fun for the player to be able to BOOP Monika. If you click on her nose she will give a tiny respond to it.

Sorry if it is a lot of work but i thought it would be a fun little detail...

Have a nice day.

Bart Embregts

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473

**Comment by Okatart333** [comment]
Wow so many people want some form of a Boop. In all honesty I really hope this gets added.

**Comment by Ant9cp** [comment]
Is it ever going to be a feature?

**Comment by scpketer** [comment]
[Do the math.](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_interactions.rpy)

**Comment by Retrolovania** [comment]
Maybe add the Boop! feature as an Extra. Maybe in the form of a "Sense" toggle? When enabled, Monika can feel if you boop her with the cursor.

**Comment by scpketer** [comment]
>Maybe add the Boop! feature as an Extra. Maybe in the form of a "Sense" toggle? When enabled, Monika can feel it if you boop her with the cursor.

From what I've seen it's being placed in extra, yes.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
