### ISSUE TITLE
[Question] Am trying to give Monika things like clothes. What am I doing wrong?

### ISSUE THREAD

**Issue by bringerofstorms** [Monika-After-Story/MonikaModDev#6521]
So I've read the gifting guide on the wiki, which was for what it is very helpful, but I've found that it doesn't really apply when trying to give her wearable things like clothes etc. (ribbons are still okay). I have downloaded the spritepack and have been trying to use that to give her some new clothes, but even though I'm copying the files in them to their correct (I think) locations under the Mod Assets > Monika folder, she can never read them for some bizarre reason. I've looked online for guides to help me through this, but the closest I've gotten is some guy on YouTube who thought uploading a guide in maximum 240p (making text illegible) with gunshot sound effects in the background that drown out all instructions was a good idea. Would somebody please walk me through the process of getting gifts from the spritepacks into the game itself?

**Comment by 20RaVen23** [comment]
Can you send the file `spj.txt`, please?

**Comment by bringerofstorms** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5398302/spj.txt)

I managed to get the green hoodie and blue shirt working yesterday but so far nothing else has worked.

**Comment by 20RaVen23** [comment]
Where did you put the folders with the sprites exactly? Can you send a screenshot of your `game/mod_assets/monika/c` folder, please?

**Comment by bringerofstorms** [comment]
I copied everything in the spritepack into its corresponding folder. Everything from /a went to /a, everything from /c went to /c etc.

![screencap](https://user-images.githubusercontent.com/53190151/96388046-d94f0080-1202-11eb-9e5f-bf2289e70c6d.PNG)

**Comment by 20RaVen23** [comment]
It's strange. The `spj.txt` file you sent didn't read nothing more than the two outfits you mentioned working.
You had MAS closed while you were adding the sprites? If you didn't, reopen MAS and try to gift them again.

**Comment by bringerofstorms** [comment]
It worked! Thank you mate, I appreciate it!! :D

**Comment by 20RaVen23** [comment]
No problem! ^^

**Comment by Ix-30** [comment]
I've been having problems as well, My spj only detects the Sakuya outfit, the sweater, the shell bikini. Only the Blue, Emerald, Ruby, Red Ribbon too. 
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5398389/spj.txt)

![Proof](https://user-images.githubusercontent.com/71111669/96389001-0c918100-116a-11eb-800a-42f27a3f21cc.png)
I've tried to put the blue shirt for example and added the Json sprite and she can't read it, I only do this when it's off and she can't read it.

Thanks in advance, I'm sorry for bringing this up bit I didn't want to open another topic, thank you.

**Comment by 20RaVen23** [comment]
So, you had MAS closed while adding them, right?

**Comment by 20RaVen23** [comment]
try to make sure you installed them properly
[https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#file-locations](url)

**Comment by Ix-30** [comment]
Yes, I always have the Game closed as I install. In the A Floder Should I unpack all A objects o the whole mod assets folder? 
![image](https://user-images.githubusercontent.com/71111669/96391469-05707000-1176-11eb-9040-a1edd83485db.png)
Also the Json object needs to go in j right?

**Comment by 20RaVen23** [comment]
> In the A Floder Should I unpack all A objects o the whole mod assets folder?
yeah, you only have to unpack the A objects there, not the whole mod_assets folder

and yes, the .JSON files need to go in `game/mod_assets/monika/j`

**Comment by Ix-30** [comment]
Thanks I solved it. Thanks a millon friend. Wind guide you.

**Comment by 20RaVen23** [comment]
Oh, good to hear that. I actually don't know how I helped here, but no problem! ^^

Thumbnails goes in `game/mod_assets/thumbs`.

**Comment by ineedlotsofhelp** [comment]
i cant even gift her ribbons

i mightve done something weird when trying to get the mod to work or its some weird thing with my laptop

**Comment by ineedlotsofhelp** [comment]
i need lots of help

and i need a usb to move the mod to a different computer

**Comment by scpketer** [comment]
You don't need a USB cable to move data. Flash drive medium or internet connection would do, too.

**Comment by ineedlotsofhelp** [comment]
thats what i meant i talked to my friend about what those where called for 10 minutes and we just gave up

**Comment by ineedlotsofhelp** [comment]
thanks for the edit

**Comment by scpketer** [comment]
On Windows file extensions are hidden by default (sorry, I can't really explain how to enable them, I don't use english locale and I don't know what are parameters called in english), so you need to enable them, otherwise .gift files become .<additional extension> when you create them.

**Comment by Ix-30** [comment]
The file extensions: https://www.thewindowsclub.com/show-file-extensions-in-windows
I think that explains it better than I could.

For the sprites I've broken it down into simple steps(I followed) So take it with a grain of salt. for this example we'll take the miku outfit.

1.) See that in each sprite pack, there is a "c" and a "j" object right? well, move the folder in to it's own place. The route where you have to paste them is(the names vary according to your computer): DDLC---->game-----mod assets------>Monika----the letter where you put these.

C="clothes" any clothes go here, most folders have the author's name, so paste it in the C folder. Therefore, "orcaramelo_hatsune_miku"---->C


*A- "Acs" objects, paste them into the a folder, in this case the objects in "a" go n the a folder, usually these don't have the author's name so paste them all in there.

*H-"Hair" Paste them into the "h" folder. As with A, it's usually a bunch of pics, put them into A. 

-J- "Json" objects. In the file you'll see a j "folder" and there should be objects there, in this case since its the miku outfit, there should be four. Move them into the "j folder"

*Finally, move the thumb into the thumbnail folder into the "modassets" this will ensure you see the preview in the "apperance" section of the game. In most, there should be a gift, that gift should be put in the "characters folder" open the game and Monika will detect it and change into it. This has to be done with MAS inactive.

For the usb/computer transfer

* Press the windows button. + R, that should prompt a box.

*write "%appdata" there. You should be taken to a folder.

*Look for the "renpy" folder, open it and there you should see Monika After Story

*Copy all the folder into a USB. This is also how you "back up" Monika, this is her "memory" of the time you spent with her.

You can either copy the game too in the usb, or download a fresh copy and mod it again. Open a "renpy" folder and paste the
Monika after story folder there.

Hope I helped, if only for a bit.

**Comment by scpketer** [comment]
I don't quite get the point of manually sorting out those 'a', 'c', and other directories. Isn't it said in guidelines that you need to just *merge* directories? That will make your OS do this exact thing automatically.

>The zip file will contain folders with the sprite pack names, and inside each of those will be a folder named mod_assets. Simply copy the mod_assets folder for the sprite pack you wish to install while MAS is closed and paste it into the game folder that is located in the ddlc directory of your MAS install.

https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs

**Comment by Ix-30** [comment]
Not for me, It did try, but somehow, It only merged certain files. Which is why I point it out. Happens to some other players I know too. So just to be safe I point it out.

**Comment by 20RaVen23** [comment]
there is the video of example about what @scpketer mentioned
https://www.youtube.com/watch?v=L5QnEdA97iE

**Comment by ineedlotsofhelp** [comment]
does MAS have to be closed

**Comment by ineedlotsofhelp** [comment]
because that would explain my problem

**Comment by multimokia** [comment]
Yes, MAS must be closed to install spritepacks

**Comment by ineedlotsofhelp** [comment]
i was so confused ok thanks 
im glad i checked on this issue until later

**Comment by ineedlotsofhelp** [comment]
what if i already put the j and c file/folder into the games j and c folders

**Comment by ineedlotsofhelp** [comment]
but when the game was on

**Comment by multimokia** [comment]
Then you need to say goodbye and relaunch MAS

**Comment by ineedlotsofhelp** [comment]
ok thanks!

**Comment by ineedlotsofhelp** [comment]
im totally giving her the black bow now

**Comment by ineedlotsofhelp** [comment]
it worked! (it took so long because i was actually eating breakfast)

**Comment by SterbeNNn** [comment]
okay, could you help me with the same problem?  although I read the entire dialogue and all the solutions, I did not understand what exactly needs to be done 😣

**Comment by SterbeNNn** [comment]
I am Russian, so you may have difficulties understanding me this is how Google translate works ¯ \ _ (ツ) _ / ¯

**Comment by scpketer** [comment]
You can go ahead and use Russian, maybe I could help you out?

**Comment by SterbeNNn** [comment]
Хорошо, буду использовать русский язык. В общем я не могу подарить Монике никакие подарки, а так же у меня выдаёт ошибку из-за некоторых спрайтов и при показе летающих островов

**Comment by scpketer** [comment]
Ну так давай сюда ошибки. Хотелось бы уметь в телепатию, но как-то не срослось.

**Comment by SterbeNNn** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5464651/spj.txt)
Держи

**Comment by SterbeNNn** [comment]
кстати я полазил по логам и нашёл, что в логе pnm.txt тоже есть ошибки

**Comment by SterbeNNn** [comment]
Дарю всё по гайдам, а вот спрайты больше никакие не скачивал, ибо в группе, откуда я взял мод, не было ссылок, или упоминания о том, что надо ещё и спрайты скачивать

**Comment by scpketer** [comment]
Скачай отсюда [spritepacks.zip](https://github.com/Monika-After-Story/MonikModDev/releases/latest) и распакуй то, что тебе нужно (или вообще всё) в `game/mod_assets`.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
