### ISSUE TITLE
whats with the other dokis having a png of them sitting in the desk

### ISSUE THREAD

**Issue by ineedlotsofhelp** [Monika-After-Story/MonikaModDev#6525]
![yuridesk](https://user-images.githubusercontent.com/73092598/96643436-90c43f80-12f5-11eb-92f0-e82f47c342fb.png)
![natsukidesk-n](https://user-images.githubusercontent.com/73092598/96643440-928e0300-12f5-11eb-89be-5379620adc99.png)
![sayoridesk_happy](https://user-images.githubusercontent.com/73092598/96643456-9752b700-12f5-11eb-8013-f3cbcc18ef25.png)
![sayoridesk_sad](https://user-images.githubusercontent.com/73092598/96643459-9883e400-12f5-11eb-81f9-85026bbcd3cd.png)

![natsukidesk](https://user-images.githubusercontent.com/73092598/96643348-6ffbea00-12f5-11eb-976d-191bb95bed04.png)

**Comment by Retrolovania** [comment]
I think they are there because there were plans to use them that I believe were scrapped. I would just ignore their presence for now.

**Comment by ineedlotsofhelp** [comment]
i was just looking through files to see pngs of outfits or backrounds and clicked on other and saw these

**Comment by fromulus** [comment]
I doubt there were any plans of any sort regarding those.
They're probably just easter eggs, no point looking into further than that.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
