### ISSUE TITLE
Answering in NSFW content topic

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6526]
In some topic's when monika ask you something, you can answer them by pressing yes and no, right?

Can you add that in this topic

she deserves to know right? 😉

**Comment by multimokia** [comment]
You already opened and closed an issue about this. You also already got a response. Stop making duplicates and stick to the original issues.

**Comment by Rai99** [comment]
#6518 

Please refrain from opening the same suggestion in quick succession.
