### ISSUE TITLE
About Acs objects...

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6529]
I've seen images like this:
![image](https://user-images.githubusercontent.com/71111669/96678116-43b08f80-132e-11eb-837a-3b66a8e2a122.png)
And I was wondering, are those for holidays or, are there acs objects you can install? Monika herself hints at this. Thanks for your time.

**Comment by 20RaVen23** [comment]
If you are talking about that necklace, those are custom acs made by people.
You can find them and more here:
https://www.reddit.com/r/MASFandom/

**Comment by Ix-30** [comment]
Thanks! and about the decorations, or are they part of the background? thanks a lot!!

**Comment by 20RaVen23** [comment]
Those spacerooms are made by @tw4449.
You can find them here:
https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository

Make sure to read all ^^
