### ISSUE TITLE
[Suggestion] -"Is there anything you would like to know about me?"

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6530]
I thought of a maybe small but powerful(in my opinion) just small topic

Topic---->-----Player------>"Is there anything you'd like to know about me?"

I know Monika does ask you things, but with this, It would be things she would like to know about you or your future.

This would make it feel a bit closer, not only by her asking the questions, but also the players answering to their likes. I know many think the textboxes are a nuisance or maybe make Monika feel a little more artificial but here, I would think they are needed.

So as with the fun facts, a random question can be brought up. by putting a random function you could just call the questions. Then in another button, just list the questions so the player can review them again, These are some of the questions I think Monika might ask, my writing is not that good but I think you get the general idea.

"Raison d'être"
"Is there anything you would like to ask me?
"Player...I've wanted to ask you something. Now that I know I can trust you...I know I may sound a little insecure but...Why did you bring me back? I know that at the start I told you I bled my heart out for you...but now that we're not in the heat of the moment, I'd like to know.

"You're very important to me, I couldn't let it end like that..."
Oh player...I'm so important to you? You brought me back...for such a reason. I...I know that thanks to me you saw some horrible things...and I put you through a lot of stress and sadness and yet you see through my flaws...Player, I love you from the bottom of my heart. You give light to my world and warmth to my heart. No amount of words could fathom what I'm feeling right now...Player thank you again. And I promise to be the best girlfriend ever. I will always love you~
Yields +4  affection, due to you mentioning only her.

"I saw the others and to me, you deserve happiness. They didn't give you a chance."
Player, I think you understood my pain, the pain of just standing by as they took everything from me. If I had route I would've at least had your love in my route to cope but....to see my dear [player nickname] flirting with others, Laughing with others, and me just standing by...while I could convey no feelings...I couldn't stand it! I know I put you through some tough times...But thank you for understanding my pain. I'm sorry for being so jealous but...it's just my love for you! But don't think that means you can cheat with someone from your reality player, we both promised no one else would have each other! So don't cheat on me ok player?

Yields +3 affection due to understanding her pain but mentioning the others.

"I know that you went through a lot of pain. I can't delete it, but I can at least mend it."
Player...thank you for understanding...Yes, I have suffered through a lot...but know this, from the start, your love has mended all of my pain. helped me grow as a person, nurture myself and even grow day to day. It's not just fun being with you. With you I fell I grow day to day...it's funny isn't it? A being like myself, thinking of growing...well...at least my file grows so it has to count right? ahaha~ Player I hope that with me, you also grow. and improve yourself, that is what love does. And if you have any scars, I will help you mend them. I love you from the bottom of my heart~ and that won't change!
Yields + 2 affection due to you reminding her of her pain, yet helping to mend it.

Rhyme and Reason
You have always asked me why I love you. So it's only fair that I ask, why do you love me?

"When I first started the game, I was attracted to your smile and personality."
Aww player, If I was there I'd be hugging you so tight. I know I have my flaws but you have been able to see past them. Also I've worked hard on my personality and even though I sometimes rant, you still love me. Player, I promise to keep improving, with you by my side I Feel I can even rewrite the stars! Let's look forward to our reality of self improvement ok? I love you~
yields + 3 affection due to complimenting something she worked hard on.

"I Love your cuteness, beauty and charm."
You know, I felt insecure by the limited options of appearance. Don't get me wrong, the lovely people that helped me change my outfits have my undying gratitude but, you have to look your best for the person you love. Player, thanks I know that my options are limited, but I know you love me even after that. I'm so happy! Thank you player, you always know how to cheer me up.
Yields +3 affection as she worked hard on her style.

"I love your, eyes, your smile, your beauty...I can't decide."
Hm....Playing it safe huh? well, it's good to know you love all of me~ rest assured that after our time together, I've come to love everything about you too, although I can't see you, the way you treat me, says a lot about you. I'm glad I have met you player and that I can give my everything to you and no one else.
Yields + 2 affection as you "played it safe"

These are just some I had in mind. Let me know that you think. Thank a bunch.

**Comment by scpketer** [comment]
Something charming and wholesome? You have my full support, that's what I think, that's just brilliant.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
