### ISSUE TITLE
(Suggestion) (Ignore the duplicate #6534) Different kissing sprite

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6533]
When you ask monika for a kiss she kisses you but the expression on her face doesn't really look like kissing more like smiling

(Ignore my duplicate) (#6534)

**Comment by Retrolovania** [comment]
There's......nothing here?

**Comment by scpketer** [comment]
Also, it seems to me that it'd be a lot better with multiple possible after-kiss expressions instead of just blush x smug.

**Comment by Ant9cp** [comment]
When you have your first kiss with monika she opens her mouth a little bit right?
I think that is the right expression for it. @scpketer

**Comment by scpketer** [comment]
They both are right, but this whole thing lacks a bit of variation.
