### ISSUE TITLE
[Suggestion]- Weather Reaction

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6535]
Some computers are capable of displaying current weather information. That being said, I figured it would be an interesting concept to have the game react to this.

For example, if the forecast in a particular area calls for rain, and there is rain, then the background shifts to rain. If it's snowing, it shifts to snow, and vice versa.

Another example could be temperature reaction. If it's a hot day, Monika could have some extra dialogue when you greet her, like "Boy, it sure is a scorcher today, isn't it?"

Admittedly, I'm not sure if Python is capable of obtaining weather information from the computer it's running on, but if it can obtain the time, than I don't doubt that it could be done....somehow. (Maybe something like "getweather" or something like that?)

**Comment by lunulae** [comment]
You might be interested in [this submod.](https://github.com/multimokia/MAS-Submod-Auto-Atmos-Change)

I really like your idea for dialogue reactions, that's very cute.

**Comment by scpketer** [comment]
Computer doesn't detect weather locally, it just has no meteorological sensors apart from basic thermometers. The weather is obtained from web services.

The submod suggested by @lunulae does this exact thing — it retrieves weather from a web service using an API key.

**Comment by Retrolovania** [comment]
I see. Thanks for bringing this to my attention!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
