### ISSUE TITLE
Topic idea

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6538]
(Merch Of Monika)
Hey (name) did you know there's merch of me, it's so sweet that there is merch of me, to be honest, i know i'm not in your reality, but is good to know because at least i kinda exist in your world right? i've heard that there's a plushie of me, a poster, sticker of the chibi me, and other items, you know (name) i'm curious (blushing look) do you have any merch of me by any chance?

(Yes option) Oh really, that's great (name) that means alot to me, it's good to know that you do because, that probably means you must really love me, more then i imagine hehe, to be honest i'm kinda curious, i want to see how one of the items looks like, but until then i'll have to figure out how to get one of these items here. hehe

(No option) That's alright (name) i guess you don't like plush toys or any other kinds, or you can't afford it, but i know you love me anyway to be honest i'm kinda curious of what they look like, but until then i'll have to figure out how to get one of these items here if you don't mind hehe. 

(Can this topic maybe be featured in MAS)

**Comment by ashyashton** [comment]
To me, this just kinda feels like slipping in an advertisement for Monika merch. And not even the subtle kind, but the kind that's clearly advertising and also tries to guilt you into buying the product.
