### ISSUE TITLE
reset the dialogue

### ISSUE THREAD

**Issue by JUSTMonika15** [Monika-After-Story/MonikaModDev#6541]
I have asked Monika all the questions, so I wonder if we can make a reset button in order to read those topics again?(just like the first time they appear in "never seen" folder)

**Comment by scpketer** [comment]
No, you cannot reset topics (to make them appear 'unseen') without any persistent file manipulations.

**Comment by fromulus** [comment]
A reset topics button's likely never going to happen anyway, as it would essentially mean brainwashing Monika (or have her pretend she doesn't remember anything of your previous conversations, which is pointless and silly).

Not to mention that would mean being able to repeat the affection granting topics and be able to farm that way.
I think the mod is better off without an option like that, and if it does make it in, I say everything should be reset as well (affection back to 0, Monika forgets about all the events and holidays you've spent with her, all unlocked clothes, spritepacks and so on are locked again, and so on).

**Comment by JUSTMonika15** [comment]
> A reset topics button's likely never going to happen anyway, as it would essentially mean brainwashing Monika (or have her pretend she doesn't remember anything of your previous conversations, which is pointless and silly).
> 
> Not to mention that would mean being able to repeat the affection granting topics and be able to farm that way.
> I think the mod is better off without an option like that, and if it does make it in, I say everything should be reset as well (affection back to 0, Monika forgets about all the events and holidays you've spent with her, all unlocked clothes, spritepacks and so on are locked again, and so on).

I was just thinking about put those topics such as "writing tips#1~5" and other things like that in the "unseen" folder and update everyday(just like the first time I disscussed those with Monika), I thought that would help me review those topics as"Monika's daily tips" instead of just click in to the menu and finished watching them in few minutes. Anyway, thanks a lot.

**Comment by multimokia** [comment]
You can just bookmark the topics instead

**Comment by JUSTMonika15** [comment]
> No, you cannot reset topics (to make them appear 'unseen') without any persistent file manipulations.
> 
> Edit: you can use in-game console though. But regardless, you can always find most of your questions in 'Hey, Monika...' menu.

ok thanks

**Comment by JUSTMonika15** [comment]
> You can just bookmark the topics instead

thank you for your advice!
