### ISSUE TITLE
Let the player add events to the calendar

### ISSUE THREAD

**Issue by AinzYnos** [Monika-After-Story/MonikaModDev#6542]
Let the player add their own events to the calendar so Monika will notify the player about the event on the given date.

**Comment by Rai99** [comment]
Custom Calendar: #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058, #5402, #5551, #6208

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
