### ISSUE TITLE
Hoping 2021 won't be so hard, either

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#6547]
This is probably already scheduled because (as it seems to me) it's quite an obvious topic that Monika could bring up in the last few days of the leaving year 2020, yet I'd like to make it clear.

So far 2020 seemed like a really hard year, and I'm probably being too pessimistic here, but it could certainly go way worse than it previously was. That being said, let's hope we'll actually make it through to the upcoming 2021 and it'll be another calm year.

Monika could refer to the Iranian conflict of January, or to the covid-19 pandemic (which was mentioned earlier in summer, if I recall correctly) - we probably don't need to literally enumerate all the bad things that happened, just something to point out what makes this year so (in a really bad sense) special - and express her relief because the player actually made it through safe and sound, and her hopes about the upcoming year?

Whoever this thing finds, what do you think?

**Comment by lunulae** [comment]
I'm not sure how much we want her to talk about specific events, but I do think having this year's New Year event reflect on how tough this year was is a fantastic idea, especially considering just how global the troubles of this year were. I'm very into this suggestion.

**Comment by scpketer** [comment]
Great to hear! I'll try to get to work on this one soon, if anyone already got something — I'm ready to collaborate.

**Comment by Booplicate** [comment]
This will be another topic that will be seen only once, so I'm not sure about it. Although, I am sure we don't want to mention everything that happened (especially conflicts). Whenever you mention something global, you bring politics in the mod.

**Comment by scpketer** [comment]
I don't want to introduce politics into mod either. But global things are not always political, recent frightening pandemic is a great example.

**Comment by Rai99** [comment]
We generally avoid topics that have an expiry date or that will go out of relevance eventually, and I'm not a fan of talking about 2020, because it's pretty much a meme at this point. 

Mentioning covid was an exception mostly because it's a matter of health and safety across the globe.

**Comment by scpketer** [comment]
Everything can be memed, we're living in 2020, after all. We can't go out of Monika's character, right, but we can't discard anything that has even the least relation to memes, can we?

**Comment by Booplicate** [comment]
> But global things are not always political, recent frightening pandemic is a great example.

You say the pandemic has nothing to do with politics, I say it has. And here we have a conflict.

**Comment by Rai99** [comment]
You also mentioned possibly mentioning the Iranian conflict, which probably doesn't have significance to everybody.

**Comment by scpketer** [comment]
Entirely artificial, actually. We'll have to wait for a third party to resolve it, I will refrain from the escalation.

**Comment by scpketer** [comment]
> You also mentioned possibly mentioning the Iranian conflict, which probably doesn't have significance to everybody.

Just as an example of event with potential severe consequences.

**Comment by Retrolovania** [comment]
Is Monika even aware of what's going on right now, though? I've never heard her talk about it, not even once...

**Comment by scpketer** [comment]
Assuming she did know about covid pandemic, yes, she would know about other sad things going on.

**Comment by ThePotatoGuy** [comment]
2020 was such a chaotic year that I think it's definitely something that can be talked about in the future. 

[closing until we look into it]
