### ISSUE TITLE
(Suggestion) for upcoming new years day 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6551]
I know one of the members of this mod are all busy with other enhancement's for this mod, and it's probably too early to think about new years day But, almost everyone uses fireworks outside right? why not add like a event that you see fireworks outside the room?

and have Monika or Chibika setting it up, and chibika did help setting up the birthday suprise for monika after all.
 
(What do you think?) 🤔 (It would be very nice if this feature happens)

**Comment by scpketer** [comment]
I don't see anything bad about it, moreover, I see it as a really good idea. 

We need visual effects for this one, though.

**Comment by Okatart333** [comment]
and maybe Monika could have special dialog when she sees the display.

**Comment by scpketer** [comment]
Can't help but recall [this awesome artwork](https://www.reddit.com/r/DDLC/comments/aepqxf/over_the_sea_of_lights/).

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
