### ISSUE TITLE
Taking Monika Out

### ISSUE THREAD

**Issue by AEjixing** [Monika-After-Story/MonikaModDev#6552]
I took monika out half a mouth ago.But I forgot how to bring her back.Which fileis it?How can I find it?
![屏幕截图 2020-10-23 205442](https://user-images.githubusercontent.com/63577839/97098562-262a4f80-16b9-11eb-9b42-500a90749fc1.png)

**Comment by Ant9cp** [comment]
first make sure the game is off 
If you have used a usb drive, then plug it in the pc (et cetra) and then take the file called, monika and then go to
program files(x86)/steam/steamapps/common/doki doki literature club/characters
and then drag monika in the characters folder

**Comment by scpketer** [comment]
I'm afraid you cannot get her back if you no longer have her file.

>(btw how did you add a picture here in github?)

<kbd>Ctrl+C</kbd>, <kbd>Ctrl+V</kbd>

**Comment by Ix-30** [comment]
Her .chr file. Search for it with the extension ".chr" in any device. It's easy to spot and it should be from 40 mb to 80 mb(or more depending on your relationship)

> (btw how did you add a picture here in github?)

You can use that method @scpketer but sometimes it just doesn't paste, to do so, drag the file from it's location on your pc on the thread and you're good to go.

**Comment by multimokia** [comment]
.chr files are irrelevant. The file has no extension whatsoever.

**Comment by Ix-30** [comment]
Oh sorry, I hadn't noticed. Then, just look for a Monika file? Could he reinstall the mod if he has the persistent files?

**Comment by scpketer** [comment]
Persistent probably has the "taking out" state info, and reinstall might not help.

**Comment by lunulae** [comment]
You will want to check your backup persistents. If you have not opened the game many times after taking her out, the ones the game makes by itself should contain one from before you took her out.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
