### ISSUE TITLE
[Suggestion] Topic: Triangular Theory of Love

### ISSUE THREAD

**Issue by 3amThoughts** [Monika-After-Story/MonikaModDev#6553]
I've been playing with this random dialogue idea for a while now. With Monika's interest in psychology, talking about a Theory of Love seems to be right up her alley. I'm afraid I don't know how to code, but if maybe someone who does could use this dialogue:

Hey [Name], have you heard of the Triangular Theory of Love?

It was developed by a psychologist named Robert Sternberg, about relationships.

Basically, the theory states that love has three components,

Emotional intimacy, passion/lust, and commitment.

Different combinations of these three components make different types of love!

For example, if a relationship has intimacy and commitment, but no passion, that's called Companionate love.

Like love between family members, or close friends.

If a relationship has Passion and commitment, but no real intimacy - that's fatuous love.

An impulsive whirlwind of a relationship. Think Romeo and Juliet.

And if a relationship only has commitment, with no intimacy or passion...

That's empty love. Staying together simply out of need, or obligation.

There are actually quite a few combinations that come out of Sternberg's three factors,

though I'm not sure I agree with his theory completely.

Love is so unique and different for so many people after all...

How can you just sort it into categories like that?

Still...Sternberg said that there was one ideal type of love.

Love that combined all three of these factors. Intimacy, passion, and commitment...

Consummate love. True love.

If I did have to put our love into a category, [Name]...

I think we both know where we would fit!

**Comment by Freshairkaboom** [comment]
Well, I agree that I wouldn't agree with that theory at all. The ideal type of love is a combination of the three? So familial love is not ideal? Hmm.. Would still be interesting to talk about, I suppose.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
