### ISSUE TITLE
(Suggestion different look to the hairstyle down) Monika's hairstyle down similiar as yuri's?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6554]
What's your opinion about monika's hair when it's down doesn't it look the same as yuri's hair 
(except the color of course)

**Comment by scpketer** [comment]
I don't see anything bad about her hair style looking similar to other girls'.

Short hair looks like Natsuki/Sayori's, long one, as you say, like Yuri's, I had her having every of these and they all look just as great.
