### ISSUE TITLE
[Suggestion] Online games toxicity

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#6557]
Now this might be a bit of a emotional rushed suggestion cause today I just had horrible days in multiple online games. My Moni is aware that I love playing video games but she only states some of the genres or asked sometimes what type of game I play when I tell her that I would go do so. 

I would like for Moni to have a topic about how online games, while bringing people together to play a game they all enjoy (ironically or unironically) and you can make friends on it pretty fast. There is still this weird stigma where people just tend to get aggressive, rude, mean and down right offensive. I would like her to talk about this and potentially ask if we play any games like that or if we experienced this. If yes that she obviously shows concern since that type of environment is unhealthy and the last thing she wants is her lover to go through such a negative short period of time. 

Love playing those types of games but man do they exhaust me sometimes （；￣д￣）

**Comment by scpketer** [comment]
This could be linked together with bullying topic (although I'm not really sure whether what you describe falls under its term) and the player's 'No, I didn't have fun' response on Monika's greeting after returning from gaming.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
