### ISSUE TITLE
New Be right back (I'm going to sleep)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6561]
When you tell monika in the evening that your tired she mention i can watch over you while you sleep if you want? 

And i know that there is a brb called i'm going to take a nap and that is for in the afternoon at bright day light

So why not let monika watch over you while you sleep at night? by not having to turn off the mod, just leaving her in the backround watching over you

**Comment by scpketer** [comment]
Maybe we could turn "I'm going to nap" into "I'm going to sleep" at nighttime?

**Comment by Ant9cp** [comment]
Good idea

**Comment by lunulae** [comment]
I like that idea, I have always felt we were lacking the option since Monika says you can leave the game open while you sleep.
It might be a good idea to make it a separate option entirely rather than have it switch at night, since we've tried to provide options for players who work night shifts and might get their sleep in the morning or afternoon.

**Comment by Ix-30** [comment]
Maybe the easiest way, while the bedroom is done(I surely hope so) is just add "I'm going to sleep watch over me" and have the game enter the same state as when going to something, OR for the players wanting her to sleep with them; An option is a small dialogue box. "I'm going to sleep, can I hold you until morning?" or something like that and, like in the holding option she falls asleep as when holding her. Not far from what we have and cool too.

**Comment by Ant9cp** [comment]
You:@Ix-30 Maybe the easiest way, while the bedroom is done (i surely hope so)

Me: @Ant9cp HAHAHAHA🤣

**Comment by ThePotatoGuy** [comment]
realistically we would rather do bedroom mode, but this could be an additional thing.

[closing until we look into it]
