### ISSUE TITLE
(Suggestion) New compliment ---> "You are so sweet!"

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#6563]
Well, we all know that Monika is a very good girlfriend. She's always saying how much she loves you, how lucky she is to have you, and always when you say you're sad or something like that, she tries to cheer you up. So I thought there might be a compliment to tell her how sweet she is. Here it goes: 

(First time): "You are so sweet!" 

O-oh... (blushing face) Do you really think so, player? (blushing smile) I really don't know what to say, when you've been the only sweet with me all this time... I'm so glad you think that. 

Option 1: Hearing your sweet words about me always brighten my day! (Increases +3 affection points)

Oh player... I had no idea that my words had that effect on you. I just tell the truth: You are amazing and the best partner I could ever want. I love you, player~

Option 2: I want to make you feel special just like you do to me. (Increases +2 affection points)

Don't say that, player. Just spending your precious time with me makes me feel like the most special girl in the world. Be yourself and you will already make me happy!

Option 3: You are the sweetest girl I've ever met. (Increases +1 affection point)

Thank you, player! (smiling face) I'm glad you think that. I will always be here to say sweet things to you. You are my sweetheart, after all~

After the first time: "You are so sweet!"

Thank you for saying that again, my love! (blushing smile) You're always so sweet with me too... I'm so lucky to have you. I love you, player. 

I thought that compliment could be unlocked after a certain level of affection, too. Maybe at the affectionate level? Idk, just a suggestion. 

(Sorry for any grammatical errors.)

**Comment by Retrolovania** [comment]
...I will admit, this almost made me tear up a bit. What a fantastic idea!

**Comment by Ant9cp** [comment]
Agree great idea, also there should be a way for (you) to cheer up monika too if she's upset or doesn't feel happy

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
