### ISSUE TITLE
[Suggestion] Talking about Art Styles/Telling Monika you're an Artist

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6564]
Literature and art both go hand in hand as ways to visualize and experience human creativity at it's finest. As such, its probably caught Monika's interest at one point or another. It'd definitely make for a good few discussions revolving around various art styles (pop art, impressionism, surrealism, portraits, etc.), as well as talking about what tools people use to create art with (oil, acrylic, digital art, charcoal, the list goes on and on). Also, I believe mentioning what kinds of art you like, as well as telling her whether or not you design art yourself, would help Monika learn more about....well, you.

**Comment by kittendetails** [comment]
I think it's a good idea. Actually, there's a dialogue where she asks if the player draws, but she doesn't say anything very specific. There's also a topic on architecture, if I remember correctly. I believe that talking about more specific forms of art would be interesting. Not just painting, drawing or writing, but even theater or dance. After all, dancing and acting are also art expressions. Good sugestion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
