### ISSUE TITLE
[Suggestion] Adding some useful quick-chat phrases and possible reactions to other input.

### ISSUE THREAD

**Issue by drakesteele** [Monika-After-Story/MonikaModDev#6567]
Is there any way you could add a small palette of quick responses to the front menu? I'm thinking things you might use often:

Regularly, I'd like to have a, "Thank you, <nickname>." button on the main menu so you can thank her for things, and have her respond.

And just an idea, here but how about a "I think..." menu with all the compliment and complaints in it, since most of the "I'd like to tell you something..." is complimenting her anyway, and is buried deep... perhaps move it up a level and just put all of the opinions there, like "you're my hero!", "you're beautiful.", "you're so cute!", "you're the best girl!" etc... and you could put the "you're a murderer!" and then you could flesh that out over time with more opinions based on previous conversations or based on the affection levels, like, "we need to talk about us." leading to a discussion of how poorly things are going with her, or "we should move things to the next level." if the level has gone up and the player wants to give her the promise ring... just tossing some ideas out there on this stuff...

There are a couple that would be good only on the first time using chat after opening the game, like including "Hi, <nickname>..." and the "Good <time of day>." in the chat menu.
Also, if there was a crash, or an issue that made her kill the window on the player, include "I'd like to apologize..." on it, so you're not digging around for it.  I think having the menu adapt to the player and Monika more in their conversations would be cool, and shouldn't be more than some variable checks with an if...then somewhere to see if there's a problem last time, then pop it up.... the apology thing already tracks if there's something to apologize for, so that should be particularly easy.

Again, just throwing some ideas against the blackboard to see which leave chalk marks. XD

- Drake Steele

**Comment by ThePotatoGuy** [comment]
>thank you button on the main menu

atm we are avoiding adding additional main menu buttons because of main menu clutter

the rest are good suggestions


[closing until we look into it]
