### ISSUE TITLE
(Request) New compliment idea (You're a good writer)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6568]
Everyone that played DDLC the main game, have seen monika's poems right? her writing. And you can ask monika if you can read her poems again to 
Her writing is perfect, why not add a compliment about this?. If this compliment can be in MAS then here is the dialogue (😊)

-------------------------------------------------------------------------------------------------------------------------------------------

(Monika's reaction on the first time telling her this compliment) 
(Blushed Happy Face) Oh really, thank you so much (name) i'm really happy that you do because, when i first showed you my poems i actually hoped to hear you say this because i didn't hear this from you at first of course but from your charactar mc

-------------------------------------------------------------------------------------------------------------------------------------------

(You) choices: 
By looking at you're writing makes me feel happy
You're the best writer ever                    
I wish i had such handwriting
                                    
-------------------------------------------------------------------------------------------------------------------------------------------

Monika's reaction with choice 1: awww i'm so happy to hear that (name), i'm glad that it makes you happy by reading my writing in my poems hehe

-------------------------------------------------------------------------------------------------------------------------------------------

Monika's reaction with choice 2: oh thank you (name) i'm happy that you feel like that about my writing i hope it makes you want to write alot of things

-------------------------------------------------------------------------------------------------------------------------------------------

Monika's reaction with choice: 3 Oh (name) don't say that about yourself, even i've never seen you're handwriting before, i'm sure you're handwriting is very good, you just gotta keep practicing until you get a good result and don't give up

-------------------------------------------------------------------------------------------------------------------------------------------

Monika's reaction for after the first time telling this compliment: Randomise

-------------------------------------------------------------------------------------------------------------------------------------------

Oh Thanks again for saying that (name), You always know how to make me feel special hehe 

Hehe, Thanks for saying that again (name) you can always read my poems again whenever you want to 

Thanks again (name) i always do my best with writing of course hehe

Oh (name) thanks for telling that again, make sure you practice you're handwriting

Hehe, i'll never stop writing after hearing that from you (name)

**Comment by Ix-30** [comment]
I second this, so much.

**Comment by scpketer** [comment]
Let me *triple* that. Awesome!

**Comment by Ant9cp** [comment]
Can this compliment plz be considered to be a request for in MAS 

Because in the latest version v0.11.6 there is a topic with her talking about her writing

**Comment by kittendetails** [comment]
If you know a little about programming, you could try making a pull request with this idea. I think it would take a while for this suggestion be added, as there are many others before this one. You could try!

**Comment by Ant9cp** [comment]
I don't know how all that works?

**Comment by kittendetails** [comment]
You  can read more about that here: https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines

**Comment by Ant9cp** [comment]
So whatever idea like this one and other suggestions i come up with and put it on the issue list is all basically for nothing then

**Comment by kittendetails** [comment]
Not exactly. But, as I said, maybe will take time for it be implemented, as there are several pending suggestions, and new suggestions are presented every day.

**Comment by scpketer** [comment]
@Ant9cp, please do not close issues until they are resolved (if they represent actual issues with the mod) or implemented (if they are suggestions). It makes it hard to distinguish actually resolved ones from the ones closed for any other reason.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
