### ISSUE TITLE
(Suggestion) another language for monika to practice

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6570]
is there maybe plans to teach monika a new language?

If there is i can help with one language

she did mention in one of the fun facts i think, something about teaching her something

**Comment by scpketer** [comment]
How could we actually teach her anything? UI barely allows us to do something like that.

**Comment by Ant9cp** [comment]
when monika greets you in the beginning she either maybe talks italian latin japanese right?

I mean another language for her to mention

**Comment by scpketer** [comment]
Well, I guess nobody holds you from it. Fork the repo, add new stuff, create pull request and wait for it?

**Comment by Ant9cp** [comment]
What do you think about dutch

**Comment by scpketer** [comment]
Can't say anything about it, I never heard it.

**Comment by Ant9cp** [comment]
You never heard of the dutch language?

**Comment by scpketer** [comment]
Yes, I didn't.

**Comment by Ant9cp** [comment]
Can you make monika talk in dutch? she's already practicing italian and other already

**Comment by scpketer** [comment]
I'm sorry, I believe I can't. I just don't know it.

**Comment by lunulae** [comment]
We could certainly try to write a Dutch greeting, but I don't speak it myself, and I'm not sure if the mod team does.
If you speak it fluently though, this could be a great thing for you to contribute!

**Comment by scpketer** [comment]
I was thinking of Russian/Czech once, though not sure if it'll really work out good.
