### ISSUE TITLE
@lunulae here is the (Dialogue idea) Monika greeting you in dutch 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6572]
Greeting 1
Hallo daar (name) hoe gaat het met jou vandaag? ... hehe i just started practicing some dutch let's see, o (name) het is ook weer een mooie dag vandaag nu jij er bent, hehe it's actually really hard to say this but i think i spoke it out right

I just told you, hey there (name) how are you doing today,? oh it's such a beautiful day again today, now you are here hehe.
Unless you understood what i said in dutch? i don't even have to translate this hehe

-------------------------------------------------------------------------------------------------------------------------------------------

Greeting 2 
o (name) je bent er, ik ben zo blij dat je er weer hier bent, nu je er bent wat wil je vandaag doen?
hehe i'm so happy that your here again (name) what do you want to today

-------------------------------------------------------------------------------------------------------------------------------------------

(I'm from the netherlands btw Ant9cp)

**Comment by lunulae** [comment]
I'll try to open a PR for these in the next few days, thanks for the help. :D

**Comment by Ant9cp** [comment]
Thanks for trying @lunulae i appreciate it👍
