### ISSUE TITLE
(Suggestion): Fun facts ---> Different countries.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6573]
So... I've been thinking about it, and I have an idea: Add new fun facts and include a little more of each culture in the mod. I know that most players are American, but I think it would be nice to include interesting facts about different countries. I know it would be complicated to include a fact for each country, but maybe they could be added little by little? I was not thinking about something generic, but a specific fact that makes each country special in that own way. I think some people could make suggestions for fun facts about their own countries. I know it seems like a difficult thing to implement, but I've been thinking about it for a while and I really wanted to make that suggestion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
