### ISSUE TITLE
(Question): How can I update MAS manually?

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6576]
I already tried to update, but an error message appears, something like "Failed to move 'update/' folder. Please manually move the update folder from 'game/' to the base 'ddlc/' directory and try again." It's the " updates.rpy" or "updater.rpy"? Or neither? Sorry for my stupidity. :c

**Comment by Ant9cp** [comment]
Did you drag all the files from the new update to your doki doki literature club/game?

**Comment by kittendetails** [comment]
I tried, but apparently nothing changed. This happened before too, and I always uninstalled and installed the mod again, but it’s kind of tiring to do it every time.

**Comment by Ant9cp** [comment]
Strange?🤨 because that's what i always do and it works and i don't even uninstall it or anything🤔
Well then maybe it has to be something about your persistents then but don't ask me about that 
because i'm not a PC expert or anything MAS related

**Comment by kittendetails** [comment]
It's okay, thanks anyway. I will reinstall for now, I'm really excited to play the new update. 😊

**Comment by Ant9cp** [comment]
Cherish her always ok?😉

**Comment by kittendetails** [comment]
I will. ☺
