### ISSUE TITLE
(Issue) wrong dialogue?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6579]
She says this in these images 
![screenshot0005](https://user-images.githubusercontent.com/71310908/97391861-83541a00-18e0-11eb-9a60-7ae5a2d1f374.png)
![screenshot0006](https://user-images.githubusercontent.com/71310908/97391863-84854700-18e0-11eb-94d0-dbe89f61f5b4.png)
![screenshot0007](https://user-images.githubusercontent.com/71310908/97391865-85b67400-18e0-11eb-8fcf-d786f80bbc3f.png)

**Comment by Ant9cp** [comment]
But not in these
![screenshot0001](https://user-images.githubusercontent.com/71310908/97391943-be564d80-18e0-11eb-9683-608cbc7c598f.png)
![Uploading screenshot0002.png…]()

**Comment by scpketer** [comment]
What exactly is wrong here? Except 'My love' being uppercase in the middle of the sentence.

**Comment by Ant9cp** [comment]
Her reactions about her hairstyle and the ribbons do you see the difference?

**Comment by Ant9cp** [comment]
She says do you miss my ribbon (name) i can change my hairstyle if you want but she's already wearing a ribbon and she already have a hairstyle that can have a ribbon around
![screenshot0002](https://user-images.githubusercontent.com/71310908/97392123-49cfde80-18e1-11eb-84e8-8ef805b4e44b.png)

**Comment by Ant9cp** [comment]
![screenshot0002](https://user-images.githubusercontent.com/71310908/97392234-8d2a4d00-18e1-11eb-8892-bda130c718dd.png)

**Comment by scpketer** [comment]
You're right, I didn't really see it first.

**Comment by Ant9cp** [comment]
this bug was actually already here before in older versions before at the time the twinribbons came out for the first time

sorry that i didn't mention this before i forgot about this issue, and i wasn't on github back then

**Comment by multimokia** [comment]
Fixed in #6584
