### ISSUE TITLE
(I changed my name) to (Can you call me a different name)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6580]
Shoudn't you maybe call this something else (I changed my name) to Can you call me a different name?
Because your asking monika this right? not yourself
![screenshot0003](https://user-images.githubusercontent.com/71310908/97394772-b350ec80-18e3-11eb-9326-a9840b10fb15.png)

**Comment by multimokia** [comment]
This change was intentional in #5934.

It was somewhat ambiguous with the nickname change prompt, plus it makes sense that you'd say that you changed your name to her if you did, rather than just wanting to be called something else (nickname)
