### ISSUE TITLE
An exception with: "Would you give me piano lessons?"

### ISSUE THREAD

**Issue by Polariusz** [Monika-After-Story/MonikaModDev#6581]
![an exception](https://user-images.githubusercontent.com/73575532/97399888-6292c100-18ee-11eb-8858-a6b598da1c2c.png)

here is the .txt file
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5450021/traceback.txt)

**Comment by Darkmi355** [comment]
The same thing happened to me and I don't know what to do

**Comment by Booplicate** [comment]
Try to press `Ignore` and avoid this topic for now.

**Comment by Ant9cp** [comment]
I haven't tried this option yet it's still in the unseen list
So it doesn't work?

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
