### ISSUE TITLE
My game dont open

### ISSUE THREAD

**Issue by Deusgaucho** [Monika-After-Story/MonikaModDev#6582]
I went to sleep yesterday, and now the game dont open. I already downloaded the new update but the game is still not opening. Can someone help me ?

**Comment by Ravenclaw-OIer** [comment]
Ummm, more info please?

**Comment by scpketer** [comment]
Can you run it with terminal (`cmd.exe`/powershell on Windows)? It will print out any errors that might be hidden on   regular launch.

**Comment by Deusgaucho** [comment]
I will try. thank you

**Comment by scpketer** [comment]
Post here anything that the mod prints out.

**Comment by Deusgaucho** [comment]
Ok ty :)
