### ISSUE TITLE
(Suggestion) More flowers for monika

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6585]
You can only gift monika roses right?
why not more?

**Comment by EllieWLMS** [comment]
we could gift her some lilies! and maybe she could talk about its origins (The Lilium flower sprang from Eve's tears when she was expelled from Eden and realized that she was expecting a baby and another Greek legend explains that this flower was created from the drops of milk that the Goddess Hera dropped when she was nursing her son Hercules.) and it's meaning! (Femininity For the Greeks and Romans, giving a Lilium flower to women meant wishing them a long life and other meaning is Love, in Victorian times, men gave lilies to women as a sign of love) a beautiful flower with a beautiful story and a beautiful meaning for a beautiful girl.

**Comment by Ant9cp** [comment]
That is a lovely idea @EllieWLMS

**Comment by Rai99** [comment]
Flower variety: #3190, #3880, #3933

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
