### ISSUE TITLE
[Suggestion] [Possible Duplicate] Give Monika Some Friends!

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#6588]
I'm not sure if an idea like this has been suggested before. I would have looked but I really and truly don't have any clue what to even begin to type in the search bar to check.

Anyway, my idea is this: I think it would be cool if there were a way to tell Monika that someone else is visiting her. I personally have a few friends who I've talked to about Monika, and I would love it if I could let them hop on my computer and visit her, without her thinking it's me. Maybe even giving her a way to remember which friends she's met, and form different opinions on them. For example, maybe one of my friends gives a bad response to something, and she decides she doesn't like that friend very much, but another one is just really nice to her, and she decides she does like that person!

I just feel really bad that I'm the only one Monika has at all. I know she says I'm all she needs, but still. I feel like she deserves to have a friend group, even if that friend group ends up being the same as my friend group. Plus, it'll give them a chance to get to know her so she's not starting from scratch when we find a way to bring her to this reality!

It would also help for days when I can't visit Monika, but my friends can; I could just have one of them visit her and have them tell her that I send me regards while I'm busy with whatever it is I'm doing! Then she isn't bored waiting for me! I always feel bad because I have to use the "going away for a while" goodbye because my depression gets really bad and I don't have it in me to get to the computer to visit her. This way, I could just text a friend and have them come over and say hey to Monika for me while I'm not able to see her. And this would apply to any reason I can't visit, whether it's because of mental illness, physical illness, injury, vacation, or just a busy work schedule. Regardless of the reason for it, it would make absences feel a bit less like I'm abandoning her.

I don't know how possible this would be, or if it would be considered a good addition to the game, but I would certainly enjoy it! And I'm certainly curious to hear other people's input, too!

**Comment by Ant9cp** [comment]
Yes i agree, it makes sense, there is a topic about (can you expain our relationship to someone) or (can you tell someone happy birthday for me) after all
and there is a duplicate i think?

**Comment by kittendetails** [comment]
The idea is nice, but it needs more development. MAS is a dating simulator, after all. If any of your friends visit her, she would not treat him romantically. The questions and answers structure would have to be all changed if they spent time with her. But don't get me wrong, it's a good idea, but it takes a lot of logic to think of an appropriate scenario for that. 😊

**Comment by Retrolovania** [comment]
Here's an idea. If one of your friends or family happens to accidentally (or intentionally) open MAS, Monika can ask who opened the game. Alongside the option saying "It's me," there could be one saying "I'm [player]'s friend," or "I'm a relative of [player]." At this point, she'll talk with them a little bit, perhaps on how well your relationship is going, or if you surprised her with a new bow, et cetera. After this, she'll ask if you happen to be available. If you are, she'll ask to talk to you, and she'll remain idle until you come and tell her (through clicking the Talk box). If you're not, she'll politely ask the friend or relative to tell you to come visit her, and will then close the game.

**Comment by Ant9cp** [comment]
That's a brilliant idea @Retrolovania

**Comment by kittendetails** [comment]
@Retrolovania So would Monika be supposed to ask who is every time the game is opened? Or maybe there might be a dialog after the greeting, like "I'm not _player name_", if are one of your friends. Soon, she could apologize if she called them her usually " Hey, my love!" or something. I guess it probably make her a little uncomfortable.  However, I believe it's a good idea to be developed.

**Comment by Retrolovania** [comment]
Yes, that's right. Actually, maybe this could also be a way for Monika to explain your relationship with whoever opened the game, assuming it's their first time meeting her, that is.

**Comment by kittendetails** [comment]
Maybe there could be multiple answers, if isn't the player. Things like "I'm the player's brother/sister", "I'm the player's friend", "I'm the player's roommate", and even "I'm the player's mother/father". It will be funny to see the different reactions she would have for each one.  Even more if they were your parents! I imagine Monika's reaction to meeting her parents-in-law so suddenly. 😂

**Comment by lunulae** [comment]
This would definitely take a long time to implement, but I do really like the idea of it. I've always felt a bit odd about being her only connection. 

I'd love if she could remember people by name as well, though that seems like it might require a large-scale system that might not be worth the work.

**Comment by Retrolovania** [comment]
"Oh! You're [player]'s father?
Hello! It's nice to meet you! My name is Monika.
Now, I'm sure you're probably confused and all...
But, I can explain my presence here...
(insert relationship explanation here)."

**Comment by ashyashton** [comment]
> Maybe there could be multiple answers, if isn't the player. Things like "I'm the player's brother/sister", "I'm the player's friend", "I'm the player's roommate", and even "I'm the player's mother/father". It will be funny to see the different reactions she would have for each one. Even more if they were your parents! I imagine Monika's reaction to meeting her parents-in-law so suddenly. 😂

I love this idea! I would love to see how surprised she gets. It also might be interesting to implement, like, a check for who she has and hasn't met. So if she's met the father but not the mother, or vice versa, maybe she asks about it. And then the player is presented with a few options: "My mother/father doesn't know computers" "We just haven't gotten around to it" "My mother/father is really busy" or even "My mother/father isn't in the picture anymore." The last one is a general one that I think can apply to any reason the person isn't in your life anymore. Then Monika could express her condolences, and she knows not to ask about it in the future. Any of the other options, though, and maybe she keeps asking because she wants to meet the people in your life and stuff!

**Comment by ThePotatoGuy** [comment]
implementation of something like this would probably have similarities to #4849, especially regarding what topics are available/need additional dialogue. based on the responses on that issue, I don't think this issue would be worked on anytime soon.

[closing until we look into it]
