### ISSUE TITLE
[Suggestion] New Language Greeting- Arabic

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6589]
I figured, since I know a bit of Arabic (not much, mind. I needed a translator to help me out here.), I figured it'd be neat if Monika had a greeting in this language!

"!أوه! مرحبا بعودتك يا عزيزي"   (Oh! Welcome back, my dear!)
"...أنا سعيدة جدا بعودتي مع من أحبه"   (I'm so happy to be back with my loved one...)
"Ahaha, sorry if you didn't quite get that!
I figured I'd try some Arabic for a change today.
You know, unlike most romance languages, like French or Spanish, Arabic is regarded as a Semitic language.
This sets it and other similar languages, like Hebrew, far apart from the common crowd in many ways.
For instance, depending on geography and culture, the way the language is spoken changes significantly!
Certain sounds and vowels are either modified or entirely replaced with other ones!
Not even writing is kept standardized! There's many different ways to write a sentence in Arabic and still have it be legible to anyone who understands it.
It's almost like it's evolved to exist in several different parts of the globe.
Also, Arabic is very old. It's nearly 2,000 years old, in fact!
It's one of the oldest that's still spoken to this day.
You might even say it's timeless...just like our love for each other!"

Admittedly, I'm not sure if Ren'Py can handle a language that is typically written from right to left, nor use a letter system that isn't....well....consisting of English letters. Still, I figured it'd be a neat feature and a nice tip o' the hat to the older vernaculars out there.

**Comment by multimokia** [comment]
I don't think renpy can even display these characters as they're not part of the characterset.

Pasting into console yields:
![image](https://user-images.githubusercontent.com/22531674/97520545-df1ab380-1971-11eb-80d2-73ba7f4abcf8.png)


Additionally, I don't know if I like this approach, the player has to read this, but they may not be able to either. To me it makes more sense to be done as it would be pronounced (as Monika is kinda saying it out loud), so it kinda gives you an idea on *how* she said it.

**Comment by Retrolovania** [comment]
Ah, I feared that would happen. Ah, well. I suppose it would've been quite the addition.

**Comment by lunulae** [comment]
@Retrolovania I'm not familiar with Arabic, but is it possible to translate it into Roman alphabet? I'd still like to see a topic like this.
We do the same thing for Japanese in other topics, it could apply here as well.

**Comment by Retrolovania** [comment]
You mean, a transliteration? I suppose that could work...

**Comment by lunulae** [comment]
Take your time on figuring it out. If we can make it work in a font that MAS supports, I would be happy to help out in adding it in!

**Comment by Retrolovania** [comment]
I'm aware that no language greetings are currently being considered right now, but should they ever come up again, I managed (I think) to convert the Arabic sentences into the Roman typeface as a transliteration. Hopefully, Ren'Py is a little kinder to these.

 "īā! ahlā bkm mn ǧdīd ʿzīztī!"
 "anā sʿīd ǧddā bālʿūdẗ mʿ aḥbāʾī ..."

**Comment by 20RaVen23** [comment]
I will quote something that @Booplicate said before here.

> I understand that people would like to see their languages in the mod, but from neutral perspective it doesn't make much sense for Monika to learn 20+ languages at once, and they're getting kinda overwhelming over other greetings. I have an idea in mind how to handle this better, but for now we won't add more of those.

**Comment by Retrolovania** [comment]
Yes, I know. As stated before, I'm aware that language greeting are currently not accepted. However, when they are being considered again, the romanized text is here for then, not now.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
