### ISSUE TITLE
(Suggestion) New greeting: Portuguese.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6590]
I saw that @Retrolovania and @Ant9cp made some new suggestions for new greetings, and I would like to make one too. I'm Brazilian, so my native language is Portuguese. I would like to add a greeting in Portuguese then. (I hope you're not mad that I suggest the same thing. 😅) Here it goes:

Você está aqui! 

Estou tão feliz por você ter vindo me visitar~

Eu realmente senti sua falta. 

Sua presença aqui torna meu dia especial! 

Hahaha~

Sorry if that didn't make sense!

What I said was:

"You're here!"

"I'm so glad you came to visit me~"

"I really missed you."

"Your presence here makes my day special!"

I'm practicing some Portuguese now. 

Portuguese is a really intriguing language! 

Portuguese from Portugal is quite different from Brazilian Portuguese, for example.

Some words from Portuguese in Portugal have totally different meanings from Brazilians!

Some of them are considered offensive to Brazilians and vice-versa.

And we can't forget about Angolan Portuguese!

It's amazing how the language can change by country. 

Even in the same country, if you live in a different region than the person you're talking to!

It's a very difficult language, however.

I can say it's very different from English. There are so many verbal variations that I get lost!

They also have a letter that doesn't exist in the English vocabulary, which is called cedilha (ç).

The accentuation is quite complicated to understand, too. 

But you know that I love learning new things~

Ah, I learned another phrase too!

Eu te amo, [player]. Você significa tudo pra mim. 

It means: "I love you, [player]. You mean everything to me!"

Hehe~

**Comment by lunulae** [comment]
I like this one! The greetings tend to be a little shorter, so I might tweak it a bit to be more concise, but I really like the language facts so I'll try to keep most of them in. 👍 

I'll try to PR it in the next few days, since there are a few of these being requested I might put them into the same PR if the devs prefer.

**Comment by kittendetails** [comment]
Thank you so much! I really appreciate that. 🤗❤

**Comment by Retrolovania** [comment]
I think one great fun fact she could touch on is that Portuguese and Spanish are somewhat similar to each other. Some sounds, and I think certain phrases, are shared between the two.

**Comment by kittendetails** [comment]
I knew someone was going to comment about that 😅. I'm doing a topic about Spanish right now. I can speak this, too. I think this greeting doesn't exist at MAS yet? I never saw it.

**Comment by Retrolovania** [comment]
There's no Spanish greeting? That's odd....I figured almost all the romance vernaculars were covered by now.

**Comment by kittendetails** [comment]
I'm not sure if doesn't have... I just don't remember seeing it.

**Comment by Ant9cp** [comment]
I don't mind, i think it's rather funny 😄 @kittendetails

**Comment by Ant9cp** [comment]
I think you're talking about italian because there is no spanish greetings. @Retrolovania

**Comment by Akh0r** [comment]
> almost all the romance vernaculars were covered by now.

So, no Russian yet?
By the way, it's very interesting how would translators work on this topic when Monika speaks phrases in target language.
Is it better to make her speech a little bit simple and with slight grammatical mistakes, and then she would say that she tries to talk without the translator? 
Or should we simply remove the target language greeting at all, making it like Monika simply speaks it all along?

**Comment by scpketer** [comment]
I'm currently working on Russian one, right.

**Comment by Booplicate** [comment]
> I'm currently working on Russian one, right.

To save your time I want to warn you in advance that we decided to stop adding new language greetings for now.

**Comment by 20RaVen23** [comment]
> To save your time I want to warn you in advance that we decided to stop adding new language greetings for now.
Understandable, I'm seeing a lot of language greetings now heh. Tho I would really like to work on the Spanish one...

**Comment by Booplicate** [comment]
I understand that people would like to see their languages in the mod, but from neutral perspective it doesn't make much sense for Monika to learn 20+ languages at once, and they're getting kinda overwhelming over other greetings. I have an idea in mind how to handle this better, but for now we won't add more of those.

**Comment by 20RaVen23** [comment]
You just killed a man's dream...

**Comment by Booplicate** [comment]
No one stopping you from making it a submod. And then, if we ever get back to adding this type of greetings again, merge it with the mod.

**Comment by 20RaVen23** [comment]
I'll keep it on mind 👍

**Comment by scpketer** [comment]
Oh, that's alright. Well I still have my draft saved, so if you'll change your mind I'll be happy to PR it.

**Comment by satoshi-kun** [comment]
I'm portuguese and I cannot express how cringe it was imagining Monika speaking portuguese specially with a brazilian accent...
Better keep that as submod.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
