### ISSUE TITLE
(Suggestion) New greeting: Spanish.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6591]
¡Hola, mi amor! ¿Qué tal?

¡Que gusto verte hoy!

Me alegro de que estés aquí ahora.

Hehe~ 

What I said was:

"Hello, my love! How are you?"

"It's nice to see you today!"

"I'm glad you're here now."

Spanish is a really nice language.

A lot of people think that Spanish is very similar to Portuguese... 

But, when you learn more about them both, the differences are clear! 

Spanish uses accents that are very different from Portuguese. 

Like the "ñ" that's just used in Spanish! 

In some countries, there is even a variation of both, called "portunhol".

However, it is not an official language... It's just a fusion of both. 

Some people think that Spanish is more elegant. 

For others, Portuguese is more seductive.  

It's a matter of opinion! 

I believe that each language has this own beauty, so I have no preference, haha~

However, it can't be denied that Spanish is a very romantic language.

The love songs are so touching. Some very famous are "Corazón Espinado" (Santana) and "Estoy Aquí" (Shakira). 

Unfortunately, most of the singers seem to be with the "corazón partído" (heartbroken), hahaha~ (That's a reference to another famous love song called "Corazón Partío", Alejandro Sanz). 

But it's still beautiful, isn't it?

Don't worry, player.

I promise I will never break your heart. 

¡Te amo!

That's means... 

"I love you!"

@lunulae You can make some changes if you want, I put a lot of things in, so you can choose which ones to add.

**Comment by Ant9cp** [comment]
(I saw that @Retrolovania and @Ant9cp made some new suggestions for new greetings, and I would like to make one too. I'm Brazilian, so my native language is Portuguese. I would like to add a greeting in Portuguese then. (I hope you're not mad that I suggest the same thing. 😅)


-------------------------------------------------------------------------------------------------------------------------------------------







I don't mind, i think it's rather funny 😄 @kittendetails

**Comment by 20RaVen23** [comment]
That is nice ^^
I would change the line "¡Qué gusto de verlo hoy!" to "¡Que gusto verte hoy!" Since "Verlo" is something too formal, I couldn't see a couple talking like that :x
Also, the last line "Yo te amo" would be "Te amo", since no one actually uses the "Yo" when people says "I" hehe.

**Comment by kittendetails** [comment]
@20RaVen23 I get it. I thought it didn't matter if I put "Yo" in the sentence (Which means "Eu" in Portuguese). In Portuguese it can also be said only "Te amo", and most of the people don't say "Eu te amo" in an informal talk, but it's considered more sincere and romantic when the person says the complete sentence.Thanks for the correction. 🤗❤

**Comment by 20RaVen23** [comment]
No problem 👍

**Comment by EllieWLMS** [comment]
you know what? I think Monika would enjoy songs like "Whenever, Wherever (Suerte)" From Shakira or "Latinoamerica" From Calle 13, in the first one she would say something like "it reminds me of us!" or something like that and in the second one she would be impressed because of the culture in Latinoamerica! (i recommend both of the songs pls hear them)

**Comment by kittendetails** [comment]
I believe that this can be another topic. I suggested the most famous for who aren't familiar with spanish musics. Great idea, maybe you should make a suggestion about them. 👍🏻

**Comment by 20RaVen23** [comment]
Maybe I can work on this? Since my native language is Spanish and so. It would be also nice to finally contribute a bit :s

**Comment by ThePotatoGuy** [comment]
Are you planing on adding this? @20RaVen23

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
