### ISSUE TITLE
Pressing '1' key triggers left mouse click action

### ISSUE THREAD

**Issue by scpketer** [Monika-After-Story/MonikaModDev#6593]
It seems that pressing <kbd>1</kbd> triggers the left mouse click, like <kbd>Enter</kbd> does. This also seems to trigger <kbd>Enter</kbd> action too.

That makes it really difficult (actually, rather impossible) to type statements in the console (I first noticed this when I tried to type `show monika 3hua at t11 zorder MAS_MONIKA_Z`, but it suddenly got executed halfway-written when I hit <kbd>1</kbd>.) which contain digit `1`.

This is not a bug of my system, other applications show no signs of anything similar.

![Demo GIF](https://user-images.githubusercontent.com/31247845/97545545-9e0fb700-19e4-11eb-9f9e-d53b81db7937.gif)

**Comment by Booplicate** [comment]
Check your custom keysims, we don't bind anything to `1`.

**Comment by scpketer** [comment]
That's what I thought... Really weird, I'm not aware of any keybinds like this either.

Alright, thanks for clarifying.

**Comment by scpketer** [comment]
Update: yep, @Booplicate's totally right, seems like a local issue of mine. Oddly none of the other applications seemed to be affected, though...
