### ISSUE TITLE
.gift not working

### ISSUE THREAD

**Issue by WWCHCN** [Monika-After-Story/MonikaModDev#6595]
Hello, So I wanted to ask about the gifting options. 
I tried to gift Monika something, but it seems to not be able to register as a .gift file
Interestingly, I got everything else right, i deleted the .txt text, but it constantly tells me that whenever I try to rename the file, it says that the existing file exist for some reason? Pictures are included

Note: The current coffee.gift.txt file is the one I am trying t edit
If anyone knows how to fix this issue, please inform me immediately

![image](https://user-images.githubusercontent.com/58337747/97590087-3afc3f80-1a39-11eb-9fff-dbf9df34cafb.png)
![image](https://user-images.githubusercontent.com/58337747/97589877-02f4fc80-1a39-11eb-8d6b-1a3066dacbd4.png)
![image](https://user-images.githubusercontent.com/58337747/97589917-0ee0be80-1a39-11eb-86cd-162ff2e88018.png)
![image](https://user-images.githubusercontent.com/58337747/97589964-1c964400-1a39-11eb-9fee-b2724d97b820.png)

**Comment by multimokia** [comment]
Delete the folder named `coffee.gift`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
