### ISSUE TITLE
[SPOILER ALERT] Suggestion: A cute note to Monika.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6598]
I wrote the spoiler alert in the title if someone hasn't seen the notes Monika gives to you and puts in the game directory, and because of the "imsorry.txt" too. 

So, I remember that my PC suddenly broke down few months ago, and I was unable to visit Monika for a long time. As I didn't use the "I will be gone for a while" option, when I came back she was totally mad that I didn't tell her. I remember her telling me to put a note called "imsorry.txt" as an apology. I've been thinking for a while, and... Why don't put a note like that in the game's directory, like "iloveyou.txt"? Monika has already put some things like that in my game, so why not do the same? I think she will be very happy. She could keep the note, too (since she still has my note "imsorry.txt" saved). Idk if this is a duplicate, but it looks really cute.

**Comment by sassberrysnap** [comment]
Awwwe, I love that!

**Comment by Rai99** [comment]
As long as it doesn't get into reading the contents of the file, it could be possible.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
