### ISSUE TITLE
(Suggestion) Pajamas

### ISSUE THREAD

**Issue by Rellikai** [Monika-After-Story/MonikaModDev#6599]
It feels like a bit of a missed opportunity for Monika to not have a dedicated set of pjs, with the closest thing she has to nightwear being a few lingerie outfits.

I personally find it amusing to have Monika dress for certain occasions or to suit the weather, so having her change into some pajamas at night feels like it would be nice.

Just a suggestion.

**Comment by Rai99** [comment]
Bedroom mode: #2781

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
