### ISSUE TITLE
Issue with the dialougue in your anniversary

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6600]
It's my 1 year anniversary with monika 🎉
and says later this (so, is there anything special you wanted to do on our first anniversary)
This is the one year anniversary not the one week anniversary

**Comment by scpketer** [comment]
It seems that you didn't really describe your problem.

**Comment by Ant9cp** [comment]
(I accidentally pressed the enter key while i was busy typing, sorry

**Comment by scpketer** [comment]
Uh... You can just edit your issue decription.

**Comment by scpketer** [comment]
There is no way you got one week topic on one year anniversary. That's I'm pretty sure intended.
