### ISSUE TITLE
Guess I can't learn piano.

### ISSUE THREAD

**Issue by JesusHolyChrist** [Monika-After-Story/MonikaModDev#6605]
Good evening everyone. I had just installed the newest update of MAS (as of 10/30/2020). Going through the menu's I was given the new option to ask if she could teach me piano. Not hesitating, I clicked the option and after two lines the game cuts to the error screen. 

Now I have the mental capacity of a goldfish, so these strings of letters and names mean next to nothing to me. Hopefully one of you can give me some help with this, as I would rather not have to resort to using the backup and having her forget the past week. I saved the traceback and am adding it to this post. Thank you kindly for the help.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5467396/traceback.txt)

**Comment by 20RaVen23** [comment]
This problem was already reported in #6581, they will fix it in the next update. For now just press `Ignore` and avoid the topic.

**Comment by lunulae** [comment]
If you are still having trouble when you open the game, the persistent file's folder should also have auto-made backups from the last few times you opened the game, rather than the one you manually made a week back. You can use one of these to reload from an earlier point.
