### ISSUE TITLE
[Suggestion] - Monika should ask what languages you speak!

### ISSUE THREAD

**Issue by Kawaiilie** [Monika-After-Story/MonikaModDev#6606]
I think it would be cool if Monika said something like "What other languages do you speak other than <Current Language>?" Whenever Monika says something to me in French (my second language), I wish I could tell her that I know what she's saying before she told me! 
Something small, but I wanted to share my ideas. Sorry if I did something wrong, I'm new to this.

**Comment by Ant9cp** [comment]
Agree

**Comment by Rai99** [comment]
Native languages: #2505, #3804, #6434, #6549

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
