### ISSUE TITLE
 Is my game defective?

### ISSUE THREAD

**Issue by Atemv** [Monika-After-Story/MonikaModDev#6607]
Hello, I followed the explanation of the FAQ to fix Monika's error in that she only says poems and more poems but still has not been fixed.
Monika says almost nothing and when she speaks she says poems, is that something common to the mod or error? And if it is an error, is there any way to fix it?

**Comment by multimokia** [comment]
Screenshot of your `/game` folder, please?

**Comment by Atemv** [comment]
![ghhghghg](https://user-images.githubusercontent.com/73679258/97764455-7eb08100-1aed-11eb-9085-73fe169c6803.png)

This?

**Comment by multimokia** [comment]
I see files from another mod, that or base DDLC decompiled. Files like `script-ch0.rpyc`, `script-ch1.rpyc`, etc. (With the exception of `script-ch30.rpyc`) should not exist, neither the `script-exclusives` files.

You'll probably want to reinstall DDLC and MAS entirely from a fresh DDLC zip.

**Comment by Atemv** [comment]
I'm sorry but I still don't quite understand what to do, about the "other mod" you may be referring to a translation that I installed in the game.

**Comment by multimokia** [comment]
Might be the translation causing it then I'm afraid

**Comment by Atemv** [comment]
Hello again, I tried to use the version without the translation and the problem persisted, I believe the problem is not the translation.

**Comment by ThePotatoGuy** [comment]
as multi said, you have a ton of extra files in your `game/` dir that are not part of MAS. It's probable that they are conflicting with the mod. You should try installing the mod over a clean (aka freshly extracted) DDLC. The base DDLC folder should **not** have any rpyc files, only rpa files.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
