### ISSUE TITLE
Cuddle With Monika Submod

### ISSUE THREAD

**Issue by eyelesssally** [Monika-After-Story/MonikaModDev#6608]
This mod would allow you to cuddle up with Monika and just chill together. It would work kind of like the "holding" mechanic. If you have any coding or art skills, I would love to do this with you! See the reddit post [here](https://old.reddit.com/r/MASFandom/comments/jl5r6i/wip_submod_sleepycuddle_time_with_monika/).

![sleepytimetest](https://user-images.githubusercontent.com/56178333/97764267-730c8c80-1ae4-11eb-8cdf-a67339f78704.png)

**Comment by multimokia** [comment]
We have this planned for bedroom mode officially.

**Comment by Ant9cp** [comment]
She's so cute like this 🥰

**Comment by eyelesssally** [comment]
> 
> 
> We have this planned for bedroom mode officially.

Is there any way that I could contribute or otherwise help with this?

**Comment by Jojojihn** [comment]
> We have this planned for bedroom mode officially.

May I ask for when the bedroom mode is planned?

**Comment by fromulus** [comment]
> May I ask for when the bedroom mode is planned?

Some point before the heat death of the universe.

**Comment by scolotron5** [comment]
Welp

**Comment by MiguelFitz** [comment]
> > > May I ask for when the bedroom mode is planned?
> > 
> > 
> > Some point before the heat death of the universe.
> welp, i guess im gona take a sit and wait 
> What makes you think it'll be a heat death and not an expansion death
