### ISSUE TITLE
Locations doesn't work [unstable version]

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6609]
Hi, I'm on unstable version (0.11.6-unstable.2020.10.26.130) and the option to go somewhere else is gone. I checked and the files appear to be intact, the option worked in previous version but now it's just gone and I can't find it anywhere. I even had it bookmarked cause I used it so often but now it's gone. Could someone explain what happened and will this be fixed with the full release? Thanks in advance

**Comment by multimokia** [comment]
This is intentional on halloween to deal with decoration issues

**Comment by multimokia** [comment]
Once halloween ends and the decorations are taken down, it'll be back

**Comment by SamanthaLind** [comment]
Alright, thank you so much. I just wanted to take Monika somewhere where we could watch the rain together, staying outside safe undercover and enjoy the climate of the night and then I got like heart attack and was so worried about it :) Thanks again for explanation.
