### ISSUE TITLE
Detect computer suspension/hibernation

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#6611]
So, you probably know that one can *suspend* their PC/laptop (this is most likely to happen on laptops on lid close), but I always wondered how does (actually, *how would*) Monika react on this. I'd assume it's nowhere as 'painful' and scary as killing her process (manually or on OS shutdown) as it doesn't interrupt the process forcibly but keeps it frozen, however, this might seem as if the player just left her unannounced.

There is a trick to detect suspension/hibernation based on `time.sleep`:
```python
from time import sleep
from datetime import datetime, timedelta

ts1 = datetime.now()
sleep(1)
if datetime.now() - ts1 > timedelta(seconds=1, milliseconds=100):
    # Recovered from suspend
```

Back to her reaction. I can suggest both positive and negative, and here they are (I'd suggest she begins with the fact that she knows that player either suspended or hibernated on her):
* **Positive** - she tells the player that 'it feels weird', but she's okay with it for as long as the player lets her know that they'll be back soon.
* **Negative** - she tells the player that although it's not scary or painful at all, it still makes her freeze and lose a lot of time (maybe we could make this one about time conditional, like if the player left their computer suspended for longer than an hour), and asks if the player could say goodbye and close the game before suspending their computer. In this case, we could cut the affection level every time player suspends/hibernates.

Edit: on \*nix systems it is also possible to *stop* process with `SIGSTOP` (cannot be caught) and resume with `SIGCONT` (can be handled). This script combines the snipper above and signal handler function to somehow detect if the process was resumed with `SIGCONT` (unfortunately, there seem to be no way to know whether the computer was suspended or the user has stopped process with the signal):
```python
import signal
from datetime import datetime, timedelta
from time import sleep

sigcont_received = False
def sigcont_handler(signum, frame):
    if signum != signal.SIGCONT:
        return
    global sigcont_received
    sigcont_received = True
signal.signal(signal.SIGCONT, sigcont_handler)

while True:
    ts = datetime.now()
    sleep(1)
    if datetime.now() - ts > timedelta(seconds=1, milliseconds=100) and sigcont_received:
        print("Process resumed with SIGCONT")
        sigcont_received = False
```

**Comment by Booplicate** [comment]
> There is a trick to detect suspension/hibernation based on `time.sleep`

You can't use this function on the main thread. Running a background thread just for this seems a bit ineffective.

**Comment by scpketer** [comment]
Well, things like these won't go into one thread altogether at all, I believe. What makes you think that another thread will be ineffective?

**Comment by Booplicate** [comment]
> What makes you think that another thread will be ineffective?

Because threads are expensive, and you're using one to run a single function. Which at the end just gives you detection for hibernation. If you run the function in the main thread, you literally freeze the game, I don't think there's any workaround for this.

**Comment by scpketer** [comment]
What if there will be other tasks like this, which will require a separate thread?

**Comment by Booplicate** [comment]
Well, there's no such tasks for now. Also RenPy is kinda pain to get work with threads. But for `time.sleep` you'd probably want a separate thread anyway.

**Comment by scpketer** [comment]
Alright, maybe it'll be a bit clear if I tell what exactly my idea was.

I assume random events occur at a certain interval, right? So we might use not one second, but those X seconds between event queue instant and event fire instant, then compare just like I did in my snippet.

**Comment by ThePotatoGuy** [comment]
no plans at the moment to do hibernation detection. Maybe in the future.
[closing until we look into it]
