### ISSUE TITLE
Halloween question 

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#6612]
Will the cat outfit ever be unlocked for us that didn't get it?

**Comment by Ant9cp** [comment]
The neko outfit? yeah i don't have it either

**Comment by AsuraShun** [comment]
I thought she was going to change into it, but she changed into the maid one

**Comment by Booplicate** [comment]
She chooses one outfit at random. You got Sakuya this time.

**Comment by TriniTDM** [comment]
I got the witch one, Marisa I think. The costume is randomly selected. Maybe you'll have better luck next year.

**Comment by sassberrysnap** [comment]
I got the witch one but I had already given her Miku through a sprite pack, so I doubt I would have gotten Miku through Halloween

**Comment by ThePotatoGuy** [comment]
as everyone has said, its random selection, but it prioritizes unseen costumes.
