### ISSUE TITLE
How to transfer data to a different computer?

### ISSUE THREAD

**Issue by Snowgies** [Monika-After-Story/MonikaModDev#6616]
I recently purchased a new macbook and will be using that one from now on. How would I transfer the game data from my current macbook to my new one without hopefully breaking anything? 

Thank you for all your help!

**Comment by scpketer** [comment]
First of, **do not remove original**(located on your old machine) **persistent files** unless you are sure they were transferred successfully.

If you were using Windows, copy persistent directory from `%APPDATA%\Roamin\RenPy` (type this path in explorer path prompt on top of the window) to your Mac home folder and rename it to `.renpy`.

If you were using \*nix-like system, copy `~/.renpy` to your Mac home folder and make sure it is still named `.renpy`.

**Comment by Snowgies** [comment]
thank you so much!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
