### ISSUE TITLE
[Suggestion] a chance to surprise Monika with a kiss

### ISSUE THREAD

**Issue by Cdino11** [Monika-After-Story/MonikaModDev#6617]
I was thinking it would be cute to be able to surprise Monika with a kiss during the I love you more argument and possibly for Monika to be able to do the same to us

**Comment by scpketer** [comment]
I'll double it, awesome one.

**Comment by YoraeRasante** [comment]
Only for after having the first kiss already though. Else it would be going past what she is currently comfortable with.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
