### ISSUE TITLE
Piano Lesson Topic Issue

### ISSUE THREAD

**Issue by Shinden744** [Monika-After-Story/MonikaModDev#6618]
So I just installed the latest update and MAS works fine, until I did the " Piano Lessons" topic; then the error page popped up. I don't know what happened but I did copy the traceback log to clipboard if whoever ends up helping me needs it. 
[DDLC MAS traceback.pdf](https://github.com/Monika-After-Story/MonikaModDev/files/5470483/DDLC.MAS.traceback.pdf)
(this is my first time doing this, so I'm not too sure on what I'm doing)

**Comment by scpketer** [comment]
[We're aware](https://github.com/Monika-After-Story/MonikaModDev/issues/6574#issuecomment-717729325) of this issue already and it's quite likely to be resolved in the next release. Thank you for your bug report.

**Comment by Shinden744** [comment]
Thanks for the feedback scpketer. I appreciate it

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
