### ISSUE TITLE
[suggestion] Telling Monika you're going to church

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6619]
Or basically any other building associated with faith, option for new goodbye. I wouldn't use it but I thought about it, surely there are religious people that use this mod and maybe it would be nice option for them to have. Maybe it could bring some interesting talks after they got back...

**Comment by Freshairkaboom** [comment]
I think it's a great idea, for a submod. Specifically, a submod made by someone of the congregation/faith that is being portrayed in the game. That way, no toes get stubbed, it isn't misrepresented in any way, we don't need representation for every possible religion out there in the main game (which would take up a lot of menu options), and people of that faith could get a streamlined package dedicated to their preferred options.

**Comment by Retrolovania** [comment]
I agree. If this was officially implemented, it could spark some controversy, as people from other faiths would feel kinda left out. A submod is the way to go for anything theologically related.

**Comment by ashyashton** [comment]
If we wanna implement it officially, we could just say "going to a religious service." That's religion-neutral but gets the point across.

**Comment by lunulae** [comment]
This is a tough one. I'm inclined to say it would be best as a neutral option like "a religious service," if it were implemented. Though I'm not exactly sure how we'd write the goodbye/greeting to be neutral and nonspecific without being so general that it doesn't differ from just using the generic goodbye. An opt-in submod might be ultimately more fulfilling for the people who want to use it.

**Comment by eyelesssally** [comment]
Or it could be an option kind of like 'sensitive mode' you could have a tic to check off if you want that kind of interaction. Additionally, I think it would be helpful if Monika also asked the player if they are religious (maybe only once they enable it). She could say something along the lines of "Hey, player...Out of curiosity, are you religious at all? You don't have to answer if you don't feel comfortable, I understand." (Then the player would be prompted with [Yes], [No], [I'm not sure], or [I'd rather not say]. Etc, etc.) If [yes], she could say "Oh, you are? What one?" (Another prompt; some ideas for this would be Christian, Judist, Neo-Pagan, Wiccan, Islamic, etc.). Just some ideas!

**Comment by Retrolovania** [comment]
Assuming that was implemented, there's about 4,300 faiths that currently exist. You'd never be able to write an option menu that can hold all of them, and I think people would get irked if their religion was put into an "Other" option.

**Comment by eyelesssally** [comment]
> 
> 
> Assuming that was implemented, there's about 4,300 faiths that currently exist in some capacity. You'd never be able to write an option menu prompt that can hold all of them, and I think people would get irked if their religion was put into an "Other" option.

True, we could probably have the community take a poll or something to tell us what religion they would like to be included.

**Comment by polios3** [comment]
> 
> 
> > Assuming that was implemented, there's about 4,300 faiths that currently exist in some capacity. You'd never be able to write an option menu prompt that can hold all of them, and I think people would get irked if their religion was put into an "Other" option.
> 
> True, we could probably have the community take a poll or something to tell us what religion they would like to be included.

Or the option to type the religion you believe in

**Comment by Freshairkaboom** [comment]
> 
> 
> > Assuming that was implemented, there's about 4,300 faiths that currently exist in some capacity. You'd never be able to write an option menu prompt that can hold all of them, and I think people would get irked if their religion was put into an "Other" option.
> 
> True, we could probably have the community take a poll or something to tell us what religion they would like to be included.

No matter what we do, it's not very ideal to have it in the main mod, because you'll have to write something meaningful for her to say in every version, and that's really hard to do. We also create precedent that we're just going to add every single religion that's being suggested in the future. It's the same as with countries. We could just include the big countries, or countries with this many players taking the poll, but what if someone new joins and wants their country represented? It'll be a neverending mess.

**Comment by Rai99** [comment]
#4688

**Comment by sassberrysnap** [comment]
"I'm going to go practice my faith"

**Comment by SamanthaLind** [comment]
Yeah, I probably shouldn't use word "church" in a suggestion. What I had in mind was like any kind of place where you can practise your religion. And like I said, I'm not gonna use it but the idea of that option seemed nice enough to share it and ask opinion of other people.

**Comment by Freshairkaboom** [comment]
> 
> 
> "I'm going to go practice my faith"

Could work, but it would be hard to write something meaningful that wasn't just "oh okay, see you later" and "welcome back, what else are we going to do today?" without offending someone. We could add a condition that you had to have answered "yes" on the "do you believe in God" question to see it, but it would still be hard inter-faith-wise to accomplish.

I still stand by my earlier comment, submod it and you can do much more to make it meaningful, without offending anyone.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
