### ISSUE TITLE
[Suggestion]- "I'd like to introduce you to....."

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6620]
We all know that a relationship cannot be kept private for long. Eventually, we will need to tell our family/friends that we have Monika as a partner. However, the current way to do this is through the topic "Can you explain our relationship to someone?"

While this is a good approach, it seems kinda.....generic(not really?). Now, obviously, there will most likely still be some explaining to do on your part, but, for the majority of it, it seems like you're basically telling Monika to do the bulk of the explanation, while you just sit idly by and watch. Explaining a relationship requires participation on both sides. Plus, depending on who you're asking Monika to explain the situation to, your friend/relative is likely to still be somewhat confused by the whole thing, and will feel dissatisfied due to the fact that what they receive isn't truly directed at _them_, per se.

I feel like the overall experience still needs to be at least somewhat directed to the person you're trying to inform, rather than have one preset explanation for anyone you talk to.

So, I was thinking there could be a new topic (name listed above) that will allow you to do this. Once clicked, Monika could say something like "Oh? Someone wants to see me? Who is it?" Then, a menu will pop up with some options, like:

My father.
My mother.
My friend(s).
My grandparent(s).
My guardian.
My stepmother.
My stepfather.
My sibling.

Once an option is clicked, Monika could say something like "Ah, so you're [player]'s friend! Nice to meet you! My name is Monika. Although, I'll just assume you already know that..." , and will then use the dialogue from the current explanation topic, but tweaked slightly in order to address the person Monika is talking to. Once done, she could then ask them if she explained it properly, with a yes/no menu appearing. If "no" is selected, she might hesitate, and ask you to help her explain the relationship. This is where the player steps in and explains any further details the other person may have. After this, you can tell Monika that they understand now. She could bid them goodbye until another time, and then resume talking to...well, you.

**Comment by ashyashton** [comment]
I like this idea! I will say, though, there should probably be an option to skip the explanation and just have her chat with the person for a moment, in case the person has already heard the explanation or the player has already explained it to them and they just wanna see Monika or something. With the other topic, you're specifically asking for an explanation, but with "I wanna introduce you to someone" you aren't inherently asking for the explanation to happen.

**Comment by Retrolovania** [comment]
Good idea! Maybe, if that person wants to talk to her a bit in the future, there could be a "Someone wants to talk to you." option.

**Comment by sassberrysnap** [comment]
Yeah!! Especially since when you say you're going to hang out with friends, she says that we should introduce them to her some time, but there is no way to! I think this would be a really good addition!!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
