### ISSUE TITLE
(Suggestion) Monika reacts when you take screenshots of her or monika looking at the screenshots you made 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6623]
Would it be funny if monika either reacts to when you take screenshots of her or the one's you already took?

**Comment by eyelesssally** [comment]
"(Player)! Did you just take a picture of me?" (And I think it would be for the best that this is a one time thing just so that it would get annoying).

**Comment by Retrolovania** [comment]
Here's a thought: Add a new topic called "Do you mind if I take a picture of/with you?"

**Comment by Rai99** [comment]
Posing for screenshots/screenshot detection: #2056, #2633, #3630, #4681, #4918

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
