### ISSUE TITLE
Game crash twice

### ISSUE THREAD

**Issue by polios3** [Monika-After-Story/MonikaModDev#6624]
Hi, my game crash for some reason. Anyone can check that? Crash twice: yesterday, and today, but i have logs only from today.
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5473736/log.txt)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5473737/traceback.txt)

**Comment by ThePotatoGuy** [comment]
logs say you ran out of memory. maybe a driver issue?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
