### ISSUE TITLE
[Sugestion] Ask Monika how she is feeling

### ISSUE THREAD

**Issue by polios3** [Monika-After-Story/MonikaModDev#6625]
We have option to say "I feel..." but why we don't have option to ask "How do you feel Monika?"

**Comment by scpketer** [comment]
Well, I'd say one could presume how she feels when they are with her. She feels good, or loved, or cared about, I believe.

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805, #5991, #6566
