### ISSUE TITLE
[Suggestion] Aquick one: Add "How are you feeling?" to the menu, so Monika can let you know her current state.

### ISSUE THREAD

**Issue by drakesteele** [Monika-After-Story/MonikaModDev#6629]
Basically, just a "How are you feeling, <name>?" or even "How are you doing?"

And that way if she's mad, or lonely, or happy with the time you spend, or feeling particularly loved, etc., she can have a quick set of phrases to reflect her emotional states, and you can, depending, apologize, be supportive, be a dick, whatever, and let that kind of start a new bit of feedback... it would make her feel more conversational until you can implement an actual chat system again, and give her nlp based responses.  Another thought that ran through my artsy-fartsy geekboy brain.

Hope these at least are thought-provoking or useful for inspiration if not directly implementable.

- Drake.

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805, #5991, #6566, #6625

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
