### ISSUE TITLE
[Suggestion] - Monika on Early Automata

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6630]
As discussions have come and gone, reflecting on how Monika could potentially find a way to come to our world, the topic of utilizing a robotic body has received quite the bit of talk. At the moment, it seems like the most likely method thus far, given the current rate of technology. However, I figure one thing to note is that the idea of recreating human movement utilizing mechanics is nothing new. In fact, the concept has existed for millennia. I figured Monika would find it an interesting topic of discussion to mention a few of these devices that tried to take on human animation using the technology of their contemporaries.

Firstly, it should be noted that the overall design of these machines, particularly those of the 18-19th Centuries, are baffling in the engineering sense, both in construction and operation. Even now, many of these devices have yet to be reverse-engineered in order to see how they function, mostly due to a lack of blueprints plus a general lack of knowledge regarding the materials and the craftsmanship required to build them.

I believe that Monika would primarily find interest in four examples of these devices, them being the Turk, the famous mechanical chess player that once challenged Napoleon (and threw a fit after the general attempted to cheat), and the three famous automata built by Pierre-Jaquet Droz, these being The Writer, The Draughtsman and The Musician. Out of all four, I feel she'd be most intrigued by The Writer. The Writer, which has the appearance of a young boy sitting at a table, utilizes a great stack of cams and gears in order to both write words on a piece of parchment as well as control how much pressure is applied to the pen it uses; an incredible feat of mechanics, even by today's standards. What makes this so interesting, is that the letters the machine writes can be swapped to make any word imaginable. Basically, The Writer was, in essence, on of the first programmable machines. Thus, Monika would probably consider it an ancestor to modern computing, and also find it somewhat ironic that it's main task is literature based.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
