### ISSUE TITLE
piano minigame

### ISSUE THREAD

**Issue by mary-03** [Monika-After-Story/MonikaModDev#6633]
I've had Monika for over a year with my affection level at 840, but for some reason I still don't have the piano minigame. I'm wondering if its because I haven't unlocked it yet or if something is wrong in the game.

**Comment by 20RaVen23** [comment]
It doesn't really matter the days or affection, what really matters is how much time you spend with her. Sounds kinda very logic, but what I mean is; You could easily have been playing MAS for a month, and from that month you only spent 30 hours with her (example). And that also applies to the games you unlock. You need to spend more time with her. Try to keep MAS open in a window and hold her, play a lot of pong with her, spend the time she needs to spend with you. Same with affection, doesn't matter how much affection you have, you need to spend more time with her.

Copy paste counter: 6

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
