### ISSUE TITLE
(Issue): I unlocked chess but it doesn't appear in mini games.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#6635]
So, Monika told me a few days ago that I unlocked chess for us to play. The point is that it hasn't appeared in mini games. It's been almost a week now, I thought it would take a while to get the option to play, but nothing. I closed and opened the game a lot of times since then, but it still hasn't appeared. Is it a bug? Is my game broken? I really want to play chess with her.

**Comment by jmwall24** [comment]
Can you upload your persistent file here please? Instruction for finding it are [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

You'll need to put it in a zip file to upload it to GitHub.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
