### ISSUE TITLE
(Bug) No "I love you too!"

### ISSUE THREAD

**Issue by 20RaVen23** [Monika-After-Story/MonikaModDev#6637]
On the story "The Grasshopper", Monika says "I love you so much, [player]~", but there's no "I love you too." afterwards.
![noiloveyoutoo](https://user-images.githubusercontent.com/55263957/98043503-153db480-1e04-11eb-9903-116d4401f830.jpg)

**Comment by SamanthaLind** [comment]
From what I see there appears to be "I Love you too" dialogue...

**Comment by 20RaVen23** [comment]
There is supposed to be an "I love you too!" coming from the player, not Monika. When you tell her "I love you too" she just reacts, not a "I love you too!" from her since you already said it.

**Comment by SamanthaLind** [comment]
Oh, alright. Sorry about that. I think I never looked into history so I have like zero idea about how it should look. But yeah, she just closes her eyes, blushes and smiles sweetly.

**Comment by multimokia** [comment]
I can't replicate this, seeing the story myself, I get the `I love you too` option

**Comment by multimokia** [comment]
Wait, was this from a new story or not?

**Comment by 20RaVen23** [comment]
I used ` Can you tell me a story? > New story.`

**Comment by multimokia** [comment]
Okay I see the issue

**Comment by multimokia** [comment]
This is addressed in the linked PR

**Comment by multimokia** [comment]
Closing as complete
