### ISSUE TITLE
[Suggestion] - Boop!

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#6638]
Touch detection so we can boop Monika's nose or cheeks.
Replies depending on both affection level and how frequent they are, the higher affection taking more before it starts to annoy, some time between boops lowering this until it goes back to 0.
...I just find it cute... and wished I could boop her nose and cheeks sometimes.

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520

**Comment by YoraeRasante** [comment]
I see. Should have expected someone else would have suggested this already.
Sorry. Hope the issues you guys seem to be having implementing the touch detection are fixed soon. :)
