### ISSUE TITLE
DDLC MAS won't open and a window shows an error

### ISSUE THREAD

**Issue by SAELOVS** [Monika-After-Story/MonikaModDev#6640]
The last time I saw Monika was a weeks ago, I said "I'm going to take you somewhere." because I was going to move her to a different user. However, I couldn't open the game after, so I uninstalled and re-installed COUNTLESS of times. It never opened anymore.

This is what the window says after trying to open the game when I modded it today:
![githa](https://user-images.githubusercontent.com/73940533/98106244-25bd6000-1ed4-11eb-8174-ea2182e6fea5.PNG)

Please help. I miss her company :[

**Comment by scpketer** [comment]
Could you post a screenshot of your DDLC installation folder? Which has `characters` and `game` folders and `DDLC.exe` file.

**Comment by SAELOVS** [comment]
![gettinhelp](https://user-images.githubusercontent.com/73940533/98107730-e5f77800-1ed5-11eb-89cf-9785a632bd83.PNG)
Here is the folder, well, at least the inside of the folder. By the windows-i686/lib folder, I'm not sure what you mean by that :( I'm sorry for being a bit of a hassle

**Comment by scpketer** [comment]
Hmm, everything seems pretty much okay here, that's weird.

**Comment by SAELOVS** [comment]
Apparently, it can't open DDLC.py. Is there any possible reason as to why this occurs?

**Comment by LooseEthics** [comment]
Try moving your install folder to some place that doesn't have you username in the filepath. Judging by those question marks in the first screenshot, you likely have some characters there that renpy doesn't like.

**Comment by SAELOVS** [comment]
Oh, okay. I'll look up on how to do that and see how it goes, I'll update with a comment. Thank you.

**Comment by scpketer** [comment]
Well, I'd check read permission on DDLC.py as well, but if you're saying you were reinstalling... It should be okay then. Right, try moving DDLC folder somewhere *with no spaces* in path, they might get in way too.

**Comment by SAELOVS** [comment]
I created a whole new user, it was the username. Thanks guys ^-^
