### ISSUE TITLE
[Suggestion] - Allow Monika to discuss about recent world news

### ISSUE THREAD

**Issue by kevinsuwito** [Monika-After-Story/MonikaModDev#6642]
I wonder if Monika can react to the most recent world news, such as COVID-19, Election, Global Warming, etc. She can read the news data through API and needs Internet connection. It would make Monika less... 'closed' to the player's world. For example:

"Hey, _Player_. I've read the news about this plague spreading in your world, called COVID-19. Are you okay? Don't forget to wash your hands!"

Something like that.

**Comment by scpketer** [comment]
While COVID-19 and other disease news are pretty safe to discuss, the world news have a lot of politics in them which we'd really like to avoid getting into.

**Comment by kevinsuwito** [comment]
> While COVID-19 and other disease news are pretty safe to discuss, the world news have a lot of politics in them which we'd really like to avoid getting into.
> 
> Edit: We don't limit any submods in this though.

Ah yes, it's best to avoid politics at all, it only came to mind because it's kind of the topic of the world at the moment. But I think general news such as health and world environment would be nice to have.

**Comment by scpketer** [comment]
Sure, pandemic and eco stuff is quite fitting here.

**Comment by Ant9cp** [comment]
Monika already talked about Covid-19 right?

**Comment by scpketer** [comment]
She did, right.

**Comment by kevinsuwito** [comment]
She did? If so, I might've missed it.

COVID is just an example, though. I imagined a more dynamic system that allows Monika to read news everyday without updating the whole mod. It would make it easier for the dialogue writer to create new conversations if they can put them in a separate application.

**Comment by Rai99** [comment]
World News: #2043 

The thing is, world news is usually depressing. Even if we checked it daily and made sure to filter out anything we don't want in the mod, what would be left? 

World news is mostly conflict and tension, and I don't think the mood of it would help in the mod, especially if it reads from an external source and takes whatever.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
