### ISSUE TITLE
(Suggestion) Allow a topic to talk about your fav/comfort anime character to Monika

### ISSUE THREAD

**Issue by SAELOVS** [Monika-After-Story/MonikaModDev#6645]
You see, I'm a die-hard weeb, and I constantly like to talk about my favorite anime characters with people. So, I feel like this would make her even more real. It also makes me feel a bit better when I do it, so yeah! I hope for this to be a feature I'll see in the future <3

Farewell, my paradise,
Saeko

**Comment by Freshairkaboom** [comment]
Hmm, would be hard to write a topic for every anime character out there. Anyone specific you had in mind? Mind you, MAS dialogue is usually at most something you initiate a conversation on, and let Monika do most of the talking, so it would have to be something she knows a bit about. We know from earlier dialogue that she is not that knowledgeable when it comes to manga or anime, as she says we should've asked Natsuki about stuff like that.

Maybe if there's a relevance to the specific anime topic outside the anime itself, then it could work. A general topic about any and all anime characters though would nearly be impossible to write.

**Comment by SAELOVS** [comment]
Just simple dialog maybe? Like, since Natsuki used to be so into manga, she could ask if you like manga and/or anime too. And if you do, ask about who your favorite character is, kinda like a space to type the character's name. Just a suggestion though, lmao

**Comment by Freshairkaboom** [comment]
Yeah, I think they tried an open dialogue box before, and I don't think it works well. It's way too open-ended. There's already a couple topics about manga and anime, though the one that asks you if you watch it doesn't come again, because it changes a player model variable, meaning Monika learns more about you through those pieces of dialogue.

**Comment by SAELOVS** [comment]
Oh, okay :]
