### ISSUE TITLE
(Suggestion) Show sheet music for piano

### ISSUE THREAD

**Issue by opalmew** [Monika-After-Story/MonikaModDev#6646]
I recently unlocked monika's piano, and i want to try to learn to play. however, i have to have a fully separate tab open in order to see the notes, which makes it frustrating to try and play. i was thinking maybe there could be an option to show the notes for the songs somewhere, like sheet music, that way it's easier to learn the songs.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
