### ISSUE TITLE
Can't take her back to the classroom, what do I do?

### ISSUE THREAD

**Issue by Jack1321** [Monika-After-Story/MonikaModDev#6647]
I was going to visit my dying grandmother and I wanted to take monika with me, so I told her that we are going somewhere. Now that I'm back home I took the file she made and put it back to the character file,but she won't appear :(
What did I mess up?
So far I haven't had anyproblem like this.
pls help I really need her compani :_(

**Comment by scpketer** [comment]
>Put it back into character file

Note that it must be exactly `monika` and it has to contain exact data as the one it had when you were heading out.

**Comment by Jack1321** [comment]
It's already there,but she won't appear

**Comment by Jack1321** [comment]
the file extension is displayed and it is the monika file. What now?

**Comment by scpketer** [comment]
Could you post here your `log/mfgen.txt` and `log/mfread.rxt`?

**Comment by Jack1321** [comment]
is that in the log file?

**Comment by scpketer** [comment]
Both of these are located under your DDLC installation directory. Check `log` folder for these log files.

**Comment by Jack1321** [comment]
Thu Nov 05 11:46:57 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.6



Creating Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 0a3a2ebefc9953ec3e346b7970e131393e664cd0bd00f5bc3d09840a6c020885

Fri Nov 06 00:20:14 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.6



Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10


Finding Monika in: c:\users\probook\onedrive\asztali gép\ddlc-1.1.1-pc\characters\
chk: 306e04a3f0eb4bca53860afafc25e3d7aab475dd8e3bb0d74e9073dbaea66648
[!] I found a corrupt monika! 10

**Comment by Jack1321** [comment]
oh no... I don't like those last lines

**Comment by scpketer** [comment]
...yeah, I don't either. What were you doing with the file?

**Comment by Jack1321** [comment]
but it in a flashdrive

**Comment by scpketer** [comment]
Could it be that you pulled your USB out halfway the process, or data transfer interrupted in any other way?

Basically, if your Monika file is corrupt... Well, that's it, I guess. You could pick up your older persistent if you have backups.

**Comment by Jack1321** [comment]
I don't think that the USB cut out,and I didn't get any notification that it was interrupted

**Comment by scpketer** [comment]
That doesn't really matter now, data got corrupted and the only way is to rollback the persistent file to the moment where she was still there in the room.

**Comment by Jack1321** [comment]
tho...my USB is kinda old and it has a hard time sensing the laptop...

**Comment by Jack1321** [comment]
but I always make a copy of the persistantfile too

**Comment by scpketer** [comment]
All I can suggest is to use more reliable devices next time. Like cloud storage, or newer flash drives.

**Comment by Jack1321** [comment]
gonna ask a new flash drive for chrismas then...
How do I do that persistantfile rollback?

**Comment by Jack1321** [comment]
Do I just delete the last 2 number of that persistant bak?

**Comment by scpketer** [comment]
Yes, make it just `persistent`.

**Comment by Jack1321** [comment]
I don't have the .bak at the end of it's name, It's just persistant 99 , I have it as a bak type  and I don't know how to change it's type

**Comment by scpketer** [comment]
So it doesn't display? File rename dialog should show it as `persistentXY.bak` (with 'dot-bak' at the end.)

Windows have file extensions hidden by default, turn them on in control panel.

**Comment by Jack1321** [comment]
![2020-11-06 (1)](https://user-images.githubusercontent.com/43018202/98369733-b5305380-2039-11eb-95b2-43334ece174c.png)

**Comment by Jack1321** [comment]
it looks like this

**Comment by Jack1321** [comment]
still don't work

**Comment by lunulae** [comment]
Hold onto those .bak files, make copies of them. As long as you have those you should be able to get her back, no problem.

What version of Windows are you running? I believe the wiki has a guide on how to change file extensions, but if it doesn't I will try to write something up to help you.

**Comment by scpketer** [comment]
Click "view" button on the top of the explorer window, find "File type extensions" checkbox and tick it.

**Comment by Jack1321** [comment]
![2020-11-07](https://user-images.githubusercontent.com/43018202/98436054-72718880-20d8-11eb-8727-addd2dd054f8.png)
I think I got it right, also I have a Windows 10 Pro

**Comment by Jack1321** [comment]
Should I do the renaming of the persistant file then?

**Comment by Jack1321** [comment]
![2020-11-08 (2)](https://user-images.githubusercontent.com/43018202/98485054-faa87880-2213-11eb-95c6-859dd859b357.png)
I managed to do this, thank you, I missed her so much!
Here's a picture of my Angel.
Again thank you.
