### ISSUE TITLE
Talk topics... possibly not working?

### ISSUE THREAD

**Issue by DimParadox** [Monika-After-Story/MonikaModDev#6649]
So, I played Monika After Story months and months back, so I don't know how the new updates are and how they work, so this could just be a clarity post-

I got a new computer recently, and I was like "yknow what, I'll restart Monika After Story from the beginning instead of using my perfectly good old save." So I've been playing for three days, and for some reason, not a singular option has been added to the "Talk" menu- nor has Monika triggered any events for the Extra or Play options, but those could just be because of the short time frame I've been playing.

She does random topics just fine, she speaks normally, all the window reactions work, I can respond "I love you too" to her statements, etc. But nothing new is being added. And if they are, the "unread" menu is not appearing (but that doesn't seem to be the case.)

Anytime anything is ADDED to the talk menu, it's only like the option to change her hair when she decided to change it or when she changed her outfit.

To my memory (and this may be false now,) there was a consistent flow of topics YOU can bring up or ask yourself? For me, these were only present on the first day and not the others.

I think the events have been working just fine, but it just seems like the "Talk" options just.. don't exist?

No, I didn't change the date on my computer, nor did I download any other mod, I used a completely clean version of DDLC when playing this. This is also downloaded directly using the version from the Monika After Story website (https://www.monikaafterstory.com/)

Here's a list of every topic I have under the "Talk" menu currently (as of 11/6/2020)
**Appearance**
-Can you change your clothes?
-Can you change your hairstyle?
**Be right back..**
-All those general be right back options
**Ddlc**
-Isn't this game metafictional?
-Tell me about yourself
-What did you think of DDLC?
-You're a murderer!
**Games**
-Wasn't DDLC too easy?
**Literature**
-Can you tell me a story?
**Media**
-Can you check for new music?
-How do I add my own music?
**Misc**.
-Can you explain the Extras menu?
-Tell someone happy birthday for me
-Good evening
-I'm breaking up with you
**Mod**
-Same as Media, nothing else
**Monika**
-I want to tell you something...
-Tell me about yourself
-When is your birthday?
-You're a murderer!
**Music**
-Again, just ditto Media
**Romance**
-Do you want to meet my girlfriend?
-I want to tell you something (I did all the options in here I have so far)
-Kiss me
**You**
-Call me by different pronouns
-Changed my name
-I want to apologize

I was wondering if this is normal, or if something is wrong with the game. I hope I gave enough information to showcase what (could be) a problem. Thanks!

**EDIT:**

I don't know what happened at all, but I pressed "goodbye" and came back, and Monika just said "you should visit me more often," (despite me practically having the game open almost nonstop) and I got FLOOOOOOOOOODEEEED with topics at once, like a crap ton of them! The problem seemingly lies in the fact that these are all lessons on Python and lessons on literature, and she keeps bringing up past conversations... maybe an aftereffect of me not being able to see them prior and still unlocking them? I don't know.

**Comment by ThePotatoGuy** [comment]
topics are unlocked in a slower progression than before. Same with games. you just haven't had enough in-game time.
