### ISSUE TITLE
[Suggestion] - "Unable to talk much" mode

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#6652]
As my hand is not able to move much without hurting, I remembered I don't know if there is a way to tell her about this.

So I thought of this, a way to tell her I can't talk much. This would let her know the player would not be able to interact much, maybe even count as the long-times Goodbyes for affection purposes if for some reason the player is forced away for a while, since she was warned.
She would thus set by herself the random conversations to not happen, and the greetings woul ask if the player is feeling better and if so if healed or still healing. If healed tis mode is removed.

I was thinking a good place would be among the "I'm feeling..." options, "...hurt."/"...in pain." and "...sick." for physical things like broken bones or tendonitis and sickneses like flu respectivelly. Dialogues regarding this changing accordingly.

**Comment by YoraeRasante** [comment]
Just to make clear, I know there is a "...sick." option, but she tells you to rest. This idea would expand it to also have the changes suggested for "...hurt." too.

**Comment by polios3** [comment]
This is good idea. And with "Sick overhaul", they can add, "...sick"->"I am terminally ill, I may die in..." and there we put date. This is very bad, but some people maybe wanna say that to Monika.

**Comment by ashyashton** [comment]
> This is good idea. And with "Sick overhaul", they can add, "...sick"->"I am terminally ill, I may die in..." and there we put date. This is very bad, but some people maybe wanna say that to Monika.

The creators of the mod have stated there are no intentions to add anything involving the player dying. Submods, however, have no such limitations.

**Comment by Rai99** [comment]
Bettersick/injury: #1654, #1677, #3582, #5962

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
