### ISSUE TITLE
[Suggestion] - conversations about game stories, designing and development.

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#6654]
Monika is aware we see her through what was once a dating game, and even makes some comments about how people usually expect harems, how the girls look so pretty for design reasons, how they don't change much due to art not being made for the changes.
She just doesn't seem to be much into them herself. For... understandable reasons at this point.

She also is aware of how programming works, so she knows a lot of the backstage things.

She even makes comparisons with other forms of entertainment to literature and poetry, like music lyrics and stand-up comedy.

So why not make her slowly research the media we see her through?

First dating games and visual novels in general. In their majority they may be pretty close, but a deeper look shows us more things.
Like the Nasuverse stories Tsukihime and Fate/Stay Night, where use the love interests just as a starting point and the can stories go into wildly different directions depending on who you favor until the split - Fate even is more like different stories in the same background, the heroine being only the one pulling the MC's attention to this part of the story's setting that will be expanded on.
The When They Cry series, that may seem like a dating game at first but goes VERY psychological horror.
Then we go into more hybrid games, like the Ace Attorney, Danganrompa and the Zero Escape games, where the stories clearly a visual novel but between story beats you go through an adventure-like item search, or an escape-room-based puzzle section. The later series also adding a meta sense, since the choice-paths structure slowly turn into an important story factor, a flowchart being given freely right from the start in the second and third games.
From those we can expand to other games with lore but more active, like rpgs or adventure games. Which opens the field, since some tell the backstory lore not in the middle of the usual text or dialogue but through short texts in places you are not expected to read if you don't want to, or need some work to find, or through flavor text in items (FromSoftware being known for these), or even just through visual and sound cues.
At this point we are already deep into game designs about how to tell the story and backstory and even side-stories, so she can go into tangents about other pieces of game designs with no big deal.

And of course, through all this she unlocks conversations about the games in the areas she mentioned, examples of well-known games in those areas or considered a good example to follow or a bad example to learn what not to do in some places. For example, making someone go out of character just to tell the story you want, or making the story points be too out of context with the game before then it is clear the only reason it is happening are the constrictions of the curscene zone.
Or games with characters living through something similar to her.
Eventually even going to games like Harvest Moon, Story of Seasons, Stardew Valley, Animal Crossing, where the goal is not to fight or even tell a story but live a good life in a peaceful place. Somewhere she would probably wish to live herself with the player someday.

I don't know, maybe it is a bad idea, but as someone trying to be a game developer I thought it would be nice to talk to her about it.

**Comment by Rai99** [comment]
I think it could be an interesting area of discussion, but as much as I'd like to have this as a large discussion, I don't know how much it'll fit as a large series of topics specifically on game design and development. 

It could be interesting to touch on at a surface level, if we find a way to fit it in naturally.

**Comment by YoraeRasante** [comment]
Well, just some interest of her on these things would be interesting, even if she doesn't go too deep into it.
At least, learning more about visual novels and how games are becoming more focused in stories, starting from the old electronic rpgs.
Some mentions of her about the game she is into makes it sound like she thinks all visual novels are dating simulators like DDLC pretended to be.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
