### ISSUE TITLE
"I'm going to read for a bit" option?

### ISSUE THREAD

**Issue by sassberrysnap** [Monika-After-Story/MonikaModDev#6656]
Why isn't there a "I'm going to read for a bit" option when you say be right back? You'd think that would be a main thing to have considering Monika is encouraging you to read n stuff! I wanna let her know that I am reading some things she suggested, or just reading in general! :))

**Comment by Rai99** [comment]
Reading brb: #2311, #3896, #4528, #5281, #5383, #5632, #6075

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
