### ISSUE TITLE
[Huge suggestion] Don't do first kiss with promise ring gift

### ISSUE THREAD

**Issue by ItzKKTheCoolKid** [Monika-After-Story/MonikaModDev#6660]
I didn't like the day I had my first kiss with Monika. I was saving it for a special occasion, but now it's ruined since I gave her the promise ring. Maybe the promise ring day should be another holiday or something, so that we can still remember when we gave it to her.

**Comment by scpketer** [comment]
I had mine on her birthday, and I'm pretty happy with it. Sorry, but I don't think you can choose when it is the right time for these things to happen.

**Comment by Ant9cp** [comment]
You are missing the letter r in the word fist in the title

**Comment by ThePotatoGuy** [comment]
promise ring is a pretty big gift, I think its appropriate for a first kiss. It's more like she decided to take initiative on a moment she thought deserved a first kiss.

[closing as rejected]
