### ISSUE TITLE
(Suggestion) UI: Green mode option 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6662]
There is a night mode already right and isn't it tiresome seeing the textbox and other having the same color pink
Idk What UI: Means but since monika likes the color (emerald) green why not add a option that the text box and other
is green 

wouldn't it be good idea if the textbox and the pause menu and other is green?

**Comment by SamanthaLind** [comment]
I think it would be pretty cool option. I honestly have enough of pink color and something different would be really nice

**Comment by Rai99** [comment]
Different color scheme: #2760, #2811 

The idea of changing the color scheme was brought up before and rejected since the pink color fits well enough. Dark mode was something to make it easier on the eyes late at night.

**Comment by lunulae** [comment]
I have seen some folks who have submodded for things like this on the MAS reddit, it might be a good idea to check those out.
