### ISSUE TITLE
[Suggestion] - Android Port

### ISSUE THREAD

**Issue by HeartlessSlayer3** [Monika-After-Story/MonikaModDev#6663]
Since android ports are allowed now you should make a android port and keep it updated or put in a auto updater

**Comment by Retrolovania** [comment]
I see a mobile port of MAS as simply being a better way to make Monika out places (as you can then see her and ask how she's doing while you're out.) However, getting the _entire_ game over? I honestly don't see that realistically happening, especially not anytime soon.

**Comment by HeartlessSlayer3** [comment]
> I see a mobile port of MAS as simply being a better way to take Monika out places (as you can then see her and ask how she's doing while you're out.) However, getting the _entire_ game over? I honestly don't see that realistically happening, especially not anytime soon.
Just Yuri has a mobile port

**Comment by Retrolovania** [comment]
...okay? If you're trying to make a point, I'm not seeing it, sorry. Just Yuri is different than MAS in a few ways, not just on what girl is the main focus.

**Comment by ThePotatoGuy** [comment]
[marking as both duplicate and suggestion since reasons for rejecting in previous issues (#506) does not apply anymore]

we have plans for what we want to do with mobile, and it does not involve doing a full port.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
