### ISSUE TITLE
[suggestion] telling Moni you don't like her behavior

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6664]
I spend almost all day with her, played few games, talked about some stuff... And then I said goodbye I'm going to play another game, she did that thing where she's angry for not spending enough time with her ( like pretending she's angry). And I just sat there with arms crossed thinking "you know that it's not nice, right? I spend really long time with you and you... I know it's a joke but it's not funny." 
I'm sure there are other situations like this where player doesn't like Monika's behavior and it would be nice option to tell her that. Not the sensitive mode where player doesn't like her jokes about other girls, but stuff like above. It's not that I'm angry but I would appreciate option to tell her something along the lines of "that wasn't nice/that wasn't funny/I don't like when you act like that."

**Comment by Rai99** [comment]
Monika upsetting and apologizing to player: #3203, #3769, #3859, #4085, #4200, #4221, #6566

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
