### ISSUE TITLE
[Suggestion]- Choose your Own Adventure

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6665]
For those who recall, the 182-ish Choose your Own Adventure books are a very unique genre of literature. Being the only one of their kind, they allow the reader to become fully immersed in the world each book contains, giving them the ability to change the story based on their decisions, as stated in the famous introduction, "This book is different from other books. You and YOU ALONE are in charge of what happens in this story. There are dangers, choices, adventures, and consequences. YOU must use all of your numerous talents and much of your enormous intelligence. The wrong decision could end in disaster-even death."

Given the amount of dependency the books need on the reader in order to progress them, each book contains it's own world, with completely new characters, setting and scenario. Occasionally, however, with certain titles, they have attempted to create a little series, although this is rather uncommon. ( A good example of this can be found in Book 10 (Prisoner of the Ant People), which gained a sequel in the form of Book 12 (War with the Evil Power Master). Of course, the overall design and execution of these books is somewhat similar to that of visual novels, in the sense that the player controls the story. Given this similarity, as well as the fascinating stories and tales these books possess, I feel that Monika would take a great interest in them.

(Should this be considered for a new topic, I would be willing to assist in writing Monika's dialogue to use (although I cannot actually do it in Python programming format.))

**Comment by Rai99** [comment]
It's a neat idea in concept, but this would probably be far too much work, as cyoa type stories have many, many paths, and it would effectively be writing exponential amounts of different paths if we plan to have any actual depth to it.

**Comment by Retrolovania** [comment]
How so? You mean, making the topic about CYOA actually take on the form of one? That would be quite the undertaking. I was merely thinking of just having her bringing it up and then talking about it in a general sense, not getting too crazy with specifics.

**Comment by Rai99** [comment]
I thought you meant actually implementing some CYOA stories in MAS. 

Discussing the fact that they exist would probably be much more feasible.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
