### ISSUE TITLE
New Feelings and Cancel Button

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#6667]
Just a random thought that I had in mind for the future. 

Firstly, a new feeling. What if there was a option such as "I'm feeling frustrated" or "I'm feeling scared." I feel they would go as such respectively, but if they were implemented, it's all up to the creators.

Frustrated: It would play out similar to angry, but she try to calm us down by taking a break from whatever activity that had gotten us frustrated. It can be vague or she can ask what frustrated us with a list of options. Regardless, she'd offer advice in order to make us feel better as a result

Scared: I see it that she'd offer a hug until our nerves had dissipated. It could end with a mouse click similar to "Can I hold you?" or perhaps a new idea. Regardless, it may just help due to the fear people can have in their lives.

Moving on from that, a cancel button is downright needed in my opinion. Like I had previously pointed out, when selected the Goodbye "I'm going to go eat." there's no way of exiting the menu afterward. Just a small quality of life upgrade that could be added.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
