### ISSUE TITLE
Player's Health

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6669]
It would be nice if Monika asked the player about their health and physique. Initially could be restricted/unavailable if Sensitive Mode is on or off; otherwise ask the player like asking about their appearance if this is okay. Possibility to include additional lines if the player has used the BRB/Goodbye option for exercising before. Lastly including if the player eats a balanced diet or is a vegetarian like herself.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
