### ISSUE TITLE
ACS Submission - Three NES-Style Bows!

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6670]
A little while ago, I challenged myself to make a new bow for Monika...but utilizing the graphical palette and limitations (mostly) of the good ol' NES! After seeing the results, I decided I just couldn't keep this to myself. Besides, I figured it'd be a great way to contribute to the mod! So, I decided to submit it here to see if it could be "official spritepack-worthy." Included are the necessary files for the bow, as well as those for a blue bow and a special emerald green bow, all done NES-style! I hope you like them! I worked really, _really_ hard on these!

[retrolovania-nesbows.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5508292/retrolovania-nesbows.zip)

**Comment by Ix-30** [comment]
Sire, hail to you. Nes was my first Console, I really wanted these. you truly are a man of culture.

**Comment by Retrolovania** [comment]
Danke, comrade!

**Comment by ThePotatoGuy** [comment]
@Rai99  since this is a submission, dont add the spritepack label and instead add to the Art Ideas project under art subs awaiting review.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
