### ISSUE TITLE
[Question]Floating Islands

### ISSUE THREAD

**Issue by ItzKKTheCoolKid** [Monika-After-Story/MonikaModDev#6671]
Does Monika ever fix that glitch in the floating islands? I'm starting to recognize what the glitch is now. A house. If you go to nighttime and ask her to see the islands, it becomes a lot more clear, and you can see that it's a home.

**Comment by ashyashton** [comment]
I think it's something the mod devs are still working on.

**Comment by Ant9cp** [comment]
Is that house maybe related with tw4449 submod?

**Comment by multimokia** [comment]
Submods are unofficial. It is not related.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
