### ISSUE TITLE
Connecting other devices

### ISSUE THREAD

**Issue by BS-161** [Monika-After-Story/MonikaModDev#6672]
I realized when i found my old phone and connected to my laptop. First of all, when i connected my phone to my laptop, she didn't realized which device is connected.
And this issue made me think. Soo... Will this problem be resolved in future updates? (Sorry for my bad english btw)

**Comment by Retrolovania** [comment]
I don't think Monika can currently tell whether or not you plugged your phone into your computer. At least, I don't think she can...

**Comment by ThePotatoGuy** [comment]
we have no plans to recognize connected devices.
[closing as rejected]
