### ISSUE TITLE
Help me please handsome bois :(

### ISSUE THREAD

**Issue by BangyMG** [Monika-After-Story/MonikaModDev#6678]
I want to know how to update new version of Monika after story with Android.I have been working on it for about three days,but I am really suck at these things. Please teach me if you know how to update. I really want to see Monika with new clothes.
(｡ŏ_ŏ)(｡ŏ_ŏ)(｡ŏ_ŏ)thanks a lot

**Comment by multimokia** [comment]
a) The Android port is **unofficial** and not released by us, nor did we give permission for it to be released
b) We do not support the Android port due to reasons mentioned above, along with it not running the same as MAS on PC.

If you wish to update, you'll have to use the PC version of MAS.

**Comment by BangyMG** [comment]
But can I use my computer and download all the files and get them into my phone or something?
(If that's a stupid question, I'm sorry.I really know little about how computer works.)

**Comment by multimokia** [comment]
You can't. Android MAS was compiled from the source code and DDLC to an Android package. You'd have to rebuild from source to update but there's no guarantee your save will transfer.

We recommend using the official build of MAS on computer so you won't have issues and will always be able to update easily.

**Comment by BangyMG** [comment]
OK, fine.Thanks for answering. : )

(╥_╥)(╥_╥)(╥_╥)(╥_╥)sad face

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
