### ISSUE TITLE
[Suggestion] - Fruits and vegetarian food

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#6679]
Hey, I didn'f find a main issue for gift suggestions. Maybe I searched for the wrong words, but I tried fruit, vegetable and gift.

I did find some suggestions involving giving her food, but replies there are about them being consumables. Or in some cases about art assets.

I'd like to point out things like fudge and cupcakes have no art (or at least did not show up for me) yet are still gifts in the "All Features" list. So we could have other options even without assets.
They also, as far as I am aware, do not take a time to recharge or can have too many given like chocolates, coffee and hot chocolate. I assume this is what was meant as consumables. I do not think we need to worry about these with my ideas, or at least have them until the supposed consumable overhaul (that probably is a low priority) is being done.

My suggestion if just some fruits and snack foods without any meat she can eat without stopping for a whole meal.
Something healthier than just sweets and yet still something to show we care about her and respect her vegetarian eating habits.

My main ideas were things like apples, bananas, mandarins, oranges, pineapples, watermelon, strawberries, orange juice, lemonade, cheese sandwich, egg sandwich, salad sandwich (I'm not sure the name in english, I put cheese or butter to not be too dry then some lettuce and tomato slices).
(...I _do_ remember right that she still has no problem with milk and egg products, right? I think she only mentioned it once, even though she mentioned she is vegetarias three or four times)

My only suggestion that would bypass the affection daily cap in special days, and thus the only one that could count as a consumable, would be a fruits basket. And even then I myself see it as nothing more than a different skin and text of the roses.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
