### ISSUE TITLE
[Suggestion] - Simple minigames

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#6680]
Simple minigame ideas that hopefully would not give much work to add but would still add some variety.

If this became a main minigames suggestion issue, I'd be happy. I tried looking for them but could not find it. Maybe a wrong keyword.

My first idea was just the classic Checkers. We already have Chess, and it uses the same board.
Another idea would be Reversi. It can reuse Chess/Checkers' boardI think.
For the simpler ones still (for the player), Tick Tack Toe.

**Comment by kittendetails** [comment]
I liked the idea. I want to add the suggestion of "rock, paper, scissors" too. I guess this is something more difficult to implement, considering that it would have to have three new arm poses. I thought maybe three options, where the player chooses between them and Monika's choices are randomly generated, then a message appears "Monika chose scissors!", but I think this is too artificial for the mod (and Monika). So, I think the idea of ​​new poses for this is better, but it would be difficult to implement.

**Comment by MadFoot8** [comment]
Yes, checkers, I prefer them than chess, and I suggested tic-tac-toe game back in 2018 and it's still in consideration

**Comment by eyelesssally** [comment]
Or we could scrap the poses altogether and just do a simple icon-based sprite.

**Comment by YoraeRasante** [comment]
I was going to suggest rock paper scissors/janken on the first post too, but as said would need something to show them. Both Monika to us, which means sprites, and us to Monika.
My thoughts would be cards, as Monika cannot see our hand: she puts her on the table,, and we have three cards and click on one.

**Comment by eyelesssally** [comment]
Cards would be pretty easy to implement I think, great idea!

**Comment by eyelesssally** [comment]
Threw together a quick concept picture for this; I have the artwork for the cards if anybody wants it! All we would need is the code.

![RoshamboConcept](https://user-images.githubusercontent.com/56178333/99326108-a28df980-2845-11eb-8046-f3822ce2e07a.png)

**Comment by ThePotatoGuy** [comment]
these cards look amazing. we could probably skip over having new monika sprites by just showing these 3 cards as in this picture and use different color highlighting to show who picked what.

**Comment by eyelesssally** [comment]
Here's the [.psd](https://drive.google.com/file/d/15crYOpTN6XbWZYk8Xh2FItODv3TrXfvI/view?usp=sharing) as well as the cards in .png format. Feel free to make use of them! Would love to see this added to MAS. 
![RPS_Cards_Spooks_Scissors](https://user-images.githubusercontent.com/56178333/99336895-7d05ed80-284f-11eb-9736-84d8e98e54ab.png)
![RPS_Cards_Spooks_Paper](https://user-images.githubusercontent.com/56178333/99336904-7d9e8400-284f-11eb-9e45-a725a6a54b40.png)
![RPS_Cards_Spooks_Rock](https://user-images.githubusercontent.com/56178333/99336909-7e371a80-284f-11eb-9e0b-eb81a6947a83.png)

**Comment by Rai99** [comment]
If rock paper scissors is planned, I had ideas on how to make it a little more than pure 1/3 RNG.

**Comment by eyelesssally** [comment]
Like what? Rock, paper, shotgun, lizard, spock, kinda variants?

**Comment by ThePotatoGuy** [comment]
@Rai99 add your ideas to my issue

**Comment by YoraeRasante** [comment]
> If rock paper scissors is planned, I had ideas on how to make it a little more than pure 1/3 RNG.

like the things mentioned in HunterxHunter? 
Been a while since I watched the competition, but I think it was... most people instinctivelly start with rock and right after losing they tend to use the hand that would have won their last bout.
I personally would have added how most people have a favorite that they use by reflex. Mine is scissors for example.
So Monika would have a higher chance to start with rock, then a higher chance to choose the one that would have won the previous one if she just lost. And if past/not using those preferences, a higher chance to use her personal favorite (I'm imagining paper).

**Comment by ThePotatoGuy** [comment]
regarding the original post's suggestions:

#829 - checkers
#778 - reversi
#687 - tic tac toe

and a main minigames issue - #55

[closing as duplicate]
