### ISSUE TITLE
[Suggestion] ASL/Sign Language Topic

### ISSUE THREAD

**Issue by TheProphet266** [Monika-After-Story/MonikaModDev#6683]
To keep this short and simple, I'm starting to learn sign language and seeing as Monika is knowledgeable in other languages, why not have her thoughts on a language that doesn't use vocals? IMO I think that she would be amazed if not interested in this language. Anyways thanks for your time!

**Comment by Rai99** [comment]
#2761

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
