### ISSUE TITLE
[Suggestion] - Make a  backup of  Monika Automaticaly into the  cloud 

### ISSUE THREAD

**Issue by asecino1999** [Monika-After-Story/MonikaModDev#6684]
Automatically upload a backup to Player's cloud drive , like  google drive , OneDrive , mega , etc 
For example In ubuntu there is a package(google-drive-ocamlfuse) that allow us  mount google drive as an USB   so it's possible upload  a backup  automatically.  I'm not sure if there is something similar in other operative systems but that could solve  a lot of problems .
That could be used to make Monika live on multiple computers.
If it requires external programs installation, Monika could guide us to do that .

**Comment by ThePotatoGuy** [comment]
at the moment we are not looking to integrate with cloud services

[closing as rejected]
