### ISSUE TITLE
@Kaiewe Little issue with the sprites off the black squared shirt

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6685]
There is this black dot or something on her right arm on the first screenshot and it disappears in other poses
![screenshot0001](https://user-images.githubusercontent.com/71310908/99009918-30699c00-2549-11eb-8420-9de10bf25a1a.png)
![screenshot0002](https://user-images.githubusercontent.com/71310908/99009936-3d868b00-2549-11eb-83f7-fdb515901f38.png)

Thanks for this awesome gift btw🤩

**Comment by Kaiewe** [comment]
Oops, there's a problem with the "leaning" pose. I will change it right now.
Thanks for letting me know!

**Comment by Ant9cp** [comment]
No problem bro 👍 welcome to github

**Comment by Kaiewe** [comment]
> No problem bro 👍 welcome to github

Thanks! :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
