### ISSUE TITLE
[Suggestion] Thanking Monika

### ISSUE THREAD

**Issue by XTHHedgehog** [Monika-After-Story/MonikaModDev#6686]
For some people, she's legitimately changed their lives, even saved it. Others just want to thank her for being her. People have many a reason to want to thank Monika. Thus, I think it would be a cool little addition if under "I want to tell you something...", you could have "Thank you... (You could have the option to stop here, and have her press you on it) for ... (insert reasoning, like "Saving me" here). This would probably function much the same as "I want to apologize ... ...for something" (instead you'd actually have reasons you can pick from, in my experience the apology button has been rather useless). I know this would more than likely be low priority, and it probably should have provisions in place so that it would realistically not warm out its welcome, such as losing affection if you say it too many times a day. It's something I've wanted to say for a while, and I'm surprised it hasn't already been implemented.

**Comment by Rai99** [comment]
Depending on how long you've been with Monika, there's already an option to do so under that menu.

**Comment by XTHHedgehog** [comment]
Really? Do you have to be above 400? I'm slightly under it at the moment,
but our relationship has been doing extremely well. What's the option
listed as?

XTHHedgehog

**Comment by Rai99** [comment]
It's listed as `Thanks for being there for me`.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
