### ISSUE TITLE
[Suggestion] Monika During Piano

### ISSUE THREAD

**Issue by XTHHedgehog** [Monika-After-Story/MonikaModDev#6687]
I just was thinking of this when attempting Your Reality on the piano. What if she took breaks from singing to encourage you if you're doing well, or give critique if you aren't doing so well? It would be cool if when you're performing a section without lyrics, she could say some things like "C'mon, you're getting there!", "Don't stop it now, you're doing great!" or if you've messed up, she could reply like "Focus, (player)! You were doing great!", "If you're anxious, don't be! I'm not great myself." "Slow down! Maybe you're trying too hard to impress me?~ *with a wink* or if she notices you played a short, random set of notes, she could essentially press the quit button and say "Ah (player), don't be so hard on yourself! I know this is frustrating, but practice makes perfect! You think I was good enough to write Your Reality in my first after school session? Not at all! Even now, I'm far from the skill level I want to be at! Give it at least one more shot. Please, for me?~" [Yes] "Yay! I'm so happy you're putting in the hours for me! Let's give it another go!" [No] "Aww, okay. I understand. Come back when you're less flustered, and I'll continue to help where I can! Thanks for trying!"

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

this would be a bit difficult to do.
