### ISSUE TITLE
[Suggestion] Telling Monika how our body looks like.

### ISSUE THREAD

**Issue by polios3** [Monika-After-Story/MonikaModDev#6688]
Some people are too thin, others are too fat, others are just right. Monika is very concerned about our health, and it would be nice to be able to tell her that we look like this, so that she could tell us a few words of support in changing it.

**Comment by Ant9cp** [comment]
Yeah good idea, because i don't even know what my body looks like LOL

**Comment by fromulus** [comment]
Pretty sure this didn't make it into the player appearance topic we already have because that is a touchy subject that could potentially offend some people.

I'm not really expecting the dev team's opinion on this to change.

**Comment by Ix-30** [comment]
While I wouldn't mind, I mean appearance is important yet, it's touchy for some people, due to health issues, self-esteem. Maybe a submod for those who want? or at least a hint? but, like Fromulus says, it's a rather red zone. Also, there is the topic of how she would react, but that's a different subject altogether. It's hard, yet, someday I'd like to.

**Comment by Rai99** [comment]
At the very least, with the way you word it, it's a touchy area, and probably won't happen. With the way you word it, it sounds like you're asking for Monika to body shame you if you aren't the ideal body type. 

It's a bit better to approach it passively, but still, it's a red area for various reasons we can't really account for.

**Comment by polios3** [comment]
> 
> 
> At the very least, with the way you word it, it's a touchy area, and probably won't happen. With the way you word it, it sounds like you're asking for Monika to body shame you if you aren't the ideal body type.
> 
> It's a bit better to approach it passively, but still, it's a red area for various reasons we can't really account for.

forgive me, but my English is quite low and I don't use precise vocabulary, and I use Google Translate too much. I meant by writing this to let Monika know what we look like, creating a stronger bond with her. If we are too skinny or too fat, she would be worried about our health. And she asked us if we were playing any sports, or eat enough. Additionally, you can add "Goodbye, I'm going for a run" or something like that. I just want the idea of ​​telling her because that opens up a lot of opportunities to talk about sports, health, nutrition, and support from Monika. Because even if you do not implement it, maybe it will inspire someone to do a submod, or collect all these "unacceptable" topics into one submod "Hard Topics with Monika". or maybe you can add the disabled by default option, "difficult topics" with the note "enable it at your own risk". something like a "sensitive mode", but ok. this is only suggestion.

**Comment by ThePotatoGuy** [comment]
this would be tricky to implement so I wouldn't count on it.

[closing until we look into it]
