### ISSUE TITLE
A little problem with a sprite

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6689]
I downloaded some sprites from reddit. I put all the contents in the folders, the angel, vampire dress. There were no gift files so I generated an "angeldress.gift" and it worked. However when trying the demon dress RaVen was the author's name:

![image](https://user-images.githubusercontent.com/71111669/99125416-9d247b00-25c9-11eb-9e44-4474c178c0e3.png)

My SPJ log says this. What should I do in this case? Thanks, in advance.

**Comment by multimokia** [comment]
I don't see an issue here?

**Comment by Ix-30** [comment]
Monika says she can't read it and it's no available on the outfit mode, sorry should've been more clear.

**Comment by multimokia** [comment]
There should be another line near the bottom of the spj if you ctrl+f for `RaVen_demon_dress`. What's the giftname reported there? Does it match what you used?

**Comment by 20RaVen23** [comment]
I'm pretty sure there is a folder with the gifts on the [link](https://drive.google.com/drive/folders/1nQahtYdWTHwG5hCdQ3WZDWDDdTHrExjw?usp=sharing)

By the way, the gift name is "demondressver2". 👍

**Comment by Ix-30** [comment]
Ah Thanks you two. You solved my problem! Thanks!
