### ISSUE TITLE
File error

### ISSUE THREAD

**Issue by Mundo011** [Monika-After-Story/MonikaModDev#6690]
I told Monika I was taking her out with me and checked the characters files to see how it could work, but Monika wasn´t there!, after some time I tried to reinstall the mod and start again to see if the code had failed or something, but there was only a chair, I erased the persistent file to see if I could start the game again from 0, but every time I opened the game again and the file just kept magically appearing again, now I have a game that the only thing I can do it´s stare to a chair...

![CHAIR](https://user-images.githubusercontent.com/71671316/99135195-c7d0fc80-25e6-11eb-96cf-65428fa42326.png)

I posted this issue a while back, but I think it was on the wrong branch I still dont know if this is the correct branch for this kind of issues, please help :,)

**Comment by ThePotatoGuy** [comment]
See this entry on the [wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Mundo011** [comment]
Thanks for the help
