### ISSUE TITLE
[Suggestion] Minor: Visual for Sleeping Monika

### ISSUE THREAD

**Issue by XTHHedgehog** [Monika-After-Story/MonikaModDev#6691]
I think it would be more realistic if Monika's face dropped to a resting position when she goes into deep sleep. Humans can't really keep a smiling face when they've gone into a good sleep, at least as far as I know. It would just be a cool extra touch of realism to her.

**Comment by Ix-30** [comment]
Agreed. While in anime, mos picture her with a sleeping happy.  Most people think something like(sorry for the quality of the images, yet they're the closest to the mental image I want to establish):
![image](https://user-images.githubusercontent.com/71111669/99159870-6f613400-26a6-11eb-9c4e-32c25ec59fd6.png)


To make a better expression I'd say something like:
![image](https://user-images.githubusercontent.com/71111669/99159846-2dd08900-26a6-11eb-81e5-c0ed48ad2d72.png)

Maybe even a silly face? As when we humans sleep, not smiling, vulnerable, and weird faces can come about. 1000% back up this idea.

**Comment by XTHHedgehog** [comment]
Yeah. Plus, Monika's Lullaby doesn't always seem to play for me, so it
would be useful to have another indicator
XTHHedgehog

**Comment by EllieWLMS** [comment]
um... while reading this I just had a weird idea... maybe Monika could have dreams! what does it have to do with the facial expression, maybe her expression could change depending on the dream, maybe she's having a weird dream where the player is talking to other girls and she has an angry face, or maybe she's having a dream where she finally kisses the player and she has a weird face! or she could have a dream about crossing to our reality and she could have a happy face idk....

**Comment by XTHHedgehog** [comment]
That would genuinely be really cool! You could move her sprite to the lower
left odd three screen, have a thought bubble depicting a couple simple
pictures depicting what she's dreaming about.

XTHHedgehog

**Comment by eyelesssally** [comment]
As I mentioned in an issue before, I've got some sprites that could be used but no code ouo'
![sleepytimetest](https://user-images.githubusercontent.com/56178333/99202299-92f6ae00-277c-11eb-8c24-3cf004c1083d.png)

**Comment by ThePotatoGuy** [comment]
`hsc` or `dsc` might work for a "resting" sleeping expression.

[closing until we look into it]
