### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6702]
What does ~ze mean?

![screenshot0001](https://user-images.githubusercontent.com/71310908/99458667-2f5fb280-292d-11eb-9661-8c90478269bd.png)

**Comment by 20RaVen23** [comment]
I investigated a bit about the character Moni is cosplaying (Marisa Kirisame), and got this;
"She speaks in an informal manner and typically uses the sentence ending particle ze (ぜ). "Ze" used at the end of verb stems delivers a "boyish" and "impolite" sound to the listener/reader. Ze is mostly used in a context to express one's will to act (similar to "let's" in English), and using it in other cases sound somewhat unnatural, perhaps "phony" or "showy"."
