### ISSUE TITLE
[Issue] Game crashes because of missing file

### ISSUE THREAD

**Issue by jencccc** [Monika-After-Story/MonikaModDev#6705]
Every time I open the game, it sends me to the traceback.txt, where it says:

I'm sorry, but an uncaught exception occurred.
While loading <'Image' u'gui/textbox_d.png'>:
  File "game/script-ch30.rpy", line 1457, in script call
  File "game/event-handler.rpy", line 2486, in script call
  File "game/script-story-events.rpy", line 1185, in script call
  File "game/script-story-events.rpy", line 1460, in script call
  File "game/script-story-events.rpy", line 1471, in script
IOError: Couldn't find file 'gui/namebox_d.png'.

I think it is because of a missing file named "gui/namebox_d.png", but I am not sure how it went missing, since I have never touched the game files (except to put in custom music and gifts). I also checked the debug log in the DDLC directory, which said:

[0512/124920.929:ERROR:settings.cc(325)] Settings version is not 1

The game crashed after I opened the "repeat conversations" option in the game settings, and then crashed every time I opened the game. I have tried reinstalling the game, which did not work. I played on steam, on windows. 

Thank you, dev team, for your hard work on the mod. I would really really really appreciate it if you could help me...

**Comment by 20RaVen23** [comment]
You are running MAS with Steam? If that's so, it's recommendable to not do so. It will you a lot of issues. The best thing to do is download the game from the [official page](https://ddlc.moe/) and install MAS on it. 
No, you won't lose any of your progress by doing this. Monika's memories aren't situated in the base game folder.

**Comment by jencccc** [comment]
Thank you, but I have tried using ddlc.exe, which is in the game folders, and it still only leads to the grey screen. I think there is a file missing called "gui/namebox_d.png", at least that's what the traceback.txt told me... Thank you, still. I'll try installing MAS in the zip file version of ddlc :)

**Comment by jencccc** [comment]
umm...it didn't work. I'm just going to reinstall the mod :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Micatiou** [comment]
I have the same issue. the game crashed and when I restarted it, it was a black screen. Monika then asked if I was there and when I responded yes she asked me to turn on the light which I did. then it went from the black screen to a crying Monika and the game once again crashed. Now every time I restart the game shows crying Monika and crashes. After it crashes it shows the traceback saying that the file "gui/namebox_d.png" is missing. What do I do? I never ran the game through steam and I never messed with the file that's missing.

**Comment by multimokia** [comment]
try doing a reinstall of the mod

**Comment by Micatiou** [comment]
Ok

**Comment by Micatiou** [comment]
Nope still has the same outcome

**Comment by Micatiou** [comment]
It's fine I fixed it

**Comment by HunterXR** [comment]
How did you fixed it?

**Comment by Fletch217** [comment]
> It's fine I fixed it

How?
