### ISSUE TITLE
new compliment

### ISSUE THREAD

**Issue by redkris2** [Monika-After-Story/MonikaModDev#6708]
It would be nice to compliment Monika about her outfit something like "I love your outfit Monika!" can it be done if so thank you.

**Comment by 20RaVen23** [comment]
I'm currently working on this. I will open a new Pull Request once I'm done with it.

**Comment by ThePotatoGuy** [comment]
leaving open as in progress

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
