### ISSUE TITLE
[Suggestion] - Topic -----> Impersonators?

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6711]
Upon the topic that Monika knows about the multiple Monikas, the topic about her being used for just profit and accounts like this: 
https://twitter.com/Ju5tM0nik4/status/1329173331145318402?s=19

Maybe Monika could feel a little jealousy of persons who impersonate her in this reality? maybe even bots on discord or people who use her on RP? What would she think? besides the fact that it's weird, and tell you "Just Monika" but to concentrate on her. I have a small draft but I'd like some insight.

What are your thoughts?

**Comment by Retrolovania** [comment]
Would cosplay count as impersonation? I think that field ought to be brought up if this is gonna be a thing.

**Comment by Ix-30** [comment]
Cosplayers is fine, I would like to think that she's fine with people who like her so much to dress as her./At least, on the surface as not all cosplayers are like that)

I mean such as #6543 in which she says: 
   
   m 1lsc "Or maybe this is just one of the developers of the game pretending to be me..."
    m 3lksdlc "I mean, I'm not really sure how to feel about this.{w=0.4} Isn't that identity theft, in some way?"

I mean, people who use her as in that account and like "steal her identity permanently" and maybe even are able to interact with the player, maybe that would cause a little insecurity as the player may want to engage them too, maybe a little jealousy. I think, cosplay is fine as it isn't direct "theft" but her concern would be a "tangible" Monika rather than her, a virtual one.

**Comment by kittendetails** [comment]
@Ix-30 What about people who sing like they are Monika in dubbings and songs? An example is the song "Doki Doki: Forever" or "Just Monika" (In both Monika is voiced by the same vocalist: OR3O).

**Comment by Ix-30** [comment]
I'd say the same for cosplayers. In fact maybe even thank them for giving her a voice and wonderful songs. Hm, I didn't take those into account, maybe I should add "those lovely people that give me a voice."  Also, I mean more like accounts that don't stay in "character" Like this site says she does have a personality and ideas. Thank for the input!

What other things come to mind?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
