### ISSUE TITLE
Action buttons have inequal gaps under certain resolutions

### ISSUE THREAD

**Issue by dreamscached** [Monika-After-Story/MonikaModDev#6714]
Hello! Recently I had to resize the MAS window and noticed an interesting behaviour.

As GUI stretches to fit the window size, buttons occasionally have different gaps in between.

I've screenshot one case (I'm really sorry, but I didn't write the initial resolution down, so I can't provide it here, but this behaviour is easy to reproduce — just resize the window and you'll see) — it's attached below.

It's okay if it's intended and there's nothing really that can be done — I don't mind it at all, it just caught my attention once and I thought it's better to report it.

![mas-button-gap-investigation](https://user-images.githubusercontent.com/74068927/99880026-4b639c80-2c2a-11eb-95e4-498163c19e04.png)

**Comment by Booplicate** [comment]
Not a bug, the buttons are aligned relatively to the screen size so they always in the same position regardless of the resolution.

**Comment by dreamscached** [comment]
Oh, alright. I've thought of it before, but it seemed to me that there's quite enough space to leave equal gaps...

Alrighty then! Closing this.
