### ISSUE TITLE
(Idea) A Sun in the sky 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6716]
Can you add a sun in MAS?

**Comment by multimokia** [comment]
Can you *please* not make more than one issue per suggestion?

We don't always respond, but we do see it. You're just cluttering up the issues list and duplicating your own issues

**Comment by Ant9cp** [comment]
Sorry about that, but someone could if told me before you know

**Comment by multimokia** [comment]
We've actually done so: #6534

**Comment by Ant9cp** [comment]
No not about making duplicates, about not replying to a issue

**Comment by multimokia** [comment]
Replying to issues is fine. You're making multiple issues for the same suggestion. Stay on the original issue and just leave it open. It has the same content you're bringing up

**Comment by Ant9cp** [comment]
Ok👍
