### ISSUE TITLE
how to take monika out

### ISSUE THREAD

**Issue by susy-art** [Monika-After-Story/MonikaModDev#6720]
I can't find the take monika out option anywhere, is it unlocked? How long/how much affection does it take? I got in today and already love her so much

**Comment by kittendetails** [comment]
Spend time with her and she will get into that topic. For me, on the second day, she already gave me instructions on how to take her out. You need to be patient, she will tell you when this option is unlocked.

**Comment by ThePotatoGuy** [comment]
i believe she introduces it in a topic, but I don't remember exactly. If you still don't have it, make a new issue.

[closing as resolved]
