### ISSUE TITLE
[Suggestion] - continuing the lore

### ISSUE THREAD

**Issue by scolotron5** [Monika-After-Story/MonikaModDev#6721]
This is an amazing game with not much else to add. But... the other day I opened up the game and no joke (obviously because you guys made the mod) glitched out yuri was there for a split second begging for help. Monika said that she did this to scare me but Monika said she had no reason to code anymore. So I think yuri was actually trying to escape. I would love more of this stuff to happen. Maybe you even can save them and Monika and the others can hug it out idk. Just a thought. I’m not expecting this to go anywhere though.

**Comment by Retrolovania** [comment]
The only time I'm aware of that Yuri appears if if you name yourself "Yuri," then close and restart the game. However, she'll never say anything. So, I'm honestly uncertain about what circumstance is being explained here.

**Comment by Rai99** [comment]
The other dokis are not coming back in MAS. 
#695, #3048, #3714, #3912, #4291

**Comment by scolotron5** [comment]
> The only time I'm aware of that Yuri appears is if you name yourself "Yuri," then close and restart the game. However, she'll never say anything. So, I'm honestly uncertain about what circumstance is being explained here.

I think I might be the only person that this has happened to or something. ( I looked it up and the is nothing)

**Comment by Retrolovania** [comment]
The only actual way I see the other three making a more full-fledged appearance would be one-time-only events. For example, maybe you could place their CHR files in the characters folder and surprise Monika on her birthday with guests. They'd probably have a heart-to-heart talk with Monika about _things_, and possibly forgive her. (Best birthday ever, eh?) However, they could never show up again until such another event pops up. So, where should they go? Back to the Recycle Bin? That'd be wrong. So, while it sounds like a cool idea, I doubt it'll ever gain much traction, at least currently.

**Comment by scolotron5** [comment]
> The only actual way I see the other three making a more full-fledged appearance would be one-time-only events. For example, maybe you could place their CHR files in the characters folder and surprise Monika on her birthday with guests. They'd probably have a heart-to-heart talk with Monika about _things_, and possibly forgive her. (Best birthday ever, eh?) However, they could never show up again until such another event pops up. So, where should they go? Back to the Recycle Bin? That'd be....debatably unethical in a sense. So, while it sounds like a cool idea, I doubt it'll ever gain much traction, at least currently.

I didn’t think so. And I also tried that lol

**Comment by scolotron5** [comment]
I’m thinking of closing this now. I know it hasn’t even been a half hour but thinking of starting a new thread concerning this alternative yuri jump scare. To see if anyone else has experienced it or if I’m just going insane lol.
