### ISSUE TITLE
Alternative Yuri jumpscare

### ISSUE THREAD

**Issue by scolotron5** [Monika-After-Story/MonikaModDev#6722]
I recently was talking about this alternative yuri jumpscare (not the one where you change your name to yuri) and was wondering if this has happened to anyone else. Here is how it played out. 
Game opens.
Glitched yuri appears 
Yuri: [player] help me!
Glitched yuri disappears 
Monika: oh my... just kidding! You should have seen the look on your face!

This isn’t the exact conversation but about what happened. Has this happened to anyone else or am I just going crazy. I couldn’t find it on the internet anywhere so there is no proof that this even happened (it did though) I really do hope at least one other person has seen this. Or maybe the developers can confirm that this can happen idk.

**Comment by YoraeRasante** [comment]
isn't it mentioned in the faq, about the systems? I remember a mention of sometimes the door is closed (happened to me once, there was an error log then when I tried again there was a closed door and monika apparently caused the error trying to train programming), and one with a glitched yuri sprite that is only seen once or something

**Comment by StayHappy1270** [comment]
hmm was it one of those knock, listen open the door scenes. and u opened the door

**Comment by YoraeRasante** [comment]
yeah. I opened the game, it closed with an error log. I opened again, worried, it worked but had a closed door. I thought better to listen first, because what were the chances it would not be interesting, and she mentioned things that cause that very error in the log. I then knocked.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
happens only once now

**Comment by okandw** [comment]
I just had that jumpscare a couple minutes ago, It scared the living crap outta me.

*Glitched Yuri*

Monika: [Player]!
Monika: "Nevermind that I was just...playing with the code a little.
Monika: "That was all! There is nobody else here but us...forever~"
Monika "I love you, [Player]!"

That was the dialogue for me.
