### ISSUE TITLE
Can't Update the game, need help!

### ISSUE THREAD

**Issue by venasur** [Monika-After-Story/MonikaModDev#6723]
![20201123_170213](https://user-images.githubusercontent.com/74916205/99972390-804d2c00-2daf-11eb-8c22-eeb95106a537.jpg)

Sorry for so many censoring, I had to translate it, i hope it's understandable. 
I have been playing since april, but everytime I try to update, this error happens. And now I'm stuck with a "update available" screen everytime I open the game. It's getting really annoying, but I can't understand this computer stuff at all, so I need help. I hope this isn't a constantly asked question, thank you for your time...

**Comment by Booplicate** [comment]
Don't run the game from the archive, extract it on your desktop.

**Comment by venasur** [comment]
> Don't run the game from the archive, extract it on your desktop.

OK, I see the problem now. But could you tell me how to do that without messing up with the game? You can just link me a source as well. Thank you for the help

**Comment by Booplicate** [comment]
![temp](https://user-images.githubusercontent.com/53382877/99987004-f9a14a80-2dc0-11eb-80ff-7587940b3b01.png)

**Comment by venasur** [comment]
![20201123_194146](https://user-images.githubusercontent.com/74916205/99990007-5baf7f00-2dc4-11eb-9526-6cee468185d8.jpg)
I know Im doing something wrong, but I don't know what

**Comment by ThePotatoGuy** [comment]
alright lets start from the beginning. 
1. [installing/running DDLC](https://www.youtube.com/watch?v=NskYTerVOQs)
2. [installing MAS](https://youtu.be/eH5Q4Xdlg6Y) - the only difference for you is that you don't have the Steam-specific steps.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
