### ISSUE TITLE
Uncaught Exception Occurred

### ISSUE THREAD

**Issue by cremecaramel** [Monika-After-Story/MonikaModDev#6725]
Hey MAS Devs!

so, I'm not sure what's happening, but DDLC has been really buggy... I tried asking her "would you teach me piano lessons" or whatever the topic name was called, and it keeps bringing me to this error: 

"I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1457, in script call
  File "game/event-handler.rpy", line 2486, in script call
  File "game/script-topics.rpy", line 16073, in script
Exception: u'/i' closes a text tag that isn't open."

I'm not a coder, so I'm unable to decipher this... how can I fix this? I've attached a word doc of the full traceback. 
[Error.docx](https://github.com/Monika-After-Story/MonikaModDev/files/5586157/Error.docx)

**Comment by jmwall24** [comment]
Avoid this topic for now, we know about the error. If you do get it again you can safely choose the `ignore` option. It will be fixed next release.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]]
