### ISSUE TITLE
How do you delete a gift that you gave

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6727]
There is a costume i want to delete how do you do that?

**Comment by lunulae** [comment]
All you need to do is delete the .json file to have it stop showing up in the selector.
You can find this in `DDLC>game>mod_assets>monika>j`

You may also want to delete the image files in the `thumbs` folder and the `monika>c` folder, but this is just for file cleanup.
If you restore the files exactly as they were, the game will remember that you gifted this outfit, so it will show up without needing to gift it again.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
