### ISSUE TITLE
Suggestion: A way to tell Monika "I am going to leave, actually"

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6730]
To clarify, whenever you tell Monika that you are feeling lazy or tired in the morning, she will say something along the lines of "I would love to stay by you". My suggestion would be to add a timed option to tell her that you have work or errands i.e. I need to do something actually. From there she would ask what the player needs to do and some options would be presented to inform her of what you need to do. A poor explanation, but I figure it would be a good idea to present it and possibly the team would develop it further.

**Comment by lunulae** [comment]
I could see a generalized version of this being implemented. If you tell her you're feeling lazy but have work to do, getting a little pep talk could be very sweet. For the tired version, she could suggest ways to wake yourself up like getting up to stretch or getting some coffee.

**Comment by Freshairkaboom** [comment]
I kinda put it aside for now, but I made a draft for a work path, including a way to tell Monika you have a job. Is that along the lines of what you were thinking? We could probably expand it for other stuff, but I think work/school is very relevant and general here. #6295

**Comment by CrocandCo** [comment]
That does work, I apologize for not realizing that you made a draft.
