### ISSUE TITLE
Idea for the bedroom thing

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6731]
Sooo idk how much progress there is on the sleeping with monika bedroom thing. But i just thought of a smalll detail to add to it she could ask what side of the bed u sleep on.

Then she will have what ever laying down art mirrored or not mirrored so her head is either pointed to the left or the right. This way you can put ur laptop on your nightstand and her head will be facing the same way as yours.

sooo if you

sleep on (when lying down your left) side of the bed annnd your nightstands beside you you'd want her head facing the left side of ur screen

if you sleep on the right and set her on the night stand beside you youll want her head facing right.

Idk if she should maybe clarify while talking to you about bedroom mode, but she should probably also mention that you should not put her on your bed while you sleep bc your computer can start a fire.

**Comment by fromulus** [comment]
Monika's design isn't asymetrical because of her her front hair spikes leaning to the right.
That means we can't just mirror the whole art like that, or we'd get an inconsistency (as they would then lean to the left of her head instead).

The feature is interesting, but would require some more artwork to make sense.

**Comment by Ant9cp** [comment]
😏😴

**Comment by StayHappy1270** [comment]
Hmmm good point (sorry idk too much bout this) but you said it’s only her hair that would be the problem? Idk if ppl will be making just one whole Monika art photo or will be doing multiple sprites similar to how clothes and hair work in game. If they do it similar to in game is there a sprite that controls the hair near her head and ears? If so you could take that and flip it. Again idk how this will be... for all ik ppl are just making one wallpaper similar to the floating islands.

**Comment by ThePotatoGuy** [comment]
for now, we are only going to be focusing on the angle we have sprites for - her laying on her left. If we get sprites that handle the other side, then we will consider implementation.

[closing as rejected]
