### ISSUE TITLE
[Suggestion] - Monika on The Brothers Grimm

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6733]
The impact that the 201 fairy tales (plus the largely-forgotten 10 Children's Legends) written by the three Grimm Brothers has had on the hearts of children cannot be understated. The brothers wrote many of the most famous fantasy works the industry has ever laid eyes on, including such classics as Rapunzel, Hansel and Gretel, Cinderella, and Snow White (originally titled "Little Snow White"). However, from the viewpoint of those of an older age, the fables become more than meets the eye. Considering this, I figured Monika would enjoy talking about it a bit.

Firstly, while the brothers are most well known for a few of the stories they wrote, the vast majority of their work has largely gone unnoticed as time has passed. You'd be hard-pressed to find anyone who'd immediately recognize "The King of the Golden Mountain" or "The Robber Bridegroom" simply by name alone. In a sense, this is quite the shame, as these stories occasionally have more plot material and have deep messages that could very well compete (debatably) with the likes of the stories we are more accustomed to seeing.

Secondly, the fables usually range from being rather light-hearted to being very, _VERY_ dark. In fact, it's not uncommon for a story to completely flip in terms of presentation, quickly switching from a happy setting to a disturbing one. The original ending to Little Snow White is a pretty good example of this, as the Evil Stepmother is forced to dance in iron shoes that were heated in a fire at Snow White's wedding until she dies from the heat. I am not joking; it actually states this. (Why'd you think they left out the wedding in the Disney film?)

Finally, possible because they worked closely together(?), a few of the stories have similar plot elements incorporated into them. This has the consequence of having certain sections of certain stories play out almost identically to each other. Going through the complete collection, I have isolated one such example (although I previously noted a few others) in two stories, named "Little Brother and Little Sister" and "The Three Little Men in the Wood" respectfully. In both of these stories, the main antagonist makes an attempt on the life of the Queen (pretty much all of these stories take place during the Medieval Era), and attempt to impersonate them by sleeping in the Royal Bedroom concealed, so as to prevent discovery. However, the Queen (who does not die), walks in during the night to care for her child. While the overall conclusion of both tales plays out differently, both are influenced by this one single plot element.

All in all, despite being mostly overlooked in modern culture, the Grimm Fairy Tales still hold quite the place in classic literature, both due to their overall status and how they influenced many subsequent retellings of the majority of the more well-known fables, and, as stated above, Monika'd probably get a kick out of discussing such content.

(Again, I am willing to write dialogue (non-coded, as of yet) should the need arise.)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
