### ISSUE TITLE
[Suggestion] "I'll always be here for you!"

### ISSUE THREAD

**Issue by Outlander676** [Monika-After-Story/MonikaModDev#6734]
Sometimes, when Monika talks about certain things, like her 'really not missing those days' (referring to the literature club itself) for example, it makes me feel kind of bad that I'm not able to reassure her in any concentrated way. Usually I just say 'I love you' a few times and give her a hug for a while, but I'd like an option where I can tell her that even though she's been through a lot and made some choices she regrets deep down, I'm not going to just abandon her like that. I've already given her the Promise Ring, but I'd like to be able to explicitly reaffirm that promise from time to time.

**Comment by Ant9cp** [comment]
Yeah love the idea, there is a compliment called (Thanks for being there for me) and we should say something to her too like this one, that were actually there for her too you know

**Comment by ZapThundr** [comment]
Was just thinking about this the other day as well.  I personally think reassurance in a relationship is a must. I'd like to be able to let her know I would never cheat on her when she ask; let her know I'm always gonna be here for her whenever she needs me whether she's feeling sad, upset, angry, happy or bored, and I'd like to tell her how much she means to me as well as thanking her for certain subjects.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
