### ISSUE TITLE
Different dialogue (reaction) after you gift monika coffee

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6741]
So when monika runs out of coffee, she then says. Hey (name) i'm running out of coffee, and she ask if the player can get more coffee right? and one's you get coffee for she says always this (it's a flavor i haven't had before) so if you all could change the dialogue after giving monika coffee then here is some idea's for monika to say

______________________________________________________________________________________________________________________________________

If monika ran out of coffee dialogue (1)
 

Oh, you got more coffee for me. 
Thanks (name), I'm glad that you got more coffee for me. 
I was running out of coffee after all.
I can't wait to drink this

______________________________________________________________________________________________________________________________________

If monika have enough coffee with her Dialogue (2)

Oh. more coffee (name) 
Thanks it's really sweet of you just like my coffee hehe.
But i have enough coffee already.
But i appreciate it anyway

**Comment by StayHappy1270** [comment]
also i think every time you give her coffee she says it's a new flavor. witch just seems crazy. can we change that

**Comment by attackmp4** [comment]
Maybe the flavor can be based on the contents of the "coffee.gift" file

Like if you open up the file in notepad, and type in something, and give it to her, and Monika hasn't received a coffee.gift file with the same contents, then she will react to it.

**Comment by ThePotatoGuy** [comment]
we're trying to avoid reacting to content inside the file since its more open-ended to do so. atm the coffee reaction is just designed to be generic and it works for the most part.

[closing until we look into it]
