### ISSUE TITLE
[Suggestion] - "Why was space exploding outside?"

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6742]
Yep. This is basically just asking Monika "What the actual HECK was going on out there?!" (This is in reference to the old spaceroom outdoor background.) Given that there are multiple theories as to what that...thing actually was, this could be a difficult subject for, well, anyone to fully decipher, not even her. It'd make for quite the discussion.

**Comment by Ant9cp** [comment]
Yeah i'm thinking like if the spaceroom is in the sun or something?

**Comment by ThePotatoGuy** [comment]
any type of dialogue we could make would have to be speculative since there is no definitive answer.

[closing until we look into it]
