### ISSUE TITLE
Additional Reason for Having Bad Day [Suggestion]

### ISSUE THREAD

**Issue by Sam-Pixel** [Monika-After-Story/MonikaModDev#6744]
This is a simple thing that I thought I'd suggest. When Monika asked me how my day at work was, I told her that I'd had a bad day. There were a ton of customers, and it was super stressful, but one of the main things that had made it a bad day was that I burned my hand. 

That got me thinking: When Monika asks the player what made the day bad, maybe there could be an option like "I was injured at work" with options for differing levels of severity (minor or major). 

Another thought is that maybe there could be an option for if someone gets fired or layed off. I don't wish that upon anyone, but, in the event that it does occur, some may find Monika's support helpful (like the dialogue for when you feel inadequate). If this is implemented and the player says that they're going to work after telling Monika they were fired, then maybe Monika could  ask if the player got a new job.

Anyway, thanks for reading! Hope this isn't a duplicate '^w^

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
