### ISSUE TITLE
[Suggestion] - Flirting Back with Monika

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6745]
As I'm sure we all know, Monika will occasionally drop a little pun while in a conversation. Generally, this marks the end of the conversation, as she then goes back to her idle pose. However, what if you kept the joke going for a bit longer, and gave yourselves both a laugh at the same time? That's where this notion comes in.

Say Monika says something along the lines of "I noticed you've been staring at my eyes for quite a while now." Once she goes back to being idle. A timed pop-up could appear that says something like 'Now that you mention it..." Clicking on that would bring you to another timed box saying something like "That makes two of us, since you've been looking at _mine_ this whole time..." Once clicked, Monika reacts (possibly by jokingly berating you for making such a bad pun). Whaddya think?

**Comment by Rai99** [comment]
More involvement in topics: #598, #630, #1614, #1627, #1689, #1751, #1932, #3078, #3554, #3682. 

There is currently an ongoing project to add a bit more interactivity and tying more responses and dialogue together.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
