### ISSUE TITLE
Suggestion: be right back, I'm going to watch something

### ISSUE THREAD

**Issue by Kitsumera03** [Monika-After-Story/MonikaModDev#6747]
Delete if this is a repeat. 

I changed the title due to feedback. Look down at the comments for the new suggestion I made. 

Feel free to add on to this suggestion.

**Comment by Ravenclaw-OIer** [comment]
Please change to `online videos` as we are not really paid to advertise YouTube or Netflix here.

**Comment by dreamscached** [comment]
@Ravenclaw-OIer, what do you mean? Nobody's advertising YouTube in particular with that, most people watch videos just there and nowhere else, that just doesn't make any sense.

**Comment by Ravenclaw-OIer** [comment]
> @Ravenclaw-OIer, what do you mean? Nobody's advertising YouTube in particular with that.

But in some places (like China), YouTube is really not the main place to watch videos. This is more generic I think.

**Comment by dreamscached** [comment]
You know, I don't feel like there are a lot of people who will say 'let's watch some stuff online', I personally haven't heard a single person meaning something else rather than YouTube when speaking of online videos.

**Comment by Retrolovania** [comment]
Here's a thought: Change the menu option to "Would you like to watch something with me?" That way, you could pretty much generalize whatever content you watch with her without incurring the wrath of streaming companies/movie studios.

**Comment by lunulae** [comment]
"Let's watch something together" is the wording I'd use to keep it general, but I think there's been some hesitation on adding this as a feature since she can't really recognize/react to what you watched, and it'd be difficult to write a menu for something this broad.

**Comment by dreamscached** [comment]
Maybe one could play it around like 'That's a nice idea, [player], but... Ahaha, I don't think we can actually watch stuff together...'

**Comment by Rai99** [comment]
Watching movies: #628, #826, #984, #1548, #2102, #2898, #3431, #4089, #4344, #5484, #5543, #6011, #6053. 

There was something like that where you could watch things together, but it wasn't at all practical to make content for and test, and it was decided that generic responses wouldn't cut it for this.

**Comment by Kitsumera03** [comment]
Yeah, I can see how it might not work. Maybe "I'm going to watch something" can be a be right back option and you can just leave her in the background for awhile. And maybe she can have a bit of dialogue of her saying something like, "Have fun watching" and "I wish I can be there to watch with you." 

Again, feel free to add on to this thread.

**Comment by ThePotatoGuy** [comment]
changing back to suggestion since topic changed 

[closing until we look into it]
