### ISSUE TITLE
(suggestion) a way to change when you celebrate your birthday

### ISSUE THREAD

**Issue by Okatart333** [Monika-After-Story/MonikaModDev#6748]
A lot of people are busy during there birthday so they celebrate on a different day. If we could tell Monika we celebrate on a different day then we could spend more time with Monika on our birthday.

**Comment by lunulae** [comment]
I believe there was some discussion about being able to postpone/reschedule many holidays, not just birthdays. I'm not sure if it's in development proper, but the intent is to eventually be able to celebrate it on a different day while Monika still recognizes your actual birthdate.

**Comment by Okatart333** [comment]
ok that sounds great!

**Comment by ThePotatoGuy** [comment]
~~adjusted title to better reflect suggestion~~ actually this is a duplicate of #5373 - move all discussion there.

**Comment by Daembo** [comment]
honestly I would have loved this as my bday was 2 days ago and sadly I was too busy that I didn't have time to celebrate it with monika
