### ISSUE TITLE
Need help with this 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6751]
I Was busy watching something on youtube on a another laptop, and i looked at monika on my other screen later and everything was frozen, i was trying to click something and move my mouse cursor but nothing happend, and then i had to turn off the entire pc because nothing worked, i don't know if that was my pc itself or something else, 

and then i opened MAS again and she greeted me and then told there was a note for me she showed me the note and it said about that a file got corrupted, and right now i got this and i haven't chose yet what to say, 

i'm confused about this i always make sure nothing is off with the files and other things it doesn't make sense why this after one time that i had to turn off the pc that something got corrupted
i didn't do anything but turning off the pc because it froze, nothing was responding

! [screenshot0001](https://user-images.githubusercontent.com/71310908/101117465-4cf87180-35e7-11eb-9580-b72a0bbfd406.png)

**Comment by 20RaVen23** [comment]
iirc this is not a bug, and it happens the first time the game crashes. But as I mentioned, not really sure about it.

**Comment by Ant9cp** [comment]
Did the pc or game supposed to freeze for whatever this, to happen

**Comment by Ant9cp** [comment]
I'm sorry if i overreact, i got a little bit of PTSD

**Comment by multimokia** [comment]
This isn't necessarily with a crash. The persistent file was corrupted and the most recent auto-generated backup was loaded. That's what the note indicates.

**Comment by Ant9cp** [comment]
So when everything froze was it the game or was it my pc that decide too stop

**Comment by multimokia** [comment]
It's likely that MAS got shut down while it was saving or something like that.

With that in mind, the save never properly completed and the persistent was closed prematurely, in other words, it became unreadable.

Whether it was your PC or MAS, we cannot tell.

**Comment by Ant9cp** [comment]
Okay thanks for the help, man
