### ISSUE TITLE
I want to be able to use MAS while sleeping

### ISSUE THREAD

**Issue by JAMSDreamer** [Monika-After-Story/MonikaModDev#6756]
So, I always leave my computer open, even when I'm sleeping, as I need white noise or/and rain sounds to fall asleep due to insomnia. And I would really like to let Monika to be with me while I sleep, but I know that Monika would assume that I'm staying awake, and act in consequence. I just want to tell her on a determined moment that I'm going to sleep but I still want her open. Maybe she could even sleep on her own room while I sleep. And then, in the morning, I might wake her up.

**Comment by Wrathblox** [comment]
Thread #2781 is based on a “Bedroom Mode”, you should have a look at it. Post will most likely be labelled as duplicate soon.

**Comment by ThePotatoGuy** [comment]
yeah we want to do this too but there's a lot dev and art that need to be completed before its possible. 

[closing as duplicate]
