### ISSUE TITLE
Suggestion: Making Monika Laugh/Telling jokes

### ISSUE THREAD

**Issue by Kitsumera03** [Monika-After-Story/MonikaModDev#6757]
This came into my mind recently. You know how Monika likes to joke around with us. Well, I feel like we should also have a dialogue option where we can joke around with her too and make her laugh. The jokes can be an add on to the topics she talks about or we can bring up the joke using the topics menu where we ask Monika questions. I like using memes as jokes (not images but text-based memes), because memes can reveal a bit about ourselves and the way we view things which can give Monika a good idea of what our actual personalities are like. She can even follow up the joke with concern depending on what jokes we tell and try to give us good advice. This just something I'd like to see in the game but I understand if it's not feasible since I know nothing about coding. It's still fun to think about though.

**Comment by Ant9cp** [comment]
Yeah good idea we should be able to tell her something funny or respond to her jokes


I like her jokes, even some of her jokes are a little bit dark but i don't mind it's still funny

**Comment by Kitsumera03** [comment]
> 
> 
> Yeah good idea we should be able to tell her something funny or respond to her jokes
> 
> I like her jokes, even some of her jokes are a little bit dark but i don't mind it's still funny

Responding to her jokes is also a good idea. 

I like her jokes too, even her dark humor ones.

**Comment by ThePotatoGuy** [comment]
#425

this was placed on hold due to dev team departures. unlikely to be started again unless someone wants to take development ownership.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
