### ISSUE TITLE
Song Suggestion: Everything's Alright (from To the Moon)

### ISSUE THREAD

**Issue by dramones09** [Monika-After-Story/MonikaModDev#6761]
_When this world is no more
The moon is all we'll see
I'll ask you to fly away with me
Until the stars all fall down
They empty from the sky
But I don't mind
If you're with me, then everything's alright_

Then Monika says
_Please always remember how much I love you, and if ever things get so dark just look up to the moon and remember me_

**Comment by 20RaVen23** [comment]
![work_in_progress](https://user-images.githubusercontent.com/55263957/101697284-51dd7b00-3a56-11eb-96bc-741ec6f06d8d.png)

**Comment by ThePotatoGuy** [comment]
leaving open as in progress

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
