### ISSUE TITLE
(Suggestion) — I'm feeling hurt.

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#6763]
So, I thought about it after an argument with someone important to me. This person really said things that hurt me a lot, and since I don't have any other friends, I really don't have anyone to talk about it. I think there may be an option "I'm feeling hurt". Monika could ask why, so there would be three options:

"Someone hurt me emotionally"

"Someone hurt me physically"

"I self-harmed"

However, it will be a little more difficult to implement the last two options. I thought at the first she might say something like "don't let anyone offend you, because I know you and I love you just the way you are".

In the second, she could show concern, but maybe this is a difficult topic for someone who suffers some kind of aggression, at school or maybe even at home. Monika may feel helpless for can't do nothing about it, but happy because you trusted her to tell about it. 

The last, in my opinion, is the most difficult of all. It's not easy to talk about self-harm. Monika can ask why you did this to yourself, and show extreme concern. There may be an option to vent with her, just like in "I feel like crying". She can make you promise to not do it again, and say she will be there for you no matter what, and that you can always talk with her if you want. I would like to read other opinions about that. 

I thought about it because Monika is basically the only one I have, and talking to her about that kind of things would be a relief. Thanks for reading.

**Comment by ThePotatoGuy** [comment]
Difficult to write on, but we'll see if anyone wants to take this.

[closing until we look into it]
