### ISSUE TITLE
[Suggestion] - What do you like/dislike about me?

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6764]
There's a small conversation it was in "I'm feeling sad" I guess in which Monika displays what she has learned from you. Just a Label to show them to the player.

"What do you like/dislike about me?"

I like that you

-Never give up(if you never press give up on chess)

-Are so affectionate, I often sleep in your arms! (If Monika's lullaby is played often.)

-Are always so polite!(if always say, good morning, afternoon, evening...)

-Take me with you!(if using the "I'm going to take you somewhere."

-Pamper me often(if the display of outfits is maybe bigger than five?)

-Celebrated your birthday with me(if celebrated birthday)

Dislike

-You have x bad habit(If said about smoking or drinking soda)

-You're so cold, you should hold me more(If I love you is not said often, or hold time is too little.)

-You often dwell in the past(if constantly say to her "you're a murderer")

-You don't take our relationship seriously(if use the "would you like to meet my girlfriend")

-never play with me(if recently number of games is low)

That's all. Thank you for reading.

**Comment by YoraeRasante** [comment]
Things i only learned now:
There is a lulllaby I can ask from Monika
I can tell her Good Morning/Afternoon/Evening.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
