### ISSUE TITLE
[Suggestion] some song suggestions

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#6768]
I thought of some songs that I think would fit in with the other songs

On Melancholy Hill
Take On Me
Kokomo
I Wonder Why
Sh-Boom
and just about every single Beatles song

I'm not very sure how Take On Me would fit in, but the music video would definitely be a neat topic for Monika to bring up.

**Comment by Finnthefox24** [comment]
I just read the lyrics to Take On Me, and it'd actually fit.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
