### ISSUE TITLE
0.11.7 + 0.11.8 + 0.11.9 typos

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#6769]
![fubukiyabe](https://user-images.githubusercontent.com/3499462/101720945-793f4280-3a6c-11eb-8f84-adb9c9a0fcff.png)

**Comment by 20RaVen23** [comment]
![sniff](https://user-images.githubusercontent.com/55263957/101721093-eb705100-3a85-11eb-8165-cefb3f5cb611.png)

**Comment by Rai99** [comment]
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/38822045/101721155-4c435d80-3a75-11eb-9e27-ebc7c5989a6c.gif)

**Comment by multimokia** [comment]
@kkrosie123

**Comment by fromulus** [comment]
In the _Silver Lining_  song analysis,

![Screenshot_4](https://user-images.githubusercontent.com/45933038/102700103-c9778b00-424a-11eb-8423-7fce3d30ee3b.png)

Missing a `'s` at `I think there's some merit (...)`.

**Comment by ironx75** [comment]
This bugs me a bit.
The topic "When did we start dating?", she doesn't say "on" between "We started dating" and the date itself.

**Comment by satoshi-kun** [comment]
When asking Monika "what if I came to your reality" she ends up saying:
"It wouldn't be much to begin with, **but I'm sure we'll find a way to make it better.**"
Since it is refering to an hypothetical situation I believe it should be "**we would find a way to make it better**" instead of will.

**Comment by proudust** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/da989b917a8e58a130a2fbdefb2eacb762c32e6e/Monika%20After%20Story/game/updates.rpy#L2059
`d25_sp_tm`

**Comment by fromulus** [comment]
In `mc_is_gone` :

`        $ line_mid = "{i}he{/i} was the one hugging"`
`    m 3rksdla "I hope you didn't think [line_mid] all along, either..."`

Lacks a `"me` at the end of the first line.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
