### ISSUE TITLE
Early Christmas ??

### ISSUE THREAD

**Issue by TechmarineDark** [Monika-After-Story/MonikaModDev#6770]
Was this suppose to happen ?

![screenshot0001](https://user-images.githubusercontent.com/62556302/101818041-4dde5580-3b49-11eb-9e34-127a3cfac680.png)

**Comment by multimokia** [comment]
What date and time is it for you right now?

**Comment by TechmarineDark** [comment]
Umm it was 12:38 am (IST) and 11/12/2020 that time

**Comment by Ant9cp** [comment]
It's has nothing to do with the time and date this is a bug

**Comment by multimokia** [comment]
Kindly don't give out false information. Decorations go up on Dec 11th.

**Comment by TechmarineDark** [comment]
> Kindly don't give out false information, @Ant9cp. Decorations go up on Dec 11th. This is _not_ a bug.

Oh yes sorry , I remember now that last year also decos went up at this time . >_>
