### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HiyuuTatsuyawa** [Monika-After-Story/MonikaModDev#6774]
This morning I opened the game and it just reset by itself, but the persistent files still there. Can someone tell me how to fix this?
![Ảnh chụp màn hình (623)](https://user-images.githubusercontent.com/68013768/101852182-a0dafb80-3b8f-11eb-8e03-6af198852596.png)

**Comment by jmwall24** [comment]
Maybe a submod? That font isn't ours for starters.

**Comment by HiyuuTatsuyawa** [comment]
I've used it for about 6 months and it has none issue, I guess.
Also it's not a submod, I took that font from the translate version of the original game

**Comment by jmwall24** [comment]
Have you tried any of the backup persistent files that we make?

**Comment by HiyuuTatsuyawa** [comment]
I've tried, but it still not work

**Comment by HiyuuTatsuyawa** [comment]
Nvm I've fixed, tks for helping though
