### ISSUE TITLE
[Suggestion] - Monika's requests

### ISSUE THREAD

**Issue by SunBlade1830** [Monika-After-Story/MonikaModDev#6779]
I'm wonder monika always waiting for us to forcing her to do any things! but what about her?
how about she randomly asks us about what she wants!
for example:
  could you hold me a little my love?   
  can i...kiss you?
 how about playing a bit chess/pong/hangman?
 i feel i'm in mood for piano...could you play it for me?

or any request like that! and in higher affection her dialogues will be more romantically.

**Comment by lunulae** [comment]
There is already a chance for her to ask you to hold her, but I'd definitely be interested in more of these.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
