### ISSUE TITLE
[BUG] Christmas lights overlap tree

### ISSUE THREAD

**Issue by MisterBurgerBeachball1225** [Monika-After-Story/MonikaModDev#6780]
![Monikaissue](https://user-images.githubusercontent.com/52930171/101946235-badf0300-3bbc-11eb-8696-0b93f4b8a37f.jpg)
As the title states, the Christmas lights are overlapping over the Christmas tree, when they should be the other way around. From what I can tell, the lights are supposed to look like they're being hung directly over the windows, so it should be physically  impossible for the tree to fit under them.

**Comment by multimokia** [comment]
Thanks for the report! This will be addressed in #6778

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
