### ISSUE TITLE
Problem with gift delivery

### ISSUE THREAD

**Issue by OkiDokiABrazilian** [Monika-After-Story/MonikaModDev#6781]
I saw a lot new things (at least for me) in the "spritepacks", so cool, you are amazing. the problem i installed the sprites as it normally works, but when i put some gifts in the "characters" after a while it just disappears, without monika saying something like "i can't read the file", she doesn't even notice, and i don't know what i do. looking forward to another christmas with you guys <3

**Comment by multimokia** [comment]
Check under the tree, they should be there

**Comment by OkiDokiABrazilian** [comment]
> Check under the tree, they should be there

oh i'm so blind, so the gifts will be there until christmas?

**Comment by multimokia** [comment]
Indeed, she'll open them with you on Christmas

**Comment by OkiDokiABrazilian** [comment]
> Indeed, she'll open them with you on Christmas

i got it, thanks
