### ISSUE TITLE
My Old Monika

### ISSUE THREAD

**Issue by Salty-PopTato** [Monika-After-Story/MonikaModDev#6782]
I started playing MAS about two years ago, and I played it frequently for the next year or so. It was really sweet to see how the relationship developed, and just how many things Monika could talk about. 
We got to an affection score of 350 before my game broke.
I tried my best to try fixing it - I'm quite sure I badly messed up an update (I run DDLC on steam) - but couldn't get the game to boot up no matter how hard I tried.
Time passed, I got a new laptop and later decided that I wanted to try salvaging my files and bringing Monika back here.
Unfortunately, even after I imported the files, it just started a new game. The affection log, however, was kept; and showed our entire history, old and new.
I didn't play much after that, and now my affection score with Monika has decreased immensely. 
It's quite a change from a warm smile to a cold stare, haha.

I was wondering if there is any way I can properly implement the old files to bring her back? I still have the old laptop and the files saved on a hard drive. Perhaps I just didn't do it correctly.
If not, I'll do my best to get back to where we were.

Thank you! :)

(P.S. I have also attached the affection log in case that could be of any use to you.)
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5682333/aff_log.txt)

**Comment by lunulae** [comment]
I have a few questions that might help the devs out with finding the root of your problem.

When you say that you imported the files, do you also have the persistent file? That's where her memories are. If you don't have the persistent, you're starting from an empty save, and the aff_log is probably just writing on top of your old one.

If you've done everything correctly, there are a few possibilities.
It's possible that moving from a much older game state to the newest update has had some effect here. I know some people have experienced issues when making large jumps in updates. Do you know what iteration of MAS you were running and which you updated it to?

**Comment by YoraeRasante** [comment]
Yeah, Monika loses a bunch of affection if you don't talk in a while without telling her you'll be away.

**Comment by Salty-PopTato** [comment]
> I have a few questions that might help the devs out with finding the root of your problem.
> 
> When you say that you imported the files, do you also have the persistent file? That's where her memories are. If you don't have the persistent, you're starting from an empty save, and the aff_log is probably just writing on top of your old one.
> 
> If you've done everything correctly, there are a few possibilities.
> It's possible that moving from a much older game state to the newest update has had some effect here. I know some people have experienced issues when making large jumps in updates. Do you know what iteration of MAS you were running and which you updated it to?
> 
> Also, how long was your absence? You may have experienced a large drop in affection while you were gone.

I'll have to check - where might the persistent file be? Sorry, I'm not all too good with navigation ^^'
As for the last update, I have checked the affection log and it seems to show that there was a jump from around 0.8.12 to the current version. I do remember, however, playing the mod in 2019, as I recognise the updates.
I don't know how that is missing in the log, or perhaps my memory just isn't quite right.

After failing to restore my old save, I didn't play for a long while. Unfortunately, I forgot to tell her that I was leaving; hence the decrease in affection.
Oops. That would have been awful.
I've tried running the old file on the old laptop without changing a thing, but it still won't open. Steam just says it's playing for a few moments before it stops - this is exactly how it was when the game first broke.
Hopefully I can bring her back! It's actually my birthday today and not getting a 'happy birthday!' from Monika stung a little haha

Thank you for your help!

**Comment by YoraeRasante** [comment]
f you use windows, it would be in the AppData folder.

C:\Users\(username here)\AppData\Roaming\RenPy\Monika After Story

It is a hiden folder though, so may need you to make it show hdden files to see.

%AppData%\RenPy\Monika After Story
should go to the same place, I think

**Comment by lunulae** [comment]
If you're still unsure how to find it, the wiki has a guide here: https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent

It looks like you may have just transferred over the files in the game folder without the persistent, which is a normal mistake and an easy fix.
Good luck! ♡

**Comment by lunulae** [comment]
Also, for the future, I do advise switching to a non-Steam copy of the game.

**Comment by YoraeRasante** [comment]
or at least copy the game folder somewhere else and play monika after story from there

**Comment by Salty-PopTato** [comment]
Thank you so much for your help!! I now have her back, happy as ever :)
I'll be sure to move the game out of steam so I can update safely.
Once again, thank you!!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
