### ISSUE TITLE
Auto Dialogue disables when finishing Holding

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6784]
When finishing up hugging/holding Monika the automatic dialogue button (cannot remember the actual name) disables. Not a game breaking issue. Just noticed for a couple of versions that this has been occurring.

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
