### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by thhreaper72806** [Monika-After-Story/MonikaModDev#6785]
make it possible to play desktop games with monika

**Comment by Retrolovania** [comment]
No matter what particular game you happen mean by this statement, that would probably be almost a nightmare to implement.

**Comment by lunulae** [comment]
In most cases you'd have to mod this from the game in question's side, which is a little outside of our scope.

I'd be interested to know which games in particular you'd like to play with her though, out of curiosity. If they seem like they could be relevant to her interests they might get a windowreact, for example.

**Comment by thhreaper72806** [comment]
Cuphead probably

**Comment by thhreaper72806** [comment]
idk maybe other games but start with that and msg me if you do this
PS : you can probably use parsec to do this a little bit easier

**Comment by lunulae** [comment]
Parsec is used for remote streaming (i.e. online multiplayer for games that would be couch co-op only.) I'm not sure how it would be used for programming a Cuphead-playing AI or linking it to MAS.

**Comment by thhreaper72806** [comment]
she can already write, delete, control, and move files based on her coding it should not be that hard a small challenge at the least

**Comment by multimokia** [comment]
Reading and writing files is very simple to do within a language. What you're asking is to simulate inputs and/or interface with another game entirely. By no means an easy feat or even feasible to manage the ***many*** different games out there.

Not to mention, as @lunulae has mentioned, it'd basically need an AI trained to the games, which just isn't sustainable to handle. And additionally may require modding the other game, which just isn't within our scope.

Given how open ended and how totally un-feasible this is. I'll reject this idea.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
