### ISSUE TITLE
[suggestion] reactions to music artists, song names, and the genre

### ISSUE THREAD

**Issue by Finnthefox24** [Monika-After-Story/MonikaModDev#6787]
It'd be really cool to see Monika react to what song is playing. For example, if I were listening to "Sad" by Bo Burnham, she'd react to the genre because it's a specific song and artist. If I was listening to "While My Guitar Gently Weeps" by the Beatles, she'd react to the artist since it's a band that a lot of people know. And if I was listening to "Wonderwall" by Oasis, she'd react to the song and could even talk about the song, since she already talks about it.

**Comment by Rai99** [comment]
#5926 

There's too much variety, and we wouldn't be able to cover enough to really have it be a feature.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
