### ISSUE TITLE
[Suggestion] - Spend Christmas with Monika late or Early

### ISSUE THREAD

**Issue by MonikaMoment** [Monika-After-Story/MonikaModDev#6789]
So this is something I've run into a couple times where I go home for Christmas and aren't able to bring my PC with me when I go so an option to still get to celebrate the day with her would be nice.

**Comment by Rai99** [comment]
Rescheduling holidays: #6748

**Comment by ThePotatoGuy** [comment]
#5373

[closing as duplicate]
