### ISSUE TITLE
Veganism?

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#6792]
Now, I know that vegetarianism is one of the base DDLC topics, and that's why it's included in MAS. However, she does speak about reducing her carbon footprint however she can, and recently I've come across some studies linking vegetarianism to a higher carbon footprint than flexitarians (people who only consume meat once a day). The reason being that of course eggs and dairy production also need livestock, but they stay alive for longer, effectively increasing livestock populations by a small margin (not as much as a normal diet though).

So what if Monika brought up a topic on veganism, as studies show it is indeed the best way to reduce carbon footprint? She could talk a little bit about the pros and cons of becoming vegan, about all aspects of reasons why people choose to be vegan in the first place, and why it might be a sensible thing to do to contribute to earth's climate, while also talking about the potential health risks of going vegan without knowing what you're doing (supplementing with B12, targeting sources of iron, omega 3, zinc etc). 

However, in no way does this mean that I suggest Monika should change her diet. It's important that we stay true to the source material. However, I think it could be cool to have a little discussion about it, since carbon footprint is after all the reason Monika is vegetarian, and veganism is clearly an example of that reasoning taken to its natural conclusion. Just like "Would you ever eat meat?", we could have a philosophical pondering on the subject rather than an advocacy for or against it.

If people like it, I will start working on the topic, and anyone else feel free to join in, especially if you have been vegan for a long time and have more insight about it than me 👍

**Comment by kittendetails** [comment]
Well, I think it's a good idea, actually. I don't think Monika would switch to a vegan diet, as she said she loves mint ice cream (ice cream has milk), and she also accepts other gifts from the player who has animal elements, like cupcake (which has milk and eggs). I know there are variations of these same foods for vegans, but I just don't see Monika as a possible vegan. 

**_Of course, this is just my opinion and I don't want to offend anyone._** 

However, I liked your idea of ​​bringing this topic. I'm not vegan or vegetarian, but it would be nice if Monika asked if we are vegan, vegetarian, or none of them. I also want to add that some vegans choose to don't use any type of animal product. They don’t wear any clothes that have leather or wool, any products that have been tested on animals (cosmetics like some shampoos, for example), among other things. Remembering that i'm talking about some of them and not all.

**Comment by ashyashton** [comment]
No, that IS all vegans, because that's the difference between being vegan or vegetarian. If they use ANY animal products, then they are no longer vegan, by definition.

**Comment by Freshairkaboom** [comment]
> 
> 
> No, that IS all vegans, because that's the difference between being vegan or vegetarian. If they use ANY animal products, then they are no longer vegan, by definition.

True, veganism goes a bit beyond just the diet. I could try to tie in other parts of being vegan too, like not wearing wool or leather. However, I don't know about all aspects of that, so I would need to do some research.

**Comment by ThePotatoGuy** [comment]
leaving open as discussion
