### ISSUE TITLE
Monika doesn't recive gifts

### ISSUE THREAD

**Issue by Hamster20073** [Monika-After-Story/MonikaModDev#6793]
monika won't accept gifts  i do every step to make the gifts work but whenever i open the game monika doeas'nt respond with anything and the .gift files always dissapear from the characters menu

**Comment by Freshairkaboom** [comment]
To be clear, do they disappear without her saying anything, or does she say something like "Are you trying to give me something?" etc.

**Comment by Ant9cp** [comment]
All the gifts that involves like clothing or any type of jewelery will be laying under the christmas tree 

in the original spaceroom (for people that have the submod for extra rooms)

when it's christmas day then monika will open all the gifts that you gave her


Consumables like coffee chocolates or any kind of food candy and drinks will be instantly be noticed by monika roses too

**Comment by Ant9cp** [comment]
@Hamster20073

All the gifts that involves like clothing or any type of jewelery, will be laying under the christmas tree

in the original spaceroom (for people that have the submod for extra rooms)

when it's christmas day then monika will open all the gifts that you gave her

This don't count for Consumables like, coffee chocolates or any kind of food candy and drinks and roses

**Comment by Feyweet** [comment]
> @Hamster20073
> 
> All the gifts that involves like clothing or any type of jewelery, will be laying under the christmas tree
> 
> in the original spaceroom (for people that have the submod for extra rooms)
> 
> when it's christmas day then monika will open all the gifts that you gave her
> 
> This don't count for Consumables like, coffee chocolates or any kind of food candy and drinks and roses

many people were confused by this, she is only storing the gifts to open them at Christmas, but after I updated the mod, the tree disappeared, even though it has disappeared and the ornaments too, I have a chance to give more gifts and she keep storing to open at Christmas?

**Comment by Ant9cp** [comment]
@Feyweet Are the other decorations? in the room gone too? if so then 
Did you download the latest version? v0.11.8 and if that didn't fix it, then i don't have any other idea's for this issue that you have 





Add a new issue about this for more assistance

**Comment by Booplicate** [comment]
@Feyweet are you using the default background (spaceroom)?

**Comment by Feyweet** [comment]
> @Feyweet você está usando o fundo padrão (espaço)?
no, and I updated the mod in another spaceroom

**Comment by Booplicate** [comment]
That's why you don't see the decoration, she decorated only one room. She still will get your gifts, though.

**Comment by Feyweet** [comment]
> É por isso que você não vê a decoração, ela decorou apenas um quarto. Mas ela ainda vai receber seus presentes.

Thank you

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
