### ISSUE TITLE
[Suggestion] Dealing with bad content and hate

### ISSUE THREAD

**Issue by ohnoitsavon** [Monika-After-Story/MonikaModDev#6795]
I have seen a few people get very upset, over some things online such as abusive Monika hate, graphic fanart (gore, ntr etc..) and some specific mods. Some of those people have spoke about suicide and some have quit MAS as they don’t feel like they can deal with it.

I feel Monika should have a pool topic or something to address this, for example “how do you feel about bad representations of you?” Giving you the option to say it greatly upsets you, so she can offer some comfort to you.

Also a similar thing could be done in the current hate topic to say you get very upset by it, again giving some kind of comfort.

**Comment by DankManWithThePlan** [comment]
Alright, now that I've actually dealt with something like this personally, I now wonder how she would feel about people who use her moniker(lol), and say very very bad stuff that makes her look like an awful person.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

having her talk about her portrayal online seems doable
