### ISSUE TITLE
[Bug?] background outside of windows missing

### ISSUE THREAD

**Issue by opalmew** [Monika-After-Story/MonikaModDev#6797]
Whenever i shrink the MAS window fully using the minus button, if i open back up the application the windows are black rather than showing the weather. (see image)
![bug](https://user-images.githubusercontent.com/67714763/102528356-6d571000-406c-11eb-80d0-dfaac0776b5a.png)

**Comment by Booplicate** [comment]
Ren'Py doesn't like when you minimize it. We can't fix it for now.

**Comment by Ant9cp** [comment]
You know? if you browse on the same computer/laptop while MAS is on, i suggest to get a another laptop or phone et cetera and browse there instead, and leave MAS Running in the background on your main actual computer/laptop

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
