### ISSUE TITLE
Monika drinking chocolate milk more often

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6798]
She drinks chocolate milk only like around the winter or on christmas why not more often i gift her so much chocolate milk until she has too much chocolate milk but she is not drinking it

**Comment by Booplicate** [comment]
I think there's a difference between chocolate milk and hot chocolate. She drinks *hot chocolate*, which makes more sense during winter.

**Comment by Ant9cp** [comment]
(I think there's a difference between chocolate milk and hot chocolate.)



Yep. stay in school kids LOL☺

**Comment by ashyashton** [comment]
I mean, hot cocoa is kinda a winter drink. Do you drink hot cocoa during the summer? Probably not. So why would Monika?

**Comment by Ant9cp** [comment]
Well yes i drink like hot chocolate or coffee on warm days so what's the problem?

**Comment by YoraeRasante** [comment]
I drink hot chocolate milk every morning. including on summers. In fact I did it not half an hour ago and I like in a tropical country of the south hemisphere so really hot day of summer today.
