### ISSUE TITLE
Exception occured

### ISSUE THREAD

**Issue by DrStrangeHat** [Monika-After-Story/MonikaModDev#6799]
Hello All.
I'm rather new to GitHub. I've also been playing MAS for about half a year now. Haven't run into major problems until now.
I just got myself an exception when I ran the new update. I think perhaps this is because I've missed the first xmas update (not playing as often as I used to). The game appears to start okay, and I haven't noticed anything odd yet, but I thought I should report this anyway. So I'll just add a notepad file with the error code in it. If anyone can shed some light on this matter I'd appreciate it.
[MAS error code.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5715964/MAS.error.code.txt)

**Comment by multimokia** [comment]
Looks like you're missing a needed file. I'd give MAS a reinstall to make sure no other files end up going missing. Otherwise MAS will have this whenever Monika leans.

**Comment by DrStrangeHat** [comment]
Thank you kindly. I'll give that a try.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
