### ISSUE TITLE
Repeat conversation 

### ISSUE THREAD

**Issue by Feyweet** [Monika-After-Story/MonikaModDev#6800]
Does anyone know in what can be used this menu and features besides repeating the topics?

**Comment by fromulus** [comment]
Nothing.
Like the name implies, this menu is meant to be there simply to "repeat topics" that she would otherwise only bring up on her own.

That menu might get expanded into something more in the future, but that's not for right now.

**Comment by Feyweet** [comment]
> Nada.
> Como o nome indica, este menu é simplesmente destinado a estar lá para "repetir conversas" que ela de outra forma só traria à tona por conta própria.
> 
> Pode ser expandido para algo mais no futuro, mas isso não é por enquanto.


 ok, thank you very much,

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
