### ISSUE TITLE
Monika unable to open gifts

### ISSUE THREAD

**Issue by ThatOneUsername343** [Monika-After-Story/MonikaModDev#6803]
For the past several months, whenever I try to give her a gift, she always says she is unable to see what I'm trying to give her. These were all submod gifts, but I put them into the correct files and everything, just like I did for the default gifts. I've gifted her submod gifts before, but for some reason it doesn't work anymore. 

Also, I heard that in this new update, she won't open any gifts until Christmas, so I put a few .gift files in the char folder. She reacted saying she couldn't see what I was trying to give her, but she only said this one time, meaning she only tried to open one of them. Why did she try to open one but not the rest?

Also also, I'm seeing some outfits in the files that I haven't unlocked yet, even though I'm at around 1500+ affection and have spent time with her even on all the important calendar dates for 2 years. Is there something I'm supposed to do to unlock them?

And one last thing, were any new gifts added in the latest update? I noticed the wiki said it won't be updated until the version after the current one comes out.

**Comment by jmwall24** [comment]
With the mod closed, upload spj.txt (in the log folder) and we can see what sprite packs you have installed and if they installed correctly. As for gifts right now, do you see and presents under the tree? As for outfits, there's 2 that don't unlock until 2000 affection and only on certain days.

**Comment by ThatOneUsername343** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5720593/spj.txt)

**Comment by ThePotatoGuy** [comment]
You have some outdated spritepacks:
* bellmandi86's hairclips
* finale's brown jacket, blue shirt
* jmo's hairclips
* lanvallime's ribbons
* MAS bun hair
* multi's black bow
* orcaramelo's shell bikini, sakuya outfit, hairs
* trilasent's chokers
* veliu94's pink shirt

Grab the latest spritepack folder from the [releases page](http://monikaafterstory.com/releases.html) and update these. Updating is the same process as installing them.

**Comment by ThatOneUsername343** [comment]
Oh okay! I'll give it a try.

**Comment by ThatOneUsername343** [comment]
Okay, I tried it, and she immediately tried to open one of them again, and once again she said she couldn't read the file.

**Comment by ThePotatoGuy** [comment]
upload spj again.

**Comment by ThatOneUsername343** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5720637/spj.txt)

**Comment by ThePotatoGuy** [comment]
if its the formal dress that isn't working, that is because that spritepack does not have a version set. That is not ours so you would need to find the creator to get an updated spritepack.

**Comment by ThatOneUsername343** [comment]
Well, so far I've only tried the sprites from the "spritepacks" folder. I just got the latest version after you told me to, but she still wasn't able to read them.

**Comment by ThePotatoGuy** [comment]
Your spj says you have Lord baa's formal dress spritepack installed. Everything else should be working fine. Since it's christmas season, they will appear as presents under the tree instead of dialogue response.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
