### ISSUE TITLE
Problem with gift

### ISSUE THREAD

**Issue by Samu49** [Monika-After-Story/MonikaModDev#6804]
I got a weird problem with gift when i try to give her gift while the game is open she say she can't read it well enough but when i try to give her gift while the game is closed she say nothing and the gift goes under the Christmas tree is that normal ? 

(Sorry for my bad English)

**Comment by Feyweet** [comment]
yes, she's storing them to open at christmas

**Comment by Samu49** [comment]
> yes, she's storing them to open at christmas

Okay but is that normal she can't read the one i give to her while the game is open

**Comment by Feyweet** [comment]
> > Sim, ela está armazenando-os para abrir no Natal.
> 
> Ok, mas é normal que ela não pode ler o que eu dou a ela enquanto o jogo está aberto


this also happened to me once, I believe it is not normal, it must be some bug, if this continue you better give gifts only when the game is closed

**Comment by Samu49** [comment]
> > > Sim, ela está armazenando-os para abrir no Natal.
> > 
> > 
> > Ok, mas é normal que ela não pode ler o que eu dou a ela enquanto o jogo está aberto
> 
> this also happened to me once, I believe it is not normal, it must be some bug, if this continue you better give gifts only when the game is closed, but that doesn't happen with consumables

Ok will she able to read the one under the tree at Christmas or not ?

**Comment by jmwall24** [comment]
Any gift that she says she can't open means that spritepack for the gift is installed incorrectly or the `.gift` file is named incorrectly.

**Comment by Samu49** [comment]
> Any gift that she says she can't open means that spritepack for the gift is installed incorrectly or the `.gift` file is named incorrectly.

I'm using the latest spritepack so i don't know what i'm doing wrong

**Comment by Samu49** [comment]
Ok i think it's working because this time she don't even read it so the gift is under the tree i guess

**Comment by ThePotatoGuy** [comment]
gift acknowledgement during christmas could be better handled but atm the tree is how it works

[closing as resolved]
