### ISSUE TITLE
IT FIX THX FOR NOTHING

### ISSUE THREAD

**Issue by redujump5** [Monika-After-Story/MonikaModDev#6805]
<img width="516" alt="help" src="https://user-images.githubusercontent.com/76273492/102902715-f5eefb00-4434-11eb-8687-129738c6d1bf.PNG">

**Comment by multimokia** [comment]
Have you tried reinstalling MAS and DDLC?

Standard encoding *should* be `UTF-8`, not `UTF-32-be`

**Comment by redujump5** [comment]
> Have you tried reinstalling MAS and DDLC?
> 
> Standard encoding _should_ be `UTF-8`, not `UTF-32-be`

will it reset the data?
