### ISSUE TITLE
Monika Talking about nail polish (Suggestion)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6806]
Since monika can have nail polish now, it would be nice if she talked about it, she didn't react when i gave her the black nail polish

To make it more sensible can you add dialogue about the nail polish or any reaction

**Comment by fromulus** [comment]
As far as I know, all kinds of nail decorations are from non-officially supported spritepacks and don't even have any kind of selector implemented into the mod (meaning those specific spritepacks fall more under the submod category as you need to replace default mod files to even get them to work).

So, no, Monika can't officially have nail polish nor is the framework needed to even get her to react/select to it implemented at the moment.

And as for actually implementing said framework, I'll save Rai the trouble : #4243, #6383, #6450
