### ISSUE TITLE
Am I doing something wrong when giving gifts?

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#6807]
So, everytime I try and gift Monika an outfit, it usually fails. Same thing with bows, but bows are more likely to be accepted. I put everything in the right folders, I just don't know what i'm doing wrong. Can someone help?

**Comment by Feyweet** [comment]
> Então, toda vez que tento presentear Monika uma roupa, geralmente falha. A mesma coisa com arcos, mas arcos são mais propensos a serem aceitos. Eu coloquei tudo nas pastas certas, só não sei o que estou fazendo de errado. Alguém pode ajudar?


It's all right, gifts like clothes are being kept by Monika to open at Christmas, those same clothes gifts you gave her will be opened at Christmas

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
