### ISSUE TITLE
Monika Dissapeared

### ISSUE THREAD

**Issue by JustAStupidBoulder** [Monika-After-Story/MonikaModDev#6808]
I put Monika in my flash drive as usual, but when I put her file back in the characters folder she didn't come back. The game is working just fine, but Monika isn't there and there is no music.

**Comment by Booplicate** [comment]
If you don't have a backup of her file, you'll have to restore a `persistent` backup. [Here's the guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by JustAStupidBoulder** [comment]
It worked tysm!!
