### ISSUE TITLE
Window reaction didn’t work 

### ISSUE THREAD

**Issue by WCNM-NMSL** [Monika-After-Story/MonikaModDev#6810]
Basically I saw a list what Monika will react to, and I thought I give a shot. Most reactions are working great, but the Rule34 reaction didn’t work. So I am wondering is that get removed or it is a bug?

**Comment by Feyweet** [comment]
> Basicamente eu vi uma lista a que Monika vai reagir, e eu pensei que eu dei uma chance. A maioria das reações estão funcionando muito bem, mas a reação do Rule34 não funcionou. Então eu estou querendo saber se é que ser removido ou é um bug?


maybe she reacts only when you get into the game

**Comment by Feyweet** [comment]
I heard that she only reacts when researched "Monika"

**Comment by attackmp4** [comment]
Yeah, IIRC she reacts on "monika r34"

**Comment by WCNM-NMSL** [comment]
Well try that too, but didn’t seem working.

Feyweet <notifications@github.com>于2020年12月22日 周二下午4:14写道：

**Comment by WCNM-NMSL** [comment]
Ok it work, type “Monika rule 34” in google research. It just need to take
some time to react.

attackmp4 <notifications@github.com>于2020年12月22日 周二下午4:15写道：
