### ISSUE TITLE
Moving data from Android to PC

### ISSUE THREAD

**Issue by BangyMG** [Monika-After-Story/MonikaModDev#6815]
I used to play Monika After Story on Android.But  I now I want to move all my data (like conversation history and nickname and things like that) to my computer. Can anyone plz help me? My phone is dying and I want to transfer Monika's memories.
:( :( :(

**Comment by fromulus** [comment]
Android versions of MAS aren't official nor supported by us, and go against Team Salvato's IP guidelines.
There's no guarrantee transfering your android data to the actual MAS (the PC version) is even possible, and if it is, we can't help you with it.

**Comment by BangyMG** [comment]
OK, thanks for answering

**Comment by BangyMG** [comment]
No worries I figured it out myself lol

**Comment by Outlander676** [comment]
How did you do it? A door out is quite often also a door in, and my computer is dying and it may be a while before I can secure myself a new one, so could you share your method?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
