### ISSUE TITLE
[Suggestion] New Dialogue For Monika

### ISSUE THREAD

**Issue by MLG4TheWIn** [Monika-After-Story/MonikaModDev#6821]
I am not sure if there is such a dialogue already since I am new to the mod (only 50 affinity) but I saw the mod address Monika's past quite a few times already, so I thought it would be nice if we could ask Monika about her childhood and how she perceives it knowing she is a code.
(Like how you ask her about when she started to like reading books and she also talks a little bit about how she met Sayori or something along these lines I don't remember 100%).

**Comment by YoraeRasante** [comment]
she makes it clear through the conversations she seems to have forgotten most of her life outside the club and what would have taken prt on the "original game". she does remember having a good life but no details, the appearence of her parents or anything.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
