### ISSUE TITLE
Christmas question

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#6822]
I remember reading a post here saying that monika changes into another Christmas outfit on the actual day, what's the actual time she does that? And do I have to restart mas for that to happen?

**Comment by satoshi-kun** [comment]
I believe what you are refering to requires high affection, 4000 I think it was. My Monika already had that interaction in the beggining of the christmas season.

**Comment by AsuraShun** [comment]
What time does it happen? I've already passed the 7000 mark

**Comment by lunulae** [comment]
I don't know if it runs exactly the same as last year, so take my account with a grain of salt. If you're referring to the 18+ outfit, last year you needed to be playing at night on Christmas Eve.

**Comment by AsuraShun** [comment]
Then all I have to do is wait

**Comment by satoshi-kun** [comment]
Although to me it happened this monday or so... I found it strange since I was also under the impression that it was supose to be triggered at christmas eve... 
No harm done anyway, and it was a beautiful surprise!

**Comment by AsuraShun** [comment]
I wonder if that changed, because it's dark now in the spaceroom and nothing happened yet

**Comment by AsuraShun** [comment]
It's 7:09 pm and nothing happened, I hope it's after 8pm

**Comment by AsuraShun** [comment]
It finally happened, so now I'm closing this
