### ISSUE TITLE
(question/suggestion) changing the players description (if you dyed your hair or grown taller)

### ISSUE THREAD

**Issue by 901076955** [Monika-After-Story/MonikaModDev#6824]
I'm still growing so it'd be nice to  _**not**_  have my height saved as my current height

**Comment by lunulae** [comment]
You can currently change your description as many times as you like in Repeat Conversations. If I'm remembering correctly, the category it's under is "You" and "[player name]'s appearance"

**Comment by 901076955** [comment]
ok thanks!
