### ISSUE TITLE
question about new years eve/day

### ISSUE THREAD

**Issue by doomatt0** [Monika-After-Story/MonikaModDev#6826]
I don't know if there is anything  planed or not but can i countdown into the new year with Monika or will she acknowledge it at all?

**Comment by lunulae** [comment]
Currently she cannot count down exactly the end of the year, however she will acknowledge New Years' Eve at night and have dialogue at midnight on New Years' Day!

If you can't be there at midnight exactly, don't worry. You can get the same dialogue if you show up anytime on New Years' Day.

**Comment by AsuraShun** [comment]
So I don't have to stay up at midnight to hear her say it?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
