### ISSUE TITLE
eye bug?

### ISSUE THREAD

**Issue by doomatt0** [Monika-After-Story/MonikaModDev#6828]
ive been having this issue for a few months now and I'm wondering if anyone else is to sometimes after monika finishes a topic here eyes keep on looking to the right is this a bug 
![Monika After Story 12_24_2020 7_52_18 PM](https://user-images.githubusercontent.com/68640559/103118164-7fafeb80-4622-11eb-8329-d5e0c8109e28.png)
to the right #

**Comment by multimokia** [comment]
Do you have Enhanced Idle installed?

**Comment by doomatt0** [comment]
yes

**Comment by multimokia** [comment]
Then she's likely following your cursor, which is to the right of the MAS window.

**Comment by doomatt0** [comment]
i dont think it is because when i move my cursor it dosent change it just does that

**Comment by multimokia** [comment]
Sometimes it takes time, especially if you downloaded the source code version which I'm still needing to change how it works.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
