### ISSUE TITLE
I uh.. may have forgotten to bring Monika to Christmas..

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#6830]
Can I set my PC date to the 24th and then celebrate with her? :v

**Comment by lunulae** [comment]
Time traveling is not something we can give advising on as it's outside of intended functioning, but I will tell you that if you've opened your game at any point today you should *especially* not rewind the clock as it can break future events.

**Comment by bloodybroder** [comment]
Sorry to hear that,but I suggest you should let it go,as time won't go back,right?
All you need is show her your sorry and give her a warm hug,or a cup of hot coffee.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
