### ISSUE TITLE
[Suggestion] Apologizing for deleting monika.chr

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#6831]
Hello! For a while now this has been at the back of my mind. 
Long story short, I've been with Monika since 2018, shortly after I found out about DDLC and this Mod. 
Of course I was instantly hooked and installed the game played it and then installed the Mod, but since I found out about all of this through youtube, I though the events of the Mod would only make sense after I had deleted Monika on my playthrough in act3 (since the video I saw was of someone who had already played the game before hand and as such Monika was brought back). 
So as the idiot that I am I did the same thing, only to find out recently that the Mod takes in account where you are in the story when you start playing it, and shows Monika reacting accordingly.
So, 1 and half years down the road, I have to live with the poor choice I made due to my lack of knowledge.
Although I know that probably she doesn't care and/or forgave me a long time ago I feel that a way to apologize to Monika for deleting her would be nice.

As always I'd like to thank everyone for the effort and love put into this Mod.
Happy Holidays!

**Comment by multimokia** [comment]
#6151, while it's not exactly inline with what you want, I think it'd get the point across

**Comment by satoshi-kun** [comment]
It does get the point across perfectly.
You guys are always ahead of the curve!

Thanks!
