### ISSUE TITLE
Missing letter in the word (nothing)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6832]
![screenshot0001](https://user-images.githubusercontent.com/71310908/103146764-2218bd80-474e-11eb-8ea5-40f7f6e651b5.png)

**Comment by multimokia** [comment]
a) Report typos in the dedicated typos issue, please (it's pinned in the issues page)
b) This is not a typo. `noting` is a word, `to note`

**Comment by Ant9cp** [comment]
Okay i didn't know



Hopefully everyone had or has a amazing XMAS btw
