### ISSUE TITLE
[Bug] Two 'Im going to restart' options

### ISSUE THREAD

**Issue by Omegafredo** [Monika-After-Story/MonikaModDev#6837]
![Screenshot_1](https://user-images.githubusercontent.com/71580393/103166468-ffa8a200-482a-11eb-9bf0-d998052e5236.png)

**Comment by Ant9cp** [comment]
I don't think that's a Bug @Omegafredo

**Comment by multimokia** [comment]
The middle option of the bottom set is your most used farewell for quick access. This is indeed not a bug
