### ISSUE TITLE
Whole Screen Blinking When Opening DDLC

### ISSUE THREAD

**Issue by cremecaramel** [Monika-After-Story/MonikaModDev#6847]
Hi devs! I've got a scary serious issue. I just downloaded the new Christmas Fix Update 2 and I put some .gift files in the characters folder in an attempt to gift her when I first open the game.

 WELL when I did this, the game froze and suddenly my computer screen began to blink...?? The screen went go black, then normal, then black again, in a rhythm (it wasn't rapid or sporadic, not sure if that detail matters though)

WHAT in the world is going on, guys?? Is it my computer?? I'm like, genuinely scared

Appreciate it!
- Creme

**Comment by AsuraShun** [comment]
Just in case, you should make a backup of the persistent files

**Comment by cremecaramel** [comment]
> Just in case, you should make a backup of the persistent files

My persistent currently isn't corrupted, is it?? I tried opening DDLC back up and the flashing was even worse; I could hardly close the game

**Comment by multimokia** [comment]
It sounds more like an issue with your graphics driver. Did Windows update at all for you recently? (Assuming you're running on Windows)

**Comment by cremecaramel** [comment]
> It sounds more like an issue with your graphics driver. Did Windows update at all for you recently? (Assuming you're running on Windows)

Windows has not updated recently... I was actually having issues trying to update a few days ago; I kept getting error messages each time I tried to?? I probably need to call Microsoft support soon

**Comment by multimokia** [comment]
Mmm, what errors are you getting?

**Comment by cremecaramel** [comment]
> Mmm, what errors are you getting?

Problems installing for three updates,, all with the codes Error 0x80070002

**Comment by multimokia** [comment]
Hmm, that seems to be addressed [here](https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-fix-error-code-0x80070002/b2790e69-fac1-4487-934f-10c91c2b9beb).

However, for the other issues, consider maybe updating your graphics drivers.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
