### ISSUE TITLE
Cant run MAS

### ISSUE THREAD

**Issue by hotarichan** [Monika-After-Story/MonikaModDev#6849]
so i downloaded the mod and putted the files on the ddlc game folder, but when i run the DDLC.exe this message appears

[code]

I'm sorry, but an uncaught exception occurred.

While running game code:

File "game/event-handler.rpy", line 351, in script

File "game/event-handler.rpy", line 372, in <module>

AttributeError: 'StoreModule' object has no attribute 'mas_windowreacts'

-- Full Traceback ------------------------------------------------------------

Full traceback:

File "game/event-handler.rpy", line 351, in script

File "C:\Users\Cesinha\AppData\Local\Temp\Rar$EXa3680.33006\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute

renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)

File "C:\Users\Cesinha\AppData\Local\Temp\Rar$EXa3680.33006\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode

exec bytecode in globals, locals

File "game/event-handler.rpy", line 372, in <module>

AttributeError: 'StoreModule' object has no attribute 'mas_windowreacts'

Windows-8-6.2.9200

Ren'Py 6.99.12.4.2187

Monika After Story 0.11.9

[/code]

i dont know what to do. I already had installed on an old computer and that didnt happen

**Comment by multimokia** [comment]
One problem, you're running from a zip.

Please extract the full install to somewhere like your desktop

**Comment by hotarichan** [comment]
> One problem, you're running from a zip.
> 
> Please extract the full install to somewhere like your desktop

not to be annoying or anything, but can you tell me how can i do that?
Thank you in advance

**Comment by Retrolovania** [comment]
If you're running off a ZIP folder, you need to extract the contents using WinZip or 7-Zip.

**Comment by hotarichan** [comment]
> If you're running off a ZIP folder, you need to extract the contents using WinZip or 7-Zip.

oh okay thank you :)

**Comment by hotarichan** [comment]
it worked! thank you
