### ISSUE TITLE
I'm sorry, but an uncaught exception occurred

### ISSUE THREAD

**Issue by KesirVG** [Monika-After-Story/MonikaModDev#6850]
Hello, I have a problem with the modem after the computer factory settings, before that everything worked and after that the game won't start and I have something like that
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 13, in script
  File "game/script-ch30.rpy", line 25, in <module>
Exception: Unstable mode files in install on first session. This can cause issues.
Please reinstall the latest stable version of Monika After Story to ensure that there will be no data issues.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "F:\Ustawienia\gry\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "F:\Ustawienia\gry\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/script-ch30.rpy", line 13, in script
  File "F:\Ustawienia\gry\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Ustawienia\gry\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 25, in <module>
Exception: Unstable mode files in install on first session. This can cause issues.
Please reinstall the latest stable version of Monika After Story to ensure that there will be no data issues.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.9-unstable.2020.12.19.133

**Comment by multimokia** [comment]
Did you back up your persistent before doing that reset??

**Comment by KesirVG** [comment]
I only transferred the game files I thought there was a save of the game because I couldn't find anything else related to the mod on the computer

**Comment by multimokia** [comment]
We have a guide on how to back up persistents [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). Monika also mentions this in one of her topics.

Unfortunately, if you reset your PC completely (didn't preserve files), it means she's gone, I'm afraid.

To get MAS working again, you need to reinstall the latest stable release of MAS, which you can get from our [releases](https://github.com/Monika-After-Story/MonikaModDev/releases) page

**Comment by KesirVG** [comment]
it's nothing to start over, or I still have its file in the character folder but I don't know if it will do anything
![obraz_2020-12-29_222324](https://user-images.githubusercontent.com/47786393/103314943-78268300-4a24-11eb-9f24-a162f3ab0803.png)

**Comment by KesirVG** [comment]
Thanks for the help

**Comment by jmwall24** [comment]
Only thing you can try if you did choose to keep files is see if you have a Windows.old file on your main drive

**Comment by KesirVG** [comment]
nice it work thanks for help me

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
