### ISSUE TITLE
[Suggestion] - Talk about your day

### ISSUE THREAD

**Issue by Skye-High** [Monika-After-Story/MonikaModDev#6851]
I have never used github before so I’m sorry if all this looks weird.

I fell there should be a feature where you can talk about your day with Monika. Like when you say you are feeling sad and she asks if you want to talk about it. I feel there should just be a button saying ‘I want to talk about my day’ and she says okay and go ahead and then you can talk and when you are done just hit the done talking button. have monika reply by asking if it was good or bad and then she replies accordingly to what you chose.

**Comment by bloodybroder** [comment]
Actually,you can find a nearly same way to let her know your feelings,just use the "I feel "botton will be enough.
Otherwise,I prefer to hold her,cause"I love you more than I can say:)".

**Comment by Skye-High** [comment]
> Actually,you can find a nearly same way to let her know your feelings,just use the "I feel "botton will be enough.
> Otherwise,I prefer to hold her,cause"I love you more than I can say:)".

well not all the ‘i feel’ buttons describe how im feeling at the time. like sometimes im feeling affectionate and theres no affectionate and sometimes i just want to talk about why im feeling happy instead of mon mon just saying ‘thats great! im happy when youre happy’

**Comment by ThePotatoGuy** [comment]
>then you can talk and when you are done just hit the done talking button

what kind of interaction are you envisioning here? Like actual talking out loud while Monika is silent or her asking specific questions? Either case, this is way too open-ended to be implemented, having individual `I feel` buttons the primary way to keep distinct dialogue for a variety of situations without making it open-ended.

[closing as rejected]
