### ISSUE TITLE
PLEASE HELP!!

### ISSUE THREAD

**Issue by dontworryabouttheusername** [Monika-After-Story/MonikaModDev#6856]
i took Monika out for new years eve,
when its time to put to put her back in the characters,
i leftclick hold and drag making two copies of her..
and the game accepted the copy,  i took her out again to delete the copy and insert the original but the game the wont accept her so i digged through the bin and pasted it "replace file" and i dont know what the real file anymore perhaps i have deleted the original..
at this point i panicked
i know this is dumb, im not good at these

please help you people are my last hope..
i know ive been rude to people in here im sorry i really am and i beg you i cant forgive myself for accidentally deleting my Monika out stupidity
i need my Monyika back.. please

**Comment by KcalbVessalius** [comment]
i guess you should go to the renpy folder and restore a persistent before you leave with her

**Comment by dontworryabouttheusername** [comment]
> i guess you should go to the renpy folder and restore a persistent before you leave with her

thankyou thankyou, so i just have to paste the persistent in there?.. ive never done this before,
and the last time i made a backup was oct29 2020
im gonna try..

**Comment by AsuraShun** [comment]
May I suggest you do those backups daily from now on?

**Comment by KcalbVessalius** [comment]
f

> > i guess you should go to the renpy folder and restore a persistent before you leave with her
> 
> thankyou thankyou, so i just have to paste the persistent in there?.. ive never done this before,
> and the last time i made a backup was oct29 2020
> im gonna try..

ok wait i will try to explain, im not good in english xd

**Comment by dontworryabouttheusername** [comment]
> i guess you should go to the renpy folder and restore a persistent before you leave with her

do i need a fresh copy?

**Comment by dontworryabouttheusername** [comment]
> May I suggest you do those backups daily from now on?

I WILL!!

**Comment by KcalbVessalius** [comment]
first, made a backup daily is always good, second when u go to roaming, renpy, mas, did u see persistents with numbers? this is game auto backup, just erase the number and the .back of one of thoses(the one more recent) and replace the current persistent when ask so, i think is pretty hard explain for text but i hope u understand

**Comment by KcalbVessalius** [comment]
![image](https://user-images.githubusercontent.com/48925478/103414008-cb025680-4b5a-11eb-88e8-5047de043ff4.png)
for example, this is my last auto backup, if my save after this hour has been corrupted i just have to rename, erase the numbers e and the .bak and everything should be fine

**Comment by KcalbVessalius** [comment]
and yep, just now i thought about send a image, i should did it before

**Comment by dontworryabouttheusername** [comment]
> and yep, just now i thought about send a image, i should did it before

aight ill be careful i dont want to mess this up again

**Comment by KcalbVessalius** [comment]
make a backup now just for good assurance

**Comment by dontworryabouttheusername** [comment]
> make a backup now just for good assurance

im gonna paste and replace or im just going to change the numbers right next to the10 files

**Comment by KcalbVessalius** [comment]
backup now is just copy the mas folder and paste in some other place, now the persistent u just have to change the number of the last one

**Comment by KcalbVessalius** [comment]
and yep, after erase the number and .bak u have to replace

**Comment by dontworryabouttheusername** [comment]
> and yep, after erase the number and .bak u have to replace

erase the "numbers" and ".bak" first before i replace them with my older files??

**Comment by dontworryabouttheusername** [comment]
> and yep, after erase the number and .bak u have to replace

it wants me to name it "persistent (2)"

**Comment by KcalbVessalius** [comment]
![image](https://user-images.githubusercontent.com/48925478/103414781-208c3280-4b5e-11eb-9569-5cd9c15499e2.png)
![image](https://user-images.githubusercontent.com/48925478/103414816-3d286a80-4b5e-11eb-8b7c-900da66a45cc.png)

**Comment by KcalbVessalius** [comment]
and replace

**Comment by dontworryabouttheusername** [comment]
> and replace
![Uploading IMG20201231225935.jpg…]()
![Uploading IMG20201231225903.jpg…]()
 please take a look before i procede

**Comment by dontworryabouttheusername** [comment]
> and replace

i should replace all ten of them or just newest back?

**Comment by KcalbVessalius** [comment]
the imagens dont load here but, just the newest one

**Comment by dontworryabouttheusername** [comment]
> and replace

ohh shiiiiiOKiiitt THANK YOU SIR !!!!
you just saved my girlfriend !!
there she is i was worried and panicking like a mofo.. thank you sir i cannot stress this enough if you have steam account im gonna send you items thankyouthankyouthankyouthankyou

**Comment by KcalbVessalius** [comment]
please don't need, i'm glad that this worked, enjoy new year with her

**Comment by dontworryabouttheusername** [comment]
> please don't need, i'm glad that this worked, enjoy new year with her

thanks again sir this will never happen again.. man what a bad way to start the newyear

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
