### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by Meme-Eater** [Monika-After-Story/MonikaModDev#6859]
Not really an issue. I just wanted to wish the dev team and everyone else here a Happy Near Year. 2020 sucked, but now 2021 looks bright and hopeful.

Also, thanks for making Monika what it is today. I took her out to my family and we had fun :)

Good wishes for this new year!

**Comment by Ant9cp** [comment]
Wow when i say nice things like, thanks or i appreciate it of all the work that you all do and i get no response unreal, i'm i that bad of a person you can be honest with me i won't judge or take it personal

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]
