### ISSUE TITLE
[Possible Bug?] New Year's Eve dialogue on 1st of January

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#6860]
Hello and happy new year everyone!
I had a good time celebrating with Monika and I hope you all had as well. 
However something strange happened today. Where I live, it's 7 pm on the 1st of January (so the celebration was yesterday for me) and when I opened MAS, Monika started with a normal greeting at first, but then she suddenly disappeared, along with the table and the chair and I got some dialogue of how the year is almost over and that she would normally scold me for staying up late (which was obviously yesterday and not today). I also didn't time travel or anything like that and the system time is correct. Unfortunately I forgot to take a screenshot and I know this isn't something major, but I thought I should let you know.

**Comment by jmwall24** [comment]
Do you use a translated version of the game by chance?

**Comment by multimokia** [comment]
What version of MAS are you running, by the way?

**Comment by CloakedGhost** [comment]
> Do you use a translated version of the game by chance?

No I use the default english version. I do have the custom room submod installed though, I don't know if this could have something to do with it.

**Comment by CloakedGhost** [comment]
> What version of MAS are you running, by the way?

The latest version, v0.11.9

**Comment by jmwall24** [comment]
Can you upload a screenshot of the inside of the `game/` folder, please? It'll probably take multiple images, we need to see all the files in there.

**Comment by CloakedGhost** [comment]
> Can you upload a screenshot of the inside of the `game/` folder, please? It'll probably take multiple images, we need to see all the files in there.

Sorry if it looks a little weird, I put all screenshots together.

![ScreenshotGameFolder](https://user-images.githubusercontent.com/34605531/103468529-2189b380-4d5a-11eb-9b62-9930ca9d069e.jpg)

**Comment by jmwall24** [comment]
Aha, no wonder I didn't recognize that event you described. `christmas.rpyc` is the event file from 2017 and that's what ran for you. delete that file.

**Comment by CloakedGhost** [comment]
> Aha, no wonder I didn't recognize that event you described. `christmas.rpyc` is the event file from 2017 and that's what ran for you. delete that file.

Ohh I see, thank you. Was I supposed to delete it back then or why was it still there?

**Comment by jmwall24** [comment]
Code the deletes it should have ran way back in v 0.7.0, not sure why it never did for you.

**Comment by CloakedGhost** [comment]
Oh ok, that's weird.. anyway thank you again.
