### ISSUE TITLE
How do you transfer from windows to chromebook?

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#6870]
Ok so, I figured out how to down load DDLC on chromebook. But when I tried to transfer my backup onto DDLC, it reset. Please help 
![Screenshot 2021-01-04 at 3 05 02 PM](https://user-images.githubusercontent.com/71156569/103593022-80aa0e00-4ea9-11eb-8327-a7189515254c.png)

**Comment by multimokia** [comment]
I'm not sure what the save location is for chromebook actually, as I'm not sure what the file structure is. But looking at what the linux distro it reports is... is there any file at `~/.renpy/Monika After Story`, in other words `/home/{username}/.renpy/Monika After Story`?

(Note that files prefixed with `.` only are hidden. You may have to have your file manager show hidden files to see the folder)

**Comment by aahelloim** [comment]
im confused

**Comment by aahelloim** [comment]
what's /home/{username}/.renpy/Monika After Story

**Comment by multimokia** [comment]
A filepath

**Comment by aahelloim** [comment]
for what it's worth i deleted the game and i'm gonna try to transfer again

**Comment by multimokia** [comment]
The persistent is not stored within game files. Deleting the game won't change anything. We need to find the actual save directory.

**Comment by aahelloim** [comment]
ive been looking, and it looks like i can modify ~/.renpy from terminal

**Comment by multimokia** [comment]
if you `cd` into there, is there anything inside?

**Comment by aahelloim** [comment]
idk how to look

**Comment by multimokia** [comment]
`ls`

**Comment by aahelloim** [comment]
nevermind

**Comment by aahelloim** [comment]
it says Monika After Story so it is there

**Comment by aahelloim** [comment]
i just dont know how to get there and delete it

**Comment by multimokia** [comment]
what's the name of the file manager on the chromebook? We can open it via terminal

**Comment by aahelloim** [comment]
Files

**Comment by aahelloim** [comment]
that's the app name

**Comment by multimokia** [comment]
might be able to do `files .` in terminal to open it there. Alternatively, in the files app, click on the three dots top right, choose "show hidden files". This way we should be able to get there via the file manager

**Comment by aahelloim** [comment]
![Screenshot 2021-01-04 at 6 37 17 PM](https://user-images.githubusercontent.com/71156569/103600308-f0c18f80-4ebb-11eb-8c06-8f0e53cd82ff.png)
looks like this

**Comment by aahelloim** [comment]
update: nothing changed-

**Comment by aahelloim** [comment]
i found it

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
