### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by chaerithechair** [Monika-After-Story/MonikaModDev#6877]
This is a list of some things that I hope will be added to MAS. It is pretty long, so they definitely do not have to add all of them unless they want to. 

1. Dialogue Topics

1. Hobbies Topic (You could be able to talk about you and Monika’s hobbies)
-Cooking (Unlocked at 200 affection)
-Writing
-Reading
-Gaming
-Drawing

2. Monika’s Childhood
- Who were your friends?
- Did you join any clubs at school?
- What were your favorite books when you were a kid?
- Did you get bullied?

Random Chatter:

Monika will ask things like:

1. What type of food do you like? (The options should be things like breakfast foods, fast food, etc.

2. What kind of music do you like? (The options should be things like pop, rap, rock, jazz, etc)

Affection Events:

1. When you reach 220 affection, Monika will cook you a meal. It would depend on what you chose in suggestion number 1 in the random chatter suggestions.

2.Every 100 affection you get, Monika writes you a poem.
Ex:
At 100 aff she writes you a poem about flowers
At 200 aff she writes you a poem about living in a game
At 300 aff she writes you a poem about how much she loves you
I think it should cap at 1000 or 2000 affection.

Gifts:
1. A painting 

2. A table decoration, like maybe a table runner or a table cloth. (You should be able to toggle them on/off)

3. A plushika

Those are all the suggestions I had. Thanks for reading up to here!

**Comment by ThePotatoGuy** [comment]
large issues with multiple suggestions makes it hard for tracking purposes, so please split them up in the future.

[closing until we look into it]
