### ISSUE TITLE
Giving monika gifts wont work

### ISSUE THREAD

**Issue by dumbydog8** [Monika-After-Story/MonikaModDev#6878]
I've pasted the mod_assets folder into the game folder every time, then after I paste the .gift file that goes along with whatever I am giving her and she can never recognize it. It works with ribbons but I've never been able to have an outfit work with her.

**Comment by ThePotatoGuy** [comment]
check out the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
