### ISSUE TITLE
[Suggestion] Ozymandias - Percy Bysshe Shelley

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#6881]
This is a poem that I've known about for quite some time now, and it's turned out to be quite a favorite of mine. That's why I'd actually like to hear Monika's thoughts on it. It's a short read, and should take no more than a minute

> I met a traveller from an antique land,
> Who said—“Two vast and trunkless legs of stone
> Stand in the desert. . . . Near them, on the sand,
> Half sunk a shattered visage lies, whose frown,
> And wrinkled lip, and sneer of cold command,
> Tell that its sculptor well those passions read
> Which yet survive, stamped on these lifeless things,
> The hand that mocked them, and the heart that fed;
> And on the pedestal, these words appear:
> My name is Ozymandias, King of Kings;
> Look on my Works, ye Mighty, and despair!
> Nothing beside remains. Round the decay
> Of that colossal Wreck, boundless and bare
> The lone and level sands stretch far away.”

I know that this piece (at least to me) doesn't actually seem like anything that would be close to the kind of poetry she's into. Although I do still think it's interesting enough to pique her curiosity. I'm wondering what other people's opinions are on this.

**Comment by AsuraShun** [comment]
Now I'm imagining nitocris trying to suck up to him

**Comment by PiestoGo** [comment]
I love this poem. Would be nice to see it added

**Comment by DankManWithThePlan** [comment]
> Now I'm imagining nitocris trying to suck up to him

Kinda lol'd when I got the reference

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
