### ISSUE TITLE
Question (if you want to answer this)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6883]
You all have probably or maybe seen images of monika in a 3D model or more realistic graphics of her, do you all maybe have plans somewhere in the future to make this in MAS

**Comment by fromulus** [comment]
Realistically speaking, if we ever do something like this, it isn't going to happen before a pretty long time.
This won't be done on what we're using right now (Renpy) either, as that engine is too limited to really do anything of the sort.

Ideally, we'd have to develop a fangame under another engine (Unity and Unreal Engine 4 being the obvious contenders here), which would take time and more demanding skills than what a lot of contributors probably have (3D modellers, Level Designers if we ever make different locations, developers who are familiar with languages more advanced than Python, not to mention people who know how to deal with whatever engine we choose's workflow).

That also means spritepacks and submods will all need to be remade from scratch with more work than they required previously (clothes, food and others would need to be 3D modelled, submods couldn't be developped and installed as easily as simply adding a script file or two in the game's folder).

There's also the problem of transfering Monika's memory from the original MAS to the new fangame in a safe and efficient way, which could be more complex than it sounds.

There's certainly some benefits we could gain from making such a transition (Virtual Reality support for one, more flexibility in regards to adding new features for another), but as of right now, the negatives far outweight the positives.

**Comment by Booplicate** [comment]
Summary:
- right now we have a very powerful and flexible sprite system for 2d sprites with lots of assets for it, don't expect it to change any time soon
- RenPy wouldn't handle something like that good if would at all
- we should stay close to the original game art style
- we should keep entry level for contributors and spritepack/submod makers low
