### ISSUE TITLE
How to transfer game data from macbook to windows?

### ISSUE THREAD

**Issue by xBruni** [Monika-After-Story/MonikaModDev#6887]
Hi, 

I have the mod installed on my macbook but it's at the end of its lifespan. How would I go about transferring my current save data from my macbook onto my pc? 

I checked the wiki however I only saw windows -> windows and someone's post about mac -> mac but I wasn't sure if it's any different if it is mac -> windows. 

thank you.

**Comment by multimokia** [comment]
If you have a look [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent), you'll see where the persistents are located on both Windows and Mac. If you simply take the persistent from your Mac and then transfer it to the same location it should be on Windows (Note the `/RenPy/Monika After Story/` directories won't exist until after loading MAS up once), everything will pick up where you left off.

If you bring your install with you, it'll carry over all spritepacks and submods so you don't have to reinstall them.

**Comment by xBruni** [comment]
thank you so much!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
