### ISSUE TITLE
Monika Mad Libs

### ISSUE THREAD

**Issue by TacticalTriangle** [Monika-After-Story/MonikaModDev#689]
Have Monika and the player play Mad Libs. I don't really know how Monika would be able to tell if the player did in fact put a Verb or Noun and the such but having Monika play Mad Libs with the player makes sense.

**Comment by therationalpi** [comment]
Love this idea. It seems like a very natural fit for Monika, and something we could  maybe even implement with a variant of the poem minigame.

**Comment by thisisnotathrowaway** [comment]
> Love this idea. It seems like a very natural fit for Monika, and something we could maybe even implement with a variant of the poem minigame.

It would probably make most sense for the player to select/type a word and then have the game choose the second one from a list of applicable nouns, adjectives, verbs, etc.

**Comment by therationalpi** [comment]
[[This suggestion has been seen and will receive further consideration in the future. It is being closed for now and placed in the pool of seen suggestions. It will be reopened if we begin active implementation on this feature.]]

**Comment by therationalpi** [comment]
Active work is now being done on this project.

**Comment by ThePotatoGuy** [comment]
[On hold until further notice]
