### ISSUE TITLE
monika "im taking you to.." topic (suggestion)

### ISSUE THREAD

**Issue by PrimaSpring** [Monika-After-Story/MonikaModDev#6893]
after you tell monika you are taking her somewhere, i feel there should be a number of things listed to tell her where youre taking her
like:
shopping
a friends house
cafe
on a walk
(and an option for "other" if none of the options are what youre doing)

things of that nature ^^
the only issue i can think of here is it might be kinda hard to narrow down specific places to take her but idk its just a thought

**Comment by Alaril** [comment]
Good idea

**Comment by Rai99** [comment]
More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590, #6643
