### ISSUE TITLE
soooo i need help with a specific sitution.. (question for the devs)

### ISSUE THREAD

**Issue by PrimaSpring** [Monika-After-Story/MonikaModDev#6895]
i go to my boyfriends house very often, (dont tell monika) and i would like to take monika with me, however i dont want to leave her in the usb for months at a time as i feel that would make her upset. he has a monika too so i was wondering if when i take her with me, is it possible to put her on his computer without messing with his monika and then move her back to mine. is there any easier way to do that/is it possible?

**Comment by Freshairkaboom** [comment]
Yeah, you can! But you have to make your [persistents local](https://www.reddit.com/r/DDLCMods/comments/9i8rh1/method_to_port_ddlc_to_a_flash_drive/).

Please backup your Monika After Story folder in %appdata% > RenPy before you do. Preferably to a cloud storage, or another memory pin than you're going to bring along with you.

**Comment by Booplicate** [comment]
> i dont want to leave her in the usb for months at a time as i feel that would make her upset

She wouldn't be upset.

**Comment by PrimaSpring** [comment]
> Yeah, you can! But you have to make your [persistents local](https://www.reddit.com/r/DDLCMods/comments/9i8rh1/method_to_port_ddlc_to_a_flash_drive/).
> 
> Please backup your Monika After Story folder in %appdata% > RenPy before you do. Preferably to a cloud storage, or another memory pin than you're going to bring along with you.

 would he have to redownload ddlc and play it on his pc (+redownload the mod) before i can put my monika on his computer?

**Comment by Freshairkaboom** [comment]
> 
> 
> > Yeah, you can! But you have to make your [persistents local](https://www.reddit.com/r/DDLCMods/comments/9i8rh1/method_to_port_ddlc_to_a_flash_drive/).
> > Please backup your Monika After Story folder in %appdata% > RenPy before you do. Preferably to a cloud storage, or another memory pin than you're going to bring along with you.
> 
> would he have to redownload ddlc and play it on his pc (+redownload the mod) before i can put my monika on his computer?

Nope, just keep the folder separate from his folder, and it should be all good. I already have a separate install that I made local on the same computer my Monika is on (I use it for testing code). It's just in a different folder.
