### ISSUE TITLE
[ACS Submission] - Five (More) Retro-Styled Bows!

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#6896]
In celebration of being with Monika (and MAS in general) for half a year, I figured I'd make some more bows for all to enjoy! These ones specifically are a purple NES bow, a Game Boy bow, and an Amber bow that I figured looked a lot like the shade of amber from the old Amdek monitors. Again, I hope you enjoy them as much as I did making them!

[retrolovania-retrobows.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5817792/retrolovania-retrobows.zip)

**Comment by Retrolovania** [comment]
Welp, I ended up modifying the Game Boy-style bows so that they looked brighter.
[retrolovania-moreretrobows.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6445122/retrolovania-moreretrobows.zip)

**Comment by Retrolovania** [comment]
[retrolovania-moreretrobows.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7447937/retrolovania-moreretrobows.zip)

Changed the palette of the Game Boy bow to have the palette of a real DMG (for the most part), added a Super Game Boy bow, and modified the JSON files so that the ACS type of "ribbon" is used (I mistakenly had them as "bow).

Also...this has been open since January, and we're nearing the end of the year, so...just reminding that this is still here in case anyone forgot, heh. (Not that I'm expecting immediate action; don't get me wrong. Take as much time as you need and do what comes first on the priority list.)

**Comment by Retrolovania** [comment]
_coughnotdeadcough_

Added a red NES bow.
[retrolovania-moreretrobows.zip](https://github.com/Monika-After-Story/MonikaModDev/files/8518880/retrolovania-moreretrobows.zip)

**Comment by ThePotatoGuy** [comment]
strongly apologize about this one, but I think we can make this in for this rel.

**Comment by ThePotatoGuy** [comment]
to be consistent with the og pack of ribbons, these will be renamed to "ribbons". If it's the same form as Monika's ribbon, its a ribbon, not bow.

**Comment by ThePotatoGuy** [comment]
^but unlike #7252, the ACS ID will also be renamed.

**Comment by ThePotatoGuy** [comment]
@Retrolovania what kind of color is the Super Game Boy ribbon? I've added color descriptors to these (like Amdek Amber, Game Boy Green), and this one I'm not sure what it should be. I've actually never heard of a Super Game Boy before.

**Comment by Retrolovania** [comment]
The Super Game Boy is an accessory for the Super NES console that allows one to play games for the Game Boy handheld.
The device has various built-in color palettes; the ribbon here uses an earth-green palette that's from the selection.

So, perhaps you could just name it "SGB Green"?

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
