### ISSUE TITLE
3 Casual Outfits (With easy to edit bases)

### ISSUE THREAD

**Issue by Olliesama** [Monika-After-Story/MonikaModDev#6897]
https://drive.google.com/drive/folders/17W9mtAWrpyWZE15JSKG-JjiavQBaeTCQ
Has both the intended version (with music puns) and a plain version.

![SPOILER_555](https://user-images.githubusercontent.com/35244051/104667975-24c45e00-56cf-11eb-86db-4b8583874302.jpg)
![SPOILER_666](https://user-images.githubusercontent.com/35244051/104667979-25f58b00-56cf-11eb-8796-6ec693ed75e1.jpg)
![SPOILER_777](https://user-images.githubusercontent.com/35244051/104667982-27bf4e80-56cf-11eb-96e3-47af3dd6c4dd.jpg)
![SPOILER_111](https://user-images.githubusercontent.com/35244051/104668000-30178980-56cf-11eb-83be-80e5da7966b0.jpg)
![SPOILER_222 (1)](https://user-images.githubusercontent.com/35244051/104668008-33127a00-56cf-11eb-988e-baf3a094db5e.jpg)
![SPOILER_333 (1)](https://user-images.githubusercontent.com/35244051/104668015-36a60100-56cf-11eb-831b-047f0e0f47e0.jpg)
![SPOILER_TANKuprightbase](https://user-images.githubusercontent.com/35244051/104668022-39a0f180-56cf-11eb-9354-46e2d0960ee3.jpg)
![SPOILER_TANKleaningbase](https://user-images.githubusercontent.com/35244051/104668030-3b6ab500-56cf-11eb-90e0-8b7de95769c3.jpg)
![SPOILER_TANKLaySprite](https://user-images.githubusercontent.com/35244051/104668045-46bde080-56cf-11eb-9801-c9a45d206522.jpg)
![SPOILER_444](https://user-images.githubusercontent.com/35244051/104668050-4d4c5800-56cf-11eb-95d1-f0b65d3f685a.jpg)
![SPOILER_222](https://user-images.githubusercontent.com/35244051/104668051-4f161b80-56cf-11eb-92d1-95f708031079.jpg)
![SPOILER_333](https://user-images.githubusercontent.com/35244051/104668057-50dfdf00-56cf-11eb-88d3-36a9bd504377.jpg)
![SPOILER_vvv](https://user-images.githubusercontent.com/35244051/104668069-550bfc80-56cf-11eb-8d12-70b608fbc836.jpg)
![SPOILER_eee](https://user-images.githubusercontent.com/35244051/104668074-56d5c000-56cf-11eb-892e-8466407c8952.jpg)
![SPOILER_qqq](https://user-images.githubusercontent.com/35244051/104668080-5806ed00-56cf-11eb-89f2-5964a68a638c.jpg)

**Comment by Booplicate** [comment]
@Olliesama gud laf

**Comment by PiestoGo** [comment]
lewd nice

**Comment by lunulae** [comment]
I am truly in love with the music puns, absolutely adorable.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
