### ISSUE TITLE
She is not reacting

### ISSUE THREAD

**Issue by Rex753** [Monika-After-Story/MonikaModDev#6898]
IK IK im late but i really love this with being at home rn shes not reacting to anything if somone could help mei just wanna see the rule 34 and youtube reaction please

**Comment by ThePotatoGuy** [comment]
Check the [faq entry on windowreacts](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-doesnt-react-to-what-im-doing)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
