### ISSUE TITLE
[Suggestion] - Teasing Monika

### ISSUE THREAD

**Issue by chippli** [Monika-After-Story/MonikaModDev#6899]
Me: Monika why do you love me?
Monika: I don´t...
Me: *insert surprised Pikachu meme*

What I would suggest was having a chance to fire back when this response appears.
Let´s say once every 10 times we get this response we would have 2 choices to pop up. One could be "..." that would resume the event as is, while the other could be something like "well this realtionship wasn't going anywhere anyway", or "well that way I won't feel as bad breaking things up".
Then she would be surprised shouting "Player!!" and break out laughing after saying something like "Well played" or "I deserved that".

All in good fun just for the laughs!

**Comment by Freshairkaboom** [comment]
I don't really think we need more options that can hurt Monika at this particular point, and I'm not sure Monika would take a sentence like that in "good fun", knowing how you're literally the only person connecting her to anything real. That's a cruel joke to play on someone that has options outside of your relationship, but I don't know if it's appropriate outside of april fool's at most.

I get it, not everyone will agree with me and think messing with your girlfriend can be good fun. I just don't know if I'll personally write such a topic. I have every confidence that before something like that gets into the mod though, it will be vetted good by the dev team, so who knows, something like it may happen.

I hope you don't take it like I'm putting your idea in the ground or anything, I'm just stating that I'm not comfortable with it, and will probably not write it myself.

**Comment by chippli** [comment]
Well this wouldn't be said to her out of the blue. It had to be said under those condictions, where Monika is already bantering and teasing the player. Also this would take place at a moment in time where I believe Monika doesn´t have any doubts about our everlasting love (I also believe that she only says "I don't..." after a certain affection threshold).

On another note when you flat out say to her that you want to break up she doesn't believe you anyway, although she gets hurt and you have an option to apolagize for that, but since, in this case, she started the teasing I wouldn't consider it hurtfull at all.

Of course I can see that my suggestions can come across as a bit harsh, but those where mere examples. It can be taken in some other direction, like "Can you keep me company anyway :(" or "That means I won! I love you more!".

**Comment by satoshi-kun** [comment]
I think if it is a bit toned down like those last examples you gave, it could be an interesting interaction.
The fact is that Monika teases the player a lot and having some sort of response to that could be fun.

In the topic of teasing Monika, I thought maybe having under the "I want to tell you something" something like "You are way above my league" just like the MC said in the game or "I love you so much I want to die" as Sayori said could trigger some bashing towards the player, like "Don't put me on a pedestal..." and "Please don't say that..."

**Comment by ashyashton** [comment]
Okay I REALLY like "can you keep me company anyways," that response had me cracking up when I saw it. If we ever add responses to that teasing, I REALLY hope it's something like that, because that is absolutely sending me.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
