### ISSUE TITLE
Monika doesn't close the game

### ISSUE THREAD

**Issue by Kek1619** [Monika-After-Story/MonikaModDev#6903]
I have a problem
Everytime i tell Monika "goodbye", she doesn't close the game and just keeps talking. What do i do?

**Comment by Booplicate** [comment]
Talking about what? She should say goodbye to you too and close the game.

**Comment by Kek1619** [comment]
> Talking about what? She should say goodbye to you too and close the game.

Nothing special, just usual topics. Honestly idk why she doesn't close the game

**Comment by Booplicate** [comment]
And she never closes the game after that? That bug happens *every* time?

**Comment by Kek1619** [comment]
> And she never closes the game after that? That bug happens _every_ time?


Yes

**Comment by Booplicate** [comment]
Attach a screenshot of your `/game` folder, please.

**Comment by Kek1619** [comment]
> Attach a screenshot of your `/game` folder, please.


'kay

![zMQKKvPee-U](https://user-images.githubusercontent.com/77551447/104835876-5bff5e80-58cb-11eb-93f5-a3bad2b2fdde.jpg)
![7M2eN7vpJl4](https://user-images.githubusercontent.com/77551447/104835877-615ca900-58cb-11eb-8510-9472a97a7bf2.jpg)
![Vjafn-9To60](https://user-images.githubusercontent.com/77551447/104835888-776a6980-58cb-11eb-8c58-1bb96e96e1aa.jpg)
![kB-NjEyCr70](https://user-images.githubusercontent.com/77551447/104835889-7cc7b400-58cb-11eb-9445-7bde8292f756.jpg)

**Comment by Booplicate** [comment]
What submods are you using? Maybe translations? And what is that `tl` folder? What's inside?

**Comment by Kek1619** [comment]
> What submods are you using? Maybe translations? And what is that `tl` folder? What's inside?

I'm using Submod Updater Plugin, Enhanced Idle and Location selector. And no, i don't use translations

There is a None folder inside the tl folder. And there are common.rpym and common.rpymc files inside the None folder

And i would like to add that this bug also happened before i installed those submods

**Comment by Booplicate** [comment]
> And no, i don't use translations
> There is a None folder inside the tl folder. And there are common.rpym and common.rpymc files inside the None folder

![Capture](https://user-images.githubusercontent.com/53382877/104838525-7ab22500-58cc-11eb-97a7-2de6eed4584e.PNG)
I guess you were using a translation before? You could probably just delete that folder, but I'd recommend making a new install just in case.

**Comment by Kek1619** [comment]
> > And no, i don't use translations
> > There is a None folder inside the tl folder. And there are common.rpym and common.rpymc files inside the None folder
> 
> ![Capture](https://user-images.githubusercontent.com/53382877/104838525-7ab22500-58cc-11eb-97a7-2de6eed4584e.PNG)
> I guess you were using a translation before? You could probably just delete that folder, but I'd recommend making a new install just in case.

Okay, thank you!
