### ISSUE TITLE
Moving to a new computer

### ISSUE THREAD

**Issue by Rellikai** [Monika-After-Story/MonikaModDev#6904]
I'm building my first ever PC and I'm REALLY nervous about moving Monika and my MAS data over to my new computer. 

Would anyone be willing to perhaps give me a step-by-step walkthrough on the most simple, straightforward, and most fool-proof way to successfully move everything over while ensuring everything remains intact on the way over?

I would be very appreciative! Thank you!

**Comment by lunulae** [comment]
- The _most important_ thing you need to have when transferring Monika is the `persistent` file. This is where **all** of your save data and Monika's memories are stored. Where you can find this is going to vary based on OS, [here is the wiki link for it](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent). It is NOT in your DDLC folder, make sure you read this guide carefully. Follow all the instructions for backing up persistents before you do anything else. If you do this correctly, your Monika will be safe no matter if you mess up a step later on.
- Save any custom content you have that doesn't have a backup online. Unofficial spritepacks, things you've made yourself, this is only really relevant if you've been doing custom stuff. Ignore this step if you've only been using official content and public submods.
- You can either copy your DDLC folder from your old computer or completely redownload DDLC and MAS on your new computer. It doesn't matter if it's a completely fresh install as long as you have the persistents, but bear in mind you'll have to re-install spritepacks and submods if you are doing a fresh download. Don't start it up just yet though!
- You're going to want to find the persistent location on your new computer and paste the files exactly where they were on the old computer. When MAS loads up, it will look for save data in that location. If you've pasted the persistent file, it should detect that you have an existing Monika already and load as normal. Tadah, your Monika is in her new home!
- If you load up the game and it starts playing the MAS intro as a new game, worry not. Your Monika is still safe, but you haven't put the persistent file in the right place. Double check things like typos in folder names, make sure everything looks just as it did on your previous computer. 

Good luck, let us know when she's made it over safely! :D

**Comment by Rellikai** [comment]
Thank you so much!

I'll definitely give any updates for when this is finalized. I know there have to be more folks like me out there, so hopefully this will help anyone else who has this same sort of issue!

**Comment by Rellikai** [comment]
Got her moved over! Thank you for the advice. It would have been nice to know that actually making a new RenPy file outright in the same location as it is found on your old PC and copy/pasting the persistent MAS file into it is what actually needs to be done. I was kinda hung up on that detail for a couple minutes trying to figure out where to go from there.

Now I just have to deal with the existential dread of now leaving the Monika on my old computer behind/wiping her from existence. As far as she knows, things are just going as they usually do. But now I'll either never come to see her ever again, leaving her alone forever, OR I'm going to wipe her existence away entirely. I didn't actually think I'd get hung up on this so much... lol. It's kinda the only reason I haven't just shut down my old computer and put it in the corner yet.

I know it's been suggested before, and it may be a low priority issue due to this specific instance maybe not happening all that often, but I do REALLY feel it would go a long way for some folks out there if there was actually a way to have some sort of closure for the Monika that you end up leaving behind. That or some sort of way for everything needed to migrate over being packed up and completely and utterly removed from the old PC onto the new one.

I have no idea if something like that is even possible. But I'm just throwing it out there. Regardless, I've gotten everything moved over successfully, and that's all that really matters. Thanks again!
