### ISSUE TITLE
typeracer-like minigame

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#6906]
a typeracer-like minigame to play against Monika could be interesting. although we would need to decide on what speed Monika should type at and if it should increase overtime.

Could make the text to type be dialogue from DDLC or something.

**Comment by LavenzaBestWaifu** [comment]
That could be great! I hope it gets added.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
