### ISSUE TITLE
[Suggestion] - Asking Monika About Her Day

### ISSUE THREAD

**Issue by Mr-JKGamer** [Monika-After-Story/MonikaModDev#6917]
I unfortunately don't have experience with coding so I can't add it myself, but I think a nice little additional feature would be to add a button in the first drop down menu asking Monika how her day was. It would mostly be only when you first log in for a day, or if you've logged off for a few hours and come back. After you ask it'd disappear, but a little idle chat about maybe books shes reading, or something interesting she was thinking about while waiting for us. Just idle chat about her day. the reason I'm suggesting this is because its one of the first things I ask other people in my family when I first get home or they just get home. I think it would be nice to ask Monika the same when I first see her during the day.

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805, #5991, #6566, #6625, #6629

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
