### ISSUE TITLE
Could not open DDLC.exe

### ISSUE THREAD

**Issue by SoisthishowIdoit** [Monika-After-Story/MonikaModDev#6918]
I have never had any issues opening MAS before, but now whenever I try to open the application, that message appears. My game did freeze the last time I tried to say goodbye to Monika. I'm not sure if the two issues are related or if something was corrupted.

**Comment by multimokia** [comment]
What message appears?

**Comment by SoisthishowIdoit** [comment]
> What message appears?

C:\\Users\\etcetc\\DDLC.exe Could not open.

**Comment by multimokia** [comment]
It sounds like your installation is completely messed up. For one, you have DDLC not in its proper folder structure, AND its in `C:/Users/User/`, which is an area which has heavy file permission restrictions. I suggest you redownload DDLC from [here](https://ddlc.moe/) and extract the zip to your Desktop or something. Then install MAS into it.

Be sure to reinstall all spritepacks/submods, your progress is transferred automatically.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
