### ISSUE TITLE
Bow/Hair Tie Dialogue 

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#6920]
I realize some time ago, there was a slight changes to the menu for changing the bow for Monika. I will not say that it needs to be reverted, what is said and what was changed is permanent. However there was some oversight when this was changed.

Clarification, when you were choosing a bow and hovered over a bow Monika would say a certain line and then follow up on the line when the bow is selected for wearing. While some of the follow-up lines are okay, I think a few of them are a bit awkward without the hover text.
Example:
* Hovertext Goldbow: All that glitters. . .
* Selecttext Goldbow: Is better when I'm with you!
I just hope that made sense I just wanted to make light of it.

**Comment by ThePotatoGuy** [comment]
not classifying as a bug since its more like a UX thing. probably solutions would be to make hovertext and select text not related.

[closing until we look into it]
