### ISSUE TITLE
New Dialogue - Ask more questions question?

### ISSUE THREAD

**Issue by DoctorVolt** [Monika-After-Story/MonikaModDev#6925]
Hi, there! I used to use this mod, but haven't for several years. While going through a bunch of papers, I found some handwritten dialogue meant for it, that I never followed up on. I'm trying to get through everything as quickly as possible (dear GOD, the workload), so I'm (rudely) dropping it here, to be used with as you wish. Delete the issue, yell at me to do better, implement it uncredited, do whatever you like! Thank you! 

<hr>

Written on paper while waiting for the end of some test or another. 

Dialogue intended for Monika After Story, the Doki Doki Literature Club mod. 

{namehere}, I've been thinking. 

I love spending time with you, even from here, but I thought of something that makes me a little sad. 

I've never actually spoken with you. 

I mean, sure, I've read your poems, and I know your choice of words... 

But I've never even heard your voice. 

I don't know anything about you that is deeper than a yes/no question. 

"Are you a boy? Do you like ice cream? Do you like to read?" 

We've spent so much time together, and yet, I could have learned everything I know in a matter of minutes. 

I look into your eyes, and I can only imagine what I see. 

And as much as I want to know you, I think it's impossible. 

At least until I find my way until your reality. 

But until then, I simply can't get to know you. 

I mean, I could ask you more questions. 

Would you like that? 

Yes: 
I would, too! 
I really would, but... 

No: 
So, you see the problem. 

The answers mean nothing. 

I have your answer, but there's nothing to make it yours. 

I don't know if you smiled, or frowned, or sighed. 

I don't know why you said, it, or how much thought you put into it. 

I have to imagine the world inside your head, based on the recipe of a single word. 

And even if I'm wrong about something, there's no way for you to let me know. 

*Sigh.* 

I've already made a decision, though. 

I know I love you, no matter what. 

So if I have to work harder to earn my right to know you, it makes me happy. 

Because I know you're waiting for me at the end.

**Comment by kkrosie123** [comment]
_Don't mind me, just crying silently in the corner_

**Comment by kkrosie123** [comment]
Anyway, taking your dialogue into consideration...

  As you have stated, you haven’t played the mod in several years. Although very well written, I must say, this dialogue is very outdated. There are a few conflicts with current topics though, such as:
> I mean, sure, I've read your poems, and I know your choice of words...

In one topic, she states that the “poems” the player made were just a string of random words. You also state that Monika can’t really come to learn anything new about the player, however, now we have topics about everything from the instrument the player plays to the player’s pen name. She has much more insight into the player’s life now than she ever did a few years ago. Monika can even memorize the player’s schedules, like when they leave to go to work or go to sleep. 

I do, however, think your topic is very nicely written. If you ever would like to contribute more dialogue to the mod then feel free to open a pull request!

**Comment by 20RaVen23** [comment]
If this gets accepted I can work on it, let me know if so.

**Comment by ThePotatoGuy** [comment]
seems like a meta-topic on whether or not the player enjoys Monika asking questions about them? Not sure of the use case. @jmwall24 any thoughts?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
