### ISSUE TITLE
-(MAS) Zodiac Signs Suggestion-

### ISSUE THREAD

**Issue by Chironex487** [Monika-After-Story/MonikaModDev#6927]
Hello,a suggestion for Monika After Story topics i have is :

Monika is asking you what zodiac sign are you ..like Virgo,Libra,Scorpio and other zodiac signs !
Whatever the player choose Monika will explain and give extra info to the player about every zodiac sign he/she choose...
Like for example..i choose Scorpio it start from 23 Oct and it last in 21 Nov...What planet are Scorpio 
which will be Pluto...and other info like:

-What personality do those born in the Scorpio sign have-
If you follow the name of the sign, the native of the Scorpio sign should be dangerous and vindictive.In reality, he is a faithful and devoted friend. It is characterized by:

-devotion to family and friends;
-tenacity and determination;
-exigency with himself and those around him;
-practical sense at the expense of high ideals;
-attraction to mystery and occultism;
-the tendency to make alliances and keep secrets.

This kind of things Monika will explain and discuss to the player whatever zodiac sign he/she  choose.

**Comment by fromulus** [comment]
While an interesting subject, Monika never really struck me as the type of person to believe in these types of things, so if she were to talk about it, it'd probably have to be from a non-serious perspective, and she'd have to express that while she might find the concept interesting, she doesn't believe it holds that much merit.

If anything, she probably could mention that she'd rather make her own opinion of what you're like by herself, rather than listening to what the stars/birthsigns have to say about it.

**Comment by Chironex487** [comment]
> While an interesting subject, Monika never really struck me as the type of person to believe in these types of things, so if she were to talk about it, it'd probably have to be from a non-serious perspective, and she'd have to express that while she might find the concept interesting, she doesn't believe it holds that much merit.
> 
> If anything, she probably could mention that she'd rather make her own opinion of what you're like by herself, rather than listening to what the s

**Comment by Chironex487** [comment]
> While an interesting subject, Monika never really struck me as the type of person to believe in these types of things, so if she were to talk about it, it'd probably have to be from a non-serious perspective, and she'd have to express that while she might find the concept interesting, she doesn't believe it holds that much merit.
> 
> If anything, she probably could mention that she'd rather make her own opinion of what you're like by herself, rather than listening to what the stars/birthsigns have to say about it.



> While an interesting subject, Monika never really struck me as the type of person to believe in these types of things, so if she were to talk about it, it'd probably have to be from a non-serious perspective, and she'd have to express that while she might find the concept interesting, she doesn't believe it holds that much merit.
> 
> If anything, she probably could mention that she'd rather make her own opinion of what you're like by herself, rather than listening to what the stars/birthsigns have to say about it.

I am sorry but this was on my mind,i know she don't belive in this things but at least i tryed my luck...

**Comment by satoshi-kun** [comment]
On a side note, Monika already knows our zodiac sign just for the fact that she already knows our birthdays.

**Comment by Rai99** [comment]
#3242

**Comment by ThePotatoGuy** [comment]
> While an interesting subject, Monika never really struck me as the type of person to believe in these types of things, so if she were to talk about it, it'd probably have to be from a non-serious perspective, and she'd have to express that while she might find the concept interesting, she doesn't believe it holds that much merit.

FYI for anyone seeing this in the future, this is the exact perspective we would have her take.

[closing as duplicate]
