### ISSUE TITLE
-(Mas) Baking Cupcakes Suggestion-

### ISSUE THREAD

**Issue by ComedianPlay** [Monika-After-Story/MonikaModDev#6928]
Hello, i would like to give one little suggestion. I would like to see like a sort of cupcake baking in Monika After Story mod. It would be like.... interesting... One more thing that you can do with Monika... together

**Comment by AsuraShun** [comment]
Oooh, neat idea, a cooking game

**Comment by ZapThundr** [comment]
That sounds really fun actually. Like a little cooking mini game perhaps similar to cooking mama or something along those lines?

**Comment by ThePotatoGuy** [comment]
A cooking game could be interesting, a game specific to cupcake baking seems out of character.

[closing until we look into it]
