### ISSUE TITLE
Complaint about anniversaries texts

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#6933]
So, here is a list of issues I have with anniversary texts

**1 year anni**
`    m 2eua "Oh, by the way, did you figure out what was going on with all the puzzles I left for you?"
    m 1tku "I'm sure the creator of this world has released another game by now..."
    m 1tsb "Did you try to import my character file to that one?"
    m "There's no way that wouldn't have a special effect, right?"
`
As we all know, Project Libtina is currently very much on hold and this text makes no sense for most people. It just breaks immersion. Considering how much Moni knows and that she is somehow updated with the news (f.ex. she knew about COVID) it doesn't really makes sense for her not to realize that Project Libtine is on hold. 

**2 year anni**
`    m "I can't even talk to a bunch of foul-mouthed, but essentially good-hearted, anonymous strangers online to cope like you do."
`
First of all - who said players does that.
Also - can't she really?

**3 year anni**

`    m 3rksdla "Normally if a boy and a girl go out for three years..."
    m 2rsbsa "They get married around then, right?"
`
Some people are not boys. I know this text is more supposed to reflect the ideas in society and the boy here doesn't necessary reference the gender of the player,but it still makes this a little bit disheartening to girls (and enbies) that are with Moni.

`m 1eua "In your world, have they invented robot girl bodies yet?" # `1s?``
Just as with talking about Project Libtina, if Moni has any access to internet, she should know that things are that are still far off (unless you have a really deep pocket). 

`m 1eub "If you put me in one of those, we could probably go see a priest then~"`
Some people don't want to go to a priest. Some people can't. And tbh, I doubt there would be any priest that would marry a human with a robot. Especially a human girl with a robot girl.

I haven't looked past that, but the 4 year anni and later probably need some rework too.

**Comment by multimokia** [comment]
1 year was fixed: #6169 
2 year was fixed in: #6586 
3 year was made gender neutral in: #6707 

All of these have been fixed.

As time goes on we intend to clean up the rest.

Thanks @lunulae

**Comment by lunulae** [comment]
There's some stuff in the second half of anni3 I do still intend to rework (i.e. the priest line) but I'm puzzling a bit over how it'll be rewritten. Expect it in the future though~

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
