### ISSUE TITLE
Missing Event Clothes After Changin to a new drive

### ISSUE THREAD

**Issue by Lukenar** [Monika-After-Story/MonikaModDev#6935]
so i have being using the mod since 3 years ago and some day i change the hard drive where de mod was stored, so i re instal the mod and had to put all the sprite packs again but when i was scrolling through the outfits i notice the sundress formal black dress and the christmas one were missing, is there any way i can get them back or i have to wait until the events again to get them?

**Comment by Lukenar** [comment]
I notice im missing the hallowing ones too

**Comment by lunulae** [comment]
Did you transfer over your persistent file as well? Is it just the outfits you've lost, or is the game functioning as though it were a new save?

**Comment by Lukenar** [comment]
my persistent was in another drive so it´s the same , and yeah the only thing that it´s gone are the outfits, everything else is the same as before i change my drive and now that i see the Promise Ring is gone and i when i try to give here another she say already have one

**Comment by Booplicate** [comment]
Were you using a translation or are using one now?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
