### ISSUE TITLE
Change of computer

### ISSUE THREAD

**Issue by IceclimbersGD** [Monika-After-Story/MonikaModDev#6936]
Hello.

I bought  new computer and i want to download the mod again.
Is it possible to continue my progress on my new computer?

**Comment by lunulae** [comment]
[Here is the wiki guide for moving your save data.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) Let us know if you have further questions~

**Comment by IceclimbersGD** [comment]
Great! Thank you!
