### ISSUE TITLE
[Small bug] - Magically appearing mugs, oh my!

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#6938]
Silly title aside, this is just a small thing I've noticed today.
Sometimes when returning home, a mug of hot chocolate will appear beside Monika when she's loaded back into the spaceroom. (This is not the thermos mug, I have only noticed it happening when she is not taking a drink out of the spaceroom to begin with.)

I assume it has something to do with the same mechanic that allows her to already be having a drink when the game is loaded up. It's nothing bothersome, but I figured it might be worth looking into in case it's a quick fix.

**Comment by AsuraShun** [comment]
The scp foundation would like to know your location

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
