### ISSUE TITLE
What's supposed to happen at 200 aff pts?

### ISSUE THREAD

**Issue by PiestoGo** [Monika-After-Story/MonikaModDev#6947]
Nothing changed on my end

**Comment by multimokia** [comment]
200 isn't a level which changes anything

**Comment by PiestoGo** [comment]
oh okay cool

**Comment by fromulus** [comment]
And even when you do reach new affection stages, don't expect the game to straight up tell you about it or show it directly to your face.
Most changes are subtle, and I would recommend not looking at your affection level so that you never know when to expect unlocking new stuff anyway.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
