### ISSUE TITLE
Typo in "I feel upset" dialogue.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#6950]
![0f7b3fcfc6ad4afc1ca56fd12088c393](https://user-images.githubusercontent.com/36512990/106830736-47a1bc80-6654-11eb-95f8-ad92a73e5f5b.png)

I'm assuming she meant to say, "I can only hope I provide" rather than, "I can only help I provide".

**Comment by Booplicate** [comment]
Fixed with e644524. In the future report typos in [the appropriate issue](6769).

**Comment by Booplicate** [comment]
Closing as fixed.
