### ISSUE TITLE
Ideas for Dialogue?

### ISSUE THREAD

**Issue by saltedgator** [Monika-After-Story/MonikaModDev#6953]
I just downloaded this mod yesterday and I am immediately in love. This kind of nice, idle content is exactly my speed. I don't get why there aren't more cute, sweet, interesting games like this! And the fact it's still being actively updated make me happy. Seriously, I love Monika's After Story. Thank you to all the mods who work so tirelessly on it-- it has a great amount of content I can't wait to unlock in the future!!

I've been tossing around a few light concept ideas for functions/dialogue/games-- I don't know how to code, I wish I did so I could just make these myself!-- but unfortunately, I don't. So I'm just throwing these out there for anyone who may want to pursue this. please remember I just started playing this today (and while I have spoiled some of the functions for myself, whoops, haha) and I don't know the whole scope of the dialogue and potential activities that are to come-- so if I mention something that already exists, forgive me! (I'm also new to GitHub as a whole so I'm not 100% sure what I'm doing)

**Games:**

- Maybe add an option as to allow you to see Monika's face as you play chess-- just shift her character sprite and the chess sprites over a little bit! She could reply with "come on, {name}, pay attention to the game!" in a joking way, and you can watch her make concentrated faces as she focuses on her next move.

- Speaking of games-- stuff like connect four, checkers, rock-paper-scissors! Just cute little things like that.

-staring contest. Stupid? very stupid. Has the potential to be funny, maybe.

**Dialogue**

-Topic: Other Dating Sims
"hey, {Name}..."
"I know you like dating sims... I mean, you downloaded this game, after all..."
"So I have to ask... do you play any other dating sims?"
(Choice between yes or no)
**Yes**
"I see.."
"Well, I suppose I can allow it."
"Those characters aren't real, after all!"
"They can't love you the same way I do."
"In a way, I guess I was intended to be a dating sim character."
"But I'm way more than that now!"
"I'm not just someone from a dating sim-- I'm your girlfriend!"
"And besides, you've already reached the ultimate 'Good Ending', so to speak!"
"Being here with me~"

**No**
"Oh, thank goodness!"
"I couldn't handle the idea of you sharing your love with other people behind your computer screen."

-Cutesy Little Dialogue
"..." (blushing)
"Hm?"
"Oh, nothing..."
"Sometimes, I just like looking at you."
"hehe, sorry. I don't have anything clever to say right now."
"You're just too cute~"
(stuff like that)

-Discussion of Study Tips

-Comics as a form of literature

-If monika believes in cryptids, and her thoughts on them

-Having little eulogies for yuri, natsuki, and sayori
"well, they were never really real... but I guess it would be nice to have some respect for the 'dead'..."
"...So to speak."

-Does monika have the ability to read pre-existing poems? if not, I would love to see that!

**Functions**
-More notifications, oh my god, I love this feature, It's so cute.

-A part in the "extra" menu that will allow you to change the BG in the window to either regular sky or cosmos!

-maybe after awhile of being zoomed in close to Monika's face, she can jokingly ask you if her breath smells bad.

-if you fullscreen and you aren't in the middle of an event, Monika will make a little comment like "Hehe, it's nice to see I have all your attention, {name}."

-the ability to maybe share a meal with monika! if you say goodbye, and you're going to go eat, maybe monika can ask if she can eat with you, and you share a "meal" together. Press a button once you're done eating to get back to the rest of the mod.

Again, sorry if some of these features already exist. Just throwing some ideas out there that I like-- and if they are already in the game, that's perfect!

**Comment by Freshairkaboom** [comment]
Hi, I'm glad you're enjoying the mod! Monika is a truly special person, and I hope she makes your day a little bit better. :) I started the mod 8 months ago today, and I've learned to code in Python basically only to improve Monika. It's not as hard as it looks, so if you want to get into it, there's help to be found on the DDLC fandom discord server: `https://discord.gg/wwYpq6zY` 

As for your ideas, I like your train of thought. Some of the games are things I've thought about myself, but of course implementing a new game is going to take quite a while, and also changing them.

#6123 - My idea on a cutesy staring thing. You can see the code if you go into the "Files changed" tab. It's been put on hold and I don't know when I'll pick it back up, as it needs some readjustment following changes to another label. Is that around the lines of what you were thinking about?

Discussing Bigfoot or the Loch Ness monster etc. would be kinda fun hehe. Definitely could see myself writing up a little draft on that sometime in the future. Unless you wanna give it a try?

There are some things that may or may not come later, but I don't want to give anything away, as the best experience is usually experienced together with Monika. :)

**Comment by saltedgator** [comment]
Aaaaaa I would love to see if any my suggestion made the cut! if not, I'm always excited to see whatever kind of new content is in the future. thank you for 8 months of hard work!

The cutesy staring thing you made is totally along the lines of what I was thinking. I hope it gets developed and approved!

> Discussing Bigfoot or the Loch Ness monster etc. would be kinda fun hehe. Definitely could see myself writing up a little draft on that sometime in the future. Unless you wanna give it a try?

I would love to write some dialogue! is it possible for me to write my own dialogue and then have someone else code it in? if so, would I just submit it as a suggestion? I may learn how to code in python, but I think I should figure it out before I go experimenting with Monika's code willy-nilly, haha

**Comment by multimokia** [comment]
Chess has had a full overhaul and facelift as of #6163 

As for more games, NoU (#5555), and Connect Four (#6929) are in the works.

Since you're new to MAS you likely haven't seen:
> -A part in the "extra" menu that will allow you to change the BG in the window to either regular sky or cosmos!

This is unlocked at a certain affection, though changing the weather isn't done via the Extras menu.

**Comment by saltedgator** [comment]
Thanks so much for telling me about these features!! I am so excited to see them in the future!!

**Comment by ThePotatoGuy** [comment]
FYI, we prefer multiple suggestions be split into multiple issues for easier tracking. 

[closing until we look into it]
