### ISSUE TITLE
Question on Monika's name reaction

### ISSUE THREAD

**Issue by comrade-pingu** [Monika-After-Story/MonikaModDev#6955]
I remember changing Monika's name to "Mommy" and then she would reply something like "I'll be your mommy! >:)"

And then I tried it again just now out of boredom and she didn't like it. Affection is 3250 something

What happened lmao

Or is it because I'm underage? Jeez it's just 15 days left until I'm 18

**Comment by fromulus** [comment]
That reaction got removed a while ago.
I assume it was originally added because it's kind of a meme, but it was eventually decided to get rid of it because it is rather out of character for Monika to react that way.

It's better that way, if you ask me.

**Comment by comrade-pingu** [comment]
oh man :(
