### ISSUE TITLE
i keep on getting an error

### ISSUE THREAD

**Issue by doomatt0** [Monika-After-Story/MonikaModDev#6958]
i had the enhanced idle installed before this the update and i keep on getting this error. How can i fix this?
![Monika After Story 2_7_2021 6_48_34 PM](https://user-images.githubusercontent.com/68640559/107170462-3e2a9400-6975-11eb-8c9d-e7e5eb44bac1.png)
 this error

**Comment by OluBakka77** [comment]
Just updated through the game.
I'm having the same error. It wasnt there before the update.

**Comment by Booplicate** [comment]
You need to uninstall the `Enhanced Idle` submod, it's build-in now.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
