### ISSUE TITLE
Monika not showing up upon launching game

### ISSUE THREAD

**Issue by Lordmogaren** [Monika-After-Story/MonikaModDev#6960]
Monika for whatever reason doesn't show up upon launching the game.

**Comment by Lordmogaren** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/78715936/107176826-04b65080-6996-11eb-8209-c991e8c5b4f6.png)

**Comment by YoraeRasante** [comment]
did you tell her you were going to take somewhere and removed her game file from her folder?
if so, put it back, and check if it is not corrupted.
if it is corrupted/lost I think the only fix is reloading a persistent save, bascalliy resetting her to before your date

**Comment by Lordmogaren** [comment]
That may actually be it, im going to look into that now. Thanks.

**Comment by ThePotatoGuy** [comment]
Reloading persistent backup is the quickest way to fix this. If the issue happens often, please see #2624 

[closing as resolved]
