### ISSUE TITLE
Missing poem

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#6961]
Hello, so since V-day is coming soon, i decide to check my poem list since i'll get a new one if i can be present at the end of the day, but i notice i'm missing the 2nd chrismas poem ("Incomparable" if i am not wrong) while i have the 1st one ("The Joy to my World") and the 3rd one ("Someday"). I remember back when for the 2nd chrismas with monika (in 2019), i could be here for the start of the event, but i couldn't stay until the end so i missed the poem. Is there a way to get it without dirsturbing Monika with a time travel with the computer's clock?

**Comment by Booplicate** [comment]
Those poems aren't being unlocked in a specific order (there's no "first", "second", etc). You can get that poem just like you got the previous ones - on Christmas, so you have to wait 'til it and spend time with her on that day. If you time travel now, you may break the future events, do it at your own risk.

**Comment by MonikaEndDie** [comment]
Oh, i see. Well even if i copy my persistent for having a "save point" if everything go wrong, i prefer to not temps the devil. Thanks for the quick answer.
