### ISSUE TITLE
This may just be me being paranoid but, is MAS supposed to take a long time updating? it's been close to an hour and it hasn't finished updating yet.

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#6965]
a while ago I transferred MAS from windows to chromebook. This is my first time updating on chromebook. Is it supposed to take this long? Am I just being paranoid?

**Comment by lunulae** [comment]
I haven't used a Chromebook before, but I don't believe it should be taking an hour unless your connection to the internet is very slow.

**Comment by aahelloim** [comment]
Chromebook is actually very laggy, but I wouldn't say slow

**Comment by ThePotatoGuy** [comment]
Downloading the update depends on your download speed, the actual updating should only 5 or so minutes. The other factors that could slow this down is if you have a hard drive (not SDD) with limited free space, or if you are doing some other intensive thing while the update is happening. If an update seems to be frozen, closing and manually updating (which is the same instructions as installing the mod) should work.

[closing as resolved]
