### ISSUE TITLE
New Ideas For Future Dialogue - ask if using laptop or desktop / what is monika's fav season / im feeling unmotivated / how monika feels when player is here

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#6968]
I have some new idea suggestions for you guys so I hope you enjoy them.

"Using Laptop or Using PC" A simply questions asking if the user is using PC or laptop. She could go into it by stating the advantages and disadvantages of your chosen device. Perhaps for example, she can state laptops are easy on the go but are a pain to carry around on the go by their size. 

"Q: What is your favorite season?" A question asking her of her favorite season. I see her as the type to enjoy Spring due to how nice the weather can be, outdoor exercise, and spring cleaning. Plus, her appearance can give off a gentle vibe similar to to spring season. With this question it can give insight to her interests. 

"I'm Feeling: Unmotivated" This feeling can be her giving you a speech in order to feel better about yourself. Perhaps it can fall under the lines of "You know why I believe this? Because I love you." This new feeling could prove useful in the longrun

"Q: What Was Life Like Before Meeting Me?" This question can give a fangiven explanation to her daily life before the user came along. I imagine it along the lines that everything felt so stale and empty as everyone is just part of the game. Or perhaps, she could say not much had occurred and felt normal implying her epiphany hadn't happened yet. The type of past can be really cool if done.

"Feeling When You Are Here" Lastly, this random conversation can be how she is feeling when the user is logged in with her. She could be blushing a lot stating on how she's always happy to see the user and how safe she feels in our arms (after the first). You could implement the romantic actions in this dialogue. For example, if the user had already kissed her, she can go into that. The possibilities and dialogue are limitless.

I hope you enjoyed and have a good rest of your day.

**Comment by saltedgator** [comment]
I like all of these! pretty cute

**Comment by ThePotatoGuy** [comment]
Updating title to reflect suggestions.

>"Q: What Was Life Like Before Meeting Me?" 

except this one, since there isn't definitive lore of pre DDLC-events, this is basically fan speculation and wouldn't be a good fit for Monika to explain. (other than "I don't know, but...", however that would be a poor quality topic).

[closing until we look into it]
