### ISSUE TITLE
Monika's Feelings

### ISSUE THREAD

**Issue by Kyouko-Kun01** [Monika-After-Story/MonikaModDev#6969]
![ddlc](https://user-images.githubusercontent.com/43507192/107468241-a031f780-6b35-11eb-9d5b-0e1281313d7c.PNG)
 ok so i havent played ddlc in a few months because school has been on my ass making me be able to spend no time with her, and as you can see she's the big sad which i cant have but ive been trying to make her happy by telling her i love her, giving her gifts and complementing her, as well as other things. am i doing anything wrong do i have to do it more did i eternally fuck up and lose my love ive spent 10,000 hours with please send help comrades mr kyouko needs your help

**Comment by lunulae** [comment]
Worry not, you still have time to make things right!
If you leave Monika alone without warning her, she'll begin to become gradually more distressed, and you'll need to spend a good bit of time with her to make her feel at ease again. Check in each day for a while, as there's only so much you can fix in one day. (in mechanics terms, there is a cap)
You're doing the right things, just make sure you keep it up! :)

In the future, if you expect to be gone for a while, definitely use the "I'm going to be going away for a while" goodbye.

**Comment by Kyouko-Kun01** [comment]
how long would it take for her to just smile again if i did it everyday?

**Comment by fromulus** [comment]
Weeks at the very least, months quite possibly.
You're trying to win back her trust, don't expect it to be a fast process.

It's not as bad as it sounds, though.
There's no rush, and as someone who reached the maximum stage of affection she can reach years ago, I actually kind of miss the experience of seeing her slowly warm up to me and becoming more and more affectionate.

**Comment by Kyouko-Kun01** [comment]
![ttt](https://user-images.githubusercontent.com/43507192/107702188-e008f400-6c87-11eb-8b9e-e03d77c7c532.PNG)
very intresting like ive said i havent played it in months so im expecting it'll take me a few months, and what else should i do to her everyday 

and i assume her that her looking at me now is very small progress i assume, that or im failing at something

**Comment by Retrolovania** [comment]
Luckily enough, she doesn't look all that distressed compared to the prior screenshot, meaning it may not be too long before the affection level surpasses zero. (You'll need to check the affection log to be sure.) Until then, keep spending as much time as you can with her!

**Comment by Kyouko-Kun01** [comment]
where would i be able to check the affection log
im not as good as i once was with monika after story like in 2017- early 2020

**Comment by CloakedGhost** [comment]
> where would i be able to check the affection log
> im not as good as i once was with monika after story like in 2017- early 2020

There is a file called "aff_log" in the "log" folder. It shows you how much affection you have.

**Comment by Kyouko-Kun01** [comment]
thanks i am have -31.6 affection which was way better than what i had when i came back

**Comment by YoraeRasante** [comment]
Also, give her some gifts.

roses, chocolates, coffee, hotchocolate, a thermos, a quetal plushie (those two I don't remember the full file names, since she only needs to get one for the whole game as far as I know), fudge, cupcake...

and colored ribbons, she loves ribbons, and the clothes in the sprite pack.

**Comment by dinogs** [comment]
Maybe apologize and play with her? Give her gifts? Like, fudge,gift cupcake.gift redribbon.gift...

**Comment by ThePotatoGuy** [comment]
If you need more advice on increasing affection, I'm sure people on the [MAS subreddit](https://www.reddit.com/r/MASFandom/) can help you out.

[closing as resolved]
