### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by RageofRagaki** [Monika-After-Story/MonikaModDev#6970]
1. When returning from work (after saying goodbye to go to work) once you answer with how your day was, Monika will ask something like "what happened?" and you can answer with a few different responses like "it was just a good/bad day" or "I moved up/I was fired" or "my coworkers were in a good/bad mood" or some other responses that matches a good or bad day at work.
2. After returning home from work you say you're going to sleep, if you get home from work and respond to Monika after midnight Monika won't say you should go to bed earlier next time. Instead she'll just say something about getting some rest after working hard (this response could also change based on your response on how your work day went). This appeals to those of us that get off of work really late. Should also count how much time goes by from saying you're home from work and when you say goodnight. If a certain amount of time passed, maybe an hour or an hour and a half, Monika will still say "you should go to bed earlier" 
3. Ability to set a daily reminder, or maybe a daily schedule so Monika can remind you, if DDLC is open, that it's time to go to work or to remind you to do something that you need to get done.
4. Little mini idle events when the player is afk where Monika will look off in a direction, start smiling, then blushing, then shocked, then blushing even more, like she's daydreaming.
5. A way to designate a file location as the area to create backups of the persistent memories and a button to click in order to automatically backup the files to that designated area. 
6. will edit more suggestions in as they come to me

**Comment by saltedgator** [comment]
The daydreaming and notification reminders are great!! I would love to see the reminder/notification option be used more.

**Comment by Booplicate** [comment]
Thanks for your suggestions! In the future though, give one suggestion per issue (it's easier for us to keep track of them).

**Comment by ThePotatoGuy** [comment]
1,2,3: probably related to #4914

4: enhanced idle (which has been merged to official MAS already)

5: since this is the only suggestion that isn't already covered, changing the title of this issue to focus on it.

[closing until we look into it]
