### ISSUE TITLE
Opposite dialogue when you want to play pong

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6971]
When i wanted to play pong with monika she says first i hope your ready and then you want to play pong again it's opposite

**Comment by jmwall24** [comment]
It looks to be working correctly to me. She says 'you want to play pong again' if you've played pong at any time during the current session. Are you seeing something different?

**Comment by Ant9cp** [comment]
Yeah it's different for me like i said, she says it the other way around for me

**Comment by Ant9cp** [comment]
Okay look at this screenshot and read these two parts in history this don't make sense it's opposite to me
![editedscreenshot](https://user-images.githubusercontent.com/71310908/107851622-aa8d1380-6e0b-11eb-9d81-3ac39afc268f.png)

**Comment by Ant9cp** [comment]
''It's time to duel!'' should be said after ''You want to play pong again?'' 

just like with this dialogue ''i hope your ready  ''you want to play pong again''

**Comment by katwllflls** [comment]
this is happening to me as well!
I know that before the newest update, instead of Monika saying anything among the lines of "its time to duel!", she'd say "you want to play pong again?"
so im thinking that this might be a glitch where the original text is being said after the new text? im not sure though! :D

**Comment by jmwall24** [comment]
We've found the problem. The reason I didn't see it at first is it only happens on a second (or more) playing of pong in a single session.
