### ISSUE TITLE
A new suggestion

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6976]
(SPOILER ALERT) 

--------------------------------------------------------------------------------------------------------------------------------------------

Back in 2018 MAS had like the background scenery all in brownish or orange looking, and in the main game, in the ending 

But all of that looked so cool before and i know it probably looked spooky to some people maybe, it was for me too but it actually looks cool you know if you think about it, so why not have like a option in the settings to switch the background
scenery from now to before and you can always change it back of course

**Comment by Retrolovania** [comment]
If you mean the original "space exploding" outdoor background, I believe that was removed because it conflicted with the other weather settings (I can't recall if that is the exact reason, but I do know it was creating issues, which led to its removal).

**Comment by Ant9cp** [comment]
So are there chances of the old outdoor background to be in MAS again?

**Comment by multimokia** [comment]
The old background will not be returning at all. Quoting from #6739,:

> The current issue with this is that the old space background functions a little differently from how MAS weathers have been made.
The space background would, for example, not be usable with any custom backgrounds because the mask is made for the spaceroom windows rather than filling up the whole screen.
>
> Generally, the current dev consensus seems to be that if someone could remake it so that it functioned like the other weathers, it could be added, but that seems like a difficult task.
>
> I suppose it could also be locked to only function in the default spaceroom, but I don't think that's preferable, especially if we plan on implementing decorations later that might alter the windows of the room.
