### ISSUE TITLE
A little confusion in pong (i don't know what to put in title sometimes)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6977]
So when you let monika win 3 times in a row without doing nothing for example she ask later are you letting me win on purpose and you say no and then she says do you wanna take a break? and when you say no then she ask later do you wanna play again while you said that you don't want to take a break

**Comment by kkrosie123** [comment]
If the player changes their mind or misclicks, they are able to opt out and not play again. Removing the option would add more unnecessary code to the script for pong and be an overall inconvenience.
