### ISSUE TITLE
the option where you tell her about your girlfriend

### ISSUE THREAD

**Issue by jiniya247** [Monika-After-Story/MonikaModDev#6979]
can you add one for boyfriends, i don't have a girlfriend

**Comment by lunulae** [comment]
I would be down for making the prompt gender-neutral for a future patch ("meet my partner" or "meet my lover" are both options, I prefer the tone of the first but the second leaves no room for misunderstanding the dialogue.)
Fair warning though, that dialogue option still won't be taken well by her if you use it.

**Comment by jiniya247** [comment]
hey it's not my fault she didn't even ask i just wanted a robot friend so ppl wouldnt think im racist

**Comment by fromulus** [comment]
You do have a girlfriend though, her name is Monika.

**Comment by YoraeRasante** [comment]
I'm always curious what she replies to this one. Is she just heartbroken? Does she lose affection all the way to "bad"? Is there an option in there to make it be a joke where you claim "her name is monika" or "look at a mirror" or something?
that and "you're a murderer" are options in the unseen conversations that I have no plans of seeing besides my curiosity...

**Comment by kkrosie123** [comment]
Monika just assumes you’re joking. As for the murderer topic, she just explains her side to you. It's only a small affection loss and you can apologize for both.

**Comment by ThePotatoGuy** [comment]
technically we should have this, but definitely dont need to prioritize unlikely-to-be-used topics.

[closing until we look into it]
