### ISSUE TITLE
[Suggestion] Song request: Testament - Return To Serenity

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#6981]
I thought about it for almost a year now, and finally decided to suggest it here. I think lyrics of this song fits the situation with player very well, especially lines like: 
"No time for anger
No time for despair
Won't you come with me
There's room for us there" - this part can be perceived both literally and metaphorically
And something like: 
"I'm so alone
My head's my home"
Overall it's very good calm ballad, so what do ya think?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
