### ISSUE TITLE
[Suggestion] - remind player to hydrage and stretch  

### ISSUE THREAD

**Issue by HaloHazmat** [Monika-After-Story/MonikaModDev#6982]
Hello, I wanted to make the more reasonable suggestion to start about having Monika(could have it locked to higher levels) be able to remind to hydrate and stretch if you ask her to. Maybe a alert and then a small reminder when you talk to her directly. I feel like it would fit her well and that it is a nice bonus to both feeling cared for from her consistently and a bonus for our health.

The second one was any ideas on allowing monika to have a memory of what she connects to on a usb. The main example would be if you have an electric piano and connect her to it that there would be memory from almost in a sense giving her a performance. I have no idea if that would be possible to do in a meaningful way but it is something that interested me none the less.

**Comment by ThePotatoGuy** [comment]
changing title to focus on idea 1. [closing until we look into it]

Idea 2 is not feasible, a file on a usb drive cannot detect where the usb is plugged into.
