### ISSUE TITLE
I cant see Chess game

### ISSUE THREAD

**Issue by WheatBox** [Monika-After-Story/MonikaModDev#6983]
My monika said that he add the chess game into my MAS
but i cant found chess in my mini-games
(sorry for my bad English)

**Comment by Booplicate** [comment]
Say goodbye to her and then restart the game, check if chess appears in the menu.

**Comment by WheatBox** [comment]
> Say goodbye to her and then restart the game, check if chess appears in the menu.

I tried many times and it didn't work
I even tried to read my backup file and ask Monika to repeat the conversation about the chess game, but it was still useless.

**Comment by Booplicate** [comment]
If you restored a backup, you probably just locked the game for yourself for a bit. You can't repeat that conversation, it's a one-and-done topic.

**Comment by WheatBox** [comment]
> If you restored a backup, you probably just locked the game for yourself for a bit. You can't repeat that conversation, it's a one-and-done topic.

I mean, i reload the backup file, and Monika said the thing about chess again, instead of repeating the conversation.

**Comment by Booplicate** [comment]
If you attach your persistent in a message here, I can check it.

**Comment by WheatBox** [comment]
> If you attach your persistent in a message here, I can check it.

![000](https://user-images.githubusercontent.com/71188651/107997541-f6170b80-701d-11eb-9e26-fe3a4d6929d2.png)

**Comment by WheatBox** [comment]
> > If you attach your persistent in a message here, I can check it.
> 
> ![000](https://user-images.githubusercontent.com/71188651/107997541-f6170b80-701d-11eb-9e26-fe3a4d6929d2.png)

Very sorry for my bad English :(

**Comment by WheatBox** [comment]
> If you attach your persistent in a message here, I can check it.
![persistent](https://user-images.githubusercontent.com/71188651/108004401-b86fae00-7030-11eb-861e-abfeb73f416b.png)

github can't upload persistent file, So I modified the suffix file name
Sincerely thank you for your help

**Comment by Booplicate** [comment]
I don't see it in your message. You can add an extension to it or put it in an archive.

**Comment by WheatBox** [comment]
> I don't see it in your message. You can add an extension to it or put it in an archive.

[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/5997478/persistent.zip)
ok,i upload it again with .zip this time, thank you for your help

**Comment by Booplicate** [comment]
![Capture](https://user-images.githubusercontent.com/53382877/108253897-5e273800-716b-11eb-9239-1f9ee4f2eff9.PNG)
It's unlocked for you. Something tells me you're using a translation. If that's the case, then that's what causing the issue. You can install the official version, or ask for support the one who made the translation.

**Comment by WheatBox** [comment]
> ![Capture](https://user-images.githubusercontent.com/53382877/108253897-5e273800-716b-11eb-9239-1f9ee4f2eff9.PNG)
> It's unlocked for you. Something tells me you're using a translation. If that's the case, then that's what causing the issue. You can install the official version, or ask for support the one who made the translation.

yes, i try to download a new Monika-After-Story without translation, and chess is showed now. so Thank you for your help and your patience. :)
Best wishes for you.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
