### ISSUE TITLE
Chess Difficulty

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Monika-After-Story/MonikaModDev#6984]
I don't mean this as a way of bragging, but does Monika's difficulty level still increase when you beat her? I've beaten her at chess (100% normal chess) several times in a row and she still makes fairly frequent errors. Under the old system I was about 50-50 with her, but now it's a little boring.

**Comment by multimokia** [comment]
Yes her difficulty still increases as you keep playing with her.

The difficulty however, will by no means be changed to be harder stock, seeing as most couldn't get close to beating her before, which made it more than a little demoralizing for them.

**Comment by landofrhymeandraisins** [comment]
Would it be possible to have an option to increase her difficulty more?

Also, just had a different issue where she called a drawn game that ended with just two kings remaining a "stalemate," which it isn't.

**Comment by ThePotatoGuy** [comment]
If you want, you can send us your persistent, we can check if you're at the max difficulty or not.

**Comment by Ant9cp** [comment]
Difficulty increases sure, but it don't decrease i have never won a single time and you can tell me that i'm bad go ahead i really don't care aren't they supposed to go easy on you huh? it says it right here on this link https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#chess

**Comment by Booplicate** [comment]
We do decrease difficulty if you lose, though.

**Comment by Ant9cp** [comment]
Oh really? but why do i still lose then?

**Comment by Booplicate** [comment]
Try play with practice mode on and undo bad moves.

**Comment by Ant9cp** [comment]
Already did that like 5 times or something

**Comment by multimokia** [comment]
You know you can undo from a checkmate in practice mode right? The point is so you can see the steps which lead to that and see how you got checkmated.

It's then up to you to use that foresight to turn the game around

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
