### ISSUE TITLE
[Suggestion] Reaction on files

### ISSUE THREAD

**Issue by SlavFries** [Monika-After-Story/MonikaModDev#6988]
Hello.
My suggestion is;
When you mod a game with a filee that has something to do with Monika,she'll react something like "(USER)...You modded me in a (Name of the game the "Monika" file is.)" oe something like that.
Hope you will approve it.
Goodbye.

**Comment by fromulus** [comment]
There's no real way to go check into other games' folders without having MAS pass as a spyware, and it's not like merely adding a file that has Monika's name to a game means you successfully modded her into said game.  

Plus, we'd probably need to have her react to the different games you "modded her in" themselves, which is something that has already been rejected a couple times.

**Comment by ThePotatoGuy** [comment]
rejecting for reasons explained by fromulus
