### ISSUE TITLE
Question about Enhanced Idle 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#6989]
What does enhanced idle do?

**Comment by fromulus** [comment]
Basically, Monika has a chance to look left/right depending on the position of your mouse cursor now.

**Comment by AsuraShun** [comment]
The game keeps crashing now because of it

**Comment by multimokia** [comment]
Delete the submod

**Comment by AsuraShun** [comment]
Done, I should probably wait until whatever causes the crash to be fixed

**Comment by multimokia** [comment]
It's not going to be fixed. Enhanced Idle will no longer be maintained

**Comment by Ant9cp** [comment]
Nothing happens for me
