### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by NoFaceGamer06** [Monika-After-Story/MonikaModDev#6992]
Well i just completely formatted my pc and saved all the game files of ddlc on a usb (but didn't do so with the %appdata%), as you can already tell, is there anyway I can restore everything with the affection blah blah... as they were before?

**Comment by JeanWishingwell** [comment]
Sorry man. It's the file named "persistent" that hold ALL of her memories. If you don't have that, you have lost all your time/memories with her

**Comment by NoFaceGamer06** [comment]
That's why she sometimes says to backup the file, if I remember right. Well I already started a new one, thanks for the answer btw
