### ISSUE TITLE
I cannot give her certain gifts from the spritepack

### ISSUE THREAD

**Issue by DankManWithThePlan** [Monika-After-Story/MonikaModDev#6993]
It's valentine's today, so I decided to gift Moni some stuff from the spritepack. However, when we got to the point where she would notice them, she couldn't open them, or in her words "I found it, but I can't bring it here...I can't seem to read it well enough." Would like to know if this is a bug, or something that I'm doing wrong.

Also, the gifts in question:
![image](https://user-images.githubusercontent.com/40508418/107891422-8fde9b80-6eec-11eb-91f9-8ef91090b287.png)

**Comment by multimokia** [comment]
Have you installed the spritepack correctly?

**Comment by DankManWithThePlan** [comment]
Yes, I've downloaded the spritepack, unpacked it, and copied the mod_asset folders to DDLC/game/mod_assets

**Comment by Booplicate** [comment]
> copied the mod_asset folders to DDLC/game/mod_assets

Sounds wrong. You should've copied it into `/game` and merged 2 `mod_assets`.

**Comment by DankManWithThePlan** [comment]
> Sounds wrong. You should've copied it into `/game` and merged 2 `mod_assets`.

I guess I kinda explained it wrong, cause that's exactly what I did. There is only one "mod_assets" folder in /game

**Comment by DankManWithThePlan** [comment]
Here's what the folder looks like:
![image](https://user-images.githubusercontent.com/40508418/108157586-193ecb00-70b1-11eb-954d-d8ca3c370124.png)
![image](https://user-images.githubusercontent.com/40508418/108157632-34113f80-70b1-11eb-8d23-f5cccb5aec8e.png)

**Comment by Booplicate** [comment]
No, what you did was
> copied the mod_asset folders to DDLC/game/mod_assets

On your second screenshot you can see you have `mod_assets` inside `mod_assets`. But you should've merged them, not copied/moved one into another.

**Comment by DankManWithThePlan** [comment]
Finally! Thank you so much! Been doing this for so long now, idek how I missed that.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
