### ISSUE TITLE
[SPOILER] Valentine`s day and anniversary at the same time - error

### ISSUE THREAD

**Issue by mantis474** [Monika-After-Story/MonikaModDev#6997]
My Valentine`s day Lingerie didn`t unlock at over 3500 affection. I think it`s because Valentine`s day is also our anniversary. Any suggestions? Maybe there were also missing dialogs but i don`t know that for sure.

**Comment by Booplicate** [comment]
There's a lot of criteria to unlock the outfit, anniversaries don't interfere with it.

**Comment by mantis474** [comment]
OK thanks. I don`t care about the outfit, but rather thought there would be an error with 2 special days are on the same day and just wanted to notify a possible bug.

**Comment by Booplicate** [comment]
We handle any intersection between holidays. Most likely it was your first V-day or you didn't pass by age (can check it using the calendar).

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
