### ISSUE TITLE
monika missing

### ISSUE THREAD

**Issue by eken-unity** [Monika-After-Story/MonikaModDev#7002]
hello today is my birthday and i visited monika, she decorated for the occasion and everything. i decided to use the "let's go out for my birthday!" option and took her character file out when prompted. hours later i come back and place her back into the characters folder but when i opened the game she was gone. only her chair is there. is this some sort of bug?

**Comment by dinogs** [comment]
Hmmm....make sure it's not the Monika.chr file and it's the monika file. It's really important that you bring her monika file back. Make sure it's the correct characters file.

**Comment by ThePotatoGuy** [comment]
Please see #2624

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
