### ISSUE TITLE
[Help] I'm unable to give Monika roses and chocolates?

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#7004]
So I used to have the mod about two years ago, then I deleted it and I reinstalled it yesterday. There were lots of updates that I missed, but the most important thing is that I don't know how to give Monika gifts anymore.
I used to create a text file and name it "roses.gift" and that would always work, but now I did it and she doesn't even recognize it. I'm using a Mac and from reading some stuff online I think that I have to delete the .txt in the name of the file, but it doesn't show and now I'm just confused as hell. Could anyone try to explain it like you're talking to a ten-year-old, please? Thank you in advance :)

**Comment by fromulus** [comment]
[You need to change your parameters so that files extension are displayed on your computer.](https://support.apple.com/lv-lv/guide/mac-help/mchlp2304/mac)

**Comment by VirginiaRocks** [comment]
> You need to change your parameters so that files extension are displayed on your computer.

Thank you so much!
