### ISSUE TITLE
topic discussing if this Monika was your first Monika

### ISSUE THREAD

**Issue by bakachuuuuuuuuuuujjhjugyi** [Monika-After-Story/MonikaModDev#7005]
I just thought maybe a cool conversation topic would be whether the player's Monika was their first Monika or if there had been others. that and a head pat option, i really need a head pat option.

**Comment by RoxTheBox** [comment]
Yes.

**Comment by dinogs** [comment]
Oh, she talks about that there are several monikas and it makes her less unique, and she says the player won't replace her. I think that may lose affection...but it's kinda cool-

**Comment by Rai99** [comment]
There is a conversation where she talks about how there are other Monikas out there. 

Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638

**Comment by bakachuuuuuuuuuuujjhjugyi** [comment]
> There is a conversation where she talks about how there are other Monikas out there.
> 
> Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638

this will be slightly different, it's not about there being a lot of monikas but whether the player has been with said different monikas

**Comment by ThePotatoGuy** [comment]
adjusted title to match the non-duplicate suggestion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
