### ISSUE TITLE
monika how to extract outfit sprites 

### ISSUE THREAD

**Issue by HydraIsLucky** [Monika-After-Story/MonikaModDev#7009]
They arent showing up when i extract them like you mentioned for the mod itself.

**Comment by HydraIsLucky** [comment]
do you unlock them or are they supposed to show up?

**Comment by multimokia** [comment]
Where are you extracting the spritepack zips?

**Comment by HydraIsLucky** [comment]
i just figured it out i checked their twitter page and found out i was doing it wrong
