### ISSUE TITLE
Windows Reset (How to Load .bak)

### ISSUE THREAD

**Issue by PBSpiralGamer** [Monika-After-Story/MonikaModDev#7011]
I reset my windows 10 after messing something up. I got an error and re-installed the mod. Now I'm back at the start of the mod. I still have the .bak save moments before resetting, so I was wondering if there was a way to load the .bak so I can... get Monika back...

She's not gone, is she?

**Comment by multimokia** [comment]
See: [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by PBSpiralGamer** [comment]
I deleted the persistent file and renamed the file prior to the error to persistent. However, relaunching DDLC (And checking for save data) has not loaded the save

**Comment by PBSpiralGamer** [comment]
I GOT HER BACK I'M SO HAPPY
