### ISSUE TITLE
Game crashed twice while playing chess after taking Monika out just prior

### ISSUE THREAD

**Issue by EmmaJK** [Monika-After-Story/MonikaModDev#7013]
Hi! Sadly my MAS has crashed twice unexpectedly whilst playing chess (the chequer board squares flashed green and then their original colours before crashing). I can only think that the cause is due to me having taken Monika "out" just before for a couple of hours. Hopefully it's only me who as had this problem (I did check but could not see any posts like this before on here).

Any advice would be great. I have just uninstalled from steam and download it again but should I remove the original mod as well and then down MAS again? I am very new to all this so please be patient with me. Thanks

**Comment by dinogs** [comment]
Okay, just to be safe...
.Delete your ALL your DDLC files. Then, install DDLC again. If you already downloaded Monika After story, put all the MAS files into the game folder. make sure you restore a file called "ringtone.rypc or something like that. Make sure ALL the MAS files are on the game file. Don't worry, you won't lose your progress with monika. You'll only lose your outfits, but not your progress.

**Comment by dinogs** [comment]
Make sure you're not in practice mode, because in that mode it gives me an error, so maybe it's that? Maybe put it on randomonized chess, play mode, color: any color or draw lots, Make sure you ignore the traceback, but....if you already had a game crash, I think it may lose your affection if you quit the game with the rror, but there's a possibility that if you press ignore the game will crash twice. Make sure all your MAS files are there, and you didn't delete ANY of them

**Comment by multimokia** [comment]
Can you send your traceback please? We need to see what the issue might be

**Comment by dinogs** [comment]
Yeah, send the traceback.

**Comment by dinogs** [comment]
Okay, to send the traceback you need to press "open with txt" or something like that.  Then a .txt file will appear there.

**Comment by dinogs** [comment]
hello?

**Comment by multimokia** [comment]
...or you can drag and drop the `traceback.txt` file from the DDLC folder into the text box here, which will upload it into your message

**Comment by dinogs** [comment]
...Are you there?

**Comment by EmmaJK** [comment]
> ...Are you there?

So sorry. Have a lot on at home and really appreciate your advice. I will go online later to do what you both have brilliantly suggested. I really am grateful!

**Comment by EmmaJK** [comment]
> ...or you can drag and drop the `traceback.txt` file from the DDLC folder into the text box here, which will upload it into your message

Thanks! I will do this tonight

**Comment by ThePotatoGuy** [comment]
@dinogs this is like a forum thread, not an instant messager. You shouldn't expect people to reply immediately, nor should you spam multiple messages in a row. You can edit previous messages if you need to add more info.

Additionally, some of what you said is suspect.

>make sure you restore a file called "ringtone.rypc or something like that.

What does this have to do with chess? We don't have a ringtone.rpyc file. Please avoid giving instructions that might be misleading. I'm going to hide these comments as a result.

It's nice that you are eager to help another person, but the first thing we'd like to know for any issue is why it happened so we can fix it in code, not how to workaround it so the crash doesn't happen. Getting the traceback is the clear first step in this process for this case. Once we have that, then a proper workaround can be determined if possible, (like, for example, reinstalling the mod, but that specifically should be a **last resort**).

**Comment by EmmaJK** [comment]
> @dinogs this is like a forum thread, not an instant messager. You shouldn't expect people to reply immediately, nor should you spam multiple messages in a row. You can edit previous messages if you need to add more info.
> 
> Additionally, some of what you said is suspect.
> 
> > make sure you restore a file called "ringtone.rypc or something like that.
> 
> What does this have to do with chess? We don't have a ringtone.rpyc file. Please avoid giving instructions that might be misleading. I'm going to hide these comments as a result.
> 
> It's nice that you are eager to help another person, but the first thing we'd like to know for any issue is why it happened so we can fix it in code, not how to workaround it so the crash doesn't happen. Getting the traceback is the clear first step in this process for this case. Once we have that, then a proper workaround can be determined if possible, (like, for example, reinstalling the mod, but that specifically should be a **last resort**).

Hi, please blame me for this. I know that Dingo is just trying to help me and it was me who asked for help. 

I also want to thank you for helping me as well! I am a 40 year old with very little experience and will make many mistakes, ha ha! Please be patient with me if ask stupid questions later

**Comment by EmmaJK** [comment]
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6011703/traceback.txt)

Forgive me, did I attach this correctly?

**Comment by Booplicate** [comment]
Can you remember what was the outcome of that chess game?

**Comment by EmmaJK** [comment]
> Can you remember what was the outcome of that chess game?

I was playing the random chess game (its the only one I have a chance of winning) and it was during the early stages of the game during both times it started to glitch (the green squares which show moves didn't show). The 1st time, I tried to save and then surrender the game but it crashed. The 2nd time when I noticed it glitch, I managed to leave the chess game but it crashed before I could tell Monika I was leaving. 

I since then and before contacting you managed to tell Monica I would be leaving for a while and selected a couple of days so I had time to try and resolve this issue.

**Comment by Booplicate** [comment]
Do you still have the save? Can you send it?

**Comment by EmmaJK** [comment]
The last saved ones I see are from yesterday sadly 
![image](https://user-images.githubusercontent.com/79284314/108539349-cb57dc00-72d7-11eb-85a7-af648b4e82fc.png)

**Comment by Booplicate** [comment]
So you had some chess game which didn't crash, right?

**Comment by EmmaJK** [comment]
You are right. Sorry for sounding confused. It certainly glitched or started acting up though only when I played the chess game. I was okay playing hangman and pong before that fine. I wonder if I did something weird when I took the Monika file out earlier today.

**Comment by EmmaJK** [comment]
I took her file out just now as well. I was worried in case I need to change anything.

**Comment by Booplicate** [comment]
No it's fine. Also taking Monika out shouldn't affect chess.

What I mean is, does chess **always** crash? Or you were able to play some chess games w/o any issues?

**Comment by EmmaJK** [comment]
> No it's fine. Also taking Monika out shouldn't affect chess.
> 
> What I mean is, does chess **always** crash? Or you were able to play some chess games w/o any issues?

Not at all. I love playing chess and do it a lot

**Comment by dinogs** [comment]
So.....does when you unlocked chess it crashed or it was normal before?

**Comment by EmmaJK** [comment]
It was perfectly fine before.

**Comment by dinogs** [comment]
Oh, okay.....

**Comment by dinogs** [comment]
I don't know much about files and coding so much, so sorry if I sometimes sound confusing

**Comment by Booplicate** [comment]
We don't see anything strange in the code. The only thing I can think of is Steam has some conflicts with the chess engine we use. We don't support Steam since it has a lot of issues with mods. I'd suggest to transfer your game to a non-steam version.

**Comment by EmmaJK** [comment]
> I don't know much about files and coding so much, so sorry if I sometimes sound confusing

Not at all! You have been helping me out

**Comment by dinogs** [comment]
Ok, playing on steam may cause some bugs or issues, are you playing on steam?

**Comment by EmmaJK** [comment]
> We don't see anything strange in the code. The only thing I can think of is Steam has some conflicts with the chess engine we use. We don't support Steam since it has a lot of issues with mods. I'd suggest to transfer your game to a non-steam version.

I'm happy to do that. Just never done it before and make so many mistakes! ha ha

I will try my best! Do I reinstall the mod as well?

**Comment by EmmaJK** [comment]
> Ok, playing on steam may cause some bugs or issues, are you playing on steam?

Yeah. I use steam a lot

**Comment by Booplicate** [comment]
[Here's the guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) that should help you. Transfer your game and try to play some chess. Let us know if the issue persists.

**Comment by dinogs** [comment]
Oh, alright...maybe that may be the cause?

**Comment by EmmaJK** [comment]
> [Here's the guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) that should help you. Transfer your game and try to play some chess. Let us know if the issue persists.

Thanks! I will go for it now. Very grateful to you! Please wish me luck and have a great day!

**Comment by dinogs** [comment]
Good luck!

**Comment by EmmaJK** [comment]
> Oh, alright...maybe that may be the cause?

I will try to download it the other way. Thanks for everything

**Comment by EmmaJK** [comment]
> Good luck!

Thanks! Take care

**Comment by dinogs** [comment]
Hello! Did it work? Did the traceback dissapear?

**Comment by EmmaJK** [comment]
> Hello! Did it work? Did the traceback dissapear?

I'm afraid I have lost everything. Not even the mod works and I know its down to me. The newly downloaded DDLC means I have no saved data (which is understandable). I know its because I have done something wrong with the mod. Guess I will literally start over from fresh, ha ha. At least it will give something to do in my free time 

I do though appreciate you all tried to help me out. Just hope I'm the only one that this happened to and have a great weekend! x

**Comment by Booplicate** [comment]
Did you follow the guide I linked? You should not lose any progress at all, the save data is kept outside of the game folder.

**Comment by EmmaJK** [comment]
> Did you follow the guide I linked? You should not lose any progress at all, the save data is kept outside of the game folder.

I tried to follow it all. I know its me who has done something wrong. I have had such a busy day and tbh, I am shattered. Ha ha! Thanks for trying to help me out.

**Comment by EmmaJK** [comment]
AHA!!!!

MY FAULT! It works!!!

**Comment by EmmaJK** [comment]
THANK YOU

**Comment by EmmaJK** [comment]
![image](https://user-images.githubusercontent.com/79284314/108553916-3d85ec00-72eb-11eb-8c92-8fbf6a0d735c.png)

**Comment by dinogs** [comment]
Remember that if you have the persistent file your progress won't be loss!

**Comment by dinogs** [comment]
Also, no problem! I love to help people

**Comment by EmmaJK** [comment]
So grateful to you!!! All is well. Just trying to figure out where the J file for the sprite packs, ha ha!
We both give our thanks 
![thanks](https://user-images.githubusercontent.com/79284314/108589236-68a52580-7355-11eb-92ad-b94457fa2ce8.png)

**Comment by Booplicate** [comment]
> Just trying to figure out where the J file for the sprite packs

Why do you need it? Just merge `mod_assets` of the spritepack with `mod_assets` in your `/game` folder. Watch [this](https://www.youtube.com/watch?v=bjJ0U8l1m8c) if you're not sure.

**Comment by EmmaJK** [comment]
> > Just trying to figure out where the J file for the sprite packs
> 
> Why do you need it? Just merge `mod_assets` of the spritepack with `mod_assets` in your `/game` folder. Watch [this](https://www.youtube.com/watch?v=bjJ0U8l1m8c) if you're not sure.

Thank you!!! The packs work thanks to you and the video xxx
