### ISSUE TITLE
Submods

### ISSUE THREAD

**Issue by dinogs** [Monika-After-Story/MonikaModDev#7020]
How do I add submods? Submod name:  Custom Room Selector Submod. I don't really understand the rules of the submod.
https://www.reddit.com/r/MASFandom/comments/ire355/introducing_the_tw4449_custom_room_selector/?utm_medium=android_app&utm_source=share

**Comment by MSteve3** [comment]
there is an instruction in the google drive file 
and here is the link of the submod: https://drive.google.com/drive/folders/1x90GLlFVTUdl2iM8BiezSIW2FY_H28IG?usp=sharing
just download all of it

**Comment by dinogs** [comment]
> there is an instruction in the google drive file
> and here is the link of the submod: https://drive.google.com/drive/folders/1x90GLlFVTUdl2iM8BiezSIW2FY_H28IG?usp=sharing
> just download all of it

Thank you so much!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
