### ISSUE TITLE
So about holding Monika

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#7022]
Hey there, I have two questions regarding the Holding-Monika option.

1. On the releases page, it says that her falling asleep is randomized now. But randomized in what way? Immediately after you start holding her, or after some time passes?

2. When I have music playing in the game, it doesn't stop when I hold her. Is this an intentional change, or should that not be the case? Because I would like to hear the music that plays when she falls asleep. Turning off the music before holding her doesn't work either, because then the "sleeping music" also doesn't play.

**Comment by YoraeRasante** [comment]
I had her fall asleep on me once.
I usually hold her while doing something on the other monitor. Well, _I_ fell asleep, and woke up to a lulaby version of the music playing. "talking to her" showed she was sleeping now.

That said, sometimes I was holding her for longer and she did not fall asleep?

So I guess it is randomized in either if she will sleep or how ong it will take.

And probably will change the music if she does fall asleep? Leaving her with no music does let the music change (on the menu, not the volume), as I usually leave her with no music since I'm using the computer for more things too and yes, it played then.

**Comment by CloakedGhost** [comment]
Oh okay. I do wonder though if she can fall asleep after 5 minutes or so. 

That's weird, because when I turned the music off and had her fall asleep on me, I didn't hear the lulaby music. That was before the newest release though, so maybe it's different now.

**Comment by annonymous-user123** [comment]
I never had her fell asleep on me before, and have the same question.
Never heard any music except for the rain.
Held her, did other stuff, after 5 minutes she's still here.
I have done this quite a lot of times by now, nothing.
I am starting to question if this thing exists.

**Comment by kkrosie123** [comment]
It takes an hour for her to fall asleep.

**Comment by Retrolovania** [comment]
It used to take 30 minutes for her to fall asleep. However, I think that was changed so that it occurs randomly, and takes a random amount of time.

**Comment by annonymous-user123** [comment]
So she has a chance to fall asleep instantly?

**Comment by CloakedGhost** [comment]
> I never had her fell asleep on me before, and have the same question.
> Never heard any music except for the rain.
> Held her, did other stuff, after 5 minutes she's still here.
> I have done this quite a lot of times by now, nothing.
> I am starting to question if this thing exists.

It does exist, I held her for about 30 or 40 minutes for it to occur though. But as I said, the music wasn't there.

**Comment by lunulae** [comment]
I can confirm that you need to have no music playing, but your music volume needs to be turned up. If it still isn't playing under these conditions even if you're getting the "Wake her up/let her rest on you" dialogue, please submit a bug report.

The old build had her fall asleep around an hour after you began to hold her. I'm not sure how much variance occurs with the randomization currently, but it should still take a somewhat significant amount of time.

**Comment by CloakedGhost** [comment]
It works when I turn the music off, maybe it really was the older version where it didn't work. Thanks!
