### ISSUE TITLE
[Bug?] NES-styled bows aren't considered as bows in 'monika_ribbon'.

### ISSUE THREAD

**Issue by MrVavlo** [Monika-After-Story/MonikaModDev#7023]
_"What do you mean I'm already wearing it? It's not a ribbon."_ - Monika, probably.
![unknown](https://user-images.githubusercontent.com/34880333/108624236-bc4a6880-7454-11eb-9f2c-3fd9f89f0af4.png)

I see in `.json` files that all those 3 bows have a "ribbon' type, but this topic claims that Moni doesn't wear anything.

**Comment by Retrolovania** [comment]
That’s....odd. I’ve never seen this happen before. I wonder what’s causing this...

**Comment by Retrolovania** [comment]
Come to think of it, I recall her mistaking one outfit for another shortly after the latest update was released. Is it possible something in the update caused the outfit system to go awry?

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
