### ISSUE TITLE
Missing J file

### ISSUE THREAD

**Issue by EmmaJK** [Monika-After-Story/MonikaModDev#7028]
Hello. I have no J file in my game files under Mod Asset>Monica. To ensure it was not just me, being silly  I checked with others before asking you  on reddit and they confirmed that I didn't have a J file. I have  downloaded DDLC from the moe website again and redownloaded the MAS mod as well - sadly, no j file again.

The only Json file I found was under lib>pythonlib2.7. I don't think this is the j file though.

I was then advised to just create a new folder under Mod Asset>Monica and call it 'j' - this has not worked either.

It's not a serious problem or anything - it just means I cannot use the sprite packs. If you could ensure others know what to do about a missing j file, that would be great though. 

Thanks! I have put in screen shots in case I was not being clear. 

![missing j file](https://user-images.githubusercontent.com/79284314/108687335-848fff00-74ee-11eb-8e23-5e0e32653b28.png)
![is this it](https://user-images.githubusercontent.com/79284314/108687339-85c12c00-74ee-11eb-89bd-d0241c7dfc8f.png)

**Comment by Booplicate** [comment]
You get that folder from spritepacks. It doesn't prevent you from using them.

**Comment by lunulae** [comment]
The vanilla mod doesn't come packaged with this folder, it's intended to be created when you merge the intended folders in each spritepack with the mod.
If it's not being created when you merge the folders, you might be installing your spritepacks incorrectly.

**Comment by EmmaJK** [comment]
Thank you for the advice. I have created a j file and will try to find out why I haven't installed the packs correctly. Thank you.
