### ISSUE TITLE
Add "Closet" for changing Monika's outfit and hair

### ISSUE THREAD

**Issue by therationalpi** [Monika-After-Story/MonikaModDev#703]
This is a major new feature. With all of the new art available to us, we need a good system for swapping monika's clothes and hairstyles. This should probably be introduced via some major in-game event, and it needs some UI to handle it.

This is in the early conceptual stages, so fresh ideas on how to do this are appreciated.

**Comment by M4R10zM0113R** [comment]
Might be meta introducing it as a new game feature using her, much like how one of the introductory dialogues is <knocking door/opening door>. (Maybe a metacomentary on additions later on? Something in the likes of how she used the "console" on the main game?)
Maybe a scene change for the UI to take place? The UI could go like poemgame, but rather than picking a set of words, would be picking the tags to the clothing (to categorize it). (Specific choices could go about with either being "loyal" to the core game with the selection, or starting to branch away from it with something ironically fitting the game's theme.)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I think it should not be available from the get-go but rather be unlocked in a random topic.
Same with the clothing.

**Comment by PopeAesthetics** [comment]
I believe this would be easy enough to bring in through a game play perspective,

Have Monika ask the player if they remember how she previously requested people to draw and send her new clothes. Then she tells the player how some talented people were nice enough to draw her some, and then have her explain the function of the new closet button. Perhaps have her make a tongue in cheek remark on how she left out the more lewd stuff for when the relationship is further down the road, as is common in other conversations. 

However I am in no way capable of helping any with the coding or artwork. I deliver pizzas for a living so I am sadly no where near the level of skill some of you possess.

**Comment by XavierDD1st** [comment]
I could do the coding when I have free time.

**Comment by fitzmill** [comment]
Would it also be a good idea to have her change into a different outfit every day? So if the day changes between two times when the game is launched she will appear in a different outfit from the day before.

**Comment by GoldTheEevee** [comment]
i would just like to put this out there but we are only talking clothes so we should talk just a bit more hair like the title. we have idea's for clothing but not for hair. we could problem use Yuri's Natsuki's and Sayori's hair but that's about it. could we take idea's from like huniepop and change them?

**Comment by therationalpi** [comment]
![hairstyles_2](https://user-images.githubusercontent.com/8276005/34998375-e8e48e22-faac-11e7-8388-e5f79e22c9f7.png)
There are actually several hairstyles that Ryuse has drawn up for us to use!

**Comment by KydonShadow** [comment]
I love this idea, personally. I don't have much coding experience so I guess this comment is only going to be morally supportive, but it feels like the aim of this mod is to bring Monika into our reality, sort of. Adding stuff like this would greatly personalize her, and make her feel more real. (The hair styles would be an awesome idea too!)

**Comment by queue5** [comment]
Someone should make a Cyborg-Monika skin in reference to the game grumps playthrough. I think it would be hilarious.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Damn those hairstyles look weird on Monika :/ (Especially the ones that change her wig).
Maybe it's just me but some of them make her seem like a completely different character archetype. Not that I mind.

**Comment by fitzmill** [comment]
If we wanted to start with hair, we first need to separate Monika's torso and head from her hair. I'm not sure if an artist is available that could do this for us. Can anyone help me out?

**Comment by thefreightrain** [comment]
I'm new but I'd be happy to help out, if that's all right. For sake of clarification, it is just the desk poses that need to be worked on at present, right? (I'd also be willing to help out with clothing as well, of course.)

**Comment by fitzmill** [comment]
Yes, mainly we just need [torso.png](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/mod_assets/monika/torso.png) and [torso-n.png](https://github.com/Backdash/MonikaModDev/blob/master/Monika%20After%20Story/game/mod_assets/monika/torso-n.png) to be separated into to photos each. One with the body and head, the other with just the hair.

**Comment by PlayerPi** [comment]
I think part of the appeal of Monika is the idea that she is always doing something in the background. Like she's alive trapped in your computer. With lines pointing to that idea as she comments on other files or guesses what's been going on. 

With that point across i feel like her just saying "Hey look what i got" it would be better with "hey look what i made/found.' and asks for the players approval. If no maybe she wont bring it up again (less Prompted) or something new is added. 

I like the idea of changing daily. I would add having her comment on the new outfit every time its premiered and having premiers on random days to help the aforementioned illusion. Maybe even having her randomly select a favorite she will more often go to.

**Comment by thefreightrain** [comment]
So I have the hair and head/torso split, with some additional fixes to the latter segment for sake of completeness.
![hair](https://user-images.githubusercontent.com/36119212/36068319-345f1d50-0e98-11e8-9caf-972718957cbe.png)
![torso](https://user-images.githubusercontent.com/36119212/36068320-3ba2b8a6-0e98-11e8-9aef-c5838ea32ecb.png)
![hair-n](https://user-images.githubusercontent.com/36119212/36068321-3e92c11e-0e98-11e8-95ac-aa3f4c37536e.png)
![torso-n](https://user-images.githubusercontent.com/36119212/36068322-4012d68c-0e98-11e8-8d57-c60bd1747f55.png)
Additionally, it might be prudent to split the hair into a few layers, both to allow for combinations and to prevent an overlay of hair going down the back to end up in front of any other clothes options in the future. I already have the current hair split into three layers (front, ribbon/hairpin accessory, and back), so it wouldn't be much work to finish and upload those instead if that ends up the way she goes.

Other than that, I'm exploring creating an alternative torso base shorter length clothes might be able to be placed on top of. Alternatively, I could switch gears and try and create a selection of hair, that might be more immediately useful anyways.

**Comment by fitzmill** [comment]
Nice! And I think that splitting up the parts of the hair might be cool. In fact, could you either get me a few different colors of ribbons or a few different hairstyles to test with? That way I can see if things are working correctly. Also I don't think it's necessary to create an outline for the head but that's just my opinion.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we start this]

**Comment by ThePotatoGuy** [comment]
Atm, new hairstyles / clothes are being implemented in a slow release fashion, where we introduce a single hair style or clothing item via a greeting or some sort and allow for ask a question to change the styles.

A wardrobe /closet option is simply too much like a Dress Up Game and not so much realistic in terms of monika as a person.

I think we're going to drop the wardrobe idea and instead randomize clothing / hair.

**Comment by ThePotatoGuy** [comment]
This is now in progress loool
