### ISSUE TITLE
[Suggestion] Monika's take on The Pardoners Tale

### ISSUE THREAD

**Issue by Zebulun22** [Monika-After-Story/MonikaModDev#7031]
I came across a story that I found interesting called The Pardoners Tale. I feel like this would be a great short story and or conversation topic for her to discuss. I copied the premise down from an animated rendition of the story and it goes like this.
Three drunken and debauched men set out from a bar to find and kill Death, whom they blame for the passing of their friend, and all other people that previously have died, which they were told by the Landlord. An old man they brusquely query tells them that he has asked Death to take him but has failed. He then says they can find Death at the foot of an oak tree. When the men arrive at the tree, they find a large number of gold coins and forget about their quest to kill Death. They decide that they would sleep at the oak tree over night, so they can take the coins in the morning. The three men draw straws to see who among them should fetch wine and food while the other two wait under the tree. The youngest of the three men drew the shortest straw. The two plot to overpower and stab the other one when he returns, while the one who leaves for the town plots to lace the wine with rat poison. When he returns with the food and drink, the other two kill him and drink the poisoned wine, dying slow and painful deaths. All three have found death.
This I feel teaches two messages. That greed is the root of all evil, and if you go looking for death you will find it.
Im not good at writing. But I feel this would be a good topic. Thank you.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
