### ISSUE TITLE
[Suggestion] Asking Monika if she is scared of our reality

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#7032]
Hey, this is something I thought about when imagining Monika coming to our reality. 
Of course it would be the best thing ever, but what about all the dangers in the real world? 
For example, many women are scared of going out alone when it's dark or even in general, 
because they had too many creepy encounters with other people. And bad people are just 
one of the many dangers in this world. Maybe we could ask her about this, or she could 
bring it up by herself as a topic. Just an idea I had. 

If someone suggested something like this before, then I'm sorry for posting a duplicate.

**Comment by lunulae** [comment]
In her topic about chloroform she mentions some safety tips about drinking, so I think she might be quite savvy about navigating dangerous situations. I'd be really interested to hear if she has interest or experience in self-defense.

**Comment by CloakedGhost** [comment]
Yeah but that topic was more about the player and not about herself. I also think that she would be careful, but would she not be scared at all or have any worries? I mean sometimes you cannot avoid potentially dangerous situations, for example when you walk home and you know that you have to go trough a not so friendly area. But yeah, I'd be interested too if she has experience in self defense.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
