### ISSUE TITLE
How do I make monika start looking at my cursor?

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#7035]
So I did some looking around and figured out I needed xdotool for the whole cursor thing, and I installed it. What do I do now? I restarted MAS after & i'm on chromebook

**Comment by dinogs** [comment]
Make sure you're not on Full Screen, just on window view. Now, move your mouse from left to right. She'll see your cursor.

**Comment by multimokia** [comment]
Xdotool is no longer used for it. Instead it works using Xlib. That said I'm not sure if Chromebooks use X11. If they don't, then enhanced idle will likely not work on Chromebook.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
