### ISSUE TITLE
[Suggestion] "You'd be even cuter with short hair."

### ISSUE THREAD

**Issue by wboorman** [Monika-After-Story/MonikaModDev#7037]
Somewhere between a suggestion and a bug.  There's an option when complimenting Monika's hair that she'd look even cuter with short hair.  It slightly lowers your affection and Monika comments about how she can't go to the salon from where she's at.  Now that Monika _can_ change her hairstyle, and specifically to have short hair no less, this response doesn't make sense anymore.  This comment should probably be replaced with something else.

If you wanted to get fancy, maybe you could even keep the short hair comment, but change Monika's response.  Maybe Monika could have a specific response if she actually _is_ styling her hair short when you make the comment.

**Comment by fromulus** [comment]
Already mentioned that plothole in the past, and it's not going to be changed.
Basically, short hairs are spritepacks, and spritepacks are considered "non-canon" to MAS's base dialogues.

**Comment by bakachuuuuuuuuuuujjhjugyi** [comment]
> It's probably easier to ignore it anyway, as Monika having short hair in and of itself is a plothole (how in the world is she able to switch between long and short hair in a matter of seconds ? is she able to magically grow hair instantly ?).

maybe you could just chalk it up to some coding mumbo jumbo or something

**Comment by CloakedGhost** [comment]
> Already mentioned that plothole in the past, and the response I got was that it's not going to be changed.
> Basically, short hairs are spritepacks, and spritepacks are considered "non-canon" to base MAS's dialogues.
> 
> It's probably easier to ignore it anyway, as Monika having short hair in and of itself is a plothole (how in the world is she able to switch between long and short hair in a matter of seconds ? is she able to magically grow hair instantly ?).

Well her world is not real, so she can do everything she wants. I always thought it was her just coding it, the same goes for changing clothing in a matter of seconds.

**Comment by Booplicate** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/e4b43f4dc4265be67cece1bb5c7f2fcffad38b3f/Monika%20After%20Story/game/script-compliments.rpy#L297-L303

The lines above implies that she's kinda insecure which makes her more human. It'd be rude to say that she needs to cut her hair right after that. That and we don't account for user-made content, something may go along with canon, something may go off.

**Comment by ThePotatoGuy** [comment]
as mentioned, spritepacks are considered out of canon. we do not need to address spritepack content in dialogue.

[closing as rejected]
