### ISSUE TITLE
Ahoge??

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#7039]
My Monika has a ahoge all of a sudden... 
![image](https://user-images.githubusercontent.com/43464011/109140460-e81f6400-775c-11eb-8c68-f2c06cc79c55.png)

**Comment by CloakedGhost** [comment]
It sometimes happens in the morning, she just got out of bed. Give her some time and she fixes it herself

**Comment by kkrosie123** [comment]
There are 10 random ahoges and a 50% chance for one to appear.

**Comment by SoisthishowIdoit** [comment]
I've seen these everywhere, but I've never gotten one. :(

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
