### ISSUE TITLE
Unlocking conditions for mini games

### ISSUE THREAD

**Issue by AEjixing** [Monika-After-Story/MonikaModDev#7041]
There are four mini games in MAS, but a few of my friends said that they only have one or two mini games.So I want to know the conditions for unlocking mini games. For example, when the number in the aff-log file is...,(as a Chinese,It is difficult to find the right words to illustrate it), unlock a certain mini game.
Best thanks!

**Comment by dinogs** [comment]
> There are four mini games in MAS, but a few of my friends said that they only have one or two mini games.So I want to know the conditions for unlocking mini games. For example, when the number in the aff-log file is...,(as a Chinese,It is difficult to find the right words to illustrate it), unlock a certain mini game.
> Best thanks!

You need to keep playing with her, over over over over over and over again. Until Monika tells you you really like to play with her and you unlock a mini game

**Comment by AEjixing** [comment]
> > MAS中有4种迷你游戏，但我的一些朋友说他们只有一两个迷你游戏，所以我想知道解锁迷你游戏的条件。例如，当aff-log文件中的数字为...（作为中文时，很难找到正确的词来说明它）时，请解锁某个小型游戏。
> > 最好的谢谢！
> 
> 您需要不断与她玩耍，一遍又一遍。直到莫妮卡（Monika）告诉您您真的很喜欢和她一起玩并且您解锁了迷你游戏

So at the code level, what is the specific value?

**Comment by ThePotatoGuy** [comment]
it's based on a system that correlates to in-game time. see `script-story-events` and `progression`, but there is no direct answer since the rate adjusts dynamically.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
