### ISSUE TITLE
Weather Doesn't Produce And It's Only In A Black Color. (Bug?)

### ISSUE THREAD

**Issue by dinogs** [Monika-After-Story/MonikaModDev#7042]
So I was playing MAS and suddenly the weather of the window was black, it wasn't raining, I tried to put the clear weather but it was black. Help me, please. Here is the following screenshot:
Look at the windows. It's black.
![2021-02-25](https://user-images.githubusercontent.com/79163316/109164528-2bb7a500-7740-11eb-99be-8fdbc46e3964.png)
k

Help?

**Comment by multimokia** [comment]
What are your computer specs

**Comment by dinogs** [comment]
> What are your computer specs

What do you mean?
