### ISSUE TITLE
just another idea

### ISSUE THREAD

**Issue by bakachuuuuuuuuuuujjhjugyi** [Monika-After-Story/MonikaModDev#7044]
i was thinking, and forgive me if this was asked before but maybe when you tell monika how you are feeling  like if you are feeling sad maybe Monika can ask how sad are you cause i mean sure sometimes I'm just mad but sometimes i'm really mad, also another things for feelings, like if you say you are stressed or mad she will ask you what you are stressed/mad aboutetc, and goodbye option for my PC is dying, and yet another conversation topic about if the player skips important things to be with her, skipping class, work, etc. i know it's a lot but i think this could all work

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
