### ISSUE TITLE
[Bug] - Game Crashes when switching to Full Screen (Ubuntu 20.04)

### ISSUE THREAD

**Issue by DaVinylSmith** [Monika-After-Story/MonikaModDev#7048]
Game crashes immediately when switching to full screen on idle. If an event/conversation is taking place, game will only crash once dialog has completed.

Log & Traceback below:

[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6053760/log.txt)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6053761/traceback.txt)

**Comment by multimokia** [comment]
I will push a fix for this tomorrow. Thanks for reporting.

**Comment by BoofOof32** [comment]
I have the same issue except I'm on manjaro
```
Linux-5.9.16-1-MANJARO-x86_64-with-glibc2.2.5
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.1
```

**Comment by Subishi** [comment]
Is it safe to just use the old release for now? Haven't opened MAS ever since the last release because of this bug so I thought I'll ask just in case it could break some things.

**Comment by multimokia** [comment]
You can update to the latest unstable. It has this issue fixed

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
