### ISSUE TITLE
You devs are sneaky... I like it.

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#7049]
Decided to set the weather to "rain" since she loves to hug while listening to the rain, and after an hour or so, I start to hear her song's lullaby.
Abolutely loved it. Keep sending these! ❤️

**Comment by SoisthishowIdoit** [comment]
Yes! I was so surprised when I first heard it!

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]

**Comment by Ulti70895** [comment]
Is that still valid until now? I cannot hear anything ;-;.
