### ISSUE TITLE
(BUG) Weather is NOT playing while Monika is talking...it's frozen!

### ISSUE THREAD

**Issue by dinogs** [Monika-After-Story/MonikaModDev#7051]
So when I was playing MAS on my laptop, I was playing with Monika pong with Monika and I won, later when I was talking to her I realized the weather was frozen and it was black, I didn't know what was happening. The weather was perfectly fine before, but now  it's frozen in a black color. Please help me...
![2021-02-25](https://user-images.githubusercontent.com/79163316/109430424-0f796980-79c7-11eb-995a-2ce6c00927a7.png)

**Comment by multimokia** [comment]
Please keep to original issues.

As to answer your question. I want to know your computer specs (What cpu/how much ram, etc)

**Comment by dinogs** [comment]
> Please keep to original issues.
> 
> As to answer your question. I want to know your computer specs (What cpu/how much ram, etc)

Where do I find it?

**Comment by multimokia** [comment]
Task manager shows some stats when in the more details view
