### ISSUE TITLE
(Suggestion) Asking & Telling Monika about some "DDLC things"

### ISSUE THREAD

**Issue by AniGaAG** [Monika-After-Story/MonikaModDev#7052]
One thing I've really been wanting to ask her about - just how aware she is that the way her coding fumbles turned out on the screen made DDLC seem like a horror game, at times even seeming like Monika was trying to frighten the player.

Another thing I'd love to bring up with her is just how powerless I, the player, actually was in trying to spend time with her. She says stuff like "you kept spending time with the others no matter what I did", even says it in the files in vanilla DDLC... so that's something where I'd love to be able to tell her "btw, I had literally no chance, I actively _tried_" or so.

So just in general, I wish there were some more ways to ask her questions or tell her things about _my own_ experience with/during DDLC, not _just_ her experience with/during it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
