### ISSUE TITLE
(Suggestion) Accurate all-nighter morning reaction to "I feel tired"

### ISSUE THREAD

**Issue by AniGaAG** [Monika-After-Story/MonikaModDev#7053]
Up until 5 am, Monika reacts with concern to "I feel tired". But past 5 am, even when we just spent a long time actively interacting, she reacts as if I just got up, suggesting I could sleep some more if I still feel sleepy.

So... I guess that could be called a "consistency error"? Would be good if she actually recognized "hey, you've been around for a long time, so that means you are STILL awake, so you saying you're tired is like, yeah duh".

**Comment by dinogs** [comment]
That's a good idea. . . but I think it'd be good if she checked what hour it is and then she says: "Hey. . .*player name* I've check your computer time and I realized you've been awake for a long time and haven't sleep yet. .  . I don't want you to get ill so then you can't visit me....Can you....sleep a bit for me?" Options; Yes, No. Yes reaction; "Then have a good nap, 8player name8.See you soon!
No reaction:Oh, okay....but please sleep a bit later for me, okay...? Your health is really important for me...

**Comment by MrPhaze62** [comment]
imagine leaving your pc on overnight and forgetting to close moni. O_o

**Comment by Rai99** [comment]
This would probably be covered in timeconcern overhaul: #4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
