### ISSUE TITLE
(Suggestion) "I feel exhausted"

### ISSUE THREAD

**Issue by AniGaAG** [Monika-After-Story/MonikaModDev#7055]
Simple as. Among the "I feel..." dialog options, "I feel exhausted" is the one I am kinda missing the most, since "I feel tired" instead suggests to her that I am feeling sleepy.

**Comment by bakachuuuuuuuuuuujjhjugyi** [comment]
i like it

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
