### ISSUE TITLE
Question about the event on april 1st (answer only with yes or no)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7057]
Does monika do something on april 1st because only one thing happend on last april 1st for me, when i looked through the talk menu then the talk menu just turned off and monika started giggling but nothing else happend after

**Comment by lunulae** [comment]
The only difference in content on April 1st is that Monika responds differently to the mean dialogue options such as "meet my girlfriend." As of this year she doesn't pull any pranks of her own.

**Comment by Ant9cp** [comment]
👍
