### ISSUE TITLE
[YouTube music submod question] Monika takes a long time to load music

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#7058]
So I have the YouTube music submod installed and I really love it. But for some reason, Monika takes a long time to search for a song and play it. It can take up to 10 minutes. My internet connection is stable, I have 400 mbps according to speedtest. So is something "limiting" or interfering with Monika?
Thanks in advance.

**Comment by ThePotatoGuy** [comment]
direct your question to the [youtube music github](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/issues)
