### ISSUE TITLE
A Bug Or Something Need Help

### ISSUE THREAD

**Issue by redujump5** [Monika-After-Story/MonikaModDev#7059]
When I Give A Gift To Monika The Error Screen Keep Coming On And I Don’t Know What To Do Help Me

**Comment by lunulae** [comment]
Could you please send a screenshot of the error screen that shows up? That will give us info about what might be going on.

**Comment by redujump5** [comment]
I’ll try to

**Comment by redujump5** [comment]
I Fix It Sorry For Your Time
