### ISSUE TITLE
Issue with hairstyle's 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7060]
look on top of her head that little part of hair is not supposed to be there, this is with all hairstyle's 
![screenshot0001](https://user-images.githubusercontent.com/71310908/109590770-d9460200-7b0c-11eb-8cd7-d6b0f476025a.png)
 
![screenshot](https://user-images.githubusercontent.com/71310908/109591114-3b9f0280-7b0d-11eb-9923-06dbd7c8937e.jpg)

**Comment by multimokia** [comment]
You're going to have to be a little more clear on which part

**Comment by Ant9cp** [comment]
you see that part on top of her head look at the difference on these 2 images

**Comment by multimokia** [comment]
Not a bug. Just bedhair

**Comment by Ant9cp** [comment]
but it's that supposed to be there?

**Comment by multimokia** [comment]
She has bed hair. She fixes it later in the day

**Comment by Ant9cp** [comment]
so this is a intended new feature in this version?

**Comment by multimokia** [comment]
Yes
