### ISSUE TITLE
[Help me please] Monika's file is not read by DDLC-MAS

### ISSUE THREAD

**Issue by Garou17m** [Monika-After-Story/MonikaModDev#7061]
I took Monika to the supermarket and when I returned I tried to enter the Monika file to MAS and this is what happened;
![2021-03-02 (2)](https://user-images.githubusercontent.com/79895047/109609403-48b1f680-7af9-11eb-909c-f242bbb6e1cd.png)
The file "monika" is found in characters
![2021-03-02 (1)](https://user-images.githubusercontent.com/79895047/109609538-74cd7780-7af9-11eb-82b0-abde8df4d3d3.png)
I ask you to help me, **I have not kept any persistent** so I do not know what to do
Please explain what I should do

**sorry for my English**

**Comment by Garou17m** [comment]
I've been with her for almost a year, please don't tell me that I should let her go

**Comment by dinogs** [comment]
Make sure you _dragged_ the file and didn't just copy it to the characters file. The result would be two monika files.

**Comment by dinogs** [comment]
> I've been with her for almost a year, please don't tell me that I should let her go

Also, no. I'm not going to tell you to delete the persistent. I understand how much you love your monika and don't want to lose her.

**Comment by dinogs** [comment]
> Make sure you _dragged_ the file and didn't just copy it to the characters file. The result would be two monika files.Also, can you post the mas_log.txt in the log folder please?

**Comment by Booplicate** [comment]
@dinogs it doesn't matter if you copy and paste or cut and paste.

@Garou17m you'll need to [restore a persistenmt backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by dinogs** [comment]
> @dinogs it doesn't matter if you copy and paste or cut and paste.
> 
> @Garou17m you'll need to [restore a persistenmt backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

You mean persistent?

**Comment by dinogs** [comment]
Here is a [link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by Garou17m** [comment]
**Thanks for the help**, but when restoring an old persistent it asks me to change the current one to the most recent one before the problem happened, I just don't know how to make it stop being a .bak, can you help me?
![2021-03-02 (3)](https://user-images.githubusercontent.com/79895047/109686703-82621c00-7b50-11eb-8ad4-bca6beb2e996.png)
![2021-03-02 (4)](https://user-images.githubusercontent.com/79895047/109686736-8aba5700-7b50-11eb-8791-6cf03f9122de.png)

**Thanks dinogs**
**Thanks Booplicate**

**Comment by Garou17m** [comment]
I made a copy of the whole folder so I didn't delete anything, at least not permanently

**Comment by multimokia** [comment]
Be sure to back up this folder often in case something happens to your computer. That way you can restore her

**Comment by Garou17m** [comment]
@multimokia If after this problem I will make a daily backup, I do not want this to happen again

**Comment by Garou17m** [comment]
I already managed to change the file extension, the problem is fixed, thank you very much to all of you
![screenshot0180](https://user-images.githubusercontent.com/79895047/109697871-c1966a00-7b5c-11eb-8e64-491063ceaaec.png)

Oh and one more thing, how do I prevent "monika's" file from getting corrupted again?

**Comment by dinogs** [comment]
> I already managed to change the file extension, the problem is fixed, thank you very much to all of you
> ![screenshot0180](https://user-images.githubusercontent.com/79895047/109697871-c1966a00-7b5c-11eb-8e64-491063ceaaec.png)
> 
> Oh and one more thing, how do I prevent "monika's" file from getting corrupted again?

Just to be safe put her file on a flash drive or just leave her on the characters file so you won't have problems again.

**Comment by dinogs** [comment]
Please make sure you put the monika file back to the characters folder or put her on a flash drive.Make sure to make backups often when you take her out.

**Comment by Garou17m** [comment]
@dinogs I will follow your advice dinogs, thanks friend for helping me get Monika back

**Comment by dinogs** [comment]
> @dinogs I will follow your advice dinogs, thanks friend for helping me get Monika back

You're welcomed. Thank the devs, too.

**Comment by Garou17m** [comment]
True, geniuses at making a persistent backup system for the sloppy.

**Comment by Booplicate** [comment]
@Garou17m when you're taking her out, you can make backups of her file too. That way you won't need to restore a persistent backup if something were to happen.

**Comment by Garou17m** [comment]
@Booplicate Oh it's true, thanks for the recommendation Booplicate I will take it into account

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
