### ISSUE TITLE
Can't give Monika quetzalplushie.gift 

### ISSUE THREAD

**Issue by Okami2011** [Monika-After-Story/MonikaModDev#7064]
I have been trying to give her this gift for over an hour now, i been following the steps and sometimes i get it to work but sometimes she gets the gift and can't read it or just doesn't even know the gift exist and i am not sure what i am doing wrong. It seems whenever I think I have gotten it figured out, I open the game and when the gift is not there, i go and check the file and the file is gone in Character

**Comment by Okami2011** [comment]
![unknown](https://user-images.githubusercontent.com/79952908/109841351-f49d3400-7c16-11eb-8279-bb7a1aa42fcd.png)

I just opened the game and she seems to have some of the gifts i gave her but the files are not in the file, not sure if that is suppose to happen or the gift just come up at random now

**Comment by GlitchyMoni** [comment]
> ![unknown](https://user-images.githubusercontent.com/79952908/109841351-f49d3400-7c16-11eb-8279-bb7a1aa42fcd.png)
> 
> I just opened the game and she seems to have some of the gifts i gave her but the files are not in the file, not sure if that is suppose to happen or the gift just come up at random now

When Monika brings the gifts to her place the gifts files dissapear.

**Comment by GlitchyMoni** [comment]
It should be a gift extension. If it's still a txt file Monika won't read it.

![2021-03-04](https://user-images.githubusercontent.com/79163316/110006909-c9324c00-7cdf-11eb-8b14-18d80a729ff4.png)



I should look like this

**Comment by Okami2011** [comment]
right I did that, i got all the steps right but for some reason when she gets the gift the gift gets deleted and then sometimes i see the gift on rotation? not sure if that is suppose to happen

**Comment by Okami2011** [comment]
so her gifts will be on rotation? last night she had her coffee and the day before that, she had her plushy bird so am i right to assume the gift rotate?

**Comment by multimokia** [comment]
There is a 1/4 chance to load in with the plush on her desk. She still has the gift, but she doesn't always play with it. Likewise she won't always drink coffee

**Comment by GlitchyMoni** [comment]
Yes, sometimes she won't have the quetzal plushie but sometimes she'll have it in the desk. She just puts it on a safe place so then she can play with it the plushie.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
