### ISSUE TITLE
How do you delete a submod?/ duplicate folder's

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7065]
I Want to delete a submod called the dark room topic something like that, and i had to copy the files in to the game folder but i don't know what to delete for this, i don't want to delete something wrong on accident

**Comment by multimokia** [comment]
You need to delete the rpy file(s) related to the submod in order to delete it

**Comment by Ant9cp** [comment]
btw there is also this lib folder from this submod that i also copied in the main lib folder of the mod

**Comment by Ant9cp** [comment]
BTW i have a duplicate of the python-package and 3 other's folder's are they maybe from the submod i try to delete because there in the DDLC folder not in game folder.

These other folder's are called darwin-x86_64 linux-i686 linux-x86_64
