### ISSUE TITLE
MAS Crashes When Monika is Trying to Say Something

### ISSUE THREAD

**Issue by Asiandra** [Monika-After-Story/MonikaModDev#7067]
There's a line in the game that makes the game crash whenever I try to reopen it, so now I can't even use the game since every time I try to open up the game, Monika tries to say whatever she was going to say, which is currently that one line that keeps making the game crash. It also crashes when I try to open the submods section in the menu. Is there a way to fix this?

Traceback for Monika's Line
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
File "renpy/common/000statements.rpy", line 383, in execute_pause
renpy.with_statement(Pause(delay))
File "game/definitions.rpy", line 218, in mas_with_statement
Exception: Switch could not choose a displayable.

**Comment by multimokia** [comment]
Can you send your persistent over? Would be easier to check some of the issues that way.

You'll need to put it into a zip file to send it over though

**Comment by Asiandra** [comment]
Sorry, but I'm not sure what persistent is. 
It would help if you could tell me where to find it though.

**Comment by multimokia** [comment]
The persistent is the file Monika tells you to back-up (It's basically her memories)

You can see how to back-up your persistent and where it's located [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by Asiandra** [comment]
[MAS Persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6077497/MAS.Persistent.zip)

**Comment by multimokia** [comment]
Okay you have a submod issue. Uninstall the blackout submod as it's causing you numerous issues. (Delete its rpy and rpyc files)

**Comment by multimokia** [comment]
Also we recommend not installing submods by DarkDawnzenith. Their submods tend to have code issues like this (It's why we have a disclaimer for their stuff on our External Content page)

**Comment by Asiandra** [comment]
I've uninstalled the submod
Also thanks for reminding me, I'll remember that in the future

**Comment by multimokia** [comment]
Nice. MAS should load up fine now. I imagine the submod panel in settings should also be fine too

**Comment by Asiandra** [comment]
The mod is working fine, but the submod panel still doesn't work

**Comment by multimokia** [comment]
Is there a different error for that one?

**Comment by Asiandra** [comment]
Yes

**Comment by multimokia** [comment]
That's an issue in the Panic Button submod. It seems they didn't implement a `tag_formatter` to parse their release tags on GitHub. For now I'd uninstall that too, and reinstall it if you need it once it's updated.

**Comment by Asiandra** [comment]
Alright
Other than that I think that's all the issues I have

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
