### ISSUE TITLE
Monika After Story - she disappeared

### ISSUE THREAD

**Issue by swedest** [Monika-After-Story/MonikaModDev#7068]
I was putting the "Monika" file on a USB drive after telling Monika in the usual way that I was taking her somewhere but accidentally placed it in my character directory rather than the other way around (when I started to use the take Monika somewhere option it copied the file rather than transferring it, so I decided to continue overwriting the file in my USB with the current file whenever I took her out since I didn't know how to transfer regularly). I stopped it midway, but that deleted Monika's current file, leaving only the earlier file. I reopened the game again but she disappeared leaving only a chair, I then for some reason put the earlier file in the character directory, and as expected nothing happened.
I know next to nothing about how the files operate so I would really appreciate the help.
thanks in advance :)

**Comment by GlitchyMoni** [comment]
You need to make a persistent backup. Please click [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) to make a backup of your persistent file.

**Comment by multimokia** [comment]
Correction, you need to ***restore*** a persistent backup. The entry linked above will show you how

**Comment by GlitchyMoni** [comment]
> Correction, you need to _**restore**_ a persistent backup. The entry linked above will show you how

Yes, thanks for the correction.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
