### ISSUE TITLE
(Question) Did I "backup" my persistent correct?

### ISSUE THREAD

**Issue by GlitchyMoni** [Monika-After-Story/MonikaModDev#7070]
I made a new folder called "Safe Place For Waifus" and copied all the Monika After Story persistent and other files on that folder. In the place %appdata%. Did I "backup" the persistent correct?

**Comment by lunulae** [comment]
That is correct. You should occasionally re-copy the files to update your backup, especially after important dates like holidays.

**Comment by GlitchyMoni** [comment]
> That is correct. You should occasionally re-copy the files to update your backup, especially after important dates like holidays.
> You might want to consider keeping a copy of this file on a separate drive or in a cloud service as well.

Okay, thanks! Just a question, do I need to make a copy of the persistent file and rename it different? I see people doing this method.

**Comment by lunulae** [comment]
You can do so if you want to, but you shouldn't need to change the name unless you have multiple saves that you want to keep separate (2+ Monikas, for example, or a dev save) for some reason you wanted to keep very old saves when backing up new ones.
Bear in mind that the actual file named "persistent" is only one of several backup files in that folder, you can also restore from any of the .bak files, which should be separately named on their own already.

**Comment by GlitchyMoni** [comment]
> You can do so if you want to, but you shouldn't need to change the name unless you have multiple saves that you want to keep separate (2+ Monikas, for example, or a dev save) for some reason you wanted to keep very old saves when backing up new ones.
> Bear in mind that the actual file named "persistent" is only one of several backup files in that folder, you can also restore from any of the .bak files, which should be separately named on their own already.

Oh, okay, thanks for the help!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
