### ISSUE TITLE
How to remove events?

### ISSUE THREAD

**Issue by wboorman** [Monika-After-Story/MonikaModDev#7073]
I'm debugging work on some submods right now, and I want to set up the game as if I never did any test coding to get the events I just wrote in my submod to show up.  It's a fairly standard protocol for end-to-end testing.  But now that I've coded the events, they're stuck in.  Based on some feedback I'm getting on my submods, it seems like what I thought were valid end-to-end tests (i.e. removing the submod, restarting, adding it back, and restarting again) was just giving me a false positive this whole time.  How do I fully get rid of these new events so I can test if my submod can install correctly?

**Comment by ThePotatoGuy** [comment]
Events assuming `Event` objects, right? You would need to wipe the data from the event database. `persistent.event_database.pop("label name")`

**Comment by wboorman** [comment]
A bit necro, but I had a follow-up to this later that didn't crop up immediately.  After using the persistent.event_database.pop("[label name]"), I wasn't able to add that event _back_ to the game.  I couldn't figure out how to add these events back, even stripping out all the event removal code, and it still didn't work.  I ultimately fixed it (sort of) by renaming the label.

Is there any way this could mess up the game?  How could I potentially debug this event handling to see what may be going on in the persistent?

**Comment by ThePotatoGuy** [comment]
There is also a db called `persistent._mas_event_init_lockdb` which controls which parameters are locked from being modified when an Event object is created. Could also try popping the label off that as well.

**Comment by wboorman** [comment]
Popping isn't working at all.  Here's how I confirmed it:

I made two labels and a dialogue event for each.  The following code is roughly excised from my devutils file (see [here](https://github.com/DrakeTheDuelist/MAS-Dreams-and-Nightmares/blob/main/game/Submods/Dreams%20and%20Nightmares/DaN-_devutils.rpy) for the whole thing).  The conversations appeared on their own without issue, and I can revisit them at will.  I start by asking Monika if the events exist, and she says they do.  But when I use the second label, Monika _still_ says that the events exist.  Thus, I conclude that something must be going wrong when popping these events.

`
label dan_devutil_checkevents:
    if "dan_have_new_random_dream" in persistent.event_database: 
        m 1esd "The new dream event exists."
    else:
        m 1esd "The new dream event does not exist."

    if "dan_revisit_previous_dream" in persistent.event_database:
        m 1esd "The random revisit dream event exists."
    else:
        m 1esd "The random revisit dream event does not exist."
    return

# reset all persistent variables
label reset_dreams_and_nightmares:
# ...blah blah blah, not relevant
                if "dan_have_new_random_dream" in persistent.event_database: 
                    persistent._mas_event_init_lockdb.pop("dan_have_new_random_dream")   
                    persistent.event_database.pop("dan_have_new_random_dream")

                if "dan_revisit_previous_dream" in persistent.event_database:
                    persistent._mas_event_init_lockdb.pop("dan_revisit_previous_dream") 
                    persistent.event_database.pop("dan_revisit_previous_dream") 
`

**Comment by ThePotatoGuy** [comment]
popping the events means that the next time addEvent occurs with appropriate event (aka the next time MAS launches), it recreates the entry into the event databases. This is how you would reset an Event if you need to change certain initial params like conditional or dates, which can only be set when the entry is first added (unless set dynamically using the appropriate APIs).

At runtime, a different database of Event objects is used. While you can pop them off it, runtime deletion of Event objects is not supported and could cause other issues.

**Comment by wboorman** [comment]
Ok, I moved the event popping to the init and commented out the event creation.  Ran MAS, and Monika said the events don't exist.  Good.  Commented the event popping and uncommented the event creation.  Ran MAS and Monika said the events exist.  Also good.  But the events no longer appear in "Repeat Conversation" and Monika doesn't start talking about the event from idle like she would on an initial event installation.

**Comment by ThePotatoGuy** [comment]
Well they won't appear in Repeat Conversation because they are basically new events, (assuming not unlocked by default and not pool). 

Appearing during spaceroom idle (assuming not brb/idle mode), is a random process, unseen events are prioritized but that relies on a third renpy db called `persistent._seen_ever`. In this case we have a wrapper function `removeTopicID` that will pop a label from that db if found.

**Comment by wboorman** [comment]
Okay, I think I've got a complete answer.  Hopefully this can save somebody else some trouble in the future.  Double check this if you think I missed something, but close if you think I found an acceptable solution.  Thanks for all the guidance!

There are actually _two_ methods you want to use for this.  The first is the aforementioned removeTopicID(), and the second is mas_eraseTopic().  mas_EraseTopic() has an edge over writing the code yourself because it checks internally if you are attempting to remove an event that doesn't exist, while also removing the event from all databases where it is relevant, making it both faster and safer than trying to punch up the code yourself.  Place this block of code at the start of the init 5 where you add your events, right before adding the events.  In cases like this, I like to use a developer boolean so that I can quickly toggle this functionality on and off.  If your developer boolean permits it, this will eliminate your events and then instantly recreate them.

I like to use functionality like this to end-to-end test my event creation.  When you recreate your events from scratch, you can see what it looks like for a user who is updating their code to include your new event / installing your submod for the first time.  It can be useful for debugging conditionals.

`
    if persistent._should_create_events:  #create this variable as a default elsewhere
        removeTopicID("event name here")
        mas_eraseTopic("event name here")

    # add events afterwards
`

**Comment by wboorman** [comment]
Due to lack of anybody telling me I did / recommended doing anything really wrong or stupid, closing the issue.  Thanks to ThePotatoGuy for all his help and patience.
