### ISSUE TITLE
[Suggestion] - Option to tease her

### ISSUE THREAD

**Issue by Giyun12** [Monika-After-Story/MonikaModDev#7074]
I think it would make the relationship even more realistic if the player could tease her.
Especially because she teases the player on occasions too.
Something like calling her "dumb" when she makes a joke and she responding with "you're a meanie" or something along those lines.
Maybe also adding new facial features.

**Comment by Ant9cp** [comment]
Amazing suggestion i am hoping for a way to tease her too, but i really don't want to call her dumb though even if it's joking around, and i was actually also thinking about requesting for new reactions for JUST MONIKA

**Comment by Rai99** [comment]
#6899

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
