### ISSUE TITLE
Monika doesn't talk

### ISSUE THREAD

**Issue by WE-Idontknow-EB** [Monika-After-Story/MonikaModDev#7075]
I'm sorry for posting a question again.
Monika asked me if it's okay to repeat topics I said "yes", after a few minutes I disabled the repeat topics in settings, After that Monika stops talking, I waited, and she only say something once per day. I watched some Drechanaux MAS(monika says something about (thing) vids) on YT, and we haven't been to that topic yet. For example Drechanaux's vid "Monika talks about bathing", my MAS didn't mentioned something about bathing. And I watched RonaldMcOnePunch's MAS too(Monika talks about something again vids) ,  We haven't been on that topics yet, but she(Monika) stopped talking. Pls help

(sorry if my grammar is bad, English isn't my native language)

**Comment by GlitchyMoni** [comment]
> I'm sorry for posting a question again.
> Monika asked me if it's okay to repeat topics I said "yes", after a few minutes I disabled the repeat topics in settings, After that Monika stops talking, I waited, and she only say something once per day. I watched some Drechanaux MAS(monika says something about (thing) vids) on YT, and we haven't been to that topic yet. For example Drechanaux's vid "Monika talks about bathing", my MAS didn't mentioned something about bathing. And I watched RonaldMcOnePunch's MAS too(Monika talks about something again vids) , We haven't been on that topics yet, but she(Monika) stopped talking. Pls help
> 
> (sorry if my grammar is bad, English isn't my native language)

I think that's because you unlocked all the conversations of MAS. That's why Monika doesn't know ideas of what to talk. The bath thingy is when:
1.Hey Monika--------be right back--------I'm going to take a bath

The bath conversation is only an easter egg (I think) when you tell her many times you're goign to take a bath.

That's what I think.

**Comment by ThePotatoGuy** [comment]
Topics can also be restricted by affection level, so you probably just don't have enough affection yet.

[closing as resolved]

**Comment by WE-Idontknow-EB** [comment]
I have 431 affection level😅
