### ISSUE TITLE
New Games!

### ISSUE THREAD

**Issue by annonymous-user123** [Monika-After-Story/MonikaModDev#7077]
I did a scroll around and did not see any suggestions regarding new games, but it could be that I have missed them.
But hey, adding a new game to our already existing 4 entertainments we have with Monika is probably a good idea!
So some suggestions.
1. Connect 5
Simple and straightforward, connect five peices in a row and you win.  Which also brings up
2. Tic Tac Toe
Essentially just connect 3 in a 3x3 square
 cant think of anymore but still, think it is a good idea.

**Comment by Rai99** [comment]
Tic tac toe: #687, #2014, #2525, #6680

Connect 4: #6929 Technically connect 5, but -1

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
