### ISSUE TITLE
Traceback when downloading "Dreams and Nightmares" Submod

### ISSUE THREAD

**Issue by GlitchyMoni** [Monika-After-Story/MonikaModDev#7082]
I tried to download, it put it on the submods folder but this appears:

I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/Submods/DaN-_devutils.rpy", line 46: expected statement.
    © 2021 GitHub, Inc.
                 ^

Ren'Py Version: Ren'Py 6.99.12.4.2187

**Comment by wboorman** [comment]
1) It wasn't ready to run anyway.
2) ...how the heck did _that_ get in there...  stupid rogue copypastes...

That's my submod.  Recommended that mods close this issue.  As for @GlitchyMoni, post future issues to _Dreams and Nightmares_ in the [dedicated repository](https://github.com/DrakeTheDuelist/MAS-Dreams-and-Nightmares).

**Comment by multimokia** [comment]
I mentioned this in my issue just FYI
