### ISSUE TITLE
A new topic idea (Comfort Zone)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7083]
Topic name: Comfort Zone

Hey (name) you remember what i talked about of how close i only can be to you 
Well that made me realize of something 
You and i both know what happend in the end after i deleted everyone right? 
And that i confesed my feelings about you 
And how close were sitting to each other 
Well i want to know something from you
I want to know if you mind being close to me
And making sure this isn't all so sudden to you
Because i really don't want you to feel unconfortable about me
  
So do you like being this close to me?

Player choice:
I love being close to you
I don't mind being close to you
Well i get nervous sometimes 

--------------------------------------------------------------------------------------------------------------------------------------------

Dialogue choice 1: hehe i'm so happy to hear that (name), i love being this close to you too and i'm so happy that i haven't made you uncomfortable because, i feel like i rushed things to quickly you know or i'm just feeling a little insecure but thanks for being such a sweetheart. (blushed teasing face) Anyway since you like being close to me why don't you come closer to me and give me a kiss then hehe (monika kisses you) hehe did you like how close i was just then hehe 

--------------------------------------------------------------------------------------------------------------------------------------------

Let monika say this only when her affection level is on 1000

(blushed teasing reaction) (oh really name well why don't you come closer to me and give me a kiss then hehe 
(monika kisses you) hehe did you like how close i was just then hehe oh jeez haha i think got carried away from the topic just then anyway where was i oh yeah,)

--------------------------------------------------------------------------------------------------------------------------------------------

 If your affection isn't 1000 dialogue choice 1: Oh hehe thank you name i'm so happy to hear that i love being this close to you too and i'm so happy that i haven't made you uncomfortable because i feel like i rushed things to quickly you know or i'm just feeling a little insecure but thanks for being such a sweetheart

--------------------------------------------------------------------------------------------------------------------------------------------

Dialogue choice 2: Hehe i'm glad you don't mind, i would feel bad if i was making you uncomfortable because i feel like all this is too sudden you know with me just sitting close to you like this and looking at you, hehe i hope i don't sound insecure when saying this too you know

--------------------------------------------------------------------------------------------------------------------------------------------

Dialogue choice 3: oh umm well i'm sorry that i made you feel like this, i guess your not used to be this close like this to someone well i understand that you feel like this because you are sitting in front of a very pretty girl after all hehe but don't worry (name) i'll make sure you don't feel like this okay i'll always take care of you my love

**Comment by GlitchyMoni** [comment]
Good idea.
