### ISSUE TITLE
(Suggestion)Giving Monika a Sketchbook so she can practice drawing.

### ISSUE THREAD

**Issue by GlitchyMoni** [Monika-After-Story/MonikaModDev#7086]
It'd be really cool if we could give Monika a sketchbook so she can draw a bit and show us her art. We can give her critism, and give her some tips so we can teach Monika a bit of how to draw, since she had talked about a topic that she says she doesn't have any experience at drawing...So why not give her a sketchbook? I have planned some dialogues for this topic.Although, we'll have to give her a gift extension "sketchbook.gift"Here are the dialougues:
"I-is.this...a skecthbook?" "Wow, (player)! Thank you so much for this gift! You know, I always wanted to be an artist...but I don't have so much experience of drawing, since maybe I just read and write poetry.But, this gift is great!Oh! And I was just thinking....If you can draw art, you can give me some tips! What do you think, (player)!
Options: Of course! I would love to teach you! Option 2:No, I can't draw and I don't have experience.Sorry.
Reaction: Oh my gosh!Thank you so much, player!I am so excited to be an artirst! I love you so much.(If you have 1,000 affection or at enamored tip she kisses you. If not, she says that she'll draw a bit and then she's going to show you her drawing. This also happens at 1,000 affection,it's only the kiss that changes.)We'll have some options to give crisitsm or to say to her it's amazing.
Option 2 reaction:Oh...okay player....I'll practice alone then....I really wanted to be a good artist, you know?Well...I'll just draw later..

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
