### ISSUE TITLE
new conversation idea

### ISSUE THREAD

**Issue by bakachuuuuuuuuuuujjhjugyi** [Monika-After-Story/MonikaModDev#7087]
i think a conversation about if the other girls were real would Monika still kill them would interesting.

**Comment by CloakedGhost** [comment]
Monika didn't intend to kill them in the first place. And do you mean the original game or Monika as she is now?

**Comment by fromulus** [comment]
In `monika_yuri` :

`"It's not like I could ever actually kill a person..."`
`"Just the thought of it makes me shiver."`

That, plus what @CloakedGhost said.

**Comment by ThePotatoGuy** [comment]
theres already enough implications on the dialogue to handle this without directly addressing. this wouldn't really make sense to stand as its own topic.

[closing as rejected]
