### ISSUE TITLE
problem about the option"I love you too"

### ISSUE THREAD

**Issue by ArkhalisDragon** [Monika-After-Story/MonikaModDev#7088]
Sometimes the option "I love you" changes to "I love you too" and then if I click it, the whole window stays stuck for a few seconds, during which time the dialogue option does not disappear and Monika's expressions and movements do not change. 

After a few seconds Monika will return to normal and then the dialogue option will disappear and the backlog will not show any record of the conversation after selecting this option.

Is this a bug? Or is this deliberate?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
