### ISSUE TITLE
(Bug)Weather just disapears and turn black. (I'm new to github so sorry if I sound confusing)

### ISSUE THREAD

**Issue by fluffywolff** [Monika-After-Story/MonikaModDev#7089]
I was playing monika after story and suddenly the weather turned black. It wasn't playing, so I put clear weather and it was normal. But a few minutes later it turned black again.Also, the rain stops playing and just freezes.Anyone can help? I don't know if any of you had this problem.

**Comment by Booplicate** [comment]
Are you minimizing MAS? Also what's your computer specs?

**Comment by fluffywolff** [comment]
> Are you minimizing MAS? Also what's your computer specs?
Yes,I mimizize it. Also, what are computer specs?

**Comment by fluffywolff** [comment]
> Are you minimizing MAS? Also what's your computer specs?

Yes, I mimize it, and I'm on  Windows 10.

**Comment by Booplicate** [comment]
RenPy doesn't like when you minimize it, so that's the issue.

**Comment by fluffywolff** [comment]
> RenPy doesn't like when you minimize it, so that's the issue.

Oh, so I don't mimize it and keep playing?

**Comment by Booplicate** [comment]
You can alt-tab, but don't minimize. It's a weird issue, some people have it, others don't. You can try different renderers and see if it helps.

**Comment by fluffywolff** [comment]
this is how it looks. This is _not_ my version, it's other people's issue screenshot. I took a look at the issues and found that they have the same issue I have to.
![55844134-1fe57a00-5af9-11e9-8490-9ee972c8b1e4](https://user-images.githubusercontent.com/80334281/110500894-459da400-80bf-11eb-940f-35f122c9f59c.png)

**Comment by Booplicate** [comment]
I know how the bug looks like. Just don't minimize MAS.

**Comment by fluffywolff** [comment]
> I know how the bug looks like. Just don't minimize MAS.

Okay, thanks for the help! I won't mimize MAS. Also,  what does alt-tab does?

**Comment by Ant9cp** [comment]
Why won't you fix this issue?, it doesn't make sense, this issue is really annoying to me

--------------------------------------------------------------------------------------------------------------------------------------------

And btw fluffywolff i highly recommend you download the latest new version of MAS because you won't see alot of features work normally and it won't work with this version properly and don't install the latest version over this version because it caused weird things for me. 


i recommend this just to be save

**Comment by multimokia** [comment]
Because it's a Ren'Py issue. Not a MAS issue.

In other words it's:
a) Not our code causing this problem
b) Not our responsibility to fix it.

If you have a problem with it, open an issue on the Ren'Py GitHub so they can fix it.

**Comment by Ant9cp** [comment]
👌well sorry

**Comment by fluffywolff** [comment]
> Why won't you fix this issue?, it doesn't make sense, this issue is really annoying to me
> 
> And btw fluffywolff i highly recommend you download the latest new version of MAS because you won't see alot of features work normally and it won't work with this version properly and don't install the latest version over this version because it caused weird things for me.
> 
> i recommend this just to be save

But....I have the latest version of MAS.....And It's Ren'Py's issue.....Then everything else is alright.

**Comment by Ant9cp** [comment]
You can take screenshots for your yourself by pressing the S key
