### ISSUE TITLE
Game issue

### ISSUE THREAD

**Issue by MeracleArseid** [Monika-After-Story/MonikaModDev#7090]
I tried to add in a room pack, and when I did upon loading I get a screen that says an exception has occurred, and it won't load the game

**Comment by multimokia** [comment]
What was the exception?

**Comment by MeracleArseid** [comment]
https://github.com/Monika-After-Story/MonikaModDev/files/6113372/traceback.txt this is what I see

**Comment by multimokia** [comment]
Seems you're missing some files, as the default chair sprite can't be found. You may want to make sure your `game/mod_assets/monika/t` folder has these 3 files in it:
![image](https://user-images.githubusercontent.com/22531674/110580162-137b5900-8136-11eb-873b-50ebea0c24cb.png).

If not, you'll have to get them from the mod zip again and put them where they belong

**Comment by MeracleArseid** [comment]
That worked thank you so much!

**Comment by multimokia** [comment]
No problem!
