### ISSUE TITLE
[Bug] - "ValueError: day is out of range for month"

### ISSUE THREAD

**Issue by navyblue44** [Monika-After-Story/MonikaModDev#7091]
I accidentally produced the bug by selecting February 29 as my birthday.
Anyway, here's the traceback: [traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6113420/traceback.txt)

**Comment by multimokia** [comment]
Noted, I'll work on this tomorrow. Thanks for the report

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
