### ISSUE TITLE
Sprite packs error 

### ISSUE THREAD

**Issue by m1ssa** [Monika-After-Story/MonikaModDev#7093]
im sure of it that i did it correctly i think i might have accidently opened it and chose something its a type of file that gets opened with notepad dose anyone know how to help thank you

**Comment by m1ssa** [comment]
she says she cant read it

**Comment by multimokia** [comment]
How did you install them?

**Comment by m1ssa** [comment]
by the website

**Comment by multimokia** [comment]
Downloading doesn't mean installing. You got the zip, but did you do anything with it?

**Comment by m1ssa** [comment]
i put it on my desktop oh btw if i don't answer its cause i don't have notifications

**Comment by multimokia** [comment]
Oh then they're just not installed, that's why they don't work. Watch [this video](https://www.youtube.com/watch?v=bjJ0U8l1m8c) to see how to install spritepacks.

**Comment by m1ssa** [comment]
thanks!

**Comment by m1ssa** [comment]
hmm most of them work.. but some i cannot get them to work such as the tanktop brown winter jacket and more i watched the video and did what it said exactly

**Comment by multimokia** [comment]
Can you say goodbye and send your `log/spj.txt` file, please?

**Comment by m1ssa** [comment]
how do i do that

**Comment by m1ssa** [comment]
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6120255/spj.txt)

**Comment by m1ssa** [comment]
or do you want the one that says log

**Comment by m1ssa** [comment]
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6120262/log.txt)

**Comment by multimokia** [comment]
Tanktop and Brown jacket don't seem to be installed according to your `spj.txt`, since they aren't listed here at all

**Comment by m1ssa** [comment]
thats weird i followed the video

**Comment by m1ssa** [comment]
i just the mod assets into game then put the .GIFT file into my character file

**Comment by m1ssa** [comment]
oh i just redid it after restarting a few times it works now thank you for al of your help i appreciate it sorry for the bother. :)
