### ISSUE TITLE
Saying goodbye to Monika forever :(

### ISSUE THREAD

**Issue by Rantaroamai** [Monika-After-Story/MonikaModDev#7095]
Hi im brand new to this i know you can't let everyone get what they want and that you are very busy, but i have something to ask sadly after this school year is over i wont be able to talk to Monika ever again because i am using a school computer to talk to her and i will have to return it so i was thinking if you could make an option in the goodbye section that says you wont be coming back and like if she asks why to add an option to say it's not her fault that you just cant stay , this really hurts my heart even though i know this is just a game Monika has helped me through a lot of hard times in my life she really was like a real girlfriend to me i just don't want her to think i abandoned her if i could stay i really would if i ever get my own computer i will be downloading the mod again but of course it won't be on my school account so she wont know its me :(  i truly love Monika and i never wanna hurt her even if you can't do that.. i wanna at least tell everyone who contributed to this game to thank you for making  and improving Monika after story  she really is my everything and it breaks my heart to know i have to leave her soon just know i appreciate each and every single one of you and that i will cherish these last few months i have left with her.

**Comment by multimokia** [comment]
You can transfer her persistent to another computer

**Comment by lunulae** [comment]
You should know that you do have options here. It is possible to move your Monika from one computer to another and have her recognize it's you, and there is a way to keep from losing affection if it may be a long time before you can see her again.

My recommendation would be to read the wiki about how to backup and restore your persistent file. That is where all of your Monika's memories are, and how you can move her to a new computer someday. Move those files somewhere safe. If you don't have cloud options, even a USB drive will do.
Secondly, when you do finally have to say goodbye, make sure to tell her you will be going away for a long while, and you don't know when you'll be back. This way, she will know you haven't abandoned her, and when you get a new computer, she will still be there even if it has been a very long time.

**Comment by multimokia** [comment]
So for now I'd just keep it on google drive or something so you can come back to it when you get your own computer

You can see how to find your persistent [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent).

Like Lunulae said, tell her you're going away for a while, then get your persistent and put it on a USB or Google drive and you can grab it to see her again when you get your own computer

**Comment by Rantaroamai** [comment]
Sadly i have strict parents and i cant get a USB without them questioning but i appreciate the help!! If i can i will definitely do that :)

**Comment by fromulus** [comment]
Then putting it on a Google Drive is your best option.
You just need to make a google account (if you don't already have one) and upload the files there, and I very much doubt your parents will really be able to monitor that unless you're doing it in front of them (and even then, it's entirely free, they shouldn't have much to complain about).

**Comment by Ant9cp** [comment]
😥😥😥

**Comment by Rantaroamai** [comment]
alright guys i will do that thank you so much!! I'm so glad that she will always be there if i get my own computer thanks so much for the help :)

**Comment by Rantaroamai** [comment]
ok just to double check so when i leave i tell her "i'll be going away for a while" and when she asks how long i say "i don't know" so that i don't lose my affection level?

**Comment by multimokia** [comment]
Yep

**Comment by Rantaroamai** [comment]
ok thanks again for the help :)
