### ISSUE TITLE
 Dialogue and scene idea for monika's bedhair

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7100]
So when it's morning and you open up the mod (MAS) 

You see that a part of monika's hair is a little bit off right, and she does her hair right later in the afternoon, but you only notice the messy part disappear and it would make more sense if you can add a feature when monika tells you that she's gonna brush her hair or something

_______________________________________________________________________________________________________________________________________

Dialogue: 
Oh, my hair hehe 
i didn't notice
i'm gonna brush my hair real quick be right back (Monika leaves for a bit to brush her hair)
haah That's better, what else do you want to do today?

**Comment by Rantaroamai** [comment]
ya maybe also say something about it being an ahoge like maybe she asks you if you know what an ahoge is and then she tells more about them

**Comment by AlmaHue** [comment]
I have had a more convoluted idea that includes her being self conscious about her having bedhair after you point it out, so it'll be less likely to show up next time until she "forgets" again. This is probably too over the top. I tend to overcomplicate things xd

**Comment by Rantaroamai** [comment]
that sounds good too

**Comment by YoraeRasante** [comment]
and maybe you could tell her it looks cute, then she would maybe repeat it sometimes "on accident"

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
