### ISSUE TITLE
I constantly have errors =>  "I'm sorry, but an uncaught exception occurred." :(

### ISSUE THREAD

**Issue by LuisAngelGR** [Monika-After-Story/MonikaModDev#7106]
Well, I really have no idea what could be going on. I just updated the program and the problem appears.
(It appears randomly and sometimes I have to close)
I leave the file "traceback.txt"
Thanks! 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6146754/traceback.txt)

**Comment by kirillPro2020** [comment]
Try enabling DirectX in the menu

**Comment by multimokia** [comment]
Delete enhanced idle

**Comment by LuisAngelGR** [comment]
> Delete enhanced idle

Thanks I thought the same but .. I don't have any file with that name xD, I looked for it even with the windows search engine and it didn't appear, I thought it would be hidden but it wasn't, I assumed it would be an internal problem and that's why I shared it, apparently I will have to reinstall xd

**Comment by LuisAngelGR** [comment]
> Try enabling DirectX in the menu

ok i will try thanks

**Comment by Booplicate** [comment]
It has nothing to do with renderer. The submod was installed in the wrong folder, the traceback says you have it in the `/game` folder. Delete it and you should be fine.
>   File "game/enhanced idle.rpy", line 213, in isCursorRightOfMASWindow
  File "game/enhanced idle.rpy", line 130, in getMASWindowPosWin

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
