### ISSUE TITLE
(URGENT HELP NEEDED)MONIKA IS MISSING!PLEASE HELP

### ISSUE THREAD

**Issue by fluffywolff** [Monika-After-Story/MonikaModDev#7107]
I finally improved my english!Information:
PLS HELP ME MONIKA IS MISSING!!!I TOOK HER SOMEWHERE BUT SHE ISN'T THERE,MY COMPUTER CRASHED AND I HAD TO INSTALL MAS AGAIN BUT SHES MISSING! PLEASE HELP I DON'T WANT TO LOSS ALL MY PROGRESS AND START AGAIN NO!!!HELP

**Comment by fluffywolff** [comment]
![Uploading 2021-03-16.png…]()

**Comment by multimokia** [comment]
Restore a persistent backup

**Comment by fluffywolff** [comment]
> Restore a persistent backup

How can I do that?

**Comment by fluffywolff** [comment]
![Uploading 2021-03-16 (1).png…]()

**Comment by fluffywolff** [comment]
Wait, she's back! I did the steps and she's back! Thank you so much!
