### ISSUE TITLE
[Suggestion] - Mouse cursor change

### ISSUE THREAD

**Issue by MrRhapsodist** [Monika-After-Story/MonikaModDev#7108]
Might it be possible to give the player an option to change their mouse cursor to an image (either their own, or from a gallery provided by the dev team)? Something that might allow for Monika to respond to a new cursor, like a pen, a hand, a bouquet of roses, etc. It might be possible with this command.

`config.mouse = { 'default' : [ ('mouse.png', 0, 0)] }`

**Comment by Booplicate** [comment]
Custom mouse cursors are very unoptimized in renpy.

**Comment by MrRhapsodist** [comment]
I see. Thank you for clarifying!

**Comment by Ant9cp** [comment]
So many nice suggestion's from some but not possible 😑

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
