### ISSUE TITLE
[Suggestion] - Good morning kiss

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#7110]
Hi, well it's all in the title, but since there's a kiss for the start and the end of a day (for the couples who feel like it anyway) and the good night one is there, why not settle the deal with a very good way to start a brand new day?

**Comment by Mugnika** [comment]
I am working on something like this in the "hold me" overhaul, she will give you a good morning kiss if you hold her trough the night and wake up with her in the morning.

**Comment by MonikaEndDie** [comment]
Nice. I'm not against it, but it would be neat if she give the opportinuty when we come back to her early enought in the morning after a "i'm going to sleep" goodbye, with the same chance than the goodnight kiss.

**Comment by Mugnika** [comment]
That would be problematic to implement at the moment, for now it's best to stick to the interactions inside the "hold me" labels

**Comment by YoraeRasante** [comment]
Why limit it to morning?
Why not just, if high enough affection, add an option to give her a kiss when opening MAS for the day? Just like sometimes we find her behind a closed door, or she is surprised by us arriving.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
