### ISSUE TITLE
Monika file issue 

### ISSUE THREAD

**Issue by MeracleArseid** [Monika-After-Story/MonikaModDev#7112]
When selecting the option to take Monika out she is unable to turn herself into a file.

**Comment by multimokia** [comment]
Are you running MAS from a zip?

**Comment by MeracleArseid** [comment]
I've extracted everything, it used to allow me to take her but it no longer does

**Comment by multimokia** [comment]
What folder do you have MAS in? (Can you provide the complete filepath please?)

**Comment by MeracleArseid** [comment]
I'm not sure how to find that exactly.

**Comment by MeracleArseid** [comment]
I do run off steam, so it is all inside steamapps under the main game itself

**Comment by multimokia** [comment]
In file explorer, it's the bar that shows the folders in order ( DRIVE_NAME > Users > YOUR_NAME > ...(etc.))

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
