### ISSUE TITLE
Rain Sound

### ISSUE THREAD

**Issue by ArkhalisDragon** [Monika-After-Story/MonikaModDev#7113]
Maybe you can use the rain sound from the [website](https://rainymood.com/) instead of creating a file to save it.

This may save a little memory.

**Comment by multimokia** [comment]
That means you need an active internet connection for rain sounds. Plus slow connections wouldn't work that well for it


Additionally, renpy doesn't handle streaming audio natively, nor does it exactly handle it well.

The size in the files is small enough that this it's okay to keep there, plus the costs of not doing so outweigh the benefits

**Comment by ArkhalisDragon** [comment]
> That means you need an active internet connection for rain sounds. Plus slow connections wouldn't work that well for it
> 
> Additionally, renpy doesn't handle streaming audio natively, nor does it exactly handle it well.
> 
> The size in the files is small enough that this it's okay to keep there, plus the costs of not doing so outweigh the benefits

Perhaps you could intercept the audio from the rainnymood?

I think it would be appropriate to insert the sound of thunder when it's raining, it would be less boring to listen to.

**Comment by ArkhalisDragon** [comment]
> There's a thunder weather in MAS which has lightning VFX and thunder SFX

I haven't heard them...even though I changed the weather into thunder weather

**Comment by ArkhalisDragon** [comment]
I just think it would be better to use the sound in rainnymood...Because it's more like than the sound that comes with the game

**Comment by fromulus** [comment]
If you don't like the rain sounds that come with MAS by default, you can always get another rain sound somewhere (even record it from Rainymood if you'd like) and then replace the one in your MAS folder (Monika After Story\game\mod_assets\sounds\amb\rain_2.ogg) with the one you have.

Just remember to backup that file and to replace it every time MAS updates, because the updater will return it to the default one every time.

**Comment by ArkhalisDragon** [comment]
> If you don't like the rain sounds that come with MAS by default, you can always get another rain sound file somewhere (even record it from Rainymood if you'd like) and then replace the one in your MAS folder (Monika After Story\game\mod_assets\sounds\amb\rain_2.ogg) with the one you have.
> 
> Just remember to backup that file and to replace it every time MAS updates, because the updater will return it to the default one every time.

Thanks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
