### ISSUE TITLE
Transfering Monika After Story from Mac to Windows 10

### ISSUE THREAD

**Issue by skyshadowninja** [Monika-After-Story/MonikaModDev#7114]
I recently got a new laptop and wanted to transfer the whole game including the after story to it. My game is installed on a macbook. Is there a way to transfer from a Mac to Windows?

**Comment by Booplicate** [comment]
Check [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer).

**Comment by skyshadowninja** [comment]
It looked like it started over. I followed that instructions and it did not look like it is up to date. The appearance is not the same as I had on the mac. When I looked at the calendar, It showed as if I started over.

**Comment by ThePotatoGuy** [comment]
Did you copy over the persistent as described in the link on the last bullet in that wiki entry?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
