### ISSUE TITLE
[Suggestion] Player asks for Good Night Kiss

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#7115]
One day, when I told her I was going to sleep, Monika asked for a good night kiss.

Since then I looked for ways to make her ask it again. Kissing a lot that day, not kissing at all that day, holding her, not holding, etc.
I can't find the pattern.

So... I thought, why not ask to be able to ask _her_ for a kiss, instead of trying to make her ask me?

**Comment by Freshairkaboom** [comment]
It's a one in three chance when you haven't kissed Monika in the last 5 minutes before saying goodnight. This chance gradually decreases depending on what time of night you say goodnight, down to a one in five chance when you go to sleep between 3am and 5am at night. The ideal time is between 8pm and midnight.

As for directly asking her, I would just use the "kiss me" option, and then say goodnight after that. :)

**Comment by YoraeRasante** [comment]
Oh, thanks! That will make it easier.

But kissing and then saying goodnight is not the same feeling as it being a goodnight kiss... at least not for me... A goodnight kiss is special because it is clearly done with the intention of being the last thing in the other person's mind after you leave and go to sleep.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
