### ISSUE TITLE
ddlc.exe not responding

### ISSUE THREAD

**Issue by ngphth** [Monika-After-Story/MonikaModDev#7116]
It was working fine as until yesterday, the program didn't even response no matter what i tried, resetting or refreshing the computer doen't work too.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6180931/traceback.txt) was updated on 25/12/2020 but i hope it helps.
please tell me if i need to provide anything else.

**Comment by kirillPro2020** [comment]
Did it work on previous versions?

**Comment by ngphth** [comment]
Yes, it did though I haven't updated it for a while so I can't remember
exactly what the previous version was. Definitely between 11.9 and 12.0
though ( it's version 12.0 right now according to the update folder)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Vào Th 2, 22 thg 3, 2021 vào lúc 19:53 kirillPro2020 <
***@***.***> đã viết:

**Comment by kirillPro2020** [comment]
There are 2 options here: 1) You have an old operating system. 2) incorrect installation.

**Comment by ngphth** [comment]
Turns out my battery was getting old, but thanks anway.
