### ISSUE TITLE
[Suggestion] - Monika, the Python Debugger

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7120]
I had a thought regarding the Python lessons Monika gives you. If you tell her that you're into programming (I believe that's an option currently?) or that you're writing some code of your own, than she'll say she's proud of you and be willing to check your code for any obvious errors.

Now, obviously, getting her to read and analyze text currently(?) hasn't been done like this before, but I think it would be feasible if it was kept simple, say, maybe only be able to read a maximum of 50 lines (most beginners start with small stuff, so this could be doable)? Also, it would probably be more feasible to have her simple note the errors in the code rather than attempt to run it, as doing so could potentially complicate things. (Besides, debuggers aren't meant to run stuff. That's the output console's job!)

**Comment by ThePotatoGuy** [comment]
I guess we could have her compile code and return back any errors. We shouldn't run code however, that can be considered an arbitrary code execution.

**Comment by Retrolovania** [comment]
That could theoretically work...

Only thing is, would the code need to be in a text file that she reads, or maybe have the code typed into the console that's used for the Python lessons?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it] - this is definitely something that needs more thought before considering implementation
