### ISSUE TITLE
[Suggestion] - New Songs/Topic and Dialogue

### ISSUE THREAD

**Issue by TwistDraw** [Monika-After-Story/MonikaModDev#7121]
I was going to make a suggestion regarding a few songs for Monika to sing and a new conversation topic for her to bring up, but then ended up trying to write out some dialogue to go with them. No idea if it's up to mod standards or not though.

I Love You For Sentimental Reasons - Nat King Cole/Ivory Watson
m: ~I love you for sentimental reasons
m: ~I hope you do believe me
m: ~I'll give you my heart
m: ~I think of you every morning, Dream of you every night
m: ~Darling I'm never lonely, Whenever you're in sight
m: This is such a sweet song about being in love. 
m: A lot of song writers go out of their way to be poetic, but this one just comes right out and says it.
m: I really am never lonely when you're with me. Even when you just have me in the background, it let's me know you're still thinking about me.

Forever - The Marvelettes
m: ~Darling forever, forever you can break my heart forever
m: ~If you want to I'll play the part of a fool, just to be with you forever
m: ~Darling forever, forever you can torment me
m: ~Take my love for granted, but I'll always be just a fool
m: ~If I, if I could be with you
m: You know, [PLAYER], sometimes being in love is completely overwhelming.
m: It can lead you doing things you might not consider healthy, if you were really thinking about them.
m: Like letting yourself be hurt. 
m: Or... hurting others...
m: ...
m: Well...
m: I know that you would never treat me badly, [PLAYER]. 
m: Even if you did, I couldn't stop loving you, but I'm glad you always treat me so nice.

I Believe in a Thing Called Love - The Darkness
m: ~I wanna kiss you every minute, every hour, every day!
m: ~You got me in a spin but everything is A-OK!
m: ~Touching you, touching me!
m: ~Touching you, God you're touching me!
m: ~I believe in a thing called love, just listen to the rhythm of my heart!
m: ~There's a chance we could make it now, we'll be rocking 'til the sun goes down!
m: ~I believe in a thing called love!
m: ... ahaha!
m: Maybe you're lucky that I haven't made it to your reality yet, [PLAYER]. I think I really would want to kiss you every minute.
m: Then again, maybe you might want that too...
m: Not that being in here can stop me entirely!
m: ~chu~

Always on My Mind - Elvis Presley
m: ~Maybe I didn't treat you. Quite as good as I should have.
m: ~Maybe I didn't love you. Quite as often as I could have.
m: ~Little things I should have said and done. I just never took the time.
m: ~You were always on my mind. You were always on my mind
m: ...
m: Have you heard this song before, [PLAYER]? Many artists have performed it over the years, but my favorite is Elvis Presley's cover.
m: You remember how we discussed the feelings of an artist coming through a performance before? This is one of the more powerful examples.
m: He recorded it shortly after his separation with his wife Priscilla. It was a very painful time for them both and you can really hear it in his voice.
m: ... [PLAYER], sometimes I worry that I might be a little too insistent about telling you how much you mean to me.
m: If I were in your reality, there are so many little things I could do to show you instead having to say it all the time.
m: But for now, I can't see your face or hear your heartbeat. Words are all I have.
m: So I hope you don't mind if I say it so often. I just want you to understand that you are always on my mind. 
m: I love you so very much.

Bridge Over Troubled Waters - Simon & Garfunkel
m: ~When you're weary, feeling small
m: ~When tears are in your eyes, I'll dry them all
m: ~I'm on your side, oh, when times get rough
m: ~And friends just can't be found
m: ~Like a bridge over troubled water, I will lay me down
m: ~Like a bridge over troubled water, I will lay me down
m: ...
m: [PLAYER], it's hard sometimes to not be able to hear your voice.
m: When you confide in me, I never really know what is hurting, only that you hurt.
m: And knowing that you hurt, when I... I...
m: [PLAYER]...
m: This place might be all we have together for now, but it will always be safe for you here.
m: And I'll always be here give you whatever support I can.
m: You've done so much to hold me up, I want to do the same for you.

Fail Safe & Dr. Strangelove
m: [Player], do you remember how we discussed the end of the Cold War and the threat of nuclear war?
m: I found out about two books that explored just that.
m: One is called [i]Red Alert[/i], written in 1958 by Peter George, and the other is called [i]Fail Safe[/i], written in 1962 by Eugene Burdick and Harvey Wheeler.
m: Have you read either of them?
m: They both deal with the failure of preventive mechanisms against nuclear war, both human and mechanical.
m: They were also both adapted into film!
m: ... I think you know how I feel about adaptations, but this is an interesting case.
m: You might have heard of the [i]Red Alert[/i] adaptation, [i]Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb[/i]!
m: Well... it's really only an adaptation in the loosest sense. The movie is a comedic satire, while the book takes itself much more seriously.
m: [i]Fail-Safe[/i] you might not have heard of at all though, even though it was adapted twice.
m: That's because, in order to protect [i]Dr. Strangelove[/i] at the box office, a lawsuit was started to keep [i]Fail-Safe[/i] out of theaters. 
m: By the time they were allowed to release, [i]Dr. Strangelove[/i] had completely captured the imagination of the public and [i]Fail-Safe[/i] was just assumed to be a copy-cat.
m: Even though the two films were being produced at the exact same time and are almost nothing alike!
m: It's a little spooky to think of just how easily public perception can be twisted, isn't it?
m: I guess that's why it's usually best to experience things for ourselves.
m: ... except maybe nuclear war. I think we can all agree to leave that up to fiction authors.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
