### ISSUE TITLE
How to set variable expressions for a line of Monika's dialogue

### ISSUE THREAD

**Issue by wboorman** [Monika-After-Story/MonikaModDev#7122]
I want to make a customizable reaction that I can change based off of certain game states.  I have _that_ logic ready to go, but I need some way to plug my chosen expressions and speeches into a standard renpy line.

A functional but smelly version of what I want goes something like this:
if a:
    m [hard-coded expression 1] "speech 1"
elif b:
    m [hard-coded expression 2] "speech 2"
#...and so on and so forth
elif z:
    m [hard-coded expression 26] "speech 26"

I want to improve on this functionality's efficiency (or at the very least readability) with something like this:
python:
    def getDialogue()
        #some such logic; merged into single method so I can compute both expression and speech with the same decision logic
        return ("variable expression", "variable speech")

$dialogue = getDialogue()
m dialogue[0] "[dialogue[1]]"

The speech I understand how to do.  Most of the "quip" logic works the same way, and I based what I wanted off of that, but I couldn't find anything in the code that could dynamically set the expression with the same ease.  What can I do to achieve this effect?

**Comment by multimokia** [comment]
use `renpy.show()` to show expressions. For example:
```renpy
python:
    chosen_exp = random.choice(["monika 1eua", "monika 1eub", "monika 3hua", "monika 5hubla"])

    renpy.show(chosen_exp)
```

So for your case:
```renpy
python:
    exp, dlg = getDialogue()
    renpy.show(exp)
    renpy.say(m, dlg)
```
is what we'd do

**Comment by wboorman** [comment]
Thanks, that did the trick!

My final answer wound up being:
```
        python:
            text_to_say = "[what Monika should say]"
            exp = "3esc"
            exp = "monika {}".format(exp)
            renpy.show(exp)
            renpy.say(m, text_to_say)
```
...and I'll just plug in my existing logic where appropriate.
