### ISSUE TITLE
some Pong Adjustements 

### ISSUE THREAD

**Issue by Barunxx** [Monika-After-Story/MonikaModDev#7124]
maybe if we could choose setting for pong like difficulty or max points to win would be better than losing to make Monika take it easy or winning to make Monika take it seriously

**Comment by fromulus** [comment]
I personally disagree.
The point here is to make it feel like you're actually playing against another person, not necessarily to make it more convenient.

You don't get to put your friends on "easy mode" when you're playing games against them, but they might go easier on you if they see you struggling against them.
Same thing here.

**Comment by Barunxx** [comment]
yeah, but. you can ask them to go easy on you, or you can tell them that you mastered the game and ready to take it all, right?
(i don't have friends so idk lol)
and a counter would be really nice

**Comment by Rai99** [comment]
#5727

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
