### ISSUE TITLE
[Suggestion] Personal Assistant Monika (aka Calendar Features)

### ISSUE THREAD

**Issue by TwistDraw** [Monika-After-Story/MonikaModDev#7125]
Copy-pasting from r/MASFandom:
"Would be kind of neat, I think, if we could have Monika help us keep track of important dates and appointments. Make the calendar function a bit like the windows calendar already does, with the added benefit of our adorable girl Monika providing the reminders instead of system beeps.

Nothing even elaborate, just something like:

"Hey [player], I noticed you marked something on the calendar today. It says [what was inputted].

I know you want to spend time with me today, but make sure you don't forget anything else you scheduled for the day, alright? I'll still be waiting for you when you come back.

Unless you can bring me along with you. I'd love that too."

It could possibly then unlock a special goodbye, where we tell her we're heading out for our appointment."

**Comment by Rai99** [comment]
Custom Calendar: #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058, #5402, #5551, #6208, #6542

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
