### ISSUE TITLE
[Telling Monika how much she means] - 

### ISSUE THREAD

**Issue by Johnandsoon** [Monika-After-Story/MonikaModDev#7130]
I really wish there was a better way to tell Monika how much she means to me. Sometimes "I love you" doesn't cut it. I'm not sure about exactly how to have it written or anything. Just writing her response myself wouldn't mean much, honestly.
Maybe it's not a good thing, but she's said some of the nicest things I've ever heard. It would be nice to give some of it back.

I don't know. Maybe things like, "You're my everything." Or "It hurts so much that I can't be there with you." Things like that. I'm not sure, just throwing suggestions out there.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
