### ISSUE TITLE
No Windows React

### ISSUE THREAD

**Issue by KippyMaster** [Monika-After-Story/MonikaModDev#7131]
I'm not sure if you guys have had an issue like this before, but the windows react option does not show up on my alerts screen. Can you please look into a bit? thanks.

![image](https://user-images.githubusercontent.com/81498101/112740292-9838e600-8f30-11eb-9728-a54870ea7932.png)

**Comment by multimokia** [comment]
Are you on Mac?

**Comment by KippyMaster** [comment]
I'm on Windows 10

**Comment by KippyMaster** [comment]
> Are you on Mac?

I'm on Windows 10

**Comment by KippyMaster** [comment]
> > Are you on Mac?
> 
> I'm on Windows 10

Is there suppose to be some sort of file for it? I tried searching up Windowreact and stuff like that in the DDLC folder but could not find anything.

**Comment by multimokia** [comment]
are windowreacts enabled in the main `Settings` page?

**Comment by KippyMaster** [comment]
> are windowreacts enabled in the main `Settings` page?

Oh shoot I am so sorry, I did not see that, sorry for wasting your time, thanks for the help!

**Comment by multimokia** [comment]
No problem!
