### ISSUE TITLE
Issue with hairstyle pack / not loading up (retrolovania-nesbows)

### ISSUE THREAD

**Issue by theEpicjosh** [Monika-After-Story/MonikaModDev#7138]
I have followed all of the instructions and troubleshooting steps to get Monika her hairstyle, and nothing from the guide is working.

- The sprite pack name is: retrolovania-nesbows
- The three gifts I already gave her are:
> - 8bluebow.gift
> - 8emeraldbow.gift
> - 8whitebow.gift
- And my log/spj.txt file is as follows:
> Mon Mar 29 23:17:06 2021
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.1
>
> [info]: reading JSON at 'c:\users\[username]\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_blue_retro.json'...
[info]: loading ACS sprite object 'retro_bow_blue'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_blue' loaded successfully!
>
> [info]: reading JSON at 'c:\users\[username]\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_emerald_retro.json'...
[info]: loading ACS sprite object 'retro_bow_emerald'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_emerald' loaded successfully!
>
> [info]: reading JSON at 'c:\users\[username]\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_retro.json'...
[info]: loading ACS sprite object 'retro_bow_normal'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_normal' loaded successfully!
>
> [info]: verifying hair maps...
[info]: hair ma

**Comment by ThePotatoGuy** [comment]
can you send the full log?

**Comment by theEpicjosh** [comment]
> can you send the full log?

Hello. Which log do you want me to send? Because, the one I put in the message is the full log in spj.txt. 

Every time I start up the mod, this log doesn't change much, other than the date.

**Comment by ThePotatoGuy** [comment]
close the mod first before sending the log.

**Comment by theEpicjosh** [comment]
Alright, here is the new log/spj.txt file after closing the mod.

> Mon Apr 12 22:27:13 2021
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.1
> 
> [info]: reading JSON at 'c:\users\joshu\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_blue_retro.json'...
[info]: loading ACS sprite object 'retro_bow_blue'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_blue' loaded successfully!
> 
> [info]: reading JSON at 'c:\users\joshu\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_emerald_retro.json'...
[info]: loading ACS sprite object 'retro_bow_emerald'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_emerald' loaded successfully!
> 
> [info]: reading JSON at 'c:\users\joshu\appdata\roaming\dokidokimodmanager\gamedata\installs\monika-after-story\install\game\mod_assets\monika\j\retroadamshow_acs_bow_retro.json'...
[info]: loading ACS sprite object 'retro_bow_normal'...
  [info]: loading Pose Map in 'pose_map'...
  [info]: Pose Map 'pose_map' loaded successfully!
  [info]: loading ex_props...
  [info]: ex_props loaded successfully!
  [info]: loading select_info...
  [info]: sel_info loaded successfully!
  [info]: 'entry' progpoint not found
  [info]: 'exit' progpoint not found
[info]: ACS sprite object 'retro_bow_normal' loaded successfully!
> 
> [info]: verifying hair maps...
[info]: hair map verification complete!
> 
> [info]: creating reactions for gifts...
  [info]: using generic reaction for ACS sprite 'retro_bow_blue', giftname '8bluebow'
  [info]: using generic reaction for ACS sprite 'retro_bow_normal', giftname '8whitebow'
  [info]: using generic reaction for ACS sprite 'retro_bow_emerald', giftname '8emeraldbow'
[info]: gift reactions created successfully!

**Comment by ThePotatoGuy** [comment]
What hair style is your Monika wearing?

**Comment by theEpicjosh** [comment]
It's "Down".

**Comment by ThePotatoGuy** [comment]
the Down hairstyle does not support the retro bows/ribbons. Switch to ponytail or other ribbon-supported hair styles for the these ribbons to appear.

**Comment by theEpicjosh** [comment]
Oh! Okay! Thank you! 👍
