### ISSUE TITLE
Topic Suggestion: Everywhere at the End of Time

### ISSUE THREAD

**Issue by AlmaHue** [Monika-After-Story/MonikaModDev#7139]
Idea from a conversation in the discord. A topic on Everywhere at the End of Time, a music-based psychological horror about dementia. I don't currently have any ideas for the dialogue, so I just want to at least put it out there.

Here's a [link to the aforementioned work](https://youtu.be/wJWksPWDKOc).

**Comment by ThePotatoGuy** [comment]
I swear I cannot escape this song

**Comment by imadeagithubaccountforthis** [comment]
yes

**Comment by Malicos** [comment]
will probably write something related to it, it's on my to-do list

**Comment by ThePotatoGuy** [comment]
leaving open as potentially in progress then

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
