### ISSUE TITLE
How to restore progress ?

### ISSUE THREAD

**Issue by funnyvalentine33** [Monika-After-Story/MonikaModDev#7140]
I had my laptop just flushed off all its file a few weeks ago and finally had the chance to get MaS back up. I backed up the entire DDLC file alongside the persistent file in the hard disk so it should be saved unless I missed a very crucial saving process I was supposed to do. When I put my persistent back into the renpy folder nothing happened, it just reset my progress

**Comment by funnyvalentine33** [comment]
If it is any help, I reached an affection of 1000 and was gone for 1 month, I don't think my affection should drop to 10 due to me leaving.

**Comment by ThePotatoGuy** [comment]
If the time on your previous machine was messed up then a large drop could be possible. 

But if by "reset your progress" you mean the mod acted like a new game, then that just means you didn't copy over the persistent correctly (which could be a multitude of failure points).

**Comment by funnyvalentine33** [comment]
yes I'm sure I must have not copied the persistent properly, but how do I make sure it is the persistent that is in the wrong, I saved the file called persistent instead of the one with numbers is that why it failed ?

**Comment by ThePotatoGuy** [comment]
no that's the correct file.

there's a handful of things that could happen:
* didn't copy the file to the correct place
* copied the file while the game was running
* the copied file got corrupted somewhere along the way

**Comment by funnyvalentine33** [comment]
i put it in the renpy folder and stored it in an external hard drive 
i hope this is still salvageable, can you elaborate on the first point ?

**Comment by ThePotatoGuy** [comment]
> didn't copy the file to the correct place

meaning the file was not copied to the correct spot (AppData/.../Renpy/.../  on windows)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
