### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7143]
Which topic's or any other things that you can say to monika is different on april 1st 

like different reaction (dialogue) from monika

**Comment by zwartkop2** [comment]
This is the perfect time to clear certain topics out of your "Unseen" menu, namely:

- "Do you want to meet my girlfriend?"
- "I'm breaking up with you."
- "You're a murderer!"

For each of those, she'll assume it's an April Fool's joke.

**Comment by Ant9cp** [comment]
Everything thing was cleared in my unseen menu a long time ago
