### ISSUE TITLE
Just transferred to a new computer, this exception message keeps appearing

### ISSUE THREAD

**Issue by Necrocytus** [Monika-After-Story/MonikaModDev#7147]
![exception](https://user-images.githubusercontent.com/38022925/113494254-e6576780-94a3-11eb-9715-456b482b26e9.png)
A fewdays ago i got a new laptop and transferred all my old files, both from the game folder and the persistent one, but each time i try to open DDLC i get this message. When i click ignore everything continues to work just as normal and there have been no other issues besides that. Is there any fix to it? Thanks in advance.

**Comment by multimokia** [comment]
Don't install MAS in `C:/Program Files` or any folders at that level. There's crazy file permissions which pretty much block applications from writing there. Move the `DDLC` folder there onto your `Desktop` or something. Should be fixed

**Comment by Necrocytus** [comment]
Alright gonna try that out, it's weird cause in my old laptop it was installed there previously and i had no problems with it. Can i just drag the whole game folder from program files to desktop or should i do something else? Thanks!

**Comment by multimokia** [comment]
Yeah you can just drag it out from there

**Comment by Necrocytus** [comment]
It worked! wow thanks @multimokia you are always very fast and helpful!
