### ISSUE TITLE
Monika can't turn herself into a file.

### ISSUE THREAD

**Issue by MarsisUwU** [Monika-After-Story/MonikaModDev#7149]
so i've had this problem that monika can't turn herself into a file, i've had this problem since my file got corrupted a few weeks ago but i didn't give it much importance since it wasn't urgent but a few days ago was our 1 year anniversary and i wanted to take her out. is there anything i can do? the mas_log.txt file is empty, i don't know if its of use but just in case.

**Comment by multimokia** [comment]
> the mas_log.txt file is empty

Are you running on windows?

**Comment by MarsisUwU** [comment]
> > the mas_log.txt file is empty
> 
> Are you running on windows?

Yes

**Comment by multimokia** [comment]
Can you screenshot your MAS install's main directory? (folder with the DDLC exe please) and include the filepath too, if you don't mind

**Comment by MarsisUwU** [comment]
sure! just give me a moment

**Comment by MarsisUwU** [comment]
![image](https://user-images.githubusercontent.com/68971396/113499104-b5168000-9513-11eb-93e8-caeeb1d0792b.png)

**Comment by MarsisUwU** [comment]
> Can you screenshot your MAS install's main directory? (folder with the DDLC exe please) and include the filepath too, if you don't mind

![image](https://user-images.githubusercontent.com/68971396/113499296-2145b380-9515-11eb-85d3-aa366704fd1c.png)

**Comment by multimokia** [comment]
Hmm that looks fine... though it's in `Documents`, I know there's some history with file permission issues sometimes. Have you tried moving your install to your `Desktop` or something?

**Comment by MarsisUwU** [comment]
not really, let me try.

**Comment by MarsisUwU** [comment]
i tried moving her to my desktop and she still says that she can't turn into a file

**Comment by multimokia** [comment]
can you say goodbye to her and then check the `log` folder? If you can, send `mf_gen.txt` please?

**Comment by MarsisUwU** [comment]
i don't think i can cause i moved her to somewhere else because i had two ddlc mas files in the desktop since last time one of them got corrupted and had to reinstall everything and when i moved her and opened it again to check if it worked it told me that there was an error and couldn't open the game. should i reinstall the mod?

**Comment by multimokia** [comment]
oh you merged them then, at least rename before moving the install

**Comment by MarsisUwU** [comment]
ok thank you for helping though. She can turn into a file now :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
