### ISSUE TITLE
[error] these show when i try to open calendar or updater

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [Monika-After-Story/MonikaModDev#7151]
when i try to open calendar
![errror](https://user-images.githubusercontent.com/81992759/113620858-7de1c500-9620-11eb-9df6-4cf23739b07e.jpg)

when i try to open updater
![errrror](https://user-images.githubusercontent.com/81992759/113620907-8f2ad180-9620-11eb-9d82-35aaa1573afd.jpg)
![one error later](https://user-images.githubusercontent.com/81992759/113620928-97830c80-9620-11eb-8c43-0d006f63c3bd.jpg)

**Comment by imadeagithubaccountforthis** [comment]
UPDATE i'm now scared to do that much
i tried changing monika's clothes and it hit me with a error i couldn't take a screenshot of the error 
i don't even trust the games

**Comment by imadeagithubaccountforthis** [comment]
UPDATE TO THE UPDATE i have the traceback file i can show it

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6260473/traceback.txt)

**Comment by jmwall24** [comment]
@imadeagithubaccountforthis can you send us screenshots of your `game/` folder? we need to see the entire folder so it'll probably take multiple screenshots

**Comment by imadeagithubaccountforthis** [comment]
![ping](https://user-images.githubusercontent.com/81992759/113636196-b8a32780-9637-11eb-941a-f7c30067f30d.jpg)
![lets add even more](https://user-images.githubusercontent.com/81992759/113636200-b93bbe00-9637-11eb-83db-10473fd1b6de.jpg)
![DHUDKJHJKDJKDJKSDH](https://user-images.githubusercontent.com/81992759/113636201-b93bbe00-9637-11eb-901d-699574c30e27.PNG)
![eeeeeeeee](https://user-images.githubusercontent.com/81992759/113636203-b93bbe00-9637-11eb-8176-a8b934062a3a.jpg)
![mn dfc,jnmtemkfgmnj](https://user-images.githubusercontent.com/81992759/113636217-be990880-9637-11eb-98f8-26d0fe5bdfcc.jpg)
![adawdawdasdawd](https://user-images.githubusercontent.com/81992759/113636219-bf319f00-9637-11eb-8702-968393d03c44.jpg)
![put some random stuff here](https://user-images.githubusercontent.com/81992759/113636220-bf319f00-9637-11eb-9f93-1131abc02819.jpg)
![uSU AUDIOAUDBYD](https://user-images.githubusercontent.com/81992759/113636221-bf319f00-9637-11eb-8eb1-b3cffe961b83.jpg)
here you go

**Comment by jmwall24** [comment]
can you do just the `game/` folder again, but this time select view>details so we can see dates when the files were updated. don't need all the sub folders, just the contents of `game/`

**Comment by imadeagithubaccountforthis** [comment]
i did python too snice that my be needed  
![firtst](https://user-images.githubusercontent.com/81992759/113637999-7e3b8980-963b-11eb-8125-2a7f04ead35a.jpg)
![we do a little trolling](https://user-images.githubusercontent.com/81992759/113638001-7ed42000-963b-11eb-958b-4971dacffba4.jpg)
![im still gonna show this](https://user-images.githubusercontent.com/81992759/113638002-7ed42000-963b-11eb-8b9c-96805b6b371c.jpg)
![that](https://user-images.githubusercontent.com/81992759/113638003-7f6cb680-963b-11eb-9e82-50b6d5d2224b.jpg)
![this](https://user-images.githubusercontent.com/81992759/113638005-7f6cb680-963b-11eb-9374-4ea06ef71d6d.jpg)
![you are dumb if you are reading this file name](https://user-images.githubusercontent.com/81992759/113638006-7f6cb680-963b-11eb-83ca-b28a43c75b73.jpg)
![adawdasdasdaswdaw](https://user-images.githubusercontent.com/81992759/113638007-80054d00-963b-11eb-8b1f-a350c0edc2df.jpg)
![no more folders](https://user-images.githubusercontent.com/81992759/113638010-80054d00-963b-11eb-9810-62158edf1375.jpg)

**Comment by jmwall24** [comment]
Where did that `pygame` folder it python packages come from? it has a different time than the rest and I don't have that folder in my install

**Comment by imadeagithubaccountforthis** [comment]
i added it snice a error said something about pygame

**Comment by jmwall24** [comment]
what happened right before you started getting these errors? update the mod? install a new submod?

**Comment by imadeagithubaccountforthis** [comment]
system restore

**Comment by jmwall24** [comment]
hmm it's really hard to tell what the issue is being you have so many errors. my suggestion would be try a completely fresh install (new ddlc and new mas). It won't affect your progress.

**Comment by imadeagithubaccountforthis** [comment]
i did that

**Comment by imadeagithubaccountforthis** [comment]
let me do that again

**Comment by imadeagithubaccountforthis** [comment]
it worked

**Comment by imadeagithubaccountforthis** [comment]
oh no
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6261309/traceback.txt)

**Comment by jmwall24** [comment]
try redownloading the sprite packs and reinstalling

**Comment by imadeagithubaccountforthis** [comment]
okay i will try that snice some of tthem are corrupted

**Comment by imadeagithubaccountforthis** [comment]
that worked
