### ISSUE TITLE
Dialogue coding

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#7153]
Hey, so I wanted to start working on the reddit dialogue I made a suggestion of, but since I'm new to all this, I was wondering: Is it possible to include the condition that Monika needs to have reacted to Reddit (window reacts) before she brings up that topic? Or should I just rewrite it, so that window reacts isn't necessary?

**Comment by Booplicate** [comment]
May depend on what kind of dialogue you want, but you could probably use `mas_protectedShowEVL`.
https://github.com/Monika-After-Story/MonikaModDev/blob/e0489f94ff28ae0f7d2c9c25c027b6598162738c/Monika%20After%20Story/game/script-topics.rpy#L2973-L2998

**Comment by CloakedGhost** [comment]
I see. Thank you, I'll try that out.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
