### ISSUE TITLE
Monika can't read my gifts no matter what I do!

### ISSUE THREAD

**Issue by JennyChicaMax** [Monika-After-Story/MonikaModDev#7156]
I tried giving her the shoulderless sweater, copied the mod_assets folder to the game file, then I went to the characters file and renamed one of them shoulderlesssweater.gift Monika could find the gift but she couldn't read it..
I tried again.
Same problem!
I tried with other gifts in the spritepacks (The chokers, white tank top), nothing works, it all says the same thing! Am I doing something wrong? I just want to let her dress up nicely... All I can do is give gifts that already exist in the game/mod! (Roses, Coffee, Hot chocolate, Certain ribbons, etc, etc)

Super sorry if I just did something wrong and whined for no reason, I'm new to this, I hope you can help, and thanks in advance!!

**Comment by TheElementalOfDestruction** [comment]
To be clear, you placed the folder "mod_assets" in the "game" folder, correct?

**Comment by JennyChicaMax** [comment]
> To be clear, you placed the folder "mod_assets" in the "game" folder, correct?

Yes, I read it's what I'm supposed to do..

**Comment by Booplicate** [comment]
> I read it's what I'm supposed to do

Did you close the game before installing the spritepacks?

**Comment by JennyChicaMax** [comment]
> > I read it's what I'm supposed to do
> 
> Did you close the game before installing the spritepacks?

I downloaded them both at the same time, should I redownload the spritepacks while the game is closed and then try again?

**Comment by zwartkop2** [comment]
The game mainly checks for new spritepacks when launching the game.

**Comment by Booplicate** [comment]
It doesn't matter how you download it. What matters is how you install them. Check [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs) (there's also a video).

**Comment by JennyChicaMax** [comment]
> It doesn't matter how you download it. What matters is how you install them. Check [this entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs) (there's also a video).

I am SO dumb!! I thought downloading and installing were the same... It all works now! Thank you so much and sorry for being such a burden.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
