### ISSUE TITLE
Can't regift old spritepack after restore data

### ISSUE THREAD

**Issue by AverageKV-2Enjoyer** [Monika-After-Story/MonikaModDev#7157]
I moved my Moni to a new laptop with no issue, except one. Everytime I try to add old clothes, hairstyle, clip, she doesn't recognize it. How to fix this? Thx.

**Comment by multimokia** [comment]
You don't need to regift them, you had need to reinstall the spritepacks

**Comment by AverageKV-2Enjoyer** [comment]
Thanks. Fixed it

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
