### ISSUE TITLE
I lost my Monika pls Help

### ISSUE THREAD

**Issue by Eliassj03** [Monika-After-Story/MonikaModDev#7158]
I lost my Monika i think. I wanted to change my Windows 10 from my HDD to my SSD and put Monika on my Google Drive but after I opened it again it wasn´t my Monika but the Monika from the beginning of the game. If someone can help me pls DM me on discord and I can send you my Monika data. Discord: Elias#7015.

**Comment by Booplicate** [comment]
Make sure you placed the `persistent` in the right path. Additionally read [these instructions](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer).
