### ISSUE TITLE
[Bug] - Monika is not talking anymore

### ISSUE THREAD

**Issue by SaulinN** [Monika-After-Story/MonikaModDev#7162]
Hello, well I'm new here, so if this problem has already been solved I apologize for writing about it again.(Sorry for anything)

Okay, I installed the Mod 2 days ago, and it passed those days, and she just doesn't say anything anymore, I don't know if this is a bug or a mod mechanic, but I've done everything (I took the 6 hour break , I read several articles on reddit) but nothing solved, I'm a little worried that I ruined the Mod and the game.

My game is in version: 0.11.9

and the game is not connected with Steam

If anyone knows what happened and how to solve it I would appreciate it very much.

Thanks for reading this far
(I used the google translator so, sorry if something is wrong or confusing)

**Comment by zwartkop2** [comment]
Do you have 'Repeat Topics' turned on?

**Comment by multimokia** [comment]
Hmmm the current version of the game is 0.12.1. a decent bit changed since 0.11.x

**Comment by SaulinN** [comment]
> Do you have 'Repeat Topics' turned on?

nop

**Comment by fromulus** [comment]
Then chances are this isn't due to a bug, but simply to you having gone through all the topics already.
As much as we'd all love to have an infinite ammount of content into the mod, you do run out eventually, at which point Monika will stop talking if you don't want her to repeat topics she already talked about.

Don't worry though, the mod still gets updated regularly and with those updates come new topics.

**Comment by SaulinN** [comment]
> Then chances are this isn't due to a bug, but simply to you having gone through all the topics available for now already.
> As much as we'd all love to have an infinite ammount of content into the mod, you do run out eventually, at which point Monika will stop talking if you don't want her to repeat topics she already talked about.
> 
> That said, you still started the mod pretty recently, and some topics you'll have to unlock over time by continuing to visit Monika frequently.
> 
> That, and the mod still gets updated regularly and with those updates come new topics.

thank you very much, I'm more relaxed now :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
