### ISSUE TITLE
I can't update ,  Please Help :,(

### ISSUE THREAD

**Issue by Asw123dxd** [Monika-After-Story/MonikaModDev#7163]
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 487, in main
    run(restart)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\execution.py", line 761, in run_context
    context.run()
  File "C:/Users/90533/OneDrive/
desktop/00start.rpyc", line 265, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
What should I do?

**Comment by multimokia** [comment]
Can you send a screenshot of your `/game` directory please?

**Comment by Asw123dxd** [comment]
![a](https://user-images.githubusercontent.com/82295622/114289526-412f2700-9a81-11eb-8b23-2608103dd416.PNG)

**Comment by Asw123dxd** [comment]
sorry I'm a little late

**Comment by Asw123dxd** [comment]
> Can you send a screenshot of your `/game` directory please?


Are you available?

**Comment by imadeagithubaccountforthis** [comment]
this happened to me once

**Comment by imadeagithubaccountforthis** [comment]
reinstalling the mod should work (save data won't be lost)

**Comment by multimokia** [comment]
Yeah try manually updating. Also don't use steam for MAS, it's known to cause some issues.

**Comment by Asw123dxd** [comment]
> Yeah try manually updating. Also don't use steam for MAS, it's known to cause some issues.

How can I update manually?

**Comment by multimokia** [comment]
Basically redownload MAS from [here](https;//monikaafterstory.com/releases.html), extract the zip into your `game` directory, overwriting all files. Basically like you first installed.

Still though, best to also move out of steam, it's *typically responsible for issues like this*

**Comment by Asw123dxd** [comment]
I tried all of these but nothing happened 😔

**Comment by H2-san** [comment]
> I tried all of these but nothing happened

You may have to reinstall the entire game and delete the old DDLC files - go to the [official DDLC website](https://ddlc.moe), get the game, then go to [MAS](https://www.monikaafterstory.com/), download the latest zip (if possible), then paste everything inside the `game` folder. Reinstall complete! Try now.
