### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7166]
Is it possible to delete chess from the game menu? because i just had enough! no one is going to change this anyway and no one is going to listen to me anyway, and i don't like it when people lie saying that chess is easier, 
i keep trying but i never won a single time, soooo i'm just done i don't mind losing sometimes, but every single time (literally)
 
just NO this is just a joke 😡

**Comment by 20RaVen23** [comment]
"When someone is losing it's the game's fault". You may want to check #6163 to see the changes because there are.
Just keep the practice and you'll eventually get better, after all you won't be good at something from the night to the next morning.

**Comment by Ant9cp** [comment]
Ohh the lies keep it up👍

**Comment by ThePotatoGuy** [comment]
next time save the game as a pgn and upload it here so we can see how the game plays out
