### ISSUE TITLE
Can we decorate the room?

### ISSUE THREAD

**Issue by Asw123dxd** [Monika-After-Story/MonikaModDev#7169]
I've always wanted to decorate this room. but I don't know how to do it. Can anyone know  help me?

(I use google translation)

**Comment by MetalBrother** [comment]
I think there is a submode for it, but I'm not sure, I also try to find it.

**Comment by 20RaVen23** [comment]
You can find the submod [here](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/tree/master), read the description of the same one to know how to add them.

**Comment by Asw123dxd** [comment]
> You can find the submod [here](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/tree/master), read the description of the same one to know how to add them.

Thank you so much !

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
