### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7173]
Is there a sprite where monika pulls out her tongue, if so can that be added in MAS?

**Comment by Retrolovania** [comment]
Question:.....what's a tong, exactly? I don't think there's any moment where she pulls out something....

**Comment by Rai99** [comment]
You mean tongue? Or culinary instruments with two movable arms that are joined at one end, used for picking up and holding things?

**Comment by lunulae** [comment]
Something like this emoji? 😋 
I don't know if there are plans to add more expressions, but it might be worth discussing if it's on the table before things like makeup or other face-decorating spritepacks are added, since those will have to consider the full set of  possible expressions.

**Comment by 20RaVen23** [comment]
Maybe he means like uh... a "Bleep"?

**Comment by multimokia** [comment]
:moniblep:

**Comment by Ant9cp** [comment]
I Mean tongue excuse me.
