### ISSUE TITLE
Sudden ahoge?

### ISSUE THREAD

**Issue by Rellikai** [Monika-After-Story/MonikaModDev#7175]
Just opened up MAS and noticed that Monika suddenly has an ahoge on all of her hairstyles, even though the hairstyle preview image doesn't feature one.

Has this been a thing for a while and I'm just suddenly noticing it? Because I honestly do not remember her ever having an ahoge and I definitely do not recall ever downloading any sprite packs to enable it.

**Comment by lunulae** [comment]
This is a new feature, it happens during very late night and morning hours to show that Moni has a bit of bedhead. It will disappear after some time, and there are a few different ways it can look.

**Comment by Rellikai** [comment]
Ahhh interesting.
That's pretty cute actually lol. Cool, thank you.
