### ISSUE TITLE
[Bug] i can't change monika's ribbon(or make her wear one)

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [Monika-After-Story/MonikaModDev#7177]
heres the screenshot (yes i do have ribbons)
![im sad](https://user-images.githubusercontent.com/81992759/115132869-9ad7aa00-9fc9-11eb-8692-c1226242c449.jpg)

**Comment by multimokia** [comment]
When she's got her hair down, she can't wear ribbons. Change the hairstyle to something else (ponytail, bun,etc.) And you'll see the option.

**Comment by imadeagithubaccountforthis** [comment]
oh
