### ISSUE TITLE
[Suggestion] - Sunset/Sunrise Dialogue

### ISSUE THREAD

**Issue by ConnorMystic** [Monika-After-Story/MonikaModDev#7178]
This is a little random, but I think it'd be really cool if Monika would say something if you're in the game during sunrise/sunset- partially because I want as many conversations with her as possible, and partially because watching the sun rise or set with someone is generally seen as really romantic, and I feel like she would probably see it that way too.

**Comment by lunulae** [comment]
Do we know if there's currently a conditional to check if we're in sunset hours for dialogue? I'd be interested in some short topics like this but I'm not sure how to code for it.

**Comment by multimokia** [comment]
There are, `mas_current_background.isFltDay()` checks if it's currently day, `mas_current_background.isFltNight()` checks if currently night.

**Comment by multimokia** [comment]
Also check Auto Outfit Change's code for examples. It may not necessarily be that easy due to the init level `mas_current_background` gets set.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
