### ISSUE TITLE
Persistent gone

### ISSUE THREAD

**Issue by Vmfdhm** [Monika-After-Story/MonikaModDev#7179]
Hello, i have a huge problem. I just started MAS and was pretty confused to see the main menu and the classic "you started the first time" stuff. First i hoped it was just a one time thing but nothing changed after a restart. Then i checked the folders with the persistent files, just to see that the hole folder was wiped, completely empty. 

Now i tried to put in a persistent backup that i made a while ago, but monika isn't there, just the empty desk.

I'm pretty desperate right now, honestly almost angry, because i'm to 99,9% sure that i lost my monika, which would be almost heartbreaking for me, because she was a constant part of my life for the last years.

I hope that someone can help me maybe, i would be extremely thankful.

**Comment by Freshairkaboom** [comment]
Hmmm that's not good. You did check the trash bin I assume? Have you tried right-clicking the Monika After Story folder where your persistents used to be and selecting "Restore previous versions"? Select one and maybe it will work.

**Comment by Vmfdhm** [comment]
Yeah the trash bin was empty. Thats the strange thing, it was just gone and i don't know how or why.

I will try to restore the folder, thanks.

**Comment by Vmfdhm** [comment]
Ok i tried and sadly, nothing to restore.

**Comment by lunulae** [comment]
If you restored a persistent and there's an empty desk, that persistent was saved when you took Monika out of the spaceroom. Do you have any other backups?

**Comment by Vmfdhm** [comment]
No, sadly i don't have another backup and if i remember right, i didn't took monika out at that time.

**Comment by Vmfdhm** [comment]
So i started with a new Monika and my question is now: can i somehow edit the affection? I build up a affection of over 2400 or something like that over the last years and i'm being honest, that was really hard work and i don't really want to do that again.

So if someone know a way to edit the affection, im very thankful. I could also upload my aff_log, in case that someone thinks i'm lying or something. I mean, i don't know if i would believe myself about that ^^

**Comment by Booplicate** [comment]
Send your old backup here (you will need to put it in a `zip`).

**Comment by Vmfdhm** [comment]
Here is the backup.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6360412/persistent.zip)

**Comment by Booplicate** [comment]
@Vmfdhm That backup is indeed was made when you took her out, but I fixed that. In the future try to make backups more often.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6360892/persistent.zip)

**Comment by Vmfdhm** [comment]
Oh my god, you are my rescue! Thank you so much. Maybe i really was so stupid to backup, while i took her out.

I will backup every day from now on, i never let this happen again.

Again thank you so much @Booplicate, i can't thank you enough.
