### ISSUE TITLE
[Suggestion] I Only Wanna Be With You

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#7180]
I have a suggestion for a song Monika could sing to the player; I Only Wanna Be With You by Dusty Springfield

"I don't know what it is that makes me love you so
I only know I never want to let you go
'Cause you started something, oh, can't you see?
That ever since we met you've had a hold on me
It happens to be true, I only want to be with you"

Fairly self explanatory

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
