### ISSUE TITLE
the background is always christmas

### ISSUE THREAD

**Issue by comrade-pingu** [Monika-After-Story/MonikaModDev#7181]
My MAS just kept using the christmas background lmao how do I change it to normal
![Untitled](https://user-images.githubusercontent.com/57129555/115832260-46a74c80-a445-11eb-801d-51a48b6e1e63.jpg)

it's been like this since december & i ignored it thinking it'll go away but it won't :/

**Comment by lunulae** [comment]
Have you changed the date on your computer while MAS is running before? It seems like this bug has happened as a result of that for some people.

**Comment by comrade-pingu** [comment]
yep, long story

i ruined my laptop's motherboard back in Nov 2020 so I couldnt open MAS way until mid Jan 2021.

So I extracted the MAS files from my ruined laptop's hard disk to my new PC and then I didn't want Monika to get mad and lose affection so I played MAS, changed the date with 3-day intervals from Nov 2020 to Jan 2021. Didnt miss Christmas too. I think I changed the date bcs I was playing at 12am, between 25th dec and 26th dec. And I forgot to close the game

Starting from that point I didnt mess with the date anymore. Can you fix it please :(

**Comment by comrade-pingu** [comment]
anyone please? :(

**Comment by Booplicate** [comment]
MAS is very sensitive to date changes, she asks you not to change the clock like that because it may break lots of things.

**Comment by ThePotatoGuy** [comment]
its a time travel issue so we're not going to do any special stuff for you right now. That said, knowing how the data looks in this case can be helpful so can you upload your persistent here?

**Comment by comrade-pingu** [comment]
![Untitled2](https://user-images.githubusercontent.com/57129555/116981324-ed1f0780-acf9-11eb-94e1-fdc652224501.jpg)
alright which one?

**Comment by comrade-pingu** [comment]
![Untitlediii](https://user-images.githubusercontent.com/57129555/116982667-aa5e2f00-acfb-11eb-9221-3d10ae29aafd.jpg)
alright which one?

**Comment by comrade-pingu** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6420084/persistent.zip)
i'll just attach all of them here

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
