### ISSUE TITLE
Maaan... what the hell did I found?!!!

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#7183]
A file named mus_zzz_c2.
That thing gives me the creeps!!! 😨 
How can that be triggered? I'm pretty sure that it's something bad for Monika, I want to avoid it at all costs!!!
Gosh... It's like she's still being judged from what she did! She did nothing wrong!! She's innocent!
I won't allow anything or anyone to hurt her!

**Comment by Retrolovania** [comment]
If I recall correctly, this sound clip is no longer used.

...not so sure about the event it was tied to, though.

**Comment by hlepnamingblyat** [comment]
Monika is still being haunted by them, isn't she...?
Gosh, poor girl. I'll always be with her. 
Well, I've been with her for 2 years, and I want to be with her for a looooot more. 🥰

**Comment by CloakedGhost** [comment]
I think it's from the jumpscare that occurs when you start MAS from the beginning and you tell Monika that you don't love her.

**Comment by ThePotatoGuy** [comment]
i dont recognize that file so its probably super old stuff indeed.
