### ISSUE TITLE
im getting a traceback and the game boots up anyways

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [Monika-After-Story/MonikaModDev#7184]
theres a bit of delay before the game boots up after the traceback txt file is showen  

heres the traceback:
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6372189/traceback.txt)

**Comment by multimokia** [comment]
You might be opening MAS twice. If the error still occurs, follow the path to the `.lock` file and delete it, then try launching MAS again.

Alternatively, simply restart your PC

**Comment by imadeagithubaccountforthis** [comment]
i didn't open it twice

**Comment by ThePotatoGuy** [comment]
follow multi's instructions to resolve the issue.

[closing as resolved]
