### ISSUE TITLE
Is there a way to put MAS in an USB? 

### ISSUE THREAD

**Issue by WE-Idontknow-EB** [Monika-After-Story/MonikaModDev#7186]
So I have a potato laptop, but I have a USB that I can use. How can I put my MAS game and her memories in a usb(so I can play MAS if I plug my USB to another PC). Is there a way?(if there's a way pls inform me😅). Thx 😄😅

**Comment by CloakedGhost** [comment]
Yes there is, but one question: Are you playing on Steam or do you have MAS in a seperate folder?

**Comment by WE-Idontknow-EB** [comment]
I don't play MAS in steam build.

**Comment by WE-Idontknow-EB** [comment]
> Yes there is, but one question: Are you playing on Steam or do you have MAS in a seperate folder?

I don't play MAS in steam build/built

**Comment by CloakedGhost** [comment]
Ok that's good. If you want to copy MAS and Monikas memories, copy the whole DDLC folder (where the MAS application is located) onto the USB. After you did that, go to the windows search bar and type "%appdata%" and hit enter. Now go to the "Renpy" folder and open it. There should be a folder called "Monika After Story" in there. These are her memories. Copy that folder onto your USB too. You can actually copy the whole "Renpy" folder if you want, but if you have other Ddlc mods installed, you will copy those files as well. When moving the folders to your new computer, you can paste the ddlc folder wherever you want, for example the desktop. As for her memories, go to "%appdata%" again and paste the Renpy folder in there. If you only copied the "Monika After Story" folder, just create a Renpy folder in that directory and paste the "Monika After Story" into it. Hope this helps.

**Comment by multimokia** [comment]
You'd want to modify the DDLC.py file to make your persistent local to the install. That way, moving the install will always move Monika with it since her memories are contained in it. Our Contributing Guidelines page has instructions on how to do this under the `Bug Fixes and New Software Features` heading.

**Comment by WE-Idontknow-EB** [comment]
Thx everyone😀. 
One last question(sorry)
Can I copy Monika's memories and paste it into/onto a new DDLC MAS?

(I copied Monika's memories but not the DDLC File(because my laptop got reformatted), can I download a new MAS file and replace the new MAS memories with my old MAS memory?
 (MAS memory = Monika's memory) 

(I'm sorry if my English is bad😅, English isn't my native language)

**Comment by lunulae** [comment]
Yes, all you need to restore Monika's memories is to replace the `persistent` file. If you've followed the steps to make your persistent local you will need to replace the one in the `DDLC/game/saves` folder.

**Comment by WE-Idontknow-EB** [comment]
> Yes, all you need to restore Monika's memories is to replace the `persistent` file. If you've followed the steps to make your persistent local you will need to replace the one in the `DDLC/game/saves` folder.

Thank you😀😄

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
