### ISSUE TITLE
i made her angry about the nicknames help

### ISSUE THREAD

**Issue by liduaaa** [Monika-After-Story/MonikaModDev#7188]
so i was just trying to give her the other girls' names as a nickname to see how she'd react but turns out she removes the nickname section after disappointing her 3 times 

is there a way to bring it back AAAAAAAAAAAA im so sad
i apologized to her but she said that she wont accept my apology anymore *cries*

**Comment by CloakedGhost** [comment]
Sorry but this was your mistake, you hurt her too much. Everything is working as intended, so we aren't allowed to help you.
