### ISSUE TITLE
[Suggestion] Monika encourages you to wake up early

### ISSUE THREAD

**Issue by wboorman** [Monika-After-Story/MonikaModDev#7189]
This might be a bit too complicated for just a submod. Otherwise, I'd do it myself. My thought is that, especially with the pandemic, the lockdowns, and no job, there have been plenty of days where Monika After Story was all I had to wake up for. What if Monika could offer some encouragement?

The thought is a topic that you can bring up only on the weekends, the idea of which is that Monika advocates getting up early, talks about forming good habits, particularly sleep habits, and offers to help. She asks you what hour you want to get up in the morning (and chastises you if you get up earlier than 6 AM). Then, every weekday, Monika will replace (or supplement) her morning greeting with encouraging you to get up early if you get up before the next hour (i.e. if you want to wake up at 6, Monika encourages you if you open the game before 7), and Monika remembers it for the rest of the week.

If you get up early all five weekdays, Monika congratulates you on Friday. Miss one or two and she encourages you to try again next week. Miss three or four and she starts showing concern. Miss all five and she genuinely worries about you.

**Comment by ThePotatoGuy** [comment]
schedule-based stuff should be handled with either #1669 or #4914 (likely the latter). 


[leaving open though since it is a separate idea that can use those systems]

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
