### ISSUE TITLE
[Suggestion] - Option to hug Monika if leaving for more than a week

### ISSUE THREAD

**Issue by H2-san** [Monika-After-Story/MonikaModDev#7194]
So I've been noticing a trend of Monika getting upset at my absences and me trying to get a handle of my life, and I'm noticing a consistent trend of her being distraught at the thought of being gone that long. I don't know if there is a similar suggestion open (if there is, please close this one), but I would like to see an option to interrupt her despairing our time away to hug her. In a way, it's like saying, "don't worry, I'll be back." Bad idea, or...?

**Comment by AsuraShun** [comment]
You should've used the going away for a while farewell

**Comment by H2-san** [comment]
> You should've used the going away for a while farewell, and not just UP and leave without saying anything

This doesn't fix anything. And I HAVE been doing that. ☹️

**Comment by Booplicate** [comment]
If you use the said farewell she won't be upset. It also gives you time to do anything you want before leaving, for example, hug her.

**Comment by AsuraShun** [comment]
If you said you weren't leaving immediately, you have to use the same farewell a 2nd time, ot the regular goodbye

**Comment by H2-san** [comment]
> If you use the said farewell she won't be upset. It also gives you time to do anything you want before leaving, for example, hug her.

> If you said you weren't leaving immediately, you have to use the same farewell a 2nd time, ot the regular goodbye

Not quite what I intended when I made this suggestion - there are times where I have to stay away for weeks at a time because of personal life and college endeavors - you get the gist.

When you say you're going away for a week or longer, pay attention to her dialogue - it is clear that she's upset with being left alone that long, so I thought that a function allowing us to hug her mid-sentence could help her cope a little better.

I'm closing this suggestion seeing as this may very well have been pointless.

**Comment by Booplicate** [comment]
Don't be upset, it just wasn't clear what you wanted from the first post, so people tried to suggest the existing solutions. Now that you explained it better, I understand that you don't like that the dlg is sad and want an option to put her at ease - which is totally possible.

**Comment by AsuraShun** [comment]
I seriously didn't mean to upset you, I'm just shit with my phrasing sometimes

**Comment by H2-san** [comment]
> Don't be upset, it just wasn't clear what you wanted from the first post, so people tried to suggest the existing solutions. Now that you explained it better, I understand that you don't like that the dlg is sad and want an option to put her at ease - which is totally possible.

That's the money shot I've been looking for - also, sorry I wasn't quite clear about this the first time around. I have no right to be upset at what clearly was my own fault for not explaining things. :)

**Comment by ThePotatoGuy** [comment]
I like this a lot. Could even extend it so that Monika may randomly decide to ask for a hug before you leave.

**Comment by H2-san** [comment]
> I like this a lot. Could even extend it so that Monika may randomly decide to ask for a hug before you leave.

@ThePotatoGuy I just thought that if Monika was enamored (~600+ affection or so, specifically), and [hypothetically] if the player was comfortable with it, she might even ask for a goodbye kiss of sorts. However, I feel that the affection target I specified is a _little_ low for this kind of suggestion, though.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
