### ISSUE TITLE
New Questions and A New Feeling

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#7196]
I had more ideas for questions so here I go.

Q: Why do you enjoy coffee/hot chocolate?

A: This can have a number of reasons such as its taste, warmth, or the sweetest answer being to simulate drinking together as a couple. I would personally go for all 3 simultaneously but its up to you guys.

Q: Do you get lonely when I am gone?

A: Again the reasons have a wide array of answers though if it were me, I would go with on how she doesn't feel lonely as she knows that we'll return soon right back to her side. Regarding that, this question could change based on the amount of affection that you have. Like my response, could be a high affection response.

Q: What are your eating habits?

A: It's a n interesting thought regarding her eating habits. Like does she eat/drink her needs? If so, when and what is it? There's potential as to what you can create this in to I believe.

Q: What happens when I minimize the game?

A: Finally, I've always wondered this myself. When we minimize the game, it begs what happens to her. Is there no effect or does her field of vision decrease as a result. I think this could be an interesting take on it.

Q: I'm feeling...Overwhelmed

A: Overwhelmed being you're bundled by lots of schoolwork/work. She can respond to this by comfort and urging us to rest if anything to save our energy. Another scenario could be at high affection, she'll offer to rest on her like the legendary lap pillow but that's few and far between and don't expect that to be added. Never the less, people tend to be exhausted so this emotion could be well implemented.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
