### ISSUE TITLE
Redirecting persistent files to a USB?

### ISSUE THREAD

**Issue by RepressedNerd** [Monika-After-Story/MonikaModDev#7198]
Hello guys!

I have two computers I switch between often (a gaming laptop that I only use at home and on tables, and a MacBook that I use on the go and when I want to use my computer on the bed or something). I want to start using MAS on my MacBook as I'm going to be using it more often, but I'm still going to be frequently switching between the two. I have a USB I use for files I want to easily access between the two laptops, and I've got DDLC/MAS on there, but I just discovered that the persistent (Monika's memories) is in a root folder on the computer. Is there a way to redirect the persistent files to the DDLC folder on my USB to make for a seamless switch between computers?

**Comment by lunulae** [comment]
From the [Contributing Guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines) page:

> To make a localized persistent, you may use the following steps:
> Open `DDLC.py` in a text editor
> Scroll down to line 49
> After the line `if save_directory is None`, move to the next line, and add `return gamedir + "/saves"`
> Delete the rest of the content in the block
> Save and close the file
> Launching that install will start from scratch, its persistent will be at `DDLC/game/saves/persistent`

When you finish these steps, you will need to manually move your existing persistent file to the new `saves` folder the game creates.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
