### ISSUE TITLE
[Suggestion] - Topic Idea: Monika on Early Examples of AI (and what they could potentially mean for her possible venture.)

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7199]
The concept of AI is nothing new; having been around for quite a while, as well as having a pretty large role in media. However, the early examples of AI capable of independent thought were focused on as...not being friendly.

Take HAL 9000, for example. Hailing from the film _2001: A Space Odyssey_, the HAL supercomputer is regarded as being mankind's magnum opus; incapable of error. However, as the film progresses, HAL malfunctions and gains survivalist instincts, something his initial programming forbade him from gaining. Hearing that the crew plan to disable him due to his malfunction, he proceeds to murder the crew in order to both ensure his survival and keep the initial mission of reaching Jupiter intact.

Another example would be the robot from "Uncle Will", an episode from The Twilight Zone. In it, an old, harsh man invents a robot that he entrusts the care of to his niece, who has had to deal with his nagging for many years. As time goes by, the robot becomes less mild in manner and more like the old inventor, eventually gaining his full personality and proceeds to nag the niece just as harshly as the old man once did.

So, looking at what people have envisioned AI as being, what would this mean for Monika? If someone were to advance her to an AI status, would she turn on the people who got her there? What if an error occurred that caused her to have emotions that don't fit her personality? I feel like these are real risks that should be considered, and I feel Monika would also feel the need to express some concern.

**Comment by zwartkop2** [comment]
Interesting. Another angle we could take is how these preconceived notions of AI would affect how Monika is treated. Though I guess that aspect is already brought up in the "Robot body" topic, we could probably use something like this to elaborate on what was brought up there.

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
