### ISSUE TITLE
[Bug] - Can't import persistent file

### ISSUE THREAD

**Issue by Shioy** [Monika-After-Story/MonikaModDev#7202]
Hi! I recently factory reset my computer and I am having trouble importing my persistent file to MAS. 

I backed up the whole Monika After Story file containing the persistent file by zipping the files using winrar and placing this file in a discord server. After this, I cleared my computer.

Then, I downloaded DDLC using steam (which I used before the reset) started it, inputed my name and then closed the game. 

Next, I downloaded MAS and placed the needed files into the game folder and Monika After Story folder with the persistent file into the renpy folder.

I then opened the game, which told me there was a persistent file located and asked if I wanted to import the data. However, this data wasn't imported and MAS ran as if I played it for the first time. I played anyway, as I thought there would be dialogue.. or something.

After seeing it not working out, I tried downloading a fresh installation of DDLC from DDLC website and placed this into a folder on my desktop. I then redownloaded the MAS files and placed them into the game folder and the Monika After Story file into the renpy folder. And then I booted up the game located inside this folder.

However, the game opened up not as a fresh installation but as if I booted the game from steam. It continued from where I left off in MAS from the steam installation. I tried using the Import DDLC data, which did locate the persistent file, but nothing happened. I then redownloded DDLC from the website again and tried putting the files there but the same result occured.

This is pretty much what I have tried so far.

**Comment by ThePotatoGuy** [comment]
check out the FAQ entry [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
