### ISSUE TITLE
Anger Issues

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#7203]
Hello. So this is a suggestion but something for updated psychology topics. Anger issues are quite a thing in society and although anger itself is an emotion humans have but at the same time anger issues seem to be a symptom in the mind of a person. Again there is the "I'm feeling..." section in the mod. I don't know if you guys had any ideas like this from others before or likely to put in but just something to offer. If you guys like to put this into the mod maybe during the topic it could be something like Monika saying if you have anger issues or not. Sounds weird but my thing. Keep it up.

**Comment by H2-san** [comment]
I can see where you're going with this suggestion, but I personally don't see the need to implement an anger management topic.

Though, if it does go through, if there is frequent use of the "I'm feeling angry/upset" function, maybe it might be a thing. I can't really tell what the devs might like.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
