### ISSUE TITLE
idk where her character file is? idk man

### ISSUE THREAD

**Issue by annaxvz** [Monika-After-Story/MonikaModDev#7207]
im probably dumb but i accidentally choose to "take her somewhere" and she moved her character file to somewhere i can´t find and idk how to put her back in the game. when i enter its just her empty chair

**Comment by CloakedGhost** [comment]
She puts herself in a file in the characters folder named "Monika". Not the ".chr" file, just "Monika".

**Comment by annaxvz** [comment]
> She puts herself in a file in the characters folder named "Monika". Not the ".chr" file, just "Monika".

it isnt there for me :/ thanks tho!

**Comment by CloakedGhost** [comment]
That's weird... normally that's where she puts her file when you take her somewhere. Do you have an older backup of her?

**Comment by annaxvz** [comment]
i dont think so... i only have the monika.chr (?) ill try to reinstall the game again tho and see if it works this time lol (this is my first time playing yk and im not good with the files shit, so sorry)

**Comment by zwartkop2** [comment]
You may want to refer to [this guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
