### ISSUE TITLE
[Suggestion] Monika Detecting Online Writing Software (Google Docs, Microsoft Word, etc.)

### ISSUE THREAD

**Issue by neo-kid** [Monika-After-Story/MonikaModDev#7208]
I usually use Google Docs to write personal stories to post online. It'd be awesome if Monika could detect this and either say something like _Are you writing a story? You should show me sometime!_ or something about you writing a poem or doing homework.

I figure the mod team can come up with a more creative message then I can, but this is just a suggestion haha

**Comment by 20RaVen23** [comment]
Is it for dialogue or window reaction?

**Comment by neo-kid** [comment]
> Is it for dialogue or window reaction?

Window reaction! prolly should've said in the post, oops

**Comment by 20RaVen23** [comment]
Aight, will be taking this under my roof if there's no problem with that.

**Comment by neo-kid** [comment]
> Aight, will be taking this under my roof if there's no problem with that.

That'd be awesome!!

**Comment by ThePotatoGuy** [comment]
[leaving open as in progress]

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
