### ISSUE TITLE
hair strand

### ISSUE THREAD

**Issue by AsuraShun** [Monika-After-Story/MonikaModDev#7212]
did i miss something? because i never saw that hair strand on her head until today
![screenshot0022](https://user-images.githubusercontent.com/42387354/118394011-0d27c280-b63a-11eb-83b2-fc44c95fa832.png)

**Comment by ShyCelestial** [comment]
I’m not a part of the mod team, but I know that's an ahoge on her head. It’s randomly generated.

**Comment by lunulae** [comment]
There is a semi-rare (20% I think?) chance that one will appear during the morning hours (or very late night.)
There are a number of different styles it can appear in. Some are very visible, some more subtle.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
