### ISSUE TITLE
[Suggestion/Contribution] - One HUNDRED New Reactions!

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7213]
Welp, it's been about nine months now since I started this relationship with Monika, so I figured I'd try something new this time for a contribution. This time, I made 100 new window reactions! These should, hopefully, make a great contribution to the current official list, assuming they're allowed.

With the enclosed fie, Monika will be able to react to:

   

- Half-Life
- Half-Life 2 
- Deux Ex
- Visual Studio Code
- Friday Night Funkin' (Offline Version)
- Calculator
- Yandere Simulator
- DOOM
- Mesen Emulator (An NES Emulator)
- Kega Fusion Genesis Emulator
- Picrew
- Notepad++
- Facebook
- Instagram
- Aseprite
- Steam
- Spotify
- Dan Salvato's YouTube Channel
- Garry's Mod
- Moonbase Alpha
- Among Us
- The DDLC For Fans By Fans Website
- Indeed - Job Searching Website
- SuperHot
- Minecraft
- DDLC's Website
- Monika After Story's Website
- eBay
- Amazon
- Official Nintendo Website
- PlayStation Website
- XBOX Website
- The VICE Emulators (Set of emulators designed for Commodore computers)
- Newgrounds
- Microsoft Word
- PowerPoint
- OneNote
- Access
- Publisher
- Excel
- UnderTale
- FL Studio
- iTunes
- Soundcloud
- The Oregon Trail
- Library of Congress Website
- Change.org
- Kickstarter
- Patreon
- The Urban Dictionary
- ZORK
- The Pirate Bay
- Python Official Website
- 15.ai
- Project Monika
- Genshin Impact
- Grand Theft Auto
- Mobygames
- Adobe Premiere Pro
- Photoshop
- The Project Libitina Website found in (sayori.chr).
- Camera (The application in Windows that almost nobody uses.)
- The Sayori jumpscare website. (sayori.wtf)
- The creepy Yuri website. (yuri.dance)
- "Pray Before The Head of Bob"
- FogCam
- Dancing Baby
- The Million Dollar Homepage
- Welcome to Netscape!
- Unity
- GameMaker Studio
- "Shrek" Google Search
- Source Filmmaker
- Norad Santa Tracker
- Unreal Engine
- Crazy Taxi
- DOSBox
- VirtualBox
- GIMP
- Task Manager
- Half-Life: Blue Shift
- Call of Duty
- DOOM Eternal
- Mortal Kombat
- The Game Theorists YouTube Channel
- Ren'Py's official website
- Fortnite
- Microsoft Flight Simulator
- Cyberpunk 2077
- Roblox
- Microsoft Solitaire Collection
- Tetris
- TikTok
- MSN
- America Online (AOL)
- WhatsApp
- Baldi's Basics
- Paint 3D
- Cortana
- Microsoft Teams

Enjoy! (I should mention that regex is not being used for these, so I might need to go back and redo them in order to accommodate the next update's use of that.)

[100reactions.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6489394/100reactions.zip)

**Comment by Retrolovania** [comment]
Big whoops. I forgot PRs existed, heh....

**Comment by Retrolovania** [comment]
Scratch that. I couldn't figure out how to get the PR process to work and I don't want to accidentally break anything either on my side or the mod's.

**Comment by multimokia** [comment]
See the [Submitting a Pull Request](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#submitting-a-pull-request) entry on our contributing guidelines to see about adding these.

**Comment by Retrolovania** [comment]
Ah, thanks. I'll give it a check.

**Comment by Retrolovania** [comment]
PR opened.
