### ISSUE TITLE
Developer Tool - relation to screen prepare?

### ISSUE THREAD

**Issue by TechNevio** [Monika-After-Story/MonikaModDev#7214]
When turning on developer mode
define config.developer = True (set it in
definitions.py, since it is already there)
I get the following error:

After initialization, but before game start.

File "game/advanced_scripts/zz_poemgame.rpy", line 300, in prepare_screen

screen mas_pg_textbutton_grid(words, row_info, col_info, xywh, bg_image=None, is_modal=False, _zorder=None, _style_prefix=None, _layer=None):

Exception: Properties are not allowed here.

Don't have a clue how that is related!

(My version is the one from Steam.)

**Comment by Booplicate** [comment]
What version of RenPy are you using and why do you need dev mode? Also it's recommended to use non-steam version of DDLC.

**Comment by TechNevio** [comment]
I am using the latest version of Renpy, i need DEV mode because it's a PAIN to restart the game everytime you do changes

**Comment by Booplicate** [comment]
That's your issue, then. You should use the same version DDLC used. But I will help you ahead and say that you don't need RenPy SDK, and that reloading won't work anyway.

**Comment by TechNevio** [comment]
Why won't reloading work ? xD sure it will lol

**Comment by Booplicate** [comment]
No, it won't. I'm telling you that to save your time, because I know how RenPy and MAS work. But you can try it yourself if you want.

**Comment by TechNevio** [comment]
ive literally seen ppl use the DEV mod refresh tool

**Comment by multimokia** [comment]
It's very broken on windows due to windowreacts (can only register one wndclass, this throws an exception on reload) among other things.

**Comment by TechNevio** [comment]
ok any idea what to do then?? I dont wanna restart the game every time

**Comment by multimokia** [comment]
If you're testing dialogue, paste the entire label into console, then call it. It overrides the old one

**Comment by TechNevio** [comment]
In wich console?? Just the console in the programm im using

**Comment by multimokia** [comment]
The Ren'Py console. Seeing as you've enabled developer mode, you can open it.

**Comment by TechNevio** [comment]
Yeah but thats my problem i cant activate DEV mode as you can see in the question i wrote on top

**Comment by Booplicate** [comment]
> That's your issue, then. You should use the same version DDLC used. But I will help you ahead and say that you don't need RenPy SDK, and that reloading won't work anyway.

This still applies.

**Comment by multimokia** [comment]
As @Booplicate said, you're using the wrong version of renpy, which introduces some breaking changes since the one DDLC was released on had.

You 
a) Don't need the renpy SDK, but instead can just put rpy files into the install and launch it
b) If you do wish to use the SDK, must then download the one corresponding to the version DDLC -- and by extension MAS, uses.

**Comment by TechNevio** [comment]
NVM I actually got it working thx for the help

**Comment by TechNevio** [comment]
Well NVM i didnt get it working......wich verstion of renpy should i use then?

**Comment by multimokia** [comment]
6.99.12.4

**Comment by TechNevio** [comment]
And you are sure this will work with dev mode then?

**Comment by multimokia** [comment]
I have developer mode enabled for my test install, so yes.

**Comment by TechNevio** [comment]
ok thx

**Comment by TechNevio** [comment]
My last question would be wich one?? There are three of them on the site
