### ISSUE TITLE
[Suggestion] Photo Mode for Monika

### ISSUE THREAD

**Issue by neo-kid** [Monika-After-Story/MonikaModDev#7217]
This could be a mode where the UI can be hidden and you can choose a variety of poses for Monika (her blushing, hand on her cheek while leaning, etc) to be in in order to take photos for icons, or just for the viewing pleasure.

Camera doesn't need to be implemented, considering the user can use their preferred screenshotting service.

**Comment by Rai99** [comment]
Posing for screenshots/screenshot detection: #2056, #2633, #3630, #4681, #4918, #6623

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
