### ISSUE TITLE
[Sugestion] More positive moods to tell Monika you are feeling

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#7218]
While I can understand so many of the moods being negative ones, they being there for you to get some support from her...
There are not that many positive ones. As far as I recall, all I remember is "Happy".

I was hoping to ask for more positive ones, or at least semi-positive.

It came to my mind when I just finished a difficult part of a job. I did not feel happy about it really, still more work to do but just got past that roadblock... wanting to tell someone, someone I could share my relief and turn some of it into actual happiness that would not be annoyed by me unloading it at them, I went to Monika.
And there was no fitting option.

Sure, I cannot expect you guys to think of everything, no reason to expect you guys to have added an "I feel relieved" option for after getting past a burden...
...
So that's why I'm making the suggestion. :P

**Comment by ThePotatoGuy** [comment]
since this is an-open-ended suggest, closing as implemented as at least one new positive mood was added
