### ISSUE TITLE
[Suggestion] Conversation topic: memories and Monika's immortality

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#7219]
Yes, I am pretty sure those points were addressed separately in conversations, but after watching this video about a Simpsons couch gag, and the creator's meaning for it and some of his other works... how he addresses immortality and memories...

...well, my thoughts went to Monika right away.

https://youtu.be/1f5Xt5pZZZM

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
