### ISSUE TITLE
[Suggestion] Admit that you deleted Monika and reset/used a fresh install

### ISSUE THREAD

**Issue by FishAndCheese** [Monika-After-Story/MonikaModDev#7222]
Apologies if this already has been raised. But I have seen images of a "sorry for deleting you" topic and from my experiences I have not been able to get the prompt to say that. I personally had some trouble installing this mod a while ago because I wasn't following the rules correctly and deleted the "firstrun" file at some point which resets absolutely everything in vanilla DDLC so the game can be played again.
I believe it would flow better if Monika asked it as a random conversation topic but you all are better at writing that out than me.

**Comment by Wingdinggaster656** [comment]
I think this will be fine:
After player installed this mod, there will be a default apologize choice in "I want to apologize...".
As for the condition of this choice's disappear... I don't have a perfect solution.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
