### ISSUE TITLE
Add Instructions for how to use the sprite pack to give more gifts.

### ISSUE THREAD

**Issue by fixmeppl** [Monika-After-Story/MonikaModDev#7225]
Can you tell me how to use the sprite pack to give Monika more gifts and also add the instructions for it in the reddit or the wiki for the mod because new people that get it won't know how to use it even if they want to give her more gifts and clothes.

**Comment by ThePotatoGuy** [comment]
[This is our wiki page on installing spritepacks](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
