### ISSUE TITLE
[Suggestion] - Adding a search bar to the Expression Previewer

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7229]
This idea's more of a quality-of-life thing than anything else.

Say you're working on a new topic, and you leave for a bit and return. If you're trying to look for the facial expression you set last based off the little code generated by the game, it'll be a bit tough narrowing it down until you find it so you can continue. I think adding a search bar that allows you to load an expression from a typed code would help shorten the amount of time it takes to get back to working on code.

**Comment by Booplicate** [comment]
I thought about that before. Not as much of a "search bar", but just an input field for exp code.

**Comment by ThePotatoGuy** [comment]
I think replacing the expcode with an interactable text field with the exp code would be great addition.

[closing until we look into it]
