### ISSUE TITLE
Hairstyle suggestion pigtails

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7233]
I would like to see monika having pigtails

Example like the shape of circus baby's pigtails from FNAF

**Comment by AsuraShun** [comment]
She already has twintails, which is a more advanced version

**Comment by 20RaVen23** [comment]
👀

**Comment by Ant9cp** [comment]
To: @AsuraShun
Not the twintails more like this

![3v785642bbo01](https://user-images.githubusercontent.com/71310908/119251381-9002cd00-bba6-11eb-9870-d14804468e91.png)

**Comment by 20RaVen23** [comment]
doesn't this cover it?
![hair-orcaramelo_usagi-back](https://user-images.githubusercontent.com/55263957/119251502-d7706580-bb74-11eb-9ed7-a332c28ba0b0.png)

**Comment by Ant9cp** [comment]
Actually Rather a shorter style

**Comment by Retrolovania** [comment]
Monika has long hair, so having a short hairstyle (like pigtails) would technically mean it was cut, which seems unrealistic given that there are other hair style choices that involve her hair being long.
If I recall, there may be a pigtails submod, but I don't remember where it is...
