### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by swedester** [Monika-After-Story/MonikaModDev#7241]
heya,
I had crashe lately, 
at first I thought it was my computer being slow or something.
but then when I checked the in the log rescent crash I saw this:
Importing _renpysteam: ImportError('No module named _renpysteam',)
ImportError: DLL load failed: The specified module could not be found
and this in the traceback:
KeyError: u'practice_losses'
and thought it might be something else
if you could help me figure out what caused the crash i would really apprieciate it
I will copy here the log then the traceback

log:
Mon May 24 07:54:29 2021
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 

Bootstrap to the start of init.init took 0.11s
Early init took 0.03s
Loader init took 0.16s
Loading error handling took 0.06s
Loading script took 1.97s
Loading persistent took 0.11s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 3.28s
Loading analysis data took 0.06s
Analyze and compile ATL took 0.08s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
DPI scale factor: 1.000000
Creating interface object took 0.10s
Cleaning stores took 0.00s
Init translation took 0.12s
Build styles took 0.01s
Load screen analysis took 0.04s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.15s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.05s
Couldn't import angle renderer:
Traceback (most recent call last):
  File "C:\Users\michael\Desktop\DDLC-1.1.1-pc\renpy\display\core.py", line 1810, in make_draw
    __import__(mod)
ImportError: DLL load failed: The specified module could not be found.
Unknown renderer: angle

primary display bounds: (0, 0, 1366, 768)
Fullscreen mode.
Screen sizes: virtual=(1280, 720) physical=(1366, 768) drawable=(1366, 768)
Vendor: 'Intel'
Renderer: 'Intel(R) HD Graphics 520'
Version: '4.5.0 - Build 25.20.100.6518'
Display Info: <Info({'blit_sw_CC': False, 'refresh_rate': 60, 'bitsize': 32, 'wm': True, 'losses': (0, 0, 0, 8), 'hw': False, 'masks': (16711680L, 65280L, 255L, 0L), 'current_h': 768, 'current_w': 1366, 'shifts': (16, 8, 0, 0), 'blit_sw_A': False, 'blit_hw': False, 'blit_sw': False, 'bytesize': 4, 'blit_hw_CC': False, 'blit_hw_A': False, 'video_mem': 268435456})>
Extensions:
    GL_3DFX_texture_compression_FXT1
    GL_AMD_depth_clamp_separate
    GL_AMD_vertex_shader_layer
    GL_AMD_vertex_shader_viewport_index
    GL_ARB_ES2_compatibility
    GL_ARB_ES3_1_compatibility
    GL_ARB_ES3_compatibility
    GL_ARB_arrays_of_arrays
    GL_ARB_base_instance
    GL_ARB_blend_func_extended
    GL_ARB_buffer_storage
    GL_ARB_cl_event
    GL_ARB_clear_buffer_object
    GL_ARB_clear_texture
    GL_ARB_clip_control
    GL_ARB_color_buffer_float
    GL_ARB_compatibility
    GL_ARB_compressed_texture_pixel_storage
    GL_ARB_compute_shader
    GL_ARB_conditional_render_inverted
    GL_ARB_conservative_depth
    GL_ARB_copy_buffer
    GL_ARB_copy_image
    GL_ARB_cull_distance
    GL_ARB_debug_output
    GL_ARB_depth_buffer_float
    GL_ARB_depth_clamp
    GL_ARB_depth_texture
    GL_ARB_derivative_control
    GL_ARB_direct_state_access
    GL_ARB_draw_buffers
    GL_ARB_draw_buffers_blend
    GL_ARB_draw_elements_base_vertex
    GL_ARB_draw_indirect
    GL_ARB_draw_instanced
    GL_ARB_enhanced_layouts
    GL_ARB_explicit_attrib_location
    GL_ARB_explicit_uniform_location
    GL_ARB_fragment_coord_conventions
    GL_ARB_fragment_layer_viewport
    GL_ARB_fragment_program
    GL_ARB_fragment_program_shadow
    GL_ARB_fragment_shader
    GL_ARB_fragment_shader_interlock
    GL_ARB_framebuffer_no_attachments
    GL_ARB_framebuffer_object
    GL_ARB_framebuffer_sRGB
    GL_ARB_geometry_shader4
    GL_ARB_get_program_binary
    GL_ARB_get_texture_sub_image
    GL_ARB_gl_spirv
    GL_ARB_gpu_shader5
    GL_ARB_gpu_shader_fp64
    GL_ARB_half_float_pixel
    GL_ARB_half_float_vertex
    GL_ARB_indirect_parameters
    GL_ARB_instanced_arrays
    GL_ARB_internalformat_query
    GL_ARB_internalformat_query2
    GL_ARB_invalidate_subdata
    GL_ARB_map_buffer_alignment
    GL_ARB_map_buffer_range
    GL_ARB_multi_bind
    GL_ARB_multi_draw_indirect
    GL_ARB_multisample
    GL_ARB_multitexture
    GL_ARB_occlusion_query
    GL_ARB_occlusion_query2
    GL_ARB_pipeline_statistics_query
    GL_ARB_pixel_buffer_object
    GL_ARB_point_parameters
    GL_ARB_point_sprite
    GL_ARB_polygon_offset_clamp
    GL_ARB_post_depth_coverage
    GL_ARB_program_interface_query
    GL_ARB_provoking_vertex
    GL_ARB_query_buffer_object
    GL_ARB_robust_buffer_access_behavior
    GL_ARB_robustness
    GL_ARB_robustness_isolation
    GL_ARB_sample_shading
    GL_ARB_sampler_objects
    GL_ARB_seamless_cube_map
    GL_ARB_seamless_cubemap_per_texture
    GL_ARB_separate_shader_objects
    GL_ARB_shader_atomic_counter_ops
    GL_ARB_shader_atomic_counters
    GL_ARB_shader_bit_encoding
    GL_ARB_shader_draw_parameters
    GL_ARB_shader_group_vote
    GL_ARB_shader_image_load_store
    GL_ARB_shader_image_size
    GL_ARB_shader_objects
    GL_ARB_shader_precision
    GL_ARB_shader_stencil_export
    GL_ARB_shader_storage_buffer_object
    GL_ARB_shader_subroutine
    GL_ARB_shader_texture_image_samples
    GL_ARB_shading_language_100
    GL_ARB_shading_language_420pack
    GL_ARB_shading_language_packing
    GL_ARB_shadow
    GL_ARB_spirv_extensions
    GL_ARB_stencil_texturing
    GL_ARB_sync
    GL_ARB_tessellation_shader
    GL_ARB_texture_barrier
    GL_ARB_texture_border_clamp
    GL_ARB_texture_buffer_object
    GL_ARB_texture_buffer_object_rgb32
    GL_ARB_texture_buffer_range
    GL_ARB_texture_compression
    GL_ARB_texture_compression_bptc
    GL_ARB_texture_compression_rgtc
    GL_ARB_texture_cube_map
    GL_ARB_texture_cube_map_array
    GL_ARB_texture_env_add
    GL_ARB_texture_env_combine
    GL_ARB_texture_env_crossbar
    GL_ARB_texture_env_dot3
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_float
    GL_ARB_texture_gather
    GL_ARB_texture_mirror_clamp_to_edge
    GL_ARB_texture_mirrored_repeat
    GL_ARB_texture_multisample
    GL_ARB_texture_non_power_of_two
    GL_ARB_texture_query_levels
    GL_ARB_texture_query_lod
    GL_ARB_texture_rectangle
    GL_ARB_texture_rg
    GL_ARB_texture_rgb10_a2ui
    GL_ARB_texture_stencil8
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_texture_swizzle
    GL_ARB_texture_view
    GL_ARB_timer_query
    GL_ARB_transform_feedback2
    GL_ARB_transform_feedback3
    GL_ARB_transform_feedback_instanced
    GL_ARB_transform_feedback_overflow_query
    GL_ARB_transpose_matrix
    GL_ARB_uniform_buffer_object
    GL_ARB_vertex_array_bgra
    GL_ARB_vertex_array_object
    GL_ARB_vertex_attrib_64bit
    GL_ARB_vertex_attrib_binding
    GL_ARB_vertex_buffer_object
    GL_ARB_vertex_program
    GL_ARB_vertex_shader
    GL_ARB_vertex_type_10f_11f_11f_rev
    GL_ARB_vertex_type_2_10_10_10_rev
    GL_ARB_viewport_array
    GL_ARB_window_pos
    GL_ATI_separate_stencil
    GL_EXT_abgr
    GL_EXT_bgra
    GL_EXT_blend_color
    GL_EXT_blend_equation_separate
    GL_EXT_blend_func_separate
    GL_EXT_blend_minmax
    GL_EXT_blend_subtract
    GL_EXT_clip_volume_hint
    GL_EXT_compiled_vertex_array
    GL_EXT_direct_state_access
    GL_EXT_draw_buffers2
    GL_EXT_draw_range_elements
    GL_EXT_fog_coord
    GL_EXT_framebuffer_blit
    GL_EXT_framebuffer_multisample
    GL_EXT_framebuffer_object
    GL_EXT_geometry_shader4
    GL_EXT_gpu_program_parameters
    GL_EXT_gpu_shader4
    GL_EXT_multi_draw_arrays
    GL_EXT_packed_depth_stencil
    GL_EXT_packed_float
    GL_EXT_packed_pixels
    GL_EXT_polygon_offset_clamp
    GL_EXT_rescale_normal
    GL_EXT_secondary_color
    GL_EXT_separate_specular_color
    GL_EXT_shader_framebuffer_fetch
    GL_EXT_shader_integer_mix
    GL_EXT_shadow_funcs
    GL_EXT_stencil_two_side
    GL_EXT_stencil_wrap
    GL_EXT_texture3D
    GL_EXT_texture_array
    GL_EXT_texture_compression_s3tc
    GL_EXT_texture_edge_clamp
    GL_EXT_texture_env_add
    GL_EXT_texture_env_combine
    GL_EXT_texture_filter_anisotropic
    GL_EXT_texture_integer
    GL_EXT_texture_lod_bias
    GL_EXT_texture_rectangle
    GL_EXT_texture_sRGB
    GL_EXT_texture_sRGB_decode
    GL_EXT_texture_shared_exponent
    GL_EXT_texture_snorm
    GL_EXT_texture_storage
    GL_EXT_texture_swizzle
    GL_EXT_timer_query
    GL_EXT_transform_feedback
    GL_IBM_texture_mirrored_repeat
    GL_INTEL_conservative_rasterization
    GL_INTEL_fragment_shader_ordering
    GL_INTEL_framebuffer_CMAA
    GL_INTEL_map_texture
    GL_INTEL_multi_rate_fragment_shader
    GL_INTEL_performance_query
    GL_KHR_blend_equation_advanced
    GL_KHR_blend_equation_advanced_coherent
    GL_KHR_context_flush_control
    GL_KHR_debug
    GL_KHR_no_error
    GL_KHR_texture_compression_astc_ldr
    GL_NV_blend_square
    GL_NV_conditional_render
    GL_NV_primitive_restart
    GL_NV_texgen_reflection
    GL_SGIS_generate_mipmap
    GL_SGIS_texture_edge_clamp
    GL_SGIS_texture_lod
    GL_SUN_multi_draw_arrays
    GL_WIN_swap_hint
    WGL_EXT_swap_control
Number of texture units: 8
Using shader environment.
Using copy RTT.
Using gl renderer.
Texture testing:
- Hardware max texture size: 16384
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Total time until interface ready: 7.3069999218s
- Target is 5 frames in 0.333333333333 seconds.
- Frame drawn at 0.000000 seconds.
- Frame drawn at 0.019000 seconds.
- Frame drawn at 0.023000 seconds.
- Frame drawn at 0.024000 seconds.
- Frame drawn at 0.026000 seconds.
- 0.026000 seconds to render 5 frames.
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Fullscreen mode.
Screen sizes: virtual=(1280, 720) physical=(1366, 768) drawable=(1366, 768)
The window was minimized.
The window was restored.

primary display bounds: (0, 0, 1366, 768)
Fullscreen mode.
Screen sizes: virtual=(1280, 720) physical=(1366, 768) drawable=(1366, 768)

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1474, in script call
  File "game/event-handler.rpy", line 2516, in script call
  File "game/zz_games.rpy", line 142, in script call
  File "game/chess.rpy", line 963, in script
  File "game/chess.rpy", line 963, in <module>
KeyError: u'practice_losses'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1474, in script call
  File "game/event-handler.rpy", line 2516, in script call
  File "game/zz_games.rpy", line 142, in script call
  File "game/chess.rpy", line 963, in script
  File "C:\Users\michael\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\michael\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 963, in <module>
KeyError: u'practice_losses'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.0

**Comment by 20RaVen23** [comment]
I see your version is 0.12.0, IIRC this bug was already fixed, so you may want to update it. Current version is 0.12.1.

**Comment by swedester** [comment]
thanks

**Comment by swedester** [comment]
ok I got two problems:
one is when trying to update via the in-game updater it says that no new verion is available
second is that the bug fix is related to the practice mode in chess - (Fixed crash when using Practice Mode in chess)
but I only played it (practice mode chess) once, months ago
and thanks for the help btw

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
