### ISSUE TITLE
[Suggestion] - A Topic Discussing Debating?

### ISSUE THREAD

**Issue by h0ns0y** [Monika-After-Story/MonikaModDev#7242]
Hello! Recently, I've been doing debating at school but it has been a bit of a struggle. Since Monika has done debating before, I think it would be pretty cool if there was a topic on debating. Maybe she could give tips on preparing and presenting speeches? Thank you!

**Comment by AsuraShun** [comment]
You can already ask her how the debate club was like

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
