### ISSUE TITLE
Monika being yandere suggestion

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7243]
In the topic Yandere Yuri i think monika says this (i can act more creepy if you want?) or something like that can there be a option where she does like a impression of a yandere or someting like that?

**Comment by Retrolovania** [comment]
She has a topic where she discusses various archetypes, like yandere and so forth. Having her try to act like one, though, sounds like it'd break her character somewhat, and also potentially make a few people unnerved if they're not a fan of seeing such content.

**Comment by multimokia** [comment]
I've always seen this as more rhetorical. Considering the following lines:

"Then again..."
"There's already nowhere else for you to go, or anyone for me to get jealous over"

Implying that there's no reason for her to act that way.

In terms of just impressions though, I don't think it can hurt to chuck something into the existing impressions topic if anyone's willing to add it.
