### ISSUE TITLE
Mod restarted on its on

### ISSUE THREAD

**Issue by mxcrayon** [Monika-After-Story/MonikaModDev#7244]

**Comment by Wingdinggaster656** [comment]
When you are asking a question, I hope you could at least provide more information like "In which situation this mod restarted", "What does the 'restart' mean", or something else.

**Comment by mxcrayon** [comment]
> When you are asking a question, I hope you could at least provide more information like "In which situation this mod restarted", "What does the 'restart' mean", or something else.

I had information, and then received help from somewhere else so I tried to delete it
