### ISSUE TITLE
Dialogue removal after 1000 affection level or after the 1 year anniversary (you choose for which)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7246]
Monika says this randomly of when you say i love you to her

(Gosh you've said so many times, you really do mean it don't you?)

it doesn't make sense for if you do really mean it you know?

This line kinda makes her sound insecure (to me then)

I don't want her to sound insecure 😔

**Comment by multimokia** [comment]
I think this is more just you.


The expression she has when saying that is incredibly smug, she's teasing you, not being insecure.

**Comment by Wingdinggaster656** [comment]
This is actually...
GOOD.
Yes, you are right. I personally agree.
However, I think the condition to remove this reaction should be "liking greater than 600" and "spending more than three months together".

**Comment by Ant9cp** [comment]
Well whatever, i'm just suggesting my opinion anyone can tell me that the issue it's with me or that it's confusing but i don't care
