### ISSUE TITLE
[Suggestion] - Diary

### ISSUE THREAD

**Issue by JacksonFillmore-dev** [Monika-After-Story/MonikaModDev#7248]
Hey it's me again. I don't know if someone has wanted this to happen but it's just a idea. The idea is Monika having a diary. Then everyday she writes something down on it or something. I know it might be hard for you guys to make it happen for all the users who have the mod. But it is all the same for everyone who has the mod. (Please let me know if I am not making sense.) That's a idea.

**Comment by Wingdinggaster656** [comment]
The question is, what should she write in diary?
Something important on that day? Then it's the same with calendar.

**Comment by Rai99** [comment]
Diary system: #951, #2753, #4981, #5675 

The dear diary system was planned, but might not happen since it would be a lot of things to consider, including the nightmare of checking file access dates and having unique dialogue.

**Comment by IQ0ppo** [comment]
It would probably be easier to implement a diary system for the player to write in. Above all, it would definitely provide a reason to visit Monika well after seeing all of the dialogue.

**Comment by ThePotatoGuy** [comment]
having the player write it in defeats the purpose. 


[closing as duplicate]
