### ISSUE TITLE
[Suggestion] Monika - Weekend topic

### ISSUE THREAD

**Issue by Freshairkaboom** [Monika-After-Story/MonikaModDev#7255]
After a long week at work, Monika talking about how it's weekend would be really nice. I'm thinking of making this topic myself, but I'm unsure if there already is a persistent for weekend specifically, or if I have to read off a specific timedate or something. I could try making one, but people have different ideas of what weekend means, so maybe the player could somehow tell Monika what their weekend looks like, and that sets the prerequisites for the topic to be called?

If anyone wanna collaborate on this, don't hesitate to let me know :) No, there's no coincidence I'm making this issue on a Friday. Happy weekend folks!

**Comment by fromulus** [comment]
I remember there being a greetings that would only trigger on monday mornings, I'm not sure if it's still in the mod (haven't seen it in a long time) but that would probably be a good place to start.

That being said, I think it might be worth waiting for time concern overhaul, that way we could be more sensitive to which time of the weekend we're at.
After all, I'd assume such a topic would have a different tone to it between a friday afternoon/evening when the weekend is just starting, and on a sunday where the anticipation of the new week is begining to kick in.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
