### ISSUE TITLE
[Suggestion] - Gifts!

### ISSUE THREAD

**Issue by niapng** [Monika-After-Story/MonikaModDev#7256]
I thought, as an artist, that would be wholesome if you can give Monika drawings (or images) as gifts, and in response, she could put them in the wall at the background.

**Comment by ThePotatoGuy** [comment]
see #5345. I'm currently working on [phase 2](https://github.com/Monika-After-Story/MonikaModDev/pull/7145) of the implementation.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
