### ISSUE TITLE
New game suggestion checkers

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7257]
Has anyone ever thought of suggesting checkers? well i am right now 
I think it would be interesting to play this with monika and checkers is similar to chess i think

**Comment by Rai99** [comment]
Checkers: #829, #1629, #2014, #3221, #4913, #6285

**Comment by Ant9cp** [comment]
If it has alot of duplicates will it eventually be accepted?

**Comment by Booplicate** [comment]
It's been accepted already, you can check the first issue (and probably the rest) for more info.

**Comment by Ant9cp** [comment]
👍
