### ISSUE TITLE
[ Suggestion ] - Monika with make-up!

### ISSUE THREAD

**Issue by niapng** [Monika-After-Story/MonikaModDev#7264]
As an artist i thought that would be great if Monika could wear make-up or nailpolish. It could be like the first time she chages her clothes, saying something like she wants to look different -there is a dialogue where she says that she is envious of the people of our reality, for having so many options when it comes to dressing and such.
I don't know about programming at all, so i'll just be able to do the sprites!

**Comment by ThePotatoGuy** [comment]
see #5429

Currently we don't have the technical capability to support dynamic makeup. But if there were a set of sprites to work with I could definitely up the priority of getting that dev ready.

Nailpolish can be done as an ACS since each pose can be assigned a separate image.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
