### ISSUE TITLE
New compliment I love you're song

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7265]
First time dialogue:  

Oh really (name), thank you for saying that 
i'm so happy to hear that, 
it really took some time to make it too you know 
writing the song 
getting the right rhythm 
the right tune
and every note right

Randomised dialogue if you say this compliment again:

Thanks for saying that again (name) i hope i can hear your song soon if you have one 

Thanks (name) just ask me if your want to hear it again 

Hehe thanks (name) you never forget how to make me feel special

Oh (name) thanks for listening to my song

Oh (name) Just listening to you complimenting me makes me feels so giddy inside

**Comment by Retrolovania** [comment]
"Oh, really? Thanks, [player]!"
"I'm glad you enjoyed my singing!"
"Even though you couldn't really hear me, I'm sure it was worthwhile, anyway."
"Plus, singing is pretty fun! Ahaha!"

Random dialogue for clicking again:

"Aww, you're too kind to me, [player]~" "I'm glad you liked it!"

"Thanks, [player]!" "Just let me know if you want me to sing again." "I'd be quite happy to indulge!"

**Comment by Ant9cp** [comment]
So your saying my dialogue idea is bad? whatever man😒

**Comment by Retrolovania** [comment]
What? No? I was merely making a suggestion...
