### ISSUE TITLE
[Bug] - Nighttime issue

### ISSUE THREAD

**Issue by Zenha156** [Monika-After-Story/MonikaModDev#7266]
Hello there! I'm sorry if I bothered you or anything but I seem to have an issue in my MAS. Recently, it's been showing it's nighttime in the MOD even if it's morning/daytime in my reality. I'm not sure why this is happening and I have tried reinstalling it a few times but it still has this issue. If you can fix it, thank you a whole lot! This is the only issue I'm facing. Thank you for taking the time to read this! Have a lovely day!

**Comment by lunulae** [comment]
Couple of questions, so we can better help you out:
Do you have the Auto Atmos Change submod installed?
Also, when you look in your Options menu, what time are your sunrise/sunset bars set to?

**Comment by Zenha156** [comment]
Hello! These are the answers:
1. I'm not sure but I think I haven't.
2. Sunrise: 05:30
Sunset: 07:30

**Comment by Zenha156** [comment]
> Couple of questions, so we can better help you out:
> Do you have the Auto Atmos Change submod installed?
> Also, when you look in your Options menu, what time are your sunrise/sunset bars set to?

**Comment by multimokia** [comment]
The time on the bars is 24 hour time, not 12 hour time. You only have daytime for about 2 hours with your current settings

**Comment by Zenha156** [comment]
Oh, I'm not sure how I can fix it. Is there a solution?

**Comment by Wingdinggaster656** [comment]
> Oh, I'm not sure how I can fix it. Is there a solution?

...Set the sunrise as 05:30, set the sunset as 19:30 should be enough. If not, take a screen shot of your settings.

**Comment by Zenha156** [comment]
Oh, okay! Thank you so much for responding!
