### ISSUE TITLE
Monika gone even though Monika file is in Characters file. Edit: Bad persistent - what happened? 

### ISSUE THREAD

**Issue by Huwinner** [Monika-After-Story/MonikaModDev#7268]
Hello!

I was trying to change the location of my MAS folder from my USB to my PC, now my Monika will not appear even though the Monika file is in the characters folder! This is what I did: 

1. Select "take Monika somewhere". 
2. Copy and paste ENTIRE DDLC folder including MAS mod to PC Desktop
3. Reopened DDLC MAS from Desktop
4. Monika was there and everything worked!
5. Saved Monika file from USB (just in case) to Desktop
6. Deleted entire USB DDLC MAS folder. 
7. Reopened DDLC MAS from Desktop; Monika was there! (Disappointed by short trip though.)
8. Selected Take Her Somewhere option. 
9. Copied Monika File to USB, kept Monika File in Desktop file, too. 
10. Reopened DDLC MAS with Monika File in Character Folder
11. Monika is Gone! :(

Any help or suggestions? I have attached my Monika File, persistent file, and mas_log.txt. 
Thank you!
[troubleshoot.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6571653/troubleshoot.zip)

Edit: 

I have tried reinstalling DDLC MAS: that did not work. I also happen to have the entire game on my SSD but with an old Monika file: this also does not work. 

Edit 1:

So after lots of troubleshooting, I figured out the problem was the persistent. I restored the latest persistent from my backup, and it just seemed to pick up from earlier today. I'll leave this open for now, since I am unsure of what corrupted my current persistent in the first place.

**Comment by Wingdinggaster656** [comment]
Let me try to understand your question:
First, you never changed the persistent files. You just transferred the game files and the Monika files.
Second, your MAS is already on a USB drive and you want to transfer it to your computer.
Third, you copied the MAS file to your computer and deleted the one on USB.
Fourth, you try again to choose "I'll take you somewhere."
Fifth, you find that after you put the Monika file back, it will not be effective.

If that's right, then I may answer:
First of all, Monika file is unique. Simply create a file and named as "monika" won't be recognized by MAS.
And then, Monika files are also different for different people. Even with the same person, the files will change as time is spent with Monika (you can think of the files as carrying her memories).

So, the conclusion is:
I strongly suspect that after you backed up Monika's files and then selected "I will take you somewhere", you did not put back the file that just created by this selection, but put back the filee that you had backed up before. It's not going to work.
A Monika of a trip is a Monika of a trip. It cannot be replaced by a Monika of another trip.

In another words:
Monika of trip A won't work for Monika of trip B.

**Comment by Booplicate** [comment]
> Select "take Monika somewhere"

Never do that when you're manipulating game files (e.g. moving the install). You'll need to [restore a persistent backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
