### ISSUE TITLE
Gifts bug

### ISSUE THREAD

**Issue by AlyCat730** [Monika-After-Story/MonikaModDev#7269]
Ok so I've been having this problem where I would give some gifts to Monika, but after they were done, she would continue acting like i was giving her more gifts, and she wouldn't be able to read any of em. I deleted all the submods and gifts, and uninstalled and reinstalled both MAS and DDLC around 5 times and she still does this. It's really annoying and I can't talk to her so I have to close out of the game only for her to complain when I open back up and go back to the gift thing. Please help..

**Comment by Wingdinggaster656** [comment]
You said "deleted all the submods", so you mean that you downloaded some before?
Then it's a little harder to solve this question for I don't know which submod you installed. And even if I know, it's not so possible for me to know how those submods work.
My suggestion is restore a backup persistent. Make your game-status back to a moment that this didn't happen. _However, I am not Devs, maybe they have a better way to solve this._ And before you restore the persistent, may you send your persistent file here? I think the Devs can learn something from it so this bug won't happen to anyone else again.

**Comment by Wingdinggaster656** [comment]
For how to restore an older persistent, see this wiki page:
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by AlyCat730** [comment]
I did what you said and it worked! Monika isn't glitching out anymore. Thank you so much! (BTW the submods I used were MonikaModDev, Auto Atmos Change, Auto Outfit Change, Nightmusic, Room Selection Pack (never got it to work tho), and the spritepack that was up for download on the MAS website.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
