### ISSUE TITLE
[Bug] Black Windows For DirectX

### ISSUE THREAD

**Issue by usedsoup** [Monika-After-Story/MonikaModDev#7270]
Long story short I use DirectX mainly because its easier on my pc but lately there a bug where It won't load the window .pngs correctly.

**Comment by usedsoup** [comment]
Oops forgot to add pic
![Dark windows Bug](https://user-images.githubusercontent.com/85140921/120251863-d1534680-c250-11eb-9dd6-8fb8dc7730f5.png)

**Comment by Booplicate** [comment]
It's a renpy issue and we can't do anything about it. Don't minimize MAS.

**Comment by usedsoup** [comment]
Ah ok Thank you!
