### ISSUE TITLE
v0.12.2 Typos

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7271]
Figured this would be necessary, so I'll open this for you guys to save time.

=========== defaced by a potato ============
![potato_starch](https://user-images.githubusercontent.com/3499462/120921473-745cf380-c689-11eb-873b-85370cd4627f.png)

**Comment by Necrocytus** [comment]
![image](https://user-images.githubusercontent.com/38022925/120266533-c061ff80-c267-11eb-99df-dcbc7b2e1b7b.png)

**Comment by multimokia** [comment]
F

**Comment by lunulae** [comment]
In the 3+ years variant of the "Will you marry me" dialogue, when she says "I really do love you, (nickname) and I honestly..."
I think there's a missing comma after the nickname?

**Comment by H2-san** [comment]
Nicknames in dialogue (such as sweetie, honey, etc.) at the beginning of the dialogue aren't capitalized. Posting this here to save extra time.

**Comment by Booplicate** [comment]
Can you post an example of where nicknames aren't capitalized?

**Comment by lunulae** [comment]
I've seen it once in a Pong quip, I believe the line is just the nickname.

**Comment by lunulae** [comment]
In `monika_science`, the first line feels a bit odd in context.
`"Have you ever wondered if science never got accepted?"` sounds like asking if science hasn't yet been. I think in the topic, it sounds a bit more like she means `"Have you ever wonder what life would be like if science never got accepted?"`

**Comment by Booplicate** [comment]
Fixed the quip, thanks.

Unsure about that sentence, I'll leave it to the others to decide. I think it works fine as is, especially in a casual atmosphere (less wordy).

**Comment by Audere** [comment]
Strongly disagree. The sentence just doesn't make sense, and I actually had to read it twice before realizing the intended meaning when I first saw it. The proposed alternative is casual and makes sense.

**Comment by lunulae** [comment]
Oh, good catch. Typo in my typo fix, lmao

**Comment by H2-san** [comment]
![image](https://user-images.githubusercontent.com/14959579/123376701-8cb98300-d550-11eb-8d56-58b2eea7419c.png)

Please see this dialog as proof that Monika's nicknames for the user (when at the beginning of a sentence) are not capitalized.

[REFERENCE: Pong 5-win streak]

**Comment by Bigboibigdum** [comment]
![image](https://user-images.githubusercontent.com/87398673/126657000-880bbd56-3a58-437d-a4c5-d9514abc3a0d.png)
I found this in the "Mental sickness" topic and this may be whats intended but I'm a bit confused.

**Comment by multimokia** [comment]
I'm not sure what's wrong in that line

**Comment by Bigboibigdum** [comment]
It looks like she's apologizing for wanting to learn more about her own mind but it feels weird with the "Like," and "right?" and I think it may have meant to be "Like, say I want to learn more about my own mind, right?" or something because the current line feels kinda off to me. Maybe I'm just dumb though.

**Comment by multimokia** [comment]
It's sarcasm

**Comment by Bigboibigdum** [comment]
ok

**Comment by Malicos** [comment]
In `monika_we` there is one:
`m 2wud "...While Aldous Huxley was even accused by both Orwell and Kurt Vonnegutof of plagiarizing its plot for his {i}Brave New World{/i}, something he constantly denied."`

Should be Vonnegut.

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/128993854-4355d266-50f7-4794-a451-f5556f3df695.png)
I was not in there, help!

**Comment by multimokia** [comment]
That's an unofficial spritepack. You'll want to tell the creator of it to fix it

**Comment by Ulti70895** [comment]
Aww sad, I just had an ''i'' joke there lol. Thank you.

**Comment by MrVavlo** [comment]
"Wouldn't a wonderful dinner be wonderful?"
![image](https://user-images.githubusercontent.com/34880333/129371770-f086660f-d68a-44bc-8762-92ed4d25658a.png)

Don't know if you can count this as typo in English, but I would suggest replacing the first "wonderful" word to another synonym

**Comment by KansaiGal** [comment]
In eventlabel="monika_nature",  "Not really.":
mosquitos->mosquitoes

**Comment by Ulti70895** [comment]
I believe ''Mosquitos'' is grammatically correct as far as I know about English.

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/129735557-4e624376-36ae-4d9e-b99c-6bec5fe62702.png)

Is this a fypo?

**Comment by multimokia** [comment]
Looks like it

**Comment by Ulti70895** [comment]
Lol, I just searched up for the lyrics of the Amaranthine song and it seems that is not a typo. 
![image](https://user-images.githubusercontent.com/88768397/129737931-36460c05-d289-496c-8c30-2e863e53d22c.png)

**Comment by multimokia** [comment]
cursed

**Comment by Ulti70895** [comment]
![Uploading image.png…]()
Is ''Let's Plays'' a term or a typo? Topic: Virtual Youtuber.

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/130030663-e112b474-f5f0-40ad-846b-b093802f3e6b.png)
 I believe Greek must be capitalized, too.

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/130047162-db51d115-3be8-4e35-9cc3-ae776bd23c90.png)
Double ''but'' is intentional in this fun fact?

**Comment by zwartkop2** [comment]
![screenshot0038](https://user-images.githubusercontent.com/79435778/130307178-3810f4d1-5130-456a-937d-939663093e6f.png)
Probably only need the second fade.

**Comment by Fradxyz** [comment]
![image](https://user-images.githubusercontent.com/83095832/130335071-e7e8c847-f82c-4432-ad51-c789ed4acc62.png)
Just a small typo, I think the topic is about camping

**Comment by multimokia** [comment]
If you mean forgo, that's not a typo, it means something along the lines of `to do without`, in this case

**Comment by Fradxyz** [comment]
oh ok. I thought it was a typo : )
________________________________

**Comment by d3adpan** [comment]
Small typo, dandere referenced twice.

![screenshot0718](https://user-images.githubusercontent.com/61102477/131252493-fd3a0d72-c819-4ae5-9c7a-8f83377abb6c.png)

**Comment by MrVavlo** [comment]
That topic is part of submod, not MAS iirc

**Comment by zwartkop2** [comment]
> Small typo, dandere referenced twice.
> 
> ![screenshot0718](https://user-images.githubusercontent.com/61102477/131252493-fd3a0d72-c819-4ae5-9c7a-8f83377abb6c.png)

This is part of a submod, iirc. You’ll have to get in contact with whoever made the submod.

**Comment by d3adpan** [comment]
Thanks, any idea which it might be?  I have several installed and I can't read the .rpyc to figure out which it belongs to or just fix it myself

**Comment by d3adpan** [comment]
Thanks, I've got it sorted now

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/131351887-87f11be5-4e80-4d44-bb01-79e0cd258578.png)
Does ''some of them'' need a verb after it?

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/132423433-f7b24ce5-4fdb-43aa-8182-4fda7d0b3912.png)
A line is duplicated.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
