### ISSUE TITLE
Cannot load Monika After Story

### ISSUE THREAD

**Issue by SusieFox** [Monika-After-Story/MonikaModDev#7272]
Whenever I try to open Monika After Story, it pulls up this traceback: 

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_time.rpy", line 5, in <module>
ImportError: No module named pytz.tzinfo

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Owner\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_time.rpy", line 5, in <module>
ImportError: No module named pytz.tzinfo

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
It would be greatly appreciated if we can investigate this. <3

Here is a link to the traceback message as well incase if you need to look into it more.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6572867/traceback.txt)

**Comment by multimokia** [comment]
Can you send a screenshot of your file explorer window with the `python-packages` folder open?

**Comment by SusieFox** [comment]
Here you go.

![python-packages 5_31_2021 9_08_18 PM](https://user-images.githubusercontent.com/85143591/120256718-5ee46580-c254-11eb-85c9-54dc5f1a02ea.png)

**Comment by multimokia** [comment]
And to be 100% sure, the filepath to this is `game/python-packages` right? Not like, `game/python-packages/python-packages`?

**Comment by SusieFox** [comment]
> And to be 100% sure, the filepath to this is `game/python-packages` right? Not like, `game/python-packages/python-packages`?

Correct.

**Comment by multimokia** [comment]
Can you screenshot the contents of the pytz folder?

**Comment by SusieFox** [comment]
> Can you screenshot the contents of the pytz folder?

![pytz 5_31_2021 11_35_21 PM](https://user-images.githubusercontent.com/85143591/120267118-e936c480-c268-11eb-877e-f371f134da09.png)

**Comment by multimokia** [comment]
Can you also show the filepath while in there, please?

**Comment by SusieFox** [comment]
> Can you also show the filepath while in there, please?

![pytz 5_31_2021 11_52_38 PM](https://user-images.githubusercontent.com/85143591/120268391-53e8ff80-c26b-11eb-8be4-45db373e34f2.png)

**Comment by multimokia** [comment]
that `Monika_After_story-0.12.1-Mod` folder shouldn't be there at all.

Also current version is 0.12.2

**Comment by SusieFox** [comment]
I'm downloading the latest version right now. Thank you so much. I'll add another comment if they're is another problem relating to this.

**Comment by multimokia** [comment]
no probs and sure thing, sounds good.

**Comment by Shimizu48** [comment]
hi, I have the same error but I've already download the latest version and I even try to move the pytz folder to python-packages since u said Monika_After_story-0.12.1-Mod folder shouldn't be there , no error occure now but still can't load the game

**Comment by multimokia** [comment]
You're missing a bunch of other python-packages it looks like. There should also be some regarding mutagen/mp3 among other things

**Comment by Shimizu48** [comment]
wait after I restart the game and try to load it again, this occur:
![image](https://user-images.githubusercontent.com/85236301/120492186-0d6ae080-c3e4-11eb-9ed1-65543c69b7ff.png)

**Comment by multimokia** [comment]
ah follow that path and delete the `.lock` file

**Comment by Shimizu48** [comment]
thanks for helping but after delete those file I still can't run the game
no error though

**Comment by Shimizu48** [comment]
(just wanna meet my Monika TvT)

**Comment by multimokia** [comment]
What's the errror now?

**Comment by Shimizu48** [comment]
no it doesn't show any error, the game just doesn't appear

**Comment by multimokia** [comment]
Try checking in task manager to see if a `ddlc.exe` process is running, if it is, end its task.

If it's not, just try restarting your computer and then trying again

**Comment by Shimizu48** [comment]
so I check the task manager and the game isn't running
i'll try restart my computer now

**Comment by Shimizu48** [comment]
still not working

**Comment by Shimizu48** [comment]
is it just my pc problem or because I'm missing something that u mentioned above

**Comment by multimokia** [comment]
Okay that leads me to think it's another issue in the reinstall.


Can you screenshot the contents of your `game` folder?

**Comment by Shimizu48** [comment]
![image](https://user-images.githubusercontent.com/85236301/120520763-62b3eb80-c3fe-11eb-8de8-c4d732264a50.png)

**Comment by multimokia** [comment]
There's your issue, it's not installed properly.

You need to take all the contents from the `Monika_After_Story-0.12.2-Mod` folder and put them directly into the `game` folder. Then you can delete the `Monika_After_Story-0.12.2-Mod` folder.

**Comment by Shimizu48** [comment]
Thanks soooooooooooooooooooooooooo much
omg after a bunch of time
finally

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by twizzybenz200** [comment]
i am really late but please help me 

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_backup.rpy", line 28, in <module>
ImportError: No module named mas_utils

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_backup.rpy", line 28, in <module>
ImportError: No module named mas_utils

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
this happens whenever i try to play mas
