### ISSUE TITLE
Possible mistake

### ISSUE THREAD

**Issue by satoshi-kun** [Monika-After-Story/MonikaModDev#7274]
I saw on the newest v0.12.2 notes that "Changed the names of the transsexual ribbon to transgender"
It seems that this change wasn't implemented, or I am looking at this the wrong way. If so I'm sorry.
![ribbon](https://user-images.githubusercontent.com/54683676/120318017-3782ac80-c2d7-11eb-9688-ff4129af9c1a.png)

**Comment by multimokia** [comment]
Have you updated the spritepack? If not the change won't be reflected

**Comment by ThePotatoGuy** [comment]
Appears I missed this in the patch notes

**Comment by satoshi-kun** [comment]
Understood. 
Since it wasn't mentioned I thought I should say something.

**Comment by satoshi-kun** [comment]
I've copied the new assets from the spritepack but they seemed exactly the same as the ones I had. The names at least
Upon laucnh no changes occured.

**Comment by multimokia** [comment]
But did you update the *json*

**Comment by multimokia** [comment]
The json itself is responsible for holding all the data relating to the pack, including the names. The sprites alone will not change that.

**Comment by satoshi-kun** [comment]
Yes. Including the thumb

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/120358347-63506300-c2d4-11eb-8814-159877fa140a.png)

Odd, the json itself has the updates in it. Unsure why it's not changing on your end

**Comment by multimokia** [comment]
Nvm, our bad. We forgot to pack that one specifically. We'll have an update on this later

**Comment by satoshi-kun** [comment]
I just did copy again the json after deleting the previous one just to check. xD

**Comment by ThePotatoGuy** [comment]
The latest spritepacks zip should be updated now.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
