### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by AlyCat730** [Monika-After-Story/MonikaModDev#7276]
I have MonikaModDev, but when it's in my game folder, DDLC just won't open at all. Not even a traceback error thing. My computer loads and nothing happens. But when I take out MonikaModDev into my Downloads folder, the game opens and works just fine. I really want to use this submod but I don't know how to get it to work.

**Comment by multimokia** [comment]
Can you screenshot the `game` folder, please?

**Comment by AlyCat730** [comment]
![image](https://user-images.githubusercontent.com/83853204/120359019-74917380-c2c4-11eb-85f8-f113480e36d9.png)
![image](https://user-images.githubusercontent.com/83853204/120359081-81ae6280-c2c4-11eb-8614-549410e9d707.png)
![image](https://user-images.githubusercontent.com/83853204/120359110-8b37ca80-c2c4-11eb-9701-9ed24177ce4b.png)
![image](https://user-images.githubusercontent.com/83853204/120359211-a571a880-c2c4-11eb-9028-2b64378c814e.png)
here ya go

**Comment by multimokia** [comment]
Don't install the source code
![image](https://user-images.githubusercontent.com/22531674/120359275-7f083900-c2d5-11eb-9570-d12a4c04be2a.png)

this makes it so you have *two* `game` folders and duplicate files, which will cause numerous issues.

**Comment by multimokia** [comment]
FYI that `MonikaModDev` is not a submod, it is the source code for the mod (the same stuff that gets compiled into all the `.rpyc` files you see there) so you don't need --and shouldn't have it there.

**Comment by AlyCat730** [comment]
ohh ok! thank you

**Comment by multimokia** [comment]
No problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
