### ISSUE TITLE
Question For new writing tips

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#7279]
Are there going to be more writing tips for monika to say i really love the writing tips 

because it has been a while

i miss monika telling the writing tips 

Okay everyone here's monika's writing tip of the day my favourite part

**Comment by Retrolovania** [comment]
There'll most likely be more added with future updates.

**Comment by multimokia** [comment]
If anyone out there wants to write and submit them, they're more than free too, we'll review em and merge them in. 

Things typically get done a lot faster if there's people out there to help out in the writing area since we tend to bounce around with coding other parts.
