### ISSUE TITLE
Suggestion for Consumables

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#7281]
Not a great idea but, for consumables the file format for replenishing items be different. So items like coffee and snacks would not be in a .gift file but in something like .item file? It just seems like a small overreaction a bit when I get her coffee and she is super ecstatic. Then again it is very appreciating of anything she gets.

To condense this in a single sentence: Is it a good idea to change or add a new file type for consumables?

**Comment by Wingdinggaster656** [comment]
I think...... It's not a bad idea, but it's not necessary.
I'm not Devs, but I think you could write your own code and send a PR if you like, and I think the Dev team would be fine with that.

**Comment by ThePotatoGuy** [comment]
currently we only want to use `.gift` to simplify the file searching alg. Also means less confusion if someone tries to give a gift but uses the wrong extension.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
