### ISSUE TITLE
3D camera. 

### ISSUE THREAD

**Issue by kirillPro2020** [Monika-After-Story/MonikaModDev#7282]
Recently, renpy added a 3D camera. Will it be used here?

**Comment by multimokia** [comment]
MAS still runs the original version of Ren'Py DDLC uses, i.e. 6.99.12, it doesn't have access to the 3D camera. Additionally we don't exactly have 3D sprites or a model to render the room + Monika with, so it's unlikely that transition would be made to use it.

**Comment by multimokia** [comment]
That said, looking up its documentation, it almost seems like a different implementation of zorder instead of being directly for rendering 3D items. It's possible we may use this once we transition to newer versions of renpy, to replace zorder

**Comment by kirillPro2020** [comment]
What is the main problem when switching to the new renpy?

**Comment by kirillPro2020** [comment]
I saw that the transition is dated for August 2024.

**Comment by multimokia** [comment]
The lack of an installer, making the jump difficult for users.

Additionally we're mainly waiting for renpy 8 to make the jump. We've backported renpy 7+ features back to our renpy in the meantime. This is why we've been working on maintaining a branch which is suited for the Py3 transition, considering Py2 is more than dead now.

Once Renpy 8 drops we'll be intending to migrate over. Hopefully that comes out much sooner than later.

**Comment by kirillPro2020** [comment]
That is, is it something in the middle, in the middle?

**Comment by multimokia** [comment]
Not sure what you mean

**Comment by kirillPro2020** [comment]
Transition version. I mean her.

**Comment by ThePotatoGuy** [comment]
Based on a quick search of "renpy 3D camera", it looks like that is a way to have fancier zooms and pans as if a camera was being moved. This can probably be done in regular renpy with custom disps and fancy ATL, but regardless theres little reason to include this. MAS is not like a regular vn.
