### ISSUE TITLE
[Suggestion] "Read me a poem" as a category like "can you tell me a story?"

### ISSUE THREAD

**Issue by puppetmotel** [Monika-After-Story/MonikaModDev#7292]
I think it would be nice to add more emphasis on Monika's love of poetry, as someone who loves poetry myself. I was excited when _There Will Come Soft Rains_ came up and she recited it to me, but it's a little annoying that it gets tucked into Repeat Category > Literature.

I had an idea to try my hand at writing dialogue where she recites several other poems along the same lines and discusses them after, but it might make more sense to organize them in the same manner as "can you tell me a story?", where you have a pick of several and new ones come up over time. You could even organize them by happy/sad/etc.

Just a concept to add a little more poetry love to the game! I'm still familiarizing myself with Python, so I thought it'd be good to suggest first.

**Comment by ThePotatoGuy** [comment]
I like this. Could even play music alongside to set the mood. 

[closing until we look into it]
