### ISSUE TITLE
New Goodbye Option

### ISSUE THREAD

**Issue by KermitThePotatoE** [Monika-After-Story/MonikaModDev#7296]
You can add "I have to go to toilet.." option to "Goodbye" option. It could be good.

**Comment by Wingdinggaster656** [comment]
Couldn't agree more, though I think that should be a Be Right Back, not a Goodbye.

**Comment by KermitThePotatoE** [comment]
> 
> 
> Couldn't agree more, though I think that should be a Be Right Back, not a Goodbye.

Hmm, you're right. But its a thing that must be added.

**Comment by Wingdinggaster656** [comment]
I've started a new pull request, see #7297.
Hope that's what you want.

**Comment by KermitThePotatoE** [comment]
oh thats good, thanks

**Comment by CloakedGhost** [comment]
Wait but why do we need that? Couldn't you just use the "I'll be right back" option? I don't see why it has to be that specific.

**Comment by 20RaVen23** [comment]
I honestly don't see it necessary myself either. I think the Be right back option covers that and a lot of other things that simply doesn't need a whole option.

**Comment by Wingdinggaster656** [comment]
I agree that we need no such many dialogue, but I think it's necessary to at least deserves a option in "I'll be right back" options(I mean in the "Doing something specific" question menu).
If you really think anything can be explained with a simple "I'll be right back" -> "Nothing", then we don't need I'm going to read, I'm going to code, I'm going to take a nap.
What, "couldn't you just use the 'I'll be right back' option? I don't see why it has to be that specific", and "I honestly don't see it necessary myself."

**Comment by 20RaVen23** [comment]
Because at this rate it'll happen the same as it did with songs and languages. A lot of either too specific stuff or just not needed.
With songs it's at least understandable, since at the end of the day, it's music.
_What's next? "I'm going to jump 7 times in one feet"?_

**Comment by Rai99** [comment]
#2243, #3270

**Comment by CloakedGhost** [comment]
> I agree that we need no such many dialogue, but I think it's necessary to at least deserves a option in "I'll be right back" options(I mean in the "Doing something specific" question menu).
> If you really think anything can be explained with a simple "I'll be right back" -> "Nothing", then we don't need I'm going to read, I'm going to code, I'm going to take a nap.
> What, "couldn't you just use the 'I'll be right back' option? I don't see why it has to be that specific", and "I honestly don't see it necessary myself."

It makes sense to have a reaction to those brbs because it actually interests Monika or she might be really happy when you work out/read/write etc. I just don't see why Monika would want to know that you are going to the toilet. I doubt that's something she wants to know.

**Comment by Wingdinggaster656** [comment]
> > I agree that we need no such many dialogue, but I think it's necessary to at least deserves a option in "I'll be right back" options(I mean in the "Doing something specific" question menu).
> > If you really think anything can be explained with a simple "I'll be right back" -> "Nothing", then we don't need I'm going to read, I'm going to code, I'm going to take a nap.
> > What, "couldn't you just use the 'I'll be right back' option? I don't see why it has to be that specific", and "I honestly don't see it necessary myself."
> 
> It makes sense to have a reaction to those brbs because it actually interests Monika or she might be really happy when you work out/read/write etc. I just don't see why Monika would want to know that you are going to the toilet. I doubt that's something she wants to know.

I agree that she would not want to know that you are going to the toilet things, but it's "you want to say you are going to the toilet", it has nothing to do with she want or not, it's the playing talking.

**Comment by CloakedGhost** [comment]
If you know that she doesn't wanna know, then why do you want to tell her that?

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
