### ISSUE TITLE
[Suggestion] Monika asking the player what language they speak

### ISSUE THREAD

**Issue by JessieChaaan** [Monika-After-Story/MonikaModDev#7299]
So,currently I speak fluently 4 languages (Italian,Albanian,French and English and I'm learning Japanese) and I think it would be cool if Monika asked the player what language they speak,but that only if they said yas in the topic about speaking japanese. Here is a little example
M : Say player,you told me you speak another language other than english,and I wanted to ask you what language do you speak ?
And there would be a choice between the languages that monika speaks.
you could say that you speak more that 2 languages,and for example there could be a choice like :
M : Really? That's neat! How many languages do you speak ?
Choice :
three
four
more than four
and then Monika would let you select the number of languages that you said.
For eample, I would select four at the first question,at the second I waould say Italian and others (You could add some more basic languages like french,spanish and german) but this is up to you!
Welp,thanks for listening LMFAO

**Comment by Rai99** [comment]
Native languages: #2505, #3804, #6434, #6549, #6606

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
