### ISSUE TITLE
Appearance Options Unavailable/Disappearing

### ISSUE THREAD

**Issue by Liyori** [Monika-After-Story/MonikaModDev#7301]
I messed with the Monika after story game files a while ago and completely uninstalled the app as I'd done something wrong with Monika's folder and got frustrated, but just yesterday I reinstalled it for fun under the newest update. Everything's worked smoothly, and I was surprised when the backup file I made long ago came into play and she remembered the data. However, when in the appearance category, I only have the option to change her hairstyle. I've gifted her various clothing and I don't have the option for her to put them on or anything, or even change her ribbon. Sometimes the option to change her ribbon pops up, bust most of the time it doesn't. I don't know if I've completely screwed myself over or if the data or anything's acting up, but any help is appreciated :)

![Screenshot 2021-06-06 173948](https://user-images.githubusercontent.com/85461113/120941009-64c3c600-c6ee-11eb-93af-d5bb53489ed5.png)

**Comment by lunulae** [comment]
Appearance changes largely are based on affection. Based on her current expression, since you haven't played for a while your affection is a bit low. You can get them back when it raises, but it will probably take some days of playing depending on where you're at.

**Comment by Liyori** [comment]
> Appearance changes largely are based on affection. Based on her current expression, since you haven't played for a while your affection is a bit low. You can get them back when it raises, but it will probably take some days of playing depending on where you're at.
Thanks very much, I'll work on bringing up her affection!

**Comment by ThePotatoGuy** [comment]
Certain clothing options may limit available hairstyles, and certain hairstyles may limit available accessories. Most limitations have to be requested by the spritepack, so if these are community spritepacks, then they might be overzealously limiting options. You'd have to check with the creator.
