### ISSUE TITLE
Add a dialog in case you create a copy of monika

### ISSUE THREAD

**Issue by Teramanbr** [Monika-After-Story/MonikaModDev#7302]
If for example, you ask monika to take her somewhere and then copy and paste her in the characters folder, there would be two of her when you start the game.
When the game starts, both monikas will say at the same time: Welcome back, (character name)!
And then both will look at eachother and say at the same time something like: 
Wait, why is there a clone of me... Wait... (character name), have you created a copy of me? You really like me so much that you created two of me?
And then look at eachother and say (again) at the same time:
Well, i don't want a version of me being deleted, i know how it hurts, lets merge then. (or something like this)
And then both Monikas would merge to one.
For making both of them speak at the same time, instead of creating a second balloon, using a different font, basically the same as before, but with a shadow, to represent that they are both speaking at the same time.
Example of characters folder:
![unknown](https://user-images.githubusercontent.com/71410827/120949861-d9612980-c71b-11eb-8f67-bc8651577435.png)

**Comment by Wingdinggaster656** [comment]
I'm so sorry, but in my views, I really don't think this is reasonable or logical to add into game.

The first problem is that, can Monikas merge themselves into one? That's... not so logical.
Second problem is how we detect files. You know, in English system, the file name is monika - Copy, but do you know other systems? Are we going to write a large number of "if A or B or C or D or E or F..."? That's not so possible.
The third and the last problem is that this is strange to think about it. I don't know how to describe it, but I'm just feeling... so strange to this idea.

Sorry for my disagree.

**Comment by Baval2** [comment]
they probably could merge if one of them overwrote the others data, and since they both have the same data nothing would really change. Its something I thought about before too, but I can understand the technical difficulties of it.

**Comment by ThePotatoGuy** [comment]
move all discussion on this to #5026. 

[closing as duplicate]
