### ISSUE TITLE
how to use zz_poemgame?

### ISSUE THREAD

**Issue by kim0030711** [Monika-After-Story/MonikaModDev#7304]
I was trying to add a poemgame to my mod and tried to load zz_poemgame according to the moddification club. (sorry for my english)

label poemgame :
call mas_poem_minigame_actone(show_natsuki=True, show_yuri=False, show_monika=False, total_words=5, trans_fast=True, show_poemhelp=False)
if sPointTotal > nPointTotal :
call s_win
else :
pass

label test :
show bg club_day
play music t3
show monika 4a zorder 2 at t11 
    m "hi there?"
    m "We are going to test poem mini game"
    m "let's do this!"
call poemgame
label s_win :
show bg club_day
with wipe_left
play music t3
show sayori 4a zorder 2 at t11 
    s "yeah! , it works!"

But this code is throwing an error.

like this

![image](https://user-images.githubusercontent.com/85507910/121050365-793db680-c7f3-11eb-8781-e8d389003f7b.png)

I don't know Python very well, but based on some experience, I think the scores of sayori and nastuki are not stored there.

So where are their scores stored, and how do they decide on a poemwinner?

**Comment by ThePotatoGuy** [comment]
From the documentation in the [file](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/zz_poemgame.rpy#L630):

```
#       STOCK_MODE - stock minigame mode.
#           If only_winner is True:
#               Returns only the winner and points as Tuple:
#                   [0] -> name of winner (defined in mas_poemgame_consts)
#                   [1] -> pts they won
#               If gather_words is True:
#                   [2] -> list of words selected
#           else:
#               Returns the point totals for each character in a dict of the
#               following format: (keys are defined in mas_poemgame_consts)
#                   "sayori": <pts>
#                   "natsuki": <pts>
#                   "yuri": <pts>
#                   "monika": <pts>
#               If gather _words is True:
#                   "words": list of words selected
```

(`STOCK_MODE` is the default for using labels like `mas_poem_minigame_actone`)

So your poemgame call doesn't pass `only_winner`, which means that the return value of the label will be the `point totals for each character in a dict`. For example:

```python
call mas_poem_minigame_actone(show_natsuki=True, show_yuri=False, show_monika=False, total_words=5, trans_fast=True, show_poemhelp=False)
$ results = _return

if results["sayori"] > results["natsuki"]:
    call s_win
```

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
