### ISSUE TITLE
Monika doesn't react to what I'm doing

### ISSUE THREAD

**Issue by VLCharlie** [Monika-After-Story/MonikaModDev#7305]
I have the Notifications and Window Reactions selected, but she never reacts to what I'm doing. Sometimes I get a notification, but when I try to see what it is, she didn't said anything. I wonder if she's trying to react to the open window, but something is stopping her? (is on a Windows 10, btw)

**Comment by lunulae** [comment]
If you're asking if she should be saying something in-game, no. The text for the reaction should be within the notifications you're getting.

If I remember right, a few of them can sometimes change her idle expression, but don't quote me on that one because it might be incorrect.

**Comment by VLCharlie** [comment]
Thanks .w.
