### ISSUE TITLE
A little help needed.

### ISSUE THREAD

**Issue by Zenha156** [Monika-After-Story/MonikaModDev#7308]
Hi! Sorry if I bothered you but I kinda have an issue. You see, I was trying to give Monika some gifts (and yes, I have received the hint document) and even restarted the game for her to notice but when I did, she doesn't seemed to have noticed the gifts. I have even been waiting for a little while but she still hasn't noticed them. And, the gift(s) I was trying to give even had the ".gift" extension but she still didn't seemed to have recognized them. This might have been in the FAQ but this time, it had the ".gift" extension in the gift file name. If this can be solved, thank you so much and for reading this! Have a lovely day!

**Comment by Wingdinggaster656** [comment]
A screenshot of your gift file, please?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
