### ISSUE TITLE
Wrong expression?

### ISSUE THREAD

**Issue by JUST-Nic3-2043** [Monika-After-Story/MonikaModDev#7311]
In script-farewells.rpy, line 441, when 'player' has to go to class under 20 minutes after opening the game Monika will say "Aw, going already?" but her expression looks rather happy than sad. Don't know if it's done on purpose or is it a mistake but I think that a more "normal" expression would be sad, rather than happy. If it is a mistake I recommend changing expression code from 1eub to 1ekc.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
