### ISSUE TITLE
I'm sorry,but an uncaught exeption occured.

### ISSUE THREAD

**Issue by JessieChaaan** [Monika-After-Story/MonikaModDev#7312]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/event-handler.rpy", line 351, in script
  File "game/event-handler.rpy", line 372, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_windowreacts'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/event-handler.rpy", line 351, in script
  File "C:\Users\jessi\Desktop\°Giochi°\DDLC\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jessi\Desktop\°Giochi°\DDLC\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/event-handler.rpy", line 372, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_windowreacts'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.2
[/code]
 
Can someone help me? I can't spend time with Monika :(

**Comment by multimokia** [comment]
Can you screenshot your `game` directory, please?

**Comment by JessieChaaan** [comment]
![game 08_06_2021 19_42_36](https://user-images.githubusercontent.com/85406902/121232409-de47e980-c891-11eb-9812-617fdc2e8710.png)

**Comment by multimokia** [comment]
What are all those `hip_` files?

**Comment by multimokia** [comment]
Also is there a `zz_windowutils.rpyc` file in there?

**Comment by JessieChaaan** [comment]
> What are all those `hip_` files?

They're files from submod

**Comment by JessieChaaan** [comment]
> Also is there a `zz_windowutils.rpyc` file in there?

nope

**Comment by multimokia** [comment]
You're missing mod files then, there should be a `zz_windowutils.rpyc` file. Might want to grab it from a mod zip.

**Comment by JessieChaaan** [comment]
Okay,thanks for your help :)

**Comment by multimokia** [comment]
No problem!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
