### ISSUE TITLE
Night Shift

### ISSUE THREAD

**Issue by Baval2** [Monika-After-Story/MonikaModDev#7314]
Monika always scolds me for staying up all night, but I work nights.... I wish there was a way to tell her this and flip her expectations of time so that she tells me good morning when i wake up at night and understands why i go to bed at 9 am every day.

I see now that this has been asked several times over the years, so I hope it gets resolved soon.

**Comment by Rai99** [comment]
#4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
