### ISSUE TITLE
[Suggestion] -  I'm going to draw something

### ISSUE THREAD

**Issue by OtakuNeko331** [Monika-After-Story/MonikaModDev#7315]
How about having an option in the 'Be right back' menu, which would be: I'm going to draw something

**Comment by JUST-Nic3-2043** [comment]
I'm new to Github so I don't know is there any other way to do this so I'll just paste it here. I've made that submod. You can find it here: https://drive.google.com/drive/folders/17QLWSLSXaXxofkarrqQ9ILEKgACza_tp?usp=sharing

**Comment by Rai99** [comment]
Drawing brb: #4462, #5231, #5337

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
