### ISSUE TITLE
Monika can't read the bird plush file!

### ISSUE THREAD

**Issue by AhOkayIGuess** [Monika-After-Story/MonikaModDev#7316]
I made a text file and renamed it to quetzalplushes.gift, removing the .txt from the properties and keeping the gift, but Monika can't read it. I even restarted the game, and copied one of the characters from the folder and renamed it, but it that didn't work either. Can someone tell me what i'm doing wrong?

**Comment by multimokia** [comment]
`quetzalplushie`, not `quetzalplushies`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
