### ISSUE TITLE
[Suggestion] Remove "I finished my coffee" things in BRB status?

### ISSUE THREAD

**Issue by Wingdinggaster656** [Monika-After-Story/MonikaModDev#7317]
You know, when Monika is having consumables to server, she will randomly put them on table to pick them.
And once she finished, she will say: "I finished my coffee. I'm going to put this cup away" things.

This will also happen when player is in BRB status. That's my issue. When you are in BRB status, Monika will probably think that you are "not in front of computer now", so you are not looking at her at all.
And since you are not looking at her, there is no need for her to say "I'm going to...". I think a better way is she simply fade in background, and then backed, without saying anything.

**Comment by Booplicate** [comment]
We can't be 100% sure the player isn't looking at the screen at the moment. Also, the dialogue in that case will be slightly different and will autoprogress, so she does acknowledge you may be away.

**Comment by Wingdinggaster656** [comment]
> We can't be 100% sure the player isn't looking at the screen at the moment. Also, the dialogue in that case will be slightly different and will autoprogress, so she does acknowledge you may be away.

Oh, I forgot that this dialogue will autoprogress, this is a good solution. Thanks for your reply, I don't think this is an issue anymore.
[Closing as I think this is done.]
