### ISSUE TITLE
[Suggestion] Have a dialogue option that says "please don't go easy on me" on games

### ISSUE THREAD

**Issue by Erenussocrates** [Monika-After-Story/MonikaModDev#7318]
It feels like it's more frustrating Monika going easy on you on games like chess and pong. Would it be fine to add a "please don't go easy on me" or "use your full power" on dialogue options, and a dialogue option to revert it back if desired?

**Comment by Wingdinggaster656** [comment]
Personally agree.
Not a bad idea.
We can even try to add one more option "Would you go a little easier on me?"

**Comment by lunulae** [comment]
I'd be down for this, though I'm not sure how we'd want to prompt it. We probably wouldn't want it to pop between every round of Pong for example, but it would be natural to be able to interject at any point like she can. Maybe a button toggle like what we have for bookmarking/blacklisting topics, but I don't know if that's more convoluted than it's worth.

I've actually thought of adjusting the pre-game menu for Hangman to be worded a little more like this as well, to be less robotic than picking a difficulty level.

**Comment by Erenussocrates** [comment]
> I'd be down for this, though I'm not sure how we'd want to prompt it. We probably wouldn't want it to pop between every round of Pong for example, but it would be natural to be able to interject at any point like she can. 

I think it could be included in the "Games" section or could be added as a dialogue option whenever you've chosen to play a game with monika, just like the setting choices that come up when you choose to play chess with her.

**Comment by Rai99** [comment]
#5727, #7124

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
