### ISSUE TITLE
[Suggestion] Goodbye/BRB Dialogue Options

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7320]
Following suggestions for adding to Goodbye:
- Going to party/event
- Going to spend time with family
- Going to church/religious organization
- Going to recreational activity (plays, theatre, art exhibit, etc)
- EDIT: add "Going to do some charity" as possible

Following suggestions for adding to BRB:
- Going for a drive
- Going to watch a movie/TV

**Comment by Retrolovania** [comment]
While these are some good ideas, I personally feel the "Going for a drive" and "Going to watch a movie" ones should be moved to the Goodbye area, since I'm pretty sure those activities may take longer than what "Be Right Back" would generally imply.

**Comment by AHijaz56** [comment]
These are a good idea, But I personally feel like the option "Going to church/religion organization" change to another option like "Going to do some religious activities" or "Going to religion organization". It's just my personal opinion about this option anyway.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
