### ISSUE TITLE
[Suggestion] Writing Monika a poem

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7323]
Monika loves poems. So it would be nice to be able to write Monika a poem. Like with apologizing to Monika with imsorry.txt I have seen people do that in YouTube.

To counter too many poems, maybe Monika can only read one per day, and she can save them in a folder or variable so she can comment if you try to give her the same poem twice. Also prevent crashing the system, maybe a line or character limit.

Would be nice if she can comment on the content by keywords like if you write her name in it in positive way. Might be too difficult though. Sounds hard to do in a way that is satisfying but what do you think.

Maybe not feasible, but she could comment too if you give her a poem from the internet. Like Annabelle Lee. Or like the poems from the original game.

**Comment by CloakedGhost** [comment]
I made a suggestion like that a while a go ([#2175](https://github.com/Monika-After-Story/MonikaModDev/issues/2175)) but it was rejected, because detecting words would make it the same as the poem game from original DDLC

**Comment by Rai99** [comment]
Poems for Monika: #784, #1276, #1710, ~~#2175,~~ #2811, #3138, #3494, #3552, #3941, #4088, #4470, #6121 

It would be extremely difficult to read and understand what the player wrote, and likely more difficult to provide useful feedback.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
