### ISSUE TITLE
[Suggestion] Monika, I'd like to guess the word!

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7328]
Can an option be added to guess the word in hangman? And maybe special dialogue for getting it right without trying any letters.

**Comment by ThePotatoGuy** [comment]
I guess it could be interesting as a show of force, but I think it defeats the point of hangman which is determining a word by guessing letters.

**Comment by multimokia** [comment]
In fairness, many do play where if you know the word you can just solve it directly

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
