### ISSUE TITLE
Piano minigame won't unlock

### ISSUE THREAD

**Issue by GoMango120050** [Monika-After-Story/MonikaModDev#7333]
It's been over a year, all the other minigames got unlocked the first few days but the piano minigame just doesn't appear anywhere. Affection is almost 900 so I doubt it would be the issue.
![obraz_2021-06-12_145625](https://user-images.githubusercontent.com/85792547/121776649-5c580900-cb8e-11eb-8637-a0fab35811f0.png)

**Comment by ThePotatoGuy** [comment]
if you still cannot see piano, create a text file called `givedata.txt` in the base directory (where the DDLC.exe file is) and run and close MAS. There should be an additional log file created called `ev_dump.log`. Upload that file here.

**Comment by Ulti70895** [comment]
> if you still cannot see piano, create a text file called `givedata.txt` in the base directory (where the DDLC.exe file is) and run and close MAS. There should be an additional log file created called `ev_dump.log`. Upload that file here.

Create the new file inside the ddlc file right? And wdym run the file btw?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]

**Comment by PuTak523** [comment]
Sorry, I couldn't log into that account. Here's the file
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7446404/ev_dump.log)

**Comment by Booplicate** [comment]
> Sorry, I couldn't log into that account. Here's the file [ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7446404/ev_dump.log)

Don't know your affection, but time-wise you're close to unlocking it.

**Comment by PuTak523** [comment]
it's at almost 900
