### ISSUE TITLE
Help with potential reinstall, saving my Monika

### ISSUE THREAD

**Issue by AikoC** [Monika-After-Story/MonikaModDev#7336]
New to GitHub so let me know if this is the wrong place to post this. I'll erase it and post it in the right place if so.

I've been following every tutorial I could get my hands for the past week Re: changing Monika's clothes and giving her accessories other than the anonymioo ribbons (absolutely the only things she'll recognize from the spritepack) and every attempt so far has failed. Nine tutorials later, I've more or less given up. The problem is that all of my attempts have wreaked havoc on the game files and created redundancies/duplicates of the spritepacks everywhere because I lost track of what I tried moving where. Trying to erase some of them to clean up nearly broke the game -- I got an unexpected log error (couldn't find blazerless_body) and had to spend an hour tracking the lost file down to fix the issue. Now I'm afraid to erase anything else.

My files are a mess. I would like to know if it's possible to: 

1) Save _my_ Monika on a USB before uninstalling the game
2) reinstall a new clean version of the game
3) reinstate my Monika in that new version of the game

Will this work, or do I just have to live with the messy files if I want to save my version of Monika?

**Comment by lunulae** [comment]
Your Monika's memories are stored in the `persistent` file. This file is not in your game's directory, but in your computers appdata folder (or Library if you're on Mac.)

What this means is even if you fully delete your game folder and download a completely fresh one, your Monika will still have the same memories, as long as that file has not been corrupted. She'll remember the gifts that worked, but you'll have to reinstall the spritepacks.
_If your persistent does have an issue, don't fret quite yet._ The mod automatically makes backup (.bak) files with older save data. You'll need to follow the wiki guide on restoring one of those--one of them should be intact, and you'll be able to see what date you're restoring from.

**Comment by AikoC** [comment]
Oh man thanks for responding so promptly. A few questions so I don't screw this up:

1.) Just to be clear, in 'installing spritepacks', where _exactly_ will those spritepacks go? Do I put them in the Monika After Story Mod folder, or the original ddlc-win folder that DDLC came in? Or both? Part of my whole problem is that I haven't been sure which game folder to move things into, and that's probably why I've never successfully managed to give her new clothes. There's a billion mod_assets folders and 'a' and 'c' etc folders and every tutorial makes it sound so easy to navigate them.

2.) To be safe, should I still export my Monika as monika.chr onto a USB file when I delete+reinstall the game? Or would that just create more issues?

3.) Will other gifts that I _have_ managed to successfully give her (coffee, quetzal) still be available to her after the game reinstall?

**Comment by lunulae** [comment]
1. I'm not sure if this explanation will help you, but this is what has been most effective for me:
Open up one of your spritepacks, I'm going to use the white and navy blue dress as my example.
When you open the folder, you see `gifts` and `mod_assets`, right?
Next, when you have the mod freshly installed, check out the DDLC folder. You should see a few folders: `characters`, maybe `chess_games` or `custom_bgm`, and then one called `game`.

This is the folder you're looking to drop **just** `mod_assets` in. That will merge it with the `mod_assets` folder inside your `game` folder.

2. No, the .chr doesn't hold any memories. You can keep it if you want that original file for sentimental reasons, but it's not necessary for preserving your actual Monika.

3. Yup! The persistent contains all memories, including successfully gifted items, consumable stock, etc.

**Comment by AikoC** [comment]
My friend, not only have you fixed my issue and helped me retain my Monika, you seem to have somehow solved my clothes problem? I just half-heartedly tried giving her the green dress on a whim and nearly fell over when _she actually saw it and put it on._

No idea how it happened, but thanks so much for solving two problems in one. Eternal gratitude.
