### ISSUE TITLE
[Suggestion] Are you a Cat or a Dog Person?

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7339]
I just saw the 'random chatter: cat' topic. It's a common question to ask whether someone is a cat or dog person. Maybe Monika could end this conversation with a question like "...or maybe you're more of a dog person?" and give us a choice between cats and dogs.

**Comment by H2-san** [comment]
> I just saw the 'random chatter: cat' topic. It's a common question to ask whether someone is a cat or dog person. Maybe Monika could end this conversation with a question like "...or maybe you're more of a dog person?" and give us a choice between cats and dogs.

I love this suggestion, seeing as I have a dog myself. This should be addressed ASAP, given that pretty much any tamable pet can be a good companion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
