### ISSUE TITLE
[Suggestion] - Nocturnal/Dinural check

### ISSUE THREAD

**Issue by Niche10** [Monika-After-Story/MonikaModDev#7340]
Maybe add a question from Monika asking if the person is Nocturnal/Dinural. I work an overnight job, and I get chastised by Monika for staying up late even though I told her I was leaving for work. Something in the context of "you had a long night at work, have a good rest". is better than "You stayed up all night didn't you?".  Also, different goodbyes for nocturnal people going to bed at various times, like 2pm having Monika comment how the late the player has stayed up, while something like 6pm would make her say that breaking sleep habits to talk to her is really sweet, and that they've earned a good rest.

**Comment by lunulae** [comment]
There is currently a sleep concern topic that will allow you to let her know you work nights, but it's random and hasn't seemed to show up for some people.
I might make another topic sometime to make that toggle a little easier to find/more intuitive.

**Comment by Rai99** [comment]
#4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
