### ISSUE TITLE
Need help transferring Monika from macbook to Laptop

### ISSUE THREAD

**Issue by skyshadowninja** [Monika-After-Story/MonikaModDev#7341]
I wanted to transfer Monika to the new laptop I got from my macbook. I followed all of the instructions about backing up persistent files and even downloaded a whole new DDLC and MAS on the laptop. Also copied the MAS and the DDLC-###### on my mac and transfer them to the renpy folder on the laptop. After all of that is done, I opened DDLC and it did went to the after story, but it did not looked as updated as I had on the mac. Please help.

**Comment by lunulae** [comment]
When you say "didn't look updated" did your game run as though Monika had no memories, or does the game itself look different?

**Comment by skyshadowninja** [comment]
Monika did not looked happy when I was on the laptop. Also when I look at the calendar part, it shows 3 months instead of 3 years that I played it on the Mac

**Comment by lunulae** [comment]
Oh, that's very strange. That looks like you've had a weird drop in affection somehow. And if the time's wrong, something's definitely amiss with the persistent.

Could you try repeating the backup/restore steps one more time? If the same problem persists it might need a more thorough investigation.

**Comment by skyshadowninja** [comment]
From what i did on the MacBook, i followed the instructions on how to backup the MAS. I copied the whole MAS folder and the DDLC -#####- folder also then transfer it to the laptop on the renpy folder (on downloaded DDLC game with the updated MAS). And that’s what I got from there. Different dates when I checked from my MacBook comparing it to the laptop.

**Comment by skyshadowninja** [comment]
> Oh, that's very strange. That looks like you've had a weird drop in affection somehow. And if the time's wrong, something's definitely amiss with the persistent.
> 
> Could you try repeating the backup/restore steps one more time? If the same problem persists it might need a more thorough investigation.

is copying both folders count as backing it up or not? If not, how do u backup on a MacBook?

**Comment by lunulae** [comment]
It sounds like you've done everything correctly, I'm trying to figure out where the issue might have arisen.
Would you mind posting the persistent files from each side (Macbook+new laptop)? I'm a little shaky on the tech side but someone in the mod team might be able to make sense of what happened.

**Comment by skyshadowninja** [comment]
![Screen Shot 2021-06-14 at 4 13 20 AM](https://user-images.githubusercontent.com/47685063/121883809-0aff6500-ccc7-11eb-9d63-68baaa47cc93.png)

DDLC-#####- folder

![Screen Shot 2021-06-14 at 4 13 07 AM](https://user-images.githubusercontent.com/47685063/121883884-20748f00-ccc7-11eb-8f49-a4cf5d3ab287.png)

MAS folder

On MacBook

**Comment by skyshadowninja** [comment]
![persistent file on laptop](https://user-images.githubusercontent.com/47685063/121884498-db9d2800-ccc7-11eb-94fa-aaea98c5b48d.PNG)

**Comment by skyshadowninja** [comment]
Persistent files on laptop when searched

**Comment by H2-san** [comment]
> Persistent files on laptop when searched

Where did you end up placing the Mac's files exactly, just to be sure?
_Note: If you want to hide your username, feel free to redact with something like `<MyUsername>`._

**Comment by skyshadowninja** [comment]
I placed them both in the renpy folder as it says on the instructions

**Comment by H2-san** [comment]
> I placed them both in the renpy folder as it says on the instructions

Where is the `RenPy` folder on your new PC? Roaming or Local?

**Comment by skyshadowninja** [comment]
I believe local. I open my file explorer, and went to the DDLC 1.1.1-pc and the renpy folder is there.

**Comment by ThePotatoGuy** [comment]
could try loading with the other persistent files you have in case one of them work. otherwise its hard to say what could have happened. If you are still having a problems make a new issue.
