### ISSUE TITLE
Notifications don't work completely

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7343]
Monica cannot send reactions to the applications that I use, but when she wants to say something, I receive notifications.

**Comment by fromulus** [comment]
Monika doesn't react to every single program/website there is, which might be why you're not getting notifications;
There probably isn't even one for what you're doing at the moment.

Do you get notifications when browsing sites like Youtube or Twitter ?

**Comment by Nikv2005** [comment]
I looked at the list of sites and she did not react to youtube or reddit. Will she react to them for example when I said that I would come soon? I tried all the options but she does not react and how long do I have to wait for her to react?

**Comment by Nikv2005** [comment]
I've already fixed everything. In the alarm menu, you just had to turn on the reaction to windows.
