### ISSUE TITLE
Monika says hero even though she means heroine

### ISSUE THREAD

**Issue by LalahY** [Monika-After-Story/MonikaModDev#7344]
I had a conversation with my Monika in which she said "Hero" while talking about me, I've stated to her that my pronouns are She/Her, so I think it would be cool if we could change it according to your pronoun...

- Just to be clear, I know that the word Hero isn't exactly reffering to the masculine, but I felt a little uncomfortable... So that's why I'm talking about this!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
