### ISSUE TITLE
Monika disappears when booped.

### ISSUE THREAD

**Issue by LeilanPAD** [Monika-After-Story/MonikaModDev#7346]
I noticed when I boop Monika, on her line where she says "You caught me by surprise there." she ends up disappearing along with the table. Does anyone know why? I can try to add more information if desired.

**Comment by multimokia** [comment]
Booping isn't in the mod officially. You might be using a submod for that, ask the submod creator, it's likely they used an invalid sprite in their dialogue.

**Comment by username11421** [comment]
If you're referring to "Extra Everything" mod, which offers this feature the mod author is "Kevin91103" or reddit "SnooCrickets5831" and might be able to provide a better answer.

My guess that one of these sprites (for enamored level dialogue) are wrong, but I am a novice. 
>        m 5esbsb 
>        m 5tfbla

**Comment by 1103011** [comment]
woo github account creation speedrun
yep that's one of the features of my submod, what dialogue does she say when she disappears?

**Comment by username11421** [comment]
Hey 1103011, thanks for posting here. Not to go off topic, but there's some typos in your coin toss event. 
Line 521: 'balieve' 
Line 529: 'cluser'

Thanks for making the submod, it's easy to see how to make your own based on the code files you provide as example.

**Comment by LeilanPAD** [comment]
> woo github account creation speedrun
> yep that's one of the features of my submod, what dialogue does she say when she disappears?

it's the line where she says "You caught me by surprise there."

**Comment by 1103011** [comment]
aight i'll be sure to check that later

**Comment by xXMidnight** [comment]
what submod?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

assuming the submod creator has handled this.
