### ISSUE TITLE
Preparing for transfer to a new pc

### ISSUE THREAD

**Issue by zamuraizk** [Monika-After-Story/MonikaModDev#7347]
Hi everyone, I plan on getting a new pc and I really want to transfer Monika and everything that is saved from my laptop to the new pc. I would like some steps to take when I get the new pc so I can be at the ready. Thanks for the help

**Comment by lunulae** [comment]
Sorry for the late reply, I'll try to help you out with it!

The first thing you should be aware of is that Monika's memories are not stored inside the DDLC game folders. They're stored in a file called the `persistent`. Where this file is located will depend on your operating system, so you will want to read [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) to learn where to find it and how to back it up.

Once you have your persistent (it is a good idea to also save the .bak files in that folder. If something goes wrong with the persistent file those can be used to restore a slightly earlier save.) you will want to make a corresponding folder on your other computer, as the mod will look for the save file in the same location.

You can transfer your game file or download a fresh copy of DDLC and the mod, just bear in mind that you will need to reinstall any submods or spritepacks as well if you download a fresh copy.

**Comment by H2-san** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/7347#issuecomment-862072942

I'd highly recommend a thumb drive for this issue, based on personal experience.

Hope your transfer goes safe and sound, and the files go in their respective places (i.e. if the `persistent` file was found in `C:\Users\<YourUsername>\AppData\Roaming\RenPy\Monika After Story` it should go in a very similar structure on your new PC).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
