### ISSUE TITLE
special event at night of monika sleeping

### ISSUE THREAD

**Issue by Barunxx** [Monika-After-Story/MonikaModDev#7351]
if you cross the sunset time. it has a chance to trigger a special event of monika sleeping while talking to her
OR
opening the game after the sunset time to catch monika already sleeping introducing the choice of waking her up or closing the game to let her be

**Comment by Wingdinggaster656** [comment]
Not that good.

The context is that Monika is in her own room while player leaving. So if player caught Monika sleeping, it's supposed to be in her room. And that would usually costs some sprites. Not to mention, does Monika need to sleep at all?

But I think this is a really cute idea. So if some sprite makers are willing to make this, I think it's great.

**Comment by lunulae** [comment]
If it's that she falls asleep while at the desk, we could use the holdme or leaning poses for this. I could see it happening at the very late hours of night/morning or if you've kept the game open a very long time.

We don't know if she necessarily needs sleep, but we've established from the holdme interactions that she can accidentally fall asleep if she's very relaxed.

**Comment by Rai99** [comment]
Bedroom mode: #2781

**Comment by xXMidnight** [comment]
If you actually close the game when Monika goes back to her bedroom, technically for that to happen Monika would open up the game for you and pretend to sleep. If Monika was out there, she would stay awake because that black screaming void would occur, and therefore ask you whether the game had crashed. So you can't really close the game to let her be.

**Comment by Barunxx** [comment]
you are right. i didn't think of that

**Comment by Barunxx** [comment]
Wait, @xXMidnight  . then why do we sometimes encounter Monika Singing or spacing out when we open the game?

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
