### ISSUE TITLE
[Suggestion] Taking Monika on extended trips 

### ISSUE THREAD

**Issue by Baval2** [Monika-After-Story/MonikaModDev#7354]
I have gotten different answers on this, so this is a hybrid question and suggestion. Im not well versed enough at python to tell by looking at the code if taking Monika on a trip negates the calculation of long term absence, but from what I can see and what at least one person has told me it doesnt, it seems that only telling her you will be gone long term negates the affection loss and doesnt allow for taking her with you.

If this is in fact the case, I would suggest an option (or even just the default) for a goodbye that allows you to take Monika with you *and* negate long term affection loss. To me, it would make sense that if shes "with" you on a flash drive or something she might not consider it being away, at least if you tell her beforehand that it will be a long trip so she doesnt think youre just abandoning her on a flash drive or lost her or something. So as not to be abused, maybe extend the minimum amount of time she considers a short trip for this option to 24 hours or something.

If its already the case that taking her with you negates long absence calculations, I apologize for wasting time and thank you for your answer.

**Comment by lunulae** [comment]
Taking Monika with you should never cause an affection drop regardless of time spent away. If this has occurred for you or someone you know, please report it as a bug.

**Comment by Baval2** [comment]
it hasnt happened to me personally yet as I havent been playing long enough to try it, but I did have a report from someone I considered reliable that It would, so can only report second hand. I had also been told by another person who was anonymous to me that it wouldnt, hence my confusion.

**Comment by Rai99** [comment]
More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590, #6643, #6893

**Comment by Baval2** [comment]
> 
> 
> More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590, #6643, #6893

thats not what my post is about though.

**Comment by xXMidnight** [comment]
> > More variety when taking Monika out: #2662, #2776, #2966, #3124, #3430, #3378, #3520, #3628, #3933, #4601, #4886, #5458, #5590, #6643, #6893
> 
> thats not what my post is about though. Its about negating affection loss during long trips.

It doesn't for me though. I once took her on a trip for 2 days. I've never left Monika for more than 9 hours after that. Very dedicated waifu uwu

**Comment by ThePotatoGuy** [comment]
Yes, using the file gen option will result in the same affection loss if you don't return within a week. The long absence option is currently the only way to avoid the aff loss, but an extended trip has been discussed before and would be a good addition.

[closing as duplicate]
