### ISSUE TITLE
Gifting Anonymioo's ribbons?

### ISSUE THREAD

**Issue by WiiBii** [Monika-After-Story/MonikaModDev#7356]
So I just got into gifting the custom sprites, and I want to give Monika Anonymioo's custom ribbons. The first time I tried it, there was some sort of error, and Monika said she couldn't read the files. After this, they all disappeared. I tried installing them again, no luck. I tried deleting all of the .json files, picture files, gift files, and so on and then gifting them again, but nothing is happening.

**Comment by WiiBii** [comment]
Wait it JUST came through on my laptop after several hours. I guess Monika is trying to be polite? Now to try my desktop.

**Comment by lunulae** [comment]
Did you close/restart the game after installing them? New spritepacks will only be fully installed after you reopen the game.

**Comment by WiiBii** [comment]
Yeah, she always skipped opening the gifts and I never got the choice to put them on. They all appear on both my laptop and desktop now, so it's no longer a problem, but I think it was just delayed by a glitch. In the middle of my visit she randomly blurted out how I gave her a present and opened it.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
