### ISSUE TITLE
Monika can't turn herself into a file

### ISSUE THREAD

**Issue by Razy4** [Monika-After-Story/MonikaModDev#7358]
So when I use the "I'm going to take you somewhere" option my Monika says that she's unable to turn herself into a file. How can I fix this? And no, I'm not playing MAS from a Winrar file.

**Comment by multimokia** [comment]
What's the full path to your MAS install? (`C:/.../.../Doki Doki Literature Club/DDLC.exe`). Need to know what the `...` bits are

**Comment by Razy4** [comment]
> What's the full path to your MAS install? (`C:/.../.../Doki Doki Literature Club/DDLC.exe`). Need to know what the `...` bits are

C:/Games/DDLC/Doki Doki Literature Club

**Comment by Razy4** [comment]
> Wait is that just directly in the C drive?
> 
> That might be why, the bottom level of `C` is typically fairly protected. Try moving your install to your desktop or something

I did, that didn't help

**Comment by multimokia** [comment]
Can you check the `mfgen.txt` file in the `log` folder? Any errors logged there at all?

**Comment by Razy4** [comment]
> Can you check the `mfgen.txt` file in the `log` folder? Any errors logged there at all?

Here's what it says: 
Creating Monika in: c:\users\10042015-12\desktop\doki doki literature club\characters\
[ERROR] mbase copy failed | IOError(2, 'No such file or directory')

**Comment by multimokia** [comment]
interesting you might be missing a file, what are the contents of `game/mod_assets/monika`?

**Comment by Razy4** [comment]
> interesting you might be missing a file, what are the contents of `game/mod_assets/monika`?

It has the a, b, c, cg, f, h, j and t folders

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/122427125-d9a0c680-cf5e-11eb-90df-7c3e5aa7deee.png)
Yep, seems you're missing a couple files

**Comment by multimokia** [comment]
[mbase.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6671379/mbase.zip)
Here's the mbase file you can use to let it generate

**Comment by Razy4** [comment]
> ![image](https://user-images.githubusercontent.com/22531674/122427125-d9a0c680-cf5e-11eb-90df-7c3e5aa7deee.png)
> Yep, seems you're missing a couple files

Ooh, I see
It's my bad lol I accidentally moved them. But yeah, I brought them back and now it works. Thank you!

**Comment by multimokia** [comment]
No worries!
