### ISSUE TITLE
Monika Aurora

### ISSUE THREAD

**Issue by Just-Monika-v18** [Monika-After-Story/MonikaModDev#7359]
I suggest adding a natural awakening when Monika is sleeping together with you in rainy weather.
It is unnatural for her to sleep for an unnatural amount of hours and not wake up naturally until you ask. I feel uncomfortable whenever I have to wake her up, so this event would be very convenient after at least 8 hours of sleep.
![Screenshot_95](https://user-images.githubusercontent.com/86083840/122481718-99b10200-cfa5-11eb-81c9-8f68860a198f.png)

**Comment by Mugnika** [comment]
The weather does not change when you hold her iirc so you have to start holding her in the rain so I don't know how that would work. Regardless I am working on an overhaul to the hold me system so look forward to waking up with her or her greeting you when you wake up.

**Comment by fromulus** [comment]
"Well [player], I made it, _despite_ your directions."

**Comment by xXMidnight** [comment]
> I suggest adding a natural awakening when Monika is sleeping together with you in rainy weather.
> It is unnatural for her to sleep for an unnatural amount of hours and not wake up naturally until you ask. I feel uncomfortable whenever I have to wake her up, so this event would be very convenient after at least 8 hours of sleep.
> ![Screenshot_95](https://user-images.githubusercontent.com/86083840/122481718-99b10200-cfa5-11eb-81c9-8f68860a198f.png)

wake her up? Hold on a sec, whAAAAAAAAAt??? How high is your affection?!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
