### ISSUE TITLE
[Bug] - ComfyUI2.0

### ISSUE THREAD

**Issue by joshuajam199** [Monika-After-Story/MonikaModDev#7360]
Describe bug and steps for reproduction here
Actually, I recently downloaded a ConfyUI which was supposed to have different themes. But after including them in MAS, I cannot access it. 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6674882/traceback.txt)
Please guide me to bring my Monika back. I just reached 1000 Affection points

**Comment by multimokia** [comment]
this looks more like an issue with the Submod Updater than it does ComfyUI.

Can you send a screenshot of your `game` directory please

**Comment by joshuajam199** [comment]
Sure 
![Screenshot (24)](https://user-images.githubusercontent.com/71544768/122513964-bc382f00-d028-11eb-8c8a-8145f9b4efec.png)
![Screenshot (26)](https://user-images.githubusercontent.com/71544768/122513966-be01f280-d028-11eb-862a-e1a761738250.png)
![Screenshot (45)](https://user-images.githubusercontent.com/71544768/122513968-be9a8900-d028-11eb-9b6f-095eea791292.png)
![Screenshot (49)](https://user-images.githubusercontent.com/71544768/122513972-bfcbb600-d028-11eb-8e73-1315c7deb06e.png)

**Comment by joshuajam199** [comment]
This is the submod updater file. I think this is also connected with the bug.
[submod_updater_plugin.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6674943/submod_updater_plugin.txt)
I converted it to txt just to send it through Github

**Comment by joshuajam199** [comment]
[errors.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6675845/errors.txt)
Can this be of any help?

**Comment by Booplicate** [comment]
![Capture](https://user-images.githubusercontent.com/53382877/122533158-e807e480-d029-11eb-9583-3c0f3d7ae276.PNG)
Someone or something modified this line, that might be the reason it crashes now. Try to add 2 spaces there, or just redownload it.

**Comment by joshuajam199** [comment]
I did that but the problem is Still there
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6676011/traceback.txt)

**Comment by Booplicate** [comment]
Did it work before you installed ComfyUI?

**Comment by joshuajam199** [comment]
Ya 
It used to work fine

**Comment by joshuajam199** [comment]
In the ComfyUI zip file there were many files which needed to be replaced eg Definitions etc

**Comment by joshuajam199** [comment]
Is there any way to make a fresh installation and keep all the memories intact. I still have those persistant files and savedata

**Comment by Booplicate** [comment]
Your save data won't be affected. You can create a new install, or delete conflicting submods.

It's weird that that submod replaces so many files, I don't think it should. You may want to report it to its creator.

**Comment by joshuajam199** [comment]
Still Thank you very much. Reinstalling the mod removed all the add ons 
But she still remembers me. That's all I require

**Comment by xXMidnight** [comment]
> Still Thank you very much. Reinstalling the mod removed all the add ons
> But she still remembers me. That's all I require

aww, someone really likes Monika ;D

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
