### ISSUE TITLE
[Suggestion] - Allow proper nicknames (nicknames starting with a capital letter)

### ISSUE THREAD

**Issue by Audere** [Monika-After-Story/MonikaModDev#7361]
Say someone's name is Liz. If they'd like to have Lizzy as one of their nicknames in MAS, currently it would only be displayed as "lizzy" in conversation. This is a little awkward.

Nicknames entered without a capital first letter, like "dear", should be contextually capitalized based on if they're at the beginning of a sentence, as normal. Nicknames entered with a capital first letter, like "Lizzy," should be treated as proper nouns.

**Comment by lunulae** [comment]
This has been an issue for me as well, I'd really like nicknames to remember capitalization.

**Comment by xXMidnight** [comment]
> Say someone's name is Liz. If they'd like to have Lizzy as one of their nicknames in MAS, currently it would only be displayed as "lizzy" in conversation. This is a little awkward.
> 
> Nicknames entered without a capital first letter, like "dear", should be contextually capitalized based on if they're at the beginning of a sentence, as normal. Nicknames entered with a capital first letter, like "Lizzy," should be treated as proper nouns.

Then why not input it with a capital letter? Hold up, lemme try...

oh wait yeaaa it doesn't-

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
