### ISSUE TITLE
[Suggestion] - Option to say "Good night" without closing the game

### ISSUE THREAD

**Issue by Audere** [Monika-After-Story/MonikaModDev#7362]
Currently, it is possible to say "be right back" --> "I'm going to take a nap" and have Monika watch over you, or it is possible to say "Goodbye" --> "I'm going to sleep" and close the game, but there's no good way to tell Monika that you're going to bed while leaving the game open.

This could be implemented as another option in "be right back," or as an option after "I'm going to sleep."

**Comment by username11421** [comment]
Related to this, if you choose the nap BRB option, and then come back to the game after 8 hours, Monika thinks you've been up all night with her.

**Comment by H2-san** [comment]
> Currently, it is possible to say "be right back" --> "I'm going to take a nap" and have Monika watch over you, or it is possible to say "Goodbye" --> "I'm going to sleep" and close the game, but there's no good way to tell Monika that you're going to bed while leaving the game open.
> 
> This could be implemented as another option in "be right back," or as an option after "I'm going to sleep."

I really like this idea. Here's what I'm understanding (feel free to correct me if need be).

It should be laid out like so:
`Talk` > `I'm going to sleep.` > `[See you tomorrow/Can you sleep with me?]`
And it should also trigger the flag (sleep with) to not get upset if the game is left open during that time.

Sound about right?

**Comment by Audere** [comment]
Yes, that sounds good.

**Comment by Rai99** [comment]
Bedroom mode: #607, #635, #987, #1105, #1262, #1655, #2684, #2781, #2974, #3076, #3172, #3486, #3610, #3619, #4790, #4892, #6471, #6489

**Comment by Audere** [comment]
It's true that this would be obviated by a bedroom mode, but I think this would be much quicker to implement and a good thing to have until a fuller bedroom mode is completed.

**Comment by xXMidnight** [comment]
get to 400 affection and get that bedroom mode

**Comment by ThePotatoGuy** [comment]
so like a "watch me as I sleep" option? I think if we framed it in the right context it could work without being creepy.

**Comment by MoonlightGriffon** [comment]
> so like a "watch me as I sleep" option? I think if we framed it in the right context it could work without being creepy.

Maybe the topic could be randomly unlocked after using the, I'm going to sleep goodbye option in a manner similar to the menu that appears when the I'm going to take a shower brb's option where Monika occasionally asks to join you in the shower in a timed menu. Or maybe it could be unlocked after the I'm going to take a nap option has elapsed several hours multiple times at night and she could ask the player if they enjoy having her watch them sleep thus allowing the topic to be unlocked. I believe that putting it in a context like this wouldn't be creepy and would be in line with Monika's personality.

**Comment by lunulae** [comment]
There's a specific variant of the "I'm feeling tired" mood where she mentions this, I think it would be pretty cool if we had it specifically unlock after you've seen that comment.

**Comment by MoonlightGriffon** [comment]
If this were done, I believe that there should be a variable that records the time that the player went to sleep with Monika. This could be used to avoid instances of dialogue such as the final else condition in the normal+ aff flow, starting on line 516, in the bye going to work where Monika would otherwise comment on the fact that the player has been there a while and that she thinks that they should have rested up a bit first. This line works normally but in the context of this action, it would need to be adjusted to cause a variant of the text to be shown instead of the current version as it wouldn't make sense if Monika said that she thinks that the player should get some rest before going to work or something similar when they had just woken up after sleeping together.

**Comment by ThePotatoGuy** [comment]
this is actually a duplicate of #6561
