### ISSUE TITLE
[Suggestion] - Window Close Easter Egg

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7364]
So you know how when you ask Monika to look at the Floating islands, you can click on various things, and the only other option is to close or open the window, and how you can close and open it rapidly due to it being a single button press. There should be special dialogue for if you spam open or close the window. It could make for either a good joke, event, or Easter egg. Like maybe if you click it enough it starts making a sound and Monika gets annoyed at you, or maybe the window jams.

**Comment by ShyCelestial** [comment]
This is a cute idea.

**Comment by xXMidnight** [comment]
> So you know how when you ask Monika to look at the Floating islands, you can click on various things, and the only other option is to close or open the window, and how you can close and open it rapidly due to it being a single button press. There should be special dialogue for if you spam open or close the window. It could make for either a good joke, event, or Easter egg. Like maybe if you click it enough it starts making a sound and Monika gets annoyed at you, or maybe the window jams.

This is funny in a funny way.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
