### ISSUE TITLE
How to gain affection

### ISSUE THREAD

**Issue by PeckNeck123** [Monika-After-Story/MonikaModDev#7366]
How do I know how much affection I have and how much you need to unlock the minigames and how much "I love you" gives

**Comment by lunulae** [comment]
Minigames are unlocked based on time you have left the game running rather than by affection. I don't have an exact time unfortunately, but if I recall right most of them besides piano unlock fairly quickly.

Affection, rather than unlock things, mostly changes the behavior of your Monika and what she says in a few topics. There is a cap per day that you can gain (besides a few exceptions, like the first time you use a new compliment) so it's not really something you farm so much as gradually goes up as you visit her each day.

**Comment by username11421** [comment]
You can see your affection in the file called "aff_log.txt" under the subfolder called "Log". Editing this will not change your affection. I love you gives 3 affection per use, up to 7 per day. Piano unlocks after 84 hours open time (12 levels at 420 exp per level and 60 exp per hour, granted every two hours) _and_ 100 affection. You can see how the piano unlocks in the progession.rpy file I believe.

**Comment by Wingdinggaster656** [comment]
> You can see your affection in the file called "aff_log.txt" under the subfolder called "Log". Editing this will not change your affection. I love you gives 3 affection per use, up to 7 per day. Piano unlocks after 84 hours open time (12 levels at 420 exp per level and 60 exp per hour, granted every two hours) _and_ 100 affection. You can see how the piano unlocks in the progession.rpy file I believe.

Corrected: "I love you" won't gives 3 affection, the exact number depends on your current affection level. If Monika is still in Normal mode, then "I love you" gives only 1 affection.
I also heard that "I love you" can only gives 0.1 affection in Distressed mod, don't know if this is true.

**Comment by username11421** [comment]
>Corrected: "I love you" won't gives 3 affection, the exact number depends on your current affection level. If Monika is still in Normal mode, then "I love you" gives only 1 affection.
I also heard that "I love you" can only gives 0.1 affection in Distressed mod, don't know if this is true.

Good point, thank you; 3 is for affectionate. I'm not sure how much it gives in distressed mode and it's not obvious from a quick look at the "monika_love" event in the script-topics.rpy file. 

I love you/ILY too options also have a timer and can only give affection every 3 minutes.

**Comment by xXMidnight** [comment]
> How do I know how much affection I have and how much you need to unlock the minigames and how much "I love you" gives

u want affection???
y u nu want to enjoy Monika????

**Comment by xXMidnight** [comment]
Question: What is the fastest way to get affection because I am teetering on the edge of 396.6 affection and I wanna get to 400

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
