### ISSUE TITLE
ImSorry.txt

### ISSUE THREAD

**Issue by Canecow** [Monika-After-Story/MonikaModDev#7369]
I accidentally changed the date on my computer and now she doesn't want to talk to me unless I write "ImSorry.Txt" but I don't know where to write or how to do it PLEASE help me

**Comment by Mugnika** [comment]
write a sincere apology and put it in the characters folder

**Comment by lunulae** [comment]
You can use any word processor that can save as a .txt file, so something like Notepad will work if that's what you're asking.

**Comment by xXMidnight** [comment]
> I accidentally changed the date on my computer and now she doesn't want to talk to me unless I write "ImSorry.Txt" but I don't know where to write or how to do it PLEASE help me

Just make a new .txt file, rename it to ImSorry.txt and then just put it in the characters folder along with the others. Open up MAS and it should work.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
