### ISSUE TITLE
I can't open the game please help

### ISSUE THREAD

**Issue by Auto-bot333** [Monika-After-Story/MonikaModDev#7370]
So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^

**Comment by Mugnika** [comment]
did you just install the mod or are you using submods?

**Comment by Wingdinggaster656** [comment]
What's the content of that traceback?

**Comment by H2-san** [comment]
> 
> 
> So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^

We need your `traceback.txt` file to know what's going on.

**Comment by Auto-bot333** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 4047, in script
  File "game/definitions.rpy", line 4049, in <module>
ImportError: No module named pytz

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/definitions.rpy", line 4047, in script
  File "C:\Users\*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 4049, in <module>
ImportError: No module named pytz

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by Auto-bot333** [comment]
Also the "*user*" part is just the anonymous version of the actual user

**Comment by Auto-bot333** [comment]
> > So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^
> 
> We need your `traceback.txt` file to know what's going on.

I'm sorry, but an uncaught exception occurred.

While running game code:
File "game/definitions.rpy", line 4047, in script
File "game/definitions.rpy", line 4049, in
ImportError: No module named pytz

-- Full Traceback ------------------------------------------------------------

Full traceback:
File "C:\Users*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
renpy.main.main()
File "C:\Users*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
game.context().run(node)
File "game/definitions.rpy", line 4047, in script
File "C:\Users*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
File "C:\Users*user*\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
exec bytecode in globals, locals
File "game/definitions.rpy", line 4049, in
ImportError: No module named pytz

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by Auto-bot333** [comment]
> > > So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^
> > 
> > 
> > We need your `traceback.txt` file to know what's going on.
> 
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> File "game/definitions.rpy", line 4047, in script
> File "game/definitions.rpy", line 4049, in
> ImportError: No module named pytz
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
> renpy.main.main()
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
> game.context().run(node)
> File "game/definitions.rpy", line 4047, in script
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
> renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
> exec bytecode in globals, locals
> File "game/definitions.rpy", line 4049, in
> ImportError: No module named pytz
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187

Also the "user" part is just the anonymous version of the actual user

**Comment by xXMidnight** [comment]
why.

why do people keep editing the game/definitions.rpy file.

it's an ImportError, so there's something wrong with the code or something? I've only had AttributeError and InputError while coding Python (the turtle logo kind eg. tom.fd(100) ) so I don't know what that error is. Sorry, I can't help :(

**Comment by xXMidnight** [comment]
> > > So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^
> > 
> > 
> > We need your `traceback.txt` file to know what's going on.
> 
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> File "game/definitions.rpy", line 4047, in script
> File "game/definitions.rpy", line 4049, in
> ImportError: No module named pytz
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
> renpy.main.main()
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
> game.context().run(node)
> File "game/definitions.rpy", line 4047, in script
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
> renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
> exec bytecode in globals, locals
> File "game/definitions.rpy", line 4049, in
> ImportError: No module named pytz
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187

Literally fix what the thing said.
File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap, so go to that bootstrap.py and edit line 295. Repeat with all.

**Comment by Auto-bot333** [comment]
> > > > So I'm trying to open the game but when I do, it gives me an error an opens up the "taceback.txt" thing. If anyone knows how to fix this please let me know. ^^
> > > 
> > > 
> > > We need your `traceback.txt` file to know what's going on.
> > 
> > 
> > I'm sorry, but an uncaught exception occurred.
> > While running game code:
> > File "game/definitions.rpy", line 4047, in script
> > File "game/definitions.rpy", line 4049, in
> > ImportError: No module named pytz
> > -- Full Traceback ------------------------------------------------------------
> > Full traceback:
> > File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
> > renpy.main.main()
> > File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
> > game.context().run(node)
> > File "game/definitions.rpy", line 4047, in script
> > File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
> > renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
> > File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
> > exec bytecode in globals, locals
> > File "game/definitions.rpy", line 4049, in
> > ImportError: No module named pytz
> > Windows-8-6.2.9200
> > Ren'Py 6.99.12.4.2187
> 
> Literally fix what the thing said.
> File "C:\Users_user_\Downloads\ddlc-win (1)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap, so go to that bootstrap.py and edit line 295. Repeat with all.

Oh jeez, I'm kinda stupid aren't I? Lol

sorry I am pretty new to these sorta things

**Comment by ThePotatoGuy** [comment]
@Auto-bot333 I hope you did not follow any of @xXMidnight 's instructions because they were all wrong.

Start by double checking that you [installed the mod correctly](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#is-there-a-guide-for-installing-mas).

Once you have verified that and you still have the traceback on start, check [these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-still-cant-run-the-game-and-none-of-the-above-faqs-solve-my-issue).
