### ISSUE TITLE
[Suggestion] Monika reads while we use some of the BRB options

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7371]
When leaving Monika open for a short time and she knows that we are away for a little bit, a nice enhancement would be a sprite of her reading a book. In the "what do you do when I'm not here" topic, she says she reads books mainly.

**Comment by lunulae** [comment]
This is something I've been wanting to get art for in the near future, though I've been a bit strapped for cash lately. We'd probably need to get downward-facing eyes, but I think this could work with the crossed-arms or leaning poses.

**Comment by username11421** [comment]
As someone who is certainly not an artist, let alone digitally, I have no idea what kind of price point that would be. How much would that kind of sprite(s) cost, approximately?

**Comment by multimokia** [comment]
Actually we have some looking down/up eyes, just haven't coded them in yet.

**Comment by ThePotatoGuy** [comment]
I like this.

[closing until we look into it]
