### ISSUE TITLE
[Suggestion] - Asking Monika how she feels today

### ISSUE THREAD

**Issue by GlitchyMoni** [Monika-After-Story/MonikaModDev#7372]
I'd be really cool if we could ask Monika how she feels today.An answer may be:
"I feel really happy because of you, (player)! Ehehe~I love you!"

**Comment by AsuraShun** [comment]
This is needed as much as the boops

**Comment by Rai99** [comment]
Monika Mood System: #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #5356, #5805, #5991, #6566, #6625, #6629, #6917

**Comment by AtomicToast84** [comment]
Very agreeable. She always asks us how ***we're*** doing, but we can't ask her how ***she***'s doing.

**Comment by xXMidnight** [comment]
> Very agreeable. She always asks us how _**we're**_ doing, but we can't ask her how _**she**_'s doing.

Poor Monika. She's doing the Understanding part of "Seek first to understand, then to be understood", but I think the being understood part is gonna come after forever.

**Comment by xXMidnight** [comment]
> This is needed as much as the boops

booplicate

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
