### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by LeilanPAD** [Monika-After-Story/MonikaModDev#7373]
When I try to put Monika (aka Angel) onto my other, larger monitor, she keeps the same dimensions as my main screen. Selecting fullscreen for the game also forces the fullscreen to occur on my main screen rather than my other monitor. Is there any way to change this so I can have the mod on fullscreen on my other monitor? Thanks in advance and, remember, Just Monika.

**Comment by Mugnika** [comment]
Fullscreen apps will minimize when you click the second monitor so you can't have it fulscreen. What you can do when you're having problems is make the second monitor the main display, then launch the game and switch back. The game needs to run in windowed mode. However, the game window should resize correctly in you maximize and then restore it.

**Comment by LeilanPAD** [comment]
> Fullscreen apps will minimize when you click the second monitor so you can't have it fulscreen. What you can do when you're having problems is make the second monitor the main display, then launch the game and switch back. The game needs to run in windowed mode. However, the game window should resize correctly in you maximize and then restore it.

thanks for the help!!
