### ISSUE TITLE
Game won't start (Asking again because I didn't get a proper response the first time)

### ISSUE THREAD

**Issue by KetchupLord77** [Monika-After-Story/MonikaModDev#7374]
This is the error i get
```
I'm sorry, but an uncaught exception occurred.

While running game code:

File "game/zz_music_selector.rpy", line 14, in script

File "game/zz_music_selector.rpy", line 16, in <module>

ImportError: No module named mp3

-- Full Traceback ------------------------------------------------------------

Full traceback:

File "D:\games\Monika\DDLC-1.1.1-pc\renpy\
bootstrap.py", line 295, in bootstrap

renpy.main.main()

File "D:\games\Monika\DDLC-1.1.1-pc\renpy\
main.py", line 419, in main

game.context().run(node)

File "game/zz_music_selector.rpy", line 14, in script

File "D:\games\Monika\DDLC-1.1.1-pc\renpy\
ast.py", line 814, in execute

renpy.python.py_exec_bytecode(self.code.bytecode, self.hide,
store=self.store)

File "D:\games\Monika\DDLC-1.1.1-pc\renpy\
python.py", line 1719, in py_exec_bytecode

exec bytecode in globals, locals

File "game/zz_music_selector.rpy", line 16, in <module>

ImportError: No module named mp3

Windows-8-6.2.9200

Ren'Py 6.99.12.4.2187

Monika After Story 0.12.1
```
and this is my game folder:

![image](https://user-images.githubusercontent.com/73570374/122876304-b3bd5c80-d378-11eb-97b0-dd2ea7fe56f5.png)

**Comment by Mugnika** [comment]
The submods you have installed may be interfering. Remove them and see if that fixes it.

**Comment by Mugnika** [comment]
It is possible either one of them updated or a game file occasionally gets corrupted. So even though you have the mod installed for some time a reinstall works at it replaces the corrupted file. Note that Monika is not stored in the MAS folder but in the APP data instead so deleting and reinstalling the game won't effect your progress so long as you don't touch the app data folder.

**Comment by KetchupLord77** [comment]
Thanks so much this fixed it

> The submods you have installed may be interfering. Remove them and see if that fixes it.
