### ISSUE TITLE
[Suggestion] Monika writes a positive poem about positivity

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#7375]
So I have been thinking about something. From my experience, there are many people playing this mod who are not really happy with their life or themselves and who often feel sad. So I thought that if the player told Monika they aren't happy with themselves or they tell her that they are feeling sad (and it's not just because of a bad day), than Monika will surprise the player the next day (or a few days after) with a poem about positivity in hopes that it will make the player feel just a bit better.

I know Monika already writes poems on special occaisions, but this is different. It's especially sweet that she doesn't do it because of a special occaision, but because she cares about what you told her. I'm sure many people would be moved to know that Monika took the time to write a poem for them to make them feel better.

**Comment by username11421** [comment]
Sounds pretty nice. If you have one/several poem variants for these occasions, you would have most of what you need to create a submod. You can see how the existing poems are written in the script-affection.rpy file. Be careful when reading it of spoilers though.

**Comment by ThePotatoGuy** [comment]
She already writes some poems, so I'll change the name of this to reflect a new poem of specific content.

[closing until we look into it]
