### ISSUE TITLE
How much affection do i need to give Monika clothes?

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7380]
Ive seen many videos about how to give monika clouthing, but when i try it it never work. 
Is the affection playing the role here or am i just doing the thing wrong???

**Comment by Auto-bot333** [comment]
I'm not an expert or anything, but I think that you need to have a certain version of the game to do that

**Comment by multimokia** [comment]
Chances are you're doing something wrong. Clothes can be gifted at any affection. What clothes are you trying to give her? If they're spritepack outfits, have you installed the spritepack for it?

**Comment by VikicatCZSK** [comment]
Yes, i did download the spritepack and yea there is a chance im doing it wrong becuse how i said ive seen many videos of how to do that, but all of them used different method. any recommendation/ ideas/videos how do i give it to her that works?

**Comment by xXMidnight** [comment]
There are many ways, but the most reliable way for me is to copy and paste everything from corresponding spritepack folder letter to DDLC -> game -> mod_assets -> mod_assets (in which should have 2 folders: "monika" and "thumbs", so move stuff from spritepack "monika" to mod_assets "monika" and repeat with "thumbs". If mod_assets "monika" doesn't have the folder letter, simply copy and paste folder.) After that, you can exit the second mod_assets and enter the first. Inside the first mod_assets in DDLC, there should be another "monika" file and another "thumbs" file. Repeat what you just did, except you can now move the items. I still recommend copying and pasting, as it is easy to make a mistake. Once you're done, reboot MAS if you left it open, go to your spritepack .gift folder and paste the components inside the character folder, open up MAS and you're done! Ask me anything if you still don't understand.

**Comment by VikicatCZSK** [comment]
> There are many ways, but the most reliable way for me is to copy and paste everything from corresponding spritepack folder letter to DDLC -> game -> mod_assets -> mod_assets (in which should have 2 folders: "monika" and "thumbs", so move stuff from spritepack "monika" to mod_assets "monika" and repeat with "thumbs". If mod_assets "monika" doesn't have the folder letter, simply copy and paste folder.) After that, you can exit the second mod_assets and enter the first. Inside the first mod_assets in DDLC, there should be another "monika" file and another "thumbs" file. Repeat what you just did, except you can now move the items. I still recommend copying and pasting, as it is easy to make a mistake. Once you're done, reboot MAS if you left it open, go to your spritepack .gift folder and paste the components inside the character folder, open up MAS and you're done! Ask me anything if you still don't understand.

do you have any video that shows how to do it ? 
becuse by this i dont understand whitch folder to open/ use and it confuses me even more-

**Comment by VikicatCZSK** [comment]
EDIT!!!!
now i finally understand how to do it 
thanks to @xXMidnight  for telling me the exact steps to it (btw if you dont undersand it, read it five more times and then you will understand it)
ill leave this issue open for other people if they need help

i also want to thanks everyone who helped me too -
@Auto-bot333 
and
@stmobo

**Comment by Legendkiller21** [comment]
@xXMidnight Stop this. You have already been told that this is completely incorrect and you still continue saying the same things. Also, there are no 2 `mod_assets` folders.

[This is the correct way of installing sprite packs](https://www.youtube.com/watch?v=bjJ0U8l1m8c).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
