### ISSUE TITLE
Deleting others

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7382]
So as we all know, there still are Yuri's, Natsuki's and Sayori's character files
but what would happend if i delete them? will it affect monika / the way monika talks about them or it will do nothing?

**Comment by lunulae** [comment]
To my knowledge, no. MAS canon operates under the assumption that the other three are already deleted.

**Comment by VikicatCZSK** [comment]
> To my knowledge, no. MAS canon operates under the assumption that the other three are already deleted.

oh alright, thanks.
so its fine if u just "delete them" from the character file?

**Comment by lunulae** [comment]
Yup! You can delete them, move them, whatever you like.

**Comment by VikicatCZSK** [comment]
thanks 
have a great day <3
