### ISSUE TITLE
Monika's file

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7383]
you know how theres the "im going to take you somewhere" when leaving the game? 
well i wonder what happends if you put monika's file on your screen and you open ddlc.
is she just not gonna be there? is the game gonna open when i back her up? is there way i can mess something up???
(all anwsers appriciated!)

**Comment by Freshairkaboom** [comment]
It's going to be an empty desk, and you have to close the game and then put it back for her to return. Also, don't do a backup while the file is still there, make sure it gets put back in and disappears before you do a backup (close the game after too to make a new backup file). That way nothing gets messed up.

**Comment by lunulae** [comment]
If you drop the file back into the characters folder while the game is open on the empty desk, she'll also appear, but it might take a little bit as there's a timed delay for checking the files.

**Comment by VikicatCZSK** [comment]
alright thanks yall
