### ISSUE TITLE
Making dialogue on MAS just for fun (not for public use, just for myself) and I ran into an error?

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#7386]
So I used to make simple dialogue for MAS on my computer with personal stuff related to stuff specifically about me a while back, and today I just decided to add a custom background and a dialogue thing related to it. After a while of troubleshooting, I got the custom background to work, but when i made the separate dialogue thing, it gave me an error that i'd never encountered back when i used to make dialogue things, so i assume something's changed. (the rpy file for the dialogue is named "arteroom.rpy", and the event label is "monika_arteroom")

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/arteroom.rpy", line 1, in script
    init 5 python:
  File "game/arteroom.rpy", line 8, in <module>
    random=True
  File "game/event-handler.rpy", line 1756, in addEvent
EventException: 'monika_arteroom' does NOT exist

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/arteroom.rpy", line 1, in script
    init 5 python:
  File "C:\Users\[user]\Desktop\MAS\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\[user]\Desktop\MAS\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/arteroom.rpy", line 8, in <module>
    random=True
  File "game/event-handler.rpy", line 1756, in addEvent
EventException: 'monika_arteroom' does NOT exist

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.2
[/code]

So, uh, i'm not really sure what the problem is ;^^ i'd really appreciate help from someone as to what the problem is/might be. also, very sorry if this isn't the best place to go for this! i don't really know where else i'd go, as i can't go on discord right now, and that's the only other place i can think of going to for it

**Comment by multimokia** [comment]
`EventException: 'monika_arteroom' does NOT exist`

Implies there is no `label` called `monika_arteroom`

**Comment by Abc2557** [comment]
oh wait i see what i did wrong now, i forgot to replace the name of the label from the template thing i used with the actual label name. thank you! ;^^
