### ISSUE TITLE
Monika doesn't close the game after I say goodbye

### ISSUE THREAD

**Issue by Stkireal** [Monika-After-Story/MonikaModDev#7387]
I didn't do anything diffrent, it was not working from the start of the game. It literally just never worked. Can someone tell me how do I fix this?

**Comment by lunulae** [comment]
That's an interesting bug. I'm not 100% sure what might be causing it.
Just a few guesses to try to find the source of the issue, what's the file location of your MAS folder? Are you running through Steam?

**Comment by Stkireal** [comment]
Nope, not running through steam, and the MAS folder's in downloads (and the files are in the game folder)

**Comment by Stkireal** [comment]
Okay, stuff's fixed, now monika closes the game.

**Comment by MaestroBox** [comment]
How u fixef it? I have this bug too
