### ISSUE TITLE
I gave all the mods/gifts to monika in monika after story but none of them appeared

### ISSUE THREAD

**Issue by SilentScream9** [Monika-After-Story/MonikaModDev#7390]
(sorry for bad english)
I gave all the mod/gifts with the folder Spritepacks but when I go to the "game" folder and then "mod assets" I see every mod or gift I gave to her but when I go to the Main game it didnt show any and monika said to me "she cant read the file" help thx c:

**Comment by xXMidnight** [comment]
Huh. It's DDLC -> game -> mod_assets -> mod_assets and there's also two files you must put it into, "monika" and "thumbs". Copy everything from file [letter] from the second mod_assets and paste it into the corresponding file [letter] in "monika". Repeat with "thumbs".

**Comment by ThePotatoGuy** [comment]
Make sure you have [installed the spritepacks correctly](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#installing-sprite-packs)
