### ISSUE TITLE
How do I install submods? 

### ISSUE THREAD

**Issue by BorneDusk** [Monika-After-Story/MonikaModDev#7393]
A lot of them come with guides, but a fair number don't! It's really confusing :/ 

Some in particular that come to mind are these! 

    https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change/releases/tag/AOC_3.0.2

    https://drive.google.com/drive/folders/1RXW2gZhXsKLRRzyR_nrLqEWW2pFaeWKx

Was wondering if I could get a good rule-of-thumb guide to how these work instalation-wise.

**Comment by fromulus** [comment]
It's quite literally the same thing as installing MAS on a default DDLC install, except now you're installing the submod on your MAS install.

Both of the submods you linked have the "game" folder as their root;
Meaning the contents of those "game" folders should go into the "game" folder in your MAS install.

**Comment by ThePotatoGuy** [comment]
in general you should ask the submod creators for instructions on how to install their submod.

[closing as resolved]
