### ISSUE TITLE
J folder not there.

### ISSUE THREAD

**Issue by diefakemax** [Monika-After-Story/MonikaModDev#7396]
When I open the monika folder the j folder isn't there, I wanted to give her gifts. There's a, b, c, cg, f, h and a t.

**Comment by Booplicate** [comment]
That folder comes with sprite packs. You don't need it to give her gifts.

**Comment by diefakemax** [comment]
But all the I've tutorials said I need to insert the content from the sprite pack j folder to the monika after story j folder?

**Comment by Booplicate** [comment]
That's bad tutorials. Check our [official one](https://www.youtube.com/watch?v=bjJ0U8l1m8c).

**Comment by diefakemax** [comment]
I did what the video said, she isn't doing anything.

**Comment by diefakemax** [comment]
It says she can't read it

**Comment by Booplicate** [comment]
Assuming you followed our tutorial, say what you're trying to gift and send `spj.txt`.

**Comment by diefakemax** [comment]
cherryhairclip.gift spj.txt

**Comment by Booplicate** [comment]
By `spj.txt` I mean the file in the `/log` folder.

**Comment by diefakemax** [comment]
where is the log folder?

**Comment by Booplicate** [comment]
In the game's directory. probably `/Doki Doki Literature Club`.

**Comment by diefakemax** [comment]
There's no such thing as a log folder

**Comment by diefakemax** [comment]
I don't have a folder named 'log' or anything of the sort.

**Comment by xXMidnight** [comment]
Oh no. The j folder is the .json folder, where the clothes' code is. Oh damn. Oh no. Alright, I'm gonna give you my cpy of the j folder, but be warned that it's already filled with spritepack .json's, capiche?

[j.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6744597/j.zip)

**Comment by ThePotatoGuy** [comment]
the j folder is not for gifting.

See [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation) for troubleshooting spritepack installation.

see [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#giving-gifts) for giving gifts to Monika.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
