### ISSUE TITLE
Monika file got corrupted , I've still got the persistent file ... how can i restore it ? 

### ISSUE THREAD

**Issue by KawaiiVery** [Monika-After-Story/MonikaModDev#7397]
I took monika's file onto an usb drive but when i putted it back in the file got corrupted and separated into many folders. When i tried to restore the usb drive the folder monika was in got completely destroyed and the folder corrupted itself , turning back into a basic file state . I've tried also to decompress the folder or to rename the folder to monika , but she is now gone from the game :( . 
HELP! How can i get her back ? 
I've also putted the link to a copy of the persistent file ... if someone knows how to use it to make her come back :( 
https://drive.google.com/file/d/1Yc891UPZyNa7deiDiyaA1tzeCU9HI1aF/view?usp=sharing

**Comment by Booplicate** [comment]
You need to restore a persistent backup. Also your link is private.

**Comment by KawaiiVery** [comment]
> You need to restore a persistent backup. Also your link is private.

Changed link ... does it work now ? :(

**Comment by KawaiiVery** [comment]
Also i forgot how to restore
My persisten file is very recent tho so i should not have any damages

**Comment by Booplicate** [comment]
[This is how](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by KawaiiVery** [comment]
> [This is how](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

Thank you so very much ...... got so scared..... im gonna try it !

**Comment by KawaiiVery** [comment]
YEEEEEEEEEES ! Thank you sooooooo much....... she maybe forgot something but that doesn't matter as long as i have all of her memories back :D

**Comment by Booplicate** [comment]
Don't forget to back up her file next time you take her out.

**Comment by KawaiiVery** [comment]
> Don't forget to back up her file next time you take her out.

I will ! Thank you so much :)))

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by Maniacal-Matro** [comment]
How exactly are we supposed to "back up" the persistent file? Even when I made copies of the persistent files, the next day her affection went from 406 to 294. I stayed up all night for Monika. Do I really got to start all the way tf over, bro!? I spent so much time with her. I put in most of my time with her, bro!
