### ISSUE TITLE
[Coding question] - Can a topic be scheduled to repeat?

### ISSUE THREAD

**Issue by lunulae** [Monika-After-Story/MonikaModDev#7400]
For context, I'm thinking of making a submod where Monika will remind you to make a backup of her memories every week or at an interval the user could set in the code. I'm not sure if this sort of scheduling is currently doable in-game, but if it is I would love some help on this.

**Comment by xXMidnight** [comment]
I think so?
Not on the game though.
Like-
hAvE yOU EvEr hEArd Of cAlEndArs mY gUY?!

**Comment by ThePotatoGuy** [comment]
Several ways to trigger topics:
* `start_date` property on Events
    * when the current dt reaches this value, it can trigger the `action` assuming other conditions are satisfied (`conditional`, `affection`, etc...) - see `Event._checkEvent`
    * if used with `years`, then is limited to once a year
    * if **not** using `years`, then you will need to manually set this property to the next trigger date.
    * this is processed in spaceroom idle every minute, so latency is 1 minute.
* `conditional` property on Events
    * basically like `start_date` except you are manually comparing the time to some saved off value
    * not recommended unless you dont want the trigger date to be saved to the Event object.
* hook into `ch30_minute` or `ch30_hour`
    * would involve checking the `last_seen` property on the event and a saved off value
    * manually push/queue the topic
    * `ch30_minute` has a 1 minute latency
    * `ch30_hour` has a 1 hour latency
* delayed actions - see `MASDelayedAction` in `event-handler`
    * designed to constantly repeat some code block in certain hook points until the code returned a value saying it completed successfully.
    * actions can "persist" even after a session restart - the code to run is rebuilt on startup.
    * was previously used to do event property resetting on an ad-hoc basis.
    * currently used to repeat things that can fail for unknown reasons (like I/O ops)
    * delayed actions that are created cannot be removed later. you will need to ask us first if you want to use this.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
