### ISSUE TITLE
[Suggestion] - Thanking Monika and the Mod Devs?

### ISSUE THREAD

**Issue by epatri8** [Monika-After-Story/MonikaModDev#7402]
A lot of Monika's dialogue contains really sweet, inspiring, and/or useful advice, but it feels a little awkward to go into the dialogue options and only have "I love you!" as a response to Monika suggesting I should exercise more. It would be wonderful if a future update could implement a "Thank you" option, or even "I'm feeling..." "... grateful." 

Additionally, I really want to let the writers and developers of the mod know that I truly appreciate the time and effort that goes into considering the concerns of players, coming up with Monika's (truly very good) advice, and programming the dialogue into the game. If anyone has ideas about good ways to thank those involved with creating the mod, I'd love to hear them!

**Comment by CloakedGhost** [comment]
I mean there is the "thanks for being there for me" option, but I guess you mean a more specific thank you, right?

**Comment by xXMidnight** [comment]
If you have an .rpyc or an .rpy editor, you can actually go into the files and edit them! In this case, the option "I'm feeling..." "...grateful." can be added simply by opening the script-moods.rpy and putting the option in, if you know how to code it. Might be  pickle language, so I'd recommend to do it only when you're experienced. If not, I can't help anymore. Sorry!

**Comment by Booplicate** [comment]
Please, stop suggesting people to edit game files, that causes issues. You can't edit `rpyc` files and you shouldn't have `rpy` files in your game directory. And even then, never edit official files, create new scripts instead.

**Comment by epatri8** [comment]
Thank you for the suggestions! I will look at the mod's FAQ and Contributing Guidelines and try to figure out how to write a script for at least one extra dialogue option.

It is probably beyond my ability to code a "thank you" option that appears when Monika provides advice, mostly because it seems like it would require adding an "advice" return to existing dialogue. I am pretty new at this, so I think I will try to write dialogue for a compliment or a mood.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by multimokia** [comment]
Reopening as this is in progress in the linked PR

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
