### ISSUE TITLE
Notifications but no messages?

### ISSUE THREAD

**Issue by CinnabunDreams** [Monika-After-Story/MonikaModDev#7403]
I keep hearing random piano chords every once in a while whenever I have the game closed which I assume are the notifications, but when I open the game Monika doesn't say anything and nothing happens?

**Comment by xXMidnight** [comment]
I've had the problem before. I'm guessing it's because you clicked out once a notification played.
Wait, the game was **closed?!**

**Comment by ThePotatoGuy** [comment]
do you have window reacts on? those will also trigger notifications depending on what you are doing.

**Comment by CinnabunDreams** [comment]
> I've had the problem before. I'm guessing it's because you clicked out once a notification played.
> Wait, the game was **closed?!**

Closed as in tabbed out-- But I didn't click out so I'm confused :(

**Comment by CinnabunDreams** [comment]
> do you have window reacts on? those will also trigger notifications depending on what you are doing.

I do have window reacts on, but what are the notifications for if nothing happens? She doesn't say anything or do anything even if I'm using something she can react to like Youtube or something

**Comment by ThePotatoGuy** [comment]
notifications should only be for her talking about something or a window react at this time. are you using any submods?

**Comment by CinnabunDreams** [comment]
> notifications should only be for her talking about something or a window react at this time. are you using any submods?

I wasn't using any when I posted this, but I just started using some recently like outfit reactions for some sprites I downloaded

**Comment by Booplicate** [comment]
You may need to enable/configure notifications in your system settings.

**Comment by CinnabunDreams** [comment]
> You may need to enable/configure notifications in your system settings.

Got it, just did that-- Hopefully it works now

**Comment by dreamscached** [comment]
Closing as resolved as there was no further feedback.
