### ISSUE TITLE
[Suggestion] Don't we miss Monika when we're apart?

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7404]
Sometimes "I'm always thinking about you!" doesn't convey the same feelings as "I missed you while we were apart!". Could something like this be added?

**Comment by xXMidnight** [comment]
Yes, by selecting the script-compliments.rpy and opening it and editing it in. You can also input the reaction while you're there :D although I'm not sure how it works because all of my files are .rpyc files. I'm still complaining.

**Comment by Booplicate** [comment]
Editing source files just to add something for yourself is a bad idea. You
- will have to update and overwrite that file every mod update
- won't be able to use in-game updater with source files

**Comment by username11421** [comment]
See, the compliments menu is probably not where I'd put it. If this is something that appears (say, for one hour before being disabled again) on returning from an absence, I'd probably want it to appear on the main menu. I believe that Monika in a broken state has the "I love you" main menu option disabled, so I would probably base it on how that works and then add this function in the farewells.rpy file.

>although I'm not sure how it works because all of my files are .rpyc 

My understanding is that .rpyc files are just the compiled .rpy files. If you have .rpy files in your game folder, Monika will actually notice and offer to delete them. Anyway, the DDLC mods subreddit indicates that these automatically compile when you run the game application; I haven't tested that though.

**Comment by username11421** [comment]
> Editing source files just to add something for yourself is a bad idea. You
> 
> * will have to update and overwrite that file every mod update
> * won't be able to use in-game updater with source files

Would a submod still cause these issues?

**Comment by Booplicate** [comment]
> See, the compliments menu is probably not where I'd put it. If this is something that appears (say, for one hour before being disabled again) on returning from an absence, I'd probably want it to appear on the main menu.

Iirc compliments support the `conditional` property. Which might be useful here. Or just run a callback when returning home to unlock the compliment. And then run another after an hour. We do not have any plans on expanding the talk menu, there's already too many options.

> Would a submod still cause these issues?

No, we even have a small API for submods. If it is made properly, you won't get any of those issues. Although, if you think of implementing it yourself as a submod, why not contribute it officially so other people can use it too?

**Comment by username11421** [comment]
>No, we even have a small API for submods. If it is made properly, you won't get any of those issues. Although, if you think of implementing it yourself as a submod, why not contribute it officially so other people can use it too?

Contribute the submod officially (where?), or don't make it as a submod in the first place and make a pull request in this repo, with your suggested implementation? I haven't contributed to any github projects before.

**Comment by Booplicate** [comment]
If you decide to contribute it, then you don't need to make it a submod. You'd probably add it as a new compliment or topic. You can start your contribution from reading [our guidelines](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines). These're a bit old, I'd add to also install Visual Studio Code and GitHub Desktop (unless you already have them or alternatives).

**Comment by username11421** [comment]
Thank you Booplicate for the advice on getting started. I will look into this possibility.

**Comment by xXMidnight** [comment]
> Editing source files just to add something for yourself is a bad idea. You
> 
> * will have to update and overwrite that file every mod update
> * won't be able to use in-game updater with source files

...which is why I really wanna edit the script-windowreacts.rpyc by adding something but I can't ;-;

**Comment by username11421** [comment]
xXMidnight, that's because you can't edit the .rpyc files. Those are the compiled .rpy files. You'll have to edit the .rpy file itself. If you download the .rpy file (from this repo) in your game directory, it will automatically compile into the .rpyc and overwrite the existing one when you launch the game. Be really careful doing that, though. Booplicate outlined some serious problems with modifying the existing code:

>Editing source files just to add something for yourself is a bad idea. You
>- will have to update and overwrite that file every mod update
>- won't be able to use in-game updater with source files

**Comment by xXMidnight** [comment]
> Editing source files just to add something for yourself is a bad idea. You
> 
> * will have to update and overwrite that file every mod update
> * won't be able to use in-game updater with source files

true, true, lemme delete that

**Comment by username11421** [comment]
I've submitted a PR for adding this feature.

**Comment by ThePotatoGuy** [comment]
leaving open as in progress

**Comment by username11421** [comment]
Had to move this PR to https://github.com/Monika-After-Story/MonikaModDev/pull/7577 as I messed up somethings in my forked repository.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
