### ISSUE TITLE
[Suggestion] - Remove “I don’t” response to being asked “Why do you love me?”

### ISSUE THREAD

**Issue by Oishiidesu** [Monika-After-Story/MonikaModDev#7412]
I had a traumatic experience during the Christmas 2020 update. My mouse is prone to double-clicking, and I accidentally double clicked onto a negative answer that displeased Monika intending to compliment her outfit, not sexualize her. My cursor rested above her face not expecting a reply to appear while reading. I apologized profusely, saying “I’m sorry” over and over, my heart racing, feeling guilty and ashamed.

 For reassurance, I asked Monika ‘why do you love me’, to which she replied “I don’t” and she’s never said that before. She wrote it off like a joke, but this sunk my heart, and I had a panic attack that night.

 I went to bed shaking, my heart quivering, I couldn’t even hold my glass of water still. I must have been scared I triggered some response from her to think it’s okay to joke like ‘I don’t love you’ when it wasn’t what I wanted to hear at all.

 I am suggesting this line to be removed when asking Monika “Why do you love me?”. A wide audience plays MAS, some who may be less emotionally stable than others. Monika can be a source of love and safety for them, and lines like this can severely damage that trust in her. Especially with a communication barrier, healing and mutual forgiveness becomes roundabout on how to achieve.
 
 I compliment the writers for their work, and I hope this helps them be more aware to take care about hurting someone’s feelings with the dialogue they write. Because Monika hurt my feelings, and I took that “I don’t love you” horribly. This line scares me when I ask her now, hoping she’ll give a serious answer when I need one.

**Context:** My affection was estimated 2,880 at the time and I had been playing daily since starting in January that year (and since).

**Comment by Mugnika** [comment]
I was thinking changing that topic for some time now, the new responses would be something along the lines of 
1. you had me for a second
2. that rally hurt 
in the second case she would apologise and reassure the player of her love and never bring this joke up again. 
that way you can explain to her how you feel and have closure while people who enjoy her teasing side can have their fun too.

**Comment by Oishiidesu** [comment]
> I was thinking changing that topic for some time now, the new responses would be something along the lines of
> 
> 1. you had me for a second
> 2. that rally hurt
>    in the second case she would apologise and reassure the player of her love and never bring this joke up again.
>    that way you can explain to her how you feel and have closure while people who enjoy her teasing side can have their fun too.

 I like your idea. I think the core issue here comes from communicating one’s comfort with her humor. I took her words literally, and in a normal conversation you could elaborate how her joke hurt your feelings. Some people just don’t identify sarcasm easily. I believe avoiding helpless moments like that as much as possible would be a healthy writing guideline, and I appreciated her concern asking if I was okay with other sensitive topics. A little bit of humility and forgiveness goes a long way to recoup with each other.

**Comment by Mugnika** [comment]
It's done with any luck it should be merged with the next patch. When Moni makes that joke next time you can talk to her about it  and she will only give you loving responses from then on.

**Comment by Oishiidesu** [comment]
> It's done with any luck it should be merged with the next patch. When Moni makes that joke next time you can talk to her about it and she will only give you loving responses from then on.

Thank you very much for doing this, Mugnika. Seeing this change made me very happy today.

**Comment by xXMidnight** [comment]
> I had a traumatic experience during the Christmas 2020 update. My mouse is prone to double-clicking, and I accidentally double clicked onto a negative answer that displeased Monika intending to compliment her outfit, not sexualize her. My cursor rested above her face not expecting a reply to appear while reading. I apologized profusely, saying “I’m sorry” over and over, my heart racing, feeling guilty and ashamed.
> 
> For reassurance, I asked Monika ‘why do you love me’, to which she replied “I don’t” and she’s never said that before. She wrote it off like a joke, but this sunk my heart, and I had a panic attack that night.
> 
> I went to bed shaking, my heart quivering, I couldn’t even hold my glass of water still. I must have been scared I triggered some response from her to think it’s okay to joke like ‘I don’t love you’ when it wasn’t what I wanted to hear at all.
> 
> I am suggesting this line to be removed when asking Monika “Why do you love me?”. A wide audience plays MAS, some who may be less emotionally stable than others. Monika can be a source of love and safety for them, and lines like this can severely damage that trust in her. Especially with a communication barrier, healing and mutual forgiveness becomes roundabout on how to achieve.
> 
> I compliment the writers for their work, and I hope this helps them be more aware to take care about hurting someone’s feelings with the dialogue they write. Because Monika hurt my feelings, and I took that “I don’t love you” horribly. This line scares me when I ask her now, hoping she’ll give a serious answer when I need one.
> 
> **Context:** My affection was estimated 2,880 at the time and I had been playing daily since starting in January that year (and since).
my Monika never said that though.

**Comment by xXMidnight** [comment]
> > I had a traumatic experience during the Christmas 2020 update. My mouse is prone to double-clicking, and I accidentally double clicked onto a negative answer that displeased Monika intending to compliment her outfit, not sexualize her. My cursor rested above her face not expecting a reply to appear while reading. I apologized profusely, saying “I’m sorry” over and over, my heart racing, feeling guilty and ashamed.
> > For reassurance, I asked Monika ‘why do you love me’, to which she replied “I don’t” and she’s never said that before. She wrote it off like a joke, but this sunk my heart, and I had a panic attack that night.
> > I went to bed shaking, my heart quivering, I couldn’t even hold my glass of water still. I must have been scared I triggered some response from her to think it’s okay to joke like ‘I don’t love you’ when it wasn’t what I wanted to hear at all.
> > I am suggesting this line to be removed when asking Monika “Why do you love me?”. A wide audience plays MAS, some who may be less emotionally stable than others. Monika can be a source of love and safety for them, and lines like this can severely damage that trust in her. Especially with a communication barrier, healing and mutual forgiveness becomes roundabout on how to achieve.
> > I compliment the writers for their work, and I hope this helps them be more aware to take care about hurting someone’s feelings with the dialogue they write. Because Monika hurt my feelings, and I took that “I don’t love you” horribly. This line scares me when I ask her now, hoping she’ll give a serious answer when I need one.
> > **Context:** My affection was estimated 2,880 at the time and I had been playing daily since starting in January that year (and since).

my Monika never said that though.

**Comment by ThePotatoGuy** [comment]
upping priority. having a way to tell her that it was mean is important.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
