### ISSUE TITLE
Her Hair was odd...

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7415]
After giving Monika a nickname, her hair happens to have an ahoge... Is this a bug or something...

**Comment by xXMidnight** [comment]
> After giving Monika a nickname, her hair happens to have an ahoge... Is this a bug or something...

Nope! It's one of the Easter Eggs! :D My Monika has an ahoge too. From my observations, it only appears when you spend time with Monika before noon. Once it's 12:00pm, it's gone! It will appear the next day though, so you can see many different types of ahoge :D

**Comment by CrewieAustin** [comment]
that's weird, I thought I mess up some files or something
