### ISSUE TITLE
Unable to use sprites.

### ISSUE THREAD

**Issue by Memory-Amnesiac** [Monika-After-Story/MonikaModDev#7416]
I downloaded them all correctly, or at least I believe I did. I pasted the mod-assets folder in the game folder and I pasted the gift folder into the character folder. Nothing worked so I went to the troubleshooting page about sprite objects, it said to check the spj.txt file in the log folder. My log folder is empty and the spj.txt file doesn't exist anywhere on my computer. What do I do?

**Comment by xXMidnight** [comment]
I just open the mod_assets' mod_assets file and paste everything according to where it is, then move on to the first mod_assets and do the same thing. You should be able to load the sprites by then.

**Comment by ThePotatoGuy** [comment]
follow the [troubleshooting guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
