### ISSUE TITLE
[Suggestion] Add DDLC-Plus! soundtracks to MAS!

### ISSUE THREAD

**Issue by supertsumu** [Monika-After-Story/MonikaModDev#7418]
Recently bought DDLC-Plus! and the OSTs are pretty damn good. Would like to jam to them with Monika in MAS.

**Comment by multimokia** [comment]
According to the IP Guidelines we can't as they didn't allow the OSTs to be used.

However you're more than free to download them from YouTube and add them in as custom music!

**Comment by Retrolovania** [comment]
If I recall correctly, Team Salvato has stated that DDLC mods cannot use any assets from Plus except for the background CGs. That would include the music.

However, you could add the tracks to your own personal install if you so wish. Don't think that violates anything.

**Comment by xXMidnight** [comment]
ig so

**Comment by ThePotatoGuy** [comment]
as multi said, we legally cannot do this with mod releases.

[closing as rejected]
