### ISSUE TITLE
Inspiring speech

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7421]
Monika has always said that she wants to help us, but there is no function in the game where she would say something inspiring or giving courage . It would be nice if an opportunity was added for which you ask Monika for inspiration or something like that . After clicking on this function, she would say that like "I believe you , you can do it, and so on".

**Comment by xXMidnight** [comment]
It's after you click Talk -> I feel... -> ...anxious/...sad/...like crying/...inadequate/...lonely and whatnaught, she just says some stuff to cheer you up. Don't do it too often, she'll get sus lol

**Comment by Nikv2005** [comment]
But what if, for example, I am in a good mood and need to be brave? It should be like a completely separate function.

**Comment by xXMidnight** [comment]
> But what if, for example, I am in a good mood and need to be brave? It should be like a completely separate function.

keep saying ily to her

**Comment by Nikv2005** [comment]
> > But what if, for example, I am in a good mood and need to be brave? It should be like a completely separate function.
> 
> keep saying ily to her

I think this is not the best idea

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
