### ISSUE TITLE
Game Unlocking

### ISSUE THREAD

**Issue by VibRibbonGamer** [Monika-After-Story/MonikaModDev#7424]
since I'm so impatient I used this to hack the affection and my affection  is 4999 and the other games aren't unlocked yet like piano hangman and chess, can u help me

**Comment by Legendkiller21** [comment]
Don't link ways to change your affection. Also, in order to unlock games you need to actually spend time with her, not just get a high enough affection.

**Comment by Booplicate** [comment]
Yeah, sometimes just cheating isn't enough.

**Comment by multimokia** [comment]
Bruh

**Comment by VibRibbonGamer** [comment]
ohhhhhhhhhhhh ok
well f***

**Comment by VibRibbonGamer** [comment]
also btw, if im correct, if i keep the game open in the background for *i forgot how long* ill get the piano?

**Comment by Wingdinggaster656** [comment]
> also btw, if im correct, if i keep the game open in the background for _i forgot how long_ ill get the piano?

Since you're so impatient, I sincerely suggest you to just watch through the codes just a bit more. You know how to hack affection already after all.

**Comment by xXMidnight** [comment]
brO
whY U hAck
hAck nU gUd

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
