### ISSUE TITLE
[Suggestion] Make a feature to be able to play higher or lower notes that the current piano will not allow

### ISSUE THREAD

**Issue by fortofawesome35** [Monika-After-Story/MonikaModDev#7425]
What it says in the title. There are many songs I would like to play on the MAS Piano (for example, Song of Healing from Majora's Mask and Saria's Song from Ocarina of Time) but unfortunately, due to the limited range of keys a QWERTY keyboard allows, there are notes in these songs that are higher or lower than the current piano allows. If there is a way to implement a sort of feature to where we can change the pitch of the keys to other piano notes so I am able to play these songs in full, that would be excellent. Thank you very much.

**Comment by xXMidnight** [comment]
:D this would be a very nice addition!

**Comment by ThePotatoGuy** [comment]
this has been sort of suggested before, but I'll keep it separate since the others arent' clear.

either way, expanding additional notes needs asset adjustments, and extra planning for keyboard mapping.

[closing until we look into it]
