### ISSUE TITLE
Separate Pronouns And Gender Topic

### ISSUE THREAD

**Issue by saltedgator** [Monika-After-Story/MonikaModDev#7426]
The option to change your pronouns doesn't make much sense, because when you ask, instead of choosing pronouns, you choose between "boy", "girl", etc. Pronouns are not synonymous with gender-- but if that isn't a valid enough reason, the segue from pronouns to gender choice is stilted and awkward. It's a little jarring when Monika asks about pronouns, and instead of choosing she/her/hers, I just say "I'm a girl". It comes across as mildly ignorant at worst-- not to mention, I think someone with such a good grasp on language as Monika would have something to say about that. I'm already making an LGBTQ+ based submod, but I thought that this issue was important enough to offer it up to the OG mod.

I would suggest just.... replacing the text within the choice boxes. "I'm a boy" can turn into "He/him/his", "I'm a girl" can turn into "she/her/hers", "Neither" can be "they/them/theirs", and Monika has mentioned using neopronouns in the past, so adding some options for that would be pretty beneficial as well.

(I realize that there is already an issue open about the transgender conversation being made different. I think this is a great choice. If that still is unresolved vis a vis dialogue, I'm more than happy to help.)

**Comment by MrVavlo** [comment]
... or just change the headline' name of that topic from "Could you call me by different pronouns?" to something else. 
And maybe separate the pronouns part to a different topic for all possible combinations.

That will be easier _and_ will not be confusing for those who aren't the part of LGBTQ+.

**Comment by saltedgator** [comment]
Yeah, I think making different topics for pronouns and gender identity is a good idea. Maybe if you choose a potential "other" option in the gender topic, it can lead to the pronoun choices as an extension. Just throwing ideas out there.

**Comment by xXMidnight** [comment]
Talk -> Hey, Monika... -> You -> Could you call me by different pronouns?

unless you're hetero

idk how to help if so

**Comment by ThePotatoGuy** [comment]
forward all discussion on this to #6084 

[closing as duplicate]
