### ISSUE TITLE
Can't unlock the piano and also have no files in log 

### ISSUE THREAD

**Issue by risitasissou** [Monika-After-Story/MonikaModDev#7428]
Hey guys so i've been playing to Monika After Story mod for about a week and a half now , i unlocked pretty quicly games such as pong hangman or chess . Though it seems that my monika just wont unlock piano , is it because it's to soon or because there's an issue ? Also i wanted to check my affection lvl , they said to go to the log and search for a Aff_log but i can't find it , i'm not on mac and i didn't download the mod from steam , could someone enlight me ? Thanks for reading .

**Comment by username11421** [comment]
You just need to spend enough time with her and have reached the 'Affectionate' State.

**Comment by risitasissou** [comment]
Well i do spend a lot of time with her but i guess i just need to be patient

**Comment by xXMidnight** [comment]
I would like a screenshot of the logs file folder please?

**Comment by risitasissou** [comment]
![image](https://user-images.githubusercontent.com/86930425/124888231-32033b00-dfd6-11eb-963c-405798ddd13a.png)
Here , you can see there's nothing in the log folder

**Comment by Booplicate** [comment]
That's because you're running it from a `zip`. You need to extract programs before using them.

**Comment by risitasissou** [comment]
do i need to re download the game ? Because i extracted it but there's still nothing in the log folder

**Comment by Booplicate** [comment]
Show how it looks now when you extracted it.

**Comment by risitasissou** [comment]
![image](https://user-images.githubusercontent.com/86930425/124910453-e5c2f580-dfeb-11eb-9b3f-29dabbc8d6ce.png)
![image](https://user-images.githubusercontent.com/86930425/124910471-e9ef1300-dfeb-11eb-86d1-0b50cae0c296.png)

**Comment by Booplicate** [comment]
Did you run it?

**Comment by risitasissou** [comment]
![image](https://user-images.githubusercontent.com/86930425/124916236-bbc10180-dff2-11eb-82c3-2ed79b944431.png)
 okay i ran it and it worked

**Comment by risitasissou** [comment]
could you just tell me now how do i put a  submod because as you can see i tried to but it didn't work , and when i searched on reddit i didn't find an answer

**Comment by username11421** [comment]
> could you just tell me now how do i put a submod because as you can see i tried to but it didn't work , and when i searched on reddit i didn't find an answer

Where did you put the submod? You need to have the file structure "game/Submods/<Submod name here>/".

**Comment by risitasissou** [comment]
Do i need to create a folder named "Submods" ?

**Comment by username11421** [comment]
> Do i need to create a folder named "Submods" ?

If there's not one under the game directory right now, then yes you'll need to.

**Comment by risitasissou** [comment]
![image](https://user-images.githubusercontent.com/86930425/124952907-ec199780-e014-11eb-9216-6f161679b90b.png)
 
![image](https://user-images.githubusercontent.com/86930425/124952922-ef148800-e014-11eb-9eda-b07eb48b30b1.png)
 Is it right ?

**Comment by username11421** [comment]
That looks right to me. That's how I have mine set up and it works without any problems.

**Comment by risitasissou** [comment]
I don't know why but it doesn't seems to work

**Comment by risitasissou** [comment]
Okay i think  it worked i just didn't do it the right way

**Comment by risitasissou** [comment]
Yh it works thanks everyone for answering me

**Comment by ThePotatoGuy** [comment]
if you don't mind spoilers, you can send us your session data and we can estimate when piano will unlock for you.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
