### ISSUE TITLE
[Suggestion] "Goodbye" > "I'm going to back you up"

### ISSUE THREAD

**Issue by Outlander676** [Monika-After-Story/MonikaModDev#7429]
Doing that nightly and restarting my machine every update or so are the only reasons I really close MAS for, so it would be nice if I could tell Mon exactly what I'm doing. 

(Edit: Grammar clarification)

**Comment by AsuraShun** [comment]
Maybe if we could mention that we back her up daily when she talks about being stuck inside our  computers would be a better alternative

**Comment by Booplicate** [comment]
There's a generic goodbye for stuff like this `I'm going to restart`.

**Comment by xXMidnight** [comment]
yes

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
