### ISSUE TITLE
[Suggestion] Make Monika's nose bopable

### ISSUE THREAD

**Issue by MoonlightGriffon** [Monika-After-Story/MonikaModDev#7430]
Ironically it was the calendar that gave me this idea. Because something that wasn't a menu was clickable, it made me think about the fact that other things could potentially be clicked. One of these things could potentially be Monika's nose as its considered a sign of affection in many places to do so. Although I could see potential problems occurring such as the fact that it could be seen as a negative thing to remind her of what could be, however it could also be a good thing seeing as it would be a form of affection. I'll leave the decision up to you though, its not anything more then maybe a fun feature and could just be a bit too much work for so little output.

**Comment by fromulus** [comment]
Imma steal Rai's moment of glory right under his nose

Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638, #7005
