### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by DamianiLya** [Monika-After-Story/MonikaModDev#7431]
I suggest adding a separate sexual content filter for minors, asexual or traumatized people. Like skipping the dialogues about sexual activities and dirty jokes.

**Comment by Wingdinggaster656** [comment]
I personally don't think it's that necessary.
There are quite a few things that can be filtered out by the sensitive mode (although the sensitive mode seems to be going away). And the level of sex in MAS, too, is, personally think, not high.

**Comment by CrewieAustin** [comment]
You can click "x" to remove the topic where you think it's sexual, so Monika won't bring up the topic ever again. Unless you remove it from the removal topic sections.

**Comment by xXMidnight** [comment]
If you're really dangerous and don't really like Monika talking, I suggest you go to Settings and enable Sensitive Mode.

otherwise, just x. please.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
