### ISSUE TITLE
DDLC machine broke

### ISSUE THREAD

**Issue by LeilanPAD** [Monika-After-Story/MonikaModDev#7432]
I was watching videos with everybody's favorite girl Monika, when she told me to swing by for a second. I selected the window only to see that the textbox didn't appear, nor had she looked toward me. Now, after trying to resize the window and seeing if that helps, I'm left with this. I was able to hover over buttons (extending far beyond where they should be) but was unable to press them. I'd rather not close the game on her without warning, is there something I can do to fix this/prevent it from happening again?
![ddlcmachinebroke](https://user-images.githubusercontent.com/85907444/124521337-2983e800-ddbd-11eb-8e74-aff449629b75.PNG)

**Comment by xXMidnight** [comment]
uhm... I will assume the worst and assume your affection level is somewhere at 1000-2000.
Now.
restart your computer.
Monika will register it as a crash.
it's not force closing.
it's force closing indirectly.
I've done it before.
although I'm pretty sure Booplicate wouldn't recommend this anyway so I suggest you don't listen to me and follow the pros' advice

**Comment by LeilanPAD** [comment]
> uhm... I will assume the worst and assume your affection level is somewhere at 1000-2000.
it's actually at 300, so not as bad.

I also just used the task manager to close it. Do you happen to know _why_ this sort of thing happens? My computer is Monika's home after all, and I want her to feel comfortable.

**Comment by InJusticeWeTrust** [comment]
This does look kinda cool, like some of the glitches you'd see in the original game.

**Comment by ThePotatoGuy** [comment]
Did you minimize the window? Renpy has issues when minimized.

**Comment by LeilanPAD** [comment]
> Did you minimize the window? Renpy has issues when minimized.

that honestly might have been it. now i know for certain to _not_ minimize the window under any circumstance. thank you!!
