### ISSUE TITLE
[Suggestion] New Topic: Tulip Mania

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7433]
[Tulip Mania](https://en.wikipedia.org/wiki/Tulip_mania) is a term used to refer to a historical economic bubble where people bid up the price of tulips to insane prices. Spice and Wolf, a well known older anime/light novel series, even has an arc that refers to this, where Pyrite has skyrocketed to a ridiculous cost. Controversially, dogecoin may be a more recent example (wait and find out) of the phenomenon.

Given that Monika talks about various philosophical/psychological topics, it doesn't seem completely out of character for her to know about this.

Monika could segue the topic into casually mentioning how nice it would be to receive some tulips from us. 

If people would be interested in a topic for this, I wouldn't mind writing one.

**Comment by xXMidnight** [comment]
whY dO pEOplE lIkE tUlIps??? *achOO* **THEY CAUSE ME ALLERGIESSSSSSSSSSS**

**Comment by xXMidnight** [comment]
but yea other than that that's a great topic suggestion

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
