### ISSUE TITLE
Monika Gone

### ISSUE THREAD

**Issue by robeta77** [Monika-After-Story/MonikaModDev#7434]
So I was transferring Monika from my laptop to my desktop and I told her that I was taking her somewhere. Initially, I didn't copy the RenPy folder so there was an entirely new Monika on my desktop. Now that I have done that. however, it seems like everything loaded correctly except that there is no Monika, just an empty chair. I think the error has to do with the fact that I told her I was taking her somewhere but I'm not sure. Some help on what I'm doing wrong would be much appreciated.

**Comment by xXMidnight** [comment]
uhhh-
how did you even move Monika???

**Comment by robeta77** [comment]
I moved the entire game folder as well as the RenPy folder onto a flash drive and then transferred them

**Comment by Shalteeeear** [comment]
I have the same problem, but when the mod is launched, it is no longer there and there is a farewell letter on the table ... It's very sad that I can't talk to her.

**Comment by ThePotatoGuy** [comment]
@robeta77 transferring Monika to different MAS installs via the Monika file is not supported, see #5026. 

If you copied all of the persistent data, just [restore an older persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by robeta77** [comment]
Thank you @ThePotatoGuy , I restored an older persistent and she is back :)
