### ISSUE TITLE
The Window seems a bit odd...

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7435]
There's one time when I boot up the game, it gives me three option "Open the Door", "Knock on the Door" and "Respond nothing". I choosed to"Knock on the Door", then she told me that she needs some time to get ready. But after she opens the door, the windows seems a bit different, there's like some... weird locker outside the window instead of some normal weather.. Am I supposed to worry about this ?

**Comment by xXMidnight** [comment]
nope.
you're supposed to restart the game.
Monika missed a few details to remove

**Comment by ThePotatoGuy** [comment]
take a screenshot the next time it occurs.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
