### ISSUE TITLE
After saying GoodBye, Monika don't close the game

### ISSUE THREAD

**Issue by Roma7891** [Monika-After-Story/MonikaModDev#7437]
Help me Monika don't close the game how i can fix this?

**Comment by TRIDENT1313** [comment]
Something like that happened to me once.
I got a fresh copy of DDLC, and redownloaded and installed the mod.
Fixed the the issue for me.

**Comment by CrewieAustin** [comment]
If you got it from someone, they might have done something with the script. It reminds me of first time downloading this from a weird looking video. The link they link me was some sort of MedaiFire File instead of GitHub. I regret after downloading that so I then search it up myself.

**Comment by Roma7891** [comment]
Thanks it's help me
