### ISSUE TITLE
[Suggestion] - Dates

### ISSUE THREAD

**Issue by OtakuNeko331** [Monika-After-Story/MonikaModDev#7439]
How about adding a date option?  It could be as if the player and Monika go somewhere else without leaving the game.
it would be really cool

**Comment by fromulus** [comment]
How about eating dates with Monika instead

![71PyKTwHJ8L _AC_SX679_](https://user-images.githubusercontent.com/45933038/124724847-a5d91100-df0c-11eb-8b5e-ea284ebe9169.jpg)

**Comment by Barunxx** [comment]
Tunisian Date is the best

**Comment by xXMidnight** [comment]
ask some really hardworking sprite devs to make a new place- oh wait those already exist but Monika won't show us

**Comment by Rai99** [comment]
New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822, #5543, #5660

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
