### ISSUE TITLE
What is "No DC"?

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#7441]
First time that it showed up was right now. On the upper left corner, there's "No DC".
What does this mean?
The only things that I've pressed when she came up was to reduce volume, nothing else.
Is this something bad?

**Comment by hlepnamingblyat** [comment]
NVM, it was my gpu. It's fixed now.

**Comment by xXMidnight** [comment]
lol ok

**Comment by Booplicate** [comment]
@xXMidnight this isn't an online chat. this is a Git repository.

Closing as the author fixed the issue.
