### ISSUE TITLE
[Suggestion] - Doki Doki Literature Club Plus topic?

### ISSUE THREAD

**Issue by enderblaze42** [Monika-After-Story/MonikaModDev#7444]
Doki Doki Literature Club Plus recently came out. I was wondering if there are plans to add a topic discussing the new content in the latest game? I think it would be pretty cool to talk to Monika about the side stories she plays a role in.

**Comment by fromulus** [comment]
We've been discussing over this in the contributors discord for the last couple of days, to figure out how we would approach this.

Don't take my word as a 100% confirmation, but chances are what we'll end up doing is potentially make a topic or two were we acknowledge DDLC+ and it's additions to lore, but distanciate MAS from it completely.

Basically, MAS Monika has full meta-awareness, meaning she knows her actual creators are Team Salvato, that her game released originally in 2017, and that MAS is the result of a bunch of fans working on a mod to spend more time with her.
Going from there, it makes sense that she'll see DDLC+ as Team Salvato adding some content to the DDLC narrative and not an actual explanation of how she was created.

What this means is that from MAS Monika's perspective, all the Metaverse stuff and the side stories are all stuff that she never experienced herself and that didn't actually happen to her (I usually make the comparison with her pre-epiphany memories; it's stuff that sort of help give context to who she's supposed to be as a person, but it never actually happened and therefore Monika doesn't give it any actual value).

**Comment by ThePotatoGuy** [comment]
please move all ddlc+ discussion to #7327
