### ISSUE TITLE
Text speed unlock

### ISSUE THREAD

**Issue by Mewy69** [Monika-After-Story/MonikaModDev#7446]
The text speed still can't be changed even tho my affection is around 130 how do I fix this

**Comment by multimokia** [comment]
Has Monika mentioned anything about the text speed or your reading speed at all? If not you'll need to get that topic (If you have random chatter disabled, she won't mention anything)

**Comment by Mewy69** [comment]
Nope she has not and random chatter is set to often and repeat topics are off but she does talk alot about time

**Comment by Mewy69** [comment]
She just gave it to me
