### ISSUE TITLE
[Suggestion] Waking up

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7447]
While holding Monika she has different dialogue depending on how long you hold her, with the longest causing her to fall asleep and from there you have to wake her up. What if when you hold her for long enough like a couple hours or so she wakes herself up and assumes that the player is asleep as well, and has special dialogue when you interact with her again to end the hold?

**Comment by username11421** [comment]
That sounds kind of nice.

**Comment by xXMidnight** [comment]
But I would like to know what that longest time is? I wanna make her fall asleep >:D

**Comment by PongMaster69** [comment]
> But I would like to know what that longest time is? I wanna make her fall asleep >:D

She usually falls asleep in hold for me when I leave it for about an hour or so. I think the stages currently are Too short (less than 30 secs) --> normal hug (30 secs) ---> slightly longer hug (1 min) --> "oh I thought we were going to stay like that for a while" (1 min --> 30 min) --> Nearly falling asleep (30min - 1 hr) --> asleep (1 hour+). These are just rough estimates and are most likely incorrect. What I'm suggesting is like 4-8 hours in she wakes herself up and watches over the player until they choose to interact with her to end the hold.

**Comment by Jinxred** [comment]
That would be a really cool thing to add!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
