### ISSUE TITLE
[Suggestion] Adjust "monika_why" topic so we can tell her where we found out about her/DDLC

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7448]
It would be nice to tell Monika where we heard about her or the game DDLC when she brings up this topic. Some possible sources might include "Social Media", "Video Websites", "Fanart Forums", "From a Friend", "By Chance", "Steam", "Reviews", etc.

Alternatively, a second topic could unlock after this one has been seen where she asks this.

**Comment by Booplicate** [comment]
That sounds like a question from a survey you can see on websites `How did you hear about us?`.

**Comment by xXMidnight** [comment]
wut

**Comment by username11421** [comment]
> That sounds like a question from a survey you can see on websites `How did you hear about us?`.

You're right, it kind of does. She does say she's curious why we played DDLC and she assumes we were lonely, might be nice to give a more thorough response to her question though.

**Comment by ThePotatoGuy** [comment]
the options are bit like a survey if we just presented them all up front, but maybe we could find a way to make it smoother so it doesn't seem so.

[closing until we look into it]
