### ISSUE TITLE
[Suggestion] Add a option where you can tell Monika where your eyes has 2 colors on both of em

### ISSUE THREAD

**Issue by Mewy69** [Monika-After-Story/MonikaModDev#7449]
Please

**Comment by xXMidnight** [comment]
It's already there. It's heterochromia, and it's already an item on the list when she asks you about your looks

**Comment by Mewy69** [comment]
Yes but she only allows you to state one eye is this color and the other eye is this color not both eyes are these colors

**Comment by zwartkop2** [comment]
So you mean [central heterochromia](http://www.actforlibraries.org/central-heterochromia/)?

**Comment by Mewy69** [comment]
Yes

**Comment by xXMidnight** [comment]
ohh... yea idk how

**Comment by Mewy69** [comment]
Yes
