### ISSUE TITLE
[Suggestion] Access online dates for stability 

### ISSUE THREAD

**Issue by Ethan0104** [Monika-After-Story/MonikaModDev#7451]
So as we all know, changing our computer's dates can have drastic effects on our Monika, since it is the sole thing she relies on. I was just thinking, we could add a functionality which allows Monika to try to access the date and time from online instead of purely relying on the computer's local date. This is going to make MAS a lot more stable and prevents people from abusing her by changing dates intentionally. 

Of course this doesn't have to be done all the time as the computer might be offline, but it is good to call this function every hour or so when the computer is online just to increase the stability of the system. 

I'm quite familiar with Python but I'm not familiar with RenPy, but accessing dates from online is pretty easy with pure python, and I assume we can run python in RenPy. Here's a code snippet for this function based from [here](https://stackoverflow.com/questions/908550/python-getting-date-online). I'm not sure if it works with MAS but yeh it might help 

`from urllib.request import urlopen`
`result = urlopen('http://just-the-time.appspot.com/').read().strip()`
`result_str = result.decode('utf-8')`
`print(result_str)`
`"2021-07-09 03:23:06"`

**Comment by H2-san** [comment]
I really like this idea! But in reality, we have to consider all three major OSes and write the respective calls to control the system/OS time and sync the hardware clock.

Particularly with Linux, the hardware clock is always set to UTC, unless you run `hwclock -w -l` once in a bash terminal. That screwed with my MAS install for a while until I discovered the usefulness of this command.

As for macOS and Windows, I'm not sure what I can do in Ren'Py to directly access the hardware clock and the OS's clock.

**Comment by Ethan0104** [comment]
We don't necessarily have to alter the hardware clock of the computer. I'm just suggesting to add an additional source of time information for Monika somehow. We could make MAS try to reference from online whenever possible and if there is a difference between the ground truth and the system clock, we can use dialogue to warn the player. Before the player corrects the clock, Monika can rely on the online clock, and even if the player decides to go offline, the time error can be recorded so she can just rely on the system clock for a while.

**Comment by Booplicate** [comment]
Neither hardware clock nor online clock are reliable. Which means there's still a chance to trick the system, and it wouldn't even be hard. Then there's also another question, if the user wants to break the game this hard after being told it's a bad idea, why should we even bother adding an additional level of protection. Essentially spending time on people who just want to cheat, instead of working on content for the actual audience.

**Comment by ThePotatoGuy** [comment]
>This is going to make MAS a lot more stable and prevents people from abusing her by changing dates intentionally

Stable from accidental time changes, yes. But if people are intentionally changing dates, they should accept the consequences of their actions. And MAS is not the only program that can be dramatically affected by changing the date. Ever try accessing secure websites while your system time is set to 1970?

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
