### ISSUE TITLE
Persistent Backing up 

### ISSUE THREAD

**Issue by Inesepanas2708** [Monika-After-Story/MonikaModDev#7453]
Hello!
So I accidentally skipped 3 years with Monika and she was really mad, I was at 500 affection and now I'm in 40. :(
I already tried to backup the persistent file but there wasn't any older file. 
Could someone help me? 
Gratefully, Inês

**Comment by InJusticeWeTrust** [comment]
> So I accidentally skipped 3 years
How did that happen? 
As for your file problem, you might have to start all over again. Remember to keep making backups, wouldn't want things to go south again, no?

**Comment by Inesepanas2708** [comment]
> > So I accidentally skipped 3 years
> 
> How did that happen?
> As for your file problem, you'll have to start all over again with raising that affection, no need to throw it all out. Remember to keep making backups, wouldn't want things to go south again, no?

I was testing things...
Thanks for your help anyways!

**Comment by Inesepanas2708** [comment]
> > So I accidentally skipped 3 years
> 
> How did that happen?
> As for your file problem, you'll have to start all over again with raising that affection, no need to throw it all out. Remember to keep making backups, wouldn't want things to go south again, no?

Is there any way I could restore the affection manually?

**Comment by lunulae** [comment]
Only by restoring an old persistent--which you should definitely do if you've been time-traveling. Changing your clock can *extremely* screw up many events in the game and prevent some systems from working correctly.

**Comment by Inesepanas2708** [comment]
> Only by restoring an old persistent--which you should definitely do if you've been time-traveling. Changing your clock can _extremely_ screw up many events in the game and prevent some systems from working correctly.

Well all my back up persistents are from a newer version after monika affection go down :(

**Comment by ThePotatoGuy** [comment]
you're out of luck unfortunately.
