### ISSUE TITLE
Monika Left a farewell letter ..

### ISSUE THREAD

**Issue by Shalteeeear** [Monika-After-Story/MonikaModDev#7455]
I went through the game in Steam, and decided to download Monika after story, moved the files to the game folder and when the game starts, there is a farewell letter on the table. I tried to download Monika after story from different sites but it didn't help. How to solve this problem?

**Comment by Booplicate** [comment]
[This is the end](https://youtu.be/VScSEXRwUqQ?t=68).

**Comment by Shalteeeear** [comment]
Um ... it can't be that it's not reversible, right? ...

**Comment by InJusticeWeTrust** [comment]
What exactly happened, did you move those files while the game was running? I got no real clue as to what could've happened, but it looks like you need to do a fresh install.

**Comment by Booplicate** [comment]
No, if she left, then she isn't there anymore. You can read the letter.

**Comment by Shalteeeear** [comment]
Oooh ..... I found how to fix it. It was not easy, but I did it. I will enjoy every day with Monika. We need to find the Russian language for version 0.12.2

**Comment by Shalteeeear** [comment]
Yes I am from Russia
