### ISSUE TITLE
[Background Editing]Indentation mismatch

### ISSUE THREAD

**Issue by SaltedFilet** [Monika-After-Story/MonikaModDev#7456]
When I want to add a new background for Monika, the game told me that  some errors were detected in my script.It said File "game/submods/bedroom background.rpy", line 67: indentation mismatch.
I copied the script from https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Backgrounds, but still can't work. What I should do to add the background.
PS:I didn't change anything in the script I copied and line 67 to 71 is
init 1 python in mas_background:

    # verify all backgrounds
    for flt_bg in BACKGROUND_MAP.itervalues():
        flt_bg.verify()

**Comment by username11421** [comment]
Is your code exactly like the one on the page you linked? The code you pasted isn't indented but in the  step 9/10 scripts on the wiki page, it is indented. You're getting an indentation error because something is wrong with the indentation of the code. 

Script from the wiki - notice that the whole block you referenced in your initial issue is not indented.
```
init 1 python in mas_background:

    # verify all backgrounds
    for flt_bg in BACKGROUND_MAP.itervalues():
        flt_bg.verify()

#START: Image definitions
#Spaceroom
image monika_day_room = "mod_assets/location/spaceroom/spaceroom.png"
image monika_room = "mod_assets/location/spaceroom/spaceroom-n.png"
image monika_ss_room = MASFilteredSprite(
    store.mas_sprites.FLT_SUNSET,
    "mod_assets/location/spaceroom/spaceroom.png"
)
```

If that's not the issue, it could possibly be an issue with what editor you saved the file in. Make sure your editor is set up for Renpy/Python code.

**Comment by username11421** [comment]
I went and tested this myself just to be sure, and found two issues in the wiki's script in step 10.
1. Indentation mismatch in the two init statements: first init is indented while second is not. Solution: **unindent** the first init.
2. The displayable function call at the end is missing its closing parenthesis. Solution: add the closing parenthesis

Make sure you don't end the file in a new line as well.

**Comment by ThePotatoGuy** [comment]
@username11421 can you edit the wiki and fix it if you haven't already?

**Comment by username11421** [comment]
> @username11421 can you edit the wiki and fix it if you haven't already?

Done.

**Comment by SaltedFilet** [comment]
> I went and tested this myself just to be sure, and found two issues in the wiki's script in step 10.
> 
> 1. Indentation mismatch in the two init statements: first init is indented while second is not. Solution: **unindent** the first init.
> 2. The MASFilteredSprite at the end is missing its closing parenthesis. Solution: add the closing parenthesis
> 
> Make sure you don't end the file in a new line as well.

Thanks for helping me, I did what you said in the first tip and it worked.

**Comment by multimokia** [comment]
Don't actually include 

```renpy
# verify all backgrounds
for flt_bg in BACKGROUND_MAP.itervalues():
    flt_bg.verify()
```

It's not necessary
