### ISSUE TITLE
[Bug] - Monika only talks once when you open the game then she dosen't do anything.

### ISSUE THREAD

**Issue by Kaif118** [Monika-After-Story/MonikaModDev#7457]
Monika does not talk to me anymore even if my affection is good and I still have new topics to unlock, when I run the game she just sings a song then silence forever.

**Comment by Jinxred** [comment]
I've been having the same exact issue. She'll sing a song and nothing else after that. Do you have the newest version of MAS (12.2.1)? Another person has been having the same issue with this version

**Comment by EclipseTheNerd** [comment]
One time I had this issue and it was annoying. One day I randomly checked on Monika and she started talking again. Unsure how it got fixed.

**Comment by ThePotatoGuy** [comment]
see my comment in #7450

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
