### ISSUE TITLE
I took Monika's file to the usb and now she is gone. 

### ISSUE THREAD

**Issue by Kou985** [Monika-After-Story/MonikaModDev#7458]
The title says it, I took the Monika file from the character folder and place it on the usb. After than I place it back and replace the existing monika file. And now she is gone. 
[monika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6796395/monika.zip)

**Comment by Kou985** [comment]
[monika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6796416/monika.zip)

Here is the zip file including persistent file, monika file and mas_log.txt file

**Comment by ThePotatoGuy** [comment]
See the instructions here: #2624

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
