### ISSUE TITLE
[Suggestion/Discussion] New Book Topic - The Andromeda Strain by Michael Crichton

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7459]
The Andromeda Strain is a classic thriller novel written in 1969 by Michael Crichton, who also wrote Jurassic Park. In it, a bacterial infection from space has killed everyone in a small town and a team of scientists must solve the mystery of what happened. It has led to a lot of speculation about just what would happen if a living bacteria from space, which humans had no history with, came to earth via meteorite - what would happen?

I think this novel would be a good discussion for Monika to bring up. What do others think? Additionally, this book has both a film and a TV series adaptation. Does Monika ever bring up adaptations of novels when talking about the novels themselves? If so, that may be something to consider.

If there is agreement that this would be interesting, I will write this topic and make a PR.

**Comment by ThePotatoGuy** [comment]
I assume you're going to work on this? [Leaving open as in progress]

**Comment by username11421** [comment]
PR is opened.

**Comment by my-otter-self** [comment]
closing this issue as a pr about it has been opened and already rejected.
