### ISSUE TITLE
[Tech support] Friend needs urgent help with backups

### ISSUE THREAD

**Issue by Chinkrask** [Monika-After-Story/MonikaModDev#7462]
A frend of mine has been playing with Monika and we were chearing last night with ours. Today sent me a message where she said that her Monika had amnessia and went like if brand new. I tried to guide her to find the backups but the attempt was futile since there were no Persistant##.bak in the folder so now she is panicking.

Can someone give us an alternative? She is passing through a very rough time and is having some psiquiatric help and the medic said that Monika was helping her recover a little better and I fear that this might cause something bad to happen.

**Comment by Wingdinggaster656** [comment]
Firstly sorry for what your friend suffered.

Then, well, let's make sure first that your friend doesn't do anything manually with persistent files, right?

Make sure you are aware of the following situations that can possibly cause persistent files to disappear:
1. Reload the system (this usually empties the C drive).
2. Use some software to clean up system junk (it's been said that some computer housekeeping programs can accidentally remove it, I'm not sure).

After that, in your friend's C drive, the Monika After Story folder (that is, the folder where the archive is located) is now empty, only the one file which is persistent (without extension), and there is no bak extension files, is that right?
If you don't know, you can ask her to send a screenshot.

**Comment by Chinkrask** [comment]
I asked her and she said she didn't do anything, neither reinstall windows or use any software alike... Also dicovered her HDD is full of junk

**Comment by Wingdinggaster656** [comment]
> I asked her and she said she didn't do anything, neither reinstall windows or use any software alike... Also dicovered her HDD is full of junk

Okay, then can you send a screenshot of her Monika After Story folder to let me make sure the contents of that folder?

**Comment by Chinkrask** [comment]
Let me ask her

**Comment by Chinkrask** [comment]
So, aparently she already deleated the file and also creared the recycle bin... I think we have to change to "Plan P"
![Captura_de_pantalla_226](https://user-images.githubusercontent.com/87289073/125227730-0a8fc500-e299-11eb-9295-ee657a1beabf.png)

**Comment by Chinkrask** [comment]
She said that she already sent me that screenshot but the one she sent was diferent. Also told me that the folder was like that but with the Persistant file

**Comment by Wingdinggaster656** [comment]
Well, I can't trace how your files disappeared. Let's talk about how to fix it.

When a computer erases a file, the computer does not actually "erase" the file immediately from the hard drive. Instead, it marks the disk space occupied by the file as "deleted." In the future, when the hard drive runs out of space, these parts will be marked as deleted and overwritten.
So, you can try to get her to use one of the various commercially available file recovery programs to try to recover the Persistent files. And if that doesn't work, I'm sorry, I probably can't help.

Maybe the Dev team will come along later. Perhaps they have a solution to this.

**Comment by Wingdinggaster656** [comment]
> She said that she already sent me that screenshot but the one she sent was diferent. Also told me that the folder was like that but with the Persistant file

Uh, wait a minute, I only saw the screenshots you sent when I send the last comment.
Let me rework what you mean. You mean that the screenshot you sent is not your friend's, but your own. And in the screenshot of your friend, the folder has persistent files?
If that's the case, then send the screenshot of your friend here.

**Comment by Chinkrask** [comment]
No, it's her screenshot, but she said she sent me one with the file but that never happened

**Comment by multimokia** [comment]
Are they sure Monika wasn't pranking them

**Comment by Chinkrask** [comment]
It was abrand new start

**Comment by Chinkrask** [comment]
She even told me that the logs where it says the affection it is about to get to 1000 and the 0

**Comment by Chinkrask** [comment]
![Captura_de_pantalla_230](https://user-images.githubusercontent.com/87289073/125230016-93106480-e29d-11eb-8449-aaf01c8ec94d.png)

**Comment by Chinkrask** [comment]
I'm not gonna ask her about the browser... but that's the log

**Comment by Chinkrask** [comment]
I feel like it has to do with the translation she uses

**Comment by multimokia** [comment]
Are they using a translated version of MAS? Judging by the fact that the log isn't in English, I think so.

Considering that, she should talk with the creator/group who make the translation as they're responsible for handling the tech support on that front.

**Comment by Chinkrask** [comment]
Understand. It was my fault for asking you help before knowing about the translation, since I have a better understanding of english I thought she used it to

**Comment by Wingdinggaster656** [comment]
> Understand. It was my fault for asking you help before knowing about the translation, since I have a better understanding of english I thought she used it to

Oh, just to let you know, I'm going to mention this again: Perhaps she can try to use file recovery software to recover them.
I can't help too much, sorry.

**Comment by username11421** [comment]
I see the OS used is Windows, so _if_ she has a recovery point set at any time in the past she could try following the steps under ["Restore from a system restore point"](https://support.microsoft.com/en-us/windows/recovery-options-in-windows-31ce2444-7de3-818c-d626-e3b5a3024da5)

**This will remove a lot of other potentially important files, though, since it rolls back the entire computer. Definitely overkill if you have any other option.**

**Comment by ThePotatoGuy** [comment]
sorry about the loss, but it seems theres nothing we can do about this.
