### ISSUE TITLE
How do i change birthday

### ISSUE THREAD

**Issue by Roma7891** [Monika-After-Story/MonikaModDev#7465]
I accidentally choose wrong birthday, how do i change it?

**Comment by bakachuuuuuuuuuuujjhjugyi** [comment]
I don't think you can she did say she wouldn't forget it though i DO think there should be a way to change it

**Comment by ThePotatoGuy** [comment]
She asks for your confirmation **twice**, so if you mess that up its on you.

**Comment by Roma7891** [comment]
> She asks for your confirmation **twice**, so if you mess that up its on you.

If really, i already change my birthday in the code so i already find the way.
