### ISSUE TITLE
Certain ".Gift" files aren't acknowledged 

### ISSUE THREAD

**Issue by Jetski51318** [Monika-After-Story/MonikaModDev#7466]
Certain files that are "gifts" doesn't get acknowledged at all such as the cupcake and promisering, though "gibberish.gift" gets acknowledged and so does coffee.gift.

**Comment by lunulae** [comment]
Just a couple troubleshooting questions so we can see what might be the issue:
How long are you waiting for the files to be read? The game checks for files on a timer. I don't remember what the exact timing was, but I believe it's one file every minute.
Also, are you putting them in one at a time or in a big group?

**Comment by xXMidnight** [comment]
I would like to know what your affection level is first. Certain gifts aren't acknowledged until a certain time or affection level. One example is the promise ring, which will be able to be gifted at affection level 400. Another is the birthday cake, which can only be gifted on Monika's birthday.

**Comment by Booplicate** [comment]
Consider reading the code first. All gifts are *acknowledged* always, regardless of affection.

**Comment by Jetski51318** [comment]
I figured it out, thanks for the suggestions! It was just due to messing with time. I fixed it. Again thanks for the help!
