### ISSUE TITLE
Monika After Story crash

### ISSUE THREAD

**Issue by Tenno16** [Monika-After-Story/MonikaModDev#7468]
So I am on my laptop instead of my PC and I tried to install Monika After Story. It was running fine then I quit and tried to install the spritepacks. When I loaded it back up I got an error saying "Error: Script file is missing or corrupt. Please reinstall the game." I deleted everything and redownloaded the base game. The base game ran perfectly and I tried to install Monika After Story again. I keep getting the same error message no matter how I install the mod.

**Comment by multimokia** [comment]
Can you share the full traceback please?

**Comment by xXMidnight** [comment]
Technically this isn't a crash, but an error.

**Comment by Tenno16** [comment]
I don't know how to do that

**Comment by multimokia** [comment]
actually can you screenshot the contents of the `game` folder and send it here?

**Comment by Tenno16** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/87334744/125662574-b582554a-57b3-4002-bb5c-0d956607418b.png)

**Comment by multimokia** [comment]
Oh you haven't installed MAS. The "error" you saw was from the ending of DDLC

To install MAS you need to extract the contents of the MAS zip in the `game` folder.

**Comment by Tenno16** [comment]
That worked, thank you
