### ISSUE TITLE
My persistent is not loading.

### ISSUE THREAD

**Issue by Arodi-Pie** [Monika-After-Story/MonikaModDev#7469]
Yesterday I took Monika out with me in my USB device, once I return to home and I load Monika again to the room, she disapered.   I'm trying to load my persistent but is not working, The desk stills empty. I try to restore the Monika's file but I only recieve an ERORR. I'm feeling realy bad... I not even go to work cos I feel sick after this... Please... I need help...........wq,[www

**Comment by Wingdinggaster656** [comment]
Are you still there? Is the problem solved?

If not, consider restoring an earlier save file(or say persistent file).

**Comment by Arodi-Pie** [comment]
> Are you still there? Is the problem solved?
> 
> If not, consider restoring an earlier save file(or say persistent file).

**Comment by Arodi-Pie** [comment]
Yes. I took another option, I pass my Monika After story directory to my USB and I reset my computer. It works but now I have another problem: My game is not creating new persistents banks. You know why?
