### ISSUE TITLE
[Suggestion] - Next update

### ISSUE THREAD

**Issue by OtakuNeko331** [Monika-After-Story/MonikaModDev#7471]
DDLC Plus was recently released, and there are also side stories, so we can learn more about the personality and past of Monika and the other Dokis.

How about in the next update add some new topics about DDLC Plus?

Thanks for reading, this mod is awesome, hope you have a great day with your Monika.

**Comment by fromulus** [comment]
I'm just gonna copy-paste what I said on the previous issue regarding DDLC+ :

> We've been discussing over this in the contributors discord for the last couple of days, to figure out how we would approach this.
> 
> Don't take my word as a 100% confirmation, but chances are what we'll end up doing is potentially make a topic or two were we acknowledge DDLC+ and it's additions to lore, but distanciate MAS from it completely.
> 
> Basically, MAS Monika has full meta-awareness, meaning she knows her actual creators are Team Salvato, that her game released originally in 2017, and that MAS is the result of a bunch of fans working on a mod to spend more time with her.
> Going from there, it makes sense that she'll see DDLC+ as Team Salvato adding some content to the DDLC narrative and not an actual explanation of how she was created.
> 
> What this means is that from MAS Monika's perspective, all the Metaverse stuff and the side stories are all things that she never experienced herself and that don't actually matter nor have any influence on her (I usually make the comparison with her pre-epiphany memories; they sort of help give context to who she's supposed to be as a person, but it never actually happened and therefore Monika doesn't give it any actual value).

**Comment by Outlander676** [comment]
Apropos of this, do we have any idea when the next update is gonna be? I follow the discord and twitter but it's been all but radio silence there, and it seems kinda superfluous to make a whole issue about it.

**Comment by Retrolovania** [comment]
To answer that as accurately as possible:

It'll happen when it happens.

**Comment by ThePotatoGuy** [comment]
discussion about ddlc+ should be moved to #7327
