### ISSUE TITLE
[Suggestion] - Giving Monika Recipes

### ISSUE THREAD

**Issue by xXMidnight** [Monika-After-Story/MonikaModDev#7472]
I have an idea.
Monika keeps saying she would like to bake cupcakes someday.
Why not give her the recipe?
Oh and probably some other ingredients too

**Comment by lunulae** [comment]
When #6994 goes through, we could maybe later create a rare event for her to make her own, which would refill her stock.

**Comment by Kritzb278** [comment]
Maybe the player could give her the recipe as a .gift file? Like recipe.gift or natsukicupcakerecipe.gift or cupcakerecipe.gift.

**Comment by ThePotatoGuy** [comment]
Similar vein to writing her a poem - hard for us to make Monika react to it in a generic yet reasonable way.

[closing until we look into it]
