### ISSUE TITLE
How do I give Monika gifts that exist in the game's file ?

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7474]
I was scrolling through a bunch of videos on how to give monika gifts, but all of them leads to the Sprite Pack (which I already know how to download). I wish there's someone out there know how to give stuff like the witch's outfit or the sweater that exist in the game's file.

**Comment by PongMaster69** [comment]
Witches outfit I believe is Halloween only (I.E. on Halloween you play on that day you unlock one of her outfits at random) If you want to install the sprite pack into the game itself (I.E. it's downloaded and you don't know how to implement it into the game) then here's how. Each costume should come with 2 folders, one containing the assets that the code needs and the other containing a .gift file. In the first folder there should be two more folders labeled things such as "a" or "j". Navigate to the game--> mod_assets ---> monika folder. In that folder you will see folders that match that folder. Copy the assets from the "a" or "j" folder from the sprite pack into the matching one in the "monika" folder, but do not replace the folder. I hope this helps and if I'm wrong please correct me

**Comment by ThePotatoGuy** [comment]
Stuff that comes with the mod generally is unlocked under specific circumstances and cannot be unlocked with gifts.
