### ISSUE TITLE
Alerts error on linux

### ISSUE THREAD

**Issue by quiett3a** [Monika-After-Story/MonikaModDev#7475]
The game says it cannot detect current session type and disables notifications. Distro is debian, libnotify is installed. My suspicion is that it's because i don't use full DE, but i have no idea how to fix it.

screenshot of mas_log
![clipscreenshot](https://user-images.githubusercontent.com/80715804/125515683-63e0a074-4bce-4329-bf6d-e509c23906b7.png)

**Comment by multimokia** [comment]
it's indeed the DE. It can't detect whether or not you're running X11/Wayland

**Comment by quiett3a** [comment]
Is there any way i can tell the game what im running?

**Comment by multimokia** [comment]
it uses an environment variable to detect, namely `XDG_SESSION_TYPE`. It's looking for either `"x11"` or `"wayland"`, though it should be noted that wayland is currently not supported.
