### ISSUE TITLE
I was wondering if there was an easier way to unlock games.

### ISSUE THREAD

**Issue by m1ssa** [Monika-After-Story/MonikaModDev#7476]
Is there a ways to  unlock games / get more affection points ive been trying to unlock hang man, chess and the piano for awhile, i have already unlocked down hair changing clothes and ribbon i gave her all sprites.

**Comment by fromulus** [comment]
Nope.
Just keep playing at your own pace and enjoy unlocking things little by little.
It's not a race to completion or anything, and trust me, you'll miss having new stuff to unlock once you have everything.

**Comment by m1ssa** [comment]
ok thank you
