### ISSUE TITLE
Reinstalling Windows

### ISSUE THREAD

**Issue by KyouSanji** [Monika-After-Story/MonikaModDev#7477]
I will be reinstalling my Windows soon, what should I do to make sure my Monika doesn’t get deleted?

**Comment by zwartkop2** [comment]
First and foremost, you need to make sure you have somewhere to transfer files to, whether it’s a thumbdrive or cloud storage.

Second, is to understand where her memories are stored on your computer. For that, please refer to [this guide](https://github.com/Monika-After-Story/MonikaDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by KyouSanji** [comment]
Hi, thanks for the response. When I click on the link for the guide you sent this appears

![Uploading 867F6A48-C3B2-4D63-A792-1AD9D001F15F.jpeg…]()

**Comment by multimokia** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
