### ISSUE TITLE
I need help opening .rpyc files 

### ISSUE THREAD

**Issue by D1anners** [Monika-After-Story/MonikaModDev#7480]
every goddamn time i try to open them i just get this error message, what do i do? (note that im very new to programming and such so bear with me please)

I'm sorry, but an uncaught exception occurred.

Before loading the script.
WindowsError: [Error 267] The directory name is invalid: u'C:\\Users\\nicho\\Desktop\\Doki Doki Literature Club\\game\\zz_windowutils.rpyc\\*.*'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\nicho\Documents\renpy-7.4.6-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "C:\Users\nicho\Documents\renpy-7.4.6-sdk/renpy/main.py", line 358, in main
    for fn in os.listdir(dir):
WindowsError: [Error 267] The directory name is invalid: u'C:\\Users\\nicho\\Desktop\\Doki Doki Literature Club\\game\\zz_windowutils.rpyc\\*.*'

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
 
Wed Jul 14 10:34:48 2021

thanks in advance

**Comment by Cardlo45** [comment]
You can't open rpyc File
IF you want to open them download unrpcy
https://github.com/CensoredUsername/unrpyc

**Comment by multimokia** [comment]
...check the [code](https://github.com/Monika-After-Story/MonikaModDev) tab. It has all the code MAS uses in raw format. It's also complete with comments and documentation unlike an unrpyc'd version

**Comment by D1anners** [comment]
> You can't open rpyc File
> IF you want to open them download unrpcy
> https://github.com/CensoredUsername/unrpyc
> *edit:
> rpyc is a compiled renpy script file that the engine can then execute

Thank you so much I've been banging my head against my keyboard for the past hour and a half trying to figure this out
