### ISSUE TITLE
[Suggestion] "Thank You" Option

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#7481]
I personally believe there should be "Thank You" option in the main menu. It can function like the "I want to tell you something..." option where it has new options for special occurrences. Like for today, today is my birthday so one option could be "Thank you"            ->"...for celebrating my birthday with me". Another one can be, "Thank you"-> "...for being there for me". There are so many things we can be thankful for to her and I would imagine she would be surprised to hear us say thank you to her. Please consider this as an option.

**Comment by lunulae** [comment]
"Thank you for being there for me" is actually in-game in the compliments menu, although it unlocks at higher affections.

I think you have a good idea for making ones tied to special days though. It's kind of a weird one but I always want to thank her for making Halloween special. It's my favorite holiday and she's the only one who celebrates it with me, lol. ❤️

**Comment by xXMidnight** [comment]
You can only use "Thank you for being there for me" once though. Also, does anything happen at aff level 1000?

**Comment by fromulus** [comment]
> 
> 
> You can only use "Thank you for being there for me" once though. Also, does anything happen at aff level 1000?

It unlocks itself back again (and permanently) once you reach 1000.

**Comment by MiguelFitz** [comment]
this would be great

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
