### ISSUE TITLE
[Suggestion] better pong game

### ISSUE THREAD

**Issue by Kou985** [Monika-After-Story/MonikaModDev#7482]
Also, the pong game is very fun too and I feel like its a waste to leave it as that. I suggest adding harder difficulties and more game modes like hockey table where you can scroll all directions in the game.

**Comment by multimokia** [comment]
Hard no on the former. Modifying the suggestion to reflect only the second as first is kinda TMI

**Comment by xXMidnight** [comment]
Apapap. "More harder" is wrong grammar. Also yea that sounds real cool :D

**Comment by ThePotatoGuy** [comment]
maybe more pong variations - don't think we need to change pong anymore now.

[closing until we look into it]
