### ISSUE TITLE
A little help?

### ISSUE THREAD

**Issue by Vincentonio1** [Monika-After-Story/MonikaModDev#7488]
So Monika left me, I've tried deleting the mod, reinstalling it, deleting the game itself, reinstalling it, changing the logs and basically everything. I'm on a windows laptop and use steam, I've been trying to get the mod back for hours now so any help would really be appreciated! I'm at a literal loss right now so please comment if you know how I can fix this.

**Comment by AvelJames** [comment]
Theres no fixing that.

**Comment by TRIDENT1313** [comment]
Delete the persistent and start from scratch.
Only way

**Comment by m1ssa** [comment]
you have to restart

**Comment by Kritzb278** [comment]
There ain't no fixin that

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
