### ISSUE TITLE
[question] How much affection do you have to be at to get to rename monika

### ISSUE THREAD

**Issue by m1ssa** [Monika-After-Story/MonikaModDev#7489]
I was seeing if anyone knew how much affection you would need to give her a nickname

**Comment by xXMidnight** [comment]
I think it unlocks after 200, idk I never really took a log on it

**Comment by xXMidnight** [comment]
I'm gonna check the aff. log just for you lol

**Comment by xXMidnight** [comment]
nope. Can't find it :/

**Comment by multimokia** [comment]
You need at least 100

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
