### ISSUE TITLE
How to give her gifts ?

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7490]
I've always wanted to give her gifts that inside the file assets already, I especially wanted to give her this outifit. But I wasn't been able to find any solutions online. If anyone out there knows how to do it, please consider letting me know.

**Comment by CrewieAustin** [comment]
![clothes-rin](https://user-images.githubusercontent.com/86544170/125715331-58e88cbe-0044-4494-b34f-0b7af34bd532.png)

**Comment by PongMaster69** [comment]
You need the sprite pack, once you have that and implement it properly then it's as simple as creating a text document with the proper title needed for the outfit, and changing the extension from .txt to .gift. I recommend checking the Wiki for more specifics.

**Comment by fromulus** [comment]
> 
> 
> ![clothes-rin](https://user-images.githubusercontent.com/86544170/125715331-58e88cbe-0044-4494-b34f-0b7af34bd532.png)

This specific outfit cannot be gifted.
It's a Halloween costume, you'll need to spend time with her on Halloween day and she just might surprise with a random costume--this is one of them.
