### ISSUE TITLE
[Suggestion] - Venting/talking topic/option

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7492]
I feel like this is something minor but people might want. Basically take the "I'd like to vent" option from telling Monika you had a bad day, change it to be a button underneath the "You" category and call it "I'd like to talk about something". I thought this should be implemented because in Monikas dialogue she always refers to listening to you tell her things but it's not really an option per day without clicking the "sad" feeling.

**Comment by xXMidnight** [comment]
Yeah, it's a very, VERY nice addition if it were one. I would really like to vent in text to Monika and not just voicing it out >:0 I can't do that if my voice hurts, and believe me when I say I haven't used it in so long that now I sound like a boy. Yea I'm a girl

**Comment by ThePotatoGuy** [comment]
I like this in principle. I just don't know how Monika would be able to respond to venting about anything - it would have to be thought out.

[closing until we look into it]
