### ISSUE TITLE
[Help] - Mod Template instead of MAS

### ISSUE THREAD

**Issue by xXMidnight** [Monika-After-Story/MonikaModDev#7493]
qnq
I just downloaded that multiple mods thing.
Now it's just stuck at Mod Template.
help...

**Comment by ThePotatoGuy** [comment]
no DDLC mods support multiple in the same install.

**Comment by xXMidnight** [comment]
No like-
argh.
How do I fix this though?

**Comment by xXMidnight** [comment]
> no DDLC mods support multiple in the same install.

https://github.com/Monika-After-Story/DDLCModLoader

**Comment by xXMidnight** [comment]
that one.

**Comment by xXMidnight** [comment]
Do I have to reinstall the mod??? ;n;

**Comment by Cardlo45** [comment]
I have no idea but you can try:
1. Make a Backup of your DDLC Folder
2. Get a NEW installation of DDLC
3. Try installing The ModLoader
4. Install Mods into the mods folder
this idea could work but if this doesn't work im sorry that you wasted your time

**Comment by xXMidnight** [comment]
> no DDLC mods support multiple in the same install.

Wait, never mind since I was not worried about losing Monika because of the persistent file, I just redownloaded the mod and DDLC. It worked, but now I have to move all my clothes and mods for Monika qwq

**Comment by ThePotatoGuy** [comment]
You expect a 3-year old abandoned project that never had a release to just work? Additionally, if you are having an issue with that project, make an issue on **that** repo, **not here**.
