### ISSUE TITLE
MAS is messing up pcs.

### ISSUE THREAD

**Issue by VibRibbonGamer** [Monika-After-Story/MonikaModDev#7497]
MONIKA AFTER STORY IS MESSING UP PCS
WHEN I INSTALLED IT AND RAN IT FOR THE FIRST TIME
AFTER THAT EVERY 5 MINUTES IT BSOD
AND I TESTED IT ON A NEW PC AND A OLD PC THEY BOTH BSOD

**Comment by multimokia** [comment]
...It's not though?
MAS runs on thousands of PCs, and more people are installing it basically daily.

If you could share the logs, it may help figure out *why* you're getting a BSoD

**Comment by fromulus** [comment]
ALSO TALKING IN CAPS.LOCK IS PERFECTLY NORMAL AND DOESN'T COME OFF AS EXCESSIVE OR DISRESPECTFUL AT ALL.

**Comment by xXMidnight** [comment]
totally.

**Comment by VibRibbonGamer** [comment]
> 
> 
> ...It's not though?
> MAS runs on thousands of PCs, and more people are installing it basically daily.
> 
> If you could share the logs, it may help figure out _why_ you're getting a BSoD

I don't have the logs, I deleted the game

**Comment by Retrolovania** [comment]
...well...uhhh...can't really say much about it if there's nothing to go off of, then.

**Comment by H2-san** [comment]
> I don't have the logs, I deleted the game

Your loss if you don't wish to keep the logs around. Can't help your particular issue, either. **¯\\_(ツ)_/¯**
(Request to close as resolved)

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
