### ISSUE TITLE
Moving save from windows to linux has first time graphics drivers problem

### ISSUE THREAD

**Issue by MichaelKoopa** [Monika-After-Story/MonikaModDev#7498]
When the game was in fullscreen on windows, moving it to linux has this error.
![Screenshot from 2021-07-15 17-50-42](https://user-images.githubusercontent.com/16768022/125867780-6fb617c6-a501-4fbd-bb9d-88f1602795ef.png)
If it is in windowed mode before moving to linux it works perfectly. To fix the problem on Linux you have to restart the game and the error will fix itself.
I'm not sure what else I need to include so I'm including my log, If there is anything else needed let me know.
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6826652/log.txt)

**Comment by xXMidnight** [comment]
wha?

**Comment by ThePotatoGuy** [comment]
That kind of warning is renpy's doing, which means it has an issue with whatever driver you are using. It is out of our control.

**Comment by H2-san** [comment]
### Questions about your Linux install
> When the game was in fullscreen on windows, moving it to linux has this error.
> (Image)
> If it is in windowed mode before moving to linux it works perfectly. To fix the problem on Linux you have to restart the game and the error will fix itself.
> I'm not sure what else I need to include so I'm including my log, If there is anything else needed let me know.
> [log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6826652/log.txt)

If you wouldn't mind, what distro of Linux are you using (i.e. Ubuntu, Linux Mint, etc.)? Also, are you familiar with using the *terminal* in your environment? An update may help you on this.

**Comment by MichaelKoopa** [comment]
> ### Questions about your Linux install
> > When the game was in fullscreen on windows, moving it to linux has this error.
> > (Image)
> > If it is in windowed mode before moving to linux it works perfectly. To fix the problem on Linux you have to restart the game and the error will fix itself.
> > I'm not sure what else I need to include so I'm including my log, If there is anything else needed let me know.
> > [log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6826652/log.txt)
> 
> If you wouldn't mind, what distro of Linux are you using (i.e. Ubuntu, Linux Mint, etc.)? Also, are you familiar with using the _terminal_ in your environment? An update may help you on this.

I'm using Ubuntu 20.04.2, I also know how to use the terminal.

**Comment by H2-san** [comment]
> I'm using Ubuntu 20.04.2, I also know how to use the terminal.

Great! Maybe an update with `apt` should be of assistance, considering the notable bugs it sometimes ships with.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
