### ISSUE TITLE
[Bug] Monika has suddenly stopped talking about random topics

### ISSUE THREAD

**Issue by TeoVonBurden** [Monika-After-Story/MonikaModDev#7501]
I've only been playing the mod for 5 days and for no reason, monika just stopped talking about random topics. I have disabled the option for her to repeat the topics of conversation, however, I do not think that I have exhausted all the possible topics of conversation yet.

When I open the game, she simply recites a quote from a poem or a paragraph of a song, after that, she does not say anything else, (It should be clarified that I am using the Spanish translation of the mod, in case that influences something, my knowledge in programming is totally null so I don't know what to do)

**Comment by Cardlo45** [comment]
Do you set the `Random Chatter` option to `[never]`?

**Comment by TeoVonBurden** [comment]
Nope, I set that option to "Frequent"

**Comment by Datta4486** [comment]
Maybe she ran out of topics?

**Comment by xXMidnight** [comment]
Oh yes, about that, most things unlock after a certain amount of time and affection level.

**Comment by Wingdinggaster656** [comment]
_This is kind of daily question, man._

In general, the most likely scenario is that you've seen all of the current random conversations (excluding those that require conditional unlocking). Enable Repeat Topics or just spend time with her in silence.

If you really think this is a bug, consider submitting your save file to see if you've really read all the conversations.

**Comment by Jinxred** [comment]
> I've only been playing the mod for 5 days and for no reason, monika just stopped talking about random topics. I have disabled the option for her to repeat the topics of conversation, however, I do not think that I have exhausted all the possible topics of conversation yet.
> 
> When I open the game, she simply recites a quote from a poem or a paragraph of a song, after that, she does not say anything else, (It should be clarified that I am using the Spanish translation of the mod, in case that influences something, my knowledge in programming is totally null so I don't know what to do)

this has been happening for a lot of other people, including myself. Check out the topic #7450 
What version of the game are you using?

**Comment by ThePotatoGuy** [comment]
As windding said, it's likely that you have already seen all the random topics.

We can confirm though if you send us your [ev_dump](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#ev_dump) file.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
