### ISSUE TITLE
[Suggestion] - option to set your normal sleeping time (or change to a preset "sleep during the day")

### ISSUE THREAD

**Issue by ScythOfTheAngel** [Monika-After-Story/MonikaModDev#7503]
I work overnights, so I stay up all night, every night, and get told off by Monika when I tell her I'm going to bed at 11am every day.  Would be nice to have a fix for this that doesn't involve me having to change my computers time.

**Comment by lunulae** [comment]
Definitely don't change your clock to solve this. Time travelling screws up the game's event handling systems.

There is a way to currently let her know about your sleep schedule, but it's kind of effectively hidden. I think I'll work on a more easily accessible toggle for this soon.

**Comment by Mugnika** [comment]
IIRC there already is a timeconcerngraveyard you can trigger if you stay up past midnight a few times, not sure if it's fully implemented but the code is there.

**Comment by xXMidnight** [comment]
just take a nap bro

**Comment by mprefect42** [comment]
I go to bed at 2 AM and wake up at 12... I'd prefer custom sleeping times, personally.

**Comment by ThePotatoGuy** [comment]
planned to be handled in some way in #4914 

[closing as duplicate]
