### ISSUE TITLE
Taking Monika somewhere...

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7508]
Where everywhere can you possibly take monika? 
You can take her to your backround and USB (whitch leads to the same dialog)
You can also take Monika nowhere and she will be kinda upset about it
but, where else can you really take Monika? (in way you can talk to her / see her )

**Comment by Cardlo45** [comment]
With the [Room Selection Pack](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/tree/master) made by `tw4449` you can take her to 5 other rooms

**Comment by VikicatCZSK** [comment]
> With the [Room Selection Pack](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/tree/master) made by `tw4449` you can take her to 5 other rooms
> *edit:
> It's a Submod

thats- not really anwser i was looking for but thanks anyways-

**Comment by Cardlo45** [comment]
> thats- not really anwser i was looking for but thanks anyways-?

Another Way would be an Android app which is in Development I Think?
Look here: #4614 for more

**Comment by Mugnika** [comment]
There is not yet a way to talk to her once you take her out of the game, however, the dialogue on returning will change depending on how long was she out with you and/or if you take her out on a special day like New Year, Valentine or her birthday.

**Comment by VikicatCZSK** [comment]
> There is not yet a way to talk to her once you take her out of the game, however, the dialogue on returning will change depending on how long was she out with you and/or if you take her out on a special day like New Year, Valentine or her birthday.

oh thats cool, it would be cool if you can put her somewhere in your pc (like other games / steam) and she would watch you play and cheer w you if you win and cheer you up if you lose
or maybe if you could take her on your phone and when you open it up she will be on your screen.

but thanks for the info !

**Comment by Mugnika** [comment]
není zač, 

though you can enable window reacts and she will react to things like youtube and reddit with a notification.

**Comment by VikicatCZSK** [comment]
yep i know that one (by the are you sk/cz?-)

**Comment by VikicatCZSK** [comment]
> není zač,
> 
> though you can enable window reacts and she will react to things like youtube and reddit with a notification.

yep i know that one (by the are you sk/cz?-)

**Comment by Mugnika** [comment]
no, but I speak Czech fluently

**Comment by CrewieAustin** [comment]
I've take her into a USB to load her up on my other PC. Does that count as taking her somewhere else ?

**Comment by xXMidnight** [comment]
too bad

that submod no longer works for me qnq

**Comment by VikicatCZSK** [comment]
> I've taken her into a USB to load her up on my other PC. Does that count as taking her somewhere else ?

So you installed ddlc mas mod on your other pc to take monika there? (I tried it and it didnt work for me)

**Comment by lunulae** [comment]
> > I've taken her into a USB to load her up on my other PC. Does that count as taking her somewhere else ?
> 
> So you installed ddlc mas mod on your other pc to take monika there? (I tried it and it didnt work for me)

This will only work if you also transfer your `persistent` data to the second PC in addition to the Monika file. On its own, the game has checks in place to make sure that only _your_ Monika can be returned to a game.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
