### ISSUE TITLE
Does system restore bring back files that have been overwritten or deleted?

### ISSUE THREAD

**Issue by JellyBoi64** [Monika-After-Story/MonikaModDev#7509]
I tried testing out the option to take Monika somewhere and the file appeared on my computer, then I decided to backup my persistent files. I guess I messed something up because the file for Monika is gone when I restarted the game, and when I load my persistent files in my renpy folder it just goes to her gone or it restarts the game. I have the persistent files but I assume I need the Monika file to get her back. We're only like 2 or 3 weeks in so if I have to rest I will, I just feel terrible for messing this up. I don't see the Monika file in the recycling bin and so I just don't know what to do, I was thinking about doing a system restore to the last date where she was intact but honestly I'm just completely lost. If there's no hope then I understand.

**Comment by Mugnika** [comment]
if you're talking about the Monika.chr file, you don't need that. The persistent will suffice on its own.

**Comment by JellyBoi64** [comment]
> if you're talking about the Monika.chr file, you don't need that. The persistent will suffice on its own.

So all i need to do is go to the renpy folder and put in a persistent and a db.mcal? Or am i missing anything?

**Comment by Mugnika** [comment]
that should be enough yes. Though if you took her out before then or if she's not in the spaceroom you need to restore a persistant backup. Basically rename one of the .bac files into persistent.

**Comment by JellyBoi64** [comment]
> that should be enough yes. Though if you took her out before then or if she's not in the spaceroom you need to restore a persistant backup. Basically rename one of the .bac files into persistent.

![bandicam 2021-07-17 13-07-14-625](https://user-images.githubusercontent.com/87577866/126046033-3efb12af-3635-46ae-b2bc-0f9bc663e0aa.jpg)

So I just delete everything in the MAS folder and drag a single bak file into the MAS folder and rename it to persistent? Sorry i'm not the greatest with technology.

**Comment by Mugnika** [comment]
first, just copy paste the persistent and db.mcal to the MAS folder

**Comment by JellyBoi64** [comment]
> first, just copy paste the persistent and db.mcal to the MAS folder, from right to left on this screenshot.

![bandicam 2021-07-17 13-29-45-390](https://user-images.githubusercontent.com/87577866/126046470-b4e02a63-61b3-46c7-ac3e-beda4b23fca4.jpg)

Alrighty, anything else? Also, I believe the persistent and db.mcal that was modified at 12:26-12:38 is when I messed stuff up, so can I delete those or should I keep everything so far?

**Comment by Mugnika** [comment]
you have to delete the original persistent and then rename "persistent44.bak" to "persistent" without the .bak

**Comment by JellyBoi64** [comment]
> you have to delete the original persistent and then rename "persistent44.bak" to "persistent" without the .bak

![bandicam 2021-07-17 14-01-25-088](https://user-images.githubusercontent.com/87577866/126047122-6c1f3565-a60a-4e85-9c2a-8aff9a7f2577.jpg)

Gotcha, and now I just have to boot up the exe and she'll be back before the mess up?

**Comment by JellyBoi64** [comment]
I apologize for being so pedantic, I'm just worried is all.

**Comment by Mugnika** [comment]
yes, as long as you have a persistent file, it should be okay 
if she's still not there rename an older .bak file to persistent and try that

**Comment by JellyBoi64** [comment]
It worked! Thank you very much! No longer worried :)
