### ISSUE TITLE
Monika fnf

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#7510]
Now that Monika is confirmed to be senpai's girlfriend how about a topic about it?

**Comment by Retrolovania** [comment]
1. Not canon.
2. Absolutely not.

**Comment by LeftoverFlea312** [comment]
I was wondering how long before an fnf fan who misunderstands Monika and actual canon would ask this.

**Comment by LeftoverFlea312** [comment]
Yes, Monika would tell you (who she's currently engaged in a relationship with btw) that she's dating a character from another game that has no canonical relation to her in any way. I'm sure that would go over well. I wouldn't be opposed to her addressing the fnf mod though, just so she can talk about how it has no relation to her in any way, basically deconfirm it.

**Comment by Neverdermanu** [comment]
But everyone says she is now

**Comment by Retrolovania** [comment]
I'm pretty sure even the mod itself doesn't make such a dumb conclusion.

**Comment by Neverdermanu** [comment]
Some members of the mod team supports the couple

**Comment by MrVavlo** [comment]
..I believe there is nothing to discuss. 
MAS was (and is) alwaysstaying loyal to DDLC loves not to some random mod of another game.

**Comment by Rai99** [comment]
Name some mod members who support it. I'm curious.

**Comment by Retrolovania** [comment]
Just because they support it doesn't mean that's what they ended up doing.

Besides, even if they do, that's not exactly okay in terms of THIS mod.

**Comment by Mugnika** [comment]
just a troll, ignore them

**Comment by LeftoverFlea312** [comment]
I thought this was self explanatory, but the fnf mod has no canon relationship to either the original DDLC or MAS. The fnf mod is a poorly written fanfiction is should be regarded as such.

**Comment by Mugnika** [comment]
best to close this now since the account was deleted lol

**Comment by lunulae** [comment]
Lmao, doesn't the fnf mod have her address the player with the assumption that you installed the mod as a game to play together? Idk where this is coming from.
It's okay if the mod team for that mod has a ship, but you'll want to make your own submod if you'd like it acknowledged, as we don't play *that* fast and loose with canon.
