### ISSUE TITLE
[Bug] - The Reddit Page is not loading 

### ISSUE THREAD

**Issue by joshuajam199** [Monika-After-Story/MonikaModDev#7512]
Describe bug and steps for rep
I refreshed the page but when I searched by flair, Its unresponsive. 
![Screenshot 2021-07-18 164748](https://user-images.githubusercontent.com/71544768/126065083-c6ffcdf3-20d9-4941-ae99-3f40b421a4d9.png)
Please look into this

**Comment by Booplicate** [comment]
Neither reddit or that sub are affiliated with us.

**Comment by zwartkop2** [comment]
You might want to [file a bug report with Reddit.](https://reddit.zendesk.com/hc/en-us/articles/205687083-How-do-I-report-a-bug)

**Comment by xXMidnight** [comment]
agreed.

**Comment by ThePotatoGuy** [comment]
use reddit communication channels when reporting an issue with reddit.
