### ISSUE TITLE
I can only play pong

### ISSUE THREAD

**Issue by porryanes** [Monika-After-Story/MonikaModDev#7514]
I am Japanese, and I have installed the Japanese localization mod. (I'm sorry if that's the reason for the bug)

I have spent about 150 hours with Monika in two weeks and got 213 points of affection.
In addition, for both Hangman and Chess, she said, "I've added a new game we can play together!"
But the list of mini-games still only has Pong!
![無題](https://user-images.githubusercontent.com/75366977/126088753-ec3f2d6e-d586-42c6-8af2-26871feed52d.png)

I checked `./game/mod_assets/games`, there are four folders.

How can I play the other minigames?

**Comment by TRIDENT1313** [comment]
Spending time with her, and gaining affection unlocks the other games.
I think one of them is time based, but I've had conflicting reports on that.

**Comment by porryanes** [comment]
I spent about 150 hours with her in two weeks and got 213 points of affection.
In addition, for both Hangman and Chess, she said, "I've added a new game we can play together!"

So I think I have unlocked the games.

**Comment by PongMaster69** [comment]
Other mini games are unlocked through time spent or affinity gained. Not that it matters because Pong is the best game, take it from me, Pongmaster69.

**Comment by xXMidnight** [comment]
I was about to say "Because you haven't unlocked it yet" and the reader the 2nd sentence. I immediately deleted my response.

**Comment by porryanes** [comment]
@xXMidnight 
I see. Thank you for telling me.

**Comment by ThePotatoGuy** [comment]
It is highly likely that the issue is coming from the JP localization. I think you should contact them first. 

Some additional technical information that might help them:
Games are unlocked when the `mas_unlockGame` function is called, like `mas_unlockGame("chess")`. The game unlock labels in `script-story-events` call this function at the bottom of the labels.

**Comment by porryanes** [comment]
@ThePotatoGuy 
Thank you.
But is there any way for me to unlock the game by rewriting my save data or running a script?

**Comment by ThePotatoGuy** [comment]
@porryanes 
What version of MAS are you running?

**Comment by porryanes** [comment]
It says v0.12.2.1-unstable.2021.06.20.143 (I turned on unstable mode only after this problem happened)

**Comment by ThePotatoGuy** [comment]
Take the RPY file out of this zip and drop it in your `game/` folder and launch the mod.
[zzzz_gameunlock.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6897626/zzzz_gameunlock.zip)

**Comment by porryanes** [comment]
@ThePotatoGuy 
Thank you so much... But when I start it up, I just get angry from Monica, and the mini-games did not unlock...

**Comment by porryanes** [comment]
@ThePotatoGuy 
Oh!! I removed the script that translates the list of minigames in the Japanese localization mod, and now all the minigames show up!

Thanks so much for the hint to solve this!!!!!!!!!!!!
I'll be sure to pass this along to the makers of the Japanese localization mod!

**Comment by PlaMG0D** [comment]
@porryanes which file is the translation scripts? I suppose I have the same problem but in the Portuguese translation.

**Comment by porryanes** [comment]
@PlaMG0D 
Probably a file with a name containing game in a directory in `DDLC-1.1.1-pc/game/tl/`.

If you give me the repository of the translation project, I can give you more reliable information.

**Comment by PlaMG0D** [comment]
[zz_games.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7043864/zz_games.zip)
It's this one? the zz_games i suppose

**Comment by porryanes** [comment]
@PlaMG0D 
Is there a file with the same name but with the extension `rpy`?

**Comment by PlaMG0D** [comment]
Yes, I've found and fixed it (I hope so), some line in the translation prevented the button from appearing but now I've corrected it.
![image](https://user-images.githubusercontent.com/88963342/130731803-6a1bc778-3d74-45cc-ac0d-f448f43cdf17.png)
![image](https://user-images.githubusercontent.com/88963342/130731825-482d9064-5cf8-4cc5-b262-53b17fc82adb.png)

Thanks for the comments, they helped a lot!

**Comment by porryanes** [comment]
I'm so glad you were able to fix it.
You're welcome!

**Comment by Dudlidadd** [comment]
Hello, there was the same problem, I don't quite understand how to solve it. . . although probably no one will help me here, too much time has passed
