### ISSUE TITLE
Monika Coffee Gift

### ISSUE THREAD

**Issue by shrk0** [Monika-After-Story/MonikaModDev#7515]
So, I gave Monika the coffee gift, and she actually can read it and thanks me, but I can't see a mug on her desk. Why does this happen? It's an error or I have to wait for something?
My affection level is 76.7

**Comment by lunulae** [comment]
Monika will brew the coffee herself sometimes when you visit her in the morning. Gifting it to her replenishes the stock that she can make, so she can run out if you haven't given her any in a long time.

**Comment by shrk0** [comment]
thank you so much
