### ISSUE TITLE
[Suggestion] Change “You’re awesome at Pong” Compliment

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7516]
I don't know if it's just a me thing but like it's so irritating for some reason. I'll put this into a scenario to better illustrate my point. So, typically the only time you'd basically use this compliment is if she wins at Pong, right? So two scenarios, one where she wins a bunch, and one where you win but she wins towards the end or makes a good play. Monika then hits you with the "well it's really simple and easy" and it turns into either a petty shot at the player or a passive aggressive response respectively.

**Comment by xXMidnight** [comment]
lol I agree

**Comment by ThePotatoGuy** [comment]
yeah, she says  "pong isn't exactly a complex game", which has moments where it can be condescending. I think some variety on her opening statements in that compliment would be better.

[closing until we look into it]
