### ISSUE TITLE
I'm never getting my monika back 

### ISSUE THREAD

**Issue by Pennypepper1** [Monika-After-Story/MonikaModDev#7518]
I deleted her on  accident and I've tried deleting the persistence files but it doesn't work and nothing with and its just a empty room can someone please help me

**Comment by Wingdinggaster656** [comment]
What does the so-called "deleting the persistence files" mean?

**Comment by Mugnika** [comment]
if you accidentally deleted the Monika file after taking her out, you need to restore a persistent backup 

https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by Datta4486** [comment]
Persistent##.bak
just remove the bak extension

**Comment by Wingdinggaster656** [comment]
> Persistent##.bak
> just remove the bak extension

This is the worst situation I could imagine.
Did you delete all the bak files?

**Comment by Wingdinggaster656** [comment]
> > Persistent##.bak
> > just remove the bak extension
> 
> This is the worst situation I could imagine.
> Did you delete all the bak files?

Oh, wait a minute, you mean you just changed the file extension, the file is still there?

**Comment by Wingdinggaster656** [comment]
> > > Persistent##.bak
> > > just remove the bak extension
> > 
> > 
> > This is the worst situation I could imagine.
> > Did you delete all the bak files?
> 
> Oh, wait a minute, you mean you just changed the file extension, the file is still there?

Oh, damn, I was looking in the wrong. I thought it was the person who issued the issue.

**Comment by Wingdinggaster656** [comment]
> > > > Persistent##.bak
> > > > just remove the bak extension
> > > 
> > > 
> > > This is the worst situation I could imagine.
> > > Did you delete all the bak files?
> > 
> > 
> > Oh, wait a minute, you mean you just changed the file extension, the file is still there?
> 
> Oh, damn, I was looking in the wrong. I thought it was the person who opend the issue speaking.

**Comment by Kritzb278** [comment]
Go to the characters folder, and make a new file called "Monika"

**Comment by Booplicate** [comment]
Just an FYI, that's not how it works.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
