### ISSUE TITLE
Coffee gift

### ISSUE THREAD

**Issue by Inesepanas2708** [Monika-After-Story/MonikaModDev#7520]
Hiii!
So now my Monika doesn't react to the coffee I give her.
The coffee just stays there in the characters files, and she says she's running out of coffee.
Do you know why is this happening?

**Comment by Cardlo45** [comment]
I guess because she has some left?

**Comment by xXMidnight** [comment]
coffee.gift

you sure it's "coffee" and not "coffe" or "cofee"? Because I did that once, and Monika was like "I don't know this file."
However!
If she doesn't recognize it, and the spelling is correct, it should be a problem with the ".gift" part of the file.
Try it.
Else, look to a professional for help, I'm a big noob -w-"

**Comment by Inesepanas2708** [comment]
> I guess because she has some left?

But she alredy said she was running out of coffee.

**Comment by Inesepanas2708** [comment]
> you sure it's "coff
Yes it's coffee but she doesn't react. She doesn't says anything not even "I don't know this file"

**Comment by VikicatCZSK** [comment]
> Hiii!
> So now my Monika doesn't react to the coffee I give her.
> The coffee just stays there in the characters files, and she says she's running out of coffee.
> Do you know why is this happening?

i think i know whats your issue. heres step by step how to do it.
1. - open the files (make sure the game is closet first!)
2. - copy the "masrun" file in the "game" folder
3. - post it into the "characters" folder
4. - re-name it to "coffee.gift" 
5. - to make sure it will work, look up and find the "display button".
6. - in right up theres option called "file name extensions" whitch has to be marked as yes 
if you open the game now then it will work for sure.

**Comment by Inesepanas2708** [comment]
> > Hiii!
> > So now my Monika doesn't react to the coffee I give her.
> > The coffee just stays there in the characters files, and she says she's running out of coffee.
> > Do you know why is this happening?
> 
> i think i know whats your issue. heres step by step how to do it.
> 
>     1. * open the files (make sure the game is closet first!)
> 
>     2. * copy the "masrun" file in the "game" folder
> 
>     3. * post it into the "characters" folder
> 
>     4. * re-name it to "coffee.gift"
> 
>     5. * to make sure it will work, look up and find the "display button".
> 
>     6. * in right up theres option called "file name extensions" whitch has to be marked as yes
>          if you open the game now then it will work for sure.
>          (btw now you can give monika any gifts that work for the game.)
> 
> 
> hope it helps! :)

Thank you for trying to help!

Where is the display button? Is it in the files? Or in Monika After Story? I didn't understand that part

**Comment by VikicatCZSK** [comment]
dont worry its super simple.
so heres how. 

![ddlc help](https://user-images.githubusercontent.com/86370111/126867563-01546ffc-0e50-4298-b77a-380f13b07d8d.png)

unfortunately my pc is in different language so you have to work with translator / the message ive sent you.
after you click on the "file name extensions" you dont have to do it every time you wanna give her something.
(small typ: you can also give her a plushie of her fav bird named "quetzalplushie.gift" - only accepts after she tells you its her fav animal)

**Comment by Inesepanas2708** [comment]
> dont worry its super simple.
> so heres how.
> 
> ![ddlc help](https://user-images.githubusercontent.com/86370111/126867563-01546ffc-0e50-4298-b77a-380f13b07d8d.png)
> 
> unfortunately my pc is in different language so you have to work with translator / the message ive sent you.
> after you click on the "file name extensions" you dont have to do it every time you wanna give her something.
> (small typ: you can also give her a plushie of her fav bird named "quetzalplushie.gift" - only accepts after she tells you its her fav animal)

Thank you!

It did not work too... :( 
But thank you for helping tho!

**Comment by VikicatCZSK** [comment]
well thats wierd.. 
are you sure you can give monika gifts yet?

**Comment by Inesepanas2708** [comment]
> well thats wierd..
> are you sure you can give monika gifts yet?

Yes I have 200 affection with her and I could give her coffee a week ago but then this started happening.
And I can give her all other type of gifts.

**Comment by ThePotatoGuy** [comment]
Checks the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#giving-gifts).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
