### ISSUE TITLE
[Suggestion] Make Monika's Nickname show in the Pong screen

### ISSUE THREAD

**Issue by Danielshmaniel** [Monika-After-Story/MonikaModDev#7522]
This is a simple suggestion to replace Monika's name with the nickname given by the player on the Pong screen. I hope I explained well.

**Comment by xXMidnight** [comment]
I agree. I called my Monika "Nova" (weird name, ik, but reasons) and it's always Monika on the pong screen

**Comment by multimokia** [comment]
The issue is names like `Love`, or `Darling`, `Sweetheart` etc. In which case they don't really act like an identifier or really work in that place, which is why it's not used there

**Comment by Danielshmaniel** [comment]
True

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
