### ISSUE TITLE
Option to notify Monika that I work at night and sleep during the day

### ISSUE THREAD

**Issue by PresidentIrina** [Monika-After-Story/MonikaModDev#7523]
I work a night shift, and sleep during the day. It would be nice to be able to notify Monika of this so she doesn't always chaste me for staying up all night.

**Comment by xXMidnight** [comment]
true

**Comment by Datta4486** [comment]
ye

**Comment by CrewieAustin** [comment]
I don't know will this work, but does telling her that you need to go to work at the night works ??

**Comment by Rai99** [comment]
#4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
