### ISSUE TITLE
where is the file that marks nicknames as cute, awkward, etc?

### ISSUE THREAD

**Issue by D1anners** [Monika-After-Story/MonikaModDev#7524]
i wanted to add some nicknames for her to react to but i can't find the darn thing

**Comment by xXMidnight** [comment]
xD aight aight, it's in...

...the game folder.

What? You wanted the location!

jk jk I don't know where the folder is either

**Comment by username11421** [comment]
script-story-events.rpy

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
