### ISSUE TITLE
Piano not unlocking 

### ISSUE THREAD

**Issue by poke2048** [Monika-After-Story/MonikaModDev#7525]
So I have been playing for a little over a month now affection level over 500 and about 8 days worth of hours and the piano game refuses to unlock not sure what to do.

**Comment by ThePotatoGuy** [comment]
piano takes some time to unlock - more than you would expect.

If you're fine with spoilers, we can calculate your estimated unlock date based on your current habits. We would need your [ev_dump](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#ev_dump) file.

**Comment by poke2048** [comment]
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/6851717/ev_dump.log)

**Comment by ThePotatoGuy** [comment]
Your stats say you should have it unlocked by now. Can you upload your [persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#persistent) here?

**Comment by poke2048** [comment]
Where do I find that?

**Comment by ThePotatoGuy** [comment]
There is link to how to find it in my previous comment.

**Comment by poke2048** [comment]
Whenever I try to upload it I get a message saying "we don't support that type of file"

**Comment by ThePotatoGuy** [comment]
As mentioned in the link, "If posting to github, you will need to zip the file first before attaching it to a github comment."

**Comment by poke2048** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6851901/persistent.zip)
There you go sorry about that

**Comment by xXMidnight** [comment]
this is confusing

**Comment by poke2048** [comment]
Well I just unlocked it so thanks anyways
