### ISSUE TITLE
A bug with "goodbye" phrase

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [Monika-After-Story/MonikaModDev#7526]
The game does not close automatically after saying "goodbye" to Monika. I have no idea what causes this bug. Can you help me?

**Comment by xXMidnight** [comment]
uh...

q-q never had this bug before

**Comment by ThePotatoGuy** [comment]
What do you mean by it does not close automatically? What happens?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
