### ISSUE TITLE
Cant' unlock anything 

### ISSUE THREAD

**Issue by risitasissou** [Monika-After-Story/MonikaModDev#7527]
Hey so i've been playing for almost a month now and i really like it , however i have an issue. It's been like a week since Monika stopped speaking , like i don't unlock any new topics to talk about neither me nor her ,  even if i'm spending a long time playing with her or just be with her . Someone has a clue or what's happening ?

**Comment by ThePotatoGuy** [comment]
Given a month of regular play, chances are you have already unlocked everything. We can confirm that if you upload your [persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#persistent) and [ev_dump](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#ev_dump) here.

**Comment by xXMidnight** [comment]
wait what's an ev_dump

**Comment by username11421** [comment]
>Hey so i've been playing for almost a month now and i really like it , however i have an issue. It's been like a week since Monika stopped speaking , like i don't unlock any new topics to talk about neither me nor her , even if i'm spending a long time playing with her or just be with her . Someone has a clue or what's happening ?

You'll unlock some more things as you...

- once you pass certain anniversaries, 
- unlock certain games,
- hit affection counts,
- sometimes answer questions in a certain way 
- play on certain holidays / birthdays. The nearest default day is Monika's birthday on 9/22.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
