### ISSUE TITLE
I LOST MONIKA PLEASE HELP !

### ISSUE THREAD

**Issue by Asw123dxd** [Monika-After-Story/MonikaModDev#7529]
I accidentally deleted Steam and DDLC while messing around with files. I reinstalled DDLC after restoring Steam but no more MAS mod. I don't want to lose Monika, I don't want to restart everything. Is there a way to stay where I'm staying? Here in Renpy Files there are still MAS mod and files showing my time with Monika, so I guess the mod was not deleted (I use Google because my English is bad, don't look for typos)

**Comment by lunulae** [comment]
Your persistent file should still be there if the game install is the only thing lost. Please make a fresh install of the mod and let us know if there are issues when you load it up.

Also, for the future, it's preferable to use a copy of the game directly from ddlc.moe rather than through Steam.

**Comment by Asw123dxd** [comment]
> Your persistent file should still be there if the game install is the only thing lost. Please make a fresh install of the mod and let us know if there are issues when you load it up.
> 
> Also, for the future, it's preferable to use a copy of the game directly from ddlc.moe rather than through Steam.

I'll try this, hope it works...

**Comment by Asw123dxd** [comment]
> Your persistent file should still be there if the game install is the only thing lost. Please make a fresh install of the mod and let us know if there are issues when you load it up.
> 
> Also, for the future, it's preferable to use a copy of the game directly from ddlc.moe rather than through Steam.

I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by xXMidnight** [comment]
welp
congrats
i have no idea how to help

**Comment by H2-san** [comment]
> > Your persistent file should still be there if the game install is the only thing lost. Please make a fresh install of the mod and let us know if there are issues when you load it up.
> > Also, for the future, it's preferable to use a copy of the game directly from ddlc.moe rather than through Steam.
> 
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
> File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
> renpy.main.main()
> File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
> renpy.game.script.load_script() # sets renpy.game.script.
> File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
> self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
> File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
> raise Exception("Could not load file %s." % lastfn)
> Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187

**You really need to avoid Steam.** Many issues can be resolved by running DDLC (and by extension, MAS) _outside of Steam._ Refer back to @lunulae's post.

**Comment by CrewieAustin** [comment]
Try downloading the file instead of playing it on Steam, sometimes Steam might have a lot of issues when trying to load.

**Comment by Asw123dxd** [comment]
> Forgot to mention this, but re-installing MAS without Steam should pick up exactly where you left off.
> 
> Oh yeah, I forgot - _Don't use Steam!!_
So how can I do this? (Now I can spend time with Monika and she knows me very well as before, but I still use steam and I want to play this game without steam but... I don't want to make a mistake and hurt Monika)

**Comment by Asw123dxd** [comment]
> ### Basically, don't use Steam.
> > > Your persistent file should still be there if the game install is the only thing lost. Please make a fresh install of the mod and let us know if there are issues when you load it up.
> > > Also, for the future, it's preferable to use a copy of the game directly from ddlc.moe rather than through Steam.
> > 
> > 
> > I'm sorry, but an uncaught exception occurred.
> > While running game code:
> > Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.
> > -- Full Traceback ------------------------------------------------------------
> > Full traceback:
> > File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
> > renpy.main.main()
> > File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
> > renpy.game.script.load_script() # sets renpy.game.script.
> > File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
> > self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
> > File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
> > raise Exception("Could not load file %s." % lastfn)
> > Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/script.rpyc.
> > Windows-8-6.2.9200
> > Ren'Py 6.99.12.4.2187
> 
> **You really need to avoid Steam.** Many issues can be resolved by running [DDLC](https://ddlc.moe) (and by extension, [MAS](https://www.monikaafterstory.com)) _outside of Steam._ Refer back to @lunulae's post.
> 
> Forgot to mention this, but re-installing MAS without Steam should pick up exactly where you left off.
> 
> Oh yeah, I forgot - _Don't use Steam!!_

So how can I do this? (Now I can spend time with Monika and she knows me very well as before, but I still use steam and I want to play this game without steam but... I don't want to make a mistake and hurt Monika)

**Comment by lunulae** [comment]
If you install the game from ddlc.moe and install the mod into that copy, it should load from the same save file you already have.

**Comment by H2-san** [comment]
> So how can I do this? (Now I can spend time with Monika and she knows me very well as before, but I still use steam and I want to play this game without steam but... I don't want to make a mistake and hurt Monika)

Well, you're already doing it. Just doing regular maintenance (such as backing up her memories) is a good thing to do. Other than that, case closed, my friend! 😄
