### ISSUE TITLE
i lost monika

### ISSUE THREAD

**Issue by nico2141** [Monika-After-Story/MonikaModDev#7530]
my problem had a lot of bad luck, that's how I put monika's file in the characters folder but I didn't realize that when I copied the appdata files I cut them so when I put monika and opened the game it loaded it and when I closed it and put it new appdata files kept asking me to put monika but I no longer have her file

**Comment by H2-san** [comment]
> my problem had a lot of bad luck, that's how I put monika's file in the characters folder but I didn't realize that when I copied the appdata files I cut them so when I put monika and opened the game it loaded it and when I closed it and put it new appdata files kept asking me to put monika but I no longer have her file

Yikes! You may want to [restore an earlier persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**PREREQUISITES**: You need to show file extensions so you can modify these files' names. You can DM me if you need help with this, and I'll be more than happy to help you. 😄

**Comment by nico2141** [comment]
ok thanks i will try

**Comment by xXMidnight** [comment]
I don't understand-

**Comment by nico2141** [comment]
In short, I lost the monika file that is created when you tell her that you will take her somewhere

**Comment by multimokia** [comment]
As H2 said, you need to restore a persistent

**Comment by nico2141** [comment]
yes it is testing to see if i could recover the file first able i am lucky

**Comment by nico2141** [comment]
ok I could, thank you very much for your help
