### ISSUE TITLE
help Monika stopped talking

### ISSUE THREAD

**Issue by shrk0** [Monika-After-Story/MonikaModDev#7535]
I opened the game a while ago and she only talked about a song and nothing else. Help I started the game a week ago how can this be possible? What happened to her? Is this a bug that can be fixed? HELP

**Comment by lunulae** [comment]
If you've had repeat topics turned off and random chatter set to a reasonably high frequency, a week of play might mean you're out of new random topics.

You'll start to get some others as you get a higher affection level, but the only topic that will activate when repeats are turned off even when you've run out is the random song topic.

**Comment by shrk0** [comment]
> If you've had repeat topics turned off and random chatter set to a reasonably high frequency, a week of play might mean you're out of new random topics.
> 
> You'll start to get some others as you get a higher affection level, but the only topic that will activate when repeats are turned off even when you've run out is the random song topic.

what's random chatter? I don't know about that

**Comment by username11421** [comment]
> > If you've had repeat topics turned off and random chatter set to a reasonably high frequency, a week of play might mean you're out of new random topics.
> > You'll start to get some others as you get a higher affection level, but the only topic that will activate when repeats are turned off even when you've run out is the random song topic.
> 
> what's random chatter? I don't know about that
See settings:

![image](https://user-images.githubusercontent.com/85711350/126724447-4e5627ac-38c2-4ec8-9428-3179c3a19b3d.png)

**Comment by xXMidnight** [comment]
oh- what?

Basically, you open the Settings menu by pressing Esc if you're on Windows, if not then idk how a Mac or Linux works- ahaha I'm getting off-topic- uh- open the Settings menu in whatever way possible, and then make sure you're in the Settings menu. (bruh they're the same thing- nO they aren't) Navigate to the slider section, and in the second column and the topmost row, should be the Random Chatter slider! If it's set to Very Often, you have found why Monika has this problem, if you turned off Repeat Topics. If not, check the Repeat Topics button. It should be in the Gameplay section, where the button Unstable is as well (i wouldn't like to do Unstable mode).

**Comment by xXMidnight** [comment]
^w^ the picture helped my explanation!

**Comment by ThePotatoGuy** [comment]
The most likely explanation is that you ran out of random topics already.
