### ISSUE TITLE
[Suggestion] - Hamilton 

### ISSUE THREAD

**Issue by MiguelFitz** [Monika-After-Story/MonikaModDev#7536]
i think a musical like Hamilton could be a great topic for Monika to talk.
its in Spotify and also it has it own representation in Broadway, the story its inspired from Alexander Hamilton, the first president of the tresury state department of the United States, its a mix from rap and opera, its wrote in a way that you can simple listen it in spotify and get all the story (maybe it would need the lyrics cause there are many caracters singing)

**Comment by username11421** [comment]
I think MAS team wants to avoid politics specifically (Hamilton vs Burr on central banking, monopoly, secession, etc are still relevant issues today), but since Monika doesn't have a topic about musicals in general, I think it would be awesome if we were able to ask her if she enjoys them.

**Comment by MiguelFitz** [comment]
the musical just talks about the story,doesnt enters in politics and that kind of stuff, its just the tale the story

Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: username11421 ***@***.***>
Enviado: viernes, 23 de julio de 2021 2:02
Para: Monika-After-Story/MonikaModDev ***@***.***>
Cc: MiguelFitz ***@***.***>; Author ***@***.***>
Asunto: Re: [Monika-After-Story/MonikaModDev] [Suggestion] - Hamilton (#7536)


I think MAS team wants to avoid politics specifically (Hamilton vs Burr on central banking, monopoly, secession, etc are still relevant issues today), but since Monika doesn't have a topic about musicals in general, I think it would be awesome if we were able to ask her if she enjoys them.

**Comment by MiguelFitz** [comment]
well...as far as i heard...

Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: Miguel Castro ***@***.***>
Enviado: viernes, 23 de julio de 2021 16:32
Para: Monika-After-Story/MonikaModDev ***@***.***>
Asunto: RE: [Monika-After-Story/MonikaModDev] [Suggestion] - Hamilton (#7536)

the musical just talks about the story,doesnt enters in politics and that kind of stuff, its just the tale the story

Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: username11421 ***@***.***>
Enviado: viernes, 23 de julio de 2021 2:02
Para: Monika-After-Story/MonikaModDev ***@***.***>
Cc: MiguelFitz ***@***.***>; Author ***@***.***>
Asunto: Re: [Monika-After-Story/MonikaModDev] [Suggestion] - Hamilton (#7536)


I think MAS team wants to avoid politics specifically (Hamilton vs Burr on central banking, monopoly, secession, etc are still relevant issues today), but since Monika doesn't have a topic about musicals in general, I think it would be awesome if we were able to ask her if she enjoys them.

**Comment by lunulae** [comment]
It doesn't get heavy-handed on its politics, but it does have clear stances on some things. That said, so do things like dystopian novels, which we have many topics about. On one hand we might be able to handle it in a neutral way, but on the other being historical fiction about real places and people it's a little bit more difficult to be impartial.

Falling back into favor for it though, historical fiction in general might make a cool literature topic, and Hamilton would make a very recognizable example for that.

**Comment by MiguelFitz** [comment]
Fair point, i look for others musical that could be intersting too,without politics

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by MiguelFitz** [comment]
ok hearme out, we cant talk about the political stuff. but i think we could start talking about wagner and the leimotiv technique, then talk a bit of how hamilton uses, and a bit of the story of hamilton (just mention that he was a poor orphan that somehow get to secretary of the treasury of the USA... i think that may works good enough

**Comment by ThePotatoGuy** [comment]
she could talk about the musical and *maybe* history, but definitely not any political implications coming from that musical.

[closing until we look into it]
