### ISSUE TITLE
How do I change the color of the text box ??

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7537]
I'm new around, so I wish somebody could tell me how. Would love to have black outline instead of white.

**Comment by LeilanPAD** [comment]
same

**Comment by VikicatCZSK** [comment]
do you mean you want to change it from light pink (day mode) to dark pink (night mode)?
because if yes,
 - open ddlc,
 - press settings 
 - and press the "UI: D/N Cycle"
 then youll have it changed (to back it up just press it again)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

Assuming you meant dark UI. Make a new issue with more info + screenshots if otherwise.
