### ISSUE TITLE
Anyone here can help me make a Blue Hoodie for Monika ?

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7538]
I know there's a green one exist already, but I would like to have a Blue one. If anyone has it, please give me one. I would be appreciated.

**Comment by username11421** [comment]
I'm not sure if one exists. You could make an art request on Reddit or offer someone a small amount of money on a gig site like Fiver to create one. You might also just be able to recolor the green one in Gimp or Photoshop.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
