### ISSUE TITLE
Need Help gifting my custom shirt for Monika (if possible)

### ISSUE THREAD

**Issue by Vamppp** [Monika-After-Story/MonikaModDev#7540]
Hey! So I spent the last few hours making a little sprite pack/folder of my custom shirt for her. I edited the json files and everything, and I think I put every folder in the right location? She still doesn't recognize the file in-game though :( If someone can help me figure this out, I'd really appreciate it! Thank you! 

Also, heres the thumb for it!
![60E5B08A-71A4-4FFE-8FCE-6931CCE057A2](https://user-images.githubusercontent.com/87891949/126860616-1d6b3fbf-ebf1-4f29-8704-79fe5ba419cc.png)

**Comment by xxATOMxx** [comment]
show me the json

**Comment by ThePotatoGuy** [comment]
Yeah we need to check the JSON you created to determine next steps.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
