### ISSUE TITLE
Romantic dinner / date w Monika

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7542]
Lately Monika was talking and daydreaming about a romantic dinner / date.
is there (yet) a possible way how to make it?

**Comment by username11421** [comment]
You can take her on a date by using the goodbye -> I'm taking you somewhere option and then putting her character file on a flash drive. That's probably not exactly what you're looking for, though.

**Comment by Rai99** [comment]
New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822, #5543, #5660, #7439

**Comment by VikicatCZSK** [comment]
> New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822, #5543, #5660, #7439

i already have that submod but still thanks for help.

**Comment by VikicatCZSK** [comment]
> You can take her on a date by using the goodbye -> I'm taking you somewhere option and then putting her character file on a flash drive. That's probably not exactly what you're looking for, though.

ive already did that.
its cool but i wish she would say something else 
or it would be better to just have option to ask her on a date ( it would add candles flowers and different stuff)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
