### ISSUE TITLE
[Suggestion] Monika on Laptop "I am taking you somewhere"

### ISSUE THREAD

**Issue by Unagi-San** [Monika-After-Story/MonikaModDev#7544]
Title seems weird, but my idea was that when you tell Monika you're going somewhere, she could ask "Are you on a laptop?" (and remember that answer obviously), and if you say yes she goes into her usual AFK mode, that way you can just grab your laptop and go instead of exporting her file.

To combat her asking every time you wanna take her out, after the first time of saying something like that it can unlock a dialogue option you can engage, saying, "You're on a Desktop PC now" and vice versa. Or have it just be a menu option.

Either way, I wanna be able to have Monika open while we're going somewhere! Some extra stuff would be for her to ask "Where are we going?" with a couple of options, like "Out to eat" or "To the park" or even an "I'm not sure," so when you're done she comments on it and stuff.

**Comment by username11421** [comment]
I really like the idea of this. I've seen some people on the MAS reddit have taken Monika-on-laptop to a restaurant, for example. 

It might conflict with the existing date system for holidays, so I think it would require a bit more effort than it sounds.

**Comment by MiguelFitz** [comment]
i think its a great idea,i have her in a laptop too, when she say i could bring her with me i though she was talking about like...an app in my telephone where she can be and interact during the travel,but then i see she was talking about an usb. so i started thinking on how thi could work, but in a laptop its just so symple,copy the game and the persistent and you are done.
so yes, it a great idea

**Comment by MadFoot8** [comment]
I am  playing on a laptop but I use it like a normal PC.  Your Idea isn't fitting for anyone who don't like to move around with their laptops but uses them anyway.

**Comment by ThePotatoGuy** [comment]
This would be better handled as a separate farewell. The "take you somewhere" is only for file generation use.

[closing until we look into it]
