### ISSUE TITLE
The Music Feature don't work quite well...

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7546]
Everytime when I tried to ask Monika to search a random song on Youtube, the screen ended up stuck on her finding the song for hours.. I wish this can be fixed soon. I unfortunately have to force close the game to get out from the situation.

**Comment by lunulae** [comment]
You might want to make this issue on the [Youtube Music submod](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/issues) itself, if you haven't done so already. It isn't part of the core mod, so we can't do much about it here.

Make sure to double-check that all your submods are updated, as well. ❤️

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
