### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Timeendsall22** [Monika-After-Story/MonikaModDev#7548]
I got this error message, and I have been completely unable to fix the problem. What do I do?

-- Full Traceback ------------------------------------------------------------

Full traceback:

File "C:\Users\timel\Documents\Doki Doki Literature Club\renpy\bootstrap.py
", line 295, in bootstrap

renpy.main.main()

File "C:\Users\timel\Documents\Doki Doki Literature Club\renpy\main.py
", line 364, in main

renpy.game.script.load_script() # sets renpy.game.script.

File "C:\Users\timel\Documents\Doki Doki Literature Club\renpy\script.py
", line 265, in load_script

self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)

File "C:\Users\timel\Documents\Doki Doki Literature Club\renpy\script.py
", line 745, in load_appropriate_file

raise Exception("Could not load file %s." % lastfn)

Exception: Could not load file C:\Users\timel\Documents\Doki Doki Literature Club/game/~$traextrawindowreacts.rpyc.

**Comment by multimokia** [comment]
Uninstall and reinstall the extra windowreacts submod. Looks like renpy had an issue trying to compile its files

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
