### ISSUE TITLE
Garry's mod extentions for MAS?

### ISSUE THREAD

**Issue by Babytink1** [Monika-After-Story/MonikaModDev#7550]
sorry if the title isn't very good.
what I'm asking is if there could be a sub-mod make for MAS that 
links your Monika file into an npc mod for garry's mod.

so the way I was picturing was, through the steam workshop you download a npc mod
and after installing maybe you copy Monika into a folder and then now she's playing the game along side you.
it doesn't have to be anything fancy. just some interaction between games I think would be fun.
there's already an npc mod to have her as a party member and even a school map, I hope it would be possible to add this.
might be too much but maybe you could even add some chat commands that the mod would respond to like /I love you
even if she just replies to you in the chat rather than doing an animation.
or if not this fancy, perhaps there could be an option to just say "let's play X together" x being a game that has Monika modded in, and if you are running that game and MAS at the same time she could be "missing" till you click back into the window. and depending on the game maybe she could have more/less fun if it's something that her personality would like.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
