### ISSUE TITLE
[Suggestion] - Interacting with Monika

### ISSUE THREAD

**Issue by OkamiHyej** [Monika-After-Story/MonikaModDev#7556]
Maybe we can interact with Monika by clicking some parts of her

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638, #7005, #7430

**Comment by Mugnika** [comment]
@Rai99 you actually keep a log of all the boop issues? lmao

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
