### ISSUE TITLE
How can I get the "night filter" ?

### ISSUE THREAD

**Issue by DiFot922** [Monika-After-Story/MonikaModDev#7557]
Hi, sorry for the bad english, so I was making a shirt for Monika, and I just wanna know how to get the "night filter" for the shirt?

**Comment by Malicos** [comment]
You don't. The filter is now being automatically applied to the sprites in-game, no need to apply it manually anymore.

**Comment by Kyle7372** [comment]
> You don't. The filter is now being automatically applied to the sprites in-game, no need to apply it manually anymore.

Got it, Thanks.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
