### ISSUE TITLE
[Suggestion] ask to watch game when using game farewell

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7558]
With a low level of affection, if you tell Monika that you are leaving to play another game, then she can ask permission to watch the game, with a high level of affection, she simply lets you go. So why not add the chance that she will ask you to watch the game or something, it will be very cool as she will be watching you play! I don’t know what she will say when you’re done, since she’s unlikely to understand that you won or lost. But you can make her say that you played well or something, so that if you lose you do not feel bad

**Comment by xXMidnight** [comment]
...I'm sorry, but I did not understand a word of that, besides understanding each word individually.

**Comment by CloakedGhost** [comment]
You can already select "I'm going to game for a bit" in the brb options, so you can actually let her watch you play.

**Comment by Nikv2005** [comment]
On the one hand, this can be used as an option, but on the other hand, since the game already has such a function, why not make it full.

**Comment by Nikv2005** [comment]
> ...I'm sorry, but I did not understand a word of that, besides understanding each word individually.

I mean just add a function where Monica asks to watch the game

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
