### ISSUE TITLE
[Suggestion] Doki Doki Snacc Club

### ISSUE THREAD

**Issue by Kritzb278** [Monika-After-Story/MonikaModDev#7559]
Okay, we all know how Natsuki makes goddess level cupcakes and Monika wants to learn how to make 'em. The idea for this came from #7472, which stated that the player should be able to give Monika the recipe, and maybe some ingredients too.

If you go to issue #7472, you can see I suggested giving it to her as a .gift file as in ### recipe.gift or ### natsukicupcakerecipe.gift. But, this got me thinking. What if we could give Monika recipes other than the cupcakes?

- Yuri makes tea that tastes like heaven, so perhaps giving Monika her tea recipe is a nice idea. I know Monika prefers coffee, but I'm sure she wouldn't complain if we give her tea.
- Natsuki's vanilla and chocolate cookies are Sayori-approved, so adding that isn't a bad idea.

I know I said giving recipes in a .gift file would be ideal, but now I was thinking about giving recipes and ingredients a new extention entirely?
Just think about it:

- cupcake.recipe
- tea.recipe
- vanillacookie.recipe
- chocolate.recipe

Of course, the names are subjectable, but .recipe extentions really seem like an efficient way to introduce snaccs.

**Comment by ThePotatoGuy** [comment]
my comment on that issue still stands - hard to react to the contents of the recipe, if that is desired functionality. 

[closing until we look into it]
