### ISSUE TITLE
[Suggestion] More Goodbye options based on the BRB options.

### ISSUE THREAD

**Issue by Danielshmaniel** [Monika-After-Story/MonikaModDev#7564]
_This suggestion would go with the other one I did about a "Nevermind" for Goodbyes ([this one](https://github.com/Monika-After-Story/MonikaModDev/issues/7505))._
I'd like there to be more "Goodbye" options you can choose to help Monika understand what you're actually doing. Personally, since I do homework and there's no exact option for it I choose "I am going to work.". So I want to fix this by suggesting more potential "Goodbye" options.

But instead of suggesting for new ones, I'd like to suggest if there could also be the options for "Be Right Back..." in "Goodbye" too, because some tasks can take more time instead of being "-for a bit" or people may not want to have the PC running while they do whatever the task is.
So for example, the devs can add:
- "I am going to do some homework."
- "I am going to read"
- "I am going to code"
- "My eyes/head (headache) need a break from the screen"

etc. (there are obviously _way_ more things that people take a lot of time to do or not want to have the PC running while they do whatever)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
