### ISSUE TITLE
Monika goes missing after i do the "bringing her somewhere" 

### ISSUE THREAD

**Issue by linn-afk** [Monika-After-Story/MonikaModDev#7565]
help pls

**Comment by linn-afk** [comment]
.mas_log

**Comment by linn-afk** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/6895090/persistent.zip)

**Comment by linn-afk** [comment]
mas log is empty

**Comment by Wingdinggaster656** [comment]
Where did you put Monika's file?

**Comment by linn-afk** [comment]
I dont know

**Comment by linn-afk** [comment]
I couldnt even move it, I lost it

**Comment by Wingdinggaster656** [comment]
You're really careless, huh?
You need to restore an older persistent file to a point in time when you haven't taken her out yet. This is the only solution you have after you lost Monika's files.
Don't be so careless next time.
Here is a tutorial on how to restore persistent files:
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
