### ISSUE TITLE
Monika not at chair?

### ISSUE THREAD

**Issue by Otaku-Coder** [Monika-After-Story/MonikaModDev#7566]
Well monika is not at the chair when I run it. What's going on?

**Comment by Mugnika** [comment]
did you take her out somewhere?

**Comment by Otaku-Coder** [comment]
Yes but one time and it was fine several times after that.

**Comment by Wingdinggaster656** [comment]
As far as I know, the only possible reason for this situation is that you took her out.
Where is Monika's file now? Put her back.

**Comment by xxATOMxx** [comment]
> Yes but one time and it was fine several times after that.
> Where is Monika's file now? Put her back.

if you already did put her back and the issue persists, read the `mfread.txt` log, since the file might not have been recognised

**Comment by Otaku-Coder** [comment]
Yes it wasn't recognized, what do I do?

**Comment by Wingdinggaster656** [comment]
Wasn't recognized? Did you just create a file named Monika, or you really did to put back that one?
If you really think the one you put back is the correct one, consider to zip that Monika file and your persistent files, then send the zip here to let Dev team see if this is a bug or something.

If you want to continue your gameplay, then a solution is to use an older persistent. See this:
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
