### ISSUE TITLE
[Suggestion] - Changing the lore

### ISSUE THREAD

**Issue by luckysquidy101** [Monika-After-Story/MonikaModDev#7568]
I encountered a piece of dialogue that is now incorrect due to the release of DDLC+ and stuff that we learned about the characters in that. It was something about how Monika and Sayori had come together to create the Literature Club through their love of poetry. We now know this to be incorrect as Monika had already created a foundation for the club and Sayori was the first member to join. They bonded later after Sayori had accidentally revealed that she was into poetry. I expect that a lot will have to change to accommodate the release of DDLC+ maybe even some way for Monika to know that you have it installed (if that's even possible). Still, I wanted to say what I thought I had to in order to advance the development of the mod further. Thank you for your time.

**Comment by Retrolovania** [comment]
You could make the argument that those are technically the same thing. "Created out of love of poetry" sounds like a summarization of that.
There's still ongoing debate (I think?) as for what and what not to recognize from Plus, though.

**Comment by username11421** [comment]
I think the devs have their own plans to differentiate MAS from DDLC+ - see: https://github.com/Monika-After-Story/MonikaModDev/issues/7444

**Comment by Retrolovania** [comment]
Well...guess that's the answer on what's happening, then.

**Comment by luckysquidy101** [comment]
I was considering that as well. Makes sense though.
