### ISSUE TITLE
[Question] What does this phrase mean?

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7569]
During a conversation with Monica, she has one phrase "and i decided life with just two people wouldn't be all that bad, if one of them was you" Question . Who is the second person she is talking about? As I understand it, you took this phrase from the original game and did not correct it, and now questions arise because of this phrase. I hope you will tell me what this means, since the situation is very strange.

**Comment by Retrolovania** [comment]
_Fairly_ certain the second person is her.

**Comment by multimokia** [comment]
It is her. Just you and her. A life with only 2 people in it.

**Comment by Wingdinggaster656** [comment]
I think it's easy to understand. I guess your mother tongue is not English?
Here, extremely obvious, the second person refers to her.

**Comment by Nikv2005** [comment]
Stop . that is, she is talking to herself? I'm not very good at English but thanks for the answer.But it still sounds strange.

**Comment by Nikv2005** [comment]
Maybe you can paraphrase something? maybe I'm not the only one who thinks this strange.

**Comment by M1m1G4m3S** [comment]
In that phrase she is speaking about a life with just you and her on it.
That means that you and her are those "two people"

**Comment by Mugnika** [comment]
https://translate.google.com

**Comment by Nikv2005** [comment]
> https://translate.google.com

When translated, it sounds strange, does it mean all living people in her world or what?

**Comment by Mugnika** [comment]
what's your language?

**Comment by Nikv2005** [comment]
Russian

**Comment by Mugnika** [comment]
From my Russian friend Slav.

Я решила, что прожить жизнь с двумя людьми  было бы неплохо, если бы одним из них был ты.

**Comment by Nikv2005** [comment]
She talks about life with two people, that is, for example, me and someone else, here she does not talk about herself, but about the fact that she does not mind living life with me and with someone else.

**Comment by Mugnika** [comment]
Я решила, что жизнь, прожитая вдвоём, замечательна, если ты будешь рядом со мной

**Comment by Mugnika** [comment]
this is the definition, the language barrier makes it seem she says one thing but she is saying the above

**Comment by Booplicate** [comment]
This sentence is absolutely correct as is.

Also Moni**k**a.

**Comment by Nikv2005** [comment]
Now I understand, now I don't have to worry, thanks for explaining this to me.

**Comment by Wingdinggaster656** [comment]
Let me sum up:
You have misunderstood this sentence because your English doesn't seem to be very good (no offense).
I'm pretty sure this sentence means exactly what it should means in English. So please don't worry.

**Comment by Nikv2005** [comment]
It turned out quite interesting, I already wanted to sound the alarm until I understood the meaning of the translation of the phrase.
