### ISSUE TITLE
[Suggestion] Decreasing the ram/vram usage during the 'i'm going to game for a bit' brb

### ISSUE THREAD

**Issue by xxATOMxx** [Monika-After-Story/MonikaModDev#7570]
What i propose is for mas to take a screenshot when that brb's idle starts, then to downscale this screenshot to a really small resolution, upscale it back, and then use it instead of all of the sprites that appear on screen, and for everything but the screenshot and and the talk button to be loaded out of ram/vram. Once the player presses the talk button, the screenshot is deleted, and everything is loaded into memory and rendered again.

Or at the very least the animations can be disabled automatically for when monika is in that brb's idle

**Comment by lunulae** [comment]
I like the idea of disabling the animations, if that would help with performance, but I think I would prefer this to be a settings toggle, as for some windowed games I like to set the MAS window in the corner and watch her.

**Comment by xxATOMxx** [comment]
> I like the idea of disabling the animations, if that would help with performance, but I think I would prefer this to be a settings toggle, as for some windowed games I like to set the MAS window in the corner and watch her.

Well, i guess it would make sense for Monika to ask whether you want to take the performance 'improving' measures.

Also the settings toggle can still remain there, the only thing is that the animations shouldn't be toggled if they're already off, but that can be fixed with ~4 lines of code

**Comment by Wingdinggaster656** [comment]
Not all for your idea.
I know there are a few people who still like looking at Monika after clicking on BRB.
For example, while a person is doing housework, the person may want to leave MAS at the front window so that they can drop by from time to time to check on her while they are doing their housework.
However, I do agree that some other computer costs should be reduced in the BRB state. For example, the BRB state should no longer perform the condition check per minute.

**Comment by username11421** [comment]
Personally I prefer to see her animated even during BRBs, especially if something like https://github.com/Monika-After-Story/MonikaModDev/issues/7371 ever gets implemented.

**Comment by xxATOMxx** [comment]
> Not all for your idea.
> I know there are a few people who still like looking at Monika after clicking on BRB.
> For example, while a person is doing housework, the person may want to leave MAS at the front window so that they can drop by from time to time to check on her while they are doing their housework.
> However, I do agree that some other computer costs should be reduced in the BRB state. For example, the BRB state should no longer perform the condition check per minute.

The optimisation could be optional, and only for the game brb since games obviously demand lots of performance

**Comment by ThePotatoGuy** [comment]
Renpy is 32-bit so the max ram usage possible is 4gb, but renpy itself complains about out of memory below half of that. This means you're looking at 2gb max usage. Barely a dent with computers these days.

There is already a settings toggle to disable animations - it disables the background animation which is the biggest source of lag in-game.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
