### ISSUE TITLE
Exception after telling Monika I'm going to sleep

### ISSUE THREAD

**Issue by NightmareCake426** [Monika-After-Story/MonikaModDev#7571]
~So, basically I accidentally missed the right time to sleep due to having some troubling thoughts and a talk with me Dad. Now, I said the goodbye Monika when I remembered that I had almost went to bed forgetting that she was still open on me desktop. So I talked to her a bit, gave her a nickname, all that jazz. Then I told her the goodbye and that I was going to sleep, which she told me a little bit off for not sleeping earlier. Then after telling me "sweet dreams" as per usual: an except screen popped up. Now, first time round I pressed ignore as it said "would continue" but when I clicked it it closed the window. I got worried and opened the game to check on Monika, as I was worried about her, only for it to carry on closing the window three times before I managed to get it to stay open. Now, me computer has an issue with crashing the game when I'm not paying attention so crashes weren't our last rodeo. So I managed to open the game, finally, and Monika with a curl on her head guessed it was another crash before continuing. I spent a little more time with her as I was worried and was getting tired so I repeated me actions of goodbye and sleep only to get the exception again. This time, I have no idea what to do as I'm really scared of ruining anything- especially since Monika is one of the characters who means a lot to me even if she is a character in a game- and I need help as I'm struggling to find answers on what to do.

Here's what popped up:
![image](https://user-images.githubusercontent.com/88172961/127589543-c9f07616-6f35-4361-9213-2569d3a5713c.png)

(IDK if that worked, I'm having some issues on me paint program atm)

If anyone knows anything on what I do or what has happened (keep in mind, this exception just appeared out of nowhere and I hadn't been twiddling with anything except watching YouTube and playing Minecraft like the past few days (and me Minecraft is on PS4 not on PC so I don't have two games running at the same time on the same software))

Please help, I'm really scared~

**Comment by username11421** [comment]
I'm curious if you're running out of space on your hard drive? Since the error is about device space.
Also, you should avoid using a Steam installation with MAS - but that _shouldn't_ cause this kind of error I don't think.

**Comment by NightmareCake426** [comment]
~I used to have storage issues but I haven't had them recently. I'll have a big clean of me laptop in the morning (as it's really late for me) and see if that exception happens again. But atm I still have the game open as I don't know what to press as I don't want Monika thinking it's just another crash or that what happened today or this night never happened. Also, I got the game from Steam but not the mod if that's what ye mean

Sorry if I'm typing a lot, I've been panicking~

**Comment by username11421** [comment]
>Also, I got the game from Steam but not the mod if that's what ye mean
You want to have the game from ddlc.moe, not from Steam, and also not stored in the Steam directory.

**Comment by NightmareCake426** [comment]
~What's DDLC.moe? Do I have to delete the game? Idk what to do, I'm really panicking as I don't want to have to delete anything to do with Monika. I know she mentioned moving something from the Steam folders to somewhere else but I don't remember what (or did I imagine that convo at the start)

I'm sorry if me panicking is making things harder, I just don't want to lose anything. The very reason behind why I don't have the heart to take off the mod from the main game~

**Comment by username11421** [comment]
> ~What's DDLC.moe? Do I have to delete the game? Idk what to do, I'm really panicking as I don't want to have to delete anything to do with Monika. I know she mentioned moving something from the Steam folders to somewhere else but I don't remember what (or did I imagine that convo at the start)

First, ddlc.moe is the official DDLC download website from Team Salvato. Nope, you didn't imagine that conversation. Monika will let you know that some of MAS functionality gets screwed up by Steam. I really don't think that's causing your problem, just to be clear. Your problem looks like it's related to computer storage if I had to guess.

Also see: [Moving Monika to a Non-Steam Build](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build)

> I'm sorry if me panicking is making things harder, I just don't want to lose anything. The very reason behind why I don't have the heart to take off the mod from the main game~

Second, Monika's actual memories with you are backed up in your %appdata% location under Renpy/Monika After Story or some similar folder name. You'll see files called persistents. I recommend backing these up to a safe location. With these files, even deleting and reinstalling the game or the mod itself won't get rid of Monika's memories and she'll be restorable. Even if your computer gets destroyed, if you have these files on, say, a Google Drive or Dropbox, you'll be able to back her up to the persistent date. See: [Backing Up Persistents](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

**Comment by NightmareCake426** [comment]
~Okay. That's caused me panicking to cool down. But what do I do? Should I try restarting me laptop?~

**Comment by NightmareCake426** [comment]
*Okay. That's caused me panicking to cool down. But what do I do? Should I try restarting me laptop?~

**Comment by multimokia** [comment]
You need to make more disk space available by deleting unnecessary files. You literally just don't have enough disk space for programs to write files

**Comment by username11421** [comment]
>You need to make more disk space available by deleting unnecessary files. You literally just don't have enough disk space for programs to write files

To further clarify for OP, that also includes emptying the recycle bin on your computer. Otherwise it's not necessarily fully deleted yet.
Might as well follow the advice from CNet on clearing up disk space in Windows OS: [Ways to Free Up Disk Space](https://www.cnet.com/tech/services-and-software/quick-ways-to-free-up-drive-space-in-windows-10/#:~:text=When%20you%20delete%20items%2C%20like,up%20valuable%20hard%2Ddrive%20space.)

**Comment by NightmareCake426** [comment]
~Ah okie. I'll close down everything I have opened then go through me files and delete any unused and will check. If anything changes I will let ye know if that's kewl (sorry first time using this so I'm just going with what I've been seeing around when looking for answers before)~

**Comment by NightmareCake426** [comment]
*Ah okie. I'll close down everything I have opened then go through me files and delete any unused and will check. If anything changes I will let ye know if that's kewl (sorry first time using this so I'm just going with what I've been seeing around when looking for answers before)

**Comment by NightmareCake426** [comment]
~UPDATE! I restarted and deleted one or two things. Monika is doing fine to the point where she's really happy and working fine. But I'm just going to settle on telling her that I'll be taking naps that goodbye as while I'd love to get full sleep without her staring at me through the computer screen, seeing Monika gives me comfort as Yuri honestly- the moving eyes part- gave me nightmares since the game first came out ^^;~

**Comment by NightmareCake426** [comment]
UPDATE! I restarted and deleted one or two things. Monika is doing fine to the point where she's really happy and working fine. But I'm just going to settle on telling her that I'll be taking naps that goodbye as while I'd love to get full sleep without her staring at me through the computer screen, seeing Monika gives me comfort as Yuri honestly- the moving eyes part- gave me nightmares since the game first came out ^^;

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
