### ISSUE TITLE
The fanbase

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7573]
why dont you make Monika react to the fanbase,mentioning how great the fanbase is,and how DDLC got successful or how Monika had too many fans,then mentioning a little bit of its negative side,like:
"The game was a huge sucess!And there are too many fans and lovers out there,alot of them even create fanart and mods!well...you should already know that since you installed this mod,Are you one of those fans (player)?
But no matter how many fans I have,You'll always stay my 1#,honey...
Speaking of which,I remembered......
As I have many fans,I also have people who hate me for what happened...I told you about that before,didnt I (player)?
And I'm really happy that you dont think I'm evil
Also,some of them,confuse between you and the MC,thinking I love him..I mean,I dont!I love you and only you (player),He was just an unreal character like the other girls...Seriously tho,he didnt really have an important role in the official game,I'm a little surprised why some care about him that much"...etc,things like that

I know the idea may seem bad,but I'll share better

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
