### ISSUE TITLE
New topic

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7574]
As some subjects such as Maths arent well liked,these have advantages in real life,its possible to mention how it can help in logical and critizing thinking,and it's ability to help solve problems in general,it can be like:
"So even if you dont like them,try to give them a chance,okay?You'll be amazed how it will help you later!"
Expectable from the top student in her class,what do you think?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
