### ISSUE TITLE
need help with downloading the mod T_T

### ISSUE THREAD

**Issue by hiraaaaaaaaaa** [Monika-After-Story/MonikaModDev#7575]
![Screenshot (1274)](https://user-images.githubusercontent.com/88242885/127743739-3234a03b-7001-4902-9258-39d2af4578c7.png)

i need some help on downloading the mod... i tried re-downloading the mod files, and even the game and this pops up...

**Comment by multimokia** [comment]
I looks like you installed the mod twice, once in the right place, once in `python-packages`

**Comment by hiraaaaaaaaaa** [comment]
> I looks like you installed the mod twice, once in the right place, once in `python-packages`

how do i delete the duplicate mod files-

**Comment by multimokia** [comment]
just delete them? You can use the delete key

**Comment by hiraaaaaaaaaa** [comment]
ah i managed to fix it! i straight up deleted the whole thing and
redownloaded the game (again lol) and re-copied and pasted the files,
thanks for pointing that out!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
