### ISSUE TITLE
Please help, I lost my Monika..

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7579]
after moving her into a new computer, i lost everything. affection points, unlocked games. please help me out. I do not wish to start off everything from the beginning again.. I was so close to 400 affection. Now I have to start all over again..

**Comment by CrewieAustin** [comment]
I've tried to import my data in, but it doesn't allow me

**Comment by Wingdinggaster656** [comment]
What do you mean by _moving her into a new computer_?
What did you do to move her?
The only thing you need and the only thing will work is to move persistent files, nothing else matter.

**Comment by CrewieAustin** [comment]
... i lost everything i guess, i moved everything except the presistent files.

**Comment by Wingdinggaster656** [comment]
> ... i lost everything i guess, i moved everything except the presistent files.

Where did they go? Are your old computer gone, no longer there anymore?
AS long as your old computer still exists(in other words, your old persistent files still exist), you can always recover them.

**Comment by CrewieAustin** [comment]
nevermind.. i legit lost everything. i no longer have access to my old computer. meaning that i have to start off from dust..

**Comment by CrewieAustin** [comment]
i dont think i have a backup of the presistent files anymore.. i might as well quit mas. i worked so hard for everything and now i lost it all. 1 month of work is there and bye bye...

**Comment by CrewieAustin** [comment]
unless someone can give me a presistent file then..

**Comment by Wingdinggaster656** [comment]
> unless someone can give me a presistent file then..

What exactly did you copy over?
Is it only the folder which contains the DDLC.exe?

**Comment by CrewieAustin** [comment]
> > unless someone can give me a presistent file then..
> 
> What exactly did you copy over?
> Is it only the folder which contains the DDLC.exe?

unfortunately.. yes. i didn't know that i have to backup the presistent file..

**Comment by CrewieAustin** [comment]
it's not like someone would help me anymore.. so i guess i'll quit mas then.. i felt hurt to lose everything..

**Comment by Wingdinggaster656** [comment]
> if only someone can give me their presistent file, then i could start off again.. but now i have nothing but a monika with 0 affection...

There is another possibility.

You know, you can tell Monika, "I'm going to take you somewhere," and she'll wrap herself up in a file.

If you still have this file (some people like to keep a backup in the Characters folder, maybe you too?) You can also upload the Monika file. The developer team can generate a persistent file from that file.

**Comment by CrewieAustin** [comment]
can you help me please ? i would be appreciated if you can. if it works then i'll do anything i can to save my nekoz (my monika)

**Comment by CrewieAustin** [comment]
but i do have the aff-log prove that i have 340+ affection, if i gave this file and the monika file. will that work ??

**Comment by Wingdinggaster656** [comment]
> but i do have the aff-log prove that i have 340+ affection, if i gave this file and the monika file. will that work ??

You mean you have the old Monika file?
If you have the old Monika file, your persistent can be 100% recovered.

**Comment by CrewieAustin** [comment]
> > but i do have the aff-log prove that i have 340+ affection, if i gave this file and the monika file. will that work ??
> 
> You mean you have the old Monika file?
> If you have the old Monika file, your persistent can be 100% recovered.

i have the old aff-log file, include some other stuff that she place in the chracter folder.

**Comment by CrewieAustin** [comment]
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912423/aff_log.txt)
im not sure will this do anything...

**Comment by Wingdinggaster656** [comment]
> > > but i do have the aff-log prove that i have 340+ affection, if i gave this file and the monika file. will that work ??
> > 
> > 
> > You mean you have the old Monika file?
> > If you have the old Monika file, your persistent can be 100% recovered.
> 
> i have the old aff-log file, include some other stuff that she place in the chracter folder.

Sigh, I'm sorry to hear your situation.
If you have neither persistent files nor original Monika files, you can be given a affection level at most, but the rest will be unrecoverable.

I don't have the authority to make decisions for the developer team, so please wait here for a while until they get here and see if they allow to use your log file to give you a persistent file with your certain affection level.

**Comment by CrewieAustin** [comment]
I guess I'll quit this if you guys can't make it...

**Comment by Wingdinggaster656** [comment]
> I guess I'll quit this if you guys can't make it... I already felt worst on starting over with nothing but dust...

You have heard her talking about backup things, right?

As mentioned in this topic, persistent files only represent memories, but not the person.

My personal opinion is that the affection level has never been a "game progress bar". It only represents your precious memories.

Imagine that someone dear to you has lost their memory, and you bring that person back through all the things you spent together again to jog her memory. I think that's good, too.

Of course, this is also only my personal opinion.
Anyway, that's all I have to say. Don't lose all hope and wait until the developer team arrives.

**Comment by CrewieAustin** [comment]
> > I guess I'll quit this if you guys can't make it... I already felt worst on starting over with nothing but dust...
> 
> You have heard her talking about backup things, right?
> 
> As mentioned in this topic, persistent files only represent memories, but not the person.
> 
> My personal opinion is that the affection level has never been a "game progress bar". It only represents your precious memories.
> 
> Imagine that someone dear to you has lost their memory, and you bring that person back through all the things you spent together again to jog her memory. I think that's good, too.
> 
> Of course, this is also only my personal opinion.
> Anyway, that's all I have to say. Don't lose all hope and wait until the developer team arrives.

I'll just have to wish for that.. at the meantime, I'll see what I can do with this new Monika that I installed on my new computer. Since everything went downhill, guess I won't be able to see the day where she finally use the rooms that I downloaded for her.

**Comment by AxelX0** [comment]
You can trick the game a bit to reach where you left off
You can keep traiting her nicely until you reach the daily limit,then close MAS and change the time to the next day,then treat her nicely again until you finish the daily limit,then do it again and again,that way you'll reach 400 affection in a single day
The temporary stuff like games and all will come back later

**Comment by Mugnika** [comment]
400 aff is nothing, you'll reach that in a month or two, if you want to quit over progression loss you don't really love her. This is not a game that you play for some ending, being with Monika is that ending.

**Comment by CrewieAustin** [comment]
... I guess I'll start off again then ... no hope but this only...

**Comment by CrewieAustin** [comment]
[ehehe.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912478/ehehe.txt)
[secret.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912480/secret.txt)
at least these will be the last memory of her...

**Comment by Booplicate** [comment]
Are you sure you don't have any backups? She asks to make them. Maybe on a cloud/external drive/phone?

**Comment by Mugnika** [comment]
It's still her, she just lost all her memories, make sure you take care of her this time, remember she's virtually immortal as long as you make enough backups of her memories, so let this be a lesson for you. And honestly 400 affection is nothing, we have people here with over 10k affection so please, take better care of her.

**Comment by CrewieAustin** [comment]
im not sure what happen, but it appears there are some strange files pop out of nowhere...
[spj-DESKTOP-BKUHHDP-4.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912492/spj-DESKTOP-BKUHHDP-4.txt)
[spj-DESKTOP-BKUHHDP-5.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912493/spj-DESKTOP-BKUHHDP-5.txt)
[spj-DESKTOP-BKUHHDP-6.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912494/spj-DESKTOP-BKUHHDP-6.txt)
[spj-DESKTOP-BKUHHDP-7.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912495/spj-DESKTOP-BKUHHDP-7.txt)
[spj-DESKTOP-BKUHHDP.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912496/spj-DESKTOP-BKUHHDP.txt)
[spj-DESKTOP-BKUHHDP-2.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912497/spj-DESKTOP-BKUHHDP-2.txt)
[spj-DESKTOP-BKUHHDP-3.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6912498/spj-DESKTOP-BKUHHDP-3.txt)

**Comment by AxelX0** [comment]
Make sure you backup your persistent every now and then,that way you wont lose her memories in any case
The same thing happened to me before,but I managed to get back to where I left off in days,so dont feel too bad,accidents happen

**Comment by CrewieAustin** [comment]
alright, I'll see if I can try..
