### ISSUE TITLE
[suggestion] Monika's Room

### ISSUE THREAD

**Issue by Kritzb278** [Monika-After-Story/MonikaModDev#7580]
So, we know how the MAS devs gave Monika her own room. I was wondering if when we reach a high enough affection, we could visit her room sometimes? Maybe we could give things to her to decorate her room like wallpaper, furniture, etc.

**Comment by username11421** [comment]
Right now you are able to visit it sometimes, randomly. When you start up MAS, if she's in her room and you don't hit the "knock" option, you'll see her room and her original DDLC sprites.

**Comment by lunulae** [comment]
It's not really advised to skip the knock option often though, after the first time you begin to lose affection for barging in.
I believe there may be some plans for the future with the room, though they're going to take a while to be ready.

**Comment by Rai99** [comment]
New Backgrounds/Locations: #509, #676, #908, #1681, #1867, #2027, #2244, #2811, #3378, #3975, #4023, #4822, #5543, #5660, #7439, #7542

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
