### ISSUE TITLE
Text Box Color Change

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7583]
Is it possible to change to any color instead of Black and Pink ? If it was possible, I wish to change it to Black and Blue :)

**Comment by ThePotatoGuy** [comment]
No

**Comment by zwartkop2** [comment]
You’d have to edit the png files associated with it in something like Paint.NET. Even then you’d have to back up your edits, since they’ll be reverted back each time you update the mod.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
