### ISSUE TITLE
Someone can teach me how to create a json file for my own custom stuff..

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7585]
I've been trying to make a blue hoodie for my monika, but I have no idea how do I import it into the game.

**Comment by Kritzb278** [comment]
Do you have the sprites for your blue hoodie?

**Comment by CrewieAustin** [comment]
Yea I do have them, I just have to ask how to make a json file out of it.

**Comment by CrewieAustin** [comment]
nevermind i already found the solution...
