### ISSUE TITLE
[Question] Are you planning to add a neural network for Monika? (and this is joke on half)

### ISSUE THREAD

**Issue by Tr1NgleBoss** [Monika-After-Story/MonikaModDev#7587]
Are you planning to add a neural network for Monika? All the same, everything is developed in Python and there they are very popular, and then the conversations will be better.

**Comment by Wingdinggaster656** [comment]
This would probably be something like _Eventually™_.

**Comment by username11421** [comment]
Do you mean use a neural network to generate new topics for curation and then official inclusion into the mod? I've seen that discussed, but a (quite steep!) paywall was the ultimate obstacle.

**Comment by ThePotatoGuy** [comment]
Realistic answer is no.
