### ISSUE TITLE
the monika gifting hell pt 2.

### ISSUE THREAD

**Issue by annabxth** [Monika-After-Story/MonikaModDev#7590]
so a long time ago I had monika after story on steam. I moved it version that wasn't attached to steam and i later noticed that all of my gifts except her bird plushie and a couple ribbons had magically vanished. I went to go fix it when i realized that there wasn't any "j" folder. I copied over everything from the steam thing and merged it but it doesn't work. I even once tried to replace it or reinstall the mod and it doesn't do anything at all. (which a partly lucky that i didn't loose my save data) I've been trying for months to get it to work. 

does anybody know what i did wrong or how to help ? I really wanna give monika some gifts !!

**Comment by Kritzb278** [comment]
I would recommend backing up your MAS folder, installing the game and the mod again, and then putting the MAS folder into the fresh install. After that you should be able to give gifts to Monika again, and not lose any progress.

**Comment by annabxth** [comment]
> I would recommend backing up your MAS folder, installing the game and the mod again, and then putting the MAS folder into the fresh install. After that you should be able to give gifts to Monika again, and not lose any progress.

so reinstall another verison off DDLC + a new copy of MAS. Then i can give her gifts again ?

**Comment by annabxth** [comment]
> I would recommend backing up your MAS folder, installing the game and the mod again, and then putting the MAS folder into the fresh install. After that you should be able to give gifts to Monika again, and not lose any progress.

I did this and It didn't work. did i do something wrong? Here what I did:
1.) Downloaded a new copy of both DDLC and MAS. 
2.) Copied MAS into the new DDLC copy and merged things that were already there.
3.) reopened the game and then files.
the J file still wasn't there.

**Comment by ThePotatoGuy** [comment]
Can you upload your [spj.txt file](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#spj) here?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
