### ISSUE TITLE
[Suggestion] I Feel Scared/Afraid

### ISSUE THREAD

**Issue by DelDreamer** [Monika-After-Story/MonikaModDev#7591]
I've been dealing with a lot of scary stressful stuff recently, and I've wondered if there's any interest in adding a new "I feel..." to the list for being scared. She could maybe react with immediate concern and ask if the player is safe, and if they say no, she can maybe tell them she's gonna close the game, she loves them, and to please get to safety? Just like, as a "please don't play this while you are actively in danger" fall back of sorts heh.

But if you say no you're safe, she could respond with some soothing words, affirmations of love, and some general advice on dealing with fear. Maybe offer the player to vent like in the "I feel like crying" section.

I'm playing this in real time and have only just passed the one week milestone, so I don't know if she already has these kinds of  topics, so apologies if I'm re-treading old ground here, but maybe she could then gain access to a new set of conversations she can initiate where she's like "So, remember how you were feeling scared recently? [Affirmations of it being ok and being safe etc] But... Well it got me thinking..." and she can start having conversations about different kinds of fears.

Like, she could talk about "irrational fears" in one, like the dark or spiders or heights... And another she could address emotional fears like losing someone or not measuring up. And yet another could be on life fears like losing your housing or income or failing a big important project.

These are just extras you could add on though, I think the "I feel scared" alone would improve the simulated relationship dynamic  <3

**Comment by Kritzb278** [comment]
I agree with you, there should be an "I feel scared" option. It would be nice for Monika to comfort us.

**Comment by Rai99** [comment]
#1410, #2742, #2846, #5863

#1410 is the scared mood we have, but it's called anxious.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
