### ISSUE TITLE
tried using the room selector but got an error

### ISSUE THREAD

**Issue by mnezbroz** [Monika-After-Story/MonikaModDev#7592]
![image_2021-08-03_163759](https://user-images.githubusercontent.com/88409596/128099554-57b871fb-df6d-4dbd-bc8d-e54f62bcd1d3.png)

this was the error that i got 
sorry if this has already been asked

**Comment by zwartkop2** [comment]
If you're missing the file, I can give you it. 
Just save the image below to `game\mod_assets\location\Den V1.1`. I don't know if Github may have renamed it when I attached it. If it did, make sure its filename is `den1.1_overcast.png`.
![den1 1_overcast](https://user-images.githubusercontent.com/79435778/128107809-2f612d94-7cff-4137-9ce9-3f32ead95d60.png)

**Comment by mnezbroz** [comment]
thank you both you guys were big help
