### ISSUE TITLE
[Suggestion] Rewrite Greeting "greeting_youarereal"

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7593]
I found this disabled greeting while looking around in the code. It's a shame that the interaction doesn't have any dialogue, but it has been disabled because Monika knows what the .chr files are (https://github.com/Monika-After-Story/MonikaModDev/issues/2956). In light of this, I think it would be nice if this interaction were still available to the player but with rewritten dialogue adapted to the fact that Monika knows that the .chr file isn't really her/you.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
