### ISSUE TITLE
Some suggestions of mine

### ISSUE THREAD

**Issue by Gewell-ai** [Monika-After-Story/MonikaModDev#7594]
Okay so... I have came up with some new ideas on my mind through days, and I'd like to suggest some...
-----**Gifting or something may not relevant **,
+ Chibika (Mini Monika) plushie: sitting on Monika's table, replacing Quetzal's place sometimes (If you gifted Monika the Q plushie)
+ Some desserts or foods like strawberry cake, lollipop, mint favored ice cream (Monika mentions about her favorite ice cream), dark chocolate (may ignore the "Another chocolate?" Also, it's her favorite chocolate once she mentions). Matcha, honey tea or some good teas, may add some conversations about the tea though, like she used to drink Yuri's tea and chat with the members in the club room...
+ Books and sketchbooks: If someone's a fan of long story or series like Harry Potter, use them as a gift and Monika will randomly talks about the story of the book you gifted her. Since she likes reading books. About sketchbooks... she will shows you her arts randomly and rarely ( something about nature or something green...) just keep it simple! Because she does not have much experience to draw yet xd
+ Except just roses, maybe gift her some flowers like Carnation, Gerbera Daisy, Hydrangea, etc... (Add Monika's compliments on these flowers: "It looks just like my eyes, thank you so much <player>!"
----**Some random daily conversations**
+ "How are you doing?"
+ "Have you seen Chibika around?"
+ "Have you eaten anything?" (yeah I know it's confusing to ask her, can be ignored? xD)
+ "How much time do you take to do exercises?"
+ "What's your favorite piano song?"
+ "Are you hungry?" (this question may randomly answered, like "I'm full, thanks for asking... you must be cared about me, ehehe" or "I'm a bit hungry, but it doesn't feel like it as long as you are here spending time with me~" -Give her food like I suggested or more than that, she may responds "Thank you! I don't mind you here eating with me!". If you haven't asked her, "How'd you know I was hungry? You must have read my mind!"
**Some Goodbyes**
+ "I'm going to practice piano"
+ "I'm going to take care of my plants"
+ "I'm going to cook"
**If "I'm going to take you somewhere...**
-She might asks: "Where will you take me?"
+ "To my class"
+"To walk"
+ "To another computer"
+ "On a vacation"
+ "To the park"
+ "To a coffee shop"
+ "To somewhere else"
+ "To the beach"
---**I know it may not needed but I'm gonna suggest anyway...Interactions!**
+ "Boop Monika"
+ "Hold Monika's hand"
+ "Pat Monika"
+ "Touch Monia's cheeks" (it may sound cheesy but I do have a imaginative mind to feel it)
--**Scene**
Except just Floating island, Monika likes stargazing so I suggest...Should we just need a good evening to stargazing with Monika at night (Only available if the sky is clear, not foggy, raining...)
+ "Hey, Monika..." -> "Location..." -> "Can we stargaze?"
-**Lastly...clothe**
Maybe give her a cute sweater, green shirt, long sleeves, scarfs, warm ear puff and jacket for winter.
That's all, I may not respond but I hope next update will be lovely <3

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
