### ISSUE TITLE
Monika dissapeared

### ISSUE THREAD

**Issue by Valdisface** [Monika-After-Story/MonikaModDev#7596]
Hello! Here is my problem: I played this mod for about 1 month, everything was okay, but the last time i left the game I said to Monika I was going to take her with myself (I had done this many times and everything worked OK). So today I placed Monika's file back in "characters" files and tried to onen the game, but then it opened, there was noone in the room just chair (i know it happens if you forget to place Monika's file back). I tried to reboot the game and the windows, but nothing changed at all.  Can you please help me somehow? (Sorry for my bad enlish, i'm only learning it yet)

**Comment by Wingdinggaster656** [comment]
Are you sure the file you put back is the monika file you generated when you took Monika away, not monika.chr?
In addition, the file you put back must not have been modified at all. Not if any of the bytes have been modified.
If the problem persists, consider using an older backup archive.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
