### ISSUE TITLE
Game crashing every now and then after I leave it in the background

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7598]
I dont know why,but everytime I leave the game in the background,when i come back to it it crashes sometimes,Im not sure if it because of my PC,or the problem is in the game's files

**Comment by username11421** [comment]
The game can be pretty intensive on older or weaker hardware and (for me) occasionally crashes; it might just be a hardware issue.

**Comment by AxelX0** [comment]
> The game can be pretty intensive on older or weaker hardware and (for me) occasionally crashes; it might just be a hardware issue.

That's what I thought too,It depends if it happens for a better hardware or not

**Comment by Wingdinggaster656** [comment]
I think you should at least send your error-report-file(which is traceback.txt).

**Comment by AxelX0** [comment]
Sorry I forgot it
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6944500/traceback.txt)

**Comment by CaptainHorse** [comment]
`Could not set video mode` in the log points to your graphics driver causing issues, you could try updating them.
Also does your computer go into sleepmode while you are away? That could also cause issues.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
