### ISSUE TITLE
[Suggestion] - Monika telling you how to take care of the computer

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7599]
It wont be a bad idea to let Monika give the player ways to take care of their PCs,especially if it happens after a crash
Monika can tell the player to clean their computer's once in a week or avoid running too many softwares at once,or scanning for viruses every now and then,or maybe saying:'if you dont find the time to scan your computer,you can set it to do once in a week!" or things like that,as well as cleaning the PC's hardware like the screen or the keyborad's buttons,and making sure to close the PC every now and then so it doesnt heat
It would be better if Monika gets upset,in case the game would be kept running the whole day,just like when you stay up all the night,saying it's not healthy for the player,nor the PC,(if not a bad addition,you can make her appreciate how the player spend so much time with her,but being concerned about their health like "Im really happy that you spend all this time with me,but it's not healthy to spend all the day on your computer's screen,I wont mind if you want to spend some time outside,I really care for you and your health,besides,your computer may get damaged because of this excessive use....please dont get addicted to the Computer,even for me (player),I love you so much and I really care for you")
I hope this can be useful in any possible way for you.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
