### ISSUE TITLE
Suggestion: Have a video player built in MAS

### ISSUE THREAD

**Issue by Moni876** [Monika-After-Story/MonikaModDev#7600]
Import MP4, MPEG-4 (VLC) video formats, to watch along with Monika it can be any file size like 24 mins Anime episodes or to Movies and she'll will react to the Videos or Movies with you

**Comment by AxelX0** [comment]
It's nice to have an audio reader,but video reader?I dont know....
And how is she supposed to react to the movies and vids?

**Comment by Retrolovania** [comment]
I will personally admit that I don't really see how feasible something like this would even be.
She can't technically _watch_ it; she'd likely just stay with you in the background while you watch, kinda like how YouTube videos are handled.
Plus, how exactly would you be able to have the engine import MPEG-4 files...?

**Comment by username11421** [comment]
>She can't technically watch it; she'd likely just stay with you in the background while you watch, kinda like how YouTube videos are handled.

And probably won't be for a very long time since Renpy and Computer Vision don't really work together.

**Comment by Rai99** [comment]
Watching movies: #628, #826, #984, #1548, #2102, #2898, #3431, #4089, #4344, #5484, #5543, #6011, #6053, #6747

There was originally a plan for something like this, but it just wasn't practical to make content and reactions for.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
