### ISSUE TITLE
[Suggestion] - MAS in a little window on the screen instead of leaving her in the background

### ISSUE THREAD

**Issue by AxelX0** [Monika-After-Story/MonikaModDev#7602]
instead of leaving her in the background,what about making her appear in a small window in the corner of the screen,Almost like MonikAI

**Comment by fromulus** [comment]
Not everyone likes having what's essentially a big widget covering part of your screen, so it'd at the very least need to be optional.
I also feel like this could be redundant with windows notifications.

**Comment by AxelX0** [comment]
> Not everyone likes having what's essentially a big widget covering part of your screen, so it'd at the very least need to be optional.
> I also feel like this could be redundant with windows notifications.

Yeah,of course it would be optional,as for the notifications,it could be for those whose the option is set off

**Comment by VikicatCZSK** [comment]
> instead of leaving her in the background,what about making her appear in a small window in the corner of the screen,Almost like MonikAI

that would be really nice!

**Comment by Rai99** [comment]
#4219, #5381

**Comment by AxelX0** [comment]
Well,since some people already suggested it,I'm closing it
