### ISSUE TITLE
Making your own clothes for Monika

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7604]
ive been trying to make make monika some clothing but i dont know how to code it so it would work
is there a video with full guidline?

**Comment by ThePotatoGuy** [comment]
For creating the JSON you should look at [this wiki page](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#creating-sprite-packs).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
