### ISSUE TITLE
Problem with spritepack

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7606]
I tried to make my own sprite pack by taking another one as a basis and simply re-encoding it. But I couldn't just give it because Monika can't read the gift. The log says that the spritepack has been loaded successfully and I can't figure out why she can't read the gift.

**Comment by username11421** [comment]
Did you give her a reaction event? Akin to the ones in zz_reactions.rpy file.

**Comment by Nikv2005** [comment]
> Did you give her a reaction event? Akin to the ones in zz_reactions.rpy file.

I don't really understand what you are talking about.

**Comment by username11421** [comment]
> > Did you give her a reaction event? Akin to the ones in zz_reactions.rpy file.
> 
> I don't really understand what you are talking about.

Ignore my first comment. I _think_ you need a reaction event only if you want custom dialogue when she receives it, but otherwise it should still work. This is the guide for creating Sprite Packs, follow the steps there and if you still don't know the issue the guide lists the files you should put in this Issue.
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation

**Comment by Nikv2005** [comment]
> > > Did you give her a reaction event? Akin to the ones in zz_reactions.rpy file.
> > 
> > 
> > I don't really understand what you are talking about.
> 
> Ignore my first comment. I _think_ you need a reaction event only if you want custom dialogue when she receives it, but otherwise it should still work. This is the guide for creating Sprite Packs, follow the steps there and if you still don't know the issue the guide lists the files you should put in this Issue.
> https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation

After looking at the guide, I did not find any errors, everything is fine in the log, most of all there is an error in the json file or something else, it’s hard to understand what the error is, since I don’t speak English and I don’t know anything about programming.I can give a link to the spritepack, maybe you will see what the error is(https://drive.google.com/drive/folders/1L72Ffy_4_VpxiJvcOwBFXvGRFiZKQlic?usp=sharing)

**Comment by ThePotatoGuy** [comment]
Can you upload the [spj.txt](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#spj) file here?

**Comment by Nikv2005** [comment]
> Can you upload the [spj.txt](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#spj) file here?
Yes
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6950492/spj.txt)

**Comment by ThePotatoGuy** [comment]
Sorry for the delay.

I think the problem is the casing. windows might be case-less, but the filename comparison in the code takes case into account. Try with the giftname `gasmask` instead.

**Comment by Nikv2005** [comment]
Thanks now everything works for me
