### ISSUE TITLE
[Suggestion] 'Work out' goodbye being aware of time of day

### ISSUE THREAD

**Issue by xandy42** [Monika-After-Story/MonikaModDev#7607]
This one's pretty simple: when telling Monika you are going to leave to go work out, she should take into account what time of day it is. For instance, if it's late at night, she might tell you to go to sleep instead of working out.

**Comment by Iceninja64** [comment]
The same should be said if you wanted to take a nap and monkia takes into account that it's late at night she would just say go to bed

**Comment by xXMidnight** [comment]
true

**Comment by YoraeRasante** [comment]
Of course, a question sometime about if we are working night shift would change any replies from her involving time.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
