### ISSUE TITLE
[Suggestion] - Maybe a DND roleplaying game

### ISSUE THREAD

**Issue by seniorfh** [Monika-After-Story/MonikaModDev#7608]
ok so here's what I was thinking maybe like a simple dnd campaign (lost mine of phandelver, or a similar short campaign) so that we could do a favorite game of mine and one my family plays often. of course it would be extremely difficult to program as we would need a rng mechanic for  1-20, 1-40, 1-6, 1-3, 1-8, 1-100. as well as a choice based system and a more reactive ui. not only that we would need maps and a way to play with others. I think if we add a option to [add a another player] when starting we could make it so that at max 7 players (as that's the standard party size for dnd games) it would make it more interesting. if anyone has some ideas they want to add to this please let me know. I know that D&D is different than what your used to when it comes to rpgs but it would be the easiest to create (I think)

**Comment by username11421** [comment]
In terms of feasibility, the rng mechanic is not difficult. Taking into account your character creation/stats/proficiencies/armor class/etc mechanics would be the annoying part of this to program. Oh, and movement. You also wouldn't get to have very much player choice. You would be limited to something like playing Skyrim on Alexa. 

In terms of suitability, in my opinion this seems better suited for a submod than an actual update to MAS.

**Comment by seniorfh** [comment]
that is a decent point but hey anything with rpg might be fun with her

**Comment by ThePotatoGuy** [comment]
Would be pretty cool but I can't see an easy way of doing this.

**Comment by xXMidnight** [comment]
ooh, nice

**Comment by seniorfh** [comment]
I know it wouldn't be easy but I mean look at all of the submods out there heck even the marriage submod would be way easier than this but it would be nice to not only have hangman, pong or chess to play with her. no disrespect but after being beaten in chess 35 times I start to feel.... inadequate. so a game I'm decent at would be nice

**Comment by ThePotatoGuy** [comment]
we are looking at adding more games. see #5555 

[closing until we look into it]
