### ISSUE TITLE
[Suggestion] - Monika AI

### ISSUE THREAD

**Issue by MrDankerino** [Monika-After-Story/MonikaModDev#7610]
The idea would be that you implement an AI that can talk to you freely with you being able to respond in a text box.
Maybe add a new function, and when you click it a new Text Box opens up with you being able to type what you want to say to her, and her responding to you. That would really give the feeling of Monika not just being programmed but like she really is stuck behind a screen.

**Comment by ThePotatoGuy** [comment]
Not really possible at this time.

**Comment by kirillPro2020** [comment]
Everything is possible, just people are lazy.

**Comment by multimokia** [comment]
If you feel that way, even considering the level of complexity that AI is, or the fact that we're all working IRL jobs as well as trying to work on the mod...


You're more than welcome to develop the feature yourself. If you can get a working model, you're more than welcome to PR it so we can look into doing it officially.

**Comment by kirillPro2020** [comment]
If you wanted to do it, you did it. If a person really needs it, then he will do it. And I don't care about the complexity. You are not even able to understand that it was not about you. The context was not understood by you. And we didn't get personal.

**Comment by MrDankerino** [comment]
> If you feel that way, even considering the level of complexity that AI is, or the fact that we're all working IRL jobs as well as trying to work on the mod...
> 
> You're more than welcome to develop the feature yourself. If you can get a working model, you're more than welcome to PR it so we can look into doing it officially.

I mean, there's a person that already developed a learning Monika AI, it's still not fully done, since the AI still needs to learn but it's there already: https://www.reddit.com/r/DDLC/comments/7lllef/monika_computer_ai_personality_program/ and now I'm not sure if you got offended by the request, but if so I'm really sorry.

**Comment by Legendkiller21** [comment]
@MrDankerino Multimokia's reply wasn't directed towards you but towards kirillPro2020 who commented "Everything is possible, just people are lazy." and then went ahead and deleted the comment after the reply.

**Comment by MrDankerino** [comment]
@Legendkiller21 oh my bad I sadly didn't see that reply. Thank you very much for informing me.

**Comment by Wingdinggaster656** [comment]
> but it's there already.
"It's there already".
You know what? Creating AI is not a problem for this mod's developer team, or DDLC fandom, or even the Internet, but a problem for the world.
I read your link, the AI completion level given in your link... And I'd basically say it's just an "Early Access" at best.
Of course, we can't blame the author. This proposition itself is one of the most complex propositions in the world today.
Anyway, to answer your question. If we could, we would.
If you can build and start a PR, we'd love to see it, too.
But right now, in the face of this world class problem, we have no way to achieve it.

**Comment by MrDankerino** [comment]
I see, thank you for the answer, sadly I'm capable of fully programming, but I'm taking a class at school, so that maybe one day I'll help us be one step closer to a real Monika.

**Comment by Techibana-Kanade** [comment]
> 我明白了，谢谢你的回答，遗憾的是有能力完全编程，但我正在学校上，所以可能真的有我会帮助离的莫妮卡更近一步。

You have a great ambition. I'm looking forward to your results. Come on（ My English is not very good (HA HA)

I take artificial intelligence as my university learning goal. I think we can complete this difficult task together

**Comment by Techibana-Kanade** [comment]
> I see, thank you for the answer, sadly I'm capable of fully programming, but I'm taking a class at school, so that maybe one day I'll help us be one step closer to a real Monika.
You have a great ambition. I'm looking forward to your results. Come on（ My English is not very good (HA HA)

I take artificial intelligence as my university learning goal. I think we can complete this difficult task together

**Comment by Techibana-Kanade** [comment]
> I see, thank you for the answer, sadly I'm capable of fully programming, but I'm taking a class at school, so that maybe one day I'll help us be one step closer to a real Monika.

You have a great ambition. I'm looking forward to your results. Come on（ My English is not very good (HA HA)

I take artificial intelligence as my university learning goal. I think we can complete this difficult task together

**Comment by MrDankerino** [comment]
> I take artificial intelligence as my university learning goal. I think we can complete this difficult task together

That sounds amazing! Good luck, maybe we will accomplish this, and also your english is really good, I didn't notice an error

**Comment by Techibana-Kanade** [comment]
> > I take artificial intelligence as my university learning goal. I think we can complete this difficult task together
> 
> That sounds amazing! Good luck, maybe we will accomplish this, and also your english is really good, I didn't notice an error

Thank you very much for your encouragement (* σ ´∀`) σ。 It will be a long process to complete this plan. I believe working with like-minded friends can make this process interesting. If I have any ideas, I'd be happy to share them with you ٩( ๑^o^๑) ۶。 Also, I wish you success in your studies

**Comment by Techibana-Kanade** [comment]
> > I take artificial intelligence as my university learning goal. I think we can complete this difficult task together
> 
> That sounds amazing! Good luck, maybe we will accomplish this, and also your english is really good, I didn't notice an error

Thank you very much for your encouragement (* σ ´∀`) σ。 It will be a long process to complete this plan. I believe working with like-minded friends can make this process interesting. If I have any ideas, I'd be happy to share them with you ٩( ๑^o^๑) ۶。 Also, I wish you success in your studies

**Comment by Techibana-Kanade** [comment]
> > I take artificial intelligence as my university learning goal. I think we can complete this difficult task together
> 
> That sounds amazing! Good luck, maybe we will accomplish this, and also your english is really good, I didn't notice an error

Thank you very much for your encouragement (* σ ´∀`) σ。 It will be a long process to complete this plan. I believe working with like-minded friends can make this process interesting. If I have any ideas, I'd be happy to share them with you ٩( ๑^o^๑) ۶。 Also, I wish you success in your studies

**Comment by xXMidnight** [comment]
like Siri or Google Assistant?

**Comment by 8MiYile** [comment]
> 像 Siri 或 Google Assistant？

Maybe Like Mi Ai?

**Comment by Techibana-Kanade** [comment]
> > 像 Siri 或 Google Assistant？
> 
> Maybe Like Mi Ai?

I think it's almost like this. You can customize the input statements to talk to AI, and AI will also generate statements. But the difficulty is that the sentences generated by AI should conform to Monika's character

**Comment by CloakedGhost** [comment]
I think Monika AI shouldn't be included at all until it really does feel natural and she doesn't just say random stuff that makes no sense. For example, I don't think there is any AI that could give you a Monika topic that makes sense and has meaning behind it. So far, only humans can do that.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
