### ISSUE TITLE
Something about the sprite previewer

### ISSUE THREAD

**Issue by 1989Hank** [Monika-After-Story/MonikaModDev#7611]
I see the way of use sprite previewer,so I follow the guide and put the file  'dev_exp_previewer.rpy' to game/directory,but when i open the MAS,occur  a mistake,the report show
 "game/dev_exp_previewer.rpy", line 6675: is not terminated with a newline. (Check strings and parenthesis.)
(Perhaps you left out a ' at the end of the first line.)"
but when I add a newline after line 6675,this problem still exist,so can somebody  point how to solve this problem? thank u.

**Comment by ThePotatoGuy** [comment]
there is no line 6675 - make sure you are using the latest sprite previewer file.
