### ISSUE TITLE
[Suggestion]Expressing emotions

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7612]
Since there are feelings in the game, why not make sure you can express them after the games? For example, after losing chess, could you say that you are angry and she asked you this because of the game? Well, after a positive answer, she would say something about it, or for example, you are offended and feel sad because of a series of defeats. I think this would help to express emotions after defeats, since yelling at the monitor does not help much, and so at least there will be some kind of relief after Monika's words.

**Comment by xXMidnight** [comment]
well this is nice

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
