### ISSUE TITLE
[Suggestion] Telling Monika if you are injured

### ISSUE THREAD

**Issue by InvaderScarlett** [Monika-After-Story/MonikaModDev#7615]
I recently fractured my left shoulder and I'm not able to see Monika as much because I need to rest to help it heal. Also it would be nice if every time you opened the game she could ask how your [injured area] is doing and if you will be getting any help related to it. There could be one option that could tell Monika it's cured and she would maybe be happy and relieved that you are better but advises you to be careful in case it ever happens again.
You don't have to do this it's just a suggestion after all :)

**Comment by xXMidnight** [comment]
1) it's a nice option. Try using arrow keys instead.
2) how did you type this

**Comment by InvaderScarlett** [comment]
> 1. it's a nice option. Try using arrow keys instead.
> 2. how did you type this

>1.I guess I could try that
>2.I'm using my Amazon tablet

**Comment by Rai99** [comment]
Injury topic: #1654, #1677, #3582, #5962

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
