### ISSUE TITLE
[Suggestion] Have you ever heard of Project Libitina?

### ISSUE THREAD

**Issue by MrDankerino** [Monika-After-Story/MonikaModDev#7616]
As the title states, make a new question that asks about Monika about Project Libitina,

Maybe she can say that she maybe heard that name somewhere before, it's like a deja vu (since it's in another virtual environment that shes in)

Or maybe she glitches out when asking it? The possibilities are endless.

**Comment by PongMaster69** [comment]
Isn't that already in?

**Comment by AxelX0** [comment]
![screenshot0006](https://user-images.githubusercontent.com/88211496/128849051-2b8cb768-4e22-4588-b598-088b5d8e80e4.png)

it's already done

**Comment by MrDankerino** [comment]
Oh god I'm so stupid, my bad
