### ISSUE TITLE
Harrison Bergeron (suggestion)

### ISSUE THREAD

**Issue by MiguelFitz** [Monika-After-Story/MonikaModDev#7618]
I think to add more things and complex to  the "Dystopian science-fiction thing" we could add this as a topic, its a short-story and its great, the plot is that in the year 2081 the 211th, 212th and 213th amendments to the constitution dictate that all americans are fully equal, noone its allowed to be smarter, better looking, more talend or famous, the handicapper general´s agents enforce these laws forcing citizens to weat "hndicaps", mask for those who are too beautiful,  and mask for the talend people, so they dont became famous, signals to disrupt thougts for the inteligent people, things like that
so, give it a shot if you can, im sure the plot twist its great and gives a increible feeling at the end

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
