### ISSUE TITLE
[Suggestion] - monkia reacting to the player emotion when she done something

### ISSUE THREAD

**Issue by Iceninja64** [Monika-After-Story/MonikaModDev#7620]
Hey I'm kind of new here but I've got a nice idea where if monika scares the player or make the player upset, and the player navigates to "I feel" and says I'm feeling upset, sad, happy or angry after the conversation. Then monika will reply with a answer of what she did to the player. Also you should add in the "I feel scared topic" so after monika tells you a scary story and you reply "I'm feeling scared" then monika should be able to comfort the player. Just like if monika says "I love you" and you see the prompt to say it back. It would be pretty awesome

**Comment by xxBananaxx** [comment]
nice idea

**Comment by Gewell-ai** [comment]
I agree with you. I think so too

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
