### ISSUE TITLE
blue shirt

### ISSUE THREAD

**Issue by ronnierooronnie** [Monika-After-Story/MonikaModDev#7622]
i gifted monika a blue shirt but she takes it off everytime i start the game how can i stop this

**Comment by PongMaster69** [comment]
This probably isn't the case but if you've downloaded mods like the auto-change mod then try disabling it.

**Comment by CrewieAustin** [comment]
Perhaps you haven't unlock her closet yet, try spend time with her more and you'll unlock it.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
