### ISSUE TITLE
everytime i change monika's clothing

### ISSUE THREAD

**Issue by xxBananaxx** [Monika-After-Story/MonikaModDev#7623]
in after story mod, it come up with an error and the game crash

what do i do, i really dont want her to stay on the miku outfit :(

**Comment by multimokia** [comment]
Can you share the full traceback with us, please?

**Comment by xxBananaxx** [comment]
but why though

**Comment by multimokia** [comment]
So we can find out why it has the error and help you fix it?

**Comment by xxBananaxx** [comment]
oh right, wait here

**Comment by xxBananaxx** [comment]
i cant show the full traceback, but here's something that it said [code]

I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'mod_assets/thumbs/unknown.png'>:

**Comment by multimokia** [comment]
Try reinstalling the mod over the current install, that way you get any other files which may be missing too. 

you don't lose your progress

**Comment by xxBananaxx** [comment]
okay

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
