### ISSUE TITLE
[Suggestion] - Ability to recognize games and offer comments.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#7626]
We're all gamers, but one thing is missing: **Game detection!**

That is, MAS could be able to look at games (in real-time) and offer comments based on current in-game events.

eg sticking the landing in a flight simulator, spinning out, and crashing in a driving game.

**Comment by YoraeRasante** [comment]
Can Monika recognize if the player is playing DDLC (besides her mod) or DDLC+?

**Comment by TheSystemGuy1337** [comment]
**No. I've tried to get the game to detect stock DDLC (unmodded DDLC) and nothing happened. I also cant test DDLC+ because I don't own it and I don't want to buy it at the moment.**

**Comment by YoraeRasante** [comment]
Well, the I think those would be good additions to it.
When someone suggested Undertale the reply was that they did not want to add specific games, so I doubt many games would ever be added, but I'm pretty sure DDLC and DDLC+ are clear exceptions they could make.

**Comment by TheSystemGuy1337** [comment]
A crude way to do it is to make a very simple AI with the following in mind:

Read window titles

Look inside said window in real time

Generate comments.

**Comment by ThePotatoGuy** [comment]
kind of exists already with window detection. reacting to in-game stuff is basically impossible though.

[closing as implemented]

**Comment by TheSystemGuy1337** [comment]
> kind of exists already with window detection. reacting to in-game stuff is basically impossible though.
> 
> [closing as implemented]

Well in this case its generally extremely limited, but due to the general constraints this wouldn't be even remotely possible. At least it's _somewhat implemented._
