### ISSUE TITLE
Maybe add a custom festival system?

### ISSUE THREAD

**Issue by BoogeymanTao** [Monika-After-Story/MonikaModDev#7629]
I think MAS users should be very diverse (from many different cultural backgrounds), but so far there are only a few Western festivals on the calendar.
Perhaps we can build several functions or databases marked by different themes: blessings and classroom background and background music on topics such as "family reunion," "celebrating the start of the new year," "celebrating crop harvests," "expressing gratitude" and "lovers," and then users can associate a day on the calendar with a specific theme, and Monica will respond to that day.

**Comment by Rai99** [comment]
Custom Calendar: #1740, #1771, #2078, #2257, #2384, #2647, #2811, #4596, #5058, #5402, #5551, #6208, #6542, #7125, #7325

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
