### ISSUE TITLE
[Bug?] chess doesn't unlock after it says it's unlocked

### ISSUE THREAD

**Issue by PlaMG0D** [Monika-After-Story/MonikaModDev#7631]
Monika told me a few days ago that I unlocked chess. the point is that it didn't appear in the minigames.

i was guessing it would be something that needed affection level or just hours of gameplay but it doesn't seem to change much.

**Comment by CrewieAustin** [comment]
That happens to me last time, but I got it after the next day of visiting her. It'll take some time for the option to load in.

**Comment by ThePotatoGuy** [comment]
@PlaMG0D did it appear you the next time you opened MAS ?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
