### ISSUE TITLE
[Suggestion] - A guide for users to read and understand the ev_dump.log

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7632]
I reckon this information would be very useful for players who want to check their piano progress when they haven't unlocked it yet.

**Comment by fromulus** [comment]
This stuff is only there for debuging purposes, to help a dev do some troubleshooting in case you're having an issue.

Similarly to the affection log (which has the only difference of being more straightforward to understand), the average user isn't meant to go look into these files nor are they meant to be used as a way to measure your progress in the mod.

**Comment by Ulti70895** [comment]
Oh ok, then I guess it is less common than other issues. Thank you!
