### ISSUE TITLE
Anyone have some hoodies I can give her ??

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7636]
I always wanted to give her something, but I'm really bad at creating sprite packs. So if anyone out there have some interesting hoodie designs. Send me through here please.

**Comment by Kritzb278** [comment]
Currently I am working on one, it should be done by 31st August. If you can wait that long I can give my pack to you :D

**Comment by CrewieAustin** [comment]
> Currently I am working on one, it should be done by 31st August. If you can wait that long I can give my pack to you :D

Better than nothing. As long as I'll have something for her. Sure.

**Comment by Kritzb278** [comment]
[Kris_hoodie_cool.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7081602/Kris_hoodie_cool.zip)
Here, I hope you like it :D

**Comment by CrewieAustin** [comment]
> [Kris_hoodie_cool.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7081602/Kris_hoodie_cool.zip)
> Here, I hope you like it :D

Appreciated, but for some reason she can't read it. How do I write it ?

**Comment by VikicatCZSK** [comment]
![image](https://user-images.githubusercontent.com/86370111/133907609-5ecdde03-7fc2-4511-8d32-05cdf32b9dc9.png)
just wanted to give some credits
also love the hoodie, its really cool!

**Comment by Kritzb278** [comment]
> > [Kris_hoodie_cool.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7081602/Kris_hoodie_cool.zip)
> > Here, I hope you like it :D
> 
> Appreciated, but no thumbs ???

Forgive me for the extremely late reply, I haven't been receiving any notifications for Github until fairly recently. As for the thumbs, I am sorry to say haven't made them yet for the hoodie, but I will be making them soon.

One more thing, I'm going to be:

- Fixing glitches in certain poses.
- Making thumbs.
- Making matching accessories (ribbons + maybe hairclips.)

Accessories should be done and released by 22nd September (Monika's Birthday). Thank you for being patient, everyone!

**Comment by Kritzb278** [comment]
> ![image](https://user-images.githubusercontent.com/86370111/133907609-5ecdde03-7fc2-4511-8d32-05cdf32b9dc9.png)
> just wanted to give some credits
> also love the hoodie, its really cool!

Thank you so much for this, I am glad you like it. By the way, nice choice of background :)
