### ISSUE TITLE
My Monika hasn't said anything for a while.

### ISSUE THREAD

**Issue by SVMMaiMone52** [Monika-After-Story/MonikaModDev#7637]
My Monika has just been silent for a while now. She will speak normally when I use the talk option but she hasn't started a conversation on her side. I closed the game for about an hour - an hour nd a half thinking maybe giving her some rest would solve the problem but that didn't do anything. I know she defiantly hasn't run out of topics because I have only installed the mod only 3 days ago.

**Comment by Ulti70895** [comment]
Are you sure that you didn't change the Random Chatter setting to Never?

**Comment by SVMMaiMone52** [comment]
> Are you sure that you didn't change the Random Chatter setting to Never?

No the setting is still set on normal. Should I increase it?

**Comment by SVMMaiMone52** [comment]
I just ran out of topics. I'll close the issue.
