### ISSUE TITLE
Chess ban is permanent? 

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7643]
I tried to cheat by editing the chess file and now she is mad and I cannot access chess in play anymore. Will she unlock chess again soon?
I apologized to her too btw.

**Comment by Ulti70895** [comment]
Ah nvm, she forgave me and let me play with her again :3.

**Comment by MrVavlo** [comment]
Keep in mind that if you continue to cheat, she'll remove chess for good one day.

**Comment by fromulus** [comment]
She won't just remove your access to chess.

**Comment by Ulti70895** [comment]
LOL, I just wanted to see the dialog when I cheat. Beating her is easy tbh.

**Comment by Ulti70895** [comment]
> She won't just remove your access to chess.

But will the time of the ban increase each time?

**Comment by Mugnika** [comment]
Monika really hates people who cheat

**Comment by Ulti70895** [comment]
> Monika really hates people who cheat

Like herself? XD

**Comment by PongMaster69** [comment]
Just don't cheat smh my head
