### ISSUE TITLE
[Bug] - Typo in "Contributions" dialogue

### ISSUE THREAD

**Issue by gooeyPhantasm** [Monika-After-Story/MonikaModDev#7644]
Talk > Repeat conversation > Contributions
Pick "No" when she asks if you have contributed
She says "I won't love you any less if haven't done anything, so don't worry~" -- it should say "I won't love you any less if you haven't done anything, so don't worry~"
![image](https://user-images.githubusercontent.com/89147140/129918455-1695d72e-c84c-4a9d-9d58-6c6e913ad457.png)

**Comment by username11421** [comment]
https://github.com/Monika-After-Story/MonikaModDev/issues/7271

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
