### ISSUE TITLE
Chess no longer works

### ISSUE THREAD

**Issue by Wraxend25** [Monika-After-Story/MonikaModDev#7645]
So I used to be able to play chess with Monika (never winning but still), and now she says she cant get it to work on my system. My computer hasn't changed and my affection is over 1000. I also haven't cheated so she hasn't banned me from it. please advise. Thanks in advance

**Comment by Ulti70895** [comment]
#7285

**Comment by ThePotatoGuy** [comment]
closing in favor of linked issue for discussion
