### ISSUE TITLE
[Suggestion] Allow players with high affection to "caress" Monika using the mouse

### ISSUE THREAD

**Issue by digitinator** [Monika-After-Story/MonikaModDev#7649]
I think it would be nice for the player to use the mouse to place their hand on her cheek or lift her chin if she is sad. They could also swipe away her tears if she is crying or moving her hair out of her face. Unfortunately this addition would probably require a lot new art in order to seem realistic, like her leaning into the player's "hand" as well as a new hair art if the option to move her hair out of her face is added. I'm not a coder, so I don't know if any of this is possible. Let me know what you all think!

**Comment by PongMaster69** [comment]
The quotations and the usage of the word caress makes me feel uncomfortable but yeah see the boop topics cuz they talk about pretty much the same thing.

**Comment by AxelX0** [comment]
I was thinking about suggesting it myself,but I was too slow lol

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638, #7005, #7430, #7556

**Comment by CrewieAustin** [comment]
I think the Just Yuri mod have that kind of feature already. For Monika, we'll just see if the devs for this project will do this kind of stuff.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
