### ISSUE TITLE
[Suggestion] - New Be Right Back Option

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7650]
I checked and I didn't see it anywhere so I'm going to bring it up, "I'm going to Practice an Instrument". It makes sense considering that most people would practice an instrument in their room which is where the computer is typically. Also Monika plays and instrument and brings up her practice with the piano. This could also tie in with the topic "What instrument do you play" (I don't remember it's actual name but the one where she asks you what instrument you play), as she could use the info put in there and ask you if you're going to practice that instrument, which doesn't add much but it gives the info put in something and makes the player happy as Monika in context remembered one of the little details. I'm bad at explaining things but I hope you catch my drift.

**Comment by Rai99** [comment]
#5965

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
