### ISSUE TITLE
[Suggestion] - Add an option to change the flower on her hair to a rose.

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7651]
I give her roses every day and sometimes she put a rose on her hair; I reckon making the ''rose'' option available in appearance when the player gives roses is really nice.
![image](https://user-images.githubusercontent.com/88768397/130301984-11c41380-be6c-4847-9972-5e8b344b40ea.png)

**Comment by VikicatCZSK** [comment]
heya, can i ask how do you give her the roses? because i tried it but i dont know what to name the file
( in "giftname".gift)

**Comment by Ulti70895** [comment]
> heya, can i ask how do you give her the roses? because i tried it but i dont know what to name the file
> ( in "giftname".gift)

Create a new text doc and change its name to ''roses.gift'' then accept the warning of changing the extension.

**Comment by VikicatCZSK** [comment]
> > heya, can i ask how do you give her the roses? because i tried it but i dont know what to name the file
> > ( in "giftname".gift)
> 
> Create a new text doc and change its name to ''roses.gift'' then accept the warning of changing the extension.

alr thanks!

**Comment by ThePotatoGuy** [comment]
it might not be in that menu because we want it to be exclusive to rose gifting. We can look at other ways to make this always accessible, like maybe via a perma gift with the roses.

[closing until we look into it]
