### ISSUE TITLE
I have a question about Surprise.txt

### ISSUE THREAD

**Issue by Schwarzer661** [Monika-After-Story/MonikaModDev#7653]
Monika says she left a surprise for me but it didn't appear. I try to repeat conversation and checked my character files, but I still don't see it.  And she has mentioned it to me three times. I don't know what to do. (/_;) 
I hope someone can help me, thank you very much.
![image](https://user-images.githubusercontent.com/46041145/130315652-e43abeae-33b7-4680-a27a-73fc6af6a07c.png)

**Comment by ThePotatoGuy** [comment]
seems like we could consider adding more potential file names or avoiding the dialogue if we cant generate the file.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
