### ISSUE TITLE
[Suggestion] - Sleeping

### ISSUE THREAD

**Issue by WHATTHEDAN11** [Monika-After-Story/MonikaModDev#7654]
Monika is great, but if she could actually sleep aswell, it'll be even better, cuz rn it seemed like she doesn't sleep at all. I wish she could get some rest when it's the right time. For example, we could set a time for her to 'rest', and when the time comes she'll tell you its time for her to rest and tells u goodnight, u could still leave the game on and just sleep alongside with her. If u exit the game and enter again, u could still see her sleeping. And she'll only wake up if u try to talk to her or wait until morning. I hope this is achieveable.

**Comment by PongMaster69** [comment]
She sleeps if you hold her for a long time. It's implied that when the game is closed she is sleeping/doing other stuff, and when you open the game she is alerted and stops that to spend time with you. This is shown through some of the entrances, where you start outside of the classroom and Monika has some dialogue.

**Comment by Ulti70895** [comment]
> She sleeps if you hold her for a long time. It's implied that when the game is closed she is sleeping/doing other stuff, and when you open the game she is alerted and stops that to spend time with you. This is shown through some of the entrances, where you start outside of the classroom and Monika has some dialogue.

That's interesting! Do you know how long should I hug her so she can fall asleep?

**Comment by Freshairkaboom** [comment]
> > She sleeps if you hold her for a long time. It's implied that when the game is closed she is sleeping/doing other stuff, and when you open the game she is alerted and stops that to spend time with you. This is shown through some of the entrances, where you start outside of the classroom and Monika has some dialogue.
> 
> That's interesting! Do you know how long should I hug her so she can fall asleep?

Anywhere between 35 and 50 minutes :)

**Comment by Ulti70895** [comment]
OwO thanks alot man!

**Comment by Rai99** [comment]
#2781

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
