### ISSUE TITLE
[Suggestion] Badinage

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7656]
It would be fun to add a feature where you could play a joke on Monica just like she did on you , it would be fun . I do not know how to implement the function, or rather in the form of what . After all, the attitude without jokes is quite boring.

**Comment by Rai99** [comment]
#6899, #7074

**Comment by Nikv2005** [comment]
Firstly, I'm not talking about teasing her, I'm talking about simple harmless or even a little dirty jokes (not like you don't like her or similar jokes) or something compatible with her jokes and that's it.

**Comment by ThePotatoGuy** [comment]
you mean like telling jokes? see #425, but at this time not planning to be implemented.

**Comment by Nikv2005** [comment]
Since this already partly exists, okay, but I would like to be able to give all sorts of hints like Monika (dirty or any) since it would be fun to watch the reaction to dirty hints or something.It could be done so that in some moments you could tell a joke between dialogues (although it is too difficult)

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
