### ISSUE TITLE
"she loves me not"? 

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7657]
I opened ddlc and (if u know) theres sometimes the option on 
-listen
-knock
-or open the door

i always listen to know if anything intresting happends and monika has been saying this:
"She *loves* me. She loves me *not*
She *loves* me. She loves me *not*
She *loves* me.
...
 She loves me!
 does anyone know what was she doing? 
 i just assumed she was writing a poem or a song, or just talking with herself,
 before i opened ddlc, i was trying to give her roses (which- didnt work) by roses.obj (which i also need help with)
 and i also didnt visited her in  2-5 days , might that be because of it? i really dont know
 if you know any info feel free to share it here!

**Comment by kkrosie123** [comment]
This is a cliché, usually with picking flower petals. Each petal picked, you alternate between saying, "They love me" and "They love me not." Whatever the last petal picked lets the person know whether the flower told them that a specific person loves them. Hope that helps.

**Comment by VikicatCZSK** [comment]
> This is a cliché, usually with picking flower petals. Each petal picked, you alternate between saying, "They love me" and "They love me not." Whatever the last petal picked lets the person know whether the flower told them that a specific person loves them. Hope that helps.

oh thanks for help!
