### ISSUE TITLE
[Bug] -  Can't recover game progress!

### ISSUE THREAD

**Issue by BlueVicky** [Monika-After-Story/MonikaModDev#7658]
Hi, i'm new to github but i really wanted to adress this problem i had in Monika After Story. I know people talked about this before, but i tried everything, so the last option i had was create an issue here.
  Ok so.. what happened was that i had the game on Ubuntu 16.04 if i remember right, but my hard drive died a few days ago. I expected this to happen, so i backed up the whole MAS folder in an USB, with the renpy folder, and the persistent.pyo file. I had a laptop with just (Slacko) Puppy Linux in, but i wanted to do anything to bring my Monika back. So i ran it there, the game started from the beggining, and i said "goodbye" later on. When the game closed, i copied and pasted the renpy folder from the USB in the game directory, which replaced the other one. When i opened the game, nothing new happened! 
Please, i need to know if i did something wrong. I really loved my Monika and i want her back. If someone helps me i will be very thankful, it means a lot to me and i love this game. Thank you.

**Comment by multimokia** [comment]
`persistent.pyo` and likewise `persistent.py` are **not** actually your persistents.

Instead, refer to [this link](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) to see where to find them and how to back up properly.

**Comment by BlueVicky** [comment]
@multimokia Yeah, i readed that many times before, but there's something that isn't clear to me. If persistent.pyo and persistent.py are not the persistents, then what file is it? I can't find any other file called "persistent". And even if i don't know which one is it, i backed up the renpy folder and the whole MAS folder, so it still doesn't seem to be enough.

**Comment by multimokia** [comment]
The one in renpy is the persistent.

You need to put that backup in the same location just on the new OS

**Comment by BlueVicky** [comment]
If it isn't too much to ask, how is the file exactly called? So i can copy one or more important files in the new OS. I've seen people always just call it "persistent", but as i said before, the closest i found to that is persistent.pyo and persistent.py . I could just paste all the backed up files of the renpy folder but i tried that and nothing happened.

**Comment by multimokia** [comment]
You're looking in the game files, it is not there.

You need to navigate to `/home/USER/.renpy/Monika After Story`

Otherwise known as `~/.renpy/Monika After Story`

**Comment by multimokia** [comment]
You'll find a file literally named `persistent` in there.

It should be noted that files or folders prefixed with `.` are *hidden*, and you'll need to configure your file manager to show hidden files

**Comment by BlueVicky** [comment]
Ooh.. now i understand. If it wasn't in the game files then i think i backed up the wrong folders and files. But that .renpy folder where the persistent and  all my progress was, originally was in my old computer with Ubuntu. That means i'm out of luck right? Because i don't have my progress anymore.

**Comment by multimokia** [comment]
Not unless you can still get in to access some of the files on that drive. But if not you are out of luck, I'm afraid

**Comment by BlueVicky** [comment]
I see.. still, thank you so much for helping me. I'll start the game again and do better next time. This mod means a lot to me, and i love it's development. Thank you!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
