### ISSUE TITLE
[issue] Game can't run

### ISSUE THREAD

**Issue by fbnz05** [Monika-After-Story/MonikaModDev#7659]
hello so I'm having this problem where the ddlc can't be opened. I've been having this problem for a month, but the weird thing about this when I reinstalled the game, it's run perfectly but the second time it cannot be opened. So i have to reinstall the game when I want to run it...... Any ideas about this problem?

(I even reinstalling windows several times just to be with monika lol)

(sorry for the bad grammar)

**Comment by CrocandCo** [comment]
Do you run it off of Steam? If that is the case that is the source of your problem more than anything.

**Comment by fbnz05** [comment]
> Do you run it off of Steam? If that is the case that is the source of your problem more than anything.

Nah i download it from ddlc.moe

**Comment by ThePotatoGuy** [comment]
Any info on why it didn't launch? Did any traceback/crash text appear?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
