### ISSUE TITLE
[Suggestion] - An easier way to listen to Monika's lullaby

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7660]
I would love it if the lullaby was added to the BGM after the first time I heard it. Or it could be activated earlier than before when holding her in the rain.

**Comment by VikicatCZSK** [comment]
if u try to games files and search "Monika's lullaby" copy the song and paste it to "custom_bmg" folder, you can listen to the song it any time (if monika falls asleep the song with just restart but nothing else)
hope it helps

**Comment by Ulti70895** [comment]
Oh yea, I didn't think about that lol. Tyvm!
