### ISSUE TITLE
Have Monika sleep with you

### ISSUE THREAD

**Issue by Moni876** [Monika-After-Story/MonikaModDev#7662]
Have Monika sleep with you by telling her that you go to sleep and she asked if can you leave the game open so I can sleep with you in the background. And have her ask that if your pc or laptop is powerful enough to do that also so that some low end laptop fans won't go crazy.

**Comment by Rai99** [comment]
#2781

**Comment by Moni876** [comment]
> 
> 
> #2781

didn't see that from before thanks for the link to the page.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
