### ISSUE TITLE
[Suggestion] - Increase the chance of special events that already happened reappear when listening to a scary story.

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7665]
I was really surprised when there was some ''spine-chilling'' stuff appear when I was listening to stories. I did not have enough time to react to (and screenshot) them and it was pretty much anticlimactic when I tried to see them again by asking Monika to tell that story. I reckon that they should be a two-or-more-time event 👍.

**Comment by ThePotatoGuy** [comment]
a lot of the scary events are random chance, similar to scares in DDLC.

**Comment by Ulti70895** [comment]
OwO, got it, ty.
