### ISSUE TITLE
[Suggestion] Monika's blanket

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7671]
I was thinking Monika would have blanket if she gets cold or if you want her to wear it.
She would say something like "Hmm, im pretty cold, ill be right back"  take the blanket and wrap it around her.
It would be pretty cute and she could also have a dialog when she asks you to cuddle with her a little in it.

**Comment by ThePotatoGuy** [comment]
a blanket ACS would probably be difficult to make, but it would be nice.

**Comment by VikicatCZSK** [comment]
> a blanket ACS would probably be difficult to make, but it would be nice.

yea thats true.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
