### ISSUE TITLE
[Bug] - Monika can not read any gift files.

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7673]
After the crash occurrence mentioned in #7669, Monika does not react with the rose gift like usual. But I do not think that is because of the crash but the limit of gifting roses. I really want to know why she was apathetic with my gifts :((. (None of the gift files work).

**Comment by ThePotatoGuy** [comment]
The character folder in the DDLC root dir is the one that is checked. Characters is not a folder that is shipped with the mod, so the origin of your second characters folder is only something you can answer.

**Comment by Ulti70895** [comment]
Thank you!
