### ISSUE TITLE
affection question

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7674]
So,uh, when i check my affection, it says 96 then it says 93. What do i do? im on macOS if it helps

**Comment by CrewieAustin** [comment]
> So,uh, when i check my affection, it says 96 then it says 93. What do i do? im on macOS if it helps

Probably means you've already reached the Max Affection Capacity, you can only gain 7 affection points daily.
If you did anything after the Max Affection Capacity, it won't be counted. It'll be only listed in Aff_Log as a display.

**Comment by toonziz** [comment]
tysm

WOW I HAD 93? now i haave like 200 smthn

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
