### ISSUE TITLE
How can I add a new game mode?

### ISSUE THREAD

**Issue by Didkrak** [Monika-After-Story/MonikaModDev#7677]
I'm working on a new game mode that would allow us to play our midi devices (such as a piano keyboard) for Monika, essentially so she can listen to me when I play piano rather than only being able to play my pc keyboard for her (none of the midi-to-keypress converters I tried work with how pygame recognizes key presses so I can't just use them). Since this is probably a pretty niche thing to want I'll make it a submod.

I already have the pygame code to read the midi input and get the notes, but can't figure out how to add a new game option to MAS. I have the game initialized the same as pong in zz_games.rpy but am clearly missing something (maybe adding it to a game list somewhere) since the new mode doesn't show up under "Play." How can I add a new game option?

**Comment by username11421** [comment]
Do you have an event that runs and unlocks it? When does the event run?

See this code here for unlocking the piano game; something like this is what you need to have somewhere if you don't already. This code is in script-story-events.rpy. 
```
init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="mas_unlock_piano_MIDI",
            conditional="store.mas_xp.level() >= 12",
            action=EV_ACT_QUEUE,
            aff_range=(mas_aff.AFFECTIONATE, None)
        )
    )

label mas_unlock_piano_MIDI:
    m 2hua "Hey! I've got something exciting to tell you!"
    m 2eua "I've finally added a piano to the room for us to use, [player]."
    if not persistent._mas_pm_plays_instrument:
        m 3hub "I really want to hear you play!"
        m 3eua "It might seem overwhelming at first, but at least give it a try."
        m 3hua "After all, we all start somewhere."

    else:
        m 1eua "Of course, playing music is nothing new to you."
        m 4hub "So I'm expecting something nice! Ehehe~"

    m 4hua "Wouldn't it be fun to play something together?"
    m "Maybe we could even do a duet!"
    m 4hub "We would both improve and have fun at the same time."
    m 1hksdlb "Maybe I'm getting a bit carried away. Sorry!"
    m 3eua "I just want to see you enjoy the piano the same way I do."
    m "To feel the passion I have for it."
    m 3hua "It's a wonderful feeling."
    m 1eua "I hope this isn't too forceful, but I would love it if you tried."
    m 1eka "For me, please?~"
    $ mas_unlockGame("piano") #The "piano" here should be whatever you called the MIDI piano internally
    return
```

If you want it to be more like Chess, where you have suboptions on choosing the existing chess game and your MIDI game is under the existing piano game, look at the menu structure for the chess game.

**Comment by Didkrak** [comment]
I initially had it setup the same as pong where in the initialization it has "unlocked=True" but that didn't work, so I have since tried the method you mentioned of having an event to unlock it, but still no luck. The event runs right after Monika greets me, but the game option still doesn't show up. The problem might be the name I give the unlock function, since I don't really understand what to pass it. For piano it passes "piano" but in the initialization of the piano game the event label is mas_piano, and I don't see anything besides the prompt that is just "piano." Similar for the other games. 

Below is the initialization and event I am currently using, based off the code I found for connect 4 here: [https://github.com/Monika-After-Story/MonikaModDev/pull/6929/files](https://github.com/Monika-After-Story/MonikaModDev/pull/6929/files). In script-ch30.rpy I also added playerpiano to game_unlock_db, as in the linked code.

```
init 5 python:
    addEvent(
        Event(
            persistent._mas_game_database,
            eventlabel="mas_playerpiano",
            prompt="My Piano"
        ),
        code="GME",
        restartBlacklist=True
    )
label mas_playerpiano:
    call game_playerpiano
    return

init 5 python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="mas_unlock_playerpiano",
            conditional="store.mas_xp.level() >= 0",
            # action=EV_ACT_QUEUE,
            action=EV_ACT_PUSH,
            # aff_range=(mas_aff.AFFECTIONATE, None)
            aff_range=(None, None)
        )
    )

label mas_unlock_playerpiano:
    m 2hua "Hey [player]."
    m 2eua "It might work this time."
    $ mas_unlockGame("playerpiano")
    return
```
And in script-ch30.rpy
```
    python:
        game_unlock_db = {
            "chess": "mas_unlock_chess",
            mas_games.HANGMAN_NAME: "mas_unlock_hangman",
            "piano": "mas_unlock_piano",
            "playerpiano": "mas_unlock_playerpiano",
        }
```

**Comment by username11421** [comment]
Have you looked at other people's WIP games to see examples and troubleshoot your issue? I found two existing PRs for you that might provide an example of what you're trying to do. I have not personally looked at these, but maybe they will be of some use to you.

https://github.com/Monika-After-Story/MonikaModDev/pull/6146
https://github.com/Monika-After-Story/MonikaModDev/pull/5555

**Comment by Didkrak** [comment]
Thanks for the extra examples. I already had one for connect 4, but still couldn't find the problem. By comparing all of em with my code and some extra testing I finally stumbled onto the problem. It was my prompt value in the initialization. I thought that was _just_ for the button to enter the game (after hitting play you would get the prompt button), but apparently it is somehow used when unlocking the game too. So I can't unlock the game if the prompt is different than the game name (I was calling the game "playerpiano" but making the prompt "My Piano"). After unlocking the game I can change the prompt and it stays available with the new prompt though, so it is just a problem with the unlocking. So the problem is fixed by just giving both the prompt and game a name like Midipiano (capitalization of the first letter doesn't seem to matter for the prompt).
