### ISSUE TITLE
[Bug] - Piano notes in verse 1 and 2 are incorrect.

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7678]
Have anyone played the piano and noticed that it should be opoopo]]p[p[] after the ''In my hand,...'' line?

**Comment by ThePotatoGuy** [comment]
Yup, you seem to be right. I don't have an ear for notes so I used a synthesia video to create the json. (probably [this one](https://www.youtube.com/watch?v=0gQzgN8tvSg)).

Can you go through all the entire json and list out other inaccuracies?

**Comment by Ulti70895** [comment]
Lel, I'll try my best.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]

**Comment by ThePotatoGuy** [comment]
not actually fixed, slated for next rel maybe

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
