### ISSUE TITLE
Self-Made Custom Piano Notes

### ISSUE THREAD

**Issue by CrewieAustin** [Monika-After-Story/MonikaModDev#7679]
Is it possible to make your own Piano Notes then bring it up to Monika ? I wonder if that will work...
I mean, I do see stuff like Jingle Bells and Happy Birthday exist. But I don't see too much custom piano songs around the internet. Except a drama where a guy wanted the entire Megalovania song to be added as Custom Piano Song.

**Comment by ThePotatoGuy** [comment]
> Is it possible to make your own Piano Notes then bring it up to Monika ? 

[Yes](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs)

> But I don't see too much custom piano songs around the internet. 

see [the wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki/External-Content#piano-notes) as well as [this issue search link](https://github.com/Monika-After-Story/MonikaModDev/labels/pianonotes)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
