### ISSUE TITLE
Text speed

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7680]
Hi again! uh, so.. Ive played MAS before and i remember her saying something about me being a fast reader, and rn i have 126 affection but she has not said anything about it..do i need more affection or....?..-

**Comment by ThePotatoGuy** [comment]
That should be enough affection for the text speed topic to trigger. Are you trying to set text speed and its not working?

**Comment by toonziz** [comment]
> That should be enough affection for the text speed topic to trigger. Are you trying to set text speed and its not working?

well, i think she hasnt gotten to it yet, but she's been talking about nicknames, books, ect, but nothing about text speed.

**Comment by toonziz** [comment]
she just mentioned it! :D

**Comment by toonziz** [comment]
oh god its too fast how do i make it a bit slower

**Comment by toonziz** [comment]
uhh is there a link to a dev mode so i can make it a bit slower and i wanna force Monika to have an ahoge

**Comment by Ulti70895** [comment]
Settings - Text speed.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
