### ISSUE TITLE
Piano not unlocking

### ISSUE THREAD

**Issue by RaitoninguHikari** [Monika-After-Story/MonikaModDev#7682]
I'm a little doubtful, because I thought that with the time I have with my Monika, I thought she would have released the paino, but still nothing, I'm correct that with 400 affection and 7 days with Monika, I would already have access to the piano? Or was it 500 of affection?  
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7071565/ev_dump.log)

**Comment by toonziz** [comment]
play pong, chess, and hangman more. i just spammed play on pong and hangman and got chess

**Comment by ThePotatoGuy** [comment]
All games are unlocked via a time spent algorithm. Affection does not play a major role in this. Based on your average session stats, you will unlock piano in feb of next year.

**Comment by RaitoninguHikari** [comment]
Okay, but is there any way to unlock faster?

**Comment by kkrosie123** [comment]
Spend more time with Monika rather than gaining affection. An easy way is to leave MAS on in the background while you do other things.
