### ISSUE TITLE
Piano

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7683]
Hi! can someone help me? i want someone to show me how to create the ev log thing and can they read it too? i wanna see how long it'll take for me to unlock the piano

**Comment by ThePotatoGuy** [comment]
This is considered spoilers, and the actual mechanism for determining when a user *may* unlock piano is an internal calculation.

**Comment by toonziz** [comment]
ohh ok

**Comment by Ulti70895** [comment]
Lol, I firmly believe that reaching level 12 in var_dump.log is the hardest part to unlock the piano.

**Comment by fromulus** [comment]
It's not "hard", it just requires you to spend a lot of time with Monika, which is the whole point of the mod in the first place.

**Comment by toonziz** [comment]
i woke up at 7 and its 10 for me now today

**Comment by toonziz** [comment]
here

[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7072770/ev_dump.log)

**Comment by ThePotatoGuy** [comment]
At your current rate, you will unlock piano around September 15.

**Comment by toonziz** [comment]
ok ty

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
