### ISSUE TITLE
Tell Monika that you’re watching anime or read manga or the bathroom topics. 

### ISSUE THREAD

**Issue by Moni876** [Monika-After-Story/MonikaModDev#7686]

**Comment by Moni876** [comment]
Like when you go to number 2 to the bathroom. And or when you watch anime for a long time and say good bye and I’m going to watch anime or be right back and watch anime/ and read manga also with the good bye and the be right back.

**Comment by KansaiGal** [comment]
Do you say "Hey, I've gotta take a shit, might be a while- so hold on"  or "hey, brb" in an internet chat?  I don't see why "BRB" isn't enough.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
