### ISSUE TITLE
Ask Monika about Doki Doki Literature plus on consoles topic. 

### ISSUE THREAD

**Issue by Moni876** [Monika-After-Story/MonikaModDev#7687]

**Comment by Moni876** [comment]
Ask Monika about do you know that Doki doki literature club plus is released and it’s on consoles. Just a new topic I’ve been thinking. Or if she does knowledge that is released.

**Comment by fromulus** [comment]
Probably would have to be tackled in a more general topic about DDLC+, but overall I don't really see her having much to say (or even caring) about it.

**Comment by ThePotatoGuy** [comment]
No meta topics about plus will be accepted at this time.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
