### ISSUE TITLE
The extra everything submod

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7688]
can someone send me the file/ google drive to the extra everything submod for mas? (DONT SEND REDDIT LINKS REDDIT IS BLOCKED ON MY MACBOOK SO I CANT ACCESS REDDIT)

**Comment by zwartkop2** [comment]
https://drive.google.com/file/d/1iCzq1J76a1x-qUm-3gnvUYKpErqvaTEC/view

**Comment by toonziz** [comment]
> https://drive.google.com/file/d/1iCzq1J76a1x-qUm-3gnvUYKpErqvaTEC/view

TYSM!!!

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
