### ISSUE TITLE
Monika not talking

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7692]
Hi again! Monika isnt talking. All she did was sing a few minutes ago, nothing else. Please help?

**Comment by ThePotatoGuy** [comment]
Check the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-isnt-saying-anything).

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
