### ISSUE TITLE
[Suggestion] A Topic About The DDLC ARG

### ISSUE THREAD

**Issue by redujump5** [Monika-After-Story/MonikaModDev#7694]

**Comment by ThePotatoGuy** [comment]
Are you talking about [this](https://www.reddit.com/r/DDLC/comments/ab0nt4/ddlc_arg_archive/) or is this a plus thing? Either way, neither topics are things that will be accepted into the mod at this time.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]

**Comment by redujump5** [comment]
The 2017 DDLC ARG
