### ISSUE TITLE
Question about json files

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7697]
I recently made a spritepack but I have a question. I took someone else's json file for the json file and just redid it for my spritepack (I just changed most of the file). Is it correct? Since I do not know if this is correct from the side of authorship or something. Is it possible to do this at all, and if so, then it was necessary to indicate whose file you took?

**Comment by ThePotatoGuy** [comment]
That is fine, JSONs are not art.

**Comment by Nikv2005** [comment]
okay then
