### ISSUE TITLE
[Suggestion] - I don't have the options in scary story time?

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7698]
I love listening to scaries, but once I clicked too fast and have to read the whole story again, that happens quite a lot lol. So why I cannot see the history?

**Comment by ThePotatoGuy** [comment]
History should still be visible. However, some lines are removed off the history for effect - not entire stories, though.

**Comment by Ulti70895** [comment]
Oh yeah, I completely forgot about that. But isn't that better to enable auto or history or things like that?

**Comment by ThePotatoGuy** [comment]
What do you mean? The History screen is not related to the auto option.

**Comment by Ulti70895** [comment]
I meant this one. 
![image](https://user-images.githubusercontent.com/88768397/131782114-5dece136-ad6d-4565-82f1-8a5f5279f860.png)

**Comment by ThePotatoGuy** [comment]
yes, that menu is locked during stories so the scary effects are consistent. I don't think we'll be changing that at this time.

**Comment by Ulti70895** [comment]
I see, thank you.
