### ISSUE TITLE
[Suggestion] - Add a way to change your birthday

### ISSUE THREAD

**Issue by Liltoad64** [Monika-After-Story/MonikaModDev#7699]
When I told Monika my birthday, I got the date and year wrong, and I want to change it because I don't like that it's not my actual birthday. I would be very glad if you did this! (I ain't going to do it myself because well... I can't code)

**Comment by Ulti70895** [comment]
Oops, I feel sorry about that. But isn't that Monika asked you to double-check before confirming your birthday? Imagine after a birthday of someone and then they change it to another date like right the day after. Wouldn't that be uncool? (my opinion)

**Comment by Liltoad64** [comment]
You do have a point, but I just wanted to be able to change it because it was like, 3:00AM when I set it (I was really tired as you could imagine) , I said that I got the date wrong but I didn't, I just wanted to be able to change it for others to be able to.

**Comment by ThePotatoGuy** [comment]
> I said that I got the date wrong but I didn't

so you input the date correctly, then?

**Comment by Liltoad64** [comment]
What I meant was I got the year wrong, but not the date. (Ex. My birthday is 7/10/2001 but I mistakenly put 7/10/2000. That just bugs me for some reason. Sorry for all the confusion.

**Comment by PongMaster69** [comment]
Already implemented. You should be able to change it on your birthday.

**Comment by Liltoad64** [comment]
... Does that mean I have to wait basically a whole year to change it? Or can I change my computer's date and do it that way?

**Comment by lunulae** [comment]
To my knowledge that is false, you cannot change it on your birthday.
The only thing you can do is restore a persistent from before the time that she asked you about your birthday. If it was very recently, you may still have an auto-generated backup in this timeframe.

**Comment by Liltoad64** [comment]
But... I don't want to lose all my affection... I am so confused.

**Comment by Ulti70895** [comment]
Oh, so that did not happen recently then? And btw, Monika once said that you should not mess things up like changing the date on your computer. But, there was a time I watched a video that represented that changing the date should not result in anything bad.

**Comment by Liltoad64** [comment]
I don't know, I sort of just want the devs to make it clear if there is a way, but if there isn't, they should add a way.

**Comment by Booplicate** [comment]
There's *a reason* why you cannot change your birthdate. Instead you confirm it **multiple** times before setting. If there's even will be a way to change birthdate, there will be a huge penalty for doing so.

**Comment by Ulti70895** [comment]
x.x it seems that there is nothing that can be done here.

**Comment by Liltoad64** [comment]
Okay I give up then. I guess it's just going to be the wrong birthday because of my stupidity.
