### ISSUE TITLE
Improve the interaction with Monika

### ISSUE THREAD

**Issue by Lu1508** [Monika-After-Story/MonikaModDev#7701]
Hi!

Yesterday, I downloaded the "Extra Everything" submod (https://drive.google.com/file/d/1iCzq1J76a1x-qUm-3gnvUYKpErqvaTEC/view) with the new dialogues like headpat or boop and I loved them

However, I think we can make it even better if, instead of "saying" what we will do, we could just "do" it by clicking the part of her body which we want to interact and will be disable when she is talking (like the calendar)

I'm already working on that, but I'm new in rpy, so I don't think I will finish it soon

What do you think? Do you like the idea?

**Comment by Lu1508** [comment]
Ok, I have to confess that I'm **_REALLY_** new in rpy

Can someone tell me what I'm doing wrong, please?

-----------------------------
    if store.mas_calendar.enabled and not store._menu:
        imagebutton:
            idle ("Submods\dot.png")
            hover "Submods\dot.png"
            action Function(monika_boop)
            xpos 675
            ypos 273
------------------------------

It gives me error in the "imagebutton:" line

**Comment by multimokia** [comment]
Can you share the full error?

**Comment by Lu1508** [comment]
sure:
------------------------
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/zz_interactivebuttons.rpy", line 28: expected statement.
    imagebutton:
               ^

Ren'Py Version: Ren'Py 6.99.12.4.2187
-----------------------------

Its says line 28 because this is the full code:

-------------------------------
label monika_boop:
    if mas_isMoniBroken():
        m 6fsc "..."
    elif mas_isMoniDis():
        m 2etd "Did you just..."
        m 2esc "Hmm..."
    elif mas_isMoniUpset():
        m 1wublo "Did you just... boop me?"
        m 1esa "Hehe..."
    elif mas_isMoniNormal():
        m 1wublo "Did you just... boop me?"
        m 1hsb "Ehehe~"
    elif mas_isMoniHappy():
        m 1wubso "Di-did you just... boop me?"
        m 1hub "Ehehehe~"
        m 1esble "You caught me by surprise there."
    elif mas_isMoniAff():
        m 1wubfo "Di-did you just... boop me?"
        m 1hub "Ehehehe~"
        m 5eublb "Did I look cute while I was all surprised?"
    elif mas_isMoniEnamored(higher=True):
        m 1wubfo "Di-did you just... boop me?"
        m 1hub "Ehehehe~"
        m 5esbsb "Did I look really cute while I was all flustered?"
        m 5tfbla "Oh, how I wish I could boop you back right now~"

    if store.mas_calendar.enabled and not store._menu:
        imagebutton:
            idle ("Submods\dot.png")
            hover "Submods\dot.png"
            action Function(monika_boop)
            xpos 675
            ypos 273
-----------------------

**Comment by username11421** [comment]
> ## sure:
> I'm sorry, but errors were detected in your script. Please correct the
> errors listed below, and try again.
> 
> File "game/zz_interactivebuttons.rpy", line 28: expected statement.
> imagebutton:
> ^
> 
> ## Ren'Py Version: Ren'Py 6.99.12.4.2187
> Its says line 28 because this is the full code:
> 
> label monika_boop:
> if mas_isMoniBroken():
> m 6fsc "..."
> elif mas_isMoniDis():
> m 2etd "Did you just..."
> m 2esc "Hmm..."
> elif mas_isMoniUpset():
> m 1wublo "Did you just... boop me?"
> m 1esa "Hehe..."
> elif mas_isMoniNormal():
> m 1wublo "Did you just... boop me?"
> m 1hsb "Ehehe~"
> elif mas_isMoniHappy():
> m 1wubso "Di-did you just... boop me?"
> m 1hub "Ehehehe~"
> m 1esble "You caught me by surprise there."
> elif mas_isMoniAff():
> m 1wubfo "Di-did you just... boop me?"
> m 1hub "Ehehehe~"
> m 5eublb "Did I look cute while I was all surprised?"
> elif mas_isMoniEnamored(higher=True):
> m 1wubfo "Di-did you just... boop me?"
> m 1hub "Ehehehe~"
> m 5esbsb "Did I look really cute while I was all flustered?"
> m 5tfbla "Oh, how I wish I could boop you back right now~"
> 
> ```
> if store.mas_calendar.enabled and not store._menu:
>     imagebutton:
>         idle ("Submods\dot.png")
>         hover "Submods\dot.png"
>         action Function(monika_boop)
>         xpos 675
>         ypos 273
> ```


I think your issue is that you are trying to define an `imagebutton `in a label. `imagebutton `belongs to screens.
You want something like:

`
if store.mas_calendar.enabled and not store._menu:
    show screen dot
`

Move the imagebutton definition to its own separate section as:

`
screen dot:
    imagebutton:
        idle ("Submods\dot.png")
        hover "Submods\dot.png"
        action Function(monika_boop)
        xpos 675
        ypos 273
`

You can also move the conditions with it as:

`
screen dot:
    if store.mas_calendar.enabled and not store._menu:
        imagebutton:
            idle ("Submods\dot.png")
            hover "Submods\dot.png"
            action Function(monika_boop)
            xpos 675
            ypos 273
`

Your action Function(monika_boop) might need to have the label in quotes: `action Function("monika_boop")`

Next, you need to move the `show screen dot` to where you actually want to chow it from. Probably an `init -5 python` block or something, but look at the screens files for examples of when they are shown. You need to move it because right now you're just trying to show the screen from the function it's calling, when you really want it already enabled and for it to call the function after you click the screen. 

Make sure you change the hover image and create an image version you want to see. You're also going to need to figure out some way of mapping the image's coordinates onto where Monika's head/hair is regardless of leaning / normal position poses.

**Comment by Lu1508** [comment]
> I think your issue is that you are trying to define an `imagebutton `in a label. `imagebutton `belongs to screens.
> You want something like:
> 
> `if store.mas_calendar.enabled and not store._menu: show screen dot`
> 
> Move the imagebutton definition to its own separate section as:
> 
> `screen dot: imagebutton: idle ("Submods\dot.png") hover "Submods\dot.png" action Function(monika_boop) xpos 675 ypos 273`
> 
> You can also move the conditions with it as:
> 
> `screen dot: if store.mas_calendar.enabled and not store._menu: imagebutton: idle ("Submods\dot.png") hover "Submods\dot.png" action Function(monika_boop) xpos 675 ypos 273`
> 
> Your action Function(monika_boop) might need to have the label in quotes: `action Function("monika_boop")`
> 
> Next, you need to move the `show screen dot` to where you actually want to chow it from. Probably an `init -5 python` block or something, but look at the screens files for examples of when they are shown. You need to move it because right now you're just trying to show the screen from the function it's calling, when you really want it already enabled and for it to call the function after you click the screen.
> 
> Make sure you change the hover image and create an image version you want to see. You're also going to need to figure out some way of mapping the image's coordinates onto where Monika's head/hair is regardless of leaning / normal position poses.

Thank you very much for the advises and yeah, I know that I should do something about the leaning / normal position poses, but now I'm gonna focus on make the program work

For now I have this code, but its not working

----------------
init -5 python:
    if store.mas_calendar.enabled and not store._menu:
        show screen buttin

screen buttin():
        zorder 200
        if store.mas_calendar.enabled and not store._menu:
            imagebutton:
                idle ("mod_assets\buttons\face\dot.png")
                hover ("mod_assets\buttons\face\dot.png")
                action Function("monika_boop")
                xpos 675
                ypos 273
--------------------------

The error says that: invalid syntax
        show screen buttin

**Comment by username11421** [comment]
Yeah so you're trying to show a screen called buttin but your screen is declared screen buttin(). When it comes to screens, only use parentheses if there's going to be an argument. That change should work. You can see an example of a screen actually being used in the hangman code as the hangman game is a screen.

When you format your posts here, there is a button you can use when putting code in a post here to turn make it clearer, keep indentation, etc. Highlight the code and click it and it'll show properly.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
