### ISSUE TITLE
background

### ISSUE THREAD

**Issue by annaxvz** [Monika-After-Story/MonikaModDev#7702]
hi! i have searched on a lot of places but i still dont get how to add things to the background/giva something to monika that she puts on the background. could anyone help me? :) thank u always

**Comment by annaxvz** [comment]
by the way i know hot to give gifts to her, i just rly dont know how to give her idk, a decoration

**Comment by ThePotatoGuy** [comment]
custom room deco is not supported yet but will be in the future (#5345) 


[closing as duplicate]
