### ISSUE TITLE
Monika is STILL not talking

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7703]
Monika hasn't been talking much. when she does, all she does is sing! have i unlocked everything or?.. 

[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7092155/ev_dump.log)

**Comment by toonziz** [comment]
> Monika hasn't been talking much. when she does, all she does is sing! have i unlocked everything or?..
> 
> [ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7092155/ev_dump.log)

i also followed the steps in the faq

**Comment by Booplicate** [comment]
There's only so many dialogues. You may unlock more over time/with new updates, but you **will always run out of new topics**. You can allow her to repeat herself in the settings.
