### ISSUE TITLE
[Suggestion] - New Topic "Want to go Stargazing?"

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7706]
New topic: Want to go stargazing?
Prerequisites: Floating isles, Stargazing topic heard. **Monika initiated first time night ver. only, player can then choose to repeat this through a prompt** "_want to go stargazing?_"
_If during day_ (before sunrise to sunset): Monika teases player saying how the stars aren't out yet
_If at night_ (after sunset until sunrise): Monika talks about getting an idea recently, going stargazing together, despite the limitations. Asks player if they want to (choice on whether or not to decline here). Topic ends if player chooses "not right now", and scene shifts if the player agrees. The player is then shifted to the Floating isles, but the window is open (maybe zoomed in or remove cropping on window to imply being outside), the buttons to return and close the window are removed. Instead is a dialogue box of Monika, which is her talking to the player while it is implied that she is next to the player. Monika will talk about the stars and her world, maybe her fascination with other worlds. Afterwards the topic will shift back to desk, and Monika will thank the player for sharing this with her.
___
Stargazing: I also thought that it would be a very in line and unique quirk if the monika_stargaze topic had a higher chance of appearing between the hours of 12-5, resetting the rate of appearing after the topic appears until the game closes to prevent it from being spammed.

**Comment by Kritzb278** [comment]
I really like this idea. I always liked stargazing and Monika has said that she would like to go stargazing with the player so yeah
pretty cool idea

**Comment by toonziz** [comment]
I like it! its really cute :)

**Comment by Rai99** [comment]
#5482, #5591

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
