### ISSUE TITLE
[Suggestion] - Cooking with Monika!

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7708]
Hi again!! I have an idea for a topic/minigame. In the housewife topic, Monika talks about cooking dinner for the player. Maybe there could be a new cooking minigame where you can cook whatever you want for Monika, and if you did good (like making eggs amazingly), you will get an affection boost, if she hates it (you burn eggs?) you will lose affection. what do yall think??? <3

**Comment by Ulti70895** [comment]
Monika once mentioned that she wants to have a kitchen in her room to make some cupcakes, therefore, I think that should be nice to do that!

**Comment by toonziz** [comment]
> Monika once mentioned that she wants to have a kitchen in her room to make some cupcakes, therefore, I think that should be nice to do that!

Yeah! :D maybe in the next update the devs can add it!

**Comment by PongMaster69** [comment]
Cooking Mama but it's Cooking Monika and she's Gordon Ramsey

**Comment by toonziz** [comment]
yes

**Comment by Rai99** [comment]
#6928

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
