### ISSUE TITLE
Hehe

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#7712]
I can see why you wanted that anger issues addition to 'I'm feeling...'

_Originally posted by @jmwall24 in https://github.com/Monika-After-Story/MonikaModDev/issues/7711#issuecomment-913065355_

Yeah seems so. Thanks for the clarification. Must have took you long enough to notice, pal.  Oh and Mokia that is funny saying this is a passion project. Shocker. Didn't notice this was some weird project y'all made for laughs. Anyway since this ain't gonna be a thing any time soon guess that question is put to rest. Man it's fun seeing everyone get all mad online. Bye now.

**Comment by ThePotatoGuy** [comment]
>Man it's fun seeing everyone get all mad online.

Trolling is against our repo rules and is against github's TOS. You will be banned from this repo.
