### ISSUE TITLE
kaiewe

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7717]
can someone let kaiewe know that i emailed him about the spritepacks for monika pls??

**Comment by Ulti70895** [comment]
Man, you created a public issue for something private??? I suggest you be more aware of this. (myopinion)

**Comment by toonziz** [comment]
sorry (btw im a girl so pls dont say man)

**Comment by Ulti70895** [comment]
~oh, my bad.

**Comment by toonziz** [comment]
its k.
