### ISSUE TITLE
Chibi Monika easter egg

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#7720]
I saw this Easter egg, but I didn't click on it, and I want to know what happens if I click on it? what is the chance of this easter egg appearing?

**Comment by toonziz** [comment]
> I saw this Easter egg, but I didn't click on it, and I want to know what happens if I click on it? what is the chance of this easter egg appearing?

what is the easter egg? when and where is it i wanna know!

**Comment by Nikv2005** [comment]
> > I saw this Easter egg, but I didn't click on it, and I want to know what happens if I click on it? what is the chance of this easter egg appearing?
> 
> what is the easter egg? when and where is it i wanna know!

When Monika show floating islands there is the chance that on middle Island appears chibi version of Monika
