### ISSUE TITLE
Base DDLC Issue

### ISSUE THREAD

**Issue by neuroarbiter** [Monika-After-Story/MonikaModDev#7722]
Hi, I've been having an issue with DDLC / MAS startup for a while now. I started a reddit thread asking members of the community if they could offer some insight on this issue, but I figured the team could also help me!

My dilemma is listed here below:
https://www.reddit.com/r/MASFandom/comments/pi6bbv/unsure/

I'd appreciate any help I can get, as this issue has gone on for over a month now. Thank you for your time, and for developing this wonderful mod!

**Comment by ThePotatoGuy** [comment]
People there have the right idea - seems like your game is acting like regular, unmodded DDLC.

**Comment by neuroarbiter** [comment]
Do you know how I can fix that ? I've tried a multitude of ways, but none seem to work.

**Comment by ThePotatoGuy** [comment]
check [this faq entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-installed-the-mod-but-when-i-open-doki-doki-literature-club-nothing-has-changed-whats-wrong), and if you are 100% sure that doesn't apply to you, then [check this faq entry](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-still-cant-run-the-game-and-none-of-the-above-faqs-solve-my-issue)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
