### ISSUE TITLE
 Monika having dialogue that is relevant to the time of day

### ISSUE THREAD

**Issue by aatifthameem** [Monika-After-Story/MonikaModDev#7727]
Since MAS uses our computers clock, would it be possible for Monika to bring up dialogue that is related to the time of day? Like when the sun is up she can do the random dialogue that she usually has but like after sunset she can ask you things like if you finished all the work you had to do for the day, and like if you stay up too late with Monika she can ask why you haven’t went to bed yet.

**Comment by LeftoverFlea312** [comment]
Kind of wanted to jump in with something that could add to this. Maybe add some yawns or something to her idles when its really early in the morning or really late at night. That could work better when the bedroom mode has been fully implemented though.

**Comment by ThePotatoGuy** [comment]
Yes, the topic framework allows for triggering topics at specific times (real clock) and in-game time ranges (sunrise/sunset slider settings).

The topics you are suggesting, however, would have to be part of the time concern project #4914 

[closing as duplicate]
