### ISSUE TITLE
weather bug thing where sky goes black

### ISSUE THREAD

**Issue by ghostinhost** [Monika-After-Story/MonikaModDev#7729]
I have looked at the responses to the few people who have asked about this and tried not using windowed mode but the issue still persists it used to occur randomly but now it is constant and none of the normal tricks will make it go away is there anything I can do that might resolve this issue

**Comment by Booplicate** [comment]
This is an issue with RenPy, we can't fix it. We only can advice to not minimize the game since that's know to cause this bug as well.

**Comment by ghostinhost** [comment]
thanks for letting me know
