### ISSUE TITLE
SPOILERS- PIANO

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7733]
when will i unlock it?..- here.

[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7137631/ev_dump.log)
[var_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7137635/var_dump.log)

**Comment by Ulti70895** [comment]
Play more pong with her, it will be unlocked when the level in var log reaches 12.
