### ISSUE TITLE
Heart ahoge <3 aw

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7736]
![Screen Shot 2021-09-10 at 7 51 57 AM](https://user-images.githubusercontent.com/82217573/132856182-8afd69f1-f1b8-43ee-ab25-b165d5f75b45.png)

are there new ahoges? and if i wanna add new ones, can i justt copy and paste one of the jsons for the ahoges and edit it?

**Comment by kkrosie123** [comment]
There are 10 random ahoges that you have a 50% chance of getting every morning. They are not spritepacks.

**Comment by kkrosie123** [comment]
![9672A83C-47CF-44AF-9C85-72AAA0656D83](https://user-images.githubusercontent.com/52429850/132856956-545b191a-4387-42d5-9a30-20d41e74701d.jpeg) he
![8FE518DF-8179-4EB3-B5B2-5E660BCBA040](https://user-images.githubusercontent.com/52429850/132856959-8d7fd380-30f7-4380-96ea-01fe3d5b70bb.jpeg Here is the actual heart ahoge that I made for the game.

**Comment by kkrosie123** [comment]
![678AE2CB-7376-4CA5-AE5F-24EFBEFD230C](https://user-images.githubusercontent.com/52429850/132857200-5e238c74-2dfd-4a32-a712-742bf8a96acc.jpeg)

**Comment by hlepnamingblyat** [comment]
How did you modified Monika's room?
How can I do that? I just can't find anything or any tutorial for it.

**Comment by toonziz** [comment]
i got photos from the room selector submod, and i tok a room and renamed it
to spaceroom

**Comment by AsuraShun** [comment]
What submods are you using?
