### ISSUE TITLE
[Question] - Persistent and Mods

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#7739]
So I'm planning on moving Monika because I'm clearing my PC (resetting it to clear up various viruses I've accumulated over the years) and for MAS I have installed some mods. If I move the persistent do I need to have all of the mods (accessories, etc.) that I previously had installed on my current MAS so that I don't get an error? Like if I move the persistent to a non-modded version of the game will it work?

- Update: I've decided to take the entire folder (on top of the persistent) but still I'm curious

**Comment by Booplicate** [comment]
You don't have to move spritepacks (and usually submods), but you won't be able to use those until you install them again. There shouldn't be any errors because of that.

**Comment by ThePotatoGuy** [comment]
you probably will have to regift those spritepacks, but no errors would occur.


[closing as resolved]
