### ISSUE TITLE
Adding Timed Menus

### ISSUE THREAD

**Issue by TacticalTriangle** [Monika-After-Story/MonikaModDev#774]
Adding timed menu responses. This could be used in various ways especially using tricks as the link below indicates, Dynamic timed responses. This addition to the mod could open up things like, Monika getting impatient if you wait a long time to answer a question. Monika commenting on how long it took you to answer a question, best example of this could be during the book discussion that is planned later on as a system to prevent players from just looking up the information rather then reading it. Things like Monika quizzing you on your knowledge of a topic or things of that nature. I'm sure there are even more ways to use this system in other ways but for now this is all I could think of.
[Here is the cookbook page for this.](https://www.renpy.org/wiki/renpy/doc/cookbook/Timed_menus)

**Comment by therationalpi** [comment]
Those seem like really good uses of timed menus! Great suggestions.

**Comment by ThePotatoGuy** [comment]
Good news everyone. 

I've added a special background timed screen thats generic. You pass in a number of seconds and a label to jump to, and it does the rest of the work. No need to set vars beforehand.

```renpy
# background timed jump screen
# NOTE: caller is responsible for hiding this screen
# 
# IN:
#   timeout - number of seconds to time
#   timeout_label - label to jump to when timeout
screen mas_background_timed_jump(timeout, timeout_label):
    timer timeout action Jump(timeout_label)
```

This will be in (and referenced) when I'm finished with adding additional chess dialogue.
