### ISSUE TITLE
[Bug] Wrong Window Reaction

### ISSUE THREAD

**Issue by Kritzb278** [Monika-After-Story/MonikaModDev#7740]
![image](https://user-images.githubusercontent.com/86920344/132943616-4305be61-bacd-4353-857d-b656fb380877.png)

In the above image, you can see that I was watching a YouTube video, but I have gotten the Reddit Reaction. I have no clue why this could've happened, other than the fact that the word "Reddit" was in the URL. This is very confusing.

**Comment by username11421** [comment]
It's looking at the active tab's text. So if you have Github open but the github page is "reddit clone" or something, you should expect to see the reddit window react; or likewise if you have reddit open but the reddit page is a discussion titled "YouTube deletes <famous_youtuber_here>'s account!" or something, I believe you'll see window react for YouTube and not reddit.

**Comment by Kritzb278** [comment]
Ohh okay
that explains it
