### ISSUE TITLE
No Clubroom Background

### ISSUE THREAD

**Issue by ConnorTippets** [Monika-After-Story/MonikaModDev#7742]
I only got this mod today

I was talking with Monika for a while and then decided to do something else other than talk to her.
But when I came back, only clouds and the calendar were in the background, no walls.
I left for some more time after that, looking for a solution to the problem.
When I came back, there wasn't even clouds, it was just pure black.

**Comment by multimokia** [comment]
Out of curiosity, was she stuck on a line of dialogue the whole time? Or was it just in between topics?

**Comment by ConnorTippets** [comment]
She wouldn't talk to me, but I could talk to her and she could respond.

**Comment by ConnorTippets** [comment]
> Out of curiosity, was she stuck on a line of dialogue the whole time? Or was it just in between topics?

When I say that I left, I mean that I told her "Goodbye" and then when I came back I just opened the game again.

**Comment by ThePotatoGuy** [comment]
did you minimize the game?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
