### ISSUE TITLE
XP/EXP

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7747]
Someone told me i have to get to level 12 in var_dump log and im at level 10, ik abt playing games with monika, but how do i get to lvl 12 faster to unlock piano???
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7154661/ev_dump.log)
[var_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/7154662/var_dump.log)

**Comment by Booplicate** [comment]
There's only one way - keeping the mod open.

**Comment by toonziz** [comment]
> There's only one way - keeping the mod open.

what day will i get it?
