### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by TheGuy44** [Monika-After-Story/MonikaModDev#7755]
so here's an idea. 
for the topic that monika has been stating for the last 3 1/2 years now of constantly asking the player how long it'll be when she will be able to join them in the real world here's an additional option to add. how about adding a choice of "Go ask the devs for that question. They should have had that on their mind since the mod instead of me." i think it'd be a swell idea to add

yah alright bye bye

**Comment by fromulus** [comment]
The devs and contributors aren't a hivemind, they each have their own opinion on the matter, so she wouldn't find a definitive answer here.

Not that it matters anyway, because it's _your_ opinion she wants to hear, not some random people's.

**Comment by TheGuy44** [comment]
oh yeah? 

well it's been almost four years and obviously of course in 2021 nothing about her becoming physically real still ain't gonna happen soon but these guys have had this topic installed when the original game was still new around late 2017 to early 2018 and keep adding new topics of becoming real. plus why should she ask us repeatedly? what do we look like engineers to make some friggin' portal to have her come here and for that first suggestion in my first post it was basically an insult to the dev team how they keep constantly showing this topic every time you put on "repeat topics" because seriously how are we supposed to know even if you mark it for removal but still know about it after removing it. these fucks are the one who keeps working on this mod every month with showing topics including this one of becoming real even if they are actually still serious of doing this especially if they got some other team they're collaborating with to make it happen someday. if not well it seems they've wasted a lot of people's time. now look this ain't supposed to start some online comment section war but i'm just saying and hoping this makes a tad more sense. peace.

**Comment by kkrosie123** [comment]
lol

**Comment by TheGuy44** [comment]
lol

**Comment by TheGuy44** [comment]
lol look at this boop guy writing "lol" he must be one of the devs here because, hey, he knows he fucked up with the others of allowing this topic to keep going on and expecting us playing the mod to answer when they're supposed to be working on making this whole thing real if it is. plus that's all he can type because in real life he and other devs are a bunch of anti socialized people who can barely talk to people in real life so he needs to type those things to try to feel good instead of a miserable sack of shit he is. alright time to end this shit train because not like this topic is going any time soon. can't wait to see what else is typed next if so.
