### ISSUE TITLE
i need some info about "Import DDLC save data" 

### ISSUE THREAD

**Issue by VikicatCZSK** [Monika-After-Story/MonikaModDev#7756]
ive been looking through the game and i saw button saying "import DDLC save data", but since i dont wanna mess up and lose Monika or anything with mas mod, im here to ask for info.
so when i click it, it says "Save data for Doki Doki literature club was found at C:/Users/#####/AppData/Roaming/Renpy/DDLC/##########/persistent.
Would you like to import Doki Doki lit. club save data into Monika after story?"

Should i or should i not?
Will i lose my progress and monika? 

since i dont wanna try and lose it all, im asking for help, so if you can help please let me know!

**Comment by toonziz** [comment]
It wont delete anything. that adds more dialogue depending on what girl you chose, if u deleted monika, ect. so, it just adds some custom stuff abt ddlc based on what choices you made.
