### ISSUE TITLE
How to change a choker into a hairclip?

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7757]
hii! so, i have some elf ears for Monika, i put it in the body section, they went behind her normal ears, i tried putting them in the choker section, did the same thing, now i wanna try hairclips, but something in the spritepack is set to be a choker, and i cant put it as a hairclip. help please!!

**Comment by ThePotatoGuy** [comment]
this is part of #7737 - closing in favor of that issue
