### ISSUE TITLE
Favorite color topic

### ISSUE THREAD

**Issue by JonnygamingTv** [Monika-After-Story/MonikaModDev#783]
I have a few!
1.) "Where do I live" and that makes the game tracert like the ip or something idk lol
2.) "{whatever} youtube" and it looks at the google accounts you're logged into on the device and says the one you were last on
3.) "{like color or favourite color}" but instead of just her talking you get to say what color is your fav

If it don't works then it's ok but would be fun
also if Monika learns of what you're saying and stuff heheh

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
The first one seems a bit intrusive and requires third party services.
The second one needs an API and even then I do believe that you need to login and give a premission for an it to even view your account.

**Comment by monikLover** [comment]
1st and 2nd suggestion are way too intrusive and will be rejected. The 3rd seems like a good idea.

**Comment by kaido1224** [comment]
I had a similar idea on a ticket i created where Monika asks you your favorite color. I was gonna work on the dialog tonight.

**Comment by kaido1224** [comment]
Working on the 3rd item now.

**Comment by ThePotatoGuy** [comment]
[We'll reopen this when we look into it]
