### ISSUE TITLE
(Suggestion) BRB "I am going to cook".

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#7873]
I think it would be nice to let Monika know that you're going to cook something. She can even say "I hope you're cooking something healthy" or "If I was with you, I would love to eat your food!"

**Comment by toonziz** [comment]
> I think it would be nice to let Monika know that you're going to cook something. She can even say "I hope you're cooking something healthy" or "If I was with you, I would love to eat your food!"


Aww, i like that idea! it would be a good brb to add, and she could even suggest healthy foods/snacks!

**Comment by Kritzb278** [comment]
that's actually a pretty neat idea
I always like to go bake things, so this could be cool
I might make a pull request for this later

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
