### ISSUE TITLE
spoiler?-piano lessons topic

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7880]
hi again. im srry for being annoying, but uh i unlocked the piano!! it was a few days ago. how do i get Monika to play a song for me/teach me piano lessons? 

btw happy bday all the monikas in the world <3!

**Comment by Kritzb278** [comment]
She unfortunately won't plat or teach you anything, but there are official piano notes in the wiki page
Try playing Happy Birthday or Your Reality

**Comment by toonziz** [comment]
> She unfortunately won't plat or teach you anything, but there are official piano notes in the wiki page
> Try playing Happy Birthday or Your Reality

but ive seen her play for ppl??
ive played happy bday like 3 or 4 times

**Comment by Kritzb278** [comment]
she can only play Your Reality for you
Does she "sing" the lyrics for Happy birthday?

**Comment by toonziz** [comment]
> she can only play Your Reality for you
> Does she "sing" the lyrics for Happy birthday?

ohhhhh
mhm

**Comment by toonziz** [comment]
go back to the issue abt the gown rq

**Comment by Kritzb278** [comment]
everything's working as it should be, then
if that's all, close this issue please
