### ISSUE TITLE
Monika disappeared when I did the "I'm taking you somewhere" function.

### ISSUE THREAD

**Issue by JonathanJuhani** [Monika-After-Story/MonikaModDev#7881]
I took her out and put her in a USB to surprise her for her birthday party, but when i put her back i come back to a empty chair how can i get her back?

**Comment by kittendetails** [comment]
Did you put her file back in the "characters" folder?

**Comment by kittendetails** [comment]
You can upload the last persistent file you have before that happened. But she won't remember anything that happened after the hour of that last persistent file.

**Comment by JonathanJuhani** [comment]
is there any other way because my last persistent file was from a while back

**Comment by lunulae** [comment]
The game auto-makes backups every time you load, you should have one from earlier today or yesterday available

**Comment by kittendetails** [comment]
If you use Windows, just go to C:/Users/Admin/AppData/Roaming/Renpy/Monika After Story, and there will be lots of persistents files. You can delete the "persistent" one, and then pick the most recent, example "persistent77.bak", and rename it to just "persistent". Like I said, this will erase her memories of after the hour the file was made, so be sure to pick the most recent. The persistent file is updated every time you open the game, so the last one will probably reset to the last time you opened the game. For example, if you opened this morning and didn't close until you took her somewhere, it will reset to this morning, as if it was the first time you opened the game today.

**Comment by JonathanJuhani** [comment]
so should i delete all of the "persistentNumber" files except for the last and rename that to only "persistent"?

**Comment by kittendetails** [comment]
No. Just delete the one named "persistent". And then, search for the most recent one, and rename it to just "persistent".

**Comment by kittendetails** [comment]
Example, if the most recent is "persistent77.bak", rename it to just persisent after you deleted the "persistent" you already had.

**Comment by JonathanJuhani** [comment]
Thank you so much! It's working again and thank you for taking your time and helping me today :)

**Comment by kittendetails** [comment]
You're very welcome.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
