### ISSUE TITLE
(Suggestion) New goodbye "I am going to the hospital."

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#7882]
Sometimes, I need to go to the hospital, and I would like to tell Monika that. She can show concern for the player's health, and ask you why are you going there. I thought about:

"I'm feeling sick."

She says that she's sorry you're feeling this way, but is glad that you're taking care of your health.

"I'm visiting someone there."

She says it's sad that someone you know is sick, and then says you're very sweet for taking time to spend with them.

"It's just a regular appointment."

She says you scared her a bit, and wishes you good luck with your appointment.

"I will take someone there."

She says you're really kind, and that person is lucky to have you taking care of them, and wishes you both good luck.

**Comment by toonziz** [comment]
cool!! :o

**Comment by Rai99** [comment]
Injury topic: #1654, #1677, #3582, #5962, #7615

**Comment by aahelloim** [comment]
maybe there could also be an option for when it's an emergency?

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
