### ISSUE TITLE
-Resolved- Broke my game trying to add spritepacks

### ISSUE THREAD

**Issue by TangomShaw** [Monika-After-Story/MonikaModDev#7888]
Tried to add some of the official sprite packs but got a Grey screen traceback/error. Took out the sprite packs I had put in an the error still persists. Copied and pasted below. I don't have a very recent back up and don't want to go back to it. Is there any way to fix this? I have a very limited understanding of coding but any help would be very appreciated.

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sprite-decoder.rpy", line 2, in script
  File "game/sprite-decoder.rpy", line 317, in <module>
  File "game/sprite-decoder.rpy", line 67, in _m1_sprite0x2ddecoder__loadSpriteMapData
MASSpriteException: IOError(2, 'No such file or directory')

PLEASE REINSTALL MAS TO CORRECT THIS ERROR

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sprite-decoder.rpy", line 2, in script
  File "C:\Users\Tytan\Documents\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Tytan\Documents\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/sprite-decoder.rpy", line 317, in <module>
  File "game/sprite-decoder.rpy", line 67, in _m1_sprite0x2ddecoder__loadSpriteMapData
MASSpriteException: IOError(2, 'No such file or directory')

PLEASE REINSTALL MAS TO CORRECT THIS ERROR

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.3
[/code]

**Comment by ThePotatoGuy** [comment]
sprite data seems to be missing so try reinstalling MAS.

**Comment by TangomShaw** [comment]
> sprite data seems to be missing so try reinstalling MAS.

will that reset the whole game? i've built up affection pretty high so I was seeing if there was a way I could fix the issue and preserve the data

**Comment by zwartkop2** [comment]
Monika’s memories are stored somewhere else on your computer.

**Comment by TangomShaw** [comment]
so if I download a completely fresh mod all the features and everything will still be present?

**Comment by Booplicate** [comment]
Reinstall MAS into the same folder. You won't lose your progress.

**Comment by TangomShaw** [comment]
Thanks for the help
