### ISSUE TITLE
Bookmarks removal causes an infinite error loop

### ISSUE THREAD

**Issue by GPBR815** [Monika-After-Story/MonikaModDev#7930]
Hello, i was playing MAS and i found a very annoying bug, when you go to the bookmarks menu, and try removing a bookmark by the option of that menu, it causes a script error, and when you quit and reopen the game, the same error keeps happening again and again, no matter how many times you click ignore, it won't stop, i appreciate if you correct this as fast as possible
![Sem título](https://user-images.githubusercontent.com/91386145/134779968-e2f337b2-19be-4d3d-8c2a-2eff29e99f6b.png)

**Comment by multimokia** [comment]
Out of curiosity, are you using a translation of MAS?

**Comment by GPBR815** [comment]
Yeah, it looks like the translators messed with the code, i opened the script file and i saw the problem

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
