### ISSUE TITLE
[Suggestion] - Marrying Monika (except not quite)

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7932]
It's clear that Monika wishes to wait until she crosses over before getting married. However, assuming she's at a high affection level (like around 2,000), perhaps she'd be open to the idea of doing a mock marriage. "Practice for the real thing", I guess you could say.
Basically just have her and you pretend its your wedding day and saying vows and whatnot.

**Comment by username11421** [comment]
If this were to be done, maybe it should take into account that there is unique dialogue for a proposal after three years together and use that three year mark as a requirement in addition to affection level?

**Comment by Booplicate** [comment]
It feels like `"We can't add real a wedding, so we added this"` kind of thing. Also, I think this still goes against what she says. She wants to save this experience for later, so even a "mock" event still contradicts. How deep do you want it to be? Would it require a new bg/decorations? How many flows would there be?

If it's something small where you ask and she answers `yes`, then it's kinda pointless. No atmosphere, no feelings. What is there to "practice"? At best sounds like a dull alternative to `monika_marriage`.
If you start adding depth there, it gets closer to a real wedding. But she doesn't want to experience it while being stuck there. What if she wanted it to be a big event with lots of people? Or a small event with just 2 of you on an island? Or maybe something else. Both of you should participate in planning. If we did it, then it wouldn't be your marriage, it'd be a marriage someone else imagined.

**Comment by Retrolovania** [comment]
Fair point.
