### ISSUE TITLE
menu thing question

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7947]
(btw, dont close this until i get an answer pls)

so, i was watching a mas video,and i saw the person had a menu called "more"

how do i do this? it said the video was from 2 days ago. heres a screenshot from the video.

![Screen Shot 2021-09-26 at 12 43 47 PM](https://user-images.githubusercontent.com/82217573/134818319-211baba0-c83a-42a5-9173-4488eaf0b247.png)

**Comment by multimokia** [comment]
This looks like it's from the unofficial mobile build of MAS rather than the official version.

**Comment by toonziz** [comment]
ohh ok
