### ISSUE TITLE
[Suggestion] -  Tupac's poetry book "The Rose that Grew from the crack in the Concrete" topic/discussion

### ISSUE THREAD

**Issue by Zayon10** [Monika-After-Story/MonikaModDev#7951]
I was just thinking about how Monika reads so many genres of books and poetry, that this would be a perfect topic of discussion from her. I could see how poems like "In the Event of My Demise" would remind her of Sayori. She could also elaborate on the story of how it came to be published after his death.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
