### ISSUE TITLE
Typo: Dandere mentioned twice in "Types of Deres" topic

### ISSUE THREAD

**Issue by CGanimated1227** [Monika-After-Story/MonikaModDev#7952]
I'm pretty sure that the second type that she mentions is a "Deredere" as that fits the second definition she uses.

![image](https://user-images.githubusercontent.com/34112217/134825737-28151f72-9656-4a8c-a33a-36b4bb0087b8.png)

**Comment by Booplicate** [comment]
Unofficial content.

**Comment by CGanimated1227** [comment]
Oops. Never mind then, I must have forgot.
