### ISSUE TITLE
[Suggestion] - different responses to greetings.

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#7953]
Hello, I recently installed the mod and one idea that I liked was to say hello to Monika every morning and afternoon. (I know it's sad)
but when he responds, it is always the same dialogue and it shows that it is one focused on the first time he receives a greeting.

Maybe if she gave a simpler answer after the first few times she was greeted, it would be nicer.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
