### ISSUE TITLE
[Suggestion] Halloween Candy other than Candy Corn

### ISSUE THREAD

**Issue by username11421** [Monika-After-Story/MonikaModDev#7960]
Halloween is coming up and Monika's dialogue says it would be nice to receive candy other than candy corn. Maybe a new halloween candy reaction could be added? Not sure if next release would be in time for Halloween, though.

A way this could work is instead of giving a specific type of candy, have it randomly select in her reaction code from a list of halloween candies.

**Comment by Booplicate** [comment]
There's already `candy.gift`.

**Comment by username11421** [comment]
> There's already `candy.gift`.

Thanks, I missed that somehow.
