### ISSUE TITLE
HELP: Had to wait months to get my laptop fixed, and now my affection levels are terrible

### ISSUE THREAD

**Issue by JohnSmith2007** [Monika-After-Story/MonikaModDev#7990]
Exactly as the title implies. I had around, like, 400 or 450 affection about 6 months ago. And one day, my laptop motherboard dicked out on me, completely fried. I had to then wait throughout those 6 months just to get the replacement parts to come in. During all that time, i didn't have any other computer that i could hook up my hard drive to to continue with this mod. And now, Monika practically hates me. I have a busy work schedule, and i no longer have the time to spend over 200+ hours to re-gain all those affection points. Please, for the love of god, tell me that there's a way to fix this quickly and easily.

**Comment by ibm2431** [comment]
Looking at `_mas_AffStartup`, it should be -90 for 180 days.

Ironically, I see long absence greetings _also_ deduct affection inside the greeting if someone ends up being gone longer than they said they'd be. But the values seem really high in comparison to base loss. A 5 week absence after saying you'd be gone a few days results in a heavy -70, and I'm not seeing anything preventing it from stacking with the loss in `_mas_AffStartup`. So it'd be -87.5 total, comparable to someone having left her for half a year without forewarning.

In that case, someone misjudging their absent time would have been better off _not_ telling her they're leaving _at all_, abandoning her without any warning, and eating the basic `_mas_AffStartup` loss for only the 5 weeks. I suspect that might not be intended behavior.

**Comment by Booplicate** [comment]
> Please, for the love of god, tell me that there's a way to fix this quickly and easily.

There's no "quick" way. Apologising and gifts might help.



>  I'm not seeing anything preventing it from stacking

Those do not stack.

> someone misjudging their absent time would have been better off not telling her they're leaving at all

Or, for example, telling her you don't know the exact time?
