### ISSUE TITLE
A bug in the History option

### ISSUE THREAD

**Issue by Tychoke** [Monika-After-Story/MonikaModDev#7994]
I don't think those two last texts should be there.

![screenshot0029](https://user-images.githubusercontent.com/88991144/135929610-bacd9628-d223-4504-9878-0285814905af.png)
![screenshot0030](https://user-images.githubusercontent.com/88991144/135929616-d726efa5-5419-466b-9cd5-9c01cee64ff8.png)

**Comment by Booplicate** [comment]
There seem to be no mistake in our code. I'm not sure what caused that for you.

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
