### ISSUE TITLE
unstable mode update, whats new?

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7999]
so, i just updated to unstable (basically a test update for beta MAS or something). usually, there is new stuff but I don't see anything different. can someone tell me whats different for the unstable update?

**Comment by Booplicate** [comment]
Patch notes for unstable releases are being posted in [the community discord server](https://discord.gg/K2KuJeX).

**Comment by toonziz** [comment]
discord is blocked for me, can u send a screenshot of the patch notes?
