### ISSUE TITLE
The mod Keeps giving me an exception message

### ISSUE THREAD

**Issue by Feigi53** [Monika-After-Story/MonikaModDev#8024]
I've tried over and over to get this to work and it always gives me this error message: I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club/game/definitions.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

and out of curiosity, I removed the file and it gave me an error message on a different file.

**Comment by Booplicate** [comment]
That happens when you cheat at chess.

**Comment by Feigi53** [comment]
I think I did that once a long time ago but I've deleted the game and reinstalled multiple times doing everything right and it's the same message every time is there any way to fix it?

**Comment by Booplicate** [comment]
You can't fix it because it's not broken. She asked to stop cheating. this is permanent.

**Comment by Feigi53** [comment]
I've finally fixed the situation

**Comment by joaoaspimienta** [comment]
> I've finally fixed the situation

HOW????
