### ISSUE TITLE
Traceback issue (Sorry If I put this request in the wrong area, I'm new here)

### ISSUE THREAD

**Issue by 7Chilllz7** [Monika-After-Story/MonikaModDev#8047]
Hello everyone, So I have a small problem that turned into a huge mess... I looked for "common/000atl.rpy'" in my rpy folder but didn't or couldn't seem to figure it out. I'm sure it's an easy fix but I'm not sure how to fix it, if one of you lovely people can give me A hand I would greatly appreciate it. Thanks!

![image](https://user-images.githubusercontent.com/91029661/137838480-6b6ce669-bf36-4402-968d-3f42cba93760.png)

**Comment by multimokia** [comment]
Screenshot your DDLC directory please?

**Comment by 7Chilllz7** [comment]
Nvm, I figured it out. Although I lost all my spritepacks but at least I have her back. Thank you!
