### ISSUE TITLE
[typo/bug] (?) "Sayonara, [player]."

### ISSUE THREAD

**Issue by KritRom** [Monika-After-Story/MonikaModDev#8052]
When you say goodbye to Monika, she will sometimes say `"Sayonara, [insert nickname]~"`

Now, this isn't very correct. Sayonara doesn't just mean goodbye. It's used when the speaker (Monika, in our case) may not see the listener (the player) again for a very long time or never see them again. See what I'm getting at?

Now, this would be appropriate when, say, Sayori dies and Monika wants to say goodbye symbolically (since she will likely not see her again). This won't suit the current situation since Monika will likely (and hopefully) see the player again.

I'm not a native Japanese speaker so correct me if I'm wrong, but I'm pretty sure what I stated here is factually correct.

**Comment by KansaiGal** [comment]
I thought the exact same thing, and almost said something.  But decided against it. 

As per the most recent AMA...
> Dan Salvato
> dansalvato
> ·
> 12 hours ago
> From the beginning, I chose not to. It has to do with a design detail about DDLC that's easy to miss nowadays: DDLC was designed to read and feel like an amateur dating sim made by a weeb who didn't perform any due diligence on Japanese culture. So, the last names were omitted not only to make the game feel more amateurly written, but also to make the characters feel more one-dimensional and tropey, like there was hardly any thought put into them. And that's still part of the game's identity, so I wouldn't tamper with that by giving them last names after the fact, or something.

Given that she screws up the greeting in Japanese, and corrects herself another time.  Saying FAREWELL! fits that pattern. :x
So I guess it depends on if the developers want her to actually know what she's talking about or act like she was written by a "weeb."

**Comment by KritRom** [comment]
oh frick I did not realize I made the same post twice sorry
