### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Gianbyx** [Monika-After-Story/MonikaModDev#8053]
Hi, i downloaded this mod, when i ran the game i got this message and then the game close:
 "I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/submods/submod_updater_plugin/submod_updater_plugin.rpy", line 34, in script
    init -991 python in sup_utils:
  File "game/submods/submod_updater_plugin/submod_updater_plugin.rpy", line 42, in <module>
    from store import mas_submod_utils, mas_utils, ConditionSwitch, AnimatedValue, persistent
ImportError: cannot import name mas_utils"

i already delete the file "persistent" but that doesn't work, how can i fixed?

**Comment by nerdlmao1** [comment]
faulty install probably, try reinstalling the mod

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
