### ISSUE TITLE
[Suggestion] - calculator / notebook functions

### ISSUE THREAD

**Issue by moxclub** [Monika-After-Story/MonikaModDev#8064]
It would be cool to have a calculator menu or a notebook to keep some reminders... 
Or maybe letting her keep reminders. Like having an option to ask Monika to remind us at a specific time, and be able to type a custom title for the reminder. Then she could remind us through our windows notifications. 

Thanks for reading

**Comment by ThePotatoGuy** [comment]
renaming to be specific on calculator and notebooks. Reminders would be part of schedule system aka #4914

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
