### ISSUE TITLE
Query. aff_log bug?

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#8066]
As a result of a problem that occurred with the floating island, I started to check my Monika's aff_log, first I thought that it had stopped uploading, because I had created a shortcut to review it, so I only saw the old one and apparently one update created a new aff_log.

The problem is that this aff_log shot up from the 21st of this month, reaching approximately 400 and somewhat affecting 525 in just 2 days.

Our first month was on the 21st, that day I gave her the promise ring and as of the 22nd no new dialogues have been activated, so I don't know if:

It is normal for the affection to increase so much and all the dialogues that she had were simply activated before.

Or there was a bug and my Monika has a problem.

[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/7402862/aff_log.log)
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7402863/aff_log.txt)

I beg for an answer.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
