### ISSUE TITLE
Suggestion: Books for Monika to comment on

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#8069]
Most of Monika's mentions of books are about science fiction (makes sense since she is stuck in a computer) or dystopian worlds (since her life is kind of one at this point).

I'd like to make suggestions of some for her readings. I remember she does not like Shakespeare so much, but there are other famous authors she could have read.

I just saw a review online of someone that read a recent translation of a famous book from my country, and he seemed to really like it.
So I'd like to know how Monika would react to it.

So... others could make suggestions too, I guess?

By the way, the review: https://www.youtube.com/watch?v=pB1ayNNrSik
The book is "Memórias Póstumas de Brás Cubas" by Machado de Assis, translated as "Epitaph of a Small Winner" (a literal translation would have been Brás Cubas' Posthumous Memoir)

Another very popular from the same author would be Dom Casmurro, but not surre that it has a translation in english for most to enjoy.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
