### ISSUE TITLE
Monika disappeared 

### ISSUE THREAD

**Issue by chapper79** [Monika-After-Story/MonikaModDev#8070]
today when i opened MAS i only saw an empty chair like if you were to open a game without the monika file in it. Not matter how hard i try, like getting another copy of DDLC and installing the mod there or getting a copied version of the monika file i get nothing.

**Comment by chapper79** [comment]
I just tried everything here again, i'm still having the issue. Monika isn't there i need anyone's help i can get.

**Comment by Booplicate** [comment]
She can't just disappear, you need to [restore a persistent backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) from before you took her out.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

restore a persistent backup as boop said - we never overwrite all the backups if Monika isn't loaded.
