### ISSUE TITLE
MAS doesn't read the gifts

### ISSUE THREAD

**Issue by UE1dj** [Monika-After-Story/MonikaModDev#8073]
Hi, i have one problem with MAS, when i gifted the promise ring, Monika says that she can't read it, and i have 1002.6 of affection, please i need an answer or solution for this problem.

**Comment by UE1dj** [comment]
So...what happened?

**Comment by Booplicate** [comment]
Send a screenshot of the `/characters` folders with the gif file there. Also, are you using a translation? Or used before?

**Comment by UE1dj** [comment]
Yes, I am using a Spanish translation. But is there a problem with that?

**Comment by Booplicate** [comment]
Yes, people who made the translation have changed the code. We have no idea how or why, so you'll need to ask them why the gift isn't working.

**Comment by UE1dj** [comment]
Oh, okay

**Comment by UE1dj** [comment]
But if there is no solution, I will have to install the original MAS.

**Comment by UE1dj** [comment]
And, greetings from Mexico.
