### ISSUE TITLE
[suggestion] have player and Monika play piano together

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#8077]
I think it would be very difficult to program.

But incredibly romantic, if the player and Monika played tunes together.

It would also be a very good turorial, letting inexperienced players make simple chords, while Monika plays the more complex.

and something amazing for players with musical experience.

As Monika is learning, she could even make mistakes sometimes, making the experience more real and giving rise to dialogues.

https://www.youtube.com/watch?v=dCfK0MSefCQ

**Comment by ThePotatoGuy** [comment]
renamed title to be accurate. not sure if we'd do this since I still want to make the piano have an osumania mode.

[closing until we look into it]
