### ISSUE TITLE
(suggestion) Monika using swear words

### ISSUE THREAD

**Issue by chapper79** [Monika-After-Story/MonikaModDev#8093]
I would like to see if after the swear word conversation there could be a question of something along the lines of "Are you okay with me using swear words from time to time" and if the player clicks yes and the player isn't in sensitive mode she will swear from time to time. I feel that the conversation would be more important that way.

**Comment by ThePotatoGuy** [comment]
can't say that Monika will swear, but she could at least know that you don't mind swearing.

[closing until we look into it]
