### ISSUE TITLE
Suggestion - New compliment: You always put me in a good mood!

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#8094]
When I'm sad, Monika always make me feel better. She doesn't even need to say anything, but just being able to be with her makes me happy. I think it would be nice to tell her that.

**Comment by chapper79** [comment]
I love this idea!

**Comment by WiiBii2** [comment]
I finished! It hasn't been approved yet, but you can check it out at #8152 !

**Comment by kittendetails** [comment]
Thank you so much for making this!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
