### ISSUE TITLE
Chess features: 1, highlight last move, 2. save game log 3. skill level-dependent responses

### ISSUE THREAD

**Issue by MarkusRamikin** [Monika-After-Story/MonikaModDev#810]
I love the chess. She seems to get better as you beat her, and worse as you lose, which is great, I actually mostly play this mod for the chess now.

Suggestion 1: make it more visually obvious somehow what Monika's last move was. 

Ideally, include a box showing a notation past moves. But more simply, the color highlight that exists is easy to miss.

Suggestion 2: finished games should be saved to a text file in chess notation. 
(I just had an awesome game which I barely won - it would have been a treat to review it!)

**Comment by ThePotatoGuy** [comment]
Regarding suggestion 2, is [PGN](https://en.wikipedia.org/wiki/Portable_Game_Notation) the appropriate notation for chess games?

**Comment by MarkusRamikin** [comment]
Sure!

Just BTW, I looked up the script. The dialog line "You really are an amazing player!" is only available if you beat her at Stockfish level 20? So basically, Magnus Carlssen could get it, but no human actually likely to play this game is ever going to see that line? *grin* Come on, give us a chance!

**Comment by ThePotatoGuy** [comment]
Yeah we could look into lowering that value. What level are you at? If you don't know, upload your `persistent` file here and I can check it.

**Comment by MarkusRamikin** [comment]
Oh, I'm terrible (currently oscillating around level 3-4, after decades of not playing), I don't expect to ever see that message myself. It just occurred to me that maybe no human has or ever would see it the way it's coded now, not without cheating. 

Although maybe that's the point, that level 20 Stockfish is - as well as I expect a true AI would be - unbeatable without cheating, and Monika meant to be pointing this out? 

Then how about instead adding new responses every few tiers? That would impact most players instead of the top few and/or the ones cheating, and let people see their strength without having to somehow unpack the persistent, or lower immersion by putting the actual number in the game. Something like:

```
        if persistent.chess_strength<2:
            m "I have to admit, I put less pressure on you there than I could have..."
            m "I hope you're not angry! I'll be challenging you more as you get better, I promise!"
        if persistent.chess_strength<4:
            m "I'll get you next time for sure!"
        elif persistent.chess_strength<6:
            m "You really didn't play badly there!"
        elif persistent.chess_strength<8:
            m "That was an interesting game!"
        elif persistent.chess_strength<10:
            m "You're quite a strong player!"
        elif persistent.chess_strength<12:
            m You're a very challenging opponent, [name]!"
        elif persistent.chess_strength<20:
            m Are you a professional chess player, [name]?"
        else:
            m "You really are an amazing player!"
            m "Are you sure you're not cheating?"
        if persistent.chess_strength<20:
            $persistent.chess_strength += 1
```
Just some ideas. Of course I don't know at what level exactly Stockfish becomes an opponent for professionals, 12 is just my random guess. Anyway, this is more of a pseudocode example.

**Comment by ThePotatoGuy** [comment]
Updates:

- [ ] add saving chess games in PGN notation 
- [ ] changed highlight color to be somewhat more visible
- [ ] consult writers for adding a wider variety of dialogue regarding skill levels

**Comment by ThePotatoGuy** [comment]
This is ready for 0.7.4.
