### ISSUE TITLE
[Suggestion] - For the piano

### ISSUE THREAD

**Issue by Itnew30** [Monika-After-Story/MonikaModDev#8102]
Hello, I have not experience in programmation but I want to contribute to this mod to improve the MAS experience. (By the way, I'm sorry if my english is bad.) I have to think about the ideas... However I have a first one: When one plays the piano; that would be great if the click of the computer's mouse worked. Moreover for people who have a touch screen, I think it would be easier to play. (Currently one can only use the keyboard.)

It's not a big idea. If I have new ideas I will send them to you. I hope my contributions will help.
Thank you~

**Comment by ThePotatoGuy** [comment]
this was initially considered but it was easier to just use keys.

[closing until we look into it]
