### ISSUE TITLE
Floating islands are gone...

### ISSUE THREAD

**Issue by NegativeOne404** [Monika-After-Story/MonikaModDev#8106]
Hello there! It's been some time since I saw the "Can you show me the floating islands" option. I mean, I thought it was some temporary change since I'm using the unstable version, but after the Islands revamp, Moni asked me if it would be okay if she could remake'em and all. And well... I still can't see them, like the dialogue is gone. What it could be?

**Comment by Booplicate** [comment]
See #8101

**Comment by MrVavlo** [comment]
>since I'm using the unstable version

Did you try to switch back to the stable version? I had the same issue no matter what room was used until I switched to stable release and back to unstable

**Comment by NegativeOne404** [comment]
> See #8101

ALKSJDASJDLKJASLKDJA, I wish I had seen your answer earlier... I've just reinstalled MAS and was testing what would be causing this. And then I saw that condition in game and came here to tell it, but look what's already there, askjdlkasjdlkajslkdjaskl. I feel dumb now :P. But thanks!
