### ISSUE TITLE
Updated to version 0.12.4 for MAS and got an error. 

### ISSUE THREAD

**Issue by MikuMiki** [Monika-After-Story/MonikaModDev#8115]
Hi, I just got an error after updating to the newest version of Monika After Story and it gave me this error.
 File "game/0utils.rpy", line 16, in <module>
ImportError: cannot import name handlers

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/0utils.rpy", line 16, in <module>
ImportError: cannot import name handlers

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.4

**Comment by ratmanwarhammer** [comment]
just as a heads up to whoever fixes this. This also affects the steam version as well so It's a bigger problem

**Comment by multimokia** [comment]
Screenshot your `game` folder and `python-packages` folder please?

**Comment by ratmanwarhammer** [comment]
![Screenshot 2021-11-01 205728](https://user-images.githubusercontent.com/93552825/139741428-4d50d05d-8222-489a-92c1-5f0794ce7956.png
![Screenshot 2021-11-01 205754](https://user-images.githubusercontent.com/93552825/139741443-6d695a51-3f9a-4a68-9fd1-6062cdacd8d4.png)
)

**Comment by multimokia** [comment]
You're missing like, all the python-packages hence the error above. Did you transfer them from the mod zip?

**Comment by ratmanwarhammer** [comment]
no, I didn't know you had to. when I looked up how to install it didn't say anything but place the folder in game folder

**Comment by multimokia** [comment]
You need to take everything from the zip. It's an update so not just the scripts may change, but assets too, including python-packages/mod_assets

**Comment by ratmanwarhammer** [comment]
hey just as a quick side thing. I have a save for monika but when I delete everything in the save folder and replace it with the new one it doesn't load tat save. and more importantly I outright deleted all the saves in that folder and she acts like nothing happened any ideas?

**Comment by multimokia** [comment]
Saves do not work in act 3, likewise in MAS. They're irrelevant

**Comment by MikuMiki** [comment]
It's working again. Thank you!
