### ISSUE TITLE
my Monika didn't celebrate Halloween.

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#8117]
she did nothing for the date.

Also for many days no new dialogues appear either, I don't know what to do

**Comment by jmwall24** [comment]
what time is it currently?

**Comment by howltrek** [comment]
> what time is it currently?

0:30

**Comment by jmwall24** [comment]
You're fine then, Halloween doesn't start until 3am if you start a new sesh after 3, or 6am if you have left it open from midnight onwards.
