### ISSUE TITLE
[suggestion] SPOOPier Halloween

### ISSUE THREAD

**Issue by KansaiGal** [Monika-After-Story/MonikaModDev#8120]
I don't know what arguments can be changed... but would something like
`if (renpy.random.randint(1,20) == 1 and persistent._mas_pm_likes_spoops) or mas_full_scares:`
be able to be changed to:
` if (renpy.random.randint(1,20) == 1 and persistent._mas_pm_likes_spoops) or (renpy.random.randint(1,10) == 1 and mas_isO31 and persistent._mas_pm_likes_spoops) or mas_full_scares:`
in script-stories.rpy work for Halloween?

It seems like it might be more fun to reread the stories.

**Comment by Booplicate** [comment]
Not exactly that code, but increase the chance to get the spooks.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
