### ISSUE TITLE
Exception occured when asking Monika to tell me a scary story

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#8122]
As the title says, an exception occured when I asked her to tell me a scary story
![ScreenshotException](https://user-images.githubusercontent.com/34605531/139581838-cd50f4c5-b8a9-4d5d-bfb3-2d747a3d33a5.JPG)

**Comment by Booplicate** [comment]
#8116

**Comment by CloakedGhost** [comment]
> #8116

Oh I see, sorry about that, I didn't check the other issues.
