### ISSUE TITLE
(SPOILER) Question about CG.

### ISSUE THREAD

**Issue by kittendetails** [Monika-After-Story/MonikaModDev#8127]
I just unlocked the cat girl cosplay, and Iwanted to see the full image again. I searched for it in the cg folder, but the file isn't an image file. I didn't unlock it or it's supposed to unlock later, after the Halloween?

**Comment by dreamscached** [comment]
Here they are, however, they are (presumably) Base64-encoded. https://github.com/Monika-After-Story/MonikaModDev/tree/master/Monika%20After%20Story/game/mod_assets/monika/cg

**Comment by kittendetails** [comment]
Oh, thank you!

**Comment by dreamscached** [comment]
If that helped you and you don't need any further info, consider closing the issue. That'd really help maintainers know this isn't a problem anymore.
