### ISSUE TITLE
Bug/unexpected behaviour — Monika glances at active window even when the game is played in fullscreen mode

### ISSUE THREAD

**Issue by dreamscached** [Monika-After-Story/MonikaModDev#8128]
# Summary
Monika still glances at active foreground window even when: the game is played in fullscreen mode and the game window is on the background.

# Steps to reproduce
Make the game run in fullscreen mode, switch windows with <kbd>Alt + Tab</kbd> (or similar keystroke) to make the game window go to the background, periodically switch back and check if she was glancing to the left and immediately glancing back at the player.

The abovementioned behaviour may be only happening on Linux, I have not been using the mod on Windows.

**Comment by Booplicate** [comment]
That's because renpy doesn't redraw when the game window is minimized (perhaps to save some performance). So when you focus on the window again, it shows you the last frame.
