### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Alexxx1407** [Monika-After-Story/MonikaModDev#8131]
I mean everything now is fine so far. But it would be nice to make her feel alive, not saying the same thing again and again even after a game or anything. Maybe new games, or new interactions! i would love to code for this but to be fair i don't really understand how to help.... if you could send me a mail of how i do it clearly i would help for sure!!! anyway good work and keep it up(alexvin80@outlook.fr) is my mail.

**Comment by WiiBii2** [comment]
If you would like to contribute something to the project, the guidelines are [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines). Looking at Monika after story -> game -> topics.rpy in GitHub is a great start if you would like to learn how to code. I learned all of my renpy skills from looking at the original code of DDLC, as well as looking up things in a guide. It isn't too hard to at least program new dialogue for Monika.

> it would be nice to make her feel alive, not saying the same thing again and again even after a game or anything

I am actually working on this issue right now! It should be complete by the end of this month. If you do end up learning more about renpy coding and would like to look at what I'm curently looking on, I'll link it right [here](https://github.com/Monika-After-Story/MonikaModDev/pull/8089).

**Comment by Alexxx1407** [comment]
Hi, i know and i already created two new moods and two compliments!! Keep up the good work tho and do your best. Thanks!

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alexxx1407** [comment]
Oh and is it possible to give the new moods i created and the new compliments too ? To je apart of the main game ?

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alexxx1407** [comment]
And is there any way i can donate you a bit to reward you're work ?

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Booplicate** [comment]
Monika After Story is a non-profit project.

**Comment by Alexxx1407** [comment]
Okay! Well keep up the good work then!

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WiiBii2** [comment]
Yeah, I do this stuff for fun, but there is indeed a way to add your changes to the game. If you go to the pull requests tab and click create pull requests, you can have your code reviewed by the moderators to be added to in-game.

**Comment by Alexxx1407** [comment]
I see !! Okay welp I'm a do a good one !!

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alexxx1407** [comment]
Where do i put my code tho? [Image]
Saying i need to choose different branches ?

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WiiBii2** [comment]
Ok so here's the rundown:
1. Go up to the right-hand side of the MAS Github page and click on fork. This should take you to your MAS page, where you own and can make changes to the project. 

2. Click on the button that says `master` and change it to `content`. This is the branch that you want to edit code on. Branches are different divisions of MAS to sort the code that is being changed. For instance, if someone made a change to `content` and then made a pull request (PR), it can be updated to the official MAS `content` branch to be merged with the `master` branch. The master branch is the one that pushes the updates to your game from my understanding.

3. Edit the code that you want to edit. This is easier if you download the Github desktop app, but it changes a few steps, so you might just want to stick with the website for now. 

4. Create a PR in the official MAS repository. When you click Pull Request in the menu and click 'create pull request', it will most likely ask you what branch you want to commit. Choose the one that you edited the code on and click 'generate request' or whatever the confirmation code is. If someone comments on your PR asking to change something, they are most likely a mod and are telling you what you need to change in order for the PR to be accepted. 

hope this helps!

**Comment by Alexxx1407** [comment]
Okay! Should be done

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________
