### ISSUE TITLE
Monika can't read gifts

### ISSUE THREAD

**Issue by LadySylvea20082020** [Monika-After-Story/MonikaModDev#8138]
Well, it's exactly as the title says. I tried to send her a gift, namely the Hot Pink Ribbon, she did receive it, but she said that "she couldn't bring it here" and she "couldn't read it well enough". What do I do? I tried to follow the tutorial as closely as I could, but for some reason, it didn't work.

**Comment by Booplicate** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-doesnt-recognize-gifts

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
