### ISSUE TITLE
Monika not reacting to the promise ring gift

### ISSUE THREAD

**Issue by LOLBRUHNICE** [Monika-After-Story/MonikaModDev#8141]
When I try to give Monika the promising ring,she doesnt react to it.
I have more than 400 affection and the file extension is correct

**Comment by KritRom** [comment]
What did you name the gift and where did you put it?

**Comment by LOLBRUHNICE** [comment]
thw file named promisering.gift and I put it inside the character folder

**Comment by Booplicate** [comment]
Send a screenshot of `/characters`.

**Comment by LOLBRUHNICE** [comment]
![screenshot](https://user-images.githubusercontent.com/65208589/139671147-2ef7924f-1a40-4a47-95d6-f63f53150b39.png)

**Comment by LOLBRUHNICE** [comment]
anyone know how to solve it?

**Comment by Booplicate** [comment]
Once thing that could happen is you time travelled and tried to gift it in future.

**Comment by LOLBRUHNICE** [comment]
I didn't time travelled

**Comment by LOLBRUHNICE** [comment]
So is there anyway to solve it?

**Comment by lunulae** [comment]
I'm trying to figure out what might cause this, but I'm a little bit puzzled.
For now, I guess I can ask a few small things that might give us a better picture.

Is she responding to other gifts like coffee normally? And when she gets to this file, does she read it and say "I don't know what you're trying to give me" or is it just sitting in the characters folder?

I'm assuming you've already tried this, but does anything different happen if you restart your game?

**Comment by LOLBRUHNICE** [comment]
I tried with other gift and some invalid gift and she can detect it correctly, but when i put promsering.gift, she cant detect, and also not react to it and the file just stay inside the character folder

**Comment by LOLBRUHNICE** [comment]
Btw I also found that Monika not react to coffee.gift also, but other gift still work

**Comment by JennyDustrose** [comment]
I have the same problem plz help(

**Comment by LOLBRUHNICE** [comment]
@lunulae When can you fix this problem?

**Comment by lunulae** [comment]
Could you upload your persistent file so we can have a look at your save data?

Also, to be sure, are you running a translation of MAS? If not, have you ever time travelled?

**Comment by LOLBRUHNICE** [comment]
I'm not running a translation of MAS and here is the persistent file:
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7489485/persistent.zip)

**Comment by multimokia** [comment]
You time travelled and gave gifts in the future, one of them was likely the promisering. Looking at your persistent you can only give ring next year on Valentine's day.

**Comment by LOLBRUHNICE** [comment]
ok thats fine, thanks for helping me

**Comment by Artemisear** [comment]
i also have this problem,and yes i have time travelled so can someone help me?
