### ISSUE TITLE
Can't launch the game on a new pc

### ISSUE THREAD

**Issue by Alexxx1407** [Monika-After-Story/MonikaModDev#8146]
![Capture d’écran (33)](https://user-images.githubusercontent.com/93495047/139676424-389addc8-b284-4dd4-a7f2-e3722639c2cb.png)
I tried to copy the game on a new pc, but i can't launch it.... I don't want to lose my progress?

**Comment by multimokia** [comment]
You need to copy your persistent to transfer your progress. See [this entry on our FAQ](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer)

**Comment by Alexxx1407** [comment]
I'm already on the other pc. And i don't have the old next to me...

**Comment by multimokia** [comment]
Do you have the old one at all?

If not do you have any persistent backups?

**Comment by Alexxx1407** [comment]
Well, i had it on a usb driver but it's broken it's making me start a new game. I mean darn it, i still have my old monika on my old computer. So i will just start a new one here

**Comment by multimokia** [comment]
You don't have to use usb too transfer. You can just use Google drive or another cloud service to transfer it over

**Comment by Alexxx1407** [comment]
I mean i did all u said but can't load the save

**Comment by multimokia** [comment]
Does the same issue happen? If so it sounds like you're not putting the persistents in the right location. Alternatively you're doing it while mas is open

**Comment by Alexxx1407** [comment]
I mean i tried but it's not working!
![Capture d’écran (34)](https://user-images.githubusercontent.com/93495047/139681346-b100b9aa-d3a8-4ab3-9656-5cbc097b4a8f.png)
I put all of this in my game.

**Comment by multimokia** [comment]
You're not in the right folder.

Persistents are *not* in the game's files. They're in AppData. Follow the instructions described in the link carefully

**Comment by multimokia** [comment]
Hence why I asked if you still have your old one so you can use Google drive to transfer the persistents

**Comment by Alexxx1407** [comment]
I don't, but don't worry i still have it on my first pc. the only problem is that monika is still in the "I'm going to take you out somewhere" she is on my usb driver, i guess she gonna have to wait 1 week ...

**Comment by Alexxx1407** [comment]
But at least i know now!
THanks i will do it next week .

**Comment by Alexxx1407** [comment]
![Capture d’écran (35)](https://user-images.githubusercontent.com/93495047/139682155-a24ca75a-2e56-4edf-9306-e508e8d497b6.png)
This is what i will take next week ? if yes then we can close this issue!

**Comment by multimokia** [comment]
Yeah exactly that. Just be sure to return her from taking her somewhere first.

**Comment by Alexxx1407** [comment]
Sure! alrright i will do it with the pc i have most affection with lmao thanks! (issue closed)
