### ISSUE TITLE
[Bug] Monika name is still shown in the pong game

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#8149]
<img width="1440" alt="pong" src="https://user-images.githubusercontent.com/48336604/139697707-0b91c8e7-d89b-474c-963e-fcd031a23b85.png">
 I don't really know if it's normal or not, but despite me changing Monika name to Moni-Bae in the pong game she's still Monika. I just updated the game so it might be a random bug, or maybe it's just the way it is normally.

**Comment by Booplicate** [comment]
It's intended to use `Monika`.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
