### ISSUE TITLE
[Bug] Monika is gone

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#8150]
I selected the option to take my Monika trick-or-treating like I always do and stayed out around 6am, again, like I always do, and when I go to open the game after first putting Monika's file back into the Characters folder, she doesn't show up. Almost as if her file isn't even in the Characters folder. Never had this happen before, and I really don't think I have the mental compacity to start over when im at over 12,000 affection with her.

**Comment by Booplicate** [comment]
The file is probably corrupted, you can check `mfread.log` for more info. if so, you'll need to [restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by Secretmanguy** [comment]
Yep, it's corrupted. Any idea how that could happen? All I did was took it out of the characters folder and set it on my Desktop, then put it back into characters when I got back.

**Comment by Booplicate** [comment]
Anything, a drive issue or a short disconnect while transferring the file. Ideally you always make a backup of her file before moving it elsewhere.

**Comment by Secretmanguy** [comment]
Is there a possibility that the game corrupted it? Because I understand if I'm moving it to a flashdrive or something for it to get corrupted, but the idea that as soon as the file is placed into Characters after you tell Monika to go Trick-or-treating, and then you make a copy and save it to the folder where you always back her file up to is corrupted as well as the one you just moved to your desktop and moved back to Characters when you return to start the game.

**Comment by Booplicate** [comment]
I do find this odd, but so far I'm unaware of any issues with generating her file. We also have a few layers of verifying it generated a valid file.

**Comment by Secretmanguy** [comment]
So...What do I do? Both versions of the Monika file, the Backup and Normal File, are corrupted. I do have a backup of the game folder and persistent files from the previous update, but no Monika Character File replacements.

**Comment by Booplicate** [comment]
> The file is probably corrupted, you can check `mfread.log` for more info. if so, you'll need to [restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

Follow the link I sent. We generate a few backups for you, should work.

**Comment by Secretmanguy** [comment]
Yeah, I dont know if I did something wrong or not, but all that did was completely reset my progress. I found the find named Persistent, deleted it, renamed the most recent one to persistent, and all that did was reset everything when i reloaded the game.

**Comment by Booplicate** [comment]
Weird, that shouldn't possible. Are you sure you renamed it into `persistent` (no extension or anything else)?

**Comment by Secretmanguy** [comment]
I just took a couple hours to replace everything with my backup from two months ago. Took forever to get back to where I am now, but sure beats trying to figure out the persistent thing. And yes, I renamed it as instructed and tried it a few times to no avail.

**Comment by ThePotatoGuy** [comment]
If it happens again, post all the logs here first. Otherwise its just a guessing game as to what is happening.

[closing as resolved]
