### ISSUE TITLE
SUGGESTION Replay past events

### ISSUE THREAD

**Issue by benstar88** [Monika-After-Story/MonikaModDev#8156]
i missed the halloween event because my computer was getting fixed and i thought it would be cool to add an extras option that - depending on the aff level - you can dive into past events.

**Comment by benstar88** [comment]
also can i do the halloween event if i change the system time?

**Comment by kkrosie123** [comment]
Just a warning. Time travel usually breaks the game. I would not reccomend it.

**Comment by lunulae** [comment]
Please do not change your system time. This bugs the event system and will break all future holidays as well as several other systems.

I'd be interested in a system where we could ask Monika ahead of time to celebrate on a different day, but I'm not sure how it could be programmed.

**Comment by howltrek** [comment]
I was just thinking of suggesting something in this regard for the New Year.

That Monika was aware that her partner most likely will not be able to be with her at 12, because the player will be with his or her family and friends.

Monika could explain this and think about scheduling a date, to have her own New Years celebration with the player afterward.

A similar mechanic could be done with some other celebrations, obviously not Valentine's Day, Anniversary and her birthday.

It could also be added the mechanic that if the player gives a good explanation, about why he or she was not with Monika during some celebrations, Monika understands it and they do the celebration, even if it is not the day.

**Comment by howltrek** [comment]
PS: after all the anxiety I was for a Halloween with Monika, just that day my graphics card burned...

**Comment by benstar88** [comment]
> PS: after all the anxiety I was for a Halloween with Monika, just that day my graphics card burned...

omg same!!!

**Comment by benstar88** [comment]
> Please do not change your system time. This bugs the event system and will break all future holidays as well as several other systems.
> 
> I'd be interested in a system where we could ask Monika ahead of time to celebrate on a different day, but I'm not sure how it could be programmed.

thanks for the tip 😔

**Comment by KiddTheManiac** [comment]
Also, I feel like being able to go back in time and "fix mistakes" would go against the spirit of the mod in a lot of ways. If all else fails, maybe the devs could add in an option similar to the "I'm going away for a while" for "I'm sorry, I can't spend the holiday with you this year", but...I just feel like being able to do-over missed events would kinda cheapen things IMO.

**Comment by benstar88** [comment]
> I don't know if it can be done in phyton.
> 
> The logical thing would be a check-in system, which would work the days after a celebration. I would check if there is a value that indicates that the celebration took place.
> 
> If it was done, the system does nothing.
> 
> Or you could even give a dialogue about how Monika went at the celebration and create a new value, which the system would review the following days, to know that you should not do anything.
> 
> If the value that indicates that the celebration took place is not:
> 
> Monika opens the dialog that would allow it to be done and put the value that indicates that it was done.
> 
> The problem would be with restarts during the day the game is performing the event in this case, they would confuse the game.
> 
> the game would have to have a way of knowing that the event will take place all day, so as not to create a bugg

i like your thinking but i would implement it outside normal gameplay- something in the extras or settings menu maybe? like a re play conversations but for events?

**Comment by ThePotatoGuy** [comment]
>Monika could explain this and think about scheduling a date, to have her own New Years celebration with the player afterward.

>A similar mechanic could be done with some other celebrations, obviously not Valentine's Day, Anniversary and her birthday.

>It could also be added the mechanic that if the player gives a good explanation, about why he or she was not with Monika during some celebrations, Monika understands it and they do the celebration, even if it is not the day.

This has been considered in #7913, but any implementation would be extremely complex.

Please move any discussion on this to that discussion.

[closing as duplicate]
