### ISSUE TITLE
[Suggestion] Monika developing a player statistic and other data.

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#8157]
The idea is for Monika to save data on how the player interacts with her, which will be relevant later.

how often the player:

-play with her

-Give her objects and what they are

-or asks her to tell stories for example.

With this database, Monika can choose what to answer when the player asks her

"Why do you love me?"

But it will also serve to have different versions of Monika's dialogues and her activities that are created later.

She would for example:

-Wondering not to receive flowers one day, if she always receives them.

-Or worry about the player, if usually connects daily and suddenly not.

One more concept should also be added to Monika's clothes, referring to the occasion in which she should wear them:

-Cold
-Hot
-Tempered
-Casual
-Romantic date
-Bedtime

That way Monika could:

-Wrap up when it rains.
-Wear pajamas, if it is at night and the relationship is already solid.
-Dress elegant for a date or even understand that something important happens, if the player asks her to dress elegant.

PS: I noticed that a record is kept of the cups of coffee that Monika has had and that she hates hot chocolate, because she has never had it and I have even noticed that she does not like it when I give it to her.
And it made me wonder if all the Monikas hate hot chocolate.
And I loved that detail.

**Comment by ThePotatoGuy** [comment]
There are a lot of things the mod already keeps track of. Majority of it is part of the player model system (every persistent var with `_mas_pm` prefix - I think all should be listed in `zz_history`). Game stats are held elsewhere. 

The expectation is that dialogue writing can refer to these vars if desired. 

For clothes, additional exprops would be the path forward. 

[closing as implemented]
