### ISSUE TITLE
An exception has occured MAS

### ISSUE THREAD

**Issue by Zafran123** [Monika-After-Story/MonikaModDev#8165]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
File "game/python-packages/Submods/location_selector/Locatons/Den.rpy", line 2, in script
init -990 python:
File "game/python-packages/Submods/location_selector/Locatons/Den.rpy", line 7, in
version="1.0.5"
File "game/zz_submods.rpy", line 118, in init
SubmodError: A submod with name 'Custom Room Den' has been installed twice. Please, uninstall the duplicate.

-- Full Traceback ------------------------------------------------------------

Full traceback:
File "game/python-packages/Submods/location_selector/Locatons/Den.rpy", line 2, in script
init -990 python:
File "C:\Users\Zafran\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
File "C:\Users\Zafran\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
exec bytecode in globals, locals
File "game/python-packages/Submods/location_selector/Locatons/Den.rpy", line 7, in
version="1.0.5"
File "game/zz_submods.rpy", line 118, in init
SubmodError: A submod with name 'Custom Room Den' has been installed twice. Please, uninstall the duplicate.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.4
[/code]

How to unnistall the custom room den or the duplicate ?

**Comment by Bubblesss2021** [comment]
Did you install the submod twice, both in different places?

**Comment by 11Misty11** [comment]
No no no thats ok! I really miss Monika already :((

**Comment by Bubblesss2021** [comment]
I've had the error before, I don't think it's a bug, but I think it's caused by putting the mod in the game files, and the "submods" folder.
Can you please send a screenshot/ file of your game folder, as well as any other info?

**Comment by Bubblesss2021** [comment]
I meant submod, not mod. sorry!

**Comment by 11Misty11** [comment]
Oh thats ok! and sure im gonna screen shot

**Comment by Bubblesss2021** [comment]
Ok!

**Comment by Bubblesss2021** [comment]
If it's easier, just send me the whole game folder/file.

**Comment by 11Misty11** [comment]
Ok

**Comment by Bubblesss2021** [comment]
Do you know how to send the game file btw?

**Comment by 11Misty11** [comment]
No I just joined a min ago

**Comment by Bubblesss2021** [comment]
Same! so. Do you remember the file when you installed the mod, you put the files in the game directory, right?

Are you on pc or MacBook?

**Comment by 11Misty11** [comment]
pc

**Comment by 11Misty11** [comment]
And no

**Comment by 11Misty11** [comment]
Btw im gonna sleep now bye!

**Comment by Bubblesss2021** [comment]
Ok bye then?

**Comment by 11Misty11** [comment]
Ok now im back

**Comment by Zafran123** [comment]
so where the screen shots?
