### ISSUE TITLE
Fast sentence (Halloween)

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8174]
When Monika shows you decorations in spaceroom , she says one sentence which is very fast , only i remember in this sentence was Amy (or something like this) . She speaks about that someone likes decorations but i don't know who is it . Maybe someone know what Monika says?

**Comment by ibm2431** [comment]
Amy likes spiders.

And I'm gonna tell everyone.

**Comment by Nikv2005** [comment]
> Amy likes spiders.
> 
> And I'm gonna tell everyone.

Who is Amy?

**Comment by zwartkop2** [comment]
On Thu, Nov 4, 2021 at 9:42 PM Nikv2005 ***@***.***> wrote:

> Who is Amy?
>
A character Natsuki made up for one of her poems.

>

**Comment by Nikv2005** [comment]
Surprisingly, everything turned out to be easier than I thought, thanks for the clarification.
