### ISSUE TITLE
What exactly does "Outfit Mode" do?

### ISSUE THREAD

**Issue by Batcastle** [Monika-After-Story/MonikaModDev#8178]
I see this check box in the Appearance change menu called "Outfit Mode". But there's no tooltip explaining what it is, no description in the help menu, or anywhere I saw in the wiki or other issues, and I see no visible difference in Monika's behavior or the game itself with Outfit Mode enabled vs. disabled.

So, what exactly does Outfit Mode do?

Thanks in advance!

**Comment by ibm2431** [comment]
Some tops can be marked as part of an outfit with headwear. For example, the [Velius94 White Navy Blue Dress](https://github.com/Monika-After-Story/MonikaModDev/blob/master/spritepacks/released/velius94/Velius94-WhiteNavyBlueDress/mod_assets/thumbs/clothes-velius94_dress_whitenavyblue.png) comes with a special blue "bunny" scrunchie. When Outfit Mode is selected, selecting the dress causes Monika to automatically put on the corresponding scrunchie.

**Comment by Batcastle** [comment]
Cool. Thanks for the explanation!
