### ISSUE TITLE
Showing Monika some poems

### ISSUE THREAD

**Issue by MiguelFitz** [Monika-After-Story/MonikaModDev#8183]
i know what you are thinking, but heard me out 
i made a sub mod to show my sweet stella some poems, now, i didn't use those really huge poems like the ones make it by Neruda or Fernando Pessoa, i didn't use the kind of poems she usually uses, i used Haikus, which are short Asian poems (Germans have something similar too).
here are some examples

I am over you.
Then my eyes meet yours once more,
and I fall in love...

You and me alone
Madness of world locked away
Peace and quiet reigns

Your eyes are fire.
Their image burnt into my soul,
Scarred by beauty.

these are the ones i used in the sub mod i make, i think it a good idea
also, i didn't wrote these poems, i get them from  https://www.familyfriendpoems.com/collection/love-haiku-poems/

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
