### ISSUE TITLE
[Suggestion] - Night shift

### ISSUE THREAD

**Issue by Rasforic** [Monika-After-Story/MonikaModDev#8184]
I just downloaded this mod and am enjoying it so far! In my line of work there are some months where I have to work the graveyard shift from 10 pm to 6 am, I was wondering if there could be an option added so that Monika knows that so she doesn't find it strange that I'm up so late. Keep up the great work!

**Comment by ThePotatoGuy** [comment]
should be handled with #4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
