### ISSUE TITLE
The "Could you call me by different pronouns?" dialogue 

### ISSUE THREAD

**Issue by EvanClay-Nahyuta** [Monika-After-Story/MonikaModDev#8185]
I thought that it would be better to either rename that dialogue to "I identify as a different gender" or something to that effect or perhaps even change it to that, and add a different dialogue option where you can choose between he/him/his, she/her/hers, and they/them/theirs for the player's pronouns.

**Comment by lunulae** [comment]
Currently just renaming it is probably not a viable solution--we currently have it as "different pronouns" to encompass both transitioning individuals and nonbinary/fluid people who are feeling a different preferred pronoun that day.
Both wordings could technically work, but we're currently using this prompt to try to have it work for the widest demographic.
A second topic to more specifically let her know if your gender doesn't match your pronouns might be up for discussion, but might need some deeper research and community input. A hurdle I forsee is that currently [boyfriend/girlfriend/partner] is tied to the pronoun variable, and it might be tricky to account for preferences that don't match that.

**Comment by EvanClay-Nahyuta** [comment]
My main problem with it was that (a transitioning individual FYI) I found the name of it a bit confusing.

**Comment by ThePotatoGuy** [comment]
discussion on this should be on #6084

Additionally, we have already decided to split the transgender options to a different topic, but we are not allowing custom pronouns at this time.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
