### ISSUE TITLE
HELP: Piano Error (No JSON object could be decoded)

### ISSUE THREAD

**Issue by JohnSmith2007** [Monika-After-Story/MonikaModDev#8195]
Ok, so I'm trying to make a custom piano version of Through The Fire & Flames by Dragonforce, but i keep getting this error in pnm.log ;

No JSON object could be decoded

I have no clue of what it means nor how to fix it.

Heres what i have so far in the json file;
[TTFAF.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7491739/TTFAF.txt)

**Comment by ThePotatoGuy** [comment]
did you name the file with the `.json` extension?

**Comment by JohnSmith2007** [comment]
> did you name the file with the `.json` extension?

Yes

**Comment by JohnSmith2007** [comment]
I literally have no clue of why its not working. It has the correct file extension, and i don't see any errors about any bits of code in the log, so what the hell?!

**Comment by JohnSmith2007** [comment]
I need to show Monika my shredding skills damnit! 🤣

**Comment by multimokia** [comment]
Your json is invalid. You have trailing commas and a missing value

**Comment by JohnSmith2007** [comment]
> Your json is invalid. You have trailing commas and a missing value

What are "trailing commas", and what value am i missing?

**Comment by ThePotatoGuy** [comment]
Use a JSON formatter ([like this one](https://jsonformatter.org/json-editor)) to check the problems with your JSON.
