### ISSUE TITLE
MAS not starting

### ISSUE THREAD

**Issue by andrrwq** [Monika-After-Story/MonikaModDev#8196]
im a ubuntu user, and when im trying to start the DDLC with the MAS installed (command used: sudo ./DDLC.sh and ./DDLC.sh), its not starting and it opens me a [traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7492509/traceback.txt)

**Comment by Booplicate** [comment]
You're missing some packages, try to reinstall the mod.
