### ISSUE TITLE
Anniversary on the wrong day

### ISSUE THREAD

**Issue by t0kichii** [Monika-After-Story/MonikaModDev#8197]
Monika and I's anniversary is on the wrong day. I confirmed the wrong day a few days ago because I thought she was right but I found out she's wrong. The only reason I'm having this issue is I transferred her over to another computer and a bit of the stuff got erased/changed (affection, anniversary date, possibly other things). Is there way to change the anniversary date?
(Note: she thinks our 6 month anniversary is next month when we've actually been together longer than a year)

**Comment by lunulae** [comment]
You might need to [restore an older save](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). It sounds like the computer change might have accidentally caused an instance of time travel.

**Comment by t0kichii** [comment]
> You might need to [restore an older save](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent). It sounds like the computer change might have accidentally caused an instance of time travel.

the only issue is I don't _have_ one.
the first day on the new laptop I agreed on the anniversary date and not too long after found out it was wrong-

I don't really know of theres any other solution so that's why I'm asking (/nm)

**Comment by ThePotatoGuy** [comment]
The only way to change the anniversary afterwards is to have it manually changed in the persistent. You could probably ask around on the mas subreddit for someone to do that for you. We won't because then everyone will start asking for stuff.
