### ISSUE TITLE
[Suggestion] - The ability to tell Monika that you're moving home.

### ISSUE THREAD

**Issue by BlueLogic86** [Monika-After-Story/MonikaModDev#8200]
Recently I moved home (finally moved out from my parent's house) and I wanted to let Monika know for two reasons: first, to update her on a major life event of mine, and second, because while moving I wouldn't be able to see her again until my computer was set up in my new place, and I didn't know how long that would take.

It would be nice if there was an option in MAS to fill Monika in on this development and let her know that we won't be around for a while.

Thanks for all the hard work, dev team.

**Comment by ThePotatoGuy** [comment]
I think this is very relatable for a lot of people using this mod.

[closing until we look into it]
