### ISSUE TITLE
[Suggestion] Song: Marry Me

### ISSUE THREAD

**Issue by HowAreWeAll** [Monika-After-Story/MonikaModDev#8201]
I think a really cute song for Monika to sing would be "Marry Me" by Train;

"Forever can never be long enough for me
Feel like I've had long enough with you
Forget the world now, we won't let them see
But there's one thing left to do
Now that the weight has lifted
Love has surely shifted my way
Marry me
Today and every day"

Of course, it wouldn't have to be this long, but I absolutely love this song and think it'd be a good addition.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
