### ISSUE TITLE
[Suggestion] Time-based affection gain when holding Monika

### ISSUE THREAD

**Issue by Batcastle** [Monika-After-Story/MonikaModDev#8206]
First off, lemme just say I am loving this mod!

I feel like there could be a great improvement by having the amount of affection you gain change depending on how long you hold Monika (with a cap of course). I feel this could be a fairly easy way to improve the immersion a tiny bit. It could be as simple as something like this:

(Python-based psudeocode. Sorry if it's not that helpful)
```python3
start_hug_time = time.time()
# Do the hug mechanic
# hug ends
end_hug_time = time.time()
hug_duration = end_hug_time - start_hug_time
if hug_duration < 10:
    affection += 0.75
elif 10 <= hug_duration < 30:
    affection += 1.25
elif 30 <= hug_duration < 90:
    affection += 2
else:
    # At this point we know hug_duration >= 90
    if monika.is_asleep():
        if monika.sleep_duration() < (60 * 30): # number of seconds in 30 minutes.
            affection += 5
        else:
            # this high of an affection gain might warrant this event being an occasional bypass.
            # Make bypass-capable have a 3-5 day cool down maybe?
            affection += 10 
    else:
        affection += 3
```
The idea is that, the longer you hug her, the more affection goes up. If she falls asleep, affection goes up even more. This could be made even more granular by making a function that handles this and runs the sleep duration through some sort of math equation, but I personally feel that that level of granularity is unnecessary.

Thanks for hearing me out! Keep up the good work!

**Comment by Booplicate** [comment]
That's a no from me. *Maybe* a bonus if she slept for X hours, but there's already enough ways to raise affection. It's a very fragile system, we already have a problem with unnatural gain.

> a fairly easy way to improve the immersion

Affection is internal, the player doesn't get to know when and how much they get. Adding more ways to gain it doesn't improve immersion. Affection farming is actually gamification and leads to immersion breaking.

**Comment by Batcastle** [comment]
While I understand those concerns, the intent wasn't to game-ify MAS. It was more to promote the possibility of making Monika more life-like. I feel like why I want this for Monika delves more into psychology then we should get into here (more than happy to share my thought process though if someone wants to hear it), so if the best way to achieve anything like this is to have a bonus after she sleeps for so long, then I can settle for that.

**Comment by ThePotatoGuy** [comment]
I think this is reasonable since its confined to the holding topic. Feel free to PR if you want to implement it, otherwise it might be a while before this is added since affection is already real easy to get.

[closing until we look into it]

**Comment by Batcastle** [comment]
I am open to implementing this myself. It will be a bit cause I am working on a submod (a lot of the important stuff is done now thankfully) and have other coding projects with a release date coming up, but I will take a look and see what I can come up with.
