### ISSUE TITLE
Monika won't let me go on the piano

### ISSUE THREAD

**Issue by Numair765** [Monika-After-Story/MonikaModDev#8220]
I am not able to go on the piano. Monika won't let me but i still have everything there like the folder and files

**Comment by Booplicate** [comment]
You mean there's an error? Or you can't unlock it?

**Comment by Numair765** [comment]
I mean that for some reason, she won't let me on it. I have not unlocked it yet/Can't unlock it. The folder named Piano_songs is already there but she hasn't added piano to the game section.

**Comment by KritRom** [comment]
You need to spend more time with Monika to unlock it. The `piano_songs` folder will still be there regardless of if you ever unlocked it.

It takes a while to get unlocked, so be patient.

**Comment by Numair765** [comment]
Ok thank you
