### ISSUE TITLE
Hatsune Miku not available

### ISSUE THREAD

**Issue by PlutoMarionette** [Monika-After-Story/MonikaModDev#8221]
Since the update, I have been unable to equip the hatsune miku costume. All the files are there, but the costume does not appear when I ask to change her outfit. I've already tried to regift it to her through the gift file, but she says that she cannot read the file well enough

**Comment by Booplicate** [comment]
Can you follow [these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)?

**Comment by PlutoMarionette** [comment]
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7536621/spj.log)
I have the json for the orcaramelo twintail hair and clothes, but not for the hairband (don't think you can gift that anyway). Prior to the update monika could wear these, and I am currently at 352.2 affection.

**Comment by Booplicate** [comment]
![Capture](https://user-images.githubusercontent.com/53382877/141754166-a23f7e94-e99a-4692-849c-dbc0476058ae.PNG)

Looks like something happened to the images. They are either corrupted or missing. You have the same issue with `orcaramelo_ponytailbraid`. I can only suggest to reinstall the spritepacks. Also I noticed you're using onedrive, it can cause odd issues like this, so if you can, disable it.

**Comment by PlutoMarionette** [comment]
I deleted and reinstalled everything which fixed the issue, thanks for the help!
