### ISSUE TITLE
[suggestion] sleep comments

### ISSUE THREAD

**Issue by MLGHitsHeadshots** [Monika-After-Story/MonikaModDev#8242]
i am constantly going to sleep way past when i should, i just want someone to tell me that i sohuldnt be doing this instead of being told the same thing everyday when i tell monika im going to sleep. please add :(

**Comment by ThePotatoGuy** [comment]
She already does this, although that is changing because of #8179

**Comment by MLGHitsHeadshots** [comment]
yes but the thing is i have a regular sleep schedule so being up at 1 am is very bad for me

**Comment by ThePotatoGuy** [comment]
Like I said, she already does this, but its changing so she doesn't do that anymore. We'll likely do some schedule-based/reminder-based mechanics with time concern.
