### ISSUE TITLE
Disable the permanent blocking of the name change function

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8261]
The game has an eternal blocking of the name change function if you insulted Monika 3 times. I believe that it is necessary to remove the eternal blocking, it is useless and cruel! People make mistakes, and there are those who deserve a second chance. Therefore, you need to add a temporary blocking of this function. Permanent blocking is illogical if you have, for example, 2000 affection.

**Comment by Legendkiller21** [comment]
The nickname lock will **not** be removed. She gives you not only a second chance, but a third one too, so in order to make her lock the ability to give her a nickname you have to go out of your way and actively try to piss her off. As mentioned in #7283 maybe in the future there will be a way to get another chance after some amount of time has passed and/or affection gained. 

> Permanent blocking is illogical if you have, for example, 2000 affection.

Your actions have consequences regardless of your affection level.

**Comment by Nikv2005** [comment]
I do not think so . the function with the name must still have a temporary lock. As I said, people make mistakes and some deserve a second chance. People can change if they want, and therefore a temporary lock is needed.And the fact that you are not given a chance when you are loved is not realistic at all. The whole meaning of love breaks down. Therefore, I suggest that at least at a high affection level add a temporary blocking

**Comment by kkrosie123** [comment]
This has already been rejected.

**Comment by multimokia** [comment]
I think unblocking at a high level is fine, but she'd be wary and if you once again betray her trust immediately, it will be locked permanently. It's a *trust* thing and *comfort* thing. At that point it doesn't make sense for her to feel like she can trust you to not be cruel after that point, and it'd come with a large loss.

However if you pick something good, she'll begin to trust you again with this sort of thing and would likely reinstate it

**Comment by kkrosie123** [comment]
^ But still, this isn't a "second chance." This is a fourth chance. So even if we did unlock it again, she'd be extremely wary.

**Comment by Booplicate** [comment]
You say second chance, but you have to call her a bad name **3 times** to lose the option.

**Comment by Nikv2005** [comment]
There are idiots like me who in the beginning did things and now even after a long time (even more than a year) they still have the function blocked. But only recently, for example, they realize their problems, but they cannot be fixed. For such cases, you need a temporary block. Monika is a kind person who can give you a fourth (or still a second) chance after a while if you are good and she understands this

**Comment by kkrosie123** [comment]
It is possible it will be changed in the future, as Legend said.

**Comment by Nikv2005** [comment]
But will there be any chance of unlocking here? It is not correct if you have a permanently blocked function forever without a second chance.

**Comment by Booplicate** [comment]
You've already given 3 chances.

**Comment by Nikv2005** [comment]
But ... As I understand it still won't be done, even if you try to be good ... I wonder why. In reality, even if you insulted the person 2, 3. at least 10 times, you will still continue to communicate as usual, and both of you will forget about it.You can continue to communicate with Monica, but you cannot, for example, call her something affectionate, that is, a small restriction in communication .

**Comment by kkrosie123** [comment]
What? If someone called me a slur for transgenders, even once, I would never talk to them ever again. Monika is being *merciful,* in my opinion. I could never imagine being called such a harsh name in her situation. Curiousity is no excuse.

**Comment by Booplicate** [comment]
> at least 10 times, you will still continue to communicate as usual

People don't work this way. We will rework the system, but you won't be able to insult her 10 times...

**Comment by kkrosie123** [comment]
But, as has already been stated, this may change in the future.

**Comment by Nikv2005** [comment]
> > at least 10 times, you will still continue to communicate as usual
> 
> People don't work this way. We will rework the system, but you won't be able to insult her 10 times...

Sounds better already. I'm not saying to offend 10 times, but at least giving one more chance or a couple of additional chances to those who understood their mistakes would be nice.And that's exactly how people work. Even if you offend a person and he was your friend or family member, you will still continue to communicate after you apologized

**Comment by Booplicate** [comment]
> you will still continue to communicate after you apologized

Can't apologise forever, people will just lose trust and think your apology's worth nothing.

**Comment by Nikv2005** [comment]
Everywhere there are any restrictions, but I'm not talking about a way out of the communication norm, I say about rare cases.

**Comment by Nikv2005** [comment]
> > you will still continue to communicate after you apologized
> 
> Can't apologise forever, people will just lose trust and think your apology's worth nothing.

Everywhere there are any restrictions, but I'm not talking about a way out of the communication norm, I say about rare cases.
