### ISSUE TITLE
HELP: None of Orcaramelos gifts are recognized by Monika

### ISSUE THREAD

**Issue by JohnSmith2007** [Monika-After-Story/MonikaModDev#8265]
I made sure that it was the latest spritepack, i triple-checked to make sure that everything was copied to the correct folders, and IT STILL DOESN'T WORK!!! What the hell?!

**Comment by lunulae** [comment]
Have you restarted the game before trying to gift them?

**Comment by JohnSmith2007** [comment]
> Have you restarted the game before trying to gift them?

Yes. Several Times

**Comment by ThePotatoGuy** [comment]
check these steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
