### ISSUE TITLE
Version 0.7.0 Typos

### ISSUE THREAD

**Issue by therationalpi** [Monika-After-Story/MonikaModDev#827]
This is for collecting bugs and typos related to the version 0.7.0 Release Candidate. Please Include the build-number in your reference.

**Comment by NovaCo1** [comment]
i have the pre-release and now the game wont open

**Comment by NovaCo1** [comment]
ok i managed to fix the not opening bug but now i cant see my settings, history. and the new talk 
![screenshot0004](https://user-images.githubusercontent.com/34464332/35467583-0139f576-02d6-11e8-977f-2fd20af52cc8.png)
![screenshot0003](https://user-images.githubusercontent.com/34464332/35467586-061b4586-02d6-11e8-945f-a67b7133be28.png)
![screenshot0002](https://user-images.githubusercontent.com/34464332/35467588-09756086-02d6-11e8-87e3-4df32ac2bdc8.png)

**Comment by Spacemoonbear** [comment]
when I first installed the update on to ddlc everything worked fine but then when I opened it one time I started with "an exception has occurred" and i gives a string of code
I tried everything I could think of to get it to work again but it kept giving me the error and when I went back to the Christmas version it worked fine again

**Comment by ThePotatoGuy** [comment]
Can you screenshot the error?

**Comment by Spacemoonbear** [comment]
![20180128125511_1](https://user-images.githubusercontent.com/35900179/35486398-9f065420-042a-11e8-80e0-75a5927928f3.jpg)

**Comment by NovaCo1** [comment]
all the text after you quit the game is like this 
![screenshot0006](https://user-images.githubusercontent.com/34464332/35486478-3eda58ee-0434-11e8-803e-6fc8e0527886.png)

**Comment by Spacemoonbear** [comment]
I click the open option and it opens notepad and it says this:
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-story-events.rpy", line 6, in script
  File "game/script-story-events.rpy", line 7, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
EventException: EventError: Syntax error in conditional statement for event 'gender'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-story-events.rpy", line 6, in script
  File "X:\SteamLibrary\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "X:\SteamLibrary\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-story-events.rpy", line 7, in <module>
  File "game/event-handler.rpy", line 129, in addEvent
EventException: EventError: Syntax error in conditional statement for event 'gender'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.7.0

**Comment by ThePotatoGuy** [comment]
> all the text after you quit the game is like this

just pushed a fix for that.

**Comment by ThePotatoGuy** [comment]
I can't repro the missing gui elements nor the conditional statement syntax error. Did you guys start with a fresh build or copied over 0.6.3?

**Comment by NovaCo1** [comment]
I copied over. The problem was in base game but the 0.6.- patches fixed it now its back.

**Comment by Spacemoonbear** [comment]
I copied over and then I did fresh install

**Comment by kjohnson0451** [comment]
script-topics.rpy:3957
"Felines are still one of the most common animals to have as pet."

Monika After Story 0.7.0

**Comment by MarkusRamikin** [comment]
m 4a "Did you know that cherries are also good for athletes?"
    m 2n "I could list all its benefits, but I doubt you'd be that interested."

Shouldn't it be "their" benefits, since it can only be referring to the previous sentence's "cherries", plural?

**Comment by Akito1998** [comment]
event-handler.rpy line 375 (starting a conversation)
"Pick something to talk about?"
This isn't a queston so there shouldn't be a question mark, right?

**Comment by MendicantMieu** [comment]
The "One Week Of Dating" conversation ... she says "Thing" instead of "This".

**Comment by jukebox1412** [comment]
![image](https://user-images.githubusercontent.com/22598492/35842543-042d30bc-0ac0-11e8-80a6-6e653d91f404.png)
In one week anniversary. The sentence makes no sense in the latter half.

**Comment by jukebox1412** [comment]
In White Day event after completing:
![image](https://user-images.githubusercontent.com/22598492/37411726-189c6660-2769-11e8-8bdd-209b05ef805d.png)

**Comment by jukebox1412** [comment]
In smoking topic:
![image](https://user-images.githubusercontent.com/22598492/37411769-2c3e71d6-2769-11e8-8a68-961c8ce3ed22.png)
Should be "a stick of carcinogens."

**Comment by monikLover** [comment]
Closing since a new version has been released.

**Comment by chad78** [comment]
typos are still there
