### ISSUE TITLE
mas_log

### ISSUE THREAD

**Issue by HolyDevils** [Monika-After-Story/MonikaModDev#8280]
my mas_log.log is spamming "[Warning! ;_;]: 'store.wear_acs_pst' is deprecated. Use 'wear_acs_in' instead." every few seconds while I'm in game is it normal? It might have something to do with me gifting something going wrong.

**Comment by Booplicate** [comment]
You can ignore it.

We should remove all uses of the old functions.

**Comment by HolyDevils** [comment]
okay thanks
