### ISSUE TITLE
[Suggestion] Packages with food as gifts

### ISSUE THREAD

**Issue by cafuneandchill** [Monika-After-Story/MonikaModDev#8283]
## Introduction

As for now, we are able to give Monika coffee, hot chocolate and some other holiday-related foods via the gifting system. My proposal is the expansion of this system that would allow to gift any possible food type as a single universal food ration gift file.

## Basic idea

A food ration would be a gift file named, for example, `food.gift` or `ration.gift`. The difference from a normal gift file would be that this gift file would also contain the list of food items included in the ration. The list could be structured as CSV, or just as a "one item per line" list:

```txt
eggs
bread
tea
chocolate
bubble gum
```

## Possible pitfalls & solutions

- **Non-food items.** Given the wildcard nature of this system, it might be hard to write code for checking types of the items included in the gift file. A possible workaround is to compare the list items with some kind of online food database.
- **Monika's reactions.** Same there -- it would be difficult to write Monika's responses to each and every possible food type. Although there's probably no need to do that altogether -- she could just say something like:

  > Oh! `{food_item}`! I'll be sure to try that later!

  Or, if she has had that exact food before:
  
  > Oh! More `{food_item}`! Thank you!

- **In-game sprites:** Also same -- would be too much work to draw all the sprites for different types of food.

**Comment by Booplicate** [comment]
CSV is probably too advanced for most people, and we usually don't read content of gift files.

But maybe an archive like `package.zip` could work. We could read the files inside and instead of processing one by one, just resupply consumables with one reaction.

**Comment by cafuneandchill** [comment]
Yeah, that could be a viable alternative, too.

**Comment by ThePotatoGuy** [comment]
I agree that we should use a zip file over other methods.

[closing until we look into it]
