### ISSUE TITLE
[Bug] - (Fixed in fork!) .sh Linux script issues (get window handle)

### ISSUE THREAD

**Issue by coder-incognito** [Monika-After-Story/MonikaModDev#8287]
Traceback:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1502, in script call
  File "game/script-ch30.rpy", line 1677, in script
  File "game/script-ch30.rpy", line 1701, in <module>
  File "game/zz_windowutils.rpy", line 724, in mas_checkForWindowReacts
  File "game/zz_windowutils.rpy", line 619, in mas_getActiveWindowHandle
  File "game/zz_windowutils.rpy", line 302, in _getActiveWindowHandle_Linux
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

```

Would have tried to fix it myself but my experience with python is NULL.

Steps to reproduce:

Launch MAS with the script. Ensure window reacts and all alerts are on. This bug will appear. (Haven't tried with reacts and all disabled).

**Comment by coder-incognito** [comment]
Added this line, `, encoding = "utf-8"` to line 302, in the Unicode parenthesis, after the preexisting text there.
Seems like there is no exception now. But no reactions either.
I'm thinking it's because Qt5 by default shows application names next to their titles, so say, it would say something like YouTube — Google Chrome
Perhaps with escape codes, namely `"\b\0"`, you could replace the em dash with this code, so it cuts off at that point, leaving only "YouTube". I'm not sure how to implement that myself though.

**Comment by coder-incognito** [comment]
Alright! Figured something out!

```
if active_winname_prop is not None:
                active_winname = unicode(active_winname_prop.value, encoding = "utf-8")
                active_winname = active_winname.replace("—","\b\0")
                return active_winname.replace("\n", "")
```

Now, one question. The notifications seem slightly delayed? They only pop up when she sends a notification saying that she wants to talk about something. Is that intended? I don't really have a frame of reference to see if it's intended or not since I don't have a Windows machine on hand that I can test the window reacts feature with.

**Comment by coder-incognito** [comment]
Ah! So I placed the edited .rpyc in my main installation (I know that's very irresponsible but my persistent is backed up). And there doesn't seem to be a delay! It seems like it works on Linux as well! I edited my fork, and unless I'm mistaken, my fork is public.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
