### ISSUE TITLE
[Festive Suggestion] - Monika sings "I'll Be Home"

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#8289]
Just a little song suggestion for when good ol' D25 rolls around.

I'd figure that, unless the dev team plans to reuse the "All I want for Christmas is You" event, a fitting song for this year would be "I'll Be Home", by Meghan Trainor, especially given this year's been largely focusing on hyping up the holidays and having families and loved ones get together. What do you think?

(If this idea gets some traction, I'll see if I can try to whip up some dialouge code.)

**Comment by multimokia** [comment]
I'm a fan

**Comment by ThePotatoGuy** [comment]
assuming you will be working on it? Leaving open as in progress.

**Comment by Retrolovania** [comment]
I do plan to try to write the dialogue code, yes.
Haven't been able to yet due to managing the fall semester for school ending and a job recently, but I'll get on it as soon as possible.

**Comment by Retrolovania** [comment]
Here is what I currently have; consists of the first stanza and chorus movement.
I will be writing more of the song into dialogue; however, I need to know if this setup is appropriate for use before I continue so I can iron out any issues with the formatting or anything else.
[Moni-D25-Alpha.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7653290/Moni-D25-Alpha.txt)

**Comment by Retrolovania** [comment]
Given the current date and how close D25 is, I think I may just write the song to use the traditional "long" song format.
Not sure if there's a way to specify for it to only be available on the actual day, though...

**Comment by Retrolovania** [comment]
Given how close D25 is now and the fact that I'm currently working on another DDLC mod to release on that day, I no longer really have time to work on this any further, so I'll have to close this.

Maybe next year...
