### ISSUE TITLE
[Suggestion] - Window React Suggestion (looking for feedback) 

### ISSUE THREAD

**Issue by AutumnLeaves991** [Monika-After-Story/MonikaModDev#8291]
So, after you ask Monika if she reads manga the following dialogue sequence occurs:

_"Yeah, I had a feeling you were going to ask me about this.
Natsuki would be the expert here, I guess.
I usually prefer reading to watching anime, but I'd be fine with anything if it's with you.
I don't judge other people for their hobbies. So if you want to load up some anime, go ahead!
I'll watch through your computer screen. Make sure it's something I'll like!"_

Those last two lines got me thinking it'd be nice for Monika to have a window reaction for CrunchyRoll or some other anime streaming sites. You could probably get away with re-using the dialogue she already uses for youtube, but I wouldn't mind trying my hand at coming up with some lines in her voice for it if people like the idea.

Figured it'd be worth seeing what other people thought before I waste anyone's time with a pull request lol

**Comment by NonyaGG** [comment]
Sounds good enough, go ahead

**Comment by lunulae** [comment]
I think it'd be a good idea. CrunchyRoll is the only (official) streaming site I'm aware of but if you know multiple ones we could use them as well.

**Comment by AutumnLeaves991** [comment]
> I think it'd be a good idea. CrunchyRoll is the only (official) streaming site I'm aware of but if you know multiple ones we could use them as well.

Pull request submitted ^^, lmk what you think of the dialogue I used.  Hopefully it sounds monika-esque

**Comment by Kzitold** [comment]
Manga is literature, so how about a reaction to MangaDex, MangaPark, etc...

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
