### ISSUE TITLE
[Suggestion] An option to add to the "I feel..." part

### ISSUE THREAD

**Issue by Draganso** [Monika-After-Story/MonikaModDev#8297]
I would like an option that would be "I feel depressed" something even worse than the "I feel sad"  maybe with monika crying of sadness, other intresting option would be to say that the "player" is dying and won't be alble to come back ever again, this one could be in the "goodbye" part maybe.
It's just a suggestion, if you don't like just say it, I will understand.

**Comment by dreamscached** [comment]
I'm pretty sure things like 'I'm dying' have been discussed before, but alas I believe they were rejected for some reason.

**Comment by ThePotatoGuy** [comment]
As mentioned, this has been discussed before and we will not be adding anything like this. see #6796, #3824, somewhat #7858. 

depression is a difficult topic to discuss and generalizing dialogue to cover everyone in these cases is absurd.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
