### ISSUE TITLE
i took monika out of the usb pasted her back into characters and shes gone well I found a reddit page that led me to here

### ISSUE THREAD

**Issue by AchillesArrow** [Monika-After-Story/MonikaModDev#8301]
[mas_log.log.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7607280/mas_log.log.zip)
[monika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7607
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7607295/persistent.zip)
283/monika.zip)

**Comment by Arodi-Pie** [comment]
Do you fix it?

**Comment by ThePotatoGuy** [comment]
see #2624 if you just want the fix

[closing this in favor of linked issue]
