### ISSUE TITLE
Expression Viewer error

### ISSUE THREAD

**Issue by SteveeWasTaken** [Monika-After-Story/MonikaModDev#8302]
So I was taking a look around the expression viewer, and I got an error out of nowhere. I tried to paste the expression code "1hktub", and the game crashed. I attached the traceback.txt file, in case it's useful. 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7610003/traceback.txt)

**Comment by ThePotatoGuy** [comment]
seems we missed something with the tear handling. @Booplicate if you want to take a look, otherwise I'll check it within the month.

**Comment by Booplicate** [comment]
I see the issue, I think we should convert back into tears code using the mod map.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
