### ISSUE TITLE
Feature suggestion: Thanking Monika for no reason.

### ISSUE THREAD

**Issue by The-Critika** [Monika-After-Story/MonikaModDev#8304]
It would be nice to be able to thank Monika for the reply to her say, book suggestions, writing and coding tips or when she mentions her efforts to get her player's attention in DDLC.

**Comment by dreamscached** [comment]
There is a topic called 'thanks for being there for me!' under 'I feel...' section. Pretty much what's being suggested here...

**Comment by AsuraShun** [comment]
> There is a topic called 'thanks for being there for me!' under 'I feel...' section. Pretty much what's being suggested here...

That's 1 reason, there's a lot of things that we wish we could thank her for besides that

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
