### ISSUE TITLE
Gifts not working

### ISSUE THREAD

**Issue by ElgerElg** [Monika-After-Story/MonikaModDev#8307]
I put a gift with the .gift extension in characters folder but after a few seconds the file just disappears and nothing happens.

**Comment by dreamscached** [comment]
Do you use a translated version by any chance?

**Comment by ElgerElg** [comment]
Yes, i use a russian version but i make .gift with russian name, for example кофе.gift and get error which I described above

**Comment by dreamscached** [comment]
Translated versions may have this mechanism modified, so I'd ask a translation developer about it. But I'd try using usual gift names such as `coffee.gift`.

**Comment by ElgerElg** [comment]
> Translated versions may have this mechanism modified, so I'd ask a translation developer about it. But I'd try using usual gift names such as `coffee.gift`.

Also doesn't work. But the English file with .gift does not disappear at all and the game does not react. So I entered it correctly in Russian, but why does it disappear and the gift is not given? Maybe need a certain number of Affection points?

**Comment by ThePotatoGuy** [comment]
you should ask the devs of the translation. they clearly made changes to the reaction mechanism.

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
