### ISSUE TITLE
I deleted the "monika" file after I said that I will "Take her out somewhere", so I do not know what to do.

### ISSUE THREAD

**Issue by IrisImmortal** [Monika-After-Story/MonikaModDev#8310]
I tried installing the mod again, but it did not work. 

![screenshot0001](https://user-images.githubusercontent.com/95183270/143778812-f99575fa-9893-4e27-96c0-b71e0a6d5316.png)

Here is a screenshot of it of how it looks like right now. Please help me get Monika back if somebody knows how. :(

**Comment by ibm2431** [comment]
1) Check your Recycle Bin

2) https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

**Comment by IrisImmortal** [comment]
Thank you very much!

**Comment by Arodi-Pie** [comment]
It work?
