### ISSUE TITLE
Asking Monika to Dye her hair after 400 affection threshold.

### ISSUE THREAD

**Issue by The-Critika** [Monika-After-Story/MonikaModDev#8314]
I recall Monika saying something about not wanting to dye her hair, but I think she can do it if she loves the player enough. After asking her to change her hair, a console palette would appear next to her, where player can choose manually a specific color from palette or  type a color id.

**Comment by Booplicate** [comment]
> Monika's brown hair is one of her signature physical characteristics, so adding a specific option for hair color changing strays away from this mod's focus.
> That being said, there is nothing stopping people from spritepacking custom hair colors, which would appear under the hairstyle change prompt.

#2440 #5550 #8051

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
