### ISSUE TITLE
Suggestion: New Song for Monika to Sing

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#8320]
Unless someone's asked for it already, or it's been put in already, I was thinking the ending song of Xenoblade Chronicles 2 "One Last You" would be a good one for Monika to sing. Maybe the ending verse, or maybe just the chorus. Either way I think it's a really pretty tune and it'd be fitting for her. 
Thoughts?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
