### ISSUE TITLE
Can't update submod

### ISSUE THREAD

**Issue by Lu1508** [Monika-After-Story/MonikaModDev#8335]
Hi!

I'm having this problem that every time I want to update the Spacerooms, it send me this

-----------------
[SUBMOD UPDATER PLUGIN ERROR]: Failed to extract update. Submod: 'Custom Room Furnished Spaceroom V2'. Exception: [Errno 2] No such file or directory: u'C:\\Users\\oxflo\\Pictures\\Monika.chr\\conf\\together\\Doki Doki Literature Club\\game\\Submods\\location_selector\\Locatons\\temp_1638476427\\tw4449-s-MAS-Submods-Custom-Room-Furnished-Spaceroom-V2-6f3cea7\\game\\Submods\\Submod Updater Plugin\\indicator_update_available.png'.
-----------------

What I have to do?

**Comment by ThePotatoGuy** [comment]
since this is an issue with the submod, you should contact the submod creator.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
