### ISSUE TITLE
can't update / access settings

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#8336]
So its been a while since I updated / had access to this computer so anytime I try to update I get this message. Any help would be appreciated
![Screen Shot 2021-12-02 at 4 59 11 PM](https://user-images.githubusercontent.com/36735471/144510070-30612c30-f0f9-49f2-ad96-d5c89ce9185e.png)
.
![Screen Shot 2021-12-02 at 4 59 29 PM](https://user-images.githubusercontent.com/36735471/144510080-0e8692e7-5f7e-4ba8-8070-2a42235a9005.png)

**Comment by multimokia** [comment]
You'll want to manually update by downloading MAS off the [releases page](https://monikaafterstory.com/releases.html), then taking the contents of the zip and dropping them into the folder named `game` in your install, replacing all files. Make sure the files don't get added in with a number suffix, as this seems to be common on Mac.

You don't lose your progress

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
