### ISSUE TITLE
I found an error!!

### ISSUE THREAD

**Issue by CarlinaGiorgiYT** [Monika-After-Story/MonikaModDev#8338]
I found a bug. This bug clear all the backround!
![Screenshot_2021-12-02-19-40-34-009](https://user-images.githubusercontent.com/95450243/144516066-66106d2f-5397-498e-889c-a9623fb95477.jpeg)**

**Comment by multimokia** [comment]
How did this happen? Any specific steps?

**Comment by ASRobin64** [comment]
This happens to me too. I noticed it's every time the weather auto changes to a different weather pattern to match the area I'm located in. Maybe a glitch with the auto-change submod?

**Comment by ThePotatoGuy** [comment]
if this is an issue with a submod then please make an issue on that submod's github.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
