### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#8339]
So I've been seeing people have Monika with different dresses or hairstyles or giving her different things like coffee. I haven't used this in a while so is there different thing I have to do? do I import them or are they affected by this new affection rating I've heard about?

**Comment by elite198** [comment]
You can add most of the clothes with sprite packs that are usually on reddit

**Comment by Wingdinggaster656** [comment]
Some of them are already in the game, you don't need to download any extension content.

You can gift Monika coffee. And for hairstyles, hairstyle down hair is unlocked gradually. For clothes, they are basically unlocked by special days like Santa Costume.

There are some things that do require additional installation. Take the contents of Spritepack.

**Comment by Pbm13** [comment]
where do I find sprite pack? I can't find it

**Comment by dreamscached** [comment]
> where do I find sprite pack? I can't find it

https://github.com/monika-after-story/monikamoddev/releases/latest, scroll down and you'll see `spritepacks.zip` file under *Assets* section. However, this pack has just official spritepacks, for user content you may want to browse Reddit or related sites.
