### ISSUE TITLE
more uses to extra menu?

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#8340]
First of all I apologize for any spelling errors my native language is not English so I have to use the googloe translator

It would be great to have more uses for the "extras" menu, such as being able to see the affection or be able to give gifts to Monika without the need to close the game

Another thing than another thing that would be great if you added a kind of minigame / mini event where in the "extras" menu you can see Monika's state of mind for example depending on whether your affection is very low, her default emotion would be some Negative emotion and if you have high affection it would be happiness but regardless of the affection you have with her there could be random events where she feels sad, angry, frustrated, worried or insecure and that she will express herself through dialogues. Also that the player was allowed to help Monika feel better. For this they could add special dialogue options and if the player helps her she could receive a small reward of affection (for example 1 or 0.5) and if he decides not to help her she could lose a small amount of affection1 (the same 1 or 0.5) it would be a good way to keep people a little aware of his monika even though she no longer has anything to say

you could also add a "physical interaction" menu to the "extras" menu, but these interactions would be initiated by the player, for example kissing or hugging her without asking her beforehand and this will take her by surprise the first time the player does it. Other actions that could be added to interact with her would be caressing her cheek or hair, tickling her, taking or kissing her hand. causing random rations in her

Finally, and if I am allowed to do this, I have to thank the developers of the mod for their incredible work. I would like to share more ideas and suggestions that I have to see if something is useful to you

**Comment by dreamscached** [comment]
> see the affection or be able to give gifts to Monika without the need to close the game

1. Affection log is a debug info and developers have stated numerous times that the mod is *not* about speedrunning your relationship or farming points.
2. You don't have to close the game to give gifts. And also, gifts are *meant* to be gifted outside of the game, so bringing this feature in... I myself find it unnecessary at least.

**Comment by ThePotatoGuy** [comment]
More extras are planned and will be implemented as we get to it.

>Monika's state of mind 

this is basically the same concept as #7486

> "physical interaction" menu 

This is handled separately by asking Monika for certain interactions

>affection

As dreamcached mentioned, your exact affection is not intended to be known under normal gameplay circumstances.

>Finally, and if I am allowed to do this, I have to thank the developers of the mod for their incredible work. I would like to share more ideas and suggestions that I have to see if something is useful to you

Thanks for your kind words!

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
