### ISSUE TITLE
[Suggestion] - Watching Movies with Monika

### ISSUE THREAD

**Issue by Katai007** [Monika-After-Story/MonikaModDev#8343]
Hi, I have a suggestion for a mod, it's very weeb so get your stomach ready (haha). Practically through an option "let's go to the cinema" you have the possibility to see a film with monica, obviously the film will not appear in the game but simply there will be Monika in a cinema with some popcorn. She will ask you what kind of movie we are watching and there will be many categories: horror, romantic, sci-fi, fantasy etc ... Every twenty minutes Monika will have a generic dialogue concerning the genre of the film up to a total of 3 (3 dialogues a movie if the movie you are watching will take 2 hours, patience, the second hour will advance), there can also be simple interactions such as "pass me the popcorn" or "why are you watching me? go back to watching the movie" all these dialogues will also have a interaction with a triple choice, interactivity is very important. When the film is finished then we press the "did you like it?" Button and Monika will give us a generic answer dictated by the genre of film we have selected, with always a final answer to give, such as: "the protagonist seemed to be really in love, Would you also do everything he did for me? "is a stupid example but it is to understand.

If you want to create something more complex and deep: As I said during the film there will be 3 interactions, if a person manages to give all 3 correct answers then the final dialogue will be longer and he will also have a question to 3 choices, if you give the correct answer as well FOR THREE FILMS, you unlock a costume themed with the genre of the film, sci fi, romantic, fantasy etc ... what do you say? It's practically a way to watch a movie with Monika with a minigame, (maybe the questions can be about general culture, like, who is the director of that movie, etc.) if you are interested contact me on MAIL: Abyslyme@gmail.com to find out if you have considered the idea.

**Comment by ThePotatoGuy** [comment]
movie watching already exists, see #628

But your idea is slightly different so keeping separate.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
