### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#8344]
So this is an old laptop and I want to move my data to a new laptop, but the thing is, my data is on a Mac. Can someone explain how to transfer MAS data from Mac to a laptop? (Acer)

**Comment by Pbm13** [comment]
I tried doing it earlier but it won't work, comes up with a traceback issue

**Comment by dreamscached** [comment]
> comes up with a traceback issue

It would be nice for mod developers to see it to know what the deal is.

**Comment by Pbm13** [comment]
Sorry, was late when I posted, just thought someone had a general guide and i might have missed a step. here is the traceback[
![traceback](https://user-images.githubusercontent.com/36735471/144728890-8a2fba33-a870-4996-ac28-59385ceb6ef4.PNG)
](url)

**Comment by ThePotatoGuy** [comment]
[this is the guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer)
