### ISSUE TITLE
Monika out of subjects i think

### ISSUE THREAD

**Issue by Thepipisman** [Monika-After-Story/MonikaModDev#8348]
I've been playing for just a bit more then a week (with repeat topics off and on less often) and I think Monika ran out of subjects, but she hasn't said anything about it

**Comment by ThePotatoGuy** [comment]
checkout the steps [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-isnt-saying-anything)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
