### ISSUE TITLE
Own Spritepack dont work

### ISSUE THREAD

**Issue by McJustina** [Monika-After-Story/MonikaModDev#8349]
Hey ho. I maked an own and first Spritepack, because i was bored and everythink works fine but if i go on choker and select my necklace ive done, you cant see it... Thats the problem and i have no idea why, so can please someone help me...

Folder A: 
![acs-mcjustins_emerald_necklace-0-0](https://user-images.githubusercontent.com/95578620/144751968-619b278d-518e-4d6e-b9bf-47b31bac4be5.png)
![acs-mcjustins_emerald_necklace-5-0](https://user-images.githubusercontent.com/95578620/144751971-00129fde-7bf8-4fab-8b00-4d614b9a36cf.png)

Screenshot from folder J:
![Bild_2021-12-05_163158](https://user-images.githubusercontent.com/95578620/144753001-f5f10511-207a-4020-b019-3c1daefa57ec.png)

And screenshot where i select it:
![Bild_2021-12-05_163636](https://user-images.githubusercontent.com/95578620/144753177-b24608b5-d2d5-4db0-844f-a6cea89fd409.png)

(Sorry for my bad english. Im learning it lol)

**Comment by ThePotatoGuy** [comment]
Can you upload the `log/spj.log` file here?

**Comment by McJustina** [comment]
Here is it @ThePotatoGuy 
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7659887/spj.log)

**Comment by ThePotatoGuy** [comment]
spj looks fine so the issue might be that the images are not in the right place. Verify that you have the sprites named correctly and in the `mod_assets/monika/a/` folder.

**Comment by McJustina** [comment]
I get it now. It was the sice of the image lmao but still thanks for helping <3

**Comment by fwqsai** [comment]
> Hey ho. I maked an own and first Spritepack, because i was bored and everythink works fine but if i go on choker and select my necklace ive done, you cant see it... Thats the problem and i have no idea why, so can please someone help me...
> 
> Folder A: ![acs-mcjustins_emerald_necklace-0-0](https://user-images.githubusercontent.com/95578620/144751968-619b278d-518e-4d6e-b9bf-47b31bac4be5.png) ![acs-mcjustins_emerald_necklace-5-0](https://user-images.githubusercontent.com/95578620/144751971-00129fde-7bf8-4fab-8b00-4d614b9a36cf.png)
> 
> Screenshot from folder J: ![Bild_2021-12-05_163158](https://user-images.githubusercontent.com/95578620/144753001-f5f10511-207a-4020-b019-3c1daefa57ec.png)
> 
> And screenshot where i select it: ![Bild_2021-12-05_163636](https://user-images.githubusercontent.com/95578620/144753177-b24608b5-d2d5-4db0-844f-a6cea89fd409.png)
> 
> (Sorry for my bad english. Im learning it lol)

where did u learn how to code? i want to create my hown spritepacks but idk how to code the folder j / hola, donde aprendiste a crear esos codigos? quiero crear mi propio spritepack para monika pero ni idea de como hacer el documento para el fichero j...

**Comment by fwqsai** [comment]
where did u learn how to code? i want to create my hown spritepacks but idk how to code the folder j / hola, donde aprendiste a crear esos codigos? quiero crear mi propio spritepack para monika pero ni idea de como hacer el documento para el fichero j...

**Comment by dreamscached** [comment]
Please don't necropost, @fwqsai. Here's the tutorial &mdash; https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects

**Comment by fwqsai** [comment]
oh thanks
