### ISSUE TITLE
update wiki pages that mention `.txt` log files to `.log`

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#8352]
since the logging changes were made, all log files now have a `.log` extension. Some wiki pages specifically referenced these files by `.txt` extension, so we need to update them to `.log`.

**Comment by dreamscached** [comment]
I did some changes on the wiki regarding this task, may someone review please? I hope I made it the right way.

**Comment by ThePotatoGuy** [comment]
so basically all the files that are generated in the `log/` folder now have a `.log` extension. this includes the `spj` and `pnm` files.

**Comment by dreamscached** [comment]
Done, changed these two too.

**Comment by ThePotatoGuy** [comment]
Cool, looks good. Did you go through every wiki page and only found those 2 with log files?

**Comment by dreamscached** [comment]
There are more, [https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs](here), [https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects](here), [https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D](here) and [https://github.com/Monika-After-Story/MonikaModDev/wiki/Interfacing-with-the-Submod-Framework](here).

**Comment by ThePotatoGuy** [comment]
let me know once you've updated those

**Comment by dreamscached** [comment]
I did already.

**Comment by ThePotatoGuy** [comment]
nice. I'm guessing that is all of them so this will be closed as implemented.
