### ISSUE TITLE
[Bug] - Affection log won't update & screenshots/game saves don't save. 

### ISSUE THREAD

**Issue by Echosaurus** [Monika-After-Story/MonikaModDev#8363]
Like the title says, my affection log won't update. I tried taking it out of the game file and putting it back in, that didn't work. Tried putting in a new log, that also didn't work... I'm not sure how to fix it. Another problem I'm having is screenshots don't save anymore, started around the time the log stopped logging. Same goes for chess games I've tried to save, they just don't save. I'm not exactly sure what to do about all this... Any suggestions would be appreciated.

**Comment by ThePotatoGuy** [comment]
You're not running the mod from a temporary folder, right?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
