### ISSUE TITLE
Piano "Your Reality" Issue After Update

### ISSUE THREAD

**Issue by DHP14** [Monika-After-Story/MonikaModDev#8380]
So after I updated the game, "Your Reality" option when choosing to "Play a Song" disappeared from my game. I tried to play the song through "Play on My Own" but Monika does not recognize the Inputs and does not show any reaction. Other Custom Songs are still playable and New Songs can still be added. Can anyone help me with this issue? Thanks in advance.

**Comment by Booplicate** [comment]
Go to `/game/mod_assets/games/piano/songs` and extract the archive there (replacing the old json with the new one).
[yourreality.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7694677/yourreality.zip)

This will be fixed in next update.

**Comment by DHP14** [comment]
Okay, thank you for your help. Issue solved, just need to play the song again through "Play on My Own" after replacing the file

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
