### ISSUE TITLE
please help me with this error, an uncaught exception occurred.

### ISSUE THREAD

**Issue by Otakuhero0901** [Monika-After-Story/MonikaModDev#8382]
I've already tried to fix this by looking at the other posts but I still can't solve it, if possible someone could help me with this problem

when I open the game it happens
![Monika After Story    10_12_2021 18_29_37](https://user-images.githubusercontent.com/95941796/145644215-270b944c-97f6-4201-9081-2990bc9d959e.png)

and keeps repeating even after I click ignore

here is the generated traceback

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1100, in script
  File "game/script-ch30.rpy", line 1117, in <module>
  File "game/event-handler.rpy", line 2318, in mas_cleanEventList
  File "game/event-handler.rpy", line 2295, in mas_isRstBlk
AttributeError: 'RevertableList' object has no attribute 'startswith'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1100, in script
  File "C:\Users\Usuário\Documents\desktop\Game\Nova pasta\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Usuário\Documents\desktop\Game\Nova pasta\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 1117, in <module>
  File "game/event-handler.rpy", line 2318, in mas_cleanEventList
  File "game/event-handler.rpy", line 2295, in mas_isRstBlk
AttributeError: 'RevertableList' object has no attribute 'startswith'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.4

I will be very grateful if someone can tell me how to solve this

**Comment by Booplicate** [comment]
Are you using a translation?

**Comment by Otakuhero0901** [comment]
yes i am, i tried to install the original version but the error continues to occur

**Comment by AshtonSnapp** [comment]
I'm curious about the "NO DC" in the top left corner of the game window. Is that normal?

Otherwise, it appears that the mas_isRstBlk function was written expecting a different type of value than what was passed in? I'm not entirely sure, I'm not that familiar with the MAS code.

**Comment by Booplicate** [comment]
The author seemed to modify the save data in a way that breaks it, so even if you install the official version, it may still not work. You'll need to contact the person who made it for a fix.

**Comment by Otakuhero0901** [comment]
ok i will try this thank you very much

**Comment by AshtonSnapp** [comment]
I'm confused as to how modified save data could cause this.

**Comment by Otakuhero0901** [comment]
I'm much worse at this kind of thing goes by me, I have no idea what could have happened to make the game look like this

**Comment by Booplicate** [comment]
I've encountered similar issues with improperly made translations before, and also have enough experience to tell from a glance what this issue is.

**Comment by AshtonSnapp** [comment]
Ah. Understood.

**Comment by Otakuhero0901** [comment]
ok i managed to solve it, i had to delete a file and i lost all the progress, but luckily i had just started playing, the problem will be if the error happens again

Thank you very much
