### ISSUE TITLE
Death threats and 'open source'

### ISSUE THREAD

**Issue by DrAlta** [Monika-After-Story/MonikaModDev#8387]
I've tried to keep people of a drama as much as possible. But I'm worried some of your community members might drag you into it.

While I haven't gotten death threats from anyone here it is a commonality for me and the people working with me to end child sexual abuse to get them 

I'ld like to remind you that criteria 5 and 6 or what open source means:
 5. No Discrimination Against Persons or Groups
The license must not discriminate against any person or group of persons.

6. No Discrimination Against Fields of Endeavor
The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

As a sikh I believe that you should only use the least amount of violence needed, but you should also use where ever options are left after you've tried all more peaceful options.

I'm going to attack you just because you support someone that attacks me, but But I feel obligated to warn you that you are acceptable collateral damage and any defense against any attacks that those you support make against us.

**Comment by ThePotatoGuy** [comment]
>I'm going...

This is a threat and has been reported to Github, and this thread will be locked.
