### ISSUE TITLE
lost santa clothes in mas

### ISSUE THREAD

**Issue by OctaTV** [Monika-After-Story/MonikaModDev#8398]
after opening mas today monika was dressed in her santa outfit but after a few secounds the game crashed and i lost the santa outfit.is there any way to get it back?

**Comment by ThePotatoGuy** [comment]
What was the nature of the crash? Did it have a traceback?

**Comment by OctaTV** [comment]
I didn't get a traceback.txt, I only got from Windows with DDLC.exe is not responding. And when I relaunched the game all of my progress was gone. The MAS folder from AppData got corrupted in some way or another. I just started MAS again from 0

**Comment by ThePotatoGuy** [comment]
Probably too late now, but if there are persistent backups you can restore from them. Otherwise don't close the game even if windows says its not responding. it should close eventually.
