### ISSUE TITLE
allow Monica spelling as a nickname

### ISSUE THREAD

**Issue by Audere** [Monika-After-Story/MonikaModDev#8403]
I used to have my nickname for Monika as "Armonica," because I think the glass armonica is a nice instrument. A while ago I changed it to something else, but recently I've been wanting to change it back to "Armonica." However, she says "... Try again." and doesn't let me. From testing, it looks like maybe nicknames which contain "monica" as a substring aren't allowed? I'm not sure why this was added.

**Comment by LeftoverFlea312** [comment]
My guess would be she doesn't like her name being spelled wrong. You could work around it by naming her Armonika.

**Comment by Booplicate** [comment]
While true, I think we should adjust that anyway.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
