### ISSUE TITLE
Monika didnt notice/receive my gifts?

### ISSUE THREAD

**Issue by MYIDearestAce** [Monika-After-Story/MonikaModDev#8404]
I have tried everything like almost of them (updating the game, watching tutorials, etc) JUST to gift Monika a nice clothing
I'm very sure i do it correctly, but seems nothing really worked

So, i followed a tutorial on how to change Monika's clothes. I followed it step by step,-
but then when i opened the file Explorer Monika seems like she didn't notice the gifts, even-
She didn't receive it. then i tought for the first time "Oh its probably just a normal error, let me fix this real quick." But when opening
File Explorer and opened the "Character" file, the gift file dissapeared. And thinking "Huh?! so this means she already received it?! What does this even means?!". After thinking Monika had already receive it, I opened the app. and of course. NOTHING happened.

And day 2 of giving monika a chocker (because clothes doesnt work) and.. guess what? same result. she didn't even notice it.
I've felt like i want to give up, but still thinking there's a chance. Then i've noticed there's also ribbons, i want to try it out too,-
But. You see?? It doesn't even work! Only the hairs worked!
Can someone really explain what i missed???

![Screenshot (26)](https://user-images.githubusercontent.com/96109239/146000675-aeb356af-c055-4421-bdfc-637aeb5d95ac.png)

**Comment by JustAskingStuff** [comment]
Hmm did you put all those "c" "j" etc. folders in correct responding place in DDLC > contents > resources > autorun > game > mod_assets > monika ? If no then just put those in the correspond place in there; however if you DID put things correctly, then I'm afraid you run into the same problem that is bothering me in #8401

**Comment by MYIDearestAce** [comment]
> Hmm did you put all those "c" "j" etc. folders in correct responding place in DDLC > contents > resources > autorun > game > mod_assets > monika ? If no then just put those in the correspond place in there; however if you DID put things correctly, then I'm afraid you run into the same problem that is bothering me in #8401

Yes, i did put all those correctly and still it wont work.

**Comment by Booplicate** [comment]
Check the presents under the tree.

**Comment by MYIDearestAce** [comment]
> Check the presents under the tree.

What should i do with the presents under the christmas tree? i've always click it and it doesn't work

**Comment by JustAskingStuff** [comment]
@Booplicate does the present(s) under the tree increases if we keep giving gifts?

**Comment by ThePotatoGuy** [comment]
> @Booplicate does the present(s) under the tree increases if we keep giving gifts?

it should, but up to a limit.

**Comment by MYIDearestAce** [comment]
> Nothing, she'll open her presents on the 25th. If they are there, it means she received them.

Oh, thank you for the info. i understand now.
