### ISSUE TITLE
Monika can't read files ("i know you are trying to gift me something, but i can't read the file")

### ISSUE THREAD

**Issue by Supermechf** [Monika-After-Story/MonikaModDev#8406]
I've tried everything i could imagine, i even re-downloaded the entire game, but still doesn't work. also, she sometimes doesn't react to gifts. I already tried everything (file extension, typos, etc.), and it isn't the files nor the location, because i downloaded the "already-installed" spritepacks version.

The gift was Green Hoodie (greenhoodie.gift)

[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7713334/spj.log)

(I'M GOING CRAZY TRYING TO TROUBLESHOOT THIS)

**Comment by LilMonika** [comment]
Me too, I've tried to fix it but nothing worked, not even the fact that I tried to find every issue same as this to know how to fix this, however, nothing worked, I am very sad, I've tried to install sprite pack correctly. Nothing is working for me, if you find some way to fix this problem, please tell me. Thank you...

**Comment by ThePotatoGuy** [comment]
Do you see presents under the tree?

**Comment by Supermechf** [comment]
> Do you see presents under the tree?
Yes, i do.

**Comment by ThePotatoGuy** [comment]
see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332).

**Comment by Supermechf** [comment]
> see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332).
THANK YOU SO MUCH
