### ISSUE TITLE
Monika Can't Read My gift files.

### ISSUE THREAD

**Issue by LilMonika** [Monika-After-Story/MonikaModDev#8408]
I've tried to fix it but nothing worked, not even the fact that I tried to find every issue the same as this to know how to fix this, however, nothing worked, I am very sad, I've tried to install sprite pack correctly. Nothing is working for me, I can't do anything. I installed the sprite pack correctly, I gave her gifts correctly, but she always has the same answer as before, I'm starting to get a little angry. If you found a way to fix this, please tell me. Thank you...

**Comment by ThePotatoGuy** [comment]
Do you see presents under the tree?

**Comment by LilMonika** [comment]
> Do you see presents under the tree?

Yes I do but I'm talking about the ones she opens once you open the game, I gave her clothes and a ribbon, and she says sorry because she can't read the file

**Comment by ThePotatoGuy** [comment]
>Yes I do but I'm talking about the ones she opens once you open the game

There are no gifts that **only** get opened when the game is launched. The system is agnostic to when the gifts are placed in the characters folder. Since it's currently christmas season, all gifts are put under the tree and will be opened/reacted to on christmas. #6783 will add some sort of feedback so its clear that this happens. 

A confirmation that the spritepacks were loaded correctly is to check steps 2 and 3 on [this page](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation).

**Comment by LilMonika** [comment]
I am not lying, she checked it once I entered and she says: "I'm sorry Senpai, I know you are trying to give me something but I can't read the file.''

**Comment by multimokia** [comment]
If she says that, your spritepacks aren't installed correctly.

**Comment by ThePotatoGuy** [comment]
>I am not lying, she checked it once I entered and she says:

I'm not saying you're lying, I'm saying that you could drop gifts while the game is running and they will be detected, too. This is just how the system works, there are no gifts that "only get opened when the game is launched".

Verify steps 2 and 3 on [this page](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation) so we can see if the spritepacks were loaded correctly.

**Comment by LilMonika** [comment]
> If she says that, your spritepacks aren't installed correctly.
Really? Could you help me fix the problem?? Or perhaps tell me how to install it correctly? I am very very desperate

**Comment by multimokia** [comment]
Firstly, what are you trying to gift?

Also can you say goodbye to Monika and send your spj.log here? (Just drag and drop it into the textbox, and wait for it to finish uploading, the filename has `uploading` in it while it's still uploading)

The `spj.log` file is in the `log` folder.

**Comment by LilMonika** [comment]
The transexualpride ribbon
She was able to get it but just was not able to read it.

**Comment by LilMonika** [comment]
And also, I used a tutorial, and it worked for them, but not for me.

**Comment by multimokia** [comment]
Please send the spj.log

**Comment by LilMonika** [comment]
I do not know how to do that so...

**Comment by LilMonika** [comment]
I don't actually know where that is too.

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/146134290-ace4c742-f163-40bd-b461-6992db00caa2.png)

**Comment by LilMonika** [comment]
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7716907/spj.log)

**Comment by multimokia** [comment]
```log
[info]:  reading JSON at 'c:\users\merlita\downloads\ddlc-win\ddlc-1.1.1-pc\game\mod_assets\monika\j\anonymioo_acs_ribbon_bisexualpride.json'...
[info]:  loading ACS sprite object 'anonymioo_ribbon_bisexualpride'...
[info]:    loading Pose Map in 'pose_map'...
[info]:    Pose Map 'pose_map' loaded successfully!
[info]:    loading ex_props...
[info]:    ex_props loaded successfully!
[info]:    loading select_info...
[info]:    sel_info loaded successfully!
[info]:    'entry' progpoint not found
[info]:    'exit' progpoint not found
[!ERROR! T_T]:  image at 'mod_assets/monika/a/acs-anonymioo_ribbon_bisexualpride-0.png' is not loadable
[!ERROR! T_T]:  image at 'mod_assets/monika/a/acs-anonymioo_ribbon_bisexualpride-5.png' is not loadable
```

Looks like you didn't install it correctly. Which tutorial did you use?

**Comment by LilMonika** [comment]
I meant bisexual-

**Comment by LilMonika** [comment]
But i also gave her the transexual, still did not work.

**Comment by LilMonika** [comment]
> ```
> [info]:  reading JSON at 'c:\users\merlita\downloads\ddlc-win\ddlc-1.1.1-pc\game\mod_assets\monika\j\anonymioo_acs_ribbon_bisexualpride.json'...
> [info]:  loading ACS sprite object 'anonymioo_ribbon_bisexualpride'...
> [info]:    loading Pose Map in 'pose_map'...
> [info]:    Pose Map 'pose_map' loaded successfully!
> [info]:    loading ex_props...
> [info]:    ex_props loaded successfully!
> [info]:    loading select_info...
> [info]:    sel_info loaded successfully!
> [info]:    'entry' progpoint not found
> [info]:    'exit' progpoint not found
> [!ERROR! T_T]:  image at 'mod_assets/monika/a/acs-anonymioo_ribbon_bisexualpride-0.png' is not loadable
> [!ERROR! T_T]:  image at 'mod_assets/monika/a/acs-anonymioo_ribbon_bisexualpride-5.png' is not loadable
> ```
> 
> Looks like you didn't install it correctly. Which tutorial did you use?

Well, The tutorial was how to give Monika the gifts, but not exactly to install sprite packs correctly.

**Comment by multimokia** [comment]
the transexualpride ribbon is not installed. You only have the bisexualpride ribbon json. But it's not loadable due to the images either being in the wrong place or missing. 

We recommend following [our official tutorial](https://www.youtube.com/watch?v=bjJ0U8l1m8c) for spritepack installation and gifting.

**Comment by LilMonika** [comment]
> the transexualpride ribbon is not installed. You only have the bisexualpride ribbon json. But it's not loadable due to the images either being in the wrong place or missing.
> 
> We recommend following [our official tutorial](https://www.youtube.com/watch?v=bjJ0U8l1m8c) for spritepack installation and gifting.

Okay, I will check it out

**Comment by LilMonika** [comment]
Thank you By the way, I can finally spoil her
