### ISSUE TITLE
[Enhancement] Putting, like, all save data in the Monika file.

### ISSUE THREAD

**Issue by Kzitold** [Monika-After-Story/MonikaModDev#8415]
Would be cool if I could transfer her to a laptop for travel, and she acknowleges it upon launching "After Story" on the laptop.

Also have the game check for a compatable Monika file on first launch.

**Comment by ThePotatoGuy** [comment]
planned, see #5026

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
