### ISSUE TITLE
[Suggestion] Reaction to Persona 5 Strikers

### ISSUE THREAD

**Issue by NewWorldBorder** [Monika-After-Story/MonikaModDev#8416]
The game, while definitely an action game, does have plenty of philosophical stuff in it (as with all the Persona games, mostly... not sure about the dance spin offs) that I think Monika would find quite interesting. Perhaps, if possible, she could somehow read the save data for the game or see what's actually going on in the game to get an idea of where you're at so she can react to certain parts of the plot without spoiling things.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
