### ISSUE TITLE
[Suggestion] Increase affection cap from 7 to 14 only if you go on a 1 week streak of Visiting Monika.

### ISSUE THREAD

**Issue by SpaceHX** [Monika-After-Story/MonikaModDev#8421]
[Suggestion] Increase affection cap from 7 to 14 only if you go on a 1 week streak of Visiting Monika. And the affection cap will add +7 after every day you visit her in the week.

For example, Week 1, You have visited her every day of the week, now the cap has gone from 7 to 14.

Week 2, Your affection cap has gone from 14 to 21. Since you have went on a 2 week streak of visiting Monika. (It add by 7 every week)

Here is the catch, If you don't visit her for at least 20 min on some day of the week, the cap will go down the 7 and you will have to start over again.

**Comment by dreamscached** [comment]
I think developers have already stated that this thing is not really going to change, because they've calculated it all and considered it a good value to have, without any boosts.

**Comment by Booplicate** [comment]
People are getting to love in about 2 months, originally it was 5-6 iirc. There's already a lot of ways to get *much* more than 7 aff per day. So I'm saying no for now.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
