### ISSUE TITLE
[Suggestion] - New piano notes sound a little bit incorrect

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#8431]
I reckon that the C should be kept instead of changing it into the C#, and changing the currently-using notes to  _opo opo ] ] p[ op [o_ (After ''In my hand...'' and ''When you're here...'')

**Comment by ThePotatoGuy** [comment]
According to our resident musician @multimokia , it's a subtle C#, but its there. 

The other notes issue is already documented in #7678 .

[closing as rejected]
