### ISSUE TITLE
Monika the nontalkative school girl

### ISSUE THREAD

**Issue by nikolikiller123** [Monika-After-Story/MonikaModDev#8432]
she has not been starting any conversations and i read the FAQ and none of the "Monika isn't speaking" have applied to the reason. i may have caused the problem by opening up the files for DDLC whilst DDLC MAS was on. i was looking for text files/interesting stuff, i didn't turn off MAS because i pulled the 'Goodbye' card 3 times today and i didn't want to find out what would happen. should i try and copy the persistence and put it on somewhere safe and redownload DDLC and MAS and put the persistence back in

**Comment by Daembo** [comment]
maybe check your settings and turn random conversations to normal?

**Comment by nikolikiller123** [comment]
it is on normal and has been

**Comment by Ulti70895** [comment]
Did you turn the ''Repeat topics'' off?

**Comment by nikolikiller123** [comment]
it fixed itself somehow

**Comment by nikolikiller123** [comment]
ok never mind, when i open up the game it seems to have only gave me one topic. then it has stopped

**Comment by Booplicate** [comment]
There's a finite number of topics, you unlock more over time.

**Comment by nikolikiller123** [comment]
I think I am incompetent
