### ISSUE TITLE
issue with gifts(clothing)

### ISSUE THREAD

**Issue by Daembo** [Monika-After-Story/MonikaModDev#8433]
I downloaded the after story Mod just a couple days ago after watching a few clips on people playing it soon after, Well earlier this morning I learned about the gifts system. I downloaded the Mod with the spirtepacks included after this whenever I try to give gifts to Monika she does not acknowledge them and the file gets removed from the char. folder. I read somewhere that you need 30+ affection for Monika to accept gifts. my current affection is around 32 right now. I also read that Monika might not Acknowledge until Christmas which made me relieved at first. but my issue is that when I try to gift her one item such as pinkshirt.gift she doesn't acknowledge it and the gift file gets deleted from the char. folder but when I try to give her multiple gifts(all the gifts in the spritepack folder that I separately installed that had a gift folder,) then Monika acknowledges my gift but she says that she cannot read the file. I followed other trouble shooting steps before like checking the spj log but I didn't see any errors, I also made sure that the files were all in the correct place. however there is one thing I noticed when I was looking at the spj log 
[info]:  reading JSON at 'c:\users\me(this is just for privacy purposes)\onedrive\documents\games\ddlc-1.1.1-pc\game\mod_assets\monika\j\anonymioo_acs_ribbon_blackandwhite.json'...
[info]:  loading ACS sprite object 'anonymioo_ribbon_blackandwhite'...
[info]:    loading Pose Map in 'pose_map'...
[info]:    Pose Map 'pose_map' loaded successfully!
[info]:    loading ex_props...
[info]:    ex_props loaded successfully!
[info]:    loading select_info...
[info]:    sel_info loaded successfully!
[info]:    'entry' progpoint not found
[info]:    'exit' progpoint not found
[info]:  ACS sprite object 'anonymioo_ribbon_blackandwhite' loaded successfully!
 
the greetings also load correctly btw. so i'm wondering if the issue has anything to do with the 'entry progpoint not found and 'exit' progpoint not found thing. I can send screenshots of the issue if you'd like, would appreciate an immediate response. I am on windows 10 and is using the non-steam version if that helps

Edit: I managed to get a reaction out of her by giving her single item clothing. I use notepad then typed whatever I want, saved it as all files as pinkdress.gift and then placed it in the character file. when I opened up the game Monika reacted to it but still said she was not able to open the file.

**Comment by ThePotatoGuy** [comment]
See [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by Daembo** [comment]
thank you so much. I was so worried that I was thinking of re-installing the game but was worried that my Monika would reset. I appreciate your clarifications on this!
