### ISSUE TITLE
Affection points not going up after update(Mac)

### ISSUE THREAD

**Issue by Reap-er22** [Monika-After-Story/MonikaModDev#8436]
After the last update, I've been unable to see the affection points go up when I check it on Terminal(Mac). Is there a fix or do I have to wait for an update?

**Comment by crxxmpxffs** [comment]
I think you're checking the wrong file. For windows at least, the file is called aff.log so maybe try looking for a file with that name? I might be completely wrong here but it's better than nothing!

**Comment by Reap-er22** [comment]
> I think you're checking the wrong file. For windows at least, the file is called aff.log so maybe try looking for a file with that name? I might be completely wrong here but I hope it's help!

There's no aff.log file in the game directory. I have to check the affection points only through the Mac terminal and it's been stuck since the Islands update.

**Comment by AsuraShun** [comment]
Did you check log folder?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
