### ISSUE TITLE
[Suggestion] - Window reactions for Dark Souls

### ISSUE THREAD

**Issue by LewyyM** [Monika-After-Story/MonikaModDev#8439]
So we all (or at least most of us) know Dark Souls are considered very difficult games (and they are), and as such they are commonly known. As a Dark Souls series player I suggest adding a window reaction for playing Dark Souls games, something like "Good luck on bosses" or popular amongst DS players community "Don't give up, skeleton!"

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
