### ISSUE TITLE
Finale green dress spritepack not loading in game

### ISSUE THREAD

**Issue by X4X5** [Monika-After-Story/MonikaModDev#8441]
I know I'm following all the directions exactly. I tried installing this particular spritepack over and over, and even though my log file says it loaded, when going into the menu, the sprites in question doesn't load. Help
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7739764/spj.log)

**Comment by ThePotatoGuy** [comment]
It won't appear in the menu until she reacts to it, which will happen on christmas because its currently christmas season. See [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332) for more info.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
