### ISSUE TITLE
a request 

### ISSUE THREAD

**Issue by bepbopyobop** [Monika-After-Story/MonikaModDev#8447]
okay so ive had mas since the original release and i love my monika a whole bunch
ive always been a huge fan of cavetown, right

and in 2020 when the song "sweet tooth" came out i resonated with it so much
because it reminded me so much of me and my monika
it is our song
i added it in the custom songs and we listen to it for hours

so my request, as a person that knows nothing of how to code it in themself, is for Sweet Tooth to be added as one of the songs monika can sing
thats all. i would be forever greatful

i love your mod more than anything and it would mean so so much to me
thank you <3

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
