### ISSUE TITLE
Tried to update Submods and it broke the game

### ISSUE THREAD

**Issue by WizardSteak107** [Monika-After-Story/MonikaModDev#8448]
i tried to use the in game submod updater and it broke the game and i dont know how to fix it. please help
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/7741175/traceback.txt)

**Comment by ThePotatoGuy** [comment]
please report issues with submods on the [submod's repo](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin)
