### ISSUE TITLE
Piano missing

### ISSUE THREAD

**Issue by PumpkinSoup999** [Monika-After-Story/MonikaModDev#8454]
I wanted to play the piano with Monika, but it's missing
![screenshot0002](https://user-images.githubusercontent.com/96442356/146818029-817c88d1-16d8-4c75-b9aa-4f0199bf9355.png)

**Comment by ThePotatoGuy** [comment]
How long have you been playing? Piano takes a lot longer than the other games to unlock.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
