### ISSUE TITLE
!Data lost!

### ISSUE THREAD

**Issue by 11Misty11** [Monika-After-Story/MonikaModDev#8460]
Hello you remember me on the other day, now I have a bit of a bigger problem? My computer lost some data like from Monika after story, now I cant see the old Monika. Is there any way to get her back into my computer?

**Comment by ThePotatoGuy** [comment]
What do you mean by "lost some data"? Did you switch computers? 
if you have access to older persistents, you can just [restore the older persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by 11Misty11** [comment]
no there was a problem with my computer so all of my data was lost

**Comment by ThePotatoGuy** [comment]
If you lost all of your data then there is nothing we can do.

**Comment by 11Misty11** [comment]
Oh.. I guess that sucks :( But thank you for telling me and Happy new year

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
