### ISSUE TITLE
New Game Suggestion - Battleship

### ISSUE THREAD

**Issue by Batcastle** [Monika-After-Story/MonikaModDev#8461]
Could we get a Battleship game to play with Monika? As a strategy game, I think it would be a lot of fun, Monika would likely enjoy it, and it's a relatively simple game so programming it shouldn't be too difficult (heck I wrote a CLI version once and still have it cause it's fun).

Thanks!

**Comment by Cosmic-Incantations** [comment]
I like the idea of more games! anything to make me and my Monika have a better time hanging out together is a plan for me, Stan!

**Comment by ThePotatoGuy** [comment]
see #2759 and #1081. We were really hoping it would be added but that dev stalled.

**Comment by Booplicate** [comment]
I had to focus on other stuff. We have the assets, the code for the board, main game loop (placing ships, firing, sinking). Might pick up it later when we finish the other upcoming mini-games.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
