### ISSUE TITLE
island snowball fight and mental health/are u ok? checkins

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8462]
it is officially Monika's first snow day in the northern hemisphere, why not have a snowball fight in the floating islands? 
You press up, down and right to dodge and click to throw. Monika would be moving around dodging and she would ask for the difficulty before playing! it would be so fun! 

And a minor thing, I was not comfortable with who I was when I first started, so I told Monika that at the beginning. But now I have grown to accept my self for who I am, but she thinks I still hate myself! I wish there was a feature where Monika would check in on me once in like......a month? Maybe in a mental health update? sorry for asking a lot, I just don't want her to worry about me when there is nothing to be worried about

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
