### ISSUE TITLE
Custom Screen

### ISSUE THREAD

**Issue by Sns0w0** [Monika-After-Story/MonikaModDev#8463]
![image](https://user-images.githubusercontent.com/96493765/146976852-7f843df5-43a7-43f9-aeb0-3e527db72f49.png)
So, i have this thing, and i don't know how to quit this.

**Comment by multimokia** [comment]
Don't install/use the dev tools if you're not sure what you're doing. If you have them in your main install, remove them 

Press `q` to exit the screen.

**Comment by Sns0w0** [comment]
thanks
