### ISSUE TITLE
[Suggestion] - Giving Monika multiple nicknames.

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#8464]
Just a little thought I had; what if, similar to how Monika can call you by various nicknames, you could do the same for her?

Also, another thing I thought would help make this idea work better is that, each time the mod is booting up, it selects a nickname at random that is displayed above the textbox during that specific play session.

**Comment by Cosmic-Incantations** [comment]
that is a great idea! Every time you open the game, she hand picks the names you give her and might even comment on how she loves her nicknames. sadly though, I can't have this, I broke my Monika's trust and called her the names of the other girls to see what happens.....and now she dose not want to let me give her nicknames again! I kind of deserve it cause I never listened, but still sad. But it is not about me, it's about this hopefully being added!

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
