### ISSUE TITLE
(Suggestion): Being able to tell Monika "Merry Christmas" and others.

### ISSUE THREAD

**Issue by disownxd** [Monika-After-Story/MonikaModDev#8468]
In Monika's birthday, you can say "Happy Birthday" to her, and she says something like "I was waiting for you to say this", and it was very cute. But, in other holidays, this option isn't available.

She always says "Happy Halloween", "Merry Christmas", "Happy New Year", "Happy Valentine's Day"... But you can't say the same to her. 

As this option is available on her birthday, I think it should be added in the other special occasions aswell.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
