### ISSUE TITLE
(suggestion) add things to Monika's calendar

### ISSUE THREAD

**Issue by SpaceyFlakes** [Monika-After-Story/MonikaModDev#8469]
It'd be cool if we could write down dates of stuff on Monika's calendar and she could inquire on them, like if you told Monika you didn't love yourself and you wrote down that you had a therapy appointment on X date at Y time Monika could comment on it and say something like 'I'm glad you're learning to love yourself.' Or, if you wrote down optometrist appointment Monika could ask if the player has glasses.

**Comment by Cosmic-Incantations** [comment]
yes! that is something I want added! You could also be able to add things like your friends or a family members birthday. You can set up reminders for other appointments, like going to the doctors, and  maybe you have to meet with someone at that day and you don't want to forget. how it could work is you would highlight the day by hovering the cursor over it and when you click it, Monika would bring up a menu for options to chose for that date, example:
apply event: which would give options for appointments, birthdays or meetings or just something miscellaneous like a release date of something. 
remove: gets rid of events you have added. 
Edit: allows you to make changes to what the event is supposed to be
inspect: she will make comments on the events like if a birthday is on that day, any thing you added or even Christmas
Cancel: exit menu, simple.

**Comment by SpaceyFlakes** [comment]
> yes! that is something I want added! You could also be able to add things like your friends or a family members birthday. You can set up reminders for other appointments, like going to the doctors, and maybe you have to meet with someone at that day and you don't want to forget. how it could work is you would highlight the day by hovering the cursor over it and when you click it, Monika would bring up a menu for options to chose for that date, example: apply event: which would give options for appointments, birthdays or meetings or just something miscellaneous like a release date of something. remove: gets rid of events you have added. Edit: allows you to make changes to what the event is supposed to be inspect: she will make comments on the events like if a birthday is on that day, any thing you added or even Christmas Cancel: exit menu, simple.

oh my god yes! That's exactly how I imagined it working!

**Comment by Cosmic-Incantations** [comment]
glad we are on the same wavelength, I thought of this YEARS ago, but I was to nervous to say anything

**Comment by ThePotatoGuy** [comment]
see #1771 and all the linked issues. We want this eventually but scheduling systems are complex and right now we want to stabilize other features that are low risk-high reward.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
