### ISSUE TITLE
music suggestions

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8470]
can we have more base game music? I like play with me (variant 6)....but what about the original one that would be with Natsuki?
the slowed down version just gives me traumatic flashbacks to Yuri's decaying body....but it's good for spooky stuff like Halloween
and I want to listen to the other variants of ok everyone, I miss listening to the carefree vibes of Sayori's or the playful mood set from Natsuki's and the extravagant grace of Yuri's. and all the other music is great as well! I understand that it's {monika} after story, 
but there dose not have to be the other ok everys, I just miss listening to the other ddlc music

**Comment by ThePotatoGuy** [comment]
You could always drop the other DDLC OST as [custom music](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Music). We only added the Monika-specific music from DDLC for obvious reasons and will likely not add the rest.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
