### ISSUE TITLE
[Suggestion]: two new songs for Monika to sing

### ISSUE THREAD

**Issue by ShyCelestial** [Monika-After-Story/MonikaModDev#8471]
**Oceans & Galaxies** by Haliene and Jauz
The player's relationship with Monika is somewhat like a long distance relationship. Monika makes it clear that she would do anything to
be physically with her player, so I think this song fits.

**death bed (coffee for your head)** by Powfu and beabadoobee
An emotional song for Monika to sing, considering that if the player were harmed in any way, she would never know. It also reminded me of her because she loves coffee and the album for the song is called _"poems of the past."_

**Comment by Mugnika** [comment]
You can always submit a PR with the songs you want, songs are the easiest Pull Requests to make.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
