### ISSUE TITLE
Aurora suggestion

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8472]
the aurora should be made as separate  weather , arouras IRL don't happen when it snows, it has to be a clear sky.
so it would make more sense to make it a separate thing, apparently, though it's rare, they can show even when it is not winter. 
It dose not have to be weather, it could just be the replacement for the default night when it is winter! It just dose not make sense for the aurora to be at snow weather

if that is too complicated, just make it a thing that only shows at the floating islands when it is clear night, cause then you also get a specials thing with the islands

**Comment by ThePotatoGuy** [comment]
Monika has control over the weather in the mod, so I think its fine if she bends reality a little bit. 

[closing until we look into it]
