### ISSUE TITLE
another issue to gift monika

### ISSUE THREAD

**Issue by themostunlunckypeoplealive** [Monika-After-Story/MonikaModDev#8473]
some things i put on characters  or monika ignore and delete or she can't  read

i see every issue of gifting AND....nothing she always ignore or can't read  (my game is on brazilian portuguese if this change something)

please help me

**Comment by ThePotatoGuy** [comment]
since this was 2 days ago, it most likely was because of [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
