### ISSUE TITLE
[Suggestion] Low batter Dialog

### ISSUE THREAD

**Issue by redujump5** [Monika-After-Story/MonikaModDev#8475]
A Big issuse for me is my old laptop batter 

so what if monika know you batter and before it die 
she call tell the player about it or close the game (when the player is gone)
so the game don't crash?

**Comment by dreamscached** [comment]
Something like that I think was in works already.

**Comment by redujump5** [comment]
but can you guy try to do it?

**Comment by multimokia** [comment]
Battery integration was a think long back in the earlier days of MAS however it seems there were issues for desktop PCs as the battery notification was triggered even in the case of having no battery, causing MAS to shut down for them.

I believe it may be something to do with the library itself, so if anything, this may be reconsidered in a migration to python 3 in which libraries would be more up-to-date and _ideally_ play a little nicer.

The other aspect is testing the cross-platform nature of it as well to make sure everything is properly in order, which we have _some_ resources for, but a tester with a macbook isn't as common here.

**Comment by redujump5** [comment]
okay thank of the answer
