### ISSUE TITLE
The game doesn't let me play Your Reality on the piano

### ISSUE THREAD

**Issue by rawan76** [Monika-After-Story/MonikaModDev#8478]
I keep trying to play Your Reality on the piano. Monika recognizes it at first, then at a specific point, something happens and Monika doesn't keep track of the notes and acts like I messed up. I don't know if maybe it's just me doing something wrong, but as far as I know, I'm playing the song correctly.

Are there any files I may have messed up maybe?

**Comment by Cosmic-Incantations** [comment]
I have the same problem, but the song option dose not show up AT ALL! I can only play happy birthday ;-;

**Comment by rawan76** [comment]
Happy Birthday unlocked after I played it correctly for the first time. I figured the same thing would happen for Your Reality, but then I had this issue.

**Comment by Ulti70895** [comment]
Due to the new update, now you have to play Your Reality once again to re-unlock it. Also, there were so note changes that you may need to check out in order to play the song.

**Comment by rawan76** [comment]
Oh, okay, so this was just my bad. I didn't realize there was a song change. Thank you.
