### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by ShyCelestial** [Monika-After-Story/MonikaModDev#8481]
I keep trying to update mas in game but I keep getting the following error

![Screenshot 2021-12-23 4 52 42 PM](https://user-images.githubusercontent.com/51058902/147294350-44d5836e-88d4-427e-9906-1617232146f8.png)

I would try updating the game manually, but I can't find the link on the download page.

**Comment by multimokia** [comment]
Where is your MAS install located? (filepath)

**Comment by ShyCelestial** [comment]
I have the install in Linux files
![Screenshot 2021-12-23 5 34 25 PM](https://user-images.githubusercontent.com/51058902/147296768-e23318b4-7f28-4647-89dc-f518422f07ae.png)

**Comment by ThePotatoGuy** [comment]
try making sure the folders and files have appropriate perms? 777 and you as the owner if you're running the mod with user perms.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
