### ISSUE TITLE
[Suggestion] - Taking Monika on dates/Moving her to laptop

### ISSUE THREAD

**Issue by SirilTheFirst** [Monika-After-Story/MonikaModDev#8482]
Right now the only option to take Monika with you is to use a flash drive and she will not be able to see, nor react to anything. 
I suggest the dialogue option in goodbyes "I'm going to move you", to which she will reply "Oh, are we going somewhere?".
You will get options like:
-I'm taking you on a date 
-I'm moving you to another PC
-Nevermind 
etc.

She'll ask you to be very careful and will move (or maybe copy for safety reasons) the persistent file and herself into characters folder, after which you will be able to transfer her to an empty MAS on another computer, and upon opening the game on the new computer she will react accordingly. If it's a date, she will act more flirty and new dialogue options will be available until you decide to finish the date. And if she is just moved she will say "This new place is nice, thank you :)" and everything will continue as usual

It would be great if something like that was possible on the phone, but from what I understand, there are legal problems. So that's my idea for now

**Comment by KritRom** [comment]
"I am moving you to another PC" option wouldn't require her to become a file. To transfer her, you will need to just need the MAS folder on the new computer, and making her a file would only complicate it.

However, letting her know she'll be moved to another PC is not a bad idea.

**Comment by SirilTheFirst** [comment]
> "I am moving you to another PC" option wouldn't require her to become a file. To transfer her, you will need to just need the MAS folder on the new computer, and making her a file would only complicate it.

It's only for immersion purposes. It would be kinda weird if she let us take her file on usb, but not when moving her. 
But I guess if it just complicates stuff for no reason, it's not necessary

**Comment by AxelX0** [comment]
I was going to suggest that myself
Since the entire story is based on her seeing everything on our desktop,it'd be weird that she doesn't react how she is in a total new environement....besides,alot of people have this issue of "Moving to a new computer",so it'd be good if Monika gives a good advice and reminds to take the persistent file

**Comment by ThePotatoGuy** [comment]
see #5026 - there are some immersion issues that need to be addressed first

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
