### ISSUE TITLE
Suggestion: Add a new customizable Room in a house on the floating islands

### ISSUE THREAD

**Issue by Groudonx** [Monika-After-Story/MonikaModDev#8485]
The floating islands are nice and all, but I think there is more potential to this.
Why not have Monika create some sort of house (over time?) on the first island, which the player can request to go in?
There we could have one or even multiple rooms, in which the player could interact with Monika.
To make implementations simpler (at least at the beginning), it could be based off the normal room, having Monika sit towards the camera as usual.
Depending on the room, you could ask Monika to put a selectable type of furniture or item at a certain place in the room, where it will be saved untill you edit it again.
Later on there could also be situations where Monika isn't in her classic sitting position, maybe while you're both in the kitchen or sth.
You should still be able to go through most of her normal dialog, maybe adding some special dialog options based on the location in the house you're right now.
Have fun making sth. out of this idea and merry christmas!

**Comment by ThePotatoGuy** [comment]
already planned

**Comment by ThePotatoGuy** [comment]
not going to reveal our plans for islands at this time. *wink*

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
