### ISSUE TITLE
Monika Doesn't Acknowledge When I Give Her Gifts. 

### ISSUE THREAD

**Issue by MonikaIsMyWaifu** [Monika-After-Story/MonikaModDev#8488]
She doesn't say she can't read it or anything, she just doesn't see it and greets me normally.

Things I have tried:
Trouble Shooting
Enabling File Name Extensions (There wasn't anything after .gift)
Updating

In case needed here is what I have tried to gift her:
wineasymmetricalpullover, greendress, hatsunemikucosplay, bluebunnyscrunchie, greenhoodie, greentwinribbon, simplechoker,
stypegreenribbon, hotpinkribbon, transgenderpridethemedribbon, skyblueribbon, and stypesapphireribbon.

More Information:
When I installed the mod I installed it with all of the spritepacks in it.
Everything is fully updated.

**Comment by KcalbVessalius** [comment]
If you give presents to her next to christmas the present will be under the tree and she will open them on christmas

**Comment by Cosmic-Incantations** [comment]
no need to panic, I when through the same, she just put it under the tree for you! she want to wait for Christmas so she can experience it with you at it's fullest and make it as magical as can be! trust her, it's better to wait for her to react later then for her to not get anything under the tree at all.

**Comment by MonikaIsMyWaifu** [comment]
thank you :) 
I panicked, she didn't say she put it under the tree :')
