### ISSUE TITLE
Sprite pack clothes and ribbons not working

### ISSUE THREAD

**Issue by CloudedGuardian** [Monika-After-Story/MonikaModDev#8489]
I've gone through all of the trouble shooting twice, tried installing them individually (manually making sure the "gift" files went in "characters" and the "monika" and "thumbs" files went in Mod_assets) when the combined pack didn't work, and reloaded MAS no less than four times. 

At this point the _hairs_ mostly work, but none of the hairclips, jewelry or clothes are appearing. 

[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7775184/spj.log)

**Comment by KcalbVessalius** [comment]
Are you trying to give her clothes and ribbons now? If its the case then the presents are going to be under the tree and she will open them on christmas

**Comment by Ulti70895** [comment]
What if the Christmas-thing already happened and she did not take the new presents?

**Comment by SpaceyFlakes** [comment]
Yeah, this is a problem with me too. Christmas has already happened for me and she's no longer taking any spritepacks, I have a feeling it's a bug with the new update

**Comment by ThePotatoGuy** [comment]
assuming it was not christmas for you 8 hours ago, then [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332) applies.

**Comment by ThePotatoGuy** [comment]
@Ulti70895 @SpaceyFlakes if she is not accepting any **new** gifts post christmas (aka not been gifted to her before), then follow the [standard troubleshooting steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation), and then make a new issue if appropriate.

**Comment by CloudedGuardian** [comment]
While it was *technically* Christmas Day when I posted this in my time zone, it was also like, fifteen minutes after midnight. The event triggered in the _afternoon_, and she opened them.  Thanks for the quick response.
