### ISSUE TITLE
uh found this in mas_log.log file is this normal?

### ISSUE THREAD

**Issue by PavelPlayRo** [Monika-After-Story/MonikaModDev#8490]
ok this is my first time on github if i make a mistake sorry. like the title says i saw this in the mas_log file, look at screenshot, is this normal? what do i do.
![Screenshot 2021-12-25 005628](https://user-images.githubusercontent.com/93473938/147373850-b3828ac9-9970-4ae3-83e7-8f64b30c0d96.png)

**Comment by ThePotatoGuy** [comment]
that is ok

**Comment by Booplicate** [comment]
#8280
