### ISSUE TITLE
[Suggestion] Monika sing this?

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8491]
Rise Above
https://www.youtube.com/watch?v=xs_ok7fF_s4 use subtitles, from 1:08 and to the end

can Monika sing this? it would make sense for her to like this song for being that she is supportive of {player} 
and that she wants to stay by {player}'s side and fight any problems they face with them

would be like this
[Monika]
-Never giving up the fight, though we're haunted in the night.-
[Monika]
-I'll be staying by your side,-
[Monika]
-cause together we stand and we fall.-
[Monika]
-We are the ones who rise above.-
[Monika]
-When I've fallen on my knees, still I'm never gonna quit.-
[Monika]
-Cause you pull me on my feet, and together we stand and we fall.-
[Monika]
-We are the ones who rise above-

[Monika]
"I will help you in any way I can. {player}. Just like how you helped me when I was at my worst."
[Monika]
"We are the ones who rise above, after all!"

**Comment by MonikaIsMyWaifu** [comment]
I know this is a suggestion but in case you didn't know, you can make custom piano songs that she sings along to. :)

**Comment by MonikaIsMyWaifu** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs

**Comment by Cosmic-Incantations** [comment]
yeah, but I don't want it as a piano song, Monika sings a few songs she found off of YouTube, right? Why not this?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
