### ISSUE TITLE
Request: More items for Monika to take with her when going somewhere.

### ISSUE THREAD

**Issue by MonikaIsMyWaifu** [Monika-After-Story/MonikaModDev#8494]
Something to keep her entertained while in the flashdrive.
I imagine a game-boy like item.

It would:
Look like a gameboy
Occasionally light up (optional)
Come in a small rectangle gift box (optional)
And would show up as a file next to monika when going somewhere.

This is more of a suggestion but I think it would be really cool.

Let me know if its possible, and what you think.
If it is possible I might make it myself.

**Comment by ThePotatoGuy** [comment]
so like, generating additional files that have to be returned or else Monika will be like "I lost my <x>!"? Interesting.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
