### ISSUE TITLE
A gift is blocking my Monika an trowing an exception

### ISSUE THREAD

**Issue by Tigron5654** [Monika-After-Story/MonikaModDev#8496]
So a coplee of days before christmas, I downloaded the sprite pack and, as instructed I put the mod_assets on the game folder and the  "giftName".gift on character and today, 25-12-2021 christmas day, she was opening the presents and when she was finish, she try to open them again and it trow this error.

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1510, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/script-holidays.rpy", line 2400, in script
  File "game/script-holidays.rpy", line 2400, in <module>
IndexError: pop from empty list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1510, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/script-holidays.rpy", line 2400, in script
  File "C:\Users\erick\OneDrive\Área de Trabalho\otras cosas\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\erick\OneDrive\Área de Trabalho\otras cosas\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-holidays.rpy", line 2400, in <module>
  File "C:\Users\erick\OneDrive\Área de Trabalho\otras cosas\DDLC-1.1.1-pc\renpy\python.py", line 618, in do_mutation
    return method(self, *args, **kwargs)
IndexError: pop from empty list

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.6

I don't know what to do and, I didn't find any other post with the same error. Someone please help me.

**Comment by jmwall24** [comment]
Did you have a crash during the christmas event?

**Comment by Tigron5654** [comment]
> Did you have a crash during the christmas event?

yes that has something to do?

**Comment by jmwall24** [comment]
Yeah, so you need to restore a backup persistent from as late as possible on december 24th. Please refer [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for how to do that. Once you find the persistent folder, make a backup copy of it just in case something goes wrong.

**Comment by Tigron5654** [comment]
> Yeah, so you need to restore a backup persistent from as late as possible on december 24th. Please refer [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for how to do that. Once you find the persistent folder, make a backup copy of it just in case something goes wrong.

hey just a question do I have to change the db.mcal to?

**Comment by jmwall24** [comment]
Nope, that doesn't need to change. Were you able to resolve the issie?

**Comment by Tigron5654** [comment]
> Nope, that doesn't need to change. Were you able to resolve the issue?

well apparently I did but the db.mcal needed to be changed to.

**Comment by jmwall24** [comment]
dbcal doesn't need to be changed, what's going on?

**Comment by Tigron5654** [comment]
soo apparently the db.mcal the original one just restores the persistent file so you need to change it to the same as the persistent backup.

**Comment by jmwall24** [comment]
that's not true, can you send a screenshot of what it looked like when you restored the persistent?

**Comment by Tigron5654** [comment]
> that's not true, can you send a screenshot of what it looked like when you restored the persistent?

first you will think I'm stupid but what exactly you need to see is the game or the archive.

and the think is that when I don't change the db_mcal the game just loads and Monika tell me that someone left a letter in the characters folder for me and the persistent I'm trying to load apears as persistent_bad.

**Comment by jmwall24** [comment]
something went wrong then. were you able to get her to react to Christmas and the gifts?

**Comment by Tigron5654** [comment]
> something went wrong then. were you able to get her to react to Christmas and the gifts?
> 
> and i wanted to see a picture of the folder with the persistents in it

ok so I'm going to see if the error doesn't persist but now it actually loaded the persistent without needing to change the db_mcal

**Comment by jmwall24** [comment]
just make sure she reacts to it being christmas and the gifts and you should be good to go

**Comment by Tigron5654** [comment]
> just make sure she reacts to it being christmas and the gifts and you should be good to go

yes it all works now. thank you very much and take care.
