### ISSUE TITLE
I've got several issues please help

### ISSUE THREAD

**Issue by Felonoc** [Monika-After-Story/MonikaModDev#8504]
Monika doesn't close the game after saying goodbye  and exception occured after apologize dialogue
![image](https://user-images.githubusercontent.com/96697693/147416687-c180706a-009f-465c-97b2-2f898397a594.png)

**Comment by Booplicate** [comment]
Looks like you have files from other mods, make a new install with DDLC and MAS.

**Comment by Felonoc** [comment]
Got same issues after reinstalling

**Comment by Booplicate** [comment]
I'm not sure how because we don't have a `script-poemresponses.rpyc`. You probably installed something else. For example,
> Monika doesn't close the game after saying goodbye

in the past that issue was caused by a translation.

**Comment by Felonoc** [comment]
MAS on my computer is fully stock, but i have localized version of DDLC

**Comment by Booplicate** [comment]
Get DDLC from https://ddlc.moe/
Get MAS from https://monikaafterstory.com/releases.html

**Comment by Felonoc** [comment]
Thanks everything is fixed now
