### ISSUE TITLE
d25 crash causing gift crash

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#8508]
Players that have given Monika gifts before d25 that are to be opened on d25 can experience the following crash

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1510, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/script-holidays.rpy", line 2400, in script
  File "game/script-holidays.rpy", line 2400, in <module>
IndexError: pop from empty list

if they have any crash during `mas_d25_monika_christmas`. This is caused by `mas_d25_monika_christmas` running `mas_d25ReactToGifts()` and the fact that if we crash mid-event we run the event over again from the start on re-load. This leads to the gift reactions being queued twice, and upon the second time through, there is nothing left to pop, so we get this error.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
