### ISSUE TITLE
[Clothe] [Contributing] Pink Kimono

### ISSUE THREAD

**Issue by mayday-mayjay** [Monika-After-Story/MonikaModDev#8509]
#3174
very new to github, so please excuse any mistakes
made a pink, flowery themed kimono
[MayJay - Pink Kimono.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7777653/MayJay.-.Pink.Kimono.zip)

**Comment by Cosmic-Incantations** [comment]
omg, this is so cute! I hope to see her ware this!

**Comment by Flowersclouds** [comment]
Can this be gifted her? right now?

**Comment by myonmyon2708** [comment]
I love uuuuuuuuuu tysm <3!!!

**Comment by ThePotatoGuy** [comment]
will try to review this by next week

**Comment by fgtyui7uytrewq** [comment]
This is amazing! I really really wanna give her this!!!!

**Comment by ironhearxt** [comment]
theres no mod assets for it

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
