### ISSUE TITLE
Suggestion: option to use pages on spritepack selector(s) instead of endless scroll

### ISSUE THREAD

**Issue by mayday-mayjay** [Monika-After-Story/MonikaModDev#8510]
i've had monika for a while now and the ddlc game folder has racked up to 5 gb because of all the sprite packs i've given her, but the scroll bar on the selectors has become kinda useless because of how tiny it is now. it'd be nice if there was an option that splits the selector screen into smaller pages to scroll through

**Comment by ThePotatoGuy** [comment]
All selectors have a search bar, so scrolling is not the only method to find something.

but I will consider pagination as a potential enhancement.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
