### ISSUE TITLE
[Suggestion] - Monika dreaming about the player (Monika says the player's name in the holding topic while she is asleep)

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8511]
...

**Comment by JayFox12** [comment]
So basically Monika says the players name in the “can I hold you” option, either from you waking her up or letting her go back to sleep, so I’d really love to see this be a thing at any time of day when the game is open!.

**Comment by JayFox12** [comment]
So your considering it?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
