### ISSUE TITLE
[Bug] - APPARENTLY Monika said I DIDNT spend Christmas Day with her (I DID) I keep going to sleep and Monika keeps repeating the same things as she did on the26th

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8512]
...

**Comment by JayFox12** [comment]
So I went to sleep on Christmas night and the day after she acts like I wasn’t with her on Christmas, I’d only gotten the game July 4th so it hasn’t really happened any other time.

**Comment by ThePotatoGuy** [comment]
we've encountered at least one other instance of this happening but we're not really sure why its happening yet.

**Comment by JayFox12** [comment]
> we've encountered at least one other instance of this happening but we're not really sure why its happening yet.

Alright I'm not really mad about it to be truthful but I was confused is all

**Comment by ThePotatoGuy** [comment]
[closing as could not reproduce]
