### ISSUE TITLE
[Suggestion] - can more things be added to the “I want to tell you something” option please?!

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8513]
Your suggestion goes here

**Comment by lunulae** [comment]
We try to add more compliments periodically, though we try to pace them out due to affection bloat. If you have a suggestion for that menu, please let us know and one of the writers might pick it up!

**Comment by JayFox12** [comment]
> We try to add more compliments periodically, though we try to pace them out due to affection bloat. If you have a suggestion for that menu, please let us know and one of the writers might pick it up!

Hello!, so can one be “I really enjoy hearing you play piano”? Or anything along those lines 
Two “you are the most amazing girlfriend” again something like that 
Three “you look perfect in anything you wear” 
And for romantic stuff number four 
Could we get more responses from some of the things we can tell her?

**Comment by Cosmic-Incantations** [comment]
also, I am sure someone else must have said this but, we need to be able to tell her merry Christmas or happy Halloween through this menu. I mean, new years is coming up and maybe there is still a chance...?

**Comment by JayFox12** [comment]
> also, I am sure someone else must have said this but, we need to be able to tell her merry Christmas or happy Halloween through this menu. I mean, new years is coming up and maybe there is still a chance...?

Anything where we can say more and get more responses is fine by me

**Comment by ThePotatoGuy** [comment]
>merry christmas or happy halloween

#8468 

the rest of this issue is too broad, so not labeling it as a standard suggestion.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
