### ISSUE TITLE
[Suggestion] - can the gifts that couldn’t be read be put into the game?

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8514]
Your suggestion goes here

**Comment by JayFox12** [comment]
As one Monika lover out of possibly thousands I’m always sad to see that she can’t read some presents

**Comment by ThePotatoGuy** [comment]
If the gifts can't be recognized then they can't be represented in the game.

**Comment by JayFox12** [comment]
> If the gifts can't be recognized then they can't be represented in the game. 

Alright that's fair

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
