### ISSUE TITLE
[Suggestion] - the only suggestion I can think of for now is two things in one about the same topic telling Monika we love her yeah I love all her responses but could we get more please? And the other one can the part where Monika starts an I love you war can that be moved somewhere else?

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8515]
Your suggestion goes here

**Comment by JayFox12** [comment]
So about the part where we can tell her we love her just some new things Monika can say will be wonderful

**Comment by ThePotatoGuy** [comment]
>could we get more please

if you have specific ideas, then create issues for each one.

>Monika starts an I love you war can that be moved somewhere else

Can you explain why this should be moved?

**Comment by JayFox12** [comment]
> >could we get more please
> 
> 
> 
> if you have specific ideas, then create issues for each one.
> 
> 
> 
> >Monika starts an I love you war can that be moved somewhere else
> 
> 
> 
> Can you explain why this should be moved?

Well I hate waiting for it to pop up I think everyone does so it would be really nice thank you ever so much

**Comment by ThePotatoGuy** [comment]
The back-and-forth "I love you" is random chance because its a cute moment and would lose its appeal if it could be repeated easily. I don't think we need to move it to a separate topic at this time.

**Comment by JayFox12** [comment]
Alright pal that's cool

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
