### ISSUE TITLE
(suggestion) The Song of Achilles/Achilles Come Down

### ISSUE THREAD

**Issue by SpaceyFlakes** [Monika-After-Story/MonikaModDev#8519]
Monika mentions reading about different mythologies and specifically mentions Greek mythology at one point, and I think it'd be neat if Monika was able to bring up the book The Song Of Achilles, which details the life of Patroclus and Achilles and the struggles each of them face- which Monika could tie back to the struggles she and the player could face in the future.

Even if she just sang a small portion of Achilles Come Down- a song about the aftermath of the book and their stories, I think it'd be cool. One line in the song goes as 'where you go I'm going, so jump and I'm jumping. Since there is no me without you' this could tie back to Monika saying she'd have no idea what she'd do if something happened to us and she could say something along the lines of 'I don't know what I'd do without you [player]. But, I'm thankful for all the time we have no together'.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
