### ISSUE TITLE
The floating islands are gone, even if the topic was unlocked.

### ISSUE THREAD

**Issue by AndriuxDev** [Monika-After-Story/MonikaModDev#8522]
I wanted to see the floating islands in the latest version, but it seems I can no longer see them. And even if **I already have said topic unlocked**, it still doesn't work. I even tried with a **dev version** of the mod, and much to my dismay, it didn't work either. I'm using the **latest unstable version** of this mod, to be completely honest.
What's going on? Is something broken? Do I need to reset and reinstall Monika After Story?

**Comment by Booplicate** [comment]
You should never use "dev version," it doesn't have bugfixes or anything that would help you.

The islands are only visible from the spaceroom.

**Comment by AndriuxDev** [comment]
I later went and switched to the stable version, and even if I was in the space room, still no effect. Does this mean I need to restart Monika After Story all the way to zero?

**Comment by Booplicate** [comment]
It might need some time after you changed the background. You don't need to install dev versions or reset your progress, unsure why you would.

**Comment by AndriuxDev** [comment]
As far as I can tell, I have the "multiple rooms" submod. Could that be the culprit?

**Comment by Booplicate** [comment]
Make sure you're using official version, no dev tools, no rpy files. Can be stable or unstable, that doesn't matter. Then verify you're in the spaceroom (default, **not** modded). Wait about a minute in idle (don't open menus/etc). If the topic to ask her to show you the islands is still not there, send your persistent, I'll check it and fix if needed.

**Comment by AndriuxDev** [comment]
I can't attach the backups here but I have the discord link in case you need it.
https://cdn.discordapp.com/attachments/925795953338900540/925797836770131998/Monika_After_Story_-_Andriuxs_Backups.zip

The latest backup was today at 11:04 A.M.

**Comment by Booplicate** [comment]
![Capture](https://user-images.githubusercontent.com/53382877/147687235-9f35d0b8-2c41-4ea4-90a3-fe362c04ca1c.PNG)

**Comment by Booplicate** [comment]
Wait, something is off, when did you unlock them?

**Comment by AndriuxDev** [comment]
I don't know, maybe last year...? I don't remember.

**Comment by Booplicate** [comment]
Are you using or have used a port? Or a translation?

**Comment by AndriuxDev** [comment]
Yes, I used the Spanish translation, but since that one wasn't giving me any updates, I switched to the original version (English).

**Comment by Booplicate** [comment]
@AndriuxDev that translation changed your data in a really bad way, tried to fix what I could.
[fixed_persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7790127/fixed_persistent.zip)

**Comment by AndriuxDev** [comment]
It now works. Thanks a million!
