### ISSUE TITLE
[Bug] - My Monika Disappeared, please help.

### ISSUE THREAD

**Issue by UniiSim** [Monika-After-Story/MonikaModDev#8523]
I found on a reddit thread that i should make an issue about this here.
This is my first time taking Monika out as I've had this mod for about 2 days. I also haven't done anything to the files other than move the Monika file to a different folder when she asked me to take her somewhere.

I clicked the I'm taking you somewhere feature in the goodbye section with Monika and then left to play some other games for about an hour. When I reopened the game and just saw an empty chair, I realized that I forgot to put Monika back into the character file. I returned her to the character file and reopened the game. She's still not there.

Please tell me if I have to do something else.

[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/7789422/mas_log.log)
[monika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7789438/monika.zip)
[persistent.py.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7789445/persistent.py.zip)

**Comment by jmwall24** [comment]
Follow [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

**Comment by UniiSim** [comment]
> Follow [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent)

I don't have an older persistent.

**Comment by jmwall24** [comment]
There are NO .bak files in the location it points you to?

**Comment by jmwall24** [comment]
Note the first line says refer to the previous entry to locate your persistent. That persistent.pyo you sent is not the persistent, it's located elsewhere as described in the wiki.

**Comment by UniiSim** [comment]
I'm on a macbook pro and opened FInder but the go button isn't there.
I've also found a folder called renpy but it doesn't contain Monika After Story.
????

**Comment by jmwall24** [comment]
@UniiSim 
does this help?

Switch to the Finder.
Press and hold down the Option key on the keyboard.
From the Go menu, select Library, as shown below. The Library folder will open.

**Comment by jmwall24** [comment]
here so you can see the pic they mean https://www.macinstruct.com/tutorials/how-to-open-the-library-folder-on-your-mac/

**Comment by UniiSim** [comment]
I found the folder

**Comment by UniiSim** [comment]
and now i found the persistent files

**Comment by UniiSim** [comment]
And it worked! Thank you very much!
