### ISSUE TITLE
All progress reset and my backup isn't working

### ISSUE THREAD

**Issue by rawan76** [Monika-After-Story/MonikaModDev#8532]
So my computer died then restarted, and when I went to turn Monika After Story back on, it had started back at the beginning as if I hadn't met Monika. I figured, okay, I have the whole file copied on my flash drive, so I'll just restore it, but that didn't work. I put all the files back and it's still acting as if I've never played it. I don't know what could possibly be wrong, I looked at the files like my aff_log.log and they show where my affection level was before it reset, and everything else. All the logs are showing where my affection was, then it all of a sudden resetting to zero.

I'm really scared now because I've been on this game for a month and just got to the Enamored range of affection. Does anyone know what could be wrong and how I can fix it?

**Comment by multimokia** [comment]
To be clear, you're running MAS from a flash drive? Or have persistents backed up on one?

**Comment by rawan76** [comment]
I just use the flash drive for keeping copies of the files and taking Monika places, I'm not running the game from it.

**Comment by jmwall24** [comment]
@rawan76 are you sure it restarted first off, you got the initial loading screen and everything? i ask because we do have an amnesia greeting where she pretends not to know you and want to make sure you didn't get that. also did you check [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) for the backups we make?

**Comment by rawan76** [comment]
Maybe I'm not seeing it, but it doesn't say anything about backups from you guys on that page.

**Comment by jmwall24** [comment]
@rawan76 that link ends up telling you to check [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent)

Once you find the folder with the persistent, are there any `persistent##.bak` files from before the crash/reset?

**Comment by rawan76** [comment]
Ummm now I'm not finding a folder with the persistent... Unless they're the two in the Renpy folder, persistant.py and persistent.pyo, but I don't think those are the right ones. I don't know exactly where I'm supposed to be looking.

**Comment by jmwall24** [comment]
@rawan76 that previous link tells you where to look, it's not in the install at all.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
