### ISSUE TITLE
[suggestion] changing the calendar color

### ISSUE THREAD

**Issue by Iceninja64** [Monika-After-Story/MonikaModDev#8543]
this is just a minor thing; but you should be able to change the calendar color from white to dark as the menu UI

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Iceninja64** [comment]
@ThePotatoGuy just to clarify that I mean the dark mode and the light mode for the menu ui should be the same. I don't know if I made a mistake clarifying this. Sorry for the inconvenience

**Comment by Booplicate** [comment]
Note, the calendar is being considered part of the room, **not** a UI element, so UI colour schemes don't affect it.

**Comment by Iceninja64** [comment]
@Booplicate ah I kind of figured it was like that but I also thought it was going to be in the extra menu, when monika told us she will be adding more things to the extra menu.

**Comment by Iceninja64** [comment]
I was wondering where was the calendar in some of the space rooms
