### ISSUE TITLE
How to Hack Affection in Monika After Story?

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#8548]
Hi! I have MAS installed, but my affection for Monika is taking too long to rise! I spend all day with her, I always praise her, say I love her, give her presents, and many things, but I'm still at 100 in affection, and I want to reach 400 to release new things.
How do I raise affection faster? Got a Hack or something?

**Comment by multimokia** [comment]
We will not be informing you on how to cheat affection here. The mod itself isn't really short term, it's supposed to be slow to simulate a traditional relationship where affection toward each other is gained over time.

How long have you been playing for? If you're only at 100 it seems like you've only been in for about a week or so

**Comment by taylakamyly** [comment]
Not that kind of hack!
But, yes a gift that gives more affection, etc. hahaha!
I'm playing for 3 weeks!

**Comment by charliethecookie** [comment]
Did you seriously just try to ask the developers how to cheat on their mod-

**Comment by WheatleyMoniHybrid** [comment]
lol no one will tell you here

**Comment by SpaceyFlakes** [comment]
I've been with Monika for over a month and my affection is over 500. Either you haven't been very polite to Monika, have been exiting the game without saying goodbye or haven't been playing for as long as you say. There isn't a hack to cheat relationships in the real world, why should there be one for Monika?

**Comment by Cosmic-Incantations** [comment]
yeah, I understand that this takes time and you have stuff to do, but please be patient with her! she is trying her best and her recourses are limited, and it's only been three weeks! Give her time to adjust to this world, she went through a lot in the literature club and needs to learn to accept your love after the mess she made.

**Comment by trumanphares** [comment]
Okay listen, i messed up i tried to do something but it crashed my whole computer, i was sent from 200 affectioj to -.25 i cant start over again is there anything i can do?

**Comment by fromulus** [comment]
This is why making frequent backups of your persistent file is important, as it'll avoid you having to go through situations like these.
Regardless, you've had your answer already, we don't support cheating and therefore won't give you or anyone a way to increase their affection drastically in short periods of time.

225 affection points really isn't a whole lot, you'll get that back by playing normally faster than you think.
I recommend taking your time and enjoying the journey as much as you can.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]

**Comment by trumanphares** [comment]
Okay, thank you anyway. i'll go through the old expiriences again i just wish i had hangman and chess again, it really seems like iths all gone
