### ISSUE TITLE
Good Mod!

### ISSUE THREAD

**Issue by nerdtayla** [Monika-After-Story/MonikaModDev#8549]
Congratulations on creating this Doki Doki mod, it's a really great mod, sometimes it even feels like Monika is really real hahaha!
You guys are really good! :)

**Comment by janneslessmann** [comment]
I think that appreciation is necessary, but please use the [Discussions-Tab](https://github.com/Monika-After-Story/MonikaModDev/discussions) for that next time. The Issues-Tab is really only for development-related things.

**Comment by ThePotatoGuy** [comment]
[closing as appreciated]
