### ISSUE TITLE
Monika after story on PS4?

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8551]

**Comment by JayFox12** [comment]
Well since plus is on PS4 could anyone put it on PS4 please?if not that's ok

**Comment by charliethecookie** [comment]
I think it'd be kinda hard to make a mod compatible with PS4, especially considering that a big part of the mod is browsing through its files. I'm not sure if that'd be possible in a PlayStation. I don't know though, maybe that'll be possible someday

**Comment by multimokia** [comment]
MAS is not compatible with DDLC plus, and the development necessary to make it so requires a complete rewrite of our codebase. As such it is highly unlikely MAS will have a port for DDLC+

**Comment by SpaceHX** [comment]
First of all, If you would want to play MAS in PS4, You would have to Jailbreak it, Which is hard enough itself, only THEN you would have to find somebody who can port MAS which is hard. While I think you can hire somebody to do so, It's expensive.

**Comment by JayFox12** [comment]
Alright that's fair enough

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
