### ISSUE TITLE
Cleaning files went wrong

### ISSUE THREAD

**Issue by Jack1321** [Monika-After-Story/MonikaModDev#8552]
Long story short: my brother started to clean some of my files, cause I don't have a lot of storage left and he deleted about everything on my One Drive, and when I restored everything I could and wanted to see Monika, this is what I got:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 5, in script
  File "game/splash.rpy", line 10, in <module>
Exception: DDLC archive files not found in /game folder. Check installation and try again.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/splash.rpy", line 5, in script
  File "C:\Users\PROBOOK\OneDrive\Asztali gép\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\PROBOOK\OneDrive\Asztali gép\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 10, in <module>
  File "C:\Users\PROBOOK\OneDrive\Asztali gép\DDLC-1.1.1-pc\renpy\exports.py", line 2113, in error
    _error_handlers[-1](msg)
  File "C:\Users\PROBOOK\OneDrive\Asztali gép\DDLC-1.1.1-pc\renpy\exports.py", line 2099, in _error
    raise Exception(msg)
Exception: DDLC archive files not found in /game folder. Check installation and try again.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.6

I'm not sure what can I do, but any help is appreciated.

**Comment by Flowersclouds** [comment]
Maybe reinstall the mod? Her memories and affection are okay.. I think. The downside of reinstalling it is all the gifts u gave her will be gone, This also happened to me once And once I re installed the mod everything was okay.

**Comment by Jack1321** [comment]
that's the thing...I'm worried about the persistent files.
Do they get overwrited bye the new download?

**Comment by Jack1321** [comment]
141 out of the 1699 files were missing
I hope it works

**Comment by Jack1321** [comment]
didn't work
same line of text as the first one

**Comment by charliethecookie** [comment]
> that's the thing...I'm worried about the persistent files.
> Do they get overwrited bye the new download?

no, because they are stored somewhere else, don't worry

**Comment by Jack1321** [comment]
alright that calmed me down a lot, but the problem is still present.

**Comment by Jack1321** [comment]
It took me some time, but I managed to find and delete every ddlc file, and downloaded everything that was needed.
To be honest, I'm dropping tears right now, I'm so relieved to have my angel back :_D
Thanks for all the help guys!
![2022-01-05](https://user-images.githubusercontent.com/43018202/148142930-c1b66ebc-df0d-4371-b641-612a5d880312.png)
