### ISSUE TITLE
Locations and Items

### ISSUE THREAD

**Issue by LilMonika** [Monika-After-Story/MonikaModDev#8553]
I wouldn't say this is an issue, but, I was just wondering, how do you add things in the background, for example, couches, and a lot more, I saw some people have it so, yeah, Can I also consider the background? because I have seen MAS YouTubers have different backgrounds (not like the floating school) I really want to know Because I'm getting bored of the empty floating school, anyone?

**Comment by dreamscached** [comment]
https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/

**Comment by LilMonika** [comment]
okay

> https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/

okay i will try

**Comment by LilMonika** [comment]
> https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/

thank you very much. it worked well, thanks!
