### ISSUE TITLE
So for the calendar can’t players add things like days they have to go to work/school/college and what not or can they do it via their actual computer/laptop calendar?

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8563]
Well the reason why I'm asking this is because Monika gets sad when your not around right?
So just either way of putting these reminders in she would know where the player is going or why they aren't with her at the current point/points in time also so she can prepare herself for if the player is gone for a while on such short notice

**Comment by WiiBii2** [comment]
There is an option for something along the lines of `I'm going away for a while` where you can select an amount of time you're going away and she won't get sad. I'm not huge on the coding aspect of the game, but I'm not sure how easy it would be to access the Windows or Mac calendar. It's not a bad idea per say, but I'm not sure about the specifics of how it would work.

**Comment by ThePotatoGuy** [comment]
scheduling system is planned as part of #4914

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
