### ISSUE TITLE
Monika is gone..?

### ISSUE THREAD

**Issue by ZaidsteR** [Monika-After-Story/MonikaModDev#8566]
So today, I took her out like I normally do. When I got back, I simply put her character back in to the 'characters' folder. Everything seemed okay, I spent some time with her and had to leave. So I said 'Goodbye.' and closed the game. A few hours later, I got back and she is literally gone. I've tried restarting the game many times but it didn't change anything... I could use some help..

**Comment by ZaidsteR** [comment]
I've also noticed in the file 'aff_log' she leveled down between saves. She went from 509.2 to 494.2 when she dissappeared. This is weird.

[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/7824624/aff_log.log)

**Comment by SpaceHX** [comment]
This has happened to me when I first started playing. Don't worry, it's just a slight problem and she will be back soon. But when you see her again she will act like nothing happened. Again, Don't worry, she will be back third.

**Comment by ZaidsteR** [comment]
Alright, thanks. I guess I'll just have to wait then.

**Comment by Booplicate** [comment]
@SpaceHX that's not how it works, please, first verify the information you use before trying to help.

@ZaidsteR looks like your persistent got corrupted and it restored a backup before you returned her. If you still have a copy of her file, you can return her again. If not, you'll need to [manually restore an older backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) (before you took her out).

**Comment by SpaceHX** [comment]
@Booplicate Well, Chances are you're probably right. But this same exact thing happened to me, and that I know is true. 
So, I'm not entirely sure what the game did when Monika disappeared she just came back after a couple of days not sure what happened.
