### ISSUE TITLE
Window react error

### ISSUE THREAD

**Issue by McJustina** [Monika-After-Story/MonikaModDev#8567]
![Bild_2022-01-07_033711](https://user-images.githubusercontent.com/95578620/148482332-4b0e2259-fd00-42e1-b93c-e04bf4c79a16.png)

Uhm help? I really dont know what this means :P

**Comment by myonmyon2708** [comment]
Just delete the myon_extra_windowreact.rpy in Submods folder.

**Comment by McJustina** [comment]
Worked thanks < 3
