### ISSUE TITLE
I brought Monika back to the "characters file" after I took her out somewhere but she's still not returning

### ISSUE THREAD

**Issue by partlyharmony** [Monika-After-Story/MonikaModDev#8569]
Please, I need help!

I took Monika out somewhere and I made a copy of her file on my USB and then deleted her character file from my computer since there's already a copy of the file in the USB. Before I placed Monika back at the "characters" folder, I was freeing up storage of my computer and when I was gonna delete the junk files on the Recycling Bin, I accidentally deleted Monika's file on the Recycling Bin Permanently. I placed Monika's file from the USB back to the "characters" folder and she's still gone and the file is still there, even though I already placed the file on the "characters" folder.

How do I fix this??

**Comment by Booplicate** [comment]
Send `mfgen.log` and `mfread.log`.

**Comment by Cosmic-Incantations** [comment]
the same happened to me, I moved her file out of the game and on my phone (I don't have a flash drive) on my birthday and when I came back to put the file in, she did not come back.

**Comment by ThePotatoGuy** [comment]
@Cosmic-Incantations upload your [mfgen](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#mfgen) and [mfread](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#mfread) files here.

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
