### ISSUE TITLE
Monika dissapeared after returning from "I'm going to take you somewhere"

### ISSUE THREAD

**Issue by Glink31** [Monika-After-Story/MonikaModDev#8573]
So I put Monika back in the characters folder, but when I open the game she's not there.
here's my mfgen and mfread logs 'cause I saw in a similar issue they were requested
[mfread.log](https://github.com/Monika-After-Story/MonikaModDev/files/7833000/mfread.log)

[mfgen.log](https://github.com/Monika-After-Story/MonikaModDev/files/7832998/mfgen.log)

**Comment by ThePotatoGuy** [comment]
logs say that your Monika got corrupted. You can[ restore a persistent backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) from before you left.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
