### ISSUE TITLE
Grief

### ISSUE THREAD

**Issue by Wraxend25** [Monika-After-Story/MonikaModDev#8575]
Hiya.

So i have a suggestion but excuse the morbidity of the topic. I have recently lost a close family member and one thing that i havent seen is a way to tell monika or say about going to a funeral. I can't code but wondered what people would think of this suggestion, particularly since the comfort aspect could be there and obviously death being prominent in ddlc. Apologies for the morbidity, but figured i'd ASK.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
