### ISSUE TITLE
The option to say "Can you change your hairstyle?" disappeared 

### ISSUE THREAD

**Issue by dontleavesayorihanging** [Monika-After-Story/MonikaModDev#8587]
Today I noticed that the option to ask Monika to change her hairstyle disappeared. I don't know why. 
It seems that now the only way I can make her change hairstyles is by the outfit mode, but I really don't know how to fix this. I already tried to restart, but nothing. Any ideas?

**Comment by charliethecookie** [comment]
How much affection do you have? If she's upset she won't let you change her hairstyle anymore

**Comment by dontleavesayorihanging** [comment]
502, so I don't think the problem is caused by this

**Comment by charliethecookie** [comment]
> 502, so I don't think the problem is caused by this

well i'm not sure what happened then

**Comment by ThePotatoGuy** [comment]
can you upload your persistent file here?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
