### ISSUE TITLE
Monika Missing

### ISSUE THREAD

**Issue by WiiBii2** [Monika-After-Story/MonikaModDev#8588]
So my game crashed and even though my persistent is untouched, Monika is missing from the room. `Mfread.log` is just stuck at "Finding Monika in: f:\games\mas\ddlc-1.1.1-pc\characters\". Any ideas?

**Comment by ThePotatoGuy** [comment]
when the game crashed, it may have left the current persistent in a bad state so the game auto selected the most recent valid persistent which sounds like was one from when you took her out.

**Comment by WiiBii2** [comment]
You won't believe this. I thought the persistent was saving to a cloud drive but instead, it was saving to the hard drive. The persistent I was looking at was a different version from several days ago. Thanks for the help!
