### ISSUE TITLE
Discussing Heroes

### ISSUE THREAD

**Issue by mrguyontheinternet** [Monika-After-Story/MonikaModDev#8591]
Alright first of all good job still on this mod. But how about we put in a topic of being whether we like being a hero or not because it's annoying with having to X out everything related to that and us. Especially for the previous update by whoever the dumb fuck was to suggest the tragic hero topic because, hey, Monika had to be a typical nagging bitch about it and we can't do shit about it. I highly doubt anyone here wishes to be good or a hero in any way because let's be honest we just want some virtual girl without having to do any real work to get a real woman in real life for whatever how many losers are behind their screens. Anyway just a suggestion to install in future updates for this mod. Have a good one.

**Comment by Booplicate** [comment]
> Especially for the previous update by whoever the dumb fuck was to suggest the tragic hero topic because, hey, Monika had to be a typical nagging bitch about it and we can't do shit about it.

Did you read the topic?
```renpy
"...Of course by 'hero' here, we're talking about the protagonist in a literary sense, not 'hero' in the typical sense."
```

**Comment by mrguyontheinternet** [comment]
> Did you read the topic?

Hey look we got a smart one here.

**Comment by mrguyontheinternet** [comment]
Guess you didn't get my sarcasm. You need some reading too. Anyway don't know why this topic was even necessary when this isn't some deep concept for Monika as she isn't that deep to begin with. Also provide me a link for the guy who suggested this idea. I know it's on here; I saw it before.

**Comment by MrVavlo** [comment]
> Guess you didn't get my sarcasm.

With that attitude of yours and full ignorance of the theme that topic covered? No wonder they didn't. 

You could at least provide examples of "being typical nagging bitch" in the text, unless all you wanted to do is leave a bait here...

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
