### ISSUE TITLE
Default gifts not recognized in spj.log

### ISSUE THREAD

**Issue by Ennaby42** [Monika-After-Story/MonikaModDev#8595]
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7847891/spj.log)
the game isn't even logging some of the default gifts like the bracelet or flower crown. some things work but others don't and it's very frustrating.

**Comment by multimokia** [comment]
Stock gifts aren't logged because they're initialized by code. The spj.log is to assist in diagnosing issues with _spritepacks_, stock gifts won't have the issues spritepacks do.

That said, bracelet or flower crown or necklace _aren't_ gifts.
