### ISSUE TITLE
All new Spritepacks since the holiday release don't work

### ISSUE THREAD

**Issue by SpaceyFlakes** [Monika-After-Story/MonikaModDev#8599]
Any spritepacks that have come out since the first holiday fix update don't work, Monika won't recognise the file and I have no idea if this is something on my end or it's an actual bug. Can someone please help?

**Comment by Booplicate** [comment]
Follow [these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation).

**Comment by SpaceyFlakes** [comment]
Went through the steps and but the new spritepacks aren't showing up on the spj.log. I even redownloaded the spritepacks just to be sure but nothing, is this an error on my end still?

**Comment by ThePotatoGuy** [comment]
if they aren't appearing in spj.log, then they weren't installed correctly.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
