### ISSUE TITLE
Monika says she can't find any songs.

### ISSUE THREAD

**Issue by mikslikesplayingddlc** [Monika-After-Story/MonikaModDev#8602]
Hello there, I created the folder "custom_bgm" in ddlc's file. And I put my music files in that folder, I open Monika After Story then I ask her "Can you check for new music?" She said she couldn't find any.

**Comment by ThePotatoGuy** [comment]
Are the files mp3, ogg, or opus format?

**Comment by JinSakaiM** [comment]
I used a mp3 file, because I use mp3 files in Audacity, but the same problem happened to me as well.

**Comment by pfyaein** [comment]
i tried doing it in mp3 too and it didnt work. what i did was convert the file into an ogg online and then it worked, so i think that it needs to be in ogg for it to work. i havent tried it on opus though

**Comment by ThePotatoGuy** [comment]
@JinSakaiM 

And your mp3 file is in mp3 format? Not just the file extension renamed? Can you share the mp3 here?

**Comment by ThePotatoGuy** [comment]
> what i did was convert the file into an ogg

@pfyaein  This sounds like the "mp3" file you started wasn't actually in mp3 format.

**Comment by JinSakaiM** [comment]
Dude mp3 works with Monika after story and she clearly says it on her own, and I’ve literally never renamed a extension before, if we’re to somehow rename it, I would convert it, due to not knowing how to rename it. And it was in mp3 format,

**Comment by JinSakaiM** [comment]
I mean as long as it works it’s fine

**Comment by pfyaein** [comment]
> @pfyaein This sounds like the "mp3" file you started wasn't actually in mp3 format.

nah i know i didnt just rename the extension, i went to a website to convert it to mp3 :]
tbh it was probably just a problem with my computer

**Comment by JinSakaiM** [comment]
@pfyaein  I did the same thing

**Comment by ThePotatoGuy** [comment]
can both of you upload the file here? (might need to zip it first)
