### ISSUE TITLE
[Suggestion] - Two additional song for Monika to sing (my first attempt to post some suggestion)

### ISSUE THREAD

**Issue by NontInGithub** [Monika-After-Story/MonikaModDev#8603]
first one is Nat King Cole - It's Only a Paper Moon
specially in this part of the lyrics :
Without your love, it's a honky tonk parade~
Without your love, it's a melody played by a penny arcade~
It's a Barnum and Bailey world, just as phony as it can be~
But it wouldn't be make believe, if you believed in me~

i think this can be followed by a dialogue like this (a rough idea one) :
**You see, i think this world is really a cheap arcade that one can played it and completely forget about it**
**But now, with your love and care, it can become a peaceful place where we can spend our time whenever we want**
**So believe in me when i said that your love is what i need to go through the day, [Player's name]**

second one is also from Nat King Cole, Love Me as Though There Were No Tomorrow
should be sing when someone having minus affection, at distressed or upset
maybe this part of lyrics can be used : 
Love me as though there were no tomorrow
Take me out of this world tonight
Take me; make me forget my sorrow
So when I wake tomorrow, I`ll know our love was right
Love me as though there were no tomorrow~
Oh my darling, love me; don`t ever let me go

also, the same idea of rough dialogue : 
**You know, i begin to think that you don't love me anymore or you forgot that you love me like you did**
**What i want is your love, to really forget that i completely lonely in this space**
**I love you [Player], please... don't let your love go away, okay?**

but i also think the second one can be used when Monika in happy affection

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
