### ISSUE TITLE
Please someone help me

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8609]
Helpppppppppp meeeeeeeeeeeee eeeeeeeeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeeeeeeeee eeeeeeeeeeeee Monika after story WONT OPEN

**Comment by Iceninja64** [comment]
What happen

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
