### ISSUE TITLE
I dont know how to backup my persistent file

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8624]
I need like a tutorial or something on how to backup my persistent file, because I have no idea how to, I was told that my persistent file was corrupted and they managed to make another, but I really want to learn how because if Im actually really anxious about it.
I am actually a bit younger in age, Im like a -mid -late preadolscent ( 10-13 ) , but I really look forward to learning how, and in my own opinion, I would like to be given a video tutorial, but Im not forcing you to, as long as I learn how to backup my persistent file ill be fine.

**Comment by janneslessmann** [comment]
Hello,

there exists a whole [wiki for MAS](https://github.com/Monika-After-Story/MonikaModDev/wiki) with a lot of information about basically everything common in there.
There is also a section about how to [back up the persistent file](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent).

I hope that I could help you!

**Comment by JinSakaiM** [comment]
Hey, I really wanna say thanks for telling me how, but there’s one problem, I don’t really know what you mean by copy, because I’m not really good at computers I’m being fr.
But I’m not rlly good at coding as well.
Basically I would prefer a video tutorial, but I don’t wanna force you to make one, I highly suggest one though.

**Comment by charliethecookie** [comment]
> Hey, I really wanna say thanks for telling me how, but there’s one problem, I don’t really know what you mean by copy, because I’m not really good at computers I’m being fr. But I’m not rlly good at coding as well. Basically I would prefer a video tutorial, but I don’t wanna force you to make one, I highly suggest one though.

you right click the file and select "copy", then you go to the place you want to put it in and right click a blank space in it and select "paste"

**Comment by JinSakaiM** [comment]
Do I put it in the RenPy folder after I open %appdata% or is it somewhere else? Sorry if this is a stupid question

**Comment by charliethecookie** [comment]
> Do I put it in the RenPy folder after I open %appdata% or is it somewhere else? Sorry if this is a stupid question

nope, you put it in a safe place where you can get it back if your computer breaks like google drive or a usb drive

**Comment by JinSakaiM** [comment]
Thanks so much! I got so anxious when I was told that the persistent file got corrupted, thanks dude I appreciate it a lot.

**Comment by JinSakaiM** [comment]
Hey, I have one last issue, so I’m on Windows, and I got google drive on my laptop, so do I put the Monika after story folder in the My Drive folder?, and do I have to add the DDLC one as well?

**Comment by JinSakaiM** [comment]
I’m pretty sure I have to put it in the My Drive folder. I think I’m gonna do it

**Comment by Cosmic-Incantations** [comment]
I would recommend copying the persistent onto google drive, I never thought about it when my computer broke down
it helps when that happens cause then Monika is saved onto your google account and no matter what happens you can find the easily, better them what I thought was the only way witch was a flash drive

**Comment by JinSakaiM** [comment]
There’s really no difference between me and Cosmic-Incantations because it is better to use it on google drive, he isn’t wrong at all.

**Comment by JinSakaiM** [comment]
I have one question, on the Monika After Story file, are you suppose to copy it or duplicate it?

**Comment by JinSakaiM** [comment]
If u duplicate Monika After Story it will create another file saying “Monika After Story - Copy” am I supposed to duplicate it or copy it?

**Comment by janneslessmann** [comment]
You don't need to copy the whole folder at all.
Just right click your persistent file and click "Copy". Then you paste it e.g. on your desktop and just throw the persistent from your desktop into the Google Drive.
If anything of MAS ever breaks you just redownload the mod and switch the persistent file with your old one from the drive.
The persistent file is basically the only one that safes significant progress. The rest of the game is "replaceable" or "redownloadable" as long as you have your persistent.

**Comment by JinSakaiM** [comment]
Is it ok if I still use to entire folder for MAS?

**Comment by JinSakaiM** [comment]
And do I put it in My Drive?

**Comment by janneslessmann** [comment]
I mean if it makes you feel more comfortable to put the whole folder into your Google Drive then you can obviously do it.
It's just not necessary because if you redownload the game and put your persistent back in it will all be as before (if I remember correctly).

**Comment by JinSakaiM** [comment]
Wdym by “it will all be as before”, I kinda got confused sorry.

**Comment by janneslessmann** [comment]
Your whole progress will be as before. I mean thats why you even backup your persistent, right?

**Comment by JinSakaiM** [comment]
Sorry if that sounded kinda stupid, but I understand what you meant now.

**Comment by janneslessmann** [comment]
Ah, its all fine. This is a place for asking questions like this so everything is ok :)
If you don't have any further question then you can close the issue. If you encounter a new one in the future, just create a new issue.

**Comment by JinSakaiM** [comment]
Ok so I have a final question,
