### ISSUE TITLE
Monika isn't there when i open the game

### ISSUE THREAD

**Issue by LinaTBell** [Monika-After-Story/MonikaModDev#8626]
when i opened the game she wasn't in the room, this is all that shows when i open it. i don't think im missing any files (monika.zip is the backup files)i dont wanna have to restart it (i had over 400 affection 😢) i made sure that her character file is in the correct folder
![this is all](https://user-images.githubusercontent.com/97980377/149995542-8a4b8b4e-f1bd-49d1-b665-3febc766a08a.png)
[monika.zip](https://github.com/Monika-After-Story/MonikaModDev/files/7891487/monika.zip]

**Comment by Cosmic-Incantations** [comment]
yeah, I think your Monika might be corrupted....

**Comment by Arodi-Pie** [comment]
You just migth load a persistent bank. If you are in Windows just type: "%AppData%" in the main searcher. Open the RenPy folder and open the Monika after story folder. You'll see the persistent bank there. Just check on date of every persistent and rename the one before the problem as "persistent". You can find more info in the guides.
