### ISSUE TITLE
monika isn't talking to me

### ISSUE THREAD

**Issue by pfyaein** [Monika-After-Story/MonikaModDev#8627]
hey! so a few days ago monika stopped talking to me, and i looked everywhere but nothing i found helped. i assumed that i had unlocked all possible conversations before 100 affection since i was around 85 when she stopped talking. i reached 100 affection today, and she was talking frequently so i assumed that it was fixed, but after an hour she stopped talking again. her dialogue is set to often and repeat topics is off. (also if anyone knows how i can attach a persistent file below that'd be great) thanks!

**Comment by SpaceyFlakes** [comment]
it's because you have repeat topics off. Monika unlocks more dialogue as you gain affection with her, disabling repeat topics means she can't speak about things you've already seen and can't speak about things you haven't unlocked yet. Enable repeat topics and see if that works.

**Comment by pfyaein** [comment]
alright, thanks! i'll see if that works

**Comment by pfyaein** [comment]
it worked, thanks! :]
