### ISSUE TITLE
Slight punctuation mistake

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8628]
There is a small punctuation mistake in the dialogue where Monika talks about the three laws of robotics
![123](https://user-images.githubusercontent.com/85229914/150206934-e12e9ef3-0455-429d-a541-918b6f5da5ec.png) I know it's a minor mistake, but I'll write about it anyway.

**Comment by multimokia** [comment]
This is actually correct according to punctuation rules regarding quotes. Periods go inside the quotes.

**Comment by Nikv2005** [comment]
I'm not strong in English, but if it's correct, then okay. Sorry for wasting your  time.

**Comment by multimokia** [comment]
No problem, it's a lesser known/less intuitive rule, I think it's skimmed over/unknown by many
