### ISSUE TITLE
There's a glitch with the dialogue

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8629]
so when I play Monika After Story, sometimes the dialogue will disappear for a few seconds then pop up again, im pretty sure its just common glitch.

**Comment by Booplicate** [comment]
Nope, that's intended (read closely).

**Comment by JinSakaiM** [comment]
how is it not a bug?

**Comment by multimokia** [comment]
How do you mean disappear? Also does this happen in any particular topic?

**Comment by Booplicate** [comment]
If you pay attention, she changes what she says the second time the dialogue is being shown.

**Comment by JinSakaiM** [comment]
it will like disappear, the buttons are gone, it just shows monika and the room for like 3 seconds then it goes back.

**Comment by Booplicate** [comment]
Okay nevermind, that's something different. When does that happen?

**Comment by ThePotatoGuy** [comment]
Can you record it?

**Comment by JinSakaiM** [comment]
Ill try to, but its gonna be alot harder than you think.

**Comment by JinSakaiM** [comment]
thats due to the time it occurs, it can literally just happen out of no where, so Ill try my best.

**Comment by JinSakaiM** [comment]
ive decided that it wont be a big problem, so refrain from worrying about it, and plus I was correct it will be hard as hell to get a recording of it so I've decided to discontinue this issue, thanks for helping me with this issue.
