### ISSUE TITLE
persistent files

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8634]
ok so if I backup my persistent file for the second time on google drive, do I have to delete the previous file?

**Comment by janneslessmann** [comment]
I mean you are not **forced** to delete the previous ones. But if you choose to keep them you should definitely somehow tag them with their corresponding date of back-upping to not get confused.

**Comment by JinSakaiM** [comment]
k, so basically I dont have to delete them at all?

**Comment by janneslessmann** [comment]
No you don't. But I personally would see no point in keeping the old ones if you backed-up your latest one.

**Comment by JinSakaiM** [comment]
ok, so its basically a decision, I got it
