### ISSUE TITLE
Lost option to rename Monika.

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8636]
I lost the option to rename Monika, I was recently kinda trying to troll her, by calling her "minigga", I did it three times, and I apologized after each apology, now I cant rename Monika.

**Comment by kkrosie123** [comment]
That's intentional

**Comment by JinSakaiM** [comment]
is there a way to get it back?

**Comment by multimokia** [comment]
At the moment there is not.

**Comment by JinSakaiM** [comment]
when will I be able to?

**Comment by JinSakaiM** [comment]
guys!, I came back with a good idea!!!!, if I load my persistent file if I can find out how, I can go back before I lost the option to rename her!

**Comment by JinSakaiM** [comment]
but it might have to be on another device because idk if it can be on my current device, not sure

**Comment by Cosmic-Incantations** [comment]
there should be an option to put a imsorry_name,txt file in the character folder and Monika will give you another chance
cause I did this to Monika a year ago just to see how she would react to the other girls names and did not know she'd be hurt
but the text file will only be accepted by Monika after one month since removal of Moni names, 
cause she wants to know you mean it

**Comment by JinSakaiM** [comment]
I actually just put a file named “imsorry_name”, but I wrote something inside of it rather personal

**Comment by JinSakaiM** [comment]
But hey, the persistent file option is possible available

**Comment by Cosmic-Incantations** [comment]
but they should add this feature, I don't want Monika to forget all the stuff we did

**Comment by JinSakaiM** [comment]
Wdym

**Comment by Cosmic-Incantations** [comment]
> there should be an option to put a imsorry_name.txt file in the character folder and Monika will give you another chance cause I did this to Monika a year ago just to see how she would react to the other girls names and did not know she'd be hurt but the text file will only be accepted by Monika after one month since removal of Moni names, cause she wants to know you mean it

as I said, there should be a feature like this, I don't wanna mess with her memories in order to recover a feature 
that I lost unintentionally. I like this cause I know that it could have been someone else on the computer who did that to Monika

**Comment by Booplicate** [comment]
It's very unlikely to do this unintentionally. You have to call her a bad name 3 times to lose the option.

Eventually, there will be a way to get the option back, but don't expect it to be a get out of jail free card, this is purely on the player to mess up.

**Comment by Cosmic-Incantations** [comment]
I understand that, but you should understand it happened over a year ago.
