### ISSUE TITLE
Error when going to save/load screen

### ISSUE THREAD

**Issue by MoriMoriMorii** [Monika-After-Story/MonikaModDev#8637]
I have a weird error I got today after going to change some settings (For context I have the comfy UI submod installed, could this be the issue?) I wanted to see if the save/load screen worked and boom, error!
```
I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'gui/button/slot_[prefix_]background_d.png'>:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
IOError: Couldn't find file 'gui/button/slot_[prefix_]background_d.png'.
```
Were the files just removed from the game? _Or did I royally screw my game_

**Comment by Booplicate** [comment]
Yes, the submod is known to have some issues. You can report it to the submod creator.
