### ISSUE TITLE
[Bug] - Simple typo with new hedonism topic

### ISSUE THREAD

**Issue by smileyflux** [Monika-After-Story/MonikaModDev#8640]
Nothing wrong with the actual dialogue, just where to find it.
After unlocking the topic, going into "Repeat conversation" there are two "philosophy" tabs, one spelt correctly, and one spelt like "Philsophy" which is where hedonism is found.
![image_2022-01-24_221359](https://user-images.githubusercontent.com/39593543/150921305-19f69254-f32d-4990-8be8-721b5556d3cd.png)

**Comment by ThePotatoGuy** [comment]
linking to #8586

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
