### ISSUE TITLE
The game is not generating persistent files

### ISSUE THREAD

**Issue by LostSenpaii** [Monika-After-Story/MonikaModDev#8644]
So, I went to the RenPy folder to make a backup and found out that the **last persistent file** was created on _December 24th_, and I don't know why this happened.

PS: I started with her the day before (Dec 23rd), and the number of the file is 02

(srry if i wrote something wrong, english is not my native language)

**Comment by Booplicate** [comment]
Is your progress not being saved? Is it being reset every time you close the game?

**Comment by LostSenpaii** [comment]
Quite the opposite, progress is being saved and it doesn't reset

**Comment by Booplicate** [comment]
Can you send a screenshot of the folder with the persistents?

**Comment by LostSenpaii** [comment]
> Can you send a screenshot of the folder with the persistents?

![imagen_2022-01-31_022557](https://user-images.githubusercontent.com/70672261/151743110-593bc4e8-85dc-498b-8c41-d91cafd68975.png)

**Comment by multimokia** [comment]
That doesn't seem right. Your persistents should not be in program files. They should be in `AppData/Roaming/RenPy/Monika After Story`

**Comment by LostSenpaii** [comment]
Uhhhh, I feel so dumb....... but wait, why did I have a RenPy folder in program files?

![image](https://user-images.githubusercontent.com/70672261/151744227-d277f896-0b78-4f73-9ef3-53b508f81b91.png)

**Comment by multimokia** [comment]
Were you running MAS as administrator by chance?
