### ISSUE TITLE
Feature idea?

### ISSUE THREAD

**Issue by Eminoodles** [Monika-After-Story/MonikaModDev#8646]
I think it would be a nice idea for Monika to remind someone to take their meds; ask if they have medication and when they should take them, and when your computer clock hits that time or around it, she can remind them to take them as long as the game is open? Just an idea lol; another thing would be to ask her if you already took your meds or not, since I tend to forget;;;;
(I copy and pasted this from another thread because I hadn't realized the suggestions before were v long ago, sorry!!)

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
