### ISSUE TITLE
UX enhancement proposal — appearance changing topics to show talk submenu upon completion

### ISSUE THREAD

**Issue by dreamscached** [Monika-After-Story/MonikaModDev#8647]
If one wants to change multiple parts of Monika's appearance, they will have to click on 'Hey, Monika... > Appearance' multiple times. I believe it would improve the user experience if any of these appearance topics returned 'Appearance' subsection back into player's view upon their completion.

**Comment by Booplicate** [comment]
We planned to refactor this system into a more use-friendly system. Perhaps using a delegate topic (stories alike) to push appropriate appearance topics.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
