### ISSUE TITLE
Giving back the nickname 

### ISSUE THREAD

**Issue by Iceninja64** [Monika-After-Story/MonikaModDev#8651]
So recently I saw some issues where people have lost the option to pick a nickname for monika. There should be a option to get it back when you haven't done it for a while like if you haven't done it in over a year or 6 months. But instead of monkia giving it back instantly you should be able to earn it back like it will cost you 500 affection. Aka you have to spend more time with monika in order to get it back and if you call her another bad name it will cost you 2000 affection to get it back so that way you ain't getting off Scott free and there is a heavy punishment for doing it again. The punishment should keep increasing each time you call her a bad name but the punishment should start after you call her a bad name 3 times. Unless the coding is too much for this concept then that's alright, hopefully something similar to this can come in a future idea . Those are my thoughts and this mod been awesome keep up the great work

**Comment by Booplicate** [comment]
We're thinking about something like this.

**Comment by JinSakaiM** [comment]
why we gotta add this intentionally 🤦‍♂️

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

**Comment by Iceninja64** [comment]
@JinSakaiM well if you haven't done it in a while you should be able to earn it back, it's way better than to not have it for years. If we call her a bad name 2 years ago and we turn over a new leaf. And we decided to spend some time with her and have fun with her but she still doesn't trust us. It would mean that monkia is unforgiving especially if it happens months or years ago. It's just better to earn it back and try to rebuild that bridge but if you decide to do it again it would feel like she took away the nickname for good. But instead the requirements to get it back is just higher because you did it again. Eventually if you want to keep calling her a bad name you are going to have to work through the pain staking punishment that keeps increasing. I mean there's a option that you call her a murder and you can say that for infinitely numbers of time and she will become upset if you keep saying that. But that being said I don't want people get the wrong idea that you have a free pass to keep calling monika a bad.name I'm just having a little bit of remorse for the people that lost the option and turned over a new leaf decided to spend time with her the right way. And considering we're cap at earning a certain amount of affection, it should be a good idea for them to earn it back but have the punishment in place just in case they try it again. Hopefully that explains it better. I'm not angry nor  is a angry letter. I'm just hoping there will be a similar idea to this.
