### ISSUE TITLE
Suggestion - monika waking up after falling asleep

### ISSUE THREAD

**Issue by mayday-mayjay** [Monika-After-Story/MonikaModDev#8652]
when monika falls asleep when being held, there should be a random chance after a while for her to wake back up in a similar way she does when the player wakes her up normally, the difference is that she could ask to keep being held after waking up on her own

**Comment by CloudedGuardian** [comment]
That could be super cute... I would love to see something like that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
