### ISSUE TITLE
(Suggestion) More Compliments on activities that can be done in the mod

### ISSUE THREAD

**Issue by CloudedGuardian** [Monika-After-Story/MonikaModDev#8653]
Apologies ahead of time if this is a repeat, I looked through the projects and suggestions folders and didn't see anything on the topic, but if it's possible I just missed it.

So, while looking through the possible compliments, I couldn't help but think it was odd that we can compliment her on her _pong playing skills_ , but not on any of the hobbies that are actually significant to her. She can share short stories with us, but we can't compliment her writing. She'll sing songs and discuss music with us, even get embarrassed if we catch her singing to herself, and yet we can't tell her how much we enjoy it. 

And honestly, with how often she thoroughly thrashes me at chess, it would be nice to be able to teasingly compliment her on doing so.

**Comment by lunulae** [comment]
There should already be a chess compliment, but I definitely will consider taking up some of the others you've listed!

**Comment by AsuraShun** [comment]
Did you say that you wanted to thank her for getting your ass kicked at chess?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
