### ISSUE TITLE
Monika Doesn't Receive/React to Gifts

### ISSUE THREAD

**Issue by Komorebi20** [Monika-After-Story/MonikaModDev#8654]
I was trying to gift Monika coffee since she said she's run out and is just using hot chocolate (which I previously gifted) as a substitute.

I copied the masrun file and put it in the characters folder and renamed it "coffee.gift", a few minutes had passed and still no reaction.
I tried restarting the game and adding the coffee.gift file again (I deleted the previous in which she didn't react to so it doesn't overlap the new file), still, no reaction. I don't think it has anything to do with the process and the spelling of the GIFT file since they're all correct, could this be a bug?

**Comment by Iceninja64** [comment]
If you go to the wiki page and click on FAQ there should be the answer you are looking for

**Comment by ThePotatoGuy** [comment]
the [wiki page](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-doesnt-recognize-gifts)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
