### ISSUE TITLE
Bad name false positive ⁠— 'Familiarity' is matched by 'liar' subpattern in bad names list

### ISSUE THREAD

**Issue by dreamscached** [Monika-After-Story/MonikaModDev#8655]
Recently, a user in #tech-support Discord channel ([message](https://discord.com/channels/372766620977725441/393978515802030091/936532211946098739)) has reported an issue with Monika unable to call them 'Familiarity'.

I did a bit of a research and found out that `Familiarity` is matched by `liar` simple subfilter ([code](https://github.com/Monika-After-Story/MonikaModDev/blob/6008eff0828f6c0b4dbeec0c19124bd2d0911be3/Monika%20After%20Story/game/script-story-events.rpy#L309)).

I'll make a PR for it if this issue isn't reported yet.

**Comment by dreamscached** [comment]
P.S. Quickly glancing at the pattern list I noticed `Skilled ` also results in false positive and is matched by `kill` subpattern as well.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
