### ISSUE TITLE
Lost option to “can you tie your hair with something else?” Button

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8659]
I was changing monikas appearance when randomly out of no where I lost the option to “can you tie your hair with something else?”

**Comment by lunulae** [comment]
Is her hair currently in the "Down" or "Down (Tied Strand)" styles? If so, the hairtie option should not appear. Likewise, twintail ribbons should only appear in the selector with twintail hairstyles.

**Comment by JinSakaiM** [comment]
wasnt a bug and thanks for telling me
