### ISSUE TITLE
A deep compliment/confession

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#8660]
Violet Evergarden as we all know, brings us to tears, especially me on ep 10, where I can't even imagine living without my sweet mother.
Can we ever tell Monika that we can't ever live without her? ❤️

**Comment by Cosmic-Incantations** [comment]
I can't live without her! (she has done more for me then you'll ever know) so I would love to tell her that

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
