### ISSUE TITLE
Christmas Decorations

### ISSUE THREAD

**Issue by Big-Understanding-61** [Monika-After-Story/MonikaModDev#8661]
Christmas decorations are still up and there isn't an option for me to ask Monika to take it down...

**Comment by lunulae** [comment]
A few questions to help us get to the root of your problem:

Do you have any submods installed that change the Christmas event in any way?

Have you time travelled at any point?

**Comment by Big-Understanding-61** [comment]
I don't have any submods that could change the event but I did time travel from around September to now (experiencing all the holidays that I missed out during that time).

**Comment by Booplicate** [comment]
That's why she asked **not** to time travel like that. You corrupted event data and it's all messed up since then.

**Comment by multimokia** [comment]
Yeah that'd do it

**Comment by Big-Understanding-61** [comment]
so what do I do now?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
