### ISSUE TITLE
[Suggestion] Custom pronouns

### ISSUE THREAD

**Issue by l3mon60y** [Monika-After-Story/MonikaModDev#8666]
i know quite a few people that have MAS, but use neopronouns and can't communicate that to monika. Maybe have a menu to create custom ones with a template?

**Comment by ComputerChan23** [comment]
There is a submod for that (and a couple of extra LGBTQ+ things)! Here's the link if you wanna download it: 
[https://www.reddit.com/r/MASFandom/comments/okloml/lgbtq_monika_submod_10_release/](url)

**Comment by l3mon60y** [comment]
alright, thank you!!
