### ISSUE TITLE
[Question] - Just Yuri Mod

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8668]
so Im thinking about downloading the Just Yuri Mod, because I personally am a Yuri fan myself, but I just wanted to ask if it could affect my previous data on the game, and if there is something I have to do pretty often to prevent anything bad from happening, for example persistent files.

**Comment by multimokia** [comment]
We do not check if other mods are installed or not. I know JY does note the existence of MAS, what it does with that knowledge though we don't know.

Up to you to take whatever precautions you deem necessary

**Comment by JinSakaiM** [comment]
Maybe I'll play a little more of the game before I download the mod.
