### ISSUE TITLE
Monika Isn't making Coffee.

### ISSUE THREAD

**Issue by PanAMD** [Monika-After-Story/MonikaModDev#8669]
A couple of days ago I gifted her the cup of coffee and she did reacted to it, and said that she will make some later, but nothing has happened, so today I decided to give her the gift again, and she said something new "Its new flavor", but the cup hasn't appeared, so I wanted to know, Is it a bug? or, Is there a schedule for her to make the coffee?.
Thanks ^^.
PD: She did reacted to it, and I also was able to gift her the quetzal plushie and it did appear.

**Comment by Mosexelle** [comment]
Hello.
Monika prepare and drink coffee from 05:00 until midday. So, if you're with her outside that time range, you will not see her cup of coffee.
But the plush toy doesn't always show up, so don't worry if you don't see it next time. This is random.

**Comment by PanAMD** [comment]
Oh I see, actually I just entered and she had a cup of coffee, so its not a bug.
