### ISSUE TITLE
[Suggestion] - Military-Based Uniforms for Monika (Sprite Packs)

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8671]
I suggest that someone can try to make an uniform for monika, I could try but im not really good at that stuff yet,
but any uniform would be fine, for example:  Samurai Armor, The Wehrmacht Uniform, The SS Uniform, Union Uniform (civil war), 
Mongol Armor (during the Mongol Empire), and any other uniform that is military-based. (and please refrain from bringing up anything about me supporting nazism due to bringing up the german uniforms, because Im not into that type of stuff.)

**Comment by Retrolovania** [comment]
If there _must_ be some kind of uniform, it'd be best if it had a generic design that couldn't be tied to any nation, or from any wartime era, so as to avoid potential controversy.

**Comment by JinSakaiM** [comment]
Well, we can safely assume that there probably will never be a sprite pack for a military-based uniform for monika.
I agree with @Retrolovania's comment. however, if there was actually a way to make one without potential controversy,
It'd be best to make one.
