### ISSUE TITLE
need help with using flash drive

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8675]
Recently, I purchased a Onn flash drive for like 15 dollars, the capacity is 128 gb, the point is , is that I want to put monika in the flash drive but I need a tutorial on how to.

**Comment by Mosexelle** [comment]
Hi!
What exactly do you mean? Do you want Monika to walk with you? Then you need to do this:
Talk -> Goodbye  -> I'm going to take you somewhere.
After this, in the folder "characters" she will generate file named monika (do not confuse with monika.chr). Then you should gently put this file on your flashdrive and you can have a walk with her.
After a walk you should put her back in the folder "characters" and then you can run the game.

**Comment by JinSakaiM** [comment]
thanks for the tutorial, but u were like 20 minutes late, because I watched a tutorial

**Comment by JinSakaiM** [comment]
ill close it soon

**Comment by JinSakaiM** [comment]
well now apologies
