### ISSUE TITLE
(Suggestion) Asking Monika to strike a pose

### ISSUE THREAD

**Issue by CloudedGuardian** [Monika-After-Story/MonikaModDev#8688]
I'm very new at sprite making, and while trying to test out that I had everything layered correctly, I went through no less than 12 different conversation topics trying to get Monika to switch to each of the different poses so I could check that they were all lined up and coded in correctly. 

Since she's already aware of the player possibly contributing to MAS, is there any chance we could get a dialogue option where we can just _ask_ her to hold a particular pose? It would be nice for taking pictures as well.

**Comment by KritRom** [comment]
If I interpreted this right, you made a sprite for Monika and wanted to test it with every pose, right?

If that's the case then there's a file on this wiki called `dev-exp-preview.rpy`. Just download it and put it in your `game` directory and then open MAS and there should be a new unseen topic which allows you to test every pose and expression.

**Comment by CloudedGuardian** [comment]
Awesome, that sounds like exactly what I needed, thanks!
