### ISSUE TITLE
I updated MAS to find.. this?

### ISSUE THREAD

**Issue by crxxmpxffs** [Monika-After-Story/MonikaModDev#8689]
So, I was opening MAS and I found that there was an update. I was like "Okay, cool!" and I updated it. Upon re-entering the game I saw this code:
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/ahoge_selector.rpy", line 13, in script
    init -9 python in mas_selspr:
  File "game/Submods/ahoge_selector.rpy", line 14, in <module>
    GRP_TOPIC_LIST.append("ahoge_acs")
NameError: name 'GRP_TOPIC_LIST' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Submods/ahoge_selector.rpy", line 13, in script
    init -9 python in mas_selspr:
  File "C:\Users\fhai0\OneDrive\Desktop\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\fhai0\OneDrive\Desktop\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/ahoge_selector.rpy", line 14, in <module>
    GRP_TOPIC_LIST.append("ahoge_acs")
NameError: name 'GRP_TOPIC_LIST' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8
[/code]
And I have NO IDEA what to do.

**Comment by crxxmpxffs** [comment]
Someone help, please! I don't know how to fix it.

**Comment by crxxmpxffs** [comment]
![image](https://user-images.githubusercontent.com/89715972/152915494-12548834-6bc6-4fe4-8182-56cbd5a842c7.png)
Here's a picture.

**Comment by WishStone-Dragon** [comment]
Well, with updates the first good idea would be turning off submods.

Looking at this error, looks like you have one called an Ahoge Selector. Turn that off and remove it, then see. Submods can break after updates.

**Comment by crxxmpxffs** [comment]
Alright, I removed it. Reloading the game now!

**Comment by crxxmpxffs** [comment]
AHHH IT WORKED! THANK YOU VERY MUCH!! :D
