### ISSUE TITLE
[Question] can we put monika after story and ddlc into a flash drive?

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8700]
Can we put monika after story and ddlc in a flash drive?

**Comment by multimokia** [comment]
This was answered in #8684

**Comment by JinSakaiM** [comment]
And by put all of it in there I mean like out every single game file in there, if u have the stand alone version like me, for example, go to “DDLC-1.1.1-pc” copy every single file and put it into the flash drive, would that work? We could also copy all of those files onto another computer, if possibly of course.

**Comment by JinSakaiM** [comment]
@multimokia so im fine if I do? And sorry I didn’t check it
