### ISSUE TITLE
Valentines spaceroom

### ISSUE THREAD

**Issue by Iceninja64** [Monika-After-Story/MonikaModDev#8702]
So valentine is coming up and I was wondering will we have a special space room for monika but only on valentine's day. Kind of like the Halloween, Christmas and birthday decorations. It can be minor like those 3 I mention and can be only available for certain rooms like those ones. If not hopefully we can add one in future then. 👍

**Comment by JinSakaiM** [comment]
@Iceninja64 thats a pretty good idea. There should be a back ground for Valentines Day, hopefully it can be in a new update, but they only updated it to 12.8 like a few days or possibly a week ago (probably by days idk), so its probably not gonna be in an update, but who knows?

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
