### ISSUE TITLE
The option to switch hairstyles has disappeared.

### ISSUE THREAD

**Issue by PencilMario** [Monika-After-Story/MonikaModDev#8713]
As in this picture, the option to switch hairstyles disappeared, where did I I made a mistake？
![a](https://user-images.githubusercontent.com/72117241/153699804-b0106378-da0b-458c-9c67-838c0f1848df.jpg)

**Comment by ThePotatoGuy** [comment]
Can you upload your persistent here?

**Comment by PencilMario** [comment]
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8054796/persistent.txt)

**Comment by PencilMario** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/8054801/persistent.zip)
