### ISSUE TITLE
[Suggestion] Little sweets with sweet phrases.

### ISSUE THREAD

**Issue by Mosexelle** [Monika-After-Story/MonikaModDev#8714]
Hello everyone!
We can give Monica a box/pack of chocolates. BUT, along with each chocolate bar, there will also be a small letter with a written phrase like "Sweet is the dawn which breaks upon lovers" (William Shakespeare) or "Young love's first lesson is the heart" (Edgar Allan Poe). And she will randomly eat a chocolate bar every day and read us the "phrase of the day." Since there can be more than a hundred such phrases, this will encourage the player to visit Monica every day. Also, chocolates are running out (you can make them in a pack of 20 pieces, for example) and we will need to give them several times (here you can copy the algorithm from coffee).
Such chocolates actually exist and they are quite popular in the country where they are produced. At least that's what they told me. I don't know if I should name the company, as I don't feel like getting bases for ads, lol. There phrases are written in several languages: English, French, Italian, German. Sometimes Spanish or Portuguese instead of German. But I think that the English version is enough.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
