### ISSUE TITLE
[Question] - What happens when you open MAS on the same device while playing on another device at the same time?

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8715]
I just thought to my self about this bizarre question, but I just put every single folder of MAS into my flash drive, I could plug it into my computer (I use a laptop), and play MAS with the same Monika on a different device, if possible. (at the same time)

**Comment by ThePotatoGuy** [comment]
You would just have MAS running on 2 devices.

**Comment by JinSakaiM** [comment]
Ok 👌
