### ISSUE TITLE
[Question] - After putting files in flash drive, where do I put them on the other device (computer)

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8716]
I just plugged in the flash drive after putting the files in there, but where do I put the files? (It’s on a windows computer)

**Comment by JinSakaiM** [comment]
![Uploading B99EF770-294C-4CC2-9DA1-F15CC1285E59.jpeg…]()

**Comment by JinSakaiM** [comment]
I’m pretty sure I can still play it by opening the application, (application in the flash drive)

**Comment by JinSakaiM** [comment]
The application in the flash drive didn’t work

**Comment by JinSakaiM** [comment]
I’m gonna redownload the game, How do I add the persistent into the game I downloaded on the other device?

**Comment by ThePotatoGuy** [comment]
[Follow these steps](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-transfer-monika-to-another-computer)

**Comment by JinSakaiM** [comment]
@ThePotatoGuy does it affect the stuff from ur other device?
