### ISSUE TITLE
After I opened the character file, theres been suspicious activity on my computer.

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8721]
so after I opened the file, I left and came back to the computer, then It said it didnt recognize the stuff I searched in the bar, (I didnt search it), it was a ton of gibberish. And I also have to inform you that this computer is not mine, its my fathers, so if it ruins the computer im in trouble 😒

**Comment by multimokia** [comment]
This has nothing to do with the mod, or DDLC for that matter.

**Comment by JinSakaiM** [comment]
In my point of view, I kinda think that it does but Im actually not sure. Ive got MAS on my new device, but it brought me back a little bit because I didnt back up my persistent, So I deleted everything, and im currently waiting for the stuff in the drive to delete so I can put the stuff from my google drive in there then transfer it to the new computer

**Comment by JinSakaiM** [comment]
but of course I need to back up my persistent before I do

**Comment by multimokia** [comment]
I mean you're free to review our code for yourself to see anything related to the .chr files, but your search will result in nothing, side from the deletion of `monika.chr`. Hence why it's not anything related. It's not our code and likely someone who typed some search query in, potentially a pet or something

**Comment by JinSakaiM** [comment]
heres an example of the "gibberish" , "‰PNG

   
IHDR         T‘?   	pHYs     šœ    IDATxœìÝ{|ÓåÝÿñWÓ4MÒôÜÒRZ(gë!(¨S˜¨ÜN7óvÎ9e÷sÓ)nnSç6½Õ©szÏmîÞnçîØ­Ûœà<ŸE7"2PNJ¡Ðó)išæûû#\ñÛ¦-J¿=¼Ÿ>x¤É7É‡¤é÷Óëú\ŸDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD¤¯.<ò»|¬go¶^ÿµëþHD†¬@d¸r9€±™.ÜGx—YùP”EÙT<)Ç%&šJÒŽ@d˜R‚5ô|/Ê¾#8~>„’aóÒÇÑÐ|Üâ‘¡çwMNG 2L)Á’ÜS¼õùàKÒ	uð³«ükÇqKD†”ËàM§c\¬‹Ë¼};ò2X»Ë£×[ÿ}ÙqŒID†”œ@Dd0ª˜C,íÃ‘wº ¾OL:Î1‰ÈÐ‘åt "ÃX²ÓÈÑsïãl‹gà$x¯çÃîË¦0—Çi…•µÔ\€"2¨…œ@dS
Övw”fAäõpÌlhN£ü nØó4@¼zú¥!"" ¿†¼^›c-´ÝzÁ@D$"""2ôý€É=ÜÚ—"-éjYÏ7©S³ˆˆˆÈÑÀUÐmã†ÙP2ÐáˆˆˆŒh*r&bÕîËº[w½î°}ûòÔ‹JDDddR›†ác=œù°1á¦z8ÖpF
»›Ù?ÐÑ‰ˆˆˆY·ô°¢°Ìv¹-àEDDDä{ºK¡ìk	g›ÍsDDDD¤¯·ØJÝtñÏY)ˆˆÈH¢¬áéu¸
ÖØ®	C¢ð%Y¸›£…ODDDdH"
