### ISSUE TITLE
Translating Monika's .CHR file

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8723]
so I recently opened the file, and I kinda wanna get it translated, I alr have Yuris translated because its Base 64, and its the easiest, but I need help getting monikas character file translated, (I have no idea what language format they use lol), I highly doubt we will be able to translate it because it probably doesnt even exist

**Comment by JinSakaiM** [comment]
heres some of the chr file

**Comment by lunulae** [comment]
If you're referring to the base DDLC .chr file, you can find the answers on the [DDLC wiki.](https://ddlcwiki.net/wiki/Monika.chr)

**Comment by Booplicate** [comment]
Please, only use issues for mod suggestions and bug reports.

**Comment by JinSakaiM** [comment]
can we ask for guidence?
