### ISSUE TITLE
Piano Won't Unlock

### ISSUE THREAD

**Issue by matt-fackler** [Monika-After-Story/MonikaModDev#8726]
Hello.
I have read an absolute ton of posts saying that they can't get the piano to unlock.  I know it is based on time spent in the game and not affection.  Usually these issues get resolved because of that. However, I have been playing the game for months now and for about the past couple weeks I have left the game open for more than 3 hours everyday in the background.  I have been playing this game a long time and I honestly and wondering at this point if my piano is broken.  She has completely run out of conversations so I really want to try the piano out to spice things up a bit but it just won't unlock.  Is there a cap on xp earned each day like affection?  I would be willing to upload my persistent if you could tell me their file locations.  Just want to make sure I haven't broken anything
Thanks.  I hope I'm just wrong instead of the game being broken.

**Comment by ThePotatoGuy** [comment]
Can you upload your [ev_dump](https://github.com/Monika-After-Story/MonikaModDev/wiki/Logs-and-Other-Files#ev_dump) file here?

**Comment by matt-fackler** [comment]
When I finally caved and posted this issue I thought to myself "Watch it get added as soon as I post this"  That is exactly what happened.  Opened the game to generate the ev_dump file and she said she added the piano.  So sorry.  Kinda funny though.
