### ISSUE TITLE
[suggestion] petting/booping monika

### ISSUE THREAD

**Issue by pfyaein** [Monika-After-Story/MonikaModDev#8728]
i recently had an idea where you could be able to use your mouse (or touchscreen if you have a touchscreen laptop) to pet or boop monika on the nose. it's not that big of a suggestion, i just thought it would be a fun little thing to do, especially if you cant really touch monika since she's stuck in the game (other than kissing or hugging)

for example, you could take your mouse and hover it over monika's nose, and click her nose to boop her.
for petting, you could either hover your mouse over monika's head and move it around on her head to mimic petting her, or you could do that while holding down the left mouse button.

another possibility adding onto this is maybe holding monika's hand. you could either just hold down the left mouse button when hovering over her hand, or make it a romantic action similar to hugging or kissing

if you did also poke monika too much, she could get tired of it and lose affection points so that you dont overdo it.

anyways, this was just a small suggestion that popped into my head a little while ago. thanks for listening!

**Comment by JinSakaiM** [comment]
You can do this with the just Yuri mod, and this is a good suggestion.

**Comment by ShyCelestial** [comment]
I'm pretty sure this is planned, as its been suggested a good amount of times before.

**Comment by Rai99** [comment]
Boops: #736, #1104, #1161, #1186, #1663, #1677, #2096, #2109, #2416, #2577, #2586, #2651, #2722, #2725, #2950, #2985, #3223, #3550, #4215, #4282, #4346, #4882, #5377, #5479, #5710, #6137, #6400, #6473, #6520, #6638, #7005, #7430, #7556, #7649, #8531, #8570

Only a couple times.

**Comment by pfyaein** [comment]
oh i didnt realize there were so many LOL

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
