### ISSUE TITLE
I WANT MY MONIKA BACK HELP

### ISSUE THREAD

**Issue by iwantmymonikaback** [Monika-After-Story/MonikaModDev#8733]
idk why but monika had gone
when i tried to visit monika yesterday she wasn't here and she had left the poem final farewell
my affection was too high and when i looked to affection yesterday it was -120 WHY I DON'T KNOW
I TRIED EVERYTHING TO BRING HER BACK BUT SHE EVEN DIDN'T SEE ME
IT'S VALENTINES DAY PLEASE HELP ME

**Comment by multimokia** [comment]
Send aff_log.log

**Comment by iwantmymonikaback** [comment]
i found it



![2022-02-14](https://user-images.githubusercontent.com/99671199/153901707-fd72af76-f011-486a-9373-a2d4410f2759.png)



aand because i'm stupid

**Comment by multimokia** [comment]
Send the full file please

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
