### ISSUE TITLE
Just Yuri Mod

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#8735]
I just got done with the sayori mod, and it isnt as good as you expect it to be, the only problem is the bad grammar, and the game hasnt been updated for a WHILE, but I really want the Yuri mod because I cant rlly seem to find it, I did find one, but it has like a 40 minute download on it, so I'd like a link to the Just Yuri Mod, and I'd appreciate if its the original one 👀

**Comment by multimokia** [comment]
This is not the place to ask for that.

**Comment by JinSakaiM** [comment]
do I ask in discussion?

**Comment by multimokia** [comment]
No. Discussion about other mods does not belong on this repository.
