### ISSUE TITLE
Strange phrase?

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8740]
![124](https://user-images.githubusercontent.com/85229914/153933005-23b268a8-80d2-47ea-9569-6edfe6af8936.png)
I don’t understand the meaning of this phrase... She seems to be not supposed to say this on February 14, but she said it. And what about the love that turned out to be a lie? What does it mean ? Is she talking about Yuri? I don't understand anything. So it's also scary

**Comment by Booplicate** [comment]
She says that she tried it when she was desperate and depressed and that she won't do it ever again.

It's random topic, so it can be triggered on F14.

**Comment by Nikv2005** [comment]
> She says that she tried it when she was desperate and depressed and that she won't do it ever again.
> 
> It's a random topic, so it can be triggered on F14.

Wait... Do you mean that she cut herself?

**Comment by zwartkop2** [comment]
I'm guessing that's what [this special poem from the base game](https://ddlcwiki.net/wiki/File:Poem_special4.png)? If you crank up the contrast, you'll see the blacked out reveals it was not written by Yuri, but someone who knew about her cutting herself.

**Comment by Nikv2005** [comment]
I did not think that everything would be so dark and confusing. I'm very surprised by all this, it's unexpected for me.

**Comment by Booplicate** [comment]
> Wait... Do you mean that she cut herself?

Yes, she has done it in the base game. Here she's just acknowledges it.

**Comment by Nikv2005** [comment]
> > Wait... Do you mean that she cut herself?
> 
> Yes, she has done it in the base game. Here she's just acknowledges it.

I’m sitting here and I understand this... I don’t even have anything to say... It’s just a little sad from this
