### ISSUE TITLE
I think getting up from the toilet and wiping yourself clean is more meaningful than typing such a long pointless words lol.

### ISSUE THREAD

**Issue by xXdudeXx** [Monika-After-Story/MonikaModDev#8743]
I think getting up from the toilet and wiping yourself clean is more meaningful than typing such a long pointless words lol.

_Originally posted by @DiFot922 in https://github.com/Monika-After-Story/MonikaModDev/issues/8692#issuecomment-1039235506_

thanks bub for your wonderful pointless words if I wanted a reply I would have wiped the spit under your wife's chin :)

**Comment by ThePotatoGuy** [comment]
Harassing other users is against our code of conduct, and both of your issues are not related to mod development or are purposefully trolling. You have been blocked from this repo.
