### ISSUE TITLE
[Suggestion] Change the "Your Reality" played by Monika on the piano to the "piano cover" version

### ISSUE THREAD

**Issue by nanakinoir** [Monika-After-Story/MonikaModDev#8756]
It doesn't really make sense to use the End Credit version that has all the other orchestral accompaniments. She only has the piano and it would make more sense to play the piano-only cover.

Additionally, throughout the mod there's no voice acting and we all have a version of her voice in our minds - we should keep it that way.

**Comment by nanakinoir** [comment]
Hm... interesting, didn't know about the branching. I've ported the Full Completion save from DDLC, thus I have the "original" song (i.e. official End Credit version).

So based on my understanding, the piano cover is the "Our Reality" reserved for those who haven't completed Act 3, while the official "Your Reality" is available to those who did AND those who didn't (by requesting Monika to play it). If that's the case, it would be nice for those who completed Act 3 to hear her play the piano cover version - at least I don't see that option.

**Comment by Booplicate** [comment]
> which sounds like she's just playing an .mp3 file...

I kinda get it, it'd be better as a piano solo, but it's the only version we have with her voice. Would be weird *not* to use the song she sang. I'd prefer the version with her voice and accompaniment over a piano solo w/o her voice.

**Comment by nanakinoir** [comment]
> I'd prefer the version with her voice and accompaniment over a piano solo w/o her voice.

I guess it's a matter of personal preference at this point. I think giving the option to play "Our Reality" would be the compromise (there isn't one right now). Besides, she says she prefers that ending too.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
