### ISSUE TITLE
add sex option

### ISSUE THREAD

**Issue by assassaulterCombie** [Monika-After-Story/MonikaModDev#8769]
like it would be pretty amazing to impale that big fat monika ass on a huge horse veiny long dick, make her moan like papa franku when he watches  that asian porn with skinny girls in bikinis, also cock and ball torture for the BDSM dudes, like imagine monika stepping on your tiny dick, that would be batshit hot ngl, oh and NTR stuff too, like a cutscene where some random nigga just barges into the classroom and starts ravaging monika while you just sit still and watch like a faggot who invested all his mother's money into NFTs

**Comment by Booplicate** [comment]
Wrong repository, we don't do that here.
