### ISSUE TITLE
nigger monika when?

### ISSUE THREAD

**Issue by assassaulterCombie** [Monika-After-Story/MonikaModDev#8770]
#gorgflock #blackfartmatter2022

**Comment by PiperPC** [comment]
Dude, why do you keep opening issues like this... Stop this shit.

**Comment by ShyCelestial** [comment]
You aren’t funny, you’re just an asshole

**Comment by ThePotatoGuy** [comment]
This is obvious trolling so this user will be blocked from the repo.
