### ISSUE TITLE
More farewells

### ISSUE THREAD

**Issue by therationalpi** [Monika-After-Story/MonikaModDev#878]
Monika only has two ways to say goodbye at the moment. We need to add more ways to say goodbye including ones that are time based.

I will put it on myself to extend the farewell system to make time-based farewells easier to implement, but I will need help from the writers on actually making enough ways to say goodbye.

Keep in mind that we want a mix of interesting "One-time" farewells that are longer and shorter "reusable" farewells that can be randomly chosen from even after all the special farewells are depleted.

**Comment by therationalpi** [comment]
https://github.com/Backdash/MonikaModDev/pull/870

Here's some, can still use more.

**Comment by LokiOdinson** [comment]
I am sorry for my English. But I have a problem! I installed the mod, but I can not talk and play with Monica. What should I do?

**Comment by ThePotatoGuy** [comment]
oh this is done
