### ISSUE TITLE
Monika can't read my gifts

### ISSUE THREAD

**Issue by OriTwi** [Monika-After-Story/MonikaModDev#8913]
I've been unable to gift monika anything from sprite packs and I'm wondering if something is wrong or if I'm just doing something incorrectly. When attempting to gift monika a gift, I download the spritepack from the official website then extract the files. I've looked at numerous guides and have tried both copying the thumb folder and monika folder into their respective folders but I have also tried individually copying a, c, and j files. Finally I copy the gift file in the character folder, monika always responds saying that she can't read the file. Is there anything I'm doing wrong?

**Comment by ThePotatoGuy** [comment]
Follow the troubleshooting guide [here](https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Sprite-Objects#troubleshooting-installation)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
