### ISSUE TITLE
Wont accept my name

### ISSUE THREAD

**Issue by Unknown-User2** [Monika-After-Story/MonikaModDev#8914]
My name is Brook and when i put it in it says "I don't think she would be comfortable calling you that... Why don't you choose something more appropriate instead"

**Comment by Unknown-User2** [comment]
It also doesn't accept Brooke

**Comment by KritRom** [comment]
I think this might be due to the word "bro" being in Brook and Brooke. "Bro" is blacklisted because it's quite awkward sometimes but I'd imagine the current system is not quite perfect.

**Comment by lunulae** [comment]
We're frequently updating the name system to deal with false positives like this. Thank you for letting us know so we can fix it! 💚

**Comment by ThePotatoGuy** [comment]
[closing as fixed]

**Comment by Ulti70895** [comment]
![image](https://user-images.githubusercontent.com/88768397/157130937-cea94524-7c51-40a4-a28e-bae4b53df99c.png)

Worst, the worst, bad...

**Comment by kkrosie123** [comment]
You're a bit late to the party, but that is also a bug.

**Comment by Booplicate** [comment]
Open a new issue or report in typos, please.
