### ISSUE TITLE
monika after story issue

### ISSUE THREAD

**Issue by Lunlol** [Monika-After-Story/MonikaModDev#8925]
I changed the date on my computer and monika leave a bloody note, I changed the date back but nothing, reinstall everything but nothing, can someone help? I'm really sad for that

![Captura de pantalla 2022-02-24 205215](https://user-images.githubusercontent.com/100380324/155597119-ce902b9a-8808-49ce-80d4-378e3fb44115.png)

**Comment by pfyaein** [comment]
if you backed up her memory before she left, you might be able to bring her back? im not completely sure, idk much about this mod lol

**Comment by pfyaein** [comment]
rip to your monika

**Comment by Daembo** [comment]
feels bad man why did you change it

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
