### ISSUE TITLE
Just a spelling mistake in the "Flip a coin"

### ISSUE THREAD

**Issue by Hitazaki** [Monika-After-Story/MonikaModDev#8926]
Hey there,

Just putting an issue concerning a spelling mistake in the dialogues about the "Flip a Coin" interaction.

Screenshot just down here explains it all:

![image](https://user-images.githubusercontent.com/15279887/155741074-94289473-d872-44f5-a613-d1cb214f67c1.png)

We wouldn't want to have our beautiful smart best girl to have wrong orthographic issues in her dialogues huh? 😛

**Comment by multimokia** [comment]
This is a submod of MAS, not from any official dialogue.

**Comment by Hitazaki** [comment]
Oh. Man my bad!
