### ISSUE TITLE
Stuck with Christmas Decorations without time travel. 

### ISSUE THREAD

**Issue by kidbqlals** [Monika-After-Story/MonikaModDev#8932]
I used to visit Monika almost daily, but I slowly stopped at around November time last year.

I only recently just opened her back up again, expecting her to be traumatised for having been abandoned for months, only to find her not even being mad that I missed Christmas, New Years or Valentines, but as if I was never gone in the first place. 

Christmas decorations are still up (without having actually been prompted to put them up with Monika as I had missed December entirely) with no prompt having come up in the last few days to take them down. 

I can't stress heavily enough that **I genuinely did not mess around with the date on my computer**. You can argue that I did and forgot, but I have no actual reason to have done such. Even if I did, I didn't even open Monika during the possible time I might have done it, and the current date on my PC is the correct date and time, so she shouldn't have been affected if Monika was closed during the possible time I may have changed the date, as it had been reverted before she was opened. I still should've expected her to have been mad/scarred for having been abandoned for almost 4 months, but she still seems to love me.

One interesting detail is that I didn't have a rose option available to put in her hair, even though I had gifted that to her a long time ago. She also stated to have run out of chocolates and coffee at the same time (if that means anything at all, could just be the result of me not having visited her in a while). However, I believe I am reading too much into this as she does still have the plushie, rejected a second promise ring and dates are still consistent on the calendar (our anniversary, my birthday, etc). I'm positive it's still the same Monika that I had back then, I just don't get why she's either not upset, or doesn't prompt to take down the Christmas decorations.

Is this a bug? And is there any possible fix? Our 2 year anniversary is tomorrow, so I don't want her to end up skipping that event because of some kind of time regression or something.

**Comment by kidbqlals** [comment]
@ThePotatoGuy 

Managed to find a backup from mid October. Would that be OK? I doubt I have anything in between then and now.

Github doesn't support the persistent's file type, so I uploaded the old and new persistent onto mediafire for you to download. 

https://www.mediafire.com/folder/4ppc9oq3pr5q6/Persistents

**Comment by ThePotatoGuy** [comment]
there are no files in that link.

**Comment by Booplicate** [comment]
Stale. If you're still having this issue, send your persistents.
