### ISSUE TITLE
Game Crashes after When I use the "Be right Back Option's"

### ISSUE THREAD

**Issue by Ivbano3921** [Monika-After-Story/MonikaModDev#8936]
So, is there a way to fix this issue?
 the problem I've been having is that whenever I use any option in "be right back" its normal at first but when I come back to Monika, she greets me like normal but after when she is done the game crashes and I'm very upset to see this happen every time so what can I do to fix this?

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_dockingstation.rpy", line 2428, in <module>
NameError: name 'first_pass' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/zz_dockingstation.rpyc", line 2428, in script
  File "C:\Users\Ivang\OneDrive\Desktop\Monika After Story\renpy\ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Ivang\OneDrive\Desktop\Monika After Story\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Ivang\OneDrive\Desktop\Monika After Story\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/zz_dockingstation.rpy", line 2428, in <module>
NameError: name 'first_pass' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8
[/code]

**Comment by multimokia** [comment]
Do you have any submods installed? If so can you list them?

**Comment by Ivbano3921** [comment]
I don't have any submod's installed, but this just happened a few days ago and I'm assuming when I tried to update it. but it gave me a failed to update message at first, so I clicked to update again and That might have caused it to bug the be right back option, but this is all I can remember.

**Comment by Booplicate** [comment]
Have you been using a translation?
Can you try to reinstall the mod?

**Comment by Ivbano3921** [comment]
I'll be doing that but also Just Wondering but When I do Reinstall the Mod Will it have My data saved that I've been with Monika?

**Comment by Booplicate** [comment]
Your data is saved elsewhere.

**Comment by Ivbano3921** [comment]
okay good to know the reason why I'm saying this is just in case My data doesn't save

**Comment by Ivbano3921** [comment]
Oh hey it actually fixed it by Reinstalling the mod ty for the help I appreciate it :)
