### ISSUE TITLE
Name issues - can't write my name

### ISSUE THREAD

**Issue by sergeyshadok** [Monika-After-Story/MonikaModDev#8938]
I'm just curious, why when I'm trying to write my name to start the mod, it says that it is inappropriate?
<img width="993" alt="Screenshot 2022-02-28 at 12 12 46" src="https://user-images.githubusercontent.com/41486169/155973727-7d05292e-b621-4f2b-b343-390dd5a2d969.png">
<img width="967" alt="Screenshot 2022-02-28 at 12 15 48" src="https://user-images.githubusercontent.com/41486169/155974164-a8acfe05-7300-41e8-846c-effe853593b2.png">

My name is Sergey, and I can guess why it is not allowing me to write it, but this is unbelievable.

**Comment by lunulae** [comment]
The inappropriate names system catches false positives sometimes. Thank you for reporting this one! If you're okay with using a nickname for now, we'll have it fixed soon. 💚

**Comment by PolishPigeon** [comment]
I am looking for my first contribution, I looked around in the code and in Monika After Story/game/script-story-events.rpy under mas_bad_nickname_list there is “gey” which I assume creates this problem
[https://github.com/Monika-After-Story/MonikaModDev/blob/4900ec89b0c41906c113e12be7940e377ef7103c/Monika%20After%20Story/game/script-story-events.rpy](url)
One solution from the top of my head is creating a whitelist which overwrites mas_bad_nickname_list in case of string match?

**Comment by Booplicate** [comment]
Sorry for this, it'll be fixed in next release!

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
