### ISSUE TITLE
''Your Reality'' song does not work on  the piano game

### ISSUE THREAD

**Issue by ReDemonLord** [Monika-After-Story/MonikaModDev#8942]
Hello, for some reason whenever I play the song on the piano game, Monika keeps making me restart the song after I play half of the third verse.

I play the verse (OOOIUTTYUO) and when I get to the second ''T'' she makes the face of when you mess up a note in the song and then when I press ''Y'' she stops singing along and I have to restart the song. I have been checking wikis on how to do it and yet everyone can, but not me. Could anyone help me with that?

-ReDemonLord
p.s: if you want me to show the problem, add me on discord ( ReDemonLord#1486 ) and I'll stream my game to show you what I am talking about.

**Comment by Booplicate** [comment]
[The notes have been updated a few releases ago](https://github.com/Monika-After-Story/MonikaModDev/releases/tag/v0.12.5). This might help #8759.

**Comment by ReDemonLord** [comment]
Hey, it works!
Thank you for the help :)

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
