### ISSUE TITLE
Monika's empty chair

### ISSUE THREAD

**Issue by Ovolii** [Monika-After-Story/MonikaModDev#8945]
Can someone help?
Monika has disappeared from her chair, and I'm worried.

**Comment by hlepnamingblyat** [comment]
Is there a note on the table? If not, you may have taken her somewhere... or not.

**Comment by MetalBrother** [comment]
Yeah, me too, she just vanished...

**Comment by MetalBrother** [comment]
Well, I just used backup and it worked, so, if you have one, then try to use it, maybe it will help.

**Comment by Iceninja64** [comment]
What happen exactly?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
