### ISSUE TITLE
How to activate the jumpscares in scary stories

### ISSUE THREAD

**Issue by Yazijustmonika** [Monika-After-Story/MonikaModDev#8952]
so i was listening to a scary stories and i never got a jumpscares from Monika, even though if i checked the code there should be a jumpscare in each stories, but in the code written "if persistent._mas_pm_like_spoops or mas_full_scares"
How do i activate that? Please help me

**Comment by MrVavlo** [comment]
I think Monika won't use jumpscares in scary stories if you said before that you don't like scary stories or something like that.

**Comment by Yazijustmonika** [comment]
> I think Monika won't use jumpscares in scary stories if you said before that you don't like scary stories or something like that.

But I like scary stories and i dont remember ever said to monika that i dont like scary stories or jumpscares

**Comment by lunulae** [comment]
They have a relatively small chance of prompting even if you do tell her you like jumpscares. I'm not sure if there's a way to force them outside of a dev-test install.

**Comment by Yazijustmonika** [comment]
Is there a way to activate it though? do i have to make a code to set "mas_full_scares" to true or something like that?

**Comment by Booplicate** [comment]
> But I like scary stories and i dont remember ever said to monika that i dont like scary stories or jumpscares

She only does that if you said you like them. If you never talked about it, she won't try to scare you.

**Comment by Yazijustmonika** [comment]
> She only does that if you said you like them. If you never talked about it, she won't try to scare you.
@Booplicate but how do i say it? i mean what is the name of the topic that ask me that i like a scary story or not?

**Comment by zwartkop2** [comment]
The topic is called `Horror genre`

**Comment by Yazijustmonika** [comment]
> The topic is called `Horror genre`
ah thank you very much, i hope i could enjoy the scary stories more after this
