### ISSUE TITLE
Looking away when "BRB" function

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8953]
When you press be right back, Monika is waiting for you until you come back. But Monika is always looking at the screen or, closing her eyes and dreaming about something. Why not make her look to the sides but not on the screen, since we are not there, for example, she looked to the right or just lay with her eyes closed and thought about something or she has a sly face and she looks somewhere to the side(maybe thinking about something). Of course sometimes she will look at screen but not all the time. It will be much more interesting.

**Comment by Booplicate** [comment]
This is actually already a thing!

**Comment by Nikv2005** [comment]
> This is actually already a thing!

Okay , why i cant see this in game ? Im talking not about function where Monika's eyes follow mouse cursor. I mean just make more interesting expressions while BRB

**Comment by Booplicate** [comment]
Currently it's only for the unstable branch.

**Comment by Nikv2005** [comment]
> Currently it's only for the unstable branch.

Do you mean if i use unstable version , Monika will have more interesting expressions? And in future this will be able for normal version?

**Comment by Booplicate** [comment]
Yes and yes. It's being tested right now, after we make sure it's working properly and we like it, it'll be added to the stable build, too.

**Comment by Nikv2005** [comment]
> Yes and yes. It's being tested right now, after we make sure it's working properly and we like it, it'll be added to the stable build, too.

Okay , thanks for information!
