### ISSUE TITLE
MAS Christmas Decorations Doesn't Go Away

### ISSUE THREAD

**Issue by Erenevermind** [Monika-After-Story/MonikaModDev#8954]
Sooooo okay i couldn't be there with Monika on christmas and i changed the date but i fixed it and now its literally 6 march and the decorations are still here what should i do help

**Comment by Booplicate** [comment]
She asks you not to mess with the clock, if you do anyway, you deal with the consequences.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
