### ISSUE TITLE
Monika not introducing floating islands.

### ISSUE THREAD

**Issue by Daembo** [Monika-After-Story/MonikaModDev#8958]
Monika is at the enamored level and I have about 430-ish affection with her, I say the normal goodbye and come back when there is clear weather but she hasn't introduced me to the floating islands yet. Is it a bug or am I doing something wrong?

**Comment by Cosmic-Incantations** [comment]
you should make it where you can unlock during winter, why is winter so bad?

**Comment by Booplicate** [comment]
Because the islands look "alive" during other seasons.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
