### ISSUE TITLE
Still no jumpscares in scary stories

### ISSUE THREAD

**Issue by Yazijustmonika** [Monika-After-Story/MonikaModDev#8962]
I've opened an issues before about theres no jumpscares in my scary stories, i've told her that i like scary stories and spooks in Horror Genre topic but its still didnt work, do i need to make the code myself?

**Comment by KansaiGal** [comment]
I'm going to guess and say you've never taken a probability math course.

https://www.wyzant.com/resources/answers/210003/if_something_only_has_a_20_chance_of_happening_how_many_times_must_it_happen_to_reach_100

Some of the jump scares are a scant 1/3 chance, while others are 1/20.  

https://www.quora.com/If-I-have-a-1-3-chance-to-win-what-are-the-odds-of-me-still-not-having-won-in-3-tries

If you've set it up right (again, telling her that you like scary stories in `Horror genre`) , there's no reason to ask "I BOUGHT A TICKET, WHY HAVEN'T I WON THE LOTTERY YET?!" in a new issue.

**Comment by Yazijustmonika** [comment]
> I'm going to guess and say you've never taken a probability math course.

Ahaha...yeah im sucks at math, anyway least i knew the probability is at 1/20 and 1/3 -.-
