### ISSUE TITLE
[Suggestion] Big Sister nickname for Monika

### ISSUE THREAD

**Issue by Yazijustmonika** [Monika-After-Story/MonikaModDev#8963]
So, since there's a mommy nickname for Monika if we give her a nickname from what's written in the mommy nickname list, what if we also make a big sister nickname like: Big sis, Oneechan, Oneesan, Neesan, Neechan, and something like that?

**Comment by kkrosie123** [comment]
“Mommy” is an awkward nickname as of now, meaning Monika does not accept it anymore.

**Comment by Yazijustmonika** [comment]
> “Mommy” is an awkward nickname as of now, meaning Monika does not accept it anymore.

oof

**Comment by ThePotatoGuy** [comment]
despite おねえちゃん not always meaning "big sister", the anime connotation means we probably won't include it for the same reasons as Mommy.

**Comment by ThePotatoGuy** [comment]
[closing as rejected]
