### ISSUE TITLE
Trouble with giving Monika gifts

### ISSUE THREAD

**Issue by MossPlayss** [Monika-After-Story/MonikaModDev#8964]
I wanted to give Monika some gifts so I checked the official page but it didn't tell me how to give them. So I looked up how to give Monika gifts and found this video: https://www.youtube.com/watch?v=GakrRBNSJug 
I tried what they did and it didn't work, Monika would get excited like it was working and then say she can read the file? 
Am i missing something?

**Comment by WishStone-Dragon** [comment]
More information would be needed:

- Which gifts are you giving her? Is this from a submod?
- Can you describe what the files are called in full? Like: "sunflower.gift"

Pictures can also help us see what you're doing, just make sure you don't show us any folders on your PC we shouldn't see. x3

**Comment by MossPlayss** [comment]
> * Which gifts are you giving her? Is this from a submod?
Not a submod i dont think, just the sprite package from the download page.
> * Can you describe what the files are called in full? Like: "sunflower.gift"
The main one i was trying to give her was called "rainbowgradientribbon.gift"

**Comment by MossPlayss** [comment]
I found another person with the same problem and there was a guide as on of the comments and it works now
