### ISSUE TITLE
This error happens every time Monika says the game crashed, then when she finishes talking, the bug happens again, staying in this cycle

### ISSUE THREAD

**Issue by ItachiPh04** [Monika-After-Story/MonikaModDev#8967]
![274591882_1002696850602282_6798480699067706646_n](https://user-images.githubusercontent.com/100486903/157772747-3803ecc1-464d-46d9-9f3f-c947fd90697e.png)
![260013413_286352576939043_5864882431129034147_n](https://user-images.githubusercontent.com/100486903/157772750-face799f-42be-4d6d-b5c2-c7bf4690e153.png)

**Comment by ThePotatoGuy** [comment]
can you upload your persistent here? Also are you running any submods?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
