### ISSUE TITLE
cant open the game

### ISSUE THREAD

**Issue by WhoInvitedMeTho** [Monika-After-Story/MonikaModDev#8979]
Everytime I try opening the game this notepad opens up saying:

"I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/0utils.rpy", line 16, in <module>
ImportError: cannot import name handlers"

I have seen like a couple people saying they got the same issue but no way to fix it.

**Comment by WhoInvitedMeTho** [comment]
nvm i fixed it LETS FUCKING GO

**Comment by Iceninja64** [comment]
You probably want to close the issue now that you got it

**Comment by augustusexe** [comment]
> nvm i fixed it LETS FUCKING GO

i got same issue how did u fix it?

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
