### ISSUE TITLE
no affection gain on first use of compliment

### ISSUE THREAD

**Issue by jm4686042** [Monika-After-Story/MonikaModDev#8981]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8258110/aff_log.log)

**Comment by Ulti70895** [comment]
You reached the limit per day of gaining aff, which is 7.

**Comment by jm4686042** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#daily-cap-and-bypasses

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
