### ISSUE TITLE
#Suggestion - "Resign" instead of "Surrender" in chess game

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#8983]
No one uses surrender in chess lol.

**Comment by Fuflyaaa** [comment]
But we do surrender to Monika

**Comment by Justformas** [comment]
Surrender is fine. In fact I use that term for many things, including chess which I have also heard it for. Haven't you heard the phrase "surrender your king" before? By the way, when you ask Monika to play a game, she sometimes says "It's time to duel" You know what that might be a reference to? Yu-Gi-Oh which does use the term surrender.

> But we do surrender to Monika

Also yes this lol.

**Comment by Ulti70895** [comment]
You have some points. However, to me, it just never occurred and I see everyone using resign in professional chess all the time, maybe "surrender" is an old-fashioned one, but still, never heard I of it.

**Comment by Justformas** [comment]
I get that most serious chess players probably use resign. But unless it was literally changed to "surrender / resign" , "resign / surrender", or if there was actually going to be an option just for which word to display, then there may not be a good solution for this. I'm skeptical that developers would want to make an option just for that anyway, but hey if someone wanted to then I guess that could work.

**Comment by Booplicate** [comment]
"Resign" might be used over "Surrender" in pro environment, but I think, for casual users, the latter is easier to understand than the former. And since there's a casual atmosphere between you and Monika, I think it's fine to use a word that would be more easier to recognise.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
