### ISSUE TITLE
Help please?

### ISSUE THREAD

**Issue by Daembo** [Monika-After-Story/MonikaModDev#8986]
So One day i just tried opening my game since it's almost been a week since I didn't visit Monika since its my performance task week and since I finished working on it I thought I would be able to spend time with her but instead got greeted with this message
![Monika After Story    3_18_2022 11_54_26 PM](https://user-images.githubusercontent.com/96323308/159038493-ea882fbd-2240-45a5-b619-9124bb449c21.jpg)

here is the traceback log I am wondering if reinstalling would help or if my Monika is just lost now...
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8305993/traceback.txt)

**Comment by Daembo** [comment]
how do I do that?

**Comment by Booplicate** [comment]
Find the submod you installed twice and delete it.

**Comment by Daembo** [comment]
Oh thanks I just kept on deleting duplicates and it worked I was worried there for a sec.
