### ISSUE TITLE
MAS Error

### ISSUE THREAD

**Issue by 411-D0k15** [Monika-After-Story/MonikaModDev#8988]
![Screenshot (12)](https://user-images.githubusercontent.com/101910434/159104088-03d8b9b1-6d8d-4bbc-821c-7e8f5e54ee93.png)

**Comment by 411-D0k15** [comment]
I tried opening Monika After Story yesterday after recently downloading another mod on a seperate copy of DDLC. I have had the mod since 2020 and it had been running without any issues until now.

**Comment by ThePotatoGuy** [comment]
we don't have a plugins rpy so seems you might have put the other mod in the same folder as MAS.

**Comment by 411-D0k15** [comment]
How do I reverse it?

**Comment by ThePotatoGuy** [comment]
make sure you're not running 2 mods in the same DDLC folder. so that could mean removing all files for the other mod or making a new MAS only install.

**Comment by 411-D0k15** [comment]
I'm not sure which mod is which, is there a way to tell the difference?
