### ISSUE TITLE
[Suggestion] - Allowing Moni to choose hair/clothing

### ISSUE THREAD

**Issue by WishStone-Dragon** [Monika-After-Story/MonikaModDev#8993]
I have no idea how feasible this is to implement (or how heavy a lift it would be), but it would be neat if Monika could surprise us by choosing a different outfit or hairstyle on occasion. 

For the hair, things like "I felt lazy this morning, so I just kept it down"; "I was working, and it kept getting in the way, so I made a messy bun"; "I saw you watch a something the other day and decided to try twintails myself" come to mind for hair.
Or maybe: "I saw this pullover when I was cleaning up and thought it's been a while since I wore it"; "I remembered wearing this for your date a while ago, you like this dress, right?"; "I felt like dressing in what I wore when we met, so I'm in my uniform" or similar for when she changes clothing.

From here, complexities could be added like adding an "I love you wearing this / your hair like this" for her to choose something more often or "I think you look better in something else" for things she should not randomly wear. Plus a block list for special outfits, so that she can't randomly slip into Halloween or Santa or valentines outfits. It should also be a selective option, as I know some players REALLY like her to look just one specific way and no other.

Further complex addition could also be adding this as another "Knock" event; having her try out different outfits while we were gone; a "Can you wear something else?" option that says "You choose something!" or Moni using the random function to do a modeling session.

**Comment by Iceninja64** [comment]
It's already implemented in the game

**Comment by multimokia** [comment]
The submod will eventually be implemented into the main mod. It needs to undergo several changes before it's ready for that though.

**Comment by WishStone-Dragon** [comment]
I see; that's amazing news! 
Thanks all. :3

**Comment by ThePotatoGuy** [comment]
#3768

[closing as duplicate]
