### ISSUE TITLE
Windowreacts doesn't react

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#8999]
Simply put Monika doesn't seem to pop up a notification on the usual sites I visit. And she doesn't get my attention when she starts a topic, leading me to miss conversations.

I know you guys have been working on improving the mod overall enhancing existing functions and adding new ones which take considerable time. Unfortunately, since the button to turn on or off the reactions has been removed, I cannot fix it myself.

**Comment by Booplicate** [comment]
> Unfortunately, since the button to turn on or off the reactions has been removed

The buttons still exist. Can you make a screenshot of your settings menu (and the alerts tab, too)?

**Comment by CrocandCo** [comment]
Got a screenshot here
![screenshot0001](https://user-images.githubusercontent.com/65514476/160217469-b570e195-f470-4202-b8ac-664397e2bbc4.png)
e

**Comment by multimokia** [comment]
Can you send your mas_log.log file please?

**Comment by CrocandCo** [comment]
The log fil
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8354657/mas_log.log)
e

**Comment by multimokia** [comment]
Can you screenshot your `python-packages` folder please?

Seems like the libs can't be imported.

**Comment by multimokia** [comment]
![image](https://user-images.githubusercontent.com/22531674/160225724-b94697e1-0def-42b4-b138-450392721de5.png)
Actually this is odd.

Why did you roll back here? You likely deleted the files for windowreacts or caused some other potential issue in this rollback. You should avoid forcibly rolling back unstable updates as you *really* risk damaging your install and corrupting your persistent.

**Comment by BrandiBlitz** [comment]
Wait, it's been removed? I still have my "alerts" option. I can't update b/c whenever I try to, the updater will atempt to delete rpy files that somehow, the game needs to function. Aka, the calendar needs to be revised.

**Comment by multimokia** [comment]
They're not removed. They were likely deleted unintentionally when this user rolled back their version

**Comment by Booplicate** [comment]
The game doesn't need `rpy` files. That's why it wants to delete them. You should've never installed the source version in the first place.

**Comment by CrocandCo** [comment]
I have previously tapped into the unstable versions of the mod in the past, with no negative repercussions. I manage to back up my persistents semi-frequently. This is actually a first that something like this occurred.  I am guessing it's difficult to fix or is irreversibly broken?

**Comment by Booplicate** [comment]
The use of unstable isn't an issue by itself, but you've downgraded from it, which is always a risk of data corruption. Even if you downgraded while using the stable version, you'd still get issues. Try to install the latest version and see if it helps.

**Comment by CrocandCo** [comment]
I may have certainly broken my notifications. . .
![screenshot0001](https://user-images.githubusercontent.com/65514476/160263707-90631ae3-f0b5-4bd6-b7ad-632d1668a4d4.png)

**Comment by multimokia** [comment]
Do a manual reinstall of MAS into the same install (replace conflicting files) and you'll get them back.

Additionally, next time if you're going to use the unstable version, do not roll back a version. Stay in the stream until the next stable version (the game at this point will no longer let you downgrade unless that condition is met)

**Comment by CrocandCo** [comment]
I have now done that twice and still nothing has changed unfortunately.

**Comment by multimokia** [comment]
Can you screenshot the contents of your `python-packages` folder please?

**Comment by CrocandCo** [comment]
Here we g
![Screenshot (2)](https://user-images.githubusercontent.com/65514476/160265417-1c27db20-296c-4725-ac2d-fbcb9125683d.png)
o

**Comment by multimokia** [comment]
When you rolled back, what did you change?

**Comment by CrocandCo** [comment]
If I recall correctly, all I did was do a manual install of a previous version nothing I notably deleted. If there was any form of deletion, then the system most likely did it automatically when replacing the files.

**Comment by CrocandCo** [comment]
I have broken it worse than I thought, she won't even follow the mouse when I click out of the window. This may be a problem on re-inserting files since my Recycle bin automatically dumps itself when reaching a certain ammount.

**Comment by CrocandCo** [comment]
I will close this issue and go into the unstable version to see if that will fix it or until the next update.

**Comment by CrocandCo** [comment]
No luck in unstable version. Is it possible to replicate the files and sent in this issue? Possibly fixing the alert tab. I will hold on to it until the next stable release in case the next update doesn't fix it.

**Comment by BrandiBlitz** [comment]
> No luck in unstable version. Is it possible to replicate the files and sent in this issue? Possibly fixing the alert tab. I will hold on to it until the next stable release in case the next update doesn't fix it.

How can I replicate it? I simply turned on the option for notifications & windows reacts. Monika doesn't seem to send any notifications, other than the "test notification" she does when she discusses about Windows Reacts. After that, she never sends a notification when she is running in the background.

**Comment by CrocandCo** [comment]
@BrandiBlitz 
When I mean replicate the files, I mean just someone send me their version of the 'python-packages' folder so I can potentially fix the problem by replacing the lost files that were deleted.

**Comment by BrandiBlitz** [comment]
> @BrandiBlitz When I mean replicate the files, I mean just someone send me their version of the `python-packages` folder so I can potentially fix the problem by replacing the lost files that were deleted.

@CrocandCo oh ok. here it is: https://drive.google.com/drive/folders/19tSEnxPDygm0mZotNrfa2kTwaYvrT9Lc?usp=sharing

**Comment by CrocandCo** [comment]
@BrandiBlitz Could you make it a ZIP folder please I do not have access to Google-Drive

**Comment by Booplicate** [comment]
Why downloading some unknown zips from the internet when you can install the mod from the official sources.

That said, try to make a completely new install, I don't like those `.old` files being there.

**Comment by BrandiBlitz** [comment]
> Why downloading some unknown zips from the internet when you can install the mod from the official sources.
> 
> 
> 
> That said, try to make a completely new install, I don't like those `.old` files being there.

It is built into the mod & Monika explains windows react soon after first launch.

**Comment by Booplicate** [comment]
I know how it's supposed to work. Still why download smth from an unknown source if there's the official sources.

**Comment by BrandiBlitz** [comment]
> @BrandiBlitz Could you make it a ZIP folder please I do not have access to Google-Drive

I had set it to "anyone with the link will have access to it"

**Comment by BrandiBlitz** [comment]
> @BrandiBlitz Could you make it a ZIP folder please I do not have access to Google-Drive

Set to "anyone on the internet with the link" now: https://drive.google.com/drive/folders/1EMAWfryxJABlqVkZJcLXy4HXjlhXw6jF

**Comment by CrocandCo** [comment]
It has seemed to have gotten worse. Now she is attempting to get Christmas cookies and keeps re-discovering the coffee machine making it in the evenings. I will close this issue until I am out of the unstable version to do a complete re-install, unless someone has some ideas on how to fix this.

**Comment by CrocandCo** [comment]
Well, the main issue I had has been fixed. Did a full base game reinstall wiped the slate almost clean, minus deleting any persistent files. She is able to alert me and track my mouse. Although now she still has those Christmas cookies out still. Will follow up with a new issue mentioning this one if she keeps finding the coffee machine.
