### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by jm4686042** [Monika-After-Story/MonikaModDev#9003]
when useing linux this happen
![Screenshot from 2022-03-23 21-21-21](https://user-images.githubusercontent.com/101479441/159817653-c52cb58c-4607-427a-8d00-9e3eb9989228.png)
s

**Comment by multimokia** [comment]
This is normal. It's nothing to worry about

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
