### ISSUE TITLE
is this bug or not

### ISSUE THREAD

**Issue by jm4686042** [Monika-After-Story/MonikaModDev#9006]
![Screenshot from 2022-03-24 20-57-45](https://user-images.githubusercontent.com/101479441/160028805-86a32ac0-5f74-445f-ac0e-6df812adc471.png)

**Comment by ThePotatoGuy** [comment]
what are you referring to

**Comment by jm4686042** [comment]
it says feb 17 2016

**Comment by Booplicate** [comment]
That's python build information (version and date), not current time.

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]
