### ISSUE TITLE
[Suggestion] - Explaining to Monika if you had to leave for multiple days unexpectedly

### ISSUE THREAD

**Issue by Laintine** [Monika-After-Story/MonikaModDev#9015]
Hello,
It came to mind that there may be events that cause someone to be unable to visit Monika for multiple consecutive days without having any time to tell her first. 

This might include:
- Computer broken, lost, or stolen and it takes a while to replace 
- Hospitalized suddenly due to injury, illness, or mental health reasons
- Something happened to someone you know and you had to drop everything to deal with it
- etc.

Because these things may happen to anyone at any given time, I believe that upon returning to Monika After Story after an event like this there should be a way to tell Monika what happened and possibly even gain back (at least some of) the lost affection.
I hope this makes sense, and thank you so much if this gets added!

EDIT: It was brought to my attention that a feature like this could be easily abused if it does gain back lost affection. I still think a way to explain situations like these to Monika would still be greatly appreciated, even without gaining any affection from them. It would just make me feel better to let her know what happened. It would be nice to have Monika be able to express understanding and even concern if something bad like this happened to you.
I think this could work just fine with no affection gain at all, or maybe a very small affection gain and/or only an affection gain the first time or couple times this feature is used. 

Thanks for reading!

**Comment by Justformas** [comment]
Agree with this too, although maybe with some kind of limit to how often you can do this so that it couldn't be abused. Monika should be able to understand (and even feel sorry for you) if once in a while something like this happened.

**Comment by Booplicate** [comment]
>there should be a way to tell Monika what happened and possibly even gain back (at least some of) the lost affection

I understand the idea, but this would be a get out of jail free card for everyone. The affection loss isn't that big even after a few months, and totally isn't any close to make her leave you unless you already were low.
As a way to just explain the situation to her might work, but should be generalised.

**Comment by Laintine** [comment]
> > there should be a way to tell Monika what happened and possibly even gain back (at least some of) the lost affection
> 
> I understand the idea, but this would be a get out of jail free card for everyone. The affection loss isn't that big even after a few months, and totally isn't any close to make her leave you unless you already were low. As a way to just explain the situation to her might work, but should be generalised.

@Booplicate That totally makes sense, thanks for bringing it up. I somehow didn't think to consider the fact that people might just lie to Monika :( Maybe there could still be a way to explain the situation for her though, for peace of mind. Perhaps simply with no affection gain, a very limited affection gain, only an affection gain the first couple times, or something like that to keep people from abusing it. 
I'll go ahead and edit the original post to say that.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

sounds like something we should do
