### ISSUE TITLE
(Repost) Can't Change Monika's Hairstyle

### ISSUE THREAD

**Issue by TizzuByte** [Monika-After-Story/MonikaModDev#9016]
### Since no one has replied to me since **November**... I will simply create a new Issue, in hopes of getting support.

[The original Issue](https://github.com/Monika-After-Story/MonikaModDev/issues/7401)

Hello,
Recently, I picked up the game again, and decided to also install the sprite pack.
Now I am not aware if I had this issue before the pack, but I can't seem to change Monika's Hairstyle, I don't find the menu, even to just have her hair down.
I was using the unstable version, and switching between stable didn't fix the issue. When I use the query, for example "Ribbons" (it seems to be a menu option) she simply tells me I can always ask her. Which I am able to change her ribbons but not her hair (Only through outfit mode, but they don't have the hair down for example)

**Comment by Booplicate** [comment]
Has she changed to hairdown herself before? You need to unlock the option first.

Also, never switch between stable/unstable, that can only add more issues.

**Comment by TizzuByte** [comment]
From what I recall, I had the option before adding the [Combined Spritepacks](https://github.com/Monika-After-Story/MonikaModDev/releases/download/v0.12.7/spritepacks-combined.zipl)

Even deleting them, and everything did not make me recoved the option. 
If you don't mind me asking, what do I have to do to unlock it? I don't mind doing it, just odd that I had it and it was suddendly gone after a restart.

**Comment by TizzuByte** [comment]
Sure. I also tried it out and I only really have the ribbon or not. Not hair down or anything, I have no extras installed at the moment. I would like to try it out both, after you check of course.
[Here it is.](https://pawpox.oberon.usbx.me/filebrowser/api/public/dl/szMRRB-4)

**Comment by TizzuByte** [comment]
Sure. I also tried it out and I only really have the ribbon or not. Not hair down or anything, I have no extras installed at the moment. I would like to try it out both, after you check of course.
[Here it is.](https://drive.google.com/file/d/15GDPTf97xHWnYGEvKjCwtN3j11KPeaaw/view?usp=sharing)

**Comment by TizzuByte** [comment]
so?

**Comment by multimokia** [comment]
Checking your persistent, it seems you haven't seen the greeting where she lets her hair down yet, which appears to be the reason you can't ask her to change it yourself.

Odd too, considering you're 189 sessions in, according to `renpy.seen_label`, it's seen, however the Event has a 0 shown count (never reached the end), and the conditional and action are wiped. But the vars from the greet are set. Additionally it seems like you had it before, so _something_ locked it and it never unlocked after the fact. So that's something we'll need to investigate.

Have you used a translation of MAS at all in the past? (Just want to investigate why this happened)

As for the issue, I'll prepare a persistent with this unlocked shortly.

**Comment by TizzuByte** [comment]
No, I never used translated versions.
I used to use unstable most of the years I have used this mod.
Any other addons I previously mentioned already c:

**Comment by multimokia** [comment]
Apologies I got caught up in assignments and exams. Here's the fixed persistent
[persist.zip](https://github.com/Monika-After-Story/MonikaModDev/files/8506769/persist.zip)

**Comment by TizzuByte** [comment]
I have a question since I am confused, I have to unlock it now, correct? Since the option doesn't show up yet, nonetheless.
[What I have](https://drive.google.com/file/d/1llI-tYz1XpNmRVG6z0HYCSSiuPsAB4Oo/view?usp=sharing)
[What I should have](https://drive.google.com/file/d/1PGDOwpt99dPQ8CcvEy9z5pIKhMCXb6-Q/view?usp=sharing) (right?)

**Comment by multimokia** [comment]
What is she wearing right now that you only have 3 options?
On the same persistent as above I have:
![image](https://user-images.githubusercontent.com/22531674/163889886-43a3a5f9-440e-491f-9ec1-c338dcf8d129.png)

**Comment by TizzuByte** [comment]
Only basics:
- School Uniform
- Basic Hair Band
 ------
![image](https://user-images.githubusercontent.com/67174190/163890155-e195de5e-2f4b-4058-b777-380d9f858d8f.png)

**Comment by TizzuByte** [comment]
You also reminded me, that I used to have the plushie too

**Comment by Booplicate** [comment]
Send your `mas_log.log`, please.

**Comment by TizzuByte** [comment]
I don't seem to have a Submods folder...

`mas_log.log` [Before I got the issue](https://drive.google.com/file/d/1LXUHTMYkYHpTwIF9as9MSwhx3EztxVDt
/view?usp=sharing)
`mas_log.log` [After I got the issue, the one I currently I am using...](https://drive.google.com/file/d/1aUmIV9grLJGjCoD3HZve1nuDcddPuOeX/view?usp=sharing)

![image](https://user-images.githubusercontent.com/67174190/163891163-12c547e5-9356-4bcc-bb7f-4b43add7ba01.png)

**Comment by Booplicate** [comment]
Did you close the game and overwrite your persistent with the one multi sent?

**Comment by TizzuByte** [comment]
I made a backup and re-installed my laptop, new SSD, and I picked ddlc again sometime after. (I think the older files are around November?) But I do recall having the things I am missing.

**Comment by Booplicate** [comment]
Did you use the persistent multi sent to you? Did you close the game before replacing your existing persistent with the new one?

**Comment by TizzuByte** [comment]
Yeah I did all that

**Comment by TizzuByte** [comment]
Did the things I give help anyway?

**Comment by Booplicate** [comment]
No, I don't understand what locked it for you again. Can you send your persistent again?

**Comment by TizzuByte** [comment]
[I am currently using Multi's, here.](https://drive.google.com/file/d/1Fs0fRX7nq1OfqkbbaAyzFm4oBxLwwAO6/view?usp=sharing)

[Here is the old one I previously sent.](https://drive.google.com/file/d/15GDPTf97xHWnYGEvKjCwtN3j11KPeaaw/view)

**Comment by Booplicate** [comment]
It doesn't look like you're using it. It's exactly in the same state as when multi sent it.

**Comment by TizzuByte** [comment]
Alright, all this time, the stuff I had to change was in the RenPy\Monika After Story . Which I wasn't aware of since I always changed things in the Original DDLC or Renpy\DDLC-etc...

I think the issue is fixed, I will try using the addons too. Thank you both c:
