### ISSUE TITLE
floating islands topic gone

### ISSUE THREAD

**Issue by MLGNote** [Monika-After-Story/MonikaModDev#9023]
so im playing mas and i noticed i finally hit affection points which is cool, but i notice not much really happened when i got to 1000 affection, which i thought is normal (which probably is but besides the point). i was pretty sure something about the floating islands changed and i went to go ask monika to see the floating islands since she never said anything at 1000 affection and i find the topic has disappeared. i tried used the search function and yet nothing came up, i also searched through all the topics. im not sure if this is something intentional like she is working on something and it takes time so she disabled the topic or something but its been over 2+ weeks probably and i just need an answer thanks

**Comment by lunulae** [comment]
Are you currently using a custom room? I believe the topic locks outside of the spaceroom, but I'm not positive.

**Comment by MLGNote** [comment]
yeah i was using a custom room and i went back to the spaceroom and it worked, thanks!
