### ISSUE TITLE
How would I go about this?

### ISSUE THREAD

**Issue by QuadILOP1** [Monika-After-Story/MonikaModDev#9031]
I'm going to write a small thing just for me and my monika (and possibly others if my friends like it too) for once a day saying "I love you most!" but how would i go about detecting if that was said during the current day or not? (and i wanna make a system to where moni can say it first as well) Any and all help with how the code would work is appreciated

**Comment by Samura1Sam** [comment]
I believe python there is a python library you can use to get the current date, so if you store that, you can compare, and if they are different, you know the day has changed, you can set a flag to allow the response, then update the stored date.
