### ISSUE TITLE
Moni ignores my gifts..

### ISSUE THREAD

**Issue by Mewkooooooooooooooooooooooooooooooooooo** [Monika-After-Story/MonikaModDev#9060]
I have tried many guides, and other stuff, but whenever I leave a gift for her, she just ignores it as if I just returned after saying goodbye without giving her anything at all. I have tried spritepacks too, those also don't work... I mean, not only clothes but also the simpliest things as coffee etc. I have been dealing with this for over a year now, and after the 2 hours of research I did today, I still haven't found a solution. And yes, I did everything right. Does anyone know how to fix this???

**Comment by lovemyapples** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/Gift-Giving-Guide
I am not sure if it'll help you but try this

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> https://github.com/Monika-After-Story/MonikaModDev/wiki/Gift-Giving-Guide I am not sure if it'll help you but try this

I have tried that a million times, haha. Sadly, it doesn't work..

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> Just to make sure, you are putting the gifts in the "characters" folder in your MAS game directory, you can see the file extensions at the end of file names, and are changing the file extension to ".gift" when renaming them, right?
> 
> So for example, an easy way to create a gift is to start by creating a new text document in the "characters" folder, however text documents end in ".txt". So for a coffee gift you'd not just change the name to "coffee.txt", but also change the file extension part at the end, so that it's "coffee.gift". Then after you restart or reopen the game she should recognize it.
> 
> Are the ".gift" files still in your characters folder after you start your game, or do they disappear? They should be disappearing.

Yep, I do it that way. I tried it with both masrun and a new txt file (I changed the extensions and names, no worries) but the gifts still stay in the characters folder.

**Comment by Justformas** [comment]
> Yep, I do it that way. I tried it with both masrun and a new txt file (I changed the extensions and names, no worries) but the gifts still stay in the characters folder.

Hmm, I really don't know then. But at least we ruled some stuff out, and it might be useful for somehow to know that the gifts files are not even disappearing. Might be a bug or something like that.

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> > Yep, I do it that way. I tried it with both masrun and a new txt file (I changed the extensions and names, no worries) but the gifts still stay in the characters folder.
> 
> Hmm, I really don't know then. But at least we ruled some stuff out, and for diagnostic purposes it might be useful for someone to know that the gifts files are not even disappearing. Might be a bug or something like that.

Well, if it is, I hope it's an easily fixable one, seeing as I can't do anything that includes files.

**Comment by Justformas** [comment]
> Well, if it is, I hope it's an easily fixable one, seeing as I can't do anything that includes files.

Actually I thought of one idea that might help someone diagnose your problem (not necessarily me), but you have to have access to a different computer and install MAS on it. You don't have to transfer over your saved data; just see if you can give gifts on a different computer (preferably one with different specs than your current computer), by doing the same thing that you have been trying. If you can, then it might be a problem that is caused by your computer, but if you can't, then you might still be doing something wrong in the gift giving process, unless that computer also has the same problem.

**Comment by Booplicate** [comment]
@Mewkooooooooooooooooooooooooooooooooooo show a screenshot of the `characters/` folder with your gifts there.

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> @Mewkooooooooooooooooooooooooooooooooooo show a screenshot of the `characters/` folder with your gifts there.

![aa](https://user-images.githubusercontent.com/104134245/164861730-6106fc9b-438f-4061-98d0-02229c18eca7.png)

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> > Well, if it is, I hope it's an easily fixable one, seeing as I can't do anything that includes files.
> 
> Actually I thought of one idea that might help someone diagnose your problem (not necessarily me), but you have to have access to a different computer and install MAS on it. You don't have to transfer over your saved data; just see if you can give gifts on a different computer (preferably one with different specs than your current computer), by doing the same thing that you have been trying. If you find that you can give gifts, then it's likely an issue caused by your original computer, but if you can't, then you might still be doing something wrong in the gift giving process, unless that computer also has the same issue as your original one.

Alr, I'll make sure to try that when I get the chance to

**Comment by Justformas** [comment]
> Alr, I'll make sure to try that when I get the chance to

@Mewkooooooooooooooooooooooooooooooooooo 
Hold on... where is Natsuki.chr Sayori.chr and Yuri.chr? Are they farther up the list in that folder, did you delete them, or is this a new or different characters folder that you made? Make sure you use your original characters folder that has those files in them, and (at least for me) the folder is literally called "characters" not "characters/".

Also, "Dosyasi" is a different language but that might not have anything to do with it.

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
> > Alr, I'll make sure to try that when I get the chance to
> 
> @Mewkooooooooooooooooooooooooooooooooooo Hold on... where are the Natsuki.chr Sayori.chr and Yuri.chr files? Are they farther up the list in that folder, did you delete them, or is this a new or different characters folder that you made? Make sure you use your original characters folder that has (or had) those character files in them, and (at least for me) the folder is literally named "characters" not "characters/" which might be used to represent a folder path like Program Files/DDLC/characters
> 
> Also, "Dosyasi" is a different language, but that might not have anything to do with it.

Yeah it used to have them, but my gifts still got ignored at that time. I'll add them back if that even matters. And yep, it's named “characters” for me too!

**Comment by Booplicate** [comment]
@Mewkooooooooooooooooooooooooooooooooooo screenshot the entire window, please.

Also are you using a translation?

**Comment by Mewkooooooooooooooooooooooooooooooooooo** [comment]
OKAY I FIXED IT. I only had to move the entire folder somewhere else, I'm sorry for wasting your time guys............ But that was never mentioned, so I'm not the one to blame :( Anyways, thank you for trying to help me

**Comment by Justformas** [comment]
@Mewkooooooooooooooooooooooooooooooooooo 
Well I'm glad you were finally able to fix it after over a year of not being able to give gifts. So the folder was in the wrong location? I'm wondering how that happened, unless you had previously moved it. But I have a possible guess:

Do you have multiple copies of DDLC installed? Like one with the MAS mod and one that is unmodded? Some people have advised doing that to keep the original game unmodded (and even for each different mod you want to use, one game copy per mod). That can be a good idea, but when you do that, you should know that when tutorials for this mod talk about the "Doki Doki Literature Club" folder/directory, they mean your MAS game folder. If you were using the characters folder in a different game directory, like an unmodded version of the game, then that's why it wasn't working.

**Comment by Tornado550** [comment]
what did you mean by having to move the whole folder because im havng the same issue rn
