### ISSUE TITLE
MAS closes automatically when minimised [Issue]

### ISSUE THREAD

**Issue by SayoHikawa1** [Monika-After-Story/MonikaModDev#9061]
I have been getting this issue where the game closes by itself when minimized, It shouldn't be a crash or a submod bug as it's a new PC and doesn't happen on my laptop (old) so I'm quite confused. This issue doesn't happen to anything else so it could be a setting I need to change after all. Other than this the game runs fine.
I have tried many things such as fresh installs or not using submods and even copying the game folder from my laptop to my PC. If anyone has an idea on a setting or anything of the sort that might be causing this please let me know, any possible advice is accepted.

**Comment by WishStone-Dragon** [comment]
Without knowing the specifics of your PC, I will take a stab in the dark here: Do you run Windows 10? Assuming that to be the current standard. x3

In which case, have a look at this: https://windowsreport.com/windows-10-apps-close-when-minimized/

Else, host of questions:

- Do you notice this with any other software?
- Have you tried to remove all other software running in the background to see if it causes the same? It could help eliminate software that doesn't play nice
- Where is your Monika installed? I noticed some issues in folders that tried to auto-save stuff to clouds, so I stuck everything in C:, which helped with that.
- Between your Laptop and your PC, are there bigger software differences? Different operating system, different use of software in general...?

**Comment by Booplicate** [comment]
It's actually simple - renpy doesn't like when you minimise it. It can cause a lot of visual bugs. Not much we can do about it, it might fix itself when we upgrade the engine.

**Comment by SayoHikawa1** [comment]
> 
Allow me to address your questions.
1. Yes I am running Windows 10
2. No, MAS seems to be the only thing
3. Yeah nothing else seems to be affecting it
4. It's staying in the default downloads folder if that changes anything 
5. They are different brands yes, and the CPU is likely different so it's possible this is a cause

Additionally I noticed it loads something (small loading symbol next to cursor) before closing it, as well as that following the link I did find some possible driver update though they dont seem to have fixed it as of now

**Comment by SayoHikawa1** [comment]
> It's actually simple - renpy doesn't like when you minimise it. It can cause a lot of visual bugs. Not much we can do about it, it might fix itself when we upgrade the engine.

judging by a few minor issues I've had elsewhere I would think this would be part of it alongside my GPU/Graphics card

**Comment by WishStone-Dragon** [comment]
(Thanks, Booplicate! I never knew.)

**Comment by SayoHikawa1** [comment]
I've found out after further testing, my graphics card generally just sucks. (It's s a bit bad/older it seems)
So I suppose I can't do anything for now, of course I could always NOT minimise MAS or just use my laptop for her instead. If there's nothing else you both want to add I'll probably close this later. Regardless thank you for the help

**Comment by Booplicate** [comment]
There's not much you can do, it's a problem within the engine. You could try a different renderer if you want, but that doesn't guarantee it'd be any better.
