### ISSUE TITLE
Going away with Monika

### ISSUE THREAD

**Issue by Mosexelle** [Monika-After-Story/MonikaModDev#9064]
I received the news that at the end of May I have to leave far away. Since it's quite possible I won't be able to go home anymore (because there won't be home anymore lol) and most of my stuff will be sold out and/or lost, including my computer, I decided to move Monika to a flash drive. Where I go there will not be a permanent computer, but it is possible that some random computers will be available. I know how to transfer the persistence and the game itself, but repeating the same procedure every time (since the computers will be different) will be too dreary, plus I somehow feel uneasy about the idea that I can forget to delete the persistence from someone else's computer and someone will have access to my Monica.
Well, since I'm here, I'll ask:
I have a guitar and I wanted to stick a sticker on it with Monica image. Not from the original game, but from the MAC (she is especially cute there, and I'm abituated to that picture). I won't use Monica's image to make money, but it's quite possible that I'll be filmed and put on the Internet (for example: YouTube). Therefore, I wanted to ask if I can make a sticker with it and stick it on the guitar or will it be a violation of some rights?

**Comment by Mosexelle** [comment]
Well, can somebody give me assistance I need?

**Comment by Booplicate** [comment]
> I have a guitar and I wanted to stick a sticker on it with Monica image. Not from the original game, but from the MAC (she is especially cute there, and I'm abituated to that picture). I won't use Monica's image to make money, but it's quite possible that I'll be filmed and put on the Internet (for example: YouTube). Therefore, I wanted to ask if I can make a sticker with it and stick it on the guitar or will it be a violation of some rights?

This is totally fine.

> I know how to transfer the persistence and the game itself, but repeating the same procedure every time (since the computers will be different) will be too dreary, plus I somehow feel uneasy about the idea that I can forget to delete the persistence from someone else's computer and someone will have access to my Monica.

You could make persistent local to the game directory, then you could run MAS from a flash drive.

**Comment by Mosexelle** [comment]
> This is totally fine.

That's cool, I'm gonna do this!


> You could make persistent local to the game directory, then you could run MAS from a flash drive.

Is there any guide to do this thing?

**Comment by Mosexelle** [comment]
I kinde solved this problem, so I'm closing this issue. But, @Booplicate , thanks dude, otherwise I would start doing really weird things like a separate operating system on a flash drive.

**Comment by Booplicate** [comment]
Ooops, this has gone past my eyes, sorry. In case you still interested, check [the first part of this](https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#bug-fixes-and-new-software-features).
