### ISSUE TITLE
[Bug] - appearance

### ISSUE THREAD

**Issue by Jaxxolotl** [Monika-After-Story/MonikaModDev#9065]
i am unsure if this is the right place to be posting this, but     I'm sorry, but an uncaught exception occurred.

While loading 'Image' u'mod_assetsthumbsremove.png'
  File gamezz_selector.rpy, line 3713, in module
  File gamezz_selector.rpy, line 3112, in render
  File gamezz_selector.rpy, line 2593, in _render_bottom_frame
  File gamezz_selector.rpy, line 2613, in _render_bottom_frame_piece
IOError Couldn't find file 'mod_assetsthumbsremove.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback
  File libwindows-i686script-ch30.rpyc, line 1513, in script call
  File libwindows-i686event-handler.rpyc, line 2534, in script call
  File libwindows-i686zz_selector.rpyc, line 4226, in script call
  File libwindows-i686zz_selector.rpyc, line 3848, in script call
  File libwindows-i686zz_selector.rpyc, line 3695, in script
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpyast.py, line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpypython.py, line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File gamezz_selector.rpy, line 3713, in module
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpyexports.py, line 1147, in say
    who(what, interact=interact)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpycharacter.py, line 877, in __call__
    self.do_display(who, what, cb_args=self.cb_args, display_args)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpycharacter.py, line 716, in do_display
    display_args)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpycharacter.py, line 508, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpyui.py, line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, kwargs)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaycore.py, line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, kwargs)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaycore.py, line 2883, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaycore.py, line 1955, in draw_screen
    renpy.config.screen_height,
  File renpydisplayrender.pyx, line 427, in renpy.display.render.render_screen (genrenpy.display.render.c6806)
    rv = render(root, width, height, 0, 0)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 693, in render
    surf = render(child, width, height, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 693, in render
    surf = render(child, width, height, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 693, in render
    surf = render(child, width, height, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplayscreen.py, line 623, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 693, in render
    surf = render(child, width, height, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 1081, in render
    st, at)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 693, in render
    surf = render(child, width, height, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 895, in render
    surf = render(d, width - x, rh, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplayviewport.py, line 259, in render
    surf = renpy.display.render.render(self.child, child_width, child_height, st, at)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplaylayout.py, line 895, in render
    surf = render(d, width - x, rh, cst, cat)
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File renpydisplayaccelerator.pyx, line 108, in renpy.display.accelerator.transform_render (genrenpy.display.accelerator.c2027)
    cr = render(child, widtho, heighto, st - self.child_st_base, at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File gamezz_selector.rpy, line 3112, in render
  File gamezz_selector.rpy, line 2593, in _render_bottom_frame
  File gamezz_selector.rpy, line 2613, in _render_bottom_frame_piece
  File renpydisplayrender.pyx, line 110, in renpy.display.render.render (genrenpy.display.render.c3440)
    cpdef render(d, object widtho, object heighto, double st, double at)
  File renpydisplayrender.pyx, line 196, in renpy.display.render.render (genrenpy.display.render.c2978)
    rv = d.render(widtho, heighto, st, at)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplayim.py, line 473, in render
    im = cache.get(self)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplayim.py, line 200, in get
    surf = image.load()
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpydisplayim.py, line 524, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File CProgram Files (x86)SteamsteamappscommonDoki Doki Literature Clubrenpyloader.py, line 543, in load
    raise IOError(Couldn't find file '%s'. % name)
IOError Couldn't find file 'mod_assetsthumbsremove.png'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8

**Comment by ThePotatoGuy** [comment]
assuming your issue here is also submod related since the other one is (#9143 )
