### ISSUE TITLE
En Passant doesn't exist in chess?

### ISSUE THREAD

**Issue by ThatDaven** [Monika-After-Story/MonikaModDev#9068]
![image](https://user-images.githubusercontent.com/57483537/165079251-8a4ef555-071e-4b8a-8b7b-253d95ffaab4.png)

So as you can see here

![image](https://user-images.githubusercontent.com/57483537/165079300-45faed2e-e9a2-4e45-b56b-aaad051885e1.png)

Pawn obviously moves 2 steps to escape my other pawn. I don't seem to be checked or anything but cannot capture using en passant?

**Comment by janneslessmann** [comment]
Please be careful with this one!
En passant can **only** be used, when the two pawns are on the same rank.
Please look at [this](https://lichess.org/study/kO2xHDCb) for further explanation.

**Comment by ThatDaven** [comment]
oh yes mb, I haven't played chess in a while and haven't encountered en passant much in 1200 elo on chess.com so :/
thanks for the heads up
