### ISSUE TITLE
[Suggestion] - Sharing same food or drinks?

### ISSUE THREAD

**Issue by NativeArtist28** [Monika-After-Story/MonikaModDev#9069]
I've been playing a bit as of late again but I would love to tell Monika that I'm also drinking coffee with her or eating chocolates after gifting her, even for other gifts too she wishes she could share with me.

 Only other idea I had was wine as a gift, she's talked about wanting to try after her story of Yuri. I'd love to have a glass a wine or coffee with her to feel a bit closer, I really hope this doesn't sound too Ridiculous, thank you for reading.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

I like this idea.
