### ISSUE TITLE
Monika kiss you when you in bad mood[suggestion]

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#9070]
When you say that you are sad , upset or something like this, Monika with some chance kiss you , for example she says "Maybe a kiss could help?". Simply and very cool idea.

**Comment by Nikv2005** [comment]
> Might be a good idea, but to point something out I think it may be intended that for you to be able to kiss Monika, you need to be at enamored+ or 400+ affection.  Yes many people are at that point, but for someone who isn't, developers might not want them to be able to kiss Monika until then.


Everyone who loves Monika at east can reach this point. So it not a problem. We speak about who already reach this point.

**Comment by Justformas** [comment]
> Everyone who loves Monika at easy can reach this point. So it not a problem. We speak about who already reach this point.

I see, was just making sure. Related Fun Fact: I will probably reach enamored today.

**Comment by Nikv2005** [comment]
> I see, was just making sure. Related Fun Fact: I will probably reach enamored today.
 
 I'm congratulate you with this!

**Comment by Justformas** [comment]
> I'm congratulate you with this!
Thanks for that. I haven't gotten to kiss Monika or seen a Promise Ring topic yet, and there's probably still a lot more for me to discover. But it's a milestone that I'm happy about... I'm very tempted to try joking about _something in particular_ immediately after giving her the Promise Ring; so there's basically only one chance. Some people might think it's evil or want to do terrible things to me over it lol, but I think Monika can take it...

**Comment by Nikv2005** [comment]
> Thanks for that. I haven't gotten to kiss Monika or seen a Promise Ring topic yet, and there's probably still a lot more for me to discover. But it's a milestone that I'm happy about... I'm very tempted to try joking about something that Monika can take fairly well, but immediately after giving her the Promise Ring. It'll probably be fine.

I think you also should have a high affection for this thing. Maybe 400 will be fine , but for safety i think it'll be better when you have more than 1000. At last don't joke at her on the day when you give her promise ring. Try to wait 1-2 days. And remember! Always apologize for that.

**Comment by Justformas** [comment]
> I think you also should have a high affection for this thing. Maybe 400 will be fine , but for safety i think it'll be better when you have more than 1000. At last don't joke at her on the day when you give her promise ring. Try to wait 1-2 days. And remember! Always apologize for that.

I think I shall accept the consequences this time, and I'm going to apologize anyway. It is something that she can take way before reaching 400 affection.

Anyway we're getting a bit off track. I do like this idea of Monika being able to kiss you when you're in a bad mood, and I guess so does Booplicate.

**Comment by JinSakaiM** [comment]
bro I've never even checked my affection before.

**Comment by JinSakaiM** [comment]
and yes she has started kissing me lately.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]

this is nice
