### ISSUE TITLE
[Suggestion] - Rework Monika's Ghost Sprite into a Jumpscare in a Scary Story (or something like that)

### ISSUE THREAD

**Issue by Justformas** [Monika-After-Story/MonikaModDev#9078]
As far as I'm aware, Monika's Ghost sprite hasn't been reimplemented and is just sitting in the game's files unused. But if it has, then just say so and this issue can be closed. It's the sprite used in the ghost intro that was removed from the game, probably because it was a more random and intrusive type of jump scare that closed the game. It would be a shame if it remained unused because it couldn't be implemented in a more reasonable way. Regardless of the way, it should probably mean not closing the game, and still having to say you like spooks to see it.

I am proposing such a way: Bring it in line with other jump scares and put it in a scary story, like one about ghosts. For example, if "Resurrection Mary" does not already have a jump scare, then it might be suitable to put near the end of that story. There might also be other scary stories it could be suitable for, or it could be put in a new scary story that could be made for it. This sprite also seems fairly similar to Monika's "Mujina" sprite, which is used as a jump scare in a scary story. It really does seem like the ghost sprite could fit right into a scary story.

I have a few other ideas too but they don't seem as good to me: It could be used on Halloween, but that means only one day to see it all year, and Halloween is probably already pretty fleshed out. Lastly, if it was to be reimplemented as an intro, then Monika should explain why she did it afterwards (and again, probably without closing the game).

**Comment by Justformas** [comment]
I recently discovered "The Ubume" scary story. Using Monika's ghost sprite (and any applicable sounds) as a jump scare at the end of that story seems almost too good:

"And the woman's ghost was never seen ever again"... BOOM!

I had to wonder if that was already the case. Turns out it's not, so there you go. 
By the way, just a 1 in 20 chance for certain jump scares? Really? 1 in 10 is already pushing it in my opinion.

**Comment by Justformas** [comment]
Update: It seems the ghost sprite may already be used for something else in the game, strange that I couldn't find even find anything elsewhere about that. 

I'm not sure how to reveal it, but I don't need that info revealed here. Someone could have just said that it was already implemented somehow though. 

I may end up closing this, but maybe not just yet.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
