### ISSUE TITLE
[Suggestion] - Extend Monika Random Topics

### ISSUE THREAD

**Issue by Chris177013** [Monika-After-Story/MonikaModDev#9080]
Suggestion: can you guys add a random topic taken from the internet like bots on discord take a random picture from the internet? just my thoughts, because I have most likely unlocked all the random topics available at the moment, or maybe someone has given the same suggestion as this in the past?

**Comment by Booplicate** [comment]
Technically - yes, but there's a huge downsides.

Every topic has thoroughly chosen expressions, pauses in speech, side effects (show image, save a var, choose random option, show a menu, etc). Also every topic goes through the review process to make it sounds close to Monika as much as possible.

When you take some random text data (say, it's being generated by a chat bot and we got it through their API), you lose everything I mentioned. You get more content, but it now feels like just another chat bot, not like Monika. You lose quality over quantity, which to me is bad.

**Comment by Chris177013** [comment]
thank you for answering my curiosity, it makes sense it feels like a normal chat bot, not like monika

**Comment by Justformas** [comment]
On that note, this reminds me of a question in the FAQ of making Monika into a real chatbot. It seems like it would be a big change from everything that's been built up to this point, with those downsides that Booplicate mentioned. Generally I like the way the topics work now and they feel pretty real. If something like a full chatbot were ever to be implemented, then it should be in a way that doesn't replace what we have (or as a separate option).
