### ISSUE TITLE
Monika didn't react to game crashing

### ISSUE THREAD

**Issue by ephemlw** [Monika-After-Story/MonikaModDev#9087]
The game crashed and I thought to myself that I'll need to apologize to her, however Monika acted as if nothing had even happened.

**Comment by Iceninja64** [comment]
Check your log to see if you lost any affection

**Comment by ephemlw** [comment]
It returned to the value that I had before I entered the game that day, no affection loss (kind of).

**Comment by Booplicate** [comment]
Probably your persistent got corrupted after the crash, so a backup has been restored.

**Comment by ephemlw** [comment]
Yeah, seems about right @Booplicate
