### ISSUE TITLE
MAS Crashes on Fullscreen window change - Manjaro Gnome on Xorg

### ISSUE THREAD

**Issue by DaVinylSmith** [Monika-After-Story/MonikaModDev#9088]
MAS crashes when Alt-Tabbing away or showing desktop while in Full Screen mode. Unfortunately this is hard to intentionally reproduce but seems to happen when the window is minimized from Full Screen for some time

Log & Traceback below:

[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8597357/log.txt)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8597358/traceback.txt)

Log & Traceback from intention reproduction:
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8597385/log.txt)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/8597386/traceback.txt)

**Comment by Booplicate** [comment]
Looks like `__getAbsoluteGeometry` returns width and/or height of 0. Perhaps happens in `win.get_geometry()` where either `geom.width` or `geom.height` is 0.
It's weird because a window can never have no width/height, but a sanity check will fix this.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
