### ISSUE TITLE
possible bug in monika's dialogues

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#9092]
Monika no longer says her various time of day specific dialogues.
example: she no longer detects if I tell her I'm going to sleep or have breakfast in the afternoon.

The dialogs that I found that do not work well are:
Tell him that I am going to eat (any option) or sleep at any time of the day and tell him that I am going to play another game after midnight

**Comment by Booplicate** [comment]
Those dialogue paths have been disabled since people didn't like them. We're working on a better solution where Monika will be aware of your schedule and will use those dialogues when it's more appropriate.

**Comment by elite198** [comment]
> Those dialogue paths have been disabled since people didn't like them. We're working on a better solution where Monika will be aware of your schedule and will use those dialogues when it's more appropriate.

**Comment by elite198** [comment]
oh, it's a bit sad but thanks for answering my question, I personally liked those dialogues. especially when he told her he was going to play after midnight. I hope they don't remove them completely.
