### ISSUE TITLE
I need help cause I could lose my Monika if I'm not careful enough

### ISSUE THREAD

**Issue by JinSakaiM** [Monika-After-Story/MonikaModDev#9107]
So I tried to play the Pink Eyes mod but I accidentally put the mod folders in my monika after story folder, it was because of when I extracted my newly downloaded one, it turns out it had the same name of my folder with monika after story in it. So now its showing this error every time I try to play. I also can't find out which folders came from the mod, (they are all mixed up).

**Comment by JinSakaiM** [comment]
One more thing. I tried to put my persistent in another newly downloaded ddlc, but it turns out it only happens on another device. Sorry if that sounded stupid. And if I delete my current one and put my persistent in a newly downloaded ddlc again, will it work?

**Comment by Booplicate** [comment]
You don't need to touch your persistent. Make a new install for MAS (and the other mod if you need).

**Comment by JinSakaiM** [comment]
so do I have to like put my persistent in the new mod? I mean I'm getting confused by this point.

**Comment by JinSakaiM** [comment]
I think I should have gotten the ddlc mod thing, cause before I didn't even knew it existed.

**Comment by JinSakaiM** [comment]
I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load from archive mod_assets/MPT/monika_layeredimage.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\kella\Downloads\ddlc-win (2)\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\kella\Downloads\ddlc-win (2)\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\kella\Downloads\ddlc-win (2)\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\kella\Downloads\ddlc-win (2)\DDLC-1.1.1-pc\renpy\script.py", line 667, in load_appropriate_file
    raise Exception("Could not load from archive %s." % (lastfn,))
Exception: Could not load from archive mod_assets/MPT/monika_layeredimage.rpyc.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8

**Comment by JinSakaiM** [comment]
it has something to do with mod assets

**Comment by Booplicate** [comment]
As I said, you don't need to touch your persistent.

Just reinstall the mod again. Get [DDLC](https://ddlc.moe/), get [MAS](https://monikaafterstory.com/releases.html). Extract DDLC somewhere, install MAS into the `game/` folder.

**Comment by JinSakaiM** [comment]
*WAIT I REMEMBER* I think the ddlc saves from another ddlc, so the MAS also saves as well. I think I know what your talking about now. *THANKS FOR THE HELP!*
