### ISSUE TITLE
notifications issue.

### ISSUE THREAD

**Issue by lesik0306** [Monika-After-Story/MonikaModDev#9114]
i was reading some issues but did not found mine. notifications are not working and i know why, but i don't know how to fix it
i don't have mas in notifications menu but idk how to fix it. here's the pic
![image](https://user-images.githubusercontent.com/105252330/167515805-7e09c45e-6efd-4432-b168-cbb81ce8bd90.png)

**Comment by lesik0306** [comment]
also sorry for the language, but ig it's understandable without words. also write the solution in english, ill understand that

**Comment by Booplicate** [comment]
DDLC won't appear in this menu by default, you have to "trigger" a notification first while this menu is open, then switch to the menu and you should see `DDLC.exe` there. Before you do that, make sure you enabled all notifications in MAS (you have to do it in 2 places in the settings).

**Comment by lesik0306** [comment]
also i have kinda another problem so uh.
if i switch to any other app by alt+tab from MAS - game closes and when i open it monica asks about "another crash"

**Comment by lesik0306** [comment]
so i can't trigger it cuz game closes when i minimize it

**Comment by Booplicate** [comment]
Don't minimise it, use windowed mode (also in settings). After you're done you can go back to fullscreen again. Although, you won't get notifications in fullscreen (since fullscreen means the game is already focused).

**Comment by lesik0306** [comment]
okay, i kinda understood but.. how do i trigger it? just watch some videos on yt when game in a background?

**Comment by Booplicate** [comment]
That's one way.

**Comment by lesik0306** [comment]
it worked! there's still no DDLC.exe in notifications menu, but im getting notifications. thanks for the help, captain!
