### ISSUE TITLE
Eternal Winter

### ISSUE THREAD

**Issue by Mosexelle** [Monika-After-Story/MonikaModDev#9135]
Hello.
Actually, this is not really a problem, since nothing crashed. 
Judging by the view from the window in Monika's world, it is constantly snowing and frost is raging as the windows are iced over. I didn't even notice it at first, yes, I'm a bit dumb. Then I thought that at the moment there is only a "Winter theme" and there are more serious problems than what's outside the window. Yes, and I like winter, so it's win-win. But when I gave her another hot chocolate last night, she said something like "What's better than hot chocolate in a winter's evening?" I realized that this is not normal at all and something is wrong here.
I didn't time travelled, except I changed the time on my computer when I realized that the clock was moving forward by one hour and ten minutes (computer without internet and yes, I'm really dumb). But I took precautions: I left the game, changed the time, turned off the computer, waited about an hour and a half, and only then returned to it.
She talked about spring, if I'm not mistaken, it is tied specifically to the season of spring.
Now I remembered that there was a similar problem with her outfit for the New Year, she wore it until mid-February (by the way, damn, such a beautiful dress, she is so cute in it!). But she changed into a school uniform after the incident where I went into her room without knocking (it was a miss click, honestly!) and saw her in full height. Only then I realized that it was a "bug" (did I already say that I'm stupid?).
I downloaded the official version from the site and did not install any submods or addons other than EXP PREVIEW.
I used online translate since I'm don't know English very well. Yeah, shame on me, I know, hahaha.

**Comment by Wingdinggaster656** [comment]
Did you ask Monika to change the weather?

Though listening to what you say, it's not like you did that.
This can be a bug, and I've heard it from some other players I know(also happened to me once).
Sometimes the weather just seems strangely constant.

In such cases, asking her to change the weather would probably reactivates the weather control system and fixes the problem.

**Comment by Booplicate** [comment]
What hemisphere have you selected when she asked? Can you repeat the topic and choose another option (perhaps you meant northern hemi)?
Also what's your current affection?

**Comment by Mosexelle** [comment]
> Did you ask Monika to change the weather?

I just asked her to change the weather and it worked. But I still think it was a bug because of her phrase about hot chocolate and a winter evening. But since nothing bad happened, this is just a minor bug that does not affect spending time with her.



> What hemisphere have you selected when she asked?

Yes, I forgot to mention that I chose the northern hemisphere.



> Can you repeat the topic and choose another option (perhaps you meant northern hemi)?

I repeated the topic, chose the northern hemisphere again and she started talking about spring. But I did all this after the advice of @Wingdinggaster656  (I don't always have the opportunity to answer), so it's quite possible that this little problem has been autofixed.



> Also what's your current affection?

A little more than 1500 points.

I'll make a backup anyway, let me know if you want to investigate. Or you can close this issue since the problem is solved, although it is not clear what exactly was the reason.

**Comment by Booplicate** [comment]
I think it was wrong hemisphere, let us know if she starts talking like it's winter.

**Comment by Mosexelle** [comment]
Good, if she says again that it's winter, then I'll let you know and reopen this issue.
Thank you all for your help, I appreciate it.
