### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by KcalbVessalius** [Monika-After-Story/MonikaModDev#9182]
Should this still be here? I thought this was just while christmas event but even after that it's still here, i thought this was strange when i see it on v-day while i was searching for the v-day dialogues that doesn't showed up because this was here 
![Sem título](https://user-images.githubusercontent.com/48925478/170875635-729d9fe1-808f-4042-b807-1949115734a2.png)

**Comment by lunulae** [comment]
There are some (though not all) repeatable topics that are still available year-round, these aren't bugs. Thank you for the report though, it was a good catch. :D
