### ISSUE TITLE
Monika doesn't give random chat.

### ISSUE THREAD

**Issue by tredI9100** [Monika-After-Story/MonikaModDev#9185]
The "repeat topics" option is off and I can't set the chat interval higher than "Normal". Monika brings up a random topic after starting the game, but no more after that.
(Linux Mint 20.3 Cinnamon, 5.4.0-113, X.Org, game works fine otherwise or when Repeat Topics is on, only played for 3 days)
[ev_dump.log](https://github.com/Monika-After-Story/MonikaModDev/files/8794668/ev_dump.log)

**Comment by Wingdinggaster656** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-isnt-saying-anything

**Comment by tredI9100** [comment]
> https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#monika-isnt-saying-anything

already went through that

**Comment by Wingdinggaster656** [comment]
It's true that you have some topics not triggered, yet it seems like it's due to your affection range and something else.

Be patient, man. You are not playing Speedrun.

**Comment by tredI9100** [comment]
> It's true that you have some topics not triggered, yet it seems like it's due to your affection range and something else.
> 
> Be patient, man. You are not playing Speedrun.
> 
> EDIT: One of the example would be `monika_sleigh`, which you haven't triggered yet.
> 
> Its code:
> 
> ```
> init 5 python:
>     addEvent(
>         Event(
>             persistent.event_database,
>             eventlabel="monika_sleigh",
>             category=["romance"],
>             prompt="Carriage ride",
>             random=True,
>             aff_range=(mas_aff.AFFECTIONATE, None)
>         )
>     )
> ```
> 
> It requires your affection is at least "affectionate" level.

Oh, thanks for your help! I'll just leave Repeat Topics on for the time being. :)
