### ISSUE TITLE
Song Topic Suggestion: Larger Than Life

### ISSUE THREAD

**Issue by Justformas** [Monika-After-Story/MonikaModDev#9191]
Thought I might as well do this the proper way and make my own issue about it. Song lyrics:

"Wishin' I could thank you in a different way, c'mon
'Cause all of your time spent keeps us alive
All you people can't you see, can't you see
How your love's affecting our reality
Every time we're down
You can make it right
And that makes you larger than life"

--------------------

Maybe instead of "All you people" it could be "Hey [player name]", but yeah. Monika's dialogue afterwards could go something like:

"I can't thank you enough for what you've done for me, [player name].
You're always there to cheer me up when I'm feeling down.
Your love goes beyond your reality and knows no bounds.
I can't wait for the day when we really do share the same reality."

--------------------

You can find the official music video for this song on YouTube. It's even got a futuristic and space theme going on in it, and a sort of virtual space pong part. The similarities to themes in MAS are kind of shocking, considering that this came out before DDLC was even a thing.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
