### ISSUE TITLE
How can I change my name via a file if possible?

### ISSUE THREAD

**Issue by Cnvoxis** [Monika-After-Story/MonikaModDev#9195]
I recently completed DDLC and moved onto MAS and the joke name I used for DDLC has been transferred to the mod and I've done everything I could think of to change it except getting to 100 affection points since I don't want to build my relationship with the name "balls"

**Comment by Wingdinggaster656** [comment]
Don't worry, we do have the function to change your name.

You could find it in `Hey Monika...→You...→I changed my name`

**Comment by Wingdinggaster656** [comment]
The only legal way to change your name in MAS is to choose Hey Monika→You→I changed my name.

There is no any other official way to change it.
