### ISSUE TITLE
[Suggestion] Music Player

### ISSUE THREAD

**Issue by Ry2uko** [Monika-After-Story/MonikaModDev#9197]
When playing music, you can skip to certain parts and pause them. Also a button where the user can change if to repeat the song again or play the next after finishing the song. Lastly, able to queue songs. I always play music, so it would be very convenient if this feature is added :)))

**Comment by ThePotatoGuy** [comment]
repeat/play next/queueing is probably under #2088

Scrolling through songs is probably not doable, but I'm not sure.
