### ISSUE TITLE
[Suggestion] - Easter egg with MC's name

### ISSUE THREAD

**Issue by hardcorehunter** [Monika-After-Story/MonikaModDev#9199]
I was wondering if you can add an easter egg with mc and have it where when you boot up the game you mc in the desk. Then Monika doesn't know MC show up.

**Comment by Wingdinggaster656** [comment]
Also how does MC looks like? Do you want to use the image which is in DDLC+?

**Comment by hardcorehunter** [comment]
well because we don't know if MC is still in the Game the easter egg will let people know that mc code is still in the game and i want the fan version in it don't forget this the og ddlc so it not the plus version.
![6qmlt6kwv5s11](https://user-images.githubusercontent.com/100521005/171778185-6275bd66-e6e1-4579-9389-92d63b307928.jpg)

**Comment by Wingdinggaster656** [comment]
> well because we don't know if MC is still in the Game the easter egg will let people know that mc code is still in the game and i want the fan version in it don't forget this the og ddlc so it not the plus version. ![6qmlt6kwv5s11](https://user-images.githubusercontent.com/100521005/171778185-6275bd66-e6e1-4579-9389-92d63b307928.jpg)

Then do we have the copyright? Also do everyone accept this art?
Additionally, what is the full egg? MC appears, then what?

I would personally reject this idea since too many problems need to be considered.

**Comment by Booplicate** [comment]
> because we don't know if MC is still in the Game the easter egg will let people know that mc code is still in the game

By our canon there's no mc in MAS.

MC is controversial and adding him has no point but only to piss those people off.

**Comment by Booplicate** [comment]
That's not mc, it's Chibika.

**Comment by Wingdinggaster656** [comment]
> well mc tells you that he is the one who helps you when your save is corrupted he tells you that he's code isn't fully gone like the others and not going to jump scare you and that mc i showed has been used in a lot of mod so you should be good. Also its there for the people to know that he isn't as dense as he was backthen as he is now. He tell you to not let know about him.

"Should"? Be responsible. We need 100% sure about it. Until we have a very clear evidence, we are not going to use that sprite.
Then again. Why would we use a non-official MC image? Will most people accept it? I highly doubt this.

Lastly, why is MC here to fix codes? Does MC even has his own free will at all? Does this character even has any basic free idea? Also even if he has his will, why he know code things?

And just like what Booplicate said. It is Chibika helping you, not MC. MC is probably gone for good now.
Chibika is, well, you could consider her as the symbol of Devs.

You are adding too many fan-made things. From  the sprite to the character of MC.
This is a mod based on the original game.

My personal opinion stays the same: Reject.

**Comment by Booplicate** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L17149-L17207
