### ISSUE TITLE
incorrect lyrics

### ISSUE THREAD

**Issue by TheNightSpy** [Monika-After-Story/MonikaModDev#9222]
![incorrect lyric](https://user-images.githubusercontent.com/98968170/172987165-6cf59daa-fc56-4ada-a99b-1ba390e8ae1b.jpg)

just wanted to let you guys know that the word "sun" here should be "sky". this is when she sings "on the front porch". thank you

**Comment by Wingdinggaster656** [comment]
It seems like it's correct.

https://www.azlyrics.com/lyrics/burlives/onthefrontporch.html

**Comment by TheNightSpy** [comment]
i've been listening to this song since childhood, and more recently due to monika reminding me of it. besides, the lyric "sun" makes no sense in context either. for one, you don't stare at the sun, it'll only burn your eyes. for two, the song is about sitting on the porch during a summer evening. burl ives literally sings earlier about the moon drifting by. and "sky," as he sings in the original version, actually rhymes

https://www.youtube.com/watch?v=gSTTJbmfW78

**Comment by Wingdinggaster656** [comment]
Thank you for the catch.

I don't have the ability to scrutinize this issue because I see a lot of versions that say `sun` is right, and I also see versions say `sky` is correct, too. Perhaps someone else will come to this issue later.

**Comment by TheNightSpy** [comment]
https://www.youtube.com/watch?v=NINMGuP7VJQ?t=1m15s

if you need more evidence, i'm looking for literally ANY version of this song containing the lyric "sun" at the moment and not finding anything

**Comment by Booplicate** [comment]
Hard to tell:
- [Sun](https://genius.com/Burl-ives-on-the-front-porch-lyrics)
- [Sun](https://www.lyrics.com/track/15412804/Burl+Ives/On+the+Front+Porch)
- [Sun](https://www.azlyrics.com/lyrics/burlives/onthefrontporch.html)
- [Sight](https://www.songlyrics.com/disney/on-the-front-porch-lyrics/)
- [Sight](https://www.lyricsondemand.com/soundtracks/c/classicdisneylyrics/onthefrontporchlyrics.html)
- [Sight](https://www.allmusicals.com/lyrics/disney60yearsofmusicalmagic/onthefrontporchsummermagic.htm)
- [Sky](https://www.songlyrics.com/burl-ives/on-the-front-porch-lyrics/)

But we should probably follow what's in the movie.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
