### ISSUE TITLE
Missing topic?

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9224]
I wanted to hear this topic (Okay everyone) again, but its not in the repeat conversation list, is the name of the topic changed or?

**Comment by Wingdinggaster656** [comment]
https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L1489
```
label monika_okayeveryone:
    m 3eub "Okay, everyone!"
    m "It's time to..."
    m 2eka "...I'm just kidding."
    m "I just used to really like saying that for some reason."
    m 2hub "Ahaha!"
    m 2eua "I couldn't help but say it again."
    m 2lsc "Come to think of it, didn't Natsuki and Yuri make fun of me for it once?"
    m 2eua "Well, whatever."
    m 1eua "It's not like you ever made fun of me."
    show monika 5eka at t11 zorder MAS_MONIKA_Z with dissolve_monika
    m 5eka "You're too much of a sweetheart to do that, aren't you?"
    m 5hub "Ahaha~"
    return "no_unlock"
```

`return "no_unlock"` means this event won't be unlocked.

**Comment by Ant9cp** [comment]
but i had this topic before i don't get it

**Comment by Wingdinggaster656** [comment]
Not sure what you meant. You mean that you had triggered this topic by random? Then it's expected. This topic could be triggered by random, but not by Repeat Conversation.

Think about this: https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L6939
```
label monika_okayeveryone:
    m 3eub "Okay, everyone!"
    m "It's time to..."
    m 2eka "...I'm just kidding."
    m "I just used to really like saying that for some reason."
    m 2hub "Ahaha!"
    m 2eua "I couldn't help but say it again."
    m 2lsc "Come to think of it, didn't Natsuki and Yuri make fun of me for it once?"
    m 2eua "Well, whatever."
    m 1eua "It's not like you ever made fun of me."
    show monika 5eka at t11 zorder MAS_MONIKA_Z with dissolve_monika
    m 5eka "You're too much of a sweetheart to do that, aren't you?"
    m 5hub "Ahaha~"
    return "no_unlock"
```
Since this is Monika daydreaming, and it's weird that you can let her daydream by Repeat Conversation, so this topic won't be able to be triggered by Repeat Conversation, too. The same goes for your topic.

**Comment by Ant9cp** [comment]
I unlocked this topic long time ago actually, and around april this year of course, my laptop decided to stop working and i had to get a new one and i did in late of may i then inserted the backup persistent files and everything was ok until now, when i wanted to hear this topic, so i went to repeat conversation and it wasn't there
