### ISSUE TITLE
Topic not showing in Repeat conversation list

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9225]
There is a topic called (Okay everyone) and it's not showing in the repeat conversation list

She does talk about this topic, if i turn on repeat topic's in the pause menu but this topic is not in the list

**Comment by Wingdinggaster656** [comment]
I think I already answered your question in #9224.

`return no_unlock` means it is expected.

**Comment by Booplicate** [comment]
It doesn't make sense to be able to start that convo.
