### ISSUE TITLE
[contributing] [submod] new brbs

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#9226]
hi! submitting some brb ideas for the next release, which i coded as a submod~

list of brbs:
- i'm going to voice chat with a friend;
- someone is calling me;
- i'm going to lie down;
- i'm going to get some food;
- i'm going to write on my journal;
- i'm going to do my nails;
- i'm going to check my social media;
- i'm going to stretch my legs;
- i need to stim.

[Otter's Be Right Backs.zip](https://github.com/Monika-After-Story/MonikaModDev/files/8884848/Otter.s.Be.Right.Backs.zip)

**Comment by ThePotatoGuy** [comment]
I'll create prs for these within the next month.

**Comment by my-otter-self** [comment]
created prs for these. closing the issue!
