### ISSUE TITLE
Are able to like give monika furniture 

### ISSUE THREAD

**Issue by Ethan4Spirit** [Monika-After-Story/MonikaModDev#9229]
Hey so i just wanted to know if you can give her furniture because he room looks sad and empty and i want to give her some furniture.

**Comment by Wingdinggaster656** [comment]
Currently, there are submods allow that.

As for officially allowing furniture, I suspect it will be added in the future, but not in the near future.

**Comment by Ethan4Spirit** [comment]
Ok thank you for the information now i have another question

**Comment by Ethan4Spirit** [comment]
Can you change her room?

**Comment by Wingdinggaster656** [comment]
You mean change the background?

If I read the code correctly, there currently seem to be a very limited number of options that require you to have at least 400 points of affection. Then, you can change specific backgrounds for specific holidays.

**Comment by Ethan4Spirit** [comment]
Oh ok thank you

**Comment by Justformas** [comment]
Here's the submod you (probably) want: https://github.com/tw4449-s-MAS-Submods/tw4449-Custom-Room-Selection-Pack-Main-Repository/tree/master

**Comment by Ethan4Spirit** [comment]
Thank You

**Comment by ThePotatoGuy** [comment]
planned as part of #5345, but delayed because of priorities, sorry.

[closing as duplicate]
