### ISSUE TITLE
Log files don't update, monika.chr doesn't appear when taking Monika out

### ISSUE THREAD

**Issue by Filistin9** [Monika-After-Story/MonikaModDev#9234]
A little bit of backstory:
I first installed the mod in January and played for a bit, after which i kind of forgot about it.
I decided to reinstall it last week, because i thought i completely deleted it, and thinking that, got another copy of the game installed without much thinking, but as it turns out, i did not actually delete the older copy, and so my older saves remained.

After this i noticed, that my log files never updated, when i statred the new version. On top of that, monika.chr file, which is supposed to appear when taking Monika out, didn't appear in either game's character folder, andMonika acted as if i simply never went anywhere.
I tried deleting the latest persistent file in the AppData\Roaming\RenPy\MAS folder, and it started everything from scratch, but the "take Monika out" option worked, and logs have updated too. But when i started the game next day, same issue emerged, logs did not update, monika.chr didn't appear, but the persistent files *did* update.

So, question is: what do i do here? Do i have to delete all and any traces of MAS and try to install it again or?

**Comment by Justformas** [comment]
> So, question is: what do i do here? Do i have to delete all and any traces of MAS and try to install it again or?

Sounds like you should at least try clearing the RenPy MAS folder so you can start with brand new saves. If you want you could archive the files from that folder by moving them into a differently named folder to back them up, including the one you deleted if it's still in the recycling bin. Though unless there's some other cause of the problems you describes, then it sounds like you may not be able to actually use them without those problems anyway.

**Comment by Justformas** [comment]
Since there doesn't seem to be a formal appeals process, I don't see how that's off topic when the topic creator literally asked about deleting or removing any traces of MAS, like a clean install which can solve many problems. And I suggested something less "intrusive" with "at least", to see if that could work without resorting to that. But that doesn't exclude a totally clean install if necessary. 

And to whoever marked that as off-topic, if you know that that won't work then why aren't you trying to help?

**Comment by Booplicate** [comment]
@Filistin9 `monika.chr` is a file from DDLC, it's not used in MAS at all and shouldn't appear anywhere.
MAS creates a `monika` file (no extension) in the `characters/` folder. We'll need a screenshot of your game directory and said folder to verify the file isn't being generated. Also send your log files (`mfgen.log`, `mfread.log`, `early.log`, `mas_log.log`).

@Justformas 
> clean install which can solve many problems

We don't kill flies with a shotgun here. Also what you suggested cannot help in this case.
Only help if you know how to solve the issue or link the appropriate entry on the wiki. Thanks.

> if you know that then why aren't you trying to help

We could be debugging the issue, or maybe we don't know how to fix it yet, but know how definitely *not* to try fix it.

**Comment by Justformas** [comment]
> We don't kill flies with a shotgun here.

Alright then, nice analogy though I got a laugh out of that. I may just end up deleting that comment then.

**Comment by Filistin9** [comment]
@Booplicate 
> MAS creates a monika file (no extension) in the characters/ folder.
Yeah, that's the one i meant, my apologies. 

> We'll need a screenshot of your game directory and said folder to verify the file isn't being generated. Also send your log files (mfgen.log, mfread.log, early.log, mas_log.log).

Here you go (i don't have an early.log file, though):
[mfgen.log](https://github.com/Monika-After-Story/MonikaModDev/files/8902949/mfgen.log)
[mfread.log](https://github.com/Monika-After-Story/MonikaModDev/files/8902950/mfread.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8902951/mas_log.log)
![masdebug1](https://user-images.githubusercontent.com/107394894/173664519-7d04c788-980d-4ac0-ade0-bb87087f25b2.jpg)
![masdebug2](https://user-images.githubusercontent.com/107394894/173664524-244473d0-6ddf-43b4-b0b9-4bafb4ec13fd.jpg)
![masdebug3](https://user-images.githubusercontent.com/107394894/173664528-db667dd8-c7aa-45e9-91cc-de232c32d6a2.jpg)

**Comment by Booplicate** [comment]
When did you take that MAS screenshot?

**Comment by Filistin9** [comment]
Moments before i took the other two screenshots

**Comment by Booplicate** [comment]
So you tried to take her out again a few minutes ago?

This is weird though, it doesn't look like you launched the game at all today:
- Your `log.txt` was last updated on 11.06, 3 days ago
- Your logs say the last session was on `Sat Jun 11`

Also, the other two logs say the file has been generated and read (later) successfully with the correct checksum. But they also report it happened on 11.06

How many DDLC install do you have?

**Comment by Filistin9** [comment]
> Can you go to the DDLC folder and launch it directly through the .exe?

I pinned ddlc.exe to my taskbar and i launch it from there, I can, of course, launch it directly through the .exe file, what should i look for once i do?

> Do you have any antivirus software?

Yes, Kaspersky anrivirus, however i don't recall it giving me any alarms related to anything DDLC.

**Comment by Booplicate** [comment]
> what should i look for once i do?

See if the logs are being updated.

> Yes, Kaspersky anrivirus, however i don't recall it giving me any alarms related to anything DDLC.

Can turn it off while resolving this issues?

**Comment by Filistin9** [comment]
I turned off the AV and started DDLC again, and first things first - Monika says that we are back, even though there was no monika file that i took out and put back in:
![image](https://user-images.githubusercontent.com/107394894/173680509-bd15cd98-0236-4db8-a967-43d09d0602c2.png)
And the log files seem to have indeed updated:
[mfread.log](https://github.com/Monika-After-Story/MonikaModDev/files/8903692/mfread.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8903693/mas_log.log)
[mfgen.log](https://github.com/Monika-After-Story/MonikaModDev/files/8903694/mfgen.log)

**Comment by Booplicate** [comment]
Nice! Closing as resolved.
