### ISSUE TITLE
[Suggestion] Reading a book Monika mentioned

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#9259]
Monika has mentioned a couple books that she either read or just knows something about. I haven't read Fahrenheit 451 before and I now I am. It would be cool to tell her that she got me interested into reading it! We can't tell her every book we read but I feel like telling her books she has read would be simpler and would make her very happy.

**Comment by Justformas** [comment]
I think in a few of the book topics she asks if you read them, though maybe this could be extended to more (or all) of the book topics.

**Comment by AfroFluff** [comment]
She does but I would like to tell her that she got me interested into reading a book she was talking about. Show her that her words reach us kinda deal.

**Comment by Booplicate** [comment]
There's a long term project - talk menu awareness, Monika would be able to understand why you're bringing up a topic better. For example, ask if you read the book she suggested to you before.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
