### ISSUE TITLE
(Question) About the new card game

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9262]
Will there be a new compliment added? to tell her that there good or awesome at the the new game because, since there is two already for both pong and chess.

**Comment by Justformas** [comment]
> I'd prefer something like "I'm enjoying playing games with you" because pong or cards isn't that difficult or skillful. I think the pong compliment can be removed. The chess one makes sense.

I kind of like Monika's reaction to the pong compliment, however despite pong being a simple game it doesn't mean there's no skill involved or it can't get difficult. I mean I think there may not even be a difficulty cap for pong or it's something very high that no one may reach (her comments may not change after some point but it can still get harder, which is good for people who want the challenge). So perhaps she could still say something about pong.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
