### ISSUE TITLE
[File Issues.] - Sub-mod File Replacement.

### ISSUE THREAD

**Issue by Someoneonheredontworry** [Monika-After-Story/MonikaModDev#9264]
I need some help with things.

Earlier today I tried adding Sub-mods to MAS. In the Folders:"**Darwin-x86_64, Linux-i686, linux-x86_64, and windows-i686**." Ever Since i have added the Sub-mod The MAS Mod will no longer Work, I think i have replaced Some of the MAS-Files with the sub-mod-Files.
At this current moment i do not know what to do, If i should replace the Current Files that i listed with the original files from the downloaded .zip file i still have in my downloads. 

The files within the mod folder have the same name of files within the lib folders.

If there is a way to fix this problem without having to restart MAS that would be nice, But i wouldn't mind restarting. 

Sub-Mod:
[YouTube.Music.2.11.zip](https://github.com/Monika-After-Story/MonikaModDev/files/8959209/YouTube.Music.2.11.zip)

![20220622173605_1](https://user-images.githubusercontent.com/108013339/175073012-ac9700ef-b49a-4384-87c9-341014d04067.jpg)

**Comment by Someoneonheredontworry** [comment]
I have been trying for the past Five hours to try to fix it and i am unable to. So i am going to take the fact that i lost my MAS Save. I can startover.

**Comment by Booplicate** [comment]
Your saves are unaffected though.

**Comment by Someoneonheredontworry** [comment]
Yeah just found that out, had to delete all the files.
