### ISSUE TITLE
inaccurate calendar

### ISSUE THREAD

**Issue by bigsmoke852** [Monika-After-Story/MonikaModDev#9270]
for some reason Is write that it is winter in June and summer in December how do i fix that ? 

![obrázok_2022-06-23_173823603](https://user-images.githubusercontent.com/108082378/175338880-003d8bf2-ddfc-4812-9446-b6dc972625bc.png)
![obrázok_2022-06-23_173848166](https://user-images.githubusercontent.com/108082378/175338948-ddd7a22d-221e-4d99-9db3-ae4afee1417f.png)

**Comment by bigsmoke852** [comment]
> Did Monika ask you about what hemisphere you live in? Just to exclude the variant where you said you're living in the Southern Hemisphere...

I do not know
I can somehow check it out?

**Comment by MrVavlo** [comment]
"Talk" -> "Repeat Conversation" -> search for "Hemispheres". If you have it, choose the North Hemisphere in the dialog.

If not, then we can say it's a bug

**Comment by bigsmoke852** [comment]
> "Talk" -> "Repeat Conversation" -> search for "Hemispheres". If you have it, choose the North Hemisphere in the dialog.
> 
> If not, then we can say it's a bug

oke thnx is fixed now I guess I just didn't understand the question then
