### ISSUE TITLE
(Suggestion) Be able to gift monika a poem/letter/card on christMAS valentines day and her birthday and other

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9274]
I have a fun and romantic idea that you the members and or creators can hopefully make a thing for all these events

We know that monika gives us poems for ''you'' the player on christmas, valentines day, monika's birthday, the player's birthday, and on new years day i think? correct me if i'm wrong but, isn't it a little unfair that we can't gift her a nice poem or a letter 
et cetera et cetera anyway, can you plz consider making this a thing to do for her?

**Comment by Booplicate** [comment]
#5731 and some others.

**Comment by Ant9cp** [comment]
Well plz consider making this a thing if you all can

**Comment by Iceninja64** [comment]
You got to read some of duplicates they'll pretty much leads to the same thing

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]
