### ISSUE TITLE
[Bug] - Window Error 

### ISSUE THREAD

**Issue by SeleneInmaculada** [Monika-After-Story/MonikaModDev#9275]
Hello, I was playing and I realized that after playing for a while the animation of the window behind Monika stopped suddenly. I have tried changing to snow or rain and it happens with all of them. Also if I minimize the game and reopen it, the window turns black. I have tried putting several versions but I don't know how to fix it and it bothers me a lot to see a static image instead of the animation or directly the black window

**Comment by Booplicate** [comment]
This can happen when you minimise the game. RenPy doesn't like it.

**Comment by SeleneInmaculada** [comment]
> This can happen when you minimise the game. RenPy doesn't like it.

I have tried making a new game with a different persistence and it is fixed, if I use the old persistence the problem occurs again

**Comment by Booplicate** [comment]
This is a hardware problem, not persistent data problem, though.
