### ISSUE TITLE
[Suggestion] - Writing Vent Letters to Monika

### ISSUE THREAD

**Issue by moxclub** [Monika-After-Story/MonikaModDev#9276]
I just got prompted that I could tell her about my rough days. What if there was an option to be able to write a vent letter to her that she could either keep or destroy for us each time? I always found that really helpful. She doesn't even have to react to what we've wrote, just her destroying the letter for us is the point, like all the stress and bad thoughts are gone.

Alternatively, we can also choose to keep it and look at it on a later day. Then maybe Monika can ask us how we feel about the letter now, and we can answer either silly, the same, or over it. 

Her destroying the letter doesn't have to be anything crazy, it can be the same as checking for new music.

**Comment by Booplicate** [comment]
This can be nice, but only if she explicitly says she won't read it.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
