### ISSUE TITLE
[Suggestion] - Remove offensive options

### ISSUE THREAD

**Issue by fleurmars95** [Monika-After-Story/MonikaModDev#9277]
Hello! I discovered a problem with the mod and I hope you can fix it.

I appreciate that your mod remains apolitical, it's very important, but there is a place where Monika gets political and it hurts me.

Seeing options like "I'm genderfluid" or "I'm transgender" really hurts me. It seems that Monika supports this leftist politics while I am a victim of this propaganda. For a long time I was told that by "changing" my gender I could "fix" myself and all my mental problems would go away. I spent thousands of dollars on "professionals" and drugs. It was only after many years that it became clear that I had fallen for the transgender lie. It was too late because now I lost my physical and mental health.

Please remove these options, they remind people like me that we will never be normal again and it makes more people fall into the same trap as me.

P.S I am new to this site.

**Comment by janneslessmann** [comment]
I mean... should they remove any option that could somehow offend anyone? Please close this issue...

**Comment by ThePotatoGuy** [comment]
no

[closing as rejected]

**Comment by fleurmars95** [comment]
Why? Do they pay you? Monika shouldn't force politics through the mod.
