### ISSUE TITLE
[Suggestion] - Soft Kitty Piano

### ISSUE THREAD

**Issue by IndependantFlower** [Monika-After-Story/MonikaModDev#9283]
Hello, anyone who would see this! I think the song "Soft Kitty" would be a good addition to a piano song you could play for Monika! It's short, simple, and easy to find instructions for! Also, Monika could make some comments about the song (I can't think of any ideas for a comment on it she should make...)! Thanks for listening!

**Comment by Wingdinggaster656** [comment]
You might like this: https://github.com/Monika-After-Story/MonikaModDev/wiki/Adding-Custom-Piano-Songs

Also, why did you use "```"? It made your text hard to read.
