### ISSUE TITLE
[Suggestion] – Fade out on the goodbyes before the game closing itself.

### ISSUE THREAD

**Issue by MrVavlo** [Monika-After-Story/MonikaModDev#9285]
Title.

I feel like suddenly closing the game at the last line of the dialog is uncomfortable.
~~And from my experience, I can't distinguish it with the situation when the game crashes at that moment immediately.~~

Don't know if someone already issued that here, but anyway – I'd like to see this implemented one day.

**Comment by WishStone-Dragon** [comment]
Hm. Can you describe more what you mean? The title does not explain the issue to me, sorry.

**Comment by Booplicate** [comment]
My issue is sometimes the user may want to close the game as soon as possible, using a transition it's a second+ to the time. But it might looks better.

I'm more interested in investigation of the issue that led you to this.

> And from my experience, I can't distinguish it with the situation when the game crashes at that moment immediately.

Basically she always closes the game after saying "goodbye" to you, so it's something that should be expected when you say "goodbye" to her.
What are those crashes you're talking about? Does the game crash on goodbye? Usually there's a traceback with the error, can you send it?

**Comment by MrVavlo** [comment]
> Can you describe more what you mean?

Basically, when the goodbye dialog is over, the screen would go black before the game will be closed. Hope it's clearer now.

> My issue is sometimes the user may want to close the game as soon as possible

Not a valid counterpoint from me, but what if user want to _open_ the game as soon as possible? 
Sure, that's more unlikely, giving the loading times, but the fade in is there (guess it's here for a reason).

And... My apologies, but I don't have any traceback related to those crashes saved. There is always some sort of lag after the end of dialog (vary in times and depends on how "busy" my PC is), so I guess the answer lies in the situation when some memory-consuming app was launched at the same time.

If I'll get that kind of crash - I'll create a new issue related to it.

**Comment by Justformas** [comment]
> let's see what others would say, I suppose?

I'd rather have fading at close be an option like in the settings menu if implemented. But I don't think fading out when closing is needed. Are there any games that actually do that? Without a fade out it feels like Monika is actually closing the game at that moment.

> And from my experience, I can't distinguish it with the situation when the game crashes at that moment immediately.
I don't see a black screen when my game closes from saying goodbye to Monika. If there's normally a black screen at all then it must be very brief. So if you see a black screen (or a longer one), then that's how you'd distinguish it right?

**Comment by ThePotatoGuy** [comment]
>There is always some sort of lag after the end of dialog

This is probably the update checking thread getting stuck. This should be fixed in #8399 .

I agree that at most, we'd do a setting to enable slower fade out (or disable quick fade out, etc...). Parts of the initial launch "fade-in" is also loading - specifically runtime loading, so trying to remove that may be difficult.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
