### ISSUE TITLE
outfit filters [suggestion]

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#9287]
there has been the addition of filters for hair ties in the appearance tab, but why not in outfits? there could be a filter for spring summer autumn and winter since it's a pain to find the outfit of the season through all the clothes we give her. it would also be nice to have a filter for dresses but it seems that even just typing "dr" in the search brings it's own filter for dresses. it seems like a lot to ask for it being about seasonal outfits but it would make good use of this filter

**Comment by Booplicate** [comment]
Currently the outfits aren't split by seasons, only a few have submodded ex props which tell if it's a "home" outfit or "outdoor."
You can use search bar to filter stuff, that filters using multiple params like name, author, type, ex props, etc.

**Comment by ThePotatoGuy** [comment]
the search bar is more than sufficient to filter down items in the selectors. An actual filter will only be added for special cases, like hair ties, for example. We'll see if that changes in the future.
