### ISSUE TITLE
About kissing...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#9292]
When you kiss her plenty of times, she says that it almost looks like the start of a make out session...
Can we have it? Can we kiss Monika non-stop?
Like... "Keep kissing her" or something...  ❤️ 💋

**Comment by Iceninja64** [comment]
You can already do that but adding in extra dialogues may be a bit much

**Comment by hlepnamingblyat** [comment]
Ooh...
What I'm trying to say is that if we can have a prompt saying "keep kissing her" or something...

**Comment by Booplicate** [comment]
Like longer kisses (#3986)? Tbh kissing could be improved, we need to fix the animation and could have more quips for when you kiss her 5 times in a row or something.

**Comment by Booplicate** [comment]
I won't mark this as a duplicate since it's a bit different. Closing as accepted.
