### ISSUE TITLE
[Question] -- Resetting persistent data

### ISSUE THREAD

**Issue by wowm03** [Monika-After-Story/MonikaModDev#9296]
Hello, I'm new to coding and wish to code a fun submod topic for my own entertainment. I've set some other dialogues for different situations like 'first time visiting the topic' and 'revisiting the topic' and I want to test them out. 
However, I've already seen the topic before I added other dialogues, meaning now I'm stuck in the dialogue of 'revisiting the topic', and I wish to reset the data so I can see if the dialogues for 'first time visiting the topic' works, and I'm not sure how I'm supposed to do that. I'd appreciate it if someone can answer me!
Apologies for my English, it isn't my mother language. Thank you.

**Comment by howltrek** [comment]
I am also working on something similar.

just put the dialog string you work with after

else:

and you put the respective

elif ev.shown_count == x:

once you are satisfied with the result.

You can also write all the code after the

else:

and then copy it, on the correct site, once you feel ready.

you make a new copy of your rpy and clean it, leaving only what should stay.

**Comment by wowm03** [comment]
> else:

Thank you <33 
Have a nice day!
