### ISSUE TITLE
[Bug or typo? Don't know how to classify] A small error in my #7288

### ISSUE THREAD

**Issue by Wingdinggaster656** [Monika-After-Story/MonikaModDev#9306]
So I found an interesting thing.

See our `chess.rpy` in `content` branch, the one that was updated by the PR I submitted (#7288).
And we got [line 50 to line 52](https://github.com/Monika-After-Story/MonikaModDev/blob/content/Monika%20After%20Story/game/chess.rpy#L50):
```
    MODE_NORMAL = "normal_chess"
    MODE_BAD_CHESS = "chess960"
    MODE_960 = "badchess"
```
While `MODE_NORMAL` was defined as `"normal_chess"`, the `MODE_BAD_CHESS` and the `MODE_960` were actually misdefined.

Not a serious bug, as these features are still 100% playable.
However, it's always uncomfortable to leave such things in the source code.

**Comment by Booplicate** [comment]
Nice catch, I'll fix that in typos since it's small and harmless.

**Comment by Wingdinggaster656** [comment]
[Closing as fixed]
