### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by parrickstar** [Monika-After-Story/MonikaModDev#9315]
I know its pretty dumb, but this one mod has been glitching my Monika for a while. It says its there twice, but I cant figure out how to delete, since it wont work and theres no duplicate. I can show ss of any folder if i need to. The traceback error is 
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/MAS Hydration Submod/00_header.rpy", line 6, in <module>
    version="1.0.1"
  File "game/zz_submods.rpy", line 118, in __init__
SubmodError: A submod with name 'MAS Hydration Submod' has been installed twice. Please, uninstall the duplicate.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/Submods/MAS Hydration Submod/00_header.rpyc", line 1, in script
  File "C:\Users\itsma\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\itsma\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/MAS Hydration Submod/00_header.rpy", line 6, in <module>
    version="1.0.1"
  File "game/zz_submods.rpy", line 118, in __init__
SubmodError: A submod with name 'MAS Hydration Submod' has been installed twice. Please, uninstall the duplicate.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.8
[/code]

**Comment by parrickstar** [comment]
Okay wait Im actually so dumb, I figured it out.

**Comment by chaeyoungshiie** [comment]
hii! im having the exact same issue, and its even on the exact same windows folder as you. if you mind, can you tell me how you fixed it? ive been trying for the past hours and i cant fix it

**Comment by Booplicate** [comment]
You have 2 `MAS Hydration` submods, delete one of them. Common mistake is having a `game/` folder inside the `game/` folder, or having multiple submods folders.

**Comment by parrickstar** [comment]
i cant exactly rememember, but i think i might have had a double file inside the foulder? if i remember it was the file called "header" or something similar, but id say check in your sub mods folder and if theres any doubles just delete 1.
