### ISSUE TITLE
[Suggestion] Hide certain pool topics?

### ISSUE THREAD

**Issue by BORXUEWIK** [Monika-After-Story/MonikaModDev#9316]
Just like the title.
Pool topics like "Do you want to meet my girlfriend" and "You're a murder" aren't that comfortable. While I want to remove them, I also understand that MAS accepts all players, not just Monika fans, so, taking a step back, could there be a way to block certain pool topics so they only appear in places like the Unseen menu?

**Comment by Wingdinggaster656** [comment]
Considering the actual gameplay experience of the game, I don't see a problem with this change.
Considering the in-game-explanation, I think it's a bit of a problem. You're asking Monika to hide certain topics(I guess this is the way you want), and Monika should not know what questions the player can ask.

In short:
From a gameplay perspective, it should be added, but I think it's hard to find a story explanation.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
