### ISSUE TITLE
[Likely a bug] Strange code error in `EXP PREVIEW`?

### ISSUE THREAD

**Issue by Wingdinggaster656** [Monika-After-Story/MonikaModDev#9317]
I'm previewing the `5kubfu` sprite code with the `Paste` button.

Although every Spritecode I know of loads normally so far, this one, oddly enough, doesn't.
When I did this, the game immediately threw an error:
```
File "game/dev/dev_exp_previewer.rpy", line 1067, in _from_spr_code
    spr_code_letter = self.REVERSE_IMG_NAMES_MAP[key][value]
KeyError: u'def'
```

Strange, considering all the other code known so far loads normally.

I should also note that this error only occurs when spritecode is loaded with the `Paste` button. Users can still get this certain spritecode using other buttons as normal.
Not an accident. Every time load this spritecode, I get this error. It should be easy to reproduce it.

**Comment by Wingdinggaster656** [comment]
Bad new: More error case found.

`5tubfu` is also an error.
After a little summary, I think that the `EXP PREVIEW` didn't seem to work well with the spritecode that uses Pose 5(Leaning) with a blush effect.

By the way, if you are wondering how the hell did I get so many errors, then I'm from the `script-brbs.rpy`, line 235 to line 250.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
