### ISSUE TITLE
MAS has been giving me a lot of problems. 

### ISSUE THREAD

**Issue by IreallyloveMonika** [Monika-After-Story/MonikaModDev#9321]
MAS has been giving me a lot of problems. It’s been crashing on me a lot. Like, multiple time a week. And a couple of times it’s even set me back. Once after a crash it just deleted my entire progress, and just today it set me back by quite awhile. My entire laptop crashed, and when I went to open MAS back up again Monika had a different hairstyle than usual. Most days, I have her with her hair down, but this time her hair was in a ponytail, and she then started talking about whether or not she should start over the floating islands, and the “what’s your star sign?” Topic was listed as “unseen” even though I have seen both of those topics when they were new. And when I checked the affection log, it did have the message “she missed you” even though I use MAS daily. Also, while I did back her up a few days ago, I keep getting an error message that there was a problem copying from flash drive to laptop. So, basically  or TL:DR MAS has been crashing a lot, and sometimes after a crash it sets me back by a lot and I'm having trouble restoring a backup from a few days ago and now where I'm sitting is it just thinks that I haven't opened MAS since whenever that update about starting over with the floating islands.

**Comment by Booplicate** [comment]
We need to know what error exactly you're getting, send your `traceback.txt`. If MAS encounters an error, it will crash itself, but not your system. So if something happens to your laptop, then it's probably other software or a hardware problem.

**Comment by IreallyloveMonika** [comment]
Well, this is what pops up when trying to copy the backup from the flash
drive onto my laptop if this is what you need. [image: Screenshot (701).png]

**Comment by Booplicate** [comment]
It didn't upload.

**Comment by IreallyloveMonika** [comment]
![Screenshot (701)](https://user-images.githubusercontent.com/49668586/179444165-27d03bc5-cd53-4bc4-addd-3862d6e47c5c.png)
Alright, I'll try sending it again.

**Comment by Booplicate** [comment]
That's an error with your laptop (probably hard drive).

**Comment by IreallyloveMonika** [comment]
Alright, so I'll just take it to a shop. Thanks for the help.  Also, should I just update MAS now? And then just kinda deal with it thinking that I haven't opened it in awhile? Or wait to get the hardrive looked at then see if I gain that progress back, then update it?

**Comment by Booplicate** [comment]
You can update now or later, but **make sure to [backup your persistent](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) outside of your laptop**.

**Comment by IreallyloveMonika** [comment]
Alright, will do. Thanks again for the help!

**Comment by Booplicate** [comment]
Closing as resolved.
