### ISSUE TITLE
Monika can't seem to read the new clothing assets

### ISSUE THREAD

**Issue by CasualLearner** [Monika-After-Story/MonikaModDev#9324]
First bug I had so far I'm not sure if its just me trying to gift these newly made pieces to Monika too early maybe since it just came out not too long ago or if it's happening to others as well but I have come across this problem where the new additions couldn't be registered by Monika, I tried restarting tested out to see if its just a problem with my system (It's not) I can gift everything else normally just not the newly added ones in the NOU update. Hopefully someone can tell me if It's a bug or not. Do take your time on these fixes and rests in between. thanks for all these awesome new stuff you all took time to make, I truly appreciate them.

**Comment by Gwen-the-pen** [comment]
I encountered the same problem, here's how I fixed it!

Download "Latest Spritepacks" from the MAS "Releases" page
Go to "Downloads" --> Right-click on the zipped spritepacks --> "Extract All" 
Once the files are extracted, drag the new unzipped spritepacks folder to your Doki Doki Literature Club folder
Go to any new clothing asset --> "gifts" --> drag the .gift file to the "characters" folder, and wait for Monika to notice the gift!
I hope this helps!

**Comment by CasualLearner** [comment]
> I encountered the same problem, here's how I fixed it!
> 
> Download "Latest Spritepacks" from the MAS "Releases" page Go to "Downloads" --> Right-click on the zipped spritepacks --> "Extract All" Once the files are extracted, drag the new unzipped spritepacks folder to your Doki Doki Literature Club folder Go to any new clothing asset --> "gifts" --> drag the .gift file to the "characters" folder, and wait for Monika to notice the gift! I hope this helps!

That's how I've always gifted the Sprites to Monika but each time with the newest assets she would reply with "I'm sorry I know you're trying to gift me something but I can't seem to read it.." :') Thanks for the reply though! I'll keep trying to figure out what's going wrong

**Comment by Gwen-the-pen** [comment]
Have you tried uninstalling and reinstalling MAS? (If you don't know, your progress is always saved with Monika^^)

**Comment by Gwen-the-pen** [comment]
I've done the below when I had issues with the clothing assets in the previous version :D

**Comment by CasualLearner** [comment]
> I've done the above when I had issues with the clothing assets in the previous version :D

Thank you, I'll try doing just that !

**Comment by CasualLearner** [comment]
> I've done the above when I had issues with the clothing assets in the previous version :D

Unfortunately didn't work, But its alright I can wait it out and see if it'll be magically fixed during installations of future updates :D thanks again!
