### ISSUE TITLE
Latest update showing issues in Terminal (v0.12.9)

### ISSUE THREAD

**Issue by svenwlive** [Monika-After-Story/MonikaModDev#9326]
So, after i had updated to the latest version, everything was mostly fine until i saw the output of the Terminal (im on Ubuntu 22.04). I have used the unstable build once and on that build i also saw the same-ish output. I have the terminal output recorded (output from after the update download). I won't paste it here as it is kinda long. Just gonna give the link to a [google docs file.](https://docs.google.com/document/d/1KkAoB6LS_921PxwlRhd6g_LDSonskV_66rF6R7Yv2-w/edit?usp=sharing) I hope this is a normal behavior.

Note: This is my first issue submission!

Svenw (twitter: [@svenwlive](https://twitter.com/svenwlive))

**Comment by Booplicate** [comment]
Thanks for the report. You don't have to worry about those, some of them will be removed with #9265 .

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
