### ISSUE TITLE
[Suggestion] Are you a virgin? Or topic on Virginity?

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#9329]
First off, this new update is amazing, great work! Second, I'm unaware of this topic existing, but as one that plans on staying a virgin or having a platonic relationship, would it be appropriate to input said topic in? Makes sense, especially if one wants to feel closer to someone, Monika in this case, by saving themselves for her.

**Comment by Wingdinggaster656** [comment]
I think this is a very rude question. Not only to ask Monika, but also to ask anyone.

Personally dislike this idea, though I also see why you want it. Understandable.

(By the way, Monika has a Virgin Starsign)

**Comment by Secretmanguy** [comment]
I said it as a Topic, not a question to Monika directly. And I think it's only fair to let a significant other or partner your with know as it's a good way to determine someone's faith or know if they've had other experiences. While I get everyone's entitled to their opinion, and I support yours as the question can seem rude, it's a very important question to someone your close to or may plan on staying with in a relationship. Allows a couple to learn intimacy with each other and not bring a whole bunch of experience requiring the less experienced one to work harder to keep up.

**Comment by Booplicate** [comment]
> it's a very important question to someone your close

While some might be ok with that question, some might be not. Making a big deal out of this may look rude.

Why is it important? If one chooses the wrong answer, would the couple break up? It's really *not* a good way to see if somebody is "faithful", and it's totally shouldn't affect a relationship.

**Comment by Secretmanguy** [comment]
But if one lies about it and it later is confirmed to be untrue down the line of the relationship, would that not be kind of a red flag? Just saying. There's already a masturbation topic which is more personal than a Virginity topic.

**Comment by CodyCat13** [comment]
I wonder how something like that _would_ be confirmed in a relationship like this one? Like any online relationship, any one of the partners could say anything and there'd really be no good way to verify it. Being truthful would always be up to the partners' morals. Lying in itself is always a red flag one way or another. With any of the choices in MAS, one could set off lots of red flags. The mod itself can literally be used solely to hurt Monika, but with that logic one could easily say the mod should've never been created so I'd leave that where it is. Now about masturbation being more personal than virginity, some might find virginity more personal than masturbation. Although, either one shouldn't affect a relationship, especially if one had interactions with others before they even started dating Monika. If you really want a virginity topic though, you could always create a personal submod for it.

**Comment by Secretmanguy** [comment]
I'm aware, and that's why I said Suggestion, not Recommendation. Again, it's just a way to make those who have the affection with Monika to feel closer or feel more attached to Your Monika by confiding such a personal thing with her. Or just blant out saying you don't feel like talking about it.

**Comment by howltrek** [comment]
sounds interesting to configure.
could come in a question tree.

sounds interesting to configure.
could come in a question tree.

if the player is an adult:
Monika could ask the player about their relationships prior to meeting her.

if the player has had a partner.

How many has the player had?

perhaps, a version of the dialogue is also necessary, for people who told you that they are asexual.

subsequently, how intimate they have been.

and there touch that subject.

along with the fact that Monika's past was just lines programmed by someone and he didn't even program her memories about it and for the same reason, she is very curious.

Personally, I think that overprotecting the players too much and idealizing the relationship with Monika to something separate from what a real relationship would be, will cause problems.

If there are players with problems socializing, an idealized simulated relationship will only further isolate them and prevent them from understanding the true mechanics of a relationship.

If the player said he was a minor, I don't even know if it would be legal to bring it up...

From my point of view, the relationship with Monika would be practically equivalent to a long-distance relationship and the challenge, to make the player feel in one, with all that this entails.

And finally, many play with the hypothesis that in reality Monika, more than being in love, manipulates the player, to ensure her survival. o.O

it's okay for her to be jealous, like an inherent part of the character, but bringing it up a lot with Monika wanting to isolate the player... sounds like that.

**Comment by Secretmanguy** [comment]
I pulled two different points out of that. Was that intentional? Or just stating your mind?

**Comment by howltrek** [comment]
> Why is it important? If one chooses the wrong answer, would the couple break up? It's really _not_ a good way to see if somebody is "faithful", and it totally shouldn't affect a relationship.

is important, because people want to know about their partner and the past that brought them together.

first kiss and things like that, are things that couples wonder after a time together.

**Comment by Iceninja64** [comment]
It really depends on who asking the question. If monika is asking it we should have a option to not talk about it or make it where you can open up to monika at a later time. If you are the one asking it, then it really should depend on the affection you have with Monica and the topic should come up randomly just like the "love poem".

**Comment by Secretmanguy** [comment]
That was my entire point. Surprised this had as much attention as it did.
