### ISSUE TITLE
[Suggestion] - New House Rule to Disable Reflecting/Mirroring in NOU Card Game

### ISSUE THREAD

**Issue by Justformas** [Monika-After-Story/MonikaModDev#9335]
I saw #9331 but it was mentioned that more house rules could be added, and I think this could be one. The way I used to play Uno (and what I thought the official rules were), were that Draw 2s, Skips, and Reverses could not be countered, and Draw 4 Wilds could not be countered with a Draw 2 either. The player lost their turn and had to draw cards as required. There were no exceptions other than the restricted Draw 4 Wild rule if we were playing with that.

Also I'm wondering why with reflecting/mirroring, skips have to be the same color but draw 2s and reverses do not? If I'm understanding that correctly?

**Comment by multimokia** [comment]
It's part of official rules where a skip must be countered only by the same colour. Basically it differentiates them. Personally I always played with a house rule that allows a skip to be countered by any colour.

Regardless it's interesting to see the different ways people play uno. The way I've always played was a lot more...chaotic lol

**Comment by Booplicate** [comment]
> it was mentioned that more house rules could be added

During development, not after release. That change would require big rewriting.

We have "official" rules with a way to enable some house rules. Everyone plays differently and it's impossible to make a version that would work for everyone. As was mentioned it's "different take on Uno", not exactly Uno.

Skips could be changed, but in 1v1 they already work akin to Reverses, so I prefer having something that makes them different.

**Comment by Justformas** [comment]
>During development, not after release. That change would require big rewriting.

Oh I see. I know it's slightly different from UNO but didn't know the full extent of intended differences/variations. I think originally I also misinterpreted what stackable draw 2s in house rules meant before I had Monika explain it. It just means the amount of cards to draw stacking, rather than being able to play/stack cards on special cards to counter them in the first place. (Previously I had seen the Twitter UNO account say you couldn't stack cards, while also mentioning the rules about Draw 4s: https://twitter.com/realunogame/status/1329433936112594954?lang=en)
So NOU rules are different.
 
> It's part of official rules where a skip must be countered only by the same colour. Basically it differentiates them. Personally I always played with a house rule that allows a skip to be countered by any colour.

>Regardless it's interesting to see the different ways people play uno. The way I've always played was a lot more...chaotic lol

To differentiate in 1v1 ok, but out of curiosity are you just referring to NOU here, or are you also saying that even UNO has an official rule allowing skips to counter? I had thought countering in and of itself was a house rule or variation of UNO, but maybe one that became really common. For example I can't find any mention of being able to counter special/action cards like that here: https://www.ultraboardgames.com/uno/game-rules.php although Wikipedia mentions "Progressive or Stacking Uno" as a house rule for stackable draw 2s/4s, and that it became so common that people were surprised when the UNO company said it wasn't part of the standard rules.

**Comment by Booplicate** [comment]
> It just means the amount of cards to draw stacking,

By default cards don't stack though, and that's the official rule.

> rather than being able to play/stack cards on special cards to counter them in the first place

You can counter cards by default, and there's no house rule to change that in MAS.

> but out of curiosity are you just referring to NOU here, or are you also saying that even UNO has an official rule allowing skips to counter?

Both, MAS NOU w/o house rules is like official Uno rules. Stacking != reflecting.

**Comment by Justformas** [comment]
> > but out of curiosity are you just referring to NOU here, or are you also saying that even UNO has an official rule allowing skips to counter?
> 
> Both, MAS NOU w/o house rules is like official Uno rules. Stacking != reflecting.

With NOU fine, but I thought this was one of the main things that falls more into "a different take on UNO" even if it's a popular variation. I want to get to the bottom of this, because I'm not finding any sort of reflecting mechanic in the rules I'm reading. I'm also seeing stacking refer to placing a special card on top of another one in the first place (to reflect).

Like here: https://www.unorules.org/wp-content/uploads/2021/03/Uno-Rules-PDF-Official-Rules-unorules.org_.pdf

"Stacking is allowing to play a special card upon an already played special card" It uses an example which is obviously stacking, but the rest of the rules in that link don't seem to mention any sort of reflecting mechanic, nor do the rules in this one either: https://service.mattel.com/instruction_sheets/42001pr.pdf

Another example: https://greatfuntips.com/uno-block-card/#Can_You_Block_a_Card_in_Uno "Blocking a +2 card with another +2 card in one turn is called stacking and is illegal on regular Uno. The legal move in classic Uno is simple – the next player has to pick two cards and lose one turn."

For skips: https://twitter.com/realUNOgame/status/1348660347008397312 "Is it just you two playing? If so, yes because every time you play a skip it skips her turn. If this is a game of more than two players, you cannot stack skips to avoid being skipped."

Also skips: https://www.unorules.org/uno-skip-card/ "If you play according to the official rules, it is worth noting that you can’t plat a Skip card on a Skip card in order to push the “skip” forward to the next player."

And Draw 4s: https://twitter.com/realUNOgame/status/1124720366130204672 "If someone puts down a +4 card, you must draw 4 and your turn is skipped." They also say you can't stack to get out of doing so. Given the context, it sounds like they were also saying you can't play a draw 2 to get out of drawing 4 in the first place.

**Comment by ThePotatoGuy** [comment]
Boop is working on a wiki page describing the default rules in the game, and how they compare to official rules as well as popular variations (if known). That should clear up the confusion regarding what applies and what doesn't. 

>it's impossible to make a version that would work for everyone
 @Booplicate I thought you said the house rule system is configurable/extendable/easily customizable, so wouldn't this be a nonissue since people can make it work how they want?

**Comment by Justformas** [comment]
> Boop is working on a wiki page describing the default rules in the game, and how they compare to official rules as well as popular variations (if known). That should clear up the confusion regarding what applies and what doesn't.

Alright, I saw that issue you made and did think it might've been in part because of this. I understand what stacking in NOU means now, but I seriously think the term "stacking" has been used to refer to different things in UNO. Even found a tweet that seems to shoot down reflecting for Draw 2s but they call it stacking: https://twitter.com/realUNOgame/status/1314599677854179331?ref_src=twsrc%5Etfw

**Comment by Booplicate** [comment]
Hmm it seems I might have been wrong.
I have a physical copy of cards with rules, reflecting was explicitly mentioned as allowed while stacking forbidden. I can't find anything that allowed that online, and official page doesn't explain much either. Although some says you can reflect skip/reverse. So I guess MAS has its own set of rules.

> I thought you said the house rule system is configurable/extendable/easily customizable, so wouldn't this be a nonissue since people can make it work how they want?

Well, not exactly easily customisable. You'd need to change quite a bit of code, especially AI part so Monika can use the new rule as well. But it's not *impossible* either, we support it to a degree, it's just a lot of work. That's why I wanted to add them when I started working on it, not after it's done.

**Comment by Justformas** [comment]
> Hmm it seems I might have been wrong.
> I have a physical copy of cards with rules, reflecting was explicitly mentioned as allowed while stacking forbidden. I can't find anything that allowed that online, and official page doesn't explain much either. Although some says you can reflect skip/reverse. So I guess MAS has its own set of rules.

Interesting that you have a copy of rules with that though. Is there a date or copyright date somewhere on those rules? And as far as you know that is a regular Uno set?

**Comment by Booplicate** [comment]
No date or copyright, just a link to their website. It's uno h2o version, maybe 10 yo or older.

**Comment by Booplicate** [comment]
I'll close this as heard out and accepted suggestion, don't expect this soon though.
