### ISSUE TITLE
No "NOU" game...?

### ISSUE THREAD

**Issue by ohlookwhoitis** [Monika-After-Story/MonikaModDev#9336]
Hey the new update added a new game right...? how come i didn't, i guess you could say, unlock it yet? my affection is 2000+ is this a bug or am i meant to do something to unlock it?

**Comment by Justformas** [comment]
#9325

It's a good idea to check your characters folder sometimes. And personally I like that way that the player is told about it and what to do.

**Comment by ohlookwhoitis** [comment]
> #9325
> 
> It's a good idea to check your characters folder sometimes. And personally I like that way that the player is told about it and what to do.

OH alright thanks man :)
