### ISSUE TITLE
Is this normal?(The new greeting: Bath greeting)

### ISSUE THREAD

**Issue by BORXUEWIK** [Monika-After-Story/MonikaModDev#9339]
After Monika says she wants to dry her hair in the "bath greeting", the player can still request a change of hairstyle and clothes, and even change them back to their normal look.
(As if the player were a super dryer)

Is this by design?

**Comment by Booplicate** [comment]
Initially wanted to hide the selectors, but then some people didn't like that. So the selectors will remain available until we get a better system for managing random outfits and hair.

**Comment by BORXUEWIK** [comment]
[Closing as answered]
