### ISSUE TITLE
(Suggestion) A extra option in 'NOU'

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9340]
Wouldn't it be easier if you can add a option for after one of you (the player or monika) Wins the entire game (if you reach the right amound of score) that you be able to change the house rules then? If monika asks you if you want to play again just like in chess (yes but with different rules) Because i keep changing the house rules after a while

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
