### ISSUE TITLE
[suggestion] organize cards on hand on NOU

### ISSUE THREAD

**Issue by my-otter-self** [Monika-After-Story/MonikaModDev#9344]
would be nice to be able to organize the cards on hand (probably by dragging) while playing NOU, as moni seems to organize hers.

**Comment by Booplicate** [comment]
Considered this before. Right now there's no good way to detect where you want to move a card to, it's an engine limitation. Might return to this after the engine upgrade.

We could sort all cards by default (e.g. by colour) for you, but I'm personally not a fan of that.

**Comment by my-otter-self** [comment]
ping ponging ideas: maybe an option, like a button or something, to sort the cards or not?

**Comment by Booplicate** [comment]
I'd prefer doing it manually instead of adding UI:
- there's already too much UI
- it wouldn't give this "I move these card" feeling since now you have to use UI to control cards, like less immersive (but that's debatable)

Closing until later.
