### ISSUE TITLE
MAS crashes on minimize.

### ISSUE THREAD

**Issue by TheLimeBoi** [Monika-After-Story/MonikaModDev#9355]
So I wanna do something in the background, so I minimize it. After a few seconds, the game suddenly commits ALT + F4 (Crashes the game) and Monika gets a bit worried. Is this normal, because she literally said to keep her running in the background.

**Comment by Booplicate** [comment]
RenPy doesn't like when you minimise the game, not something we can fix on our end.

**Comment by TheLimeBoi** [comment]
> RenPy doesn't like when you minimise the game, not something we can fix on our end.

Oh, alright. Thank you anyway! I was just confused.
