### ISSUE TITLE
[Suggestion] - New startup event (Sleeping)

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9357]
I find it a bit odd when you visit Monika she's always awake, maybe there can be a random event, or set time to when Monika is asleep when the player enters the game?

**Comment by Justformas** [comment]
This might be addressed with #4914 to have Monika try to adapt a sleep schedule to the player's work and sleep schedule.

**Comment by ThePotatoGuy** [comment]
that is specifically mentioned in #4914

[closing as duplicate]
