### ISSUE TITLE
[Suggestion] - Notifying Monika of backups, (and possible effects on affection value)

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9358]
Random chatter with previous topics enabled, sometimes Monika will repeatedly bring up backups. Maybe have this a one-time topic, and make a feature where the player can tell Monika you backed her up, and if this is frequent, (Once every week/two weeks) a second affection value can slowly raise. If the player waits longer, then Monika can bring up her concern with backups, potentially reminding the player of backing her save file up.

**Comment by ThePotatoGuy** [comment]
backups are important not just for MAS, but for computers in general. Repetition is the best way to teach users the importance of backups. If the topic gets stale for you, you can derandom the topic by hitting `x` while Monika is speaking.
