### ISSUE TITLE
[Suggestion] - Toggleable random songs playing at startup

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9361]
Monika is always listening to the same song for a long time when the player leaves. Making a toggleable option in the settings to allow Monika to play a random song every time the player opens the game.

**Comment by Justformas** [comment]
This may not be exactly what you want but in the meantime there is a submod that lets Monika you put songs in a folder for Monika to pick from to play in the evening, if no music is already playing: https://github.com/multimokia/MAS-Submod-Nightmusic

**Comment by ThePotatoGuy** [comment]
seems like a natural extension of #2088.

Also that submod probably works, too.

[closing as duplicate]
