### ISSUE TITLE
There are no .rpy files in my Monika After Story game file. I've tried looking for them but all I have are .rpyc ones. Help?

### ISSUE THREAD

**Issue by Gwen-the-pen** [Monika-After-Story/MonikaModDev#9366]

**Comment by Booplicate** [comment]
You shouldn't have `rpy` in the `game/` folder. So what's the issue?

**Comment by Gwen-the-pen** [comment]
> You shouldn't have `rpy` in the `game/` folder. So what's the issue?

Someone said to unlock the background selector, I'd need to paste code from a .rpy file - yet there are none.

**Comment by Booplicate** [comment]
No, you never edit the mod's `rpy`, if you want to add something custom, create a submod.

The selector should be automatically unlocked when appropriate.
