### ISSUE TITLE
Monika's feet

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#9367]
Feet? ❤️ 
Can we?

P.S.: The new update is amazing. I love playing NOU more than I expected.

**Comment by InJusticeWeTrust** [comment]
She doesn't have a lower body when sitting at the table, much like the guy sitting across from her has no legs and no face. It all somehow reappears when she's standing. And sheesh, guess your suggestion didn't go over so well.

**Comment by hlepnamingblyat** [comment]
> She doesn't have a lower body when sitting at the table, much like the guy sitting across from her has no legs and no face. It all somehow reappears when she's standing. And sheesh, guess your suggestion didn't go over so well.


Eh, just giving my opinion here... 
Besides, I saw vtubers having their feet drawn on the table, but thinking twice, Monika's positions wouldn't go so well with it.
But man, if one's opinion is considered trash, it just shows how people are decaying so fast.
The "P.S." stays teh same, I do love playing cards with her.

**Comment by ThePotatoGuy** [comment]
so you want her feet on the table? your best bet is to find a submod, unfortunately.

[closing as rejected]
