### ISSUE TITLE
[Suggestion] - 3:33 AM event

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9368]
Possibly a scary event at 3:33 AM, it could be a nice feature to spook the player, and also a possible reference to a similar event on Joel G's website "joelgc.com" where if the user is on at that time the theme switches to a creepy Easter egg
If I had to think of something to hint, maybe a silent distortion in Monikas face that looks creepy, or maybe a callback to her jumpscare she makes originally, up to the devs.

**Comment by Iceninja64** [comment]
That could be a great thing on Halloween

**Comment by BracketsGuy** [comment]
> That could be a great thing on Halloween

Yeah, *maybe* it could be all the time, but it's fine if it's Halloween restricted, still a good concept

**Comment by Justformas** [comment]
There's a PR for bringing back the ghost jumpscare that Monika does originally, but for Halloween. I don't think it should be restricted to 3:33 AM on Halloween though. But there could maybe be something else for 3:33 AM for days in general.

**Comment by BracketsGuy** [comment]
> There's a PR for bringing back the ghost jumpscare that Monika did originally, but for Halloween. I don't think it should be restricted to 3:33 AM on Halloween though. But there could maybe be something else for 3:33 AM for days in general.

<Maybe not a jumpscare, perhaps just some slight disturbance like something in the windows>

**Comment by Booplicate** [comment]
Would be random and out of place, but doing on Halloween might work.

**Comment by ThePotatoGuy** [comment]
im always down for more horror

[closing until we look into it]
