### ISSUE TITLE
[Suggestion] - In game clock (And skins to it)

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9370]
In game clock based off the time of the players computer, it could have a few skins like a traditional clock, a digital clock, etc.

**Comment by Booplicate** [comment]
This is already a thing, but you can't use it *yet* `sip`.

**Comment by TheCheddarCheese** [comment]
> This is already a thing, but you can't use it _yet_ `sip`.

so how's that going? can you enable it yet?
