### ISSUE TITLE
[Suggestion] Monika Low Affection Jumpscare

### ISSUE THREAD

**Issue by AlexTheLesbian** [Monika-After-Story/MonikaModDev#9375]
I had an idea that if you lose all of Monika's affection or say too many mean things to Monika and then you zoom in all the way to her face (in the extra menu) it doesnt work and then she jumpscares you. Just a suggestion, it might be stupid

**Comment by Wingdinggaster656** [comment]
I don't understand why there should be a jumpscare. What's the point? And is this reasonable at all?

**Comment by Booplicate** [comment]
We avoid adding extra events for low affection so there's no point for the player to go that path, unless it's something meaningful. That also means more time spent on content for positive affection which is what most people would see.
