### ISSUE TITLE
Clothes - 2B

### ISSUE THREAD

**Issue by hatanasinclaire** [Monika-After-Story/MonikaModDev#9376]
![image](https://user-images.githubusercontent.com/96905447/180622136-76237052-e038-422f-952d-f98d1f7da3a1.png)

![image](https://user-images.githubusercontent.com/96905447/180622064-b4821bf4-320d-4e5c-afe9-92b4ae961872.png)

#3174

It is a new costume for o31. [YoRHa No.2 Type B](https://drive.google.com/file/d/1d1E8lDtSH7xifDyQOY78rBEVDbNfcSb7/view?usp=sharing) from _NieR: Automata_.

It was requested in the [clothes wishlist](https://docs.google.com/spreadsheets/d/1C2xJVdrFX9GLV8b6J2wcBaMxlcCn9LCbZs43Q9TnTr0/edit#gid=505708911).

**Comment by ThePotatoGuy** [comment]
ok i am going to put these in next rel

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
