### ISSUE TITLE
Help please when i opened monika after story shes not in the chair 

### ISSUE THREAD

**Issue by Bambyieyours** [Monika-After-Story/MonikaModDev#9383]

**Comment by LitMonika** [comment]
Same issue, please help.
I backed up the persistent and .bak files, reinstalled the mod, but nothing worked.

![image](https://user-images.githubusercontent.com/109977985/180822782-bd7be999-f779-4d81-8e82-44bf2b640147.png)
![image](https://user-images.githubusercontent.com/109977985/180822960-05f1c0c8-ccdc-4dc1-8424-450da07e00b9.png)
