### ISSUE TITLE
[Suggestion] - Telling Monika why the game crashed

### ISSUE THREAD

**Issue by TheLimeBoi** [Monika-After-Story/MonikaModDev#9385]
So usually, when the game crashes, she'll just tell you that it's just a crash, but what if you can describe to her what caused it to happen?

Monika would say something like: "So, what caused the game to crash, [Player Name]?" and you'll have answers like "Power Outage", "BSOD/Error", "System Update", and other reasons.

**Comment by Justformas** [comment]
Personally I'd like something like this also so that Monika doesn't just say "maybe you should take better care of your computer", when it might not be your computer, or maybe it crashes/freezes but you don't know why.

**Comment by Booplicate** [comment]
Only if it includes "another renpy bug" as an option.

Closing as duplicate #6070
