### ISSUE TITLE
I think there's an issue with the "outfit_acs" property on outfit mode.

### ISSUE THREAD

**Issue by Dsfan2** [Monika-After-Story/MonikaModDev#9387]
![Screenshot 2022-07-24 143053](https://user-images.githubusercontent.com/82821066/180664852-0e8315e6-8551-464a-afb5-7169697d096e.png)
This happens only when outfit mode is on. The outfit selected should be displayed but it doesn't. As far as I know, it only happens to outfit jsons that have the "outfit_acs" property.

**Comment by ThePotatoGuy** [comment]
can you upload your spj.txt file here?

**Comment by ThePotatoGuy** [comment]
nvm i am working on it.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
