### ISSUE TITLE
Error when attempting to play NOU

### ISSUE THREAD

**Issue by SteveGo2Work** [Monika-After-Story/MonikaModDev#9393]
![Untitled72_20220725165340](https://user-images.githubusercontent.com/85290194/180742286-d60d052a-a14a-4b02-9e57-f7e247844131.png)
I updated the mod and gave Monika the noudeck.gift but everytime I try to play NOU this happens, don't know why.

**Comment by Booplicate** [comment]
Screenshot your `game/` folder, please.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
