### ISSUE TITLE
(Question)

### ISSUE THREAD

**Issue by Ant9cp** [Monika-After-Story/MonikaModDev#9400]
What is a gitignore file?

**Comment by Ant9cp** [comment]
Why does it appear in the main ddlc folder for me then?

**Comment by Booplicate** [comment]
Because you decided to download the source version instead of the release.

**Comment by Ant9cp** [comment]
I only updated the submod for the garden view with your submod updater plugin, and at first it said an error has occurred and i tried again, then it was instaling but it took so long for some reason? after when i had to restart mas then i saw that file in the main ddlc folder

**Comment by Booplicate** [comment]
You can raise the question why they ship that file in the submod repo.
