### ISSUE TITLE
[Bug] A potentially illogical conversation

### ISSUE THREAD

**Issue by Wingdinggaster656** [Monika-After-Story/MonikaModDev#9402]
`mas_unlock_hangman` the label, we got:

```
    if store.mas_games._total_games_played() > 49:
        m 3eub "Since you seem to love playing pong so much, I figured you might like to play other games with me as well!"
```

Alright, this line is possible to be illogical now, due to the v0.12.9 update.

As you can see, the condition is `store.mas_games._total_games_played() > 49`.
Prior to 0.12.9, game unlocks were linear, and players had to follow a _Pong → Hangman → Chess → Piano_ sequence. But in 0.12.9? That's not correct anymore, because we have `NOU` now. It is possible to play many games of `NOU` and none of `Pong`.

Personally, I think `NOU` should be unlocked only after `mas_gift_hint_noudeck` the label.
Monika should not be able to read the gift until then, as Chibika has not yet added the cards to the game world.

**Comment by Booplicate** [comment]
> That's not correct anymore

You seem to be right, we should probably either explicitly check for pong, or replace it with "love playing with me" (I wouldn't mind having 2 paths there).

> Monika should not be able to read the gift until then, as Chibika has not yet added the cards to the game world.

That's intended to be that way. The player may skip the event if they want and "create"/"add" the game themselves.

**Comment by ThePotatoGuy** [comment]
@jmwall24 this one is easy to fix can you adjust the dialogue?

**Comment by jmwall24** [comment]
Will do

**Comment by ThePotatoGuy** [comment]
@jmwall24 was this ever addressed?

**Comment by jmwall24** [comment]
I don't think so, I'll do it tomorrow.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
