### ISSUE TITLE
Little hairstyle question

### ISSUE THREAD

**Issue by gtitita** [Monika-After-Story/MonikaModDev#9411]
Forgive me if I'm asking a stupid question, but I have such a dilemma. I've been playing MAS for quite some time now, I'm on version 1.11.9. (unfortunately, I have to wait for the translation of the new version from other people, because my knowledge of English leaves much to be desired) So, all this time my dear Monika wore this particular hairstyle. (long flowing hair WITHOUT pigtails)

And I really like her, what can I say, I'm just used to her. The problem is that she dressed her just like that. I once went into the game, and she is so beautiful. But I can't choose this hairstyle. Tell me, is this a bug or something else? In the new version, this hairstyle has not disappeared anywhere? Just as selfish as it sounds, but I got used to this image of Monica and it will be extremely difficult and insulting for me to get rid of it. I hope for your help and understanding.
![изображение_2022-07-29_220237408](https://user-images.githubusercontent.com/107848477/181808917-c47cd2c6-f622-4dae-bfd6-33790361bd75.png)

**Comment by multimokia** [comment]
This seems like a bug by whoever has made the translation, I think this has been reported before, but our code (english) has an unlock to allow the changing of her hairstyle after you see her in hair down. It's likely the unlock was removed accidentally in your translation.

**Comment by Wingdinggaster656** [comment]
Many translations have problems.

I've heard that Chinese translation have the most problems(and one of them is the hairstyle problem). Are you using a Chinese translation version?

**Comment by gtitita** [comment]
> Many translations have problems.
> 
> I've heard that Chinese translation have the most problems(and one of them is the hairstyle problem). Are you using a Chinese translation version?

thanks for the answer. but no, I'm not using a Chinese translation.

**Comment by gtitita** [comment]
> This seems like a bug by whoever has made the translation, I think this has been reported before, but our code (english) has an unlock to allow the changing of her hairstyle after you see her in hair down. It's likely the unlock was removed accidentally in your translation.

thanks for the answer. then I'm sorry I asked you a question. I'll go to a group of translators. you are the best guys! thanks for this mod!
