### ISSUE TITLE
[Suggestion] - Add "I love you too" to "Going to sleep?" in "Goodbye"

### ISSUE THREAD

**Issue by svenwlive** [Monika-After-Story/MonikaModDev#9417]
When saying "Goodbye" and saying "yes" to "Are you going to sleep?" she usually says "I love you". I was thinking of like a button appearing after like 3 or 5 seconds for replying to her with "I love you too". And after hitting the button, she would do something about it. Just a suggestion.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
