### ISSUE TITLE
Suggestion - Pdf for Monika (I put details in the comments)

### ISSUE THREAD

**Issue by pittypie** [Monika-After-Story/MonikaModDev#9426]
Its not important but when Monika said "Im going to outlive you aren't I?". I though it would be an interesting idea to be able to give her a photograph of the player more or less as a gift. I don't know how hard it is too code something like that so sorry if that is too much to ask.

**Comment by ThePotatoGuy** [comment]
picture-based gifts would be part of #5345

[closing as duplicate]
