### ISSUE TITLE
MAS crashes when I open it

### ISSUE THREAD

**Issue by TotallyMia** [Monika-After-Story/MonikaModDev#9433]
I randomly opened up the game and after a few minutes my window froze and everything crashed, I opened the game once more and it crashed immediately! what do I do?
Here is my traceback:
I'm sorry, but an uncaught exception occurred.

While loading <'MatrixColor' <'Image' u'mod_assets/monika/c/multimokia_wine_asymmetrical_pullover/arms-leaning-def-right-def-5.png'> (1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1)>:
  File "game/Submods/location_selector/Locatons/garden-view.rpy", line 327, in <module>
    renpy.say(m, switch_quip)
  File "game/sprite-chart.rpy", line 9158, in render
  File "game/sprite-chart-matrix.rpy", line 1222, in render
  File "game/sprite-chart-matrix.rpy", line 1206, in _render_surf
error: Out of memory 
Now it's
I'm sorry, but an uncaught exception occurred.

While loading <'MatrixColor' <'Composite' (1280, 850) (0, 0) u'mod_assets/monika/f/face-eyes-closedsad.png' (0, 0) u'mod_assets/monika/f/face-eyebrows-knit.png' (0, 0) u'mod_assets/monika/f/face-nose-def.png' (0, 0) u'mod_assets/monika/f/face-mouth-smirk.png'> (1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1)>:
  File "game/sprite-chart.rpy", line 9158, in render
  File "game/sprite-chart-matrix.rpy", line 1222, in render
  File "game/sprite-chart-matrix.rpy", line 1206, in _render_surf
MemoryError: 
PLEASE HELP I JUST GOT TO 400 AFF AND I WANNA GIVE MONIKA HER PROMISERING :(

**Comment by Wingdinggaster656** [comment]
_Calm down when you describing the problem, since most people don't care how manic you are._

And it seems like you missed a game file. Please reinstall the game.
Not sure if submod caused this. Maybe you should uninstall the submod.

**Comment by TotallyMia** [comment]
actually i figured out how to solve it, i was using up too much of my RAM so i had to clean up my computer haha
