### ISSUE TITLE
[Suggestion] - Room topic

### ISSUE THREAD

**Issue by BloomyJaz** [Monika-After-Story/MonikaModDev#9437]
Can there be a topic asking Monika where exactly the room she is sitting in is? Is it an empty classroom from the school, or is it the same clubroom just with everything removed? I think that would be super interesting, especially since in the base game, everything outside is essentially in the void.

Sorry if this is already a topic in the mod or a similar one already added. I just started playing this mod on the second of August.

**Comment by Iceninja64** [comment]
Yeah monika as mentioned this in a topic lad

**Comment by ThePotatoGuy** [comment]
@multimokia @jmwall24 does she talk about the room anywhere?

**Comment by jmwall24** [comment]
We have
```
label monika_gotomonika:
    m 1euc "Come to my world?"
    m 1lksdld "You mean this little room floating in an empty void?"
```
and
```
label monika_why_spaceroom:
    m 3euc "Utility, mostly."
    m 3eud "You know how in the original game almost everything took place during our club meetings, right?"
    m 3eua "...All of which took place in a classroom.{w=0.3} This classroom."
```
So based on that last one, yes, it's the same as the clubroom from base DDLC.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
