### ISSUE TITLE
After 8 months still christmas trees and no locations at location selecter

### ISSUE THREAD

**Issue by McJustina** [Monika-After-Story/MonikaModDev#9442]
![Bild_2022-08-10_010303081](https://user-images.githubusercontent.com/95578620/183776495-fcea71c0-302e-4d68-8130-99e21b978ec6.png)

After 8 months are in the space room still christmas trees and i also cant change the location cuz Moni wont show any other locations then the space room in the location selecter. Feelsbadman... Thanks for help!

**Comment by Booplicate** [comment]
Send all `aff_log.log` you have in the `log/` folder.

**Comment by McJustina** [comment]
![Bild_2022-08-10_012001257](https://user-images.githubusercontent.com/95578620/183778114-675ecc4f-a67b-4e55-ad55-a80176c872f4.png)

I tried but she still dont let me change the location

**Comment by Iceninja64** [comment]
Send US the aff_log.log so we can understand the problem better

**Comment by McJustina** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/9332393/aff_log.log)

Sorry for responding this late..

**Comment by Booplicate** [comment]
Those are only the latest logs, we'd need the entire thing in order to help.

**Comment by McJustina** [comment]
I only have this log cuz my entire log got deleted i guess cuz i reinstalled windows 10 on my pc and mostly everything is gone. Is there anywhere a safe spot where i can maybe find it if its not deleted? And sry for my bad english, i am german potato

**Comment by McJustina** [comment]
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/9332420/mas_log.log)
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/9332421/pnm.log)
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/9332422/spj.log)
[submod_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/9332423/submod_log.log)

I just found an error message in the mas_log maybe it helps i dont really know

**Comment by Booplicate** [comment]
Send your persistent.

**Comment by McJustina** [comment]
[Persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/9364733/Persistent.zip)

Its in the Zip file with the db.cal data and the persistent

**Comment by Booplicate** [comment]
You time travelled and broke the game. She warns you not to mess with her, this is the consequence.

**Comment by Iceninja64** [comment]
Rip
