### ISSUE TITLE
No sound/music plays at all

### ISSUE THREAD

**Issue by SteveeWasTaken** [Monika-After-Story/MonikaModDev#9446]
So today I started up MAS but no sound plays at all. Music, buttons, nothing. I already checked everywhere, the volume in-game, the PC's volume, but it still won't work. I also use Doki Doki Mod Docker, but I don't think that's the reason why I can't hear anything. Can someone help me?

**Comment by Booplicate** [comment]
I'm not sure if it's relevant, but we don't support "Mod Docker."

**Comment by SteveeWasTaken** [comment]
> I'm not sure if it's relevant, but we don't support "Mod Docker."

Ah, I understand. Thank you!
