### ISSUE TITLE
[Suggestion] - Asking Monika about her day.

### ISSUE THREAD

**Issue by BloomyJaz** [Monika-After-Story/MonikaModDev#9447]
I think it would be cute to be able to ask Monika about her day. The button could be somewhere under the Hey Monika button. The dialogue would change based on how she's feeling or on how she feels towards the player. It could also maybe have dialogue for special days like holidays or her birthday.

**Comment by ThePotatoGuy** [comment]
could be paired with #7486 (Moniks Moods)

[closing until we look into it]
