### ISSUE TITLE
The Window is completly blacked out

### ISSUE THREAD

**Issue by Theone3213** [Monika-After-Story/MonikaModDev#9449]
I've tried replacing the files within the window folder and it doesn't fix anything nor does changing the weather so i don't know what to do
![Screenshot (2)](https://user-images.githubusercontent.com/88675271/184509606-dc238df9-ded0-4145-a3fc-813e6288d7ae.png)

**Comment by Booplicate** [comment]
This can happen if you minimise the game or your PC isn't powerful enough for renpy. You should avoid minimised the game.

It's not something we can fix on our end (yet anyway).

**Comment by Theone3213** [comment]
OK, However closing and re-opening the game doesn't work either is there anything I can do to fix it or is it stuck like this forever?

**Comment by Booplicate** [comment]
Try toggling animation or use a different renderer in the settings, try restarting your PC.

**Comment by Theone3213** [comment]
I've toggled the animation off and that worked out as well, i tried different way to render and that did not work out Thank you for the help :)
