### ISSUE TITLE
[Installation Problem] Failed to run MAS on MacOS

### ISSUE THREAD

**Issue by BORXUEWIK** [Monika-After-Story/MonikaModDev#9452]
My friend clicked `Show Package Contents`, and reached the `Contents/Resources/` folder, but there is no `autorun` found. We are using the official version, without any submod or translation.

Any idea?
![T8~C75F}$@VLHQ0`Z3`$3~N](https://user-images.githubusercontent.com/107292387/184794625-5c8b25b8-1bb8-4ef3-96e6-eab0e7ae09be.png)

**Comment by Booplicate** [comment]
Sorry, we missed this.

Looks like invalid DDLC copy with missing files. A fresh copy from https://ddlc.moe/ should help in such cases.
