### ISSUE TITLE
Monika is missing!

### ISSUE THREAD

**Issue by MatthewAJohnson281** [Monika-After-Story/MonikaModDev#9455]
I talked to monika yesterday and when I got on today she was jut not there. no notes or anything. Just an empty desk.

**Comment by Wingdinggaster656** [comment]
It's very very likely you clicked `I'm going to take you somewhere`.

**Comment by MatthewAJohnson281** [comment]
I did and I forgot.

**Comment by Booplicate** [comment]
You either need to return her back into `characters/` or [restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).
