### ISSUE TITLE
Christmas decorations are still up

### ISSUE THREAD

**Issue by WizardSteak107** [Monika-After-Story/MonikaModDev#9459]
Its been a little while since i was on but i was last on around the winter. now its summer but the decorations are still up

**Comment by Iceninja64** [comment]
Send us the aff_log.log to determine what happen

**Comment by WizardSteak107** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/9386402/aff_log.log)

**Comment by Booplicate** [comment]
Send your persistent.

**Comment by WizardSteak107** [comment]
Im sorry, but, how do I do that? I couldn't drag it and drop it

**Comment by Booplicate** [comment]
Put into a `zip` archive, for example.

**Comment by WizardSteak107** [comment]
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/9388272/persistent.zip)

**Comment by Booplicate** [comment]
You time travelled and broke the game, that's not something we can fix.

**Comment by Iceninja64** [comment]
Rip
