### ISSUE TITLE
i tried to install a nou skin and got this error

### ISSUE THREAD

**Issue by PanickingPanini** [Monika-After-Story/MonikaModDev#9460]
![Screenshot 2022-08-20 at 3 03 55 PM](https://user-images.githubusercontent.com/111630415/185733627-6b252afd-43ab-4797-b2fa-bca8c5ac0e28.png)
 
 i replaced the nou file with the nou skin file and this happened and idk how to fix this

**Comment by SomeFellowBrowser** [comment]
Make sure to check the NOU files and the skin files, if the NOU files had SFX file, and the skin doesn't, make sure to add the SFX file from the original NOU files, this happened to me before

**Comment by PanickingPanini** [comment]
well the problem now is i dont have the original nou file anymore and i dont have a backup of it- since i just got nou yesterday

**Comment by PanickingPanini** [comment]
> Make sure to check the NOU files and the skin files, if the NOU files had SFX file, and the skin doesn't, make sure to add the SFX file from the original NOU files, this happened to me before, I used sfx as a reference but it could be another missing file

well the problem now is i dont have the original nou file anymore and i dont have a backup of it- since i just got nou yesterday

**Comment by SomeFellowBrowser** [comment]
Want me to send a drive link to the original NOU files?

**Comment by PanickingPanini** [comment]
> Want me to send a drive link to the original NOU files?

would love it if you do please :')

**Comment by SomeFellowBrowser** [comment]
> 

It'll take a moment since I forgot to update my google drives MAS file so I can't just extract the NOU files easily since there is none _;v;_

**Comment by PanickingPanini** [comment]
its fine, you can take your time dsjndgkjdfg

**Comment by SomeFellowBrowser** [comment]
> its fine, you can take your time dsjndgkjdfg

https://drive.google.com/drive/folders/13lpkjND4Otqh_FIvJgvAK_ow360FpjrF?usp=sharing
My PC is real laggy today, also I reread this while it was loading, since I'm new I looked real shady Dx

**Comment by PanickingPanini** [comment]
it worked, thanks a lot for your help :D

**Comment by SomeFellowBrowser** [comment]
> it worked, thanks a lot for your help :D

No problem it was nearly the same error I got when it happened to me, _I don't know why spritepacks don't add the SFX file_

**Comment by PanickingPanini** [comment]
i'll keep that in mind next time when i install those lol
