### ISSUE TITLE
[BUG] NOU game

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#9464]
![screenshot0028](https://user-images.githubusercontent.com/88768397/185797194-ddbd1de9-7ad1-4178-82a5-a6f5f7aa4718.png)
![screenshot0029](https://user-images.githubusercontent.com/88768397/185797195-7252fccb-1275-4400-b9bf-d0028e1836c9.png)
I had 2 cards left and I couldn't say NOU.

**Comment by Booplicate** [comment]
Did you say nou before?

**Comment by Ulti70895** [comment]
Oh yeah, I did do the things you said, thank you.
