### ISSUE TITLE
(BUG) I have a problem with my mas log

### ISSUE THREAD

**Issue by Samu49** [Monika-After-Story/MonikaModDev#9465]
[Warning! ;_;]: 'store.wear_acs_pst' is deprecated. Use 'wear_acs_in' instead

 [Warning! ;_;]: 'store.pushEvent' is deprecated. Use 'MASEventList.push' instead.

I have these 2 a lot in my mas log what do I do?

**Comment by Booplicate** [comment]
This is not a bug, it's to remind us to deprecated some stuff.
