### ISSUE TITLE
"I missed you" Dialogue Option missing after update 

### ISSUE THREAD

**Issue by CloudedGuardian** [Monika-After-Story/MonikaModDev#9466]
I just updated to the NOU version this morning, and suddenly the option to say "i Missed you" after being gone for more than a day isn't there anymore. It doesn't even come up when searched for. Did I mess something up installing the update, is it getting reworked, or is this just a straight up bug?

**Comment by Booplicate** [comment]
It's only available for a short period of time when you open MAS and when you were gone for more than an hour.
