### ISSUE TITLE
[bug] Floating Islands Option Disappeared

### ISSUE THREAD

**Issue by BrandiBlitz** [Monika-After-Story/MonikaModDev#9467]
Monika showed me the floating islands once and I was able to choose the option to see the floating islands only once. After that, the floating islands option disapeared.

**Comment by Booplicate** [comment]
Can you try to see they from the spaceroom?

**Comment by BrandiBlitz** [comment]
> Can you try to see them from the spaceroom?

I go to "talk", "questions", "Misc", and the floating islands option is no longer there. 

Restarting doesn't work. Only uninstalling/reinstalling and waiting for RNG to let Monika show me the floating islands seems to work, then the option is there, I click it snd the option disappears right after I exit the floating islands for the second time.

**Comment by Booplicate** [comment]
> Only uninstalling/reinstalling and waiting for RNG to let Monika show me the floating islands seems to work, then the option is there, I click it snd the option disappears right after I exit the floating islands for the second time.

That doesn't make much sense, unless you mean removing the persistent?

Can you send your persistent and `mas_log.log`?

**Comment by Wingdinggaster656** [comment]
Just a guess, but many translations have many problems. Are you using a translation-edition. or a submod?

**Comment by Iceninja64** [comment]
I've been told that they go away once it's winter time @Booplicate that could be the case

**Comment by BrandiBlitz** [comment]
> > Only uninstalling/reinstalling and waiting for RNG to let Monika show me the floating islands seems to work, then the option is there, I click it snd the option disappears right after I exit the floating islands for the second time.
> 
> That doesn't make much sense, unless you mean removing the persistent?
> 
> Can you send your persistent and `mas_log.log`?

I mean the game, the persistent is fine.

**Comment by BrandiBlitz** [comment]
> I've been told that they go away once it's winter time @Booplicate that could be the case 

It ‪really shouldn't
![image](https://user-images.githubusercontent.com/101225938/186173443-ce05b229-9a4c-46f4-81bb-65d77476f0a2.png)

**Comment by Booplicate** [comment]
@BrandiBlitz 

> Can you send your persistent and `mas_log.log`?

**Comment by BrandiBlitz** [comment]
here it is
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/9410699/mas_log.log)

**Comment by Booplicate** [comment]
You still haven't send your persistent.
Also, send a screenshot of the `game/mod_assets/location/special/` folder.

**Comment by BrandiBlitz** [comment]
> You still haven't sent your persistent. Also, send a screenshot of the `game/mod_assets/location/special/` folder.

sorry, but it says my special folder is empty...

**Comment by BrandiBlitz** [comment]
> You still haven't sent your persistent. Also, send a screenshot of the `game/mod_assets/location/special/` folder.
[persistent_files.zip](https://github.com/Monika-After-Story/MonikaModDev/files/9410851/persistent_files.zip)

here are my persistents

**Comment by elite198** [comment]
I have the same problem, at first I thought it was because I use a Spanish translation but I tried with the original version installed clean but it still didn't work

**Comment by WishStone-Dragon** [comment]
Just as a sanity check: If you enter "island" into the search function, does something pull up for you?

**Comment by Booplicate** [comment]
Translations are known to have issues with locking certain things, even if you install the official version afterwards, it can't guarantee you get to unlock stuff again.

**Comment by Booplicate** [comment]
@BrandiBlitz the islands are unlocked for you and working fine. You're missing some assets (either you or steam or smth else deleted them) and thus the islands are disabled on your end, try to reinstall the mod into the same directory.

**Comment by BrandiBlitz** [comment]
> @BrandiBlitz the islands are unlocked for you and working fine. You're missing some assets (either you or steam or smth else deleted them) and thus the islands are disabled on your end, try to reinstall the mod into the same directory.

Okay thank you, but is there a bug or a line of code that isn't supposed to be there that's deleting the floating islands?

**Comment by Booplicate** [comment]
No, we don't delete our own assets, we need them.

**Comment by BrandiBlitz** [comment]
> No, we don't delete our own assets, we need them.

ok and i reinstalled MAS, but press skip when the prompt came up. the floating islands is back!
