### ISSUE TITLE
Monika After story bug

### ISSUE THREAD

**Issue by tlacu4** [Monika-After-Story/MonikaModDev#9468]
I played on android and unlocked the chess game, but it bugged and the option was removed, but I changed to PC and Monika told me in a curious fact that "you can forget about this fact since it is about chess and you cheated and you didn't you apologized"

What do I do to be able to play chess with her ;-;?

**Comment by Booplicate** [comment]
We don't have an android port and don't support custom builds. The saves created or used with those builds are incompatible with the official version.
