### ISSUE TITLE
MAS submod plugin bug

### ISSUE THREAD

**Issue by BrandiBlitz** [Monika-After-Story/MonikaModDev#9473]
Whenever I update a submod, I noticed that it installs the latest versions, but does not delete the old versions of said Submods and thus, breaking the game on startup.

**Comment by BrandiBlitz** [comment]
In addition, I get confused on which is the latest version, since when it is downloaded, the version number is not displayed

**Comment by Booplicate** [comment]
Report that in the submod repository.
