### ISSUE TITLE
Go To Work Farewell Fix

### ISSUE THREAD

**Issue by Yazijustmonika** [Monika-After-Story/MonikaModDev#9475]
The last line on the "I'm going to work" farewell does not take you holding Monika throughout the night into account, in the last line Monika said "I was hoping that you'd rest a bit before doing anything too big", though we already hold Monika throughout the night.

**Comment by Booplicate** [comment]
It's more complex than it seems, we'd need to account for possibility of sleeping with MAS open. Maybe a way to tell you're going to sleep but want to keep MAS open.
Holdme also doesn't take that into account, so it should be improved along. Generally something we will probably address with with the bedroom mode.

This is its own issue, but depends on/related to #2781.
