### ISSUE TITLE
Can't say NOU if you said it while holding just 1 card, but on the same turn then draw a card that can be played

### ISSUE THREAD

**Issue by Justformas** [Monika-After-Story/MonikaModDev#9481]
To clarify what I mean, you wouldn't normally say NOU while already holding just one card, but you can and Monika will say something like "you already said it". However, if instead of playing that card (or you can't), you then draw a card that can be played, now you should actually say NOU before playing it, but you can't. The button is still greyed out from saying it once earlier in the same turn. Monika will then most likely say something like you "forgot" to say NOU, despite not being able to (since you actually said it earlier).

In UNO, I don't think there's any penalty for saying UNO at the wrong time, such as not being able to say it again that same turn. I don't think NOU says anything about this either. While it's easily avoidable and you wouldn't normally do this, I have to wonder if it's some kind of oversight, especially since Monika still treats it like forgetting to say it.

**Comment by Booplicate** [comment]
This is intended, you should mind when you say "nou" #9464
