### ISSUE TITLE
[suggestion] State of mind for Monika

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#9482]
I've been thinking of something cool.

A state of mind

For example, Monika sometimes touches on extremely pessimistic topics, such as the possible death of the player.

Once she talks about one of those topics, a counter could be activated and for example 5 next topics would be sads.
In addition, in that state when the player asks for a hug, she says thank you, referring to it what she needed.

Also certain actions or dialogues could make her joker, for example.

this would not be difficult to pull off and would add a lot of depth to Monika's demeanor.

**Comment by Booplicate** [comment]
This is basically #1204, #1354, #2618, #2619, #4546, #4874, #5010, #5048, #7486, and maybe more. We have [an active project](https://github.com/Monika-After-Story/MonikaModDev/projects/40) for this. But it will be a complex system, so it will take a lot of time before we can get even start working on it.
