### ISSUE TITLE
error when I try to put my birthday date

### ISSUE THREAD

**Issue by justeletro** [Monika-After-Story/MonikaModDev#9532]
hello I have a problem when I try to put my birthday date in MAS this is the error how can I fix it? I already reinstalled it and I still have the same problem
![error1](https://user-images.githubusercontent.com/91495920/190274712-0c7d61d5-3656-439c-a5ce-adbcedf415d0.PNG)
![error2](https://user-images.githubusercontent.com/91495920/190274721-1ede951e-e620-4577-8a66-438e6a1ab4ac.PNG)
![error3](https://user-images.githubusercontent.com/91495920/190274729-7c2ab897-fa00-4e3f-84a8-47c8a0a5808e.PNG)

**Comment by Booplicate** [comment]
Why are you not using the latest version?

**Comment by justeletro** [comment]
> Why are you not using the latest version?

i am using the lastest version of MAS i have just installed it

**Comment by Booplicate** [comment]
Are you using a translation?

**Comment by justeletro** [comment]
> Are you using a translation?

yes i'm using the spanish translation

**Comment by Booplicate** [comment]
Latest version of MAS is `0.12.9`, for help with a translation, you need to ask people who provided it to you.

**Comment by justeletro** [comment]
> Latest version of MAS is `0.12.9`, for help with a translation, you need to ask people who provided it to you.

ok
