### ISSUE TITLE
[Suggestion] - Dizzy Monika when shaking window.

### ISSUE THREAD

**Issue by RuderLaplace** [Monika-After-Story/MonikaModDev#9537]
Pretty much is just that.
A dizzy face and a couple of lines about how much that disturbs her and asking to not doing that, plus an appropiate "I'm sorry..." entry (and maybe aff_loss after the first time) when shaking the game window.

When I saw pointer tracking I thought about interacting from outside the game.
I see some difficulties here, though.
Calculating speed, time being moving at (whatever it could be considered as) "high" speed, counter reset if mouse stopped for "too long"...
But you may know about this more than me.

And, if you have enough time, perhaps a quick animation sliding the desk horizontally.

Probably nobody has a reason to do that on pourpose.
But with 2 monitors I move the window "very" often, so it clicked in my mind to try that right after discovering her eye-tracking.

**Comment by Booplicate** [comment]
Would be cool, although should thought-out how to detect this and avoid triggering when just slowly moving around.
#6326
