### ISSUE TITLE
[Suggestion] - """Shazam""" custom_bgm for a Hibikase reaction.

### ISSUE THREAD

**Issue by RuderLaplace** [Monika-After-Story/MonikaModDev#9538]
When Monika said she likes a song (Hibikase) I instantly thought there may be a reaction for playing it.
I don't know how much complex could be to (offline-ly) identify that song pattern.
I assume the game fully runs without ussing internet. Is it?

**Comment by Booplicate** [comment]
Similar to #5926 #6787

I'm going to reject this too. Analysing audio is not a trivial task and it's out of scope of our project. It's not really feasible to react to any song just by its metadata, but reacting to something specific might be possible (it was suggested before).
