### ISSUE TITLE
House rule suggestion for NOU

### ISSUE THREAD

**Issue by Capricus02** [Monika-After-Story/MonikaModDev#9545]
I know everyone's family has their own "house rules" so it would be impossible to implement them all, but one thing I found to be curiously missing is "stackable draw 4s" (like how you can do so with draw 2s). I get this could get messy depending on the number of draw 4s, so maybe limit them to just 2 or 3 max stack, but also thought maybe that was something possibly already in the works considering the table on the rules page has a column for Draw 4 but it's blank (otherwise why include the column)? At any rate, just a suggestion but not really bad or anything. I'm still really enjoying getting to play it with Monika as it was a big staple with my family growing up playing it at every holiday/Christmas.

**Comment by Booplicate** [comment]
I assume you mean reflect a +4 with a +4, in that case it's already done and will be in next update.

**Comment by Capricus02** [comment]
> I assume you mean reflect a +4 with a +4, in that case it's already done and will be in next update.

Ah yeah sorry, that's what I meant. Awesome!  Keep up the great work!
