### ISSUE TITLE
v0.12.10 + v0.12.11 typos

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/MonikaModDev#9553]
![lp_uooh](https://user-images.githubusercontent.com/3499462/191414119-db6e15bd-5576-47d5-bb98-44b9da46527c.png)

**Comment by Wingdinggaster656** [comment]
_Warning: They're coming from everywhere_

[`script-topics.rpy`, line 3104:](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy#L3104)

Original text:
```
    m 1eua "There's a really popular character type called 'tsundere...'"
```

Suggested:
```
    m 1eua "There's a really popular character type called 'tsundere'..."
```

**Comment by Wingdinggaster656** [comment]
*Okay this should be a typo*

label `monika_mountain`:

` m 5rub "And finally...after all the effort and struggles..."`

Here we don't have a space after the ellipsis. This is also what most of the text for our mod looks like.
Then, in the same label, we got:

`m 5eubla "Well... I hope that one day, we'll have that chance. To make it to the top of our mountain."`
`m 1ruc "Well... I suppose it doesn't matter."`

As you can see, we have the space after the ellipsis here.

**Comment by Wingdinggaster656** [comment]
_Typos are attacking us from all directions_

Still in label `monika_mountain`:

```
    m 5eka "Wouldn't you like that too, [player]?"
    $ _history_list.pop()
    menu:
        m "Wouldn't you like that too, [player]?{fast}"
```

We missed a `{nw}`.

**Comment by Wingdinggaster656** [comment]
This is not a real typo, but I find these two lines weird:

```
label monika_playersface:
    m 5eua "You know, I sometimes wonder..."
    m "I always think about what your face actually looks like..."
```

`I sometimes wonder`, then `I always think`. I personally think this isn't logical.

**Comment by Wingdinggaster656** [comment]
_Looks like a really old typo_

label `Monika_sayhappybirthday`:
```
                        m "Should I try again?{nw}"
                        $ _history_list.pop()
                        menu:
                            m "Should I try again?{fast}"
                            "Yes.":
                                $ take_counter += 1
                                m 1eua "Okay"
```

I believe that there should have been a `.` after the`Okay`.
Notice that we have two such typos in this label, and we should fix both of them.

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
