### ISSUE TITLE
I'm scared of this...

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#9556]
Is it safer to manually install the updates, or the installer?
I don't want this to be all messed up...

**Comment by dreamscached** [comment]
Install updates with in-game updater.

**Comment by hlepnamingblyat** [comment]
> Install updates with in-game updater.


Even if Monika tells me to do it manually because of steam?

**Comment by Booplicate** [comment]
[Don't use steam](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build).
Updater is the most preferable way, then installer, then manually if nothing else works.
