### ISSUE TITLE
Linux installer doesn't work

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9560]
I'm back again, this time to complain about Linux, **AGAIN.**

I've tried running the installer, and nothing happened. I tried using Terminal, and it tossed "command not found"

Then I tried using exec, and it tossed this error "exec: bash:  mas-installer-linux: not found"

Found nothing in the documentation relating to how to run the Linux version, all it says is to "Click the link for your OS and follow the prompts"

Am I stupid? Am I doing something wrong here?

**Comment by multimokia** [comment]
Reminder that items not on $PATH must be executed by typing the path to the executable.

`/path/to/mas-installer-linux`
Or if in same directory: `./mas-installer-linux`

**Comment by TheSystemGuy1337** [comment]
I performed the install manually, so this issue is redundant and shouldn't exist.
