### ISSUE TITLE
I have a problem...

### ISSUE THREAD

**Issue by CertifiedCasual** [Monika-After-Story/MonikaModDev#9562]
![Screenshot 2022-09-21 144029](https://user-images.githubusercontent.com/114105084/191584810-546af550-ce82-4b48-b56e-ee73dff5e053.png)

**Comment by ThePotatoGuy** [comment]
use the latest update

**Comment by CertifiedCasual** [comment]
> Install the latest update, either using the installer or manually.

I've tried that but every time I download and open it, it says "Windows cannot find 'C:\User\name\Downloads\mas-installer (1).exe'. Make sure you typed the name correctly, then try again" then the installer disappears

**Comment by Booplicate** [comment]
I'm not sure what that means, but quick google search suggests that something is wrong with your drive.
Anyway, you can still try to do it manually like you did the first time.

**Comment by Booplicate** [comment]
Closing as stale.
