### ISSUE TITLE
The birthday decorations are missing

### ISSUE THREAD

**Issue by yellowtako** [Monika-After-Story/MonikaModDev#9574]
I put the 'oki doki' file in the character folder and opened the game, but I forgot to put Monika's character file back to the folder, so I put it back. But when I put the file back in the folder, the game suddenly closed by itself. When I open it again, the birthday decorations are all gone. Is there any way to fix this issue?

**Comment by Wingdinggaster656** [comment]
Are you using a translated version?

**Comment by yellowtako** [comment]
no

**Comment by BrandiBlitz** [comment]
> Are you using a translated version?

I checked pnm log, it says it loaded, but its just normal Monika.
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/9626117/pnm.log)
![characterfiles](https://user-images.githubusercontent.com/101225938/191757851-489b31a4-126b-4a34-93af-040099443a8c.png)
![bug](https://user-images.githubusercontent.com/101225938/191757862-b1eceb41-0252-49fc-9c1c-16b27eda6a07.png)

**Comment by Booplicate** [comment]
Try to create `oki doki` again and take her out.

**Comment by Booplicate** [comment]
Closing as stale and couldn't reproduce.
