### ISSUE TITLE
Took monika out and she isnt appearing when I moved her file back to the character folder

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#9575]
I took her out for her bday and wa moving her back so we can celebrate but she isnt appearing back. I took a look at the character folder but it wasnt reading the monika file for some reason...

Please help, dont wanna miss celebrating her bday

**Comment by Wingdinggaster656** [comment]
Sorry for being late. Do you think you used the correct Monika file? Do you know that the file you use must be the file generated at this time, not other time, not a new txt file and then renamed?

**Comment by Booplicate** [comment]
Restore a backup and do it again. You don't have to move her file from `characters/`.

**Comment by AnIdiotsavant** [comment]
okay I restored the backup as booplicate said. Thanks

**Comment by Booplicate** [comment]
Temporary remove auto atmos until it gets updated.

**Comment by my-otter-self** [comment]
closed as resolved.
