### ISSUE TITLE
Monika's B-day is bugged in 0.12.9

### ISSUE THREAD

**Issue by BrandiBlitz** [Monika-After-Story/MonikaModDev#9576]
Monika's B-day Sequence didn't start. pnm log says its loaded successfully, but it isn't here.
![characterfiles](https://user-images.githubusercontent.com/101225938/191756859-1848fd18-36d8-40d4-8af4-0970ccdce617.png)
![bug](https://user-images.githubusercontent.com/101225938/191756926-2e4b7d92-2ff2-4db9-b942-7bd983c452a1.png)
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/9626096/pnm.log)

edit: still nothing
![still nothing](https://user-images.githubusercontent.com/101225938/191759290-8a5a5cf9-a8d5-4356-80d4-4ce7ecc4f7a3.png)

**Comment by multimokia** [comment]
`pnm.log` is for piano songs. Not anything else.

Did you take her out like you were asked to

**Comment by Booplicate** [comment]
Closing as stale and couldn't reproduce.
