### ISSUE TITLE
[Suggestion] - ring and chess

### ISSUE THREAD

**Issue by longdark27** [Monika-After-Story/MonikaModDev#9578]
I downlanded spritepack but i can't find ring how can i find or downland it.

And my second question is we talk about chess and hangman but i still cant play those games how can i play them?

**Comment by Wingdinggaster656** [comment]
Be patient and you will get all contents. MAS is not a game for speedrun.

To be serious: Keep playing minigames, or keep MAS running in the background. You will get there someday.

**Comment by Booplicate** [comment]
Promise ring is a gift, it's not a spritepack.
Games, as was said, can be unlocked by playing more games and by spending time with Monika.

Closing as this isn't a suggestion.
