### ISSUE TITLE
Spoilers in regards to future events

### ISSUE THREAD

**Issue by CrocandCo** [Monika-After-Story/MonikaModDev#9579]
To maintain obscurity, I will try to be vague as possible.

There seems to be an outfit that is visually interesting that is themed for an upcoming event.
Is there a requirement to get this outfit, because I cannot seem to gift it.

**Comment by Justformas** [comment]
There are outfits for special events that can't be gifted and you have to wait to for the event to see it.

**Comment by CrocandCo** [comment]
I will consider this as information from a contributor.

**Comment by Justformas** [comment]
I will consider that a complement.
