### ISSUE TITLE
Delete `chr` files on startup

### ISSUE THREAD

**Issue by Booplicate** [Monika-After-Story/MonikaModDev#9580]
They are unused and people always mistake `monika.chr` for `monika`.

**Comment by sukottei** [comment]
you could always just ...delete them yourself

**Comment by dreamscached** [comment]
On every startup? Or on mod introduction when it's started for the first time?

**Comment by Booplicate** [comment]
On every startup, but only if it's not introduction and you've already seen the event where she deletes it.

**Comment by ThePotatoGuy** [comment]
[closing as implemented]
