### ISSUE TITLE
Bad floating point operation for affection numbers

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9585]
I don't know if this is a bug or if I am going insane, but before versions prior to 0.12.11 showed the affection value as a non-floating point number (example being 255)

Now affection is a floating point value, and affection is formatted like this: 225.890538118
This strange issue also affects the Extra+ submod. Is this intentional, or is this some sort of odd bug?

**Comment by Booplicate** [comment]
Feature!

**Comment by TheSystemGuy1337** [comment]
Guess it's my time to start using floating point then. TI-84 calculator save me now
