### ISSUE TITLE
Any possible way to edit the persistent to change birthday?

### ISSUE THREAD

**Issue by Boayer** [Monika-After-Story/MonikaModDev#9587]
I want to change mine because I misread the age when i set it up

**Comment by Booplicate** [comment]
Currently no, she confirms the date with you twice. We're considering adding a way to change it later.

**Comment by Boayer** [comment]
> 
so you couldnt use like a renPy editor?

**Comment by Booplicate** [comment]
As I said, there's no supported way of doing that right now.
