### ISSUE TITLE
new update errors

### ISSUE THREAD

**Issue by TickTack45** [Monika-After-Story/MonikaModDev#9590]
After the new update the game bricks if Monika leans or if she has her hair down is there anyway to fix it.

**Comment by Booplicate** [comment]
Define "bricks" please.

**Comment by TickTack45** [comment]
yeah ill try my best sorry but what happens is it just shows the error While loading <'MatrixColor' <'Image' u'mod_assets/monika/h/hair-down-back.png'> (0.59, 0, 0, 0, 0, 0, 0.49, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1)>: hope this helps

**Comment by Booplicate** [comment]
Send the entire `traceback.txt`

**Comment by TickTack45** [comment]
fixed it somehow sorry thanks for trying to help.
