### ISSUE TITLE
How to Check Affection in game

### ISSUE THREAD

**Issue by epsseniyer** [Monika-After-Story/MonikaModDev#9621]
im beginner i dont know anything :(

**Comment by Wingdinggaster656** [comment]
No, there isn't a way to check affection in the actual gameplay.

The way to check affection is through debug log. You could find the log file in `<DDLC Directory Here>\log\aff_log.log`. However, it's highly unrecommended to check affection, and that log is just for developers.

**Comment by sukottei** [comment]
you can also install the extra+ mod which in my opinion is way easier (u can find it on reddit)

**Comment by my-otter-self** [comment]
closed as resolved/question replied.
