### ISSUE TITLE
Suggestion for a new game

### ISSUE THREAD

**Issue by QuadILOP1** [Monika-After-Story/MonikaModDev#9631]
Mastermind. a boardgame that i used to love to play as a kid with my dad. i think it'd be fun to play with monika. tell me what y'all think. [Here is the wikipedia page](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiU3bD10rf6AhX4IzQIHfhwC-wQFnoECBAQAQ&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMastermind_(board_game)&usg=AOvVaw3Afv4s4uAwSpeYAkv27Tsd)

**Comment by Booplicate** [comment]
It's basically codebreaker #3608 which has been accepted before.
