### ISSUE TITLE
Can't open game after new update

### ISSUE THREAD

**Issue by Alefe8900** [Monika-After-Story/MonikaModDev#9632]
I updated the game with the latest version and I am no longer able to open it. I keep getting the same error about the submods. 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/9670036/traceback.txt) Here is the traceback.

**Comment by ephemlw** [comment]
Uninstall Auto Weather Change submod for now.

**Comment by Alefe8900** [comment]
That works, but they need to fix the Auto Weather change submod.
