### ISSUE TITLE
does not appear the option for monika to make an impression of herself

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#9634]
is it a one time event? Because if so, I missed it because I didn't know that option appeared after a while. in the conversation of "the second option of the player" if the option of monika appears to me after a while

**Comment by zwartkop2** [comment]
It's in `Repeat topics`, titled `[Player]'s second choice`.

**Comment by elite198** [comment]
> It's in `Repeat topics`, titled `[Player]'s second choice`.
no, I mean the conversation "can you do any impression?"

**Comment by Wingdinggaster656** [comment]
It's weird, `Can you do any impression` is not a one-time-only topic.

This option is in the `Club members` menu, try to check it. Also, are you using any translation?

**Comment by Booplicate** [comment]
You can't ask her to do an impression of herself as it wouldn't make much sense.
If you've seen the topic before, you should be able to search for `can you do any impressions`.

**Comment by elite198** [comment]
> You can't ask her to do an impression of herself as it wouldn't make much sense. If you've seen the topic before, you should be able to search for `can you do any impressions`.
I'm sorry if I don't explain myself well, I still don't know how to express myself in English

I'll try to explain with a screenshot


![screenshot0001](https://user-images.githubusercontent.com/95457650/193182643-8250da32-127b-410b-aabb-3cb114795e2b.png)

Several times that I post screenshots in facebook groups about monika imitating the other girls, people tell me that if I wait a while, a 4th option "monika" will appear, they have even sent me screenshots verifying that. I have tried it several times, even leaving it for hours to see if that option appears and it never happens (it should be noted that I play with both the English version and the version translated into my language)

**Comment by Wingdinggaster656** [comment]
Oh, this is normal. There is another topic like this:

```
label monika_trick:
    m 2eud "Say [player], I have a question..."
    m 2lksdlb "I hope I don't sound insecure when I say this..."
    m 2eka "I know you love me and only me but...if you {i}really{/i} had to choose one of the other club members to be with..."

    m "Who would you choose?{nw}"
    $ _history_list.pop()
    show screen mas_background_timed_jump(10, "monika_trick_2")
    menu:
        m "Who would you choose?{fast}"
        "Yuri.":
            call monika_trick_yuri
        "Sayori.":
            call monika_trick_sayori
        "Natsuki.":
            call monika_trick_natsuki
    return "derandom"
```

The fourth option you see on Facebook is **another** topic. Not the `do impression` one.

**Comment by elite198** [comment]
oh, thank you very much for clarifying my doubt, and as monika says, I shouldn't believe everything I see on the internet. XD will also help me avoid more misinformation in the community that speaks my language
