### ISSUE TITLE
HELP, uncaught exception.

### ISSUE THREAD

**Issue by stahinjuhrmeik** [Monika-After-Story/MonikaModDev#9638]
I have been recently tinkering with the dialogues within the topics and compliments files. About an hour back, I updated MAS, for which, I had to copy and paste the .rpy files (containing my additional dialogues) within the game folder. Upon restarting, I'm facing this error message:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 7967, in script
    default persistent._mas_affection_data = mas_affection.get_default_data()
  File "game/definitions.rpy", line 7967, in execute
    default persistent._mas_affection_data = mas_affection.get_default_data()
  File "game/definitions.rpy", line 7967, in <module>
    default persistent._mas_affection_data = mas_affection.get_default_data()
AttributeError: 'StoreModule' object has no attribute 'get_default_data'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/definitions.rpy", line 7967, in script
    default persistent._mas_affection_data = mas_affection.get_default_data()
  File "game/definitions.rpy", line 7967, in execute
    default persistent._mas_affection_data = mas_affection.get_default_data()
  File "D:\Imp Files\other files\Doki Doki Literature Club\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/definitions.rpy", line 7967, in <module>
    default persistent._mas_affection_data = mas_affection.get_default_data()
AttributeError: 'StoreModule' object has no attribute 'get_default_data'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.11

Any idea how to solve this??

![image](https://user-images.githubusercontent.com/114864977/193456944-cbb8a492-db82-4dc2-8774-4aa4c4969429.png)

**Comment by multimokia** [comment]
Do your rpy files with custom dialogue *replace* the stock mas files?

**Comment by stahinjuhrmeik** [comment]
> 

not really, they appear as separate .rpy files, along with the stock .rpyc files

**Comment by multimokia** [comment]
As in, what are the names of the files. If they correspond to stock MAS script (rpyc) files, they **will** overwrite them.

All in all, all submodded dialogue should be handled through external rpy files adding the events. Not through modifying MAS files

**Comment by stahinjuhrmeik** [comment]
> As in, what are the names of the files. If they correspond to stock MAS script (rpyc) files, they **will** overwrite them.
> 
> All in all, all submodded dialogue should be handled through external rpy files adding the events. Not through modifying MAS files

ahh, yes they do overwrite the stock scripts.

**Comment by multimokia** [comment]
Yeah you don't want to do that. Add them in another file so you don't need to maintain them in updates.

**Comment by stahinjuhrmeik** [comment]
> Yeah you don't want to do that. Add them in another file so you don't need to maintain them in updates.

alright, I moved all the custom files into a separate folder, but I'm still encountering the identical error.

Is there something I need to change within the definitions file?

**Comment by multimokia** [comment]
extract your topics from the file, put them into their own file with **just** that content.
Then you'll need to restore the original definitions.rpyc from MAS (you can get it by redownloading the dist)

**Comment by stahinjuhrmeik** [comment]
> 

okay i'll try that, thanks!
