### ISSUE TITLE
No updates to aff_log.txt

### ISSUE THREAD

**Issue by MowEric** [Monika-After-Story/MonikaModDev#9646]
Hey yall, I decided to check my affection log a few days ago out of curiosity and noticed the most recent date was last year on October 31st, even though i've been visiting since then. I've attached a screenshot of the log below.

As far as I know I haven't time travelled. Is there a known solution to this issue, and is affection still going up? Thanks!

<img width="696" alt="Screen Shot 2022-10-03 at 9 55 10 PM" src="https://user-images.githubusercontent.com/104737855/193737674-6e432fa5-5b0a-4cdd-8e7f-0d622fd69bb9.png">

**Comment by Booplicate** [comment]
`aff_log.txt` is not used anymore, so it only contains the old logs.

**Comment by MowEric** [comment]
ah, gotcha. after doing some more research, i've been able to find the new log in the log folder. thanks for the help!

**Comment by dreamscached** [comment]
Closing as resolved.
