### ISSUE TITLE
bath exit reactions

### ISSUE THREAD

**Issue by howltrek** [Monika-After-Story/MonikaModDev#9652]
It is rare that Monika reacts the same as always, when she is alone wearing a towel and her hair is wet, to:

I love your hair
I love your outfit
you are beautiful

not only that, you miss out on good easter eggs

**Comment by Booplicate** [comment]
This sounds like our Talk Menu Awareness project.

**Comment by ephemlw** [comment]
Wait, is bath greeting already implemented in the game? I'm asking because I've never had one.

**Comment by Booplicate** [comment]
Yes.

**Comment by ephemlw** [comment]
Then why haven't I got this greeting yet? Am I that unlucky?

**Comment by Booplicate** [comment]
Possible, or just didn't meet the criteria yet.

Closing until we start working on this later.
