### ISSUE TITLE
please I need help with a possible bug when minimizing the M.A.S. wndow

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#9656]
every time i minimize the game or it is minimized by accident it froze and does not let me return to maximize it and after a few seconds it crashes this happens to me with other DDLC mods too. but especially with the M.A.S. before I had a laptop with windows 7 and when minimizing the M.A.S. It froze and I couldn't maximize it anymore until I closed it with task manager. this did not happen to me with other mods

PD: any clue to unlock the NOU game? for a matter of time I could barely update my M.A.S. and try to unlock the game by playing the others a bit (as I did to unlock chess and hangman) I played them several times except for chess that I only played once and waited for days and it still hasn't unlocked

**Comment by Booplicate** [comment]
Ren'Py doesn't like when you minimise the game window, not something we can specifically fix.

NOU doesn't depend on other games. See [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/NOU-rules#how-to-unlock).

**Comment by elite198** [comment]
> Ren'Py doesn't like when you minimise the game window, not something we can specifically fix.
> 
> NOU doesn't depend on other games. See [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/NOU-rules#how-to-unlock).

oh I see, it's just that in older versions of the mod I could normaly minimize the mod.
anyway thanks for both clarifications

**Comment by Booplicate** [comment]
> oh I see, it's just that in older versions of the mod I could normaly minimize the mod.

It's inconsistent, some people are having this issue, some aren't. The issue exists from the earliest days, usually occur on low end laptops, but sometimes happens even on beefy setups. General rule is to not minimise the game (you can still run in background, just don't minimise).
