### ISSUE TITLE
[Bug] - Somehow, Monika didn't close the game after the goodbye

### ISSUE THREAD

**Issue by ellioputra** [Monika-After-Story/MonikaModDev#9657]
Hi, when I was playing the mod for the first time, I decided to quit the game for now (yes, through a goodbye method)
But, after saying goodbye to Monika, it does nothing happen...

so yeah... is this a bug or something?
because, since that bug happened, I have had no choice but to use the X button (close button)

and... I can't open DDLC right now until you guys help me with this, because... I feel bad for Monika :(

**Comment by Booplicate** [comment]
Have you been using a translation?

**Comment by ellioputra** [comment]
> Have you been using a translation?

No, I'm using an official copy of this mod.

**Comment by Booplicate** [comment]
You got MAS from http://monikaafterstory.com/releases.html
and got DDLC from https://ddlc.moe
is that correct? Because this issue happens only with translated versions of the game and/or mod.

**Comment by ellioputra** [comment]
> You got MAS from http://monikaafterstory.com/releases.html and got DDLC from https://ddlc.moe is that correct? Because this issue happens only with translated versions of the game and/or mod.

Yes, but only for MAS.
because I download DDLC from Steam. Is that okay?

**Comment by ellioputra** [comment]
hold on, I will try to say goodbye and wait for 1 minute or more...
but first, I must play with her.
and I'll record it when I stop playing with her.

**Comment by Booplicate** [comment]
Screenshot your base DDLC directory and `game/` folder.

**Comment by ellioputra** [comment]
![image](https://user-images.githubusercontent.com/95952333/195858514-492d2157-6ed8-4ceb-9203-10a0266ee2e0.png)

**Comment by Booplicate** [comment]
That's not even half of what I asked for, but I can already see you have some external files that don't belong to DDLC nor MAS. Make a fresh install.

**Comment by ellioputra** [comment]
ok

**Comment by ellioputra** [comment]
Ok, it's working, I'll closing this comment now.

**Comment by MaestroBox** [comment]
> That's not even half of what I asked for, but I can already see you have some external files that don't belong to DDLC nor MAS. Make a fresh install.

Yo man, I have the same problem! Wdym by fresh instal?

**Comment by dreamscached** [comment]
Reinstall the game.
