### ISSUE TITLE
(suggestion) allow the "i'm breaking up with you" dialog to come back for april fools day if monika disabled it already

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#9664]
I'd like to leave a suggestion in honor of those of us who couldn't attempt that dialogue on April Fools' Day.

In my case Monika disabled it after reaching 700 or 1000 affection and I couldn't test that experience, it would be great if the dialog came back that day only for those who have that dialog disabled.

And by the way, it would be great if more jokes were added for both sides, for example:

On Monika's part, she could pretend that she abandoned the player and that when she opens the note on the table she says "you fell" or something.
she could also use those sprites of the other girls that are in the files. I imagine the player entering and seeing yuri for example saying something like "h-hello player it's been a while. oh are you looking for monika? don't worry she won't bother us anymore, now we can spend eternity together" or something like that with the others . the point is that after a few dialogues the screen suffers from glitches and it is revealed that she was monika "disguised" all the time playing a prank on the player.
another joke could be a reference to a youtube video called "monika is pregnant" it could tell the player that she is pregnant because of a virus or something XD it could be funny.

As for the player, I can't think of anything besides the jokes that can be done to her now, but it would be great if they added gifts with the theme of that day and if you use them more than once you lose a little affection

pd i mean these sprites 
![natsukidesk-n](https://user-images.githubusercontent.com/95457650/195514127-34a46d4e-39b6-4a18-9191-7245e33d087a.png)
![sayoridesk_happy](https://user-images.githubusercontent.com/95457650/195514134-313f64c3-2f3d-4e9e-9171-7df56263ef58.png)
![sayoridesk_sad](https://user-images.githubusercontent.com/95457650/195514137-c4b1a711-e65c-4738-8e1a-9cd5ce156651.png)
![yuridesk](https://user-images.githubusercontent.com/95457650/195514140-7214a026-c876-47b5-a8f0-154fbc7e69b0.png)
![natsukidesk](https://user-images.githubusercontent.com/95457650/195514141-a1793136-56f2-4f46-a26d-fdb270382dbe.png)

**Comment by Booplicate** [comment]
I'm not sure extra handling for that event is worth it, unless somebody can come up with a clear solution.
MAS isn't designed to be completed on 100%, you can't see everything. So, personally, I think not being able to see that flow in some cases is fine.

Other Dokis won't appear in MAS directly, it'd imply they exist in MAS. Also those sprites are old and don't match our current style.
