### ISSUE TITLE
Empty 'Now, where was I...' when game crashed while in settings menu opened via 'Talk' menu.

### ISSUE THREAD

**Issue by dreamscached** [Monika-After-Story/MonikaModDev#9665]
I have noticed this bug while testing my submod settings pane that caused a crash upon calling a function on button click.

Steps to reproduce:
1. Start the game
2. Open 'Talk' menu
3. Open settings menu with 'Settings' button on the textbox.
4. Cause a game crash/force exit with `sys.exit()`
5. Re-open the game and experience an empty (with no following dialogue) 'Now, where was I...' Monika behavior.

**Comment by Booplicate** [comment]
Was there any topic in progress?

**Comment by dreamscached** [comment]
No, I only opened talk menu just to access the textbox and 'settings' button.

**Comment by dreamscached** [comment]
Update: I have tried to reproduce it again on record, but it seems I can't anymore. Which is really weird as I experienced it *several* times doing the same routine as described in the issue before I posted it...

**Comment by dreamscached** [comment]
Yes, no longer reproducible for some reason for me. What I was testing had no topics at all, I was testing a button click action in submods menu, so beside talk menu there were no way a topic could be started and left hanging.

**Comment by Booplicate** [comment]
I think there was a topic, but it got removed. Or perhaps it got pushed, but there was a sanity check within the label. I'd investigate further, but we'd need to know what topic was it. Could be a submod, too.
