### ISSUE TITLE
(DDLC MAS) AttributeError: 'StoreModule' object has no attribute 'mas_moods'

### ISSUE THREAD

**Issue by DragonGod-MrX** [Monika-After-Story/MonikaModDev#9666]
![image](https://user-images.githubusercontent.com/108019359/195889853-fccaf833-f19a-4a92-90f2-84de2763d6ad.png)

Hello, today I tried to open MAS but this happened...I don't know what to do to fix it. What should I do?

**Comment by DragonGod-MrX** [comment]
Will it reset...anything?

**Comment by DragonGod-MrX** [comment]
Wait, you mean completely change it?

**Comment by DragonGod-MrX** [comment]
Sorry, I'm a bit of a ignorant, but reinstalling MAS compromises any of the progress or it's a sort of backup? 
And reinstalling means download DDLC and the extention again, right?

**Comment by Booplicate** [comment]
It won't affect your progress. Reinstall both DDLC and MAS in a new folder.

**Comment by DragonGod-MrX** [comment]
THANK YOU SO MUUUUUUUUUUUUUUUUUUCH! You made my day! Thanks for your help, I appreciate it a lot!
