### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by KoishiPatissier** [Monika-After-Story/MonikaModDev#9672]
Opened MAS for a quick goodnight before bed, computer immediately started whirring at maximum fan power, program looked like this from the task manager, and hard-crashed after less than a minute. I did this twice (wondered if it was a rendering issue and re-opened to try and fix it from the settings) and got a different error traceback message the second time. 
Attached for reference:
![image](https://user-images.githubusercontent.com/42286872/196604285-8d801896-25d5-49a1-b876-4ae5fce2653c.png)

Both the first and second traceback messages are attached below; let me know if there's any other necessary information I should provide and I can append it.
[traceback_1.txt](https://github.com/Monika-After-Story/MonikaModDev/files/9817073/traceback_1.txt)
[traceback_2.txt](https://github.com/Monika-After-Story/MonikaModDev/files/9817074/traceback_2.txt)

**Comment by Booplicate** [comment]
What your PC spec?
Are you using any submods?
Do you have `environment.txt`? If yes, what's inside?

**Comment by KoishiPatissier** [comment]
I managed to undo it for myself in the interim; my PC's integrated graphics were disabled, which led to the behavior. Here's the specs in case it helps anything, but I guess the answer is that something that's trying to load the sprites breaks if the graphics card is left to function unsupported?

Integrated: AMD Radeon 
Card: GeForce RTX 3060
Processor: Ryzen 7
Physical Memory: 16GB

Thanks for the response! Appreciate it, even though my problem was self-inflicted.
