### ISSUE TITLE
mas_gainAffection isn't working properly

### ISSUE THREAD

**Issue by SteveeWasTaken** [Monika-After-Story/MonikaModDev#9679]
I was working on a Submod, and whenever I try to give monika affection with it, her affection stays the same. When looking at the logs, it seems that when I give her any affection with mas_gainAffection, it automatically lowers to a random number. While I was testing with various different numbers, it lowered 99 affection to 7.1054273576e-15, and not only that, but it also didn't add that 7.1054273576e-15 affection at all. Why is this happening, and why are decimal values even accepted for affection?

**Comment by Booplicate** [comment]
This is the design choice.

**Comment by SteveeWasTaken** [comment]
Adding 99 affection at once worked to me before, and now it doesn't, so it doesn't make much sense. I also set "bypass" to True, but it still didn't work. Shouldn't it add the 99 affection anyways if I have bypass set to True?

**Comment by Booplicate** [comment]
No, adding 99 affection doesn't make sense from the gameplay perspective.

**Comment by SteveeWasTaken** [comment]
Alright, I understand. Thanks!
