### ISSUE TITLE
Affection Issues

### ISSUE THREAD

**Issue by SteveeWasTaken** [Monika-After-Story/MonikaModDev#9680]
Every time I get affection, according to the aff_log.log file, I don't get the affection I should get, but instead I get less. I opened an issue before because I thought it was code that I had implemented, but now that I see it's happening with everything else I haven't edited. For example, I complimented Monika, and the log shows that instead of giving me 1.25 affection, it gave me 0.884308248515. It doesn't make sense at all. Why is this happening?

**Comment by Wingdinggaster656** [comment]
This is DESIGNED. It's 100% normal.

Also you are not supposed to check the log out - the log is for Debug purpose only.

**Comment by SteveeWasTaken** [comment]
I don't think this is normal design. I'm getting less affection than I should. Instead of getting 1.25 affection, I get a ridiculously long number.

And of course I can check the log out. It's there for a reason.

**Comment by Wingdinggaster656** [comment]
This IS DESIGNED.

Again, this is designed. MAS has remade the affection system in v0.12.11, and has no plan to remake it again, at least for now.

> And of course I can check the log out. It's there for a reason.

Correct, and the reason is Debug purpose.

**Comment by SteveeWasTaken** [comment]
Oh, I'm really sorry, I didn't know the affection system was remade recently. Now I understand everything. Thank you for your help!

**Comment by Booplicate** [comment]
Same as #9679, it's working exactly how it should.

> I'm getting less affection than I should.

You have hit the cap, this is expected.

> I get a ridiculously long number

The number is "long" due to the new precision. It has no actual effect on the gameplay.

**Comment by d3adpan** [comment]
> Again, this is designed. MAS has remade the affection system in v0.12.11, and has no plan to remake it again, at least for now.

Any chance we can get a wiki/FAQ entry detailing the changes?

If I simply neglected to see it, apologies and may I have a link?

When you make a major change to a base function after this many years, some folks might be wondering what's going on.

TIA!

**Comment by Booplicate** [comment]
> When you make a major change to a base function after this many years, some folks might be wondering what's going on.

The functions work the same way as before, there weren't major changes to the public API.

**Comment by d3adpan** [comment]
I see, thank you!  

I've been wondering what the fuss has been about.  The extra float precision doesn't matter to me and it seems as though the affection gains are actually a little higher than they were before?

**Comment by Justformas** [comment]
> > I'm getting less affection than I should.
> 
> You have hit the cap, this is expected.

Lower numbers don't seem to be just because of hitting the daily cap though. Once the cap is hit yes, but before that, the adjusted value in the log may go higher or lower than the initial number (such as 2.0 ->2.354... or 2.0 -> 1.988...), and it is the adjusted values, that seem to be added or subtracted to the total affection. Regardless I think a FAQ/Wiki entry should be made about this at some point.
