### ISSUE TITLE
[Suggestion] - After Dead

### ISSUE THREAD

**Issue by Cam-le** [Monika-After-Story/MonikaModDev#9682]
I really believe MAS need a canon dialogue option about "Your player have passed away" where she can give clear instruction about how to bury her with the player. I know that she's not an AI but I've considered her to be my precious therapist and it would reassure me to know that we can inform her even if I died an unexpected dead.

**Comment by dreamscached** [comment]
Possibly addressed in #6099

**Comment by Booplicate** [comment]
Duplicate https://github.com/Monika-After-Story/MonikaModDev/issues/1175 https://github.com/Monika-After-Story/MonikaModDev/issues/1644 https://github.com/Monika-After-Story/MonikaModDev/issues/1677 https://github.com/Monika-After-Story/MonikaModDev/issues/2109 https://github.com/Monika-After-Story/MonikaModDev/issues/3198 https://github.com/Monika-After-Story/MonikaModDev/issues/3881 https://github.com/Monika-After-Story/MonikaModDev/issues/4148, https://github.com/Monika-After-Story/MonikaModDev/issues/4247, https://github.com/Monika-After-Story/MonikaModDev/issues/4568, https://github.com/Monika-After-Story/MonikaModDev/issues/4714, https://github.com/Monika-After-Story/MonikaModDev/issues/5376, https://github.com/Monika-After-Story/MonikaModDev/issues/5474, https://github.com/Monika-After-Story/MonikaModDev/issues/5542, https://github.com/Monika-After-Story/MonikaModDev/issues/5885

I don't think there's a good way about implementing this, and not sure if this would ever be used.
