### ISSUE TITLE
Will changing your system locale affect MAS?

### ISSUE THREAD

**Issue by t0kichii** [Monika-After-Story/MonikaModDev#9693]
I know this is a weird and probably easy to answer question, but i needed to change my system locale for something and I want to know if I need to change it back before opening MAS. I figured I _should_ but I haven't done anything yet and would just like to check to make sure I don't make a mistake. (I don't know a lot about system locale so I'm just hoping someone here does. If you don't know what I'm referring to you can look it up but I'm not sure if that will help you jsjdhdxjxj)

**Comment by Booplicate** [comment]
You don't have to, MAS should work on any locale. Just restart MAS when you change it. Also make sure the path to the game contains only latin characters.

**Comment by t0kichii** [comment]
Thank you!!!

**Comment by dreamscached** [comment]
Closing as resolved.
