### ISSUE TITLE
[Suggestion] Skip "already gave this gift" after it's been said enough

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#9697]
I frequently download a lot of spritepacks at once, like the whole catalogue that comes with the update or a single creator's whole collection, and just dump the files into the right places and let Monika sort the rest out. But it takes a lot longer to get through if I've downloaded any of those items before and just don't remember; this gets more and more common the more spritepacks I download. I think it would be nice if it could be skipped.

**Comment by dreamscached** [comment]
I don't think this is implementible at this point. Spritepacks have programming entry and exit points which do not only include dialogue but also include code used to activate something, set persistent variables etc.

Adding this button to skip programming points entirely would cause a lot of custom logic to break.

**Comment by Booplicate** [comment]
This can be possible, but it exists to provide feedback that some gifts didn't work. Perhaps it could be put under a single reaction with "You failed to give me X gifts."
But I'd say this should be done after the gift system overhaul and after we get a gifting log.
