### ISSUE TITLE
i don't know if it's a spoiler but just in case...

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#9698]
about the new costume (2B), should we give it right now so Monika can prepare it for halloween or the D day?

**Comment by Booplicate** [comment]
If you give it now, she will be able to pick it on O31.

**Comment by MonikaEndDie** [comment]
Ok, thanks. And about the NOU shirt, just to be sure: while i didn't founded it inside the spritpack folder we can download to install new outfits's files, i saw it was already installed when i updated the mod, so theoretically, i don't need to do anything about this one?

**Comment by Booplicate** [comment]
It unlocks randomly when you play NOU.

**Comment by MonikaEndDie** [comment]
I see. It's everything i need to know, thank you.

**Comment by dreamscached** [comment]
Closing as resolved.
