### ISSUE TITLE
So I really need help

### ISSUE THREAD

**Issue by iloveyuri** [Monika-After-Story/MonikaModDev#9702]
So When I was trying to update MAS for the Halloween update, but then this error popped up when i was trying to open it up again:
![2022-10-30](https://user-images.githubusercontent.com/117046805/198905512-d2a152f9-2b99-4d5e-a485-ad20b2f82037.png)
I don't know what to do since i'm not sure what wrong with the code.

**Comment by Booplicate** [comment]
If you're using a translation, you can't go back to the official MAS. If you're running the source version, you can't update.

Make a fresh DDLC install and get MAS there using the installer.

**Comment by iloveyuri** [comment]
Tysm!
