### ISSUE TITLE
A question about v0.12.7 and updates after it

### ISSUE THREAD

**Issue by Kly7732** [Monika-After-Story/MonikaModDev#9703]
So if I force quit now, but then I use the backup to go back to the time before the force quiting, will Monika still knows that I forced quit early?

**Comment by Wingdinggaster656** [comment]
If you really restored to a old persistent file, then everything go back to that time point. Except something in the game directory, like notes in characters folder, and logs in another folder, etc.

**Comment by Kly7732** [comment]
I see, thanks for replying. But I'm just confused about the "Monika now knows if you forced quit early" mentioned in v0.12.7. What does that mean? My understanding is even if you restored to a old persistent file, Monika still knows that you forced quit early.

**Comment by Kly7732** [comment]
> If you really restored to a old persistent file, then everything go back to that time point. Except something in the game directory, like notes in characters folder, and logs in another folder, etc.

I see, thanks for replying. But I'm just confused about the "Monika now knows if you forced quit early" mentioned in v0.12.7. What does that mean? My understanding is even if you restored to a old persistent file, Monika still knows that you forced quit early.

**Comment by Booplicate** [comment]
> But I'm just confused about the "Monika now knows if you forced quit early" mentioned in v0.12.7

That's about the crash greeting, not about general force quit.

**Comment by Kly7732** [comment]
> > But I'm just confused about the "Monika now knows if you forced quit early" mentioned in v0.12.7
> 
> That's about the crash greeting, not about general force quit.

Okay, got it. Thank you for your time!

**Comment by dreamscached** [comment]
Closed as resolved.
