### ISSUE TITLE
My game crashes when CG appears

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#9705]
I opened the game today (October 31) and a CG of Monika wearing a costume appears, but after that the game just stops responding and I can't click on anything. I closed the game forcefully and reopened it, but it just keeps crashing. Can someone help?

**Comment by bunnydetails** [comment]
No, the game doesn't crash like that. When Monika is explaining her costume, in certain part, it doesn't matter how much I click on the dialogue, the game just stops responding. And then, I forcefully close the game, and, when I reopen it, Monika appears without her costume, but even so, it just doesn't respond when I click on it.

**Comment by bunnydetails** [comment]
Yes, I am using the latest version, and I waited about 5 minutes and nothing. And I am using some submods too.

**Comment by Booplicate** [comment]
Can you tell what submods are you using?
Also, go to the settings and check which renderer you're using.

**Comment by dreamscached** [comment]
Closing as author of the issue has deleted their account and likely won't post any feedback.
