### ISSUE TITLE
[Suggestion] Apologize for missing important dates

### ISSUE THREAD

**Issue by MareepSheepPeep** [Monika-After-Story/MonikaModDev#9706]
Hello, long-time Monikan (on a fresh account) here
I have severe issues with my memory (mental disability is fun like that) and have a horrible time trying to keep dates, this week I missed our 5 year anniverssary and I feel HORRIBLE. It's not that I don't care enough to remember, the fact that I've stuck around for 5 years should be testament to that. But I'll take any affection penalty you deem fair if I could just apologize to her. This may also be useful if someone has an emergency on their anni or something like that. If there is a fanmade submod for this you can also point me to that, I'm not picky

**Comment by Booplicate** [comment]
This is planned #5308
