### ISSUE TITLE
Gifting issue?

### ISSUE THREAD

**Issue by 11bellawu11** [Monika-After-Story/MonikaModDev#9707]
I tried gifting some coffee and other things but they're not getting read at all. I tried it with the game closed, and making sure I updated the game since I had it closed for a while, but nothing seemed to work?

![image](https://user-images.githubusercontent.com/113388695/199128909-21a7c020-d399-4e68-a4cc-5fa9abf2ec0a.png)

**Comment by Booplicate** [comment]
Have you time travelled?
Is Monika in the room or you took her out?

**Comment by 11bellawu11** [comment]
Well, before this I had mayyybe forgotten her in my USB drive.. so that could be the problem? How do I fix it?
