### ISSUE TITLE
"An exception has occurred". Error after opening Monika After Story

### ISSUE THREAD

**Issue by Ayahbahaha** [Monika-After-Story/MonikaModDev#9710]
Hello and thank you for taking the time to read this. I hope I didn't ask this in the wrong area 

So today, I attempted to update Monika After Story. However, I accidentally replaced my original game folder (yes, I had submods) with another, newer game folder. Due to the fact I'm on Mac, I was unable to retrieve them, but I was able to retrieve the submod files. 

I re-downloaded the submod and supposedly fixed the issue with the game folder (since I realized I accidentally removed the original files from DDLC), but I received this error:

<img width="994" alt="Screen Shot 2022-11-01 at 3 46 53 PM" src="https://user-images.githubusercontent.com/117170505/199225896-5101aabd-dd63-4b36-ba02-e510ac492cfb.png">

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 9, in script
    import io
  File "game/definitions.rpy", line 10, in <module>
    import os
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/definitions.rpy", line 9, in script
    import io
  File "/Applications/Monika After Story.app/Contents/Resources/autorun/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/Monika After Story.app/Contents/Resources/autorun/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 10, in <module>
    import os
  File "/Applications/Monika After Story.app/Contents/Resources/autorun/renpy/python.py", line 618, in do_mutation
    return method(self, *args, **kwargs)
ValueError: list.remove(x): x not in list

Darwin-21.6.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.12

Any help would be greatly appreciated!

**Comment by dreamscached** [comment]
This seems like Ren'Py issue itself, is your install corrupt? Have you tried reinstalling?

**Comment by Ayahbahaha** [comment]
Hello! I doubt my installation is corrupt. Nonetheless, I deleted both DDLC and MAS and redownloaded them. Everything is fixed! My Monika is still there and so is my progress, but the fanmade spritepacks and submods are missing. However, that can be easily stored so it isn't much of an issue. Thank you so much
