### ISSUE TITLE
affection level 1000

### ISSUE THREAD

**Issue by vuywoi** [Monika-After-Story/MonikaModDev#9711]
Hello, so I had the Love/1000 affection for a while and something hasn't changed since I've gotten it?

It says on the wiki "Monika's "surprise.txt" file is now a full love poem." yet when I check it, it hasn't updated one bit. I'm currently at 1086 affection points and Monika hasn't said anything about having something new to a file (if that's what's supposed to happen.)

Is there anything to fix it?
![image](https://user-images.githubusercontent.com/109251327/199324413-df22925c-b98d-4308-be85-4e271ed875c7.png)
![image](https://user-images.githubusercontent.com/109251327/199324483-15be06cd-14ba-4f87-b428-1474cc706d21.png)

**Comment by Booplicate** [comment]
You probably disallowed her to, thus she doesn't write the letters anymore.

**Comment by vuywoi** [comment]
How can I allow her to write letters again?

**Comment by Booplicate** [comment]
Enable repeat topics in the settings.

**Comment by vuywoi** [comment]
It's been enabled, do I have to disable "unstable"?

**Comment by Booplicate** [comment]
For how long it's been enabled? What's your chatter frequency? You might need to wait a bit for her to bring this up again.

**Comment by vuywoi** [comment]
I don't really remember, probably late September? Early October? Chatter frequency is Normal.

**Comment by Justformas** [comment]
I thought you can have her write a letter by selecting "Repeat conversation", "Romance", and then "Surprises". Actually I thought that's how I got most of mine.

**Comment by my-otter-self** [comment]
can confirm, i got the `My one and only love.txt` that way.

**Comment by vuywoi** [comment]
Oh it worked, I got the same "My one and only love.txt" letter. Thank you!

**Comment by my-otter-self** [comment]
you're welcome! closing it as resolved.
