### ISSUE TITLE
issues with the gifts.

### ISSUE THREAD

**Issue by iloveyuri** [Monika-After-Story/MonikaModDev#9712]
I tried giving Monika gifts like this to her:
![2022-11-01](https://user-images.githubusercontent.com/117046805/199362855-fb3236f0-895d-4596-bf38-7293a74d6968.png)
But she says she can't read them, I tried restarting the game but nothing worked.

**Comment by dreamscached** [comment]
Make sure you installed the spritepacks properly.

**Comment by iloveyuri** [comment]
Question: how do I install them properly?

**Comment by Booplicate** [comment]
Those are custom gifts, you will need to contact the creator for support.
