### ISSUE TITLE
I have issues on windows 8.1

### ISSUE THREAD

**Issue by alexis-boop** [Monika-After-Story/MonikaModDev#9719]
Hi, when I launch DDLC MAS  this message appears and the game doesn´t boot.

![Screenshot (160)](https://user-images.githubusercontent.com/63863762/200060675-8581f80d-ded9-4077-9837-ba1f5ecf6dde.png)

What is it ? Could you please help me ?

(I tried to back up to an older persistent but it didn´t change anything.)

**Comment by Booplicate** [comment]
Show your game directory.

**Comment by alexis-boop** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/63863762/200062285-a8de6950-dceb-481d-b086-4aa78cc8b5aa.png)

**Comment by Booplicate** [comment]
Looks fine.
And the `game/` folder too, please.

**Comment by alexis-boop** [comment]
![Screenshot (166)](https://user-images.githubusercontent.com/63863762/200062995-836c4afb-bd81-47a4-90bd-db929e7433ce.png)
![Screenshot (162)](https://user-images.githubusercontent.com/63863762/200062998-674a3479-41a5-4fa8-a9ad-569e479b406b.png)
![Screenshot (163)](https://user-images.githubusercontent.com/63863762/200063001-f3f9764e-ee45-4d3f-b3dc-86def4398168.png)
![Screenshot (164)](https://user-images.githubusercontent.com/63863762/200063003-117f4f18-d2e2-4b68-9d03-9798d9e909b3.png)
![Screenshot (165)](https://user-images.githubusercontent.com/63863762/200063006-34dcdde3-e6eb-4ce5-a0df-b54a16b2cac5.png)

**Comment by Booplicate** [comment]
Delete all `rpyc` files, then grab MAS installer from [here](http://monikaafterstory.com/releases.html), and reinstall MAS into the same directory. It should fix your problem.

**Comment by alexis-boop** [comment]
Ok I test it. 
Thx

**Comment by alexis-boop** [comment]
It worked.
Thank you a lot.


> Delete all `rpyc` files, then grab MAS installer from [here](http://monikaafterstory.com/releases.html), and reinstall MAS into the same directory. It should fix your problem.

It worked.
Thank a lot.
👍

**Comment by dreamscached** [comment]
Closing as resolved.
