### ISSUE TITLE
When I open MAS, I get this error. Can someone tell me how to fix?

### ISSUE THREAD

**Issue by TowheadedDesert** [Monika-After-Story/MonikaModDev#9720]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_spritejsons.rpy", line 396, in script
  File "game/zz_spritejsons.rpy", line 467, in <module>
  File "game/0utils.rpy", line 301, in init_log
IOError: [Errno 13] Permission denied: u'C:\\Users\\antho\\OneDrive\\Desktop\\DDLC\\MAS\\DDLC-1.1.1-pc\\log\\spj.log'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/zz_spritejsons.rpy", line 396, in script
  File "C:\Users\antho\OneDrive\Desktop\DDLC\MAS\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\antho\OneDrive\Desktop\DDLC\MAS\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_spritejsons.rpy", line 467, in <module>
  File "game/0utils.rpy", line 301, in init_log
  File "python-packages/logging/__init__.py", line 920, in __init__
  File "python-packages/logging/__init__.py", line 952, in _open
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/codecs.py", line 884, in open
IOError: [Errno 13] Permission denied: u'C:\\Users\\antho\\OneDrive\\Desktop\\DDLC\\MAS\\DDLC-1.1.1-pc\\log\\spj.log'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.12

**Comment by dreamscached** [comment]
Change permissions on `log` folder to allow writing files.

**Comment by TowheadedDesert** [comment]
I checked the log folder and the spj and they both have all permissions including writing allowed.

**Comment by Wingdinggaster656** [comment]
Give MAS the permission to access the certain directory.

Also, you are running MAS from Onedrive. This could cause numerous strange problems, move MAS to a non-Onedrive directory, RIGHT NOW.

**Comment by TowheadedDesert** [comment]
@Wingdinggaster656 
It says everything has full maxed out permissions for everything
and also how do I move MAS to a different directory?

**Comment by Wingdinggaster656** [comment]
> @Wingdinggaster656
> It says everything has full maxed out permissions for everything
> and also how do I move MAS to a different directory?

Don't you know how to use computer? Just move MAS like you move anything else on your computer.

**Comment by TowheadedDesert** [comment]
@Wingdinggaster656 @dreamscached 
Oh yeah I understand now. I moved it to "This PC"
So about the actual problem, do you know any other solution? I have given log and spj all the permissions that it will allow me to.

**Comment by ashyashton** [comment]
> Don't you know how to use computer? Just move MAS like you move anything else on your computer.

@Wingdinggaster656 
Jesus dude, why the hell are you being so mean about it? Not everyone knows a ton about computers and how they work, there's no need to be rude. This is where people come to get support for the mod; why are you being so rude when they do so? No one is forcing you to be the one to answer, so chill the hell out, damn.
