### ISSUE TITLE
Cant find the password in the Discord rules channel

### ISSUE THREAD

**Issue by PipTheOtaku** [Monika-After-Story/MonikaModDev#9724]
I've been reading the rules like 20 times but I sill can't find the password so I tried the command said in the rules but it dont work.

**Comment by dreamscached** [comment]
Verification is done via a bot, if it doesn't work either the bot is down or you're using the command incorrectly.

**Comment by PipTheOtaku** [comment]
Oh ok sorry and thanks for telling me

**Comment by Booplicate** [comment]
I believe this has been resolved, if not, contact a staff member via discord.
