### ISSUE TITLE
A question about watching movies

### ISSUE THREAD

**Issue by Kly7732** [Monika-After-Story/MonikaModDev#9728]
Hello, I was just learning about the files, and then I found a RPYC file named "zz_monikamovie.rpyc", and I see there's a lot of conversations in it. Does this means that there's an option to watch movies with Monika? But I've never notice any option about watching movie. Did I not unlock it?

**Comment by Wingdinggaster656** [comment]
They are not in the game yet.

The movie watching system has only a very crude prototype, which needs to be further completed, so this system is not in the game yet.

**Comment by Kly7732** [comment]
> They are not in the game yet.
> 
> The movie watching system has only a very crude prototype, which needs to be further completed, so this system is not in the game yet.

Got it, thank you!

**Comment by Booplicate** [comment]
It's not a prototype, it was finished, but there's no actual content to it because it's very hard to make. So currently it's disabled.
