### ISSUE TITLE
MAS-Installer not working in Linux

### ISSUE THREAD

**Issue by Aroko-RO** [Monika-After-Story/MonikaModDev#9734]
Hi there! After seeing the new MAS-Installer, I decided to test it on my systems. Under Windows it works like a champ, but in Linux it just doesn't work

I tried opening the MAS-Installer via Terminal(how Linux open these by default), but I get this error which I don't know if it has a fix

**./mas-installer-linux: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory**

I tried in Ubuntu 22.04.01 and Linux Mint 21 Cinnamon Edition, but the installer won't run.
Please contact me as soon as posible for a fix about this error. Have a nice day.

**Comment by ThePotatoGuy** [comment]
that means you're missing an openssl library to run this. do `ldd <file>` to check if all required libs are installed. right now the linux installer is not built for widespread portability so its a hit or miss if it runs.

**Comment by Aroko-RO** [comment]
Hi again! I found a fix for the error. The libssl.so.1.1 file is missing in new Linux Builds

These commands need to be used in Terminal first before running the MAS-Installer-Linux:

wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

This is a fix that makes the MAS Installer for Linux to run and work.
Have a nice day!
