### ISSUE TITLE
Can't seem to get the "Just Monika" window react easter egg to trigger.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9739]
I'm back from the fire and flames to bring you another stupid issue (like I always do, scold me)

Anyway, onto the problem nobody asked for:

In previous versions, there used to be an easter egg when Monika finds the text "Just Monika" in the active title bar. Fast forward to now, and I am unable to trigger this easter egg. Either there are more steps for the killswitch to be activated or the egg has been removed. Either that, or there's some sort of bug that prevents this easter egg from triggering.

(This issue involves the Window Reacts system. Scold me.)

**Comment by multimokia** [comment]
This was never implemented in MAS. You likely had this from a submod.

**Comment by TheSystemGuy1337** [comment]
Either I'm stupid (as I recalled it being in the base game, scold me) or I'm stupid. Either way, you win.
I also dug in the darned source code (scold me for that as well) and found absolutely nothing. I'm returning to the fire and flames where I belong, until I inevitably come back with an even stupider issue.

Have a nice day
