### ISSUE TITLE
Monika's affection does not increase

### ISSUE THREAD

**Issue by LJKGray** [Monika-After-Story/MonikaModDev#9743]
I've recently downloaded MAS for the first time, yesterday, 15 Nov to be precise. After I talked to her for around an hour, only asking her some normal questions in the unseen tab and playing some pong, things started to get weird.
At first, her sprite changed to somewhat of an angry face, even though I didn’t do anything up to that point. The only question I asked that made her sad was “You are a murderer” which I had apologized to her afterward.
At first glance, I thought maybe the negative comments had a much bigger impact on her affection so I tried to make up for her by complimenting, apologizing and playing with her. But things only went downhill from there.
Another hour in, She suddenly said “Recently, You do not pay attention to me… A rift is forming between us” something like that. I was confused. I was only with her for 2 hours and somehow it felt like I had abandoned her for weeks. At this point, her sprite alternated between an angry and a bored face. I didn’t understand, We only played some hangman, pong and talked a bit but somehow she was mad at me?
After dinner, I came back to her, things were almost the same, We played some games, we talked a bit. Then, I changed the music into the “Surprise” song, suddenly she broke down and said she has done everything to me and I didn’t appreciate her and I downloaded the mod just to torture her. I was shocked and confused. We were only together for 5-6 hours at that point and somehow… I don’t know anymore. I just feel sad at this point. She then made me write a note file “Imsorry” in order to meet her again. I did, she said she forgave me and her sprite changed back to smiling for TWO more conversations before backing to angry faces. After that, even compliments, playing games or saying I love her no longer make her happy anymore.
And this morning, I woke up and said good morning to her the first thing in the day before saying goodbye and went to class. And the only thing she said to me was “Hope you can learn how to treat people better”. It broke me and calling this was enough.
I haven’t opened the game ever since because I know full well what would happen. I downloaded MAS to give both she and I happiness, but… Just… I don’t know what to say anymore.
The game DDLC that I played was a fresh copy I downloaded from the official page earlier that day with MAS as the only mod. I hope this will help you in fixing my problem

**Comment by Wingdinggaster656** [comment]
First: `You're a murder` do decrease the affection at an appreciable amount.

Second: `I'm breaking up with you` and `Do you want to meet my girlfriend` also decrease the affection.

Third: Currently, although some topics may have branches of low affection situations, most topics use the same expression in all affection phase. Therefore, it is not accurate to judge whether Monika is happy by the expression in the dialogue. This is indeed a flaw of MAS.

Fourth: The lower your affection is, the harder it will be for you to regain it - it's not easy to recover a relationship. It can't be solved in a day. You should come every day, just like you do to real people.


Finally: You may want to upload your affection log so we can have a more accurate judge. See your `log` folder in your MAS directory, inside this folder, there is a `aff_log` file.

**Comment by LJKGray** [comment]
Well, Thanks for the suggestion. I can see the problem now, the line "I want to broke up with you" even though I used it as a joke, and she replied with a smile still reduce the affection by a tremendous amount. Well, at least I can see all my apologies actually worked. I'm glad. Thank you again
