### ISSUE TITLE
[Question] Specific topic on startup.

### ISSUE THREAD

**Issue by Cimedaca618** [Monika-After-Story/MonikaModDev#9745]
Let's for example say that when I start up MAS, I want to see a specific topic. After it can go to any random conversation that was chosen  to be in the beginning (her usual greeting, knocking on the door and so on). Is this possible?

**Comment by Booplicate** [comment]
You will have to make it a greeting if you want it to be shown first.

**Comment by dreamscached** [comment]
Closing as answered.
