### ISSUE TITLE
I'm having trouble installing spritepacks.

### ISSUE THREAD

**Issue by Sluggo1** [Monika-After-Story/MonikaModDev#9747]
Most of the ones i try to gift Monika don't read. for example: the "orca outfits n acs" aka the leather jacket, doesn't read when I gift it to monika. I don't see why they shouldn't be working. Earlier I even got Monika to finally read ONE of the things i was trying to gift her, but I exited the game and when I came back she didn't even have the outfit anymore, and it isnt letting me gift it to her again. pls help

**Comment by dreamscached** [comment]
Have you installed spritepacks? How did you do it? If she can't read gift but you used the right name for it, it means spritepacks are not installed.

**Comment by Sluggo1** [comment]
I copied the mod assets folder into the game folder, and I checked to make sure that the correct folders and assets were where they should be. so I have no clue

**Comment by Sluggo1** [comment]
what do you mean by "install"?

**Comment by Iceninja64** [comment]
Wait what you have to install spritepacks? Kind of confused on the wording

**Comment by Sluggo1** [comment]
The thing is that I'm able to gift SOME outfits to her, and I know I'm ptting the files in the right place. But she will only be able to read some of them

**Comment by Sluggo1** [comment]
I was able to gift her one of the ones she wasnt reading earlier, but I don't know why it suddenly decided to work

**Comment by totallyarandomdude** [comment]
I also got a similar problem, I gave Monika shell bikini and i didn't work(some cloths might be deleted by the devs)(my guess)
