### ISSUE TITLE
game effection broke.

### ISSUE THREAD

**Issue by Videogame-Oscar** [Monika-After-Story/MonikaModDev#9749]
![image](https://user-images.githubusercontent.com/78685277/202904827-0c01ec88-5a42-4c09-a634-ef7a3aa6195b.png)

**Comment by dreamscached** [comment]
What is wrong here?

**Comment by my-otter-self** [comment]
they probably mean the "FREEZE!". you can only get a specific amount of affection per day.

**Comment by Wingdinggaster656** [comment]
I can't see anything weird in your log -- if you think that you are not getting affection from `monika_love` is weird, I can tell you it's 100% designed.

Like what my-otter-self said: You can only get a specific amount of affection per day.

**Comment by Videogame-Oscar** [comment]
i know i  had the affection before at like 200 or something and this happens

**Comment by Booplicate** [comment]
Send the entire log file, please.
