### ISSUE TITLE
Can't restore backup

### ISSUE THREAD

**Issue by Spakrky** [Monika-After-Story/MonikaModDev#9757]
I just redownloaded MAS, and i can't restore my backup. I've got all the files (persistent, db.cmal, auto.save,...). I've put them all into the saves location but it's still like new.

**Comment by dreamscached** [comment]
Are you sure you're putting stuff into the right place? Where are you trying to put it?

**Comment by Spakrky** [comment]
Into C:\Users\USER\AppData\Roaming\RenPy\Monika After Story, i also tried C:\Users\USER\AppData\Roaming\RenPy\DDLC-MonikaBeforeStory

**Comment by Booplicate** [comment]
Did you close the game before restoring persistent? Can you describe your process of restoring a backup?

**Comment by Spakrky** [comment]
I did close the game, after that i put the persistent into the folder and tried opening the game.

**Comment by Wingdinggaster656** [comment]
Consider the possibility that there is a problem with your backup of `persistent` files.

Please upload your `persistent` here.

**Comment by Spakrky** [comment]
> Consider the possibility that there is a problem with your backup of `persistent` files.
> 
> Please upload your `persistent` here.

It won't let me.

**Comment by Spakrky** [comment]
Got it onto dropbox https://www.dropbox.com/s/4qlslgg58lb3lja/persistent?dl=0

**Comment by Booplicate** [comment]
This is not a new-new persistent, but it's quite fresh, so perhaps you're not that far in the game or you backed up something else.

**Comment by Spakrky** [comment]
Aw man, i won't be able to play chess for some time. :/
Thanks anyway! :D
