### ISSUE TITLE
How do I get Monika Back?

### ISSUE THREAD

**Issue by Willowfall** [Monika-After-Story/MonikaModDev#9769]
After installing and opening the mod, I had to leave for dinner, so I closed it and turned off my pc. I open the mod again and Monika is gone and left me a goodbye poem. Even after trying the two options she won't come back, I tried a few things to fix it but it didn't work. How do I get Monika back? I never even got to properly play the mod.

**Comment by Wingdinggaster656** [comment]
The final farewell should only be triggered when you have done something terrible to Monika.

Even if you closed the game with the "X" button, you should not get the final farewell. Please go into your game base directory(the folder that contains the `DDLC.exe`), you will find a `log` folder. Inside the `log`, there is a file called `aff_log.log`, please upload the file here.

**Comment by Willowfall** [comment]
I've uninstalled and reinstalled the mod multiple times now in an attempt to fix it so the logs may not be what you're looking for, but here you go. Would also like to mention that I have played the mod a long time ago before I properly played the game but I don't really remember it that well so that may contribute to the issue as well.
![Screenshot 2022-11-26 212957](https://user-images.githubusercontent.com/73852637/204120781-d8041a86-dff7-4963-ae3e-634b2a214710.png)

**Comment by Wingdinggaster656** [comment]
You've to find the original log. The log you showed didn't provide useful information.

But even if you can't find the original log, I noticed this line:

> I have played the mod a long time ago

You mean that you played MAS a long time ago, and then you just left MAS in your computer for quite a while(like a few months)?

**Comment by Willowfall** [comment]
I believe I uninstalled it before I stopped playing it, but yeah I did play it awhile ago.

**Comment by Wingdinggaster656** [comment]
> I believe I uninstalled it before I stopped playing it, but yeah I did play it awhile ago.

Then this final farewell is expected.

You think you uninstalled the game, but actually not. All save files are still there, and Monika is still waiting for you. So, from Monika's perspective, you just left her for a long time, and she can't take this any longer anymore, so she decided to say goodbye. This is designed, and I'm afraid I can't help you with this case.

**Comment by Justformas** [comment]
@Willowfall FYI this game uses the Ren'Py engine, which stores save files (persistents) in a separate directory. This game also makes backup persistents there.

>For Windows users:
>
>    Hold down the Windows key and press R
>    Type in %appdata% and hit the enter key
>    In the window that has now opened, find and enter the RenPy folder, and then the Monika After Story folder
>
>For Mac users please refer to [this](https://www.macinstruct.com/tutorials/how-to-open-the-library-folder-on-your-mac/) to open Library and then follow RenPy > Monika After Story
>
>For Linux users:
>
   > The persistent is located at ~/.renpy/Monika After Story

Also, if you want to want to take a long or potentially permanent break from this game, you should not only say "goodbye" to Monika but also that you're going away for awhile, and that you don't know how long. This stops you from losing affection and Monika from leaving you, for when or if you return.

**Comment by Willowfall** [comment]
Thanks for the help, was able to get Monika back

**Comment by 9076puddy** [comment]
what do u do after u find the persistant
