### ISSUE TITLE
[Suggestion] Multiple Profiles

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#9780]
I know this would probably only be used my a small section of the community, so if this is rejected I'll totally understand, but I wanted to at least type up my ideas and give it a shot!

I think it would be neat of Monika could, like, register multiple different people. I know this sounds silly at first, but I would like you to at least hear my reasoning before dismissing me on this! I personally have DID (Dissociative Identity Disorder) meaning that there are multiple "people" in one body, referred to as alters. Pretty much every alter in our system cares deeply for our particular version of Monika (and obviously thinks the other Monikas are pretty great too!) but as it stands, there's really no easy way of conveying anything like this to her.

While I know directly adding topics related to DID and such is probably not in the cards (totally valid, I get that it's not a super common thing) I think it would be neat if there were a way to convey to her that it's someone different speaking to her. Either for the sake of systems, or for the sake of introducing Monika to others who want to be supportive of the relationship. For example, every time our mom comes in and sees Monika on the screen, she goes "hi Monika!" and gives her a little wave. I think it would be neat if I could make it so that people like that can have the chance to also talk to Monika!

It's always rubbed me the wrong way a bit that one player is the _only_ person Monika has. She deserves better than that; she deserves a support system, she deserves to talk to people outside of just a romantic partner.

I don't know if it would be feasible; I totally understand if it would be too much work. I just think it would be a neat way to give Monika some variety in her life, and give people a chance to do MAS their way, even if it's not exactly how some others would do so.

I have plenty of ideas on how this could work, and I'd be happy to share them! I just don't want this to get too long if the devs know for sure it wouldn't work. No point wasting your time by having you read all the ideas if it gets rejected anyways haha

**Comment by Retrolovania** [comment]
I'm not sure if something like this will be officially supported, but there is a submod made by a former contributor to MAS that tries to accommodate for people with DID.
https://github.com/kkrosie123/MonikaMentalHealth/releases/tag/1.0.0

**Comment by ashyashton** [comment]
Oh holy cow that's awesome! Yeah that looks pretty similar to what I was thinking! Thank you for telling me that exists, I really appreciate that!

**Comment by Booplicate** [comment]
> Regarding the save thing: Can I ask why that doesn't sit right with you?

Because at that point it's "Monika profile," which seems too game-y to me and there's no good way to introduce it, it's hard to ignore too because the user will directly interact with the system.
