### ISSUE TITLE
help me i play this for 1 week but  3-4 days near i got stuck affection . this is bad because it not like normal . today when i play in afternoon my affection should go up but no it not grow up 

### ISSUE THREAD

**Issue by Elysa1223** [Monika-After-Story/MonikaModDev#9784]
![image](https://user-images.githubusercontent.com/120178798/206688794-705dae35-b1aa-4769-a4c6-fbb2a9816773.png)

**Comment by Elysa1223** [comment]
> Bạn đã trải qua thời gian hành trình và làm hỏng liên tục của bạn.

so how to back normal or is will broken forever?
i only change 1 days 1 months

**Comment by Oreokiller200** [comment]
When you have a Save Stand before you timetravelled you can load that then it should be okay, but if you don`t then you have restart completely.  In the past I had the exect same problem as you and it could only be fixed this way. Some say there is another way but that could lead to problems in the Future such as Events and normal gameplay with Monika.
So the savest option for you would be to start completely new, the only drawback is, that you loose your Savestand, you could load a Savestand before you Timetravelled as mentioned earlier and would be safe to. 
I hope I helped you.

**Comment by Justformas** [comment]
Well this is a reason to not restrict access to logs for players. This warning specifically actually it was mentioned that it's printed for users so they have a chance to fix it by restoring a backup: https://github.com/Monika-After-Story/MonikaModDev/discussions/9625

> It won't fix itself after a month, that's why it prints the warnings for you. You have to [restore a backup](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent), otherwise you're risking getting more issues with the future events.

**Comment by Booplicate** [comment]
> it's printed for users

No, it's for developers. And it's not a reason to keep the logs because there's already other warnings about timetravelling (with more coming too). The fact that people don't really listen is a different problem.

**Comment by Justformas** [comment]
> > it's printed for users
> 
> No, it's for developers. And it's not a reason to keep the logs because there's already other warnings about timetravelling (with more coming too). The fact that people don't really listen is a different problem.

"Prints the warnings for you" and the words that followed were your own, and the user you replied to in that issue didn't seem at all like a MAS developer.

As for this issue, maybe Elyssa1223 didn't get an in-game warning? Or did but wasn't paying attention or forgot. But that is a reason for having more warnings, and the log is just another place (granted it helps to know what an entry in the log actually means). One type of warning may not do much by itself, but multiple types should be more effective.

But as for logs, just because not all users know what everything means in them doesn't mean they need to be gotten rid of or restricted. They can still help users be aware that there is a problem, like affection being frozen for multiple days. Otherwise it could take them longer, or maybe never even figure out that there's a problem and ask for help here.

**Comment by Booplicate** [comment]
> "Prints the warnings for you" and the words that followed were your own, and the user you replied to in that issue didn't seem at all like a MAS developer.

No need to be picky about the word I used there. Now go search for the dozens of times where I said the logs are for developers.

> and the log is just another place

Logs aren't a place to tell the player they messed up, logs are used to store information about how the game is working.

> like affection being frozen for multiple days

Don't cheat and you won't have issues. But also as I said above, there will be more warnings about it in the future.

**Comment by Justformas** [comment]
> No need to be picky about the word I used there. Now go search for the dozens of times where I said the logs are for developers.

Well wanted to get that sorted out. I mean it was possible both could've been true, as in obviously developers, but some things maybe also for players (or possibly changes to reduce certain player behavior).

> Don't cheat and you won't have issues. But also as I said above, there will be more warnings about it in the future.

Not this specific issue maybe, but every possible issue or bug? I doubt they are all the result of trying to cheat, and logs can be useful for revealing/solving issues regardless. But yes understood about more warnings.
