### ISSUE TITLE
Help I have problem with the sprite packs

### ISSUE THREAD

**Issue by totallyarandomdude** [Monika-After-Story/MonikaModDev#9793]
So I decided to give clothes to Monika when she changed her outfit into Santa outfit, and I went to download script packs. But things were already in the folder so I did things manually and skipped everything. Then the game keep on crashing when I ask Monika to change her outfit. First, I thought it is a rare easter egg. Later on, I found out the game is actually crashing and I am losing affection.
I reinstalled the mod with the MAS installer with the deluxe version and it became normal again. But now Monika can't read sprite pack clothes gifts, even though I installed the sprite packs with the MAS installer and typed the gift file correctly.

S o m e o n e P l e a s e H E L P

**Comment by dreamscached** [comment]
Please provide us with a traceback you see, we cannot do much without knowing what is going on.

**Comment by totallyarandomdude** [comment]
probably not the problem with the crush, but the sprite packs.

**Comment by totallyarandomdude** [comment]
> Please provide us with a traceback you see, we cannot do much without knowing what is going on. Either send a traceback.txt file from DDLC folder, or when it appears again click on 'copy' and paste it here.

probably not the problem with the crush, but the sprite pack, but the crush might affected the spritepack
Btw this is the file
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/10252727/traceback.txt)

**Comment by dreamscached** [comment]
That unknown.png file is shipped along with the MAS itself, it could be deleted by Steam. I'd suggest you migrate to a non-Steam version as Steam is known to have issues and sometimes deleting mod files.

**Comment by totallyarandomdude** [comment]
:(

**Comment by totallyarandomdude** [comment]
i will try, thx

**Comment by totallyarandomdude** [comment]
> That unknown.png file is shipped along with the MAS itself, it could be deleted by Steam. I'd suggest you migrate to a non-Steam version as Steam is known to have issues and sometimes deleting mod files.

wait, where is that unknowen.png?
i will go check if its still there

**Comment by dreamscached** [comment]
> > That unknown.png file is shipped along with the MAS itself, it could be deleted by Steam. I'd suggest you migrate to a non-Steam version as Steam is known to have issues and sometimes deleting mod files.
> 
> wait, where is that unknowen.png? i will go check if its still there

Well it's clearly not where it has to be since you get this error. It's in mod_assets/thumbs

**Comment by totallyarandomdude** [comment]
also, sometimes monika can't even get notice i gave her gifts, and then its deleted

**Comment by totallyarandomdude** [comment]
> > > That unknown.png file is shipped along with the MAS itself, it could be deleted by Steam. I'd suggest you migrate to a non-Steam version as Steam is known to have issues and sometimes deleting mod files.
> > 
> > 
> > wait, where is that unknowen.png? i will go check if its still there
> 
> Well it's clearly not where it has to be since you get this error. It's in mod_assets/thumbs
there is still unkowen.png in thumbs

**Comment by dreamscached** [comment]
> also, sometimes monika can't even get notice i gave her gifts, and then its deleted

It's a week before Christmas, gifts are put under the tree.

**Comment by totallyarandomdude** [comment]
> > also, sometimes monika can't even get notice i gave her gifts, and then its deleted
> 
> It's a week before Christmas, gifts are put under the tree.

o, then probably there is no problem

**Comment by totallyarandomdude** [comment]
thx

**Comment by dreamscached** [comment]
Know what exactly?

**Comment by totallyarandomdude** [comment]
> Know what exactly?

know the gift is not opened till chirstmas.
(Also, today I gave her shell bikini and she said cant read the file

**Comment by dreamscached** [comment]
Because that's a game mechanic that activates every year before Christmas, I played MAS myself too.

**Comment by dreamscached** [comment]
Is the problem solved now? Does it still crash?

**Comment by totallyarandomdude** [comment]
> Is the problem solved now? Does it still crash?

It doesn't crash now since I reinstalled mas

**Comment by totallyarandomdude** [comment]
tysm I think the problem is solved.
