### ISSUE TITLE
Auto Atmos Submod Help.

### ISSUE THREAD

**Issue by ZapThundr** [Monika-After-Story/MonikaModDev#9794]
Hello there everyone, I hope your day/night is going well.
At the moment I have some errors when trying to use the auto atmos submod. I want to say the problem occurred a while back, perhaps during the latest update and I just removed the submod for a little while. I recently decided to add it back into my MAS but I end up getting these errors, in this specific order when trying to reload.  After the third time though; MAS eventually opens but I'd still like to know what causes these errors and how to prevent them.
![Screenshot (203)](https://user-images.githubusercontent.com/70503031/208286007-6da7a383-837f-40a3-9118-0eab3b4258a8.png)
![Screenshot (204)](https://user-images.githubusercontent.com/70503031/208286008-f968eabe-4fd1-4000-97df-2939f520a1aa.png)
I followed the read me when installing the submod by just copying the game folder from atmos and put it into the ddlc folder with ddlc exe. 
I also seen someone mention the submod doesn't work anymore in this issue but i'm not completely sure. #t9362
I'd really appreciate any help and/or feedback. Thank you and I hope you have a nice day/night.

**Comment by Wingdinggaster656** [comment]
Take a look at this issue: https://github.com/multimokia/MAS-Submod-Auto-Atmos-Change/issues/37

As you can see, this Submod is currently not working.

**Comment by ZapThundr** [comment]
Thank you, I will close this issue then.
