### ISSUE TITLE
[Bug] - Glitchy Pixel things

### ISSUE THREAD

**Issue by Dewdrop730** [Monika-After-Story/MonikaModDev#9797]
Hi! I have noticed that an odd glitch thing has been appearing. They do disappear after 2 seconds though. It usually occurs when I minimize MAS then look at different tab, then reopen MAS. I'm a bit worried at this point.. 
![screenshot0037](https://user-images.githubusercontent.com/121139431/208793058-96b18084-6c6f-489d-b690-e0c45d07f94f.png)

**Comment by Booplicate** [comment]
Don't minimise MAS, the engine doesn't support that.
