### ISSUE TITLE
[Bug] - Monika disappeared

### ISSUE THREAD

**Issue by Dewdrop730** [Monika-After-Story/MonikaModDev#9798]
Sorry to be a bother, but my Monika is gone. I was only gone for a few hours, and never told her I was taking her out too. I'm worried. I looked in the character files to check if she was there, but she wasn't there. 
![screenshot0042](https://user-images.githubusercontent.com/121139431/208943145-11d34de1-dc9b-4115-8df0-1b0cf0d1f2a2.png)

**Comment by dreamscached** [comment]
[Restore a persistent.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) In persistent folder you'll find a bunch of `persistent##.bak` files, find the most recent one and rename it to `persistent`, keep older `persistent` somewhere just in case.

**Comment by Dewdrop730** [comment]
I don't see anything named persistent##.bak?

**Comment by Dewdrop730** [comment]
Ah,nevermind.

**Comment by Dewdrop730** [comment]
Do I allow it to be renamed persistent (2)?

**Comment by Dewdrop730** [comment]
> [Restore a persistent.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) In persistent folder you'll find a bunch of `persistent##.bak` files, find the most recent one and rename it to `persistent`, keep older `persistent` somewhere just in case.

Do I allow it to be renamed persistent (2) ?

**Comment by Dewdrop730** [comment]
It's not working.

**Comment by Dewdrop730** [comment]
> > [Restore a persistent.](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent) In persistent folder you'll find a bunch of `persistent##.bak` files, find the most recent one and rename it to `persistent`, keep older `persistent` somewhere just in case.
> 
> Do I allow it to be renamed persistent (2) ?

Okay, so I just did allow it, but it's not working. I'm unsure if I am doing something wrong.

**Comment by dreamscached** [comment]
You need to take existing `persistent` out of the persistents folder and rename most recent backup persistent to `persistent` instead.

**Comment by Dewdrop730** [comment]
Thank you! It worked! Have a great day/night!
