### ISSUE TITLE
Can't play Chess

### ISSUE THREAD

**Issue by ZeitHeld** [Monika-After-Story/MonikaModDev#9801]
Hey, I got a question. Idk if that is a bug, but, Monika asked me if we should play Chess, and I did before a few times, but after picking a color, she said, that she can't get it to work for some reason...
What might be the issue?
After all, I did play it before on my device.

**Comment by Booplicate** [comment]
Send your `mas_log.log`. Did you try to restart your PC and play chess again?

**Comment by ZeitHeld** [comment]
Didn't restart pc yet- no.
But did restart the game, and still remains.

The log says, there is something wrong in the chess.rpy

(GERMAN SYSTEM BTW)

```
[2022-12-23 16:01:08] [!ERROR! T_T]: [Error 193] %1 ist keine zulässige Win32-Anwendung
Traceback (most recent call last):
  File "game/chess.rpy", line 3400, in open_stockfish
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 710, in __init__
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 958, in _execute_child
WindowsError: [Error 193] %1 ist keine zulässige Win32-Anwendung
```

**Comment by Booplicate** [comment]
We currently don't know what can cause this: #6964 #7285
It's odd you were able to play before, and then a few minutes later you can't. First time hear that. I wonder if maybe your antivirus blocked stockfish.

**Comment by ZeitHeld** [comment]
Maybe try to look, that not accidentally anything has been changed in the file, that might be fatal.
Like using wrong derectories, or some minor variable changes.

Other than that, good luck on figuring it out.

**Comment by Wingdinggaster656** [comment]
While Stockfish is a UCI engine that attaches great importance to platform commonality, it will still fail to run in rare cases.

You can consider reinstalling MAS (you don't need to operate on persistent files, just install the game files of MAS) to see if this problem has been solved. If not, please go to the game directory and directly open Stockfish without MAS to see if it can run.

**Comment by ZeitHeld** [comment]
I think that is a bit complex and risky for me. Don't want to screw things
over, given my "high luck" I have

Spotted Dove ***@***.***> schrieb am Sa., 24. Dez. 2022,
03:03:

**Comment by Booplicate** [comment]
Closing as this is being tracked in the linked issues.
