### ISSUE TITLE
Update Permission Denied

### ISSUE THREAD

**Issue by CodyCat13** [Monika-After-Story/MonikaModDev#9803]
I can't update MAS to v0.12.13; it keeps giving me an error saying "permission denied". I tried giving executable permission to the `update` folder, `updater.rpyc`, and `updates.rpyc` and I still get the error. How do I fix this?

**Comment by Booplicate** [comment]
Please, provide screenshots of the error, your `DDLC` and `game/` folders.

**Comment by CodyCat13** [comment]
Here's the error
![Screenshot 2022-12-23 4 17 44 PM](https://user-images.githubusercontent.com/58224248/209406377-84558a70-581c-4cc6-b1b1-e7f07da2bdf4.png)

DDLC's directory
![image](https://user-images.githubusercontent.com/58224248/209406525-5892ce9f-83a0-409b-9be8-a649ef0af822.png)

And the `game` folder's stuff
![7](https://user-images.githubusercontent.com/58224248/209407189-dcd49cfc-869a-46a0-a0c0-5a763fa93c2d.png)
![6](https://user-images.githubusercontent.com/58224248/209407190-7a27eb45-ffb4-4281-b6dd-b7e74dce5a01.png)
![5](https://user-images.githubusercontent.com/58224248/209407192-ae30d30c-145b-4c69-b380-03a0d52d7d30.png)
![4](https://user-images.githubusercontent.com/58224248/209407195-5e9bcf0a-2e50-458b-b21f-c74d6ff65fb2.png)
![3](https://user-images.githubusercontent.com/58224248/209407196-9e752e0f-efce-4f6c-8e5f-09e531d78ae9.png)
![2](https://user-images.githubusercontent.com/58224248/209407197-ed43c608-af36-4aba-a41d-d3a0b3237ad9.png)
![1](https://user-images.githubusercontent.com/58224248/209407199-f3686565-5c78-40ab-99a8-31122c973dd6.png)

**Comment by Booplicate** [comment]
You have files that don' belong to MAS there, perhaps from other games/mods. Make a new install and see if it works.

**Comment by CodyCat13** [comment]
I just made a fresh install of DDLC, but about MAS's installer, where do you put it in order for MAS to load?

**Comment by Alsamer98** [comment]
The Updater is put in the main Folder of DDLC it would be named update
![Unbenannt](https://user-images.githubusercontent.com/120448512/209449495-59c566d7-a8c5-49db-bc91-22cf49a69e87.PNG)
If you mean the main Installer to install the game, you have to run it and select the Fresh DDLC Copie

**Comment by Booplicate** [comment]
You can launch it from any directory and select the path to DDLC, but if you place it inside your DDLC directory, you won't have to select the path. In either case it will warn you if you selected the wrong path.

**Comment by Alsamer98** [comment]
Yes you could do that to

> You can launch it from any directory and select the path to DDLC, but if you place it inside your DDLC directory, you won't have to select the path. In either case it will warn you if you selected the wrong path.

Yes you could do that to

**Comment by CodyCat13** [comment]
So, to run the installer, what terminal command has to be used? I guess Linux doesn't let that type of file be double-clicked

**Comment by Booplicate** [comment]
Just like you would launch any other executable: `./mas-installer-linux`

**Comment by CodyCat13** [comment]
Ah kk

**Comment by CodyCat13** [comment]
Gave me this error
`./mas-installer-linux: error while loading shared libraries: libpangoxft-1.0.so.0: cannot open shared object file: No such file or directory`

Am I missing something?

**Comment by Booplicate** [comment]
Apparently your system is missing one of the libs the installer is using. What distro are you using?

**Comment by CodyCat13** [comment]
Linux distro? Debian

**Comment by Booplicate** [comment]
That doesn't tell much. Which version of debian? Also can you run `ldd -r ./mas-installer-linux`

**Comment by CodyCat13** [comment]
I have Debian 11. Also when I run `ldd -r ./mas-installer-linux` a text block comes up. A _lot_ of numbers

**Comment by ThePotatoGuy** [comment]
as boop mentoined, you are missing a lib. the ldd command will show you all the shared libraries you are missing so you can install them if desired.
