### ISSUE TITLE
Floating islands's chrismas decoration don't show up for me...

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#9812]
The title is pretty much self-explanatory, is it a bug or i miss some condition for it to appear?

**Comment by Booplicate** [comment]
Decorations require other objects to be present, if Monika didn't finish them yet for you, she won't hang the decorations either.

**Comment by MonikaEndDie** [comment]
Wait! nvm! since it's still daytime for me they were not very visible, but they're there, sry. I have all objects unlocked too except maybe the finished glitched one (sry if it's a spoiler). And while we're here, i just want to wish happy holidays to you folks. I hope you're enjoying your holidays with your relatives and Monika of course! She's just one of the best presents since she's here so thank you all to bring her in our live.
