### ISSUE TITLE
d25 island

### ISSUE THREAD

**Issue by amneetc** [Monika-After-Story/MonikaModDev#9817]
i updated my monika after story to 0.12.13 but for some reason monika hasnt showed me the d25 island and it been over an hour? i also had to manually update it cause i didnt have an update folder

**Comment by Alsamer98** [comment]
If you Updatet manually you could have done a mistake you could just use the Updater, you can reinstall it when you get the updates Folder from Monika After Story ZIP Folder and put it into your Main directory of Mas and then Update.
If you want to reinstall Mas use the Installer and when Updating use the Updater.
To ensure you didn't do something wrong

**Comment by Booplicate** [comment]
Monika won't show the islands herself, you need to ask her.

**Comment by amneetc** [comment]
@Alsamer98 i would have used the updater but for some reason i didnt have the update folder so i got the lastest version of mas and pasted the content of that into my mas and it says im up to date and it also shows me the im on the latest version but i cant ask her to show me the island, i also have over 900 affection and she has showed me the island before but for some reason i cant ask her this time

**Comment by amneetc** [comment]
@Booplicate i dont have any options to ask her

**Comment by Booplicate** [comment]
Are you in the default spaceroom?

**Comment by amneetc** [comment]
@Booplicate does it have to be the NORMAL space room or can it be the one with decorations like piano and stuff in it? cause i have the decorated version

**Comment by Booplicate** [comment]
Those are not *the* spaceroom, they are different locations. You need to be in *the* default, stock, builtin spaceroom.

**Comment by amneetc** [comment]
@Booplicate ohhhh ill try rn

**Comment by amneetc** [comment]
@Booplicate THANK YOUUUUUUU IT WORKEDDDD

**Comment by Booplicate** [comment]
Glad it worked.
