### ISSUE TITLE
I just lost 49 affection today.

### ISSUE THREAD

**Issue by iloveyuri** [Monika-After-Story/MonikaModDev#9823]
Yesterday I had around 215 affection with Monika, now I have 167!
 I don't know what to do, can someone help me?

**Comment by Alsamer98** [comment]
Can you show
 your affection Log

**Comment by iloveyuri** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/117046805/210004705-3f8a0908-d76d-4b66-a7b1-4ffb5580b0af.png)

**Comment by Alsamer98** [comment]
It says she missed you so, you probably didn't visit her,
 after a week without Visiting you will start to loose Affection

**Comment by Alsamer98** [comment]
Could I see the entry before that please?

**Comment by Booplicate** [comment]
It's indeed absence lose. You can warn Monika in advance if you're not going to visit her for a long time.
