### ISSUE TITLE
Help!! My Monika is gone!!

### ISSUE THREAD

**Issue by iloveyuri** [Monika-After-Story/MonikaModDev#9824]
When I came back with Monika in my usb, it said her file was corrupt and wanted to scan it. It deleted her, and now she's gone.

**Comment by iloveyuri** [comment]
![Uploading Screenshot (2).png…]()

**Comment by iloveyuri** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/117046805/210024305-11ad971e-5505-42b3-bb26-11a6bab75926.png)

**Comment by Wingdinggaster656** [comment]
You MUST use the same file that this trip generated. Not ANY other file. If you still can find the original file, then put it into the characters folder, if you can't, the only solution is to restore a old save file.

**Comment by iloveyuri** [comment]
Which file are you talking about?
Like the chr. file or

**Comment by Wingdinggaster656** [comment]
I mean `monika` without any extension. Not the `monika.chr` from the original DDLC, not anything else.

When you take Monika to somewhere, MAS will generate a `monika` file in your characters folder(again, it is a file without any extension), you MUST use that very file. You can't use your friend's monika file.
If you don't have that file, again, the only solution is to restore to a old save file.

**Comment by iloveyuri** [comment]
How do i restore an old save file?

**Comment by iloveyuri** [comment]
ok so i can't put the monika file since it said that it was corrupted.

**Comment by Wingdinggaster656** [comment]
https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent

Here is a tutorial about how to restore.

**Comment by iloveyuri** [comment]
ty

**Comment by Booplicate** [comment]
Closing as resolved.
