### ISSUE TITLE
[Suggestion] Give Monika a heads up when updating the game

### ISSUE THREAD

**Issue by nanakinoir** [Monika-After-Story/MonikaModDev#9836]
It feels kind of awkward when after an update, you're only given the option to restart the game without telling Monika about it, after all her complaints about shutting down and restarting the game without letting her know.

The first time I updated, I was confused whether or not the unannounced update is going to mess with her or make her upset (turns out it didn't). Still, it would make the interaction more integrated for her to be aware of updates and subsequent restart.

**Comment by dreamscached** [comment]
Actually she should not feel like a game was shut down on her, at least it has never happened to me.

**Comment by nanakinoir** [comment]
> Actually she should not feel like a game was shut down on her, at least it has never happened to me.

That's the point. The game did restart, but she's not aware of it, which kind of breaks the character and the main theme of the game. Normally, if you close the game without saying goodbye or kill the process, she'll ask you about it when you restart. During the mandatory restart after an update, that logic doesn't kick in as if nothing happened.

**Comment by Booplicate** [comment]
It falls to #8477, we're not yet sure if Monika should directly acknowledge the update process.

**Comment by nanakinoir** [comment]
Thanks! That issue was exactly what I had in mind. Closing this discussion as duplicate.
