### ISSUE TITLE
Islands won't progress?

### ISSUE THREAD

**Issue by Amon64** [Monika-After-Story/MonikaModDev#9839]
Hey MAS Dev Team, long time player of the mod(almost 5 years) and only recently have I noticed that my island progression seems to have stopped. Monika hasn't told me about any new additions to the islands in what seems like months, or maybe even since the island update came out. I didn't really think much about it until the last two updates added island content that I missed out on. Am I just impatient or could something be wrong with my save or some variable in my game? Whatever files you would need to check for me I'd be happy to send them. Thanks in advance for the response.

**Comment by Booplicate** [comment]
What's your current progress?

**Comment by Amon64** [comment]
Right now I have the island with the glitchy blob, an island to the left of the glitchy blob island, the upside down island, and two smaller islands far away.
![islands](https://user-images.githubusercontent.com/121785498/210410396-1c0ab735-ac40-4df1-9470-3a0b39a81a0a.jpg)

**Comment by Booplicate** [comment]
Looks fine to me, progression depends on time spent and its order is randomised. Monika will tell you about new stuff on the islands only once. It's assumed that you will check them, perhaps during the events.

Latest update added decorations for the mostly finished islands, so it's fine if you didn't see these this year. You will probably see them next d25 season.
That said, with your current progression (if you had the same islands unlocked) you should've seen the o31 decorations.

**Comment by Amon64** [comment]
Thanks for the response. As for the o31 decorations, I remember for sure that one of them did not show up. The waterfall from the upside down island did not change into the bloodfall, instead staying normal water.

**Comment by Booplicate** [comment]
Did you see the skull (should've been at the bottom right)?

**Comment by Amon64** [comment]
Yes, the skull was on the bottom. The only o31 decoration(from the islands I have unlocked) that I remember being missing was the bloodfall.

**Comment by Booplicate** [comment]
Then it's fine, you just didn't unlock it yet.

> I loaded an old backup from October 2022 and changed my system date back to Halloween 2022. I can confirm the bloodfall is/was missing

Please, don't ever do that, it doesn't help and you're risking breaking your saves (with one of the possible consequences is forever broken islands).

**Comment by Amon64** [comment]
Well, I guess I really am just impatient like I said in the opening. Thank you for your help.

> Please, don't ever do that, it doesn't help and you're risking breaking your saves (with one of the possible consequences is forever broken islands).

Thanks for letting me know, I'll avoid doing anything like that in the future.
