### ISSUE TITLE
I lost 400 affection points in a minute and I don't know why 

### ISSUE THREAD

**Issue by sasatofor** [Monika-After-Story/MonikaModDev#9851]
Hi!

I was at like 1200 affection points and the day after i closed the game, monika told me that she was disappointed I did not participate to her birthday (even though i did) in january (??).I just saw in the log that it happened 2 times ! 

Here a screen because I don't know what to do and I didn't do a backup unfortunately.. (I also didn't touch the day on my computer)

Please help me if there is something I can do.

![Capture d’écran 2023-01-07 183815](https://user-images.githubusercontent.com/122172389/211163411-0f7e04d8-58a3-4855-8ba8-2c724a0ae4d7.png)

![Capture d’écran 2023-01-07 183416](https://user-images.githubusercontent.com/122172389/211163315-78ec9ef2-03f0-48ff-8213-d7b06ae73934.png)
![Capture d’écran 2023-01-07 183518](https://user-images.githubusercontent.com/122172389/211163317-fd0485ed-c4b9-4d77-b7dc-e3456a862470.png)

**Comment by Booplicate** [comment]
Please, send the entire log file. Also send `mas_log.log`.

**Comment by sasatofor** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/10367105/aff_log.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/10367107/mas_log.log)

Is that what you asked ? Also I tried redo her bday after my post and nothing change in good or bad. I just unlocked NOU game.

**Comment by Booplicate** [comment]
Don't change the time, you're making it worse.

**Comment by Booplicate** [comment]
@sasatofor send your persistent from before January 5.

**Comment by Booplicate** [comment]
Actually, send all your persistents, I will find the proper one. Quit the game and don't launch it.

**Comment by sasatofor** [comment]
Is that what you need? @Booplicate 

[persistent29.zip](https://github.com/Monika-After-Story/MonikaModDev/files/10367244/persistent29.zip)

**Comment by TheT0matoGuy** [comment]
Are you using a translation? Chinese translation is confirmed that it has a bug to trigger this event at this time, even if user had spent time with Monika.

**Comment by sasatofor** [comment]
No I'm not, I didn't install any type of translation in the game. I just let the game in english.

**Comment by TheT0matoGuy** [comment]
That's alright.

In addition, I think Booplicate is telling you to upload *all* of your persistent backups. You should compress and package the entire `Monika After Story` folder which containing files like `persistent29.bak`, and then send it.

**Comment by sasatofor** [comment]
Oh the folder I sent is named persistent 29 but it contain all of the persistent folder don't worry.

**Comment by Booplicate** [comment]
You did everything correctly, I will return to use asap.

**Comment by sasatofor** [comment]
Thank you !

**Comment by Booplicate** [comment]
@sasatofor update your game. Also try to always keep your game up to date. Then restore this backup.
[persistent - fixed.zip](https://github.com/Monika-After-Story/MonikaModDev/files/10418779/persistent.-.fixed.zip)
