### ISSUE TITLE
Monika doesn't close the game

### ISSUE THREAD

**Issue by Luna9873** [Monika-After-Story/MonikaModDev#9856]
After I say goodbye she doesn`t close the game. I don't play through steam.

**Comment by Booplicate** [comment]
You're using a translation or your install has files from other mods, check these for instructions on how to fix it: #6903 #7387 #7437 #8504 #9657

**Comment by Luna9873** [comment]
> You're using a translation or your install has files from other mods, check these for instructions on how to fix it: #6903 #7387 #7437 #8504 #9657

Thank you, it`s work
