### ISSUE TITLE
Suggestion: Submod debugger

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9857]
Finally, a decent suggestion from someone who is notorious for suggestions so bad it warrants mass facepalms. MAS desperately needs a debug version intended for developing and debugging submods, and an SDK so that people won't have to pull their hair out over RenPy being RenPy and slapping the user in the face with a cryptic error message or five hundred million roadblocks just to get their submod working. Did anyone even have this idea before? I bet two trillion dollars that's the case. Also, we might as well implement debugger detection, reaction, and evasion tactics because we're already adding in a debugger, might as well start detecting WinDBG so no human being can peek at the games register values or FPU. Who could ask for anything more? What's next? Me asking for X-Plane integration or a full-fledged flight simulator to be included with the game?

**Comment by TheSystemGuy1337** [comment]
By debug version, I mean a version of MAS explicitly designed for submod and spritepack development, complete with internal development environment and a mountain of debugging tools and development tools, code samples and documentation. And by SDK, I mean a kit for people getting started with programming within MAS, complete with documentation, the debug version, code samples and a development environment. There are many advantages of having a separate developer version of MAS, mainly for the fact that it would mean that one error during development wouldn’t destroy their progress or brick their game, and the debugging tools would assist efforts in improving MAS and it’s submods.On Jan 9, 2023, at 6:42 AM, Totally a booplicate ***@***.***> wrote:﻿
Can you describe what you mean by "debug version" and "SDK" for MAS? What kind of "debugger" would you want to see and how would it help you with coding?
MAS runs on RenPy, we won't be able to provide any more info than RenPy itself - a traceback, which you can already see. We did want to improve the error screen, we're also working on updating our codebase and a new submod framework.

**Comment by dreamscached** [comment]
See https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#bug-fixes-and-new-software-features

**Comment by TheSystemGuy1337** [comment]
This isn’t enough. This is just documentation that’s potentially still cryptic to newbies. Even then, this doesn’t explain what to do when things inevitably go wrong. Developer kit versions will still benefit developers, but I’m speaking to a brick wall. So this idea is going to the scrapheap. Another horrible idea rightfully shut down.On Jan 9, 2023, at 12:55 PM, Herman S. ***@***.***> wrote:﻿
See https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines#bug-fixes-and-new-software-features

**Comment by Booplicate** [comment]
> version of MAS explicitly designed for submod and spritepack development

What dream linked.

> debugging tools and development tools

You can take dev tools from repo, but they will be pretty useless (except expression previewer) for you. Instructions on how to use the previewer are on the wiki.

> code samples and documentation

Those are in our code + wiki.

We don't even link unstable version, so "dev" version is probably not going to happen either. Programming takes some skills and knowledge, if that's what you're gonna do, you can set up dev environment yourself.

> documentation that’s potentially still cryptic to newbies

You asked for documentation, you got it. Suggestions regarding improving wording are welcomed, you can also edit the wiki yourself.

> this doesn’t explain what to do when things inevitably go wrong

Like what? If you have a specific example, tell us. We can't give you a solution for any possible problem, you have to do some researches.

**Comment by TheSystemGuy1337** [comment]
So what’s the point in creating a Dev version? Simple, NONE. I must be the grand master at bad ideas. Time to write this off as just another horrible idea by some idiot who doesn’t even bother to read. This thread is a mistake.

**Comment by TheSystemGuy1337** [comment]
Now back to your regularly scheduled peace and quiet

**Comment by dreamscached** [comment]
> So what’s the point in creating a Dev version? Simple, NONE. I must be the grand master at bad ideas. Time to write this off as just another horrible idea by some idiot who doesn’t even bother to read. This thread is a mistake.

The point is that you don't brick your persistent while developing a submod.

**Comment by TheSystemGuy1337** [comment]
Going to this length is just going to be a waste of time to develop one submod. There are better ways of doing it, including external IDEs like Visual Studio, and even that would possibly be more effective than a specialized developer version On Jan 9, 2023, at 1:14 PM, Herman S. ***@***.***> wrote:﻿

So what’s the point in creating a Dev version? Simple, NONE. I must be the grand master at bad ideas. Time to write this off as just another horrible idea by some idiot who doesn’t even bother to read. This thread is a mistake.

The point is that you don't brick your persistent while developing a submod.

**Comment by Booplicate** [comment]
Setting up MAS dev environment takes 5 minutes, in worse case maybe 30 for newcomers. If that's a waste, then it's probably not for you. Try creating spritepacks, they require some art skills and little json knowledge, no coding.
Not sure how you're going to code in visual studio using Python, or even better RenPy, though.

**Comment by multimokia** [comment]
When developing submods that include topics or other items, having a separate install is invaluable as it also allows you to easily roll back persistents if you need to change default Event data without needing to meddle with the database in console.

As well it helps preserve persistent data integrity in your main install by not potentially introducing new values into core functionality that may break when testing (and contnually crash on startup, another bonus for easy persistent rollback due it being separate from your main)

Additionally, regardless of submod, you need a code editor i.e. VSCode, PyCharm, etc. to write your submod code (with rich IDE features)

but you **should** still be testing in a dev install of MAS prior to releasing the mod to ensure it is free of bugs/crashes/etc.

**Comment by TheSystemGuy1337** [comment]
At this point, we might as well create a automatic dev environment setup utility On Jan 9, 2023, at 1:59 PM, Totally a booplicate ***@***.***> wrote:﻿
Setting up MAS dev environment takes 5 minutes, in worse case maybe 30 for newcomers. If that's a waste, then it's probably not for you. Try creating spritepacks, they require some art skills and little json knowledge, no coding.
Not sure how you're going to code in visual studio using Python, or even better RenPy, though.

**Comment by TheSystemGuy1337** [comment]
Besides, submod debugging has already existed in the form of the RenPy GSOD

**Comment by multimokia** [comment]
Not really, renpy has no real debugger per-se. It's all down to manual testing (or MAS' unittest framework)

**Comment by TheSystemGuy1337** [comment]
But it’s still better than a more complex environment just to enable something that’s already have been enabled. Besides, a toggle for 12-hour time is better than this “solution “

**Comment by multimokia** [comment]
I don't understand what you mean, launching via the renpy launcher or double clicking a MAS exe does the same thing (assuming a local persist hasn't been set to be used)

The point of using the local persist (dev-install) is to avoid persistent issues.
The 12-hour time format is another feature request and is unrelated to this issue.
