### ISSUE TITLE
Add toggle for 12-hour time for sunrise and sunset settings

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9858]
Here we go again. A big annoyance of mine (and other people) is that the sunrise and sunset settings are in 24-hour military time instead of the standard 12-hour time 99% of us are used to. Instead of a nuclear solution (in this case switch to 12-hour time), there should be an option to use 12-hour time, however the game should still internally use military time. Besides, I don't think many people use 24-hour time, so this adds additional complexity in playing this. Granted, there are converters out there, but nothing beats a physical toggle to switch between the two standards.

**Comment by dreamscached** [comment]
I think we could rather use locale settings instead and format time based on user's preference.

**Comment by Booplicate** [comment]
![Capture](https://user-images.githubusercontent.com/53382877/211412810-d5509daf-cb11-4e55-a41b-adaf37a18d44.PNG)

**Comment by TheSystemGuy1337** [comment]
Better idea, but this presents a potential roadblock. How do we read locale information from RenPy on Windows and macOS systems?On Jan 9, 2023, at 1:28 PM, Herman S. ***@***.***> wrote:﻿
I think we could rather use locale settings instead and format time based on user's preference.

**Comment by dreamscached** [comment]
I'm pretty certain Python has a standard way of formatting time locale-based, the mechanism for it is pretty much uniform on each platform.

**Comment by TheSystemGuy1337** [comment]
And since we're on this topic, we should make it where MAS can automatically look up sunrise and sunset information from the internet via ZIP code or users address (with their permission of course)

**Comment by dreamscached** [comment]
There's a submod that does that I think, that would require a use of external service that provides such info; unsure what's the position of MAS devs on that.

**Comment by TheSystemGuy1337** [comment]
I don't think the MAS devs would probably like that, or they might think it's a breach on privacy. So, a compromise is to look at the system's locale and set 24-hour, military and 12-hour time automatically.

**Comment by dreamscached** [comment]
If someone moves they don't immediately give up their cultural preferences, it's a long process. Plus if they want to change locale they will, time format doesn't depend on timezone, so doesn't sunset/sunrise time.

**Comment by TheSystemGuy1337** [comment]
So, I have no more issues with this. I’ve finally provided a GOOD SUGGESTION

**Comment by Booplicate** [comment]
Not sure how much sense it makes to have a toggle for *another* setting.
Maybe if Monika asked what time format you're using, which she could use too later on, I could see this happening.

**Comment by TheSystemGuy1337** [comment]
Well. This is unfortunately not going anywhere. What a surprise. My brightest idea gets thrown out. Since I have no more good ideas, and this idea is out the window, I’m simply going to give up bringing any of my half decent ideas since it’s just going to get thrown out. This is why I sometimes hate the MAS community.

**Comment by TheSystemGuy1337** [comment]
Anyway, screw the toggle switch and my hopes and dreams of not having to pull my hair out over 24 time, since this good idea has gone straight to hell.
