### ISSUE TITLE
Monika won't notice specific gifts

### ISSUE THREAD

**Issue by doinkadoink** [Monika-After-Story/MonikaModDev#9868]
I was adding new hairstyles in Monika's folder when this started,
I don't know what I did wrong, but monika won't notice "coffee.gift" "hotchocolate.gift", or "cupcake.gift" anymore in the characters folder.
She notices literally any other gift: roses, fudge, chocolate, even if i just gift "afgfbsfhr.gift" she notices that it's there.
Can anyone help me out?

**Comment by Booplicate** [comment]
Have you changed time on your computer while MAS was open?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
