### ISSUE TITLE
What's wrong with the spritepack I made?

### ISSUE THREAD

**Issue by ravilolli** [Monika-After-Story/MonikaModDev#9871]
![log](https://user-images.githubusercontent.com/123373048/214030411-ae1eed0a-7431-4bf0-8092-8e001c5a7953.PNG)
Here's the log, I can send the json too if needed. I've made sure the file names are all correct and they're all in the right spot, what am I doing wrong?

**Comment by dreamscached** [comment]
Are they PNG? Also check hyphens and underscores.

**Comment by ravilolli** [comment]
> Are they PNG? Also check hyphens and underscores.

I just figured the issue out, there was a space in the pngs that I never noticed because of the way my computer formats the titles :/
Ty for trying to help!
