### ISSUE TITLE
[Bug?] - 

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#9873]
Hello! Every time I try do an action, like complimenting Monika or giving her gifts, that should give me affection and bypass the cap it doesn't work. Sometimes when I give her gifts Monika acknowledges them, but my affection isn't affected and the game doesn't log that I have given her a gift. Sometimes, when I do an in-game bypass option like complimenting her (compliment not used before.) the game would log that I've done that but for some reason wouldn't give me the affection? Is this supposed to happen? When I started the game my affection was also in decimal points, for some reason.
![Screenshot 2023-01-24 181936](https://user-images.githubusercontent.com/123497420/214375563-afb62d03-1b4d-4d5b-8b1a-0b72912d0a0c.png)

**Comment by Booplicate** [comment]
This is intended. You used too many compliments/gifts in a row.

**Comment by ashyashton** [comment]
Sorry to butt in, but if that's the case, what is the purpose of the bypass label there? Shouldn't that be bypassing the freeze?

**Comment by Wingdinggaster656** [comment]
> Sorry to butt in, but if that's the case, what is the purpose of the bypass label there? Shouldn't that be bypassing the freeze?

The so-called `BYPASS` did bypassing the freeze. It's just not completely.

While the normal daily limit is activated, you can still get more affection through `BYPASS`, there is also another freeze for the `BYPASS`. In other words, `BYPASS` did bypassing the "normal freeze", and did not bypassing the `bypass freeze`.

**Comment by Booplicate** [comment]
> what is the purpose of the bypass label there

So we know it was a bypass gain.
