### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0mniSci** [Monika-After-Story/MonikaModDev#9876]
I've been receiving this error randomly when opening MAS. Sometimes it doesn't pop up, and sometimes it does. It doesn't seem to cause any problems with opening MAS either way, but I want to know what is causing this and how to fix it just in case something worse happens. Thanks! 
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/10498765/traceback.txt)

**Comment by Booplicate** [comment]
Were you launching multiple instances of MAS? Or quickly relaunching it after closing?

**Comment by 0mniSci** [comment]
No, just launched it normally

**Comment by dreamscached** [comment]
To be resolved in #10037.
