### ISSUE TITLE
[Possible Bug?] Monika only ever changes into 2 outfits

### ISSUE THREAD

**Issue by CloakedGhost** [Monika-After-Story/MonikaModDev#9882]
The auto outfit change was implemented into MAS, correct? If not then this issue can be closed and I will ask in the submod github.

Anyway, my Monika only changes into 2 outfits and completely ignores the other ones. I don't know why that is, is there an easy fix?

**Comment by dreamscached** [comment]
As far as I know it was never implemented in MAS itself, no.

**Comment by Booplicate** [comment]
It's not part of MAS yet. You're probably misconfigured it.

**Comment by CloakedGhost** [comment]
Ah I see, I only remembered that some submods where merged into MAS, but couldn't remember if this was one of them. Thanks.

**Comment by Booplicate** [comment]
Only "enhanced idle" has been.
