### ISSUE TITLE
player nickname issue

### ISSUE THREAD

**Issue by Mudkipgirl** [Monika-After-Story/MonikaModDev#9883]
I installed the Memories of Self-Care & Literature and the Presence Submod and now this appeared when I said I was feeling sniffly, what happened?
![Uploading 62db491a-36fe-4025-894c-780bc71128fa.jpg…]()

**Comment by dreamscached** [comment]
Your image didn't upload properly, plus issues about submods don't belong here. Consider asking on Reddit or on Discord.
