### ISSUE TITLE
[Suggestion] Monika tells the player who's going first in NOU

### ISSUE THREAD

**Issue by arbabf** [Monika-After-Story/MonikaModDev#9885]
Title - I assume it's random, but because of human bias and no concrete way to tell who's going first I always assume Monika's getting the first turn when it benefits her and me when I get shafted (e.g. a skip).

**Comment by Booplicate** [comment]
She actually tells you if it's your turn
https://github.com/Monika-After-Story/MonikaModDev/blob/9e91075e11c0590decd49edcc976ba62eb67b999/Monika%20After%20Story/game/zz_cardgames.rpy#L147-L151

**Comment by arbabf** [comment]
Excuse my ambiguity - I meant an indication of who's going first before the NOU game begins.

**Comment by Booplicate** [comment]
You mean how it's being selected? The winner of the last game will have the first turn.

**Comment by arbabf** [comment]
Oh, really? I never picked that up.
> You mean how it's being selected?

I meant more in the realm of Monika saying 'Hey, you're going first' before the NOU starts while in the spaceroom, when you confirm starting the game.
In this case, ideally, it would be 'You won last time, so you're going next.' or along those lines.

**Comment by ThePotatoGuy** [comment]
not sure if that line is necessary but we'll put it to consideration.

[closing until we look into it]
