### ISSUE TITLE
[Bug] - Tried to install a location mod, got two errors idk how to fix?

### ISSUE THREAD

**Issue by Nenekuu** [Monika-After-Story/MonikaModDev#9886]
Problem's in the name, I have no idea what I should do with these two issues? Game is completely softlocked until this gets sorted out ;-;
First screenshot is on trying to boot the game, second is on trying to reload a previous state
![Capture](https://user-images.githubusercontent.com/124254902/216299391-6bf69a11-8e7d-4087-bd1b-20c476e3bb03.PNG)
![Capture2](https://user-images.githubusercontent.com/124254902/216299504-52c3b79c-b14e-4da5-a5af-fdbf4447b538.PNG)

**Comment by dreamscached** [comment]
Check if you have another location with the same name anywhere. You likely have another Playroom location already installed.

**Comment by Nenekuu** [comment]
> Check if you have another location with the same name anywhere. You likely have another Playroom location already installed.

Just tried that, I found a file called "playroom.rypc" and deleted that, also deleted the Day variant of the background but it still pulls the same error, where else besides game and submod_assets should I look?

**Comment by Booplicate** [comment]
This is not a bug, you incorrectly installed the submod. The submod author can provide additional support if you need it.
