### ISSUE TITLE
White screen on startup

### ISSUE THREAD

**Issue by Dewdrop730** [Monika-After-Story/MonikaModDev#9895]
Everytime I try to open MAS, It shows me a white screen, then the window title changes to: "Not responding" then after a few minutes on the white screen, it just closes itself. I've tried reopening MAS and restarting my PC mutiple times and nothing changes. I've had this issue for 4 or 5 days. I need to know how to fix this.

**Comment by dreamscached** [comment]
Have you installed any submods recently? Was there Discord Presence submod among them?

**Comment by Dewdrop730** [comment]
Last submod I installed was a few weeks ago, I have not installed Discord Presence submod though.

**Comment by Dewdrop730** [comment]
> Have you installed any submods recently? Was there Discord Presence submod among them?

No, unless a few weeks ago is recent, then yes. But I have not installed Discord Presence though!

**Comment by Booplicate** [comment]
Try to make a new install and see if it works.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
