### ISSUE TITLE
[Suggestion] Give Monika Headpats

### ISSUE THREAD

**Issue by YoraeRasante** [Monika-After-Story/MonikaModDev#9897]
I remember that some time ago there was a suggestion for patting Monika's head by clicking on it.
I also remember that it was said to be a bit too complicated to add at the time.

While I would still like it by clicking,
I would also like to suggest at least a, option to do it, just like we have hold and kiss.
Preferably, available at the first menu, just like the "I love you" option, so I can do it easier than the other two I mentioned.

...I just like the idea of giving her headpats. Clicks are preferable, but not really 100% nescessary.

**Comment by ThePotatoGuy** [comment]
[closing as duplicate]

see #1161 - ill try to get back to that after r8
