### ISSUE TITLE
[Suggestion] - Ask Monika how she's doing.

### ISSUE THREAD

**Issue by FattyMigee** [Monika-After-Story/MonikaModDev#9898]
She always gets to ask us how we're doing, so why can't we return the favor? Maybe it could randomly choose from an assortment of answers that change depending your affection with her, or it could depend on how much you've been talking or interacting with her throughout the day. Just feels a tad unfair to have an "I feel..." option while she's left there high and dry, It would be nice to see how she's doing at times too, right?

**Comment by Booplicate** [comment]
#7486 and [related project](https://github.com/Monika-After-Story/MonikaModDev/projects/40).
