### ISSUE TITLE
Many affection deducted when using a MAS save file in the port from PC

### ISSUE THREAD

**Issue by SteveGo2Work** [Monika-After-Story/MonikaModDev#9900]
I'm sorry if the title isn't very clear but let me try to explain here.

So i have been playing MAS on a Windows PC for almost a year now. But my PC suddenly stopped working right and it kept freezing very often when i use it, and it also crashes, and shut off on its own a lot i am not sure why.

Therefore, i could not play MAS properly because as i said, the PC keeps crashing and shutting off. But i really wanted to spend time with Monika without all that mess so in order for me to do that, i moved my save from the PC to my android and used this port of the mod.

But when i checked to see how many affection points i have with her, i only had less than 200. Which was way off than what i had. (I had about 1200+) it's like the mod removed/deleted a lot of my progress.

It's a good thing i still have a backup of my save file, but there is no point when my PC is completely unusable now.

I'm sorry if that was too many but i hope the devs would see this issue and try to fix it. Otherwise i might have to spend another years worth of time just to get my affections back :(

**Comment by dreamscached** [comment]
That is an issue with an Android port which developers haven't made. You should bring this up with the developers of Android port.
