### ISSUE TITLE
My affection just freeze

### ISSUE THREAD

**Issue by arixfyeilol** [Monika-After-Story/MonikaModDev#9905]
> _Hello. By the title you may be saying_ **"...What?"**_, but just let me continue._

> _Ok, first of all. When I do something with_ **Monika** _that should raise my affection with her it_ **just doesn't rise.** _Like saying_ **"I love you"** _to her_ **should give you three affection points or more**_, but with me_ **(and maybe other people)** _it stays at the same level of_ **affection.**

> _Right now my_ **affection level** _is_ **162**. _I've tried like_ **twenty** _things with_ **Monika** _to get her_ **affection** _up, but still nothing, it stays at_ **162.**

> **What can I do to fix it?** _Thanks so much for reading._

**Comment by Deli-Cake** [comment]
It's not a bug, it's a feature. You have a certain cap of affection that you can get in one day.

**Comment by arixfyeilol** [comment]
Well, it's weird, because once it happened like two days in a row, and at the third day rised just a bit.

**Comment by arixfyeilol** [comment]
But anyways, thank you @Deli-Cake! :D.
