### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Gamemaster5801** [Monika-After-Story/MonikaModDev#9907]
Sup, i just want to ask if so much affection  decimals in MAS is normal.
Here is my affection log:

[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/10736436/aff_log.log)

Sorry if im wasting your time just wanna be sure.

**Comment by Booplicate** [comment]
Yes, it's just a number.

**Comment by Gamemaster5801** [comment]
thank you
