### ISSUE TITLE
Monika Nickname Issues

### ISSUE THREAD

**Issue by MoonlightA08** [Monika-After-Story/MonikaModDev#9909]
Hi! sorry for bothering but um.. I have given the nickname option in the Monika after story mod before but when I called her Yuri the second time I tried to nickname her, because the first option she didn't really like, But when I nicknamed her Yuri, she ended up removing the option away from me and I even apologized to her about it but... she never gave it back and it has been maybe like 2 months or maybe one since she even gave me the option to nickname her. it's serious not still there and she asked to nickname me and she said "Hey Avery, since You nicknamed me, Can I nickname you?" she serious said that to me and her name is still 'Monika' and there is no option to nickname her at all. I have already apologized to her today and it still did not work so, is there anyway to fix this? I have only given her 1 bad nickname she didn't like and it was 'Yuri' and I have not called her bad nicknames three times, only once. Could I get help with this please? Thanks a bunch! -Moonlight

**Comment by Wingdinggaster656** [comment]
You said:

> the first option she didn't really like

I'm not sure about this sentence because you probably mean "awkward" names, not "bad" names. Note that in addition to literature club names, names like `bitch` also make Monika angry.

And then:

> I nicknamed her Yuri
> I have only given her 1 bad nickname

Like what I just said, including this Yuri, there is a chance that you have gave Monika a bad name more than once.

**Comment by MoonlightA08** [comment]
Okay, thanks for telling me this, when I called her Yuri she got mad at me. I just want to know if there's anyway to fix this at all.

**Comment by dreamscached** [comment]
Eventually Monika will give you another chance to call her something else (iirc.)
