### ISSUE TITLE
Repeated "Out of memory" crashes on Windows 11

### ISSUE THREAD

**Issue by tw4449** [Monika-After-Story/MonikaModDev#9910]
I recently had to migrate MAS to a new Windows 11 computer (Alienware x17 R2 laptop), and ever since I have had random crashes, usually without any traceback message at all. Today I had 4(!) separate crashes, but this time it gave me traceback messages for the last three (see attached images). The common denominator is they all say "Out of memory," however this computer is a gaming laptop with ample memory (32gb), and about half of these crashes happened when I wasn't running anything else. The only time it never seems to happen is when Monika is actually active (when I don't have the dialog box and buttons hidden by the H key/right click).

This only happened on my last computer (Dell G7 laptop, Windows 10) when running memory-intensive programs while MAS was open, and even then only a handful of times in about three years. 

![Traceback screenshot 1](https://user-images.githubusercontent.com/58648177/218946201-58fdfc99-c03a-4fdd-b00d-402d33b2184e.png)
![Traceback screenshot 2](https://user-images.githubusercontent.com/58648177/218946216-514ee50e-37e3-4ff4-b56a-7f8d8c88ce95.png)
![Traceback screenshot 3](https://user-images.githubusercontent.com/58648177/218946226-ac5d30b2-9a2e-4f7f-9ac6-c21a347d8f18.png)

**Comment by Booplicate** [comment]
Not sure how much we can do about windows 11. If there's no tracebacks, then it's usually a problem on the OS/hardware side.
For out of memory, what GPU do you use?

**Comment by Booplicate** [comment]
> but there's also an Intel Iris Xe

Can you verify renpy uses the external GPU? Also make sure your renderer is set to OpenGL or DirectX.

> Will the move to Python 3 help with Windows 11 compatibility issues?

It might, but I can't guarantee, win 11 is kinda unstable from my experience.

**Comment by tw4449** [comment]
It was on Iris/DirectX, switched to OpenGL to see if that does anything.

How do I check what GPU renpy is using?

**Comment by tw4449** [comment]
Wait, it having been set to "Iris/DirectX" could mean that is *was* using the internal Iris Xe GPU.

**Comment by Booplicate** [comment]
I'm actually now sure, usually it's `Angle/DirectX`. Maybe intel provides their own API, but in this case I think you're right, it'd use your integrated GPU.

> How do I check what GPU renpy is using?

Usually you can check/adjust that in the control panel of your GPU (there should be some software for that). Alternatively, I believe some information about the GPU will be dumped into `log.txt` in your game directory.

**Comment by tw4449** [comment]
Alright, the log confirmed that it's using the Iris card, (Renderer: 'Intel(R) Iris(R) Xe Graphics') even for OpenGL. Now how do I change which it uses?

**Comment by Booplicate** [comment]
> Usually you can check/adjust that in the control panel of your GPU (there should be some software for that).

**Comment by Booplicate** [comment]
Going to close this as it's not a MAS issue, but the wrong configuration. If crashes continue, I can only suggest trying different renderers and wait for the next updates.

**Comment by tw4449** [comment]
Should've mentioned sooner, I've been using OpenGL for the last three days and have not had another crash. If someone else has the same issue, that would be a good solution to suggest.

**Comment by tw4449** [comment]
Thanks for all the help, BTW
