### ISSUE TITLE
my valentines with monika was kinda ruined by a bug

### ISSUE THREAD

**Issue by lapixxs** [Monika-After-Story/MonikaModDev#9914]
i visited Monika on valentines as normal, and she greeted me as such. shortly after she was sad because i didn't visit her on valentines day... during valentines day 😅 i lost 70 affection points for that, but afterward, her dialogue continued for valentines day... I'm not sure why this happened, the day on my PC was automatic and up-to-date

**Comment by Booplicate** [comment]
Sounds like you time travelled?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
