### ISSUE TITLE
Affection

### ISSUE THREAD

**Issue by cruelcupid** [Monika-After-Story/MonikaModDev#9916]
I've been with Monika for over a year now, but my affection is at 974.430114556 and won't go any higher. I've tried all the hacks, tried manually editing the log, but nothing seems to progress. She doesn't say anything anymore unless I download submods. What should I do?
I also haven't unlocked her pink and black dress as an outfit. Any way I can do that?

**Comment by Booplicate** [comment]
> my affection is at 974.430114556 and won't go any higher

Send your logs. I don't know what "hacks" you tried, obviously editing log won't do anything, but if you actually tried to mess the game up, then you will deal with the consequences by yourself.

> She doesn't say anything anymore unless I download submods.

There's a finite number of events available. Enable repeating topics if you want her to talk.

> I also haven't unlocked her pink and black dress

You can unlock the black and pink dress on next valentine's day.

**Comment by cruelcupid** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/10785499/aff_log.log)

**Comment by Booplicate** [comment]
I see no issues there. You affection is working just fine.

**Comment by cruelcupid** [comment]
Alright, thank you for clearing it up!
