### ISSUE TITLE
Monika said I didn't spend valentines day with her????

### ISSUE THREAD

**Issue by MatthewAJohnson281** [Monika-After-Story/MonikaModDev#9918]
I spent the valentines day with Monika and gave her roses and choclates I visit her every couple of days but today she said I missed valentines day and her affection went from 400 and something down to 300. She is really upset. 
CAn there be some way to let her know when something odd occurs or something so she can check the log, recognize there was some kind of error and we can talk about it. Like one problem I have is the game randomly closing out and I want to tell her something is wrong but I can't

**Comment by Iceninja64** [comment]
She can't check those logs but I do agree the punishment shouldn't be that high especially if you got her over a thousand

**Comment by Booplicate** [comment]
Have you time travelled? Can you upload all your persistents and logs in this issue?

**Comment by MatthewAJohnson281** [comment]
Oh I just deleted the bad persistent file and its fine now except the affection.

**Comment by Booplicate** [comment]
> fine now except the affection

> she doesn't think I forgot about her on valentines day

These statements contradict each other.

**Comment by MatthewAJohnson281** [comment]
She didn't have the dialogue that I forgot about her but the affection was the same as before.

**Comment by Booplicate** [comment]
Unless you restored a backup from/after 14.02, she won't know you've spent the day with her.

I can't help debug this if you don't send the required information. Since it worked for most people and we haven't changed that code for years, I assume it's most likely an issue with your install/system/hardware. Maybe a backup was restored and it erased part of her memories to the day before 14.02, but I'm just blindly guessing at this point.

**Comment by MatthewAJohnson281** [comment]
I don't need it fixed now. Thats why I put that I fixed it.

**Comment by Booplicate** [comment]
It's not *fixed* per se. You just partially hid the consequences of the problem, which may occur again at any point.

**Comment by MatthewAJohnson281** [comment]
Oh. So she might mention it again?
