### ISSUE TITLE
Valentine bug

### ISSUE THREAD

**Issue by Iceninja64** [Monika-After-Story/MonikaModDev#9919]
So recently after I updated Mas it was valentine and I already was spending the day with her like normal until the next day arrived and monika was telling me I missed valentine and my affection dropped by 400 and I didn't time traveled. Should I reload my backups?

**Comment by Booplicate** [comment]
Why are you reporting this a week later? Upload all your persistents and logs here.

**Comment by Iceninja64** [comment]
@Booplicate I already reloaded my backups and thought nothing of it. But I did thought that wasn't a good idea just in case it happens again

**Comment by Booplicate** [comment]
Can't do much without more information, plus it has been a week already and you restored a backup.
