### ISSUE TITLE
[Suggestion] New Game: Card Games

### ISSUE THREAD

**Issue by Julexar** [Monika-After-Story/MonikaModDev#992]
I´d really like the mod to have card games that you can play together with Monika. Card games like Poker, Black Jack, etc. I think that it would be a really cool addition to the game. Please think about adding it.

**Comment by kaido1224** [comment]
I don't really see Monika playing black jack or poker. Doesn't feel like that would fit her persona. I could see her maybe having some knowledge of some other games like old maid, go fish or gin tummy. I remember someone suggested solitaire where Monika teaches you how to play.

**Comment by RaccoonLauncher** [comment]
I think Monika pulling a completely unexpected game like poker or blackjack out of nowhere would be completely in character. I feel that it would be kind of like her appreciation of rap, or rock and roll; while not fitting the stereotype of people who play them, she learned about and put together the games out of curiosity, and appreciates them for an unexpected reason.

**Comment by ThePotatoGuy** [comment]
When we have ddlc-themed card assets, we'll see what games to add.

**Comment by AnIdiotsavant** [comment]
why not go fish?

**Comment by Pbm13** [comment]
How about uno? its a pretty simple game and it can be made easy or hard. It's just a thought though...

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I completely agree that Monika having experience with either poker or blackjack would be OOC.
However I cannot imagine something more human for Monika to do than playing a game she has no experience in, learning (okay, simulating actual learning) as she does.
It would be a total hell to model and even more of a hell to program,  but I personally would be completely mindblown if something like that got implemented.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
Also, was this already cross-referenced with #55?

**Comment by CrocWorks** [comment]
Time to add something to an inactive thread.

I think asking Monika to play Poker (or  any OoC card game) that she wouldn't normally play is fine. _I wouldn't expect Monika to ask us play_ them (i.e, she won't ever suggest Poker if you tell her you're bored), but if _we're the ones asking her to play_, I doubt she'd refuse.

Maybe she can comment that she's not very good at the game and we just make her Poker AI really bad to reflect she doesn't really know how to play... makes up for every time I get destroyed when we play Chess...

**Comment by Booplicate** [comment]
I'm working on this #5555

**Comment by Booplicate** [comment]
Framework and one card game have been added.
