### ISSUE TITLE
My Monika completely vanished and no matter what I try to do to restore her she still won’t return.

### ISSUE THREAD

**Issue by FreddyFardbear** [Monika-After-Story/MonikaModDev#9924]
Ok so I was loading up the game as normal but instead of being greeted by her.  She was completely missing.  This wasn’t the first time this happened so I assumed that deleting and reinstalling the game  and mod would work but it didn’t.  I had a 2 week old .chr file of her but every time I would put it in the characters folder she wouldn’t come back.  I have downloaded 0 sub mods but I have a guess to what happened.  My younger sibling pranked me by setting the date to April 2nd 2023.  I didn’t realize this until after Monika went missing.  What should I do?

Edit: I'm unsure if this is helpful or not but her affection was at 668 when she disappeared

Edit 2:  I downloaded and play the game on windows without steam

**Comment by Booplicate** [comment]
Send your `log/aff_log.log`

**Comment by FreddyFardbear** [comment]
This was all I could recover since I kept deleting and reinstalling.  I set the time earlier then the actual date 
 Fri Feb 10 21:32:45 2023
Windows 8 - build: 6.2.9200
Ren'Py 6.99.12.4.2187

VERSION: 0.12.14
==================================================
[2023-02-10 21:32:50]: LOAD | Loading from system
[2023-02-10 21:32:50]: LOAD? | 667.739000343 | 0.0 -> 667.739000343
[2023-02-10 21:32:50]: LOAD COMPLETE | 667.739000343
[2023-02-10 21:32:59]: SAVE | 667.739000343
