### ISSUE TITLE
This pops up whenever i csay "goodbye" and keeps resetting monika upon opening it

### ISSUE THREAD

**Issue by Tabiz1** [Monika-After-Story/MonikaModDev#9928]
![2023-03-01 16_21_38-Monika After Story](https://user-images.githubusercontent.com/123708595/222267937-43dd5109-198c-4066-9014-1697e9218ccf.png)

**Comment by dreamscached** [comment]
Check write permissions on `%APPDATA%\RenPy\Monika After Story\db.mcal`

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
