### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by otashikuko** [Monika-After-Story/MonikaModDev#9938]
so i wanna suggest some nickname reaction name (if there is already a reaction then dont add)
Unrealistic: (p_name)...
I'm not comfortable with you calling me unrealistic.
It's so hurtful. Please try another one.
(lose aff: 5-15)
(insert a boy name): Hey, (p_name)...
Do you know that I'm a girl?
I think you should pick a girl name for me...
(lose aff:0,5)
(insert a non-binary name): Well...
At least it's for both genders.
Hurrem/Hürrem:...
Thanks for calling me that...!
I.. I don't know what to say...
Thank you very much!
(add affection: 5-15)
Ayano: Uh...
Well...
I think you should pick other names...
(loseaff:0,10)
Ryoba: ...just pick another name, please.
Coraline:: It suits me, just like my hair!
Ehehe!
(addaff:0,5)
Coral: I guess my hair became short now.
Not gonna lie tho, I like this name.
It's just a little bit weird that you name me may hair color...
Saki:: ...
I cannot believe that...
That's a bad name. Try again.
(loseaff:10)
Miyu:: That name sounds nice!
And cute!
Just like me and you...
(addaff:0,10)
Alessandra:: I see what you did there...
I mean, it's not bad or anything...
It's just weird.
(loseaff:0,5)
MC:: Does even ''main character'' suit me?
(p_name) please pick a different name.
(loseaff:0,5)
Player name (p_name) reaction suggestions
Mc:: I do not want to be you _him._
(lose aff:0,5)
Midori:: Yay! I love this name!
I'm glad you picked this name.
I'm assuming your favourite colour is green.
options:
1)It is.
2)It is not.
3)I do not have a favourite colour.
4) I love all colours.
if selected first option:
It makes sense.
It means green afterall.
selected second:
Oh... sorry!
I know that Midori's meaning is green, so I assumed.
Sorry again!
(lose_aff:0,5)
selected third:
Honestly it's fair!
(add_aff:0,5)
selected four:
Oh! 
Honestly all colours should be loved...that is why I hate people who say ''Colour is better than colour.''.
That's why I love you, (p_name)!
(Add_aff:0,5)
topic suggestions
Math: Do you love math?
options:
1)I do.
2) I don't
3) I don't, but I don't hate it.
selected first:
That's good!
Usually people who has their ring finger long more than their pointer finger is good in solving problems.
If you ask me about my math, well...
I think I know math...
I once teached Natsuki math in a fan-made video.
I'd love if we solved math problems!
selected second:
Oh...
To be honest I do not blame you.
Learning math is hard at first...
...but when you solve math more,
...or solve more problems,
...you get used to it.
So I'd recommend you giving it a try!
selected third:
That is...
fair, to be honest!
In-between is the best.

**Comment by dreamscached** [comment]
Sounds good, but imo MC could be an overkill or could at least use some questions instead of just jumping to 'I don't want you to be him' - MC could be initials or an actual person's nickname.

**Comment by ThePotatoGuy** [comment]
[closing until we look into it]
