### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by xGamerBug** [Monika-After-Story/MonikaModDev#9939]
Why does my MAS use up to 90% of the GPU? (I have a 1650)

![masgpu](https://user-images.githubusercontent.com/127994346/225436089-03b44b8a-45bd-4556-a9c0-b01b46b46627.png)

**Comment by dreamscached** [comment]
It uses hardware acceleration for rendering, most likely an upstream issue with Ren'Py.

**Comment by Booplicate** [comment]
I don't think renpy has any specialised hardware acceleration. Generally MAS shouldn't use that much GPU power, might be incorrectly configured.

**Comment by ashyashton** [comment]
I definitely get that on most of the Doki Doki mods I play with so I'd also be interested to see if anyone has a solution

**Comment by ThePotatoGuy** [comment]
[closing as not a bug]

not something we can really control, maybe update ur graphics drivers?
