### ISSUE TITLE
[Bug] - cant change monika's hair

### ISSUE THREAD

**Issue by otashikuko** [Monika-After-Story/MonikaModDev#9943]
im at 239 affection and still i cant change monika's hair, i didnt experienced this before, i know she changes her hair at startup but she never did even tho im at 239 affection, i will show a screenshot if wanted

**Comment by Booplicate** [comment]
Can you upload your `aff_log.log`?

**Comment by otashikuko** [comment]
i cheated aff _once,_ so it looks complicated (just ignore the ones after the '' . ''). if not i could show it in the game (extra+)

**Comment by otashikuko** [comment]
> i cheated aff _once,_ so it looks complicated (just ignore the ones after the '' . ''). if not i could show it in the game (extra+)

btw the cheat failed but aff.log is still complicated

**Comment by Wingdinggaster656** [comment]
Are you using any translation?

**Comment by otashikuko** [comment]
nope

**Comment by otashikuko** [comment]
just the english version, nothing else

**Comment by Booplicate** [comment]
It's not a bug if you tried to cheat and messed up event data yourself. For normal progression the events work.

**Comment by otashikuko** [comment]
but i dont think it has to do anything with hair (i cheated script-compliments)
