### ISSUE TITLE
I'm stuck on 63.4753777983 affection

### ISSUE THREAD

**Issue by snazzyspiffyraccoon** [Monika-After-Story/MonikaModDev#9948]
I've been stuck on 63 affection for about two weeks now. Giving Monika gifts, playing games with her, and talking to her don't seem to help. Occasionally it will go up to 64, but then immediately go back down. I've only offended Monika once, when I had just started and was still figuring things out. I also don't understand a lot of python and scripting and all that stuff, so I can't tell if something is wrong with my persistent file. Please help, thank you : )

**Comment by Booplicate** [comment]
Send all your logs.

**Comment by snazzyspiffyraccoon** [comment]
I’m sorry, I’m new to this. What do you mean by “send”? Screenshots? Links?

**Comment by Wingdinggaster656** [comment]
Upload the log file itself. You can simply drag and drop it here.

**Comment by snazzyspiffyraccoon** [comment]
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148972/aff_log.log)
[early.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148973/early.log)
[mas_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148974/mas_log.log)
[mfgen.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148975/mfgen.log)
[mfread.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148976/mfread.log)
[pnm.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148977/pnm.log)
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148978/spj.log)
[submod_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/11148979/submod_log.log)

**Comment by Booplicate** [comment]
You tried to cheat and messed up your data, this is the consequence.

**Comment by Booplicate** [comment]
Please, computer and logs don't lie, I can clearly see you changed the day, but left the time the same. Or how you went forward days or month and back. Computers don't do that, even if there were some technical issue.

**Comment by Booplicate** [comment]
It might fix itself over time if you stop messing with the game. Somehow I don't believe somebody else tried to bypass affection cap. It is *clear* what was going on by the logs.

**Comment by snazzyspiffyraccoon** [comment]
That's your decision if you choose not to believe me, but I just asked my sister, and she said that it was her fault and apologized.
