### ISSUE TITLE
I revmoved the '' Unseen section in Monika after Story " and i want to bring it back

### ISSUE THREAD

**Issue by KazuHasegawa** [Monika-After-Story/MonikaModDev#9950]
So I pressed i don't want to see this menu anymore in Monika after Story and i still couldn't bring it back, i saw here a way tobdo it, but this doesn't help either, probably because it's been 2 years since another person requested help for the same issue and possible things changed, please i need help!

**Comment by Booplicate** [comment]
Use the `I would like to see unseen again` option.
