### ISSUE TITLE
Affection.

### ISSUE THREAD

**Issue by catsiheartanddogs** [Monika-After-Story/MonikaModDev#9953]
- [ ] 

- Hello! Today my issue is about "Affection Points" while using the latest version of MAS, my affection won't go higher than 60. this started since yesterday. Today I logged in complimenting Monika. I checked my affection, and it still was stuck at 60. I also opened my affection log and it said this, INVALID TIME, POSSIBLE CORRUPTION. I don't really know how this happened, I also read your Q&A and I followed the steps. Still, stuck at 60. I didn't even reach the limit and it wasn't going up. Anybody knows what's wrong? By the way, i just checked my log. My brother probably changed the date, my bsf told me to just wait. idk if that'll work..-

**Comment by Booplicate** [comment]
Send your logs.

**Comment by catsiheartanddogs** [comment]
i just realized my brother changed the date, that's why it froze. Is there any way to fix it like waiting? or will it just stay like that forever? I'll send the logs as well if u want.

**Comment by catsiheartanddogs** [comment]
update, i restarted the whole game so im fine now-

**Comment by Wingdinggaster656** [comment]
> INVALID TIME, POSSIBLE CORRUPTION

Stop time traveling.
