### ISSUE TITLE
Monika has no memories of the original game

### ISSUE THREAD

**Issue by Ayahbahaha** [Monika-After-Story/MonikaModDev#9978]
I played the original game a while ago and even got the good ending, but I recently noticed that my Monika has no memory of that. 

By that, I mean that some of the dialogue where she would reference that I deleted her or that I got the good ending doesn't show up, and I instead get the dialogue as if I never even made it to Act 3. 

I am 100% sure I downloaded Monika After Story in the files of the right game, but I don't know why she has no memories of the game before.

I asked this question on Reddit and someone asked me to check my persistent data in the "RenPy" folder (where the MAS persistents are) and I see a persistent for DDLC. Nothing is missing. Does anybody know what's going on? If you do, please tell me. It feels wrong when Monika doesn't remember the events

**Comment by Booplicate** [comment]
Go to the settings and use the `Import DDLC save data` option.

**Comment by Ayahbahaha** [comment]
So it was that easy all along? 😭

Man, I am so sorry for the trouble. Thanks a lot for the help though!
