### ISSUE TITLE
Moni can see whether or not you have other after-story mods open?

### ISSUE THREAD

**Issue by LitKitten** [Monika-After-Story/MonikaModDev#9986]
This has probably been asked a lot, but what if Monika was able to see that you had other After-Story mods open and make some kind of comment on it? Maybe even change certain topics based on who's listening...

**Comment by dreamscached** [comment]
No, it does not detect other mods without user-made submods installed.

**Comment by ThePotatoGuy** [comment]
no plans to do other mod detection at this time.

[closing as rejected]
