### ISSUE TITLE
Sprite packs aren't being read

### ISSUE THREAD

**Issue by GlitchedBoi** [Monika-After-Story/MonikaModDev#9988]
I downloaded the deluxe version of MAS which is meant to have them pre installed, but the game doesn't seem to recognize them. (heres the [spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/11411262/spj.log))

**Comment by dreamscached** [comment]
- Don't use steam
- Spritepacks appear to be loading normally, check if you enter gift names properly.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
