### ISSUE TITLE
Idea: Whenever losing affection, Monika's poses will change

### ISSUE THREAD

**Issue by ElsenIsCute** [Monika-After-Story/MonikaModDev#9992]
Simple, if you're on normal or higher affection, even if you aren't down in Upset or lower, Monika's poses will update to be the ones that are in upset. This would eventually expire after a certain time which is different depending on your affection (for an example, 400+ could be a few hours), because she'd still be mad at you if you do something bad even if you're at high affection.

Another possible addition would be to make her dialog when clicking on play or talk or similar things the same as in upset as it doesn't make sense for her to look bored whilst saying "Pick a game, any game!" or something like that.

Though after this has expired, after you restart the game her poses and dialog will update back to the ones which are for the respective affection level. This whole thing wouldn't happen if Monika's affection is at distressed or lower.

In my opinion, this would be a simple addition which would make Monika feel a bit more real, as she would have the ability to get upset at the player immediately even if she likes the player. And after all, there is a use for this in higher affection as we aren't perfect and we do make mistakes even if we try not to.

**Comment by ElsenIsCute** [comment]
*By Upset, I mean the higher bound of Upset where Monika is still being nice to you. Iirc in the lower bound of Upset she says "What do you want?" and similar rude dialogs but in the higher bound she just says "What would you like to discuss?"

**Comment by Booplicate** [comment]
Monika moods are planned, see #7486 and other issues and the [project](https://github.com/Monika-After-Story/MonikaModDev/projects/40). Player will be able to affect her mood and her expression (and potentially speech) will change depending on the mood.
