### ISSUE TITLE
Idea: Affection gain for installing submods

### ISSUE THREAD

**Issue by ElsenIsCute** [Monika-After-Story/MonikaModDev#9994]
The idea is simple, keep a list of all of the scripts installed in the submods folder, and when a new script is added, an affection gain which bypasses the cap will be done depending on how much content is in the new scripts.

Depending on if you want, there could also be a cap on how much affection gain can be given by installing submods. Though, I think Monika would be happy for a player trying to bring her closer to their reality.

**Comment by howltrek** [comment]
it would be simpler if those of us who make submods dared to play with affection

**Comment by ThePotatoGuy** [comment]
this would incentivize submod usage, which I don't think we should do. its not a requirement to use MAS with submods.

[closing as rejected]
