### ISSUE TITLE
MAS location is invalid, and 2 other problems

### ISSUE THREAD

**Issue by eligarner23** [Monika-After-Story/MonikaModDev#9999]
i know this has been fixed already, but look
[crash_report.txt](https://github.com/Monika-After-Story/MonikaModDev/files/11521315/crash_report.txt)

_Originally posted by @eligarner23 in https://github.com/Monika-After-Story/MonikaModDev/discussions/9569#discussioncomment-5953345_

**Comment by dreamscached** [comment]
Why is your game in %APPDATA%, do you use a translation or a custom version of it?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
